### ISSUE TITLE
Text input callback is called way too many times

### ISSUE THREAD

**Issue by Wizzard033** [ocornut/imgui#1001]
I noticed that the console example spams callbacks, and so I can't smoothly scroll through history.
This is due to the fact that the key is queried every frame:
`if ((flags & ImGuiInputTextFlags_CallbackHistory) != 0 && IsKeyPressedMap(ImGuiKey_UpArrow))`

I'm not sure if this was a design decision, but the console example doesn't even work right.
I'd imagine that there is supposed to be a key repeat delay for this.

What am I doing wrong? Or does it just work this way?
I'm using release v1.49 with the SDL2 OpenGL3 example.
Unknown if related to #996

**Comment by ocornut** [comment]
There is a key repeat.
It is related to #996 your timestamps are completely wrong so it is repeating every frame given the times you are giving it (it is thinking that 5000 * 1/60 = 83 seconds elapsing every second).

**Comment by Wizzard033** [comment]
I summed every io.DeltaTime every frame for one second starting from program initialization.
The loops add up to 0.559667 seconds, which is to be expected given initialization takes time.
Why is it counting every frame as 1/60 of a second when I'm giving it io.DeltaTime?

**Comment by ocornut** [comment]
You need to figure out your issue at #996 this is very clearly related.
In that issues you stated using a fallback of 1/60 when your values were incorrect, a fallback of 1/60 at 5000 fps will give that sort of incorrect knowledge of time passing to imgui.

**Comment by Wizzard033** [comment]
That's true if the fallback is triggered enough, but it only is triggered on the first frame. As I said, the sum of the variable is less than 1 second, and so I am passing a ton of 0's and small values to represent an accurate passage of time as seconds in io.DeltaTime. I guess I'll just start debugging library code at this point.

**Comment by ocornut** [comment]
In the Demo window, the bottom-most collapsing header shows Inputs/Keyboard info and you can see under "Keys Pressed" what imgui sees according to the corresponding KeyDown[] value + the default repeat rate. The repeat rates are configured in ImGuiIO:

```
float         KeyRepeatDelay;           // = 0.250f             // When holding a key/button, time before it starts repeating, in seconds (for buttons in Repeat mode, etc.).
float         KeyRepeatRate;            // = 0.050f             // When holding a key/button, rate at which it repeats, in seconds.
```

Just to clarify, that `IsKeyPressedMap()` call you mentioned in the first post by default handles repeation according to those repeat rate. So holding a key would trigger 1 press immediately, then a second one after 0.250 seconds, then subsequent ones even 0.050 seconds (~3 frames at 60 FPS).

**Comment by Wizzard033** [comment]
My key repeat delays look fine. I think the issue is when I do io.DeltaTime = 0.

**Comment by ocornut** [comment]
Hows does your application behave if you look at the display at the bottom of ShowTestWindow()?

**Comment by Wizzard033** [comment]
That's what I meant. Sorry. It takes about a second for the delay.

**Comment by Wizzard033** [comment]
It was exactly as I suspected. When io.DeltaTime = 0, key repeat does not work correctly.

    // From ImGui::IsKeyPressed
    const float t = g.IO.KeysDownDuration[key_index];
    if (t == 0.0f)
        return true;

    // From ImGui::NewFrame
    for (int i = 0; i < IM_ARRAYSIZE(g.IO.KeysDown); i++)
        g.IO.KeysDownDuration[i] = g.IO.KeysDown[i] ? (g.IO.KeysDownDuration[i] < 0.0f ? 0.0f : g.IO.KeysDownDuration[i] + g.IO.DeltaTime) : -1.0f;

**Comment by ocornut** [comment]
The library doesn't break at high framerate, but io.DeltaTime should never be 0.0f. Zero is an incorrect input. We chose to assert with >= to make it easier for the first frame but you need to fix your time calculation.

Even at 5000 fps, 1.0f/5000.0f isn't zero.

**Comment by Wizzard033** [comment]
It's incorrect to use a millisecond precision timer and have greater than 1000 FPS with your library?

**Comment by cedriclmenard** [comment]
I get the same behaviour using the SDL2 OpenGL2 demo. No matter what I set as a value for KeyRepeatDelay and KeyRepeatRate, it's always a 1:1 in terms of key input in the InputText field and the frames.

**Comment by jrz371** [comment]
Like @ocornut said, the issue @Wizzard033 and @cedriclmenard doesn't come from framerate or key repeat speeds. They're using the ImGui_ImplSDL2_ProcessEvent incorrectly. Their stuff probably looks something like this.
`
SDL_PollEvent(&event);
ImGui_ImplSDL2_ProcessEvent(&event);
`
SDL_PollEvent returns 1 when there's a new event to process and 0 otherwise. It won't clear the data in the event structure though. So during the next frames the old event data is still in the structure when there's nothing new. This'll then have ImGui process the same event over and over until a new event occurs. Using the timestamp is a hack to get around that core issue. They need to change their implementation to something like this.
`
if(SDL_PollEvent(&event))
{
ImGui_ImplSDL2_ProcessEvent(&event);
}
`
I was banging my head off the wall with the same issue till I read the examples. You can read more in the examples/example_sdl_XXX/main.cpp
