### ISSUE TITLE
InputText: proper way of getting a callback for any pressed key?

### ISSUE THREAD

**Issue by reliasn** [ocornut/imgui#1002]
One of my input texts needs to show the pressed key name according to this list: https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx

So if the user presses 'A', the input text will change to 'A'. If the user presses Control, the input text will change to 'VK_CONTROL'. If the user presses F3, the text will be 'VK_F3'.

To implement that, I need a callback every time there's a WM_KEYDOWN event. A ``ImGuiInputTextFlags_CallbackCharFilter`` callback isn't enough because no chars are entered when certain system keys are used. So I decided to use the flag ``ImGuiInputTextFlags_CallbackAlways`` and have a callback like this:
```c++
char lastKeyDown = 0;

// In my message loop
...
    case WM_SYSKEYDOWN:
    case WM_KEYDOWN:
        lastKeyDown = wParam;  // store the pressed key in lastKeyDown
        if (wParam < 256)
	        io.KeysDown[wParam] = 1;
        return io.WantTextInput;
...

int TextEditCallback(ImGuiTextEditCallbackData* data){
    if(lastKeyDown && data->Buf){
        string keyName = W32::getKeyName(lastKeyDown);  // simply grabs the string name relative to the entered key
        lastKeyDown = 0;
        memcpy(data->Buf, keyName.c_str(), keyName.size() + 1);
        data->BufTextLen = keyName.size();
        data->BufDirty = true;
        data->CursorPos = 0;  // I actually wanted the InputText to lose focus entirely, but this is fine.
    }
    return 0;
}
```
With this implementation, even though ``TextEditCallback`` is called every time the InputText is focused, the ``if`` part is only executed when a key is actually entered. This works very well and I get what I need, but it feels like I'm missing something which makes me wonder if there's a better way to achieve this.

I think the ideal solution here would be a flag that calls the callback every time any key is pressed. This flag would work as a "mid-term" between ``ImGuiInputTextFlags_CallbackCharFilter`` and ``ImGuiInputTextFlags_CallbackAlways``. But since this use-case is so specific, it might not be interesting to have it.

Anyways, I'd appreciate if anyone could give me any inputs on this matter.

Thanks!

**Comment by ocornut** [comment]
This request is really confusing.

Why is an InputText() widget involved at all with what you are doing? It feels like if you want to translate external keys into strings, you can do it in your code and then just display it using any other widgets? Why involving InputText() in the first place? 

Why can't you use `ImGuiInputTextFlags_CallbackAlways` ?

**Comment by reliasn** [comment]
Sorry if I didn't provide enough details. I need an InputText() because the user will click on it and then type a key. As soon as he hits the first key, the translated key name should appear in the InputText. Like below:
![](https://i.gyazo.com/00c18c18e6d686eec1afcfca74fdc5f8.png)

In my application, there's a feature where the user can bind a key in order to use it in combination with a click. So in the example above, if the user presses SHIFT + Click, the feature is executed.

I can use ``ImGuiInputTextFlags_CallbackAlways`` just fine and the implementation that I posted above achieves what I need, however, I thought there was some other way of making ImGui call my callback function for any key pressed, including a system key. With ``ImGuiInputTextFlags_CallbackAlways``, I need that ``lastKeyDown`` check because the callback is called every time the InputText is focused. 

Just like there's ``ImGuiInputTextFlags_CallbackHistory`` for UP/DOWN and ``ImGuiInputTextFlags_CallbackCompletion`` for TAB, it would be nice to have a ``ImGuiInputTextFlags_CallbackAnyKey`` flag. For that, I thought of something like this in your ``ImGui::InputTextEx`` function:

```c++
...
else if ((flags & ImGuiInputTextFlags_CallbackHistory) != 0 && IsKeyPressedMap(ImGuiKey_DownArrow))
{
    event_flag = ImGuiInputTextFlags_CallbackHistory;
    event_key = ImGuiKey_DownArrow;
}
else if ((flags & ImGuiInputTextFlags_CallbackAnykey) != 0 && IsAnyKeyPressed())
{
  event_flag = ImGuiInputTextFlags_CallbackAnykey;
  event_key = GetKeyPressed();
}
else if (flags & ImGuiInputTextFlags_CallbackAlways)
    event_flag = ImGuiInputTextFlags_CallbackAlways;
...
```

Thanks for your reply!

**Comment by ocornut** [comment]
> Sorry if I didn't provide enough details. I need an InputText() because the user will click on it and then type a key. As soon as he hits the first key, the translated key name should appear in the InputText. Like below:

Then there's absolutely no reason to use InputText(), you're not allowing the user to input raw text, you have probably a single value here and you are not reliant on any propetry of InputText().. Manage the inputs/values/translation yourself and display it using Text() or another widget.

**Comment by reliasn** [comment]
The user does input text, but only 1 character and this character is translated to its keyboard name. I thought InputText() was the correct way to implement this because on Win32 I implemented the same thing using Edit Controls.

![](https://i.gyazo.com/8e0b4079701b108ed4e3ca7e92c4d478.png)
```c++
struct W32Ctrl {
    HWND hwnd; 
    int item, *var;
    string name;
};
vector<W32Ctrl> charCtrls
...
if (msg.message == WM_KEYDOWN || msg.message == WM_SYSKEYDOWN){
    for(auto &u : charCtrls){  // std::vector or 
        if(msg.hwnd == GetDlgItem(u.hwnd, u.item)){
          W32::setDlgText(u.hwnd, u.item, W32::getKeyName(msg.wParam));  // Simply calls SetDlgItemText
          SetFocus(NULL);
          return false;  // Causes the message to not be dispatched by TranslateMessage/DispatchMessage
        }
    }
}
```
The code above checks if the WM_KEYDOWN/SYSKEYDOWN event happened on one of my "char" edit controls which behave like I explained, i.e., the user types a key and the key name appears.

For ImGui, I could try to do the same, but I don't know how I would find which InputText is being used (This is done by ``GetDlgItem`` on the above Win32 example). Since InputText has text edit callbacks, then I decided to use them to achieve what I want. But again, ``ImGuiInputTextFlags_CallbackCharFilter`` isn't enough because it ignores many keys and ``ImGuiInputTextFlags_CallbackAlways`` only works if I explicitly add a check to only change the ``data->Buf`` field when there was a WM_KEYDOWN/SYSKEYDOWN.

``ImGuiInputTextFlags_CallbackAlways`` is fine but I thought it would be nice to have another flag. I will try to implement what I'm thinking on my fork and post it here if I manage to get it working.

**Comment by ocornut** [comment]
Store a string and display it with Text() or LabelText(), etc.
There's absolutely nothing of InputText() that you need here and it's getting in your way.

**Comment by nem0** [comment]
@reliasn Not sure if it helps but I am doing something similar https://github.com/nem0/LumixEngine/blob/master/src/editor/settings.cpp#L144-L168

**Comment by reliasn** [comment]
@nem0 If I understood correctly, the user sets the shortcut by hovering the button and pressing a key while the reset is done by clicking the button. It's a very interesting approach that doesn't depend on InputText, but I confess I still think that an InputText callback for whichever pressed key would be quite convenient sometimes, for example, if you press Backspace in the InputText and you need the callback for this edit. From what I tested, ``ImGuiInputTextFlags_CallbackCharFilter`` doesn't catch that. ``ImGuiInputTextFlags_CallbackAlways`` catches it, but it is called every time the InputText is focused instead of only when a key is pressed.

**Comment by ocornut** [comment]
This is silly. You can see that your own Win32 code doesn't interact in a meaningful way with the Win32 text control but just set text its string which is equivalent to displaying one with ImGui::Text() or any other function. Set a bool based on clicking/hovering whatever button, then in our key callback set a string and just display it in the UI.
