### ISSUE TITLE
imgui + nanovg for 3D polygon editor

### ISSUE THREAD

**Issue by Symbian9** [ocornut/imgui#1003]
Is it possible use imgui (UI, menu) + nanovg (canvas of working space) for this opensource OpenGL-based 3D editor?
* http://ysflight.in.coocan.jp/polygoncrest/e.html

**Comment by ocornut** [comment]
Yes you can do anything. It's just OpenGL it is under your control. 
Please check the Gallery threads. https://github.com/ocornut/imgui/issues/973
(Also please also spend more time investigating the library and reading examples/topics before asking multiple questions in a row.)
