### ISSUE TITLE
ImGUI::Image  Problems  with DirectX11

### ISSUE THREAD

**Issue by Throbbing** [ocornut/imgui#1004]
The  **ImGui::Image**  function  can  correctly show   SRV created from file(`D3DX11GetImageInfoFromFileA` ) .
![image](https://cloud.githubusercontent.com/assets/12167368/22536390/6ba733ec-e93c-11e6-8043-b4522753b7c7.png)

However .when I create a manual SRV. the  **ImGui::Image ** show nothing.  

```
`
D3D11_TEXTURE2D_DESC td;
	ZeroMemory(&td, sizeof(td));
	td.Usage = D3D11_USAGE_DEFAULT;
	td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
	td.Width = 600;
	td.Height = 400;
	td.Format = DXGI_FORMAT_R32G32B32A32_FLOAT;
	td.MipLevels = 1;
	td.ArraySize = 1;
	td.MiscFlags = 0;
	td.CPUAccessFlags = 0;
	td.SampleDesc.Count = 1;
	td.SampleDesc.Quality = 0;

```
	D3D11_SUBRESOURCE_DATA sd;
	sd.pSysMem = dd;
	sd.SysMemPitch = 600*sizeOF(DXGI_FORMAT_R32G32B32A32_FLOAT);
	HR(jmxREX::hw.d3dDevice->CreateTexture2D(&td, &sd, &mGameWndImage.tex));
	

	D3D11_SHADER_RESOURCE_VIEW_DESC srvd;
	ZeroMemory(&srvd, sizeof(srvd));
	srvd.Format = td.Format;
	srvd.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
	srvd.Texture2D.MostDetailedMip = 0;
	srvd.Texture2D.MipLevels = 1;
	HR(jmxREX::hw.d3dDevice->CreateShaderResourceView(mGameWndImage.tex, &srvd, &mGameWndImage.srv));`
![image](https://cloud.githubusercontent.com/assets/12167368/22536405/88f0213e-e93c-11e6-90c2-b863034d319f.png)
But by the NSight, **I found that the SRV is created successfully and filled expected color.**
![image](https://cloud.githubusercontent.com/assets/12167368/22536449/c5df65fa-e93c-11e6-9cbd-c03b45ac9685.png)
![image](https://cloud.githubusercontent.com/assets/12167368/22536460/d7b70314-e93c-11e6-9d3e-c7d0c83fcfda.png)

What is Wrong?

**Comment by ocornut** [comment]
This is mostly a DX11 question, not an ImGui question.

The only thing ImGui::Image() does it store your ImTextureId parameter and then emit vertices.
The rendering details are left to the rendering loop and are DirectX11 details.

If you can suggest a way to improve the DX11 example code to naturally cover most use cases, a patch is welcome. If you have build your own engine over DX11 you should probably change your use of ImTextureId to pass in higher level primitives that just a `ID3D11ShaderResourceView*` as imgui_impl_dx11.cpp does. I don't know enough about DX11 to imagine all possible use cases.

**Comment by Throbbing** [comment]
@ocornut 
Oh. It is my problem...
When i fill  the SRV, I neglect the `BlendState` and set the alpha channel of texture '0',It means that the whole SRV is transparent for DX11 .
I have solved it.Thank you for you reply

**Comment by ocornut** [comment]
I have now written a tutorial to cover image file loading for common graphics API:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
