### ISSUE TITLE
OpenGL1.x

### ISSUE THREAD

**Issue by Symbian9** [ocornut/imgui#1006]
Is it supported by devices limited to OpenGL1.x?

**Comment by Wohlstand** [comment]
Every example implements the support on different render api, therefore yes, if you will implement example (out just port one of examples (for GL2) to OpenGL 1.x yourself)

**Comment by ocornut** [comment]
As long as you can render textured triangles you can render imgui.

You only need to adapt this render loop:
https://github.com/ocornut/imgui/blob/master/examples/opengl2_example/imgui_impl_glfw.cpp#L73
