### ISSUE TITLE
How to load/save imgui styles

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#101]
This is just an old file of mine I forgot to turn into a gist.
It can be used to save/load imgui styles to/from files in a text format.

Here is the gist with code and usage instructions: https://gist.github.com/Flix01/2c6e06b4a4f93016c334

(in the hope that somebody will share some alternative imgui style :))

**Comment by ocornut** [comment]
I'll close that for now. People can look around closed topics.
In the future hope to start a wiki with links.
