### ISSUE TITLE
How to disable user interaction on widget

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#1012]
Hi,

I have a curve widget and show three of them (one for each RGB channel)
As they are quite big I am rendering them all at the same CursorScreenPos so that you can see them all because of transparency.
![curvas](https://cloud.githubusercontent.com/assets/1795930/22745453/e3477fd6-ee20-11e6-952b-6316622079c4.jpg)
When user interacts only the topmost of them should respond.
How can achieve this

**Comment by sonoro1234** [comment]
Now I am solving this drawing first the curve I want to interact with. The problem is that it appears not at the top but at the bottom!

**Comment by ratchetfreak** [comment]
draw it again last?

**Comment by sonoro1234** [comment]
Yes but is an expensive widget!

**Comment by sonoro1234** [comment]
I am using ratcherfreak proposal. Perhaps BeginDisabled()/EndDisabled(); proposal in #211 would be the way.

**Comment by ocornut** [comment]
Closing as duplicate. @sonoro1234, see #211 for beginning of a solution.
