### ISSUE TITLE
Incorrect crop of overflowing elements

### ISSUE THREAD

**Issue by alaxmo13** [ocornut/imgui#1015]
Hi,

We're trying to use imgui using the vulkan example. 
It seems that the elements only dissapear if they're completely out of their windows, and when they should be shown partially they're shown in full.

Any clue why this might be happening?

![why1](https://cloud.githubusercontent.com/assets/4052441/22825494/deb36638-ef8d-11e6-9bda-ae4c006faebf.png)
![why2](https://cloud.githubusercontent.com/assets/4052441/22825495/dec863c6-ef8d-11e6-9f8d-bd98717a61a5.png)

Edit; Sorry, the error was at our end. Someone had commented the scissor.

**Comment by ocornut** [comment]
Cool. For the records for people stumbling on this, it is a classic problem with not honoring the clipping rectangles provided in the draw calls.

In the future I would like to provide a "Testing" window to help identity typical integration issues.
