### ISSUE TITLE
Performance: cost of issuing widgets command vs rendering them

### ISSUE THREAD

**Issue by rickyviking** [ocornut/imgui#1016]
Hi Omar,

I have some ImGui tools spread in my framework codebase which is re-used in different applications.
I'd like to keep these ImGui tools available (on demand) on the shipped applications, making sure to reduce the performance impact at the minimum when the gui is not requested/visible.

I'm wondering if the cost of issuing the widgets command is negligible compared to the cost of rendering them with ImGui::Render(). If that's the case, my idea is to leave the widgets code always active and simply switch off the rendering part (no ImGui::Render() and backed implementation callback).  

Otherwise I'll have to place all ImGui related code within if blocks and check at runtime whether ImGui is currently "in use" or not, which could reduce the code readability.

What do you suggest?
Thank you, 
Ricky

**Comment by ocornut** [comment]
No it is quite the opposite, the cost of Render() is very minor compared to the cost of doing anything else.

You should probably add checks because your Begin()/End() block.

It would be possible to add an option to globally force Begin() returning false, which may reduce the number of checks, provided you are already checking the return value of Begin() - which you should :)

**Comment by rickyviking** [comment]
Hi @ocornut ,
ok I'll go and add a check the return value of every Begin()/End() block :)

The global option might be a nice addition. 
Or what about a way to override returning value for an individual widget? This could be another boolean or a callback maybe.
It could be useful to collapse code like:
```
if (show_another_window)
{
   if (ImGui::Begin("Another Window", &show_another_window))
   {
      ImGui::Text("Hello");
   }
   ImGui::End();
}
```

into something like:
```
if (ImGui::Begin("Another Window", &show_another_window, [some_override]))
{
      ImGui::Text("Hello");
}
ImGui::End();
```

**Comment by ocornut** [comment]
That override is also called the `&&` operator?

```
if (ImGui::Begin("Another Window", &show_another_window,) && !disable_all)
{
      ImGui::Text("Hello");
}
ImGui::End();
```

**Comment by rickyviking** [comment]
yeah right :)
I thought you were suggesting an override internal to ImGui::Begin() implementation, probably because an early override check could be faster than invoking a regular Begin().

**Comment by ocornut** [comment]
Yes, if there is a _global_ override it would be in a global setting that affects all Begin() for convenience, and shortcut them. I may add that later!
