### ISSUE TITLE
Separate separator colour from border OR border bug?

### ISSUE THREAD

**Issue by avaskoog** [ocornut/imgui#1019]
Yo!

I may have messed up completely, but all my windows lack the show-border flag, and I have deleted all ImGui save/config/ini files and I have added the no-save flag to all windows as well. Yet I still see borders no matter what. Considering there's an option to _show_ borders rather than hide them, shouldn't the default be no borders? How come I'm seeing borders?

My hacky solution so far has been to just set the theme's style's border colour to have an alpha value of zero, but that comes with my particular issue right now: I want a borderless layout, but since the only way I've managed to get rid of borders is to set the alpha to zero, and horizontal separators (`Separator()`) in menus use the same colour style, my separators are now invisible, and I would like to see those despite having a borderless theme...

So unless there is some show-border issue to be solved (either because there is a bug or because I made some kind of mistake), I guess it would be nice to have separator colour be separate from border colour, since I want to hide the borders but not the separators.

c:

**Comment by ocornut** [comment]
You have a bug somewhere - is your imgui modded?

You are correct that no border should appear unless you pass the _ShowBorder flag. However the BeginChild() function has a bool which itself sets this flag in the window. Presumably your codebase uses lots of child windows for tabs so maybe thats your issue.

This is going to be refactored and "fixed" in a further release (maybe 1.50): we will add BorderSize to ImGuiStyle and remove the ShowBorder flag accordingly. This flag is a little inconsistent at the moment.

**Comment by avaskoog** [comment]
Aahh. Yes. I had actually touched that flag before to try and be smart about it in some way before, and had just forgotten about it.

But the attempt at smartness comes from the other issue you bring up (apparently I had been setting the flag depending on the alpha value of the colour as an ad-hoc solution, which broke down when it got to the separators now), which is that whether or not to have borders is not currently AFAIK a style/theme setting, so yes, that'd be a good addition indeed! c:

**Comment by avaskoog** [comment]
Am I mistaken, or is it true that there is still no way to get rid of menubar borders other than setting the alpha to zero? I managed to get rid of the windows' borders now but the menu popups still have borders and I can't find any boolean flag in those functions.

**Comment by ocornut** [comment]
Yes you are correct, this should be reworked when I get to do a pass on all border settings.

**Comment by avaskoog** [comment]
All right, thanks for the sanity check!

**Comment by ocornut** [comment]
@avaskoog I have now applied the (breaking) change of renaming the `ImGuiCol_Column_XXX` enums to `ImGuiCol_Separator_XXX`. 
`Columns()` and `Separator()` now uses that colors.

I think it should fix the issue "Separate separator colour from border".
I am working on moving the Border to the style structure as `float BorderSize` and removing the ShowBorder flag as well. This is a slightly more tricky change, I'll commit it along with improvements related to #707

**Comment by ocornut** [comment]
@avaskoog Now pushed a handful of changes today so you can now freely alter the border size `style.WindowBorderSize`, `style.FrameBorderSize` `style.PopupBorderSize`, independently. 
See functions such as `ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f)`. 
The ImGuiWindowFlags_ShowBorders flag has been completely obsoleted.

Let me know if that all works as expected for you!
