### ISSUE TITLE
Horizontal layout for Childwindows

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1020]
Hey there, I'm quite new to ImGui, so please bear with me.

I'm currently trying to add ImGui to my little project/hobby.
I've achieved to create an ImGui Window, and inside that window I've created Checkboxes.
Each of those checkboxes makes a child window appear, although, they appear vertically, which is my problem.

Could I somehow make the Child Windows stand side by side of each other Horizontally?

**Comment by ocornut** [comment]
Hello,

You can use `ImGui::SameLine()` between calls to BeginChild(), along with passing a width to `BeginChild()`.

PS: Best to provide screenshots/sample shot to make sure your situation is well understood. Here it is confusing as to why you have mentioned "checkboxes" at all.

**Comment by emilo0212** [comment]
Here, I made an illustration with a drawing in paint. Hope this explains why I need the checkboxes at all and how I really want it to be. Thanks for replying!

![unavngivet](https://cloud.githubusercontent.com/assets/25754141/22904928/858779e2-f23e-11e6-95d4-07aa3244c539.png)

**Comment by ocornut** [comment]
My message above answers your question, then!

**Comment by emilo0212** [comment]
Hmm. Could you possibly give me an example of how it would work in code? 

If that's not an issue.
I'll gladly search myself aswell if you dont have time.

**Comment by ocornut** [comment]
Please search yourself, this is what the imgui examples and demo are for.

**Comment by emilo0212** [comment]
Alright man, thanks for your help tho! I really appreciate it.
