### ISSUE TITLE
How to use Sameline several times

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1021]
I'm using ImGui::SameLine(); to align my Checkboxes horizontally and it works fine, but when I try and do SameLine(); with my Childwindows, they just align aside my checkboxes, how could I make it separate?

Code: 

'ImGui::Begin(charenc("Borahook"), &Files.Menu.Opened, ImVec2(500, 500), 0.45f, 
ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse);

		{
			if (Files.Menu.Opened)

			{
				ImGui::SameLine();
				ImGui::Checkbox(charenc("Visual Settings"), &Files.Menu.Visual);
				ImGui::SameLine();
				ImGui::Checkbox(charenc("Misc Settings"), &Files.Menu.Misc);
				ImGui::SameLine();
				ImGui::Checkbox(charenc("System Configs"), &Files.Menu.System);
			}

			if (Files.Menu.Visual)
			{
				ImGui::SameLine();
				ImGui::BeginChild("Visual Settings", ImVec2(100, 100), ImGuiWindowFlags_AlwaysUseWindowPadding);
				{
					ImGui::Text("XDXDXD1");
				}
				ImGui::EndChild();
			}

			if (Files.Menu.Misc)
			{
				ImGui::SameLine();
				ImGui::BeginChild("Misc Settings", ImVec2(100, 100), ImGuiWindowFlags_AlwaysUseWindowPadding);
				{
					ImGui::Text("XDXDXD");
				}
				ImGui::EndChild();
			}

		}
		ImGui::End();`

![05a0c2cdf7a78ca8311e6433b776b073](https://cloud.githubusercontent.com/assets/25754141/22909453/83ebefda-f254-11e6-8e2e-f8e82dad2649.png)

**Comment by ocornut** [comment]
Before after further questions please spend more time looking at the problem and the different examples provided with imgui. Thanks!
When you solve a problem it is also good manner to explain it for future readers.
