### ISSUE TITLE
Nothing to be done for `Makefile'.

### ISSUE THREAD

**Issue by clankill3r** [ocornut/imgui#1023]
I try to build on Mac.

What I did was open terminal then:

```
cd /Users/doekewartena/Documents/imgui/examples/opengl3_example 
make Makefile
```

Which gives me the error:

`make: Nothing to be done for `Makefile'.`

Anything I can do?
I'm really bad at setting things up.

**Comment by VZout** [comment]
Try deleting and re-cloning the project. Than cd back into the correct dir and call `make` a argument should not be necessary since there is only 1 makefile. I can't reproduce this problem with a fresh install.

**Comment by clankill3r** [comment]
Thanks! Cloning the project again fixed it. Strange...
Not I can run things instead of only reading :)
