### ISSUE TITLE
Possible to save canvas/window to PNG within ImGUI? [Linux]

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#1025]
Not sure if this is possible currently, or even if it's possible through SDL.

I want to be able to get a screenshot of the current ImGui application and save to PNG.  Obviously I can do this through the OS/WindowManager but I'd like to be able to do it within my app so I can set the saved screenshot name appropriately for what is being viewed/rendered.

**Comment by colesnicov** [comment]
https://github.com/ocornut/imgui/wiki/screenshot_tool

**Comment by ocornut** [comment]
This is OpenGL code. Capturing would depend on your rendering system. The question itself is unrelated to ImGui sorry.
