### ISSUE TITLE
Alternative tooltip content for plots

### ISSUE THREAD

**Issue by YukinoHayakawa** [ocornut/imgui#1026]
Currently, the PlotEx function hard-codes the value indices as the independent variable in its tooltip. However, it would be more convenient in some circumstances that a variable other than that could be used. For example, when visualizing a function such as a filter, the values (1D with uniform distribution) actually used to evaluate the function could be a better alternative.

**Comment by ocornut** [comment]
I agree but have no ETA to support it.

Right now, the easier way is to copy PlotEx() into your own code and do something custom.

A future, more evolved plot API should allow you to query the value(s) hovered and then you'll be able to display anything with it.

**Comment by ocornut** [comment]
Closing this old issue, nowadays we'd suggest using https://github.com/epezent/implot

**Comment by YukinoHayakawa** [comment]
> Closing this old issue, nowadays we'd suggest using https://github.com/epezent/implot

The library looks really awesome IMO. Thank you very much.
