### ISSUE TITLE
Columns inside column

### ISSUE THREAD

**Issue by colesnicov** [ocornut/imgui#1028]
Hi Omar.
Is a way to display the columns within the column without using BeginChild?

This works:

        ImGui::Begin("Dive columns");
        ImGui::Columns(2, "outer", true);
        {
            ImGui::Text("%s", "outer column 1");
            ImGui::NextColumn();
            ImGui::BeginChild("inner");
            ImGui::Columns(2, "inner", true);
            {
                ImGui::Text("%s", "inner column 1");
                ImGui::NextColumn();
                ImGui::Text("%s", "inner column 2");
            }
            ImGui::Columns(1);
            ImGui::EndChild();
        }
        ImGui::Columns(1);
        ImGui::End();

![worked example](http://i.imgur.com/p1ZCf66.png)

But this had not:

        ImGui::Begin("Dive columns");
        ImGui::Columns(2, "outer", true);
        {
            ImGui::Text("%s", "outer column 1");
            ImGui::NextColumn();
            ImGui::Columns(2, "inner", true);
            {
                ImGui::Text("%s", "inner column 1");
                ImGui::NextColumn();
                ImGui::Text("%s", "inner column 2");
            }
            ImGui::Columns(1);
        }
        ImGui::Columns(1);
        ImGui::End();

![non worked example](http://imgur.com/VLIs3LT.png)

**Comment by ocornut** [comment]
It's not possible at the moment (without an extraneous Child).
The next columns api (#125) will be based on a BeginColumns()/EndColumns() model to allow that.
