### ISSUE TITLE
merge DefaultFont with Awesome Fonte causes a fail in IM_ASSERT(Glyphs.Size < 0xFFFF)

### ISSUE THREAD

**Issue by hugoalexrsantos** [ocornut/imgui#1030]
Hi ocornut,

I'm trying to merge the default font with the awesome font following the example in the Extra_Fonts folder, by it always fails the " IM_ASSERT(Glyphs.Size < 0xFFFF);" in the ImFont::BuildLookupTable() function

The code that i'm using is:
#include "IconsFontAwesome.h"
...

    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->AddFontDefault();
    ImFontConfig config;
    config.MergeMode = false;
    const ImWchar icon_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };
    io.Fonts->AddFontFromFileTTF("resources/fonts/fontawesome-webfont.ttf", 12.0f, &config, icon_ranges);

I Noticed that when running the ImFontAtlas::Build():
for (int input_i = 0; input_i < ConfigData.Size; input_i++) #L1271  iterates 2 times which seems correct as I'm loading 2 fonts... ConfigData.Size=2

the innerloop that loops throwgh the ranges: #L1285
 for (const ImWchar* in_range = cfg.GlyphRanges; in_range[0] && in_range[1]; in_range += 2)
        {
            total_glyph_count += (in_range[1] - in_range[0]) + 1;
            total_glyph_range_count++;
        }
for the default font, it iterates only once with range 32 to 255 [224 Glyphs]
for the icons font, it strangely iterates 3 times with ranges:
27541 to 63392 [35852 Glyphs]
126 to 2623 [2498 Glyphs]
27520 to 62992 [35473 Glyphs]
total_glyph_count = 74047 Glyphs 
total_glyph_range_count = 4
I specified only 1 range 
ICON_MIN_FA  = 0xf000 (61440) 
ICON_MAX_FA = 0xf2e0 (62176) [737 Glyphs].

Is this a bug, or I'm I doing something wrong?
by the way, I downloaded the latest version of the ImGui code just yesterday.
Thank you in advance.

**Comment by ocornut** [comment]
This is described in various places.

Your range pointer needs to persist to the point the fonts are actually build. Make them static or global or store them somewhere. Right now you are probably building the font in a different function and all those ranges in the stack are unwinded already.

**Comment by hugoalexrsantos** [comment]
Hi,

Changed the line to
STATIC const ImWchar icon_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };

it worked perfectly.

thank you.
