### ISSUE TITLE
Border for individual elements?

### ISSUE THREAD

**Issue by colesnicov** [ocornut/imgui#1031]
Hi Omar, again :-)

Maybe it just do not understand, maybe it is a good idea for the next innovation...

Now is the moment I have encountered while trying to the highlighted button at `BeginChild`. Here are the facts:
- `Begin (... ImGuiWindowFlags_ShowBorders)` does not display the border with `BeginChild`. And their content as buttons, are also no borders ... I have also set in `BeginChild` `ImGuiWindowFlags_ShowBorders`.
- If you want to have at the `Button` or `ImageButton` a border, I need to `Begin[Child]` set flags on `ImGuiWindowFlags_ShowBorders` but after that is bounded on any element, which is undesirable.

_Question:_ **How to set borders for individual elements??**

**Comment by colesnicov** [comment]
Hrrr,
Any hints?

**Comment by ocornut** [comment]
Enable the border at all time and manipulate the border color with PushStyleCol(), PopStyleCol().

**Comment by colesnicov** [comment]
https://github.com/ocornut/imgui/issues/819

**Comment by ocornut** [comment]
Flagged as style, when I revamp the style system some of the change would include specifying border per type of element, similarly to how you can specify background colors.

**Comment by ocornut** [comment]
@colesnicov Pushed changes today so you can now freely alter the border size `style.FrameBorderSize` with e.g. `ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f)`. The ImGuiWindowFlags_ShowBorders flag has been completely obsoleted.
