### ISSUE TITLE
library not found for -lglfw3

### ISSUE THREAD

**Issue by clankill3r** [ocornut/imgui#1032]
I can get the opengl3_example working, but I would also like to get the apple_example working so I can step through with a debugger.

When I build I get:

> ld: library not found for -lglfw3
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I do have glfw-3.2.1 installed.

In an attempt to fix:

I added 
> /usr/local/Cellar/glfw/3.2.1/lib
 to the **Library Search Paths**.

And I added `OpenGL.framework` and `libglfw3.dylib` to **Linked Frameworks and Libraries**.

But I still hit the error. Damn I hate Xcode.

**Comment by petmac** [comment]
I encountered this same issue. There's a very easy fix.

In the project navigator, in the Frameworks group, you should see a reference to libglfw3.dylib. Click on it, and in the right panel (Utility navigator?) change the name to libglfw.3.dylib.

I guess GLFW added a dot before the 3 at some point.

**Comment by petmac** [comment]
I created a Pull Request to fix this: #1044

**Comment by AlexxNica** [comment]
@petmac Perfect. Your solution fixed for me, it's all working fine now. Thank you! 😃

**Comment by ocornut** [comment]
Closed as solved per #1044
