### ISSUE TITLE
ColorConvertU32ToFloat4 green is level of blue (fixed code inside)

### ISSUE THREAD

**Issue by Jorith** [ocornut/imgui#1033]
This is what it should be. At the moment blue levels are same as green always.

ImVec4 ImGui::ColorConvertU32ToFloat4(ImU32 in)
{
    float s = 1.0f/255.0f;
    return ImVec4(
        ((in >> IM_COL32_R_SHIFT) & 0xFF) * s,
        ((in >> IM_COL32_G_SHIFT) & 0xFF) * s,
        ((in >> IM_COL32_B_SHIFT) & 0x00) * s,
        ((in >> IM_COL32_A_SHIFT) & 0xFF) * s);
}

**Comment by ocornut** [comment]
You may be confused by something else in your own code, the current implementation is correct.

Changing `& 0xFF` to `& 0x00` basically completely destroy the blue channel here.

**Comment by Jorith** [comment]
Guess i'm wrong then, this works for me, what you have not ^^

**Comment by ratchetfreak** [comment]
double check your IM_COL32_*_SHIFT values,
