### ISSUE TITLE
ImGui::RadioButton does (basically) "ImVec2(y,y)" - is it supposed to be like that?

### ISSUE THREAD

**Issue by tom-seddon** [ocornut/imgui#1034]
I'm writing a radiobutton-like control, and I came across the following odd code in ImGui::RadioButton. I've reformatted it deliberately:

    const ImRect check_bb(window->DC.CursorPos,
                          window->DC.CursorPos + ImVec2(label_size.y + style.FramePadding.y*2-1,
                                                        label_size.y + style.FramePadding.y*2-1));

Is it really supposed to use Y twice?

Thanks,

--Tom

**Comment by ocornut** [comment]
Yes because it is ensuring that we draw a square, so make we build up a square from the total Height.

**Comment by tom-seddon** [comment]
Right, OK - I think I see what's going on. Thanks for the quick reply :)

--Tom

**Comment by ocornut** [comment]
I will add a comment in the code to clarify that. Thanks!

**Comment by xarthurx** [comment]
Hi, I have a following question to this issue.

The current high level `RadioButton` only receive label and variables, but not the size directly.
ImGui will calculate the width based on the `square_sz` and `label_size` variable.

Does it mean there is no high-level wrapper for making the `RadioButton + Label` similar to what we can do in the normal `Button` (an `ImVec2` can be fed to set the size)?

What I'd like to control is the width of the radio labels as shown below:

![image](https://user-images.githubusercontent.com/1921878/69950629-f4822600-14f3-11ea-8eb9-493247c8be63.png)
