### ISSUE TITLE
How to change menu colors with a slider?

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1036]
Hey there, I'm back again :)

This time I'm trying to change the ImGui's CheckMark colors.
I have the style.Colors[ImGuiCol_CheckMark] = ImVec4(R, G, B, A).
I've defined 3 float values, to represent R, G & B.
I've made 3 sliders, and assigned them to give the value from1-255 to R, G and B.
Although, when I change these colors from the slider, the CheckMark colors wont change, do I need to re-render the ImGui each time I change the float value with the sliders?

Little illustration:
//Declarations:
`float R = 0.f;
float G = 0.f;
float B = 0.f;

ImGui::SliderFloat("Red Amount"), R, 1.f, 255.f, "%.0f");
ImGui::SliderFloat("Green Amount"), G, 1.f, 255.f, "%.0f");
ImGui::SliderFloat("Blue Amount"), B, 1.f, 255.f, "%.0f");

style.Colors[ImGuiCol_CheckMark] = ImVec4(R, G, B, 1.00f);`

This doesn't seem to edit the CheckMark.

**Comment by colesnicov** [comment]
try

```
static float R = 0.f;
static float G = 0.f;
static float B = 0.f;
```

**Comment by ocornut** [comment]
You may also just directly edit the values as a color:

`ImGui::ColorEdit4(name, &style.Colors[ImGuiCol_CheckMark].x, true);`

**Comment by liamdebell** [comment]
how can i use coloredit4
