### ISSUE TITLE
Aligning a window to the bottom of the screen

### ISSUE THREAD

**Issue by hamoid** [ocornut/imgui#1045]
Hi, I'm trying to create a small window at the bottom of the screen. It works, but it's drawn twice at different locations. I'm using OpenFrameworks.

    // --- Menu window
    if(menuIsOpen) {
        settings.windowPos.x = 0;
        settings.windowPos.y = 0;
        if (ofxImGui::BeginWindow("", settings, corner)) {
            if (ImGui::Button("Restart")) {
                cout << "Restart" << endl;
                menuIsOpen = false;
            }
            if (ImGui::Button("Settings")) {
                settingsIsOpen = true;
                menuIsOpen = false;
            }
            if (ImGui::Button("Help")) {
                editIsOpen = true;
                menuIsOpen = false;
            }
            ImGui::SetWindowPos(
                ImVec2(0, ofGetHeight() - ImGui::GetWindowHeight()),
                true);
            cout << ImGui::GetWindowPos().y << endl;
        }
        ofxImGui::EndWindow(settings);
    }

For some reason the cout prints two values: 1093 immediately after making menuIsOpen true, and then 961 repeatedly as long as the window is open. These are the settings:

        ImGuiWindowFlags corner =
            ImGuiWindowFlags_NoMove |
            ImGuiWindowFlags_NoResize |
            ImGuiWindowFlags_NoCollapse |
            ImGuiWindowFlags_NoSavedSettings |
            ImGuiWindowFlags_AlwaysAutoResize |
            ImGuiWindowFlags_NoTitleBar;

It looks like the window is drawn with only the button Restart visible (for one frame), and then with all 3 buttons as requested.

Is there a better way to align a window to the bottom of the screen? Thank you :)

**Comment by hamoid** [comment]
I think I found out the reason. I'm reusing the same settings to create many windows. I thought it was a good idea (to avoid creating a bunch of objects). But maybe it's not :)

If I replace

        settings.windowPos.x = 0;
        settings.windowPos.y = 0;

by

        settings.windowPos.x = 0;
        settings.windowPos.y = 2000;
        settings.windowSize.x = 0;
        settings.windowSize.y = 0;

It seems like the first time the window is drawn it's outside of the screen, so there's no more flickering. Is reusing settings a bad idea?

**Comment by ocornut** [comment]
I have no idea what those things are, they seems to be part of some wrapped included in ofximgui, it's not really core imgui and therefore I cannot help without getting a repro using imgui calls.

**Comment by hamoid** [comment]
I understand. Thanks! I'll research further and contact the ofxImGui ppl.

**Comment by hamoid** [comment]
Replacing the OpenFrameworks addon calls with native ones it looks like this:

    if(menuIsOpen) {
        bool * p_open = nullptr;
        if (ImGui::Begin("menu", p_open, corner)) {
            if (ImGui::Button("A")) {}
            if (ImGui::Button("B")) {}
            if (ImGui::Button("C")) {}
            cout << ImGui::GetWindowSize() << endl;
            ImGui::SetWindowPos(ImVec2(0, 768 - ImGui::GetWindowHeight() - 40), true);
        }
        ImGui::End();
    }

The issue seems to be that the window size changes after the first frame:

    32, 22
    274, 218
    274, 218
    274, 218
    ....

Is that to be expected?

**Comment by hamoid** [comment]
If I replace `ImGui::GetWindowHeight()` with `ImGui::GetCursorPos().y` it works :) The two values are not identical (because of padding / spacing), but I can work around it.

In case it helps diagnose a possible issue, this is my style:

    ImGuiStyle & style = ImGui::GetStyle();
    style.WindowPadding            = ImVec2(15, 15);
    style.WindowRounding           = 10.0f;
    style.ChildWindowRounding      = 10.0f;
    style.FramePadding             = ImVec2(10, 10);
    style.FrameRounding            = 10.0f;
    style.ItemSpacing              = ImVec2(10, 10);
    style.WindowTitleAlign         = ImGuiAlign_Center;
    style.ItemInnerSpacing         = ImVec2(10, 10);
    style.IndentSpacing            = 0.0f;
    style.ScrollbarSize            = 20.0f;
    style.ScrollbarRounding        = 16.0f;
    style.GrabMinSize              = 20.0f;
    style.GrabRounding             = 16.0f;
    style.Alpha                    = 0.0f;

**Comment by ocornut** [comment]
@hamoid Sorry for my late answer (even more sorry as I was overwhelmed with many vague requests while your posts are totally clear and fine!).

You are right, in that situation the window size is computed and unavailable during the first frame, so that sort of pattern cannot work on the first frame. 

Using GetCursorPos().y + SetWindowPos() at the end as you did is pretty good workaround and probably the best you can do at the moment without computing or locking the height yourself. It is a little unsatisfactory but the best I can think of at the moment. If you have any suggestion on how we could improve it I'm happy to hear it, for now I would just leave it as is.

**Comment by hamoid** [comment]
Thank you for taking a look into it (and for developing ImGui! :) )

Would it make sense to return 0 if the height of the window is not yet calculated? That would make it easy to test to avoid drawing the window until the size is known.

**Comment by ocornut** [comment]
> Would it make sense to return 0 if the height of the window is not yet calculated?

That's a good point, I'm noting the idea but it may be tricky (there are a lot of messy complications and edge cases with anything related to window auto-sizing, auto-resizing can be requested later than the first frame etc.).
