### ISSUE TITLE
Implementation for Cocos2D Objective C

### ISSUE THREAD

**Issue by spuckfunkel** [ocornut/imgui#1046]
I watched the GDC talk about ImGui and it seems like the perfect Gui for game development. At the moment I am creating games with Cocos2D-ObjC. I just started a new game and would really like to use ImGui for my tools. But I am struggling to implement it into Cocos2D. I thought it won't be that difficult because you can mix c++ and objective c code. I looked into the Cocos2D-x implementation to see if I can port it to Cocos2D-ObjC but it is too hard for me :). I am not really a c++ coder and I think I have to understand the inner workings of Cocos2D to port it. Which I don't have yet.

My second guess was to use the implementation from the opengl2 example and simply create a second window above the Cocos2D context but I could not find how to make the glfw window opaque. so it will overdraw the Cocos2D scene.

Do you have a hint how I can easily use ImGui with Cocos2D ObjC?

**Comment by ratchetfreak** [comment]
The only requirements to use imgui is filling in the IO struct each frame and have a way to render textured triangles.

**Comment by ocornut** [comment]
Closing this as not being a really open issue. A maintainer for variety of official Cocos2D backend would be ideal.
