### ISSUE TITLE
Render upside down

### ISSUE THREAD

**Issue by sybalos** [ocornut/imgui#1047]
Hi,
I'm new to 3D rendering and i want to use imgui into my own code base (DX11 renderer). I'm almost there except for one issue which is that everything is rendered upside down (see image below). When using VS graphic debugger it show that the problem might be in the vertex/index buffer since the input assembler pipeline stage is showing inverse Y vertices position. My own custom geometry render correctly. Any help would be really appreciate.

![imgui](https://cloud.githubusercontent.com/assets/4392609/23389733/f158ec38-fd37-11e6-9dca-99ef74b541c9.jpg)

Thanks.

**Comment by ocornut** [comment]
Just invert the y coordinates of your projection matrix!

**Comment by sybalos** [comment]
Yes indeed, i think i was curious as to why the vertices coordinates provided by imgui was not the one i expected.

Thanks for the quick answer!
