### ISSUE TITLE
ImGui ignoring window setting size when 'ImGuiWindowFlags_NoInputs' is specified

### ISSUE THREAD

**Issue by Bhagawan69** [ocornut/imgui#1048]
Hi! 

First let me say I LOVE your library, it has made wonders for me and my users, I will upload a screenshot soon of my implementation to your screenshots section :-)  

Now to the bug, apparently when specifying 'ImGuiWindowFlags_NoInputs' the ImGui::Begin method will ignore the window settings from the INI file.  

IMO the issue is due to ImGui.cpp(3883):
---------------------------------------------------------------------------
 if (flags & ImGuiWindowFlags_NoInputs)
        flags |= ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize;
---------------------------------------------------------------------------
Followed then into the internal CreateWindow() method, line 3810:
---------------------------------------------------------------------------
if (ImLengthSqr(settings->Size) > 0.00001f && !(flags & ImGuiWindowFlags_NoResize))
            size = settings->Size;
---------------------------------------------------------------------------
As the no input flags adds "no-resize" to the flags in Begin, causing CreateWindow to to ignore "settings->Size"

Thank you again for wonderful library!

EDIT: Not sure why my formatting made it all bold, I just opened this account and new to Github so I beg your pardon for this bold mess :-)

**Comment by ocornut** [comment]
Closing and merging with new duplicate #1056 
Are you the same person asking? Quite surprising to see two people asking the same thing nearly on the same time :)

**Comment by ratchetfreak** [comment]
bout the formatting add an extra blank line between the text and the --- otherwise the formatter thinks you want a header instead of a separator

**Comment by ocornut** [comment]
(Closing as duplicate, sorry, intended to close before as we moved to the other topic)

**Comment by ocornut** [comment]
Fixed.
