### ISSUE TITLE
Unable to use InputText.

### ISSUE THREAD

**Issue by MonkahTV** [ocornut/imgui#1050]
Hi!

I'm currently attempting to run ImGui alongside SFML (and its respective RPI bindings) on a Raspberry Pi 3, and have had near perfect success, with the exception of InputText.

InputInt, InputFloat, Checkbox, and all other fields seem to be responding to user input just fine. However, while it is possible to select and focus on an InputText, it seems to ignore my keypresses and as a result, nothing enters the text-box. There is the 'field selected' blinking line within the box, which I believe eliminates it being an issue with widget selection or focusing.

This issue extends to all text fields within the ImGui Demo, leading me to believe that it's likely not an issue within my code. There have been no errors of relevance that could help identify the issue at hand. Initializing an InputText seems to leave it with that set value, but as you might expect, this value isn't modifiable by the user. I have tested this issue with both char* as well as char arrays, this issue seems to persist to both.

I wish I had more information to provide, but with no relevant errors/warnings, there's really not much I can offer. Thanks in advance!

**Comment by ocornut** [comment]
Is your binding correctly calling io.AddInputCharacter() with translated characters?

**Comment by MonkahTV** [comment]
The imgui-SFML binding does seem to have that, yeah. To the best of my knowledge, there are a good number of users that've used IMGUI/SFML without encountering this issue.

` // imgui-SFML.cpp
case sf::Event::TextEntered:
                if (event.text.unicode > 0 && event.text.unicode < 0x10000) {
                    io.AddInputCharacter(event.text.unicode);
                }
                break;`

**Comment by colesnicov** [comment]
Here is ImGui SFML bindings what I use [https://gist.github.com/colesnicov/571d725d376c90569572905ce4b84666](https://gist.github.com/colesnicov/571d725d376c90569572905ce4b84666)

**Comment by MonkahTV** [comment]
@colesnicov We seem to have the same TextEntered event code-- I don't think the issue is related to the bindings.

`        case sf::Event::TextEntered:
            if (event.text.unicode > 0 && event.text.unicode < 0x10000)
            {
                io.AddInputCharacter(static_cast<ImWchar>(event.text.unicode));
            }
            break;`

**Comment by MarkSill** [comment]
In your event handling code, do you call `ImGui::SFML::ProcessEvent(event)`? That's what handles text.
