### ISSUE TITLE
Background images

### ISSUE THREAD

**Issue by wheybags** [ocornut/imgui#1054]
Hi,
I'm thinking of using this library for the gui of [freeablo](https://github.com/wheybags/freeablo), but obviously I'd need to style it to look like the original diablo's gui.
So, I was wondering if there's any support for something like background images on windows or on arbitrary widgets, that I could use to achieve this?

**Comment by ocornut** [comment]
You can draw a background manually in a window but there's not really support to do something for individual widgets.

**Comment by wheybags** [comment]
Ok, is adding support to do styling like that something feasible, or should I just give up and try a different lib?

**Comment by ocornut** [comment]
Anything is feasible if you do and maintain it yourself, but it isn't within the scope of what dear imgui desire to achieve.

That said you could technically use the lower level function such as ImDrawList and say, ButtonBehavior and knock up a Diablo-looking GUI with dear imgui as a base. That sort of approach works but it works better if it's not your first use of the library. If I were to redo Diablo 1 original GUI i wouldn't use an off-the-shelve product probably.

**Comment by wheybags** [comment]
The reason I want to use an off-the-shelf library is that I want the UI to
be moddable in the end. So, I was planning on trying the Lua binding, and
allowing users to edit their GUI by changing Lua files.
I might give it a go, but if it's too much work I'll go for a different
library.
The reason I wanted to use dear imgui in particular is that it's the first
I've ever heard of immediate mode GUIs, and I really love the idea.

**Comment by ocornut** [comment]
It's really not designed to be very moddable in term of visuals.
