### ISSUE TITLE
Loading window size from ini with NoResize flag

### ISSUE THREAD

**Issue by HasKha** [ocornut/imgui#1056]
Hello, first of all thanks for the awesome library!
I am using locked windows (NoMove and NoResize), and I noticed that the library does not load the size from .ini when the NoResize flag is set. This is due to the following code.

line 3810 in imgui.cpp:
```C
if (ImLengthSqr(settings->Size) > 0.00001f && !(flags & ImGuiWindowFlags_NoResize))
    size = settings->Size;
```

I removed the second part of the condition and obtained the behavior I wanted. I was wondering if this was intentional, and if so, what is your reasoning behind it, especially considering that the location is correctly loaded even with the NoMove flag set.

**Comment by ocornut** [comment]
I don't understand the intent, if the window isn't resizable by the user there's shouldn't be data in the .ini file in the first place. How would you use it?

Have you tried to use `SetNextWindowSize()` to manually set a window size?

**Comment by HasKha** [comment]
In my application I use some transparent windows as containers for simple data. Such windows are essentially invisible (no background, no title bar) and the data appears to be "floating". Moreover, those windows are typically locked and don't capture mouse input. All of this is handled perfectly by ImGui::Begin with the appropriate window flags.

The user can choose to temporarily move and resize those windows, and the application will pass the appropriate flags to ImGui::Begin to allow for this. Window locations, sizes and collapse status are then saved by ImGui on exit, which is great, and loaded back on the next launch, which is again great, except for the fact that the current behavior is to not load size on those windows, since their default status on launch is to be locked. 

Sorry if it wasn't clear (or if it still isn't), and sorry for not seeing the other issue. I am not indeed the same person :)

**Comment by Bhagawan69** [comment]
@ocornut funny indeed but no we're not the same person myself and @HasKha .

As I mentioned in #1048 this will also occur when setting 'ImGuiWindowFlags_NoInputs' as the flag will internally set the NoResize flag behind the scenes which will cause the ini size to be ignored.   

In my app I use ImGui as a game HUD to display data, the users have an option to "unlock'' the UI and change w/e they want (I.e. Move/resize/etc) after which they will lock they UI again to not interfere with the game input so when loading the windows from the INI rhe size settings were ignored when the users had the input set to off before loading.

**Comment by ocornut** [comment]
Looking at this. 
Actually it looks like @Bhagawan69 #1048 is slightly different.

Interestingly those issues are very similar in nature to #1000 which was a crash bug related to flipping the `ImGuiWindowFlags_NoSavedSettings` flag.

**Comment by ocornut** [comment]
@HasKha @Bhagawan69 Applied this fix. At the moment I can't see any issue with doing so. Thanks!
