### ISSUE TITLE
Avoiding input collisions with game logic

### ISSUE THREAD

**Issue by charliegillies** [ocornut/imgui#1058]
I'm sure this is a question that's been answered before, but for some reason I couldn't find anything about it.

I'm currently building a 2d level editor with imgui and I'm having an issue where the game logic is responding to clicks as well as imgui (e.g. clicking on actors through imgui windows).

Is there a way to tell if ImGui has processed any input actions?

**Comment by ratchetfreak** [comment]
check WantCaptureKeyboard and WantCaptureMouse those will tell you when an imgui widget wants input focus and there are methods to turn it off the next frame for when you want to drag the mouse behind a window.

**Comment by ocornut** [comment]
Please read the FAQ and the doc in imgui.cpp

**Comment by charliegillies** [comment]
@ocornut @ratchetfreak I'm stupid. Thanks guys.

**Comment by charliegillies** [comment]
Fixed and working perfectly. ImGui is awesome, @ocornut - thank you for providing an amazing tool.
