### ISSUE TITLE
Push/Pop user data?

### ISSUE THREAD

**Issue by benblo** [ocornut/imgui#1059]
Is there a way to push custom user data (eg uint64, void*, whatever) that I can consult back later?
I realize I could roll my own, but this seems like a common usecase so maybe it's already possible and I just can't find it.

Here's the scenario: a property editor, I want to always call begin/endProperty, even if the property is not open:
<pre>
	Boolean hasChildren = type.fields.size() > 0;
	if (ImGui_beginProperty(obj, label, hasChildren, "struct"))
	{
		// draw content here...
	}
	ImGui_endProperty();
</pre>
(Sorry it's not C++ but should be readable.)

So I always call endProperty to PopId (and I prefer to keep things symmetrical). But if the tree was open, it also has to TreePop, so I need to figure it out.

Wishful code sample:
<pre>
function Boolean ImGui_beginProperty( String label, Boolean hasChildren, String fieldLabel )
{
	Boolean isOpen = false;
	if (hasChildren)
	{
		ImGui_alignFirstTextHeightToWidgets(); // Text and Tree nodes are less high than regular widgets, here we add vertical spacing to make the tree lines equal high.
		isOpen = ImGui_treeNode(label);
		ImGui_nextColumn();

		ImGui_alignFirstTextHeightToWidgets();
		ImGui_text(fieldLabel);
		ImGui_nextColumn();
	}
	else
	{
		ImGui_alignFirstTextHeightToWidgets(); // Text and Tree nodes are less high than regular widgets, here we add vertical spacing to make the tree lines equal high.
		ImGui_treeAdvanceToLabelPos();
		ImGui_text(label);
		ImGui_nextColumn();

		ImGui_alignFirstTextHeightToWidgets();
		if (fieldLabel.length() > 0)
		{
			ImGui_text(fieldLabel);
			ImGui_nextColumn();
		}
		// else: draw field value
	}

	<b>ImGui_pushUserData(isOpen);</b>
	return isOpen;
}

function ImGui_endProperty()
{
	<b>if (ImGui_popUserData(isOpen))</b>
	{
		ImGui_treePop();
	}

	ImGui_popID();
}
</pre>

**Comment by Flix01** [comment]
> Is there a way to push custom user data (eg uint64, void*, whatever) that I can consult back later?

One way of doing it is using the state storage.
I asked this myself in an old issue: https://github.com/ocornut/imgui/issues/974.

Hope it helps.

**Comment by benblo** [comment]
Thanks, that state storage seems interesting, I'll have to look it up, see what it's meant for and how it's used.
But yeah, as you say I'd rather have a stack than something id-based, I'll probably just make my own.

**Comment by ocornut** [comment]
Hello,

Sorry I thought I had answered this thread but apparently my answer went missing in action.
It doesn't look like you need an extra imgui feature for that. Just using `vector<bool>` with `push_back()`, `pop_back()` should give you that functionality and would be completely under your control. You could also reorganize your code to just store that boolean locally.

**Comment by benblo** [comment]
Yep, ImVector<bool> did the trick.
It will be a little more icky if I start using multiple contexts (which I might), but so far so good.

As for storing locally... not very practical in my context. One pattern I'm experimenting is "bracket" (scoped) structs, that push something on constructor and pop it on destructor... makes the code much more compact in some situations, especially if you need to return the result of widget (just return directly, no more "cache, pop, return").
