### ISSUE TITLE
Cyrillic symbols in textboxes.

### ISSUE THREAD

**Issue by ShovelBox** [ocornut/imgui#1060]
Hi, thanks for your project, its amazing :)

I'm using ImGui_ImplDX11_WndProcHandler for input handling, and everything is fine, except one thing:
When I'm trying to type with russian keyboard layout, I'm getting bad symbols.

Your demo project also shows bad symbols (questions symbols) 

![1](https://cloud.githubusercontent.com/assets/4295311/23791739/ff7f18f2-05a5-11e7-8811-2eee2f910125.gif)

Could you point me on right direction? How to resolve?

**Comment by ocornut** [comment]
Hello,

Did you read the FAQ and documentation? 
Did you load a Cyrillic font with the correct Cyrillic glyphs loaded? 

First check if you can display Cyrillic characters (using UTF-8 C++11 literal, such as `ImGui::Text(u8"insert text here");`). If you can display them not input them, the problem lies in your application not passing the correct Unicode codepoint to io.AddInputCharacter().

-Omar

**Comment by ShovelBox** [comment]
![image](https://cloud.githubusercontent.com/assets/4295311/23792739/1effffb2-05aa-11e7-9644-a42690db3e9c.png)

Its ok, I can display russian symbols. Yes, I've loaded correct font  with Cyrillic glyphs

**Comment by ShovelBox** [comment]
``` ImGuiIO& io = ImGui::GetIO();
        ImFontConfig font_cfg;
        font_cfg.FontDataOwnedByAtlas = false;
        font_cfg.MergeMode = false;
        font_cfg.MergeGlyphCenterV = true;
        io.Fonts->AddFontFromMemoryTTF(Roboto_TTF_Data, RobotoFont_TTF_DataSize, 18.0f, &font_cfg, io.Fonts->GetGlyphRangesCyrillic());
        font_cfg.MergeMode = true;
        font_cfg.PixelSnapH = true;
        font_cfg.MergeGlyphCenterV = true;
        static const ImWchar icons_ranges_md[] = { ICON_MIN_MD, ICON_MAX_MD, 0 };
        io.Fonts->AddFontFromMemoryTTF(Material_TTF_Data, MaterialFont_TTF_DataSize, 18.0f, &font_cfg, icons_ranges_md);

**Comment by ShovelBox** [comment]
I'm simply pass everything from
WndProcHook(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
to ImGui_ImplDX11_WndProcHandler(hWnd, message, wParam, lParam)

``` 
case WM_CHAR:
        // You can also use ToAscii()+GetKeyboardState() to retrieve characters.
        if (wParam > 0 && wParam < 0x10000)
            io.AddInputCharacter((unsigned short)wParam);
        return true;
    }
```

do u think something wrong with wParam?

**Comment by ocornut** [comment]
Print the value and see by yourself if they are valid Unicode codepoints (and _not_ legacy local page codepoints in the 0x80...0xFF range). I think with Windows you need to compile your application with Unicode libraries to get valid unicode in the WM_CHAR message.

**Comment by ShovelBox** [comment]
![image](https://cloud.githubusercontent.com/assets/4295311/23793402/d2139d64-05ac-11e7-86f0-137981a2d3f8.png)

Right now, MultiByte charset is enabled.
I'll try to enable Unicode.

**Comment by ocornut** [comment]
Please try to do your research thoroughly and post collated results instead of making successive posts as they happens. (Some people receive notifications for those messages)

**Comment by ShovelBox** [comment]
Sorry for that. I'll try to resolve this problem in next few days and let you know about results. If you think its better to close this issue now, please do.

**Comment by ShovelBox** [comment]
![1](https://cloud.githubusercontent.com/assets/4295311/23796007/4634fc3a-05ba-11e7-9f5c-1ef158e2a5db.gif)

It works, changed Character Set to Unicode.
Thanks for help

**Comment by sergey-zero** [comment]
I have same issue, i can't change project to unicode, and found this resolution
```
	case WM_CHAR:
			wchar_t wch;
			MultiByteToWideChar(CP_ACP, MB_PRECOMPOSED, (char*)&wParam, 1, &wch, 1);
			io.AddInputCharacter(wch);
```

**Comment by Frozk** [comment]
Hi is this working for GE europe?

**Comment by potoshopDev** [comment]
in C++20 not working? (u8)
https://learn.microsoft.com/en-us/cpp/cpp/string-and-character-literals-cpp?view=msvc-170

// Before C++20
const char* str1 = u8"Hello World";
const char* str2 = u8"\U0001F607 is O:-)";
// C++20 and later
const char8_t* u8str1 = u8"Hello World";
const char8_t* u8str2 = u8"\U0001F607 is O:-)";

**Comment by PathogenDavid** [comment]
@potoshopDev C++20 introduced a breaking change that made it so `u8` string literals are no longer assignable to `const char*`.

The easiest solution for MSVC is to disable the breaking change with [`/Zc:char8_t-`](https://learn.microsoft.com/en-us/cpp/build/reference/zc-char8-t?view=msvc-170).

Alternatively you can manually cast the `u8` string to `(const char*)`.

See https://github.com/ocornut/imgui/issues/5881 for details.
