### ISSUE TITLE
Is there any way to check whether a window has just been made active?

### ISSUE THREAD

**Issue by haferburg** [ocornut/imgui#1061]
In response to user input I am creating a window that has an `InputText`. I would like the text to automatically starts out as selected when the window pops up, so I want to call `SetKeyboardFocusHere`, but only if the window has not been visible (active(?)) before.

This hack seems to do the trick:

    bool ImGui::WindowWasActive(const char* name) {
      ImGuiWindow* window = FindWindowByName(name);
      return window != 0 && (window->WasActive || window->Active);
    }

Is there an official way of doing this? Adding an optional `bool*` parameter to `Begin` might be cleaner.

**Comment by ocornut** [comment]
@haferburg 
I have just added `IsWindowAppearing()` for that purpose.

Note that there's another issue (#343, where `SetKeyboardFocusHere()` breaks if the item is clipped) but the specs of `IsWindowAppearing()` returning false when first doing the hidden-resize then true once makes it a non-issue here.
