### ISSUE TITLE
How can I do a "Multi-line Text Input" with "Word Wrapping"?

### ISSUE THREAD

**Issue by adricoin2010** [ocornut/imgui#1062]
Hello, I would like to know how I can add `Word Wrapping` to `Multi-line Text Input`, without adding `\n` to the text string.

If the function is not available, it would be a good addition in the future.

Thank you all. Sorry for my English.

**Comment by ocornut** [comment]
This is not possible at the moment and won't be possible for a while. Multi-line text input basically needs a rewrite and we can consider supporting wrapping there.
Closing and merging with duplicate #952

**Comment by ocornut** [comment]
I have posted a WIP branch for word-wrapping here:
https://github.com/ocornut/imgui/issues/3237#issuecomment-3245649332
Please send feedback if you can!

**Comment by ocornut** [comment]
FYI `ImGuiInputTextFlags_WordWrap` is now part of the public API.
