### ISSUE TITLE
C++ SFML Issue with drawing Sprite to Window well using ImGui::Render()

### ISSUE THREAD

**Issue by UchihaKite** [ocornut/imgui#1064]
Good Morning,
If this is an obvious fix, I apologize, this will only be my first time using ImGui. So, I set up a little project and decided to give ImGui a shot. Originally I only had the basic ImGui window and a CircleShape drawing to the screen. It was until I replaced the CircleShape with a Sprite, that I noticed the Sprite would draw to the screen and instantly disappear. At first I thought this was an issue with my code, however, when I commented out ImGui::Render(), the Sprite drew to the screen and didn't disappear. Is their something special I have to do in order to draw a sprite to the window and use an ImGui window?
![imguiissue](https://cloud.githubusercontent.com/assets/20590483/23867482/3e228f8c-07d9-11e7-8425-cedc83b52eab.JPG)

**Comment by ocornut** [comment]
I don't understand the questions. I don't know what `CircleShape` or `Sprite` refers to, they are probably SFML concepts and not ImGui concepts therefore it is hard to help without more detailed explanation and a functionally repro. Maybe ask to someone who knows about SFML and the SFML integration you are using.

**Comment by UchihaKite** [comment]
Thank you for the quick reply, I will redirect my question accordingly. If it is all the same to you, could you keep this open? Just in case someone who knows the answer comes in? Thank you for your time!

**Comment by ocornut** [comment]
Let's keep it open for a little while, yes.

**Comment by colesnicov** [comment]
Check [https://www.sfml-dev.org/tutorials/2.0/window-opengl.php#using-opengl-together-with-the-graphics-module](https://www.sfml-dev.org/tutorials/2.0/window-opengl.php#using-opengl-together-with-the-graphics-module)

Also may in order:

```
ImGui::Begin();
...
ImGui::End();

m_window->clear();
m_window->draw(...);
window->resetGLStates();
ImGui::Render();
m_window->display();
```
?

**Comment by UchihaKite** [comment]
Aha! That worked! Thanks for letting me know man! Really means a lot that you took the time to answer my question.
