### ISSUE TITLE
one frame lag

### ISSUE THREAD

**Issue by benblo** [ocornut/imgui#1066]
OK, so I'm using ImGui in an app (embedded in Qt, ugh) where I don't control the update/render loop (grate fun! much frustrate!).
Basically I can only listen to mouse/kb events, request a redraw, and run imgui in the paint event. And then I never get another redraw until another mouse/kb comes.

So, I notice a few little quirks :) ! Like the InputText carret only blinks when the mouse moves... and widgets drawn upstream according to a state that gets changes downstream are out of sync. Eg, the InputInt draws the value, then the +/- buttons: if I click those buttons, the state is changed, but the field's text is not.
I have quite a few similar cases, eg a "toggle all" checkbox in the header of column grid is out of sync when one of the row checkboxes gets toggled, etc.
It's actually surprising how often you *don't* move the mouse at all after a click (when I do, I get the redraw, yay).

Now I'm not saying that's wrong, I think this is inherent of immediate mode (right?). 
It can be a little confusing for the user though. One workaround I could see is, when I detect such cases (basically, as soon as *anything* changes), flush the current frame (how would I do that?), and start over before render.
Can anyone think of a less drastic way?

**Comment by Pagghiu** [comment]
Can you schedule some kind of timer on the event loop to request a redraw at a later time?

**Comment by ocornut** [comment]
Yeah you should probably just redraw the one or few frames.

> Like the InputText carret only blinks when the mouse moves... 

Well it is only going to blink if you render. How would it blink it you are not re-rendering?

There was an old discussion suggesting we could add a timer to let the user know if render is desirable (perhaps with a timer if you want to render a blinking cursor in minimum render steps but that would make cpu consumption very uneven).
https://github.com/ocornut/imgui/issues/71#issuecomment-101236857

**Comment by ratchetfreak** [comment]
Here's a little hint, you can run Imgui code outside the paint event.

You set the io.RenderDrawListsFn to null and instead use ImGui::GetDrawData() in the paint function.

Then you can start use startTimer(10) to make Qt run the timerEvent function every 10 milliseconds. The timerEvent function will then hold the newFrame/Render imgui code. And you can request a repaint at the end.

**Comment by benblo** [comment]
Thanks all.

> Well it is only going to blink if you render. How would it blink it you are not re-rendering?

@ocornut sure I understand why it doesn't blink, it's just funny to notice.

> Here's a little hint, you can run Imgui code outside the paint event.
> You set the io.RenderDrawListsFn to null and instead use ImGui::GetDrawData() in the paint function.

@ratchetfreak ... not sure I follow. I already control when to call ImGui::Render(), what would setting 
RenderDrawListsFn to null accomplish?

> Then you can start use startTimer(10) to make Qt run the timerEvent function every 10 milliseconds. The timerEvent function will then hold the newFrame/Render imgui code. And you can request a repaint at the end.

Yeah, as I said this is very peculiar context, I don't control this Python code.
This is for [Fabric Engine](http://fabricengine.com/), which integrates into DCCs (eg Maya) and only gives me a hook into the viewport, with kb/mouse and render events.

I'm currently fiddling with all this mess to try and hook my own Qt widget so I have better control of all this...

**Comment by meshula** [comment]
You can post a paint event to your qwidget on a 10ms timer as @ratchetfreak suggests, although it should be sufficient to just do your rendering within paint in the normal way.

http://doc.qt.io/qt-4.8/qwidget.html#paintEvent

**Comment by ocornut** [comment]
@benblo Are you happy with us closing this topic?

**Comment by benblo** [comment]
Yes sorry, should have done it already!
