### ISSUE TITLE
Add an extra labelling syntax for string that are visible but not part of ID

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#107]
Currently there is a syntax that allows including extra ID info that are not visible to the end-user,

Common case

    Label
    // display "Label"
    // use "Label" for ID

vs

    Label##HiddenPart
    // display "Label"
    // use "Label##HiddenPart" for ID

Introduce another syntax to handle the other case, aka "VaryingLabel" + "StaticID""
May be using ### ?

    Label###HIddenPart
    // display "Label"
    // use "###HiddenPart" for ID

Unlikely to affect backward compatibility.

**Comment by ocornut** [comment]
One could argue we could change the current behaviour of ## to be the new expected behaviour and keep a single syntax.

It would break backward compatibility if users used label such as "Hello##1" and "World##1", such change would make the identifier collide.

Has anybody reading this used this feature?

**Comment by dkrikun** [comment]
Hi, has this feature been documented?
In fact, I learned the hard way that the label is used to id a widget.
Can it be possible to explicitly supply a handle as a separate argument?

**Comment by ocornut** [comment]
> Can it be possible to explicitly supply a handle as a separate argument?

Hard to answer this question from a general perspective. Most functions takes a label/id and that would mean duplicating all functions and would go against a lot of the simplicity of ImGui.
You can use PushID/PopID to distinguish ids or the ## syntax. Isn't it enough?

It is documented in the blurbs at the top of imgui.cpp but yeah, it's common to learn it the hard way first. I might consider to add automatic sequential id-differenciation when there is a conflict, that would work in most cases but it may confuse the user further.

**Comment by dkrikun** [comment]
Now that I know about PushID/PopID and the ## syntax I think it is most appropriate not to break the existing api (or duplicating all functions).
Used to add terminal spaces to avoid id collisions XD

**Comment by ocornut** [comment]
OK this is now done. 

I have also updated the FAQ section and added a small demo using those features on window titles.

![animated title](https://cloud.githubusercontent.com/assets/8225057/6543582/fa0dc7c6-c518-11e4-91bc-682787f2dfd3.PNG)


```
 A primer on the meaning and use of ID in ImGui:
 
   - widgets require state to be carried over multiple frames (most typically ImGui often needs to remember what is the "active" widget).
     to do so they need an unique ID. unique ID are typically derived from a string label, an integer index or a pointer.
     
       Button("OK");        // Label = "OK",     ID = hash of "OK"
       Button("Cancel");    // Label = "Cancel", ID = hash of "Cancel"

   - ID are uniquely scoped within Windows so no conflict can happen if you have two buttons called "OK" in two different Windows.

   - when passing a label you can optionally specify extra unique ID information within string itself. This helps solving the simpler collision cases.
     use "##" to pass a complement to the ID that won't be visible to the end-user:

       Button("Play##0");   // Label = "Play",   ID = hash of "Play##0"
       Button("Play##1");   // Label = "Play",   ID = hash of "Play##1" (different from above)

     use "###" to pass a label that isn't part of ID. You can use that to change labels while preserving a constant ID.

       Button("Hello###ID"; // Label = "Hello",  ID = hash of "ID"
       Button("World###ID"; // Label = "World",  ID = hash of "ID" (same as above)

   - use PushID() / PopID() to create scopes and avoid ID conflicts within the same Window:

       Button("Click");     // Label = "Click",  ID = hash of "Click"
       PushID("node");
       Button("Click");     // Label = "Click",  ID = hash of "node" and "Click"
       for (int i = 0; i < 100; i++)
       {
          PushID(i);
          Button("Click");  // Label = "Click",  ID = hash of "node" and i and "label"
          PopID();
       }
       PopID();
       PushID(my_ptr);
       Button("Click");     // Label = "Click",  ID = hash of ptr and "Click"
       PopID();
      
     so if you have a loop creating multiple items, you can use PushID() / PopID() with the index of each item, or their pointer, etc.
     some functions like TreeNode() implicitly creates a scope for you by calling PushID().

   - when working with trees, ID are used to preserve the opened/closed state of tree nodes.
     depending on your use cases you may want to use strings, indices or pointers as ID. 
      e.g. when displaying a single object that may change over time (1-1 relationship), using a static string as ID will preserve your node open/closed state when the targeted object change.
      e.g. when displaying a list of objects, using indices or pointers as ID will preserve the node open/closed state differently. experiment and see what makes more sense!
```

**Comment by christophe-f8** [comment]
Dear Omar,

This is my first message here so I'd first like to thank you for this wonderful library, it's been VERY useful.

I comment on this closed post because while the PushIP/PopID works well with child windows, it is not supported on top windows. After a quick look in the code it seems not that complicated to add, but since I'm new to Dear imgui I preferred to manage the issue externally (with ##) to not break anything.

Anyway, I thought I should let you know about this should you want to extend the PushID/PopID mechanism to top level windows.

**Comment by ocornut** [comment]
@christophe-f8 I don't understand your message or what you are suggesting. PushID works inside any window.

**Comment by christophe-f8** [comment]
Sorry my explanation was not really good, I should probably have added a little more context.
I'm developing an enhanced layout manager (basically a flexbox layout, like with CSS + other features like separate automatic width/height resizing and minimum size constraints).
To that extent I developed a dialog class and a layout class. The dialog class is rendered using ImGui::Begin/End and within that the nested layouts are rendered using ImGui::BeginChild/EndChild (then, within the layouts, widgets are rendered using Image(), Button() and others).

What I noticed is that within BeginChild the title, parent window name and id (that comes from PushID) are combined to create a unique name, so even if 2 of my layouts have the same title, everything works well.
However, inside Begin the name is used as is. So if I have 2 dialogs with the same names, all the events stop working correctly. I managed to make things work by making sure each dialog has a unique name (I combined the dialog title with some unique ID and ## which works well but adds quite a bit of code on the application side). I was just thinking that it would be great if we could use PushID just before calling Begin to uniquely identify dialogs.

Anyway, that's not a bug, just a suggestion. And maybe I'm missing something (I only used ImGui for few days...)

**Comment by ocornut** [comment]
OK, I misunderstood your original post. This is by design, as there's no relationship between one window on the stack and another one. Begin() can be used recursively (in fact we are doing this at all time, since there's always a `"Debug##Default"` window pushed on the stack at the time of NewFrame(). Begin() can also be used to append to an existing window from multiple locations. 

> I combined the dialog title with some unique ID and ## which works well but adds quite a bit of code on the application side

As a suggestion, this should 1-2 line max with a printf style helper. If you use string you ought to have nice helpers for them. (e.g. with my mini [Str.h](https://github.com/ocornut/str) I'd use a syntax like `Begin(Str30f("WindowName##%08X", id).c_str(), &open)`)

**Comment by christophe-f8** [comment]
I understand. And yes, that's about what I ended up with. But thanks for pointing me out to Str.h, I'll surely use it next time.
