### ISSUE TITLE
When two text inputs are together text is written to both buffers.

### ISSUE THREAD

**Issue by msmshazan** [ocornut/imgui#1070]
I am writing a login window. 

` if (show_login_window)
        {
            ImGui::SetNextWindowSize(ImVec2(200,20), ImGuiSetCond_FirstUseEver);
            ImGui::Begin("Login Window", &show_login_window);
            ImGui::Text("Hello");
         ImGui::Columns(2);
            ImGui::Text("Name :");
            ImGui::NextColumn();
            ImGui::InputText("",&name[0] ,sizeof(name),ImGuiInputTextFlags_AlwaysInsertMode);
            ImGui::Spacing();
            ImGui::NextColumn();
            ImGui::Text("Password :");
            ImGui::NextColumn();
            ImGui::InputText("",&pass[0] ,sizeof(pass),ImGuiInputTextFlags_Password);
            ImGui::Columns(1);
   
            ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
            ImGui::End();
        }
        `
But when I click the input box text is written to both buffers.Which are not the same.

**Comment by ocornut** [comment]
Your text inputs fields have the same identifier.
Please read the FAQ in imgui.cpp at "How can I have multiple widgets with the same label? Can I have widget without a label? (Yes). A primer on the purpose of labels/IDs."

**Comment by msmshazan** [comment]
Oops my bad. Sorry.
