### ISSUE TITLE
Changing the size of the Font, for Buttons.

### ISSUE THREAD

**Issue by UchihaKite** [ocornut/imgui#1071]
Good Afternoon,
I was wondering if it was possible to increase the font size of a button? Just would like to make some things a little easier to read. Thank you in advance for your time!

**Comment by ocornut** [comment]
See https://github.com/ocornut/imgui/issues/1018
Right now the most natural way would be to have 2 fonts and change them with PushFont/PopFont. Fonts are rasterized into bitmaps so "nice" scaling isn't supported yet, which is why there's no PushFontSize/PopFontSize or equivalent call at the moment.

**Comment by BioAbnerUAD** [comment]
Sorry to reopen an old Issue but I wanted to know if it's still the case that I need to push an entire font or if you've managed to create a simpler method. Thanks in advance.
