### ISSUE TITLE
IsWindowHovered listbox detection bug

### ISSUE THREAD

**Issue by jkbz64** [ocornut/imgui#1072]
It seems there is problem with ImGui::IsWindowHovered. It returns false when hovering over listbox widget(also listbox slider) which is obviously placed in window.

**Comment by ocornut** [comment]
Any scrolling section is a child window so you probably want to use `IsRootWindowOrAnyChildHovered()`.
I don't know what a listbox slider is.

**Comment by jkbz64** [comment]
I meant scroll bar not slider, my bad. Ok, thanks for answer.
