### ISSUE TITLE
How to render a web browser in imgui

### ISSUE THREAD

**Issue by wsw364321644** [ocornut/imgui#1075]
Steam achieve web browser in it's overlay. Can I  use Rendering Engine and imgui do the same thing.(Some problems may not be appropriate here.)
If possible :
    1.any suggestion in which Rendering Engine.
    2.Can i have a basic process.( I thougnt Rendering Engine is similar to a gui, get the event and output the texture. if so is there possible to use an existing widget that I can get it's events that i can pass to engine.)

If not is there are any suggestions.

**Comment by ocornut** [comment]
Sorry this question is too unrelated to imgui and the possible answers are too wide.
Short answer: chromium, webkit? it isn't going to be easy.

**Comment by rlabrecque** [comment]
If anyone finds this from this point on then have a look at this tweet: 
https://twitter.com/ocornut/status/890210588600565762
