### ISSUE TITLE
FramePadding in Labels and Text

### ISSUE THREAD

**Issue by jordiexvision** [ocornut/imgui#1081]
The main question here is how hard would it be to allow FramePadding to be applied in some widgets and drawing routines where it is now currently not applied.

Please look at the reference image:
A button (labeled as "button test") has padding, and an inputText ("OSD Text1") also has padding. 
But labels and most importantly `ImGui::Text()` have no padding. Therefore the text renders right at the first pixel.
I have been trying to adjust the padding of labels and text uniformly but I as far as I could see, a lot of modification in ImGui would be required to satisfy my "design maniac" self.

I understand that what I'm looking at may be uncommon, uninteresting or a bad idea in terms of performance. I still would like to know how difficult would it be go get this working.

In my opinion it would be a good idea to introduce a new padding type for those cases so that users can adjust it at their own will.

![2017-03-30 18_13_31-](https://cloud.githubusercontent.com/assets/16813257/24497016/fdae5360-1574-11e7-907c-32dd49595a4c.png)

Here ome of the code i used and also some of the code I tried to fix the issue. Of course I'm not familiar with the internals of ImGui so I didn't have much luck.

	//-----------
	void drawSliderFloat()
	{
		ImGui::PushID(this->getName().c_str());
		ImGui::PushItemWidth(sliderWidth);
	//		ImGui::Text(this->getName().c_str());
		ImGui::SliderFloat(
			"##SliderFloat",	//this->getName().c_str(),
			&this->value,
			this->getMin(),
			this->getMax(),
			this->getName().c_str());
		ImGui::PopItemWidth();
		ImGui::PopID();

		ImGui::SameLine();
		ImGui::PushID(this->getName().c_str());
		ImGui::PushItemWidth(inputIntWidth);
		ImGui::InputFloat("##f1",
			&this->value,
			this->getMin(),
			this->getMax()
		);
		ImGui::PopItemWidth();
		ImGui::PopID();
	}

	void drawTextWrapped()
	{
		ImGui::PushID(this->getName().c_str());
		static float wrap_width = sliderWidth + inputIntWidth + ImGui::GetStyle().ItemSpacing.x;

		//draws with wraping:
		//		ImGui::TextWrapped(str, wrap_width); // it resizes on window scale
		ImGui::PushTextWrapPos(ImGui::GetCursorPos().x + wrap_width);
		ImGui::Text(str);
		//		ImGui::TextLabelled(str);
		ImGui::PopTextWrapPos();

		//		// draw custom frame
		ImGui::GetWindowDrawList()->AddRectFilled(
			ImVec2(ImGui::GetItemBoxMin().x, ImGui::GetItemBoxMin().y),
			ImVec2(ImGui::GetItemBoxMax().x + ImGuiStyleVar_FramePadding, 	ImGui::GetItemBoxMax().y),
			ImColor(0, 255, 255, 25)
		);
		ImGui::PopID();
	}

	void ImGui::RenderTextWrapped2(const ImVec2 pos_min, const ImVec2& pos_max,  const char* text, 	const char* text_end, float wrap_width, ImGuiAlign align)
	{

	// Hide anything after a '##' string
	const char* text_display_end = FindRenderedTextEnd(text, text_end);
	const int text_len = (int)(text_display_end - text);
	if (text_len == 0)
		return;

	ImGuiContext& g = *GImGui;
	ImGuiWindow* window = GetCurrentWindow();

	if (!text_end)
		text_end = text + strlen(text); // FIXME-OPT

	// Perform CPU side clipping for single clipped element to avoid using scissor state
	ImVec2 pos = pos_min;
	const ImVec2 text_size = CalcTextSize(text, text_display_end, false, 0.0f);

	// Align
	if (align & ImGuiAlign_Center) pos.x = ImMax(pos.x, (pos.x + pos_max.x - text_size.x) * 0.5f);
	else if (align & ImGuiAlign_Right) pos.x = ImMax(pos.x, pos_max.x - text_size.x);
	if (align & ImGuiAlign_VCenter) pos.y = ImMax(pos.y, (pos.y + pos_max.y - text_size.y) * 0.5f);

	if (text_len > 0)
	{
		window->DrawList->AddText(g.Font, g.FontSize, pos, GetColorU32(ImGuiCol_Text), text, text_end, wrap_width);
		if (g.LogEnabled)
			LogRenderedText(pos, text, text_end);
	}
	}

	void ImGui::TextLabelledV(const char* fmt, va_list args)
	{
	const ImVec2& size_arg = ImVec2();
	ImGuiButtonFlags flags = 0;
	ImGuiWindow* window = GetCurrentWindow();
	if (window->SkipItems)
		return;

	const char* text_begin = fmt;
	const char* text_end = FindRenderedTextEnd(text_begin);
	const float wrap_pos_x = window->DC.TextWrapPos;
	const bool wrap_enabled = wrap_pos_x >= 0.0f;
	const float wrap_width = wrap_enabled ? CalcWrapWidthForPos(window->DC.CursorPos, wrap_pos_x) : 0.0f;

	ImGuiContext& g = *GImGui;
	const ImGuiStyle& style = g.Style;
	const ImGuiID id = window->GetID(text_begin);
	//	const ImVec2 label_size = CalcTextSize(text_begin, NULL, true);
	//	const ImVec2 label_size = CalcTextSize(text_begin, text_end, true, wrap_width);
	const ImVec2 label_size = CalcTextSize(text_begin, text_end, true, wrap_width);

	ImVec2 pos = window->DC.CursorPos;
	if ((flags & ImGuiButtonFlags_AlignTextBaseLine) && style.FramePadding.y < window->DC.CurrentLineTextBaseOffset)
		pos.y += window->DC.CurrentLineTextBaseOffset - style.FramePadding.y;
	ImVec2 text_size = CalcItemSize(size_arg, label_size.x + style.FramePadding.x * 2.0f, label_size.y + style.FramePadding.y * 2.0f);

	//	const ImRect bb(pos, pos + size);
	//	ItemSize(bb, style.FramePadding.y);
	//	if (!ItemAdd(bb, &id))
	//		return ;

	//	const ImVec2 text_size = CalcTextSize(text_begin, text_end, false, wrap_width);

	// Render (we don't hide text after ## in this end-user function)
	const ImRect bb(pos, pos + text_size);
	ItemSize(bb, style.FramePadding.y);
	if (!ItemAdd(bb, &id))
		return;

	// Renfer text
	RenderTextWrapped2(bb.Min, bb.Max, text_begin, text_end, wrap_width, ImGuiAlign_Center | ImGuiAlign_VCenter);

	// Render frame
	//	RenderFrame(bb.Min, bb.Max, ImGuiCol_ButtonActive, true, style.FrameRounding);
	// Render frame
	ImGui::GetWindowDrawList()->AddRectFilled(
		ImVec2(ImGui::GetItemBoxMin().x, ImGui::GetItemBoxMin().y),
		ImVec2(ImGui::GetItemBoxMax().x + ImGuiStyleVar_FramePadding, ImGui::GetItemBoxMax().y),
		ImColor(0, 255, 255, 25)
	);
	}

	void ImGui::TextLabelled(const char* fmt, ...)
	{
	va_list args;
	va_start(args, fmt);
	TextLabelledV(fmt, args);
	va_end(args);
	}

	/// SliderFloat hack**
	    RenderTextClipped(frame_bb.Min, frame_bb.Max, value_buf, value_buf_end, NULL, ImGuiAlign_Left | ImGuiAlign_VCenter);

**Comment by ocornut** [comment]
Jordi, not interested in this anymore?
I admit I was confused by the report and the provided code.
Normal widget should use `InnerPadding.x` to create space between them and text, and this appears to be the only thing you reported. Combining multiple items horizontally `SameLine()` generally have you pass a spacing too. Technically it is still possible to provide this option but I don't really understand why you would need it without a more clear and detailed explanation.

**Comment by jordiexvision** [comment]
Still interested, but not sure I addressed the issue in the right way. Also I was a bit tired and I didn't explain it very well. I will go back to it and find out if there is another way to achieve what I was looking for. I will try to report it more clearly as well. Thank you!
