### ISSUE TITLE
ImGui::Begin{} ignoring Windowflags?

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1089]
So I did the following and the Begin box literally ignores the Windowflags no matter what I do.

```
ImGui::SetNextWindowSize(ImVec2(1027, 97), ImGuiSetCond_FirstUseEver);
if (ImGui::Begin("title", &Main::showWindow, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_ShowBorders) | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove)
	{
ImGui::End();
}
```

**Comment by ocornut** [comment]
Are you using "title" for title or something else? There's one known specific case if you call your window "Debug" because imgui creates an implicit window called that at the beginning of the frame, so the first flags are used. (i will fix this, the fix is pretty easy)

**Comment by emilo0212** [comment]
Well I just found the issue, if you look at the code I posted above, you can see I put a bracket behind the "ImGuiWindowFlagS_ShowBorders", without noticing. So I just removed it and put it all the way at the end of the code. Stupidity next level :D, sorry for wasting your time.

**Comment by ocornut** [comment]
No worry. When you submit a repro make sure it is actually the code you are using and not the code you think you are using :)
