### ISSUE TITLE
Please clean up printf %p's on non-void* types

### ISSUE THREAD

**Issue by xaxxon** [ocornut/imgui#1090]
```
/home/xaxxon/apb/imgui/imgui.cpp:9677:72: warning: format specifies type 'void *' but the argument has type 'ImDrawCallback'
      (aka 'void (*)(const ImDrawList *, const ImDrawCmd *)') [-Wformat-pedantic]
                        ImGui::BulletText("Callback %p, user_data %p", pcmd->UserCallback, pcmd->UserCallbackData);
                                                    ~~                 ^~~~~~~~~~~~~~~~~~
/home/xaxxon/apb/imgui/imgui.cpp:9726:126: warning: format specifies type 'void *' but the argument has type 'ImGuiWindow *'
      [-Wformat-pedantic]
  ...if (!ImGui::TreeNode(window, "%s '%s', %d @ 0x%p", label, window->Name, window->Active || window->WasActive, window))

```

at least these two, but I don't have the latest builds.   

http://en.cppreference.com/w/cpp/io/c/fprintf

**Comment by ocornut** [comment]
Could you specify your compiler, version, platforms and compiler flags?

It's another counterproductive overzealous warning in my opinion, and should better be ignored with a pragma, rather than cluttering the code in different places.

**Comment by xaxxon** [comment]
the compiler flag is in the error message and I get it on clang 3.9 and 3.9.1 on mac and linux.   -Wformat-pedantic is presumably part of -pedantic, since I don't explicitly turn on format-pedantic.

**Comment by ocornut** [comment]
Ignoring that warning now. 
Also see, e.g. http://clang-developers.42468.n3.nabble.com/The-p-conversion-and-cast-to-void-td4044226.html

**Comment by ocornut** [comment]
And obviously touching anything compiler-specific breaks something, so ignoring that warning created new warnings on older versions of Clang. Fixed.
