### ISSUE TITLE
API/ABI changes review for imgui

### ISSUE THREAD

**Issue by lvc** [ocornut/imgui#1091]
May be useful for tracking API/ABI changes in the library: https://abi-laboratory.pro/tracker/timeline/imgui/

The report is created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

Thank you.

![imgui-1](https://cloud.githubusercontent.com/assets/1517837/24825640/5208cc50-1c33-11e7-9a24-ce70e8d35e2b.png)

![imgui-2](https://cloud.githubusercontent.com/assets/1517837/24825643/5754a1f2-1c33-11e7-895c-9b00972e8f3b.png)

## Environment
* Linux x86_64
* GCC 4.9
* imgui 1.30 and higher

**Comment by ocornut** [comment]
Thank you for the info. Will keep this tool in mind, may be of use sometimes.

Dear ImGui isn't concerned by ABI compatibility at all so its not really the sort of project where those numbers matters the same way as your typical widespread eg: DLL.
