### ISSUE TITLE
How can I make my tabs (buttons) square and not effect rest of style?

### ISSUE THREAD

**Issue by Skrrt** [ocornut/imgui#1095]
So basically I think it's ImGui::GetStyle()->AntiAliasedShapes = true; that makes it remove the corners from checkboxes,etc. Im wondering how to only apply this to my buttons that I am using as tabs eg; 

`void MainWindow()
{
	if (!showMainWindow)
		return;

	static int page = 0;
	ImGui::SetNextWindowSize(ImVec2(960, 645), ImGuiSetCond_FirstUseEver);
	if (ImGui::Begin("Hero Quest", &showMainWindow, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar))
	{
		const char* tabs[] = {
				"Home",
				"Inventory",
				"Bank",
				"Teleport",
				"Misc",
		};
		int tabs_size = sizeof(tabs) / sizeof(tabs[0]);

		for (int i = 0; i < tabs_size; i++)
		{
			ImVec2 windowSize = ImGui::GetWindowSize();
			int width = windowSize.x / tabs_size - 9;

			int distance;
			if (i == page)
				distance = 0;
			else
				distance = i > page ? i - page : page - i;

			ImGui::GetStyle().Colors[ImGuiCol_Button] = ImVec4(0.10f, 0.09f, 0.12f, 1.00f);

			if (ImGui::Button(tabs[i], ImVec2(width, 0)))
				page = i;

			ImGui::GetStyle().Colors[ImGuiCol_Button] = ImVec4(0.10f, 0.09f, 0.12f, 1.00f);
			
			if (i < tabs_size - 1)
				ImGui::SameLine();
		}

		ImGui::Separator();

		switch (page)
		{
			case 0:
				HomeTab();
				break;
			case 1:
				InventoryTab();
				break;
			case 2:
				BankTab();
				break;
			case 3:
				TeleportTab();
				break;
			case 4:
				MiscTab();
				break;
		}

		ImGui::End();
	}
}`

Id like to make the tabs square. and truly have no idea what to do to make it work

**Comment by ocornut** [comment]
Hello, I do not even understand your question. Please provide more context and/or screenshots and/or standalone repro and/or a clearer explanation.

The shape of most items is rectangle when `style.FrameRounding` is 0.0 otherwise rounded. You can use `PushStyleVar(ImGuiStyleVar_FrameRounding, xxx).` to adjust this value and `PopStyleVar()` to restore it.
