### ISSUE TITLE
Center Horizontally?

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1098]
I'm trying to center 3 checkboxes horizontally based on the windows width.

I did try to search and I even looked through demo.cpp, but I might have missed it.
Here's my current code:

```
  ImGui::Separator();
  int currentwidth = ImGui::GetWindowSize().x;
  int checkboxes = 3;
  int nextwidth = (currentwidth-(currentwidth*2))/checkboxes;

  ImGui::PushItemWidth(nextwidth);
  ImGui::Checkbox("1 | ", &Settings::1);
  ImGui::SameLine();
  ImGui::Checkbox("2 | ", &Settings::2);
  ImGui::SameLine();
  ImGui::Checkbox("3", &Settings::3);
  ImGui::PopItemWidth();
  ImGui::Separator();
```

**Comment by colesnicov** [comment]
Hi.
Sorry for english...

I think that you could calculate the dimensions of each element is added together into a pile and consequently it correctly centered ..

Why
```
int currentwidth = ImGui::GetWindowSize().x;
int nextwidth = (currentwidth-(currentwidth*2))/checkboxes;
```
?
Explane
```
int currentwidth = 800px;
int nextwidth = (800 - (800 * 2)) / 3;
```

**Comment by emilo0212** [comment]
So it could be easier to change the size of the menu whenever I'd want, so I just declared 2 ints.

**Comment by emilo0212** [comment]
I don't know to be honest, I just went with common sense and logic and thought dividing half the size of the monitor in negative numbers with the amount of arrays would be = dividing the space between each array.

**Comment by colesnicov** [comment]
If you try?

```
float startx = (screensize - ( (checkboxsize * 3) + (indent * 2) ) ) / 2;
ImGui::SetCursorPosX(startx);
ImGui::PushItemWidth(nextwidth);
ImGui::Checkbox("1 | ", &Settings::1);
ImGui::SameLine();
...
```

or similar...
