### ISSUE TITLE
[Question] How does dear ImGui render text?

### ISSUE THREAD

**Issue by zwcloud** [ocornut/imgui#1101]
Does dear ImGui uses some cache? Or just build the glyph rects on the fly every frame?

I'm reading the source code and it seems the answer is the latter one. But I'm not quite sure.

-------------------------

Just profiled `ImGui::TextUnformatted` and it's really fast. It only uses less than 0.02ms per text on average:

> 0.006247
> 0.004016
> 0.010263
> 0.006247
> 0.006247
> 0.004016
> 0.016064

**Comment by ocornut** [comment]
Yes we render the glyphs every frame. 
It didn't feel necessary to use a cache but it might happen in the future for some things.
