### ISSUE TITLE
Issue with rendering callback optimization 

### ISSUE THREAD

**Issue by rickyviking** [ocornut/imgui#1106]
I'm using a rendering callback to draw ImGui.

As in my callback I'm also cleaning up some stuff, I'd need it to be called every frame.
Instead, there is an optimization which doesn't invoke the callback when there's nothing to draw for the current frame:
https://github.com/ocornut/imgui/blob/master/imgui.cpp#L2785

Do you think it's possible to remove the check against zero, and invoke the callback regardless?
Thank you

**Comment by ratchetfreak** [comment]
You can instead do 

```C++
ImGui::Render();
your_render_callback(ImGui::GetDrawData());
```

**Comment by ocornut** [comment]
As pointed by ratchetfreak, you can just set `io.RenderDrawListsFn = NULL;` and call your code yourself given `ImGui::GetDrawData()`.

Or you can call your "cleaning" code after `ImGui::Render()` as well?

I think most users would find the current behavior more desirable.
