### ISSUE TITLE
How can I decide ListBox height and weight?

### ISSUE THREAD

**Issue by coly-damri** [ocornut/imgui#1107]
const char* listbox_items[] = { "Apple", "Banana", "Cherry", "Kiwi", "Mango", "Orange", "Pineapple", "Strawberry", "Watermelon" };
        static int listbox_item_current = 1;
        ImGui::ListBox("listbox\n(single select)", &listbox_item_current, listbox_items, IM_ARRAYSIZE(listbox_items), 4);

I have tried this example. They look good but does't known how define height and weight.
plz Help!

sorry for my english skill

**Comment by ocornut** [comment]
Width is defined like other standard widget with `ImGui::PushItemWidth()`. Use `PushItemWidth(-1)` to right align if you don't want a label showing.

Height is the last parameter (that you set to 4) defined in number of items.

Look at the code for `ListBox()` if you want to create something very custom.

**Comment by coly-damri** [comment]
Thank you for The Answer! Your ImGui is very very useful!

**Comment by Cazadorro** [comment]
Does not appear to actually extend list-box beyond a certain size.  Can limit it, but not change size beyond some arbitrary maximum (it looks like 7 or 8 items), at least when using the ListBoxHeader method of creating a listbox.
