### ISSUE TITLE
Pointer/buffer to selected text in InputText() ?

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#1109]
Apologies in advance if I have missed something obvious here.

What is the most appropriate way to see/access what text has been selected by the user in an InputText() field so I can make a copy of it.

( in picture attached, the text 'R19' )
![ss](https://cloud.githubusercontent.com/assets/5660591/25308936/4a597b40-2803-11e7-982d-0d7af261dab8.png)

**Comment by inflex** [comment]
Looks like I'm a moron. ctrl-c/v already do seem to work.  Sorry.

**Comment by ocornut** [comment]
There is an answer to your question (callbacks allow retrieving the cursor/selection information) but this is a good reminder of why you ought to always explain the context and what you are trying to achieve.  :)

**Comment by colesnicov** [comment]
It looks like a good idea. I would love if I had available some pointer with which I had access to the currently selected text in the field.

**Comment by ocornut** [comment]
This is what the callback is giving you.
