### ISSUE TITLE
Style Editor prints non-existing ImGuiCols

### ISSUE THREAD

**Issue by xythobuz** [ocornut/imgui#111]
When printing all colors to TTY using the Style Editor, it outputs something like this:

    // ...
    style.Colors[ImGuiCol_CheckBgHovered] = ImVec4(1.00f, 0.40f, 0.40f, 0.45f);
    style.Colors[ImGuiCol_CheckBgActive] = ImVec4(0.65f, 0.50f, 0.50f, 0.55f);
    style.Colors[ImGuiCol_CheckSelected] = ImVec4(0.90f, 0.90f, 0.90f, 0.50f);
    // ...

These don't exist. You probably meant CheckHovered, CheckActive and CheckMark?

**Comment by ocornut** [comment]
Oops, mismatching strings in GetStyleColName(). Fixed, thanks!
