### ISSUE TITLE
AddFontFromTTF

### ISSUE THREAD

**Issue by ohelli** [ocornut/imgui#1115]
In my ofApp,  I am using 
`ImFont* font = io.Fonts->AddFontFromFileTTF("Cousine-Regular.ttf", 22.0f);` 

to add a font to my project and have received the an assertion failure in **Line 1196** of **imgui_draw.cpp**. I am assuming the path is incorrect, meaning the file cannot be found and therefore the assertion fails. At the moment, the .ttf file is in the same directory as code above. Should I be using another path?
Thanks in advance!

**Comment by ocornut** [comment]
Hello,

> the .ttf file is in the same directory as code above

That statement doesn't fully make sense. What you need to consider is what is the current directory of your running application at the time this is called. You can test with fopen() and would receive the same failure to open if the file doesn't exist. Depending on your ide/debugger configuration your startup directory may be the same as the .exe directory or something different. This is what you want to figure out first.
