### ISSUE TITLE
How do I use binary_to_compressed_c.cpp

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1121]
I'm trying to apply icons to imgui with AddFontFromMemoryCompressedTTF, although I don't know how I can export the binary from the TTF file, using the binary_to_compressed_c.cpp works apparently but I don't understand how I can use it. Could someone give an example?

**Comment by ericoporto** [comment]
On Linux it's actually `g++` and not `gcc` (the command on the comment pushed above).
