### ISSUE TITLE
How do I center the horizontal & vertical length of a buttons' text?

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1123]
I'm using the style.ButtonTextAlign, but when it comes to the buttons where I use icons, they're just too vertically high, I was wondering if I could specifically change the vertical length of some specific button labels.

**Comment by ocornut** [comment]
If you are merging icon font into a normal font try to make the icon the same size at the main font.
You can use `style.FramePadding` or pass an explicit size to `Button()` to adjust their size.

PS: Please don't recycle topics into different questions this way. The fast rate of your questions and their closure (or renaming/recycling, here) suggest that you are posting before doing serious research.

**Comment by emilo0212** [comment]
I apologize for the fast change of subject, I was in an urge and I couldn't figure it out =/

I have 5 main buttons with icons, which are the buttons with the icons, and I want them to be bigger than the other ones, but setting the size of the button label to 30 or over makes it too high vertically, and I've already tried setting style.FramePadding to 4, 3 and others as well. Still doesn't work =/

![5f91a76f0532697191bdf9f667fd20eb](https://cloud.githubusercontent.com/assets/25754141/25616872/74296c8a-2f3f-11e7-8ad2-4a69da9b03a5.png)

**Comment by LWSS** [comment]
hi @emilo0212 :^)
