### ISSUE TITLE
Remove or indirect reference to IO functions to save memory

### ISSUE THREAD

**Issue by greggman** [ocornut/imgui#1124]
IMGUI currently uses fprintf, fopen, fclose, printf, and a other dependencies (so no, it doesn't actually have zero dependencies 😉)

Have you thought about doing it like the STB font library you included and making all of those replaceable? STB does it like this

```
   #ifndef STBTT_malloc
   #include <stdlib.h>
   #define STBTT_malloc(x,u)  ((void)(u),malloc(x))
   #define STBTT_free(x,u)    ((void)(u),free(x))
   #endif

   #ifndef STBTT_assert
   #include <assert.h>
   #define STBTT_assert(x)    assert(x)
   #endif

   #ifndef STBTT_strlen
   #include <string.h>
   #define STBTT_strlen(x)    strlen(x)
   #endif

   #ifndef STBTT_memcpy
   #include <memory.h>
   #define STBTT_memcpy       memcpy
   #define STBTT_memset       memset
   #endif
```

Have you considered doing the same in IMGUI ?

     #ifndef IMGUI_IO
         #include <stdio.h>
         typedef File IMGUIFile; 
         #define IMGUIopen fopen
         #define IMGUIclose fclose
     #endif

or something along those lines?

**Comment by ocornut** [comment]
It's not advertised as "zero dependency" (which would mean nothing tbh) but "minimal dependencies" :)

Are you in a situation where you actually need to save memory and doing it would help you?

I think it'd be extra hassle/maintenance (forever, for me), would make the top of the header less friendly, and the sort of the user who actually care about this are the sort of users who wouldn't use a C++ library in the first place. So I'd very much rather not do it unless there is a great reason to do it (and maybe a serious user behind the request). 

Note that malloc, free and assert are already replaceable, as this is very common for game programmers to change them. (by the way the replacement method for malloc will probably change in the future, as the current way is causing confusion/issues when using multiple contexts).

But I don't know many reasonable people who are not using memcpy/memset :)

**Comment by greggman** [comment]
Well it does say *no external dependencies*. So I guess that depends on your definition of "external" 😁

It's just nice not to have to hack the code to remove those external dependencies on a platform that doesn't have fopen or app that doesn't need file support. Here's an example of how much memory it takes

```
-rw-r--r--  1 gregg  staff     138 May  2 19:58 test-fopen.cc
-rw-r--r--  1 gregg  staff  119056 May  2 20:01 test-fopen.js
-rw-r--r--  1 gregg  staff   15357 May  2 20:01 test-fopen.wasm
-rw-r--r--  1 gregg  staff      72 May  2 19:57 test-fprintf.cc
-rw-r--r--  1 gregg  staff   43672 May  2 20:01 test-fprintf.js
-rw-r--r--  1 gregg  staff   13111 May  2 20:01 test-fprintf.wasm
-rw-r--r--  1 gregg  staff      63 May  2 19:56 test-printf.cc
-rw-r--r--  1 gregg  staff   43832 May  2 20:01 test-printf.js
-rw-r--r--  1 gregg  staff   26228 May  2 20:01 test-printf.wasm
-rw-r--r--  1 gregg  staff      61 May  2 19:56 test-puts.cc
-rw-r--r--  1 gregg  staff   43660 May  2 20:01 test-puts.js
-rw-r--r--  1 gregg  staff   13600 May  2 20:01 test-puts.wasm
-rw-r--r--  1 gregg  staff      46 May  2 19:56 test-stdio.cc
-rw-r--r--  1 gregg  staff   43664 May  2 20:01 test-stdio.js
-rw-r--r--  1 gregg  staff   12608 May  2 20:01 test-stdio.wasm
-rw-r--r--  1 gregg  staff      27 May  2 19:55 test.cc
-rw-r--r--  1 gregg  staff   43640 May  2 20:02 test.js
-rw-r--r--  1 gregg  staff   12608 May  2 20:02 test.wasm
```

* test is just a empty main function
* test-stdio is the same empty main function but includes stdio.h
* test-puts adds a call to `puts`
* test-printf calls `printf`
* test-fprint calls `fprintf(stdout...`
* test-fopen calls `fopen, fread, fclose`

You can see referencing fopen/fread/fclose adds 76k to the code.

76k might not sound like much but Google has done research showing that for every k removed X% more people download your app. Since I'm not using the file features it would be nice if there was a way to turn it off. Of course I can just go hack teh codez. I just thought I'd bring it up. It seems simple and the beloved STB libraries do it so there is certainly precedent.

**Comment by ocornut** [comment]
Well but in your use case (which you discussed to me, and it isn't a "mass use case") those 76K wouldn't make any difference, so your case doesn't seem like it makes a difference.?

We are using and need sprintf (or vsnprintf) and perhaps a lot of that printf code wouldn't be removable either way.

It seems simple but - I have 6+ months of full-time work listed in those open issues, and that's the sort of stuff than add a small overhead that we can almost never remove. Future code would breaks often, code would be more alien to the casual reader/contributors, etc. The rare edge cases + maintaining compilable examples are already often taking more time than actually working on the libraries features so it's my role to avoid that feature creep :)

If that feature is going to be used by 0.1% of the most knowledgable users, for a non critical gain, then perhaps user adding #define in `imconfig.h` to redirect those symbols to dummy symbols would work?

**Comment by greggman** [comment]
"isn't a mass use case". hmmm. I'll be more people view the stuff once up than the the majority of apps get downloads 😜

But okay, it's not a big deal. I just thought I'd ask.

**Comment by ocornut** [comment]
It's a fair request, I keep those things in mind. Thanks and sory!

**Comment by pdoane** [comment]
It's not a big deal for us, but we would redirect calls to the standard library if it were made available.  Probably the biggest advantage for would be sprintf() as that's a fairly large chunk of code.

**Comment by ocornut** [comment]
Linking this thread to #1038 (printf should be replaceable somehow, by stb_printf or your own stuff)
