### ISSUE TITLE
Including imgui.h multiple times results in redefinition errors

### ISSUE THREAD

**Issue by maluramichael** [ocornut/imgui#1125]
Currently i'am working on a little framework and a game which uses that framework. The framework now includes the imgui.h and my game the header file which uses the imgui.h. Now when i add imgui.h to another file in my framework i cannot compile anymore because my setup does not recognises the #pragma once statement.

Is there a hint how to fix this or maybe my compiler is setup wrong?

```sh
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

**Comment by ratchetfreak** [comment]
you can add include guards to imgui.h yourself.

**Comment by paulsapps** [comment]
AppleClang 8.0.0.8000042 should support #pragma once directive

**Comment by maluramichael** [comment]
@ratchetfreak yea of course. But i would like to have a place for imgui on my drive as a repo, update it via `git pull` and don't want to fix this problem every time. I don't think @ocornut would replace #pragma once with an include guard 😄

**Comment by ocornut** [comment]
Could you post your actual error? I have never seen Clang not supporting pragma once.

**Comment by maluramichael** [comment]
Yea now i cannot reproduce it fully. I had to "fake" it a bit. 

What i red so far on the internet is that pragma once works on file level. If i include imgui via submodule in my framework and as a submodule in my other project they are 2 seperate files.

I recreated this error through include imgui.h from 2 different places:
```cpp
#include <Pancake/UI/imgui.h>
#include "../../../../../../../usr/local/include/imgui.h"
```

Like i said i had to include this way to show you the error because i fixed my problem by only use imgui as a submodule in my framework and then include the correct header in my game.

```sh
/Applications/CLion.app/Contents/bin/cmake/bin/cmake --build /Users/michaelmalura/Development/Private/gamecollection/cmake-build-debug --target uitest -- -j 8
Scanning dependencies of target uitest
[ 50%] Building CXX object games/uitest/CMakeFiles/uitest.dir/main.cpp.o
In file included from /Users/michaelmalura/Development/Private/gamecollection/games/uitest/main.cpp:9:
/Users/michaelmalura/Development/Private/gamecollection/games/uitest/../../../../../../../usr/local/include/imgui.h:87:8: error: redefinition of 'ImVec2'
struct ImVec2
       ^
/usr/local/include/Pancake/UI/imgui.h:87:8: note: previous definition is here
struct ImVec2
       ^
In file included from /Users/michaelmalura/Development/Private/gamecollection/games/uitest/main.cpp:9:
/Users/michaelmalura/Development/Private/gamecollection/games/uitest/../../../../../../../usr/local/include/imgui.h:97:8: error: redefinition of 'ImVec4'
struct ImVec4
       ^
/usr/local/include/Pancake/UI/imgui.h:97:8: note: previous definition is here
struct ImVec4
```

**Comment by ocornut** [comment]
You shouldn't duplicate a .h file in the first place.
