### ISSUE TITLE
Columns Separator Position

### ISSUE THREAD

**Issue by vtrbh** [ocornut/imgui#1126]
Is there a way to save the adjustable column separator (vertical line) position or to make a preset position for it so the application would start with this vertical lines in the position that i wanted?

**Comment by ocornut** [comment]
Not at the moment, the only way to work around it is to call `GetColumnOffset` `SetColumnOffset` yourself.

It is an obvious desirable feature that will be part of Columns rework (#125)

**Comment by vtrbh** [comment]
Thanks, i managed to fix my issue with SetColumnOffset
