### ISSUE TITLE
SDL2 keyboard handling issue / backspace key not working

### ISSUE THREAD

**Issue by mefesto** [ocornut/imgui#1127]
I have an SDL2 / Opengl 4+ project and have been integrating (dear) ImGui. Everything is working great except for keyboard input for backspace, del, home, end, pgup, pgdn, and arrows. All other keys seem to work as expected.

I followed the `sdl_opengl3_example` project but noticed that the ctrl, alt, shift keys weren't working correctly when I viewed the results in the `ImGui Demo > Keyboard, Mouse & Focus` window. Also, when typing in a text widget I could not use the backspace or del keys.

After various edits I have the ctrl, alt, shift keys being reported correctly by ImGui but the backspace and other meta-ish keys continue to be unresponsive. Below is a snippet of my keyboard event handler:

```cpp
  if (event.type == SDL_KEYDOWN || event.type == SDL_KEYUP) {
    int key = event.key.keysym.sym & ~SDLK_SCANCODE_MASK;
    bool isKeyDown = (event.type == SDL_KEYDOWN);
    
    io.KeysDown[key] = isKeyDown;

    switch (event.key.keysym.sym) {
      case SDLK_LSHIFT:
      case SDLK_RSHIFT:
	io.KeyShift = isKeyDown;
	break;
      case SDLK_LCTRL:
      case SDLK_RCTRL:
	io.KeyCtrl = isKeyDown;
	break;
      case SDLK_LALT:
      case SDLK_RALT:
	io.KeyAlt = isKeyDown;
	break;
    }
  }
```
Thanks for any help and for a great ImGui tool!

**Comment by mefesto** [comment]
I guess I should also mention that I'm running on:

- Linux Mint 18
- SDL 2.0.4

**Comment by ocornut** [comment]
You aren't settings the KeyShift/KeyAlt/KeyCtrl modifiers correctly.

**Comment by ocornut** [comment]
Sorry I sent the earlier message (by e-mail) earlier.

It's not clear from your message if you were having issues with keyboard modifiers when using unmodified SDL examples, or when working in your own codebase "based on the example" ?
Why not using the provided code?

```
            io.KeyShift = ((SDL_GetModState() & KMOD_SHIFT) != 0);
            io.KeyCtrl = ((SDL_GetModState() & KMOD_CTRL) != 0);
            io.KeyAlt = ((SDL_GetModState() & KMOD_ALT) != 0);
            io.KeySuper = ((SDL_GetModState() & KMOD_GUI) != 0);
```

**Comment by mefesto** [comment]
They seem to work when I view the results in the ImGui demo window. Below is a screenshot where I'm holding the CTRL key down. Note how the KeyMods field properly shows that it enabled:

![screenshot from 2017-05-03 17-03-16](https://cloud.githubusercontent.com/assets/86009/25681553/a9406b24-3022-11e7-9a54-bea899b1666b.png)

Same goes for alt and shift. So that leads me to believe that the modifiers are being set correctly. Is that not true? When the event handler was the same as the example in the project these keys didn't work properly.

Anyway, those modifiers aren't my main concern -- it's the backspace key which doesn't seem to do anything in a text field. I can type all the letters I want and they properly show up in the selected text field but I cannot delete those letters with the backspace key.

**Comment by ocornut** [comment]
OK re-reading your message I think the problem may be due to your KeyMap[] array not being set properly. 

What do you mean by:
> All other keys seem to work as expected.

Which other keys?

The demo window can display the content of KeyDown[] but imgui doesn't know which key is what, which is what the KeyMap[] array does.

**Comment by mefesto** [comment]
> All other keys seem to work as expected

I just meant [a-z], [0-9] and their variants when shift is held down. Those all work.

What doesn't seem to work (for me) is the Backspace, Del, Home, End, PgUp, PgDown, and Arrows.

The way I'm testing this is to go to an `input text` field in the ImGui Demo window under the Widgets section and I type in the first `input text` field I see. The letters appear as normal but if I want to correct what I typed I hit the backspace key which does nothing. The expected behavior is for it to delete the previous character in the `input text` field.

**Comment by mefesto** [comment]
> OK re-reading your message I think the problem may be due to your KeyMap[] array not being set properly.

That was it! Thanks so much!

**Comment by ocornut** [comment]
A-z, 0-9 are characters, not keys.

Make use the KeyMap[] array to setup with the indices pointing to the KeyDown[] array.
