### ISSUE TITLE
Using Treenodes with a for loop.

### ISSUE THREAD

**Issue by Pioneer11X** [ocornut/imgui#1128]
I'm trying to dynamically populate the scene hierarchy, However, I'm running into a few issues.

The code, I have is attached in Picture 1.

![image](https://cloud.githubusercontent.com/assets/10460714/25682573/b25be644-3026-11e7-8fea-0d28f4aa40bd.png)

The result I have is that, the expand tree button ( functionality works only on the first button ). If I click the first button, both of the expands. If I click the second tree, nothing happens. 

This might not warrant an issue here or I might be missing something really basic ( I started using C++ recently ). So, I'm sorry if it is something basic.

**Comment by ocornut** [comment]
Please read the FAQ about duplicate names.

**Comment by Pioneer11X** [comment]
Thanks, that was the issue. Sorry for bothering for such a minor issue.

**Comment by ocornut** [comment]
No problem, it is a rather common issue.
I would like to add a system to detect it but it's not trivial and there would be false positive in some useful cases.
