### ISSUE TITLE
Text + Images

### ISSUE THREAD

**Issue by vtrbh** [ocornut/imgui#1133]
1° Problem: 

I am making a chat for my game using ImGui and i managed to get it working properly using the ExampleAppLog in the imgui_demo as base. I would like to know if there is a way to insert images into the text area like AddLog add texts or overwrite text character combination with an image, and keep them in the same line, the idea is to make emoticons for it (if you wrote :) it would display :smile:), it would be nice if theres already a premade way to get this working or if you could tell me some other way to make it. If theres no way at all i would like to turn this into a request.

2° Problem

Ive done a player list for my game using columns and selectable, and i wanted to insert images into it according to player info/stuff. What i need is to be able to change the image Y position without changing the text position so i could align it, here you can see what i mean:
![untitled 2](https://cloud.githubusercontent.com/assets/24484602/25754366/423518e8-3195-11e7-8006-99121a230013.jpg)

Thanks!

**Comment by ocornut** [comment]
Hello,

I don't understand your question (1) when in question (2) you seem to already have a solution?
You can use SetCursorPosXX functions to move the cursor, or GetWindowDrawList()->AddImage() and draw the image wherever you want them to be.

**Comment by vtrbh** [comment]
the question 1 itself would be to overwrite characters into an image, as i said like if you write :) it would render :smile: 

the second one its a different thing, there i want to be able to align the images to the text but i dont know exactly how, because im not using GetWindowDrawList(), i just drawed it inside a selectable list

**Comment by ocornut** [comment]
Good :) closing this for now.

Another higher-end solution would be to create yourself a simple "rich-text" simpler, where you can insert code.

For example in my game I use custom markups this `This is [b]bold[/b] text` or `Insert a [img]icon.png[/img] here` and I have a function that render those markup blocks.

**Comment by paulsapps** [comment]
You could also use a "magic" char and add the emo icons to your font atlas.

**Comment by simonvanbernem** [comment]
> Good :) closing this for now.
> 
> Another higher-end solution would be to create yourself a simple "rich-text" simpler, where you can insert code.
> 
> For example in my game I use custom markups this `This is [b]bold[/b] text` or `Insert a [img]icon.png[/img] here` and I have a function that render those markup blocks. It's not a trivial thing to implement but pretty useful for a game.

Is there code available that does this? I want to do something like shown in the image below and being able to work off of an example would make things easier:

![image](https://github.com/user-attachments/assets/52505a8c-c3a3-4a1b-97b3-3f3f4dd38eff)

For some reason I'm not getting very far beyond this issue when searching how to embed images in text in the github issues, although people have no doubt done this many times.
