### ISSUE TITLE
[proposal] Create a forum ?

### ISSUE THREAD

**Issue by ebachard** [ocornut/imgui#1135]
Several issues are just questions like "howto .... " or something close. From another side,  ImGui users base is growing, and the needs follow.
I seriously don't know whether github is able to provide such service, but isn't it the time to create a forum (or something similar) ? Not sure the wiki is the answer though.

Possible topics could be: 
- FAQ : discover ImGUI, how to do something, something else
- development : improve security, performance, portability and more
- API specific questions. e.g. OpenGL specific, SDL2 specific, API interactions
- addon, interesting forks : e.g. Tabs from Scott Mudge are nice and easy to integrate, but this is not the only available addon. cvui and some other could be another answer
- feedback:  ImGUI useg, screenshots, examples and so on ..
- professional support (why not !)
... (whatever other good idea)

Feel free to close this issue if I'm off topic, or in the case I completely misunderstood how things work on github :-)

**Comment by zwcloud** [comment]
I recommend [discourse](https://www.discourse.org/).

**Comment by benrob0329** [comment]
An IRC or [Matrix](https://matrix.org) room might be helpful as well.

**Comment by yinjimmy** [comment]
https://groups.google.com/

**Comment by ocornut** [comment]
> Several issues are just questions like "howto .... " or something close. 

I think a separate forum won't solve anything. Those people are often new programmers or confused users, who either don't read docs, either don't understand them, they would still ask the same questions on a forum. What would help are better docs, better examples, better wiki/links. Off-loading answers to other people can be done here (it's already happening here, with everyone help - thanks!). 

So I am not sure I see the point of using of a separate forum when this place does the job. All those topics can be discussed here and the Wiki could be improved to organize things. It would mostly scatter the information and perhaps lowering the information quality.  I would like to encourage advanced users to start opened-ended discussion topics here if we they like.

If imgui really takes off (5 times the numbers of users, maybe) I'd see the point more clearly. It won't take off now as it is 50% finished. And I would _prefer_ that it doesn't take off until it's more finished, the more user the more overwhelmingly hard it is for me to actually make useful progress on the library. While advanced users are pushing the limits of the libraries, all the forks and custom hacks are both a blessing and a curse (It's really hard to come back from a forked repository). Mostly I think what dear imgui needs is just serious hours sitting down and making code/docs progress happen. 

IMHO any "live" chat like IRC is counter-productive, the useful information is lost for most (not commonly searchable). But if I mean, if you people wants to start any of that, feel free to do so!

But,

While I happen to disagree it looks like many of you feels the needs for something. 
Could you elaborate? Are you finding it uncomfortable to open topics or discuss here? Could it be just the fact that this is labelled "Issues", in spite of the fact that it works like a forum?

**Comment by benrob0329** [comment]
>IMHO any "live" chat like IRC is counter-productive, the useful information is lost for most (not commonly searchable)

Matrix chats are very search-able actually, and can be bridged to other networks.

**Comment by colesnicov** [comment]
no forum

**Comment by AndrewJDR** [comment]
Just wanted to chime in -- if some realtime chat IS used, I can also recommend matrix.
* All history is searchable and isn't subject to crappy limits (e.g. slack has the 10k message limit, matrix does not)
* It's open source
* You can run your own server and federate with the server just like irc.
* It bridges to irc (freenode), so people using irc clients can also chat there.

**Comment by AndrewJDR** [comment]
fwiw, an irc channel does exist - #dearimgui on freenode.
This same room also accessible via matrix - https://riot.im/app/#/room/#dearimgui:matrix.org (searchable history, web based, etc)
Feel free to join in.

kung__ and myself are ops in there. @ocornut if you ever want admin / op / ownership status over the channels just let us know.

**Comment by ebachard** [comment]
@ocornut  : thanks for the complete and useful answer. Reading twice, I fully agree your choice, and maybe we could improve the wiki. What do you suggest ?  How does it work ? How many people contribute ? Is everything git linked ? Do you have plans or ... ? 

Waiting, I'll continue to test and learn Dear ImGUI source code. Ufff ... I got work  :-)

@AndrewJDR : I was sure there was one IRC channel ;-)  thanks a lot for the information. As a first try, I'm currently connected, and there are 8 users on the channel. Not that bad for a Sunday :p

**Comment by ocornut** [comment]
Both for learning source code (which shouldn't really be a goal in itself) and for the contributing to the library and or wiki, the most useful first step is to use the library in a real project yourself.  To get quality stuff happening we need people that are both A) available and pro-active and B) knowledgeable about dear imgui and its ecosystem. The overlap is those two qualities is unfortunately uncommon. Knowledgeable comes with using the library on a real project! When there's enough of those people hovering around, things will more naturally happen. It may take a while, which is fine!

**Comment by johanwendin** [comment]
Not very knowledgable about GitHub, but is it possible to create more tabs? (like Issues but named other things?)

It does muddy the waters a bit when "how to..." is mixed with issues, suggestions etc. And by that I don't mean that they're in any way wrong - the more people using ImGui the better. Just that it's harder to see what could use some work and who needs help.

**Comment by ocornut** [comment]
The way I see it-
When someone needs help the issues are easy to answer and close. The unanswered issues are usually because they connect to a missing feature or something requiring extra work (generally code).

**Comment by ocornut** [comment]
I've reversed my stance on that (thanks @ebachard!), moving this discussion to #1907.
My main concern is always that I don't want to be disconnected from the problems people are having. I assume I could still more passively stalk whatever public forum we have.
I'm registering a domain name for it now.
