### ISSUE TITLE
Using TreeNode

### ISSUE THREAD

**Issue by Burskin** [ocornut/imgui#1136]
You can show how to use it correctly the "TreeNode" to build multiple attachments and change the type from "child" to "parent" like as in ReClass app (means "loop-rendering")? Thanks!
![sss](https://cloud.githubusercontent.com/assets/28480355/25771481/ba0a363e-325b-11e7-9e06-8c7072f0dba1.jpg)

**Comment by ocornut** [comment]
Just draw whatever you need. You can use `SameLine` to keep items on a same line.
Run and check the demo `ShowTestWindow` code.
