### ISSUE TITLE
Close popup without using ImGui::CloseCurrentPopup()

### ISSUE THREAD

**Issue by colesnicov** [ocornut/imgui#1137]
Hello to everybody.

Is there a possibility to close the popup window on the way:

```
ImGui::OpenPopup("TEST");
ImGui::BeginPopupModal("TEST");
...
ImGui::EndPopup();


ImGui::Begin("___");
if(ImGui::Button("Close TEST popup", ImVec2(...)))
{
    // Here i want to close the popup with the name TEST
}
ImGui::End();
```

**Comment by colesnicov** [comment]
Inspired from here: https://github.com/ocornut/imgui/issues/249

I just added a boolean indice:

`static bool test_open(true);`

like this:

```
static bool test_open(true);

if(test_open){
    ImGui::OpenPopup("TEST");
}

ImGui::BeginPopupModal("TEST", &test_open);
...
ImGui::EndPopup();


ImGui::Begin("___");
if(ImGui::Button("Close TEST popup", ImVec2(...)))
{
    // Here i want to close the popup with the name TEST
    test_open = false;
}
ImGui::End();
```

**Comment by ocornut** [comment]
I would still like to add popup apis using ImGuiID (they'd have a behave very slightly differently because functions like ClosePopup() would need to scan the popup stack). Linking to #331 for reference.

**Comment by micb25** [comment]
Hey, is there any news about a `ClosePopup()` function?

I want to implement a "Loading..." animation in my application via a modal popup. I have a global thread-safe counter (`m_LoadingCounter`) that gets increased when a thread starts to load a file and gets decreased when its done. Unfortunately, I need to track the status (opened/closed) of the popup manually. Short example:

```C++
// called every frame

if (m_LoadingCounter == 0 && !m_IsWindowOpen)
    return;

if (!m_IsWindowOpen) {
    ImGui::OpenPopup(WINDOW_TITLE_ID);
    m_IsWindowOpen = true;
}

// ...

if (ImGui::BeginPopupModal(WINDOW_TITLE_ID, nullptr, WINDOW_FLAGS)) {
    // ...
    if (m_LoadingCounter == 0) {
        ImGui::CloseCurrentPopup();
        m_IsWindowOpen = false;
    }
    ImGui::EndPopup();
}
```

This would be much easier with a `ClosePopup()` function, since it is not necessary to store the state of the popup in the application:
```C++
// called every frame

const bool windowOpen = ImGui::IsPopupOpen(WINDOW_TITLE_ID);

if (m_LoadingCounter == 0) {
    if (windowOpen)
        ImGui::ClosePopup(WINDOW_TITLE_ID);
    return;
}
    
if (!windowOpen)
    ImGui::OpenPopup(WINDOW_TITLE_ID);

// ...

if (ImGui::BeginPopupModal(WINDOW_TITLE_ID, nullptr, WINDOW_FLAGS)) {
    // ...
    ImGui::EndPopup();
}
```

**Comment by ocornut** [comment]
I will look into it but I think what’s missing here is a way to make a window modal without it being a popup. If you control both opening and closing it doesn’t have to be a popup. Modals are a bit ill designed currently. Linking to #402
