### ISSUE TITLE
Constraint of only min or max window size

### ISSUE THREAD

**Issue by degracode** [ocornut/imgui#1139]
I've got a tweak to `ApplySizeFullWithConstraint` that allows you to constrain only the minimum, or only the maximum size of a window. This is useful where I want to use `ImGuiWindowFlags_AlwaysAutoResize`, but with a minimum so that the title bar text is visible, and the window is at least a reasonable size. Eg:

`SetNextWindowSizeConstraints(ImVec2(100.0f, -1.0f), ImVec2(-1.0f, -1.0f));`

```
        // Using -1,-1 on either X/Y axis to preserve the current size.
        ImRect cr = g.SetNextWindowSizeConstraintRect;
        new_size.x = (cr.Min.x >= 0) ? ImMax(new_size.x, cr.Min.x) : window->SizeFull.x;
        new_size.x = (cr.Max.x >= 0) ? ImMin(new_size.x, cr.Max.x) : new_size.x;
        new_size.y = (cr.Min.y >= 0) ? ImMax(new_size.y, cr.Min.y) : window->SizeFull.y;
        new_size.y = (cr.Max.y >= 0) ? ImMax(new_size.y, cr.Max.y) : new_size.y;
        if (g.SetNextWindowSizeConstraintCallback)
```

Is there a better way I could do this?

**Comment by ocornut** [comment]
Hello,
You could achieve it through the callback (meh!), I think your patch would make sense to apply tho. Will look into it. Thanks!
Omar

**Comment by notSam25** [comment]
Has anyone found a solution for setting the max window size? I saw that ImGui has a min var(ImGuiStyleVar_WindowMinSize) but I didn't see a max, please enlighten me.

**Comment by notSam25** [comment]
> Has anyone found a solution for setting the max window size? I saw that ImGui has a min var(ImGuiStyleVar_WindowMinSize) but I didn't see a max, please enlighten me.

Nevermind, I found a function after a bit of documentation spelunking. My solution was using SetNextWindowSizeConstraints.

**Comment by ocornut** [comment]
I have now answered for #3186, but essentially the correct way to do what you requested is:

`SetNextWindowSizeConstraints(ImVec2(100.0f, 0.0f), ImVec2(FLT_MAX, FLT_MAX));`
