### ISSUE TITLE
Rendering issue with OpenGL3 example code (Windows)

### ISSUE THREAD

**Issue by Atemboi** [ocornut/imgui#1141]
Hi, I'm incorporating ImGui into my engine and I've stumbled across an issue where the currently focused window is not rendering properly, and the fonts come out as garbled text

![](https://i.gyazo.com/8fbd72fa3c8fa7fcab034a1ab9b2a5ee.png)

The issue only occurs if I'm rendering multiple windows, and I'm confused as to why I'm getting this result

**Comment by ocornut** [comment]
It looks like the imgui font texture isn't being bound properly in all the draw calls.

Double-check your rendering loop, or maybe post the code to help identifying the problem.

**Comment by Atemboi** [comment]
`            ImGui::Begin("Renderer settings");
            ImGui::SetWindowSize(ImVec2(200,200));
            ImGui::Text("Set Gamma");
            ImGui::SliderFloat("gamma", &gamma, 0.0f,5.0f);
            ImGui::Text("Teapot Instances");
            ImGui::InputInt("teapots",&teapotInc);
            ImGui::Text("Main scene settings");
            ImGui::Checkbox("Draw main Scene", &drawScene);
            ImGui::End();
            ImGui::ShowTestWindow(&cursorEnabled);` is all I am doing at the moment, for my two ImGui windows.

Then, for my drawing calls, I'm doing this:
`        if (drawScene)
        {
            mainVAO.bindVAO();
            window.drawFromVBODirect(pipeline,GL_TRIANGLES);
        }
        suzanneVAO.bindVAO();
        window.drawFromVBOInstanced(suzannePipeline,GL_TRIANGLES,teapotInc);
         ImGui::Render();
        window.Update();`

The function window.Update(); just swaps the backbuffer, and then polls events.

**Comment by ocornut** [comment]
I am talking about the actual imgui render function which you used or implemented.

**Comment by Atemboi** [comment]
ah, sorry


```
    // Setup render state: alpha-blending enabled, no face culling, no depth testing, scissor enabled
    glEnable(GL_BLEND);
    glBlendEquation(GL_FUNC_ADD);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    glDisable(GL_CULL_FACE);
    glDisable(GL_DEPTH_TEST);
    glEnable(GL_SCISSOR_TEST);

    // Setup viewport, orthographic projection matrix
    glViewport(0, 0, (GLsizei)fb_width, (GLsizei)fb_height);
    const float ortho_projection[4][4] =
    {
        { 2.0f/io.DisplaySize.x, 0.0f,                   0.0f, 0.0f },
        { 0.0f,                  2.0f/-io.DisplaySize.y, 0.0f, 0.0f },
        { 0.0f,                  0.0f,                  -1.0f, 0.0f },
        {-1.0f,                  1.0f,                   0.0f, 1.0f },
    };
    glUseProgram(g_ShaderHandle);
    glUniform1i(g_AttribLocationTex, 0);
    glUniformMatrix4fv(g_AttribLocationProjMtx, 1, GL_FALSE, &ortho_projection[0][0]);
    glBindVertexArray(g_VaoHandle);

    for (int n = 0; n < draw_data->CmdListsCount; n++)
    {
        const ImDrawList* cmd_list = draw_data->CmdLists[n];
        const ImDrawIdx* idx_buffer_offset = 0;

        glBindBuffer(GL_ARRAY_BUFFER, g_VboHandle);
        glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)cmd_list->VtxBuffer.Size * sizeof(ImDrawVert), (const GLvoid*)cmd_list->VtxBuffer.Data, GL_STREAM_DRAW);

        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, g_ElementsHandle);
        glBufferData(GL_ELEMENT_ARRAY_BUFFER, (GLsizeiptr)cmd_list->IdxBuffer.Size * sizeof(ImDrawIdx), (const GLvoid*)cmd_list->IdxBuffer.Data, GL_STREAM_DRAW);

        for (int cmd_i = 0; cmd_i < cmd_list->CmdBuffer.Size; cmd_i++)
        {
            const ImDrawCmd* pcmd = &cmd_list->CmdBuffer[cmd_i];
            if (pcmd->UserCallback)
            {
                pcmd->UserCallback(cmd_list, pcmd);
            }
            else
            {
                glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->TextureId);
                glScissor((int)pcmd->ClipRect.x, (int)(fb_height - pcmd->ClipRect.w), (int)(pcmd->ClipRect.z - pcmd->ClipRect.x), (int)(pcmd->ClipRect.w - pcmd->ClipRect.y));
                glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer_offset);
            }
            idx_buffer_offset += pcmd->ElemCount;
        }
    }


```

**Comment by Atemboi** [comment]
here's also a small snippet from a generated log, specifically of the draw calls given for the ImGui windows displayed
```
glDrawElements(GL_TRIANGLES,1752,GL_UNSIGNED_SHORT,0000036C) GLSL=4  Textures[ (0,3) (1,2) ]  Time= 234us
glBindBuffer(GL_ARRAY_BUFFER,7)
glBufferData(GL_ARRAY_BUFFER,1200,06FCC360,GL_STREAM_DRAW)
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,8)
glBufferData(GL_ELEMENT_ARRAY_BUFFER,180,06FCC8B8,GL_STREAM_DRAW)
glBindTexture(GL_TEXTURE_2D,3)
glScissor(50,0,504,403)
glDrawElements(GL_TRIANGLES,90,GL_UNSIGNED_SHORT,00000000) GLSL=4  Textures[ (0,3) (1,2) ]  Time= 28us
glBindBuffer(GL_ARRAY_BUFFER,7)
glBufferData(GL_ARRAY_BUFFER,8840,06FDA008,GL_STREAM_DRAW)
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,8)
glBufferData(GL_ELEMENT_ARRAY_BUFFER,1626,06FDC9E0,GL_STREAM_DRAW)
glBindTexture(GL_TEXTURE_2D,3)
glScissor(0,0,1280,720)
glDrawElements(GL_TRIANGLES,333,GL_UNSIGNED_SHORT,00000000) GLSL=4  Textures[ (0,3) (1,2) ]  Time= 39us
glBindTexture(GL_TEXTURE_2D,3)
glScissor(140,421,192,181)
glDrawElements(GL_TRIANGLES,480,GL_UNSIGNED_SHORT,0000029A) GLSL=4  Textures[ (0,3) (1,2) ]  Time= 70us
glUseProgram(3)
```

**Comment by ocornut** [comment]
Hard to guess, the code and log looks ok (though I only skimmed through them).
The currently focused window would be the last one drawn, that's one hint.
Perhaps try disabling the rest of your rendering to see if there's anything relation between it and the effect you are having.

**Comment by Atemboi** [comment]
Yeah, just did so

I disabled every draw call/VAO bind, aside from `ImGui::Render` , and creating the two windows, and I get the same result, sadly

**Comment by ocornut** [comment]
Do the applications in `examples/opengl_*` work?

**Comment by Atemboi** [comment]
I have just built them, and the GL3 one has the same issue

**Comment by ocornut** [comment]
Wow this is very strange then, I've never seen such issue happen in the past.
What if you open many windows?
What is the your OS and graphics card?

**Comment by Atemboi** [comment]
My operating system is windows 10, and I'm using a GTX 1060

I believe it might be to do with the texture loading process, but I'm not sure

**Comment by ocornut** [comment]
I mean, you can see the log you posted above, it's a pretty simple log and it looks correct.
Your OS and graphics cards are very common (this is what I have too). Hard to understand what is happening. Are the GL2 or DX11 example behaving the same?

**Comment by Atemboi** [comment]
Both the GL2 and the DX11 examples work fine

**Comment by Atemboi** [comment]
A few people have tested out a demonstration for it which I compiled (GL 3.2, GLSL 1.5), and a few people reported issues with a similar result to me, or a large translucent triangle extruding from the top left corner, to the inactive window, while the active window was invisible

**Comment by ocornut** [comment]
Do the precompiled GL3 example binaries works for you?
http://www.miracleworld.net/imgui/binaries/imgui-demo-binaries-20161113.zip

**Comment by Atemboi** [comment]
Yes, I downloaded those before, and it worked fine

**Comment by ocornut** [comment]
OK, so to keep reducing the possible issues, I have compiled the last version myself but for 32 and 64 bits. Using Visual Studio 10.
(Whereas the binaries above are dated 2016/11)
[opengl3_example.zip](https://github.com/ocornut/imgui/files/998877/opengl3_example.zip)

**Comment by Atemboi** [comment]
Both examples show the same behaviour, with some sort of font corruption

**Comment by ocornut** [comment]
Here what was modified in this folder since 2016/11/13:
https://github.com/ocornut/imgui/commits/master/examples/opengl3_example

So maybe either one of those commits is causing a problem:
https://github.com/ocornut/imgui/commit/01286f6636021f0b7d1e9102b098a61439b89ada
https://github.com/ocornut/imgui/commit/50b4b29beb5c48a9dde38dd0e240054b9a68b31e

before
https://raw.githubusercontent.com/ocornut/imgui/a68ac96bc4b37ce79588aec23df83ede0d2f6099/examples/opengl3_example/imgui_impl_glfw_gl3.cpp

first commit
https://github.com/ocornut/imgui/blob/50b4b29beb5c48a9dde38dd0e240054b9a68b31e/examples/opengl3_example/imgui_impl_glfw_gl3.cpp

second commit
https://github.com/ocornut/imgui/blob/01286f6636021f0b7d1e9102b098a61439b89ada/examples/opengl3_example/imgui_impl_glfw_gl3.cpp

Would you mind trying with those versions in order?

**Comment by Atemboi** [comment]
I've just quickly tried all three and they all share the same issues

**Comment by ocornut** [comment]
So just to confirm, since we are tracking a weird bug,
About http://www.miracleworld.net/imgui/binaries/imgui-demo-binaries-20161113.zip
> Yes, I downloaded those before, and it worked fine

Can you confirm that it works fine on your setup TODAY?

**Comment by Atemboi** [comment]
Those have worked properly today

**Comment by ocornut** [comment]
Rebuilt the 2016/11/13 code on my setup today to see if makes a difference, along with 2 later builds:

[builds1.zip](https://github.com/ocornut/imgui/files/998890/builds1.zip)

**Comment by Atemboi** [comment]
The first example works fine, however the other two examples have the same issue when rendering the windows

**Comment by ocornut** [comment]
OK good, we're getting somewhere.
Do you know how to use git bisect to perform those tests locally between 20161112 and 20161219 ?

**Comment by Atemboi** [comment]
I have not used it before

**Comment by ocornut** [comment]
You can use it on the command-line or depending on the git client you use you may have access to a GUI helper.
See See https://git-scm.com/docs/git-bisect

$ git bisect start
$ git bisect bad db593220fc419547b80e188b104051d39fc1a8e3 
$ git bisect good 81eefb704b6427bc4758cc55b15f5db845d6c5f6 

Basically it'll cut the range in the middle so you can test a version in the middle, and depending of it works or not it keeps reducing the range until you find the commit that broke it.

**Comment by Atemboi** [comment]
I have just done this and I found that the `Alpha8` function to get texture data changed to `RGBA32`.

I changed it back, and now I have good results in my application.

It took a while to pinpoint, but thanks for the help.

**Comment by ocornut** [comment]
I do not quite understand, could you clarify? I see no such change between Nov 12 and December 19.

The function ImGui_ImplGlfwGL3_CreateFontsTexture has been like this for a while:

```
bool ImGui_ImplGlfwGL3_CreateFontsTexture()
{
    // Build texture atlas
    ImGuiIO& io = ImGui::GetIO();
    unsigned char* pixels;
    int width, height;
    io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height);   // Load as RGBA 32-bits (75% of the memory is wasted, but default font is so small) because it is more likely to be compatible with user's existing shaders. If your ImTextureId represent a higher-level concept than just a GL texture id, consider calling GetTexDataAsAlpha8() instead to save on GPU memory.

    // Upload texture to graphics system
    GLint last_texture;
    glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture);
    glGenTextures(1, &g_FontTexture);
    glBindTexture(GL_TEXTURE_2D, g_FontTexture);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels);

    // Store our identifier
    io.Fonts->TexID = (void *)(intptr_t)g_FontTexture;

    // Restore state
    glBindTexture(GL_TEXTURE_2D, last_texture);

    return true;
}
```

**Comment by Atemboi** [comment]
I don't know, I took the November commit, and compared it to the latest one, and that line had changed

**Comment by ocornut** [comment]
This line has _never_ changed for the GL3 example.

Are you always and only looking at `examples/opengl3_example` ?

**Comment by Atemboi** [comment]
Yes, I've done a binary search and the line has changed

**Comment by ocornut** [comment]
Are you sure you are looking at `imgui_impl_glfw_gl3.cpp` ? I see no evidence of such change ever.

**Comment by Atemboi** [comment]
Yes

**Comment by ocornut** [comment]
Would you mind getting on chat so we can sort this out? If there is a problem I would like it to be fixed.
I am `omarcornut` on skype and likewise at gmail.com

**Comment by Kaldaien** [comment]
@Atemboi: Alpha8 isn't valid in a pure GL3 environment to begin with (which is what the ImplGlfwGL3 sample targets). You can either pad the stuff out to RGBA or use R8 with a swizzle mask as needed, but changing it to alpha8 isn't the solution.

**Comment by ocornut** [comment]
We never used Alpha8 in the gl3 example, there's no trace of it in any commit, this thread is lacking clarify and I suppose Atemboi wasn't actually testing vanilla master code, rendering the other feedback invalid. I'll close it for now since there's no evidence that this is happening elsewhere.

**Comment by gbelardelli** [comment]
I Omar,
I just download last sources with examples and compiling it on Visual Studio 2015 Community. I build for Win32 with Debug. 
When I run the example_glfw_opengl3 the rendering problem appear as displayed in attached screenshot.

![sshot](https://user-images.githubusercontent.com/19502596/48549619-8f4f9880-e8d0-11e8-820d-e13fb962c4fa.jpg)

The issue only occurs if I'm rendering multiple windows. 
Ex: if I comment the two lines
        if (show_demo_window)
            ImGui::ShowDemoWindow(&show_demo_window);

all works fine.

My laptop is a Dell Vostro with Intel i5-3210 Cpu and 6GB Ram.
OS: Windows7 Professional 64  with SP1

Renderer: Intel(R) HD Graphics 4000
Vendor: Intel
Memory: 2112 MB
Version: 3.3.0 - Build 8.15.10.2696
Shading language version: 3.30 - Intel Build 8.15.10.2696

**Comment by ocornut** [comment]
Hello Gianluca, this seems like a different issue from the above.

Windows OpenGL drivers are known to be a mess especially on old integrated Intel HD cards, have you tried updating your drivers? Many strange OpenGL issues were fixed by updating drivers.

How does the OpenGL2 and DX11 demo perform on the same setup?

**Comment by gbelardelli** [comment]
Hi, the driver is the latest old version from Intel ( 2012 )!
OpenGL2 & DX11 works fine.

**Comment by gbelardelli** [comment]
Yes I know... but I can't install the new driver... seems that Dell laptop have a customized intel driver.
At this point I switch to opengl2. But is curious why with 2 or more windows the rendering fail. I try to investigate to myself.
Thanks

**Comment by ocornut** [comment]
You can look at the render loop in imgui_impl_opengl3.cpp. Multiple windows will lead to multiple calls to glBindBuffer/glBufferData/glBindBuffer/glBufferData used to upload vertices and indices. Unless we missed something I think this is all legal GL code and the driver is at fault.

Honestly starting new projects with OpenGL in late 2018 is not a great idea. If you are under Windows you will be better using DirectX or Vulkan.

**Comment by gbelardelli** [comment]
Ok thanks for advice, I take a look to imgui_impl_opengl3.cpp... My main project use Vulkan and I haven't problem on my house pc, but this work laptop has not support for vulkan. For now my main purpose is only to understand well imgui and I think that rendering platform isn't the problem.
