### ISSUE TITLE
horizontally aligned widgets, fixed width and scrolling

### ISSUE THREAD

**Issue by q-depot** [ocornut/imgui#1142]
Hi,

I need to create vertical widgets with fixed width aligned horizontally, ideally I'd like to have a bigger area that I can pan on both directions.

I'm not sure about how to create the vertical widget and layout. I tried using BeginGroup but I can't set the group's width. I also tried the Columns layout, but again same problem, the columns always fit the parent window, I'd rather have the window size adapting to its content.
Initially I thought about using a window for each vertical widget, but because I can't have nested windows, I can't do the scrolling and other layout elements.

this is more or less what I'm looking for(top right window)
![imgui ableton](https://cloud.githubusercontent.com/assets/32179/26032198/45d6a114-3885-11e7-8a59-4d8010f6b6f4.jpg)

![imgui](https://cloud.githubusercontent.com/assets/32179/26032199/45d87264-3885-11e7-8abc-a3e7242f7de8.jpg)

**Comment by ocornut** [comment]
Child windows (`BeginChild`) gives you an independent scrolling and clipping region.

I think the thing is that holding you back is:
> I'd rather have the window size adapting to its content.
This is not possible for child windows at the moment, and likely won't be possible soon.

What I would do:
- create one parent child window (for scrolling) with width/height calculated to accomodate all your contents.
- within it, create multiple child window separated with SameLine()
- somehow use the middle mouse position to adjust the scrolling of the main one.

You can also replace the inner child windows with columns. Either way you would have to calculate yourself the widget you need. Columns are still rather undevelopped at the moment.
