### ISSUE TITLE
Render Backend Checklist?

### ISSUE THREAD

**Issue by JSandusky** [ocornut/imgui#1148]
Is there a render backend checklist of things to pay extra attention to?

In implementing a QT based renderer (through QPainter, not through QGL ... that'd be silly) I ran into a few odd situations that took a bit of time to recognize there was a problem or even what it was (particularly with text being ... very un-text-like, and clip-rects).

![QPainter based renderer](http://i.imgur.com/Lc0p2Mcl.jpg) [QPainter based renderer - Full res. version](http://i.imgur.com/Lc0p2Mc.png) IMGUI on the left and Nuklear on the right, both in QT through QPainter ... getting to tell signal/slot connection hell to go piss is delightful.

Is running all of the imgui_demo.cpp code through the backend enough to be sure that everything should check out as healthy?

**Comment by ocornut** [comment]
Unfortunately there's no such checklist yet.
Rendering is pretty simple, so if you get clipping right (which you can test by resizing a window and look at raw `Text()` statements inside the window. Note that the library does lots of coarse CPU-side clipping so sometimes it is a matter of a single character not being render-clipped properly (you can see character appearing/disappearing one by one entirely).

The other problems are usually related to inputs.

**Comment by JSandusky** [comment]
The demo is pretty much perfect as far as I can tell. I just went through it piece by piece adding a section at a time and verifying, then moving on.

I'm going to close this since the demo was actually plenty sufficient after I checked out the Allegro backend which I had overlooked, which is quite a bit clearer than the others.
