### ISSUE TITLE
[Linux][SFML] Font rendering problem.

### ISSUE THREAD

**Issue by lorow** [ocornut/imgui#1150]
So hi @ocornut!
Today I treid to setup Imgui and SFML on my linux machine (newest Manjaro Deepin) but an unexpected problem occured. The imgui font isn't rendering properly, I can see only some glitches, like on the screenshoot. I tried to move then to my system font folder ( yes, I cleaned the font cache after that), add them by code or even add a custom one by code (like on the wiki). Nothing helped. 

Here is how it looks like

https://imgur.com/a/uA1Qf

Here is my cmakelists.txt file

```
cmake_minimum_required(VERSION 3.7)
project(untitled)

set(CMAKE_CXX_STANDARD 14)

set(SOURCE_FILES main.cpp)

#detect and add all imgui files
file(GLOB imgui_src "imgui-master/*.*" )
file(GLOB imgui_sfml_src "imgui-master/imgui-sfml-master/*.*" )
file(GLOB fonts "imgui-master/extra_fonts/*.*")
#prepare executable
add_executable(untitled ${SOURCE_FILES} ${imgui_src} ${imgui_sfml_src} ${fonts})

# Detect and add SFML
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake_modules" ${CMAKE_MODULE_PATH})
#Find any version 2.X of SFML
#See the FindSFML.cmake file for additional details and instructions
find_package(SFML REQUIRED network audio graphics window system)
if(SFML_FOUND)
    include_directories(${SFML_INCLUDE_DIR})
    target_link_libraries(untitled ${SFML_LIBRARIES} ${SFML_DEPENDENCIES})
endif()

# OpenGL
find_package(OpenGL REQUIRED)
include_directories(${OPENGL_INCLUDE_DIR})
if (OPENGL_FOUND)
    target_link_libraries(untitled ${OPENGL_LIBRARIES})
    # or: target_link_libraries(${EXECUTABLE_NAME} ${OPENGL_gl_LIBRARY})
    target_link_libraries(untitled m)  # if you use maths.h
endif()
```
Thanks a lot for any help!

**Comment by ocornut** [comment]
The system fonts/cache has nothing to do with it. ImGui handle fonts itself..
Your build process has nothing to do with it either.

The problem is that you haven't uploaded the font texture generated by imgui.
Are you using one of the existing SFML backend?
Please look at the existing SFML backend or provide a repro. You may ask the SFML backends github owner if you are using them.

PS: Please use the github attachment system for pictures and not imgur.

**Comment by lorow** [comment]
Like I mentioned in the original post, I'm using [Imgui SFML backend](https://github.com/eliasdaler/imgui-sfml) which works just fine on my windows machine. Ow and sorry for the imgur.

**Comment by ocornut** [comment]
I would suggest to ask @eliasdaler then. 
Skimming at this wrapper it should call `createFontTexture` then `setFontTexture`, maybe one of those has a problem with your rendering setup, I don't know.
