### ISSUE TITLE
How to change the horizontal position of labels

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1154]
The title basically tells it all.

I've tried ImVec2 and that didn't work:
`ImGui::Text("lol", ImVec2(25, 0));`

I also just tried (I'm dividing with 6, because I have 6 labels I want to be equally spaced, and have a space of 5 between eachother.
`ImGui::Text("test", ImVec2(ImGui::GetWindowSize().x/6 - 5, 0));`

**Comment by ocornut** [comment]
Have you looked at the imgui_demo.cpp and ran the demo application?
(I'm not sure where you did you see a ImVec2 parameter to Text()).

Use `ImGui::SetCursorPos()` or `ImGui::SetCursorPosX()`.
Or `ImGui::SameLine(pos_x)`.
