### ISSUE TITLE
Autocomplete - Text cursor position

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#1155]
Hi, I'm working on autocomplete in multiline input and I need to get text cursor position (screen coordinates). I have found no way to get it. Is there a solution for this problem?

**Comment by ocornut** [comment]
What would you like to do with it?
Would it be sufficient to pass to the callback called for autocomplete?

**Comment by nem0** [comment]
I am using the callback https://github.com/nem0/LumixEngine/blob/6fe28750818250cbd1801998e1c15c92e8cf7275/src/lua_script/editor/plugins.cpp#L723
and then I show the popup https://github.com/nem0/LumixEngine/blob/6fe28750818250cbd1801998e1c15c92e8cf7275/src/lua_script/editor/plugins.cpp#L733

My issue is that the popup is shown where mouse cursor is and I would like to show it where text cursor is
![popup](https://cloud.githubusercontent.com/assets/153526/26328946/5566cb2e-3f45-11e7-9edf-575a0736c049.png)

**Comment by ocornut** [comment]
I think the endgame of InputText would be to add an API to query its state in a sort of stable form. In the meanwhile I think it is reasonable to include that position in the callback data, and we'll remove it when that position becomes available elsewhere.

It should be an easy change.

(Immediate workaround: the cursor pos is already passed to the IME function handler)

**Comment by nem0** [comment]
Thanks, the IME position works fine.

**Comment by Shpendicus** [comment]
@nem0  hey dude , I need to know the text-position on screen too? Can u direct me maybe to what you are using?

**Comment by nem0** [comment]
https://github.com/nem0/LumixEngine/blob/1fcdd58d3e3dcb89008da4c29aac039434d4959b/src/lua_script/editor/lua_script_plugins.cpp#L317

**Comment by Shpendicus** [comment]
@nem0 well, my C# binding does not offer this sadly :D  

but do you happen to know a good way how to colorize specific words in a string, for instance :

```
string txt = "this is a {red}very long long {green}text";

```

so that every word which specific marker gets colorized in that case; "very= red" and "text=green"
