### ISSUE TITLE
Compressing fonts issue

### ISSUE THREAD

**Issue by emilo0212** [ocornut/imgui#1158]
So I'm trying to figure out how I can compress a custom .ttf font I've found.

I'm using the binary_to_compressed_c.cpp file, and what I need from it, is the compressed size and the compressed data, not in base85
This is the command I'm trying atm: ./a.out -nocompress "SourceSansPro-Regular.ttf" 
but it only outputs the data without showing how much data or what the size is of that data.

Like, if you go onto google and download RobotoMonoRegular.ttf and the included .h, it shows the data + size
```
static const unsigned int RobotoMonoRegular_compressed_size = 85122;
static const unsigned int RobotoMonoRegular_compressed_data[85124/4] = 
```

**Comment by ocornut** [comment]
I have just tried what you said and it output the size along with the data, and it always did, so I don't understand your question.
