### ISSUE TITLE
ImDrawList rendering in world coordinates?

### ISSUE THREAD

**Issue by paulsapps** [ocornut/imgui#1162]
Using ImDrawList for general rendering is in the FAQ. I render an arrow like so:

```
    ImGui::Begin("testing", nullptr, ImVec2(io.DisplaySize.x, io.DisplaySize.y), 0.0f, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoInputs);

    ImDrawList* list = ImGui::GetWindowDrawList();

    ImVec2 lineP1 = { 150.0f, 100.0f };
    ImVec2 lineP2 = { 150.0f, 300.0f };
    static float thickness = 4.0f;
    static float arrowWidth = 12.0f;
    static float arrowHeight = 18.0f;
    static float lineWidth = 4.0f;

    list->PathLineTo({ lineP1.x - thickness, lineP1.y + arrowHeight }); // P1
    list->PathLineTo({ lineP1.x - arrowWidth, lineP1.y + arrowHeight  }); // P2
    list->PathLineTo({ lineP1.x, lineP1.y }); // P3
    list->PathLineTo({ lineP1.x + arrowWidth, lineP1.y + arrowHeight }); // P4
    list->PathLineTo({ lineP1.x + thickness, lineP1.y + arrowHeight }); // P5
    list->PathLineTo({ lineP2.x + thickness, lineP2.y }); // P6
    list->PathLineTo({ lineP2.x - thickness, lineP2.y }); // P7
    list->PathFillConvex(IM_COL32(255, 255, 0, 255));

    list->PathLineTo({ lineP1.x - thickness, lineP1.y + arrowHeight }); // P1
    list->PathLineTo({ lineP1.x - arrowWidth, lineP1.y + arrowHeight }); // P2
    list->PathLineTo({ lineP1.x, lineP1.y }); // P3
    list->PathLineTo({ lineP1.x + arrowWidth, lineP1.y + arrowHeight }); // P4
    list->PathLineTo({ lineP1.x + thickness, lineP1.y + arrowHeight }); // P5
    list->PathLineTo({ lineP2.x + thickness, lineP2.y }); // P6
    list->PathLineTo({ lineP2.x - thickness, lineP2.y }); // P7
    list->PathStroke(IM_COL32(0, 0, 0, 255), true, lineWidth);

    ImGui::End();
```
But this renders in screen coordinates and I want to render in world coordinates.

How could I do this? I was thinking instead of using ImVec2(io.DisplaySize.x, io.DisplaySize.y) then I'd have to do something like ImVec2(worldSizeX, worldSizeY) but then what about scaling?

Or is it possible to create and use an ImDrawList outside of ImGui::Begin/End and pull the vertex/index buffers to push into the world rendering pipe line?

**Comment by ocornut** [comment]
You can either project your vertices before you submit them to your ImDrawList or after at rendering time. If you want to project at rendering time, you might use ImDrawList callbacks or other techniques to pass your matrices/etc. To the renderer.

ImDrawList api won't touch your vertices so io.DisplaySize won't affect anything.

You can also use ImDrawList outside of ImGui but it is relying on the global ImGui atlas being setup (to access a white pixel) and the AddText() shortcut relies on current font+fontsize.

Omar

**Comment by paulsapps** [comment]
Thanks, will try it.

**Comment by ocornut** [comment]
For my game, I create separate ImDrawList instances (outside of imgui windows) and pass world coordinates, which is possible because my coordinates are 2D and my vertex format is simple. The renderer projects the cliprect + set projection matrice used the vertex shader. I use callbacks inside the ImDrawList to change render state (change shader, blending options etc.).

**Comment by paulsapps** [comment]
OK I think my issue now is that when my world view is zoomed the size is larger than the "fake" ImGui window so it becomes clipped. Is there some way to just turn the clipping off for the draw list?

I guess you didn't have the clipping issue because you where not using in the context of a Window.

**Comment by ocornut** [comment]
ImDrawList doesn't do any clipping, your renderer does based on provided ClipRect. Presumably you want to clip based on screen coordinates after you are done projecting your vertices, so I don't see a problem.

**Comment by paulsapps** [comment]
Ah of course you are right:
```
const RECT r = { (LONG)pcmd->ClipRect.x, (LONG)pcmd->ClipRect.y, (LONG)pcmd->ClipRect.z, (LONG)pcmd->ClipRect.w };
mDevice->SetScissorRect(&r);
```

If I don't set the SetScissorRect then nothing gets clipped away.

**Comment by paulsapps** [comment]
Sorry I have another question about using ImDrawList outside of ImGui.

I am trying to use AddCallback to pass some extra data. Right now I do something simple that says if the call back is set then use another matrix (just to test something).

I found that it failed because AddCallback then adds another draw command, so this happens:

1. First empty command has non null call back, "correct" matrix is set, nothing is drawn.
2. Second command has a null call back, "wrong" matrix is set and the triangles are drawn.

To workaround I can do this:

```
        list->AddCallback(FakeImDrawCallBack, 0x0);
        list->CmdBuffer.pop_back();
```

Is there some other way to have "custom" data per draw command that doesn't require hacking the draw command list like this? I know a "real" call back would probably work but my use case is so simple it actually adds more complexity.

In my render I'm trying to just do something like:

```
foreach(DrawCmd cmd : cmds)
{
  switch(cmd->UserData)
 { 
   case 1: EnableNormalRenderingStates(); break;
   case 2: EnableSpecialRenderingStates(); break;
 }

 // usual render the triangles with the given texture in the DrawCmd code
}
```

**Comment by ocornut** [comment]
This is how callback works, they are their own command. Just adapt your render loop, there's barely any added complexity:

```
foreach(DrawCmd cmd : cmds)
{
  if (cmd->UserCallback)
  switch(cmd->UserData)
 { 
   case 1: EnableNormalRenderingStates(); break;
   case 2: EnableSpecialRenderingStates(); break;
 }
 else
 // draw
```

**Comment by paulsapps** [comment]
I am a bit confused, for instance:

```
foreach(DrawCmd cmd : cmds)
{
  if (cmd->UserCallback)
  {
    switch(cmd->UserData)
    { 
      case 1: SetMatrix1(); break;
      case 2: SetMatrix2(); break;
    }
    DrawTris();
 }
 else
 {
  SetMatrix3(); 
  DrawTris();
  }
}
```

What I would see is that cmds contains 5 cmds, and only 1 has cmd->UserCallback set which might call SetMatrix2() and its DrawTris() renders 0 tris. Therefore it changes nothing as the next cmd would cause SetMatrix3() to be called and render the actual tris I expected in the first cmd.

**Comment by paulsapps** [comment]
Oh wait I see it now, the cmd is just a "marker" to set the state, therefore the logic must be:

```
SetMatrix3(); 
foreach(DrawCmd cmd : cmds)
{
  if (cmd->UserCallback)
  {
    switch(cmd->UserData)
    { 
      case 1: SetMatrix1(); break;
      case 2: SetMatrix2(); break;
    }
    DrawTris();
 }
 else
 {
  DrawTris();
  }
}
```

**Comment by ocornut** [comment]
Yes.

**Comment by thedmd** [comment]
To deal with problem of world-space only drawing I ended up adding two new functions was added to `ImDrawList`.
```cpp
IMGUI_API void  PushTransformation(const ImMatrix& transformation);
IMGUI_API void  PopTransformation();
```
Feature is opt-in, so if you do not use these you do not pay for this feature.

`PushTransformation` - it saves current vertex buffer position, saves old transformation and sets provided one as current.
`PopTransformation` - transforms all vertices from saved position to current one and pop transformation from the stack.

Vertices are transformed multiple times if case of recurrent calls to Push/Pop pair. This is a drawback of this solution. So far I didn't notice any errors large enough to affect look of ImGui.

```cpp
// A: Draw a rect at 0, 0 of size 10x10
drawList->AddRect(ImVec2(0.0f, 0.0f), ImVec2(10.0f, 10.0f));

// Translate by 100 units along X axis
drawList->PushTransform(translation_matrix(100, 0));

    // B: Draw a rect at 100, 0 of size 10x10
    drawList->AddRect(ImVec2(0.0f, 0.0f), ImVec2(10.0f, 10.0f));

    // Scale local space twice along Y axis
    drawList->PushTransform(scale_matrix(1.0f, 2.0f));

       // C: Draw a rect at 100, 0 of size 10x20
       drawList->AddRect(ImVec2(0.0f, 0.0f), ImVec2(10.0f, 10.0f));

    // Pop transformation. At this point vertices of 'C' will be transformed by scale matrix.
    drawList->PopTransformation();

// Pop transformation. At this point vertices of 'B' and 'C' will be transformed by translation matrix.
drawList->PopTransformation();

// 'A' vertices are not affected by any transformation.
```

I did add `ImMatrix` which is basically 2D transformation matrix.
```cpp
struct ImMatrix
{
    float m00, m01, m11, m10, x, y;
};
```

As an extension it is possible to add `SetTransformation` as a syntactic sugar to `PushTransformation(inverse(drawList->_TransformationStack.back().Transformation))`. This reduce matrix to identity nullifying any transformation. Matrix multiplication however will still be done.

Note: Fringes are uniformly scaled to match current transformation, so AA works as expected. Non-uniform scaling is not handled.

What to you think about this approach?

**Comment by paulsapps** [comment]
I don't know - sounds like it could be expensive as the pop would do many transforms? What if the matrix was just set like a texture id and then the renderer just sets the matrix in the shader?

**Comment by thedmd** [comment]
It has potential to be expensive. I'm yet to hit the ceiling. There is no immediate tragedy, simple 2D transformation is not that expensive (4 multiplication, 6 additions). I think this is sufficient for most UI that can be thrown on ImGui.

Approach I presented does not require change to API and is transparent to widgets. Introducing matrix will probably have greater impact on ImGui internals in terms of line changed that I'm willing to do. Every back-end should be then adjusted to handle matrices. Doing so will break things like AA fringes. Draw lists generate triangle soup and due to that it is not viable to implement them even on client side (like nanovg does). Increase in API complexity will be necessary to deal with this problem.

There are always custom draw commands where sky is the limit. : )

**Comment by paulsapps** [comment]
I'm currently porting my 2D game to use ImDrawList for everything :D
