### ISSUE TITLE
Release font texture before set it to NULL

### ISSUE THREAD

**Issue by Nifury** [ocornut/imgui#1163]
g_FontTexture is set to NULL without Release() in ImGui_ImplDX9_InvalidateDeviceObjects() in DirectX 9 example.

**Comment by ocornut** [comment]
It is being released however it may be unclear `Fonts->TexID` is a copy of `g_FontTexture` at this point, see what `ImGui_ImplDX9_CreateFontsTexture` does.

Current code:
```
    if (LPDIRECT3DTEXTURE9 tex = (LPDIRECT3DTEXTURE9)ImGui::GetIO().Fonts->TexID)
    {
        tex->Release();
        ImGui::GetIO().Fonts->TexID = 0;
    }
    g_FontTexture = NULL;
```

Changed to:
```
    // At this point note that we set ImGui::GetIO().Fonts->TexID to be == g_FontTexture, so clear both.
    if (g_FontTexture)
        g_FontTexture->Release();
    g_FontTexture = NULL;
    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->TexID = NULL;
```

Which indeed is clearer for the casual reader! Thanks.
