### ISSUE TITLE
Asset browser

### ISSUE THREAD

**Issue by VinnyVicious** [ocornut/imgui#1165]
I'm creating a small asset browser with IMGUI, in order to allow drag'n'drop of models. I've also wanted to add a small preview of the model. What i'm currently doing is that i foreach into my asset folder, create a new FBO for each asset, and then render an image. But i don't think this is right. 

How would you guys do it?

**Comment by bluebear94** [comment]
Not sure if this issue is relevant to imgui, but

Hmm, I'd create a single FBO then switch the texture whenever you change the asset being viewed.

**Comment by VinnyVicious** [comment]
Yes, but i'm listing a lot at a single time. I'm using the FBO's as icons.

**Comment by ocornut** [comment]
You may want to cache the thumbnail into textures (either in RAM or on the disk), the FBO being only the intermediate setup you use to create one of those textures.

**Comment by VinnyVicious** [comment]
But doing the FBO is the right approach, right? I just need some caching then. Thanks! :)

**Comment by ocornut** [comment]
Well that's not really a question that relates to imgui.. if you need thumbnails for your objects I presume you need to render them somehow. However you render them is up to how your engine/code works.
