### ISSUE TITLE
lost window focus

### ISSUE THREAD

**Issue by q-depot** [ocornut/imgui#1166]
Hi,

I'm not sure this is an issue with ImGui itself,  when I open the system file dialog to load or save a file, it looks like I also loose the focus and the drag events stop working. To fix it I need to click on another window and back on the main app or alt+tab.

Is this a known issue?

**Comment by ocornut** [comment]
Hello Andrea,
Your question is very vague. 
Which bindings/backend code are you using?
When you use the word "window" please clarify if you mean "OS window" or "imgui window", etc. Presumably you are referring to "OS windows" and "OS system file dialog". 
What do you mean by drag events? The imgui demo window display inputs received by imgui, what do you see in there when you have the problem?
Do you understand that core imgui library doesn't know about your OS at all and it is up to your code to decide how/when you pass inputs to imgui? The code in the examples/ folder may be reacting differently based on the underlying library or os. Did you copied some of that example code or made your own?
-Omar

**Comment by q-depot** [comment]
My app opens a native system file dialog, when I close it and try to interact with a DragFloat, the widget doesn't work properly until I click on another OS windows and back to my app.
again, I'm not sure this is ImGui related.

**Comment by ocornut** [comment]
Please answer the questions if you want to have people understand your problem:
"Which bindings/backend code are you using?" 
"The imgui demo window display inputs received by imgui, what do you see in there when you have the problem?"

For example, the code in examples/opengl3_example using GLFW3 does:

```
    if (glfwGetWindowAttrib(g_Window, GLFW_FOCUSED))
    {
        double mouse_x, mouse_y;
        glfwGetCursorPos(g_Window, &mouse_x, &mouse_y);
        io.MousePos = ImVec2((float)mouse_x, (float)mouse_y);   // Mouse position in screen coordinates (set to -1,-1 if no mouse / on another screen, etc.)
    }
    else
    {
        io.MousePos = ImVec2(-1,-1);
    }
```
In other word it only passes the mouse inputs when the window is focused.
You can either change this behavior, or make sure your window is focused.

**Comment by sgf** [comment]
i got the same problems.look at the gif:

![window_move](https://user-images.githubusercontent.com/2557696/27287676-1c81b87a-5537-11e7-9ab3-ef083befd4e7.gif)

once click the Main Window,then first click other imgui_window will lot input.
the second time,will be fine.

**Comment by ocornut** [comment]
@sgf Please read the thread and questions above then. Thanks!

**Comment by sgf** [comment]
@ocornut ok It's my fault. i think he should be show the git img will be good and easy to Understand.
my problem is little different with him.and i think ( the reason was program lost WM_NCLBUTTONUP Message)

**Comment by ocornut** [comment]
Hi @q-depot, just wondering if you found a solution to your issue?
Looks like the other poster deleted some messages so the thread because a little more confusing :)

You can also have the `Keyboard, Mouse & Focus > Keyboard & Mouse State` section of the Demo window open to inspect the data that are being passed to imgui.cpp via your backend code.

**Comment by q-depot** [comment]
Hi, sorry for the delay in responding, I had to work on something else. I still didn't fix this, I'll have a look today and let you know.

**Comment by q-depot** [comment]
I found the issue and fixed it, as expected this has nothing to do with ImGui itself.

I'm using ImGui in a Cinder app ([Cinder-ImGui](https://github.com/simongeilfus/Cinder-ImGui)), the library wrapper manages the mouse and key events. 
When I open an external file dialog using ctrl+o(or what ever key) the keydown event is triggered, but because the window focus is passed to the external dialog, the keys are never released.

I've created a function in the Cinder library to explicitly release the keys when I open the file dialog. It would be good in ImGui to define the size of the keysDown array somewhere so I don't have to hard code "512" in my function.

`
void clearKeyEvents()
{
    // bool KeysDown[512]; imgui.h #787
    ImGuiIO& io = ImGui::GetIO();
    for( size_t k=0; k < 512; k++ ){
        io.KeysDown[k] = false;
    }    
    io.KeyCtrl = false;
    io.KeyShift = false;
    io.KeyAlt = false;
}`

**Comment by ocornut** [comment]
>  It would be good in ImGui to define the size of the keysDown array somewhere

You can use an ARRAYSIZE) macro if you have one.

ImGui for example uses this one:
`#define IM_ARRAYSIZE(_ARR)      ((int)(sizeof(_ARR)/sizeof(*_ARR)))`
(Some people are using template-based version which guard against using it on a pointer.)
