### ISSUE TITLE
Changing Button's Size

### ISSUE THREAD

**Issue by carlitos05052** [ocornut/imgui#1168]
Hey there, I've been trying to change the button's size without breaking the code but I was unsuccessful.
Here's my code:
```
	if (ImGui::Button("ESP")) OptionsManager.bCurrentTab = 1; ImGui::SameLine(0);
	if (ImGui::Button("Aimbot")) OptionsManager.bCurrentTab = 2; ImGui::SameLine(0);
	if (ImGui::Button("Anti-Aimbot")) OptionsManager.bCurrentTab = 3; ImGui::SameLine(0);
	if (ImGui::Button("Misc")) OptionsManager.bCurrentTab = 4; ImGui::SameLine(0);
```
Currently looks like this: 
![screenshot_4](https://cloud.githubusercontent.com/assets/28835097/26795412/951517fe-49f3-11e7-9bad-f4becb83d9cd.png)

I just want the tabs to look bigger, I tried adding ImVec2(w, h) at the end of each line but it didn't work.

Thanks in advance.

**Comment by ocornut** [comment]
You haven't really tried enough! Look and run the demo code, notice `Button()` can take an optional ImVec2& parameter which is used exactly for that.

**Comment by paulsapps** [comment]
You really where not joking that lots of game cheaters use DearImGui!

**Comment by carlitos05052** [comment]
Still can't figure it out, I just started doing C++ by the way.

**Comment by carlitos05052** [comment]
I fixed it, if anyone's still looking for a fix, here: 
	

> if (ImGui::Button(XorStr("ESP"), ImVec2(140.f, 20.f))) OptionsManager.bCurrentTab = 1; ImGui::SameLine(0); ImGui::PushItemWidth(200);
> 	if (ImGui::Button(XorStr("Ragebot"), ImVec2(140.f, 20.f))) OptionsManager.bCurrentTab = 2; ImGui::SameLine(0);
> 	if (ImGui::Button(XorStr("Anti-Aimbot"), ImVec2(140.f, 20.f))) OptionsManager.bCurrentTab = 3; ImGui::SameLine(0);
> 	if (ImGui::Button(XorStr("Misc"), ImVec2(140.f, 20.f))) OptionsManager.bCurrentTab = 4; ImGui::SameLine(0);

Thanks @ocornut
