### ISSUE TITLE
Draw image covering the whole window

### ISSUE THREAD

**Issue by tuket** [ocornut/imgui#1171]
Hello.
I wanted to display an image covering the whole window.
But I am having trouble to find the right dimensions.

```
ImVec2 pos = ImGui::GetCursorScreenPos();
ImVec2 maxPos = ImVec2(pos.x + ImGui::GetWindowSize().x, pos.y + ImGui::GetWindowSize().y);
unsigned texId = renderTarget.getTexture(0);

ImGui::GetWindowDrawList()->AddImage(
	(void *)texId,
	ImVec2(pos.x, pos.y),
	ImVec2(maxPos),
	ImVec2(0, 1), ImVec2(1, 0)
);
```

I tried to use the cursor position as the "minPos"

![imagen](https://user-images.githubusercontent.com/4165974/26842249-6d95bc48-4aec-11e7-9a3e-1a9b96ae9843.png)

As you can see the image gets cut at the botton.

If I use `ImVec2 pos = ImGui::GetWindowPos();` intead, it gets cut at the top.

![imagen](https://user-images.githubusercontent.com/4165974/26842317-b29efc96-4aec-11e7-83d9-f96685ceef50.png)

**Comment by tuket** [comment]
I figured out a way.
For the top-left corner I use `ImGui::GetCursorScreenPos()`.
For the bot-right corner I use `ImGui::GetWindowPos() + ImGui::GetWindowSize()`.

**Comment by tuket** [comment]
I will close this thread. But if anyone knows a better way, I would be interested.

**Comment by colesnicov** [comment]
Hi.
Check this from [https://github.com/ocornut/imgui/blob/5e1caaaef3953091b5395cbeb17c67548d542801/imgui.h#L130](https://github.com/ocornut/imgui/blob/5e1caaaef3953091b5395cbeb17c67548d542801/imgui.h#L130) to [https://github.com/ocornut/imgui/blob/5e1caaaef3953091b5395cbeb17c67548d542801/imgui.h#L135](https://github.com/ocornut/imgui/blob/5e1caaaef3953091b5395cbeb17c67548d542801/imgui.h#L135)

**Comment by ocornut** [comment]
The problem is if you want to create a window with an explicitly-sized usable client region. Currently the size passed are window size.
Maybe we need an equivalent of Client vs Window rect conversion concepts.
