### ISSUE TITLE
Multiple text in main menu bar 

### ISSUE THREAD

**Issue by msmshazan** [ocornut/imgui#1175]
This code doesn't work only one text gets rendered. Same for colored text.
```C++
ImGui::BeginMainMenuBar();
ImGui::Text("TIME:%02i:%02i:%02i",Win32Systime.wHour,Win32Systime.wMinute,Win32Systime.wSecond);          
ImGui::Text("DATE:%02i:%02i:%04i",Win32Systime.wDay,Win32Systime.wMonth,Win32Systime.wYear);
ImGui::EndMainMenuBar();

**Comment by dpethes** [comment]
Please use BeginMenu / EndMenu.

**Comment by msmshazan** [comment]
But I want colored text

**Comment by msmshazan** [comment]
How can I align the text so i can have them on right side of the screen.

**Comment by ocornut** [comment]
Hello @msmshazan,

You need to use ImGui::SameLine() else the subsequent line is displayed below. The regular dear imgui layout ruling apply, except this menubar window doesn't resize and doesn't have vertical scrolling. 

You align content you need to use functions such as ImGui::SetCursorPosX().
