### ISSUE TITLE
sdl_opengl2_example fail to display PNG Image

### ISSUE THREAD

**Issue by traw** [ocornut/imgui#1176]
I like dear ImGui and just started learning. I Have modified sdl_opengl2_example to display image. Basically I removed unnecessary code. I tried many things but couldn't succeed. Here is my code. 
```// ImGui - standalone example application for SDL2 + OpenGL
// If you are new to ImGui, see examples/README.txt and documentation at the top
// of imgui.cpp.

#include "imgui_impl_sdl.h"
#include <cstdlib>
#include <imgui.h>
#include <iostream>

#include <SDL2/SDL.h>
#include <SDL2/SDL_opengl.h>

#include <SDL2/SDL_image.h>
using std::cout;
std::string path = "era.png"; // Test Image to display
int tw = 0, th = 0;  //Texture width and Height
SDL_Surface *surface = NULL;
SDL_DisplayMode current;
SDL_Window *gWindow = NULL;
SDL_GLContext glcontext;

void loadSurface() {
  surface = IMG_Load(path.c_str());
  if (surface == NULL) {
    std::cout << "Unable to load image " << path.c_str() << " ! SDL_image Error: " << IMG_GetError() << "\n";
    exit(1);
  }
}
GLuint load_texture() {
  if (surface == NULL) 
    loadSurface();
  int Mode = GL_RGB;
  switch (surface->format->BytesPerPixel) {
  case 4:
    if (surface->format->Rmask == 0x000000ff)  Mode = GL_RGBA;
    else      Mode = GL_BGRA;
    break;
  case 3:
    if (surface->format->Rmask == 0x000000ff)   Mode = GL_RGB;
    else   Mode = GL_BGR;
    break;
  default:
    std::cout << "Error, image is not truecolor." << std::endl;
    return;
  }
  unsigned int texture;
  glGenTextures(1, &texture);
  glBindTexture(GL_TEXTURE_2D, texture);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  std::cout << "Texture: " << texture << " Mode: " << Mode  <<"\n";
  tw = surface->w;  th = surface->h;
  std::cout << "Image size : " << tw << "x" << th << "\n";
  glTexImage2D(GL_TEXTURE_2D, 0,   surface->format->BytesPerPixel /*GL_RGB*/, 0, surface->w, surface->h,  Mode  /*GL_RGBA*/, GL_UNSIGNED_BYTE,  surface->pixels);
  // glGenerateMipmap(GL_TEXTURE_2D);
  return texture;
}

void initSDL() {
  if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER) != 0) {
    std::cout << "Error: " << SDL_GetError() << "\n";
    exit(1);
  }
  // load support for the JPG and PNG image formats
  int flags = IMG_INIT_JPG | IMG_INIT_PNG;
  if (( IMG_Init(flags) & flags) != flags) {
    std::cout << "IMG_Init: Failed to init required jpg and png support: Error-> " << IMG_GetError() << "\n";
    SDL_Quit();
    exit(1);
  }
  cout << "SDL initialized\n";
}
void destroySDL() {
  SDL_DestroyWindow(gWindow);
  IMG_Quit();
  SDL_Quit();
}
void initWindow() {
  SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
  SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
  SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
  SDL_GetCurrentDisplayMode(0, &current);
  gWindow =
      SDL_CreateWindow("ImGui SDL2+OpenGL example", SDL_WINDOWPOS_CENTERED,
                       SDL_WINDOWPOS_CENTERED, 800, 600,
                       SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);
}

int main(int argc, char **argv) {
  initSDL();
  initWindow();
  glcontext = SDL_GL_CreateContext(gWindow);
  ImGui_ImplSdl_Init(gWindow);
  GLuint tex = load_texture();
  bool show_another_window = true;
  ImVec4 clear_color = ImColor(114, 144, 154);
  bool done = false;
  while (!done) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
      ImGui_ImplSdl_ProcessEvent(&event);
      if (event.type == SDL_QUIT)
        done = true;
    }
    ImGui_ImplSdl_NewFrame(gWindow);
    if (show_another_window) {
      ImGui::SetNextWindowSize(ImVec2(800,600), ImGuiSetCond_FirstUseEver);
      ImGui::SetNextWindowPos(ImVec2(0,0), ImGuiSetCond_FirstUseEver);
      ImGui::Begin("Window 1", &show_another_window);
      // ImGui::ImageButton((void *)tex, ImVec2(tw, th));
      //ImGui::Image((viod *)tex, ImVec2(tw, th), ImVec2(0, 0), ImVec2(1, 1),
      //             ImColor(255, 255, 255, 255), ImColor(255, 255, 255, 128));
     //ImGui::GetWindowDrawList()->PushTextureID(tex); 
     ImGui::GetWindowDrawList()->AddImage(  (ImTextureID)tex, ImVec2(tw, th), ImVec2(50,50));
     //ImGui::GetWindowDrawList()->PopTextureID();
      ImGui::End();
    }
    glViewport(0, 0, (int)ImGui::GetIO().DisplaySize.x,
               (int)ImGui::GetIO().DisplaySize.y);
    glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
    glClear(GL_COLOR_BUFFER_BIT);
    ImGui::Render();
    SDL_GL_SwapWindow(gWindow);
  }
  ImGui_ImplSdl_Shutdown();
  SDL_GL_DeleteContext(glcontext);
  destroySDL();
  return 0;
}
```

screenshot

![texture](https://user-images.githubusercontent.com/2088753/26988783-46651996-4d6e-11e7-885c-96db57f7a9d0.png)

**Comment by ocornut** [comment]
I'm not sure how that code can compile as you have a `return` path with no value in load_texture().
It's probably a bug on your loading side.

The ImGui-side code looks correct here, assuming that your ImGui_ImplSDL renderer is unmodified.

You can call ImGui::ShowMetricsWindow() to browse the draw calls, or debug through the ImGuiSDL render function, or maybe use a graphic debugger such as RenderDoc to check if your texture is correct.

**Comment by ebachard** [comment]
@traw  : After some time diving with your code, I compiled it (on Linux only) and got it finaly working. If I'm not wrong,  looks like several issues appeared:

- imho, you don't load correctly the .png (see the proposed load_texture() at the end
- the way you are using ImGui::GetWindowDrawList() leads to an image in SDL coordinates : when you move the ImGui window, the image does not move. 
- some memory leaks are present, due to a missing glDeleteTextures()
- I'm wondering about the TextureID visibility (but I didn't investigate more)

Last but not least, my code is not that clean (people correcting me are welcome), but if you are interested, I can post it there.

Below, my own load_texture():

GLuint load_texture()
{
    // avoid leaks
    if (texture != 0)
        glDeleteTextures(1, &texture);

    if (surface == NULL) 
        loadSurface();

    int Mode = GL_RGB;
    switch (surface->format->BytesPerPixel)
    {
        case 4:
        if (surface->format->Rmask == 0x000000ff)
            Mode = GL_RGBA;
        else      Mode = GL_BGRA;
            break;

        case 3:
        if (surface->format->Rmask == 0x000000ff)
            Mode = GL_RGB;
        else   Mode = GL_BGR;
        break;

        default:
            std::cout << "Error, image is not truecolor." << std::endl;
            return EXIT_FAILURE;
    }

    glGenTextures(1, &texture);
    glBindTexture(GL_TEXTURE_2D, texture);

    tw = surface->w;  th = surface->h;
    glTexImage2D(GL_TEXTURE_2D, 
                             0,
                             Mode,
                             surface->w,
                             surface->h,
                             0,
                             Mode,
                             GL_UNSIGNED_BYTE,
                             surface->pixels);

    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

    return texture;
}

**Comment by ocornut** [comment]
Closing this as ebachard has provided more than enough for @traw to chew on.

**Comment by ocornut** [comment]
I have now written a tutorial to cover image file loading for common graphics API:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
