### ISSUE TITLE
Question about Imgui::Render() with multisampled FBO

### ISSUE THREAD

**Issue by Edwinzero** [ocornut/imgui#1177]
I am trying to use IMGUI as a debug GUI for rendering testing. My idea is like to draw everything  into a multisampled fbo and then use this to pass to a intermediate fbo to display it on the default screen. 
![image](https://user-images.githubusercontent.com/5100412/26997225-de39f08a-4d45-11e7-9715-e17a1d86e766.png)
my drawing oreder is like below:
```
void Render(void)
{
	if (ANTIALIASING) {
		glEnable(GL_MULTISAMPLE); 
		glBindFramebuffer(GL_FRAMEBUFFER, canvas.multisampleFBO.fbo_);
	}
	// Get Back to the Modelview
	glClearColor(0.15f, 0.15f, 0.18f, 1.0f);
	glClearDepth(1.0);
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
	glEnable(GL_DEPTH_TEST);
	glMatrixMode(GL_MODELVIEW);
	glLoadIdentity();

        if (1) {
		// draw 3D scene
		glMatrixMode(GL_MODELVIEW);
		glPushMatrix();
		DrawScene3D();
		glMatrixMode(GL_MODELVIEW);
		glPopMatrix();
	} 
	if (1) {
		// draw gui, 
		glMatrixMode(GL_MODELVIEW);
		glPushMatrix();
		drawGUI();
		glMatrixMode(GL_MODELVIEW);
		glPopMatrix();
	}

	if (ANTIALIASING) {
                // read rendered fbo to intermediate fbo for display to default screen.
		glBindFramebuffer(GL_READ_FRAMEBUFFER, canvas.multisampleFBO.fbo_);
		glBindFramebuffer(GL_DRAW_FRAMEBUFFER, canvas.intermediateFBO.fbo_);
		glBlitFramebuffer(0, 0, screenWidth, screenHeight, 0, 0, screenWidth, screenHeight, 
                                             GL_COLOR_BUFFER_BIT, GL_NEAREST);

                // back to default screen
		glBindFramebuffer(GL_FRAMEBUFFER, 0);
		glClearColor(0.0f, 0.0f, 1.0f, 1.0f);
		glClear(GL_COLOR_BUFFER_BIT);
		glDisable(GL_DEPTH_TEST);

                // draw resolved texture on quad
		glUseProgram(GLCanvasProgram);
		glBindVertexArray(canvas.mem.vao);
		glActiveTexture(GL_TEXTURE0);
		glBindTexture(GL_TEXTURE_2D, canvas.intermediateFBO.tex_);	
		glDrawArrays(GL_TRIANGLES, 0, 6);
		glBindVertexArray(0);
		glUseProgram(0);
	}
	
	glFlush();
	glutSwapBuffers();
	glutPostRedisplay();
}
```
When I disable the antialiasing and comment the FBO creation, then the GUI back to screen again.
![image](https://user-images.githubusercontent.com/5100412/26997387-401472ac-4d47-11e7-9328-cbe8f0b0adb5.png)

Here is the code for DRAWGUI():
```
void drawGUI()
{
        if (!g_FontTexture)
		ImGui_ImplGLUT_CreateDeviceObjects();

	ImGuiIO& io = ImGui::GetIO();

	// Setup display size (every frame to accommodate for window resizing)
	io.DisplaySize = ImVec2((float)w, (float)h);

	// Setup time step
	int timeSinceStart = glutGet(GLUT_ELAPSED_TIME);
	float deltaTime = (timeSinceStart - oldTimeSinceStart) / 1000.0f;

	io.DeltaTime = deltaTime > 0.0 ? deltaTime : (float)(1.0f / 60.0f);
	oldTimeSinceStart = timeSinceStart;

	// Start the frame
	ImGui::NewFrame();

	// 1. Show a simple window
	// Tip: if we don't call ImGui::Begin()/ImGui::End() the widgets appears in a window automatically called "Debug"
	if (show_debug_window)
	{
		ImGui::SetWindowSize(ImVec2(200, 150), ImGuiSetCond_FirstUseEver);
		ImGui::SetWindowPos(ImVec2(0, screenHeight - 250));
		static float f = 0.0f;
		ImGui::Text("Debug information");
		ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
		if (ImGui::Button("Test Window")) show_test_window ^= 1;
		if (ImGui::Button("Camera Info")) show_cameraInfo_window ^= 1;
		ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
	}
	ImGui::Render();
}
```
How should  I handle the relationship between those buffers and IMGUI render() method? Thank you for concerning this matter.

**Comment by ocornut** [comment]
Classic GL curse apply - one of those function calls / GL state is interfering with the GL rendering function provided in the imgui_impl_xxxx file. In theory we try not to assume any GL states, but there are so many of them that it is difficult to get it right 100%.

You can start by selectively commenting out chunks of your ANTIALIASING block to find what exactly is affecting the `ImGui_ImplGlfwGL3_RenderDrawLists()` function. From there we can attempt to add extra GL state backup/restore in that function.

Note that imgui render doesn't need depth testing either.

**Comment by ocornut** [comment]
@Edwinzero Any update on this? It would be nice to fix the GL example code if there is something to fix!

**Comment by EladBahar** [comment]
Hi @Edwinzero or @ocornut 
did u solve it somehow?
thanks..

**Comment by ocornut** [comment]
Closing this as stalled. Might have been fixed by a change in the back-end since then, might not, but hard to see without iteration with one affected. Most high-level app would restore conflicting OpenGL state.
