### ISSUE TITLE
Minor: Function name in comment outdated

### ISSUE THREAD

**Issue by yazzn** [ocornut/imgui#1178]
Nothing urgent just an outdated comment I stumbled upon while messing around
imgui_draw.cpp:1164
> When using MergeMode make sure that a font has already been added before. You can use **ImGui::AddFontDefault()** to add the default imgui font.

has been moved to `ImGui::GetIO().Fonts->AddFontDefault();`

**Comment by ocornut** [comment]
Fixed, thanks!
