### ISSUE TITLE
gcc -Wconversion on ImColor::ImColor(int, int, int, int)

### ISSUE THREAD

**Issue by Roflraging** [ocornut/imgui#118]
Hi Omar,

In our code base we compile with very high warning and error settings.

As such, our code fails to compile when we get to the imgui header:

`dalekim1@lispy:/home/dalekim1/sjgame1 [master]> time ./make.sh -j8 config=release-assertions
==== Building gamelib (release-assertions) ====
==== Building imgui (release-assertions) ====
==== Building miniz (release-assertions) ====
imgui.cpp
DebugPanel.cpp
In file included from src/DebugPanel.cpp:20:0:
imgui/imgui.h: In constructor ‘ImColor::ImColor(int, int, int, int)’:
imgui/imgui.h:707:85: error: conversion to ‘float’ from ‘int’ may alter its value [-Werror=conversion]
     ImColor(int r, int g, int b, int a = 255)                       { Value.x = r / 255.0f; Value.y = g / 255.0f; Value.z = b / 255.0f; Value.w = a / 255.0f; }
                                                                                     ^
imgui/imgui.h:707:107: error: conversion to ‘float’ from ‘int’ may alter its value [-Werror=conversion]
     ImColor(int r, int g, int b, int a = 255)                       { Value.x = r / 255.0f; Value.y = g / 255.0f; Value.z = b / 255.0f; Value.w = a / 255.0f; }
                                                                                                           ^
imgui/imgui.h:707:129: error: conversion to ‘float’ from ‘int’ may alter its value [-Werror=conversion]
     ImColor(int r, int g, int b, int a = 255)                       { Value.x = r / 255.0f; Value.y = g / 255.0f; Value.z = b / 255.0f; Value.w = a / 255.0f; }
                                                                                                                                 ^
imgui/imgui.h:707:151: error: conversion to ‘float’ from ‘int’ may alter its value [-Werror=conversion]
     ImColor(int r, int g, int b, int a = 255)                       { Value.x = r / 255.0f; Value.y = g / 255.0f; Value.z = b / 255.0f; Value.w = a / 255.0f; }
                                                                                                                                                       ^
cc1plus: all warnings being treated as errors
make[1]: *** [obj/release-assertions/gamelib/DebugPanel.o] Error 1
make: *** [gamelib] Error 2
make: *** Waiting for unfinished jobs....
Linking imgui

real	0m6.856s
user	0m7.895s
sys	0m0.344s
dalekim1@lispy:/home/dalekim1/sjgame1 [master]> gcc --version
gcc (GCC) 4.8.3
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

For now, we get around this by just converting each component to float.

**Comment by ocornut** [comment]
Thanks, should be fixed now.
