### ISSUE TITLE
Combo always show me the last element in the array

### ISSUE THREAD

**Issue by LaurentGarcia** [ocornut/imgui#1180]
Hello there,

I have the following code, and for example if the variable texNumber has a value 4 I copy my vector of string to the char array pointers. the std::cout is telling me that I have different values in the array but the combo is always rendering the 4 values with the same last position value.... 

const char* textures[texNumber];

for (int i=0; i<texNumber;i++)
{
	textures[i] = this->shaderManager.getTextureName(i).c_str();
	std::cout<< textures[i] << std::endl;
}

// Kd Diffuse
ImGui::Text("Color");
static int  kdTextureSelected = 0;
ImGui::Combo("Albedo",&kdTextureSelected,textures,texNumber);

**Comment by ocornut** [comment]
I do not know what this could be happening with the following code. Did you remove something from your actual code?

By the way you probably do not want to be copying the pointers everywhere, instead, use the `ImGui::Combo` prototype that takes a getter, implement the getter to read from say, a std::vector<string> or whatever you use and create your own `ImGui::Combo` that does just that.

Something like:

```
static auto vector_getter = [](void* vec, int idx, const char** out_text)
{
    auto& vector = (std::vector<std::string>*)vec;
    if (idx < 0 || idx >= (int)vector.size()) { return false; }
    *out_text = vector.at(idx).c_str();
    return true;
};
 
bool Combo(const char* label, int* currIndex, std::vector<std::string>& values)
{
    if (values.empty()) { return false; }
    return Combo(label, currIndex, vector_getter,
        static_cast<void*>(&values), values.size());
}
```

**Comment by LaurentGarcia** [comment]
Thanks mate,
It's working you idea, and I'm agree with  you that pointers should be avoided! :dagger: 
THANKS for such a wonderful library :)

**Comment by ocornut** [comment]
@LaurentGarcia 

> I'm agree with you that pointers should be avoided!

This is not what I said at all. I said you shouldn't need to COPY data when calling Combo, that's unnecessarily expensive. Instead use those getter functions to retrieve the data on demand as Combo() needs it. Pointers are everywhere in C/C++ and cannot be avoided.
