### ISSUE TITLE
Not all style variables available to be set in PushStyleVar

### ISSUE THREAD

**Issue by kavika13** [ocornut/imgui#1181]
Might be intentional, didn't find anything in issues search right now for PushStyleVar

I could understand why some might be kept "private" for sandboxing purposes (window padding, safe area, touch padding), but some of them seem like they are mostly stylistic.

Here's a list of variables that are in the `ImGuiStyle` struct, but not in the `ImGuiStyleVar_` enum:

```
ImVec2 WindowTitleAlign;
ImVec2 TouchExtraPadding;
float ColumnsMinSpacing;
float ScrollbarSize;
float ScrollbarRounding;
float GrabRounding;
ImVec2 DisplayWindowPadding;
ImVec2 DisplaySafeAreaPadding;
bool AntiAliasedLines;
bool AntiAliasedShapes;
float CurveTessellationTol;
```

**Comment by ocornut** [comment]
Hello @kavika13,

It isn't really to sandbox them away, the reasoning was that you don't likely have a reason to change them on the fly within your UI code. They are typically set once and the procedure has been to poke into the style structure during say, initialization, via `ImGui::GetStyle().xxx =`. 

Out of curiosity do you need to change them during the course of your application running? or was it more coming from a desire of using the Push API consistently?

**Comment by kavika13** [comment]
I've exposed the push api to our mods scripting language, but so far I haven't exposed the style struct.

I'm considering sandboxing styles so that a mod cannot affect the style of another mod, and possibly not the main UI either. I could also do this via separate contexts, but so far I haven't found a strong need to go that far.

**Comment by ocornut** [comment]
@kavika13 Can you confirm if you are interested in exposing those specific values to your script?
It's still not really clear why you would want a mod to change the style of your UI with those specific variables (e.g. scrollbar rounding, sizes). 

> I'm considering sandboxing XXXX so that a mod cannot affect XXXX the main UI either.

Not sure how far you want to take than sandboxing, bot user calling imgui code will pretty much always be able to break stuff if they want.

**Comment by kavika13** [comment]
We are wrapping imgui before exposing them to our scripting layer, so some sandboxing (making sure calls are balanced) would be possible. The intention would be to prevent crashes and game breaking behavior, not to prevent espionage.

As for which style vars get exposed, the issue was filed with consistency in mind. It seems to me like unless there’s an inordinate perf or complexity cost, then several of those variables aren’t particularly special “app wide” vales. It would be valid to set them differently in different contexts. In our case, each mod migjt have good reason to have its own style, especially TC style mods.

**Comment by ocornut** [comment]
This is totally valid. I guess the reason I'm not thrilled about adding extra enums without a known user/use case is that I'm expecting styles to evolve and break over the year, and trying to discourage this situation where users of a scripting language with no compile-time checks are left with a million broken things. I personally think exposing too much of styles to your modders (especially as your game has been fairly successfully) may create a situation of tension where it'll become too costly for your community that you ever update imgui.

Of that list above `WindowTitleAlign` `ScrollbarSize` `ScrollbarRounding` `GrabRounding` are arguably stylistic, the others are more "system" variables. I'll add those 4 right now.

**Comment by ocornut** [comment]
Pushed. Let me know if there's anything else you feel should be added!

**Comment by ocornut** [comment]
Closing this old topic (was solved back then).
