### ISSUE TITLE
Is Combo() meant to return "true" even if current_item does not change?

### ISSUE THREAD

**Issue by francholi** [ocornut/imgui#1182]
Hi,

I am trying out Combo, and it feels like I don't want to run code if the selected option does not change, but if I click on it, no matter what I choose I will always get true as return value. 

A trivial change to the code saving current item at the top and checking at the very end does the job for me, but I was just wondering if this was the expected behavior and what was the rationale for it.

Just to clarify, I understand that when I click outside the combo it returns false, this question is only about clicking the same option that was selected before.

thanks!
Francisco

**Comment by francholi** [comment]
Just to clarify further, I understand that if I click outside the combo it returns false :)

**Comment by ocornut** [comment]
> this question is only about clicking the same option that was selected before.

You are correct that at the moment, if you click the _same_ option again it will return true. The consistent behaviour over widgets has been to do that, but it is certainly debatable. We could change/fix that.

FYI the change would be turning:

```
                if (Selectable(item_text, item_selected))
                {
                    ClearActiveID();
                    value_changed = true;
                    *current_item = i;
                }
```
Into
```
                if (Selectable(item_text, item_selected))
                {
                    ClearActiveID();
                    if (*current_item != i)
                    {
                        value_changed = true;
                        *current_item = i;
                    }
                }
```

**Comment by francholi** [comment]
Great!, thanks. I have just started using it, so now I know what to expect in that particular case.

If someone is using that _true_ value as some sort of _reload_ mechanism of whatever is selected, then the change could affect them significantly, so I can totally live with the way it works now :)

**Comment by ocornut** [comment]
I think the change is fairly sensible but I would have to think about the consequences on user codebases.
I think a future better Combo() API may want to introduce flags to select that sort of behavior.

**Comment by nem0** [comment]
In one of my projects I use combo as a navigation and if I select something already selected, the page refreshes. If the behaviour is changed, I can no longer do that. On the other hand if it stays the same I can still do ```old_value != new_value```.

**Comment by ocornut** [comment]
Thanks Mikulas. Will leave it as is for now, took note that we could expose this behavior later/somehow.

**Comment by francholi** [comment]
Sorry, I didn't know if I was meant to close this or not, then I saw Mikulas comment and re-opened it but I am happy with the answers.

**Comment by ocornut** [comment]
I have eventually pushed this change for consistency. Commit: a02315e.
In the event someone needs this for reloading, they can use the flexibility of the `BeginCombo()` api.
