### ISSUE TITLE
Checking to see if the scrollbar was clicked

### ISSUE THREAD

**Issue by DaulPavid** [ocornut/imgui#1185]
I don't know if this is actually missing or it's just not obvious to me.
Is there any way to check if the window scrollbar has been clicked / is being held down?

**Comment by ocornut** [comment]
The undocumented way right now would be to do `GImGui->ActiveId == GImGui->CurrentWindow->GetID("#SCROLLX");` however that may break with future update. 

It would be more interesting to understand why would you like to do that / what you are trying to achieve, and from there we can devise a solution.

**Comment by DaulPavid** [comment]
I have both the X and Y scroll enabled on a window, and I also scroll vertically if the mouse is dragging up or down within the window. I'd like to disable that scrolling if the user is holding down and dragging on the bottom scrollbar because I otherwise might induce vertically scrolling while dragging the horizontal scroll bar. If needed, I'll post a visual to illustrate what I mean.

**Comment by ocornut** [comment]
Presumably if you are capturing drags over the window, you have a widget e.g. InvisibleButton() in there covering the window so that it doesn't move? Then you can perform your own scrolling when that widget is active? I'm not sure how is your setup.

**Comment by ocornut** [comment]
@DaulPavid FYI there's a function `ImGuiID GetScrollbarID(ImGuiWindow* window, ImGuiAxis axis)` in imgui_internal.h, so you can replace the code above with:

```
ImGuiWindow* window = ImGui::GetCurrentWindow();
ImGuiID active_id = ImGui::GetActiveID();
bool any_scrollbar_active = active_id && (active_id == ImGui::GetScrollbarID(window, ImGuiAxis_X) || active_id == ImGui::GetScrollbarID(window, ImGuiAxis_Y)
```

Unlike the solution above this is not likely to ever break with future updates.

**Comment by LeonardoCBoar** [comment]
Just to help anyone who stumbled here,
`GetScrollbarID` was renamed to `GetWindowScrollbarID` , so the updated code is:

```
ImGuiWindow* window = ImGui::GetCurrentWindow();
ImGuiID active_id = ImGui::GetActiveID();
bool any_scrollbar_active = active_id && (active_id == ImGui::GetWindowScrollbarID(window, ImGuiAxis_X) || active_id == ImGui::GetWindowScrollbarID(window, ImGuiAxis_Y)
```

**Comment by UnrealKaraulov** [comment]
@ocornut now this solution is breaked :)

Please update solution ?:)

**Comment by dan-roboticarm** [comment]
I have a similar issue, but specifically for scrollbars in a table.  This code does not seem to work for me. I tried passing in the current window to GetWindowScrollbarID, but it always failed. I also tried passing in the child window of the table to GetWindowScrollbarID but that also did not work.
