### ISSUE TITLE
Modularize ImGUI

### ISSUE THREAD

**Issue by stevefan1999** [ocornut/imgui#1186]
Separate default widgets into different components.

Some are never used but was included anyway. Right now I had to manually remove them which is a pretty hard mess and causes me some trouble updating ImGUI.

**Comment by ocornut** [comment]
Then don't remove them. What is the purpose of removing widgets? 

Existing ImGui features won't be split into more files. The gain would be worthless and it would go against the philosophy of this project, sorry.
