### ISSUE TITLE
How to align text in window

### ISSUE THREAD

**Issue by msmshazan** [ocornut/imgui#1187]
How to align text in window not in buttons and title bar?

**Comment by ocornut** [comment]
Hello @msmshazan, there aren't specific alignment primitives. It's probably better if you explain what you are trying to do.

You can use SetCursorPosXXX functions to position cursor before drawing if you want to position things in a certain way (not particularly high-level).

**Comment by msmshazan** [comment]
Thanks currently using set cursor pos but it gets tedious to calculate string length.
Is it possible to calculate string length of formatted strings.

**Comment by ocornut** [comment]
You'd currently need to create your own helper to format the string into a buffer, calciulate size to set position then display. It's easy to do for single-line text.

**Comment by esemeniuc** [comment]
Could you provide an example if possible? It'd help people google for this (like myself)

**Comment by ocornut** [comment]
ImGui doesn't have alignment primitives, if you want to align things everywhere you'll be fighting against the tide. msmshazan's original topic was vague and ill-defined and I should have closed this topic before (closing it now). I'm happy to help but please ask _very specific_ questions and include the context. "Align text in window" is too vague.
