### ISSUE TITLE
Minor issue with SBTT_Free

### ISSUE THREAD

**Issue by septag** [ocornut/imgui#119]
I don't know If it should be considered as a bug or not. (or just a documentation tip)
STBTT_Free in the stb_truetype.h sometimes passes NULL pointer. So the client app that overrides free/alloc should check for the pointer not being null and then do his stuff.

**Comment by ocornut** [comment]
It is standard for both free() and delete to do no action on NULL.
http://www.tutorialspoint.com/c_standard_library/c_function_free.htm
I am adding a comment tho. Thanks!
