### ISSUE TITLE
Removing fonts?

### ISSUE THREAD

**Issue by paulsapps** [ocornut/imgui#1190]
How can I remove a font? 

My use case is this: I am trying to render subtitles which are always a certain percentage of the screen size. So I add a font of that size. But if the user resizes the window then I need to remove the font and add a new one with the correct size.

This is how I add the font:

```
    ImGuiIO& io = ImGui::GetIO();
    ImFontConfig config;
    config.OversampleH = 3;
    config.OversampleV = 3;
    io.Fonts->AddFontFromFileTTF((mFileSystem->FsPath() + "data/Roboto-Regular.ttf").c_str(), Percent(7, screenH), &config);
```

But seems there is no API to remove it?

**Comment by ocornut** [comment]
There is none because you would currently have to entirely clear the font atlas first anyway.

**Comment by paulsapps** [comment]
DOH seems obvious now! Thanks.

**Comment by ocornut** [comment]
Removing font at anytime will be supported by 1.92. Work in progress `dynamic_fonts` (#8465) branch has it.
