### ISSUE TITLE
ImDrawList missing PrimTriangleUV?

### ISSUE THREAD

**Issue by paulsapps** [ocornut/imgui#1191]
I'm trying to use ImDrawList to render some 'external' textured triangles. But it appears there is no API to do it?

It seems like it should be possible to do but I'm not sure how to do it. PrimQuadUV seems like it should be quite close to what I'm trying to do. But I don't understand its implementation.

Is there already a function for this I've missed? If not then any pointers on how to adapt PrimQuadUV for a single triangle?

Edit: Here is my failed attempt

```
static void PrimTriangleUV(
    ImDrawList& list,
    const ImVec2& a,
    const ImVec2& b,
    const ImVec2& c,
    //const ImVec2& d,
    const ImVec2& uv_a,
    const ImVec2& uv_b,
    const ImVec2& uv_c,
   // const ImVec2& uv_d,
    ImU32 col)
{
    ImDrawIdx idx = (ImDrawIdx)list._VtxCurrentIdx;
    list._IdxWritePtr[0] = idx; 
    list._IdxWritePtr[1] = (ImDrawIdx)(idx + 1); 
    list._IdxWritePtr[2] = (ImDrawIdx)(idx + 2);
  //  list._IdxWritePtr[3] = idx;
   // list._IdxWritePtr[4] = (ImDrawIdx)(idx + 2);
   // list._IdxWritePtr[5] = (ImDrawIdx)(idx + 3);

    list._VtxWritePtr[0].pos = a; list._VtxWritePtr[0].uv = uv_a; list._VtxWritePtr[0].col = col;
    list._VtxWritePtr[1].pos = b; list._VtxWritePtr[1].uv = uv_b; list._VtxWritePtr[1].col = col;
    list._VtxWritePtr[2].pos = c; list._VtxWritePtr[2].uv = uv_c; list._VtxWritePtr[2].col = col;
    //list._VtxWritePtr[3].pos = d; list._VtxWritePtr[3].uv = uv_d; list._VtxWritePtr[3].col = col;

    list._VtxWritePtr += 3;// 4;
    list._VtxCurrentIdx += 3;//4;
    list._IdxWritePtr += 3;// 6;
}
```

**Comment by ocornut** [comment]
That function looks correct. 
Note that when using `PrimXXX` functions you need to call `PrimReserve` priorhand, so if you want to draw a single triangle you'd do `PrimReserve(3,3)` + `PrimTriangleUV`.

**Comment by paulsapps** [comment]
You are right.. I was stomping over other data - it pays to use debug builds, thanks! :(
