### ISSUE TITLE
g.IO.Fonts->Fonts.Size > 0

### ISSUE THREAD

**Issue by 0xFTP** [ocornut/imgui#1193]
Okay.. So I have been stuck with this error/crash for a couple of days now. I have literally no idea how to fix it. Any help would be appreciated. I'm running 32-bit d3d9 latest ImGui.

**Comment by paulsapps** [comment]
I believe this means the font isn't loaded. Check the path is correct etc.

**Comment by 0xFTP** [comment]
I'm not loading any fonts. I reckon that is the problem? I'm gonna try and grab the fonts provided by ImGui and see, if the error persists.

**Comment by sgf** [comment]
hm,i think u should be show out the code or give out more information.

**Comment by sgf** [comment]
ImGuiContext& g = *ImGui::GetCurrentContext();
g.Font //this is the code to get current font.

**Comment by ocornut** [comment]
@0xFTP You typically need to call GetTexDataAsRGBA32() to build the font texture, which will add a default font if there's none. Check what the DX9 example is doing.

**Comment by ocornut** [comment]
Did you read the comment associated to your assert?

```
IM_ASSERT(g.IO.Fonts->Fonts.Size > 0); // Font Atlas not created. Did you call io.Fonts->GetTexDataAsRGBA32 / GetTexDataAsAlpha8 ?
```

**Comment by 0xFTP** [comment]
Oooh, yup. So sorry, didn't read that. I got it working now. Thanks for the help.
