### ISSUE TITLE
ImageButtons w/ Text?

### ISSUE THREAD

**Issue by MonkahTV** [ocornut/imgui#1195]
Hi, Ocornut!

I was wondering if there was any possible method of accomplishing an image-button with dynamic/IMGUI text.

The only real idea I had was overlapping a text widget and an imagebutton widget, but IMGUI doesn't seem to support overlapping very well. Or maybe using the graphics processing engine to render an image at the location of a transparent text button-- although finding texture-coords of an element doesn't really seem to be a possibility (nor a clean solution)

Any ideas as to how I could go about accomplishing this?

**Comment by ocornut** [comment]
Somehow this never got answered....

You can manually overlap text using the `ImDrawList::AddText()` function, based on the render state of your button.

While undocumented and expected to (at last!) evolve during the year, the RenderTextXXX helpers functions in imgui_internal.h provide additional functionalities such as ellipsis and clipping. They'll be reworked as public API later.
