### ISSUE TITLE
tips on Getting it to work with eclipse?

### ISSUE THREAD

**Issue by mfriendc** [ocornut/imgui#1197]
I've been trying to use eclipse so I don't get stuck with visual studio, but whenever I try to add imgui as a library (following the tutorial steps exactly, mind you) it always says "couldn't find -I[directory]" I tried so many things, and even tried simply copying all of the files into my src folder, but that doesn't seem like the correct way to do it either

is eclipse just a bad program? I don't understand what I'm doing wrong, and if I can't install imgui as a library, I don't know how I'm supposed to install glfw or gl3w either

(sorry for posting this in issues, I honestly don't know where else to put it)

**Comment by ocornut** [comment]
I think you'd get better help in a place where people know about Eclipse. I don't even know if Eclipse is just an IDE or also a build system or both. Presumably adding .cpp/.h files to an existing c++ project should be trivial with any software. 

For glfw/gl3w if that's what you want to use in your application, adding library to link (with external include/library paths) might be a little less trivial depending on the software/os but it should be covered by most documentations/tutorials/forums.

**Comment by mfriendc** [comment]
I guess it's neither since it doesn't work for any of the complicated things I want to do with it

I suppose what I should ask for clarification is, in their tutorials they keep referencing "libraries" as things with a ".o" or ".so" file like "libboost.o" but imgui doesn't have one of those, and I'm not sure how to use it as a library since it doesn't match their assumed pattern for a library, am I missing something about how libraries work?

**Comment by ocornut** [comment]
Dear imgui is the unusual one here, we're avoiding distributing or considering it as a traditionally library because it's causing way too many troubles for windows users (this is partly why single-file libs are popular).

.o, .so, .lib are compiled objects/libraries. Here you want to be adding to the source file to your project. Just like you probably have a "main.cpp" in your project. Just consider that you are copying the imgui files into your own existing project, aka copy the .cpp+.h files in your app directory (say, create an imgui/ folder and copy that) and add them your eclipse project. No library involved.

**Comment by mfriendc** [comment]
alright, I think that makes a lot more sense, then, thank you for the clarification

**Comment by mfriendc** [comment]
something still seems to be wrong

I've given up on expecting eclipse to do anything on its own, so I've switched all of my includes to absolute links, but when I do that, all of the IMGUI_API lines hilight in red and say IMGUI_API does not name a type, I followed back to the definition and all it does is #ifndefine IMGUI_API\n#define IMGUI_API\n#endif 

I don't understand what's going wrong here

**Comment by ocornut** [comment]
Eclipse is most probably not a broken program, or at least not broken not in the way you think. C++ ecosystem is just difficult to understand. Get yourself books at C/C++ if you have time :)
