### ISSUE TITLE
ImGuiStyleVar_Alpha is unused

### ISSUE THREAD

**Issue by astillich** [ocornut/imgui#1198]
I just got confused by this while trying to create a transparent window: ImGuiStyleVar_Alpha isn't referenced anywhere in the code base except for imgui.h and I think it should be removed.

**Comment by ocornut** [comment]
It's actually working but not explicitly reference (there was a table implicitly referring to the enum order).  I have now added comments to clarify the non-obvious relationship between this and the data structure and the internal code.

Note that 'Alpha' may not actually be what you want here, as you rarely want transparent text, but more often transparent background window (see `styles.Colors[ImGuiCol_WindowBg]`).
