### ISSUE TITLE
Assertion _format_char != ₩0

### ISSUE THREAD

**Issue by ShovelBox** [ocornut/imgui#1201]
Hello, my Chinise/Japaneese/Korean users have some troubles, application just crashes when tries to print hieroglyphs.

I tried to reproduce it on my computer, but it works fine at my side. I started investigation and changed my default windows language from RU -> KR (Korean). And app started to crash.

I started debug build and found something.
ImGui::TextUnformatted is able to display hieroglyphs fine,
ImGui::Text throws assertion (screenshot attached)

P/s: Project character set: Use Unicode Character Set
Source file encoding UTF-8
ImGui is able to display hieroglyphs fine.
At my locale (RU/EN) ImGui::Text is able to display everything fine.
Any ideas or tips? Thanks!

```
ImVec4 col = ImColor(255, 255, 255);
ImGui::PushStyleColor(ImGuiCol_Text, col);
ImGui::TextUnformatted(u8"弄得好");  <-- Its fine
ImGui::PopStyleColor();

ImGui::Text(u8"弄得好"); <-- Assertion and crash here
```
![Screenshot](https://image.prntscr.com/image/BYlkT4Z7RAmCuCDmAxtqWg.png)

**Comment by ocornut** [comment]
UTF-8 is designed to never contains any byte <128 within encoded characters that aren't Ascii.

Can you dump the data of the string literal you got here? With:

const char* p = u8"弄得好";
for (int n = 0; p[n]; n++)
    printf("p[%d] = %02x\n", n, p[n]);

**Comment by ShovelBox** [comment]
here is a result:

```p[0] = ffffffe5
p[1] = ffffffbc
p[2] = ffffff84
p[3] = ffffffe5
p[4] = ffffffbe
p[5] = ffffff97
p[6] = ffffffe5
p[7] = ffffffa5
p[8] = ffffffbd
```

**Comment by ocornut** [comment]
I got the format wrong in the dumping code (or should have masked with 0xFF) but anyway, as expected there's no value that are under 0x80 so I don't understand why vsnprintf() would react to it.

The safe/correct way would be to use a "%s" format string anyway, but I don't quite understand why that UTF-8 string wouldn't work even as a format string.

**Comment by ShovelBox** [comment]
![](https://image.prntscr.com/image/XAtpXz-uTmiwhZtCbORZAQ.png)

```
int ImFormatStringV(char* buf, int buf_size, const char* fmt, va_list args)
{
	printf("Before vsnprintf\r\n");
	for (int n = 0; buf[n]; n++)
		printf("buf[%d] = %02x\n", n, buf[n]);

	printf("buf_size = [%d]\r\n", buf_size);

	for (int n = 0; fmt[n]; n++)
		printf("fmt[%d] = %02x\n", n, fmt[n]);

    int w = vsnprintf(buf, buf_size, fmt, args);
	printf("After vsnprintf\r\n");
    buf[buf_size-1] = 0;
    return (w == -1) ? buf_size : w;
}
```

![](https://image.prntscr.com/image/kxb6_IgmQUKjja_Le7iaYQ.png)

If I switch back to english or russian, it will work fine. Maybe locale-dependent settings changes vsnprinf behaviour... I'll continue my investigation.

**Comment by ShovelBox** [comment]
``setlocale(LC_CTYPE, "");`` was a reason for this unexpected problem (it helped me to resolve problems with cyrillic characters in paths, but ruined application on korean system language.)

I hope this information will help someone in future
