### ISSUE TITLE
Context Menu only on right click

### ISSUE THREAD

**Issue by rjx-ray** [ocornut/imgui#1203]
I'm trying to create a copy/paste context menu on a input text field that is activated by a right click.
Trouble is I get the menu on any mouse click no matter which mouse button I specify.
My code is like this:

bool gotInput = (ImGui::InputText("", urlText, 1024, EnterForTrue));
static float value = 0.5f;
if (ImGui::BeginPopupContextItem("item context menu",3))  {
	if (ImGui::Selectable("Copy")) value = 0.0f;
	if (ImGui::Selectable("Paste")) value = 3.1415f;
	ImGui::EndPopup();
}
if (gotInput) {
	doSomeThing;
}

Changing the specified mouse button in the call to BeginPopupContextItem() seems to have no effect, I always get the popup on any button. This prevents me from entering text normally after selecting the field with the left button.

Am I doing something wrong?

I am using dear imgui, v1.50 WIP with ofxImGui for Open Frameworks 0.9.7 release under Windows 10.

By the way, CTRL-C and CTRL-V do work

Thanks in advance for any help

**Comment by ratchetfreak** [comment]
How do you fill the IO.MouseDown array?

**Comment by rjx-ray** [comment]
I didn't do anything about that, didn't realise I had to. Could you point me at an explanation. - Thanks

**Comment by rjx-ray** [comment]
OK, I'm following it through, something wrong in the open frameworks add on. thanks for the hint
