### ISSUE TITLE
Going cpu idle / Redisplay when using glfwWaitEvents() in main loop?

### ISSUE THREAD

**Issue by jdumas** [ocornut/imgui#1206]
Hi there,

I have a question about using ImGui + Glfw when the application is not permanently refreshed, i.e. when there is a `glfwWaitEvents()` in the main loop. Let's say we take the `opengl3_example` app, and add a `glfwWaitEvents();` after [L89](https://github.com/ocornut/imgui/blob/d3f4309491517a4412b6738063ded96f61fa020f/examples/opengl3_example/main.cpp#L89).

Now, if you launch the app, the FPS is only updated when you move the mouse, which makes sense. However, if I click on the color picker (to switch between RGB/HSV/Hex), but don't move the move, then things are updated only when I move the mouse again.

I was wondering if it was a limitation of ImGui's immediate mode, a problem in the ColorEdit widget, or something more general that should be done in the glfw main loop of this example?

**Comment by ocornut** [comment]
Always update for 1-2 extra frames after mouse is moved and it should be ok.

**Comment by ocornut** [comment]
To clarify, several types of actions incur a frame of delay. For example when you open a popup, the first frame is used for a dry run to compute an initial size for the popup. 

Ideally, imgui should expose a flag/timer to express that sort of thing optimally and reliably, and also allow you to e.g. refresh on a cursor blink if you desire so (probably unlikely).

**Comment by jdumas** [comment]
Thanks for the answer, I see your point. I'll to modify my main loop accordingly, even though it gets a bit more cumbersome to do so.

**Comment by ocornut** [comment]
@jdumas Let me know if this is working out for now, and if the issue can be closed! Thanks.

**Comment by jdumas** [comment]
@ocornut Sure. Right now I'm refreshing the display constantly to make the UI is responsive. Would still be nice to have `bool ImGui::NeedRedraw()` callback or something.

**Comment by ocornut** [comment]
Why not just doing this in the meanwhile?
> Always update for 1-2 extra frames after mouse is moved [or keyboard is pressed].

It should be a matter of just adding a counter on your side and resetting it on any input event.

**Comment by jdumas** [comment]
I just didn't get around to do that yet, since I have something that works already :p.
Feel free to close the issue if you like, and I'll reopen it if I have further questions =)
