### ISSUE TITLE
Appending to existing menus?

### ISSUE THREAD

**Issue by degracode** [ocornut/imgui#1207]
Is there a way that you can extend a menu that's already been created elsewhere? Quite often it's useful for sub-systems and unconnected bits of code to expose new commands etc in the main menu bar, but at the moment each call to BeginMenu() will create a new menu, rather than extending the previous instance of it.

Effectively, I want this code:
```
if(ImGui::BeginMenu("Test"))
{
	ImGui::MenuItem("Test Item 1");
	ImGui::EndMenu();
}

if(ImGui::BeginMenu("Test"))
{
	ImGui::MenuItem("Test Item 2");
	ImGui::EndMenu();
}
```
to behave as-if I'd simply done this:
```
if(ImGui::BeginMenu("Test"))
{
	ImGui::MenuItem("Test Item 1");
	ImGui::MenuItem("Test Item 2");
	ImGui::EndMenu();
}
```
however I end up with two menus, that have aliased input, and a weird clipping issue with the second item's text:
![image](https://user-images.githubusercontent.com/7349637/27662267-0749dd14-5c55-11e7-96c9-cc9bbaa78ed9.png)

**Comment by ocornut** [comment]
Appending doesn't work in menus yet. I forgot the exact reason right now. Would ideally want to fix it but probably not a high priority, will keep that noted though.

**Comment by stonecompass** [comment]
Will this be possible at some point in the near future?

**Comment by ocornut** [comment]
If someone tries to get it to work, yes. I have too much on my plate to be looking at it myself at the moment, hence the dangling open issue.

**Comment by ocornut** [comment]
This is now supported thanks to commits 0342a3c and 24bd33a!

**Comment by ocornut** [comment]
Pushed a fix where it using Left<>Right arrow to navigate within horizontally layed out item of a appended menu would erroneously close the menu (bd2355a)
