### ISSUE TITLE
ImGui swich page not working

### ISSUE THREAD

**Issue by mDenis16** [ocornut/imgui#1210]
ImGui::Begin(charenc("Ragebot Settings"), &Vars.Menu.Ragebot, ImVec2(300, 500), 0.9f, ImGuiWindowFlags_NoCollapse);
	
			{
				const char* tabs[] = {
					"Aimbot",
					"Triggerbot",
					"Visuals",
					"HvH",
					"Misc",
				};
				int tabs_size = sizeof(tabs) / sizeof(tabs[0]);

				for (int i = 0; i < tabs_size; i++)
				{
					ImVec2 windowSize = ImGui::GetWindowSize();
					int width = windowSize.x / tabs_size - 9;

					int distance;
					if (i == page)
						distance = 0;
					else
						distance = i > page ? i - page : page - i;

					if (ImGui::Button(tabs[i], ImVec2(width, 0)))
						page = i;

					if (i < tabs_size - 1)
						ImGui::SameLine();
				}
				ImGui::Separator();
//identifier "page" is undefined
				switch (page)
				{
				case 0:
					AimbotTab();
					break;
				case 1:
					VisualTab();
					break;
				case 2:
					TriggerbotTab();
					break;
				case 3:
					HvHTab();
					break;
				case 4:
					MiscTab();
					break;
				}
			}
			ImGui::End();
		}

**Comment by ocornut** [comment]
You probably need a static or global variable called `page` here.. this isn't really an imgui issue and I encourage you to ask that sort of question on generic programming forums such as StackOverflow. This place isn't really the place for us to solve generic programming issues.

For future requests of that sort, please use sentences words to clearly, thoroughly explain the problem. Also please say thanks!
