### ISSUE TITLE
Merging fonts

### ISSUE THREAD

**Issue by vossik** [ocornut/imgui#1212]
Hello, I'm probably very very stupid but I have problems with merging fonts (Verdana and Font Awesome)
Here is my code:
#include "IconsFontAwesome.h"
ImFontAtlas _fonts;
_fonts.AddFontFromFileTTF(Fonts\Verdana.ttf, 14.0f, 0, _fonts.GetGlyphRangesDefault());
_fonts.AddFontDefault();
static const ImWchar icons_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };
ImFontConfig icons_config; icons_config.MergeMode = true; icons_config.PixelSnapH = true;
_fonts.AddFontFromFileTTF("Fonts\fontawesome-webfont.ttf", 14.0f, &icons_config, icons_ranges); 
_fonts.GetTexDataAsRGBA32(&pixel_data, &width, &height, &bytes_per_pixel);

But when i use something like ICON_FA_FILE, i shows ? at my GUI. What am i doing wrong?

**Comment by ocornut** [comment]
Hint: use imgui to debug your imgui issues!
If you call `ImGui::ShowStyleEditor()` it has a block that allows you to inspect what your fonts are.

Here you would have 2 font, first one is Verdana, second one Default+Icons, you'd need to use `PushFont` to select the later, have you done that?

**Comment by ocornut** [comment]
@vossik Closing this as I believe I answered your question. Let me know if you still have issues.
