### ISSUE TITLE
DirectX example fps counter inaccurate - Win10

### ISSUE THREAD

**Issue by dylmye** [ocornut/imgui#1213]
DirectX11 and DirectX9 example binaries show a crazily inaccurate FPS count for whatever reason on Win10 X64. OpenGL2 and 3 show the correct value of ~60fps.

Maybe I don't understand properly but it just seems wild.

![comparison of directx and opengl FPS counters](https://user-images.githubusercontent.com/7024578/27833573-58076c92-60cb-11e7-94b4-6d77db545feb.png)

**Comment by ocornut** [comment]
It's accurate it's just that the example application doesn't explicitly ask for vsync.. so depending on driver setting you may get or not vsync.

Without vsync it running unthrolled at maximum possible speed (which is convenient to measure imgui performances, but drains a CPU core and GPU and not really desirable but real applications, you want to limit frame rate.)

**Comment by dylmye** [comment]
Ah, thanks. Sorry!
