### ISSUE TITLE
How To Change InputText's Value

### ISSUE THREAD

**Issue by DrJedikiah** [ocornut/imgui#1216]
Hi, I made a simple gui and I made a login screen, so I have two inputs and a button.
The issue is, I wanna make a remember me button but I can't change the value of the input in load.
`static char username[64] = GetUsername();
ImGui::InputText("Username", username, 64, ImGuiInputTextFlags_CharsNoBlank);`

How I can set the input? I can't set it like username = something; either. GetUsername() is string btw.

**Comment by DrJedikiah** [comment]
I've discovered a function called strcpy :D :D Problem solved.

**Comment by ocornut** [comment]
Nice color theme!
