### ISSUE TITLE
Know if active widget is an InputText

### ISSUE THREAD

**Issue by Lugruf** [ocornut/imgui#1219]
I'm working on an editor for a game where, when I press delete, the selected objects should be destroyed unless an InputText widget is active. I don't want to be editing some string property of an object, press delete to remove a character and destroy the object instead. I can use ImGui::IsAnyItemActive to know if there's an active widget, but I don't have any clue about what the item is, so that would cause false positives. Is there a way of knowing if a widget of type InputText is active?

Thanks in advance

**Comment by ocornut** [comment]
Are you sure what you need isn't the existing io.WantCaptureKeyboard flag?

**Comment by Lugruf** [comment]
It was exactly that. Thank you very much
