### ISSUE TITLE
Getting a list of variables in a window/group

### ISSUE THREAD

**Issue by Hperigo** [ocornut/imgui#1220]
Hi, is it possible to get a list of variables inside a window or a group? 

for example:
--
```
ImGui::Text("Hello, world!");
ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
ImGui::ColorEdit3("clear color", (float*)&clear_color);
if (ImGui::Button("Test Window")) show_test_window ^= 1;
if (ImGui::Button("Another Window")) show_another_window ^= 1;
ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
```
and something like:
```
std::vector<float> im_floats = ImGui::GetSliderFloats();

for(auto& f : im_floats){
saveFloatsToJson(f);
}

```
I trying to simplify the way I edit and serialize my variables. That way I can automate a little bit this process, instead of having to list them in ImGUI and a serialization lib.

any help is appreciated =)
thanks!

**Comment by ratchetfreak** [comment]
you can put all the floats in a struct:

```C++
struct values{
float f;
float[3] clear_color;
} vals;
ImGui::Text("Hello, world!");
ImGui::SliderFloat("float", &valsf, 0.0f, 1.0f);
ImGui::ColorEdit3("clear color", &vals.clear_color[0]);
if (ImGui::Button("Test Window")) show_test_window ^= 1;
if (ImGui::Button("Another Window")) show_another_window ^= 1;
ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
```

Then you can dump the values struct.

**Comment by ocornut** [comment]
Henrique, your question doesn't really make sense in the context of imgui, as imgui doesn't hold on any of your data. You completely own the data.

Often game engine would store type information in some ways (either in data, such as storing types and offsets, either expressed in code) that they can use for serialization and imgui output.

**Comment by ocornut** [comment]
Closing this.

**Comment by Hperigo** [comment]
Hi Omar & ratchetfreak, 
thank you for the fast reply.

I do a lot of experimentation  with opengl and interactive installations, and that would have been an easy (lazy? o.O) way of serializing the data without thinking to much about it, so I just had to ask =)

thank you again
bye bye.
