### ISSUE TITLE
Load fonts

### ISSUE THREAD

**Issue by oktay0** [ocornut/imgui#1222]
Hello, how do I load fonts for ImDrawList::AddText?
I tried 
ImFont* pFont = ImGui::GetIO().fonts->AddFontFromTtf("C::\\1.ttf", 14.f);
drawlist->AddText(pFont, ...)

But this cause a crash. I use DX9

**Comment by oktay0** [comment]
I tried to load Microsoft Yi Baiti and places it to "C:\\1.ttf"

**Comment by ocornut** [comment]
If you say that something is causing a crash, please provide a callstack.

Your path is wrong C/C++ and most languages uses \ as the escape character in strings so if you want a \ character you need to double it.

**Comment by oktay0** [comment]
![image](https://user-images.githubusercontent.com/30021267/27994430-186c64e8-64e0-11e7-983c-6d2b870228f2.png)
 here is my code

![image](https://user-images.githubusercontent.com/30021267/27994425-06c4c10e-64e0-11e7-8de7-5173f700005b.png)
here is the error

**Comment by ocornut** [comment]
1/ Please provide a callstack.

2/ Add an assert that pFont!=NULL to check if the font was loaded. 

3/ When adding fonts you need to Build the font atlas and then upload your texture in memory as explained and done in every example, you don't seem to be doing it.

**Comment by oktay0** [comment]
`_drawList->AddText(ImVec2(30, 30), ValveSDK::Color::Black().GetU32(), "SampleText");`
![image](https://user-images.githubusercontent.com/30021267/27994886-cbf23234-64e7-11e7-8b9f-ce66aeea8d04.png)

**Comment by ocornut** [comment]
Please provide a useful callstack aka one where you own code has been compiled with enough debug information to see somehow.

Also see other points.

**Comment by oktay0** [comment]
![image](https://user-images.githubusercontent.com/30021267/27996485-a484c528-6504-11e7-9576-deaee7a4e0eb.png)
Sorry for the delay

**Comment by ratchetfreak** [comment]
We don't have a crystal ball, Nor do we have infinite time. 

Please try and provide as much information we'll need to reproduce your issue. 

Try and extract all the calls you make to imgui that leads up to the crash.

**Comment by ocornut** [comment]
You need to call ImGui::NewFrame() to setup the initial window pointers and fonts.

**Comment by oktay0** [comment]
ImGui::NewFrame() is called in ImGui_ImplDX9_NewFrame() and I call it in PreRender(device) (see screenshots)

**Comment by oktay0** [comment]
Maybe there is a way to add ID3DXFont* somehow to ImDrawList?

**Comment by ocornut** [comment]
It's hard to help you without appropriate information. Compiling in Debug mode would get you a better callstack. e.g. It looks like the inferred ImVector<ImGuiWindow*> type is wrong as ImDrawList doesn't use those types.

> Maybe there is a way to add ID3DXFont* somehow to ImDrawList?

No. 

Q: Do you get the crash if you don't try to add/load that font?
