### ISSUE TITLE
Absolute positioning of text label?

### ISSUE THREAD

**Issue by jdumas** [ocornut/imgui#1227]
Hi,

I would like to use ImGui as an easy way to show the id (text label) of mesh vertices in a 3D viewer. For that I'd need to position a text label `ImGui::Text` at an absolute (x,y) position (within the viewport). Is it possible with the current API? If not, would you consider adding this feature? Controlling the Z value of the label would also be a plus (obviously), but I could live without.

It seems overkill to create one window per label with `SetNextWindowPos`, but I guess that could work (if I were to somehow hide the window frame and background).

**Comment by ocornut** [comment]
Use SetCursorScreenPos() or direct calls to draw_list->AddText() if you don't need interactive widget.

You may create your own ImDrawList or create an invisible, fullscreen window with no inputs.

**Comment by jdumas** [comment]
Ok got it! It still need an englobing window that I have to extend to the whole screen and make transparent, but that should work, thanks!

**Comment by ocornut** [comment]
Probably a good idea to just use a ImDrawList instance!

**Comment by jdumas** [comment]
So I can just create a new `ImDrawList()` with default everything and use it directly to draw my labels?

**Comment by ocornut** [comment]
Yes, and then you only need to render this ImDrawList in your renderer the way you render others. The only requirement is that you initialize ImGui atlas because imDrawList relies on it.

We're missing an API to manually register a draw list. In your render function you can copy draw_data->CmdLists to add the new pointers if that's convenient, or factorize your render function to be able to call it with a single draw list, or create and setup a ImDrawData instance with 1 draw list and call your render function with it. Something like:

```
ImDrawData draw_data;
draw_data.Valid = true;
draw_data.CmdLists = &my_draw_list;
draw_data.CmdListsCount = 1;
MyRenderFunc(&draw_data)
```

**Comment by jdumas** [comment]
I see what you mean. As it is now, it's probably as much code to use a dedicaded transparent imgui window (which I have implemented already). That way I don't have to touch or expose the `ImGui_ImplGlfwGL3_RenderDrawLists()` I'm using.

Btw, when I draw text with `ImVec4(10, 10, 250, 255)` (using the drawlist or `ImGui::ColoredText`), I get something white (instead of blue). Am I missing something?

**Comment by ocornut** [comment]
DrawList takes colors as ImU32, you can pack one at compile-time with IM_COLOR() macro giving 0..255 values.

ColoredText() takes ImVec4() which are 0.0f-1.0f float. 
I think the ImGui:: side API taking colors should allow to take ImU32 as well, it is an overlook.

You can use the ImColor() helper to pass either integer or float, but it's a little confusing/awkward (not happy about this helper now).

**Comment by jdumas** [comment]
Ah ok. I was using `ImGui::GetColorU32(ImVec4(0, 0, 10, 255))`, and I thought it was taking color range between 0 and 255.

**Comment by ocornut** [comment]
The color helpers really need to be tidied up to be more consistent (may have to break some api in the cleanup).

Closing this as AFAIK original question was answered.

**Comment by jdumas** [comment]
Sure thanks!
