### ISSUE TITLE
Dragable Separator, or Horizontal Columns

### ISSUE THREAD

**Issue by DanielPower** [ocornut/imgui#1234]
I can easily create Columns with separators that can be dragged horizontally to resize the width. I'm having difficulty finding a way to do the same vertically. If I have three panes separated by Separators, is there any way to make a Separator draggable, or is there another way I can go about this?

**Comment by ocornut** [comment]
Hello Daniel,

There's no well integrated solution right now but you can look at this pattern I once experienced with:
https://github.com/ocornut/imgui/issues/319

Which is probably close to what you want.

The various docking solutions may also be of interest:
https://github.com/ocornut/imgui/issues/351



Sent from my fax machine

**Comment by DanielPower** [comment]
Thank you, I was able to come up with a perfect solution based on your suggestion in #319. Great library!

**Comment by rrizik** [comment]
@ocornut Curious if there is a solution to this now? Its been 7+ years, hoping something was implemented. Thanks!

Maybe my situation is a bit different but what I'm doing is drawing column names at hard coded locations. And then I do BeginChild and draw each of those columns at the same hard coded locations. But now I want small vertical bars in between the column names that I drag left or right to change drawing locations.

<img width="708" height="203" alt="Image" src="https://github.com/user-attachments/assets/3a6989d3-eeca-4b31-975f-ac831f7f5b3b" />

**Comment by ocornut** [comment]
> [@ocornut](https://github.com/ocornut) Curious if there is a solution to this now? Its been 7+ years, hoping something was implemented. Thanks!
> 
> Maybe my situation is a bit different but what I'm doing is drawing column names at hard coded locations. And then I do BeginChild and draw each of those columns at the same hard coded locations. But now I want small vertical bars in between the column names that I drag left or right to change drawing locations.
> 
> <img alt="Image" width="708" height="203" src="https://private-user-images.githubusercontent.com/3270002/484398988-3a6989d3-eeca-4b31-975f-ac831f7f5b3b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTY3OTYyMjEsIm5iZiI6MTc1Njc5NTkyMSwicGF0aCI6Ii8zMjcwMDAyLzQ4NDM5ODk4OC0zYTY5ODlkMy1lZWNhLTRiMzEtOTc1Zi1hYzgzMWY3ZjViM2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MDJUMDY1MjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM1ZmQxOWZhMjNhNzQ1NzFkMjgxMjM5Njg2MDFmZTM1NDkxYzhhZGJiNWMxMjM1ZTE0YWViZGM4YTU0OGRkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TifgY1BjkAjppyxqBuq-rYsfb2os5cJk4fAv5MFyss8">

This seems unusually odd. Why not using the Tables API which does that but better?

**Comment by rrizik** [comment]
@ocornut you are 100% right. I should have explored the demo UI before posting. Sorry about that. I think that will work fine. I saw that I can also have custom headers. Does that mean I can include multiple buttons in the headers, or even have the headers perform actions once I left click on them?

**Comment by ocornut** [comment]
> Does that mean I can include multiple buttons in the headers, or even have the headers perform actions once I left click on them?

Best to ask questions in new topics. But you can submit headers manually using `TableHeader()` (instead of calling `TableHeadersRow()` to populate the whole row with default headers). What action to do want performed when clicking a header? The default behavior is to alter the Sort settings.

**Comment by rrizik** [comment]
I have a sorting functions with up and down arrow buttons to sort ascending/descending. Figured I could get rid of those buttons and just have the click of the header sort in an alternating fashion. 

Separately if you look at the image I shared at the top right, you will see a [+] [x] [m] buttons to the right of the "Category" header. I want those to be separate buttons I can click that live inside the header itself. 

Yeah I'll create an new topic is this convo goes on any longer. Thanks!

**Comment by ocornut** [comment]
> I have a sorting functions with up and down arrow buttons to sort ascending/descending. Figured I could get rid of those buttons and just have the click of the header sort in an alternating fashion.

The tables API already provide a sorting interface. Please refer to existing demos and headers and open new issues if you have precise question.

For the `[+] [x] [m]` buttons simply don't call `TableHeader()` on the cell and submit normal buttons.
