### ISSUE TITLE
sdl-opengl2 visual studio

### ISSUE THREAD

**Issue by rivenblades** [ocornut/imgui#1235]
Could someone provide a VisualStudio project in the examples of imgui-master?
It currently has none, both in sdl-opengl2 and 3 folders.
I am havig trouble in compiling as i get:
imgui_impl_sdl.obj : error LNK2019: unresolved external symbol "struct ImGuiIO & __cdecl ImGui::GetIO(void)" (?GetIO@ImGui@@YAAEAUImGuiIO@@XZ) ....

**Comment by ocornut** [comment]
Please post your project/command-line and full error.
It looks like you probably forgot to include the three .cpp files in your project.
