### ISSUE TITLE
Drawing one widget over others widgets ?

### ISSUE THREAD

**Issue by itamago** [ocornut/imgui#1236]
Hello,

I may have a strange question which is not very easy to explain with a classic usecase :
 - I would like to draw several widgets **in a ChildWindow**, let's say **1 combo + 1 dragint**. 
 - And I would like to draw a **BIG text over the whole ChildWindow**, covering the combo and the dragint. 

How do you correctly reset the cursor position as if the combo and the dragint were not drawn ?
Are there some side-effects, like the combo+dragint will not contribute to extend the ChildWindow's size ?

Thanks for your help

**Comment by ocornut** [comment]
Hello Pacome,
I am not sure I understand your problem exactly.

- Would you like the Combo/DragInt to ignore inputs when the "Big Text" is displayed, or not?

I imagine what you are trying to do is display a big "DISABLED" thingie and block other inputs? Also see #211. Right now in your situation the simplest/dumb way to disable all inputs would be to draw a big InvisibleButton _FIRST_ in the child window that would steal the inputs from the subsequent widgets. That is, until we add widespread support for #211.

Currently ChildWindow never have automatic size so the contribution of the combo/dragint will only affect the scrollbar. Internally the variable that will lead to calculate the content size of a window is `window->DC.CursorMaxPos`, we more or less do `CursorPosMax = Max(CursorPos, CursorMaxPos)` in function such as ItemSize() (it's expressed in a different way in that function but that's the idea).

**Comment by itamago** [comment]
Exact, I would like to display something like "Disabled".
Understood, I will try that today. Thanks !!

**Comment by itamago** [comment]
For those who are interested in disabling the content of a ChildWindow, here is some code to be modified but giving a rough idea of how to do it :
```
ImVec2	g_disableChildCursorPos;
ImVec2	g_disableChildTotalSize;

void DisableChildBegin()
{
	g_disableChildCursorPos = ImGui::GetCurrentWindow()->DC.CursorPos;
	g_disableChildTotalSize = ImGui::GetContentRegionAvail();
	ImGui::InvisibleButton("disableID", g_disableChildTotalSize);
	ImGui::GetCurrentWindow()->DC.CursorPos = g_disableChildCursorPos;
}

void DisableChildEnd(const ImColor & colorBg, const ImColor & colorText, const char* text)
{
	ImGui::GetCurrentWindow()->DC.CursorPos = m_disableChildCursorPos;
	ImGui::PushStyleColor(ImGuiCol_Text, colorBg);
	ImGui::TextWithBackground(ImGuiAlign_Center | ImGuiAlign_VCenter, g_disableChildTotalSize, colorText, false, "%s", text);
	ImGui::PopStyleColor();
}
```

And an example of usage :

```
ImGui::BeginChild("Test", ImVec2(graphWidth, graphHeight), true);
DisableChildBegin();
ImGui::Combo(...);
ImGui::DragInt(...);
DisableChildEnd(colorBg, colorText, "Disabled");
ImGui::EndChild();
```

Implementation of ImGui::TextWithBackground is missing, but you can easily guess what it does :)
