### ISSUE TITLE
Reading mouse coordinates using ImGui::GetCursorPos() crashes.

### ISSUE THREAD

**Issue by edselmalasig** [ocornut/imgui#1238]
Thanks

**Comment by ocornut** [comment]
It's pretty much impossible for this function to crash unless you have changed the imgui context pointer. Could you post a callstack and/or reproduction?

**Comment by ocornut** [comment]
Sorry I got confused I thought you said GetMousePos(), which basically returns io.MousePos.

GetCursorPos() reads the position from the current window. Normally as soon as you call NewFrame() you should have a window pushed into the window stack.

1. Try to provide a callstack to confirm that the error is CurrentWindow being NULL.
2. Did you call NewFrame(), or are you calling GetCursorPos() after Render()?
3. Possibly if you added one End() too much, call it would pop the default window and leave you with no active window (interestingly we could potentially add an assert to detect this case)

**Comment by edselmalasig** [comment]
Yes you were right I should use io.mousepos.
