### ISSUE TITLE
How to get the actual values of MouseCursor Position when ImGui::Render() is enabled?

### ISSUE THREAD

**Issue by edselmalasig** [ocornut/imgui#1239]
How do I the actual values of Mouse Cursor Position when ImGui::Render is enabled? I get different values when Render is active. glfwGetMousePointer seems to report the correct values. but when I do I print it inside Mousebuttonfunc callback of glfw I get static values I get static non changing 114, -112 it seems that it is returning the values of the debug window of ImGui.

**Comment by ocornut** [comment]
There's no function called `glfwGetMousePointer` in GLFW afaik.

`ImGui::GetMousePos()` is basically returning `io.MousePos` and the backend code is basically calling `glfwGetCursorPos()` and copying the two floats to `io.MousePos`.

So any of those three things will give you the mouse position. I'm not sure what `ImGui::Render is enabled' means, but regardless, the mouse position isn't affected by rendering at all.

Please provide some code snippet.

**Comment by ocornut** [comment]
@edselmalasig Any update on this, have you solved your problem?
