### ISSUE TITLE
Double clicks register very awkwardly

### ISSUE THREAD

**Issue by berkay2578** [ocornut/imgui#1241]
Hey, this is similar to the _many_ issues that were created with the same gist: `ImgurIO.MouseDoubleClicked` either gets set on a random click (like on 3rd or 4th click) or doesn't get set at all.

My environment is set-up on D3D9 with a WndProc (parent process' original WndProc is overridden with `SetWindowLongPtr`). I'll keep the code as relevant and as short as possible. I should also mention that I'm using the `imgui_impl_dx9` from the Examples.

`BeginScene:`
```
if (!isImGuiInit) {
 ImGui_ImplDX9_Init(hWnd, pDevice); // (parent window handle, d3d9 device created by the parent process)
 isImGuiInit = true;
}

ImGui_ImplDX9_NewFrame();
```
`EndScene:`
```
// this is the code you posted in an older issue, double clicks register randomly as I've said above
ImGui::Begin("Bug #754");
static int counter_single = 0;
static int counter_double = 0;
if (ImGui::Selectable("Double click me", false, ImGuiSelectableFlags_AllowDoubleClick))
	if (ImGui::IsMouseDoubleClicked(0))
		counter_double++;
	else
		counter_single++;
ImGui::Text("counter_single = %d", counter_single);
ImGui::Text("counter_double = %d", counter_double);
ImGui::End();
```

`WndProc:`
```
if (isImGuiInit & ImGui_ImplDX9_WndProcHandler(hwnd, uMsg, wParam, lParam)) {
 if (io.WantCaptureMouse | io.WantTextInput) {
  // Block events from passing to the parent window
  return true;
 }
}
```
WndProc works as it should. The DeltaTime is also calculated with the default code: `io.DeltaTime = (float)(current_time - g_Time) / g_TicksPerSecond;`.

However, if I process the `LBUTTON` myself inside the `BeginScene` before calling `ImGui_ImplDX9_NewFrame`, with `LBUTTON` handler code removed from `ImGui_ImplDX9_WndProcHandler`, double clicks work perfectly; e.g., `io.MouseDown[0] = GetKeyState(VK_LBUTTON) < 0;`. Parent window doesn't have the `CS_DBLCLKS` attribute. Is this a compatibility issue because I'm hooking a window's WndProc or can this be related to ImGui's code? Because after changing `MouseDoubleClickTime` to `0.45f` the double clicks always registered at the 3rd click.

**Comment by ocornut** [comment]
Thanks for the detailed information.

It seems to work ok when I paste your repro block in the DX9 standalone example app, so something will your setup seems to be causing the problem. It looks like you've looked at the right place already. 

- For some reason you aren't receiving the right LBUTTON right in your event function and it is most likely the culprit. ImGui itself probably has nothing to do with it. Maybe print down the WM_LBUTTONDOWN/WM_LBUTTONUP event (or use a ImGuiTextBuffer for logging and display that in app)... if the events aren't received maybe `CS_DBLCLKS` is still active somehow?

- You can display ImGui::GetTime() if you want to double-check that your time values are correct. If your time is moving too time and/or the application framerate is too low it may be easy to miss a double-click.

- I am not sure you should be testing the return value of `ImGui_ImplDX9_WndProcHandler(hwnd, uMsg, wParam, lParam))` in your code above.

- If you use GetKeyState() you may miss more presses at low framerate. Also of interest: the GLFW examples uses an `g_MousePressed[]` array to always pass a DOWN to imgui is a DOWN+UP happens during the same update/event poll, which is a simple way to minimize missing inputs on low framerate. But somehow the DX examples don't do that. I should add it.

**Comment by berkay2578** [comment]
Thanks for replying. I've looked into the things you've said:

- I've double-checked and WndProc does capture `WM_LBUTTONDOWN`/`WM_LBUTTONDOWN` but doesn't capture `WM_LBUTTONDBLCLK` or even `WM_NCLBUTTONDBLCLK` as expected. The parent process uses ScaleForm so there is a chance some UI elements might have `CS_DBLCLKS`. I'll check if the main window style later gets overridden in the parent process.
- > I am not sure you should be testing the return value of ImGui_ImplDX9_WndProcHandler(hwnd, uMsg, wParam, lParam)) in your code above.

noted.
- I only used `GetKeyState()` for the sake of simplicity and also because it's inside impl_d3d9; e.g.,
