### ISSUE TITLE
ImGui /w Cinder - simple multiple window

### ISSUE THREAD

**Issue by Brianfog** [ocornut/imgui#1242]
Awesome library!

I have a question regarding multiple windows under Cinder. Lets say you have a main window with ImGui running. You set parameters (RGBs for example) in a imgui window and now you'd want to draw this color texture (rendered fbo) in a separate window (and drag this window to the other screen). You pass this TextureRef as an argument when creating a new window.

Creating a window itself is not a problem (BasicAppMultiWindow example), but when this window is created (it is visible), ImGui throws an exception here.

`inline    ImGuiWindow*  GetCurrentWindow()          { 
		ImGuiContext& g = *GImGui; 
		g.CurrentWindow->Accessed = true; 
		return g.CurrentWindow; 
	}`

Is creating a window this way fine and what else should be done to get it working? Thanks guys.

Edit: **moving imgui debug window from draw() (and placing it under update) solves the problem (having them in two different blocks was the problem), because no imgui cals between render and newFrame. How to change window content is the next objective.**

Edit 2: **It turns out this was the only issue. The solution then was to set userdata for main window (a simple flag for my problem) and separate functionalities for child windows.**

**Comment by ocornut** [comment]
Hello Brian,

Sorry I don't really understand your problem precisely nor your answers, everything is really vague in your message. 

If you want multiple ImGui contexts you need to make sure they all go through the NewFrame()/Render() loop, and make sure the ImGui atlas texture is uploaded to all the Graphics/OpenGL contexts that are using it. It's might also a question to raise with the Cinder wrapper, if the wrapper has facility to handle multiple windows.

> It turns out this was the only issue. The solution then was to set userdata

Is your problem solved?

**Comment by Brianfog** [comment]
Hi, the problem is solved, yes.

I found a solution to work with only one imgui context (main window only) and let the cinder wrapper handle other smaller windows. The problem I experienced was my bad (incorect newFrame/render loops) because cinder update and draw both had imgui components to draw. When a second window got created, these newframe/render loops gor corrupted.

Thank you, Omar.
