### ISSUE TITLE
GetInternalState functions change?

### ISSUE THREAD

**Issue by drillsar** [ocornut/imgui#1244]
I have the following code that I am trying to figure out how to change:

```
ImGuiDrawer::~ImGuiDrawer() {
  auto previous_state = ImGui::GetInternalState();
  ImGui::SetInternalState(internal_state_.data());
  ImGui::Shutdown();
  if (previous_state != internal_state_.data()) {
    ImGui::SetInternalState(previous_state);
  }

  current_drawer_ = nullptr;
}

void ImGuiDrawer::Initialize() {
  // Setup ImGui internal state.
  // This will give us state we can swap to the ImGui globals when in use.
  internal_state_.resize(ImGui::GetInternalStateSize());
  ImGui::SetInternalState(internal_state_.data(), true);
  current_drawer_ = this;
```

**Comment by thedmd** [comment]
As far as I know internal state was replaced by ImGuiContext some time ago. You should find more information on header. API is pretty straightforward.

**Comment by drillsar** [comment]
Yes I know I changed it to the following:

```
ImGuiDrawer::~ImGuiDrawer() {
  auto previous_state = ImGui::GetCurrentContext();
  ImGui::SetCurrentContext(internal_state_.data());
  ImGui::Shutdown();
  if (previous_state != internal_state_.data()) {
    ImGui::SetCurrentContext(previous_state);
  }

  current_drawer_ = nullptr;
}

void ImGuiDrawer::Initialize() {
  // Setup ImGui internal state.
  // This will give us state we can swap to the ImGui globals when in use.
  internal_state_.resize(ImGui::SetCurrentContext(ImGuiState* ctx)
  ImGui::SetCurrentContext(internal_state_.data(), true);
  current_drawer_ = this;
```
getting the following errors:

c:\users\tom\documents\xenia\src\xenia\ui\imgui_drawer.cc(38): error C2664: 'void ImGui::SetCurrentContext(ImGuiState *
)': cannot convert argument 1 from 'uint8_t *' to 'ImGuiState *' [C:\Users\Tom\Documents\xenia\build\xenia-ui.vcxproj]
  c:\users\tom\documents\xenia\src\xenia\ui\imgui_drawer.cc(38): note: Types pointed to are unrelated; conversion requi
  res reinterpret_cast, C-style cast or function-style cast
c:\users\tom\documents\xenia\src\xenia\ui\imgui_drawer.cc(40): error C2446: '!=': no conversion from 'uint8_t *' to 'Im
GuiState *' [C:\Users\Tom\Documents\xenia\build\xenia-ui.vcxproj]
  c:\users\tom\documents\xenia\src\xenia\ui\imgui_drawer.cc(40): note: Types pointed to are unrelated; conversion requi
  res reinterpret_cast, C-style cast or function-style cast
c:\users\tom\documents\xenia\src\xenia\ui\imgui_drawer.cc(50): error C2065: 'ctx': undeclared identifier [C:\Users\Tom\
Documents\xenia\build\xenia-ui.vcxproj]
c:\users\tom\documents\xenia\src\xenia\ui\imgui_drawer.cc(50): error C2275: 'ImGuiState': illegal use of this type as a
n expression [C:\Users\Tom\Documents\xenia\build\xenia-ui.vcxproj]
  c:\users\tom\documents\xenia\third_party\imgui\imgui.h(57): note: see declaration of 'ImGuiState'
c:\users\tom\documents\xenia\src\xenia\ui\imgui_drawer.cc(51): error C2059: syntax error: 'ImGui::SetCurrentContext' [C
:\Users\Tom\Documents\xenia\build\xenia-ui.vcxproj]

**Comment by thedmd** [comment]
Context API does not map directly to internal state API. Functions wasn't just renamed, they are different.

Change you made is not valid C++ code. Is appears you didn't have much grasp in programming. I don't think we can help you much in here, since this place is dedicated to issues with ImGui library not learning how to code.
