### ISSUE TITLE
Access Violation in ImGui::MemFree()

### ISSUE THREAD

**Issue by fuchstraumer** [ocornut/imgui#1248]
Been stuck on this bug for a few days now - I'll add as much info as I've been able to gather after giving some context. Hopefully this isn't something super silly or foolish.

I've got a simple little [Vulkan rendering abstraction](https://github.com/fuchstraumer/VulpesRender/tree/dacd37c5f7cd4381170522306ce582404f62df34) that I've added as a submodule to two personal projects and my work project: this system uses ImGui (also as a submodule) to provide GUI functionality and previously worked just fine when I was compiling the rendering subsystem alongside all of my projects (previously only used in one personal project) vs linking it as a static library as I have been trying to do.

I re-arranged things this weekend to get it working as a standalone library that I could compile to a static library and link simply into my projects. Now, thing's aren't working and always crash when trying to load the font data - even if I try to load the font data from a file (and I've checked to make the path is right). 

Callstack: 
![callstack](https://user-images.githubusercontent.com/11087615/28538724-1e26d924-7064-11e7-8bb9-79089f43e6f3.PNG)

Links to the code called earlier, from my rendering system:
https://github.com/fuchstraumer/VulpesRender/blob/dacd37c5f7cd4381170522306ce582404f62df34/src/gui/imguiWrapper.cpp#L165

If I check the call to ImVector::reserve, things seem fine and nothing stands out as critically incorrect in the locals window:
![locals](https://user-images.githubusercontent.com/11087615/28538801-5bda78ca-7064-11e7-945f-4a82330d73ab.PNG)

The exact exception thrown is:
![exception](https://user-images.githubusercontent.com/11087615/28539063-4199c546-7065-11e7-8fe7-1b693bd2bf9f.PNG)

and the locals window just displays ptr's value being `0x0000000000000000`

I wondered if this relates to how I link things together and compile my library: I'm linking as a static library, ignore all default libraries, but still link msvcrtd.lib (and specify to the librarian that we should link dependencies). So I disabled all of that and re-ran the program in question and still got the error shown. 

Sorry if this is something trivial - I've checked all throughout the issues section with a tremendous range of search parameters, and read up and down the FAQ and documentation and can't find anything to guide me. 

I'm really quite stuck and this is blocking progress on my personal and work projects: I was really hoping that the submodule + static library format would work out for me, but clearly something is going awry when doing this.

Let me know of any other information you'd like to see and I'll do my best to acquire it.

**Comment by fuchstraumer** [comment]
I made some further attempts at fixing/identifying this: I tried to override the MemFreeFn to just use `std::free`, but that didn't work. Then while looking at the values of the `ImGuiIO` struct I noticed something rather strange:
![override_free](https://user-images.githubusercontent.com/11087615/28545104-86c3898a-707a-11e7-8793-5c132aea8c4f.PNG)

Somehow, there was a residual copy of ImGui in my project files somewhere. This header included the `ClipboardUserData` pointer but the compiled files did not: compiled is v1.51, residual copy is 1.49. Removing that and recompiling with the most up-to-date version of ImGui seems to have fixed the issue.

Closing this as I've found the bug and feel a tiny bit silly, but at least it was something non-trivial.

**Comment by ocornut** [comment]
Take-away learning: don't copy and paste files :)

**Comment by fuchstraumer** [comment]
The bitter irony is that I had added imgui as a submodule in my renderer to avoid this very occurrence, which is why I also am trying to make renderer a submodule... but I didn't clean up my old copy-and-paste shenanigans and thus here I am! ;p
