### ISSUE TITLE
How I can place 2 element side by side?

### ISSUE THREAD

**Issue by czvpka** [ocornut/imgui#1249]
Hello, I've just implemented Color Picker from some issue i've found, now I'm wondering, how to place 2 elements side by side?
I want to place a list box on the left side of my color picker, how I can achieve this? Please, help me! 😞

**Comment by ocornut** [comment]
Use SameLine().
This is the second time in a row that you are asking a question easily answered by looking at the demo code. Please be more considerate next time and do more researchs.

**Comment by ocornut** [comment]
There are other ways to achieve basic layout, again please check the examples.
