### ISSUE TITLE
Making text draw as a rainbow with ImColor

### ISSUE THREAD

**Issue by ViralAphinity** [ocornut/imgui#1250]
I'm attempting to cause some text to draw as a rainbow, is there a way to do that?

`Draw::ImDrawText(ImVec2(4.f, 4.f), ImColor(210, 95, 0, 255), XORSTR("Rainbow!"), NULL, 0.0f, NULL, ImFontFlags_Shadow);`

**Comment by ocornut** [comment]
Make your own text draw function!

**Comment by ViralAphinity** [comment]
I'm really bad at C++ though, this is for a friend who can't figure it out, and I certainly couldn't either

**Comment by ocornut** [comment]
Unfortunately this isn't really a question for this place then, maybe ask on a general C++ forum about way to copy chunk of text rendering functions and adapt it. Also see #902 for ideas/reference.
