### ISSUE TITLE
Moving Popup windows?

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#1252]
I just came to the realization that there's no reason to prevent most popups from being moved.
In `BeginPopupEx` if we just remove the `ImGuiWindowFlags_NoMove` flag, popups can be moved.

Does anyone sees in their codebase, a side-effect, potential breakage or reason to not just remove this flag?

Thinking of cases such as:
![ref](https://user-images.githubusercontent.com/8225057/28490663-4137c232-6f12-11e7-8201-747a0fdba63c.PNG)

The popup auto position but no reason to lock its position.

When the popup is filled with menu items and auto-sized there's typically little room to grab and move them, but I don't think it is something that people would really care about. Also, because child menu are positioned by their parent, you still cannot move a child menu (which also is to be expected).

**Comment by skrrtskrrt** [comment]
hey can I get the code for the color customizer thing to pop up from clicking the color icon

**Comment by ocornut** [comment]
This is being worked on in the color-picker branch, also see #346 discussion. It should be merged in Master within the week.

**Comment by skrrtskrrt** [comment]
Oh cool I'd just like the small preview color square to be beside something that you color and when you click it the big color picker appears under it

**Comment by skrrtskrrt** [comment]
http://i.imgur.com/dXkumTf.png basically this

**Comment by ocornut** [comment]
I couldn't see an issue with removing the `ImGuiWindowFlags_NoMove` flags from popup, so committed it.
