### ISSUE TITLE
ImageButton disable border

### ISSUE THREAD

**Issue by raresica1234** [ocornut/imgui#1254]
Hello everybody, I have a strange issue, I don't know how to disable the border on an ImageButton:

![Example](https://puu.sh/wXb8y/d77d3bc323.png)
Thanks!

**Comment by colesnicov** [comment]
Hello, sorry for bad language.

If You can play with `frame_padding` argument of `ImageButton` function or with border color style eg. `PushStyleColor(ImGuiCol_Border, ...) `?

**Comment by ocornut** [comment]
As a general tip, use your programmer IDE feature to jump to function declarations and definitions where you are likely to find comments about them.

```
// frame_padding < 0: uses FramePadding from style (default)
// frame_padding = 0: no framing
// frame_padding > 0: set framing size
// The color used are the button colors.
bool ImGui::ImageButton(ImTextureID user_texture_id, const ImVec2& size, const ImVec2& uv0, const ImVec2& uv1, int frame_padding, const ImVec4& bg_col, const ImVec4& tint_col)
```

PS: Consider merging in an icon font into the default font if you are going to use icons, this makes things much simpler and natural. Read extra_fonts/README.txt about it.
