### ISSUE TITLE
Setting an icon font for buttons

### ISSUE THREAD

**Issue by ViralAphinity** [ocornut/imgui#1255]
I'm not certain on how this is done, and I believe asking here might be more direct.
I need to assign a .ttf font I have to a set of buttons in my menu, but I do not know where and what to modify in the GetStyle function.

`
Settings::UI::Windows::Main::open = true;
		ImVec2 temp = ImGui::GetWindowSize();
		Settings::UI::Windows::Main::sizeX = (int)temp.x;
		Settings::UI::Windows::Main::sizeY = (int)temp.y;
		temp = ImGui::GetWindowPos();
		Settings::UI::Windows::Main::posX = (int)temp.x;
		Settings::UI::Windows::Main::posY = (int)temp.y;
		const char* tabs[] = {
				"1",
				"2",
				"3",
				"4",
		};

		for (int i = 0; i < IM_ARRAYSIZE(tabs); i++)
		{
			int distance = i == page ? 0 : i > page ? i - page : page - i;

			ImGui::GetStyle().Colors[ImGuiCol_Button] = ImVec4(
					Settings::UI::mainColor.Color().Value.x - (distance * 0.035f),
					Settings::UI::mainColor.Color().Value.y - (distance * 0.035f),
					Settings::UI::mainColor.Color().Value.z - (distance * 0.035f),
					Settings::UI::mainColor.Color().Value.w
			);

			if (ImGui::Button(tabs[i], ImVec2(ImGui::GetWindowSize().x / IM_ARRAYSIZE(tabs) - 9, 100)))
				page = i;

			ImGui::GetStyle().Colors[ImGuiCol_Button] = Settings::UI::accentColor.Color();

			if (i < IM_ARRAYSIZE(tabs) - 1)
			{
				//ImGui::Columns(1);				
				ImGui::SameLine();				
			}

		}
`

The font sets the numbers in the const char* tabs[] bit as icons.

**Comment by ocornut** [comment]
You can use `ImGui::PushFont` / `PopFont` to change the font.
To load extra fonts check the example code, documentation in imgui.cpp and extra_fonts/ folder.
