### ISSUE TITLE
Item won't take all width

### ISSUE THREAD

**Issue by czvpka** [ocornut/imgui#1256]
Hello, I have following code:
`if (ImGui::BeginChild("dsfasfasfas", { 220, 0 }, true, ImGuiWindowFlags_NoResize)) {
	const char* listbox_items[] = { "Apple", "Banana", "Cherry", "Kiwi", "Mangdsadsdasso", "Orange", "Pineapple", "Strawberry", "Watermelon" };
	static int listbox_item_current = -1;
	ImGui::ListBox("", &listbox_item_current, listbox_items, 9, 18);
	ImGui::PushItemWidth(-1);
}
ImGui::EndChild();`

But the listbox won't fill the child, like in screenshot: https://scr.hu/p0k3R4
Anyone can help me? :/

**Comment by ocornut** [comment]
Call PushItemWidth() before ListBox()..

**Comment by itamago** [comment]
You need to retrieve the available height, and give it as a parameter :
```
const float availHeight = ImGui::GetContentRegionAvail().y;
ImGui::Button("full size", ImVec2(20,availHeight));
```
It would work for any widget for which you provide the size.
Unfortunately, the height of ListBox is automatically calculated according to the number of visible items. If you really want to create a ListBox occupying the whole height, then you need to create your own widget I guess.

**Comment by czvpka** [comment]
@itamago Is it possible in case of listbox? I don't see size parameter :/

**Comment by czvpka** [comment]
Okay, I resolved it by adding new `bool` parameter to ListBox, and if it's set to `true` then in ListboxHeader instead of calculating height based on `height in items` I define `size.y` by `ImGui::GetContentRegionAvail().y` :smile: Thanks everyone for help!

**Comment by ocornut** [comment]
`ListBox()` only has `height_in_items` maybe it was an API mistake and I should change it to a regular size. But you can also call ListBoxHeader()/ListBoxFooter() yourself.
