### ISSUE TITLE
Fading

### ISSUE THREAD

**Issue by bighaxor** [ocornut/imgui#1257]
Not an issue but I was wondering if you can make the ImGUI menu fade in / out on toggle if so how?

**Comment by ocornut** [comment]
No you cannot.

**Comment by ratchetfreak** [comment]
Fading in can be hacked in if you know what you are doing with alpha and a frame counter and a changed set of shaders but it's not going to be pretty.

fading out is much harder due to the way the system is setup.

**Comment by ocornut** [comment]
As ratchetfreak suggested, fade out would be quite difficult with the architecture of the library. 
Either way that sort of eye candy isn't on the immediate road map.

Note that you can perfectly animate/fade stuff yourself by using the ImDrawList api, but doing it on popups or windows and expecting fade-out to work is not planned.
