### ISSUE TITLE
Font not Visible on Custom Implementation without Dependency

### ISSUE THREAD

**Issue by Remi123** [ocornut/imgui#1258]
Hi, 
First I want to let you know that I really like using IMGUI my projects. 

This time around, I cannot use GLFW and was looking for a custom implementation without dependency. I know that you don't support this kind of implementation, but i saw that you refer to [this unmerged branch by @Pagghiu](https://github.com/Pagghiu/imgui/blob/f82b0d8c728fda72c877634b82c1a9784e026ce4/examples/opengl_example/main_without_deps.cpp) as the reference for this. My first try is to copy part of the code into mine to get a result

After some issue with implementing in my architecture, i was able to saw a result. Unfortunately, the only missing piece is the Font as you can see in the image below 👍 
![imgui](https://user-images.githubusercontent.com/16803994/28882654-e0d30c7e-7779-11e7-8e52-fc8957c79999.jpg)

I'm so close, but after two days of searching and trying, I must call for help. I'm not asking to fix my code, I'm looking toward some advice on what I shall look into to fix it since my code is almost the same as the the example.

I'm suspecting that my io.Font.TexID is not the good one, since the example is 0x01 but mine is 0x00000000cccccccc for reasons I'm not able to find.

Some of my code

RENDER FUNCTION OF THE IMGUI
`void ImImpl_RenderDrawLists(ImDrawData* draw_data)
{
Same as the example but with glUseProgram(0) uncommented
}`

INITIMGUI 
`
bool InitImGui(float display_width, float display_height)
{
	ImGuiIO& io = ImGui::GetIO();
	io.DisplaySize = ImVec2(display_width, display_height);
	io.DeltaTime = 1.0f / 60.0f;
	io.KeyMap[ImGuiKey_Tab] = VK_TAB;	

	io.RenderDrawListsFn = ImImpl_RenderDrawLists;

	glEnable(GL_TEXTURE_2D);
	io.Fonts->AddFontDefault();

	unsigned char* pixels;
	int width, height;
	io.Fonts->GetTexDataAsAlpha8(&pixels, &width, &height);

	GLuint tex_id;
	GLint last_texture;
	//glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture);
	glGenTextures(1, &tex_id);
	glBindTexture(GL_TEXTURE_2D, tex_id);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
	glTexImage2D(GL_TEXTURE_2D, 0, GL_ALPHA, width, height, 0, GL_ALPHA, GL_UNSIGNED_BYTE, pixels);
	// Store our identifier
	io.Fonts->TexID = (void *)(intptr_t)tex_id;	

	//glBindTexture(GL_TEXTURE_2D, last_texture);	
	return true;
}`

IN MY RENDER LOOP
`{
	wglMakeCurrent(m_hdc, m_hglrc);
	
	glClearColor(0.1f, 0.45f, 0.75f, 1.0f);//BackGround color
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

	glEnable(GL_DEPTH_TEST);
	glEnable(GL_TEXTURE_2D);
	glDepthFunc(GL_LEQUAL);
	glClearDepth(1.0);	

	ImGuiIO& io = ImGui::GetIO();
	//glLoadIdentity();
	ImGui::NewFrame();	
	bool show_another_window = true;
	static float f;
	ImGui::Begin("Another Window", &show_another_window, ImVec2(600, 500));
	ImGui::SetCursorPos(ImVec2(25.0f, 25.0f));
	ImGui::Text("Hello, world!");
	ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
	ImGui::End();

	ImGui::Render();
	SwapBuffers(m_hdc);
}`

Thank you again and any help is appreciated,

Remi

**Comment by Remi123** [comment]
Quick Update : I've found that the @Pagghiu  version of the code was using function like glMatrixMode and those are deprecated in OpenGL4.0 and my program isn't compatible with it . I'm currently in the process of removing GLFW function in the  imgui_impl_glfw_gl3 files and replace them manually with the attributes of my WindowGL class

I'll keep posting update

**Comment by ocornut** [comment]
The correct texture isn't bound - or probably no texture is bound:

> I'm suspecting that my io.Font.TexID is not the good one, since the example is 0x01 but mine is 0x00000000cccccccc for reasons I'm not able to find.

Well it's pretty much your issue. 0xCCCCCCCCC in visual studio debug builds means that the value was not initialized (the debug allocator memset everything with 0xCCCCCCCC before giving you the memory.).

Can you check the value of `tex_id` in a debugger when you do this?
```
// Store our identifier
io.Fonts->TexID = (void *)(intptr_t)tex_id;
```

Do you have custom DLL in place, or anything making it possible for different instances of imgui to be loaded/unloaded/initialized?

Your code above looks right so I think there's something you are omitting.

**Comment by ocornut** [comment]
@Remi123 Closing this issue now. Note that the examples have recently been refactored, making it easier and more natural than before to integrate win32 + opengl bindings without relying on GLFW.

**Comment by Impulse21** [comment]
I am currently experiencing this same issue with DX12, I am setting the textureID properly, however, the fonts appear the same as above. Not sure what else could be the issue. Is anyone help to assist with this?
`	ImGuiIO& io = ImGui::GetIO();
	io.Fonts->AddFontDefault();

	unsigned char* pixels;
	int width, height;

	io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height);
	this->m_texture.Create(width, height, DXGI_FORMAT_R8G8B8A8_UNORM, pixels);

	// io.Fonts->GetTexDataAsAlpha8(&pixels, &width, &height);
	// this->m_texture.Create(width, height, DXGI_FORMAT_R8_UINT, pixels);

	static_assert(sizeof(ImTextureID) >= sizeof(this->m_texture.GetSRV().ptr), "Can't pack descriptor handle into TexID, 32-bit not supported yet.");
	io.Fonts->TexID = (ImTextureID)this->m_texture.GetSRV().ptr;`

**Comment by PyotrRomanov** [comment]
@Impulse21 
Have you by chance figured out what the issue was? My texture isn't coming out right after passing the font file to IMGUI, and the result is the same as yours.

**Comment by Impulse21** [comment]
@PyotrRomanov  sorry, forgot to update this. Yes, I did - the issue was that my blend state wasn't set up correctly. I ended up copying the one defined in the dx12 samples. Hope that helps😊
