### ISSUE TITLE
Help Text for ImGuiIO unclear

### ISSUE THREAD

**Issue by pdJeeves** [ocornut/imgui#1262]
In the help text for ImGuiIO it may mean that I should store the inputs received that frame, then after calling NewFrame() check the WantCaptureMouse and similar fields to determine if I should forward them to the program.  

Or it means to query the fields before filling the input, not after calling new frame, and forwarding them immediately if not used. It probably doesn't matter given the short time between frames, but which is the better interpretation?

**Comment by ocornut** [comment]
The better interpretation is the first one. As the `WantCaptureMouse` flag is updated by `NewFrame`.
The FAQ says:

```
 Q: How can I tell when ImGui wants my mouse/keyboard inputs and when I can pass them to my application?
 A: You can read the 'io.WantCaptureXXX' flags in the ImGuiIO structure. Preferably read them after calling ImGui::NewFrame() to avoid those flags lagging by one frame, but either should be fine.
```

But as you pointed out it's not a big issues if you do the second, it will only delay the toggle of WantCaptureMouse which is a hardly noticeable thing.

I have added some clarification to the both parts of the document which refers to those flags, so it should be clearer now (see commit).
