### ISSUE TITLE
GetClipboardText breaks copy/paste

### ISSUE THREAD

**Issue by menohack** [ocornut/imgui#1264]
GetClipboardTextFn_DefaultImpl and SetClipboardTextFn_DefaultImpl are missing a CloseClipboard() call when they return early. OpenClipboard on success requires a matching call to CloseClipboard, otherwise the program prevents copy and paste from working in windows.

**Comment by ocornut** [comment]
Oh wow, nice find. I've seen mostly using the GLFW sample and my own apps with their own handlers, so this bug in the default win32 handler slipped. Fixed, thanks!

**Comment by ocornut** [comment]
FYI now also fixed SetClipboardTextFn, it was reported by @menohack but I brain-farted and only fixed the GetClipoardTextFn back then.
https://github.com/ocornut/imgui/commit/70cb427469de3da6e0d0db8b806c33b2899f08bf
