### ISSUE TITLE
Confusion reading demo code

### ISSUE THREAD

**Issue by traw** [ocornut/imgui#1267]
```
static bool a=false;
if (ImGui::Button("Button")) { printf("Clicked\n"); a ^= 1; }
if (a)
  {
    ImGui::SameLine();
    ImGui::Text("Thanks for clicking me!");
   }
```
Above snippet taken from `Imgui_demo.cpp`. Snippet uses `static bool a` to display text on screen, can't we directly put second `if` condition code inside first condition?   
Also, why `bool` variable `a` is declared  `static`?

**Comment by ocornut** [comment]
We use `static` variables inside function in the demo solely to make the demo code compact with everything in the same location (not using classes/struct or moving data outside the function code). It means the variable will persist across calls, aka it is pretty much like a global but scoped inside the function.

`a ^= 1;` invert the value of the boolean to false becomes true and vice-versa. Same as writing `a = !a`, I should probably change it to `a = !a` as it is easier to understand. It wouldn't be the same thing to put them in the same.

**Comment by traw** [comment]
Ok. Great 
I thought it might be some design issue.

**Comment by paulsapps** [comment]
Agree that `a = !a` is much clearer in this instance.

**Comment by ocornut** [comment]
I added a comment and tweaked that part of the code now.
