### ISSUE TITLE
Compile time and runtime version querying

### ISSUE THREAD

**Issue by Roflraging** [ocornut/imgui#127]
A lot of libraries provide a compile time version and runtime version checking.  Would be nice to have this so I can just check the version that is being run by clients inside our game like this:

![version](https://cloud.githubusercontent.com/assets/3121968/6114675/6bbbe6dc-b065-11e4-9a73-edd14ef4f7ed.png)

Not really a huge issue by any means, since usually we propagate the correct version to our dev machines pretty quick since we just compile ImGui directly in our build process every time, but does make tracking down any GUI bugs to a particular version easier.

-Dale Kim

**Comment by ocornut** [comment]
How do other libraries label their versions in-between two releases? (say between 2.0.3 and 2.0.4) ? 
The way I currently do it is that I edit the header of imgui.cpp imgui.h with "2.0.4 wip" (2.0.4 being the next target). Effectively you'll probably mostly see those versions if you are on trunk.

**Comment by Roflraging** [comment]
Most libraries don't really do that, as far as I know; they usually change the version numbers when they make a new official release.

I'm not sure exactly what your version number scheme is, but just as an example if you are doing X.YZ where X is major, Y is minor, and Z is an update version, then maybe have a W which simply marks it as WIP?

**Comment by ocornut** [comment]
Btw the dual versioning only really makes sense if you are using precompiled binaries, which I don't expect people would do with ImGui. :)

**Comment by Roflraging** [comment]
Right, which is awesome, by the way.  I used to think for a very long time that it was better for all libraries to be separately compiled ahead of time and loaded in later as a shared object/dll but my experience has proved otherwise.

Honestly, I think it would be enough in ImGui to just provide a printable string...

Lots of other libraries do all sorts of shenanigans where you have to grab individual bytes in a particular way out of a uint32.  I only ever care about reading the version and printing it out as a readable string!

In which case, I bet you could just do something like:

```
#define IMGUI_VERSION    "2.0.4 WIP"
```

**Comment by ocornut** [comment]
Will do !
