### ISSUE TITLE
Please add API to load/decompress data generated with binary_to_compressed_c

### ISSUE THREAD

**Issue by space2** [ocornut/imgui#1270]
The binary_to_compressed_c tools is very nice to easy add data to the application, however currently it works for fonts only.
I want to use it to load images as well, however I don't want to duplicate the whole stb_decompress code. Would it be possible to add a small function to decompress these data buffers? For example, for now, I added this at the and of imgui_draw.cpp:

unsigned char * DecompressData(const void* compressed_data, int compressed_size)
{
    const unsigned int buf_decompressed_size = stb_decompress_length((unsigned char*)compressed_data);
    unsigned char* buf_decompressed_data = (unsigned char *)malloc(buf_decompressed_size);
    stb_decompress(buf_decompressed_data, (unsigned char*)compressed_data, (unsigned int)compressed_size);
    return buf_decompressed_data;
}

**Comment by ocornut** [comment]
Hello,

Won't add, sorry. imgui is not a general framework, and new API needs to be supported for a long time so it's not directly useful for the general use case of imgui it's not worth it.
There are much better ways to compress images that using this technique, and if for some reason that's really what you want you can trivially copy the `stb_decompress()` function into your own code.
Or you can patch your copy of imgui_draw.cpp to remove the `static` before `stb_decompress` and then call it from your code.

-Omar
