### ISSUE TITLE
GetScrollMaxX/Y return incorrect value

### ISSUE THREAD

**Issue by degracode** [ocornut/imgui#1271]
They both subtract the scrollbar Size, when it should add instead:
`return window->SizeContents.x - window->SizeFull.x + window->ScrollbarSizes.x;`

If you call SetScrollX(GetScrollMaxX()), then the scrollbar will go almost to the end, but not quite.

If you drag a scrollbar all the way to its extent, you'll get the max value, eg 35. However GetScrollMaxX will return 3 basedon this maths:

window->SizeContents.x - window->SizeFull.x = 19
window->ScrollbarSizes.x = 16
19-16 = 3, but 19+16 = 35.

**Comment by ocornut** [comment]
You are correct, fixed now. It wasn't extremely obvious because it requires the other scrollbar to notice. I also updated the demo to display more stuff and made the `Begin` code use those functions as it should have.

**Comment by ocornut** [comment]
Thanks :)

**Comment by degracode** [comment]
Ah, thanks! I forgot to mention that I had both scroll-bars turned on.

**Comment by ocornut** [comment]
Closing. There's another bug (not directly related) right now when Horizontal Scrollbar is enabled and straddle the limit of a disabled Vertical Scrollbar it doesn't automatically enable the Vertical Scrollbar.

(PS: I'd be nice if you have screenshots from your game to share in the Gallery threads)
