### ISSUE TITLE
How to get the integer value of the colors?

### ISSUE THREAD

**Issue by chargerfox** [ocornut/imgui#1272]
Hi from Argentina. ImGui is the best but i have a problem.

I'm starting to use imgui and I need to get the whole value of the colors.
I have this code:

```
Static float ESPColor [3] = {0,0,0};
ImGui :: ColorEdit3 ("Color", ESPColor);
#define VisibleColor D3DCOLOR_ARGB (255, ESPColor [0], ESPColor [1], ESPColor [2])
```

Here I need integer values from 0 to 255 but ColorEdit has floating values from 0.0f to 1.0f.
Can you convert and get these values easily without having to do a mathematical conversion?
Thank you very much and sorry for my English.

**Comment by ocornut** [comment]
Have you looked for the word "color" in imgui.h ?

Basically you only need to take your float value, clamp between 0.0 and 1.0, multiply it by 255 and cast to integer.

See also
`ImU32 ColorConvertFloat4ToU32(const ImVec4& in);`

**Comment by chargerfox** [comment]
Yes, is very stupid the question and very simple the answer. Im sorry. i solved this and work fine.

```
static float CrossHairColor[3] = { 0,0,0 };
ImGui::ColorPicker3("", fMBMESPNameColor, ImGuiColorEditFlags_NoOptions | ImGuiColorEditFlags_NoInputs);
pDevice->Clear(1, &rec2, D3DCLEAR_TARGET, D3DCOLOR_ARGB(255, int (CrossHairColor[0] * 255), int(CrossHairColor[1] * 255), int(CrossHairColor[2] * 255)), 0, 0); //Red
```

Thanks. Imgui is super congratulations.
