### ISSUE TITLE
Mega screenshots

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#1273]
I should be posting this to the Gallery Thread #1269 but the files here are rather big and I don't want to spam the screen.

Today I upgraded my Screenshooting tool to create mega-capture of very big windows by moving the window and stitching multiple capture.

https://github.com/ocornut/imgui/wiki/screenshot_tool
![screenshot_maker](https://user-images.githubusercontent.com/8225057/29072866-19b30e5c-7c7c-11e7-9a5e-6b58ff565ed9.PNG)

It's mostly for fun right now. 
Perhaps I can use something like that to generate shots for the main github page, and either way more automation is always useful (e.g. for #435.). Also interesting because at a glance you can see some of the issues that a theme may have (the "white" theme below has issues).

Results:

![out_dark](https://user-images.githubusercontent.com/8225057/29072799-d3d9f2e2-7c7b-11e7-938d-471cdc796c06.png)

![out_cinder](https://user-images.githubusercontent.com/8225057/29072770-aef614e2-7c7b-11e7-8861-212c2c416439.png)

![out_white](https://user-images.githubusercontent.com/8225057/29073027-a7d6d65a-7c7c-11e7-9ab5-d868570d40b2.png)

**Comment by rokups** [comment]
\<offtopic>
Were these styles shared anywhere? They look gorgeous and i would love to get my hands on them.
\</offtopic>

**Comment by ocornut** [comment]
I'm working on making those available in the default imgui but ran into some tangential problems (e.g: bordering). You can grab many of them here: https://github.com/ocornut/imgui/issues/707 or click on the `Style` label here.

**Comment by flamendless** [comment]
Im not sure if here is the right place to ask, but how about a graph where i can plot points and make lines? Just like this 
![image](https://user-images.githubusercontent.com/17418737/48904175-89d9eb80-ee98-11e8-9b82-80cfa45b0bf7.png)

**Comment by ocornut** [comment]
Closing this old thread.
FYI the "mega / stitched" screenshot can now be achieve with the Dear ImGui Capture Tool inside Test Engine.
Our Test Suite has those two examples:

```cpp
// ## Capture all tables demo
t = IM_REGISTER_TEST(e, "capture", "capture_table_demo");
t->TestFunc = [](ImGuiTestContext* ctx)
{
    ctx->SetRef("Dear ImGui Demo");
    ctx->ItemOpen("Tables & Columns");
    ctx->ItemClick("Tables/Open all");
    ctx->ItemOpenAll("Tables/Advanced/Options", 1);
    ctx->ItemOpen("Tables/Tree view/**/Root");
    ctx->ItemInputValue("Tables/Advanced/Options/Other:/items_count", 50000); // Fancy

    ctx->CaptureScreenshotWindow("", ImGuiCaptureFlags_StitchAll | ImGuiCaptureFlags_HideMouseCursor);

    ctx->ItemClick("Tables/Close all");
};

// ## Capture all tables demo
t = IM_REGISTER_TEST(e, "capture", "capture_implot_demo");
t->GuiFunc = [](ImGuiTestContext* ctx)
{
    ImPlot::ShowDemoWindow();
};
t->TestFunc = [](ImGuiTestContext* ctx)
{
    ctx->SetRef("ImPlot Demo");
    ctx->ItemOpenAll("");
    ctx->CaptureScreenshotWindow("ImPlot Demo", ImGuiCaptureFlags_StitchAll | ImGuiCaptureFlags_HideMouseCursor);
};
```

Attached for fun the implot demo:
![capture_implot_demo_0000](https://user-images.githubusercontent.com/8225057/211871506-76338874-e431-4e06-9a72-de650201fbc1.png)
