### ISSUE TITLE
EditColor4 sliders throwing errors?

### ISSUE THREAD

**Issue by officialabyssal** [ocornut/imgui#1279]
I have a little test to try the EditColor sliders but for some reason it's giving me compile errors in Visual Studio such as: identifier 'style' is undefined, 'style': undeclared identifier, and: left of '.Colors' must have class/struct/union.

My code is here:
`ImGui::PushItemWidth(100);
ImGui::ColorEditMode(ImGuiColorEditMode_RGB);
ImGuiEx::ColorEdit4("Text Color", &style.Colors[ImGuiCol_Text], false);
ImGui::PopItemWidth();`

**Comment by ocornut** [comment]
You have no variable called 'style' in scope.
eg `ImGuiStyle& style = ImGui::GetStyle()`
This is a generic C++ question and not really related to imgui development, please ask those on generic C++ forums next time!
