### ISSUE TITLE
Window title text being clipped

### ISSUE THREAD

**Issue by Roflraging** [ocornut/imgui#128]
Looks like the clipping changes introduced a minor change in the way the text is being clipped, specifically for the window titles:

ImGui 1.30:
![screenshot-brigador 566a6275336023426f54bdea5dd849b2c63f39f1 14 06 12 feb 9 2015 release-assertions -1](https://cloud.githubusercontent.com/assets/3121968/6114852/9cd6f08a-b066-11e4-81b4-44257aa9a955.png)

ImGui 1.31:
![screenshot-brigador 0cc18721f059efafe564ba67e8cf509c69dddfce 14 15 14 feb 9 2015 release-assertions](https://cloud.githubusercontent.com/assets/3121968/6114857/a7fe86bc-b066-11e4-9875-ca9736c0b5a9.png)

Characters where there are descenders like g, y, p, etc are clipped at the bottom in 1.31 where in 1.30 they are not.  Also notice that this only occurs on the window titles, elsewhere there appears to be no change.

-Dale Kim

**Comment by ocornut** [comment]
Oops, fixed. 
I know of the bug with large int, it's on my todo list (the reason is that there is a int->float->int happening to reduce code duplication, but I can solve that in another way).
