### ISSUE TITLE
Font loading screen

### ISSUE THREAD

**Issue by Garry050** [ocornut/imgui#1280]
my GUI are loading TTF font to support Japanese and Chinese. but It temporarily freezes to load the font when drawing the GUI for the first time
I'd like to display an overlay loading fonts. I want to display an overlay "loading fonts"
I tried to refer to the code of Splash part of Reshade and tried to make it, but I can not do it :(

sorry my bad english

**Comment by ocornut** [comment]
> It temporarily freezes to load the font when drawing the GUI for the first time

Loading the Font isn't the same thing as Drawing the GUI. Drawing the GUI never freeze.

The font loading times are split between:
a) The file system opening and reading of the file (either your own fopen/fread or `AddFontFromFileTTF`).
b) The call to `ImFontAtlas::Build()` (which is called by `GetTexDataAsAlpha8/GetTexDataAsRGBA32`)

Few solutions
1) You can move both in a thread if you wish, as long as ImGui isn't accessed from another thread.

2) You can use `ImFontAtlas::GlyphRangesBuilder` type to help building a range based on your application/game text data, to reduce the time of b) and texture size.

3) If you want to display a Loading Fonts screen, just display it before loading the fonts... use an image for example. If you want to display it using ImGui font rendering, first load/build a minimal font set, render the screen, then loading the other fonts and call Build again.

For further details please discuss it on a general game development forum.
