### ISSUE TITLE
How to get the exact mouse coordinates relative to an image drawn on a window ?

### ISSUE THREAD

**Issue by dhiahassen** [ocornut/imgui#1281]
Now i am having this game engine 
![engine](https://user-images.githubusercontent.com/17810558/29284427-ff5f4a80-812a-11e7-8b37-495a8de75e1d.JPG)
, the black portion with the green circle is the engine own frame buffer object , ( sdl_gpu target 'GPU_Target*'t ) , i passed the opengl handle to imgui to render that image using Imgui::Image() , i am using 'sdl_opengl3_example' .
now i want the embedded game engine to recieve input from that black portion of the screen via imgui , i get the click event i convert it relative to that portion, i mean i apply a transform on the coordinates then i send that event to my embedded game engine . the problem is that the calculation is slightly wrong , it goes this way : 

```if(ImGui::BeginDock("Engine",nullptr,ImGuiWindowFlags_HorizontalScrollbar|ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoCollapse)){
                    /// tell the inbox if it should receive input
                    EngineInbox.SetInputOn(ImGui::GetWindowIsFocused());
                    /// move the draw cursor to the top left corner of the window
                    ImGui::SetCursorPos(ImVec2(0,0));
                    /// get window draw region
                    ImVec2    win_region = ImGui::GetContentRegionAvail();
                    /// send the region to engine inbox
                    EngineInbox.SetRenderingWindowSize(win_region.x,win_region.y);
                    /// tell the engine the current draw position
                    ImVec2 w_pos = ImGui::GetCursorPos() ,c_pos = ImGui::GetWindowPos();
                    EngineInbox.SetRenderingPosition(w_pos.x+c_pos.x,w_pos.y+c_pos.y);
                    ImGui::Image((ImTextureID)GPU_GetImageHandle(engine_screen->image),ImVec2(engine_screen->w,engine_screen->h));
                    /// tell the engine the current view potion
                    ImVec2 uv1,uv2; /// top left and button down range ( 0 ... 1) like uv coords
                    uv1.x = abs(ImGui::GetWindowContentRegionMin().x)/engine_screen->w;
                    uv1.y = abs(ImGui::GetWindowContentRegionMin().y)/engine_screen->h;
                    uv2.x = ImGui::GetContentRegionAvail().x / engine_screen->w +uv1.x;
                    EngineInbox.SetViewPortion(uv1.x,uv1.y,uv2.x,uv2.y);
}

                    ImGui::EndDock();
}```


then the engine sandbox does this : 
```
       /// if motion event
       if (update_frame->event->GetType() == UmbEventType::POINTER_MOVE)
       {
           UmbPointerMoveEvent * event = dynamic_cast<UmbPointerMoveEvent*>(update_frame->event);
           if (event != nullptr)
           {
              int mx,my;
              float fmx,fmy;
              event->GetCoord(mx,my);
              if (mx>=rendering_x && my>=rendering_y && mx<=rendering_x+rendering_win_w && my<=rendering_y+rendering_win_h) /// if click within inbox
              {
                    if (is_mouse_over == false)
                    {
                        SDL_ShowCursor(0);
                        is_mouse_over = true;
                    }
                    fmx = (float(mx)-rendering_x)+uv1_x*Umb::Graphics::GetDisplay()->GetWidth();
                    fmy = (float(my)-rendering_y)+uv1_y*Umb::Graphics::GetDisplay()->GetHeight();
                    mx = fmx;
                    my = fmy;
                    event->SetCoord(mx,my); /// transform click relative to black portion
                    internal_mx = mx;
                    internal_my = my;
              }else
              {
                  if (is_mouse_over)
                  {
                    is_mouse_over = false;
                    SDL_ShowCursor(1);
                  }
              }
           }

       }```

then i pass the click to the engine , now i am getting wrong results of about 2 to 12 pixels deppending on the position of the horizontal and virtical scroll bar of the back portion , then what i do is to hide the cursor and ask the engine to draw it when the cursor passes through it .

**Comment by ocornut** [comment]
I'm not sure to understand why your code is complicated, but it is hard to read without the code formatting (PS: use triple-backquotes to surround quote blocks).

```
ImVec2 screen_pos = ImGui::GetCursorScreenPos();
EngineInbox.SetRenderingPosition(screen_pos.x, screen_pos.y);
ImGui::Image((ImTextureID)GPU_GetImageHandle(engine_screen->image),ImVec2(engine_screen->w,engine_screen->h));
```

You've already got the absolute position and size of your view here, nothing else is required to transform your mouse coordinates to your game/view space.

**Comment by dhiahassen** [comment]
It is complicated because i want the black poriton ( engine screen ) to be with scrolling , and i want the user to be able to resize the window and scroll it to navigate through the engine's screen , and when he click , whereever the scrolling is , i still callculate the currect coordinate for the internal engine world , in other words , the coordinate of the click relative to the top left corner of the drawn image ( the engine screen ) and that with scrollling included . 
my mistake was that i tried to calculate the screen  cursor position myself using cursor potion relative to window + window position and i got slightly wrong results , now i am using 'GetCursorScreenPos()' 

with this                     `EngineInbox.SetViewPortion(uv1.x,uv1.y,uv2.x,uv2.y);`

i was telling the engine the visible image potion using uv coordinates , i calculate them myself , these are the same data you recieve when rendering an image using gl_handle , the same data you recive from imgui , the UV coodinates , and i am using them to calculate the click coordinates relative to the inner world of the engine , i pass them to the engine using `EngineInbox.SetViewPortion(uv1.x,uv1.y,uv2.x,uv2.y);`

Is there a simpler way to do all this ?

**Comment by ocornut** [comment]
Given imgui screen pos and size you can convert your mouse input to game screen coordinate. 

Then your problem is that you want to convert from game screen coordinate to your world coordinates. It's not really a problem that has anything to do with imgui.

**Comment by dhiahassen** [comment]
It has actually :p , i am not here to hack a help ! hh

I want to get the mouse coordinates relative to the top left corner of the visible portion of an image ( or any 'widget'  but an image in my case )

**Comment by ocornut** [comment]
You can query the scrolling with `GetScrollXXX` functions, so, e.g.

```
MousePos.x - GetCursorScreenPos().x - GetScrollX()
MousePos.y - GetCursorScreenPos().y - GetScrollY()
```

I'm not sure why you need to use GetWindowContentRegionXX function here.
Anyway, to debug that sort of thing, just display all the values/computation with ImGui::Text() so you can visualize what's going on and what's wrong.

**Comment by dhiahassen** [comment]
So

`MousePos.x - GetCursorScreenPos().x - GetScrollX()`

What does it give ?

**Comment by ocornut** [comment]
> What does it give ?

Print it out with `ImGui::Text` as stated above to find out.

> Much and mach thanks for the the replies

Unfortunately this is not working. This is not a place for hand-holding and generic programming advices so I have to close this thread. Other may reply. But you probably want to figure it out by yourself or ask on a gamedev forum.

**Comment by dhiahassen** [comment]
you know the issue is certainly Imgui's usage related , i explained that , so thanks
