### ISSUE TITLE
vertical alignment of buttons

### ISSUE THREAD

**Issue by ecraven** [ocornut/imgui#1284]
Is there any way to align buttons of different size in a row (using .Button and .SameLine) *bottom*-aligned? By default, their top will align, but I'd need them to align along their bottoms :-/
Thanks for any ideas on how to solve this!

**Comment by ocornut** [comment]
It isn't possible at the moment, you would have to use `SetCursorPos()` to position them yourself. I have added a note for this in the todo list.

**Comment by ecraven** [comment]
> It isn't possible at the moment, you would have to use
> `SetCursorPos()` to position them yourself. I have added a note for
> this in the todo list.

Thanks! I'll look into SetCursorPos!

**Comment by ocornut** [comment]
The reason it isn't possible is that to bottom-align you need to know where "bottom" is and that requires knowing about the tallest element.

So whenever that will be supported it will likely be either through an explicit declaration of the desired height or via a multi-pass system or via 1-frame feedback delay.

**Comment by ecraven** [comment]
> The reason it isn't possible is that to bottom-align you need to know
> where "bottom" is and that requires knowing about the tallest element.
> So whenever that will be supported it will likely be either through an
> explicit declaration of the desired height or via a multi-pass system
> or via 1-frame feedback delay.

Thanks, I understand that. I've kind of solved it with moving the
cursor, but I don't fully understand how item height is calculated yet
(need to read the source some more), so it's not perfect yet ;)

No hurry, it would just be nice to have this some day.

**Comment by ocornut** [comment]
For `Button` and most items the height would be (height of your text) + style.FramePadding.y * 2
The height of your text label is generally `ImGui::GetFontSize() * 1` for single-line button.

**Comment by ocornut** [comment]
Closing this issue.
