### ISSUE TITLE
How to handle resize of created window

### ISSUE THREAD

**Issue by tigrazone** [ocornut/imgui#1287]
I create window by
      ImGui::Begin("Render");
      ImTextureID tex_id = reinterpret_cast<void *>(
                    static_cast<intptr_t>(gl_texid));
      ImGui::Image(tex_id, ImVec2(256, 256), ImVec2(0, 0),
                   ImVec2(1, 1));// Setup camera and draw imguizomo
      ImGui::End();

how to handle size change of created window?

**Comment by ocornut** [comment]
I don't understand your question, please clarify.
Have you checked the demo code, and imgui.h ?

**Comment by tigrazone** [comment]
shown code is from https://github.com/lighttransport/nanort/tree/master/examples/nanosg
file https://github.com/lighttransport/nanort/blob/master/examples/nanosg/main.cc
from line 912.
shown code create window and render image into it and show. 
if I change size of window with rendered image, I want to handle size change for replace image width and height
look at gifed explaination http://moo.ho.ua/imgui-resize.gif

**Comment by mmozeiko** [comment]
Have you tried `ImGui::GetWindowSize()`?

From imgui.h file:
 
    IMGUI_API ImVec2        GetWindowSize();    // get current window size

**Comment by tigrazone** [comment]
show me example how to use it

**Comment by mmozeiko** [comment]
Same as with any other imgui function:

    ImVec2 size = ImGui::GetWindowSize();

    // now use size.x and size.y
    // ...

**Comment by ocornut** [comment]
Closing this old issue.
Using `ImGui::GetContentRegionAvail()` would be the preferred answer, generally.

```
ImVec2 avail_size = ImGui::GetContentRegionAvail();
ImGui::Image((void*)my_texture, avail_size);
```

**Comment by olkotov** [comment]
An example of handling window resizing.

```cpp
void ViewportWindow::Draw()
{
	ImGui::PushStyleVar( ImGuiStyleVar_WindowPadding, ImVec2( 0.0f, 0.0f ) );
	ImGui::Begin( "Viewport" );

	if ( HandleWindowResize() == false )
	{
		ImGui::End();
		ImGui::PopStyleVar();
		return;
	}

	RenderFrame();
	
	ImGui::Image( (void*)m_ColorBuffer, ImVec2( m_Window.width, m_Window.height ), ImVec2( 0.0f, 1.0f ), ImVec2( 1.0f, 0.0f ) );

	ImGui::End();
	ImGui::PopStyleVar();
}

bool ViewportWindow::HandleWindowResize()
{
	ImVec2 view = ImGui::GetContentRegionAvail();

	if ( view.x != m_Window.width || view.y != m_Window.height )
	{
		if ( view.x == 0 || view.y == 0 )
		{
			// The window is too small or collapsed.
			return false;
		}

		m_Window.width = view.x;
		m_Window.height = view.y;

		RecreateFramebuffer();

		// The window state has been successfully changed.
		return true;
	}

	// The window state has not changed.
	return true;
}
```
