### ISSUE TITLE
How to catch of closed window event

### ISSUE THREAD

**Issue by SandSt0rm** [ocornut/imgui#1290]
Hey,

I'm using a menu item: ImGui::MenuItem("Motion Blur", NULL, &motionBlurPE);
When the user is clicking this option, the function returns true, so i can catch this event, and I open a new window with ImGui::Begin function.

then the user finishes with the new window and click the 'x' button to close it, how can i catch this event?

Thanks

**Comment by ocornut** [comment]
There's not many "events" in imgui, those functions modify the bool you are passing the address of (it is `bool* p_open` for Begin()) and this is your defacto state about weither a window is opened.

MenuItem() returns true when clicked, and also toggle the bool you pass it.

**Comment by SandSt0rm** [comment]
thanks, i'll just pay attention to the boolean value in real time then.

**Comment by ocornut** [comment]
Look at what the code in imgui_demo.cpp is doing, and just use that bool to decide if you need to create the window (which itself receives a pointer to the bool).
