### ISSUE TITLE
Gamepad navigation branch, can't navigate inside child

### ISSUE THREAD

**Issue by galop1n** [ocornut/imgui#1291]
Hi,

It seems that the navigation to a child is not working. I can see reference of code to leaving a child, and the documentation seems to indicate it is possible to enter one, but so far, i am out of luck messing with the pad.

Did i miss something ?

**Comment by ocornut** [comment]
You are right it looks like there is a bug. Will look into it.

**Comment by ocornut** [comment]
FYI it was broken by this change in the master branch
https://github.com/ocornut/imgui/commit/ddf08ec2e846659a298351b6f9d91cf5d641b991

Which somehow conflicted with how the nav branches needed to identify child windows. I'm working on a fix.

**Comment by ocornut** [comment]
Should be fixed now.
