### ISSUE TITLE
Edit all color attributes using col_main with ColorEdit3?

### ISSUE THREAD

**Issue by officialabyssal** [ocornut/imgui#1292]
Basically when I try using the ColorEdit 3 sliders they work fine for changing independent attributes:
`ImGui::ColorEdit3("Header Color", (float*)&style.Colors[ImGuiCol_Header]);`

But when I try to make a slider that changes anything that uses col_main such as [ImGuiCol_ScrollbarGrabActive],  [ImGuiCol_Header], and style.Colors[ImGuiCol_Button], I get errors with this code.
`ImGui::ColorEdit3("Header Color", (float*)&col_main);`

Any idea on how I could make it so the slider changes all items using col_main as the x, y, and z variables?

**Comment by ocornut** [comment]
I don't understand your question. It seems like a C++ question.

What is col_main? What is the type of that variable? If you are getting an error please provise the exact error. Please also provide an independant piece of code we can paste into the examples app to understand your bug.

**Comment by officialabyssal** [comment]
Basically I have a variable called col_main that controls most of the colors but I want to change the col_main variable with a slider so the slider changes all items using col_main. The code might explain more.
`	ImVec4 col_text = ImColor(255, 255, 255);
	ImVec4 col_main = ImColor(235, 66, 66);
	ImVec4 col_back = ImColor(33, 36, 43);
	ImVec4 col_area = ImColor(51, 56, 69);

	style.Colors[ImGuiCol_Text] = ImVec4(col_text.x, col_text.y, col_text.z, 1.00f);
	style.Colors[ImGuiCol_TextDisabled] = ImVec4(col_text.x, col_text.y, col_text.z, 0.58f);
	style.Colors[ImGuiCol_WindowBg] = ImVec4(col_back.x, col_back.y, col_back.z, 1.00f);
	style.Colors[ImGuiCol_ChildWindowBg] = ImColor(43, 48, 58);
	style.Colors[ImGuiCol_Border] = ImVec4(col_back.x, col_back.y, col_back.z, 1.00f);
	style.Colors[ImGuiCol_BorderShadow] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
	style.Colors[ImGuiCol_FrameBg] = ImVec4(col_area.x, col_area.y, col_area.z, col_area.w + .1f);
	style.Colors[ImGuiCol_FrameBgHovered] = ImVec4(col_main.x, col_main.y, col_main.z, 0.68f);
	style.Colors[ImGuiCol_FrameBgActive] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_TitleBg] = ImVec4(col_main.x, col_main.y, col_main.z, 0.45f);
	style.Colors[ImGuiCol_TitleBgCollapsed] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_TitleBgActive] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_MenuBarBg] = ImVec4(col_area.x, col_area.y, col_area.z, 0.57f);
	style.Colors[ImGuiCol_ScrollbarBg] = ImVec4(col_area.x, col_area.y, col_area.z, 1.00f);
	style.Colors[ImGuiCol_ScrollbarGrab] = ImVec4(col_main.x, col_main.y, col_main.z, 0.85f);
	style.Colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(col_main.x, col_main.y, col_main.z, 0.90f);
	style.Colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_ComboBg] = ImVec4(col_area.x, col_area.y, col_area.z, 1.00f);
	style.Colors[ImGuiCol_CheckMark] = ImVec4(col_main.x, col_main.y, col_main.z, 0.90f);
	style.Colors[ImGuiCol_SliderGrab] = ImVec4(col_main.x, col_main.y, col_main.z, 0.90f);
	style.Colors[ImGuiCol_SliderGrabActive] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_Button] = ImVec4(col_main.x, col_main.y, col_main.z, 0.50f);
	style.Colors[ImGuiCol_ButtonHovered] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_ButtonActive] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_Header] = ImVec4(col_main.x, col_main.y, col_main.z, 0.76f);
	style.Colors[ImGuiCol_HeaderHovered] = ImVec4(col_main.x, col_main.y, col_main.z, 0.86f);
	style.Colors[ImGuiCol_HeaderActive] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_Column] = ImVec4(col_back.x, col_back.y, col_back.z, 1.00f);
	style.Colors[ImGuiCol_ColumnHovered] = ImVec4(col_back.x, col_back.y, col_back.z, 1.00f);
	style.Colors[ImGuiCol_ColumnActive] = ImVec4(col_back.x, col_back.y, col_back.z, 1.00f);
	style.Colors[ImGuiCol_ResizeGrip] = ImVec4(col_main.x, col_main.y, col_main.z, 0.20f);
	style.Colors[ImGuiCol_ResizeGripHovered] = ImVec4(col_main.x, col_main.y, col_main.z, 0.78f);
	style.Colors[ImGuiCol_ResizeGripActive] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_CloseButton] = ImVec4(col_text.x, col_text.y, col_text.z, 0.16f);
	style.Colors[ImGuiCol_CloseButtonHovered] = ImVec4(col_text.x, col_text.y, col_text.z, 0.39f);
	style.Colors[ImGuiCol_CloseButtonActive] = ImVec4(col_text.x, col_text.y, col_text.z, 1.00f);
	style.Colors[ImGuiCol_PlotLines] = ImVec4(col_text.x, col_text.y, col_text.z, 0.63f);
	style.Colors[ImGuiCol_PlotLinesHovered] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_PlotHistogram] = ImVec4(col_text.x, col_text.y, col_text.z, 0.63f);
	style.Colors[ImGuiCol_PlotHistogramHovered] = ImVec4(col_main.x, col_main.y, col_main.z, 1.00f);
	style.Colors[ImGuiCol_TextSelectedBg] = ImVec4(col_main.x, col_main.y, col_main.z, 0.43f);
	style.Colors[ImGuiCol_PopupBg] = ImVec4(col_main.x, col_main.y, col_main.z, 0.92f);
	style.Colors[ImGuiCol_ModalWindowDarkening] = ImVec4(0.20f, 0.20f, 0.20f, 0.35f);`

**Comment by ocornut** [comment]
Then edit col_main with ColorEdit3 and then call the code that does the rest.

**Comment by officialabyssal** [comment]
Well that's the problem I can't because everytime I use this code,
`ImGui::ColorEdit3("Header Color", (float*)&col_main);`

I get the following errors.
`identifier 'col_main' is undefined
'col_main': undefined identifier`

Yet I defined it in the code above but here's more.
`ImGui::ColorEditMode(ImGuiColorEditMode_RGB);
ImGuiStyle &style = ImGui::GetStyle();
ImGui::ColorEdit3("Text Color", (float*)&style.Colors[ImGuiCol_Text]);
ImGui::Separator();
ImGui::ColorEdit3("Header Color", (float*)&style.Colors[ImGuiCol_Header]);
ImGui::Separator();
ImGui::ColorEdit3("Header Color", (float*)&style.Colors[ImGuiCol_Header]);
ImGui::Separator();
ImGui::ColorEdit3("Header Color", (float*)&col_main);`

**Comment by ocornut** [comment]
It looks like you are confused by C++ programming. Could you ask on a general programming forums for suggestions about that, otherwise it's becomes a never ending thing when we use this forum to answer general programming questions.

**Comment by officialabyssal** [comment]
Aight thanks though.

**Comment by ocornut** [comment]
Posting _complete_ snippet of code on sites like StackOverflow will help. It seems you don't have a col_main in scope here and need to rearrange the code, perhaps store col_main somewhere accessible and move the rest into a function you can call when col_main etc changed.

ColorEdit3 and most widgets return true when the value has been modified so you can use that return value to call the function that will recompute the styles colors.
