### ISSUE TITLE
Drawing custom elements

### ISSUE THREAD

**Issue by Hperigo** [ocornut/imgui#1295]
I haven't found lot of documentation on this topic, so forgive me if this is something that someone already asked

So how would I write a window that does this?
![image](https://user-images.githubusercontent.com/3333460/29694862-ad0e9e64-8915-11e7-9df6-b7e4cd4550a4.png)
(https://github.com/ocornut/imgui/issues/973 )

thanks =)
bye

**Comment by ocornut** [comment]
See some reference here:
https://github.com/ocornut/imgui/issues/786

**Comment by Hperigo** [comment]
cool thanks =)

**Comment by ocornut** [comment]
Closing as #786 contains the goods :)
