### ISSUE TITLE
ProgressBar draws 'progress' even when value is 0

### ISSUE THREAD

**Issue by berkay2578** [ocornut/imgui#1296]
Before all, I'm running version 1.51. ProgressBar draws an unexpected filled rectangle when the `fraction` value is 0 and `style.FrameRounding` is greater than 0.0f. This also happens with the default theme. I tried to fix it but I failed.

With FrameRounding:
![image](https://user-images.githubusercontent.com/10451146/29748961-737ae79a-8b2a-11e7-85c8-4c106fd81120.png)
Without FrameRounding:
![image2](https://user-images.githubusercontent.com/10451146/29748972-99cf7b22-8b2a-11e7-931c-96c85dfb997c.png)

gifs:
[style.FrameRounding = 0.0f](https://gfycat.com/RequiredPertinentBuck)
[style.FrameRounding > 0.0f](https://gfycat.com/NimbleOccasionalArawana)

A dirty workaround for now is to use:
`RenderFrame(bb.Min, fill_br, GetColorU32(ImGuiCol_PlotHistogram), false, fraction < 0.01f ? 0.0f : style.FrameRounding);`

**Comment by berkay2578** [comment]
I have also noticed that the rectangle of `ImGuiCol_PlotHistogram` is drawn _over_ the rectangle of `ImGuiCol_FrameBg`, this causes issues if you want both of the colours to have transparency. I'm currently using this as a workaround:
```
``

**Comment by ocornut** [comment]
> I have also noticed that the rectangle of ImGuiCol_PlotHistogram is drawn over the rectangle of ImGuiCol_FrameBg, this causes issues if you want both of the colours to have transparency. 

Most things in imgui are drawn over the FrameBg color, that's the desired platforms. Your solution wouldn't easily be applicable to widgets like `PlotHistogram()`, etc.

I'll look at how we can fix your first issue above.

**Comment by berkay2578** [comment]
> Most things in imgui are drawn over the FrameBg color, that's the desired platforms. Your solution wouldn't easily be applicable to widgets like PlotHistogram(), etc.

I'm only posting it for future reference if anyone else wants to draw the progressbar in the same way I do. This is a unique situation where I'm using it to draw a digital speedometer anyways.

> Please use github attachment and no external link when possible, else the links will end up failing in the future, making things harder to refer to for others.

Noted, I've edited the main post to have images of the issue.

**Comment by ocornut** [comment]
> Yeah, I know, it's for extreme situations like mine where I'm using it to draw a digital speedometer with the RPM value as the background.

That function is literally 2 calls to RenderFrame() which is 1 call to draw_list->AddRectFilled(), if you are doing custom rendering you'd probably be better just doing the calls yourself instead of relying on ProgressBar.

Looking at the rendering.

**Comment by ocornut** [comment]
This should be fixed now (with quite some pain to get the rendering right - but the resulting function will be useful for other stuff).
