### ISSUE TITLE
ImGui::Begin() ignores flags?

### ISSUE THREAD

**Issue by czvpka** [ocornut/imgui#1298]
Hello there, my problem is that, when I call ImGui::Begin() it ignores flags that I given. Here's my code:
https://pastebin.com/6haCJRZE
That should make window not collapsable and not resizable, also there should not be any title bar, but the flags are just ignored. Any fix? Any help really appreciated.

**Comment by berkay2578** [comment]
I'm considering that you didn't even attempt to understand the function you're using.

From imgui.h:
```
IMGUI_API bool          Begin(const char* name, bool* p_open = NULL, ImGuiWindowFlags flags = 0);
IMGUI_API bool          Begin(const char* name, bool* p_open, const ImVec2& size_on_first_use, **float bg_alpha = -1.0f**, ImGuiWindowFlags flags = 0);
```
You're missing the `float bg_alpha` and your compiler is interpreting the window flags as a float. Anyways, you should use the first `Begin(const char*, bool*, ImGuiWindowFlags)` and call `ImGui::SetNextWindowSize(ImVec2, ImGuiCond)` as commented in the header file, the second function will eventually be marked obsolete.

**Comment by ocornut** [comment]
Thank you @berkay2578, problem solved!
(Yeah I'm really frustrated by this `bg_alpha` parameter.. I'll probably go alpha when we decide to do a big-breakage-combo, maybe api 2.0).
