### ISSUE TITLE
Cannot link imgui to my OpenGL project

### ISSUE THREAD

**Issue by CatsNipYummy** [ocornut/imgui#1299]
I get the following errors:

`Error	LNK2019	unresolved external symbol "bool __cdecl ImGui_ImplGlfwGL3_Init(struct GLFWwindow *,bool)" (?ImGui_ImplGlfwGL3_Init@@YA_NPAUGLFWwindow@@_N@Z) referenced in function "public: void __thiscall MainWindow::Display(void)" (?Display@MainWindow@@QAEXXZ)	OpenGL	D:\Repos\OpenGL\OpenGLGame\OpenGL\window.obj	1	
Error	LNK2019	unresolved external symbol "struct ImGuiIO & __cdecl ImGui::GetIO(void)" (?GetIO@ImGui@@YAAAUImGuiIO@@XZ) referenced in function "public: void __thiscall MainWindow::Display(void)" (?Display@MainWindow@@QAEXXZ)	OpenGL	D:\Repos\OpenGL\OpenGLGame\OpenGL\window.obj	1	
Error	LNK2019	unresolved external symbol "void __cdecl ImGui::Text(char const *,...)" (?Text@ImGui@@YAXPBDZZ) referenced in function "public: void __thiscall MainWindow::Display(void)" (?Display@MainWindow@@QAEXXZ)	OpenGL	D:\Repos\OpenGL\OpenGLGame\OpenGL\window.obj	1	
Error	LNK2019	unresolved external symbol "bool __cdecl ImGui::Button(char const *,struct ImVec2 const &)" (?Button@ImGui@@YA_NPBDABUImVec2@@@Z) referenced in function "public: void __thiscall MainWindow::Display(void)" (?Display@MainWindow@@QAEXXZ)	OpenGL	D:\Repos\OpenGL\OpenGLGame\OpenGL\window.obj	1	
Error	LNK2019	unresolved external symbol "bool __cdecl ImGui::SliderFloat(char const *,float *,float,float,char const *,float)" (?SliderFloat@ImGui@@YA_NPBDPAMMM0M@Z) referenced in function "public: void __thiscall MainWindow::Display(void)" (?Display@MainWindow@@QAEXXZ)	OpenGL	D:\Repos\OpenGL\OpenGLGame\OpenGL\window.obj	1	
Error	LNK2019	unresolved external symbol "bool __cdecl ImGui::ColorEdit3(char const *,float * const,int)" (?ColorEdit3@ImGui@@YA_NPBDQAMH@Z) referenced in function "public: void __thiscall MainWindow::Display(void)" (?Display@MainWindow@@QAEXXZ)	OpenGL	D:\Repos\OpenGL\OpenGLGame\OpenGL\window.obj	1	
Error	LNK2019	unresolved external symbol "void __cdecl ImGui_ImplGlfwGL3_NewFrame(void)" (?ImGui_ImplGlfwGL3_NewFrame@@YAXXZ) referenced in function "public: void __thiscall MainWindow::Display(void)" (?Display@MainWindow@@QAEXXZ)	OpenGL	D:\Repos\OpenGL\OpenGLGame\OpenGL\window.obj	1	
Error	LNK1120	7 unresolved externals	OpenGL	D:\Repos\OpenGL\OpenGLGame\Debug\OpenGL.exe	1`

Is there a .lib file I need to link? I've added the C++ files.

**Comment by ocornut** [comment]
Hello Anil,

> I've added the C++ files.

This error basically suggest you the C++ files aren't compiled into your project.
There's no .lib file for imgui (adding the C++ files is the standard way).

(Please try to ask general c++/programming/linking questions on a general programming forum because they are classic problems that programmers encounters and it's not specific to imgui.)
