### ISSUE TITLE
Creating child box title

### ISSUE THREAD

**Issue by czvpka** [ocornut/imgui#1300]
Hello. I want to make a child box title, like here: [screenshot1](https://user-images.githubusercontent.com/26123917/29744548-10522dc8-8aa7-11e7-9c4a-cd4f7d08d8d8.png)
Anyone know how can I do that? I tried with `ImGui::SameLine(some values to position text);` but it works only in X axis, no I can't place it higher or lower than it is. Any help really appreciated :smile:

**Comment by berkay2578** [comment]
Look into `ImGui::SetCursorPos*()` instead for this. However, if that's actually ImGui, it's heavily customised. You won't be able to get the same look without writing some custom controls yourself.

**Comment by czvpka** [comment]
@berkay2578 Do you know how can I customize child box border? At least I should edit it.

**Comment by ocornut** [comment]
Just draw the label yourself after you finishing drawing the child window.

Note that child windows are here to provide a separate scrolling region, note of the screenshot above requires childs. You'd just need to do the layout yourself (skip some vertical space, call Indent(), skip some vertical space and then draw the stuff yourself).

It would probably be useful to provide helpers/ways to do it more naturally.

**Comment by arcneex** [comment]
Polaks aimware GUI is better than imgooey you cannot even comprehend his brain is enormous

**Comment by ocornut** [comment]
Closing, moving to #1496.
