### ISSUE TITLE
Sliders with scientific notation

### ISSUE THREAD

**Issue by MomentsInGraphics** [ocornut/imgui#1301]
When changing values with a high dynamic range through sliders, scientific notation is very useful. Passing "%.1e" as format string to ImGui::SliderFloat() works fine in terms of display but if the value is small, dragging the slider is useless because it will round too much. ImGui::ParseFormatPrecision() will see the 1 and conclude that it can round to multiples of 0.1. 

Here is my ad hoc fix for that:
~~~~~~
// Parse display precision back from the display format string
int ImGui::ParseFormatPrecision(const char* fmt, int default_precision)
{
    int precision = default_precision;
    while ((fmt = strchr(fmt, '%')) != NULL)
    {
        fmt++;
        if (fmt[0] == '%') { fmt++; continue; } // Ignore "%%"
        while (*fmt >= '0' && *fmt <= '9')
            fmt++;
        if (*fmt == '.')
        {
            precision = atoi(fmt + 1);
            if (precision < 0 || precision > 10)
                precision = default_precision;
            if (fmt[2] == 'e' || fmt[2] == 'E')
                precision = 38;
        }
        else if (fmt[0] == 'e' || fmt[0] == 'E')
            precision = 38;
        break;
    }
    return precision;
}
~~~~~~

**Comment by ocornut** [comment]
Thanks @MomentsInGraphics. I have now fixed the parsing in that situation. Using different code because suggested code would break with two digits e.g. "%10e". Also instead of using `precision = 38` I'm just disabling the code in `RoundScalar`. Thanks!

Commit:
https://github.com/ocornut/imgui/commit/7a7327addec8cde30c13d6224a121033043874ba

**Comment by MomentsInGraphics** [comment]
That looks much cleaner than what I did and I can confirm that it works for my use case. Thanks for the amazingly quick fix and all the work you put into dear imgui in general.
