### ISSUE TITLE
Hello, I was wondering how to disable this child window that pops up on Windows

### ISSUE THREAD

**Issue by justinjk007** [ocornut/imgui#1303]
![wtf](https://user-images.githubusercontent.com/12916795/29892337-3ce6c306-8d9c-11e7-9352-34c66e54faaa.PNG)

As you can see along with the main window, there is an empty cmd window. Is there any way to disable that ?

Thanks for the help . I am very new to imgui.

**Comment by ratzlaff** [comment]
That is not an artifact of imgui but how the executable was built. With Visual Studio, it is most likely because the subsystem is set to [CONSOLE](https://docs.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem)

**Comment by justinjk007** [comment]
I tried changing the Subsystem to all other values possible. All I am getting is lot of linker errors. I tried  changing the Architecture(default Win32)   to x64 which also spit out a lot of errors. Only setting the subsystem to CONSOLE and architecture to Win32 works. Does this also mean if I want to use imgui with my CGAL build which is x64, that won't be possible ?

Thanks for the reply thou.

**Comment by justinjk007** [comment]
OK I found out in windows adding this above the main function will fix the problem.

```c
#pragma comment(linker, "/SUBSYSTEM:windows /ENTRY:mainCRTStartup")
```

**Comment by ocornut** [comment]
This question has a absolutely nothing to do with the dear imgui library. Please ask on eg: stackoverflow.

**Comment by ocornut** [comment]
Could you provide the linker errors you get, and what exactly did you try to build with what compiler?

**Comment by justinjk007** [comment]
Oops never mind , changing the subsystem also fixed architecture trouble I think. It compiles without errors . I guess restarting Visual Studio fixed it.
