### ISSUE TITLE
Question regarding io.MousePos

### ISSUE THREAD

**Issue by zhihua-z** [ocornut/imgui#1304]
Thanks for providing us with this library, now I am doing my school project using your library, however, we are not allowed to use glfw and gl3w so I have to write some alternatives to the glfw functions in your opengl3 example.

The problem is, when I code the getCursorPos, I have some doubt, is the cursor position relative to the top left corner of the window position? or the client area position? Is the following implementation correct?

  `POINT p;`
  `RECT rec;`
  `GetCursorPos(&p);`
  `GetWindowRect(myHwnd, &rec);`

  `x = p.x - rec.left;`
  `y = p.y - rec.top;`

this code behaves very strange, the cursor position get more and more off as it goes further from the top left corner

Thanks for your help!

**Comment by ocornut** [comment]
ImGui has no knowledge or concept of your OS windows. It's behaving in a abstract space where visible coordinates are going from (0.0, 0.0) to DisplaySize and however you map your mouse to that space or your rendering/windows/visuals to that space doesn't matter to imgui.

In other word and to use Windows terminology, you probably want to use client size as DisplaySize assuming that you renderer all pixels to fit that same client area.

Either your mouse position doesn't match your client size, either your rendering function (eg: projection matrix) is not treating imgui coordinates as 1:1 with that client size. 

That's something that you have to debug by yourself. You can use a debugger or ImGui::Text to display a maximum of values (client size, return value from GetCursorPos) to solve it. You can also take a screenshot to measure the visible client size and verify that it matches that you expect and what the rendering function fed to its projection matrix.
