### ISSUE TITLE
How to Hide Close Menu Button "X" Without no Titlebar Function?

### ISSUE THREAD

**Issue by GrammarLord** [ocornut/imgui#1305]
Problably I couldn't find because of the right word but How to Hide Close Menu Button "X" Without no Titlebar Function?

**Comment by ocornut** [comment]
Pass `bool* p_open = NULL` to the function.

**Comment by GrammarLord** [comment]
This is not relevant but how can I do No Move for just main body. Not for titlebar. What I mean I can move from title bar with mouse but not from main body. I hope you understand. @ocornut

**Comment by ocornut** [comment]
That's not possible at the moment.
