### ISSUE TITLE
Close Button Shape

### ISSUE THREAD

**Issue by GrammarLord** [ocornut/imgui#1308]
How can I change the shape of close button? Like square. I did look few resources but I couldn't find in the sources.

**Comment by ocornut** [comment]
It is not possible and not planned at the moment to make that sort of skinning possible.

The function the sources is literally called `CloseButton()` :)

**Comment by GrammarLord** [comment]
What I mean is this.[https://pasteboard.co/GIkz3s9.png](url). And there is one more question. I am using imgui for game hacking. When I auto inject the dll I can't move the menu. When I open the game first then manual inject when I do alt+tab. I will upload wait a sec.

**Comment by ocornut** [comment]
> What I mean is this. https://pasteboard.co/GIkz3s9.png "

This is already what you have asked above and I've answered you it's not possible unless you fork imgui code.

> And there is one more question. 

One topic for each unrelated question please...

> I am using imgui for game hacking. When I auto inject the dll I can't move the menu. When I open the game first then manual inject when I do alt+tab. I will upload wait a sec. Video https://youtu.be/8TGuBx9uFpY

...make it zero topic please. Your question has nothing to do with imgui.
