### ISSUE TITLE
Pass user data in ImDrawData

### ISSUE THREAD

**Issue by n00bmind** [ocornut/imgui#1309]
Hi.
I've just started integrating your awesome library in my engine, but I'm going the pure manual route, so just OpenGL with no wrappers/helper libs.
I use a struct to hold some OpenGL related state, like compiled shader ids, etc, and I find I need to have access to it when my render callback is called, in order to get to this kind of data during rendering.
Since you already group all the data passed to the callback in a nice struct, I think it would be super useful to add a user-configurable void * there so that the callback can get any extra data needed.
Just a suggestion.

Also, I saw you don't have a pure Win32 example, so maybe I could upload a stripped-down version of my code when I manage to integrate the basic stuff, at least as a starting point?

**Comment by ocornut** [comment]
You can set the RenderFn pointer to NULL, call the GetDrawData() accessor use that however you will instead of going through that callback. 

I imagine that an hypothetical 2.0 api would get rid of the callback to favor that other approach.

If you search in the PR here you'll find an old unmerged pull request with a native Win32 example but it was rather noisy and not following the structure of other examples enough. I agree it would be nice extra to have such example available.

**Comment by ocornut** [comment]
@n00bmind Edited my post above for clarity, it was terribly written, sorry for that. (note for self: avoid using phone to reply after landing from a long flight).

I think I will rework the examples to use this approach soon.

**Comment by n00bmind** [comment]
Hey,
I just realized that I never got back to you on this..
I got aside a couple hours yesterday and stripped down my code to create a barebones example which I've commited to a fork I created.
I also went ahead and created a pull request https://github.com/ocornut/imgui/pull/1553, so you can review it and see if you like it.

Cheers, and happy new year!

**Comment by ocornut** [comment]
Hello!

While I appreciate (and we can use) the work in #1553, I don't see the connection with the question asked at the top of this topic here. My answer was that you can/should ignore the `io.RenderDrawListsFn` field. You can call Render+GetDrawData and then pass that draw data however you want to your own functions, and that answers your issue above, there's no callback involved anymore.

I will rework the examples/ apps to stop using `io.RenderDrawListsFn` at some point.

Omar

**Comment by n00bmind** [comment]
Yes sorry, it's just that I saw this issue linked on my github the other day and then I remembered about the example code..
This should probably be closed now.
