### ISSUE TITLE
Access Violation in ImFont::BuildLookupTable()

### ISSUE THREAD

**Issue by Visse** [ocornut/imgui#131]
Hi, the offending code is:
```c++
if (const ImFont::Glyph* space_glyph = FindGlyph((unsigned short)' '))
{
    Glyphs.resize(Glyphs.size() + 1);
    ImFont::Glyph& tab_glyph = Glyphs.back();
    tab_glyph = *space_glyph;
```
where 'space_glypth' is a dangling pointer after the resize of 'Glyphs'

**Comment by ocornut** [comment]
Stupid bug sorry for that. Hopefully it shouldn't have triggered with most vector implementations policy because it is the first time I hear about it. Thanks for finding it!
