### ISSUE TITLE
How to force an image to be rendered exactely at (0,0) coordinates inside a window without spacing ?

### ISSUE THREAD

**Issue by dhiahassen** [ocornut/imgui#1310]
I am trying to render an image to fully fill the entire window , but it is drawn almost at (0,0) at not exactely there , even it is set the cursor to 0,0 it still is rendering with a bit of spacing in the x-axes ( not y-axes ) , after calculating the spacing by substracting GetItemRectMin()-GetWindowPosition() , on the x axe it is 0 pixels !!! but yet as you can see in the image when i put a pixel ( see the tiny red pixel on the top left corner  ) to GetItemRectMin() of the image it is even out of the window ! ( the black rect is the image filt with black to make it obvious for you  )
![engine2](https://user-images.githubusercontent.com/17810558/30002888-7e4d8e4a-90b4-11e7-8ada-1a4092b6b71d.JPG)

**Comment by ocornut** [comment]
Because there is a clip rectangle that removes the edges of the window (based on style.WindowPadding.x). So you can either set WindowPadding to zero or push another bigger clipping rectangle (to cover the full window, or fullscreen).
