### ISSUE TITLE
Suggestion: Keypad Return also triggers ImGuiInputTextFlags_EnterReturnsTrue

### ISSUE THREAD

**Issue by Twinki14** [ocornut/imgui#1312]
Currently the Keypad Return Key does not trigger _EnterReturnsTrue, only the main Enter/Return key.

At least, this seems to be the case for GLFW3.

Adding a mew ImGuiKey_ entry for the keybad return, and binding it, could be a solution.

**Comment by ocornut** [comment]
It's true. In the meanwhile you can set your `KeyDown[KeyMap[ImGuiKey_Enter]]` value to the logical or of both your Enter keys.

**Comment by Twinki14** [comment]
You can set ImGuiKey_'s to multiple values?

Mind showing me a quick example?

**Comment by ocornut** [comment]
No, you can set the value in KeyDown[] yourself.

So you can add, e.g. `KeyDown[GLFW_KEY_ENTER] |= KeyDown[GLFW_KEY_KP_ENTER];` before new frame to merge the Keypad Enter value into the main value.

**Comment by Twinki14** [comment]
Ahh, figured it out.

Thank you.
