### ISSUE TITLE
How to make dropdown buttons?

### ISSUE THREAD

**Issue by czvpka** [ocornut/imgui#1314]
Hello, I want to make something like this guy did:
![image](https://i.gyazo.com/a021203d1dd5ef1bc5a4338d529fa61d.gif)
Anyone know, is it possible with standard ImGui functions? ;) Thanks for any replies 😄

**Comment by ocornut** [comment]
They are just `CollapsingHeader` or `TreeNode` widgets.
Please take the time to read _and_ run the demo applications because asking questions that are answerable there.

**Comment by czvpka** [comment]
I didn't even noticed there are some examples, I'm really sorry and I feel dumb now :x I'll try this out @ocornut, thanks!
