### ISSUE TITLE
WantTextInput can be set incorrectly with DragFloat

### ISSUE THREAD

**Issue by jadwallis** [ocornut/imgui#1317]
I've run into what I think is a bug in the way the `WantTextInput` flag (of `ImGuiIO`) is calculated when a `DragFloat` widget is used in a particular way.

The value of a `DragFloat` can be changed both by dragging and by double-clicking to enter text-entry mode. When dragging, I expect `WantTextInput` to be false, and if I start out just dragging the `DragFloat`, then it is. If I then enter text-entry mode on the same `DragFloat` to enter a value with the keyboard, `WantTextInput` becomes true, also as expected. All fine so far.

However, if, having entered a value through text entry, I then go back to dragging that same `DragFloat`, `WantTextInput` becomes true while dragging! This seems like a bug? `WantTextInput` is calculated as follows:

`g.IO.WantTextInput = (g.ActiveId != 0 && g.InputTextState.Id == g.ActiveId);`

...where `g.InputTextState.Id` stores the ID of the widget we were last editing the text of. This starts out as 0, and is then set to the ID of the `DragFloat` when we change its value using the text-entry approach. But once we have finished entering text, that ID is not cleared, and once we start dragging the `DragFloat` again, it becomes the `g.ActiveId`, meaning `WantTextInput` becomes true.

(I imagine this might hit any other widgets that can be 'activated' in a way that isn't 'editing text', if any such widgets exist; `DragFloat` just happens to be the widget I noticed this bug with.)

**Comment by ocornut** [comment]
Thanks for the report James, I have confirmed the issue.

We need `g.InputTextState.Id` to persist when we use it to preserve some text edit state across simple usage interruptions (such as clicking on a button while editing text), so we cannot clear out this field (and arguably the data persistence of InputText should be redesigned at some point.)

I'll search for a good way to fix it in the meanwhile.

**Comment by ocornut** [comment]
Should be fixed now!

**Comment by jadwallis** [comment]
Awesome! Thanks for the lightning-fast response. :)
