### ISSUE TITLE
SetScrollHere for horizontal layouts

### ISSUE THREAD

**Issue by inolen** [ocornut/imgui#1318]
Is there anything equivalent currently?

I looked into hacking up a copy of SetScrollHere replacing some y's with x's, but it looks like horizontal layouts may not be _quite_ as first class as vertical ones (e.g. it didn't seem there was an equivalent of PrevLineHeight for horizontal-based layouts).

For context, I'm trying to get these disc images laid out like so, such that you can scroll through them with keyboard input:
http://i.imgur.com/DUyrb2L.png

**Comment by ocornut** [comment]
Hello,
You may get away with using `SetScrollX()` in the meanwhile?
(There's currently a few inconsistency with scrolling that I will look into fixing)

**Comment by inolen** [comment]
That worked fine for me for now.

**Comment by ocornut** [comment]
Eventually `SetScrollHereX()` `SetScrollFromPosX()` were added in 1.72, closing this!

**Comment by ocornut** [comment]
Forgot to clarify:

> but it looks like horizontal layouts may not be quite as first class as vertical ones (e.g. it didn't seem there was an equivalent of PrevLineHeight for horizontal-based layouts).

It is using `float last_item_width = window->DC.LastItemRect.GetWidth();`

I'm also working on exposing the better function to "scroll toward making item visible" which would naturally scroll toward the direction of the item.
