### ISSUE TITLE
Too many Arguments, enable checked box by default  

### ISSUE THREAD

**Issue by thenewcm2001m** [ocornut/imgui#1326]
header file 
` OPTION(bool, loadin, false);`
cpp file 
`static bool checked = true;
ImGui::Checkbox("Enable glow", &g_Options.loadin,&checked);`
I am getting too many arguments error,
Possible fix?

**Comment by ocornut** [comment]
The signature of Checkbox is:
`bool Checkbox(const char* label, bool* v);`

This is a general C++/programming question, please be more considerate next time about not using this place for those.

**Comment by thenewcm2001m** [comment]
i am new to c++, so what would my cpp line look like?
Thanks

**Comment by ocornut** [comment]
Run the examples applications or call `ImGui::ShowTestWindow()` there are plenty of examples here.
You can find the code for that in imgui_demo.cpp and see how everything works.

**Comment by thenewcm2001m** [comment]
ok, but all your checkbox examples are only using two arguments, i need to
use 3 arguments
