### ISSUE TITLE
ImGUI and DirectX

### ISSUE THREAD

**Issue by RichardCRV** [ocornut/imgui#1327]
There is a problem
To draw the menu it is necessary to open 
```
ImGui::Begin(here parameters);
There is a stuffing
ImGui::End;
```

But if I want to draw something on directX
I can't cause 
```
pDevice->BeginScene ();
DrawLine(x, y, x + w, y + h, Color, pDevice);
pDevice->EndScene ();
pDevice->Present (NULL, NULL, 0, NULL);
```
It turns out crash
If I use ImGui as the menu, at me it is impossible to draw something on directx
What do I do not so?

Drawing of the menu
https://imgur.com/a/AEh35

Drawing of the line
https://imgur.com/a/nuimo

The call goes from one place
By a call of function of the menu - everything is good, it works
By a call of function of drawing of lines - crash

Drawing of lines correct if to cause it not from endscene, she works, but blinks

**Comment by ocornut** [comment]
I'm sorry but:
- This question is off-topic. ImGui::Begin()/End() don't touch DirectX _at all_ and so by definition has nothing to do with what you claim.
- It is hard to understand what you are asking at all. Maybe ask on a general programming forum in you home language?

1. Be more clear. Provide full code and precise information. Please try to provide a full reproduction app (with sources) to replicate your issue. If you say something is crashing, please show a callstack to specify how and where it crashes.
2. Specify which renderer you are using, are you using one of the `imgui_impl_dx??.cpp` file, did you made any modification to it?
3. Look in the RenderDrawList function `imgui_impl_dx???.cpp` file you may be using to understand what it is doing and how it. For example, the DX9 and DX11 renderer tries to backup all DX state it changes, and then restore them at the end.

(PS: Please use github attachments for picture, not imgur.com website)
