### ISSUE TITLE
Multiple filters in same window behave wrong

### ISSUE THREAD

**Issue by djdeath** [ocornut/imgui#1332]
Hi,

Thanks a lot for your work on ImGui. Just starting to use it and I find it really easy to use.
I get a lot done pretty quick!

I think I'm hitting a bug or limitation when using to ImGuiTextFilter in the same window.
When trying to write into the text filter input field, both filters are getting the focus at the same time.
![bug](https://user-images.githubusercontent.com/434333/30773026-cb0e0844-a05f-11e7-8952-fd6e9c26a850.png)

Should the filters get a specific id maybe?

**Comment by ocornut** [comment]
Hello,

Please read the FAQ about how ID work in dear imgui.

**Comment by djdeath** [comment]
Thanks, sorry for the noise.

**Comment by ocornut** [comment]
No worry, it's a recurrent issue but it's not obvious at first how the UI works.
Right now there's no way for the library to notify/guide the user through ID conflict issues, but once you get the grasp of how it works it's rarely a real issue.

**Comment by ocornut** [comment]
It has one but it has a default:
`Draw(const char* label = "Filter (inc,-exc)"`

**Comment by djdeath** [comment]
Duh!
I thought that was the default filter...
Sorry!
