### ISSUE TITLE
PushStyleVar changes isn't taken into account when BeginChild border is set to false

### ISSUE THREAD

**Issue by StuartSulaski** [ocornut/imgui#1338]
Hello Omar,

I may have found a strange bug with PushStyleVar and BeginChild.
You can find the snippet of code which recreates the issue below.

```
ImGui::Begin("Test Window");
{
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2{ 20.f, 2.f });
    {
        ImVec2 childWindowSize{ 200.f, 50.f };
        ImGui::BeginChild("Child 1", childWindowSize, true);
        {
            ImGui::Text("Hello World");
        }
        ImGui::EndChild();
        ImGui::BeginChild("Child 2", childWindowSize);
        {
            ImGui::Text("Hello World");
        }
        ImGui::EndChild();
    }
    ImGui::PopStyleVar();
}
ImGui::End();
```

When I run this code the first child has a padding of (20, 2) as specified in the PushStyleVar() but the second does not.
The only difference between the two is that the first one has his border param set to true and the second not.
If you set the border of the second child to true then his padding is correct.

Do you also have this issue ?
Is it simply due to a misunderstanding on my end or is this genuinely a bug ?

Thank you for your time

**Comment by ocornut** [comment]
It's indeed a little strange, but the reason is that in most occasions using `BeginChild()` without a border, having the padding would look odd.
If you pass the flag `ImGuiWindowFlags_AlwaysUseWindowPadding` to `BeginChild()` it will enforce using the padding even without a border.

**Comment by StuartSulaski** [comment]
Great that solved the issue 👍
Thanks a lot.
