### ISSUE TITLE
AddFonts issues

### ISSUE THREAD

**Issue by AIrSkycc** [ocornut/imgui#1341]
auto &imgui_io = _imgui_context->IO;
		auto &imgui_style = _imgui_context->Style;
		imgui_io.Fonts = _imgui_font_atlas.get();
		imgui_io.IniFilename = nullptr;
		imgui_io.KeyMap[ImGuiKey_Tab] = 0x09; // VK_TAB
		imgui_io.KeyMap[ImGuiKey_LeftArrow] = 0x25; // VK_LEFT
		imgui_io.KeyMap[ImGuiKey_RightArrow] = 0x27; // VK_RIGHT
		imgui_io.KeyMap[ImGuiKey_UpArrow] = 0x26; // VK_UP
		imgui_io.KeyMap[ImGuiKey_DownArrow] = 0x28; // VK_DOWN
		imgui_io.KeyMap[ImGuiKey_PageUp] = 0x21; // VK_PRIOR
		imgui_io.KeyMap[ImGuiKey_PageDown] = 0x22; // VK_NEXT
		imgui_io.KeyMap[ImGuiKey_Home] = 0x24; // VK_HOME
		imgui_io.KeyMap[ImGuiKey_End] = 0x23; // VK_END
		imgui_io.KeyMap[ImGuiKey_Delete] = 0x2E; // VK_DELETE
		imgui_io.KeyMap[ImGuiKey_Backspace] = 0x08; // VK_BACK
		imgui_io.KeyMap[ImGuiKey_Enter] = 0x0D; // VK_RETURN
		imgui_io.KeyMap[ImGuiKey_Escape] = 0x1B; // VK_ESCAPE
		imgui_io.KeyMap[ImGuiKey_A] = 'A';
		imgui_io.KeyMap[ImGuiKey_C] = 'C';
		imgui_io.KeyMap[ImGuiKey_V] = 'V';
		imgui_io.KeyMap[ImGuiKey_X] = 'X';
		imgui_io.KeyMap[ImGuiKey_Y] = 'Y';
		imgui_io.KeyMap[ImGuiKey_Z] = 'Z';
		imgui_style.WindowRounding = 0.0f;
		imgui_style.ChildWindowRounding = 0.0f;
		imgui_style.FrameRounding = 0.0f;
		imgui_style.ScrollbarRounding = 0.0f;
		imgui_style.GrabRounding = 0.0f;

		const auto font_path = filesystem::get_special_folder_path(filesystem::special_folder::windows) / "Fonts" / "msyh.ttc";
		if (filesystem::exists(font_path))
		{
			_imgui_font_atlas->AddFontFromFileTTF(font_path.string().c_str(), 18.0f, NULL, _imgui_font_atlas->GetGlyphRangesChinese());
			_imgui_font_atlas->AddFontFromFileTTF(font_path.string().c_str(), 18.0f, NULL, _imgui_font_atlas->GetGlyphRangesChinese());
		}
		else
		{
			const auto font_path = filesystem::get_special_folder_path(filesystem::special_folder::windows) / "Fonts" / "msyh.ttf";
			if (filesystem::exists(font_path))
			{
				_imgui_font_atlas->AddFontFromFileTTF(font_path.string().c_str(), 18.0f, NULL, _imgui_font_atlas->GetGlyphRangesChinese());
				_imgui_font_atlas->AddFontFromFileTTF(font_path.string().c_str(), 18.0f, NULL, _imgui_font_atlas->GetGlyphRangesChinese());
			}
			else
			{
				_imgui_font_atlas->AddFontDefault();
				_imgui_font_atlas->AddFontDefault();
			}
		}

		load_configuration();
	}

**Comment by AIrSkycc** [comment]
Why does the program crash?

**Comment by ocornut** [comment]
> otherwise the program will crash

- Please specify where it crash and how, and if it is an assert. 
- Use triple ``` to surround code in github.

**Comment by AIrSkycc** [comment]
if i write that way 
`const auto font_path = filesystem::get_special_folder_path(filesystem::special_folder::windows) / "Fonts" / "msyh.ttc";
	if (filesystem::exists(font_path))
	{
		_imgui_font_atlas->AddFontFromFileTTF(font_path.string().c_str(), 18.0f, NULL, _imgui_font_atlas->GetGlyphRangesChinese());
	}
	else
	{
		const auto font_path = filesystem::get_special_folder_path(filesystem::special_folder::windows) / "Fonts" / "msyh.ttf";
		if (filesystem::exists(font_path))
		{
			_imgui_font_atlas->AddFontFromFileTTF(font_path.string().c_str(), 18.0f, NULL, _imgui_font_atlas->GetGlyphRangesChinese());
		}
		else
		{
			_imgui_font_atlas->AddFontDefault();
		}
	}`

it will crash

**Comment by AIrSkycc** [comment]
image:
[http://i1.bvimg.com/530695/c0033d87e78aa0c3.png](url)

**Comment by ocornut** [comment]
Please provide a proper callstack in debug mode if you want help.
Closing this until you can provide an explanation, sorry.

**Comment by AIrSkycc** [comment]
ok i try it.
