### ISSUE TITLE
 arabic font

### ISSUE THREAD

**Issue by k1epic** [ocornut/imgui#1344]
hi
how to add arabic font ?

**Comment by ocornut** [comment]
See #1343

**Comment by k1epic** [comment]
**my ide RTL   support type  :** 

int main(int, char**)
{
        ......

	HWND hWnd = glfwGetWin32Window(window);

	io.ImeWindowHandle = hWnd;

	SetWindowLong(hWnd, GWL_EXSTYLE, GetWindowLong(hWnd, GWL_EXSTYLE) | WS_EX_LAYOUTRTL);

         ....
}

**and mirros projection  opengl 2 :** 

void ImGui_ImplGlfw_RenderDrawLists(ImDrawData* draw_data)
{
    ...
	// Setup viewport, orthographic projection matrix
	glViewport(0, 0, (GLsizei)fb_width, (GLsizei)fb_height);
	glMatrixMode(GL_PROJECTION);
	glPushMatrix();
	glLoadIdentity();
	glOrtho(0.0f, io.DisplaySize.x, io.DisplaySize.y, 0.0f, -1.0f, +1.0f);
	glMatrixMode(GL_MODELVIEW);
	glPushMatrix();
	glLoadIdentity();

        ///////////////////////////////////////////////////////
	glTranslatef((GLsizei)fb_width, 0, 0);
	glScalef(-1, 1, 1);
        //////////////////////////////////////////////////////
   ......
}

need to flip U in gltextureCoords ()

**Comment by ocornut** [comment]
Sorry it's not possible to display Arabic with dear imgui.

**Comment by ejurinsky** [comment]
@ocornut any plans to add the support?

**Comment by ocornut** [comment]
Unlikely for now.
