### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by r-lyeh** [ocornut/imgui#1346]
Not really an issue, but I just saw the recent SNES mini / MIT license topic on twitter, and it is said again the common misconception that MIT license does not require attribution. This guy's answer is very concise:

https://opensource.stackexchange.com/questions/4058/what-is-the-point-of-including-the-mit-copyright-text-if-you-use-someones-code

The point is that people that uses MIT licensed software must comply with the legal stuff; including the LICENSE file in F/OSS projects is enough, but if people of a commercial/closed project are using 100 MIT licensed libraries, they should credit those 100 libraries one by one. Which can be cumbersome to accomplish sometimes. I switched all my projects from MIT to ZLIB long time ago, (and actually im switching to dual PD+0BSD recently) just because these kind of stupid legal issues.

If you don't want to force users to display the legal text in a commercial/closed project then you can use a MIT+clarification notice like the https://github.com/munificent/wren/blob/master/LICENSE did , or use ZLIB or BOOST license, or 0BSD (which is similar to PD+nowarranty), etc :)

**Comment by ocornut** [comment]
You are totally right, I think I brain farted on this tweet.

My assumption for crediting in commercial software was altered by the nature of dear imgui - the library is not going to be included in the shipped software in many of its commercial uses. Although I have no evidence, I'd be surprised if the SNES Mini that shipped included dear imgui, I assume it was used during development?. 

By the way, console platforms now support a "legal blurb" system that can be displayed in the console OS, so closed-source games don't have to worry with displaying all of it in-game. Between that and just including a .TXT file next to PC/Mac binaries, it isn't so cumbersome.

I think I am fine with the License as is. 
Only niggle is, as pointed out by someone I was talking to recently, the fact that I wrote "Omar Cornut and ImGui contributors" in there, which I intended as a way to acknowledge external contributions, might in theory hinder my abilities to e.g. re-license future versions if I wanted to (not that I have any desire to do so). Do you have any input on that?

**Comment by r-lyeh** [comment]
Nope, but I would also like to know. I have been accepting/encouraging PRs for years without knowing 100% the legal implications of it.

**Comment by meshula** [comment]
That's why you're seeing more and more (modified) Apache 2 licenses out there ~ that license's contributor's agreement covers that point. https://www.apache.org/licenses/icla.pdf  (The modification is generally that use of the library doesn't give you rights to use the name of the project or its contributors in marketing.) A typical usage is here - https://graphics.pixar.com/usd/docs/Contributing-to-USD.html

**Comment by ocornut** [comment]
Closing this, thanks r-lyeh for the initial clarification. (github now has clickable licence icons that makes the same info very obvious too).

I'll keep the other topic is mind, was mostly wondering out of curiosity but there's no blocking/serious issues here.
