### ISSUE TITLE
Running ImGui with floating point overflow exceptions enabled causes a crash

### ISSUE THREAD

**Issue by gambiting** [ocornut/imgui#1353]
Hi! So I've ran into an issue where running ImGui while the floating point overflow exceptions are enabled causes a crash in imgui.cpp on line:

`        if (window_pos_set_by_api && ImLengthSqr(g.SetNextWindowPosVal - ImVec2(-FLT_MAX,-FLT_MAX)) < 0.001f)`

Since well, the code is effectively trying to do a square of FLT_MAX when next window position is 0,0 , which results in that function returning inf with exceptions disabled, but on platforms where the exceptions are enabled it leads to a crash.

I think it's just trying to find out if someone passed in FLT_MAX as the window size, but doing it this way definitely results in float overflow when you pass in anything other than FLT_MAX.

It seems to be an very specific edge case so I got around it by deleting the ImLengthSqr call, but I think a better solution could be found? 

To reproduce, call this before using any ImGUI code(on Windows):

`_clearfp();
		_controlfp_s(
			(unsigned int)NULL,
			(unsigned int)~(_EM_OVERFLOW),
			(unsigned int)MCW_EM);`

**Comment by ocornut** [comment]
Hello,
AFAIK that line was removed from the code, which version are you using?

**Comment by gambiting** [comment]
Hi,

Thanks for replying! You're right, the line appears gone from the latest version - it must have been fixed relatively recently as I've grabbed latest just few weeks ago. Sorry for the trouble!
