### ISSUE TITLE
Toggle between checkboxes 

### ISSUE THREAD

**Issue by PixelClear** [ocornut/imgui#1354]
hi 

I have two checkboxes I want to toggle between them.
When one is checked other should be disabled.
Currently I am doing it like this .

`renderingloop
{

 if (ImGui::Checkbox("Feature Tracker Module", &dummy[5]))
    {
        featureTrackerSelected = !featureTrackerSelected;
        ekfModuleSelected = false;
        dummy[6] = false;
        ImGui::SameLine();
    }
    else if (ImGui::Checkbox("EKF Module", &dummy[6]))
    {
        ekfModuleSelected = !ekfModuleSelected;
        featureTrackerSelected = false;
        dummy[5] = false;
        ImGui::SameLine();
    }

}`

But I see CheckBoxFlag() function. So I am wondering is there better way to achieve this than what I am doing. Unfortunately I did not see any example usage of this function.

How I can do this ?

Regards
PixelClear

**Comment by johanwendin** [comment]
The functionality you're after is usually handled via a RadioButton.
(see https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L278 )

Would that work for you?
(you could use a static int and then switch on its value to set your variables accordingly)

**Comment by ocornut** [comment]
You can replace all the state you are carrying, `featureTrackerSelected`, `ekfModuleSelected`, `dummy[]` with a single enum value.

`enum Module
{
   Module_FeatureTracker
   Module_XXX,
   Module_YYY,
};

if (RadioButton("Feature Tracker Module", current_module == Module_FeatureTracker)) 
   current_module = Module_FeatureTracker;`
etc.
