### ISSUE TITLE
Mouse up when MenuItem is clicked

### ISSUE THREAD

**Issue by haferburg** [ocornut/imgui#1355]
I have a popup menu with BeginPopup and MenuItem. MenuItem returns true on the mouse down event, but ImGUI doesn't eat the corresponding mouse up. So the mouse up ends up triggering events that I didn't intend to trigger (select/deselect objects in my editor). I'm wondering how to deal with that. Is it a bug? How can I work around it?

Observation: In Windows, the popup menu ignores mouse down within the menu rect, and only does something on mouse up. Mouse down outside the rect hides the popup, and the mouse down is propagated to whatever is under the mouse. I believe mouse down in general is only ever used to start a drag. For clicking, only the mouse up is used.

**Comment by ocornut** [comment]
Hello,
Are you on latest?
I think if you update your copy of imgui to latest, you'll find this behavior has been changed already. There was indeed that bug on master (but not in the Navigation branch), and the fix was merged 11 days ago.

**Comment by haferburg** [comment]
Hi there! :)
No, I'm not, I'm on 1.51. Sorry for not mentioning it. Thank you for letting me know.
