### ISSUE TITLE
_NoTreePushOnOpen on CollapsingHeader

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#1356]
Hi,

I am not understanding how to remove _NoTreePushOnOpen flag programatically. Perhaps you mean that code can be changed to remove it from
```
return TreeNodeBehavior(window->GetID(label), flags | ImGuiTreeNodeFlags_CollapsingHeader | ImGuiTreeNodeFlags_NoTreePushOnOpen, label);
```
thanks
victor

**Comment by ocornut** [comment]
Hello,

Why do you need to remove it?
You can always call TreePush() yourself.

**Comment by sonoro1234** [comment]
I need it to resolve conflicts between equal labels inside different CollapsingHeaders.
I have used PushID PopID to solve it (I dont want to indent)

Thanks

**Comment by ocornut** [comment]
So it looks like you have already solved your problem?

**Comment by sonoro1234** [comment]
Yes, Thankyou very much for attention
