### ISSUE TITLE
Child acting really weird.

### ISSUE THREAD

**Issue by csAlphyy** [ocornut/imgui#1357]
Hello, So today I tried to implement Sidebar tabs into my ImGui Project. It worked all fine, but when it came to the Child, Instead of it being aligned at the top, it decides to go to the bottom. Any help? This is what Is happening:
![nuo5rbl](https://user-images.githubusercontent.com/31821288/31310885-456f6630-ab98-11e7-9c5a-c6914c445e52.png)

This is my Code of the tabs:
`			
static int Menu_Tab = 0; 1; 2; 3; 4;

			if (ImGui::Button("  AIMBOT  ")) Menu_Tab = 0;
			ImGui::Spacing();
			ImGui::Spacing();
			ImGui::Spacing();
			if (ImGui::Button("  VISUAL  ")) Menu_Tab = 1;
			ImGui::Spacing();
			ImGui::Spacing();
			ImGui::Spacing();
			if (ImGui::Button("   SKIN   ")) Menu_Tab = 2;
			ImGui::Spacing();
			ImGui::Spacing();
			ImGui::Spacing();
			if (ImGui::Button("   MISC   ")) Menu_Tab = 3;
			ImGui::Spacing();
			ImGui::Spacing();
			ImGui::Spacing();
			if (ImGui::Button("   CFGS   ")) Menu_Tab = 4;

			ImGui::SameLine();
			ImGui::SameLine();

			float SpaceLineOne = 120.f;
			float SpaceLineTwo = 220.f;
			float SpaceLineThr = 320.f;

			if (Menu_Tab == 0) // Aimbot Tab
			{	
				DrawAimbotTab();
			}
			else if (Menu_Tab == 1) // Visuals Tab
			{
				DrawEspTab();
			}
			else if (Menu_Tab == 2) // SkinsTab
			{
				DrawSkinTab();
			}
			else if (Menu_Tab == 3) // MiscTab
			{
				DrawMiscTab();
			}
			else if (Menu_Tab == 4) // Config
			{
				DrawConfigTab();
			}
`

And this is one of my voids (the first tab)
`	
void DrawAimbotTab()
	{
		
		ImGui::BeginChild("AIMBOT", ImVec2(457, 125), true);

		ImGui::Text("AIMBOT");

		ImGui::PushItemWidth(110.f);
		ImGui::Text("WEAPON: ");
		ImGui::SameLine();
		ImGui::Combo("##AimWeapon", &iWeaponID, pWeaponData, IM_ARRAYSIZE(pWeaponData));
		ImGui::PopItemWidth();

		ImGui::Spacing();
		//ImGui::Separator();
		ImGui::Spacing();

		ImGui::Checkbox("ACTIVE", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_Active);

		ImGui::PushItemWidth(362.f);
		ImGui::SliderInt("FOV", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_Fov, 1, 300);
		ImGui::SliderInt("SMOOTHING", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_Smooth, 1, 300);
		ImGui::PopItemWidth();

		const char* Aimspot[] = { "HEAD" , "NECK" , "LOWER NECK" , "BODY" , "THORAX" , "CHEST", "STOMACH" };
		ImGui::PushItemWidth(362.f);
		ImGui::Combo("AIMSPOT", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_Spot, Aimspot, IM_ARRAYSIZE(Aimspot));
		ImGui::PopItemWidth();

		const char* AimFovType[] = { "ON PLAYER" , "STATIC" };
		ImGui::PushItemWidth(362.f);
		ImGui::Combo("FOV TYPE", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_FovType, AimFovType, IM_ARRAYSIZE(AimFovType));
		ImGui::PopItemWidth();

		ImGui::PopItemWidth();

		ImGui::Spacing();
		//ImGui::Separator();
		ImGui::Spacing();

		ImGui::PushItemWidth(362.f);
		ImGui::SliderInt("DELAY", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_Delay, 0, 200);
		ImGui::SliderInt("RCS", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_Rcs, 0, 100);
		ImGui::PopItemWidth();

		ImGui::Spacing();
		//ImGui::Separator();
		ImGui::Spacing();

		if (iWeaponID >= 10 && iWeaponID <= 30)
		{
			ImGui::PushItemWidth(362.f);
			ImGui::SliderInt("RCS FOV", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_RcsFov, 1, 300);
			ImGui::SliderInt("RCS SMOOTHING", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_RcsSmooth, 1, 300);
			ImGui::PopItemWidth();

			const char* ClampType[] = { "ALL TARGETS" , "SHOT" , "SHOT + TARGET" };
			ImGui::PushItemWidth(362.f);
			ImGui::Combo("RCS CLAMPING", &Settings::Aimbot::weapon_aim_settings[iWeaponID].aim_RcsClampType, ClampType, IM_ARRAYSIZE(ClampType));
			ImGui::PopItemWidth();
		}
		ImGui::EndChild();
	}
`

Any ideas? Thanks for the help :)

**Comment by csAlphyy** [comment]
//Solved

**Comment by paulsapps** [comment]
Thanks for explaining exactly what the issue is and how to solve it so that this is at least some use to others... [END OF SARCASM].

:)

**Comment by ocornut** [comment]
When child are acting really weird I would say the first step is to talk to them.
