### ISSUE TITLE
Changing tabs on the main window from a new window.

### ISSUE THREAD

**Issue by csAlphyy** [ocornut/imgui#1358]
(Sorry for my bad English, It isn't my primary language.)

So, lately I've tried to do something like this (this isn't mine, but that's what im trying to do.):
![xdriaab](https://user-images.githubusercontent.com/31821288/31321931-64cefd54-ac85-11e7-9f5f-4e657767b06e.png)

Once the buttons underneath the main menu are clicked, the specific tab show on the main menu. Is there a possible way of giving me information (not spoonfeeding me the code) of how would I go about doing this? I can't get my head around this. 
Thank you for any help. :)

**Comment by ocornut** [comment]
I'm sorry this isn't really a dear imgui related question, please try to ask on a general programming discussion forum.
