### ISSUE TITLE
Dragging the window while mouse is inside the ImGui::BeginChild();

### ISSUE THREAD

**Issue by csAlphyy** [ocornut/imgui#1359]
Pretty much the title. It's kind of annoying, as I'm working on a project w/o a title bar, and It's hard to drag it around (It's very small.)
If this is an option, Then could I please know how to activate?

Thank you. :)

**Comment by ocornut** [comment]
It's already possible in the last version (unless you passed the `_NoMove` flag to your child window creation). There was a bug in 1.51 which prevented it.
