### ISSUE TITLE
ImGui::GetColumnOffset() assert when a child region is not visible

### ISSUE THREAD

**Issue by Roflraging** [ocornut/imgui#136]
Hey Omar,

I've been doing some more work recently with some of my tools that make extensive use of columns.  In an attempt to do some work on setting column offsets, I ran into an assert:

```
dalekim1@lispy:/home/dalekim1/imgui/examples/opengl_example [upstream]> ./imgui_example 
imgui_example: ../../imgui.cpp:6303: float ImGui::GetColumnOffset(int): Assertion `column_index < (int)window->DC.ColumnsOffsetsT.size()' failed.
Aborted
```

The code to reproduce:

```
ImGui::Begin("Column index assert: DRAG ME DOWN OFF SCREEN (or make window small!)", NULL, ImVec2(400.0f, 400.0f));
ImGui::Text("Taking up space...");
ImGui::Text("Taking up space...");
ImGui::Text("Taking up space...");
ImGui::Text("Taking up space...");

static int columns = 3;
ImGui::BeginChild("child");
ImGui::Columns(columns);

for (int i = 0; i < columns; ++i)
{
    ImGui::GetColumnOffset(i);
}

ImGui::EndChild();
ImGui::End();
```

My preliminary investigation shows that the function ImGui::Columns() bails out early because of the `if (window->SkipItems)` test at the beginning of the function.  This prevents the window->DC.ColumnsOffsetT from being resized later on at the end of the function, which eventually lets ImGui::Get/SetColumnOffset() run into the assert and explode.

-Dale Kim

**Comment by ocornut** [comment]
Alright, Columns() bailing out is probably incorrect here. Let me investigate a little.

**Comment by ocornut** [comment]
Removed the bailing it was incorrect. Applied some other optimizations (BeginChild inherit Collapsed state from parent).

From a user perspective when Begin or BeginChild return false you can avoid submitting the content (but you still need to call End/EndChild). I have just added the return value to BeginChild which was previously missing.
