### ISSUE TITLE
IsWindowFocused() return false for all windows

### ISSUE THREAD

**Issue by djdeath** [ocornut/imgui#1361]
Hi,

I'm trying to implement a Alt-Tab kind of behavior to move across the windows my application is creating.
I've noticed something odd, While redrawing my windows, with the following code : 

```
ImGui::IsRootWindowFocused(); -> false

window = windows;
while (window) {
  ImGui::Begin(window->name);
  ImGui::IsWindowFocused(); -> false
  window = window->next;
}
```
It seems to happen once you click within a child. Clicking again outside a child will make IsWindowFocused(); again.
I'm not sure whether that's the intended behavior or just a bug.

**Comment by ocornut** [comment]
I'm not 100% sure I understand your description, but as I understand it that's exactly the intended behavior. You might want to use `IsRootWindowOrAnyChildFocused()`.

CTRL-Tab will eventually be supported by the Navigation branch as well.

**Comment by djdeath** [comment]
Is there anyway to tell whether a window or any of its children is focused?

**Comment by ocornut** [comment]
Err, that's what I have just posted.

**Comment by djdeath** [comment]
Oh sorry... I failed to register that RootWindow is a normal window  :(
Confused with the X11 semantic where RootWindow is the back of the screen (when there are no windows).

**Comment by ocornut** [comment]
I also just realized that may be confusing. I'll see if I can tweak some of the comments accordingly.

**Comment by djdeath** [comment]
Gtk+ uses toplevel if it helps.

**Comment by djdeath** [comment]
Otherwise your suggestion works :) Thanks again!

**Comment by ocornut** [comment]
Closing this. Note that the header file explains what a "root window" is.
I will rework those function soon-ish, similarly to what I did with `IsItemHovered`/`IsWindowHovered` (see #1382), `IsWindowFocused()` should become full featured with flags to specific how to report focus in regards to child or parent parents.
