### ISSUE TITLE
ImGuiWindowFlags_AlwaysAutoResize + Columns

### ISSUE THREAD

**Issue by john-chapman** [ocornut/imgui#1363]
In version 1.52 the behavior of `ImGuiWindowFlags_AlwaysAutoResize` has changed when using columns to arrange widgets - it looks like the auto resize doesn't account for the columns. This was working in version 1.50:
```
ImGui::Begin("foo", 0, ImGuiWindowFlags_AlwaysAutoResize);
   ImGui::Columns(4);
       // blah blah
   ImGui::Columns(1);
ImGui::End();
```
But in 1.52 looks like this:
![pasted_image_at_2017_10_10_10_20_am_360](https://user-images.githubusercontent.com/5657483/31379826-bc92165e-adaf-11e7-8658-abc8cc172115.png)

**Comment by ocornut** [comment]
Columns use the available space (which you may force adjust with eg: SetCursorPosX or SetNextWindowContentsSize), they don't yet feed back their contents back into the window contents size.

Previously there was a bug which made only the last column declare its space outside the columns set, which would tends to make your use case non-zero width but still rather incorrect.

At the moment unfortunately the only solutions are either to grow the width yourself or ditch the AutoResize flag.

**Comment by ihamer** [comment]
Can you elaborate on "grow the width yourself"? I would like to try implementing this.

**Comment by ocornut** [comment]
Just call SetCursorPosX() to do that.

**Comment by L-P** [comment]
Had the same problem, fixed it by specifying a constant width:

```c++
ImGui::SetNextWindowSizeConstraints({230, -1}, {230, -1});
ImGui::Begin("SomeWindowWithTextColumns", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
```

This will set the height automatically and keep the width fixed. Not ideal but it works.

`SetNextWindowContentSize` did not work with a height of 0.f as it should per stated in the documentation, only `SetNextWindowSizeConstraints` with a height of -1 correctly adjusts the window height.

As the text shown has a constant width, this worked for me.

**Comment by ocornut** [comment]
> SetNextWindowContentSize did not work with a height of 0.f as it should per stated in the documentation, 

This is a bug introduced in eab6333a0b96bd30413bb17408303a5df438ffde, pushed a fix now. Thanks.

Test:
```
ImGui::SetNextWindowContentSize(ImVec2(400, 0.0f));
ImGui::Begin("Test #1363", NULL, ImGuiWindowFlags_AlwaysAutoResize);
ImGui::Columns(4);
ImGui::Text("column 0");
ImGui::Text("blah blah");
ImGui::Columns(1);
ImGui::End();
```
![image](https://user-images.githubusercontent.com/8225057/35393599-b2081104-01e5-11e8-87e4-82bd17aaf7c5.png)

**Comment by ocornut** [comment]
Closing this as Columns are a Legacy feature.
Tables are reporting their contents so auto-sizing of a Parent Window carrying a Table should work.
