### ISSUE TITLE
Render strings

### ISSUE THREAD

**Issue by Barashuk** [ocornut/imgui#1364]
Hey. How can I render lines without "\n", but at the same location by X. Just for the line "Name Surname" and "Last Message" you need to use different fonts.
With "\n"
```
ImGui::Image((void *)texture->pTexture, ImVec2(40, 40));
ImGui::SameLine();
ImGui::Text("Name Surname\nLast Message");
```
![1](https://user-images.githubusercontent.com/8094947/31430492-ac741f18-ae79-11e7-867c-20a2897e8b00.png)
Without "\n"
```
ImGui::Image((void *)texture->pTexture, ImVec2(40, 40));
ImGui::SameLine();
ImGui::Text("Name Surname");
ImGui::Text("Last Message");
```
![2](https://user-images.githubusercontent.com/8094947/31430493-ac98dcb8-ae79-11e7-8784-ce4927af6276.png)

**Comment by ocornut** [comment]
In the absence of an easier way to lock the starting X position, this is what `BeginGroup()/EndGroup()` is doing. 
`Image() / SameLine() / BeginGroup() / Text() / Text() / EndGroup()`

**Comment by Barashuk** [comment]
Thanks, man. There are 2 more questions. How can I render the text at the right edge of the current window or group and can I render a rectangle with its own sizes through the imgui?

**Comment by dpethes** [comment]
For rectangles try ImDrawList's AddRect or AddRectFilled.

**Comment by ocornut** [comment]
@Barashuk : If you want to right-align text you need to position it yourself.
