### ISSUE TITLE
Font not changing.

### ISSUE THREAD

**Issue by csAlphyy** [ocornut/imgui#1366]
So, I've tried to change the font by doing so:

ImGuiIO& io = ImGui::GetIO();
io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Courier New.ttf", 25.0f);

Which i expected to do the job with no problems. But I was wrong, - The font does not change at all, and I'm not sure why. I put that where my menu opens, So ImGui::Begin{
(font parameters)
}.

Any help to as why this is happening? Much thanks :)

**Comment by ocornut** [comment]
Read about string escaping in c++!

**Comment by ocornut** [comment]
Also use a debugger and trace execution inside the function to find out what's wrong.
