### ISSUE TITLE
ImGui::BeginChild() with specified size extends past window for interactions

### ISSUE THREAD

**Issue by Roflraging** [ocornut/imgui#137]
I was doing some moving of my windows around and noticed a case where I was grabbing a window when the mouse wasn't inside the graphical area of the window.

Code is basically like this:

```
ImGui::Begin("Child too large");

ImGui::Text("Resize window to be small, then click and drag just outside window border.");
ImGui::BeginChild("too big", ImVec2(600.0f, 600.0f));
ImGui::EndChild();

ImGui::End();
```

Should I be clamping the child size myself to the window size?

-Dale Kim

**Comment by ocornut** [comment]
Definitively a bug if that happens. I'll look into it tomorrow. The area rectangles are normally clipped by the parent area (and generally parent window padding).

Note that you can pass a (0,0) for fit all or a negative value to align from the right or lower edge. Works on both axis independently.
