### ISSUE TITLE
InputTextMultiline() and IsItemHovered()

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#1370]
Hi.
I'm not sure if something's changed or if it's a bug, but it seems that IsItemHovered() doesn't work anymore with InputTextMultiline() (no tooltip shows up).
With single line input text everything seems to work.

```c++
static char bfr[128]="Hello!";
ImGui::InputTextMultiline("IsItemHovered() Test",bfr,128);
if (ImGui::IsItemHovered()) ImGui::SetTooltip("%s","Hovered!");
```

**Comment by ocornut** [comment]
Thanks, will look at it. Are you on Master or Nav branch?

**Comment by Flix01** [comment]
Yes, that's probably the commit that caused the issue.
I'm on the Master branch.

**Comment by ocornut** [comment]
I don't have a satisfying solution just yet, so for now I have reverted that changes and added notes about it.  So this is fixed here.

**Comment by Flix01** [comment]
Thanks.
