### ISSUE TITLE
Clip Rect bug

### ISSUE THREAD

**Issue by midnite8177** [ocornut/imgui#1372]
I found a series of steps will create incorrect rendering. I traced back the issue to commit 0873da85ecab9c4074d493dc232adc885f35a008 (Dec 15, 2015).

Here is how to reproduce:
1) Grab 'dear imgui' extract 
2) Inject the following snippet of code into imgui_demo.cpp before the line:
`if (ImGui::TreeNode("Grid"))`
this code:
`            if (ImGui::TreeNode("In columns"))`
`            {`
`                ImGui::Columns(3, NULL, false);`
`                static bool selected[16] = { 0 };`
`                for (int i = 0; i < 16; i++)`
`                {`
`                    char label[32]; sprintf(label, "Item %d", i);`
`                    if (ImGui::Selectable(label, &selected[i])) {}`
`                    ImGui::NextColumn();`
`                }`
`                ImGui::Columns(1);`
`                ImGui::TreePop();`
`            }`

3) build the directx11_example
4) Run the example and follow these given input steps on the "ImGui Demo" window to reproduce:
   a) Expand "Widgets"
   b) Expand "Word Wrapping"
   c) Expand "Selectables"
   d) Expand "In columns" under "Selectables"
   e) Expand "Filtered Text Input"
5) Now using the mouse wheel, scroll down the demo window. You'll notice when you get to the "Value" section, widgets start dropping out / get clipped.

I have reproducible steps for the latest code in GitHub, but thought I would give you repro steps for the commit where the bug seems to have appeared.

See attached screenshot.

![imgui](https://user-images.githubusercontent.com/5049035/31635355-061c98c2-b28c-11e7-8e51-162f28b446e8.PNG)

**Comment by midnite8177** [comment]
Actually - I think this just got fixed in the last day or two. Ha!

**Comment by ocornut** [comment]
Yes it just got fixed yesterday :) see this post 
https://github.com/ocornut/imgui/issues/1172#issuecomment-336734722
Sorry you had to spend time studying this!
