### ISSUE TITLE
Imgui::ShowTestWindow()

### ISSUE THREAD

**Issue by eue398** [ocornut/imgui#1373]
So when I try using that in my c++ internal cheat game menu I get an error

1>Menu.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::ShowTestWindow(bool *)" (?ShowTestWindow@ImGui@@YAXPA_N@Z)

**Comment by ocornut** [comment]
You need to compile/link imgui_demo.cpp into your application. This is a generic c++ issue that's unrelated to dear imgui, please look on general programming forums for those questions/answers.
