### ISSUE TITLE
Drag and Drop Parenting

### ISSUE THREAD

**Issue by Bonicx** [ocornut/imgui#1374]
Hi I would like to know if drag and drop parenting could be done without any collision/AABB methods to achieve something like https://docs.unity3d.com/Manual/Hierarchy.html

**Comment by ocornut** [comment]
Hello,

Please clarify the questiom, as I'm not really sure what you are trying to do.

Also linking to 
https://github.com/ocornut/imgui/issues/143

**Comment by Bonicx** [comment]
https://youtu.be/a2FY0fMuxvE
Using unity as an example.
Creating a child of a gameobject by dragging it to another object and making to the parent gameobject

**Comment by ocornut** [comment]
It's not really a first class citizen in the library (yet), but you can manually achieve those things with extra code. See the thread I linked above.

**Comment by ngminteck** [comment]
this what i want to implement
 https://github.com/ocornut/imgui/issues/2209

**Comment by ocornut** [comment]
Closing as old/duplicate, there are existing implementation for that.
