### ISSUE TITLE
CheckBox() with a tick mark

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#1378]
I have changed the checkbox to use a check mark instead of a plain square. I'm not sure why I haven't done that before. I know some of you {@dougbinks?) were using their own just to get that.

![image](https://user-images.githubusercontent.com/8225057/31716222-21db56d0-b407-11e7-9986-77acfe24f21d.png)

![checkboxes](https://user-images.githubusercontent.com/8225057/31716243-3f36cf84-b407-11e7-819e-8ed9708ef2d8.PNG)

At different scale:

![image](https://user-images.githubusercontent.com/8225057/31716179-f035d574-b406-11e7-93b8-b1fc3bcdfd6d.png)

![image](https://user-images.githubusercontent.com/8225057/31716210-10f04344-b407-11e7-9f05-39547fe6a8cc.png)

Additionally the tick mark used for MenuItem() is also now a little thicker.

I am only creating this thread to let people know. Will close thread in a few days. 
I can't imagine anyone being unhappy with but if you are, let me know!

**Comment by dougbinks** [comment]
Nice work, thank you I was using a font based workaround to add a check - the default wasn't easily parsed by some people.

**Comment by ebachard** [comment]
Nice feature !  Thank you very much ! 

BTW, testing your code, I got this warning: 
  src/3rdparty/imgui/imgui.cpp: In function ‘void ImGui::RenderCheckMark(ImVec2, ImU32, float)’:
   
 src/3rdparty/imgui/imgui.cpp:3011:19: warning: unused variable ‘g’ [-Wunused-variable]
       ImGuiContext& g = *GImGui;'''

Got it fixed removing the line above ( arounf line 3009) in imgui.cpp. This is probably related to https://github.com/ocornut/imgui/commit/bf778ebb7edd73176c76469eb7869e56854c16d3

**Comment by ocornut** [comment]
I don't understand @ebachard it's not in the current code and the line numbers don't match. The committed `RenderCheckMark` uses g to access `g.CurrentWindow`.

**Comment by ebachard** [comment]
Maybe I something wrong, sorry. To tell you more, I directly picked your change from the commit I mentionned above, and after I adapted your changes to my current code, here is what I got:

    void ImGui::RenderCheckMark(ImVec2 pos, ImU32 col, float sz)
    {
        //ImGuiContext& g = *GImGui;
        ImGuiWindow* window = GetCurrentWindow();

      float thickness = ImMax(sz / 5.0f, 1.0f);
      sz -= thickness*0.5f;
      pos += ImVec2(thickness*0.25f, thickness*0.25f);
  
      float third = sz / 3.0f;
      float bx = pos.x + third;
      float by = pos.y + sz - third*0.5f;
      window->DrawList->PathLineTo(ImVec2(bx - third, by - third));
      window->DrawList->PathLineTo(ImVec2(bx, by));
      window->DrawList->PathLineTo(ImVec2(bx + third*2, by - third*2));
      window->DrawList->PathStroke(col, false, thickness);
  }

And it seems to work well here, without the need of the context (at least in the code above)

**Comment by ebachard** [comment]
![checkmark_test 1378](https://user-images.githubusercontent.com/23149049/31719838-003ecc9c-b415-11e7-8595-efd941905152.png)

A screenshot, to illustrate.

**Comment by ocornut** [comment]
You should use git facilities to merge code and not merge manually, this is only going to create more troubles for you.

(PS: when you have a new app please try to post screenshots in the gallery threads too ;)

**Comment by ebachard** [comment]
You're right, I really need to learn deeply git facilities :-)

Of course, when It willl be ready, I'll post screenshots + the style I'm using and more. Waiting, I added ImGui in the list of ressources (see my miniDart repository on my github account, and you'll understand what I mean)

**Comment by Flix01** [comment]
@ocornut I prefer tick marks too (adding a new style variable for it would probably be too much...).
Perhaps now checked radio buttons look too big compared to tick marks (or it's just my impression?)

**[OT]** I was about asking a way to check/uncheck multiple MenuItems without closing/reopening the Menu every time, but I've quickly found an easy way to do it:
```c++
            // Just a test to check/uncheck multiple checkItems without closing the Menu (with the RMB)
            static bool booleanProps[3]={true,false,true};
            static const char* names[3]={"Boolean Test 1","Boolean Test 2","Boolean Test 3"};
            const bool isRightMouseButtonClicked = ImGui::IsMouseClicked(1);    // cached
            for (int i=0;i<3;i++)   {
                ImGui::MenuItem(names[i], NULL, &booleanProps[i]);
                if (isRightMouseButtonClicked && ImGui::IsItemHovered()) booleanProps[i]=!booleanProps[i];
            }
```
... just in case someone is interested...

**Comment by ocornut** [comment]
(Offtopic is offtopic please move it to another thread)

**Comment by Bonicx** [comment]
@ocornut I tried the style editor changed the color but the save button did not appear 
Code is at the demo.cpp  
line 1930 -> if (ref) { ImGui::SameLine(); if (ImGui::Button("Save")) ref->Colors[i] = style.Colors[i]; }
