### ISSUE TITLE
Basic use of IMGUI inside SDL program.

### ISSUE THREAD

**Issue by piluve** [ocornut/imgui#138]
Hello;

First I have to say that this project looks awesome and it is free so that is just amazing...

I am having some trouble setting up IMGUI with my SDL application.

First I will show which code I am using to configure the thing:

INIT IMGUI:
```
ImGuiIO& io = ImGui::GetIO();
  io.RenderDrawListsFn = ImImpl_RenderDrawLists;
  io.DisplaySize.x = 900.0f;
  io.DisplaySize.y = 600.0f;
  io.DeltaTime = 1.0f / 60.0f;
  unsigned char* pixels;
  int width, height, bytes_per_pixels;
  io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height, &bytes_per_pixels);
```

Render draw Listn fn

```
static void ImImpl_RenderDrawLists(ImDrawList** const cmd_lists, int cmd_lists_count)
{
  if (cmd_lists_count>0)
    std::cout << cmd_lists[0]->vtx_buffer.at(0).col << std::endl;
}
```

UPDATE IMGUI
```
 ImGuiIO& io = ImGui::GetIO();
  ImGui::NewFrame();
  ImGui::Begin("My window");
  ImGui::Text("Hello, world.");
  ImGui::End();
```

With that my program compiles and executes with no errors/logs but I can´t see anything.

I am not sure whats wrong with it I am quite noob with this type of things.

See you!

**Comment by Roflraging** [comment]
You need to actually implement the rendering function in ImImpl_RenderDrawLists().  I use imgui in a game I'm working on and we literally just copied the implementation from the opengl_example.  You should be able to do the same.

Right now all you do is print out the first element of the commands, but don't do any drawing at all!

**Comment by piluve** [comment]
In that func I see many things, do I have to use all that?

**Comment by Roflraging** [comment]
It isn't that much, really.  Are you familiar with graphics programming?

That example rendering function is pretty minimal and does everything necessary to render imgui correctly.  Basically it saves off some of the OpenGL state that the application might have set, then starts to modify it for its own use.  Then it submits all the vertex, texture, and scissoring information for OpenGL to draw with.

Then it resets the GL state at the end before the function ends.

**Comment by piluve** [comment]
RIght now I am learning Opengl and 3d graphics programming so for me thats quite new :D , I think that I understan more or less that func, it just set the rendering pipeline for the IMGUI or something like that -_-

**Comment by piluve** [comment]
The thing is , do I need all that array of code or there are some parts that are not necesary?

**Comment by ocornut** [comment]
You need the entire function, you can copy the one from the OpenGL2 example :)

**Comment by piluve** [comment]
Then I will try that!

**Comment by piluve** [comment]
I´ve spend all the moorning trying to set up OpgelGl(GLEW+GLFW) and finally got all that working, I just tested a basic sample of and opengl program where I open a window and draw a background and all works nice!

But now I copy and paste the sample code for opengl (imgui one) and... PUM! errors :c

´´´
     1>main.obj : error LNK2001: unresolved external symbol ___glewActiveTexture
     1>main.obj : error LNK2001: unresolved external symbol ___glewBlendEquation
     1>main.obj : error LNK2001: unresolved external symbol ___glewBindBuffer
     1>main.obj : error LNK2001: unresolved external symbol ___glewBufferData
     1>main.obj : error LNK2001: unresolved external symbol ___glewDeleteBuffers
     1>main.obj : error LNK2001: unresolved external symbol ___glewGenBuffers
     1>main.obj : error LNK2001: unresolved external symbol ___glewMapBuffer
     1>main.obj : error LNK2001: unresolved external symbol ___glewUnmapBuffer
     1>main.obj : error LNK2001: unresolved external symbol ___glewAttachShader
     1>main.obj : error LNK2001: unresolved external symbol ___glewCompileShader
     1>main.obj : error LNK2001: unresolved external symbol ___glewCreateProgram
     1>main.obj : error LNK2001: unresolved external symbol ___glewCreateShader
     1>main.obj : error LNK2001: unresolved external symbol ___glewDeleteProgram
     1>main.obj : error LNK2001: unresolved external symbol ___glewDeleteShader
     1>main.obj : error LNK2001: unresolved external symbol ___glewDetachShader
     1>main.obj : error LNK2001: unresolved external symbol ___glewEnableVertexAttribArray
     1>main.obj : error LNK2001: unresolved external symbol ___glewGetAttribLocation
     1>main.obj : error LNK2001: unresolved external symbol ___glewGetUniformLocation
     1>main.obj : error LNK2001: unresolved external symbol ___glewLinkProgram
     1>main.obj : error LNK2001: unresolved external symbol ___glewShaderSource
     1>main.obj : error LNK2001: unresolved external symbol ___glewUniform1i
     1>main.obj : error LNK2001: unresolved external symbol ___glewUniformMatrix4fv
     1>main.obj : error LNK2001: unresolved external symbol ___glewUseProgram
     1>main.obj : error LNK2001: unresolved external symbol ___glewVertexAttribPointer
     1>main.obj : error LNK2001: unresolved external symbol ___glewBindVertexArray
     1>main.obj : error LNK2001: unresolved external symbol ___glewDeleteVertexArrays
     1>main.obj : error LNK2001: unresolved external symbol ___glewGenVertexArrays
     1>main.obj : error LNK2001: unresolved external symbol _glewExperimental
´´´

Linker errors !!!

Any idea of whats wrong?

Thx!

**Comment by ocornut** [comment]
The sample code uses statically compiled GLEW (without DLL)

```
#define GLEW_STATIC
#include <GL/glew.h>
```

So either remove #define GLEW_STATIC from the example code.
Or link with glew32s.lib (static version) instead of glew32.lib (dll version)

**Comment by piluve** [comment]
:dart: 
Oh men :D It works!
Now It is time to work!

**Comment by ocornut** [comment]
Good luck :)

We will try to provide a SDL example eventually (there is one submitted as a Pull Request but it is a little old, need one or two tweaks).
