### ISSUE TITLE
You can move a NoMove window...

### ISSUE THREAD

**Issue by tom-seddon** [ocornut/imgui#1381]
In `ImGui::EndFrame`, the hovered window's flags are checked when the mouse is down, so that if the `NoMove` flag is set, it won't go into move mode. But in `ImGui::NewFrame`, it's the hovered window's root window that gets moved. So shouldn't the root window's `NoMove` flag be checked too?

This feels like a bug, because makes it harder than necessary to create an immovable window. (I came across this problem using the Lumix docking stuff, which creates its own internal window that *doesn't* have the `NoMove` flag set.) But perhaps there's something I'm missing.

Thanks,

--Tom

**Comment by ocornut** [comment]
Looks like a bug indeed, its possible the fix recently applied for https://github.com/ocornut/imgui/issues/1337 broke this. 

Will look into it.

**Comment by ocornut** [comment]
Fixed, and also fixed another bug, which repro was:

```
ImGui::Begin("Bug #1381", NULL, 0);
ImGui::Text("Root");
ImGui::BeginChild("Child1", ImVec2(0, 0), true, ImGuiWindowFlags_NoMove);
ImGui::Text("Child1");
ImGui::BeginChild("Child2", ImVec2(0, 0), true);
ImGui::Text("Child2");
ImGui::EndChild();
ImGui::EndChild();
ImGui::End();
```

The flag is now inherited so you cannot move the root window by click-dragging on Child2.
