### ISSUE TITLE
IsItemHovered(), IsWindowHovered() improvements

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#1382]
(This is a news/info post. Will close in a few days)

I have pushed a bunch of changes related to the IsItemHovered() and IsWindowHovered() functions, in the form of new flags. 

This is interesting to know:
- If you are using mouse-triggered popups (~context menus) this is also interesting.
- If you are using Drag'n Drop related idioms (#143) in your code this will likely interest you, and might affect you.
- If you are using any other idioms related to hovering, most commonly when creating tooltip or displaying status based on hovered items.

Previously it was frequent to use `IsItemRectHovered`/`IsItemHoveredRect` (same function, was renamed on August 22) to do a basic rectangle-only test.

The existing normal functions now have flags to allow this and more, with better defined options:
```
bool IsItemHovered(ImGuiHoveredFlags flags = 0);
bool IsWindowHovered(ImGuiHoveredFlags flags = 0);
```

The flags are:
```
enum ImGuiHoveredFlags_
{
    ImGuiHoveredFlags_Default                       = 0,        // Return true if directly over the item/window, not obstructed by another window, not obstructed by an active popup or modal blocking inputs under them.
    ImGuiHoveredFlags_AllowWhenBlockedByPopup       = 1 << 0,   // Return true even if a popup window is normally blocking access to this item/window
    //ImGuiHoveredFlags_AllowWhenBlockedByModal     = 1 << 1,   // Return true even if a modal popup window is normally blocking access to this item/window. FIXME-TODO: Unavailable yet.
    ImGuiHoveredFlags_AllowWhenBlockedByActiveItem  = 1 << 2,   // Return true even if an active item is blocking access to this item/window
    ImGuiHoveredFlags_AllowWhenOverlapped           = 1 << 3,   // Return true even if the position is overlapped by another window
    ImGuiHoveredFlags_RectOnly                      = ImGuiHoveredFlags_AllowWhenBlockedByPopup | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem | ImGuiHoveredFlags_AllowWhenOverlapped
};
```

- This is particularly useful for contextual menu triggered from an item. The high-level `BeginPopupContextItem()` helper now uses the `ImGuiHoveredFlags_AllowWhenBlockedByPopup` flag meaning that you can right-click again on a different spot to reopen a context menu. (#439). Note that I also have committed another change that allows closing popups by right-clicking anywhere, making popups generally more usable.

- Those new options will make it easier/clearer to have finer controls on drag and drop related behaviour.
- If you use e.g. tooltip you can also have finer controls as to how when they should appear.

In the demo window you can visualize the output of those functions will different flags:

![hovered](https://user-images.githubusercontent.com/8225057/31837945-ff7f9800-b5da-11e7-9ea7-e023aebb0d25.png)
Above: normal hovering.

![hovered_allow_when_overlapped](https://user-images.githubusercontent.com/8225057/31837968-1570c40e-b5db-11e7-9366-bea5b7faeec5.png)
Above: Here the button is hidden by another window, but `IsItemHovered(ImGuiHoveredFlags_AllowWhenOverlapped)`/`RectOnly` call returns true as expected:

![hovered_allow_when_blocked_by_popup](https://user-images.githubusercontent.com/8225057/31838003-36b2b65e-b5db-11e7-826b-01897f633d63.png)
Above: Here there is an open popup (the color picker) which prevents from clicking the button "ITEM" (so it doesn't appear as hovered). The `IsItemHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup)` and `IsWindowHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup)` calls both returns true.

![hovered_allow_when_blocked_by_active](https://user-images.githubusercontent.com/8225057/31838060-71bf036a-b5db-11e7-8be0-bacfd43848a9.png)
Above: Here I have clicked on the DRAG ME button and click-dragged the mouse over the ITEM button. The `IsItemHovered(ImGuiHoveredFlags_AllowWhenBlockedByActiveItem)` returns true.

Hope it is clear, and useful!
I haven't worked out in details how those features may relate to parent-child window relationship, and I imagine we could introduce new flags there.

BREAKING CHANGES
- `IsItemHoveredRect/IsItemRectHovered` has been obsoleted, it is equivalent to calling: `IsItemHovered(ImGuiHoveredFlags_RectOnly)` aka all the flags enabled. I have kept an inline function doing that.
- On August 22 I renamed `IsItemHoveredRect` to `IsItemRectHovered` for consistency with other functions. Instead of keeping 2 legacy names, I have now completely removed the name introduced on August 22, since few people will have renamed it their code, and if they did they are likely to find their way through the new changes. So only the oldest legacy name persist and it will be obsoleted in a few months/years.

- Similarly, `IsWindowRectHovered()` has been obsoleted, the exact behavior that it had is equivalent to calling `IsWindowHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem)`.
- Similarly, on August 22 I renamed `IsMouseHoveringWindow` to `IsWindowRectHovered` and I have removed the most recently introduced name. So the oldest legacy name `IsMouseHoveringWindow` will persist for a few more months/years.

- `IsWindowHovered()` default behavior has been changed to return false if an item of another window is active. It makes the function more consistent and symmetrical with `IsItemHovered()` and I believe it is a better default and won't affect many people. You can call `IsWindowHovered(ImGuiHoveredFlags_AllowWhenBlockedByActiveItem)` to get the old behavior.
This will probably affect you if you were doing drag and drop across windows and using `IsWindowHovered`.

**Comment by Blaze349** [comment]
I now get these errors in the demo file:
```
src/imgui_demo.cpp:1776:40: error: use of undeclared identifier 'ImGuiHoveredFlags_AllowWhenBlockedByPopup'
                ImGui::IsWindowHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup),
                                       ^
src/imgui_demo.cpp:1777:40: error: use of undeclared identifier 'ImGuiHoveredFlags_AllowWhenBlockedByActiveItem'
                ImGui::IsWindowHovered(ImGuiHoveredFlags_AllowWhenBlockedByActiveItem));
                                       ^
src/imgui_demo.cpp:1788:38: error: use of undeclared identifier 'ImGuiHoveredFlags_AllowWhenBlockedByPopup'
                ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup),
                                     ^
src/imgui_demo.cpp:1789:38: error: use of undeclared identifier 'ImGuiHoveredFlags_AllowWhenBlockedByActiveItem'
                ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenBlockedByActiveItem),
                                     ^
src/imgui_demo.cpp:1790:38: error: use of undeclared identifier 'ImGuiHoveredFlags_AllowWhenOverlapped'
                ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenOverlapped),
                                     ^
src/imgui_demo.cpp:1791:38: error: use of undeclared identifier 'ImGuiHoveredFlags_RectOnly'
                ImGui::IsItemHovered(ImGuiHoveredFlags_RectOnly));
```

**Comment by Blaze349** [comment]
I mean the widgets

**Comment by ocornut** [comment]
Those enums are in imgui.h afaik so you must have messed up with something locally. Are you using stock imgui or did you modify or merge something manually?


Sent from my fax machine

**Comment by Blaze349** [comment]
What happened was that I downloaded the demo file but forgot to update the other files.

**Comment by ocornut** [comment]
Everyone who is using `IsWindowHovered()` : could you share your use cases of using the function? (code, pseudo-code, purpose, etc.)

The change described here introduced a bug that affects the console demo (see #1404, unable to open the right-click context menu while hovering the child window, because another widget is active). The fix for that one thing is easy but it led me to question exactly how `IsWindowHovered()` should behave when other items are active, and in particular in respect with where the active item is (within the window, outside, a child or a descendant?).

So seeing your usage patterns would be useful.
I already have those for references: https://github.com/nem0/LumixEngine/search?utf8=%E2%9C%93&q=IsWindowHovered&type=

**Comment by ocornut** [comment]
I have made the same transition for IsWindowFocused, which now has flags and can handle more cases:
```
bool ImGui::IsWindowFocused(ImGuiFocusedFlags flags = 0);
```
So essentially:
`IsRootWindowFocused()` 
becomes:
`IsWindowFocused(ImGuiFocusedFlags_RootWindow)`

`IsRootWindowOrAnyChildFocused()` 
becomes:
`IsWindowFocused(ImGuiFocusedFlags_RootAndChildWindows)`

In addition it's now possible to do:
`IsWindowFocused(ImGuiFocusedFlags_ChildWindows)`
Which wasn't possible before.

```
// Flags for ImGui::IsWindowFocused()
enum ImGuiFocusedFlags_
{
    ImGuiFocusedFlags_ChildWindows          = 1 << 0,   // IsWindowFocused(): Return true if any children of the window is focused
    ImGuiFocusedFlags_RootWindow            = 1 << 1,   // IsWindowFocused(): Test from root window (top most parent of the current hierarchy)
    ImGuiFocusedFlags_RootAndChildWindows   = ImGuiFocusedFlags_RootWindow | ImGuiFocusedFlags_ChildWindows,
};
```

Demo code:
![image](https://user-images.githubusercontent.com/8225057/33885872-f69dfab8-df44-11e7-8e0e-68bfba69c618.png)

**Comment by ocornut** [comment]
Closing this as solved.

**Comment by csp-admin** [comment]
Since I didnt find a way to change a text color on hover with my hand-made icon font  I did it myself

`bool IconButton(ImFont* font, const char* iconChar, ImVec4 iconColor, ImVec4 iconhoverColor, ImVec2 position, float size)
{
	ImGui::SetCursorPos(position);	
	ImVec2 mousePos = ImGui::GetMousePos() - ImGui::GetCurrentWindow()->Pos;

	//ConsolePrintColor(22, 222, 22, "mouse pos %f %f   pos x %f y  %f \n", mousePos.x, mousePos.y, position.x, position.y);

	ImGui::PushFont(font);
	if (mousePos.x >= position.x && mousePos.x <= position.x + size &&
		mousePos.y >= position.y && mousePos.y <= position.y + size)
	{
		ImGui::TextColored(iconhoverColor, iconChar);
		ImGui::PopFont();
		return true;
	}
	else
	{
		ImGui::TextColored(iconColor, iconChar);
		ImGui::PopFont();
		return false;
	}
}`
