### ISSUE TITLE
How to check if clip rects changed.

### ISSUE THREAD

**Issue by DynamicStatic** [ocornut/imgui#1383]
I'm new to ImGui, just getting it set up with Vulkan.

Is there a way to check if clip rects have changed since the last frame?

The reason I ask is because if the clip rects haven't changed, the command buffer used to render ImGui can be resubmitted without re-recording, however if the clip rects have changed the command buffer has to be re-recorded.

Thanks

**Comment by ocornut** [comment]
Hello,

Well you can track and compare the clip rect yourself but it won't tell you if the vertices changed.

It goes quite against the nature of imgui to avoid rerunning your imgui code, and render cost should be trivial. 

However, down the line I would like to add an explicit window flag to freeze or lower the refresh frequency of non-focused window, which would essentially reuse the existing ImDrawList data for a given window.

**Comment by DynamicStatic** [comment]
Hey,
Thanks for getting back so quickly.
I'm not trying to avoid running the imgui code, just Vulkan command buffer recording...
The vertex and index buffers can be updated without re-recording command buffers.
In pseudo code my set up looks something like...
```
void process_frame()
{
    ImGui::NewFrame();
    process_stuff();
    // ImGui calls, etc...
    ImGui::Render();

    imGuiVertexBuffer.write(ImDrawVerts);
    imGuiIndexBuffer.write(ImDrawIdxs);

    if (windowResized || im_gui_rects_changed()) {
        record_some_stuff(commandBuffer);
        for (ImDrawData ...) {
            record_im_gui_stuff(commandBuffer);
        }
    }

    submit_command_buffer(commandBuffer);
}
```

It's not a problem if there isn't a built in way to check if there were any changes...I just thought I'd ask if it's available.

In any case, I really appreciate how much this library kicks ass, thanks.

**Comment by ocornut** [comment]
Cool. Closing this.

You can hash the command passed by imgui. I'd be surprised if the creation of those Vulkan command buffer would be something you can even measure the cost of.
