### ISSUE TITLE
Text only overlay?

### ISSUE THREAD

**Issue by davide92013** [ocornut/imgui#1384]
Hello Yo So i make mods for gta v and i did this with the image and i forgot how its done. All the time the text is overlay-ed on the game when img gui is closed how would it be done someone would be able to help me would be great !!!

![image](https://user-images.githubusercontent.com/32988609/31855400-7cd7cd0a-b6a2-11e7-8d64-bc32d06c09b4.png)

**Comment by ocornut** [comment]
Check the Overlay example in the ImGui Demo window it should have everything you need.

**Comment by davide92013** [comment]
But that does not show how i always call it first then it crashed imgui lol
