### ISSUE TITLE
Text Overlay Needs Running All The Time!

### ISSUE THREAD

**Issue by davide92013** [ocornut/imgui#1385]
Hello So i mod GTA V But I need this box to allways open the text and when i close it the text shuts off i nee d it to always run no matter what when its closed or open And The Grey box Gone. I Looked at everything Please Help !! Thank You 

![image](https://user-images.githubusercontent.com/32988609/31856029-83150392-b6af-11e7-9d97-4baab767be64.png)

**Comment by ocornut** [comment]
Please don't open two threads for the same topic.

**Comment by davide92013** [comment]
Sorry just needed to get fix and i did not know sorry buddy
