### ISSUE TITLE
How to Run IMG Gui Over The Game

### ISSUE THREAD

**Issue by davide92013** [ocornut/imgui#1386]
Hello so i Open GTA V And it seems to be hooking in the back ground when i load the game i press F4 Imgui opens GTA Uses DirextX how would i be able to run it along side that over the game any thoughts or questions Would be Perfect 👍

**Comment by ocornut** [comment]
This issue repository isn't the place to ask and you aren't providing any useful information for people to help you. Please ask on other community.
