### ISSUE TITLE
Support top level menu items

### ISSUE THREAD

**Issue by sawickiap** [ocornut/imgui#1387]
I would like to propose adding support for top-level menu items. Sometimes I have a command that is very important (let's call it "VIP"), which I would like to be accessible within one click, not inside some menu. I tried following code:

```cpp
if(ImGui::BeginMainMenuBar())
{
    if(ImGui::BeginMenu("File"))
    {
        if(ImGui::MenuItem("Exit"))
            // Exit...
        ImGui::EndMenu();
    }

    if(ImGui::BeginMenu("Edit"))
    {
        //...
        ImGui::EndMenu();
    }

    if(ImGui::BeginMenu("Window"))
    {
        //...
        ImGui::EndMenu();
    }

    if(ImGui::MenuItem("VIP")) // !!!
        // Very important command...

    if(ImGui::BeginMenu("Help"))
    {
        //...
        ImGui::EndMenu();
    }

    ImGui::EndMainMenuBar();
}
```

But it doesn't work as expected. "VIP" menu item fills all remaining space and "Help" menu after it isn't shown at all. Wrapping `ImGui::MenuItem("VIP")` with `ImGui::PushItemWidth` / `PopItemWidth` doesn't help either.

![imgui_toplevelmenuitem](https://user-images.githubusercontent.com/10674866/31859904-a36ebf26-b712-11e7-9246-a17850127d9b.png)

**Comment by ocornut** [comment]
Hello Adam,

I have pushed a small fix that disable MenuItem() from spreading its highlight in that situation.
However note that you may not want menu item here, as they need to reserve space for shortcuts and tick marks, this space is reserved on the right-most side (which will be the right most side of the menu bar), and even if you don't use shortcuts/tickmarks the spacing will look a little different from a menu. However we could try to make change that the spacing would look identical if neither shortcuts or tickmarks are used.

![image](https://user-images.githubusercontent.com/8225057/31860121-bc9ba51a-b715-11e7-8dfc-848a022c9adb.png)

Generally I tend to use Button() in that case.

**Comment by ocornut** [comment]
> However we could try to make change that the spacing would look identical

Done that now.
I think it's rather misleading and not a good idea to use MenuItem() like that - you are better off using Button() - but there's no reason to actively prevent it. 

Note that in this context it would ignore the shortcuts and selected tick-mark. Unfortunately because of the dual API with one taking `bool selected` we can't differenciate "no selected tickmark" from "never a selected tickmark", so we can't adjust spacing to allow for it.

**Comment by sawickiap** [comment]
Thank you very much for your quick response!

I didn't know Button could be used in main menu. I will use either Button or your improved MenuItem then. Thanks again.
