### ISSUE TITLE
Issue with InputText() losing focus - also, how am I supposed to clear it?

### ISSUE THREAD

**Issue by JaminGrey** [ocornut/imgui#1388]
I have some code like this:
`static char consoleText[128];
if(ImGui::InputText("###ConsoleBox", &consoleText[0], IM_ARRAYSIZE(consoleText), ImGuiInputTextFlags_EnterReturnsTrue))
{
    std::string command = std::string(consoleText);

    if(command.empty() == false)
    {
        consoleHistoryTimeLeft = ConsoleHistoryVisibleDuration;

        this->executeConsoleCommand(command);

        consoleText[0] = '\0';
        //std::strcpy(consoleText,"");
    }

    ImGui::SetActiveID(ImGui::GetID("###ConsoleBox"), ImGui::GetCurrentWindow());
}`

My first problem is after hitting enter the first time, the InputText loses focus, and I can no longer ever regain focus. So I have to call `ImGui::SetActiveID(ImGui::GetID("###ConsoleBox"), ImGui::GetCurrentWindow());` after each callback to make sure it stays focused. This seems to fix the issue, but is obviously a hack, and I'm not sure why I'm getting that behavior in the first place.

My second issue is, the text isn't being cleared. Neither `consoleText[0] = '\0';` nor `std::strcpy(consoleText,"");` is working. Or rather, in the debugger they show that it works, and but the next frame the `ImGui::InputText()` resets the value to whatever it had last frame. Being a local static variable, no other of my code is touching that variable - something in `ImGui::InputText()` is re-applying the old text to the buffer.

What is the proper way to clear the buffer?

**Comment by ocornut** [comment]
Hello Jamin,

`InputText()` owns a copy of your text while being active. Your `SetActiveID()` line using internal code is going to really confuse the system in that situation. 

If you run and look at the console example in imgui_demo.cpp you'll find it is using the `ImGui::SetKeyboardFocusHere()` function to keep the focus after a command has been input:

```
// Command-line
if (ImGui::InputText("Input", InputBuf, IM_ARRAYSIZE(InputBuf), ImGuiInputTextFlags_EnterReturnsTrue|ImGuiInputTextFlags_CallbackCompletion|ImGuiInputTextFlags_CallbackHistory, &TextEditCallbackStub, (void*)this))
{
    char* input_end = InputBuf+strlen(InputBuf);
    while (input_end > InputBuf && input_end[-1] == ' ') { input_end--; } *input_end = 0;
    if (InputBuf[0])
        ExecCommand(InputBuf);
    strcpy(InputBuf, "");
}

// Demonstrate keeping auto focus on the input box
if (ImGui::IsItemHovered() || (ImGui::IsRootWindowOrAnyChildFocused() && !ImGui::IsAnyItemActive() && !ImGui::IsMouseClicked(0)))
    ImGui::SetKeyboardFocusHere(-1); // Auto focus previous widget
```

As you can notice the `if ()` here is rather specific and cumbersome, you may use different conditions such as `IsWindowAppearing()`, etc. The focusing system has been under rewrite, I haven't pushed it yet but I expect to push a host of better and clearer functions to handle that sort of things, they will replace SetKeyboardFocusHere and fix its issues. In the meanwhile this should work.

**Comment by JaminGrey** [comment]
Thank you, that works for the present - it does have some odd behavior, but I'll wait for the new focus system before griping further. =P

It'd also be nice if there was an overload for `ImGui::InputText()` that took a std::string directly.

**Comment by JPGygax68** [comment]
I seem to have had the same problem, and I fixed it by calling `SetKeyboardFocusHere(-1)` in the `if` block. 
But I do wonder why I loose the focus in this situation (where does it go?), and why clicking the text field does not work to put it back from that moment on?
