### ISSUE TITLE
Can't donate via Paypal

### ISSUE THREAD

**Issue by richgel999** [ocornut/imgui#139]
I want to send you a donation because imgui is awesome, but I don't see how to do it via Paypal.

**Comment by ocornut** [comment]
Hi Rich and thanks for your help :)

You are right I should set that up eventually. In the meanwhile my PayPal address is omar at miracleworld.net

Well appreciated!

**Comment by ocornut** [comment]
Hard to believe how confusing PayPal website can be. I had a to watch a youtube tutorial video to successfully setup a button (random pages disappearing, being logged off, etc.). Done!
Thanks for the head up!

I see you worked with Atman in the past. Atman is the person who introduced me to the concept of imguis via code he dropped in the codebase for PixelJunk Racers. I built on that base for PixelJunk Shooter before going and rewriting a full-featured one later.

**Comment by richgel999** [comment]
Yes, Atman and I worked together for several years back in the day. He's
doing the whole VR thing now, while I'm still in games. imgui is awesome
for the type of quick visualization and artist tools I write all the time.

Thanks again,
-Rich
