### ISSUE TITLE
Potential Memory Leak in ImFontAtlasBuildWithStbTruetype

### ISSUE THREAD

**Issue by Moka42** [ocornut/imgui#1391]
Hi Omar,

In _ImFontAtlasBuildWithStbTruetype_ function there is a potential memory leak on _tmp_array_ buffer when _stbtt_InitFont_ call fails and it returns false without calling `ImGui::MemFree(tmp_array);`

```c++
if (!stbtt_InitFont(&tmp.FontInfo, (unsigned char*)cfg.FontData, font_offset))
{
    // Missing cleanup ?
    // ImGui::MemFree(tmp_array);
    return false;
}
```

Thank you.

**Comment by ocornut** [comment]
Correct! Should be fixed now.
Thanks for reporting!
