### ISSUE TITLE
Mouse released event captured by ImGui when click is owned by application

### ISSUE THREAD

**Issue by Moka42** [ocornut/imgui#1392]
Hi Omar,

ImGui tells information to the user application so they can capture/discard the inputs according to the input owner.
But when a mouse drag starts from the application but ends above an ImGui window, the mouse released event is captured by ImGui.
This is a problem because the application will still continue the drag event as ImGui tells the application to capture/discard the mouse release event.

To avoid the issue this change in `ImGui::NewFrame` fixed the problem but may have introduced some others : 
```c++
if (g.IO.MouseClicked[i])
    g.IO.MouseDownOwned[i] = (g.HoveredWindow != NULL) || (!g.OpenPopupStack.empty());
mouse_any_down |= g.IO.MouseDown[i];
// g.IO.MouseReleased[i] added in condition because when mouse drag starts from engine and finishes above ImGui window,
// mouse released event was captured by ImGui.
// Initial check : if (g.IO.MouseDown[i])
if (g.IO.MouseDown[i] || g.IO.MouseReleased[i])
    if (mouse_earliest_button_down == -1 || g.IO.MouseClickedTime[mouse_earliest_button_down] > g.IO.MouseClickedTime[i])
        mouse_earliest_button_down = i;
```

Is it a safe change or does it introduce some incorrect behaviors ?
Thank you.

**Comment by ocornut** [comment]
Thanks for pointing this out.

Your fix is partially correct, but there is another bug with how we track double click and reset contents of `g.IO.MouseClickedTime[]`. If you hold left button in application, then hover imgui and double-click right button, the right button release will trigger a `WantCaptureMouse=1` for one frame.

Looking at it!

Btw a trick to debug this is to modify the demo display under "Keyboard & Mouse State" to display click/release with a different colors according to capturing state,
e.g. `ImGui::TextColored(io.WantCaptureMouse ? ImVec4(0,1,0,1) : ImVec4(1,0,0,1), "b%d", i);`

(Also linking this to the Drag and Drop thread #143)

**Comment by Moka42** [comment]
Hi Omar, thanks for the support !

I can indeed reproduce your other bug with the current workaround.
Anyways this one is less blocking than the first one that can occur more often with "normal" use (when we are moving an actor in our engine or making a square selection and finishing on ImGui window).

Thanks for looking at it and if I have another possible fix I'll let you know.
