### ISSUE TITLE
Load font for ImGui::Begin

### ISSUE THREAD

**Issue by ds-cs** [ocornut/imgui#1397]
Dear Ocornut,

I'm using your lib with DirectX9.
I have the case, that I need to load a special font only for one window (ImGui::Begin)
..
What I did:
ImFont* pFont = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Ruda-Bold.ttf", 50);
ImGui::PushFont(pFont);

I've load the font, location seems to be correct. If I try to push font.. I get some strange errors. How can I load a front for a window and change after this specific window back to default font?

**Comment by ocornut** [comment]
Hello,

Your font is not loaded. When you say "a strange error" you need to specify what and provide all the information otherwhise we cannot help you.

In c++ a single \ in a string will inhibit the next character. Use \\ or /.

**Comment by ds-cs** [comment]
![image](https://user-images.githubusercontent.com/33124939/32135915-ef55ca3a-bc06-11e7-9826-1c672331fbd2.png)


My code:
		if (ImGui::Begin(nameChar, &Vars.Menu.Opened, ImVec2(windowWidth, windowHeight), 1.0F,  ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_ShowBorders | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollWithMouse))
		{
			ImVec2 lPos = ImGui::GetCursorPos();
			ImGuiStyle& style = ImGui::GetStyle();


			ImFont* pFont = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Ruda-Bold.ttf", 50);
			ImGui::PushFont(pFont);

**Comment by ocornut** [comment]
For the records if I try to load this file here:
https://github.com/google/fonts/blob/master/ofl/ruda/Ruda-Bold.ttf
It works here. So I suspect either your path either your file may be wrong. Use a debugger to trace into `AddFontFromFileTTF()` to see what is happening.

(You should add an assert that pFont isn't NULL. Going to add that in the examples now, it would be helpful for everyone)

**Comment by ds-cs** [comment]
actually I searched arround and you cannot push for a new font!
There are some unresolved issues open for exactly this topic.

If yours is working, would be so kind and share the code with me inside a ImGui::Begin?!

**Comment by ocornut** [comment]
I don't want what unresolved issue you are referring to. `PushFont()` work the only limitation is that you cannot call it before calling NewFrame() at least once.

Test loading 2 fonts during init:
```
    // Load Fonts
    ImGuiIO& io = ImGui::GetIO();
    ImFont* font1 = io.Fonts->AddFontDefault();
    ImFont* font2 = io.Fonts->AddFontFromFileTTF("../../extra_fonts/Ruda-Bold.ttf", 16.0f);
```
Then in main loop:
```
        ImGui::Begin("Test #1397");
        ImGui::Text("Hello!");
        ImGui::PushFont(font2);
        ImGui::Text("Hello!");
        ImGui::PopFont();
        ImGui::End();
```

![image](https://user-images.githubusercontent.com/8225057/32136601-d6e09fe8-bc10-11e7-9ba9-4522ea84dc26.png)

Alternatively if you only load 1 font (the font you want) you don't need to call PushFont.

**Comment by ocornut** [comment]
Make sure you load font during init and not every frame, your snippet above may suggest you are reloading a font every frame.

If you do:
`Begin` ... `LoadFontXXX` .. `PushFont` then the font doesn't have a chance to be built.

Generally people do:
`LoadFontXXX` (during init) ... Build fonts .. Main Loop

People who need to reload fonts during the application execution (which you don't appear to need) can load them at the beginning of the main loop and then rebuild the fonts.

**Comment by Dazzid** [comment]
HI,
Sorry for posting in a closed issue. My Question is where should I add the font to be found by AddFontFromFileTTF? I'm trying absolute paths and relative as well, but always end up here:

IM_ASSERT(0); // Could not load file.

What I'm missing?
This is an amazing library by the way!

**Comment by Dazzid** [comment]
I have a very simple example in openframeworks. It compiles well noe but the font is not yet placed. Looks I'm just missing the part that loads the font?

`#include "ofApp.h"

//--------------------------------------------------------------
void ofApp::setup(){
gui.setup();
    //imageButtonSource.load("of.png");
    imageButtonID = gui.loadImage(imageButtonSource);
    ImGuiIO& io = ImGui::GetIO();
    
   // font1 = io.Fonts->AddFontDefault();
    font1 = io.Fonts->AddFontFromFileTTF("/Users/David/Openframeworks/apps/myApps/imGui/bin/data/fonts/Verdana.ttf", 18.0f);
   // ImGui::Fonts->GetTexDataAsRGBA32;
    //ImGui::PushFont(font1);
}

//--------------------------------------------------------------
void ofApp::update(){

}
ImVec4 clear_color = ImVec4(0.99f, 0.55f, 0.10f, 1.00f);
//--------------------------------------------------------------
void ofApp::draw(){
    //required to call this at beginning
    gui.begin();

    bool show_another_window = true;
    ImGui::SetNextWindowSize(ofVec2f(400,400), ImGuiSetCond_FirstUseEver);
    ImGui::SetNextWindowPos(ofVec2f(100,100));
    ImGui::Begin("Final Result", &show_another_window);
    ImGui::BeginChild("Scrolling");

   // ImGui::PushFont(font1);
    for (int n = 0; n < 50; n++)
        ImGui::TextColored(clear_color, "%04d: Some text");
    ImGui::EndChild();
    //ImGui::PopFont();
    
    //ImGui::ImageButton((ImTextureID)(uintptr_t)imageButtonID, ImVec2(300, 300));
    ImGui::End();
    gui.end();
}`

**Comment by ocornut** [comment]
Use a debugger to find out what's wrong with the AddFontFromFileTTF() call.
Make sure AddFontXXX is called before Build/GetTexDataAsRGBA32 (find where that is called in your binding)
Call ImGui::ShowStyleEditor() to browse/see the list of loaded fonts.

**Comment by Dazzid** [comment]
do you have an example using AddFontXXX? I think is that line what is missing:

it appears this message:    IM_ASSERT(font && font->IsLoaded());    // Font Atlas not created. Did you call io.Fonts->GetTexDataAsRGBA32 / GetTexDataAsAlpha8 ?

**Comment by ocornut** [comment]
> do you have an example using AddFontXXX? I think is that line what is missing:

The examples/ apps and misc/fonts/README have enough infos. Find out where your binding is building the font atlas and load fonts before that..

**Comment by Dazzid** [comment]
actually one of the reasons I'm trying to change the font is because I need to show text with bigger font size, to do so then I will need to change the scaling as well?

**Comment by Angshu1** [comment]
Hello my code is 

static bool pen = false;
            ImGuiWindowFlags fhgl = 0;
            fhgl |= ImGuiWindowFlags_NoTitleBar;

            ImGuiIO& io = ImGui::GetIO();
            ImFont* font1 = io.Fonts->AddFontDefault();
            ImFont* font2 = io.Fonts->AddFontFromFileTTF("C:\Windows\Fonts\Ruda-Bold.ttf", 16.0f);

            ImGui::Begin("g",&pen, fhgl);

            ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
            ImGui::TextColored(ImVec4(0.00, 0.91, 0.22, 1.0),"Framerate: (%.1f)", ImGui::GetIO().Framerate);

            ImGui::End();

when i run it sends an error like this https://prnt.sc/sif6j2

even after i remove ImFont* font2 = io.Fonts->AddFontFromFileTTF("C:\Windows\Fonts\Ruda-Bold.ttf", 16.0f);

and run this 

ImGuiWindowFlags fhgl = 0;
            fhgl |= ImGuiWindowFlags_NoTitleBar;

            ImGuiIO& io = ImGui::GetIO();
            ImFont* font1 = io.Fonts->AddFontDefault();

            ImGui::Begin("g",&pen, fhgl);

            ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
            ImGui::TextColored(ImVec4(0.00, 0.91, 0.22, 1.0),"Framerate: (%.1f)", ImGui::GetIO().Framerate);

            ImGui::End();

it still sends me that error can you tell me what am i doing wrong?

**Comment by FourlokoDev** [comment]
yes
