### ISSUE TITLE
Tabs placement issue 

### ISSUE THREAD

**Issue by confirmed12** [ocornut/imgui#1398]
Well I'm having an issue w tabs placement.. First I would like yall to take at the menu first:

https://i.imgur.com/xwx0Sy0.png

See how the left side of the tabs is not a little out like the right side? I been trying to get them the same for a long time but I never get good results.. Any ideas?

Code:
https://pastebin.com/P4BXv03a

**Comment by wi1h** [comment]
can't you just use ImGui::SameLine and start drawing the tabs however far over?

**Comment by csAlphyy** [comment]
I believe youre using window padding. Add me on discord, alpha#9840 since I saw this pic on the best menu in your opinion thread on UC :^)

**Comment by ocornut** [comment]
Closing this now.
