### ISSUE TITLE
Beginchild issue?

### ISSUE THREAD

**Issue by confirmed12** [ocornut/imgui#1399]
For some reason my beginchild is so spaced to the left for some reason... 

You can see in this picture
https://i.imgur.com/wl9EbT3.png

Look how its literally connected all the way to the left, how can I fix this?

**Comment by ocornut** [comment]
Please provide standalone repro code when submitting an issue. There's no way anyone can help you if you don't make the effort to provide complete information.

Please use github attachment when submitting pictures, and not imgur (so the question can stay useful to others in the future).
