### ISSUE TITLE
Performance Question ImGui::ListBoxHeader();

### ISSUE THREAD

**Issue by jeamcsgo** [ocornut/imgui#1401]
Hello, one dumb Question in terms of ListBoxHeader.

Why does the frames per second are dropping so hard when i use ListBoxHeader in my Window? :D
And can i fix it or replace it?  

FPS with ListBoxHeader "21" : 
![fps21](https://user-images.githubusercontent.com/31592104/32148047-1be31ac2-bcf1-11e7-8ca5-b1a84e7022d9.PNG)

FPS with ListBoxHeader "115" : 
![fps115](https://user-images.githubusercontent.com/31592104/32148057-39c0bf04-bcf1-11e7-8ef4-f9a7b4a9c864.PNG)

```
ImGui::ListBoxHeader(XorStr("##GUNS"), ImVec2(-1, -1));
		for (auto it : ItemDefinitionIndexMap)
		{
			bool isDefault = (int)it.first < 0;
			if (!isDefault && !Util::Contains(Util::ToLower(std::string(filterWeapons)), Util::ToLower(Util::Items::GetItemDisplayName(it.first).c_str())))
				continue;

			if (Util::Items::IsKnife(it.first) || Util::Items::IsGlove(it.first) || Util::Items::IsUtility(it.first))
				continue;

			const bool item_selected = ((int)it.first == (int)currentWeapon);
			ImGui::PushID((int)it.first);
			std::string formattedName;
			char changeIndicator = ' ';
			bool isChanged = Settings::Aimbot::weapons.find(it.first) != Settings::Aimbot::weapons.end();
			if (!isDefault && isChanged)
				changeIndicator = '*';
			formattedName = changeIndicator + (isDefault ? Util::Items::GetItemDisplayName(it.first).c_str() : Util::Items::GetItemDisplayName(it.first));
			if (ImGui::Selectable(formattedName.c_str(), item_selected))
			{
				currentWeapon = it.first;
				UI::ReloadWeaponSettings();
			}
			ImGui::PopID();
		}
		ImGui::ListBoxFooter();
```

**Comment by ocornut** [comment]
It's something in your code, your code must be slow for some reason, 
Even without manually clipping, outputting ~40 Selectable() with ImGui wouldn't cost one percent of those 11 ms you are losing.

**Comment by jeamcsgo** [comment]
Why on Linux works? :D
