### ISSUE TITLE
Empty vertical space in inputs

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#1405]
I would like to get rid of the empty vertical space between text an input

Empty space:
dear imgui
![image](https://user-images.githubusercontent.com/153526/32187506-97fcc4a0-bda5-11e7-9636-393703cdf103.png)

No empty space:
Unity
![image](https://user-images.githubusercontent.com/153526/32187527-a6ab758c-bda5-11e7-880d-a6c4c1b24b6b.png)
Google Spreadsheet
![image](https://user-images.githubusercontent.com/153526/32187863-812ea530-bda6-11e7-9f7a-2397d2daab98.png)

Is it possible to use baseline + ascender line to position text in widgets?

**Comment by wi1h** [comment]
do you mean justifying the input left/right?

**Comment by nem0** [comment]
No, vertical alignment. Unity and Google spreadsheet examples are what I would like to have

**Comment by berkay2578** [comment]
Have you tried using the Style Editor inside `ImGui::ShowTestWindow()`? What you're looking for is `ImGuiStyle::FramePadding`

**Comment by ocornut** [comment]
It looks like style.FramePadding is what you want to change? 

`PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0,0));`

**Comment by nem0** [comment]
It's not padding, I tried that first ofc :) Even with 0 padding, there is empty vertical space above text. What's more padding is symmetrical. You can see the problem in every screenshot in readme.

I checked both imgui and stb_truetype and they do not provide  ascender line, so I guess what I want might not really be possible.

**Comment by ocornut** [comment]
Looking at your screenshot, it looks like might be able to combine negative `FramePadding.y` + `ImFont::DisplayOffset.y` to some degree.

(NB: I think there is a current rounding problem with makes text 1 pixel too low depending on font data and odd/even pixel size, which tends to push your text lower. Using e.g. `font->DisplayOffset.y = -1` may fix it).

**Comment by nem0** [comment]
Setting ```ImFont::DisplayOffset.y``` to 0 (default is 1) helps, thank you.
