### ISSUE TITLE
Blender style InputFloat+ SliderFloat combo?

### ISSUE THREAD

**Issue by c4ooo** [ocornut/imgui#1407]
Would it be possible to add a blender-styled InputFloat+ SliderFloat combo where the user can both slide left/right to decrease/increase the value, but also be able to click on it and manually set it to a specific value? I understand you don't have time for all requests but this would be nice for people who are making editors of one kind or another ;)

**Comment by wi1h** [comment]
ctrl clicking on the slider will let you input a number via keyboard

**Comment by ocornut** [comment]
Also DragFloat provides an interface a little closer to what you mention. Both sliders and drags support ctrl+click to input a value.

**Comment by c4ooo** [comment]
Thanks, didn't realize that you could use ctr to edit the value directly :)

**Comment by ocornut** [comment]
Closing this as solved. I tweaked the End-User Guide description and `ShowUserGuide()` function to make that feature more apparent. I presume you hadn't read those before?
