### ISSUE TITLE
Controlling the Size of a Text Box's Clickable Area

### ISSUE THREAD

**Issue by CaptainKraft** [ocornut/imgui#1413]
Is there a way to make a text box have a larger area to click? If I put '.' into a text box, it's very difficult to click on that small text.

**Comment by ocornut** [comment]
I don't understand the question. If you mean an InputText() widget, it should have a fixed width defined by the PushItemWidth() function.

**Comment by CaptainKraft** [comment]
This is for the Text() widget. When I click on my text, I switch it to input text. It's difficult to click on any text if it is small. PushItemWidth() doesn't seem to affect the clickable area of the Text widget.

**Comment by ocornut** [comment]
You may create a custom widget or use high-level primitives eg GetCursorPos() Text() GetCursorPos() InvisibleButton() to layout a bigger item and test inputs on that.

**Comment by CaptainKraft** [comment]
Thank you. I'll give it a shot.
