### ISSUE TITLE
How to add lines on top of an image

### ISSUE THREAD

**Issue by therocode** [ocornut/imgui#1415]
I am trying to render an image in an imgui window and then add some custom lines on top of it.

I am rendering the image as per usual with ImGui::Image. Given the text inside imgui.h which says:

> If you want to add custom rendering within a window, you can use ImGui::GetWindowDrawList() to access the current draw list and add your own primitives.
> You can interleave normal ImGui:: calls and adding primitives to the current draw list.

My thought is that I can just first render the image with ImGui::Image and then get the draw list and add some lines with drawList->AddLine(). After trying this however, the line is drawn correctly inside the window, but it ends up behind the image.

How come it ends up behind, when I add it _after_ the ImGui::Image call? Is z-ordering for things not based on which order they are added to the draw list?
Is there a better way of achieving this than my proposed solution?

Thanks

**Comment by ocornut** [comment]
It is rendering in order, so
- Either you are omitting something (eg using child window to manipulate the sort order) or made a mistake. Providing repro code would help you confirm what you are seeing.
- Or perhaps your rendering function is accidentally using the depth buffer which could lead to it looking it it is rendered behind, but you'd probably have other artifacts if that was the case.

You can use the metrics window to browse draw calls and confirm what is happening.

**Comment by therocode** [comment]
Ooh right, yes the image is drawn in a child window. The principle of the code is as such:

```
void mySpecialImageFunc()
{
      //additional stuff here
      ImGui::BeginChildFrame(...);  //the purpose of this child is to give the image scroll bars for when it's too big
      ImGui::Image(...);
      ImGui::EndChildFrame();
}


//calling code:
mySpecialImageFunc();

//trying to add lines on top of my image here:
ImDrawList* drawList = ImGui::GetWindowDrawList();
drawList->AddLine(spr::toImVec(start), spr::toImVec(end), 0xFF0000FF, 10.0f);
```
So yeah, if children are rendered in front of other stuff, it makes sense that the lines end up behind. What's a good solution to this case though? I'd not wanna do the line code inside of mySpecialImageFunc since that's a library function and is reused in several places, some of which don't have those lines. The lines are for a specific use case of this image function.


As extra information, the special image function is a function that creates an image with zoom in/out buttons etc.

**Comment by ocornut** [comment]
It's probably easier if you refactor your code. You may be able to also just call BeginChild() again with the same identifier to append into the child window from a separate spot (this is guaranteed to work with normal windows so you can append into them, but I think it might possibly not work with BeginChild or confuse the layout in the parent window... i could look into it it is probably an easy fix to allow guarantee it to work for child window)
As for this line:
`drawList->AddLine(spr::toImVec(start), spr::toImVec(end), 0xFF0000FF, 10.0f);`
Two tips:
- see imconfig.h there are macros you can use to setup the ImVec2 type so it automatically converts back and forth from/to your engine types.
- You can IM_COL32() macro to generate color.

**Comment by therocode** [comment]
Okay, I quickly tried calling BeginChild again, but it didn't seem to work indeed, I didn't see anything extra rendered, who knows where it ended up.

Btw, side question, how come there is no BeginChildFrame overload which takes a const char* for the ID?

Feel free to make it guaranteed to work if you want to, but for now I also solved it on my side by letting the specialImageFunc take an optional lambda for doing extra operations after the image has been drawn - not the nicest solution but it works.

Thanks for the tips, that's neater indeed I'll change to that :)

Thanks for your time helping out!

**Comment by ocornut** [comment]
> Okay, I quickly tried calling BeginChild again, but it didn't seem to work indeed,

I just tested and checked the code and it works (the code explicitly handle it, I couldn't check when I posted my previous message from the phone).

```
ImGui::Begin("Feat #1415");
ImGui::Text("Main A");
ImGui::BeginChild("Test", ImVec2(200, 200), true);
ImGui::Text("Child A");
ImGui::EndChild();
ImGui::Text("Main B");
ImGui::BeginChild("Test");
ImGui::Text("Child B");
ImGui::EndChild();
ImGui::End();
```

![image](https://user-images.githubusercontent.com/8225057/32414282-b9b82ca6-c223-11e7-8f26-f96cd92e4fd0.png)

Also this works:
```
ImGui::Begin("Feat #1415");
ImGui::Text("Main A");
ImGui::BeginChild("Test", ImVec2(200, 200), true);
ImVec2 p = ImGui::GetCursorScreenPos();
ImGui::Image(ImGui::GetIO().Fonts->TexID, ImVec2(100,100));
ImGui::EndChild();
ImGui::Text("Main B");
ImGui::BeginChild("Test");
ImGui::GetWindowDrawList()->AddLine(p, ImVec2(p.x + 50, p.y + 50), IM_COL32(255, 0, 0, 255), 3.0f);
ImGui::EndChild();
ImGui::End();
```
![image](https://user-images.githubusercontent.com/8225057/32414307-185f9dde-c224-11e7-9b10-4ac1a2c1154f.png)

> Btw, side question, how come there is no BeginChildFrame overload which takes a const char* for the ID?

No specific reason, but I'm not very happy with the name/signature to those helpers API (BeginChildFrame and ListBoxHeader) so right now I'd prefer not adding extra overload to them.
