### ISSUE TITLE
Using vector for Combo?

### ISSUE THREAD

**Issue by SephLeague** [ocornut/imgui#1419]
would it not be better to use std::vector<char*> to pass the combo box items and then get the size from .Size()?

**Comment by ocornut** [comment]
No people not all people use vector<> and want to use it. You can create yourself a helper that wrap a vector<> using the callback. You’ll probably even find that helper on this issue tracker if you look for it.

The upcoming BeginCombo API will also make it more natural to pass on various types, but you can do with the existing function.

**Comment by ocornut** [comment]
Closing as duplicate
Search for:
https://github.com/ocornut/imgui/search?utf8=%E2%9C%93&q=combo+std+string&type=Issues

Yield:
https://github.com/ocornut/imgui/issues/911
https://github.com/ocornut/imgui/issues/673
Also
https://eliasdaler.github.io/using-imgui-with-sfml-pt2/#using-imgui-with-stl
