### ISSUE TITLE
OpenGL examples weird offset (GPU driver issue?)

### ISSUE THREAD

**Issue by mathee12** [ocornut/imgui#1421]
Hello people!

So I want to check out imgui and use it for my c++/openGL simulation visualization tool I'm currently building. However running the imgui-demo-binaries-20171013, I have a very strange vertical offset, meaning when I want to click a button I actually have to click like 1cm below.
![image](https://user-images.githubusercontent.com/8364783/32652365-4d2a8ab8-c604-11e7-8814-2e906376d0f6.png)
![image](https://user-images.githubusercontent.com/8364783/32652386-5fbe1604-c604-11e7-9c7f-c8f275d9ed43.png)

In the first image I'm clicking the "B" button, in the second I am currently clicking and moving the slider. The vulkan and directx9/11 examples work just fine. Any ides on what's going on here? :)

Cheers,
Matt

**Comment by ocornut** [comment]
Hmm, this is rather odd.
We are leaving the window creation to GLFW which is a rather wide spread and reliable library, 

Could you try a couple of the older binaries to see if you the same issues has been always present?
http://www.miracleworld.net/imgui/binaries/

You can then do a few things to inspect where it is going wrong:
- In the test window, open "Inputs & Focus" -> "Keyboard & Mouse" state you can visualize the mouse position. See how it differs in each corners of the application area. Is the mouse offset? Or incorrectly scaled?
- You may also print or display `io.DisplaySize`, compare the value to the mouse position, and also take a screenshot and see if `io.DisplaySize` matches your OS window client area.

**Comment by mathee12** [comment]
Thanks for the hints. Yes the issue exists also for older binaries. However: I had the same issue when I tried the AntTweakBar-gui, so I assume it's nothing imgui-specific. I will now investigate on the points you mentioned.

**Comment by zerkshop** [comment]
Hey I had the same-ish problem. The vulkan demo worked fine, but had an annoying vertical mouse offset with the opengl demo. Googling a bit and found out somewhere that there was an issue with intel graphics drivers. I updated the driver and problem fixed. This was on my Surface Pro 4. I would try updating drivers

**Comment by ocornut** [comment]
I'll close this as a driver issue.
