### ISSUE TITLE
Vertical button layout

### ISSUE THREAD

**Issue by Zort3x** [ocornut/imgui#1424]
Hey, So I'm trying to make something like this

https://i.gyazo.com/06201c5facd2baf1022233b56c01e00a.png

But i've tried to do this for some time now but i cant find a way how, If anyone knows how to do this please reply

(also id ask this on a irc or discord channel but i cant find some so i assume that there isent any and im just posting it here)

**Comment by Blick1337** [comment]
beginchild endchild

**Comment by ocornut** [comment]
The demo should explain provide most of the building blocks you need to replicate this screen. See the "Simple layout" applet for example.

`Button()` allows you to pass a size and if you pass -1 on the X axis it'll use all available space, so you can create a layout with a child window on the left, then SameLine, then other childs on the right.
