### ISSUE TITLE
Getting a LOT of errors in imgui_demo.cpp

### ISSUE THREAD

**Issue by 2n0w** [ocornut/imgui#1426]
Hello, I'm getting 105 when including imgui_demo.cpp in my project.

I've included all of the .cpp and .h files in the main imgui folder, but it still has 105 errors.
I would have included the list of errors but I'm not sure how to copy all of the errors without  CTRL clicking on everything.

Why does this happen?

**Comment by ocornut** [comment]
You can copy the errors from your log/output.
No one can help if you don’t provide the most basic information, aka the error themselves.

Also specify which compiler, OS, which of the application/code you are compiling..

**Comment by 2n0w** [comment]
im just making a test dll to open the ImGui::ShowTestWindow() thing, and im using all the original files, but it still wont work. i'm compiling under x86 in release mode on windows 8.1.

heres the error log: https://pastebin.com/dGW3RXxw

**Comment by ocornut** [comment]
It looks like you have either modified imgui_demo somehow, it should be including imgui.h, or you are using files from different versions of imgui (possibly your imgui_demo is newer than the rest of imgui).
