### ISSUE TITLE
Seperator & ComboBox

### ISSUE THREAD

**Issue by lolnobody** [ocornut/imgui#1428]
Hello i new to this and how i can set seperator width ?

How i can do that like this -> https://imgur.com/a/TBVsp 

Also how to disable this from any moving -> https://imgur.com/fMAenPQ

**Comment by ocornut** [comment]
Your question aren't clear, your subject line isn't explicit, we barely understand what you want, and somehow to forgot to say "thanks" when asking people to help you. Please refer to demo code. 
I have to close this thread, won't provide support, please figure this out with your community.
