### ISSUE TITLE
ImGui_ImplWin32_WndProcHandler

### ISSUE THREAD

**Issue by crylessdomore** [ocornut/imgui#1429]
In the current version ImGui_ImplWin32_WndProcHandler function does not return 1.
_see https://github.com/ocornut/imgui/blob/master/examples/directx9_example/imgui_impl_dx9.cpp_

#MY_BAD

**Comment by Nukem9** [comment]
Be careful, the return values are not all the same (sometimes 1, sometimes 0). I think DefWindowProc should be used if the messages are unhandled?

https://msdn.microsoft.com/en-us/library/windows/desktop/ms645616(v=vs.85).aspx
```
WM_MOUSEMOVE
Return value

If an application processes this message, it should return zero.
```

**Comment by crylessdomore** [comment]
ImGui_ImplWin32_WndProcHandler should return 1 whenever the message is matching and does not replace DefWindowProc or CallWindowProc.
_see https://github.com/ocornut/imgui/blob/master/examples/directx9_example/main.cpp#L18_

**Comment by crylessdomore** [comment]
I am sorry, I just reviewed my position and you are right it can not work as I said but it is not even correct to always return 0.

It should return 1 when click/press on a ImGui item to prevent DefWindowProc call.

**Comment by ocornut** [comment]
Which problem are you trying to solve exactly?

**Comment by crylessdomore** [comment]
It is hard to explain: I am trying to prevent DefWindowProc call so that I do not click on what is under the menu created with ImGui.

```
LRESULT CALLBACK WndProc(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
{
	if (ImGui_ImplWin32_WndProcHandler(hWnd, Msg, wParam, lParam)) {
		return TRUE;
	}

	return DefWindowProc(hWnd, Msg, wParam, lParam);
}
```

**Comment by ocornut** [comment]
Why do you want this behavior? Do you have apps reacting to individual win32 messages, or are you just trying to filter mouse and keyboard? 
Have you checked the io.WantCaptureMouse et io.WantCaptureKeyboard flags provided by imgui? They are normally provided for that purpose.

**Comment by crylessdomore** [comment]
Thank you! io.WantCaptureMouse and io.WantCaptureKeyboard was exactly what I was looking for :)

I post my solution for those who have/will have the same issue, it is not complete because some events are still to handle but I think it reach as example.

```C++
LRESULT CALLBACK hkWndProc(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
{
	if (pMenu) {
		pMenu->handleInput(hWnd, Msg, wParam, lParam);
	}

	ImGuiIO& io = ImGui::GetIO();

	if (io.WantCaptureMouse
		|| io.WantCaptureKeyboard) {
		return TRUE;
	}

	return CallWindowProc(oWndProc, hWnd, Msg, wParam, lParam);
}
```

I take advantage of it to propose a change...

Before
```C++
IMGUI_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    ImGuiIO& io = ImGui::GetIO();
    switch (msg)
    {
    case WM_LBUTTONDOWN:
    case WM_RBUTTONDOWN:
    case WM_MBUTTONDOWN:
    {
        int button = 0;
        if (msg == WM_LBUTTONDOWN) button = 0;
        if (msg == WM_RBUTTONDOWN) button = 1;
        if (msg == WM_MBUTTONDOWN) button = 2;
        if (!IsAnyMouseButtonDown() && GetCapture() == NULL)
            SetCapture(hwnd);
        io.MouseDown[button] = true;
        return 0;
    }
    case WM_LBUTTONUP:
    case WM_RBUTTONUP:
    case WM_MBUTTONUP:
    {
        int button = 0;
        if (msg == WM_LBUTTONUP) button = 0;
        if (msg == WM_RBUTTONUP) button = 1;
        if (msg == WM_MBUTTONUP) button = 2;
        io.MouseDown[button] = false;
        if (!IsAnyMouseButtonDown() && GetCapture() == hwnd)
            ReleaseCapture();
        return 0;
    }
    case WM_MOUSEWHEEL:
        io.MouseWheel += GET_WHEEL_DELTA_WPARAM(wParam) > 0 ? +1.0f : -1.0f;
        return 0;
    case WM_MOUSEMOVE:
        io.MousePos.x = (signed short)(lParam);
        io.MousePos.y = (signed short)(lParam >> 16);
        return 0;
    case WM_KEYDOWN:
    case WM_SYSKEYDOWN:
        if (wParam < 256)
            io.KeysDown[wParam] = 1;
        return 0;
    case WM_KEYUP:
    case WM_SYSKEYUP:
        if (wParam < 256)
            io.KeysDown[wParam] = 0;
        return 0;
    case WM_CHAR:
        // You can also use ToAscii()+GetKeyboardState() to retrieve characters.
        if (wParam > 0 && wParam < 0x10000)
            io.AddInputCharacter((unsigned short)wParam);
        return 0;
    }
    return 0;
}
```

After
```C++
IMGUI_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    ImGuiIO& io = ImGui::GetIO();
    switch (msg)
    {
    case WM_LBUTTONDOWN:
    case WM_RBUTTONDOWN:
    case WM_MBUTTONDOWN:
    {
        int button = 0;
        if (msg == WM_LBUTTONDOWN) button = 0;
        if (msg == WM_RBUTTONDOWN) button = 1;
        if (msg == WM_MBUTTONDOWN) button = 2;
        if (!IsAnyMouseButtonDown() && GetCapture() == NULL)
            SetCapture(hwnd);
        io.MouseDown[button] = true;
        break;
    }
    case WM_LBUTTONUP:
    case WM_RBUTTONUP:
    case WM_MBUTTONUP:
    {
        int button = 0;
        if (msg == WM_LBUTTONUP) button = 0;
        if (msg == WM_RBUTTONUP) button = 1;
        if (msg == WM_MBUTTONUP) button = 2;
        io.MouseDown[button] = false;
        if (!IsAnyMouseButtonDown() && GetCapture() == hwnd)
            ReleaseCapture();
        break;
    }
    case WM_MOUSEWHEEL:
        io.MouseWheel += GET_WHEEL_DELTA_WPARAM(wParam) > 0 ? +1.0f : -1.0f;
        break;
    case WM_MOUSEMOVE:
        io.MousePos.x = (signed short)(lParam);
        io.MousePos.y = (signed short)(lParam >> 16);
        break;
    case WM_KEYDOWN:
    case WM_SYSKEYDOWN:
        if (wParam < 256)
            io.KeysDown[wParam] = 1;
        break;
    case WM_KEYUP:
    case WM_SYSKEYUP:
        if (wParam < 256)
            io.KeysDown[wParam] = 0;
        break;
    case WM_CHAR:
        // You can also use ToAscii()+GetKeyboardState() to retrieve characters.
        if (wParam > 0 && wParam < 0x10000)
            io.AddInputCharacter((unsigned short)wParam);
        break;
    }
    return 0;
}
```

**Comment by ocornut** [comment]
> I take advantage of it to propose a change...

If there is one learning in this thread is that you should state what you are trying to achieve with a change.

**Comment by crylessdomore** [comment]
I thought it was easy to guess, I just changed return 0 for each case with break as the function always returns 0

It is nothing important.

**Comment by ocornut** [comment]
Closing, moved to #1431

**Comment by ArkAngeL43** [comment]
`If there is one learning in this thread is that you should state what you are trying to achieve with a change.` okay but you can stop being an ass about it XD, jesus dude stop being so rude

**Comment by imshoppinginwalmart** [comment]
I know it's been eight years since this post was made, but I cannot express in words how much setting up imgui makes me want to absolutely fucking shoot myself.

**Comment by ocornut** [comment]
@imshoppinginwalmart Well it should be about 20 lines in most situation:
https://github.com/ocornut/imgui/wiki/Getting-Started

Maybe instead try to express in words what your problems actually are if you intend to receive help.
