### ISSUE TITLE
Does it make sense to have value in radians and min and max in degrees?

### ISSUE THREAD

**Issue by elect86** [ocornut/imgui#1435]
https://github.com/ocornut/imgui/blob/852ece3a0e29a27771148c95fda51ba5e4e65e0c/imgui.cpp#L7019

Wouldn't be better for all the values to be coherent?

**Comment by ocornut** [comment]
It's a mistake and it is a little stupid, but not easy to fix (though this version isn't used a lot so we could change the min/max units and it wouldn't be dramatic in this direction.... maybe I'll do that).
Also note that contrary to the edited value, the min/max bounds are often fixed/known by the developer.

**Comment by MarkusMiller** [comment]
Sorry for ticket necromancy, but I actually just ran into a situation where it perfectly made sense to have the angle in rad but the display in degrees (I wanted to make an adjustable field of view, so this setting made perfect sense). However, for flexibility reasons, I'd find a more configurable solution preferable.

**Comment by trapazza** [comment]
Also, is there any way to have a granularity other than 1 degree? I'm using it for an scenario where a precision of 1/10th of a degree is  required.

Thanks :)

**Comment by ocornut** [comment]
Just reimplement the function in your core with a custom format, it is a 2-3 lines format.

**Comment by ocornut** [comment]
Closing this old issue. I agree `SliderAngle()` can't tackle all cases but it's easy to come up with something better locally. 

We should probably provide a default widget to visually select a 2D angle, too!
