### ISSUE TITLE
Squares menu?

### ISSUE THREAD

**Issue by fenomenalne** [ocornut/imgui#1436]
Hey,
I was wondering if you can do something like this using imgui:
![alt text](https://i.imgur.com/MpEIo9o.png)

Let me explain what is happening in this picture. So the main menu is 3 squares*, each one leads to a submenu. I really like this kind of design and this is where my question comes from.

### for example
- square 1: colors menu
- square 2: more options
- square 3: more options

**Comment by ocornut** [comment]
Your question is unfortunately a little too vague. 
You can do anything if you put the code/time at it.  It's not something that's supported off the shelves in the BeginMenu API , but you can perfectly create a square button and have then open popups that contains square buttons as well.
