### ISSUE TITLE
ImGui::Selectable fps drop

### ISSUE THREAD

**Issue by dikbutt** [ocornut/imgui#1438]
Okay, i am going through a problem with my code that, when i add too many entries on my Selectable list, it lags the hell out of me. (commenting the string that retrieves the items to add on the selectable makes the fps stay stable) and it's only when that specific menu is open.

**Comment by ocornut** [comment]
How many selectable?
It perhaps means your code is too slow. 
Please post your code.
You should probably be using ImGuiListClipper for large lists.

**Comment by dikbutt** [comment]
if (ImGui::Selectable(skin.first == -1 ? skin.second.displayName : Util::WstringToString(pLocalize->FindSafe(skin.second.displayName)).c_str(), item_selected))
			selectedModelSkin = skin.first;

This is the line, that if commented, the lag disappears

entire code : https://pastebin.com/wK1BMK4r

line 356 is the line that if commented, """fixes""" the issue

**Comment by dikbutt** [comment]
removing the if() doesn't fix the issue

**Comment by ocornut** [comment]
- You didn't answer my question "how many selectable?"

- You or someone else already posted the exact same question with the same code a few weeks ago.

- You can and you should use ImGuiListClipper to only loop among visible items.

- Your code `Util::WstringToString(pLocalize->FindSafe(skin.second.displayName)).c_str()` it likely way too slow, it suggests you are doing memory allocations, string conversions and search. If you replaced it by hardcoded strings e.g. `Selectable("hello")` you will be able to guess how much speed is the fault of Selectable and how much is your code. Unless you have tens thousands+ items the cost of Selectable() itself shouldn't be an issue, and it you have tens thousands+ items you should use ImGuiListClipped anyway.
