### ISSUE TITLE
ImGui::Retain()

### ISSUE THREAD

**Issue by dkrikun** [ocornut/imgui#144]
Hi,

There are cases when it is needed to display the same ui as in the previous frame, but it is not convenient to reproduce exactly the same commands to ImGui.

Could it be possible to add, e.g. `ImGui::Retain()`, that will not clear the internal state for the duration of the next frame?

Thx

**Comment by ocornut** [comment]
If you call Render() without calling NewFrame() you'll get the same render again.

Note that this second frame won't be interactive.

**Comment by dkrikun** [comment]
Is it possible to make it interactive?

**Comment by ocornut** [comment]
No, that's impossible. All interactions happens at the time you are calling the functions. This is the point of immediate-mode gui.

I'm curious about you saying "it is not convenient to reproduce exactly the same commands to ImGui.".
Immediate-mode gui aim to make it as stateless as possible on the client side, and therefore sending commands should be trivial. What sort of thing makes it not convenience to send commands?

**Comment by dkrikun** [comment]
I have a set of components that are scheduled for processing each frame. A
component carries out its duties and issue commands to ImGui for debug.
There is also a "pause" mode, in which the components aren't even
scheduled. Still, I would like to see and interact with the ui.

**Comment by ocornut** [comment]
That's fair.
So I guess you need to have a way to "schedule" only the debug processing of your items somehow (the functon that sends the ImGui commands) and that can be done when the game is paused.

**Comment by dkrikun** [comment]
I guess that's what I'll do. It would however require that the components
will have to recognize the pause mode and behave accordingly. Thanks.

**Comment by ocornut** [comment]
Or you should just call the code that does the UI, if it's not interleaved with the rest of the processing code. Good luck.
