### ISSUE TITLE
Windows-1250 character support

### ISSUE THREAD

**Issue by TheVektor** [ocornut/imgui#1446]
Hi!
I have problems with character encoding.
DX:
I have created an Arial font and i am drawing a text like "árvíztűrő tükörfúrógép" which contains all special lower-case hungarian letters. This worked fine.

imgui:
I create an ImGui::InputText, i write "árvíztűrő tükörfúrógép" then pass the string to DX to draw.
In this case the output replaced the special characters to a very different ones. (e.g. @$ßˇ¤)

How should i fix this? :/

**Comment by ocornut** [comment]
- Made you have loaded the right font with the right glyph ranges that contains the characters you need. In the demo window under Window Options > Style > Font you can browse the contents of your font and check what glyphs have been loaded.
- ImGui uses utf-8, you need your strings encoded as utf-8. C++11 can use the `u8"árvíztűrő tükörfúrógép"` to encode a string literal as utf-8.
- Please read the FAQ and read all of extra_fonts/README.txt.

**Comment by TheVektor** [comment]
- Yes the font i have loaded contains the correct characters i want to use.
- char str[256]; <--- i think this is an UTF-8 string
- I am not really into fonts, characters and encoding, i just want to use the correct range that fits into Windows-1250 code page, so everyone can use the program i wrote (atleast from middle-eu)

**Comment by ocornut** [comment]
> Yes the font i have loaded contains the correct characters i want to use.

The font contains the characters but have you LOADED the characters, by setting up the glyph ranges?

`char str[256]` this is not a UTF-8 string or anything, this is an array of 256 bytes.
`"árvíztűrő tükörfúrógép"` is NOT utf-8 encoding
`u8"árvíztűrő tükörfúrógép"` is utf-8 encoding in C++11

Local codepage are not supported, imgui uses utf-8.
