### ISSUE TITLE
ListClipper Preventing Scrolling to Bottom

### ISSUE THREAD

**Issue by CaptainKraft** [ocornut/imgui#1447]
I have a vector of lines where I'm trying to print output to a window. When I use the clipper and try to scroll all the way down, it just won't. The scroll bar immediately jumps back up a couple lines.

Note: console_lines is a std::vector of std::string
```c++
            ImGuiListClipper console_clipper(console_lines.size());
            while (console_clipper.Step()) {
                for (int i = console_clipper.DisplayStart;
                     i < console_clipper.DisplayEnd; i++) {
                    ImGui::TextWrapped("%s", console_lines[i].c_str());
                }
            }
            if (scroll_console)
                ImGui::SetScrollHere();
```

Am I using the clipper incorrectly?

**Comment by ocornut** [comment]
Unfortunately, by using `TextWrapped()` you are breaking the main assumption of the ListClipper which is that items should be evenly spaced out vertically. They are just not compatible at the moment.

**Comment by CaptainKraft** [comment]
Ahhh, OK. Thanks for the info.
