### ISSUE TITLE
Inconsistent behavior of IsItemHovered() (was: Problem with tooltip on widgets)

### ISSUE THREAD

**Issue by attilaz** [ocornut/imgui#145]
I am showing tooltips like this:

Combo/InputText/etc.
if (ImGui::IsItemHovered())
	ImGui::SetTooltip("I am a tooltip");

For Combo tooltip is visible when hovering on the label, but not on the dropdown part.
For InputText tooltip is visible when hovering on the input part, but not on the label.

Is it possible to get Is*Hovered for the whole widget instead of just some part of it?

Thanks for this UI engine, this is the first UI that I really enjoy to use.

**Comment by ocornut** [comment]
Hello!

Yes sorry, IsItemHovered() is known to be a little inconsistent at the moment. It was added after the fact and I never got to fix all widgets to behave super consistently.

For now I have fixed Combo() to behave like most/all widget aka IsItemHovered() will return true when hovering the framed section with the value (and not the label).

I will eventually go and have a pass at cleaning up widget internal so they are consistent and so you can query more detailed hovering information.

**Comment by ocornut** [comment]
AFAIK the majority of widget should behave the same way at the moment, if you find another that isn't please let me know.

**Comment by attilaz** [comment]
Thanks for the combo fix. I will let you know if I find something.

**Comment by ocornut** [comment]
FYI what's left of this issue is the
" Is it possible to get Is*Hovered for the whole widget instead of just some part of it? "

**Comment by ocornut** [comment]
Should be all consistent now.
