### ISSUE TITLE
warning: format not a string literal and no format arguments

### ISSUE THREAD

**Issue by ebachard** [ocornut/imgui#1450]
Hi  Omar,

On Linux, using the code below (in fact, every time I used the popup) + O3 optimisation level with g++-5.4.0, I got the warning  mentionned in the title.

```
            /*       Championnat        */
            ImGui::SameLine();
            static int selected_level = 1;
            const char * names[] = { "LFH", "D2F", "N1F", "N2F", "N3F", "-18CF", "Reg" };

            if (ImGui::Button("Niveau de jeu : "))
                ImGui::OpenPopup("niveau_jeu");

            ImGui::SameLine();
            ImGui::Text(names[selected_level]);  /* THE PROBLEM IS THERE */

            if (ImGui::BeginPopup("niveau_jeu"))
            {
                ImGui::Text("Championnat");
                ImGui::Separator();

                for (int i = 0 ; i < IM_ARRAYSIZE(names); i++)
                   if (ImGui::Selectable(names[i]))
                        selected_level = i;
                ImGui::EndPopup();
            }

```
As you already understood, I used the code in imgui_demo.cpp to write the one above.
Searching on the web lead me to this: https://stackoverflow.com/questions/17260409/fprintf-error-format-not-a-string-literal-and-no-format-arguments-werror-for

And finaly, a simple 
            ImGui::Text("%s", names[selected_level]);
fixed all the warnings, and seems to add more safety in the code. 

I'm not very handy using github, but I created a pull request (not sure everything worked though ...). Waiting, I need your opinion, because I have no idea about what will happen on Windows with this change.

Thanks in advance for your time :-)

**Comment by ocornut** [comment]
None of that code you posted is in imgui.cpp or imgui_demo.cpp so that I don't know what pull request you intend to do here..

**Comment by ebachard** [comment]
Sorry, I didn't hit the button :-)  ... should be visible now

**Comment by ocornut** [comment]
is that the only occurrence of the warning with your compiler settings?
Can you change the PR to use `TextUnformatted()` instead?
Thanks!

**Comment by ebachard** [comment]
Yes, that's the only occurence of the warning.

Indeed, using:
    ImGui::TextUnformatted("bla bla");

Avoids the warning. So ... what is the best choice ?  

More precisely, is it equivalent  to use  ImGui::Text( "%s", names[selected_level]) (e.g.) ?

**Comment by ocornut** [comment]
Yes, that's the purpose of `TextUnformatted()`.

**Comment by ebachard** [comment]
Ok, thanks a lot for your (fast) answer, and apologies for the noise.

**Comment by ocornut** [comment]
No problem, thanks for the report :)
I pushed the fix directly now!
