### ISSUE TITLE
SDL binding: Odd menu bar problem

### ISSUE THREAD

**Issue by Czar-Ec** [ocornut/imgui#1452]
Hello, I have a very odd problem in my code where the menu bar does not work if the mouse is on the window when the program starts, but the menu bar definately does work when the mouse is not over the window.

I can't seem to pinpoint the cause of this, it might be the fact that I'm also checking events alongside ImGUI, here is a snippet of my code:

```
while (appRun)
	{
		//update mouse position
		SDL_GetMouseState(&mousePos.x, &mousePos.y);
			
		//check for inputs
		while (SDL_PollEvent(&eventMain) != 0)
		{
			//update frame for imgui
			ImGui_ImplSdlGL2_NewFrame(window);
			{
				gui.menuBar(appRun);
			}


			//process events via SDL
			switch (eventMain.type)
			{			
				case SDL_QUIT:
					appRun = false;
					break;

				//while clicking the left button
				case SDL_MOUSEBUTTONDOWN:
					if (eventMain.button.button = SDL_BUTTON_LEFT && key[SDL_SCANCODE_LSHIFT])
					{
						clickAndDrag = true;
					}
					break;

				//when the button is no longer pressed
				case SDL_MOUSEBUTTONUP:
					if (eventMain.button.button = SDL_BUTTON_LEFT)
					{
						clickAndDrag = false;
					}
					break;
					
					
				//process event for IMGUI
				ImGui_ImplSdlGL2_ProcessEvent(&eventMain);
			}
}
```

Anyways, I'm hoping you may be able to help with this.

**Comment by Czar-Ec** [comment]
Just to clarify, I mean MAIN menu bar
![mainmenuissue](https://user-images.githubusercontent.com/32554382/32987052-b505837a-ccd7-11e7-8ad9-39ea4ccea25d.PNG)

**Comment by ocornut** [comment]
I don’t know what gui.menuBar() does but you _need_ to call Render or EndFrame for each call to NewFrame() else some things will break. Perhaps that’s the reason for your issues?

(I’ve been meaning to add an assert to detect this situation - will look into it. Vaguely recall a reason why it wasn’t easily obvious to add)

**Comment by ocornut** [comment]
Hello, 

1) I misread the code so my suggestion may be invalid. However make sure Render/NewFrame are always called.

2) You are supposed to update your inputs _before_ calling NewFrame(). While I don't think this is causing your issue, your current code ordering will effectively make inputs lag by an extra frame.

3) Please clarify "menu bar doesn't work". It is being displayed? Are the menu options highlighting when hovered by mouse?
You can call ShowMetricsWindow() and under `Basic State` section try to inspect what is happening. Is your main menu bar window detected as hovered? Also display your mouse coordinates and check if they are right.

**Comment by Czar-Ec** [comment]
Ok, so I have placed the ProcessEvent before the NewFrame, I have a rendering function which also calls ImGui::Render after the NewFrame and I still have the same problem. I have found out that this doesnt just affect the menu bar but the entire ImGui inputs.

Ive also set the mouse to print its position and seems to be correct.

Note: The original problem was that the menu options arent highlighting when hovered over by the mouse, now the problems seems to be that ImGui isnt taking any inputs

**Comment by ocornut** [comment]
The code that calls `ImGui_ImplSdlGL2_ProcessEvent(&eventMain);` in your first code is inside the switch() but not under a case statement, it likely never runs.

Otherwhise please try to provide a repro (see https://stackoverflow.com/help/mcve) it's hard to get what is going wrong in your implementation without that.

**Comment by Czar-Ec** [comment]
I apologise if this has take a week, I am currently shuffling this with other university projects.
I have created a repro which simplifies what I need to do and the problem still appears.
I'm not certain whether its because the ordering of process is wrong in my program or if SDL_Renderer is incompatible with what I'm doing

`int main(int argc, char** argv)
{
	SDL_Window *window = nullptr;
	SDL_DisplayMode currentDisplay;
	//simulation renderer
	SDL_Renderer *renderer;
	//opengl context
	SDL_GLContext glcontext;
	

	//initialise SDL
	if (SDL_Init(SDL_INIT_EVERYTHING) < 0)
	{
		//debug output
		std::cerr << "Error: " << SDL_GetError() << std::endl;
		exit(0);
	}

	else
	{
		// Setup window
		SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
		SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, 24);
		SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);
		SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
		SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);
		SDL_GetCurrentDisplayMode(0, &currentDisplay);

		//create the window
		window = SDL_CreateWindow(
			"ZEUS",
			SDL_WINDOWPOS_CENTERED,
			SDL_WINDOWPOS_CENTERED,
			//1366
			currentDisplay.w / 2,
			//768
			currentDisplay.h / 2,
			//show window on screen
			SDL_WINDOW_SHOWN
			//resizable window
			| SDL_WINDOW_MAXIMIZED
			//opengl window
			//| SDL_WINDOW_OPENGL
		);

		//opengl context
		glcontext = SDL_GL_CreateContext(window);

		//check if window was created
		if (window == NULL)
		{
			std::cout << "SDL Window error: " << SDL_GetError() << std::endl;
			//exit the program
			exit(0);
		}
		//continue setup
		else
		{
			//initialise IMGUI
			ImGui_ImplSdlGL2_CreateDeviceObjects();
			ImGui_ImplSdlGL2_InvalidateDeviceObjects();
			ImGui_ImplSdlGL2_Init(window);

			//find GPU drivers
			int oglIdx = -1;
			int nRD = SDL_GetNumRenderDrivers();
			for (int i = 0; i < nRD; i++)
			{
				SDL_RendererInfo info;
				if (!SDL_GetRenderDriverInfo(i, &info))
				{
					if (!strcmp(info.name, "opengl"))
					{
						oglIdx = i;
					}
				}
			}

			//create the renderer, linking the number of GPU drivers
			renderer = SDL_CreateRenderer(window, oglIdx,
				SDL_RENDERER_ACCELERATED
				| SDL_RENDERER_PRESENTVSYNC
			);



			//initiate glew
			glewExperimental = true;
			glewInit();

			//setup ImGui style
			//ImGuiStyle &style = ImGui::GetStyle();
			//style.Colors[ImGuiCol_MenuBarBg] = ImVec4(0.6f, 0.0f, 0.0f, 1.0f);

			//allow transparency
			SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_BLEND);
		}
	}

	bool appRun = true;
	SDL_Event eventMain;

	//loop
	while (appRun)
	{
		//check for inputs
		while (SDL_PollEvent(&eventMain) != 0)
		{

			//process event for IMGUI
			ImGui_ImplSdlGL2_ProcessEvent(&eventMain);
		}
		//update frame for imgui
		ImGui_ImplSdlGL2_NewFrame(window);
		{
			ImGui::ShowMetricsWindow();

			//menubar
			ImGui::BeginMainMenuBar();
			//File
			if (ImGui::BeginMenu("File"))
			{
				//Make a new simulation
				if (ImGui::MenuItem("New Simulation", "CTRL+N"))
				{
					std::cout << "New Sim\n";
				}

				ImGui::EndMenu();
			}
			ImGui::EndMainMenuBar();
		}


		///////////////////////////////////////////////////////////////////////////////
		//Rendering
		SDL_SetRenderDrawColor(renderer, 100, 100, 100, 255);
		SDL_RenderClear(renderer);
		SDL_Rect vp;
		//get window size
		vp.w = (int)ImGui::GetIO().DisplaySize.x;
		vp.h = (int)ImGui::GetIO().DisplaySize.y;

		//link viewport to the renderer
		SDL_RenderSetViewport(renderer, &vp);


		//render the world map
		//SDL_RenderCopy(renderer, worldMap, NULL, NULL);

		//render the IMGUI elements
		//glUseProgram(0);
		ImGui::Render();

		//update the screen
		SDL_RenderPresent(renderer);
	}
	
	return 0;
}`

**Comment by ebachard** [comment]
@Czar-Ec  : can you test using SDL_GL_SwapWindow(window) instead of SDL_RenderPresent(renderer) ? 
If I'm not wrong, I think I had a similar issue long time ago with SDL2 renderer + ImGui

HTH

**Comment by Czar-Ec** [comment]
@ebachard I have done that and the program is definately taking mouse input, the part that doesn't is the ImGUI portion.

**Comment by Czar-Ec** [comment]
This is just speculation, but I think I have pin pointed the cause of ti not working. Using SDL_GetCurrentDisplayMode() is a function that breaks the input to ImGui. If you like, you can remove that line in my repro ro see if the same problem occurs for you

**Comment by Czar-Ec** [comment]
I have also found out that this occurs when using SDL_GetDesktopDisplayMode(). The functions may be doing something which prevents ImGui from being able to read inputs

**Comment by Czar-Ec** [comment]
So I haven't been in this thread for a while and I've pretty much adapted my project to not use the desktop display mode, so I'll be closing this issue.

Might be making more issue posts later on since I'm very heavily using ImGui in my project :)
