### ISSUE TITLE
popup menu on child windows

### ISSUE THREAD

**Issue by Ghost-yc** [ocornut/imgui#1453]
when use imgui v1.52 code, can't popup menu on child window. example code:
```c++
ImGui::BeginChild()
if (ImGui::BeginPopupContextWindow())
{
   if (ImGui::Selectable("Clear"))
   {
   }
  ImGui::EndPopup();
}
```

**Comment by ocornut** [comment]
This
```
ImGui::Begin("Issue #1453");
ImGui::BeginChild("test", ImVec2(100,100));
if (ImGui::BeginPopupContextWindow())
{
    if (ImGui::Selectable("Clear"))
    {
    }
    ImGui::EndPopup();
}
ImGui::EndChild();
ImGui::End();
```

Works:
![image](https://user-images.githubusercontent.com/8225057/33019670-a15b5af0-cdfb-11e7-8891-a0dfd25aaaa3.png)

Please provide a minimal, complete and verifiable example next time (see https://stackoverflow.com/help/mcve). The code you posted is incomplete.

**Comment by Ghost-yc** [comment]
Sorry about my code problem

**Comment by Ghost-yc** [comment]
In fact, the demo inside the console, the right is not pop-up menu

**Comment by ocornut** [comment]
It works here.

Note that there was a bug added on Oct 20 that was fixed on Nov 2nd:
https://github.com/ocornut/imgui/pull/1404
