### ISSUE TITLE
Memory leak for tab?

### ISSUE THREAD

**Issue by Nyque** [ocornut/imgui#1457]
I seem to get one instance of 32 bytes memory leak with just the following code
```
BeginTabBar("tab");
if (TabItem("item"))
{
}
EndTabBar();
```
`ShowTabsDemo` gives a 32 bytes memory leak as well

**Comment by ocornut** [comment]
Do you have more information about the leak?

There's no Shutdown() for the Tabs data in the old Tabs branch, that's in the work. If you don't use more than 1 imgui context it shouldn't matter, that memory that imgui reuses.

**Comment by ocornut** [comment]
The leak is probably that you need to add, in the `ImGuiBigStorage` definition, a destructor:

`~ImGuiBigStorage() { Clear(); }`

If you can confirm that fixes your leak I'll push that to the branch.

**Comment by Nyque** [comment]
I tried `~ImGuiBigStorage() { Map.Clear(); }` and `~ImGuiBigStorage() { Data.clear(); }` but it still doesn't solve the problem.

Let me know what kind of extra information you need.

**Comment by ocornut** [comment]
It needs to be `~ImGuiBigStorage() { Clear(); }`
But now I realized that the public branch may not have the `Clear()` function. Here it is:
`void Clear() { for (int n = 0; n < Data.Size; n++) Data[n].~T(); Map.Clear(); Data.clear(); }`

> Let me know what kind of extra information you need.

Well, if you say there is a leak you probably didn't pull that fact off your hat, you must have some information about the leak... some software told you, what did they say?

**Comment by Nyque** [comment]
Thank you. The `Clear()` function you gave solved the memory leak.

**Comment by ocornut** [comment]
Thanks, this is now merged in the `tabs` branch. I have also merged latest `master` and `drag_and_drop` into `tabs` for good measure.
