### ISSUE TITLE
Remember Tabs

### ISSUE THREAD

**Issue by ILoveImgui** [ocornut/imgui#1458]
Hi 💃 
I have tried for a little while on figure out how i can remember the last open tab, with the new tabs system. But no luck :/ (https://github.com/ocornut/imgui/commit/99661607d1166d3a7dded71d9c9a66c0dec34847)

What i have tried to do is when the tab bar stops running, it save the tab that was open. And when opening it up agen i sett the last open tab so that tab shows up.
I now about the ImGui::SetTabItemSelected, but i have a problem on getting the string to the last tab used. 
I am going to keep trying to i get it working, but it had been nice if someone could come with a example /idea on how to do this the best way possible. For my way is probably going to be messy :/

PS.
Keep up the good work 👍

**Comment by ocornut** [comment]
Please only report Tabs issues in the Tabs thread #261. Closing this. 
Persistence will work in the final tab/docking system, it won't at the moment. Please wait a few weeks/months until it's finished.

The string to SetTabItemSelected is the concatenation of all string id used to produce the final ID. This API was only created for quick debugging and the function signature will change.
