### ISSUE TITLE
OpenGL rendering issues (was: Problem with fonts)

### ISSUE THREAD

**Issue by hateom** [ocornut/imgui#1459]
I managed to integrate the ImGui in my custom OpenGL platform, but I can't get the fonts to render properly. Can you please point me in the right direction?

This is what I see when I try to use the demo in my environment:
https://www.dropbox.com/s/btjcevq6zqxw8dq/imgui_problem.png?dl=0

**Comment by ocornut** [comment]
Hard to say.

Are you using the stock rendering code from the opengl3 example? It should just work if you copy and paste the render code.

You can use graphics debugger like RenderDoc to figures out whats wrong. 

PS: please use github image attachments inside of transient external links, so that the issues are useful for future readers.

**Comment by hateom** [comment]
I based my code on opengl2_example - modified imgui_impl_glfw files to hook up the input and modified a bit some viewport & ortho setup.
Thanks for the feedback - will try the mentioned methods.

Attaching the image again for further reference:

![imgui_problem](https://user-images.githubusercontent.com/7631245/33200821-79edd92c-d0f6-11e7-8dc7-60e831b296b0.png)

**Comment by ocornut** [comment]
If you use modern opengl in your code (aka anything with shaders) you shouldn’t use the opengl2 rendering path, it’ll just be a minefield. That’s explained pretty much in the header of every opengl files and the examples readme and the getting started section, I’m not sure what I can do other than deleting this code or calling the folder “legacy” ?

**Comment by hateom** [comment]
Agreed, but my host application where I'm integrating imgui supports only OpenGL 2.1.

**Comment by ocornut** [comment]
Fair!  
Then hmm I don't know what's wrong. 
The vertices position and colors are correct, so I would guess the UV are probably correct as well. Something related to texture binding? RenderDoc would definitively help you.

**Comment by hateom** [comment]
Will try it for sure. Thanks for the tip.

**Comment by hateom** [comment]
The weird part is that I just tried it on windows, and the fonts work OK.
The previous screenshot was from Mac OS.
However there's still something weird going on at the edges of the windows and around the expandable triangles:

![screenshot 2017-11-24 17 17 15](https://user-images.githubusercontent.com/7631245/33218112-612b6e14-d13b-11e7-92a3-2d6d5ad2cfdf.png)

I will keep digging.

**Comment by ocornut** [comment]
@hateom Hello! Any progress on it? The last screenshot, could it be a problem with your backface culling setup?

**Comment by hateom** [comment]
Hey, I stopped the project for now. I can only report that when using OpenGL 3.3 everything works fine. Will try to see if there's a way to switch from 2.1 to 3+.

**Comment by hateom** [comment]
Just to give feedback - it was a problem with the OpenGL 2 example implementation.
I had to adjust the OpenGL 3+ code for the OpenGL 2.1 compatibility mode on macOS (using some Apple specific extensions like: `glBindVertexArrayAPPLE`). After doing that everything is fine.

**Comment by ocornut** [comment]
Would be interested in details if you remember them. You mention replacing glBindVertexArray with glBindVertexArrayAPPLE, but the problem above was when using imgui_impl_opengl2.cpp which doesn't use this function.

GL cross-platform compatibility and examples is still a tedious mess, sorry this is getting me grumpy so often :( Any extra data point is helpful at least we have records.

**Comment by ocornut** [comment]
According to #1900 our example are mislabeled and opengl3/ code could run on a 2.x context. We do have GLSL 120 shaders which are compatible with GL 2.1. The main obstacle with using imgui_impl_opengl3.cpp is often the confusion with OpenGL loaders. The patch in #2002 aims to simplify that.

**Comment by hateom** [comment]
I took the opengl3 example (from that point in time where it had only GLSL 330 shaders) and rewritten them to 120 + replaced the VAO functions with APPLE extensions. So possibly the issue has been resolved since then.

I will grab the latest opengl3 example and see if it works.

**Comment by ocornut** [comment]
Closing as dangling random backend issue, may or not be resolved or applicable.
