### ISSUE TITLE
Any way to set focus to a particular window?

### ISSUE THREAD

**Issue by Roflraging** [ocornut/imgui#146]
I've been wanting to implement some functionality that involves multiple windows and setting focus on a particular one of interest.

For example, I wanted to have two different windows that are loosely related to each other; Window A has the high level overview of the contents of a resource pack, while Window B is the detailed editing window of a particular resource.  Window A would serve as a method to just inspect the pack and possibly select individual resources for editing.  Selecting a resource would bring up Window B and start editing that resource in Window B.  From Window B, I wanted to have a button that would bring Window A right back into focus (or open it if it isn't already open) so you can jump right back to the high level resource pack view.

One of the other use cases I wanted to have is something like a modified file warning dialog box, where some settings were changed but weren't written back to disk and is still at risk of losing data.  I want to make sure the user gets a chance to handle the information as they see fit before proceeding.  Currently, I have a quick and dirty implementation where I just open up another window, but the user is free to completely ignore it and basically work right around it (or accidentally click something else and they lose the window under a stack of other windows).

Is this possible to do with the current API?  I've searched around and only noticed a function to test if a window has focus, but that's about it.

-Dale Kim

**Comment by ocornut** [comment]
Done. I also added setter given names.

```
void  SetNextWindowPos(const ImVec2& pos, ImGuiSetCondition cond = 0);    // set next window position - call before Begin().
void  SetNextWindowSize(const ImVec2& size, ImGuiSetCondition cond = 0);  // set next window size. set to ImVec2(0,0) to force an auto-fit.
void  SetNextWindowCollapsed(bool collapsed, ImGuiSetCondition cond = 0); // set next window collapsed state.
void  SetNextWindowFocus();                                               // set next window to be focused / front-most

void  SetWindowPos(const ImVec2& pos, ImGuiSetCondition cond = 0);        // set current window position - call within Begin()/End(). may incur tearing.
void  SetWindowSize(const ImVec2& size, ImGuiSetCondition cond = 0);      // set current window size. set to ImVec2(0,0) to force an auto-fit. may incur tearing.
void  SetWindowCollapsed(bool collapsed, ImGuiSetCondition cond = 0);     // set current window collapsed state.
void  SetWindowFocus();                                                   // set current window to be focused / front-most

void  SetWindowPos(const char* name, const ImVec2& pos, ImGuiSetCondition cond = 0);        // set named window position - call within Begin()/End(). may incur tearing.
void  SetWindowSize(const char* name, const ImVec2& size, ImGuiSetCondition cond = 0);      // set named window size. set to ImVec2(0,0) to force an auto-fit. may incur tearing.
void  SetWindowCollapsed(const char* name, bool collapsed, ImGuiSetCondition cond = 0);     // set named window collapsed state.
void  SetWindowFocus(const char* name);                                   // set named window to be focused / front-most
be focused / front-most
```

**Comment by Roflraging** [comment]
Awesome, thanks Omar!
