### ISSUE TITLE
Is it possible to run vulkan_example on Android?

### ISSUE THREAD

**Issue by kingofoz** [ocornut/imgui#1465]
Thanks!

**Comment by kingofoz** [comment]
@ocornut

**Comment by ocornut** [comment]
Please no arbitrary ping, especially as you could figure out the answer yourself if you tried a little more..

A: Not as is because vulkan_example uses GLFW which doesn’t support Android, but with a simple rework of the code there’s no reason you can’t use imgui with a vulkan renderer on Android.

**Comment by kingofoz** [comment]
I see. Thank you!
