### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by dvre** [ocornut/imgui#1467]
Hey, this is what my text looks like:
![image](https://user-images.githubusercontent.com/34073915/33340461-6d2c4f0a-d47c-11e7-8c8b-c75f146c6e50.png)

However, I want it to look like this (same size, font):
![image](https://user-images.githubusercontent.com/34073915/33340490-7e3312b6-d47c-11e7-812b-a1a5dc33d50a.png)

As you can see the second one doesn't look as blurry.
Any idea?

**Comment by ocornut** [comment]
Your question is ill-defined. Please submit more information, possibly in the form of a MCVE (https://stackoverflow.com/help/mcve)
You are not telling us which font you are using, which font settings, if you are using an existing unmodified imgui backend or your own with probably different rendering properties, etc. And clearly those two pictures you posted are not the "same size". Not sure what magically answer you expect here.

Dear ImGui rasterize font into textures using stb_truetype.h and small font that are meant to appear anti-aliased typically don't look very good with that rasterizer. If you use FreeType + the freetype rasterizer for imgui (code in https://github.com/ocornut/imgui_club) you'll probably achieve a little better quality.

You may also use small font that are meant to appear pixel-perfect such as ProggySmall and that'll work with the default imgui font rasterizer.
