### ISSUE TITLE
Crashing with message cannot assert

### ISSUE THREAD

**Issue by iBrooda** [ocornut/imgui#1471]
`
namespace DirectX {

	EndScene_t g_fnOriginalEndScene;
	Reset_t g_fnOriginalReset;

	WNDPROC g_pOldWindowProc;
	HWND g_hWindow;

	bool g_IsInitialized = false;

	HRESULT __stdcall Hooked_EndScene(IDirect3DDevice9* pDevice) {
		if (!g_IsInitialized) {
			ImGui_ImplDX9_Init(g_hWindow, pDevice);

			g_IsInitialized = true;
		}
		else {
			ImGui::GetIO().MouseDrawCursor = OptionsManager.bShowMenu;

			//Begins a new ImGui frame.
			ImGui_ImplDX9_NewFrame();

			if (OptionsManager.bShowMenu) {

				
				ImGui::Begin("Enzine.tk | Cheat", &OptionsManager.bShowMenu, ImVec2(200, 115), OptionsManager.s_MenuTransparency, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar);
				{
					TAB MANAGER HERE IT IS NOT THIS

				}ImGui::End();

				ImGui::Begin(XorStr("Enzine"), &OptionsManager.bShowMenu, ImVec2(685, 300), 
				}	                         
					{
                                                  MENU CODE HERE IT IS NOT THIS 
					}
				}ImGui::End();

				if (OptionsManager.bEnableSkin) {
					static char filterWeapons[32];
					static char filterSkins[32];

					ImGui::Begin(XorStr("Enzine - Skinchanger"), &OptionsManager.bEnableSkin, ImVec2(685, 300), OptionsManager.s_MenuTransparency, 0);
					{
						ImGui::BeginChild("first child", ImVec2(250, 420), true);
						{
							ImGui::PushItemWidth(-1);
							ImGui::InputText(XorStr("##FILTERWEAPONS"), filterWeapons, ARRAYSIZE(filterWeapons));
							ImGui::PopItemWidth();
							ImGui::ListBoxHeader(XorStr("##GUNS"), ImVec2(-1, -1));
							for (auto it : ItemDefinitionIndexMap)
							{
								bool isDefault = (int)it.first < 0;
								if (!isDefault && !Contains(ToLower(std::string(filterWeapons)), ToLower(ItemDefinitionIndexMap.at(it.first).entityName)))
									continue;

								if (IsUtility(it.first))
									continue;

								const bool item_selected = ((int)it.first == (int)OptionsManager.currentWeapon);
								//ImGui::PushID((int)it.first);
								std::string formattedName;

								formattedName = ItemDefinitionIndexMap.at(it.first).entityName;
								if (ImGui::Selectable(formattedName.c_str(), item_selected))
								{
									OptionsManager.currentWeapon = (int)it.first;
								}
								//ImGui::PopID();
							}
							ImGui::ListBoxFooter();
						}ImGui::EndChild();
						ImGui::SameLine();

						ImGui::BeginChild("second child", ImVec2(200, 420), true);
						{
							std::string skinName = weaponnames(OptionsManager.currentWeapon);
							{
								ImGui::PushItemWidth(-1);
								ImGui::InputText(XorStr("##FILTERSKINS"), filterSkins, ARRAYSIZE(filterSkins));
								ImGui::InputInt(XorStr("##custom ID"), &OptionsManager.W[OptionsManager.currentWeapon].ChangerSkin);
								ImGui::PopItemWidth();
								ImGui::ListBoxHeader(XorStr("##SKINS"), ImVec2(-1, -1));
								std::string skinStr = "";
								int curItem = -1;
								int s = 0;
								for (auto skin : OptionsManager.weaponSkins[weaponnames(OptionsManager.currentWeapon)])
								{
									int pk = OptionsManager.skinMap[skin].paintkit;
									if (pk == OptionsManager.W[OptionsManager.currentWeapon].ChangerSkin)
										curItem = s;
									bool selected = OptionsManager.W[OptionsManager.currentWeapon].ChangerSkin == pk;

									skinStr = OptionsManager.skinNames[OptionsManager.skinMap[skin].tagName].c_str();
									skinStr += " | ";
									skinStr += std::to_string(OptionsManager.skinMap[skin].paintkit);
									if (!Contains(ToLower(std::string(filterSkins)), ToLower(skinStr)))
										continue;
									if (ImGui::Selectable(skinStr.c_str(), selected))
									{
										pk = OptionsManager.skinMap[skin].paintkit;
										OptionsManager.W[OptionsManager.currentWeapon].ChangerSkin = pk;

										break;
									}
									s++;
								}

								ImGui::ListBoxFooter();
							}
						}ImGui::EndChild();
						ImGui::SameLine();

						ImGui::BeginChild("third child", ImVec2(200, 420), true);
						{
							ImGui::ListBoxHeader("##KNIVES", ImVec2(-1, -1));
							{
								if (ImGui::RadioButton(XorStr("Default"), &OptionsManager.bKnifeChanger, 0))
								{

								}
								if (ImGui::RadioButton(XorStr("Bayonet"), &OptionsManager.bKnifeChanger, 1))
								{

								}
								if (ImGui::RadioButton(XorStr("Flip Knife"), &OptionsManager.bKnifeChanger, 2))
								{

								}
								if (ImGui::RadioButton(XorStr("Gut Knife"), &OptionsManager.bKnifeChanger, 3))
								{

								}
								if (ImGui::RadioButton(XorStr("Karambit"), &OptionsManager.bKnifeChanger, 4))
								{

								}
								if (ImGui::RadioButton(XorStr("M9 Bayonet"), &OptionsManager.bKnifeChanger, 5))
								{

								}
								if (ImGui::RadioButton(XorStr("Huntsman"), &OptionsManager.bKnifeChanger, 6))
								{

								}
								if (ImGui::RadioButton(XorStr("Falchion"), &OptionsManager.bKnifeChanger, 7))
								{

								}
								if (ImGui::RadioButton(XorStr("Bowie"), &OptionsManager.bKnifeChanger, 8))
								{

								}
								if (ImGui::RadioButton(XorStr("Butterfly Knife"), &OptionsManager.bKnifeChanger, 9))
								{

								}
								if (ImGui::RadioButton(XorStr("Shadow Daggers"), &OptionsManager.bKnifeChanger, 10))
								{

								}
							}
							ImGui::ListBoxFooter();
						}ImGui::EndChild();

					}ImGui::End();
				}
			}

			ImGui::Render();
		}

		return g_fnOriginalEndScene(pDevice);
	}
}

`

It is somewhere when activating OptionsManager.bEnableSkin... it is saying this
https://gyazo.com/b69a782fd34cb95cb359521343321f0d?token=fe37a93198a698a5644eb274e44475a0

**Comment by ocornut** [comment]
Please provide a callstack and check what functions led to the assert. It is likely trying to tell you something and you need to read that message.
