### ISSUE TITLE
Can't see cursor on ImGui menu

### ISSUE THREAD

**Issue by DavydMAC** [ocornut/imgui#1472]
How to fix missing cursor on an ImGui Menu (Internal Cs:Go Cheat).
Thanks.

**Comment by ocornut** [comment]
Please provide full repro code, as well as a clear explanation of what is happening, what you are doing, and what you are expecting.

**Comment by DavydMAC** [comment]
I am not so good coder ,so after creating the dll file and injecting to csgo and pressing Insert , it's poping up a menu for the hack (in-game) but the problem is that i don't have a cursor on it , i still can click on buttons but the cursor is invisible.
How i could draw a simple cursor ?
Visual Studio: http://prntscr.com/hi4b9i
InGame Menu: http://prntscr.com/hi4csz
I should have a cursor on the menu but i don't see it.

**Comment by ocornut** [comment]
This is not an imgui problem. The mouse cursor is controlled by the application via the Windows APIs Eg: ShowCursor() function of Win32 api.

You can request imgui to draw a software mouse cursor by settings io.MouseDrawCursor=true in the ImGuiIO structure. A software mouse cursor will feel more laggy than the cursor handled by the os.

Closing this.

**Comment by DavydMAC** [comment]
Thanks.

**Comment by DavydMAC** [comment]
Bro one more thing so where exactly to put io.MouseDrawCursor = true ?
