### ISSUE TITLE
ImGui::Hotkey

### ISSUE THREAD

**Issue by csAlphyy** [ocornut/imgui#1474]
So I just updated the ImGui today, and ImGui::Hotkey seems to be missing. Has it been renamed, removed or replaced with something else? Thank you :)

**Comment by ocornut** [comment]
Dear Imgui never had a function called ImGui::Hotkey().

**Comment by ocornut** [comment]
(If you added one to your copy of imgui you should never edit imgui.cpp but add it in your own file)

**Comment by csAlphyy** [comment]
Oh so I did! I'm sorry, and thank you.
