### ISSUE TITLE
Warning when compiling with VS2017 64bit 

### ISSUE THREAD

**Issue by enci** [ocornut/imgui#1475]
I am getting the following warning when compiling with VS2017 64bit:
`\imgui.cpp(2681): warning C4244: 'argument': conversion from '__int64' to 'int', possible loss of data`
The code line is:
`const ImGuiID type_hash = ImHash(type_start, type_end - type_start, 0);`
The second argument is 64 bit wide, but `ImHash` is expecting an int. With an explicit cast it all works well, but I am not sure if it's the **correct** solution.

**Comment by ocornut** [comment]
This line of code was already removed from Master a few days ago, if you update it should be fixed.
