### ISSUE TITLE
Window can't be moved when ImGuiCond_Always and GetWindowPos() are combined

### ISSUE THREAD

**Issue by towerpark** [ocornut/imgui#1476]
If you retrive a window position and use it to draw the window in next frame by ImGuiCond_Always, the window can't be moved by mouse. I reproduced it with the newest master (5f7cd7f) by putting the following code in OpenGL2 example app:
```
static ImVec2 pos(0, 0);
ImGui::SetNextWindowPos(pos, ImGuiCond_Always);
bool open;
ImGui::Begin("", &open);
pos = ImGui::GetWindowPos();
ImGui::End();
```
If ImGuiCond_Always is changed to ImGuiCond_Once or ImGuiCond_FirstUseEver, it will work just fine.
Is it a desired behavior or a bug?

By the way, thank you for the great work.

**Comment by ocornut** [comment]
I am not sure what you are asking here... if you have explicitly setting the window position every frame, how do you expect it to move? Those two things are contradicting each others. What are you trying to do?

**Comment by towerpark** [comment]
I'm sorry I wan't clear.

If the window is dragged, the value of `pos` returned from `GetWindowPos()` can be different from `pos` in `SetNextWindowPos()` in the same frame. What the code is trying to do is getting the new position (after being dragged) and use it as window position in next frame. I thought the code should act exactly the same with code that doesn't set position explicitly. Though it seems there's no point to do this, I'm using Imgui this way just because of some needs of my application.

In addition, the similar code for window size works that way, i.e. I can still change window size by mouse:
```
    static ImVec2 sz(200, 200);
    bool open;
    ImGui::SetNextWindowSize(sz, ImGuiCond_Always);
    ImGui::Begin("", &open);
    sz = ImGui::GetWindowSize();
    ImGui::End();
```

**Comment by ocornut** [comment]
>  Though it seems there's no point to do this, I'm using Imgui this way just because of some needs of my application

Please describe what you are trying to achieve with this / which problem you are solving.

**Comment by towerpark** [comment]
First, thank you for trying to help me to solve the problem.

My case is shown as the following code (To keep it short, code not directly related such as injecting inputs is not included):
```
class MyWnd {
    Vec2  m_pos;
public:
    void setPos(Vec2 pos) {
        m_pos = pos;
    }
    void draw() {
        ImGui::NewFrame();
        ImGui::SetNextWindowPos(m_pos, ImGuiCond_Always);
        ImGui::Begin("", nullptr);
        m_pos = ImGui::GetWindowPos();
        ImGui::End();        
        ImGui::Render();        
    }
};
```
The position of `MyWnd` can be modified by both `setPos()` called by my application and mouse drag. In order to simplify code, I was retriving window position at the end of a frame and feeding it to the window in next frame so that position change caused by both `setPos()` and mouse drag could be reflected automatically. Of couse, the code only works if window position after being dragged were calculated in `Begin()`.

Now I've added a dirty flag and set window position explicitly only when it's changed via `setPos()` -- a little bit longer but not so bad :)
```
class MyWnd {
    bool  m_dirty;
    Vec2  m_pos;
public:
    void setPos(Vec2 pos) {
        m_pos = pos;
        m_dirty = true;
    }
    void draw() {
        ImGui::NewFrame();
        if (m_dirty) {
            ImGui::SetNextWindowPos(m_pos, ImGuiCond_Always);
            m_dirty = false;
        }
        ImGui::Begin("", nullptr);
        ImGui::End();        
        ImGui::Render();        
    }
};
```
