### ISSUE TITLE
New Combo model not dependent on item index

### ISSUE THREAD

**Issue by aaslane** [ocornut/imgui#1477]
The current combo works great when the list of items is static, but when using a list of items that can change externally it can be better to hold the currently selected item instead of the index of the item.

The new Combo routine to allow this model is below. It is based on your routine, and the changes are minor (original lines are commented). Feel free to change how you want to best fit into your structure/style.

Instead of passing the current item index, a pointer to the current item is passed. This allows the current item to be stored by the caller instead of the index. It also allows a non-list item to be passed (i.e. "Select an item") when nothing has been selected yet.

Edit: sorry the formatting below did not work very well. So it is attached as file as well.

[NewCombo.txt](https://github.com/ocornut/imgui/files/1527216/NewCombo.txt)

`// Changes: pass in current item as string vs index, current_item may not be in list
// Combo box function.
bool ImGui::Combo(const char* label, const char*& current_item, bool (*items_getter)(void*, int, const char**), void* data, int items_count, int height_in_items)
{
    ImGuiContext& g = *GImGui;
    const ImGuiStyle& style = g.Style;

    const char* preview_text = current_item;
//    const char* preview_text = NULL;
//    if (*current_item >= 0 && *current_item < items_count)
//        items_getter(data, *current_item, &preview_text);

    // Size default to hold ~7 items
    if (height_in_items < 0)
        height_in_items = 7;
    float popup_height = (g.FontSize + style.ItemSpacing.y) * ImMin(items_count, height_in_items) + (style.FramePadding.y * 3);

    if (!BeginCombo(label, preview_text, ImVec2(0.0f, popup_height)))
        return false;

    // Display items
    // FIXME-OPT: Use clipper
    bool value_changed = false;
    for (int i = 0; i < items_count; i++)
    {
        PushID((void*)(intptr_t)i);
//         const bool item_selected = (i == *current_item);
        const char* item_text;
        if (!items_getter(data, i, &item_text))
            item_text = "*Unknown item*";
        const bool item_selected = strcmp(current_item, item_text) == 0;
        if (Selectable(item_text, item_selected))
        {
            value_changed = true;
            current_item = item_text;
//            *current_item = i;
        }
        if (item_selected && IsWindowAppearing())
            SetScrollHere();
        PopID();
    }

    EndCombo();
    return value_changed;
}
`

**Comment by ocornut** [comment]
Hello @aaslane,

Apologies that you never got an answer to this.
I believe such as you posted this I was reworking the combo API into new `BeginCombo()` / `EndCombo() function and forgot to answer you. Using the `BeginCombo()` / `EndCombo()` model the selection state can be handled by the user in any manner, so this is effectively solving the problem that your variation of the function was solving.

Thanks for posting this, and sorry again for the delay,
Closing this thread now.

Omar
