### ISSUE TITLE
How to draw a specific area inside a loaded texture from dds file?

### ISSUE THREAD

**Issue by r3peat** [ocornut/imgui#1478]
![Image](https://i.imgur.com/PbgVsmx.png)

for example this dds file contains multiple images i wanna draw one by one.

is there a way to tell imgui to render a specific area inside a loaded texture?

**Comment by Brianfog** [comment]
Check the [demo code](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp), ImGui::Image  and ImGui::ImageButton few lines below (lines 557 & 577).

**Comment by ocornut** [comment]
The `ImGui::Image()` and `ImDrawList::AddImage()` function are taking uv coordinates. Please read about uv coordinates if you don't know what they are, it's not an imgui specific thing.
