### ISSUE TITLE
Dragging an item hides hover functionality

### ISSUE THREAD

**Issue by 123tris** [ocornut/imgui#1479]
I'm still new to the library so forgive me for my lack of knowledge of the API

As I've tried to implement dragging I've realized that dropping is a bit of a pain. This is because the frame where the mouse released is, the hover detection still doesn't work. This only happens if you drag a UI item like a treenode or a button. I believe this has to do with `ImGui::IsItemActive()`
 
For example:
`if (ImGui::IsWindowHovered() && ImGui::IsMouseReleased(0)) std::cout << "test\n";` will not be called if you dragged an item and then released it over the window, it will only be called if you dragged nothing and then released the mouse. Is this intended?
This is needed for my drop and drag system, considering that this pretty much is my drop condition.

**Comment by ocornut** [comment]
Hello,

Two things:
- The IsWindowHovered and IsItemHovered() since a month or so have various flag to ease implementing those patterns:
https://github.com/ocornut/imgui/issues/1382

- May I suggest looking at the work in progress drag_and_drop branch instead
https://github.com/ocornut/imgui/tree/drag_and_drop
In particular see this post describing the API:
https://github.com/ocornut/imgui/issues/143#issuecomment-344533856
There's no demo for it apart from the fact that the Color widget are implementing it but that post has the exemple.
It probably already has what you need in there?

**Comment by 123tris** [comment]
Ah I just had to update ImGui, thanks for the hover flags they really help a lot!
My implementation of drag and drop is by simply using dragable interfaces.
```
/**
* Base class for all the editor items that can be dragged
* eg. a prefab gets dragged into a inspector property field.
*/
class Draggable
{
public:
	virtual ~Draggable() = default;
};
```
And then I have a static class to set the dragging of an item.

```
class EditorDragging
{
public:
	/**
	* \return Returns the current draggingItem. Any draggable object can be selected
	*/
	static Draggable* getDragableItem() { return draggingItem; }
	/**
	* \param draggingItem The item to be set as the dragable item
	*/
	static void setDragableItem(Draggable* draggingItem)
	{
		EditorDragging::draggingItem = draggingItem;
	}
	/**
	 * \brief sets the currently dragging item to equal nullptr
	 */
	static void reset()
	{
		draggingItem = nullptr;
	}

private:
	static Draggable* draggingItem;
};
```
I then downcast it and check in the editor code if it is the object it's looking for:

```
EditorNode* draggingNode = dynamic_cast<EditorNode*>(EditorDragging::getDragableItem());
if (draggingNode != nullptr && ImGui::IsWindowHovered())
{
	draggingNode->move(nullptr);
	EditorDragging::reset();
}
```

That's pretty much it, I believe most people have a similar setup?

**Comment by ocornut** [comment]
I don't really know how any of that code connects to your imgui calls. Surely you must be calling something else that just `ImGui::IsWindowHovered()` to get the whole functionality to work?

> I believe most people have a similar setup?

Unfortunately the answer to that question for many programming problems is often "no"  :)

Anyway, if you have time to look into the `drag_and_drop` git branch to see is that may help you, I'm happy to get feedback on it. That branch will probably be merged in a few weeks.

**Comment by ocornut** [comment]
Closing as solved afaik? @123tris 
(The drag and drop branch was merged into master shortly after you posted this, and hopefully it can be of use to you.!)
