### ISSUE TITLE
Centering Checkbox text.

### ISSUE THREAD

**Issue by csAlphyy** [ocornut/imgui#1480]
So I messed around with the Checkbox bool just to make it smaller, which worked perfectly fine. Now 1 problem I have, is that the text isn't centered;
![image](https://user-images.githubusercontent.com/31821288/33630240-86aa2092-d9fe-11e7-99c3-35246abbd5ec.png)

I was trying to find out for couple of hours now and can't. Can someone point me to the right direction? Thank you.

**Comment by cyanidee** [comment]
mess with RenderTextClipped() arguments, (text_min and text_max if i remember correctly). Also nice GAMESENSE menu copy dude gib sorc cod

**Comment by cyanidee** [comment]
![image](https://user-images.githubusercontent.com/32851089/33676980-8f7f2820-dab7-11e7-9f63-484dfc01f05c.png)
line 7796, mess with 1st argument (try subtracting/adding ImVec2 size from/to it, maybe you will achieve right result)

**Comment by csAlphyy** [comment]
Grr, can't get it to work. This is getting on my nerves.

**Comment by cyanidee** [comment]
if you want, i could try to help you on discord or something cause i had issues with it too :joy: czapek#1122

**Comment by csAlphyy** [comment]
Added bro :d

**Comment by ocornut** [comment]
Closing this as you can handle the conversation offline. This is not really a place for teaching C++ so we can't have those conversations here. Thanks!

**Comment by csAlphyy** [comment]
Checking back to close this, and it's closed. Thank you @cyanidee :)
