### ISSUE TITLE
CollapsingHeader closes upon renaming

### ISSUE THREAD

**Issue by Markus-13** [ocornut/imgui#1481]
SO simple code like this one:
```
	if (ImGui::CollapsingHeader(hdr_name)) {
		ImGui::InputText("Name", hdr_name, 32);
		//...
	}
```
gives next behaviour:
 upon typing (or deletion) of any character header collapses, so u need to open it again and again after each attempt to rename the title...

P.S. Just started to use imgui in my project and it's already not working as expected, very frustrating...

**Comment by Markus-13** [comment]
Well now im confused even more - i've changed my approach and moved InputText for header name into context menu and now it's behaviour even more weird:
1) when i open some header, then rename it - it closes, but when i rename it back to previous name it opens again
2) when i rename some header to the same name as another header has - 2nd header just copies state of the 1st and couldn't be opened/closed anymore

So it seems that headers use some kind of stringtable or something like that where they store their states based on the string given as title... Isn't that awfully bad design decision???

**Comment by ocornut** [comment]
If you want to use a CollapsingHeader() You probably want to use the ### string-id operator to enforce a stable identifier while changing the label.

Note that TreeNode() more commonly used for what you are doing allows you to pass an identifier decorelated from the label.

I don’t know if you created your ‘id’ structure field especially trying to solve this issue or not, but can use your index or pointer as loop identifiers as well, depending what kind of persistence you need for them.

You may move your menu code jnside the loop after CollapsingHeader, and just use if (BeginPopupContextitem()) instead of manually doing it.

**Comment by Markus-13** [comment]
Well, i've tried using TreeNode with TreePop but it's behavior exactly same.
 Adding id with 3 preceding hash symbols after title helped tho.
So it seems if u need to keep open/closed state regardless of the title u need to use overloaded version with additional bool* operand while maintaining open-state by yourself OR adding id like that:
```
		char tmp[48] = "";
		strcat_s(tmp, lrs[i].nm); //<-changeable title
		strcat_s(tmp, "###");
		strcat_s(tmp, lrs[i].id); //<-unique static id
		bool hdr_opn = ImGui::CollapsingHeader(tmp);
```
Looks ugly but works as expected...

**Comment by ocornut** [comment]
You haven't used TreeNode properly then.

You don't need to use ### at all if you are using TreeNode() or TreeNodeEx().
Also you can replicate a CollapsingHeader() by just calling TreeNode with the `ImGuiTreeNodeFlags_CollapsingHeader | ImGuiTreeNodeFlags_NoTreePushOnOpen` flags.

**Comment by ocornut** [comment]
That's the only code you should need:

```
for (SptwIdx i = 0; i < lr_cnt; i++)
{
    bool open = ImGui::TreeNode((void*)i, "%s", lrs[i].nm);
    if (ImGui::BeginPopupContextItem())
    {
       //..
       ImGui::EndPopup();
    }
    if (open)
    {
       //..
       ImGui::TreePop();
    }
}
```

**Comment by ocornut** [comment]
As for:
```
		char tmp[48] = "";
		strcat_s(tmp, lrs[i].nm); //<-changeable title
		strcat_s(tmp, "###");
		strcat_s(tmp, lrs[i].id); //<-unique static id
		bool hdr_opn = ImGui::CollapsingHeader(tmp);
```
May I suggest using helpers for that if you don't want to drive yourself mad.

For example with my simple Str class ( https://github.com/ocornut/str/ ) I would do:
```
                Str64f tmp("%s###%s", lrs[i].nm, lrs[i].id)
		bool hdr_opn = ImGui::CollapsingHeader(tmp.c_str());
```

But essentially it's bad luck you looked at CollapsingHeader() first because it's not an API designed for that sort of data, this is what the underlying TreeNode() API exposes better. You can always create yourself an additional CollapsingHeader() entry point that takes the 2 paramaters and call TreeNode().

**Comment by Markus-13** [comment]
> You haven't used TreeNode properly then.

>That's the only code you should need:
> ```
> for (SptwIdx i = 0; i < lr_cnt; i++)
> {
>     bool open = ImGui::TreeNode((void*)i, "%s", lrs[i].nm);
>     if (ImGui::BeginPopupContextItem())
>     {
>        //..
>        ImGui::EndPopup();
>     }
>     if (open)
>     {
>        //..
>        ImGui::TreePop();
>     }
> }
> ```

Yeah i was using wrong version of TreeNode, and presented code works fine, but for now i'll stick with that approach:
```
namespace _ui
{
	//...
	const ImGuiTreeNodeFlags hdr_flg = ImGuiTreeNodeFlags_CollapsingHeader | ImGuiTreeNodeFlags_NoTreePushOnOpen;
};
//...
void _ui::UiWndScene() {
	if (!ImGui::Begin("Scene Layers", false, _ui::wnd_flg)) {
		ImGui::End();
		return;
	}
	SptwIdx lc = Sptw_BadId;
	for (SptwIdx i = 0; i < lr_cnt; i++){
		bool open = ImGui::TreeNodeEx((void*)lrs[i].id, _ui::hdr_flg, "%s", lrs[i].nm);
		if (lc == Sptw_BadId) if (ImGui::IsItemHovered() && ImGui::IsMouseClicked(1)) {
			lc = i;
			lr_cur = lc;
		}
		if (open) {
			ImGui::PushID(lrs[i].id);
			ImGui::ColorEdit4("Color", lrs[i].cl[0]);
			//more elements to add...
			ImGui::PopID();
		}
	}
	if (lc != Sptw_BadId){
		ImGui::OpenPopup(SptwLrMenu);
	}
	if (ImGui::BeginPopup(SptwLrMenu)) {
		ImGui::Text(lrs[lr_cur].id); ImGui::SameLine();
		if (ImGui::Button("MoveUp")) LyrMove(&lr_cur, -1);
		ImGui::SameLine();
		if (ImGui::Button("MoveDown")) LyrMove(&lr_cur, 1);
		ImGui::InputText("Name", lrs[lr_cur].nm, 32);
		//more elements to add...
		if (ImGui::Button("Close")) ImGui::CloseCurrentPopup();
		ImGui::EndPopup();
	}
	ImGui::End();
}
```
Such logic layout is just more convenient for me atm. I will need some selection (separated from open/closed state) available for only one header at a time, so i utilize `lr_cur` variable in my code anyways and i guess i will just add some manual click-handling and visualization for selected header at first. And further I will need to implement new gui-element from a scratch anyways, cuz i want drag'n'drop functionality and also few built-in buttons for headers...

P.S. at the whole using ImGui in OpenGL app seems pretty good decision, it's fast and ez to use, i just kinda had some problems grasping it yesterday =)

**Comment by ocornut** [comment]
Also note you are using `ImGuiTreeNodeFlags_NoTreePushOnOpen` + `TreePush` you could remove both.

For drag and drag maybe check the drag_and_drop branch and this recent comment in particular:
https://github.com/ocornut/imgui/issues/143#issuecomment-344533856

**Comment by Markus-13** [comment]
> Also note you are using ImGuiTreeNodeFlags_NoTreePushOnOpen + TreePush you could remove both.
Thx for pointing that, but i already got that part)

> For drag and drag maybe check the drag_and_drop branch and this recent comment in particular:
> #143 (comment)
Yeah, it looks exactly as what we want in the final app. I think it will be very good starting point for implementation of our own widgets.

Also as to string handling mentioned before i appreciate your advice, but i don't think i need anything like that right now. In my note about "ugly" code i actually wanted to emphasize that it WORKS regardless of it's look =)
As a guy who has some reverse engineering experience and asm coding as well i have zero problems with "ugly" code, cuz to some extent i can imagine how it will look in the resulting binary and it's rly far from original high-level language representation anyways =)) I know it's bad attitude for programmer but it's just my personal idiosyncrasy to OOP and overall usage of different libraries when u actually could be fine without them (well, in most simple cases at least =). And also i think it's always good to be aware of how your code works at a lower level and when u use some library it could be so time-consuming to understand how it works "under the hood" that u just can't afford that in most cases. IMHO ofc.
 So the main reason we picked ImGui among other solutions was bcuz it looks not too bloated and straightforward and the time we'll need to learn how it works in the deep will be lesser than for other frameworks. And it's simple on the other hand so we can start using it "from the box" after few days. Actually it were just two evenings and at the basic level it works already, feels real good)))

P.S. Thanks for comments, i wasn't expecting so much useful feedback, it's very encouraging.
