### ISSUE TITLE
how to locale the ui? 

### ISSUE THREAD

**Issue by hemmingway** [ocornut/imgui#1482]
how to add multilingual support?

**Comment by hemmingway** [comment]
samply replace the const char*  to const wchar_t ?

**Comment by ocornut** [comment]
Just use different text strings... 
it's not really something that dear imgui will do for you.

**Comment by ocornut** [comment]
dear imgui uses UTF-8 for all strings, not UTF-16, so you need your string encoded as UTF-8 and the data type is const char*

**Comment by ocornut** [comment]
Hello @hemmingway, can we close this issue?
