### ISSUE TITLE
IM_ASSERT(0); // Could not load file.

### ISSUE THREAD

**Issue by iBrooda** [ocornut/imgui#1483]
Loaded the font in the gui like this
```C++			ImGuiIO& io = ImGui::GetIO();
			io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Ruda-Bold.ttf", 13.0f);
			//Begins a new ImGui frame.
			ImGui_ImplDX9_NewFrame();
```

**Comment by ocornut** [comment]
This particular font worked when I tested it here:
https://github.com/ocornut/imgui/issues/1397

**Comment by iBrooda** [comment]
@ocornut so this
```C++
ImGuiIO& io = ImGui::GetIO();
			io.Fonts->AddFontFromFileTTF("C:\Windows\Fonts\Ruda-Bold.ttf", 13.0f);
```
instead of this
```C++
			io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Ruda-Bold.ttf", 13.0f);
			//Begins a new ImGui frame.
			ImGui_ImplDX9_NewFrame();
```

**Comment by ocornut** [comment]
You should use \\ for backslash in string constants. Please read about "string escaping" in C/C++.

It's likely that you can't access a file in this location, maybe the file doesn't exist.

Please use a debugger to step inside AddFontFromFileTTF() and you'll see it is only trying to call fopen()+fread()+fclose() to access your file. 

It's unlikely to be a problem with imgui.
