### ISSUE TITLE
How to set window size?

### ISSUE THREAD

**Issue by suzurose** [ocornut/imgui#1484]
Hi, I want to have a square image button in a single window, and my code is:

    ImGui::SetNextWindowSize(ImVec2(115.0f,120.0f));
    if (!ImGui::Begin("", opened, ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoResize|ImGuiWindowFlags_NoCollapse|ImGuiWindowFlags_NoScrollbar))    
    {
        ImGui::End();
        return;
    }
    
    ImGui::ImageButton(tex, ImVec2(100.0f, 100.0f));
    
    ImGui::End();
 

However, no matter what number I set in `ImGui::SetNextWindowSize` (e.g., `ImGui::SetNextWindowSize(ImVec2(10.0f,120.0f))`), there is always a bigger padding on the right hand side of the image, as shown in the following figure. 

How can I fix that? Thanks very much!

<img width="334" alt="screenshot 2017-12-07 12 13 26" src="https://user-images.githubusercontent.com/34328482/33698511-0f8dd3e6-db48-11e7-8c07-d557155c50ba.png">

**Comment by ocornut** [comment]
This is working for me

```
        if (ImGui::Begin("Test #1484", NULL, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar))
            ImGui::ImageButton(ImGui::GetIO().Fonts->TexID, ImVec2(100.0f, 100.0f));
        ImGui::End();
```
![image](https://user-images.githubusercontent.com/8225057/33710710-c152ec9e-db41-11e7-89ca-93acc682a282.png)

**Comment by suzurose** [comment]
Thanks. It is weird that it does not work with the [openFramworks binding](https://github.com/jvcleave/ofxImGui) (I have updated it to the master branch of Dear Imgui 1.53), as shown below. But it is OK when I use the demo OpenGL3 code. 

I will figure it out and post the answer here.

<img width="344" alt="screenshot 2017-12-07 18 34 44" src="https://user-images.githubusercontent.com/34328482/33711083-a4a0eae2-db7d-11e7-8627-59c336d311e6.png">

**Comment by ocornut** [comment]
Maybe see if you have a non-default value in ImGui::GetStyle().WindowMinSize ?

**Comment by suzurose** [comment]
Cool. Thanks a lot. 🎉 

<img width="212" alt="screenshot 2017-12-07 18 42 14" src="https://user-images.githubusercontent.com/34328482/33711288-7918ae36-db7e-11e7-9858-dbd52b5ea3e8.png">
