### ISSUE TITLE
ImGui::Spacing() with custom height parameter

### ISSUE THREAD

**Issue by hemmingway** [ocornut/imgui#1487]
When i use  ImGui::Spacing() function,   but i want a more  vertical spacing,     i  think should modify the  ImGui::Spacing() function, just like: 

`
IMGUI_API void          Spacing(float h = 0.0f); 
`

`

void ImGui::Spacing(float h)
{
    ImGuiWindow* window = GetCurrentWindow();

   
 if (window->SkipItems)
        return;
    ItemSize(ImVec2(0, h));
}

`

so...., when,  we can use look like this,   add more spacing before....

`
ImGui::Spacing(20.0f);
if (ImGui::CollapsingHeader("System Info")) showSystemInfo();
`

**Comment by ocornut** [comment]
Hello @hemmingway,
I forgot to reply to this, but you can simply use:

`ImGui::Dummy(ImVec2(0.0f, 20.0f));`
