### ISSUE TITLE
IsItemActive() does not work for ColorEdit picker window

### ISSUE THREAD

**Issue by OpenKastle** [ocornut/imgui#1489]
`IsItemActive()` checks whether or not the context's active item ID matches the current window's last item ID.  However, the color edit's color picker is a separate window. 
 In the example below, when the user makes changes using the picker window, `IsItemActive()` returns false because it checks against the last item ID of the current window, not the picker window.

```
ImGui::ColorEdit3(...)
if (ImGui::IsItemActive())
{
} 
```

**Comment by ocornut** [comment]
Hello,
That's correct. 
May I first ask what use you would have of using `IsItemActive()` pattern on the color picker window?

**Comment by OpenKastle** [comment]
I'm interested in knowing when a user is making changes to a UI control.  For my purposes, "making changes" is defined as the user is currently grabbing a UI control, regardless of whether or not they are moving the mouse and changing the control's value.

It isn't sufficient for me to check the return value of the item because it returns false when the mouse stops moving, even if the user is still grabbing the control.  In my particular case, this is undesirable because as soon as my application detects that the user is finished manipulating a control, it renders a high-resolution frame which takes a non-trivial amount of time.  Ideally I would like to wait until the user lets go of the control, not until the user stops moving the mouse.

To conflate the issue, checking for the `ColorEdit`'s return value _is_ a sufficient workaround because it returns true even if the mouse isn't moving.  However, the `DragFloat`s in the picker window still suffer from this problem.

**Comment by ocornut** [comment]
Thanks, that makes sense. I’ll see what I can do. In the meanwhile you might be able to use IsAnyItemActive() as a workaround, but it’ll return true if you use text edit boxes anywhere in the application.

**Comment by ocornut** [comment]
Hello,

I have now made is so that `IsItemActive()` should work.

Also:

> To conflate the issue, checking for the ColorEdit's return value is a sufficient workaround for the square color picker item because it returns true even if the mouse isn't moving.

This is a bug, for being inconsistent with other API, so I have fixed it now (and you should be able to use IsItemActive() instead.

Test code:
```
static ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);
bool modified = ImGui::ColorEdit3("clear color", (float*)&clear_color);
bool hovered = ImGui::IsItemHovered();
bool active = ImGui::IsItemActive();
ImGui::Text("Modified: %d\nHovered: %d\nActive: %d", modified, hovered, active);
```

**Comment by OpenKastle** [comment]
That fixed it, thanks for the assistance!
