### ISSUE TITLE
Combo horizontal alignment issue

### ISSUE THREAD

**Issue by attilaz** [ocornut/imgui#149]
combo label overlaps with next widget on the same line.

repro: https://gist.github.com/attilaz/04beb4319061b371fd32#file-gistfile1-txt-L33

![combo_bug](https://cloud.githubusercontent.com/assets/4198194/6442611/75bd139e-c0f1-11e4-9758-dc50b318f653.png)

**Comment by ocornut** [comment]
Fixed. Thanks again! Another side-effect of what was reported in #145. Sorry for that.

**Comment by attilaz** [comment]
Thanks for the quick fix!
