### ISSUE TITLE
How to draw an .png file into a ImGui window

### ISSUE THREAD

**Issue by MemorableDeath** [ocornut/imgui#1493]
Uhh yeah im trying to draw a image but i have no idea

`ImTextureID my_tex_id = io.Fonts->TexID;`

`float my_tex_w = (float)io.Fonts->TexWidth;`

`float my_tex_h = (float)io.Fonts->TexHeight;`

`ImGui::Image(my_tex_id, ImVec2(my_tex_w, my_tex_h), ImVec2(0, 0), ImVec2(1, 1), ImColor(255, 255, 255, 255), ImColor(255, 255, 255, 128));`

Just copy and pasted the example from imgui_demo but how can i change the ImTextureId to a png?

`
ImTextureID my_tex_id = "D:\DL\_SHIT\xd.JPG";
`

doesnt work

**Comment by ocornut** [comment]
Turning an image into a graphics textures it out of scope of imgui, it's up to your back end code. Please read about OpenGL / DirectX texture loading, whatever graphics backend you are using. Also please read the documentation about ImTextureId and browse/run the demo window code.

**Comment by MemorableDeath** [comment]
k

**Comment by ocornut** [comment]
I have now written a tutorial to cover image file loading for common graphics API:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

**Comment by ocornut** [comment]
It wouldn’t be a good idea to step into that territory no, but for other reasons we might end up including some texture-related helpers in backends eventually.

**Comment by dsantxez** [comment]
Thank you for your answer and work
