### ISSUE TITLE
possible to list things upside down?!

### ISSUE THREAD

**Issue by iBrooda** [ocornut/imgui#1494]
okay so basically im trying to make a log.. however it list's things going down.. is there a way I can make it either clear something when there are x elements in the frame..
currently does this
log 1 here
log 2 here
log 3 here
end of window here
log 4 here and you cant see it

I want it to do this

log 1 here
log 2 here
log 3 here
end of window erase log 1 and now it looks like this

log 2 here
log 3 here
log 4 here...

**Comment by ocornut** [comment]
Sorry @iBrooda this is not really an imgui question but a general programming question.
Dear ImGui is here to present / display the data you feed it, however you feed it.

Depending on how your Log data is stored you may program it to keep at maximum N number of lines by deleting the first lines, or program your ImGui display to only display the last N lines... There are many ways to achieve that but it's not in the scope of this github.

Note also that the demo Log window has code that sets the scrolling to the bottom of the window, so the latest lines are visible while the older ones are still available.
