### ISSUE TITLE
Crash in the Console example when I resize the window to minimal possible height

### ISSUE THREAD

**Issue by geneotech** [ocornut/imgui#1500]
```
sdl_opengl3_example: ../../imgui.cpp:4551: bool ImGui::Begin(const char*, bool*, ImGuiWindowFlags): Assertion `window_size_x_set_by_api && window_size_y_set_by_api' failed.
```

Repro:

- Pulled the repo at https://github.com/ocornut/imgui/commit/b016215c80f64fef17b8aaad843167c3c8d3855b
- built sdl_opengl3_example with ``make``
- run ``./sdl_opengl3_example`` from the folder
- Examples->Console
- Immediately resize the window to decrease the height as much as is possible

**Comment by ocornut** [comment]
@geneotech Should be fixed now. The bug didn't have much side effects because this is the point where the windows are all too small and/or clipped, but adding asserts recently made it more visible.

**Comment by geneotech** [comment]
Much appreciated! Keep up the excellent work!
