### ISSUE TITLE
Sliding menu effect on expanding and collapsing

### ISSUE THREAD

**Issue by elect86** [ocornut/imgui#1501]
Hi,

I'd like some sliding menu, where you click to expand and reduce a window/menu (or whatever component) with a nice sliding effect

something like [this](https://youtu.be/teqYKcj62VA?t=10m54s) (without the other graphics effects, like the logo spinning, of course)

I searched, but I didn't find anything suitable (I'd be happy to be proven wrong)

Is it possible? Would you take into account something similar?

**Comment by ocornut** [comment]
It’s not trivially possible at the moment. Probably possible to hack it somehow by animation window pos/size/size constraints. but this is not the purpose of imgui so I’m not to keen about going there seriously.

**Comment by elect86** [comment]
Pity, but I understand.
