### ISSUE TITLE
Making an ImGui button a perfect circle

### ISSUE THREAD

**Issue by csAlphyy** [ocornut/imgui#1503]
So as the title suggests, I was trying to recreate a perfect circle with ImGui, which came out like this:
![image](https://user-images.githubusercontent.com/31821288/34043851-ab893b2a-e19a-11e7-9908-2654d0a25e43.png)
So as you can tell, it of course isn't a circle but more like a dodecagon. I'm currently doing PushStyleVar(ImGuiStyleVar_FrameRounding, 24.f) which leads me to the picture above. Could someone give me any suggestions as to how I could try and maybe "smooth" out the edges or just point me into another direction with a different correct way. Thank you.

**Comment by ocornut** [comment]
Did you even look at the parameters of the function you are using `ImDrawList::AddCircle()` ?

**Comment by csAlphyy** [comment]
Im using ImGui::Button() With PushStyleVar around it.

**Comment by ocornut** [comment]
Oh then, it's not possible.

**Comment by csAlphyy** [comment]
Hmm, a friend of mine suggested to make the value of the shapes being rendered higher which could work. I guess I'll leave this alone then.
