### ISSUE TITLE
Windowpadding is always 0...

### ISSUE THREAD

**Issue by r0pi314** [ocornut/imgui#1507]
As the title says i cant change the windowpadding... I tried using PushStyleVar, Or just changing the windowspadding by: ImGui::GetStyle().WindowPadding = ImVec2(8, 8); . I want to have itemspacing and windowpadding as 0 to make the menubar buttons look like this...

Here is my code: `void Menu::Render()
{
	ImGui_ImplDX9_NewFrame();

	ImGui::GetIO().MouseDrawCursor = _visible;

	static int active_sidebar_tab = 0;

#pragma region Style
	ImGuiStyle* _style = &ImGui::GetStyle();

	_style->WindowPadding = ImVec2(0, 0);                      
	_style->FramePadding = ImVec2(4, 4);                       
	_style->ItemSpacing = ImVec2(0, 0);                      
	_style->FrameBorderSize = 0.0f;
#pragma endregion

	/********************************************************************************************/

	ImGui::SetNextWindowPos(ImVec2{ ImGui::GetWindowWidth() / 2, ImGui::GetWindowHeight() / 2 }, ImGuiCond_Once);
	ImGui::SetNextWindowSize(ImVec2(800, 700), ImGuiCond_Once);

	if (_visible && ImGui::Begin("noWARE.xyz by wEp", &_visible, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar)) 
	{
		static int page = 0;
		for (int i = 0; i < IM_ARRAYSIZE(sidebar_tabs); i++)
		{
			int distance = i == page ? 0 : i > page ? i - page : page - i;

			if (distance != 0){
				ImGui::GetStyle().Colors[ImGuiCol_Button] = ImVec4(
					0.075,
					0.075,
					0.075,
					1.f
				);
			}

			if (ImGui::Button(sidebar_tabs[i], ImVec2(ImGui::GetWindowSize().x / IM_ARRAYSIZE(sidebar_tabs), 50.f)))
				page = i;

			ImGui::GetStyle().Colors[ImGuiCol_Button] = ImVec4(0.1f, 0.1f, 0.1f, 1.f);

			if (i < IM_ARRAYSIZE(sidebar_tabs) - 1)
				ImGui::SameLine();
		}

		// //
		/**/ImGui::GetStyle().ItemSpacing = ImVec2(8, 8);
		/**/ImGui::GetStyle().FrameBorderSize = 1.f;
		/**/ImGui::GetStyle().WindowPadding = ImVec2(8, 8);
		// // 

		ImGui::Separator();

		switch (page)
		{
		case 0:
			RenderAimTab();
			break;
		case 1:
			RenderVisualsTab();
			break;
		case 2:
			RenderMiscTab();
			break;
		case 3:
			RenderSkinchangerTab();
			break;
		case 4:
			RenderSettingsTab();
			break;
		}

		ImGui::SetCursorPos(ImVec2(8, ImGui::GetWindowHeight() - 58));
		if (ImGui::Button("panic", ImVec2(150, 50))) {
			g_Unload = true;
		}

		ImGui::End();
	}`
![windowpadding](https://user-images.githubusercontent.com/29129288/34071827-218ef6e2-e27d-11e7-89b1-a5bafba292f1.png)

**Comment by ocornut** [comment]
WindowPadding is used by the `Begin()` function, you cannot change it mid-way during the window creation.

**Comment by r0pi314** [comment]
And how could i achive this(like the screenshot) type of menu with windowpadding set to (8,8) but only after menu bars?
