### ISSUE TITLE
ImGui with just OpenGL (no SDL or GLFW)

### ISSUE THREAD

**Issue by elertan** [ocornut/imgui#1509]
Hey, I'm looking to use ImGui as an overlay for an existing project, the project doesn't use any of these wrapper libraries, just native opengl. I'm trying to implement ImGui writing my own RenderDrawLists function, but so far I have no luck with having the GUI drawing on the screen.

I don't have a lot of experience using OpenGL. And I'd love to see some examples using just opengl.
Thanks!

**Comment by ocornut** [comment]
In both of the existing SDL/GLFW examples you mentioned, the RenderDrawLists functions are 100% OpenGL and have nothing to do with SDL or GLFW. You can use copy them.

You may use software like RenderDoc to debug your rendering.

**Comment by elertan** [comment]
Hey @ocornut thanks for helping out.

I'm trying to use the provided GLFW Render implementation, which relies on a few functions that are not provided by GL.h. I have found another header that does provide these functions 'GLext.h' but now I have errors linking against opengl32.lib . But that doesn't have anything to do with ImGui whatsoever.

If I manage to get it to work Ill post my solution on this issue. Feel free to close the issue as well.

Anyways, cheers!

**Comment by ocornut** [comment]
Maybe this will help:
https://www.khronos.org/opengl/wiki/OpenGL_Loading_Library

Closing this as it isn’t directly an imgui issue as you pointed out. If you check out the unmerged pull requests there’s an old one for an OpenGL one without SDL/Glfw which might be helpful.

**Comment by Kareem786-sa** [comment]
i cannot build glfw to cross build for aarch64-poky-linux and it stopped me using ImGui also.
