### ISSUE TITLE
OpenGL GLFW_GL3 implementation idx_buffer_offset always 0 (nullptr)

### ISSUE THREAD

**Issue by elertan** [ocornut/imgui#1510]
Hey, I'm trying to use the GLFW implementation's RenderDrawLists function, but it crashes during 
`glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer_offset);`

Because `idx_buffer_offset` is set to be 0, and only gets updated after the first glDrawElements call.

> glDrawElements (...). This call is attempting to dereference a NULL pointer, which is a red flag that nothing is bound to GL_ELEMENT_ARRAY_BUFFER.

Not sure how to go about this.

**Comment by ocornut** [comment]
This is how it should be, do you actually get a crash in the unmodified example code? Your need vbo vao etc to be bound..

**Comment by elertan** [comment]
The issue probably probably lies in the vbo and vao not being bound. I'm not using the exact unmodified code, because the example code some functions that `GLext.h` provides. These functions are being set at runtime using `wglGetProcAddress();`. I have only changed the calls made to those functions point to the ones I have grabbed at runtime, and that part of the code also executes fine. Other than that I haven't changed anything to the example code. But the game after calls the `glDrawElements();` function the game crashes, and my first impression was that the function call was trying to access something that points to nothing.

As for VAO and VBO:
` glBindVertexArray(g_VaoHandle);` and ` glBindBuffer(GL_ARRAY_BUFFER, g_VboHandle);
        glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)cmd_list->VtxBuffer.Size * sizeof(ImDrawVert), (const GLvoid*)cmd_list->VtxBuffer.Data, GL_STREAM_DRAW);` are being called just as in the example. (unmodified, just copy pasted honestly : ) )

Also sorry for creating issues that might not be related to ImGui.

**Comment by ocornut** [comment]
@elertan 
Also see:
https://github.com/ocornut/imgui/pull/322
https://github.com/ocornut/imgui/issues/350

In particular:
> The problem was that the array and element array buffers must be bound BEFORE calling glEnableVertexAttribArray(...) and glVertexAttribPointer(...): in the opengl3 demo you used a vertex array object: that's probably the reason why the last two calls were missing.

This is probably the issue you were having? Could you confirm?

**Comment by elertan** [comment]
Hi @ocornut 

I'll try to see if this resolves the issue soon. I'll update you on this.

Thanks!

**Comment by ocornut** [comment]
@elertan Did you eventually manage to get back to this issue?

**Comment by elertan** [comment]
Hi @ocornut , I dont recall doing so. If nobody else is having this issue, feel free to close it down.
