### ISSUE TITLE
Customized font doesn't influence to `ImGui::SetTooltip()`

### ISSUE THREAD

**Issue by paladin-t** [ocornut/imgui#1511]
Customized font overrides fine to `ImGui::BeginTooltip()` and `ImGui::EndTooltip()`:

![2](https://user-images.githubusercontent.com/2062224/34090633-5e5b8078-e3f3-11e7-91e7-acbdef54883b.png)

But no influence to `ImGui::SetTooltip()`:

![1](https://user-images.githubusercontent.com/2062224/34090632-5e2484ec-e3f3-11e7-8832-5480cbf34d79.png)

Did I miss anything?

**Comment by ocornut** [comment]
Hello! This bug was already fixed several months ago so I guess you are using an older version?

**Comment by paladin-t** [comment]
Uh, yes, nice to know that. It's just not the right time point to upgrade it for the moment (before releasing a new version). I'll do that in my next releasing.

Sorry for this.
