### ISSUE TITLE
Font weight change?

### ISSUE THREAD

**Issue by cyanidee** [ocornut/imgui#1515]
As in issue, is there any way to change it? My font is too bold in ImGui 😖

**Comment by ocornut** [comment]
It's not possible sorry. Fonts bold/italic variations are usually different sub-font or .ttf file.

If you use imgui and the imgui_freetype wrapper here:
https://github.com/ocornut/imgui_club
It introduces a way to make the font Bolder, but the opposite isn't possible.

**Comment by cyanidee** [comment]
When I am using game's engine drawing, the font is way thicker, and the problem is ImGui somehow makes the font bolder. No idea how. It is Windows's built in font, and the one I am using is the thickest variation of the font. If it isn't possible to make it thicker, thanks for answer ;)

**Comment by ocornut** [comment]
>  If it isn't possible to make it thicker,

This is the opposite of what you asked earlier:

>  My font is too bold 

Thick =~ Bold. 

Which font and which size are you using?
Font rendering is a pretty complex thing. Using imgui_freetype may help depending on how much effort you want to put at it.

**Comment by cyanidee** [comment]
Oh my god, not thick 😑 I meant thin 😂 Sorry for that. And I am using Microsoft Sans Serif and my font size in ImGui init code is set to 14.f

**Comment by ocornut** [comment]
It's not possible to make it more thin.
It's possible to make it more bold, if you use the imgui_freetype code (but you need to setup freetype in your project and it's some work). imgui_freetype with auto-hinting may also improve your rendering quality.

Fonts are this size are tricky to display right and we don't support RGB sub-pixel rendering.

**Comment by cyanidee** [comment]
So if I would set up freetype in my project then there is chance, the font would be drawn "in higher quality" and it would just look better than using ImGui's font system that is built in?

**Comment by ocornut** [comment]
Yes, if you use freetype + that imgui_freetype code.

**Comment by cyanidee** [comment]
Okay, thanks! I will test it out :D

**Comment by ocornut** [comment]
Closing this issue. If you have problem with imgui_freetype (_not_ related to linking freetype itself) feel free free to reopen this.
