### ISSUE TITLE
Sliderfloat min under 0.0f

### ISSUE THREAD

**Issue by ricklepickle** [ocornut/imgui#1516]
I am trying to set a slider float to 0.0001 as the min and 1.0 as the max but for some reason i cant get it to go under 0.0 when trying to move it around

**Comment by ocornut** [comment]
I do not understand your question.
0.0001 is above 0.0 so it won't go under.

Also note that precision is held within the parameter `const char* display_format = "%.3f"` so if you want to display 0.0001 to need to use higher precision, e.g. "%.6f".
