### ISSUE TITLE
IM_PLACEMENT_NEW question

### ISSUE THREAD

**Issue by maxon887** [ocornut/imgui#1517]
Hello, i was studying your code. Exactly this one
```C++
#ifdef IMGUI_DEFINE_PLACEMENT_NEW
struct ImPlacementNewDummy {};
inline void* operator new(size_t, ImPlacementNewDummy, void* ptr) { return ptr; }
inline void operator delete(void*, ImPlacementNewDummy, void*) {}
#define IM_PLACEMENT_NEW(_PTR)  new(ImPlacementNewDummy(), _PTR)
#endif
```
kinda difficut to understand) but
in way you already overridden new/delete why do not put in it custom memory allocation code? Like that:
```C++
#ifdef IMGUI_DEFINE_PLACEMENT_NEW
struct ImPlacementNewDummy {};
inline void* operator new(size_t t, ImPlacementNewDummy) { return CustomMalloc(); }
inline void operator delete(void*, ImPlacementNewDummy) { CustoFree(); }
#define IM_NEW new(ImPlacementNewDummy())
#endif
```

and use it like that:
```C++Type* p = IM_NEW Type();```

**Comment by ocornut** [comment]
The reason for using that dummy type is that somehow it works without including the `<new>` header.

As for your idea, Yes. I actually had some stash doing something similar and will replace it. I wanted to decide how/where to move the allocator helpers first.

**Comment by maxon887** [comment]
thank you, fast reply)

**Comment by ocornut** [comment]
@maxon887 I looked at this today, I couldn't get your syntax to work for IM_NEW (my code actually only had a solution for IM_DELETE)

This is what I ended up with:
```
struct ImNewAllocDummy {};
struct ImNewPlacementDummy {};
inline void* operator   new(size_t, ImNewPlacementDummy, void* ptr) { return ptr; }
inline void  operator   delete(void*, ImNewPlacementDummy, void*)   {} // This is only required so we can use the symetrical new()
inline void  operator   delete(void* p, ImNewAllocDummy)            { ImGui::MemFree(p); }
#define IM_PLACEMENT_NEW(_PTR)  new(ImNewPlacementDummy(), _PTR)
#define IM_NEW(_TYPE)           new(ImNewPlacementDummy(), ImGui::MemAlloc(sizeof(_TYPE))) _TYPE
#define IM_DELETE(_PTR)         delete(ImNewAllocDummy(), _PTR), _PTR = NULL
```

Based on https://github.com/nem0/LumixEngine/blob/4f15b614d79d36499141a54b9593bb9369a070fb/src/engine/iallocator.h
Also see #484

**Comment by maxon887** [comment]
Sorry, but i think 
`#define IM_DELETE(_PTR)         delete(ImNewAllocDummy(), _PTR), _PTR = NULL`
does not call appropriate
`inline void  operator   delete(void* p, ImNewAllocDummy)            { ImGui::MemFree(p); }`
as you expected. please check that actuial ImGui::MemFree is called. also be avare that some ImVectors have explicit MemFree in their destructors

**Comment by maxon887** [comment]
tomorrow i'll check why IM_NEW decision is not working

**Comment by ocornut** [comment]
You are right, my bad. It's hardly noticeable in basic tests because IM_DELETE is only used by functions in Shutdown(). Should be fixed now. Been using the template IM_DELETE in another branch. I don't know how to implement IM_NEW/IM_DELETE in a more symetrical manner. 

We still use MemFree explicitely, in the case you have mentioned, `ImVector<>` don't process construction/destruction.

**Comment by maxon887** [comment]
Hello, why did you said "I couldn't get your syntax to work for IM_NEW (my code actually only had a solution for IM_DELETE)". According to commit https://github.com/ocornut/imgui/commit/9cda86d55a80c9f032af84f657b9fe8e6c7f3f52
you added the same IM_NEW macro, and replace inplaced macrocies. Or i got something wrong?

**Comment by maxon887** [comment]
Or, i've get it, not the same usage pattern. but similar
`DrawList = IM_NEW(ImDrawList)(&context->DrawListSharedData);`

**Comment by ocornut** [comment]
Still not sure how your syntax could have worked (it didn't work as is when I tried, with MSVC 2010 and 2015). Only constraint here is that we want to support C++98 ~ MSVC 2008-2010 with imgui. 
We may raise that constraint at some point in the future but currently it's been working out well.
