### ISSUE TITLE
BOTW graphical glitch

### ISSUE THREAD

**Issue by vonbriggs** [ocornut/imgui#1518]
![capture botw 2](https://user-images.githubusercontent.com/34773291/34302111-5ff91afa-e6e4-11e7-9faa-2845a7dec01b.PNG)
![capture botw](https://user-images.githubusercontent.com/34773291/34302114-6230a3a6-e6e4-11e7-9af1-e7ec027e961f.PNG)
![capture botw 3](https://user-images.githubusercontent.com/34773291/34302119-64be3d36-e6e4-11e7-88e7-90688a7b320c.PNG)
![capture botw 4](https://user-images.githubusercontent.com/34773291/34302122-66908ab0-e6e4-11e7-99a3-a58344b3e9b5.PNG)
![capture botw set](https://user-images.githubusercontent.com/34773291/34302126-69cb95e4-e6e4-11e7-9fe4-b50b1ff12d3a.PNG)
![capture botw set 2](https://user-images.githubusercontent.com/34773291/34302127-6b577a0e-e6e4-11e7-8ab3-cb1476dbd432.PNG)
help

**Comment by ocornut** [comment]
Off-topic, closed, and blocked.
