### ISSUE TITLE
ImDrawListData->FontSize problem

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#1519]
@ocornut: Hi, I'm sorry in advance if I've got no ready to use code at the moment...
However, I'm checking this commit: https://github.com/ocornut/imgui/commit/531c11d5c72890f324c9734ef5c860408b8a7f3d and this issue: https://github.com/Flix01/imgui/issues/32

The problem is that now Lumix Engine's docking does not display text in its tabs.

After debugging a bit I've discovered that the problem lays in one line:
```cpp
// This does nothing:
draw_list->AddText(pos + ImVec2(0, 1), text_color, dock_tab->label, text_end);
// This would work (with hard-coded font size):
// draw_list->AddText(NULL,14.f,pos + ImVec2(0, 1), text_color, dock_tab->label, text_end);
```
That seems to happen because: ```draw_list->_Data->FontSize==0```.

How can we fix this issue ?

**Comment by Flix01** [comment]
Actually looking at the ImGui code nothing seems to be wrong to me...

How can it happen that ```draw_list->_Data->Font``` is OK and ```draw_list->_Data->FontSize==0```?
Is there's a way to trigger an update to ```draw_list->_Data->FontSize```?

**Comment by ocornut** [comment]
Try those:

In `static void SetCurrentWindow(ImGuiWindow* window)`
and `void ImGui::SetWindowFontScale(float scale)`

Add:
`    g.DrawListSharedData.FontSize = g.FontSize;`

Let me know if it fixes it?

**Comment by Flix01** [comment]
Fix N.1:
```cpp
const float font_size = ImGui::GetCurrentWindow()->CalcFontSize();
[...]
draw_list->AddText(NULL, font_size, pos + ImVec2(0, 1), text_color, dock_tab->label, text_end);
```

Fix N.2 **does not work**
```cpp
// In static void SetCurrentWindow(ImGuiWindow* window)
// g.DrawListSharedData.FontSize = g.FontSize; // is already there!
void ImGui::SetWindowFontScale(float scale)
{
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = GetCurrentWindow();
    window->FontWindowScale = scale;
    g.FontSize = window->CalcFontSize();
    g.DrawListSharedData.FontSize = g.FontSize;
}
```

**Comment by ocornut** [comment]
> // is already there

I don't see it:
```
static void SetCurrentWindow(ImGuiWindow* window)
{
    ImGuiContext& g = *GImGui;
    g.CurrentWindow = window;
    if (window)
        g.FontSize = window->CalcFontSize();
}
```

Is `g.FontSize` correct that the time where `g.DrawListSharedData.FontSize` is zero?

**Comment by Flix01** [comment]
@ocornut: Sorry. That indeed fixed the issue (I thught it was ```static void SetCurrentFont(ImFont* font)```).
Fix N.2
```cpp
static void SetCurrentWindow(ImGuiWindow* window)
{
    ImGuiContext& g = *GImGui;
    g.CurrentWindow = window;
    if (window) {
        g.FontSize = window->CalcFontSize();
        g.DrawListSharedData.FontSize = g.FontSize; // Or maybe we can set it to zero if no window...
    }
}
void ImGui::SetWindowFontScale(float scale)
{
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = GetCurrentWindow();
    window->FontWindowScale = scale;
    g.FontSize = window->CalcFontSize();
    g.DrawListSharedData.FontSize = g.FontSize; // New, but no fix!
}
```

Thanks for your support.

**Comment by ocornut** [comment]
Committed the fix now. 
(Best not to close an issue until it's actually fixed in Master :)

**Comment by Flix01** [comment]
OK.
