### ISSUE TITLE
Feature request: Smooth rendering

### ISSUE THREAD

**Issue by raegnar** [ocornut/imgui#152]
Is it possible to get optional support for smooth rendering of widgets like that in the [memononen](https://github.com/memononen/imgui) fork?

**Comment by ocornut** [comment]
Yes will do eventually, but probably not a top priority.
Duplicate of #133

**Comment by ocornut** [comment]
Closed as duplicate. Will do !

**Comment by ocornut** [comment]
I have merged and moved Mikko changes into a new branch until they are sorted out
https://github.com/ocornut/imgui/tree/2015-03-antialiased-primitives

Please follow #133 for future updates.
