### ISSUE TITLE
frame border glitch

### ISSUE THREAD

**Issue by terryadavis** [ocornut/imgui#1520]
https://imgur.com/a/GC5Uj

it really isn't noticeable there but when it's not a tiny picture but on my monitor, it's very visible

**Comment by terryadavis** [comment]
at the top left corner zoom in a bit

**Comment by ocornut** [comment]
I cannot reproduce the issue. Are you on on the latest version, do you have any mod? 
![image](https://user-images.githubusercontent.com/8225057/34326003-0d8ad3b0-e8a3-11e7-99d3-c72402f950e0.png)

**Comment by ocornut** [comment]
PS: Please use github attachment for images and not imgur, anything you put on imgur will disappear at some point, making those issues less useful for future readers.
