### ISSUE TITLE
Combo fails to select an item

### ISSUE THREAD

**Issue by Parasite03** [ocornut/imgui#1521]
Hello!
I'm using ImGui to create the interface for a tool for my C++ project.

	if (ImGui::BeginCombo("", "Select Algorithm"))
	{
		for (auto algorithm : algorithms)
			if (ImGui::Selectable(algorithm.first.c_str()), algorithm.second == selected_algorithm_)
			{
				selected_algorithm_ = algorithm.second;
			}
		
		ImGui::EndCombo();
	}

algorithms is an std::map, the key is a string and the value is a member of an enum
This code results in a combo box that has all the items I want, but when I try to select an item it doesn't want to do it.
Thanks.

**Comment by ocornut** [comment]
Your combo needs an identifier (here you used an empty string), and you are always passing “select algorithm” as a preview string so it’s always going to display that regardless of the current selection.

**Comment by Parasite03** [comment]
Thanks!
The identifier made no difference, but fixing the preview string helped.
I also noticed a really strange bracket misplacement in the if,  which caused unwanted behavious. Not sure how it even worked.

**Comment by ocornut** [comment]
Without the preview string the combo worked (set the value correctly) but you wouldn’t see it in the combo itself.

In C++ you can use the comma (,) operator to sequence multiple statements. So when you write  A,B both A and B are evaluated and it returns B. It’s not commonly used except in for loops.
So with your mistake your code did if (A, B) where B was the boolean testing for selection and that’s the condition for the if.
