### ISSUE TITLE
Menu bar (was: Tabs Or Options at top of screen)

### ISSUE THREAD

**Issue by SuicidehookDev** [ocornut/imgui#1522]
So on my current project i had tabs in a window to organize everything but now want to make tabs like the one in this screenshot
![image](https://user-images.githubusercontent.com/32649794/34348759-c357b694-ea5c-11e7-9097-e150a1e450b1.png)
 
![image](https://user-images.githubusercontent.com/32649794/34348764-cc559162-ea5c-11e7-9692-08abc581679d.png)
as you can see i want them at the top of the screen when i open my menu but cant find anything on how to do this thank you for any response

**Comment by ocornut** [comment]
See BeginMainMenuBar().
Generally, please run and read the demo function to find what’s possible and how things are called.
