### ISSUE TITLE
Font loading

### ISSUE THREAD

**Issue by ViralAphinity** [ocornut/imgui#1524]
I'm attempting to load an icon set for an array that I've made, whenever I open the menu it renders all the characters as massive laggy blocks. The process drops to 1 FPS no matter the window I'm in. Am I supposed to use different parameters in anything?

`ImGui::Begin("quality menu", &bing, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_ShowBorders | ImGuiWindowFlags_NoResize);
{
	ImGuiIO& io = ImGui::GetIO();
	ImFont* Icons = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Icons.ttf", 20.0f);
        io.Fonts->Build();
	const char* tabs[] = {
		"=",
		"[",
		">",
		"_",
		"*",
		"?",
		";"
	};

	ImGui::BeginChild("Main1", ImVec2(150, 0), true, ImGuiWindowFlags_NoResize);
	{
		ImGui::NewFrame();
		ImGui::PushFont(Icons);
		for (int i = 0; i < IM_ARRAYSIZE(tabs); i++)
		{
			int distance = i == page ? 0 : i > page ? i - page : page - i;

			ImGui::GetStyle().Colors[ImGuiCol_Button] = ImVec4(
				Settings::UI::mainColor.Color().Value.x - (distance * 0.035f),
				Settings::UI::mainColor.Color().Value.y - (distance * 0.035f),
				Settings::UI::mainColor.Color().Value.z - (distance * 0.035f),
				Settings::UI::mainColor.Color().Value.w);

			ImGui::GetStyle().Colors[ImGuiCol_Button] = Settings::UI::mainColor.Color();

			if (ImGui::Button(tabs[i], ImVec2(ImGui::GetWindowSize().x - 15, ImGui::GetWindowSize().y / IM_ARRAYSIZE(tabs) - 6)))
				page = i;

			i < IM_ARRAYSIZE(tabs) - 1;
		}
		ImGui::PopFont();
		ImGui::EndChild();
	}
`

**Comment by ocornut** [comment]
Font needs to be built into the font atlas, you generally can't load a font in the middle of an imgui frame (like you did) because you need to call the atlas Build() or GetTexDataXX functions to build it.

**Comment by ocornut** [comment]
> The process drops to 1 FPS no matter the window I'm in. Am I supposed to use different parameters in anything?

And this is another effect of trying to reload the font every frame like your code does.
