### ISSUE TITLE
Columns: hitting an assertion when changing column count

### ISSUE THREAD

**Issue by franciscod** [ocornut/imgui#1525]
```
imgui.cpp:11031: void ImGui::BeginColumns(const char*, int, ImGuiColumnsFlags): Assertion `columns-
>Columns.Size == columns_count + 1' failed.
```

Working on some repro code!

**Comment by franciscod** [comment]
Before this (line 1552 of imgui_demo.cpp)

```c++
        // Basic columns
        if (ImGui::TreeNode("Basic"))
```

add:

```c++
        if (ImGui::TreeNode("Dynamic (broken)?")) {
          static int dynamic_column_count = 3;
          ImGui::Columns(dynamic_column_count, "asd", false);
          for (int n = 0; n < dynamic_column_count; n++) {
            ImGui::Text("Lol %d", n);
            ImGui::NextColumn();
          }
          ImGui::Columns(1);
          if(ImGui::Button("Use 4 columns now")) {
            dynamic_column_count = 4;
          }
          ImGui::TreePop();
        }
```

**Comment by franciscod** [comment]
If this is not a bug, how can I change the the columns count? Maybe change the columns id altogether? (add the count to the id?)

**Comment by ocornut** [comment]
> Maybe change the columns id altogether? (add the count to the id?)

The code path if you don't specify an identifier (passing `NULL` instead of "asd") does exactly that.
I think it could be improved on imgui side, but the question is: what do you expect to happen when changing the column count, in term of columns sizing/placement? 

-Omar

**Comment by ocornut** [comment]
> what do you expect to happen when changing the column count, in term of columns sizing/placement?

I think the answer is obvious if borders are disabled (as in your example) as you expect columns to always be evenly spaced.
I'll find a decent solution for when borders are enabled and try to implement that as wel.

Code
```
ImGui::Begin("Issue #1525");
if (ImGui::TreeNode("Dynamic (broken)?")) 
{
    static int dynamic_column_count = 4;
    ImGui::Columns(dynamic_column_count, "asd", false);
    for (int n = 0; n < dynamic_column_count; n++) 
    {
        ImGui::Text("Lol %d", n);
        ImGui::NextColumn();
    }
    ImGui::Columns(1);
    ImGui::DragInt("columns count", &dynamic_column_count, 0.1f, 1, 10);
    ImGui::TreePop();
}
ImGui::End();
```

**Comment by ocornut** [comment]
(Reposted with modifications) 

> what do you expect to happen when changing the column count, in term of columns sizing/placement?

I think the answer appears obvious if borders are disabled (as in your example) as you expect columns to always be evenly spaced, but there's still the issue that user could call `SetColumnWidth()`, `SetColumnOffset()` and break that assumption.

I'll look for a simple/decent solution toward allowing it, but would be interested in hearing your own use case.

Code
```
ImGui::Begin("Issue #1525");
if (ImGui::TreeNode("Dynamic (broken)?")) 
{
    static int dynamic_column_count = 4;
    ImGui::Columns(dynamic_column_count, "asd", false);
    for (int n = 0; n < dynamic_column_count; n++) 
    {
        ImGui::Text("Lol %d", n);
        ImGui::NextColumn();
    }
    ImGui::Columns(1);
    ImGui::DragInt("columns count", &dynamic_column_count, 0.1f, 1, 10);
    ImGui::TreePop();
}
ImGui::End();
```

**Comment by franciscod** [comment]
Thanks Omar for having a look :)

>The code path if you don't specify an identifier (passing NULL instead of "asd") does exactly that.
Nice! I'll check that out.

> what do you expect to happen when changing the column count, in term of columns sizing/placement?
On my usecase, I use SetColumnWidth on each column. And sometimes I want to insert columns at arbitrary places and handle the widths myself. So that case is also almost trivial. I'm not sure what to do in the middle (some fixed columns, and others evenly spaced)... I keep thinking of a standard DOM reflow on HTML/CSS but that's a beast and has its own issues so maybe it's not an useful analogy :)

**Comment by ocornut** [comment]
I think for now it wouldn't hurt to offset the given ID with the columns count, I'm going to just do it. So in that situation the columns setting will differ.

**Comment by ocornut** [comment]
Hello @franciscod, for now I am clearing the columns offset when changing count. 
I'll keep a note when Columns gets redesigned that something better is desirable (probably in columns v2).

**Comment by franciscod** [comment]
Cool! Thanks! Simple solution :)
