### ISSUE TITLE
push result from ImGui::InputText to a vector

### ISSUE THREAD

**Issue by Jakobzzz** [ocornut/imgui#1530]
Hello,
I'm currently working on a layer settings menu option for my game engine and I have stumbled across 
a problem when I want to add the result from ImGui::InputText to a `std::vector<const char*> ...` The situation can be illustrated below:

![gif](https://i.imgur.com/9NO6tyi.gif)

As you can see I'm able to overwrite the new layer with new text which I should not be able to do since this is just another item added to my layers vector:

```
//Show layers
for (auto c : m_scene->getLayers())
{
    ImGui::Text("Layer: %s", c);		
    ImGui::Separator();
}

//m_layerName is of the type std::vector<char>
//Input name for new layer				
if (ImGui::InputText("", m_layerName.data(), m_layerName.size(), ImGuiInputTextFlags_EnterReturnsTrue))
     m_scene->getLayers().push_back(m_layerName.data());
```
I believe I'm doing something silly, but I can't come up with a solution. Any  suggestions?

Thanks.

**Comment by ocornut** [comment]
I don't know what `m_scene->getLayers()` is but presumably you are storing pointers e.g. `char *` in there, and which your push_back call you are only copying a pointer to the current address used by `m_layerName()` (which might change if you resize that that vector).

If you are confused by strings and pointers the best way is to use `std::string` to store your layer name strings. When you create a `std::string` from a `char*` it will copy its contents.

Hope it helps.
I have to close this issues that we're straying far off the topic of imgui here.
