### ISSUE TITLE
error dx9

### ISSUE THREAD

**Issue by kyrox02** [ocornut/imgui#1532]
help me please

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "bool __cdecl ImGui_ImplDX9_Init(void *,struct IDirect3DDevice9 *)" (?ImGui_ImplDX9_Init@@YA_NPEAXPEAUIDirect3DDevice9@@@Z)

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "__int64 __cdecl ImGui_ImplDX9_WndProcHandler(struct HWND__ *,unsigned int,unsigned __int64,__int64)" (?ImGui_ImplDX9_WndProcHandler@@YA_JPEAUHWND__@@I_K_J@Z)

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: void __cdecl ImGuiIO::AddInputCharactersUTF8(char const *)" (?AddInputCharactersUTF8@ImGuiIO@@QEAAXPEBD@Z)	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "void __cdecl ImGui_ImplDX9_NewFrame(void)" (?ImGui_ImplDX9_NewFrame@@YAXXZ)

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "bool __cdecl ImGui::ColorEdit3(char const *,float * const,int)" (?ColorEdit3@ImGui@@YA_NPEBDQEAMH@Z)	

	Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "void __cdecl ImGui::End(void)" (?End@ImGui@@YAXXZ)	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "void __cdecl ImGui::Spacing(void)" (?Spacing@ImGui@@YAXXZ)

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "struct ImGuiIO & __cdecl ImGui::GetIO(void)" (?GetIO@ImGui@@YAAEAUImGuiIO@@XZ)

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "bool __cdecl ImGui::Checkbox(char const *,bool *)" (?Checkbox@ImGui@@YA_NPEBDPEA_N@Z)

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "bool __cdecl ImGui::SliderFloat(char const *,float *,float,float,char const *,float)" (?SliderFloat@ImGui@@YA_NPEBDPEAMMM0M@Z)

**Comment by ocornut** [comment]
You forgot to link with the imgui cpp files.
If you have a problem of that sort and fix it yourself it would be courtesy to write down the solution for future readers.

**Comment by ameyakale-tcd** [comment]
Could anyone put here the solution for the above error, I'm facing the same atm. 
Thanks in advance

**Comment by Blqtent** [comment]
@ameyakale-tcd do the /FORCE option in all options in the linker section
1. go to Linker in project properities
2. go to all options
3. type FORCE
4. make the setting true
5. recompile
