### ISSUE TITLE
How to customize titlebar elements?

### ISSUE THREAD

**Issue by halcyonx** [ocornut/imgui#1539]
Hi! There is way to change some properties of title bar or close button? I want to change height of my title bar and size/color of close button.

**Comment by ocornut** [comment]
Hello,

The title bar height is FontSize + FramePadding.y * 2, so you can possibly use PushStyleVar(ImGuiStyleVar_FramePadding, ...) to alter the frame padding before Begin(), then restore a more proper value for your widget.

The color of the close button is exposed in the style colors. The size is based on the title bar height. The shape is not customizable for now (although I expect to change it at some point).

**Comment by ocornut** [comment]
Closing this as answered.
