### ISSUE TITLE
Resizable columns

### ISSUE THREAD

**Issue by emoon** [ocornut/imgui#154]
Hi,

I wonder if it's possible to support resizable columns (that the user can drag with the mouse) ? Looking at the header file there are these 3 functions that seems related to it but has no comment and I haven't looked at the code yet on what they actually do:

```C++
IMGUI_API float         GetColumnOffset(int column_index = -1);
IMGUI_API void          SetColumnOffset(int column_index, float offset);
IMGUI_API float         GetColumnWidth(int column_index = -1);
```

**Comment by ocornut** [comment]
Columns are resizeable by default with the mouse, if you click on the column line it should work :)

The column API #125 still have major limitations. The two main things that are missing are
- Being able to set the default column position and a general sizing policy.
- Have proper column headers (clickable, excluded from scrolling region, etc.)

**Comment by emoon** [comment]
Ah it actually do work :+1: :)

Then I guess something that would be is to optionally being able to change the mouse cursor on such events (Allowing the user to register callbacks should be good enough and when a sizing event call the callback with HorizontalResize/VerticalResize and such)

I do something similar for this in ProDBG for resizing of the docking windows (which happens outside ImGui)

Here is the Mac impl:

https://github.com/emoon/ProDBG/blob/master/src/prodbg/ui/mac/cursor_mac.mm

**Comment by ocornut** [comment]
Oh I suppose because you have a custom theme it didn't light up the column in a different color when hovering?

Good idea on the cursors, will add a new bug # for that.

**Comment by emoon** [comment]
Correct. I had fiddled around a bit too much with it so I didn't see the highlight :) I have fixed this locally now and can see it.

The cursor this isn't very high priority but should hopefully be fairly easy to add and its much more natural to resize with a resize cursor as one is used to it.

**Comment by ocornut** [comment]
Closing this and opened #155 for the mouse cursors.
The styling system isn't very good at the moment, it's too hard to get a style done unless you focus on 2-3 colors. But that's low priority.

**Comment by emoon** [comment]
Agreed. Not such a big deal and thanks for #155 :)
