### ISSUE TITLE
Suggestion for IsAnyWindowHovered() function replacement ?

### ISSUE THREAD

**Issue by OldSnake22** [ocornut/imgui#1544]
Hello Omar, 

Do you have some suggestion for a quick way to know if any IMGUI window is hovered now that those function are marked as obsolete ? 

Thank you !

**Comment by ocornut** [comment]
Have you tried searching for `IsAnyWindowHovered()` in the code at all?

**Comment by OldSnake22** [comment]
Oh my bad ! I was not thinking that the underlying code was so easy... I think it's time for me to go to bed. Sorry for this and thank you for your truly great work !

**Comment by ocornut** [comment]
I try to make it that every API breakage/obsolete functions gets a redirection + is documented in the API BREAKING CHANGES section. I'm curious about how you even found that the function was marked as obsolete without stumbling on the replacement?
