### ISSUE TITLE
Is it possible to add a layer on top of imgui, for retained mode UI operation? Suggestions?

### ISSUE THREAD

**Issue by cesss** [ocornut/imgui#1547]
Hi,

In some of my apps, immediate mode is fine, but other apps really benefit from a retained mode UI.

I'm wondering if I could encapsulate imgui somehow inside of a C++ layer that converted the paradigm from immediate mode to retained mode?

Note that this encapsulation layer should avoid polling, I mean, I want the CPU to be idle when there's no input in a retained mode UI.

Would this be easy to do? Any suggestions? Thanks!

**Comment by ocornut** [comment]
If you want the CPU to be idle, just avoid calling imgui stuff when there's no inputs, or render at lower frequency if you need animation. If you want to keep a "game" view running at full framerate you may rely on callback to render your game view along with the imgui render data, and only call in NewFrame() and create window when there's UI inputs.

As for the general question, it's too vague to be answered. If you want to defeat the purpose of dear imgui you may do so, but you may be better off not using it at all then..

**Comment by cesss** [comment]
Maybe immediate mode is the purpose of dear imgui (it's named after it anyway), but even if it is, it's not the only goal you achieved. In fact, I found imgui from searching for the other goals you achieved. Namely:

- Trivial to build (the less dependencies, the better).
- C/C++ only (no Java, no JS, no HTML5, no Python, no nothing: just pure C/C++).
- UI rendered with OpenGL 2.x (no 3.x requirements).
- Friendly with old compilers (away from the trend of using the latest C++ 2037 novelties).
- Non-copyleft open source (LGPL is not suitable for me).
- Multiline text input widget.
- UTF-8 support.
- Aesthetically pleasant widgets, or at least suitable to be tuned for nice minimalistic aesthetics.

Now, if you search for the above features, you'll find that dear imgui doesn't have many competitors... in fact, maybe it's the only one providing the whole of the list.

So, while immediate mode might be your purpose, maybe dear imgui is still my best choice even if I need retained mode.

Now, back to my question, and, on second twice, I think a retained mode layer should be trivial to write, as any GUI system must work internally as immediate mode. It's just a matter of storing the GUI in memory, and whenever you get a mouse/keyboard event from the OS, tell imgui about the event and draw the GUI in immediate mode from the memory representation that you stored when the GUI was created.

So, I think I must be able to do this without modifying the imgui source code.

Finally, I don't have anything against immediate mode, in fact, I consider it a plus that I could use imgui in immediate mode for games or realtime simulations, for example. It's just that I also need retained mode for some other apps.

Thanks a lot for developing dear imgui!!

**Comment by ocornut** [comment]
> It's just a matter of storing the GUI in memory, and whenever you get a mouse/keyboard event from the OS, tell imgui about the event and draw the GUI in immediate mode from the memory representation that you stored when the GUI was created.

But I don't see how that would differ from just running the immediate mode code when you get a mouse/keyboard event from the OS. your solution can ONLY be slower by adding an extra layer.

**Comment by cesss** [comment]
Not sure. Basically, I think every GUI system needs immediate mode behaviour in its lowest level kernel code, so ideally you should be able to get zero penalty from immediate mode (provided the code is very efficient: for example you do **not** want to redraw the UI when you get a mouse/keyboard event --you only want a geometry check of the event coordinates with the widgets geometry).

Anyway, I'm thinking in some apps that I already developed for other UI libraries years ago. Modifying their UI logic to follow the immediate mode paradigm would mean rewriting big portions of the application, while changing to another retained mode lib would be much less effort.

Well, I'm closing this issue, I think everything is fine :-)

**Comment by chip1092** [comment]
I think Google Flutter could be considered in this discussion. I think it has been designed somehow in between. Working in immediate mode by taking retained mode into consideration, consider widget and render trees, dirty flag and the way build system will be triggered and synched accordingly. I am not telling this design choice could be a game changer or a great boost, but this is an area that worth time and efforts in a controlled manner.
I am thinking about using ImGui in developing a trading platform. There are many things which should be considered in design and development. But ImGui is one of the candidates at first place.
Tks
