### ISSUE TITLE
Increasing Mainmenubar size

### ISSUE THREAD

**Issue by SuicidehookDev** [ocornut/imgui#1548]
i want to increase my mainmenubar size including text and the bar

Currently i have this and would like to increase it to be thicker
![image](https://user-images.githubusercontent.com/32649794/34892647-0084ef34-f82a-11e7-966f-1a13890c2cd3.png)

**Comment by ocornut** [comment]
Use 
`ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ...);` / `ImGui::PopStyleVar()` like everywhere else.

**Comment by MishraMohit21** [comment]
> Use `ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ...);` / `ImGui::PopStyleVar()` like everywhere else.

I tried it but didn't work.
The Menu Item text was displaced but the bar height did not change

**Comment by GamingMinds-DanielC** [comment]
> I tried it but didn't work. The Menu Item text was displaced but the bar height did not change

For the menu bar height to change you need to also have the style set while opening the window. That's where the space for the menu bar is reserved. No idea how this was handled in 2018, but unfortunately that affects the window title as well, so that's not a great solution.
