### ISSUE TITLE
Mouse cursor types

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#155]
Add a way for tell the application of which type of mouse cursor to display.
Applications can handle it or not.
The windows examples can support this.

Proposed enumeration
- normal cursor
- text input cursor
- resize horizontal
- resize vertical
- resize upper-left <> lower-right
- resize lower-left <> upper-right
- move

Extra (can't think of where imgui can send this, but nice to have so the cursor can "set" it themselves)
- disabled
- pen 

Applications are free to handle all the "resize" cursor the same way.

( Suggested here: https://github.com/ocornut/imgui/issues/154 )

**Comment by ocornut** [comment]
That's done. The hardest part was embedded the cursors in code (imgui can draw cursors for you) and then reducing the code space, first version took 200 lines. Ended up with this beauty:

```
ImGui::GetMouseCursor()
ImGui::SetMouseCursor()

// Enumeration for GetMouseCursor()
enum ImGuiMouseCursor_
{
    ImGuiMouseCursor_Arrow = 0,
    ImGuiMouseCursor_TextInput,
    ImGuiMouseCursor_Move,                  // Unused by ImGui
    ImGuiMouseCursor_ResizeNS,              // Unused by ImGui
    ImGuiMouseCursor_ResizeEW,              // Unused by ImGui
    ImGuiMouseCursor_ResizeNESW,            // Unused by ImGui
    ImGuiMouseCursor_ResizeNWSE,
    ImGuiMouseCursor_Count_
};
```

```
    const char texture_data[TEX_DATA_W*TEX_DATA_H+1] =
    {
        "..-         -XXXXXXX-    X    -           X           -XXXXXXX          -          XXXXXXX"
        "..-         -X.....X-   X.X   -          X.X          -X.....X          -          X.....X"
        "---         -XXX.XXX-  X...X  -         X...X         -X....X           -           X....X"
        "X           -  X.X  - X.....X -        X.....X        -X...X            -            X...X"
        "XX          -  X.X  -X.......X-       X.......X       -X..X.X           -           X.X..X"
        "X.X         -  X.X  -XXXX.XXXX-       XXXX.XXXX       -X.X X.X          -          X.X X.X"
        "X..X        -  X.X  -   X.X   -          X.X          -XX   X.X         -         X.X   XX"
        "X...X       -  X.X  -   X.X   -    XX    X.X    XX    -      X.X        -        X.X      "
        "X....X      -  X.X  -   X.X   -   X.X    X.X    X.X   -       X.X       -       X.X       "
        "X.....X     -  X.X  -   X.X   -  X..X    X.X    X..X  -        X.X      -      X.X        "
        "X......X    -  X.X  -   X.X   - X...XXXXXX.XXXXXX...X -         X.X   XX-XX   X.X         "
        "X.......X   -  X.X  -   X.X   -X.....................X-          X.X X.X-X.X X.X          "
        "X........X  -  X.X  -   X.X   - X...XXXXXX.XXXXXX...X -           X.X..X-X..X.X           "
        "X.........X -XXX.XXX-   X.X   -  X..X    X.X    X..X  -            X...X-X...X            "
        "X..........X-X.....X-   X.X   -   X.X    X.X    X.X   -           X....X-X....X           "
        "X......XXXXX-XXXXXXX-   X.X   -    XX    X.X    XX    -          X.....X-X.....X          "
        "X...X..X    ---------   X.X   -          X.X          -          XXXXXXX-XXXXXXX          "
        "X..X X..X   -       -XXXX.XXXX-       XXXX.XXXX       ------------------------------------"
        "X.X  X..X   -       -X.......X-       X.......X       -    XX           XX    -           "
        "XX    X..X  -       - X.....X -        X.....X        -   X.X           X.X   -           "
        "      X..X          -  X...X  -         X...X         -  X..X           X..X  -           "
        "       XX           -   X.X   -          X.X          - X...XXXXXXXXXXXXX...X -           "
        "------------        -    X    -           X           -X.....................X-           "
        "                    ----------------------------------- X...XXXXXXXXXXXXX...X -           "
        "                                                      -  X..X           X..X  -           "
        "                                                      -   X.X           X.X   -           "
        "                                                      -    XX           XX    -           "
    };
```

I have yet to make the example honor the cursor type at the OS level.

**Comment by ocornut** [comment]
I initially intended to have the example apps honor the cursor shapes using OS cursor facilities but it's too much work to consider portability and without straying off standard OS cursor shapes. So this is the user responsibility to decide how they want to handle that. The "software" cursor rendering is always available and useful on console or embedded platforms. I don't expect people to use it on computers because it'll be tied to the application framerate where the OS one isn't.
Potentially we could expose a facility to retrieve the imgui cursor texture data in some form that the user can pass to their OS/library.

Closing now because it's really low priority and hasn't been requested.

**Comment by emoon** [comment]
Thanks :) I will use this when my target OS doesn't support it (as you stated as one of the use-cases above)

**Comment by colesnicov** [comment]
Hi Omar.
Implementation of cursor pointer will not? :)

**Comment by ocornut** [comment]
@colesnicov 
> Implementation of cursor pointer will not? :)

ImGui can already render a software mouse cursor, but those don't refresh as smoothly as a hardware cursor. Prefer to use OS cursor facilities if you can.

**Comment by aeris170** [comment]
@ocornut is ImGuiMouseCursor_Move removed in the latest version? Can't seem to find it.

**Comment by ocornut** [comment]
@aeris170 There was never a `ImGuiMouseCursor_Move`. You may be referring to `ImGuiMouseCursor_Hand` (from 1.63) or `ImGuiMouseCursor_ResizeAll`.

**Comment by aeris170** [comment]
@ocornut forgive me if I'm not getting something here. In your second post, the one with the code, I see the enum "ImGuiMouseCursor_Move", but now you say it was never there to begin with. Can you explain why this is the case? Also, if there is not a move cursor (something like ✊, not 👆), how can I render it?

**Comment by aeris170** [comment]
OK, now I see. I was looking for "ResizeAll". Thank you for your help! :)
