### ISSUE TITLE
Menus with columns

### ISSUE THREAD

**Issue by codecat** [ocornut/imgui#1550]
Is this possible? Here's a quick mockup in mspaint of what I mean:

![](https://i.imgur.com/o9K2NGr.png)

**Comment by ocornut** [comment]
Selectable() is almost the same as MenuItem(), you can use Selectable + Columns in your menu.

**Comment by codecat** [comment]
Thanks! I'm going to give it a shot.

**Comment by codecat** [comment]
Hm, I might be doing it wrong. I get this:

![](https://i.imgur.com/xg8djbH.png)

With this code:

```cpp
ImGui::Columns(2, "locations");
if (ImGui::Selectable(str, false, ImGuiSelectableFlags_SpanAllColumns)) {
	// do something...
}
ImGui::NextColumn();
ImGui::TextUnformatted("Foo");
ImGui::Columns();
```

**Comment by ocornut** [comment]
So the thing is that `Columns()` is currently a container that fits within the available width, and your menu window doesn't have anything else so right now you need to specify a width.

You can either use `SetNextWindowContentWidth()` before `BeginMenu()`:

```
ImGui::SetNextWindowContentWidth(200);
if (ImGui::BeginMenu("Menu"))
{
    ImGui::Columns(2, "locations");
    if (ImGui::Selectable("Hello", false, ImGuiSelectableFlags_SpanAllColumns)) {
        // do something...
    }
    ImGui::NextColumn();
    ImGui::TextUnformatted("Foo");
    ImGui::Columns();
    ImGui::EndMenu();
}
``` 

Or just moving the cursor within your window will also increase this width:

```
if (ImGui::BeginMenu("Menu"))
{
    ImGui::Columns(2, "locations");
    if (ImGui::Selectable("Hello", false, ImGuiSelectableFlags_SpanAllColumns)) {
        // do something...
    }
    ImGui::NextColumn();
    ImGui::TextUnformatted("Foo");
    ImGui::Columns();
    ImGui::SetCursorPosX(200);
    ImGui::EndMenu();
}
```

Or outputing other items in that menu.

**Comment by codecat** [comment]
Ah cool, that solved my problem, thanks! 😊 

Additionally, I also used `SetColumnWidth` to have proper widths:

```cpp
ImGui::Columns(2, "locations");
ImGui::SetColumnWidth(0, 300.0f);
ImGui::SetColumnWidth(1, 100.0f);
```
