### ISSUE TITLE
Imgui::Imagebutton

### ISSUE THREAD

**Issue by molnia2145** [ocornut/imgui#1552]
I'm try to create dll project, and I want to insert a picture there, I turned it into bytes, but I can not draw it
Can you help me?
```
IDirect3DTexture9 *tImage = nullptr;
if (tImage == nullptr)D3DXCreateTextureFromFileInMemoryEx(YouD3Device, &NameArry, sizeof(NameArry),132, 132, D3DX_DEFAULT, 0, D3DFMT_UNKNOWN, D3DPOOL_MANAGED, D3DX_DEFAULT, D3DX_DEFAULT, 0, NULL, NULL, &tImage);
BYTE NameArry[...] =
{            . . .             };
ImGui::Image(tImage, ImVec2(132, 132));
ImGui::ImageButton(tImage, ImVec2(132, 132));

**Comment by ocornut** [comment]
Sorry can't help you without a Minimal, Complete, and Verifiable example (https://stackoverflow.com/help/mcve), without basic amount of context and without a polite thanks.  Dear ImGui works for what you are trying to do, 

I would appreciate if cheaters stopped coming here to ask questions as the level of questions are either clueless, either disrespectful, either harming this project. You guys have forums with hundreds of other dear imgui users doing the same thing, please figure things out within your community.
