### ISSUE TITLE
Assertion failed on SDL2 OpenGL3 Example

### ISSUE THREAD

**Issue by kitebizelt** [ocornut/imgui#1555]
Whenever I try to run the compiled sdl2 opengl3 example application, it runs fine, until I select a text input and try to hit CTRL and SHIFT. It always gives me this same error on both Windows and Mac.

`Assertion failed: (user_key_index >= 0 && user_key_index < ((int)(sizeof(g.IO.KeysDown)/sizeof(*g.IO.KeysDown)))), function IsKeyPressed, file ../../imgui.cpp, line 3489`

**Comment by kitebizelt** [comment]
This is on the line 3489:
```
bool ImGui::IsKeyPressed(int user_key_index, bool repeat)
{
    ImGuiContext& g = *GImGui;
    if (user_key_index < 0) return false;
    IM_ASSERT(user_key_index >= 0 && user_key_index < IM_ARRAYSIZE(g.IO.KeysDown));
    const float t = g.IO.KeysDownDuration[user_key_index];
    if (t == 0.0f)
        return true;
    if (repeat && t > g.IO.KeyRepeatDelay)
        return GetKeyPressedAmount(user_key_index, g.IO.KeyRepeatDelay, g.IO.KeyRepeatRate) > 0;
    return false;
}
```

**Comment by ocornut** [comment]
This is a bug that was introduced by #1541, give me a bit.

**Comment by ocornut** [comment]
@kitebizelt This should be fixed now, sorry for the issue that creeped in (I compile but don't test the SDL binding as often or thoroughly). I have also added an extra assert to catch those issues a little earlier next time.
