### ISSUE TITLE
Fix the Japanese glyph range; include Punctuations

### ISSUE THREAD

**Issue by usagi** [ocornut/imgui#156]
Hi, I'm a native Japanese. I was try the library today, then I like it :+1: 

However, ImGui does not have some of the common Japanese glyphs. Japanese require full range of `0x3000-0x303F` as _CJK Symbols and Punctuation_, but it's not supporting `ImFontAtlas::GetGlyphRangesJapanese()` now.

The current ImGui implementation:
https://github.com/ocornut/imgui/blob/d251204564a28ab090ef6423d48a4baaf7aa4d0d/imgui.cpp#L7614

The documentation of the _UNICODE CJK Symbols and Punctuation_ (Range 3000-303F):
http://www.unicode.org/charts/PDF/U3000.pdf

I'll write a patch and pull-request in near future, please wait a pull-request.

**Comment by usagi** [comment]
Thank you for your the merge :+1:

**Comment by ocornut** [comment]
Thanks for the fix. I have committed another one after that to put 0x3000-0x30FF in the same range, and also included them in the GetGlyphRangesChinese() function.
