### ISSUE TITLE
Assertion Failed: Invalid DisplaySize Value

### ISSUE THREAD

**Issue by Kewun0** [ocornut/imgui#1562]
https://i.imgur.com/qZa7YOS.png

I am trying to hook imgui to GTA: Vice City, but I am getting the error as in screenshot ^
My code 
`				ImGui::NewFrame();
				ImGui::Begin("test", 0, 0);
				ImGui::Text("test text");
				ImGui::End();`

How can I fix this?

**Comment by ocornut** [comment]
Sebastian,

The assert literally tells you what’s wrong. Please read the docs and examples and assert message.
