### ISSUE TITLE
cant change Color of BG for text

### ISSUE THREAD

**Issue by exsec** [ocornut/imgui#1566]
I can't change the color text BG. Tried using PushStyleColor( ImGuiCol_WindowBg,ImVec4(1,0,0,1));
but it doesn't work.

**Comment by ocornut** [comment]
Hello,

There's no concept or feature of background color for text. `ImGuiCol_WindowBg` is the window background.
Depending on your use case, you may draw a filled rectangle with the ImDrawList API before the text, which is simple if you have single line blocks of text.

Omar

**Comment by ocornut** [comment]
You can call `ImGui::CalcTextSize()` and then add style.FramePadding * 2 if it's a framed element.

**Comment by ewan-b** [comment]
Perfect thank you.
