### ISSUE TITLE
SetNextWindowBgAlpha

### ISSUE THREAD

**Issue by codecat** [ocornut/imgui#1567]
Can't find an issue for it yet, but this is mentioned in one of the old deprecated `Begin` calls:

https://github.com/ocornut/imgui/blob/db2ba13154e9c87b189f90e66bf2afd099d59045/imgui.cpp#L5015-L5018

I'd like to have the mentioned `SetNextWindowBgAlpha` for one reason, which is using `ImDrawList` "outside" of a window. Currently I'm drawing on an empty transparent window with all of these flags:

```c++
ImGuiWindowFlags_NoTitleBar |
ImGuiWindowFlags_NoResize |
ImGuiWindowFlags_NoMove |
ImGuiWindowFlags_NoScrollbar |
ImGuiWindowFlags_NoSavedSettings |
ImGuiWindowFlags_NoInputs
```

This method was suggested in some issue on github a looong time ago, so maybe there's a better solution for this now.

**Comment by ocornut** [comment]
Hello,

In theory you can use the piece of code mentioned in the comment.
In practice, I have to admit that when updating an old codebase with `#define IMGUI_DISABLE_OBSOLETE_FUNCTIONS` enabled, this was by far the most annoying change, so I think I am going to add this `SetNextWindowBgAlpha()` function right now.

One question is should the Alpha value by an absolute value (like it was in that old `Begin()` prototype) or a multiplier to the corresponding BgColor?

**Comment by codecat** [comment]
I think absolute makes the most sense, because then the programmer can decide whether to use the window background alpha or not. If you make it a multiplier you'd need to do some maths to get a true `1.0f` alpha.

**Comment by ocornut** [comment]
Added!

**Comment by ocornut** [comment]
> This method was suggested in some issue on github a looong time ago, so maybe there's a better solution for this now.

As for this, you may use GetOverlayDrawList() or you may create your own instances of ImDrawList also. But the current method works just as well.

**Comment by codecat** [comment]
Ah, `GetOverlayDrawList` works wonderfully, thank you!

**Comment by ocornut** [comment]
Pushed a fix (as pointed by @truedim here https://github.com/ocornut/imgui/commit/9a76fd30fd21d0c4f6403b27a235b883ece71f28#commitcomment-27071577)
