### ISSUE TITLE
Deprecated ImGui::Begin(...) and ImGui::SetNextWindowBgAlpha(...) handle alpha<0 differently

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#1568]
Basically, as far as I can understand, now ```ImGui::SetNextWindowBgAlpha(bg_alpha);``` is used when the deprecated version of ```ImGui::Begin(...,bg_alpha,...)``` gets called.

But now if we pass for example ```bg_alpha=-1.f``` we get a transparent window.
Previously the default alpha value of 0.7f (as far as I remember) was used.

In short I think this is breaking some old deprecated code, unless we handle negative values correctly in ```ImGui::SetNextWindowBgAlpha(bg_alpha);```.

**Comment by ocornut** [comment]
Hmm, I think you shouldn't need/want to call `SetNextWindowBgAlpha(-1.0f)`, perhaps we could assert for that?

**Comment by ocornut** [comment]
Oh I see the problem, sorry. It is a problem when called through the old `Begin()` signature. Fixing now!

**Comment by Flix01** [comment]
Thank you!

**Comment by ocornut** [comment]
Fixed, my bad.
