### ISSUE TITLE
CreateTexture failing with higher font sizes

### ISSUE THREAD

**Issue by ryzashi** [ocornut/imgui#1570]
Hello,

I'm creating around 5 fonts with like 3-4 different sizes each.
Now, when I try to multiply all font sizes by 2, CreateTexture fails returning "D3DERR_INVALIDCALL".

I'm using the DX9 implementation.

Is there any way to fix this?

**Comment by ocornut** [comment]
Are you adding many glyphs? With a regular ascii/latin set 20 fonts should be ok.
Check how big the texture become, perhaps DX9 or your driver has a size limit.
When add a font you can pass an `ImFontConfig` structure which allows you to configure oversampling. By default `OversampleH = 3` and `OversampleV = 1` which will make your font texture data 3 times larger than necessary, so you may reduce that to 1.
