### ISSUE TITLE
Opengl3-Opengl2 example resolution problem (Windows 7)

### ISSUE THREAD

**Issue by zyasar** [ocornut/imgui#1581]
Hi,
Opengl2-Opengl3 example have resolution problem on Windows 7 but not linux  like below 
 Linux screenshot
![capture](https://user-images.githubusercontent.com/35923515/35550729-d692e192-059c-11e8-95e9-62b88472bc8f.PNG)
Windows 7 screenshot
![capture2](https://user-images.githubusercontent.com/35923515/35550730-d6b2b8b4-059c-11e8-9ce7-f390e8257f17.PNG)
Why it works differently?How can I solve my problem?

**Comment by ocornut** [comment]
What is your screen resolution?
I would say it could be an issue either with Hi-DPI either with GPU driver enabling super-sampling or something like that. We should look into how we can adjust the OpenGL code to avoid it.

**Comment by zyasar** [comment]
thanks @ocornut   ,I have changed antialiasing off from NVidia settings .it works fine  :) :+1:
