### ISSUE TITLE
Wrong text in box and title

### ISSUE THREAD

**Issue by 0x452** [ocornut/imgui#1582]
Hello, guys!

I'm trying to paste code into text box and then i got it: 

![image](https://user-images.githubusercontent.com/17140731/35573188-68f8d16e-05e7-11e8-9128-fa00eafb85a7.png)

Here should be 'wtf' message

**Comment by ocornut** [comment]
Please provide actual imgui code we can use to repro your problem.
Also see https://stackoverflow.com/help/mcve

**Comment by 0x452** [comment]
sorry, here is code

```
const char	*szTitleDialog;
const char	*szTextDialog;

CDialogs::CDialogs(const char *title, const char *text)
{
	szTitleDialog = title;
	szTextDialog = text;
}
void CDialogs::Draw()
{
	if (szTitleDialog == nullptr) return;

	ImGui_ImplDX9_NewFrame();

	ImGui::Begin(szTitleDialog, NULL, ImGuiWindowFlags_NoResize);
	ImGui::Text(szTextDialog);
	ImGui::Button("OK"); ImGui::SameLine();
	ImGui::Button("EXIT");
	ImGui::End();

	ImGui::Render();
}
```

**Comment by ocornut** [comment]
That's not a properly repro, sorry. We have no idea how you are calling CDialogs and what's the lifetime of the pointed data. Your pointers are probably not pointing to valid string data at the time of the call. 

Please read about strings and strings literally in C/C++, , this is not the right place.
