### ISSUE TITLE
Disabled Sliders

### ISSUE THREAD

**Issue by zivsha** [ocornut/imgui#1583]
Is there a way to disable a slider, as you would a button (with `ImGuiButtonFlags_Disabled`)?
If not, how would you recommend working around this issue?

**Comment by ocornut** [comment]
Hello,

Seeing you are using the `imgui_internal.h` API (which `ImGuiButtonFlags_Disabled` is part of), you may be able to use:

```PushItemFlag(ImGuiItemFlags_Disabled)
//...
PopItemFlag();```

Please understand that this feature is unfinished, it will disable functionalities but will NOT affect the color/look of your slider. The API will be made public when that is finshed.

Also see #211

**Comment by zivsha** [comment]
Thanks
