### ISSUE TITLE
I cant get it to work to have multiple fonts

### ISSUE THREAD

**Issue by HenkieHanker2** [ocornut/imgui#1585]
hey m8,

i know its probz a really stupid question but i cant get it to work. and yes i have googled a lot for this. i just dont understand the other posts. 

i need the 3 fonts and i dont know how to do that, i can get it to work with 1 font but not with 2.

wich line of code do i need and where to place?

this is the code :

`   long __stdcall hkEndScene(IDirect3DDevice9* device)
    {
		//if (GetAsyncKeyState(VK_INSERT)) Vars.Menu.Opened = !Vars.Menu.Opened;

		ImGuiIO& io = ImGui::GetIO();

		//ImFont* fDefault1;
		//ImFont* fTabs1;
		//ImFont* fSubTabs1;

		ImFont* fDefault1 = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Exo2-Regular.ttf", 20.0f);

		
		ImFont* fTabs1 = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\legacyfont.ttf", 45.0f);

		ImFont* fSubTabs1 = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\AstriumWep.ttf", 20.0f);

        auto oEndScene = direct3d_hook.get_original<EndScene>(index::EndScene);

        static auto viewmodel_fov       = g_CVar->FindVar("viewmodel_fov");
        static auto mat_ambient_light_r = g_CVar->FindVar("mat_ambient_light_r");
        static auto mat_ambient_light_g = g_CVar->FindVar("mat_ambient_light_g");
        static auto mat_ambient_light_b = g_CVar->FindVar("mat_ambient_light_b");
        static auto crosshair_cvar      = g_CVar->FindVar("crosshair");

        viewmodel_fov->m_fnChangeCallbacks.m_Size = 0;
        viewmodel_fov->SetValue(g_Options.viewmodel_fov);
        mat_ambient_light_r->SetValue(g_Options.mat_ambient_light_r);
        mat_ambient_light_g->SetValue(g_Options.mat_ambient_light_g);
        mat_ambient_light_b->SetValue(g_Options.mat_ambient_light_b);
        crosshair_cvar->SetValue(!g_Options.esp_crosshair);

		Variables Vars = Variables();

		static ConVar* convar;
		//VMTD3D.ReHook();

		if (!g_Options.MenuInit)
		{
			Gui_Init(device);
			convar = g_CVar->FindVar("cl_mouseenable");
		}
		ImGui::GetIO().MouseDrawCursor = g_Options.Opened;

		ImGui_ImplDX9_NewFrame();
		auto& style = ImGui::GetStyle();
		int W, H;
		g_EngineClient->GetScreenSize(W, H);

		DefineTab();

		if (g_Options.Opened)
		{
			if (style.Alpha > 1.f)
				style.Alpha = 1.f;
			else if (style.Alpha != 1.f)
				style.Alpha += 0.01f;

			style.WindowMinSize = ImVec2(0, 0);
			//ImGui::PushFont(fDefault1);
			int w;
			int h;
			style.Colors[ImGuiCol_Border] = ImVec4(0.27f, 0.27f, .27f, 1.00f);

			g_EngineClient->GetScreenSize(w, h);

			style.Colors[ImGuiCol_WindowBg] = ImVec4(0.13f, 0.13f, 0.13f, 1.f);
			ImGui::SetNextWindowSize(ImVec2(650, 400));
			ImGui::Begin("##tabarea", &g_Options.Opened, ImVec2(650, 400), 1.f, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoFocusOnAppearing | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoBringToFrontOnFocus);
			{
				style.WindowPadding = ImVec2(0, 0);
				style.ItemSpacing = ImVec2(0, 0);
				//ImGui::PushFont(fText1); DEZE CRASHED
				if (g_Options.MenuTab == 0) BtnActive(); else BtnNormal();
				if (ImGui::Button("a", ImVec2(162.5, 75))) g_Options.MenuTab = 0;
				ImGui::SameLine();
				if (g_Options.MenuTab == 1) BtnActive(); else BtnNormal();
				if (ImGui::Button("b", ImVec2(162.5, 75))) g_Options.MenuTab = 1;
				ImGui::SameLine();
				if (g_Options.MenuTab == 2) BtnActive(); else BtnNormal();
				if (ImGui::Button("c", ImVec2(162.5, 75))) g_Options.MenuTab = 2;
				ImGui::SameLine();
				if (g_Options.MenuTab == 3) BtnActive(); else BtnNormal();
				if (ImGui::Button("d", ImVec2(162.5, 75))) g_Options.MenuTab = 3;

				style.Colors[ImGuiCol_ChildWindowBg] = ImVec4(0.0, 0.96, 0.97, 1.f);
				ImGui::BeginChild("BlueBalls", ImVec2(650, 6), false, 0);
				ImGui::EndChild();

				style.Colors[ImGuiCol_ChildWindowBg] = ImVec4(0.13f, 0.13f, 0.13f, 1.f);
				style.ItemSpacing = ImVec2(30, 0);
				//ImGui::PushFont(fDefault1);
				ImGui::PushFont(fTabs1); //isloaded crash HERE				
				if (g_Options.MenuTab == 0)
				{
					DrawLegitTab();
				}
				else if (g_Options.MenuTab == 1)
				{
					DrawRageTab();
				}
				else if (g_Options.MenuTab == 2)
				{
					DrawVisualsTab();
				}
				else if (g_Options.MenuTab == 3)
				{
					DrawMiscTab();
				}
				else if (g_Options.MenuTab == 4)
				{
					DrawColorsTab();
				}
				ImGui::PopFont();
			}
			ImGui::End();
			//background

		}
		else
		{
			if (style.Alpha < 0.f)
				style.Alpha = 0.f;
			else if (style.Alpha != 0.f)
				style.Alpha -= 0.01f;
		}
		ImGui::Render();
		
		if (InputSys::Get().IsKeyDown(VK_TAB))
			Utils::RankRevealAll();

			
		return oEndScene(device);

    }`

 
where it says isload crash HERE it will crash. heres a screenshot : 
![e447a8fbf5ebdb2930429fee4fed69a2](https://user-images.githubusercontent.com/35076607/35640200-ce3cca5a-06bc-11e8-9811-97530dfe3a7c.png)

wich line of code do i need and where to place?

Thanks. (btw ur project is awsome dude. is there an donation link?)

**Comment by ocornut** [comment]
The comment _EXACTLY_ on the line of your assert says:
`"Font Atlas not built. Did you call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8() ?"`
Which you didn't read. Your fonts are not built, you probably loaded fonts after building the font atlas, or never built the font atlas.

I actually modified this exact assertion in recent version (PS: you didn't specify the version you are using) to display that text string within the assert message because of the number of people submitting similar issues.

> Thanks. (btw ur project is awsome dude. is there an donation link?)

The _FIRST_ paragraph of the README, which you didn't read, is a donation link.
It shows how not serious you are about this, which is unacceptable. 

If I may suggest, if you intend to make everyone's life miserable with those cheats at least make your life better by trying to learn programming (e.g. by reading programming books), this will come in handy. The cheaters coming here for advices have been the most entitled lazy fuckers to ever grace this issue tracker.

Please refer to https://stackoverflow.com/help/mcve for any further post here.

You are now blocked, but as soon as I receive your donation I'll unblock you and forward it to charity :)

**Comment by ocornut** [comment]
Sorry for being rude but I had a LOT of your peers coming here and I need to stop them coming.
