### ISSUE TITLE
Community stance: the situation with "pasters" and cheaters

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#1586]
Those subscribed to this project have probably noticed the influx of support requests from users who are using dear imgui to create cheating overlays for multi-player games like CS GO, etc. (I need to clarify that their activities are more than often unethical and making a lots of people unhappy).

While I initially wanted to avoid judging people based on what they do with imgui, it became problematic as their requests are more than often extremely vague, badly formulated, and often coming mostly from their misunderstanding of C++. Many of them are starting their work/hobby based on guides that instruct them to copy and paste lines of code they don't understand, and make little effort to learn programming. To make things more difficult, I suspect that with their scheme of injecting DLL into running processes, many of them don't know how to use a debugger at all.

Dealing with them is a little time consuming but mostly it is a little depressing. I often tried to genuinely help them based on the reasoning that they are the reflection of problems a new programmer would have with imgui, but effectively it looks like they aren't in for the programming. They also tend to delete their messages (so as not to leave traces/help because their field is competitive) or leave without barely a thank you. Over time my answers have been increasingly hostile toward them. 

To make this easy on me, I will from now on immediately block them and close their issues as soon as I suspect they come from a script-kiddie-cheating-in-multiplayer-games background (they are remarkably easy to spot). I have already blocked a good dozen over the past few months, but from now on the blocking with come without a glimpse of help. Note that many other forms of creative or elaborate cheats/hacking/reverse engineering tools are perfectly fine. 

It worries me that my past hostility towards those few users would deter some less experienced programmers from asking questions for fear of my answers. Anyone else: your question, feature requests and feedback are always welcome, there are no stupid questions. This software is becoming better because of all your requests.

(Just please try to provide [repro code](https://stackoverflow.com/help/mcve) in the form of something I can paste in a barebone imgui example :)

*EDIT* Edited a few things for clarity.

**Comment by ocornut** [comment]
Trivia: There are dozens of gated communities with hundreds of cheaters/pasters discussing and exchanging code. So I know there are lot more of those people out there who may be tempted to ask questions here. Feeding one of them is not giving the right signal, I should have realized that earlier.

Amusingly, there is a stigma against using dear imgui in their groups, because it is too easy to use! So a sizeable amount of people are trying to make their menu look "not-imgui" to claim they've created their own. Because of that they have a tendency to harshly modify their copy of the imgui codebase, with the added side-effect that when they ask questions you don't know which version of the code they are using.

**Comment by Roguezilla** [comment]
I can see your point here. But, like, close only the issues that you can tell come from those who paste, can't understand a single line of C++ and don't even know how to debug.

**Comment by ocornut** [comment]
I’ll have to reserve myself the right to block people based on what I think is reasonable. The idea is that we shouldn’t discriminate based solely on skills. We want to be welcoming new programmers. So it has to be juged on a case by case basis, taking account of the nature, intent, thoughtfulness, politeness of the request, history of the person, etc. Note that I’ve been accodomating and patient for a long time, and I’ll continue to do so for people who are not crossing the line. That line is hard to clearly define but it’s easy to tell which side someone is on when you see their message. The vast majority of people who are reading this thread will not by affected by any of this and if you think your project nature is near the line then just double down on making sure you ace the other criterias.

**Comment by KittoniuM** [comment]
This is right, there are many pasters who use this GUI in their shitty hacks. I made a post about it here:

https://bigpackets.com/forum/discussion/imgui-sucks-and-for-beginners-only/

**Comment by KittoniuM** [comment]
i dont know any solution other than taking everyone who uses imgui in their hacks to jail and finishing them..

**Comment by ocornut** [comment]
I’ll lock this conversation now so it doesn’t derail toward this sort of low quality posts. Back to normal operations.

**Comment by irufus** [comment]
@ocornut Was it the link to bigpackets[.com]? I still see it

**Comment by ocornut** [comment]
(@irufus I am also confused, the posts were not visible last time when I edited the later message, maybe github toyed with how they display/hide messages of blocked users? Anyway I can see it again now..)

**Comment by WeskerPower** [comment]
interesting, people asking stuff on this github, i highly doubt they are hackers, sin they usually use QT hacks to make cheats, sure some might use imgui, im a new imgui user searching answers, like changing button states, and im fairly new to c++, trying to create my own sfml and imgui game, but i came down this rabbit whole and i think that, not answering newbie questions because a hacker might use it, well thats like saying im not going to release my code to the public because some assassin might use it, but then again your free to do w/e, i just think that i could find my solution earlier if the gates where open, and i know variables are in the headers but im dumb and tired of trying stuff that clearly doesnt work

**Comment by ocornut** [comment]
> ot answering newbie questions because a hacker might use it, well thats like saying im not going to release my code to the public because some assassin might use it

It's completely different. I can't stop cheaters using Dear ImGui, but I don't want to be spending MY TIME helping those people, or anyone being a [Help Vampire](http://slash7.com/2006/12/22/vampires/). I already spend 10+ hours a week helping people here. You can use Discord discord.dearimgui.org if you want to talk to people. This is not up for debate.

**Comment by thatfox** [comment]
> Those subscribed to this project have probably noticed the influx of support requests from users who are using dear imgui to create cheating overlays for multi-player games like CS GO, etc. (I need to clarify that their activities are more than often unethical and making a lots of people unhappy).
> 
> While I initially wanted to avoid judging people based on what they do with imgui, it became problematic as their requests are more than often extremely vague, badly formulated, sometimes rude, and often coming mostly from their misunderstanding of C++. Many of them are starting their work/hobby based on guides that instruct them to copy and paste lines of code they don't understand, and make little effort to learn programming. To make things more difficult, I suspect that with their scheme of injecting DLL into running processes, many of them don't know how to use a debugger at all.
> 
> Dealing with them is a little time consuming but mostly it is a little depressing. I often tried to genuinely help them based on the reasoning that they are the reflection of problems a new programmer would have with imgui, but effectively it looks like they aren't in for the programming. Along with being often lazy or rude, they also tend to delete their messages (so as not to leave traces/help because their field is competitive) or leave without barely a thank you. Over time my answers have been increasingly hostile toward them.
> 
> To make this easy on me, I will from now on immediately block them and close their issues as soon as I suspect they come from a script-kiddie-cheating-in-multiplayer-games background (they are remarkably easy to spot). I have already blocked a good dozen over the past few months, but from now on the blocking with come without a glimpse of help. Note that many other forms of creative or elaborate cheats/hacking/reverse engineering tools are perfectly fine.
> 
> It worries me that my past hostility towards those few users would deter some less experienced programmers from asking questions for fear of my answers. Anyone else: your question, feature requests and feedback are always welcome, there are no stupid questions. This software is becoming better because of all your requests.
> 
> (Just please try to provide [repro code](https://stackoverflow.com/help/mcve) in the form of something I can paste in a barebone imgui example :)
> 
> _EDIT_ Edited a few things for clarity.

Yeah, it's like.. if you're going to make a menu for the said "x" game, literally just use the native drawing functions provided by the engine, or just use Direct-X. 

Everyone I know who uses IMGUI as a menu collectively usually gets made fun of for their incompetence, ultimately giving the IMGUI project a bad reputation; among the unwilling.

**Comment by crispyi2** [comment]
When I see people use ImGui for making cheat software first off i think why did you choose C/C++, and then I think it's prob because they are a braindead idiot who is so trash at video games they decide to not even buy a cheat engine but MAKE THEIR OWN. People who cheat make no sense

**Comment by FuryFearless** [comment]
I saw this topic after a long time, but I want to talk to you about something.
Now close your eyes and think of a game and to win this game you have to deposit money which means p2w.
Do you think it would be a stupid idea to cheat on that game in this part?

**Comment by noor0x07** [comment]
ratio bozo

**Comment by Gorzy-dev** [comment]
Lmao idk what you expected the cheating community is full of retards.

**Comment by commonbreed** [comment]
I think it's important to differentiate "low-quality questions" from "questions that are clearly from some script-kiddie-hacker." The former unfortunately exist in any software community and I believe closing their questions by linking them to an issue accusing them of developing some nefarious game overlay is unfair.

**Comment by ocornut** [comment]
The rules/guidelines are already stating this:
“If you are involved in cheating schemes (e.g. DLL injection) for competitive online multiplayer games, please don't post here. We won't answer and you will be blocked. It doesn't matter if your question relates to said project. We've had too many of you and need to project our time and sanity.”

Opening a new issue requiring deleting a link to guidelines. I only close with this issue # linked when I have evidence of a connection with online multiplayer cheating.

You are right that I should include the link to guidelines more frequently when closing.

People don’t fully comprehend that this is a matter of project survival. If I had to parse and read dozens of lazier incomplete messages every days I would quickly prefer to stop working on this. It’s unfortunate but this place cannot simultaneously be a playground to teach programming to kids and a fruitful project in active development.

**Comment by ocornut** [comment]
@commonbreed FYI following your comment the other day I have upgraded the issue template to the new system supported by github, it now includes inline links and better/clearer commentary about requirements. https://github.com/ocornut/imgui/pull/5927#issuecomment-1877327799

**Comment by trxy9** [comment]
99% of people who use imgui for developing cheats come to other places like certain discord servers revolving around imgui (sometimes they sell custom imgui menus for cheats) to get help. Wont really change much and you should have expected it to happen...

**Comment by ocornut** [comment]
Well that’s exactly the intended goal. Let that crowd manage themselves without drowning us in stupid questions.

**Comment by trxy9** [comment]
> Well that’s exactly the intended goal. Let that crowd manage themselves without drowning us in stupid questions.

I know this only adds to your point, but i've seen a lot of people use external imgui bases to fake cheats and scam people, and it's ridiculous the amount of people who believe it. 

I'm 14 and know basic imgui, and while only being able to style and add widgets and tabs to an external base, still being able to do similar stuff as the people i've mentioned before*, but just goes to show how easy it is to manipulate the use of imgui for their profit and be stupid people.

* I actually talked to the owner of a specific 'cheat' for a game and he told me he made over €1k i think it was by pasting someone's imgui base while having no idea what he was doing. 

Of course, I've seen imgui been used for good, but as one of the only tools you can use to create an overlay to directx9/10/11 processes, you should sort of expect it to be used in this case. I dont think 'stereotyping' people because they ask simple questions regarding help means they're using imgui for purposes it isn't intended to be used for. Despite me being involved in cheating communities for quite a while now, I couldn't name you a single software that doesn't use imgui or zgui (very similar i believe) for the menu.

**Comment by dretax** [comment]
@ocornut I humbly thank you for creating imgui, but calling out all cheaters as minor script kiddies is a meme on It's own.
There are some professional guys out there doing "script kiddie" work with actual reverse engineering of kernel, and utilizing cool stuffs you probably can't really imagine on vulnerability side. I do the same thing, but also on the anti-cheat spectrum.
We call the mentioned group "pasters", coming from the unknowncheats side. It's what we deal with on a daily basis, not just imgui, they find our published blogposts, or sources, and they attempt to make profit of their "research".

**Comment by pilot2254** [comment]
@ocornut thanks for maintaining Dear ImGui and for being upfront about the issue you described in this issue.

I want to be respectful and transparent: I develop small-cheat projects for singleplayer and private, cooperative testing with friends only, and I use those projects mainly to learn C++ and reverse engineering concepts. I will never use or distribute tools intended to give an unfair advantage in competitive multiplayer.

All of my work is open source and clearly documented as "educational / singleplayer only". I can also add any labeling, license text, or a README note you prefer to make my intentions clear. Before I go further I wanted to ask whether you are comfortable with me using Dear ImGui in such projects, or whether you prefer people not mention this use case at all. If this is unwelcome, I will not open issues or request support for those projects and I will follow whatever channel you prefer to discuss it. Thanks for your work on ImGui.

**Comment by ocornut** [comment]
@pilot2254 thanks for your message.
For avoidance of doubt: the primary issue is not about me being comfortable or not with people using dear imgui in certain projects. It is about me not providing support, and therefore my time and energy, to a certain category of users.

The fact that you are write such a comprehensive message already puts you very largely above the lots of the average multiplayer cheat maker poster. And there’s no issue at all in the first place, your use case really doesn’t fall within the use cases I described and it is therefore perfectly fine that you ask questions.

**Comment by pilot2254** [comment]
thanks for your answer!
