### ISSUE TITLE
PushStyleColor/PopStyleColor crashed

### ISSUE THREAD

**Issue by zyasar** [ocornut/imgui#1587]
I have to use many PushStyleColor/PopStyleColor because of my UI design .I think imgui is confused about sorting of stack so it crashed :(
(I have controlled all PushStyleColor/PopStyleColor begin/end both in ImGui::Begin/BeginChild or  out ImGui::Begin/BeginChild)
How can I solve this?

**Comment by ocornut** [comment]
Hello @zyasar,

> so it crashed :(

If you state that a library crashed, please use the debugger and provide a callstack so as to provide some basic data about what's going on.

Note that imgui asserts (which is a dialog box that looks like a crash, though in this case depending on your assert implementation you may be able to skip it) on mismatching Push/Pop pairs. It compares the stack size on Begin and End and asserts when they differs, so as to give you a hint as to where you had mismatch Push/Pop. This is most likely the nature of your problem, you have mismatching number of Push and Pop in your code flow. 

Providing a Minimal, Complete, and Verifiable example (https://stackoverflow.com/help/mcve) would help reporting the problem, and most often the process of creating this MCVE you have you solve the problem.

**Comment by ocornut** [comment]
@zyasar Any news about this?

**Comment by ocornut** [comment]
Closing as answered or probable user's issue. Let us know if you haven't solved it on your end.
