### ISSUE TITLE
Cannot load file

### ISSUE THREAD

**Issue by Tim4135** [ocornut/imgui#1593]
Hi,

So i have been playing around with imgui yesterday and all went okay.
Now today I boot up my pc, launch visual studio, click on the "Local  Windows Debugger"button as always to launch my program.
Program launches and then says this in the console window of my app:
`Assertion failed: 0, file c:\users\tim\source\repos\openglgameengine3\libraries\ext\imgui\imgui_draw.cpp, line 1526`
And my program pops up and says:
![afbeelding](https://user-images.githubusercontent.com/22937934/35778479-f57e118c-09be-11e8-9f96-84aaf450622b.png)
If I press abort, it aborts.
If I press ignore, the app closes.
If I press Retry, VS2017 pops up pointing to line 1526 in imgui_draw.cpp and points at:
`IM_ASSERT(0); // Could not load file.`

But if I open my app by going to the debug folder of my app and manually opening it, it is all fine?!
Does someone know what is happening here and if it is normal?(Especially since i didn't have it yesterday?)
I modified one thing in the code, I modified this:
`if (ImGui::Button("Close Me"))
				show_another_window = false;`
to this:
`if (ImGui::Button("Don't Close Me!"))
				show_another_window = false;`

SO what is causing it?

Thanks

**Comment by ocornut** [comment]
Tim, you aren't providing the most important information: what are you trying to load, how are you loading it, etc. ? Check your debugger callstack you know what is the calling function.

> But if I open my app by going to the debug folder of my app and manually opening it, it is all fine?!

Visual Studio/debugger has options to setup the starting directory, which may not be the same directory at the .exe file. Whereas when you run an .exe by double-clicking on Explorer the starting directory will be the same as the .exe directory.

![image](https://user-images.githubusercontent.com/8225057/35778594-6fee3eb4-09c0-11e8-9179-3ac6753eecae.png)

Note that in the case you copied the entire imgui repo and are loading the fonts I put in `extra_fonts/`, I have moved this folder to `misc/fonts/` very recently.

**Comment by Tim4135** [comment]
The only thing i thing can be wrong is this:
`ImFont* font = io.Fonts->AddFontFromFileTTF("fonts\\ArialUni.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesJapanese());`
in the debug folder, i have a folder named fonts with that font in it.
But the working directory may be the problem, will check that out now.

Thanks!

**Comment by Tim4135** [comment]
Thanks!, the wroking directory was the problem.
The strange thing is, what changed it?
It was okay yesterday.


But thanks, this can be closed
