### ISSUE TITLE
Show special tooltip for widgets (buttons)

### ISSUE THREAD

**Issue by halcyonx** [ocornut/imgui#1595]
Hello! I use dear ImGui and its amazing lib!

I made editor interface with number of buttons, these buttons draws via ImGui::ImageButton.
I need to show additional little tooltips for each of these buttons while Alt pressed (to show shortcut combination).
There is some way to do this? Thans in advance.

**Comment by ocornut** [comment]
@halcyonx This is well documented in the demo code. Please run `ShowDemoWindow()` and refer to its code. Did you even look for the word "tooltip" in imgui.h ?

**Comment by mika314** [comment]
For people who use Google and don't like to read documentation, or just for future me:
```C++
      ImGui::Button("List##List");
      if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled))
      {
        ImGui::SetTooltip("Select at least one difficulty");
      }
```

**Comment by Laamy** [comment]
life saver

> For people who use Google and don't like to read documentation, or just for future me:
> 
> ```c++
>       ImGui::Button("List##List");
>       if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled))
>       {
>         ImGui::SetTooltip("Select at least one difficulty");
>       }
> ```

life saver
