### ISSUE TITLE
Share drag information between contexts?

### ISSUE THREAD

**Issue by volcoma** [ocornut/imgui#1598]
Hi, I've been playing with the drag an drop stuff and I am pretty happy with the design you came out with. Good job! I am just trying to figure out how to share the drag and drop state between contexts. For example I have 2 windows (platform ones) with a separate context each to handle rendering and stuff. I am trying to achieve drag and drop between the two windows. Do you have any idea how to achieve this in the current state? I see a lot of members regarding drag and drop in the context struct. Is this issue tackled in the experimental docking (virtual viewports) stuff that you are working on? Thanks a lot.

**Comment by ocornut** [comment]
Hello, 

I don't have the workaround / answer to your exact problem, it's possible to route the payload manually but probably a bit tedious work.

However this won't be necessary as the target is that a single imgui will be able to handle multiple windows. So yes, that is part of the virtual viewport feature. (#1542) I expect virtual viewport to be become available before docking/tabs, but have no ETA for it at the moment.

**Comment by volcoma** [comment]
Thanks for the info!

**Comment by ocornut** [comment]
I'll close that as I don't expect a fix before virtual viewport makes it to the repo.
You may solve it yourself with the multiple context (the solution will be in the back-end side) but probably not worth it unless you absolutely need that sharing soon.
