### ISSUE TITLE
Accents on items (ComboBox)

### ISSUE THREAD

**Issue by exphck** [ocornut/imgui#1601]
How do I write letters with accents?

In the following image shows the problem with the accent, appears ? instead of the letter + accent:
![accents](https://user-images.githubusercontent.com/33573509/35945939-1846743e-0c49-11e8-9212-2823cfe08222.png)

It should look like this:
Utilit?os -> Utilitários
Avia? -> Avião
?ngulos -> Ángulos
?ago -> Âmago

**Comment by ocornut** [comment]
Please read the FAQ about fonts and world wide display. You need to use utf-8 string, either encode your source file as utf-8 or use the syntax `u8”my string”` with C++11.

**Comment by exphck** [comment]
Thanks occornut worked perfectly.
