### ISSUE TITLE
PushID and Begin

### ISSUE THREAD

**Issue by L-P** [ocornut/imgui#1602]
Hi,

I'm currently working on an interface where multiple windows can be opened with
the same title.  
I hoped `Begin()` would take `PushID` into account and create a separate
window, instead I got garbage.

I expected it since the documentation mentions `PushID` and widgets but not
windows, but it seems to me that the `IDStack` could be used for windows
without adding much complexity (though I'm not familiar with ImGui internals).

From a design standpoint, it would be the difference between having my window
manager manage the windows (`∀ window {PushID, {Begin, End}, PopID}`) and
having to push down UI-specific data to a component that should not care about
what's managing it or if windows with similar titles exists which it can't
possibly know.  

As a crude mitigation I can always append the pointer of the component to the
window title but it does not feel right.

So the actual question : should/could `Begin` make use of the `IDStack` of the
previous context? This would imply having an `IDStack` for the global context.

**Comment by ratchetfreak** [comment]
you can still used the "title##foobar" notation to get windows with the same title but different IDs

**Comment by ocornut** [comment]
Hello,

There is an example in the Demo that solves exactly this problem. Normally you’d use the ## operator in string to append to the ID but you may also want to use ### to overwrite the ID completely. Please check the demo and read the FAQ about the IDs.

Begin() is a function can be called multiple times (to create a new window while in the context or another, or append to an existing window) and thus applying the ID Stack to its identifier wouldn’t work.

Omar

**Comment by L-P** [comment]
I forgot windows had their own independent context and could be started from other windows (I tend to avoid that). My suggestion requires more convoluted changes than anticipated.

Fine by me, `##` it is.

**Comment by ocornut** [comment]
If you want stable ids with changing titles you’ll want to use ### too.
