### ISSUE TITLE
Drag and drop: preview on target without hovering

### ISSUE THREAD

**Issue by volcoma** [ocornut/imgui#1603]
It would be great if a new flag can be added to ImGuiDragDropFlags_  flags so that previews can be seen even if not hovering over them. This would help the user to see where he can drop a dragged item. Being a flag the user can use that functionality wherever he sees fit.

Another cool feature could be to add internal support for drag/drop between input fields as you did with the color. But the first one is more important at least for me :)

**Comment by ocornut** [comment]
Hello, 

Answering for completeness, even consider how old the question is.
I briefly looked at this again today and realizing there isn't much worth doing on the library side.
Depending on desired rules you may simply do something like that.
```cpp
SomeItem();
if (const ImGuiPayload* payload = ImGui::GetDragDropPayload())`
   if (payload.IsDataType(MY_DATA_TYPE))
      GetWindowDrawList()->AddRect(GetItemRectMin(), GetItemRectMax(), ...);
```

The only "opaque" standard is the **style** of the preview rectangle which is drawn in `AcceptDragDropPayload()` function:
```cpp
if (!(flags & ImGuiDragDropFlags_AcceptNoDrawDefaultRect) && payload.Preview)
    window->DrawList->AddRect(r.Min - ImVec2(3.5f,3.5f), r.Max + ImVec2(3.5f, 3.5f), GetColorU32(ImGuiCol_DragDropTarget), 0.0f, 0, 2.0f);
```

So I've decided to move that in a new oneliner `RenderDragDropTargetRect()`, function in imgui_internal.h so at least you can refer to it, the code becomes:

```cpp
SomeItem();
if (const ImGuiPayload* payload = ImGui::GetDragDropPayload())`
   if (ImGui::IsItemVisible() && payload.IsDataType(MY_DATA_TYPE))
      ImGui::RenderDragDropTargetRect(g.LastItemData.Rect);
```
