### ISSUE TITLE
PushStyleVar and PopStyleVar

### ISSUE THREAD

**Issue by El3ctr1cR** [ocornut/imgui#1609]
So I tried to Push a style and pop the style, but when I try to pop it it will not pop it officially, because the style will be everywhere (in other windows, etc)

Code:
`			```
ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0f, 0.0f));
			ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
			ImGui::PushStyleVar(ImGuiStyleVar_IndentSpacing, ImVec2(0.0f, 0.0f));
			ImGui::Text("");
			if (ImGui::Button("Tab1", ImVec2(172, 50))) Global::MenuTab = 0;
			ImGui::SameLine();
			if (ImGui::Button("Tab2", ImVec2(172, 50))) Global::MenuTab = 1;
			ImGui::SameLine();
			if (ImGui::Button("Tab3", ImVec2(172, 50))) Global::MenuTab = 2;
			ImGui::SameLine();
			if (ImGui::Button("Tab4", ImVec2(172, 50))) Global::MenuTab = 3;
			ImGui::SameLine();
			if (ImGui::Button("Tab5", ImVec2(172, 50))) Global::MenuTab = 4;
                        ImGui::PopStyleVar();
			ImGui::End();
```

**Comment by ocornut** [comment]
Sorry but #1586
