### ISSUE TITLE
Crashing when Window is slightly off screen

### ISSUE THREAD

**Issue by TylerEspo** [ocornut/imgui#1610]
I am receiving the follow exception if I move the current window off ~ half way

https://gyazo.com/aec3584e46c0459331789e3a27e84f9b

Exception thrown: read access violation.
window->DC.GroupStack.Data was 0x11100EA.

**Comment by ocornut** [comment]
Could you provide repro code and a screenshot of your window?

What I can guess is that you aren’t honoring Begin/End BeginChild/EndChild pairs properly. For those two functions the Endxxx call needs to always be called regardless of if the Beginxxx returned false. False is an indicator that the window contents will be clipped and can be skipped entirely, it typically happen when a window is collapsed or when a child window is fully clipped.

**Comment by TylerEspo** [comment]
Issue fixed. Accidentally hooked on D3D Scene end instead of Present. Thank you!
