### ISSUE TITLE
io.RenderDrawListsFn Crashing 1.60

### ISSUE THREAD

**Issue by davidElusion** [ocornut/imgui#1616]
Hello Omar Or anyone i was on ImGui 1.52 and i followed the Update of ImGui. 

When it comes to Injecting ImGui Into GTA V. I seem to crash and when i debug it i goes to this 

>     io.RenderDrawListsFn = ImGui_ImplDX11_RenderDrawLists;  // Alternatively you can set this to NULL and call ImGui::GetDrawData() after ImGui::Render() to get the same ImDrawData pointer.
> 

Would there be any possible fix lol. For this to stop the crashing upon loading into the game ?. It only happend when i updated from 1.52 > 1.60 ImGui Thank You  

![image](https://user-images.githubusercontent.com/36486093/36222512-6b605084-11b9-11e8-9267-07a399b36667.png)

**Comment by ocornut** [comment]
Please read the docs ("api breaking changes") and #1599.

**Comment by davidElusion** [comment]
Yes i looked into it and read all of it. But im still confused on why it is crashing upon startup

**Comment by ocornut** [comment]
Have you called CreateContext()?
Do you have asserts enabled in your build?

**Comment by davidElusion** [comment]
Where do i call CreateContext(); What part and no how to enable ?

**Comment by ocornut** [comment]
> Where do i call CreateContext(); 

The examples are showing it and the link I posted has the answer for that literally on the first bold line.

> And what are asserts and how to enable ?

https://www.google.com/search?q=what+are+asserts+c%2B%2B
https://www.google.com/search?q=how+to+enable+asserts+c%2B%2B

**Comment by davidElusion** [comment]
Aha Thank you i don't have asserts in my build and where do you put

ImGui::CreateContext() Before ImGUI Where would that be 

I have script.cpp where i call my functions 
and menu.cpp where it draws ImGui Where would i put it at the top of Render ?

**Comment by davidElusion** [comment]
I Add it to Menu::Render

![image](https://user-images.githubusercontent.com/36486093/36290141-c37424d2-12bb-11e8-98ba-dd2015eef9a0.png)

CRASH ALLWAYS HERE :( WHAT :( :(
