### ISSUE TITLE
ImFont::DisplayOffset and Ascent/Descent issues

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#1619]
**Does anyone here uses the ImFont::DisplayOffset field?**

It's been arbitrarily set to default to ImVec2(0, 1) since July 2015.
This has been done mostly because it looks righter with ProggyClean, and on some fonts with the way we rounded Ascent/Descent it made fonts more centered, but it was incorrect in other cases.

I have created a `font_offset` branch that does 2 things:
https://github.com/ocornut/imgui/compare/font_offset?expand=1

1/ set DisplayOffset.y to 0 by default in ImFont. AddFontDefault() changes it to 1 for ProggyClean.
2/ in the font builder, I am rounding Ascent and Descent values to they match what freetype does (it always rounds them).

DisplayOffset 0, without rounded Ascent/Descent:
You can see that the STB render looks too high, and this is where the previous DisplayOffset=1 value helped.
![stb_ascent_1_before](https://user-images.githubusercontent.com/8225057/36252534-38773dcc-1245-11e8-9683-4c9b0fd95ebb.gif)

DisplayOffset 0, with rounded Ascent/Descent:
![stb_ascent_2_after](https://user-images.githubusercontent.com/8225057/36252535-38917778-1245-11e8-93e9-8dc787b0b1fb.gif)

**How this going to affect people:**

 -People who only used default font: won't be affected.
- People who didn't touch DisplayOffset.y : hopefully fonts are better centered now. Any regression?
- People who override DisplayOffset.y = 0 won't be affected.
- People who did DisplayOffset.y -= 1 will now have their font one pixel too high. Those are people who were caring about their use of fonts, so they will notice and fix easily?

(I think one tangential issue we have with this is that FramePadding.y is symmetrical, we don't have a way to specify a different padding value for bottom and top. Ideally would be useful. Practically would probably break things and add confusion?)

**Comment by goncalo** [comment]
I have been using ImFontConfig.GlyphOffset.y = -1 in custom fonts which I guess was compensating DisplayOffset.y = 1 to 0 (never noticed DisplayOffset wasn't zero).

As other fonts can be merged into the default ImFont, wouldn't it be better to use GlyphOffset.y = 1 in ProggyClean instead of DisplayOffset to offset just ProggyClean glyphs?

**Comment by ocornut** [comment]
@goncalo: which font file and size/settings were you using? default stb rasterizer?  So i can double check the effect of my ascent/descent rounding.

> As other fonts can be merged into the default ImFont, wouldn't it be better to use GlyphOffset.y = 1 in ProggyClean instead of DisplayOffset to offset just ProggyClean glyphs?

That’s exactly what this patch is doing.

**Comment by stfx** [comment]
I also only used `ImFontConfig.GlyphOffset.y` to fix vertical font alignment when merging multiple fonts so this seems like a good change from my point of view.

**Comment by ocornut** [comment]
This is now merged. If you were adding or subtracting to `ImFont::DisplayOffset.y` you may be affected. Hopefully it'll be easier to spot if that's the case.
