### ISSUE TITLE
Javascript binding + WebGL demo

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#1620]
"JavaScript bindings for Dear ImGui using Emscripten and TypeScript "
by @flyover
Github https://github.com/flyover/imgui-js
Readme https://flyover.github.io/imgui-js/

There's a web demo which even supports gamepad.
https://flyover.github.io/imgui-js/example/

Interestingly the web demo has a sandbox window when you can input imgui code and it's get evaluated live (it's easy to break the library with mismatch Begin/End pairs at the moment, something which I would like to improve in the future)
![image](https://user-images.githubusercontent.com/8225057/36264106-30d6eee2-126c-11e8-99bf-6cc655e00426.png)

**Comment by heroboy** [comment]
This is why I opened this issue https://github.com/ocornut/imgui/issues/204 long ago
