### ISSUE TITLE
ImGui::PlotLines doesn't draw lines when all values are the same

### ISSUE THREAD

**Issue by MarkSill** [ocornut/imgui#1621]
Using imgui 1.50 with love.imgui on Windows 10 and Ubuntu 17.10.

When drawing a graph with `ImGui::PlotLines` where all values are the same, no lines are visible.

In the pictures, the top graph adds some extra values so that the graph is always visible (since it's common to remain at 60 FPS for extended periods of time). The bottom graph also does this, but it appends zeros, so when it's all zeros, nothing is visible.

Example of data where lines _are_ drawn:
![data](https://user-images.githubusercontent.com/1900613/36291304-0594c868-127f-11e8-8886-329873e2d40e.png)

Example of data where no lines are drawn for the file access graph.
![no_data](https://user-images.githubusercontent.com/1900613/36291309-080d9ee4-127f-11e8-8b7f-c31d1e52344a.png)

Example Lua code:
```lua
local values = {}
for i = 1, 120 do
    values[i] = 0
end

imgui.PlotLines("graph", values, #values)
```

Untested C++ code:
```c++
float lines[120];
ImGui::PlotLines("graph", lines, 120);
```

**Comment by ocornut** [comment]
Hello,

If you don't pass an explicit scale_min/scale_max imgui needs to calculate the range based on the value.
I pushed a fix to avoid a divide by zero if all the values are the same, it seems appropriate.

You may either update your Löve bindings or apply the same patch locally.

```
ImGui::Begin("Test #1621");

float lines[120];
for (int n = 0; n < 120; n++)
    lines[n] = 0.0f;
ImGui::PlotLines("graph 0.0f", lines, 120);

for (int n = 0; n < 120; n++)
    lines[n] = 1.0f;
ImGui::PlotLines("graph 1.0f", lines, 120);

ImGui::End();
```
