### ISSUE TITLE
[Linux] two warnings at build time (1.60 WIP)   

### ISSUE THREAD

**Issue by ebachard** [ocornut/imgui#1623]
Hi,

Building on Linux x86_64, I got two similar warnings. As written in the log:
```
src/3rdparty/imgui/imgui.cpp:4890:6: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
 void ImGui::ClosePopup(ImGuiID id)
      ^
src/3rdparty/imgui/imgui.cpp: In function ‘void ImGui::EndMenu()’:
src/3rdparty/imgui/imgui.cpp:11242:6: warning: assuming signed overflow does not occur when assuming that (X - c) > X is always false [-Wstrict-overflow]
 void ImGui::EndMenu()
      ^
```
Maybe my compiler is too old (using gcc-5.4.0 and g++-5.4.0 ). 

FYI, I'm using the following flags:
```
gcc -O3  -Wall -fPIC -std=c99  // for the gcc part
g++ -O3  -std=c++11 -Wall -fPIC  -DBUILDING_LINUX_VERSION  // for the g++ part
```

As a fix,  see https://gist.github.com/ebachard/ceae85bd3df3f738623897421d8c1cfe . If ever I'm plain wrong with my hack, feel free to close the issue and do what you want. If you consider the code useful, just use it :-)

I didn't put the full build command line, but if you need it, I can add it, no problem.

Last, as a feedback, upgrading from 1.54 to 1.60 was really easy: simply following your instructions, and I directly built it ! Thanks again for your great ImGui !

**Comment by ocornut** [comment]
Hello,
I couldn't find a satisfying and clear way to silence this. It's up to whatever the optimizer does and tricky.
I added some extraneous asserts and disabled the warning for GCC.
Ref
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
Thanks!
