### ISSUE TITLE
Window clipping isuses after upgrading to 1.60 WIP

### ISSUE THREAD

**Issue by stfx** [ocornut/imgui#1624]
I have recently upgraded from 1.51 to 1.60 WIP due to keyboard navigation (fantastic work!) and have noticed that some content is now being clipped by a few pixels.

Below is the easiest reproduction case I could come up with which draws a reticle in the center of the screen. In 1.51 the circle including outline is completely drawn but in 1.60 WIP the top and left side of the outline is being clipped off by about 1px. Additionally minimum window size seems to be limited to 32x32px but that was already in 1.51 too.

Windows with other text/content are now being clipped off by some pixels at well (I am using a custom fixed-width font). Have there been any changes regarding that that I don't know of?

```c++
// @ screen resolution 1280x720
float reticleDiameter = 6.f;
ImVec2 _reticleCenter = ImGui::GetIO().DisplaySize * 0.5f;
ImVec2 _reticleWindowSize = ImVec2(reticleDiameter, reticleDiameter);
ImVec2 _reticleWindowPosition = _reticleCenter - _reticleWindowSize * 0.5f;

float _reticleThickness = 1.f;
float _reticleRadiusOutline = reticleDiameter * 0.5f;
float _reticleRadius = _reticleRadiusOutline - _reticleThickness;
ImU32 _reticleColorOutline = ImGui::ColorConvertFloat4ToU32(ImVec4(1.f, 0.f, 0.f, 1.f));
ImU32 _reticleColor = ImGui::ColorConvertFloat4ToU32(ImVec4(1.f, 1.f, 1.f, 1.f));

ImGui::GetStyle().WindowPadding = ImVec2(0, 0);
ImGui::GetStyle().WindowRounding = 0;
ImGui::SetNextWindowPos(_reticleWindowPosition);
ImGui::SetNextWindowSize(_reticleWindowSize);

ImGui::Begin("reticle", nullptr, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollWithMouse | ImGuiWindowFlags_NoInputs);
ImDrawList* drawList = ImGui::GetWindowDrawList();
drawList->AddCircleFilled(_reticleCenter, _reticleRadius, _reticleColor, 12);
drawList->AddCircle(_reticleCenter, _reticleRadiusOutline, _reticleColorOutline, 12, _reticleThickness);
ImGui::End();
```

**Comment by ocornut** [comment]
The change is probably that window now have a border size by default.

`style.WindowBorderSize = 1.0f;`

And we made every borders not affect sizes/layouts because that simplifies code (both for imgui and user), however in the case of windows the border size affects the clipping rectangle.

While this is enough info for you to fix it, I'm wondering how much of that will affect users of previous version. For it to affect you, you'd need to have WindowPadding < WindowBorderSize, aka WindowPadding = 0.0f.

**Comment by stfx** [comment]
Thanks @ocornut, changing to `style.WindowBorderSize = 0.f;` does indeed make it work like before and fix it in my case and I agree that probably very few people use `WindowPadding` at zero.

Btw do you have any insights on why a window size can't be below 32px on both width and height?

**Comment by ocornut** [comment]
There's a value `style.WindowMinSize` (= enum `ImGuiStyleVar_WindowMinSize`) you can adjust.
It's just convenient for regular windows to have a minimum, in reality we should more clearly separate them between manual resize vs programmatically resized values.
