### ISSUE TITLE
Is there a way to have a tree with nodes, that can be reparented by dragging?

### ISSUE THREAD

**Issue by Tim4135** [ocornut/imgui#1625]
Hi,

So i am trying to create a Game Engine using Imgui, and i am wondering if this is possible.
I want to use it for a object hierarchy, like Unreal Engine and unity have, where you can drag an object onto another object, and it becomes part of it.
Is there a way to do that?

Thanks

**Comment by ocornut** [comment]
Hello Tim,

It's probably possible but I haven't attempted it myself and it's probably a little tricky or awkward to do right at the moment. It's one of the remaining task of #143 to implement that sort of pattern in the demo and possibly helpers to make it easier.

**Comment by Tim4135** [comment]
Could you maybe give me an idea on how I could do this?

**Comment by ocornut** [comment]
That's what the drag and drop API is for. It's not a trivial thing to handle if you want to use it to both reorder and reparent nodes. so if you aren't comfortable with imgui as your other posts suggests it may be a little tricky in the current state. Do you already have a tree with nodes showing your scene?

**Comment by Tim4135** [comment]
Yes, i do already have a list with tree nodes, now i want to be able to reorder them and parent them.
Is there some documentation on the Drag and Drop api? Or is that not a part of imgui?

**Comment by ocornut** [comment]
The drag and drop is already in imgui, it's in beta and not well documented but if you look for it you'll find ways to use it.

**Comment by Tim4135** [comment]
Well, could you then maybe provide where it is defined in IMgui files, or some function names?

**Comment by ocornut** [comment]
I am sorry Tim I cannot hand-hold you like that, if you can't figure out where to locate it you are giving me a strong signal that you are not trying.
