### ISSUE TITLE
How can I get layer of each UI widget?

### ISSUE THREAD

**Issue by IngoChou** [ocornut/imgui#1630]
Hello, 

I want to get layer of each UI widget, such as window background, text, editor, button and so on, so I can render them at different depth. There is z-fighting problem in my App.

Thanks for your help.

**Comment by ocornut** [comment]
> There is z-fighting problem in my App.

The vertices are 2d and don’t have a Z component. You need to render the imgui mesh with depth-test and depth-write disabled as all the examples are showing.

**Comment by IngoChou** [comment]
Ok, thanks for your help.
