### ISSUE TITLE
Crash on loading a font from a file

### ISSUE THREAD

**Issue by onqtam** [ocornut/imgui#1631]
So today I updated imgui (hadn't done that in more than 1 month) and while migrating (now using ```ImGui::CreateContext();``` and etc.) I saw that my program crashes (asserts) on this code:

```c++
    ImGui::CreateContext();
    ImGui_ImplGlfwGL2_Init(window, true);

    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->AddFontFromFileTTF("D:/rcrl/src/third_party/imgui/extra_fonts/Cousine-Regular.ttf", 17.f);
```

This code used to work but now calling ```ImFileLoadToMemory()``` returns null (returned from ```ImFileOpen()``` which calls ```_wfopen()``` - returns null).

I'm positive that the path used for opening the file is still correct - nothing else in the project has changed.

**Comment by ocornut** [comment]
If you have been using the files directly from the raw imgui repo (which your path suggests so), notice the fonts have moved into the misc/ folder. So your path is invalid.

I'm personally using Everything (https://www.voidtools.com) to locate files in a second. That sort of tool would help you verify the "the path used for opening the file is still correct" assertion easily.

**Comment by onqtam** [comment]
embarrassing... thanks!
