### ISSUE TITLE
Node graph editor / Lines for Animator State Machine

### ISSUE THREAD

**Issue by julienangel** [ocornut/imgui#1632]
Hi there,

It would be possible do draw lines like this?

https://blogs.unity3d.com/wp-content/uploads/2014/06/mecUnity5-2.png

I am trying to make an animator state machine.

Cheers

**Comment by nem0** [comment]
https://github.com/ocornut/imgui/issues/306

**Comment by ocornut** [comment]
You may use the ImDrawList API e.g. `ImDrawList::AddLine()` to render custom primitives.

If your question is about creating a full blown node editor you can check #306 as pointed out.
