### ISSUE TITLE
How can I get vertices of each widget?

### ISSUE THREAD

**Issue by IngoChou** [ocornut/imgui#1634]
Hello,

 ImGui uses a vertex buffer which saves all vertex. But I want to operate vertices of some ImGui widget by its name or ID. As we all know, cmd_list->CmdBuffer[i]  also includes many widgets, not a single widget.

So, my question is:
1. How can I distinguish vertices for each widget (e.g. background, text, button, edtor ... ) in the ImGui vertex buffer?
2. If I can distinguish vertices for each widget, how can I get its widget type? e.g. text or button ?

Thanks for help.

**Comment by ocornut** [comment]
You cannot do either. Are you asking for the same question as in #1630?
When you ask for such feature please always explain the context (why you need it), it’s hard to give a correct answer without a context.

**Comment by IngoChou** [comment]
Hello, ocornut ,

Thanks for your reply. I want to select a widget and drag it to any where. Not only select the widget by mouse, but also by its name or ID in my code. I also want to implement widget animation by change/update its vertices and/or color.

Thanks for your help.

**Comment by ocornut** [comment]
Hello, unfortunately "drag it to any where" or "widget animation" are too vague and generic statement to provide a good answer. Selection/dragging can be achieved in various way depending on the context: drag and drop api etc, probably involve state on your side. It really depend what you actually need to do. I cannot give a more accurate answer without understanding the problem.

You probably don't want to be altering vertices already submitted to the ImDrawList. You can create custom widgets code, or use the ImDrawList API to render stuff, or alter the style to change colors emitted by existing widgets. 

It looks like you may be trying to go against the current and design of dear imgui. While it's possible to twist it in many interesting and useful ways it's generally not something I'd suggest if you just recently started using the library. Generally with more experience using the library you start getting a feel or where to hit to make the thing you want to happen.
