### ISSUE TITLE
Keyboard Navigation Tweaks

### ISSUE THREAD

**Issue by domgho** [ocornut/imgui#1640]
I have tried out dear imgui's new fantastic navigation implementation in 1.60 WIP and could get it to work for my usage case (end-user UI) very well except for two little things:

1. Is there a way to make a widget nav focused by default so that upon pressing SPACE you could immediately activate a button?
Context: I would like to hit SPACE right after showing the pause UI to press the first button (resume). Currently SPACE or arrow keys need to be pressed first to activate navigation and only then the user can press the first button (SPACE again) or navigate to others. If however the window had active navigation the last time it was shown it now allows SPACE immediately to activate the first button which seems inconsistent. I tried using `ImGui::SetItemDefaultFocus();` and `ImGui::SetNextWindowFocus();` to no avail. This behavior also only happens with normal windows, on popups navigation works without activating first expected.

2. How can you make it so certain widgets do not need to be activated first with SPACE before changing their values?
Context: I would like to simply allow LEFT + RIGHT to change slider values in the settings UI without pressing SPACE first as all widgets are placed vertically and users do not expect the current behavior.

I am aware that my requirements might be slightly different than the norm so I would appreciate any pointers where to look to implement/change this myself.

**Comment by ocornut** [comment]
1.A. There are two different questions here. 
Nav is initially only activated on the first key-press, and the nav cursor becomes hidden when mouses move, that's one thing. If you keep using nav it'll stay activated. We probably need a call to control that. 
You can may create your own function using `imgui_internal.h` and do:
```
g.NavDisableHighlight = false;
g.NavDisableMouseHover = true;
```
(This doesn't come with guarantee of forward compatibility, but will probably be good enough for a workaround for you at the moment).

1.B. `SetItemDefaultFocus()` does that, but the cursor won't show if NavDisableHighlight == true which is the case by default. See if calling the function above after initialization or when opening your menu fixes it for now.

2. You cannot with the default widgets.
You probably want to implement your own widgets there, which would be easy for the kind of widget you need.
When your widget is Active you may alter ActiveIdAllowNavDirFlags to automatically inhibit certain Nav direction. When you widget is merely Focused/Hovered you'll need to catch those move requests and cancel them with `NavMoveRequestCancel()` (also from imgui_internal.h, just exposed).

**Comment by stfx** [comment]
Thanks @ocornut, very helpful!

1.
```c++
ImGuiContext& g = *ImGui::GetCurrentContext();
if (g.CurrentWindow->Appearing)
{
	g.NavDisableHighlight = false;
	g.NavDisableMouseHover = true;
}
```
now highlights the first widget on showing the window until mouse is moved which is perfect and while SPACE now works to press the button the first time it unfortunately still requires two presses after the showing the window subsequently. This only happens if I close the window when pressing SPACE on a button that closes it (even on next frame in my case) and even on default imgui. This might be a bug as on subsequent window show you can navigate with the arrow keys but still need to press SPACE twice to press a button.

2.
I was able to get the slider to behave as requested thanks to your input with the changes below. Do you maybe have any pointers on how to disable keyboard activation using SPACE on certain widgets as this is an unwanted state for those sliders now?
```diff
diff --git a/imgui.cpp b/imgui.cpp
index 8f3492e..f02d2cf 100644
--- a/imgui.cpp
+++ b/imgui.cpp
@@ -8545,7 +8545,8 @@ bool ImGui::SliderBehavior(const ImRect& frame_bb, ImGuiID id, float* v, float v
     const ImGuiStyle& style = g.Style;
 
     // Draw frame
-    const ImU32 frame_col = GetColorU32((g.ActiveId == id && g.ActiveIdSource == ImGuiInputSource_Nav) ? ImGuiCol_FrameBgActive : ImGuiCol_FrameBg);
+    const bool navHovered = g.NavId == id && !g.NavDisableHighlight && g.NavDisableMouseHover && (g.ActiveId == 0 || g.ActiveId == id || g.ActiveId == window->MoveId);
+    const ImU32 frame_col = GetColorU32(g.ActiveId == id ? ImGuiCol_FrameBgActive : g.HoveredId == id || navHovered ? ImGuiCol_FrameBgHovered : ImGuiCol_FrameBg);
     RenderNavHighlight(frame_bb, id);
     RenderFrame(frame_bb.Min, frame_bb.Max, frame_col, true, style.FrameRounding);
 
@@ -8597,11 +8597,10 @@ bool ImGui::SliderBehavior(const ImRect& frame_bb, ImGuiID id, float* v, float v
 
     // Process interacting with the slider
     bool value_changed = false;
-    if (g.ActiveId == id)
     {
         bool set_new_value = false;
         float clicked_t = 0.0f;
-        if (g.ActiveIdSource == ImGuiInputSource_Mouse)
+        if (g.ActiveId == id && g.ActiveIdSource == ImGuiInputSource_Mouse)
         {
             if (!g.IO.MouseDown[0])
             {
@@ -8616,7 +8615,7 @@ bool ImGui::SliderBehavior(const ImRect& frame_bb, ImGuiID id, float* v, float v
                 set_new_value = true;
             }
         }
-        else if (g.ActiveIdSource == ImGuiInputSource_Nav)
+        else if (navHovered)
         {
             const ImVec2 delta2 = GetNavInputAmount2d(ImGuiNavDirSourceFlags_Keyboard | ImGuiNavDirSourceFlags_PadDPad, ImGuiInputReadMode_RepeatFast, 0.0f, 0.0f);
             float delta = is_horizontal ? delta2.x : -delta2.y;
@@ -8626,6 +8625,7 @@ bool ImGui::SliderBehavior(const ImRect& frame_bb, ImGuiID id, float* v, float v
             }
             else if (delta != 0.0f)
             {
+                NavMoveRequestCancel(); // not really needed in my case
                 clicked_t = SliderBehaviorCalcRatioFromValue(*v, v_min, v_max, power, linear_zero_pos);
                 if (decimal_precision == 0 && !is_non_linear)
                 {
```
