### ISSUE TITLE
Unused variable compiler warning (pairSetCount)

### ISSUE THREAD

**Issue by norsetto** [ocornut/imgui#1642]
Hi! Not really an issue, more of a wish ... anyhow, there is an annoying compiler warning when processing stb_truetype.h:

stb_truetype.h:2454:42: warning: unused variable ‘pairSetCount’ [-Wunused-variable]
                                    stbtt_uint16 pairSetCount = ttUSHORT(table + 8);

caused by the fact that this is only used in an assert; I just added a `STBTT__NOTUSED(pairSetCount);` after the `STBTT_assert(coverageIndex < pairSetCount);` to get rid of it.

**Comment by ocornut** [comment]
Fixed thanks. I'll make a pull request on the original repo as well.
