### ISSUE TITLE
Image() doesn't seem to work though AddImage() does?

### ISSUE THREAD

**Issue by hippyau** [ocornut/imgui#1644]
Hi there,
    So I've resisted asking and tried for days to solve this, tried to eliminate all other parts besides core ImGui but who knows.  I'm using CImGui with virtually unmodified ImGui DirectX 11 example code to create the windows and do everything, then there is a callback to PureBasic for the run loop where we create the widgets, it returns and then the frame is rendered - I literally added one line to the DX example loop code, and being binded to PureBasic through a DLL is working great so far, except Image().

The run loop in the DLL that is calling this callback looks like the below, with all the DX initialization and ImGui_Impl* basically just cut and paste from the ImGui DX11 Example...

```cpp
[...]
		ImGui_ImplDX11_NewFrame();

		// run the callback to PureBasic
		if (ptr_reg_callback) (*ptr_reg_callback)();

		// Rendering
		g_pd3dDeviceContext->OMSetRenderTargets(1, &g_mainRenderTargetView, NULL);
		g_pd3dDeviceContext->ClearRenderTargetView(g_mainRenderTargetView, (float*)&clear_color);
		ImGui::Render();
[...]
```

so in PureBasic, I make a window...  (Excuse the PureBasic, but this code is working and pretty easy to follow)
```purebasic
        igBegin("Purebasic ImGUI Image", @show_window2, 0)         
        ; // use a drawlist to show the texture
        Protected *drwlist = igGetWindowDrawList()
        ImDrawList_AddImage(*drwlist, *texID, 100,100,512,512)     
        ; // try use the ImGui Image widget  (note, the ImVec2 & ImVec4 are easier to passed as individual float values due to PB compiler, that seems to work fine with every other function in the API.)
        ; //     tex       w/h       uva    uvb     tint rgba   boarder rgba
        igImage(*texID,  512,512, 0.0,0.0,1.0,1.0,   0,0,0,0,   255,0,255,255) 
        igEnd()
```

I worked out a class to load the texture inside the DLL, and this is clearly loading the image handing back a texture ID, and seems to be working fine, I can confirm I have a good texture ID (ID3D11ShaderResourceView*) . 

Now the window on the right, the Image widget is there, at the right size with the border coloured magenta.  There should be an image there in that border.  
![imgui_window_a](https://user-images.githubusercontent.com/36442309/36629199-6c49c5c4-199e-11e8-932f-292549c169d2.png)

But, if I use GetWindowDrawList() or GetOverlayDrawList() with AddImage() I can see my texture is loaded and valid - but fixed to the main window, not the imgui window.  I get that, but shouldn't Image() work just fine if the texture ID is okay? I realize the texture ID is a function of DirextX, but it appears to be valid and working.  (I use WIC to load my test.png, that seems to be working fine?)

Drag the window to the left...

![imgui_window_c](https://user-images.githubusercontent.com/36442309/36629455-ad7448aa-19a1-11e8-9a6b-39b13062aeb3.png)

And all the way to the left....

![imgui_window_b](https://user-images.githubusercontent.com/36442309/36629262-611c855a-199f-11e8-8c7e-e13274c28180.png)

All I have done between these two images is move the window over to the left with the mouse, this is with igGetWindowDrawList().
Naturally if I use the overlay draw list, it's on top and always visible.

So I can load a texture, that is working it seems, but why would Image() not work when Add_Image() does?  Is this a context thing maybe?   But maybe it's transparent?   I'm not too good with DX, but this is almost working, and I can't tell if a ImGui or a DX problem :(

 I'm loading with this code below, this happens in PureBasic via calls to the DLL, but only after all the DX is running, it executes once after the first call or ImGui_ImplDX11_NewFrame(); and before the first call of ImGui::Render();

```cpp
Initialize(g_pd3dDevice, g_pd3dDeviceContext, filename);
```
Which is...

```cpp
bool TextureClass::Initialize(ID3D11Device* device, ID3D11DeviceContext* context, wchar_t* filename)
{
	// Load the texture in
	HRESULT hr = DirectX::CreateWICTextureFromFile(device, context, filename, &m_resource, &m_texture);
	if (FAILED(hr))
		return 0;

	return true;
}
```

Cheers, 
  Hippy

**Comment by ocornut** [comment]
Hello,

1.
On the positioning with `ImDrawList::AddImage()` : the ImDrawList low-level API is unaware of the windowing aspect, so all the positions you pass to it are absolute. Note how `ImDrawList::AddImage()` takes position as parameters and `ImGui::Image()` doesn't because it layout the image from the current position (`ImGui::GetCursorScreenPos()` for screen absolute coordinates). So knowing that you could fix the AddImage call by using `GetCursorScreenPos()` as a position. You may also call `ImGui::Dummy()` just to advance the ImGui layout cursor.

2.
However, why `ImGui::Image()` doesn't work seems really mysterious to me given the information you provided, there's a bug somewhere waiting to be solved.
You may want to double-check if your PureBasic to C or C to C++ bindings are passing all the parameters correctly, in the same order as expected by the native library?
You can also use the Metrics window `ShowMetricsWindow()` to inspect the individual draw calls and you'll see the vertices emitted by the `Image()` function and maybe that would help narrowing the problem.

Thank you for writing a detailed message.

**Comment by hippyau** [comment]
Argh, I am freaking an idiot.....   Sorry,  I screwed up.... for days!   Tint values of zero, the image was invisible and not even being drawn as the alpha was 0.   Duh!    Sorry, ignore entirely.  

Everything is great, I'll share this binding when it's ready,  and thanks for the support... your message prompted the discovery.
