### ISSUE TITLE
AddRect() without AntiAliasedLines missing a pixel

### ISSUE THREAD

**Issue by or75** [ocornut/imgui#1646]
// style.AntiAliasedLines = false;
// ImGui.cpp : 6000
```
// Borders example +10,10
if ( window_border_size > 0.0f )
{
	window->DrawList->AddRect( window->Pos , window->Pos + window->Size + ImVec2( 10.f , 10.f ) , 
	GetColorU32( ImGuiCol_Border ) , window_rounding , ImDrawCornerFlags_All ,window_border_size );
}
```
the right lower pixel is not displayed
with others, everything is fine

![sharex_2018-02-25_13-43-25](https://user-images.githubusercontent.com/5619678/36640535-ed745a40-1a31-11e8-9408-017722165a4d.png)

**Comment by ocornut** [comment]
Hello, I had noticed this issue with the non-AA path. 
Made a fix for it now which doesn't affect the rounding rect.
I think the AA path should actually be using this path for non-rounded rectangle, will save a few vertices/cpu.

Test code

[code]ImGuiStyle& style = ImGui::GetStyle();
style.Colors[ImGuiCol_Border] = ImVec4(1, 0, 0, 1);
style.FrameBorderSize = 1.0f;
style.WindowRounding = 0.0f;
style.AntiAliasedLines = io.KeyCtrl;[/code]
