### ISSUE TITLE
How can i render IDirect3DSurface9 to native window's background as a big background of imgui ?

### ISSUE THREAD

**Issue by shithappens2016** [ocornut/imgui#1648]
Hello
I need  render IDirect3DSurface9 to native windows's background. then render all imgui widgets above it.
how could i do that?

**Comment by ocornut** [comment]
I am sorry this is a DirectX9 question not an imgui question. If you check directx9_example/main.cpp you’ll see how imgui is rendered. You can that at any time.

**Comment by shithappens2016** [comment]
thanks. i'll check directx9_example/main.cpp
