### ISSUE TITLE
Slider available when checkbox checked

### ISSUE THREAD

**Issue by Haterul** [ocornut/imgui#1652]
Hello, so I have a question. Is it possible to make that sliders to be available only when a checkbox is checked?
![slider](https://user-images.githubusercontent.com/26658878/36851846-f1ff61e2-1d72-11e8-9d64-9d3ead2fa149.png)

Like, FOV View and FOV Model View to be visible/available only when FOV Changer checkbox is checked?

**Comment by ocornut** [comment]
Yes, you can use an `if` statement.

**Comment by Haterul** [comment]
Can you give me an example, please?

**Comment by ocornut** [comment]
Please refer to C/C++ books or tutorials about how to use if statements, here isn’t the place sorry.

**Comment by ocornut** [comment]
Apologies to myself, I didn't immediately realize this was another case of CS GO cheating.
Sorry but #1586

**Comment by aylaylay** [comment]
How is it any of your business what he's using it for?

**Comment by ocornut** [comment]
@aylaylay The amount of support requests are already overwhelming, I'm doing this by myself, and there is a huge overlap between cheaters and: ill-defined time-wasting requests from entitled people who have no interest in programming and asking me to solve their homework while making it as hard as possible to me to mind-read them. 

It's an easy line to draw really.

**Comment by ice1000** [comment]
@Haterul if u can spend 1 sec on reading the demo n u'll know:

```cpp
static bool isChecked = false;
ImGui::Checkbox("FOV Changer", &isChecked);
if (isChecked) {
  ImGui::SliderInt // pass your arguments
}
```

**Comment by dexterdeeznuts** [comment]
learn c++
