### ISSUE TITLE
Window's center

### ISSUE THREAD

**Issue by 0x452** [ocornut/imgui#1657]
Hello Omar!

Is there any function to move window center in the middle of the window? I want to place my window at the center of my screen but window moves from center if it trying to be bigger.

**Comment by ocornut** [comment]
You can use
`SetNextWindowPos(ImVec2(io.DisplaySize.x * 0.5f, io.DisplaySize.y), ImGuiCond_Always, ImVec2(0.5f,0.5f))`

**Comment by PsychoCoffee** [comment]
Where is `io` declared?

**Comment by Zordon1337** [comment]
> Where is `io` declared?

use ImGuiIO& io = ImGui::GetIO();
