### ISSUE TITLE
Erreur C2039 'Hotkey' : n'est pas membre de 'ImGui'

### ISSUE THREAD

**Issue by QxZK** [ocornut/imgui#1662]
(Please carefully read guidelines in [CONTRIBUTING.md](https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md) then delete this line)

You can include code this way:
```cpp
ImGui::Begin("Hello");
ImGui::ThisIsMoreCode();
```
Salut, come je sis que tu est français ça va etre plus simple 👍 
En gros, j'ai voulu update un paste cheat en rajoutant la derniere update de imgui, sauf que en le compilant il m'affiche comme erreur:
Erreur C2039 'Hotkey' : n'est pas membre de 'ImGui'
sauf que pour les autres j'avais compris comment les régler, sauf que la le soucis c'est que je ne trouve rien dans imgui.cpp, rien n'indique comme quoi il a changé de nom ou quoi... Si tu pourrais m'aider ça serais cool, merci bcp

**Comment by ocornut** [comment]
Sorry but #1586
