### ISSUE TITLE
error with hotkey missing

### ISSUE THREAD

**Issue by noobshowesl** [ocornut/imgui#1663]
Hi, So i have update imgui for my battlenet account manager but hotkey is missing rename or juste replaced ? Thanks you very much
All the best
Jordan

**Comment by ocornut** [comment]
Sorry but #1586 #1662
Please stop posting here with new accounts, your problem has nothing to do with imgui, there’s no ‘hotkey’ in imgui, you are expecting us to magically fix your code without even providing the code, and you haven’t read the guideline, this is disrespectful and ridiculous.
