### ISSUE TITLE
How to upgrade to 1.60 (master release)?

### ISSUE THREAD

**Issue by bjadamson** [ocornut/imgui#1665]
Hi, I recently just tried upgrading my project from 1.53 to the latest master. I found a bunch of functions I used to call, seem to be missing their implementations in the new imgui.cpp file.

At least, that's what I'm seeing. For example, ColorEdit4 in 1.53 was defined in imgui.h. It was implemented in [imgui.cpp](https://github.com/bjadamson/BoomHS/blob/release/external/imgui/source/imgui.cxx#L9841).

In the newest version, I can't find the implementation of that [function anywhere in imgui.cpp](https://github.com/ocornut/imgui/blob/master/imgui.cpp). I looked through the other cpp files for an implementation, as well as the rest of the project.

Thanks, truly confused..

**Comment by ocornut** [comment]
Hello @bjadamson,

Which errors are you getting?
The "API BREAKING CHANGES" section of imgui.cpp should list changes but there shouldn't be that much.

`bool ImGui::ColorEdit4(const char* label, float col[4], ImGuiColorEditFlags flags)` is still in imgui.h and imgui.cpp, but github doesn't display the full files.

**Comment by bjadamson** [comment]
Ah. Thanks for teaching me a bit about github. I see it there when viewing the raw file, thanks!
