### ISSUE TITLE
BeginChild Resize to Contents?

### ISSUE THREAD

**Issue by skl131313** [ocornut/imgui#1666]
Is there a resize to content mode for an axis using `ImGui::BeginChild()`?

I want to have horizontal scrolling but I don't want there to be vertical scrolling. I want it to resize to the size of the contents vertically. Is there anything like this?

I can manually set a fixed size, but then I need to calculate and compensate for when the horizontal scrollbar might be visible.

**Comment by ocornut** [comment]
Hello @skl131313, unfortunately it isn't possible at the moment. I see what you are trying to do and agree it would be helpful. I have an idea of how to implement it but it's not a trivial change and I don't know when I'll be able to tackle it.

In the meanwhile, maybe using both flags `ImGuiWindowFlags_HorizontalScrollbar | ImGuiWindowFlags_AlwaysHorizontalScrollbar` can allow you to compute that extra height for the scrollbar since it won't change any more.

**Comment by skl131313** [comment]
No worries if it requires a big change, it's more of a nice to have feature than a requirement.

**Comment by ocornut** [comment]
It is now possible to
- manually resize child windows (on either axis)
- make child windows auto-fit (on either axis)

See #1710 and new examples in "Demo->Layout->Child Windows"

Basic auto-resize:
```cpp
ImGui::BeginChild("name", ImVec2(-FLT_MIN, 0.0f), ImGuiChildFlags_Border | ImGuiChildFlags_AutoResizeY);
```

Using a min/max constraint may be particularly useful:

```cpp
ImGui::SeparatorText("Auto-resize with constraints");

static int draw_lines = 3;
static int max_height_in_lines = 10;
ImGui::SetNextItemWidth(ImGui::GetFontSize() * 8);
ImGui::DragInt("Lines Count", &draw_lines, 0.2f);
ImGui::SetNextItemWidth(ImGui::GetFontSize() * 8);
ImGui::DragInt("Max Height (in Lines)", &max_height_in_lines, 0.2f);

ImGui::SetNextWindowSizeConstraints(ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 1), ImVec2(FLT_MAX, ImGui::GetTextLineHeightWithSpacing() * max_height_in_lines));
if (ImGui::BeginChild("ConstrainedChild", ImVec2(-FLT_MIN, 0.0f), ImGuiChildFlags_Border | ImGuiChildFlags_AutoResizeY))
    for (int n = 0; n < draw_lines; n++)
        ImGui::Text("Line %04d", n);
ImGui::EndChild();
```
![child_resizable2_with_constraints](https://github.com/ocornut/imgui/assets/8225057/70492343-8930-498d-ae75-0c78bbbb12b8)

If you omit the `SetNextWindowSizeConstraints()` you can have auto-resizing on either axis.

Please note that combining both `ImGuiChildFlags_AutoResizeX` AND `ImGuiChildFlags_AutoResizeY` together is not recommended as it undo the main purpose of child windows.
