### ISSUE TITLE
Hello, Question Regarding DX9 Texture Filtering!

### ISSUE THREAD

**Issue by ClaudiuHKS** [ocornut/imgui#1669]
Hi!

I have changed D3DTEXF_LINEAR to D3DTEXF_ANISOTROPIC, will this make a difference? I am just curious, I want the highest quality ever for my DX9 application!

@imgui_impl_dx9.cpp

```cpp
    g_pd3dDevice->SetSamplerState(0, D3DSAMP_MINFILTER, D3DTEXF_ANISOTROPIC);
    g_pd3dDevice->SetSamplerState(0, D3DSAMP_MAGFILTER, D3DTEXF_ANISOTROPIC);
```

**Comment by ClaudiuHKS** [comment]
Or defining STBTT_MAX_OVERSAMPLE to 128, will this help too? Thanks!

**Comment by dpethes** [comment]
Anisotropic won't make any difference; it improves sampling on textures that are rendered on surfaces that are tilted/at an angle to the screen. Imgui doesn't do that.

**Comment by ocornut** [comment]
Neither would make a difference.
I am closing this under the law of Sorry but #1586 to save myself and everyone time.

**Comment by MMOForum** [comment]
Hi bro 
![Ekran_Alnts](https://user-images.githubusercontent.com/126662627/224025290-febd2a6d-30a2-4c59-8cfa-ce1acbff8ec2.PNG)
Help me
