### ISSUE TITLE
SliderFloat Problems

### ISSUE THREAD

**Issue by 4Sharer** [ocornut/imgui#1672]
Hello,
so I have a issue. When I use the sliderfloats I always have this small variable underneath the slider that I want to remove but I am not able to find a way to do so.

![unbenannt](https://user-images.githubusercontent.com/37192162/37171644-cc55244e-230e-11e8-920a-52fe47d739e8.png)

I hope you know a answer.

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by 4Sharer** [comment]
why are you declaring this as a cheat?

**Comment by ocornut** [comment]
It is a combination of heuristic:
- Account created five minutes before posting. First post. 
- Terminology of values displayed.
- Poster doesn't actually explain anything (no code, little information) and expect me to magically read their mind and the code on their hard-drive.
- Doesn't provide the basic information requested by the Issues template.

Those factors also are clashing badly with the fact that the screenshot shows custom widgets. People who can make custom widgets would not be that vague and unhelpful in their own request to ask for help.
