### ISSUE TITLE
Covariant / CovScript bindings

### ISSUE THREAD

**Issue by mikecovlee** [ocornut/imgui#1673]
Hey! I am a C++ developer from China.
Recent days I have implemented a ImGui binding for my own programming language which called [Covariant Script](https://github.com/covscript).
The code is hosting on [CovScript ImGui](https://github.com/covscript/covscript-imgui).
Can you give us some advice? Thanks.

**Comment by ocornut** [comment]
Hello Michael.
I have added a link to your bindings from the [Wiki page](https://github.com/ocornut/imgui/wiki/Links). If you have any questions/requests feel free to ask here.

**Comment by ocornut** [comment]
Closing as you don't seem to be asking anything more.
