### ISSUE TITLE
how ImGUI::Button and ImGUI::NextColumn changes DC.CursorPos?

### ISSUE THREAD

**Issue by wbc91** [ocornut/imgui#1675]
I set the DC.CursorPos by using SetCursorScreenPos()method. But after calling ImGUI::Button and ImGUI::NextColumn, the pos has changed. The buttons belongs to ImGUI::TreeNode.  Can you explain how the button works and how can I manually set positions to widget. Thanks.

**Comment by ocornut** [comment]
Hello wbc91, could you provide a code example to clarify your use case and question. Include code, tell us what you expect of this code, tell us what it happening and how that doesn't match your expectation. At the moment your question is a little wide and vague.

Both Button and NextColumn - and pretty much every call - will change the cursor position. 
Nothing "belong" to TreeNode.
You can set SetCursorPos/SetCursorScreenPos to position upcoming widgets, so you are on the right track and your question needs to be clarified.

**Comment by ocornut** [comment]
It's hard to understand what you are doing without pseudo-code or a repro. I don't know how many times you are calling NextColumns and where, etc. You can recreate a simplified version of the issue to understand it better.

Those are the vertical distances generally used:
```
float GetTextLineHeight();           // ~ FontSize
float GetTextLineHeightWithSpacing();// ~ FontSize + style.ItemSpacing.y (distance in pixels between 2 consecutive lines of text)
float GetFrameHeight();              // ~ FontSize + style.FramePadding.y * 2
float GetFrameHeightWithSpacing();   // ~ FontSize + style.FramePadding.y * 2 + style.ItemSpacing.y (distance in pixels between 2 consecutive lines of framed widgets)
```

An unframed treenode will use `FontSize + style.ItemSpacing.y`
A button will use will use `FontSize + style.FramePadding.y * 2 + style.ItemSpacing.y`

You probably don't need to bother with calling `NextColumns()` more than once, you can draw all your contents in 1 cell on both sides.

**Comment by wbc91** [comment]
hello, ocornut, I solved my problem by calling ImGUI::SameLine() after calling ImGUI::Button() and ImGUI::NextColumn. I need to read more code to understand the scheme behind them. Thanks~

**Comment by ocornut** [comment]
Nice, closing this then.
(Note: I still don't know how your code operated. Please try to provide pseudo code or a simple minimal repro when asking questions of this kind.)
