### ISSUE TITLE
NULL undeclared identifier 

### ISSUE THREAD

**Issue by zahirzohair** [ocornut/imgui#1679]
im vry new to Imgui and i want to create tabs on my project but when i add the tabs files then i get bunch of errors like NULL undeclared identifier imgui.h and many more

**Comment by ocornut** [comment]
Sorry we can’t help you if you don’t provide complete information about your context and your issue. This is not a place where we can magically read your mind and your files. There’s no official support for tabs either.

**Comment by zahirzohair** [comment]
Hi,
thank you for reply. actually i just wanna know how to add tabs to my
project ?
since im very new to imgui, i dont know where to add those codes on my
project?

**Comment by ocornut** [comment]
There is a "tabs" branch with a preliminary tab API and other resources on the Wiki (check docks/tabs).
