### ISSUE TITLE
Any way to disable keyboard capturing when dragging a slider?

### ISSUE THREAD

**Issue by franciscod** [ocornut/imgui#1682]
Hello everyone :)

I'm trying (with no success so far) to have slider which I can drag with the mouse and at the same time get keyboard events in my app. 

Got no luck with `ImGui::CaptureKeyboardFromApp(capture)`.
`ImGui::ClearActiveID()` kinda works, but I cannot keep dragging afterwards.

Is there any way to do this in the current state of the code? I'm happy to hack a solution but it would be awesome if it's already there.

Thanks,
Francisco

**Comment by franciscod** [comment]
Solved using `IsItemActive`. When a slider I'm interested in not capturing the keyboard is active, I flip a mask, and then I "and" that mask with `ImGui::GetIO().WantCaptureKeyboard`. Works! Do you think there is a better way?

**Comment by ocornut** [comment]
Hello,
Please provide code. It’s hard to read code written in english.
`if (ImGui::IsItemActive()) CaptureKeyboardFromApp(false);` I think should work.

**Comment by franciscod** [comment]
That works and was what I was looking for. Thanks!

**Comment by ocornut** [comment]
Nice. I presume in the upcoming PushItemFlag() api we could provide a flag to enforce this behavior on any kind of item. I’ll take note of this idea in my todo list.

**Comment by franciscod** [comment]
Sounds like a cool feature for the new api :)
