### ISSUE TITLE
Creating configurable hotkeys/shortcuts

### ISSUE THREAD

**Issue by SlidyBat** [ocornut/imgui#1684]
I've been trying to create configurable hotkeys/shortcuts for certain actions/buttons, something (loosely) similar to [this](http://image.webzen.net/C9/guideImage/beginnersGuide/img_basicGameCtrl5.gif) where you can click on the "button" then get user input for what key it should be and maps it to a certain action.

I've looked around and couldn't find this sort of functionality anywhere in the API (sorry if it already exists)
The closest I've gotten is creating a text box with a restricted size of 1 character, but obviously this is very hacky/ugly and it also doesn't accept special keys such as Alt/Ctrl/Shift/F1 or any combinations of those.

I was hoping this could become a feature in ImgUi, or if it is already possible using current tools then maybe someone could point me in the right direction.

Thanks!

**Comment by ocornut** [comment]
Most of that isn’t and shouldn’t be the responsibility of imgui. Imgui doesn’t know about the exact format of your input and input system.

You can create buttons to put your app in a mode where it’ll scan every possible input source/key/button and the first press detected is the key you want. If you want more elaborate feature (key combo etc) this is up to you.

And then similarly it’s up to you to decide how to display the name of a shortcut. You may display it as a regular Text() or inside a button (for a buttok you’d want to ensure its id is stable and not colliding with the id of other buttons, probably using PushId(action); Button(label) where label if your current key description followed by ### to reset the id.

**Comment by SlidyBat** [comment]
I see, guess I'll have to make my own system for it. Thanks for the help.
I'll also post the code here once I get it done in case anyone else is looking for a similar feature.

**Comment by ocornut** [comment]
> I'm still quite new to the ImGui api so if anyone has any tips on making this a bit cleaner it would be appreciated.

That's fine if it works for you.
Note that 99% of that code you wrote isn't related to ImGui at all, this isn't even remotely an imgui question nor an issue with being new to the imgui api. The functions probably don't need to be in the imgui namespace although that's your choice here.

Your Button will have conflicting id if you allow multiple actions to be mapped on the same key or if multiple keys have the same name. I wrote above how you can push PushID + the ### string operator to decorrelate the ID from the display string. The FAQ explains it and the Demo has an example of using the ### string operator for that.

**Comment by SlidyBat** [comment]
Thanks for all the help. When I said cleaner I actually meant visually. ATM I write text with ImGui::Text then make the button with ImGui::Button and stuff them together with ImGui::SameLine, however by doing it like this the button and the text aren't vertically centered together. I was hoping there was a better way of doing the button + text combo together.

I'll also try implementing the ID thing, thanks again.

**Comment by ocornut** [comment]
You can use `AlignTextToFramePadding()` to vertically align the text baseline.
When you are looking for something the best is to find where this seems to be done in the done code.

**Comment by AmpedScripts** [comment]
> Managed to get it done in a sort of hacky way, but its good enough for my use case. I'm still quite new to the ImGui api so if anyone has any tips on making this a bit cleaner it would be appreciated.
> 
> https://pastebin.com/gMgLQKQp

How do i use this like how do i call it?

**Comment by S1ckZer** [comment]
> > Managed to get it done in a sort of hacky way, but its good enough for my use case. I'm still quite new to the ImGui api so if anyone has any tips on making this a bit cleaner it would be appreciated.
> > https://pastebin.com/gMgLQKQp
> 
> How do i use this like how do i call it?

you found out how to use this ?

**Comment by AmpedWasTaken** [comment]
> > > Managed to get it done in a sort of hacky way, but its good enough for my use case. I'm still quite new to the ImGui api so if anyone has any tips on making this a bit cleaner it would be appreciated.
> > > https://pastebin.com/gMgLQKQp
> > 
> > 
> > How do i use this like how do i call it?
> 
> you found out how to use this ?

nope
