### ISSUE TITLE
How to get Position and Size of all exisitng windows?

### ISSUE THREAD

**Issue by Tim4135** [ocornut/imgui#1685]
Hi, 
So I have been experiementing with sfml in imgui and want to be able to click on things in the game, but want to ignore those clicks when there is a window above it.
So my idea was to get the position and size in pixels from all imgui windows, and check if the Mouse is NOT in there when the mouse button is pressed.
In order to do this, I need to get the x and y coordiantes of each window, and the size in pixels in the x and y axis.
But how can I do that?

Thanks

edit:
I am aware of the functions:
```
ImVec2 ImGui::GetWindowSize() // and
ImVec2 ImGui::GetWindowPos()
```
But how do I know of which window they return the size of?

**Comment by ocornut** [comment]
This is not the correct way to achieve what you want.
Please read the FAQ.

![image](https://user-images.githubusercontent.com/8225057/37569032-3813f356-2add-11e8-857b-0df2c76950c0.png)
