### ISSUE TITLE
Scrolling by dragging on 'empty space'?

### ISSUE THREAD

**Issue by nikki93** [ocornut/imgui#1689]
Hi! This is a great lib and it's been working well with just small integration code. :) I'm using it in an iPad / iPhone context and was wondering if it's possible to easily enable scrolling when a user clicks and drags in 'empty space' in the window? Sort of like how it happens on most mainstream UIs on iOS and Android these days.

In the demo window included with imgui it says, "Click and drag on any empty space to move window." -- I basically want this but instead of moving the parent window, to move the containing scroll region. Thanks! :)

**Comment by thedmd** [comment]
You can use invisible button covering whole screen to grab input and handle dragging. Just remember to use it at very end of your UI.

Let me know if you need more clues.

**Comment by ocornut** [comment]
Now that we have `ConfigFlags` we could consider including that sort of feature as a global flag in the codebase. Perhaps it should be wired on two-fingers touches however, which we don't have a way to wire in at the moment.

**Comment by rg-net** [comment]
Mobile will do this on one finger. So if that is the main use case perhaps we should stay consistent to what the use probably expects...

**Comment by ocornut** [comment]
> You can use invisible button covering whole screen to grab input and handle dragging. Just remember to use it at very end of your UI.

FYI I posted code to do #3379 to do this.
I'm closing this as it is essentially the same as #3379 so we can have the conversation in one spot. Will post in both threads if another solution/change is made.
