### ISSUE TITLE
Scrolling issues with node editor control

### ISSUE THREAD

**Issue by citruslee** [ocornut/imgui#1690]
During my trial to make a scrollable grid, I encountered at my code also at the [node editor sample ](https://gist.github.com/ocornut/7e9b3ec566a333d725d4) a possible bug. When you drag the window the inner canvas is moving as well. When you scroll in the inner canvas, everything is fine, and does not move the window. I can provide code listing, but it is basically right now the d3d11 example with node graph editor sample code.

here is the screen grab.
![imgui](https://user-images.githubusercontent.com/4135686/37723311-64d3b6bc-2d2e-11e8-8bb9-ead83c5fa0cb.gif)

**Comment by ocornut** [comment]
I'm surprised anyone is still referring to this old gist from #306, but I suppose in the absence of an official example this is a decent reference! Will try to turn it into an imgui_demo.cpp thing at some point

The offset the grid was rendered at was wrong, fixed it now:

```
-        for (float x = fmodf(offset.x,GRID_SZ); x < canvas_sz.x; x += GRID_SZ)
+        for (float x = fmodf(scrolling.x, GRID_SZ); x < canvas_sz.x; x += GRID_SZ)
-        for (float y = fmodf(offset.y,GRID_SZ); y < canvas_sz.y; y += GRID_SZ)
+        for (float y = fmodf(scrolling.y, GRID_SZ); y < canvas_sz.y; y += GRID_SZ)
```

I have also fixed the sign of `scrolling` which was oddly inverted:
```
-    ImVec2 offset = ImGui::GetCursorScreenPos() - scrolling;
+    ImVec2 offset = ImGui::GetCursorScreenPos() + scrolling;
-        scrolling = scrolling - ImGui::GetIO().MouseDelta;
+        scrolling = scrolling + ImGui::GetIO().MouseDelta;
```
