### ISSUE TITLE
ImGui v1.60 (WIP) Popups only consider WindowBorder, not PopupBorder

### ISSUE THREAD

**Issue by Twinki14** [ocornut/imgui#1697]
Toggling PopupBorder in the Style Editor doesn't toggle proper popup borders, however if I toggle WindowBorder, it's adds a border to popups.

![2018-03-25_07-55-47](https://user-images.githubusercontent.com/5809130/37875240-0021807e-3002-11e8-823a-4c3ea4950b64.gif)

**Comment by ocornut** [comment]
You are right @Twinki14, this is now fixed.
PopupBorderSize should match the selection of ImGuiCol_PopupBg (in `GetWindowBgColorIdxFromFlags()`).

There's another subtle inconsistency where tooltips are still using `WindowRounding` and not `PopupRounding` however, I think it's desirable with the current look to preserve rounded tooltips by default but will probably bite us back at some point (I'm keeping a note of it when I will have a chance to refactor the styling more thoroughly).

Thanks!
