### ISSUE TITLE
Textures and skinning.

### ISSUE THREAD

**Issue by simongeilfus** [ocornut/imgui#17]
Hi Omar,

This is not really an issue, but more a suggestion about the library. I wanted to open the discussion with you before trying to implement something and send a PR. Let me know what you think!

I noticed the handy system to change colors per call using the PushStyleColor/PopStyleColor. That made me think about adding a PushTexCoords/PopTexCoords. If I'm correct every draw call that is not a text have texcoords that point to the upper-left corner of the font texture atlas, where a white pixel allow everything to get coloured correctly. Adding the pushpop methods I'm suggesting would allow to bypass this system and specify the texture coordinate of a custom skin. Allowing the library to render widgets with a much more customisable and complete style. At the same time it will continue to leverage the texture atlas and have only one texture binding for the whole batch of draw calls. The PushTexCoord would allow to specify the position of the skin in the atlas, and the PopTexCoord will at some point come back to the default notexture (0,0). 

To be able to properly texture the different rectangles, I guess that it means that we will have to double the number of vertices per rectangles (to properly scale the texture at the corners). This can probably be done in the fragment shader without changing the number of vertices. 

Except for this last bit, I think it would be a relatively easy and awesome feature to add to the library. Skinning is never totally required for a gui library but when well designed, it definitely push it to the next level.

So that was my random thoughts about your already really nice library!

Cheers,
Simon.

**Comment by ocornut** [comment]
I'm closing this for now. Feel free to reopen later if you feel it's something you want to work on, but right now this would definitively be very low in the priority list.

However I'm happy to hear about skinning improvements, such as improving the Style system (I was thinking of using something with less parameters and relying on variance in HSV space, so e.g. button can be defined by their hue and the "hovered"/"active" colors are variants in HSV space).
Not against supporting some form of gradient and anti-aliased shapes will come at some point.

**Comment by Xetrics** [comment]
Maybe add tinting at the very least for the time being?

**Comment by ocornut** [comment]
> Maybe add tinting at the very least for the time being?

You can already change the color of every element using PushStyleCol()

**Comment by GreatIndieDeveloper** [comment]
how is it going with this , any new news ?

**Comment by enquel** [comment]
Hi @ocornut 

I love Dear ImGUI, I love the entire paradigm, it makes visual apps feel truly dynamic again, and I think the skinning functionality would help popularize it further, to the mainstream. There is a huge demand for that.

I was thinking on the most painless way to expose skinning to the devs, and I don't think multiple UVs would do the job. Everything would get messy, convoluted, form-like. 

My view? There should be a system that is position independent, relying on the widget functionality. I thought the best way would be to expose interface for the users to develop their own customizations of rendering -> so we have the default "raw" UI, and let's say some pixel meta class that holds info on the pixel's ownership, relative position (am I inside button/on the edge of button/on the corner, etc.). The user would then be able to run a "second pass", let's call it ornamentation pass, over the bare UI.

The question remains whether the most atomic unit would be a pixel, or a position inside a rectangle being a "body" of a widget.

 Now, I don't know how performant that would be, and what the Dear ImGUI internals are, but this is a quick idea I got on the versatile system for skinning.

What do you think?
