### ISSUE TITLE
Button retains "hovered" style after mouse moved off window

### ISSUE THREAD

**Issue by KriyenKP** [ocornut/imgui#1702]
Created a new button to minimize the window. 
When used the window minimizes fine but when I bring it back up, the button stays in hovered state unless i move my mouse onto the window. I set a flag to identify its state and it says it's not hovered but is still highlighted?

**Comment by ocornut** [comment]
I don’t understand your question. Please provide the information requested by the issue template/guidelines. What does minimizing means? Are you minimizing an imgui window or an operating system window? Which backend do you use? please provide more context and a repro or pseudo code.

**Comment by KriyenKP** [comment]
Sorry sorry. 
C++
So What I'm doing is firing off      
`  if (ImGui::Button("-", ImVec2(20, 20)))
  {
    ShowWindow(m_windowHwnd, SW_MINIMIZE);
  }
`
This minimizes the application to the taskbar on windows. 
When I click on the minimized application in order to restore it and show it again, the button still has the style of a hovered button, but it is not in hovered state according to ImGui

**Comment by ocornut** [comment]
Which backend (`imgui_impl_xxx.cpp` files) and which version.

> the button still has the style of a hovered button, but it is not in hovered state according to ImGui

This sentence appears to say two contradicting things. How do you know "it is not in hovered state according to ImGui"? Does it keep happening even when you hover the mouse back into the window? What happens when you interact with the button?

**Comment by KriyenKP** [comment]
imgui_impl_dx9.cpp

So I've set the button to be blue when hovered.
When I hover and move away it's perfect.
When I hover and click the button to trigger the minimize, the button doesn't release the style for hover because it is now minimised and I guess the render process doesn't fire maybe??
When I restore the window, the button remains blue instead of changing back to grey (non hovered style). I put in a flag to check if "isanyitemhovered" and it returns false. Hence my saying it is no longer in a hovered state. I think the issue is that when it's minimising the hovered style is not released because it is losing focus before it can complete it and halting it maybe? 
![1](https://user-images.githubusercontent.com/6653717/37961914-de16a180-31b9-11e8-8682-29fdf8d8f3b7.JPG)
![2](https://user-images.githubusercontent.com/6653717/37961917-de48e21c-31b9-11e8-833c-95e0ccce967a.jpg)

**Comment by KriyenKP** [comment]
It might be related to this : https://github.com/rib/gputop/issues/172

**Comment by KriyenKP** [comment]
As it turns out...what I was doing isn't the trigger. 
If I hover a button and immediately take the mouse of the imgui window, the button stays hovered. How do I avoid this.
