### ISSUE TITLE
Exception thrown: read access violation.

### ISSUE THREAD

**Issue by scdmew** [ocornut/imgui#1705]
![be](https://user-images.githubusercontent.com/37879367/38046408-ea4c2888-32bf-11e8-9aae-faf927e2d96d.png)

hello, when i'm trying to compile the program everytime show's me this exception thrown, how can I fix it?

**Comment by ocornut** [comment]
@scdmew The line you pointed says "Forgot to call NewFrame()?"
In fact it looks like you haven't created an imgui context at all, if you call NewFrame() it would also assert and crash on `IM_ASSERT(GImGui != NULL && "No current context. Did you call ImGui::CreateContext() or ImGui::SetCurrentContext()?");`

**Comment by scdmew** [comment]
you are right but still can't compile.
![sdde](https://user-images.githubusercontent.com/37879367/38078422-8a7c2b38-333c-11e8-9e9d-d07d319da905.png)
![bwewe](https://user-images.githubusercontent.com/37879367/38078444-950bd792-333c-11e8-9d02-286893faeec5.png)

**Comment by ocornut** [comment]
I am sorry but all those questions are answered by the documentation, examples and comments.
Please read the messages and compare your code to the example code.
