### ISSUE TITLE
How to determine if a window is active or being selected? 

### ISSUE THREAD

**Issue by yeongasm** [ocornut/imgui#1707]
Hello Omar, hope you are having a great day. 

As above; how would I determine if a window is being selected or not? I'm trying to implement an ESC/ Ctrl+W kinda close an active window mechanism to my program. I've tried setting a pointer variable `activeWindow` to `p_open` when `ImGui::IsWindowFocused()` is true. 

The idea is that `activeWindow` would be stored inside a stack and if the window is being selected and I hit ESC/ Ctrl+W, the stack manager would change that value in the stack to `false` hence closing the window.

If anyone has a better solution than this, I would greatly appreciate it. Thank you for your time.

Edit: The problem with `ImGui::IsWindowFocused()` is that if I have 2 windows open and I alternately switch between them, `activeWindow` would just be assigned to the `p_open` of the last window opened.

**Comment by ocornut** [comment]
I think you just answered your question both in term of the function to call and how to store that information. Everytime a window is the focused one you can bump it back to the top of the stack.

**Comment by yeongasm** [comment]
Thanks for response Omar, 

I did a quick prototype and it seems that I must have done something wrong before this. `ImGui::IsWindowFocused()` does work as it was intended to do. 

It seems that I have wrongly set `activeWindow` to `p_open` when it should be `activeWindow = true`. Again, thank you for your time Omar.

**Comment by ocornut** [comment]
Good. Closing this then. 
(Btw when you refer to you own code “activeWindow = true” we have no idea what it may means)
