### ISSUE TITLE
A question about using dear imgui with vulkan

### ISSUE THREAD

**Issue by zuEE** [ocornut/imgui#1714]
I am a beginner in both imgui and Vulkan. I want to start build my program based on your vulkan example and [this tutorial](https://vulkan-tutorial.com/Introduction), but I meet some conflict about command buffers and frame render process. I wonder if I need to render my own things by adding my code after the frame_present function in main loop with new command pool and buffers?

**Comment by ocornut** [comment]
> I meet some conflict

That is a little too vague unfortunately. May I sugggest querying on a Vulkan related community?

You’ll want to do most things (~everything) before the Present call. 

Personally I don’t know much about Vulkan so it’ll be hard to me to tell you more, beside the question doesn’t have much to do with imgui itseld.

You may check the ‘viewport’ branch where the examples have been refactored a little and in particular the Vulkan code.

Good luck :)

**Comment by zuEE** [comment]
Thanks ^ ^
