### ISSUE TITLE
Slider with callback?

### ISSUE THREAD

**Issue by patrikhuber** [ocornut/imgui#1716]
Hi,

I've got a few sliders (`ImGui::SliderFloat`), and after moving them, there's a more-or-less expensive operation following (let's say 100 ms) that creates a mesh and this mesh should then be drawn.
So basically I only want to do this expensive operation if any slider value has changed, and not each time the `ImGui` functions get called in the loop (for reference, I'm using [libigl](https://github.com/libigl/libigl) and their `igl::opengl::glfw::Viewer`, which uses `ImGui` since recently).
There doesn't seem to be any way to hook a callback onto a slider? What are the options?

Thanks!

**Comment by ocornut** [comment]
All/most widgets return true when the value has just changed, and IsItemActive() will also return true when the slider is being held.

Also see #820 to build a construct out of IsItemActive() - will aim to move this construct to the public api.

**Comment by patrikhuber** [comment]
@ocornut Thank you very much for the quick reply! That was very helpful. Callbacks would be nice, but I guess this has to do. I'll play around with it a bit and that should help me get it to work. Thanks!
