### ISSUE TITLE
Memory leak caused by AddWindowSettings()

### ISSUE THREAD

**Issue by dhiahassen** [ocornut/imgui#1719]
`AddWindowSettings()` from `imgui.cpp` :

```
static ImGuiWindowSettings* AddWindowSettings(const char* name)
{
    ImGuiContext& g = *GImGui;
    g.SettingsWindows.push_back(ImGuiWindowSettings());
    ImGuiWindowSettings* settings = &g.SettingsWindows.back();
    settings->Name = ImStrdup(name);
    settings->Id = ImHash(name, 0);
    return settings;
}
```

Is causing memory leaks according to my memory profiler , ( home make ) , Stacktrace :

```
XXX/Imgui/imgui.cpp:773
XXX/Imgui/imgui.cpp:2580
XXX/Imgui/imgui.cpp:1007
XXX/Imgui/imgui.cpp:3694
XXX/Imgui/imgui.cpp:3556
XXX/Imgui/imgui.cpp:3761
XXX/Imgui/imgui.cpp:3707
XXX/Imgui/imgui.cpp:3302
XXX/Imgui/imgui_impl_sdl_gl3.cpp:398
XXX/UI/UI.cpp:189
```

` settings->Name` is indeed never freed in imgui source files , also is `Id` ...
imgui has many memory leaks , i think i gonna report many of them , i just want you to confirm this leak first

**Comment by ocornut** [comment]
Have you called ImGui::Shutdown() ?

**Comment by dhiahassen** [comment]
what a shame , shutdown() is there in the source code but the parent function is never getting calling due to imgui_dock version , ( the old version of imgui dock doesnt use imgui contexts ) updated now , and no single memory leak detected ! amazing , all memory allocations are hoocked (malloc/calloc..free/new/delete) , and imgui makes no leaks according to the profiler

**Comment by ocornut** [comment]
Good to hear, closing this!
