### ISSUE TITLE
Allow to replace C runtime library functions

### ISSUE THREAD

**Issue by mmozeiko** [ocornut/imgui#172]
Following commit in my branch of imgui fork allows to not use default C runtime library functions and instead provide custom ones: https://github.com/mmozeiko/imgui/commit/661eb02b250d10fa562a7a54980892d849f836ee
This follows up my two previous pulls requests: #168 #171

Idea is similar to STBTT_malloc, STBTT_memset and other STB functions in stb_truetype.h file - you provide values for IM_MALLOC, IM_MEMSET and other #defines and Imgui will use those instead of C default ones.

To do that you need to:
* enable IMGUI_DISABLE_TEST_WINDOWS define in imconfig.h
* enable IMGUI_DISABLE_STDLIB define in imconfig.h
* provide proper defines for IM_MALLOC and other maros in imconfig.h (by default they are user_xyz)
* probably enable IMGUI_INCLUDE_IMGUI_USER_H and provide imgui_user.h where you actually declare or define user_xyz functions.

Does this approach is OK? If yes, I can create pull request.

Enabling IMGUI_DISABLE_STDLIB makes Imgui to disable any functionality related to file I/O. This includes:
* saving and loading settings from ini file
* logging to tty/file
* loading ttf fonts from file

I think this is reasonable, because if you want to disable standard library functions you typically will have custom functionality for file I/O anyway.

There are couple functions which could be easily implemented in imgui.cpp to reduce amount of functions user needs to replace:
* isprint and isupper are very simple functions
* atoi is used only in one place for determining float precision
* sscanf is used only to parse 3 or 4 byte hex value, so instead of asking user to provide full-feature sscanf, simply convert hex value directly

This commit also has few minor changes to STB files. I've already created pull requests to nothings/stb repository with these changes.

**Comment by ocornut** [comment]
Mārtiņš, I am sorry I am not sure I want to merge that in. It's really getting in the way of readability and assumptions for what seems to be a really extreme use case. 

How about using a set of #define in imconfig.h with the std names that would apply to imgui.h and maybe a matching "footer" in a separate file that your project include after imgui.h set to undef them. That would have the same effect without having to modify any of the imgui code.

**Comment by paulsapps** [comment]
#define memset my_memset would work

**Comment by mmozeiko** [comment]
Ok, I understand readability argument. How about this change: https://github.com/mmozeiko/imgui/commit/5a944fd9ae98b43393f483f9f4994e7fe7ccca5e ?
This leaves all the stdlib functions intact and I will simply #define them to my functions. It's a bit fragile solution, because it messes up names in <string.h> and other includes, so it can break something. And for visual studio some functions need weird __declspec for declarations. But if you get them right, everything works and I'm ok with that.

**Comment by ocornut** [comment]
a) I have merged only a few bits so far (comments and replacing sprintf).

b) LoadFileFromMemory() or other disk I/O shouldn't be called if:
- io.IniFilename is set to NULL
- io.LogFilename is set to NULL and LogToFile isn't called (won't be because it's your application)
From his point if you can replace the other functions then you could replace fopen etc. with dummies? It will be fragile either way because I won't be able to consider the possibilities of all those features being disabled so it'll probably break occasionally, adding a new functions, etc. I'd really like to avoid those scattered ifdef. In fact I think it'll break less without the ifdef.

c) All the pre-stb define can be defined by yourself in imconfig.h
The stuff inside stb_ I'm not going to merge until nothings merge them but they shouldn't be too hard to maintain or keep in a patch, it's not code that change. 

So if you can allow ImLoadFileToMemory/LoadSettings/SaveSettings to compile and link with your dummies it should all be ok?

I've seen all sort of low-level hackery and obsessions but it is the first time I see someone insisting on not linking with any of those posix functions :) Sorry to be a little resisting but I need to measure the impact on readability maintenance (which goes on forever) and already swamped in things to do with imgui.

**Comment by mmozeiko** [comment]
Yes, calling LoadFileFromMemory is not a problem. Problem is that I am required to provide fopen/... etc functions. I don't want that :) That includes saving/loading ini settings.

Well I guess I'll maintain my own changes for this one :) That's OK, I understand my use case is not a very typical one. Feel free to close this issue.

**Comment by ocornut** [comment]
I mean you can provide empty fopen() and assert in it - that's actually simpler than maintaining the ifdef.
If you set io.IniFilename to NULL both LoadSettings()/SaveSettings() will early out.
Sorry for that :(

**Comment by mmozeiko** [comment]
Heh, somehow I missed part where setting IniFilename to NULL will help me here. Thanks for this tip!

**Comment by ocornut** [comment]
And LogFilename == NULL also (I just fixed it an hour ago).

But if you call LogToFile() with an explicit filename it'll still attempt to open it, but ImGui won't call that for you.

**Comment by floooh** [comment]
Hi, apologies for bumping this old thread, but I guess it's better then starting a new one :) I'd also prefer a way to compile imgui without calling the fopen/fclose functions for porting to web platforms (emscripten and PNaCl) which don't support synchronous file IO (thus I'll have to use the '...FromMemory' functions for getting data into imgui anyway). A simple config-define IMGUI_DISABLE_STDIO would be sufficient for me, which just removes the functions calling into the stdio functions from the imgui API.

The main problem seems to be the LoadSettings() function which is called from NewFrame() which then would prevent the compiler's dead-code elimination from removing imgui functions which into fopen, etc... which in turn would cause to pull in emscripten's stdio wrapper code.

I guess I'll play around with it a bit in a fork and see whether removing the IO calls makes a noticeable difference in client size on emscripten and PNaCl and then report back :)

**Comment by floooh** [comment]
Removing the fopen/fread/fclose calls saves about 20kByte uncompressed from an emscripten client. Probably not worth the hassle so I'm fine with closing this ticket again :)

**Comment by ocornut** [comment]
Cool, closing again then.
For others, the emscripten demo is at http://floooh.github.io/oryol/ImGuiDemo.html

**Comment by wizzard0** [comment]
Link rot: http://floooh.github.io/oryol-samples/asmjs/ImGuiDemo.html

**Comment by floooh** [comment]
I have moved the demos around, sorry about that :)
