### ISSUE TITLE
ImGui::InputTextMultiline Backspace Key

### ISSUE THREAD

**Issue by GGWPGG** [ocornut/imgui#1723]
Hi,
I have a little problem.
I ame using ImGui::InputTextMultiline and that work good and all, but i have a littel bug. Whan holding in keys it normaly does like this aaaaaaaaaa, and that is what i want.. But it doesent do the same for backspace. With backspace it delete one character and thats it. Tryd it in the demo version and that worked as i wanted.

So it probly has something to do with that i ame using WNDPROC if i arent wrong. But i dont know whats cosing it to not keep deleting whan holding inside backspace.

**Comment by ocornut** [comment]
Keys (Backspace) and Characters ('a') are passed through different mechanism. With the default binding setup the repeat rate for Characters is handled on the backend side, while Keys repeat is handled on imgui side, provided `io.DeltaTime` is filled correctly (we need timing information).

Closing as you are not providing the bare minimum amount of information requested by the issue template. Please reopen when you have more details.
https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md
