### ISSUE TITLE
Remove spacing after slider?

### ISSUE THREAD

**Issue by mew351** [ocornut/imgui#1728]
So basically I'm trying to make a very compact menu for my program, I am having an issue though where the slider has a big space after (relatively big due to the small menu).

The red arrows are where the spaces are
It's super close to the item before it but there's a space after.

I've looked in the documentation and haven't found anything about it, here's the photo

![image](https://user-images.githubusercontent.com/12377381/38453230-003d0150-3a07-11e8-808d-9776a0981654.png)

Thanks!

**Comment by ocornut** [comment]
Sorry but #1586 
Also that is a modified slider code anyway, it's not vanilla imgui code.
