### ISSUE TITLE
ItemSize issue with ScrollBars

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#1730]
Hello,

i have a problem with my app, not sure if its an imgui bug.

i display quad texture on imgui, and i calc the width and height of my texture according to ImGui::GetContentRegionAvailWidth();

So when i resize the height of the app precisely i get a vibrating recalc.
showing and hiding the scrollbar.

i tried to get the max region including scrollbar. but it not work, 
but maybe i doing something wrong ?

I tried with : 
ImGui::GetContentRegionAvail()
ImGui::GetContentRegionMax()
ImGui::GetWindowContentRegionMax()

maybe its the height of the scrollbar taking more height that without scrollbar ?

i use ImGui::Image

how i can correct this behaviour ?

![2018-04-07_16-46-14](https://user-images.githubusercontent.com/1434736/38456321-cd3090a6-3a83-11e8-9d54-61be91aadef5.gif)

**Comment by ocornut** [comment]
The problem here is that you have widgets whose height depend on the width, which creates a feedback loop with the scrollbar. It’s a little tricky to solve properly.. but the easy workaround is to always enable the vertical scrollbar.

**Comment by aiekick** [comment]
ok i understand so its not an issue. you can delete this post so :) thanks

**Comment by aiekick** [comment]
Is there a way to know if a scrollbar is shown on the current window ?

**Comment by aiekick** [comment]
ok i found the falg ImGui::GetCurrentWindow()->ScrollbarY

**Comment by ocornut** [comment]
Not sure what you are trying to do here. There’s a window flag to always enable the scrollbar.
