### ISSUE TITLE
Memory ownership of AddFontFromMemoryTTF?

### ISSUE THREAD

**Issue by rSixDroid** [ocornut/imgui#1734]
I noticed I was getting a SIGTRAP upon exiting my app, the culprit: a default font _embedded_ within the app, loaded with **AddFontFromMemoryTTF()**. Stack trace suggests IMGUI attempting to free the memory the font occupies. This is where I realize I erroneously made an assumption about this call, but looking at it now, it makes sense enough. A workaround is to allocate some mem and duplicate the already embedded font there and pass _that_ off to AddFontFromMemoryTTF, which works fine and exits cleanly. This of course is a little wasteful, however.

For those of us who still monkey with incbin/objcopy/bin2s etc, would it be out of the question to have an option to load a font for which the source does not need to be freed? Apologies in advance if I've missed something in the API...

Cheers

**Comment by ocornut** [comment]
There is a flag in the ImFontConfig structure to do exactly that.

(This api is a little awkward but it is tricky to change it without changing people code. Will change it at some point tho.)

**Comment by ocornut** [comment]
To clarify, you need to do:

```
ImFontConfig cfg;
cfg.FontDataOwnedByAtlas = false;
fonts->AddFontFromMemoryTTF(data, data_size, size, &cfg, ...);
```

**Comment by rSixDroid** [comment]
That's the ticket. Thank you, Omar.

I should have paid attention to the font config struct, I somehow completely missed it...
