### ISSUE TITLE
Android demo (was: Not responsive)

### ISSUE THREAD

**Issue by KaungZawHtet** [ocornut/imgui#1735]
![30516598_893009807548601_1442643999641829376_o](https://user-images.githubusercontent.com/15225530/38498261-cfce2dc6-3c29-11e8-92f7-3fb27484ebe7.png)

After opening the app from the link https://play.google.com/store/apps/details?id=org.imgui.android&hl=en , I found the widgets are too small but they work.

Hope upgrading better compatibility with mobile devices and I am waiting for more mobile friendly widgets.

**Comment by ocornut** [comment]
This google store link is a very old version demo created by someone else and it is not maintained. Please ask the creator of this app about it. 

dear imgui is not designed for mobile devices.

**Comment by KaungZawHtet** [comment]
The world is full of mobile devices driven by android or ios. Thinking for the mobile development can make this project bigger with larger community. I hope you will re-consider your roadmap to extend it. Anyway, thx for the reply.

**Comment by ocornut** [comment]
This project doesn't _need_ to be bigger or have a larger community.  I am only a single developer. It's a UI system with very unusual and specific trade offs that are great for a certain type of users (game developers) but not viable for everyone.

It's already usable on mobiles, many people use it this way. But it was designed and optimized for precise inputs (mouse) and thus won't be ideal for high density UI on a touch screen.

**Comment by ocornut** [comment]
Note that an Android backend and demo has been merged through #3446
