### ISSUE TITLE
Demo.cpp

### ISSUE THREAD

**Issue by wilburforce666** [ocornut/imgui#1736]
Uhm slight issue. When I add the imguidemo.cpp I get this error when I try to compile
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'bool ImGui::ColorButton(const ImVec4 &,bool,bool)': cannot convert argument 1 from 'const char [10]' to 'const ImVec4

**Comment by ocornut** [comment]
Your imgui_demo.cpp file doesn't match imgui.h imgui.cpp etc.
You shouldn't have to "add the imguidemo.cpp" it is part of imgui. If you have removed it from an old version and you want to stay in the old version, then find the matching imgui_demo.cpp for that version from github tagged versions.

(The prototype of `ColorButton()` was changed on 2017-08-08 (v1.51) as noted in the API BREAKING CHANGES section.)

**Comment by wilburforce666** [comment]
I am using 1.51 for all of the Imgui cpp files
