### ISSUE TITLE
Always 'on' checkbox 

### ISSUE THREAD

**Issue by v71** [ocornut/imgui#1743]
Hello, thanks for your hard work on imgui, there is a problam i am trying to overcome, about an 'always on' checkbox, to show installed features , how can achieve this ?
thans and sorry for the stupid question but i have come back to work on imgui after trying different libs...

**Comment by ocornut** [comment]
The checkbox state is up to your application, your own the bool.

If you do:
```
bool v = true;
ImGui::Checkbox("checkbox", &v);
```
It'll always be on...

Note that clicking on it will uncheck it for a frame. It's possibly not a problem at all for you.
To disable that you'd need something like `ImGui::PushItemFlag(ImGuiItemFlags_Disabled, true);` (see #211) which is currently a private api from imgui_internal.h, or draw an invisible button _before_ and behind the checkbox.

**Comment by v71** [comment]
Tha worked perfectly, thanks, i think that somehow,someone with a big sense of altruism should write a series of tutorials to avoid the same questions over and over again.

**Comment by ocornut** [comment]
Good, closing this!
Well, I'm not sure there are already some articles (linked in wiki) but the more the merrier!
