### ISSUE TITLE
++ if else

### ISSUE THREAD

**Issue by Tiokun** [ocornut/imgui#1746]
You may use the Issue Tracker to ask for help and submit bug reports, feature requests or suggestions. 
PLEASE CAREFULLY READ THIS DOCUMENT before doing so:
[CONTRIBUTING.md](https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md).

You can include code snippets using `Begin()` for short in-line snippets, or:
```cpp
ImGui::Begin("Hello");
ImGui::ThisIsMoreCode();
```
For multiline snippets.

(Clear this form before submitting your issue. Please read the CONTRIBUTING.md file!)

**Comment by ocornut** [comment]
Sorry but #1586. You aren't even asking anything yet managed to spam :(

**Comment by MyNameIsKodak** [comment]
> You may use the Issue Tracker to ask for help and submit bug reports, feature requests or suggestions. PLEASE CAREFULLY READ THIS DOCUMENT before doing so: [CONTRIBUTING.md](https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md).
> 
> You can include code snippets using `Begin()` for short in-line snippets, or:
> 
> ```c++
> ImGui::Begin("Hello");
> ImGui::ThisIsMoreCode();
> ```
> 
> For multiline snippets.
> 
> (Clear this form before submitting your issue. Please read the CONTRIBUTING.md file!)

any fix yet ? i haveing the same err
