### ISSUE TITLE
Inputtext losing focus when using multiple windows

### ISSUE THREAD

**Issue by bs3n** [ocornut/imgui#1750]
Hey, I'm just trying to learn using imgui in a LUA/Love2D setup. I'm pretty happy with what I've achieved so far (made some development tools for our future game) and I managed to solve any issue I've stumbled upon so far.

Sadly, now I have no idea how to solve my issue. I've got two windows, where the first one selects which one is displayed as the second window. All possible second windows have multiple inputtext widgets.
![q](https://user-images.githubusercontent.com/12234126/38770953-d6a84948-401a-11e8-8c23-31181e8abfbe.png)
Whenever I'm typing something into any inputtext widged, it loses focus after one or two characters.
How can I change that behavior? I know I can achieve this by using only one window, but I don't want the upper part to be scrollable.

**Comment by bs3n** [comment]
I'm using imgui 1.53

I'll try to cut the code down to the crucial parts:

``
  imgui.SetNextWindowPos(0,0)
  imgui.SetNextWindowSize(love.graphics.getWidth(),selectHeight)
  imgui.Begin("##Select",nil,{"ImGuiWindowFlags_NoTitleBar", "ImGuiWindowFlags_NoResize", "ImGuiWindowFlags_NoMove", "ImGuiWindowFlags_NoCollapse","ImGuiWindowFlags_NoClose", "ImGuiWindowFlags_MenuBar"})
  if imgui.BeginMenuBar() then
    if imgui.BeginMenu("File") then
      if imgui.MenuItem("Reload") then love.load() end
      if imgui.MenuItem("Save") then saveFile() end
      if imgui.MenuItem("Quit") then love.event.quit() end
      imgui.EndMenu()
    end
    imgui.EndMenuBar()
  end
  modeSelect = imgui.RadioButton("Master",modeSelect,0)
  imgui.SameLine()
  modeSelect = imgui.RadioButton("Language files",modeSelect,1)
  imgui.SameLine()
  modeSelect = imgui.RadioButton("Search",modeSelect,2)
  imgui.Separator()
-- change window 1 depending on selected RadioButton
  if modeSelect == 0 then if imgui.Button("Add string") then addString() end end
  if modeSelect == 1 then selectLang() end
  if modeSelect == 2 then search = imgui.InputText("##search", "", 1000) end
  imgui.Separator()
  imgui.End()
  imgui.SetNextWindowPos(0,selectHeight)
  imgui.SetNextWindowSize(love.graphics.getWidth(),love.graphics.getHeight() - selectHeight)
-- call window 2 depending on selected RadioButton
  if modeSelect == 0 then masterWindow() end
  if modeSelect == 1 then fileWindow() end
  if modeSelect == 2 then searchWindow() end
  imgui.Render()
``

This is an example of the second window:

``
  imgui.Begin("##LangFiles",nil,{"ImGuiWindowFlags_NoTitleBar", "ImGuiWindowFlags_NoResize", "ImGuiWindowFlags_NoMove", "ImGuiWindowFlags_NoCollapse","ImGuiWindowFlags_NoClose", "ImGuiWindowFlags_NoMenuBar", "ImGuiWindowFlags_AlwaysVerticalScrollbar"})
  imgui.PushItemWidth(30)
  imgui.LabelText("##ID","ID")
  imgui.SameLine()
  imgui.PushItemWidth(love.graphics.getWidth() - 60)
  imgui.LabelText("##String","String")
  for i = 1, #LangFileString[langFiles[langSelect]] do
    imgui.PushItemWidth(30)
    imgui.LabelText("##" .. LangFileID[langFiles[langSelect]][i],LangFileID[langFiles[langSelect]][i])
    imgui.SameLine()
    imgui.PushItemWidth(love.graphics.getWidth() - 102)
    LangFileString[langFiles[langSelect]][i] = imgui.InputText("##" .. LangFileString[langFiles[langSelect]][i], LangFileString[langFiles[langSelect]][i], stringLength)
  end
  imgui.End()
``

**Comment by ocornut** [comment]
Try to narrow down a repro without anything else running in your app.

**Comment by bs3n** [comment]
There isn't anything else running at the moment, it's just creating those windows.

imgui.Begin()
...create menu and widgets
imgui.End()

imgui.Begin()
...create inputtext widgets
imgui.End()

imgui.Render()

Whenever I click on a inputtext widget, it gets the focus, but as soon as I start typing, the focus is lost. This isn't happening in the first window. If theres an inputtext widget, I'm able to type as much as I want.

**Comment by bs3n** [comment]
Oh god, how embarrasing. I named the label including their own string which of course changes as soon as I'm typing... I guess I need to take a break :smile: 
Sorry for wasting your time :grinning:

**Comment by ocornut** [comment]
No problem :) note that you may use the ### string operator to use a variable label with a fixed identifier, read the FAQ about it!
