### ISSUE TITLE
Could input widget like sliders have a user action to set it to a known default Value ?

### ISSUE THREAD

**Issue by turmansky** [ocornut/imgui#1751]
For Slider and input controls with large ranges it would be really useful if there was a user action say D+Click or right double click that would set the control to a specified default. The default  value would be specified at control creation as an additional parameter along with some identifier for the type of user action.
We have used this for many years in the past with custom Win32 controls to save our operators when they get into bad states with controls variables and it was one of the few items that they were unanimous about a feature we added.
Wondering if that would be useful and appropriate here. 
We can always build that functionality with imGui as a layer above it so its not a big issue but just curious if anyone else has raised this feature.
Love imGUI after 2 months of use.

**Comment by ocornut** [comment]
Hello @turmansky,

Double click is already used to input text in Slider and Drag controls.

> We can always build that functionality with imGui as a layer above it 

I think this is the right solution. You can create your own function with your own signature, which you can keep in the `ImGui::` namespace if you wish (you can extend namespaces from your own code). Your function would call e.g. SliderFloat() and and add e.g. a context menu or checking another button to set the value. The context menu will be the simplest and most flexible solution, if you don't mind the 2 steps action (right-click to open the menu, then select an option).

Something like:
```
bool SliderFloatDefault(const char* label, float* v, float v_min, float v_max, float v_default, const char* display_format = "%.3f")
{
    bool ret = ImGui::SliderFloat(label, v, v_min, v_max, display_format);
    if (ImGui::BeginPopupContextItem(label))
    {
        char buf[64];
        sprintf(buf, "Reset to %f", v_default);
        if (ImGui::MenuItem(buf))
            *v = v_default;
        ImGui::MenuItem("Close");
        ImGui::EndPopup();
    }
    return ret;
}
```
![image](https://user-images.githubusercontent.com/8225057/38777177-f8163e08-40a3-11e8-8354-664745f8a567.png)

It's tricky to make it a default feature, we are already a little bottleneck by the number of API and parameters, those things are better off added by the user.

**Comment by turmansky** [comment]
Agree. 
Thank you !

**Comment by dromer** [comment]
Hmm, I also really want to add such double-click behavior to the sliders.
In many UI contexts this is a UX that is common place and I'd like to replicate that for sliders as well.

Does anyone have an idea how to accomplish this, other than re-implementing an entire slider object?
