### ISSUE TITLE
The possibility of partnership with the Avalonia project

### ISSUE THREAD

**Issue by insinfo** [ocornut/imgui#1752]
It would be great for the community if a partnership happens, as Avalonia lacks an Accelerated Hardware API (OpenGL).
Mainly for OpenGL targets like Android, IOS, MacOs, Linux, WASM (WebAssembly)

https://github.com/AvaloniaUI/Avalonia/issues/1387#issuecomment-381389726

**Comment by ocornut** [comment]
Sorry @insinfo, but it looks like you've been spamming multiple project and your suggestion is vague and ill defined. Anyone is free to use dear imgui, so if Avalonia wants to use it they can.
