### ISSUE TITLE
Frame Border Size Inconsistent When Dynamically Adjusting Location of Widgets

### ISSUE THREAD

**Issue by clmiti** [ocornut/imgui#1753]
When I attempted adjusting the location of checkboxes dynamically to keep them in the center of the application regardless of the window size, using something like `float LineDist = ImGui::GetWindowWidth() * 0.50f;` I observed the frame border size appearing to increase to 2px at times on widgets in question. Not a big deal but most certainly noticeable if you look close.

**Comment by ocornut** [comment]
@clmiti I think I understand your issues - many of the ImDrawList primitives requires points to be either aligned on the pixel perfectly. ImGui generally maintain pixel aligned positions between calls. If you used ImDrawList yourself you need to align position accordingly else anti-aliased shapes and borders may be unreliable in term of how many pixels they cover.

If you have more questions please provide a screenshot and some code to understand your use case better.
