### ISSUE TITLE
Quick and Easy "Ready To Fill" VS Solution For DearImGUI?

### ISSUE THREAD

**Issue by josephguerrero2018** [ocornut/imgui#1756]
I'm Currently creating an helper application for GURPS with your incredible software. Here's a screenshot of my work so far. 
This solution was kinda cheesed into existence by Dumping my own custom headers into one of the imgui demos. It was brute force but It worked nicely enough for visual testing and direct comparison of formatting and other tools in real time. 
![tons of nested info](https://user-images.githubusercontent.com/22943792/38974997-fd99e054-4360-11e8-80d5-8171aabee477.JPG)

Using the Demo Interface as an example, I have made some significant progress. For the sake of condensing my code into something more manageable, I really badly need a "ready to fill" Visual Studio solution that  just has an empty body. Like the Demo, but  all of its "meat" carefully trimmed out of it, save for the Body of the page, ready to roll.

I have been doing some trimming myself, but I realize that my needs might be similar to others that would want to get started on their own programs, so I'm just dropping in with a little request for everyone.

**Comment by ocornut** [comment]
Joseph,
I don’t understand your request. The examples/ application are _exactly_ that. They are nearly empty demo application. Just copy one main.cpp, comment out the dozen lines of demo imgui calls, and add the stuff you need. 

You don’t need and should not edit imgui_demo.cpp or edit imgui.h, just add the stuff you need in your own file.

**Comment by josephguerrero2018** [comment]
I'm sorry about that. I'll continue my work on porting my application elsewhere.

**Comment by ocornut** [comment]
Cool :) closing now!
