### ISSUE TITLE
seeing 1px border on windows which are supposed to be full width

### ISSUE THREAD

**Issue by xaxxon** [ocornut/imgui#1758]
**Version/Branch of Dear ImGui:**

latest release version

**Back-end/Renderer/OS:**

opengl 3.3 on mac

**My Issue/Question:** I had to update my code since it had been a while since i'd updated, but I'm getting a 1 pixel border where I'm expecting the window to be full width.   Previously the window had been black all the way to the edge with no border.   Any idea what else I need to update

```
ImGui::SetNextWindowPos(ImVec2(0, window_dimensions.height - 40));
ImGui::SetNextWindowSize(ImVec2(window_dimensions.width, 40));


int Gui::FULL_SCREEN_FLAGS = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove |
                             ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse |ImGuiWindowFlags_NoCollapse |
                             ImGuiWindowFlags_NoSavedSettings;

```

![image](https://user-images.githubusercontent.com/143986/39021832-7cf6ce26-43e7-11e8-8d32-2e67e8fc7f22.png)

**Comment by ocornut** [comment]
Hello Zac, window borders have been enabled in the default style recently.

You may override it:
```
ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);`
```
or
```
ImGuiStyle& style = ImGui::GetStyle();
style.WindowBorderSize = 0.0f;
```

(Border don't affect total window size)

You are not explaining why this is a problem to you but I guess you are creating exact-sized windows to fit an image inside them? If that's the case you may want to override the border for this window.

(I think imgui needs a function to window size <> client area size given ImGuiWindowFlags + style, but I'm not 100% sure that difference will always be limited to those two inputs?)

**Comment by xaxxon** [comment]
That was it, thank you.   I do like the new theme and in general what you've done.   It had been around 1-1.5 years since I'd updated I think and it wasn't too painful at all.

**Comment by ocornut** [comment]
In the past there was a ShowBorder window flag but it was problematic (inconsistent with other style values, inheritance was ambiguous, borders applied to both windows and widgets). Using `ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);` here you can control that border more precisely.

**Comment by ellectroid** [comment]
> Hello Zac, window borders have been enabled in the default style recently.
> 
> You may override it:
> 
> ```
> ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);`
> ```
> 
> or
> 
> ```
> ImGuiStyle& style = ImGui::GetStyle();
> style.WindowBorderSize = 0.0f;
> ```
> 
> (Border don't affect total window size)
> 
> You are not explaining why this is a problem to you but I guess you are creating exact-sized windows to fit an image inside them? If that's the case you may want to override the border for this window.
> 
> (I think imgui needs a function to window size <> client area size given ImGuiWindowFlags + style, but I'm not 100% sure that difference will always be limited to those two inputs?)

Is this still relevant? I have a black border at the side (and when an element is placed at x=0, the border draws on top of the element). Neither of the proposed solutions have any effect.

**Comment by ocornut** [comment]
> Is this still relevant? I have a black border at the side (and when an element is placed at x=0, the border draws on top of the element). Neither of the proposed solutions has any effect.
> Also tried setting ImGuiStyleVar_FrameBorderSize. No use, the black vertical line is still there.

Hard to tell what is your issue without seeing the code, but it seems like you have a border displayed.

**Comment by ellectroid** [comment]
> Hard to tell what is your issue without seeing the code, but it seems like you have a border displayed.

It happens by default with literally any window, Even empty. Also, it happens in any project and on any machine (on all 3 of my computers that I happened to develop on). I create window at (0,0) and make it full frame size, without borders or anything.

...
ImGuiWindowFlags window_flags= ImGuiWindowFlags_NoTitleBar
			| ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove
			| ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_AlwaysAutoResize
			| ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoBackground
			| ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse;
...
ImGui::SetNextWindowSize(main_viewport_size, 0);
ImGui::SetNextWindowPos( { 0, 0 }, 0);
ImGui::Begin("windows_name", nullptr, window_flags);
...

I'm using d3d9, using the example file as a starting point (from within which I call other functions in other files that actually draw stuff).

**Comment by ocornut** [comment]
You are not specifying imgui version, but if you are using a non-zero value for WindowPadding, until [1.90.6](https://github.com/ocornut/imgui/releases/tag/v1.90.6) it applied a ClipRect.
(Also consider using GetMainViewport()->Pos and Size instead of hardcoded {0,0} as that won't work on some setups with multi-viewports.)

**Comment by ellectroid** [comment]
I'm using 
#define IMGUI_VERSION       "1.90.4 WIP"
#define IMGUI_VERSION_NUM   19032

I didn't set any paddings to anything (on account of not knowing how). Thanks for the advice about the viewport and (0,0). I had no idea more than one viewport was a thing.  

How can I remove that ClipRect?

**Comment by ocornut** [comment]
WindowPadding doesn't default to 0. 
You can surround your window with `PushStyleVar(ImGuiStyleVar_WindowPadding, { 0, 0 })` .. `PopStyleVar();`.

**Comment by ellectroid** [comment]
That did it! PushStyleVar(ImGuiStyleVar_WindowPadding, { 0, 0 }) removed all border, it left 1 pixel border. So I added ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f); from the answer above, and now I have full frame to draw on. Just what I needed. Thanks!

```
ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, { 0, 0 });
ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
ImGui::Begin(...);
...
ImGui::End();
ImGui::PopStyleVar(2);
```

**Comment by ocornut** [comment]
Please note that since 1.90.6, WindowPadding won't affect the cliprect, only the line start X position.
I am assuming that your widgets were manually positioned or using counter indentation.

**Comment by ellectroid** [comment]
To be honest, I'm not sure I understand what it means. Does it mean that from 1.90.6 onwards I will have the black rectangle around the window again?

**Comment by ocornut** [comment]
It means that from 1.90.6 you won't have the black rectangle even without modifying WindowPadding.
