### ISSUE TITLE
First time with imgui

### ISSUE THREAD

**Issue by lostspirit1** [ocornut/imgui#1766]
I created a project with imgui archives
but i got this error :
Severity Code Description Project File Line Suppression State
Error LNK2019 unresolved external symbol _WinMain@16 referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@yahxz) Img C:\Users\Spirit\Pictures\imgui-master\MSVCRTD.lib(exe_winmain.obj) 1

please help .
[imguispirit.zip](https://github.com/ocornut/imgui/files/1936465/imguispirit.zip)

**Comment by lostspirit1** [comment]
i use visual studio 2017, c++.

**Comment by ocornut** [comment]
Hello @lostspirit1, you already have asked the exact same question in #1762 and I told you the question is actually unrelated to dear imgui. This is a general C++ development question and if you look it up on google you'll find that a C++ program needs a main() or WinMain() function which your project doesn't provide. We can't be giving general non-imgui related programming support here, please find a more suitable development forum.
