### ISSUE TITLE
Mismatching data structures (was: Changing IO values takes no effect.)

### ISSUE THREAD

**Issue by Rinnegatamante** [ocornut/imgui#1769]
**Version/Branch of Dear ImGui:** 
https://github.com/Rinnegatamante/imgui-vita
which is based on https://github.com/ocornut/imgui/tree/bcac02809f46e9bd4ba190f87481f5896dbb45a3

**My Issue/Question:** 
I'm trying to implement ImGui in a port for PSVITA of Wolfenstein 3D (based on Wolf4SDL) i'm currently working on however it seems whenever i change IO values returned by ImGui::GetIO they don't take place. The same issue seems to not affect the same project launcher.
Relative launcher where everything works fine: https://github.com/Rinnegatamante/vitaWolfen/blob/master/launcher/source/main.cpp

Port where the IO changes seems to not take effect: https://github.com/Rinnegatamante/vitaWolfen/blob/sdl/source/sys_psp2.cpp

 ImGui_ImplVitaGL_Init(); will set MouseDrawCursor to true however the subsequent call that should set it to false seems to not take effect and, in game, mouse cursor is always drawn.
The FPS counter too always shows FPS: 0.0 even if in the launcher it corretly works and shows FPS: 59.9.
ImGui_callback is called everytime the framebuffer is drawn via SDL thanks to SDL_SetVideoCallback.

I've also copy-pasted from the example code the checkbox that's supposed to change DrawMouseCursor property. Here's the result:
https://rinnegatamante.it/drawcursor1.jpg
https://rinnegatamante.it/drawcursor2.jpg

**Comment by Rinnegatamante** [comment]
ImGui seems to not detect my changes to IO reference, like if i have a local reference not linked anymore to what imgui.cpp sees.

**Comment by ocornut** [comment]
If it did then none of your mouse/touch inputs would work.
Most probably your code that keeps overwriting io.MouseDrawCursor based on touch information is not working as expected.

**Comment by Rinnegatamante** [comment]
As i've said, it affects also io.deltaTime that's defined in my implementation for NewFrame and never touched elsewhere. Even stripping away touch code by the way makes the cursor being rendered even if DrawMouseCursor should be set to false.

**Comment by ocornut** [comment]
Check what's the value of &ImGui::GetIO() from both side of the fence. Perhaps if you have a DLL-ish/module system in place it is possible that your globals are not shared across the boundaries of those modules, in which case you'd want to use GetCurrentContext() / SetCurrentContext() to modify the global in each module.

**Comment by ocornut** [comment]
Found the problem, user code was changing structure packing inconsistently across compilation units, leading to mismatching structure layout.
https://github.com/Rinnegatamante/vitaWolfen/blob/75a9c6f3414d57a632d0796c1df1aa57094b8ab7/source/wl_def.h#L27

Similar mistake as #1695, in the future will consider using some function+macro combo magic to compare client-side structure size with imgui.cpp side structure size and asserts/error earlier. 

Closing this.
