### ISSUE TITLE
Plotting data

### ISSUE THREAD

**Issue by kenkit** [ocornut/imgui#1772]
Hi, 
I'm using IMGUI as the default user interface for all my apps since it's easy to use.  However I've noticed that there is little information/documentation on the api.
Ok, my current problem is that I have a histogram which is an arrary of floats which is updated every second incrementally, if the value reaches max it resets to 0. The problem is the graph iteself begins repeating while ovewriting the existing values instead of moving the whole thing to one side.
Here is part of my code

```
  if (diff.total_milliseconds() >= 1000) {
                upload_log[current_ul_log] = graph_rt;//--this is the value I'm plotting
                last_ulspeed = graph_rt;
                current_ul_log++;
            }

 ImGui::PlotHistogram("Log", upload_log, IM_ARRAYSIZE(upload_log),
                current_log, std::string("speed " + std::to_string(upload_speed) + std::string(rate[current_rate].symbol)).c_str(), 0.0f, max_ul_value, ImVec2(0, 80));
```

So my question is do I have to iterate over the whole array just to make it look like it's moving ?
I didn't see this being done in the examples, I thought of using a vector but I don't know how to do it.
Any help will be greatly appreciated.

**Comment by ocornut** [comment]
The `values_offset` parameter serves this purpose.

**Comment by kenkit** [comment]
Oooh, I see my mistake, I have two graphs so I was using the wrong value_offset which should be current_ul_log thanks for your assistance.
Btw is it possible to render imgui to a texture ? , like say I have the window rendered on one face of a cube ?

**Comment by ocornut** [comment]
Good, closing this.

> Btw is it possible to render imgui to a texture ? , like say I have the window rendered on one face of a cube?

Just as anything you render with OpenGL or DirectX can be rendered to a texture, yes. The question doesn't really have anything to do with imgui it's more a graphics API question at this point.
