### ISSUE TITLE
Consider tagging issues that lend themselves to unit tests

### ISSUE THREAD

**Issue by xaxxon** [ocornut/imgui#1777]
This may be out of date but I remember seeing that formal unit testing may be coming down the line and if that’s he case i suggest when a new êissue comes in that lends itself to a unit test that you tag it for finding some actual issues to test against for regression.  The real world issues are often the ones that are hard to consider when coming up with tests just out of your head.  

You know.  Things like columns with auto size and not storing settings :-)

No need to reply.  Feel free to just close.

**Comment by ocornut** [comment]
My plan was to import all issues into a spreadsheet (using the github api) and every one of them will be considered for a unit test. Perhaps 50% of them would be eligible for one and I can classify them to first focus on the subtle and weirder ones.

Once we get a bare minimum baseline of test I want to quick focus on hard issues, edge cases, one frame glitches, things related to flickering sizes, etc.

**Comment by ocornut** [comment]
Closing as suggested. Thanks! My daily work is very frequently slowed down by fighting hard-to-notice regressions so I'm also well obsessed with testing for what bite us once rather than only imaginary tests.
