### ISSUE TITLE
help with icon + text

### ISSUE THREAD

**Issue by lostspirit1** [ocornut/imgui#1781]
i make this : 
http://prntscr.com/jauv01
code :  ImGui::SameLine(400);
				ImGui::Button("b", ImVec2(30.f, 30.f));
				g_pGui->IconFont();
				ImGui::SameLine(0.0, 0.f);
				ImGui::Button("Legit", ImVec2(40.f, 35.f));

but i want one button with icon + text

is possible?

**Comment by ocornut** [comment]
Merge the fonts and use a single string with icon + text, as instructed by the font readme.

**Comment by lostspirit1** [comment]
@ocornut  about add one background image to one beginchild what i need make?

**Comment by ocornut** [comment]
Sorry but #1586
