### ISSUE TITLE
Resize Issue!

### ISSUE THREAD

**Issue by radovicz** [ocornut/imgui#1784]
I created a GLFWWindow with ImGui in it,but the problem i am currently facing is resizing.
What i want the program to do is to resize all ImGui components whenever i resize GLFWWindow.
Which would be the best way to do this and i already tried a few but some of them did not work and some of them simply crashed the entire app?

**Comment by ocornut** [comment]
You can use `SetNextWindowPos(0,0)`/`SetNextWindowSize(io.DisplaySize)` to make an imgui window follow the size of your platform window. Please describe what you tried, with code. If you have a crash please provide a callstack and information about it and make sure you read the comments if it is an Assert. And generally please make sure that you've read and are following the [Issues creation Guidelines](https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md) document.

**Comment by radovicz** [comment]
Thanks,i will try to be better in the future and what i decided to do instead is to just force the app to be maximized all the time and to disable window resizing!
