### ISSUE TITLE
Need to show multiple fonts in a single dropdown. 

### ISSUE THREAD

**Issue by KriyenKP** [ocornut/imgui#1793]
**Version/Branch of Dear ImGui:**
dear imgui, v1.52 WIP
ImGui Win32 + DirectX9 binding

Renderer

Need to show multiple fonts in a single dropdown. 
Language change dropdown that will show 
Chinese as 中文
Japanese as 日本語
Russian as русский

etc etc

**Comment by ocornut** [comment]
Combo boxes are just regular windows you can do anything you want with them, including changing fonts. Just use BeginCombo.

Also, you don’t necessarily need multiple font to support those languages you could be using a single font. 

Please use correct and precise imgui terminology, there’s nothing called “dropdown” in imgui.

**Comment by KriyenKP** [comment]
Sorry sorry. I meant combo box.
But you need to assign the list to the combobox? How would I cater for each?

**Comment by ocornut** [comment]
Version 1.52 may not have the general BeginCombo() API only the old Combo(), in which case it is better to update.
