### ISSUE TITLE
How to disable window rounding?

### ISSUE THREAD

**Issue by FishJesus** [ocornut/imgui#1797]
Hello, this is a simple problem I cant seem to find a solution to, when creating rectangles or displays of any kind with imgui they all appear to be smoothed out near the edge, how can i change this in order to give my imgui a sharp crisp feel.
![image](https://user-images.githubusercontent.com/38995711/39658763-4309e9c4-4fdf-11e8-9ccf-42b56e6440a8.png)

**Comment by Nukem9** [comment]
```
ImGui::GetStyle().WindowRounding = 0.0f;// <- Set this on init or use ImGui::PushStyleVar()
ImGui::GetStyle().ChildRounding = 0.0f;
ImGui::GetStyle().FrameRounding = 0.0f;
ImGui::GetStyle().GrabRounding = 0.0f;
ImGui::GetStyle().PopupRounding = 0.0f;
ImGui::GetStyle().ScrollbarRounding = 0.0f;
```

If you're like me, I didn't want *any* rounding in the ui.

**Comment by FishJesus** [comment]
thank you

**Comment by ocornut** [comment]
@FishJesus Please use `ShowDemoWindow()` and `ShowStyleEditor()` next time to browse for available features. The question could have been easily answered if you looked in there.

**Comment by vityafx** [comment]
Sorry, it's not really clear, if I can set these variables via `PushStyleVar`, when do I need to do that? After creating a frame via NewFrame but before creating a window? Or after creating a window? It's just that it doesn't work for me. Via the demo window it works, but it doesn't work when I try to do that for my window.

**Comment by ocornut** [comment]
WindowRounding is latched during the `Begin()` call. You can push/pop multiple times during the frame and every frame.
So PushStyleVar() / Begin() / PopStyleVar() should work.
