### ISSUE TITLE
i dont know how to use  to use languages Thailand in IMGUI

### ISSUE THREAD

**Issue by Ballza190123** [ocornut/imgui#1798]
Hello I Have Try To use Languages Thailand But Show Text Empty
ImGui::Text("สวัสดีครับ"); //SawasdiKrub
Help Me

**Comment by ocornut** [comment]
Please read the font documentation in `misc/fonts/README.txt`.

**Comment by ocornut** [comment]
Closing - sorry but #1586. (Same login/question on csgo cheating forum).
