### ISSUE TITLE
Yet another pure Java binding

### ISSUE THREAD

**Issue by ice1000** [ocornut/imgui#1799]
Repo: https://github.com/ice1000/jimgui

It has CircleCI builds so everyone can build it themselves.

I created it because I'm not satisfied with the one written in Kotlin, whose release size is about 30mb.  
It's too large for a simple tiny program.

My binding in progress (started less than a week) but a lot of features are already available now.

**Screenshots**

![jimgui-2](https://user-images.githubusercontent.com/16398479/39666503-38222a82-50d7-11e8-92f6-676df6b49f90.gif)

**Comment by ice1000** [comment]
Even created a code generation framework for this.

https://github.com/ice1000/jimgui/blob/7dd02b7e7c0bc97530b619fac91c2a4d3669e9f5/buildSrc/src/GenGenTask.kt#L88-L245

**Comment by ice1000** [comment]
@ocornut Should I close this issue?

**Comment by ocornut** [comment]
Yeah, i’ll close it now that it’s listed. Thank for letting us know! Looking good :)
