### ISSUE TITLE
Problemm with compile!

### ISSUE THREAD

**Issue by IlkaPoilka** [ocornut/imgui#1802]
LNK2001 ""bool __cdecl ImGui_ImplDX9_Init(void *,struct IDirect3DDevice9 *)" (?ImGui_ImplDX9_Init@@YA_NPAXPAUIDirect3DDevice9@@@Z)"	DimonHook	C:\Users\antid\Desktop\DimonHook\DimonHook\main.obj	1	
here this error ->  ImGui_ImplDX9_Init(hWnd, pDevice);

**Comment by ocornut** [comment]
Sorry but #1586
