### ISSUE TITLE
Automatically scrolling down a log doesn't scroll all the way

### ISSUE THREAD

**Issue by codecat** [ocornut/imgui#1804]
**Version/Branch of Dear ImGui:**

1.61 WIP

**My Issue/Question:**

I have a window containing the log of my application, and my intent is to automatically scroll it down when a new line is added, 

Above, `m_scrollToBottom` is set to true when there's some new lines added to the log. This doesn't fully scroll all the way down when new lines are added, it's as if the newly added line wasn't actually there. See screenshot below for context.

**Standalone, minimal, complete and verifiable example:**
```
static ImGuiTextBuffer _buffer;
static bool _scrollToBottom = false;

void AddLog(const char* str)
{
	_buffer.appendf("%s\n", str);
	_scrollToBottom = true;
}

void DrawLogWindow()
{
	ImGui::SetNextWindowPos(ImVec2(50, 50), ImGuiCond_FirstUseEver);
	ImGui::SetNextWindowSize(ImVec2(800, 600), ImGuiCond_FirstUseEver);

	ImGui::Begin("Log", &m_visible, ImGuiWindowFlags_NoCollapse);
	ImGui::TextUnformatted(_logBuffer.begin());

	if (_scrollToBottom) {
		ImGui::SetScrollHere(1.0f);
		_scrollToBottom = false;
	}

	ImGui::End();
}
```

**Screenshots/Video**

![log](https://user-images.githubusercontent.com/136534/39867451-4686fc3e-5455-11e8-92a0-448b665eb656.png)

**Comment by ocornut** [comment]
It seems that there's a bug in `SetScrollFromPosY()` when used on the same frame as an increase of the contents height, for now you may work-around it by using `ImGui::SetScrollHere(0.999f)` (you'll be missing 1 `ItemSpacing.y` worth of scrolling only).

**Comment by codecat** [comment]
Ah I see. Thanks for the workaround, this will work fine for the time being.

**Comment by codecat** [comment]
Here's another workaround that scrolls to the right position, but has that 1 extra frame stutter: (set `m_scrollToBottom` to 2)

```cpp
if (m_scrollToBottom > 0) {
	ImGui::SetScrollHere(1.0f);
	m_scrollToBottom--;
}
```

**Comment by ocornut** [comment]
Should be fixed now, if you can update let me know if it works for you.
I also changed the demo code to use SetScrollHere(1.0) instead of SetScrollHere(0.5) at the intent is clearer this way here.

**Comment by codecat** [comment]
Thanks for the quick fix! This works well, but there's still 1 frame where you can see it get covered by the bottom border. (Like with the integer workaround I posted above)

**Comment by ocornut** [comment]
I can't seem to repro that.

**Comment by codecat** [comment]
Try this:

```cpp
	static bool _scrollToBottom = false;
	static ImGuiTextBuffer _textBuffer;
	static int _number = 0;

	ImGui::Begin("Test control", nullptr, ImGuiWindowFlags_NoSavedSettings);
	if (ImGui::Button("Add line")) {
		_textBuffer.appendf("Number: %d\n", ++_number);
		_scrollToBottom = true;
	}
	ImGui::End();

	ImGui::Begin("Test", nullptr, ImGuiWindowFlags_NoSavedSettings);
	ImGui::TextUnformatted(_textBuffer.begin());
	if (_scrollToBottom) {
		ImGui::SetScrollHere(1.0f);
		_scrollToBottom = false;
	}
	ImGui::End();
```

Also, I initially tried this code, which shows the original problem again. Probably because it's a button, or maybe because it's more than just 1 control?

```cpp
	static bool _scrollToBottom = false;
	static ImGuiTextBuffer _textBuffer;
	static int _number = 0;

	ImGui::Begin("Test", nullptr, ImGuiWindowFlags_NoSavedSettings);
	ImGui::TextUnformatted(_textBuffer.begin());
	if (ImGui::Button("Add line")) {
		_textBuffer.appendf("Number: %d\n", ++_number);
		_scrollToBottom = true;
	}
	if (_scrollToBottom) {
		ImGui::SetScrollHere(1.0f);
		_scrollToBottom = false;
	}
	ImGui::End();
```

**Comment by ocornut** [comment]
Oh I see, sorry. It's not visible in the Console demo because the window padding is different.
It's not an easily solvable problem unfortunately, see #1526

**Comment by codecat** [comment]
Interesting, thanks for the info.

**Comment by ocornut** [comment]
The simplest workaround is to use WindowPadding.y == 0.0 in this case.

Other possible workaround I can think of right now would just be too messy/silly: move the cursor but don't draw the new item for a frame (if your text log is split into distinct items), set a clipping rectangle corresponding to the last reach distance, etc. that sort of thing. I don't think it's worth exploring it at least from the user's point of view. 

(When the ImDrawList become double buffered I would like to experiment with the possibility of occasionally reusing the previous frame of a given window to cover tricky transition like that. A similar technique could be used for dynamic font atlas if we have to grow the texture atlas mid-frame in that manner that would invalidate the previous UV (aka resizing the texture): being extremely occasional, reusing the entirely of the last frame render to hide invalid UV would be a good practical solution.)

**Comment by codecat** [comment]
Well I'm not going to make a lot of effort for something as simple as a scrolling debug log, but it's good to know there's possibilities either way!
