### ISSUE TITLE
Lag when dragging child windows

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [ocornut/imgui#1805]
Hi, first thanks for this amazing library!

**Version/Branch of Dear ImGui:**

1.60 (master) x 1.51

**My Issue/Question:**

It seems to me that sometime between version 1.51 and 1.60 some commit added a "lag" when dragging windows. I don't know if you can see it from the videos bellow, but when I drag the child window in version 1.51 the window "sticks to the mouse pointer", but when I do the same in version 1.60 first the mouse pointer goes, then the window follows (it is still pretty fast, but noticeable).

I'd like to know if this was on purpose and if there is any option/way to disable this lag in version 1.60 (so that it behaves like before)?

P.S.: Of course I could change imgui's code, but generally I like to avoid doing that so that I can update it easily.

**Screenshots/Video**

Before (1.51):

![before](https://user-images.githubusercontent.com/27699948/39871666-fd0cbb98-543b-11e8-888d-c41a2a45c22c.gif)

After (1.60):

![after](https://user-images.githubusercontent.com/27699948/39871672-012e5452-543c-11e8-911b-fdc768aaebda.gif)

Thanks anyways!

**Comment by usernameiwantedwasalreadytaken** [comment]
Thanks for the prompt answer.

> Can you compare how both behave at identical framerate?

Yeah! The framerate. I missed that... Now it runs exactly like before.

I don't have much experience with games and rendering like that (more like an MFC/Java/CSharp guy...). So this made me realize how much change can be caused by the framerate, both in terms of user experience and CPU/GPU usage:

![unthrottled](https://user-images.githubusercontent.com/27699948/39876453-961dd4ae-5449-11e8-9392-e6c844618a1b.png)

I personally prefer the unthrottled user experience (not making a game). But the high CPU/GPU usage might make me stick with the (now) default vsync behavior.

Again, thanks very much. Closing this.

**Comment by ocornut** [comment]
60 FPS isn't a bad framerate but the way mouse cursor are specifically handled by modern OS makes the dragging at 60 FPS feels very laggy. As mentioned, the solution of temporarily switching to a software mouse cursor while dragging is something I would like to experiment with more later.

The unthrottled version will always burn 1 CPU core. You could perfectly also aim at a framerate in-between, say 120 FPS. It's not a perfect strategy client-wise but it's easy to setup. (By the way, the unthrottled 700 FPS you get is an unusually low number on any semi modern machine.. Curious if the GIF capture affected it?).

**Comment by usernameiwantedwasalreadytaken** [comment]
I guess for now I will just use vsync. Maybe later I can find a compromise.

> By the way, the unthrottled 700 FPS you get is an unusually low number on any semi modern machine.. Curious if the GIF capture affected it?

Yes, it was definitely affecting it. Without the recorder, I can get to 1200-1300 FPS:

![unthrottled_app](https://user-images.githubusercontent.com/27699948/39878746-7bc62088-544f-11e8-9274-2c85651d117f.png)

**Comment by danger89** [comment]
> As a workaround, you can sleep the main thread for 17ms (1/60fps = 16.67ms) before Polling Events in each frame.

Adding sleep/waits in production code is a NO go. Never do this people. I'm using Imgui with GLFW + Vulkan. I tried already using `glfwWaitEvents()`  iso `glfwPollEvents()`. But I still suffer from this mouse lagging issue.

When I look to other applications like the Firefox browser, which is also hardware accelerated via the GPU with vsync, I do not experience this kind of mouse lag when dragging stuff around. This is really a bug in Imgui. Please re-open.

**Comment by Ristovski** [comment]
To anyone stumbling upon this in the future: If on Linux, one can use https://registry.khronos.org/OpenGL/extensions/SGI/GLX_SGI_video_sync.txt to significantly improve the latency (not sure what the Window equivalent is)

Example usage with GLFW is:
`glfwSwapInterval(0)` since `glXWaitVideoSyncSGI` will do the blocking (to vsync), then:
```C
glfwSwapBuffers(window);

uint remainder;
glXWaitVideoSyncSGI(1, 0, &remainder);
```

nVidia drivers recommend calling `glFinish()` before `glXWaitVideoSyncSGI()`, so beware.

Here is a simple demo showcasing the improvements (toggles between standard loop with vsync and no vsync + glXWaitVideoSyncSGI). As you can see, using glXWaitVideoSyncSGI improves the latency by quite a lot.

White square is a hardware accelerated cursor, green square is a quad updated with mouse coords, same effect can be seen in ImGui when dragging windows etc:

https://user-images.githubusercontent.com/994445/181042739-22e3d429-6e4e-4c91-9bc3-b6f5e2a88891.mp4

**Comment by pieter3d** [comment]
A crude but effective way of doing this (with GLFW anyway) is to put this in your loop:
```c++
  const bool dragging = ImGui::IsMouseDragging(ImGuiMouseButton_Left);
  glfwSwapInterval(dragging ? 0 : 1);
```
