### ISSUE TITLE
Problem with chinese or japanese input

### ISSUE THREAD

**Issue by 0x452** [ocornut/imgui#1807]
Hello, ocornut!

Thank you for imgui! I'm trying to make Japanese and Chinese input (i'm using ArialUni font with custom ranges)

```
static const ImWchar ranges[] =
{
	0x0020, 0xFFFF,//almost language of utf8 range
	0,
};
		
io.Fonts->AddFontFromMemoryCompressedTTF(ArialUni_compressed_data, ArialUni_compressed_size, 19.0f, NULL, &ranges[0]);
```
and i'm using (in `ImGui_ImplDX9_WndProcHandler`

```
if (wParam > 0 && wParam < 0x10000)
	io.AddInputCharacter((unsigned short)wParam)
```

But i'm getting that: 

![Image of Yaktocat](https://media.discordapp.net/attachments/425621615171338245/444184781845168158/TIM20180511021130.jpg)

what is a problem could be?

**Comment by ocornut** [comment]
The problem is that your wParam is probably not an Unicode codepoint. Use printf to verify the values you are passing to io.AddInputCharacter(). Read windows docs about WM_CHAR, WM_UNICHAR and how application build settings affect them.

**Comment by 0x452** [comment]
Thank for your answer! But we can’t use unicode setting in our project, is there any other way to convert it to unicode with WM_CHAR?

**Comment by wbc91** [comment]
The reason why we cannot type Chinese is we disabled the Unicode. Then one Chinese character will be split into two chars. However, the ImGui uses ImWchar to accept each one of them as a wchar. I resolved it by doing so.

int input_count = 0;
char InputBuffer[2];
void ImGuiIO::AddInputCharacter(ImWchar c)
{
	const int n = ImStrlenW(InputCharacters);
	if (n + 1 < IM_ARRAYSIZE(InputCharacters))
	{
		if (c > 128)
		{
			++input_count;
			if (input_count == 1)
			{
				InputBuffer[0] = (char)c;
			}
			else if (input_count == 2)
			{
				InputBuffer[1] = (char)c;
				wchar_t pwBuffer[2];
				::MultiByteToWideChar(CP_GBK, 0, InputBuffer, -1, pwBuffer, 2);
				ImWchar outputChar = pwBuffer[0];
				InputCharacters[n] = outputChar;
				InputCharacters[n+1] = '\0';
				input_count = 0;
			}
		}
		else
		{
			InputCharacters[n] = c;
			InputCharacters[n+1] = '\0';
		}
		
	}
}

Hope this can be a solution and finish such kind of problems.

**Comment by wbc91** [comment]
The reason why we cannot type Chinese is we disabled the Unicode. Then one Chinese character will be split into two chars. However, the ImGui uses ImWchar to accept each one of them as a wchar. I resolved it by doing so.

```

int input_count = 0;
char InputBuffer[2];
void ImGuiIO::AddInputCharacter(ImWchar c)
{
	const int n = ImStrlenW(InputCharacters);
	if (n + 1 < IM_ARRAYSIZE(InputCharacters))
	{
		if (c > 128)
		{
			++input_count;
			if (input_count == 1)
			{
				InputBuffer[0] = (char)c;
			}
			else if (input_count == 2)
			{
				InputBuffer[1] = (char)c;
				wchar_t pwBuffer[2];
				::MultiByteToWideChar(CP_GBK, 0, InputBuffer, -1, pwBuffer, 2);
				ImWchar outputChar = pwBuffer[0];
				InputCharacters[n] = outputChar;
				InputCharacters[n+1] = '\0';
				input_count = 0;
			}
		}
		else
		{
			InputCharacters[n] = c;
			InputCharacters[n+1] = '\0';
		}
		
	}
}
```
Hope this can be a solution and finish such kind of discussion.

**Comment by JX-Master** [comment]
My solution is adding WM_IME_CHAR support in WndProc function so that we don't need to change the source code of ImGui.cpp, since MultiByteToWideChar is not platform-independent.
This works for Chinese character in multi-bytes mode, hope it helps.

`       case WM_IME_CHAR:
	{
		auto& io = ImGui::GetIO();
		DWORD wChar = wParam;
		if (wChar <= 127)
		{
			io.AddInputCharacter(wChar);
		}
		else
		{
			// swap lower and upper part.
			BYTE low = (BYTE)(wChar & 0x00FF);
			BYTE high = (BYTE)((wChar & 0xFF00) >> 8);
			wChar = MAKEWORD(high, low);
			wchar_t ch[6];
			MultiByteToWideChar(CP_OEMCP, 0, (LPCSTR)&wChar, 4, ch, 3);
			io.AddInputCharacter(ch[0]);
		}
		return 0;
	}`
![tim 20180604225333](https://user-images.githubusercontent.com/25875303/40924579-30a53882-684a-11e8-9717-cfd1db0bb1c7.png)

**Comment by wbc91** [comment]
@JX-Master Your solution is better. Awesome!

**Comment by ocornut** [comment]
Thank you @JX-Master for the precision. I have updated the FAQ to add more details because this is a common problem.

**Comment by liu-kan** [comment]
@ocornut & @JX-Master When input Japanese with MS Japanese IME under CP936, dual bytes of one Japanese char are send within **one or two** wParam in succession. I test it with setting Windows display language to Japanese, the result is the same, I guest in Native Japanese System is same situation. So here is some tweaks.
```C++
// in initialization code
		BYTE previous_ime_char;
		WORD lang_id;
		previous_ime_char=0;
		HKL hkl=GetKeyboardLayout(0);		
		lang_id=LOWORD(hkl);
// in HandleMsg
       case WM_IME_CHAR:
			if (lang_id==0x0412)
				break;
			auto& io = ImGui::GetIO();
			DWORD wChar = wParam;
			if (wChar <= 127)
			{
				io.AddInputCharacter(wChar);
				return 0;
			}
			else if(wChar<0xFF){
			//GBK also supports Traditional Chinese, Japanese, English, Russian and (partially) Greek.
			//When input Japanese with MS Japanese IME under CP936, dual bytes of one Japanese char are send within one or two wParam in succession.
				if (previous_ime_char==0){ 
					previous_ime_char=(BYTE)(wChar & 0x00FF);
					return 0;
				}
				else{
					BYTE b2=(BYTE)(wChar & 0x00FF);
					wChar = MAKEWORD( previous_ime_char,b2);
					previous_ime_char=0;
				}
			}
			else
			{
				// swap lower and upper part.
				BYTE low = (BYTE)(wChar & 0x00FF);
				BYTE high = (BYTE)((wChar & 0xFF00) >> 8);
				if (previous_ime_char==0)
					wChar = MAKEWORD(high, low);
				else{
					wChar = MAKEWORD(previous_ime_char, high, low);
					previous_ime_char=low;
				}
			}
			wchar_t ch[6];
			MultiByteToWideChar(CP_OEMCP, 0, (LPCSTR)&wChar, 4, ch, 3);
			io.AddInputCharacter(ch[0]);			
			return 0;
		}
```
Fig.1 with @JX-Master tweak, but Without this tweaks. (Char in red frame is wrong!)
![Fig. 1 jp_withoutPatch](https://user-images.githubusercontent.com/8097683/103520985-fff00f80-4eb2-11eb-830a-96f0e39356c4.JPG)

Fig.2 with this tweaks, in chinese system.
![Fig.2 ch_jp_disCN](https://user-images.githubusercontent.com/8097683/103521099-2d3cbd80-4eb3-11eb-8f8f-24266a6c87b5.JPG)

Fig.3 with this tweaks, and change  Windows display language to Japanese.
![Fig.3 jp_disJP](https://user-images.githubusercontent.com/8097683/103521193-51989a00-4eb3-11eb-9998-a28f38f5bd75.JPG)

**Comment by sweihub** [comment]
@JX-Master Thanks for the Chinese input fix, the code should be included into official imgui demo I think.
