### ISSUE TITLE
Drawing each window separately

### ISSUE THREAD

**Issue by rhard** [ocornut/imgui#1809]
----

**Version/Branch of Dear ImGui:**

1.60

**Back-end/Renderer/OS:** _(if the question is related to inputs or rendering, otherwise delete this section)_

OpenGL3

**My Issue/Question:**

Hi Team,

My renderer engine gives OpenGL drawing callback only for each window separately. There is no callback to draw full-screen. So, is it possible to split RenderDrawListsFn to draw each window one by one?

What would be a possible approach in such case? Maybe many ImGuiIO instances?

Thanks,
Roman.

**Comment by ocornut** [comment]
I'm not sure I understand the question or request, please clarify.
Each ImDrawList typically correspond to a imgui window.

**Comment by rhard** [comment]
I have a game engine which provides an API for the plugin creators. There is an old callback to draw in OpenGL fullscreen directly. I created ImGui backend for the game using your OpenGL3 example. It is working as expected.

Now the game developers are going to sanitize their API and will remove the hook from above. The only possibility will remain is to create native windows. Each window will have a draw callback to draw OpenGL and fill the window. I created one window with fullscreen size and is able to draw ImGui content as well.

But there could be other windows from different plugins and from the game itself. So now I have other problems like how to handle mouse callbacks, window overlapping etc.

What I want is to draw each imgui window in a separate native game window. It like 

Let's say I have:

ImGui::Begin("Window 1");
    ...
    ...
    ...
imGui::End();

ImGui::Begin("Window 2");
    ...
    ...
    ...
imGui::End();

So I want the content of Window 1 is rendered inside draw callback for native window 1 and Window 2 is rendered inside callback for window 2.






     

 

   
  
 Using this API I can create a window with the draw callback to draw in OpenGL. Now I want to integrate ImGui to fill in this window callbacks.


As I understand current ImGui examples show how to draw complete ImGui content in one Render call, which I don't have anymore.

**Comment by ocornut** [comment]
But you could have all your imgui windows in the same secondary OS window and be done with it? Why precisely are you trying you dissociate the imgui windows from each others? It's possible but a lot more work.

You can create one imgui context `ImGui::CreateContext()` per OS window, and input management is up to you. Depending on your plugin architecture, if plugins don't interact with each other it may make more sense this way.

The upcoming viewport branch (#1542) ~ planned for 1.70 in a few months is trying to formalize an extension of allow to interacti seamlessly with multiple OS windows, but it's a big change and it's not ready yet.

**Comment by rhard** [comment]
The native windows I told are not the OS windows, but **game** native windows. Yes, I created one such "fake" transparent full-size window and draw ImGui staff there. Example of such solution is shown below:

![image](https://user-images.githubusercontent.com/8452952/39946170-73326f52-556d-11e8-91c2-a9133bfaf3e4.png)

I have three windows here. One on top is the game native window, left and right are ImGui windows drawn inside one full-screen transparent native window. Let's say the first(native) window is on top. Now if I select left window, both ImGui windows become on top of native. From the user point of view, this is not OK while right Window should stay behind the native. (I know technically this is true, while ImGui content is drawn in one step).

If for example here will be another plugin in the game which uses the same approach, the user will see all windows from one plugin are jumping all together in front of windows from another plugin.

 My idea was to assign somehow each ImGui window to own game window. 

Anyway thank you for your help, I will chekc viewport branch.

**Comment by rhard** [comment]
Another question is how to stop highlight the buttons if the mouse is over but the window is not on top or not in focus?

![image](https://user-images.githubusercontent.com/8452952/39950868-06777c3c-5585-11e8-8cdf-7375b60f2b52.png)

**Comment by ocornut** [comment]
I'm sorry it's just difficult to understand your use case and questions here.

If your application want imgui and non-window windows blending seamlessly with z-order to work, the application has to be responsible for window management and hit testing and passing the mouse to imgui when appropriate.

**Comment by rhard** [comment]
It's OK. I actually find the way how it may work. You can close the issue.

Thank you for the great library and for sharing it free!
