### ISSUE TITLE
Help wanted: Trouble in AMD / NVIDIA rendering

### ISSUE THREAD

**Issue by Encamy** [ocornut/imgui#1810]
**Version/Branch of Dear ImGui:**

 v1.60

**Back-end/Renderer/OS:**

- Windows 10 Pro 1803 build 17134.48
- Render: OpenGL 4.5
- IDE: MSVS Enterprise 2017

**Hardware Info**
First PC:
GPU: GeForce GTX 660
OpenGL version: 4.5.0 NVIDIA 397.64

Second PC:
GPU: AMD Radeon(TM) R7 Graphics
OpenGL version: 4.5.13506 Core Profile Context 23.20.15017.3010

**My Issue/Question:**

I have two PC. One with Nvidia gpu, another with Amd.
At NVIDIA GPU all work properly, but with AMD GPU strange things happen.

When I'm trying to open ImGui window, objects in the scene are rendered incorrectly (look at gif in attachments).
Without ImGui all works correctly (texturing/lighting and etc..), but in next frame after enabling ImGui everything breaks.

I tried to recompile and use the same .exe, always the result is the same.
I just can't understand what is going on. Looks like something wrong this cube coordinates (but they are ok).

I'll be glad if you can help me.

**Standalone, minimal, complete and verifiable example:**
```
ImGui::CreateContext();
ImGui_ImplGlfwGL3_Init(window, true);
ImGui::StyleColorsDark();

while (!glfwWindowShouldClose(window))
{
ImGui_ImplGlfwGL3_NewFrame();
ImGui::Begin("Debug", 0);
//some sliders (i removed this lines as unnecessary)
ImGui::End();
ImGui::Render();
ImGui_ImplGlfwGL3_RenderDrawData(ImGui::GetDrawData());
glfwSwapBuffers(window);
}

```

**Screenshots/Video**
Nvidia GPU:
![nvidia](https://user-images.githubusercontent.com/10367317/39960058-3a70e8a8-5624-11e8-8d10-509eb1df2185.gif)
Amd GPU:
![amd](https://user-images.githubusercontent.com/10367317/39960059-3a8e0956-5624-11e8-9648-2e41b7a557dd.gif)

Here is my full code: [github](https://github.com/Encamy/Beaver/blob/master/Beaver/main.cpp#L362)

**Comment by ocornut** [comment]
Hello,

The RenderDrawData function is trying to save and restore all the OpenGL state it modifies, but perhaps something isn’t restored properly. 

What you can do is to progressively comment out chunks of the render function. It doesn’t matter if imgui itself doesn’t show correctly any more, but try to find which GL calls are having an effect on your application first, then we can see how to fix it.

Omar

**Comment by Encamy** [comment]
Hello, Omar
The problem was in the library [tinyobjloader](https://github.com/syoyo/tinyobjloader). Maybe I used it in wrong way. Or my implementation of array obect is incorrect.
With objects created without tinyobjloader all works perfectly. Thank you for help
I think the issue can be closed now.

**Comment by ocornut** [comment]
Hello @encamy,
From an imgui point of view this is not a satisfactory resolution. The examples’ render function are meant to setup every piece of GL state they rely on, and restore any modified one. Your code above suggest that it isn’t the case so ideally we need to fix it. If you wish to help imgui you can try doing what I suggested above to find out what is interfering with the rest of your code.

**Comment by ocornut** [comment]
The mystery of OpenGL :)

Ideally the imgui render function should have zero external side effect on GL apart from writing pixels into the active framebuffer. If you have an idea later on how to investigate that it’d be cool.
