### ISSUE TITLE
IsClippedEx return false for all widgets when one is active

### ISSUE THREAD

**Issue by thedmd** [ocornut/imgui#1812]
ImGui 1.61+ (propably dating back to v1.44 WIP)

`IsClippedEx` seems to return false for all widgets with ID when any widget is in active state.

I disabled clipping in backend to test clipping rectangles. What I found that clipped widgets come back when I press (and hold) any other widget. Please notice arrow button in bottom right corner.

Is this an intended behavior or a bug?

![imgui-clip](https://user-images.githubusercontent.com/1197433/39971281-a6198de2-56f8-11e8-9f37-9bbaf4c7497b.gif)

**Comment by ocornut** [comment]
Do your arrows widget have unique ID and they don't all have the same ID ?
The active ID widget is never clipped so it can handle its processing.

**Comment by thedmd** [comment]
Yes. My mistake, sorry. : /

**Comment by ocornut** [comment]
np.. the construct in IsClippedEx() is difficult to read, I may rewrite it.
