### ISSUE TITLE
Columns: Change row colours

### ISSUE THREAD

**Issue by Jarrio** [ocornut/imgui#1813]
**Version/Branch of Dear ImGui:* 1.61

**My Issue/Question:** 
When dealing with large amounts of data, it would be nice to able to make readability easier with the ability to alternate (or colour coordinate multiple entries) row entries for the column API. As I can see right now to partially achieve these is to make the entry selectable. But that's not really the same as being able to glance over without moving the mouse from the current activity.

**Example:** 
![image](https://user-images.githubusercontent.com/748557/40006670-e088234a-5792-11e8-9234-5db3c01bc157.png)

**Comment by ocornut** [comment]
Yes this is a planned feature with the new columns/table system. I don't have an ETA but it may start showing up in master in a few short months.

In the meanwhile, if you are displaying large list of even spaced items (presumably using ImGuiListClipper) you can also draw them manually using the ImDrawList API.

**Comment by ocornut** [comment]
If you mean the _pixel position_ (that's what `GetColumnOffset` gives you), you can always use GetCursorPos(), GetCursorScreenPos(), etc.

**Comment by Jarrio** [comment]
Thanks, finally got around to this. The effect I wanted to achieve actually ended up being quite simple to implement - I just wanted a visual representation of quantities in a row/column like so:
![image](https://user-images.githubusercontent.com/748557/40498143-17802c2c-5f76-11e8-8497-6706fc37dbaf.png)

I'm using a language called Haxe but the code should be easily understood manipulatable for any other target:
```haxe
var draw_list = cpp.Pointer.fromRaw(ImGui.getWindowDrawList()).ref;

for (data in splice) {
	if (data == null) {
		continue;
	}

	ImGuiHelper.addColumnEntry(data[0]);
	
	max_column_width = ImGui.getColumnWidth(-1);
	var quantity_percent = (this.list.max_quantity - data[1].toFloat()) / this.list.max_quantity;

	if (quantity_percent < 0.1) {
		quantity_percent = 0.1;
	}

	bar_width = max_column_width * quantity_percent;
				
	var line_pos = ImGui.getCursorScreenPos();
	line_pos.x += max_column_width;

	var line_size = Util.toVec2(line_pos.x - bar_width, line_pos.y + 16);
	draw_list.addRectFilled(line_pos, line_size, this.base_color.toUInt());

	ImGuiHelper.addColumnEntry(data[1].formatNumber());
}
```

Should anyone be curious on how to achieve something like this for the time being!

**Comment by otse** [comment]
this gave me so many errors

**Comment by ocornut** [comment]
Thanks @Jarrio for your suggestion there.

For reference:
- There was a similar discussion in #2668 where we posted some code.
- And the upcoming Tables API (#2957) will provide both features to render alternate odd/even row color and alter row/cell colors manually. 
- In your specific case your display is specific anyway, so a custom approach is fine.

Will close this now!
