### ISSUE TITLE
Linker error 

### ISSUE THREAD

**Issue by Zort3x** [ocornut/imgui#1814]
**Version/Branch of Dear ImGui:**

v1.61

**Back-end/Renderer/OS:** _(if the question is related to inputs or rendering, otherwise delete this section)_

D3dx9 / Windows 10

**My Issue/Question:** Every single time i've tried to use imgui i always end up with linker errors, which is weird considering im doing what my friend told me to do and his works fine.
Without even using imgui, just when building i get 47 link errors

(https://hastebin.com/yocigurunu.rb) <- Linker errors

I'm suspecting this is due to the way im adding them to the project, but since there isn't really an official tutorial i cant really verify this.
I just add the imgui folder to my projects root then chose add existing files then chose imgui's files

**Comment by ocornut** [comment]
Hello,

This is a C++/Compiler/DLL issue not an imgui issue. Look up for information about linkage and compiling/linking with DLL. Depending on your exact setup you may or not need to redefine IMGUI_API in imconfig.cpp.

We can’t really help you without more details about your project and a detailed repro. I don’t know what your setup looks like and so cannot guess what’s wrong with it.

**Comment by Zort3x** [comment]
I seem to have fixed all of the linker errors, i made a mistake in one of my projects properties, anyways now im getting "unexpected end of file while looking for precompiled header. did you forget to add '#include "stdafx.h" to your source? twice (imgui.cpp & imgui_impl_dx9.cpp)

**Comment by ocornut** [comment]
You may want to disable precompiled headers for external libraries such as imgui.
Please look those issues up on Stackoverflow etc. they are very common/generic issues in the C++/Windows world.

**Comment by Zort3x** [comment]
I know you closed this, but i managed to actually get it to compile by disabling precompiled headers, it runs without assertion failures, but nothing shows up
