### ISSUE TITLE
ImGui::CalcTextSize does not take a format

### ISSUE THREAD

**Issue by Pombal** [ocornut/imgui#1818]
Hi, I'd like to draw floats at different precisions horizontally. It seems like what I want is to use ImGui::CalcTextSize to know what offset to pass to ImGui::SameLine. The problem is CalcTextSize does not take a format and ImGui::Text does so I don't know how to correctly calculate the size of a format like "%.2f" versus a format like "%.6f". 

Any ideas? Thanks a lot!

**Comment by ocornut** [comment]
Use sprintf or your own formatting helper to format once into a string and then pass that to `CalcTextSize()` and use `ImGui::TextUnformatted(str)` instead of `ImGui::Text("%s", str)`. (the later will also work but it's saner to not have to go through the formatting function twice)

**Comment by Pombal** [comment]
Awesome, thanks!
