### ISSUE TITLE
[viewports] some observations/bugs

### ISSUE THREAD

**Issue by einsweniger** [ocornut/imgui#1819]
**Branch of Dear ImGui:**

viewport (1cafdb5b46a366d566e4f430e8b093b5c2bd1352)

**Back-end/Renderer/OS:**

GLFW/OpenGL3/Linux + tiling window-manager (i3)

opengl3_example

**My Observations**

So, as promised I took a stab at the viewport branch.
Several issues surfaced, and I wanted to report them.

### Consequences of using a tiling window manager [caveat1]

I'm using a tiling window-manager. That means, whenever a new window is created it's moved according to the rules supplied by the user. By default for me, that's "resize and fit between the other windows"

![test2](https://user-images.githubusercontent.com/699867/40113933-5c5d4e4a-590b-11e8-8837-e2113cf26789.gif)

This is more of a "me problem", but for documentations sake, adding `glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);` after the other window hints keeps the window floating, so for me this is a solution. There might be other ways to set hints for the window manager, not sure if that's **the one**.

### Grabbing a window [caveat2]

With linux, there's usually the option to hold [alt] and drag a window. That's nice for me; i don't have to aim for the window title bar and use that.
When moving a window like this, ImGui will not detect tat the window is back in the original frame and render it as usual.
Linux window-managers also allow resizing with [alt] + [drag right mouse], which works fine (except when disabling window resizing like above).

### Dragging a window outside [caveat3]

When I drag a window out of the original one, a new one is created as expected. After the new window was created my mouse (obviously?) stops dragging, I have to release the mouse button and drag again. Might be another problem with me and my window manager

### Jittering windows [bug1]

After dragging the window outside, the window position jitters erratically. The amount of offset varies greatly and I am unsure what causes it.
Same for tooltips

### FPS drop [bug2]

As soon as tooltips or windows appear outside of the normal application, FPS halve.

### the visuals

Since github won't accept a webm w/ 300 kb and a gif clocks in at 5MB, here's a youtube link, with annotations in captions.
https://www.youtube.com/watch?v=e_PEHcUdUuI&t=8s

**Comment by ocornut** [comment]
Hello @einsweniger, could you repost this in #1542 ?

**Comment by einsweniger** [comment]
gladly! there's also some added information in caveat2
