### ISSUE TITLE
No Mouse input 

### ISSUE THREAD

**Issue by ghost** [ocornut/imgui#1820]
**Version/Branch of Dear ImGui:**
Latest (v1.61)

**Back-end/Renderer/OS:** _(if the question is related to inputs or rendering, otherwise delete this section)_
d3dx9

**My Issue/Question:** _(please provide context)_
Sorry for asking for help agian but  i seem to have encountered another issue, it draws perfectly now but theres no input, after watching a tutorial on how to set it up apparently i need to use ImGui_ImplDX9_WndProcHandler in my wndproc, although it seems this isn't in imgui anymore?
Are there any alternatives in the current imgui?

**Comment by Zort3x** [comment]
I looked at it, i did try to use it aswell but i just get errors, i tried with an old version of imgui aswell, same thing
