### ISSUE TITLE
Unresolved External symbol errors

### ISSUE THREAD

**Issue by CowzMooMoo** [ocornut/imgui#1824]
Help, I am getting errors with newest version of ImGui
Errors:
https://i.imgur.com/PyNATZd.png
All files that I include:
https://i.imgur.com/2VEo5lG.png

Thanks in advance

**Comment by coderboyisongithub** [comment]
Same problem with me pal

**Comment by ocornut** [comment]
@CowzMooMoo Sorry but #1586 
@coderboyisongithub You need to compile and link all the .cpp files of imgui. The screenshot suggest he didn't compile or link with imgui_draw.cpp

**Comment by ocornut** [comment]
@coderboyisongithub I don't understand what you mean. All .cpp needs to be compiled like any regular piece of code. This is documented at the top of the README file. Just add the files to your existing project.

**Comment by coderboyisongithub** [comment]
mean i need to create a project,compile all cpp and then use its library
into my project>

**Comment by ocornut** [comment]
No. You already have a project (your app/game). You can add the imgui .cpp files into your project. Don't create a library if you don't need to.

**Comment by coderboyisongithub** [comment]
I got it"! i added all .cpp files ...though it is triggring
error:1>E:\ImGUI\imgui_draw.cpp(101): error C2006: '#include' : expected a
filename, found 'identifier'
1>E:\ImGUI\imgui_draw.cpp(101): fatal error C1083: Cannot open include
file: '': No such file or directory
and it is about (#ifdef IMGUI_STB_RECT_PACK_FILENAME
#include IMGUI_STB_RECT_PACK_FILENAME).Why so?previously a attached .h
files also but faced same error..:(

**Comment by ocornut** [comment]
It looks like you defined `IMGUI_STB_RECT_PACK_FILENAME` for some reason.?
This place isn't a community for helping people with general C++ stuff unfortunately. Please read https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md and when reporting issue please make sure you provide the right amount of information and in a readable format. This will force you to study and narrow down your issue.

**Comment by coderboyisongithub** [comment]
I didnt defined IMGUI_STB_RECT_PACK_FILENAME  by the way..I is in you
header..I didnt touched your code still>!!
