### ISSUE TITLE
ImGuiColorEditFlags_NoDragDrop

### ISSUE THREAD

**Issue by OswaldHurlem** [ocornut/imgui#1826]
**Version/Branch of Dear ImGui:** v1.61 WIP

**My Issue/Question:** For prototype design purposes I am using a few non-interactive ColorButtons. However, Dear ImGui prevents me from making them totally non-interactive since they work as drag/drop targets.
What would be nice is a flag to disable this.
If this instead worked via a unstable internal function like PushItemFlags, that would be OK.

**Standalone, minimal, complete and verifiable example:**
```
    ImGui::Text("I'd like this button to do absolutely nothing");
    ImGui::ColorButton("#DoNothingButton", ImVec4(1.0f, 0.0f, 0.0f, 1.0f), ImGuiColorEditFlags_NoTooltip);
```

**Comment by ocornut** [comment]
@OswaldHurlem Added this as suggested, it makes sense. 

```
// ColorEdit: disable drag and drop target. ColorButton: disable drag and drop source.
ImGuiColorEditFlags_NoDragDrop      = 1 << 9,
```
