### ISSUE TITLE
Imgui is displaying nothing while glfw window is working fine..why?

### ISSUE THREAD

**Issue by coderboyisongithub** [ocornut/imgui#1828]
I attached imgui with my opengl project.i am using glfw/glew.I used opengl3_example to setup imgui into my project. I modified so that it must use glew instead of using gl3w.The problem is, GLFW window and opengl is working normal but Imgui elements is not being rendered,Though,I build the example first.It works there,I obtain no runtime error..every thing is fine currently..here is the implementation code 
`
#include "stdafx.h"
#include "lunchBox.h"
#include "imgui.h"
#include "imgui_impl_glfw_gl3.h"

	static void glfw_error_callback(int error, const char* description)
	{
	fprintf(stderr, "Error %d: %s\n", error, description);
	}

	int main(int, char**)
	{
	// Setup window
	glfwSetErrorCallback(glfw_error_callback);
	if (!glfwInit())
	return 1;
 
	#if __APPLE__
	glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
	#endif
	GLFWwindow* window = glfwCreateWindow(1280, 720, "ImGui GLFW+OpenGL3 example", NULL, NULL);
	glfwMakeContextCurrent(window);
	glfwSwapInterval(1); // Enable vsync
	glewInit();

	// Setup Dear ImGui binding
	IMGUI_CHECKVERSION();
	ImGui::CreateContext();
	ImGuiIO& io = ImGui::GetIO(); (void)io;
	//io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;  // Enable Keyboard Controls
	//io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;   // Enable Gamepad Controls
	ImGui_ImplGlfwGL3_Init(window, true,(char*)glGetString(GL_VERSION));

	// Setup style
	//ImGui::StyleColorsDark();
	ImGui::StyleColorsClassic();

	// Load Fonts
	// - If no fonts are loaded, dear imgui will use the default font. You can also load multiple fonts and use ImGui::PushFont()/PopFont() to select them. 
	// - AddFontFromFileTTF() will return the ImFont* so you can store it if you need to select the font among multiple. 
	// - If the file cannot be loaded, the function will return NULL. Please handle those errors in your application (e.g. use an assertion, or display an error and quit).
	// - The fonts will be rasterized at a given size (w/ oversampling) and stored into a texture when calling ImFontAtlas::Build()/GetTexDataAsXXXX(), which ImGui_ImplXXXX_NewFrame below will call.
	// - Read 'misc/fonts/README.txt' for more instructions and details.
	// - Remember that in C/C++ if you want to include a backslash \ in a string literal you need to write a double backslash \\ !
	//io.Fonts->AddFontDefault();
	//io.Fonts->AddFontFromFileTTF("../../misc/fonts/Roboto-Medium.ttf", 16.0f);
	//io.Fonts->AddFontFromFileTTF("../../misc/fonts/Cousine-Regular.ttf", 15.0f);
	//io.Fonts->AddFontFromFileTTF("../../misc/fonts/DroidSans.ttf", 16.0f);
	//io.Fonts->AddFontFromFileTTF("../../misc/fonts/ProggyTiny.ttf", 10.0f);
	//ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\ArialUni.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesJapanese());
	//IM_ASSERT(font != NULL);

	bool show_demo_window = true;
	bool show_another_window = false;
	ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);

	// Main loop
	while (!glfwWindowShouldClose(window))
	{
	// You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
	// - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application.
	// - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application.
	// Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
	glfwPollEvents();
	ImGui_ImplGlfwGL3_NewFrame();
	//ImGui::NewFrame();

	// 1. Show a simple window.
	// Tip: if we don't call ImGui::Begin()/ImGui::End() the widgets automatically appears in a window called "Debug".
	{
	static float f = 0.0f;
	static int counter = 0;
	ImGui::Text("Hello, world!");                           // Display some text (you can use a format string too)
	ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f    
	ImGui::ColorEdit3("clear color", (float*)&clear_color); // Edit 3 floats representing a color

	ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our windows open/close state
	ImGui::Checkbox("Another Window", &show_another_window);

	if (ImGui::Button("Button"))                            // Buttons return true when clicked (NB: most widgets return true when edited/activated)
	counter++;
	ImGui::SameLine();
	ImGui::Text("counter = %d", counter);

	ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
	}

	// 2. Show another simple window. In most cases you will use an explicit Begin/End pair to name your windows.
	if (show_another_window)
	{
	ImGui::Begin("Another Window", &show_another_window);
	ImGui::Text("Hello from another window!");
	if (ImGui::Button("Close Me"))
	show_another_window = false;
	ImGui::End();
	}

	// 3. Show the ImGui demo window. Most of the sample code is in ImGui::ShowDemoWindow(). Read its code to learn more about Dear ImGui!
	if (show_demo_window)
	{
	ImGui::SetNextWindowPos(ImVec2(650, 20), ImGuiCond_FirstUseEver); // Normally user code doesn't need/want to call this because positions are saved in .ini file anyway. Here we just want to make the demo initial state a bit more friendly!
	ImGui::ShowDemoWindow(&show_demo_window);
	}

	// Rendering
	int display_w, display_h;
	glfwGetFramebufferSize(window, &display_w, &display_h);
	glViewport(0, 0, display_w, display_h);
	glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
	glClear(GL_COLOR_BUFFER_BIT);
	ImGui::Render();
	ImGui_ImplGlfwGL3_RenderDrawData(ImGui::GetDrawData());
	glfwSwapBuffers(window);
	}

	// Cleanup
	ImGui_ImplGlfwGL3_Shutdown();
	ImGui::DestroyContext();

	glfwDestroyWindow(window);
	glfwTerminate();

	return 0;
	}

`
Till now every thing is fine but no imgui window is found in glfw window??

**Comment by ocornut** [comment]
If this exact code doesn't work but the code in examples/opengl3_example/ work then you want to compare them and see what changed. Maybe see if moving the `glewInit()` call would make a difference, and remove that extraneous version string you added to the `ImGui_ImplGlfwGL3_Init()` call for a start.

You may also use a graphics debugger such as RenderDoc to understand what's going on with your rendering.

**Comment by coderboyisongithub** [comment]
@ocornut 
I just encountered the error in code... it is here
` ImGui_ImplGlfwGL3_Init(window, true,NULL);` the third parameter needs to be null.the opengl version string parameter,It is working fine,but why so??

**Comment by coderboyisongithub** [comment]
Humm...may be..but what about the function difinition...the thrid parameter is causing error of duplicate function deceleration..(which i removed by slight modification in your code...Now its working fine:))But why so??

**Comment by coderboyisongithub** [comment]
Do imgui have any error callback or error reterival function just like in opengl `glGetProgramInfoLog(),glGetProgramiv() ` things like that??That could be handy in those situation??

**Comment by ocornut** [comment]
This is a GL error you were having anyway, it’s not within the scope of imgui to be helping with GL use. The new comments should help.

> .the thrid parameter is causing error of duplicate function deceleration..(which i removed by slight modification

Please provide details.
