### ISSUE TITLE
Forceing Keyboard hot.

### ISSUE THREAD

**Issue by Shanzem** [ocornut/imgui#1832]
**Version/Branch of Dear ImGui:**

1.54

**Back-end file/Renderer/OS:**

Direct x 9 example/windows 8.1.

You rock, thank you soo much for imgui, you are THE first graphical interface i have ever used.
And you got me hooked, thank you!

Trying to turn a right click menu to do copy and paste.

By tricking in code that CTRL+C has been pressed.

Is it doable?
```
if(show_right_click_menu)
		{
			ImVec2 base_pos = ImGui::GetMousePos();
			ImGui::SetNextWindowPos(ImVec2(base_pos.x,base_pos.y),ImGuiCond_Appearing);
			ImGui::SetNextWindowSize(ImVec2(100,105));
			ImGui::Begin("###rightmenu", &show_right_click_menu,ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize);
			ImGui::BeginChild("####rightmenu", ImVec2(-1,-1), true,ImGuiWindowFlags_NoScrollbar);
            sprintf(right_click_selection, "  Copy", 1);
            if (ImGui::Selectable(right_click_selection, right_menu_selection == 1 ))
////////////////////////////////////////////////////////////////////
//
//	Still WIP instead of reinventing the wheel. Forceing CTRL+C hot.
//	Imgui`s built in copy function should pick the key combination up. 
//	Same for paste operation. CTRL+V hot.
//
//	However proveing maddeningly difficult!
//	Will have to post a issue note on github.
//
//	Can also achieve the same with Redo/Undo.
//
//	Keys CTRL+Y: redo & CTRL+Z: undo.
//
//	Failed attemps below BUT keeping for github question to Omar Cornut.

			{
			right_menu_selection = 1; //show_right_click_menu = false;
			//ImGui::GetIO().KeyCtrl == true and ImGuiKey_C == true;
			//ImGui::IsKeyDown(ImGuiKey_C) == true;
			//IsKeyPressedMap(ImGuiKey_C) = true; 
			//ImGuiKey_C == true;
			//ImGuiIO.KeyCtrl = true;ImGuiIO.KeysDown = ImGuiKey_C = true;
			}
			ImGui::Separator();
			sprintf(right_click_selection, "  Paste", 2);
            if (ImGui::Selectable(right_click_selection, right_menu_selection == 2 )){right_menu_selection = 2;} 
   			ImGui::Separator();
			sprintf(right_click_selection, "  Redo", 3);
            if (ImGui::Selectable(right_click_selection, right_menu_selection == 3 )){right_menu_selection = 3;} 
   			ImGui::Separator();
			sprintf(right_click_selection, "  Undo", 4);
            if (ImGui::Selectable(right_click_selection, right_menu_selection == 4 )){right_menu_selection = 4;} 
   			
			ImGui::EndChild();
			ImGui::End();
		}
```

**Comment by ocornut** [comment]
What are you trying to copy/paste/undo/redo?

You are asking about how to implement what you think is the right solution to your problem, without describing the initial problem in more detail. 

Clipboard operations are supported on `InputText()`. Interacting with another widget would deactivate the InputText() so what you are trying to do wouldn't work or wouldn't make much sense. You probably need to state your initial problem first so we can discuss solutions.

**Comment by Shanzem** [comment]
I see! Basically highlighting (Text selection) from an InputTextMultiline.
And pasteing into another  InputTextMultiline. but instead of using CTRL+C,CTRL+V.

Opening a right click window and when a user click the button copy, CTRL+C from the keyboard is turned
true. so imgui has been told (fooled) to copy selected text.

imgui does not lose text selected on right clicking only left!

Link to project main. Its a simple LUA editor :+1: 


https://github.com/Shanzem/LAU.Editor/blob/master/main.cpp

**Comment by ocornut** [comment]
> imgui does not lose text selected on right clicking only left!

The problem is that clicking the _button_ with lose the selection currently. I'll add a note about making that more easy to achieve with future InputText change but right now it's not trivial.

**Comment by Shanzem** [comment]
Thank you sooo much i wish i could contribute but my programming skills and knowledge are lacking if none existent. That means asking for changes and it makes me feel awful. 

Again thank you.

**Comment by ocornut** [comment]
No worry, it's a fair request. It's just that we have lots of request and need to prioritize them. This is useful as it will contribute for defining the specs to a future rework of InputText.
