### ISSUE TITLE
Activate non existing widget in next frame.

### ISSUE THREAD

**Issue by e3dos** [ocornut/imgui#1833]
Dear Omar,
I have the current situation:
```
if (m_rename) {
			
			if (ImGui::InputText("##objectNameInput", buf, 1024)) {
				lastSelected->setObjName(buf);
			};
if (!ImGui::IsItemFocused()) m_rename = false;
			
		}		
		else {
			if (ImGui::Selectable(lastSelected->getObjName().c_str())) {
				m_rename = true;
				ImGui::SetKeyboardFocusHere(-1);
			};
		}

```

Is it possible to activate the textInput without even existing on the current frame?
I want to achieve a input text only if the user selects the non input text button, like some apps do.
Right now this is not working because when it first appear, the text input button comes with lost focus.
If focus is lost on the text input, I want to get back to the normal selectable button.

I saw a  IMGUI_API void          ActivateItem(ImGuiID id); function but since it is on internals
I don't know if I should use it.

edit:
Ok I got working with:
```
if (m_rename) {
			
			if (ImGui::InputText("##objectNameInput", buf, 1024)) {
				lastSelected->setObjName(buf);
			};
			if (!ImGui::IsItemActive()) m_rename = false;
		}		
		else {
			if (ImGui::Selectable(lastSelected->getObjName().c_str())) {
				m_rename = true;
				ImGui::ActivateItem(ImGui::GetID("##objectNameInput"));
			};
		}
```

Thanks!

**Comment by ratchetfreak** [comment]
Sounds really like you want a different visual for unselected inputText that hides that it is a input text
