### ISSUE TITLE
How to do this?

### ISSUE THREAD

**Issue by nikitenko987** [ocornut/imgui#1834]
![image](https://user-images.githubusercontent.com/39587983/40480600-ae493b86-5f57-11e8-9af9-8e7f947c2a08.png)
(image from your github page)
How to create this? I really dont know.

**Comment by ocornut** [comment]
This is just some drawing some lines using `ImDrawList::AddLine()` API and drawing a texture using e.g. `ImDrawList::AddImage()` or `ImGui::Image()`.

**Comment by nikitenko987** [comment]
Yes, i know how to draw image or line, but how to draw mesh on background? or this image too?
I just want to use this in my game, i think its cool. I saw one guy, who use this to change player name coords by moving text in this place, its rly possible?

**Comment by ocornut** [comment]
I don't know what you refer as "mesh on background".
The grid is made of lines. The character is an imagine.

> I just want to use this in my game, i think its cool. I saw one guy, who use this to change player name coords by moving text in this place, its rly possible?

I don't understand. Please clarify and provide more context.

**Comment by nikitenko987** [comment]
Ok. He moves the text (nickname) in the radius of the grid, but in so doing the position of the text in the game also changes, just like in this field

**Comment by Wolftronics-SBC** [comment]
maybe that will help
https://openframeworks.cc/documentation/3d/ofMesh/

**Comment by ocornut** [comment]
> Ok. He moves the text (nickname) in the radius of the grid, but in so doing the position of the text in the game also changes, just like in this field

I don't understand what any of this means, sorry.

**Comment by nikitenko987** [comment]
![image](https://user-images.githubusercontent.com/39587983/40482279-f4a4df86-5f5c-11e8-9066-b7956fc39eea.png)
And now?

**Comment by ocornut** [comment]
You are asking a programming question that has nothing to do with dear imgui there, I have to close this.
