### ISSUE TITLE
FYI: There is no reason to save ELEMENT_ARRAY_BUFFER binding here

### ISSUE THREAD

**Issue by greggman** [ocornut/imgui#1836]
https://github.com/ocornut/imgui/blob/5fd23eeb742516bbcc2b3d3b6907f7f11297344b/examples/opengl3_example/imgui_impl_glfw_gl3.cpp#L87

ELEMENT_ARRAY_BUFFER binding is part of the vertex array state. Since you're creating a new vertex array you then set the ELEMENT_ARRAY_BUFFER on that vao. When you restore the previous VAO it will automatically be back to the previous ELEMENT_ARRAY_BUFFER just like all of the attributes.

**Comment by ocornut** [comment]
Those discussions linked below seems to agree on your statement and so I've pushed the change. The VAO used to be created once but the code has been changed to recreate them to make it easier to use the code with multiple OpeNGL contexts, so now it's created during render and that backup/restore of the ELEMENT_ARRAY_BUFFER is extraneous. 

That's all assuming that the statement that "ELEMENT_ARRAY_BUFFER is part of the VAO state" is correct. OpenGL being a minefield I don't exclude the possibility that on some config/some drivers, but I guess we'll find out if this happens!

Thanks!

Some ref:
https://www.opengl.org/discussion_boards/showthread.php/176790-VAOs-and-GL_ARRAY_BUFFER-binding
https://stackoverflow.com/questions/46133849/vao-and-gl-element-array-buffer-association
