### ISSUE TITLE
Undefined reference of ImGUI

### ISSUE THREAD

**Issue by LiuZHolmes** [ocornut/imgui#1837]
I tried the sample code for opengl3 in ubuntu 18.04 LTS 

        #include <imgui.h>
        #include <imgui_impl_glfw_gl3.h>
        #include <GL/gl3w.c>
        #include <GL/gl3w.h>
        #include <GLFW/glfw3.h>
        #include <imgui_internal.h>
        
        static void error_callback(int error, const char* description)
        {
            fprintf(stderr, "Error %d: %s\n", error, description);
        }
        
        int main(int, char**)
        {
            // Setup window
            glfwSetErrorCallback(error_callback);
            if (!glfwInit())
                return 1;
            glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
            glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
            glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
        #if __APPLE__
            glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
        #endif
            GLFWwindow* window = glfwCreateWindow(1280, 720, "ImGui OpenGL3 example", NULL, NULL);
            glfwMakeContextCurrent(window);
            glfwSwapInterval(1); // Enable vsync
            gl3wInit();
        
            // Setup ImGui binding
            ImGui_ImplGlfwGL3_Init(window, true);
        
            // Load Fonts
            // (there is a default font, this is only if you want to change it. see extra_fonts/README.txt for more details)
            //ImGuiIO& io = ImGui::GetIO();
            //io.Fonts->AddFontDefault();
            //io.Fonts->AddFontFromFileTTF("../../extra_fonts/Cousine-Regular.ttf", 15.0f);
            //io.Fonts->AddFontFromFileTTF("../../extra_fonts/DroidSans.ttf", 16.0f);
            //io.Fonts->AddFontFromFileTTF("../../extra_fonts/ProggyClean.ttf", 13.0f);
            //io.Fonts->AddFontFromFileTTF("../../extra_fonts/ProggyTiny.ttf", 10.0f);
            //io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\ArialUni.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesJapanese());
        
            bool show_test_window = true;
            bool show_another_window = false;
            ImVec4 clear_color = ImColor(114, 144, 154);
        
            // Main loop
            while (!glfwWindowShouldClose(window))
            {
                glfwPollEvents();
                ImGui_ImplGlfwGL3_NewFrame();
        
                static float f = 0.0f;
                ImGui::Text("Hello, world!");
                ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
                ImGui::ColorEdit3("clear color", (float*)&clear_color);
                if (ImGui::Button("Test Window")) show_test_window ^= 1;
                if (ImGui::Button("Another Window")) show_another_window ^= 1;
                ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
        
                // Rendering
                int display_w, display_h;
                glfwGetFramebufferSize(window, &display_w, &display_h);
                glViewport(0, 0, display_w, display_h);
                glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
                glClear(GL_COLOR_BUFFER_BIT);
                ImGui::Render();
                glfwSwapBuffers(window);
            }
        
            // Cleanup
            ImGui_ImplGlfwGL3_Shutdown();
            glfwTerminate();
        
            return 0;
        }
The include path is correct and i link all the lib for gl3w, glfw3 and etc..
CMake : target_link_libraries(${PROJECT_NAME} GL GLU glfw3 X11 Xxf86vm Xrandr pthread Xi dl Xinerama Xcursor)
Then i got a bunch o errors : undefined refenrence of  
ImGui_ImplGlfwGL3_Init(GLFWwindow*, bool, char const*)
ImGui_ImplGlfwGL3_NewFrame()
ImGui::Text(char const*, ...) and so on...
What should i do to fix this? is this a common c++ configuration error or the problem of imgui?

**Comment by ocornut** [comment]
You need to be compiling/linking with all the functions you are referencing.
You probably forgot to compile and link with all of the `imgui*.cpp` files you are using.
This is a common C++ error.
