### ISSUE TITLE
ImDrawVert change possible? (add a union for the color)

### ISSUE THREAD

**Issue by mgerhardy** [ocornut/imgui#1841]
**Version/Branch of Dear ImGui:**

master

**My Issue/Question:**

My engine is using the `ImDrawVert` data types to map to opengl constants automatically. A stripped down version looks like this:

```
/**
 * @brief Maps data types that are then later mapped to gl data types
 */
template<class DATATYPE>
constexpr inline DataType mapType() {
	if (std::is_floating_point<DATATYPE>()) {
		if (sizeof(DATATYPE) == 4u) {
			return DataType::Float;
		}
		return DataType::Double;
	}

	if (sizeof(DATATYPE) == 1u) {
		if (std::is_unsigned<DATATYPE>()) {
			return DataType::UnsignedByte;
		}
		return DataType::Byte;
	}

	if (sizeof(DATATYPE) == 2u) {
		if (std::is_unsigned<DATATYPE>()) {
			return DataType::UnsignedShort;
		}
		return DataType::Short;
	}

	if (sizeof(DATATYPE) == 4u) {
		if (std::is_unsigned<DATATYPE>()) {
			return DataType::UnsignedInt;
		}
		return DataType::Int;
	}

	return DataType::Max;
}
```

Currently I have to add a union to perform the mapping 
```
#define IMGUI_OVERRIDE_DRAWVERT_STRUCT_LAYOUT \
struct ImDrawVert { \
	union { \
		ImVec2 pos; \
		struct { \
			float x; \
			float y; \
		}; \
	}; \
	union { \
		ImVec2 uv; \
		struct { \
			float u; \
			float v; \
		}; \
	}; \
	union { \
		ImU32 col; \
		struct { \
			uint8_t r; \
			uint8_t g; \
			uint8_t b; \
			uint8_t a; \
		}; \
	}; \
};
```
This is due to the fact that the engine can't know whether you are giving a value to the first integer of a x-component color struct, or a color value packed as integer.

With the union added I'm able to perform all the mapping automatically:
```
	_vbo.addAttribute(_shader.getColorAttribute(_bufferIndex, &ImDrawVert::r, true));
	_vbo.addAttribute(_shader.getTexcoordAttribute(_bufferIndex, &decltype(ImDrawVert::uv)::x));
	_vbo.addAttribute(_shader.getPosAttribute(_bufferIndex, &decltype(ImDrawVert::pos)::x));
```

Now finally to my question. Would it be possible to add this union upstream? It might help others, too. While it is not a big deal to override it on my own, it just wouldn't be needed with that union.

**Comment by mgerhardy** [comment]
The "problem" here might be that ImVec2 might be a custom non-imgui controller type. But for the color, this should still work.

**Comment by ocornut** [comment]
I am not sure I understand the need to change such a low level imgui type when you could either

- make your function take explicit types.
- create a local dummy type that matches the ImDrawVert layout and satisfy the constraints of type detection functions.

Etc.
There are many ways around that wouldn’t need to affect every users.

**Comment by mgerhardy** [comment]
For me it works - I was just thinking that it might be an improvement.
