### ISSUE TITLE
Seeking sample of how to have 2 (or more) font sizes of same font so I can push/pop.

### ISSUE THREAD

**Issue by pvtinflex** [ocornut/imgui#1842]
My apologies in advance if I have missed the obvious.

I'd like to bake the same font in to my ImGui app with 2 or 3 different sizes so I can pick which is most appropriate for the required task.

My second question is then, how does one specifically select that font size to be used?

I do feel like I've missed an obvious thing here.  I searched through the code examples for PushFont()/PopFont() and read through the imgui/misc/fonts/ too.

**Comment by ocornut** [comment]
Hello,

The AddFontXXX functions are returning ImFont*. You can store those pointers in your app code and pass them to PushFont() as needed.

-Omar

**Comment by pvtinflex** [comment]
Fantastic.  Just the clarification I was seeking.  Much appreciated.
