### ISSUE TITLE
Closing a Popup when the last item isn't hovered

### ISSUE THREAD

**Issue by Pombal** [ocornut/imgui#1846]
Hello,

I'm trying to open a Popup when hovering over a CheckBox and then having the Popup automatically close when the CheckBox isn't being hovered anymore.

I've tried something along the lines of:

`
ImGui::Checkbox("awesome", &awesomeness);
if (ImGui::IsItemHovered())
{
    ImGui::OpenPopup("context");
}
else
{
    ImGui::CloseCurrentPopup();
}`

and using variations with BeginPopup and EndPopup but it always seems like the popup isn't in the stack and doesn't get closed, even though it is visible. The opening when on hover works great.

Another issue I see is that while the PopUp is open I can't click on the CheckBox. I do want to have input on the PopUp since it's going to be a DragInt but I'd like the inputs to go to the PopUp while I'm inside the Popup rect and the inputs to go to the CheckBox while I'm outside the Popup rect and inside the CheckBox one.

What am I missing? Thanks!

**Comment by Pombal** [comment]
BeginTooltip() is just for text right? I'd like the Popup to be a DragInt that I can interact with. But only if the mouse has hovered over another element. When the mouse hovers away I'd like the Popup to disappear, kind of like how the Tooltip works. I guess what I want is a halfway between the Tooltip and the Popup. Is there a way to achieve this?

**Comment by ocornut** [comment]
BeginTooltip() is for anything. however:

> But only if the mouse has hovered over another element. When the mouse hovers away I'd like the Popup to disappear, 

There is a contradiction here. If you hover away from the checkbox that opened the popup, moving to to the popup, then you code will close the popup. In other terms, the behavior you are asking for makes you unable to interact with the popup at all. The behavior you want is therefore probably something else.

**Comment by Pombal** [comment]
Good to know BeginTooltip() works with anything, thanks. Problem is it follows the mouse so I can't interact with it.

I guess the behaviour I want is: If I hover over an element, I'd like a popup to appear. If the mouse is inside the original element or inside the popup, then maintain the popup visible so interaction is possible with either. Input should be on the popup but if I click on the original element client rect then the input should go to the original element. If the mouse stops hovering either of the elements, hide the popup.

As an example, the imgui memory editor code has an options button which opens a popup with some options when clicked. The behaviour I'm after is instead of clicking, I'd like to hover over the options button and have the options appear right below as usual and if the mouse leaves the options menu or the options themselves then the menu disappears.

**Comment by ocornut** [comment]
You'll want to use `IsItemHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup)` on the original item + `IsWindowHovered()` inside the popup itself. If both are false then you can close the popup.

Display all those values with `Text()` statement before attempting any call to `CloseCurrentPopup()` if you are not sure how they work.

**Comment by Pombal** [comment]
Nice, thanks! That gives me most of what I want.

I had to use `ImGuiHoveredFlags_AllowWhenBlockedByActiveItem` on `IsWindowHovered()` to be able to interact with the popup otherwise it would disappear when clicked.

I still have a few issues I'm not able to fix:
- When the mouse is near an edge of the Checkbox, the Popup flickers intermittently. The flickering goes away when moving the mouse more to the center of the Checkbox.
- I'm not able to click on the CheckBox, only the Popup. I'm not sure how say that input should also be able to go to the Checkbox if the mouse clicked on it, even if the popup is the active item.

**Comment by ocornut** [comment]
> When the mouse is near an edge of the Checkbox, the Popup flickers intermittently. The flickering goes away when moving the mouse more to the center of the Checkbox.

I don't know. There's probably a problem in your code and I can't guess what it is.

> I'm not able to click on the CheckBox, only the Popup. I'm not sure how say that input should also be able to go to the Checkbox if the mouse clicked on it, even if the popup is the active item.

That defeats the main behavior of popups. If you don't need a popup, use a regular window.

**Comment by Pombal** [comment]
This is the code I use, not sure what can cause the flickering. Approaching the Checkbox with the mouse very carefully will trigger the flickering it but clicking on it will also trigger it more reliably. I'm using version 1.61 btw.

```
            ImGui::Checkbox("Foo", &foo);
            ImGui::PushItemWidth(90);

            bool ishovered = ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenBlockedByPopup);
            if (ishovered)
            {
                ImGui::OpenPopup("context");
            }

            if (BeginPopup("context"))
            {
                if (ImGui::DragInt("##bar", &bar, 0, 1, 8, "%.0f"))
                {
                    // stuff
                }

                ishovered |= IsWindowHovered(ImGuiHoveredFlags_AllowWhenBlockedByActiveItem);
                if (!ishovered)
                {
                    CloseCurrentPopup();
                }

                EndPopup();
            }
```

I said the input should *also* be able to go the Checkbox but that was incorrect, I want it to *only* go to the Checkbox is the mouse is over it but not over the Popup. Is that any easier to achieve? 
If not, how could I go about it using a regular window like you propose? Wouldn't I hit the same input issue but with much more code to try and recreate a popup/tooltip?

**Comment by Pombal** [comment]
I see, I understand now why popups are the wrong approach here.

I'll create my own window that does this behaviour but I believe it could be a good feature for imgui if it was supported. The ideal version I'm imagining would position the popup in a non movable, non resizable way such that you can't have gaps between the checkbox and the popup. That allows for context defined popups that are interactable and don't require a click from the user to see. The checkbox could be used to enable or disable a feature and the popup on hover would be used to further refine options related only to the original element.

Thanks for the help! :)

**Comment by ocornut** [comment]
Well you can position window with SetNextWindowPos(), query the bounding box of the item with GetItemRectMin/Max, and create the window with _NoMove, _AutoResize etc flag. There’s not much to do.

Popups or Menus (which is very close things in dear imgui) are the more standard approach for this. As I said you idea will require to the user moving the mouse precisely, which is error-prone, while menus use more tolerant algorithms.

**Comment by Pombal** [comment]
You are right that it will require more precision from the user but I think if well implemented, it wouldn't be too much burden on the user. Especially if the user is expecting that kind of behaviour.

I've been trying to implement it using Begin() and End() but without much success. I do the Begin() and End() between an IsItemHovered() call but of course then the window does not appear if I'm hovering over the new window but outside the original element. I'd like the new window to be visible if I'm hovering over the original element ( checkbox for example ) or the newly created window but I'm not sure how to do that.

**Comment by ocornut** [comment]
This seems usable:

```
ImGui::Begin("Test #1846");
static bool b = false;
static bool opened = false;
ImGui::Checkbox("Hover me", &b);
bool hovered = ImGui::IsItemHovered();
if (hovered)
    opened = true;
if (opened)
{
    ImGui::SetNextWindowPos(ImVec2(ImGui::GetItemRectMax().x, ImGui::GetItemRectMin().y));
    ImGui::Begin("blah", NULL, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_Tooltip | ImGuiWindowFlags_ChildWindow);
    ImGui::Text("Hello from window 2");
    ImGui::MenuItem("test");
    ImGui::MenuItem("test2");
    if (!hovered && !ImGui::IsWindowHovered())
        opened = false;
    ImGui::End();
}
ImGui::End();
```

With a menu instead:
```
ImGui::Begin("Test #1846 Menu");
ImGui::Checkbox("##Hover me", &b);
ImGui::SameLine();
if (ImGui::BeginMenu("Hover Me"))
{
    ImGui::Text("Hello from window 2");
    ImGui::MenuItem("test");
    ImGui::MenuItem("test2");
    ImGui::EndMenu();
}
ImGui::End();
```
There's an issue where the menu arrow doesn't get adjusted for the text baseline of the current line (should be able to fix that pretty easily).

**Comment by Pombal** [comment]
Yes, the first code is exactly what I was looking for! Just needed to change ImGui::IsWindowHovered() to take AllowWhenBlockedByActiveItem, otherwise I couldn't interact with the item if it was DragInt instead of text, for example.

Your example with menus showed me that indeed, the menu interaction is better for the user, I will probably end up using that instead. Thanks a lot :)

**Comment by ocornut** [comment]
Closing this now.
