### ISSUE TITLE
Counter Clockwise Winding in DirectX 11 

### ISSUE THREAD

**Issue by Epaenetus** [ocornut/imgui#185]
I was wondering if there was a way to enable counter clockwise winding for DirectX 11. As I have it now, I set a different raster state whenever I go to render ImGui. This is not a big issue, but I just wanted to see if there was already support for CCW.

**Comment by ocornut** [comment]
It's not possible. I just assumed that disabling culling would be faster for the GPU anyway, so that's the prefered way of rendering ImGui.
