### ISSUE TITLE
font issue

### ISSUE THREAD

**Issue by aprilnoble** [ocornut/imgui#1852]
Hi, I'm having a issue when I try to change the font from my menu. Can someone spot my mistake here? Thanks! 
And sorry about the "meme" code here lol.

``

ImFont* nigga;

	ImGuiIO& io = ImGui::GetIO();
	nigga = io.Fonts->AddFontFromFileTTF("Tahoma.tff", 9.0f);
	ImGui::PushFont(nigga);
	if (ImGui::Begin(XorStr("Greed"), &g_Options.Menu.Opened, ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse | ImGuiWindowFlags_NoCollapse | G::extra_flags))
	{
		const char* tabs[] = {
			"aimbot",
			"visuals",
			"miscellaneous",
			"skin override"
		};

		for (int i = 0; i < IM_ARRAYSIZE(tabs); i++)
		{

			//ImGui::GetStyle().Colors[ImGuiCol_Button] = ImColor(54, 54, 54, 255);

			if (ImGui::Button(tabs[i], ImVec2(ImGui::GetWindowSize().x / IM_ARRAYSIZE(tabs) - 9, 0)))
				page = i;

			//ImGui::GetStyle().Colors[ImGuiCol_Button] = ImColor(54, 54, 54, 255);

			if (i < IM_ARRAYSIZE(tabs) - 1)
				ImGui::SameLine();
		}

		ImGui::Separator();

		switch (page)
		{
		case 0:
			RenderLegit();
			break;
		case 1:
			RenderVisuals();
			break;
		case 2:
			RenderMisc();
			break;
		case 3:
			RenderSkinChanger();
			break;
		}
		ImGui::End();
	}
}

``

**Comment by ocornut** [comment]
Sorry but #1586.
