### ISSUE TITLE
Crashed with added bitmap fonts when rendering.

### ISSUE THREAD

**Issue by tousuke** [ocornut/imgui#1853]
**Version/Branch of Dear ImGui:**

v1.53

**Back-end file/Renderer/OS:** _(if the question is related to inputs/rendering/build, otherwise delete this section)_

trace : https://pastebin.com/TgeJJ6rW
with DirectX9 and Windows 10

**My Issue/Question:** _(please provide context)_

Hello,excuse me,I have a trouble now.
My program with Dear Imgui have to load a lot of fonts cause it had to support some countries language.
I'm using AddFontFromFileTTF added fonts from .fon font files with enabled MergeMode,
it's only using for some users because some problem with their video card. 
and if call a NewFrame ,it will crash my program.
If load another ttf fonts could be without crash.

I have search a lot and read docs,but I have no idea about it,
maybe I do something wrong...?

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
..
ImGuiIO& io = ImGui::GetIO();
ImFontConfig config;
config.MergeMode = true;
config.OversampleH = 1;
io.Fonts->AddFontDefault();
io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\app932.fon", 16.0f, config, io.Fonts->GetGlyphRangesJapanese());
..
..
ImGui_ImplDX9_NewFrame();
```

Thank you for helping!!

**Comment by sonoro1234** [comment]
perhaps AddFontFromFileTTF is only for TTF but not bitmap fonts?

**Comment by ocornut** [comment]
.fon files are not supported.
When reporting errors please make sure you have asserts enabled, you should have received asserts earlier.

**Comment by tousuke** [comment]
Understood,thank you all for answering!

can I ask a question about it please?
Is there have another way to use more less video memory?
seems over 4 fonts with large glyph range let my user crashed.

Thank you for helping!

**Comment by ocornut** [comment]
You can:
- remove oversampling on both axises
- upload Alpha only textures instead of RGBA
- use the GlyphRangeBuilder and only render glyphs that your software actually needs

**Comment by tousuke** [comment]
Thank you for answering!

I will try it,thank you for helping,really!

Thank you again!
