### ISSUE TITLE
Cursor on textbox index?

### ISSUE THREAD

**Issue by Majed93** [ocornut/imgui#186]
Is it possible to get the index of which the cursor is currently at in a text box?

**Comment by ocornut** [comment]
Currently the only way is a little awkward
- You need to set a callback to the InputText() with ImGuiInputTextFlags_CallbackAlways
It'll call your callback during the function.
In the ImGuiTextEditCallbackData structure you get 'CursorPos'.

It should be possible to add API to retrieve some of the InputText() state more easily if that's needed.

**Comment by Majed93** [comment]
I've already got a callback in my inputText(), ImGuiInputTextFlags_CallbackCharFilter.
This is what i have currently:
ImGui::InputText("", strPlain, IM_ARRAYSIZE(strPlain), ImGuiInputTextFlags_CallbackCharFilter, TextFilters::FilterAZ);

TextFilters::FilterAZ is a struct to enable auto capitalisation.

**Comment by ocornut** [comment]
FilterAZ is a function. Change it so that it provide you with the cursor position as well as doing the capitalisation.

**Comment by Majed93** [comment]
Ok, but how would that get the index of which character in the char array the cursor is currently at?

Example -
ABCDEFGHIJKL

How would it know that the cursor(blinker) is at E so it returns 5 as the index value?

**Comment by ocornut** [comment]
The structure you get passed has a CursorPos integer that gives you that.

**Comment by Majed93** [comment]
So something like
int i = data->CursorPos;

that would give me the index?

**Comment by ocornut** [comment]
Yes..

**Comment by Majed93** [comment]
That always seems to give me 0?

**Comment by ocornut** [comment]
Are you testing EventFlag for ImGuiInputTextFlags_CallbackAlways ?
You won't get the data on a CharFilter event.
Read the description of the 'ImGuiTextEditCallbackData' structure.

**Comment by Majed93** [comment]
I understand now. But i need it to do it for the ImGuiInputTextFlags_CallbackCharFilter event.

**Comment by ocornut** [comment]
Oh you want to fiilter given the position? 

I could provide the info but I need to rewrite the clipboard pasting loop accordingly.

**Comment by Majed93** [comment]
In my text box i've put both flags in now
ImGuiInputTextFlags_CallbackAlways  |   ImGuiInputTextFlags_CallbackCharFilter
So now while it still filters it does the callback and it seems to get the position correctly in the callback struct. Think the only problem i now have is actually getting the int value assigned to a variable in my class

**Comment by ocornut** [comment]
What are you wanting to use the cursor position for ?
Maybe I can figure out an easier way to retrieve.

**Comment by Majed93** [comment]
I simply need to get the index of which the cursor is at when the user erases a character from the text box(box1). I've got another string which i display(box2) which is the encrypted version of the input box. So if i user was to erase a character from the middle of the input box(box1) for example, that corresponding character should be erased in the other string(box2). So essentially they should match. Getting the cursor position would make it easy for me to find which character to erase from that string(box2)

**Comment by ocornut** [comment]
Looks like you should just recreate the content of box2 from the content of box1 every time. Trying to maintain the data following interactions you'd have to handle all possible interactions, it'd be lot of code and it'll be buggy.
InputText() returns true if the data was modified.

**Comment by Majed93** [comment]
Ok, i've got it now, thanks for the help!
