### ISSUE TITLE
TreeNode with icon between arrow and text

### ISSUE THREAD

**Issue by SuperWangKai** [ocornut/imgui#1863]
Can we make tree node like this?
This is the tree node ui from Firefox windows 10. The icon image is between the arrow and text. And I believe it's a common practice.
<img width="175" alt="treenode" src="https://user-images.githubusercontent.com/15721569/41025207-e0255cf6-69a3-11e8-90bc-7a820fdef72c.png">

I tried using an empty TreeNode and a Selectable to achieve this, however, there is disconnection of the mouse interaction between arrow and Selectable, which is confusing for user.

Thanks!

**Comment by ocornut** [comment]
The way we support icons is by mapping them to Unicode point so they are part of the text itself.
See misc/fonts/README for instruction on how to use unicolor icon fonts.
You may also use the CustomRect API to map custom region of the atlas to unicode point and render colorful icons into them yourself.

**Comment by SuperWangKai** [comment]
Brilliant! I'll try it out. I guess I can close the issue.

**Comment by Milerius** [comment]
@SuperWangKai Did you find a convenient solution? if yes can you explain or show a snippet for example ?

**Comment by iOrange** [comment]
> @SuperWangKai Did you find a convenient solution? if yes can you explain or show a snippet for example ?

There's a good example with C++ code in `misc/fonts/README.txt`, check `USING ICONS` section

**Comment by TomieAi** [comment]
it will be nice if they accept ImTextureID as 2nd param on ImGui::TreeNode

**Comment by IniKiwi** [comment]
I want that!
