### ISSUE TITLE
Keyboard Slider Float Tweaks Not Working With Small Range And %.0f Format

### ISSUE THREAD

**Issue by stfx** [ocornut/imgui#1866]
Expected:
Slider should change value when activating slider keyboard input and using arrow keys

Current:
Slider does not change value when activating slider keyboard input and using arrow keys with small range and format being `"%.0f"`

Reproduce:
```c++
float fieldOfView;
ImGui::SliderFloat("fov", &fieldOfView, 80.f, 120.f, "%.0f");
```

Details:
There is code in `ImGui::SliderBehaviorT` like `delta /= 100.0f;    // Gamepad/keyboard tweak speeds in % of slider bounds` which results in step size smaller than 1 with small range and format being `"%.0f"`

My workaround has been to use `ImGui::SliderInt` and casting the values between float and int

**Comment by ocornut** [comment]
Note that holding the arrow keys would work, the float is being modified but there's not enough precision to see it. Near that code I think we should change in `SliderBehaviorT`:


```
if (is_decimal || is_power)
```

With
```
const int decimal_precision = is_decimal ? ImParseFormatPrecision(format, 3) : 0;
if ((decimal_precision > 0) || is_power)
```

To match the old behavior. I'll have to think what other side effect it may have.

**Comment by ocornut** [comment]
Fixed.
