### ISSUE TITLE
Displaying Text Using a For Loop

### ISSUE THREAD

**Issue by AlwaysKamin** [ocornut/imgui#1868]
ImGUI v1.50

I am attempting to list the files that are within a directory. The names of the files are placed into a vector of strings named v. I am just simply attempting to loop through the vector and display the text within a pop-up. This might be a really dumb mistake on my part as its late but I can't for the life of me get the text to display. When I attempt to hard code outside of the loop everything works as you would imagine. But simply putting it into the loop causes nothing to be displayed. Any help would be appreciated and again I am sorry if this is a dumb question. Thanks in advance for the help. 

```
for(int i = 0; i < numberOfFiles; i++){
     ImGui::Text("%s", v[i].c_str());
}
```

<img width="590" alt="screen shot 2018-06-08 at 2 32 23 am" src="https://user-images.githubusercontent.com/8315826/41142722-adc5429a-6ac4-11e8-9181-f8623fd6e819.png">

**Comment by ocornut** [comment]
Well, it's not really a Dear ImGui related problem.
Probably either your value for `numberOfFiles` is incorrect, either the vector itself is incorrect somehow.

You could use a debugger or imgui to visualize your values:
`ImGui::Text("numberOfFiles = %d", numberOfFiles);`

**Comment by AlwaysKamin** [comment]
Yeah, I was really dumb, I caught my issue just now and was coming back to address it. I was forgetting to clear my vectors. That's what I get for working too late. Thank you for such a speedy response as well!
