### ISSUE TITLE
Win32 Mousewheel: Scale input by WHEEL_DELTA

### ISSUE THREAD

**Issue by zx64** [ocornut/imgui#1874]
I find the default mouse wheel implementation a bit too fiddly when using my laptop's trackpad because all wheel inputs are quantised to +1.0 or -1.0.

I've been using this implementation instead:
```
    case WM_MOUSEWHEEL:
    {
        io.MouseWheel += (float)GET_WHEEL_DELTA_WPARAM(wParam)/(float)WHEEL_DELTA;
        return 0;
    }
    case WM_MOUSEHWHEEL:
    {
        io.MouseWheelH += (float)GET_WHEEL_DELTA_WPARAM(wParam)/(float)WHEEL_DELTA;
        return 0;
    }
```

I've tested it on my laptop's (cheap Synaptics) trackpad and my MX518 (discrete scrolling only), so do not know how well this feels for mice with a horizontal wheel or wheels that can freely spin.

Thanks!

**Comment by ocornut** [comment]
This is correct, I'm surprised no one caught this one before. 
I pushed the fix now, thank you!
