### ISSUE TITLE
Source changes very fast?

### ISSUE THREAD

**Issue by Tim4135** [ocornut/imgui#1876]
I'v been using ImGui for quite a while, and I keep creating new projects with it where I redownload ImGui each time.
I noticed that ImGui changes lot and very fast, is that temporarily a temporarily thing? Or will it keep changing very fast?
WIth changing I mean the things like initializing and examples. It's very annoying if I have to relearn an re-study ImGui every update(which seems to happen every day).
So what's up with that?

**Comment by ocornut** [comment]
ImGui will keep evolving. However all the changes are logged in ChangeLog and apart from the "API Breaking Changes" (also precisely documented) they should not affect you much. It's not really a case of "relearning".

> WIth changing I mean the things like initializing and examples.

There was a major refactor of the examples pushed to the repository a few days ago. This is exceptional and for the good. However the old bindings will also perfectly work with the current version. 

If you are not confident with handling this, you can choose and lock the version you are using. Some people choose to rarely update. Some people (who are maybe agile and experimented) are happy to update very regularly, as the incremental changes are easy to follow.

**Comment by Tim4135** [comment]
Okay, thanks. I will just stick with a certain version and update once in a while unless there is a new feature or something.
That reminds me, have you managed to add tabs support?
And is it possible to do UE4 like line drawing for nodes?

**Comment by ocornut** [comment]
> That reminds me, have you managed to add tabs support?

Not yet.

> And is it possible to do UE4 like line drawing for nodes?

You can build them yourself with some effort. See #306
