### ISSUE TITLE
DXGI_FORMAT_R8_UNORM texture renders as red in D3D11

### ISSUE THREAD

**Issue by ewan-b** [ocornut/imgui#1877]
----

**Version/Branch of Dear ImGui:**
Master

**Back-end file/Renderer/OS:**
imgui_impl_dx11
imgui_impl_win32

**My Issue/Question:** _(please provide context)_
I have made minor modifications to the D3D11 win32 sample app to display images loaded from disk. Greyscale textures with format DXGI_FORMAT_R8_UNORM are drawn as red in this version. This is a known issue with D3D11 where previous versions implicitly added the .rrr swizzle. It can be fixed by changing:
```
float4 out_col = input.col * texture0.Sample(sampler0, input.uv);
```
to
```
float4 out_col = input.col * texture0.Sample(sampler0, input.uv).rrra;
```
in the pixel shader, but obviously this then breaks it for any colour textures.

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
// Assuming pData points to single channel 8-bit image data with width nWidth and height nHeight

// Set up texture description
D3D11_TEXTURE2D_DESC desc;
ZeroMemory(&desc, sizeof(desc));
desc.Width			= nWidth;
desc.Height			= nHeight;
desc.MipLevels		= 1;
desc.ArraySize			= 1;
desc.Format			= DXGI_FORMAT_R8_UNORM;
desc.SampleDesc.Count	= 1;
desc.SampleDesc.Quality	= 0;
desc.Usage				= D3D11_USAGE_DEFAULT;
desc.BindFlags			= D3D11_BIND_SHADER_RESOURCE;
desc.CPUAccessFlags		=  0;

// Set up initial data description for the texture
CHECKPOINT();
D3D11_SUBRESOURCE_DATA initData;
ZeroMemory(&initData, sizeof(initData));
initData.pSysMem			= pData;
initData.SysMemPitch		= nDataSize / nHeight;
initData.SysMemSlicePitch	= nDataSize;

// Create the texture
ID3D11Texture2D pTexture = nullptr;
g_pd3dDevice->CreateTexture2D(&desc, &initData, &pTexture));

// Create a view of the texture
ID3D11ShaderResourceView pView = nullptr;
g_pd3dDevice->CreateShaderResourceView(pTexture, nullptr, &pView);

// Draw image
ImGui::Begin("Top", &show_top, ImGuiWindowFlags_NoTitleBar);
ImGui::Image(pTexture, ImVec2(364, 512), ImVec2(0, 0), ImVec2(1, 1));
ImGui::End();
```

**Screenshots/Video**
![imguired](https://user-images.githubusercontent.com/40206779/41295763-4613f410-6e53-11e8-9f5d-365860bd4891.png)

**Comment by ocornut** [comment]
Hello,

> but obviously this then breaks it for any colour textures.

Then it's not appropriate to be committed as it, because color textures are way more common that single-channel ones.

The usual ways to approach that are:
- If you want to `ID3D11ShaderResourceView*` as the data to store in ImTextureID, you may use render callback to pass information to the renderer (here, you may want to use a callback to change the current shader).
- If you have a higher-level engine you may want to replace using `ID3D11ShaderResourceView*` with using a higher-level type that give information about the texture as well as the way to display it. 

I don't really know DirectX11, but wouldn't specifying a format using a `D3D11_SHADER_RESOURCE_VIEW_DESC` parameter to `CreateShaderResourceView()` also allow that? (That's just a guess, I don't know graphics API very much).

**Comment by ewan-b** [comment]
Easiest solution was to add an additional pixel shader for greyscale textures and switch between them. Pixel shader was defined in imgui_impl_dx11.cpp immediately after creating the original pixel shader:
```
// Create the greyscale pixel shader
{
	static const char* pixelShader =
	"struct PS_INPUT\
            {\
            float4 pos : SV_POSITION;\
            float4 col : COLOR0;\
            float2 uv  : TEXCOORD0;\
            };\
            sampler sampler0;\
            Texture2D texture0;\
            \
            float4 main(PS_INPUT input) : SV_Target\
            {\
            float4 out_col = input.col * texture0.Sample(sampler0, input.uv).rrra; \
            return out_col; \
            }";

	D3DCompile(pixelShader, strlen(pixelShader), NULL, NULL, NULL, "main", "ps_4_0", 0, 0, &g_pPixelShaderGreyscaleBlob, NULL);
	if (g_pPixelShaderGreyscaleBlob == NULL)  // NB: Pass ID3D10Blob* pErrorBlob to D3DCompile() to get error showing in (const char*)pErrorBlob->GetBufferPointer(). Make sure to Release() the blob!
		return false;
	if (g_pd3dDevice->CreatePixelShader((DWORD*)g_pPixelShaderGreyscaleBlob->GetBufferPointer(), g_pPixelShaderGreyscaleBlob->GetBufferSize(), NULL, &g_pPixelShaderGreyscale) != S_OK)
		return false;
}
```

Then replace the texture bind and draw call inside ImGui_ImplDX11_RenderDrawData as follows:
```
// Bind texture, Draw
ID3D11ShaderResourceView* pTextureView = (ID3D11ShaderResourceView*)pcmd->TextureId;
if (pTextureView)
{
	D3D11_SHADER_RESOURCE_VIEW_DESC desc;
	pTextureView->GetDesc(&desc);
	switch (desc.Format)
	{
		case DXGI_FORMAT_R8_UNORM:
		case DXGI_FORMAT_R8_UINT:
		case DXGI_FORMAT_R8_SNORM:
		case DXGI_FORMAT_R8_SINT:
			ctx->PSSetShader(g_pPixelShaderGreyscale, NULL, 0);
			bGreyscaleShader = true;
			break;

		default:
			if (bGreyscaleShader)
			{
				ctx->PSSetShader(g_pPixelShader, NULL, 0);
				bGreyscaleShader = false;
			}
			break;
	}
}
ctx->PSSetShaderResources(0, 1, &pTextureView);
ctx->DrawIndexed(pcmd->ElemCount, idx_offset, vtx_offset);
```
This also requires the bGreyscaleShader boolean variable to be declared outside the loop and initialised to false.

**Comment by ocornut** [comment]
I would write this using something like:

```
ID3D11PixelShader* current_shader = NULL;

ID3D11PixelShader* expected_shader = NULL;
switch (..)
{
   ... expected_shader = g_pPixelShaderXXX;
}

if (current_shader != expected_shader)
{
   ctx->PSSetShader(g_pPixelShader, NULL, 0);
   current_shader = expected_shader;
}
```

**Comment by ewan-b** [comment]
Yes, that seems like a sensible refinement. Thanks.
