### ISSUE TITLE
Turkish Characters

### ISSUE THREAD

**Issue by emreires** [ocornut/imgui#1880]
How can display turkish characters in imgui?

**Comment by ocornut** [comment]
Hello,
You need to load a font with the glyph ranges used for Turkish (I think just loading 0x0020 to 0x01FF should be enough if your have the right font).
Please read misc/fonts/README.txt

**Comment by emreires** [comment]
I have right font but it doesnt work :/

**Comment by emreires** [comment]
Can you give example source code?

**Comment by ocornut** [comment]
Apologies, I gave you the wrong answer. The right answer is: Sorry but #1586.

**Comment by emreires** [comment]
:D uh, no.

I'm not a paster or cheater.
Im doing a simple 2d game, lol

**Comment by ocornut** [comment]
Please read the documentation. If you say something doesn't work, please provide proper repro code. We can't help you if we don't know what you have tried.

- load a font that contains turkish characters
- when loading the font you need to specify the glyph range
- use the style editor, inside "fonts" to confirm that the glyphs you need are loaded
- make sure you pass utf-8 strings, which you can do in C++11 by using `u8"Selam Dünya"`

**Comment by drbiricik** [comment]
Example Turkish Font Use :
![Turkish Font Use](https://pasteboard.co/Hw6UR8v.png)

**Comment by Flix01** [comment]
@drbiricik: Not sure if this can help you, but for all these kind of problems, I'd also make sure that all the source files I'm using are saved using the UTF8 encoding.

I don't know what's the default encoding in Turkey (probably UTF8 already) so I don't know if this can help you or not! :unamused: 

Also I think you should add the code you're using to display the text...

**Comment by ice1000** [comment]
No, @Flix01 this is not related to encodings -- his encoding is correct.

**Comment by Flix01** [comment]
@Ice1000: OK then...

**Comment by ocornut** [comment]
String literals in c++ needs to be prefixed with u8 to be encoded as utf-8.

So “xxx” should be u8”xxx”.
Otherwise the exact encoding would be determined by the compiler and probably follow a local codepage which is not the same as utf-8 encoding.

**Comment by drbiricik** [comment]
it worked. thank you.

**Comment by revengecommando** [comment]
> Can you give example source code?

Emre reis yapabildiysen banada kodu yazarmısın?

**Comment by emreires** [comment]
> > Can you give example source code?
> 
> Emre reis yapabildiysen banada kodu yazarmısın?

Stringi yazdırırken 

"yazdıracağımız yazı"

bu şekilde değil aşağıda yazdığım şekilde yazdır:

u8"yazdıracağımız yazı"

UTF8 encodesi ile türkçe karakterler problemsiz bir şekilde görünür olacaktır.

İyi çalışmalar.

**Comment by emreires** [comment]
> > Can you give example source code?
> 
> Emre reis yapabildiysen banada kodu yazarmısın?

Yardım gerekiyorsa ekleyebilirsin, anladığım kadarıyla oyun camiasındasın.
Discord: Vortéx!#3643

**Comment by emrecpp** [comment]
static const ImWchar icons_ranges_Turkish[] = { 
	0x0020, 0x00FF, // Basic Latin + Latin Supplement
0x00c7, 0x00c7, // Ç
0x00e7, 0x00e7, // ç
0x011e, 0x011e, // Ğ
0x011f, 0x011f, // ğ
0x0130,  0x0130,// İ
0x0131, 0x0131, // ı
0x00d6, 0x00d6, // Ö
0x00f6, 0x00f6, // ö
0x015e, 0x015e, // Ş
0x015f, 0x015f, // ş
0x00dc, 0x00dc, // Ü
0x00fc, 0x00fc, // ü

0, };
	io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\arial.ttf", 16.0f,0, icons_ranges_Turkish);
			ImGui::Text((const char*)u8"\u00c7 \u00e7  \u0130  İŞÇĞ Emre Demircan");

**Comment by emrecpp** [comment]
static const ImWchar icons_ranges_Turkish[] = { 
0x0020, 0x00FF, // Basic Latin + Latin Supplement
0x00c7, 0x00c7, // Ç
0x00e7, 0x00e7, // ç
0x011e, 0x011e, // Ğ
0x011f, 0x011f, // ğ
0x0130, 0x0130,// İ
0x0131, 0x0131, // ı
0x00d6, 0x00d6, // Ö
0x00f6, 0x00f6, // ö
0x015e, 0x015e, // Ş
0x015f, 0x015f, // ş
0x00dc, 0x00dc, // Ü
0x00fc, 0x00fc, // ü

0, };
io.Fonts->AddFontFromFileTTF("C:\Windows\Fonts\arial.ttf", 16.0f,0, icons_ranges_Turkish);
ImGui::Text((const char*)u8"\u00c7 \u00e7 \u0130 İŞÇĞ Emre Demircan github:emrecpp");

**Comment by emartisoft** [comment]
if you are using vs c++ compiler than instead of u8 string literal can also use this.

``` cpp
#pragma execution_character_set("utf-8")
....
 ImGui::Button("Tıkla bakalım öçşiğüÖÇŞİĞÜ");
....
```

``` cpp
// from @emrecpp 
static const ImWchar icons_ranges_Turkish[] = {
0x0020, 0x00FF, // Basic Latin + Latin Supplement
0x00c7, 0x00c7, // Ç
0x00e7, 0x00e7, // ç
0x011e, 0x011e, // Ğ
0x011f, 0x011f, // ğ
0x0130, 0x0130,// İ
0x0131, 0x0131, // ı
0x00d6, 0x00d6, // Ö
0x00f6, 0x00f6, // ö
0x015e, 0x015e, // Ş
0x015f, 0x015f, // ş
0x00dc, 0x00dc, // Ü
0x00fc, 0x00fc, // ü

0, };
io.Fonts->AddFontFromFileTTF("C:\Windows\Fonts\arial.ttf", 16.0f,0, icons_ranges_Turkish);
```
