### ISSUE TITLE
Combo Colour?

### ISSUE THREAD

**Issue by emreires** [ocornut/imgui#1881]
Can I change only combo box colour?

**Comment by ocornut** [comment]
You can use anything between BeginCombo and EndCombo, including PushStyleCol/PopStyleCol.

**Comment by emreires** [comment]
http://prntscr.com/jv2ohx

Here. I want change this red button.

**Comment by ocornut** [comment]
You can use PushStyleCol/PopStyleCol. Read and study the ShowDemoWindow() function and imgui.h.

**Comment by emreires** [comment]
ImGuiCol_ComboButton

I need like this ^^.

I want change color combobox button :)

**Comment by Darky-Lucera** [comment]
I need a way to change the color of the label (only the label) of a combo:
 - ImGuiCol_Label or ImGuiCol_TextLabel or ImGuiCol_LabelText 

Is it possible?

**Comment by ocornut** [comment]
@Darky-Lucera Just hide the label (read FAQ about label/id) and use a TextColored.

**Comment by Darky-Lucera** [comment]
Thanks!
