### ISSUE TITLE
Optional Histogram bar labels

### ISSUE THREAD

**Issue by TurkeyMan** [ocornut/imgui#1882]
**Version/Branch of Dear ImGui:**

b5d38...

**My Issue/Question:** _(please provide context)_

I'm rendering histograms, which receive an array of samples.
Hovering reveals the sample index and the value.
I'd really like it if the function received an additional optional arg that was a list of string labels for each sample, where the label is presented in the hover info instead of the index.

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```c++
float arr[] = { 0.6f, 0.1f, 1.0f };
const char* labels[] = { "a", "b", "c" };
ImGui::PlotHistogram("Histogram", arr, IM_ARRAYSIZE(arr), 0, NULL, 0.0f, 1.0f, ImVec2(0, 80), labels);
```

**Comment by ocornut** [comment]
Hello @TurkeyMan,

I think we need to redesign the Plot api, there are too many desirable features and just stashing additional parameters isn't going to cut it. In this situation, being able to query the index of the hovered sample would be preferable perhaps.

For now my suggestion would be to copy and recreate a custom PlotHistogram() on your side of the code (you'll need to `#include "imgui_internal.h"). It is a reasonably small function and you can easily tweak it and redefine it's signature.

This feature is definitively among the things we ought to solve with a V2 of plots.

-Omar

**Comment by TurkeyMan** [comment]
Thanks @ocornut, I'll take a look.

Looking forward to a feature-rich V2! :P

**Comment by ocornut** [comment]
Thanks for your patience :) Closing this for now.
