### ISSUE TITLE
Context menu attached to a tree node

### ISSUE THREAD

**Issue by MontyBlenheim** [ocornut/imgui#1883]
I have a treeItem and I want to add a context menu to allow adding further child nodes.
With the following code, I can open a right click menu for the tree node, however it will open anywhere in the window that the treenode exists.

```
if( ImGui::TreeNode( "uniqueLabel" ) )
{
    ImGui::TreePop();
}

ImGui::PushID("uniqueLabel");
if (ImGui::BeginPopupContextWindow("Context Menu"))
{
    ImGui::EndPopup();
}
ImGui::PopID();
```

I tried wrapping it in an IsItemHovered("uniqueLabel") which correctly meant I could only open a context menu when right clicking on the tree node, but as soon as I moved to the context menu, I was no longer hovering on the tree item and so the menu closed.

An obvious solution would be to store some state about if the menu is open, but imgui is meant to be stateless. I'm wondering what the correct 'imgui' way of achieving this is?

**Version/Branch of Dear ImGui:**

dear imgui, v1.52 WIP

**Comment by ocornut** [comment]
You can use `BeginPopupContextItem()` exactly for this.

```
bool open = ImGui::TreeNode("...");
if (ImGui::BeginPopupContextItem())
{
   // your popup code
   ImGui::EndPopup();
}
if (open)
{
   // your tree code stuff
   ImGui::TreePop();
}
```

The only gotcha if that you want to execute the contents inside the TreeNode after calling BeginPopupContextItem, as `BeginPopupContextItem()` uses the last submitted item.

**Comment by MontyBlenheim** [comment]
Brilliant, that worked perfectly! Can't believe I missed the Item version. I went for a slightly different layout:

```
bool open = false;
if( ImGui::TreeNode("...") )
{
    // tree code
}

// Need this since there are multiple tree nodes, and it seems to repeat the content without it
ImGui::PushID("...");
if (ImGui::BeginPopupContextItem())
{
   // your popup code
   ImGui::EndPopup();
}
ImGui::PopID();

if (open)
   ImGui::TreePop();
```

Thanks again!

**Comment by ocornut** [comment]
`BeginPopupContextItem()` without parameter picks the ID of the last item, so assuming your `TreeNode()` all have unique ID - which is a requirement for then to open and close properly - you shouldn't need the PushID/PopID() there, you already dodged the ID collision with the TreeNode parameters.

**Comment by MontyBlenheim** [comment]
Is it possible that’s a newer imgui feature? My version doesn’t allow that function without a parameter and a quick glance at the code shows it doesn’t check for empty strings to do some lookup.

**Comment by ocornut** [comment]
> Is it possible that’s a newer imgui feature? 

Correct. Sorry I glanced at your version number, because 1.52 WIP is so visually close to the current version 1.62 WIP I wrongly assumed you were on latest master. Your solution will work if you don't want to upgrade, but I would advise to try updating at some point :)

**Comment by MontyBlenheim** [comment]
Cool. Yeah I plan on updating soon. Thanks for the timely and helpful response :)
