### ISSUE TITLE
Induce a redraw/new-frame/event to compensate for need to  differentiate between Mouse click vs dragging?

### ISSUE THREAD

**Issue by pvtinflex** [ocornut/imgui#1884]
UPDATE:  I had a coffee and reworked things a bit;  I now make the default context menu come up with MouseClick(), *but* I monitor to see if IsMouseDragging() becomes true with IsMouseDown(), and if so I close the context menu and change to the rubber-band box select mode; as such, there's a short moment where the context is visible but it is insignificant; most definitely not a problem compared to the prior behaviour where the context menu would not come up until the next event/frame.

------------------Original question--------------------
Maybe I'm just not coding things right, but I'm having troubles getting my code to differentiate between MouseClick(1) and IsMouseDragging(1).

If it's just clicked (no dragging) I want to bring up a context menu ( that works fine ), but if I drag I want it to do something else (rubber-band box selection, and that works fine too).

To avoid the context menu coming up when trying to drag-select, I changed MouseClicked(1) to MouseReleased(1) and that works because I can see if the mouse was dragging while it was "down" and opt to not show the context menu, *except* that now the context menu won't actually show until the next frame, ie the mouse is moved, which seems like a minor thing until you try use it in real life and it's a bit confusing/disorientating.

After all that, I'm wondering, is there a way I can induce/invoke ImGui to generate a new frame explicitly with a dummy event to result in a proper drawing of the "ghost" context menu?  Not sure if this is akin to asking for a GOTO in coding, but at the moment I'm feeling a bit out of ideas how to make this work.

**Comment by ocornut** [comment]
> except that now the context menu won't actually show until the next frame, ie the mouse is moved,
[...]
> is there a way I can induce/invoke ImGui to generate a new frame
[...]
> Not sure if this is akin to asking for a GOTO in coding

Sorry I don't understand much of this post (particularly confusing quotes above), even after your edit/update. 
The `BeginPopupContextItem()` functions use `IsMouseReleased()` exactly to allow this sort of thing. 
Standard context menus in window do the same thing and react pretty much on `IsMouseReleased()`.

**Comment by pvtinflex** [comment]
Apologies @ocornut - my code is a mess here and I think it's going to take a few more coffee shots to sort it out.  Somehow I've managed to cut-paste a dreadful mash of things.

What matters though is that it's working again, but I think it's going to need more refactoring.  You can genuinely ignore this thread, in fact, might be best if I just remove it.
