### ISSUE TITLE
Rendering existing game into imgui window

### ISSUE THREAD

**Issue by wrymn** [ocornut/imgui#1885]
Hi,

we have existing java framework for creating games (runs on OpenGL & GLWF). We are planning on making editor for our framework, that will run on top of our game.

My question is, how could we accomplish running imgui window and rendering our framework`s game inside imgui window? 
I can get window context ID that framework created. Can I use it to render it to texture or pass it into your window? (via imgui::begin())

We want to accomplish something like this:

![image](https://user-images.githubusercontent.com/12801017/41505919-6babce14-7213-11e8-936f-7803fca2dc1f.png)

Is this even possible without altering rendering core of our framework?

**Comment by ocornut** [comment]
You can render to texture and then use this texture in imgui with eg ImGui::Image().

**Comment by wrymn** [comment]
Thank you @ocornut for the reply.

I have little experience with OpenGL. I have not found any way how to render to texture, having only OpenGL Window Context ID. Is it possible?

**Comment by ocornut** [comment]
It’s possible but here isn’t the place to discuss OpenGL programming topics. You can look it up I’m sure there are several OpenGL tutorials and documentation leading you to it.
