### ISSUE TITLE
Cursor Y offset on Linux SDL

### ISSUE THREAD

**Issue by KammutierSpule** [ocornut/imgui#1886]
**Version/Branch of Dear ImGui:**
v1.62 WIP, latest master branch update...

**Back-end file/Renderer/OS:**
Linux Mint, Cinnamon 3.6.7
SDL: 2.0.25

**My Issue/Question:**
I just build the example_sdl_opengl 2 and 3 and I am experience an Y offset in the cursor.
I did some debugging, it reports at the begin of the top (first draw pixel) that y position is 28.
The window is created with Height=720
while debugging:
SDL_GetWindowSize(window, &w, &h);
SDL_GL_GetDrawableSize(window, &display_w, &display_h);

it reports h = 716 on both h and display_h

if I build the example_glfw_opengl3 the cursor works OK.
if I set io.MouseDrawCursor = true; it works OK (but I guess it is expected)

**Standalone, minimal, complete and verifiable example:**
I am building the examples:
example_sdl_opengl2 (btw, there is a issue in Makefile, missing a -I../ on Linux )
example_sdl_opengl3

**Comment by ice1000** [comment]
Same issue here. Stably reproduce

**Comment by ocornut** [comment]
Hello,

I cannot repro the rendering issue under Windows so a fix or less ambiguous information would be appreciated. Trying a more recent version of SDL and/or other GPU drivers may make a difference too.

I fixed the Makefile.

**Comment by ice1000** [comment]
Now seems that it's Linux only.

**Comment by KammutierSpule** [comment]
I just installed SDL from repository (2.0.8) and built it again, both sdl examples now work ok!
I looked in libsdl documentation searching for release notes and bug fixes but I get lost, so I couldn't find the exact version that fixed this issue.

**Comment by ice1000** [comment]
Oh, so we should blame sdl... :laugh:

**Comment by andrejlevkovitch** [comment]
About uncorrected mouse position (sorry my English please) - I had this problem too. How I can think in sdl-204 (and less) in function SDL_GetWindowPos takes coordinates with titlebar. So when in imgui_impl_sdl.cpp:230 it calculate coordinates for imgui we have uncorrect value, which less then right value on size of titlebar. 
![screenshot from 2018-10-28 20-39-57](https://user-images.githubusercontent.com/29674023/47619860-4d62dc00-daf4-11e8-8655-bcf6f2c7bc94.png)
![screenshot from 2018-10-28 20-39-17](https://user-images.githubusercontent.com/29674023/47619861-4d62dc00-daf4-11e8-8a28-32805dc2782d.png)
