### ISSUE TITLE
how can i make buttons greyed out and unclickable in imgui? is there any flag or built in function for that ? 

### ISSUE THREAD

**Issue by zahirzohair** [ocornut/imgui#1889]
You may use the Issue Tracker to ask for help and submit bug reports, feature requests or suggestions. 

PLEASE CAREFULLY READ THIS DOCUMENT before doing so:
[CONTRIBUTING.md](https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md).

SELECT "PREVIEW CHANGES" TO TURN THE URL ABOVE INTO A CLICKABLE LINK.

(Delete everything above this section before submitting your issue. Please read the CONTRIBUTING.md file!)

----

**Version/Branch of Dear ImGui:**

XXX

**Back-end file/Renderer/OS:** _(if the question is related to inputs/rendering/build, otherwise delete this section)_

XXX

**My Issue/Question:** _(please provide context)_

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
See #211 (mostly the lower posts).

There is a function `ImGui::PushItemFlag(ImGuiItemFlags_Disabled, true);` in the imgui_internal.h (non-public) API which you may use. It's however not finished and doesn't affect visuals at all, so the widgets won't become grey.

Currently you may do something like that:
```
    static bool disabled = false;
    ImGui::Checkbox("Disable", &disabled);
    if (disabled)
    {
        ImGui::PushItemFlag(ImGuiItemFlags_Disabled, true);
        ImGui::PushStyleVar(ImGuiStyleVar_Alpha, ImGui::GetStyle().Alpha * 0.5f);
    }
    [...]
    if (disabled)
    {
        ImGui::PopItemFlag();
        ImGui::PopStyleVar();
    }
```

PS: Next time you post something please fill in the issue as requested by the issue template.

**Comment by ocornut** [comment]
For cross referencing, we added PushDisabled/PopDisabled in imgui_internal.h today:
https://github.com/ocornut/imgui/issues/211#issuecomment-857704649

**Comment by JC3** [comment]
Is there any non-internal way to do this these days or is it still the same techniques described above?

I'm using the Python bindings from `pyimgui` and they don't expose any of the internal stuff, so I'm looking for other ways to disable buttons using the public API.

**Comment by ocornut** [comment]
BeginDisabled()/EndDisabled() was added to public API n 1.84.

**Comment by JC3** [comment]
Cool thanks I'll raise an issue on pyimgui to expose it.
