### ISSUE TITLE
DragFloat default is very wide

### ISSUE THREAD

**Issue by Extrawurst** [ocornut/imgui#189]
see the following screenshot:
![screen shot 2015-04-09 at 14 27 22](https://cloud.githubusercontent.com/assets/776816/7066618/ab894934-dec4-11e4-8746-a0da307d9f0c.png)

these are three DragFloat() entrys side by side using SameLine() but they are very wider even though the value hardly every needs this much space, is it possible to give DragFloat a specific size that the label gets centered in and clipped?

**Comment by ocornut** [comment]
Hi,

Currently it follows the same settings as the other widgets (and I want to come back to those settings soon*). I wonder if it would make more sense if DragFloat as a different size by default but I'm not sure how to express that yet, adding too many parameters is an issue and we're still debating DragFloat in #180 suggesting optional reference bounds that you can bypass would be useful.

For now,
If you PushItemWidth(100) you'll get a frame 100 pixels wide.
The default is ItemWidth = WindowWidth * 0.65
You can also use ItemWidth = -100; to align to the right side of a window.

* My plan is to globally rewrite the size settings. Possibly include a way to set the width/size of 1 or more items in advance without require a Push/Pop. And provide a lot more options to allow other configuration such as label-widget, label\nwidget, widget-label.

**Comment by Extrawurst** [comment]
Thanks for the hint, `PushItemWidth(100)` was exactly what i was looking for!

By the way, this application is using imgui wrapped in a c-api (https://github.com/Extrawurst/cimgui) that i wrote to be able to use imgui in the D programming language (https://github.com/Extrawurst/DerelictImgui):

![screen shot 2015-04-09 at 14 49 04](https://cloud.githubusercontent.com/assets/776816/7066957/a67b707c-dec7-11e4-9c5e-ccd619231d99.png)

**Comment by Extrawurst** [comment]
Another question arising: You see my usage of Bullet()+SmallButton() for the leaf-items of my tree in the left window to be able to recognize clicks on items there. my question is, is there a cleaner way, some way that does not looks so much like a button but gives me feedback if the user clicked on it ? Text() does not give me feedback, even IsItemActive() together with those Text()/BulletText() elements does not work...

**Comment by ocornut** [comment]
You can use Selectable(label, false) which will return true on click.
Or pass true if you know a given item is selected.
I suppose we could add a TextButton() helper that doesn't have the "width filling" behaviour of expandable not the "selected" parameter.

About cimgui (nice!) I just posted some notes here https://github.com/Extrawurst/cimgui/issues/1

**Comment by ocornut** [comment]
Another possibility would be to modify the style of the button, e.g.

```
ImGui::PushStyleCol(ImGuiCol_Button, ImColor(0,0,0,0));
ImGui::Button
ImGui::PopStyleCol()
```
But that's a bit verbose and maybe you want to wrap it.

**Comment by Extrawurst** [comment]
Selectable was the route i took, works great, now that i can visualize the selected leaf in the tree the fact that u can also select a node makes me wanna highlight a TreeNode that is currently selected. let me guess - only possible using the PushStyle stuff ?

**Comment by ocornut** [comment]
Not directly possible at the moment.

Maybe with a mix of TreeNode/SameLine/Selectable but it'll be not obvious. There's probably a missing middle-ground new function to be added here but I need to think about it a bit more thoroughly rather than not adding one new API. Perhaps splitting TreeNode() into lower-level helpers would be more flexible.

**Comment by Extrawurst** [comment]
I see, no problem. should i make a fresh issue for that to be able to track it?

**Comment by ocornut** [comment]
Yes please, and I close this one :)
