### ISSUE TITLE
Listing 1000’s of images in an imGUI listbox 

### ISSUE THREAD

**Issue by bayesianio** [ocornut/imgui#1891]
Dear all,
I am trying to do the following, everything should be triggered by a UI:

1. Let a user select a directory
2. Populate a UI element with a list of image names in that directory; it is possible that there are 1000’s of images.
3. Upon clicking an image name in that UI element with the mouse / or alternatively scrolling with the keyboard , display the image.

I saw the dirListExample in OpenFrameworks, however it only loads a limited number of images and does not utilize a UI element.

![2018-06-20 10_35_50-window](https://user-images.githubusercontent.com/36111600/41646267-000e05e4-747c-11e8-9b0d-e4a169df454d.png)

**Comment by ocornut** [comment]
Hello,

I don't understand what the question is here. Have you checked the imgui demo code and already used imgui? Please do a little research there.

You may e.g. create a child window on the left and output Selectable() into it. If you have 1000+ elements and want to save a bit of CPU you can use ImGuiListClipper to only output the Selectable that are visible on screen.

You can display images with e.g. `ImGui::Image()` or lower-level `ImDrawList::AddImage()`. Loading/streaming textures would be your responsibility here and has not much relation to what Dear ImGui does. The handling of textures in imgui is typically confusing to new users, I would suggest asking on openFramework community about how to do this.
