### ISSUE TITLE
How to have a window always behind all others?

### ISSUE THREAD

**Issue by bsenftner** [ocornut/imgui#1892]
Dear ImGui: verion 1.61

How to have a window always behind all others?

I have a property viewer & editor, where many of the fields require a popup styled window to contain their large editing contents. I currently have my win32 application frame creating an ImGui window filling that frame, which I use ImGui to render hover and click activated items (mostly text). Like a desktop, I'd like this full-application sized ImGui window to be active, but always in the back. 

Due to the size of each data field, I would like to use ImGui Windows for each field's editor. 
I would like a user to be able to click on more than one field of the "property viewer back window" and see and operate more than one field editor floating above at a time. This is necessary to view and copy partial text between different field editors. 

Currently, using one ImGui window as a field editor, any click on the back property viewer window causes the property viewer window to move to the front, and the field editor window is lost for good behind the property viewer window. 

I would like the back window, the all properties viewer, to accept and respect mouse hovers/clicks & key input, while any number of additional ImGui field editor windows are always on-top-of the property viewer, and sorting focus between themselves with their last interaction. 
 
Is this possible? 
```
bool CX_videoAdminPane::ImguiTextEditPopup(const char* popupId, char* text_buff, const size_t edit_buff_size,
																				 ImVec2& popupSize, bool& show_flag, bool& old_show_flag )
{
	bool ret = false, weAreNew = false;
	ImVec2 edit_frame_size;

	if (show_flag)
	{
		// only set window size if we are just popping the window for first time
		if (show_flag != old_show_flag && old_show_flag == false)
		{
			ImGui::SetNextWindowSize(popupSize);
			old_show_flag = show_flag;
			weAreNew = true;
		}

		// yeah, it's a window now, ImGuiPopups end when clicked outside
		if (ImGui::Begin(popupId))
		{
			ImGui::PushStyleColor(ImGuiCol_Text, m_imgui_text_edit_color);

			if (weAreNew)
			{
				edit_frame_size = popupSize;
			}
			else
			{
				edit_frame_size = ImGui::GetWindowContentRegionMax();
			}
			edit_frame_size.x -= (ImGui::GetStyle().FramePadding.x / 2);
			edit_frame_size.y -= (ImGui::GetTextLineHeightWithSpacing() * 3.0f);

			ImGui::InputTextMultiline("##", text_buff, edit_buff_size, edit_frame_size, ImGuiInputTextFlags_AllowTabInput);
			
			ImGui::NewLine();
			ImGui::SameLine(edit_frame_size.x - 130.0f*2.0f);

			if (ImGui::Button("Cancel", ImVec2(120, 0)))
			{
				show_flag = false;
				old_show_flag = false;
			}

			ImGui::SetItemDefaultFocus();
			ImGui::SameLine(edit_frame_size.x - 125.0f);

			if (ImGui::Button("Save", ImVec2(120, 0)))
			{
				show_flag = false;
				old_show_flag = false;
				ret = true;
			}

			ImGui::PopStyleColor();
		}
		ImGui::End();
	}

	return ret;
}
```

**Comment by ocornut** [comment]
Hello Blake,

Have you tried the `ImGuiWindowFlags_NoBringToFrontOnFocus` window flag?
It doesn't do exactly that you are asking, but in many (most?) situation this effectively provide the desired thing. An appearing window with this flag will be moved at the back of the window list, and subsequent click/focus on the window won't move it to the front.

(Later on would investigate finer control of window ordering e.g. #983, #1328, but this is not possible at the moment).

Omar

**Comment by bsenftner** [comment]
Hi Omar,

That was it, it works exactly as I describe with ImGuiWindowFlags_NoBringToFrontOnFocus. I'm not sure why I ignored that flag, but it's the ticket to a desktop-like back window. Thank you!

-Blake

**Comment by ocornut** [comment]
Great to hear :)
