### ISSUE TITLE
AlwaysAutoResize window not resized on first call.

### ISSUE THREAD

**Issue by sc00ter** [ocornut/imgui#1893]
master branch

Nothing is drawn the first time this is called, unless ImGui::SetNextWindowSize(...) is called prior to Begin().  
```
ImGui::NewFrame();
ImGui::SetNextWindowPos(ImVec2(x, y), ImGuiCond_Always);
ImGui::Begin("", nullptr,  
  ImGuiWindowFlags_NoMove|ImGuiWindowFlags_NoTitleBar
  |ImGuiWindowFlags_NoResize|ImGuiWindowFlags_AlwaysAutoResize
  |ImGuiWindowFlags_NoSavedSettings
  |ImGuiWindowFlags_NoFocusOnAppearing
  |ImGuiWindowFlags_NoNav); 
ImGui::Text("%s", text);
ImGui::End();
ImGui::EndFrame();
ImGui::Render();
auto dd = ImGui::GetDrawData();

assert(dd->TotalVtxCount > 0); // will fail on first run.
```

Cheers.

**Comment by ocornut** [comment]
That's intentional, we need to compute the contents size on the first frame so the window can have a size on the next frame.

What's the issue with it?

**Comment by sc00ter** [comment]
It's not a huge deal, but it is showing up as an error on a vulkan based render test case.
Basically vulkan is recording a command buffer which is using imgui to draw some text overlays.
As the command buffers only get created once upfront, and not for each frame, it will always fail.

**Comment by ocornut** [comment]
>  it is showing up as an error on a vulkan based render test case.

If there is an error in the Vulkan example could you clarify what/where the error is?

I can't seem to reproduce the error even when taking this early return path in `ImGui_ImplVulkan_RenderDrawData()`: 
```
void ImGui_ImplVulkan_RenderDrawData(VkCommandBuffer command_buffer, ImDrawData* draw_data)
{
    VkResult err;
    if (draw_data->TotalVtxCount == 0)
        return;
```

**Comment by sc00ter** [comment]
Sorry, I don't mean in the Vulkan example in imgui.  I'm referring to a vulkan project I am working on.

To clarify, in this particular case,  the command buffer is pre-recorded once, but submitted to vulkan's render queue each frame, rather than being re-recorded each frame.  So in the case where no window size is given, the above issue occurs.

Perhaps this use case, albeit a common vulkan scenario, is a little outside the scope of imgui's general design.

**Comment by sc00ter** [comment]
sure, thanks for the help.
