### ISSUE TITLE
How to right-align a MenuItem in a MainMenuBar ?

### ISSUE THREAD

**Issue by AlessioR** [ocornut/imgui#1894]
Hi,

there's a function that can simply do this ?
Or I must play with window size and SetCursorPos ?
I'm trying to put widget on mainmenu like screenshot from The Dragon's Trap.

Thank you,
Alessio

**Comment by ocornut** [comment]
There's no such function, you need to position the current yourself if you want right-aligned menu items.
Note that you can use SameLine() and any regular widget in a menu bar.

**Comment by AlessioR** [comment]
Thank you,

I'm using following code
```
const float PADDING = 20.0f;
const char* help = "About"
ImVec2 size = ImGui::CalcTextSize(help);
ImGui::SetCursorPos(ImVec2(ImGui::GetIO().DisplaySize.x-size.x-PADDING, 0));

if ( ImGui::BeginMenu(help) ) {
...
```

As you can see I'm using a const value PADDING to prevent that text will be unreadable ( clipped ) , can it be omitted and use ImGui function instead ?

Then I would know text_end argument in CalcTextSize is used for.

Alessio

**Comment by ocornut** [comment]
Most item uses sizes defined in the ImGuiStyle structure. The important ones are `FramePadding` (added to all items that are framed) and `ItemSpacing` (added between successive items).

Here you may want to use, e.g.
```
ImGuiStyle& style = ImGui::GetStyle();
size.x += style.FramePadding.x * 2 + style.ItemSpacing.x;
```

`text_end` arguments are only if you want to calculate/display strings that are not zero-terminated. If you leave it NULL it will automatically look until the end of the string.

**Comment by AlessioR** [comment]
Thank you,
Alessio
