### ISSUE TITLE
imgui_demo: PushID/PopID or TreeNode/TreePop Mismatch

### ISSUE THREAD

**Issue by flyover** [ocornut/imgui#1895]
**Version/Branch of Dear ImGui:**

1.62

**My Issue/Question:**

In the example (example_glfw_opengl3, in this case):
Select "ImGui Demo" -> "Examples" -> "Property editor"
Click "Object_0" (or "Object_1" or "Object_2")
```
example_glfw_opengl3: ../../imgui.cpp:5545: void CheckStacksSize(ImGuiWindow*, bool): Assertion `*p_backup == current && "PushID/PopID or TreeNode/TreePop Mismatch!"' failed.
Aborted
```

**Comment by ocornut** [comment]
My bad, I broke this with 640c0566 + 826d77185e5967b5d572304945e37102efb58181. Fixed now.
Thanks!
