### ISSUE TITLE
TreeNode should keep selection state when arrow clicked

### ISSUE THREAD

**Issue by SuperWangKai** [ocornut/imgui#1896]
TreeNode should allow user to expand or collapse and keep selection state not changed, when user clicking the arrow.

Correct me if I missed something.

Thanks very much!

**Comment by ocornut** [comment]
I am not sure what you mean by selection state, TreeNode currently don’t hold any selection state. Please provide more details.

**Comment by SuperWangKai** [comment]
Oh, sorry. 

Here is my issue: AFAIK, we use methods like `ImGui::IsItemClicked()` to trigger the selection (#1872). However, when user clicks on the arrow of the tree node, `ImGui::IsItemClicked()` also returns true. In this case, when a user intends to expand/collapse the node, the node will also be selected. This is not desired.

**Comment by SuperWangKai** [comment]
X coord approach appearly solves my problem. Cheers! :)

**Comment by Folling** [comment]
You could split the TreeNodeBehaviour into two items, one button for the arrow, and one for the rest.
This should be toggeable with a `ImGuiTreeNodeFlags_SeparateArrow` flag (or something similar, in which case two button behaviours and ItemAdd's are used instead of just once.

**Comment by ocornut** [comment]
Hello,

I have made two changes:
- For #2886 made it that it is possible to ctrl-click the arrow, which should facilitate implementing multi-select patterns.
- Added a `IsItemToggledOpen()` call to explicitely query if the node was just closed/open making it possible to differenciate this from e..g a simple click.

Both of those changes should normally answer the problem opened here now.

-Omar
