### ISSUE TITLE
Extra hovering region for TreeNode 

### ISSUE THREAD

**Issue by SuperWangKai** [ocornut/imgui#1897]
I have another question about TreeNode... I drew an ugly picture to make it clear.

![hover_region](https://user-images.githubusercontent.com/15721569/41812231-d8d8ae6a-7751-11e8-8638-ea432bc22499.png)

Currently, the green rect is for the hovering, however, I think it would be much easier for user to select if we can have an option to make the red rects be the hovering region as well. 

I'm not sure if missed some existed approach.

**Comment by ocornut** [comment]
We need to implement `ImGuITreeNodeFlags_SpanAllAvailWidth` to be consistent with `Selectable()` having the same option. This is not by default to allow laying out other items in the same spot.

**Comment by ocornut** [comment]
Fixed now, added `ImGuiTreeNodeFlags_SpanAvailWidth`.
See #2438 for details.
