### ISSUE TITLE
Vertical align icon font and text

### ISSUE THREAD

**Issue by AlessioR** [ocornut/imgui#1898]
Hi,

I'm trying to vertically center an icon font with a text message.

![before](https://user-images.githubusercontent.com/5927792/41817385-55662e56-779a-11e8-93dd-7dcf33facdbd.jpg)

I'm using following code to center vertically the text message:

```
ImVec2 pos = ImGui::GetCursorPos();
ImGui::Text(icon);
pos.x += 80;
pos.y -= 8;
ImGui::SetCursorPos(pos);
ImGui::Text(g_alertMsg);
```

so I can achieve this:

![after](https://user-images.githubusercontent.com/5927792/41817396-9361fafa-779a-11e8-841b-f00f445e3ea9.jpg)

There's a better way to implement this removing hardcoded constants ?

Then I noticed a small padding between main window and modal message:
![zoom](https://user-images.githubusercontent.com/5927792/41817418-3eea1d9e-779b-11e8-8e30-3a2c2600458f.jpg)

Can be removed ?

Thank you,

Alessio

**Comment by ocornut** [comment]
> Can be removed ?

This is probably either `style.DisplayWindowPadding` or `style.DisplaySafeAreaPadding`.
Please look at the style structure in details if you have questions about any spacing/padding.
