### ISSUE TITLE
Menu Item : Differents colors of items 

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#1903]
Hello,

htis is not an issue.

i would like to apply different colors of Menu Items : 

for the moment i have that :
![dllhost_2018-06-25_12-49-59](https://user-images.githubusercontent.com/1434736/41848393-9e219020-787d-11e8-80c4-b13cca33c0c6.png)

these items represents shaders and i would like to display items frame bg with red colors or orange colors
if the shaders has errors or warnings.

i tried the PushStyleColor, but i dont know what style to use.
When i go to the function MenuItem maybe im wrong but i not see the method RenderFrame
so at this moment i dont understand, how the menu are drawn.

Regards.

**Comment by ocornut** [comment]
You can use the style editor to find out which colors are used.

**Comment by aiekick** [comment]
thanks, 

ok its the style PopupBg, but how i can change color of particular item ?

because if i do that :

`
	ImGui::PushStyleColor(ImGuiCol_PopupBg, ImVec4(0.8f, 0.2f, 0.2f, 1.0f));
	ImGui::MenuItem("item");
	ImGui::PopStyleColor();`
'

he not change colors. and its logic, no ? there is not the method Renderin Frame in the function MenuItem only RenderText.

its not possible ?

**Comment by ocornut** [comment]
> ok its the style PopupBg
> he not change colors.

It's not. You yourself found it is not.

Have you tried looking at all the matching colors in the Style Editor and tweaking them to find out which one affects the color you want to change?

> there is not the method Renderin Frame in the function MenuItem only RenderText.

Have you looked deep enough?

> its not possible ?

It is possible.

**Comment by aiekick** [comment]
heu, i speack about change the bg color of the popup per item not the selectable color itself.
when i used the styleeditor, popupbg change the color of the frame.
indeed the Selectable has no frame background
but ok i will implement my MenuItem with a spetial Selectable

**Comment by ocornut** [comment]
You can draw a background (eg:red) before calling MenuItem(), or add an error icon in the text, or change the text color, or add a colored item on the right of the menu item.

**Comment by ocornut** [comment]
When I refactor the style system (in the future) I could indeed add extra color entries for all those currently transparent/invisible frames prior to selection. Right the simplest is just to draw the background yourself before calling MenuItem().

**Comment by aiekick** [comment]
finally i just add a spetial case in Selectable when we are in a menuitem :


```cpp
// render frame bg => aiekick 2018/06/26
if (flags & ImGuiSelectableFlags_MenuItem)
{
	const ImU32 col = ImGui::GetColorU32(ImGuiCol_PopupBg);
	ImGui::RenderFrame(bb_full.Min, bb_full.Max, col, false, 0.0f);
}
```

before

```
// Render
if (hovered || selected)
{
	const ImU32 col = GetColorU32((held && hovered) ? ImGuiCol_HeaderActive : hovered ? ImGuiCol_HeaderHovered : ImGuiCol_Header);
	RenderFrame(bb_with_spacing.Min, bb_with_spacing.Max, col, false, 0.0f);
	RenderNavHighlight(bb_with_spacing, id, ImGuiNavHighlightFlags_TypeThin | ImGuiNavHighlightFlags_NoRounding);
}
```

like if no tuning i keep the color of PopupBg, but i re add a frame and even its not necessary
and i can tune the color of PopupBg for my need

so i get that now :

**Comment by ocornut** [comment]
But now you have modified imgui, making your next updates more difficult.. you could render the frame yourself before calling MenuItem().

**Comment by aiekick** [comment]
yep btw as i have specific needs, i have modified many things in imgui:) but you are right for the frame, but difficult to calc the good frame size for all cases :)

**Comment by ocornut** [comment]
Closing this now.
I would really recommend not modifying imgui.cpp especially here as you don't really need to (you can implement custom widgets in your own files).

I find it hard to believe that you can make the elaborate software you posted about in the gallery and find it difficult to calculate the frame size (even `ImVec2(999.0f, GetFrameHeight()`) would work in this context)

**Comment by aiekick** [comment]
no i speack about all the padding when you calculate the frame of an item according to text or many ohter behavior. in your items you calculate that with many way, its hard to calculate before the call to ImGui::Something(). this just what i said, but i can foud solution but its time :)

**Comment by ocornut** [comment]
You can call `CalcTextSize()` it's not a lot of work. But the point is that `ImVec2(999.0f, GetFrameHeight()` _IS_ a working solution for exactly what you are doing here. MenuItem/Selectable highlight take all the horizontal space they have available. You may replace 999.0f with `GetContentRegionAvailWidth()` and you'll get the same result. In every case this is a few lines of code to get this rectangle displayed and this will be much less pain than modifying imgui.cpp.

```
ImVec2 p_min = ImGui::GetCursorScreenPos();
ImVec2 p_max = ImVec2(p.min.x + GetConetntRegionAvailWidth(), p.min.y + GetFrameHeight())
ImGui::GetWindowDrawList()->AddRectFilled(p_min, p_max, IM_COL32(255,0,0,200));
ImGui::MenuItem(...);
```

**Comment by aiekick** [comment]
ok thank you very mush :+1:

**Comment by Asher-Ul-Haque** [comment]
Its FrameBGHover color you ar elooking for
