### ISSUE TITLE
Converting from MUCH older imgui version

### ISSUE THREAD

**Issue by w123finder** [ocornut/imgui#1904]
I currently have a heavily edited version of the nvidia flex demo that runs off a very early version of imgui which I would like to update to a more recent version, however the frameworks are so different between the two versions I don't know where to begin.  I looked around for imgui blogs where I could post this, since I didn't want to clutter the issues tab, but alas I am here.  

I am attaching a link to the flex demo download, since if its possible there to update the framework, it will be possible in my project.  Thank you for any help!  

https://drive.google.com/file/d/1wMPZw5ZntmTKlCURdmR0xsE-xbAxGbaq/view?usp=sharing

**Comment by ocornut** [comment]
This is not the same library, the library was https://github.com/AdrienHerubel/imgui/
(notice the author aren't the same, the name isn't the same, Mikko Mononen made an IMGUI library as part of the Recast examples and Adrien Herubel later extracted it as standalone library).
The library principles are rather close so it shouldn't be too difficult to switch it to dear imgui if you want to.

**Comment by w123finder** [comment]
Thanks!

**Comment by w123finder** [comment]
@ocornut 
Is there any chance you could point me in a starting direction?  I know you're busy, and if you don't have time to answer I completely understand, but my project team just shafted this onto me and I have no real experience working with any variation of imgui.  Sorry for bothering you!

**Comment by ocornut** [comment]
The starting direction are the examples and documentations and links provided here. I can’t provide more sorry.

**Comment by w123finder** [comment]
@ocornut 
Sorry to bother you again, but I think I found my answer, but just to make sure I'm not messing anything up on the rendering side of things, do you happen to know of any 3d imgui demos so I can check my logic?

**Comment by ocornut** [comment]
I don't understand the question.

**Comment by w123finder** [comment]
@ocornut 
Sorry for not being clear, I was just wondering if you know of any 3d applications/programs/demos that use dear imgui software for their ui.

**Comment by dpethes** [comment]
@w123finder there are plenty of open source programs that use imgui in the Gallery (links are in the readme).
