### ISSUE TITLE
imguiex-osx doesn't build

### ISSUE THREAD

**Issue by wtholliday** [ocornut/imgui#1906]
**Version/Branch of Dear ImGui:**

master (79153cf)

**Back-end file/Renderer/OS:**
macOS

**My Issue/Question:** `examples/examples_apple` fails to build on macOS

**Screenshots/Video** 

<img width="714" alt="imgui" src="https://user-images.githubusercontent.com/841144/41950983-97eed8d8-797d-11e8-9d93-c071741a402c.png">

**Comment by ocornut** [comment]
I have fixed those paths now so it should compile again. Note that the OSX parts are none other than the GLFW+GL2 example which you can access and compile separately. 

You should be able to compile any of the GLFW/SDL + OpenGL/Vulkan examples on a Mac (and if not they should be fixed).

The example_apple/ folder is not being kept up to date (see #1873, tl;dr; I don't own a Mac, I'm struggling to use one and little Mac help is coming to maintain the examples applications, so I may as well delete the folder for now to people can focus on the other examples)
