### ISSUE TITLE
How to handle same inputs for different parts of the gui

### ISSUE THREAD

**Issue by e3dos** [ocornut/imgui#1912]
Sorry if it's not totally a imgui related problem.

I have various lists I can select objects with imgui. But what is the best strategy to handle, for example, if I select a object and want to delete it, how do I handle this delete input to know which list the delete input is going to act upon.
I know that imgui have active windows flag(?), but I have some workspace that is the viewport of the application which is opengl and do not have any gui to interact with.
Any suggestions are welcome.

I don't even know how QT handle those things.

**Comment by ocornut** [comment]
I think in this situation you can just test `if (ImGui::IsWindowFocused())` on the window that contains the list.

> but I have some workspace that is the viewport of the application which is opengl and do not have any gui to interact with.

Not sure to understand if that will affect anything. If you click outside of your object list (e..g in the "void" behind imgui or on another window) the Object List window won't be focused anymore.

**Comment by e3dos** [comment]
Thanks for the feedback Omar.

**Comment by ocornut** [comment]
@e3dos Good! Let me know if that solves your problem (so then we can close the thread.)
If interested I will tag you when we revisit this topic and handle shortcuts in a more high-level manner.
