### ISSUE TITLE
XPM Support for Embedded Colored and Transparent Icons

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#1915]
Hello,

i continue in the process of incorporate in imgui what i have implemented. :)

for my softwares, i would like to have embedded ressources for icons.
I worked a long time with wxWidgets who have this support of XPM format by default.

il have created some method for create glTexture from xpm file to be used by image button or other controls.

i need to improve this to load all ressources one time, and create an atlas tecture like you do for the font.
and find a way like font to have the sprite pos corresponding to an icon tag

Do you see a simple meaning to incorporate that in imgui, or its not a good idea for imgui ?
with this system it will be easier to have some colored icons included in code.

**Comment by ocornut** [comment]
Hello,

Your question is a little confusing and seems to have little to do with "XPM", and could be completely handled on the application side. Dear ImGui is not going to load image from disk and create textures for you.

However, there's a "Custom Rectangles/Glyphs API" in ImFontAtlas which is a helper which may be fitting. You can register rectangle sizes before building the font atlas, and get their position/uv after the atlas is build, then you can copy custom graphics data into those rectangles (by your own mena). You can also map those rectangles to Unicode points. This is used to create custom glyphs or colored icons.

Please check it out!
Unfortunately, I can't be providing support like that if you don't do the work of research and clarity on your side. Would you be kind and wait 24 hours before your next post, thank you.

**Comment by aiekick** [comment]
i thinck you can supress this post :)
