### ISSUE TITLE
'alloca' was not declared in this scope

### ISSUE THREAD

**Issue by l0phtgh0st** [ocornut/imgui#1917]
I am trying to use Imgui with "Cygwin gcc 6.4.0" and I got the error below.

`imgui_draw.cpp:831:77: error: 'alloca' was not declared in this scope`

Is imgui a cross platform library or does it only support Windows?

**Comment by ocornut** [comment]
The library should work on every platform, it’s just that the .h location of alloca is inconsistent accross systems/compilers. If you look at the top of imgui_draw.cpp there’s a few lines dedicated to deciding the right header file to include depending on the compiler/os version.

Could you find where alloca is declared with your version of cygwin, so we can push a fix? You may edit those few lines and toy around. Try including: malloc.h or alloca.h or stdlib.h and let me know which one works on your system? Thanks.

**Comment by sonoro1234** [comment]
```
#if defined(__CYGWIN__) && !defined(_WIN32)
	/* Cygwin POSIX under Microsoft Windows. -------------------- */
  
#endif
```

**Comment by l0phtgh0st** [comment]
I try changing the `imgui_draw.cpp` to

```
#include <stdio.h>      // vsnprintf, sscanf, printf
#if defined(__CYGWIN__)
#include <alloca.h>     // alloca
#endif//__CYGWIN__
#if !defined(alloca)
#ifdef _WIN32
#include <malloc.h>     // alloca
#if !defined(alloca)
#define alloca _alloca  // for clang with MS Codegen
#endif
#elif defined(__GLIBC__) || defined(__sun)
#include <alloca.h>     // alloca
#else
#include <stdlib.h>     // alloca
#endif
#endif
```

I try to use it like

```
#include "imgui/imgui.h"

void Draw();

int main()
{
	while(true){
		Draw();
	}

	return 0;
}

void Draw()
{
	ImGui::Text("Hello, world");
}
```

It crash with `Exception: STATUS_ACCESS_VIOLATION` . Maybe I am not using the library correctly?

**Comment by ocornut** [comment]
You need to create a context and wire bindings, see examples/ for that.

Thanks for testing for header files, will try to patch it soon.

**Comment by l0phtgh0st** [comment]
It doesn't work as a stand-alone library and need to wire up with other library?

I only found examples which use imgui with other library.

**Comment by ocornut** [comment]
You need to feed the inputs and render the 3d triangles somehow. There are many ways to do that and we provide some examples using convenient librairies such as glfw or sdl.

**Comment by ocornut** [comment]
Pushed a fix for the alloca() issue, hopefully it will be right this time :)
