### ISSUE TITLE
Who draws the cursor?

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#1918]
1.62 Version
glfw opengl3 in windows

**My Issue/Question:** 

With previous implementations then only relevant variable to tell who draws the cursor was io.MouseDrawCursor:

* imgui : io.MouseDrawCursor is true
* glfw: io.MouseDrawCursor is false

Now NoMouseCursorChange is also relevant:

* imgui : io.MouseDrawCursor is true and NoMouseCursorChange is false
* glfw: io.MouseDrawCursor is false and NoMouseCursorChange is true

Other combinations are possible so that true-true gives two cursors and false-false leaves the cursor as an arrow forever.

I am not sure to understand what was the motivation behind the change.

**Comment by ocornut** [comment]
`NoMouseCursorChange` request that the back-end won't interact with the hardware/os mouse cursor, so the user code can do it. This is in case the service provided by the back-end is not enough for the application who made have more custom/finer manipulation of cursor visibility and shapes.

The function touching the hardware/os cursor in every back-end does:
```
if (io.ConfigFlags & ImGuiConfigFlags_NoMouseCursorChange)
    return;
```

And the comment says:
_// Instruct back-end to not alter mouse cursor shape and visibility. Use if the back-end cursor changes are interfering with yours and you don't want to use SetMouseCursor() to change mouse cursor. You may want to honor requests from imgui by reading GetMouseCursor() yourself instead.
ImGuiConfigFlags_NoMouseCursorChange    = 1 << 5,_   

The way your post is presented is therefore misleading. If you set `ImGuiConfigFlags_NoMouseCursorChange` you take the responsibility of manipulating the hardware/os cursor yourself, which include hiding it if you also decide to request imgui's software mouse cursor, etc.

**Comment by sonoro1234** [comment]
```
The way your post is presented is therefore misleading. If you set ImGuiConfigFlags_NoMouseCursorChange you take the responsibility of manipulating the hardware/os cursor yourself, which include hiding it if you also decide to request imgui's software mouse cursor, etc.
```
Yes, but it was already achieved in older implementations by just setting io.MouseDrawCursor to false and I cant understand what extra benefits we have with this new mechanism.

**Comment by ocornut** [comment]
If your app code is already calling e.g. glfw mouse cursor functions that the code in imgui_impl_glfw.cpp would conflict with your code. This flag serve this purpose and is the only way to make sure the backend don't call glfw mouse cursor function.

**Comment by sonoro1234** [comment]
<code>
// Hide OS mouse cursor if ImGui is drawing it
    glfwSetInputMode(g_Window, GLFW_CURSOR, io.MouseDrawCursor ? GLFW_CURSOR_HIDDEN : GLFW_CURSOR_NORMAL);
</code>

Compared with old behaviour above we are able now to let both glfw and imgui cursors hidden
by setting io.MouseDrawCursor  false and NoMouseCursorChange  true and also glfwSetInputMode(window,glc.GLFW_CURSOR, glc.GLFW_CURSOR_HIDDEN)
That makes me understand the changes althought 3 actions need to be performed for that.

Perhaps other solution would be to drop all cursor stuff from implementations and user could control cursors with just io.MouseDrawCursor (true or false) and glfw cursor functions glfwSetInputMode and glfwSetCursor althought I dont know in other implementations.

**Comment by ocornut** [comment]
I don’t understand what you are trying to say or solve.

First, you can remove io.MouseDrawCursor out of the equation because there’s little reason to use it on a computer (it’s mostly useful for console systems).

If to set NoMouseCursorChange the app controls the cursor, otherwise the binding controls it and it’s enough for 90% of users. 

The point of the impl_ file is to provide useful code, it’s not a “solution” (to a problem i don’t understand) to remove code that is useful to 90% of the user.

**Comment by sonoro1234** [comment]
<code>First, you can remove io.MouseDrawCursor out of the equation because there’s little reason to use it on a computer (it’s mostly useful for console systems).</code>

Ahh, I didnt realize this.
All is now clear.
Thanks omar for your patience.
