### ISSUE TITLE
Feature request: Image(ImTextureID, ImVec2 pos, ImVec2 size)

### ISSUE THREAD

**Issue by ice1000** [ocornut/imgui#1920]
I have a `ImTextureID` and I want to draw only a part of it, I can specify a `pos` which points to the x, y position of that part in the texture and `size` which tells the width and the height of that part.

**Comment by sivu** [comment]
Image already has uv0 and uv1 parameters that are texture coordinates. 
just set uv0 = { pos.x / imageSize.x, pos.y / imageSize.y }, uv1 = { (pos.x+size.x) / imageSize.x, (pos.y+size.y) / imageSize.y }

**Comment by ice1000** [comment]
Thanks. My fault
