### ISSUE TITLE
Color issue with DirectX11 on specific target applications

### ISSUE THREAD

**Issue by koemeet** [ocornut/imgui#1927]
**Version/Branch of Dear ImGui:**
https://github.com/ocornut/imgui/commit/7b2662d245104d1d756e1d698ea6de3ce18472f9

**Back-end file/Renderer/OS:**
Windows 10, version 1803

**My Issue/Question:**
On certain d3d11 targets, when I use ImGui, the colors seem to be a lot more light than they should be. Here an example of the issue I am trying to explain. I ran the same ImGui sample code on two different d3d11 targets (first row of squares is on an existing d3d11 application and the second row is on my own regular d3d11 test application):

Colors used (in order of the squares):
`rgb(28, 30, 37)` `rgb(255, 0, 0)` `rgb(255, 0, 255)` `rgb(255, 0, 100)` `rgb(100, 0, 100)`

![afbeelding](https://user-images.githubusercontent.com/1569156/42293192-aa0372de-7fd8-11e8-9280-6b8a88b39d50.png)

As you can see the last application displays the colors as they should be. But the first d3d11 target seems to make the ending colors way more light than they are in reality. The DX11 setup of the failing application is likely rather complex and sets up certain stuff which likely conflicts with ImGui (maybe lightning etc.).

It is good to know that the first application is an already existing d3d11 program, which I hook into, to provide a GUI on top of this application. Likely this application calls some DX api in its render loop which makes ImGui behave in an unexpected way.

I have also attached a screenshot of the demo window on the failing d3d11 application to display the color bug in more detail.

**Standalone, minimal, complete and verifiable example:**
```cpp
  // inside render loop ...
  ImGuiIO& io = ImGui::GetIO();
  io.DisplaySize = ImVec2(1920.f, 1080.f);

  ImGui_ImplDX11_NewFrame();
  ImGui::NewFrame();

  ImGui::Text("Hello, world!");

  ImGui::Render();
  ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
```

**Screenshots/Video**
This is how the demo window looks like on the failing d3d11 target (as you can see its way way to light than it should be):
![afbeelding](https://user-images.githubusercontent.com/1569156/42296586-e534fe44-7ff7-11e8-9051-282f69119d26.png)

**Comment by ocornut** [comment]
Hello,

Possibly the issues are related to sRGB vs Linear Blending and Gamma Correction.
You'll need to read #1724 and #578. 

Possibly you may get away with undoing gamma correction by applying a powf(color, 1.0f/2.2f) to the pixel colors. Otherwise you may need to adjust the imgui style.

Or maybe you are rendering into a render target which the game itself is using as a texture with a post-process pass.

-Omar

**Comment by koemeet** [comment]
Thank you! This information helps me a lot understanding what is going on.

I saw for directx9 its fixable by doing the following before rendering imgui:
```
device->SetRenderState(D3DRS_SRGBWRITEENABLE, false);
```

Is something like this also possible in dx11, so that I don't have to edit the pixel shader.

**Comment by koemeet** [comment]
I was able to fix it properly, by preparing my own render target view in the correct DXGI Format:

```cpp
D3D11_RENDER_TARGET_VIEW_DESC desc = {};
memset(&desc, 0, sizeof(desc));
desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
desc.ViewDimension = D3D11_RTV_DIMENSION_TEXTURE2D;

device->CreateRenderTargetView(render_target_texture, &desc, &render_target_view);
```

**Comment by Sewer56** [comment]
In the case of OpenGL:

```cpp

	const bool srgbEnabled = glIsEnabled(GL_FRAMEBUFFER_SRGB);
	glDisable(GL_FRAMEBUFFER_SRGB);
	if (srgbEnabled)
		glEnable(GL_FRAMEBUFFER_SRGB);

**Comment by planetchili** [comment]
My quick fix that yielded acceptable results _for me_.
```cpp
// gamma-correct style
const auto ToLinear = [](float x) {
  if (x <= 0.04045f)
  {
    return x / 12.92f;
  }
  else
  {
    return std::pow((x + 0.055f) / 1.055f, 2.4f);
  }
};
for (auto& c : std::span{ ImGui::GetStyle().Colors, size_t(ImGuiCol_COUNT) })
{
  c = { ToLinear(c.x), ToLinear(c.y), ToLinear(c.z), c.w };
}
```
Just do this after you initialize ImGui.
