### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by kenkit** [ocornut/imgui#1928]
Hi how do I add tabs, I don't see any example on how to do that. I tried using this https://github.com/scottmudge/imgui_tabs but it seems the code is old so it doesn't work. 
I need something like 
![687474703a2f2f692e696d6775722e636f6d2f3650534b394e4c2e676966](https://user-images.githubusercontent.com/1732471/42321927-29f9ba04-8063-11e8-833d-1fa6c0dd6282.gif)

I hope you will bear with my too many questions. I just want to make something really great.

**Comment by sonoro1234** [comment]
Tabs are not part of base imgui (this repo) but can be emulated as with this Lua code
in wihich tabed_dialogs is a table of dialogs (basically a function drawing things)

```
for i,v in ipairs(tabed_dialogs) do
    local dopop = false
    if i == curr_dial then
        ig.PushStyleColor(imgui.ImGuiCol_Button, ig.ImVec4(1,0,0,1))
        dopop = true
   end
   if (ig.Button(v.name)) then curr_diall = i end
   if dopop then imgui.igPopStyleColor(1); end
   ig.SameLine(0,1)
end

imgui.igSeparator();
tabed_dialogs[curr_dial]:draw()
```
![tab](https://user-images.githubusercontent.com/1795930/42334329-527af9ce-807d-11e8-9e1b-3354164b574a.gif)

**Comment by kenkit** [comment]
Nice I think i'll find something usefull in there.
Thank you

**Comment by kenkit** [comment]
I found a working copy https://trello.com/c/ihjVWcju There are screenshots in there.

**Comment by kenkit** [comment]
@sonoro1234  Did a good job linking me to that other branch, since I've just discovered a whole lot of new features.
Thanks guys

**Comment by ebachard** [comment]
@kenkit : sorry I missed the issue. Just in case you are still interested, I forked Scott Mudge work some time ago, but I'm unsure he added my changes (PR in progress). If you want to give it a try, everything is here : https://github.com/ebachard/imgui_tabs  (I just resync'ed today, and it should just build with the current 1.63 WIP of Dear ImGui).

Last but not least, if you see problems, don't hesitate to file an issue.

Thanks,
ericb
