### ISSUE TITLE
Cannot use custom directx9 texture

### ISSUE THREAD

**Issue by Wimacs** [ocornut/imgui#1930]
The imgui demo works perfectly on my Windows 10 x64 laptop, and I'm trying to load some additional texture created by directx9, using this very simple function:

```cpp
#include <d3dx9tex.h>
template<typename T> using Ref = T &;

auto platformLoadTexture(const wchar_t* fileName,
                         Ref<size_t> width,
                         Ref<size_t> height,
                         Ref<ImTextureID> texture) -> bool {
	LPDIRECT3DTEXTURE9 localTexture;
	if (!SUCCEEDED(D3DXCreateTextureFromFile(g_pd3dDevice, fileName, &localTexture))) return false;
	D3DSURFACE_DESC desc;
	localTexture->GetLevelDesc(0, &desc);
	width = desc.Width;
	height = desc.Height;
	texture = reinterpret_cast<ImTextureID>(texture);
	return true;
}
```

And I use it in the demo main.cpp:

```cpp
    ZeroMemory(&msg, sizeof(msg));
// my code begin
    ImTextureID localTexture;
    size_t width, height;
    platformLoadTexture(_T("cirno.png"), width, height, localTexture);
// my code end
    ShowWindow(hwnd, SW_SHOWDEFAULT);
```

And draw the image in the main loop after `ImGui::ColorEdit3`, like this:

```cpp
ImGui::Image(localTexture, ImVec2(width, height));
```

And the program stops running. I used Visual Studio 2017 debugger and I see the error occurs at line 181 in imgui_impl_dx9.cpp, here:

```cpp
                const RECT r = { (LONG)(pcmd->ClipRect.x - pos.x), (LONG)(pcmd->ClipRect.y - pos.y), (LONG)(pcmd->ClipRect.z - pos.x), (LONG)(pcmd->ClipRect.w - pos.y) };
  // error line
                g_pd3dDevice->SetTexture(0, (LPDIRECT3DTEXTURE9)pcmd->TextureId);
 // error line end
                g_pd3dDevice->SetScissorRect(&r);
                g_pd3dDevice->DrawIndexedPrimitive(D3DPT_TRIANGLELIST, vtx_offset, 0, (UINT)cmd_list->VtxBuffer.Size, idx_offset, pcmd->ElemCount/3);
```

I believe you can simply modify the demo and reproduce this bug. Please take a look.

The image `cirno.png` used in the code above will be attached in the comment.

**Comment by Wimacs** [comment]
![cirno](https://user-images.githubusercontent.com/15726940/42373385-50f980be-8147-11e8-966d-97c4cb37293a.png)

**Comment by sivu** [comment]
> texture = reinterpret_cast<ImTextureID>(texture);

Maybe you should cast localTexture instead?

**Comment by Wimacs** [comment]
Thanks for the quick reply! It's my fault, sorry for bothering! @sivu

**Comment by ocornut** [comment]
I have now written a tutorial to cover image file loading for common graphics API:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
