### ISSUE TITLE
imgui_impl_sdl trows an #define error with tdm-gcc 5.1.0 (mingw32 compiler) on windows 10.

### ISSUE THREAD

**Issue by Hecatonecles** [ocornut/imgui#1936]
on the imgui 1.62 i get this error on win10 with tdm-gcc 5.1.0 (mingw compiler).
error log:
```
"----------Building project:[ EMULATOR - Debug ]----------"
mingw32-make.exe[1]: Entering directory 'D:/Basic/Workspace/EMULATOR'
imgui_impl_sdl.cpp:44:64: error: missing binary operator before token "("
 #define SDL_HAS_VULKAN                      SDL_VERSION_ATLEAST(2,0,6)

 imgui_impl_sdl.cpp:46:6: note: in expansion of macro 'SDL_HAS_VULKAN'
#if !SDL_HAS_VULKAN
      ^
imgui_impl_sdl.cpp:41:64: error: missing binary operator before token "("
 #define SDL_HAS_WARP_MOUSE_GLOBAL           SDL_VERSION_ATLEAST(2,0,4)
                                                                ^
imgui_impl_sdl.cpp:122:5: note: in expansion of macro 'SDL_HAS_WARP_MOUSE_GLOBAL'
 #if SDL_HAS_WARP_MOUSE_GLOBAL
     ^
imgui_impl_sdl.cpp:44:64: error: missing binary operator before token "("
 #define SDL_HAS_VULKAN                      SDL_VERSION_ATLEAST(2,0,6)
                                                                ^
imgui_impl_sdl.cpp:181:10: note: in expansion of macro 'SDL_HAS_VULKAN'
     #if !SDL_HAS_VULKAN
          ^
imgui_impl_sdl.cpp:41:64: error: missing binary operator before token "("
 #define SDL_HAS_WARP_MOUSE_GLOBAL           SDL_VERSION_ATLEAST(2,0,4)
                                                                ^
imgui_impl_sdl.cpp:210:5: note: in expansion of macro 'SDL_HAS_WARP_MOUSE_GLOBAL'
 #if SDL_HAS_WARP_MOUSE_GLOBAL
     ^
imgui_impl_sdl.cpp:43:64: error: missing binary operator before token "("
 #define SDL_HAS_CAPTURE_MOUSE               SDL_VERSION_ATLEAST(2,0,4)
                                                                ^
imgui_impl_sdl.cpp:222:5: note: in expansion of macro 'SDL_HAS_CAPTURE_MOUSE'
 #if SDL_HAS_CAPTURE_MOUSE
     ^
mingw32-make.exe[1]: *** No rule to make target 'Debug/imgui_impl_sdl.cpp.o.d', needed by 'Debug/imgui_impl_sdl.cpp.o'.  Stop.
mingw32-make.exe: *** [All] Error 2
mingw32-make.exe[1]: Leaving directory 'D:/Basic/Workspace/EMULATOR'
Makefile:4: recipe for target 'All' failed
====6 errors, 5 warnings====
```

if i comment out lines 41 to 48 it compiles without problems.

if it gives an workaround of that error please tell me.

ps: i also include stdint.h in the imgui_impl_opengl2.cpp to solve an error trowed by intptr_t.

**Comment by ocornut** [comment]
Hello,

What is your version of SDL?
Doesn't it has a `SDL_VERSION_ATLEAST` macro in SDL_version.h?

**Comment by Hecatonecles** [comment]
i  use SDL version 2.0.8 (stable) if i look at SDL_version.h the SDL_VERSION_ATLEAST macro is defined.

**Comment by ocornut** [comment]
Does adding `#include <SDL_version.h>` manually before fixes it?

**Comment by Hecatonecles** [comment]
including SDL_version.h manualy before imgui_impl_sdl.h does not fix the error.

**Comment by ocornut** [comment]
> including SDL_version.h manualy before imgui_impl_sdl.h does not fix the error.

Could you dig into the code to understand where the error lies? Maybe by investigation or manually developing the code in the macros (`SDL_VERSION_ATLEAST` uses `SDL_COMPILEDVERSION` and `SDL_VERSIONNUM()`` ?

**Comment by Hecatonecles** [comment]
if i add this two macros manualy to the imgui_sdl_impl.h then it will compile without errors.
```

#define SDL_VERSIONNUM(X, Y, Z) \
    ((X)*1000 + (Y)*100 + (Z))

#define SDL_VERSION_ATLEAST(X, Y, Z) \
    (SDL_COMPILEDVERSION >= SDL_VERSIONNUM(X, Y, Z))
```

**Comment by ocornut** [comment]
That's very strange. I can't explain why `#include <SDL_version.h>` at the top of `imgui_impl_sdl.cpp` wouldn't fix it. SDL_version.h has no other include guard than a regular `#ifndef SDL_version_h_` and those macros are the earliest thing declared in the file.

Does compiling examples/example_sdl_opengl2/ or examples/example/sdl_opengl3/ get you the same error?

Are you sure the right version of SDL_version.h is being included and not another esoteric version of SDL? You can add an `#error` line at the top of include/SDL_version.h WITHIN your SDL 2.0.8 folder to ensure it is this one that is being included.

**Comment by Hecatonecles** [comment]
yepp im sure that i include SDL_version.h from my SDL 2.0.8 folder. i havent an other one installed.
i also use the examples/example_sdl_opengl2/ demo to test imgui. how i wrote above i patched the
imgui_impl_opengl2.cpp too, here it was an error from intptr_t.

i cant test examples/example_sdl_opengl3/ while my graphics card is an old one and reject opengl3 context. sorry for that.

**Comment by ocornut** [comment]
I pushed a change for intptr_t.

I can't find a reason for the SDL_version issue sorry. It doesn't make sense to me, `<SDL.h>` include `SDL_version,h` which has those macros. Please investigate if you can.

> i also use the examples/example_sdl_opengl2/ demo to test imgui

I asked because your error above mention `D:/Basic/Workspace/EMULATOR` which looks like a different project than the imgui examples project.

> i cant test examples/example_sdl_opengl3/ while my graphics card is an old one and reject opengl3 context. sorry for that.

Made changes yesterday to reduce the OpenGL version, you may edit example_sdl_opengl3/main.cpp to change to GL 2.1 + GLSL 120 or GL 2.0 + GLSL 110 as well.

**Comment by Hecatonecles** [comment]
okay i will try it but im not a good c++ programmer so i do not understand all of this language. i have to learn about it a bit more ;)

if i found a solution for the SDL error i report it here. but it can take a while :/

ps: i use the CodeLite IDE and my project lay in my basic/workspace folder. all what i need is in it and i pass a seperate include and lib folder to gcc so it can find it.
if it helps here is the .mk file from my project. https://pastebin.com/5eQAAgPF

**Comment by Hecatonecles** [comment]
okay i think i have an workaround for the sdl error.
if i change imgui_impl_sdl.h at the lines that trow this wired error to this it compiles.
```
// SDL
// (the multi-viewports feature requires SDL features supported from SDL 2.0.5+)
#ifdef SDL_VERSION_ATLEAST
#define SDL_HAS_WARP_MOUSE_GLOBAL           SDL_VERSION_ATLEAST(2,0,4)

#define SDL_HAS_CAPTURE_MOUSE               SDL_VERSION_ATLEAST(2,0,4)
#define SDL_HAS_VULKAN                      SDL_VERSION_ATLEAST(2,0,6)
#define SDL_HAS_MOUSE_FOCUS_CLICKTHROUGH    SDL_VERSION_ATLEAST(2,0,5)
#endif
```

**Comment by Hecatonecles** [comment]
okay im an idiot i think i trow the sdl includes in my seperate include dir and got this error. if i trow it to my tdm-gcc includes dir it will work. but im not understanding why it will not work with my own directory if i pass it to the compiler :/
