### ISSUE TITLE
Is ImGui::GetStyleColorName(ImGuiCol idx) missing ImGuiCol_NavWindowListHighlight ?

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#1939]
In imgui.cpp. It should be current master branch.

(I hit the assert at the end of the switch statement) .

ImGuiCol_NavWindowListHighlight is defined in imgui.h.

**Comment by ocornut** [comment]
Fixed now! Apologies. I backported this change from another branch yesterday and while shuffling code messed up with the switch statement.

**Comment by Flix01** [comment]
No worries. Thanks :smile: .
