### ISSUE TITLE
Cannot show image by stbi_load + example_glfw_opengl3

### ISSUE THREAD

**Issue by Bobyuan1015** [ocornut/imgui#1943]
I put my code blow in main.cpp of example_glfw_opengl3 folder, but the UI cannot show the image up.
There is just a black color area whose side is equal to the image's size. Please help me out.

My final goal is to show video wall. In the first stage, I just would like to show a single image for testing functions. And please recommend me some possible solutions to show videos. many thanks

  int my_image_width, my_image_height;
            unsigned char* my_image_data = stbi_load("work1.png", &my_image_width, &my_image_height, NULL, 4);

            // Turn the RGBA pixel data into an OpenGL texture:
            GLuint my_opengl_texture;
            glGenTextures(1, &my_opengl_texture);
            glBindTexture(GL_TEXTURE_2D, my_opengl_texture);
            glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
            glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, my_image_width, my_image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, my_image_data);

            // Now that we have an OpenGL texture, assuming our imgui rendering function (imgui_impl_xxx.cpp file) takes GLuint as ImTextureID,
            // we can display it:
            ImGui::Image((void*)(intptr_t)my_opengl_texture, ImVec2(my_image_width, my_image_height));

**Comment by ocornut** [comment]
- Please verify that stbi_load() successfully loaded the image (with an assert or debugger, display and verify all the values).
- Use a graphics debugger such as RenderDoc to verify that your OpenGL context has the right texture.
- After this is done, please provide a full complete repro (as described in the guidelines visible when you open an issue) including code + data.

When you have verified everything please post the results and suitable info and you may re-open this topic.
I have to be harsh here but this kind of question popups up all the time and it is almost always an error on the user side. We even provide an example now (which you pasted) so I am not sure I can help more than that.

> And please recommend me some possible solutions to show videos.

Sorry this is not the right place.

**Comment by Bobyuan1015** [comment]
Hi ocornut

what is a good way to show video or camera data? Many thanks for your guidance.
Looking forwards to hearing from yours

**Comment by ocornut** [comment]
I have now written a tutorial to cover image file loading for common graphics API:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
