### ISSUE TITLE
Clicking on Slider knob shifts its position

### ISSUE THREAD

**Issue by armadillu** [ocornut/imgui#1946]
**Version/Branch of Dear ImGui:** 
1.60 master

**My Issue/Question:** 
When using any of the sliders, especially when using a style with a large "GrabMinSize", the slider knob shifts its position upon clicking on it. It does so to place the knob right under where the mouse is, but if the knob is large enough, its quite unlikely the user will click right in the middle.

This makes it very hard to "undo" a click on a slider; as if I just click and let go, I already changed the slider value. In most slider implementations, clicking on the handle and letting go doesn't affect state.

It should internally store an offset (x distance between local mouse click pos and knob center), and set the knob position based on that, instead of where the mouse input is.

**Screenshots/Video** 

![jul-13-2018 17-50-41](https://user-images.githubusercontent.com/167057/42700868-4ba4889c-86c5-11e8-938b-567534f4514e.gif)

**Comment by ocornut** [comment]
I agree we could implement that change, will look into it.

**Comment by ocornut** [comment]
Finally supported with d3fd263. Thank you for your patience!
