### ISSUE TITLE
Reset collapsed state of CollapsingHeader

### ISSUE THREAD

**Issue by AlessioR** [ocornut/imgui#1947]
Hi,

I'm using ImGui 1.63 WIP and I would to know if there's I way to reset collapsed (open) state of a row in a CollapsingHeader.
If I've understand correctly, "open" state is remember by ImGui hashing text contents of rows.
I've a CollapsingHeader that is filled dinamically  and I would that each rows will be uncollapsed when reload occurs.

Thank you.

**Comment by ocornut** [comment]
Hello,

You can use `SetNextTreeNodeOpen(bool open, ImGuiCond cond = ImGuiCond_None);` before the `CollapsingHeader()` call.

You may also poke directly into the underlying storage, e.g.

`ImGui::GetStateStorage()->SetInt(ImGui::GetID("MyCollapsingHeader"), 1);`

**Comment by ocornut** [comment]
@AlessioR Closing this topic as I think your question as been answered. Let me know if you are having issues with it.
