### ISSUE TITLE
Save State In OpenGL Examples

### ISSUE THREAD

**Issue by HardlineStudios** [ocornut/imgui#195]
I've been integrating this great little library into my engine and noticed that the render functions in the example code doesn't save render and texture state which did cause issues with my engine. 

Here is what I did to solve this. At the start of the RenderDrawList function, I save both program and texture state:

```C++
static void ImGui_RenderDrawLists(ImDrawList** const cmd_lists, int cmd_lists_count)
{
  if (cmd_lists_count == 0)
    return;

  //
  // save current program/texture state
  GLint nLastProgram = 0;
  glGetIntegerv(GL_CURRENT_PROGRAM, &nLastProgram);

  GLint nLastTexture = 0;
  glGetIntegerv(GL_TEXTURE_BINDING_2D, &nLastTexture);
```

and then at the end before leaving, I restore it:

```C++
  // Restore modified state
  glBindVertexArray(0);
  glUseProgram(nLastProgram);
  glDisable(GL_SCISSOR_TEST);
  glBindTexture(GL_TEXTURE_2D, nLastTexture);
```

Hope this helps someone! Might be worth adding to the examples?

**Comment by Extrawurst** [comment]
i think in the bundled examples this code has no benefit besides being noise. of course integrating it in an engine >may< make this necessary but that depends totally on the usage scenario and should not be part of those examples in my opinion

**Comment by HardlineStudios** [comment]
Well in my case, rather than re-write the render function, I just kept it as is. Seemed like the simpler solution and so I just wanted to save someone else a few hours of figuring out why things were randomly crashing after ImGui::Render was called! :)

**Comment by Extrawurst** [comment]
why rewrite your render function ? you can simply wrap the ImGui::Render inside the two blocks you posted here?!

**Comment by HardlineStudios** [comment]
Right that's what I'm saying. No one should re-write anything. 

Most people who get this library will grab the render function in the examples that best suits their needs and keep going. So I went with the GL 3 demo and just modified the ImGui_ImplGlfwGL3_RenderDrawLists function and in doing so, ran into this small issue with state preservation hence why I posted what I did.  :)

**Comment by heroboy** [comment]
If you do this, you need save and restore **all** render states.

**Comment by ocornut** [comment]
You are correct and ideally we should save/restore all render states, which appears to be a bit of a faff with modern GL. I don't even know how to do it for some of the state modified. I suppose it wouldn't hurt saving/restoring those two.

Out of curiosity why didn't you use the simpler fixed-pipeline GL codebase? That works as well.

**Comment by HardlineStudios** [comment]
I suppose I could have but to stay consistent with my current engine's code base, I went with the GL3 example. :)

**Comment by Extrawurst** [comment]
is it allowed to even call the legacy immediate mode API from a >=3 ogl context ?

**Comment by ocornut** [comment]
Yes of course. Lots of code depends on it and it's quite widely supported (even if it's probably annoying for the drivers maintainers..). OpenGL being such a mess it is quite helpful sometimes.

**Comment by ocornut** [comment]
I'll close this. I realize we're not saving everything. If someone wants to come up with a patch that saves everything I might consider it but I guess it'll be too bulky.

Those two states (shader and textures) are the most likely to break people software who use the GL3 example code in a way that's confusing for a short while. So fixing them is good. The other states we changes consists in disabling depth testing, disabling culling, enabling blending, enabling scissoring, the effect of those leak if any, should be easiest to assess.

**Comment by richardlalancetteyoui** [comment]
Interesting! This is what I have been struggling recently :)
Thanks for sharing!

**Comment by richardlalancetteyoui** [comment]
I believe our engine is breaking IMGUI.
I can render IMGUI in GLFW3 on its own window, but as soon as I combine it with our SDK, our engine renders, but IMGUI is gone.

I doubt it has anything to do with IMGUI, probably something in our SDK.

**Comment by ocornut** [comment]
Ideally if you could narrow it down to which GL state is getting in the way we should patch imgui_impl_opengl3 to explicitely reset/set/restore it.

**Comment by richardlalancetteyoui** [comment]
Yup, I guess, that's my next step. Using opengl2 ATM.

**Comment by ocornut** [comment]
Thats likely the first source of your problem, you shouldn’t use the _opengl2 code with modern opengl, it’s written all over this back-end.

**Comment by richardlalancetteyoui** [comment]
Ah! opengl3 it is then! Thank you!

**Comment by richardlalancette** [comment]
Looks like I'm stuck with OPENGL2 for now. Until the SDK group upgrades to 3.

**Comment by richardlalancette** [comment]
I'll fix the render states and hopefully post a PR soon.

**Comment by ocornut** [comment]
Thank you!
