### ISSUE TITLE
How is it you can put conditional statemente before other parts of UI?

### ISSUE THREAD

**Issue by trusktr** [ocornut/imgui#1952]
I'm looking at the README, and I see:

```cpp
ImGui::Text("Hello, world %d", 123);
if (ImGui::Button("Save"))
{
    // do stuff
}
ImGui::InputText("string", buf, IM_ARRAYSIZE(buf));
ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
```

I'm so confused. How is it that the input and slider can appear in the UI before the user has clicked save, yet in the code the input and slider come after the conditional which is checking for the save button click?

From the snippet I am imagining this code running only once. Am I missing something? Is this in a render loop repeatedly or something?

**Comment by franciscod** [comment]
> Is this in a render loop repeatedly or something?

Yes :) right before the code, on the README:

> After Dear ImGui is setup, you can use it from _anywhere_ in your program loop:

**Comment by ocornut** [comment]
This is the key thing with the IMGUI paradigm. Yes, the UI is refreshed every frame (well, as long as you call the code). You can read some the Links provided in the Readme to understand more about how it works.

**Comment by ice1000** [comment]
> From the snippet I am imagining this code running only once.

No, it runs once per frame. If your display card doesn't support vsync (like mine) it'll run like 5000 times per second.

**Comment by ocornut** [comment]
You can choose to render at maximum speed (here 5000 fps) but you certainly don’t have to and probably shouldn’t even if your gpu setup doesn’t vsync. You can cap the refresh speed with a timer or even go idle if there are no input events.

**Comment by ice1000** [comment]
@ocornut I know, I have written a frame locker myself..

**Comment by ocornut** [comment]
@trusktr Closing this as I feel we have answered you.
