### ISSUE TITLE
Two Histograms in one

### ISSUE THREAD

**Issue by kenkit** [ocornut/imgui#1955]
Hi,
How can I plot two histograms in one graph ?
Like one in blue another in green on the same chart.
Thanks in advance

**Comment by Nukem9** [comment]
https://github.com/ocornut/imgui/issues/632#issuecomment-302987492 ?

**Comment by ocornut** [comment]
Thanks @Nukem9 . Closing this thread as #632 seems to answers it.
I would like to redesign Plot functions in the future to make this an easy thing to do.

**Comment by kenkit** [comment]
Thank,s for your assistance, I've been offline lately. But am still working hard to complete this project soon. So far I think am doing good.
![capture](https://user-images.githubusercontent.com/1732471/43109429-77992282-8eef-11e8-9838-263b597f5468.PNG)

**Comment by kenkit** [comment]
Hehe, those were the two graphs I wanted to merge into one. I hope it's possible to set colors for each once i've merged them into one

**Comment by kenkit** [comment]
@ocornut Is there an example I can use ?
I need to merge this two arrays which I plot like this 
`        ImGui::Text("DL");
        ImGui::PushItemWidth(-1);
        ImGui::PlotHistogram("", download_log, IM_ARRAYSIZE(download_log),
            current_log, std::string("speed " + std::to_string(download_speed) + std::string(rate[current_rate].symbol)).c_str(), 0.0f, max_value, ImVec2(0, 80));
        ImGui::PopItemWidth();
        ImGui::Text("UL");
        ImGui::PushItemWidth(-1);
        ImGui::PlotHistogram("", upload_log, IM_ARRAYSIZE(upload_log),
            current_ul_log, std::string("speed " + std::to_string(upload_speed) + std::string(rate[current_rate].symbol)).c_str(), 0.0f, max_ul_value, ImVec2(0, 80));
        ImGui::PopItemWidth();`

**Comment by ocornut** [comment]
The code in #632 should allow you to do that. There’s no official solution, but you can paste the code in that other thread into your own .cpp file (it will need to include imgui_internal.h) to have a widget that can render multiple data set, and tweak the widget accordingly.

Otherwise, you may also copy the code for PlotHistogram() and create your own function out of it.

**Comment by kenkit** [comment]
It seems I failed to clearly explain what I need.
Is it possible to use that function without the getter ? I mean like passing an array directly as I did above
