### ISSUE TITLE
_gl3wProc Unresolved External

### ISSUE THREAD

**Issue by BurnoutBen** [ocornut/imgui#1956]
**Version/Branch of Dear ImGui:**

dear imgui, v1.63 WIP

**Back-end file/Renderer/OS:** _(if the question is related to inputs/rendering/build, otherwise delete this section)_

Windows 10, 64bit.

**My Issue/Question:** _(please provide context)_

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
When compiling my DLL (which currently doesn't even do anything I have just included the files) I get a LNK1120 Error for unresolved external of _gl3wProcs. I have included imconfig.h, imgui.h, imgui_impl_opengl3.h, imgui_impl_win32.h, imgui_internal.h, stb_rect_pack.h, stb_textedit.h and stb_truetype.h included in my project. I am also using imgui.cpp, imgui_draw.cpp and imgui_impl_opengl3.cpp.

Compiler Output.
```
1>------ Build started: Project: Testing ImGUI, Configuration: Release Win32 ------
1>dllmain.cpp
1>imgui_impl_opengl3.cpp
1>imgui_impl_opengl3.obj : error LNK2001: unresolved external symbol _gl3wProcs
1>C:\Users\Bens PC\Desktop\Coding\Visual Studio\C++\AssaultCube\Learning ImGUI\Testing ImGUI\Release\Testing ImGUI.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "Testing ImGUI.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Screenshots/Video** _(you can drag files here)_

![devenv_2018-07-20_20-54-02](https://user-images.githubusercontent.com/32690103/43022438-344997f6-8c5f-11e8-8293-503d744eda93.png)
![explorer_2018-07-20_20-55-26](https://user-images.githubusercontent.com/32690103/43022448-401bc766-8c5f-11e8-9b44-7d17a8c8d771.png)

**Comment by ocornut** [comment]
You need to link with gl3w.c if you use it in the default opengl3 bindings.
