### ISSUE TITLE
right align element on sameLine to window size

### ISSUE THREAD

**Issue by Extrawurst** [ocornut/imgui#196]
imagine a window with always autosize and a treenode structure where every node is extended with a button on same line. how could i align those buttons all to the right side of the window?

this shot illustrate the "X" buttons:
![2015-04-15 editorinspectors](https://cloud.githubusercontent.com/assets/776816/7157780/354ba97a-e373-11e4-8951-469a6759ba5d.png)

**Comment by ocornut** [comment]
The easiest right now would be to change your SameLine() to something like SameLine(GetWindowWidth()-30);

But I'm not sure how that'll play with always auto-resize, probably not so well (you can try). A possible solution later down the road would be to specify this sort of layout at a higher-level using some layout helper and among other things it would know how that can create a feed-back loop with auto-resize. Right now a variation on what's above is probably the best bang for buck.

**Comment by Extrawurst** [comment]
that did the trick, thanks! that was easier than I thought ^^
![screen shot 2015-04-15 at 14 03 58](https://cloud.githubusercontent.com/assets/776816/7158242/58ce945c-e378-11e4-9cb4-c6d05a935fca.png)

**Comment by Extrawurst** [comment]
I may have to reopen this issue, if i put a second smallbutton into the  sameline the window extends itself "sometimes" 1 pixel per frame in width. any ideas why ? and how do you record those short "screen caps" that you sometimes post as gifs ? i could use that to show u my problem..

**Comment by Extrawurst** [comment]
![image](https://cloud.githubusercontent.com/assets/776816/7204097/dd5121f6-e51f-11e4-8bdd-45bf774026c7.png)

maybe the screenshot is enough it seems the problem just occurs because a scrollbar appears ...

**Comment by ocornut** [comment]
I am using GifCam for the gifs.

If your window is auto-resizing and you are drawing outside of its bounds then that will keep resizing forever... So if you want to use auto-resize AND query the window width to place your widgets you need to make sure they don't extend the window in a feedback loop.

Ideally please post repros :)

**Comment by Extrawurst** [comment]
Thanks so much for all the support!
