### ISSUE TITLE
Request: Multi Selection Combo box for older version of ImGui?

### ISSUE THREAD

**Issue by synvy** [ocornut/imgui#1963]
I am using ImGui 1.51 and would love to upgrade but I have changed so much inside the ImGui files that it would be more pain than it's worth to upgrade to a newer version than to just ask if anyone has this.

I am looking for a combo box that allows me to select multiple items inside then display as such:

The selected options would show as such when selected:

[option 1, option 2, optio...]

I know in the newer version of ImGui this is possible with ImGui::BeginCombo / ImGui::EndCombo then using ImGui::Selectable inside of those, but as I said, I am using an older version of ImGui and it would be more pain than it's worth to upgrade.

Any help would be appreciated.

**Comment by ocornut** [comment]
Sorry but #1586
