### ISSUE TITLE
Viewport SetNextWindowPos Error

### ISSUE THREAD

**Issue by durswd** [ocornut/imgui#1970]
**Version/Branch of Dear ImGui:**

viewport Branch 0095b7a 

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
OS: Windows10
Compiler: Visual Studio 2015

**My Issue/Question:** _(please provide context)_

SetNextWindowPos assigns absolute position to window.
For example, ```ImGui::SetNextWindowPos(ImVec2(80, 80));``` fix a window on (80, 80) on a desktop even if this window is in main window.

This bug can fix below codes. But rendering is wrong in a frame.

```
static void SetWindowPos(ImGuiWindow* window, const ImVec2& pos, ImGuiCond cond)
{
    // Test condition (NB: bit 0 is always true) and clear flags for next time
    if (cond && (window->SetWindowPosAllowFlags & cond) == 0)
        return;

    IM_ASSERT(cond == 0 || ImIsPowerOfTwo(cond)); // Make sure the user doesn't attempt to combine multiple condition flags.
    window->SetWindowPosAllowFlags &= ~(ImGuiCond_Once | ImGuiCond_FirstUseEver | ImGuiCond_Appearing);
    window->SetWindowPosVal = ImVec2(FLT_MAX, FLT_MAX);

    // Set
	ImVec2 new_pos;
	if (window->ViewportOwned)
	{
		new_pos = pos;
	}
	else
	{
		new_pos = pos + window->ViewportPos;
	}

	const ImVec2 old_pos = window->Pos;
	window->Pos = ImFloor(new_pos);
	window->DC.CursorPos += (window->Pos - old_pos);    // As we happen to move the window while it is being appended to (which is a bad idea - will smear) let's at least offset the cursor
	window->DC.CursorMaxPos += (window->Pos - old_pos); // And more importantly we need to adjust this so size calculation doesn't get affected.
}

```

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_

```
ImGui::SetNextWindowPos(ImVec2(80, 80));
ImGui::Begin("Hello, world!");
ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

![image](https://user-images.githubusercontent.com/5775729/43329677-10f5e1f4-91fc-11e8-9d9b-b654f5ec6a0a.png)

![image](https://user-images.githubusercontent.com/5775729/43329693-1d593d60-91fc-11e8-9ae7-f6cf82e3ae68.png)

**Comment by ocornut** [comment]
This is very intentional and one of the breaking change of the Viewport branch:
```
2018/XX/XX (1.XX) when multi-viewports are enabled, all positions will be in your natural OS coordinates space. It means that:
- Reference to hard-coded positions such as in SetNextWindowPos(ImVec2(0,0)) are probably not what you want anymore. 
you may use GetMainViewport()->Pos to offset hard-coded positions, e.g. SetNextWindowPos(GetMainViewport()->Pos)
- Likewise io.MousePos and GetMousePos() will use OS coordinates coordinates. 
If you query mouse positions to interact with non-imgui coordinates you will need to offset them, e.g. subtract GetWindowViewport()->Pos.
```

If you have hard-coded position you need to replace your code to offset the position:

`ImGui::SetNextWindowPos(ImGui::GetMainViewport()->Pos + ImVec2(80, 80));`

**Comment by durswd** [comment]
Thank you for your information.
I need to read all references.

**Comment by ocornut** [comment]
When Viewports (#1542) make it to a release on master will have to make this change extra clear in the release notes. The difference only exists if viewports are explicitly enabled, but it will probably bite quite a few users.

If you have any suggestion on how to improve the documentation and/or function call don't hesitate!

**Comment by zx64** [comment]
I have almost an opposite use case related to this issue - I'd like to be able to use `SetNextWindowPos` (or a different API) to force a window to be created in a new viewport if needed (e.g. a Debug UI that floats alongside the main window).

**Comment by ocornut** [comment]
We could give a special meaning to e.g.
`SetNextWindowViewport(-1)`
For this purpose?

**Comment by zx64** [comment]
Works for me. :-)

**Comment by ice1000** [comment]
Agreed
