### ISSUE TITLE
Question: Where did you learn batching and gui techniques?

### ISSUE THREAD

**Issue by JaroMalonoar** [ocornut/imgui#1971]
Where did you learn batching and gui techniques, and where would I find/learn advanced/best efficient rendering (I know basics instancing etc. etc.)?

**Comment by ocornut** [comment]
Hello @JaroMalonoar, there's no simple single answer to that question. I never really formally learned GUI stuff aside from trying to write my own (all my early projects has strong GUI components so I guess I had interest in that). Most of those skills were built up while trying to make games over the years, making lots of tooling, understanding performances constraints specific to game development, the dynamic of game teams, learning from experience and colleagues. 

I'm sorry I don't have a great answer to provide you as I am rather disconnected from learning materials available nowadays. However I am sure there are enough resources on the internet. I think the key to learning is to just trying making stuff, don't focus on learning techniques in vacuum: "batching" "best efficient rendering" are vague hollow words that can mean a million different things depending on the context. Nobody goes to a course to learn "batching". Focus on the end not the mean: making a concrete app/game/experiment/product happening! The tools you need to make it happen, with perseverance you will find and learn them along the way.

Good luck!

**Comment by JaroMalonoar** [comment]
Thanks!
