### ISSUE TITLE
Question: Why primitives position are based on screen dims

### ISSUE THREAD

**Issue by iScrEamM** [ocornut/imgui#1976]
Why positon is set from x: 0 - 1280; y: 0 - 720 even if projection is {-1.0f, 1.0f, -1.0f, 1.0f }? What controls it?

**Comment by ocornut** [comment]
The projection matrix project pixel coordinates positions into normalized view position.
That code is in the imgui_impl_XXX renderer you are using.

**Comment by iScrEamM** [comment]
Yes, in imgui_impl_opengl3 there is a projection matrix which projects into NDC, so adding new rect should be relative to NDC, not screen with and height. Like this:
```AddRect(Vector2(-0.3f, 0.3f), Vector2(0.3f, -0.3f), color);``` - that's how it should be with projection NDC
instead of 
```AddRect(Vector2(100, 300), Vector2(1120, 600), color); ``` - that's how it is now if sdl window w = 1280; h = 720;

**Comment by iScrEamM** [comment]
Oh, I see now, sorry! I've got one more question. What controls widgets while changing sdl window size (they stay the same size, etc.)?

**Comment by ocornut** [comment]
Widgets are not affected by Platform Window Size.

Widgets are affected by ImGui Window Size. Check the Demo window under “Layout” for some examples of how it is done.

**Comment by iScrEamM** [comment]
imgui windows act the same. They stay the same size while window resolution is changing. When I am rendering simple unfilled rect in my app, different resolutions cause different sides of quads to be different thickness. Like for example 1280x720:
![image](https://user-images.githubusercontent.com/37987816/43365701-f9202392-9330-11e8-8b04-185d18333782.png)

when thickness is too small only 2 sides are shown

1920x1080:
![image](https://user-images.githubusercontent.com/37987816/43365708-1b2f2550-9331-11e8-8d26-074951eee7ff.png)

thickness is the same and all sides are shown, but rect gets bigger thanks bigger resolution.

imgui windows stay the same all the time.

**Comment by ocornut** [comment]
Your projection matrix or framebuffer size are incorrect. Sorry this isn’t an imgui question and I can’t helping much further. For imgui questions please provide clear minimum-complete-reproduce-example as instructed by the Contributing guidelines and Issue Template.
