### ISSUE TITLE
Create Texture for ImGui::Image (DirectX 11)

### ISSUE THREAD

**Issue by MrArting** [ocornut/imgui#1979]
Hello. I want to ask how to create texture for ImGui::Image properly in DirectX 11 from PNG file? 
In DirectX 9 I using D3DXCreateTextureFromFileInMemoryEx, and all is fine:
![dota2_2018-07-29_16-57-40](https://user-images.githubusercontent.com/19289745/43367116-bba0c420-9350-11e8-9c40-235620e2a45e.png)

In DirectX 11 I tryed to use D3DX11CreateShaderResourceViewFromMemory, but something wrong with colors (too much white):
![dota2_2018-07-29_16-53-52](https://user-images.githubusercontent.com/19289745/43367128-0b93efde-9351-11e8-845f-e8cbc1fc623e.png)

How can I fix this problem?

**Comment by ocornut** [comment]
`ImGui::Image()` create vertices that are rendered by the example binding imgui_impl_dx11.cpp, there's no processing or modification or magic performed by dear imgui, it doesn't even know anything about your textures, it's just passing data around. 

This is probably a sRGB vs Linear Space issue with your setup, see #1927.

**Comment by ocornut** [comment]
(Adding ref in some old issues for searching purpose) 

There’s a tutorial to load textures with various graphics api here: https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

**Comment by yaroslavhorokhovets** [comment]
@ MrArting , Nice to meet you. Excuse me, could you send me your source code used DirectX9? So, I can solve your issue perfectly.
