### ISSUE TITLE
Question: Where scaling rendered objects takes place?

### ISSUE THREAD

**Issue by DonTweaks** [ocornut/imgui#1981]
I am wondering where scaling for instance rect takes place. Even when display size is bigger or smaller it stays fit and nice drawn. What method does it? I have been trying to figure it out removing some methods from drawlist like: 
- channels
- clip rect
- antialiasing
- in function with draw call I disabled blending, culling, blending, texture - everything except vao, vbo, ebo, projection matrix, viewport  and shader

and it still rendered the same, so it has to be another option.
What makes primitives scaled?

High resolution:
![image](https://user-images.githubusercontent.com/29126744/43369801-56d02b66-9374-11e8-9365-53c0e60d33dd.png)
Low res:
![image](https://user-images.githubusercontent.com/29126744/43369809-6ed8045e-9374-11e8-83f7-ae3c67ef4e3c.png)

Does not it look the same size and without any thickness or rect sides problems?

**Comment by ocornut** [comment]
Just saw your edit and details (they don’t appear in the e-mail notifications)... there’s NO scaling as you have noticed, objects are displayed with the same pixel size, this is why they look the same way. io.DisplaySize which represent the total available space but that doesn’t impact the way items are rendered, it only impacts the projection matrix that is setup in imgui_impl_xxx to translate from pixels to screen space.

**Comment by DonTweaks** [comment]
I am not sure how it works. It seems to my like it is scaled like:

```
vector2 scale = vector2(displaySize.x / 1280, displaySize.y, 720)
position.x / scale.x
position.y / scale.y
size.x / scale.x
size.y / scale.y
```

and then add rect with those values as positon and dimension of a rect 

more using your code if I did explain it wriedly

I change PathRect() -> `a` to be ` x, y`; ->`b` to be` w, h`

```
void ImDrawList::AddRect(const ImVec2& a, const ImVec2& b, ImU32 col, float rounding, int rounding_corners_flags, float thickness)
{
    if ((col & IM_COL32_A_MASK) == 0)
        return;

    PathLineTo(a);
    PathLineTo(ImVec2(a.x, a.y + b.y));
    PathLineTo(a + b);
    PathLineTo(ImVec2(a.x + b.x, a.y));

    PathStroke(col, true, thickness);
}

//in ImGui::Begin() somewhere

//Draw rect on position {100, 100} and with size {50, 50} and thickness 1 and scale it
ImVec2 scale = ImVec2(displaySize.x / 1280, displaySize.y, 720);
window->DrawList->AddRect(ImVec2(100.0f / scale.x, 100.0f / scale.y), ImVec2(50.0f / scale.x, 50.0f / scale.y), 0.0f, 0, 1.0f);
```

but you said it is not scaled by anything, so if it would not be, it should act like this (this is  I guess a square when resolution is 1280x720 and change his nature on different resolution)
![image](https://user-images.githubusercontent.com/29126744/43370978-06be954e-9389-11e8-8e6c-3765a90927cc.png)
with resolution 1702x517 (a random one)

a scaling by this vector `scale` should cause this rect to be all the time a squere.

**Comment by ocornut** [comment]
I'm sorry @DonTweaks I don't have the time/bandwidth to explain how an orthogonal projection matrix works, please research it or discuss it on general graphics/programming community. Here isn't really the place, this place is for discussing imgui features and development. If other people want to answer feel free to, but for now I'll be closing this thread.
