### ISSUE TITLE
InvisibleButton with height 0 doest trigger BeginDragDropTarget

### ISSUE THREAD

**Issue by bear24rw** [ocornut/imgui#1983]
If I use an InvisibleButton with height 0 it does not trigger BeginDragDropTarget. This is inside a BeginChild block.

```c++
// ImGui::Button(" ", ImVec2(10,0));  // works
// ImGui::InvisibleButton(" ", ImVec2(10,0)); // doesnt work
ImGui::InvisibleButton(" ", ImVec2(10,10)); // works
if (ImGui::BeginDragDropTarget()) {
```
----

**Version/Branch of Dear ImGui:**

6211f40f3d903dd9df961256e044029c49793aa3 / Master

**Back-end file/Renderer/OS:**

example_glfw_opengl3

**Comment by ocornut** [comment]
Hello,

I am not sure what you are expecting here? You cannot reach or hover a zero-sized object.

**Comment by ocornut** [comment]
Clarification, since your example shows Button in the comment:
A regular `Button()` uses the label size when one axis is zero, so `Button(" ", ImVec2(10,0")` will have the default height (which is `GetFrameHeight() == FontSize+FramePadding.y*2`).

`InvisibleButton` doesn't have a default size because there's no label so if you have a ImVec2(0,0) sized-button it will take no space.

**Comment by bear24rw** [comment]
Your explanation makes sense. I assumed that InvisibleButton would act totally identical to a button in every way except that it's... invisible. Does it make sense to have InvisibleButton act differently? Is there a use case where one wants a 0 px dimension?

Specifying GetFrameHeight() as the invisible buttons height is what I needed, thanks!

**Comment by ocornut** [comment]
It's a semi-common pitfall unfortunately. I have now added an assert in `InvisibleButton()` to catch this situation more clearly. There is indeed no point is passing a 0 px dimension as far as I know.

Notice the function signatures are different in two ways:
```
bool  Button(const char* label, const ImVec2& size = ImVec2(0,0));
bool  InvisibleButton(const char* str_id, const ImVec2& size);
```

- `label` becomes `str_id` - we use this terminology everywhere in imgui.h to differentiate strings that may be visible from strings that are not.
- There is no default value for `size`.

I realize that both differences are subtle and very easy to overlook. I think adding the extra is a good thing.

**Comment by bear24rw** [comment]
I would argue for making size 0 default to something (like GetFrameHeight for y) but I guess there is no good default width?

The assert will definitely at least make it clear that it's a user error, not a imgui bug.
