### ISSUE TITLE
Program Crashes Due To Incorrect Initialisation?

### ISSUE THREAD

**Issue by BurnoutBen** [ocornut/imgui#1987]
**Version/Branch of Dear ImGui:**

1.63 WIP

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_
Windows 10, OpenGL

Back-ends: imgui_impl_opengl3.cpp

**My Issue/Question:** 
I have hooked the SwapBuffers function of OpenGL in a game. I then initialise ImGui in this hooked function (same thread as games OpenGL so can easily access it.) When I call ImGui::ShowDemoWindow(); my game crashes due to line 6445 of imgui.cpp which consists of `window->DrawList->PushTextureID(g.Font->ContainerAtlas->TexID);`

The crash message states it is a Win32 Exception: 0xc0000005 [0x44]

Clearly I am not initialising ImGui properly.

My Code In The Hooked Function
```
BOOL __stdcall hwglSwapBuffers(_In_ HDC hDc)
{
	if (!ImGUI_Initialized) {
		setup_ortho();
		ImGuiContext* context = ImGui::CreateContext();
		ImGui::SetCurrentContext(context);
		ImGuiIO& io = ImGui::GetIO();

		io.DeltaTime = 1.0f / 60.0f;
		io.DisplaySize.x = 1920;
		io.DisplaySize.y = 1080;

		io.Fonts->AddFontDefault();
		unsigned char * pixels;
		int width, height, bytes_per_pixels;
		io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height, &bytes_per_pixels);
		
		ImGui_ImplOpenGL3_Init(NULL);
		ImGUI_Initialized = true;
		std::cout << "ImGui Initialized..." << std::endl;
	}

	ImGui::ShowDemoWindow();

	//Test to see if OGL was hooked correctly
	//glBegin(GL_LINES);
	//glVertex2f(100, 100);
	//glVertex2f(200, 200);
	//glEnd();

	return owglSwapBuffers(hDc);
}
```

setup_ortho() function. Was told to add this by another user who had similar issues with rendering menu etc. Doesn't seem to affect my code with or without it.
```
void setup_ortho() {
	glPushAttrib(GL_ALL_ATTRIB_BITS);
	glPushMatrix();
	GLint viewport[4];
	glGetIntegerv(GL_VIEWPORT, viewport);
	glViewport(0, 0, viewport[2], viewport[3]);
	glMatrixMode(GL_PROJECTION);
	glLoadIdentity();
	glOrtho(0, viewport[2], viewport[3], 0, -1, 1);
	glMatrixMode(GL_MODELVIEW);
	glLoadIdentity();
	glDisable(GL_DEPTH_TEST);
}
```
**Screenshots/Video** _(you can drag files here)_
![image](https://user-images.githubusercontent.com/32690103/43288481-e964b0de-911f-11e8-98fb-90fd105900a1.png)

**Comment by ocornut** [comment]
You forgot to call `ImGui::NewFrame()`, please follow on the example application code.

**Comment by ocornut** [comment]
I have tweaked the asserts to get a clearer error when calling Begin() outside of the NewFrame/EndFrame scope.

In the past NewFrame() was initializing the context so you would have gotten an assert on the various `IM_ASSERT(g.Initialized);` tests, but this tests became less useful as we switched to the explicit CreateContext() calls which performs the initialization. New asserts are added now.

**Comment by BurnoutBen** [comment]
Even after adding the `ImGui::NewFrame()` and `ImGui_ImplOpenGL3_NewFrame()` functions then calling ImGui::ShowDemoWindow() I get another crash with error message Win32 Exception: 0xc0000005 [0x0] because of line 309 of imgui_implopengl3.cpp.

Excuse me if I am being stupid as I haven't worked much with graphics before.

![ac_client_2018-07-30_17-29-29](https://user-images.githubusercontent.com/32690103/43410236-2b479f6a-941e-11e8-8c45-746a86481db9.png)

**Comment by ocornut** [comment]
I don't know what on line 309 without knowing your exact git version #. 
Please use a debugger to trace into the code, and if you are using imgui_impl_opengl3.cpp unmodified, which rely on the gl3w OpenGL loader you need to initialize gl3wInit() as done in the example application.
