### ISSUE TITLE
ImGui::ShowStyleEditor uses deprecated API (plus fix)

### ISSUE THREAD

**Issue by Alzathar** [ocornut/imgui#1990]
**Version/Branch of Dear ImGui:** 1.63WIP (master branch, commit 65b46f6)

Compiler: MSVC 15

When the macro `IMGUI_DISABLE_OBSOLETE_FUNCTIONS` is defined, the linker complains about the missing function `ImGui::InputFloat` in `ImGui::ShowStyleEditor`. The problem is at the line [imgui_demo.cpp:2496](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L2496) (deprecated integer precision API).

This line should be replaced by:

```c++
ImGui::InputFloat("Font offset", &font->DisplayOffset.y, 1.0f, 1.0f, "%1.0f");
```

Note: I decided to not create a PR for this one line modification, but if you prefer I will create it.

**Comment by ocornut** [comment]
Thanks @Alzathar , fixed now. How did you even notice?

Because the value used in the demo is 0, in all my test scripts (I'm compiling with Clang and GCC with and without `IMGUI_DISABLE_OBSOLETE_FUNCTIONS`) it wasn't caught, for the simple reason that that 0 was promoted to (const char*)NULL and calling the other version.

(I tried with both Visual Studio 2015 and 2017 with IMGUI_DISABLE_OBSOLETE_FUNCTIONS with warning level 4 and it didn't trigger a warning either.)

**Comment by Alzathar** [comment]
I guess I was lucky to find it 😄. 

More seriously, the best answer I can give you is because I compile `imgui.cpp` in a static library and `imgui_demo.cpp` in a binary linked to this library. When I include and use `imgui_demo.cpp` in the library, the linker does not complain (tested in my project with MSVC 15 and with Clang for the Dear ImGui example 'example_imgui_glfw_opengl3' w/ and w/o the macro `IMGUI_DISABLE_OBSOLETE_FUNCTION` defined).

To rationalize this answer, I would say that the mangled symbols for the deprecated API are not generated in the static library. Then, the linker does not find the symbol for the function `ImGui::InputFloat(char const *,float *,float,float,int,int)` when it links the library with the binary.

When the files `imgui.cpp` and `imgui_demo.cpp` are compiled in the same project, I guess  the compiler look for existing symbols and it promote the value `0` to `(const char *)NULL` to fit with the known function. Thus, the linker does not complain.

To give more evidence to this answer, I tried with different settings (x86, x64, Debug, Release, C++11, C++17) with MSVC 15.7.5 and Windows SDK 10.0.17134.0 and each time, the linker throws the following error (same thing for Clang under macOS):

```
imgui_demo.cpp.obj : error LNK2019: unresolved external symbol "bool __cdecl ImGui::InputFloat(char const *,float *,float,float,int,int)" (?InputFloat@ImGui@@YA_NPEBDPEAMMMHH@Z) referenced in function "void __cdecl ImGui::ShowStyleEditor(struct ImGuiStyle *)" (?ShowStyleEditor@ImGui@@YAXPEAUImGuiStyle@@@Z)
```

**Comment by ocornut** [comment]
This looks like a case where you are not defining `IMGUI_DISABLE_OBSOLETE_FUNCTION` across all compilation units. It is defined in imconfig.h or for all the cpp involved?

**Comment by Alzathar** [comment]
You are right. I defined the macro only for the library and not the binary. Thanks to point me this problem.
