### ISSUE TITLE
Name-Value property UI

### ISSUE THREAD

**Issue by SuperWangKai** [ocornut/imgui#1991]
I found that in the sample of imgui, as for the properties (name-value) panel, the value is always on the left while the name of the property is on the right. This is not a common practice. For most of the tools, it's better if we put name on the very left so user can find a certain property quicker.

I've tried to put the label on the left, and the value widgets on the right, and this will make the layout a mess.
And also I have tried `Columns` and it turned out that it's not working with `CollapsingHeader`, as the later will be cut off by the `Column`...

So we need a solution.

**Comment by ocornut** [comment]
> This is not a common practice. For most of the tools, it's better if we put name on the very left so user can find a certain property quicker.

This is not a common practice but it allows for easier and more flexible layout (you can add extra items on the right) and make clipping simpler.

> I've tried to put the label on the left, and the value widgets on the right, and this will make the layout a mess. And also I have tried Columns and it turned out that it's not working with CollapsingHeader, as the later will be cut off by the Column...

You can close the Columns set when you need to use a CollapsingHeader and re-open it. It's not ideal but it should work.

There is a Property Editor applet in the demo which does that, have you checked it?
![image](https://user-images.githubusercontent.com/8225057/43512696-11248b98-957c-11e8-82a1-acd1e5a8a96b.png)


There's an open task for it #395 so doing to close it as duplicate.

**Comment by SuperWangKai** [comment]
Thank you very much! However, if I close the Columns and reopen it, I cannot control the column position since there will be many individual splitters...

**Comment by ocornut** [comment]
The Columns will be synchronized _however_ there will be a small shearing/lag between them at the moment.

**Comment by SuperWangKai** [comment]
Thank you for all the explaination! I should have tried it harder...

However, there remains last issue for me. How can I make the Column ratio act like splitter, so the space on the right can be larger and when user enlarge the window, the space on the right can grow faster (e.g. keeping the ratio or keeping left space unchanged) ?

![default](https://user-images.githubusercontent.com/15721569/43525217-c47f4d8e-95d3-11e8-9858-3911ac21025d.png)

Many thanks!

**Comment by ocornut** [comment]
It’s not possible at the moment unless you fiddle with columns offset manually (eg: remember the _width_ of the first column when it is being moved, and reapply this width).

**Comment by ocornut** [comment]
Really wish Columns were better, they are pretty terrible at the moment :( one thing at a time..

**Comment by SuperWangKai** [comment]
You are definitely right! One thing at a time!
