### ISSUE TITLE
Is there a proper way to disable imgui from auto updating mouse and keyboard inputs?

### ISSUE THREAD

**Issue by elect86** [ocornut/imgui#1995]
In our imgui port we just created a new couple of BackendFlag on the same direction of `ConfigFlag.NavNoCaptureKeyboard` in order to prevent imgui from [updating itself](https://github.com/kotlin-graphics/imgui/blob/master/src/main/kotlin/imgui/impl/LwjglGlfw.kt#L121) the mouse status

But I just wonder if this is really the right way or we are supposed to do something else since this shall be a pretty common scenario for those who need it in VR and want to pass for example the vive touchpad as mouse input.

**Comment by ocornut** [comment]
Once you have a custom backend, which you do, there’s no reason for you to use BackendFlags. Just pass the information you need with your own variables/functions?

The point of those flags is to have a shared api for standard option.

Btw your naming “NoCaptureMouse” is very misleading here, as there’s already a concept of Capture in the API. And BackendFlags are meant to denote capatabilities (they are written only by the backend not by the app). So your hypothetical standard flag should be ImGuiConfigFlags_NoMouseUpdate and not ImGuiBackendFlags_NoMouseCapture.

**Comment by elect86** [comment]
Thanks Omar for the tips, very useful
