### ISSUE TITLE
How to make shadows on combobox and buttons

### ISSUE THREAD

**Issue by youngjakepw** [ocornut/imgui#1997]
Hello, how to make shadows on combobox and buttons on imgui?? (Im bad speak english)

Example:
![image](https://user-images.githubusercontent.com/34943801/43568942-b5b63d6a-963e-11e8-9be9-4c661a418164.png)
![image](https://user-images.githubusercontent.com/34943801/43568952-bed60362-963e-11e8-849c-d7733d38eb66.png)

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by Ou7law007** [comment]
You can emulate a shadow by drawing a 1-pixel larger black box using `window->DrawList->AddRectFilled()` (or AddRect) inside ImGui::Checkbox() then drawing your actual inner checkbox.
