### ISSUE TITLE
How to make shadows

### ISSUE THREAD

**Issue by RIPJake** [ocornut/imgui#1998]
Hello ocornut.
How to make shadows. I'm search it not for cheat. I make interface for my game :c 

ss on old issue for example because I've never seen this 

Pls help :c

**Comment by ice1000** [comment]
Make ur own. imgui doesn't support this currently.

**Comment by ice1000** [comment]
I guess ocornut is typing "sorry but #1586 " :stuck_out_tongue_winking_eye:

**Comment by RIPJake** [comment]
But it not for csgo cheats :c

**Comment by ice1000** [comment]
Then why don't you search "shadow" in issue and take a look at #1329 which appears on the first page of the search result?

**Comment by RIPJake** [comment]
Oh, thanks. Exactly what is needed
