### ISSUE TITLE
Rendering ImGui with just a drawTexture function?

### ISSUE THREAD

**Issue by Tim4135** [ocornut/imgui#2000]
Hi,

So I made a very very simple renderer that just takes a texture and renderers with the given x,y,width and height coordinates. the texture class contains an vector with the pixels(r,g,b,a), and the height and width of the texture. It is very limited, I know. But is it enough to render ImGui? I never made a render implementation before, so I don't quite know what it needs.

Thanks!

**Comment by ocornut** [comment]
![sisyphus_2000](https://user-images.githubusercontent.com/8225057/43663511-0d3c1132-976a-11e8-8395-3360948227b4.png)

Hello @Tim4135,

- Have you looked at how the imgui examples renderers are implemented?
There are 10 renderers provided in the examples/ folder which could answer your question.

- Have you read the programmer guide in imgui.cpp?
It has a section called "THIS HOW A SIMPLE RENDERING FUNCTION MAY LOOK LIKE" which explain what you need to do.

You need to render textured triangles with rectangular scissor/clipping support. This is written in maybe a dozen different places in the various comments and examples. Rendering textured triangles is what GPU hardware are good and most-natural at.

Please be a little more considerate when asking questions Tim, if you intend to implement something you should do the minimum amount of research before asking!

-Omar

**Comment by Tim4135** [comment]
May I ask what `MyEngineDrawIndexedTriangles` does?
I think it is the only needed thing I am missing right now. Right?
So ImGUi creates a list of 2d meshes, and textures. Are it also multiple textures, or do the meshes have texture coordinates and one texture?
What if my renderer doesn't support meshes(2d or 3d) yet?

**Comment by ice1000** [comment]
Typo: "Are it" -> "Are they"

**Comment by Tim4135** [comment]
@ice1000 Isn't "Are it" correct because I'm talking about one list? But anyways, I edited it. Thanks!
