### ISSUE TITLE
Font Style for Elements

### ISSUE THREAD

**Issue by Sifaus** [ocornut/imgui#2017]
(added dramatic effect for fun) 

I am in a problematic situation. I have a lot of hard-coded and dynamically generated ui elements that need actual font size change. Weight change.

That's is okay, I thought, I can just use different floats when loading fonts and I can also add differently weighted versions of the font. I have also added different fonts to be able to change title bar fonts and all that.

Then I noticed, my God, I need to push/pop these! Both for generated and hard-coded parts of the ui! True horror!  (:p)

So I wanted to ask if I was missing something and if there is a war to change fonts of elements from stylesheet. Something like: 

`style.fonts[titlebars] = fontBold20p;`
`style.fonts[buttons] = fontItalic16p;`
`style.fonts[default] = font16p`
`...`

(`font...p` is `ImFont*`)

Or any way to do something like this? 

Thanks.

**Comment by Sifaus** [comment]
Oh wow that Limit Theory ui looks great! They didn't release any code, right?

So I have two questions now:

Do you know when we can expect styling v2, even roughly? Current minor styling is my biggest (probably only) issue. 

Also how can I help? I'm not that well versed with imgui (just been using it for last few months) but if there is a design somewhere I'd like to read and try to help out. 

As I said before, I am not _that_ good with imgui yet, but I'll post screenshots as soon as I have something nice to show. Making a game from zero (except few libraries like imgui) is a pain. D':

**Comment by ocornut** [comment]
> Oh wow that Limit Theory ui looks great! They didn't release any code, right?

No but I don't think there's anything magic here, probably helpers e.g. Header("xxx") that does the PushFont/Text/PopFont and some layout. You can build yourself those helpers (For consistency, you might want to create them within the `ImGui::` namespace so they can be called ImGui::Header() etc. but you create create them within your own source file, never edit imgui.cpp!)

> Do you know when we can expect styling v2, even roughly? Current minor styling is my biggest (probably only) issue.

No idea sorry. Last time I estimated a task for "roughly next month" has been more than six months ago. 

On the wiki + todo there are lists of things to help with. Styling is a complex/wide topic and imgui has tough perf requirements, so if you aren't already well versed in imgui development the best way you can help is probably just to drop your wishlist and let me interpret them. Dear imgui is always going to be a rather low-level toolkit so don't expect web-quality styling all across the board.

**Comment by Sifaus** [comment]
Alright, thanks! I believe this issue is now resolved.
