### ISSUE TITLE
strange issue found , bad texture , and not capturing mouse click on Chinese computers

### ISSUE THREAD

**Issue by IdontCare94** [ocornut/imgui#2018]
I made a menu and it works perfectly on my computer but i send it to my Chinese friend , it has bad texture and not capturing mouse clicks , same window 10 , but mine is English version , and my friend is Chinese version 
Sorry for bad English

**Comment by ocornut** [comment]
We can’t help if you aren’t providing enough information and not answering the questions asked when creating an Issue.

**Comment by IdontCare94** [comment]
https://media.discordapp.net/attachments/469048901475893249/478212221319774208/unknown.png?width=1039&height=585

https://images-ext-2.discordapp.net/external/F6OXZv1yDW4CHuE-aJeFmMrcmiFsuC8N6QOKjogaH4A/https/media.discordapp.net/attachments/469048901475893249/478202908643557377/Capture.PNG

**Comment by IdontCare94** [comment]
Its External overlay 

	WNDCLASSEX wc;
	ZeroMemory(&wc, sizeof(WNDCLASSEX));
	wc = { sizeof(WNDCLASSEX), ACS_TRANSPARENT, WndProc, 0L, 0L, GetModuleHandle(NULL), NULL, LoadCursor(NULL, IDC_ARROW), NULL, NULL, L"RTTS", NULL };
	RegisterClassEx(&wc);
	hwnd = CreateWindowEx(WS_EX_TOPMOST | WS_EX_TOOLWINDOW | WS_EX_LAYERED, wc.lpszClassName, L"", WS_POPUP, 0, 0, Screen_X, Screen_Y, NULL, NULL, wc.hInstance, NULL);
	SetLayeredWindowAttributes(hwnd, 0, 0, LWA_COLORKEY);
    MARGINS margins = { -1 }; 
	DwmExtendFrameIntoClientArea(hwnd, &margins);

**Comment by ocornut** [comment]
Sorry but #1586
