### ISSUE TITLE
IsMouseDoubleClicked on TreeNode results in two doubleclicks

### ISSUE THREAD

**Issue by Extrawurst** [ocornut/imgui#202]
when using ig_IsMouseDoubleClicked after a TreeNode like (pseudo code):
```
Treenode(nodename);
if(IsMouseDoubleCLicked(0))
  printf(nodename);
```

the root nodename is printed AND the actually clicked one too (in that order). note that i render a couple of cascaded treenodes like.. well a tree ^^

**Comment by Extrawurst** [comment]
ok double click has obviously some problems when used on iterated list items or in my case trees. all the items after the one actually double clicked return true aswell...

**Comment by Extrawurst** [comment]
damn i am just realizing double click returns true for the whole frame... my bad, i did not realize the design ...

**Comment by Extrawurst** [comment]
ok wrong again.. i dont get it *sigh*

**Comment by ocornut** [comment]
That returns the mouse state.
You may want to do

if (ImGui::IsItemHovered() && ImGui::IsMouseDoubleClicked())

?

**Comment by Extrawurst** [comment]
yeah that works, thank you!
