### ISSUE TITLE
Round Progress bar

### ISSUE THREAD

**Issue by kenkit** [ocornut/imgui#2020]
Hi,
Is it possible to have  a round progress bar with text at the center like this in imgui ?
Please point me to the right direction. I suppose it's also possible to achieve this using shaders, but I think it would be awesome if IMGUI supported this natively.

![capture](https://user-images.githubusercontent.com/1732471/44051219-ec0f68bc-9f41-11e8-953c-176a43d7b1c5.PNG)

**Comment by ice1000** [comment]
https://gist.github.com/ice1000/865c7666d13b945628254aa00bd9d62d

**Comment by ice1000** [comment]
PLEASE DO A SEARCH BEFORE POSTING ISSUES THANK YOU

**Comment by kenkit** [comment]
Looks, interesting. Let me see if I can get that to work. If I could get the exact version as the one posted above with text,you'd have really helped me out.

**Comment by ice1000** [comment]
```cpp
using ComVec4 = const ImVec4 &;
auto Spinner(float radius, float thickness, int num_segments, ComVec4 color) {
	auto window = GetCurrentWindow();
	if (window->SkipItems)
		return;

	auto &g = *GImGui;
	const auto &style = g.Style;
	auto &&pos = ImGui::GetCursorPos();
	ImVec2 size{radius * 2, radius * 2};
	const ImRect bb{pos, pos + size};
	ItemSize(bb);
	if (!ItemAdd(bb, 0))
		return;

	window->DrawList->PathClear();
	int start = static_cast<int>(abs(ImSin(static_cast<float>(g.Time * 1.8f)) * (num_segments - 5)));
	const float a_min = IM_PI * 2.0f * ((float) start) / (float) num_segments;
	const float a_max = IM_PI * 2.0f * ((float) num_segments - 3) / (float) num_segments;
	const auto &&centre = pos + radius;
	for (auto i = 0; i < num_segments; i++) {
		const float a = a_min + ((float) i / (float) num_segments) * (a_max - a_min);
		auto time = static_cast<float>(g.Time);
		window->DrawList->PathLineTo({centre.x + ImCos(a + time * 8) * radius,
		                              centre.y + ImSin(a + time * 8) * radius});
	}
	window->DrawList->PathStroke(GetColorU32(color), false, thickness);
}
```

This is the code that finally got merged in my own codebase, using C++17

**Comment by ice1000** [comment]
`pos + size` has used this operator

```cpp
static inline ImVec2 operator+(ComVec2 lhs, ComVec2 rhs) { return {lhs.x + rhs.x, lhs.y + rhs.y}; }
```

**Comment by kenkit** [comment]
nice work. I'll test it and see what I can achieve with it. 
I don't think adding text will be a challenge.
Thank you.

**Comment by ice1000** [comment]
> EDIT: Maybe even make it a part of the API where the user can choose the type of progress bar he wants.

What do you mean by "type"? The gist I provided has implemented two types of progress bars, one of those is exactly the progress bar you want, except that it doesn't display the text inside since the font size is fixed and it's very possible for the text to overlap with the circle, making the final widget ugly. You can display the text anywhere simply by `ImGui::Text`.
And if you do a search on "progress indicator", the issue appears on the first page of the search result (there's only two results https://github.com/ocornut/imgui/search?q=progress+indicator&unscoped_q=progress+indicator&type=Issues). Don't ask existing questions again and again to bother the maintainers.

**Comment by kenkit** [comment]
ooh, sorry then. Next time I'll make sure to search thoroughly.

**Comment by kenkit** [comment]
is it possible you guys add a chatt system like gitter ?
It could be usefull for this type of things

**Comment by ice1000** [comment]
![spinner](https://user-images.githubusercontent.com/16398479/44063022-bfbf3df6-9f2c-11e8-9759-dffa0e43be50.gif)

Code:
```cpp
static float val{};
ImGui::Spinner(16);
ImGui::BufferingBar(val, {400, 10});
ImGui::SliderFloat("Buffering Bar Value", &val, 0, 1);
```

**Comment by kenkit** [comment]
I didn't know it's called a spinner, I was searching for "Circle progress bar"

**Comment by ice1000** [comment]
@kenkit if you search "chat room" in this repo you get #1135. You've said to search before asking, dude

**Comment by ocornut** [comment]
There's a chat room at https://gitter.im/ocornut/imgui but it hasn't been used much.
Also opened a forum https://discourse.dearimgui.org/ but haven't been publicizing it yet, will do it soonish.

**Comment by ice1000** [comment]
I've posted std from this issue to discourse lol

**Comment by kenkit** [comment]
Thanks everyone, I managed to get it working with what @ice1000 posted above.

**Comment by kenkit** [comment]
But I could not get the text into the circle

**Comment by kenkit** [comment]
I've updated https://discourse.dearimgui.org/t/modified-code-from-issue-1901-for-spinner/22
