### ISSUE TITLE
Simple way to scroll to a widget and give it keyboard focus?

### ISSUE THREAD

**Issue by kavika13** [ocornut/imgui#2021]
v1.53 (can't easily update right now, in case this is easier in a newer version)

Is there a simple way to scroll to a widget and give it keyboard focus? Right now it seems like I need to jump through some hoops to get it to work right.

The only way I've gotten it to work right:

- Frame 0+: Display widget (...wait for external impulse that triggers set-focus logic)
- Frame 1: Display widget
- Frame 1: `SetScrollHere`
- Frame 2: `SetKeyboardFocusHere`
- Frame 2: Display widget
- Frame 3+: Display widget

If I call `SetKeyboardFocusHere` without calling `SetScrollHere` first, then it does nothing, unless I already have the window scrolled to the right place.

If I call `SetScrollHere` then immediately call `SetKeyboardFocusHere`, either immediately before or immediately after the widget call, then the wrong thing gets focused.

In my experiments, it also seems like `SetScrollHere` and `SetKeyboardFocusHere` have different concepts of "here", and the order they need to be invoked (list at the top) makes it pretty hard to use.

Please let me know if you want a minimal repro to accompany this, or if it is already clear enough.

**Comment by ocornut** [comment]
Hello,

No need for a repro, it's a known issue (see e.g. #343) and I am aware of the inconsistency with the "Here" concept :(

A while ago I started a work-in-progress branch to ditch `SetKeyboardFocusHere()` and replace it with a couple of new helpers, along with reworking the entire Tabbing code which is severely outdated, but I couldn't finish the work and had to move to other tasks. There were a few unsolved issues back then, but I'll like to get back to it - those functions are known to be problematic.

I think a workaround you may use to get `SetKeyboardFocusHere()` to register is to manually set `g.ActiveId = ` to the ID of the item if you are able to obtain it, this will disable clipping. 

Note that 1.60+ has `SetItemDefaultFocus()` which would perhaps do what you need on an Appearing windows.

-Omar

**Comment by kavika13** [comment]
I have successfully worked around this challenge in my code already. I wanted to file this ticket as sort of a "feature request" to make this simpler in some way. Maybe `SetItemDefaultFocus()` already covers it?

**Comment by ocornut** [comment]
`SetItemDefaultFocus()` won't cover your use case at it is designed for the window appearing frame.

The future/intended new API `FocusItem` and `ActivateItem` are aimed at solving this properly.

**Comment by ocornut** [comment]
Closing! Thanks for the reminder that this needs to be sorted out :)
