### ISSUE TITLE
"Link error when compiling dx11 example"

### ISSUE THREAD

**Issue by cmccracken86** [ocornut/imgui#2028]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _D3DCompile@44 referenced in function "bool __cdecl ImGui_ImplDX11_CreateDeviceObjects(void)" (?ImGui_ImplDX11_CreateDeviceObjects@@YA_NXZ)	Project2	C:\Users\User\source\repos\Project2\Project2\imgui_impl_dx11.obj	1	

I am running into this linking issue while trying to run the examples in imgui.cpp.  I am not sure what I am missing to link this and make this work.

I am very new to all this, is there any kind of video or material about the absolute basics of how everything works.  Because I have looked at everything is middle to high level.  I recently graduated college.

**Comment by ice1000** [comment]
Please re-title your issue as "Link error when compiling dx11 example"

**Comment by ocornut** [comment]
Hello Christopher,

It looks like you aren’t linkin with the .lib that contains the d3d compiler. The example should be doing that. If you google the error you are having you should find many answers to your issue.

Omar
