### ISSUE TITLE
Merging Default Font With Third Party Compressed Font 

### ISSUE THREAD

**Issue by clmiti** [ocornut/imgui#2029]
**Version/Branch of Dear ImGui: 1.62

I am attempting to merge Awesome Font with the default imgui font. I have converted the .ttf file over to compressed data using binary_to_compressed_c. I am attempting to merge the fonts in my init function as shown below. Unfortunately when attempting to open my GUI nothing is drawn, even using something simple using the default font such as ImGui::Begin("Debug");. When I remove any reference to merging the fonts the GUI draws fine.

`

	ImGui::CreateContext();
	ImGuiIO& io = ImGui::GetIO();

	int ttf_size;

	const void* ttf_data = ImGuiAl::Fonts::GetCompressedData(ImGuiAl::Fonts::kFontAwesome, &ttf_size);

	if (ttf_data) {

		io.Fonts->AddFontDefault();

		// merge in icons from Font Awesome
		static const ImWchar icons_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };
		ImFontConfig icons_config; icons_config.MergeMode = true; icons_config.PixelSnapH = true;
					
		io.Fonts->AddFontFromMemoryCompressedTTF(ttf_data, ttf_size, 22.0f, &icons_config, icons_ranges);

		unsigned char* pixels;
		int width, height, bytes_per_pixel;
		io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height, &bytes_per_pixel);

		// Upload texture to graphics system
		LPDIRECT3DTEXTURE9 g_FontTexture = NULL;
		pDevice->CreateTexture(width, height, 1, D3DUSAGE_DYNAMIC, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, &g_FontTexture, NULL);
			
		D3DLOCKED_RECT tex_locked_rect;
		g_FontTexture->LockRect(0, &tex_locked_rect, NULL, 0);
		
		for (int y = 0; y < height; y++)
			memcpy((unsigned char *)tex_locked_rect.pBits + tex_locked_rect.Pitch * y, pixels + (width * bytes_per_pixel) * y, (width * bytes_per_pixel));
		g_FontTexture->UnlockRect(0);

		// Store our identifier
		io.Fonts->TexID = (ImTextureID)g_FontTexture;
	}

	// Setup style
	ImGui::StyleColorsDark();
	Gui::SetStyleVars();

	Gui::Init = true;
`

**Comment by ocornut** [comment]
I guess make sure your data in correct.. try loading the ttf file from disk. 

Make sure you have asserts enabled.

Try adding an extra AddFontDefault() before the first one, so your merge attempt is in a second font and you can use the style editor to browse loaded fonts and understand what’s going on.

**Comment by clmiti** [comment]
Thank you for your response, I have tried the following suggestions and am no closer to the desired result.

I have asserts enabled and can confirm my fonts are loading successfully.

I am certain my data is correct,I have just attempted loading the .ttf file from disk anyway, successfully loaded however same issue persists.

I can confirm my font ranges are correct, I am also using the corresponding .ttf file now.

I have added an extra AddFontDefault(); so my merge attempt is in a second font, hoping this would allow me to browse loaded fonts and I have the same issue, I am unable to get anything to show at all. At this point I am convinced it must be something to do with the way I'm trying to load the textures.

I am attempting to load my font texture the same way ImGui_ImplDX9_CreateFontsTexture does.

My code is below can you confirm I'm trying to do this correctly? I have spend the past two days going over the documentation and examples and am no closer to getting what should be a relatively simple thing working.


`bool ImGui_ImplDX9_CreateFontsTextureHelper(IDirect3DDevice9* pDevice)
{
	// Build texture atlas
	ImGuiIO& io = ImGui::GetIO();
	unsigned char* pixels = NULL;
	int width, height, bytes_per_pixel;
	io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height, &bytes_per_pixel);

	// Upload texture to graphics system
	LPDIRECT3DTEXTURE9 g_FontTexture = nullptr;;
	if (pDevice->CreateTexture(width, height, 1, D3DUSAGE_DYNAMIC, D3DFMT_A8R8G8B8, D3DPOOL_DEFAULT, &g_FontTexture, NULL) < 0)
		return false;
	D3DLOCKED_RECT tex_locked_rect;
	if (g_FontTexture->LockRect(0, &tex_locked_rect, NULL, 0) != D3D_OK)
		return false;
	for (int y = 0; y < height; y++)
		memcpy((unsigned char *)tex_locked_rect.pBits + tex_locked_rect.Pitch * y, pixels + (width * bytes_per_pixel) * y, (width * bytes_per_pixel));
	g_FontTexture->UnlockRect(0);

	// Store our identifier
	io.Fonts->TexID = (void *)g_FontTexture;

	return true;
}

void Gui::Init(IDirect3DDevice9* pDevice)
{
	ImGui::CreateContext();
	ImGuiIO& io = ImGui::GetIO();

	ImFontConfig config;
	const ImWchar icon_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };

	io.Fonts->AddFontDefault();
	io.Fonts->AddFontDefault();
	config.MergeMode = true;
	config.FontDataOwnedByAtlas = false;
	config.PixelSnapH = true;

	io.Fonts->AddFontFromFileTTF("C:\\Users\\fa.ttf", 16.0f, &config, icon_ranges);

	ImGui_ImplDX9_CreateFontsTextureHelper(pDevice);
}`

**Comment by ocornut** [comment]
> I have asserts enabled and can confirm my fonts are loading successfully.
> I am certain my data is correct,
> I can confirm my font ranges are correct, 

The code you initially posted had `icon_ranges[]` with a persistent global scope (static), whereas the new (different) code doesn't have it. That's one error.

I am unfortunately unable to process requests of this kind here. From now on, please move this discussion to the newly created Discourse forum:
https://discourse.dearimgui.org/c/getting-started
