### ISSUE TITLE
How to insert a background image in the window that is created by glfw.

### ISSUE THREAD

**Issue by leongong1996** [ocornut/imgui#2044]
I'm a Beginner of ImGui, and I don't know how to insert a background image to the window.Have ImGui provided the related methods?or is it need programming about openGL.

**Comment by ice1000** [comment]
`ImGui::Image` is what you need.

To learn about `ImTextureID`, read the header files of each renderer header file (like `imgui_impl_opengl3.h`).
You'll have to write a little code related to OpenGL.

**Comment by leongong1996** [comment]
I know how to add pictures to an image widget, but I want to add background to the window that GLFW creates, which is the largest window.

**Comment by ice1000** [comment]
You can create a window that fits the glfw's window with

```cpp
auto MAIN_WINDOW = ImGuiWindowFlags_NoMove |
        ImGuiWindowFlags_NoTitleBar |
        ImGuiWindowFlags_NoBringToFrontOnFocus |
        ImGuiWindowFlags_MenuBar |
        ImGuiWindowFlags_NoCollapse |
         ImGuiWindowFlags_NoResize;

int w, h;
glfwGetWindowSize(window, &w, &h);
ImVec2 size(w, h);
ImGui::SetNextWindowPos(ImVec2());
ImGui::SetNextWindowSize(size);
if (ImGui::Begin(title, nullptr, MAIN_WINDOW)) {
  ImGui::Image(your texture, size);
  ImGui::End();
}
```

And you can still create other windows.

**Comment by ice1000** [comment]
Push Style, draw the background window and pop.

**Comment by leongong1996** [comment]
Thank you, I have solved the problem.

**Comment by leongong1996** [comment]
其实我也是成都的哟

**Comment by ice1000** [comment]
幸会幸会
