### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ocornut/imgui#2047]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [ImGui_Marmalade_GetClipboardText](https://github.com/ocornut/imgui/blob/d4cd121ae1a2a323f4f05082c63ed9d59d70ccd8/examples/imgui_impl_marmalade.cpp#L97 "ImGui_Marmalade_GetClipboardText function")
* [ImGui_Marmalade_InvalidateDeviceObjects](https://github.com/ocornut/imgui/blob/d4cd121ae1a2a323f4f05082c63ed9d59d70ccd8/examples/imgui_impl_marmalade.cpp#L198 "ImGui_Marmalade_InvalidateDeviceObjects function")

**Comment by ocornut** [comment]
They ease stepping/debugging and it doesn't make a difference here.

**Comment by elfring** [comment]
Can such function examples be nicer because of a bit smaller code without two questionable pointer checks?
