### ISSUE TITLE
Proper way to Log to a file? (using the LogText api)

### ISSUE THREAD

**Issue by Bawabawa01** [ocornut/imgui#2049]
Hello. Can anyone show me what is the proper way to use LogToFile/LogText methods?
As far as I understand, LogToFile is needed for kinda initialization of log file(using path to it). 

However, when I do `LogText("some string");`, except "some string" I am getting all control's texts logged in the file. If I use `LogToFile(-1, "path to the file");` for initializing once before LogText's, I get an exception.

PS: Sorry, couldn't find anything in Issues thread.

**Comment by ocornut** [comment]
>  I get an exception.

If you say there is an exception please provide details about it and call-stack.
LogToFile() will currently fail and assert if the file cannot be opened for writing, so most likely your path is incorrect.

You probably need to do `LogToFile(-1, filename)` then use `LogText()` and `LogFinish()`.

> I am getting all control's texts logged in the file.

The initial purpose of the logging api is the capture the UI in textual form, so this is expected, yes (until we perhaps add flags to selectively direct more or less contents). You can use LogToTile+LogText+LogFinish as a combo to log directly to a text file, but that's not much different than just calling fopen/fprintf/fclose yourself or using iostream.

**Comment by Bawabawa01** [comment]
>The initial purpose of the logging api is the capture the UI in textual form, so this is expected

This cleared everything, thanks.
