### ISSUE TITLE
Button Render On Top of Child Window

### ISSUE THREAD

**Issue by ahmadierfan** [ocornut/imgui#2051]
I'm working on a scroller that has arrow left and right for scrolling.
the only problem is I want half the button to be rendered on top of the child window but can't seem to get it right. 
how can I manipulate z-order or is there some kinda trick I can use?

In this example, half the button is uninteractable and seems to be rendered with lower z-order than the child window (my scroller).
![q](https://user-images.githubusercontent.com/10983665/44775515-0f484b00-ab8b-11e8-8b0b-fa2a77ee8a16.png)

**Comment by ahmadierfan** [comment]
Update: When I put the buttons in another child window becomes interactable but the rendering is still the same and the vertical lines are rendered on top of the buttons.

**Comment by ocornut** [comment]
Ahmad,

Child windows are always in front of their parent (and multiple child windows for a same parent are in the same order they were submitted)). 

Having an interactive button straddling both parent and child is difficult.
If you are willing to dig lower-level and use `<imgui_internal.h>`, the `ButtonBehavior()` function has a flag `ImGuiButtonFlags_FlattenChildren` which allows a button in the parent-most window to detect hover signal even if the mouse is over a child window (this is used by the resize grip). The problem you may have then is that you can't draw your button in the parent window if there are things above it, and may need to draw it in the OverlayDrawList.

**Comment by ahmadierfan** [comment]
@ocornut 
It's Actually Done. I rendered both buttons after rendering the child and used set cursor pos to position the items and I put each button in a child window and it works well.
