### ISSUE TITLE
Set io.MousePos invalid

### ISSUE THREAD

**Issue by kanren3** [ocornut/imgui#2055]
![qq 20180901194942](https://user-images.githubusercontent.com/32032670/44945645-631f9200-ae20-11e8-9b23-e657efd90dad.png)
No use

**Comment by ocornut** [comment]
@kanren3 Please use words and follow the [issue_template](https://github.com/ocornut/imgui/blob/master/.github/issue_template.md).

**Comment by ice1000** [comment]
@ocornut Is it expected that assigning to `io.MousePos` will change the mouse pos?

**Comment by ocornut** [comment]
> @ocornut Is it expected that assigning to io.MousePos will change the mouse pos?

That's an ambiguous question.
Setting `io.MousePos` sets the mouse pos used by imgui, it doesn't set the OS mouse position.

I'm closing this until original poster wants to formulate an actual question.

**Comment by ice1000** [comment]
> Setting `io.MousePos` sets the mouse pos used by imgui, it doesn't set the OS mouse position.

This has answered my question, sorry for the ambiguity, Thanks!

**Comment by westernA** [comment]
op
