### ISSUE TITLE
pointer being freed was not allocated ImFontAtlasBuildWithStbTruetype 

### ISSUE THREAD

**Issue by Milerius** [ocornut/imgui#2058]
Version used: ImGui 1.62

Bug: pointer being freed was not allocated

Screenshot:

<img width="1680" alt="capture d ecran 2018-09-03 a 03 40 43" src="https://user-images.githubusercontent.com/21139416/44963543-91d65f00-af2b-11e8-8d5a-79c1396c72ad.png">

Use the imgui sfml wrapper from elias daler with this minimal code:

```cpp
IO.Fonts->Clear(); // clear fonts if you loaded some before (even if only default one was loaded)
// IO.Fonts->AddFontDefault(); // this will load default font as well
IO.Fonts->AddFontFromFileTTF("font1.ttf", 8.f);
IO.Fonts->AddFontFromFileTTF("font2.ttf", 12.f);

ImGui::SFML::UpdateFontTexture(); // important call: updates font texture
```

```cpp
void UpdateFontTexture()
{
    ImGuiIO& io = ImGui::GetIO();
    unsigned char* pixels;
    int width, height;

    io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height);

    sf::Texture& texture = *s_fontTexture;
    texture.create(width, height);
    texture.update(pixels);

    io.Fonts->TexID = (void*)texture.getNativeHandle();
}
```

note: This is not happenning every time, 2 / 3 of the time it's happens
My code work with the default font.

This happen on OSX.

Windows/Linux doesn't complain

Clang 6.0 using c++17.

**Comment by Milerius** [comment]
<img width="1680" alt="capture d ecran 2018-09-03 a 04 07 18" src="https://user-images.githubusercontent.com/21139416/44964106-15457f80-af2f-11e8-81f6-776204cbd1a0.png">
<img width="1680" alt="capture d ecran 2018-09-03 a 04 08 15" src="https://user-images.githubusercontent.com/21139416/44964107-15457f80-af2f-11e8-8d4c-6ef998331e07.png">
<img width="1680" alt="capture d ecran 2018-09-03 a 04 08 21" src="https://user-images.githubusercontent.com/21139416/44964108-15457f80-af2f-11e8-9298-29ed849f8834.png">
<img width="1680" alt="capture d ecran 2018-09-03 a 04 08 24" src="https://user-images.githubusercontent.com/21139416/44964109-15de1600-af2f-11e8-810b-e3f955d7efba.png">
<img width="1680" alt="capture d ecran 2018-09-03 a 04 08 27" src="https://user-images.githubusercontent.com/21139416/44964111-15de1600-af2f-11e8-8028-c9eb9eea2171.png">
<img width="1680" alt="capture d ecran 2018-09-03 a 04 08 30" src="https://user-images.githubusercontent.com/21139416/44964112-15de1600-af2f-11e8-8fe6-dfd844ad646d.png">
<img width="1680" alt="capture d ecran 2018-09-03 a 04 08 34" src="https://user-images.githubusercontent.com/21139416/44964113-15de1600-af2f-11e8-82ac-c17a637f611e.png">

**Comment by Milerius** [comment]
@eliasdaler any idea ? (i'm using your wrapper, and youre method for loading fonts)

**Comment by eliasdaler** [comment]
Hello. Please open the issue in ImGui-SFML repo, looks like it's not the problem with ImGui :)

**Comment by ocornut** [comment]
I'll close this for now, assuming it is an ImGui-SFML thing (otherwise please see if you can provide a core imgui repro).
