### ISSUE TITLE
text input after completion causes segfault

### ISSUE THREAD

**Issue by timkerk** [ocornut/imgui#206]
Im using a variation of the console example in my code. I noticed after i updated the imgui code in my project that command completion was causing segfaults. 
When you type a string and complete it with the tab key, any key entered after causes a segfault (except enter). I then built the example code on its own and it does the same. It was all working fine with an older version and im not sure whats causing it.

**Comment by ocornut** [comment]
Working on it, thanks!

**Comment by ocornut** [comment]
Should be fixed now. Sorry!
