### ISSUE TITLE
Can’t click on window’s buttons

### ISSUE THREAD

**Issue by 0x452** [ocornut/imgui#2061]
Hi, Ocornut!

I have a problem, i have two windows, first is shown always and second have button and can be called in same time with first. The problem is that i can’t click on buttons of second window while the first is opened. 

Thanks!

**Comment by 0x452** [comment]
Still have that issue

**Comment by ocornut** [comment]
Please provide a proper explanation and repro, and follow all the instructions asked when opening a New Issue.
