### ISSUE TITLE
  How to make the text behind the image button align to the image button?

### ISSUE THREAD

**Issue by leongong1996** [ocornut/imgui#2064]
just like title.I have not found the way to do that in the "ShowDemoWindow"
![2018-09-06 17-54-39](https://user-images.githubusercontent.com/42726405/45150844-61c6de80-b1ff-11e8-829c-caab146c4b10.png)

**Comment by ice1000** [comment]
Before drawing the text, do `ImGui::SetCursorPos({ImGui::GetCursorPos().x, ImGui::GetCursorPos().y + (yourImageHeight - ImGui::GetFont()->FontSize) / 2})`

**Comment by ice1000** [comment]
Without C++11 you can `ImGui::SetCursorPos(ImVec2(ImGui::GetCursorPos().x, ImGui::GetCursorPos().y + (yourImageHeight - ImGui::GetFont()->FontSize) / 2))`

**Comment by ice1000** [comment]
Does my previous code solve your problem? If so, close this please.

**Comment by leongong1996** [comment]
Yes, Thank you.
