### ISSUE TITLE
ImGui::DestroyContext(ctx) -> SaveIniSettingsToDisk() does not use supplied context

### ISSUE THREAD

**Issue by scottmudge** [ocornut/imgui#2066]
**Version/Branch of Dear ImGui:**

Current

**Back-end file/Renderer/OS:**

Back-ends: N/A
OS: N/A
Compiler: N/A

**My Issue/Question:** 

When `ImGui::DestroyContext(ctx)` is called with a supplied/specific context, `SaveIniSettingsToDisk()` is called, which subsequently uses the global/static context var `GImGui` rather than the context supplied to `ImGui::DestroyContext(ctx)`. If the user is attempting to shutdown/destroy a specific context while `GImGui` is set to `NULL`, this yields an access violation.

**Standalone, minimal, complete and verifiable example:**

```
ImGui::SetCurrentContext(NULL);
ImGui::DestroyContext(mContext);
```

This yields an access violation.

I understand that I can set the current context before calling `ImGui::DestroyContext(ctx)`, but then what's the point of supplying a specific context to that function if I need to call `ImGui::SetCurrentContext(ctx)` anyway? `ImGui::DestroyContext(ctx)` should either set the `GImGui` var before invoking `Shutdown()`, or `SaveIniSettingsToDisk()` should be able to receive a specific context as an argument.

**Comment by ocornut** [comment]
Hello @scottmudge,
Looks like a bug to me, it should be fixed now!

(Not changing `SaveIniSettingsToDisk()` signature because every imgui function apart from the context ones assume current context, so instead Shutdown is swapping the context temporarily).

**Comment by scottmudge** [comment]
Great, thanks!
