### ISSUE TITLE
Font image appears instead of my image

### ISSUE THREAD

**Issue by endlicheri** [ocornut/imgui#2073]
Hello.
Currently, I would like to display an image loaded by OpenCV on ImGUI window.
I can display it with OpenCV imshow function or OpenGL GLFW window.
However, when I tried to display it on ImGUI window, Font image(an image which appears when we click widgets/Images tab on "ImGui Demo" window.)
I attached the code which is related to ImGui, so if someone can find out the bug, please let me know.
I am sorry if this is not worth for asking here.

in main.cpp
---------------------------------------------------------
    GLImage gl_image;
    gl_image.init();
    cv::Mat captured_image;
    captured_image = cv::imread("test.jpg");
    glfwMakeContextCurrent(window2);
    gl_image.draw(captured_image);
    while (!glfwWindowShouldClose(window))
    {
    ImGui::Begin("image", NULL);
        GLuint texture2;
        texture2 = gl_image.getTexture();
        ImGui::Image((void*)(intptr_t)texture2, ImVec2(297, 172));
        ImGui::End();
      }
---------------------------------------------------------

class for rendering
---------------------------------------------------------
     class GLImage
     {
     private:
        GLFWwindow *imgWindow;
        GLuint vao;     
        GLuint vbo;    
        GLuint image;   
        GLuint imageLoc;
        Shader s; 
    
    //vertex shader
    const char *vertexSource =
    "#version 330 core \n"
    "layout(location = 0) in vec4 pv;\n"
    "void main(void)\n"
    "{\n"
    "    gl_Position = pv;\n"
    "}\n";

    // fragment shader
    const char *fragmentSource =
    "#version 330 core \n"
    "uniform sampler2DRect image;\n"
    "layout(location = 0) out vec4 fc;\n"
    "void main(void)\n"
    "{\n"
    "    fc = texture(image, gl_FragCoord.xy);\n"
    "}\n";
    int vertices;
    
    public:
      void init();
      void draw(cv::Mat frame);
    };

    void init()
        {
        int w, h;
       // image size. currently, set manually.
        w = 297;
        h = 172;

        glewExperimental = GL_TRUE;
        glewInit();

        glGenVertexArrays(1, &vao);
        glBindVertexArray(vao);

        glGenBuffers(1, &vbo);
        glBindBuffer(GL_ARRAY_BUFFER, vbo);
        
        static const GLfloat position[][2] =
        {
            { -1.0f, -1.0f },
            { 1.0f, -1.0f },
            { 1.0f, 1.0f },
            { -1.0f, 1.0f }
        };
        vertices = sizeof(position) / sizeof (position[0]);
        glBufferData(GL_ARRAY_BUFFER, sizeof(position), position, GL_STATIC_DRAW);
        glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0);
        glEnableVertexAttribArray(0);
        
        glGenTextures(1, &image);
        glBindTexture(GL_TEXTURE_RECTANGLE, image);
        glTexImage2D(GL_TEXTURE_RECTANGLE, 0, GL_RGB, w, h, 0, GL_BGR, GL_UNSIGNED_BYTE, NULL);
        glTexParameteri(GL_TEXTURE_RECTANGLE, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_RECTANGLE, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        glTexParameteri(GL_TEXTURE_RECTANGLE, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
        glTexParameteri(GL_TEXTURE_RECTANGLE, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
        
        
        s.initInlineGLSL(vertexSource, fragmentSource);
        imageLoc = glGetUniformLocation(s.program, "image");
    }

    void draw(cv::Mat frame)
    {
        glfwMakeContextCurrent(imgWindow);
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
        
        cv::flip(frame, frame, 0);
        glBindTexture(GL_TEXTURE_RECTANGLE, image);
        glTexSubImage2D(GL_TEXTURE_RECTANGLE, 0, 0, 0, frame.cols, frame.rows, GL_BGR, GL_UNSIGNED_BYTE, frame.data);

        // enable shader
        s.enable();
        
        glUniform1i(imageLoc, 0);
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_RECTANGLE, image);
        glBindVertexArray(vao);
        
        glBindBuffer(GL_ARRAY_BUFFER, vbo);
        glBindBuffer(GL_ARRAY_BUFFER, 0);
        glDrawArrays(GL_TRIANGLE_FAN, 0, vertices);
        
        glBindVertexArray(0);
        
        s.disable();
        }
    };
---------------------------------------------------------

<img width="1392" alt="2018-09-10 17 54 40" src="https://user-images.githubusercontent.com/13681728/45287191-a49bf580-b522-11e8-819c-4a6ee156ac90.png">

**Comment by ocornut** [comment]
Hello,

**You are not explicitly specifying which back-end file you are using, what your imgui render loop looks like, your imgui version, OS, etc. as requested by the issue template.**

The code you are providing is not a correct and accurate repro:
Even though this:

```
    GLuint texture2;
    texture2 = gl_image.getTexture();
    ImGui::Image((void*)(intptr_t)texture2, ImVec2(297, 172));
```
Looks correct (assuming that `gl_image.getTexture()` return you the OpenGL identifier).

This:

```
while (!glfwWindowShouldClose(window))
{
ImGui::Begin("image", NULL);
    GLuint texture2;
    texture2 = gl_image.getTexture();
    ImGui::Image((void*)(intptr_t)texture2, ImVec2(297, 172));
    ImGui::End();
  }
```

Can't possibly work as-is (it would be an infinite loop drawing nothing) meaning you have omitted useful code and not tested the repro.

At any rate:
A) Either your value for `texture2` is not a valid GL texture identifier.
B) Either your render loop (which you haven't provided) doesn't bind the `TextureId` texture provided in the `ImDrawCmd` structure.

Assuming you are using an unmodified `imgui_impl_opengl3.cpp` for the render loop then B) would be correct in which case A) is your issue and it is an issue on your side.

You can use the tool Demo Window->Help->Metrics to browser draw commands and see the texture id value that you are passing to imgui.
