### ISSUE TITLE
Mouse (touch) down issue on iOS

### ISSUE THREAD

**Issue by hsm4** [ocornut/imgui#2074]
We are using imgui in the [SLProject library](https://github.com/cpvrlab/SLProject/wiki/Version-History) on desktop OS with GLFW as well as on Android and iOS. I read that imgui was not planned to be used on touch devices, but I have to say it works pretty well and save a lot of time. So thanks a lot for this library first.
The only problem is on iOS where the touchdown event is right followed by the touchup event. This causes an imgui menu only being marked as hovered but it doesn't open. On Android it works perfectly because right after a touchdown event a series of mouse move events follow.
Can I somehow mark a menu as hovered before I call BeginMenu?
Regards
Marcus

**Comment by ocornut** [comment]
Hello,

There's two aspects here:
Are you using the imgui_impl_glfw.cpp code for mouse inputs, or custom bindings?

**Fast press/release**
Same issue as #1992. The imgui_impl_glfw.cpp back-end should already handle the case of mouse being pressed then released during the same imgui frame. 

**Release needs to preserve mouse position for a frame or two**
However for Buttons to work the mouse position `io.MousePos` needs to be over the button on the release frame. When receiving a touch up event you need to preserve the io.MousePos value for an extra frame, and then you are allowed to clear it back io `-FLT_MAX, -FLT_MAX` to signify "no mouse".

> Can I somehow mark a menu as hovered before I call BeginMenu?

This is not the problem you want to address. The problem you want to address is a general mouse input problem, as discussed in your post and above.

**Comment by ocornut** [comment]
> Hi,
first of all: I'm blown away by the speed and extensiveness of your answers. The solution is a forced repaint after the touchdown event. We do indeed capture all events into an event queue and the problem was indeed that no paint came before the touch-up event. So thanks a lot for your tips.
Having this problem solved I can state that imgui works perfectly on hires touch devices.
You can close this issue.
Thanks.
Marcus

@hsm4, I am closing this issue as per your answer in #1992 (which I assume was meant to be posted here :).

A bit of details:

One of the issue with touch device is that the architecture doesn't allow for easily searching for "nearest" widgets for hit-testing, so if you have dense/narrow UI, interactions may be awkward considering capacitive touch screen aren't as precise as a mouse cursor. 

You can increase `style.TouchExtraPadding` but it's only safe to increase as long as `style.TouchExtraPadding` is <= the spacing between your items (generally `style.ItemSpacing`), beyond that the _first_ submitted widget covering the padding-included-surface will receive the touch hit.

**Comment by hsm4** [comment]
Hi omar,
thanks for the answer. That’s what we exactly do.
At startup we pass the DPI and scale the proportional, the fixed font
as well as the padding and spacing pixel setting.
This may could be an extension to imgui because with this imgui work well with fingers.


    if (!SLFileSystem::fileExists(fullPathAndFilename))

    {

        // Scale for proportional and fixed size fonts

        SLfloat dpiScaleProp  = dotsPerInch / 120.0f;

        SLfloat dpiScaleFixed = dotsPerInch / 142.0f;


        // Default settings for the first time

        SLGLImGui::fontPropDots  = SL_max(16.0f * dpiScaleProp, 16.0f);

        SLGLImGui::fontFixedDots = SL_max(13.0f * dpiScaleFixed, 13.0f);


        // Adjust UI paddings on DPI

        style.FramePadding.x     = SL_max(8.0f * dpiScaleFixed, 8.0f);

        style.WindowPadding.x    = style.FramePadding.x;

        style.FramePadding.y     = SL_max(3.0f * dpiScaleFixed, 3.0f);

        style.ItemSpacing.x      = SL_max(8.0f * dpiScaleFixed, 8.0f);

        style.ItemSpacing.y      = SL_max(3.0f * dpiScaleFixed, 3.0f);

        style.ItemInnerSpacing.x = style.ItemSpacing.y;


        return;

    }

Regards
Marcus Hudritsch

Institute Human Centred Engineering<https://www.ti.bfh.ch/en/research/institute_for_human_centered_engineering/institute_for_human_centered_engineering.html>
Group Computer Perception & Virtual Reality<https://www.cpvrlab.ti.bfh.ch/>
Berner Fachhochschule<https://www.ti.bfh.ch/en>
Höhenweg 80<https://www.google.ch/maps/place/H%C3%B6heweg+80,+2502+Biel/@47.14243,7.2432697,343m/data=!3m1!1e3!4m5!3m4!1s0x478e1ead3f2bb213:0xe98c3366691c7430!8m2!3d47.1427343!4d7.2437418?hl=de>
Room N.553
2502 Biel / Bienne
Festnetz: +41 32 321 64 86
Mobil: +41 77 405 15 00
marcus.hudritsch@bfh.ch<mailto:marcus.hudritsch@bfh.ch>




On 10 Sep 2018, at 20:46, omar <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
first of all: I'm blown away by the speed and extensiveness of your answers. The solution is a forced repaint after the touchdown event. We do indeed capture all events into an event queue and the problem was indeed that no paint came before the touch-up event. So thanks a lot for your tips.
Having this problem solved I can state that imgui works perfectly on hires touch devices.
You can close this issue.
Thanks.
Marcus

@hsm4<https://github.com/hsm4>, I am closing this issue as per your answer in #1992<https://github.com/ocornut/imgui/issues/1992> (which I assume was meant to be posted here :).

A bit of details:

One of the issue with touch device is that the architecture doesn't allow for easily searching for "nearest" widgets for hit-testing, so if you have dense/narrow UI, interactions may be awkward considering capacitive touch screen aren't as precise as a mouse cursor.

You can increase style.TouchExtraPadding but it's only safe to increase as long as style.TouchExtraPadding is <= the spacing between your items (generally style.ItemSpacing), beyond that the first submitted widget covering the padding-included-surface will receive the touch hit.

**Comment by ocornut** [comment]
Notice there is a function ImGuiStyle::ScaleAllSizes() to do that.
I'm currently evaluating solutions to handle the DPI problem properly, in particular as the `viewport` branch radically changes the problem: imgui windows may be on different screens and therefore require different scaling, so `Begin()` can essentially alter the font size, etc.
