### ISSUE TITLE
Incorrect floating-point wrap-around handling in ImGui::DragBehaviorT when format precision is 'low' (eg %.0f)

### ISSUE THREAD

**Issue by vegorovinno** [ocornut/imgui#2075]
**Version/Branch of Dear ImGui:** 

1.65 release (no modifications)

**Back-end file/Renderer/OS:** 

Custom
OS: Windows Desktop

**My Issue/Question:**

Because of floating point precision errors, DragBehaviorT wrap-around detection can trigger when it's not supposed to. I don't think wrap-around detection for floating point even makes sense.

Consider an input of `*v = 11.0000010`, `v_speed = 0.1`, `v_min = 0.0` and `v_max = 360.0` while dragging to the right (`g.DragCurrentAccum = 0.3`): v_cur will be adjusted to 11.3 and then rounded by RoundScalarWithFormatT to 11.000000 (no longer equal to the *v we started with). Later, the condition `if (v_cur > v_max || (v_cur < *v && adjust_delta > 0.0f))` will see that we were moving right but `v_cur 11.000000` < `*v 11.0000010` and the result will be clamped to `v_max`

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
ImGui::Begin("Example Bug");
static float fangle = 0.0f
float angle = fangle / (float)M_PI * 180.0f; // math.h
if (ImGui::DragFloat("Angle", &angle, 0.1f, 0.0f, 360.0f, "%.0f"))
  fangle = angle * (float)M_PI / 180.0f;
ImGui::End();
```

**Screenshots/Video**

https://monosnap.com/file/pHhMqu4Te2qzGiXBDgJ034aEpPdxis#

**Comment by ocornut** [comment]
Thank you @vegorovinno, you are right.

I had a stashed fix for that that I developed as part of #2024 but didn't finish, it's now in. As you pointed out I'm basically not attempted the integer-wrap detection on decimal type.

Should be fixed now!

(PS: You can attach screenshots/video directly to the github post, this way they are guaranteed to stay visible for future readers, whereas third-party hosting tend to remove their file after a certain time)
