### ISSUE TITLE
After treeNodeEx expand,IsItemClicked Failed!

### ISSUE THREAD

**Issue by yafacex** [ocornut/imgui#2077]
local bFoundSelect
    local function recurDraw(node)
        local name,addr = getName(node)
        local children = node:getChildren()
        if #children > 0 then
            local bSelect = (self.cur_select_node == node)
            if bSelect then
                imgui.PushStyleColor(0,1,0,1)
            end
            if imgui.treeNodeEx(name,imgui.ImGuiTreeNodeFlags_OpenOnArrow) then
                if bSelect then
                    imgui.PopStyleColor()
                end
                for i,child in ipairs(children)do
                    recurDraw(child) 
                end
                imgui.treePop()
            else
                if bSelect then
                    imgui.PopStyleColor()
                end
            end
            if imgui.IsItemClicked() then
                if not bFoundSelect then
                    bFoundSelect = true
                    self.cur_select_node = node 
                end
                print("IsItemClicked",name)
            end
        else
            if self.cur_select_node == node then
                imgui.PushStyleColor(0,1,0,1)
                imgui.treeNodeEx(name,imgui.ImGuiTreeNodeFlags_Leaf)
                imgui.treePop()
                imgui.PopStyleColor()
            else
                imgui.treeNodeEx(name,imgui.ImGuiTreeNodeFlags_Leaf)
                imgui.treePop()
            end
            if imgui.IsItemClicked() then
            -- if imgui.button(name) then
                if not bFoundSelect then
                    bFoundSelect = true
                    self.cur_select_node = node
                end
            end
        end
    end

export c++ api to lua for game use.
I'm drawing the scene Hierachy recursivly.When the treeNode is collapsed,IsItemClicked() return true.But after the treeNode expand,IsItemClicked() return false!As i know,IsItemClicked equals IsMouseClicked&&IsItemHoverd，i found that IsMouseClicked returned false!

with ImGuiTreeNodeFlags_OpenOnArrow flag,when i click the triangle on the left,IsItemClicked() also return true.....Is it reasonable?

**Comment by yafacex** [comment]
![aa50](https://user-images.githubusercontent.com/7322814/45397824-539c1680-b674-11e8-8a32-60162851efaf.gif)

**Comment by ocornut** [comment]
`IsItemClicked()` return the value for the _LAST_ item submitted. There's no stack storage of that data on tree push/pop.

```
if (TreeNode(A))
{
   TreeNode(B);
}
IsItemClicked() <- return value for B
```

You should call `IsItemXXX` right after `TreeNodeXXX`:

e.g.
```
bool open = TreeNodeXXX()
bool clicked = IsItemClicked()
if (open)
{
    ...
    TreePop();
}
```

**Comment by yafacex** [comment]
It works,thanks for your reply!

**Comment by JPGygax68** [comment]
@ocornut Shouldn't that information be stacked? I think that would be more intuitive.

**Comment by ocornut** [comment]
To stack it the way you intent we would need to compute every possible IsItemXXX state for every tree node.

**Comment by JPGygax68** [comment]
I'm still a beginner - didn't realize how many there are. So doing that would mean stacking all the data on which all the IsItem...() queries are based - or precompute all the values. Probably not worth it.
Your workaround works perfectly btw, so thanks for that!

**Comment by tourkit** [comment]
> `IsItemClicked()` return the value for the _LAST_ item submitted. There's no stack storage of that data on tree push/pop.
> 
> ```
> if (TreeNode(A))
> {
>    TreeNode(B);
> }
> IsItemClicked() <- return value for B
> ```
> 
> You should call `IsItemXXX` right after `TreeNodeXXX`:
> 
> e.g.
> 
> ```
> bool open = TreeNodeXXX()
> bool clicked = IsItemClicked()
> if (open)
> {
>     ...
>     TreePop();
> }
> ```

Hey @ocornut & @yafacex  ! 

Sorry I'm trying to replicate this but no luck, I can't wrap my head arround the logic here, 

can you make this very simple example work for me plz

and hopefully this can then be used as proper example for futur users with similar problem

thx !

`
        if (TreeNode("Foo")) {

            // if (IsItemClicked()) cout << "Foo" << endl; // Not good: prints one out of two clicks

            if (TreeNode("Bar")) {  TreePop(); }  

            if (IsItemClicked()) cout << "Bar" <<endl; // Good: prints BBB on every click
            
            TreePop();
        
        } 

        // if (IsItemClicked()) cout << "Foo" <<endl; // Not good: prints one out of two clicks, also when BBB is clicked...

`

**Comment by tourkit** [comment]
working simplified example : 

            bool aaa = ImGui::TreeNode("AAA");
            if (ImGui::IsItemClicked()) std::cout << "AAA" <<std::endl;

            if (aaa) {

                bool bbb = ImGui::TreeNode("BBB");
                if (ImGui::IsItemClicked()) std::cout << "BBB" <<std::endl;
                if (bbb) {

                    ImGui::TreePop();

                }
                
                ImGui::TreePop();
            }

            bool ccc = ImGui::TreeNode("CCC");
            if (ImGui::IsItemClicked()) std::cout << "CCC" <<std::endl;
            if (ccc) {

                ImGui::TreePop();

            }

**Comment by iwubcode** [comment]
In case anyone is wondering, this also seems to impact `BeginPopupContextItem()`.  The solution working for me is to use `OpenPopup()` along with checking `ImGui::IsItemHovered() && ImGui::IsMouseReleased(ImGuiMouseButton_Right)` before the node state is handled.
