### ISSUE TITLE
SetInt(name,1) unable to collapse all treeNodes

### ISSUE THREAD

**Issue by yafacex** [ocornut/imgui#2079]
![aa51](https://user-images.githubusercontent.com/7322814/45399706-af1dd280-b67b-11e8-8424-e6300bed985e.gif)

I want  all the collapseHeaders of treeNode to close using SetInt(name,0) when i click "fold all" button.Top collapseHeader did close as i expect,However when i clicked top collapseHeader,inner treeNodes left expand.Although GetInt("app.scenes.study.play_theme") == 0

**Comment by ocornut** [comment]
With `SetInt(id, 0)` you'll only close a single node, there's no way at the moment to close node recursively, other than 
a) iterating the open node and flagging them for closure, 
or b) using a dedicated storage for that tree so you can easily clear the entire storage at once.

**Comment by yafacex** [comment]
I did SetInt(id,0) recursively and it doesn't work.I will check my code and tell you later.

**Comment by ocornut** [comment]
@yafacex Any update on this?

**Comment by ocornut** [comment]
Closing as per no repro, probable user error.
