### ISSUE TITLE
DirectX11: Any reason for invalidating and creating devices again here?

### ISSUE THREAD

**Issue by ice1000** [ocornut/imgui#2086]
https://github.com/ocornut/imgui/blob/4b353ce482eccde65d426513f26f2ab11dbae384/examples/example_win32_directx11/main.cpp#L81-L85

I heard it's not needed to invalidate and create devices when resizing buffers. Is there any reason to do this or references about this?
I commented those two lines (81, 85), the example still works well.

**Comment by ocornut** [comment]
May have been an incorrect assumption based on what DX9 needs. The commit is old: 66a5837ba8f05090c02e12bba8a8e71dce6ddb8e.
Enabling debug device (`D3D11_CREATE_DEVICE_DEBUG`) doesn't seem to complain. 

I don't have time to dig further but if more DX10/DX11 experts wants to chime in and confirm that it indeed has no use?

**Comment by ice1000** [comment]
@ocornut This is said by a dx11 expert and he's not good at English so I ask question for him. Personally I recommend commenting those two lines until we find bugs.

**Comment by ice1000** [comment]
Superseded by #2088
