### ISSUE TITLE
ImGui::SetActiveID  will change ImGui::InputInt

### ISSUE THREAD

**Issue by af-bwf** [ocornut/imgui#2090]
ImGui V1.60
Ubuntu 16.04

Using ImGui::SetActiveID to select an input e.g. ImGui::InputInt, will overwrite the input field with what was in the last selected input field.
```

        ImGui::Begin("test", nullptr, 0);
            static int a = 0;
            if(ImGui::InputInt("a", &a, 1, 10))
            {
                 id_a = ImGui::GetActiveID();
            }

            static int b = 0;
            ImGui::InputInt("b", &b, 1, 10);

            static int c = 0;
            ImGui::InputInt("c", &c, 1, 10);

            static int d = 0;
            ImGui::InputInt("d", &d, 1, 10);

            char charBuffer[STRING_INPUT_MAX_SIZE] = "abcde";
            ImGui::InputText("e", charBuffer, IM_ARRAYSIZE(charBuffer));

            if(ImGui::IsKeyPressed(GLFW_KEY_A))
            {
                ImGui::SetActiveID(id_a, ImGui::GetCurrentWindow());
            }
        ImGui::End();

```
The relevant ImGui::InputInt is made active, but it will be overwritten, eaven by the text string if InputText is active when pressing the 'a' key.
I need to make the input active and not change it when doing so.
What am I doing wrong?

**Comment by af-bwf** [comment]
`        ImGui::Begin("test", nullptr, 0);
            static int a = 0;
            if(ImGui::InputInt("a", &a, 1, 10))
            {
                 id_a = ImGui::GetActiveID();
            }

            static int b = 0;
            ImGui::InputInt("b", &b, 1, 10);

            static int c = 0;
            ImGui::InputInt("c", &c, 1, 10);

            static int d = 0;
            ImGui::InputInt("d", &d, 1, 10);

            char charBuffer[STRING_INPUT_MAX_SIZE] = "abcde";
            ImGui::InputText("e", charBuffer, IM_ARRAYSIZE(charBuffer));

            if(ImGui::IsKeyPressed(GLFW_KEY_A))
            {
                ImGui::SetActiveID(id_a, ImGui::GetCurrentWindow());
            }
        ImGui::End();`
Code more readable

**Comment by ocornut** [comment]
Hello,

Please always focus on discussing **what you are trying to achieve** first, rather than focusing on what you think is a possible solution for what you are trying to achieve.

> I need to make the input active and not change it when doing so.

This is done in the Demo window, under `"Inputs, Navigation & Focus" > "Focus From Code"`.
