### ISSUE TITLE
error while calling ImGui::ColorPicker4(...) in vulkan + SDL configure

### ISSUE THREAD

**Issue by bigdimboom** [ocornut/imgui#2095]
Cannot free buffer 0x32 that is in use by a command buffer. The spec valid usage text states 'All submitted commands that refer to buffer, either directly or via a VkBufferView, must have completed execution

![image](https://user-images.githubusercontent.com/6119906/45904549-6c66a380-bdbb-11e8-93cd-ad0be0bc0e65.png)

![image](https://user-images.githubusercontent.com/6119906/45904615-98822480-bdbb-11e8-9fb0-e7f1530e176a.png)

**Comment by ice1000** [comment]
imgui branch? Definition of `color` variable?

**Comment by ice1000** [comment]
`ImGui::ColorPicker` shouldn't be used like that. Your code is making the `ColorPicker` only visible when the button is clicked.

You should read the documentation and use `ColorPicker` like

```cpp
ImVec4 color(1, 1, 1, 0);
ImGui::ColorPicker4("Pick", (float *) &color);
```

To add a button to control the visibility, use:

```cpp
ImVec4 color(1, 1, 1, 0);
static bool isVisible = false;
if (ImGui::Button("Show picker")) isVisible = !isVisible;
if (isVisible) ImGui::ColorPicker4("Pick", (float *) &color);
```

**Comment by ocornut** [comment]
@bigdimboom: your question has likely nothing to do with the ColorPicker and is tied to the Vulkan renderer. Because you didn’t bother filling in the requested New Issue form I am closing your issue now.

**Comment by bigdimboom** [comment]
The picker works fine, but the validation layer prompts error
