### ISSUE TITLE
Vulkan debug/validation layer is triggered during color picking

### ISSUE THREAD

**Issue by bigdimboom** [ocornut/imgui#2097]
**Version/Branch of Dear ImGui:**

Master

**Back-end file/Renderer/OS:** 

Windows, Vulkan

Back-ends: imgui_impl_SDL.cpp + imgui_impl_vulkan.cpp
OS: windows
Compiler: vs 2015

**My Issue/Question:** _(please provide context)_

Color Picker or ColorEiditor works correctly but it pops vulkan resource error

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
		ImGui::Begin("transform data.");
		ImGui::Text("fps average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
		ImGui::Separator();

		ImGui::ColorEdit4("clear color", color);

		ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

![image](https://user-images.githubusercontent.com/6119906/45906442-1f3a0000-bdc2-11e8-9ec0-b49a61317022.png)

**Comment by bigdimboom** [comment]
This bug seems to go away when I set VkPresentMode to fifo.

**Comment by ocornut** [comment]
@bigdimboom Does it really only happen when opening the color picker? This feels coincidental/unrelated, as from the point of view of the renderer it doesn't really know what the open widgets or windows are. Possibly you are getting the issue past a certain amount of time/vertices. Would be good to clarify.

The examples/ main.cpp currently _always_ use `VK_PRESENT_MODE_FIFO_KHR` unless the code is modified. So you if are not currently referring to an error happening in the examples/example_sdl_vulkan/ application, please try to repro and report the issue within that application. 

Right now it feels that you are reporting a bug that only happen in your own application, and without providing details about it.

(
In `ImGui_ImplVulkanH_SelectPresentMode()` in imgui_impl_vulkan.cpp when you uncomment the two lines that print the available present modes:
```
    for (uint32_t avail_i = 0; avail_i < avail_count; avail_i++)
        printf("[vulkan] avail_modes[%d] = %d\n", avail_i, avail_modes[avail_i]);
```
Which present mode is selected by the code which is causing that issue? (There's also a printf statement in `SetupVulkanWindowData()` in main.cpp that you can uncomment).
)

**Comment by ocornut** [comment]
@bigdimboom Any feedback? Does it still happen for you?
It may be related to #2071, 
See in particular the updated patches https://github.com/ocornut/imgui/pull/2071#issuecomment-464802635

**Comment by ocornut** [comment]
Closed as expected fixed since the recent fixes addressed exactly this issue.
