### ISSUE TITLE
ImGui needs a better name!

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#21]
ImGui is a generic term which makes googling for this library uneasy.
While we can keep the git and source code "imgui" (if desired), it would be beneficial to include a keyword or two that would uniquely identify the library. Any suggestions?

**Comment by ocornut** [comment]
I'd want to slap myself all day if the library was named after me.
Topic still on !

**Comment by emoon** [comment]
haha :) fair enough.

**Comment by Flix01** [comment]
If you want to keep the "imgui" part and you just want to add an adjective, I agree that something like:
"friendly imgui" or "easy imgui" or "quick imgui" or "compact imgui"  would be OK, as I expect that users nowadays look for easy-to-use compact code with almost no dependency at all.

Another common approach would be to find something crazy and "exotic" with no meaning at all that is easy to remember, like "Nancy purple brocket's imgui" (or something like that with less words that is easier to remember).

I'd rather use the first approach.

As a side note there are already other libraries named Imgui (like this: https://github.com/AdrienHerubel/imgui, which should be a direct extrapolation of the gui included in memononen's Recast and Detour library as far as I can understand): so making this library unique is a good choice.

**Comment by emoon** [comment]
Personally I don't think it's needed to keep imgui as part of the name but that is of course up to @ocornut

**Comment by jarikomppa** [comment]
"Ocornut's ImGui" seem to be the de-facto name..

**Comment by aytekaman** [comment]
How about openImGui?

**Comment by hypernewbie** [comment]
+1 immie

**Comment by emoon** [comment]
Immie is actually pretty nice imo :)

**Comment by Extrawurst** [comment]
I think it is a bad idea to rename completely. I have no trouble finding ocornuts gui simply googling for "imgui" (first hit) the other github project with the same name was not updated in 2 years and has ridiculously less stars. keeping the name "IMGUI" and adding "Ocornut's" as a prefix unofficially in a logo or something seems less objectionable though.

i think marketing wise it would have much more impact to create a dedicated website with a more structured documentation than the one page mess of a README.md. You can conveniently use github pages for that and include whatever logos seem fit. As a starting point for newcomers such a website with a collection of code snippets and screenshots/gifcasts of the result would be more important (imho)

**Comment by Extrawurst** [comment]
as a plus for github pages: everyone can create PRs and contribute, whether it is actual documentation or a better home for the example imgui usages than the kitchen sink #issue that there is right now ;)

**Comment by nikmes** [comment]
imgui on google bring reaults for imgur ... i love your work and i am currently replacing my homebrewed level editors gui with ingui. cppgui is  my suggestion

**Comment by paulsapps** [comment]
Github pages would definitely be a good idea :) I've just discovered them myself

**Comment by adam4813** [comment]
imui++?

**Comment by ApoorvaJ** [comment]
SlimGui? :D

**Comment by Pagghiu** [comment]
Præsens (Immediate in ancient Latin)
Immediato (Immediate in Italian)
Immediate (minimalist style)
imMEDIATE (:apple: style)
I'm GUI (Existentialist style)
ImGuy (Average Joe style)

**Comment by hypernewbie** [comment]
imgüi

**Comment by ocornut** [comment]
simgui ?

**Comment by paultech** [comment]
Has popularity of the library removed this rename requirement? imgui in search engines return this project now (along with your patreon link!)

**Comment by Extrawurst** [comment]
that maybe due to your google tracking. on my work machine which is not infected by my personal google search history and behaviour tracking it returns this github project but no patreon and the other imgui is second exactly behind it...

**Comment by ocornut** [comment]
Alright let's try to sort that out!

**I still beieve the best would be to settle on a low-key prefix or suffix to "ImGui" that would be included on the pages and various documentations/headers but not affect the namespace/code itself.**
Could we focus on those?

Flix01 said:
> "friendly imgui" or "easy imgui" or "quick imgui" or "compact imgui"

That sort of thing.

Flix01 said:
> Another common approach would be to find something crazy and "exotic" with no meaning at all that is easy to remember, like "Nancy purple brocket's imgui" (or something like that with less words that is easier to remember).

Or that sort of thing. Also good, something completely arbitrary and random (better if it's a single word).

Jarikomppa
> "Ocornut's ImGui" seem to be the de-facto name..

Would rather go for Omar's ImGui instead of ocornut, but more in favor of the things above (not a fan of things named after people unless it's really low-key like one letter).

Sorry I'm not contributing much. I'll sit now and try to brainstorm some words :)

**Comment by ocornut** [comment]
I sort of like those:
Dear ImGui
Bonjour ImGui
?

Sweet, Dolce, Neat, Pop, Joly, Glint,

**Comment by Extrawurst** [comment]
Are you serious ? :D

**Comment by tamaskenez** [comment]
OmGui would be the best... too bad it doesnt contain imgui as a substring

**Comment by paultech** [comment]
LiveUI, CurrentUI, drawNOW,BeforeSwap, EveryFrameUI

**Comment by ocornut** [comment]
I am serious! Would rather go for something friendly or an emotion than something very techy. The good thing about "Dear ImGui" is that it's sort of light-hearted, original and doesn't steal the show from the ImGui word.
(Agree omgui would have been good, had I thought of it a year ago.)

**Comment by Extrawurst** [comment]
actually i think "omars ImGui" would be the best choise simply because it
already leads to almost a full google result page targeting your lib or
forums talking about this lib...

**Comment by ocornut** [comment]
That's a fair point.

**Comment by leino** [comment]
WhimGui, because you can make GUIs on a whim?

**Comment by BillDStrong** [comment]
ImGUI - The tiny GUI builder.

Itty Mitty GUI - ImGUI

I Make GUI - ImGUI

Itty bitty Mighty GUI - ImGUI

**Comment by ocornut** [comment]
Proposed branding.

![out](https://cloud.githubusercontent.com/assets/8225057/9825766/8b0de6c8-58cd-11e5-960f-0eeed4004d6c.png)

I think it's a strong name. The idea is to keep it rather low-key and not intrude in the code. Won't change any namespace/filename (obviously). Would add the name at the top of headers in comments and in a few locations but that'd be it. It's mostly a way to be able to recognize/name it with clarity when needed to communicate.

**Comment by ocornut** [comment]
Variants

![dear imgui 2](https://cloud.githubusercontent.com/assets/8225057/9826102/b79e3330-58cf-11e5-95c5-404ee67d0a1d.png)

![dear imgui 3](https://cloud.githubusercontent.com/assets/8225057/9826135/ff0cd6f4-58cf-11e5-81fb-2be9b0a02759.png)

Something along those lines.

**Comment by breakin** [comment]
omgui

om for omar
omg for omg
gui for gui

Sorry couldn't fit im in there :)

**Comment by ocornut** [comment]
Here's the code
```
ImGuiIO& io = ImGui::GetIO();
io.Fonts->AddFontFromFileTTF("../../extra_fonts/DroidSans.ttf", 18.0f);
ImFont* font2 = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\Gothic.ttf", 40.0f);
[....]
ImGui::SetNextWindowSize(ImVec2(266,84));
ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(1,1));
ImGui::Begin("  reduced fat!###logo", NULL, ImGuiWindowFlags_NoCollapse);
ImGui::PushFont(font2);
ImGui::Text("    dear imgui,    ");
ImGui::PopFont();
ImGui::End();
ImGui::PopStyleVar();
```
![reduced fat](https://cloud.githubusercontent.com/assets/8225057/9826543/1486a386-58d3-11e5-8438-909d00d5a09a.png)

**Comment by jvcleave** [comment]
+1 for omgui :)

**Comment by ocornut** [comment]
Guys, no offence but it looks like nobody has been reading this thread. I can't rename the library and either rename all symbols/files either have two different and confusing names.

**Comment by theGiallo** [comment]
I vote for "I am GUI" or "I'm GUI". Very personal, so warm, much feelings. No symbols rename.

**Comment by ajohnson23** [comment]
PRIMGUI (pronounced either "Prime GUI" as in 'prime - really great', or "prim-gui" as in 'prim - very proper and neat')
SUBLIMGUI (pronounced "SublimeGUI", which could also be used, but we're trying to maintain the "imgui" part, right? Also clashes with the text editor?)

**Comment by ajohnson23** [comment]
Imgui Jr (or imgui Junior)
junior can mean "small", is also kind of cute and endearing.

**Comment by ajohnson23** [comment]
Another one: trimgui
"trim" synonyms: reduce, decrease, cut down, cut back on, scale down, prune, etc
Idea being imgui is trimmed down/far simpler to deal with compared to Qt, GTK, etc.

**Comment by ocornut** [comment]
How about what I suggested "dear imgui,", what do you think.

**Comment by Extrawurst** [comment]
After reading all ideas I still think keeping it simply "Imgui" is the most
elegant one...

**Comment by ajohnson23** [comment]
I'm not crazy about dear imgui, but couldn't pinpoint specifically why. I'm sure i'd get used to it though if that's what happened.
if you're into simple endearing terms on the front of "imgui", simply "nice imgui" or "imgui jr" is more my style. Speaking purely for myself of course!

**Comment by ajohnson23** [comment]
The idea of keeping imgui is fine for now since this is the only game in town, but it could get ambiguous down the line if imgui as a general paradigm catches on and other projects spring up.

The term "PC" always annoyed me for that reason (from google):
The Historical Meaning of “PC” “PC” has several different meanings. On one extreme, PC just means “personal computer,” and smartphones and tablets are just as much PCs as laptops and desktops. On the other extreme, “PC” originally meant “IBM PC-compatible.”

**Comment by ocornut** [comment]
imgui as a paradigm has caught. It's in Unity (old) and a few other librairies are using the name name, that's the whole reason for this thread in the first place.

**Comment by ajohnson23** [comment]
Very true. I think a prefix/postfix is a good idea.

**Comment by ajohnson23** [comment]
I was actually responding to some of the earlier comments in this thread pointing out that this project gets first place on SERPs for "imgui".
That may be true now, but in a couple or few years, who knows...

**Comment by theGiallo** [comment]
> **ocornut commented 5 hours ago**
 > How about what I suggested "dear imgui,", what do you think.
I don't perceive it as a name. It sounds not identifying. So my gut spoke.
Maybe making it an acronym could help? DIG? (Dear Immediate GUI) DIGUI?

**Comment by jarikomppa** [comment]
I reinstate that "omar's imgui" is pretty much the de-facto name already..
=)

**Comment by r-lyeh** [comment]
what about slimgui? :)

**Comment by emoon** [comment]
I like slimgui :)

**Comment by chyvonomys** [comment]
Guinness --> imguinness :)

**Comment by ZahlGraf** [comment]
Advanced IMGUI => AIMGUI

**Comment by miniupnp** [comment]
I would go for libZOOP :-)

**Comment by ocornut** [comment]
I've gone and went for a low-key "dear imgui" to get over with that topic. 

Commits are very simple:
https://github.com/ocornut/imgui/commit/e4cf44e967643f587d227df8fec4168db1a45b01
https://github.com/ocornut/imgui/commit/e34b4b46da61f3dd8f7157aeaafe0372cce1ecee

Probably won't be noticeable to most!

**Comment by ocornut** [comment]
Good news, nobody has been rioting so far :)
Closing this.

**Comment by xcyl** [comment]
omgui

**Comment by ScopesDK** [comment]
FrameIO
