### ISSUE TITLE
Linker errors due to inline Indent/Unindent.

### ISSUE THREAD

**Issue by neilogd** [ocornut/imgui#210]
I noticed that my production builds were failing due to Indent & Unindent being inline (https://github.com/ocornut/imgui/blob/master/imgui.cpp#L7804). I have a local change to no longer make them inline, was considering commiting and sending over a pull request, but I am assuming these are inline for a reason. Thought it would be worth asking that here first? Did they show up as a hotspot in complex UIs?

**Comment by ocornut** [comment]
I have removed the inline marker, they don't make sense in this context, it was just out of habit when I extracted those two lines out of TreePush/TreePop. Neither should be a bottleneck.
