### ISSUE TITLE
ImGui failing to bug with MinGW on windows?

### ISSUE THREAD

**Issue by dev0-1** [ocornut/imgui#2100]
Hi!

I have been using ImGui for a while with MSVC++(Windows) and GCC(Linux) compilers, but recently I started using MinGW(gcc/g++) for windows, but ImGUi doesn't compile on this compiler, it gives this error:
```
<path>\imgui\imgui.cpp: In function 'FILE* ImFileOpen(const char*, const char*)':
<path>\imgui\imgui.cpp:1573:69: error: '_wfopen' was not declared in this scope
     return _wfopen((wchar_t*)&buf[0], (wchar_t*)&buf[filename_wsize]);
```
By removing the define containing this function, it compiles correctly(but without saving I guess), but that is not a neat solution and I am afraid this will cause ImGui to break on other compilers.

Any idea what I can do about it? Is it my fault or an ImGui bug?

Thanks!

**Comment by ocornut** [comment]
Which version of imgui are you using?

**Comment by ocornut** [comment]
```
VERSION 1.65 (Released 2018-09-06)
- Fixed a build issue with non-Cygwin GCC under Windows.
```

**Comment by dev0-1** [comment]
> 
> 
> Which version of imgui are you using?
// dear imgui, v1.62 WIP
Oh ok, will download the new release. Sorry for bothering you.
