### ISSUE TITLE
How to draw image on top of another image ?

### ISSUE THREAD

**Issue by trlsmax** [ocornut/imgui#2101]
**Version/Branch of Dear ImGui:**

1.65 and tabs branch

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_opengl2.cpp + imgui_impl_glfw.cpp
OS: WIN7 X64
Compiler: Virtual Studio 2015

**My Issue/Question:** _(please provide context)_

How to draw image on top of another image ? I want to use AddImage to draw and move a small image on top of a large one, but the small display wrong color. It display ok when draw it separately. 

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
ImGui::Begin("Example Bug");
ImVec2 p = ImGui::GetCursorScreenPos();
ImGui::Image(large_id, large_size);
ImGui::GetWindowDrawList()->AddImage(small_id, p, ImVec2(p.x+image.x, p.y+image.y), ImVec2(0,0), ImVec2(1,1));
ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
> How to draw image on top of another image ? 

Call Image or AddImage multiple times.

Your code fragment looks alright but it is incomplete and lacking screenshots so it is hard to tell what is wrong.

**Comment by trlsmax** [comment]
Here is the screenshot:
![2018-09-26_144538](https://user-images.githubusercontent.com/5501321/46061985-f8e9db00-c19a-11e8-8b63-df1e80518356.png)

code:
```
ImGui::Begin("TEST");
ImGui::Image(small_id, small_size);
ImGui::SameLine();
ImGui::Image(large_id, large_size);
ImVec2 p = ImGui::GetCursorScreenPos();
ImGui::Image(large_id, large_size);
ImGui::GetWindowDrawList()->AddImage(small_id, p, ImVec2(p.x+small_size.x, p.y+small_size.y), ImVec2(0,0), ImVec2(1,1));
ImGui::End();
```

**Comment by trlsmax** [comment]
Is because there are alpha channel in the image ? I need to try images without alpha channel.

**Comment by trlsmax** [comment]
use jpg image file solve the problem.
Thanks.
