### ISSUE TITLE
Callback functions for InputFloat or DragFloat

### ISSUE THREAD

**Issue by Enigma-li** [ocornut/imgui#2107]
Hi,

Is there callback functions for InputFloat item: ImGui::InputFloat("input float", &f0, 0.01f, 1.0f);

**Comment by ocornut** [comment]
For what purpose? What are you trying to do?

**Comment by Enigma-li** [comment]
Thanks, you are right!

I add the operations when input the new value in this way:

```
if (ImGui::InputFloat(...)) {
  // do something when the user modifies the field
}
```
or use ```ImGui::IsItemActive()``` and ```ImGui::IsItemHovered()``` to add operations.

**Comment by medbensalah** [comment]
This can be useful when trying to support mathematical expressions.
For example 2 + 2 will be processed to 4 and won't fallback to 2

**Comment by ocornut** [comment]
You should probably just use an `InputText()` and do the swap when validated.
