### ISSUE TITLE
InputText question

### ISSUE THREAD

**Issue by jomindiko** [ocornut/imgui#2114]
I'm new about imgui, and i want to use InputText, but how to get the entered text?
I have been looking for something on this subject for a very long time, but I haven’t found it. Please help.

**Comment by ocornut** [comment]
Hello,

Your question is ambiguous. Please clarify and provide more details.

**Comment by zivler** [comment]
Just assign a variable and call inputtext then maniupulate that variable for your use:
static char textvar [20]; 
ImGui::InputText("Enter Text", textvar, 20, ImGuiInputTextFlags_CharsUppercase);

I'm not sure that's what you want since it's ambiguous as said by ocornut.

**Comment by jomindiko** [comment]
Okay, for example: I entered in Input Text username, then i want get this username from Input Text and use in my code. (for auth, ect..)

**Comment by zivler** [comment]
http://www.cplusplus.com/doc/tutorial/basic_io/

**Comment by ocornut** [comment]
@jomindiko There are plenty of example in the imgui demo. Your question mostly suggest lack of familiarity with C/C++ so I would suggest asking on a more general programming forum. Others may be able to guide you there, whereas this place here is devoted to Dear ImGui issues. Hope it works out for you!
