### ISSUE TITLE
BeginTabItem declaration (docking)

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#2115]
**Version/Branch of Dear ImGui:**

docking

https://github.com/ocornut/imgui/blob/docking/imgui.h#L521

is problematic for parsing in cimgui_auto
should be

 BeginTabItem(const char* label, bool* p_open = NULL, ImGuiTabItemFlags flags = 0);

I know  BeginTabItem(const char* label, bool* p_open = NULL, ImGuiTabItemFlags = 0); is valid C or C++ declaration but having the argument names greatly simplifies parsing (as everything before the name is then the type of the argument)

**Comment by ocornut** [comment]
Fixed now, thanks!
