### ISSUE TITLE
A U FCKING PASTER!!!! YOUR CODE AS MY ASSHOLE!!!! ALL SHACKED AND U SUCKING BIG COCK OF ME!!!!!!! PLS DELETE MSVS FORM YOU'R PC!!!!!!!!!!!!!!!!!1!

### ISSUE THREAD

**Issue by busybox10** [ocornut/imgui#2120]
A U FCKING PASTER!!!! YOUR CODE AS MY ASSHOLE!!!! ALL SHACKED AND U SUCKING BIG COCK OF ME!!!!!!! PLS DELETE MSVS FORM YOU'R PC!!!!!!!!!!!!!!!!!1!
 http://prntscr.com/l2v5dh

**Comment by d4rkd3n1337** [comment]
cumshot anime!
