### ISSUE TITLE
only first checkbox actually working

### ISSUE THREAD

**Issue by Froosi** [ocornut/imgui#2122]
(Click "Preview" to turn any http URL into a clickable link)

1. IF YOU ARE HAVING AN ISSUE COMPILING/LINKING/RUNNING/DISPLAYING/ADDING FONTS/WIRING INPUTS, please post on the "Getting Started" Discourse forum:
https://discourse.dearimgui.org/c/getting-started

2. You may use this Issue Tracker to ask for help and submit bug reports, feature requests or suggestions that don't fit in any category of (1). PLEASE CAREFULLY READ THE CONTRIBUTING DOCUMENT before submitting any issue: https://github.com/ocornut/imgui/blob/master/.github/CONTRIBUTING.md

3. PLEASE MAKE SURE that you have: read the FAQ in imgui.cpp; explored the contents of ShowDemoWindow() including the Examples menu; searched among Issues; used your IDE to search for keywords in all sources and text files; and read the CONTRIBUTING.md file linked above.

4. Delete points 1-4 and PLEASE FILL THE TEMPLATE BELOW before submitting your issue. 

----

**Version/Branch of Dear ImGui:**

XXX

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp
OS: XXX 
Compiler: XXX _(if the question is related to building)_

**My Issue/Question:** _(please provide context)_

XXX

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
Please read the FAQ.
