### ISSUE TITLE
Incomplete fix for PR "OpenGL 3 Example: Use GLboolean for compile/link status"

### ISSUE THREAD

**Issue by hesiod** [ocornut/imgui#2125]
The [fix](02afbaeef00d18bddcaabd378cb1812656e4daad) for PR #2112 was incomplete: It only covered the cast required in `CheckShader`, but not the one in `CheckProgram`.
See hesiod/imgui@d4c3a8a79a3f0f6621da832e342649bd72317987 in the original PR for the missing changes (in lines 333 and 342).

**Comment by ocornut** [comment]
Apologies, I didn’t notice you had updated the PR following the discussion, hence the manual (incompletr) change I made. Will merge the fixed one now. Thank you!

**Comment by hesiod** [comment]
No worries - and sorry about the confusing force push!
