### ISSUE TITLE
Sync many columns' width

### ISSUE THREAD

**Issue by MultiTeemer** [ocornut/imgui#2136]
I want to make several 2-columns blocks with possibility to change their width simultaneously.
I managed to achieve this using the same ID for them, but this mechanism doesn't work when I use PushID()/PopID() calls.
Let's consider example:

![example](https://user-images.githubusercontent.com/3601502/47103621-51ffd880-d248-11e8-842c-dd12996e64e5.gif)

If I add PushID/PopID calls inside "some header", inner columns stop to change their size by dragging outside columns.

I've also tried to use functions GetColumnWidth, SetColumnWidth, but it results in flickering and visual artifacts:

![example2](https://user-images.githubusercontent.com/3601502/47103953-06016380-d249-11e8-8fa6-6aadf2fa2598.gif)

Is there some way to achieve such a functionality?

**Comment by meshula** [comment]
I was recently trying to solve this as well; no luck. (I wanted all the second columns visually aligned with each other, irrespective of tree expansion level)

**Comment by ocornut** [comment]
Hello,
I don't have a full answer right now but I've been looking at those issues recently.
Please note that in your specific case you only require a sync because you are using a `CollapsingHeader()` in the middle of the column set and this is forcing you to end/begin the columns set again.
Without the CollapsingHeader you wouldn't need this.

**Comment by ocornut** [comment]
Closing as this is supported by Tables api

**Tables with the same identifier share all settings (width, visibility, order, etc)**
![tables_synced](https://user-images.githubusercontent.com/8225057/99835267-aa5ede00-2b64-11eb-9dce-573a8e454a87.gif)

Honoring indentation is configurable on a per-column basis:

![image](https://user-images.githubusercontent.com/8225057/101508045-81698600-3977-11eb-9c33-75841eeaa5c6.png)

To replicate what the gif above tries to do you would probably want to indent after opening the table.
