### ISSUE TITLE
sdl2 opengl imgui keyboard doesnt detect problem

### ISSUE THREAD

**Issue by emrekaya413** [ocornut/imgui#2138]
i used imgui_impl_opengl3.
i am using only <GL/glew.h>.
i don't use  <GL/gl3w.h> and <glad/glad.h>.

and my code just these:

```
init:
// Setup Dear ImGui binding
IMGUI_CHECKVERSION();
ImGui::CreateContext();
io = ImGui::GetIO(); (void)io;

ImGui_ImplSDL2_InitForOpenGL(window, mainContext);
ImGui_ImplOpenGL3_Init(glsl_version);

// Setup style
ImGui::StyleColorsDark();
```

```
while:
// Start the Dear ImGui frame
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplSDL2_NewFrame(window);
ImGui::NewFrame();

ImGui::InputText("string", buf, IM_ARRAYSIZE(buf));

ImGui::Render();
SDL_GL_MakeCurrent(window, mainContext);
glViewport(0, 0, (int)io.DisplaySize.x, (int)io.DisplaySize.y);
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

but i cant write. it doesn't detect keyboard what i need to add these codes ? can you show me with write for sdl2.
sorry for bad english :)

**Comment by ice1000** [comment]
You need `io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;` after `(void)io`.

**Comment by emrekaya413** [comment]
> You need `io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;` after `(void)io`.

i added but still didnt work

**Comment by emrekaya413** [comment]
i recorded video https://youtu.be/BAFrI7qtjsQ Keys down Keys pressed dont detect

**Comment by emrekaya413** [comment]
i just added demo codes after inputText.  demo codes : 
```
// 1. Show the big demo window (Most of the sample code is in ImGui::ShowDemoWindow()! You can browse its code to learn more about Dear ImGui!).
        if (show_demo_window)
            ImGui::ShowDemoWindow(&show_demo_window);

        // 2. Show a simple window that we create ourselves. We use a Begin/End pair to created a named window.
        {
            static float f = 0.0f;
            static int counter = 0;

            ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.

            ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
            ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
            ImGui::Checkbox("Another Window", &show_another_window);

            ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f
            ImGui::ColorEdit3("clear color", (float*)&clear_color); // Edit 3 floats representing a color

            if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)
                counter++;
            ImGui::SameLine();
            ImGui::Text("counter = %d", counter);

            ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
            ImGui::End();
        }

        // 3. Show another simple window.
        if (show_another_window)
        {
            ImGui::Begin("Another Window", &show_another_window);   // Pass a pointer to our bool variable (the window will have a closing button that will clear the bool when clicked)
            ImGui::Text("Hello from another window!");
            if (ImGui::Button("Close Me"))
                show_another_window = false;
            ImGui::End();
        }
```

**Comment by emrekaya413** [comment]
> What's the code you're using in the video?



> What's the code you're using in the video?

i just added demo codes after inputText. demo codes :

// 1. Show the big demo window (Most of the sample code is in ImGui::ShowDemoWindow()! You can browse its code to learn more about Dear ImGui!).
        if (show_demo_window)
            ImGui::ShowDemoWindow(&show_demo_window);

        // 2. Show a simple window that we create ourselves. We use a Begin/End pair to created a named window.
        {
            static float f = 0.0f;
            static int counter = 0;

            ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.

            ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
            ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
            ImGui::Checkbox("Another Window", &show_another_window);

            ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f
            ImGui::ColorEdit3("clear color", (float*)&clear_color); // Edit 3 floats representing a color

            if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)
                counter++;
            ImGui::SameLine();
            ImGui::Text("counter = %d", counter);

            ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
            ImGui::End();
        }

        // 3. Show another simple window.
        if (show_another_window)
        {
            ImGui::Begin("Another Window", &show_another_window);   // Pass a pointer to our bool variable (the window will have a closing button that will clear the bool when clicked)
            ImGui::Text("Hello from another window!");
            if (ImGui::Button("Close Me"))
                show_another_window = false;
            ImGui::End();
        }

**Comment by ice1000** [comment]
Could you please show your code around `io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;`?

**Comment by emrekaya413** [comment]
> Could you please show your code around `io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;`?
init:
```
// Setup Dear ImGui binding
IMGUI_CHECKVERSION();
ImGui::CreateContext();
io = ImGui::GetIO(); (void)io;
io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;  // Enable Keyboard Controls



ImGui_ImplSDL2_InitForOpenGL(window, mainContext);
ImGui_ImplOpenGL3_Init(glsl_version);

// Setup style
ImGui::StyleColorsDark();
```

**Comment by emrekaya413** [comment]
i added  ImGui_ImplSDL2_ProcessEvent(&event); inside SDL_PollEvent and it work.

like this: 

main while:

```

while (SDL_PollEvent(&event))
{
 ImGui_ImplSDL2_ProcessEvent(&event);
 if (event.type == SDL_QUIT)
 done = true;
}
// Start the Dear ImGui frame
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplSDL2_NewFrame(window);
ImGui::NewFrame();

ImGui::InputText("string", buf, IM_ARRAYSIZE(buf));

ImGui::Render();
SDL_GL_MakeCurrent(window, mainContext);
glViewport(0, 0, (int)io.DisplaySize.x, (int)io.DisplaySize.y);
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

```

**Comment by ocornut** [comment]
`ImGuiConfigFlags_NavEnableKeyboard` has nothing to do with inputting type, it is to enable full-on keyboard navigation (arrow keys/space/enter to manipulate dear imgui).

Instead you need you pass your SDL event to the `ImGui_ImplSDL2_ProcessEvent()` as you found out. Reading the main.cpp of examples/example_sdl_opengl3 is always recommended :)

**Comment by ice1000** [comment]
> `ImGuiConfigFlags_NavEnableKeyboard` has nothing to do with inputting type, it is to enable full-on keyboard navigation (arrow keys/space/enter to manipulate dear imgui).

Thanks for noticing that.
