### ISSUE TITLE
How to make child window share with parent window scroll?

### ISSUE THREAD

**Issue by ngminteck** [ocornut/imgui#2143]
**Version/Branch of Dear ImGui:**

165

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_win32.cpp
OS: win64
Compiler: visual studio 2017 10.017134.0   c++lastest

How to make child window share with parent window scroll?

When i use mouse scroll , the parent window position don't move and the parent scroll position don't move too.

<img width="959" alt="capture" src="https://user-images.githubusercontent.com/36160697/47254652-c9777700-d497-11e8-955d-e0d6010d6468.PNG">

**Comment by ocornut** [comment]
The _purpose_ of a child window is to have a different scrolling region. Don’t use one if you don’t need that.

Otherwise you can set the _NoScrollWithMouse window flag if you want the mouse wheel event to be passed to the parent.

**Comment by ngminteck** [comment]
Thank it help for my problem, it possible the other child follow other child scroll?

**Comment by ocornut** [comment]
Why not using a single child?

**Comment by ngminteck** [comment]
i was actually for some sort of rectangle function, that i can arrange my content of my widget.

I know there is draw list, i try avoid deep in the lib code and create custom widget.
