### ISSUE TITLE
ImGuiTreeNodeFlags_Selected flag problem

### ISSUE THREAD

**Issue by ngminteck** [ocornut/imgui#2145]
**Version/Branch of Dear ImGui:**

165

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_win32.cpp
OS: window 10 64bit
Compiler: visual studio 2017 c++lastest

**My Issue/Question:** _(please provide context)_

ImGuiTreeNodeFlags_Selected flag problem, when i select my item ( ImGui::TreeNodeEx), it select the stuff on below node , rather than the node i selected, even my debug print out is correct

SetSelection() - toggle between select, is a boolean
GetSelection() - get the boolean result 
![untitled](https://user-images.githubusercontent.com/36160697/47264413-51698980-d549-11e8-80a1-0e79fcad9c01.jpg)

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
`void EditorWorldOutliner::ObjectBranch(Factory* m_objFactory)
{

	ImGuiTreeNodeFlags node_flags = ImGuiTreeNodeFlags_None;
	for (auto objectItr = m_objFactory->GetGameObjectsT()->begin(); objectItr != m_objFactory->GetGameObjectsT()->end(); ++objectItr)
	{
		if (ImGui::IsItemClicked())
		{
			(*objectItr).second->SetSelection();
			std::cout << std::endl;
		}

		node_flags =  ((*objectItr).second->GetSelection() == true ? ImGuiTreeNodeFlags_Selected : 0);
		
		if ((*objectItr).second->GetChildObjects().size() == 0)
		{
			node_flags |= ImGuiTreeNodeFlags_Leaf;
		}
		else
		{
			node_flags |= ImGuiTreeNodeFlags_OpenOnArrow | ImGuiTreeNodeFlags_OpenOnDoubleClick;
		}
		bool node_open = ImGui::TreeNodeEx((*objectItr).second->GetIDName().c_str(), node_flags, (*objectItr).second->GetIDName().c_str());
		if (node_open)
		{
			ChildObjectBranch(m_objFactory,(*objectItr).second->GetChildObjects());
			ImGui::TreePop();
		}
	}
}`
```

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
You are calling IsItemClicked before TreeNode therefore testing the wrong item.
