### ISSUE TITLE
How to make a group of CollapsingHeader act like Radio button

### ISSUE THREAD

**Issue by trlsmax** [ocornut/imgui#2146]
**Version/Branch of Dear ImGui:**

1.65

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
OS: linux
Compiler: gcc

**My Issue/Question:** _(please provide context)_

XXX

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_

What I want is make a group of CollapsingHeader act link Radio button, only one in the group can open.
I want to use the CollapsingHeader to hide or show the info of some 3D model, when one is clicked, close all others and open the clicked, and display the 3D model in the opengl viewport.
I can't figure this out.

**Screenshots/Video** _(you can drag files here)_

**Comment by r-lyeh** [comment]
That's interesting!

**Comment by trlsmax** [comment]
Thank you for you reply. I understand the logic of your code, but it din't compiled.
```
error: invalid use of incomplete type ‘struct ImGuiContext’
             ImGuiStorage* storage = g.CurrentWindow->DC.StateStorage;
```
Today, I came up a poor solution : a custom TreeNodeBehavior function use the radio button method

check if pressed, if yes, set the selected to current index.
```
    bool hovered, held, pressed = ButtonBehavior(interact_bb, id, &hovered, &held, button_flags);
	if (v != NULL && pressed)
		*v = index;
```
before rendering , close the not selected.
```
	if (v != NULL && *v != index && is_open) {
		is_open = false;
		window->DC.StateStorage->SetInt(id, is_open);
	}
```

**Comment by r-lyeh** [comment]
Cool. You needed to include imgui_internal.h likely :D
