### ISSUE TITLE
Help about including my renderer.

### ISSUE THREAD

**Issue by TheSpyGeek** [ocornut/imgui#2148]
**Version/Branch of Dear ImGui:**

v1.65

**Back-end file/Renderer/OS:** basic engine

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
OS: Ubuntu
Compiler: G++ 7.3.0

**My Issue/Question:**

Hello, I am trying to do a basic graphic engine with openGL. In it, I can add any object to render it. Each object as his own shader. So my question is:
* Is it possible to add the rendering of my scene which is in many files and defined as classes that use types like ```GLuint``` and function from glew? When I compile it say "gl.h included before glew.h".
* If it is possible. Where and how can I do this?

I have been trying for 2 days :(

Below there is a basic example of my renderer.

Shader.h
```
#include <glew.h>
#include <gl.h>
class Shader {
    void load(const char *vertex_file_path, const char *fragment_file_path);
    void reload(const char *vertex_file_path, const char *fragment_file_path);
    inline GLuint id() ;
    void checkCompilation(GLuint shaderId);
    void checkLinks(GLuint programId)
}
```

Object.h
```
#include <gl.h>

class Object {
    vec3 *vertices;
    int *triangles;
    Shader *shader;
}
```
Scene.h
```
class Scene {
    Object *arrayOfObject; // composed the scene
}

```

Renderer.h
```
#include <glew.h>
#include <gl.h>

class Renderer {
     Scene *scene;
     void init();
     void drawScene();
}
```

**Comment by ocornut** [comment]
Your question is ill-defined and seems off topic and not really related to imgui, sorry.
You may get more help on other communities.
