### ISSUE TITLE
How can I specify the position and size of widgets?

### ISSUE THREAD

**Issue by J-Liu** [ocornut/imgui#215]
I want to specify the position and size of Button Label and so on, not only the window, how can make it?

**Comment by ocornut** [comment]
Use SetCursorPos*() functions to position the draw cursor.
For the size it currently depends on the type of widget. Widgets like Button() or Selectable() can take a size as parameter. For composed widget that are followed by a label you can use PushItemWidth() at the moment.

**Comment by J-Liu** [comment]
Thank you! SetCursorPos* works!

**Comment by haseeb-heaven** [comment]
Or we can use **ImGui::SameLine();** method to achieve the same result.
