### ISSUE TITLE
ImGui SameLine problem

### ISSUE THREAD

**Issue by ngminteck** [ocornut/imgui#2154]
**Version/Branch of Dear ImGui:**

165

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_win32.cpp
OS: window10
Compiler: visual studio 2017

How to make the thumbnail generate will base on child region window size,  if the x pos is out of bound,
it will not use sameline and generate at below instead
<img width="1260" alt="capture" src="https://user-images.githubusercontent.com/36160697/47604431-71f38100-da2c-11e8-803d-def8e949841f.PNG">

XXX

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
Please provide a repro then re-open.
