### ISSUE TITLE
Auto resizing window should be rendered twice to show something.

### ISSUE THREAD

**Issue by nikitablack** [ocornut/imgui#2158]
**Version/Branch of Dear ImGui:**

1.66

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

OS: Linux 
GAPI: Vulkan

**My Issue/Question:**

First I'd like to describe my use-case. I know that imgui concept is to update every frame. But if data was not changed I don't see the point in buffers update. I need to fill a screen with static text labels - I'm drawing as fast as I can, but the data changes not that often - let's say I get a new data every 10th frame. Obviously, I don't want to spend precious cycles and send the data to the gpu if it's the same. So I want to fill my buffers once and then use them multiple frames.

**Standalone, minimal, complete and verifiable example:**
```
ImGui::GetIO().DisplaySize = ImVec2(10000.0F, 10000.0F);
	
for(int i{0}; i < 2; ++i)
{
	ImGui::NewFrame();
		
	ImGuiStyle& style{ImGui::GetStyle()};
	style.WindowRounding = 0.0f;
	style.WindowPadding = ImVec2{0.0f, 0.0f};
	style.WindowBorderSize = 0.0f;
	
	const ImGuiWindowFlags windowFlags{ImGuiWindowFlags_NoTitleBar
                                           | ImGuiWindowFlags_NoMove
		                           | ImGuiWindowFlags_NoResize
		                           | ImGuiWindowFlags_NoScrollbar
		                           | ImGuiWindowFlags_NoInputs
		                           | ImGuiWindowFlags_AlwaysAutoResize};
		
	ImGui::SetNextWindowBgAlpha(0.5F);
	ImGui::SetNextWindowPos(ImVec2(0.0F, 0.0F));
	ImGui::SetNextWindowSize(ImVec2{0.0F, 0.0F}); // auto size
	
	ImGui::Begin("Imgui Window", nullptr, windowFlags);
	
	ImGui::SetCursorPos(ImVec2{100.0F, 100.0F});
	ImGui::Text("Hello window!");
	
	ImGui::SetCursorPos(ImVec2{150.0F, 120.0F});
	ImGui::Text("Hello\nwindow 2!");
	
	ImGui::End();
	
	ImGui::Render();
		
	const ImDrawData* const drawData{ImGui::GetDrawData()};
	auto t{drawData->TotalVtxCount};
}
```
Please notice the strange loop with 2 iterations. On the first iteration I always have `t` equal to zero. The secont iteration fills the `drawData` normally. This is necessary only with `NextWindowSize` of `{0.0F, 0.0F}`.  If the size is not zero, everything works on first iteration, but `ImGuiWindowFlags_AlwaysAutoResize` have no effect.

Update: Actually `ImGuiWindowFlags_AlwaysAutoResize` have no effect at all. With a window size of zero, the window get's resized even without that flag. With a non-zero size, the flag is ignored.

**Comment by ocornut** [comment]
> Auto resizing window should be rendered twice to show something. 

We need a first pass to compute the size of the window contents. That is correct, by specs and won't change. 

If you keep calling `ImGui::SetNextWindowSize(ImVec2{0.0F, 0.0F})` every frame it is roughly equivalent to using `ImGuiWindowFlags_AlwaysAutoResize` but I think there are few differences (I don't remember off the bat), but basically avoid calling `ImGui::SetNextWindowSize(ImVec2{0.0F, 0.0F})` multiple times and just use the flag.

> Obviously, I don't want to spend precious cycles and send the data to the gpu if it's the same. So I want to fill my buffers once and then use them multiple frames.

(You might want to measure the cost of that GPU upload/render first. I feel like the precious brain cycles you are spending on this might be a net negative as you could be using that time looking at more important features or optimizations!)

If all you are rendering if text you can ditch `ImGui::` API and use `ImDrawList::` api as well. But then at this point there's less reasons to use ImGui.

**Comment by nikitablack** [comment]
Thank you. I didn't see the 2 pass requirement in the code. Also, you wrote about specs? Which specs, where can I read it?

**Comment by ocornut** [comment]
I didn't write actually specs, my wording was overly zealous there, but this is how it is expected to be. A one-pass IMGUI system is going to have to rely on temporal data to do even most basic layouting.

The intended use case of Dear ImGui functions is to call them every frame. People using idle mechanisms would only need to render 1-2 frames after the last user input (needs time for "releases" to be caught and rendered) so this is a little similar to what you are doing here.
