### ISSUE TITLE
ImGuiTreeNodeFlags: Framed flag makes Leaf/Bullet flags become ignored (unnecessarily)

### ISSUE THREAD

**Issue by goran-w** [ocornut/imgui#2159]
**Version/Branch of Dear ImGui:**

1.65

**Back-end file/Renderer/OS:**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
OS: Windows 10
Compiler: Visual Studio 2017 _(if the question is related to building)_

**My Issue/Question:**

Hi! I'd like to be able to render a CollapsingHeader() without an arrow or with a bullet (for use as a plain separator etc). I tried calling TreeNodeEx() and passing ImGuiTreeNodeFlags of CollapsingHeader and Leaf/Bullet, but the latter flag was ignored.

I looked at the code for ImGui::TreeNodeBehavior() and found that in the "if (display_frame)" path, RenderArrow() is called without looking at flags ImGuiTreeNodeFlags_Bullet and ImGuiTreeNodeFlags_Leaf, while the "else" path handles these as expected.

Do you think this could be changed? There doesn't seem to be many other differences between the framed and unframed cases...

**Standalone, minimal, complete and verifiable example:** 

**Screenshots/Video**

**Comment by ocornut** [comment]
> Do you think this could be changed? There doesn't seem to be many other differences between the framed and unframed cases...

Yes. It's a little bit of a faff but if you can make a nice PR for it I would merge that.

**Comment by goran-w** [comment]
Thanks! I'll look into that, then. It would be a minimal change, but I'll have to try it out first.
/Göran

**Comment by goran-w** [comment]
I made some tests, to see how it would look. The only change is in the Leaf and/or Bullet headers in the screenshot below. It's straight forward and matches what's already there for tree nodes, except for for the "Leaf header" where I left-adjusted the text to match any unindented Text sub-/sibling items.

![image](https://user-images.githubusercontent.com/44604769/47721370-3df8a580-dc50-11e8-962c-ecaed48926c1.png)

(BTW, I noted that Leaf implies that the tree node or header is always open, so any (logically) nested sub-items are always visible. Convenient!)

**Comment by goran-w** [comment]
To apply the Bullet/Leaf flags I used TreeNodeEx(), since CollapsingHeader() does not accept flags.

Left-adjusting the text for (non-Bullet) Leaf headers (as in my screenshot) means we are a bit less consistent with normal (non-Framed) tree nodes, but I think it looks better in the Framed context and it also aligns better with NoTreePushOnOpen (which is the default for CollapsingHeader).

Would it be OK to make a pull request with this change?

**Comment by goran-w** [comment]
Alright, I made a pull request: #2160
(Please bear with me, I'm new to GitHub... ;)

**Comment by ocornut** [comment]
Thank you Goran!
I’ll be unavailable for a few days so please bear with me if I can’t react about this so soon. Will try next week!

**Comment by goran-w** [comment]
As a bonus, we can now do this:

![image](https://user-images.githubusercontent.com/44604769/47730748-17903580-dc63-11e8-8c7c-4616503a9fa3.png)

(I'm using Font Awesome in a Leaf header TreeNodeEx() here... ;)

**Comment by ocornut** [comment]
Merged now, sorry for the late reaction!
