### ISSUE TITLE
Implicit conversion of NULL constant to bool

### ISSUE THREAD

**Issue by neilogd** [ocornut/imgui#216]
Noticed on the latest when compiling with clang 3.5, offending line:

https://github.com/ocornut/imgui/blob/master/imgui.h#L362

**Comment by ocornut** [comment]
Thanks! That happened when I switched the two functions (note, those two are WIP api that I intent to change in the following weeks).

**Comment by neilogd** [comment]
I figured it was best to add an issue instead of a pull request when I
noticed the WIP :) Just updated to the latest and spotted the warnings come
through.
