### ISSUE TITLE
How to make the animation of images ratating looks smooth?

### ISSUE THREAD

**Issue by haorenhl007** [ocornut/imgui#2167]
I want to rotate an needl image， but it not looks smooth。How can I to improve it？The refresh of the gui is about 30fps。
the code is as follow：
`#include <math.h>
static inline ImVec2 operator+(const ImVec2& lhs, const ImVec2& rhs)
{
return ImVec2(lhs.x + rhs.x, lhs.y + rhs.y);
}
static inline ImVec2 ImRotate(const ImVec2& v, float cos_a, float sin_a)
{
return ImVec2(v.x * cos_a - v.y * sin_a, v.x * sin_a + v.y * cos_a);
}
void ImageRotated(ImTextureID tex_id, ImVec2 center, ImVec2 size, float angle)
{
ImDrawList* draw_list = ImGui::GetWindowDrawList();

float cos_a = cosf(angle);
float sin_a = sinf(angle);
ImVec2 pos[4] =
{
    center + ImRotate(ImVec2(-size.x * 0.5f, -size.y * 0.5f), cos_a, sin_a),
    center + ImRotate(ImVec2(+size.x * 0.5f, -size.y * 0.5f), cos_a, sin_a),
    center + ImRotate(ImVec2(+size.x * 0.5f, +size.y * 0.5f), cos_a, sin_a),
    center + ImRotate(ImVec2(-size.x * 0.5f, +size.y * 0.5f), cos_a, sin_a)
};
ImVec2 uvs[4] = 
{ 
    ImVec2(0.0f, 0.0f), 
    ImVec2(1.0f, 0.0f), 
    ImVec2(1.0f, 1.0f), 
    ImVec2(0.0f, 1.0f) 
};

draw_list->AddImageQuad(tex_id, pos[0], pos[1], pos[2], pos[3], uvs[0], uvs[1], uvs[2], uvs[3], IM_COL32_WHITE);
}`

It looks like as follow：
![image_rotate](https://user-images.githubusercontent.com/3020932/47891140-eb57fd00-de8c-11e8-88f8-1e750f946dea.gif)

**Comment by ocornut** [comment]
I don't understand your post/request. In your video the animation looks smooth.
Furthermore, this isn't an imgui specific question, so please ask this on generalist game developer forums.
