### ISSUE TITLE
ImGui not rendering after window resize

### ISSUE THREAD

**Issue by ImCytox** [ocornut/imgui#2170]
So i have coded a dll for a directX11 programm which hooks the present and draw imgui as an overlay above it. The main problem is when i resize the window of the programm ImGui is not rendering anymore.
How do i have to handle this ? Do i have to hook the "IDXGISwapChain::ResizeBuffers" method of D3D11?
If yes what code do i have to implement there ?

Thanks in Advance

**Comment by ocornut** [comment]
This is a D3D11 question and not a dear imgui question. Sorry but #1586.
