### ISSUE TITLE
Linux + Mac laptop resolution issue

### ISSUE THREAD

**Issue by hamedsabri** [ocornut/imgui#2171]
(Click "Preview" to turn any http URL into a clickable link)

I am running my app ( https://github.com/hamedsabri/Explore3MF ) on Linux ( Fedora29  distro ) that is installed on my Mac Laptop ( display resolution 2880x1800 ) but menus show very small in the app. Do I need to set something in the code to take to handle DPI properly?

**Version/Branch of Dear ImGui:**

master

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

OS:  Fedora / Ubuntu Distros on Mac + Nvidia dirive GeForce GT 650M

**Screenshots/Video** _(you can drag files here)_

![fedora_app](https://user-images.githubusercontent.com/13695234/47957982-9359ed00-df97-11e8-856f-2ad50621f168.png)

**Comment by BrutPitt** [comment]
The easiest way, I think, is to change **ImGui::GetIO().FontGlobalScale** (value>1 bigger)
Or set font size on loading (via AddFontFromFileTTF, for example), or changing ImFont::Scale to resize font dynamically.
Some examples are imgui_demo

**Comment by ocornut** [comment]
Hamed, you didn’t specify which back-end files you are using.

Look up for “DPI” for some ideas.

**Comment by hamedsabri** [comment]
@BrutPitt Thank you, will give it a try.

@ocornut  Oh my bad. I am using imgui_impl_glfw, imgui_impl_opengl3 for back-end files

@ebachard,  Thank you for testing the app and you certainly have a point there :+1: 

3MF fundamentally is a zip format but it turned out that on Linux the file formats were set to text/plain which is obviously wrong and the NMR Exception makes sense. See below:

```
$> file -i ~/Explore3MF/src/Apps/ThreeMFApp/Resources/3MF/3MFrocket.3mf
rocket.3mf: text/plain; charset=us-ascii
```
Now, download the same file from github and test the file type:
```
$> file -i ~/Downloads/rocket.3mf
rocket.3mf: application/zip; charset=binary
```
I just fixed the issue (https://github.com/hamedsabri/Explore3MF/commit/72872d58333 ). I need to investigate this since I don't quite understand why this happened in the first place. Maybe it had something to do with git LFS? not 100% sure.

The filters in native file dialog are set correctly as we only want to load *.3mf

This app should run fine on both Nouveau display and Nvidia driver.

Best Regards,
H

**Comment by hamedsabri** [comment]
@BrutPitt  ImGui::GetStyle().ScaleAllSizes and ImGui::GetIO().FontGlobalScale did the trick.  Thank you.
