### ISSUE TITLE
Viewport branch example_sdl_opengl2 issues

### ISSUE THREAD

**Issue by tom-seddon** [ocornut/imgui#2175]
**Version/Branch of Dear ImGui:** 

168af9b3777c0c3701b9222d95b085334adc52dc

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl2.cpp
OS: Windows 10
Compiler: VC++ _(if the question is related to building)_

**My Issue/Question:** _(please provide context)_

Tried to build SDL2 demo to check out the new docking stuff, but ran into some issues, both in terms of getting it built and getting it running.

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_

Run VS2015 x64 Native Tools Command Prompt and enter the commands below.

	md imgui-test
	cd imgui-test
	wget --no-check-certificate https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
	unzip SDL2-devel-2.0.9-VC.zip
	git clone https://github.com/ocornut/imgui
	cd imgui
	git checkout docking
	cd examples\example_sdl_opengl2
	set SDL2DIR=..\..\..\SDL2-2.0.9
	cl /Zi /MD /I %SDL2DIR%\include /I .. /I ..\.. main.cpp ..\imgui_impl_sdl.cpp ..\imgui_impl_opengl2.cpp ..\..\imgui*.cpp /link /LIBPATH:%SDL2DIR%\lib SDL2.lib SDL2main.lib opengl32.lib /subsystem:console

Result: `LINK : fatal error LNK1181: cannot open input file 'SDL2.lib'` - looks like the latest SDL puts x86 and x64 libs in separate folders. So add `x64` to the linker path:

    cl /Zi /MD /I %SDL2DIR%\include /I .. /I ..\.. main.cpp ..\imgui_impl_sdl.cpp ..\imgui_impl_opengl2.cpp ..\..\imgui*.cpp /link /LIBPATH:%SDL2DIR%\lib\x64 SDL2.lib SDL2main.lib opengl32.lib /subsystem:console

That builds, but doesn't run, because it needs SDL2.dll.

    copy "%SDL2DIR%\lib\x64\SDL2.dll" .

That runs, but after a moment or two, produces an error.

    Assertion failed: (g.FrameCount == 0 || g.FrameCount == g.FrameCountPlatformEnded) && "Forgot to call UpdatePlatformWindows() in main loop after EndFrame()?", file ..\..\imgui.cpp, line 3276

Edit main.cpp to add a call to that somewhere hopefully sensible.

    diff --git a/examples/example_sdl_opengl2/main.cpp b/examples/example_sdl_opengl2/main.cpp
    index f0cb373..9bccec2 100644
    --- a/examples/example_sdl_opengl2/main.cpp
    +++ b/examples/example_sdl_opengl2/main.cpp
    @@ -131,6 +131,7 @@ int main(int, char**)
    
             // Rendering
             ImGui::Render();
    +        ImGui::UpdatePlatformWindows();
             glViewport(0, 0, (int)io.DisplaySize.x, (int)io.DisplaySize.y);
             glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
             glClear(GL_COLOR_BUFFER_BIT);

This works, but the process hangs if you try to drag one of the dear imgui windows out of the Windows window. Ctrl+C from its console window will force it to quit though.

Thanks,

--Tom

P.S. example_sdl_opengl3 does build and run, though the suggested command line assumes x86

**Comment by ocornut** [comment]
Hello,
I pushed fixes for this example for SDL+OpenGL2 in 797f2044cdf0978321842ae8b3d1250f79cfbc39 and fixed the README missing the x86/x64 path, though as mentioned in comments everywhere you shouldn't really use the legacy OpenGL code.
