### ISSUE TITLE
Is hidpi officially supported yet?

### ISSUE THREAD

**Issue by gwjames** [ocornut/imgui#2177]
I am currently running ImGui 1.65 with GLFW 3.2 on a Mac with retina display.

Should I expect HiDPI to be working 100%? The window size retrieved is half the size of the framebuffer.

The GUI is rendering correctly but I am having some mouse coordinate mapping issues. It looks like the mouse coordinates being inserted are not getting scaled with the display ratio.

e.g. I have a vertical row of buttons. With my cursor at the top-left, the first button is highlighted. If I start moving my cursor down, the respective highlighted button is further and further down... where my cursor is over Y=200 but the button at Y=400 is highlighted.

Should there be some sort of scaling I should be setting in the input code?

**Comment by ocornut** [comment]
Click on the DPI tag for some pointers on Issues/PR.
