### ISSUE TITLE
imgui windows sliding by themselves

### ISSUE THREAD

**Issue by ValgeirK** [ocornut/imgui#2179]
I ran into line 4763 in imgui.cpp causing my windows to slide on their own. 

I am resizing my windows and moving the imgui windows in code to keep them in the same relative place and size. I do this with floats but in begin the stored location is floored by casting to an int and then back to float. Which causes the value to decrease by one each frame.

```
window->Pos = ImFloor(window->Pos);
```

I commented this line out and it fixed my issue but I wanted to point it out if this was intended or not.

**Comment by ocornut** [comment]
This is intended and necessary for various reasons.
If you want to move/resize windows please use rounded positions only.

**Comment by ValgeirK** [comment]
Ok, thank you
