### ISSUE TITLE
runtime error in example if IMGUI_IMPL_OPENGL_LOADER_GLAD is defined

### ISSUE THREAD

**Issue by doug-moen** [ocornut/imgui#2180]
**Version/Branch of Dear ImGui:**

Version 1.65 : 

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_opengl3.cpp, imgui_impl_glfw.cpp
OS: Ubuntu 16.04
Compiler: gcc 5.4.0

**My Issue/Question:** _(please provide context)_

`examples/example_glfw_opengl3/main.cpp` fails to run
if `IMGUI_IMPL_OPENGL_LOADER_GLAD` is defined.
The problem is here:
```
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLAD)
    bool err = gladLoadGL() != 0;
#endif
    if (err)
    {
        fprintf(stderr, "Failed to initialize OpenGL loader!\n");
        return 1;
    }
```
`gladLoadGL()` returns 0 on error, and non-zero on success.
So the error condition is inverted.
The fix is:
```
    bool err = gladLoadGL() == 0;
```

**Comment by ocornut** [comment]
This was already fixed in master.
