### ISSUE TITLE
vkDestroySwapchainKHR causes deadlock when used with SDL

### ISSUE THREAD

**Issue by eRabbit0** [ocornut/imgui#2181]
RE: SDL + Vulkan + Xorg
When SDL_DestroyWindow() is called before CleanupVulkan() it causes deadlock inside ImGui_ImplVulkanH_DestroyWindowData(), to be precise it hangs on vkDestroySwapchainKHR() call.

Problem manifests itself on my main system (Fedora 29 (4.18.16)) with both standard amdgpu and copr amdvlk drivers on AMD Radeon RX470.
Issue is absent on Fedora 29 (4.18.16) laptop with proprietary NVIDIA v410.66 driver (hybrid GPU).

When SDL_DestroyWindow() is called after CleanupVulkan() program finishes fine.
Seems like same issue with GLFW, as described in this thread: https://github.com/GPUOpen-Drivers/pal/issues/7

**Comment by ocornut** [comment]
Thank you @eRabbit0, I have now pushed that change. I could not see any extra warning from the validation layer; the equivalent GLFW+Vulkan example had it in the same order; and the window destruction code in the viewport branch did the same as well.
