### ISSUE TITLE
Request to provide example for using IMGUI with VTK 8.1

### ISSUE THREAD

**Issue by pdhahn** [ocornut/imgui#2182]
----

**Version/Branch of Dear ImGui:**

XXX

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp
OS: XXX 
Compiler: XXX _(if the question is related to building)_

**My Issue/Question:** _(please provide context)_

Please provide an example that uses IMGUI with VTK, preferably version 8.1 of VTK.

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
Sorry I am not able to develop and maintain sample on demand for less known frameworks.
Users of VTK can create this example and it'll be linked from the homepage and wiki.

**Comment by jaswantp** [comment]
Example implementation files and usage [here](https://github.com/ocornut/imgui/issues/3488#issuecomment-709008332)
