### ISSUE TITLE
Black screen and resolution glitched....

### ISSUE THREAD

**Issue by ImCytox** [ocornut/imgui#2189]
So i have a d3d11 hook which is using imgui as overlay above a game. When i inject this while the game is in background everything works fine, but when i inject while the game is in forground:
- first i get black screen
- when i tab out and back in, the resolution is totally fucked and i have to close the game...

Does it matter when ImGui gets initialized(when in background or in forground) ?

Any ideas what could be the problem ?

Thx in Advance

**Comment by ocornut** [comment]
Sorry your issue is ill-defined. You are not answering the questions asked by the template, nor providing a repro or enough information. 

> Does it matter when ImGui gets initialized(when in background or in forground) ?

I'm not sure what background/foreground means here.
