### ISSUE TITLE
Numpad Enter key is ignored when using ImGuiInputTextFlags_EnterReturnsTrue

### ISSUE THREAD

**Issue by dcourtois** [ocornut/imgui#2191]
Configuration:

   - docking branch @ 5f8c9ae (but probably valid for all branches)
   - GLFW / OpenGL3 back-end (unmodified)
   - Windows 10 / Visual Studio 2017 (up-to-date)
   - Compiled in Debug / Win64

To explain the issue a bit further: when using an input with the `ImGuiInputTextFlags_EnterReturnsTrue` option flag, only the Enter key of the main part of the keyboard is actually working. Validating the input using the numpad Enter key doesn't work.

The problem comes from here: https://github.com/ocornut/imgui/blob/50c43d1c8e031c56177fd13aab076ed3e1a75c26/imgui_widgets.cpp#L3360

This only checks for one key value; however GLFW has 2 distinct values for those 2 Enter keys, thus only one of my keyboard's Enter keys is working.

If most implementations support 2 different values for those 2 enter keys, it might make sense to add a new value into the `ImGuiKey_` enum to handle this secondary Enter key ? If you have any idea as to how this should be handled (if it should) feel free to comment here, I can work on a fix and send a pull request for review :)

**Comment by ocornut** [comment]
This is the PR you are looking for #2005:
In the meanwhile you can hijack `ImGui_ImplGlfw_KeyCallback()` function to replace `GLFW_KEY_KP_ENTER` with `GLFW_KEY_ENTER`.

**Comment by dcourtois** [comment]
@ocornut thanks for the quick answer ! I only checked the issues, next time I'll think of checking the PR too :) And thanks for the `ImGui_ImplGlfw_KeyCallback` pointer, it works perfectly. Closing this issue, sorry for the inconvenience.

**Comment by ocornut** [comment]
Note that this is now fixed by #2625.

**Comment by timbeaudet** [comment]
Umm, with this being fixed, is the TL;DR of how I'm supposed to a NumpadEnter to the KeyMap when ImGuiKey_Return or _NumpadEnter don't exist?
