### ISSUE TITLE
Individual Borders

### ISSUE THREAD

**Issue by gwjames** [ocornut/imgui#2192]
I've seen you can use FrameBorderSize, ImGuiCol_Border and ImGuiCol_BorderShadow for borders.

I was wondering if there was a way to specify which borders to render?

e.g. if you create a frame that you only want to have a right border

**Comment by ocornut** [comment]
Hello,

It is not possible at the moment, Styling V2 may eventually allow it by providing bordering variants (see #1535 #447) but probably not soon.
