### ISSUE TITLE
Is it possible to enable highlighting/color of the selected item from TreeNodeEx??

### ISSUE THREAD

**Issue by Bonicx** [ocornut/imgui#2193]
Since the multi select functionality is still not out yet, I would like to know if it is possible to highlight multiple selected nodes in TreeNodeEx?

**Comment by ocornut** [comment]
Yes you can use the ` ImGuiTreeNodeFlags_Selected` flag.

**Comment by Bonicx** [comment]
How do I make not selected when you have not click on anything yet? Right now it is highlighting the object in the list

**Comment by ocornut** [comment]
> How do I make not selected 

Don't use the `ImGuiTreeNodeFlags_Selected` flag.
The selection state is entirely on your side.

**Comment by Bonicx** [comment]
Alright thank you!

**Comment by ngminteck** [comment]
the best is the item object have a bool selection variable itself . this how i did multi select

**Comment by Bonicx** [comment]
Was kinda busy wrapping up my semester, so I have a container of object either a list or vector.
Right now only the first element that is selected will be highlighted in red, with ctrl left click I was able to select the other objects however, the second object and later on more objects that are selected will not be highlighted in red. Is there anyway to solve this? Like @ngminteck had mention about adding a bool variable to each object created?

**Comment by Bonicx** [comment]
@ocornut 
`if (node_clicked != -1)	
{
	 if (ImGui::GetIO().KeyCtrl) selection_mask ^= (1 << node_clicked); 
else
	selection_mask = (1 << node_clicked);
}`

I tried following the demo example of using this part for the multi select but it doesn't seems to be working
