### ISSUE TITLE
ImGui Treenode EX selection

### ISSUE THREAD

**Issue by digiminteck** [ocornut/imgui#2194]
**Version/Branch of Dear ImGui:**

1.65

opengl 3

Back-ends: imgui_impl_win32.cpp + imgui_impl_opengl3.cpp
OS: win 10 
Compiler: visual studio 2017

I have a string to store the item currently selected, which is default prefab

however when i run my code. the imgui show i select both prefab and texture.

XXX
```
// in declaration
std::vector <std::string> memory_asset_directory_name;

// in init
memory_asset_directory_name.push_back("Prefab");
memory_asset_directory_name.push_back("Texture");

// in draw function
ImGuiWindowFlags  CollapsingHeader_flag = ImGuiTreeNodeFlags_DefaultOpen;
	ImGuiTreeNodeFlags TreeNodeEx_flags = ImGuiTreeNodeFlags_None;
	if (ImGui::CollapsingHeader("Memory Asset"), CollapsingHeader_flag)
	{
		for (auto elem : memory_asset_directory_name)
		{
			TreeNodeEx_flags |= ImGuiTreeNodeFlags_Leaf | (elem.compare(current_selected_directory) == 0 ? ImGuiTreeNodeFlags_Selected : 0);
			ImGui::Text(current_selected_directory.c_str());
			ImGui::Text(elem.c_str());
			ImGui::TreeNodeEx(elem.c_str(), TreeNodeEx_flags, elem.c_str());
			if (ImGui::IsItemClicked())
			{
				current_selected_directory = elem;
			}
			ImGui::TreePop();
		}
	
	}

```

**Screenshots/Video** _(you can drag files here)_
<img width="189" alt="capture" src="https://user-images.githubusercontent.com/45137962/48669558-017ae400-eb42-11e8-8091-a686a0c1c08d.PNG">

**Comment by ocornut** [comment]
You are never resetting `TreeNodeEx_flags`. This is a regular C++/programming error.
