### ISSUE TITLE
No Mouse/Keyboard Inputs Received

### ISSUE THREAD

**Issue by r3peat** [ocornut/imgui#2198]
**Version/Branch of Dear ImGui:**
v1.66 WIP

**Back-end file/Renderer/OS:**
Back-ends: imgui_impl_WIn32.cpp + imgui_impl_DX9.cpp
OS: Win10 

**My Issue/Question:** 
Using a d3d9::present hook to do some internal rendering inside some hooked process.
Rendering is fine so i guess the HWND is correct but it just does not process any input into ImGui elements like mouse nor keyboard.
All mouseinput/keyboardinput params are correctly passed to ImGuiIO and also the cursor pos is correct (i verified with a circle draw around the cursor)

the hook is fine
imgui inits without errors
rendering is fine

just no inputs

ImGui::IsAnyItemHovered() is always 0
ImGui::GetIO().WantCaptureMouse is always 0

i dont use ImGui_ImplDX9_WndProcHandler
i pass wndParams with my own logic, which works in another project which hooks another process (i 1:1 just use the same code)

What i want to know is where i can check stuff to figure out whats causing this

**Standalone, minimal, complete and verifiable example:**

if required i can post code but i think its not needed. The same code runs just fine when hooked to another process.

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
Sorry but #1586
