### ISSUE TITLE
Interacting with slider will move the window when use dock space

### ISSUE THREAD

**Issue by GuoJiechang** [ocornut/imgui#2202]
**Version/Branch of Dear ImGui:**

v1.66 WIP

**Back-end file/Renderer/OS:** _(or specify if you are using a custom engine back-end)_

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
OS: windows 
Compiler: XXX _(if the question is related to building)_

**My Issue/Question:** _(please provide context)_
The slider works fine when floating on the dock space, however, when I move this window into a dock space and move the slider, the window will move as well. I've checked the demo,not have such problem. I am not sure what causes this problem. Here's the gif showing the problem.

Thx for help!
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18341331/48891431-525a4780-ee76-11e8-8252-5bacf90cc413.gif)

**Standalone, minimal, complete and verifiable example:** _(see CONTRIBUTING.md)_
```
void showDockSpace(bool* p_open)
{
	static bool opt_fullscreen_persistant = true;
	static ImGuiDockNodeFlags opt_flags = ImGuiDockNodeFlags_PassthruDockspace;
	bool opt_fullscreen = opt_fullscreen_persistant;

	// We are using the ImGuiWindowFlags_NoDocking flag to make the parent window not dockable into,
	// because it would be confusing to have two docking targets within each others.
	ImGuiWindowFlags window_flags = ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoDocking;
	if (opt_fullscreen)
	{
		ImGuiViewport* viewport = ImGui::GetMainViewport();
		ImGui::SetNextWindowPos(viewport->Pos);
		ImGui::SetNextWindowSize(viewport->Size);
		ImGui::SetNextWindowViewport(viewport->ID);
		ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
		ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
		window_flags |= ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove;
		window_flags |= ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus | ImGuiWindowFlags_NoBackground;
	}

	ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
	ImGui::Begin("DockSpace Demo", p_open, window_flags);
	ImGui::PopStyleVar();

	if (opt_fullscreen)
		ImGui::PopStyleVar(2);

	//// Dockspace
	ImGuiIO& io = ImGui::GetIO();
	if (io.ConfigFlags & ImGuiConfigFlags_DockingEnable)
	{
		ImGuiID dockspace_id = ImGui::GetID("MyDockspace");
		ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), opt_flags);
	}
	ImGui::End();
}
while (!glfwWindowShouldClose(window))
{
	glfwPollEvents();
        //create imgui
	ImGui_ImplOpenGL3_NewFrame();
	ImGui_ImplGlfw_NewFrame();
	ImGui::NewFrame();

        bool open = true;
	showDockSpace(&open);

        ImGui::Begin("Animator");
        static float f = 0.0f;
	ImGui::SliderFloat("", &f, 0.0f, 1.0f);
	if (percentage != f)
	{
		percentage = f;
		animator.setFrame(percentage);
	}
	ImGui::End();
```

**Screenshots/Video** _(you can drag files here)_

**Comment by ocornut** [comment]
Please provide a `Standalone, minimal, complete and verifiable example: (see CONTRIBUTING.md)`
And then you will understand your bug.

**Comment by GuoJiechang** [comment]
@ocornut 
Hi, I've add the code including the code for dock space which I modified from the demo code, and in the main loop, I add a new window with a slider inside it. I can't figure out what's going wrong.

**Comment by ocornut** [comment]
Your slider has no ID this is invalid. Please read the FAQ.

**Comment by GuoJiechang** [comment]
@ocornut 
Thank you very much for your reply, it works.
