### ISSUE TITLE
ImGUI on 3D Position

### ISSUE THREAD

**Issue by cristianoprogrammer** [ocornut/imgui#2204]
**Context:** 

I need put a ImGui window in a 3d perspective position on a Augmented Reality application.

Like this:

<img width="667" alt="captura de tela 2018-11-22 as 10 50 12" src="https://user-images.githubusercontent.com/235153/48904103-8157c580-ee44-11e8-9caa-68bae127798f.png">

----------------------------------------------------------------------------

**Problem:**

When i change from orthographic matrix to perspective matrix, the position of components and the interaction change

----------------------------------------------------------------------------

**If someone have one direction to me follow.  Tks!**

**Comment by ocornut** [comment]
This is a 3D rendering problem and not really within the scope of this issue tracker unless you nail down a precise and actual dear imgui question.

If you reproject the imgui rendering data is a non-standard manner you'll need to calculate your mouse cursor position accordingly to the projection.

**Comment by ocornut** [comment]
Going to close this as I think you'll get better answers in a general 3d programming forum and your request is too vague. Please reopen if you have more precise information that leads to an actual precise imgui question.
