### ISSUE TITLE
Platform_SetWindowPos/Platform_SetWindowSize called continously in the viewport branch

### ISSUE THREAD

**Issue by marius-luca-87** [ocornut/imgui#2205]
Revision: 251541308024eb2830b8d4fb3d64d1869995f0b9
Date: 22-Nov-18 16:29:18

imgui.cpp after line 7850  "// Apply Position and Size (from ImGui to Platform/Renderer back-ends)"

        if (!viewport->PlatformRequestMove)
            g.PlatformIO.Platform_SetWindowPos(viewport, viewport->Pos);
        if (!viewport->PlatformRequestResize)
            g.PlatformIO.Platform_SetWindowSize(viewport, viewport->Size);

There seems to be a typo in the "platform request move/size"condition leading to continuous calls.

**Comment by ocornut** [comment]
It is currently intentional that we call those functions every frame, currently it doesn't seem to be problematic cost wise. The back-end can freely compare last known position.

**Comment by marius-luca-87** [comment]
Thanks for the info. I was unsure if this is something that needs to be handled on the backend side.

**Comment by ocornut** [comment]
I think I'll actually had a cache to compare too on imgui side now. I was hesitant because we may run into bugs, but if that's the case I'd rather run into them on imgui side.
