### ISSUE TITLE
Make custom rendering using ImDrawList click-throughable (so you can click/drag stuff behind shapes)

### ISSUE THREAD

**Issue by Hecklezz** [ocornut/imgui#2208]
**Version/Branch of Dear ImGui:**
1.66

**Back-end file/Renderer/OS:**
Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
OS: Windows 10 1809 (Latest)
Compiler: VS2017 (Latest)

**My Issue/Question:**
I am trying to do custom rendering using ImDrawList to draw shapes and other types of drawing however, I need for them to be clicked-through. Right now if I have a filled shape drawn on the screen and I have something(button or text, doesn't matter what) behind this shape, clicking on the shape will bring it into focus and not click the thing behind (button or text, or anything) behind it. 

I have tried specifying the window flags with the following but they didn't help- 
ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoInputs

The main window is created using CreateWindowEx with the following-
DWORD style = WS_POPUP;
DWORD exstyle = WS_EX_LAYERED;

And it still did not help, the shapes would still take focus.

**Standalone, minimal, complete and verifiable example:**
```
ImGuiWindowFlags flags = ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoInputs | ImGuiWindowFlags_NoDecoration;

ImGui::Begin("Shapes", 0, flags);
ImDrawList* draw_list = ImGui::GetWindowDrawList();

static ImVec4 col = ImVec4(1.0f, 1.0f, 0.4f, 1.0f);
const ImU32 col32 = ImColor(col);
draw_list->AddCircleFilled(ImVec2(WINDOW_WIDTH/2, WINDOW_HEIGHT/2), 100, col32, 32); 

ImGui::End();
```

**Screenshots/Video**
https://streamable.com/52g39

**Comment by ocornut** [comment]
Hello,

Your text is ambiguous as to why by "click-through" you mean "click-through within the imgui context, reaching other imgui windows behind" or "click-through within the OS". But both your suggestion and `WS_EX_LAYERED` and video suggest the later, in which case this is not a dear imgui question but something to do at the windows api level.

**Comment by Hecklezz** [comment]
Thank you for explaining that it is likely a windows api level issue, but off the top of your head do you have any suggestions or thoughts on what it could be, or what flag I may be missing? From what I gathered from googling, WS_EX_LAYERED should have been the solution but it wasn't.

**Comment by Hecklezz** [comment]
No problem, thank you anyway!
