### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by dkrikun** [ocornut/imgui#221]
Currenlty, ImGui is thread-agnostic and not thread-safe.

In a project, I have multiple "agents", each running on a separate thread, and I would like to have these agents output/input stats to/from ImGui, let's say, each agent works with its own window (`ImGui::Begin()`/`ImGui::End()`).

So naively, I added mutexes etc. to properly sync. access to ImGui part. However, this did not work well. The problem with this setup is that the agent won't necessarily call ImGui api at the right time, that is between begin frame/end frame. Thus, sometimes, a window is shown, sometimes it doesn't, or even it has it's content drawn twice.

Any ideas on how one could solve the problem?

**Comment by hypernewbie** [comment]
The same problem happens with any stateful API, for example OpenGL itself has binding states.
I suggest wrapping higher scale operations eg. DrawUIWindow() or DrawUIBox() which gets a lock, does everything between Begin() and End() before releasing the lock.

**Comment by ocornut** [comment]
I believe the problem he is referring to is the fact that threaded user code can run during the time between Render() and NewFrame().

You would need to take the lock before the calling ImGui::Render() up after calling ImGui::NewFrame() which may or not be a long time. You can aim to reduce that time by putting NewFrame right after Render() if you can retrieve your inputs at this point.

**Comment by dkrikun** [comment]
@ocornut That's right. However, the problem is even harder: the threaded code might run any number of times between `Render()` and `NewFrame()`.
It might run exactly once -- than all is good. But it also might not run, than we've got flickering; or it might run twice, than we've got widgets added twice in a window. I don't think that locking between `Render()` and `NewFrame()` will help.

**Comment by ocornut** [comment]
Ah well then it's up to you to manage that, no magic. If you aren't just logging stuff and you are displaying interfaces/tools, and you can't reliably do it at the same frequency from the threads, perhaps your threaded task should expose data for the main thread to turn into ui. 

You can use a pattern like IMGUI_ONCE_UPON_A_FRAME to workaround being too fast but not the opposite. I don't see an easy way individual window could allow to be refreshed at a different frequency.

**Comment by dkrikun** [comment]
Might it be possible to tell the widgets to "stay" (as opposed to being cleared by `NewFrame()`)  and then the threads could just update the existing data?

**Comment by ocornut** [comment]
Sorry that's not possible it doesn't even make sense with the api and architecture.

**Comment by dkrikun** [comment]
If I understand you correctly, it is due to the *immediate mode* ui concept?

**Comment by ocornut** [comment]
Not exactly. The API i'm providing is designed to process your data immediately and your data can be temporary (eg: on the stack). We could make an API that assumed persistent user data and then I could store widget infos and edit the data later on without another user submission.

Technically we could have an immediate-mode API that retain more infos that ImGui does and assume more persistence. But thats not how ImGui is designed.

**Comment by dkrikun** [comment]
I'm not pressing in any way to violate the design principles of ImGui, instead I'm trying to understand if it may be possible to help with the usecase without doing so.

I can see that there is a code in `ImGui::Begin` that implements *get-or-create* semantics through `FindWindowByName`. What if I disable disposing of all windows and widgets in the `NewFrame` (so that the data will stay) and than use `IMGUI_ONCE_UPON_A_FRAME` to avoid being too fast?

Thanks!

**Comment by ocornut** [comment]
The best you could do would be to preserve the ImDrawList and draw the old window. Again there's no "widget" stored only the vertices to do them, so the interaction can only happen at the time you call the widgets again. 

In theory that would be possible (drawing only, you wouldn't be able to interact with the window until it is running again). In practice I believe there will be lots of bugs and maintenance required because that's not what the code expect. For example we ditch the active id if the id didn't exist in the last frame. That sort of thing would be to be reworked considering disparate per-window updates.

So this is "correct"
> What if I disable disposing of all windows and widgets in the NewFrame (so that the data will stay) 
But it's not just a matter of commenting the few lines in NewFrame(), there will be lots other changesa and my intuition is they would make ImGui code more complex.

**Comment by dkrikun** [comment]
Ok, thanks, I'm closing this.

**Comment by ocornut** [comment]
I think it is an idea we can reevalute in the future, to allow to "freeze" a window. It's probably not in any immediate roadmap.
