### ISSUE TITLE
clang warnings

### ISSUE THREAD

**Issue by Lecrapouille** [ocornut/imgui#2225]
The following code:
```
void foo::bar()
{
    std::string name("foo'");
    ImGui::Text(name.c_str());
}
```
does not produce warnings with g++ but with clang++ (version 3.8) I have:
```
      format string is not a string literal (potentially insecure)
      [-Wformat-security]
          ImGui::Text(name.c_str());
```
Should I wrote like ImGui::Text("%s", name.c_str());

**Comment by ocornut** [comment]
You can also use TextUnformatted(name.c_str()); which will be faster.

**Comment by Lecrapouille** [comment]
Thx !

**Comment by seanballais** [comment]
I would also just to inform that this problem also occurs in Clang 10. I would guess that it's just the result of the Clang static analyzer.

**Comment by ocornut** [comment]
Sean could you post the precise warnings you are getting while compiling dear imgui or the demo?

**Comment by seanballais** [comment]
@ocornut, I compiled my project which contains the following code snippet:

```cpp
     eastl::array<eastl::string, 3> mouseButtonStateTexts;
     ...
     ... {
        ...
        ImGui::Text(mouseButtonStateTexts[i].c_str());
     }
```

Compiling with Clang 10 shows this warning:

```cpp
/home/seanballais/Documents/Academics/UPVTC/Subjects/Thesis/System/corex/src/corex/core/DebugUI.cpp:212:19: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
      ImGui::Text(mouseButtonStateTexts[i].c_str());
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/seanballais/Documents/Academics/UPVTC/Subjects/Thesis/System/corex/src/corex/core/DebugUI.cpp:212:19: note: treat the string as an argument to avoid this
      ImGui::Text(mouseButtonStateTexts[i].c_str());
                  ^
                  "%s",
```

I'm also using Conan.

**Comment by ocornut** [comment]
So its in your code... the answers above state you should use TextUnformatted() instead

**Comment by seanballais** [comment]
@ocornut, yep! I did that too already. I think it's because of Clang's behaviour.

**Comment by richjohnson-wwt** [comment]
I am getting this warning with ImGui::TextWrapped where I need my text to wrap. I don't see TextWrappedUnformatted as an option.
