### ISSUE TITLE
MingW fails to build

### ISSUE THREAD

**Issue by rokups** [ocornut/imgui#2226]
I am using snapshot of docking branch and MingW fails to build it because `IsBuilt()` function is defined in header and marked as `dllexport`/`dllimport`. Seems related to https://github.com/ocornut/imgui/issues/349. Moving function to cpp or removing export macro would be great. Thanks!

Compiler: GCC (Rev2, Built by MSYS2 project) 7.2.0

**Comment by ocornut** [comment]
Fixed in master, thank you! You may cherry-pick the commit in your copy of the docking branch until it is merged back there.
