### ISSUE TITLE
Child Windows Rounding Isn't Applied to Images

### ISSUE THREAD

**Issue by Erfan-Ahmadi** [ocornut/imgui#2227]
![untitled](https://user-images.githubusercontent.com/10983665/49444514-a3f2c280-f7e4-11e8-801f-7bb8d35e0239.png)
Is there a way that roundings can get applied to images as well?
Or should I write a shader for each image that makes them round?

**Comment by ocornut** [comment]
Hello,
Clipping is performed using rectangle so that's not possible.
However in your case, if you are going to display an image fitted within a rounded window, you may use `ImDrawList::AddRoundedImage()` and display the image with rounded corners yourself.
