### ISSUE TITLE
SDL Texture rendered in ImGui

### ISSUE THREAD

**Issue by ivsancho** [ocornut/imgui#2228]
**Version:** 1.67    **Branch:** master
**Environment:** SDL2
**Operating System:** Windows 10

**SDL Texture rendered in ImGui**

Hello,

I'm developing a little custom 2D graphic engine with SDL and ImGui and I have the problem that I would like to draw in ImGui a SDL_Texture. Code sample:

```
...
//SDL Texture:
  texture = SDL_CreateTexture(manager.render_->renderer(),
                              SDL_PIXELFORMAT_RGBA8888,
                              SDL_TEXTUREACCESS_TARGET, 200, 200);
...
//Render zone:
    SDL_SetRenderTarget(manager.render_->renderer(), texture);
    //Some SDL render lines.
    SDL_SetRenderTarget(manager.render_->renderer(), texture);
...
//ImGui:
    ImGui::Image((ImTextureID)texture, { 200.0f, 200.0f });
```

This last part doesn't work and crashes in runtime :S How could I bind my SDL texture with ImGui Image? I'm not using any other render API, only SDL 2.

Thanks in advance (:

**Comment by ebachard** [comment]
Hi,

I'd suggest you to have a look at https://github.com/ocornut/imgui/issues/1116

**Comment by ivsancho** [comment]
Hi,

thank you for your answer but this is not what I'm exactly looking for... :( I'm not working directly with OpenGL in this case, should I do it?

**Comment by ebachard** [comment]
@ivsancho : sorry, I read too fast, and I missed the Windows 10 point. I simply would tell that SDL_Renderer does not marry well with ImGui, because they seem to do the same things.

Indeed, you can use another driver. In SDL2 sources, you should find the one to fit your needs. 

I never used directx or friends (only OpenGL for me, for cross compilation reasons), but if I'm not wrong, there is https://wiki.libsdl.org/SDL_HINT_RENDER_DRIVER if you want to force a given driver, SDL_SetHint should help you e.g. : 
````
SDL_SetHint(SDL_HINT_RENDER_DRIVER, "software"); 
```` 
The full lsit of choices is (if I'm not wrong): direct3d, opengl, opengles2, opengles, metal, software

Last there is a FAQ in imgui.cpp and maybe this could help you (line around 535 IIRC), and everything is explained, but you probably already read it.

HTH

**Comment by ocornut** [comment]
@ivsancho you need to look into how SDL_Renderer perform its rendering.
If you are using the GL back-end of SDL_Renderer, find out how to extract the GL texture id from the SDL_Texture. If you are using the DX9 back-end of SDL_Renderer, ditto.

Then at your `Image()` call point call whatever function you found to retrieve this low-level identifier out of the SDL_Texture and pass that to `Image()`.

(Another solution would be to implement the ImGui rendering using SDL_Renderer API directly, not rely on GL/DX9 but unfortunately SDL_Renderer is so limited it doesn't have functions for rendering triangles and it cannot be done with the current version of SDL_Renderer.)

**Comment by ocornut** [comment]
My honest more sincere answer would be:

> I'm developing a little custom 2D graphic engine with SDL and ImGui and I have the problem that I would like to draw in ImGui a SDL_Texture. 

Don't use SDL_Renderer if you are developing anything non trivial. Just use OpenGL or DirectX or Vulkan.
SDL_Renderer as it stands today is really too limited to do anything and will get in the way of sensible progress. I honestly don't even know why this API exist.

**Comment by ivsancho** [comment]
@ebachard @ocornut Thank you for your answers, I have been working these last days in the posible solution during my free time but the truth is that I have advised that SDL is a limited system as you said. I tried to find out the handler of the texture and I also tried other posible solutions, but I have changed my initial idea. I will continue developing and reading documentation and, if I guess something, I will share it with you (:

Thanks guys!

**Comment by ocornut** [comment]
> I have advised that SDL is a limited system as you said

Just to clarify, SDL is great and useful.

(I was walking about SDL_Renderer which is an optional component of SDL used for rendering.)

**Comment by ivsancho** [comment]
> Just to clarify, SDL is great and useful.

Yes, sorry, that's I wanted to say, SDL is nice and easy to learn but it seems more limited than other graphic API. In my case, I only want to program a little 2D engine to develop a fun toy but SDL_Renderer is limited as you said and it seems that SDL works in a different way with textures than OpenGL.

**Comment by ocornut** [comment]
SDL is not a graphic API, it is a windowing/inputs/events/misc API. 

It's perfectly compatible with other graphics API and this is what most sensible software are doing (the examples/ app are also doing exactly that).

If you want to program a little 2D engine using SDL or GLFW as a base for portability is ideal. Just don't use the SDL_Renderer component of it. SDL + your own DX/OpenGL graphics stuff.

**Comment by ivsancho** [comment]
Okey, thank you for your advises (:
