### ISSUE TITLE
Moving and resizing outside window broken in latest Viewport branch.

### ISSUE THREAD

**Issue by timleijten** [ocornut/imgui#2229]
Hello,

I just tried the newest docking branch(1.66b) on Linux(Ubuntu 18.10, Gnome). And noticed some serious issues. I am using the glfw_opengl3 example.

First, whenever I drag a ImGui window out of the main ImGui window, it stops dragging, probably because it lost focus. This is annoying, but might be the fault of GLFW instead of ImGUI(It works fine in the SDL example) Do you know if it's possible for me to solve this?

Second, on GLFW, when a ImGui windows is dragged outside of the main window, dragging it will cause it to shake(very heavily) away from the mouse:
![shakingimgui](https://user-images.githubusercontent.com/45663599/49591873-ee547a80-f96f-11e8-9ef0-c817fa41f37f.gif)
But, the shaking doesn't happen when I enable viewports decoration and drag it with the decoration from Gnome.(It still shakes when dragged on an ImGui part) So what's happening here? Apparently, ImGui or the example is doing something wrong with setting the position of the window, but I can't find the bug in the code. Do you know what's wrong?

Third issue, when resizing the actual window in ImGUi on an external window, ImGui is resizing too slow. But when the window is resized using decorations, it works just fine:
![resizingimgui](https://user-images.githubusercontent.com/45663599/49592620-e09ff480-f971-11e8-96d6-7cabb0baf776.gif)
First, resizing on a normal window is shown, then resizing using ImGui handle on a decorated window, and then using native Gnome Window handle to resize. Notice how resizing with the nativie Gnome handle doesn't cause artifacts.
So, why does that happen? How is resizing in ImGui different from resizing from code? What is being done differently?(Are you maybe precalculating what the Window size should be or something?)

So could you help me with this?(I hope I provided enough details)

Thanks!

**Comment by ocornut** [comment]
Please post your message in #2117 there is a thread for it.
Also note I have __just__ pushed some commits which may fix some of that (they are some of the things discussed in #2117).

I am not a Linux user and cannot solve everyone's problem so I would need Linux users to dig into those problems themselves (it may take hours/days of work but I can't magically be doing all that myself). Closing this.

**Comment by ocornut** [comment]
@timleijten Did you try again with the latest commit I mentioned? https://github.com/ocornut/imgui/commit/f3a0b17bb8be22c8ae88a6a064c25c1cf13c3c72

**Comment by timleijten** [comment]
@ocornut Yes I did. The dragging issue has been solved! Unfortunately, the resizing issue and the dragging out of main window issue remain. But those aren't really big problems.
So thank you very much!

If you don't mind me asking, what was the problem?

Oh and I have a feature request, if you have some spare time, could you maybe look into GLFW and it's transparancy. As GLFW supports windows with transparent backgrounds, which would allow for window rounding and transparency like in the main window.

Thanks!

**Comment by ocornut** [comment]
Could you edit your post on the main thread to reflect those findings? I purposely told you some issues were fixed so you could update your feedback accordingly before posting on the right thread.

**Comment by timleijten** [comment]
> Could you edit your post on the main thread to reflect those findings? I purposely told you some issues were fixed so you could update your feedback accordingly before posting on the right thread.

Yes I will, definitely!
