### ISSUE TITLE
ImGui::TabItemEx(): Missing NULL pointer check in docking branch

### ISSUE THREAD

**Issue by pwegscheider** [ocornut/imgui#2231]
**Version/Branch of Dear ImGui:**

Version: Dear ImGui 1.67 WIP (16602)
Branch: docking
Operating System: Windows

**My Issue/Question:** 
With the commit "Docking: Added io.ConfigDockingTabBarOnSingleWindows option"
TabItemEx() tries to access a NULL pointer if it is called for "normal" tabs.

**Standalone, minimal, complete and verifiable example:** 

Try sample ImGui Demo -> Examples -> Documents
docked_window is a NULL pointer, which is not checked in the code: 
```
    // Drag and drop a single floating window node moves it
    // FIXME-DOCK: In theory we shouldn't test for the ConfigDockingNodifySingleWindows flag here.
    // When our single window node and OnlyNodeWithWindows are working properly we may remove this check here.
    ImGuiDockNode* node = docked_window->DockNode;
    const bool single_window_node = node->IsRootNode() && node->Windows.Size == 1 && g.IO.ConfigDockingTabBarOnSingleWindows;
```
With this fix the sample works:
```
    ImGuiDockNode* node = docked_window != NULL ? docked_window->DockNode : NULL;
    const bool single_window_node = node != NULL && node->IsRootNode() && node->Windows.Size == 1 && g.IO.ConfigDockingTabBarOnSingleWindows;

```

**Comment by ocornut** [comment]
Thank you @pwegscheider, this is fixed now!
