### ISSUE TITLE
Win32 child window can't update the mouse input

### ISSUE THREAD

**Issue by leozzyzheng** [ocornut/imgui#2232]
**Version/Branch of Dear ImGui:**

Version: 1.65
Branch: release version

**Back-end/Renderer/Compiler/OS** 

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Compiler: VS2015 with update 3, version 14.0.25420.1
Operating System: Windows 7 x64

**My Issue/Question:** 

When I use ImGui on a Win32 window created by style `WS_CHILD`, the `ImGui_ImplWin32_NewFrame` can't handle the mouse input correctly when the child window has no focus.

**Standalone, minimal, complete and verifiable example:** 
The source code in `ImGui_ImplWin32_UpdateMousePos` is:
```
if (::GetActiveWindow() == g_hWnd && ::GetCursorPos(&pos))
```

The `GetActiveWindow()` will return the parent window when the child window has no focus, the child window has no focus by default, so the mouse input will has no effect on the child window.

I have changed the code to check whether the hwnd returned by `GetActiveWindow()` is the parent(including the parent of parent and all of them). The code works fine to me and I think it need be fixed.

**Screenshots/Video**
NONE

**Comment by ocornut** [comment]
What is the code you used?

**Comment by leozzyzheng** [comment]
@ocornut Very simple, just use [IsChild](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-ischild) to also check the window returned by `GetActiveWindow` is the parent of `g_hWnd`. The real code might be:

```
HWND hwnd = ::GetActiveWindow();
if ((hwnd == g_hWnd || ::IsChild(hwnd, g_hWnd)) && ::GetCursorPos(&pos))
```

**Comment by leozzyzheng** [comment]
@WasserEsser Thanks for your reply, I just forget that thread is also related to the HWND.

**Comment by ocornut** [comment]
Hello @leozzyzheng, could you confirm that this is still needed even as the code was changed to use `GetForegroundWindow()` ?
I don't know if GetForegroundWindow may return the child window directly?

**Comment by ocornut** [comment]
I pushed a change using ::IsChild() now.

**Comment by leozzyzheng** [comment]
@ocornut Sorry reply you late, I think `GetForegroundWindow` could solve the thread issues and `IsChild` solve the relationship issue. Thanks for your update.
