### ISSUE TITLE
Create a text field that add entry in SFML

### ISSUE THREAD

**Issue by peminguyen** [ocornut/imgui#2236]
Hi there,

I just learned about ImGUI like a few hours ago. I need to create a text field that allows me to enter a text within SFML, and get that input to store it as a string. 

I wonder if you have any idea how to make the combination of ImGUI and SFML? Thanks a lot!

**Comment by ocornut** [comment]
Hello,

Have you looked for the word SFML in the readme and the wiki in the Bindings/Framework section?
