### ISSUE TITLE
Getting scrollbar sizes

### ISSUE THREAD

**Issue by aCuria** [ocornut/imgui#2238]
I wish to draw an image in a window with the functions "Fit to window" and "Fill Window" where:

1) When using "Fill window" the scrollbar may appear on one axis but not both
2) When using "Fill window" the scrollbar does not appear on both axis 

I am using ImGui::GetContentRegionAvail() for these computations but it does not work perfectly:

1) If the window initially has scrollbars on one more more axis, ImGui::GetContentRegionAvail() returns the content region available assuming the scrollbars exist. This will cause "fit to window" to compute a smaller image size than expected.

2) "Fill Window" always ends up with scrollbars on both axis

Whats the best way to do these computations? I imagine i need to know the size of the scrollbar

In the code below, `screenSize = ImGui::GetContentRegionAvail(); `
and the result of the function is passed to the second parameter of `ImGui::Image()`

`Vec2f Zoom::fitToScreen(const Vec2f & textureSize, const Vec2f & screenSize) const`
`{`
	`float aspectRatio = textureSize.width / textureSize.height;`
	`auto scale = textureSize / screenSize;`
	`return scale.x > scale.y ? Vec2f{ screenSize.x, screenSize.x / aspectRatio } : Vec2f{ screenSize.y * aspectRatio, screenSize.y };`
`}`

`Vec2f Zoom::fillScreen(const Vec2f & textureSize, const Vec2f & screenSize) const`
`{`
`	float aspectRatio = textureSize.width / textureSize.height;`
`	auto scale = textureSize / screenSize;`
`	return scale.x < scale.y ? Vec2f{ screenSize.x, screenSize.x / aspectRatio } : Vec2f{ screenSize.y * aspectRatio, screenSize.y };`
`}`

**Comment by ocornut** [comment]
This is falling into the XY Problem ( https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem ) as I am aware you are trying to solve #2212. Please open #2212 when you have provided a clear repro, then you may also discuss your suggested solution there including the contents of this post above.
