### ISSUE TITLE
Cannot dynamically add new fonts

### ISSUE THREAD

**Issue by petrihakkinen** [ocornut/imgui#224]
When I add a new font at runtime (after init) and rebuild the texture, the new font appears ok but existing fonts get corrupted. I think this happens because the glyphs move around in the font atlas but the texture coordinates of old fonts are not updated. Is it possible to somehow fix this without needing to readd all previously added fonts to the atlas?

**Comment by ocornut** [comment]
Looks like a bug, after building the font atlas we call ImFontAtlas::ClearTexData().
When adding new fonts the old font isn't in the InputData yet so after the second atlas build Fonts[0] isn't updated. Not sure what's the righter way to fix it yet.

**Comment by petrihakkinen** [comment]
Rerasterizing everything is acceptable for me. It just felt buggy that adding a new font corrupts the old fonts. I would be happy if adding a new font would "just work". (I'm doing lots of live coding, so I'm used to adding new resources on the fly. Speed is not critical in this case.).

No need to rush this fix, take your time.

**Comment by ocornut** [comment]
That last commit https://github.com/ocornut/imgui/commit/5df542c3c09f09676c6f54e539736351219b8bf4 allows to append new font.

I moved the ClearInputData() from imgui to application side, so it is in the example applications but anyone integrating with their own engine can see more clearly what is being done.
Connects to #220 only when calling ClearInputData() you'll notice that ImFontAtlas has taken ownership of the TTF blob.

**Comment by petrihakkinen** [comment]
Thanks, it fixed the issue!

**Comment by ocornut** [comment]
FYI work on `dynamic_fonts` toward 1.92 (#8465) adds support for adding font dynamically at any time in the frame.
