### ISSUE TITLE
Imgui can't interactive with anything.

### ISSUE THREAD

**Issue by the7shfun** [ocornut/imgui#2243]
I not a c++ guys. So may have something i dont know.
I spent a whole day try to figure out why .But still cant work.
I just write comment in code.Hope can help with understanding.
Please forgiving my english. :)

`extern LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);
LRESULT CALLBACK hkWndProc(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
{
### 	//just some test. Dont mind.
	if (Msg == WM_MOUSEMOVE)
	{
		mousePos.x = (signed short)(lParam);
		mousePos.y = (signed short)(lParam >> 16);
		return 0;
	}

### 	//i try return true or false or 1 or 0.Same problem.
	if (ImGui_ImplWin32_WndProcHandler(hWnd, Msg, wParam, lParam))
		return 1;

### 	//done mind.
	//if (!clickThough && (ImGui::GetIO().WantCaptureMouse || ImGui::GetIO().WantCaptureKeyboard))
	//	return 1;

### 	//old version i use this. I saw the new version use DefWindowProc . but i got some issue with this.
	return CallWindowProc(oriWndProc, hWnd, Msg, wParam, lParam);
}

void ImguiInit()
{
### 	//Get main window . Dont mind this.
	mainWinProc = GetMainWindow();

	oriWndProc = (WNDPROC)SetWindowLongPtr((mainWinProc), GWL_WNDPROC, (LONG)(LONG_PTR)hkWndProc);

	ImGui::CreateContext();
### 	//I saw demo do this. But i dont know why. I not the c++ guys.
	ImGuiIO& io = ImGui::GetIO(); (void)io;
	ImGui_ImplWin32_Init(mainWinProc);
	ImGui_ImplDX11_Init(pDevice, pContext);

### 	//just some color stuff
	ImGui::GetStyle().Colors[ImGuiCol_MenuBarBg] = ImVec4(0.99f, 0.62f, 0.88f, 0.40f);
	ImGui::GetStyle().Colors[ImGuiCol_HeaderHovered] = ImVec4(0.99f, 0.05f, 0.49f, 0.80f);
	ImGui::GetStyle().Colors[ImGuiCol_TitleBg] = ImVec4(0.94f, 0.34f, 0.51f, 0.83f);
	ImGui::GetStyle().Colors[ImGuiCol_TitleBgActive] = ImVec4(0.96f, 0.20f, 0.44f, 0.90f);

### 	//and told me init done.
	MessageBox(0, "Imgui init Done!", 0, 0);
}

void ImguiDraw(IDXGISwapChain* pSwapChain)
{
### 	//window come up. But i cant interactive with anything.Just a window.
	ImGui_ImplDX11_NewFrame();
	ImGui_ImplWin32_NewFrame();
	ImGui::NewFrame();
	**//I try this still not working**
	ImGui::CaptureMouseFromApp(true);

### 	//Also try demoWindow same problem
	//ImGui::ShowDemoWindow();

	if (ImGui::Begin("Test Demo"))
	{
		ImGui::Text("WantCaptureMouse : %d", ImGui::GetIO().WantCaptureMouse);
		ImGui::Text("WantCaptureKeyboard : %d", ImGui::GetIO().WantCaptureKeyboard);
		ImGui::Text("ReadMousePos : %.0f %.0f", mousePos.x, mousePos.y);
### 		//Just try if i do this it will work or not. But doesnt work.
		ImGui::GetIO().MousePos = mousePos;
		ImGui::Text("MousePos : %.0f %.0f", ImGui::GetIO().MousePos.x, ImGui::GetIO().MousePos.y);
		if (ImGui::BeginMenu("Menu Test"))
		{
			ImGui::EndMenu();
		}

		ImGui::End();
	}

	ImGui::Render();
	ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());

	//I cant use this. it will crash.
	//pSwapChain->Present(1, 0); // Present with vsync
}`

**Comment by ocornut** [comment]
Sorry but #1586
