### ISSUE TITLE
Docking issue

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#2246]
Hi
i just was playing with imgui docking and after docking a lots of windows with each other (i forgot the final layout) , the next time i execute imgui example the dockspace doesn't work anymore,  until i remove the file imgui.ini  .

![imgui](https://user-images.githubusercontent.com/10813427/50300653-5ed9bc00-0485-11e9-805c-7d47e9640b86.gif)

**here is the ini file** :
`
[Window][DockSpace Demo]
Pos=0,0
Size=1264,762
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Hello, world!]
Pos=531,391
Size=346,212
Collapsed=0

[Window][ImGui Demo]
Pos=458,239
Size=318,404
Collapsed=0

[Window][Style Editor]
Pos=1225,20
Size=455,669
Collapsed=0
DockId=0x00000003,0

[Window][Example: Console]
Pos=0,697
Size=1223,291
Collapsed=0
DockId=0x00000006,0

[Window][Example: Custom rendering]
Pos=496,20
Size=727,675
Collapsed=0
DockId=0x00000001,0

[Docking][Data]
DockSpace     ID=0xFA06BC56 Pos=0,22 Size=1264,740 Split=X CentralNode=1 SelectedTab=0x080FC883
  DockNode    ID=0x00000002 Parent=0xFA06BC56 SizeRef=1223,742 Split=Y SelectedTab=0x080FC883
    DockNode  ID=0x00000001 Parent=0x00000002 SizeRef=1145,675 SelectedTab=0x080FC883
    DockNode  ID=0x00000006 Parent=0x00000002 SizeRef=1145,291 SelectedTab=0x46B5E99C
  DockNode    ID=0x00000003 Parent=0xFA06BC56 SizeRef=455,742 SelectedTab=0xE3E9716C
`

**Comment by ocornut** [comment]
I can confirm there is a bug in this situation.
