### ISSUE TITLE
Main window question 

### ISSUE THREAD

**Issue by xumepoc** [ocornut/imgui#2247]
Is there a way to have the same title bar from imgui the main window. I want to have the same "look and feel" for the main window as the rest of the windows from imgui.
It would be great to have the possibility to have a main window from imgui, in which optionally you can draw a QWidget or QOpenDLWidget or anything you like (not only 3D, but also 2D).

**Comment by ocornut** [comment]
Sorry your message is too ambiguous/vague to be answered.

If you want to use QT make a QT application, you can easily render imgui inside an OpenGL view of QT.

**Comment by sgf** [comment]
i think @ocornut is talk about want to let the Main-Window（Platform-Window） Style  looks like the Imgui sub-window style
