### ISSUE TITLE
sliders affect each other

### ISSUE THREAD

**Issue by yuchenz27** [ocornut/imgui#2249]
In my code I have three float sliders:
```
ImGui::SliderFloat("", &directionalLightPosition.x, -100.0f, 100.0f, "x = %.1f");
ImGui::SliderFloat("", &directionalLightPosition.y, -100.0f, 100.0f, "y = %.1f");
ImGui::SliderFloat("", &directionalLightPosition.z, -100.0f, 100.0f, "z = %.1f");
```

Basically, I want to change these three values separately. However, in my program, when I changed any one of these three sliders, the other two changed acoordingly, Namely, after I changed one of those sliders, all three sliders became to have the same value!

It seems that this problem always happens when you have several consecutive sliders with the same type.

Is there a way to solve this problem?

**Comment by ocornut** [comment]
Your sliders are sharing the same ID. Please read the FAQ the answer is in it.

**Comment by yuchenz27** [comment]
Solved! Thanks for the quick reply
