### ISSUE TITLE
DrawList and BeginChild problem

### ISSUE THREAD

**Issue by DonHomka** [ocornut/imgui#2250]
![image](https://user-images.githubusercontent.com/31521265/50400653-6eb11300-0799-11e9-92b4-3e12c023224c.png)
Hey. I use non-standard elements in BeginChild, and these elements are outside the boundaries of the scroll box.
Lua:
`		imgui.BeginChild("##scroll", imgui.ImVec2(iScreenWidth - (tMenuBarSet.hide and tMenuBarSet.mwidth or tMenuBarSet.width) * 2, iScreenHeight - 240), true)
		local yoff, mheight = 160, 30
		local p = imgui.GetCursorScreenPos()
		for i = 1, #tHotKeys do
			local v = tHotKeys[i]
			imgui.Dummy(imgui.ImVec2(0, mheight))
			DrawList:AddRectFilled(imgui.ImVec2(p.x, p.y + (mheight * (i - 1)) + 2), imgui.ImVec2(iScreenWidth - p.x, p.y + (mheight * (i - 1) + mheight)), imgui.ColorConvertFloat4ToU32(imgui.ImVec4(0.0, 0.0, 0.0, i % 2 ~= 0 and 0.5 or 0.7)))
		end
		imgui.EndChild()`

**Comment by ocornut** [comment]
Not providing requested informations.
