### ISSUE TITLE
Two InputText same buffer.

### ISSUE THREAD

**Issue by Belsnickle** [ocornut/imgui#2252]
```
#define MAX_OBJECTS 2;
Object objects[MAX_OBJECTS];
enum Mode
{
	Mode_All,
};
static int mode = 0;
if (ImGui::RadioButton("All", mode == Mode_All)) { mode = Mode_All; } 

if (mode == Mode_All)
{
	int i;
	for (i = 0; i < MAX_OBJECTS; i++)
	{
		static char str[50];
		ImGui::InputText(objects[i]->getName(), str, IM_ARRAYSIZE(str));
	}
}
```
Changing one input text field changes all input text fields.  I thought this was issue https://github.com/ocornut/imgui/issues/1070

The object names are different and so should the labels.  I also did Push ID with the unique object name and still wrote to every input text field.  What am I missing?

Happy Holidays

**Comment by DoctorGester** [comment]
Well you said it yourself, "same buffer". Your char array is static so it's a global.

**Comment by Belsnickle** [comment]
Thanks!

**Comment by Belsnickle** [comment]
I gave my variable 'str' a value like in imgui_demo.cpp and my edits are now limited to the box I selected for editing.

The text is not permanent like in the demo however.  When I deselect the InputText field my data reverts back to what I created 'str' as.

**Comment by ocornut** [comment]
This is mostly likely a side-effect of you misunderstanding C++ and the data flow.
Please re-open when you have **standalone, minimal, verifiable reproduction** that we can paste in. When making one you would probably understand your issue.

**Comment by Belsnickle** [comment]
You were right it was a misunderstanding of C++.  I moved my char str variable to my object class and it works as intended.
