### ISSUE TITLE
Saving the InvisibleButton Canvas as a PNG or JPEG, using CImg or similar libaries

### ISSUE THREAD

**Issue by Chubek** [ocornut/imgui#2256]
**Summary**: Rendering InvisibleButton to file. 

**Version/Branch of Dear ImGui:**

Version: Latest
Branch: Master 

**Back-end/Renderer/Compiler/OS** 

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: GLFW
Operating System: Windows
**My Issue/Question:** I emailed this to ocornut but I imagine it would be an invasion of his privacy to ask him in email, so I apologize and ask here. Plus, this way, other people can use this as well.

See, I wish to create a Mograph package. It has three sections, Creation, Composition, and Shaders. In all sections, I will be doing extensive operations on an InvisibleButton which I'll use as a canvas. However, this button needs to be saved as a PNG file. I have CImg for that, but just how is it possible to render an Invisible Button to a file?

You see, I don't want to use libraries such as Skia. Imgui is a wonderful, feature-rich library and it has everything I want. Please put me in the right direction. Thank you.

**Edit:** Should I create a framebuffer object with a texture attachment, and render your imgui data to it? I know how to do the first two, I just don't know how to render the imgui data to my framebuffer. I'd be happy with a nudge in the right direction. Thank you.

**Comment by DoctorGester** [comment]
> Should I create a framebuffer object with a texture attachment, and render your imgui data to it? I know how to do the first two, I just don't know how to render the imgui data to my framebuffer. I'd be happy with a nudge in the right direction. Thank you.

Yes. You already have code in your render backend which draws imgui data to your screen. You just need to set the correct render target and call your render function again. You'll still need some sort of image encoding library for png. I'm not sure if stb_image can encode, lodepng certainly can and it's not a terribly large dependency (it's fairly big, but it's 1 file and it's not skia or libpng large).

**Comment by ocornut** [comment]
Closing this as answered above.
You can freely call the existing `_RenderDrawData()` Everything else is out fo the scope of dear imgui itself.
