### ISSUE TITLE
Example code references undefined cmd_list / missing instantiation

### ISSUE THREAD

**Issue by tim-rex** [ocornut/imgui#2258]
Just a minor issue, _cmd_list_ is not defined in the example pseudocode _"HOW A SIMPLE RENDERING FUNCTION MAY LOOK LIKE"_...

https://github.com/ocornut/imgui/blob/d8451352737c08a5ee22b0d805415cb4a8327e5b/imgui.cpp#L262

Requires the following on the preceding line:

`const ImDrawList *cmd_list = draw_data->CmdLists[n];
`

**Comment by ocornut** [comment]
Thank you Tim, fixed now!
