### ISSUE TITLE
Support WM_XBUTTONUP WM_XBUTTONDOWN

### ISSUE THREAD

**Issue by frederich** [ocornut/imgui#2264]
ImGui_ImplWin32_WndProcHandler doesn't handle WM_XBUTTONUP WM_XBUTTONDOWN, therefore io.MouseDown[3] and [4] doesn't work.

Version: newest
Branch: master

**Comment by ocornut** [comment]
Hello Frederich,
Happy to see a pull request for it.

**Comment by frederich** [comment]
case WM_XBUTTONDOWN: case WM_XBUTTONDBLCLK:
    {
        int button = 1;
        if (msg == WM_XBUTTONDOWN || msg == WM_XBUTTONDBLCLK) button = GET_XBUTTON_WPARAM(wParam);

        if (!ImGui::IsAnyMouseDown() && ::GetCapture() == NULL)
            ::SetCapture(hwnd);
        button += 2;
        io.MouseDown[button] = true;
        return 0;
    }
    case WM_XBUTTONUP:
    {
        int button = 1;
        if (msg == WM_XBUTTONDOWN || msg == WM_XBUTTONDBLCLK) button = GET_XBUTTON_WPARAM(wParam);

        button += 2;
        io.MouseDown[button] = false;
        if (!ImGui::IsAnyMouseDown() && ::GetCapture() == hwnd)
            ::ReleaseCapture();
        return 0;
    }

**Comment by ocornut** [comment]
Added the proper code to handle XBUTTON 4 and 5 now.
