### ISSUE TITLE
Tooltip get out of rendering area

### ISSUE THREAD

**Issue by CedricGuillemet** [ocornut/imgui#227]
Tooltip position is not clamped so it gets renderer when mouse cursor is close to the border

![](http://i.imgur.com/uButOeP.png)

**Comment by ocornut** [comment]
Which version do you have? This should have been committed in trunk on May 1st.

**Comment by CedricGuillemet** [comment]
v1.39 WIP

**Comment by ocornut** [comment]
Latest ? (as in, what's currently in the trunk?), or you got it before May 1st ?
Tooltips should be clamped within the display area (0.0f->io.DisplaySize), or (DisplayVisibleMin->DisplayVisibleMax) if the later is set.

**Comment by ocornut** [comment]
Could you confirm there is a bug with latest or provide a repro? If you have a version after May 1st it should works as far as a I know. 1.39 WIP is a general tag that started from April 21 and still running until I finalize 1.39.

**Comment by CedricGuillemet** [comment]
Argh!
I just updated and it crashes in ImVector::reserve . No
callstack...investigating...

2015-05-24 18:40 GMT+02:00 omar <notifications@github.com>:

> Could you confirm there is a bug with latest or provide a repro? If you
> have a version after May 1st it should works as far as a I know. 1.39 WIP
> is a general tag that started from April 21 and still running until I
> finalize 1.39.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocornut/imgui/issues/227#issuecomment-105034275>.
>



-- 
Cedric Guillemet
http://www.skaven.fr http://twitter.com/skaven_

**Comment by ocornut** [comment]
Oops, thanks!

**Comment by CedricGuillemet** [comment]
Must be on my side. Anyway the tooltip is fixed! Thanks a lot :)

2015-05-24 23:04 GMT+02:00 omar <notifications@github.com>:

> Oops, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocornut/imgui/issues/227#issuecomment-105062000>.
>



-- 
Cedric Guillemet
http://www.skaven.fr http://twitter.com/skaven_

**Comment by ocornut** [comment]
OK, closing this bug for now. Let me know if you find any problem!
