### ISSUE TITLE
Make layout window background transparent and can be click through

### ISSUE THREAD

**Issue by Grupie** [ocornut/imgui#2271]
Sorry for noob question because I see many people can do this. But it is not success with me.

I want to draw menu in a game screen like this image
![image](https://user-images.githubusercontent.com/46587143/51013830-41d16e00-1597-11e9-95b1-30095a8a453b.png)

So, could you please help me? Thank you.

**Comment by ocornut** [comment]
Cannot help you, sorry. Your question is too unclear and not following the Issue template.
