### ISSUE TITLE
Document window blinks on docking to the parent

### ISSUE THREAD

**Issue by Mg32** [ocornut/imgui#2286]
**Be careful about the screenshot below includes flashing.**

**Version/Branch of Dear ImGui:**

Version: 1.68 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS** 

Back-ends: GL3W + GLFW + OpenGL3
Compiler: g++(MSYS2)
Operating System: Windows 10 x64

**My Issue/Question:** 

I found a strange behavior of Example->Documents in the demo.
When the child document window is docked to the parent in "DockSpace+Window" mode, the window blinks per frame and becomes not able to operate.

**Screenshots/Video** 

![imgui-flicker](https://user-images.githubusercontent.com/2096686/51248214-c9254400-19d2-11e9-883b-95b85401d106.gif)

**Comment by ocornut** [comment]
I have pushed the more reasonable fix for this, which is submit the documents windows even if the parent "Example: Document" window is not visible. See commit: 2f9bae140b8b770804053668d1a0814ce5c4fb11

Thanks for reporting this!
