### ISSUE TITLE
AddCircleFilled draws an irregular polygon instead of a regular one

### ISSUE THREAD

**Issue by baktery** [ocornut/imgui#2287]
**Version/Branch of Dear ImGui:**

Version: 1.6WIP
Branch: https://github.com/google/filament/tree/master/third_party/imgui

**My Issue/Question:** 

Drawing a circle with ImDrawList::AddCircleFilled() I noticed that the size of all the segments were not the same.

For example, you can try to draw an hexagon (6 segments) and you will see an irregular polygon instead of a regular hexagon.

**Standalone, minimal, complete and verifiable example:**

This is the original function:

```
void ImDrawList::AddCircleFilled(const ImVec2& centre, float radius, ImU32 col, int num_segments)
{
    if ((col & IM_COL32_A_MASK) == 0)
        return;

	const float a_max = IM_PI*2.0f * ((float)num_segments - 1.0f) / (float)num_segments;
	PathArcTo(centre, radius, 0.0f, a_max, num_segments);
    PathFillConvex(col);
}
```

PathActTo() is not called with the proper number of segments. This a fixed version:

```
void ImDrawList::AddCircleFilled(const ImVec2& centre, float radius, ImU32 col, int num_segments)
{
    if ((col & IM_COL32_A_MASK) == 0)
        return;

	const float a_max = IM_PI*2.0f * ((float)num_segments - 1.0f) / (float)num_segments;
	PathArcTo(centre, radius, 0.0f, a_max, num_segments-1);
    PathFillConvex(col);
}
```

It seems like AddCicle() function also has the same issue.

**Comment by ocornut** [comment]
Thank you @baktery, I verified this and pushed a fix.
Even though `PathArcTo()` is correct as it is, it can be misleading when used for a full closed shape. so I added a few comments around those functions and the circle function.

Also added an hexagon in the demo:
![image](https://user-images.githubusercontent.com/8225057/51264554-14315e00-19b7-11e9-832a-297e49fe2899.png)
