### ISSUE TITLE
Direct3D D3DRS_FOGENABLE enabled affects ImGui UI's

### ISSUE THREAD

**Issue by giladreich** [ocornut/imgui#2288]
**Version/Branch of Dear ImGui:**

Version: 1.67
Branch: master

**Back-end/Renderer/Compiler/OS** 

Backends: Direct3D 9
Compiler: msvc141 VS17
Operating System: Win10

**Issue:** 

Something tiny, but I though I should add it here.
When enabling fog to the direct3d device, it will affect the ImGui UI's or render on top of them.
Code example:
```cpp
s_lpD3DDev->SetRenderState(D3DRS_FOGENABLE, TRUE);

ImGui_ImplDX9_NewFrame();
ImGui_ImplWin32_NewFrame();
ImGui::NewFrame();

ImGui::Begin("Hello, world!"); 
ImGui::End();

ImGui::EndFrame();
... and so on
```

**Screenshots/Video** 

![imgui_fog](https://user-images.githubusercontent.com/17655494/51267668-8f4a4280-19be-11e9-89e6-68591566512c.png)

**Comment by giladreich** [comment]
Sample code to solve this:
```cpp
	DWORD dwFogEnabled;
	m_pEng->GetDevice()->GetRenderState(D3DRS_FOGENABLE, &dwFogEnabled);
	m_pEng->GetDevice()->SetRenderState(D3DRS_FOGENABLE, FALSE);

	ImGui_ImplDX9_NewFrame();
	ImGui_ImplWin32_NewFrame();
	ImGui::NewFrame();

	ImGui::Begin("Hello, world!"); 
        ImGui::End();

	ImGui::EndFrame();
	ImGui::Render();
	ImGui_ImplDX9_RenderDrawData(ImGui::GetDrawData());
	m_pEng->GetDevice()->SetRenderState(D3DRS_FOGENABLE, dwFogEnabled);
```

That way we always making sure fog is disabled before doing ImGui UI's rendering.

**Comment by ocornut** [comment]
Hello @giladreich,

Could you submit the appropriate pull request to fix ImGui_ImplDX9_RenderDrawData() ? (incl Changelog at the top of imgui_impl_dx9.cpp and docs/Changelog.txt).

Thank you!

**Comment by giladreich** [comment]
Sure do! will into this now and post a pull request.
I'll also double check Direct3D 10 and 11 to see if it has the same problem.
