### ISSUE TITLE
Qt Widget for ImGui and Direct3D / DirectX

### ISSUE THREAD

**Issue by giladreich** [ocornut/imgui#2293]
Hey everyone,

I made an opensource project as thanks back to Dear ImGui to support the people who will be using Qt and DirectX.

Originally Qt not supporting DirectX, since their painting engine based on OpenGL, I therefore created these widgets to simplify the usage of Direct3D in Qt.

I hope some of you will find it useful for your own projects and interesting as much as I did :)

![qt_and_imgui](https://user-images.githubusercontent.com/17655494/51347377-35ba4480-1aa0-11e9-928c-aa92c9655351.gif)

Link:
https://github.com/giladreich/QtDirect3D

**Comment by ocornut** [comment]
Added to Wiki in https://github.com/ocornut/imgui/wiki/Bindings and Readme, thank you.

**Comment by ocornut** [comment]
Closing this (link avail in readme and wiki).

**Comment by tatolevicz** [comment]
Hey @giladreich I'm facing the same issue as you in the begging .. the Imgui isn't responsive when promoting it inside a Qt openglwidget.. but I'm on a macOS and the backend is not the same I think. Can give a clue if the solution for you works on macOS too or I'm doing something wrong!?
