### ISSUE TITLE
Followup: "g was nullptr"

### ISSUE THREAD

**Issue by N00TN00T** [ocornut/imgui#2295]
This is a followup for the closed [issue](https://github.com/ocornut/imgui/issues/2292#event-2081274174). I posted 3 days ago where I was asked to:

> please build a minimum, complete, verifiable repro as instructed by the Issue template. You can reopen this issue when you have the repro.

I have now done this, and am getting the same exact result.

Here is the code used:

Application.h (in project **Core**):

    #pragma once
    #include <GL\glew.h>
    #include <GLFW/glfw3.h>
    #include <imgui.h>
    #include <imgui_impl_opengl3.h>
    #include <imgui_impl_glfw.h>

    #ifdef EXPORT_DLL
        #define API __declspec(dllexport)
    #else
        #define API __declspec(dllimport)
    #endif

    class API Application {
    private:
	    GLFWwindow *m_window;
    public:

	    void Run();

	    virtual void Update() = 0;
    };

Application.cpp (in project **Core**):

    #include "Application.h"
    #include <iostream>

    void Application::Run() {

	    if (!glfwInit())
		    std::cout << "err glfw init\n";

	    m_window = glfwCreateWindow(1280, 720, "imgui test", nullptr, nullptr);
	    glfwMakeContextCurrent(m_window);
	    glfwSetWindowUserPointer(m_window, this);

	    if (glewInit() != 0)
		    std::cout << "err glew init\n";

	    ImGui::CreateContext();
	    ImGui::StyleColorsDark();
	    ImGui_ImplOpenGL3_Init("#version 410");
	    ImGui_ImplGlfw_InitForOpenGL(m_window, true);

	    auto& _io = ImGui::GetIO();

	    _io.DisplaySize = ImVec2(1280, 720);
	    _io.DeltaTime = 1.f / 60.f;

	    glClearColor(.6f, .6f, 1.f, 1.f);

	    while (true) {

		    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

		    ImGui_ImplOpenGL3_NewFrame();
		    ImGui_ImplGlfw_NewFrame();
		    ImGui::NewFrame();

		    //ImGui::ShowDemoWindow();
		    Update();

		    ImGui::Render();
		    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

		    glfwPollEvents();
		    glfwSwapBuffers(m_window);
	    }
    }

entry.h (in project **Sandbox**):

    #pragma once

    int main();

entry.cpp (in project **Sandbox**):

    #include "entry.h"
    #include "..\Core\Application.h"

    class Sandbox
	: public Application {
	
	    virtual void Update() override {
		    ImGui::ShowDemoWindow();
	   }
    };

    int main() {

	    auto _app = new Sandbox();
	    _app->Run();
	    delete _app;

	    return 0;
    }

The way I linked ImGui into my projects was by creating a vs solution with all the needed ImGui files and built it into a .lib file which is then used by **Core** and **Sandbox**.
**Sandbox** is linked with **Core** with the built-in vs way of adding **Core** as a reference in the references of **Sandbox**.

Here is the zip file with the projects, in case you want to see how I linked everything: https://www.mediafire.com/file/wcxqwk1b47d9ww3/ImGuiTest.zip/file

I may have misunderstood static/dynamic linking, so if the case is that this is in fact dynamic linking then how do I statically link ImGui into my visual studio projects?

**Comment by ocornut** [comment]
Moved back to #2292.
