### ISSUE TITLE
Can't collapse windows anymore.

### ISSUE THREAD

**Issue by ninnghazad** [ocornut/imgui#230]
Used to work, everything else seems to work, dragging, resizing, using elements, hiding-bool, typing ... - but no more triangle- or double-click to collapse windows. I can't really recall what i might have changed to cause this, fresh imgui didn't help. out of ideas seeing everything else about imgui seems to work as it should. if the X button works (and all elements), why wouldn't the triangle button... ? 

edit: one thing i noticed is that i can drag when holding the triangle, can't do that with anything else clickable but the window's bg.

**Comment by ocornut** [comment]
Hmm. it works in the trunk. Is your double-click still working? You can test it by double-clicking an InputText() to select the text, or double-click a DragFloat() to text edit it. Does double-click on the resize grip at the lower-right of a window does something? 

Double-click is time based and rely on the DeltaTime input passed between each call to NewFrame(). If you let the default DeltaTime set to 1.0f/60.0f (60 hz) but are running NewFrame() at a much faster rate then time will pass faster from ImGui point of view and you'll have difficulty double-clicking fast enough.

The triangle itself is not interactive, which is already something inconsistent in the interface that I meant to fix. The only way to collapse at the moment is to double-click.

**Comment by ninnghazad** [comment]
Ah ok, must have mixed that up in my memory with the triangle being clickable. And my doubleclicks did not work - i changed scale of time at some point and thusly set a ms value instead of a s value to io.DeltaTime. a simple /1000.0f and it works again. thanks!

**Comment by ocornut** [comment]
Good to hear. I'll probably change the triangle to act on a simple click eventually.

**Comment by Extrawurst** [comment]
is there an issue for that already ?

**Comment by ocornut** [comment]
Not on github but its in my personal todo list (i let things naturally appear on github when people ask for them)
