### ISSUE TITLE
imstb_rectpack.h wrong #endif location

### ISSUE THREAD

**Issue by frederich** [ocornut/imgui#2302]
Compile error while using imgui_freetype.h/cpp.

`
a:\aalyz\src\imstb_rectpack.h(218): error C2365: 'STBRP__INIT_skyline': redefinition; previous definition was 'enumerator'
a:\aalyz\src\imstb_rectpack.h(217): note: see declaration of 'STBRP__INIT_skyline'
a:\aalyz\src\imstb_rectpack.h(221): error C2084: function 'void stbrp_setup_heuristic(stbrp_context *,int)' already has a body
a:\aalyz\src\imstb_rectpack.h(220): note: see previous definition of 'stbrp_setup_heuristic'
a:\aalyz\src\imstb_rectpack.h(233): error C2084: function 'void stbrp_setup_allow_out_of_mem(stbrp_context *,int)' already has a body
a:\aalyz\src\imstb_rectpack.h(232): note: see previous definition of 'stbrp_setup_allow_out_of_mem'
a:\aalyz\src\imstb_rectpack.h(253): error C2084: function 'void stbrp_init_target(stbrp_context *,int,int,stbrp_node *,int)' already has a body
a:\aalyz\src\imstb_rectpack.h(252): note: see previous definition of 'stbrp_init_target'
a:\aalyz\src\imstb_rectpack.h(286): error C2084: function 'int stbrp__skyline_find_min_y(stbrp_context *,stbrp_node *,int,int,int *)' already has a body
a:\aalyz\src\imstb_rectpack.h(285): note: see previous definition of 'stbrp__skyline_find_min_y'
a:\aalyz\src\imstb_rectpack.h(339): error C2371: 'stbrp__findresult': redefinition; different basic types
a:\aalyz\src\imstb_rectpack.h(339): note: see declaration of 'stbrp__findresult'
a:\aalyz\src\imstb_rectpack.h(342): error C2084: function 'stbrp__findresult stbrp__skyline_find_best_pos(stbrp_context *,int,int)' already has a body
a:\aalyz\src\imstb_rectpack.h(341): note: see previous definition of 'stbrp__skyline_find_best_pos'
a:\aalyz\src\imstb_rectpack.h(356): error C2568: '=': unable to resolve function overload
a:\aalyz\src\imstb_rectpack.h(356): note: could be 'int stbrp__skyline_find_min_y(stbrp_context *,stbrp_node *,int,int,int *)'
a:\aalyz\src\imstb_rectpack.h(414): error C2568: '=': unable to resolve function overload
a:\aalyz\src\imstb_rectpack.h(414): note: could be 'int stbrp__skyline_find_min_y(stbrp_context *,stbrp_node *,int,int,int *)'
a:\aalyz\src\imstb_rectpack.h(437): error C2084: function 'stbrp__findresult stbrp__skyline_pack_rectangle(stbrp_context *,int,int)' already has a body
a:\aalyz\src\imstb_rectpack.h(436): note: see previous definition of 'stbrp__skyline_pack_rectangle'
a:\aalyz\src\imstb_rectpack.h(439): error C2440: 'initializing': cannot convert from 'stbrp__findresult (__cdecl *)(stbrp_context *,int,int)' to 'stbrp__findresult'
a:\aalyz\src\imstb_rectpack.h(439): note: No constructor could take the source type, or constructor overload resolution was ambiguous
a:\aalyz\src\imstb_rectpack.h(516): error C2084: function 'int rect_height_compare(const void *,const void *)' already has a body
a:\aalyz\src\imstb_rectpack.h(515): note: see previous definition of 'rect_height_compare'
a:\aalyz\src\imstb_rectpack.h(527): error C2084: function 'int rect_original_order(const void *,const void *)' already has a body
a:\aalyz\src\imstb_rectpack.h(526): note: see previous definition of 'rect_original_order'
a:\aalyz\src\imstb_rectpack.h(540): error C2084: function 'int stbrp_pack_rects(stbrp_context *,stbrp_rect *,int)' already has a body
a:\aalyz\src\imstb_rectpack.h(539): note: see previous definition of 'stbrp_pack_rects'
a:\aalyz\src\imstb_rectpack.h(558): error C2440: 'initializing': cannot convert from 'stbrp__findresult (__cdecl *)(stbrp_context *,int,int)' to 'stbrp__findresult'
a:\aalyz\src\imstb_rectpack.h(558): note: No constructor could take the source type, or constructor overload resolution was ambiguous
`

Solution:
The #endif https://github.com/ocornut/imgui/blob/54ba8a643ed28e2bd930b64bad9024407296d227/imstb_rectpack.h#L189 is on the wrong location, correct is line 582.

**Comment by frederich** [comment]
I do an unity build:

foo.cpp
#include <windows.h>
#include <stdio.h>
#include "target.cpp"
#include "mprintf.cpp"
#include "assert.cpp"
#include "imgui.cpp"
#include "imgui_draw.cpp"
#include "imgui_widgets.cpp"
#include "imgui_impl_dx11.cpp"
#include "imgui_impl_win32.cpp"
#include "imgui_freetype.cpp"
#include "main.cpp"


cl.exe foo.cpp

**Comment by ocornut** [comment]
This is fixed now.

Please always describe the root problem in context rather than what you think the solution (your suggested solution is not correct and didn't provide enough information to understand the problem). Thanks!
