### ISSUE TITLE
Imgui/ROS integration (Segmentation fault)

### ISSUE THREAD

**Issue by Brunovieira8** [ocornut/imgui#2315]
Version: Latest
Branch: master

Back-ends: ???
Compiler: cmake 
Operating System: Ubuntu 16.04

Dear all,

I'm trying to create a simple imgui-based GUI to be able to change some ROS topics in order to be able to customize "on-the-fly" a Gazebo simulation. When trying to create all the ROS environment to include this imgui integration, I'm dealing with a **Segmentation fault** issue, and it is only related to Imgui's approach since it happens on my loop dedicated to it's inclusion on my application.The cmake compilation presents no errors, as well.

The code i'm having issues with is the following: (based on your Readme's examples)
```

bool my_tool_active = true;
ImGui::Begin("My First Tool", &my_tool_active, ImGuiWindowFlags_MenuBar);
if (ImGui::BeginMenuBar())
{
    if (ImGui::BeginMenu("File"))
    {
        if (ImGui::MenuItem("Open..", "Ctrl+O")) { /* Do stuff */ }
        if (ImGui::MenuItem("Save", "Ctrl+S"))   { /* Do stuff */ }
        if (ImGui::MenuItem("Close", "Ctrl+W"))  { my_tool_active = false; }
        ImGui::EndMenu();
    }
    ImGui::EndMenuBar();
}
float my_color[4];

// Edit a color (stored as ~4 floats)
ImGui::ColorEdit4("Color", my_color);

// Plot some values
const float my_values[] = { 0.2f, 0.1f, 1.0f, 0.5f, 0.9f, 2.2f };
ImGui::PlotLines("Frame Times", my_values, IM_ARRAYSIZE(my_values));

// Display contents in a scrolling region
ImGui::TextColored(ImVec4(1,1,0,1), "Important Stuff");
ImGui::BeginChild("Scrolling");
for (int n = 0; n < 50; n++)
    ImGui::Text("%04d: Some text", n);
ImGui::EndChild();
ImGui::End();

```
as I specified previously this code runs in a "endless" loop, which i'm sure it's working `properly.`

**Comment by ocornut** [comment]
I will also close this issue as the Issue Template specifically request this type of issue shouldn’t be reported here. Please post on the Discourse forum, only after you can provide the requested information and clarify about which backend you are using.

**Comment by lucasw** [comment]
@Brunovieira8 you may be interested in looking at https://github.com/lucasw/imgui_ros/tree/master/imgui_ros, though I've since moved exclusively to ros2 in the `crystal` branch there.

**Comment by Brunovieira8** [comment]
Thank you both for the answers, sorry for not fulfilling the provided template.

@lucasw Just found out your project, great job! since i'm only needing a small and simple implementation, finishing my current work should be the best approach. I'm having issues on getting SDL includes under CMakeLists done... any help you can provide on this? Can we discuss this on direct messaging? Thank you
