### ISSUE TITLE
Docking demo renders outside SDL window on Linux with Vulkan

### ISSUE THREAD

**Issue by MattGuerrette** [ocornut/imgui#2316]
Version: 1.67
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_vulkan.cpp 
Compiler: gcc
Operating System: Fedora 29

**My Issue/Question:**

Imgui docking demo executable renders outside of the SDL window. I know, this sounds ridiculous, but here it is......

![woahnelly](https://user-images.githubusercontent.com/6388953/51879327-fb269680-2340-11e9-816e-49f0c8bb789b.jpg)

**Comment by MattGuerrette** [comment]
Yes, I actually should have tested the OpenGL build as well... Anyway, there do seem to be performance quirks with the Vulkan demo but that most likely the vulkan implementation. As the docking is still WIP I will close this.

**Comment by robodrunk** [comment]
I've noticed strange fps fluctuations on that build, too.  Like staying about 30 and eventually getting back to 60.

**Comment by ocornut** [comment]
@MattGuerrette Rendering "outside" the main window is the entire purpose of the multi-viewport feature (enabled via `io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable'). 

> Anyway, there do seem to be performance quirks with the Vulkan demo

If you have issue with it see #1542 and #2117 for Linux/Mac specific issues, reports are welcome but please be specific.
