### ISSUE TITLE
ExampleAppLog misses first printed line.

### ISSUE THREAD

**Issue by bluescan** [ocornut/imgui#2318]
The first line of text submitted to the static instance of ExampleAppLog does not display.
IMGUI 1.67
Repo: Run the demo. Select Example -> Log. Hit "Add 5 Entries". You will only see 4 lines added the first time out.
Cause: The ExampleAppLog default constructor does not push a 0 into the LineOffsets.
Fix: 
Add
	ExampleAppLog() : ScrollToBottom(false)
	{
		Clear();
	}

to the struct. It's also worth noting that struct ExampleAppLog is currently relying on zero-initialization of bool ScrollToBottom (it is used with the static keyword in the demo code). If you were to put ExampleAppLog on the stack, the value of ScrollToBottom will not be initialized to any particular value at all.

**Comment by ocornut** [comment]
Fixed both, thank you Tristan!
(Not sure what happened, this probably had a constructor at some point that got removed?)
