### ISSUE TITLE
How do you implement this interface?

### ISSUE THREAD

**Issue by swordwest** [ocornut/imgui#2319]
![Uploading IMG_20190106_171811.jpg…]()
How do you implement this interface?Shaped Windows run along the screen and can be automatically scaled.

**Comment by swordwest** [comment]
![img_20190106_171811](https://user-images.githubusercontent.com/10961500/51897085-e00f6180-23e8-11e9-8b6e-1e17e3ba3437.jpg)

**Comment by swordwest** [comment]
Can someone help me?

**Comment by ocornut** [comment]
You may use the low level api e.g. ImDrawList and `imgui_internal.h` API to create your own widgets.

**Comment by swordwest** [comment]
Is there a similar example?

@ocornut

**Comment by ocornut** [comment]
They are plenty of custom widgets example you browse the Wiki.
You can't easily create a _window_ that has a non-rectangular hovering region.

I am sorry you are not getting more complete answers, but this is a wide topic and it looks like you haven't done much research on it yet. People are not often available to improvise an easy step by step guide. I suggest you spend some time looking at imgui_widgets.cpp source code and other widgets on the wiki.

**Comment by swordwest** [comment]
Very feel you, I will study carefully.Please give me more advice in the future.
