### ISSUE TITLE
Cancelling edit doesn't reset the input buffer

### ISSUE THREAD

**Issue by relick** [ocornut/imgui#2321]
**Version/Branch of Dear ImGui:**

Version: 1.67 and master
Branch: master

**Back-end/Renderer/Compiler/OS**

*Tested using:*
Back-ends: imgui-SFML
Compiler: mingw-w64 gcc 8.2
Operating System: Windows

**My Issue/Question:**

When typing in an `InputText` or `InputTextMultiline` and cancelling the edit (typically through pressing escape), whilst the text box does lose focus as expected, the input text buffer doesn't revert to its original contents. Reverting used to be the behaviour in previous versions but now seems to be broken on both 1.67 and master. Looking at the code it seems this may have just been an oversight when InputText resize callbacks were added.
I was able to fix it locally by changing this line in InputTextEx:
```c
// If the underlying buffer resize was denied or not carried to the next frame, apply_new_text_length+1 may be >= buf_size.
ImStrncpy(buf, edit_state.TempBuffer.Data, ImMin(apply_new_text_length + 1, buf_size));
```
to
```c
ImStrncpy(buf, apply_new_text, ImMin(apply_new_text_length + 1, buf_size));
```

If you'd like me to submit a PR for this fix let me know, but I'll wait for now in case there's an aspect to fixing this that I have missed.

**Comment by ocornut** [comment]
Thank you for finding this @relick.

It somehow escaped naive detection because applying the zero-terminator means that _text addition_ would appear to be successfully cancelled. 

"Hello" -> "Hello world" (Escape) -> "Hello" (appears to work!)
But
"Hello world" -> "Hello w" (Escape) -> "Hello world" (fail)

Broken in
24ff2598160f4e4ee373b668872f717373828fae

Fixed now.

However I noticed there is _another_ bug where if you enable Keyboard Navigation, in this situation the Nav code will consume the ESC event earlier and not leave a chance for `InputText()` to cancel the edit. Will fix this later today/

**Comment by ocornut** [comment]
(
Bonus:

I also added a basic test for test in my (work in progress) testing framework #435
![image](https://user-images.githubusercontent.com/8225057/51980664-04bf1400-2491-11e9-9f5b-62a6ed771f01.png)
```
// Insert
strcpy(buf, "Hello");
ctx->ItemClick("InputText");
ctx->KeyCharsInputAppend("World123");
IM_CHECK(strcmp(buf, "HelloWorld123") == 0);

// Delete
ctx->ItemClick("InputText");
ctx->KeyPressMap(ImGuiKey_End);
ctx->KeyPressMap(ImGuiKey_Backspace, 3);
ctx->KeyPressMap(ImGuiKey_Enter);
IM_CHECK(strcmp(buf, "HelloWorld") == 0);

// Insert, Cancel
ctx->ItemClick("InputText");
ctx->KeyPressMap(ImGuiKey_End);
ctx->KeyChars("XXXXX");
ctx->KeyPressMap(ImGuiKey_Escape);
IM_CHECK(strcmp(buf, "HelloWorld") == 0);

// Delete, Cancel
ctx->ItemClick("InputText");
ctx->KeyPressMap(ImGuiKey_End);
ctx->KeyPressMap(ImGuiKey_Backspace, 5);
ctx->KeyPressMap(ImGuiKey_Escape);
IM_CHECK(strcmp(buf, "HelloWorld") == 0);
```
)

**Comment by benbrauns** [comment]
> However I noticed there is _another_ bug where if you enable Keyboard Navigation, in this situation the Nav code will consume the ESC event earlier and not leave a chance for `InputText()` to cancel the edit. Will fix this later today/

Is there a way to allow this behavior. I'm trying to prevent the cancel behavior from happening.
