### ISSUE TITLE
Extending ImGuiContext by inheriting from it

### ISSUE THREAD

**Issue by Alzathar** [ocornut/imgui#2322]
**Version/Branch of Dear ImGui:**

Version: v1.67 release

**Back-end/Renderer/Compiler/OS**

Back-ends: GLFW 3.3 + Sokol
Compiler: MSVC 2017
Operating System: Windows 10 64-bit

**My Issue/Question:**

Complex widgets (e.g. `ImGuiTabBar`) need to keep some states between frames. Internally ImGui stores these states inside `ImGuiContext` objects. It would be great if custom complex widgets (e.g. like charts) could profit of this internal storage instead of having to rely on supplementary global variables (like in [imguiex](https://github.com/thedmd/imgui-dev/blob/master/imguiex/imguiex.h) that creates another context and required function to create/destroy/get/set it ).

Everything in ImGui gives the possibility to inherit from the `ImGuiContext` structure. To do it, you have to:
 - define the preprocessor symbol `GImGui` ;
 - create a new external global variable to store the content of the extended context
 - declare the extended context structure inheriting from the structure `ImGuiContext`
 - define function to create/destroy/get/set the extended context

The code should looks like this

```c++

#define GImGui GImGuiExtended // To use custom extended context

extern IMGUI_API ImGuiContextExtended* GImGuiExtended;  // Current implicit ImGui context pointer

#include <imgui_internal.h>

struct ImGuiContextExtended : ImGuiContext {
  explicit ImGuiContextExtended(ImFontAtlas *shared_font_atlas) : ImGuiContext(shared_font_atlas) {};
};

IMGUI_API ImGuiContextExtended* CreateContextExtended(ImFontAtlas *shared_font_atlas = nullptr);
IMGUI_API void DestroyContextExtended(ImGuiContextExtended* ctx = nullptr); // nullptr = destroy current context
IMGUI_API void SetCurrentContextExtended(ImGuiContextExtended* ctx);
```

However, there is one problem withthat solution. Currently, the structure `ImGuiContext` is defined inside the file `imgui_internal.h` and used it few times in inline functions (like at line [1197](https://github.com/ocornut/imgui/blob/master/imgui_internal.h#L1197)). Thus, the compiler returns errors like this one `error C2027: use of undefined type 'ImGuiContextExtended'`.

One solution to fix this compiler error is to move the declaration of the structure ImGuiContext in a dedicated header (e.g. `imgui_context.h`). Another solution should be to define inline functions in the `imgui.cpp` file but this sounds bad for performance reason.

Do you think this modification is feasible?

**Comment by ocornut** [comment]
Hello,

I think you could make your GImGui macro return the `ImGuiContext*` pointer and you won't have this problem:

`#define GImGui  ((ImGuiContext*)GImGuiExtended) // To use custom extended context`

Your custom code can use `GImGuiExtended` directly.

**Comment by Alzathar** [comment]
Hello and thanks ! That does the trick.

With your solution it is also necessary to define the macro `IMGUI_SET_CURRENT_CONTEXT_FUNC`, otherwise the compiler complains with "error C2106: '=': left operand must be l-value" in the definition of the function `SetCurrentContext` . The macro is defined as following:

```
#define IMGUI_SET_CURRENT_CONTEXT_FUNC(ctx) \
  GImGuiExtended = (ImGuiContextExtended *)ctx;
```
