### ISSUE TITLE
ImGuiWindowFlags_NoMove + ConfigDockingTabBarOnSingleWindows allows a window to be docked to itself

### ISSUE THREAD

**Issue by haldean** [ocornut/imgui#2325]
**Version/Branch of Dear ImGui:**

Version: 1.68 WIP (e114337)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: gcc
Operating System: both MacOS and Linux, but it's a logic bug so I think probably all platforms

**My Issue/Question:**

Setting the `ImGuiWindowFlags_NoMove` flag on a window with docking on and tab bars displayed on single windows allows the user to try to dock a window to itself, which then causes a failed assertion. I would expect that no docking handles appear when a window is flagged as `NoMove`.

**Screenshots/Video**

[Here's a screencap](https://photos.google.com/share/AF1QipPry2QJzkAjlYG7LVxmTuOR2Xre8IO5Tm_SsTR_gnF1wOpi9EewrXZ6mI8AiHkSdA/photo/AF1QipNJOf5fS7J2Po4U7FN1j4ansCVmMV3i8ypnGYNe?key=enRPX3N4dHh1T1JNRmM1T2dwVS1rWVBHU2NtZmpR)

In this video, I show that I can move the demo window around, then I turn "No move" on in the demo window options, I click and drag on the window's tab, and docking handles appear that allow me to dock the window. I would expect no docking handles to appear, because the window is not supposed to move, but I especially wouldn't expect docking handles to appear on the same window I'm currently moving. If you drop the window onto the docking handle, you get an assertion failure:

    [...]/src/main/cpp/imgui.cpp:10522: void ImGui::DockContextQueueDock(ImGuiContext*, ImGuiWindow*, ImGuiDockNode*, ImGuiWindow*, ImGuiDir, float, bool): Assertion `target != payload' failed.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// in setup:
	ImGuiIO &io = ImGui::GetIO();
	io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
	io.ConfigDockingTabBarOnSingleWindows = true;

// in main loop:
        static bool showDemo = true;
        if (showDemo) ImGui::ShowDemoWindow(&showDemo);
```

**Comment by haldean** [comment]
I found it while I was messing with the window flags in the demo window to see how the window flags were different in the docking branch, but I actually plan to use a NoMove window with docking mode; I'm using ImGui in a modelling application, so we have lots of dockable windows that have modelling parameters in them. There's also a set of buttons that control the camera that I want to be stuck to the center-bottom of the viewport that will probably be in an unmoveable and undecorated window.

**Comment by ocornut** [comment]
Had to revert this, it caused an issue with drag and drop in docking branch (see #2331). Will reapply correct fix soon.

**Comment by ocornut** [comment]
Pushed another fix for this now!
