### ISSUE TITLE
With GLSL #version > 410 are not used the "*_glsl_410_core" shaders, but older ones

### ISSUE THREAD

**Issue by BrutPitt** [ocornut/imgui#2329]
Hi @ocornut 

Using `ImGui_ImplOpenGL3_Init("#version 450");`, I noticed that ImGui use and add the string `#version 450` to  the defaults `*_shader_glsl_130` shaders , while I would expect it to use `*_shader_glsl_410_core` shaders.

It's not really a problem, it works anyway and the shaders are formally identical, but from source:

https://github.com/ocornut/imgui/blob/2d363fa315e97e3b4b1a5e1a800d0fbd6378e2c1/examples/imgui_impl_opengl3.cpp#L480-L484

would be enough just to change: 
``` c
else if (glsl_version >= 410) 
 { 
     vertex_shader = vertex_shader_glsl_410_core; 
     fragment_shader = fragment_shader_glsl_410_core; 
}
``` 
or is there a particular reason why it is?

Thanks

**Comment by ocornut** [comment]
No reason afaik. If you confirm that it works i’ll make the change!

**Comment by ocornut** [comment]
Applied the patch now!

**Comment by BrutPitt** [comment]
Yes, I confirm: it works.
I tested and used it for a couple of days before to open an "issue".

Thanks.
