### ISSUE TITLE
Docking branch: why does drag and drop not work?

### ISSUE THREAD

**Issue by namuda** [ocornut/imgui#2331]
I build example/GLFW + OpenGL3 code and DemoWindow's Drag and Drop is not working.
Do you have a plan to fix it?

**Comment by namuda** [comment]
In the bool ImGui :: BeginDragDropTarget () function
Commenting out lines 10010 and 10011 in the Imgui.cpp file could be run temporarily.
Is there no problem in this case?

**Comment by ocornut** [comment]
Pushed a quick hotfix for this now (reverting a change made for #2325). Will push a correct fix for #2325.
