### ISSUE TITLE
Greyed out FreeMono.ttf font and misalignment using ImGui::Text()

### ISSUE THREAD

**Issue by eRabbit0** [ocornut/imgui#2332]
RE: Vulkun + SDL + Linux (amd_gpu)

While learning how to work with fonts i encountered two different issues.
To resolve them both, i simply used different Mono font which both renders white and allows correct alignment of text. 
Not sure if below are bugs or my system misbehaves.

1) For one particular font on Linux - "gnu-free/FreeMono.ttf", if it is loaded first, all text is greyed out.
Changing style didn't allow to make it white. Though same font loaded second (with twice the size) renders white. Rest of the fonts i tried are OK.
![imgui_freemono ttf](https://user-images.githubusercontent.com/28832010/52272713-a692a500-2958-11e9-8385-e9e271099ecb.png)
```
ImVector<ImWchar> 	 ranges;
ImFontGlyphRangesBuilder builder;

builder.AddRanges   (io.Fonts->GetGlyphRangesDefault());
builder.AddText     (u8"φθ");										
builder.BuildRanges (&ranges);

if (config.fonts) {
	aux->fonts    = (ImFont **)calloc (2, sizeof (ImFont *));					
	aux->fonts[0] = io.Fonts->AddFontFromFileTTF (config.fonts[0], 13.0f, NULL, ranges.Data);
	aux->fonts[1] = io.Fonts->AddFontFromFileTTF (config.fonts[0], 26.0f, NULL, ranges.Data);
	
	unsigned char * pixels; 
	int width, height, bytes_per_pixels; 
	io.Fonts->GetTexDataAsAlpha8 (&pixels, &width, &height, &bytes_per_pixels);
	IM_ASSERT (io.Fonts->Fonts[0]->IsLoaded());
}
```
2) Second issue affected more fonts and screws formatting in ImGui::Text();
```
ImGui::Text ("current   %6.2f A", 0,52f);
ImGui::Text ("voltage   %6.2f V", 112,ff);
ImGui::Text ("cos θ   %6.2f", 0,72f);
```
See below example of misaligned text using "gnu-free/FreeSans.ttf" and normal behaviour with default ImGui font.
![imgui_misalignment](https://user-images.githubusercontent.com/28832010/52273009-95966380-2959-11e9-914e-938771bec964.png)
![imgui_normal](https://user-images.githubusercontent.com/28832010/52273076-bc549a00-2959-11e9-8a99-95666fc720ef.png)

**Comment by ocornut** [comment]
Hello,

Please attach the fonts file or provide links, and use Style Editor> Fonts to inspect the loaded font data.

For 1) I believe this is merely an artefact of the fact rendering low resolution fonts with stb_truetype without hinting can’t get you sharp results easily. You can use the Multiply setting of ImFontConfig as a cheap workaround, or increase solution, or use imgui_freetype.

For 2) I believe this is not a monospace font and therefore you have no guarantee that the characters would align.

**Comment by eRabbit0** [comment]
Hi ocornut,

Link to the greyed out font is below:
https://github.com/opensourcedesign/fonts/blob/master/gnu-freefont_freemono/FreeMono.ttf

Inspected loaded FreeMono.ttf and colour seem to be {1, 1, 1 ,1}. Should be artefact of rendering as you mentioned.
No questions on the second issue, all clear now.

Thank you for prompt reply!

**Comment by ocornut** [comment]
> Inspected loaded FreeMono.ttf and colour seem to be {1, 1, 1 ,1}.

TTF fonts don't have color information, this is an artefact of rendering.

Unfortunately this type of thin font is hard to rasterize at such low resolution without more advanced technique (hinting, subpixel rendering).

Using FreeType might get you better result.
I think dear imgui is doing a bad job at exposing oversampling, if you change from the default (3,1)  to `cfg.OversampleH = cfg.OversampleV = 2;` or `cfg.OversampleH = cfg.OversampleV = 1;` you will probably get better result.

Compare:
```
    {
        ImFontConfig cfg;
        io.Fonts->AddFontFromFileTTF("../../misc/fonts/FreeMono.ttf", 13.0f, &cfg);
    }
    {
        ImFontConfig cfg;
        cfg.OversampleH = cfg.OversampleV = 2;
        io.Fonts->AddFontFromFileTTF("../../misc/fonts/FreeMono.ttf", 13.0f, &cfg);
    }
    {
        ImFontConfig cfg;
        cfg.OversampleH = cfg.OversampleV = 1;
        io.Fonts->AddFontFromFileTTF("../../misc/fonts/FreeMono.ttf", 13.0f, &cfg);
    }
```

I've been looking at this recently and I hope that by 1.70 we can solidify the font rendering patterns.

**Comment by eRabbit0** [comment]
Hi ocornut,

Tried suggested settings, and oversampling as 2 produces better greek glyphs though difference is marginal for English letters.

Thank you for suggestion, i'll use value '2' from now on.

**Comment by ocornut** [comment]
I've been making tests likely and in most situations OversamplingH=2 seemed to provide better result than OversamplingH=3. 

Also see:
https://github.com/nothings/stb/tree/master/tests/oversample
