### ISSUE TITLE
Out-of-bounds read in stb_textedit_discard_redo (imstb_textedit.h)

### ISSUE THREAD

**Issue by zzzyap** [ocornut/imgui#2333]
Small issue our code analysis picked up, may be a problem with stb_textedit or the modified imstb_textedit. If it is not a problem with the modifications in imstb_textedit let me know and I'll forward it over to stb.

---
```
static void stb_textedit_discard_redo(StbUndoState *state)
{
```
**1. assignment: Assigning: k = 98.**
```
   int k = STB_TEXTEDIT_UNDOSTATECOUNT-1;
```
**2. Condition state->redo_point <= k, taking true branch.
3. cond_at_most: Checking state->redo_point <= k implies that state->redo_point may be up to 98 on the true branch.**
```
   if (state->redo_point <= k) {
      // if the k'th undo state has characters, clean those up
```
**4. Condition state->undo_rec[k].char_storage >= 0, taking true branch.**
```
      if (state->undo_rec[k].char_storage >= 0) {
         int n = state->undo_rec[k].insert_length, i;
         // move the remaining redo character data to the end of the buffer
         state->redo_char_point += n;
         STB_TEXTEDIT_memmove(state->undo_char + state->redo_char_point, state->undo_char + state->redo_char_point-n, (size_t) ((STB_TEXTEDIT_UNDOCHARCOUNT - state->redo_char_point)*sizeof(STB_TEXTEDIT_CHARTYPE)));
         // adjust the position of all the other records to account for above memmove
```
**5. Condition i < k, taking true branch.
8. Condition i < k, taking false branch.**
```
         for (i=state->redo_point; i < k; ++i)
```
**6. Condition state->undo_rec[i].char_storage >= 0, taking true branch.**
```
            if (state->undo_rec[i].char_storage >= 0)
```
**7. Jumping back to the beginning of the loop.**
```
               state->undo_rec[i].char_storage += n;
      }
      // now move all the redo records towards the end of the buffer; the first one is at 'redo_point'
```
**Out-of-bounds read (OVERRUN)
9. overrun-local: Overrunning array of 1584 bytes at byte offset 1584 by dereferencing pointer state->undo_rec + state->redo_point + 1.**
```
      STB_TEXTEDIT_memmove(state->undo_rec + state->redo_point+1, state->undo_rec + state->redo_point, (size_t) ((STB_TEXTEDIT_UNDOSTATECOUNT - state->redo_point)*sizeof(state->undo_rec[0])));
      // now move redo_point to point to the new one
      ++state->redo_point;
   }
}
```

**Comment by ocornut** [comment]
Hmm, weirdly enough I discussed this in https://github.com/nothings/stb/issues/321
And the current code in imstb_textedit.h does NOT reflect my conclusion posted there.
**I haven't thought about it again** but I'd suggest doing was my post there suggested to do, I may have lost the change when updating the code at some point?

Could you try replacing:
```
STB_TEXTEDIT_memmove(state->undo_rec + state->redo_point+1, state->undo_rec + state->redo_point, (size_t) ((STB_TEXTEDIT_UNDOSTATECOUNT - state->redo_point)*sizeof(state->undo_rec[0])));
// now move redo_point to point to the new one
++state->redo_point;
```

With
```
STB_TEXTEDIT_memmove(state->undo_rec + state->redo_point+1, state->undo_rec + state->redo_point, (size_t) ((STB_TEXTEDIT_UNDOSTATECOUNT - state->redo_point - 1)*sizeof(state->undo_rec[0])));
// now move redo_point to point to the new one
++state->redo_point;
```

And see what your static analyzer says?
Do you have a runtime repro in mind?

> If it is not a problem with the modifications in imstb_textedit let me know and I'll forward it over to stb.

This came as an attempt to fix various legit issues in the current nothings/stb_textedit.h so there's easy comparaison to make (aka stb_textedit.h appears to currently be _more_ broken than our modified imstb_textedit.h)

**Comment by zzzyap** [comment]
No repro, just something that popped up but thought it was worth mentioning.
Will try it out (looks good just reading it).
The analysis runs on the whole codebase (will take a bit) and there isn't really a repro on our end to test it out. But if it stops complaining it's most likely a win :)

**Comment by ocornut** [comment]
This should be fixed now.

I also created a test script to repro the issue locally (test bed is not published yet, but will be).

![image](https://user-images.githubusercontent.com/8225057/52308610-111a0400-299e-11e9-83ca-4947e19e4e5f.png)

**Comment by ocornut** [comment]
If possible please confirm this does indeed makes your static analyzer relax!

**Comment by zzzyap** [comment]
Unfortunately the code analysis is still complaining :( 
Will poke it a bit more to see if I can get more info out of it.

**Comment by ocornut** [comment]
Thank you! Would appreciate the report there.

**Comment by zzzyap** [comment]
Sorry for not getting back to you sooner. 
The report is produces is the same as the initial report.
We decided to ignore it, the fix you presented makes sense and our code analysis is just being over picky. 
Thanks.
