### ISSUE TITLE
How to get R, G , B from ColorEdit3

### ISSUE THREAD

**Issue by Nitro112** [ocornut/imgui#2335]
Hey!

I would like to know, how to get R, G, B values from ColorEdit3?
for example,
float Color[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
ImGui::ColorEdit3("Color", (float*)&color);
now when i pass Color[0] and Color[1] and Color[2] to another function. it gives me different values.
Also tried to pass it to ImGui::Text("%f, %f, %f, %f", Color[0], Color[1], Color[2], Color[3]); and that gave me huge numbers.

**Comment by ifarbod** [comment]
Change this line:

```cpp
ImGui::ColorEdit3("Color", (float*)&color);
```
To:
```cpp
ImGui::ColorEdit3("Color", color);
```

And set `Color`'s size to 3 instead of 4, but if you want the alpha value too, use `ColorEdit4`.

**Comment by Nitro112** [comment]
Thank you! I'll try that.
