### ISSUE TITLE
Draw Triangles with indices

### ISSUE THREAD

**Issue by zalavariandris** [ocornut/imgui#2338]
**Version: 1.68**
**Branch: master**

**ofxImgui/GLFW/VisualStudio/windows**

First I'd like to say Hello, this is my first post here. This library become my favorit ever. I was always struguling to have a little ui to explore ideas while coding. And Imgui really helps without getting in the way! So thanks for writing and sharing it. I also learn a lot from the ideas and the source code.

But I have a little question: I am trying to create a function to draw triangles with indices. ImGui already using inidces under the hood and the glfw renderer uses glDrawElements with GL_TRIANGLES, so I thought it would be relatively easy. As a starting point, I copied the code from AddConvexPolyFilled to my custom function and prepended drawList where needed. For my surprise the custom function behaves strange: the last point of the triangle sticks to the top left corner of the window.

On the screenshot the red triangle is produced by the AddConvexPolyFilled function and the white triangle is from the custom function.

Since it seem to be the same code, there must be something obvious I miss. Probably the drawList is different when I get the current one.

So the question is how to fix my function to produce the same result as the original AddConvexPolyFilled?
How to draw a 2D mesh with custom vertices and indices, with ImGui?

![addtriangles_test](https://user-images.githubusercontent.com/4587642/52526748-ccec7380-2cbd-11e9-924a-085acd5889c0.PNG)

	void AddTriangles(const ImVec2 * points, const int points_count, ImU32 col) {
		ImDrawList * drawList = ImGui::GetWindowDrawList();

		const ImVec2 uv = drawList->_Data->TexUvWhitePixel;

		// Non Anti-aliased Fill
		const int idx_count = (points_count - 2) * 3;
		const int vtx_count = points_count;
		drawList->PrimReserve(idx_count, vtx_count);
		for (int i = 0; i < vtx_count; i++)
		{
			drawList->_VtxWritePtr[0].pos = points[i];
			drawList->_VtxWritePtr[0].uv = uv;
			drawList->_VtxWritePtr[0].col = col;
			drawList->_VtxWritePtr++;
		}
		for (int i = 2; i < points_count; i++)
		{
			drawList->_IdxWritePtr[0] = (ImDrawIdx)(drawList->_VtxCurrentIdx);
			drawList->_IdxWritePtr[1] = (ImDrawIdx)(drawList->_VtxCurrentIdx + i - 1);
			drawList->_IdxWritePtr[2] = (ImDrawIdx)(drawList->_VtxCurrentIdx + i);
			drawList->_IdxWritePtr += 3;
		}
		drawList->_VtxCurrentIdx += (ImDrawIdx)vtx_count;
	}

	void ofApp::draw()
	{
		gui.begin();
		//ImGuiStyle style = ImGui::GetStyle();
		//style.AntiAliasedFill = false;
		//style.AntiAliasedLines = false;
		ImGui::Begin("Triangles test");
		std::vector<ImVec2> points{
			ImVec2(200, 200), ImVec2(200, 500), ImVec2(500, 500)
		};
		AddTriangles(points.data(), points.size(), ImColor(255, 255, 255, 255));
		ImDrawList * drawList = ImGui::GetWindowDrawList();
		drawList->AddConvexPolyFilled(points.data(), points.size(), ImColor(255, 0, 0, 128));
		ImGui::End();
		gui.end();
	}

**Comment by ocornut** [comment]
If I copy and paste your code I get exactly 2 of the same triangle, not matching your screenshot.
You have a problem elsewhere, either way this is a problem in your code.

**Comment by ocornut** [comment]
You may use the Metrics window to inspect the final vertices/indices, that should be able to help you.

**Comment by zalavariandris** [comment]
Interesting. I created a function inside imgui_draw.cpp and it works there. It must be something else. Strange. Thanks for testing it : )
