### ISSUE TITLE
How can I change the Widgets Size?

### ISSUE THREAD

**Issue by swordwest** [ocornut/imgui#2339]
How can I change the Widgets Size? eg.  The checkbox Height Or Width?

**Comment by ebachard** [comment]
Hello,

Not sure, I'm fully answering your question (@ocornut  will correct me), but a good start could be to read carefully imgui.cpp, because a lot of information is inside ;-)

e.g., on Linux: head -1122 imgui.cpp | tail -5 

returns:

````


// To scale your entire UI (e.g. if you want your app to use High DPI or generally be DPI aware) you may use this helper function. Scaling the fonts is done separately and is up to you.
// Important: This operation is lossy because we round all sizes to integer. If you need to change your scale multiples, call this over a freshly initialized ImGuiStyle structure rather than scaling multiple times.
void ImGuiStyle::ScaleAllSizes(float scale_factor)

````

HTH

**Comment by ocornut** [comment]
Use PushItemWidth().
Run the demo code and browse to find what you need, then look at the code.

**Comment by swordwest** [comment]
@ocornut ,I know this function can change widget width,but how can I change the widget height?

**Comment by ocornut** [comment]
Most widget height are derived from `(FontSize + style.FramePadding.y * 2)`
Some can be overrided with a size parameter in the function signature.
