### ISSUE TITLE
Font size 

### ISSUE THREAD

**Issue by InfernoLum** [ocornut/imgui#2344]
Hello, I have been working on a menu(for a game cheat) which is using ImGui and I would like to change the font size of certain buttons. Is that possible?

Kind regards

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by InfernoLum** [comment]
Damn dear imgui is quite good unlike its "helpful" developer

**Comment by xo1337** [comment]
> Damn dear imgui is quite good unlike its "helpful" developer

yeah lmao, he gets mad at people who don't know how to do stuff in imgui lol, idk why but thats just him lmaoo

**Comment by BtheDestroyer** [comment]
He gets mad when people e-beg for Github users to write cheating tools for them - he's fine with anyone asking for help in ways that show they're using the tool in a reasonable way if they do so in a way that shows they have a general understanding of computer science and aren't just looking to copy-paste others' code.

**Comment by xo1337** [comment]
> He gets mad when people e-beg for Github users to write cheating tools for them - he's fine with anyone asking for help in ways that show they're using the tool in a reasonable way if they do so in a way that shows they have a general understanding of computer science and aren't just looking to copy-paste others' code.

I don't see anyone making cheats with imgui, what did the developer of imgui expect for people not to make cheats with it? lmao, this can't be a joke

**Comment by BtheDestroyer** [comment]
You clearly didn't actually read #1586...

> I will from now on immediately block them and close their issues as soon as I suspect they come from a script-kiddie-cheating-in-multiplayer-games background...
> ...Note that many other forms of creative or elaborate cheats/hacking/reverse engineering tools are perfectly fine.

They're fine with people making cheats, they just don't want people begging to have programs written for them.

**Comment by SorryX** [comment]
He is asking for how to modify font size not to write a cheat. That's fully related to imgui.
