### ISSUE TITLE
Window resize with Vulkan + SDL

### ISSUE THREAD

**Issue by eRabbit0** [ocornut/imgui#2348]
Hi ocornut,

I was having an issue handling resize with Vulkan + SDL on both amdgpu and NVidia proprietary drivers under recent Fedora.
```
while (!done) {
	SDL_Event event;
	while (SDL_PollEvent(&event))
	{
		ImGui_ImplSDL2_ProcessEvent(&event);
		if (event.type == SDL_QUIT)
			done = true;
		if (event.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_RESIZED && event.window.windowID == SDL_GetWindowID(window)) 
			ImGui_ImplVulkanH_CreateWindowDataSwapChainAndFramebuffer (g_PhysicalDevice, g_Device, &g_WindowData, g_Allocator, (int)event.window.data1, (int)event.window.data2);
	}
	...
	ImGui::Render();
	memcpy(&wd->ClearValue.color.float32[0], &clear_color, 4 * sizeof(float));
		FrameRender(wd);
}
```
The problem was that exception in FrameRender() was triggered before polled SDL resize event.

Workaround is pretty straight forward:
1) Adjusted struct ImGui_ImplVulkanH_WindowData by adding window member:
```
struct ImGui_ImplVulkanH_WindowData
{
	void		    *window;		
	...
};
```
2) Added error check for vkAcquireNextImageKHR as below
```
static void
FrameRender (ImGui_ImplVulkanH_WindowData* wd)
{
	VkResult err;

	VkSemaphore& image_acquired_semaphore  = wd->Frames[wd->FrameIndex].ImageAcquiredSemaphore;
	err = vkAcquireNextImageKHR (g_Device, wd->Swapchain, UINT64_MAX, image_acquired_semaphore, VK_NULL_HANDLE, &wd->FrameIndex);
	if (err == VK_ERROR_OUT_OF_DATE_KHR) {
	    	int w, h;
    		SDL_GetWindowSize ((struct SDL_Window *)wd->window, &w, &h);

		ImGui_ImplVulkanH_CreateWindowDataSwapChainAndFramebuffer (g_PhysicalDevice, g_Device, &g_WindowData, g_Allocator, w, h);
	} else if (err != VK_SUCCESS && err != VK_SUBOPTIMAL_KHR)
		check_vk_result(err);
	...
```
3) Polling for SDL_WINDOWEVENT_RESIZED should be redundant now, so removed it.

4) This fix works fine for amdgpu, but on NVidia Optimus laptop (hybrid) i have additional issue that when i click outside app's window, system freezes for about 10 seconds, and trying resize crashes app on check_vk_result() in FramePresent().

If i add same VK_ERROR_OUT_OF_DATE_KHR handler to FramePresent it resizes OK (now on both amd and nvidia), though i still need to figure out what causes these freezes.

I'm no expert in graphics programming, and if there is better solution i'd gladly implement it.

**Comment by ocornut** [comment]
Hello @eRabbit0,

Could you clarify "The problem was that exception in FrameRender() was triggered before polled SDL resize event.", which exception/error? And bundle this as a Pull Request?

Thank you.

**Comment by eRabbit0** [comment]
VSync seem to be the culprit.
I did further experiments and situation looks as follows on resize (without handling VK_ERROR_OUT_OF_DATE_KHR):

1) **VSync on** - SDL event queue is empty, despite already resized window, we proceed further, catch VK_ERROR_OUT_OF_DATE_KHR in FrameRender() and abort(). During all tests, SDL resize events were added (and handled) only on the next frame.

2a) **VSync off with amdgpu** - 6200 FPS, resize from keyboard works fine, but doing it using mouse succeeds only 10% of the time. Adding VK_ERROR_OUT_OF_DATE_KHR handler only for **vkAcquireNextImageKHR()** solves issue. NVidia Optimus still crashes though.

2b) **VSync off with NVidia Optimus** - 1500 FPS, mostly works, but there are occasional crashes, adding VK_ERROR_OUT_OF_DATE_KHR handler only for **vkQueuePresentKHR()** solves issue, though does nothing for amdgpu.

Also, turning VSync off on NVidia Optimus solved 10 sec freezes on my laptop.
All in all, it looks like it is both driver and VSync dependent.

I will be working with rendering part of my app next week, and combine all findings in one pull request afterwards.

**Comment by eRabbit0** [comment]
Hi ocornut,

As i mentioned i'm collecting suggestions for Vulkan binding while working on rendering part of my app.
Meantime, one thing i can report with certainty is the issue regarding system freezes with NVIDIA Optimus under Linux using proprietary drivers (up to recent 418.31.03).

As i suspected problem was VSync. Long story short, it's problem with NVidia drivers and can be solved by turning off PRIME Syncronization, executing "xrandr --output <output> --set "PRIME Synchronization" 0" for relevant <output>. In this case app runs as if it was compiled with IMGUI_UNLIMITED_FRAME_RATE flag.

References:
https://github.com/SaschaWillems/Vulkan/issues/296
https://devtalk.nvidia.com/default/topic/957814/linux/prime-and-prime-synchronization/post/5102922/#5102922

**Comment by eRabbit0** [comment]
Hi ocornut,

I more or less finished implementing 3D rendering in my app. Ended up rewriting pretty much everything.

Regarding the issue with resize, i suggest to do the following:
1) Catch VK_ERROR_OUT_OF_DATE_KHR in two places: after call to vkAcquireNextImage and vkQueuePresentKHR. Both could return such value.

      _amdgpu_ - catches VK_ERROR_OUT_OF_DATE_KHR right after vkAcquireNextImageKHR
      _nvidia_    - catches same error only after vkQueuePresentKHR, no matter what i did

2) Handle if as follows (just exit function):
```
	err = vkAcquireNextImageKHR (g_Device, wd->Swapchain, UINT64_MAX, image_acquired_semaphore, VK_NULL_HANDLE, &wd->FrameIndex);
	if (err == VK_ERROR_OUT_OF_DATE_KHR) {
		return;
	} else if (err != VK_SUCCESS && err != VK_SUBOPTIMAL_KHR)
		check_vk_result (err);
```
Same code for vkQueuePresentKHR.

3) Keep current code for SDL resize event recreating swapchain there (no changes here):
```
        while (SDL_PollEvent(&event))
        {
            ImGui_ImplSDL2_ProcessEvent(&event);
            if (event.type == SDL_QUIT)
                done = true;
            if (event.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_RESIZED && event.window.windowID == SDL_GetWindowID(window))
                ImGui_ImplVulkanH_CreateWindowDataSwapChainAndFramebuffer(g_PhysicalDevice, g_Device, &g_WindowData, g_Allocator, (int)event.window.data1, (int)event.window.data2);
        }
```
4) Remove FramePresent() and move its code to the end of FrameRender.
This is necessary because if we exit FramRender() on VK_ERROR_OUT_OF_DATE_KHR, there is nothing new to present to the swapchain. It will just produce artefacts.

These are minimal changes to avoid crashes which i experienced.
Return on error and move code from FramePresent() to FrameRender(). That's it.

This is raw version of the program for control of my industrial milling robot :)
![screenshot from 2019-03-04 14-32-15](https://user-images.githubusercontent.com/28832010/53766837-0d1dcb00-3ee5-11e9-8898-f08c77ff69a6.png)
