### ISSUE TITLE
Single window

### ISSUE THREAD

**Issue by mnemode2** [ocornut/imgui#2349]
I want to use `imgui` for my simple windows application, I want one window with several controls (bottons, etc)
Is this possible to create such window with `imgui`?
I don't want one big window with `imgui` subwindows but one `imgui` window with controls

NOT like this:
![image](https://user-images.githubusercontent.com/47631447/52785092-c95f4080-305f-11e9-86b8-196727262221.png)

I want to build desktop app

**Comment by ocornut** [comment]
Just create an OS window that doesn't have OS decorations, then create an imgui window that fills the OS window using `SetNextWindowPos(ImVec2(0,0)); `SetNextWindowSize(io.DisplaySize);`

**Comment by mnemode2** [comment]
" OS window that doesn't have OS decorations"
How can I do that on Windows?
via `CreateWindow`?

**Comment by ocornut** [comment]
That's not a question related to Dear ImGui. Look up for `WS_POPUP` `WS_EX_TOOLWINDOW` flag in Win32 api.

**Comment by mehditlili** [comment]
Just to precise, `SetNextWindowPos(ImVec2(0,0)); SetNextWindowSize(io.DisplaySize); ` as the name hints should be called before creating the window. On Linux at least, I get an Imgui window without an X button unlike the example above. So keeping the window decorator of my OS is preferred (Using Compiz)

**Comment by ocornut** [comment]
Amending this old thread

You should not do:
```
SetNextWindowPos(ImVec2(0,0)); 
SetNextWindowSize(io.DisplaySize); 
```
But:
```
ImGuiViewport* viewport = ImGui::GetMainViewport():
SetNextWindowPos(viewport->Pos); 
SetNextWindowSize(viewport->Size); 
```
To ignore main menu bar.

Which you can also change:
```
ImGuiViewport* viewport = ImGui::GetMainViewport():
SetNextWindowPos(viewport->WorkPos); 
SetNextWindowSize(viewport->WorkSize); 
```
