### ISSUE TITLE
Triggered IM_ASSERT when building font ranges

### ISSUE THREAD

**Issue by r-lyeh** [ocornut/imgui#2353]
Hello @ocornut,

Just upgraded to latest 1.68 + docking branch and related custom add-ons.
This assertion fails now:
`Assertion failed: src_tmp.GlyphsList.Size == src_tmp.GlyphsCount, file C:/prj/#AVA/editor/3rd/@ocornut/imgui_draw.cpp, line 1879`

Also, this is the minimal repro-steps case that used to work before.
Apparently, overlapping font ranges were ok before but now it wont build atlas :D

```C++
ImGuiIO& io = ImGui::GetIO();
ImFontConfig *cfg = &ImFontConfig();

static const ImWchar default_ranges[] =
{
	0x0020, 0x00FF, // Basic Latin + Latin Supplement
	0x0080, 0x00FF, // Latin_Supplement

	0,
};

io.Fonts->AddFontFromMemoryCompressedTTF( FONT_MAIN_BUF, FONT_MAIN_LEN, FONT_MAIN_SIZE, cfg, default_ranges );
```

**Comment by r-lyeh** [comment]
Managed to compile after fixing (manually) many overlapping ranges in many locales (phiew)

The issues that you mentioned somewhere else are gone :D

Quick feedback after comparing new 1.68+docking against old 1.66+docking.
Minor issues mainly, I understand the 
- Loading old imgui.ini crashed; had to delete file to get it working, then recreate previous docking layout . `Assertion failed: tab->NameOffset != -1 && tab->NameOffset < TabsNames.Buf.Size, file c:\prj\#ava\editor\3rd\@ocornut\imgui_internal.h, line 1475`
- There is some new random flickering in the blue drop regions when dragging tabs. Even if user does not move mouse, there is random flickering on and off.
- Also, some minor z-order issues with those very same blue drop regions. At some point one of the tabs went out of focus even if no other tab was overlapping at all. Couldnt give that bar any kind of focus with mouse. Fixed it by reordering layout of surronding tabs. Cannot give repro steps for this.

And now the juicy bits :D
![image](https://user-images.githubusercontent.com/35402248/52905979-367efb80-3243-11e9-82b4-1bfc94566201.png)

**Comment by ocornut** [comment]
Hello,

Could you provide the crashing ini file? Was it an assert or a crash?

Could you provide gif of the other issues?

Will look into them tomorrow.

**Comment by r-lyeh** [comment]
1. It was an assert in fact: `Assertion failed: tab->NameOffset != -1 && tab->NameOffset < TabsNames.Buf.Size, file c:\prj\#ava\editor\3rd\@ocornut\imgui_internal.h, line 1475`

Ini file here: https://github.com/r-lyeh/AVA/blob/30eda74515838554749718668ec3cd5e81daae68/editor/editor.ini

2. Sure, I will try to record sth.

**Comment by r-lyeh** [comment]
The issue is much less noticeable in the gif due to low framerate. Sorry.
Repro-steps (I think). Maximize client window. Pick any tab which is large enough. Scroll it so it overlaps right and bottom screen borders. Notice the issue. Note: I am using a single monitor setup right now.

![gif](https://user-images.githubusercontent.com/35402248/52912636-4d116b00-32b4-11e9-89a9-a2fce1c016b3.gif)

**Comment by r-lyeh** [comment]
About the z-order issue, I will try to record a gif whenever I found it again, but I havent been able to reproduce it again :)

**Comment by ocornut** [comment]
(1) Fixed the overlapping font range within same font issue now.

(2) For the assert I'll need to investigate further for a repro. If you can get it to repro, a callstack would be helpful. 

(3) For the docking drop overlay moving: do you have multi-viewport enabled? and does the dragged window leads to a new viewport being created? It is frequent to see unsynchronized renders (not always easy to fix depending on codebase/engine, there is a workaround but I'll like to first confirm if your bug is related to multi-viewport).

Please open separate issues when the topics are unrelated (don't hesitate to open 3 issues for 3 different bugs!). Thanks a lot!

**Comment by r-lyeh** [comment]
1. Nice!
2. Cannot reproduce that assert anymore.
3. Multi? yes. dragging to new viewport? no idea, it is overlapping with the physical monitor borders. ie, there is no more space left so dunno what imgui would do.

ps: oook. i just found 2 new bugs today :) feel free to close this issue and i'll re-open as needed.

**Comment by r-lyeh** [comment]
Created 3 new issues from derived issues. Original issue is fixed.
