### ISSUE TITLE
Can't close popupmenu with keyboard focused inputtext

### ISSUE THREAD

**Issue by CedricGuillemet** [ocornut/imgui#2354]
Hi there,

With master v1.68 WIP, I'm having an issue with popupmenu. 
I want a popup menu containing some menuitems and a focused input text. That input text is used to filter menuitems.

Here is a simple repro:
```
if (ImGui::BeginPopup("context_menu"))
{
            static char inputText[64] = { 0 };
            // Comment next line to be able to close context menu...but lose focus on text edit

            ImGui::SetKeyboardFocusHere();
            ImGui::InputText("", inputText, sizeof(inputText));
            ImGui::Separator();
            ImGui::MenuItem("You have to", NULL, false, false);
            ImGui::MenuItem("Click an item", NULL, false, false);
            ImGui::MenuItem("To close the menu", NULL, false, true);
            ImGui::EndPopup();
}
if (ImGui::IsMouseClicked(1))
            ImGui::OpenPopup("context_menu");
```

My Issue is that when the inputtext get the focus (SetKeyboardFocusHere), the user can't close the popupmenu by ESC, click,... he has to select a menu item.
When the SetKeyboardFocusHere line is commented, everything works fine. 

Thank you for your help :)

**Comment by ocornut** [comment]
The focus/nav function are currently in a bit of a limbo, Maybe this will work for you?

```
if (IsWindowAppearing())
   SetKeyboardFocusHere();
```

When the `InputText` is active, ESC will first disable this so it may requires two presses on ESC.
I understand that another step would make to configure InputText so it can forward the ESC to the popup (via item flags), but if that works well enough for you now let me know!

**Comment by CedricGuillemet** [comment]
I can click around to close the popup so it's good enough for now.
Thank you Omar!
