### ISSUE TITLE
Adding tick marks to your PlotLines()

### ISSUE THREAD

**Issue by JamAndCheese** [ocornut/imgui#2356]
if anyone is looking into adding tick marks to your plots, you can consider adding this code to PlotEx() right before the text rendering code. You might want to enclose it in a test for PlotLines versus histogram.

`
    // Draw X ticks

    //
    // Minor ticks
    //
    ImU32 tickColor  = GetColorU32( ImVec4( 0.35f, 0.35f, 0.35f, 1.00f ) );
    float       tickInc( 0.05f );
    float       tickLen( 0.05f );
    int         countTicks( 1.0f / tickInc );
    float       tickPos( tickInc );

    for ( int n = 0; n < countTicks; ++n ) {

      // Add top ticks
      ImVec2 tp0  = ImVec2( tickPos, 0.00f );
      ImVec2 tp1  = ImVec2( tickPos, tickLen );
      ImVec2 pos0 = ImLerp( inner_bb.Min, inner_bb.Max, tp0 );
      ImVec2 pos1 = ImLerp( inner_bb.Min, inner_bb.Max, tp1 );

      pWindow->DrawList->AddLine( pos0, pos1, tickColor );

      // Add bottom ticks
      tp0  = ImVec2( tickPos, 1.0f );
      tp1  = ImVec2( tickPos, 1.0f - tickLen );
      pos0 = ImLerp( inner_bb.Min, inner_bb.Max, tp0 );
      pos1 = ImLerp( inner_bb.Min, inner_bb.Max, tp1 );

      pWindow->DrawList->AddLine( pos0, pos1, tickColor );

      tickPos += tickInc;

    }

    //
    // Major ticks
    //
    tickColor   = GetColorU32( ImVec4( 0.4f, 0.4f, 0.4f, 1.00f ) );
    tickInc     = 0.1f;
    tickLen     = 0.1f;
    countTicks  = 1.0f / tickInc;
    tickPos     = tickInc;

    for ( int n = 0; n < countTicks; ++n ) {

      // Add top ticks
      ImVec2 tp0  = ImVec2( tickPos, 0.00f );
      ImVec2 tp1  = ImVec2( tickPos, tickLen );
      ImVec2 pos0 = ImLerp( inner_bb.Min, inner_bb.Max, tp0 );
      ImVec2 pos1 = ImLerp( inner_bb.Min, inner_bb.Max, tp1 );

      pWindow->DrawList->AddLine( pos0, pos1, tickColor );

      // Add bottom ticks
      tp0  = ImVec2( tickPos, 1.0f );
      tp1  = ImVec2( tickPos, 1.0f - tickLen );
      pos0 = ImLerp( inner_bb.Min, inner_bb.Max, tp0 );
      pos1 = ImLerp( inner_bb.Min, inner_bb.Max, tp1 );

      pWindow->DrawList->AddLine( pos0, pos1, tickColor );

      tickPos += tickInc;

    }
`

**Comment by r-lyeh** [comment]
@JamAndCheese can you post a screenshot? thx :D

**Comment by JamAndCheese** [comment]
Major and minor ticks shown, with the above definitions.

![plotter](https://user-images.githubusercontent.com/29165592/53067296-d382a400-3490-11e9-8ce0-d0a2aa436e88.png)

**Comment by JamAndCheese** [comment]
Major and minor X ticks shown, with the above definitions. 
![plotter](https://user-images.githubusercontent.com/29165592/53067388-32481d80-3491-11e9-8cfc-0bd3d6acda0f.png)

I also have example of Y ticks, if someone is interested.

**Comment by Stars-6195** [comment]
Can you please share the screenshot for y-axis @JamAndCheese

**Comment by ocornut** [comment]
FYI nowadays I would recommend using ImPlot
https://github.com/epezent/implot

I've tagged this issue so it can easily be found.

**Comment by Stars-6195** [comment]
Since i am coding in .net, implot or the cimplot are not supported in this language 
hence i am writing to add it manually!!  

Thank you for the response

**Comment by ocornut** [comment]
cimgui should support extensions like that,
e.g. this project has implot and other extensions in .net
https://github.com/EvergineTeam/ImGui.Net

**Comment by Stars-6195** [comment]
its missing the cimplot.dll files and Imgui.net does not support Implot !!!  @ocornut

**Comment by Stars-6195** [comment]
@ocornut  thank you  will have a look into it !!
