### ISSUE TITLE
Bug: IM_ASSERT: tab->NameOffset != -1

### ISSUE THREAD

**Issue by r-lyeh** [ocornut/imgui#2362]
Loading old imgui.ini asserted/crashed; had to delete file to get it working, then recreate previous docking layout . `Assertion failed: tab->NameOffset != -1 && tab->NameOffset < TabsNames.Buf.Size, file c:\prj\#ava\editor\3rd\@ocornut\imgui_internal.h, line 1475`

_Originally posted by @r-lyeh in https://github.com/ocornut/imgui/issues/2353#issuecomment-464394136_

**Comment by r-lyeh** [comment]
I am currently trying to reproduce this again without success. I will attach dump & callstack when I find it.

**Comment by ocornut** [comment]
I'll close this as we are lacking a repro or details. Don't hesitate to post here if you stumble on something and I'll reopen the issue.
