### ISSUE TITLE
Columns render over Tabs

### ISSUE THREAD

**Issue by dank** [ocornut/imgui#2364]
**Version/Branch of Dear ImGui:**

Version: 1.67 (release)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: Visual C++ compiler
Operating System: Windows 10

**My Issue/Question:**

Columns render on top of unselected tabs.

**Screenshots/Video**

![capture](https://user-images.githubusercontent.com/1585101/52985626-c0a19e00-33c2-11e9-9859-3967917925ab.PNG)
![capture2](https://user-images.githubusercontent.com/1585101/52985627-c0a19e00-33c2-11e9-8823-5431ee488dbf.PNG)

As I adjust the width of the column, more of the unselected tab is visible. 

**Standalone, minimal, complete and verifiable example:**
```c++
if (ImGui::Begin("test", NULL, ImVec2(0, 0), 1.f)) {
		if (ImGui::BeginTabBar("Hello")) {
			if (ImGui::BeginTabItem("First")) {
				ImGui::Columns(2);
				ImGui::Text("Hello");
				ImGui::Spacing();
				ImGui::Text("Hello");
				ImGui::Text("Hello");
				ImGui::Spacing();
				ImGui::Text("Hello");
				ImGui::EndTabItem();
			}

			if (ImGui::BeginTabItem("Second tab and very long name hi hello bye")) {
				ImGui::EndTabItem();
			}

			ImGui::EndTabBar();
		}
}
ImGui::End();
```

**Comment by ocornut** [comment]
Well your code is ambiguous as you open a Columns set and never close it.
Depending on what you are trying to achieve you may want to close the columns with `Columns(1)`..

**Comment by dank** [comment]
Ah, my bad. I did not understand the `Columns` correctly. After closing the columns, it worked.

Thank you.

Closing this issue.
