### ISSUE TITLE
GLFW - example integration on Osx breaks OpenGL state

### ISSUE THREAD

**Issue by sadovsf** [ocornut/imgui#2366]
Hello recently i updated my ancient version of ImGUI i was using to current one Tagged as 1.68 in git (commit: 3c15dffc944419eb4bb17984548468270ca90486). With that i discovered after integrating with my engine. That there is one call which causes OpenGL to cry about unknown enum value (Error 500). Piece of code that is causing this issue is:

glGetIntegerv(GL_CLIP_ORIGIN, (GLint*)&last_clip_origin); // Support for GL 4.5's glClipControl(GL_UPPER_LEFT)

From example integration for OpenGL3. When i remove this everything runs well. Iam using GLFW with already mentioned OpenGL3 on Osx Mojave (Latest update). Also i was not able to find glGetIntegerv documentation allowing enum value GL_CLIP_ORIGIN as parameter so maybe it is even bug.

**Comment by ocornut** [comment]
`GL_CLIP_ORIGIN` may not be supported on Osx Mojave.
I presume the define comes from gl3w.h , so we have a problem here and need to find another way to detect support (e.g. query OpenGL version?) Do you have a suggestion?

Linking to #2186.

**Comment by sadovsf** [comment]
Sure, version could work or for time being as Apple is not going to support much OpenGL any further it should be quite safe to disable for Osx generally (we are still on something like v3.3)

**Comment by ocornut** [comment]
> it should be quite safe to disable for Osx generally (we are still on something like v3.3)

That should do the trick. 

> Also question is if this should even be in OpenGL3 example as it is 4.5 feature

The file is kind of misnamed as it support wide range of versions, will rename to imgui_impl_gl at some point.

**Comment by sadovsf** [comment]
Also maybe important piece of info, i'am using IMGUI_IMPL_OPENGL_LOADER_GLEW

**Comment by sadovsf** [comment]
Perfect, should i make pull request or you will do the change?

**Comment by ocornut** [comment]
Hello,
I can add the ifdef, but I'll like to to hunt for a few more confirmation that 4.5 functions are not accessible on OSX (sorry if this sound naive/dumb! I don't know much about either tech!). Asked the author of the previous issue tht led to issue, if you have more reference to share it would help.

**Comment by sadovsf** [comment]
I fully understand that. Here is some more info about ogl on osx:
https://www.google.com/amp/s/appleinsider.com/articles/18/06/04/opengl-opencl-deprecated-in-favor-of-metal-2-in-macos-1014-mojave/amp/

https://www.forums.fusionfalluniverse.com/index.php?topic=15145.0

And yes it looks like we will have to use some wrapper above rendering tech like bgfx in the future to have multiplatform rendering solution which sucks 😕

**Comment by MichaelSSky** [comment]
AFAIK the method is not supported on OS X due to the lack of support for OpenGL 4.5

**Comment by ocornut** [comment]
Thank you both, I have applied the fix for it now!
