### ISSUE TITLE
Is ImGui::InputTextMultiline selected return message

### ISSUE THREAD

**Issue by FaceDragon** [ocornut/imgui#2370]
Is it possible to get a return message that tells if the InputTextMultiline box is selected? Like it return true if you have clicked inside InputTextMultiline and it is ready to type? It had been where heandy if we could do something like this if there isn't a method for this at current state.

example:
if(ImGui::InputTextMultiline())
{
Do stuff when selected
}
Or
Bool Selected;
ImGui::InputTextMultiline(Selected......)
if(Selected)
{
Do stuff when selected
}

**Comment by ocornut** [comment]
You can use ImGui::IsItemActive(). Check the demo code for details.
