### ISSUE TITLE
Can't change separator color

### ISSUE THREAD

**Issue by EggsyCRO** [ocornut/imgui#2374]
**Version/Branch of Dear ImGui:**

Version: dear imgui v1.60
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11
Compiler: Visual Studio 2017
Operating System: Windows 10

**My Issue/Question:**

I tried changing the Separator color, but it stays white for some reason. I made sure I'm not pushing the color to white anywhere or something similar. I can change the color of everything else with no issue, but separator just won't change for some reason.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/39103865/53285421-889eb000-3760-11e9-933e-c0f8aa3de265.png)

Can't really provide any more code because of the simple nature of the issue.

**Comment by ocornut** [comment]
Have a look at the style editor inside Demo to make sure the values are set correctly and try to tweak them live to see the effect.

**Comment by ocornut** [comment]
Hello,

It works perfectly here:
`style.Colors[ImGuiCol_Separator] = ImVec4(1.0f, 0.0f, 0.0f, 1.0f);`

![image](https://user-images.githubusercontent.com/8225057/53287135-41bcb480-3778-11e9-8855-5184d03c17d2.png)

So there is a mistake somewhere else in your code, that is omitted by your repro.

**Comment by ocornut** [comment]
Closing this as an issue, feel free to comment if you have problem tracking the issue in your code however.

**Comment by EggsyCRO** [comment]
All my code seems fine, when I hardcoded the color in the Separator function it started working normally. Before that it was taking the Separator color which was green but still displayed white for some reason.
