### ISSUE TITLE
Mouse Position Fix, Mouse Hiding

### ISSUE THREAD

**Issue by imnotkind** [ocornut/imgui#2375]
**Version/Branch of Dear ImGui:**

Version: 1.66b
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_freeglut.cpp 
Compiler: VC15
Operating System: Windows 10

**My Issue/Question:**

Hello, I'm new to imgui :)
I'm trying to hide my mouse and fix my mouse's position, just like an fps game.
This functionality is in winapi, freeglut, and whatsoever, but does imgui provide a way?
What is the most recommended way to achieve this in imgui style?

**Comment by ocornut** [comment]
Hello,

**(1) Mouse cursor**

The Freeglut backend doesn't touch/alter mouse cursor state, so you are free to alter the OS mouse cursor via you own mean. 

I didn't actually realize Freeglut had a `glutSetCursor()` function so you are correct it is indeed possible with FreeGlut and therefore the FreeGlut back-end should support it.

I would take a PR if you are willing to add the code for it.
In `ImGui_ImplFreeGLUT_NewFrame()` you probably want to call glutSetCursor() based on the current value of `ImGui::GetMouseCursor()`. You can look at the other backend to mimic the code/wording used there.

Then from the end-user code you can call `ImGui::SetMouseCursor(ImGuiMouseCursor_None)` every frame to overwrite the cursor and this info will be picked by the Freeglut backend and turned into a `glutSetCursor(GLUT_CURSOR_NONE)` call.

**(2) Mouse inputs.**

You can disable mouse inputs in dear imgui by setting `io.ConfigFlags |= ImGuiConfigFlags_NoMouse`, it will ignore mouse position and buttons. You can also set an invalid position (-FLT_MAX, -FLT_MAX) to achieve a similar purpose.

**Comment by ocornut** [comment]
Hello,
I have added a note in imgui_impl_glut.cpp that this not implemented. If someone wants to submit a PR to add support for it using FreeGlut facility I'll merge it. Closing the issue until that.
