### ISSUE TITLE
Line UP

### ISSUE THREAD

**Issue by AlexWhiteS** [ocornut/imgui#2377]
How can I lift the areas marked with the red line up?
![24-02-2019 014412](https://user-images.githubusercontent.com/47930474/53292641-8414de80-37d6-11e9-9f91-7800b0e02e13.png)

**Comment by ocornut** [comment]
I don’t understand the question.

**Comment by AlexWhiteS** [comment]
> Я не понимаю вопроса.

Is there any way to raise the button (INFO) at the level with the button (NEWS)?

**Comment by AlexWhiteS** [comment]
> I don’t understand the question.

Is there any way to raise the button (INFO) at the level with the button (NEWS)?

**Comment by ocornut** [comment]
If you can write code that adds custom widgets and gradients (which you are not providing) surely you must be able to position some text vertically?

I am closing this because you didn’t answer any of the requested information and didn’t follow the contributing guidelines.
