### ISSUE TITLE
mulltiple problems with imgui_impl_vulkan 

### ISSUE THREAD

**Issue by newincpp** [ocornut/imgui#2378]
Hi,
I've been trying to implement imgui in my vulkan renderer lately and I ran into some problems. I'm not sure if the problems come from my code imgui though.
First it would be great to have guidelines somewhere on how should I implement imgui, a bit more comments or some draw that are not imgui in the example would have been really helpful. Looking at those I though I had to draw imgui into separate renderpass but I couldn't so I changed my strategy and put imgui at the end of my main commandBuffer.

Assuming putting imgui in the same commandBuffer as the rest of my draw was the intended design I ran into multiple problems:
First my validation layers were very unhappy to have `CreateOrResizeBuffer` calls between `vkBeginCommandBuffer` and `vkEndCommandBuffer`. It was complaining that I shouldn't change any buffer that is in use in the current command buffer.
So I separated ImGui_ImplVulkan_RenderDrawData in two parts.
I generated a [patch](https://gist.githubusercontent.com/newincpp/00f8f95fedfc04a780bd675e343ff24d/raw/195980fac0b864b1c1e6983decd732e86319dca5/imgui_impl_vulkan.cpp.patch)
the full code is [here](https://git.psychoscientists.com/newin/LunaticPlatypusV2/src/master/LunaticPlatypus/imgui/imgui_impl_vulkan.cpp)
and the code where I use those functions: [here](https://git.psychoscientists.com/newin/LunaticPlatypusV2/src/master/LunaticPlatypus/vkRenderer.cpp)

It kinda made it work on OSX but radv on linux [doesn't really seems to like my code very much](https://twitter.com/newincpp/status/1097135036330115072)
Note that when I was using imgui in a separate renderpass renderdoc was showing that there is no problems displaying fonts or anything. this display problem appeared when I put imgui into my main commandbuffer.

I wonder if I'm doing it wrong since the very beginning or if there is some actual bug inside imgui ?

**Comment by newincpp** [comment]
little update: I updated vulkan today and it seems it fixed the display problem: https://twitter.com/newincpp/status/1101859499504254977 it is now working fine but that only answer a part of this post

**Comment by ocornut** [comment]
Hello @newincpp 

I think those issues are fixed in those branches:

https://github.com/ocornut/imgui/tree/vulkan_fix_master
https://github.com/ocornut/imgui/tree/vulkan_fix_docking

Would you mind giving them a test?

Thank you!

**Comment by newincpp** [comment]
I'm gonna try those branch but I'm breaking a lot of stuff in my engine and I don't have that much time (mainly because this is a project I'm doing on my free time). So I might try this in a few weeks rather days.

**Comment by ocornut** [comment]
The fixes were merged anyway, given the explanation above I'll just assume this is the same issue.
If you still have issues don't hesitate to comment here and I'll reopen the issue.
