### ISSUE TITLE
Keyboard navigation two items focused at the same time with Ctrl+Tab

### ISSUE THREAD

**Issue by tomasiser** [ocornut/imgui#2380]
**Version/Branch of Dear ImGui:**

Version: 1.69 WIP
Branch: master (6f80179a1d45753e7065ea7f79360e8e30e5d115)

**Back-end/Renderer/Compiler/OS**

Back-ends: example_glfw_opengl3

**My Issue/Question:**

_Consider watching the gif, it is less complicated._

1) Run the example from the latest master.
1) In the `ImGui Demo` window, check `NavEnableKeyboard`.
1) Open Widgets -> Basic and click inside `Hello, world!` input.
1) Now in **the other window**, double click inside an input (e.g., `G` of the clear color). This should focus and active the input in the other window.
1) Press Ctrl+Tab to focus to the demo window again.
1) Notice that the focus (blue rectangle) gets into the demo window and the `Hello, world!` input, but the input box in the other window is still active and all keyboard events get passed to this unfocused input.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/10374559/53302888-e962e100-3863-11e9-86d9-bedd064d2d39.png)

![imguiwrongfocus](https://user-images.githubusercontent.com/10374559/53302861-83765980-3863-11e9-9b98-c023ca29a176.gif)

**Comment by ocornut** [comment]
Thank you Tomáš, I confirmed as a bug (it is also a surprisingly old bug).

There's two aspect to the fix, 
- The `// Apply final focus` section of `NavUpdateWindowing()` should probably call `ClearActiveID()`.
- `InputTextEx()` should be able to detect better that its active id has been stolen (there are a few tests in there that are rather short sighted), for things like #701 and maybe other reasons, will need to investigate this a little.

Will look it shortly.

**Comment by ocornut** [comment]
I pushed a fix for this (and wrote a test for it).
