### ISSUE TITLE
Switch case compile error in imggui.cpp

### ISSUE THREAD

**Issue by djwingrove** [ocornut/imgui#2381]
**Version/Branch of Dear ImGui:**
GitHub master

**Back-end/Renderer/Compiler/OS**

Compiler: Visual Studio 17
Operating System: Windows 10 

**My Issue/Question:**

ImGui::LogFinish() line 8919 in imggui.cpp
```
    switch (g.LogType)
    {
    case ImGuiLogType_TTY:
        fflush(g.LogFile);
        break;
    case ImGuiLogType_File:
        fclose(g.LogFile);
        break;
    case ImGuiLogType_Buffer:
        break;
    case ImGuiLogType_Clipboard:
        if (!g.LogBuffer.empty())
            SetClipboardText(g.LogBuffer.begin());
        break;
    }
```
This generates error ```fatal error: enumeration value 'ImGuiLogType_None' not handled in switch```

It needs an extra case statement for ImGuiLogType_None the same way ImGuiLogType_Buffer does.

**Comment by ebachard** [comment]
If I correctly understood the problem, another (imho more usual) way to fix such issue is to use "default" keyword.  Something like below:

 ```
default:
    break;
````

**Comment by ocornut** [comment]
Merged the PR, thank you!
