### ISSUE TITLE
IsMouseClicked has a misleading name

### ISSUE THREAD

**Issue by lubieowoce** [ocornut/imgui#2385]
**My Issue/Question:**

I believe that the name of `IsMouse(Double)Clicked` is misleading. Here's why:

To my mind (and, I think, in common usage), a *click* happens when a mouse button goes `Up -> Down -> Up`.
A click consists of a *press* (`Up -> Down`) and a *release* (`Down -> Up`).
Here's a graph to visualize it:

```
      |
   up |--------.               .------------
 down |        '---------------'
      |_______________|_______________|______ t
            pressed       released
                          clicked
```
A double-click is similar (assuming it fits within `MouseDoubleClickTime`):
```
      |                                     
   up |--------.               .--------------.               .------------
 down |        '---------------'              '---------------'
      |_______________|_______________|_______________|_______________|______ t          
            pressed       released         pressed'       released'
                          clicked                       double-clicked
```
So to me, the name of `IsMouseClicked` suggests that the function returns `true` after the whole (double)click sequence is finished¹. However, the functions actually return `true` when a (double)click has just begun (a `Up -> Down` sequence), i.e. during the *press*:
```
      |
   up |--------.               .------------
 down |        '---------------'
      |_______________|_______________|______ t
            pressed       released
            clicked  <--------              
```

**Possible solution**
I believe it'd be better to rename `IsMouseClicked` to `IsMousePressed` to match the naming and semantics of the corresponding function for keyboard input (`IsKeyPressed`). I'd also rename `IsMouseDoubleClicked` to `IsMouseDoublePressed` or something similar.

It'd also be nice to have functions to tell when a (double)click has ended – to avoid naming conflicts / breaking existing code, they could be called something like `IsMouseClickFinished` or `IsMouseClickComplete`.

---

¹ As a piece of evidence, I spent an afternoon second guessing everything about my input handling while trying to figure out why `IsMouseClicked()` was `true` a frame before the `Button` being clicked on actually registered the click...

**Comment by ocornut** [comment]
Thanks for your post and the delightful ascii art.

The reasoning is not incorrect, but
- In every UI framework the "pressed-then-released" events are tied to a specific context. More specifically, on most button-like type of widgets both the pressed and released events need to happen over the same widget to be registered. What that means is that what you expect from `IsMouseClicked` isn't prossible to achieve without extra information, as it is almost never solely based on mouse information only but relate to the actual UI behind it.
- You state _"and, I think, in common usage"_ but I would argue every engine/sdk use different terminology (which is unfortunate) and "clicked/released" works pretty much just as well. Regardless, for such a commonly used function it would be problematic to rename is at this point without a really strong incentive.
- Also: "IsMouseDoublePressed"

> ¹ As a piece of evidence, I spent an afternoon second guessing everything about my input handling while trying to figure out why `IsMouseClicked()` was `true` a frame before the `Button` being clicked on actually registered the click...

If you are unsure of the behavior or semantic of an imgui call, I suggest just displaying its output `ImGui::Text("%d", ImGui::IsMouseClicked(0))`.

The important question is probably "why do you care in the first place".
While I don't know your original intent, I suspect that you've been looking at mouse events while you may be wanting to look at button behaviors instead. There's an internal `ButtonBehavior()` function which is used by many functions, including `Button()` and `InvisibleButton()` and this provide the common semantic of returning true on the release event if both events happens over the item. Using the later is a common thing in dear imgui. Depending on your goal this might be a better direction to look at?

**Comment by ocornut** [comment]
Ping @lubieowoce

**Comment by ocornut** [comment]
Closing due to lack of answer.
