### ISSUE TITLE
Non-hardware accelerated solutions for an ImGui 2D app

### ISSUE THREAD

**Issue by Twinki14** [ocornut/imgui#2395]
I've been working on a simplistic GUI app using ImGui, and for sometime I've been thinking about the hardware requirements it currently has due to using an OpenGL 3.3 context for rendering.

The app itself is nothing more than just ImGui alone. There isn't any need for 3D rendering, it isn't a modeling/texturing app or for game debug. It's simply a GUI with some basic tasks. It doesn't seem proper to have such a basic app, have such a hardware requirement, and the app itself will be used on non-hardware accelerated systems like your typical run-of-the-mill Windows VPS's. 

I have very little experience with GUI's in general, and even smaller experience with graphics API's. The reason why I've clamored to ImGui is because of how easy it is to write with, understand, and how open it is.

So I guess what i'm looking for is a software rendering solution, that's also cross-platform.

I have given this a shot https://github.com/emilk/imgui_software_renderer but sadly, it doesn't seem to perform all that well to honestly be considered.

**Comment by ocornut** [comment]
For future reference, this section of the wiki lists other software rasterizer:
https://github.com/ocornut/imgui/wiki/Useful-Widgets#software-rendererrasterizer
