### ISSUE TITLE
Button in the same line as a TreeWindow header

### ISSUE THREAD

**Issue by Rush2k** [ocornut/imgui#2396]
Hi,

I'm trying to put a button in the same line as the header of the tree window (eg code below), and I am having issues getting the button to activate reliably. By that I mean; it either needs a lot of clicks to trigger, or it only opens when the tree window is open.

![object_treenode](https://user-images.githubusercontent.com/5002363/53700007-e8213f00-3da2-11e9-8841-0f1fbd7c7518.PNG)

Here's a minimal example code of what I'm doing:
	ImGui::AlignTextToFramePadding();
	bool treeopen = ImGui::TreeNode("TreeTest");
	ImGui::SameLine();
	if (ImGui::Button("+")) ImGui::OpenPopup("ElementList");
	if (ImGui::IsItemHovered()) ImGui::SetTooltip("new element");
	if (ImGui::BeginPopup("ElementList")) {
		ImGui::MenuItem("element 1");
		ImGui::EndPopup();
	}
	if (treeopen)
		ImGui::TreePop();

I tried this instead:
	bool treeopen = ImGui::TreeNodeEx("TreeTest", ImGuiButtonFlags_AllowItemOverlap);

But it actually made opening the tree harder through the arrow.

What's the preferred setup to make this work?

**Comment by ocornut** [comment]
This works for me:

```
ImGui::AlignTextToFramePadding();
bool treeopen = ImGui::TreeNodeEx("TreeTest", ImGuiTreeNodeFlags_AllowItemOverlap);
ImGui::SameLine();
if (ImGui::Button("+")) ImGui::OpenPopup("ElementList");
if (ImGui::IsItemHovered()) ImGui::SetTooltip("new element");
if (ImGui::BeginPopup("ElementList")) 
{
    ImGui::MenuItem("element 1");
    ImGui::MenuItem("element 2");
    ImGui::EndPopup();
}
if (treeopen)
{
    ImGui::Text("Tree contents");
    ImGui::TreePop();
}
```

You said:
"I tried this instead:
bool treeopen = ImGui::TreeNodeEx("TreeTest", **ImGuiButtonFlags_AllowItemOverlap**);"

I think you meant `ImGuiTreeNodeFlags_AllowItemOverlap` and NOT `ImGuiButtonFlags_AllowItemOverlap` here.

You may otherwise have another issue in your real app code where maybe the identifier of the + buttons are conflicting with each others (if you don't use PushID/PopID).

**Comment by Rush2k** [comment]
Thank you! It was a combination of ID issues and incorrect flags.
