### ISSUE TITLE
Use of custom IsWindowsVersionOrGreater instead of default IsWindows10OrGreater?

### ISSUE THREAD

**Issue by zzzyap** [ocornut/imgui#2401]
Something minor we noticed in the win32 example:
https://github.com/ocornut/imgui/blob/8414c0bb096a767775efc507c56f87b7fe3d8d35/examples/imgui_impl_win32.cpp#L392-L402

Is there a particular reason this is used instead of the default windows versions?
https://docs.microsoft.com/en-us/windows/desktop/api/VersionHelpers/nf-versionhelpers-iswindows10orgreater
https://docs.microsoft.com/en-us/windows/desktop/api/versionhelpers/nf-versionhelpers-iswindows8point1orgreater

**Comment by ocornut** [comment]
As mentioned in the comment above it, this is designed to allow compiling with earlier Windows SDK.

In fact, most of the code below exist to 1) allow compiling with earlier Windows SDK (while support for the features offered by Windows 10) or 2) allow running with earlier Windows version. 

This sort of scheme is often used by librairies (e.g. glfw) to maximize portability.

**Comment by ocornut** [comment]
If your problem is that you have conflict in unity builds we can certainly rename them.

**Comment by zzzyap** [comment]
I believe the default ones goes all the way back to vista and also has a wrapper for the generic major, minor, service pack version (https://docs.microsoft.com/en-us/windows/desktop/api/versionhelpers/nf-versionhelpers-iswindowsversionorgreater). 

Its not a problem just curiosity.

**Comment by ocornut** [comment]
The underlying VerifyVersionInfoW() is part of Vista but IsWindowsVersionOrGreater() doesn't seem to be part of SDK 7.0a which is used by Visual Studio 2010 (currently my oldest target\*).

![image](https://user-images.githubusercontent.com/8225057/53828797-f035d600-3f7e-11e9-863d-d39dc9dd90ec.png)

![image](https://user-images.githubusercontent.com/8225057/53828721-be247400-3f7e-11e9-8e76-72fc3496af51.png)

\* Arguably it would be nice at some point to aim for a newer oldest target, I'll ask around.
