### ISSUE TITLE
How to write Vietnamese in imgui

### ISSUE THREAD

**Issue by huyluong2345** [ocornut/imgui#2403]
i can't write Vietnamese in imgui, some characters work, some characters are replaced by "?"
Ex: ImGui::Text(u8"Nguyên Đông Dương");
Result:
![image](https://user-images.githubusercontent.com/48280785/53876088-9f82b380-4038-11e9-9951-1630a9338e48.png)

I hope everyone will help me, thank you very much

**Comment by ocornut** [comment]
Hello,

You need to load a font that contains the Vietnamese characters, and load the glyph ranges required for the language, e.g. http://vietunicode.sourceforge.net/charset/.

Please read the misc/fonts/README.txt file about font loading.

**Comment by huyluong2345** [comment]
can you help me, i dont know how to make glyph ranges for vietnam, and i dont find out font for vietnam have character such as "ư" "ơ"....

**Comment by ocornut** [comment]
I have added a `GetGlyphRangesVietnamese()` function containing the glyphs listed in the link I pasted above.

The first font I tried had the glyphs in there:
`io.Fonts->AddFontFromFileTTF("../../misc/fonts/Roboto-Medium.ttf", 16.0f, NULL, io.Fonts->GetGlyphRangesVietnamese());`

![image](https://user-images.githubusercontent.com/8225057/54157873-7f446180-4449-11e9-9376-4c7e00eb71a3.png)

`io.Fonts->AddFontFromFileTTF("../../misc/fonts/DroidSans.ttf", 16.0f, NULL, io.Fonts->GetGlyphRangesVietnamese());`

![image](https://user-images.githubusercontent.com/8225057/54157937-b3b81d80-4449-11e9-9d44-470e88bbfcaa.png)

`io.Fonts->AddFontFromFileTTF("NotoMono-Regular.ttf", 16.0f, NULL, io.Fonts->GetGlyphRangesVietnamese());`

![image](https://user-images.githubusercontent.com/8225057/54158019-e2ce8f00-4449-11e9-912e-ebbc9cc39672.png)

**Comment by huyluong2345** [comment]
yeah tks very much

**Comment by dominota** [comment]
@huyluong2345 You can display Vietnamese characters with ImGui::Text but what about ImGui::Inputtext function? I face this problem when trying to type Vietnamese character from keyboard. I use [Unikey ](https://www.unikey.org/en/)with Telex mode. I type "**hà nội**" but i get "**haà noôiội**"
@ocornut can you please tell me some hints

![keyboard](https://user-images.githubusercontent.com/54459455/87404654-a0dacd80-c5e8-11ea-8a3b-dda1186309f1.png)

**Comment by duyxoan0307** [comment]
@dominota I had the same problem as you, did you find the solution?

**Comment by dominota** [comment]
@duyxoan0307 can apply vietnamese for ui elements excepting text edit.

**Comment by duyxoan0307** [comment]
> @duyxoan0307 can apply vietnamese for ui elements excepting text edit.

I must use Copy + Paste from Notepad to use text edit in Vietnamese, hope this library will support soon, thanks for your reply :D

**Comment by Basilisvirus** [comment]
I am late for the reply, but as someone new to C++ programming, It it not obvious for new programmers that, you can build your own glyphs using the already-existing answer here: https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-and-input-non-latin-characters-such-as-chinese-japanese-korean-cyrillic.

So for example I wanted to build Greek letters. I do the below:

```
        // Or create your own custom ranges (e.g. for a game you can feed your entire game script and only build the characters the game need)
        ImVector<ImWchar> ranges;
        ImFontGlyphRangesBuilder builder;
        builder.AddText(u8"ΑΆαάΒβΓγΔδΕΈεέΖζΗΉηήΘθΙΊιίΚκΛλΜμΝνΞξΌΟόοΠπΡρΣσςΤτΥΎυύΦφΧχΨψΩΏωώ"); //adding all greek letters variations
        builder.AddChar(0x7262);                               // Add a specific character (not sure if needed)
        builder.AddRanges(io.Fonts->GetGlyphRangesJapanese()); // Add one of the default ranges
        builder.BuildRanges(&ranges);                          // Build the final result (ordered ranges with all the unique characters submitted)
        io.Fonts->AddFontFromFileTTF("../../misc/fonts/ClearSans-Regular.ttf", 16.0f, NULL, ranges.Data);

        // Retrieve texture in RGBA format (are the below needed? not sure)
        //unsigned char* tex_pixels = NULL;
        //int tex_width, tex_height;
        //io.Fonts->GetTexDataAsRGBA32(&tex_pixels, &tex_width, &tex_height);
        //io.Fonts->GetTexDataAsAlpha8(&tex_pixels, &tex_width, &tex_height);
```
