### ISSUE TITLE
Modal windows do not recenter when OS window resizes

### ISSUE THREAD

**Issue by hyperum** [ocornut/imgui#2405]
**Version/Branch of Dear ImGui:**

Version: v1.61 WIP
Branch: master

**My Issue/Question:**

Modal popups do not center themselves when the OS window is resized. This is mildly annoying at best, but when the window is resized to a small enough size, the modal popup can no longer be seen.

I've isolated the problem to imgui.cpp/5035:
```
SetNextWindowPos(g.IO.DisplaySize * 0.5f, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
```
Which can be replaced by:
```
SetNextWindowPos(g.IO.DisplaySize * 0.5f, ImGuiCond_Always, ImVec2(0.5f, 0.5f));
```
to get the expected behavior.

I'm not suggesting this is the optimal solution. Setting the position on every call is probably not ideal. 

EDIT: Removed section I realized was wrong. Is this a wontfix? Are users expected to modify this behavior on a case-by-case basis?

**Comment by ocornut** [comment]
The problem with using `ImGuiCond_Always` is that it will make it impossible for the user move the window.

You should however be able to call `SetNextWindowPos(g.IO.DisplaySize * 0.5f, ImGuiCond_Always, ImVec2(0.5f, 0.5f));` on your first before the call to `BeginPopupModal()`, as it doesn't overwrite the previous SetNextWindowPos call value if there is one.
