### ISSUE TITLE
Docking: negative enum value compared against char

### ISSUE THREAD

**Issue by nkross** [ocornut/imgui#2408]
**Version/Branch of Dear ImGui:**

Version: 1.69 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom
Compiler: clang toolchain (Android NDK)
Operating System: Android

**My Issue/Question:**

On the `docking` branch, `ImGuiDockNodeSettings::SplitAxis` is of type `char` but one of its possible values is `ImGuiAxis_None` (-1).

When building for Android using the NDK toolchain, `char` is unsigned so checking for equality with `ImGuiAxis_None` causes a compilation error:
https://github.com/ocornut/imgui/blob/docking/imgui.cpp#L13677

This could be fixed by changing the type of `ImGuiDockNodeSettings::SplitAxis` to `signed char`.

**Comment by ocornut** [comment]
I'll fix this but honestly:

> When building for Android using the NDK toolchain, char is unsigned

This is absolutly freaking me out and I'm sure there are other problems waiting to be found if that's the case.

**Comment by PathogenDavid** [comment]
> This is absolutly freaking me out

Fun piece of trivia to bring up at parties and horrify coworkers: The C/C++ standards leave it up to the implementation to decide whether or not `char` is signed or not.

Most (all?) compilers even let you change it. For example [`/J` in MSVC](https://docs.microsoft.com/en-us/cpp/build/reference/j-default-char-type-is-unsigned) or `-fsigned-char` in GCC/Clang (although it's undocumented in Clang.)
