### ISSUE TITLE
Incorrect parent viewport ID

### ISSUE THREAD

**Issue by Hedanito** [ocornut/imgui#2409]
**Version/Branch of Dear ImGui:**

Version: 1.69 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom
Compiler: Visual Studio 2017
Operating System: Windows

**My Issue/Question:**

As you can see in the following screenshot, all viewports get the main viewport as their parent, even though the tooltip (viewport #4) should be a child of the demo window (viewport #3):
![image](https://user-images.githubusercontent.com/768069/53981191-5bfc7800-4112-11e9-90f4-4244af3d8ad5.png)

In practice this can result in some incorrect behaviour with the operating system's window manager. When applying this parenting in Windows it will cause undesired Z-ordering, moving the tooltip as well as the main viewport in front of the demo window.
![image](https://user-images.githubusercontent.com/768069/53980878-b77a3600-4111-11e9-8984-7e5e5a500452.png)

**Comment by ocornut** [comment]
Hello @Hedanito, thanks for reporting this.
I now have applied a change to set the parent viewport correctly for popups and tooltips.

**Comment by Hedanito** [comment]
It works, thank you for the quick fix.

![image](https://user-images.githubusercontent.com/768069/54231626-250ad580-4509-11e9-9020-cc14cd98577e.png)
