### ISSUE TITLE
Combo box bug when a text widget is focused

### ISSUE THREAD

**Issue by apessino** [ocornut/imgui#241]
There is an easy-to-repro problem selecting a combo box if any text input widget has the focus. If text input is active clicking on a combo box does not open it, rather it flashes for one frame and then closes again.

To reproduce:

1) show the test window
2) open the "widgets" header
3) ctrl+click in any of the input fields so that you can enter text to set the value (any sort of text input being active in any widget type that supports it will cause the problem).
4) now click on the combo box: what you get is a flash as the combo box is visualized and immediately hidden, to actually open it you have to click on it again.

Not the biggest bug in the world, but hopefully not difficult to fix either. :)

A=

**Comment by ocornut** [comment]
Thanks, looking into it. Curiously it seems like a very old bug.

**Comment by ocornut** [comment]
I made the simple fix. I will however rework Combo to use the new popup facility, it'll be more consistent.

**Comment by apessino** [comment]
Cool – thanks! :)
