### ISSUE TITLE
Shouldn't be there ImGui::SetTabItemSelected?

### ISSUE THREAD

**Issue by darkgnostic** [ocornut/imgui#2410]
Version: 1.69 WIP
Branch: master

I have following situation: I have two tabs, and first one is selected. I need to select *second one* programatically.
Problem is easily solved by adding one pending uid flag, and then selecting the tab by adding ImGuiTabItemFlags_SetSelected.
If I understand well (in snippet below) this would happen:

 - On first iteration ImGui::BeginTabItem it will return true since it is selected
 - On a second iteration it will also select  tab item and return true. Do we have in this case two select tab items? Of course this will happen on only one frame and on next frame only second will be selected.

I saw in imgui_demo.cpp that there is ImGui::SetTabItemClosed to notify tab bar that tab item is closed. Shouldn't be there ImGui::SetTabItemSelected function as well?

**Code snippet** 
```
ImGui::Begin("Example Snippet");
for (unsigned i = 0; i < documents_.size(); i++) {
  
  auto* doc = &documents_[i];
  ImGuiTabItemFlags_ flag = ImGuiTabItemFlags_None;
 
   // pending selection uid is uid of tab that need to be selected programatically
  if (pending_selection_uid_== doc->uid_) {
      flag = ImGuiTabItemFlags_SetSelected;
      pending_selection_uid_ = 0;
 }

   if (ImGui::BeginTabItem(doc->Title().c_str(), &doc->opened_, flag))  {
     ImGui::EndTabItem();
    }
}

ImGui::End();
```

**Comment by ocornut** [comment]
> - On first iteration ImGui::BeginTabItem it will return true since it is selected
> - On a second iteration it will also select tab item and return true. Do we have in this case two select tab items? Of course this will happen on only one frame and on next frame only second will be selected.

I'm not sure I understand those two lines, or maybe there is an error in them.
Do you mean your problem is that using `ImGuiTabItemFlags_SetSelected` means the selection will be delayed by one extra frame?

We could add such function but it wouldn't vastly simplify your code, since you'd need to call `SetTabItemSelected()` in the context of the tab bar (inside the BeginTabBar/EndTabBar block) either way at which point the difference is adding a local variable and an extra test. It would however remove that one frame delay for the selection (I'd be interested in knowing in which case this will make a difference, and how you are currently using `ImGuiTabItemFlags_SetSelected`?)

**Comment by darkgnostic** [comment]
So this is my current situation:

When I open a new document in my app, I wanted to make newly opened document automatically selected. In case when I have no open documents, there is no problem. When there is at least one then the problem occurs. Maybe *the problem* is a bit harsh word, misbehavior would be nicer.

Currently my loop looks like this.

```
for (unsigned i = 0; i < documents_.size(); i++) {

	auto* doc = &documents_[i];

	auto flag = doc->IsDirty() ? ImGuiTabItemFlags_UnsavedDocument : 0;
	if (pending_selection_uid_ == doc->uid_) {
		pending_selection_uid_ = 0;
		
		flag |= ImGuiTabItemFlags_SetSelected;
	}

	if (ImGui::BeginTabItem(doc->Title().c_str(), &doc->opened_, flag)){
		active_document_uid_ = doc->uid_;
		ImGui::EndTabItem();
	}
}
```

Every document has its own `uid_` to distinguish one document from another, and I hold active document uid in `active_document_uid_`.

`pending_selection_uid_ ` will be the next tab that need to be selected (since I can't select document other way). I load document at some other point in the app then set  there `pending_selection_uid_ ` to uid of newly created document.

After loading, when I render the tabs, my tab no.0 is rendered selected (previous state), then on i = 1 I find that `pending_selection_uid_ ` is newly loaded document, so i give it selected flag (tab no.1). At this point I presume, both of tabs will be rendered selected. Then on next render frame only tab 1 will be rendered selected. 

By introducing SetTabItemSelected, first if statement would be obsolete as well as `pending_selection_uid_` member variable. Not that I need badly SetTabItemSelected function :) it works flawlessly this way. Just it seemed logical if you have function that notifies ImGUI when tab is closed from some other part of code, there is a missing function that notifies ImGUI when tab is selected from some other part of code.

You can close this issue if you find it obsolete, this issue was actually the question.

**Comment by ocornut** [comment]
> When I open a new document in my app, I wanted to make newly opened document automatically selected. 

Wouldn’t just using `ImGuiTabBarFlags_AutoSelectNewTabs` solve your problem?

**Comment by ocornut** [comment]
> At this point I presume, both of tabs will be rendered selected. Then on next render frame only tab 1 will be rendered selected.

Also: this is not the case, only 1 tab will be rendered selected and it is locked during the BeginTabBar and Layout process prior to the submission of the first tab item.

The reason `SetTabItemClosed()` exist is that this is currently the only possible way to provide a glitch-free experience, so you can close one tab and stop submiting it, and in the next frame display the contents of another yet without going through a frame where no tab contents are displayed.

I don't disagree that `SetTabItemSelected()` would be a minor convenience but my role is also to question every new API added. It would only turn 3-4 lines of code into 1, not remove any complexity, and above all I think in your situation you want to use `ImGuiTabBarFlags_AutoSelectNewTabs` and then none of this would matters.

**Comment by darkgnostic** [comment]
Somehow I have missed `ImGuiTabBarFlags_AutoSelectNewTabs` flag. Yes, this completely solves my issue. Thank you for your time.
