### ISSUE TITLE
Problems when attempting to reset my docking layout.

### ISSUE THREAD

**Issue by SSBMTonberry** [ocornut/imgui#2414]
Hello!
I got a piece of code that used to work in an older version of the docking branch, but I updated it the 23rd of february, and since then it crashes when I call `resetDock()`. Previously I used one of the first public versions of the docking branch, from October or something last year. Do you see anything that might cause it? 
`drawDock()` is running every frame, and works fine. So does `createDock()` when ran at the start of the program, but `resetDock()`, which is used to reset the layout, crashes when called (it is called manually by a button press). If it matters, I'm using Arch Linux as OS.

Here is my code:
```c++
void ProgramManager::drawDock()
{
    bool open = true;

    ImGuiWindowFlags window_flags = ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoDocking;
    ImGuiViewport* viewport = ImGui::GetMainViewport();
    ImGui::SetNextWindowPos(viewport->Pos);
    ImGui::SetNextWindowSize(viewport->Size);
    ImGui::SetNextWindowViewport(viewport->ID);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
    window_flags |= ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove;
    window_flags |= ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus;

    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
    ImGui::Begin(DOCK_ROOT_ID.c_str(), &open, window_flags);
    ImGui::PopStyleVar();

    ImGui::PopStyleVar(2);

    if (ImGui::DockBuilderGetNode(ImGui::GetID(DOCKSPACE_ID.c_str())) == nullptr)
    {
        createDock();
    }

    ImGui::PushStyleColor(ImGuiCol_DockingEmptyBg, {35, 65, 90, 255});
    ImGuiID dockspace_id = ImGui::GetID(DOCKSPACE_ID.c_str());
    ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), 0);
    ImGui::PopStyleColor();
    ImGui::End();
}

void ProgramManager::createDock()
{
    ImGuiID dockspace_id = ImGui::GetID(DOCKSPACE_ID.c_str());
    ImGuiViewport* viewport = ImGui::GetMainViewport();

    ImGui::DockBuilderRemoveNode(dockspace_id); // Clear out existing layout
    ImGui::DockBuilderAddNode(dockspace_id); //viewport->Size); // Add empty node

    ImGuiID dock_main_id = dockspace_id; // This variable will track the document node, however we are not using it here as we aren't docking anything into it.
    ImGuiID dock_id_left = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Left, 0.20f, nullptr, &dock_main_id);
    ImGuiID dock_id_right = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Right, 0.20f, nullptr, &dock_main_id);
    ImGuiID dock_id_bottom = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Down, 0.20f, nullptr, &dock_main_id);

    //ImGui::DockBuilderDockWindow(SystemLog::ID.c_str(), dock_id_bottom);
    //ImGui::DockBuilderDockWindow(FormManager::PROPERTY_EDITOR_ID.c_str(), dock_id_right);
    //ImGui::DockBuilderDockWindow(FormManager::PROJECT_EXPLORER_ID.c_str(), dock_id_left);
    //ImGui::DockBuilderDockWindow("Extra", dock_id_prop);

    ImGui::DockBuilderDockWindow(fmt::format("dummy###{0}", FilelistForm::ID).c_str(), dock_id_left);
    ImGui::DockBuilderDockWindow(fmt::format("dummy###{0}", AudioPlayerForm::ID).c_str(), dock_main_id);
    ImGui::DockBuilderDockWindow(fmt::format("dummy###{0}", PlaylistForm::ID).c_str(), dock_id_right);
    ImGui::DockBuilderDockWindow(SystemLog::ID.c_str(), dock_id_bottom);
    ImGui::DockBuilderFinish(dockspace_id);
}

void ProgramManager::resetDock()
{
    bool open = true;


    ImGuiWindowFlags window_flags = ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoDocking;
    ImGuiViewport* viewport = ImGui::GetMainViewport();
    ImGui::SetNextWindowPos(viewport->Pos);
    ImGui::SetNextWindowSize(viewport->Size);
    ImGui::SetNextWindowViewport(viewport->ID);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
    window_flags |= ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove;
    window_flags |= ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus;

    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
    ImGui::Begin(DOCK_ROOT_ID.c_str(), &open, window_flags);
    ImGui::PopStyleVar();

    ImGui::PopStyleVar(2);

    createDock();

    ImGui::PushStyleColor(ImGuiCol_DockingEmptyBg, {35, 65, 90, 255});
    ImGuiID dockspace_id = ImGui::GetID(DOCKSPACE_ID.c_str());
    ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), 0);
    ImGui::PopStyleColor();
    ImGui::End();

    SystemLog::get()->addDebug("Layout has been reset.");
}
```
The crash points me here:
![image](https://user-images.githubusercontent.com/26206421/53761955-1435e080-3ec7-11e9-987f-b07206b895fb.png)

Which got there through createDock(), which this time was called in resetDock():
![image](https://user-images.githubusercontent.com/26206421/53762043-4fd0aa80-3ec7-11e9-8ed5-bdd8d5838622.png)

_Originally posted by @SSBMTonberry in https://github.com/ocornut/imgui/issues/2109#issuecomment-469416002_

**Comment by ocornut** [comment]
`DockBuilderRemoveNode()` begins with:
```
    ImGuiDockNode* node = DockContextFindNodeByID(ctx, node_id);
    if (node == NULL)
        return;
```
before calling DockBuilderRemoveNodeDockedWindows, DockBuilderRemoveNodeChildNodes, DockContextRemoveNode, so it is surprising the assert on DockContextRemoveNode would fail.

It would be useful to get closer a repro for the bug (code + ini file), or you can try stepping through `DockBuilderRemoveNode()` to understand the issue.

**Comment by ocornut** [comment]
Hello Robin,

I understand the issue better now. There are in fact two issues.

1) When you ported your code to the new signature for `DockBuilderAddNode`, instead of:
```
ImGui::DockBuilderAddNode(dockspace_id); //viewport->Size); // Add empty node
```
You should use:
```
ImGui::DockBuilderAddNode(dockspace_id, ImGuiDockNodeFlags_Dockspace); // Add empty node
ImGui::DockBuilderSetNodeSize(dockspace_id, viewport->Size);
```
The `ImGuiDockNodeFlags_Dockspace` flag here before was automatic, but now we can create dock node that are floating window so this difference is important. I added an extra comment because even though I mentioned thatr signature and behavior change in main thread it is easy to miss.

This will fix your issue.

2) I pushed a fix for a bug in the `DockBuilderRemoveNode()` that effectively led root-dockspace-that-have-no-central-node to be deleted. With the fix above this will not happen anyway.

In my repro I noticed a flickering of some scrollbar (e.g. where you have your "system log" window) which I have added to my list of things to investigate.

Thanks for the report!

**Comment by ocornut** [comment]
> In my repro I noticed a flickering of some scrollbar (e.g. where you have your "system log" window) which I have added to my list of things to investigate.

Also fixed this other issue.

**Comment by SSBMTonberry** [comment]
Excellent work as always, Omar! Well spotted!
Sadly I've been too busy to be able to touch my code today, but I'll update it all tomorrow and see how it goes :)

Thank you for your quick response and dedication! It's greatly appreciated!

**Comment by SSBMTonberry** [comment]
Btw, I can verify that the latest changes fixed the problem! Thank you very much, again! :)
