### ISSUE TITLE
SetWindowPos incorrect results in multi display

### ISSUE THREAD

**Issue by seoyeon01** [ocornut/imgui#2415]
**Version/Branch of Dear ImGui:**

Version: 1.69 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl2.cpp + imgui_impl_glfw.cpp 
Compiler: Visual Studio 2017
Operating System: Win10

**My Issue/Question:**
**Screenshots/Video**

When moving the location using SetWindowPos on a dual monitor, 
the result is unintended as shown in the picture below.

case1 ) window located on monitor1
![img1](https://user-images.githubusercontent.com/48429544/54105769-60c57280-4417-11e9-9ea2-9a56d8d9fa80.jpg)

![img2](https://user-images.githubusercontent.com/48429544/54106163-a171bb80-4418-11e9-8d21-1b31d723cc85.jpg)

case2 ) window located on monitor2
![img3](https://user-images.githubusercontent.com/48429544/54106345-2230b780-4419-11e9-9f90-02a2cf1c058c.jpg)
![img4](https://user-images.githubusercontent.com/48429544/54106346-22c94e00-4419-11e9-8ae3-9823698bdb06.jpg)

case3) window located on monitor2 + different size window
![img5](https://user-images.githubusercontent.com/48429544/54106347-22c94e00-4419-11e9-8d49-4c655750ee94.jpg)

![img6](https://user-images.githubusercontent.com/48429544/54109634-886e0800-4422-11e9-9ba7-0175f859b933.jpg)

**Standalone, minimal, complete and verifiable example:** 
```
// Please do not forget this!
ImGui::Begin("Example Bug");

if( ImGui::Button( "set pos ( 0, 0 )" ) )
    ImGui::SetWindowPos( ImVec2( 0, 0 ) );
ImGui::Text( "pos : %.f, %.f", ImGui::GetWindowPos().x, ImGui::GetWindowPos().y );
ImGui::Text( "size : %.f, %.f", ImGui::GetWindowSize().x, ImGui::GetWindowSize().y );

ImGui::End();
```
I searched for articles of FAQs, Readme, posted same issue etc... but couldn't find them
i'm sorry if i missed it

Thank you always.

**Comment by ocornut** [comment]
It looks like the window is being clamping within the bound of the same monitor.

Please note that using `SetWindowPos()` is never recommended, you should use `SetNextWindowPos()`, but I agree there seem to be a bug in there anyway.

**Comment by ocornut** [comment]
I pushed a fix to this bug now.
In your case the window coordinates were clamped within the previous monitor.
