### ISSUE TITLE
Window stop refreshing when main viewport minimized (glfw backend)

### ISSUE THREAD

**Issue by seoyeon01** [ocornut/imgui#2416]
**Version/Branch of Dear ImGui:**

Version: 1.69 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl2.cpp + imgui_impl_glfw.cpp 
Compiler: Visual Studio 2017
Operating System: Win10

**My Issue/Question:**
**Screenshots/Video**

![3](https://user-images.githubusercontent.com/48429544/54108806-45129a00-4420-11e9-9c82-382d8193c9c1.gif)

1) minimize main window
2) resize other viewport
3) window turns black

**Standalone, minimal, complete and verifiable example:** 
```
// Please do not forget this!
ImGui::Begin("test window");
// just begin~end window also have same issue(in gif example)
ImGui::End();
```

**Comment by ocornut** [comment]
Hello,
I noticed this happen with the GLFW backend but this has nothing to do with resizing. If you display anything in those window you'll notice they are not refreshed at all when the parent is minimized. This needs to be investigated.

**Comment by seoyeon01** [comment]
You're right.

I know that the rules here only deal with the contents of the imgui, 
and not with anything else."(Glfw, opensl, directX etc...)
But for the purpose of resolving the current problem (at least temporarily).
I'm going to talk about options for GLFW.

For your precious time.
The story I'm going to tell you below is temporary and my immature way of doing things.
(This is also the story of the GLFW Option.
 That's why I don't write new articles. and use long comment...)
If you're looking for the right solution, you don't read it.
You'd better move on.

If you are interested, I would appreciate it 
if you could read it and offer a better solution.

**Comment by seoyeon01** [comment]
To solve this problem without modifying the code of imgui 
as much as possible (backend bind, imgui.h/cpp etc), I used the following methods:
(I think this method is messy and can cause other problems.
But it can be achieved to act in the way it is intended.)

point is
1. don't use main window(hide)
2. make other window and use it like a main window

When create window :
glfwWindowHint(GLFW_VISIBLE, false );
window = glfwCreateWindow (1, 1, title_name, NULL );

And don't use the main window.(it is invisible and 1x1 pixel)
(because if size is bigger than 1x1, your new window can included in invisible window)

You can create a window that has a main window as a parent.
( ImGui::Begin ~ End() )
Use the new window as the main window.

There are several reasons for doing this stupid thing.
it can help slove the many problem of GLFW things...

like border issue, render issue, task bar issue,,, many many issue.....
(caused by my inept ability. and GLFW problem)

for example
(You don't have to read. But I'd appreciate it if you could give me a better solution.)
-- boder issue ---------------------------------
I dont want to use the default border(button of the window 
and the binder that displays the name)

i want to use my custom border and
can resize, move like other window.(like adobe photoshop)

it need "glfwWindowHint( GLFW_DECORATED, GLFW_FALSE );"
but! there is many restrictions.
cant move, cant resize, fix position at ( 0, 0 )..

if you want border function(move, resize, basic thing) and custom border
u will made all function and callback etc........

but. there is easy way to solve problem.
use ImGui docking and don't use main window,
make new window and use it as main window.

and customizing style, make border u want.
it can resize, move, minimize, maximize with out
make all function! 

--------
anyway..
this solution is work.

and it can solve this refreshed issue(temporarily)

**Comment by ocornut** [comment]
Thank you. I will investigate this further, as I don't understand why the issue is happening.
As we strive to support multi-viewport with our default backends and GLFW is popular, I want to fix it.

**Comment by ocornut** [comment]
I have fixed this bug now!

(The fix is a little short-sighted as I don't want to incorporate the full DPI/framebufferscale design in the viewport/docking branch just yet, but it does the job.)
