### ISSUE TITLE
Viewport windows do not activate on click if NoTaskBarIcon and NoDecoration are true

### ISSUE THREAD

**Issue by PathogenDavid** [ocornut/imgui#2420]
(This is applicable to the docking branch when utilizing the viewports feature #1542)

When `ConfigViewportsNoTaskBarIcon` and `ConfigViewportsNoDecoration` are both set to true, `ImGuiViewportFlags_NoFocusOnClick` is applied to all non-primary viewports. This was done in [e1143377c2621184551d1dcac136e7e4a76e409b](https://github.com/ocornut/imgui/commit/e1143377c2621184551d1dcac136e7e4a76e409b) to prevent short-lived viewports like combo box dropdown form stealing focus.

An unfortunate side-effect of this on Windows is that if another window is occluding a viewport window, clicking on that viewport window will not bring it to the front.

For example, in the following screenshot Notepad has focus. If I click on the ImGui Demo window, it does not react to the mouse input. If I modify `imgui_impl_win32.cpp` to remove the `WM_MOUSEACTIVATE` handling, it comes to the front as expected.

![image](https://user-images.githubusercontent.com/278957/54348543-3fcb7000-4617-11e9-8f12-74d28bdc400b.png)

The logic which controls this flag is on [imgui.cpp:5620](https://github.com/ocornut/imgui/blob/b1af4d36ce1506b34b8f89dc1a038ec4c5fdbbdd/imgui.cpp#L5620-L5621).

It's not clear to me the most ideal way to fix the issue. The first thing that came to mind was to change the logic so that `ImGuiViewportFlags_NoFocusOnClick` isn't applied to viewports which are children of the main viewport, but I don't know enough about ImGui to know whether that'd have unintended side-effects.

Alternatively, maybe instead of checking the `ImGuiViewportFlags_NoDecoration` flag, it should check the flags that trigger `NoDecoration` instead?

Something like this:

```cpp
// Update common viewport flags
ImGuiViewportFlags viewport_flags = (window->Viewport->Flags) & ~(ImGuiViewportFlags_TopMost | ImGuiViewportFlags_NoTaskBarIcon | ImGuiViewportFlags_NoDecoration);
bool isFloatingWindow = (flags & (ImGuiWindowFlags_ChildMenu | ImGuiWindowFlags_Tooltip | ImGuiWindowFlags_Popup)) != 0;
if (flags & ImGuiWindowFlags_Tooltip)
    viewport_flags |= ImGuiViewportFlags_TopMost;
if (g.IO.ConfigViewportsNoTaskBarIcon || isFloatingWindow)
    viewport_flags |= ImGuiViewportFlags_NoTaskBarIcon;
if (g.IO.ConfigViewportsNoDecoration || isFloatingWindow)
    viewport_flags |= ImGuiViewportFlags_NoDecoration;
if (isFloatingWindow)
    viewport_flags |= ImGuiViewportFlags_NoFocusOnAppearing | ImGuiViewportFlags_NoFocusOnClick;
```

(Once again, not sure if this has any unintended consequences or missing edge-cases with this solution.)

**Comment by ocornut** [comment]
Hello @PathogenDavid,

Thanks for the report. I agree with your conclusion and believe your suggestion is the best thing to do right now. I pushed an equivalent change with a more detailed comment.

**Comment by PathogenDavid** [comment]
No problem, thanks a lot for the fix!
