### ISSUE TITLE
Error imgui GLSL 4.40

### ISSUE THREAD

**Issue by Zukhruf** [ocornut/imgui#2421]
Version: 1.69
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl.cpp
Compiler: Visual Studio, C++ 11
Operating System: windows 10

**My Issue/Question:**

I Try to add GUI on my animation engine program. But when adding ImGui for opengl3 sdl2, I always have error at glGetIntegerv(GL_ARRAY_BUFFER_BINDING, &last_array_buffer);, and the error says, Access violation executing location 0x0000000000000000. Before adding imgui, my program works fine. I search some solution on the internet, but none of those are works. 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/17612617/54427556-6f7c9400-474d-11e9-969b-393f02eea527.png)

**Standalone, minimal, complete and verifiable example:** 
```
bool    ImGui_ImplOpenGL3_CreateDeviceObjects()
{
    // Backup GL state
    GLint last_texture, last_array_buffer;
    glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture);
    glGetIntegerv(GL_ARRAY_BUFFER_BINDING, &last_array_buffer); <-- Error at this line
#ifndef IMGUI_IMPL_OPENGL_ES2
    GLint last_vertex_array;
    glGetIntegerv(GL_VERTEX_ARRAY_BINDING, &last_vertex_array);
#endif 
}
```

**Comment by ocornut** [comment]
You have probably not initialized the GL functions pointers of the GL function loaders that is used by imgui_impl_opengl3.cpp (by default we use gl3w)

**Comment by ocornut** [comment]
I made a few changes to imgui_impl_opengl3.cpp to help users understand what they have made this mistake of not initializing the GL function loader.

Please refer to the examples/ main.cpp files for a working application.

**Comment by Jaumeavinyo** [comment]
Hi! have a similar problem with gladLoadGL() wich now i sopose it is called gladLoadGLLoader() as I can see in glad.c. My problem is a access violation with the variable  "last_active_texture". the thing is that after adding gladloader in my code, The problem persist

[ERROR HERE](https://prnt.sc/19j2ogx)
[gladLoadGL screenshot](https://prnt.sc/19j34h8)

**Comment by ocornut** [comment]
@Jaumeavinyo What's your version and the most recent date at the top of your imgui_impl_opengl3.cpp ?
Can you step in `ImGui_ImplOpenGL3_Init()` and confirm the values of GlVersion and the value of the `gl_loader` string defined near the end of that function?

**Comment by Jaumeavinyo** [comment]
I downloaded the 1.81 imGui release from your repo. The most recent date in the change log of the file imgui_impl_opengl3.cpp is:
//  2021-XX-XX: Platform: Added support for multiple windows via the ImGuiPlatformIO interface.
//  2021-01-03: OpenGL: Backup, setup and restore GL_STENCIL_TEST state.

the glsl version string is: "#version 130" and the value of the gl_loader string is unknown because I don't really think I understand where does the inside function of the loader get the string from

[image here](https://prnt.sc/19j58e3)

**Comment by Jaumeavinyo** [comment]
pd: thanks for the hyper fast attention to my post!

**Comment by ocornut** [comment]
The code in `ImGui_ImplOpenGL3_Init()` has this block:

```
    // Debugging construct to make it easily visible in the IDE and debugger which GL loader has been selected.
    // The code actually never uses the 'gl_loader' variable! It is only here so you can read it!
    // If auto-detection fails or doesn't select the same GL loader file as used by your application,
    // you are likely to get a crash below.
    // You can explicitly select a loader by using '#define IMGUI_IMPL_OPENGL_LOADER_XXX' in imconfig.h or compiler command-line.
    const char* gl_loader = "Unknown";
    IM_UNUSED(gl_loader);
#if defined(IMGUI_IMPL_OPENGL_LOADER_GL3W)
    gl_loader = "GL3W";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLEW)
    gl_loader = "GLEW";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLAD)
    gl_loader = "GLAD";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLAD2)
    gl_loader = "GLAD2";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLBINDING2)
    gl_loader = "glbinding2";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLBINDING3)
    gl_loader = "glbinding3";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_CUSTOM)
    gl_loader = "custom";
#else
    gl_loader = "none";
#endif
```

You want to step at the end of this block and check the exact version for `gl_loader`. If it isn't "GLAD" or "GLAD2" then the compile-time configuration is wrong and the backend doesn't know about your loader so it's going to try accessing the function symbols from another loader which wasn't initialized.

**Comment by Jaumeavinyo** [comment]
Here you have it. Thanks

// Debugging construct to make it easily visible in the IDE and debugger which GL loader has been selected.
    // The code actually never uses the 'gl_loader' variable! It is only here so you can read it!
    // If auto-detection fails or doesn't select the same GL loader file as used by your application,
    // you are likely to get a crash below.
    // You can explicitly select a loader by using '#define IMGUI_IMPL_OPENGL_LOADER_XXX' in imconfig.h or compiler command-line.
    const char* gl_loader = "Unknown";
    IM_UNUSED(gl_loader);
#if defined(IMGUI_IMPL_OPENGL_LOADER_GL3W)
    gl_loader = "GL3W";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLEW)
    gl_loader = "GLEW";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLAD)
    gl_loader = "GLAD";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLAD2)
    gl_loader = "GLAD2";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLBINDING2)
    gl_loader = "glbinding2";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLBINDING3)
    gl_loader = "glbinding3";
#elif defined(IMGUI_IMPL_OPENGL_LOADER_CUSTOM)
    gl_loader = "custom";
#else
    gl_loader = "none";
#endif

**Comment by Jaumeavinyo** [comment]
Im using:
 gl_loader = "GLAD"

**Comment by ocornut** [comment]
Your first answer suggest you are misunderstanding my question.
Please use a debugger or add a printf() statement to actually confirm that the runtime value of gl_loader is GLAD.

**Comment by Jaumeavinyo** [comment]
[here you have it, debuuged and confirmed](https://prnt.sc/19j9ihg)

**Comment by ocornut** [comment]
You didn't gave me the GlVersion version, only the GLSLversion one.

**Comment by Jaumeavinyo** [comment]
> You didn't gave me the GlVersion version, only the GLSLversion one.

where do I find this=?

**Comment by Jaumeavinyo** [comment]
> You didn't gave me the GlVersion version, only the GLSLversion one.

[here?¿](https://prnt.sc/19jachd)

**Comment by ocornut** [comment]
In your version of the code there's a variable `g_GlVersion` setup at the beginning of `ImGui_ImplOpenGL3_Init()`
I am afraid I can't help further if you are not researching things further and not reading comments.

Also your first screen has some code saying `glPushDebugGroup()` which is not part of vanilla imgui_impl_opengl3 and was never part of it, and it looks like it may be this function call that crash, and you are using a modified backend so at this point I can't really help debugging random modified code that wasn't provided nor have a justification.

**Comment by Jaumeavinyo** [comment]
> In your version of the code there's a variable `g_GlVersion` setup at the beginning of `ImGui_ImplOpenGL3_Init()`
> I am afraid I can't help further if you are not researching things further and not reading comments.
> 
> Also your first screen has some code saying `glPushDebugGroup()` which is not part of vanilla imgui_impl_opengl3 and was never part of it, and it looks like it may be this function call that crash. So you are using a modified backend so at this point I can't really help debugging random modified code that wasn't provided nor have a justification.

Okay, you helped a lot, don'tworry I just needed some clues to find where was the problem, pd, my gl version is 320
