### ISSUE TITLE
Issue using io.ClearInputCharacters()

### ISSUE THREAD

**Issue by ShermIO** [ocornut/imgui#2425]
**Version/Branch of Dear ImGui:**

Version: 1.67
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp 
Compiler: Visual Studio Community 2017
Operating System: Windows 10 (Ver 1809)

**My Issue/Question:**

Hello! I am having issues using io.ClearInputCharacters(). I can use io.AddInputCharactersUTF8("sample character") just fine. I use the following code to add input characters: https://pastebin.com/WYXT6tEK

However, when I try to clear the input characters, nothing simply happens. I am using the following code to clear input characters and added a simple cout to ensure that I am getting detecting the press of backspace just fine. https://pastebin.com/GhSK9zej

Any help or thoughts is much appreciated. I am sure the issue is probably me doing something wrong, however, in the chance that it is an issue with ImGui, I wanted to make you guys aware. Thanks!

**Comment by ocornut** [comment]
InputCharacters is a character queue that is processed and consumed every frame, there’s almost never a reason to clear it and you certainly shouldn’t clear it In relation to the backspace key. You are misunderstanding its purpose.

Refer to imgui_impl_win32.cpp about how to use AddInputCharacter() functions via the WM_CHAR message.
