### ISSUE TITLE
Missing clipboard support in Freeglut backend

### ISSUE THREAD

**Issue by FullStackDevoloper** [ocornut/imgui#2426]
Version/Branch of Dear ImGui:

Version: 1.69
Branch: WIP

Back-end/Renderer/Compiler/OS:

Back-ends: imgui_impl_freeglut.cpp + imgui_impl_opengl2.cpp 
Compiler: g++
Operating System: Linux/Ubuntu

My Issue/Question:

i  noticed that in glut example " Logging strings to clipboard " doesn't seem to be working, but it's working in the glfw3 example.

- glut doesn't support logging to the clipboard? it's not related to OpenGL or context window tho
since we are copying a string.
- or you just didn't implement this example to support this feature?

I don't know i just got a bit confused, and i really prefer logging my text using a feature in ImGui rather than using some Linux library and terminal commands from my c++ code.

I have also tried this simple code below, but it's not working:

ImGui::LogToClipboard();
ImGui::LogText("Hello, world!");
ImGui::LogFinish();

Thanks for your help,

**Comment by ocornut** [comment]
There’s no clipboard support in the Freeglut backend nor in Freeglut itself afaik.

**Comment by FullStackDevoloper** [comment]
okay, good to know and thanks for your answer :)

**Comment by ocornut** [comment]
I added a comment about it in the file now, that comment was missing.

**Comment by FullStackDevoloper** [comment]
Yeah great, i have used xclip lib and it is working just fine now
