### ISSUE TITLE
can't view long string using ImGui::Text ?

### ISSUE THREAD

**Issue by FullStackDevoloper** [ocornut/imgui#2429]
Version/Branch of Dear ImGui:

Version: 1.69
Branch: WIP

Back-end/Renderer/Compiler/OS:

Back-ends: imgui_impl_freeglut.cpp + imgui_impl_opengl2.cpp
Compiler: g++
Operating System: Linux/Ubuntu

My Issue/Question:
I am trying to read file content and store it in a string then pass it to ImGui::Text to view it
but it only shows part of it, the string might contain 300/400 lines and around 10k characters tho.

is there a way to increase the text length that ImGui::Text can take?

**Comment by ocornut** [comment]
You can use TextUnformatted().

Also check Demo>Examples>Long Text.

**Comment by FullStackDevoloper** [comment]
Thanks so much, i will check the example
