### ISSUE TITLE
Change default bg_col of ImageButton()

### ISSUE THREAD

**Issue by ApoorvaJ** [ocornut/imgui#243]
For `ImageButton()`, I think the default value of `bg_col` should be `(0,0,0,0)` instead of `(0,0,0,1)`.

Most of the time, an `ImageButton` will be used to create buttons with icons on them. The default value makes it seem like a bug - that the code is ignoring the alpha.

Here's a screenshot of the default behavior of an `Image()` vs the default behavior of an `ImageButton()`:

![scr_26](https://cloud.githubusercontent.com/assets/2312221/8148462/9bdbc580-12bc-11e5-8f6b-186cbedae515.png)

**Comment by ApoorvaJ** [comment]
Related issue:
When using `ImageButton()`, if `frame_padding` is set to 0, and the `bg_col` alpha is 0, then the button isn't drawn at all. 

Makes sense when the image is fully opaque, but otherwise the button should be drawn behind the image, even if padding is 0.

**Comment by ocornut** [comment]
Agreeing for first change. Fixed both. Thanks!

**Comment by ApoorvaJ** [comment]
That was quick. Thanks! :)
