### ISSUE TITLE
non-deterministic crashes in freeglut example

### ISSUE THREAD

**Issue by jpantaleoni** [ocornut/imgui#2430]
I just started looking at ImGui for use with Freeglut, and I am sporadically getting crashes at startup on the (unmodified) provided example (i.e. it crashes often, but not always).

The crash, when it happens, seems to always happen in imgui.cpp : L3386

IM_ASSERT((g.IO.DeltaTime > 0.0f || g.FrameCount == 0)              && "Need a positive DeltaTime!");

disabling the assert everything seems to run fine

![imgui-crash](https://user-images.githubusercontent.com/6178097/54521831-0e7ed700-496c-11e9-88ba-ed2ad767cddf.jpg)
.

I am on:

- ToT master / 1.69
- Windows 10 / VS 2017
- freeglut 3.0.0

Other than that, the library seems awesome!

**Comment by ocornut** [comment]
The code that does the DeltaTime computation needs to be reworked to never output zero.

I am bit surprised at the number of people using Freeglut (I expected this number to be near zero but you are the second person posting about it recently). This is such a broken and outdated framework I may just remove that example code, its mere presence may encourage people to stick to something that has no reason to be used in 2019.

**Comment by jpantaleoni** [comment]
Eh - I know!
Just too lazy to switch to something else...

**Comment by ocornut** [comment]
How about submitting a PR to fix the aforementioned issue? The requirement that DeltaTime>0 is documented in the changelog of 1.68.

**Comment by ocornut** [comment]
I pushed a fix for this along with a few useful comments.

```
// !!! GLUT IS OBSOLETE SOFTWARE. Using GLUT is not recommended unless you really miss the 90's. !!!
// !!! If somebody or someone is teaching you GLUT in 2019, you are being abused. Please show some resistance. !!!
```
