### ISSUE TITLE
ImColor not corresponding to the rgb color

### ISSUE THREAD

**Issue by thomasxd24** [ocornut/imgui#2437]
**Version/Branch of Dear ImGui:**

Version: master
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9cpp + imgui_impl_win32.cpp 
Operating System: Windows 10

**My Issue/Question:**

Basically i am trying the window bg color with

```
ImGuiStyle& style = ImGui::GetStyle();
	style.Colors[ImGuiCol_TitleBg] = ImColor(165,23,69);
```
The problem is the color at the end doesnt correspond with the color of rgb
This is the color i need:
![image](https://user-images.githubusercontent.com/11338924/54709255-79373a80-4b45-11e9-82f6-4e5e2b0074b9.png)
but at imgui i got this instead:
![image](https://user-images.githubusercontent.com/11338924/54709322-953adc00-4b45-11e9-8a9f-97e38e70f1b4.png)

Am i doing this wrong?

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

```
	ImGuiStyle& style = ImGui::GetStyle();
	style.WindowTitleAlign = ImVec2(0.5f, 0.5f);
	style.Colors[ImGuiCol_TitleBg] = ImColor(165,23,69);
	style.FrameRounding = 0.0f;
	style.ChildRounding = 0.0f;
	style.WindowRounding = 0.0f;
	ImGui::SetNextWindowBgAlpha(0.3f);
	ImGui::Begin("Debug");
	ImGui::Text("Debug");
	ImGui::End();
```

**Comment by ocornut** [comment]
Dear ImGui emit unmodified colors. Your rendering pipeline probably have post process or gamma correction in that alters the colors.
