### ISSUE TITLE
Resize window by one edge only (removing the resize grip)

### ISSUE THREAD

**Issue by Melix19** [ocornut/imgui#2439]
**Version/Branch of Dear ImGui:**

Version: Release 1.69
Branch: master

**Back-end/Renderer/OS**

Back-end/Renderer: imgui-SFML
Operating System: macOS 10.14.3

**My Question:**

I need a window that can be resized by one edge only, disabling and hiding the resize grip on the angle of the window completely. A possible solution would be the one provided in #2254, but the result is just an hidden grip that however can be activated just by clicking on that area. I also searched in the demo and in the imgui.h but I just found the io.ConfigWindowsResizeFromEdges that it's not what I was finding (even because I want just one edge to be used).

**Comment by ocornut** [comment]
It’s not possible but you can trivially add your own option for it. I don’t think I would want to merge such patch, but it may sway it if you detailed _why_ you need such change.

**Comment by Melix19** [comment]
I have a left side panel in my program with a TreeView. I want this window to be resizable only by its width, and to achieve this I use SetNextWindowSizeConstraints that works fine. The problem is that I can resize the window by the other side which is not exactly what I want (watch attached gif). Also, not having these grip altogether it's just a better design in my case imho.

![imgui](https://user-images.githubusercontent.com/23530586/54777560-d77e1f00-4c12-11e9-8e71-b63954538ca8.gif)

**Comment by Melix19** [comment]
I managed to add an io.ConfigWindowsResizeFromGrips to my local project to fix my issue. I can make a PR if you want!

**Comment by ocornut** [comment]
I think you probably ought to use a passthru dockspace and a docking node on the left side.

Technically we could consider including specific flags (per corner, per side) as part of the resizing constraints but it feels like this is more of a problem to be handled by docking.

**Comment by Melix19** [comment]
Oh, haven't tried the docking branch before. It's much better now, thanks! 
I'll close the issue.

**Comment by Melix19** [comment]
Umh, there is just a problem, is there a function to dock a window on a side of a node? I found SetNextWindowDockID, but this seems just to dock the window to its center.

**Comment by Melix19** [comment]
Nevermind, after lots of researches and tests I found out the DockBuilderXXX methods and how to use them.
