### ISSUE TITLE
Resize ImGui windows on host window resize

### ISSUE THREAD

**Issue by Omegastick** [ocornut/imgui#2442]
**Version/Branch of Dear ImGui:**

Version: 1.67
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: gcc 8.1.0
Operating System: Ubuntu 18.04

**My Issue/Question:**

As far as I can see, the recommended way to handle host window (Linux/Windows's windows) resizing is to use `ImGui::GetIO().FontGlobalScale` and `ImGui::GetStyle().ScaleAllSizes()`. The problem I'm facing is that this doesn't address the actual size and position of the ImGui windows. After scaling the host window up 2x and changing the relevant ImGui size settings accordingly, the ImGui window is too small. See the screenshots for a more clear idea of what's going on.

Is there a way around this? If not, I'd be happy to have a go at implementing a `ResizeAllWindows()` function or similar.

**Screenshots/Video**

Before resize (very small resolution):
![Screenshot from 2019-03-22 12-58-20](https://user-images.githubusercontent.com/17452111/54799751-d811c680-4ca1-11e9-9721-0b315699b4ea.png)
Ignore that the text is unreadable because of the low resolution. Layout-wise everything is fine.

After resize (1920x1080):
![Screenshot from 2019-03-22 12-58-29](https://user-images.githubusercontent.com/17452111/54799686-9e40c000-4ca1-11e9-94ad-c15d3f6753f3.png)
Then after the resize the scale of the ImGui elements is fine, but the ImGui window hasn't resized or been repositioned to account for the new host window's scale.

**Comment by ocornut** [comment]
You are not specifying but I assume you resizing is related to DPI change of the monitor the window is on?

There is an internal WIP mechanism to do that in the viewport/docking branch (see `ScaleWindowsInViewport`) if you have multi-viewport enabled. I agree we could probably expose some of that in the master branch earlier, even if it is in imgui_internal.h.

**Comment by Omegastick** [comment]
Sorry for the slow reply. My use-case is when the user maximizes/unmaximizes the window, I'd like all the content inside to scale with it. For now, I could just lock the user into one resolution, but that would cause the problems when switching between monitors with different DPIs that you've come across in the viewport/docking branch.

I'll switch to the docking branch, give ScaleWindowsInViewport a go and report back on how it works.

**Comment by Omegastick** [comment]
@ocornut I got `ScaleWIndowsInViewport` working. My GLFW window resize callback looks like this:
```cpp
void resize_window_callback(GLFWwindow *glfw_window, int x, int y)
{
    if (x == 0 || y == 0)
    {
        return;
    }
    spdlog::debug("Resizing window to {}x{}", x, y);
    glViewport(0, 0, x, y);

    // Reset all ImGui windows
    reset_imgui_style();
    float relative_scale_reset = static_cast<float>(resolution_x) / last_resolution_x;
    for (const auto &viewport : ImGui::GetCurrentContext()->Viewports)
    {
        ImGui::ScaleWindowsInViewport(viewport, relative_scale_reset);
    }

    // Scale them to the appropriate size
    float relative_scale = static_cast<float>(x) / resolution_x;
    for (const auto &viewport : ImGui::GetCurrentContext()->Viewports)
    {
        ImGui::ScaleWindowsInViewport(viewport, relative_scale);
    }
    ImGui::GetStyle().ScaleAllSizes(relative_scale);
    ImGui::GetIO().FontGlobalScale = relative_scale;

    last_resolution_x = x;
    last_resolution_y = y;
}
```

It assumes that the aspect ratio stays the same when resizing.

Let me know if I'm doing something wrong here.

**Comment by xr4zz3rs** [comment]
Thanks successful.

**Comment by xr4zz3rs** [comment]
And i not found menu's color only blue-alpha how change this?
