### ISSUE TITLE
NewLine() Skipping all ScrollArea

### ISSUE THREAD

**Issue by rosen90** [ocornut/imgui#2443]
Hi I am trying to write text next to Scroll Area with buttons. When I call ImGui::NewLine() It seems that all scroll area is one whole Line(don't know why) and then there is new lines I needed.

Example: 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/4669237/54855141-df66bd80-4cfd-11e9-9a08-af2af7ba29f2.gif)

The new texts must be right after the first, but ImGui::NewLine(), skips whole Scroll Area. Any Ideas?

Here is the code:

           ` //Create Scroll Area
            ImVec2 ScrollAreaSize = ImGui::GetContentRegionAvail();
            ScrollAreaSize.x -= dimension.scroll_offset;
            ScrollArea child("GAME_SELECT_VIEW", ScrollAreaSize);

            int btnId = 0;
            for(auto row = 0; row < m_vectorMsg.size(); ++row)
            {
                //Draw Buttons
                DrawDetailsRow();
                ImGui::NextColumn();
                
                //Draw Page Numbers
                DrawPageLists();
                ImGui::NewLine();
            }
         }

        for (int i = 0; i < m_vsEmptyPageSlot.size(); ++i)
        {
            if (m_vsEmptyPageSlot[i] == 0)
            {
                ImGui::SameLine(ImGui::GetWindowWidth() - 550);
                ImGui::TextUtf8("Maximum Games Per " + std::to_string(i+1) + " Page Reached");
                ImGui::NewLine();
            }
        }
    }`

If I remove the last ImGui::NewLine function from second for loop, all the texts are drawn one over another.

**Comment by ocornut** [comment]
Hello,
Please provide repro code that we can actually test/compile/run. See the description of MVCE in the New Issue guidelines.
