### ISSUE TITLE
Can I avoid the IsMouseDragging() event when I click on a button of overlapping window?

### ISSUE THREAD

**Issue by JamAndCheese** [ocornut/imgui#2447]
(Click "Preview" to turn any http URL into a clickable link)

1. PLEASE CAREFULLY READ:
https://github.com/ocornut/imgui/issues/2261

2. IF YOU ARE HAVING AN ISSUE COMPILING/LINKING/RUNNING/LOADING FONTS, please post on the "Getting Started" Discourse forum:
https://discourse.dearimgui.org/c/getting-started

3. PLEASE MAKE SURE that you have: read the FAQ in imgui.cpp; explored the contents of ShowDemoWindow() including the Examples menu; searched among Issues; used your IDE to search for keywords in all sources and text files; and read the link provided in (1).

4. Be mindful that messages are being sent to the mailbox of "Watching" users. Try to proof-read your messages before sending them. Edits are not seen by those users, unless they browse the site.

5. Delete points 1-5 and PLEASE FILL THE TEMPLATE BELOW before submitting your issue.

Thank you!

----

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: XXX
Branch: XXX _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: XXX

**My Issue/Question:**

XXX _(please provide as much context as possible)_

**Screenshots/Video**

XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Please do not forget this!
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by JamAndCheese** [comment]
I have a window in which I detect dragging with `ImGui::IsMouseDragging( 0, 0.0f )` in order to create a selection rectangle. It works as expected. I then open an overlapping window with a button, to record the coordinates of such selection box, but when I click on the button there is a mini-dragging event registered on the underlying window, which ruins my already defined selection rectangle.

Any suggestions?

**Comment by nicolasnoble** [comment]
You've completely ignored any part of what the issue template was asking you to do and report about.

**Comment by ocornut** [comment]
> when I click on the button there is a mini-dragging event registered on the underlying window

This is the expected behavior if you call `ImGui::IsMouseDragging(0, 0.0f)`, the zero threshold will start reporting a drag from the initial click. You probably need to be checking your window focus with `IsWindowFocused` etc. either way.

Closing as you have ignored the issue template.

**Comment by JamAndCheese** [comment]
Thanks. I will look into.
PS: You guys are very sensitive. I was on phone and could not see the whole thing. Geez.
