### ISSUE TITLE
Column InputText Bug

### ISSUE THREAD

**Issue by IHLee89** [ocornut/imgui#2448]
The value entered in email1 is not applied properly.
Pressing email1 changes email2, pressing email2 changes email3.
Pressing email3 changes email1,2,3 at once.

static char email1[256] = "111";
static char email2[256] = "222";
static char email3[256] = "333";
ImGui::Columns(4);
static int testInt[3];
ImGui::InputInt("1", &testInt[0]);
ImGui::InputText("email", email1, 32);
ImGui::NextColumn();
ImGui::InputInt("2", &testInt[1]);
ImGui::InputText("email", email2, 32);
ImGui::NextColumn();
ImGui::InputInt("3", &testInt[2]);
ImGui::InputText("email", email3, 32);
ImGui::NextColumn();
ImGui::Columns(1);

**Comment by ocornut** [comment]
Please read the FAQ.
