### ISSUE TITLE
Holding and releasing mouse on menu item should open it

### ISSUE THREAD

**Issue by paulsapps** [ocornut/imgui#245]
Enhancement request for menu behavior. 

When you click and hold down the mouse on a top level menu it opens. Then if you scroll down on a newly opened submenu item and release the mouse button nothing happens. It would be nice if this opened the menu as it does in win32 apps.

**Comment by ocornut** [comment]
Short update, will do this ( I knew about this when I made the menu release, c.f. https://github.com/ocornut/imgui/issues/126#issuecomment-105595137 )

It's a bit of an odd inconsistency compared to pretty much everything in the system, so not just a simple one-line change but probably simple enough. Will do! The menu is "active" while mouse is being held and menu item would have to take account of that and allow to be activated when mouse is released on a menu item while a menu in the item hierarchy is active. It probably won't work with Button() or the other widgets that are rarely used in menus.

**Comment by ocornut** [comment]
Easier than I thought. Hopefully didn't break anything in the process.
