### ISSUE TITLE
Windows disappear after using shader

### ISSUE THREAD

**Issue by FullStackDevoloper** [ocornut/imgui#2450]
Version/Branch of Dear ImGui:

Version: 1.69
Branch: WIP

Back-end/Renderer/Compiler/OS:

Back-ends: imgui_impl_freeglut.cpp + imgui_impl_opengl2.cpp
Compiler: g++
Operating System: Linux/Ubuntu

My Issue/Question:
i am trying to use #version 330 shaders but all imgui windows disappear, do i have to switch to 110 version shaders for it to work since it's opengl_2 example or i have to switch to glfw3 example code ?

**Comment by ocornut** [comment]
This is an OpenGL question rather than a Dear ImGui question.
Moreover your question is not explicit. "i am trying to use #version 330 shaders", what, where? There's no shader in imgui_impl_opengl2.cpp.
With GL3+ the shader version must match the OpenGL context version you created in your applicaton.

Please ask on a general game/gpu programming forum.

**Comment by FullStackDevoloper** [comment]
in my opengl context im using imgui windows to edit my objects properties, everything works fine as long as iam in the immediate mode but when i render an object using shaders ( imgui windows disappear)

**Comment by ocornut** [comment]
The main.cpp says:
```cpp
// If you are using this code with non-legacy OpenGL header/contexts (which you should not, prefer using imgui_impl_opengl3.cpp!!), 
// you may need to backup/reset/restore current shader using the commented lines below.
//GLint last_program; 
//glGetIntegerv(GL_CURRENT_PROGRAM, &last_program);
//glUseProgram(0);
ImGui_ImplOpenGL2_RenderDrawData(ImGui::GetDrawData());
//glUseProgram(last_program);
```

**Comment by FullStackDevoloper** [comment]
i didn't find those in the main.cpp but i have added them and still doesn't work
i don't know why binding VBO make imgui disappear
glBindBuffer(GL_ARRAY_BUFFER, VBO);
glBufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);

**Comment by FullStackDevoloper** [comment]
and when i uncomment those line u mentioned i get segmentation fault

**Comment by FullStackDevoloper** [comment]
ughhh sorry bro just solved the issue, i had to unbind the vertex array and the buffer object in the main loop and after initializing
