### ISSUE TITLE
Crash on using FreeType test code (and maybe FreeType impl. itself)

### ISSUE THREAD

**Issue by 0x416c69** [ocornut/imgui#2454]
Version: v1.69 (From the Release page)
Using DirectX9 and Win32.
FreeType version: 2.10.0

Screenshot of call stack, exception address, etc.
![devenv_2019-03-29_06-13-56-AM](https://user-images.githubusercontent.com/10671711/55203865-a2616600-51ea-11e9-870b-e6c9943aa5af.png)

Also when I check if font_config is not a null pointer, the application runs but here's the behavior: (Don't mind the cursor position, it's my recorder issue)
![2019-03-29_06-21-58-AM](https://user-images.githubusercontent.com/10671711/55203963-fec48580-51ea-11e9-9ae5-a79e78c8a5cd.gif)

There is no extra code, the code is not modified at all, using example_win32_directx9 and UpdateRebuild is getting called before NewFrame.

**Comment by ocornut** [comment]
> There is no extra code, the code is not modified at all

There's no support for FreeType in the default example, therefore by definition the example code has been modified. Please provide a repro.

**Comment by 0x416c69** [comment]
Of course that I actually modified lines for this according to the documentation, what I meant was the original code is not modified.

So the modifications: https://www.diffchecker.com/lR6s7jdI

**Comment by ocornut** [comment]
Thanks for the details.

The assert in `ImGui_ImplDX9_InvalidateDeviceObjects()` was unnecessary and inconsistent with other bindings so I have removed it.

I also clarified the suggested test code in freetype/README.md so it won't crash before a first atlas build, therefore not requiring a build at init time.

See e21bbee311a13c451a72fb0710fd25d963d2a974.
