### ISSUE TITLE
Any idea when horizontal scroll bar will be available?

### ISSUE THREAD

**Issue by nikmes** [ocornut/imgui#246]

**Comment by ocornut** [comment]
I was actually looking into some of that recently.
It should be quite easy to add. 

There's a few problems to take care of, e.g. some clipping optimisations for huge block of texts are skipping on text width calculation. Scrolling is easy and free but calculating accurate size to have a reference point of how big is the contents, can sometimes be costly.

**Comment by ocornut** [comment]
Note that you can easily hack some form of manual scrolling by positioning the cursor.
e.g.

```cpp
static float x = 0.0f;
if (ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_LeftArrow)))
    x -= ImGui::GetIO().DeltaTime * 1000.0f;
if (ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_RightArrow)))
    x += ImGui::GetIO().DeltaTime * 1000.0f;
ImGui::SetCursorPosX((float)(int)-x);
ImGui::BeginGroup();
...
```

**Comment by nikmes** [comment]
Thanks! I ll give it a try.

On 20 July 2015 at 03:55, omar <notifications@github.com> wrote:

> Note that you can easily hack some form of manual scrolling by positioning
> the cursor.
> e.g.
>
> static float x = 0.0f;if (ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_LeftArrow)))
>     x -= ImGui::GetIO().DeltaTime * 1000.0f;if (ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_RightArrow)))
>     x += ImGui::GetIO().DeltaTime * 1000.0f;ImGui::SetCursorPosX((float)(int)-x);ImGui::BeginGroup();
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocornut/imgui/issues/246#issuecomment-122723424>.
>



-- 
Best Regards
Nicholas Messaritis

**Comment by ocornut** [comment]
OK pretty much done with that.
The horizontal scrollbar is always off by default and has to be enabled using ImGuiWindowFlags_HorizontalScrollbar.

You can call SetNextWindowContentWidth(width) before Begin() to specify a desired width.
The change had more side-effects than effects, had to change a few things but it may introduce new bugs.

![horizontal_scrollbar](https://cloud.githubusercontent.com/assets/8225057/9568628/0f7fbbf6-4f47-11e5-9980-96fff3cb8151.gif)

![horizontal_scrollbar2](https://cloud.githubusercontent.com/assets/8225057/9568630/12adf78e-4f47-11e5-8795-a81784c18405.gif)

**Comment by Extrawurst** [comment]
@ocornut you are amazing... thank you!

**Comment by digiorgi** [comment]
@ocornut WOW!! Thanks! thanks!

**Comment by nikmes** [comment]
Looks cool. I will upgrade my code tonight :) Thanks a lot

**Comment by nikmes** [comment]
https://www.facebook.com/2dleveleditor/?ref=aymt_homepage_panel
