### ISSUE TITLE
ImGui::Button width calculation bug?

### ISSUE THREAD

**Issue by darkgnostic** [ocornut/imgui#2463]
I'm using latest 1.70 WIP master

If I set item size with `ImGui::PushItemWidth(ImGui::GetWindowSize().x*0.5f);` then draw button with `ImGui::Button("Button", ImVec2(-1.0f, 0.0f))`, it will stretch button across whole width instead only half of window width.

![button](https://user-images.githubusercontent.com/4980221/55315098-e1eab500-546b-11e9-9ef1-40809e68f0ad.PNG)

This works well with various input types, but not with the button. Is this a bug or am I missing something?

**Comment by ocornut** [comment]
Hello Izzy,

It's not a bug but for various reasons Button's default behavior differs from widgets that contains an external label.

If you use `ImGui::PushItemWidth(-1.0f)` the _other_ widgets on the pictures will use the full width, which by looking at your picture may appear preferable to what you have asked for?

You may also use `ImGui::Button("Button", ImVec2(ImGui::GetWindowSize().x*0.5f, 0.0f))` to make the button match the half width used by the PushItemWidth() call mentioned above.

**Comment by darkgnostic** [comment]
Thank you for your swift response.

Actually I need a second version, I have just  reduced the width of input fields for the sake of demonstration.

Also found that there is `ImGui::GetContentRegionAvailWidth()` which is more appropriate than `ImGui::GetWindowSize().x`.
