### ISSUE TITLE
Automatic linking via vcpkg is not working.

### ISSUE THREAD

**Issue by gdeverlant** [ocornut/imgui#2466]
**Version/Branch of Dear ImGui:**

Version: 1.68

**My Issue/Question:**

Do you know why when I do **cmake .. -DCMAKE_TOOLCHAIN_FILE=G:\programming\c++\vcpkg\scripts\buildsystems\vcpkg.cmake**
This dude ends up here :

**Screenshots/Video**

![image](https://files.gitter.im/gdeverlant/stKk/image.png)

The correct path should be : **G:\programming\c++\vcpkg\installed\x86-windows\debug\lib\miguid.lib**

**Comment by ocornut** [comment]
Please submit this on the vcpkg repository.

**Comment by gdeverlant** [comment]
Where is that?

**Comment by ocornut** [comment]
https://www.google.com/search?client=firefox-b-d&q=vcpkg

**Comment by gdeverlant** [comment]
Thank you, you are so nice when you want 😄
