### ISSUE TITLE
TempBuffer size should be configurable

### ISSUE THREAD

**Issue by bear24rw** [ocornut/imgui#2469]
I am trying to render a full screen of text using `TextWrapped` but it seems it is clamped to the hardcoded TempBuffer size of `1024*3+1`. Maybe `TempBuffer` size should be compile-time configurable in the same way that I can `-DImDrawIdx="unsigned int"`?

**Comment by nicolasnoble** [comment]
If you are trying to render such a large portion of text, maybe `TextWrapped` isn't the right fit?

**Comment by ocornut** [comment]
For large amount of text you should always use TextUnformatted.
You can still push a wrapping position, see what TextWrapped is doing.

**Comment by bear24rw** [comment]
Thanks, somehow I missed that function. This works great
```cpp
              ImGui::PushTextWrapPos(0.0f);
              ImGui::TextUnformatted(text.c_str());
              ImGui::PopTextWrapPos();
```

**Comment by ocornut** [comment]
Excellent!
Please remember to follow the issue template recommendations and express your need ("draw long wrapped text") rather than only your suggested solution ("change this buffer").
