### ISSUE TITLE
Creating window grid 

### ISSUE THREAD

**Issue by Coen4622** [ocornut/imgui#2470]
Hello, I am currently converting a grid towards a imgui component where you can drag multiple windows in a grid. However as far as I know this can only be done on a windows platform level as seen in the GIF. Are there any solutions to this? It looks like achieving this with docking is not possible in the current state.

I am currently on the docking branch.

![GridGif](https://user-images.githubusercontent.com/9967231/55489443-350e6480-5632-11e9-971c-f580234ba12c.gif)

**Comment by ocornut** [comment]
1) You didn't fill the requested Issue Template.
2) Your question is way too ambiguous. 

Please carefully clarify all those things so I can re-open the issue.

You can use `IsItemActive()` after Begin() to detect when a window is being dragged and snap them otherwise.

**Comment by randohinn** [comment]
@Coen4622 Sorry to drag up an old issue, but did you mnage to get this working :) ? I'm looking to do something similar...
