### ISSUE TITLE
creating and deleting window in runtime

### ISSUE THREAD

**Issue by Miriinae** [ocornut/imgui#2476]
**Version/Branch of Dear ImGui:**

Version: 1.68
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

**My Issue/Question:**

(I’m sorry, but I am not good at english)
How to create and delete window in runtime?
I want to make layout like Blender. But I can't find about it anywhere.

![Peek 2019-04-06 16-00](https://user-images.githubusercontent.com/25080544/55666143-2ec3f680-5885-11e9-9aae-5f3e69fa03b5.gif)
[create(duplicate) and delete window in blender]

I tried to create a tool to create a new window. : 
```
void create_window(const char* name) {
    ImGui::Begin(name);
    ImGui::Text("%s", name);
    ImGui::End();
}

ImGui::Begin("make window", &my_window);
static char name[32] = "";
ImGui::InputText("input text", name, IM_ARRAYSIZE(name));
if(ImGui::Button("create window")) {
    char* s = name;
    create_window(s);
}
ImGui::End();
```
![Peek 2019-04-06 16-55](https://user-images.githubusercontent.com/25080544/55666651-d133a800-588c-11e9-94d2-ddcd1a8d4935.gif)

However, the window once blinked and disappeared.

So my question is : How to Create and Delete window in runtime?

**Comment by ocornut** [comment]
Hello,

You need to submit elements to imgui every frame. If you stop calling an element it will stop appearing. In your code you only call Begin()/End() during the frame where the button was pressed. 

Dear ImGui works assuming you have a main loop where you regenerate your GUI, similarly to how game engines works.

Please ask further questions on the Discourse forum or on general programming forums.
