### ISSUE TITLE
Visual Studio 2015/2017 + Android + NDK + ImGUI

### ISSUE THREAD

**Issue by kazeniu** [ocornut/imgui#2477]
Hello,

I've tried to implement ImGUI into VS NDK Template. That template uses a precompiled header which contains these includes (as default):
`
#include <jni.h>
#include <errno.h>

#include <string.h>
#include <unistd.h>
#include <sys/resource.h>

#include <EGL/egl.h>
#include <GLES/gl.h>

#include <android/sensor.h>

#include <android/log.h>
#include "android_native_app_glue.h"
`

I have tried all of these but no results:
https://github.com/sfalexrog/Imgui_Android

Sample: [android_sample.zip](https://github.com/ocornut/imgui/files/3050482/android_sample.zip)

**Comment by ocornut** [comment]
Didn’t fill issue template.
