### ISSUE TITLE
Lack of Explanation on ImGui::Begin & ImGui::End

### ISSUE THREAD

**Issue by calioranged** [ocornut/imgui#2478]
Can anyone offer an explanation of how ImGui::Begin() and ImGui::End() work as there is next to nothing to read on this. Begin 'pushes' the 'window' on to the stack and End 'pops' the 'window' off the stack, but why is the End() call issued before the Render() call? Surely End() should be after as it is... you know, the end? A far more detailed explanation is required than that offered in the comments above the Begin() function, especially for new users like me!

**Comment by DJLink** [comment]
I may be wrong here, and someone correct me if I'm wrong.
Begin() as you mentioned starts a new window, that means calls made after this and before the corresponding End() will be applied to current window in the stack. So if you create a combo box, will be placed inside this window. Until you call End(), and you can now start a new Windows for example if you want with another Begin()

Think Render as a separate operation. Begin/End and all other calls are kind of to create the logic of everything, to create the UI in memory, the structure, once it's done you call Render to render everything.

It can be a bit overwhelming at start and the best way really is to put the demo running, play a little bit and see what you want to use using examples from imgui_demo.cpp

**Comment by calioranged** [comment]
**DJLink** thanks a lot for your reply, that has cleared up a lot of my uncertainties.
