### ISSUE TITLE
SDL2 hide cursor

### ISSUE THREAD

**Issue by teamclouday** [ocornut/imgui#2479]
I'm working on ImGUi with SDL2, trying to hide the cursor
but SDL_ShowCursor(SDL_FALSE) does not work
I've read that ImGui may also draw cursor internelly

So how to properly disable cursor?

**Comment by ocornut** [comment]
Have you looked at the imgui_impl_sdl.cpp to find your answer?

**Comment by teamclouday** [comment]
@ocornut Do you mean ImGui_ImplSDL2_UpdateMouseCursor() ? I'll try to figure it out

**Comment by ocornut** [comment]
Yes.

(A)
If you want to handle the SDL mouse cursor shape/visibility yourself, you can set `io.ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange`, as instructed on Line 7 of imgui_impl_sdl.cpp.

(B)
You may also leave imgui_impl_sdl.cpp handling the cursor visibility, and instead call `ImGui::SetMouseCursor(ImGuiMouseCursor_None)`. In ImGui fashion note that you need to call this every frame to keep the cursor hidden.

**Comment by teamclouday** [comment]
@ocornut Thank you very much! It works
