### ISSUE TITLE
Add IsMouseReleased() and IsKeyReleased() functions

### ISSUE THREAD

**Issue by ApoorvaJ** [ocornut/imgui#248]
ImGui has great built-in input tracking already. While it is trivial to implement these functions externally, I think they would be a useful addition to the core input framework.

`bool IsMouseReleased(int button)` would return true if the specified mouse button was pressed last frame and is not pressed this frame. This is useful to track things like when dragging ends.

`IsKeyReleased(int key_index)` would be the keyboard counterpart.

**Comment by ocornut** [comment]
Done!

**Comment by ApoorvaJ** [comment]
Perfect. Thanks! :)
