### ISSUE TITLE
ImGui::Button Explanation

### ISSUE THREAD

**Issue by calioranged** [ocornut/imgui#2481]
*** Beginner Question *** 

What does ImGui::Button do? There is no explanation of this function in either the declaration or definition, but in the main.cpp file there is a line which says 'Buttons return true when clicked', which makes sense. But does ImGui::Button have any other use? Does this create buttons as well as check if they have been clicked? If not, then how are buttons initially created?

**Comment by DJLink** [comment]
Yes, ImGui::Button will display a single clickable button with a label. As you said the return of that function will tell you if it was clicked or not.

The example below code will show a Button with "Save" label, on the moment when it's clicked it will call whatever code you have in it. You can call it more times for more buttons.

```
if (ImGui::Button("Save"))
{
	//... my_code 
}

if (ImGui::Button("Cancel"))
{
	//... my_code 
}
```

 Hope this helps.

**Comment by calioranged** [comment]
**DJLink** thanks a lot for that information.

So just to confirm, are you saying that with the following snippet:

`if (ImGui::Button("Clear Colour"))`
`{`
`             // do something`
`}`

The first time that `if (ImGui::Button("Clear Colour"))` is run, it will create a button with the label "Clear Colour", and then all subsequent runs will check if the 'Clear Colour' button was pressed, and if it _was_ pressed then the body of the _if()_ statement in the above code snippet will run?

**Comment by ocornut** [comment]
>  it will create a button with the label "Clear Colour", and then all subsequent runs will check if the 'Clear Colour' button was pressed, 

Your notion of "creating" a button is anchored in the classic retained-mode paradigm (RMGUI).
The idea with the IMGUI paradigm is that the button only exist if you call the function. From Dear ImGui point of view, the button only exists during the `Button()` call. There's no trace of it before and after, apart from the visual output (we emit vertices that will be rendered to look like a button).

Essentially this will have the same effect you described. And if you stop calling the `Button()` function, the button will stop appearing.

**Comment by calioranged** [comment]
**ocornut** I just followed some of those links and now I understand the difference between RMGUI and IMGUI. Thanks a lot for your help.

**Comment by chethanapavan** [comment]
ImGui Button Freeze

i am using ImGui in my application for UI, my question is when i press the button the code in side if condition will execute ,
but once i pressed  the button , I can't press the other button including pressed button ,  could any one let me know the solution, thank you in advance

if (ImGui::Button("Button"))
{
	//... my_code 
}

**Comment by DJLink** [comment]
> ImGui Button Freeze
> 
> if (ImGui::Button("Button"))
> {
> //... my_code
> }

Hi could you provide a more complete sample, this code only has 1 button, where is the other button being used, inside the //my_code scope, outside?

**Comment by chethanapavan** [comment]
Hi, no other button  not inside the  my_code , outside the my_code, for example,
if (ImGui::Button("Save"))
{
	//... my_code 
}

if (ImGui::Button("Cancel"))
{
	//... my_code 
}

**Comment by DJLink** [comment]
both those buttons should work even after pressing one time.
When you say can't be pressed does the button not even highlight on mouse hover, or is only your logic inside that scope that doesn't run again? could it be some sort of internal condition on your logic that blocks it after one press?

Does this code allow you to press the buttons multiple times?

```cpp
static bool show_window = true;
ImGui::Begin("My Window", &show_window);

if (ImGui::Button("Save"))
{
cout << "Button Pressed"; //or your IDE equivalent output log
}

if (ImGui::Button("Cancel"))
{
cout << "Button Pressed"; //or your IDE equivalent output log
}
ImGui::End();

```

**Comment by chethanapavan** [comment]
Hi,  thank you for the reply yes , once I press the button , that button even not highlight on mouse hover the next time and i can't modify window or i can press the other button or the same button

**Comment by DJLink** [comment]
> Yes the above code allow me to press buttons multiple time and also ,FPS also stop once press the button

In this case, and if after pressing a button your code inside that scope is not using any imgui API call that means that the problem is not imgui but something else about your code logic which makes it difficult to help. 
My suggestions examining your code line by line, see what makes it break, since with fps stopped that means you are freezing the program somehow. Sorry can't help more but it doesn't seem to be imgui related.

**Comment by chethanapavan** [comment]
Hi, thank you so much for the reply ok I will check my code once again and get back

**Comment by aiafrasinei** [comment]
Depends on what you are doing in your code.

If its something blocking and takes some time it will freeze the main loop
of the application.
May need to create a thread for that processing or some other method let
the gui do some rendering.

Not aware of how imgui is implemented but this should be the case.

**Comment by chethanapavan** [comment]
Hi, so this question is regarding button freez  in the following code when i press the button the other button or widgets or windows will freez may I know  how to over come this problem
int main(int, char**)
{
    // Setup window
    glfwSetErrorCallback(glfw_error_callback);
    if (!glfwInit())
        return 1;

    // Decide GL+GLSL versions
#if __APPLE__
    // GL 3.2 + GLSL 150
    const char* glsl_version = "#version 150";
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  // 3.2+ only
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);            // Required on Mac
#else
    // GL 3.0 + GLSL 130
    const char* glsl_version = "#version 130";
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
    //glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  // 3.2+ only
    //glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);            // 3.0+ only
#endif

    // Create window with graphics context
    GLFWwindow* window = glfwCreateWindow(1280, 720, "Dear ImGui GLFW+OpenGL3 example", NULL, NULL);
    if (window == NULL)
        return 1;
    glfwMakeContextCurrent(window);
    glfwSwapInterval(1); // Enable vsync

    // Initialize OpenGL loader
#if defined(IMGUI_IMPL_OPENGL_LOADER_GL3W)
    bool err = gl3wInit() != 0;
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLEW)
    bool err = glewInit() != GLEW_OK;
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLAD)
    bool err = gladLoadGL() == 0;
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLBINDING2)
    bool err = false;
    glbinding::Binding::initialize();
#elif defined(IMGUI_IMPL_OPENGL_LOADER_GLBINDING3)
    bool err = false;
    glbinding::initialize([](const char* name) { return (glbinding::ProcAddress)glfwGetProcAddress(name); });
#else
    bool err = false; // If you use IMGUI_IMPL_OPENGL_LOADER_CUSTOM, your loader is likely to requires some form of initialization.
#endif
    if (err)
    {
        fprintf(stderr, "Failed to initialize OpenGL loader!\n");
        return 1;
    }

    // Setup Dear ImGui context
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    //io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;     // Enable Keyboard Controls
    //io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;      // Enable Gamepad Controls

    // Setup Dear ImGui style
    ImGui::StyleColorsDark();
    //ImGui::StyleColorsClassic();

    // Setup Platform/Renderer bindings
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init(glsl_version);

    // Load Fonts
    // - If no fonts are loaded, dear imgui will use the default font. You can also load multiple fonts and use ImGui::PushFont()/PopFont() to select them.
    // - AddFontFromFileTTF() will return the ImFont* so you can store it if you need to select the font among multiple.
    // - If the file cannot be loaded, the function will return NULL. Please handle those errors in your application (e.g. use an assertion, or display an error and quit).
    // - The fonts will be rasterized at a given size (w/ oversampling) and stored into a texture when calling ImFontAtlas::Build()/GetTexDataAsXXXX(), which ImGui_ImplXXXX_NewFrame below will call.
    // - Read 'docs/FONTS.md' for more instructions and details.
    // - Remember that in C/C++ if you want to include a backslash \ in a string literal you need to write a double backslash \\ !
    //io.Fonts->AddFontDefault();
    //io.Fonts->AddFontFromFileTTF("../../misc/fonts/Roboto-Medium.ttf", 16.0f);
    //io.Fonts->AddFontFromFileTTF("../../misc/fonts/Cousine-Regular.ttf", 15.0f);
    //io.Fonts->AddFontFromFileTTF("../../misc/fonts/DroidSans.ttf", 16.0f);
    //io.Fonts->AddFontFromFileTTF("../../misc/fonts/ProggyTiny.ttf", 10.0f);
    //ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\ArialUni.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesJapanese());
    //IM_ASSERT(font != NULL);

    // Our state
    bool show_demo_window = true;
    bool show_another_window = false;
    ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);

    // Main loop
  //  while(!glfwWindowShouldClose(window))


        while(window)

    {
        // Poll and handle events (inputs, window resize, etc.)
        // You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
        // - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application.
        // - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application.
        // Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
        glfwPollEvents();

        // Start the Dear ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        // 1. Show the big demo window (Most of the sample code is in ImGui::ShowDemoWindow()! You can browse its code to learn more about Dear ImGui!).
        if (show_demo_window)
            ImGui::ShowDemoWindow(&show_demo_window);

        // 2. Show a simple window that we create ourselves. We use a Begin/End pair to created a named window.
        {
            static float f = 0.0f;
            static int counter = 0;

            ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.

            ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
            ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
            ImGui::Checkbox("Another Window", &show_another_window);

            ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f
            ImGui::ColorEdit3("clear color", (float*)&clear_color); // Edit 3 floats representing a color

            if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)

            {

                for (int i = 0; i < 1000000; i++)


                {


                    cout << i;


                }


               
            }

          


          ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
            ImGui::End();
        }



       // if (ImGui::Button("Button1"))


      


        // 3. Show another simple window.
        if (show_another_window)
        {
            ImGui::Begin("Another Window", &show_another_window);   // Pass a pointer to our bool variable (the window will have a closing button that will clear the bool when clicked)
            ImGui::Text("Hello from another window!");
            if (ImGui::Button("Close Me"))
                show_another_window = false;
            ImGui::End();
        }

        // Rendering
        ImGui::Render();
        int display_w, display_h;
        glfwGetFramebufferSize(window, &display_w, &display_h);
        glViewport(0, 0, display_w, display_h);
        glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        glfwSwapBuffers(window);
    }

    // Cleanup
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();

    glfwDestroyWindow(window);
    glfwTerminate();

    return 0;
}

**Comment by chethanapavan** [comment]
Hi, so this question is regarding button freez in the following code when i press the button the other button or widgets or windows will freez may I know how to over come this problem

 while(window)

{
    // Poll and handle events (inputs, window resize, etc.)
    // You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
    // - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application.
    // - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application.
    // Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
    glfwPollEvents();

    // Start the Dear ImGui frame
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    // 1. Show the big demo window (Most of the sample code is in ImGui::ShowDemoWindow()! You can browse its code to learn more about Dear ImGui!).
    if (show_demo_window)
        ImGui::ShowDemoWindow(&show_demo_window);

    // 2. Show a simple window that we create ourselves. We use a Begin/End pair to created a named window.
    {
        static float f = 0.0f;
        static int counter = 0;

        ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.

        ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
        ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
        ImGui::Checkbox("Another Window", &show_another_window);

        ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f
        ImGui::ColorEdit3("clear color", (float*)&clear_color); // Edit 3 floats representing a color

        if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)

        {

            for (int i = 0; i < 1000000; i++)


            {


                cout << i;


            }


           
        }

      


      ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
        ImGui::End();
    }



   // if (ImGui::Button("Button1"))


  


    // 3. Show another simple window.
    if (show_another_window)
    {
        ImGui::Begin("Another Window", &show_another_window);   // Pass a pointer to our bool variable (the window will have a closing button that will clear the bool when clicked)
        ImGui::Text("Hello from another window!");
        if (ImGui::Button("Close Me"))
            show_another_window = false;
        ImGui::End();
    }

    // Rendering
    ImGui::Render();
    int display_w, display_h;
    glfwGetFramebufferSize(window, &display_w, &display_h);
    glViewport(0, 0, display_w, display_h);
    glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
    glClear(GL_COLOR_BUFFER_BIT);
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    glfwSwapBuffers(window);
}

// Cleanup
ImGui_ImplOpenGL3_Shutdown();
ImGui_ImplGlfw_Shutdown();
ImGui::DestroyContext();

glfwDestroyWindow(window);
glfwTerminate();

return 0;

**Comment by chethanapavan** [comment]
i am using ImGui in my application for UI, my question is when i press the button the code in side if condition will execute ,
but once i pressed the button , I can't press the other button including pressed button , could any one let me know the solution,

Example Code

 while(window)

    {
        // Poll and handle events (inputs, window resize, etc.)
        // You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
        // - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application.
        // - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application.
        // Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
        glfwPollEvents();

        // Start the Dear ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        // 1. Show the big demo window (Most of the sample code is in ImGui::ShowDemoWindow()! You can browse its code to learn more about Dear ImGui!).
        if (show_demo_window)
            ImGui::ShowDemoWindow(&show_demo_window);

        // 2. Show a simple window that we create ourselves. We use a Begin/End pair to created a named window.
        {
            static float f = 0.0f;
            static int counter = 0;

            ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.

            ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
            ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
            ImGui::Checkbox("Another Window", &show_another_window);

            ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f
            ImGui::ColorEdit3("clear color", (float*)&clear_color); // Edit 3 floats representing a color

            if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)

            {

                for (int i = 0; i < 1000000; i++)

                {
                    cout << i;
                }
               
            }

**Comment by chethanapavan** [comment]
I Tried using thread but till have the same problem, it woul be helpful if some one give me suggestion.

**Comment by DJLink** [comment]
>  for (int i = 0; i < 1000000; i++)
> 
>{
>      cout << i;
>}

looping for 1000000 is a sure way to momentarily freeze the program. Code is executed in sequence, so until this finishes it won't allow the rest to execute. Games and Imgui are executed inside a "main" loop, which typically executes 60 times per second (60FPS), if you lock it somehow it won't be able to draw the next frame.

This might not be the best place for getting help with this part and threads. Here's the thing, once you enter that if(Imgui::Button) {  } scope you are supposed to do your calculations and exit asap, otherwise you lock the whole program, this is not related to imgui, it would happen in anything else too.
If you need something running in parallel, like a thread you mentioned I recommend looking at these resources:

https://en.cppreference.com/w/cpp/thread/thread
https://www.tutorialspoint.com/cplusplus/cpp_multithreading.htm

But my best suggestion is to keep it simple inside that scope, run a small calculation/execution if possible, threads are a complicated thing at first, and feels like it might put even more confusion.

**Comment by chethanapavan** [comment]
Hi, I wonder how to perform some task like calling multiple functions by pressing button and with out button freeze, i would like to get some suggestion

**Comment by PauloMenezes99** [comment]
How about when you want to use ImGui::SameLine(); but the if is screwing everything cuz it won't let it stay on the same line, what option do i have to align the buttons?

**Comment by DJLink** [comment]
> How about when you want to use ImGui::SameLine(); but the if is screwing everything cuz it won't let it stay on the same line, what option do i have to align the buttons? 

Where are you putting the SameLine()? Inside our outside The if? Please provide a sample so it's easier to evaluate

**Comment by PauloMenezes99** [comment]
if (ImGui::Button("Unload")); SameLine();
{
// Nvm, it's solved, i was doing this
}
if (ImGui::Button("Unload"))
{
//And its like this, was being dumb xD
}; SameLine();

Newcomer to this
