### ISSUE TITLE
Font Size Causing Crashes

### ISSUE THREAD

**Issue by FaTeLz** [ocornut/imgui#2483]
Whenever I inject ImGui it instant crashes. I've already trial and errored and realized it only ever happens when i increase font size above 9

```	ImFont* TextFont = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Tahoma\\Tahoma Regular.ttf", 11);```

**Comment by ocornut** [comment]
Sorry but #1586
Didn’t bother reading/filling template, blocked
