### ISSUE TITLE
PlotLines not handling NaN (was ImMin returns NaN if RHS is NaN)

### ISSUE THREAD

**Issue by bear24rw** [ocornut/imgui#2485]
**Version/Branch of Dear ImGui:**

Version: 1.70 WIP (16990)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: clang-1000.11.45.2
Operating System: macOS 10.14

**My Issue/Question:**

I am plotting data that sometimes has NaN values in it, sometimes this causes the PlotLines() to not render correctly. I believe I have traced it down to ImMin/ImMax not handling NaNs correctly.

**Screenshots/Video**

Current behavior:
<img width="188" alt="Screen Shot 2019-04-10 at 4 34 44 PM" src="https://user-images.githubusercontent.com/778194/55920681-942e2500-5bae-11e9-9a08-557dd77faf93.png">

Expected behavior:
<img width="262" alt="Screen Shot 2019-04-10 at 4 34 19 PM" src="https://user-images.githubusercontent.com/778194/55920705-9db78d00-5bae-11e9-8245-014af71fa1a3.png">

**Standalone, minimal, complete and verifiable example:** 
This example code produces a blank graph with current master
```
        ImGui::Begin("NaN Bug");
        float values[6] = {
            0.0f,
            1.0f,
            0.0f/0.0f,
            4.0f,
            5.0f,
            0.0f/0.0f};
        ImGui::PlotLines("Plot", values, 6);
        ImGui::End();
```
This code shows the ImMin handling NaNs differently than fmin if the NaN is on the right hand side.

```
#include <stdio.h>
#include <math.h>
#include "imgui.h"
#include "imgui_internal.h"
int main() {
    printf("fmin  %f %f\n", fmin(0.0f/0.0f, 5.0f), fmin(5.0f, 0.0f/0.0f ));
    printf("ImMin %f %f\n", ImMin(0.0f/0.0f, 5.0f), ImMin(5.0f, 0.0f/0.0f));
    return 0;
}
```
```
fmin  5.000000 5.000000
ImMin 5.000000 nan
```
**Possible fix:**
An immediate fix is to swap the argument order when calling ImMin/ImMax:
```
diff --git a/imgui_widgets.cpp b/imgui_widgets.cpp
index ad3126cd..d0f68f09 100644
--- a/imgui_widgets.cpp
+++ b/imgui_widgets.cpp
@@ -5521,8 +5521,8 @@ void ImGui::PlotEx(ImGuiPlotType plot_type, const char* label, float (*values_ge
         for (int i = 0; i < values_count; i++)
         {
             const float v = values_getter(data, i);
-            v_min = ImMin(v_min, v);
-            v_max = ImMax(v_max, v);
+            v_min = ImMin(v, v_min);
+            v_max = ImMax(v, v_max);
         }
         if (scale_min == FLT_MAX)
             scale_min = v_min;
```
Another fix could be to not rely on ImMin/ImMax for plot scaling:
```
diff --git a/imgui_widgets.cpp b/imgui_widgets.cpp
index ad3126cd..e18f900a 100644
--- a/imgui_widgets.cpp
+++ b/imgui_widgets.cpp
@@ -5521,8 +5521,8 @@ void ImGui::PlotEx(ImGuiPlotType plot_type, const char* label, float (*values_ge
         for (int i = 0; i < values_count; i++)
         {
             const float v = values_getter(data, i);
-            v_min = ImMin(v_min, v);
-            v_max = ImMax(v_max, v);
+            if (v < v_min) v_min = v;
+            if (v > v_max) v_max = v;
         }
         if (scale_min == FLT_MAX)
             scale_min = v_min;
```
However it seems like the "correct" fix is to have ImMin/ImMax behave the same as fmin and max. I'm not sure how to do that in a portable way though.

**Comment by ocornut** [comment]
Hello,

I am not sure either fixes are desirable asis, as they would rely on behaviors that are too subtle.

You say "Expected behavior" and "handling NaN correctly" but nothing in PlotXXX function description state that NaN are supported in the first place and neither there is one correct way to handle NaN.
The function as is are plotting continuous, evenly spaced samples. What do you even have NaN in there? Shouldn't be focus on a plotting system that can allow to plot arbitrary disjoint sources of data? 

In this case, the breakage appears to only spread from the code computing the minimum and maximum values (which can already be provided via the function parameters).

In the absence of better plotting function, I wouldn't mind adding a NaN test in there:

```
        for (int i = 0; i < values_count; i++)
        {
            const float v = values_getter(data, i);
            if (v != v) // Ignore NaN values
                continue;
            v_min = ImMin(v_min, v);
            v_max = ImMax(v_max, v);
        }
```

In the min/max calculation. However there's zero guarantee that any of those data will be displayed properly by the Line/Histogram renderers.
Would that work for you?

**Comment by bear24rw** [comment]
> You say "Expected behavior" and "handling NaN correctly" but nothing in PlotXXX function description state that NaN are supported in the first place and neither there is one correct way to handle NaN.

In regards to plotting I was expecting behavior similar to other plotting libraries like matplotlib in python:

```
import matplotlib.pyplot as plt
plt.plot([0,1,float('nan'),4,5,float('nan')])
plt.show()
```
<img width="326" alt="Screen Shot 2019-04-12 at 10 48 03 AM" src="https://user-images.githubusercontent.com/778194/56056238-7c6eb200-5d10-11e9-95a8-39ad53dc1579.png">

In regards to a generic min(float a, float b) function I was expecting behavior similar to the standard library fmin() function

> The function as is are plotting continuous, evenly spaced samples. What do you even have NaN in there? Shouldn't be focus on a plotting system that can allow to plot arbitrary disjoint sources of data?

I am plotting regularly sampled timeseries data from a hardware sensor. Sometimes the sensor cannot determine the value and returns a nan in the datastream. This is considered a legitimate value in our application. When looking at the timeseries plot it is useful to see when the sensor failed to read a value. 

> In this case, the breakage appears to only spread from the code computing the minimum and maximum values (which can already be provided via the function parameters).

I definitely could compute the min/max myself and handle nans however I want but it is more convenient for to have PlotLines be able to handle it.

> However there's zero guarantee that any of those data will be displayed properly by the Line/Histogram renderers.

Yes it would depend on how the backend handles a nan vertex position. Another check for nan could be added before calling AddLine if we really wanted to be explicit about it.

>Would that work for you?

Yes, that would be the most explicit to readers of the code that nans are handled specially.

**Comment by ocornut** [comment]
Thanks for the details!

Regardless of what fmin/fmax do, I think it would be unhealthy to speficially handle NaN in our ImMin/ImMax functions that those functions are used everywhere. It would inccur extra cost everywhere as well as muddling the responsability of handling NaN. If we found use for being explicitely with handling of NaN we could perfectly create alternative explicit min/max helpers and use them in specific spots.

I pushed the check in the PlotXXX functions computation of min/max range. (commit above)
As we refactor the Plot functions I'll take note that it may be convenient to be more explicit and provide guarantee (or lack of) as to how the different plotting tools handle NaN.

**Comment by bear24rw** [comment]
> I pushed the check in the PlotXXX functions computation of min/max range. (commit above)
As we refactor the Plot functions I'll take note that it may be convenient to be more explicit and provide guarantee (or lack of) as to how the different plotting tools handle NaN.

Great, thanks!
