### ISSUE TITLE
How to get size and position of 'content' area?

### ISSUE THREAD

**Issue by eddieparker** [ocornut/imgui#2486]
Is there an API for discovering the position and size of the region inside of the tabbed area?

i.e., if I have a docked window that looks like this:

![image](https://user-images.githubusercontent.com/1141487/56007833-c191d600-5c75-11e9-9c2e-1b45d6b17e1e.png)

How do i get the green rectangle as a position and size?

GetWindowPos/GetWindowSize() seem to get everything including the tab, which makes sense.  The GetWindowContentRegion APIs don't seem to respect the starting position either.

Is there a recommended way to do this?

**Comment by ocornut** [comment]
At this point the question is not really Docking related, when docked the layout and reported sizes are identical to any floating window with a title bar.

> The GetWindowContentRegion APIs don't seem to respect the starting position either.

I am not sure what you mean by "don't seem to respect the starting position either." but the best way to understand what is going on is _always_ to visualize your values. Get the min/max points, and draw a rectangle yourself, e.g. `ImGui::GetForegroundDrawlist()->AddRect(...)`.

The content region respect WindowPadding. In your case you may want to use PushStyleVar to push a zero WindowPadding for your window.

![image](https://user-images.githubusercontent.com/8225057/56032115-95339380-5d21-11e9-9367-b3a35d7de6ad.png)

**Comment by eddieparker** [comment]
Thanks for the tip about drawing the rectangle!  Definitely helped.

Turns out to get the area I wanted I needed to use the content region but offset it by the window pos; I didn't read the comment clearly enough to realize it was in window space.

``` cpp
		// Yellow is content region min/max
		{
			ImVec2 vMin = ImGui::GetWindowContentRegionMin();
			ImVec2 vMax = ImGui::GetWindowContentRegionMax();

			vMin.x += ImGui::GetWindowPos().x;
			vMin.y += ImGui::GetWindowPos().y;
			vMax.x += ImGui::GetWindowPos().x;
			vMax.y += ImGui::GetWindowPos().y;

			ImGui::GetForegroundDrawList()->AddRect( vMin, vMax, IM_COL32( 255, 255, 0, 255 ) );
		}
```

Thanks!

**Comment by ocornut** [comment]
> didn't read the comment clearly enough to realize it was in window space.

Right, apologies!
I think it was a huge design mistake to have window-space coordinates at all.
I hope maybe 2.0 can remove all those!

**Comment by eddieparker** [comment]
No worries! 

That said, just as feedback from a new-ish user: because the comments stretch out so far past my editor's width, it's a bit of a pain to read them, so I think I got lazy and didn't see the 'window space' comment.  I also don't know where I could read up on the different spaces to get them clear in my head; although it's pretty apparent once I thought about it.
