### ISSUE TITLE
How to remove, or change the shading effect when dialog open

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#2491]
I am wanting to provide a theme-edit series of options for my program but in order to see the result of the modifications 'real time' it would be preferable if the main canvas/background wasn't shaded out. 

Is this possible, have I missed something obvious (would not surprise me one bit!)

![s](https://user-images.githubusercontent.com/5660591/56075384-6d1d6080-5e05-11e9-953e-32f13d8769b4.png)

**Comment by DJLink** [comment]
I think you can use ImGuiCol_ModalWindowDimBg for that purpose

```
ImGuiStyle& style = ImGui::GetStyle();
style.Colors[ImGuiCol_ModalWindowDimBg] = ImVec4(R, G, B, A);
```
 
![image](https://user-images.githubusercontent.com/423769/56076814-0e3bf500-5dcd-11e9-9660-46a5dacc228a.png)

**Comment by inflex** [comment]
Perfect!   Thank you  (  basically set 'A'lpha to 0 ).

![s](https://user-images.githubusercontent.com/5660591/56077093-4ec25f80-5e1b-11e9-98b6-b5cb1688ccd4.png)

**Comment by ocornut** [comment]
Note this is only shown when using a modal dialog which are meant to disable interactions with other windows.

If you open just any other kind of window it wouldn’t display the dimming bg. You may just use a regular window and let the user interact with it along with the rest of the app!

**Comment by inflex** [comment]
>  You may just use a regular window and let the user interact with it along with the rest of the app!

That option was also suggested by another person (outside of this thread).  Considering the nature of the dialog, it might be a superior option.  Thank you.
