### ISSUE TITLE
How to hide window when the we click the background of it

### ISSUE THREAD

**Issue by SuperWangKai** [ocornut/imgui#2495]
Very similar use scenario to #2491 -

If we use a regular window as the popup instead of a modal, sometimes, we would like to hide the popup window when user click the space out of the window's rectangle. How can we achieve this.

Thanks.

**Comment by ocornut** [comment]
Your question is ambiguous. Please provide more details and be accurate with your terminology. 

It sounds like maybe you just want to use a Popup window (but not a Modal Popup) ? Closing themselves when clicking outside _is_ the behavior of Popup.

**Comment by SuperWangKai** [comment]
Thanks @ocornut

There is a question, if we use popup, how can we get the event of window closing "event"? 
By knowing when the popup close, we can handle things like reverting the operations or committing all the changes made on the pupup window.

**Comment by nicolasnoble** [comment]
> how can we get the event of window closing "event"?

```C++
static bool myPopupIsOpen = false;
if (someCondition) {
  ImGui::OpenPopup("myPopup");
  myPopupIsOpen = true;
}

if (ImGui::BeginPopup("myPopup") {
  ImGui::Text("Contents of myPopup");
  ImGui::EndPopup();
} else if (myPopupIsOpen) {
  myPopupIsOpen = false;
  PopupJustGotClosedEvent(); // handle rollbacks or commits here
}
```

**Comment by SuperWangKai** [comment]
Thanks for the reply! @nicolasnoble 

Ok, I met another issue... how can we close the popup window by clicking its background?

**Comment by ocornut** [comment]
Your question are ambiguous again. What do you mean by background? Please check the demo window, it feels like you haven’t explored enough of it which affects both your understanding of popups and the terminology you are using.

**Comment by SuperWangKai** [comment]
OK, I got it. It is the code structure of mine which mislead me. Nicolas' code works and the sample is useful as usual.
