### ISSUE TITLE
exits on "g.PlatformIO.Platform_CreateWindow(viewport)" with error code 0x3

### ISSUE THREAD

**Issue by khanIdris** [ocornut/imgui#2500]
I'm using the imgui docking branch with dx11. At first it ran fine, until I called imgui::Being() and imgui::End(), my program kept crashing with error code 0x3.
after debugging, I found that it was exiting on the line "g.PlatformIO.Platform_CreateWindow(viewport)" in imGui.cpp

the program runs fine unless I try to draw a window. i.e call  imgui::Being() or imgui::End()

// Here's the code

		// Start the Dear ImGui frame
		ImGui_ImplDX11_NewFrame();
		ImGui_ImplWin32_NewFrame();
		ImGui::NewFrame();

		{
		       ImGui::Begin("Another Window");   
		       ImGui::End();
	        }

		// Rendering
		ImGui::Render();
		pd3dDeviceContext->OMSetRenderTargets(1, &g_mainRenderTargetView, NULL);
		ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());

		if (io->ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
		{
			ImGui::UpdatePlatformWindows();
			ImGui::RenderPlatformWindowsDefault();
		}

**Comment by ocornut** [comment]
It looks like you have asserts disabled (please do read the Issues Guidelines carefully, and make sure you have asserts enabled when you use dear imgui, and please try to submit entire callstacks). Asserts would have caught your issue earlier.

I am guessing you have `ImGuiConfigFlags_ViewportsEnable` config flag enabled in your app but the bindings hasn't been initialized with them enabled, or doesn't support them.

**Comment by khanIdris** [comment]
![assert](https://user-images.githubusercontent.com/34336372/56269479-62b6db80-6111-11e9-931b-404d9b16ed42.png)

here's the assertion, 
even after calling ImGui::SetCurrentContext(ctx);

**Comment by khanIdris** [comment]
I added a depth Stencil and it Worked!
