### ISSUE TITLE
Secondary viewports not rendering with DX9 back-end

### ISSUE THREAD

**Issue by dumbasPL** [ocornut/imgui#2502]
**Version/Branch of Dear ImGui:**

Version: 1.70 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: MSVC Visual Studio 2019 (win32 and x64)
Operating System: Windows 10 (1903)

**My Issue**

when a window becomes wider or higher than the original one then it becomes black.
Stuff like buttons still work if you know where to click so this appears to be just a rendering problem.
I also tested this on other directx backends and it appears it is just the dx9 one

**Video**

https://youtu.be/wvagdgWFk_4

**Standalone, minimal, complete and verifiable example:**
how to replicate:
- clone docking branch
- compile and run the dx9 example

**Comment by Tanc-ANT** [comment]
Hi @ocornut . 
I found a bug in DX9 Docking branch.  It has a similar operation what  @dumbasPL  did. So I decided put this problem in this issue. 

Version/Branch of Dear ImGui:

Version: 1.70 WIP
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: MSVC Visual Studio 2015(Debug x64)
Operating System: Windows 10 (1803)

My Issue

It will cause the assert in debug mode when I drag a child window out of the main window then resize the main window.  In the release mode the program will crash.

Video

https://youtu.be/n6VdHRYny6g

Standalone, minimal, complete and verifiable example:
how to replicate:

clone docking branch
compile and run the dx9 example

**Comment by ocornut** [comment]
Thank you both. I confirmed there is an issue with DX9 support for multi-viewports as you reported.

Linking to original PR #2394, maybe @giladreich would want to have a look?

**Comment by giladreich** [comment]
Hey Omar :) Thanks for the ping! I'm currently quiet busy with stuff that hopefully the next month I'll have time to dig into this issue.

**Comment by ocornut** [comment]
Should be all fixed now! Thanks for @Tanc-ANT for the help.
Also fixed the black viewport issue.
