### ISSUE TITLE
Rendering issue when the window draw list command buffer is too large

### ISSUE THREAD

**Issue by ArekSredzki** [ocornut/imgui#2504]
**Version/Branch of Dear ImGui:**

Version: 1.70 WIP (20f0cb02), but this issue occurred on earlier versions as well
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp
Compiler: clang 6.0.0
Operating System: Ubuntu 16.04

**My Issue/Question:**

In doing some data plotting (with the [utility here](https://github.com/ocornut/imgui/issues/1729#issuecomment-383354190)), I've found that if a window draw list command buffer exceeds a certain length then rendering issues occur.

After some digging, I've found that the issue occurs once the following value exceeds around ~`200000`. On one of my machines the threshold is around ~`240000` and ~`290000` on another.
```
ImGuiWindow* window = GetCurrentWindow();
window->DrawList->CmdBuffer.Data[window->DrawList->CmdBuffer.Size-1]
```

The issue seems to get worse as more commands get added.

Interestingly, the issue does not propagate outside of the window in which it is occuring.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/879918/56460424-50c67a00-6357-11e9-95e7-c0d3a0768b0c.png)
![image](https://user-images.githubusercontent.com/879918/56460429-62a81d00-6357-11e9-8dfd-f7aea486ccb5.png)

Screenshots from the example below:
![image](https://user-images.githubusercontent.com/879918/56460685-7a81a000-635b-11e9-8eec-61d539959b15.png)
![image](https://user-images.githubusercontent.com/879918/56460694-908f6080-635b-11e9-802f-ac2382263aed.png)

**Standalone, minimal, complete and verifiable example:**
```
ImGui::Begin("Example Bug");

static int dot_count = 10;
ImGui::SliderInt("Number of dots", &dot_count, 1, 20000);

ImGuiWindow* window = ImGui::GetCurrentWindow();

for (int i = 0; i < dot_count; i++) {
    window->DrawList->AddCircleFilled(ImVec2(5, 5), 5, IM_COL32(255, 0, 0, 255), 4);
}

auto &cmd_buffer = window->DrawList->CmdBuffer;
auto& draw_cmd = cmd_buffer.Data[cmd_buffer.Size-1];
printf("draw_cmd.ElemCount      %d\n", draw_cmd.ElemCount);

ImGui::End();
```

Your help is much appreciated! Thank you!

**Comment by ArekSredzki** [comment]
Here's a slightly more visually-complete example:
```
ImGui::Begin("Example Bug");

static int dot_count = 10;
ImGui::SliderInt("Number of dots", &dot_count, 1, 10000);

ImGuiWindow* window = ImGui::GetCurrentWindow();

for (int i = 0; i < dot_count; i++) {
    constexpr int kCircleRadius = 400;
    ImVec2 dot_position{};
    dot_position.x = std::sin(i / (double) dot_count * 2 * M_PI) * kCircleRadius + kCircleRadius;
    dot_position.y = std::cos(i / (double) dot_count * 2 * M_PI) * kCircleRadius + kCircleRadius;
    dot_position += window->DC.CursorPos;
    const int red_value = (i / (double) dot_count) * 255;
    window->DrawList->AddCircleFilled(dot_position, 1, IM_COL32(red_value, 0, 0, 255), 4);
    window->DrawList->AddDrawCmd();
}

auto &cmd_buffer = window->DrawList->CmdBuffer;
auto& draw_cmd = cmd_buffer.Data[cmd_buffer.Size-1];
printf("draw_cmd.ElemCount      %d\n", draw_cmd.ElemCount);

ImGui::End();
```
![image](https://user-images.githubusercontent.com/879918/56460855-478cdb80-635e-11e9-8939-729cb718c511.png)
![image](https://user-images.githubusercontent.com/879918/56460860-5e333280-635e-11e9-814c-9f9e5ccf1329.png)

**Comment by ArekSredzki** [comment]
I just tried adding a call to `window->DrawList->AddDrawCmd();` in order to limit the number of draw commands in any one instance of the command buffer.

If I call `window->DrawList->AddDrawCmd();` on every iteration of the loop in my example, and only have one dot per instance of the command buffer, the issue is worse.

However, if I only call `window->DrawList->AddDrawCmd();` when the number of elements is getting "too large", I no longer see the weird rendering issue. That said, It doesn't appear that points that get placed into the additional draw commands get rendered at all.

![image](https://user-images.githubusercontent.com/879918/56461007-6f7d3e80-6360-11e9-913c-1c76f94bb350.png)
![image](https://user-images.githubusercontent.com/879918/56461011-8c197680-6360-11e9-9a50-46a775295bad.png)


```
ImGui::Begin("Example Bug");

static int dot_count = 10;
ImGui::SliderInt("Number of dots", &dot_count, 1, 50000);

ImGuiWindow* window = ImGui::GetCurrentWindow();

auto &cmd_buffer = window->DrawList->CmdBuffer;

for (int i = 0; i < dot_count; i++) {
    auto& draw_cmd = cmd_buffer.Data[cmd_buffer.Size-1];
    if (draw_cmd.ElemCount >= 200000) {
        printf("draw_cmd.ElemCount      %d\n", draw_cmd.ElemCount);
        window->DrawList->AddDrawCmd();
    }

    constexpr int kCircleRadius = 400;
    ImVec2 dot_position{};
    dot_position.x = std::sin(i / (double) dot_count * 2 * M_PI) * kCircleRadius + kCircleRadius;
    dot_position.y = std::cos(i / (double) dot_count * 2 * M_PI) * kCircleRadius + kCircleRadius;
    dot_position += window->DC.CursorPos;
    const int red_value = (i / (double) dot_count) * 255;
    window->DrawList->AddCircleFilled(dot_position, 1, IM_COL32(red_value, 0, 0, 255), 4);
}

auto& draw_cmd = cmd_buffer.Data[cmd_buffer.Size-1];
printf("draw_cmd.ElemCount      %d\n", draw_cmd.ElemCount);

ImGui::End();
```

**Comment by ArekSredzki** [comment]
Ugh.. after far too many hours of searching, I finally found the issue.

I had to uncomment the line that changes `ImDrawIdx` to a 32 bit uint in `imconfig.h` as the vertex indexes were overflowing.

Mistakenly, I was searching for issues in the largest numbers when I should have noticed that the issues started precisely when the vertex count passed 2^32.

Notably, there was another issue in our platform rendering function which caused the `idx_buffer` offset to overflow in the cases where I was adding new draw commands when the element count got high. This overflow was hiding the other issue in this condition.

Hopefully this is useful to someone who runs into a similar issue.

Perhaps it would be good to add a note about the 32 bit option to the FAQ?

**Comment by ocornut** [comment]
There is an Assert call that checks exactly for this in Render() or EndFrame(). It is surprising you haven’t stumbled on it earlier?

**Comment by ArekSredzki** [comment]
@ocornut That would be a great feature but I don't see such an assert.

I do see that there are asserts for things such as `Mismatched Begin/BeginChild vs End/EndChild calls`, but that's different.

**Comment by ArekSredzki** [comment]
I feel that the check to see whether there is a vertex index overflow must happen elsewhere anyway. Likely in imgui_draw.

**Comment by ocornut** [comment]
`AddDrawListToDrawData()` has this:
```
// Check that draw_list doesn't use more vertices than indexable (default ImDrawIdx = unsigned short = 2 bytes = 64K vertices per ImDrawList = per window)
// If this assert triggers because you are drawing lots of stuff manually:
// A) Make sure you are coarse clipping, because ImDrawList let all your vertices pass. You can use the Metrics window to inspect draw list contents.
// B) If you need/want meshes with more than 64K vertices, uncomment the '#define ImDrawIdx unsigned int' line in imconfig.h to set the index size to 4 bytes.
//    You'll need to handle the 4-bytes indices to your renderer. For example, the OpenGL example code detect index size at compile-time by doing:
//      glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer_offset);
//    Your own engine or render API may use different parameters or function calls to specify index sizes. 2 and 4 bytes indices are generally supported by most API.
// C) If for some reason you cannot use 4 bytes indices or don't want to, a workaround is to call BeginChild()/EndChild() before reaching the 64K limit to split your draw commands in multiple draw lists.
if (sizeof(ImDrawIdx) == 2)
    IM_ASSERT(draw_list->_VtxCurrentIdx < (1 << 16) && "Too many vertices in ImDrawList using 16-bit indices. Read comment above");
```

Could you confirm that this is indeed getting triggered? Are your asserts enabled? Try to add `IM_ASSERT(0)` and make sure it is triggering.

**Comment by ArekSredzki** [comment]
Thanks, It appears that our CMake config for this project didn't enable asserts for the `RelWithDebInfo` configuration so the asserts were never hit. At least now we'll know for next time :grimacing:

**Comment by ocornut** [comment]
I have added a note that I'd like the future "Integration Checker" window to include a test for making sure asserts are enabled.
