### ISSUE TITLE
Flickering Bug with SplitChannel, / MergeChannels and DrawList->AddImage

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#2506]
Version: .70 WIP (16990)
Branch: master

I have a weird flickering bug. 

I use SplitChannel, / MergeChannels for have a style applied on a bg of a group

i have a pingpong texture displayed with drawlist->AddImage , so the id of the texture displayed change after each swap.
see in the gif, the flickering is due to the image display. when i mouse over the flickering stop

if i comment drawlist->AddImage, it work, when i uncomment, the next items are flckering.
not sure if its a bug of imgui or from my softs.

![2019-04-20_22-22-05](https://user-images.githubusercontent.com/1434736/56461928-c6176680-63ba-11e9-964a-3ee25661d0fd.gif)

**Comment by ocornut** [comment]
Hello,
Could you try to make a minimal repro?
Thank you.

**Comment by aiekick** [comment]
ok, i will try.

**Comment by aiekick** [comment]
its difficult to do a small repro.

the problem appear only when i split channels, and only with my pingpong system.

each rendering of my texture, i swap the texture id. (back becone front and front become back of what its uplaoded to the gpu)

after that i calcl en render imgui.

i dont know how, but my texture is used by the next imgui item control. this is why its filickering.

 i will inspect the split channel method

**Comment by ocornut** [comment]
@aiekick Any news on this?
The point of a repro is to narrow down the issue. There's probably a bug in the channel splitter but it would help if you tried to made a repro. It doesn't look hard, and I can't be guessing what your code is doing.

**Comment by aiekick** [comment]
i know what is the goal of that. but i have tried to do a small repro but i not got the bug. i thinck i have a gl context bug since start of NoodlesPlate dev, and maybe some memory leaks somwhere but nout found where (because i see sometime the font texture in place of my textures.
the problem occur when i switch the texture id, but liake said not found a bug with a minimal case. i will search more, maybe is near the texture binding, when i fill one..

**Comment by aiekick** [comment]
finally succeed to isolate the problem. i have created a repo with a fully workable example : https://github.com/aiekick/ImGui_DrawList_ChannelsSplitter_Bug
use the GLFW Opengl3 sample and try
you were right, my double buffuired system is not the problem, but a texture creation before the loop.. its weird

**Comment by aiekick** [comment]
i found, that if i intialize my texture after your (for the font), it work like a charm.
we see the font texture in each framed group and all texts.

is there a possibility than using a texture number other than 1 for the font (the first texture is the font i thinkc), can cause a bug somewhere ? i know we can have more font so more texture numlber, but the frist font is always 1 no ?, if his initialization in done first of all.

**Comment by aiekick** [comment]
i have remove my texture creation and,

in ImGui_ImplOpenGL3_CreateFontsTexture()

i have duplicated the line "glGenTextures(1, &g_FontTexture);"

like that i ensure than the first texture number will be 2 instead of 1. the bug is appearing

no texts under ImGui::Images

**Comment by aiekick** [comment]
i thinck the bug is in ImDrawListSplitter::Merge(ImDrawList* draw_list)

at last if i always do AddDrawCmd instead of UpdateClipRect,=> no bug.
maybe we need to do UpdateTextureID() after UpdateClipRect no ? it resolve the bug too
maybe in some case he can add two drawcalls. not sure if its normal :)

**Comment by ocornut** [comment]
I would like to get this fixed but it is still extremely tedious to wade through the noise of an entire repo and so many messages, for what should be a 10 lines repro...

**Comment by aiekick** [comment]
i know but it was not easy to found the bug.  im not an expert in dev..
for summary i have added "draw_list->UpdateTextureID();" after the " draw_list->UpdateClipRect();" in ImDrawListSplitter::Merge(ImDrawList* draw_list)

**Comment by ocornut** [comment]
All I have asked is for a minimal repro (instead of large project) in order to understand the bug.
Here I made it now:

```
// Confirm hard-coded values 0x01 (atlas) and 0x02 (empty) do what we expect with our OpenGL back-end
{
    ImGui::Text("1:");
    ImGui::SameLine();
    ImGui::Image((ImTextureID)1, ImVec2(50, 50));   // Confirming this is our atlas
    ImGui::SameLine();
    ImGui::Text("2:");
    ImGui::SameLine();
    ImGui::Image((ImTextureID)2, ImVec2(50, 50));   // Confirming this is showing as black
}

// Bug repro
{
    ImDrawList* draw_list = ImGui::GetWindowDrawList();
    draw_list->ChannelsSplit(2);
    draw_list->ChannelsSetCurrent(0);
    ImGui::Text("Hello");
    draw_list->ChannelsSetCurrent(1);
    ImGui::Image((ImTextureID)2, ImVec2(50, 50));
    draw_list->ChannelsMerge();
}
```

![image](https://user-images.githubusercontent.com/8225057/65068297-acd60e80-d988-11e9-87ce-de9b7b4cf236.png)

**Comment by ocornut** [comment]
Now I have the repro I can understand the fix the bug, should be fixed now.
I understand you had found the fix before, but you never let me understand the issue. I cannot apply the fix if I don't understand the issue. This is why the minimal repro is required.

Thanks for reporting!

**Comment by aiekick** [comment]
i have created a project here :https://github.com/aiekick/ImGui_DrawList_ChannelsSplitter_Bug ..
it was a full repro of the bug. its easy now after some iterations but it was not before that

**Comment by ocornut** [comment]
Lots of noise (unnecessary code to understand) in this entire repository, the minimal repro I postes above is 7 lines, it can’t get simpler. 

Thanks for finding this!
