### ISSUE TITLE
Change window title while keeping old window

### ISSUE THREAD

**Issue by emoon** [ocornut/imgui#251]
Hi,

I have a specific problem which is due to using StateStorage. I have some code that looks like this

```C++
ImGui::Begin(state->title, ...);
MyData* data = (MyData*)GetStateStorage()->GetVoidPtr();
data->foo = 1;
state->title = "Change to something new"
```

The next time around ImGui::Begin(...) starts it will create a new window as the name to it has changed and my data->foo will go away.

I wonder if there is some way to prevent this? What I really do is only want to change the title that is being displayed but when looking at the code I can't see any obvious way to do it without changing it.

Ideas?

**Comment by ocornut** [comment]
You can use the ### operator for that to dissociate the ID completely from the title for this sort of case.
See the example called "Manipulating window title", it's in the Example menu.

**Comment by emoon** [comment]
Sweet! Works :) Thanks!
