### ISSUE TITLE
popupmodel rounding, selected item highlight rounding possible?

### ISSUE THREAD

**Issue by user698869** [ocornut/imgui#2511]
Hello,

I'm sorry if this is a dumb question, but I did not found an option to round the edges of the selected item in popup window. https://prnt.sc/ngcayc

As you can see there, the pop-up has rounded edges but this looks bad if you select first/last item especially when the selection goes above the corners.

Thanks for help.

**Comment by ocornut** [comment]
This isn't possible at the moment.

Adding a SelectableRounding field currently creates three issues:
- MenuItem in menu bar are too tall which affects rounding visibility and looks odd (could be fixed).
- Same name/semantic for both Selectable vs MenuItem may be problematic.
- Hovering Selection of TreeNode not affected. Perhaps should rename to SelectionRounding?

So it won't/cannot be merged presently.
Instead you should try to keep a non-zero WindowPadding for those case.

See patch
[SelectableRounding.zip](https://github.com/ocornut/imgui/files/3116127/SelectableRounding.zip)

**Comment by user698869** [comment]
Thanks, that works.
