### ISSUE TITLE
Remove ImGui window to reveal glfw window

### ISSUE THREAD

**Issue by Jeremy11712** [ocornut/imgui#2512]
Is there a way to terminate an ImGui window? I have a button that, when pressed, Id like the ImGui window to terminate/collapse thus revealing the GLFW window behind it.

**Comment by Wizzard033** [comment]
Just don't draw the ImGui window
```
if (!windowActive) { return; }
// all your ImGui stuff for the given window here
```

**Comment by Jeremy11712** [comment]
Maybe I do not follow... But I must draw the ImGui window for usage, but upon clicking a certain button (ie start) I would like the ImGui window to go away thus exposing the game that exists in my glfw window :)

**Comment by Wizzard033** [comment]
Yes - so you only do the code for the ImGui window when you're using it

windowActive = true when the window is open
windowActive = false when the window is closed

You can check when the window is closed by feeding a boolean pointer to ImBegin

**Comment by ocornut** [comment]
The programmer guide starts with:
"Your code creates the UI, if your code doesn't run the UI is gone!"

If you stop submitting the window it will stop displaying.
Please study the examples/ app and demo code in depth.
