### ISSUE TITLE
InputTextMultilineWithHint possibility?

### ISSUE THREAD

**Issue by jpan127** [ocornut/imgui#2513]
I have seen `InputTextWithHint` has been implemented, but I think `InputTextMultilineWithHint` is missing.  From what I can tell, it seems an input `const char *hint` can just be passed into this function, and then passed down to `InputTextEx`.

@ocornut What do you think?

**Comment by ocornut** [comment]
My intuition when adding the original function was the hint it wasn't much useful for multi-text, and trying to fend off API explosion I passed on it. 

It's a 1 line function so you are free to add it in your own code? (remember you can include `imgui_internal.h` and add function in `ImGui::` namespace from your own source code).

**Comment by jpan127** [comment]
Yea, we have already adopted it into our own code, just thought that this might be useful for others and maybe you had some insights into why it might not be a good idea.

**Comment by ocornut** [comment]
In which context are you using it?

**Comment by jpan127** [comment]
1) Using it as a read only text box, and the hint says what text will eventually populate the box with.
2) Will maybe in the future use it as an input text box, which will also be desirable with a hint.

**Comment by ocornut** [comment]
As mentioned above the reason is that we need to limit API entry points, and you can recreate this API with a trivial function on your side:

```
namespace ImGui
{
bool InputTextMultilineWithHint(const char* label, const char* hint, char* buf, size_t buf_size, const ImVec2& size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data)
{
    return InputTextEx(label, hint, buf, (int)buf_size, size, flags | ImGuiInputTextFlags_Multiline, callback, user_data);
}
};
```

So I suggest you use that?

**Comment by ocornut** [comment]
Closing as answered.

**Comment by Patitotective** [comment]
I'm confused about how to implement this on v1.87 since the `Multiline` flags is now on `ImGuiInputTextFlagsPrivate` and `InputTextEx` accepts `ImGuiInputTextFlags`. Is there another way to achieve the multiline text input with hint? Or am I missing something about the API?
Thanks.

**Comment by ocornut** [comment]
There’s no change you only need to include imgui_internal.h to access the enum. Those types are loosely typed.
