### ISSUE TITLE
Multiple InputTextMultiline causes flickering

### ISSUE THREAD

**Issue by jpan127** [ocornut/imgui#2514]
**Version/Branch of Dear ImGui:**
Version: dfb82d5
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp
Compiler: clang 6.0.0
Operating System: Ubuntu 16.04

**My Issue/Question:**

I am currently using `InputTextMultiline` with no flags (or read only) to display multi-line text.  The text is displayed well with a single text box.  However, adding multiple text boxes in the same window produces rendering issues (flickering).

Just speculating, but it seems the last box to be added never flickers like the others.

**Screenshots/Video**

10 boxes:
![image](https://user-images.githubusercontent.com/19752007/56776920-a8178080-6783-11e9-8e42-3af1191432ca.png)

1 box:
![image](https://user-images.githubusercontent.com/19752007/56776931-b1085200-6783-11e9-9e18-e9773dc1eaec.png)

**Standalone, minimal, complete and verifiable example:**
```c++
ImGui::Begin("Labels");

static int num_boxes = 10;
ImGui::SliderInt("", &num_boxes, 1, 10);

for (int i = 0; i < num_boxes; ++i)
{
    constexpr ImGuiInputTextFlags kFlags = ImGuiInputTextFlags_None;
    char text[10] = "test";
    const std::string label = "##" + std::to_string(i);
    ImGui::InputTextMultiline(label.c_str(), text, 10,
                       ImVec2(-1.0f, ImGui::GetTextLineHeight() * 2), kFlags);
}

ImGui::End();
```

Thanks!

**Comment by ArekSredzki** [comment]
@ocornut Your help in hunting down this issue would be much appreciated. Assertions are enabled and this issue happens regardless.

**Comment by ocornut** [comment]
Hello, I cannot repro this when I pasted the code, I can only assume the issue relates to something that has been omitted here.

**Comment by ocornut** [comment]
You can use the Metrics windows to inspect the individual draw commands and confirm that the correct data is being output for the renderer to use. Which renderer is being used has been omitted from the post but I assume it is imgui_impl_opengl3.cpp one way or another it is choking on that data (could even be a driver issue if unlucky?). Are multi-viewports enabled?

**Comment by ocornut** [comment]
Any news? @jpan127 
In the absence of a working repro I'll assume you have a problem somewhere else in your code.

**Comment by jpan127** [comment]
@ocornut Hi sorry, I have been busy with some other issues.  Please keep this ticket open and I will try to provide some more context soon.

**Comment by ocornut** [comment]
I'll close this for now, when you make another post here I will reopen the issue. Thanks!
