### ISSUE TITLE
Black rectangle with directx9

### ISSUE THREAD

**Issue by anastasiaklimova3303** [ocornut/imgui#2515]
I am trying to create imgui::image on directx9
I am loading texture via D3DXCreateTextureFromFileEx

But I can see only black rectangle instead of my picture.
Texture loading code:
![изображение](https://user-images.githubusercontent.com/32042785/56817873-17a67200-684f-11e9-81ce-65c23a87f56f.png)

Image drawing code:
![изображение](https://user-images.githubusercontent.com/32042785/56817898-2856e800-684f-11e9-8285-41f22d1278f0.png)

Thank you!

**Comment by ocornut** [comment]
Not following issue guidelines, closing.
