### ISSUE TITLE
black rectangle instead of my picture.

### ISSUE THREAD

**Issue by linablow** [ocornut/imgui#2516]
**Version/Branch of Dear ImGui:**
Version: 59f012d65603c5961b6eb3f6d2a003f0ba9d100e
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp
Compiler: Visual Studio 2019 (v142)
Operating System: Windows x64

**My Issue/Question:**

I am trying to create imgui::image on directx9
I am loading texture via D3DXCreateTextureFromFileEx
But I can see only black rectangle instead of my picture.

**Screenshots/Video**

Texture loading code:
![изображение](https://user-images.githubusercontent.com/32042785/56818772-05c5ce80-6851-11e9-85ff-1586da2aa8a5.png)

Image drawing code:
![изображение](https://user-images.githubusercontent.com/32042785/56818786-0a8a8280-6851-11e9-95fe-23d6e477def4.png)

Thank you!

**Comment by nicolasnoble** [comment]
As a general rule of thumb, posting a screenshot of your code isn't what the template is asking for. The screenshot part is about showing what imgui does. Code is much better shared in textual form that we can then copy paste.

**Comment by linablow** [comment]
Code text (no screenshots)

Texture loading code:
```cpp
VOID DXHooking::CreateTexture(CHAR* file, LPDIRECT3DTEXTURE9* result) {

	HRESULT res = 
		D3DXCreateTextureFromFileEx(this->device, 
			file,
			D3DX_DEFAULT, 
			D3DX_DEFAULT, 
			D3DX_DEFAULT, 0, 
			D3DFMT_UNKNOWN, 
			D3DPOOL_DEFAULT,
			D3DX_FILTER_NONE,
			D3DX_FILTER_NONE, 0, NULL, NULL,
		result);

}
```

Texture loading code:
```cpp
ImTextureID texID = reinterpret_cast<ImTextureID>(this->logoTexture);

	ImGui::Image(texID, ImVec2(200.f, 110.f));
```

**Comment by ocornut** [comment]
This doesn't consistute a repro.
Most likely the error is not in this code but in the code you are omitting.
Please submit a full repro.

**Comment by linablow** [comment]
```cpp
BOOL DXHooking::GetDX9(DXContainer* result) {
	Direct3DCreate9_t CreateEnv = (Direct3DCreate9_t)GetProcAddress(GetModuleHandleA("d3d9.dll"), "Direct3DCreate9");

	IDirect3D9* dxEnv = CreateEnv(D3D_SDK_VERSION);
	HWND hWindow = GetDesktopWindow();


	D3DDISPLAYMODE displayMode;
	unsigned long long vmt = **(unsigned long long**)&dxEnv;

	GetAdapterDisplayMode_t pGetAdapderDisplayMode = (GetAdapterDisplayMode_t)((*(unsigned long long*)(vmt + 8 *
		GET_ADAPTER_DISPLAY_MODE_INDEX)));

	pGetAdapderDisplayMode(dxEnv, D3DADAPTER_DEFAULT, &displayMode);

	D3DPRESENT_PARAMETERS pp;
	ZeroMemory(&pp, sizeof(pp));

	pp.Windowed = TRUE;
	pp.hDeviceWindow = hWindow;
	pp.BackBufferCount = 0;
	pp.BackBufferWidth = 0;
	pp.BackBufferHeight = 0;
	pp.BackBufferFormat = displayMode.Format;
	pp.SwapEffect = D3DSWAPEFFECT_DISCARD;

	IDirect3DDevice9* pDevice = NULL;

	CreateDevice_t pCreateDevice = (CreateDevice_t)((*(unsigned long long*)(vmt + 8 * CREATE_DEVICE_INDEX)));
	HRESULT res = pCreateDevice(
		dxEnv,
		D3DADAPTER_DEFAULT,
		D3DDEVTYPE_HAL,
		hWindow,
		D3DCREATE_SOFTWARE_VERTEXPROCESSING | D3DCREATE_DISABLE_DRIVER_MANAGEMENT,
		&pp,
		&pDevice
	);

	//pDevice->SetTextureStageState(0, D3DTSS_COLOROP, D3DTOP_ADD);
	//pDevice->SetTextureStageState(0, D3DTSS_COLORARG1, D3DTA_DIFFUSE);
	//pDevice->SetTextureStageState(0, D3DTSS_COLORARG2, D3DTA_TEXTURE);

	if (!SUCCEEDED(res)) {
		return FALSE;
	}

	result->d3d = dxEnv;
	result->device = pDevice;

	this->device = pDevice;

	return TRUE;
}
```

I am hooking dx9 EndScene

Hook function:
```cpp
HRESULT DX9Hook(IDirect3DDevice9* pd3dDevice) {

	if (!hooking->imGuiInit) {
		ImGui::CreateContext();
		ImGuiIO& io = ImGui::GetIO();

		ImGui_ImplWin32_Init(FindWindowA(NULL, WINDOW_NAME));
		ImGui_ImplDX9_Init(pd3dDevice);

		Globals::gui->Init();

		hooking->imGuiInit = TRUE;
	}

	ImGui_ImplDX9_NewFrame();
	ImGui_ImplWin32_NewFrame();
	ImGui::NewFrame();

	Globals::gui->RenderGUI();

	ImGui::EndFrame();
	ImGui::Render();
	ImGui_ImplDX9_RenderDrawData(ImGui::GetDrawData());

	DX9EndScenePrototype_t orig = hooking->GetOriginalEndScene();
	return orig(pd3dDevice);
}
```

And this is a part of RenderGUI() called before ImGui::End:
```cpp
ImTextureID texID = reinterpret_cast<ImTextureID>(this->logoTexture);

ImGui::Image(texID, ImVec2(200.f, 110.f));
```

And this is Init:
```cpp
this->defaultFont = ImGui::GetIO().Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\calibri.ttf", 
		GUIConfig::FontSize);
	
this->hooker->CreateTexture((char*)"C:\\Users\\Riza\\Desktop\\d2jscore_config\\logo.png", 
	&this->logoTexture);
```

The picture is valid and texture loading returns D3D_OK

**Comment by linablow** [comment]
But it shows black rectangle(

**Comment by linablow** [comment]
Other elements are drawn without problems, I have problem only with images

**Comment by ocornut** [comment]
This doesn't consistute a repro.
Most likely the error is not in this code but in the code you are omitting.
Please submit a full repro.

**Comment by linablow** [comment]
I can't share full source code, because there are a lot of files. But I sent you part that does imgui render.
Why this problem with black rect can be at all?

**Comment by ocornut** [comment]
Use the Metrics window in DrawList section to look at the emitted draw call, and you can use a debugger to step insite the render function.

Basically you are making a mistake in your DX9 code, so this is not much of a dear imgui question.
You can build a minimal repro that exhibit the issue and likely while building it you will understand your error. But we can't do much more than that.

**Comment by linablow** [comment]
Ok. anyway, thank you!

**Comment by nicolasnoble** [comment]
Even if your work contains a lot of files, it should be doable for you to create a very small project that you can publish as a github repository and that we can build ourselves.

**Comment by linablow** [comment]
I solved it. It was my fault, sorry for wasting your time(

**Comment by ocornut** [comment]
Consider explaning the issue or mistake in question, may be useful for other users.

**Comment by linablow** [comment]
I am hooking endscene inside of the game and I was creating new device, instead of using existing.

**Comment by linablow** [comment]
I just found offset to existing device and used it
