### ISSUE TITLE
glGetError on CORE profile glfw

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#2519]
**Version/Branch of Dear ImGui:**

Version: 1.70WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: the sample: example_glfw_opengl3

Operating System: Windows7

**My Issue/Question:**

When setting in this example
```cpp
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  // 3.2+ only
```
and checking glGetError as

```cpp
        glfwMakeContextCurrent(window);
	int err = glGetError();
	if(err!=GL_NO_ERROR)
           printf("glError %d\n",err);
        glfwSwapBuffers(window);
```
example is running whitout any visual difference but glGetError is reporting 1280
It does not happen with COMPAT profile.

**Comment by sonoro1234** [comment]
more info
```
gl.VENDOR       ATI Technologies Inc.
gl.RENDERER     Radeon (TM)  HD 7670M
gl.VERSION      3.2.11411 Core Profile Context
```

**Comment by ocornut** [comment]
The `example_glfw_opengl3` example doesn't have the core flag, the code does:

```
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
    //glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  // 3.2+ only
```

What happens then?

**Comment by sonoro1234** [comment]
No glError as with COMPAT profile explicitely setted.

**Comment by ocornut** [comment]
I don't understand what you are saying.

Do you get a glError() with the unmodified example_glfw_opengl3 example?

**Comment by sonoro1234** [comment]
No, sorry.
Unmodified example gives no error.
But 
```
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
    //glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  // 3.2+ only
```
gives error also

**Comment by ocornut** [comment]
So it's not an issue in Dear ImGui example and it is 100% a OpenGL problem, why posting here?

**Comment by sonoro1234** [comment]
Well, could be that some not CORE opengl is used by the opengl3 implementation and so it gives the error.

**Comment by ocornut** [comment]
I don't understand what you're saying, and I don't understand why it relates to imgui.

If any of the examples if causing an error, I am interested.
If imgui_impl_glfw.cpp can be failing or causing an error, I am interested.

In this case you are pointing to neither. Compatibility issues in user's application code are aff-topic.

**Comment by sonoro1234** [comment]
What causes the error is a slight modification of the example in which I set
```cpp
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  // 3.2+ only
```

**Comment by ocornut** [comment]
But you do realize that at this point dear imgui is 0% involved and your question is an OpenGL question?

**Comment by sonoro1234** [comment]
I still dont understand if you dont accept GL version modifications in the examples.
But could find where the first 1280 error is caused 
https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl3.cpp#L177

**Comment by ocornut** [comment]
I want imgui_impl_opengl3.cpp to work with any OpenGL 3/4 setup, but if you get an error before you call any of the ImGui_Impl_OpenGL functions it's not a problem for imgui_impl_opengl3.cpp it's a problem of your application.

Until now you mentioned user-side code and `glfwMakeContextCurrent()` giving out an error...

> But could find where the first 1280 error is caused

Now, this is the first time in this thread that you mention that imgui_impl_opengl3.cpp is affected.. we are getting somewhere.

1280 is 0x500 `GL_INVALID_ENUM`:
If you are 100% sure that there is no error before the call to `glGetIntegerv(GL_POLYGON_MODE...` and one after, then this becomes an issue we ought to fix.

According to https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPolygonMode.xhtml the **function** glPolygonMode() is supported by pretty much all version of GL, and it is implied that glGet GL_POLYGON_MODE is the same.

You'd maybe need to investigate further.

**Comment by ocornut** [comment]
The code to read polygon mode was added here (Sept 2017)
https://github.com/ocornut/imgui/pull/1307
And it is the first time someone mentions an error with it.

At least here (Windows 10), if I litter the code with many:
`{ GLenum err = glGetError(); IM_ASSERT(err == GL_NO_ERROR); }`

And change the context to 3.2 CORE it doesn't happen to me.
Because of how `glGetError()` works (error values are kept until the functionis called) you need to make sure it is glGetXXX(GL_POLYGON_MODE) that triggers the error and not anything else before.

**Comment by sonoro1234** [comment]
>Until now you mentioned user-side code and glfwMakeContextCurrent() giving out an error...
I didnt mean that but that I inserted some code after that in example
https://github.com/ocornut/imgui/blob/master/examples/example_glfw_opengl3/main.cpp#L181

>Now, this is the first time in this thread that you mention that imgui_impl_opengl3.cpp is affected.. we are getting somewhere.
If you search the issue you will get several references to opengl3 implementation

>If you are 100% sure that there is no error before the call to glGetIntegerv(GL_POLYGON_MODE... and one after, then this becomes an issue we ought to fix.

I did  glGetError in several places: no error before and an error before this line

>function glPolygonMode() is supported by pretty much all version of GL, and it is implied that glGet GL_POLYGON_MODE is the same.

 In https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGet.xhtml you will not find this constant

**Comment by ocornut** [comment]
Thanks, I understand better what you meant originally.

`GL_POLYGON_MODE` will be defined by the loader here so the value will always exist at compile time with the default loader, which doesn't mean that the underlying driver will like it.

It could be bug in the ATI driver at a given version that they mistakenly deprecated this? Are you on latest driver version? At the moment here with both Nvidia and Intel drivers I can't get a GL error with that setup (3.2 core).

**Comment by sonoro1234** [comment]
Only could found this https://community.amd.com/thread/169728
And I tried to get last driver other times for another problem without succes
:-(

**Comment by ocornut** [comment]
Nice find.. the bug report mentions two things so it is not clear what the exact status of GL_POLYGON_MODE is from their pov.

Could you use `glDebugMessageCallback()` and see exactly if they give you a more detailed message?

I am not sure what would be the best action there.. if we overzealously remove the GL_POLYGON_MODE getter then we essentially undo #1307. If we can find a proper reference as to how this was maybe deprecated we could probably use the GL strings to selectively not call the function?

I'll try to make a post on the AMD forum too!

**Comment by sonoro1234** [comment]
Unfortunately my GPU is 4.2 maximum so there is not glDebugMessageCallback()

Do you understand how GL_VERSION_1_0 and similar defines are used in glcorearb.h?
There should be the key. I only know that glcorearb.h is dedicated to CORE profiles.

**Comment by ocornut** [comment]
> Do you understand how GL_VERSION_1_0 and similar defines are used in glcorearb.h?
There should be the key. I only know that glcorearb.h is dedicated to CORE profiles.

This is checking if another of the standard header has already been included. This is suggesting that any OpenGL version from 1.1 has `GL_POLYGON_MODE` already, but the loader doesn't really bother with deprecations unfortunately.

**Comment by sonoro1234** [comment]
According to ://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPolygonMode.xhtml GL_POLYGON_MODE can be used for glGet.

So this is not an imgui issue but a Radeon driver issue (which they havent updated since 2016)

I just use glGetError after the imgui functions ended to clear the error flag as a temporary solution.

**Comment by ocornut** [comment]
Thank you. May be worth raising this on Radeon forums too!
