### ISSUE TITLE
Assertion failed when using for loop

### ISSUE THREAD

**Issue by teamclouday** [ocornut/imgui#2523]
I have a list of objects, and I want to use a for loop to create `InputFloat4` and `ColorEdit3` for each of them.  
But when I actually drag the color (with more than one object in the list), it shows `Assertion failed! Expression: g.ActiveId == id || g.ActiveId == 0 || g.DragDropActive`   
Also, when I have more than one objects in array, their values are all the same (They're controlling the same pointer address instead of seperate ones)  

My code:  
```cpp
for(unsigned i = 0; i < this->myLights.size(); i++)
{
glNamedBufferSubData(this->lightBuffer, i*(sizeof(SourceLight)), sizeof(SourceLight), myLights[i]);
ImGui::Spacing();
ImGui::Text("Light %u", i+1);
ImGui::Spacing();
ImGui::InputFloat4("Light Position", (float*)glm::value_ptr(myLights[i]->position));
ImGui::ColorEdit3("Light Color", (float*)glm::value_ptr(myLights[i]->color));
ImGui::DragFloat("Light Attenuation", &(myLights[i]->attenuation), 0.001f, 0.0f, 1.0f);
ImGui::DragFloat("Light Ambient Coefficient", &(myLights[i]->ambientCoeff), 0.001f, 0.0f, 1.0f);
ImGui::DragFloat("Light Cone Angle", &(myLights[i]->coneAngle), 0.1f, 0.0f, 80.0f);
}
```  

How can I fix it in the for loop?

**Comment by ocornut** [comment]
For the first problem:
- please fill in the required issue template info first.

For the second problem:
- please read the FAQ.

**Comment by teamclouday** [comment]
Problem fixed. After reading [`imgui_demo.cpp`](https://github.com/ocornut/imgui/blob/db2d58a68b923319695acfd10dadb6706a200d32/imgui_demo.cpp#L434), simply add PushID and PopID around each loop solves the issue
