### ISSUE TITLE
Active Titlebg color

### ISSUE THREAD

**Issue by emoon** [ocornut/imgui#253]
Something that would be nice would be to have a a color for the TitleBg when it's active (so it could be a bit brighter to indicate which window is active)

In my case I'm going to implement so it's possible to jump between windows using the keyboard and having an indication of which that is active would be nice.

**Comment by ocornut** [comment]
Done. I'm sure there's a few cases with how ImGui manage focus that don't match what Windows does. It may release window focus in some cases involving popups/menus. Looks like it works for the cases I have tested.

**Comment by emoon** [comment]
Alright. Thanks! If I found some cases that seems weird I will report :)

**Comment by ocornut** [comment]
Cool!
(By which I mean, making the active window "visible" now make those differences immediately visible if any, whereas they were invisible previously unless you used keyboard actions like tabbing)

**Comment by emoon** [comment]
Tested this now. Seems to work just as I want it. Cheers!
