### ISSUE TITLE
How to remove spacings?

### ISSUE THREAD

**Issue by SvRich** [ocornut/imgui#2532]
![57153619-70da4c80-6ddf-11e9-9e82-c693fb486a65](https://user-images.githubusercontent.com/30383573/57155095-d2e48300-6dda-11e9-8bd3-37495b02cfe1.png)

**Comment by SvRich** [comment]
It isn't cheat, it is client for russian social network VK.

**Comment by SvRich** [comment]
And how to remove button's border?

**Comment by nicolasnoble** [comment]
Then the problem isn't about cheating. The problem is about you not following the issue template.

**Comment by nicolasnoble** [comment]
See https://github.com/ocornut/imgui/issues/2514 as an example of a good issue.

**Comment by ocornut** [comment]
Your other profile is covered by #1586 and you haven’t followed the issue template.
