### ISSUE TITLE
how to get the pressed  keyboard button?

### ISSUE THREAD

**Issue by MohammadNsearaty** [ocornut/imgui#2533]
I am trying to use the keyboard input in my application ( I am using glut implementation )
but dear imgui is reading the input from the keyboard and the opengl window is not responding for the keyboard
so i am trying to know which keyboard button was pressed by the dear imgui to use it in  my application.

**Comment by nicolasnoble** [comment]
Read the FAQ, the examples, and the demo file - depending on what you actually want to do, this should tell you what you can do.

https://github.com/ocornut/imgui/blob/86f92fe75605021a7440d72131a6aa7e27ca13a9/examples/example_glut_opengl2/main.cpp#L85-L88
https://github.com/ocornut/imgui/blob/86f92fe75605021a7440d72131a6aa7e27ca13a9/imgui_demo.cpp#L330
https://github.com/ocornut/imgui/blob/86f92fe75605021a7440d72131a6aa7e27ca13a9/imgui_demo.cpp#L625

**Comment by ocornut** [comment]
Mohammad, don't call `ImGui_ImplGLUT_InstallFuncs()`, set your own glut func and call the `ImGui_ImplGLUT_xxx` ones from there. Please read imgui_impl_glut.h/cpp comments and code.

Your issue didn't fill the issue template. Future issues like this will be closed.

**Comment by UmutArdaBenli** [comment]
`ImGui::IsKeyPressed(ImGuiKey key,bool repeating)` is now possible.
