### ISSUE TITLE
Git merge left over

### ISSUE THREAD

**Issue by ibachar** [ocornut/imgui#2534]
imgui_impl_dx11.cpp in the current docking branch contains leftover git merging markers:

https://github.com/ocornut/imgui/blob/825b61e4bafea73d2b3a35a97d224bf9886b7ea0/examples/imgui_impl_dx11.cpp#L95

**Comment by ibachar** [comment]
PR: https://github.com/ocornut/imgui/pull/2535

**Comment by ocornut** [comment]
Merged, thank you!
(No need to create issues for PR especially simple ones)
