### ISSUE TITLE
Is possible to use ImGui on Windows form?

### ISSUE THREAD

**Issue by Suprachan** [ocornut/imgui#2536]
Well, I would like to know if it's possible to draw ImGui on Windows form, c#/c++

**Comment by ocornut** [comment]
Check https://github.com/mellinoe/ImGui.NET for C# bindings.
Dear ImGui uses GPU/3d rendering. If you can display a 3d rendering in your WinForms app you can use dear imgui.

**Comment by xAyman** [comment]
Exactly !
