### ISSUE TITLE
SetNextWindowSize on a dummy window causes it to un-hide.

### ISSUE THREAD

**Issue by Dingobloo** [ocornut/imgui#2540]
**Version/Branch of Dear ImGui:**

Version: 1.70 WIP
Branch: docking 

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl2.cpp + imgui_impl_sdl.cpp
Compiler: Clang & MSVC 
Operating System: OSX High Sierra & Windows 10 

**My Issue/Question:**

ImGui::SetNextWindowSize on a dummy window being used to access GetWindowDrawList causes it to no longer be hidden which is especially disruptive on the docking branch because it creates its own window that cannot be moved, docked or interacted with. SetNextWindowPos(ImVec2(0, 0)) also causes this behaviour on its own but the window is smaller. This may be a regression, as it functions as expected with an earlier version of the docking branch from last year (1.66 WIP) 

**Screenshots/Video**
Incorrect Output: 
![BlackBox](https://user-images.githubusercontent.com/4349811/57276437-fc582400-70e4-11e9-98d3-9e5c8cccb13e.png)
Expected Output: 
![NoBlackBox](https://user-images.githubusercontent.com/4349811/57276447-037f3200-70e5-11e9-9a62-9d53d688cbc7.png)

**Standalone, minimal, complete and verifiable example:** 
```
ImGuiIO& io = ImGui::GetIO();
		
const ImU32 flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoInputs | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoFocusOnAppearing | ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoBackground;
		
ImGui::SetNextWindowSize(io.DisplaySize);
ImGui::SetNextWindowPos(ImVec2(0, 0));
		
ImGui::Begin("gizmo", NULL, flags);
	ImDrawList* mDrawList = ImGui::GetWindowDrawList();
ImGui::End();
```

**Comment by ocornut** [comment]
Hello,

At first glance it looks like it _was_ a bug and it is now fixed. I am not sure I understand why you would expect the window to not be visible _if_ you have enabled multi-viewports and then you position it on a location _outside_ your main viewport?

You may want to use GetBackgroundDrawList(GetMainViewport()) instead?

**Comment by ocornut** [comment]
(Posting from email seems to have messed up carriage returns for me, sorry)

To clarify, this code is only problematic with multi-viewports enabled. 

Another solution is to position the window at io.DisplayPos instead of (0,0).

**Comment by Dingobloo** [comment]
Yeah seems it was just a casualty of the semantic change to setPos that wasn't apparent until the bugfix, and I can see why it wouldn't be desirable (or in some cases possible) to have no-background supported viewport windows outside the bounds of the main viewport. 

Will close this and work with the maintainer of the widget to avoid the behaviour when using the viewport branch.

**Comment by ocornut** [comment]
I am looking into adding some sort of helper variable or function to bridge the gap between master and viewport-enabled-branch and make it easier to share code function on both. 

In the meanwhile the code is meant to check for #ifdef IMGUI_HAS_VIEWPORTS
