### ISSUE TITLE
Add support for monochrome font rendering with freetype

### ISSUE THREAD

**Issue by HolyBlackCat** [ocornut/imgui#2543]
In addition to antialiased rendering, freetype supports monochrome rendering. But at the moment this setting is not exposed in `imgui_freetype.h/.cpp`.

It would be great to have a flag in `ImGuiFreeType::RasterizerFlags` for that.

Monochrome rendering can be enabled simply by passing `FT_RENDER_MODE_MONO` instead of `FT_RENDER_MODE_NORMAL` to `FT_Render_Glyph`.
I think it causes freetype to output 1-bit-per-pixel bitmaps (`ft_bitmap->pixel_mode == FT_PIXEL_MODE_MONO`), so we'd also have to change `FreeTypeFont::BlitGlyph` to decode those bitmaps.

**Comment by ocornut** [comment]
Excellent, that would be great! 
I think you've identified what there is to do in the first post, mostly a matter of making `BlitGlyph` handle it nicely.

**Comment by HolyBlackCat** [comment]
Made a PR: https://github.com/ocornut/imgui/pull/2545

**Comment by ocornut** [comment]
Merged, thank you!
I gave a test, on some fonts (wth `MonoHinting` activated) the results are really pleasant. I'd recommend it to people who like the sorts of font imgui uses by default.

![image](https://user-images.githubusercontent.com/8225057/57567525-d1b6e580-73da-11e9-87f0-dc477cbe58ec.png)
