### ISSUE TITLE
ColorEdit

### ISSUE THREAD

**Issue by KeynS** [ocornut/imgui#2549]
Hey. Question about ColorEdit.
I wanted to clarify how to remove the stroke strip. At the moment I have this:
![image](https://user-images.githubusercontent.com/25707446/57568439-2e70cb00-73f0-11e9-8814-a6f9fa694296.png)
I wish it were like this:
![image](https://user-images.githubusercontent.com/25707446/57568433-1c8f2800-73f0-11e9-9536-d3e09c4aaa6b.png)

Perhaps the problem is the old imgui version. But I would not want to change the version

**Comment by ocornut** [comment]
Not filled issue template, closing.
