### ISSUE TITLE
`IMGUI_IMPL_API` Error: this declaration has no storage class or type specifier		

### ISSUE THREAD

**Issue by fedqx** [ocornut/imgui#2552]
Hi, I'm trying to set up imgui in my game engine but i got an error. on file `imgui_impl_opengl3.h ` and `imgui_impl_glfw.h`,  I got error `IMGUI_IMPL_API` Error: this declaration has no storage class or type specifier. I added and tried compile all the files that listed in [Here](https://github.com/ocornut/imgui/edit/master/docs/README.md#L26-L35) in lines 26 to 35 plus those GLFW and OpenGL files in the example.
and i got that error. I can provide info about project on demand.
Thank you.

**Comment by ocornut** [comment]
Not read or filled issue template, closing.
