### ISSUE TITLE
ListBox Active Color

### ISSUE THREAD

**Issue by NMan1** [ocornut/imgui#2553]
What is the style to change the color of a the list box's active/hovered item?
EX: https://gyazo.com/35643b60dc5a369f7cb47b566df65f16 
How would I change the white color? I've tried ImGuiCol_FrameBgActive which didn't work.

Thank you.

**Comment by nicolasnoble** [comment]
You haven't read nor filed the issue template.

Also, github has an embedded image hosting system. There is no need for you to host them on advertisement-laden websites.

**Comment by ocornut** [comment]
Sorry but #1586
