### ISSUE TITLE
unresolved external symbol

### ISSUE THREAD

**Issue by HighPolyLuna** [ocornut/imgui#2555]
Hey everyone, getting some pesky errors literally out of nowhere.
`1>imgui_demo.obj : error LNK2001: unresolved external symbol "float __cdecl ImGui::GetContentRegionAvailWidth(void)" (?GetContentRegionAvailWidth@ImGui@@YAMXZ)
1>imgui_impl_win32.obj : error LNK2001: unresolved external symbol "public: void __thiscall ImGuiIO::AddInputCharacter(unsigned short)" (?AddInputCharacter@ImGuiIO@@QAEXG@Z)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "struct ImVec2 __cdecl ImGui::GetContentRegionMaxScreen(void)" (?GetContentRegionMaxScreen@ImGui@@YA?AUImVec2@@XZ)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::FocusPreviousWindowIgnoringOne(struct ImGuiWindow *)" (?FocusPreviousWindowIgnoringOne@ImGui@@YAXPAUImGuiWindow@@@Z)
1>C:\Users\Censored\Downloads\censored.dll : fatal error LNK1120: 4 unresolved externals`
Any ideas? Thank you!

**Comment by nicolasnoble** [comment]
https://github.com/ocornut/imgui/issues/1586

**Comment by HighPolyLuna** [comment]
> #1586

Why did you link this?

**Comment by HighPolyLuna** [comment]
This is for Counter Strike: Global Offensive, but this is not meant for online use. This is an offline misc feature enhancer. I don't encourage cheating in online multiplayer games.

**Comment by HighPolyLuna** [comment]
Fixed it.

**Comment by xAkex0001** [comment]
How`?
