### ISSUE TITLE
drag input via keyboard has no effect

### ISSUE THREAD

**Issue by krumelmonster** [ocornut/imgui#2557]
**Version/Branch of Dear ImGui:**

Version: 1.71 git (fc3c3de551cbc5c13443f6e25977078006275713)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp; imgui_impl_glfw.cpp; GLEW
Compiler: gcc 8.3.0
Operating System: GNU/Linux

**My Issue/Question:**

Double clicking an input in a ColorEdit without ImGuiColorEditFlags_NoInputs (e.g. the either R, G or B integer in the demo but this seems to be an issue with drags in general) opens up a temporary input where I can enter a new value. However it does not seem to be possible to set the respective color component to that new value e.g. by pressing enter. Because `TempInputTextScalar` will *always* return false, causing value_changed in ColorEdit4 to not be set in such cases.

**Screenshots/Video**

![2019-05-15-222741_217x28_scrot](https://user-images.githubusercontent.com/13542760/57807116-ccea8c80-7760-11e9-82c2-ff021055c4e7.png)
double clicking either of the values will let me type a new value, however, changes are lost on focus change/enter press, the color won't change.

```
// From the example
ImGui::ColorEdit3("clear color", (float*)&clear_color);
```

**Comment by krumelmonster** [comment]
e6d5f230e5cd48b831b9d14b4b70e3c4e2d24aab allows submitting a value only via the enter key not by other ways of changing focus (tab key) without cancelling input (escape key). Furthermore, no bounds checking is performed. If the pr is approved, I'd like to change these as well if we agree on what'd be expected behaviour.

**Comment by ocornut** [comment]
Thank you @krumelmonster for reporting this. This appear to have been broken by d3a387c for #2034 a few days ago. I'll look into fixing now.

**Comment by ocornut** [comment]
Should be fixed now. 

> Because TempInputTextScalar will always return false

That was the bug added a few days ago.
Added regression tests for this.
