### ISSUE TITLE
Circular sliders / Knobs

### ISSUE THREAD

**Issue by AlexFundorin** [ocornut/imgui#2559]
Is it possible to create circular type sliders with imgui? I mean, like a knob or an encoder. Both endless and range types.

**Comment by Alzathar** [comment]
It seems you did not do any research in the issues.
https://github.com/ocornut/imgui/search?q=knob&type=Issues

Flix01 added an KnobFloat function in his repository : 
https://github.com/Flix01/imgui/blob/imgui_with_addons/addons/imguivariouscontrols/imguivariouscontrols.h#L901

**Comment by ocornut** [comment]
Closing as no reaction, hopefully #942 will be useful, don't hesitate to post there if anything comes to mind!

**Comment by hippyau** [comment]
![image](https://user-images.githubusercontent.com/36442309/148376967-c19286ee-f4b4-4acd-8df9-8d244c472ef5.png)

In rust.

https://github.com/DGriffin91/imgui-rs-knobs
