### ISSUE TITLE
Collapsing header doesn't push ID !

### ISSUE THREAD

**Issue by ebriney** [ocornut/imgui#256]
Hi Omar,
I did some some few tests with the latest version of imgui.

I fix almost every annoying ID issues with the new void* handle hashing which is great to desambiguate most situations relative to trees.

In some of my UIs i use Collapsing headers and must manually add Push/Pop ID if i have shared elements under collapsing. And there is no overload with the void* ID.

Thanks for your great job as usual.

**Comment by ocornut** [comment]
Yes that's because there's no "pop" for the collapsing header so it doesn't modify the state. Unfortunately I don't think it can / should be changed at this point.

**Comment by ebriney** [comment]
Ok, thanks, I understand, you have no way to figure out the pop with current interface.

Concerning hash function, I can share you the implementation I used after trying a lot of things.

For string hashing, I used the one found in Emil Persson (Head of Research at Avalanche Studios) framework : http://www.humus.name/index.php?page=Comments&ID=296&start=0
very efficient, i never got any problem with it.

I replace the hash function with a more optimized one because on some processor multiply can have a latency of few cycles stalling the CPU :

inline uint64_t HashMe64(uint64_t h, uint64_t c)
{
    return ((h << 5) + h) + c; //h*33+c (djb2 hash function)
}

inline uint32_t HashMe32(uint32_t h, uint32_t c)
{
    return ((h << 5) + h) + c; //h*33+c (djb2 hash function)
}

inline size_t HashMePtr(size_t h, size_t c)
{
    return ((h << 5) + h) + c; //h*33+c (djb2 hash function)
}

**Comment by ocornut** [comment]
Did you have performance problems with CRC32?
Will look into replacing CRC32 but last time I tried to setup a test the total cost of all CRC32 was barely measurable.

From reading your message it is suggesting that you are hashing things yourself to form a void* ? What does your code looks like?
void* is really for passing a pointer to be hashed. If you really to build a stack to create hashes you can use PushID()/PopID().

(My intuition is that replacing *33 by *32 would pretty much defeat a lot of the hashing properties)

Was considering FNV1a which is what a few knowledgeable people recommended to me:
http://www.isthe.com/chongo/tech/comp/fnv/

**Comment by ocornut** [comment]
Closing this as the hashing discussion doesn't seem to relate to the stated issue (but we can continue discussing it).

**Comment by ebriney** [comment]
I had no performance issues with CRC32 and no collision with a lot of nodes (~1000) so it's fine to keep it (3d buffers generation should take a lot more time :) ).

I didn't understand what do you mean with void*.
In imgui I use the new prototype you add with void* as ID and use the address of my objects in treeviews.

FNV1a hash function looks pretty good too (very similar than djb2).
dbj2 variant use xor instead of add too but that does the same, everything is in the 33 constant,
sdbm use 65599 instead for similar results.
