### ISSUE TITLE
Secondary viewports not rendering if nothing has been drawn in main one

### ISSUE THREAD

**Issue by dumbasPL** [ocornut/imgui#2560]
**Version/Branch of Dear ImGui:**

Version: 1.71
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: Visual Studio 2019
Operating System: Windows 10 (1903)

**My Issue/Question:**

Secondary viewports not rendering if nothing has been drawn in main one.
Dear imgui remembers the location of windows and if all windows are dragged out of viewport 0 and the program gets closed or io.ConfigViewportsNoAutoMerge flag is set then the next time the program starts all secondary viewports witch will be created will not be rendered until something gets rendered in the main one.

**Screenshots/Video**

![imgui](https://user-images.githubusercontent.com/29180158/57866805-3a012f00-7800-11e9-9983-bd5eb9d130c3.gif)

**Standalone, minimal, complete and verifiable example:**
clone and build the docking branch

**Comment by ocornut** [comment]
I can confirm this is happening with the DX9 renderer. I don't think it is happening with other renderers.

I have debugged it for 15 minutes and tried different hypothesis, the only conclusion I can find is that there's some weird/legacy driver logic that awaits for a draw call in the first window. So the workaround I found is to submit a dummy zero-polygon draw call.

This should be fixed now!
