### ISSUE TITLE
Undocking issue with InputInt

### ISSUE THREAD

**Issue by zzzyap** [ocornut/imgui#2562]
Version: v1.70 WIP
Branch: docking

Window is unable to undock with InputInt.
Able to undock when collapsing header is closed (IE InputInt is not called).
Example code:
```
if (ImGui::Begin("Testing"))
{
    if (ImGui::CollapsingHeader("Test"))
    {
        int someInt = 1;
        if(ImGui::InputInt("", &someInt))
        {
            someInt = max(1, someInt); // do something
        }
    }
}
ImGui::End();
```
![20190517_263](https://user-images.githubusercontent.com/13419807/57945631-5eb0e180-78a8-11e9-8739-500de6892c7b.gif)

Related if InputInt has a label `ImGui::InputInt("What?", &someInt)` it is able to undock.

![20190517_265](https://user-images.githubusercontent.com/13419807/57945685-7f793700-78a8-11e9-9269-49f80a4fd1bb.gif)

EDIT: edited as it looks to be an issue with input int and not collapsing header.

EDIT 2: occurs with `InputText` and `InputFloat` too.

**Comment by ocornut** [comment]
You simply have an ID collision, which is a common week 1 source of error, surprising to hear it from you :)

If you are not sure what I am referring to read the FAQ about the ID Stack.

**Comment by zzzyap** [comment]
Ah yes, id of "" (0) is going to collide. mb Thanks.
Closing. 
Just noting incase someone comes across this thread "##UniqueIdentifer" etc... can be used for label.
