### ISSUE TITLE
Crash with DockSpace when using PassthruCentralNode

### ISSUE THREAD

**Issue by TomSmeets** [ocornut/imgui#2563]
Version: 1.71
Branch: docking (7e772f6a51d0db5d00d9e9b4649cbe4cb0da79b9)

Add `ImGuiDockNodeFlags_PassthruCentralNode` to ShowExampleAppDockSpace in `imgui_demo.cpp`:
```diff
--- a/imgui_demo.cpp
+++ b/imgui_demo.cpp
@@ -4326,6 +4326,7 @@ void ShowExampleAppDockSpace(bool* p_open)
     static bool opt_fullscreen_persistant = true;
     bool opt_fullscreen = opt_fullscreen_persistant;
     static ImGuiDockNodeFlags dockspace_flags = ImGuiDockNodeFlags_None;
+    dockspace_flags |= ImGuiDockNodeFlags_PassthruCentralNode;
 
     // We are using the ImGuiWindowFlags_NoDocking flag to make the parent window not dockable into,
     // because it would be confusing to have two docking targets within each others.
```

### Run the demo app
* Run `example_sdl_opengl3`
* Enable DockSpace: `Examples->Dockspace`
* Dock the `Hello, world!` window on the bottom
* Dock the `ImGui Demo` window on the right
* Undock the `ImGui Demo` window

#### Result
```
example_sdl_opengl3: ../../imgui.cpp:12193: void ImGui::DockNodeUpdate(ImGuiDockNode*): Assertion `node->IsDockSpace()' failed.
```

**Comment by ocornut** [comment]
Thank you @TomSmeets for spotting this assert.
Should be fixed now.
