### ISSUE TITLE
Checking if an item is visible

### ISSUE THREAD

**Issue by ChriisH** [ocornut/imgui#2566]
Hello, I'm actually working on animation stuff and I would like to fade in the new items like Button, Text.. when using the Vertical slider and seeing the new visible items.

I'm actually increasing the alpha channel of the ImGuiCol_Text to make it looks like it's appearing but I can't check if the item is now visible or not, do you have any idea how I could achieve that please?

**Comment by ocornut** [comment]
It depends what your definition of "visible" is. 

You can call `IsItemVisible()` after an item to test if its bounding box was within the current clipping rectangle.

If your definition of "visible" relates to Alpha, you are in control of the style/alpha therefore you can test those values.

You can also call one of the two `IsRectVisible()` function to test a bounding box ahead of time, supposing you know where your item will land.

**Comment by ChriisH** [comment]
> It depends what your definition of "visible" is.
> 
> You can call `IsItemVisible()` after an item to test if its bounding box was within the current clipping rectangle.
> 
> If your definition of "visible" relates to Alpha, you are in control of the style/alpha therefore you can test those values.
> 
> You can also call one of the two `IsRectVisible()` function to test a bounding box ahead of time, supposing you know where your item will land.

It works perfectly fine, thank you very much!
