### ISSUE TITLE
Multiple calls ImGui::BeginMainMenu crashed

### ISSUE THREAD

**Issue by Ghost-yc** [ocornut/imgui#2567]
**Version/Branch of Dear ImGui:**

Version: 1.7
Branch: master

**Back-end/Renderer/Compiler/OS:**

Compiler: Visual Studio 2017
Operating System: Windows 10

**My Issue/Question:**

when there is no windows display multiple invoked ImGui::BeginMainMenu is crashed  in imgui.cpp line 2831

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/8528210/58064418-94114400-7bb4-11e9-8461-b0b9161893f3.png)

here's the modifyed file:
[code.zip](https://github.com/ocornut/imgui/files/3200506/code.zip)

**Comment by ocornut** [comment]
Should be fixed, thank you.
I also added comments in `ItemAdd()` about why we _don't_ check that NavWindow is not NULL (this is a critical path function so we avoid extraneous checks there).
