### ISSUE TITLE
How could mouse wheel scrolling be smooth

### ISSUE THREAD

**Issue by ChriisH** [ocornut/imgui#2569]
Hello again, I'm trying to make my GUI looks smooth, is there a way to make `UpdateMouseWheel()` smooth instead of scrolling directly?

Cordially,
Chris H

**Comment by ocornut** [comment]
It's not possible at the moment without some work on the code (which is not a high priority for at the moment).
Also see #2462

**Comment by ocornut** [comment]
Closing this as answer. Added task in TODO.txt (not urgent and/or waiting for a well designed PR).
