### ISSUE TITLE
Small bug in Long text display 

### ISSUE THREAD

**Issue by emoon** [ocornut/imgui#257]
Hi,

There is a small bug in the example. It looks like this when started: 

![screen shot 2015-07-02 at 08 40 21](https://cloud.githubusercontent.com/assets/350822/8471214/470da3ba-2096-11e5-8d76-512b03861119.png)

Then if you stroll down with the scrollbar just a very few pixels (one can barley see it moving) you get a display that looks like this

![screen shot 2015-07-02 at 08 40 13](https://cloud.githubusercontent.com/assets/350822/8471224/736befc0-2096-11e5-96d7-6ea6a3b48385.png)

Not sure if this is a known issue or not.

**Comment by ocornut** [comment]
Thanks. Not sure how this one slipped away (been there for a while). TextUnformatted() uses a system similar to ImGuiListClipper that look for carriage returns in the text to clip text.
