### ISSUE TITLE
Opengl ES 2.0 example

### ISSUE THREAD

**Issue by bruenor41** [ocornut/imgui#2571]
Hello,

please has someone patch for OpenGL ES 2.0? I like to use this great app on Android, but I need ES version 2, no 3.

Many thanks

**Comment by ocornut** [comment]
imgui_impl_opengl3 already supports ES 2.

**Comment by bruenor41** [comment]
Cool many thanks :)

**Comment by Ammar64** [comment]
Does it support GLES 3 I get no window with GLES 3.2 on android

**Comment by PathogenDavid** [comment]
@Ammar64 The [official Android example](https://github.com/ocornut/imgui/tree/313676d200f093e2694b5cfca574f72a2b116c85/examples/example_android_opengl3) uses OpenGL ES 3.
