### ISSUE TITLE
Viewports: Keep one Viewport Window on top of others

### ISSUE THREAD

**Issue by eclbtownsend** [ocornut/imgui#2574]
```
Dear ImGui 1.70 WIP (16991)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: _WIN32
define: _WIN64
define: _MSC_VER=1913
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.BackendFlags: 0x00001402
 HasMouseCursors
 PlatformHasViewports
 RendererHasViewports
--------------------------------
```
**My Issue/Question:**

I'm looking to accomplish a similar behavior to https://github.com/ocornut/imgui/issues/717 but for Viewports.  When all windows are inside the same viewport, 'NoBringToFrontOnFocus' can be used to keep another window from covering your desired 'on top' window but if both are in their own viewports this does not work.

I hope the gif illustrates the sort of behavior I'm looking for.  I understand this could be a very complicated task given the backend platform work with viewports so I'm mostly looking for guidance on a potential workaround. 

Thank you!

**Screenshots/Video**

![viewports](https://user-images.githubusercontent.com/35241930/58190342-2a0aa480-7c71-11e9-9333-f03d44c8a653.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
   if (ImGui::Begin("Interaction Window", nullptr, ImGuiWindowFlags_NoBringToFrontOnFocus)) {
      ImGui::Text("Click here to do stuff");
   }
   ImGui::End();

   if (ImGui::Begin("Interaction Options Window")) {
      ImGui::TextWrapped("Here be options for modifying how Im interacting with Interaction Window");
   }
   ImGui::End();
```

**Comment by ocornut** [comment]
As a workaround you may set `ImGuiViewportFlags_TopMost` on the viewport via `SetNextWindowClass()` call. There's also a `ImGuiViewportFlags_NoFocusOnClick` but it is not honored by the SDL back-end (it may be possible to honor maybe in a non-portable way).

I think we ought to add a more general `ImGuiWindowFlags_TopMost` which may be simpler to implement now that the focus vs depth order are in separate arrays.

**Comment by eclbtownsend** [comment]
Thank you! I was trying to figure how to use the TopMost viewport flag but never saw the windowClass portion, this fixes my issue.

I certainly prefer the concept of 'set this as topmost' as opposed to trying to set others as not coming forward
