### ISSUE TITLE
Merge atlas image of icons into font

### ISSUE THREAD

**Issue by SuperWangKai** [ocornut/imgui#2575]
Is there any way to build font from an atlas texture of icons/text or merge this texture into current font?

This will be useful if we already have an icon atlas texture and want to apply them into text rendering just as how we handle with icon font files.

Thanks!

**Comment by ocornut** [comment]
Not officially supported but you may look at #2127

**Comment by SuperWangKai** [comment]
> Not officially supported but you may look at https://github.com/ocornut/imgui/issues/2127

This approach works. I think we can close the issue.
