### ISSUE TITLE
Adding an icon to MenuItem (Selectable) [Help]

### ISSUE THREAD

**Issue by kotokun2** [ocornut/imgui#2582]
Hi,

First id like to state that this is more of a question and not an issue.
I am new to Dear ImGui and id like to know if there is any sort of forum or reddit page dedicated to ImGui devs so i can post questions there instead of flooding the issue page.
I am using the latest build of the docking tree and am looking to modify the **MenuItem** (more exactly the **Selectable**) so it has a icon next to it. 
And i've succeeded in doing just that by adding a **SameLine** and **Image** randomly in a copy of the **Selectable** widget
Code:
 bool Selectable(const char* label, bool selected, ImGuiSelectableFlags flags, const ImVec2& size_arg, GLint icon)
    {
        ImGuiWindow* window = GetCurrentWindow();
        if (window->SkipItems)
            return false;

        ImGuiContext& g = *GImGui;
        const ImGuiStyle& style = g.Style;

        if ((flags & ImGuiSelectableFlags_SpanAllColumns) && window->DC.CurrentColumns) // FIXME-OPT: Avoid if vertically clipped.
            PushColumnsBackground();

        ImGuiID id = window->GetID(label);
        ImVec2 label_size = CalcTextSize(label, NULL, true);
        ImVec2 size(size_arg.x != 0.0f ? size_arg.x : label_size.x, size_arg.y != 0.0f ? size_arg.y : label_size.y);
        ImVec2 pos = window->DC.CursorPos;
        pos.y += window->DC.CurrLineTextBaseOffset;
        ImRect bb_inner(pos, ImVec2(pos.x+label_size.x, pos.y + label_size.y-5));
        ItemSize(size);

        // Fill horizontal space.
        ImVec2 window_padding = window->WindowPadding;
        float max_x = (flags & ImGuiSelectableFlags_SpanAllColumns) ? GetWindowContentRegionMax().x : GetContentRegionMax().x;
        float w_draw = ImMax(label_size.x, window->Pos.x + max_x - window_padding.x - pos.x);
        ImVec2 size_draw((size_arg.x != 0 && !(flags & ImGuiSelectableFlags_DrawFillAvailWidth)) ? size_arg.x : w_draw, size_arg.y != 0.0f ? size_arg.y : size.y);
        ImRect bb(pos, ImVec2(pos.x +size_draw.x, pos.y + size_draw.y));//pos + size_draw);
        if (size_arg.x == 0.0f || (flags & ImGuiSelectableFlags_DrawFillAvailWidth))
            bb.Max.x += window_padding.x;

        // Selectables are tightly packed together so we extend the box to cover spacing between selectable.
        const float spacing_x = style.ItemSpacing.x;
        const float spacing_y = style.ItemSpacing.y;
        const float spacing_L = (float)(int)(spacing_x * 0.50f);
        const float spacing_U = (float)(int)(spacing_y * 0.50f);
        bb.Min.x -= spacing_L;
        bb.Min.y -= spacing_U;
        bb.Max.x += (spacing_x - spacing_L);
        bb.Max.y += (spacing_y - spacing_U);
       
       
        bool item_add;
        if (flags & ImGuiSelectableFlags_Disabled)
        {
            ImGuiItemFlags backup_item_flags = window->DC.ItemFlags;
            window->DC.ItemFlags |= ImGuiItemFlags_Disabled | ImGuiItemFlags_NoNavDefaultFocus;
            item_add = ItemAdd(bb, id);
            window->DC.ItemFlags = backup_item_flags;
        }
        else
        {
            item_add = ItemAdd(bb, id);
        }
        if (!item_add)
        {
            if ((flags & ImGuiSelectableFlags_SpanAllColumns) && window->DC.CurrentColumns)
                PopColumnsBackground();
            return false;
        }

        // We use NoHoldingActiveID on menus so user can click and _hold_ on a menu then drag to browse child entries
        ImGuiButtonFlags button_flags = 0;
        if (flags & ImGuiSelectableFlags_NoHoldingActiveID) button_flags |= ImGuiButtonFlags_NoHoldingActiveID;
        if (flags & ImGuiSelectableFlags_PressedOnClick) button_flags |= ImGuiButtonFlags_PressedOnClick;
        if (flags & ImGuiSelectableFlags_PressedOnRelease) button_flags |= ImGuiButtonFlags_PressedOnRelease;
        if (flags & ImGuiSelectableFlags_Disabled) button_flags |= ImGuiButtonFlags_Disabled;
        if (flags & ImGuiSelectableFlags_AllowDoubleClick) button_flags |= ImGuiButtonFlags_PressedOnClickRelease | ImGuiButtonFlags_PressedOnDoubleClick;
        if (flags & ImGuiSelectableFlags_AllowItemOverlap) button_flags |= ImGuiButtonFlags_AllowItemOverlap;

        if (flags & ImGuiSelectableFlags_Disabled)
            selected = false;
        SameLine();
        Image((void*)icon, ImVec2(16, 16));
        const bool was_selected = selected;
        bool hovered, held;
        bool pressed = ButtonBehavior(bb, id, &hovered, &held, button_flags);
        // Hovering selectable with mouse updates NavId accordingly so navigation can be resumed with gamepad/keyboard (this doesn't happen on most widgets)
        if (pressed || hovered)

           
            if (!g.NavDisableMouseHover && g.NavWindow == window && g.NavLayer == window->DC.NavLayerCurrent)
            {
              
                g.NavDisableHighlight = true;
                SetNavID(id, window->DC.NavLayerCurrent);
            }
        if (pressed)
            MarkItemEdited(id);

        if (flags & ImGuiSelectableFlags_AllowItemOverlap)
         
            SetItemAllowOverlap();
       
        // In this branch, Selectable() cannot toggle the selection so this will never trigger.
        if (selected != was_selected) //-V547
            window->DC.LastItemStatusFlags |= ImGuiItemStatusFlags_ToggledSelection;
      
        // Render
        if (hovered || selected)
        {
           
            const ImU32 col = GetColorU32((held && hovered) ? ImGuiCol_HeaderActive : hovered ? ImGuiCol_HeaderHovered : ImGuiCol_Header);
            RenderFrame(bb.Min, bb.Max, col, false, 0.0f);
            RenderNavHighlight(bb, id, ImGuiNavHighlightFlags_TypeThin | ImGuiNavHighlightFlags_NoRounding);
        }

        if ((flags & ImGuiSelectableFlags_SpanAllColumns) && window->DC.CurrentColumns)
        {
            PopColumnsBackground();
            bb.Max.x -= (GetContentRegionMax().x - max_x);
        }
        
        if (flags & ImGuiSelectableFlags_Disabled) PushStyleColor(ImGuiCol_Text, style.Colors[ImGuiCol_TextDisabled]);
        RenderTextClipped(bb_inner.Min, bb_inner.Max, label, NULL, &label_size, style.SelectableTextAlign, &bb);
        if (flags & ImGuiSelectableFlags_Disabled) PopStyleColor();

        // Automatically close popups
        if (pressed && (window->Flags & ImGuiWindowFlags_Popup) && !(flags & ImGuiSelectableFlags_DontClosePopups) && !(window->DC.ItemFlags & ImGuiItemFlags_SelectableDontClosePopup))
            CloseCurrentPopup();
        
        IMGUI_TEST_ENGINE_ITEM_INFO(id, label, window->DC.ItemFlags);
       
        return pressed;
    }

This is the result:
![{79027708-DC78-41E8-89B8-2D32846477AA} png](https://user-images.githubusercontent.com/27425312/58373203-b693bc00-7f2a-11e9-958a-574e66a645a4.jpg)

But i have a problem, on mouse over the icon disappears.
Can someone tell me how to properly do this?

Thank you, 

PS: I know the imgui_demo.cpp has a lot of examples enough to get anyone started but it would be great to have a forum/reddit/anything(Discord maybe?) where devs can help each other and leave the issues page reserved for bugs and upcoming features.

**Comment by kotokun2** [comment]
Fixed it 


```
 if (hovered || selected)
        {
           
            const ImU32 col = GetColorU32((held && hovered) ? ImGuiCol_HeaderActive : hovered ? ImGuiCol_HeaderHovered : ImGuiCol_Header);
            RenderFrame(bb.Min, bb.Max, col, false, 0.0f);
            RenderNavHighlight(bb, id, ImGuiNavHighlightFlags_TypeThin | ImGuiNavHighlightFlags_NoRounding);
            SameLine();
            Image((void*)icon, ImVec2(16, 16));
        }
        else {

            SameLine();
            Image((void*)icon, ImVec2(16, 16));
        }

```

**Comment by ocornut** [comment]
Look into merging an icon font, it is generally a much easier and flexible way to incorporate icons in a dear imgui app.

**Comment by kotokun2** [comment]
Thanks I'll look into it.

**Comment by noisewuwei** [comment]
> Look into merging an icon font (read `misc/fonts/README.txt`), it is generally a much easier and flexible way to incorporate icons in a dear imgui app.

 But,how to load a color logo?
