### ISSUE TITLE
ColorEdit4 Popup Displaying and inputing HSV instead of RGB

### ISSUE THREAD

**Issue by DerGaijin** [ocornut/imgui#2587]
Version: 1.71 WIP
Branch: master
Back-ends: imgui_impl_Glfw.cpp + imgui_impl_Vulkan.cpp
Operating System: Windows 10

The Colorpicker Popup is displaying and inputing HSV instead of RGB
or did i miss some flags for that ?

```
ImGui::Begin("Example Bug");
glm::vec4 TempColor(1.0f);
ImGui::ColorEdit4("##IMAGECOLORPICK", &TempColor.r, ImGuiColorEditFlags_DisplayRGB | ImGuiColorEditFlags_InputRGB);
ImGui::End();
```
That also happens in the Demo window with the coloredits

**Comment by ocornut** [comment]
This is a bug that has been introduced by 79bb4ce1 (#2383, #2384), will look into fixing.

**Comment by ocornut** [comment]
Pushed fix now, thanks for finding and reporting this!
