### ISSUE TITLE
Inconsistent behavior UV between ImGui::Image and ImDrawList::PrimRectUV

### ISSUE THREAD

**Issue by PointlessReboot** [ocornut/imgui#2588]
**Version/Branch of Dear ImGui:**

Version: 1.69
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: custom
Compiler: vc++ 2017
Operating System: windows

**My Issue/Question:**

When we render images they appear upside down, so I looked into the drawing functions and was a little confused.

While ImGui::Image specifies the UV coords as being uv0={0,0} and uv1={1,1}, it seems the low level draw list code ImDrawList::PrimRectUV inverts the uv.v coord, so we get uv1={0,1} and uv1={1,0}.

Now I understand I can just pass in flipped uv's but I am wondering why it was done this way, is this some hang over from OpenGL?

Cheers
Graeme

**Comment by ocornut** [comment]
AFAIK none of the code in dear imgui inverts any UV.v coord, not sure where you got that from.

**Comment by PointlessReboot** [comment]
Sorry, it's our engine.. I was unable to get a true image from our asset store.. So I ran a RenderDoc capture, and it us..

Sorry for the trouble

**Comment by PointlessReboot** [comment]
No issues in ImGui
