### ISSUE TITLE
Drawlist steals cursor in overlay

### ISSUE THREAD

**Issue by wholivesinapineappleunderthesea** [ocornut/imgui#2596]
Version: 1.70
Branch: master
Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp 
Compiler: Visual Studio
Operating System: Windows 10

I have been rendering lines and shapes over my game, I create an overlay with CreateWindow and it has been working great with ImGui.
My issue is, that I've been using the drawlist of a blank invisible window to draw, and it steals the cursor from my game:
![overlayissue](https://user-images.githubusercontent.com/34866740/58674160-867a5d80-831c-11e9-917e-9ba9e3ee1de9.png)
(usually the cursor is invisible and is controlled by the game, however, the drawlist steals it)

This is how I create the window:
```
HWND hwnd = CreateWindowEx(WS_EX_TOPMOST | WS_EX_LAYERED, OVERLAY_WINDOW_NAME, OVERLAY_WINDOW_NAME, WS_POPUP, tSz.left, tSz.top, Width, Height, 0, 0, 0, 0);
```
(Width and Height are the window size of the game being overlayed, tSz is the positioning)

And this is how I get the drawlist:

```
ImGui::SetNextWindowPos(ImVec2(0, 0));
ImGui::SetNextWindowSize(ImVec2(Width, Height));
ImGui::SetNextWindowBgAlpha(0.0f);
ImGui::Begin("", NULL, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoInputs | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoFocusOnAppearing | ImGuiWindowFlags_NoBringToFrontOnFocus);
OverlayDrawList = ImGui::GetWindowDrawList(); // You don't need the imgui context, so just use this DrawList anywhere
ImGui::End();
```

Then, of course, I use the drawlist to make rectangles and lines.

My question being, is it possible to make a window that doesn't respond to mouse highlighting/mouse inputs? (I thought ImGuiWindowFlags_NoInputs would do that)
Is there a better way to render shapes?

(I also appoligise for the vagueness of this and it being cheat related)

Thanks

**Comment by ocornut** [comment]
- You are not specifying what "drawlist steals cursor in overlay" means at all, it's ambiguous making it hard to understand what your problem is in the first place.
- You may use `GetForegroundDrawList()` directly without creating a window.
- `Begin("")` with an empty string is illegal and should assert. If you don't have assert enabled you are going to run into lots more troubles.
- Sorry but #1586. I made an exception because your post shows effort but rules are rules so I'm closing this.

**Comment by wholivesinapineappleunderthesea** [comment]
WS_EX_NOACTIVATE fixed it, thanks!
