### ISSUE TITLE
Mouse Dragging

### ISSUE THREAD

**Issue by mhalber** [ocornut/imgui#260]
Hi, 

I am fairly new to imgui, so it is possible that I am missing something, however I believe there is possible bug with ImGui::IsMouseDragging()'s current behavior.
Even after finishing the drag over a window, said function will return true, with drag distance equal to 0.0 in both direction. Is there any reasoning for this function to return true after mouse is released? Only subsequent mouse click will stop the dragging from being reported.

A possible fix to that is to simply reset the g.IO.MouseDragMaxDistanceSqr[i] to 0.0 after the mouse is release in ImGui::NewFrame()

Thanks!

**Comment by ocornut** [comment]
Sounds like a probable bug. Will look into it in a few hours.

**Comment by ocornut** [comment]
Went through logs and can't seem a reason why it was this ever way. Because it was never part of a test perhaps it was always broken and assuming the user would test IsMouseDown() first.
