### ISSUE TITLE
Mouse-wheel scroll behaviour over child windows

### ISSUE THREAD

**Issue by Tom-Evers** [ocornut/imgui#2604]
**Version/Branch of Dear ImGui:**

Version: 1.71
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Operating System: Windows 10

**My Issue/Question:**
When scrolling a tall list that contains another scrollable field, that subfield 'captures' the mousewheel scroll action.
This should not be default behaviour: when the mouse does not move, the mousewheel should keep affecting the field that the scroll action originated in.

**Screenshots/Video**

![bug](https://user-images.githubusercontent.com/10848631/58789911-8960a100-85ef-11e9-8726-67797cd43654.gif)

**Standalone, minimal, complete and verifiable example:**
Build and run the docking branch.

**Comment by ocornut** [comment]
This is an interesting idea, I admit I hadn't thought of doing it this way (locking the target scrolling window until moving the mouse again). I'll give it a try when possible. I think OS X behaves the same way as we currently do. Also see #1245

**Comment by ocornut** [comment]
Closing as fixed, see #2579 for details.

**Comment by ocornut** [comment]
(Apologies, I have posted a message stating this was fixed but was thinking of a totally different issue. Deleted the wrong message and re-opened this.)

**Comment by ocornut** [comment]
Hello @Tom-Evers 
I have now implemented this feature and pushed it into master. It will be merged in docking shortly (you may merge it ahead if you want).
Commit:
https://github.com/ocornut/imgui/commit/26f14e056c01649af1f64f73e08c65900a932ad0

Very happy with this improvement!
