### ISSUE TITLE
ImGuiComboFlags_NoArrowButton ignores rounding

### ISSUE THREAD

**Issue by DucaRii** [ocornut/imgui#2606]
**Version/Branch of Dear ImGui:**

Version: 1.71 WIP
Branch: master
**Back-end/Renderer/Compiler/OS**

Back-ends: directx9 win32
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

Enabling the ImGuiComboFlags_NoArrowButton flag ignores combo rounding

**Screenshots/Video**

![alt text](https://i.imgur.com/sB76Urk.png "Arrows")
![alt text](https://i.imgur.com/6OUzQU7.png "No arrows")

**Comment by ocornut** [comment]
Thanks for noticing that. A fixing PR would be welcome!

**Comment by DucaRii** [comment]
sure thing!
I've fixed this by simply changing this line
`window->DrawList->AddRectFilled(frame_bb.Min, ImVec2(value_x2, frame_bb.Max.y), frame_col, style.FrameRounding, ImDrawCornerFlags_Left);`
to
`window->DrawList->AddRectFilled(frame_bb.Min, ImVec2(value_x2, frame_bb.Max.y), frame_col, style.FrameRounding, flags & ImGuiComboFlags_NoArrowButton ? ImDrawCornerFlags_All : ImDrawCornerFlags_Left);`

the pull request can be found here: #2607

**Comment by ocornut** [comment]
Applied fix, thank you!
