### ISSUE TITLE
Can't get keyboard input to work?

### ISSUE THREAD

**Issue by TimLeijten** [ocornut/imgui#2608]
Hi,

I am switching ImGui from directly using OpenGL to using my Engine API. All is well(Rendering and Mouse input works) except for Keyboard input.
I have a function that returns the id of the last pressed/released key and returns if it is being pressed or released. I pass that info to ImGui like this:
```
    if (Application::renderDeviceWindow->getKeyboardKeySingle().second)
    {
        io.KeysDown[Application::renderDeviceWindow->getKeyboardKeySingle().first] = true;
    }
    else {
        io.KeysDown[Application::renderDeviceWindow->getKeyboardKeySingle().first] = false;
    }
```
getKeyboardKeySingle returns the key id as first(int), and if it is pressed as second(bool). The key id(first) returned by getKeyboardKeySingle is exactly the same as the ones returned by GLFW. So the numbers corrospond to the characters here: [glfw docs](https://www.glfw.org/docs/latest/group__keys.html).
If I'm correct, ImGui "should" be able to directly use the characters(a-z 0-9) without mapping but needs help with backspace and such.
Now the problem is that with above code, nothing is typed. when I press a, I can see in the imgui demo window under "Inputs, Navigation and Focus->Keyboard..." that it registers my keys. When I press 'a' it says "keydown: 65 (0.3 sec)" and it goes away when I release it. So to me it sounds like I pass it to imgui correctly.
But when I try to type in a text box in the demo window, nothing happens. So I tried this:
```
    io.KeyMap[ImGuiKey_Backspace] = 259;
    io.KeyMap[ImGuiKey_A] = 65;
```
And the good news is, backspace works. The bad news is, typing the character 'a' still does nothing. I know input is working because I can delete text using backspace. But every other character just doesn't work.

So I am clueless on why?
Why does ImGui register my keypresses, but not type anything?(Even when I manually tell it the id of the key?)

I hope you can help!
I am using 1.68wip with docking support.

Thanks!

**Comment by ocornut** [comment]
`Characters` and `Keys` are different concepts in most API including imgui.
To register characters you need to call `io.AddInputCharacter()`. Please read the provided examples/ back-ends for reference.

**Comment by TimLeijten** [comment]
> `Characters` and `Keys` are different concepts in most API including imgui.
> To register characters you need to call `io.AddInputCharacter()`. Please read the provided examples/ back-ends for reference.

Thanks, that was it. I thought KeysDown would handle all keys because it can store so many values. But it works now.

**Comment by ocornut** [comment]
Excellent, closing this issue now!
