### ISSUE TITLE
there is not a -very- simple example or I cannot get :(

### ISSUE THREAD

**Issue by iboyildiz** [ocornut/imgui#2617]
thanks for your very valuable works..
if this is not a good question or even cannot be named an "issue", please forgive me, I'm pure noob (and besides my english is not good)
is there a complete noob example anywhere in this project? I mean only a gui that has 
 `ImGui::Text("hello world"); `

or like..
Is this impossible because of architecture of this library (if there is not a one)?
(I use an old machine, with lubuntu 16 -xenial ubuntu based- os)
Thanks so much, and best wishes!

**Comment by ocornut** [comment]
Hello,
The simplest examples are all in the examples/ folder.

**Comment by iboyildiz** [comment]
Thanks so much for your response.
I now find example_null and could make main.cpp, but there is not a gui!
can this example change to a gui showed one with few code lines? (or does this need too many lines to show a gui?)

**Comment by ocornut** [comment]
example_null doesn’t create a window nor a graphics context and therefore cannot display anything.

The other main.cpp files in examples/ are unfortunately as simple as they can be. The difficulty is that each framework and graphics api needs some cruft to create a window and a graphics context.

Maybe read a tutorial about eg: glfw or sdl to learn how to use that first.

**Comment by iboyildiz** [comment]
Thanks for your helps.
I hope I will understand the dynamics of sdl-opengl2 example if I look at it.. (because I can only run this and the directx9 examples - I think because this old machine )
Maybe if I understand, I would share my solutions here, for noobs like me..

**Comment by ocornut** [comment]
I will close this as answered for now. Feel free to ask more questions here.
