### ISSUE TITLE
Docking: Partially rendered menubar on other windows

### ISSUE THREAD

**Issue by aswerw** [ocornut/imgui#2623]
```
Dear ImGui 1.71 (17100)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1914
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x0000C441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
 DpiEnableScaleViewports
 DpiEnableScaleFonts
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.71 (17100)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: Unmodified example_win32_directx11 project.
Operating System: Windows 10 x64

**My Issue/Question:**

When multiple ImGui windows are docked together, and if one of them has a menubar, then a menubar will be partially rendered (just the gray background rectangle) onto all other windows in that group even if they don't have a menubar.

**Screenshots/Video**

![alt text](https://i.imgur.com/ykFog4E.png)

**Standalone, minimal, complete and verifiable example:**
Using unmodified example_win32_directx11 project.

**Comment by ocornut** [comment]
Thank you.
Pushed fix 07d3083
> Docking: Fixed rendering of outer decoration happening on non-visible docked window (#2623, #2109). Revealed by 0770449. We are actually better than before now, as previously those would get unnecessarily get rendered into a hidden draw list.
