### ISSUE TITLE
ImageButton - BackGround

### ISSUE THREAD

**Issue by AlexWhiteS** [ocornut/imgui#2628]
Is it possible to remove this dark blue background behind the button? And is it possible to remove the borders of the button / make it round. Thank you in advance.
ImageButton () function variables have not resolved the issue.
![7bhLzVmD](https://user-images.githubusercontent.com/47930474/59549705-4cd76280-8f6a-11e9-960a-8283c7ccf489.jpg)

**Comment by ocornut** [comment]
Closing for not following the issue template, was not first warning.
