### ISSUE TITLE
Make a collapse button in title bar optional

### ISSUE THREAD

**Issue by przemkovv** [ocornut/imgui#2634]
I would like to ask, if it has a sense to add a possiblity to not render a collapse button in a title bar, while still allowing to collapse a window by double-click on title bar. 
From my perspective, the interface that I'm designing would be cleaner without the button (see the screenshot)

![obraz](https://user-images.githubusercontent.com/3495693/59699992-d1d4ad00-91f2-11e9-9b4c-660b395b6ab4.png)

The simplest way would be to add an additional flag to `ImGuiWindowFlags_`, however, most of the bits are already used. The other approach would be to extend the `ImGuiStyle` struct by an additional field.

What do you think about the idea? If you agree, I could prepare PR.

**Comment by ocornut** [comment]
There's already a `style.WindowMenuButtonPosition` setting in style, which since 1.71 can be set to `ImGuiDir_Left` or `ImGuiDir_Right`. We could tentatively support `ImGuiDir_None`, however it would become problematic to honor it with docking enabled.

I would appreciate a PR for this change, then looking into the effect of it in the docking branch.

(\*) This is called "WindowMenuButton" because it's purpose is evolving in the Docking branch, but comments also refer to it as the "Collapse" button in Master.

**Comment by przemkovv** [comment]
I've missed somehow the `style.WindowMenuButtonPosition` option with `ImGuiDir_None` and it works great in my case. Also in the docking branch. 
Without docking: 
![obraz](https://user-images.githubusercontent.com/3495693/59703555-65f64280-91fa-11e9-87e9-b122e658613e.png)
With docking: 
![obraz](https://user-images.githubusercontent.com/3495693/59703600-81614d80-91fa-11e9-8425-db31f0af4f89.png)
In both cases, the "Hello World" window uses `ImGuiDir_None`.

However, if set to anything but `Left` or `Right`, the assert in `NewFrame` fires:
```IM_ASSERT(g.Style.WindowMenuButtonPosition == ImGuiDir_Left || g.Style.WindowMenuButtonPosition == ImGuiDir_Right);```

Nevertheless, is it ok for you if I prepare PR as following:
1. add `style.WindowShowCollapseButton`,
2. add support for `PushStyleVar`,
3. handle it in `RenderWindowTitleBarContents` function?

The other way would be to introduce a new enum for `style.WindowButtons` with `WinButton_Collapse` and, maybe in the future, with `WinButton_MaximizeRestore`. However, the latter is not supported yet (I don't know if there is even plan for that), then it could be an overkill for now.

**Comment by ocornut** [comment]
@przemkovv I have been unable to repro the glitch you mention with my similar patch, and see no reason for that happening, so applied similar patch as-is for now.

You can now `style.WindowMenuButtonPosition = ImGuiDir_None` or adjust it with the Style Editor.

Let me know if you encounter any issue with it! Thanks!

**Comment by xAyman** [comment]
yessir

**Comment by Tanishq-Banyal** [comment]
> ![obraz](https://user-images.githubusercontent.com/3495693/59699992-d1d4ad00-91f2-11e9-9b4c-660b395b6ab4.png)

Can you please share your theme ?

**Comment by DANGERMODVIP** [comment]
Hey bro I'm danger 

I need your small help plz help 

Plz give toggle buttons codes plz

My friend ask me I'm noob so plz help me bro
