### ISSUE TITLE
Cannot enable vtx offset for foreground and background draw lists

### ISSUE THREAD

**Issue by G-glop** [ocornut/imgui#2638]
Version: 1.72 WIP
Branch: docking

`GetViewportDrawList `on the docking branch forgets to set `AllowVtxOffset` flag introduced by d1e8b698d0e1c26744817490f8ee4f91182dcb9d, causing the foreground / background draw lists created by it to be limited to 64k verticies.

When setting `draw_list->Flags` also check for `RenderHasVtxOffset`: 
`(g.IO.BackendFlags & ImGuiBackendFlags_RendererHasVtxOffset ? ImDrawListFlags_AllowVtxOffset : 0)`

**Comment by ocornut** [comment]
Pushed the fix now, the `draw_list->Flags = ` assignment should have been removed after merging d1e8b698d0e1c26744817490f8ee4f91182dcb9d into docking. Thank you!
