### ISSUE TITLE
Have anyone tried out FreeType 2.10 version with color-layered outline glyphs?

### ISSUE THREAD

**Issue by bsviglo** [ocornut/imgui#2641]
Sorry that I'm not following the issue guideline but I'd rather want to emphasize that using color glyphs may significantly improve overall look of the dear imgui UI. 

https://www.freetype.org/

**FreeType 2.10.0**
2019-03-15
**This release brings one notable feature, namely support for color-layered outline glyphs (for example, scalable emoji glyphs)**. Additionally, the API reference has been completely overhauled and modernized, as already announced...

**Comment by ocornut** [comment]
I haven't looked into this specifically, but need to mention that with some effort it is possible to use the `AddCustomRectFontGlyph() / GetCustomRectByIndex()` API to register rectangles into the atlas and blit custom graphics data mapped to characters. This is being used by some teams to use **colorful icons**.

I agree that wiring the necessary changes to allow using colored glyphs more naturally would be useful.

**Comment by ocornut** [comment]
Browsing old issue I found this which is now resolved by #3369 and the `ImGuiFreeTypeBuilderFlags_LoadColor` flag. Closing as solved.
