### ISSUE TITLE
Is rubber-banding available?

### ISSUE THREAD

**Issue by newagelightbulb** [ocornut/imgui#2642]
**Version/Branch of Dear ImGui:**

Version: 1.60 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom
Operating System: Windows

**My Issue/Question:**

Is rubber-banding functionality part of ImGui, or is there an example? Looking through the code and searching on the web doesn't find anything (although it is referred to by different names) so I figured it was best to ask before trying to dive into it manually. Thanks.

**Comment by ocornut** [comment]
Maybe it would help if you clarified what you meant by rubber-banding.. especially as you pointed out it can be referred to by different names.

**Comment by newagelightbulb** [comment]
Sorry: I mean clicking and holding down the mouse puts you into a mode where you can drag a rectangle around UI elements and group-select them.

**Comment by ocornut** [comment]
So I guess I would call it ~"drag select" "rectangle select" , are we thinking about the same thing?

I suppose it would come naturally after finishing the new range/multi-select system (#1861), which works but I'm really unhappy with the way the API works.. I suppose when I am done with new tables I would naturally tackle the range/multi-select system and then maybe dragging to select would come after.

It would imply disabling movement on clicking on windows void (already exposed as `io.ConfigWindowsMoveFromTitleBarOnly` but would need to be made default).

I don't really have an ETA neither a recommendation to how this would work.

(PS: If you want to look at it I'd suggest first updating as 1.60 is old, and checking out the range-select branch)

**Comment by newagelightbulb** [comment]
Sounds good, I'll upgrade and take a look. Thanks!

**Comment by ocornut** [comment]
FYI 1.91.0 (July 2024) introduced a `BeginMultiSelect()` API which has a box-selection feature.
See https://github.com/ocornut/imgui/releases/tag/v1.91.0 and https://github.com/ocornut/imgui/wiki/Multi-Select for details.
