### ISSUE TITLE
bsf framework integration

### ISSUE THREAD

**Issue by pgruenbacher** [ocornut/imgui#2646]
I've starting on making a plugin for bsf repo. https://github.com/GameFoundry/bsf/issues/351

I've attached an image of my current output.
![Screenshot from 2019-07-03 17-45-37](https://user-images.githubusercontent.com/3332598/60627040-bf45a080-9dba-11e9-9bd5-1e501d8266b1.png)

The main thing I'm confused about at the moment is 
a) characters are not inputting. I've confirmed that the text inputs are focused, but for some reason keyboard inputs aren't registering. My guess is that imgui is not recognizing the keyboard inputs as text characters and so are not registering? Easiest way to confirm that? I'll probably figure this one out on my own.
b) text input symbol and the imgui window close icon aren't showing up. however when I do renderdoc I can confirm the mesh exists there. Seen this before?
![Screenshot from 2019-07-03 17-53-19](https://user-images.githubusercontent.com/3332598/60627249-74785880-9dbb-11e9-8c55-cfd5d758e118.png)

**Comment by pgruenbacher** [comment]
ah yea easy for a) issue, I was just missing 
    io.AddInputCharacter(c);

**Comment by pgruenbacher** [comment]
ah turning off back-face culling resolves the issue with some triangles not rendering. I guess bsf does back-face culling by default.

**Comment by pgruenbacher** [comment]
@ocornut shouldn't imgui be able to do a draw thread separate from the main thread? After all if the draw data is just a bunch of vertex data.. shouldn't it only be written to during the Imgui::Render()? However I noticed that the NewFrame() clears the RenderData, which would seem to indicate it's not thread-safe in that regard. Why not just clear the data at the start of the new Imgui::Render(). That way I can have on thread that does all the Imgui::Begin(), Imgui::End(), Imgui::NewFrame(), etc. while there can be a separate gpu thread that just calls GetDrawData() and all I have to worry about is making sure that the two threads are locked during the Imgui::Render()?

**Comment by pgruenbacher** [comment]
I just don't really understand what the point of clearing dthe draw data in the new thread is, I moved the clear draw data to the start of the Render() call and everything seemed fine...

**Comment by pgruenbacher** [comment]
@ocornut I ended up just doing a clone on the DrawList data and that seems to resolve the multi-threading issue. The Cloning of draw lists isn't gonna be a memory issue right?

https://github.com/pgruenbacher/bsf/blob/7893493b7a8db5c9bb3c9eabdff930ada4808be6/Source/Plugins/bsfImgui/Src/BsImguiRenderer.cpp#L136-L150

**Comment by pgruenbacher** [comment]
It's finished. https://github.com/pgruenbacher/bsfImgui

**Comment by ocornut** [comment]
Hello Paul,

> I  just don't really understand what the point of clearing dthe draw data  in the new thread is, I moved the clear draw data to the start of the  Render() call and everything seemed fine...

Pointers in ImDrawData are pointing to draw lists which are being appended to between `NewFrame()` and `EndFrame()`, it is correct to obsolete those pointers in NewFrame().

> I ended up just doing a clone on the DrawList data and that seems to resolve the multi-threading issue. 

This is the right way to do it currently.

It is arguably not ideal: we could ideally do a swap of the content of each ImDrawList, avoid most of the copying involved. We'd need a helper to make that possible.

> The Cloning of draw lists isn't gonna be a memory issue right?

I don't know what your specs are nor how much vertices you are using so I cannot tell for you.
The Metrics window will give you numbers or you can measure it yourself and decide if it is acceptable.
A large/complex imgui scene with rounding and borders will probably reach 500kb-1mb worth of data.

**Comment by ocornut** [comment]
As a request for your repo, in the readme could you try to use the full name "dear imgui" instead of just "imgui" which is ambiguous?

**Comment by pgruenbacher** [comment]
sure thing. i was just worried about memory leak when doing the cloning. i.e. I wasn't sure if the cloned draw list was getting cleaned up each frame or not. It'd be nice to have official helper method for cloning the entirety of the ImDrawData for separate render thread.

**Comment by ocornut** [comment]
> It'd be nice to have official helper method for cloning the entirety of the ImDrawData for separate render thread.

I agree, feel free to make a PR :) It doesn't exist because ImDrawData itself doesn't mandate ownership and so it is difficult to clear/free the contents of ImDrawData without additional context.

By only offering the CloneOutput function at the ImDrawList level we make it clearer that the user of this needs to take responsability delete those draw list, that is, until an alternative solution is found. Probably we should add a flag in ImDrawData to specify if it owns its draw lists.

It's not a hard problem but I also have hundreds of other open topics so the priority is not very high at the moment. I think it'd be nicer to support swapping from one ImDrawData to the other instead.

**Comment by pgruenbacher** [comment]
no worries. it works as is.
