### ISSUE TITLE
Find out how big the space is that isn't docked.

### ISSUE THREAD

**Issue by TimLeijten** [ocornut/imgui#2651]
Hi

I use dockspaces is my application, and would like to know how big the space is that isn't docked so I can draw my game view there. So what I mean is, when you dock windows in the dockspace and disable center docking, there will always be a square in the dockspace that isn't covered by docked window. I want to know the size and location of that square and draw stuff over it.
Is that possible?

Thanks!

**Comment by ocornut** [comment]
You may use `imgui_internal.h` and call `DockBuilderGetCentralNode()` with your dockspace id, but take nore that the central node won't always be empty.

I think what you really want to do is just to draw you game view inside a window, and then let the user dock that window anywhere.

**Comment by 0xnicholasc** [comment]
For my application, ImGui is something the use can toggle on and off. I am resizing my Vulkan viewport based on the central node. As you have said, the central node is not always empty, but that's not an issue for me. In short, I want my viewport to be derived by the application and not be a moveable window by the user.

I think it would be a good idea for the `DockBuilderGetCentralNode()` to be exposed to the main API (not just internal). I am new to ImGui, but it is my understanding that you don't guarantee forward-compatabillity in `imgui_internal.h`. Will you consider making this functionality available outside `imgui_internal.h`?

Currently, I have done it myself by adding to the namespace:
```
#include "ImGui_ext.h"
#include "imgui_internal.h"

namespace ImGui
{
	NodeBounds ImGui::GetCentralNode(ImGuiID dockspaceId)
	{
		auto centeralNode = ImGui::DockBuilderGetCentralNode(dockspaceId);

		return {
			centeralNode->Pos.x,
			centeralNode->Pos.y,
			centeralNode->Size.x,
			centeralNode->Size.y
		};
	}
}
```

**Comment by ocornut** [comment]
> Will you consider making this functionality available outside imgui_internal.h?

For now it is fine in there, the day it changes, if it changes, will be because we replaced the concept of central node with perhaps tags in nodes.

I'll close this as answered, but again, I believe the right way to handle it is NOT to query this information, but rather to render your game to a texture and render that texture in an imgui window using `ImGui::Image()`.
