### ISSUE TITLE
I am trying to write a tool for my engine, Imgui causes my game texture and light source to be lost on some maps(DX11)

### ISSUE THREAD

**Issue by CNLouisLiu** [ocornut/imgui#2654]
Dear ImGui 1.72 WIP (17101)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1921
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00

**Comment by CNLouisLiu** [comment]
Asked a friend, this seems to be a bug in the high version of the DX11 shader. The model generated by IMGUI conflicts with our own model.

**Comment by ocornut** [comment]
You are not providing a repro not enough details. We cannot guess what your problem is. Please edit or add enough details and I will reopen this topic.

**Comment by CNLouisLiu** [comment]
> You are not providing a repro not enough details. We cannot guess what your problem is. Please edit or add enough details and I will reopen this topic.

After using the dear IMGUI to draw the debug menu, the game screen lacks textures and light sources.

**Comment by ocornut** [comment]
It is possible that there are some state that dx11 backend doesn’t backup and restore properly. Try to comment out parts of the render function in imgui_impl_dx11 until you find which section is affecting your own render.

**Comment by CNLouisLiu** [comment]
Let me try it, this is a probabilistic problem so it is difficult to debug.

**Comment by CNLouisLiu** [comment]
This problem is a headache, my friend told me that there is a conflict when generating the model.

**Comment by ocornut** [comment]
I gave you the steps toward a solution above. When you isolate that code in imgui_impl_dx11.cpp is conflicting with your render we can attempt to remove more side-effects from imgui_impl_dx11.cpp.
