### ISSUE TITLE
Font missing ?

### ISSUE THREAD

**Issue by astron51** [ocornut/imgui#2659]
![image](https://user-images.githubusercontent.com/42890576/60980604-5daba600-a367-11e9-94b9-d08c4f4aa697.png)

Running in D3D9 Environment and this occur without any warning or error 
need help :( , the interface render just fine all the font display correctly but this happen randomly and occur glitch or bug like the photo above

**Comment by astron51** [comment]
![image](https://user-images.githubusercontent.com/42890576/60981121-51741880-a368-11e9-881b-cd04b3e96190.png)
I run this before running WndProc and here's the Reset function 
![image](https://user-images.githubusercontent.com/42890576/60981210-78cae580-a368-11e9-911b-eddc308effff.png)

**Comment by ocornut** [comment]
Missing repro and haven't filled issue template. Please fill issue template by Editing your post (click "New Issue" to see the template again but don't open a New Issue), then I will reopen this.

**Comment by ocornut** [comment]
This is most likely an error on your site. Please use a debugger to figure out if the font are loaded correctly, check the texture size and if the is created correctly into the DX9 context.

Using `GetGlyphRangesChineseFull()` is highly discouraged. Use a ImFontConfig structure and set Oversampling fields to 1 to minimize the size cost. Maybe your texture is too large for DX9/HW.

**Comment by ocornut** [comment]
FYI, work on `dynamic_fonts` branch aimed to be merged in 1.92 (#8465) solves this, as glyphs are rasterized and packed on demand when they are used.
