### ISSUE TITLE
Font went missing randomly

### ISSUE THREAD

**Issue by astron51** [ocornut/imgui#2660]
**Version/Branch of Dear ImGui:**

Version: 1.72 (17101)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: C++ Project using VS2019
SDK : 10.0 VS2019
Operating System: Windows 10 LTSC x64

**Issue**

Using the latest version of Imgui and I try to render it in D3D9 environment everything seems fine but the interface's font went missing randomly : 
![image](https://user-images.githubusercontent.com/42890576/60981501-0a3a5780-a369-11e9-946f-1e58b33210f1.png)

I run CreateContext before hooking WndProc

```ImGui::CreateContext();
ImGuiIO& io = ImGui::GetIO();
io.DeltaTime = 1.0f / 60.0f;
D3DDEVICE_CREATION_PARAMETERS D3DCP;
pDevice->GetCreationParameters(&D3DCP);
io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\msyh.ttc", 15.0f, NULL, io.Fonts->GetGlyphRangesChineseFull());
io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\msyh.ttc", 15.0f, NULL, io.Fonts->GetGlyphRangesJapanese());
ImGui_ImplWin32_Init(D3DCP.hFocusWindow);
ImGui_ImplDX9_Init(g_pDevice);
io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
io.ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange;
io.ConfigWindowsMoveFromTitleBarOnly = TRUE;
```
And here's the reset 
```
g_pFont->OnLostDevice();
	ImGui_ImplDX9_InvalidateDeviceObjects();
	HRESULT iReturnValue = ((tReset)oReset)(pDevice, pPresentationParameters);
	g_pFont->OnResetDevice();
	ImGui_ImplDX9_CreateDeviceObjects();
	return iReturnValue;
```

**Extra Info**

The entire framework I used work flawlessly with older version of ImGui and I just update Imgui to 1.72

**Comment by ocornut** [comment]
Hello,

I said in #2659 "don't open a new issue", Please stay in #2659. 

You are most certainly making a mistake to providing a fuller repro is the more likely way you will get help. Also check my other suggestion in #2659. Please also confirm that your asserts are enabled.
