### ISSUE TITLE
GetContentRegionAvail doesn't work with DisplayFramebufferScale / Retina

### ISSUE THREAD

**Issue by deltars** [ocornut/imgui#2661]
Hi,

GetContentRegionAvail returns too large a value with Retina displays.

```
ImVec2 ImGui::GetContentRegionAvail()
{
    ImGuiWindow* window = GImGui->CurrentWindow;
    return GetContentRegionMaxAbs() - window->DC.CursorPos;
}
```

Should become:

```
ImVec2 ImGui::GetContentRegionAvail()
{
    ImGuiWindow* window = GImGui->CurrentWindow;
    return GetContentRegionMaxAbs() - (window->DC.CursorPos * ImGui::GetIO().DisplayFramebufferScale);
}
```

Hope this helps.

**Comment by deltars** [comment]
Or it might be that GetContentRegionMaxAbs() should return a value in scaled space ie divided by DisplayFramebufferScale instead. Not really sure if the numbers are meant to be scaled at this point.

**Comment by ocornut** [comment]
I don’t think the suggested change is correct. Why do you expect this particular function to alter output while all the other functions don’t?

Currently the suggested solution is to load a font at the scaled size and scale the style accordingly with the ImGuiStyle::ScaleAllSizes() function. Every sizes should them be a factor of either font size either one of the style’s size.

**Comment by deltars** [comment]
Sorry Omar, maybe I don't understand what the function is meant to do.

I am trying to place an image that fills the remaining space in my fixed size window.

I was expecting GetContentRegionAvail to give me the correct size so that the image fills the remaining space. However, the image gets clipped and GetContentRegionAvail seems to give a bigger number than is the remaining space.

The difference seems to be the window position. The returned value from GetContentRegionMaxAbs() seems to be in retina pixel space, while the cursor pos seems to be in scaled space.

I am using 1.71

I think GetContentRegionAvail was doing what I expected on Windows, but I am now on my mac with retina display.

**Comment by ocornut** [comment]
There's no concept of "retina pixel space" vs "scaled space" in the current version, so you must be confused by something else. Displaying all those values using ImGui::Text() call or ImDrawList rectangle, or using Metrics>Tools to browse the rectangles may help you clarifying what is wrong

(Note that you need to make sure your clipping rectangle are scaled by thisi factor in your rendering function.)

**Comment by deltars** [comment]
thank you for replying.

my initial change suggestion is certainly wrong and i will look at it further and try to understand exactly what my issue is.

**Comment by deltars** [comment]
Yes sorry, I had my window set to a silly size (going off the screen) and so the region size was also silly.

Imgui api is working correctly.

Looking forward to docking!
