### ISSUE TITLE
How to draw an arc (circular line segment)

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#2662]
**Version/Branch of Dear ImGui:**
Version: 1.71
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui.net
Operating System: win10

**My Issue/Question:**
I didn't find a method for drawings arcs. I need this for things like knobs and diagrams. What would be a recommended method for adding required polygons to the draw list?

**Comment by ocornut** [comment]
If I look for the word “arc” in the api I can find ImDrawList::PathArcTo and ImDrawList::PathArcToFast which is exactly what you are looking for...

Use PathAddXXX functions to constitute a path then PathStroke or PathFillConvex.

**Comment by pixtur** [comment]
Thank you!

**Comment by ocornut** [comment]
Take note that there’s no concave polygon filler, only one for convex polygon. So depending on the exact shape you want to draw you might need to split the render in two parts.

Also as a neat trick, worth knowing that end points are connected by lines, so using only 4 arc you can draw a rounded rectangle (you don’t need to add the “lines” in between).

**Comment by pixtur** [comment]
Awesome. That's actually a very useful tip, because I'm in the process of implementing "houdini"-like node connections (which are basically just a number of arcs connected by lines). 

ps. sorry about asking stupid question. I have no idea, how I could miss the arc functions. I guess I have to switch from googling "imgui draw arc" to actually reading imgui.h.

**Comment by ocornut** [comment]
This topic #306 may have some useful references.

> ps. sorry about asking stupid question. I have no idea, how I could miss the arc functions. I guess I have to switch from googling "imgui draw arc" to actually reading imgui.h.

No worry! (I myself get a little cranky with my answers sometimes mostly for being overwhelmed with the requests).
