### ISSUE TITLE
How to use multiple OS Windows

### ISSUE THREAD

**Issue by Darkratos** [ocornut/imgui#2663]
Version: 1.79
Branch: master

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp 
Compiler: VS2019
Operating System: Windows 7 x64

Hey, I was wondering how can I do this:
https://twitter.com/ocornut/status/946470996529336321

When I try to setup multiple windows it becomes like this:
![Sem título](https://user-images.githubusercontent.com/49787965/61163627-8eb1e500-a4e5-11e9-832b-5750dcf0eac8.png)

I ommited the contents of the first window, but everything is as expected

**Comment by ocornut** [comment]
I don’t understand the question or the problem.
Multi-viewports are available in the Docking branch.

**Comment by Darkratos** [comment]
Sorry, but the examples don't show anything about multiple HWND's.
I can initialize one window using:

`ImGui_ImplDX9_Init(pDevice);
ImGui_ImplWin32_Init(window);`

But I can't switch to another one.

**Comment by ocornut** [comment]
You haven’t really specified exactly what you are trying to do, so I am just going for what’s available.

In the Docking branch if you enable multi-viewports you can drag any imgui window outside of the main HWND and it will turn into its own viewport (with its own HWND).

**Comment by Darkratos** [comment]
At the start of the program, I create two windows, one is the main and the other is hidden (shows only when I click a button).
I initialize directx on both(2 HWNDs and 2 LPDIRECT3DDEVICE9s).

Then I initialize ImGui on the first window and it renders fine.
The problem is: when I click the button to "unhide" the 2nd window, I don't have a way to switch the HWND's. Even if I call my InitImGui with the other pDevice and HWND.
Could you provide an example of how we can do it? Or it isn't possible at the moment.

**Comment by Darkratos** [comment]
Sorry, I now realized that I didn't need to create another window, I just had to use the MultipleViewportsEnable flag. Thanks!
