### ISSUE TITLE
How can i go about hooking ImGui to an application using C#?

### ISSUE THREAD

**Issue by renewablezip01** [ocornut/imgui#2669]
I was wondering how you can hook ImGui to a application using C#. Does it work the same way as C++? Or is there any code differences between them that i have look take into account?

I don't really know how to go about it to figure out what to do. If someone could answer this question it would be really helpful. Thank you :)

Edit: Most tutorials I have seen use C++

**Comment by ocornut** [comment]
Hello,

Hooking into another app to run your code is probably possible, but that’s not really a question in the scope of dear imgui. There’s a C# binding for the library this is the main question that matter. 

You’ll probably find your answer on another place that specialize in hooking apps.
