### ISSUE TITLE
Obtain the Caret position from a textfield outside of a callback

### ISSUE THREAD

**Issue by Folling** [ocornut/imgui#2671]
Is there a way to get the Caret position from a Textfield without using a callback?
I've been unable to find one. The `CursorPos` in `ImGuiInputTextCallbackData` is only available in the callback, however the callback cannot be used with capturing functions, so I was looking for something along the lines of:

```cpp
if(ImGui::InputText("label", someString)) {
    handleTextChange();
}

int caretPosition = ImGui::GetCaretPosition();
doSomethingWithCaretPosition(caretPosition);
```

**Comment by ocornut** [comment]
> however the callback cannot be used with capturing functions

Why don’t you use a regular non-capturing lambda/function, use the void pointer to pass the address you need to write to.

**Comment by Folling** [comment]
Ah sorry, I didn't see the parameter for the user_data. Thanks for the quick response!
