### ISSUE TITLE
Editing DualShock 4 controller configuration?

### ISSUE THREAD

**Issue by ndevasia** [ocornut/imgui#2679]
Version: v1.65
Branch: master
Back-ends: Using custom engine backend
Compiler: VS2017
Operating System: Windows 10 Enterprise v. 1809

I'm trying to replicate the behavior of a custom debug tool. Specifically, the custom debug tool can be moved around the screen by the left stick. Normally in ImGui, you can do this by holding S (the menu button) and moving the left stick. I am currently replicating the debug tool behavior behavior in ImGui by setting io.NavInputs[ImGuiNavInput_Menu] = 1 every time the left stick moves, but I was wondering if there is a way to edit the configurations here such that I can move the ImGui window around with just the left stick alone and without having to set the NavInput_Menu variable every single time.

**Comment by ocornut** [comment]
> without having to set the NavInput_Menu variable every single time.

If you are saying this is working, what's the problem with doing that?

You could poll inputs and call `SetWindowPos()` yourself and not pass the inputs to the Navigation system..

Trying to mimic all specificity of an old/existing tool is probably not a good idea either.. you are going to be fighting against more and more dear imgui features.

**Comment by ocornut** [comment]
Ping @ndevasia ?

**Comment by ocornut** [comment]
Closing as abandonned.
