### ISSUE TITLE
Synchronization of window move flags

### ISSUE THREAD

**Issue by N0LECODER** [ocornut/imgui#2681]
**Version/Branch of Dear ImGui:**

Version: 1.72WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_directX9.cpp + imgui_impl_win32.cpp
Compiler: VS2017
Operating System: Windows 10

**My Issue/Question:**

Soo I wonder if there is way to move WIndows`s Window when I am moving ImGui::Begin() Window.Since I removed captionbar and my project looks good I also wanna make it able to move to second monitor or soo.

![Screenshot_1](https://user-images.githubusercontent.com/34031968/61580267-35166f80-ab10-11e9-9822-cf0580aa4a2a.png)

**Comment by ocornut** [comment]
You should probably be looking into the the multi-viewport feature in the Docking branch.
