### ISSUE TITLE
InputText is cleared on focus loose

### ISSUE THREAD

**Issue by zernax** [ocornut/imgui#2687]
**My Issue/Question:**
I am currently working for a program for my friends that they wanted, and i am making a login, i am currently using this code : 
![image](https://user-images.githubusercontent.com/40726857/61756246-1969ce00-ad89-11e9-9835-c3780568fa54.png)
 and when the inputtext is loosing focus, it just clears, which never happened to me before, it was all good before, may someone help me ?, thank you :)
sorry for the naming, its not me that decided, what i mean by it clears i mean that it just removes what i typed

**Comment by ocornut** [comment]
Sorry but #1586
