### ISSUE TITLE
Orconut closed my issue without even reading what i said, please read this thank you :)

### ISSUE THREAD

**Issue by zackylemur** [ocornut/imgui#2688]
Orconut its not a cheat, if you saw amphoracheats in the thing thats not my account thats my friend's account i had problems with github verification, its a software that reunits people in fortnite, like for scrims but like the software helps you get into match with them, please unlock my issue,

_Originally posted by @ocornut in https://github.com/ocornut/imgui/issues/2687

**Comment by ocornut** [comment]
Sorry but #1586
