### ISSUE TITLE
Design from anthor guy can anyone this?

### ISSUE THREAD

**Issue by Florian9900** [ocornut/imgui#2689]
**Version/Branch of Dear ImGui:**

Version: New

**My Issue/Question:**

Hello can you help me (can you me this write under screenshots is (imgui::.......)
how make this guy this can anyone me send source code or write

**Screenshots/Video**

https://i.gyazo.com/b732212826df6a13cebfac6aa2dd9a6e.png

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Please do not forget this!
Design

**Comment by ocornut** [comment]
Sorry but #1586
