### ISSUE TITLE
Inlining combos seems to break the combo position and size.

### ISSUE THREAD

**Issue by Aborres** [ocornut/imgui#2691]
Dear ImGui 1.72 WIP (17101)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1914
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00

**My Issue/Question:**

Seems like if you Inline (ImGui::SameLine()) two Combos the second combo goes way over the window and, depending on the size of the window this can extend beyond the width of your screen. Also, the second Combo appears completely misaligned to where it is located in the window.

I was having this issue using the main branch, I have switched to the docking branch and I have the same issue there. I have attached two images that show the problem. 

To simplify the problem I am testing this using your **example_glfw_opengl3** project with no modifications (apart from the small snippet) and nothing enabled in imguiconfig.h.

**Screenshots/Video**

Aligned
![image](https://user-images.githubusercontent.com/9192778/61819684-70d07280-ae4b-11e9-88c4-7423215c3305.png)

Misaligned and over the window size
![image](https://user-images.githubusercontent.com/9192778/61818810-8e044180-ae49-11e9-8f51-cc7dcfa87ff3.png)

Initial example

https://user-images.githubusercontent.com/9192778/61595523-3ae38200-abf0-11e9-90a5-d1c6832b252e.png

I have pasted this snippet in main.cpp:173

```
            ImGui::Begin("Test");
            int aspect_ratio = 0;
            const char* items[] = {"Free", "4:3", "16:9"};
            if (ImGui::Combo("AspectRatio", &aspect_ratio, items, 3)) {}

            ImGui::SameLine();

            int current_ = 0;
            if (ImGui::Combo("Image", &current_, items, 3)) {}
            ImGui::End();

```

**Comment by ocornut** [comment]
You need to adjust the width of the combo box.
The width of framed items is defined by `PushItemWidth()/PopItemWidth()` or `SetItemNextWidth()`.
The default value for it is == `GetWindowSize().y * 0.65`.
Most generally if you have multiple of them on a same line they won't all have a label to display.

**Comment by Aborres** [comment]
Is this the intended behavior then? 
Since (until now) most things have always aligned and fit automatically I thought It might be a bug.

Adding the width does indeed fix the combos.

```
        const float width = ImGui::GetWindowWidth();
        const float combo_width = width * 0.25f;
        ImGui::SetNextItemWidth(combo_width);

        const char* items[] = {"Free", "4:3", "16:9"};
        ImGui::Combo("AspectRatio", &aspect_ratio, items, 3);

        ImGui::SameLine(2.0f * combo_width);

        ImGui::SetNextItemWidth(combo_width);
        ImGui::Combo("Image", &current_, texture_names_.c_str());
```

![image](https://user-images.githubusercontent.com/9192778/61821588-7af47000-ae4f-11e9-8ecf-f9ef7839137f.png)

**Comment by ocornut** [comment]
It is intended behavior indeed.
I wouldn’t say it is ideal, but only we have more advanced layout tech in place this is how it would work.

**Comment by Aborres** [comment]
Thanks a lot for the support.
