### ISSUE TITLE
Advice on how to implement a custom drag/edit control

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#2695]
**Version/Branch of Dear ImGui:**
v1.71 master  / imgui.net / win10

**My Issue/Question:**
I want to implement a custom version of the _DragFloat_ control. I already managed to implement a custom dragging behavior for value modification and add our undo/redo functionality. But I can't figure out, how I can replace the _button control_ with a _text input control_ after clicking instead of dragging:

1. It tried to understand the implementation of `DragFloat` but don't know how to replicate it with the public API. Is this even possible?
2. I can't find a "labeless" input field control, that shares the button's layout behavior.
3. I don't know to transfer the "hotness" of the active button to a newly active (focused) input control.

I'm not asking for examples or sample code but for general estimation if this is feasible with the public API.

Thanks a lot!

**Comment by ocornut** [comment]
Hello Thomas,

I haven't looked at this in details yet, but as for
> general estimation if this is feasible with the public API.

What you are expecting should be feasible with imgui (and if there's anything blocking you we should fix it), however for custom widgets of that sort it is expected to go through the `imgui_internal.h` API. In this specific case you may need to replicate the `temp_input_xx` related code in `DragScalar()`.

For anything "labeless" use a string in the format `"##id"`, please read the FAQ about it.
