### ISSUE TITLE
Tip: use Begin/BeginChild to put yourself into the context of an already drawn window

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#270]
*EDIT* see below for better version
Not sure where to post that until we have a Wiki (we will).

I am writing a dumb memory viewer that is to become a memory editor. Literally 5 minutes so far. Code below.

![memory editor](https://cloud.githubusercontent.com/assets/8225057/8631088/60f44788-272c-11e5-9450-709c5ef18ca9.PNG)

**The interesting trick that isn't obvious to many, is that you can Begin a wiindow *again* just to put yourself into the context of that window.**
So here I want to react to the user inputting an address to go to, I BeginChild() again the child that I've already drawn so I can use SetScrollFromPosY() on it.

```cpp
ImGui::BeginChild("##scrolling", ImVec2(0, -ImGui::GetItemsLineHeightWithSpacing()));
//...do stuff
ImGui::EndChild();

//...
// and then much later
ImGui::BeginChild("##scrolling");
ImGui::SetScrollFromPosY(ImGui::GetCursorStartPos().y + (goto_addr / Rows) * line_height);
ImGui::End();
```

It has many uses, thought I'd share that!

**Comment by paultech** [comment]
I'm going to use that for you know what! Awesome tip I wasn't aware of.

**Comment by ocornut** [comment]
Also note you can also use multiple begin to append to a window.
It can be useful if you want to just log stuff.

```cpp
  void MyDeepNestedFunctionThatDoesThing(float v)
  {
     ImGui;:Begin("log"); // append
     ImGui::Text("MyDeepNestedFunctionThatDoesThing %f", v);
     ImGui::End();
  }
```

(You can even omit begin/end to add to a default window called "Debug")

**Comment by ocornut** [comment]
Btw I posted the final one here
https://gist.github.com/ocornut/0673e37e54aff644298b

![memory editor3](https://cloud.githubusercontent.com/assets/8225057/8632155/97ab86cc-274c-11e5-964e-3e2fc044e03c.gif)

**Comment by emoon** [comment]
Neat :) Thanks for posting this.

**Comment by edselmalasig** [comment]
how do i add use ImGui::Begin() / ImGui::End () properly I am using opengl and sdl on windows? i am using the project sdl_opengl_example. everytime i call ImGui::Begin(params.. ) the program crashes. can you guys help?

**Comment by ocornut** [comment]
Moved to https://github.com/ocornut/imgui/wiki/Tips
