### ISSUE TITLE
[Question] What's the actual impact on overall performance? imgui suitable for HPC software?

### ISSUE THREAD

**Issue by iBaer** [ocornut/imgui#2703]
**My Question:**

I planned to do some benchmarks myself, but maybe things have already been done.
For our high performance software I was considering on migrating the GUI (outdated retained mode framework) to imgui. Now since imgui is basically constantly redrawing itself I am worried about the impact it will have on the simulation at the core of the software.

What needs to be rendered is an interactive 3D viewer of a CAD model with some surrounding menus here and there. The software is running some physical simulations on the model basically using all available CPU cores at 100%, which results in changes visible in the 3D viewer.

Would imgui have any impact at all coming from a retained mode GUI? Unfortunately I couldn't find any sources claiming more than just the usual retained mode vs immediate mode comparisons.

**Comment by ocornut** [comment]
There's not a single yes/no answer to that question.

Dear ImGui puts a different type of burden on you, if your code to iterate and submit your structures is abnormally slow (unnecessary allocations, copies) and you are throwing 10k items at imgui naively without clipping, then it could be a problem.

Generally and if you are careful the impact should be marginal, and very well easily recouped by the fact that your UI/tooling dev productivity gets decoupled allowing you to put more energy in the rest of your app or into making tools leading to wider improvements of all sorts.

In the current version enabling FrameRounding and FrameBorderSize is quite slow but there is a plan to make that very cheap again.

Best to do your own measurement... just run the Demo window in your app and see what it does for you..

> The software is running some physical simulations on the model basically using all available CPU cores at 100%, which results in changes visible in the 3D viewer.

What you will probably need to do however is to make sure your dear imgui can keep rendering at interactive frame rate (e.g. 30+ FPS) so you may need a model where your UI thread is not bottleneck by slow simulation. If your UI runs at slow framerate the experience will be very poor. 

For low framerate you'll also need to implement a simple IO queue (e.g. https://gist.github.com/ocornut/8417344f3506790304742b07887adf9f) .. this will be added into core imgui at some point.

**Comment by iBaer** [comment]
Thanks for your well elaborated answer.
Including the Demo window into my application (it was quite simple since we already have a SDL routine running) was a nice idea.
I couldn't measure any major performance decrease at all, which is great and entirely what I was hoping for. Though I will do some proper measurements and performance analysis late ron.
Engineers running the simulation in GUI mode won't be affected much and the others wouldn't notice the change anyway.
The next step is -- just as you mentioned -- to find out if the engineers running the software will be pleased with some changes to the look and feel that are unavoidable by changing to dear imgui.

**Comment by ocornut** [comment]
Great. I'll be closing this issue now, but feel free to comment if needed and I can get it reopened!
