### ISSUE TITLE
Vulkan backend can't render into a multisampled frame buffer

### ISSUE THREAD

**Issue by vilya** [ocornut/imgui#2705]
The Vulkan backend always sets the MSAA sample count to `VK_SAMPLE_COUNT_1_BIT` when creating its pipeline in `ImGui_ImplVulkan_CreateDeviceObjects`, which means you get errors if you try to render into a multisampled framebuffer.

I was able to work around this by adding a new `MSAASamples` member to the `ImGui_ImplVulkan_InitInfo` struct and using that to pass in the correct value for the sample count when I setup ImGui. This works, but it means the field will have an invalid value if you zero-initialise the struct, so I'm not sure whether this is technically the "right" way to fix it.

**Version/Branch of Dear ImGui:**

Version: 1.73 WIP
Branch: master, commit 3548fb80134cdf90565241d0930db38ba1d7fcf7

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_vulkan.cpp + imgui_impl_glfw.cpp

**Comment by ocornut** [comment]
I believe adding the field with a comment ">= 1" but also turning 0 to 1 in `ImGui_ImplVulkan_Init()` would be acceptable? Could you submit a PR for it? 
Thank you!

**Comment by vilya** [comment]
Thanks, I've submitted the PR.

**Comment by ocornut** [comment]
Merged, thank you!
