### ISSUE TITLE
SetNextItemWidth() not working on Button widget

### ISSUE THREAD

**Issue by kyranf** [ocornut/imgui#2712]
**Config/Build information:**  
```
Dear ImGui 1.71 (17100)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1900
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1920.00,1017.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```
**Version/Branch of Dear ImGui:**

Version: 1.71
Branch: master (as of release 1.71 )

**Back-end/Renderer/Compiler/OS**

Back-ends: GLFW / GL3W and Open GL 3 
Compiler:  visual studio 2015 
Operating System: Windows 10

**My Issue/Question:**
The SetNextItemWidth() function works fine on a LabelText widget, but not for a button widget or the Text widget. The buttons sizes are just auto-scaled for the text, it seems. In my screenshot, every button visible there has been requested to be 100 wide.  It also doesn't seem to work for "text" widget. 

IS this intended functionality or am I missing something?

Is this something I can achieve in the short term with blank space character padding?

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/7900774/62553238-e0405c00-b866-11e9-9a1c-2a0613361751.png)

**Standalone, minimal, complete and verifiable example:** 

```
		ImGui::SetNextItemWidth(100.0f);
		if (ImGui::Button("Start")) {
			handleStartButtonPressed();
		}
```

**Comment by ocornut** [comment]
There’s code/design missing for that as mentioned in the release note for SetNextItemWidth. The problem is that we would likely want SetNextItemWidth to act differently as PushItemWidth/PopItemWidth (which shouldn’t affect eg Button for many reasons) and that would constitute a large inconsistency. 

Note that you can literally provide a width to the Button() function too.

**Comment by kyranf** [comment]
Thank you for that explanation. I understand, things are work-in-progress.

For the Button widget arguments, there is an ImVec2 argument for size which I will experiment with. Thanks!

**Comment by kyranf** [comment]
yay!
```
ImGui::SetNextItemWidth(100.0f);
		if (ImGui::Button("Start", ImVec2(100, 0))) {
			handleStartButtonPressed();
		}
```
![image](https://user-images.githubusercontent.com/7900774/62555896-afaef100-b86b-11e9-828f-15c6c91be37a.png)
