### ISSUE TITLE
Image and ImageButton

### ISSUE THREAD

**Issue by LegendRX** [ocornut/imgui#2713]
hello i am trying to draw image and image button but i cant find out how i tried to use 

D3DXCreateTextureFromFileInMemoryEx(pDevice, 
			&mgByte,
			sizeof(mgByte),
			100, 
			100, 
			D3DX_DEFAULT, 0, 
			D3DFMT_UNKNOWN, 
			D3DPOOL_MANAGED, 
			D3DX_DEFAULT, 
			D3DX_DEFAULT, 0, 
			NULL, NULL, &div);
as d9d menu but that makes the gui not appear

**Comment by ocornut** [comment]
Not filled issue template, closing.
