### ISSUE TITLE
Errors in imgui_impl_opengl3.cpp

### ISSUE THREAD

**Issue by ejamshidiasl** [ocornut/imgui#2719]
Hello
i have simple glfw application and now i want to add imgui to it
i downloaded imgui files and examples work but i have error in my application
[i added all include , library and etc. like example]
ERROR:
imgui_impl_opengl3.cpp -> identifier glBlendEquation is undefined
imgui_impl_opengl3.cpp -> and more than 200 errors like this
(i edit nothing in this file)

**Comment by ocornut** [comment]
Hello,

1) please fill the requested issue template everytime you open an issue. If you don’t your next issue with be closed.

2) please first confirm if the example application are building. Eg, try building examples/example_glfw_opengl3 with the provided project file or batch file or makefile.
