### ISSUE TITLE
Some Chinese glyphs are missing, for example '浏' (unicode: 0x6d4f)

### ISSUE THREAD

**Issue by zhaohanli** [ocornut/imgui#2721]
**My Issue/Question:**

XXX _(please provide as much context as possible)_
Line 2590-Line 2598 in imgui_draw.cpp:
const ImFontGlyph* ImFont::FindGlyph(ImWchar c) const
{
    if (c >= IndexLookup.Size)
        return FallbackGlyph;
    const ImWchar i = IndexLookup.Data[c];
    if (i == (ImWchar)-1)
        return FallbackGlyph;
    return &Glyphs.Data[i];
}
in this function, i returns 0xff for the Chinese character ‘浏’ (c = 0x6d4f), denoting no valid glyph found in arialuni.ttf.

**Screenshots/Video**

![word](https://user-images.githubusercontent.com/30373848/62815590-5b4a9080-bb4d-11e9-9be1-4c40515fec82.PNG)
![glyphs](https://user-images.githubusercontent.com/30373848/62815731-67375200-bb4f-11e9-9bcf-96615e11218b.PNG)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
static char strText[256];
strcpy(strText, u8"浏览文件夹");
ImGui::InputText(u8"输入文字", strText, IM_ARRAYSIZE(strText));

**Comment by ocornut** [comment]
Please do not delete the contents of your original post when you've solved your problem.
Those public forums are meant to help other users.
