### ISSUE TITLE
ColorPicker / ColorEdit Widget Wrong Conversion from HSV to RGB

### ISSUE THREAD

**Issue by MegaBor** [ocornut/imgui#2722]
**Version/Branch of Dear ImGui:**

Version: 1.72b
Branch: master

**My Issue:**

Hi, I think color picker doesn't work well when doing conversion from HSV to RGB.
When I set S to 0, it jumps to red. In Photoshop color picker doesn't do that.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52722806/62832685-cc17a880-bc32-11e9-81cb-a7ff38e4125a.gif)

**Comment by MegaBor** [comment]
Is there a way to force the color picker to not use HSV format? So I don't have to bother regarding this issue. I saw `ImGuiColorEditFlags_DisplayRGB` flag, but although I'm using it, it still displays HSV when I pick a color. How about also displaying `ImGuiColorEditFlags_DisplayRGB` and `ImGuiColorEditFlags_DisplayHex`? The assertion doesn't allow that.

**Comment by IAmEki** [comment]
Have you tried `ImGuiColorEditFlags_InputRGB`?

**Comment by MegaBor** [comment]
@IAmEki, Thanks! I see with the new changes it does display RGB with this flag, but the problem where the color transition jumps to red still there. I think the color values needs to be clamped.

**Comment by ocornut** [comment]
See #2383 (and #2384) to understand the issue.
If your code is storing RGB i don't think this is fully solvable.

- You can store HSV values and use the `InputHSV` flag to avoid those singularities.
- We could potentially make an open color picker instance store HSV intermediate values internally to work-around this... for the lifetime of the picker you would be protected. However this wouldn't work with HSV sliders in any regular in-line ColorEdit widget, so that would create a discrepancy between the two usages (in-line vs picker popup).

I don't know if there is a better solution. @haldean would know perhaps ?

**Comment by haldean** [comment]
I agree 100% with what you said Omar; as long as the application is holding all of the color state, the widget doesn't have enough information to keep the hue slider in the same place when S/V go to 0. To fix, you'd have to pass HSV values (using `InputHSV`) or the library would need to store a "last hue" somewhere.

**Comment by ocornut** [comment]
Hmmm, we could probably store a "last hue" associated to the last active widget ID, and have ColorEdit4/ColorPicker4 restore that hue on edit.. That would maybe attenuate the issue enough?

**Comment by MegaBor** [comment]
Thank you @ocornut. Looking into this issue more in depth, I believe storing last hue could potentially solve this issue. However, I'm pretty new to using ImGui, so I'm not confident enough with the sources providing a pull request to this, but I'll try to see if something comes up in mind.

**Comment by ocornut** [comment]
Merged this, thank you @rokups !

**Comment by ocornut** [comment]
Merged a fix for this, thank you @rokups !

The fixes stores last Hue for a given RGB set.
Note that the picker has another singularity of the same kind, when setting V=0 breaks Saturation. A fix for that other issue could be nice sometimes.
