### ISSUE TITLE
Make ImRect public into imgui.h

### ISSUE THREAD

**Issue by zyzyz** [ocornut/imgui#2727]
(Click "Preview" to turn any http URL into a clickable link)

**Version/Branch of Dear ImGui:**

Version: 1.71
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MSVC
Operating System: Windows 7

**My Issue/Question:**

Hello ocornut,

I was wondering why keeping ImRect internally but exposing ImVec2&ImVec4 as parameter of API for outside user? I'm writing custom widgets like "function curve graph" and IMO ImRect would be used frequently and it's common to let users __pass ImRect in__ from their own programs. However, besides including "imgui_internal.h" in .cpp implementation file of custom widgets, users also have to include it in their own programs in order to access ImRect, which is not what I am expecting as this leaks the interal things of ImGui out.

I know 
+ there are some native ImGui APIs that still using two ImVec2 or one ImVec4 for representing a "Rect" parameter from users, 
+ I can still create my own Rect data structure as parameter type,

but why bother? Even if it's intended to force ImGui users to make their own types and do the implicit cast in imconfig.h, ImRect is not declared in imgui.h file like ImVec2/ImVec4 so there is not way to "inject" my own Rect type.

So I'm asking is it possible to move ImRect into imgui.h in order to make it "public"?
If not, I would like to know what's the concern? 

Thanks.

**Comment by ocornut** [comment]
The reasons it isn't public are:
- To try avoiding adding "high-level" data structures in the public API when possible. Obviously `ImRect` is not super high-level but it is still higher-level than float/ImVec2 and starts pushing the user toward not using their own data type, which makes dear imgui a little more frameworkey-oppressive. 
- Taking that decision would require making use that the `ImRect` api is the best it can be and won't break. I think methods like `Overlaps`, `ClipWithFull`, `IsInverted` may currently be confusing or misleading I am not sure it is of public-quality. Generally it would be widening our surface of responsability and maintainance. 
- We already rarely ever expose classes with methods that would feel like an expeption. Even if it does makes sense, perhaps moving some of those features as loose ImXXX functions would be more consistent and more compatible with using dear imgui from other languages.
- Additionally if we exposed ImRect and didn't use it in the publci API it would seem weird and there would be added pressure in changing some of the existing API using two ImVec2 to use ImRect instead, which would break more things.

None of this are very hard requirements but they'd require time to evaluate and redesign some of it. The assumption with `imgui_internal.h` is that things might possibly break (even if ImRect rarely ever does) and it is used by more advanced users who have a easier time dealing with changes.

I'm not 100% against it but my suggestion is that it is better to either use two ImVec2 in your api either just use ImRect and that would require imgui_internal.h in your code. If you are willing to spend the time doing a deeper analysis of the points I posted above (naming convention etc.) that maybe would help making that change.

Note that ImVec4 are almost always used for colors apart from `ImVec4 ClipRect` in the `ImDrawCmd` structure.

**Comment by zyzyz** [comment]
Thanks for your suggestion and detailed explanation.

I haven‘t had a deep thinking yet about all the points you mentioned, but for the 4th point, maybe having an extra overload is not a bad thing for flexibility and convienence? But I'm guessing it conflicts the design cocept of ImGui? (correct me if I'm wrong :stuck_out_tongue_closed_eyes:)

I would update in the future if I figure out good solutions.

Please feel free to reopen this issue if you feel it's necessary.
