### ISSUE TITLE
How to change font in c# binding?

### ISSUE THREAD

**Issue by ejamshidiasl** [ocornut/imgui#2730]
Hello
i cannot change font in ImGui.Net with io.Fonts.AddFontFromFileTTF please help.
```
// Get font texture from ImGui
            var io = ImGui.GetIO();
            io.Fonts.GetTexDataAsRGBA32(out byte* pixelData, out int width, out int height, out int bytesPerPixel);

            // Copy the data to a managed array
            var pixels = new byte[width * height * bytesPerPixel];
            unsafe { Marshal.Copy(new IntPtr(pixelData), pixels, 0, pixels.Length); }

            // Create and register the texture as an XNA texture
            var tex2d = new Texture2D(_graphicsDevice, width, height, false, SurfaceFormat.Color);
            tex2d.SetData(pixels);

            // Should a texture already have been build previously, unbind it first so it can be deallocated
            if (_fontTextureId.HasValue) UnbindTexture(_fontTextureId.Value);

            // Bind the new texture to an ImGui-friendly id
            _fontTextureId = BindTexture(tex2d);

            // Let ImGui know where to find the texture
            io.Fonts.SetTexID(_fontTextureId.Value);
            io.Fonts.ClearTexData(); // Clears CPU side texture 
```

**Comment by ocornut** [comment]
Not read guideline, not filled issue template, not asking on the right repository.
I am sorry Esmail but this is the third time. I have to block you from this place because I need to protect my sanity and the quality of issues/requests.

**Comment by ejamshidiasl** [comment]
sorry
ImGui.Net is not active
please help
------
there is no error or warning but font not change

**Comment by ocornut** [comment]
The imgui.net repo is perfectly active and you posted there 27 minutes ago. You HAVE to follow the rules if you post here. Otherwise please post elsewhere.

(There’s a dummy website “imgui.net” where someone who made a clone “hello imgui” is trying to surf on user confusion.. the whole thing is misleading and should be avoided)

**Comment by ocornut** [comment]
Use the demo window to go the style editor and browse fonts to see if your font is load3; and how many fonts there are. 

Maybe your font was loaded after the default font. In this case you can use PushFont at the beginning of your frame to change the font, or you can register your font in a different place so it is the default font.

Blocking you now.
