### ISSUE TITLE
Using DirectX SRV with OpenGL Implementation

### ISSUE THREAD

**Issue by nicovanbentum** [ocornut/imgui#2733]
Branch: Docking
Back-ends: imgui_impl_opengl3.cpp + imgui_impl_dx11.cpp
Operating System: Windows 10

In my current project I switch between DirectX and OpenGL by calling the corresponding 'impl' functions and rendering every frame of my renderer to an fbo that goes to an ImGui::Image.
My new idea is that I want ImGui to render using just OpenGL and that switching API's only changes what I pass to the ImGui::Image as ImTextureID. So basically I want to use imgui_impl_opengl3 but be able to pass a DX ShaderResourceView* to an ImGui::Image. I have read the FAQ but I'm not quite sure I understood everything correctly. Would this require a custom RenderDrawData implementation? or a completely custom impl cpp file that handles both API's?

**Comment by ocornut** [comment]
It's hard to understand why you would wander into mixing DX and GL this way, but yeah, presently you'll need a custom RenderDrawData implementation. You may copy one of the back-end and modify it.

However it is true that for #2697, #301 we may end up exposing a function pointer to specifically replace the "SetTexture" component of each renderer, in which case what you are trying to do would be easier.

**Comment by ocornut** [comment]
Closing this as answered.
