### ISSUE TITLE
Function ImGui_ImplGlfwGL3_RenderDrawData doesn't  or no longer exist

### ISSUE THREAD

**Issue by hbina** [ocornut/imgui#2738]
https://github.com/ocornut/imgui/blob/a33cedda142f6e96a9bd2d665290830362671566/imgui.cpp#L641

Closest I could find is `void ImGui_ImplOpenGL3_RenderDrawData(ImDrawData* draw_data)`

Consider renaming it to avoid 5 seconds of confusion.

The referenced file also does not exist.

**Comment by ocornut** [comment]
Thank you, now fixed in master!
