### ISSUE TITLE
Recommended way to store widget-data

### ISSUE THREAD

**Issue by Folling** [ocornut/imgui#2742]
**My Issue/Question:**

A lot of times applications require runtime relevant state, that doesn't necessary belong in the model, but rather to widgets themself, and I'm wondering what best practice would be recommended when dealing with those widget states.

Most Dear ImGui widgets get their frame-based state from the data that is passed to them, i.e. TextFields take a `char*` and then draw that one, ComboBoxes represent a list state, which is obviously stored somewhere in the model, and can hence be designated to be selected as well. But how about widgets, which require information about something that has nothing to do with the model itself? 
Say for example, that I have a textfield with auto-completion, now the user gets to maneuver around the found results with the arrow keys. How exactly should I store the information about which result the user is currently having selected?
I am aware that `ImGui::GetStateStorage` exists, but I'm a bit uncertain if that's the ideal way of treating it, as it seems a bit abstract to me to so elusively separate state from their respective domain, and in fact, make it globally accessible.

I can obviously not just reconstruct the widget every frame since that would destroy the state, so what comes to mind is some form of globally accessible class that provides access to widgets based on ids. That is, it creates them if they didn't exist, and returns them if they did, to persist state between frames.

**Comment by ocornut** [comment]
Ideally we'd have a mechanism to store custom pointers in `ImGuiContext` but that would require extraneous indirection.

I think you are just better off carring that state on your side. You may key it with `ImGuiContext*` if you need to handle multiple simultaneous imgui context (unlikely). 

Most widgets are designed to avoid carrying per-instance state, in many cases we store 1 of the data along with an ID and that data is for the the active widget. Widgets like tab bar or columns are storing more persistent state for non-active widgets however, they store that data in ImGuiContext.

You may instanciate an `ImPool<mytype>` (from `imgui_internal.h`) if you need a storage helper and you want to use your own (or e.g. `std::set` etc.)

**Comment by Folling** [comment]
Thank you very much for the response. 
I totally forgot about Tabbars, since they have pretty much the same usecase of storing which of a list of things is currently active. 
I doubt I need to link it with an ImGuiContext in my usecase, but I'll have a look at the internal ways of ImPool to see which storage container would be most suited.

**Comment by ocornut** [comment]
Closing this now, don't hesitate to post again if needed and I can reopen the thread.
