### ISSUE TITLE
Improved Plot widget for displaying audio data

### ISSUE THREAD

**Issue by soulthreads** [ocornut/imgui#2747]
I've implemented a Plot widget that can show a grid, has custom tooltip support, logarithmic x-axis scaling, is able to draw multiple sources on the same plot, and also supports selection.

All of this was really useful for me when working with audio and ultrasonic data, since I often need to compare signals, show spectrums of the selected part of the signal, and know what value it has at a particular point.

The code is located at https://github.com/soulthreads/imgui-plot  
It is written in C++11 style, but if folks really need it, I can scale it down to C++98 with no problem.

Here are some samples of what it looks like:

Displaying waveform and spectrum:  
![Displaying Waveform and Spectrum](https://linuxoids.net/static/imgui-plot/waveform_and_spectrum.png)

Selection example on a plot with multiple sources:  
![Selection Example](https://linuxoids.net/static/imgui-plot/selection_example.gif)

I hope you will find it useful, and feel free to file issues if you have any problems with it!

**Comment by ocornut** [comment]
Closing this now. Thanks for sharing this!

Nowadays I would assume most people would be using [ImPlot](https://github.com/epezent/implot) to solve this, but yours came first :) It's also been listed in https://github.com/ocornut/imgui/wiki/Useful-Extensions at the time we opened that page.

Pasting a copy of one your picture as I can't seem to find it on your repo:
![96739012-9f772900-13bf-11eb-831b-e4b1ba82e152](https://github.com/ocornut/imgui/assets/8225057/a0cf8ff2-feec-4fe4-9269-c5aa754d74fc)
