### ISSUE TITLE
Discord/Gitter chat server?

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#2748]
As mentioned in some threads, some of you know that I have been reluctant to promote chat forums because I believe support Q&A is more more useful in the long term when it is searchable, persistant and agreggated in a same place.

It's however been often requested to create and promote such chatting place, and I am willing to give it a try and see if we can grow the community differently, perhaps provide help to new users in a more flexible way, and generally exchange about dear imgui related stuff.

I have one request: **I would like some people to want to be jointly administrating that place**. I'll probably perform some casual admin duty as well but I think it is healthier to have a group of people working on it. Anyone?

**Question: Discord or Gitter? Pros and Cons? Other suggestions?**

I don't use them much so I don't know! 

I have created a test Discord server now https://discord.gg/NgJ4SEP (currently empty)
And people have created a Gitter forum earlier https://gitter.im/ocornut/imgui which a few people posted to in the past.

**Comment by NPatch** [comment]
Found this out of curiosity. I use Gitter due to bgfx anyway. But here's a thorough analysis of those choices:
https://github.com/neuecc/UniRx/issues/327

**Comment by ocornut** [comment]
Using Discord for now (I'm myself not very happy with it but it's good to experiment with).
