### ISSUE TITLE
MultiLine Textediting: End Button doesn't work as expected

### ISSUE THREAD

**Issue by DanielGibson** [ocornut/imgui#275]
At least in the SDL2 example on Linux, the cursor will be at the beginning of the next line instead of the end of the current line.

At first sight it seems like a stb_textedit bug, but maybe it's intended like that and imgui doesn't use it correctly, not sure.

Anyway, what I found during debugging:
* We start at `InputTextEx()`, `else if (IsKeyPressedMap(ImGuiKey_End))`
* this calls (simplified): `edit_state.OnKeyPressed(STB_TEXTEDIT_K_LINEEND | k_mask);`
* which will call `stb_textedit_key(this, &StbState, STB_TEXTEDIT_K_LINEEND);`
* which brings us to that function in stb_textedit.h, `case STB_TEXTEDIT_K_LINEEND:` in line 954ff, comments by me:
```
      case STB_TEXTEDIT_K_LINEEND: {
         StbFindState find;
         stb_textedit_clamp(str, state); // irrelevant
         stb_textedit_move_to_first(state); // irrelevant
         stb_textedit_find_charpos(&find, str, state->cursor, state->single_line);
         state->cursor = find.first_char + find.length;
         state->has_preferred_x = 0;
         break;
      }
```
* `stb_textedit_find_charpos()`will call `STB_TEXTEDIT_LAYOUTROW(&r, str, i);` from imgui.cpp, line 6909 to gather some information about each line, including the number of chars
  * the number of chars is indirectly obtained from `InputTextCalcTextSizeW()`, by using its `remaining_chars` argument - which will point to the first char after the `\n` char at the end of the line
  * the number of chars of the line the cursor is currently in will be `find.length` from above, like `(int)(text_remaining - (text + line_start_idx))`
  * `find.first_char` will be the first char of the line the cursor is currently in

So by setting `state->cursor = find.first_char + find.length;` in `stb_textedit_key()` in the case pasted above, the cursor will be set to the position *after* the newline character of the line.  

Example:
* `text` is `asd\nBNM`, the cursor is currently at `s`, `line_start_idx` is 0,  `text_remaining` will point to `B`, `find.first_char` will be 0, and thus the cursor will be before `a`.  
* So `text_remaining - (text + line_start_idx)` == `text_remaining - text` == 4 
   * => `find.length == 4`
* So `state->cursor = find.first_char + find.length;` will put the cursor after `\n`, instead of after `d`.

So it might be a bug in stb_textedit and actually changing  `state->cursor = find.first_char + find.length;` to  `state->cursor = find.first_char + find.length - 1;` to skip the newline seems to work.  
(If that is a valid fix it must also be applied to the `case STB_TEXTEDIT_K_LINEEND | STB_TEXTEDIT_K_SHIFT:` a few lines below)

But I'm not totally sure if `STB_TEXTEDIT_LAYOUTROW()` is even supposed to count newline chars in `StbTexteditRow::num_chars`, so it might be a bug in imgui to do that. (Just subtracting 1 in `STB_TEXTEDIT_LAYOUTROW()` break things badly, though - then when trying to move the text cursor with the arrow keys the whole application stops responding and seems to run in an endless loop. But that issue might well lie within the imgui code and not stb_textedit)

**Comment by ocornut** [comment]
Thanks for the report and the detective work (it's quite a spaghetti part of the code there).
I have looked at it and I am not sure either. The specs of STB_TEXTEDIT_LAYOUTROW aren't very clear and it's lacking example. By the look of code in stb_textedit.h it looks like it must count the \n else lots of the other multi-line functionalities cannot work.

As is, `state->cursor = find.first_char + find.length - 1;` would break single-line edition and pressing the end key on the last line of a text buffer not ending with a \n character (it would erroneously backtrack by 1 character).

Adding those 2 lines after the state->cursor assignment in STB_TEXTEDIT_K_LINEEND
```cpp
         if (!state->single_line && find.length > 0 && STB_TEXTEDIT_GETCHAR(str, state->cursor-1) == STB_TEXTEDIT_NEWLINE)
            state->cursor--;
```
And in STB_TEXTEDIT_K_LINEEND | STB_TEXTEDIT_K_SHIFT:
```cpp
         if (!state->single_line && find.length > 0 && STB_TEXTEDIT_GETCHAR(str, state->cursor-1) == STB_TEXTEDIT_NEWLINE)
            state->cursor = state->select_end = state->cursor - 1;
```
Appears to fix it, but I'm not sure if that's a correct fix.

**Comment by DanielGibson** [comment]
Maybe we could get Sean to look at it?

**Comment by ocornut** [comment]
Yeah I was posting something just now.

**Comment by ocornut** [comment]
Marking this as fixed in ImGui (with the stb_textedit patch)
