### ISSUE TITLE
draw_list render calls  like AddCircle and variants are rendering onto "Debug" window

### ISSUE THREAD

**Issue by tehmanu** [ocornut/imgui#2751]
**Version/Branch of Dear ImGui:**

Version: 1.73 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: VS2019
Operating System: Windows 10

**My Issue/Question:**

draw_list render calls  like AddCircle and variants are rendering onto "Debug" window

Im trying to render some interactible circles. I guet the window draw list and just call the addCircle method, but instead of rendering on the current window, the circles are being rendered on a "Debug" window as the screenshot shows

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/6010272/63648661-4831e600-c733-11e9-9ae0-6b85320725eb.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

```
static bool testRenderwindow = true;
const ImVec2 p = ImGui::GetCursorScreenPos();
ImDrawList* draw_list = ImGui::GetWindowDrawList();
float nodeSize = 20.0f;
if (ImGui::Begin("testRender", &testRenderwindow)) {
            ImGui::Bullet();
            draw_list->AddTriangle(p, ImVec2(p.x + 3.0f, p.y), ImVec2(p.x + 1.5f, p.y + 1.0f), ImColor(1.0f, 0.0f, 0.0f), 20);
            draw_list->AddCircleFilled(ImVec2(p.x + 4.0f, 0.0f), nodeSize, ImColor(1.0f, 0.0f, 0.0f), 20);
            draw_list->AddCircleFilled(ImVec2(p.x + 2.0f,0.0f), nodeSize, ImColor(1.0f, 0.0f, 0.0f), 20);
            draw_list->AddCircleFilled(ImVec2( p.x +4.0f,0.0f), nodeSize, ImColor(1.0f, 0.0f, 0.0f), 20);
            ImGui::End();
}
```

**Comment by ibachar** [comment]
I think it is because you need to call ImGui::End regardless of the return value of Begin

**Comment by ocornut** [comment]
You are calling GetWindowDrawList() before Begin() so getting the draw list of the previous window in the stack.

**Comment by tehmanu** [comment]
oh right, it's working fine now! thanks!!
