### ISSUE TITLE
IsButtonActive returns false while drag and move a button

### ISSUE THREAD

**Issue by tehmanu** [ocornut/imgui#2753]
**Version/Branch of Dear ImGui:**

Version: 1.73 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: VS2019
Operating System: Windows 10

**My Issue/Question:**

IsButtonActive returns false while drag and move a button

Ive created an invisible button and i want to click and drag in the x axis. The problem is that when I click and drag, as soon as I'm not hovering the button, the IsItemActive() returns false making the drag cancel..

**Screenshots/Video**

[Imgur](https://i.imgur.com/MtL5hvq.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

```
for (auto a = 0; a < _animations[x]->transformNodes.size(); a++) {
    // Custom ID
    std::string popupId = std::to_string(_animations[x]->transformNodes[a].first.x)
        + std::to_string(_animations[x]->transformNodes[a].first.y)
        + std::to_string(_animations[x]->transformNodes[a].second);
   
    ImGui::PushID(popupId.c_str());

    // Calculate the position where the node goes
    cursorPos.x += win->Size.x * _animations[x]->transformNodes[a].second / max_time;
    ImGui::SetCursorScreenPos(cursorPos - ImVec2(timeline_radius, timeline_radius));

    ImGui::InvisibleButton("##Node", ImVec2(2 * timeline_radius, 2 * timeline_radius));

    if (ImGui::IsItemActive() && ImGui::GetMouseDragDelta().x > 0){
        _animations[x]->transformNodes[a].second += ImGui::GetIO().MouseDelta.x / win->Size.x * max_time;
        if (_animations[x]->transformNodes[a].second < 0.0f)
            _animations[x]->transformNodes[a].second = 0.0f;
    }
    if (ImGui::IsItemHovered()) {
        ImGui::BeginTooltip();
        // Modifiy the x value of the node
        Animation<float>::displayTransformPopup(_animations[x]->transformNodes[a]); 
        ImGui::EndTooltip();
    }
    draw_list->AddCircleFilled(cursorPos, nodeSize, ImGui::IsItemActive() || ImGui::IsItemHovered() ? active_color : inactive_color);

    if (a != _animations[x]->transformNodes.size())
        ImGui::SameLine();

    ImGui::PopID();
}
```

**Comment by ocornut** [comment]
Hello,

Your code is neither standalone, neither minimal, neither complete, therefore not  verifiable. If you tried to reduce your code toward that you’ll most probably understand the error you made.

**Comment by tehmanu** [comment]
Hello, and sorry for the messy code!

I've detected so far the problem, I was pushing id's with the popId I have in the code, the point is that I was using a member determining the poisition so whenever I moved a node, the Id's were different.

Thank you and sorry for the mess!
