### ISSUE TITLE
Why is there nothing, a dumb library, NOTHING ANYTHING, as with her ???????? Segmentation

### ISSUE THREAD

**Issue by kaizer1** [ocornut/imgui#2755]
I write: 
ImGuiContext* myContext =  ImGui::CreateContext();
 ImGui::SetCurrentContext(myContext);

bool tr = true;
ShowExampleAppConsole(&tr);
   printf(" a NEW 22  %s \n", GetVersion());
  ShowUserGuide();

  Render();
  NewFrame();

EndFrame();
 
 
 
 MISTAKE!!!!!! 
segmentation fault !!!!!!! 
  How to build simple project with this library ?????????? 
   Not a single working example, not a single line of normal documentation

**Comment by ocornut** [comment]
There are 15 working examples in the examples/ folder. If you ask for help please read the guidelines and provide everything that is being asked.
