### ISSUE TITLE
ContextMenu popups are movable

### ISSUE THREAD

**Issue by Folling** [ocornut/imgui#2763]
ImGui Version 1.7.2
GLFW_OPENGL3 Backend
ArchLinux 64 Bit

You're able to freely move around popups.
Here's a GIF to demonstrate this:

![ezgif-5-8ee9def0bb71](https://user-images.githubusercontent.com/23152870/63813300-75e27f00-c92d-11e9-833f-5ca2059cdef1.gif)

I don't think this is intended, as I've never seen it possible in any other software.
The code to reproduce this is:

```cpp
if(ImGui::BeginPopupContextItem("id")) {
    // draw any number of menu items, though minimum 1
}
```

**Comment by ocornut** [comment]
I think there's two things here:

- The fact that the context popups were Dockable when dragged from the top is definitively a bug that I have just fixed.

- The fact that popups are moveable I think it a good thing. It's not standard but I see no reason to prevent it? e.g. Color Picker is a popup we sometimes want to move. 

Let me know.

**Comment by Folling** [comment]
I agree that some Popups need to be movable, but others aren't. This can currently be circumvented by just removing the padding from the ContextMenu (which I believe should be the standard, I don't know of a ContextMenu in an application that has padding). But some popups shouldn't be movable. Take the ContextMenu when right clicking in firefox/chrome or on windows. It's a bit unusual UX wise that you can move that around.

**Comment by ocornut** [comment]
>  It's a bit unusual UX wise that you can move that around.

It's unusual only because most framework don't offer this option, but do you see any problem with it?

**Comment by Folling** [comment]
Apart from the UX I don't no. This is far from a huge priority anyway, but it'd be nice to toggle whether or not the popup is movable 🤔

**Comment by ocornut** [comment]
Well you can always Begin into the popup with the `ImGuiWindowFlags_NoMove` flag. The point is, until we have evidence that this is problematic I don't think there is a reason to alter it.

The first issue was definitively a bad bug, thanks for reporting.
Will be closing this now!
