### ISSUE TITLE
Wrong assert in SliderBehavior

### ISSUE THREAD

**Issue by loicmouton** [ocornut/imgui#2765]
ImGui Version 1.7.2 (and probably more)

I think the assert in the function ImGui::SliderBehavior (file: imgui_widgets.cpp) may be wrong because the wrong variable was used for the test.
It is:
```C++
switch (data_type)
{
/* ... */
 case ImGuiDataType_U32:
        IM_ASSERT(*(const ImU32*)v_min <= IM_U32_MAX/2);
```
Yet, I suspect it should be:
```C++
switch (data_type)
{
/* ... */
 case ImGuiDataType_U32:
        IM_ASSERT(*(const ImU32*)v_max <= IM_U32_MAX/2);
```
(v_min was used instead of v_max)
The same remark can be made for the "ImGuiDataType_U64" case.

Edit: Misclicked and submitted this issue without actually writting anything in it

**Comment by ocornut** [comment]
Why do you think it is wrong? It looks right to me.
For unsigned value we want to test that the smallest value fits within the range so what we are able to handle.

**Comment by loicmouton** [comment]
If we have:
- v_min = IM_U32_MAX/2
- v_max = IM_U32_MAX/2 + 10

It won't be a valid range as "slider bounds are limited to half the natural type range" (in this case, the valid range would be [0, IM_U32_MAX/2]) and v_max exceeds this limit but it will still pass the assert because v_min was tested instead of v_max.

**Comment by ocornut** [comment]
Apologies, you are right! Fixed now! Thanks!
