### ISSUE TITLE
OpenGL3 example broken on OSX

### ISSUE THREAD

**Issue by trevex** [ocornut/imgui#277]
The commit e3b9a618839bda97e5bec814172185f3667e2324 seems to have broken rendering on OS X.
On linux everything works as expected, but OS X throws `GL_INVALID_OPERATION` for the `glDrawElements` on line 91 of the GL3 implementation and therefore nothing is rendered.

I suspect this is due to the OpenGL driver being more strict on OS X, because with a GL core context, client-side arrays for the `indices` parameter of `glDrawElements` and `glDrawElementsInstanced` are explicitly disallowed.

**Comment by ocornut** [comment]
Do you know what would be a good fix? I am not really familiar with OSX nor OpenGL. Maybe the iOS exemple provide a better base?

**Comment by trevex** [comment]
Just did some more testing and the specified commit is not the problem, the problem was introduced by the use of indices. 

The solution would be to load the indices into a buffer as well and bind it to `GL_ELEMENT_ARRAY_BUFFER`. So essentially the procedure of streaming data to the vertex buffers, has to be done for an index buffer as well.

**Comment by trevex** [comment]
Not much time to dispose just now, but I can try to get a pull request done in the next couple of days if necessary.
