### ISSUE TITLE
Keep window title same color [Docking]

### ISSUE THREAD

**Issue by xpenatan** [ocornut/imgui#2771]
Hi.  How can I keep the my window title green when docking others windows?

![tab](https://user-images.githubusercontent.com/6472084/64065182-a56ce200-cbe0-11e9-809b-3f89188eeefd.gif)

Using docking branch (#a4af3cc)

I'm just pushing text style to begin method but it does not work when the docking api dock another window. 

What I want is to have a green "Hello World" text and a white "ImGui Demo" text when its docked.  Is this possible ?

Code:
``` Java
ImGui.PushStyleColor(ImGuiCol.Text, Color.GREEN.toIntBits());

ImGui.Begin("Hello World");

ImGui.PopStyleColor();

//... Other codes

ImGui.End();
```

```
- Please provide the platform/renderer back-ends (imgui_impl_XXX files) you are using along with your operating system and its version.

https://github.com/xpenatan/jDear-imgui/blob/master/extensions/gdx-imgui/src/main/java/com/github/xpenatan/imgui/gdx/ImGuiGdxImpl.java

windows 10

- If you are not calling dear imgui directly from C++, please provide information about your Language and the wrapper/binding you are using.

Made my own lib which calls C++ directly from Java.  the rendering is using libgdx opengl classes.
https://github.com/xpenatan/jDear-imgui

```

Thanks.

**Comment by ocornut** [comment]
This is not possible at the moment.
This is the same as #2539 so I'll close this as a duplicate issue.

**Comment by xpenatan** [comment]
I see,  Thanks !

**Comment by ocornut** [comment]
I just pushed change which specifically fixes this for tab color and text color (as per this issue).

There will be a separate commit to solve #2539/#2700, see last post in #2700 for an explanation why it isn't a trivial change.
