### ISSUE TITLE
HTML support

### ISSUE THREAD

**Issue by blockspacer** [ocornut/imgui#2782]
**First attempt**: I managed to add litehtml support to imgui, but without support for complex CSS. Inspired by https://github.com/ocornut/imgui/issues/973#issuecomment-318058115 see for full code litehtml branch https://github.com/blockspacer/qtimgui-wasm-port/blob/feature/litehtml/container_qt5_imgui.cpp

**Second attempt**:  Now i ask for any help with a lot better HTML/CSS system, with animations e.t.c. https://github.com/blockspacer/skia-opengl-emscripten

I found cobalt.foo project - tiny, but powerful HTML/CSS engine. I removed JS engine from it, so it became small and can run in browser (small browser in browser!). For now that cobalt-for-browser port can create custom HTML nodes and bind C++ callbacks via HTML attrs (like onclick="dosmth").

Just wrap your GUI element into html node and bind cobalt event to your GUI event. See https://github.com/blockspacer/skia-opengl-emscripten/issues/3 for details

**Comment by v71** [comment]
I could be interested,for another project i had to develop a kind of json parser, i think that this parser could replace the couple html/css , if you do not mind to suppor them.
contact me at vp8671@libero.it if you are interested.
