### ISSUE TITLE
Synchronizing ImGui Windows

### ISSUE THREAD

**Issue by sariug** [ocornut/imgui#2783]
**Version/Branch of Dear ImGui:**

Commit : aca6ee1a912fd6bf022cce15a5c25a2eb2c0f6df
Date : Sat May 11 11:25:49 2019 +0200

**Back-end/Renderer/Compiler/OS**

Operating System: UBUNTU 16.04LTS

**My Issue/Question:**

I have a server-client program chain. I want to have a synchronized imgui for both server and clients. Server is the one, regularly updated. Clients are just there to watch, but will never change the imgui interface. 

I am able to multicast data from server to clients. Is there a way to serialize and deserialize the imgui interface ? Or anything closer you may suggest ?

**Comment by ocornut** [comment]
You'll probably want to send vertex data, see imgui-ws and RemoteImGui listed at:
https://github.com/ocornut/imgui/wiki

**Comment by sariug** [comment]
Not exactly but close enough ! Thanks !
