### ISSUE TITLE
Problems with display chinese

### ISSUE THREAD

**Issue by Shirone912** [ocornut/imgui#2784]
Such as the title, i am from taiwan,I have to apologize first,my English level is less than mediocre.
i use the SDL OpenGL2 Version and add Chinese fonts

![image](https://user-images.githubusercontent.com/55393411/64961010-2279a600-d8c7-11e9-98bb-360a1b22fc2d.png)

![image](https://user-images.githubusercontent.com/55393411/64960681-54d6d380-d8c6-11e9-9337-be3e9bab35e1.png)

![image](https://user-images.githubusercontent.com/55393411/64960600-2e189d00-d8c6-11e9-9c51-2ac6be3c9737.png)

**Comment by ocornut** [comment]
Your earlier edit showed that you loaded the font with a wrong path string.
Please read the font readme and comments in the main.cpp files.
