### ISSUE TITLE
Suggestion: Expose LogToBuffer to the user

### ISSUE THREAD

**Issue by Lectem** [ocornut/imgui#2789]
**My Question:**

I find logging ImGui really useful as it can help us automate bug reports a bit by dumping the debug windows text.
However right now the only options are to log to the clipboard, TTY or a file handle.

Internally, ImGui has `LogToBuffer`, is there any reason for not exposing this to the user ?
In my use case, I'd like to use our own filesystem implementation.

Thanks.

Example:
```cpp
// I would like to be able to do
ImGui::LogToBuffer();
// Draw my window
SomeFunctionThatWouldCopyTheLog(GetCurrentContext()->LogBuffer.begin());
ImGui::LogFinish();

```

**Comment by ocornut** [comment]
For now I would suggest just using `LogToBuffer()` as is by including `imgui_internal.h`.

Exposing this publicly would require another api to retrieve the buffer pointers.

**Comment by ocornut** [comment]
Closing this.
