### ISSUE TITLE
Copy & paste using hotkeys produces an extra 'c' or 'v', so as cut, select all.

### ISSUE THREAD

**Issue by AkizukiRyoko** [ocornut/imgui#279]
I'm using the latest imgui repository with glfw as fore-end (from opengl_example) under ubuntu 15.04. While I've found that manipulating an InputText with hotkeys will cause some extra characters to appear. For examples:
* Type `123456`, press Ctrl+X, the InputText is cleared while `123456x` is apparent in cliboard.
* Assuming string `foobar` is in clipboard, press Ctrl+V when focused on a InputText, `vfoobar` will be shown in it.
* Using Ctrl+C producing analogous problems.
* Press Ctrl+A twice will replace original content with `a`.

One possible solution I've found it to ignore any inputted character when modifier keys are pressed in ImGui_ImplGlfw_CharCallback.

**Comment by ocornut** [comment]
I suppose it means that GLFW isn't behaving consistently on all OS. On Windows I don't get a character callback when modifiers are pressed. We should be able to add this test in the callback function if we can get the right modifiers at this point in time. Reading io.KeyCtrl etc. is probably good enough but in theory they may data from the previous frame.

I have another problem then. Eventually we would need to receive those characters callback and I will need to use them for other features such as pressing ALT+letter to open a menu with the keyboard.

**Comment by ocornut** [comment]
OK I have just noticed that GLFW has a function glfwSetCharModsCallback() that does just that. So we'll need to use this and make the filtering in imgui code.

**Comment by ocornut** [comment]
Should be fixed but I couldn't test it on a Mac. @AkizukiRyoko can you confirm it is fixed?

**Comment by ocornut** [comment]
That function was introduced in glfw 3.1 which apparently isn't widespread..

**Comment by ocornut** [comment]
@AkizukiRyoko Which version of GLFW are/were you using?

**Comment by ocornut** [comment]
I have fixed a workaround but please let me know which version of GLFW you had the issue with.!

**Comment by AkizukiRyoko** [comment]
It appears that the problem has gone on my platform (glfw 3.0.4). Thank you.

**Comment by borg** [comment]
Using this [openFrameworks](https://github.com/jvcleave/ofxImGui/issues/43) implementation on OSX still getting c and v instead of copy paste. Not sure it's a mismatch between GLFW implementation of cmd ([GLFW_KEY_LEFT_SUPER](http://www.glfw.org/docs/latest/group__keys.html#gafb1207c91997fc295afd1835fbc5641a
)) and oF or ImGui, but extending the previous fix to include check for is_super_down seems to solve it.
 
glfwGetVersionString 3.1.0 Cocoa NSGL chdir menubar retina
imgui.cpp 7730

'''
            if (!(is_ctrl_down && !is_alt_down) && !is_super_down && is_editable)
            {
                for (int n = 0; n < IM_ARRAYSIZE(g.IO.InputCharacters) && g.IO.InputCharacters[n]; n++)
                    if (unsigned int c = (unsigned int)g.IO.InputCharacters[n])
                    {
                        // Insert character if they pass filtering
                        if (!InputTextFilterCharacter(&c, flags, callback, user_data))
                            continue;
                        edit_state.OnKeyPressed((int)c);
                    }
            }
'''

**Comment by ocornut** [comment]
I believe this should be fixed at the level of either GLFW or ofxImGui, you can perfectly filter the characters using the same condition.

Not knowing if certain IME can emit characters using the Super key isn't safe to filter it for everyone, but if you filter it yourself it may be ok.
