### ISSUE TITLE
glfw events are not handled, if polling and rendering are done on separate threads. 

### ISSUE THREAD

**Issue by fishingGrapes** [ocornut/imgui#2792]
I created a glfw Window on the Main thread and then started a separate thread for rendering and set my glfw context as current in this render thread. So events are polled using glfwPollEvents on the main thread while rendering is done on the render thread and everything works fine. However I create Dear Imgui context in the render thread, and it can't act on the Glfw events being polled on the main thread. How can I overcome this?

**Comment by ocornut** [comment]
Sounds like this is a GLFW question, not a dear imgui question..

**Comment by fishingGrapes** [comment]
Okay! Please close this issue then :relaxed:
