### ISSUE TITLE
Customizing BeginChildEx (title)

### ISSUE THREAD

**Issue by numero69** [ocornut/imgui#2794]
**Version/Branch of Dear ImGui:**

Version: 1.69
Branch: Master I believe

**My Issue/Question:**

 Hello, this is only a question, related to style and widgets. I am using the default ImGui widgets, but I wanted to customize my BeginChildEx function, to draw the title of it in a FilledRect.

For example like when you do this:
`ImGui::BeginChild("Hi");
{
ImGui::Separator();`

But obviously, this is not a really good way of doing it after every single Child. 
Also, I wanted to say I am a total beginner in drawing, positioning and stuff, and I tried my best to customize my BeginChildEx

`	RenderText(GetCursorPos(), name);
	ImU32 title_bar_col = GetColorU32(ImGuiCol_TitleBgActive);
	RenderFrame(size, ImVec2(500,20), title_bar_col, true, 0.0f);`

This is what I tried, it did not work of course.

**Screenshots/Video**
Unfortunately, my code did not draw anything on the screen, so I think screenshots would not help.

**Comment by ocornut** [comment]
Hello,
You can use the ImDrawList api to draw content and you shouldn't need to modify `BeginChildEx`, just draw the content you want after calling BeginChild. 
Consider asking on the Discord channel for help about drawing shapes. https://discordapp.com/invite/NgJ4SEP
