### ISSUE TITLE
Virtual keyboard inputting

### ISSUE THREAD

**Issue by sariug** [ocornut/imgui#2796]
**Version/Branch of Dear ImGui:**

Version: 1.73
Branch: master _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

**My Issue/Question:**

I am trying to create a virtual keyboard. (I unfortunately have to do this for my application)

![vrkey](https://user-images.githubusercontent.com/14132181/65375045-37708380-dc91-11e9-9ef6-2e7241ac523d.png)

I read through the issues before and saw two encounters. When I use focus here and and related functions, I get close enough for many cases. However, for this, I could not find a solution. 
Input float 3.. How may I explore through the different floats in this ? 

![inputfloat3](https://user-images.githubusercontent.com/14132181/65375054-6981e580-dc91-11e9-8f86-8b0d97d77124.png)

    ImGui::Text("Box");
    {
        ImGui::InputFloat3("Min", box_min);
        ImGui::InputFloat3("Max", box_max);
    }

(Sorry if its not the best explanation.)
Thanks !

**Comment by ocornut** [comment]
I don't understand your question/issue.

**Comment by sariug** [comment]
I want to the keyboard focus on lets say the second text input in inputfloat3. 

In the others we were actually modifying the const char* so it was easy. but inputfloat3 works as
`ImGui::InputFloat3("Max", box_max);` . How can I do keyboard focus just on the second text input ?

**Comment by ocornut** [comment]
You can emit a Tab character, or programmatically use the `SetKeyboardFocusHere()` api.

**Comment by sariug** [comment]
Thank you very much.
