### ISSUE TITLE
Paypal link shows French for US-EN locale

### ISSUE THREAD

**Issue by JamesBoer** [ocornut/imgui#2799]
Hi Omar,

The PayPal link seems to always display French, even if one is in a EN-US locale like me (although it does still show $USD).  If it does that for everyone, it may end up hurting your chances for donations.  Just wanted to let you know.

Incidentally, I'd also like to mention my admiration for this project of yours.  I finally bit the bullet and integrated it into my own game engine, and it's simply magnificent.  My first project is an in-game graphical profiler, but it's going to be very useful for lots of other debugging / dev tools.

**Comment by ocornut** [comment]
Thank you for the heads up @JamesBoer, I think I have fixed it now.
PayPal button editor was a little confusing, it allows you to select a "Country" but from what I understand know this is only affecting the Language of the button and is unrelated to my own country. It's also a little bizarre it's not using your own language if you are logged in.. anyway, should be fixed now. Thanks!
