### ISSUE TITLE
stb_truetype 1.06 assertion

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#280]
@ocornut I'm sorry for the delayed answer to your questions in #133 but I've been on travel with limited internet access.

I think it's better to split this off the #133 discussion regarding assertions I've been hitting during latest update of imgui, as I don't think it's a great idea answering to closed issues :see_no_evil: 

I get an assertion in stb_truetype 1.06 on latest IMGUI master featuring the updated stb_truetype 1.06 asserts when adding font awesome.

<img width="224" alt="stb_truetype_assertion_1" src="https://cloud.githubusercontent.com/assets/5406873/8796378/a8274a86-2f94-11e5-953b-aa7a751f7f05.png">
![stb_truetype_assertion_2](https://cloud.githubusercontent.com/assets/5406873/8796405/ddf3ffce-2f94-11e5-9020-f553279119ab.jpg)
![stb_truetype_assertion_9](https://cloud.githubusercontent.com/assets/5406873/8796406/de15bd80-2f94-11e5-992a-f939c5d29a0f.jpg)

I have been able to recreate a small repro case:
- Tested on the OpenGL Sample from today's master (60dce8b)
- Needs the binarized/compressed font awesome
- The assert is hit consistently when stb_truetype == 1.06 and it's not hit when stb_truetype == 1.05

I've created a small repro in a branch (OpenGL sample, not OpenGL3)
https://github.com/Pagghiu/imgui/tree/bug-stb-truetype

Regarding your question in #133 
> On updating to indexed rendering - did you run into any issue or confusing thing that you think could have been easier

It literally took me 10 minutes to update everything on multiple platforms. I'm lucky as I'm using a plain OpenGL backend, so updating was actually a copy/paste of the Rendering function in the OpenGL sample with the addition of small code changes to handle High-DPI displays.
I also have a function that "clones" the entire ImDrawData to let another thread do the rendering job, and it was just as easy to update. I need that to correctly handle rendering/vsync on OSX (runs on a special OS thread) and to avoid multithreading issues that's my only option, but this is probably a topic for another github issue someday :smile:

**Comment by ocornut** [comment]
I can repro but I suppose we'll need to make a repro for stb_truetype,h

**Comment by ocornut** [comment]
Should be fixed now.

**Comment by Pagghiu** [comment]
Yes, everything works correctly now! :+1:
