### ISSUE TITLE
SDL backend does not work with SDL_VIDEODRIVER=wayland

### ISSUE THREAD

**Issue by NeroBurner** [ocornut/imgui#2800]
**Version/Branch of Dear ImGui:**

Version: 1.73 WIP
Branch: example_add_glad_files (master + glad OpenGL 3.3 Core)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp (as well as opengl2, and vulkan)
OpenGL backends tested with gl3w and glad loaders
Compiler:  g++ (GCC) 9.1.0 as well as clang version 8.0.1 
Operating System: Arch Linux

**My Issue:**
when starting an example_sdl_XXX with the `SDL_VIDEODRIVER=wayland` environment variable on wayland the window loads fine, but the elements can't be interacted with

**Screenshots/Video**

first run with `./example_sdl_vulkan` shows the xwayland symbol in the title-bar (top left corner). And it it fully functionable
![Screenshot_20190923_233025](https://user-images.githubusercontent.com/9076163/65464468-23c44900-de5a-11e9-8a6f-bafe12758b1a.png)

second run with `
SDL_VIDEODRIVER=wayland ./example_sdl_vulkan` shows wayland symbol, but is not actionable
![Screenshot_20190923_232937](https://user-images.githubusercontent.com/9076163/65464439-1018e280-de5a-11e9-9f15-a7e5238a3547.png)

**Standalone, minimal, complete and verifiable example:** 
- On wayland compile example_sdl_(opengl3, opengl2 or vulkan)
- let example run with `SDL_VIDEODRIVER=wayland` environment variable `SDL_VIDEODRIVER=wayland ./example_sdl_opengl3`
- see that the UI cannot be interacted with

**Comment by ocornut** [comment]
Could you look into it to try to understand the issue? I am probably never going to look into it myself.

**Comment by NeroBurner** [comment]
found the issue: `SDL_GetGlobalMouseState` does not work with the wayland backend. Most probably a security measure for programs to not grab everything the user does
https://wiki.libsdl.org/SDL_GetGlobalMouseState

using SDL_GetMouseState https://wiki.libsdl.org/SDL_GetMouseState works

I'll send a PR

**Comment by ocornut** [comment]
Thanks! Will also aim to rework some of that logic (perhaps for #2696) so may change later.
You may just add an additional `defined(xxx)` test in that block in the meanwhile!

**Comment by ocornut** [comment]
Merged #2802, thank you @NeroBurner !
