### ISSUE TITLE
Error instanciating ImVector::find() functions for compiling cimgui

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#2801]
When compiling cimgui with 1.73 it seems that ImVector operator== needs to be defined

```[ 16%] Building CXX object CMakeFiles/cimgui.dir/cimgui.cpp.obj
In file included from C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4:0:
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h: In instantiation of 'T* ImVector<T>::find(const T&) [with T = Im
DrawVert]':
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4408:24:   required from here
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h:1276:147: error: no match for 'operator==' (operand types are 'Im
DrawVert' and 'const ImDrawVert')
     inline T*           find(const T& v)                    { T* data = Data;  const T* data_end = Data + Size; while (data
< data_end) if (*data == v) break; else ++data; return data; }

                ~~~~~~^~~~
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h: In instantiation of 'T* ImVector<T>::find(const T&) [with T = Im
FontGlyph]':
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4412:24:   required from here
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h:1276:147: error: no match for 'operator==' (operand types are 'Im
FontGlyph' and 'const ImFontGlyph')
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h: In instantiation of 'T* ImVector<T>::find(const T&) [with T = Im
GuiTextFilter::ImGuiTextRange]':
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4416:24:   required from here
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h:1276:147: error: no match for 'operator==' (operand types are 'Im
GuiTextFilter::ImGuiTextRange' and 'const ImGuiTextFilter::ImGuiTextRange')
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h: In instantiation of 'T* ImVector<T>::find(const T&) [with T = Im
GuiStorage::ImGuiStoragePair]':
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4420:24:   required from here
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h:1276:147: error: no match for 'operator==' (operand types are 'Im
GuiStorage::ImGuiStoragePair' and 'const ImGuiStorage::ImGuiStoragePair')
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h: In instantiation of 'T* ImVector<T>::find(const T&) [with T = Im
DrawChannel]':
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4424:24:   required from here```

**Comment by ocornut** [comment]
Which compiler are you using?
I've been testing with VS 2010, 2015, Clang, GCC and it looked like those operators would only be needed when actually instanciating the type.

**Comment by sonoro1234** [comment]
Yes, but they are effectively used when compiling cimgui which instantiates all ImVector templates

**Comment by ocornut** [comment]
It looks like it's a `const` thing, because the `contains()` method has been doing the same thing forever already..

What happens if you replace the non-const `find()` method with:
```
inline T*           find(const T& v)                    { const T* data = Data; const T* data_end = Data + Size; while (data < data_end) if (*data == v) break; else ++data; return (T*)data; }
```
?

**Comment by sonoro1234** [comment]
```
[ 16%] Building CXX object CMakeFiles/cimgui.dir/cimgui.cpp.obj
In file included from C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4:0:
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h: In instantiation of 'T* ImVector<T>::find(const T&) [with T = Im
DrawVert]':
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4408:24:   required from here
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h:1277:149: error: no match for 'operator==' (operand types are 'co
nst ImDrawVert' and 'const ImDrawVert')
  inline T*           find(const T& v)                    { const T* data = Data; const T* data_end = Data + Size; while (dat
a < data_end) if (*data == v) break; else ++data; return (T*)data; }

                  ~~~~~~^~~~
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h: In instantiation of 'T* ImVector<T>::find(const T&) [with T = Im
FontGlyph]':
C:\luaGL\gitsources\anima\LuaJIT-ImGui\cimgui\cimgui.cpp:4412:24:   required from here
C:/luaGL/gitsources/anima/LuaJIT-ImGui/cimgui/imgui/imgui.h:1277:149: error: no match for 'operator==' (operand types are 'co
```

**Comment by ocornut** [comment]
I wonder if it is an artefact of the fact that the `find_erase()` `find_erase_unsorted()` are calling `find()` so it is trying to complice that function. 
What if you comment out `find_erase` and `find_erase_unsorted` ?

**Comment by sonoro1234** [comment]
does not solve issue-

Issue happens when compiling cimgui.cpp

```
CIMGUI_API ImDrawVert* ImVector_ImDrawVert_find(ImVector_ImDrawVert* self,const ImDrawVert v)
{
    return self->find(v);
}
```

**Comment by ocornut** [comment]
I see.. my suggestion would be that you don't emit those functions nor expose them in the C wrapper, and that would solve your problem.

To be honest I don't expect people to be using ImVector at all from cimgui, do you?

**Comment by ocornut** [comment]
(PS: I am going to make myself some batch files to run cimgui builder more periodically in other to catch those issues ahead!)

**Comment by sonoro1234** [comment]
> To be honest I don't expect people to be using ImVector at all from cimgui, do you?

I think some people could be using them

**Comment by ocornut** [comment]
Well then good luck finding a solution :D
I honestly don't know how to approach that.. I think it's not really needed to support that tbh, that class is there as a support class for other things but expecting user to use their own containers.

Maybe you could blacklist those functions in your builder?

**Comment by sonoro1234** [comment]
> I honestly don't know how to approach that.. I think it's not really needed to support that tbh, that class is there as a support class for other things but expecting user to use their own containers.

The first approach would be defining operator== for ImVector




> Maybe you could blacklist those functions in your builder?

I must decide if generating ImVector is necessary before

**Comment by sonoro1234** [comment]
https://github.com/mellinoe/mellinoe.github.io/search?q=ImVector&unscoped_q=ImVector

**Comment by ocornut** [comment]
> The first approach would be defining operator== for ImVector

The issue is `operator==` is missing on the `T` type, not ImVector.
This is meant as a helper function but doesn't necessarily makes sense for every `T` type.

**Comment by sonoro1234** [comment]
Ahh, yes it should be defined for ImDrawVert

**Comment by sonoro1234** [comment]
Just dropped ImVector functions support in cimgui 1.73
