### ISSUE TITLE
opengl3+glfw+glad it is error

### ISSUE THREAD

**Issue by bizehao** [ocornut/imgui#2806]
I am Chinese，Maybe my English is a little bad.  i am sorry
I've been tested.  
（
     target_link_libraries(ImguiTest PRIVATE gl3w)
     #target_link_libraries(ImguiTest PRIVATE GLEW::GLEW)
     #target_link_libraries(ImguiTest PRIVATE glad)
）

opengl3+glfw+gl3w and opengl3+glfw+glew are Perfect operation，
but opengl3+glfw+glad it is error, and it is show "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"  and I don't understand
I debug it , it  may be glBindSampler() , I Uncertain

**Comment by BrutPitt** [comment]
Hi, @bizehao.
You should be a little more specific... so it's hard to help you...

Anyway...
Usually this happens (with glad) when you call a function not present in the declared context profile: 
e.g. if you declare a 3.0 GL/GLFW context and then you call a glBindSampler (it belong to OpenGL 3.2) you call a function whose "address / pointer" is not loaded (valid).

In this case, it is sufficient to change the GLFW context initialization from:
``` cpp
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
```
to 
``` cpp
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
```

**Comment by bizehao** [comment]
thank you 
I'll try your solution later.

I was going to build a cross-platform system, but there will be a lack of DLL running on Win10. So for the time being, I use directx12 on Windows and the combination of OpenGL + glfw + glew on linux. Thank you very much.

**Comment by bizehao** [comment]
thank you 
I'll try your solution later.
I was going to build a cross-platform system, but there will be a lack of DLL running on Win10. So for the time being, I use directx12 on Windows and the combination of OpenGL + glfw + glew on linux. Thank you very much.

**Comment by bizehao** [comment]
@BrutPitt   Change the version of the statement by using your method glad. it is success, Thank you.
