### ISSUE TITLE
Tab Item gets mixed up with nameless widget when the window is docked

### ISSUE THREAD

**Issue by Husenap** [ocornut/imgui#2807]
Branch: docking
Commit: 3233d85d
Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC

Hello!

I noticed multiple things that are behaving weirdly when having a widget without a name.

I would also like to know if it is considered "wrong" or "bad practice" to have a widget without a name, according to imgui?

* The window gets undocked if you drag the widget
* The TabItem seems to think it is the widget
* If you click the widget the TabItem lights up, and vice versa
* If you click and drag the TabItem, the widget will think it's being dragged.

```cpp
static float f1 = 0.f;
ImGui::Begin("working_example");
ImGui::DragFloat("drag me", &f1);
ImGui::End();
static float f2 = 0.f;
ImGui::Begin("broken_example");
ImGui::DragFloat("", &f2);
ImGui::End();
```

![](https://i.imgur.com/ZUC6xIr.gif)

**Comment by ocornut** [comment]
I expect to make a change to tab/dockable window id, but essentially you are having an id conflict with the window id itself and an empty label without id at the root of a window was always illegal.

Please read the FAQ about id, label and id stick.

**Comment by Husenap** [comment]
It was just me using the ID wrong, it was easily fixed by adding `##ID` without any text, I don't know why I never thought of that at the time :)
