### ISSUE TITLE
SetWindowSize not work

### ISSUE THREAD

**Issue by Cesar1986BR** [ocornut/imgui#2808]
I new in Imgui, so i use the source to made my custom menu using dx11.
I get problem here that, even if i define a size width and height for the  window not work.

sorry my bad english.

```
    // Our state
    bool show_demo_window = true;
    bool show_another_window = false;
    ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);

     float ImGuiWidth = 100.f;
     float ImGuiHight = 100.f;
	 
	 float ImGuiWidth = 100.f;
     float ImGuiHight = 100.f;
	 // 1. Show the big demo window (Most of the sample code is in ImGui::ShowDemoWindow()! You can browse its code to learn more about Dear ImGui!).
        if (show_demo_window)
            ImGui::ShowDemoWindow(&show_demo_window);

        // 2. Show a simple window that we create ourselves. We use a Begin/End pair to created a named window.
        {
            static float f = 0.0f;
            static int counter = 0;

            auto& style = ImGui::GetStyle();
            bool placeholder_true = true;

			// not work =/, kepp the  defult size windows
            ImGui::SetWindowSize(ImVec2((float)ImGuiWidth, (float)ImGuiHight));


            ImGui::Begin("Hello, world!",0, ImGuiWindowFlags_NoResize);                          // Create a window called "Hello, world!" and append into it.

            ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
            ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
            ImGui::Checkbox("Another Window", &show_another_window);
		}
```

**Comment by BrutPitt** [comment]
Hi @Cesar1986BR 

if you read prototype in `ImGui.h`:
``` cpp
    IMGUI_API void          SetWindowSize(const ImVec2& size, ImGuiCond cond = 0);                      
// (not recommended) set current window size - call within Begin()/End(). set to ImVec2(0,0) to force an auto-fit. prefer using SetNextWindowSize(), as this may incur tearing and minor side-effects.
```
In particular it say: **call within Begin()/End()**
Anyway use `SetNextWindowSize()`

**Comment by Cesar1986BR** [comment]
@BrutPitt thx

**Comment by ocornut** [comment]
Closing this as solved. Thank you Michele for the help!

**Comment by CallumCVM** [comment]
I know this is old and closed, but I fixed this in what I think is an easier way (this still seems to be a problem if running inside an application frame (Qt for example).

In ImGui_ImplWin32_UpdateMousePos I added the following code at the end :
`    float dpiScale = ImGui_ImplWin32_GetDpiScaleForHwnd(bd->hWnd);

    io.MousePos.x /= dpiScale;
    io.MousePos.y /= dpiScale;
`
And then in ImGui_ImplWin32_NewFrame change:
`io.DisplaySize = ImVec2((float)(rect.right - rect.left), (float)(rect.bottom - rect.top));`

To:
`float dpiScale = ImGui_ImplWin32_GetDpiScaleForHwnd(bd->hWnd);

    io.DisplaySize = ImVec2((float)(rect.right - rect.left) / dpiScale, (float)(rect.bottom - rect.top) / dpiScale);`

I hope this helps somebody in the future.
