### ISSUE TITLE
Float calculation overflow

### ISSUE THREAD

**Issue by domgho** [ocornut/imgui#2813]
Hi, there is a float overflow in the calculation at https://github.com/ocornut/imgui/blob/f0f5301612dbaa2caeede3091df6aee1c872dbdf/imgui.cpp#L5722
`window->InnerRect` on startup is `Min(FLT_MAX,FLT_MAX), Max(-FLT_MAX,-FLT_MAX)` which causes an overflow when calculating `window->InnerRect->GetSize()`.

I accidently found this by setting flush-to-zero and denormals-are-zero for faster float calculations and testing the flags like so:
```c++
#include <xmmintrin.h>
_mm_getcsr();
```
I then noticed that [bit 3](http://softpixel.com/~cwright/programming/simd/sse.php) got set after calling `ImGui::NewFrame()` which also happens in the shipped demos.

Dear ImGui 1.73

**Comment by ocornut** [comment]
Hello @domgho,

Thanks for your post.
Can you explain how is it a problem?

While I could set `InnerRect` to an empty rectangle, I can't rule out this is happening elsewhere so I'd rather tackle the problem fully if there is actually a problem to tackle.

If you add `InnerRect = ImRect(0.0f, 0.0f, 0.0f, 0.0f);` in `ImGuiWindow()` constructor do you get any other overflow?

**Comment by domgho** [comment]
Thanks for your reply. While this may not crash the program since `OM` (overflow mask at bit 10) is usually set to 1 it is incorrect math and possibly undefined behaviour so it should best be avoided:

> OM _[and others]_ are masks that tell the processor to ignore the exceptions that happen, if they do. This keeps the program from having to deal with problems, but might cause invalid results.

Yes this is the only place where this is happening for my game. Constructing `InnerRect` to zero as suggested fixes it and I have not seen any other issues caused by that.

**Comment by ocornut** [comment]
Thank you!
I've fixed it now as you have stated this is the only occurrence.
However note that the result of that calculation on the `avail_size_from_last_frame = ` line was not used as `use_current_size_for_scrollbar_*` fields are always true for a new window, so I see it as a non-issue.
