### ISSUE TITLE
Scaling issues with high DPI/retina display on Mac

### ISSUE THREAD

**Issue by DiligentGraphics** [ocornut/imgui#2816]
Hello!

I am having some issues with retina display scaling on MacOS. I am trying to reuse MacOS implementation from `imgui_impl_osx.mm` and every frame call `ImGui_ImplOSX_NewFrame`. The function properly determines dpi (2) and sets it in `io.DisplayFramebufferScale`. However, the renderer still clips the image:

![image](https://user-images.githubusercontent.com/15135271/65852111-0c79d580-e30a-11e9-8c87-b3db3056a45d.png)

Mouse events are also not handled properly as scaling is not applied to coordinates.

Manually scaling display size and mouse input in `imgui_impl_osx.mm` fixes the problem:

```cpp
ImGuiIO& io = ImGui::GetIO();
const float dpi = [view.window backingScaleFactor];
io.DisplaySize = ImVec2((float)view.bounds.size.width*2, (float)view.bounds.size.height*2); 
io.DisplayFramebufferScale = ImVec2(dpi, dpi);
```

```cpp
if (event.type == NSEventTypeMouseMoved || event.type == NSEventTypeLeftMouseDragged) 
{
   NSPoint mousePoint = event.locationInWindow;
   mousePoint = [view convertPoint:mousePoint fromView:nil];
   mousePoint = NSMakePoint(mousePoint.x, view.bounds.size.height - mousePoint.y);
   io.MousePos = ImVec2(mousePoint.x * 2, mousePoint.y * 2);
}
```

So it appears like `io.DisplayFramebufferScale` has no effect. Am I missing something?

Dear Imgui version: 1.73

**Comment by ocornut** [comment]
`io.DisplayFramebufferScale` should be copied to `ImDrawData::FramebufferScale` and then the renderer code uses it:

Assuming you are using `imgui_impl_vulkan.cpp` (that is only half suggested by your window title but not explicit in the issue description), the code does:

```
ImVec2 clip_scale = draw_data->FramebufferScale; // (1,1) unless using retina display which are often (2,2)
[...]
// Project scissor/clipping rectangles into framebuffer space
ImVec4 clip_rect;
clip_rect.x = (pcmd->ClipRect.x - clip_off.x) * clip_scale.x;
clip_rect.y = (pcmd->ClipRect.y - clip_off.y) * clip_scale.y;
clip_rect.z = (pcmd->ClipRect.z - clip_off.x) * clip_scale.x;
clip_rect.w = (pcmd->ClipRect.w - clip_off.y) * clip_scale.y;
```

So if that doesn't work for you with `impl_impl_vulkan.cpp` I suggest you dive and debug the code to try to understand what's going on.

**Comment by DiligentGraphics** [comment]
Thanks for the pointer though this doesn't work unfortunately. All render coordinates seem to be at native resolution, so scaling scissor rects breaks everything. Will keep digging

![image](https://user-images.githubusercontent.com/15135271/65888139-e1b46f00-e353-11e9-9919-cfa4627869fd.png)

What about mouse coordinates? Why do I have to scale them manually too?

**Comment by rokups** [comment]
This does not happen with standard imgui demos. If you shared your code i could try and debug it.

**Comment by DiligentGraphics** [comment]
@rokups It does not indeed. Looks like in my setup all rendering happens at native resolution rather than being scaled by bakingScaleFactor. I've never fully understood how this whole DPI scaling works. Anyway, I figured out workarounds to make things work, so closing the issue.
