### ISSUE TITLE
CMake build errors for glfw monitor functions popping up at random.

### ISSUE THREAD

**Issue by coderguy1777** [ocornut/imgui#2821]
**Version/Branch of Dear ImGui:**

Version: 1.62
Branch: master & docking, reason is ive encountered this error in both branches.

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp (using custom engine, making one at least with imgui involved.)
Compiler: C++14 (if the question is related to building or platform specific features)_
Operating System: Linux Mint 19.2 Cinnamon

**My Issue/Question:**

When using ImGui with GLFW, and having it in a custom folder on linux and using cmake to compile my game engine, in imgui_impl_glfw.cpp has undefined functions for glfw's built in monitor features, which are shown at the bottom of the terminal output in the screenshot shown below. The fix for this on linux at least, is fixing the include settings for imgui_impl_glfw.cpp by replacing line 43 with: `#include <libraries/imgui/examples/libs/glfw/include/GLFW/glfw3.h>` which for some reason fixes the problems. Note the first directory, libraries, is my own directory, so replacing that first directory with any directory of your choice for where you put imgui should give the same error.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/33611224/66010980-38729380-e48f-11e9-862c-c816a04c3b63.png)
```

**Comment by ocornut** [comment]
(1) those functions are not used in `master` branch so I don't understand why you claim it happens in `master`, but this is a clue that you may be compiling the wrong sets of file somehow.

(2) those functions are available from GLFW 3.3 and the code in imgui_impl_glfw.cpp explicitely only uses them if your version of GLFW is 3.3.

My guess is the following
- Either you have an intermediate custom-compiled version of GLFW between 3.2 and 3.3 that state it is 3.3 but doesn't have glfwGetMonitorXXXX in which case please update GLFW to proper 3.3. This is likely!
- Either there's something else fishy in your code, or other modifications you have omitted.
You mention cmake and use a custom `build.sh` script, neither of those are part of the dear imgui package but we are helping you with incomplete information here.

**Comment by corentin-plouet** [comment]
I think it's an issue with @coderguy1777's CMake file. It looks like it's picking the system Glfw header to build the file that's vendored with Imgui.

@coderguy1777 instead of changing the #include, which is clearly the wrong approach, you should be able to use include_directories / target_include_directories to set the proper directory for the header.

**Comment by ocornut** [comment]
Thank you Corentin.
I'll close this as an issue on @coderguy1777's side.
