### ISSUE TITLE
Unresponsive mouse events 

### ISSUE THREAD

**Issue by Spinkoo** [ocornut/imgui#2824]
So basically am making a game engine using opengl & after setting imgui layer with glfw window i called the ImGui::showdemowindow all looking good, and i used an event system that i set for  the glfw ( setting the glfw callbacks ) so when i try the mouse event i can hover over the demowindow buttons & options but once i click nothing happen ( the callback of presseing is called & the GetIO().MouseDown[button] is set to true & then to  false in release but the buttons of the imgui window doesnt seem to respond )

It seems like the problem is caused by the opengl_imgui initalziation so am gonna leave the init part of the imgui

that's the initalization 

                             
            IMGUI_CHECKVERSION();
		ImGui::CreateContext();

		ImGui::StyleColorsDark();
		ImGuiIO& io = ImGui::GetIO();
		io.BackendFlags |= ImGuiBackendFlags_HasMouseCursors;
		io.BackendFlags |= ImGuiBackendFlags_HasSetMousePos;
	

		io.KeyMap[ImGuiKey_Tab] = GLFW_KEY_TAB;
		io.KeyMap[ImGuiKey_LeftArrow] = GLFW_KEY_LEFT;
		io.KeyMap[ImGuiKey_RightArrow] = GLFW_KEY_RIGHT;
		io.KeyMap[ImGuiKey_UpArrow] = GLFW_KEY_UP;
		io.KeyMap[ImGuiKey_DownArrow] = GLFW_KEY_DOWN;
		io.KeyMap[ImGuiKey_PageUp] = GLFW_KEY_PAGE_UP;
		io.KeyMap[ImGuiKey_PageDown] = GLFW_KEY_PAGE_DOWN;
		io.KeyMap[ImGuiKey_Home] = GLFW_KEY_HOME;
		io.KeyMap[ImGuiKey_End] = GLFW_KEY_END;
		io.KeyMap[ImGuiKey_Insert] = GLFW_KEY_INSERT;
		io.KeyMap[ImGuiKey_Delete] = GLFW_KEY_DELETE;
		io.KeyMap[ImGuiKey_Backspace] = GLFW_KEY_BACKSPACE;
		io.KeyMap[ImGuiKey_Space] = GLFW_KEY_SPACE;
		io.KeyMap[ImGuiKey_Enter] = GLFW_KEY_ENTER;
		io.KeyMap[ImGuiKey_Escape] = GLFW_KEY_ESCAPE;
		io.KeyMap[ImGuiKey_KeyPadEnter] = GLFW_KEY_KP_ENTER;
		io.KeyMap[ImGuiKey_A] = GLFW_KEY_A;
		io.KeyMap[ImGuiKey_C] = GLFW_KEY_C;
		io.KeyMap[ImGuiKey_V] = GLFW_KEY_V;
		io.KeyMap[ImGuiKey_X] = GLFW_KEY_X;
		io.KeyMap[ImGuiKey_Y] = GLFW_KEY_Y;
		io.KeyMap[ImGuiKey_Z] = GLFW_KEY_Z;

 

		ImGui_ImplOpenGL3_Init("#version 410");

and for the update part 

               ImGuiIO& io = ImGui::GetIO();
		App& app = App::Get();
		
		 
             io.DisplaySize=ImVec2((float)app.getWindow().GetWidth(),app.getWindow().GetHeight());
	
		
		ImGui_ImplOpenGL3_NewFrame();

		ImGui::NewFrame();
		ImGui::ShowDemoWindow();
		
		ImGui::Render();

		ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

Note: the keyboard events is totally working fine i tried to tab over the inputs of the test window & it all work fine but for the mouse clicking something is the wrong

**Comment by ocornut** [comment]
(1) **Please fill the issue template as requested. Please edit your issue with the template and I will reopen it.**

(2) You should be using imgui_impl_glfw, why are you not using it?

**Comment by Spinkoo** [comment]
i have set the glfw window myself in a seprate work with all the mouse & keyboard events & their callbacks & i wanted to add  the imgui as a layer on top of it that's why i didnt use the imgui_impl_glfw

**Comment by ocornut** [comment]
That's not a good reason, you can perfectly use `imgui_impl_glfw` along with your own handlers.
