### ISSUE TITLE
I just want a dialog based application 

### ISSUE THREAD

**Issue by introcosmo** [ocornut/imgui#2834]
Version/Branch of Dear ImGui:

Version: dear imgui, v1.73
Branch: master

Screenshots/Video
![image](https://user-images.githubusercontent.com/3878283/66373813-166f9880-e9dc-11e9-9358-f55bb91e4a3e.png)

My Issue/Question:
Hi!
I just want a dialog based application(Hello, world!) without backgroud window(Dear ImGui DirectX11 Example) for drawing.
Is that possible? How should I do?
Thanks!

**Comment by Folling** [comment]
You'll have to be a bit clearer.
A dialog based application? So you want your entire appliciation to just be dialogs? As in the warning dialogs you'd get when something wrong happens?
Or do you just want a big background window that covers the entire screen without small windows that you can drag around?
Or do you want an application that contains of different native windows?

**Comment by introcosmo** [comment]
My problem gets clear by uploaded image with title names of dialogs. I tried to seek the api to conceal the background window. But I found nothing. 
I am grateful if somebody helps.

**Comment by Folling** [comment]
So you basically want something like this:
![image](https://user-images.githubusercontent.com/23152870/66391611-d9040e80-e9cd-11e9-8f2a-3442ad41f4c1.png)
A window that fills the entire screen?

**Comment by corentin-plouet** [comment]
Yes it's definitely possible.
You always have at least one OS window (the one with the green background, in your screenshot). And you always need to have one ImGui window. The trick is to maximize that single ImGui window to fill the OS window, like on the screenshot shown by @Folling.

You can use SetNextWindowPos, SetNextWindowSize calls with appropriate arguments before you Begin the ImGui window.

**Comment by introcosmo** [comment]
> So you basically want something like this:
> ![image](https://user-images.githubusercontent.com/23152870/66391611-d9040e80-e9cd-11e9-8f2a-3442ad41f4c1.png)
> A window that fills the entire screen?

Yes, How do you implement that? Do as corentin-plouet said with SetNextWindowPos, SetNextWindowSize  or someway easier?
Thanks for your reply!

**Comment by Folling** [comment]
If you don't need the menubar you can use `ImGui::DockSpaceOverViewPort` and then dock the window to that dock-id. 
The dockbuilder API is a bit flimsy right now, but you can read about it here:
https://github.com/ocornut/imgui/issues/2109#issuecomment-426204357

**Comment by ocornut** [comment]
```
SetNextWindowPos(ImVec2(0,0))
SetNextWindowSize(ImGui::GetIO().DisplaySize)
Begin(...)
```

**Comment by ocornut** [comment]
Please move this to Discord or elsewhere, thank you.
https://discord.gg/NgJ4SEP
