### ISSUE TITLE
this imgui have % of retained mode anyway

### ISSUE THREAD

**Issue by iperov** [ocornut/imgui#284]
static bool b_show_wnd; - is retained mode :D
1 byte of widget state in user space
other 99% of data in imgui space
why ?

**Comment by emoon** [comment]
On which line is that? I can't find it anywhere in the (latest) codebase

**Comment by iperov** [comment]
just example =\

**Comment by ocornut** [comment]
Because this data typically drives the control flow of your application code. I'm not sure it would make more sense or be more practical to make it opaque.

Any idea in mind?

**Comment by paulsapps** [comment]
Its hard to know what you're talking about without specific examples?

**Comment by iperov** [comment]
omar check plz email about retained mode gui
