### ISSUE TITLE
Selectables with icons is it possible?

### ISSUE THREAD

**Issue by FOLOME** [ocornut/imgui#2841]
I can't find any helper function to do something like this (selectable with icon and name)
![Annotation 2019-10-10 095639](https://user-images.githubusercontent.com/43178999/66554346-bb0cea00-eb44-11e9-8aac-76cc9f15ed83.jpg)

Is it possible?

**Comment by ocornut** [comment]
Hello @FOLOME ,

Please fill the Issue Template when submitting an issue.
To use icon you can merge a font icon into your main font and then declare icons as part of the text.
The icons will be monochrome.
See misc/fonts/README for some details.
