### ISSUE TITLE
Multiple viewport with SDL + Opengl3

### ISSUE THREAD

**Issue by optus23** [ocornut/imgui#2843]
Hi! I'm creating an engine with SDL v2 and OpenGL3 and I would like to ask you a few questions.

First of all I'm a nooby in Opengl so be patient pls :), how can I use multiple viewport inside a window initialized with a SDL context like unity? Because I can not debug the example (example_sdl_opengl3).

On the other hand, there's a way to render in a child window?

Btw congrats for doing ImGui! Super cool library!

![ereerererer](https://user-images.githubusercontent.com/36281630/66613656-7cb80f00-ebc6-11e9-817e-e6c7b764c46c.png)

**Comment by BrutPitt** [comment]
Hi, optus23.
If you mean something like that:
![sshot001](https://user-images.githubusercontent.com/16171743/66623412-d8e15a00-ebeb-11e9-8451-23d465e8ccef.jpg)
with multiple ImGui viewports, or/and also with *dockable* windows, you need to get/downlaod the [**docking**](https://github.com/ocornut/imgui/tree/docking) branch (not *master* branch).
This because is still in development (advanced!) phase, but is very (very!) stable (mostly in Windows).

To use it, need to add some line in your **ImGui** initialization:
```cpp
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;           // Enable Docking
    io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;         // Enable Multi-Viewport / Platform 
```
And in the main loop, after ImGui render cycle:
```cpp
        // Update and Render additional Platform Windows
        // (Platform functions may change the current OpenGL context, so we save/restore it to make it easier to paste this code elsewhere.
        //  For this specific demo app we could also call SDL_GL_MakeCurrent(window, gl_context) directly)
        if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
        {
            SDL_Window* backup_current_window = SDL_GL_GetCurrentWindow();
            SDL_GLContext backup_current_context = SDL_GL_GetCurrentContext();
            ImGui::UpdatePlatformWindows();
            ImGui::RenderPlatformWindowsDefault();
            SDL_GL_MakeCurrent(backup_current_window, backup_current_context);
        }
```
But is all well documented in the examples of [**docking**](https://github.com/ocornut/imgui/tree/docking) branch

**Comment by ocornut** [comment]
@optus23 Before considering multiple viewports, are you able to compile, run and render dear imgui within Unity? That itself is not a trivial thing to do.

**Comment by ocornut** [comment]
(Ignore my previous message, deleted now).

@optus23 Your message is ambiguous, it feels like you are not referring to "multi-viewports" as what it is in dear imgui terminology. Maybe all you want is to render your game visual output within an imgui window. In the later case you need to render your game to a texture and then rendering that texture inside an imgui window using e.g. `ImGui::Image()` or `ImDrawList::AddImage()`. See https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

But please 
1) clarify your question.
2) absolutely fill the issue template and read issues guidelines next time you create an issue. Failing to do so will get you blocked (unfortunately we have too many open issues and I won't accept those not fitting desired standards).

Thank you.

**Comment by optus23** [comment]
The texture was the right answer... My apologies sr.ocornut, was not my intention waste your time.

Thanks for all
