### ISSUE TITLE
ImGui crashes (access violation) when clicking the '+' or '-' button of InputScalar

### ISSUE THREAD

**Issue by Gliath** [ocornut/imgui#2844]
```
Dear ImGui 1.73 WIP (17203)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1923
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sfml
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000041
 NavEnableKeyboard
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x00000007
 HasGamepad
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**ImGui crashes when I click on the + or - button of a InputScalar:**

I want to be able to change some value of an object.
When I tested the + and/or - (on various datatypes), it crashes. 
The gif shows the implementation for my project, but I tested with a minimal code as well and the result is the same. 

**Screenshots/Video**

![Editing a gif](https://user-images.githubusercontent.com/6312386/66639950-35f30500-ec18-11e9-851b-42e2742a0127.gif)

![Crash after clicking the '+' or '-' button](https://user-images.githubusercontent.com/6312386/66640022-5d49d200-ec18-11e9-9497-3d5e162e062d.png)

**Code used (minimized):**
```
ImGui::Begin("Example Bug");
static int8_t testingBugValue = 2;
int8_t bugValue = testingBugValue;
ImGuiInputTextFlags flags = ImGuiInputTextFlags_None;
const char* format = (flags & ImGuiInputTextFlags_CharsHexadecimal) ? "%08X" : "%d";
ImGui::InputScalar("Byte", ImGuiDataType_S8, &bugValue, (void*) 1, (void*) 64, format, flags);
testingBugValue = bugValue;
ImGui::End();
```

**Comment by ocornut** [comment]
If you look at the crash you'll notice it is trying to dereference the `step` `step_fast` pointers to get the value. You are giving it 1 and 64 as pointers so dereferencing that would crash. You should pass pointer to an address hold the values.

Look at imgui_demo.cpp for how to use `InputScalar`, under `Widgets->Data Types` the coments are explaning how it works and why it works this way.

**Comment by ocornut** [comment]
In other words you can use:
```
static int8_t step = 1;
static int8_t step_fast = 64;
ImGui::InputScalar("Byte", ImGuiDataType_S8, &bugValue, &step, &step_fast, format, flags);
```
But I recommend reading the comments to understand why it works this way.

I will now make a change to the function prototype to add `p_` prefix to those arguments to hopefully clarify their use.

**Comment by Gliath** [comment]
Thank you for the clarification.
I didn't think of the possibility of a de-referencing issue.
