### ISSUE TITLE
FAQ, Wiki, simplifying main Readme

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#2848]
Some changes have been made to the main Readme (which appears when landing on the github webpage) and the FAQ. This is a post to notify people, gather some interest and suggestions.

Thanks to @ker0chan for her help on the Readme (lots more feedback that I haven't processed yet) and @ButternCream for his help working on the FAQ.

- Created a [FAQ wiki page](https://github.com/ocornut/imgui/wiki/FAQ) and gathered entries that were scattered in Readme and imgui.cpp into it.
**EDIT* Moved FAQ to https://github.com/ocornut/imgui/blob/master/docs/FAQ.md
**EDIT* Added permanent link: https://www.dearimgui.org/faq 
- Cleaned up the Readme to make it shorter, easier to digest, with more references to Wiki pages and a little less redundancy.
- Created an [Image Loading and Displaying Examples](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples) page to answer a commonly asked question by user.
- Generally lots of small improvements to the Wiki pages.

Onward:
- Hope we can together grow the wiki into an increasingly useful resources. Even with the many improvements made in the past months, information are still lacking and scattered. 
- The info e.g. in misc/fonts/ could also be moved.
- There's lot we could do: e.g. a page giving an overview of Dear ImGui features, with screenshots and minimal api references would be nice.

My main concern:
- Many elements of the FAQ were in imgui.cpp. It made it easy to grep some info from the code, and was tightly tied to your version. Moving the FAQ to the Wiki create a disconnect between user's version and what may be on Wiki, which is not very desirable. Also it requires the internet to read the FAQ. I have left an index in imgui.cpp and some key answers (ID stack) in there. Opinion?
- Github's wiki is not amazing. ~~You can attach picture but you can't upload them via the wiki interface (yet you can upload from Issues).~~ (Fixed 2022). Renaming page loses their history. Changes don't go via PR which has pros and cons.

Suggestion:
- We can move the FAQ outside of the Wiki and back in the repository but instead of being in imgui.cpp it'll be in docs/FAQ.md
So it is still possible to browse online with nice formatting or grep/browse locally so we don't have the version disconnect. It means that changing the FAQ will require a PR, perhaps that's for the best?
I think we could also gatter more information into a same place of the repo (e.g. move misc/fonts/README to a file in docs/), perhaps have one large file under docs/ . There's still room for many Wiki pages but a few keys information may be best hosted on the main repo?

**Comment by ButternCream** [comment]
> We can move the FAQ outside of the Wiki and back in the repository but instead of being in imgui.cpp it'll be in docs/FAQ.md

I personally think this would be more efficient than the wiki. To address your concern about the users version and the FAQ disconnection, I think moving it to the docs folder would eliminate that issue in future releases. Mainly because if someone is looking for a past versions FAQ we could easily link to to a previous commits FAQ. I'm not sure how we could address this for current past versions but its just a thought. Let me know what you think!

Any other ideas are appreciated too.

**Comment by ocornut** [comment]
I have moved the FAQ to the repository:
 https://github.com/ocornut/imgui/blob/master/docs/FAQ.md

And create a permanent shortcut link to it:
 https://www.dearimgui.com/faq
Which is easier to remember and share.

Nice improvements overall, last month we didn't have the FAQ in formatted web form.

I think one of the next step could be to transition the stuff in misc/fonts/README somewhere else. It might be too big for FAQ entry, at that point we are starting to build a documentation?

**Comment by ButternCream** [comment]
I could start working on the fonts README and converting it into a nice markdown like the FAQ. Once I'm finished I could throw it in misc/fonts via PR and you can check over and fix / reorganize things. 

As for building documentation, I've seen lots of projects use readthedocs.io but I've never personally hosted anything there so I'm not sure how it works. Could be an easy way to organize everything into one place and simply link to the "documentation" instead of separate links for separate sections.

**Comment by chadbramwell** [comment]
New here! I've been reading up on fonts and have hit a few broken links (404s) that point at https://github.com/ocornut/imgui/blob/master/misc/fonts/README.txt

I presume any links to misc/fonts/README.txt should point at docs/FONTS.txt?

I was able to fix https://github.com/ocornut/imgui/wiki/Loading-Font-Example (hopefully that's okay!)

**But I'm unable to modify the broken link in https://github.com/ocornut/imgui/issues/2261**

**Comment by ocornut** [comment]
@chadbramwell Thank you for the wiki fix and head up Chad, I have fixed the link in 2261 and also in a few other old issues.

**Comment by ocornut** [comment]
I have revamped the wiki index page today:
https://github.com/ocornut/imgui/wiki

Things are better organized (by topics, not by "format").

Also note a few months ago we launched the https://github.com/ocornut/imgui/wiki/Useful-Widgets page with a Gallery of dear imgui extensions.

**Comment by ocornut** [comment]
Closing this old issue.

Please note that this week I had to disable user-editing of the Wiki. It is because wiki won't have a chance to be indexed, making information discovery poor. I have submitted a suggestion to GitHub to solve this problem: [#133123](https://github.com/orgs/community/discussions/133123). **Please consider upvoting to help.**
