### ISSUE TITLE
glDrawElementsBaseVertex is not available in GL 3.1

### ISSUE THREAD

**Issue by dpilawa** [ocornut/imgui#2852]
**Version/Branch of Dear ImGui:**

Version: 1.72b
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Clang 8.0.0
Operating System: win10

**My Issue/Question:**

This piece in `imgui_impl_opengl3.cpp` is not sufficient to decide on the use of glDrawElementsBaseVertex which is available from GL 3.2 onwards (and not in GL 3.1).

`// Desktop GL has glDrawElementsBaseVertex() which GL ES and WebGL don't have.
#if defined(IMGUI_IMPL_OPENGL_ES2) || defined(IMGUI_IMPL_OPENGL_ES3)
#define IMGUI_IMPL_OPENGL_HAS_DRAW_WITH_BASE_VERTEX     0
#else
#define IMGUI_IMPL_OPENGL_HAS_DRAW_WITH_BASE_VERTEX     1
#endif`

**Comment by ocornut** [comment]
You are correct. We would need a PR that :

- Rename `IMGUI_IMPL_OPENGL_HAS_DRAW_WITH_BASE_VERTEX` to `IMGUI_IMPL_OPENGL_MAY_HAVE_DRAW_WITH_BASE_VERTEX`.

- In `ImGui_ImplOpenGL3_Init()` query the context version number using `glGetIntegerv(GL_MAJOR_VERSION, ...` etc, store in a single value (e.g. g_GlVersion = major * 1000 + minor), make that query outside of the ifdef for good measure.
- Set ImGuiBackendFlags_RendererHasVtxOffset accordingly or not.

- In the rendering function select between both functions depending on the version.

**Comment by ocornut** [comment]
@dpilawa Do you feel like attempting to make this PR? 
Thanks!

**Comment by dpilawa** [comment]
@ocornut Yes, will do.

**Comment by dpilawa** [comment]
@ocornut I will need to find another solution and remove reference to `glDrawElementsBaseVertex` by compiler directives in contexts below 3.2. If I select between both functions in rendering function based on global variable, I still end up with code which won't compile on a pure 3.1 system (`glDrawElementsBaseVertex` is undeclared there and 
`IMGUI_IMPL_OPENGL_MAY_HAVE_DRAW_WITH_BASE_VERTEX` precompiler condition is too weak). 

If you have a quick idea, drop me a line, please.

**Comment by ocornut** [comment]
> I still end up with code which won't compile on a pure 3.1 system 

Which GL loader are you using?

**Comment by dpilawa** [comment]
@ocornut I am using GLAD with compatibility profile.

**Comment by ocornut** [comment]
OK so I guess we could
- introduce optional #define to enforce overally GL version and compile that out
- take advantage of standard #defined emitted in glad to automatically select a default at compile time? Can we find any of those?

**Comment by dpilawa** [comment]
Right, let's use these which GLAD emits: `#define GL_VERSION_3_x 1`. On 3.1 `GL_VERSION_3_2` will not be defined. I will work on PR later this week.

**Comment by ocornut** [comment]
Fixed via #2866
