### ISSUE TITLE
Combo isn't working while window is docked

### ISSUE THREAD

**Issue by VictorSegura99** [ocornut/imgui#2853]
Version: 1.74
Branch: Docking

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Operating System: Windows 10 pro

Hello, first of all, thanks for the amazing library Dear ImGui! 
I am doing a Game Engine and I found myself with an error I don't know how to solve.
When I have a window docked and I try to expand a combo, it doensn't answer and keeps collapsed. If the window isn't docked, everything works as expected.

![ezgif-6-5987952190d1](https://user-images.githubusercontent.com/36154682/67033058-24789400-f115-11e9-96b8-7c2095ec7d06.gif)

```
	if (ImGui::CollapsingHeader("Style")) {
		ImGui::Spacing();
		ImGui::Text("Select the style");
		ImGui::Spacing();
		if (ImGui::Combo("", &App->window->style, "Classic\0Dark\0Light\0"))
		{
			switch (App->window->style)
			{
			case 0: ImGui::StyleColorsClassic(); break;
			case 1: ImGui::StyleColorsDark(); break;
			case 2: ImGui::StyleColorsLight(); break;
			}
		}
		ImGui::Spacing();
	}
```

Thanks again for the library and the help! :)

**Comment by ocornut** [comment]
Your combo is missing a proper ID.
Please read the FAQ.
