### ISSUE TITLE
Draw an image with pixel data

### ISSUE THREAD

**Issue by 2uy** [ocornut/imgui#2855]
Version/Branch of Dear ImGui:

Version: 1.72 
Branch: master

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Operating System: Windows 10

My Issue/Question:

hi omar,
I want to make a tool with Imgui.

1. I have a raw date ( pixel data ), 192*192 that I got from a sensor.
I have to draw images with these data.
I called window api in my old tool.
How should I draw an image with Imgui?

2. How should I draw the scales and letters of the x- and y-axes when I draw a graph?
How do you draw the line?

Thanks

**Comment by ocornut** [comment]
Hello @2uy,

(1) Please read FAQ "Q: How can I display an image? What is ImTextureID, how does it work?"
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md
and linked from that FAQ entry the "Image loading and displaying exemples"
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

(2) You can use the ImDrawList api. See Demo->Examples->Custom Rendering.

**Comment by 2uy** [comment]
> Hello @2uy,
> (1) Please read FAQ "Q: How can I display an image? What is ImTextureID, how does it work?"
> https://github.com/ocornut/imgui/blob/master/docs/FAQ.md
> and linked from that FAQ entry the "Image loading and displaying exemples"
> https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
> (2) You can use the ImDrawList api. See Demo->Examples->Custom Rendering.

Thanks,
one more question.
How to read pixel value of specific coordinate from image? 
For example, the pixel value of the mouse cursor?
