### ISSUE TITLE
Font Vertical Alignment In Headers

### ISSUE THREAD

**Issue by Bodyclock-Games** [ocornut/imgui#2857]
Font Vertical Alignment In Headers

Hi, I wondered if its possible to vertically align an icon font with the label text within a header or title. At the moment the label text is too low or the icon is too high (see screenshot)?

![Headers](https://user-images.githubusercontent.com/49901560/67107787-67963e00-f1cd-11e9-8a13-f26a93b7c831.png)

Current Code
void Environment::Create()
	{
		if (ImGui::Begin(WINDOW_ENVIRONMENT " Environment"))
		{
			if (ImGui::CollapsingHeader(HEADER_TERRAIN " Terrain"))

Thanks for your time and a great piece of software.

Regards

Chris

**Comment by ocornut** [comment]
If your icon font size is smaller than your text font size, add an offest when merging:

e.g.
cfg.GlyphOffset.y += (text_font_size - icon_font_size) * 0.5f

**Comment by Bodyclock-Games** [comment]
Thanks, I'll play around with that but the fonts are the same size. Ideally I'd like the Icon font size to be larger but obviously that compounded the issue.

Sorry about the template completion.

**Comment by Bodyclock-Games** [comment]
That worked perfectly, thanks

**Comment by ocornut** [comment]
I suggest you also try to load both of them separately and in `Style Editor > Fonts` and inspect what the baseline, ascent/descent etc. are. It's possible that we could handle that offset automatically when merging font, maybe your value can confirm it. Could you post them?

**Comment by Bodyclock-Games** [comment]
Sure.
This worked for me using the Google Material Design Icons and the Inter font. I guess the mileage may change depending on the relative font sizes. This is what I'm using:

	const float m_FontSize = 18.0f;
	const float m_IconSize = 24.0f;
	config.GlyphOffset.y -= (m_FontSize - m_IconSize);


//This worked when the font and icon font were both 18.0f
//config.GlyphOffset.y += 6.0f;

![Fixed](https://user-images.githubusercontent.com/49901560/67110057-294f4d80-f1d2-11e9-9f73-69442748db46.png)

Cheers

Chris

**Comment by ocornut** [comment]
Hello,

Could you load both fonts in size 18.0f, NOT MERGED, and report those values you can find in `Style Editor -> Fonts` ?
![image](https://user-images.githubusercontent.com/8225057/67110244-8f3bd500-f1d2-11e9-901d-9cfc86a7183b.png)

Thank you.

**Comment by Bodyclock-Games** [comment]
Sure, is this what you're looking for;

![Demo](https://user-images.githubusercontent.com/49901560/67114753-efd00f80-f1dc-11e9-8266-c98605f9ad08.png)

**Comment by ocornut** [comment]
Thank you
The very first screenshot had both at 18x you said? (Here the icon one is 24)

**Comment by Bodyclock-Games** [comment]
Sorry, my bad.

![Demo](https://user-images.githubusercontent.com/49901560/67115258-16427a80-f1de-11e9-9b34-2526f4562808.png)
