### ISSUE TITLE
Is it possible to flush internal ImGui pool of windows?

### ISSUE THREAD

**Issue by kozodeevv** [ocornut/imgui#2858]
**Issue Template**
Version: 1.74 WIP
Branch: docking
Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MinGW 7.3.0 x64
Operating System: win10 

**My Issue/Question:**
Hi. I am working on little inhouse tool for content generation. An we have been choosen Dear ImGui as main gui library for this project. 

Main workflow is built on idea, that user may have any number of opened editors (image view, file browser, etc.), and switch between them doing some work. When work is done, you save it, and close editor.

And after some time playing with ImGui apis, making prototype, i noticed that count of windows, that reported in 'Dear ImGui Metrics' window increasing while you open new windows, and didn't decrease in time, when you working, or opening/closing windows.

The first question is: should i care about it, or it just fine, and imgui has some GC iternally that will collect all that unused windows after time? Or i need some kind of tracking mechanism, that manages id's of windows, by recycling it, to avoid leaking of pooled imgui objects.

If i need it, what direction should i choose?
For now, we tried two approaches, first - call windows with id that made on pattern Format("Window Name ##%X",  this). (string is cached). It may some time create two Window objects with same addres, but it pure fortune.
Use auto incremented/decremented ids. We just put static integer inside each type of window, and inc/dec it in constructor/destructor. But it also has pitfalls, like, you open two windows (count == 2 windows ids == 0,1), than close first one (count == 1, windows with id 1 persist), than open new window, and "bam", you have two windows in one, because they are share same id (1).
Now we looking into some kind of id-pool, that givese you unique ids, and recycles them each time window object has been destroyed.

All that thing makes me little bit sad, because ImGui such a nice thing, that make a lot of things for you, and you could just make cool stuff, without indepth thinking about all that low level things. But dealing with id pools, makes you think.

Second question is: as far as i can see, ImGui has pools, that based on some kind of map<WindowID, ActualWindow>, can i flush it some how, if i know, that i would never use same ids again (in case if window id is based on addres of controller object)?

**Comment by ocornut** [comment]
Hello,

> Should I care about it?

If you can’t measure the effect of a supposed issue then you probably shouldn’t care too much about it. There is a GC which frees the large buffers (vertex buffers, mostly) when windows are unused but the windows themselves are kept.

It also very much depends of the magnitude of windows count you are talking about. If it is 100 windows then you definitely don’t have to care about it. If it is 10000 windows then you will pay some meaningful overhead which you could aim to avoid. It also depends on the average lifetime of your app session (20 minutes or 20 consecutive hours).

If this is actually a problem for you, you could decide to shutdown and recreate the imgui context from time to time. You will lose the data stored in ImGuiStorage which is mostly the open/close state of tree nodes. We could decide to evolve the GC to free windows and keep that data aside later but it never came as a point of pressure for users.

You probably want to avoid situation where “window id is based on address of controller object)?“. Instead allocate an id per active object and generate your window names using it.

Making an id pool thing should be a matter of creating a simple helper struct which you can reuse easily I suppose?

You could create a vector, indexed by the ID value + 1 int storing the first available ID. In each element of the vector, store the next available element index, or -1 when the ID is actively used, grow the vector when there’s no available ID.

struct IdPool
{
ImVector<int> data;
int first_avail_id = -1;

int AllocateId()
{
  if (first_avail_id == -1)
  {
      data.push_back(-1);
      return data.Size - 1;
  }
  int id = first_avail_id;
  first_avail_id = data[id];
  data[id] = -1;
  return id;
}

void FreeId(int id)
{
  IM_ASSERT(id >= 0 && id < data.Size);
  IM_ASSERT(data[id] == -1); // make sure its used
  data[id] = first_avail_id;
  first_avail_id = id;
}
}

I’m typing this on the phone untested so it may be buggy or incorrect but should get you started.

-Omar

**Comment by kozodeevv** [comment]
Well, you probably right, about the negligiable size of impact, doing nothing, and left things as they are right now.

But my perfectionists feelings talking inside me, differently. When i know, that some objects left, and isn't used anymore, i want to delete them. Yes, in this particular case it doesn't make sence, because objects are became compacted after some time(as i findout later), and only id, and some other small stuff left.

The actual lifecycle of my app is about one working day (8-9 hrs), and couple of dozens windows opened.

Your pool implementation is nice. It will help get rid of unused objects, and keep implementation simple.

Thank you very much for your quick reply. ImGui is great, we love it.

Kind regards, KV.
