### ISSUE TITLE
Flame Graph Widget for displaying Performance metrics

### ISSUE THREAD

**Issue by bwrsandman** [ocornut/imgui#2859]
I was looking for a flame graph widget in like those profilers displayed in the gallery but I couldn't find any open source ones.
So I decided to roll out my own and make it available to anyone who wants to use it.

The code is located at https://github.com/bwrsandman/imgui-flame-graph
The widget can be called with `PlotFlame` I tried to keep the function signature similar to `PlotEx`.

![imgui-widget-flame-graph](https://user-images.githubusercontent.com/1013356/67152105-b4167200-f2d0-11e9-8186-397641521c02.png)

I am open to feedback and I hope someone finds it useful.

**Comment by ocornut** [comment]
Thank you @bwrsandman for posting this. Added link to Wiki.
Hopefully when we get around to rewrite a new plotting system this will be one of the feature we'll want to support nicely.

**Comment by ocornut** [comment]
Closing this now (marked as "useful widget" + added link in https://github.com/ocornut/imgui/wiki/Useful-Widgets)
Thanks again for this!
