### ISSUE TITLE
SetCursorPos() with SameLine()

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#2860]
**Version/Branch of Dear ImGui:**

Version: 1.72
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui.net
Operating System: win10

**My Issue/Question:**
I'm trying to write a custom component that renders a Button with a centered image icon. The icon is a glyph from an IconFont.

In my UI code I do something like this...

```
CustomComponents.IconButton(Icon.JumpToFirstKeyframe,"##firstKeyframe",  _timeControlsSize);
ImGui.SameLine();
            
CustomComponents.IconButton(Icon.JumpToPreviousKeyframe,"##prevKeyframe",  _timeControlsSize);
ImGui.SameLine();
```
But SameLine ignores the position set SetCursorPos() and uses the last end pos of  `Text()` that I'm using to write the custom icon. (see screenshot below).

What would be the most effective way of rendering a custom glyph at a position without affecting the` SameLine()` layout?

My custom component
```
        public static bool IconButton(Styling.Icon icon, string label, Vector2 size)
        {
            var clicked = ImGui.Button(label, size);
            Icons.DrawCentered(icon);
            return clicked;
        }
```

Drawing the icon
```
        public static void DrawCentered(Icon icon)
        {
            var g = IconFont.FindGlyph((char)icon);
            var iconSize = new Vector2(g.X1-g.X0, g.Y1- g.Y0)/2;
            var pos= (ImGui.GetItemRectMax() + ImGui.GetItemRectMin()) / 2 - iconSize;

            var keepPosition = ImGui.GetCursorScreenPos();
            ImGui.SetCursorScreenPos(pos);
            ImGui.PushFont(IconFont);
            ImGui.Text(((char)(int)icon).ToString());  // <--- this modifies the position
            ImGui.PopFont();
            ImGui.SetCursorScreenPos(keepPosition);  //<--- I assumed this would restore the pos
        }
```

**Screenshots/Video**

![IconAlignment](https://user-images.githubusercontent.com/1732545/67160482-80c7f780-f351-11e9-96aa-6124839a6eff.png)

**Comment by pixtur** [comment]
I found a work around using an `InvisibleButton`:

```
        public static bool IconButton(Styling.Icon icon, string label, Vector2 size)
        {
            var lastPos = ImGui.GetCursorScreenPos();
            var clicked = ImGui.Button(label, size);
            Icons.DrawCentered(icon);
            ImGui.SetCursorScreenPos(lastPos);
            ImGui.InvisibleButton("##dummy", size);
            return clicked;
        }
```

**Comment by ocornut** [comment]
Hello Thomas,

Technically speaking you could be using BeginGroup/EndGroup but this is quite overkill.

You should consider merging your icon fonts into your main font so you don't have to do all this font juggling. Because `style.ButtonTextAlign` default to (0.5,0.5) (== centered) just calling `ImGui.Button()` will give you the exact effect effect as your IconButton() function:

`ImGui.Button(Icon.JumpToPreviousKeyframe + "##prevKeyframe", _timeControlsSize);`

**Comment by pixtur** [comment]
Excellent solution! I'm not sure about the distinction between main font / icon font. We currently use four fonts (light, bold, small and icons). But this should work just fine with PushFont(), shouldn't it?

With the following code...

```
        public static bool IconButton(Styling.Icon icon, string label, Vector2 size)
        {
            ImGui.PushFont(Icons.IconFont);
            ImGui.PushStyleVar(ImGuiStyleVar.ButtonTextAlign, new Vector2(0.5f,0.5f));
            var clicked = ImGui.Button((char)(int)icon+"##"+label, size);
            ImGui.PopStyleVar();
            ImGui.PopFont();
            return clicked;
        }
```
it works like a charm.
