### ISSUE TITLE
how to get pixel from a drawn image

### ISSUE THREAD

**Issue by 2uy** [ocornut/imgui#2867]
Version/Branch of Dear ImGui:
Version: 1.72
Branch: master
Back-end/Renderer/Compiler/OS
Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Operating System: Windows 10

**My Issue/Question:**

hi omar,
I drew an image with imgui.
How can I get the pixel value of a certain coordinate in my image? 
( For example, the pixel value of my mouse cursor coordinates )

thanks,

**Comment by ocornut** [comment]
Hello @2uy,

You already asked the same question in #2855.

If you refer to the FAQ and Tutorials I linked to in that thread, namely https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples, you would understand that Dear ImGui doesn't know nor have access to your images. You own the images and therefore reading from them is not an Dear ImGui question but rather a question that has to do with DX11.

You can either hold on a RAM copy of the texture (the one before you uploaded to DX11 Graphics API) and read from there, either use some code to read straight from the texture or the framebuffer held by DX11. Neither of those problems are something we can solve for youhere.

You can use `ImGui::GetItemRectMin()` `ImGui::GetItemRectMax()` to retrieve the position of your last submitted image (equivalent to reading `ImGui::GetCursorScreenPos()` before submitting the item), and `ImGui::GetMousePos()` to retrieve the mouse position, from there you can calculate the pixel position in your texture. Actually reading from that pixel is out of scope here.
