### ISSUE TITLE
AddTriangle draws lines with nonuniform thickness

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#2868]
**Version/Branch of Dear ImGui:**

Version: 1.74 WIP (3c238ecae30b264aa8cf0509f1e24a6c8e1d6d21 latest commit at this time, but the same issue is even in much older versions)
Branch: master

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Compiler: msvc 2019
Operating System: Win10

**My Issue/Question:**

Lines of a triangle have nonuniform thickness

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/153526/67474154-48c3fb80-f654-11e9-95ef-e5ac695f4497.png)

**Standalone, minimal, complete and verifiable example:** 

```
        ImGui::Begin("test");
        auto dl = ImGui::GetWindowDrawList();
        const ImVec2 o = ImGui::GetCursorScreenPos();

        dl->AddTriangle(o, ImVec2(o.x + 100, o.y + 0), ImVec2(o.x + 0, o.y + 100), IM_COL32(0, 255, 0, 255), 3);
        ImGui::End();
```

If I do this, the triangle looks allright:
![image](https://user-images.githubusercontent.com/153526/67474601-05b65800-f655-11e9-98ea-36f4a06eb7cf.png)

**Comment by ocornut** [comment]
Hi !

I believe this is the same as #2183 in particular there's a suggestion https://github.com/ocornut/imgui/issues/2183#issuecomment-523273174
(the change referred in that comment is #2518 by @rmitton)

I haven't looked at your suggestion is detail, it seems simpler to implement than mentioned in the comment above (tho the sqrt is costly), I just have no idea if it is right.

We probably need a little portable suite that shows a bunch of test cases so we can compare algorithms. 

Pasting actual text for your patch would help :)

**Comment by nem0** [comment]
Oh yes, it is indeed the same issue. I'm sorry for that. I tried to search for something similar without success. My fix is probably not robust/complete, since I did not understand what `IM_FIXNORMAL2F` supposed to do and did not investigate further. I will try to improve the fix.
Closing this now and I will continue in #2183 if I think of anyhting.

**Comment by ocornut** [comment]
There was actually an issue which creeped in January 2019 and made this worst>
See #4053, fix pushed.
