### ISSUE TITLE
DragFloat with single click to edit?

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#2883]
**Version/Branch of Dear ImGui:**

Version: 1.62
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui.net
Compiler: c#
Operating Win10

**My Issue/Question:**

Is it possible to change the DragFloat interaction from double click to start keyboard input to single click (without drag)? It's just a personal preference, but I think the double clicking is unnecessary: If I want to click, I can click, otherwise I drag. Photoshop, AfterEffects and many other applications have the same interaction and since DragFloat already has a drag threshold, it seems to be feasible to implement such a behavior.

**Comment by ocornut** [comment]
Sounds like a reasonable idea to experiment with.

Thoughts:
- This would be problematic on touch systems where keyboard inputs are not wired, or not efficient to use. And we can't reasonably tell if that's the case or it so at beast it would be a setting or require new `ImGuiBackendFlags` to pass that info to the core library.

Note that you can also CTRL+Click to achieve the same effect as double-click (this is in order to match the behavior of Sliders which also currently react without a drag threshold).

**Comment by Folling** [comment]
As a workaround for this you could swap the internal state checking for whether a mouse-button is double clicked with the state of whether a mouse-button is clicked

I suppose that should work as a hacked solution to avoid editing any internals

**Comment by pixtur** [comment]
Oh it looks like, I failed to post/submit my last reply. Let's try again:

Thanks for your consideration. I know that changing the current behavior will have a lot of implications and I am also not a fan of additional options for personal arbitrary preferences. But since our application finally reached a state where I can actually create some content, I noticed how much I dislike double-clicking for a frequent interaction like this one.

Interesting side note: In tooll.io I assigned CTRL+Click to "reset" to default. This was super handy especially because it was also assigned to a Vector group title for resetting the whole vector group. We also assigned Dragging the title (for scaling group values or changing the brightness of colors (up/down and saturation). Both I used very frequently: https://youtu.be/Ky2JDuCoUiw?t=283

I probable will try again to write a custom component for editing. It should be possible to save the current id in a static component variable if it switched to edit mode.

@Folling I don't fully understand your suggestion, but I think that is probably not easy, because we're using imgui.net which doesn't expose the internal API.

**Comment by Arugin** [comment]
Yeah, I feel like adding an option with single click to edit would be great.

**Comment by ocornut** [comment]
I apologize that I forgot to post here before, but 1.80 (january 2021) added a `io.ConfigDragClickToInputText = true;` config option to enable this. Also see #3737.
I've been considering to make that enabled by default on a future major release maybe 1.90.

Please give it a try and let me know.

**Comment by pixtur** [comment]
Oh! That's awesome. Thanks for following up on that one!
