### ISSUE TITLE
How button works in columns

### ISSUE THREAD

**Issue by seukaiwokeo** [ocornut/imgui#2885]
`ImGui::Columns(6, NULL, false);
						for (int i = 0; i < Items.size(); ++i) {
if (ImGui::Button("Get")) {
     SetItem(Items[i]);
}

}

ImGui::Columns(1);`

First button in columns works but the others doesn't

**Comment by ocornut** [comment]
- Please read FAQ 
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-why-are-multiple-widgets-reacting-when-i-interact-with-a-single-one-q-how-can-i-have-multiple-widgets-with-the-same-label-or-with-an-empty-label

- Please fill issue template next time you open an issue.

**Comment by TheoMcIntosh** [comment]
> `ImGui::Columns(6, NULL, false); for (int i = 0; i < Items.size(); ++i) { if (ImGui::Button("Get")) { SetItem(Items[i]); }
> 
> }
> 
> ImGui::Columns(1);`
> 
> First button in columns works but the others doesn't

I have the same issue :( did you solve it?

**Comment by ocornut** [comment]
> i have the same issue :( did you solve it?

I already answered with the solution. 
Read the FAQ https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system
You should use PushID()/PopID() in loops generally to make underlying identifiers uniques.
