### ISSUE TITLE
How can I use ImGui display pointcloud or any Customized format data without using texture?

### ISSUE THREAD

**Issue by nonlinear1** [ocornut/imgui#2888]
Recently ,I want use imgui and opengl shader display pointclouds with customized format data On ubuntu18.04. The format of pointclouds is struct pointcloud { float x, float y, float z, float r, float g, float b}. I found If I want display some picutre or anything in imgui I must use ImGUI::Image, Just like this "ImGui::Image((void*)(intptr_t)my_image_texture, ImVec2(my_image_width, my_image_height));" .But for pointcloud  { float x, float y, float z, float r, float g, float b} this kinds of datas. They cann't become any textures. I use the following shader to display:
constexpr char const PointCloudFragmentShader[] =
R"(
#version 430
in vec4 vertexColor;
out vec4 fragmentColor;
uniform bool enableShading;
void main()
{
      fragmentColor = vertexColor;
}
)";

constexpr char const PointCloudVertexShader[] =
R"(
#version 430
layout(location = 0) in vec4 inColor;
layout(location = 1) in vec3 inPositon;
out vec4 vertexColor;
uniform mat4 view;
uniform mat4 projection;
void main()
{
     gl_position = projection*view*vec4(inPosion,1);
    vertexColor = inColor;
}
}
But use opengl shaders to display, I cann't put the picture of pointcloud in the windows of imGUI.
Could someone give me suggestion about  how to use imGui display pointcloud with opengl shader?
Thank you very much!

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (do not create a new post) with the Issue Template shown in "New Issue", then reply here when edited.

Closing until post is edited.
