### ISSUE TITLE
UWP compile error C2039: `OpenClipboard`: is not a member of global namespace

### ISSUE THREAD

**Issue by linuxaged** [ocornut/imgui#2892]
got error when building latest docking branch with vcpkg.
Steps:
* modify `${VCPKG_ROOT}/ports/portfile.cmake`, use docking branch instead of master
```
		vcpkg_from_github(
		    OUT_SOURCE_PATH SOURCE_PATH
		    REPO ocornut/imgui
		    HEAD_REF docking
		)
```
* `vcpkg install --head imgui --triplet x86-uwp`

The Error:

    生成启动时间为 2019/11/12 21:00:29。
         1>节点 1 上的项目“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\install.vcxproj”(默认目标)。
         1>项目“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\install.vcxproj”(1)正在节点 1 上生成“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\ZERO_CHECK.vcxproj”(2) (默认目标)。
         2>PrepareForBuild:
             正在创建目录“Win32\Debug\ZERO_CHECK\”。
             正在创建目录“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\Debug\”。
             正在创建目录“Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\”。
           InitializeBuildStatus:
             正在创建“Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
           CustomBuild:
             Checking Build System
           FinalizeBuildStatus:
             正在删除文件“Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”。
             正在对“Win32\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate”执行 Touch 任务。
         2>已完成生成项目“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\ZERO_CHECK.vcxproj”(默认目标)的操作。
         1>项目“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\install.vcxproj”(1)正在节点 2 上生成“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\ALL_BUILD.vcxproj”(3) (默认目标)。
         3>项目“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\ALL_BUILD.vcxproj”(3)正在节点 2 上生成“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj”(4) (默认目标)。
         4>PrepareForBuild:
             正在创建目录“imgui.dir\Debug\”。
             正在创建目录“imgui.dir\Debug\imgui.tlog\”。
             正在创建目录“Generated Files\”。
           GetInstalledSDKLocations:
             搜索以“UAP, 10.0.18362.0”为目标的 SDK。
             搜索以“Windows, 8.1”为目标的 SDK。
           ResolveSDKReferences:
               读取 SDK 清单文件“C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\SDKManifest.xml”。
               目标配置和体系结构“Debug|x86”
               在 SDK 清单中找不到“FrameworkIdentity”特性“FrameworkIdentity-Debug-x86”。 
               在 SDK 清单中找到了“FrameworkIdentity”特性“Name = Microsoft.VCLibs.140.00.Debug, MinVersion = 14.0.27323.0, Publisher = 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'”。
               在 SDK 清单中找到了“APPX”位置特性“AppX-Debug-x86=.\AppX\Debug\x86\Microsoft.VCLibs.x86.Debug.14.00.appx”。
               在 SDK 清单中找到了“APPX”位置特性“AppX-Debug-x64=.\AppX\Debug\x64\Microsoft.VCLibs.x64.Debug.14.00.appx”。
               在 SDK 清单中找到了“APPX”位置特性“AppX-Debug-ARM=.\AppX\Debug\ARM\Microsoft.VCLibs.ARM.Debug.14.00.appx”。
               在 SDK 清单中找到了“APPX”位置特性“AppX-Debug-ARM64=.\AppX\Debug\ARM64\Microsoft.VCLibs.ARM64.Debug.14.00.appx”。
           ExpandSDKReferences:
             枚举“C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\”中的 SDK 引用“Microsoft.VCLibs, Version=14.0”。
           InitializeBuildStatus:
             正在创建“imgui.dir\Debug\imgui.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
           CustomBuild:
             Building Custom Rule C:/workspace/vcpkg/buildtrees/imgui/src/head/docking-4204cbc554/CMakeLists.txt
           ClCompile:
             C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX64\x86\CL.exe /c /I"C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\\" /I"Generated Files\\" /Iimgui.dir\Debug\ /Z7 /W3 /WX- /diagnostics:column /sdl /MP /Od /Ob0 /Oi /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _UNICODE /D UNICODE /D WINAPI_FAMILY=WINAPI_FAMILY_APP /D __WRL_NO_DEFAULT_LIB__ /Gm- /EHsc /RTC1 /MDd /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"imgui.dir\Debug\\" /Fd"imgui.dir\Debug\imgui.pdb" /Gd /TP /FU"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86\store\references\platform.winmd" /analyze- /errorReport:queue  /utf-8 "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_demo.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_draw.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_widgets.cpp"
             Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x86
             Copyright (C) Microsoft Corporation.  All rights reserved.
             cl /c /I"C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\\" /I"Generated Files\\" /Iimgui.dir\Debug\ /Z7 /W3 /WX- /diagnostics:column /sdl /MP /Od /Ob0 /Oi /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _UNICODE /D UNICODE /D WINAPI_FAMILY=WINAPI_FAMILY_APP /D __WRL_NO_DEFAULT_LIB__ /Gm- /EHsc /RTC1 /MDd /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"imgui.dir\Debug\\" /Fd"imgui.dir\Debug\imgui.pdb" /Gd /TP /FU"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86\store\references\platform.winmd" /analyze- /errorReport:queue  /utf-8 "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_demo.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_draw.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_widgets.cpp"
             cl /c /I"C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\\" /I"Generated Files\\" /Iimgui.dir\Debug\ /Z7 /W3 /WX- /diagnostics:column /sdl /MP /Od /Ob0 /Oi /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _UNICODE /D UNICODE /D WINAPI_FAMILY=WINAPI_FAMILY_APP /D __WRL_NO_DEFAULT_LIB__ /Gm- /EHsc /RTC1 /MDd /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"imgui.dir\Debug\\" /Fd"imgui.dir\Debug\imgui.pdb" /Gd /TP /FU"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86\store\references\platform.winmd" /analyze- /errorReport:queue  /utf-8 "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_demo.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_draw.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_widgets.cpp"
             imgui.cpp
             cl /c /I"C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\\" /I"Generated Files\\" /Iimgui.dir\Debug\ /Z7 /W3 /WX- /diagnostics:column /sdl /MP /Od /Ob0 /Oi /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _UNICODE /D UNICODE /D WINAPI_FAMILY=WINAPI_FAMILY_APP /D __WRL_NO_DEFAULT_LIB__ /Gm- /EHsc /RTC1 /MDd /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"imgui.dir\Debug\\" /Fd"imgui.dir\Debug\imgui.pdb" /Gd /TP /FU"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86\store\references\platform.winmd" /analyze- /errorReport:queue  /utf-8 "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_demo.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_draw.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_widgets.cpp"
             cl /c /I"C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\\" /I"Generated Files\\" /Iimgui.dir\Debug\ /Z7 /W3 /WX- /diagnostics:column /sdl /MP /Od /Ob0 /Oi /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _UNICODE /D UNICODE /D WINAPI_FAMILY=WINAPI_FAMILY_APP /D __WRL_NO_DEFAULT_LIB__ /Gm- /EHsc /RTC1 /MDd /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"imgui.dir\Debug\\" /Fd"imgui.dir\Debug\imgui.pdb" /Gd /TP /FU"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86\store\references\platform.winmd" /analyze- /errorReport:queue  /utf-8 "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_demo.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_draw.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_widgets.cpp"
             cl /c /I"C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\\" /I"Generated Files\\" /Iimgui.dir\Debug\ /Z7 /W3 /WX- /diagnostics:column /sdl /MP /Od /Ob0 /Oi /Oy- /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _UNICODE /D UNICODE /D WINAPI_FAMILY=WINAPI_FAMILY_APP /D __WRL_NO_DEFAULT_LIB__ /Gm- /EHsc /RTC1 /MDd /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"imgui.dir\Debug\\" /Fd"imgui.dir\Debug\imgui.pdb" /Gd /TP /FU"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86\store\references\platform.winmd" /analyze- /errorReport:queue  /utf-8 "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_demo.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_draw.cpp" "C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui_widgets.cpp"
             imgui_demo.cpp
             imgui_draw.cpp
             imgui_widgets.cpp
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14501,12): error C2039: 'OpenClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14501,8): error C3861: 'OpenClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14503,28): error C2039: 'GetClipboardData': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14503,44): error C3861: 'GetClipboardData': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14506,11): error C2039: 'CloseClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14506,25): error C3861: 'CloseClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14516,7): error C2039: 'CloseClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14516,21): error C3861: 'CloseClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14522,12): error C2039: 'OpenClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14522,8): error C3861: 'OpenClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14528,11): error C2039: 'CloseClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14528,25): error C3861: 'CloseClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14534,7): error C2039: 'EmptyClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14534,21): error C3861: 'EmptyClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14535,11): error C2039: 'SetClipboardData': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14535,8): error C3861: 'SetClipboardData': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14537,7): error C2039: 'CloseClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14537,21): error C3861: 'CloseClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
         4>已完成生成项目“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj”(默认目标)的操作 - 失败。
         3>已完成生成项目“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\ALL_BUILD.vcxproj”(默认目标)的操作 - 失败。
         1>已完成生成项目“C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\install.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

           “C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\install.vcxproj”(默认目标) (1) ->
           “C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\ALL_BUILD.vcxproj”(默认目标) (3) ->
           “C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj”(默认目标) (4) ->
           (ClCompile 目标) -> 
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14501,12): error C2039: 'OpenClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14501,8): error C3861: 'OpenClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14503,28): error C2039: 'GetClipboardData': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14503,44): error C3861: 'GetClipboardData': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14506,11): error C2039: 'CloseClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14506,25): error C3861: 'CloseClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14516,7): error C2039: 'CloseClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14516,21): error C3861: 'CloseClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14522,12): error C2039: 'OpenClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14522,8): error C3861: 'OpenClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14528,11): error C2039: 'CloseClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14528,25): error C3861: 'CloseClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14534,7): error C2039: 'EmptyClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14534,21): error C3861: 'EmptyClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14535,11): error C2039: 'SetClipboardData': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14535,8): error C3861: 'SetClipboardData': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14537,7): error C2039: 'CloseClipboard': is not a member of '`global namespace'' [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]
             C:\workspace\vcpkg\buildtrees\imgui\src\head\docking-4204cbc554\imgui.cpp(14537,21): error C3861: 'CloseClipboard': identifier not found [C:\workspace\vcpkg\buildtrees\imgui\x86-uwp-dbg\imgui.vcxproj]

        0 个警告
        18 个错误

    已用时间 00:00:01.64

**Comment by ocornut** [comment]
I have no idea how UWP works and if it disable classic Win32 function.

You can `#define IMGUI_DISABLE_WIN32_FUNCTIONS` in imconfig.h to disable using those two functions.

You will need to setup `io.SetClipboardTextFn` `io.GetClipboardTextFn` in the binding to your own UWP mapping if you want Dear ImGui to access/use your OS clipboard.

**Comment by linuxaged** [comment]
Same issue https://github.com/bkaradzic/bgfx/issues/325#issuecomment-91208281

**Comment by ocornut** [comment]
Hello @linuxaged,

Could you see if this would fix it for you:

- Remove the `#define IMGUI_DISABLE_WIN32_FUNCTIONS` line you added.

- Instead, in imgui.cpp, right under this block:
```
#ifndef __MINGW32__
#include <Windows.h>
#else
#include <windows.h>
#endif
```
Try adding:
```
#if defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_APP)
#define IMGUI_DISABLE_WIN32_DEFAULT_CLIPBOARD_FUNCTIONS
#endif
```

I think it should work and then we can add this code in Dear ImGui codebase to avoid editing imconfig.h.

Thank you!

**Comment by ocornut** [comment]
Merged PR, thank you.
