### ISSUE TITLE
Unity Builds of imgui broken by duplicated function HelpMarker

### ISSUE THREAD

**Issue by missmah** [ocornut/imgui#2893]
**Version/Branch of Dear ImGui:**

Version: vanilla
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: Not relevant here.
Compiler: MSVC 14, but this shouldn't matter. Unity build is what matters here.
Operating System: Windows 10

**My Issue/Question:**

Our Unity Builds just broke because `static void HelpMarker(const char* desc)` now exists in two separate compilation units (`imgui.cpp` and `imgui_demo.cpp`).

It seems either one should be extern and use the other at link time, or if you really want duplication, the function should either be renamed in one case or go into a header as inline.

**Comment by ocornut** [comment]
Thank you @missmah for reporting.
Should be fixed now.

I have also added in our CI task list to add a test for unity builds, so hopefully this won't happen in the future. 

Note that we still have a bunch of symbols that are not in `ImGui::` namespace so we won't guarantee a "project-wide" unity build to function, however we should at least guarantee that "dear imgui-wide" unity build should.

**Comment by missmah** [comment]
Thanks @ocornut for the quick fix! I went in to temporarily make the changes locally, and next time I sync'd it was already fixed.

And understood and appreciated on the Unity front. Thanks again for everything you do!

**Comment by ocornut** [comment]
1742ca45c5aace614be83b237af2f014b4c2d90d by @rokups added CI testing for unity builds now.

![image](https://user-images.githubusercontent.com/8225057/69736185-4e6c9f80-1132-11ea-9966-dcdb4a5a5265.png)
