### ISSUE TITLE
Demo code would causes unexpected situation

### ISSUE THREAD

**Issue by kwangsing3** [ocornut/imgui#2897]
**Version/Branch of Dear ImGui:**

Version: 1.74 WIP(17301)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 

Compiler: MS Visual studio  C++17
Operating System: Windows10

**My Issue/Question:**
 
Hi, I change some code at the example for showing what's going on , and found some contradiction.  
The code from imgui_demo.cpp will cause unexpected situation, as the gif.

**Screenshots/Video**
From the example:
![ezgif-2-56b0e17001a4](https://user-images.githubusercontent.com/18378969/69042420-2099a380-0a2c-11ea-9354-12bde0063d32.gif)

My case:
![2019-11-16-23-49-53](https://user-images.githubusercontent.com/18378969/68996458-609a4280-08d5-11ea-91a4-d7c1c52ce54d.gif)

**Standalone, minimal, complete and verifiable example:** 

The function will return false after docking,  (although it's reasonable)
And in my case, I called it every frame at another class, so it cause flashing.

Or, I had a misunderstanding?

These code are from imgui_demo.cpp
```c++
        static bool _settrue = true;
            if (!ImGui::Begin("Scene", &_settrue))
            {
                // Early out if the window is collapsed, as an optimization.
                ImGui::End();
                return 0;
            }
            ImGui::End();
```

**Comment by ocornut** [comment]
Hello,

You didn’t provide a “ Standalone, minimal, complete and verifiable example:” at all so it’s all to tell whats going on. If you claim that just settings the flag is enough then please provide a video of the bug in the regular dear imgui demo, without running your own code.

It’s more likely that your code exhibit the issue and we can’t dig in without more details.

**Comment by kwangsing3** [comment]
Sorry, my fault.
Please,  $git clone https://github.com/kwangsing3/Error_repository.git
I cleared most unrelated code and files as possible, and keep the bug successfully.


If you don't mind, let me mention one more thing maybe it's the reason.
I opened a Popup item with Menuitem, (Of course without changed source code)
I search other issue before, it couldn't be done normally, but you did gave some solution, 
Suppose that this is the only thing out of your control, I guess?

![2019-11-17-09-55-58](https://user-images.githubusercontent.com/18378969/69002024-57d05d80-0923-11ea-9bbe-718bd9cda463.gif)

After deleted that, it still happen, so that's not the reason, but just let you know :P

**Comment by ocornut** [comment]
If you return from your main loop this is going to exit your application.
This has nothing to do with the initial issue you showed above.
Please ask for support on the Discord server (see https://github.com/ocornut/imgui/wiki)
