### ISSUE TITLE
About early that SDL2 OpenGL3 example high CPU solved

### ISSUE THREAD

**Issue by mindoff6502** [ocornut/imgui#2899]
I don't know why it's closed,but I just solved.
For some reason, SDL2 Opengl in Release Mode will run very fast and no auto vsynth wait in the while loop.So if it runs too fast sure it will cost high CPU.Don't know why SDL OpenGL act different with GLFW.Also the imgui example they look the same.They don't act the same.
The solve for me is add
SDL_Delay(16);
at the end of while loop.16 can be other number you should test,
Then the CPU will drop
Then the example will act the same.

Don't know if I make my point clear.
That's my solution for now.

**Comment by mindoff6502** [comment]
Also I should say this may or may not be useful because this will cause FPS drop.

**Comment by ocornut** [comment]
I closed #2898 because I established this wasn't a dear imgui topic.
Please post in the same issue instead of reopening several new issues, than you.
