### ISSUE TITLE
questions regarding event loop

### ISSUE THREAD

**Issue by sancelot** [ocornut/imgui#2901]
I am used too make a window refresh only if needed .
meaning when there are some user input event or mouse event.

It looks like it is redisplayed on a regular refresh rate.

Is it possible to avoid it ?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
Closing.
