### ISSUE TITLE
incorrectly draws a png picture

### ISSUE THREAD

**Issue by kasiroprax** [ocornut/imgui#2902]
Why i have that mistakes? left switch ImGui draw, right - original png.
Any ideas?
![imgui_swiches](https://user-images.githubusercontent.com/42935187/69363391-82167800-0ca1-11ea-8ece-e3cfe5139e28.png)

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.

Closing. Blocked.
