### ISSUE TITLE
Texture2D ortho transformation before adding to draw list

### ISSUE THREAD

**Issue by rytisss** [ocornut/imgui#2903]
**Version/Branch of Dear ImGui:**

Version: 1.73
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp
Compiler: Visual Studio C++
Operating System: Windows 10

**My Question:**

I'm trying to perform ortho transformation to texture before adding it to drawing list. Howerer, i don't really know how to get shader ID to do that. My code:

```
glm::mat4 projMat = glm::ortho(leftOrtho, rightOrtho, topOrtho, bottomOrtho);
glGetIntegerv(GL_CURRENT_PROGRAM, &ID);//not sure about this
glUseProgram(ID);//not sure about this
GLint locationID = glGetUniformLocation(ID, "ProjMtx");//Error goes here
error = glGetError();
if (error != GL_NO_ERROR)
{
	std::cout << "not working" << std::endl;
}
glUniformMatrix4fv(ID, 1, GL_FALSE, glm::value_ptr(projMat));
```

After this, i'm adding texture to drawing list:

```
ImGui::GetWindowDrawList()->AddImage(
(ImTextureID)frameBuffer, pos,
bottomRight, ImVec2(0, 0), ImVec2(1, 1));
```

It does work and draws image, however the main idea of transformation is to perform ortho transformation to maintain aspect ratio on window resize.

**Comment by ocornut** [comment]
Hello,

This is more of an OpenGL question than a Dear ImGui question.

You can use ImDrawList::AddCallback() to register callbacks which will be run by your render loop (here imgui_impl_opengl3.cpp), as all the ImDrawList commanda are deferred and rendered at the end of this frame by that render function.

One the minutia of using shaders etc please ask on OpenGL/graphics programming forum.

In this particular example you listed, if you are going to only render a few images (rather than a 10000+ vertices mesh) then you would probably be better off transforming the vertices CPU side and sending transformed vertices to ImDrawList by emitting the vertices yourself (see what AddImage does).

**Comment by ocornut** [comment]
PS: please do fill the issue template, further issue from same user will be closed/blocked if issue template if not filled correctly.

**Comment by rytisss** [comment]
Thank you for a quick response.
(I updated question as in template)

**Comment by rytisss** [comment]
AddImage() pushes texture with uv (position) to stack for rendering as i understand. I have also found AddImageQuad() method, that i probably can be used for orthographic transformation. I can't find a lot of information.

**Comment by rytisss** [comment]
Okay, sorry for bothering again, but i will post this, so people who will end up in the same situation can solve it faster. So in general AddImageQuad() does work. In general, this :)
```cpp
void ImDrawList::PrimRectUV(const ImVec2& a, const ImVec2& c, const ImVec2& uv_a, const ImVec2& uv_c, ImU32 col)
{
    ImVec2 b(c.x, a.y), d(a.x, c.y), uv_b(uv_c.x, uv_a.y), uv_d(uv_a.x, uv_c.y);
    ImDrawIdx idx = (ImDrawIdx)_VtxCurrentIdx;
    _IdxWritePtr[0] = idx; _IdxWritePtr[1] = (ImDrawIdx)(idx+1); _IdxWritePtr[2] = (ImDrawIdx)(idx+2);
    _IdxWritePtr[3] = idx; _IdxWritePtr[4] = (ImDrawIdx)(idx+2); _IdxWritePtr[5] = (ImDrawIdx)(idx+3);
    _VtxWritePtr[0].pos = a; _VtxWritePtr[0].uv = uv_a; _VtxWritePtr[0].col = col;
    _VtxWritePtr[1].pos = b; _VtxWritePtr[1].uv = uv_b; _VtxWritePtr[1].col = col;
    _VtxWritePtr[2].pos = c; _VtxWritePtr[2].uv = uv_c; _VtxWritePtr[2].col = col;
    _VtxWritePtr[3].pos = d; _VtxWritePtr[3].uv = uv_d; _VtxWritePtr[3].col = col;
    _VtxWritePtr += 4;
    _VtxCurrentIdx += 4;
    _IdxWritePtr += 6;
}

void ImDrawList::PrimQuadUV(const ImVec2& a, const ImVec2& b, const ImVec2& c, const ImVec2& d, const ImVec2& uv_a, const ImVec2& uv_b, const ImVec2& uv_c, const ImVec2& uv_d, ImU32 col)
{
    ImDrawIdx idx = (ImDrawIdx)_VtxCurrentIdx;
    _IdxWritePtr[0] = idx; _IdxWritePtr[1] = (ImDrawIdx)(idx+1); _IdxWritePtr[2] = (ImDrawIdx)(idx+2);
    _IdxWritePtr[3] = idx; _IdxWritePtr[4] = (ImDrawIdx)(idx+2); _IdxWritePtr[5] = (ImDrawIdx)(idx+3);
    _VtxWritePtr[0].pos = a; _VtxWritePtr[0].uv = uv_a; _VtxWritePtr[0].col = col;
    _VtxWritePtr[1].pos = b; _VtxWritePtr[1].uv = uv_b; _VtxWritePtr[1].col = col;
    _VtxWritePtr[2].pos = c; _VtxWritePtr[2].uv = uv_c; _VtxWritePtr[2].col = col;
    _VtxWritePtr[3].pos = d; _VtxWritePtr[3].uv = uv_d; _VtxWritePtr[3].col = col;
    _VtxWritePtr += 4;
    _VtxCurrentIdx += 4;
    _IdxWritePtr += 6;
}
```

**Comment by ocornut** [comment]
You want to be transforming your vertices (e.g. using a 2d rotation matrix op)
See #1982 for an exemple but you'll find more resources about rotating a quad on the internet (unrelated to the dear imgui).

**Comment by thedmd** [comment]
There is an extension I made to deal with 2D transformations in ImDrawList
[feature/draw-list-transformation](https://github.com/thedmd/imgui/tree/feature/draw-list-transformation) with basic `ImMatrix`.

**Comment by thedmd** [comment]
Hi @Jemal 

This PR basically adds three functions to `ImDrawList`:
```cpp
    IMGUI_API void  SetTransformation(const ImMatrix& transformation);
    IMGUI_API void  ApplyTransformation(const ImMatrix& transformation);
    IMGUI_API void  PopTransformation(int count = 1);
```

They're working like OpenGL's matrix `glLoadMatrix`, `glPushMatrix` and `glPopMatrix`.

```cpp
auto draw_list = ImGui::GetWindowDrawList();
draw_list->ApplyTransformation(ImMatrix::Rotation(45 * 3.1415f / 180.0f));
ImGui::Button("Hello");
draw_lsit->PopTransformation();
```

It will work with `AddImage` function too. Magic will happen when `PopTransformation` is called, so everything you draw after calling `ApplyTransformation` will be affected.

Please note this does not change ImGui logic in any way.

**Comment by thedmd** [comment]
It appers image is scalled with respect to top/left corner of your screen (which is origin of coordinate system).
To scale object around it center usually following steps are executed:
* translate object by `(-cx, -cy)` where `cx` and `cy` are coordinatnates of the center of rectangle in global coordinate system
* scale
* translate object by `(cx, cx)` to move rect back where it was

This sequence of operations is expressed as single `ImMatrix`.

Something like this. Note: I'm not 100% sure if order of multiplication here is right or should be reveresd.
```cpp
ImMatrix ScaleAroundCenter(ImVec2 scale, ImVec2 center)
{
    return ImMatrix::Combine
    (
        ImMatrix::Combine
        (
            ImMatrix::Translation(-center.x, -center.y),
            ImMatrix::Scaling(scale)
        ),
        ImMatrix::Translation(center)
    );
}

// with operator*
ImMatrix ScaleAroundCenter(ImVec2 scale, ImVec2 center)
{
    return ImMatrix::Translation(-center.x, -center.y)
         * ImMatrix::Scaling(scale)
         * ImMatrix::Translation(center);
}
```
