### ISSUE TITLE
custom mouse cursor

### ISSUE THREAD

**Issue by xarthurx** [ocornut/imgui#2904]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.69
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Operating System: Windows

**My Issue/Question:**
I'm working on a custom UI that allows users to draw/paint on the screen. This requires a custom mouse cursor (as simple as a circle is enough now) with the ability of size changing.

I've seen from the demo window and the code that there are several default cursors `ImGuiMouseCursor_`. 

My question contains two parts:
1. How can I change/replace them? Should the new cursor be an image or sth like  https://github.com/ocornut/imgui/issues/2854 (I guess this is defining a font?)
2. How can I change the size? (if a font, then change the font size? can I? Or if an image, changes the size of the image?)

Quite helpless here and will appreciate any kind of help.

Thanks.

**Comment by ocornut** [comment]
You can just set the cursor to `ImGuiMouseCursor_None` and then draw your own shape using the `ImGui::GetForegroundDrawList()->AddXXX` calls, either using geometry either using an image which you can load yourself (see https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-an-image-what-is-imtextureid-how-does-it-work and https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples)

**Comment by unknown81311** [comment]
Im wondering how I can set the cursor image depending on how imgui is setting the cursor type.
for instance imgui sets the cursor to have arrows if the user is touching the border of a resizable window.
