### ISSUE TITLE
Assert in DockNodeTreeUpdatePosSize() when minimized

### ISSUE THREAD

**Issue by MrHunte96** [ocornut/imgui#2906]
**Version/Branch of Dear ImGui:**

Version: 1.74 (WIP)
Branch: mocking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_opengl3.cpp _(or specify if using a custom engine/back-end)_
Compiler: visual studio 2019
Operating System: Windows 10

**My Issue/Question:**

Hi, I have an issue with minimizing my window after docking the ImGuiWindows in a certain way. I'm not sure if I edited something or it's a bug. I tried to use all the imguidemo.cpp code to replicate this issue.
Anyone experience this too?

**Screenshots/Video**
 Here a video: 
https://youtu.be/0U_77LUN5xA

**Standalone, minimal, complete and verifiable example:** 
```
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplWin32_NewFrame();
    ImGui::NewFrame();
    ImGui::ShowDemoWindow();  
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

**Comment by ocornut** [comment]
Hello,
Thank you for the report!
I have confirmed that I am able to reproduce the issuehere.

**Comment by ocornut** [comment]
I have looked into this and established that the asserts added in 718e15c7 and 7c183dc6 are faulty. Removed those and also fixed another bug making minimized viewports consistently preserve their last known size (in your case the zero-sized viewport when minimized was triggering your issue, but is not the only possible trigger). 
Adding some tests in the Regression Tests framework now.
