### ISSUE TITLE
Font Outline

### ISSUE THREAD

**Issue by ReignG** [ocornut/imgui#2909]
I saw that a while ago there was no support for outline in fonts, is there anything new now?
Any method of putting font outline in imgui?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
Closing.

**Comment by ocornut** [comment]
Bonus: Sorry but #1586
