### ISSUE TITLE
example_glfw_metal consumes too much RAM while in background (11+ GB)

### ISSUE THREAD

**Issue by marcizhu** [ocornut/imgui#2910]
**Version/Branch of Dear ImGui:**

Version: 1.74 WIP
Branch: master (commit `b205ab01`)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_metal.cpp
Operating System: macOS Catalina 10.15.1

**My Issue:**

While running the example app (`imgui_demo.cpp`), if the app goes to the background, it starts to consume more and more RAM until the system runs out and hangs. I've seen it consume up to 58 GB of RAM all by itself.

**Screenshot**

Here's an example of macOS' activity monitor showing 11.54 GB of RAM being used by the example app while in the background.

<img width="1440" alt="Screenshot" src="https://user-images.githubusercontent.com/6199781/69887873-5884ce80-12e9-11ea-95ea-7b9208413965.png">

**Standalone, minimal, complete and verifiable example:**

Just compile the app inside `examples/example_glfw_metal` from commit `b205ab01` using GNU Make, run the executable, and place any other application on top of it, covering the entire app, for example Safari, Sublime Text... I found out that any app in full screen invokes this behavior . After that, It will start to memory leak and consume more and more resources pretty much instantaneously.

**Comment by marcizhu** [comment]
I've just tested this with the latest commit (`bf6d1ba`) and it shows the same exact behavior

**Comment by ocornut** [comment]
Hello,
Thank you for reporting. Looks like there is a leak somewhere. Tagging @warrenm who might have an idea?

**Comment by marcizhu** [comment]
Thanks for the quick response!
I agree, this looks like a memory leak, but for some reason it only happens when the app goes into the background. When it's running in the foreground, the app only uses 200-300 Mb, which is perfectly fine.

I'm trying to provide all the information I have in order to fix this. If I discover anything new, I'll post it here :)

**Comment by warrenm** [comment]
Odd. Currently traveling, but will investigate as time allows. In the meantime, does anyone have an Instruments trace indicating where these leaks might originate? Does this  manifest in release builds launched outside Xcode?

**Comment by bear24rw** [comment]
I traced it down to `id<CAMetalDrawable> drawable = [layer nextDrawable];` leaking IOSurfaces.  I think what is happening is that when the window is covered App Nap kicks in (like in https://github.com/ocornut/imgui/issues/1765) which pauses the underlying CFEvent loop which causes the main threads default `autoreleasepool` to not drain (https://stackoverflow.com/a/34263858/253650). It seems[ the recommended way](https://developer.apple.com/library/archive/documentation/3DDrawing/Conceptual/MTLBestPracticesGuide/Drawables.html) is to wrap everything in a `@autoreleasepool` block.

 Unfortunately this is kind of ugly as it adds another nesting level, maybe there is a better solution? I pushed [a branch](https://github.com/bear24rw/imgui/tree/metal_autoreleasepool ) that adds the `@autoreleasepool` wrapper if we want to go with that (https://github.com/bear24rw/imgui/commit/90d2b0066be487e81774b4bceb206b9837645fe7).

**Comment by warrenm** [comment]
That’s the conclusion I came to as well, and I think this is the correct solution.

**Comment by ocornut** [comment]
Max fix is now merged, thanks a lot!
I agree it looks a little bit fishy to have to do it this way, but I'm not familiar with Metal nor ObjC so I'll trust your judgment on this.
