### ISSUE TITLE
Trees, indentation, and leaf nodes

### ISSUE THREAD

**Issue by v71** [ocornut/imgui#2911]
Hello, after a period of inactivity , i started again using dearimgui, for a project i need a tree , actually i am using this piece of code to recursively draw a tree, but i do not know if i am doing something wrong here, is there a way to indent nicely child nodes , and also i have used a sort of an hack to draw leaf nodes , i have attached the offending piece of code.
thanks
Sorry if i posted in the wrong section

	void DrawModelTree(vml::models::Model3d *model, ImVec4 &TextCol0,int indentspace)
			{
			
				ImGui::Indent(indentspace);
				
				size_t n = model->GetChildCount();

				if (n == 0)
				{
					ImGui::AlignTextToFramePadding();
					ImGui::Indent(indentspace-8);
					ImGui::TextColored(TextCol0, "%s", model->GetScreenName().c_str());
					ImGui::Unindent(indentspace-8);
				}
				else
				{
					if (ImGui::TreeNode(model->GetScreenName().c_str()))
					{

						for (size_t i = 0; i < n; ++i)
						{
							DrawModelTree(model->GetChild(i), TextCol0, indentspace-3);
						}

						ImGui::TreePop();
					}
				}

				ImGui::Unindent(indentspace);
			}

**Comment by v71** [comment]
OK, solved

**Comment by ocornut** [comment]
Would be good to share before/after screenshots and share your solution.

**Comment by v71** [comment]
Just stopped using recursive computed indentation, there was no need after all , current indentation is optimal
