### ISSUE TITLE
Group padding

### ISSUE THREAD

**Issue by TheBoJaN** [ocornut/imgui#2913]
Before I begin, I should note that I'm using ImGui.Net and all my code is C# but as ImGui.Net is just a set of bindings to ImGui it's essentially the same.

I've spent the morning Googling, searching this github page and experimenting and have been unable to find the proper way to set group padding(if one even exists).

I'm trying to turn the following (please try not to get lost in the beauty of my placeholder art!)
![image](https://user-images.githubusercontent.com/3692535/69988720-cf97ae00-1507-11ea-8873-75ed1ac47249.png)

into this:
![image](https://user-images.githubusercontent.com/3692535/69988676-b858c080-1507-11ea-8cd7-2a12b5aa96be.png)

I've come up with a workaround using dummies that works fairly well but obviously comes with some overhead and I'd like to know if there's already a way to pad a group.

You can see my workaround below, with the inner group outlined in teal and the 0x0 dummies in magenta

![image](https://user-images.githubusercontent.com/3692535/69988793-f8b83e80-1507-11ea-9611-3904ed9f3737.png)

If anybody else finds this issue from google, here's the code for the workaround:
```
        public static void BeginPaddedGroup()
        {
            //Outer group
            ImGui.BeginGroup();

            ImGui.Dummy(new Vector2());
            ImGui.Dummy(new Vector2());
            ImGui.SameLine();
                
            //Inner group
            ImGui.BeginGroup();
        }

        public static void EndPaddedGroup()
        {
            //End inner group
            ImGui.EndGroup();

            ImGui.SameLine();
            ImGui.Dummy(new Vector2());
            ImGui.Dummy(new Vector2());

            //End outer group
            ImGui.EndGroup();
        }
```

**Comment by ocornut** [comment]
You could just replace the two dummy + sameline with a single `SetCursorPos(GetCursorPos() + padding)` and that's all you need to do. 

I don't understand why you need the "outer" group there.

Your code could do something like:

```
ImVec2 p0 = GetCursorScreenPos();
SetCursorScreenPos(p0 + padding);
BeginGroup();
...
EndGroup();
ImVec2 p1 = GetItemRectMax() + padding;
Dummy(ImVec2(0.0f, padding.y);
GetWindowDrawList->AddRect(p0, p1, ...);
```

**Comment by TheBoJaN** [comment]
Interesting. I didn't know about the cursor position, I'd just assumed is related to the text cursor/caret and never looked twice. That's a much simpler solution, thanks!

The inner group was so I could push the entire group over rather than putting a dummy at the beginning of each line.
