### ISSUE TITLE
SDL2 OpenGL3 example doesnt render correctly for non-high dpi (OSX)

### ISSUE THREAD

**Issue by prime31** [ocornut/imgui#2916]
**Version/Branch of Dear ImGui:**

Version: 1.74
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl2.cpp
Compiler: c++ from Makefile
Operating System: macOS

**My Issue/Question:**
Making one change in the SDL_Window creation to remove HIGHDPI results in rendering taking up only the bottom 1/4 of the screen and mouse coordinates are off.

original line:
`SDL_WindowFlags window_flags = (SDL_WindowFlags)(SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);`

modified line:
`SDL_WindowFlags window_flags = (SDL_WindowFlags)(SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);`

**Screenshots/Video**

<img width="1392" alt="Screen Shot 2019-12-02 at 5 42 16 PM" src="https://user-images.githubusercontent.com/60377/70013322-11d2e680-152c-11ea-83dc-91445047385f.png">

**Standalone, minimal, complete and verifiable example:**
Simply delete ` | SDL_WINDOW_ALLOW_HIGHDPI` from line 59 in `example_sdl2_opengl3/main.cpp` and run

**Comment by RobertoMalatesta** [comment]
SDL2 version ??

See the code here to get the compiled/linked versions:

[https://wiki.libsdl.org/SDL_GetVersion](https://wiki.libsdl.org/SDL_GetVersion)

Gl3w version ?

--R

**Comment by prime31** [comment]
SDL2 version: `SDL version: 2.0.10`

gl3w is the one in the `examples/libs` folder. I can't seem to find any version number in the source or a method to get it. If you let me know how to fetch it I'll grab it for you.

**Comment by prime31** [comment]
Ok, I actually ran into this in a another project. Looks like the fix may have landed in SDL but isn’t released yet: https://hg.libsdl.org/SDL/rev/46b094f7d20e

**Comment by prime31** [comment]
Closing this out. Turns out it is a bug in SDL fixed in the upcoming release.
