### ISSUE TITLE
1 Frame Delay

### ISSUE THREAD

**Issue by aspioupiou** [ocornut/imgui#2918]
Hi everyone, 
We heavily use ImGui + Magnum. We've noticed some strange behaviour we investigated related to texture display flickering.

We found out that it happens when the textures are resized (we delete and recreate these right after), since ImGui seems to have a 1 frame delay. The easy workaround is to move temporary  the texture.

We're not the only one who noticed this delay but we haven't found the reason (and any documentation) of this 1 Frame push-back. Could anyone give some details about this ?

Cheers,

**Comment by ocornut** [comment]
The render loop is 100% part of Magnum, perhaps Magnum introduce some buffering mechanism. Either way this is a question to ask on Magnum’s side not really here, as dear imgui isn’t really aware of the concept of textures.
