### ISSUE TITLE
Indexed Rendering 65536 Limit per window

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#292]
I understand that it's probably a design decision but I've been hitting the 65536 Index limit inside a single window, due to ImDrawIdx being an unsigned short. I was searching some API to "break" the index chain but looks like there's one unique VTX and IDX buffer per DrawList, and there's one DrawList per Window.
FYI, the reason is that I am drawing a good number of 2D points (as small rectangles) to display edge outlines of an image.
 I could use the usercallback mechanism, but I'm wondering if there's a better way.
Additionally in my opinion the ImDrawList should assert in debug if someone tries to write more than 65536 vertices.
Suggestions?

Here's a good one.
![indexed rendering limit 1](https://cloud.githubusercontent.com/assets/5406873/9117302/7b7e43b8-3c69-11e5-8398-6b0eb1fa896c.jpg)

here's a bad one (more than 65536 indexes), my background image becomes garbage.
![indexed rendering limit 2](https://cloud.githubusercontent.com/assets/5406873/9117303/7ba14dc2-3c69-11e5-8a12-4419692867a8.jpg)

**Comment by ocornut** [comment]
- I will add an assert somewhere.

- We could potentially allow the user to #define ImDrawIdx, that wouldn't be a hard patch probably.Maybe it'll warn/break occasionally.

- Otherwise you can use multiple ImDrawList, we ought to allow to insert them in arbitrary order but if you create child windows it'll allow that.

PS: I'd like to see a full resolution version of those picture! :)

**Comment by adamdmoss** [comment]
FYI I hit this too!  I decided that I didn't much care, for my use, but a relatively simple workaround would also be pleasant.

**Comment by ocornut** [comment]
What did you do to hit this Adam?

**Comment by Pagghiu** [comment]
Hi Omar, I did it as you've been suggesting (ChildWindows) and it works perfectly!
Something like this
```cpp
//...
	int currentChild = 0;
	ImVec2 wpos = ImGui::GetWindowPos();
	ImVec2 backupPos = ImGui::GetCursorScreenPos();
	ImGui::SetCursorScreenPos(wpos);
	ImGui::BeginChild(currentChild++);
	ImDrawList* draw_list = ImGui::GetWindowDrawList();
	int numberOfPoints = pDlg->cv.getObject(foundObject)->_numVerifyPts;
	double* pX = pDlg->cv.getObject(foundObject)->_aVerifyPtsX;
	double* pY = pDlg->cv.getObject(foundObject)->_aVerifyPtsY;
	for (int i = 0; i < numberOfPoints; i++)
	{
		float x = static_cast<float>(pX[i]);
		float y = static_cast<float>(pY[i]);
		x *= zoom;
		y *= zoom;
		x += topLeftScreen.x;
		y += topLeftScreen.y;

		const float w = 1.0f;
		ImVec2 minR(x - w, y - w), maxR(x + w, y + w);
		draw_list->AddRectFilled(minR, maxR,ImColor(0,255,0,128));
		if (draw_list->_VtxCurrentIdx > 65536 - 8)
		{
			ImGui::EndChild();
			ImGui::SetCursorScreenPos(wpos);
			ImGui::BeginChild(currentChild++);
			draw_list = ImGui::GetWindowDrawList();
		}
	}
	
	ImGui::EndChild();
	ImGui::SetCursorScreenPos(backupPos);
//...
```

I'm also attaching some screenshot of our Robotic Visual Guidance software (CortexRecognition:registered: ), as you're requesting ;)

It's a world class 6DOF robotic guidance solution !
Basically it's able to find from an arbitrary image, the type and location of a taught model in 6 Degrees of freedom using real millimeters and degrees. With this information you can send a robot to go and pick parts or other kind of processes. We're in the process of enhancing our website and building some new professional videos, but if you're curious you can watch those. I'm talking about real robots, not virtual ones from videogames! :space_invader:  

https://www.youtube.com/watch?v=ebob20egGjE
https://www.youtube.com/watch?v=vjlULbJYeM0

(those old videos are not featuring the new IMGUI UI...but the upcoming ones will!)

![cortex recognition 1](https://cloud.githubusercontent.com/assets/5406873/9145715/0383c0c4-3d57-11e5-88a9-acc61bd70ce5.jpeg)
![cortex recognition 2](https://cloud.githubusercontent.com/assets/5406873/9145717/03b9c214-3d57-11e5-94f3-a51bc82322d6.jpeg)
![cortex recognition 3](https://cloud.githubusercontent.com/assets/5406873/9145720/042db50c-3d57-11e5-8efc-3607f8b87048.jpeg)
![cortex recognition 4](https://cloud.githubusercontent.com/assets/5406873/9145721/0452a1be-3d57-11e5-8aff-8fb360f929ce.jpeg)
![cortex recognition 5](https://cloud.githubusercontent.com/assets/5406873/9145718/03bb88f6-3d57-11e5-8b62-6d19321d8686.jpeg)
![cortex recognition 6](https://cloud.githubusercontent.com/assets/5406873/9145719/0423ad96-3d57-11e5-8965-54c1b04795ea.jpeg)
![cortex recognition 7](https://cloud.githubusercontent.com/assets/5406873/9145716/03a9936c-3d57-11e5-9ff5-225e348e4480.jpeg)

**Comment by ocornut** [comment]
Thanks for the screenshots!

I have added an assert and the possibility to override ImDrawIdx with a different type. Tested with unsigned int and it works (of course you need to adjust your draw function accordingly).

**Comment by ocornut** [comment]
There's now another solution to this, see #2591
