### ISSUE TITLE
Failing to render with DX12 back-end (help wanted!)

### ISSUE THREAD

**Issue by BobMowzie** [ocornut/imgui#2921]
**Version/Branch of Dear ImGui:**

Version: 1.75
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx12.cpp + imgui_impl_win32.cpp 
Compiler: MSVC (Visual Studio 2017)
Operating System: Windows 10 x64

**My Issue/Question:**

Hello! I'm desperate for help with Imgui for a school assignment due very very soon. None of my professors or TAs have been able to identify the issue, and the Discord server community wasn't able to find the problem either. So, I'm creating an issue on the github as my last resort.
I'm developing a DXR project and have integrated and set up ImGUI with the project. However, although tracing calls shows that ImGUI is successfully rendering, absolutely no GUI appears in my window. I can see my raytraced scene, but ImGUI is not drawing. I'm completely at a loss as to why.

I may be simply missing a call somewhere in my setup, but I looked very thoroughly and found nothing. I'm fairly new to the pipeline side of things, so I may have made a mistake there. In either of these cases, I'm sorry to have wasted your time. However, I'm fairly sure something more involved is wrong.

https://github.com/aleward/Pudgy-Pals-Build-2.0.0-Even-Pudgier/blob/master/dxrProject5/src/D3D12RaytracingProceduralGeometry/DXR-Other.cpp
Most of the implementation can be found here. Pardon the confusing code; it's a group project frankensteined together from previous classwork and other people's code.

Any help is appreciated! Thanks!

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing until fixed.

**Comment by BobMowzie** [comment]
Sorry about that! Updated with format.

**Comment by ocornut** [comment]
@BobMowzie Have you been able to solve your issue?

**Comment by BobMowzie** [comment]
Unfortunately, no. We bound our menu options to key presses instead and submitted the project. But thank you for following up.

**Comment by ocornut** [comment]
If you don't have need for a fix can we close this for now?
GFX issues can be tricky to fix but it would be good to eventually find the reason.  It'll eventually pop back in different circumstance and maybe we'll have more hints about what happens.
Using GPU debugger such as RenderDoc may help track the issue.

**Comment by BobMowzie** [comment]
Sure, yes. That would be fine.
