### ISSUE TITLE
GLFW Errors with current master

### ISSUE THREAD

**Issue by Mutaru16bit** [ocornut/imgui#2922]
Linux x86_64

this error occurs when the glfw/opengl3 build

here is output from the glfw/opengl3 example when using provided makefile:

![Untitled](https://user-images.githubusercontent.com/40045935/70325392-1bd83c00-17ef-11ea-815f-a2e2d99b459e.png)

**Comment by rokups** [comment]
What GLFW version are you using?

**Comment by Mutaru16bit** [comment]
3.3+

**Comment by rokups** [comment]
Could you be more precise? I would like to test that exact version.

**Comment by Mutaru16bit** [comment]
it still builds using older versions of Dear Imgui

**Comment by rokups** [comment]
Please list `GLFW_VERSION_MAJOR` and `GLFW_VERSION_MINOR` define values you have.

**Comment by rokups** [comment]
Actually.. Do you happen to use a custom-built glfw version from git? This would explain the failure. Code path that breaks is enabled only for glfw 3.4+ which is not released yet. You could have a version that identifies as 3.4 but does not have new cursor functionality. It is very fresh.

**Comment by Mutaru16bit** [comment]
that might be the issue, I'm running Manjaro Linux and its glfw is built from git

**Comment by rokups** [comment]
Alright. Reinstalling glfw should fetch latest code with needed changes and fix your issue.

**Comment by Mutaru16bit** [comment]
but I also tested it myself and it builds fine with older versions of the Imgui Master

**Comment by rokups** [comment]
Of course. Older versions did not support these new cursors that were added to glfw just days ago.

**Comment by Mutaru16bit** [comment]
glfw is latest master version

**Comment by Mutaru16bit** [comment]
two versions installed in two locations and pkg-config was selecting the .pc file for the older one

**Comment by Mutaru16bit** [comment]
sorry, my dev environment is a mess.

**Comment by ocornut** [comment]
We pushed a workaround for this, being considerate that there's a 7 months period where any GLFW version pulled straight from master/ would have had the same issue.
Thanks for reporting!
