### ISSUE TITLE
Align the framed text of items inside popup

### ISSUE THREAD

**Issue by eax0r** [ocornut/imgui#2924]
**Version/Branch of Dear ImGui:**

Version: 1.75 WIP (17401)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: MSVC (Visual Studio 2019)
Operating System: Windows 10 x64

**My Issue/Question:**

I have spent some time now to find a proper way to adjust the framed text of items when using **e.g. combo boxes**, I am only able to modify the `const char* preview_value`, as it is directly rendered with `RenderTextClipped`, but when it comes to the **items displayed inside the actual popup**, I have not found yet the right way to adjust the padding of it.

In the verifiable example below, I am trying to modify the actual padding, although I am trying to make it work directly in my wrapper functions, and not actually manually pushing anything with the API.

I would actually like to being able to push a style variable, like it should actually make sense if it was `FramePadding` or something like `PopupTextAlign`, to pad my strings without interacting with the actual frame.

(I also tried to use the standard library, but this is obviously not how you do it properly nor pixel perfect.)

So in the end, I just want to be able to horizontally align the framed text of my items inside the popup_window of `ImGui::BeginCombo`, or even other widgets using popup.

**Screenshots/Video**

![Align_ccombo](https://user-images.githubusercontent.com/55549616/70387121-5da8e400-19a1-11ea-93b0-37eb5283332a.png)

**1**. This is the base popup with the window padding reset, `ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0,0));`

**2**. This is when I try to change the position of my item `const char** out_text`, with e.g. `ImGui::SetCursorPosX(ImGui::GetCursorPosX() + 10);`

**3**. This is what I want to achieve with **the most appropriate way**.

**Standalone, minimal, complete and verifiable example:**

```
ImGui::Combo("Combo box 1", &current_item, "Off\0Adaptive");
```
```
static const char* items[]{ "Off", "Adaptive" };
ImGui::Combo("Combo box 1", &current_item, [](void* data, int idx, const char** out_text)
{
	if (current_item.enabled)
	{
		ImGui::SetCursorPosX(ImGui::GetCursorPosX() + 10);
		*out_text = items[idx];
	}
	else
	{
		*out_text = items[idx];
	}
	return true;
}, nullptr, IM_ARRAYSIZE(items));
```
```
static const char* items[]{ "Off", "Adaptive" };
ImGui::Combo("Combo box 1", &current_item, [](void* data, int idx, const char** out_text)
{
	if (current_item.enabled)
	{
		static std::string name;
		name = items[idx];
		*out_text = name.insert(0, 4, ' ');
	}
	else
	{
		*out_text = items[idx];
	}
	return true;
}, nullptr, IM_ARRAYSIZE(items));
```

**Comment by ocornut** [comment]
Hello,

You mention `BeginCombo()` in your description but it's not in your repro code?
If you use BeginCombo instead of Combo you'll more more flexibility to submit items however you want them.

The tricky thing is that BeginCombo() does:

```
// Horizontally align ourselves with the framed text
PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(style.FramePadding.x, style.WindowPadding.y));
bool ret = Begin(name, NULL, window_flags);
PopStyleVar();
```

So we overwrite WindowPadding.x with FramePadding.x in order for items in the combo to be aligned with the item in preview. Because of this you have some spacing on the edges of the popup. 

Workaround would be:
- Using `PushClipRect()` you can push a clip rect that cover edge of the window.
- Set FramePadding.x=0 and set item position

Additionally, Selectable() have a specific behavior where they aim to fill the spacing gaps between selectables, in both axis, which generally means adding ItemSpacing*0.5 on each side, which for you making things a little more tricky.

In your picture you are not showing the current/default case which would be to have a little spacing between the edge of the window and more padding in the highlight, this is working well in most situation and is consistent with everything else in Dear ImGui, so it's not clear why you want to stray away from that consistency.

**Comment by eax0r** [comment]
Thanks a lot for your detailed answer @ocornut.

I indeed forgot about `PushClipRect()`, and in my case it would do the trick easily.

> You mention BeginCombo() in your description but it's not in your repro code?

My bad, I am using the latest API but as I have already heavily modified it in my wrapper I didn't want to post the repro code associated with, I just wanted to point out the behavior. (and for some reason I used the old API, habit)

> In your picture you are not showing the current/default case which would be to have a little spacing between the edge of the window and more padding in the highlight, this is working well in most situation and is consistent with everything else in Dear ImGui, so it's not clear why you want to stray away from that consistency.

Well, it is for styling purposes only, in order to fit the current design of my packet analyzer, but I could stay just fine with the default behavior.

> In your picture you are not showing the current/default case which would be to have a little spacing between the edge of the window and more padding in the highlight, this is working well in most situation and is consistent with everything else in Dear ImGui, so it's not clear why you want to stray away from that consistency.

I have reset the window padding, and it is only showing the popup part of my combo, I should have post a better picture.

**Comment by eax0r** [comment]
![captureint_vpn](https://user-images.githubusercontent.com/55549616/70497028-09714180-1b12-11ea-9916-6b4948ac61fb.png)

@ocornut, so a little update, it worked out for my needs, and I kept the default WindowPadding.x overwrite, using of course the general api (and did remove all references of the old Combo() api in my wrapper).

```
const char *interfaces[] = { "ipsec0", "ipsec1", "ipsec2", "ipsec3", "ipsec4", "any" };
	if (ImGui::BeginCombo("Capture", interfaces[settings.network.interfaces], ImGuiComboFlags_None))
	{
		for (int i = 0; i < IM_ARRAYSIZE(interfaces); i++)
		{
			bool is_selected = settings.network.interfaces == i;
			if (ImGui::Selectable(interfaces[i], &is_selected))
				settings.network.interfaces = i;
			if (is_selected)
				ImGui::SetItemDefaultFocus();
		}
			ImGui::EndCombo();
	}
```

Sorry if my issue was irrelevant for you, and thanks for your time, let me know if I have to close the issue.

Regards,
