### ISSUE TITLE
How to convert Css Design to ImGui ?

### ISSUE THREAD

**Issue by bytech043** [ocornut/imgui#2928]
How I Convert Css Design To ImGui ? 
Is This Possible ?
if this possible How I Do
Example : Css Design Checkbox,Button,Slider (Have Animation etc.)

if this possible Please help me.

**Comment by ocornut** [comment]
Not possible.

Also:
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
Closing.
