### ISSUE TITLE
support stateful user functions

### ISSUE THREAD

**Issue by usagi** [ocornut/imgui#293]
I want to use stateful [user functions](https://github.com/ocornut/imgui/blob/a793ad682d5509c6354ab40ac73bbd365c32322d/imgui.h#L674) as below:

```c++
// my needs
ImGui::GetIO();
io.SetClipboardTextFn =
  [some_glfw3_window_handle](const char* text)
  { glfwSetClipboardString( some_glfw3_window_handle, text ); };
```

But, current implement cannot support stateful functor objects(a `operator()` implemented object and a stateful labmda-expression). Thus, I propose there:

- Change an user function type to the `std::function` type from the function pointer type.

I prepare the change sample and pull-request, short time later.

**Comment by ocornut** [comment]
I'm sorry I cannot take this:

- That would break compilation for everyone.
- std::function is c++11 and we don't rely on that for portability. std::function is less compatible, less portable, more confusing to a variety of users, and less efficient.
- We don't use any c++ libraries apart from new().

- Also and mainly, every bit of ImGui are based around a global context pointer anyway (which the user can swap), So you can store your window handle globally it won't make a difference, or use UserData in ImGuiIO (or we can add more to ImGuiIO).

**Comment by paulsapps** [comment]
If you are using C++11 then you can just use a lamba without changing anything:

void* some_glfw3_window_handle = nullptr; // this can be used from the lamba :)
io.SetClipboardTextFn = [&](const char* text)
{
glfwSetClipboardString( some_glfw3_window_handle, text );
};

**Comment by usagi** [comment]
@ocornut 

Okay, I understood your ImGui policy. I close the issue and I'll try the other solutions. Thanks.

-----

@paulsapps 

Sorry, we cannot use your propose because the C-style function pointer object cannot use a stateful-lambda object(it cannot convert to a function pointer from a stateful-lambda, it can convert a stateless lambda only) in C++11 or later(C++14). 

You can read the C++ specification, see the "S.5.1.2 Lambda expressions":

> The closure type for a non-generic lambda-expression with no lambda-capture has a public non-virtual nonexplicit const conversion function to pointer to function with C++ language linkage (7.5) having the same parameter and return types as the closure type’s function call operator.

**Comment by ocornut** [comment]
Thanks. Sorry, we need to avoid c++11 for a library as it's not really supported by all platforms (for example the Wii-U / 3DS compilers) and those support on console are generally of variable quality.
