### ISSUE TITLE
I Do Press Press Game ? How I Show my score on ImGui::Text ?

### ISSUE THREAD

**Issue by GameCreatorGitGit** [ocornut/imgui#2930]
My Code İs 
`float sag = 24;
float yukari = 80;
#include <iostream>
#include <cstdio>
#include <ctime>

int score = 0;
std::string str = std::to_string(score);
const char* cstr = str.c_str();
bool gamestart = true;
void Gamegameptr()
{

	ImGui::BeginChild("##gamearea", ImVec2(0, 0), ImGuiSetCond_FirstUseEver, false);
	ImGui::Text(u8"Score :");
	ImGui::SameLine();
	
	ImGui::TextColored(ImVec4(0.20f, 0.24f, 0.52f, 1.00f), cstr);

	ImGui::SameLine();
	ImGui::Text(u8"User :");
	ImGui::SameLine();
	ImGui::TextColored(ImColor(5, 213, 255), u8"%s", username);

	ImGui::Separator();
	ImGui::SetCursorPos(ImVec2(sag,yukari));
	if (ImGui::Button("Add 5 Score", ImVec2(15, 15)))
	{
		score += 5;
		cstr = str.c_str();
	}
	ImGui::EndChild();
}
`

But I Pressed Can't add or show on Score Table.

Help Me Please. Thanks.

**Comment by GameCreatorGitGit** [comment]
or How i make snake game on ImGui Menus

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
Closing, Blocked.
