### ISSUE TITLE
Thread safety of ImGui::* draw calls?

### ISSUE THREAD

**Issue by famastefano** [ocornut/imgui#2932]
**Version/Branch of Dear ImGui:**

Version: 1.74 and future (stable only)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: Win32 + DirectX 11 custom game engine backend
Compiler: MSVC (Visual Studio 2019 latest stable)
Operating System: Windows 10 x64

**My Question:**

I'm in the design phase of a custom game engine written in C++ and DirectX 11, targeting Windows 10 x64 with the Win32 interface.
I'm planning to use Dear ImGui for both the Game Engine (Visual Script Editor UE4-like + UI) and in-game UI.
I will use a 3rd party, production ready, ECS and design everything around that.
> What if I have multiple UI components, be it nodes or whatever from the visual script editor or in-game UI, and I call ImGui::* functions from separate threads?

As far as I've understood, ImGui creates draw commands that are issued to the backend.
DirectX 11 has the nice feature of Deferred Contexts:

> Deferred contexts differ from the immediate context in that the commands that the deferred contexts record cannot be executed until the application explicitly requests to execute the commands, by executing the generated command list.

But that's part of the backend.
I'm wondering if ImGui has some kind of synchronization available to generate commands in separate threads.

**Example (pseudo code):**
```
// Each system in the ECS potentially runs on different threads and might spawn additional tasks (threadpool based)

void node_drawer_system()
{
    auto node_list = ECS::get_nodes_to_draw();
    for(auto& node : node_list)
        node.draw();
}

void draw_visual_script_ui_system()
{
    auto ui_list = ECS::get_ui_to_draw();
    for(auto& ui : ui_list)
        ui.draw();
}
```

Maybe the list of components to draw is small, so I won't parallelize the draw calls, but different components types might run concurrently.

**Comment by ocornut** [comment]
Hello,

> I'm wondering if ImGui has some kind of synchronization available to generate commands in separate threads.

Not presently and unlikely in near to mid future. 
The `ImGui::` api is not thread safe unless you have **multiple** Dear ImGui contexts and `#define` GImGui to access a TLS pointer with different context on each thread.

**Comment by ocornut** [comment]
Closing this as answered, no reaction from original poster.
