### ISSUE TITLE
Threat detected on example application

### ISSUE THREAD

**Issue by ironfey** [ocornut/imgui#2933]
I just cloned the repo and build the example application. This trigger GData Anti Virus when trying to execute it. I did an upload to VirusTotal and several scanners have problems with the freshly built executable
https://www.virustotal.com/gui/file/fe666def6198c11dd6642dc7b58140c5a02eba885d6c3f8f799052d5ed3fa2a4/detection

**Comment by ocornut** [comment]
Hello Felix,
Then it means you probably have a virus on your machine.

**Comment by ocornut** [comment]
Here's my own upload: https://www.virustotal.com/gui/file/38b98977cbc0154f66cc8ea260ab33bc2c9fb6b1e0f4c8b27d2a0332be0c7fe4/detection

**Comment by ironfey** [comment]
All right will check further
