### ISSUE TITLE
How to display "##" characters within UI-Elements (e.g. Selectable)

### ISSUE THREAD

**Issue by irieger** [ocornut/imgui#2936]
```
Dear ImGui 1.74 (17400)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=9
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: GCC 9.2.1
Operating System: Ubuntu 19.10

**My Issue/Question:**

Hey,

after trying to find a proper documentation in the FAQ/Header/Doku-Part of the imgui.cpp I decided to come here with a short user request. I build a file dialog menu where each entry is represented by a Selectable. File sequences like "some_images_0001.tiff" to "some_images_0151.tiff" are represented as "some_images_####.tiff [1-151]".

I think you know where the problem is. At first I was wondering why the string suddenly ends and then realized, that of course imgui interprets it as the label. Is there a way to disable this behaviour or escape '#' characters?

Short code sample to reproduce I just added:
```
ImGui::Begin("Selectable demo");
static bool foobar1 = false;
static bool foobar2 = true;
// The following string gets cut by as ## is interpreted for label definition
ImGui::Selectable("this_is_not_working_#####.tif", &foobar1);
ImGui::Selectable("this_of_course_is.tif", &foobar2);
ImGui::End();
```

**Comment by ocornut** [comment]
There's no general way unless the function takes an explicit start/end pointer.
A workaround is the following:

Use something like:

```
ImVec2 p = ImGui::GetCursorScreenPos();
ImGui::Selectable("##EmptyLabel");
ImGui::SetCursorScreenPos(p);
ImGui::TextUnformatted("this_should_be_working_now_####.tif");
```

**Comment by irieger** [comment]
Cool, thank you very much. Seems to work just fine.
