### ISSUE TITLE
Text Render Issues

### ISSUE THREAD

**Issue by crazydef** [ocornut/imgui#2939]
I'm seeing some minor artefacts when rendering text with a reasonably large font (in this case 48 pixels high, segoe ui in Windows):

![image](https://user-images.githubusercontent.com/22217579/71257855-102f5e00-2335-11ea-9945-f35d1025d26f.png)

The tops of the uppercase letters COG and the number 0 appear to be clipped.

I'm also seeing artefacts most probably caused by rounding errors with UV coordinates on the right side of the `k`, and on both sides of the degree symbol, `°`:

![image](https://user-images.githubusercontent.com/22217579/71258253-022e0d00-2336-11ea-9635-8065c56f653e.png)

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
Closing until fixed.
