### ISSUE TITLE
Constrain height of expanded CollapsingHeader

### ISSUE THREAD

**Issue by pvtinflex** [ocornut/imgui#2947]
I want to be able to limit the expanded height of a collapsing header to a specific size; I've just updated to the latest ImGui and I see there's been a few changes to the API ( not that I knew how to do it before either ).

In the image, the |> Board Notes header flows beyond the bottom of the window, I'd like to be able to constrain that back to a lesser height.

Code for that header is ... 
```
	if (obdata.notes.size() > 0) {
		if (ImGui::CollapsingHeader("Board Notes")) {
			ExpandOBDataNotes( &obdata.notes, 1, 0 );
		}
	}
```

![s](https://user-images.githubusercontent.com/39491273/71387294-ea5cce80-263e-11ea-8d48-f6b053ed56c4.png)

**Comment by ocornut** [comment]
Hello,

Collapsing Header have no height per-se, they don't "contains" the contents following them.
You can use a `BeginChild`/`EndChild` block to create a scrolling region which you can configure of height of.

(PS: Please free requested issue template when creating new issue, thank you.)

**Comment by pvtinflex** [comment]
Thank you.
