### ISSUE TITLE
Need advice on Tab handling

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#2951]
**Version/Branch of Dear ImGui:**

Version: v1.70
Branch: master 

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui.net
Operating System: win10

**My Issue/Question:**
We implemented a custom version of DragFloat1,2,3,4 etc. (see screen capture below). Most of the implementation was straight forward. But I'm lost on how to implement tabbing for the vector parameters.

Currently the component holds an internal state to switch between drag input (a Button) and text input. So if the first float input is in text-mode the component looks basically like...

```
ImGui.InputText(); //<-focused
ImGui.SameLine();
ImGui.Button();
ImGui.SameLine();
ImgGui.Button();
```

I would assume that the second button actually could receive focus. But I'm not sure how.

**Screenshots/Video**

**Standalone, minimal, complete and verifiable example:**
I could post the 300 lines source code of the component, if it would be helpful.
![parameter-view-test](https://user-images.githubusercontent.com/1732545/71518580-e4bbee80-28b3-11ea-9035-db745ebd5ef1.gif)

**Comment by ocornut** [comment]
Hello,

You want to be looking at how `SliderScalar()` and `DragScalar()` are registering themselves into the tab list. They call `FocusableItemRegister()`. 

Also see how they call `TempInputTextIsActive()` and `TempInputTextScalar()` (those later two functions after used for the helper that create a temporary InputText, have been renamed and reworked slightly recently so they'll be named differently in 1.70).

This API will be entirely redone as I have some plans to rework the whole focusing system this is why it's all private API for now, but by the time they are redone things will make a lot more sense and it shouldn't be too much trouble to update.

Posting your widget source could be nice, I'd like in the future to promote the creation of more custom widgets and it's great to see this kind of stuff being done publicly. Even as-is, the GIF should be pretty inspiring for many.

**Comment by pixtur** [comment]
Darn, it looks like `FocusableItemRegister()` ist not available from ImGui.net.

Would it be possible to make Buttons explictly focusable (like web browsers do with <button/>)? Since they can be selected through keyboard navigation this seems like the expected behavior, anyways.

I posted a gist of the code [here](https://gist.github.com/pixtur/c5af8d98e8f26442c8319e303fdd0d47):

**Comment by ocornut** [comment]
None of the `imgui_internal.h` stuff are exposed in cimgui nor ImGui.Net (see https://github.com/cimgui/cimgui/issues/108)

The current tabbing system was designed a long time ago before navigation was more generally introduced. Yes we should have more general support for Tabbing through everything. I have a private branch with an early design for that but there were a few problems and it's unfinished work. Presumably I made that branch much harder to implement because I was redesigning remote activation/focus API at the same time (being able to focus or activate a button given an ID) and that got complicated. I'll have to see if I could finish until the tabbing part first.

**Comment by pixtur** [comment]
Advanced keyboard navigation would be really powerful. Imgui already comes very close to an ideal solution. So I'm really looking forward to the refined API.

Maybe as a workaround, I could render invisible `InputText` controls that trigger the activation state for the component. Although a dirty hack, it would not be the ugliest thing I have done so far with ImGui.

**Comment by sonoro1234** [comment]
> I could post the 300 lines source code of the component, if it would be helpful.

I am most interested in that AntTweakBar style knob behaviour used in your camera position!!
