### ISSUE TITLE
Demo details and several other things

### ISSUE THREAD

**Issue by OneArb** [ocornut/imgui#2952]
Version: 1.63 WIP
engine orx
GCC / clang
Linux

Thanks for sharing ImGui. I love designing GUI and am looking forward to customizing widgets to the minute level!

Follows the first tidbits, I have encountered so far:

-1) What would be the best way to indent text within `ImGui::Text`?

I wanted to use `\t` but where would I set the number of characters for a tab within ImGui?

-2) In multi-line Text Input,  would SHIFT+TAB be expected to remove a tab?

-3) In Basic Widgets - input text, a few keyboard features stated in USER GUIDE and (?) remain to be implemented:

CTRL+Left/Right
CTRL+A
undo/redo
clipboard

Basic Widgets - input int, arithmetic operators can be typed in and remain to compute.

-4) "Another Window" in the demo, will not close, nor be movable, even when adding a flag set to 0.

I enjoy the library.

Thanks

**Comment by ocornut** [comment]
Hello @OneArb,

In the future please try to open separate issues for unrelated questions or use the Discord server, thank you. Also note your version of Dear ImGui is 16 months old.

> 1) What would be the best way to indent text within ImGui::Text?

You can use `Indent()`/`Unindent()`, or `SetCursorPosX(100.0f)` or sometimes `SameLine(100.0f)` they are variety of ways and no "best way" it depends on what exactly you are done.

> 2) In multi-line Text Input, would SHIFT+TAB be expected to remove a tab?

That's not implemented/expected but I realize some editors support that so we could add it, but the precise behavior of how it should behave in regards has yet to be designed (maybe we can try to mimic Visual Studio). Note that TAB input within text fields is only enabled when using the ImGuiInputTextFlags_AllowTabInput` flag.

> 3) -3) In Basic Widgets - input text, a few keyboard features stated in USER GUIDE and (?) remain to be implemented:

All those things works. If it doesn't work there's probably a bug in your Orx bindings (maybe the CTRL key is not set correctly by the bindings, maybe it doesn't handle Clipboard properly?). The Orx bindings found in the Wiki seems to be handling those well by skimming sources.

> Basic Widgets - input int, arithmetic operators can be typed in and remain to compute.

I don't understand this.

> 4) "Another Window" in the demo, will not close, nor be movable, even when adding a flag set to 0.

I can't reproduce this bug and I don't see a reason for it happening.

**Comment by OneArb** [comment]
Hello @ocornut,

Thanks for directing me to Discord.

> You can use Indent()/Unindent(), or SetCursorPosX(100.0f) or sometimes SameLine(100.0f) 

I was looking to add an offset to the cursor at the end of the preceeding widget.
`ImGui::SetCursorPosX((ImGui::GetCursorPosX() +5))` does it.

> SHIFT+TAB 

I use `Shift+TAB` all the time to unindent a group of lines (Notepad++, CodeLite, Code::Blocks). I like when I can unindent regardless of the cursor position in the line. Best way to have it work one's way is it implement oneself...

> All those things works. If it doesn't work there's probably a bug in your Orx bindings (maybe the CTRL key is not set correctly by the bindings, maybe it doesn't handle Clipboard properly?). 

Solved. I tracked the issue, the Linux "locate pointer" feature "Show position of pointer when Control key pressed" changed the control key behavior in Orx (though not in the OS). The control key would only work when the Shift key was pressed at the same time.

>   Basic Widgets - input int, arithmetic operators can be typed in and remain to compute.

> I don't understand this.

I refer to Dear ImGui Demo - Basic Widgets - input int
According to (?) help
You can apply arithmetic operators +,*,/ on numerical values. Use +- to subtract.

This widget do not compute arithmetic operators on my 1.75 WIP demo version.

> "Another Window" in the demo, will not close, nor be movable, even when adding a flag set to 0.

> I can't reproduce this bug and I don't see a reason for it happening, afaik it always worked.

I'll get around to investigate that issue. I presume the first step is to track a close window event and a move window event?
