### ISSUE TITLE
Introduction of Java binding

### ISSUE THREAD

**Issue by SpaiR** [ocornut/imgui#2961]
Repository: [SpaiR/imgui-java](https://github.com/SpaiR/imgui-java)

Binding uses native access to do a direct calls to the Dear-ImGui API. It has everything to work, with pre-compiled binaries for different operation systems (win32/64, linux32/64). Small snippet in the README file shows how to start an example app in a three commands.

It supports most of the ImGui features. Some of the very specific stuff is still in a wip, but what is available is enough to build complex UI solutions.

Binding provides OpenGL implementation (port of the imgui_impl_opengl3) and provides the example which shows how to use it (port of the imgui_impl_glfw). But it doesn't force to use it, so users can use their own renderer if they need so.

It also has a partly ported original documentation in a form of javadoc, so users can refer to it.

Speaking about the binding API itself, it fully mirrors the original ImGui API (with respect to overloaded methods), with differences where it's needed to work in Java.

**Comment by ocornut** [comment]
Added to Wiki> Bindings section! Thanks!

**Comment by SpaiR** [comment]
Ok. Then I'm closing the issue. And by the way, thanks to YOU for your amazing work!
