### ISSUE TITLE
I want make rainbowbar to stick to the frame.

### ISSUE THREAD

**Issue by union2589** [ocornut/imgui#2963]
![giphy](https://user-images.githubusercontent.com/49794479/71764293-bd4ecc80-2f18-11ea-8688-99f17c061a90.gif)

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
