### ISSUE TITLE
How to make window stick with main viewport? (backdrop, background)

### ISSUE THREAD

**Issue by hippyau** [ocornut/imgui#2966]
Version: 1.75 WIP
Branch: Docking     (Via CImGui Docking Branch)

DX11/Win10/VS2015

**My Issue/Question:**

I show a logo on my ImGui desktop.  it's a window itself with the logo image drawn with ImDrawList_AddImage.  This was the first thing drawn in my loop. It worked great, but now it is it's own window in docking, and I've lost control of it.

Best way to show image on main window background?
or...
How to make window stick to main window?

I tried ImGuiWindowFlags_NoDocking

My Window:  (excuse the PureBasic, which is working fine...)

```
; main loop
.........
 ;desktop window, show a logo, center it up
  IgSetNextWindowPos(0,#MainMenuBarHeight+1);
  IgSetNextWindowSize(*ImGuiIO\DisplaySize\X,*ImGuiIO\DisplaySize\Y);
  
  igPushStyleColor(#ImGuiCol_WindowBg,0,0,0,0)
  igBegin("###Desktop", #Null,#ImGuiWindowFlags_NoFocusOnAppearing|#ImGuiWindowFlags_NoBringToFrontOnFocus| #ImGuiWindowFlags_NoTitleBar|#ImGuiWindowFlags_NoResize|#ImGuiWindowFlags_NoMove|#ImGuiWindowFlags_NoScrollbar|#ImGuiWindowFlags_NoScrollWithMouse);
  Protected logox = (*ImGuiIO\DisplaySize\X/2)-(img_logo_large\w/2)
  Protected logoy = ((*ImGuiIO\DisplaySize\Y+#MainMenuBarHeight+1)/2)-(img_logo_large\h/2) + #MainMenuBarHeight+1
  ImDrawList_AddImage(igGetWindowDrawList(),img_logo_large\tex, logox,logoy, logox+img_logo_large\w,logoy+img_logo_large\h)
  igPopStyleColor(1)
```

This used to work fine, but in docking the ###Desktop window is not tied to the main window.

PS>  I've written a new API generator in PureBasic, for binding CImGui with PureBasic, which I'll publish shortly. :)

New Years Cheers,
 Hippy  <3

**Comment by ocornut** [comment]
I don't think your question has something to do with Docking, but rather with Multi-Viewports?

You can use GetMainViewport()->Pos/Size for position reference. (0,0) is desktop position.
And SetNextWindowViewport(GetMainViewport()->ID) as wlel.

**Comment by hippyau** [comment]
Brilliant!  You are right, this resolved my issue.   Many thanks :)
