### ISSUE TITLE
vcpkg imgui and imgui-sfml assertion failure

### ISSUE THREAD

**Issue by esduran** [ocornut/imgui#2967]
**Version/Branch of Dear ImGui:**

Version: vcpkg x64-windows 1.73-1
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: Used With SFML and imgui-SFML
Compiler: Visual Studio Community 2019 (MSVC 16)
Operating System: Windows 10 64-bit

**My Issue/Question:**

When running my application in x64-Debug I get:
`Assertion failed: g.FrameScopeActive, file C:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\imgui.cpp, line 5400`
only when I add `ImGui::Begin` and `ImGui::End` calls to my source file.

I am attempting to start a new C++ project using vcpkg, CMake, and Visual Studio on windows. I installed the following packages through vcpkg:

-  imgui-sfml:x64-windows    v2.1
- imgui:x64-windows   v1.73-1
- sfml:x64-windows   v2.5.1-4

In my _CMakeLists.txt_ I include the following:
```
...
find_package(SFML CONFIG COMPONENTS REQUIRED windows graphics system)
find_package(imgui CONFIG REQUIRED)
find_package(ImGui-SFML CONFIG REQUIRED)
...
add_executable(main app/main.cpp)
target_link_libraries(main
                                PRIVATE imgui::imgui
                                              ImGui-SFML::ImGui-SFML
                                             sfml-system
                                             sfml-window
                                             sfml-graphics)
```

My _main.cpp_ file consists of the following:
```c++
#include <imgui.h>
#include <imgui-SFML.h>

#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/System/Clock.hpp>
#include <SFML/Window/Event.hpp>

int main()
{
	// Setup ImGui context
	ImGui::CreateContext();
	sf::RenderWindow window(sf::VideoMode(640, 480), "Test GUI");
	ImGui::SFML::Init(window);

	sf::Clock deltaClock;

	while (window.isOpen()) {
		sf::Event event{};
		while (window.pollEvent(event)) {
			ImGui::SFML::ProcessEvent(event);

			if (event.type == sf::Event::Closed) { window.close(); }
		}

		ImGui::SFML::Update(window, deltaClock.restart());

		ImGui::Begin("Test Begin");
                ImGui::Button("Test Button");
		ImGui::End();

		window.clear();
		ImGui::SFML::Render(window);
		window.display();
	} //end while

	ImGui::SFML::Shutdown();
}
```

When running my application in Visual Studio using the x64-Debug configuration I immediately get the following assertion failure for `IM_ASSERT(g.FrameScopeActive)`. This only happens when I add the lines
```
ImGui::Begin("Test Begin");
ImGui::Button("Test Button");
ImGui::End();
```

Without them I get a running black window (first image below).

I have been unable to find a solution to this problem. I am unsure if this is an issue with ImGui-SFML or ImGui itself. Any help with this would be greatly appreciated. Thank you!

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/12473592/71820810-f2ad0480-3055-11ea-97df-1674c7a679f9.png)
![error_2](https://user-images.githubusercontent.com/12473592/71820670-71557200-3055-11ea-8eca-6f7b85347805.png)

**Comment by ocornut** [comment]
Hello Esteban,
I would suggest asking on the https://github.com/eliasdaler/imgui-sfml repository, could be a bug there. Unfortunately ImGui-SFML doesn't use the standard naming convention of other back-ends so I don't know what it does in its Update function but it should be its responsability to call `ImGui::NewFrame()`.
Good luck!

**Comment by esduran** [comment]
Thank you! I'll ask on that repo then.
