### ISSUE TITLE
How can I control which windows can be attached to which dockspace?

### ISSUE THREAD

**Issue by KarimIO** [ocornut/imgui#2968]
**Version/Branch of Dear ImGui:**

Version: v1.75
Branch: _docking_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + Custom window implementation
Compiler: MS Visual Studio 2019
Operating System: Windows 10

**My Question:**

I'm trying to develop a level editor similar to that of the Unreal Engine, in which I can have different editors, for example a three material editors, one 
level editor, and one model viewer. Each of these I would implement as their own dock space. I'm currently having a problem because I want to restrict the panels to only snap to the main windows, but because of the nature of the panels I can't seem to set a hierarchy. How can I make sure I can't bring these subpanels to the top level? (This also causes errors when switching back to the main dockspaces) Also, when the dockspaces are tabbed together, or when a dockspace is minimized, the dockspace ejects its panels. I also wanna restrict the subpanels to only dock into their specified dockspace. I think all these features would be fixed by having a sense of ownership btw dockspace and panel. Is this implemented/planned? If not, do you have any suggestions on implementing it? I

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/10359829/71935260-0cae2a80-31af-11ea-9ffc-d3ce9614b424.png)

https://gist.github.com/KarimIO/15c709bb7b69231a8ab9c5b5b5b62c45

**Comment by ocornut** [comment]
You can use ImGuiWindowClass’ ID field for that.

**Comment by ocornut** [comment]
Also refer to https://github.com/ocornut/imgui/issues/6487#issuecomment-1580720798 for a fuller demo.
