### ISSUE TITLE
Problem displaying Portuguese text

### ISSUE THREAD

**Issue by lucass0** [ocornut/imgui#2969]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.75
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp _(or specify if using a custom engine/back-end)_
Operating System: Windows

**My Issue/Question:**

I'm having trouble trying to render Brazilian Portuguese texts that contain accents as well (eg. á é í ó ç)..

Is there support for my language? I checked that it exists for chinese language i imagine portuguese is also supported, if so how can i do it?

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/28022517/71945611-0e272500-31a6-11ea-8fd0-9ef2d909f20e.png)
![image](https://user-images.githubusercontent.com/28022517/71945624-1717f680-31a6-11ea-9bbf-64a8b2844963.png)

**Comment by ocornut** [comment]
If you browse the font details you'll see that those characters are available:
![image](https://user-images.githubusercontent.com/8225057/72064686-ae7f6580-32dc-11ea-9089-c4b478cdd258.png)

Your problem has to do with encoding of the source file. 
Try using `u8"á é í ó ç"` with C++11 or change source file text encoding or compiler text encoding settings. This FAQ entry applies: https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-and-input-non-latin-characters-such-as-chinese-japanese-korean-cyrillic

**Comment by lucass0** [comment]
> If you browse the font details you'll see that those characters are available:
> ![image](https://user-images.githubusercontent.com/8225057/72064686-ae7f6580-32dc-11ea-9089-c4b478cdd258.png)
> 
> Your problem has to do with encoding of the source file.
> Try using `u8"á é í ó ç"` with C++11 or change source file text encoding or compiler text encoding settings. This FAQ entry applies: https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-and-input-non-latin-characters-such-as-chinese-japanese-korean-cyrillic

Thanks, it worked using u8 and doing a cast.
![image](https://user-images.githubusercontent.com/28022517/72114274-c75e3a00-3321-11ea-9d50-339b529c6ade.png)
![image](https://user-images.githubusercontent.com/28022517/72114288-d0e7a200-3321-11ea-97f2-f174a8f59975.png)
