### ISSUE TITLE
Framerate across multiple monitors drops (DX11, multi-viewports)

### ISSUE THREAD

**Issue by greenkalx** [ocornut/imgui#2970]
```
Dear ImGui 1.75 WIP (17401)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1914
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x0000C441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
 DpiEnableScaleViewports
 DpiEnableScaleFonts
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 2141.00,1303.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.75
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp _(or specify if using a custom engine/back-end)_
Compiler: Visual Studio 2017
Operating System: Windows 10 Pro

**My Issue/Question:**

greenkalxToday at 1:53 AM
On docking branch, if I move the Demo and Hello viewports to another monitor, the FPS drops to half (of 60fps). Is this due to running on another adapter? Or twice the vsync? (example_win32_directx11)

omarToday at 2:34 AM
@greenkalx could you open an issue, specify which gpu and see if updating drivers makes a difference? Normally that example only wait for vsync on one viewport

**Screenshots/Video**

Not much to see, just moving the two default viewports to another monitor.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Just running vanilla imgui from docking branch, no changes.

**Comment by greenkalx** [comment]
Running very recent NVIDIA driver, attaching system info from NVIDIA control panel..

[NVIDIA System Information 01-09-2020 09-41-23.txt](https://github.com/ocornut/imgui/files/4041726/NVIDIA.System.Information.01-09-2020.09-41-23.txt)

**Comment by greenkalx** [comment]
For vsync, I was testing with my own app with two windows across two monitors.
I was seeing the frame rate drop as well, until I changed my SwapChain to present with vsync only on one window, not the other.
Does imgui have a similar structure?

**Comment by ocornut** [comment]
Well you can see in the example_win32_dx11 and imgui_impl_win32 how the swap chain are setup. Which change would you make to it ?

**Comment by greenkalx** [comment]
Got me, I should be reading the code more.
If there is one swapchain per viewport, I'd say have sync on one viewport only.

I see there is one swapchain in main.cpp which uses vsync. The viewports present without vsync (imgui_impl_dx11).
vsync on one viewport.. what happens when there are no viewports just the host viewport?

**Comment by greenkalx** [comment]
Propose:
```
In main.cpp:
{
    if number of viewports == 0
        call Present with vsync
    else
        call Present without vsync
}

In imgui_impl_dx11:
{
    if (viewportId == 0)
        call Present with vsync
    else
        call Present without vsync
}
```
I'll try this..

**Comment by ocornut** [comment]
main.cpp only does Present on the main viewport and imgui_impl_dx11 only does Present on the secondary viewports, so there's no `if` to add. `ImGui_ImplDX11_SwapBuffers()` already call Present without vsync so it's already doing what you are suggesting. Hence the issue.

**Comment by greenkalx** [comment]
Ya, that doesn't work.

**Comment by greenkalx** [comment]
Seems like a platform specific issue. (directx, not opengl)
I was recommended to look into using the flip model:
https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/dxgi-flip-model 
https://devblogs.microsoft.com/directx/dxgi-flip-model/

**Comment by greenkalx** [comment]
My intentions for imgui were for cross-platform. I'm switching to vulkan.
I was still tied up thinking of our old project with making it performant in directx.
We can park or close this.

**Comment by ocornut** [comment]
Could you go the project properties, Target Platform version change `8.1` to `10.0.xxxx` if you have that installed, then in main.cpp and imgui_impl_dx11.cpp you can try altering that line
```
sd.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;
```
into e.g.
```
sd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_DISCARD;
```
or
```
sd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL;
```
?

**Comment by SuperWangKai** [comment]
`DX11 Debug Layer` reports (running on Win10) -
> DXGI WARNING: IDXGIFactory::CreateSwapChain: Blt-model swap effects (DXGI_SWAP_EFFECT_DISCARD and DXGI_SWAP_EFFECT_SEQUENTIAL) are legacy swap effects that are predominantly superceded by their flip-model counterparts (DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL and DXGI_SWAP_EFFECT_FLIP_DISCARD). Please consider updating your application to leverage flip-model swap effects to benefit from modern presentation enhancements. More information is available at http://aka.ms/dxgiflipmodel. [ MISCELLANEOUS WARNING #294: ]

**Comment by ocornut** [comment]
I would need to experiment with how we can selectively use the new swap effects while actually compiling and running everywhere. The issue is that most of that stuff requires modern SDK.

So we may need something of that sort ?

```
#if WINVER >= 0x0A00    // Windows 10 SDK
    const bool win10 = IsWindows10OrGreater();
#else
    const bool win10 = false;
#endif
#if WINVER >= 0x0602    // Windows 8 SDK
    const bool win8 = IsWindows8OrGreater();
#else
    const bool win8 = false;
#endif

    sd.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;
#if WINVER >= 0x0A00    // Windows 10
    if (win10)
        sd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_DISCARD;
    else
#endif
    if (win8)
        sd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL;
    sd.BufferCount = (sd.SwapEffect == DXGI_SWAP_EFFECT_DISCARD) ? 1 : 2;
#endif
```

Or is there a way to query if the swap chain can use a swap effect?

Even that doesn't compile because it requires `<VersionHelpers.h>`. `imgui_impl_win32.cpp` uses its own version of `IsWindowsVersionOrGreater()` for portability, but including that in every main.cpp is going to be hell.

But first and foremost it would be useful if @greenkalx could test changing the blit model (both in main.cpp and imgui_impl_win32.cpp) while targetting a Windows 10 SDK.

**Comment by sergeyn** [comment]
> Or is there a way to query if the swap chain can use a swap effect?
I believe the proper way to detect if dxgi1.2 is present and that one is available if  you can get IDXGIFactory2 interface

**Comment by greenkalx** [comment]
I see activity in this thread, but my email notifications were going to another folder which I wasn't checking. Fixing that..

I was using DXGI_SWAP_EFFECT_DISCARD in main.cpp and imgui_impl_win32.cpp.

But I recommend not spending more time on this for now.

Since originally reporting this, I've switched PCs and video cards and now the second monitor only runs at 30fps and cannot be configured to 60fps in NVIDIA control panel. I have a GTX 1060 card now where I had a GTX 1050 Ti before. I may need a new HDMI cable? The second monitor feels more laggy than when I was running the 1050 Ti, but I'm not 100% sure both were 60fps before the hardware switch. I can try again once I get my hardware/cables sorted.

Also, I've moved to Vulkan from DirectX11.

**Comment by darkgnostic** [comment]
> I see activity in this thread, but my email notifications were going to another folder which I wasn't checking. Fixing that..
> 
> I was using DXGI_SWAP_EFFECT_DISCARD in main.cpp and imgui_impl_win32.cpp.
> 
> But I recommend not spending more time on this for now.
> 
> Since originally reporting this, I've switched PCs and video cards and now the second monitor only runs at 30fps and cannot be configured to 60fps in NVIDIA control panel. I have a GTX 1060 card now where I had a GTX 1050 Ti before. I may need a new HDMI cable? The second monitor feels more laggy than when I was running the 1050 Ti, but I'm not 100% sure both were 60fps before the hardware switch. I can try again once I get my hardware/cables sorted.
> 
> Also, I've moved to Vulkan from DirectX11.

I have GTX 1060 with two monitors attached. I had exactly the same problem. One monitor ran on 60 Hz, second on 30Hz. 

I had one monitor on DP and second on HDMI. HDMI was running on 30Hz. Since I had two HDMI inputs on monitor (LG) I switched to other HDMI and everything started to run on 60Hz. Hope this helps.

**Comment by greenkalx** [comment]
Thanks @darkgnostic, it was the HDMI settings on the monitor.
https://www.dell.com/support/article/en-ca/sln306595/setting-up-the-p2415q-p2715q-monitors-with-hdmi-2-0-that-support-4k-x-2k-60hz?lang=en

I can move imgui viewports and menus to the other monitor and no effect on the fps.
I really thought the second monitor was at 60fps before the video card swap.

**Comment by sakiodre** [comment]
@ocornut I've seen a lot of dear imgui code that uses the legacy `DXGI_SWAP_EFFECT_DISCARD` only because it's in the dx11 example and they don't know/care to change it, have you reconsidered switching to the flip model?

> I would need to experiment with how we can selectively use the new swap effects while actually compiling and running everywhere. The issue is that most of that stuff requires modern SDK.

I have implemented and tested your code on Windows 7, 8, 10, and 11, and they all work. The documentation doesn't specify what exact build number is supported, so I just grabbed the earliest build of 8 and 10 that I could find.

Even if the system didn't support the flip model but somehow still passed the version check, I think we could just add another check if `D3D11CreateDeviceAndSwapChain` returned `DXGI_ERROR_UNSUPPORTED`.

> Even that doesn't compile because it requires <VersionHelpers.h>. imgui_impl_win32.cpp uses its own version of IsWindowsVersionOrGreater() for portability, but including that in every main.cpp is going to be hell.

I'm not sure what the issue you were mentioning was, but since b66529fe3e603540fed81b2b0678ff13f780e48e made the API stable, I don't see any reasons not to use it.

-------
I remember reading in some issues that you said the backends are not your priority and they often hog the development process with issues and bug reports. So we may prefer the "if it works, don't change it" over upgrading a seemingly unnecessary thing that advanced users will do anyway.

**Comment by mirh** [comment]
https://github.com/GameTechDev/PresentMon/issues/212#issuecomment-2084458654
Just for the records (I know OP had a far more trivial problem, but still googling for the symptoms can end you up here) 20H1 and possibly 24H2 should have smoothed out a lot of multi-monitor pacing woes.
