### ISSUE TITLE
ButtonBehavior flags for going outside item

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#2971]
I am trying to get Button behaviour (trigger pressed when mouse button is released) but also if it is released when mouse is outside item. (previously clicked on item)
Can this be achieved with any flag?

**Comment by ocornut** [comment]
How are you going to use that?

**Comment by sonoro1234** [comment]
In this code
https://github.com/sonoro1234/LuaJIT-ImGui/blob/master/extras/curve.cpp#L725

**Comment by ocornut** [comment]
You can call `IsItemDeactivated()` to get this information.

**Comment by ocornut** [comment]
That said I think it's also ok to add a flag to ButtonBehavior for that and will add it.

**Comment by ocornut** [comment]
Added `ImGuiButtonFlags_PressedOnClickReleaseAnywhere` in imgui_internal.h

**Comment by sonoro1234** [comment]
Still working with 1.74 so I cant use the recently added flag.
I added IsItemDeactivated to the Curve code but is is not saying true when releasing mouse outside Curve. 

```cpp
ImRect bb(window->DC.CursorPos, window->DC.CursorPos + size);
        ItemSize(bb);
        if (!ItemAdd(bb, 0))
            return false;
		
		if (!pressed_on_modified && IsItemDeactivated())
			return true;

        //const bool hovered = ItemHoverable(bb, id);
		bool hovered, held;
		bool pressed = ButtonBehavior(bb, id, &hovered, &held, 0);
```

Any reason to explain this?

**Comment by sonoro1234** [comment]
with 1.75 could test new flag and it works as expected
