### ISSUE TITLE
How to insert custom strings/data into InputTextMultiline text box buffer at current cursor position in code?

### ISSUE THREAD

**Issue by kepler425b** [ocornut/imgui#2972]
I was thinking I should just get cursor position within the text box to insert data to string buffer myself manually (not sure how to do that), but I think there is a built-in API for this purpose but not that obvious? I can't figure it out reading source code alone.

**Comment by ocornut** [comment]
You can do this using the inputtext callback system. The callback data structure has helper functions for it. It’s not super welcoming/easy api for now.

(PS: please fill in the requested form when creating a new issue next time, thank you.)
