### ISSUE TITLE
Question: are you rendering with Nearest texture filtering? (instead of Bilinear)

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#2973]
Hello,

Dear ImGui can technically be rendered with the texture unit configured to use Nearest sampling instead of Bilinear. All examples and provided backends have been using Bilinear, which allows for oversampling of fonts, some (not ideal) degree of font scaling, and generally more convenient when rendering user images.

**Question: Are you rendering Dear ImGui using Nearest filter, and why?**
**If you use it, do you use it for all your Dear ImGui rendering, or only temporarily (e.g. when doing a certain `ImGui::Image()` call). Do you ever render part of the Atlas texture (which is used by ImDrawList shape) using Nearest filtering?**

Some reasons I can think of:
- A) Using a software renderer
- B) Rendering on very low spec gpu/machine (please specify)
- C) Trying to achieve a certain look intentionally (please specify)
- D) Switching to nearest filter temporarily (via a ImDrawCallback) to blit 1:1 image data faster. 

Reason is we're looking into making changes to the ImDrawList rendering primitives that would require Bilinear filtering of the texture to render shapes. That potential change would still allow D to work but would potentially make things harder for A,B,C.

Please note that the problem only applies if Nearest filtering is used when drawing ImDrawList shapes such as borders, rectangles, anti-aliasing lines, circles etc.

Based on your feedback we could decide on the best solution or workaround (e.g. provide a runtime flag, vs provide a compile-time flag, vs ditch that support alltogether?).

Thanks.

PS: If you are using one of the `imgui_impl_xxx` backend without modification, you are using Bilinear filtering.

**Comment by agersant** [comment]
Hello!
I work on a spritesheet editor whose main use case it to manage pixel-art game sprites. Rendering the sprites with nearest neighbor filtering is crucial for them to look good when scaled (by integer zoom factors). Project: https://github.com/agersant/tiger/

**Comment by alexkirsz** [comment]
Option C.

I'm using the nearest neighbor filter in order to be able to zoom in on small textures. My textures are weights in a neural network, thus the necessity to be able to distinguish the individual pixels/values.

![image](https://user-images.githubusercontent.com/1621758/72171290-f7b1e100-33d2-11ea-93fe-08d9516e2d20.png)

**Comment by ocornut** [comment]
I need to clarify the question above into:
**" do you use Nearest texture filtering in the same draw command as other ImDrawList shapes (rectangles, borders, fonts) "**

**Comment by mattiasljungstrom** [comment]
I'm fairly sure I've used nearest pixel on macOS retina displays to make UI look crisp while drawing it scaled up. I'm not on the cutting edge version of imgui, so maybe this isn't relevant anymore.

**Comment by alexGuntha** [comment]
I've set Dear ImGui's Atlas texture to be drawn with Nearest filtering because I also draw my engine's text using Nearest to avoid some rendering issues that are most likely my fault, but in practice, as long as I don't manipulate ImGui's font scale, I could as well set it to bilinear.

**Comment by Flix01** [comment]
Aside from nearest filtering some user textures (like in my image editor to keep zoomed pixels square), the only reason I use it on the main texture atlas is when I use the default Dear ImGui embedded font, because when I zoom it, I think it looks better this way (less blurring on the already blocky font).

As far as I remember there was no other reason for not using a better texture filtering...
Probably having a better quality embedded font would help.

**Comment by ocornut** [comment]
Thank you everyone for your answers on this!

**Comment by joeslay** [comment]
Generally no, but I do round coordinates before calling DrawRect to render non-antialiased horizontal/vertical lines on a scaled overlay to prevent it looking blury.

**Comment by ocornut** [comment]
Closing this as answered, thank you all!
