### ISSUE TITLE
[win32] Paste from clipboard history not working

### ISSUE THREAD

**Issue by crackedmind** [ocornut/imgui#2977]
**Version/Branch of Dear ImGui:**

Version: `1.75 WIP (17401)`
Branch: master and docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp and imgui_impl_glfw.cpp
Operating System: Windows 10 1909

**My Issue/Question:**
It's a little similar to previous issue #2976 Paste from clipboard history (win+v hotkey) not working in sdl/glfw backends. But it working in plain win32 backend.

**Comment by rokups** [comment]
This happens because windows clipboard manager sends CTRL+v messages without scancode set. Both GLFW and SDL rely on scancode to detect which key is pressed and thus it fails.

https://github.com/glfw/glfw/issues/1623
https://bugzilla.libsdl.org/show_bug.cgi?id=4940

**Comment by crackedmind** [comment]
@rokups Thank you, good to know.

**Comment by rokups** [comment]
This will be fixed in next GLFW release.

**Comment by ocornut** [comment]
Closing this as a non-dear imgui issue, reported to GLFW and SDL and fixed in GLFW. Thanks Stanislav and Rokups.
