### ISSUE TITLE
When both scrollbars appear at a certain position they start blinking.

### ISSUE THREAD

**Issue by ofabricio** [ocornut/imgui#2978]
**Version/Branch of Dear ImGui:**

Version: **1.75 WIP**
Branch: **master**

**Back-end/Renderer/Compiler/OS**

Back-ends: **imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp**
Compiler: **gcc**
Operating System: **windows**

**My Issue/Question:**

I'm trying to have a widget centered in a window. But when both scrollbars appear at a certain position they start blinking, causing the content region to have a different value each frame. It seems to happen when the window is at the limits of the content region.

I dont know if I'm using the right methods for the calculation, the code to reproduce is below.

**Screenshots/Video**

![img](https://user-images.githubusercontent.com/1385704/72262564-f57b9c80-35f5-11ea-802e-58bb79132cab.gif)

**Standalone, minimal, complete and verifiable example:**

```cpp
ImGui::Begin("Canvas", 0, ImGuiWindowFlags_HorizontalScrollbar);
{
    // Get window/content metrics.
    ImVec2 win_ctt_min = ImGui::GetWindowContentRegionMin();
    ImVec2 win_ctt_max = ImGui::GetWindowContentRegionMax();
    ImVec2 win_pos = ImGui::GetWindowPos();
    win_ctt_min.x += win_pos.x;
    win_ctt_min.y += win_pos.y;
    win_ctt_max.x += win_pos.x;
    win_ctt_max.y += win_pos.y;
    // Debug draw.
    // ImGui::GetForegroundDrawList()->AddRect(win_ctt_min, win_ctt_max,
    //                                         IM_COL32(255, 255, 0, 255));

    ImVec2 canvas_size(32 * 8, 32 * 8);
    // Offset for centering the canvas on the window content.
    ImVec2 canvas_offset((win_ctt_min.x + win_ctt_max.x) / 2.0 - (canvas_size.x / 2.0),
                         (win_ctt_min.y + win_ctt_max.y) / 2.0 - (canvas_size.y / 2.0));

    ImGui::SetCursorScreenPos(canvas_offset);
    ImGui::Button("Hello", canvas_size);
}
ImGui::End();
```

**Comment by ocornut** [comment]
I think the way you are positioning your contents is creating a feedback loop as your initial offset is altering the maximum position and therefore scrolling.

I would suggest to make sure `canvas_offset >= win_ctt_min` on each axis, that would fix it and I think it's a better user experience.

You could also use `ImGuiWindowFlags_AlwaysVerticalScrollbar | ImGuiWindowFlags_AlwaysHorizontalScrollbar` instead as well.

It's alternating between
![image](https://user-images.githubusercontent.com/8225057/72447331-73d26d00-37b5-11ea-8385-db99d963aefb.png)

And
![image](https://user-images.githubusercontent.com/8225057/72447340-78972100-37b5-11ea-8c5c-444412199375.png)

If you step in debugger or do the calculation you'll probably find out why your centering scheme is creating that feedback loop.

**Comment by ofabricio** [comment]
Indeed, that's a lot better. Thank you for your time, and sorry for the not-exactly-a-bug issue.
