### ISSUE TITLE
Cant pass render target to imgui window using dx11

### ISSUE THREAD

**Issue by roveldo135** [ocornut/imgui#2987]
Hello,i've been working on dx11  game engine for while,and i like to draw my scene view into a imgui window.So far i created render texture and resource view however i wasnt able to manage pass the view to imgui window.
This is my scene view
![image](https://user-images.githubusercontent.com/36901319/72625351-b339be80-3959-11ea-9d24-9653ae3b3852.png)
I want my scene target texture to be displayed in this blue window
![image](https://user-images.githubusercontent.com/36901319/72625433-dc5a4f00-3959-11ea-99da-2aac2ed6314f.png)
Here's my target&resource init code
`//Render Texture Variables
		D3D11_TEXTURE2D_DESC textureDesc;
		D3D11_RENDER_TARGET_VIEW_DESC renderTargetViewDesc;
		D3D11_SHADER_RESOURCE_VIEW_DESC shaderResourceViewDesc;

		//Set Texture Description
		ZeroMemory(&textureDesc, sizeof(textureDesc));
		textureDesc.Width = targetW;
		textureDesc.Height = targetH;
		textureDesc.MipLevels = 1;
		textureDesc.ArraySize = 1;
		textureDesc.Format = DXGI_FORMAT_R32G32B32A32_FLOAT;
		textureDesc.SampleDesc.Count = 1;
		textureDesc.Usage = D3D11_USAGE_DEFAULT;
		textureDesc.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;
		textureDesc.CPUAccessFlags = 0;
		textureDesc.MiscFlags = 0;
		// Create the texture
		pDevice->CreateTexture2D(&textureDesc,NULL, pRenderBackBuffer.GetAddressOf());
		//Create Render Target View Description
		ZeroMemory(&renderTargetViewDesc, sizeof(D3D11_RENDER_TARGET_VIEW_DESC));
		renderTargetViewDesc.Format = textureDesc.Format;
		renderTargetViewDesc.ViewDimension = D3D11_RTV_DIMENSION_TEXTURE2D;
		renderTargetViewDesc.Texture2D.MipSlice = 0;

		//Creating Render Target View using texture2d;
		pSwapChain->GetBuffer(0, __uuidof(ID3D11Texture2D),&pRenderBackBuffer);
		pDevice->CreateRenderTargetView(pRenderBackBuffer.Get(),nullptr, &pRenderTarget);

		//Creating ShaderResourceView Description
		shaderResourceViewDesc.Format = textureDesc.Format;
		shaderResourceViewDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
		shaderResourceViewDesc.Texture2D.MostDetailedMip = 0;
		shaderResourceViewDesc.Texture2D.MipLevels = 1;

		// Create the shader resource view.
		pDevice->CreateShaderResourceView(pRenderBackBuffer.Get(), &shaderResourceViewDesc, pShaderResourceView.GetAddressOf());

		////Depth&Stencil
		Microsoft::WRL::ComPtr<ID3D11Texture2D> pDepthStencil;
		D3D11_TEXTURE2D_DESC descDepth = {};
		descDepth.Width = w;
		descDepth.Height = h;
		descDepth.MipLevels = 1u;
		descDepth.ArraySize = 1u;
		descDepth.Format = DXGI_FORMAT_D24_UNORM_S8_UINT;
		descDepth.SampleDesc.Count = 1u;
		descDepth.SampleDesc.Quality = 0u;
		descDepth.Usage = D3D11_USAGE_DEFAULT;
		descDepth.BindFlags = D3D11_BIND_DEPTH_STENCIL;
		pDevice->CreateTexture2D(&descDepth, nullptr, &pDepthStencil);
		//Creating Description
		D3D11_DEPTH_STENCIL_VIEW_DESC dsDesc = {};
		dsDesc.Format = DXGI_FORMAT_D24_UNORM_S8_UINT;
		dsDesc.ViewDimension = D3D11_DSV_DIMENSION_TEXTURE2D;
		dsDesc.Texture2D.MipSlice = 0u;
		//Create Stencil View
		pDevice->CreateDepthStencilView(pDepthStencil.Get(), &dsDesc, &pDepthView);
		//Set Render Target
		pContext->OMSetRenderTargets(1u, pRenderTarget.GetAddressOf(), pDepthView.Get());`
And this is how i try to render on a button
`ImGui::ImageButton((void*)pGraphics->pShaderResourceView.Get(), ImGui::GetWindowSize());
Couldnt do with this either
`ImGui::GetWindowDrawList()->AddImage(
			(void*)pGraphics->pShaderResourceView.Get(), ImVec2(ImGui::GetItemRectMin().x + pos.x,
				ImGui::GetItemRectMin().y + pos.y),
			ImVec2(pos.x - 10, pos.y), ImVec2(0, 0), ImVec2(1, 1));*/`

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
