### ISSUE TITLE
Directx11 renderer crash

### ISSUE THREAD

**Issue by Nukem9** [ocornut/imgui#299]
This causes the entire kernel display driver to stop responding, usually forcing me to hard reboot my laptop. I'll try to get some kind of dump without my computer freezing.
The source code is pretty simple, if it needs to be posted here let me know.

*edit: You can also see a small graphical artifact to the right of the error box. This shows up before the crash.

![image](https://cloud.githubusercontent.com/assets/4228359/9267159/35bf775c-4218-11e5-935e-781b5da25edd.png)

**Comment by ocornut** [comment]
What's the repro?

The example code for the DX11 has a limit on buffer size:
https://github.com/ocornut/imgui/blob/master/examples/directx11_example/imgui_impl_dx11.cpp#L32
So this probably needs to be fixed.

It's surprising that this would crash a NVIDIA driver though..

**Comment by Nukem9** [comment]
That seems to be it! I doubled the values and it no longer crashes.

The "Metrics" menu displays ~20300 verts, which is just enough to overflow that buffer. I don't know if you will be able to reproduce it yourself. I hit 20k+ vertices only at 2560x1440 resolution or higher.

**Comment by ocornut** [comment]
OK I could repro with both DX9 and DX11 with lots of contents. Better fix those samples then with dynamically growing buffers. If you know DX9 or DX11 well enough to fix them let me know!

**Comment by ocornut** [comment]
Done!

**Comment by Nukem9** [comment]
Thanks!
