### ISSUE TITLE
How do I draw an image using SDL2/OpenGL2 ?

### ISSUE THREAD

**Issue by mslinklater** [ocornut/imgui#2990]
Does anyone have any sample code for drawing an ImGui image using SDL2 & OpenGL2 ? Here is my code, but all I get is a white square.

```
// setup
SDL_Surface* gHelloWorld;
gHelloWorld = SDL_LoadBMP("hello_world.bmp");

// draw
ImGui::Begin("ImageTest");
ImGui::Image((void*)gHelloWorld, ImVec2(100,100));
ImGui::End();
```

**Comment by ocornut** [comment]
There’s one on the wiki.
You’ll need to pass a GL texture identifier to Image() function. Check SDL and GL docs about how to check a GL texture.
