### ISSUE TITLE
io.MouseDown[3](VK_XBUTTON1) & [4](VK_XBUTTON2) not working

### ISSUE THREAD

**Issue by SilHey** [ocornut/imgui#2991]
I've been trying to add a hotkey element to ImGui that I found online. everything works fine apart from when I try and bind XButton1 and XButton2 which both are not recognized and I was wondering why?
Heres some code to preview the issue
`	
if (io.MouseDown[i]) {
				switch (i) {
				case 0:
					key = VK_LBUTTON;
					break;
				case 1:
					key = VK_RBUTTON;
					break;
				case 2:
					key = VK_MBUTTON;
					break;
				case 3:
					key = VK_XBUTTON1;
					break;
				case 4:
					key = VK_XBUTTON2;
					break;
				}`
in this case, case 3 and 4 are never reached when i press them on my mouse.

**Comment by anarh1st47** [comment]
which wndproc implementation you use? 
https://github.com/ocornut/imgui/blob/8bcac7d95caa7e3b960b7bf7c3bcda4ecfe4541f/examples/imgui_impl_win32.cpp#L282
https://github.com/ocornut/imgui/blob/8bcac7d95caa7e3b960b7bf7c3bcda4ecfe4541f/examples/imgui_impl_win32.cpp#L297

this lines(as ik) should handle xmouse

**Comment by ocornut** [comment]
1) Sorry but #1586.

2) Didn't follow requested guidelines or issue template. Please make sure you have read the guidelines.

Closing, blocked.

This is supported by imgui_impl_win32.cpp since 2019-01-17 (~v1.68).
