### ISSUE TITLE
Scaling Allegro Example

### ISSUE THREAD

**Issue by kns1966** [ocornut/imgui#2996]
The included Allegro example unlike some of the others (e.g., directx9) does not appear to scale the demo dialog windows on my 4k monitor.  This is on Windows 10 with Visual Studio 2017 and a just downloaded version of the imgui repository.

Suggestions for a fix would be most appreciated.

Edit: In my own example I had code to calculate a scaling factor.  I've now applied this value to the font associated with the imgui window which led to partial success.  What remains is to also scale the various input boxes.

**Comment by ocornut** [comment]
If you scale the font and the style it should be ok for most. We are still missing a standardized sets of values for users to use to scale their constants.
