### ISSUE TITLE
BeginMainMenuBar with no other windows - ignores mouse hover/clicks

### ISSUE THREAD

**Issue by adnsv** [ocornut/imgui#2997]
When using only BeginMainMenuBar without any other windows, all mouse hover/clicks are ignored. Was working before, possibly related to Jan 20 changes (3fe6ae9)

to reproduce:

```cpp
if (ImGui::BeginMainMenuBar()) {
    if (ImGui::BeginMenu("File")) {
        ImGui::MenuItem("New Database...");
        ImGui::EndMenu();
    }
    ImGui::EndMainMenuBar();

    // no other windows
}
```

Tracked the problem to `ButtonBehavior` > `ItemHoverable` > `IsWindowContentHoverable` returning false when checking for g.NavWindow, which turns out to be null in this case:
```cpp
 if (!g.NavWindow)
        return false;
```
I am using this workaround for now:

```cpp
if (ImGui::BeginMainMenuBar()) {
    if (!ImGui::IsAnyWindowFocused())
        ImGui::FocusWindow(ImGui::GetCurrentWindowRead());
    if (ImGui::BeginMenu("File")) {
        ImGui::MenuItem("New Database...");
        ImGui::EndMenu();
    }
    ImGui::EndMainMenuBar();
}
```

**Comment by ocornut** [comment]
Hello Alex,
Apologies, this is a bug caused by 3fe6ae97323ddfa9cce73831b930af63c34d287b (January 20) I did a small refactor and made a mistake altering the behavior of `IsWindowContentHoverable()`, that mistake is now reverted.
Thanks a lot !

**Comment by adnsv** [comment]
Omar,
Thanks, I'm impressed with the quick response
