### ISSUE TITLE
Square Checkbox Or Toggle Button?

### ISSUE THREAD

**Issue by Developy05** [ocornut/imgui#2998]
![checkbox](https://user-images.githubusercontent.com/60199929/72935457-6f3e2380-3d76-11ea-86e1-b56bb6c1bccf.gif)

I made a simple web page in ImGui I coppy my website but I dont make a like this checkbox or toggle button how I made a like this checkbox or toggle button

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
