### ISSUE TITLE
ImGuiTextFilter doesn't handle multiple/separate filter (ex: goodcode -bug -slow)

### ISSUE THREAD

**Issue by ebriney** [ocornut/imgui#30]

**Comment by ocornut** [comment]
Thread necromancy: I have changed `ImGuiTextFilter` today to also support space as a separator.
It comes with support quotes blocks, e.g. inputting "foo bar" (with quotes) treat the thing as a single keyword.
I'll be posting more improvements and details at #2435

**Comment by ocornut** [comment]
Finished posting other improvements.
For avoidance of doubt:
```text
  ""         display all lines
  xxx        display lines containing "xxx"
  xxx yyy    display lines containing "xxx" and "yyy"
  "xxx yyy"  display lines containing "xxx yyy"
  xxx,yyy    display lines containing "xxx" or "yyy"
  -xxx       hide lines containing "xxx"
```

There's also code for a `ImGuiTextFilterMultiSource` helper at https://github.com/ocornut/imgui/pull/2435#issuecomment-5762677330 which is not part of the API but might be if there's any need.
