### ISSUE TITLE
How to make input-semi-transparent windows?

### ISSUE THREAD

**Issue by crazydef** [ocornut/imgui#3003]
Hi,

I'm trying to make a window transparent to the mouse, but not its controls.  Is this possible?

Basically I have a single window that covers the whole screen (to avoid the ridiculous complications of using two different coordinate systems (window and drawlist) when rendering) that needs to be transparent to the mouse, but I need controls within that window to still be clickable.

Ideally I'd like this to be pixel perfect through a callback for hit testing, but I could probably get by with marking specific rects as transparent or opaque to the mouse.

**Comment by ocornut** [comment]
It's unfortunately not possible and not super easy to do automatically with the current architecture.

Marking shapes/rects explicitly transparent however would be possible but super tedious... The docking branch has a system to register 1 rectangular hole though, we could merge that in master possibly.

> (to avoid the ridiculous complications of using two different coordinate systems (window and drawlist)

By "window" do you mean "dear imgui window" or "your native window". If the earlier, you should use `GetCursorScreenPos()` everywhere and not `GetCursorPos()`.

**Comment by crazydef** [comment]
Thanks for the quick response.  :)

I mean an ImGui window.  I have mostly custom UI elements being rendered directly through ImDrawList - which always takes screen coordinates, right?, and then ImGui controls  interspersed which use local window coordinates.  I figured the easiest way around this was to create a fullscreen window so at least then I'll be on the same page as far as positioning elements and rendering is concerned.

PS, sorry for not using the template.  I assumed that was more for bugs than mere questions.  :)

**Comment by ocornut** [comment]
> then ImGui controls interspersed which use local window coordinates

That's something I'm trying to slowly obsolete and it's going to take time but if you should Get/SetCursorScreenPos instead of Get/SetCursorPos you should see the local window coordinates much less.

Remaining are the "ContentRect" stuff which is a large mess that I'm transitioning to WorkRect and when we expose the WorkRect api hopefully it should be all absolute coordinates and ContentRect can be obsoleted.

**Comment by crazydef** [comment]
Hmm, I'll take your word that SetCursorScreenPos will work with ImGui controls (I'm not at the point where I have controls away from the top of the screen right now), but it definitely doesn't seem to be working for text.  Or rather, I can't quite work out what's going on with text.

Creating a window across the bottom of the screen like this...

```
float top = displaySize.y - height;

ImGui::SetNextWindowPos(ImVec2(0.0f, top));
ImGui::SetNextWindowSize(ImVec2(displaySize.x, height));
ImGui::SetNextWindowBgAlpha(0.0f);

ImGui::Begin(...);

ImDrawList* dl = ImGui::GetWindowDrawList();

dl->AddRectFilled(ImVec2(0.0f, top), displaySize, 0xAA000000, 0, ImDrawCornerFlags_None);
```

...renders a semi black transparent bar across the bottom of the screen, as expected.

And I can use the following with local window coordinates to render text in that 'window':

```
ImGui::PushStyleColor(ImGuiCol_Text, colour);
ImGui::SetCursorPos(pos);
ImGui::Text(text);
ImGui::PopStyleColor();
```

However, changing `pos` to screen coordinates and calling `ImGui::SetCursorScreenPos` doesn't work.  (I see no text.)

Changing the above to the following:

```
dl->AddText(imFont, imFont->FontSize * scale, pos, ImGui::GetColorU32(colour), text);
```

refuses to work regardless of the coordinate system used.

I also have a window at the top of the screen using the same text render function which continues to work just fine.  I.e., when window coordinates fit directly over screen coordinates my text render wrapper function can call either `ImGui::Text` or `dl->AddText` without problems.

**Comment by ocornut** [comment]
Which branch are you using and do you have multi-viewports enabled?

**Comment by crazydef** [comment]
We're using master from about three weeks ago.

Not sure about multi-viewports.  Where would I found that out?  (I'm not doing anything with the viewport, but it's possible someone else is.)

**Comment by ocornut** [comment]
(I asked that question because enabling multi-viewports (they are in the `docking` branch) need to affect the coordinate space to match your OS coordinates (so (0,0) is top-left of main monitor). That's to say even in the most random question there is a use for filling the new issue template.)

> However, changing pos to screen coordinates and calling ImGui::SetCursorScreenPos doesn't work. (I see no text.)

Then I think you have a bug and either values are not what you think they are. Using a debugger or displaying values with `ImGui::Text()` someewhere you can probably find your issue. But you should be able to use "screen coordinates" everywhere without trouble.

**Comment by crazydef** [comment]
hah.  You're right.  Sorry.  I was still pulling displaySize from ImGui::GetWindowSize() when I shouldn't have been.

**Comment by ocornut** [comment]
Not sure if there's something else we can do with this issue?
I don't mind merging the internal api from docking where a hit hole can be registered per window, but that will be a single rectangular hole per window. Otherwise it's currently not possible.

**Comment by crazydef** [comment]
In the UI engines I've written in the past, I allow derived types to implement their own hit testing as needed, and those tests walk up the object tree from the object whose bounding box is under the mouse (or touch) to the root object at the top (typically the thing that owns the windows).  Any level that returns true aborts the walk up the tree and registers that object as the "mouse object" (which is only true for desktop systems these days, but you get the idea).  This is usually performed per frame to ensure animating elements are tracked accurately.  In the past I usually ended up rendering the whole game in a UI widget so clicks that made it to the bottom of the tree were automatically routed to the game engine, which meant I didn't have to worry about multiple paths in the wrong end of the input system.

In Imgui, I could imagine a callback function set on a per window basis that is called at each level in the same way.  It would have to have some way to identify the object being queried, and a way to call the default hit testing functionality for the object in question.  But it would then give you the ability for pixel perfect hit testing on pretty much anything in the hierarchy.

That said, it's not something I really need now the coordinate issues have been resolved.  Our UI is now split into distinct windows and the main stuff drawn over the top (actually interspersed among other windows) is - for now - flagged as NoInputs.  I suspect at some point in the future I will end revisiting that decision when someone decides they want to be able to click on things, but I'll cross that bridge when I come to it.  :)

**Comment by ocornut** [comment]
The system needs to know at the beginning of the frame which window is being hovered, as lots of code is relying on this assumption for variety of reasons. Implementing this would therefore not be easy but feel free to dig further if you feel you need it.

Closing this now.
