### ISSUE TITLE
black background even after changing it

### ISSUE THREAD

**Issue by Vaseliinikives** [ocornut/imgui#3013]
my background is black even after changing it.
example picture with ImGui::StyleColorsClassic();
![image](https://user-images.githubusercontent.com/45107100/73884616-f8715200-486e-11ea-9344-c29ecf7ec8db.png)

**Comment by ocornut** [comment]
Sorry but #1586.
Didn't follow requested guidelines or issue template.  Please make sure you have read the guidelines.
Closing, blocked.
