### ISSUE TITLE
Imgui Antialiased crashing

### ISSUE THREAD

**Issue by putteherja** [ocornut/imgui#3014]
Hello when setting antialiased to false the lines is not crashing.
What I am doing is drawing every bone/hitbox in game.
I have tested to rewrite the code many times now, hope you can help.

I am new to posting in github, here is youtube video and pastebin link:

https://www.youtube.com/watch?v=o5_ETUrA2Wc
https://pastebin.com/XQPBMKB9

Thank you!

**Comment by ocornut** [comment]
Sorry but #1586.
Didn't follow requested guidelines or issue template. Please make sure you have read the guidelines.
Closing, blocked.
