### ISSUE TITLE
Render target clear color not displaying using ImGui::Image

### ISSUE THREAD

**Issue by roveldo135** [ocornut/imgui#3015]
Version: ???
Branch: Docking

**imgui_impl_dx11/Renderer/Compiler/Win10**

**Render target clear color not displaying using ImGui::Image:**

Im using **Render Target Texture** to show game view on imgui::Image(),contents of the scene successfully rendered on the image but clear color seems missing,it looks like im drawing my scene over complete transparent image.

Here how it looks like,but i should be seen as blue background.
![image](https://user-images.githubusercontent.com/36901319/73949708-d974cd80-490b-11ea-8019-aeed47193c13.png)
I tested clearcolor works as intented when rendering on the window.

**Comment by ocornut** [comment]
This is a DX11 issue, not a dear imgui related issue. Please refer to DX/graphics communities.
