### ISSUE TITLE
Incorrect first column line height calculation.

### ISSUE THREAD

**Issue by AllenDang** [ocornut/imgui#3018]
**Version/Branch of Dear ImGui:**

Version: 1.74
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: GLFW 3.3 + OpenGL 3.2
Compiler: Golang + CGO

**My Issue/Question:**

Use imgui.PushTextWrapPos with imgui.Text will cause this issue.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/18550/74117959-7b3e3800-4bf4-11ea-965a-91abb5cf0f17.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Please do not forget this!
ImGui::Begin("Example Bug");

// Here will be the Golang code but I think should be able to point the issue out.
imgui.Columns(3, "#DemoTable", true)

imgui.Separator()
imgui.Text("Loooooooooooooooooooooooooooooog line")
imgui.NextColumn()
imgui.Text("Age")
imgui.NextColumn()
imgui.Text("Location")

imgui.NextColumn()
imgui.Separator()
imgui.Text("Second Loooooooooooooooooooooooooooooog line")
imgui.NextColumn()
imgui.Text("Age")
imgui.NextColumn()
imgui.Text("Location")

ImGui::End();
```

**Comment by ocornut** [comment]
Hello @AllenDang, 

- Are you sure you are in 1.74 and not 1.74 WIP ? An issue precisely related to this was fixed in 1.74 but depending on which commit you grabbed of 1.74 WIP you might not have the fix.
- Your description says "Use imgui.PushTextWrapPos with imgui.Text will cause this issue." but your example doesn't use PushTextWrapPos.

**Comment by AllenDang** [comment]
@ocornut I download imgui from release tab and the first line of imgui.h is "// dear imgui, v1.74" I think it should be 1.74.

And sorry I miss the PushTextWrapPos, and in the go wrapper I actually using TextUnformatted. 
Here is the minimal demo code.

       ```
 ImGui::Begin("Example Bug");
        ImGui::Columns(3, "#DemoTable", true);

        ImGui::Separator();
        ImGui::PushTextWrapPos(0.0f);
        ImGui::TextUnformatted("Loooooooooooooooooooooooooooooog line");
        ImGui::PopTextWrapPos();
        ImGui::NextColumn();
        ImGui::Text("Age");
        ImGui::NextColumn();
        ImGui::Text("Location");

        ImGui::NextColumn();
        ImGui::Separator();
        ImGui::PushTextWrapPos(0.0f);
        ImGui::TextUnformatted("Second Loooooooooooooooooooooooooooooog line");
        ImGui::PopTextWrapPos();
        ImGui::NextColumn();
        ImGui::Text("Age");
        ImGui::NextColumn();
        ImGui::Text("Location");

        ImGui::End();

```

**Comment by ocornut** [comment]
I checked out both 
bdce8336364595d1a446957a6164c97363349a53 (1.74)
c262276988da6ae4b16911d9c56fc8d9226e7319 (first version marked 1.74 WIP)

And can't repro a bug using your code.
![image](https://user-images.githubusercontent.com/8225057/74142477-4d0f2700-4bf9-11ea-9727-feb0f78b400e.png)

**Comment by AllenDang** [comment]
@ocornut My bad, I invoked ImGui::Separator() before ImGui::NextColumn(). Thanks for your kindly response.
