### ISSUE TITLE
Dynamic layout

### ISSUE THREAD

**Issue by GkqqNkKC** [ocornut/imgui#3020]
I'm trying to separate the normal window into multiple parts. This is kinda what I want to get:

![image](https://user-images.githubusercontent.com/35461917/74165426-c0329080-4c2d-11ea-8f17-99023d299756.png)

There are a lot of flaws. Before I will explain what I tried until now I want to point in the image attached what's wrong: the tab bars on the same line are hitting each other, so there's no space between "Stats" and "Inventory". The same happens with "Party" and "Clan", they are just empty and auto-resized, but they are not different tabs, but different bars. What I need is a blocky style. I put blocks into the window, especially blocks that are automatically resizing to content. I already did that there, but there's no space between the so-called "blocks". Do not pay attention at how I use tabs, is not in this example but sometimes I want 2 tabs on same tab bar, it just happened that now I don't need. As example, using fixed size child windows does exactly what I want, they are like a block in the window, and they provide some space between it and other childs

**First try:** I use tab bars in childs
```
BeginChild("a", ImVec2(...));
...
EndChild();
SameLine();
BeginChild("b", ImVec2(...));
...
EndChild();
```
This assures the right space between blocks, but they MUST have fixed size, which I don't want

**Second try:** I use tab bars in groups, like in the image
```
BeginGroup();
...
EndGroup();
SameLine();
BeginGroup();
...
EndGroup();
```
This assures the dynamic size which I need, but there's no space between the groups. In general this should be fixed by itself due the fact that the elements inside a group has their own paddings, but seems like tab bars have no padding, and since everything happens inside them, no padding between groups

**Third try:** using groups with separators, default one as horizontal, and..., columns as hacky vertical? I want to use horizontal ones inside tabs too, but they seem to cut the whole window, rather than stay there, so still not good. Even if I abandon using those separator inside, I wasn't able to make the columns resizable to content, rather than equal split

**Fourth try:** using groups, but having near tab bars some Dummy. It didn't end well, and sometimes I even got the group to take full window width even if the values inside dummies were not bigger than 20

**Fifth try:** tweak style of tab bar (even other widgets if necessary). I failed since I wasn't found an already existing style which could set the padding. I used the demo sliders to get what I wanted, no success. The ability of setting specific margins for an element would be useful I think

What I think shall happen:
- don't use Childs, their scope is to make use of scrollbars, and not to seperate content like that
- don't use columns, they are not meant for this grid style
- use Groups since they group content, exactly what I need
- make Groups to have space between them, or tab bars (widgets) to have space, at least 0 as default and able to be set

Summary of what I need: split window into content fitting divisions that have space between them

**Comment by ocornut** [comment]
> Summary of what I need: split window into content fitting divisions that have space between them

Maybe use the docking branch?

**Comment by GkqqNkKC** [comment]
It looks promising! I was able to group multiple windows into one, but what I also need is to display the docked windows by default, and not me dragging them. I looked into DockBuilderXXX functions, but I failed to find any example on how to do it. I assume I draw the windows normally, and just once I run DockBuilderXXX functions starting with `DockBuilderDockWindow("beginningWindow", ImGuiID("dockId"))`?

**Comment by rokups** [comment]
Here is an example: https://github.com/rokups/rbfx/blob/master/Source/Tools/Editor/Editor.cpp#L636-L653

**Comment by GkqqNkKC** [comment]
Seems overkill for what I want to do... Can't I just set the tab bar padding in the source files?

**Comment by GkqqNkKC** [comment]
MODIFYING SOURCE REPLY

I found out that tab bars intersection is not that there's no space between them. The first one actually goes up until the end of the window (or child), which means the second one is actually a tab bar over another tab bar

This switches the problem to: how to make tab bar to take the width of its group rather than whole window (child)?

USING DOCKING REPLY

Managed to build a default layout. The trick was just to find the main post related the docking, and I were able to dig from there

The problem I encounter: failed to split a node in such a way to "attach" the other ones in order to keep the minimal sizes of other windows. Tried 0.f and -1.f

GENERAL ISSUE REPLY

With the summary at the end of issue start I meant to redirect the reader to the principal idea, not to tell him "forget everything until there" so u can understand the context. I don't especially look to use specific widgets I mentioned, I just want to split the window in minimal sized parts who are titled and can be stacked (like how I used tab bars to put 2 tabs into the same area)

I'm really concerned how to do this, or how u thought this could be done (since I'm sure u had in mind that users might want to build layouts). I will have to fallback to use while developing large childs and brute-force the minimal fixed sizes if there's no other solution

**Comment by GkqqNkKC** [comment]
I will close the issue since I'll treat it as invalid

**Comment by ocornut** [comment]
Apologies for not giving you a better answer, I have been swamped. 

You are pointing out things that are arguably not trivial to setup with dear imgui as of today, which we should improve on, and there are many possible answers here.

I’ve been working on exposing a “WorkRect” api which should answer some of your question better, and I think Docking should also be reworked to facilitate usage of simple layout with moveable splitters, without involving the full docking machinery.
