### ISSUE TITLE
Docking: pressing arrow keys while dragging window crash

### ISSUE THREAD

**Issue by RamiAwar** [ocornut/imgui#3025]
**Docking branch**
Version: latest as of this date
Branch: Docking

Whole application crashes when trying to click right arrow key WHILE dragging the document window.

Replication:
1- Open Demo
2- Examples->Document
3- Drag document, and while dragging, press right arrow key twice, sometimes happens when pressed just once. Has to do with highlighting the checkboxes present there I guess? I have no idea, not a developer of ImGui and very new user.

Code I'm using: copied  from ImGui examples for OpenGL3/GLFW backend. ((ImGui::ShowDemoWindow(...))

I tried debugging using VS 2019, after it crashes I press Retry (in debug mode), and it takes me to exception thrown at the following line in ```imgui.cpp```:
```
        *p_open = false;

    // Update ChildId to allow returning from Child to Parent with Escape
    ImGuiWindow* parent_window = window->DockNode->HostWindow;
    window->ChildId = parent_window->GetID(window->Name);
}

void ImGui::BeginDockableDragDropSource(ImGuiWindow* window)
{
    ImGuiContext& g = *GImGui;
    IM_ASSERT(g.ActiveId == window->MoveId); // <-------------- Breakpoint triggered here
    IM_ASSERT(g.MovingWindow == window);

    window->DC.LastItemId = window->MoveId;
    window = window->RootWindow;
```

Sorry if not enough details were provided, I'm available for questions though. If you can't replicate it talk to me and I could provide more details.

**Comment by ocornut** [comment]
Thank you @RamiAwar for reporting this, this is now fixed by 8836975dcfc770731932ebec3bbb69579fb29071
I am not so happy with the exact nature of the fix but this should do the job. I'll later investigate a more through way to ensure the two values are synchronized.
