### ISSUE TITLE
Begin does not work properly if I pass it a const char * 

### ISSUE THREAD

**Issue by prostotin** [ocornut/imgui#3026]
`ImGui::Begin("Yeet");`
The window will look like this:
![image](https://user-images.githubusercontent.com/37674127/74618680-c7134480-5100-11ea-86c5-b8c5e246895f.png)
Works fine. Begin() takes a const char * as a parameter, so I created one to randomize the Window Name. 

So logically:
`const char* winName = charArr; // charArr contains randoms characters.`
` ImGui::Begin(winName );`
But this does not work. The imgui window is not proper size, and duplicates when i move it around.
![image](https://user-images.githubusercontent.com/37674127/74618760-148fb180-5101-11ea-863c-ace7e8948114.png)
Directx9 implementation

**Comment by ocornut** [comment]
Sorry but #1586 

Didn’t fill requested issue template.
