### ISSUE TITLE
Crash with custom allocators on program exit?

### ISSUE THREAD

**Issue by septag** [ocornut/imgui#303]
There is a situation when crash occurs when using imgui :
- Using non-crt allocator, the allocator destroys on program shutdown
- Call _imguiCreate_ on program init
- shutdown the program and call _imguiDestroy_ 
- Destroy the allocator
- Crash

I guess the problem is with statically defined variable inside imgui.cpp :
```
static ImFontAtlas      GImDefaultFontAtlas;
```
Which allocates some heap inside during the initialization and never releases until the end of program (which dynamic allocator is missing at that point)

As I workaround I added this line to ocornut-imgui/imgui.cpp :
```
void ImGui::Shutdown()
{
    ImGuiState& g = *GImGui;
    GImDefaultFontAtlas.Clear();
```

**Comment by ocornut** [comment]
Thanks. I will add a reference counter to ImGuiState to handle that.

**Comment by ocornut** [comment]
Actually, my answer was wrong.

ImGui::Shutdown already does that:
```
    if (g.IO.Fonts) // Testing for NULL to allow user to NULLify in case of running Shutdown() on multiple contexts. Bit hacky.
        g.IO.Fonts->Clear();
```
And Fonts should point to &GImDefaultFontAtlas.

And the constructor for ImFontAtlas shouldn't create any location. Therefore I'm not sure which bug exactly you are having. Are you setting up the allocators *before* initializing ImGui?

**Comment by septag** [comment]
Yes I am
Actually I'm using it as bgfx's 3rdparty code, which he wrote another layer over it. 
I have to dig more and see what it does exacly and report back ...

**Comment by ocornut** [comment]
@septag Any news on this?

**Comment by ocornut** [comment]
@septag ping

**Comment by ocornut** [comment]
Moving to #396
