### ISSUE TITLE
Setting size for menu

### ISSUE THREAD

**Issue by Remist0** [ocornut/imgui#3030]
**Version/Branch of Dear ImGui:**
Version: 1.74 WIP

**My Issue/Question:**
Version: v1.74 WIP

My question is how I can properly set menu size? I use `SetNextWindowSize` for that but when menu is not open this setting works for next window. 

Upd.: I use `SetNextWindowSizeConstraints` for temporary hack, but maybe there is better solution.

**Screenshots/Video**
![](http://gif.targem.ru/gif/d19856b95f8a06aceea370ad53bf.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
if (ImGui::Begin("TestWndWithMenu"))
{
    ImGui::SetNextWindowSize({200.0f, 600.0f});
    if (ImGui::BeginMenu("Lot of elements"))
    {
        for (uint32_t i = 0; i < 200; ++i)
            ImGui::MenuItem("Item");

        ImGui::EndMenu();
    }
}
ImGui::End();

ImGui::Begin("AnotherTestWnd");
ImGui::End();
```

**Comment by ocornut** [comment]
Hello @Remist0,
Thanks for reporting. This was a menu and I just pushed the fix for it!

**Comment by Remist0** [comment]
Thank you!
