### ISSUE TITLE
SDL numpad enter mapping

### ISSUE THREAD

**Issue by Davido71** [ocornut/imgui#3031]
I'm using SDL (SDL2 version 2.0.10) with a OpenGL3 backend. When I used the flag ImGuiInputTextFlags_EnterReturnsTrue the 'return' key works but the numpad 'enter' does not. 

I fixed it by  changing the following code in imgui_impl_sdl.cpp
```
// From
io.KeyMap[ImGuiKey_KeyPadEnter] = SDL_SCANCODE_RETURN2;

// To
io.KeyMap[ImGuiKey_KeyPadEnter] = SDL_SCANCODE_KP_ENTER;
```

Thought I'd pass it along. Thanks for your work!

**Comment by ocornut** [comment]
Fixed, thank you @Davido71 !
