### ISSUE TITLE
Child Window Scrollbar Flickers during Parent Window resize

### ISSUE THREAD

**Issue by gallickgunner** [ocornut/imgui#3036]
I'm working on my file dialog addon I posted [earlier](https://github.com/gallickgunner/ImGui-Addons) in the gallery and I seem to notice a strange (or maybe not so strange) issue.
![test](https://user-images.githubusercontent.com/40718428/75098119-37740700-55d4-11ea-865a-425889fa201c.png)

As you can notice from the screen, there is a child window that renders a list of all the files and dirs. Since I know the length of the list before opening this said window, I can set the content size. This window shows a horizontal scrollbar depending on whether there are more items than what fits the current size. Currently the list is small, hence no scrollbar.

However, as soon as I quickly stretch the window to the right, a scrollbar appears and then disappears as soon as I slow down the speed with which I'm stretching or stop expanding the window completely as captured in the below screenshot. If you expand the window at a specific speed the scrollbar comes and goes causing flickering.

![test2](https://user-images.githubusercontent.com/40718428/75098216-51621980-55d5-11ea-8152-a8c6c88ffb77.png)

My code is as  simple as,

```
ImGui::SetNextWindowContentSize(ImVec2(content_width, 0));
ImGui::BeginChild("##ScrollingRegion", ImVec2(window_width window_height), true, ImGuiWindowFlags_HorizontalScrollbar);
```

Where for the current call it's guaranteed, that `content_width < window_width`. However if you stretch too quickly, somewhere along the line, I think the *new* `content_width` gets compared with the previous `window_width` which is smaller and the scrollbar appears for the stretching duration.
 Just my dumb guess, from what I could gather by printing the content and window widths.

If you want more code, I'm willing to post more. Anyways thanks for the great library :) and sorry if it's a dumb issue that's already been solved. Didn't find anything regarding this on the net.

**Version/Branch of Dear ImGui:**

Version: 1.75
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Windows

**Comment by ocornut** [comment]
Hello,

> If you want more code, I'm willing to post more. 

A minimal/pastable repro would be helpful there.

Thank you.

**Comment by gallickgunner** [comment]
Really sorry but I think I need a sleep. I have managed to solve the issue, but I'm gonna list a repro and the solution I found.

A minimal basic repro is,
```
ImGui::SetNextWindowSize(ImVec2(200,300), ImGuiCond_Appearing);
if(ImGui::Begin("Test", nullptr))
{
    float width = 300; // dynamic
    float max_content_width = ImGui::GetWindowSize().x - ImGui::GetStyle().WindowPadding.x * 4.0f;    
    if(max_content_width > width)
        width = max_content_width;
    ImGui::SetNextWindowContentSize(ImVec2(width, 0));
    ImGui::BeginChild("##ScrollingRegion", ImVec2(0, 250), true, ImGuiWindowFlags_HorizontalScrollbar);
    {
        //Render a list or whatever
        ImGui::Selectable("abc2", false);
        ImGui::Selectable("abc3", false);
        ImGui::Selectable("abc4", false);
        ImGui::Selectable("abc5", false);
        ImGui::Selectable("abc6", false);
    }
    ImGui::EndChild();
    ImGui::End();
}
```

Note that the `width= 300` is actually dynamic and can change on any frame but set to a constant for simplicity. The idea was to set the content width of the child window to either tha max content size or more (to allow horizontal scroll bars) but not lower than that. 

Instead of doing
```
if(max_content_width > width)
        width = max_content_width;
```
I did
```
if(max_content_width > width)
        width = 0;
```
to allow the content to expand automatically to the max size which solved the issue. Manually setting it to the max content size gives flickering scroll bars during resize. Maybe I didn't calculate the `max_content_width` correctly. Anyways, I'm happy this got solved. You can close the issue, thanks.
