### ISSUE TITLE
Implementing a renderer, not all vertices rendering?

### ISSUE THREAD

**Issue by spacechase0** [ocornut/imgui#3039]
**Version/Branch of Dear ImGui:**

Version: 1.75, according to the demo window
Branch: master, I think? (Using ImGUI.Net, which uses cimgui)

**Back-end/Renderer/Compiler/OS**

Back-ends: [ImGUI.Net](https://github.com/mellinoe/ImGui.NET), porting [imgui-sfml](https://github.com/eliasdaler/imgui-sfml)
Compiler: Not sure what the cimgui build was built with.
Operating System: Windows 10

**My Issue/Question:**

So, I'm using C# to remake/improve upon a tool I made with C++ and imgui-sfml a while back. However, I'm encountering an issue where everything isn't rendering onto the screen. It appears to only render some of the vertices? I attached a video to show what I mean.

I've tried doing things like adding +100 to the amount of vertices I render (to go past what the library is telling me), which does make a little bit more render... but it sometimes will crash from going too far, depending on what I do with the UI.

I'm pretty sure this isn't an issue with ImGui.NET, as I compiled both of their demos and they worked fine. I tried copy+pasting the library files from the working build to my exe as well (in case the NuGet package was out of date or something).

**Screenshots/Video**

![bXNyPFSexb](https://user-images.githubusercontent.com/665679/75183415-8030da80-5710-11ea-95b2-e5f951042c33.gif)

Here are both implementations of renderers I tried: https://gist.github.com/spacechase0/f46cec793c8e10b417ca1cd55118772a (the rest of the code is a straightforward port of imgui-sfml, but you can find it here: https://github.com/spacechase0/ImGuiSfmlNet )

And here is the actual test program:
```csharp
using ImGuiNET;
using ImGuiSfmlNet;
using SFML.Graphics;
using SFML.System;
using System;

namespace ImGuiSfmlTest
{
    class Program
    {
        static void Main(string[] args)
        {
            // NOTE : This is workaround to create a functioning opengl context for OpenTK (for current OpenTK version)
            var gameWindow = new OpenTK.GameWindow();

            var window = new RenderWindow(new SFML.Window.VideoMode(640, 480), "ImGui + SFML + .Net = <3");
            window.SetFramerateLimit(60);
            ImGuiSfml.Init(window);

            window.Closed += (s, e) => window.Close();

            CircleShape shape = new CircleShape(100);
            shape.FillColor = Color.Green;

            Clock deltaClock = new Clock();
            while ( window.IsOpen )
            {
                window.DispatchEvents();

                ImGuiSfml.Update(window, deltaClock.Restart());

                ImGui.ShowDemoWindow();
                //ImGui.ShowTestWindow();

                ImGui.Begin("Hello, world!");
                ImGui.Button("Look at this pretty button");
                ImGui.End();

                window.Clear();
                window.Draw(shape);
                ImGuiSfml.Render(window);
                window.Display();
            }
        }
    }
}
```

I also just discovered the Metrics window, and managed to make that render, if that helps. Included is some console output with what I get from the `ImDrawData` (I'm running `Console.WriteLine("MEOW:" + n + " " + cmd_i + " " + pcmd.ElemCount);` right before the user callback check in the GL renderer.)

<img width="680" alt="devenv_87REnGB2pJ" src="https://user-images.githubusercontent.com/665679/75184491-73ad8180-5712-11ea-8b14-49b6fa2ceea1.png">

I realize this is probably an issue on my end, but any help would be appreciated.

**Comment by spacechase0** [comment]
I compiled the latest master with ImGui-SFML and added the same debug output to it's RenderDrawLists and got almost the same amount of vertices (but everything rendered fine):

![image](https://user-images.githubusercontent.com/665679/75492436-c80c6780-5985-11ea-9c73-62487bcf3719.png)
(The one on the left is the C++ code, the right is the C# code.)

I also copied the imgui.ini from the C++ version to the C# version before running to make sure the same things were showing/hidden, etc.

I assume the 18 vertex difference is due to a difference between master and the version ImGui.NET uses. It certainly doesn't sound like enough to cause the rendering issue.

**Comment by ocornut** [comment]
Hello,
The `ImDrawList` structure has a `const char* _OwnerName` field you can use to facilitate debugging.
I would suggest discussing it on the Discord https://discordapp.com/invite/NgJ4SEP

**Comment by ocornut** [comment]
Hello @spacechase0 

Have you solved your problem?

In all likehood, as you mentioned this is not a problem with Dear ImGui so I may I suggest we close it for now. If you have any more info we'll do our best to help you but we can't help random personal issues dangling in the issues repository. 
Maybe people in the Discord can help you solve your issue?

**Comment by Kyjor** [comment]
Hi @spacechase0 , I know this is a long shot but did you manage to fix this? I’m working on an Imgui implementation with another language and am having this same exact issue. If you have any information that would be greatly appreciated. Thanks!

**Comment by adamwych** [comment]
Don't worry whoever stumbles upon this GitHub issue after researching this issue for too many hours just like me! I FOUND THE SOLUTION!

My scenario: I'm using ImGui.NET + SDL3 renderer to draw ImGUI. I had to implement a custom renderer in **unsafe** C# to make it work and encountered the exact same issue as OP.

Here's the original code (from ImGui repository) that I used as a reference:
https://github.com/ocornut/imgui/blob/18e5d769fd7fc48b809ee3b8f6bef6906289251d/backends/imgui_impl_sdlrenderer3.cpp#L215-L226

This is basically the most important part of the renderer, it extracts vertex data from `ImDrawData` and sends it to SDL.

Here's my **INCORRECT** re-implementation of the same code in unsafe C#:
```csharp
var xy = (float*)(vtxBuffer + (nint)cmd.VtxOffset + 0);
var uv = (float*)(vtxBuffer + (nint)cmd.VtxOffset + 8);
var color = (SDL_Color*)((byte*)vtxBuffer + (nint)cmd.VtxOffset + 16);

var tex = (SDL_Texture*)cmd.GetTexID();
SDL_RenderGeometryRaw8BitColor(
    _renderer,
    tex,
    xy,
    Unsafe.SizeOf<ImDrawVert>(),
    color,
    Unsafe.SizeOf<ImDrawVert>(),
    uv,
    Unsafe.SizeOf<ImDrawVert>(),
    (int)(drawList.VtxBuffer.Size - cmd.VtxOffset),
    (nint)(idxBuffer + (nint)cmd.IdxOffset),
    (int)cmd.ElemCount,
    sizeof(short)
);
```

Here's the **CORRECT, WORKING** version:
```csharp
var xy = (float*)(vtxBuffer + (nint)cmd.VtxOffset + 0);
var uv = (float*)(vtxBuffer + (nint)cmd.VtxOffset + 8);
var color = (SDL_Color*)(vtxBuffer + (nint)cmd.VtxOffset + 16);

var tex = (SDL_Texture*)cmd.GetTexID();
SDL_RenderGeometryRaw8BitColor(
    _renderer,
    tex,
    xy,
    Unsafe.SizeOf<ImDrawVert>(),
    color,
    Unsafe.SizeOf<ImDrawVert>(),
    uv,
    Unsafe.SizeOf<ImDrawVert>(),
    (int)(drawList.VtxBuffer.Size - cmd.VtxOffset),
    (nint)((short*)idxBuffer + (nint)cmd.IdxOffset), // <-- This line is different!
    (int)cmd.ElemCount,
    sizeof(short)
);
```

As you can see, the issue was that I wasn't casting `idxBuffer` to `short*` before adding the offset, so the math was incorrect.
