### ISSUE TITLE
Demo console filter behaves odd

### ISSUE THREAD

**Issue by krumelmonster** [ocornut/imgui#3045]
Version: 24bd33ace808ed77fd1840b19f2b8b4789a3ae62
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp; imgui_impl_glfw.cpp; GLEW
Compiler: gcc 9.2.1
Operating System: GNU/Linux

**My Issue/Question:**

I'm having a hard time getting a proper Logging/Console setup and the "Console" Demo kind of leaves puzzled.

Concerning the filter: My understanding was that you could apply multiple filters and separate them by a comma, however, to my surprise x,-1 and -1,x behave differenty. Is this a bug or desired behaviour?
I couldn't really find a specification on how those filters work and the code doesn't make it obvious to me either.

**Screenshots/Video**

![2020-03-01-172415_450x280_scrot](https://user-images.githubusercontent.com/13542760/75629333-6cd6b100-5be1-11ea-82b6-28ed945d58a6.png)
![2020-03-01-172417_450x280_scrot](https://user-images.githubusercontent.com/13542760/75629334-6d6f4780-5be1-11ea-94a4-2faf97c87c93.png)
![2020-03-01-172422_450x280_scrot](https://user-images.githubusercontent.com/13542760/75629335-6d6f4780-5be1-11ea-8c50-63cf1929906b.png)

**Standalone, minimal, complete and verifiable example:**

see imgui_demo.cpp:3802

**Comment by ocornut** [comment]
See #2435

**Comment by krumelmonster** [comment]
This pr is a year old and has no feedback. The filter functionality isn't really in the scope of a Bloat-free Graphical User interface and the code is hardly documented, readable, or fit for production software. Why not outsource such bits to a separate header where it can be made clear that it may have been abandoned and/or have a lower code quality then the rest of the library?

**Comment by ocornut** [comment]
> This pr is a year old and has no feedback. 

There are about 480 opens tasks/pr here and I am the only person reviewing things thoroughly.
It hasn't been abandoned and although I agree that advanced applications will be likely to want to implement their own, more advanced solution, I don't agree that it's particularly lower code quality, unreadable etc. For the limited scope of what it provides, it is also perfectly fit for production.

FYI 
> to my surprise x,-1 and -1,x behave differenty

This was designed as such as I initially believed it was more flexible to handle it this way. I understand this can be causing confusion and not disagreeing this could be reworked. We can move this discussion to #2435.
