### ISSUE TITLE
Platform-specific Virtual Keyboards

### ISSUE THREAD

**Issue by jay8ee** [ocornut/imgui#3046]
I have looked in the docs, so first let me apologise if this is answered somewhere already.

We are working with a couple of platforms that support virtual system keyboards, some mobile but also some games consoles. We want to be able to show the systems virtual keyboard when there is no physical keyboard attached and be able to take the result from the virtual keyboard and set the value on whatever imGUI control was clicked.

Is there an established pattern for hooking interactions with imGUI controls that accept keyboard input to detect when they get focus and open the system virtual keyboard? Or is this something we will have to implement ourselves?

Thanks.

**Comment by ocornut** [comment]
See FAQ:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-to-my-application
