### ISSUE TITLE
No way i can render popup modal

### ISSUE THREAD

**Issue by fuhranku** [ocornut/imgui#3051]
Greetings. I'm working with OpenGl 3.30 w/ C++

**Version/Branch of Dear ImGui:**

Version: 1.74
Branch: master

**My Issue/Question:**

Modal is not showing under any circumstances. I've read issue #331 and working examples here exposed are not working for me either. A simple case like this won't show anything at all

I initialize ImGui like this:`
```
bool UI::init(GLFWwindow* window) {
	IMGUI_CHECKVERSION();
	ImGui::CreateContext();
	if (!ImGui_ImplGlfw_InitForOpenGL(window, true) || !ImGui_ImplOpenGL3_Init("#version 330 core"))
		return false;
	ImGui::StyleColorsDark();
}
```
My draw function: 
```
void UI::draw() {
	// Start new frame
	ImGui_ImplOpenGL3_NewFrame();
	ImGui_ImplGlfw_NewFrame();
	ImGui::NewFrame();

       // This basic example shows nothing for me
        if (ImGui::BeginMainMenuBar())
        {
            if (ImGui::BeginMenu("menu"))
            {
                if (ImGui::MenuItem("menu item"))
                   ImGui::OpenPopup("popup");
                ImGui::EndMenu();
            }
            ImGui::EndMainMenuBar();
        }

        if (ImGui::BeginPopupModal("popup"))
        {
            ImGui::Text("Lorem ipsum");
            ImGui::EndPopup();
        }

	ImGui::Render();
	ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
}


```

I've been reading all related issues but apparently it should render my modal with this case, and is not working. Everything else works just fine.

**Comment by ocornut** [comment]
Hello,

It seems like you missed the key explanation and solution outlined in #331, e.g.
https://github.com/ocornut/imgui/issues/331#issuecomment-140055181

You have to remember that `OpenPopup()` and `BeginPopup()` are relying on the ID stack:

https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-why-are-multiple-widgets-reacting-when-i-interact-with-a-single-one-q-how-can-i-have-multiple-widgets-with-the-same-label-or-with-an-empty-label

So in your example you are doing the Open while the top of ID stack is "/mainmenubar/menu" and you are trying to Begin into it while the top of the ID stack is "/", so the ID don't match.

**Comment by fuhranku** [comment]
Hello! Thank you for this quick answer! Now i'm trying with boolean flag workaround and it's working now (it seems i did miss key explanation), to be honest ID stack still not 100% clear for me, i'll be diggin more into it. 

Thank you, hopping a smooth and fancy workaround for modals :-)

**Comment by ocornut** [comment]
I'll let you read the linked FAQ, if you still have issue or questions feel free to post here!
