### ISSUE TITLE
Is there a callback functioin for slider?

### ISSUE THREAD

**Issue by mindoff6502** [ocornut/imgui#3052]
I think I need a callback for slider like some other UI,OnValueChanged or something like this.
Does imgui have such thing?I search the source code,and didn't find something like this.
If there is,could someone show me a example?
If not,do I need to code this myself?any easy way to do this?
Thanks.

OK,just use if will get change,stupid I am.

**Comment by YuDang1024** [comment]
I encountered the same problem as you, but I don’t know if it’s too late to answer you now.
I found a way to solve it.
I don't know if it is the best solution, but it can solve the problem.
I use Dear imgui in Lua.
SliderInt function will return a value, this value represents whether the slider of the current slider is being changed, you can judge by this return value,
When it is equal to true, the slider is being slid,
When it is equal to false, the slider is not sliding
