### ISSUE TITLE
Can I render multi font text in one draw?

### ISSUE THREAD

**Issue by mindoff6502** [ocornut/imgui#3054]
Something like this won't work.

```
io.FontDefault = font1;
ImGui::Text("abcdefghijklmnopqrstuvwxyz");
io.FontDefault = font2;
ImGui::Text("ABCDEFGHIJKLMNOPQRSTUVWXYZ");
```

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 

- Please make sure you have read the guidelines.
- Your question is too ambiguous. Use the Discord if you want to ask ambiguous questions.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.

**Comment by ocornut** [comment]
You can use load multiple fonts and use `PushFont()` to select one.
Read `docs/FONTS.txt`
