### ISSUE TITLE
Tables crash with > 31 columns + ScrollY + ScrollFreezeTopRow

### ISSUE THREAD

**Issue by GrigoryGraborenko** [ocornut/imgui#3058]
Version: 1.76 WIP (17502)
Branch: imgui/tree/tables

Back-ends: Qt + https://github.com/seanchas116/qtimgui
Compiler: Visual Studio 2019
Operating System: Windows 10

Hi! I'm part of a team writing a 3D subsea pipeline inspection utility for Fugro. We're currently in the process of creating a prototype replacement for our Unity/C# version. One of the business requirements is that human-created tags/events on pipes are visualized in a spreadsheet-style way. Unfortunately, some of this data is imported, and has a large number of critical fields - some of them more than 32, 

At the moment, creating a table with 32 or more columns will trigger an assertion as soon as you start scrolling down. This happens in particular when I have ImGuiTableFlags_ScrollFreezeTopRow enabled. Sorry I haven't attached a call stack, but even zipped, it's too big for github.

Also, is there any chance that the 64 column limit I've heard about can be set by a preprocessor flag? The data we have to deal with is ill-defined and we might need more than that.

Here's a minimal example:

    ImGui::Begin("Example Bug");
    ImGuiTableFlags flags =
        ImGuiTableFlags_ScrollY
        | ImGuiTableFlags_ScrollFreezeTopRow
        ;

    const double itemsHeight = 20;
    std::vector<std::string> headers;
    for (int i = 0; i < 32; i++) {
        headers.push_back("Header");
    }
    if (ImGui::BeginTable("EventTable", headers.size(), flags, ImVec2(500, 500))) {
        for (auto header = headers.begin(); header != headers.end(); header++)
        {
            ImGui::TableSetupColumn(header->c_str(), ImGuiTableColumnFlags_DefaultSort);
        }
        ImGui::TableAutoHeaders();

        for (int i = 0; i < 100; i++) {
            ImGui::TableNextRow(0, itemsHeight);
            for(auto header = headers.begin(); header != headers.end(); header++)
            {
                ImGui::Text("Data");
                ImGui::TableNextCell();
            }
        }
        ImGui::EndTable();
    }

ImGui::End();

**Comment by ocornut** [comment]
Thanks you Grigory. I could confirm there's a bug in `TableDrawMergeChannels()` with >31 columns and freezing enabled, as the number of draw channel 1+count*2 exceed 64 and this function makes heavy use of 64-bit flags. I'll look into the fix.

> Also, is there any chance that the 64 column limit I've heard about can be set by a preprocessor flag? 

That's a bigger change unfortunately, but I'll keep it in mind.

**Comment by ocornut** [comment]
Should be fixed now, by 339ffd2 + 96a2c461 mostly (and minor 4918a649 3bfc9e8a7)

**Comment by ocornut** [comment]
Also fixed bug where we asserted on 64 columns (limit was incorrectly 63 instead of 64) and added a basic regression tests in our automation framework.

**Comment by GrigoryGraborenko** [comment]
That was amazingly fast turnaround - wasn't expecting that at all! Thank you!

**Comment by GrigoryGraborenko** [comment]
@ocornut Just a heads up - this fix seems to have seriously impacted performance for large number of rows

**Comment by ocornut** [comment]
Hello,

I don’t believe it should have, can you confirm that alternating to a commit before and after with same code makes a difference?

**Comment by GrigoryGraborenko** [comment]
Sorry, my bad, maybe not - likely to have been some code changes on my end. If it is because a particular commit of ImGui I'll create a new issue, but it's definitely not this bugfix that's responsible.
