### ISSUE TITLE
请问用vk怎么在imgui的窗口里面显示图片？

### ISSUE THREAD

**Issue by lucky-sc** [ocornut/imgui#3059]
我创建了vkimage;然后通过vkUpdateDescriptorSets更新到例子中的描述符:g_Descriptor。
虽然能够显示图片，但文字变成了图片；
`    VkDescriptorImageInfo desc_image[1] = {};`
`    desc_image[0].sampler = sampler;//这是我自己创建的 纹理采样器`
`     desc_image[0].imageView = imageView;`
`     desc_image[0].imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;`
`     VkWriteDescriptorSet write_desc[1] = {};`
`     write_desc[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;`
`     write_desc[0].dstSet = g_DescriptorSet;//这是例子中的描述符`
`     write_desc[0].descriptorCount = 1;`
`     write_desc[0].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;`
`     write_desc[0].pImageInfo = desc_image;`
`     vkUpdateDescriptorSets(g_VulkanInitInfo.Device, 1, write_desc, 0, NULL);`

**Comment by Vadmeme** [comment]
你在自我檢疫中嗎?

**Comment by ocornut** [comment]
Hello. We need to keep this service in English here.
If you create a Chinese speaking forum/community for "Dear ImGui", we will add links to it. 

This is currently not supported by the unmodified imgui_impl_vulkan back-ends, see #914.
