### ISSUE TITLE
Feature Request: Blank or null (optional) numerical inputs

### ISSUE THREAD

**Issue by GrigoryGraborenko** [ocornut/imgui#3063]
**Version/Branch of Dear ImGui:**

Version: 1.75
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: Qt
Compiler: MSVC 2019
Operating System: Windows 10

**My Issue/Question:**

Hi! I'm trying to figure out how to make float/double/int inputs nullable or able to be set blank. Currently deleting the entire number will not trigger a IsItemEdited call, nor will it change the pointed-to value.

Ideally, the user would be able to blank out the field, and I could detect that and set a bool or whatever to leave that field blank - by formatting the field with "" instead of "%.3f". I understand that I could have a checkbox there as well, but that's more complicated and unwieldy than being able to just delete the value.

**Comment by ocornut** [comment]
I imagine you would need to implement a custom version of `InputScalar()` which you may copy in your own code files, and then adjust. If you remove the `if (p_step != NULL)` block from that function  you'd be left with a much smaller function. The function signature would need to be able to report that element.

Instead of calling `value_changed = DataTypeApplyOpFromText()` you may have a custom path that checks for empty string.

**Comment by GrigoryGraborenko** [comment]
Hi, thanks for the advice! Here's what I ended up with:

    bool InputNullableDouble(const char* label, double* v, bool& isNull, const char* format, ImGuiInputTextFlags flags)
    {
        flags |= ImGuiInputTextFlags_CharsScientific;
        ::std::string str;
        if (!isNull)
        {
            int buffSize = snprintf(str.data(), 0, format, *v);
            str.resize(buffSize);
            snprintf(str.data(), buffSize, format, *v);
        }

        bool changed = ImGui::InputText(label, &str, flags);
        if (str.length() == 0)
        {
            changed = !isNull;
            isNull = true;
            return changed;
        }
        if (changed)
        {
            isNull = false;
            ImGui::DataTypeApplyOpFromText(str.data(), GImGui->InputTextState.InitialTextA.Data, ImGuiDataType_Double, v, format);
        }
        return changed;
    }

Usage:

                double minVal = filter->m_MinValue.toDouble();
                bool isMinNull = filter->m_MinValue.isNull();
                ImGuiUtils::InputNullableDouble(" to ", &minVal, isMinNull, "%.3f");
                if (ImGui::IsItemEdited())
                {
                    filter->m_MinValue = isMinNull ? QVariant() : QVariant(minVal);
                }
