### ISSUE TITLE
Whole numbers used for style coloring

### ISSUE THREAD

**Issue by JerimiahOfficial** [ocornut/imgui#3064]
Can I use whole numbers instead of float numbers inside of my color styling? When I try using an RGBA format (0 to 255) but the UI always turns out white due to the color values seen as a float value.
e.g
```
colors[ImGuiCol_WindowBg] = ImVec4(0.06f, 0.06f, 0.06f, 0.94f); -> Window background is not white
style.Colors[ImGuiCol_WindowBg] = ImVec{ 255 255, 255, 255}; -> Window background is white
```
I've tried something sort of like this an seemed to work on one of my projects but not on the current project. Would this have been something to do with the version used?
```
void ImGui::StyleColorsDark(ImGuiStyle* dst)
{
     ImColor WindowBg = ImColor(16, 16, 16, 255);
     style.Colors[ImGuiCol_WindowBg] = WindowBg;
}
```

**Comment by rokups** [comment]
Style colors are refined as RGBA floats, 0.0f being black and 1.0f being white. If you want to convert 8 bit integer to a float format do `value * (1.0f / 255.0f)`. `ImColor(16, 16, 16, 255);` should be working just fine. Just make sure you do not mix integer and float types in parameters as `ImColor` has constructors taking 4 floats and 4 ints.

**Comment by JerimiahOfficial** [comment]
> Style colors are refined as RGBA floats, 0.0f being black and 1.0f being white. If you want to convert 8 bit integer to a float format do `value * (1.0f / 255.0f)`. `ImColor(16, 16, 16, 255);` should be working just fine. Just make sure you do not mix integer and float types in parameters as `ImColor` has constructors taking 4 floats and 4 ints.

Thanks, I'll take this into consideration.

**Comment by ocornut** [comment]
Closed as answered by @rokups . Thank you!

Jerimiah please fill the requested template when opening a new issue. You may also use the Discord server http://discord.dearimgui.org to discuss that sort of questions. Thank you.
