### ISSUE TITLE
Multiple calling BeginMainMenuBar during frame

### ISSUE THREAD

**Issue by metarutaiga** [ocornut/imgui#3068]
**Version/Branch of Dear ImGui:**

Version: ea039941
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_osx.mm + imgui_impl_metal.mm
Compiler: Xcode 11.3.1
Operating System: macOS 10.15.3

**My Issue/Question:**

It can't do more call BeginMainMenuBar during frame since docking(multi-viewport) branch.
I found the problem here.

    // Feed back into work area using actual window size
    viewport->CurrWorkOffsetMin.y += GetCurrentWindow()->Size.y;

It would get wrong coordination next call during frame.

**Screenshots/Video**

<img width="199" alt="截圖 2020-03-22 上午11 35 49" src="https://user-images.githubusercontent.com/52752725/77241720-51cfed80-6c31-11ea-8fdf-2dfe29b4909d.png">

**Standalone, minimal, complete and verifiable example:** 

```
    if (ImGui::BeginMainMenuBar())
    {
        if (ImGui::BeginMenu("xxGraphic"))
        {
            ImGui::MenuItem("About xxGraphic", nullptr, nullptr);
            ImGui::EndMenu();
        }
        ImGui::EndMainMenuBar();
    }

    if (ImGui::BeginMainMenuBar())
    {
        if (ImGui::BeginMenu("Sample"))
        {
            ImGui::MenuItem("About Sample", nullptr, nullptr);
            ImGui::EndMenu();
        }
        ImGui::EndMainMenuBar();
    }
```

**Comment by ocornut** [comment]
This should be fixed now, thanks for reporting!
