### ISSUE TITLE
Cannot drag window across monitor border with `ConfigWindowsMoveFromTitleBarOnly` on

### ISSUE THREAD

**Issue by SuperWangKai** [ocornut/imgui#3071]
**Version/Branch of Dear ImGui:**

Version: 1.76 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_dx11.cpp 
Compiler: VS2019
Operating System: Windows 10

**My Issue/Question:**

If I set `ConfigWindowsMoveFromTitleBarOnly` as true, when I dragging a platform window (not the main window) from main monitor to secondary monitor, the platform window cannot move across between the monitors.

The monitor layout is as:
![image](https://user-images.githubusercontent.com/15721569/77306031-005b5780-6d32-11ea-8f7b-90c9d5cc6d6e.png)

This issue is related to https://github.com/ocornut/imgui/blob/16a9488c13f2889726fbcc06cdd224f954501bdd/imgui.cpp#L5528

**Screenshots/Video**
![monitor_issue](https://user-images.githubusercontent.com/15721569/77307130-aeb3cc80-6d33-11ea-8db9-fa0dc04c2ffa.gif)

**Comment by ocornut** [comment]
Should be fixed with 30ba3c3 !
