### ISSUE TITLE
Plot functions registering their ID change from 1.67 to 1.68

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#3072]
Hi, 

There is some old code that was working on 1.67 but stopped to work in 1.68. Basically I draw a PlotLines widget and then some InvisibleButtons over it. What stopped to work was IsItemActive in this lines of code: Previously is_active was true when clicking over this item but in 1.68 stopped to work.

```Lua
ig.SetCursorScreenPos(b_pos)
ig.PushIDStr(ID)
ig.InvisibleButton("",ig.ImVec2(r*2, r*2))
local is_active = ig.IsItemActive()
ig.PopID()
```

I looked in docs/CHANGELOG.txt for changes in 1.68 but I was not able to find any reference to IsItemActive. What could it be?

**Comment by ocornut** [comment]
Most likely it is 
97ed97b8ce55163e470929d78f2d83477524861f

It was previously not registering its it.
If your button covers the same bounding box as the plot widget, you shouldn't need to submit the button at all, just use `IsItemActive()` after the plot.

**Comment by sonoro1234** [comment]
>  just use `IsItemActive()` after the plot.

I am not sure to understand. I was drawing several InvisibleButtons over the PlotLines, so the code posted above was used several times, once for each InvisibleButton. Only one of them was active after mouse click.
If IsItemActive is only used after PlotLines, I wont be able to differentiate which InvisibleButton was clicked?

**Comment by ocornut** [comment]
No you won't but you can test the coordinate.
Otherwise maybe using `SetItemAllowOverlap()` after the Plot function can work.

**Comment by sonoro1234** [comment]
> No you won't but you can test the coordinate.

yes but this changes the logic behind Control_point (which was an independent widget that knows when it is activated) and makes everything less simple.



> Otherwise maybe using `SetItemAllowOverlap()` after the Plot function can work.

I have tried this in 1.68 and does not solve the problem. perhaps in later versions?

**Comment by ocornut** [comment]
I don't know, you can investigate.

**Comment by sonoro1234** [comment]
No, it does not work

This was the self contained ControlPoint

```Lua
function ControlPoint(ID,graph,pos,r)
	r = r or 5
	local origin = graph.origin
	local size = graph.size
	local x,y = pos.x,pos.y
	local xpos = size.x*(x - graph.xmin)/(graph.xmax-graph.xmin)
	local ypos = size.y*(y - graph.ymin)/(graph.ymax-graph.ymin)
	local b_pos = ig.ImVec2(origin.x + xpos - r,origin.y - ypos - r)
	ig.SetCursorScreenPos(b_pos)
	ig.PushIDStr(ID)
	ig.InvisibleButton("pp",ig.ImVec2(r*2, r*2))
	local is_active = ig.IsItemActive()
	ig.PopID()
	local draw_list = ig.GetWindowDrawList()
	draw_list:AddCircleFilled(ig.ImVec2(origin.x + xpos,origin.y - ypos), r, ig.U32(1,0,0,1))
	if is_active then
		print"active"
		local m = ig.GetIO().MousePos
		local xval = graph.xmin + (graph.xmax-graph.xmin)*(m.x - origin.x)/size.x
		local yval = graph.ymin + (graph.ymax-graph.ymin)*(-m.y + origin.y)/size.y
		pos.x = xval
		pos.y = yval
	end
end
```

where graph is PlotLines plus some info about its size ,position and internal coordinate limits. It is a pitty loosing this behaviour.

**Comment by sonoro1234** [comment]
Trying to change the ControlPoint logic I am now using isItemActive just after PlotLines but it never returns true!!
