### ISSUE TITLE
ImGui crashes

### ISSUE THREAD

**Issue by Retr0Hype05** [ocornut/imgui#3077]
So I'm making an auto clicker for my brother so he can farm stuff in some games and I wanted to switch to ImGui for a UI, So I'm pretty sure it has something to do with the loop but I'm not sure. I've been trying new ways to make this and ways to fix this for hours and I've got nothing. If anyone can tell me why it crashes and, tell me how to fix it then that would be really awesome.

`if (ImGui::Button("Toggle"))
            {

                bool Click = false;

                while (1)
                {
                    if (GetAsyncKeyState('F'))
                    {
                        Click = true;
                    }

                    if (GetAsyncKeyState('R'))
                    {
                        Click = false;
                    }

                    if (Click == true)
                    {
                        mouse_event(MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0);
                        Sleep(sliderInt);
                        mouse_event(MOUSEEVENTF_LEFTUP, 0, 0, 0, 0);
                        Sleep(sliderInt);
                    }
                }
                return 0;

            }`

**Comment by ocornut** [comment]
Sorry but #1586
