### ISSUE TITLE
MainMenubar with Imagebutton, image does not fill entire menu

### ISSUE THREAD

**Issue by sparlund** [ocornut/imgui#3080]
**Version/Branch of Dear ImGui:**

Version: ec2a24a (updated 1 day ago or so)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 
Compiler: g++
Operating System: Ubuntu

Hi,

First of all, thanks for a great GUI system. I'm a beginner to everything graphics related but it's still easy to get to work.

I want to have a main menu bar at the _bottom_ of the screen, so I've created a copy of the BeginMainMenuBar that I call BeginBottomMenubar. It uses `SetNextWindowPos(ImVec2(0.0f, g.IO.DisplaySize.y),0, ImVec2(0.0f, 1.0f))` to align the window to the bottom and `SetNextWindowSize(ImVec2(g.IO.DisplaySize.x/2, 50))` to set the size. But when I add an ImageButton to the menu bar, it's only as high as the font size. I want the ImageButton to fill the entire menubar, how do I do this?

I've tried using DisplaySafeAreaPadding, ImGuiStyleVar_FramePadding and some more things that probably doesn't make sense. 

Here's my custom menu function.
```cpp
bool ImGui::BeginBottomMainMenuBar()
{
    ImGuiContext& g = *GImGui;
    g.NextWindowData.MenuBarOffsetMinVal = ImVec2(g.Style.DisplaySafeAreaPadding.x, ImMax(g.Style.DisplaySafeAreaPadding.y - g.Style.FramePadding.y, 0.0f));
    // g.Style.DisplaySafeAreaPadding = ImVec2(100,100);
    SetNextWindowPos(ImVec2(0.0f, g.IO.DisplaySize.y),0, ImVec2(0.0f, 1.0f));
    SetNextWindowSize(ImVec2(g.IO.DisplaySize.x/2, 50));
    PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    PushStyleVar(ImGuiStyleVar_WindowMinSize, ImVec2(0, 0));
    PushStyleVar(ImGuiStyleVar_FramePadding,ImVec2(0,0));
    ImGuiWindowFlags window_flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_MenuBar;
    bool is_open = Begin("##BottomMainMenuBar", NULL, window_flags) && BeginMenuBar();
    PopStyleVar(3);
    g.NextWindowData.MenuBarOffsetMinVal = ImVec2(0.0f, 0.0f);
    if (!is_open)
    {
        End();
        return false;
    }
    return true; //-V1020
}
```
And below is how I implement use it. 
```cpp
if (ImGui::BeginBottomMainMenuBar())
        {
            if (ImGui::BeginMenu("File"))
            {
                if (ImGui::MenuItem("Test"))
                {
                }
                if (ImGui::MenuItem("Test"))
                {
                }
                ImGui::EndMenu();
            }
            if (ImGui::ImageButton((void*)(intptr_t)texture1,ImVec2(60,60)),frame_padding = 0)
            {
            }
            if (ImGui::ImageButton((void*)(intptr_t)texture1,ImVec2(60,60)),frame_padding = 10)
            {
            }
            ImGui::EndMainMenuBar();
        }
```
Look at the bottom of the figure. texture1 is a square 32x32 red image. But as you can see it's only as high as the font, and there is some transparent layer under it that I want to fill up with my textures.
Other than that it's working as I want to.

![Screenshot from 2020-03-28 11-52-01](https://user-images.githubusercontent.com/36102821/77822048-77f10400-70ef-11ea-8489-600f3c7014eb.png)

This is the first time I've created a GitHub issue so I've probably broken some rules or not included enough info, but in that case I'll update. I've looked at issue #1548 (https://github.com/ocornut/imgui/issues/1548) but it does not solve my issue.

thanks, 
Johan

**Comment by ocornut** [comment]
Hello Johan,

`BeginMenuBar()` pushes a ~one line high clipping rectangle (check the functon code).
Popping the clip rect and pushing a dummy one before EndMenuBar() may work.

Otherwise, you may not need to use a menu bar at all, a regular window would work. The menu-bar has a property where you can press Alt to toggle between the scrolling region of a window and the menu-bar region. Here you don't have a main scrolling region for the window so you probably don't care about that property of the menu bar.

**Comment by sparlund** [comment]
Hi,

You were right, it was easier to just use a normal Begin() and specify window and position to the bottom. Don't know why I was so hell bent on using the menu bar function..

Thanks, I'll close this issue.

**Comment by Sudo0x22** [comment]
hello,
if you wanted it to be the whole screen size 

`bool ImGui::BeginBottomMenuBar()
{
    ImGuiContext& g = *GImGui;
    g.NextWindowData.MenuBarOffsetMinVal = ImVec2(g.Style.DisplaySafeAreaPadding.x, ImMax(g.Style.DisplaySafeAreaPadding.y - g.Style.FramePadding.y, 0.0f));
    // g.Style.DisplaySafeAreaPadding = ImVec2(100,100);
    SetNextWindowPos(ImVec2(0.0f, g.IO.DisplaySize.y), 0, ImVec2(0.0f, 1.0f));
    SetNextWindowSize(ImVec2(g.IO.DisplaySize.x, g.NextWindowData.MenuBarOffsetMinVal.y + g.FontBaseSize + g.Style.FramePadding.y));
    PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    PushStyleVar(ImGuiStyleVar_WindowMinSize, ImVec2(0, 0));
    ImGuiWindowFlags window_flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_MenuBar;
    bool is_open = Begin("##BottomMainMenuBar", NULL, window_flags) && BeginMenuBar();
    PopStyleVar(2);
    g.NextWindowData.MenuBarOffsetMinVal = ImVec2(0.0f, 0.0f);
    if (!is_open)
    {
        End();
        return false;
    }
    return true; //-V1020
}`

**Comment by Sudo0x22** [comment]
hello,
if you wanted it to be the whole screen length

> bool ImGui::BeginBottomMenuBar()
{
    ImGuiContext& g = *GImGui;
    g.NextWindowData.MenuBarOffsetMinVal = ImVec2(g.Style.DisplaySafeAreaPadding.x, ImMax(g.Style.DisplaySafeAreaPadding.y - g.Style.FramePadding.y, 0.0f));
    // g.Style.DisplaySafeAreaPadding = ImVec2(100,100);
    SetNextWindowPos(ImVec2(0.0f, g.IO.DisplaySize.y), 0, ImVec2(0.0f, 1.0f));
    SetNextWindowSize(ImVec2(g.IO.DisplaySize.x, g.NextWindowData.MenuBarOffsetMinVal.y + g.FontBaseSize + g.Style.FramePadding.y));
    PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
    PushStyleVar(ImGuiStyleVar_WindowMinSize, ImVec2(0, 0));
    ImGuiWindowFlags window_flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_MenuBar;
    bool is_open = Begin("##BottomMainMenuBar", NULL, window_flags) && BeginMenuBar();
    PopStyleVar(2);
    g.NextWindowData.MenuBarOffsetMinVal = ImVec2(0.0f, 0.0f);
    if (!is_open)
    {
        End();
        return false;
    }
    return true; //-V1020
}
