### ISSUE TITLE
How to restrict NoMove to window title?

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#3081]
**Version/Branch of Dear ImGui:**

Version: 1.70
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui .net
Operating System: win10

**My Issue/Question:**
For our application dragging windows at the content-area causes undesired user interaction problems. We would prefer a setting that restricts the draggable area to the Window's title bar (similar to Win10 or MacOS). Currently `ImGuiWindowFlags.NoMove` also disables dragging the title bar. 

For some windows, we implemented the following work-around in our window manager...

```
                if (PreventWindowDragging)
                    ImGui.BeginChild("inner", ImGui.GetWindowContentRegionMax()- ImGui.GetWindowContentRegionMin(), false, ImGuiWindowFlags.NoMove);

                DrawContent();

                if (PreventWindowDragging)
                    ImGui.EndChild();
                
                ImGui.End();
```

Sadly this causes side effects when adding splitters and other sub windows.

Is there a window-flag like `ImGuiWindowFlags.NoMoveAtContentArea`? Or do you have advice how to implement this behaviour?

**Comment by ocornut** [comment]
Hello,

There is a global configuration flag in the IO structure to do exactly that.

Omar

**Comment by pixtur** [comment]
Found it! `ConfigWindowsMoveFromTitleBarOnly` 

Thanks a lot!
