### ISSUE TITLE
antialiased lines

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#3082]
Version: 1.75
Branch: master

Back-ends: glfw and opengl3 from cimgui

Operating System: widows7

I dont get antialiased lines with this code

```Lua
local points = {}
local pointsI 
function GL.imgui()
	local igio = ig.GetIO()
	local mpos = igio.MousePos
	local dl = ig.GetForegroundDrawList()
	dl.Flags = bit.bor(dl.Flags,ig.lib.ImDrawListFlags_AntiAliasedLines)

	if igio.MouseClicked[0] then
		points[#points+1]= ig.ImVec2(GL:ScreenToViewport(mpos.x, mpos.y))
		pointsI = ffi.new("ImVec2[?]",#points)
	end

	for i=1,#points do 
		pointsI[i-1] = ig.ImVec2(GL:ViewportToScreen(points[i].x,points[i].y))
		dl:AddCircleFilled(pointsI[i-1], 4, ig.U32(1,0,0,1))
	end
	dl:AddPolyline(pointsI,#points,ig.U32(1,1,0,1),true, 2)
end
```
![GIF](https://user-images.githubusercontent.com/1795930/77847874-8529f380-71c0-11ea-874b-33191d49cb57.gif)

am I doing something wrong?

My second question would be: Is there any workaround to avoid converting coordinates from viewport space to screen space every frame?
(As in my framework `anima` there are both reference spaces where viewport is a fixed size FBO centered in a variable screen (window) size)

**Comment by ocornut** [comment]
Acute angles are wrongly rendering, see #2183, #2964

> Is there any workaround to avoid converting coordinates from viewport space to screen space every frame?

Use ImDrawList callbacks to pass e.g. projection matrixes to your custom rendering loop, and apply those projection in the render loop.

**Comment by sonoro1234** [comment]
> Use ImDrawList callbacks to pass e.g. projection matrixes to your custom rendering loop, and apply those projection in the render loop.
 
There is still to few information for me in:
https://github.com/ocornut/imgui/search?q=%22ImDrawList+callbacks%22&unscoped_q=%22ImDrawList+callbacks%22&type=Issues

May be some day we have a worked example?

**Comment by ocornut** [comment]
I can’t provide examples for every possibility under the sun especially one that requires a modified render loop.

Check how the render function you are using is setting its projection matrix and use callbacks to change that matrix.
