### ISSUE TITLE
Error 0xc000007b after updating ImGui files...

### ISSUE THREAD

**Issue by Darkratos** [ocornut/imgui#3084]
**Version/Branch of Dear ImGui:**

Version: 1.76
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp 
Compiler: VS2019
Operating System: Windows 7 x64

**My Issue/Question:**

It's simple, yet quite annoying.
I was using an older version of the docking branch, and everything was perfect.
The previous working version is 1.72.
Today, I decided to update the ImGui files, and now, everytime I try to run the
exe, an error shows up, saying the app couldn't be initialized correctly( 0xc000007b ).
I made 0 changes to the code, except changing the ImGui::Begin from 5 args to 3
and adding the ImGui::SetNextWindowSize before that.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/49787965/77855049-662d6080-71c4-11ea-9650-58333ab6bdae.png)
Sorry, the message is in my native language( PT-BR ), but I've translated it at the error
description.

**Comment by ocornut** [comment]
Please provide the information requested by Issue Guidelines and we can reopen this topic.
