### ISSUE TITLE
add .gitignore

### ISSUE THREAD

**Issue by CobbsLab** [ocornut/imgui#3088]
hi,

would be nice add a .gitignore file to avoid the .DS_Store file

**Comment by ocornut** [comment]
Hello,
There's already one in the examples/ folder where all editing artifacts should be created.

**Comment by CobbsLab** [comment]
ok nice but
I do not know why
I have a .DS_Store file in the root directory

**Comment by ocornut** [comment]
This is very frustrating because, having .gitignore in examples/ was a nice way of communicating and ensuring that artifacts are only produced in the examples/ folder.

I have no moved .gitignore to the root folder to solve this :/

Thank you!

**Comment by thewoz** [comment]
thanks
