### ISSUE TITLE
How to use opengl glfw3 render in a imgui window?

### ISSUE THREAD

**Issue by sysescool** [ocornut/imgui#3089]
I have no idea about it...
and it drives me crazy...
really need help.

https://stackoverflow.com/questions/60955993/how-to-use-opengl-glfw3-render-in-a-imgui-window

**Comment by ocornut** [comment]
Sorry but this is an OpenGL issue not a Dear ImGui issue. Please ask on OpenGL communities or you may use our Discord chat.

**Comment by sysescool** [comment]
sorry about it.
