### ISSUE TITLE
Problem using imgui in dxhook

### ISSUE THREAD

**Issue by zl950402** [ocornut/imgui#309]
like http://puu.sh/jRhy8/601f10c325.png

**Comment by Philpax** [comment]
It looks like you're not clearing your render target at the start of a new frame.

**Comment by zl950402** [comment]
if (!bInit)
	{

		ImGui_ImplDX9_Init(targetWindow, pDevice);
			drawGUI = true;
		bInit = true;
	}
	if (drawGUI)
	{
		ImGui_ImplDX9_NewFrame();
		
		// 1. Show a simple window
		// Tip: if we don't call ImGui::Begin()/ImGui::End() the widgets appears in a window automatically called "Debug"
		{
			static float f = 0.0f;
			ImGui::Text("Hello, world!");
			ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
			ImGui::ColorEdit3("clear color", (float*)&clear_col);
			if (ImGui::Button("Test Window")) show_test_window ^= 1;
			if (ImGui::Button("Another Window")) show_another_window ^= 1;
			ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
		}

		// 2. Show another simple window, this time using an explicit Begin/End pair
		if (show_another_window)
		{
			ImGui::SetNextWindowSize(ImVec2(200, 100), ImGuiSetCond_FirstUseEver);
			ImGui::Begin("Another Window", &show_another_window);
			ImGui::Text("Hello");
			ImGui::End();
		}

		// 3. Show the ImGui test window. Most of the sample code is in ImGui::ShowTestWindow()
		if (show_test_window)
		{
			ImGui::SetNextWindowPos(ImVec2(650, 20), ImGuiSetCond_FirstUseEver);
			ImGui::ShowTestWindow(&show_test_window);
		}
	
		ImGui::Render();
	//	ImGui_ImplDX9_Shutdown();
	}
	

	return pEndScene(pDevice);

**Comment by paulsapps** [comment]
P.S it is nice to leave the original issue in here so that anyone with the same problem knows what the fix is!

**Comment by zl950402** [comment]
ok, can u post proper code pls?

**Comment by ocornut** [comment]
There's no picture. Can you upload the picture using GitHub.
Have you fixed your issue? If it's fixed we can close it.

**Comment by zl950402** [comment]
![20150828144256](https://cloud.githubusercontent.com/assets/3389647/9540593/18312560-4d93-11e5-9fc3-a36613bd6723.png)

nice gui! 
it like this when i drag the window

**Comment by zl950402** [comment]
if (showgui)
		{
			ImGui_ImplDX9_NewFrame();
			// 1. Show a simple window
			// Tip: if we don't call ImGui::Begin()/ImGui::End() the widgets appears in a window automatically called "Debug"
			{
				static float f = 0.0f;
				ImGui::Text("Hello, world!");
				ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
				ImGui::ColorEdit3("clear color", (float*)&clear_col);
				if (ImGui::Button("Test Window")) show_test_window ^= 1;
				if (ImGui::Button("Another Window")) show_another_window ^= 1;
				ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
			}

			// 2. Show another simple window, this time using an explicit Begin/End pair
			if (show_another_window)
			{
				ImGui::SetNextWindowSize(ImVec2(200, 100), ImGuiSetCond_FirstUseEver);
				ImGui::Begin("Another Window", &show_another_window);
				ImGui::Text("Hello");
				ImGui::End();
			}

			ImGui::Render();
		}

**Comment by ocornut** [comment]
You are not clearing your target/framebuffer before Render.

**Comment by zl950402** [comment]
how to clear that ? 
like this?
        g_pd3dDevice->SetRenderState(D3DRS_ZENABLE, false);
        g_pd3dDevice->SetRenderState(D3DRS_ALPHABLENDENABLE, false);
        g_pd3dDevice->SetRenderState(D3DRS_SCISSORTESTENABLE, false);
        D3DCOLOR clear_col_dx = D3DCOLOR_RGBA((int)(clear_col.x*255.0f), (int)(clear_col.y*255.0f), (int)(clear_col.z*255.0f), (int)(clear_col.w*255.0f));
        g_pd3dDevice->Clear(0, NULL, D3DCLEAR_TARGET | D3DCLEAR_ZBUFFER, clear_col_dx, 1.0f, 0);

**Comment by zl950402** [comment]
hi ocornut, can you give me a example please.

**Comment by ocornut** [comment]
Yes

**Comment by zl950402** [comment]
but that clears all background how to fix that ?

**Comment by ocornut** [comment]
Have a look at directx9_example/ it is doing only that.

**Comment by zl950402** [comment]
yeah i know that, but this is going to clear all background 
{
			pDevice->SetRenderState(D3DRS_ZENABLE, true);
			pDevice->SetRenderState(D3DRS_ALPHABLENDENABLE, false);
			pDevice->SetRenderState(D3DRS_SCISSORTESTENABLE, false);
			D3DCOLOR clear_col_dx = D3DCOLOR_RGBA(255,255,255,0);
			pDevice->Clear(0, NULL, D3DCLEAR_TARGET | D3DCLEAR_ZBUFFER, clear_col_dx, 1.0f, 0);
}

it dont have that problem when i drag the miniumed bar

![20150828152538](https://cloud.githubusercontent.com/assets/3389647/9541297/5e719e5a-4d99-11e5-82e6-93dc722525dd.png)

![20150828152545](https://cloud.githubusercontent.com/assets/3389647/9541298/60345dfe-4d99-11e5-95ad-356ffce2d30c.png)

**Comment by ocornut** [comment]
Then clear earlier, before you draw your background.

**Comment by zl950402** [comment]
cant be earlier..

why the minium bar is dragable, but the full window isn't ?

when double click the title it goes normal and dragable. How to fix that in the src? Because i dont think clear is a good way. thanks :) 

![20150828154709](https://cloud.githubusercontent.com/assets/3389647/9541575/251b9c34-4d9c-11e5-89e5-a6310f58dbb4.png)

![20150828154717](https://cloud.githubusercontent.com/assets/3389647/9541576/26ad9278-4d9c-11e5-9d69-9acae0c7cf58.png)

**Comment by ocornut** [comment]
I'm not sure what you mean by "but this is gonna clear everything" "cant be earlier", you need to clear your framebuffer at some point. Not sure to understand your draggable issue either.
I can't really give DirectX9 technical support at this point.

**Comment by zl950402** [comment]
this is my endscene ive tried to clear, but it wont work.. only EndScene is in using
HRESULT WINAPI nEndScene(LPDIRECT3DDEVICE9 pDevice)
{	
	if (!bInit)
	{
		ImGui_ImplDX9_Init(targetWindow, pDevice);
		bInit = true;
	}

	if (drawGUI)
	{
			ImGui_ImplDX9_NewFrame();
			// 1. Show a simple window
			// Tip: if we don't call ImGui::Begin()/ImGui::End() the widgets appears in a window automatically called "Debug"
			{
				static float f = 0.0f;
				ImGui::Text("Hello, world!");
				ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
				ImGui::ColorEdit3("clear color", (float*)&clear_col);
				if (ImGui::Button("Test Window")) show_test_window ^= 1;
				if (ImGui::Button("Another Window")) show_another_window ^= 1;
				ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
			}

			// 2. Show another simple window, this time using an explicit Begin/End pair
			if (show_another_window)
			{
				ImGui::SetNextWindowSize(ImVec2(200, 100), ImGuiSetCond_FirstUseEver);
				ImGui::Begin("Another Window", &show_another_window);
				ImGui::Text("Hello");
				ImGui::End();
			}

			ImGui::Render();
		}

	return pEndScene(pDevice);
}

**Comment by ocornut** [comment]
You need to clear your frame buffer.
Sorry I don't do Skype support.

**Comment by zl950402** [comment]
ok thanks for help
