### ISSUE TITLE
Getting imGui working with Point Cloud Library

### ISSUE THREAD

**Issue by victoryc** [ocornut/imgui#3093]
Has anyone here gotten imGui working with PCLVisualizer of Point Cloud Library? 

Thanks.

**Comment by kerm1t** [comment]
option: write your own visualizer in OpenGL as VTK gets slow soon, e.g. https://github.com/kerm1t/PAuLaFAST

**Comment by victoryc** [comment]
I was able to get ImGui working with point cloud library & VTK. For the benefit of anyone else needing to do this in future: The idea I used was to create a subclass of vtkRenderer to render ImGui and add it as an additional renderer to PCLVisualizer's render window.
