### ISSUE TITLE
Relation between FindGlyph and unicode writting as text

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#3094]
Hello,

I cant understand the relation between the code used in FindGlyph (which for ICON_FA_HAND_O_UP of font-awesome4 is 0xF0A6) and the unsigned chars needed for making it appear in ImGui:Text (which for this character is 0xef,0x82,0xa6)
Could you please help me understanding if there is any relation?

Thanks

**Comment by ocornut** [comment]
Characters are encoded as UTF-8 inside strings, it is a pretty standard (if not the most standard) encoding scheme which is backward compatible with ASCII.

For example in https://www.branah.com/unicode-converter
If you enter \uF0A6 in the UTF-16 box you will see \xef\x82\xa6 in the UTF-8 box.

There are some helpers UTF-8<>wchar functions in imgui_internal.h and maybe OS/librairies have functions like that. 

Compare
https://github.com/juliettef/IconFontCppHeaders/blob/master/IconsFontAwesome4.h
`#define ICON_FA_HAND_O_UP u8"\uf0a6"`

https://github.com/juliettef/IconFontCppHeaders/blob/master/IconsFontAwesome4_c.h
`#define ICON_FA_HAND_O_UP "\xef\x82\xa6"`

This is the exact same value, the first code is a modern C++ extension to use Unicode point in literals (the \u part) and convert to UTF-8 (the u8 part).

**Comment by sonoro1234** [comment]
Great thaks for solving the puzzle!!
