### ISSUE TITLE
I can't load an icon font for my menu

### ISSUE THREAD

**Issue by RugerNey** [ocornut/imgui#3095]
`	ImGuiIO& io = ImGui::GetIO();
	io.Fonts->AddFontDefault();
	ImWchar ranges[] = { 0xf000, 0xf3ff, 0 };
	ImFontConfig config;
	config.MergeMode = true;
	font_w = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Guns 1.ttf", 16.0f, &config); // , ranges);`
As you can see, I did everything by example. Then I wrote this code in my menu:
`ImGui::PushFont(font_w);
			ImGui::Text(u8"ABCDE");
			ImGui::PopFont();`
But the menu does not show the desired result.
Instead of a font with weapons, I see simple letters.
I'm still a novice. More detailed information and an answer will help me a lot. Thanks

**Comment by ocornut** [comment]
Sorry but #1586.
