### ISSUE TITLE
Is it possible to load ttf without knowing ranges?

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#3096]
Hello,

I would like to implement a `.ttf` viewer. Just load the font and see which are the codepoints and show the character but without knowing the cp ranges present in this font file.
Is this possible?
Perhaps giving an enormous range?
Which would be a good range in this case?

Thanks

**Comment by ocornut** [comment]
Hello Victor,

In recent version if you pass a full range e.g. 0..FFFF it will only load the available glyphs.

There's a little bit of loss as the two lookup tables will be necessarily maxxed up (we can improve that in the library, triming them to last required characters) but it's a minor issue.

Victor I must say you have been asking many questions that could be solved by looking a comments or trying thing out yourself with a few lines of code. Please be mindful of my work time. 

Cheers.

**Comment by sonoro1234** [comment]
> Victor I must say you have been asking many questions that could be solved by looking a comments or trying thing out yourself with a few lines of code. Please be mindful of my work time.

Sorry about that. Yes, I could have guessed 0..FFFF but as it is not in the docs I was unsure.
Sorry again.

**Comment by ocornut** [comment]
That said, it's always good to have more references in the Github threads (this is why I am also trying to get all issues tagged).

(I have noted that we can improve lookup tables storage now)

**Comment by sonoro1234** [comment]
I just checked that the valid maximal range is `0x0020,0xFFFF` because `0x0000,0xFFFF` does not load font or even crashes.
Another observation is that 

```cpp
#define FONT_ICON_FILE_NAME_MDI "materialdesignicons-webfont.ttf"

#define ICON_MIN_MDI 0xF68C
#define ICON_MAX_MDI 0xF13B5
```

cant be loaded probable because the greater codepoint exceeds ImWchar16, I guess it could be loaded when ImGui uses ImWchar32

**Comment by ocornut** [comment]
0 signify the end of ranges otherwise we would have no way to know the size, 0x0001,0xFFFF would work as well.

> 0xF13B5 cant be loaded probable because the greater codepoint exceeds ImWchar16, I guess it could be loaded when ImGui uses ImWchar32

Yes that's correct.
