### ISSUE TITLE
Set border color of focused window?

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#3097]
**Version/Branch of Dear ImGui:**
Version: 1.70
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui.net
Operating System: win10

**My Issue/Question:**
This is a minor detail and I could find a work around. Nevertheless I was wondering if it is possible to set the board color of the focused window. Right now, only the header is being used to indicate focus. In our app, we deal a lot with hotkeys, and many of them are only relevant for the current window.

Ideally, I would do something like this, but I don't know if the window is focused before actually beginning it...
```
            ImGui.PushStyleColor(ImGuiCol.Border, isFocused ? Color.Blue : Color.Black);
            if (ImGui.Begin(Config.Title, ref Config.Visible, WindowFlags))
            {
                   // do stuff
            }
            ImGui.PopStyleColor();
```

**Recent example screenshot**

![image](https://user-images.githubusercontent.com/1732545/78378035-b34c7080-75d0-11ea-9712-d4dd0425cbab.png)

**Comment by ocornut** [comment]
I'd suggest disabling border color then drawing it after the Begin() call over the window?

**Comment by pixtur** [comment]
Thanks for the quick answer. That was one of the work arounds I had in mind.
