### ISSUE TITLE
Canvas Renders too much pixels and Program stuck 

### ISSUE THREAD

**Issue by Molers** [ocornut/imgui#3098]
----

**Version/Branch of Dear ImGui:**

Version: v1.64
Branch: master

**Back-end/Renderer/Compiler/OS**

Operating System: Windows

**My Issue/Question:**

I have been uncomment  #define ImDrawIdx unsigned int in imconfig.h
 My question is how to let the program not too much slow,when the canvas window show,the program not responding or  freeze(stuck) and i can not drag anything and do anything ,How can I Optimize code or change something in order to Let my program run fast,not stuck.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/23693269/78468755-490d0a80-774d-11ea-87aa-4df349560984.png)

**Standalone, minimal, complete and verifiable example:**
```
ImVec2 canvas_pos = ImGui::GetCursorScreenPos(); 
 ImVec2 canvas_size;
canvas_size.x = 400;
canvas_size.y =400;
for (int r = 0; r < vres; r++)		
              for (int c = 0; c <= hres; c++)  
{
 draw_list->AddRectFilled(ImVec2(canvas_pos.x + r, canvas_pos.y + c), ImVec2(canvas_pos.x + (r+1), canvas_pos.y + (c+1)), IM_COL32(100, 255, 255, 255));
}
ImGui::End();
```

**Comment by ocornut** [comment]
You may disable anti-aliasing and it’ll be a little faster, but otherwise if you want to do per pixel manipulation you shouldn’t be using ImDrawList polygon based primitives they are going to be too heavy. use textures from your graphics system.

**Comment by Molers** [comment]
Thank you for your answer,it seems not work much through disable anti-aliasing,and in fact as you say 
I want to do per pixel manipulation,because it was a renderer. 
in my reference code ,it use thread to implementation in other GUI wxwidget called wxthread 

[raytracegroundup](http://www.raytracegroundup.com/author.html)

**Comment by ocornut** [comment]
Please refer to the usage of textures in your preferred graphics API, dear imgui’s ImDrawList won’t be able to help you meaningfully for pixel manipulation.
