### ISSUE TITLE
Multiple windows attached to one

### ISSUE THREAD

**Issue by artemking4-Projects** [ocornut/imgui#3099]
**Version/Branch of Dear ImGui:**

Version: Last
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_d3d9.cpp + imgui_impl_win32.cpp
Operating System: Windows x86

**My Issue/Question:**

I want to simply attach some windows, to another, root window. Just like it is on this image:
https://cdn.discordapp.com/attachments/625026346405330966/696346745419857980/unknown.png
How can this be properly done?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 

- Please make sure you have read the guidelines.
- Please provide more complete, your post is too ambiguous.
- Please clarify what you have tried.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing for now.

**Comment by artemking4-Projects** [comment]
Done.

**Comment by ocornut** [comment]
You could be querying the pos/size of the central window then using SetNextWindowPos()/SetNextWindowSize() on the left and right window, what is the problem with that?

Note that you may find the Docking #2109 useful, and specifically what you are aiming at in a generalized way would be covered by Photoshop-style docking which as been discussed (#2248) but is unlikely to happen very soon.

**Comment by artemking4-Projects** [comment]
The problem is, that when i focus on any window of theese, they get on top, but others dont.
I tried using IsWindowFocused+FocusWindow, but this is gonna be painful when you have more than two windows.

**Comment by artemking4-Projects** [comment]
Here is a screenshot of what i mean
![c95f6377](https://user-images.githubusercontent.com/21024632/78552598-38c65f80-7821-11ea-8328-83c1bd5c068f.png)

**Comment by ocornut** [comment]
I don't understand why the focus would matter, your first example suggests non-overlapping windows and now you are showing showing completely different. And it's hard to understand what you've tried.

**Comment by ocornut** [comment]
My bad, should have seen the clues,
Sorry but #1586
