### ISSUE TITLE
Problem with Columns

### ISSUE THREAD

**Issue by chenas** [ocornut/imgui#310]
I draw a table with columns, it shows Y scrollbar when it's small enough. But it won't show X scrollbar.
![1](https://cloud.githubusercontent.com/assets/3212124/9541810/4dc880aa-4d9e-11e5-9e0b-73eb97e8c129.png)

**Comment by ocornut** [comment]
There's no horizontal scrollbar in ImGui yet.

**Comment by ocornut** [comment]
What you can do as a workaround is initially set the window width to be bigger and/or the column width to be smaller (using SetColumnOffset once).

**Comment by ocornut** [comment]
Horizontal scrolling added, see #246
