### ISSUE TITLE
How can i input a ImVec4 color?

### ISSUE THREAD

**Issue by RandomNotDev** [ocornut/imgui#3103]
Hi, I want to make a system that allows the user to set the colors of the application buttons, I'm using this code to select the color:

int col[4];
ImGui::PushItemWidth(280.0f);
ImGui::ColorEdit3("Select theme color",(float*)col);

With this, i can select the color that i want, but how can i set it to the buttons? I've tried it:

int col;
ImVec4* colors = style.Colors;
colors[ImGuiCol_Button] = ImVec4(col);

But it returns this error: https://prnt.sc/rtmjvo

Please help me, and thanks!

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 

- Please make sure you have read the guidelines.
- This is not the place to ask C++ learning questions, sorry. Please try on StackOverflow.

Closing.

**Comment by Qehhre** [comment]
style.Colors[ImGuiCol_Button] = ImColor(0,0,0,255); xDDD use rgb
