### ISSUE TITLE
Embed font file into executable

### ISSUE THREAD

**Issue by OverShifted** [ocornut/imgui#3104]
Hi.
I'm trying to load some font actually "Roboto-Light.ttf" for my game engine
[github.com/OverShifted/OverEngine (pretty much same as TheCherno/Hazel)](https://github.com/OverShifted/OverEngine)
here is my code:
```
ImGuiIO& io = ImGui::GetIO();
ImFont* Font = io.Fonts->AddFontFromFileTTF("d:/d.ttf",20.0f);
```
[OverEngine/src/OverEngine/ImGui/ImGuiLayer.cpp](https://github.com/OverShifted/OverEngine/blob/master/OverEngine/src/OverEngine/ImGui/ImGuiLayer.cpp) line 99
I've also tryed this:
```
ImFont* Font = io.Fonts->AddFontFromFileTTF("d:/d.ttf", 20.0f, NULL, io.Fonts->GetGlyphRangesDefault());
```
but for both; This dialog comes up:
![Dialog image](https://user-images.githubusercontent.com/53635046/78536536-e9167280-77e5-11ea-8cea-215da7591e97.PNG)

and this message appears in console:
```
Assertion failed: !Locked && "Cannot modify a locked ImFontAtlas between NewFrame() and EndFrame/Render()!", file D:\overenginedev\fromscratch\OverEngine\OverEngine\vendor\imgui\imgui_draw.cpp, line 1780

D:\overenginedev\fromscratch\OverEngine\OverPlayerExec\..\bin\Debug-windows-x86_64\OverPlayerExec\OverPlayerExec.exe (process 11684) exited with code 3.
```
what should I do?

and the last question:
relative paths to the font is related to final .exe file or source file?
I mean if we have :
```
ImFont* Font = io.Fonts->AddFontFromFileTTF("font.ttf",20.0f);
```
font should be in same directory as _source.cpp_ file for example or near _.exe_ file?

DearImgui 1.76 WIP docking branch
compiler and IDE: Visual studio 2019
Impl files: glfw and opengl3

**Comment by OverShifted** [comment]
Opps excuse me every one If I put add font before newframe(); it will be fixed 😨

**Comment by OverShifted** [comment]
But how to embed file in executable file?

**Comment by rokups** [comment]
> But how to embed file in executable file?

This is a general programming question unrelated to Dear ImGui. Please ask on stackoverflow or similar platform.

**Comment by OverShifted** [comment]
> > But how to embed file in executable file?
> 
> This is a general programming question unrelated to Dear ImGui. Please ask on stackoverflow or similar platform.

I know. but what about [binary_to_compressed_c.cpp ( goto line 253)](https://github.com/ocornut/imgui/blob/master/docs/FONTS.txt)
It is part of Imgui and I didn't get that from _docs/FONTS.txt_

**Comment by ocornut** [comment]
> and the last question: relative paths to the font is related to final .exe file or source file?

This is related to your current working directory, which is configurable in your IDE.

Your first question - where you literally quoted the answer which was displayed in the answer - suggest you aren’t putting much effort solving your problems and searching and for available information. Please do some more research.
