### ISSUE TITLE
Tooltips outside of ImGui display elements

### ISSUE THREAD

**Issue by tim-rex** [ocornut/imgui#3106]
**Version/Branch of Dear ImGui:**

Version: 1.76 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: OpenGL 4.6
Compiler: Visual Studio 2019
Operating System: Windows 10

**Question**
I'm trying to use SetTooltip() at arbritrary screen coordinates that are unknown to ImGui.  I only want to draw those tooltips on areas of the screen that are not already occupied by existing ImGui windows or widgets.

Is there a canonical way to query if a given screen coordinate is already occupied by some window/widget?  Or if I can iterate over all known window positions and determine this for myself?  I could potentially use that to decide wether to generate the tooltip.

I only see calls to reference the current window (which I guess is in line with the whole _immediate_ mode thing).  Probably this is state that I would need to track myself?

Another option would be if I can somehow set the Z-order of tooltips (perhaps selectively) to draw behind other ImGui display elements..

**Comment by ocornut** [comment]
Hello,

> Or if I can iterate over all known window positions and determine this for myself? I could potentially use that to decide wether to generate the tooltip.

You can iterate `g.Windows`, filter out the ones where `window->WasActive == false`, and for the remaining ones feed their bounding box into your algorithm. 

My gut feeling is that you are not solving the right thing, by definition you cannot guarantee that some space is "available" (no imgui window) on the screen so you'll algorithm would need a plan B either way.

> Another option would be if I can somehow set the Z-order of tooltips (perhaps selectively) to draw behind other ImGui display elements..

I don't understand the connection between this and the problem stated above. They are contradicting each others, if you want to guarantee your tooltip don't overlap anything, the Z order should not matter to you. 

Maybe we are missing an explanation of what you are trying to solve in the first place (see http://xyproblem.info/).

**Comment by tim-rex** [comment]
Sorry Omar.  I thought I was being clear about my intent, but after a few revisions of what I wanted to ask I still managed to leave out important context.

Some screenshots will probably help.

Here's a tooltip I'm using, on an area of the screen that I'm rendering outside of ImGui.

![image](https://user-images.githubusercontent.com/19639392/78821101-db711080-79d0-11ea-8b41-56f4734e2947.png)


And here's what the tooltip looks like on an area of the screen that would otherwise be obscured by ImGui..

![image](https://user-images.githubusercontent.com/19639392/78817590-4881a780-79cb-11ea-8bd0-4b988c4bb933.png)


I would prefer this particular tooltip did not obscure any ImGui windows.

I've taken your suggestion and am iterating over g.Windows - so far it works perfectly.
Thank you.

**Comment by ocornut** [comment]
Also note that you **might** be able to take advantage of the `FindBestWindowPosForPopupEx()` function in imgui_internal.h. It's not really documented or guaranted to be forward compatible, but I imagine that if/when it ever changes the changes will be simple.
