### ISSUE TITLE
Clipboard memory destruction order issue using custom allocator

### ISSUE THREAD

**Issue by simon-yeunglm** [ocornut/imgui#3110]
**Version/Branch of Dear ImGui:**

Version: 1.73 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: custom 
Compiler: VisualStudio 2017
Operating System: Windows 10

**My Issue/Question:**
In my program, I used a custom allocator (by calling `ImGui::SetAllocatorFunctions()` ) and using the default clipboard functions (i.e. `GetClipboardTextFn_DefaultImpl()`, `SetClipboardTextFn_DefaultImpl()` ). A crash will occur during program exit if I have copied and pasted some values.

The crash is due to the destruction order of the **static** variable `buf_local` in `GetClipboardTextFn_DefaultImpl()` _(https://github.com/ocornut/imgui/blob/master/imgui.cpp#L9810)_

```
static const char* GetClipboardTextFn_DefaultImpl(void*)
{
    static ImVector<char> buf_local;
    ...
}
```
The destructor of `buf_local` is called after my custom allocator is destroyed during program exit, causing the crash.

Should I implement my clipboard functions instead of using the default functions when using custom allocators? Currently I work around the problem by moving the static variable out of the function and call `buf_local.clear()`  inside `ImGui::DestroyContext()`.

Thank you.

**Comment by ocornut** [comment]
Hello Simon,

There was already a similar buffer in the imgui context (used by another of the clipboard handler) so I have now made them all use the same one to prevent the issue you are describing.

Thank you for the issue report!
