### ISSUE TITLE
example_win32_directx12 crashes when maximizing window via double click

### ISSUE THREAD

**Issue by CanisLupus** [ocornut/imgui#3115]
The example in folder `example_win32_directx12` crashes when you double click the window header to maximize it on Windows. This does not happen when using the maximize button itself.

The error is:
`Assertion failed: (((HRESULT)(hr)) >= 0), file ..\imgui_impl_dx12.cpp, line 348`

**Version/Branch of Dear ImGui:**

Version: Dear ImGui 1.76 WIP (17502)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx12.cpp
Compiler: cl, using "vcvarsall x64"
Operating System: Windows 10, x64

**Comment by sergeyn** [comment]
PR #3087 fixes it.

**Comment by CanisLupus** [comment]
I can confirm that this fix solves it. Thanks! I'm not sure if I should close this issue, so please feel free to do so.

**Comment by ocornut** [comment]
Merged the fix by @sergeyn now. Thanks!
