### ISSUE TITLE
Viewport merge when mother window minimized

### ISSUE THREAD

**Issue by OverShifted** [ocornut/imgui#3118]
Version: 1.76 WIP
Branch: Docking

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Visual Studio 2019
Operating System: Win10
**My Issue/Question:**

1. I dragged one of imgui windows outside of the main window
2. I minimized the main window
3. I dragged the imgui window over the lastest place that the main window was there

but suddenly imgui window hid and merged in the main window
**I have viewport decoration Enabled** I mean:
`io.ConfigViewportsNoDecoration = false;`

I created a couple of functions to disable and enable auto-merge on Minimize and UnMinimize
Like this:
```
void OnMinimize()
{
    mGuiIO& io = ImGui::GetIO();
    io.ConfigViewportsNoAutoMerge = true;
}

void OnUnMinimize()
{
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigViewportsNoAutoMerge = false;
}
```
But with this ; when I minimize the main window , all of imgui windows will un-merge.
How can I fix it?

excuse me because of poor English,

**Comment by ocornut** [comment]
This seems like a bug to fix.
We have knowledge of minimized viewports and many behaviors are adapted for this case, it looks like this one behavior is missing.

![image](https://user-images.githubusercontent.com/8225057/79073150-34002080-7ce5-11ea-93ff-584be8e5107d.png)

**Comment by ocornut** [comment]
Well it looks like it was a trivial bug..

That test was faulty:

```
if (!(viewport->Flags & (ImGuiViewportFlags_CanHostOtherWindows | ImGuiViewportFlags_Minimized)))
    return false;
```
Turned it into correct (and more readable)
```
if ((viewport->Flags & ImGuiViewportFlags_CanHostOtherWindows) == 0)
    return false;
if ((viewport->Flags & ImGuiViewportFlags_Minimized) != 0)
    return false;
```

Fixed!
