### ISSUE TITLE
Invalid check for minimum GL version to support vertex offset

### ISSUE THREAD

**Issue by wolfpld** [ocornut/imgui#3119]
`imgui_impl_opengl3.cpp`:169 checks for OpenGL 3.2 by comparing `g_GlVersion` value to `3200`. However, in line 160 the version variable is constructed as `major * 1000 + minor`, producing `3002` instead.

**Comment by OverShifted** [comment]
Look at this if at line 168 :
_Lines 168 to 171_
```
#if IMGUI_IMPL_OPENGL_MAY_HAVE_VTX_OFFSET
    if (g_GlVersion >= 3200)
        io.BackendFlags |= ImGuiBackendFlags_RendererHasVtxOffset;  // We can honor the ImDrawCmd::VtxOffset field, allowing for large meshes.
#endif
```

**Comment by ocornut** [comment]
Thank you @wolfpld ! This is rather embarassing little bug, essentially it means only 4.0+ contexts would benefit from `ImGuiBackendFlags_RendererHasVtxOffset`. Fixed now!

Amend #2866 #2852
