### ISSUE TITLE
How Parsec customised imgui that much?

### ISSUE THREAD

**Issue by OverShifted** [ocornut/imgui#3122]
My question is simple.
How Parsec ([https://parsecgaming.com/features/#features](https://parsecgaming.com/features/#features)) customised imgui that much?
screenshot from imgui releases page down here \\/ \\/ \\/

![](https://user-images.githubusercontent.com/8225057/74334374-13295680-4d9a-11ea-8a51-88d001ac75dc.png)

Are they changed imgui source code or done that just by using imgui styles?

**Comment by ocornut** [comment]
They are mostly extra custom widget based over imgui_internal.h, i don’t see anything preventing you to do that.

**Comment by OverShifted** [comment]
I couldn't find any documentation or something about that in the wiki.
Is there any tutorial/doc about custom widgets?

**Comment by ocornut** [comment]
There’s none no, and it require some comfortable understanding of both dear imgui and programming to make your way through it. 

However, if you dissect that screenshot you’ll find there aren’t that many custom widgets in there:

- Using icons, images + varying fonts color and size can already get you half way with having a nice looking application. I reckon this is most of what you see here.

- Pushing custom style colors on a per widget basis (to eg change text color in a button) also gives a nicer look easily.

**Comment by OverShifted** [comment]
How can I 

> Pushing custom style colors on a per widget basis (to eg change text color in a button) also gives a nicer look easily.

?

Like this?
```c++
Imgui::Begin("Test");
Imgui::stylesdark();
Imgui::button(....);
Imgui::styleslight();
Imgui::End();
```
?
will it change just button to black?

**Comment by ocornut** [comment]
Yes essentially, however you don't need to change the whole style (that will be too slow).
You can use PushStyleColor(), PushStyleVar() functions then restoring PopStyleColor(), PopStyleVar() to restore the change.

**Comment by OverShifted** [comment]
Oh cool 😀😀
I think I can close the issue.
