### ISSUE TITLE
Suggestion resizing multiple windows from their border (was: Idea for people made imgui)

### ISSUE THREAD

**Issue by OverShifted** [ocornut/imgui#3125]
In new VScode, you can resize multiple windows at the same time by dragging from intersect of two window edges
this is just an idea for you to implement that in imgui.

**Comment by ocornut** [comment]
Seems like what docked windows in the docking branch already do.

**Comment by OverShifted** [comment]
No, I cant see this feature.

![](https://code.visualstudio.com/assets/updates/1_43/sash-corners.gif)

look at that gif from [https://code.visualstudio.com/updates/v1_43](https://code.visualstudio.com/updates/v1_43#_draggable-sash-corners)

**Comment by ocornut** [comment]
OK I understand what you mean now! Thank you!
I don't think this is high priority but going to add this into my todo list for docking.

**Comment by OverShifted** [comment]
Thanks🙏🙏
