### ISSUE TITLE
Style Rounding Corner

### ISSUE THREAD

**Issue by petercooke536** [ocornut/imgui#3128]
I am trying to add rounding to the styles TabRounding and ChildRounding but whenever I do it, it adds little transparent rounders in all of the corners of the tab.  I have set the global alpha to 1.0f and have assigned colors to all of the ImGuiCol_ properties.  I also have tested setting the rounding to 0.0f and these transparent rounders do not appear.  So is there anyway to set the color of these rounders or edit them so this transparency does not show up when trying to use rounding styles? 

Sorry for crappy pic.

![IMG_20200414_204031](https://user-images.githubusercontent.com/4993875/79287241-31422e80-7e91-11ea-9fb6-fffbb504a6db.jpg)

**Comment by ocornut** [comment]
Please provide the details requested by the new issue template, they are asked for a reason. Please also provide a repro.

Comment here when details are added and will reopen the issue. Right now we can’t help without a repro, version and backends details.
