### ISSUE TITLE
VS2015 x64 crash

### ISSUE THREAD

**Issue by thefastman** [ocornut/imgui#313]
I've crash on init if I try to build app on VS2015 with run-time "Visual Studio 2015 (v140)"  64bit mode.
It crashes in imgui.cpp on line
...
 IM_ASSERT(g.IO.Fonts->Fonts.Size > 0); 
...

Any ideas why font initialization crashes app ?

**Comment by ocornut** [comment]
`IM_ASSERT(g.IO.Fonts->Fonts.Size > 0);           // Font Atlas not created. Did you call io.Fonts->GetTexDataAsRGBA32 / GetTexDataAsAlpha8 ?`

**Comment by thefastman** [comment]
Yes, exactly.

**Comment by ocornut** [comment]
Did you call io.Fonts->GetTexDataAsRGBA32 / GetTexDataAsAlpha8 ?

**Comment by ocornut** [comment]
Are you using an example provided in examples/ or your own code?

**Comment by thefastman** [comment]
Yes, I'm using example with imgui_impl_dx11.cpp
I see that in ImGui_ImplDX11_CreateDeviceObjects() should be called ImGui_ImplDX11_CreateFontsTexture() with  io.Fonts->GetTexDataAsRGBA32.
But it does not. Because g_pd3dDevice has NULL value

....
bool    ImGui_ImplDX11_CreateDeviceObjects()
{
    if (!g_pd3dDevice) /// <-- IS NULL
        return false;
    if (g_pFontSampler)
        ImGui_ImplDX11_InvalidateDeviceObjects();
...

**Comment by thefastman** [comment]
When I switch to "Visual Studio 2012 (v110)" 64bit all is ok.

**Comment by ocornut** [comment]
So we must figure out why the device is NULL. It is created in main.cpp CreateDeviceD3D() it is a pretty simple function. Could you investigate?

**Comment by thefastman** [comment]
Hm, yes, you right.
May be I localized issue, on VS2015 x64

...
 D3DCompile(vertexShader, strlen(vertexShader), NULL, NULL, NULL, "main", "vs_5_0", 0, 0, &g_pVertexShaderBlob, NULL); 
...

Returns NULL in g_pVertexShaderBlob

**Comment by thefastman** [comment]
I've added error out value 
 D3DCompile(vertexShader, strlen(vertexShader), NULL, NULL, NULL, "main", "vs_5_0", 0, 0, &g_pVertexShaderBlob, &err);
LPCSTR errMsg = (char*)err->GetBufferPointer();
err->Release();

instead NULL and in errMsg see:

```text
Shader@0x000000013F1160D0(1,33-34): error X3530: invalid register specification, expected 'b' binding
```

**Comment by ocornut** [comment]
What happens if you replace

"cbuffer vertexBuffer : register(c0)"

with

"cbuffer vertexBuffer : register(b0)"

**Comment by thefastman** [comment]
Yes, it works now.
Thanks. 
Could you please explain why it happened and why different runtime versions affects on it ?

**Comment by ocornut** [comment]
I have no idea. I don't even know DX11, I just googled the error.

**Comment by Querijn** [comment]
"c" defines a buffer offset, rather than a constant buffer "b". 

changing to 64 bits might cause it to read wrong memory?

**Comment by thefastman** [comment]
Hi Querijn, 
>>changing to 64 bits
I did not change 32bit to 64bit.
The difference only in runtime version VS2012(v110) vs VS2015(v140)

**Comment by Querijn** [comment]
Then it sounds like something got enforced in the latest version.. Might be wrong, would have to look at it.

**Comment by ocornut** [comment]
I assume that VS2015 comes with an updated DX11 in its standard library or something?

**Comment by Querijn** [comment]
Yup, since Windows 8 (correct me if I am wrong), the Windows SDK includes the DirectX SDK.

**Comment by ocornut** [comment]
I'll call that a fix.. constant-buffer sounds righter :)

**Comment by blunted2night** [comment]
Just for completeness, the issue is caused by a change to 'Windows SDK Version' in the project properties (in my case it was from '8.1' to '10.0.10586.0')
