### ISSUE TITLE
How to create just a button without background debug panel. 

### ISSUE THREAD

**Issue by sergeyn** [ocornut/imgui#3131]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: dx12

**My Issue/Question:**

Hi

I would like to have the one and only button in my window without any panels behind it. Just empty application window with cleared background and a button, how do I achieve that ? 

Thanks

**Standalone, minimal, complete and verifiable example:**
```
   Begin("main",nullptr, ImGuiWindowFlags_NoDecoration);
   Button("my button");  
   End();
```

**Result**
![image](https://user-images.githubusercontent.com/668090/79457429-8052a580-7ff0-11ea-9dea-0b7ffc72d118.png)

**Comment by ocornut** [comment]
Question is ambiguous and missing issue template.

You can use the _NoDecoration flag to disable bg, borders, title bar ec.

**Comment by sergeyn** [comment]
Sorry for missing template, updated initial post to include template. _NoDecoration flag looks like on the screenshot in the initial post. How do I get rid of that back panel or make it transparent ?

**Comment by ocornut** [comment]
Add `ImGuiWindowFlags_NoBackground`.

**Comment by sergeyn** [comment]
ok, thanks, somehow I missed that flag. it works now.
