### ISSUE TITLE
Thick window borders generates padding

### ISSUE THREAD

**Issue by gcaseres** [ocornut/imgui#3138]
**Version/Branch of Dear ImGui:**

Version: 1.76
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: gcc
Operating System: ubuntu 18

**My Issue/Question:**

I want to create a window with a thick border and no padding, but there is always a padding related to the border size.
In this example, I'm using a border size of 10 without padding, but as you can see in the screenshot there is a padding relative to the border size.

Is there a way to get a thick border but 0 padding?

**Screenshots/Video**

![border_padding](https://user-images.githubusercontent.com/1785996/79688026-2bf33400-8243-11ea-8c8f-5fee88892a8c.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```

ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 10);
ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
ImGui::Begin("Test");
char text[10];
ImGui::InputText("Test", text, 10);
ImGui::End();
ImGui::PopStyleVar(2);
```

**Comment by ocornut** [comment]
As stated in the comments, thick borders are not supposed to supported by the styling system so this is presently out of scope, sorry. We'll probably come with solutions for this eventually.

In the meanwhile you can yourself draw a border over the window using the ImDrawList API.

**Comment by gcaseres** [comment]
@ocornut Thanks for your quick reply and workaround. For now, I'll try to follow your suggestion rendering my own border.

Regards

**Comment by ocornut** [comment]
Please note you will have to push a clipping rectangle that can contains your border, otherwise it'll be clipped by the window.
