### ISSUE TITLE
Disable New Window Focus

### ISSUE THREAD

**Issue by BalazsJako** [ocornut/imgui#314]
In some situations it would be useful if a newly opened or unhidden window did not get the focus and leave the current focus intact.

**Comment by ocornut** [comment]
Could you clarify your use case and how this is getting in your way? (you mentioned docking in an earlier communication but I'm not sure it was related?). I'm thinking that maybe the answer to your problem may be something else.

Are you concerned about focus as in "visual ordering", or in term of what window takes keyboard inputs? Both concepts are co-existing.

How do you ethe change would work? Would it be a flag per-window? Or a more global and long-term global flag in ImGuI? Would menus, popups, modals windows be exempt from it?

**Comment by BalazsJako** [comment]
My use case is the following: The screen is an usual 3D view with objects rendered in it, on top of which I render small 2D icons (ImGui::Image() enclosed inside a ImGui window), positioned on the 2D projected coordinates of the origin of the objects (to make it possible to select them with the mouse or show additional info about them). Additionally, there are two other "big" (floating, semi-transparent) overlay windows showing the scene hierarchy tree and some kind of a property sheet. As the camera moves in 3D view, the  small windows appear or disappear, as the origins of the objects enter or leave the camera frustum. Newly appearing icon windows remove focus from the big windows and are rendered in front of the property window, instead of behind it.

Sorry for not providing a screenshot, but it is not possible at the moment, I hope I explained it in enough detail.

Yes, the solution would be something else, but preventing focus to new window seems to be useful anyway (for me at least). It might be global flag, as it might be a tiny bit faster than an extra parameter to the Begin()  function, and because it is not a too common case to disable it.

**Comment by ocornut** [comment]
Having a local flag to Begin() is easier and seems to make more sense here. If we have a global flag we need to decide how it behave with menus/popups/modals (I don't know how that would work), and it generally make behavior less deterministic Here we'd have very localized behavior..

**Comment by ocornut** [comment]
Basically you only want to add a new flag and test here in Begin()

```
// New windows appears in front
if (!window_was_visible)
{
    window->AutoPosLastDirection = -1;

    if (!(flags & (ImGuiWindowFlags_ChildWindow|ImGuiWindowFlags_Tooltip)) || (flags & ImGuiWindowFlags_Popup))
        FocusWindow(window);

    // Popup first latch mouse position, will position itself when it appears next frame
    if ((flags & ImGuiWindowFlags_Popup) != 0 && !window_pos_set_by_api)
        window->PosFloat = g.IO.MousePos;
}
```

**Comment by apessino** [comment]
I have the exact same issue (with a similar scenario). Using ImGui to “attach” information panels to 3D entities that move in the environment and can come into view while you are doing editing in another ImGui window. If a popup is open, for example, it will close as the main window loses focus. I have been trying to figure out the best way to fix the issue – having a flag in Begin() that lets me create windows that do not change the focus (or come to the front) at all would be awesome.

A=

**Comment by ocornut** [comment]
Added! Let me know if that works for your use case, I believe it will.

PS: Andrea, any engine screenshot? :) looking forward to see what you guys will be doing next!

Tested with
```
if (ImGui::GetIO().KeyCtrl)
{
    ImGui::Begin("Taking focus");
    ImGui::Text("Hi!");
    ImGui::End();
}
if (ImGui::GetIO().KeyAlt)
{
    ImGui::Begin("Not Taking focus", NULL, ImGuiWindowFlags_NoFocusOnAppearing);
    ImGui::Text("Hi!");
    ImGui::End();
}
```

**Comment by apessino** [comment]
Hey Omar, thank you SO much, once again.

Nothing I can share right now, but let’s just say that ImGui has become central to all of the non-consumer-facing UI we do, and then some… ;) I will share all I can as soon as I am at liberty to do so…

Keep up the great work!

A=

**Comment by BalazsJako** [comment]
Hi Omar,
Thank you very much, it solves my problem.
Have a great day!

**Comment by ocornut** [comment]
Great!|
Closing this :)

**Comment by jpreiss** [comment]
I am overlaying ImGui on other interactive content in a SDL2 window. I am trying to initialize ImGui with no focus on any windows, similar to what happens if I click in the "void". I tried passing `ImGuiWindowFlags_NoFocusOnAppearing` to all of my windows, but ImGui still initializes with one of the windows focused. Is there anything I can do?

**Comment by jpreiss** [comment]
That works! Thank you for such dedicated support of this project.
