### ISSUE TITLE
imgui and SDL2 using the same Direct3d device ?

### ISSUE THREAD

**Issue by binbinhfr** [ocornut/imgui#3140]
Version: 177 wip
Branch: master
Back-ends: example_sdl_directx11.cpp
Compiler: VS2019 c++
Operating System: win10

Hi, I already have some hints from Omar, but in case someone around here has any idea, or even better an example to provide, I share my question 👍 

I wrote a little game under SDL2, using its DirectX renderer, and all the nice 2D graphical function that SDL2 offers (classic primitives, textures, sprites, scaling, etc...).    Now I'd like to add a modern GUI on top of that and imgui seems perfect. So I would like to use SDL graphics and Imgui mixed in the same window.

I compiled imgui example with DX and SDL2 with no problem  (example_sdl_directx11) .    BUT it seems that the SDL2 implementation provided in this example only covers the inputs/events part of SDL2, not the graphic part. So when I try to create a SDL2/DX renderer (https://wiki.libsdl.org/SDL_CreateRenderer), I can do it, but it competes with imgui/DX context (created by CreateDeviceD3D(hwnd)) and I cannot draw on both of them at the same time. I just can obtain a window that flickers between imgui and my SDL2 renderer....

Here (https://github.com/Tyyppi77/imgui_sdl), Tyyppi77 wrote a simple graphical backend for imgui with SDL2 functions.     BUT SDL2 is not good at rendering textured triangles, so (as the guy admitted himself), the resulting rendering quality is quite "coarse" comparing to the original DX-backend version of Imgui.

So, I'm not familiar with DX, but my question is :   is it possible from the original example_sdl_directx11 (to retain visual quality and SDL inputs compatibility) to somehow share the same graphical DX context between the SDL2 renderer and the DX context created by imgui-example ?   For example, I would like to add to the example_sdl_directx11/main.cpp file one call to SDL_RenderFillRect that would draw a simple rectangle below imgui widgets.

hints sor far 
- in SDL there is a function that return a DX object 
   https://wiki.libsdl.org/SDL_RenderGetD3D9Device
   IDirect3DDevice9* SDL_RenderGetD3D9Device(SDL_Renderer* renderer)

- in example_sdl_directx11 /main.cpp, there is a CreateDeviceD3D(hwnd) function that create the DX handles used by imgui dx-backend.

- in case you ask, SDL seems to be DX11 compatible since 2.0.9 .

**Comment by ocornut** [comment]
A quick look at SDL source code seems to show it doesn't have an equivalent of `SDL_RenderGetD3D9Device` for the DX11 renderer; so indeed I don't know a way to access the device. :( 

Maybe there's a way to enumerate devices in a given process but I don't know DX11 enough.

Very sincerely this is only adding one extra anectodal evidence to the fact that the "SDL Renderer" component is nearuseless (not to be mistaken with core "SDL" which is good) . The functionalities it provides are surprisingly out of touch with modern hardware requirement, and using `ImDrawList` API would probably be an even better replacement.  If you can load images into your back-end (see https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples) you can use ImDrawList as a replacement for SDL_Renderer.

I wasn't aware of the existence of https://github.com/Tyyppi77/imgui_sdl and I am afraid it's going to be very slow and it seems to look bad. Sincerely, don't use SDL_Renderer.

**Comment by binbinhfr** [comment]
ok @ocornut , thanks for your answer and your very valuable help.

**Comment by ocornut** [comment]
New **imgui_impl_sdlrenderer.cpp** backend!

FYI, although I personally recommend using native graphics API backends, SDL 2.0.18 (tentative [scheduled in 52 days](https://libsdl.org/next.php)) will add support for a new `SDL_RenderGeometry()` function which allowed a SDL_Renderer backend to be created. 

This is now available on master (currently requires building SDL from latest sources)
https://github.com/ocornut/imgui/pull/3926#issuecomment-924204079

(Note the backend currently doesn't support multi-viewports.)
