### ISSUE TITLE
Crash on resize opengl3

### ISSUE THREAD

**Issue by blakat360** [ocornut/imgui#3144]
**Version/Branch of Dear ImGui:**

Version: 37f665b619946b1651d120b063a537a694f4ab2d
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp _(or specify if using a custom engine/back-end)_
Operating System: Linux

**My Issue/Question:**

I have made a dear imgui window fit an entire glfw window. 

When I resize the window so that a button is no longer visible, the program crashes. 

I have made the UI dynamic and so it responds to the window size callback. The callback is triggered before the resize is complete, thus i render a button offscreen and the program crashes.

Can we not have this and instead just make components rendered off screen not visible to the user.

**Comment by ocornut** [comment]
Hello,
As per the Issue Submitting guidelines, if you state that something crash you must provide a callstack.
