### ISSUE TITLE
How can I add padding around ImGui::Text() item?

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#3145]
**Version/Branch of Dear ImGui:**
Version: 1.75
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui.net
Operating System: win10

**My Issue/Question:**
I want to add some padding around a text element...

```ImGui.Text("My Text")```

I tried style overrides for ItemSpacing and InnerItemSpacing and a few other parameters. Without success.

I probably could do something like...

```
ImGui.SetCursorPos( ImGui.GetCursorPos() + Vector2.one * 10);
ImGui.Text("Text with 10px padding");
ImGui.Dummy( Vector2.one * 10);
```

... but was wondering if there is a simpler way.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/1732545/79798184-e9238000-8358-11ea-8472-ddeda4a5c99c.png)

**Comment by rokups** [comment]
There is not. `Text()` just renders some text at current cursor position. You may make your own convenience wrapper `PaddedText()` that takes padding parameter. I do not know what api surface is exposed by imgui.net, but you could create extra padding by rendering `InvisibleButton()`. Something like:

```cpp
ImVec2 sz = ImGui::CalcTextSize(my_string);
ImVec2 cursor = ImGui::GetCursorPos();
ImGui::InvisibleButton("##padded-text", sz + ImVec2(padding_x * 2, padding_y * 2));    // ImVec2 operators require imgui_internal.h include and -DIMGUI_DEFINE_MATH_OPERATORS=1
ImVec2 final_cursor_pos = ImGui::GetCursorPos();
ImGui::SetCursorPos(cusror + ImVec2(padding_x, padding_y));
ImGui::Text(my_string);
ImGui::SetCursorPos(final_cursor_pos);
```

**Comment by pixtur** [comment]
Okay. Thank you for the quick answer. I just wanted to be sure that I didn't miss something obvious.
