### ISSUE TITLE
How to check if the next item is focused?

### ISSUE THREAD

**Issue by zispo** [ocornut/imgui#3147]
I need to check if the next item is focused. The reason is I want to change the background color of an InputText if the field is focused. I didn't find a "focused background color" setting to do this so the only way I can do this is if I can know if the next item is focused before I render it so that I can push the colors. There's calls to know if the previous item is focused and calls to know if any item is focused but there's not a call to know if a specific item is focused or if the next item is focused, both of those would work.

Cheers.

**Comment by rokups** [comment]
Hey @zispo. Easiest way to achieve thous would be checking if `InputText()` is focused after it is rendered, saving result in a bool and rendering different background on the next frame. This introduces one frame lag, but that is not a problem given duration of the frame.

**Comment by ocornut** [comment]
You may also call `ImGui::GetID("blah")` to get the id of the item ahead of time and compare that to `g.ActiveId` or `g.NavId` (respectively current activated item, which is the case when an input text is focused, and actual focused item).

So e.g.
```
ImGuiID id = ImGui::GetID("something");
bool is_active = (id == g.ActiveID);
if (is_active)
   ...
ImGui::InputText("something", ...");
```

**Comment by zispo** [comment]
Hey thanks a lot guys, I went with the second solution which requires "imgui_internal.h", I'm also using the method GetActiveID() that I found which feels a bit cleaner.

`bool is_active = ImGui::GetID("MyTextInput") == ImGui::GetActiveID()`

I'll close the thread.
