### ISSUE TITLE
Blank image, visualized by another frame than main()

### ISSUE THREAD

**Issue by Thanh-Binh** [ocornut/imgui#3150]
Hallo
In my framework, in the main program I call a visualization routine, which is implemented in another header file, I can plot all but can not visualize image, it is displayed as blank image.

### main.cpp ##
#include "visualize_header.hpp"
...
main ()
{
   ...
  visualize();
}
#########

#####visualize_header.hpp
visualize()
{
   ImGui::Begin("Application windows");
    sf::Texture imTexture;
    imTexture.loadFromFile("./test.bmp");
    ImGui::Image((void*)(intptr_t)imTexture.getNativeHandle(), ImVec2(imTexture.getSize().x, imTexture.getSize().y));
   ImGui::End();
}
#####
I do not know why? Can you please help? Thanks

**Comment by rokups** [comment]
It is a responsibility of your backend to render textures, therefore this is issue with your backend and not Dear ImGui. Also you did not fill out issue template. It is there for a reason, and that reason is not to ignore it.

**Comment by Thanh-Binh** [comment]
@rokups Sorry I do nor understand you. Could you pls explain me more?
What is a problem with my backend? Why I can render it in main(), but not in another file?
Is there any global variable used in ImGUI, so that it can not be found in other file?
Thanks

**Comment by rokups** [comment]
If that snippet is exactly what you have - it is a lifetime problem. `imTexture` is declared on the stack and gets destroyed when function exits. In order to render this texture it must be alive until `ImGui::Render()` call finishes.

**Comment by Thanh-Binh** [comment]
I insert ImGui::Render() at the end of visualization(), but have got segmentation error by runing.

**Comment by rokups** [comment]
You should not do that. `ImGui::Render()` is called at very end of frame. Please follow [examples](https://github.com/ocornut/imgui/tree/master/examples).

**Comment by ocornut** [comment]
You can ask on https://github.com/eliasdaler/imgui-sfml repository you may get more SFML-friendly help.
But basically Rokups answer which I liked above is the right answer. Your texture needs to stay alive for the frame so it cannot be declared on the stack.

**Comment by Thanh-Binh** [comment]
@rokups I already do it at every frame.
@ocornut Ok. I will ask at imgui-sfml
