### ISSUE TITLE
[Tables] select the whole line with a selectable or another way

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#3151]
Version: 1.77
Branch: Tables

the tables branch Iwork like a charm for my ImGuiFileDialog, 
created a branch [here](https://github.com/aiekick/ImGuiFileDialog/tree/detail_view_mode), for use table instead of just list.

by the way im using a selectable in the first cell.
Is there a way for draw selection on the whole line ?
maybe if all collumns of one line can be selected when one item of one line is mouse hovered or clicked ?

![BZOPSWcqrI](https://user-images.githubusercontent.com/1434736/80030752-ee173980-84e8-11ea-9055-41e3872866a2.gif)

**Comment by ocornut** [comment]
Check the flags for Selectable()

**Comment by aiekick** [comment]
haha, im ridiculous.
It's working. it was so easy. thank you so much :)

**Comment by ocornut** [comment]
To make this thread useful to other readers, the answer is you can use `Selectable()` with the ImGuiSelectableFlags_SpanAllColumns flag.

**Comment by sairus7** [comment]
What about table tree with selection via `ImGuiTreeNodeFlags_Selected`?
<img width="415" alt="image" src="https://github.com/ocornut/imgui/assets/20798349/42fafe29-8cfd-407c-bc44-e21c78966366">

**Comment by ocornut** [comment]
There’s an equivalent SpanAllColumns flags for table nodes.

**Comment by sairus7** [comment]
Where exactly? Didn't find anything in `ImGuiTableFlags_`

**Comment by ocornut** [comment]
My bad there is none, let me get back to you later.

**Comment by ocornut** [comment]
I have now added `ImGuiTreeNodeFlags_SpanAllColumns` with 2c07d58.
I am a little confused as to why this was added/requested before.
