### ISSUE TITLE
ImGui Content inside AddCallback()

### ISSUE THREAD

**Issue by vassilcom** [ocornut/imgui#3155]
I'm trying to implement ImGui into the existing wxWidget app. Problem that I faced is to use ImGui content inside a class which is rendered through AddCallback (no context and id is presented). 

```
void render_function(const ImDrawList* parent_list, const ImDrawCmd* cmd)
{
	content_class->render();
}
ImGui::GetWindowDrawList()->AddCallback(render_function, (void*)this);
```
I have a problem when I'm trying to use ImGui popup window (or any ImGui function) inside the 'content_class'.

can anyone suggest any workaround to tackle this issue?

 I guess it's a pretty common issue, but unfortunately I could not find any related post that could help to deal with that.

**Comment by ocornut** [comment]
Hello @vassilcom ,

- I don't really understand your question.
- Your issue hasn't filled the issue template.
- `ImDrawCmd* cmd` has `UserCallback` and` UserCallbackData` which correspond to the two values you passed to AddCallback(). This may be what you are looking for, but without understanding your question I am not sure.

**Comment by ocornut** [comment]
Rereading I think I understand what you mean. Those are low-level drawing callbacks and you shouldn't call ImGui:: functions from them. You absolutely don't need to use ImDrawCallback mechanism for that this is not what they are for.

Just call your content_class->Render() code instead of calling AddCallback() and call imgui code from there.

**Comment by vassilcom** [comment]
Thank you for your response! 

content_class->Render() is rendered inside the ImGui window, and it works fine. I'm just trying to have another ImGui window inside the content_class: a popup window if mouse was clicked on the element inside content_class. So it's like ImGui in ImGui. 

The idea is to draw an existing visualization graph inside the ImGui window, and to have a popup window if mouse was click on some element of that rendered graph.

**Comment by ocornut** [comment]
Just use the regular functions such as Begin() to create more windows. I don’t understand what low-level ImDrawList have to do with that.

If you need something else I am afraid you would need to be more explicit.

**Comment by ocornut** [comment]
Closing this, feel free to ask on the Discord if you are unsure how to proceed.
