### ISSUE TITLE
Tables: is there a simple way to know when a header was pressed 

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#3159]
Version: 1.77
Branch: Tables

I would like to know when a header fo the tables is pressed and maybe when he is hovered .

like if we have a func bool IsHeaderPressed(int collumn) ?

I search in the code, but not found a func for that, 

maybe we can do that when we use oursefl the func TableHeader()

**Comment by ocornut** [comment]
Why do you need that? Always please explain the intent. (See http://xyproblem.info/)

Anyway you can use any IsItemXXX function with TableHeader().

**Comment by aiekick** [comment]
i have a specific sorting function to use when its pressed and i also want to change myself the icon for show when he is sorted and in what direction

**Comment by ocornut** [comment]
Those features are already handled by the table api, please check the demo and api.

**Comment by aiekick** [comment]
i see your sorting func, but like said i have a specific sorting behaviour

**Comment by aiekick** [comment]
Ok not seen at beginning than we could use custom sorting func :) thanks

**Comment by ocornut** [comment]
> Ok not seen at beginning than we could use custom sorting func :) thanks

You can't even use "non-custom" sorting func, it's only possible to have the sorting on user side.

> by the way i would like to use my custom font icon for arrows when ascending and descending.

Not possible now and not a priority, sorry.

**Comment by aiekick** [comment]
np, i can manage it with ImGui::TableHeader and ImGui::IsItemClicked().

thanks for the Tables feature. it is great :)
