### ISSUE TITLE
Docking | Docking Windows To Top Left/Right Without Pushing Bottom Docked Window To Center

### ISSUE THREAD

**Issue by ElxtePrxgrxmmxr75** [ocornut/imgui#3165]
Is there any way I can make my window docking so that I can dock a window on the left or right of my GLFW window but have it so that the bottom of the left/right window stays above the bottom docked window?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 

- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.

**Comment by ElxtePrxgrxmmxr75** [comment]
> Didn't follow requested guidelines or issue template.
> 
> * Please make sure you have read the guidelines.
> * Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
> 
> Closing.

Sorry! I edited it now!

**Comment by ocornut** [comment]
Finding it hard to understand the question.

**Comment by ElxtePrxgrxmmxr75** [comment]
> Finding it hard to understand the question.

**A simpler way to explain it:**
![image](https://user-images.githubusercontent.com/64323620/80292087-3b92e100-874b-11ea-8a3f-ef6223fff309.png)

In the above image, the docked window on the right is all the way down the right side of the window, if I add a docked window to the left in code, it also appears the same as the right window appears in the image, even if I have a docked window at the bottom. How can I get my left and right windows to look the same as the left window in the above image?
