### ISSUE TITLE
Can you restrict windows to a grid?

### ISSUE THREAD

**Issue by randohinn** [ocornut/imgui#3166]
Is there a way in imgui, to somehow, create a windowing system like this: Notice, how window creation, positions and sizing are restricted to the grid. (This is GrandMA 3 onpc, if anyone wants to play with it)? If so. what would be the easiest way to do this?

See video of what I'm asking for: https://streamable.com/t1w0wg

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
