### ISSUE TITLE
Weird issue with shared library using imgui

### ISSUE THREAD

**Issue by xahon** [ocornut/imgui#3169]
**Version/Branch of Dear ImGui:**

IMGUI_VERSION: "1.77 WIP"
IMGUI_VERSION_NUM: 17601
Branch: d3212482fe6e158db71999ae84de754f908ab8fd _(master)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MSVC 19.25.28614.0
Operating System: Windows 10

**My Issue/Question:**
An issue occurs when I use imgui functions in executable that links to the providing library dynamically. Under providing library I mean library that links to imgui and uses it under the hood (initialization, termination), think of it as GameEngine.dll that uses imgui as gui framework and executable as actual game that uses GameEngine.dll.

Here is sample [project](https://github.com/xahon/imgui_shared_lib_issue/tree/cbf4e797cc629329834f65f2634a1773623a8afd)

It is a piece of actual code:
```C++
void OnGUI() {
    ImGui::Begin("Camera");
    {
        ImGui::DragFloat("Camera Distance", &cameraDistance, 0.1f);
        ImGui::DragFloat("Camera Height", &cameraHeight, 0.1f);
        ImGui::DragFloat("Camera Orbit Angle", &cameraOrbit, 0.1f);
    }
    ImGui::End();
}

int main() {

    App a;
    a.CreateWindowwwww();
    // a.Run(); // Will work for both Executable_SHARED and Executable_STATIC
    // a.Run(&OnGUI); // Works only for Executable_STATIC
    return 0;
}
```
Consider these lines
```C++
a.Run(); // Will work for both Executable_SHARED and Executable_STATIC
a.Run(&OnGUI); // Works only for Executable_STATIC
```
The only difference is `Run()` runs the same code as in `OnGUI` function, but it is inlined in method, see here https://github.com/xahon/imgui_shared_lib_issue/blob/7f0b353ef3749083a9c64ad7a2d6521985e66398/Library/Lib.cpp#L69

There is 4 cmake targets:
Library_SHARED and Library_STATIC which provide GameEngine.dll and GameEngine.lib respectively
Executable_SHARED and Executable_STATIC which provide consumer of the library linked dynamically in the first case, and linked statically in the second case
The second case runs fine, while the first one fails when I pass `Imgui` code into it as function

The exception is here:
_g is nullptr_
```C++
bool ImGui::Begin(const char* name, bool* p_open, ImGuiWindowFlags flags)
{
    ImGuiContext& g = *GImGui;
    const ImGuiStyle& style = g.Style;
    IM_ASSERT(name != NULL && name[0] != '\0');     // Window name required
    IM_ASSERT(g.WithinFrameScope);                  // Forgot to call ImGui::NewFrame()
    ...
```

I have no clue what is going on and why it doesn't work

**Comment by ocornut** [comment]
﻿Hello,

Globals are not shared accross DLL borders so you need to call ImGui::SetCurrentContext() on every side of the fence.

**Comment by xahon** [comment]
@ocornut could you elaborate on what "Globals are not shared accross DLL borders" means? I used another dlls and had no problems before

**Comment by thedmd** [comment]
@xahon You can find detailed explanation [heae on stackoverflow](https://stackoverflow.com/questions/19373061/what-happens-to-global-and-static-variables-in-a-shared-library-when-it-is-dynam).

**Comment by xahon** [comment]
@ocornut am i understand it correctly? I should use some king of memory mapping and store ImguiContext* in it and then I should `SetCurrentContext` back and forth in both dll and exe?
