### ISSUE TITLE
Font DisplayOffset customization

### ISSUE THREAD

**Issue by BalazsJako** [ocornut/imgui#317]
I am trying to customize the appearance of ImGui and I found that while the Font structure has a DisplayOffset member which controls the global offset of a font, it can not be specified through the API. The default value is set to (0.0, 1.0) and is it a perfect value for the default font with the default sizes, but a different font would require different value.

This is the default font with default display offset:
![imgui_defaultfont](https://cloud.githubusercontent.com/assets/10564136/9655147/07332022-5227-11e5-9bc2-204e65d9cc46.png)

Sans font with the same default offset:
![imgui_sanswrong](https://cloud.githubusercontent.com/assets/10564136/9655149/07356ed6-5227-11e5-945c-47c8400159a0.png)

Sans font with (0.0, -1.0) offset:
![imgui_sansright](https://cloud.githubusercontent.com/assets/10564136/9655253/c2fb6120-5227-11e5-8f97-6e3946735d9c.png)

**Comment by ocornut** [comment]
Well you can alter the DisplayOffset value, everything is public for that reason.

Somehow I thought the default value was (0,0) and only the default font set it (0,1), but I noticed that I've switched the default value to (0,1), I don't remember when.

**Comment by BalazsJako** [comment]
Yes, it is not a major issue, just a kind of nice-to-have.

**Comment by ocornut** [comment]
I'm not happy with this parameter (it doesn't take account of the scaling) and it is an adjustable runtime parameter rather than an initial-setup thing, so that's why it's not "promoted" as a ImFontConfig field. I think for now it's totally fine and legal to just access the field.

**Comment by BalazsJako** [comment]
OK, thank you, it will do it for me. :)
