### ISSUE TITLE
Detect Imgui focus / mouse is over ?

### ISSUE THREAD

**Issue by binbinhfr** [ocornut/imgui#3170]
Version: Dear ImGui 1.77 WIP (17601)
Branch: master
Back-ends: SFML
Compiler: VS2019 c++
Operating System: win10x64

Hi, I already made a few developpement with ImGui, that I am using as a nice UI over my game, but I wonder how to split events between ImGUI and the rest of my app (lying under Imgui windows).

I would like to know when ImGui has focus, and even just when the mouse is over a ImGui window (and not on my app lying below).

Once I will know that, I suppose that I just have to use  io.WantCaptureKeyboard and io.WantCaptureMouse to see what events are left to my app.

I looked around but did not see examples using io.WantCaptureKeyboard and io.WantCaptureMouse and I still wonder where to use them correctly...

PS: Omar, thanks again for this great tool ! ;-)

**Comment by rokups** [comment]
Hello @binbinhfr,
For window states check out `IsWindowFocused()` and `IsWindowHovered()` APIs.

Examples also have instructions how to handle ` io.WantCaptureKeyboard` and `io.WantCaptureMouse `:
```
// You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
// - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application.
// - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application.
// Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
```

**Comment by binbinhfr** [comment]
thx @rokups .

IsWindowFocused() and IsWindowHovered() are what I was looking for.

For io.WantCaptureMouse, io.WantCaptureKeyboard, I did read the doc, but I still wonder how I should use them with continuous keyboard testings (that are not events polled in the classic event loop) like the sf::Keyboard::isKeyPressed of the SFML lib for example...

**Comment by rokups** [comment]
Something along these lines:

```
bool IsKeyPressed(int key)
{
    ImGuiIO& io = ImGui::GetIO();
    return !io.WantCaptureKeyboard && sf::Keyboard::isKeyPressed(key);
}
```

And only use `IsKeyPressed()` to read key state.

**Comment by ocornut** [comment]
I don't understand why you would use IsWindowFocused() etc this is not the right thing you want.

Just read `io.WantXXX` flags as mentioned above.

**Comment by binbinhfr** [comment]
@ocornut : my problem is with sf::Keyboard::isKeyPressed that do do belong to the polling loop.

Usually, my loop looks like :

```
while(events to poll)
{
   treat imgui events
   if(!io.WantCaptureKeyboard())
     treat keyb app events
   if(io.WantCaptureMouse)
     treat mouse app events
}

treat all iskeypressed() at once

update

render
```

The iskeypressed() are not in the polling loop, because their effect should not be duplicated.
So if I condition them with io.WantCaptureMouse, the effect would be undefined, because io.WantCaptureMouse only refers to the last event treated, right ?
