### ISSUE TITLE
LNK error 2019 with IMGUI GLFW OpenGL3

### ISSUE THREAD

**Issue by nigtard** [ocornut/imgui#3174]
**Imgui glfw opengl3**

**Visual Studio 2019 with MSVC compiler **

Operating System: Windows 10

**My Issue/Question:**

When I am trying to compile my project Im getting several compiler errors, I have included images of all my includes. Most of the errors are coming from the glfw3.lib so I am unsure of what is going on here. 

![image](https://user-images.githubusercontent.com/63432322/80436459-2b0a7400-88cd-11ea-9f30-9aab93428fad.png)

![image](https://user-images.githubusercontent.com/63432322/80436481-3c538080-88cd-11ea-91d5-3c6689ff5543.png)

![image](https://user-images.githubusercontent.com/63432322/80436498-470e1580-88cd-11ea-890c-31e6fa3fa73e.png)

`1>------ Build started: Project: Atlas, Configuration: Debug Win32 ------
1>LINK : warning LNK4217: symbol '_sscanf' defined in 'imgui.obj' is imported by 'glfw3.lib(context.obj)' in function '_parseVersionString'
1>LINK : warning LNK4286: symbol '__vsnprintf' defined in 'imgui.obj' is imported by 'MSVCRTD.lib(vsnprintf.obj)'
1>glfw3.lib(win32_window.obj) : error LNK2019: unresolved external symbol __imp__DeleteObject@4 referenced in function _createIcon
1>glfw3.lib(win32_window.obj) : error LNK2019: unresolved external symbol __imp__CreateBitmap@20 referenced in function _createIcon
1>glfw3.lib(win32_window.obj) : error LNK2019: unresolved external symbol __imp__CreateDIBSection@24 referenced in function _createIcon
1>glfw3.lib(win32_window.obj) : error LNK2019: unresolved external symbol __imp__DragAcceptFiles@8 referenced in function _createWindow
1>glfw3.lib(win32_window.obj) : error LNK2019: unresolved external symbol __imp__DragFinish@4 referenced in function _windowProc@16
1>glfw3.lib(win32_window.obj) : error LNK2019: unresolved external symbol __imp__DragQueryPoint@8 referenced in function _windowProc@16
1>glfw3.lib(win32_window.obj) : error LNK2019: unresolved external symbol __imp__DragQueryFileW@16 referenced in function _windowProc@16
1>glfw3.lib(init.obj) : error LNK2019: unresolved external symbol __imp__vsnprintf referenced in function __glfwInputError
1>MSVCRTD.lib(vsnprintf.obj) : error LNK2001: unresolved external symbol __imp__vsnprintf
1>glfw3.lib(wgl_context.obj) : error LNK2019: unresolved external symbol __imp__DescribePixelFormat@16 referenced in function _choosePixelFormat
1>glfw3.lib(wgl_context.obj) : error LNK2019: unresolved external symbol __imp__SetPixelFormat@12 referenced in function __glfwCreateContextWGL
1>glfw3.lib(wgl_context.obj) : error LNK2019: unresolved external symbol __imp__SwapBuffers@4 referenced in function __glfwPlatformSwapBuffers
1>glfw3.lib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp__DeleteDC@4 referenced in function _createMonitor
1>glfw3.lib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp__GetDeviceCaps@8 referenced in function _createMonitor
1>glfw3.lib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp__CreateDCW@16 referenced in function _createMonitor
1>glfw3.lib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp__GetDeviceGammaRamp@8 referenced in function __glfwPlatformGetGammaRamp
1>glfw3.lib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp__SetDeviceGammaRamp@8 referenced in function __glfwPlatformSetGammaRamp
1>D:\projects\Atlas\Debug\Atlas.exe : fatal error LNK1120: 16 unresolved externals
1>Done building project "Sourcerer.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`
Thanks in advance.

**Comment by rokups** [comment]
You are probably mixing /MT with /MD. All libraries have to be compiled using same option.

**Comment by ocornut** [comment]
Functions like `CreateDC` and `DescribePixelFormat` if you google them are listed as part of gdi32.lib, are you linking with gdi32.lib ?

**Comment by ocornut** [comment]
Sorry but #

**Comment by Vovan675** [comment]
Have you fixed it? I have same error

**Comment by nigtard** [comment]
yeah I included `legacy_stdio_defintions.lib` and that seemed to fix it @Vovan675
