### ISSUE TITLE
Potential Memory Leak in ImDrawList::ChannelsSplit

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#318]
I've not been tracking down to the detail where the leak is but 
Steps to Reproduce:
1) Open the OpenGL example
2) Add MSVC CRT Memory Leak Check
3) Run the Demo in Debug
4) Open Columns collapsing Header in the demo
5) Close the demo
6) Leak

```cpp
// ImGui - standalone example application for Glfw + OpenGL 2, using fixed pipeline

#include <imgui.h>
#include "imgui_impl_glfw.h"
#include <stdio.h>
#include <GLFW/glfw3.h>
#include <crtdbg.h> // ADD THIS

static void error_callback(int error, const char* description)
{
    fprintf(stderr, "Error %d: %s\n", error, description);
}

int main(int, char**)
{
     // AND THIS
	_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);
    ///....everything as usual
}
```

```
Detected memory leaks!
Dumping objects ->
{1261} normal block at 0x004329D0, 256 bytes long.
 Data: <      #D  jB   D> 00 00 00 00 00 A0 23 44 00 00 6A 42 00 90 95 44 
Object dump complete.
The program '[4544] opengl_example.exe: Native' has exited with code 0 (0x0).
```

**Comment by ocornut** [comment]
Thanks, I'll look at it. I'm doing something rather fishy for the column split/merge mechanism to make the code short and efficient so it's quite possible there's a leak.

**Comment by ocornut** [comment]
Fixed! There was a leak indeed (1 leak of 192 bytes per ImDrawList using channels aka typically Columns). The leak wouldn't grow further.

**Comment by Pagghiu** [comment]
So fast! =D
