### ISSUE TITLE
Compile errors on MinGW

### ISSUE THREAD

**Issue by TheMostDiligent** [ocornut/imgui#3183]
**Version/Branch of Dear ImGui:**

Version: 1.77 (WIP)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + custom engine/back-end
Compiler: x86_64-w64-mingw32-c++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Operating System: Windows

**My Issue/Question:**

`imgui_impl_win32.cpp` fails to compile on MinGW/Windows with error at [line 408](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_win32.cpp#L408):

```
...\imgui\examples\imgui_impl_win32.cpp:408:5: error: 'SetProcessDPIAware' was not declared in this scope
     SetProcessDPIAware();
     ^~~~~~~~~~~~~~~~~~
```

**Comment by ocornut** [comment]
I'll see if I can add a fix but you are supposedly to specify a value for `_WIN32_WINNT` when compiling with Cygwin, otherwise you are compiling for extremely old versions of Windows.

**Comment by ocornut** [comment]
Pushed a fix. Note that by default if you don't specify a windows version, MinGW is compiling with 0x503 aka "Windows Server 2003" so you'll be missing various features. 
See values https://docs.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=vs-2019

**Comment by TheMostDiligent** [comment]
Thank you!
