### ISSUE TITLE
Date/calendar widget?

### ISSUE THREAD

**Issue by cesss** [ocornut/imgui#3189]
**My Issue/Question:**

Did anybody implement a date/calendar widget? I'm asking just for avoiding reinventing the wheel...

**Comment by ocornut** [comment]
There’s one listed in the wiki.

**Comment by cesss** [comment]
Thanks a lot, @ocornut !! The funny thing is that I did looked at the wiki before posting and didn't find it... I believe I'm starting to "read in diagonal" these days... a bad symptom 😄

**Comment by colesnicov** [comment]
> **My Issue/Question:**
> 
> Did anybody implement a date/calendar widget? I'm asking just for avoiding reinventing the wheel...

Do you have something?

**Comment by ClaasJG** [comment]
See https://github.com/ocornut/imgui/wiki/Useful-Extensions .
Flix01's ImGui-Addons contains a date picker.
