### ISSUE TITLE
Error after include libraries

### ISSUE THREAD

**Issue by duongbaoquy** [ocornut/imgui#3191]
Hello,
Thanks for a great library. Currently I am using it to create my own application, but encounter some errors (after I included imgui_impl_glfw.h>  that I still don't really understand. Can you help me understand why these errors occur and how to fix them?
Sorry if this was a silly question. 
Thanks for reading
![image](https://user-images.githubusercontent.com/62133702/80955248-2a239600-8e29-11ea-8df5-7eff02a26191.png)

**Comment by ocornut** [comment]
- You haven't filled the requested issue template, please fill it for subsequent issue. 
- You need to include `imgui.h` before including other includes.
- Note that this was actually changed/fixed by #3105 on April 6 (commit 00927105b)
