### ISSUE TITLE
Cannot query search to MySQL

### ISSUE THREAD

**Issue by sungardaJ** [ocornut/imgui#3192]
So recently I've been trying to connect my MySQL database and read data from it. However, I encountered a problem where to program does compile, and will indeed work, but will close itself after a few seconds. 
The error I got was "exited with code -1073741819."
I used the included ImGui program example as my base, https://github.com/ocornut/imgui/blob/master/examples/example_win32_directx9/main.cpp 
I did not change anything except for the main loop, the part where it says  "// 2. Show a simple window that we create ourselves. We use a Begin/End pair to created a named window."

Here is my code:

`        {
            MYSQL* conn;
            MYSQL_ROW row;
            MYSQL_RES* res;
            conn = mysql_init(0);

            conn = mysql_real_connect(conn, "localhost", "root", "toor", "sql_store", 3306, NULL, 0);
            int qstate;

            ImGui::Begin("Window");

            ImGui::Columns(8);
            ImGui::Text("ID");
            ImGui::NextColumn();
            ImGui::Text("ID 1");
            ImGui::NextColumn();
            ImGui::Text("Class");
            ImGui::NextColumn();
            ImGui::Text("Subject");
            ImGui::NextColumn();
            ImGui::Text("Name");
            ImGui::NextColumn();
            ImGui::Text("Score 1");
            ImGui::NextColumn();
            ImGui::Text("Score 2");
            ImGui::NextColumn();
            ImGui::Text("Score 3");
            ImGui::NextColumn();
            ImGui::Separator();

                if (!qstate) {

                    std::string query = "SELECT * FROM sql_store.studentdata;";
                    const char* q = query.c_str();
                    qstate = mysql_query(conn, q);
                    res = mysql_store_result(conn);

                    while (row = mysql_fetch_row(res)) {
                        ImGui::Text(row[0]);
                        ImGui::NextColumn();
                        ImGui::Text(row[1]);
                        ImGui::NextColumn();
                        ImGui::Text(row[2]);
                        ImGui::NextColumn();
                        ImGui::Text(row[3]);
                        ImGui::NextColumn();
                        ImGui::Text(row[4]);
                        ImGui::NextColumn();
                        ImGui::Text(row[5]);
                        ImGui::NextColumn();
                        ImGui::Text(row[6]);
                        ImGui::NextColumn();
                        ImGui::Text(row[7]);
                        ImGui::NextColumn();
                        ImGui::Text(row[8]);
                        ImGui::NextColumn();
                    }
                }

            ImGui::End();
        }`

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
Closing, blocked.
