### ISSUE TITLE
IsWindowMoving or IsWindowResized ?

### ISSUE THREAD

**Issue by DaveInDev** [ocornut/imgui#3196]
Version: Dear ImGui 1.77 WIP (17601)
Branch: master
Back-ends: SFML
Compiler: VS2019 c++
Operating System: win10x64

Hi there,
I looked into the doc and code for a way to detect if a ImGUI window is currently being moved or resized by the user, but I did not find anything ? 
I saw a IsWindowFocused() that is in the same "window event" flavour, but nothing about position/size being touched. Did I miss something ?
These flags could be up as soon as the user grab any edge of the window, or its titlebar (and only if the window is movable/resizable).

**Comment by ocornut** [comment]
Hello Dave,

As per the issue guidelines, when asking such question please always specify and clarify why you need this, then we can head toward a satisfying solution. (otherwise, http://xyproblem.info/)

**Comment by DaveInDev** [comment]
Oh yes, you're right, I'm quite new to this, sorry.
I would like to restrain the position and size of ImGui window in the main app window, so that they never hide a specific zone of the main window. It would be easier if I have some kind of "moving/resizing" flag(almost events), to detect any change and to react accordingly.

**Comment by ocornut** [comment]
You can use `SetNextWindowSizeConstraints()` to restrict size.
We don't have a `SetNextWindowPosConstraints()` function although this is discussed in #2827 (but #2827 specifically requested a work-area which could be honored without custom constraint as well).

Using `imgui_internal.h` you may compare the value of `g.MovingWindow` to current window pointer.

**Comment by DaveInDev** [comment]
thx man.
