### ISSUE TITLE
How to use ImGui::Image() in dx12, help, please !

### ISSUE THREAD

**Issue by Kinesiser** [ocornut/imgui#3197]
**Version/Branch of Dear ImGui: 1.77 WIP

Version: dx12 , not the dx12 Ultimate

Branch: I am sorry, I am foreigner, I first using github and am poor in English that I don`t know what to write in this row. Google translation can not help me. By the way, is Branch the way to show the wrong code ? 

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx12.cpp + imgui_impl_win32.cpp + main.cpp in example
Compiler: VS2019 
Operating System: win10 

**My Issue/Question:**

hello, 

I am sorry. I have tried much times, almost four days. I want to use ImGui to be the GUI of my homework. I can only write words with dx12. The issue is that I can not even use ImGui::Image(). But I really need a GUI, I like Dear ImGui, I want to do with it.

The issue is throwed in code of ImGui. But I can not solve it by myself. It`s so sad. 

The fact is that I have seen the FAQ : ImGui::Image(), downloaded demo, the example and .h .cpp. But ImGui::Image() is not often used. I can load texture with dx12, but I can not write correctly to use dx12 with ImGui. It's always that the rendering pipeline is in my heart, but if do with ImGui, I can not know what has changed in the process. Such as I can not know use the g_pd3dSrvDescHeap in tutorial main.cpp or not. Because ImGui has two way to show the texture. No shader,then it's the first way. I give texture to the ImGui::Image(), then it can draw. But how it do the rendering in the function, did it use the pipeline ? If yes, what I do to the Resource, Heap, CPU/GPU Handle, View, how can I bind them to the pipeline ? If I use my variables, I don't know how it works in the ImGui pipeline. From the error, I think that's what I do cause the error. But I can not know it`s where, because I can not know the whole pipeline works. There's some process in the ImGui API that I can't know.

I hope that could you give some more tutorial with dx12 ? It`s hard for a fresher to do the work by seeing dx11 examples.  I have searched a lot, but there is little about dx12 doing the same things. 

Only you could help me, please !

**Screenshots/Video**

The things below is the code. 

First two is my code, last two is the error that I can`t solve.
I have do just as the tutorial in FAQ about image. 
Firstly, the load function I use the nvidia texture tools to change file to dds. Then use dx12 fucntion load the texture. But throw the first error. 
Second time, I use the stbi_load to get the file data, but throw the second error.

I have do the things just like what the FAQ said, but I can not know the reason what cause them.

![QQ截图20200505210204](https://user-images.githubusercontent.com/61084464/81069018-df327d00-8f13-11ea-97f8-6a4b82b97e4e.png)

![QQ截图20200505210218](https://user-images.githubusercontent.com/61084464/81069037-e8bbe500-8f13-11ea-8db8-5e18c72cf1c2.png)

![QQ截图20200505205514](https://user-images.githubusercontent.com/61084464/81068474-03da2500-8f13-11ea-8b76-91a2a8ae43c4.png)

![QQ截图20200505205605](https://user-images.githubusercontent.com/61084464/81068493-089ed900-8f13-11ea-96a9-2d115c5047da.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```

That`s two fucntions.
One using nvidia texture tool and d3dx12.h fucntion load the texture.
The other using stbi_load()

void LoadMyTextureAgain(CD3DX12_GPU_DESCRIPTOR_HANDLE* texGPUHandle)
{


    Texture* fruitTex = new Texture();
    fruitTex->Name = "fruitTex";
    fruitTex->Filename = L"D:\\OneDrive保存的信息\\OneDrive\\桌面\\1.dds";
    DirectX::CreateDDSTextureFromFile12(g_pd3dDevice, g_pd3dCommandList, fruitTex->Filename.c_str(), fruitTex->Resource, fruitTex->UploadHeap);

    assert(fruitTex->Resource != NULL);

    //--------------------------------------------------------------------------------------------

    ID3D12DescriptorHeap* mSrvDescHeap = nullptr;


    D3D12_DESCRIPTOR_HEAP_DESC srvHeapDesc = {};
    srvHeapDesc.NumDescriptors = 1;
    srvHeapDesc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
    srvHeapDesc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
    g_pd3dDevice->CreateDescriptorHeap(&srvHeapDesc, IID_PPV_ARGS(&mSrvDescHeap));



    CD3DX12_CPU_DESCRIPTOR_HANDLE texCPUHandle(mSrvDescHeap->GetCPUDescriptorHandleForHeapStart());

    D3D12_SHADER_RESOURCE_VIEW_DESC srvDesc = {};
    srvDesc.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
    srvDesc.Format = fruitTex->Resource->GetDesc().Format;
    srvDesc.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
    srvDesc.Texture2D.MostDetailedMip = 0;
    srvDesc.Texture2D.MipLevels = fruitTex->Resource->GetDesc().MipLevels;
    srvDesc.Texture2D.ResourceMinLODClamp = 0.0f;
    g_pd3dDevice->CreateShaderResourceView(fruitTex->Resource.Get(), &srvDesc, texCPUHandle);

    texCPUHandle.Offset(1, g_pd3dDevice->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV));


    //-----------------------------------------------------------------------------------------------------

    ID3D12RootSignature* mRootSignature = nullptr;


    CD3DX12_DESCRIPTOR_RANGE texTable;
    texTable.Init(D3D12_DESCRIPTOR_RANGE_TYPE_SRV, 1, 0);

    CD3DX12_ROOT_PARAMETER slotRootParameter[1];
    slotRootParameter->InitAsDescriptorTable(1, &texTable, D3D12_SHADER_VISIBILITY_PIXEL);

    CD3DX12_ROOT_SIGNATURE_DESC rootSigDesc(1, slotRootParameter, 0, nullptr, D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT);
    Microsoft::WRL::ComPtr<ID3DBlob>serializedRootSig = nullptr;
    Microsoft::WRL::ComPtr<ID3DBlob>errorBlob = nullptr;
    HRESULT hr = D3D12SerializeRootSignature(&rootSigDesc, D3D_ROOT_SIGNATURE_VERSION_1, serializedRootSig.GetAddressOf(), errorBlob.GetAddressOf());
    g_pd3dDevice->CreateRootSignature(0, serializedRootSig->GetBufferPointer(), serializedRootSig->GetBufferSize(), IID_PPV_ARGS(&mRootSignature));


    //--------------------------------------------------------------------------------------------------




    texGPUHandle = new CD3DX12_GPU_DESCRIPTOR_HANDLE(mSrvDescHeap->GetGPUDescriptorHandleForHeapStart());

    /*
    assert(texGPUHandle != NULL);
    g_pd3dCommandList->SetGraphicsRootSignature(mRootSignature);
    ID3D12DescriptorHeap* descHeaps[] = { mSrvDescHeap };
    g_pd3dCommandList->SetDescriptorHeaps(_countof(descHeaps), descHeaps);
    g_pd3dCommandList->SetGraphicsRootDescriptorTable(0, *texGPUHandle);
    */


    //fruitTex->Resource->Release();
    //fruitTex->UploadHeap->Release();
    //g_pd3dCommandList->Close();

}


bool LoadTextureAgain(CD3DX12_GPU_DESCRIPTOR_HANDLE* myTexGPUHandle,int* out_width,int* out_height)
{
    int image_width = 0;
    int image_height = 0;
    unsigned char* image_data = stbi_load("../MyImage01.jpg", &image_width, &image_height, NULL, 4);
    if (image_data == NULL)
    {
        throw("image_data is null");
        return false;
    }


    Microsoft::WRL::ComPtr<ID3D12Resource> texBuffer = nullptr;
    Microsoft::WRL::ComPtr<ID3D12Resource> texBufferUploader = nullptr;

    texBuffer = d3dUtil::CreateDefaultBuffer(g_pd3dDevice, g_pd3dCommandList, image_data, sizeof(*image_data), texBufferUploader);

    CD3DX12_CPU_DESCRIPTOR_HANDLE texCPUHandle(g_pd3dSrvDescHeap->GetCPUDescriptorHandleForHeapStart());
    
    D3D12_DESCRIPTOR_HEAP_DESC srvHeapDesc = {};
    srvHeapDesc.NumDescriptors = 1;
    srvHeapDesc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
    srvHeapDesc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
    g_pd3dDevice->CreateDescriptorHeap(&srvHeapDesc, IID_PPV_ARGS(&g_pd3dSrvDescHeap));

    D3D12_SHADER_RESOURCE_VIEW_DESC srvDesc = {};
    srvDesc.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
    srvDesc.Format = texBuffer->GetDesc().Format;
    srvDesc.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
    srvDesc.Texture2D.MostDetailedMip = 0;
    srvDesc.Texture2D.MipLevels = texBuffer->GetDesc().MipLevels;
    srvDesc.Texture2D.ResourceMinLODClamp = 0.0f;
    g_pd3dDevice->CreateShaderResourceView(texBuffer.Get(), &srvDesc, texCPUHandle);

    texCPUHandle.Offset(1, g_pd3dDevice->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV));

    myTexGPUHandle = new CD3DX12_GPU_DESCRIPTOR_HANDLE(g_pd3dSrvDescHeap->GetGPUDescriptorHandleForHeapStart());
    *out_width = image_width;
    *out_height = image_height;

    stbi_image_free(image_data);

    return true;
}

```

**Comment by ocornut** [comment]
You seem to be passing a pointer to D3DX12_CPU_DESCRIPTOR_HANDLE as ImTextureId whereas the documentation says you should pass a D3DX12_CPU_DESCRIPTOR_HANDLE (NOT a pointer to it), which is why this code currently only compiles in 64-bit modes (because D3DX12_CPU_DESCRIPTOR_HANDLE is always 64-bit but ImTextureId by default is sizeof(void*))

Please paste code instead of picture.
You can use e.g. `ImGui::Image((void*)*myTexGpuHandle)` or `ImGui::Image(*(void**)myTexGpuHandle)`.

**Comment by Kinesiser** [comment]
Thank you !
I will trying it again. The project is too big to upload. Above two pictures are all my code, the other is the main.cpp of tutorial.
And here is almost 12pm, if I have problem, could I bother you tomorrow ?

**Comment by Kinesiser** [comment]
And I try ImGui::Image(*(void**)myTexGpuHandle) . It can works, but get something that I can't know.

![QQ截图20200506001443](https://user-images.githubusercontent.com/61084464/81089876-7f49cf80-8f2f-11ea-88f0-c6f737a8247d.png)

**Comment by ocornut** [comment]
Please use Discord for further discussion, thank you.

**Comment by ocornut** [comment]
You may also read about UV Coordinates here 
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#About-texture-coordinates

And research it on the internet.

**Comment by ocornut** [comment]
We added a dx12 exemple here
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
