### ISSUE TITLE
Navigation focus loss on window open

### ISSUE THREAD

**Issue by domgho** [ocornut/imgui#3202]
**Version/Branch of Dear ImGui:**

Version: 1.75
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom
Compiler: MSVC 2019
Operating System: Win 10

**My Issue/Question:**

I am hiding/showing my HUD window when pressing a button in another window. The issue I am facing is that the toggle button loses navigation focus after pressing it.

It seems a newly opened window always takes navigation focus from the currently active one.

**Standalone, minimal, complete and verifiable example:**
```c++
static bool show = false;
if (show)
{
    ImGui::Begin("HUD");
    ImGui::End();
}

ImGui::Begin("OtherWindow");
ImGui::Button("Hello");
if (ImGui::Button("Toggle"))
    show = !show;
ImGui::End();
```
1. Click on Hello button and verify keyboard/gamepad navigation between Hello button and Toggle button works inside OtherWindow
2. Press toggle button using keyboard/gamepad (Space? Enter? A?)
3. Notice how the toggle button (and the whole OtherWindow) loses naviation focus and you can no longer continue navigating inside OtherWindow

EDIT: Adding ImGuiWindowFlags_NoFocusOnAppearing flag to the HUD window fixes it

**Comment by ocornut** [comment]
Please clarify how to repro using code above.

**Comment by domgho** [comment]
@ocornut Sorry, I have just added clear reproduction steps:

1. Click on Hello button and verify keyboard/gamepad navigation between Hello button and Toggle button works inside OtherWindow
2. Press toggle button using keyboard/gamepad (Space? Enter? A?)
3. Notice how the toggle button (and the whole OtherWindow) loses naviation focus and you can no longer continue navigating inside OtherWindow
