### ISSUE TITLE
Access violation exception when resizing viewport

### ISSUE THREAD

**Issue by Redcrafter** [ocornut/imgui#3204]
**Version/Branch of Dear ImGui:**

Version: 1.77 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: msvc
Operating System: Windows 10

**My Issue/Question:**

I am getting an Access violation exception when resizing viewports using the triangle in the bottom right. Resizing by dragging the right or bottom edge does not cause this.

**Screenshots/Video**

![out](https://user-images.githubusercontent.com/19157738/81178011-d9867700-8fa7-11ea-81d8-5044adc4caac.gif)

**Standalone, minimal, complete and verifiable example:**
Using unmodified code from examples/example_glfw_opengl3

**Comment by ocornut** [comment]
I cannot repro here.

What's your GPU and drivers? 
Try updating the drivers (e.g directly from nvidia).
Try downloading symbols for the DLL to see where it could crash etc.

**Comment by Redcrafter** [comment]
I managed to fix it. After looking at call stack some more i noticed nahimicosd.dll in there which is part of my audio driver. Uninstalling it solved the issue.

**Comment by ocornut** [comment]
Nahimic is plague.... When I got my new laptop the sound was garbled I almost returned it until I noticed it was a bug in the Nahimic software breaking audio output severely...
