### ISSUE TITLE
Hardly visible vertical scroller in the full-screen mode

### ISSUE THREAD

**Issue by MichaelKv** [ocornut/imgui#3205]
Hello. I use 
ImGui::SetNextWindowSize(ImVec2());
ImGui::SetNextWindowPos(ImVec2());
ImGui::Begin("Mike Plot");
to emulate the full-screen mode. My window contains several plots that do not fit into the window so the vertical scroller appears. The scroller works OK without SetNextWindowXXX calls but it is hardly visible and usable (it is hard to notice it and pick it with the mouse) in my “full-screen” mode. What is the correct way of the full-screen mode implementation?
Thank you in advance,
--
Michael

![VScrollerInFullScreen](https://user-images.githubusercontent.com/37277165/81186360-596a0c80-8fbb-11ea-80f0-eecb8bec228d.png)

**Comment by ocornut** [comment]
Use `io.DisplaySize` for size, not `ImVec2(0,0)`
