### ISSUE TITLE
Make ImDrawData* instance persistant.

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#321]
Move ImDrawData from stack to context so user can hold on it between Render() and NewFrame(), and perhaps an accessor to this data. This would make the RenderFunc optional.

This is partly to appear more friendly on the surface to people who have an irrational fear and misunderstanding of global state, to over-engineered code-bases and those with pedantically strict coding style. (That sentence may carry a certain bias)

**Comment by Pagghiu** [comment]
The only limitations I've found with global state is that it makes it not possible to use imgui from multiple threads. I've found some use cases where being able to "generate" the gui in different threads (one thread per window) and then composing/rendering "later" (in another thread) would have made code a little bit simpler, expecially on OSX where if you want to do a "proper" desktop application, you should run your stuff in the main loop (generation) and rendering in the vsync loop (handled by the OS).
But, as always, no big deal, putting the right synchronization primitives here and there solved the issue with little performance cost.

**Comment by ocornut** [comment]
Yeah but that's a vastly different topic. ImGui isn't engineered to be thread-safe, it's obviously a state machine and it's meant to leave you the responsibility of handling that access at the granularity of the whole interface. If we were to support simultaneous multi-thread rendering, e.g. on different window that would requires quite some re-engineering and I wouldn't know how to make the library as efficient then.

**Comment by ocornut** [comment]
Done
