### ISSUE TITLE
Popups can no longer be opened on first frame on the docking branch

### ISSUE THREAD

**Issue by wolfpld** [ocornut/imgui#3211]
Version: `ecf82ca8066`
Branch: `docking`

The following code creates a window with a button. Clicking on the button opens a popup. In certain situations we may want to force this popup to be opened right away when the UI is presented to the user, without their interaction. We can achieve that by using a variable, which will act as-if user clicked the button (realistically this would be `bool`).

```
static int force = 1;
ImGui::Begin( "test" );
if( ImGui::Button( "test" ) || force > 0 )
{
    force--;
    ImGui::OpenPopup( "testPopup" );
}
if( ImGui::BeginPopup( "testPopup" ) )
{
    ImGui::Text( "popup" );
    ImGui::EndPopup();
}
ImGui::End();
```

Note that popup positioning code is omitted in this example, and the popup will appear at the location of the mouse cursor. This behavior should be kept in mind, as it may mislead into thinking that the popup hasn't opened, if careful observation is not performed.

On ImGui version 1.76 this code works as expected. On `docking` branch however, the popup is never seen. Both the `OpenPopup()` function and `BeginPopup()` branch are entered during the first frame, but in the next frames `BeginPopup()` returns false. Attributing this to misbehavior during the first frame can be confirmed by changing the initial value of `force` to 2, in which case `OpenPopup()` is also called in second frame, resulting in popup being displayed.

**Comment by ocornut** [comment]
I'm not sure it is specific to the docking branch, but if another window takes the focus it will close the popup. The docking system can create windows in `NewFrame()` and various constructs on your side may also lead to windows appearing a little later and therefore taking focus away from the popup.

If I paste your repro at the end of the main.cpp demo I can see the popup, If i paste it at the beginning of the main loop in main.cpp the popup gets closed by other windows in that main.cpp main loop. That, regardless of being on docking or master.

In imgui_internal.h you can try looking for this block:
```
// Debug Logging for selected systems. Remove the '((void)0) //' to enable.
```

Uncommenting
```
#define IMGUI_DEBUG_LOG_POPUP         IMGUI_DEBUG_LOG // Enable log
```
And commenting
```
//#define IMGUI_DEBUG_LOG_POPUP(...)      ((void)0)       // Disable log
```

And you'll get some printf which may lead you to understand why the popup is being closed.

PS: The debug log in `ClosePopupsOverWindow()` might crash on `ref_window->Name` deference, which you could fix with `ref_window ? ref_window->Name : "<NULL>"` if needed.

**Comment by wolfpld** [comment]
The root cause of this issue was adding a new window for layout purposes, which was not needed in the non-docking version. This indeed closed the popup.

If anyone would encounter this issue in the future, I will present a little wrapper class, which can be used as a workaround (it also has uses in other places where ImGui has friction in the first frame):

```c++
template<typename T>
class DecayValue
{
public:
    DecayValue( const T& init, bool active = false )
        : m_value( init )
        , m_active( active )
    {
    }

    operator const T& () const { return m_value; }
    T operator->() const { return m_value; }

    DecayValue& operator=( const T& value )
    {
        m_value = value;
        m_active = true;
        return *this;
    }

    void Decay( const T& value )
    {
        if( m_active )
        {
            m_active = false;
        }
        else
        {
            m_value = value;
        }
    }

private:
    T m_value;
    bool m_active;
};
```

Feel free to close this issue, if the current behavior is intended.

**Comment by ocornut** [comment]
Yeah, I'm not sure what else there is we can do presently, if variants of this issue eventually pop-up we can come back to that but right now I guess I'll close this.

I would like it better if those debug logs would be more readily available (e.g. a synthetic compressed event log could be made available which might helps some users, generally understanding issues related to Focus, Popup or Docking operations can be hard if you don't know where to look, which is why I added those debug flags but more people won't think of using them..).
