### ISSUE TITLE
Viewports without backgrounds leave void of nodraw

### ISSUE THREAD

**Issue by anthofoxo** [ocornut/imgui#3213]
**Version/Branch of Dear ImGui:**

Version: 1.77 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Microsoft Visual Studio Compiler
Operating System: Windows 10

Using viewports and the option "No Background" leaves void of nodraw
Using the demo window (or any window).

Using the demo window with viewports enabled, drag it from the main application window and enable window configuration->no background. from here interacting with menus, hovering over the main app window leave an uncleared color buffer. Going into the source, i enable GLFW_TRANSPARENT_FRAMEBUFFER which fixes some of the transparency issues, however this still leaves uncleared data from iterations with menus etc.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/17318787/81459965-6714c300-9170-11ea-8ca4-8d4000f1974f.png)

https://www.youtube.com/watch?v=jDDqmTxTpU8

I've managed to fix this issue by a few small edits, however i doubt its good for merging but i'll put it here for reference

https://github.com/anthofoxo/imgui/commit/3f25c53fd851ddfdaf98b9ad4ed43d4ea17e82c5

**Comment by anthofoxo** [comment]
Also the screenshot and video are without my small transparent framebuffer modification

**Comment by ocornut** [comment]
`Begin()` on owned viewports sets the `ImGuiViewportFlags_NoRendererClear` flag on the viewport:

```
// We also tell the back-end that clearing the platform window won't be necessary, as our window is filling the viewport and we have disabled BgAlpha
viewport_flags |= ImGuiViewportFlags_NoRendererClear;
window->Viewport->Flags = viewport_flags;
```

I think we can remove this when _NoBackground is set on the window, however, not that your rendering is likely to instead clear the framebuffer, so if you want transparent windows you may need to alter the rendering backend.

This is what the OpenGL renderer does when rendering:

```
static void ImGui_ImplOpenGL3_RenderWindow(ImGuiViewport* viewport, void*)
{
    if (!(viewport->Flags & ImGuiViewportFlags_NoRendererClear))
    {
        ImVec4 clear_color = ImVec4(0.0f, 0.0f, 0.0f, 1.0f);
        glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
        glClear(GL_COLOR_BUFFER_BIT);
    }
    ImGui_ImplOpenGL3_RenderDrawData(viewport->DrawData);
}

static void ImGui_ImplOpenGL3_InitPlatformInterface()
{
    ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();
    platform_io.Renderer_RenderWindow = ImGui_ImplOpenGL3_RenderWindow;
}
```

So you would likely need to hook `platform_io.Renderer_RenderWindow` with your own function.

**Comment by ocornut** [comment]
Pushed a fix to not set ImGuiViewportFlags_NoRendererClear when ImGuiWindowFlags_NoBackground is set. Please note the above - background color is technically then undefined so if you rely on that you may need to clear background with your own color if meaningful.

**Comment by ikrima** [comment]
afaict, this fix  causes ImGuiViewportFlags_NoRendererClear  to never be set. bug or intended?
- can't see anyway ImGuiViewportFlags_NoRendererClear gets set
- unless it's meant to only for manual override with SetNextWindowClass/ViewportFlagsOverrideSet

**Comment by ocornut** [comment]
@ikrima You are correct. Looking at this now.

**Comment by ocornut** [comment]
Afaik the previous fix was just backward, fixed the fix.

However, generally speaking the request of @anthofoxo comes from a desire of supporting compositing of transparent windows, which will need further work and standardization on the backends side. Will discuss this further in #2766.
