### ISSUE TITLE
Rendering Speed

### ISSUE THREAD

**Issue by kpo8** [ocornut/imgui#3216]
**Version/Branch of Dear ImGui:**

Version: NA
Branch: NA _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: NA _(if the question is related to building or platform specific features)_
Operating System: NA

**Background**
Hi, first off I have been lurking on this repo for about three months and I have read quite a lot of issues and I have seen your problem with cheaters.  I apologize for that,people have no shame, I would like to say I am doing nothing with video games. I feel I need to mention that because I have not used this account since school, so my repos are a little dated (I use gitlab)
Frankly, ImGui is an amazing little library to use and very intuitive.

**Question**
My question is conceptual in nature and  relates to the render. ImGui works by rendering frame by frame, so I need a while loop to accomplish this. I am doing a lot of logic between  frames, and impressively it has not slowed the renderer down.The only time it slows it down is when I am doing a labor intensive task like scanning for Bluetooth devices in between frames (which I solved by making thread and detaching it). But other things I cannot delegate to separate threads (like Imgui calls),
so the question is, for example, how many imgui objects can the renderer generate per frame before performance starts to slow down? If this is more of an Opengl question, then I apologize for asking in the wrong place.

I am developing on a single board computer with some horsepower but I still need to be conscious of overhead.

Ex: 10 buttons works fine
       100 buttons assuming still works fine
       1000 butttons ???

**Screenshots/Video**

NA

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

NA

// Here's some code anyone can copy and paste to reproduce your issue
NA
```

**Comment by ocornut** [comment]
Why not testing things yourself with a loop?

**Comment by ocornut** [comment]
PS: The general answer is that 1000+ widgets is largely fine, but for very large lists (e.g. 10k+ items) you can use `ImGuiListClipper` to coarse-clip non visible items.

**Comment by kpo8** [comment]
I did not think of the above, sorry!!

If if it can handle 1,000 widgets without struggling then I am fine. I'm working with a project where many people are adding many things and I panicked about this the other day. This answers my question. 

As to the "how" the renderer does this (and rendering in general), I think I can find that information elsewhere.

Thank you!!
