### ISSUE TITLE
ImGuiTreeNodeFlags_DefaultOpen does not update ImGuiStorage

### ISSUE THREAD

**Issue by OriolCS2** [ocornut/imgui#3221]
Version: 1.74
Branch: docking

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Operating System: Windows 10 pro

Hello, I'm trying to know if a collapsing header is opened or closed and I'm doing this by using this piece of code:

`ImGui::GetStateStorage()->GetInt(ImGui::GetCurrentWindow()->GetID("Transform"))`

My Collapsing header is this:

`ImGui::CollapsingHeader("Transform", ImGuiTreeNodeFlags_DefaultOpen | ImGuiTreeNodeFlags_AllowItemOverlap);`

What I've found is that when the collapsing header has the flag ImGuiTreeNodeFlags_DefaultOpen, the ImGuiStorage has 0 (but the collapsing header is opened) but when I closed it and then I reopen it, now it has a 1.

So the problem I have is that when I open the application, and I try to Get the int of the ImGuiStorage of my collapsing header it returns me a 0, but the collapsing header is opened. If then I close it and reopen it, it goes perfect. So I think that the problem is because of the flag ImGuiTreeNodeFlags_DefaultOpen

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/36154523/81508629-711bfa80-9305-11ea-88a7-6f2900f90255.gif)

As it can be seen in the gif, when I first open my application, the collapsing header is opened but the ImGuiStorage says it is not opened. 

Is there any way to know if a collpasing header is opened if the collapsing header has this flag ImGuiTreeNodeFlags_DefaultOpen?

Thanks!!

**Comment by ocornut** [comment]
Hello,

Look what TreeNodeBehavior is doing.

**Comment by OriolCS2** [comment]
ImGuiStorage is just updated when there is an input of the user, that is what I've seen. So there is no way to know if it is opened or closed, am I right?

**Comment by ocornut** [comment]
Look how TreeNodeBehavior is querying that information, there’s a function for it.

Beside, if you know the tree node is open by default then you can consider it is open when not in the storage. That’s what that function is doing.

**Comment by OriolCS2** [comment]
Yes you are right, if it does not exists in storage then I know it is opened. Thank you, I did not realized that. I close the issue.
