### ISSUE TITLE
Weird keyboard nav with multiple BeginMenu calls

### ISSUE THREAD

**Issue by u3shit** [ocornut/imgui#3223]
**Version/Branch of Dear ImGui:**

Version: 1.77
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glew.cpp + imgui_impl_opengl3.cpp
Operating System: Linux

**My Issue/Question:**

In my program, I can call BeginMainMenuBar and BeginMenu multiple times, and the menu items I add are automatically combined. Neat! But the keyboard navigation is working weird in this case. In the example below I add 4 menu items in two different locations. If I open the menu and start pressing the down button, the selection goes to `a`, `b` then it wraps back to `a`. If I press up, I get to `d` and actually only pressing the up button I can go through the whole menu, but not in the other direction. Also if I press down while `d` is selected, nothing happens.
The comment in `imgui.h` says "Use BeginMenu() to create a menu. You can call BeginMenu() multiple time with the same identifier to append more items to it." so I suppose this is a supported operation, and it works fine with mouse.

**Screenshots/Video**

![foo](https://user-images.githubusercontent.com/17014489/81515893-58780880-9336-11ea-9212-a3d9741b1acf.gif)

**Standalone, minimal, complete and verifiable example:**
```c++
if (ImGui::BeginMainMenuBar())
{
  if (ImGui::BeginMenu("Menu"))
  {
    ImGui::MenuItem("a");
    ImGui::MenuItem("b");
    ImGui::EndMenu();
  }
  ImGui::EndMainMenuBar();
}

if (ImGui::BeginMainMenuBar())
{
  if (ImGui::BeginMenu("Menu"))
  {
    ImGui::MenuItem("c");
    ImGui::MenuItem("d");
    ImGui::EndMenu();
  }
  ImGui::EndMainMenuBar();
}
```

**Comment by ocornut** [comment]
Thanks for reporting. 
Should now fixed by a6f4b0fd70150a7cbde03e99fda09ef7b2bfb6d6 courtesy of @rokups (also added a regression test for it)
