### ISSUE TITLE
Cannot draw anything on top of a image.

### ISSUE THREAD

**Issue by armvirus** [ocornut/imgui#3225]
i am trying
`ImGui::Image(my_texture, ImVec2(my_image_width, my_image_height));
ImGui::Button("Login", ImVec2(ImGui::GetWindowWidth() / 2, ImGui::GetWindowHeight() / 2 - 70))`

but only the image is rendered. and nothing on top.

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
Closing, blocked.
