### ISSUE TITLE
high ASCII support for ImGui::Text* functions

### ISSUE THREAD

**Issue by ceosag** [ocornut/imgui#3238]
**Version/Branch of Dear ImGui:**

Version: v1.77 WIP
Branch: tables

**Back-end/Renderer/Compiler/OS**

Back-ends: custom OpenGL
Operating System: Win10

**My Issue/Question:**

I'm using ImGui to display text content loaded from disk. Some of the text files in question are older and so contain high ASCII characters, for example 0x92 ’. Because the content can be arbitrary, including %whatever sequences, I'm using ImGui::TextUnformatted for display.

When encountering a high ASCII character, RenderText takes the bottom code path here:

```
        // Decode and advance source
        unsigned int c = (unsigned int)*s;
        if (c < 0x80)
        {
            s += 1;
        }
        else
        {
            s += ImTextCharFromUtf8(&c, s, text_end);
            if (c == 0) // Malformed UTF-8?
                break;
        }
```

This fails because the text isn't UTF8, which then causes the string to abort printing partway through.

Is there a way to print text using ImGui to have the content interpreted as ISO-8859-1? Would you be open to accept a patch that added a flag for this (ImGuiTextFlags_Something?) or would you recommend doing work outside ImGui to guarantee that passed-in content is valid UTF8? If the latter, would you be willing to willing to accept a patch that added documenting the requirement that all passed-in content is valid UTF8?

For a simple repro, you can try to print the string "I\x92d be".

**Comment by ocornut** [comment]
Hello,

Unfortunately there are no plan to support local codepage, sorry.
They are widely obsolete tech as this point and I can't find of a way for the library to support them without large amount of cognitive and CPU overhead.

You should convert your content to UTF-8 at runtime prior to displaying it.
Note that C++11 provide `u8""` literals to encode your literals as UTF-8:
https://github.com/ocornut/imgui/wiki/Loading-Font-Example

> If the latter, would you be willing to willing to accept a patch that added documenting the requirement that all passed-in content is valid UTF8?

There are various suggestions and references that the library takes UTF-8 but if you can find other useful places to add that more explicit I'm happy to add them.

**Comment by ocornut** [comment]
Closing as answered.
