### ISSUE TITLE
All my windows scroll themself to the end

### ISSUE THREAD

**Issue by newincpp** [ocornut/imgui#3240]
Hello,
I'm not sure if this is a bug or a missunderstanding but here is my problem:
Any windows with enough content to produce a scrollbar automatically scroll to the end.
If I try to scroll to the top it just goes down again. I just can't reach the start (or I have to be really really fast).
It happen on really all windows so I'm not sure a code snippet will really help but just to have an example to talk with this one:
```
    if (ImGui::CollapsingHeader("availableFunctions")) {
        ImGui::Indent();
        if (ImGui::CollapsingHeader("Function")) {
            for (const ShaderGenTK::Function& func : ShaderFunction::_userDefinedFunctionDB) {
                ImGui::Button(func._symbol.c_str(), ButtonSize);
            }
        }
        if (ImGui::CollapsingHeader("Build-in")) {
            for (const ShaderGenTK::Function& func : ShaderGenTK::glslNativeFuncDB) {
                ImGui::Button(func._symbol.c_str(), ButtonSize);
            }
        }
        if (ImGui::CollapsingHeader("Operators")) {
            for (int8_t i = 0; i < ShaderGenTK::BinaryOperator::MAX_INVALID; ++i) {
                ImGui::Button(ShaderGenTK::BinaryOperator::typeToString((ShaderGenTK::BinaryOperator::Type)i).c_str(), ButtonSize);
            }
        }
        ImGui::Unindent();
    }
```
This piece of code produce the problem I'm talking about when _userDefinedFunctionDB and/or glslNativeFuncDB and/or Operator Enum is too big. But I have also a bunch of multiline inputs text and every single one windows with a scroll bar just scroll down by itself.
Just incase you want to see the whole code it's [here](https://git.n700.ovh/newin/Matther) and the case I'm talking about is in [mattherDisplay_toolTab.cpp](https://git.n700.ovh/newin/Matther/src/branch/master/matther/mattherDisplay_toolTab.cpp)
Imgui.h tells me that I have "1.68 WIP"

Edit: A bit after I posted the issue I started suspecting imgui instead of my code so I tried different thing:
it seems that the problem occur when my wacom bamboo ONE (CTL-471 to be precise) is connected. so I think this is a input catching problem from Imgui as it doesn't occur on any other software. I'm gonna investigate further.
(I'm on linux with xorg 1.20.7, mesa 8.4.0, and xf86-input-wacom 0.39.0 as input drivers with kernel 5.6.13)

**Comment by ocornut** [comment]
Hello,

You ignored and didn’t fill the issue template so there’s no way to tell which platform backend you are using which would be the primary useful information here.

Somehow your tablet/device probably ends up sending inputs that are interpreted as MouseWheel event by the backend. You should be looking at that and debugging how the backend is receiving those inputs.

**Comment by ocornut** [comment]
Please confirm the backend and if it repro in the unmodified example applications.

**Comment by newincpp** [comment]
Oh yeah I'm sorry:
Back-end: glfw (X11 mode)
Renderer: Vulkan
Compiler: clang 10.0.0
OS: Linux (gentoo)

I was able to reproduce it in `imgui/examples/example_glfw_vulkan` but not by default:
The default code worked great but uncommenting `io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;` (as suggested in the demo window) did reproduce the problem.

**Comment by ocornut** [comment]
Interesting! Yes it looks like it is reported as a gamepad then :( i would support reporting this to the glfw repo.
Going to add in some comments to mention this possible behavior.

**Comment by newincpp** [comment]
I guess because it's a glfw problem and not an imgui one I should close this issue
