### ISSUE TITLE
ImFont font error

### ISSUE THREAD

**Issue by Angshu1** [ocornut/imgui#3241]
Hello my code is

static bool pen = false;
ImGuiWindowFlags fhgl = 0;
fhgl |= ImGuiWindowFlags_NoTitleBar;

        ImGuiIO& io = ImGui::GetIO();
        ImFont* font1 = io.Fonts->AddFontDefault();
        ImFont* font2 = io.Fonts->AddFontFromFileTTF("C:\Windows\Fonts\Ruda-Bold.ttf", 16.0f);

        ImGui::Begin("g",&pen, fhgl);

        ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
        ImGui::TextColored(ImVec4(0.00, 0.91, 0.22, 1.0),"Framerate: (%.1f)", ImGui::GetIO().Framerate);

        ImGui::End();
when i run it sends an error like this https://prnt.sc/sif6j2

even after i remove ImFont* font2 = io.Fonts->AddFontFromFileTTF("C:\Windows\Fonts\Ruda-Bold.ttf", 16.0f);

and run this

ImGuiWindowFlags fhgl = 0;
fhgl |= ImGuiWindowFlags_NoTitleBar;

        ImGuiIO& io = ImGui::GetIO();
        ImFont* font1 = io.Fonts->AddFontDefault();

        ImGui::Begin("g",&pen, fhgl);

        ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
        ImGui::TextColored(ImVec4(0.00, 0.91, 0.22, 1.0),"Framerate: (%.1f)", ImGui::GetIO().Framerate);

        ImGui::End();

it still sends me that error am i doing something wrong?

after retrying https://prnt.sc/sifape

**Comment by rokups** [comment]
Fonts can not be loaded between NewFrame() and EndFrame() calls.

**Comment by ocornut** [comment]
As stated above. Please read the error message provided with asserts they are answering your questions.

**Comment by Angshu1** [comment]
Hello i followed what it stated i resolved my code here https://prnt.sc/siidlh

But when i run it https://prnt.sc/siie15

**Comment by Angshu1** [comment]
> Fonts can not be loaded between NewFrame() and EndFrame() calls.

https://prnt.sc/siidlh
https://prnt.sc/siie15

**Comment by Angshu1** [comment]
Assertion failed: (0) && "Could not load font file!"

**Comment by rokups** [comment]
@Angshu1 next time please do not delete your posts once issue is resolved. Such issues are useful to people who encounter same problems in the future.
