### ISSUE TITLE
Not possible to undock

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#3243]
In last docking branch:
https://github.com/ocornut/imgui/commit/3b3af6b73136a03dfcdb84872fc08542900a1aa8
It is not possible to undock docked windows.

It worked correctly in
https://github.com/ocornut/imgui/commit/7ddc1adefbdca94e7de350653def7a647ff45612

(I have not bisected so could work in between)

**Comment by ocornut** [comment]
Confirmed bug introduced by last merge, working on it.

**Comment by ocornut** [comment]
Should be fixed now, let us know if you stumble on anything else as the code is not trivial (7b3d379819c487f0d5323ed7bd7c9109a2bc1d76 was pretty risky but moving us in a better, more explicit direction).

**Comment by sonoro1234** [comment]
Yes, it is fixed
