### ISSUE TITLE
build instructions for msys2 in example_sdl_opengl3 should use SDL2

### ISSUE THREAD

**Issue by ktye** [ocornut/imgui#3251]
The comment for building on windows/MSYS2 references the wrong package:
https://github.com/ocornut/imgui/blob/master/examples/example_sdl_opengl3/Makefile#L11

it should be `mingw-w64-i686-SDL2` instead of `mingw-w64-i686-SDL`. then it works just fine.

**Comment by ocornut** [comment]
Hello,

I changed it but as with everything package-manager-related I expect the person who added this original comment added this for a reason and it may be SDL on some configuration, SDL2 on others. Updating for now, being just a comment it is fairly harmless :)

Thank you!
