### ISSUE TITLE
Groups do not align as expected

### ISSUE THREAD

**Issue by GkqqNkKC** [ocornut/imgui#3254]
**Version/Branch of Dear ImGui:**

Version: 1.76 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: SFML (OpenGL)
Operating System: Windows 10

**My Issue/Question:**

Groups do not align as expected. Between button `A` and `B` is a visible height difference

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/35461917/82687664-41071c80-9c60-11ea-8bcf-b3761537c5df.png)

**Standalone, minimal, complete and verifiable example:**
```cpp
void group(std::string title, std::function<void()> fct) {
    using namespace ImGui;
    BeginGroup();
    PushFont(GetIO().Fonts->Fonts[1]);
    Text(&title[0]);
    PopFont();
    fct();
    EndGroup();
}
int main() {
    // Before main loop
    ImGui::SFML::Init(window, false);
    auto io = ImGui::GetIO();
    io.Fonts->AddFontFromFileTTF("font.ttf", 18);
    io.Fonts->AddFontFromFileTTF("font.ttf", 30);
    ImGui::SFML::UpdateFontTexture();

    // Inside main loop
    using namespace ImGui;
    Begin("Test", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
    group("Asadasd", [&] {
        Text("gergre");
    });
    SameLine();
    group("Asddasdsad", [&] {
        Text("geefefefefefrgre");
    });
    group("Gd", [&] {
        Button("A");
    });
    SameLine();
    group("hjH", [&] {
        Button("B");
    });
    SameLine();
    group("hjfH", [&] {
        Button("B");
    });
    End();
}
```

**Comment by GkqqNkKC** [comment]
Any updates?

**Comment by rokups** [comment]
It seems like you tripped on [this detail](https://github.com/ocornut/imgui/blob/d29157ce584e731114ff09d448120e094307304f/imgui.cpp#L7320). As a workaround you can add `AlignTextToFramePadding()` after `BeginGroup()`.

**Comment by GkqqNkKC** [comment]
@rokups , it worked. Thx for help
