### ISSUE TITLE
Allow drag window with mouse, but also ignore if appropriate.

### ISSUE THREAD

**Issue by cmaughan** [ocornut/imgui#3256]
**My Issue/Question:**

Suppose I am drawing some custom UI inside an ImGui window.  I know I can stop ImGui from moving the window by making it an invisible button.  But what if I want a combination where sometimes I want to allow ImGui to move the window when clicking, and sometimes I want to take over the mouse interaction?  My scenario is that I have a custom rendered UI on an OpenGL surface, displayed as an image inside an ImGui Window.  I want the user to be able to click elements of that UI and interact with them, but I also want the user to be able to click outside the UI elements - in the dead space around them, to move the window in the usual ImGui way.

Is there a recommended approach to this?  I thought about making it an invisible button, but then forwarding the message to ImGui if I was not interested in it, so that it can implement the window drag.

My motivation is that I like the window drag, it helps stop windows getting stuck off screen.  But I don't want it to universally occur at any point inside my image.

**Comment by cmaughan** [comment]
The following approach gives me what I want; not sure it is elegant or not ;)  m_pCaptureParam indicates if the user is interacting with my custom control....

`    ImGui::GetIO().ConfigWindowsMoveFromTitleBarOnly = (m_pCaptureParam != nullptr);`

**Comment by ocornut** [comment]
Hello,

You should be able to use `StartMouseMovingWindow()` from `imgui_internal.h` when your click lands on area that you don't use. 
In the `docking` branch this function has a slightly different signature to decide how to behave with docking node.

-Omar

**Comment by ocornut** [comment]
Hello @cmaughan,
Did that answer your question?

**Comment by cmaughan** [comment]
Yes, it did, sorry for not closing; I used your approach and it works just fine.
