### ISSUE TITLE
Render metal texture

### ISSUE THREAD

**Issue by KonstantinToporkin** [ocornut/imgui#3257]
Hi, how can I show an Image with metal texture, Image() does not work
this is my texture loading code:
```
    MTLTextureDescriptor *textureDescriptor = [[MTLTextureDescriptor alloc] init];
    
    textureDescriptor.pixelFormat = MTLPixelFormatRGBA32Float;
    
    textureDescriptor.width = width;
    textureDescriptor.height = height;
    id<MTLTexture> texture = [g_device newTextureWithDescriptor:textureDescriptor];
    MTLRegion region = {
        { 0, 0, 0 },                   // MTLOrigin
        {width, height, 1} // MTLSize
    };
    
    NSUInteger bytesPerRow = 4 * width * sizeof(float);
    
    [texture replaceRegion:region
    mipmapLevel:0
      withBytes:imageData
    bytesPerRow:bytesPerRow];
```

**Comment by ocornut** [comment]
Hello Konstantin,

If you look at comments and code in [imgui_impl_metal.mm](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_metal.mm) it says `ImTextureId` is defined as storing a `MTLTexture`. 

Check `makeFontTextureWithDevice()` for an example of creating a texture or any other Metal reference/documentation. The code here is turning an id<MTLTexture> to a `ImTextureId` using `(__bridge void *)texture`

I can't help much more as I'm not a Metal user.

**Comment by KonstantinToporkin** [comment]
th

> Hello Konstantin,
> 
> If you look at comments and code in [imgui_impl_metal.mm](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_metal.mm) it says `ImTextureId` is defined as storing a `MTLTexture`.
> 
> Check `makeFontTextureWithDevice()` for an example of creating a texture or any other Metal reference/documentation. The code here is turning an id to a `ImTextureId` using `(__bridge void *)texture`
> 
> I can't help much more as I'm not a Metal user.

Thank you very much, I will try)
