### ISSUE TITLE
Problems with labels of ImGui long controls like sliders

### ISSUE THREAD

**Issue by MichaelKv** [ocornut/imgui#3262]
Hi.
I have several problems with labels of ImGui items.
1. The total majority people I know read from left to right. All the program they work with and operating systems dialogs put labels of input fields and horizontal sliders on the left. I.e. all of them have a form “Label: <very long input control>”. ImGui places labels on the right. I have to handle the problem with additional programming. Checkboxes and radio-buttons are Ok to have their labels on the right.
2. Horizontal sliders like SliderFloat may not be extended to the full window width. Even having been assigned an invisible label, like "##Label" and with ImGui::PushItemWidth(-100); helper they still have an empty place on the right.
3. Does ImGui have a horizontal slider that a kind of moves a smaller window/range inside of a bigger one? The bigger the internal and external windows/ranges difference/width the smaller the runner size. I mean the following: [-----[===========]------------] and [-----[====]------------------]. I believe ImGui does have it for vertical sliders.

Thank you in advance.

**Comment by ocornut** [comment]
1. This has been discussed in #395, we will eventually support various combination but the current setup (A) makes it easier to support text clipping with single draw call and (B) Is actually much more flexible in term of laying out multiple widgets on a same line. Having label on the left is actually quite a limiting thing. It's easy to re-implement with custom wrapper.

2.  Use PushItemWidth/SetItemWidth(-FLT_MIN) to right align. You are giving the example of `-100` aka "leave 100 pixels unused".  I'm not sure I understand your question.

3. I don't understand your request, so the answer is probably no. You can adjust style.GrabMinSize, and for integer sliders the grab width is adjusted based on the size it represent among the min/max range.

**Comment by MichaelKv** [comment]
I do not know why but I have decided that -100 is a magic value (as -1 for width of a window) while reading this github.com/ocornut/imgui/issues/267 . My bad.
As for 3 I need a horizontal slider as in a text editor. If your screen is 100 symbols wide than while your strings are up to 100 symbols long a gui makes the runner (I am not sure how it is called) of the slider control is so big that it cannot move. 101 symbols long strings make the runner smaller and it can move a little (to scroll one symbol), 200 symbols long strings require the runner to be half the length of the scroller, 1000 symbols long strings and above require the smallest runner possible. I would like to pass to ImGui two ranges -- the big external one and small "visible" one and it would choose the proper length of the runner of the slider control (depending on its screen length).

**Comment by ocornut** [comment]
This is already what the vertical and horizontal scrollbars do I still don't understand your request.

**Comment by MichaelKv** [comment]
IMGUI_API bool          SliderFloat(const char* label, float* v, float v_min, float v_max, const char* format = "%.3f", float power = 1.0f); cannot do it. It does not know about my ranges. I would like to be able to somehow pass the info to it.

**Comment by ocornut** [comment]
OK, so you are trying to create a scrollbar with a slider.
Why not using the regular Horizontal Scrollbar facility provided by windows?

**Comment by MichaelKv** [comment]
If you mean I could make the computer to render the whole data I need to visualize than I cannot do it because the data may not fit in its memory. I do not even use the plot facilities for this because such controls are not supposed to handle really big data. I select and decimate the data according to the window size and the portion is is supposed to show. One portion at a time. In parallel. But ImGui does not really need a parallel processing as I found. It is quick enough itself unlike QT + QWT bundle. The bad news is that my ImGui application is capable to work out the bounce of my mouse pointer (it bounces near the blinking cursor or in the whole ImGui window, at least when I drag the slider). The quick operation becomes the problem and I probably need a replacement for my mouse, or driver or OS -- I cannot believe that the mouse pointer is drawn programmably in the 21st century in Windows.

**Comment by ocornut** [comment]
**I mean if you need a scrollbar, use a scrollbar.**  I don't understand why you need a Scrollbar and are trying to use a Slider for it. This has nothing to do with "rendering whole data", for large sets you can still clip/decimate based on visibility.

If you move the cursor inside a window it enlarge the maximum contents bounds of a window and create a scrollbar when contents is larger than window size. Surely you've noticed that dear imgui has scrollbars already. Horizontal scrollbars needs to be explicitly enabled with `ImGuiWindowFlags_HorizontalScrollbar`.

I don't understand why your message is going in ten different directions instead of sticking on the topic. I'm sorry to say you've reached my patience quota. None of your five issues had the requested issue template filled. Please ask on Discord in the future.
