### ISSUE TITLE
The question about the child windows heights calculation

### ISSUE THREAD

**Issue by MichaelKv** [ocornut/imgui#3263]
I have an ImGui application that plots graphs one in a row. Let us say that there are 7 graphs that fit into the window vertically without a need of a vertical scroller.  I use github.com/epezent/implot libraty and its BeginPlot calls ImGui::BeginChild with the provided size as it is.
I calculate the size of the graph for ImGui::BeginChild as above the following way:
ImVec2 graphWindowSize = ImGui::GetContentRegionAvail();
ImVec2 oneGraphSize = ImVec2(-1, graphWindowSize.y / allGraphs_.size() - allGraphs_.size());
….
ImGui::BeginChild(…, oneGraphSize, …);
Please, notice the “- allGraphs_.size()” part. I need exactly one extra pixel for each ImGui::BeginChild call inside my window to be sure the vertical scroller will not appear. So, if I have 3 graphs I need to calculate the graph child window height the following way: graphWindowSize.y / 3 - 3. If I subtract, for example, 2 or 1 then unneeded vertical scroller appears.
My question is: is such a behavior defective? And if it is not do you plan to provide a kind of helpers for translating floating point arithmetic (rounding) into the window coordinate system?
Thank you.

**Comment by ocornut** [comment]
- All size values needs to be rounded to integer values.

- What's your value for `style.ItemSpacing.y` ? Every item is separated by ItemSpacing.

- Can you confirm this reproduces with e.g. raw `InvisibleButton()` call. Provide a repro would help.

**Comment by MichaelKv** [comment]
> Provide a repro would help.
You are welcome.  For example_win32_directx12:
ImGui::SetNextWindowSize(ImGui::GetIO().DisplaySize);
ImGui::SetNextWindowPos(ImVec2());
ImGui::Begin("Mike", nullptr, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize);
ImVec2 graphWindowSize = ImGui::GetContentRegionAvail();// ImGui::GetWindowSize();
ImVec2 oneGraphSize = ImVec2(-1, graphWindowSize.y / 3 /*- 3*/);
ImGui::BeginChild("1", oneGraphSize);
ImGui::EndChild();
ImGui::BeginChild("2", oneGraphSize);
ImGui::EndChild();
ImGui::BeginChild("3", oneGraphSize);
ImGui::EndChild();
ImGui::End();

**Comment by MichaelKv** [comment]
-3 shall be commented out with c-style comment. I have tried to resend the code with the "insert code" button but it looks awful in preview too.

**Comment by ocornut** [comment]
Use \`\`\` markers to surround code blocks. 
https://guides.github.com/features/mastering-markdown/

**Comment by MichaelKv** [comment]
```
ImGui::SetNextWindowSize(ImGui::GetIO().DisplaySize);
ImGui::SetNextWindowPos(ImVec2());
ImGui::Begin("Mike", nullptr, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize);
ImVec2 graphWindowSize = ImGui::GetContentRegionAvail();// ImGui::GetWindowSize();
ImVec2 oneGraphSize = ImVec2(-1, graphWindowSize.y / 3 /*- 3*/);
ImGui::BeginChild("1", oneGraphSize);
ImGui::EndChild();
ImGui::BeginChild("2", oneGraphSize);
ImGui::EndChild();
ImGui::BeginChild("3", oneGraphSize);
ImGui::EndChild();
ImGui::End();
```

**Comment by ocornut** [comment]
Hello Mike,
Have you read my answer above?

**Comment by ocornut** [comment]
If you take account of item spacing it works:

```
ImGui::Begin("Issue #3263", NULL);
float avail_height = ImGui::GetContentRegionAvail().y;
float spacing_y = ImGui::GetStyle().ItemSpacing.y;

int graph_count = 3;
ImVec2 graph_size;
graph_size.x = -1.0f;
graph_size.y = floorf((avail_height - (graph_count - 1) * spacing_y) / graph_count);

ImGui::BeginChild("1", graph_size, true);
ImGui::EndChild();
ImGui::BeginChild("2", graph_size, true);
ImGui::EndChild();
ImGui::BeginChild("3", graph_size, true);
ImGui::EndChild();
ImGui::End();
```
![image](https://user-images.githubusercontent.com/8225057/82809966-9d02b880-9e8d-11ea-8135-989b8a1107a6.png)

**Comment by MichaelKv** [comment]
Good, thank you. I believe I will set the item spacing to zero for the concrete child window and will take it into account in the future.
