### ISSUE TITLE
Image rotate is not correct

### ISSUE THREAD

**Issue by Yusheng9966** [ocornut/imgui#3267]
(Click "Preview" above ^ to turn URL into clickable links)

1. PLEASE CAREFULLY READ: [FAQ](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md)

2. PLEASE CAREFULLY READ: [Issue Submitting Guidelines](https://github.com/ocornut/imgui/issues/2261)

3. FOR FIRST-TIME USERS ISSUES COMPILING/LINKING/RUNNING/LOADING FONTS,  please use the [Discord server](http://discord.dearimgui.org).

4. PLEASE MAKE SURE that you have: read the FAQ; explored the contents of `ShowDemoWindow()` including the Examples menu; searched among Issues; used your IDE to search for keywords in all sources and text files; and read the link provided in (1) (2).

5. Be mindful that messages are being sent to the e-mail box of "Watching" users. Try to proof-read your messages before sending them. Edits are not seen by those users.

6. Delete points 1-6 and PLEASE FILL THE TEMPLATE BELOW before submitting your issue.

Thank you!

----

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

```
Dear ImGui 1.75 (17500)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1900
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: XXX

**My Issue/Question:**

Image rotate is not correct

**Screenshots/Video**

XXX _(you can drag files here)_
![ScreenShot00013](https://user-images.githubusercontent.com/808664/82976185-fa734280-a010-11ea-9b8e-dc0fb886bfae.png)
![ScreenShot00016](https://user-images.githubusercontent.com/808664/82976210-0fe86c80-a011-11ea-81c4-101f32b9fd12.png)
![ScreenShot00015](https://user-images.githubusercontent.com/808664/82976212-11199980-a011-11ea-8b05-0ce7e6e75cb9.png)
![ScreenShot00014](https://user-images.githubusercontent.com/808664/82976213-124ac680-a011-11ea-9cc7-2011784ecf3f.png)

**Standalone, minimal, complete and verifiable example:** _(see []([]([](https://github.com/ocornut/imgui/issues/2261)_)))
```
// Here's some code anyone can copy and paste to reproduce your issue
	        static int nRotate = 0;
		ImGui::InputInt("roate", &nRotate);
		ImTextureID my_tex_id = m_pViewModel->m_EditorDisplayViewModel->getEditorViewTextureID();
		if (nRotate == 0)
		{
			ImGui::Image(my_tex_id, canvas_size);
		}
		else if (nRotate == 1)
		{
			ImGui::Image(my_tex_id, canvas_size, ImVec2(0,1), ImVec2(1,0));
		}
		else if (nRotate == 2)
		{
			ImGui::Image(my_tex_id, canvas_size, ImVec2(1,1), ImVec2(0,0));
		}
		else if (nRotate == 3)
		{
			ImGui::Image(my_tex_id, canvas_size, ImVec2(1,0), ImVec2(0,1));
		}
```

**Comment by ocornut** [comment]
Hello,
Behavior is correct and as expected. Those values are UV coordinates (see https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#About-texture-coordinates). If you want to rotate an image you'd need to alter the 4 end points of the polygons, not the UV coordinates. (UV coordinates will allow you to "flip" the image"). You can use `draw_list->AddImageQuad()` for this..

See
https://github.com/ocornut/imgui/issues/1982#issuecomment-408834301

Please post further question in #1982 if needed. Thank you!
