### ISSUE TITLE
Navigating InputText with arrows inserts question marks with Allegro 5 backend

### ISSUE THREAD

**Issue by 60rntogo** [ocornut/imgui#3268]
Version: 1.77 WIP (17601)
Branch: master
Back-ends: imgui_impl_allegro5.cpp
Compiler: GCC 9.3.0
Operating System: Ubuntu 20.04

When I navigate an InputText box by pressing left and right arrow keys each key press inserts a question mark character into the box. The problem can be reproduced in the "Dear ImGui Demo" window in the application from example_allegro5 directory compiled with no modifications. For comparison I checked the demo with GLFW/OpenGL3 back-end and the problem doesn't occur so it seems it is a problem with the Allegro back-end.

**Comment by ocornut** [comment]
Hello,
Was this recent change already merged in your version?
https://github.com/ocornut/imgui/pull/3252

**Comment by 60rntogo** [comment]
I have just pulled the newest version and the problem is fixed indeed. Sorry for not checking first.

**Comment by ocornut** [comment]
Would rather hear that a problem is fixed than us having another to fix ;)
Closing now.
