### ISSUE TITLE
Configurable font texture atlas width

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#327]
I am generating pretty large font texture atlas (as I'm rendering icon fonts as you may know ;) but I have found problem when width or height of any texture is anything above 4096 on some hardware.
Debugging the code I've found those lines of code fixing width to 512.

```cpp
bool    ImFontAtlas::Build()
{
   //...
    // Start packing
    TexWidth = (total_glyph_count > 1000) ? 1024 : 512;  // Width doesn't actually matters.
```

Hardware I am targeting has no problems with 2048 or even 4096 wide textures and this of course would cause the texture height to be smaller.
I'm manually changing those constants but I think that this can be a good candidate to be user configurable.

**Comment by ocornut** [comment]
Could reuse those existing fields (with default=0) but only if I change ClearTexData() to reset them to zero, not sure that's desirable. I think I'll had another set of fields.

**Comment by ocornut** [comment]
It may result in Build() falling which it never did until know, so I would need to look into the effect of failing to pack here.

**Comment by ocornut** [comment]
How many glyphs do you have, out of curiosity ?

**Comment by ocornut** [comment]
I am a little uncomfortable with that because it would mean the user has to provide a value that they can't really calculate / they have to derive it from guess/data and if you start changing your font settings that's one thing to maintain.

**Comment by Pagghiu** [comment]
I have 794 glyphs, because I'm rendering font awesome entirely (I could select only the glyphs I'm using that are probably less than 100). The problem is that those icons take a lot more space than characters (they're rendered at bigger size) and then you have retina / oversampling that can further increase memory usage.
TexDesiredWidth should do the job in my opinion.

**Comment by ocornut** [comment]
Ok let's say this is done. When we get around to rewrite the atlas system to be completely dynamic we may remove it.

**Comment by ocornut** [comment]
FYI as of 1.92 `TexDesiredWidth` was removed but setting `TexMinWidth == TexMaxWidth` allows for the same thing.
It's also generally unnecessary nowadays as glyphs are packed and repacked on demand.
