### ISSUE TITLE
Providing (-1, -1) for size_min or size_max alone in SetNextWindowSizeConstraints has no effect.

### ISSUE THREAD

**Issue by trss** [ocornut/imgui#3270]
From the documentation below, the obvious thing to do is to provide `(-1, -1)` for `size_max` if one wants to provide `size_min` alone. But this results in `size_min` not being honored.
https://github.com/ocornut/imgui/blob/3f26a07ee1813cecaa87253436149e28fc11dc4e/imgui.h#L307

The code below makes it clear why it behaves this way and the fix looks simple.
https://github.com/ocornut/imgui/blob/3f26a07ee1813cecaa87253436149e28fc11dc4e/imgui.cpp#L4946-L4947

Of course, it's always possible to provide `FLT_MAX/INT_MAX`. But that took a long while for me to figure out.

If this is the intended behavior, I feel that the documentation could be made clearer.

**Comment by ocornut** [comment]
Hello,
It seems like this has already been reported and there's a pull request here: #3186

**Comment by trss** [comment]
Somehow missed that, my bad.

**Comment by ocornut** [comment]
No worries! I'll close this and will aim to look at and merge #3186 soonish.

**Comment by ocornut** [comment]
See #3186 for an update. Our comments/docs were misleading, you can use 0.0f and FLT_MAX if you want no constraint on one bound. The suggested change (here and in #3186) are not correct afaik.
