### ISSUE TITLE
BulletText and wrapping ?

### ISSUE THREAD

**Issue by DaveInDev** [ocornut/imgui#3273]
Version: Dear ImGui 1.77 WIP (17601)
Branch: master
Back-ends: SFML
Compiler: VS2019 c++
Operating System: win10x64

Hi,

it seems that ImGui::PushTextWrapPos is working with some Text widgets (at least Classic and Colored) , but not with **BulletText**. 
Is it intended, or maybe am I missing something ?
Is there a way to wrap such a widget at the end of the window ?

**Comment by ocornut** [comment]
That's right. You'd need to implement a custom function calling e.g. `Bullet()` + `TextUnformatted()`.
While it would be easy to replace `BulletText()` to internally call `RenderTextWrapped()` instead of `RenderText()`, that would make it's behavior inconsistent with other widgets so I am not sure it is a wise design choice currently.

**Comment by DaveInDev** [comment]
Thanks @ocornut , I did not notice this simple Bullet() function : it's exactly what I need to do the trick.

**Comment by pegvin** [comment]
I faced something similar, and not sure how efficient my solution is, but sharing it here for someone to use:

```c++
#define TEXT_BULLET(bullet, text) ImGui::TextWrapped(bullet); ImGui::SameLine(); ImGui::TextWrapped(text);

ImGui::Begin("Test");
ImGui::TextWrapped("This is wrapping list:");
ImGui::Indent();
	TEXT_BULLET("1.", "Item 1");
	TEXT_BULLET("2.", "Item 2");
	TEXT_BULLET("3.", "Item 3");
	ImGui::Indent();
		TEXT_BULLET("-", "Oh Look This is a sub-item");
	ImGui::Unindent();
	TEXT_BULLET("$", "Oh look this is not a sub-item");
ImGui::Unindent();
ImGui::TextWrapped("List has ended");
ImGui::End();

#undef TEXT_BULLET
```

Output is this:

https://github.com/ocornut/imgui/assets/75035219/44247d79-5307-42f2-8a5f-a3b2192e186a
