### ISSUE TITLE
float overflow on MacOS when double clicking

### ISSUE THREAD

**Issue by NKTomHaygarth** [ocornut/imgui#3276]
**Version/Branch of Dear ImGui:**

Version: 1.77
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: custom
Compiler: apple-clang
Operating System: MacOS

**My Issue/Question:**

When running my application with the undefined behaviour sanitiser enabled a float overflow is detected in the code when checking for double clicks (below). I believe this is caused by the setting of `MouseClickedTime` to `-DBL_MAX`

```
if ((float)(g.Time - g.IO.MouseClickedTime[i]) < g.IO.MouseDoubleClickTime)
{
    ImVec2 delta_from_click_pos = IsMousePosValid(&g.IO.MousePos) ? (g.IO.MousePos - g.IO.MouseClickedPos[i]) : ImVec2(0.0f, 0.0f);
    if (ImLengthSqr(delta_from_click_pos) < g.IO.MouseDoubleClickMaxDist * g.IO.MouseDoubleClickMaxDist)
        g.IO.MouseDoubleClicked[i] = true;
    g.IO.MouseClickedTime[i] = -DBL_MAX;    // so the third click isn't turned into a double-click
}
```

Can `g.IO.MouseClickedTime[I]` be reset to 0.0 instead of `-DBL_MAX`?

**Comment by NKTomHaygarth** [comment]
Hey, thanks for the response.

> No, because that would trigger a double-click if a first click is done on context start

That makes sense. Setting `g.IO.MouseClickedTime[i] = -g.IO.MouseDoubleClickTime * 2.0f;` does indeed fix the issue.

Cheers!

**Comment by ocornut** [comment]
Merged, thank you!
(will probably minor conflict with #3229)
