### ISSUE TITLE
Centering text inside InputText widget

### ISSUE THREAD

**Issue by moobsmc** [ocornut/imgui#3277]
Hi! I've been trying to look for a solution around this but i can't seem to find any documentation or any flags inside the actual code that allows this which leads me to this issue. Im curious if you/anybody can point me in the right direction to achieve what i'm looking for.

![Matador_ICSBIslBjX](https://user-images.githubusercontent.com/38496143/83450999-96101300-a456-11ea-841a-7bc60d64fd46.png)

So far what i've been trying is to modify the code inside the InputTextEx function and went off an older issue that revolved around right-aligning the text (which works when i implement it, but only after pressing enter)

https://github.com/ocornut/imgui/pull/1442/commits/af54bf6862362fd278d9a6c211a5dda53a1fb189

**Comment by ocornut** [comment]
Hello,
It's currently not easily possible to implement because support for multi-line text would require per-line centering which is currently not available in the low-level functions.
