### ISSUE TITLE
Can I have multiple Begin/End blocks for one window?

### ISSUE THREAD

**Issue by 60rntogo** [ocornut/imgui#3278]
I noticed that I can create multiple Begin/End blocks with the same id and their contents are concatenated together as if they were all in one block. Can I do that or should I always have only one block per window? If it is OK, should I pass the flags once or every time? When should I push/pop stack variables that affect the window?

I know that I can discover these behaviors by experimenting, but I would appreciate an official confirmation if this is reliable.

**Comment by ocornut** [comment]
>  Can I do that 

Yes, the comment on `Begin()` says 
```
    // - You may append multiple times to the same window during the same frame.
```
(going to clarify the wording) and the demo shows it.

You can pass the flag once, they need to be ignored the second time.

> When should I push/pop stack variables that affect the window?

Every-time they need to be used, with the exception of `WindowPadding`, `WindowRounding` `WindowBorderSize` which for technical reason need to be "locked" in the first `Begin()` call.

Appending in very reliable. Which style info are locked/latched in first `Begin()` is an implementation detail not currently strictly guaranteed by the API but I would say it is fairly safe.

**Comment by 60rntogo** [comment]
That's great, thanks. I read this comment but I didn't gather that it refers to multiple calls to `Begin` so it might be a good idea to rephrase it.

**Comment by ocornut** [comment]
Rephrased
````
// - You may append multiple times to the same window during the same frame.
```
into
// - You may append multiple times to the same window during the same frame by calling Begin()/End() pairs multiple times.
//   Some information such as 'flags' or 'p_open' will only be considered by the first call to Begin().
```
