### ISSUE TITLE
AddFont*TTF packs characters with wrong aspect ratio

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#328]
I don't know since when this was introduced but I see the atlas generated by ttf files to be wrong.

On the latest master opengl_example as reference

```cpp
//Default font should be proggyclean at 13
 io.Fonts->AddFontDefault()
```
![addfontok](https://cloud.githubusercontent.com/assets/5406873/9817033/d9fb4956-58a0-11e5-8f2d-a9df756820e5.jpg)

```cpp
io.Fonts->AddFontFromFileTTF("../../extra_fonts/ProggyClean.ttf", 13.0f);
```
![addfontnotok](https://cloud.githubusercontent.com/assets/5406873/9817034/d9fc63d6-58a0-11e5-80c0-f1f9df2c1a93.jpg)

Am I missing something that has changed in font handling with oversampling or is this a bug?

**Comment by ocornut** [comment]
io.Fonts->AddFontDefault() disable oversampling because it doesn't make sense for that sort of font, whereas it is on by default for AddFontFromFileTTF() which seemed sensible.

**Comment by Pagghiu** [comment]
I see, OversampleH default is 3 and Oversample V is 1.
So everything is as expected, I'm sorry, we can probably close this one ;-)

**Comment by ocornut** [comment]
I'll add extra comments and perhaps helpers. I'm not too happy with how ImFontConfig can be declared.
