### ISSUE TITLE
Capitalization of "Dear"

### ISSUE THREAD

**Issue by drdoofensmirch** [ocornut/imgui#3280]
dear is uncapitalised in the title, but is in the read me file, :| it could cause problems if you want to make it the official name but reffered to differently in the read me

**Comment by ocornut** [comment]
Whole title is in lower-case at the top of the readme/page, which indeed is inconsistent with how it is written anywhere else. I don't think it's a problem but I may change it at some point.

**Comment by drdoofensmirch** [comment]
Oh thx i was just a bit concerned

**Comment by ocornut** [comment]
Changed it in the readme.
