### ISSUE TITLE
About the size of ImGui components

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3284]
Hello, everyone.
Sorry for taking everyone's time。
Because I would like to ask questions about how to control the size of the Dear Imgui component。
I know that in the "imgui.ini" file you can control the starting position and size of the window, or control whether the window is collapsed.
like this
![image](https://user-images.githubusercontent.com/55690445/83828313-e9ae8500-a712-11ea-9104-c3f427aa8fcf.png)
Excuse me, is there any corresponding interface in Dear Imgui to set the size of the component, I only found one: SetNextItemWidth() can set the next width, so how should I set the height of the next component?

**Comment by YuDang1024** [comment]
I found an interface that seems to solve the problem:
ImGuiStyle:ScaleAllSizes
But after using it, the window can not be drawn, maybe the way I added it is wrong?
I will update my progress in solving the problem, if you have a better solution, you can leave a message to tell me

**Comment by ocornut** [comment]
> Excuse me, is there any corresponding interface in Dear Imgui to set the size of the component, I only found one: SetNextItemWidth() can set the next width, so how should I set the height of the next component?

Some component such as `Button()` or `Selectable()` have explicit size overrides in their paragram.

Most components have their size derived from the size of size of the text + FramePadding, e.g. the height of a button is typically `FontSize + style.FramePadding.y * 2.0f`.

See Style Editor to understand how size affect widgets.
