### ISSUE TITLE
C++ Run Library Failed

### ISSUE THREAD

**Issue by anyeyongheng520** [ocornut/imgui#3289]
![W6}S~JE872}ZMIUCH4 WV7D](https://user-images.githubusercontent.com/66551992/83965366-d30c5780-a8e5-11ea-8153-8435012dd9e6.png)

how to solve?

**Comment by anyeyongheng520** [comment]
I run in debug mode

**Comment by rokups** [comment]
Please read error message and examples.

**Comment by ocornut** [comment]
Also read
https://github.com/ocornut/imgui/wiki/Loading-Font-Example#about-filenames

And
https://github.com/ocornut/imgui/blob/master/docs/FONTS.txt

Please ask for http://discord.dearimgui.org for more questions.
