### ISSUE TITLE
Drawing to a Movable Viewport

### ISSUE THREAD

**Issue by Zuppka** [ocornut/imgui#329]
I've been using ImGui for a bit for a small project I'm working on and so far it's solved a lot more issues that it created and I'm rather satisfied with the functionality! However I'm encountering a programming roadblock now and was wondering if I'd still be able to do what I want using ImGui.

I have a render area larger than the window resolution, where the program window acts as a viewport. So for example a 1000x1000 render area where only a 200x200 area is visible in the window at one time. I would like to have ImGui windows move around with the viewport, so their position in the viewport is always the same.

The problem I encounter is that once I move the viewport out to a location greater than the viewport size, the UI visually remains correctly in position, but the "clickable" area gets shifted over and no longer aligns with the ImGui elements as you can see here: 
![spanishinfantilehadrosaurus](https://cloud.githubusercontent.com/assets/223192/9824361/3e0a73ba-589a-11e5-9f82-a44bf00b1e36.gif)

Is there something I could just be overlooking that can easily fix this issue? Is there a way to move the "clickable" area directly?

My current implementation is a little messy (I'm using SFML) so I'm also concerned this may be an issue of implementation instead. Let me know if further clarification is needed. Any advice is greatly appreciated!

**Comment by ocornut** [comment]
I'm not sure to understand what you mean by "moving the viewport".

What you would do in this case I think is set DisplaySize to 1000x1000 and then adjust DisplayVisibleMin/DisplayVisibleMax to the visible portion. The output render will be the DisplayVisibleMin..DisplayVisibleMax range and you can shift your projection matrix to max DisplayVisibleMin to the corner of your 200x200 window.

Let me know if that makes sense.

**Comment by Zuppka** [comment]
I'm not quite sure what you mean by "..you can shift your projection matrix to max DisplayVisibleMin..", but I tried to play around with updating DisplayVisibleMin as the top left and DisplayVisibleMax as bottom right of a rectangle representing the window resolution. I didn't notice any difference in results.

Perhaps this could clarify better:
https://gfycat.com/PlayfulSpicyFox
![playfulspicyfox](https://cloud.githubusercontent.com/assets/223192/9826562/4eddf72a-58a9-11e5-9700-902c5a976e52.gif)

The window resolution here is 640x480 (bottom cropped out since nothing interesting happens there) while the render area (DisplaySize) is 1536x1024. I made the buttons highlight in orange, and you can see the first mouse over they all highlight correctly. 

As I move the the right, the "viewport" moves across from zero to DisplaySize.x, maintaining the 640x480 window size. Although I keep the mouse stationary, different buttons are highlighted as I move across. The ImGui window remains stationary (as intended), but the location of the highlight area of the buttons appear to move relative to the GUI and no longer line up.

Hope this clears it up a bit, and thanks for the quick assistance!

**Comment by ocornut** [comment]
I don't understand why you need a DisplaySize so big. Which ImGui components are being displayed? Are the green blocks and red arrows imGui component? If you don't different regions scrolling differently use different windows, this is what windows are for.

You can start a window with Begin() or child window BeginChild(), then use scrolling functions or use SetCursorPos() to offset everything. e.g. SetScrollX(-100).

**Comment by Zuppka** [comment]
The only ImGui component in that animation is the bar on top, it's a narrow horizontal window with ImGui buttons.

The blocks and main window are drawn with another library. I'll look into the scrolling functions but would they work only on elements within an ImGui window or on windows themselves?

Thanks!

**Comment by ocornut** [comment]
OK so you don't need to extend the imgui display or do anything fancy. Your first message what misleading. Based on the first animation you are either just passing incorrect mouse coordinate to ImGui, either not rendering ImGui with the correct projection matrix that a 1:1 map to the screen.
