### ISSUE TITLE
Adding button in tab bars

### ISSUE THREAD

**Issue by rjx-ray** [ocornut/imgui#3291]
I am using a "+"  button after a reorderable tab bar to add a new tab.
![image](https://user-images.githubusercontent.com/24891831/84030419-effb6600-a98b-11ea-896c-24bf7bb6001e.png)

if I move the last tab the button's position moves to after the moved tab instead of after the tab bar
![image](https://user-images.githubusercontent.com/24891831/84030575-33ee6b00-a98c-11ea-9f04-8a81c16ff0f7.png)

I'm using ImGui 1.75 included with https://github.com/jvcleave/ofxImGui

Here's the code outline - a tab is class which has a name variable and I keep the tabs in a C++ vector
`	

    ImGuiTabBarFlags tab_bar_flags = ImGuiTabBarFlags_AutoSelectNewTabs | ImGuiTabBarFlags_Reorderable;
    if (ImGui::BeginTabBar("MyTabBar", tab_bar_flags)) {
        for (auto tab : tabs) {
            string name = tab->name;
            if (ImGui::BeginTabItem(name.c_str())) { 
                // switch to the newly selected tab
                ImGui::EndTabItem();
            }
        }
        ImGui::EndTabBar();
    }
    ImGui::SameLine();
    if (ImGui::Button("+")) {
        // create the new tab and push_back
    }
`

**Comment by ocornut** [comment]
Hello Richard,

I thought we could modify `EndTabBar()` to set the "last item" information for layout, but this usage pattern would break if the tabs shrinking down or scrolling, so I remember why I explicitly didn't make that change in `EndTabBar()`.

I think instead we should add specific `ImGuiTabItemFlags` flags to:
- disable reordering on a specific tab
- treat the tab as a button: it would not get selected and return true on click

This would allow implementing this behavior using a tab (and you can alter tab colors in the style if you want it to be red, etc).

**Comment by rjx-ray** [comment]
Hi Omar, thanks for the quick response. 
My + button is a separate  ImGui button, outside of the tab bar.
It seemed to me that its just the end point of the tab bar that was calculated wrong.
So I do want to be able to re-order the last tab. 

By the way, I had originally tried having a "+" tab after all the others.
I had to do special logic as the new tab wasn't selected until the following cycle so I ended up with two new tabs. 
Also I had the issue you describe that the new tab was placed after the "+" tab and the "+" tab then couldn't be re-ordered because any click on it creates a new tab.
So it seemed simpler to have a separate button

**Comment by rjx-ray** [comment]
I've managed to devise a workaround for this:

If I sort my tabs vector to be in the same order as the ImGui tabs display then the "+" button stays at the end after the last tabItem I call.
That also means that I can save the tab ordering between app invocations which is a requirement for me.

I did the sorting by getting the tabbar tab offsets and names and copying the offset into my tab class. Obviously I'm having to access ImGui internals for this which is not ideal. Also I'm having to sort on every cycle as I don't know when the ordering is changed

But for now its working OK for me.

**Comment by ocornut** [comment]
Hello Richard,
We are currently working on a proper solution for this.

**Comment by rjx-ray** [comment]
Fantastic! 
It would be great if you could also include some method of notifying a change of ordering and getting the results
Thanks

**Comment by ocornut** [comment]
You should not need to get a notification of change of ordering.
I'd rather work on allowing to preserve that order.

**Comment by rjx-ray** [comment]
Could it be preserved between app invocations?

**Comment by ocornut** [comment]
Well yes that's what we should aim for, but notice it is awkward to
preserve order without preserving visibility, and visibility is tied to
your code flow, so it's not easy to make something useful out of only
preserving order. Anyway this is another topic. If you want to manually
save order you can currently query structures in imgui_internal.h, but we
won't attempt to provide mid-way public API for this.

**Comment by rjx-ray** [comment]
OK, I understand, thanks for all the great stuff you do.

**Comment by rjx-ray** [comment]
Would it be possible to add a favicon to tab - maybe as a optional parameter to BeginTabItem?

**Comment by ocornut** [comment]
Use fonts icons as described in the docs. Let’s focus on one issue if you have more questions about this please ask on Discord or open a separate issue, thank you!

**Comment by ocornut** [comment]
This now has been implemented (it was surprisingly _lots_ of work to get it right, done mostly by @Xipiryon, lots of corner cases, resizing/scrolling policy issues)

You can now use `TabItemButton()` + `ImGuiTabItemFlags_Leading`, `ImGuiTabItemFlags_Trailing` flags.
See Demo > Layouts > Tabs for details.

Regular tabs can also be trailing/leading.

![image](https://user-images.githubusercontent.com/8225057/93906189-3044e100-fcfc-11ea-8140-e8a41865b824.png)

The next thing in line is to allow to appends tab using multiple `BeginTabBar()`/`EndTabBar()` which would make it possible to add custom buttons into docking nodes created by the docking system.

**Comment by ocornut** [comment]
Appending to tab bar has been added a bit ago by the way, so closing this as all done.
