### ISSUE TITLE
Making a transparent ImGui window

### ISSUE THREAD

**Issue by UsamaK98** [ocornut/imgui#3292]
Version: 1.76
Branch:master

Back-ends: imgui_impl_glut.cpp + imgui_impl_opengl2.cpp _
Compiler: g++
Operating System: Ubuntu 20

**My Issue/Question:**

Hi, I'm working on a semester project where I have to create a game similar to bejeweled. We had been provided with a skeleton code based on freeglut. Goals of the project were to create a match-3 game with 2 modes and several levels. Also I had to  3 menus; Main menu, Pause menu, Level selection menu. Now I have a background image for each of my menus, and i created a texture binding class to bind and render my backgrounds and my gems, however; I want to create a seamless window using ImGui that is partially or fully transparent so that i can create buttons on that window that might look as they are rendered on top of the background.

Additionally, I couldnt find any tutorial/instructions regarding how to create a drop down menu bar usually found at the top of a window.

**Comment by PossiblyAShrub** [comment]
> seamless window using ImGui that is partially or fully transparent

Try setting window flags when you call `ImGui::Begin()`
```C++
ImGuiWindowFlags window_flags = 0;
window_flags |= ImGuiWindowFlags_NoBackground;
window_flags |= ImGuiWindowFlags_NoTitleBar;
// etc.
```
Here's a before/after 
![Capture](https://user-images.githubusercontent.com/46799759/84101808-af1f4380-a9c3-11ea-9214-a5266f124189.JPG)

 *--- A great place to look for examples on almost all ImGui features is the demo window ---*

> Additionally, I couldn't find any tutorial/instructions regarding how to create a drop-down menu bar usually found at the top of a window.

Try looking at `ImGui::BeginMenuBar()`
If you do a find/replace for 'BeginMenuBar(),' in the `imgui_demo.cpp` file. You will find a nice example of the menu bar in action.

**Comment by ocornut** [comment]
Closing as answered thank you @PossiblyAShrub
