### ISSUE TITLE
Changing PopupBG Text Colors

### ISSUE THREAD

**Issue by MustafaDaPro** [ocornut/imgui#3298]
Hello, while I was designing my menu today I found that my white text + white popupbg is unreadable.  I want to do 2 things:
 - Change the popup text to black without globally changing it throughout my menu
- Add an option to change text color while hovered (ImGuiCol_PopupTextHovered = etc)
Anyone know how to do this? I'd appreciate some help.

Edit: I have something like this in mind: https://prnt.sc/sz5h5x

**Comment by rokups** [comment]
Use `PushStyleColor()` / `PopStyleColor()` around code sections you want to modify. Push appropriate color based on based on whether last item is hovered. Something like:

```cpp
PushStyleColor(ImGuiCol_Text, _wasHoveredLastFrame ? col_hover : col_normal);
Text("Popup content");
_wasHoveredLastFrame = IsItemHovered();
PopStyleColor();
```

**Comment by ocornut** [comment]
Sorry but #1586.
