### ISSUE TITLE
Console which does auto-scroll

### ISSUE THREAD

**Issue by GkqqNkKC** [ocornut/imgui#3299]
The example found in the demo shows a console which allows auto-scroll only by clicking a checkbox. Most consoles nowdays scrolls automatically to the bottom if the current scroll is already at the bottom. This means that if I scroll a bit up, the console would remain on the same line even if new lines / text is pushed at the bottom. Though, if I'm at the bottom, when new lines are pushed, the scroll will jump automatically at the end

This is a good behavior because the user can see what's happening in real-time, and if he sees something he wanna take a deeper look into, he can scroll a bit up in order to lock the scroll and have longer time to read. Note that this behavior does not require any checkmark from the user

I think it would be a nice feature. If it does not sound too "important", at least what is a good way to replicate the behavior mentioned earlier? I tried some stuff that I decided to discard since it was too messy

**Comment by ocornut** [comment]
Unless you are using an old version (PS: you didn't fill the requested issue template), this is already what the demo does. 

Code in e.g. `ExampleAppLog` does:
```
if (AutoScroll && ImGui::GetScrollY() >= ImGui::GetScrollMaxY())
    ImGui::SetScrollHereY(1.0f);
```

And `Autoscroll` is buried in an Option menu and there as a didactic/documenting feature, but it would be fine to not expose the Checkbox at all in an application.

**Comment by GkqqNkKC** [comment]
Thx for helping. `Autoscroll` is confusing to be `false` when the checkbox is enabled and vice-versa, but clearly somehow I wasn't too focussed when I read the demo code. Sry for not filling the issue template, gonna make sure it is there next time
