### ISSUE TITLE
IsMouseHoveringRect returns false when rect overlaps inclusively

### ISSUE THREAD

**Issue by vlmillet** [ocornut/imgui#3301]
Hello, 
`ImGui::IsMouseHoveringRect(ImVec2(0, 0), ImVec2(ImGui::GetIO().DisplaySize.x, 24))`
always returns `false `where I expect it to return `true` on top 24 pixels margin of the main window. 
I've seen that the `Overlaps` test in `ImRect` is not left-left/right-right/... inclusive, is it wanted ?
Or a `|| g.MouseViewport->GetMainRect().Contains(...)` is missing in `IsMouseHoveringRect` 
Or I'm really tired and I don't see what goes wrong..

(In my case I can do `MousePos.y < 24` test but I found the bug (?) before thinking of that)

**Comment by ocornut** [comment]
Moving to #3976
