### ISSUE TITLE
Vertical Scroll Glitch

### ISSUE THREAD

**Issue by Andrey763** [ocornut/imgui#3302]
![ezgif-3-002d5fafff91](https://user-images.githubusercontent.com/66968579/84691902-a1326b00-af4d-11ea-853f-7f4bc815c28c.gif)
How Can I Fix Scroll Bar Glitch?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
Closing.
