### ISSUE TITLE
Font / Images Strange Transparency Issue

### ISSUE THREAD

**Issue by rk85097** [ocornut/imgui#3303]
Hi, 

Did anyone bump into this type of issue? Some of my app users claim to have the font look strange as in the attached screenshot, I suspect it has to do with some transparency issue. 

I tried to understand what is "special" about these users, but could not find a common factor.
This issue seems to happen also on images, where transparent image (png) background is white instead of being transparent.

Version: dear imgui, v1.77 WIP
Back-end: OpenGL

```
string fontsPath = PathStore().fonts();
string main = fontsPath + "DejaVuSans.ttf";
string bold = fontsPath + "DejaVuSans-Bold.ttf";
ImGuiIO& io = ImGui::GetIO();
regularFont = io.Fonts->AddFontFromFileTTF(main.c_str(), 17.0f);
boldFont = io.Fonts->AddFontFromFileTTF(bold.c_str(), 17.0f);
```

Any ideas?

<img width="351" alt="Screen Shot 2020-06-15 at 23 33 54" src="https://user-images.githubusercontent.com/5455346/84703363-cd0b1c00-af60-11ea-9a10-df13bc9e32c4.png">

**Comment by ocornut** [comment]
Most likely your texture hasn't been uploaded to GPU, maybe because it is too big for the GPU (I don't know how you setup your fonts but see https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#font-loading-instructions)

**Please do fill the requested issue template when opening an issue.** We don't know which version or back-ends you are using and how they would react to failed texture upload. Issues are closed or users are often blocked for not fulfilling guidelines.

**Comment by rk85097** [comment]
> Most likely your texture hasn't been uploaded to GPU, maybe because it is too big for the GPU (I don't know how you setup your fonts but see https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#font-loading-instructions there's a paragraph describing what you get)
> 
> **Please do fill the requested issue template when opening an issue.** We don't know which version or back-ends you are using and how they would react to failed texture upload. Issues are closed or users are often blocked for not fulfilling guidelines.

Thanks, I have updated my question.

My code is following the font initialization requirements. 
Any help - ideas to how to better investigate this - would be appreciated.

**Comment by ocornut** [comment]
> I suspect they run another app that uses IMGUI at the same time - will that cause such issue?

No it shouldn't.

Things I can think of:
- Font texture is too large for their GPU/driver (unlikely if you are only loading those 2 fonts at size 17.0f, with ascii glyph range).
- Your app is also using OpenGL in a way that somehow alter state and break the back-end. (Note that even in your edit you didn't specify which back-end you are using, they are two OpenGL back-ends, and maybe OpenGL versions supported). Does your app does _anything_ with OpenGL? Try to get those users one of the Dear ImGui compiled demo (unmodified) and see if they also run into that issue.

**Comment by ocornut** [comment]
Closing this. Please don't hesitate to post if you find more information about your issute.
I've also updated the FAQ to include this common issue in it:

https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-i-integrated-dear-imgui-in-my-engine-and-little-squares-are-showing-instead-of-text
