### ISSUE TITLE
Can't delete window pointer in memory

### ISSUE THREAD

**Issue by Barashuk** [ocornut/imgui#3304]
How can I remove a window from the memory of an imgui?
```
ImGuiWindow* window = FindWindowByName(u8"Test name##_name");

//some my not imgui code
if (!window->Active && misc->iCursorMode) {
            misc->ToggleCursor(false);
            auto windowsByID = GetCurrentContext()->WindowsById;
            auto windows = GetCurrentContext()->Windows;
            windows.erase(&window, windows.end());
            windowsByID.Data.erase((ImGuiStorage::ImGuiStoragePair*) & window, windowsByID.Data.end());  
        }
Log("win pointer: %p", window);
```
A non-null pointer to the window in the last line is written to the log

**Comment by ocornut** [comment]
You cannot and you should not have to. Why are you trying to do this?

**Please do fill the requested issue template when opening an issue. **

**Comment by Barashuk** [comment]
I want to make the cursor automatically disappear through the button when closing the window. In general, I succeeded, but at some points in the program’s work it turns out that the cursor closes even when I don’t need it. Also, if "FindWindowByName" returns a null pointer, then everything will work as I need, therefore I decided to delete it. I will tell the complete information on the use of the Imgui version in the evening.

**Comment by ocornut** [comment]
> I want to make the cursor automatically disappear through the button when closing the window. 

I don't understand this. Please clarify. You can discuss it in discord.dearimgui.org
But you should not need to "delete any window".

**Comment by ocornut** [comment]
@Barashuk I am closing this as you are not providing sufficient information. You should not, never, attempt to delete `ImGuiWindow` instances. If there's something you'd like to achieve please discuss it on the discord and open an issue if there's a concensus that opening an issue is the right thing to do.
