### ISSUE TITLE
centering a multiline string

### ISSUE THREAD

**Issue by himanaiza** [ocornut/imgui#3305]
I can't figure out how to insert a multi-line string, so that each new line is centred, if possible, I would like to see an example, I searched for it and found it with large strings.
With a small string length, it turns out, but if the string is already more than the width of the element where I want to insert it, it turns out not the same. 
By default it splits it itself as I need it but the alignment is on the left

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
