### ISSUE TITLE
Vulkan glfw port help

### ISSUE THREAD

**Issue by gviznyuk** [ocornut/imgui#3307]
I'm using a java port of imgui along side with vulkan (port with lwjgl).  I have integrated the vulkan glfw version of imgui, yet I'm getting this magic picture:

![Screenshot from 2020-06-17 22-41-09](https://user-images.githubusercontent.com/37628526/84972516-02447500-b0ed-11ea-9138-67248cddd8ea.png)

Any help will be greatly appreciated.

**Comment by ocornut** [comment]
I think you ought to be asking on lwjgl communities or in the Issue tracker of that java port of dear imgui. This is a likely application error and is too far from the concern to this repository (dear imgui C++ library).
