### ISSUE TITLE
Cannot close TreeNode if you leave the InputText label empty

### ISSUE THREAD

**Issue by xAl0n3** [ocornut/imgui#3310]
**Version:**
Version: 1.76 WIP

**Back-end/Renderer/Compiler/OS:**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Compiler: Visual Studio 2019
Operating System: Windows 10 1909

**My Issue/Question:**

When you leave the InputText title empty, you can't close the TreeNode where it is in

**Code:**
`ImGui::InputTextWithHint("", "< Chat input >", buf, sizeof buf);`

**The issue is related to:**
https://github.com/ocornut/imgui/blob/99f68d79581deef58d1edc5d07a92ad7806cabd6/imgui_widgets.cpp#L3183

**Screenshot/Video:**
https://i.imgur.com/lvQggD5.gifv

**Comment by ocornut** [comment]
Please read the FAQ.
