### ISSUE TITLE
Polish chars in InputText! Not work! Help me!

### ISSUE THREAD

**Issue by Gildin213** [ocornut/imgui#3313]
> Sorry for my bad English

Hi, I have a problem with Polish characters in ImGui!
Although I have a range of Polish characters 
`const ImWchar* ImFontAtlas::Polski()
{
	static const ImWchar ranges[] =
	{0x0020, 0x00FF,0x0100, 0x017F,0};
	return &ranges[0]; 
}`
File encoding set to 650001 without signature!
Font = c:\\Windows\\Fonts\\Arial.ttf

effect = https://prnt.sc/t521ah

What do I have to do to get these characters?
Displaying them works correctly! But typing these characters no longer works as I would like!

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Read FAQ, read FONTS documentation, and please ask on Discord.
Closing.

**Comment by ocornut** [comment]
FYI 1.92 (#8465) will make glyph loading automatic, so no need to specify glyph ranges.
