### ISSUE TITLE
About io.WantCaptureMouse flag is invalid on Android platform

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3315]
I use Dear ImGui as the display of the UI interface on the Android platform.
There are two parts in the application: the first is the UI, which provides players with buttons to operate the game; the second is the game scene, which is used to display the game model
I want to use it when processing screen messages:
`if (io.WantCaptureMouse)
{  Send the message to ImGui for processing  }`
But unfortunately, when I first entered the application, I clicked on the game scene (at this time did not click on the interface of Dream ImGui), the judgment was still successful.
For mobile platforms, or on screen touch-based platforms, can this "io.WantCaptureMouse" flag be used as a standard for message distribution?
Or is there something wrong with my method of use?
thank you very much~~

**Comment by ocornut** [comment]
`if (io.WantCaptureMouse) { Send the message to ImGui for processing }`

You are misunderstanding the purpose and behavior of `io.WantCaptureMouse`. 
All inputs messages need to be sent to Dear ImGui.
When `io.WantCaptureMouse == false`, don't send the message to your main app.
Please read the FAQ and examples application.
Everything works in Android.
