### ISSUE TITLE
how to make a DLL for a Other Gui Program

### ISSUE THREAD

**Issue by yezilaoda** [ocornut/imgui#3319]
I have a large win32api Gui Program.
I want add a imgui popupwindow into it
how to do

**Comment by PossiblyAShrub** [comment]
I'm sorry but we cannot help you with so little info. Please refer to the post/issue How to Open an Issue #2261, on how to properly provide all the info needed so we can help you. 

If you're confused as to how you can integrate dear imgui with your application, please take a look at the imgui_impl_xxx.cpp files in the "examples/" folder. Also, the imgui.cpp file contains tons of documentation and the imgui_demo.cpp file contains examples for almost every feature in dear imgui.
