### ISSUE TITLE
Not Able to Assign INFINITY or FLT_MAX to A Float Using DragFloat# or SliderFloat#

### ISSUE THREAD

**Issue by AkizukiRyoko** [ocornut/imgui#332]
I'm using DragFloat#s and SliderFloat#s to configure physical objects. When the mass of an object is set to INFINITY, it will be excluded from physics integration.
An initial configuration of infinity mass can be seen upon DragFloat and SliderFloat which displays 'inf' instead of a particular number. While as long as I edit it to a value, the little 'inf' will be gone forever and it is not possible to set it to 'inf' anymore since these widgets don't accept character inputs.
An exception is, it will work if I add a minus '-' in front of the 'inf'... So it seems we should be able to process the input properly.
Maybe we can make the widgets accept some specific chars such as 'i' to indicate an infinite value just as using '-' to indicate we are typing a negative value.

**Comment by ocornut** [comment]
Ryoko,
Allowing text input for infinity would probably need to be optional and require a float to those function. May I suggest adding a small button/checkbox just next to your Slider/Drag only for mass, to set the vaue to infinity instead?

![mass](https://cloud.githubusercontent.com/assets/8225057/9871046/cab74482-5b88-11e5-8342-ca4e35df228e.PNG)

**Comment by AkizukiRyoko** [comment]
Maybe this is not in great demand... Putting an extra button IS a workaround, indeed, but not perfect. We're manipulating floats, which means anything among decimal, infinities, even NaNs. Ignoring NaNs is fine since we are not really using it in game development. But for infinities, and for scientific notations (I've just found it not possible to type an e into it, neither...), there should be situations to make them useful.
Anyway, adding a button is fine, or even use scripting system. But I think our GUI system will be more complete if we can handle all possible values.

**Comment by ocornut** [comment]
You can (and probably should) wrap the options you want into a custom function.
Maybe replace the "inf" button by a popup where you can select the special values you want (and you can also have a "revert" option inside that menu).

For scientific notation or other form of inputs, you can use InputText() and just do the parsing yourself. You can filter the character yourself as well.

I'm not against adding more features but I don't know how to add those specific features considering they need to be optional.

**Comment by AkizukiRyoko** [comment]
Really helpful ideas. Thank you!
