### ISSUE TITLE
why the window imgui create can't hide?

### ISSUE THREAD

**Issue by hisupersylar** [ocornut/imgui#3320]
when  i create a imgui window,then i click the close button of the topright of the window,then the window i created  should hide,but it is not,why?someone can help me .
another strange thing is that when i show the demo window ( the call  ShowDemoWindow in  the  imgui_demo.cpp file ) in my project , i found that the demo window  didn't contain the close button. it is so Puzzling.

**Comment by rokups** [comment]
First and foremost - issue template is not for you to ignore, so please fill it out next time.

Close button is displayed only when `p_open` parameter is supplied to `Begin()`. In order to hide your window when closed you should stop calling `Begin()`/`End()` when `*p_open` is set to `false`.

**Comment by hisupersylar** [comment]
the first problem has been solved,  it is same as the problem at [https://github.com/jvcleave/ofxImGui/issues/40](url)

**Comment by hisupersylar** [comment]
https://github.com/jvcleave/ofxImGui/issues/40

**Comment by hisupersylar** [comment]
[https://github.com/jvcleave/ofxImGui/issues/40#issuecomment-226279464](url)  the  code help me.
