### ISSUE TITLE
Mouse is under the window

### ISSUE THREAD

**Issue by kaceros90** [ocornut/imgui#3322]
**Version/Branch of Dear ImGui:**

Version: dear imgui, v1.75 WIP
Branch: master
ImGui DirectX 11

**My Issue/Question:**
The mouse is under the window
Here's is screenshot: [Imgur](https://imgur.com/a/iKXO4Db)

**Comment by rokups** [comment]
You provide way too little information. However it does seem like your application renders software mouse cursor before it renders Dear ImGui drawlists. Fix rendering order in your application.
