### ISSUE TITLE
rendering  opengl output to a imgui window

### ISSUE THREAD

**Issue by hisupersylar** [ocornut/imgui#3324]
![image](https://user-images.githubusercontent.com/38312862/85951289-d353bc00-b994-11ea-925f-38ae34e34987.png)
as above, i ouput something to a imgui window.  my idea is render output to tex(use fbo)，then add the tex to a Image created in a
imgui window. it is not Completely correct. Is there some reason for this result?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template, for the second time.
Closing, blocked.
