### ISSUE TITLE
Slider coupling bug

### ISSUE THREAD

**Issue by atkurtul** [ocornut/imgui#3329]
Version: 1.77
Branch: master
Back-ends: imgui_impl_win32.cpp + imgui_impl_vulkan.cpp
Compiler: VS2019
Operating System: Windows 10

**My Issue/Question:**
When drawing scalar sliders one after another, sliding one changes the values of both as show in this [video.](https://www.youtube.com/watch?v=Sf2XfpP3S24&feature=youtu.be)

**Standalone, minimal, complete and verifiable example:** 
```
		ImGui_ImplWin32_NewFrame();
		ImGui::NewFrame();
		ImGui::Begin("window");
		ImGui::SliderInt("", &size[0], 100, 1920);	
		ImGui::SliderInt("", &size[1], 100, 1080);
		if (ImGui::Button("Resize"))
			r.win.Resize(size[0], size[1]);
		if (ImGui::Button("Load model")) r.LoadModelFromDialogBox();
		for (int i = 0; i < r.models.size(); ++i)
		{
			if (ImGui::Button(r.models[i]->path.c_str())) r.DeleteModel(r.models[i]);
			ImGui::SliderFloat4("pos", r.models[i]->xform.pos.xmm.f32, -10, 10);
		}
		DrawMat("view", cam.view);
		DrawMat("prj", cam.prj);
		ImGui::Separator();
		ImGui::InputFloat4("ray", cam.ray.xmm.f32);
		ImGui::End();
		ImGui::Render();
```

**Comment by ocornut** [comment]
Please read the FAQ.

**Comment by LineOfCodeboi** [comment]
I am also having this issue. Before stating "Read the FAQ" again, I'm quite new to this library, and after giving the FAQ a good read I still do not understand by what this is caused nor how to fix it. Could you please give me a little bit more information regarding either how to fix it or at which article to look?

Thank you in advance.

**Comment by PathogenDavid** [comment]
@LineOfCodeboi The sliders have an ID conflict and you need to disambiguate them. [Here's the relevant FAQ entry.](https://github.com/ocornut/imgui/blob/94b680e83052b9ff2e877360309020b72db057f2/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it)

**Comment by kevinalberts** [comment]
I don't want to bump but if you couldn't fix it, it's because of ImGui::SliderInt("" <--- this. You're using the same ID for 2 Sliders.
