### ISSUE TITLE
update vertex / index buffers takes too much time

### ISSUE THREAD

**Issue by coldgemini** [ocornut/imgui#3332]
is there a way to check if imgui widget is updated? 
currently I need to update vertex/index buffer each loop iteration even nothing is updating!

**Comment by ocornut** [comment]
You can use mechanism such as #2749 , many things are possible.

You didn’t fill issue template nor provided much details or actual measurements so I am going to close this now. While it does take time to “update vertex / index buffers”, a fair portion of users loosely claiming so haven’t done measurements and aren’t noticeably affected. If you don’t come up with more details I’ll have to assume you aren’t.
