### ISSUE TITLE
Issue when drawnig thick stroke / thick triangle

### ISSUE THREAD

**Issue by ruanwenfeng** [ocornut/imgui#3333]
**Version/Branch of Dear ImGui:**

Version: 1.76
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Windows 10

**My Issue/Question:**

Why do the sides of the triangle look strange？

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/27943586/86352553-8b84ab80-bc98-11ea-9d7b-c76aab457e8a.png)

**Standalone, minimal, complete and verifiable example:**
```
// Here's some code anyone can copy and paste to reproduce your issue
draw_list->AddTriangle({ 128,100 }, { 256,512 }, { 384,200 }, IM_COL32(255, 255, 255, 255), line_width);
draw_list->AddLine({ 100,100 }, { 228,512 }, IM_COL32(255, 255, 255, 255), line_width);
```

**Comment by ocornut** [comment]
Hello, there's a known issue with thick (>1.0f) stroked shapes, 
See #2183 and PR #2964, working on it.
Will close this as duplicate, but feel free to post more details/questions in those other threads if helpful.

Thank you!
