### ISSUE TITLE
Wrong colors, horizontal stripes, and corrupted text (Intel {Pentium G4400,Core i3-6100U}, onboard graphics)

### ISSUE THREAD

**Issue by vvanelslande** [ocornut/imgui#3334]
**Version/Branch of Dear ImGui:**

Version: 1.77
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp (SDL 2.0.12) + imgui_impl_opengl3.cpp (loader: glad 0.1.33)
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

Wrong colors, horizontal stripes, and corrupted text

**Screenshots/Video**

![](https://cdn.discordapp.com/attachments/692523028046676051/728334750762139648/Captura_de_pantalla_344.png)

**Standalone, minimal, complete and verifiable example:**
https://github.com/ocornut/imgui/tree/master/examples/example_sdl_opengl3

**Comment by domgho** [comment]
This looks similar to https://github.com/bkaradzic/bgfx/commit/7c24f1bc24df0050bfda935320f52c707799933c

Try adding the following OpenGL attributes:
```c++
SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, 1);
```

**Comment by vvanelslande** [comment]
@domgho that fixed it, thanks

**Comment by domgho** [comment]
Glad to hear that, could you please try adding the attributes one by one and tell me which is the one that fixed it (RGB, Alpha or accelerated visual)?

**Comment by vvanelslande** [comment]
everyone that has this issue is offline

**Comment by domgho** [comment]
I did more research and apparently this is a known issue in the recent Intel drivers and rolling back fixes it: https://community.intel.com/t5/Graphics/GREEN-LINES-ON-AFTER-EFFECTS/td-p/1188849

After updating to 27.20.100.8336 I can reproduce it and setting `SDL_GL_ALPHA_SIZE` to at least 3 bits fixes it.

**Comment by ocornut** [comment]
Closing as the bug seemingly has been fixed on Intel side according to the thread linked above.
Thank you @domgho for investigating this!

If we find that too many users have buggy drivers we may set those defaults in the SDL examples.
