### ISSUE TITLE
Problem with detecting pressed of "pause" button.

### ISSUE THREAD

**Issue by Landgraf132** [ocornut/imgui#3336]
Version: 1.78 wip 17702
Branch: master

Back-ends: imgui_impl_dx9 imgui_imp_win32
OS: Windows 7 SP 1
Compiler: MSC 1916 (Microsoft Visual Studio)
Renderer: DirectX 9
 
Hi everybody. I got a problem with detection of pressed "pause" button. Usually with press button go time counter, but not with "pause" button case. And I can't correctly detect of pressed this button. It's occurred and in default ImGui demo (example_win32_directx9). Can I fix it?  

I am press "pause" button.

![pause](https://user-images.githubusercontent.com/16545917/86534573-ff65c480-bee1-11ea-92b1-5979634b440b.gif)

I am press any button (example "space")

![correct](https://user-images.githubusercontent.com/16545917/86534612-3c31bb80-bee2-11ea-8b1d-84dbaa2ab0a8.gif)

**Comment by ocornut** [comment]
Hello,

I cannot seem to repro here, if I run example_win32_dx9/ and hold the PAUSE key of my keyboard it is seen as held.

With some printing added in imgui_impl_win32.cpp:
```
    case WM_KEYDOWN:
    case WM_SYSKEYDOWN:
        if (msg == WM_KEYDOWN)
            printf("WM_KEYDOWN %d\n", wParam);
        else
            printf("WM_SYSKEYDOWN %d\n", wParam);
        if (wParam < 256)
            io.KeysDown[wParam] = 1;
        return 0;
    case WM_KEYUP:
    case WM_SYSKEYUP:
        if (msg == WM_KEYUP)
            printf("WM_KEYUP %d\n", wParam);
        else
            printf("WM_SYSKEYUP %d\n", wParam);
        if (wParam < 256)
            io.KeysDown[wParam] = 0;
        return 0;
```
I get:
```
WM_KEYDOWN 19
WM_KEYDOWN 19
WM_KEYDOWN 19
WM_KEYUP 19
```

So I have no idea what may be leading to this behavior on your side, maybe something to do with a keyboard driver or tool interfering. Try adding the `printf()` statement to confirm that you are maybe getting the KEYUP message too early.

**Comment by Landgraf132** [comment]
I get:
```
WM_KEYDOWN 19
WM_KEYUP 19
WM_KEYDOWN 19
WM_KEYUP 19
```
I was try press this button with built-in windows keyboard and all work properly. I think this is not ImGui problem. Thank you.
