### ISSUE TITLE
Demo window drawing issue in Vulkan

### ISSUE THREAD

**Issue by SilverClawko** [ocornut/imgui#3337]
Version: 1.77
Branch: master

Back-ends: imgui_impl_vulkan.cpp
Compiler: Visual Studio 2017
Operating System: Windows 10 1809

i'm trying to add imgui in my demo vulkan project, and i follow the step in impl_vulkan. i got the demo window but it only show a part.  when click the menu, it show more.

https://imgur.com/86oZJke
https://imgur.com/6bF96Lj

I tried to compare my code with the example, it's seem the drawdate have wrong vtxcount and idxcount

my code :

ImGui::NewFrame();
ImGui::ShowDemoWindow();
ImGui::Render();

**Comment by ocornut** [comment]
Hello,
What happened there?
