### ISSUE TITLE
Crash: Index buffer out of bounds when drawing triangles

### ISSUE THREAD

**Issue by WEREMSOFT** [ocornut/imgui#3339]
**Version/Branch of Dear ImGui:**

Version: 1.76
Branch: master

**OpenGL3.0/Raylib/gcc/Linux**

Back-ends: I'm using RLGL, an openGL abstraction layer for raylib with the objective of creating an implementation for it.
Compiler: GCC 9.3.0
Operating System: Linux/Ubuntu

**My Issue/Question:**

I'm trying to create an implementation for the raylib game engine (raylib.com), this uses a custom abstraction layer for openGL called rlgl.

I managed to create the functions needed to make umgui run(using cimgui because raylib is writen in C). The problem is that under certain circumstances, the index buffers contain values out of bound with respect of the vertex buffer.

**Screenshots/Video**

This is the moment when the crash happens, you can see the variables on the left side.
![Screenshot from 2020-07-07 00-36-28](https://user-images.githubusercontent.com/808249/86661442-011baf00-bfec-11ea-9406-81143299dc71.png)

The issue happens when I roll over the "collapse" control (down arrow)on the "Dear Imgui demo" main window.

![Screenshot from 2020-07-07 00-36-43](https://user-images.githubusercontent.com/808249/86661997-9454e480-bfec-11ea-91b9-47f3545ddc59.png)

**Standalone, minimal, complete and verifiable example:** 

```
void raylib_render_draw_triangles(unsigned int count, const ImDrawIdx *idx_buffer, const ImDrawVert *idx_vert, unsigned int texture_id)
{
    // Draw the imgui triangle data
    rlPushMatrix();
    for (unsigned int i = 0; i < (count - 3); i += 3)
    {
        rlBegin(RL_TRIANGLES);
        rlEnableTexture(texture_id);

        ImDrawIdx index;
        ImDrawVert vertex;
        index = idx_buffer[i]; // idx_buffer contains a number way higer than the count parameter
        vertex = idx_vert[index]; // crash by Out of bounds.
        draw_triangle_vertex(vertex);
        
        index = idx_buffer[i+2];
        vertex = idx_vert[index];
        draw_triangle_vertex(vertex);
        
        index = idx_buffer[i+1];
        vertex = idx_vert[index];
        draw_triangle_vertex(vertex);
        rlDisableTexture();
        rlEnd();
        rlPopMatrix();
    }
}
```
The full code can be found here: 

https://github.com/WEREMSOFT/c99-raylib-cimgui-template/blob/master/src/main.c

Thanks in advance.

**Comment by WEREMSOFT** [comment]
I compiled the code using emscripten. If you use chrome canary, you can debug the C code  in the browser. Here's the link
https://htmlpreview.github.io/?https://github.com/WEREMSOFT/c99-raylib-cimgui-template/blob/master/html/main.html

**Comment by ocornut** [comment]
Your code looks invalid, you are not pulling the right `ImDrawCmd`, so you are repeatedly rendering from the first `ImDrawCmd` while increasing the idx_buffer value.

(After you fix it, you may end up noticing that this per-vertex handling, per-triangle draw call approach is probably going to be unnecessary heavy on the CPU. I wouldn't be surprised is that render loop ends up taking 10+ times what the original OpenGL render loop. This will be a good excersice for you to optimize, but you may have to see with rlgl provide abstractions for functions that are not GL1-era functions.)
