### ISSUE TITLE
Windows defined before a dock space cannot be docked to that dock space

### ISSUE THREAD

**Issue by mastergog1** [ocornut/imgui#3341]
Version: Docking branch. Latest from today 7.7.2020.
Back-ends: imgui_impl_glfw3cpp + imgui_impl.opengl3.cpp 
Operating System: Windows 10 Pro

Here is minimal example I tested on the example solution from today's Docking branch:
```
        ImGui::Begin("Main_DockSpace", 0, ImGuiWindowFlags_NoDocking);
        ImGuiID mainDockspaceID = ImGui::GetID("Main_DockSpace");
        ImGui::DockSpace(mainDockspaceID);
        ImGui::SetNextWindowDockID(mainDockspaceID, ImGuiCond_FirstUseEver);
        ImGui::Begin("First");
        ImGui::End();
        ImGui::End();
        ImGui::Begin("Secondary_DockSpace", 0, ImGuiWindowFlags_NoDocking);
        ImGuiID infoDockspaceID = ImGui::GetID("Info_DockSpace");
        ImGui::DockSpace(infoDockspaceID);
        ImGui::SetNextWindowDockID(infoDockspaceID, ImGuiCond_FirstUseEver);
        ImGui::Begin("Second");
        ImGui::End();
        ImGui::SetNextWindowDockID(infoDockspaceID, ImGuiCond_FirstUseEver);
        ImGui::Begin("Third");
        ImGui::End();
        ImGui::End();

```
What's happening is that "Second" and "Third" can dock to "MainDockSpace" but "First" cannot dock to "Secondary_DockSpace". Is that normal?

I feel there is a high chance I'm using the features in a wrong way, but I can't figure it out. My main goal is to have an initial layout for the 3 windows and 2 dock spaces. Then the windows should be freely re-arranged. Except for "Main_DockSpace" and "Secondary_DockSpace" to which we have passed ImGuiWindowFlags_NoDocking

Thank you for the attention.

**Comment by ocornut** [comment]
Hello,

This is documented as such in imgui.h:
```
// About DockSpace:
// - Use DockSpace() to create an explicit dock node _within_ an existing window. See Docking demo for details.
// - DockSpace() needs to be submitted _before_ any window they can host. If you use a dockspace, submit it early in your app.
```
And cannot be changed.

**Comment by mastergog1** [comment]
Wow, my bad... Thank you.

**Comment by ocornut** [comment]
No worries! I'll be closing this now.
