### ISSUE TITLE
TabBar column

### ISSUE THREAD

**Issue by kvetinkavole** [ocornut/imgui#3343]
when i use ImGui::NextColumn(); in the tabbar it hide/move (idk) other tabs
With ImGui::NextColumn(); :
 https://gyazo.com/53a5ac2c56707880cae8b056c685768e
Withount: 
 https://gyazo.com/652c5dac66190f0f28d8bb4c3bef4971
Someone help me with fix?

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by diabopl** [comment]
rip
