### ISSUE TITLE
Problems with overlapping items ('InvisibleButton()')

### ISSUE THREAD

**Issue by dgregorius** [ocornut/imgui#3346]
**Version/Branch of Dear ImGui:**

Version: WP 177
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw3.cpp 
Compiler: Visual Studio 2019
Operating System: Windows 10 Professional

**My Issue/Question:**

I am working on an animation tool and have a basic 2D blendspace. See the attached screenshot as example:

![Blendspace](https://user-images.githubusercontent.com/7042834/87099134-d9039a00-c1fd-11ea-94ce-1a35538369a0.PNG)

The white dots are the animation points which define the blendspace and the red circle is a handle which I can mouse drag to interactively preview the blendspace. Both are rendered using the drawlist and then I add an invisible button for basic item interaction. E.g.

`void Point2D( ImVec2 Position, ImVec2 AxisMin, ImVec2 AxisMax, ImVec2 GridMin, ImVec2 GridMax, bool Selected, float Radius, float Slop )
		{
		float X = ImGui::AxisToScreen( Position.x, AxisMin.x, AxisMax.x, GridMin.x, GridMax.x );
		float Y = ImGui::AxisToScreen( Position.y, AxisMin.y, AxisMax.y, GridMin.y, GridMax.y );
		
		ImDrawList* DrawList = ImGui::GetWindowDrawList();
		DrawList->AddQuadFilled( ImVec2( X + Radius, Y ), ImVec2( X, Y + Radius ), ImVec2( X - Radius, Y ), ImVec2( X, Y - Radius ), Selected ? IM_COL32( 199, 165, 26, 255 ) : IM_COL32( 192, 192, 192, 255 ) );

		// Item
		ImVec2 PinCenter( X, Y );
		ImVec2 PinRadius( Radius + Slop, Radius + Slop );
		ImGui::SetCursorScreenPos( PinCenter - PinRadius );
		ImGui::InvisibleButton( "##Point", 2.0f * PinRadius );
		}
`

When an animation point (white dots) and the drag (red circle) overlap I only can have one item interact. The one which is rendered first. Even if I don't call 'ImGui::InvisibleButton()' for the animation points (white dots) while I am previewing the blendspace the handle (red circle) does not react. The code basically creates the items for the white dots while it is edited. No handle is rendered at this time. If I am previewing the blendspace the white dots are still rendered, but no items are created. The handle (red circle) is rendered now and I only create the item for it. If I create the item only for one and *never* (as in code deleted) for the other everything works. Only if I create the item for both it fails - even though `ImGui::InvisibleButton()` for the animation points and handle are never called in the same frame. 

Any suggestions how to handle this? I assume I am running into some caching problem such that the items are still around even when I don't create them for a particular frame. Practically `ImGui::IsItemActive()` always return false for the second item.

Best,
-Dirk

**Comment by rokups** [comment]
Try using `SetItemAllowOverlap()`.

**Comment by dgregorius** [comment]
Phantasico! This did the job, thank you sir!

**Comment by ocornut** [comment]
Closing this as answered, but would like to add that for this sort of use, you are likely to be able to handle things better and in a simpler way by creating a single `InvisibleButton()` covering your area, and handling the hovering details yourself.

**Comment by ocornut** [comment]
Linking this to https://github.com/ocornut/imgui/issues/3909#issuecomment-799328231 which has an explanation of overlapping modes.

**Comment by luis605** [comment]
I'm using this function as follows inside a child container:
```cpp
    ImGui::BeginChild("Entities List", childSize, true, ImGuiWindowFlags_HorizontalScrollbar);
    ImGui::InvisibleButton("Background", ImGui::GetWindowSize());
    ImGui::SetItemAllowOverlap();
    ....
    a bunch of selectables
```
But it seems to be having no effect, since all the selectables are below the Invisible Button. Am I using the function provided by the API correctly?

**Comment by ocornut** [comment]
Try with `SetNextItemAllowOverlap()` BEFORE `InvisibleButton()`

**Comment by luis605** [comment]
Same issue. Here is the updated code:
```cpp
    ImGui::Begin("TEST");
    ImGui::BeginChild("Entities List", ImVec2(500, 500), true, ImGuiWindowFlags_HorizontalScrollbar);
    ImGui::SetNextItemAllowOverlap();
    ImGui::InvisibleButton("Background", ImGui::GetWindowSize());

    ImGui::Selectable("Item 1");
    ImGui::Selectable("Item 2");

    ImGui::EndChild();

    ImGui::End();
```

**Comment by ocornut** [comment]
>  since all the selectables are below the Invisible Button.

Ah. Well you need to position them...

e.g.
```
ImVec2 p = ImGui::GetCursorScreenPos();

ImGui::SetNextItemAllowOverlap();
if (ImGui::InvisibleButton("Background", ImGui::GetWindowSize()))
    printf("InvisibleButton\n");

ImGui::SetCursorScreenPos(p);
if (ImGui::Selectable("Item 1"))
    printf("Item 1\n");
if (ImGui::Selectable("Item 2"))
    printf("Item 2\n");
```
