### ISSUE TITLE
Hitting IM_ASSERT() : Docking branch and directX12 project when disable io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;

### ISSUE THREAD

**Issue by NaokiIzutani** [ocornut/imgui#3347]
**Version/Branch of Dear ImGui:**

Version: 1.77
Branch: docking

**Back-end/Renderer/Compiler/OS**
Back-ends: example_win32_directx12 x64 Debug
Compiler: Visual Studio 2019
Operating System: Windows 10 64bit

**My Issue/Question**
I am executing example_win32_directx12 with disable "io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;".

![2020y07m10d_124852822](https://user-images.githubusercontent.com/59438084/87115696-f2b0ea00-c2ae-11ea-92e2-b2c3375a2609.jpg)

Hitting at the end of the program : IM_ASSERT(viewport->RendererUserData == NULL && viewport->PlatformUserData == NULL); 

![2020y07m10d_125719117](https://user-images.githubusercontent.com/59438084/87115766-225ff200-c2af-11ea-8ff6-1bda99e42d57.jpg)

This is my first time to post issue on github and i'm not good at English sorry.

**Comment by ocornut** [comment]
Hello @NaokiIzutani,
Thank you for your report. I confirm this is an issue currently and will investigate.

**Comment by ocornut** [comment]
Should be fixed now!

**Comment by NaokiIzutani** [comment]
Thank you!
