### ISSUE TITLE
Some strange glitch

### ISSUE THREAD

**Issue by SweetAss** [ocornut/imgui#3352]
The edges of the elements look weird, but the text displays fine.

![wer](https://user-images.githubusercontent.com/29024350/87360813-8e727c80-c573-11ea-855c-9e48ee896df3.PNG)
![QWRDs](https://user-images.githubusercontent.com/29024350/87360815-8f0b1300-c573-11ea-8284-ccf5e31ddc1c.PNG)

Maybe i need some glEnable or disable something, but i cant find what it is

**Comment by ocornut** [comment]
Sorry but #1586
