### ISSUE TITLE
Child Window Horizontal Scrollbar

### ISSUE THREAD

**Issue by michaelquigley** [ocornut/imgui#3354]
Version: 1.76
Back-ends: imgui_impl_glfw + imgui_impl_opengl3
Compiler: MSVC 19.26
Operating System: Windows 10

I've got a very basic window, which is embedding an `ImGui::BeginChild`/`ImGui::EndChild`:

```
ImGui::BeginChild("child", ImVec2(0, 0));
ImGui::SetCursorPos({1500, 1500});
ImGui::TextUnformatted("hello");
ImGui::EndChild();
```

The parent window that is embedding this child is created with the flags:

`ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoScrollbar`

I'm not getting a horizontal scrollbar to appear on the child window, no matter what combination of flags I try. I've been looking at the examples and searching for hours.

![hello](https://user-images.githubusercontent.com/4443091/87728627-7ed07f00-c791-11ea-8bb6-7a5411ae40a5.PNG)

You can see the `hello` text peeking out behind the vertical scrollbar. The vertical scrollbar seems to be properly respecting the size of the child's contents.

Thanks in advance for any help you can offer.

**Comment by ocornut** [comment]
Hello,

Horizontal scrollbar are opt-in (for variety of reasons), there’s a ImGuiWindowFlags to activate it for the window.

In Demo>Layout there’s a section dedicated to Horizontal Scrolling that showcase use of that flag too.

**Comment by michaelquigley** [comment]
I've tried adding this:

`ImGui::BeginChild("child_2", ImVec2(0, 0), ImGuiWindowFlags_HorizontalScrollbar);`

...as well as the `Always` variant, and in combination, and I still get nothing. Can I not have a horizontal scrollbar just on the child?

**Comment by michaelquigley** [comment]
For what it's worth, adding `ImGui::SetScrollHereX` _does_ scroll my panel to the left edge and I see my text, but still no scrollbar:

```
ImGui::BeginChild("child_2", ImVec2(0, 0), ImGuiWindowFlags_HorizontalScrollbar);
ImGui::SetCursorPos({1500, 1500});
ImGui::TextUnformatted("hello");
ImGui::SetScrollHereX(1.0f);
ImGui::EndChild();
```

![scrolled](https://user-images.githubusercontent.com/4443091/87743808-d08c0000-c7b7-11ea-8046-ab5831ae96ec.PNG)

**Comment by michaelquigley** [comment]
I must have some sort of build reliability issue, because this is now working, almost as if by magic. I swear this wasn't happening for multiple hours, but now appears to be happy:

```
static float w = 200.0f;
static float h = 1500.0f;

ImGui::BeginChild("child_1", ImVec2(w, h), true);
ImGui::TextUnformatted("child_1");
ImGui::EndChild();

ImGui::SameLine();
ImGui::InvisibleButton("vsplitter", ImVec2(8.0f, h));
if(ImGui::IsItemActive()) {
    w += ImGui::GetIO().MouseDelta.x;
}

ImGui::SameLine();
ImGui::BeginChild("child_2", ImVec2(0, 0), false, ImGuiWindowFlags_HorizontalScrollbar);
ImGui::TextUnformatted("child_2");
ImGui::SetCursorPos({1500, 1500});
ImGui::TextUnformatted("hello");
ImGui::EndChild();
```

![working](https://user-images.githubusercontent.com/4443091/87746202-f6b49e80-c7bd-11ea-8935-9c8d01444467.PNG)

Sorry for the distraction. Closing. Don't usually have build reliability issues. Some sort of random gremlin. 👍
