### ISSUE TITLE
How to edit the ImGui GUI?

### ISSUE THREAD

**Issue by RandomNotDev** [ocornut/imgui#3359]
Hello! So, im new using ImGui, and i want to edit the default GUI. I mean, make the Gui looks better, but the problem is that i dont know how to do it. I need some dll? Some another library? Please give me this little help.

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please make sure your posts are filling the Issue Template shown in "New Issue".
- PLEASE ASK ON DISCORD FOR THIS KIND OF QUESTION. Thank you!
Closing.
