### ISSUE TITLE
Shift + Num keys (!@#$%^&_) are not detected on ImGui::InputText

### ISSUE THREAD

**Issue by Nir-Az** [ocornut/imgui#3362]
**Version/Branch of Dear ImGui:**

Version:  "1.49"
Branch: Unknown

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp 
Operating System: Windows 10

**My Issue/Question:**
I use ImGui::InputText() function, when I insert A-Z / 0-9 or any other single key I see it rendered on the InputText box.
If I hit a _ key (Underscore = SHIFT + -) or any other Shift + num key nothing happens.
I debuged it in ImGui and it seems like he think I hit CTRL and SHIFT, both values are true and then the logic is not to call the callback function.

g.IO.KeyCtrl = true
g.IO.KeyShift = true

**Screenshots/Video**

N/A

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
Just open an  ImGui::InputText() on windows 10 and see if you can render SHIFT + NUM keys..


Is it a known issue on my version?
Am I doing something wrong?

Thank you,

Nir.

**Comment by ocornut** [comment]
I am sorry Nir your version is way too old for me to remember off-hand if it had such an issue. You can search in the Changelog which appears in docs/ inversion, or you can easily try the latest version examples on your machine and see if you still have such bug in.

**Comment by ocornut** [comment]
I'm closing this now.

It is incorrect that `io.KeyCtrl` would be set when holding only the Shift key, so perhaps there is a problem with your back-end. I would be happy to help if you used a more recent version but at this point I cannot support a 4+ years old version.

**Comment by Nir-Az** [comment]
I will try to debug it since I cannot update my ImGui version at the current stage.

Thanks.

**Comment by Nir-Az** [comment]
False alarm,
it's not ImGui's fault.

Thanks for the support 👍
