### ISSUE TITLE
Basic sample without 3rd party libraries?

### ISSUE THREAD

**Issue by atorralb** [ocornut/imgui#3364]
Hi team,
sorry to interrupt you.
This might not be the right place but I've been looking all over the internet for some basic examples of imgui but it seems they use other libraries (SDLF or OpenGL)

Can  anybody share me or point me to a basic c++ sample to run this library ( I just want the most basic example to run a window or a button ) in my windows linux subsytem ( ubuntu 18) with the command line.  I've been running the makefiles but have been giving me  compilation errors.  So it will be nice a:
a) basic c++ file
b) command line to run given file

thank you very much and I will close upon provided

**Comment by ocornut** [comment]
Hello,

The examples in the examples/ are the most basic samples to run Dear ImGui in good condition. You cannot render GPU accelerated content without a library and creating windows/contexts it best relegated to a library like SDL or GLFW.

If you are confused by using SDL or OpenGL you are likely going to be even more put off by a version using raw X11 + software rendering (its going to be a lots more code, going to be less portable, and slower).
