### ISSUE TITLE
Can't disable mouse inputs for only a window and not its contents

### ISSUE THREAD

**Issue by JMS55** [ocornut/imgui#3368]
You should be able to disable mouse inputs for windows, but not their contents. 

I'm using an window with no background, non resizeable, can't move it, no title, etc for my UI, like so:
![image](https://user-images.githubusercontent.com/47158642/88760074-3b372700-d13a-11ea-96c1-81874693dafd.png)

The issue is that the window captures mouse input in the space to the right of the "Brush Size" text, since there's technically an invisible background there. Here's what it looks like with the background showing:
![image](https://user-images.githubusercontent.com/47158642/88760149-63268a80-d13a-11ea-9a0c-2f41b1c8c5ac.png)

Using the no mouse input flag fixes this, but also makes it so that you can't interact with any of the buttons or widgets either. I want a mode like no mouse input, but only applying to the window itself, and not it's contents.

**Comment by JMS55** [comment]
I suppose this could be fixed by splitting each row into a separate window for now.

**Comment by ocornut** [comment]
Hello @JMS55,

It's a little difficult with the current hovering scheme. We decide of the "hovered window" at the beginning of the frame, based on first rectangle hit on the front-to-back list of window, and then lots of interactions are filtered early based on this hovered window.

The sort of pass-through you mention would require much more involved hit-testing for each widget, and I honestly wouldn't know how to implement it efficiently at this point.

Some thoughts for work-arounds:
- A. You could split each row into a separate window as you mention (would work but not ideal as keyboard/gamepad navigation won't easily be able to cross-over from one to the other).
- B. There's a specific mechanism used the docking system which allows to register a rectangular hole in window to become input pass-through. I just merged that code in master (c7f5876f) yesterday and if you call `SetWindowHitTestHole()` (declared in imgui_internal.h) you can register that rectangle yourself and it'll have the desired effect. It's a little bit manual but should work.

The hit test callbacks discussed in #1512 would similarly require you to know where those holes are, so I think using (B) should be sufficient for you.

Omar

**Comment by JMS55** [comment]
Thank you for the information. (B) seems like it will work, with (A) as a work-around until imgui publishes a release and imgui-rs updates to it.

Feel free to close this issue
