### ISSUE TITLE
Callback for backspace and delete keys

### ISSUE THREAD

**Issue by s9w** [ocornut/imgui#3373]
**Version/Branch of Dear ImGui:**
Version: 1.77
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Win10

**My Issue/Question:**
`ImGui::InputText()` and friends offer callback functions, in particular `ImGuiInputTextFlags_CallbackCharFilter` to catch character input. That does however not fire for backspace or delete key. In #1723 it was hinted that the reason is a different internal mechanism. Would it still not be possible to expose the result to the callback function? Text input is typically something that can result in expensive checks. Running those checks only on input changes is crucial, and not possible right now if I'm not missing something.

```c++
int type_callback(ImGuiInputTextCallbackData* data) {
   // doesn't run on backspace or delete
   return 0;
}

ImGui::Begin("Example");
static char buf6[64] = "";
ImGui::InputText("label", buf64, 64, ImGuiInputTextFlags_CallbackCharFilter, type_callback);
ImGui::End();
```

**Comment by ocornut** [comment]
> Running those checks only on input changes is crucial, and not possible right now if I'm not missing something.

Hello, I am not sure exactly what you are trying to check in those callbacks specific to those keys, could you elaborate on your use case?

As with every function, InputText() returns true when the underlying value has been modified, which may be helpful for your situation.

**Comment by s9w** [comment]
Oh, I'll be damned - I never noticed that these functions have return values, too. Sorry & thanks!
