### ISSUE TITLE
Debug window issues :/

### ISSUE THREAD

**Issue by KennySpag** [ocornut/imgui#3374]
**Version/Branch of Dear ImGui:**

Version: No idea sorry
Branch: Same

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler:  Visual Studio 19
Operating System: Win10

**My Issue/Question:**

I'm working on a project at the moment and I have finished designing the menu. However, the debug window is visible. From what I have read, this would be caused by a misuse of ImGui::Begin (And it's children). However, I cannot, for the life of me (I've looked for over 3 hours through the entire source and I cannot find it. The debug window is also empty (Incase that means anything)
My question is: Is there a way I can locate this problem without manually searching? (Cause I have been, and can't find it)

**Screenshots/Video**
https://prnt.sc/tsgjdx

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

https://hastebin.com/demuviresi.php
^^ This is the menu files, however, there are other instances of Begin being called.

**Comment by ocornut** [comment]
Sorry but #1586
