### ISSUE TITLE
Fuzzy text when merging non whole number width glyphs. 

### ISSUE THREAD

**Issue by se5a** [ocornut/imgui#3377]
This is more a "how to" than an issue report, posted to help anyone else who might come across this or similar problems.
This will be broken down into four parts:
- First we will look at what I was "Trying to do" which led to the problem,
- then look at the "Symptoms" of this specific problem with some screenshot examples, 
- then examine the "Cause", 
- and finally some code snippets and examples on how to "Fix" it. 
The code snippets will be in C#, as that's what I'm writing in, however it should be simple enough to the reader to translate these to cpp or whatever language they're using in their project. 

### What I was trying to do:
I have been trying to write a 4x space game, somewhat akin to Aurora4x, due to the share amount of information, I needed to use a font that worked well and looked crisp at small sizes, and ended up sticking with the default font ProggyClean. 
However, this font is missing some greek glyphs I wanted to use, specifically Omega, Nu, Delta, and Theta (ΩωΝνΔδθΘ).
I then merged these extra glyphs from another font which did have them into the font atlas. I'll include a code snippet of how to do this as part of the "Fix" section. 

### Symptoms:
Firstly, due to the font I'd chosen for the extra glyphs (I'd given up trying to find a better one after searching around) the glyphs had to be resized down to 13px, this is fairly simple to do as part of the merging process, in doing so however the glyphs look a little less crisp than the rest of the text, this in and of itself while not ideal I could live with in the short to medium term. The real problem however that text *after* these glyphs were used ended up often being fuzzy as well:
![image](https://user-images.githubusercontent.com/1490538/89132458-708faa80-d568-11ea-8ea4-a30f5e78bb3d.png)
The text is in most cases a simple string eg: `ImGui.Text("Total Δv for all manuvers: " + Stringify.Velocity(totalManuverDV));`

### Cause:
The glyph "widths" or `AdvanceX` valuse of ProggyClean are all whole numbers of 7.0 however the gyphs I'd added, once resized were no longer whole number AdvanceX values ranging from 6.2 to 9.4 causing following text to be offset horizontally by a fraction of a pixel.   
The AdvanceX values of a glyph can be seen in the Demo->Tools->StyleEditor->Fonts:
![image](https://user-images.githubusercontent.com/1490538/89132713-4f2fbe00-d56a-11ea-8b3b-f637f09198ec.png)
The screenshot above shows the StyleEditor window with the cursor hovering over one of the glyphs, and the tooltip displaying the AdvanceX value. Note also the PixelSnapH value at the end of the "Input0" and "Input1" lines. we will discuss this in the following "Fix" section (and a bug in Dear Imgui itself, now fixed in commit 5d87841 (versions 1.78 and above). 

### Fix:
In this section I'll lay out the code to load a font from file line by line, and how to merge gyphs to the final font atlas.
To make things a bit easier, and cleaner I'm going to get the references to a few things: 
First off the fontAtlas, this is where the final set of glyphs or chars will be stored:
`ImFontAtlasPtr fontAtlas = ImGui.GetIO().Fonts;`
Next I'm going to get the config which we'll need later to merge the new chars together:
`ImFontConfigPtr config = new ImFontConfigPtr(ImGuiNative.ImFontConfig_ImFontConfig());`
and finally the 'font builder' which will be used to get just the specific glyphs I was after:
`ImFontGlyphRangesBuilderPtr builder = new ImFontGlyphRangesBuilderPtr(ImGuiNative.ImFontGlyphRangesBuilder_ImFontGlyphRangesBuilder());`

That done, I now load the first font into the font atlas, `rf` here is just a string to my 'resourcesFolder` where the fonts are stored on disk, in this case I'm getting all the glyphs:
`fontAtlas.AddFontFromFileTTF(Path.Combine(rf, "ProggyClean.ttf"), 13);`
Note that another way to do the above is to simply: `fontAtlas.AddFontDefault();` since proggyClean at 13 is the default font.  

Next I want to get the glyphs from the second font to the builder, 
`builder.AddText("ΩωΝνΔδθΘ");`
then get the `ranges` from the builder:
`builder.BuildRanges(out ImVector ranges);`

Now we want to merge the ranges into the `fontAtlas`, before we do though, we want to make some changes to the config:
First off, we want to tell it that we're now merging:
`config.MergeMode = true;`
Now this is where we fix the problem we were having, by changing the PixelSnapH to true, imgui will round up the AdvanceX of the glyphs to whole numbers and we will no longer have glyphs getting drawn at fractional positions:
`config.PixelSnapH = true;`

Finaly we merge the ranges into the fontAtlas:
`fontAtlas.AddFontFromFileTTF(Path.Combine(rf, "DejaVuSans.ttf"), 13, config, ranges.Data);`

and for clarity the whole block of code:
```cs
unsafe
{
    ImFontAtlasPtr fontAtlas = ImGui.GetIO().Fonts;
    ImFontConfigPtr config = new ImFontConfigPtr(ImGuiNative.ImFontConfig_ImFontConfig());
    ImFontGlyphRangesBuilderPtr builder = new ImFontGlyphRangesBuilderPtr(ImGuiNative.ImFontGlyphRangesBuilder_ImFontGlyphRangesBuilder());
    builder.AddText("ΩωΝνΔδθΘ"); //Omega, Nu, Delta, Theta (UPPER and lower cases)
    builder.BuildRanges(out ImVector ranges);
    fontAtlas.AddFontFromFileTTF(Path.Combine(rf, "ProggyClean.ttf"), 13);
    config.MergeMode = true;
    config.PixelSnapH = true;
    fontAtlas.AddFontFromFileTTF(Path.Combine(rf, "DejaVuSans.ttf"), 13, config, ranges.Data);
}   
```
Note because I'm messing with pointers, in C# I need to put this in an `unsafe` block. 

Ok now, if you're using an Dear Imgui version older than 1.78 (at the time of writing if you're using imgui.net from nuget you will be on 1.75) you'll need to do some extra little things to work around a bug where Dear Imgui is ignoring the PixelSnapH in the config for the second font, and using the PixelSnapH in the config of the first one loaded. notice in the screenshot of the StyleEditor posted above that the PixelSnapH for the first (ProggyClean) is 0, the second(DejaVuSans) is 1, but the `AdvanceX` on the glyph is 8.8! 
If I'd loaded ProggyClean with `AddFontDefault()` I would have never hit this bug as using the default sets up config to PixelSnapH to true, but I wanted to make it simple for future me to just replace the default font by just editing the string font name in the AddFontFromFileTTF call, instead of having to stop and remember exactly what to do to load it. 
To work around this, I reorder the lines of code around a bit, setting the PixelSnapH before loading the first font and passing config when loading the first (ProggyClean) font. 
note that I need to change `MergeMode=true` *after* I've loaded the first font and before the second:
```cs
config.PixelSnapH = true;
fontAtlas.AddFontFromFileTTF(Path.Combine(rf, "ProggyClean.ttf"), 13, config);
config.MergeMode = true;
fontAtlas.AddFontFromFileTTF(Path.Combine(rf, "DejaVuSans.ttf"), 13, config, ranges.Data);
```
### Finaly:

and the result is orders of magnitude better:
![image](https://user-images.githubusercontent.com/1490538/89133611-69b96580-d571-11ea-9e73-51a621b9c415.png)

Thanks to Ocornut for his patience with me getting side tracked and chasing this problem down wrong turns, and the lightning quick fix once we'd discovered and pinned down the actual bug.

**Comment by ocornut** [comment]
Thanks for the writeup!

Not going to add much to this but going on a tangent :)
As a side note... I'm quite puzzled/shocked at the extra verbosity of using this from C#, namely
```
 ImFontAtlasPtr fontAtlas = ImGui.GetIO().Fonts;
 ImFontConfigPtr config = new ImFontConfigPtr(ImGuiNative.ImFontConfig_ImFontConfig());
 ImFontGlyphRangesBuilderPtr builder = new ImFontGlyphRangesBuilderPtr(ImGuiNative.ImFontGlyphRangesBuilder_ImFontGlyphRangesBuilder());
```
Couldn't the C# binding provide ways to create those structure on the stack with not as much noise?
