### ISSUE TITLE
Clipboard data when ImGui not being run on main thread?

### ISSUE THREAD

**Issue by jwdevel** [ocornut/imgui#3378]
**Version/Branch of Dear ImGui:**

Version: 1.77
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: custom ([BGFX](https://bkaradzic.github.io/bgfx/) renderer)
Compiler: GCC 8.3 (but not really relevant)
Operating System: Debian 10.4

**My Issue/Question:**

I'm trying to figure out the best way to do clipboard copy/paste handling when using GLFW multi-threaded, and ImGui is on a different thread from the GLFW input processing one.

I am generally *not* calling ImGui functions from my "main" GLFW thread. I have a separate rendering thread, which submits draw calls, so that's where ImGui stuff happens.  (maybe this is not recommended? Interested to know, if so.)

I have seen ImGui's GLFW example code, which uses this for clipboard access:

```
static const char* ImGui_ImplGlfw_GetClipboardText(void* user_data)
{
    return glfwGetClipboardString((GLFWwindow*)user_data);
}

static void ImGui_ImplGlfw_SetClipboardText(void* user_data, const char* text)
{
    glfwSetClipboardString((GLFWwindow*)user_data, text);
}
```

But unfortunately, per the GLFW docs, those functions can only be called from the "main" thread.

For comparison, with other input, I am handling it with a queue. For instance, keyboard and mouse events are read on the main GLFW thread, put on the queue, then processed on the rendering thread as needed.
I also update ImGui's IO state at that time, so ImGui has access to keys, mouse, etc.

But that approach doesn't work so well with the clipboard, because GLFW does not provide clipboard events.
I could poll every X milliseconds, but I'm hoping to avoid that.

This is especially a problem for "Copy" inside of ImGui. In a system like mine (if I avoid the polling approach), it would need to send a "request clipboard" event, wait for that to be processed on the main thread (which would call `glfwGetClipboardString`), then wait for that data to come back to the rendering thread. Obviously that doesn't really work with the ImGui's mode of operation.

So, what is the right approach here?

**Comment by jwdevel** [comment]
Having worked on this a bit, I suspect the best approach available, given what GLFW provides, is polling, and maintaining a render-thread-visible "current clipboard snapshot" that gets synced with the main thread.

Feel free to close this, unless there is some better approach I missed.

**Comment by ocornut** [comment]
Hello,

It might be worth investigating why GLFW wants it called on the main thread (what the constraint/requirement are, also it may be OS dependant) but then that's more of a GLFW question.

If you maintain this snapshot note that the "dear imgui thread" may call Set/Get sequences multiple times, but otherwise it should be easy to do as you say.

I'll close for now but feel free to comment if you run into other issues.
