### ISSUE TITLE
[1.45] Unstable Mouse Click Detection

### ISSUE THREAD

**Issue by ZahlGraf** [ocornut/imgui#338]
Hi
In my current application I have issues with an unstable mouse button click detection.
When I receive an event that the mouse button is down, I set the corresponding MouseDown variable of IMGUI to true. And when I receive an event that the mouse button is up again, then I reset this variable to false. 
In a debug build I printed these events to console.
I also printed to the console, when (after a io.NewFrame() ) the MouseClicked and MouseDoubleClicked variable was true.

I would expect the following output:
```
[Event] Mouse Down
[IMGUI] Mouse Click
[Event] Mouse UP
[Event] Mouse Down
[IMGUI] Mouse Click
[IMGUI] Mouse Double Click
[Event] Mouse UP
```

However in my application I got the following output:
```
[Event] Mouse Down
[IMGUI] Mouse Click
[IMGUI] Mouse Click
[IMGUI] Mouse Double Click
[IMGUI] Mouse Click
[IMGUI] Mouse Click
[IMGUI] Mouse Double Click
[IMGUI] Mouse Click
[IMGUI] Mouse Click
[IMGUI] Mouse Double Click
[Event] Mouse UP
[Event] Mouse Down
[IMGUI] Mouse Click
[IMGUI] Mouse Click
[IMGUI] Mouse Double Click
[Event] Mouse UP
```
So it detects a single mouse click as multiple mouse clicks.
I rewrote the code a little bit and tested it. Here I got the expected behaviour. 

```
	 // This is the original code.
	 //g.IO.MouseDownDuration[i] = g.IO.MouseDown[i] ? (g.IO.MouseDownDuration[i] < 0.0f ? 0.0f : g.IO.MouseDownDuration[i] + g.IO.DeltaTime) : -1.0f;
        //g.IO.MouseClicked[i] = g.IO.MouseDownDuration[i] == 0.0f;
        //g.IO.MouseReleased[i] = g.IO.MouseDownDurationPrev[i] >= 0.0f && !g.IO.MouseDown[i];

        /// This is new
        g.IO.MouseReleased[i] = false;
        g.IO.MouseClicked[i] = false;

        if (g.IO.MouseDown[i])
        {
          if (g.IO.MouseDownDuration[i] < -0.5f)
          {
            g.IO.MouseDownDuration[i] = 0.0f;
            g.IO.MouseClicked[i] = true;
          }
          else
          {
            g.IO.MouseDownDuration[i] += g.IO.DeltaTime;
          }
        }
        else
        {
          if (g.IO.MouseDownDuration[i] > 0.01f)
          {
            g.IO.MouseDownDuration[i] = -1.0f;
            g.IO.MouseReleased[i] = true;
          }
         /// here my code ends
```
Best Regards

**Comment by ocornut** [comment]
It looks like you are passing a constant DeltaTime of 0.0 to ImGui to it doesn't think time is moving.

**Comment by ZahlGraf** [comment]
That's a good point. It should not happen from the program sequence point of view. However my application runs on very high frame rates, so maybe sometimes it build up a frame below 1ms and then of course it could be that the DeltaTime is +-0.0. 

I tested it again and added a check if DeltaTime is greater then 0.0f. If not then just a constant value of 0.00001f is delivered to the IMGUI DeltaTime.

So it seems, that my application was just to fast for IMGUI.
However, I wonder why I IMGUI did not raise the assertion, maybe because it was never exactly 0.0 (you cannot test if a float is equal to 0.0f as a result of a calculation)

**Comment by ocornut** [comment]
DeltaTime is in seconds. If your frame is about 1 ms the value should be 1.0f/1000.0f, never zero.

We have an assertion `IM_ASSERT(g.IO.DeltaTime >= 0.0f);`
But DeltaTime=0.0 is legal and useful in some other use cases.

**Comment by ZahlGraf** [comment]
I see. The timer value I get from my system is in milliseconds resolution. Thus when the frame time is in fact below 1ms it will result in a DeltaTime of 0.0 between two frames. 
So in fact is was an error of my application.

However when 0.0f is in some cases a legal value for DeltaTime, then also the mouse click detection should work with it.

**Comment by ocornut** [comment]
> However when 0.0f is in some cases a legal value for DeltaTime, then also the mouse click detection should work with it. 

I made it a little more friendly to dt 0.0 however it's never going to fully work if only fed dt 0.0, e.g. time measurement for a double-click obviously needs time to move.

**Comment by ZahlGraf** [comment]
Thanks :+1:

**Comment by malithmdw** [comment]
I have same problem. what is the solution for this? I cant understand the delta time solution.
