### ISSUE TITLE
I can't use keyboard or mouse on GLUT window with imgui

### ISSUE THREAD

**Issue by ShlomiRex** [ocornut/imgui#3382]
I wrote OpenGL program with glut
I move camera around with keyboard and mouse 
I wanted to add simple GUI to control stuff in the scene, so I chose imgui
I added imgui demo of opengl2 and glut implimentation to my project, it works
Basically I got 1 window which is 'The Game' and 1 window which is imgui demo window
But now I can't use mouse or keyboard to control my scene, the callback functions don't get called

```
int main(...) {
     ..........................
    //Register callbacks
    glutMouseFunc(mouse_click_handler); //Mouse clicks (no mouse changed, only clicks)
    glutKeyboardFunc(keyboard_handler); //Keyboard events
    glutReshapeFunc(reshape_handler); //Window reshaped
    glutDisplayFunc(display_handler); //Render
    glutMotionFunc(mouse_motion_handler);
    .................

        // Setup Dear ImGui context
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;

    // Setup Dear ImGui style
    ImGui::StyleColorsLight();

    // Setup Platform/Renderer bindings
    ImGui_ImplGLUT_Init();
    ImGui_ImplGLUT_InstallFuncs();
    ImGui_ImplOpenGL2_Init();

    //Glut main loop
    glutMainLoop();

    // Cleanup
    ImGui_ImplOpenGL2_Shutdown();
    ImGui_ImplGLUT_Shutdown();
    ImGui::DestroyContext();

    return 0;
}
```

As you can see I simple added imgui stuff after setting up callbacks for my glut window

![Untitled](https://user-images.githubusercontent.com/17744127/89323318-299bd500-d68e-11ea-9142-3caaf1b8dbc5.png)

**Comment by ocornut** [comment]
Please read the comments in imgui_impl_glut.h, your answer is here.

Please fill in the requested template when opening an issue. Thank you.

**Comment by ShlomiRex** [comment]
> n

I read it.
Nothing there is helping me solve the callback handling issue. The header files just contains functions to trigger 'keyboard' event FOR IMGUI. NOT FOR 'The Game'.

**Comment by ocornut** [comment]
Try reading it again.

**Comment by ShlomiRex** [comment]
> 
> 
> Try reading it again.

//  [ ] Platform: Missing clipboard support (not supported by Glut).

In my understanding clipboard != keyboard, is that the problem?

**Comment by ylecuyer** [comment]
Hello @ShlomiRex I encountered the same issue and as you said the comments in `imgui_impl_glut.h` aren't helping (unless saying "if you are using glut use something else" is helping in any way -_-)

So here is the answer:

GLUT only allows one callback for keyboard/special, when you do `ImGui_ImplGLUT_InstallFuncs` which is defined by

```c
void ImGui_ImplGLUT_InstallFuncs()
{
    glutReshapeFunc(ImGui_ImplGLUT_ReshapeFunc);
    glutMotionFunc(ImGui_ImplGLUT_MotionFunc);
    glutPassiveMotionFunc(ImGui_ImplGLUT_MotionFunc);
    glutMouseFunc(ImGui_ImplGLUT_MouseFunc);
#ifdef __FREEGLUT_EXT_H__
    glutMouseWheelFunc(ImGui_ImplGLUT_MouseWheelFunc);
#endif
    glutKeyboardFunc(ImGui_ImplGLUT_KeyboardFunc);
    glutKeyboardUpFunc(ImGui_ImplGLUT_KeyboardUpFunc);
    glutSpecialFunc(ImGui_ImplGLUT_SpecialFunc);
    glutSpecialUpFunc(ImGui_ImplGLUT_SpecialUpFunc);
}
```
Those callbacks are set.

One way I found to add my own handling is to override the ImplGUT callback like this:

```c
//after the call to ImGui_ImplGLUT_InstallFuncs()

//set your own callbacks
glutKeyboardFunc(processKeyboardKeys);
glutSpecialFunc(processSpecialKeys);
```

And elsewhere define those callbacks like this:

```c
void processNormalKeys(unsigned char key, int x, int y) {
  //your handling

  //if not handled on your side call imGui implementation
  ImGui_ImplGLUT_KeyboardFunc(key, x, y);
}

void processSpecialKeys(int key, int x, int y) {
  //your handling

  //if not handled on your side call imGui implementation
  ImGui_ImplGLUT_SpecialFunc(key, x, y);
}
```

**Comment by PathogenDavid** [comment]
> (unless saying "if you are using glut use something else" is helping in any way -_-)

Normally I'm inclined to agree, but GLUT is *seriously* old. The GLUT homepage advertises how it supports Windows 95 and the library hasn't seen an update in over 20 years.

That being said, Omar is referring to this comment, which basically says to do what you're recommending:

https://github.com/ocornut/imgui/blob/23a15834fa23226bd26a17f5142b00678617fec4/backends/imgui_impl_glut.h#L27-L28
