### ISSUE TITLE
Directory tree view

### ISSUE THREAD

**Issue by OverShifted** [ocornut/imgui#3384]
Hi.
I've just implemented a tree view for my little game engine's editor to show the contents of a directory and supports multiple selections.
Then I decided to share that with you guys so I created a gist and uploaded the code.
[https://gist.github.com/OverShifted/13aec504dfe376dcc2171e8b7451c5b5](https://gist.github.com/OverShifted/13aec504dfe376dcc2171e8b7451c5b5)

This is not perfect. it has std::string allocation and checks the filesystem every frame but you might make it better.
 
![gif](https://user-images.githubusercontent.com/53635046/89397486-269ff380-d725-11ea-9e18-58bd06249bb7.gif)

**Comment by ocornut** [comment]
FYI I have added this in the Wiki Extension List under "File Browsers / File Dialog":
https://github.com/ocornut/imgui/wiki/Useful-Extensions

Thanks for sharing!

**Comment by OverShifted** [comment]
Thanks @ocornut! But the gist link seems to be wrong.
