### ISSUE TITLE
Dock nodes of copied dockspace are invalid

### ISSUE THREAD

**Issue by rottier** [ocornut/imgui#3385]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: Win32 backend, D3D11
Operating System: Windows 10

**My Issue/Question:**

I'm currently utilizing the docking branch to create (and delete) configurable dockspaces on the fly. So far, this works like a charm. However, I'm running into some issues with `ImGui::DockBuilderCopyDockSpace`, which I would like to use to duplicate dockspaces. When debugging, I can see that the old and new dock ids are valid, the old windows can be found and that the provided new names of the window_remap_pairs are applied to the newly copied and docked windows. However, the duplicated dockspace doesn't show up properly. The windows are there, but in a broken null-state (can't be found between dock nodes in the metrics window, can be found under windows) and the metrics window shows nullified dock nodes. Calling `ImGui::DockBuilderFinish` doesn't seem to make any difference.

I've provided two screenshots of the metrics window showing the dock nodes state before and after duplication.

**Screenshots/Video**
![DockNodeBeforeDuplication](https://user-images.githubusercontent.com/48617696/89387192-6e615380-d702-11ea-8ff2-4442a28b3c16.PNG)
_Above you can see the metrics of the dock nodes before duplication of a dockspace that contains two panels_

![DockNodeAfterDuplication](https://user-images.githubusercontent.com/48617696/89387246-82a55080-d702-11ea-8b14-a999b6934cf5.PNG)
_Above you can see the metrics of the dock nodes after duplication of that dockspace_

I currently can't provide a working example in C++ because it's currently written using the LuaJIT bindings. Below is roughly what's happening, translated to faux C++.

```
// These are actually requested from a dockspace id register
ImGuiID old_id = ImGui::GetID("OldDockSpace");
ImGuiID new_id = ImGui::GetID("NewDockSpace");

const char* remap[4] = {"###old_name_1", "###new_name_1", "###old_name_2", "###new_name_2"};

ImVector<const char*>* remap_vec = (ImVector<const char*>*)data->remap;

ImGui::DockBuilderCopyDockSpace(old_id, new_id, remap_vec)

// Doesn't seem to matter if dockspace finish-function is invoked
ImGui::DockBuilderFinish(new_id)
```

**Comment by ocornut** [comment]
I am not sure I would be able to help without more details.

Debugging/stepping into the `DockBuilderCopyDockSpace()` and `DockBuilderCopyNode()` function is going to be the easiest way to find what's going on wrong. The demo in my private test bed for this is working.

Also understand that windows are carrying their link to the dockid and the dock node may not be populated with the window before the window gets submitted. But as you pointed out in your case it's odd that the duplicated dock node doesn't have its child nodes, which it should.

**Comment by rottier** [comment]
Thanks for your swift reply, I will dig deeper into this to see where things go wrong. Would it be possible to share that demo so I can check how it's generally supposed to be used?

**Comment by ocornut** [comment]
There's a patch in here with a use of that code:
https://github.com/ocornut/imgui/issues/2109#issuecomment-459409449
Which I believe should still work as-is. I maintain it among many private branches but I tend to make those available to selected users and paying clients otherwise it's too much support work for me, the more I make public the more I get burdened by the support requests (especially on unfinished stuff).

**Comment by rottier** [comment]
In the meantime, I've found the culprit and I can verify that the copy-functionality works perfectly. I was using gui.get_id instead of using my own registered dock id when submitting the generated dockspace. Doh...

Thanks for helping out, @ocornut!
