### ISSUE TITLE
Scrolling resizable colums with fixed headers

### ISSUE THREAD

**Issue by thekiwicoder0** [ocornut/imgui#3387]
Hi,
This is not an issue per se, but I'm trying to make a table view using the columns api.
I have 4 columns, each with it's own header. I'd like to scroll the content while keeping the headers fixed in place.
Not quite sure the best approach for this, I've tried drawing the headers with columns, then resetting, and then using BeginChild for the content. This almost works, except resizing the columns does not resize the headers.

How should I approach this?
Thanks

**Comment by ocornut** [comment]
You should use the Tables branch, it provides exactly this:
https://github.com/ocornut/imgui/issues/2957

This is aimed at merging in master for 1.80 but already usable and regularly rebased over master.
