### ISSUE TITLE
DragFloatRange2 min and max bounds are broken

### ISSUE THREAD

**Issue by ldsLaurent** [ocornut/imgui#3388]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.77 WIP (17601)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_DX11.cpp + imgui_impl_Win32.cpp _(or specify if using a custom engine/back-end)_
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: Windows10

**My Issue/Question:**

There is a bug in DragRange2 widgets caused by the fact that Drag widgets do not clamp the value if v_min == v_max. This is an odd decision, v_min == v_max would be a perfectly defined and valid situation, and this breaks the DragRange2 behavior.
As a simple example imagine a DragFloatRange2 with a min of 0 and a max of 1. If both the currentMin and Current Max get dragged to 0, it is now possible to drag the min to any value from -FLT_MAX to FLT_MAX.
Dragging the min in this state will call
DragFloat("##min", v_current_min, v_speed, (v_min >= v_max) ? -FLT_MAX : v_min, (v_min >= v_max) ? *v_current_max : ImMin(v_max, *v_current_max), format, power);
This call will be entered with both v_min and v_max = 0.0f and the drag will not clamp. The same behavior can of course be used to break the max value by first dragging both values to the max range.

If the test for clamping in DragBehaviorT was:
const bool is_clamped = (v_min <= v_max);
instead of
const bool is_clamped = (v_min < v_max);
The issue would not happen.

Of course if this change was made all similar logic widgets should be changed to not treat equal min and max values as meaning unbounded.

**Screenshots/Video**

XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
static float min = 0.0f;
static float max = 0.0f;
ImGui::DragFloatRange2("Range test", &min, &max, 0.25f, 0.0f, 1.0f, "Min: %.1f", "Max: %.1f");
ImGui::End();
```

**Comment by ocornut** [comment]
Hello, this was fixed two weeks ago in #1441 so if you update to latest it should work.
