### ISSUE TITLE
About InputText Controls Selected Issues

### ISSUE THREAD

**Issue by Ghost-yc** [ocornut/imgui#339]
When I use InputText space character beyond the control display if the input range, use the mouse to drag the selected content, the cursor and select the area would exceed the control
![cap](https://cloud.githubusercontent.com/assets/8528210/9960143/61290ca6-5e4b-11e5-814e-c671d59e8cd7.PNG)

**Comment by ocornut** [comment]
Scroll tracking when mouse dragging was broken around June 16 when adding multiline text edition. Will look into it.

**Comment by ocornut** [comment]
Fixed!
