### ISSUE TITLE
how to draw a circle with filled gradient color

### ISSUE THREAD

**Issue by Thanh-Binh** [ocornut/imgui#3396]
Dear all,
I want to draw a circle with filled gradient color like that
![image](https://user-images.githubusercontent.com/6269904/89736341-fdef6500-da68-11ea-983a-5668044fe881.png)

Maybe we can set the beginning and end color like blue to red etc
I think it looks like ColorPicker4, but can not draw it.
Could you please help me?
Thank your very much for help

**Comment by ocornut** [comment]
Hello,
You can look at how `ColorPicker4` does it:

```
        // Render Hue Wheel
        const float aeps = 0.5f / wheel_r_outer; // Half a pixel arc length in radians (2pi cancels out).
        const int segment_per_arc = ImMax(4, (int)wheel_r_outer / 12);
        for (int n = 0; n < 6; n++)
        {
            const float a0 = (n)     /6.0f * 2.0f * IM_PI - aeps;
            const float a1 = (n+1.0f)/6.0f * 2.0f * IM_PI + aeps;
            const int vert_start_idx = draw_list->VtxBuffer.Size;
            draw_list->PathArcTo(wheel_center, (wheel_r_inner + wheel_r_outer)*0.5f, a0, a1, segment_per_arc);
            draw_list->PathStroke(col_white, false, wheel_thickness);
            const int vert_end_idx = draw_list->VtxBuffer.Size;

            // Paint colors over existing vertices
            ImVec2 gradient_p0(wheel_center.x + ImCos(a0) * wheel_r_inner, wheel_center.y + ImSin(a0) * wheel_r_inner);
            ImVec2 gradient_p1(wheel_center.x + ImCos(a1) * wheel_r_inner, wheel_center.y + ImSin(a1) * wheel_r_inner);
            ShadeVertsLinearColorGradientKeepAlpha(draw_list, vert_start_idx, vert_end_idx, gradient_p0, gradient_p1, col_hues[n], col_hues[n + 1]);
        }
```

You need access to `imgui_internal.h` to call `ShadeVertsLinearColorGradientKeepAlpha()` on a set of vertices.

**Comment by Thanh-Binh** [comment]
@ocornut thanks for your help.
How can I know from your example:
1. the color at the start and end point by drawing circle?
2. in your case, you draw a circle, but I want to draw only a segment of circle from, I say, 7am o'clock to 12 than 1, .. 5pm
What should I modify this code?
Thanks for your help

**Comment by ocornut** [comment]
I am sorry I can't hand-hold you reading the existing C++ code. Please ask on Discord chat about it.

**Comment by Thanh-Binh** [comment]
Thanks, Now I can solve it using your hint and after looking your code, so that I can close this.
