### ISSUE TITLE
Dockspace popup menu

### ISSUE THREAD

**Issue by timeinpixels** [ocornut/imgui#3398]
Is there a way to create a popup menu in an empty Dockspace?
I need a quick right-click context menu with an option to add new window, but the context menu should be available only in an empty dockspace "behind" all the windows.

**Comment by ocornut** [comment]
Hello,

It took me a while to answer this question.
I pushed acf043a and 85a661d and you should be able to poll for that specific empty node hovering using `imgui_internal.h` now:

```
#include "imgui_internal.h"
[...]
ImGuiContext& g = *GImGui;
bool is_dockspace_hole_hovered = g.HoveredDockNode && g.HoveredDockNode->IsEmpty() && ImGui::DockNodeGetRootNode(g.HoveredDockNode)->ID == dockspace_id;
```

From there you should use `OpenPopup()` + `BeginPopup()`, probably like:

```
if (is_dockspace_hole_hovered && IsMouseReleased(1))
   OpenPopup(....)
if (BeginPopup(...)
{
```


(Note that we've been working on a change for #3291, which would eventually facilitate adding custom button in dock node that have tab bar, but not directly solving your specific case).

**Comment by timeinpixels** [comment]
Thanks! Works like a charm!

**Comment by ocornut** [comment]
Great. I'll close this for now!

**Comment by ocornut** [comment]
When I applied this change I thought it would be good if actual docking relied on `g.HoveredDockNode` which actually broke quite a few things. It's possible to set docking/payload filter and therefore on overlapping docking node the actual docking target is not necessarily the 'top-most' docking node. Applied a fix now while preserving `g.HoveredDockNode` as an available mechanism for some operations such as the one discussed above.

**Comment by ocornut** [comment]
It is the same field, it was renamed as the field was only meant to be used for debugging (actual docking can't use this as there are variety of docking filters behaving dynamically).
