### ISSUE TITLE
Suggestion for the Fonts documentation

### ISSUE THREAD

**Issue by stoeckley** [ocornut/imgui#3400]
I've been carefully reading the Fonts docs and FAQ today but there seems to be a piece of missing info that would make it much easier to learn about using a better font:

While there is some nice sample code provided, I can't find a good place to actually place this code. I've tried putting it in various places in the demo code, but that doesn't seem to work anywhere I've tried. Maybe a note about where you could put this -- or show a specific place in the demo code it could go -- would make that easier. For example it mentions to do this before calling NewFrame(), but as a total newbie to the library, it's still not clear where I could quickly paste something like this to see it have an effect:

```
ImGuiIO& io = ImGui::GetIO();	
io.Fonts->AddFontFromFileTTF("examples/Arial Black.ttf", 13);
io.Fonts->Build();
```

Wherever I place this (and I've tried a bunch!), it runs without errors but these three lines of code make the screen entirely blank instead of showing the normal demo.

**Comment by ocornut** [comment]
Hello,

Have you use your IDE to search for "AddFontFromFileTTF" in the example folder? Literally every main.cpp has commented out code showing where/how to use it.

> Wherever I place this (and I've tried a bunch!), it runs without errors but these three lines of code make the screen entirely blank instead of showing the normal demo.

What's the return value from your call? Are you sure its not asserting on incorrect path (which is an extremely frequent error). Have you read the https://github.com/ocornut/imgui/blob/master/docs/FONTS.md section about Filenames? 

Going to add some extra clarification in the fonts docs.

**Comment by stoeckley** [comment]
Hi, thanks for the reply.

> Literally every main.cpp has commented out code showing where/how to use it.

No wonder, I have been using the `example_apple_metal` project, which seems to be nearly the only one without this commented code -- looking at the others, now I see it. I had been reading the docs over and over to see what I was missing, and I should have just changed to a different example project instead. Thanks!

**Comment by ocornut** [comment]
Apologies for the omission. I haven’t written those Apple examples and although I try to make sure they contains the same information this has slipped through!

Will make sure it is equally present in the .mm files and will add clarifications to fonts.md as wel. Thanks for reporting!

**Comment by ocornut** [comment]
I added the missing comments in b762417507c6d77fcaf226f158eb248dc201eb6c

I'm also however noticing that both example_apple_metal/ and example_apple_opengl2/ are lacking cleaning up and they are rather inconsistent between each others, as well as being inconsistent with other examples. I hope some OSX user could come and tidy them up so they are consistent. I would advise that they move toward what example_apple_opengl2/ is doing and less what example_apple_metal is doing.
