### ISSUE TITLE
 LTO build fails due to one definition rule violation

### ISSUE THREAD

**Issue by belegdol** [ocornut/imgui#3403]
This was originally reported as https://github.com/mamedev/mame/issues/7046. In brief, Fedora 33 has enabled LTO by default. mame has failed to build with LTO enabled due to ODR violations, one of which comes from imgui. Mame bundles imgui via bgfx.
Here is the error:
```
../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.h:1344: warning: type 'struct ImGuiIO' violates the C++ One Definition Rule [-Wodr]
 1344 | struct ImGuiIO
      | 
../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.h:1344: note: a different type is defined in another translation unit
 1344 | struct ImGuiIO
      | 
../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.h:1408: note: the first difference of corresponding definitions is field 'RenderDrawListsFnUnused'
 1408 |     void*       RenderDrawListsFnUnused;
      | 
../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.h:1405: note: a field with different name is defined in another translation unit
 1405 |     void        (*RenderDrawListsFn)(ImDrawData* data);
      | 
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [mame.make:269: ../../../../../mame64] Error 1
```
While LTO is unlikely to help mame as stated in the original issue, it might be useful for other projects using dear-imgui which is why I am posting it here.

**Comment by ocornut** [comment]
Hello,

Check said field and you'll understand this is an error in bgfx and/or mame, they must be defining the IMGUI_DISABLE_OBSOLETE_FUNCTIONS inconsistently. Ideally a project would only alter imconfig.h of define IMGUI_USER_CONFIG once and then stick all config options in that configuration file, so all compilation units use the same configuration.

That field triggering the ODR was  added as an exceptional safeguard for a common issue which can be ignored if ODR isn't a problem, if it this then it's up to the user to use consistent compile-time imgui options.

**Comment by belegdol** [comment]
Thanks for the pointer, I believe I know where the issue is.
