### ISSUE TITLE
Cutom Values in Sliders

### ISSUE THREAD

**Issue by scarletxd** [ocornut/imgui#3405]
Hey
The other day i was making a simple game for the sake of experience and learning.
I am using imgui's renderer for most of the stuff including controls and some 2d graphics, but the game was kinda bland and required so customization and i was working on it.
My question is how do i use custom values in the sliders?

Ii have a sliderint which goes from 0 to 120 and i want the game to do x when the value is 0 and y when its between 1 and 100 and z when its above 100 which i have done, but i want to show something like 
"Auto" on the slider when the slider hits 0 and
"Title/Label + (the actual value - 100)" when the slider hits 100+

What i have as of now:
```cpp
const char* slider_get(int value, std::string title) {
    if (value == 0) {
        return "Auto";
    }
    else if (value > 100) {
        return "";//don't know what i wanna do here
    }
    else {
        return "%d";
    }
}
```

Thanks in advance!

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. Closing.
