### ISSUE TITLE
Imgui.ini cannot be written since program can not modify the files under the install directory on some platform

### ISSUE THREAD

**Issue by HenryAWE** [ocornut/imgui#3407]
**Version/Branch of Dear ImGui:**

Version: 1.73
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC 2017
Operating System: Windows 10 1903

**My Issue/Question:**
Program can not modify the files under the install directory on some platform, such as `C:\Program Files\XXX` on Windows
Currently my solution is setting the working directory of the program to some accessible directory before initializing the ImGui
Is there any better solution? Such as redirecting the data of the `imgui.ini` into memory and saving/loading it by myself

**Comment by ocornut** [comment]
You can change `io.IniFilename` to the full path of your choice.

**Comment by ocornut** [comment]
You can also see `io.IniFilename = NULL;` and use `LoadIniSettingsFromDisk(), `LoadIniSettingsFromMemory()`, `SaveIniSettingsToDisk()`, `SaveIniSettingsToMemory()` however you want. 

`io.WantSaveIniSettings` will be set to true when saving needs to be done and then you can clear the flag again.
