### ISSUE TITLE
C4996 'strcpy': This function or variable may be unsafe. In imgui_impl_opengl3.cpp.

### ISSUE THREAD

**Issue by samrrr** [ocornut/imgui#3408]
C4996	'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	irambis	C:\Users\genam\source\repos\irambis\irambis\src\ImGui\imgui_impl_opengl3.cpp	176	
C4996	'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	irambis	C:\Users\genam\source\repos\irambis\irambis\src\ImGui\imgui_impl_opengl3.cpp	177	
C4996	'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	irambis	C:\Users\genam\source\repos\irambis\irambis\src\ImGui\imgui_impl_opengl3.cpp	499	

Version: Current release

Back-ends: imgui_impl_opengl3.cpp
Compiler: MSVC 2019
Operating System: Windows 10

Cant compile with precompiled header.
Because of unsafe things. Every updade imgui i am need again add _s.

What about add some ifdef for this use?

Add _CRT_SECURE_NO_WARNINGS isnt a good way for me.

**Comment by ocornut** [comment]
Hello,

If you insist on not turning `_CRT_SECURE_NO_WARNINGS` for your code, then when using Precompiled Header you shouldn't compile third party code such as Dear ImGui with your precompiled header enabled. Visual Studio project files offer this options, as well as sensible build systems.

That's the best I can do. Working around this in small cpp files such as backends would be too much ifdef blocks and even Microsoft seemingly suggested that `_CRT_SECURE_NO_WARNINGS` was a mistake, I recall reading it is now or soon to be reenabled by default.

Cheers

**Comment by samrrr** [comment]
https://github.com/ocornut/imgui/blob/95c99aaa4be611716093edcb6b01146ab9483f30/imgui.cpp#L757

Is add something like this to cpp isnt a good way?

#ifdef _MSC_VER
#pragma warning (disable: 4996)             // 'This function or variable may be unsafe': strcpy, sscanf, strcat
#endif
