### ISSUE TITLE
[Release] RGB into ImVec4 automation

### ISSUE THREAD

**Issue by HyeN2018** [ocornut/imgui#3415]
Hello, im not having any issues with your project, i just found the conversion from RGB into ImVec4 a bit hard to understand as a newcomer and after some researches i created a C++ program to convert them.

In my opinion, a lot of users will find this very useful.

Preview: https://imgur.com/a/YavEy96
EXE Link:https://drive.google.com/file/d/1AWMxMlv4HuJ297rbIUTkksB0E18DT4kj/view?usp=sharing
Virustotal Link:https://www.virustotal.com/gui/file/f953f0cde40a9744445c33bac0bc8cb9e846c1f5dbf3e0de98be956f0671a7cf/detection
I don't really know how it got 2 detections but you can compile it yourself to check.

Here's the source code for it:

```
using namespace std;
#include <iostream>

int main(float R,float G,float B,float Alpha,int loop)
{
	loop = 0;
	cout << "Example input:144 17 18 255" << endl;
	cout << "144 = R (Red)" << '\n';
	cout << "17 = G (Yellow)" << '\n';
	cout << "18 = B (Blue)"<<'\n';
	cout << "255 = Alpha" << '\n'<<'\n';
	while (loop == 0)
	{
		cout << "Input you RGBA Color:";
		cin >> R >> G >> B >> Alpha;
		R = R / 255;
		G = G / 255;
		B = B / 255;
		Alpha = Alpha / 255;
		cout << "Result: ";
		printf("%.2ff", R);
		cout << ", ";
		printf("%.2ff", G);
		cout << ", ";
		printf("%.2ff", B);
		cout << ", ";
		printf("%.2ff", Alpha);
		cout<<'\n';
		cout << '\n';
	}

}
```

**Comment by ocornut** [comment]
Hello, I think it's better you discuss it on the Dear ImGui Discord server, as the Github Issues are not fit for general programming explanation.
Thank you.
