### ISSUE TITLE
Sidebar: left window padding

### ISSUE THREAD

**Issue by Vine1** [ocornut/imgui#3425]
Hi!
I want to make sidebar for my window. I can render it using RenderFrame/window->DrawList->AddFilledRect, but I don't know how to move *sidebar width* pixels right all window content. Changing CursorPos moves only first element. I want to move all.
Also, second problem is window padding. Can I draw sidebar before padding? Screenshot(padding x 50 pixels) https://i.imgur.com/fpiYzwg.png

**Comment by ocornut** [comment]
You can use Indent() or BeginGroup() or SetCursorPos() + BeginChild().
Push a WindowPadding of zero if it's bothering you.

Didn't follow requested guidelines or issue template. Closing.
- Please make sure you have read the guidelines. 
- Please make sure you have checked the demo.
