### ISSUE TITLE
Does imgui support to add anchor in a image? 

### ISSUE THREAD

**Issue by continue567** [ocornut/imgui#3426]
Like this in Lens Studio
![image](https://user-images.githubusercontent.com/20896273/91001196-a838c200-e5fd-11ea-8813-773f75af94c4.png)
There are 4 anchor points in face image.

**Comment by ocornut** [comment]
Not out of the box but you can create any custom widgets. Please ask on Discord for further help.

Closing this: Didn't follow requested guidelines or issue template.

**Comment by ocornut** [comment]
Check wiki for widgets references, eg this bezier editor use anchors:
https://github.com/ocornut/imgui/issues/786
