### ISSUE TITLE
InputTextMultiline/Password Flag Assertion

### ISSUE THREAD

**Issue by hoffstadt** [ocornut/imgui#3427]
**Version/Branch of Dear ImGui:**

Version: 1.78 and 1.79 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: ALL
Operating System: ALL

**My Issue/Question:**

When using _InputTextMultiline_ with the **ImGuiInputTextFlags_Password**, an assertion occurs saying to fonts remain on the stack. 

**Screenshots/Video**

XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
static char text[200] = "Here we go    ";
ImGui::InputTextMultiline("Widget", text, sizeof(char)*200, ImVec2(0,0), ImGuiInputTextFlags_Password);
```

**Comment by ocornut** [comment]
Fixed by #3428, thanks for reporting.
