### ISSUE TITLE
STL conformance for ImVector

### ISSUE THREAD

**Issue by manhnt9** [ocornut/imgui#3429]
**Version / Branch of Dear ImGui:**

Version: 1.78
Branch: master

**Back-end / Renderer / Compiler / OS**
SDL + Vulkan / GCC 9.3 / Ubuntu 20.04

**My Issue/Question:**
When using ImVector with some STL adapters, I can't compile due to lack of `max_size()` implementation.
(I'm trying to bind `dear ImGui`'s data types for anoother language - current bindings still don't fit my circumstance after trying out).

**Proposed fix**
Add this function to ImVector (imgui.h):
```cpp
    inline std::size_t max_size() const { return XXX; // platform-specific limit }
```
I've tried that and compiled successfully.

**Comment by ocornut** [comment]
﻿Hello,
ImVector<> is not designed to be STL conformant and being not sure how you intend to use that I don’t know what else is coming next (aka we won’t make ImVector fully conformant). 

If your vector bindings are auto-generated you could possibly insert that data/function yourself?. Maybe add max_size() pretending it is INT_MAX, try working with that and see how far you get? 
If the only thing you need is max_size() I’d consider adding it.

**Comment by manhnt9** [comment]
Yep adding only `max_size()` has worked so far. I'm pretty sure that no other modification is required for this kind of task. Maybe someone else will need it too in the future. The issue is discovered when using dear ImGui's type with [Sol2](https://github.com/ThePhD/sol2) - a very popular Lua binding for C++.

**Comment by ocornut** [comment]
Added `max_size()` now!
