### ISSUE TITLE
Page up/page down doesn't seem to work with `InputTextMultiline`

### ISSUE THREAD

**Issue by jarrettchisholm** [ocornut/imgui#3430]
**Version/Branch of Dear ImGui:**
**Back-end/Renderer/Compiler/OS**

```
Dear ImGui 1.79 WIP (17803)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1927
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

If I open the `InputTextMultiline` widget, and then add a bunch more text so that it is scrollable, and then hit page up or page down it does not do anything.

Is this a limitation of imgui?

**Comment by ocornut** [comment]
You are correct this is currently a missing feature in `InputTextEx()`, it needs to be added there.

(Note that PageUp/PageDown is otherwise supported by navigation (OUTSIDE of Multiline Input) but has to be explicitly enabled with the `ImGuiConfigFlags_NavEnableKeyboard` flag.)

**Comment by Xipiryon** [comment]
@jarrettchisholm I've made the change, which is now on master ( https://github.com/ocornut/imgui/commit/ec945f44b5eff1d82129233be5643abbff2845da ) :)
