### ISSUE TITLE
cursor under window

### ISSUE THREAD

**Issue by Kianbs** [ocornut/imgui#3435]
Hi, i have a issue with my Mouse Cursor.

it is under my imgui window.

so you can see: https://cdn.discordapp.com/attachments/733780733306339499/748306589076815902/unknown.png

my code:

https://hastebin.com/yapuhayiye.cpp

i hope that anyone can help me.

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
