### ISSUE TITLE
negative char value doesn't print

### ISSUE THREAD

**Issue by ApourtArtt** [ocornut/imgui#3436]
Hello !

I have been troubling for a long time (trying, reading, reading, trying, etc.) to display some characters.

First of all :
- I am talking about negative char (-128 ~ -1), so `é°èà` can't be displayed. Even worse : sometimes, the whole string seems ignored.
- I have configured the range to accept `{0x20, 0xFF, 0}` and in my tries, I configured (then removed) it with `{0x20, 0xFFFFFFFF, 0}`. I also tried `{0x20, 0xFFFF, 0}` for the `>0xFF` char.
- I am sure that my font accept those characters and I tried with default font, Arial font, and the one I want to use. I also checked with charmap as an "ultimate test" (could have done with imgui_demo, though).
- **Using a "compiled string" (I don't know how it is called) work : `u8"35°C"` will be printed as it has to be printed.**
- `#pragma execution_character_set("utf-8")` or `/utf` don't change anything.

As an example, if my string is `35°C`, it will print `35C`, but if I use a more-than-one-byte character (`>0xFF`), then the string will display : `nothing`.
My datas are assigned during the execution, not during the compilation, received as `char *` : I can parse ever bytes, and I will see `0xFFFFFFB0` for `°`. I tried to add `0xFF` to this byte, but no way, as it is a `char`. So I converted it as a `std::string`, I wanted it anyway. Tried again to add this `0xFF`, but was stupid, it is still `char`.
So here I am : I read a lot, tried a lot, and didn't succeeded.

Last important information I think I can give, is that I am using `std::string` and I use `std::string::c_str()` function to get the `char *` reprensation. But looking byte to byte, it is the same, so I am pretty sure it isn't due to this.

On top of that, I am also using a console and it is displaying everything has it should. So I know that I am messing up something, but what ?!

PS : I posted it on Discord with some differences and I want to thank the one who helped me to figure out some things ! Unfortunately, still didn't succeed.

**Comment by ocornut** [comment]
Your string data needs to be UTF-8 encoded.
Using u8”” encode literal as UTF-8. You mention this is working why not using that?

If you have strings from other sources you need to use a function to convert them from whatever encoding they use to UTF-8. If you search for utf8 related librairies you’ll probably find those helpers (imgui_internal.h also have some).

This is not really a Dear ImGui specific problem by the way.

**Comment by ocornut** [comment]
I am closing this because you didn’t fill the requested issue template nor following issue guidelines.
