### ISSUE TITLE
Deleting the background off imgui apps

### ISSUE THREAD

**Issue by nanoCPP** [ocornut/imgui#3438]
Hey, I was wondering if there is some way that you could like erase the background of the ImGui application so there is just the windows instead of the background aswell, 
![image](https://user-images.githubusercontent.com/66254725/91640743-c183a900-ea17-11ea-90da-c2da20c2cf97.png)

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
