### ISSUE TITLE
No main/parent window.

### ISSUE THREAD

**Issue by nanoCPP** [ocornut/imgui#3439]
**My Issue/Question:**
Hey, is there any way to make the main/parent window background invisible so you just have the ImGui windows instead of the big main window with the ImGui windows inside it? Look at the gif too see what I'm tryna say.

**Screenshots/Video**
![c5b8dkH](https://user-images.githubusercontent.com/66254725/91646500-b7799e80-ea47-11ea-80a8-d8f71a309183.gif)
I WOULD LIKE SOMETHING LIKE THIS INSTEAD OF :
![image](https://user-images.githubusercontent.com/66254725/91646554-2f47c900-ea48-11ea-8b08-ff646e82103c.png)

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
