### ISSUE TITLE
Access ImDrawVert only over getter and setter functions.

### ISSUE THREAD

**Issue by ZahlGraf** [ocornut/imgui#344]
Hi

This is not an urgent request and it is not an error at all. I just want to make an enhancement proposal and maybe you will find it useful for future versions.

I'm currently implementing a binding for IMGUI to Irrlicht. To be compatible with all render engines of Irrlicht (DirectX, OpenGL, Software-Renderer), I don't want to use native OpenGL or DirectX functions for that. So I want to render all IMGUI primitives with Irrlicht API functions.
This is basically possible, however Irrlicht uses a very different type of Vertex than IMGUI to render primitives. 

Thanks to IMGUI_OVERRIDE_DRAWVERT_STRUCT_LAYOUT you can simply exchange the type of ImDrawVert. However all drawing functions of IMGUI expect a "pos", "uv" and "col" member inside ImDrawVert. 
Of course the Irrlicht Vertex type has similar members but with different names and different types. So I cannot use the IMGUI_OVERRIDE_DRAWVERT_STRUCT_LAYOUT functionality. 

At the moment the only possibility for me is to copy in a loop all IMGUI vertices to a temporary array of Irrlicht vertices before I render them with Irrlicht. This is not really an optimal solution from performance point of view. 

That's why I would suggest to introduce functions to write and read the Position, Color and UV coordinates to/from ImDrawVert objects instead of using the ImDrawVert members directly. 
Something like that:
inline void writePosToVert(ImDrawVert * pVertex, float X, float Y) {...}
inline void readPosFromVert(ImDrawVert * pVertex, float &X, float &Y) {...}

And then allow to overwrite those functions with own functions when IMGUI_OVERRIDE_DRAWVERT_STRUCT_LAYOUT is set. 

Then I could set ImDrawVert to the original Irrlicht Vertex type and I could adapt the access functions to handle the Irrlicht Vertex Layout and use the Vertex Array given in ImDrawList directly to render the primitives with Irrlicht.

Best regards :)

**Comment by ocornut** [comment]
That would be unacceptable both for performances and for readability.

You can simply use IMGUI_OVERRIDE_DRAWVERT_STRUCT_LAYOUT with a structure that matches the memory mapping of your vertex format but name the field like ImGui expect them. aka copy and paste your structure and rename those 3 fields.

**Comment by ZahlGraf** [comment]
It is not that easy since those 3 fields are not just have different name, they also have different types that are accessed in different ways as IMGUI does it.

You can add those access functions as inline functions, thus the generated assembler code would be the same like accessing the members directly. And if you don't trust the compiler to optimize this you could also use access macros instead of access functions (But every modern compiler at the market today can handle those inline functions this without performance losses). 

Furthermore I don't really understand the argument of less readability. Using getter/setter functions instead of accessing class/struct members directly is a widely spread programming technique called "encapsulation" and is considered as "very good coding style" in literature. 

Don't get me wrong: It is your project and your decision. It is just a suggestion and it would help to adapt IMGUI to many different render engines. 
I don't ask you to do it immediately or within the next month. I just ask you to consider such an option in any further release.
At the moment I'm fine with the performance penalty I get from copying the Vertex list into an temporary array. And if I really cannot live with this any more, I will simply create my own local patch for IMGUI.

**Comment by ocornut** [comment]
> It is not that easy since those 3 fields are not just have different name, they also have different types that are accessed in different ways as IMGUI does it.

How is your vertex structure looking like?

> (But every modern compiler at the market today can handle those inline functions without performance losses). 

Not in an optimized build and ImGui is optimized for non-optimised builds as well.
But yeah, we could use macros possibly.

> considered as "very good coding style" in literature. 

I don't care what is "considered" "very good coding style" in "literature". If we followed very good coding style from literature ImGui wouldn't be allowed to exist at all in the first place :)
Many applications of encapsulation (which itself is a perfectly legit concept) are bullshit.

**Comment by ZahlGraf** [comment]
The position vector has three float members instead of two (z must be set to 0 for the GUI elements).
Furthermore there is also a normal vector also with three floats. Here X and Y must be set to 0 and Z must be set to 1 for GUI. 
The color is also u32 but in a different order then the native OpenGL color.

**Comment by ocornut** [comment]
Then it's not a problem just create a structure with ImVec2 pos and a dummy z, normal etc. ImGui won't touch them. You can set a constructor if you want to reset Z 0.0 and set the normal (although your shader could ignore it too).

For the color you are better off using a shader/render setup that render the thing that ImGui uses. While you are there you can just use ImGui native vertex format. Your original assumption is a bit misleading:

> however Irrlicht uses a very different type of Vertex than IMGUI to render primitives. 

If you are making an engine I'd imagine you can render with different vertex formats as well.

**Comment by ZahlGraf** [comment]
I don't know, this sounds more like a dirty hack than a solution. If the compiler creates really the same memory layout out of it is not guaranteed. It could add padding bits to it or between two Irrlicht versions the layout of the vector structs or of the vertex in general could change silently and lead later to very strange errors that are compiler, architecture and version dependent. 

Of course I could simply use the OpenGL example code from IMGUI and adapt it to work together with the Irrlicht OpenGL renderer. In fact I already implemented a native OpenGL renderer out of your OpenGL example that works quite well with Irrlicht. However this is just a test and fall-back implementation, since this would limit Irrlicht to just use OpenGL for rendering.
I want also support the other Irrlicht render engines, thus for a more generic driver, I'm limited to the API functions of Irrlicht. And that's why I have to use Irrlicht Vertices and Irrlicht Color Scheme. Everything else is just a hack. 

As I said: I'm not in a hurry. Keep this ticket here and think about it in the next months. I can completely understand that you don't want to touch code that is working very well, just to fulfil a single request of a single user with low priority. 

If you change it in such a way in any future release, I will be happy, since then I can use a non-patched IMGUI version. If not it is also ok for me, I can work around it. 
Maybe in the next months you will get more requests like this from other IMGUI users, when they read about this idea here. 
Thanks for sharing your suggestions and thought about it :)

**Comment by ocornut** [comment]
>sounds more like a dirty hack than a solution.

It if works it is a solution. Whether you feel it is a hack or not is another thing. In practice it works and won't break. They are trivial types. And you can always add a compile time assert to check that the types have the same size and it'll tell you if it ever breaks.

>I'm limited to the API functions of Irrlicht.

Surely the engine must allow user to develop their own shaders?

I can't keep too many issues open, already have lots of work on the library so we need to prioritize and focus on the important stuff. Keeping an issue open has a mental cost :). And here you've got a solution of copying vertices around anyway which has such a minor cost anyway.

**Comment by ZahlGraf** [comment]
Of course you can add own shaders to Irrlicht. But it is another step to more complexity. 
Also with the memory it is too complex in the end. In practice it might work out of the box with my compiler and with my current version of Irrlicht and IMGUI. Static assertions will only help to find issues with it earlier but not to solve the issues. In the end, both solutions: Shaders and memory layout will lead much maintenance work when the code is used for different versions, compilers, operating systems and CPU architectures. 

Really, it is much easier to simply apply a patch file to IMGUI to solve the issue at the source with native C/C++ code that is highly portable.

Of course you are free to close this ticket. It is still there and everyone who is interested can find, read and reopen it if he wants.

**Comment by ocornut** [comment]
I'd imagine it should be trivial to add a shader to Irrlicht.

There's hundred of access to those fields in ImGui and even an additional macro would be unsatisfactory for what essentially already has solution on your side (copy loop or a shader will be a one-off on your side I fail to see why that would require more than rare-maintenance, whereas ImGui code will be worked on for a long time and is designed to be terse and avoid unnecessary noise and indirections which a macro would add).

Anyway I'm sorry but I prefer to close this at the moment. Too many higher priorities :(
