### ISSUE TITLE
My try align button to center fail

### ISSUE THREAD

**Issue by samrrr** [ocornut/imgui#3440]
I am try align button by use this:

ImGui::Indent((ImGui::GetWindowSize().x - ImGui::ButtonSize("Quit...........................").x) / 2 
	- ImGui::GetStyle().ItemSpacing.x);
if (ImGui::Button("Quit..........................."))
{
	core.QuitGame();
}

Its work:
![image](https://user-images.githubusercontent.com/18705603/91663372-062f4300-eaf1-11ea-801f-12d89f217c2e.png)
![image](https://user-images.githubusercontent.com/18705603/91663377-0deee780-eaf1-11ea-8232-9e49b542706e.png)

But its Fails when indent_w==0
![image](https://user-images.githubusercontent.com/18705603/91663361-f6176380-eaf0-11ea-865d-65da25d9082a.png)

https://github.com/ocornut/imgui/blob/master/imgui.cpp#L7106
void ImGui::Indent(float indent_w)
{
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = GetCurrentWindow();
    window->DC.Indent.x += (indent_w != 0.0f) ? indent_w : g.Style.IndentSpacing;
    window->DC.CursorPos.x = window->Pos.x + window->DC.Indent.x + window->DC.ColumnsOffset.x;
}

I can try set its to 0.000000001f but its not a really solution.

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (do not create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
