### ISSUE TITLE
ImGuiBackendFlags_PlatformHasViewports and ImGuiBackendFlags_RendererHasViewports wrongly named in comment

### ISSUE THREAD

**Issue by juliettef** [ocornut/imgui#3445]
https://github.com/ocornut/imgui/blob/600b8f60b48f8a038065753830e99e975412379e/imgui.h#L1183

Comment should refer to ImGuiBackendFlags_PlatformHasViewports and ImGuiBackendFlags_RendererHasViewports respectively.

Thought it would be easier for you as an issue rather than a PR.

**Comment by ocornut** [comment]
Thank you Juliette for spotting this.
I'll commit this along the next change in Docking (it's already staged)

**Comment by ocornut** [comment]
Sneaked this change in 8dacb4da20021f4289ac56a83738672604a0db61
