### ISSUE TITLE
Text drawing improving request: Cache glyphs into multi textures (size under 2048x2048) to avoid crash on some old device

### ISSUE THREAD

**Issue by Xiliusha** [ocornut/imgui#3448]
**Version/Branch of Dear ImGui:**

Version: 1.78
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: custom 2d graphic engine (based on imgui_impl_win32.cpp + imgui_impl_dx11.cpp)
Compiler: MSVC 19.27.29111
Operating System: Windows10 2004 19041.450

**My Issue/Question:**

I'm using imgui for 1 years and I recieved a crash report from one of my team member last week:
* me and other menbers can open the application normally
* he can't open the application because application crashed
* he buy a new laptop and ⛏ the old one, the problem solved

I found why it crashed, because his old laptop only support D3D_FEATURE_LEVEL_9_1 and the maximum texture size allowed is 2048x2048. Our application need to draw Chinese and Japenese text so the size of atlas texture is up to 16384x16384. (my god...)
_Yes, I can using "Windows Image Component" to scale the texture size, but this is not I want. If I do it, all the glyphs will become mosaic._

So I think imgui can add support of multi atlas textures in the future. (maybe it is easy to implement?)
_The other choice is support dynamic font atlas texture, but I known this is more complex and need to design a more friendly API and rewrite huge number of codes._

Anyway, thank you for bringing us such a nice GUI library. 😄

**Comment by ocornut** [comment]
Hello,

> The other choice is support dynamic font atlas texture, but I known this is more complex and need to design a more friendly API and rewrite huge number of codes.

This is what we are going to do eventually. Multi-texture atlas prior to that isn't going to be any easier it's going to completely break the merging of draw calls.

I think you should look at "Font Atlas too large?" section of the FONTS documentation:
https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#font-loading-instructions

Honestly Dear ImGui is not suited to display Chinese at this point only you build your own custom dynamic range and build dynamically when needed.

So unfortunately as per your request this isn't something we can do short term.

**Comment by Xiliusha** [comment]
Thanks.
Now our solution is limit the minimum D3D feature level to 11_0 (support 16384x16384 texture) and we known this is not a long-term solution.
Are there any related issue, branch or pull request about dynamic font atlas texture? I'm interested in it and search in issues, but I can't found.

**Comment by ocornut** [comment]
Hello,
As mentioned above you have other solutions such as using `ImFontGlyphRangesBuilder` and building and rebuilding your atlas dynamically based on needs.

> Are there any related issue, branch or pull request about dynamic font atlas texture? I'm interested in it and search in issues, but I can't found.

There's none. I'm starting to build a more solid idea of how things needs to be done but I don't know when it'll be happening.

I'm closing this as for now we're not doing what suggested above. I'll post again here if there's a suitable change.
