### ISSUE TITLE
Bugged ImGuiInputTextCallbackData::DeleteChars?

### ISSUE THREAD

**Issue by ryobg** [ocornut/imgui#3454]
What happens if we call, for example, `DeleteChars (0, 5)` when our `CursorPos` is somewhere in the middle of the string i.e. less than `byte_count`, but after `pos`? For example `2`.

Answer: Out of this function we are left with dangling `CursorPos == -3`. Which may or may not trigger an assert out of the callback, depending how more we messed up with this out of order state. Selection is also going off btw.

Excerpt of the more important piece of code:
```c++
void ImGuiInputTextCallbackData::DeleteChars(int pos, int bytes_count)
{
    IM_ASSERT(pos + bytes_count <= BufTextLen);
    // ...
     if (CursorPos + bytes_count >= pos)
        CursorPos -= bytes_count;
    else if (CursorPos >= pos)
        CursorPos = pos;
    SelectionStart = SelectionEnd = CursorPos;
    //..
}
```

Direct link:
https://github.com/ocornut/imgui/blob/70289ab42ca01fccc4c3d18a6ce880cd79b203e4/imgui_widgets.cpp#L3614

**Comment by ryobg** [comment]
Possible solution is to clamp it within a safe range during the first condition? Say:
```c++
CursorPos = ImMax (CursorPos - bytes_count, 0);
```

**Comment by ocornut** [comment]
Hello @ryobg, thanks a lot for reporting this!
I believe this code is incorrect and should always have been:
```
    if (CursorPos >= pos + bytes_count)
        CursorPos -= bytes_count;
    else if (CursorPos >= pos)
        CursorPos = pos;
   SelectionStart = SelectionEnd = CursorPos;
```
Fixed it now.

**Comment by ryobg** [comment]
Quick! Patched (its old) my code this way too. Good luck!
