### ISSUE TITLE
Button with wrapped label

### ISSUE THREAD

**Issue by JonasTietz** [ocornut/imgui#3456]
```
Dear ImGui 1.77 WIP (17601)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201402
define: __linux__
define: __GNUC__=7
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x00001406
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.77 WIP
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_onpengl3.cpp 
Operating System: Ubuntu 18.04

**My Issue/Question:**

Hello :)
I want to create fixed size buttons with long wrapped text. Right now I don't find an easy way to do this.
My approach would be to implement my own button based on ImGui::ButtonEx and RenderTextWrapped. 
But I would still need to center the lines and clip it if the text is to long.
My question is if I am missing something obvious or is this the way to go.

**Comment by ocornut** [comment]
Hello Jonas,

> My approach would be to implement my own button based on ImGui::ButtonEx and RenderTextWrapped

That should work, you'd essentially want to write your own alternate version of `ButtonEx()`.

> But I would still need to center the lines 

Centered multi-line rendering is currently not supported in the low-level function.

> and clip it if the text is to long

The `RenderTextClipped()` call done in `ButtonEx()` has all the parameters you need here.

**Comment by JonasTietz** [comment]
Thanks for the reply :)
Then I will take a deeper look at RenderTextClipped().
I guess this issue can be closed. I just wanted to make sure that I didn't miss some part of the API.
