### ISSUE TITLE
Imgui DirectX11 Issue (PLEASE RESOPND ASAP)

### ISSUE THREAD

**Issue by Dubhghall** [ocornut/imgui#3458]
I get this error when compiling my project in visual studio : error LNK2019: unresolved external symbol _D3D11CreateDeviceAndSwapChain@48 referenced in function "bool __cdecl CreateDeviceD3D(struct HWND__ *)" (?CreateDeviceD3D@@YA_NPAUHWND__@@@Z)

https://i.imgur.com/zXtnomz.png

(PLEASE RESOPND ASAP)

Thanks.

**Comment by johanwendin** [comment]
You haven't linked properly to Direct3D by the looks of it. It's not an ImGui issue. (and not nearly as urgent as you impose)

**Comment by Dubhghall** [comment]
> You haven't linked properly to Direct3D by the looks of it. It's not an ImGui issue. (and not nearly as urgent as you impose)

I used the DirectX 11 example
