### ISSUE TITLE
Freetype in implementations question

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#3465]
**Version/Branch of Dear ImGui:**

Version: 1.78
Branch: master or docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp (or sdl also)

**My Issue/Question:**

I have made cimgui able to use FreeType2 with imgui_freetype.cpp and I am now loading the fonts with Freetype
The LuaJIT-ImGui code for changing font is now:

```Lua
--this will run outside of imgui NewFrame-Render
local function ChangeFont(font,fontsize)
	local ig = win.ig
	local FontsAt = ig.GetIO().Fonts
	------destroy old
	FontsAt:Clear()
	------reconstruct
	--load default
	FontsAt:AddFontDefault()
	--prepare config for extra font
	local fnt_cfg = ig.ImFontConfig()
	fnt_cfg.PixelSnapH = true
	--use merge to see results without changing font
	--fnt_cfg.MergeMode = true
	fnt_cfg.GlyphMinAdvanceX = fontsize 
	fnt_cfg.GlyphMaxAdvanceX = fontsize 
	fnt_cfg.OversampleH = 1
	fnt_cfg.RasterizerFlags = ffi.C.MonoHinting
	
	--maximal range allowed with ImWchar16
	local ranges = ffi.new("ImWchar[3]",{0x0001,0xFFFF,0})

	local theFONT= FontsAt:AddFontFromFileTTF(font, fontsize, fnt_cfg,ranges)
	if (theFONT == nil) then return false end
	
	--regenerate 
	ig.ImGuiFreeType_BuildFontAtlas(FontsAt,ffi.C.MonoHinting)
	--FontsAt:Build()
	ig.lib.ImGui_ImplOpenGL3_DestroyFontsTexture()
	ig.lib.ImGui_ImplOpenGL3_CreateFontsTexture()
	--set as default
	--ig.GetIO().FontDefault = theFONT
	return true
end
```

So I have used ImplOpenGL3_DestroyFontsTexture(); and ImplOpenGL3_CreateFontsTexture(); instead of DestroyDeviceObjects or CreateDeviceObjects and it seems to work but I am still in doubt:

In https://github.com/ocornut/imgui/tree/master/misc/freetype

Is correct to replace

ImGui_ImplXXX_DestroyDeviceObjects();
 ImGui_ImplXXX_CreateDeviceObjects();

by

ImGui_ImplXXX_DestroyFontsTexture();
 ImGui_ImplXXX_CreateFontsTexture();

or result wont be the same?

**Comment by ocornut** [comment]
- Haven't filled issue template.
- You are not explaining why you care about this (see http://xyproblem.info) so can't provide a meaningful answer.
- Not all back-ends have a _DestroyFontsTexture() function.

**Comment by sonoro1234** [comment]
Sorry about that, just updated information above.

**Comment by ocornut** [comment]
Well you are still not explaining the reason for doing that in the first place.
But since you are concerned with a single back-end why not just looking at the back-end code and see if it fits your needs?

**Comment by sonoro1234** [comment]
> Well you are still not explaining the reason for doing that in the first place.

The reason for wanting to try imgui_freetype?

**Comment by ocornut** [comment]
The reason for calling ImGui_ImplOpenGL3_DestroyFontsTexture() instead of calling ImGui_ImplOpenGL3_DestroyDeviceObjects()....

**Comment by sonoro1234** [comment]
Ahh, the reason would be avoiding unnecessary work to be done. (In case it is unnecessary for just reconstructing fonts)

**Comment by ocornut** [comment]
That's negligible but if it works for you it'll work.

We will at some point have API to communicate/request the back-end to reload part of the texture, this is planned for shadow and fonts api.
