### ISSUE TITLE
Option to display label on left side for data inputs and combo

### ISSUE THREAD

**Issue by brukted** [ocornut/imgui#3469]
Dear ImGui 1.76 WIP (17502)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1900
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00

Is there any way to display the label for a combo on left side instead of right side  other than  something  like  this
```
ImGui::Text("label");
ImGui::SameLine();
if(ImGui::BeginCombo("","preview")){
      //Combo items
     ImGui::EndCombo();
}
```

**Comment by rokups** [comment]
You would have to render it manually. I have a function just for that.

Sample usage:
```cpp
ImGui::ItemLabel("Label on the left", ItemLabelFlag::Left);
ImGui::BeginCombo("##combo", ...);
```

```cpp
enum ItemLabelFlag
{
    Left = 1u << 0u,
    Right = 1u << 1u,
    Default = Left,
};

void ItemLabel(ea::string_view title, ItemLabelFlags flags)
{
    ImGuiWindow* window = ImGui::GetCurrentWindow();
    const ImVec2 lineStart = ImGui::GetCursorScreenPos();
    const ImGuiStyle& style = ImGui::GetStyle();
    float fullWidth = ImGui::GetContentRegionAvail().x;
    float itemWidth = ImGui::CalcItemWidth() + style.ItemSpacing.x;
    ImVec2 textSize = ImGui::CalcTextSize(title.begin(), title.end());
    ImRect textRect;
    textRect.Min = ImGui::GetCursorScreenPos();
    if (flags & ItemLabelFlag::Right)
        textRect.Min.x = textRect.Min.x + itemWidth;
    textRect.Max = textRect.Min;
    textRect.Max.x += fullWidth - itemWidth;
    textRect.Max.y += textSize.y;

    ImGui::SetCursorScreenPos(textRect.Min);

    ImGImGui::AlignTextToFramePadding();
    // Adjust text rect manually because we render it directly into a drawlist instead of using public functions.
    textRect.Min.y += window->DC.CurrLineTextBaseOffset;
    textRect.Max.y += window->DC.CurrLineTextBaseOffset;

    ItemSize(textRect);
    if (ItemAdd(textRect, window->GetID(title.data(), title.data() + title.size())))
    {
        RenderTextEllipsis(ImGui::GetWindowDrawList(), textRect.Min, textRect.Max, textRect.Max.x,
            textRect.Max.x, title.data(), title.data() + title.size(), &textSize);

        if (textRect.GetWidth() < textSize.x && ImGui::IsItemHovered())
            ImGui::SetTooltip("%.*s", (int)title.size(), title.data());
    }
    if (flags & ItemLabelFlag::Left)
    {
        ImGui::SetCursorScreenPos(textRect.Max - ImVec2{0, textSize.y + window->DC.CurrLineTextBaseOffset});
        ImGui::SameLine();
    }
    else if (flags & ItemLabelFlag::Right)
        ImGui::SetCursorScreenPos(lineStart);
}
```

**Comment by ocornut** [comment]
You can also use Columns for that (or upcoming Tables api).

About:
```
ImGui::Text("label");
ImGui::SameLine();
if(ImGui::BeginCombo("","preview")){
      //Combo items
     ImGui::EndCombo();
}
```
Please note that an using empty label in combo is incorrect 99% of the times, please read the FAQ https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it
An empty label with conflict with whatever is already in the id stack (e.g. root window itself).

**Comment by brukted** [comment]
Thanks!

**Comment by Andrew900460** [comment]
I know this is an old thread, but this was the top result on google.\

The custom code that Rokups offered has a couple compiler errors that have to be resolved. Such as:
* "ItemLabelFlag" and "ItemLabelFlags"
* ea::string_view ??? std::string_view
* ImVec2 does not have overload for subtraction operator
etc.

I fixed those things on my end, which hopefully gives the correct functionality:

Named this file `imgui_extras.cpp`
```
#include <string_view>
#include <imgui.h>
#include "imgui_extas.h"
#include <imgui_internal.h>


static ImVec2 Subtract(const ImVec2 a, const ImVec2 b) {
	return ImVec2{b.x - a.x,b.y - a.y};
}

void ImGui::ItemLabel(std::string_view title, ItemLabelFlag flags) {
	ImGuiWindow* window = ImGui::GetCurrentWindow();
	const ImVec2 lineStart = ImGui::GetCursorScreenPos();
	const ImGuiStyle& style = ImGui::GetStyle();
	float fullWidth = ImGui::GetContentRegionAvail().x;
	float itemWidth = ImGui::CalcItemWidth() + style.ItemSpacing.x;
	ImVec2 textSize = ImGui::CalcTextSize(title.data(), title.data()+title.length());
	ImRect textRect;
	textRect.Min = ImGui::GetCursorScreenPos();
	if(flags & ItemLabelFlag::Right)
		textRect.Min.x = textRect.Min.x + itemWidth;
	textRect.Max = textRect.Min;
	textRect.Max.x += fullWidth - itemWidth;
	textRect.Max.y += textSize.y;

	ImGui::SetCursorScreenPos(textRect.Min);

	ImGui::AlignTextToFramePadding();
	// Adjust text rect manually because we render it directly into a drawlist instead of using public functions.
	textRect.Min.y += window->DC.CurrLineTextBaseOffset;
	textRect.Max.y += window->DC.CurrLineTextBaseOffset;

	ImGui::ItemSize(textRect);
	if(ImGui::ItemAdd(textRect, window->GetID(title.data(), title.data() + title.size()))) {
		ImGui::RenderTextEllipsis(ImGui::GetWindowDrawList(), textRect.Min, textRect.Max, textRect.Max.x,
			textRect.Max.x, title.data(), title.data() + title.size(), &textSize);

		if(textRect.GetWidth() < textSize.x && ImGui::IsItemHovered())
			ImGui::SetTooltip("%.*s", (int)title.size(), title.data());
	}
	if(flags & ItemLabelFlag::Left) {
		ImGui::SetCursorScreenPos(Subtract(textRect.Max, ImVec2{0, textSize.y + window->DC.CurrLineTextBaseOffset}));
		ImGui::SameLine();
	} else if(flags & ItemLabelFlag::Right)
		ImGui::SetCursorScreenPos(lineStart);
}
```
Named this file: `imgui_extras.h`

```
#pragma once
#include <string_view>

enum ItemLabelFlag {
	Left = 1u << 0u,
	Right = 1u << 1u,
	Default = Left,
};

namespace ImGui {
	void ItemLabel(std::string_view title, ItemLabelFlag flags);
}
```

With this being said though, idk if this code is still the "correct" or "main" way to do this, as this issue is 4 years old now.
It would be nice if there was simply some global setting to make any Widget with a label render from the left instead. Set once and then forget for the rest of the program.

In my case, the custom ItemLabel function seems to add a ton of extra space and pushes widgets out of view. I have a bunch of Widgets on a single line using SameLine(), and most of the widgets get hidden because the label length is way too long.

**Comment by ocornut** [comment]
Most people nowadays are using tables to achieve this.

> It would be nice if there was simply some global setting to make any Widget with a label render from the left instead. Set once and then forget for the rest of the program.

FYI this is one of our oldest open issue: #395 
I have an internal refactor planned which should allow this, it's however a highly constraining change as it prevents FramedWidget;SameLine;ExtraContents idioms from being usable.
