### ISSUE TITLE
GL3 sample is missing call to glDisable(GL_BLEND)

### ISSUE THREAD

**Issue by nickgildea** [ocornut/imgui#347]
The GL3 sample's render function calls glEnable(GL_BLEND) but doesn't call glDisable(GL_BLEND) when restoring the state.

**Comment by ocornut** [comment]
Doing that know but I haven't saved all the blend func/settings. Need to do that as well.

**Comment by ocornut** [comment]
Now saving/restoring some more blending state, closing this.
