### ISSUE TITLE
How to get Last Hover Id Timer & Last Hover Id?

### ISSUE THREAD

**Issue by enchanty** [ocornut/imgui#3474]
LastActiveIdTimer Version <- I Have This
```  float addf = 0.10f;
    float g = *v ? 1.0f : 0.0f;
    if (g.LastActiveId == g.CurrentWindow->GetID(label))
    {
        float tb = ImSaturate(g.LastActiveIdTimer / addf);
        g = *v ? (tb) : (1.0f - tb);
    }
```
LastHoverIdTimer Version <- I Need This
``` float addf = 0.10f;
    float g = *v ? 1.0f : 0.0f;
    if (g.LastHoverId == g.CurrentWindow->GetID(label))
    {
        float tb = ImSaturate(g.LastHoverIdTimer / addf);
        g = *v ? (tb) : (1.0f - tb);
    }
```

How I Get Last Hover Id Timer & Last Hover Id

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
