### ISSUE TITLE
FPS control?

### ISSUE THREAD

**Issue by Xeverous** [ocornut/imgui#3476]
**Version/Branch of Dear ImGui:**

Version: newest (commit a1597cff088a827e98688632f6523fae2b6513af)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: any/all
Compiler: any/all
Operating System: any/all

**My Issue/Question:**

FPS in the example demos seems fixed (60). I'm searching for ways to control FPS:

- How many FPS can this library output (without any limits)
- How to set/remove upper bound for FPS

I have checked FAQ, browsed issues and the header comments but nothing appears to be there. There is only framerate variable which stores current FPS based on last 120 frames.

**Screenshots/Video**

Not needed.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Not needed.

**Comment by ocornut** [comment]
Hello,

The reason it is not covered by documentation is that's not a topic that is in the control of dear imgui. The library renders what you ask it to render, with the `io.DeltaTime` that you specify.

That 120 float array you mentioned is merely a helper to facilitate calculating framerate but doesn't alter it.

You can ask this question on game development forum, but the TL;DR; is that:
- If you disable waiting for vsync (also often referred to as swap interval), you'll notice that the application will run at "maximum" speed (e.g. probably 1000-2000 FPS) and burn all resources of 1 CPU core.
- When possible, it is ideal for game-like application to render at screen refresh rate and using vsync as a natural way to throttle the speed down.
- But you can manually throttle down the speed, by e.g. using delay to wait until the expected time.

if you search for e.g. "fps limiter c++" you'll probably find good references to get started with.

**Comment by Xeverous** [comment]
That's enough for me, I just needed to know that FPS/core loop is outside the scope of this library.

**Comment by Andrej123456789** [comment]
Just call sleep function and sleep for 10 miliseconds and you will get max 60 FPS
