### ISSUE TITLE
[Request] Custom ImGui::BeginCombo Imgui 

### ISSUE THREAD

**Issue by Hyndratos** [ocornut/imgui#3485]
Hi could anyone help me in doing this Custom. ImGui::BeginComboa
![image](https://user-images.githubusercontent.com/49354762/93826558-29708c80-fc70-11ea-8b14-eb7773bfe6fe.png)

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 

- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
- Please clarify your question, it is currently hard to understand what you are asking about.

Closing until issue is edited.

You may also use Discord to ask for help.
