### ISSUE TITLE
Check the font build in ImGui_ImplWin32_NewFrame

### ISSUE THREAD

**Issue by actboy168** [ocornut/imgui#3487]
ImGui_ImplWin32_NewFrame will check if the font is built. If the Renderer releases the resource (ClearTexData) after creating the font resource, this check will fail. But it has no effect. Does this mean that this check is wrong?

**Comment by ocornut** [comment]
Hello @actboy168,
Sorry for my very late answer to this.
You are very right, the assert was incorrectly formulated, preventing the use of `ClearTexData()`.
I fixed it now.
We don't expect `ClearTexData()` to be used by many people but still.
Note that work on #3761 when enabled will probably require user to keep CPU copy in memory.

We'll keep allow manual warming / baking of ranges + discarding of CPU/RAM data, can be useful for low-specs platforms.
