### ISSUE TITLE
korean input

### ISSUE THREAD

**Issue by H0ng** [ocornut/imgui#3489]
korean is well displayed but I can't enter Korean on InputText

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines and FILL THE FORM.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.

**Comment by H0ng** [comment]
Ime is disabled when i click on the input text

**Comment by H0ng** [comment]
> Didn't follow requested guidelines or issue template.
> 
> * Please make sure you have read the guidelines and FILL THE FORM.
> * Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
> 
> Closing.

Ime is disabled when i click on the input text

**Comment by H0ng** [comment]
modified it.

**Comment by H0ng** [comment]
> Didn't follow requested guidelines or issue template.
> 
> * Please make sure you have read the guidelines and FILL THE FORM.
> * Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
> 
> Closing.

modified it.

**Comment by ocornut** [comment]
> modified it.

- You didn't fill the form, please specify which back-ends you are using.
- I think SDL has a bug where the IME is not displayed.
- Please add printf() code next to the `io.AddInputCharacter()` call and see which characters are sent to dear imgui.
