### ISSUE TITLE
[MinGW] using DLL causes error due to IMGUI_API for inline functions

### ISSUE THREAD

**Issue by ZahlGraf** [ocornut/imgui#349]
Hi

I built today a DLL with MinGW (GCC 4.9.3) of IMGUI. Then later while I was compiling the demo application I got 4 errors from the imgui.h file (IMGUI_API is then dllimport)

```
imgui.h:1163:15: error: function 'ImDrawData::ImDrawData()' definition is marked
 dllimport
     IMGUI_API ImDrawData() { Valid = false; CmdLists = NULL; CmdListsCount = TotalVtxCount = TotalIdxCount = 0; }
               ^
imgui.h:1219:33: error: function 'void ImFontAtlas::SetTexID(void*)' definition
is marked dllimport
     IMGUI_API void              SetTexID(void* id)  { TexID = id; }
                                 ^
imgui.h:1278:33: error: function 'float ImFont::GetCharAdvance(short unsigned in
t) const' definition is marked dllimport
     IMGUI_API float             GetCharAdvance(unsigned short c) const  { return ((int)c < IndexXAdvance.Size) ? IndexXAdvance[(int)c] : FallbackXAdv
ance; }
                                 ^
imgui.h:1281:33: error: function 'bool ImFont::IsLoaded() const' definition is m
arked dllimport
     IMGUI_API bool              IsLoaded() const                        { return ContainerAtlas != NULL; }
                                 ^
```

All these functions are implicit inline functions, so basically they don't need to be imported from a DLL. I guess this is the reason for that error on MinGW. 
Deleting the IMGUI_API definition from these function fixes the errors.

I also recompiled everything (DLL + Application) with MSVC2015 to check if this fix harms the Visual C++ build. But everything was fine. 

I looked at the [dllimport attribute documentation for GCC 4.9.3](https://gcc.gnu.org/onlinedocs/gcc-4.9.3/gcc/Function-Attributes.html#Function-Attributes)

> Currently, the attribute is ignored for inlined functions. If the attribute is applied to a symbol definition, an error is reported. 

I just wonder why MinGW does not treat these functions as inline functions and raises this error. However when I explicitly add the "inline" keyword to this function MingW compiles without errors. It just prints a warning that dllimport was ignored for those functions. 

Best Regards

**Comment by adam4813** [comment]
Compiler attempting to optimize unintelligently perhaps?

**Comment by paulsapps** [comment]
I believe its because it wants to use external linkage but can't because its inline. E.g if I replace Imgui.dll with some other version with the same interface it wont pick up the inline code changes because they wont be called from the dll, they're inlined into the client code.

**Comment by adam4813** [comment]
What Paul said. I misread the issue.

**Comment by ocornut** [comment]
I removed the IMGUI_API market here. It is a little annoying there. 
ImGui needs some of the inlining for performance. Compiling as DLL is possible (but not recommended) although as you pointed out the use of inline makes is that end-user code needs to be compiled for the same version as the DLL. (which effectively it pretty much the same for so many libraries on Windows..)

**Comment by ZahlGraf** [comment]
Thanks, for taking care about this.

At least in the examples I created so far, I could not see any performance drop from shared library compared to static library. However the examples are running anyway at around 2000 FPS, so I guess you would not notice some function calls more. 

This might be differently in much more complex projects with really huge GUIs that run on non high-end computers or mobile devices. Here every function call counts!

**Comment by ocornut** [comment]
No it is rather minor to be fair (in particular those 4 calls), I've just been spending too much time on optimisation a decade ago and it never left me. As long as compilers manage to inline most functions without a same compilation unit, even compiled as dll export it's totally fine (and it seems to be the case)
