### ISSUE TITLE
Problem with glDrawElements and other ImGui changes

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#350]
Hello. 

I left ImGui a couple of months ago (just before the popup menu release) and now I'm trying to upgrade my programs to support the git version of the library.

I'm currently experiencing a couple of problems:

1) When I use shaders, I got a segmentation fault in <b>glDrawElements</b>; however the same program, using no shaders, works. The problem must be somewhere in my code, since the plain opengl3 demo works. However I'm not going to post my code now, but hints about this problem could be helpful :)

2) When I use semi-transparent image buttons (as toolbar buttons), now the background looks blue instead of being completely transparent. Is the API changed ? How can I restore the transparent background ?

Thank you in advance.

**Comment by hypernewbie** [comment]
Which video card?

**Comment by Flix01** [comment]
GT 130 with proprietary driver on Ubuntu.

But that it's not the point, since the default imgui-opengl3 demo works properly: so it's something in my code.

I just hoped somebody else had the same problem and solved it to have some hint...

**Comment by ocornut** [comment]
1) Perhaps this thread can be a hint on your problem with glDrawElements?
https://github.com/ocornut/imgui/pull/322

2) Nothing related with transparency has changed for a long time.

**Comment by Flix01** [comment]
Thanks for your reply.

1) I've solved it right now!
The problem was that the array and element array buffers must be bound BEFORE calling glEnableVertexAttribArray(...) and glVertexAttribPointer(...): in the opengl3 demo you used a vertex array object: that's probably the reason why the last two calls were missing.

However the I moved the binding of the two buffers outside the loop, so I made the glEnableVertexAttribArray(...) and glVertexAttribPointer(...) calls only once outside the loop as well: that should not hurt performance that much.

2) Well, but it seems that the ImGui style Button color still affects the colors of my semi-trasparent images. So it's not clear to me what is the role of the Button color and the other two colors that ImGui::ImageButton(...) takes as parameters ...

**Comment by Flix01** [comment]
Never mind, I've found the relevant code inside ImButton:

```c++
    // Render
    const ImU32 col = window->Color((hovered && held) ? ImGuiCol_ButtonActive : hovered ? ImGuiCol_ButtonHovered : ImGuiCol_Button);
    RenderFrame(bb.Min, bb.Max, col);
    if (bg_col.w > 0.0f)
        window->DrawList->AddRectFilled(image_bb.Min, image_bb.Max, window->Color(bg_col));
    window->DrawList->AddImage(user_texture_id, image_bb.Min, image_bb.Max, uv0, uv1, window->Color(tint_col));
```
So, I'll start to think about it.
