### ISSUE TITLE
Coloured in the right color 

### ISSUE THREAD

**Issue by A0R3M1O** [ocornut/imgui#3500]
Hello everyone, sorry for perhaps a very stupid question, such a situation, I need to paint a circle with an empty center as a spinnerBar, only this painting dodge occur provided that if the variable type float is 100.0f, then the circle will be painted completely, if for example this variable will be equal to 20.0f then, the circle will be painted on 20%, I'm  a beginner (

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please read the guidelines then edit your post with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
