### ISSUE TITLE
 how can i convert beginCombo to listbox?

### ISSUE THREAD

**Issue by Hyndratos** [ocornut/imgui#3504]
i need help how can i edit this code in listbox format. I tried some time but I have not managed to do it
```
	static const char* current_item = NULL;
	ImGui::SameLine(0, 20);
	if (ImGui::BeginCombo("##resources", current_item))
	{
		for (int i = 0; i < resources->size(); i++) {

			auto resource = resources->at(i);


			bool is_selected = (current_item == resource->name.c_str());
			if (ImGui::Selectable(resource->name.c_str(), is_selected))
				current_item = resource->name.c_str();


			if (is_selected)
				ImGui::SetItemDefaultFocus();

		}
		ImGui::EndCombo();

	} ImGui::SameLine();
```

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

If you don’t want to read and follow guidelines please ask on Discord, thank you.

Closing.
