### ISSUE TITLE
Feature request: ImgGui::Image1d

### ISSUE THREAD

**Issue by tuket** [ocornut/imgui#3510]
It would be great if we could have an alternative to `ImgGui::Image` that works for 1D textures. Currently, when you pass a 1D texture from OpenGL it throws an error:
```
GL_INVALID_OPERATION error generated. Target doesn't match the texture's target
```
because ImGui tries to bind it as `GL_TEXTURE_2D`

**Comment by thedmd** [comment]
This is probably a task for custom `ImDrawCallback`:
https://github.com/ocornut/imgui/blob/4fd43a8b64155d9c01c615afd5b0831a60b47c0f/imgui.h#L1980-L1989

**Comment by ocornut** [comment]
Hello,
As mentioned by Michał if you want to do something back-end dependant you may use the `ImDrawCallback` mechanism for binding the texture yourself. 

Generally in high-level engine people would end up storing a high-level "texture" or "material" data into ImTextureID which would help identifying the contents and/or way to bind and display it (shader permutation). In the case of the raw OpenGL binding, technically it may be possible in OpenGL to obtain the type of the texture given its id? In which case for this specific case (1d binding) you could also do it automatically, but in reality there's an infinite combination of render possibilities so it's better to embrace either using callbacks, either using a higher-level type for ImTextureId.

**Comment by tuket** [comment]
Thanks for your help, I will try the callback approach.
