### ISSUE TITLE
Mouse Input Overlay

### ISSUE THREAD

**Issue by GameChampCrafted** [ocornut/imgui#3512]
How am I suppose to allow mouse input from the application imgui is on? This is what I am currently doing which is not working. 
![image](https://user-images.githubusercontent.com/39221871/95283177-23121100-0829-11eb-8764-d77de1ad31fa.png)
I read in the imgui class file that I should use 'ImGui::GetIO().WantCaptureMouse = true;' which is not making a difference.

**Comment by GameChampCrafted** [comment]
Or is there anyway to make the gui always interactable when it gets showed?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Compare your code to examples code to find what you are missing.
- To reopen: Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.

**Comment by ocornut** [comment]
Giving you a more complete answer as your post are made in good faith, but PLEASE do fill requested issue template when asked.
I think you are not forwarding window message (notice the examples/ are calling `ImGui_ImplWin32_WndProcHandler()` to forward messages received from the main app).
