### ISSUE TITLE
Implementing ImGui in a component based Engine

### ISSUE THREAD

**Issue by tzikitxo** [ocornut/imgui#352]
Hello all, Im creating a component Game Engine in c++ using openGl 3.3. I readed the examples, but I would like to ask for help on how to implement it.

Thank for your help, is my first engine :P

**Comment by ocornut** [comment]
Please clarify, you're not giving much information. There's an example for OpenGL which you should be able to mostly copy and paste.

**Comment by tzikitxo** [comment]
Well, sorry, i went theough the opengl examples, but I already got my own renderable component with rendera all the renderables, algo got my own input manager. The part that most troubles is the rendering part :/

**Comment by adam4813** [comment]
In our engine we just render the gui after all "renderable" components but
before well flip the front and back buffers.

**Comment by neilogd** [comment]
Same approach here. ImGui is rendered after the scene renders all components. It is treated as a special case as since its a debug UI system.

-----Original Message-----
