### ISSUE TITLE
// Demonstrate create a simple game view.

### ISSUE THREAD

**Issue by FilipePpereira** [ocornut/imgui#3524]
![meuprojecto01](https://user-images.githubusercontent.com/71448175/95754734-62ae8200-0c9b-11eb-87bc-81060cbc8025.PNG)
![meucodigo](https://user-images.githubusercontent.com/71448175/95754793-76f27f00-0c9b-11eb-831f-1432254f1094.PNG)
![meuprojecto](https://user-images.githubusercontent.com/71448175/95754797-7823ac00-0c9b-11eb-9e19-f1deff4fc598.PNG)
![meuprojecto01](https://user-images.githubusercontent.com/71448175/95754799-7823ac00-0c9b-11eb-9406-4d3852d7011b.PNG)

void WindowManager::ShowExampleAppPropertyEditor(bool* p_open)
{	
	ImGuiViewport* viewport = ImGui::GetMainViewport();

	
	ImGuiWindowFlags flags = ImGuiWindowFlags_NoScrollbar
		| ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_AlwaysUseWindowPadding;

	ImGui::SetNextWindowSize(ImVec2(viewport->Size.x, viewport->Size.y), ImGuiCond_FirstUseEver);
	
	
	if (!ImGui::Begin("Editor", p_open, flags))
	{
		ImGui::End();
		return;
	}
		
	ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0, 0));
	
	s_pWindowManager->m_FrameBuffer->Bind();

	ImGui::Text("Frametime: %.3f ms (FPS %.1f)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
	ImGui::Image((void*)s_pWindowManager->m_FrameBuffer->GetTexture(), ImVec2(viewport->Size.x, viewport->Size.y));

	

	glm::mat4 projection = glm::mat4(1.0f);
	glm::mat4 view = glm::mat4(1.0f);
	glm::mat4 model = glm::mat4(1.0f);

	glm::vec3  m_Position = glm::vec3(0.0f, 0.0f, 0.0f);
	glm::vec3  m_Front = glm::vec3(0.0f, 0.0f, -1.0f);
	glm::vec3  m_Up = glm::vec3(0.0f, 1.0f, 0.0f);
	
	/*view = glm::lookAt(m_Position, m_Position + m_Front, m_Up);*/
	view = s_pWindowManager->m_camera->GetViewMatrix();
	projection = glm::perspective(glm::radians(45.0f),
		viewport->Size.x / viewport->Size.y, 0.01f, 10000.0f);

	angle += 1000.0f / ImGui::GetIO().Framerate;

	
	model = glm::translate(model, glm::vec3(0.0f, 0.0f, -10.0f));
	model = glm::rotate(model, glm::radians(0.0f), glm::vec3(0.0f, 1.0f, 0.0f));

	s_pWindowManager->m_ShaderProgram->UsePrograma();
	s_pWindowManager->m_ShaderProgram->SetMat4("view", view);
	s_pWindowManager->m_ShaderProgram->SetMat4("projection", projection);
	s_pWindowManager->m_ShaderProgram->SetMat4("model", model);
	s_pWindowManager->m_CubeObject->Draw(s_pWindowManager->m_ShaderProgram);

	s_pWindowManager->m_FrameBuffer->Unbind();

	
	ImGui::PopStyleVar();
	
	ImGui::End();
}

**Comment by ocornut** [comment]
Hello,
What is this for?
