### ISSUE TITLE
How do I make ImGui menu movable at the same time as I control a game?

### ISSUE THREAD

**Issue by Tescoo** [ocornut/imgui#3525]
Hi,
So im using this code to make a virtual cursor:

ImGui::GetOverlayDrawList()->AddRectFilled(ImGui::GetIO().MousePos, ImVec2(ImGui::GetIO().MousePos.x + 5.f, ImGui::GetIO().MousePos.y + 5.f), ImColor(255, 255, 255));

and im using code to hide it, but i want to be able to control the game/application at the same time as the menu, EG, if im controling the menu with the cursor, i want the game camera to also move, not sure if its possible with imgui but if it is, let me know.
thanks, Tescoo

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
