### ISSUE TITLE
ImGui::ListBox is rendering other listboxes inside of each other

### ISSUE THREAD

**Issue by Bizzie2k** [ocornut/imgui#3526]
Version: 1.78 WIP

Back-ends: imgui_impl_dx9.h + imgui_impl_win32.h
Compiler: Visual Studio 2019, using v142 build tools. _(if the question is related to building or platform specific features)_
Operating System: Windows 10

Issue: When trying to render a listbox from another listbox (i.e. if the user selects one option on a listbox, render another listbox below it), the new listbox will become a part of the old one, however any features under the listbox will fit as though the listbox had its own area.

Without selecting any options (normal): 
![Capture](https://user-images.githubusercontent.com/68201998/95806908-84752c80-0cce-11eb-9547-27e0761678ce.PNG)
With selecting an option to attempt to render a new listbox (abnormal): 
![Capture1](https://user-images.githubusercontent.com/68201998/95806945-98b92980-0cce-11eb-84ed-4e901b740955.PNG)

```
static int selectedItemArray = 0;
static const char* items[]{ "Please select one:", "Primary", "Secondary", "Knives" };
static int PrimarySelected = 0;
static const char* PrimaryItems[]{ "Please select one:",
                                        "This would be a big array nobody would want to see" };

ImGui::ListBox("", &selectedItemArray, items, IM_ARRAYSIZE(items));
        switch (selectedItemArray) {
        case 0:
            break;
        case 1:
            ImGui::ListBox("", &PrimarySelected, PrimaryItems, IM_ARRAYSIZE(PrimaryItems));
            break;
        }
```

Used to work fine and the way it was intended, but apparently I messed something up by adding a float slider under it (which I removed, still wont render as intended) and now it gives me this issue. Any help would be appreciated.

**Comment by Bizzie2k** [comment]
The issue fix: I needed to add names to the other list boxes.

**Comment by ocornut** [comment]
Please read the FAQ!
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md
