### ISSUE TITLE
ListBox and Buttons: alignment (in the same line) ListBox elements and Buttons

### ISSUE THREAD

**Issue by pablocamacho** [ocornut/imgui#3531]
**Version/Branch of Dear ImGui: I have no problem with the version/branch of ImGui. I will use whichever you recommend to me as the best. But my requirement is to use the most modern C++ version. I am using ImGui alongside with SFML (just because the examples which I have found to start with included SFML).

Back-ends: [Do not know what do you expect exactly here. But I need pure C++ / pure ImGui (maybe, plus SFML).
Compiler: g++-10
Operating System: Ubuntu 20.04

**My Issue/Question: I have a requirement with the following topics:
1) populating a ListBox from a vector (which I have already found responded in your documentation).
2) Additionally, I need to add a Button to each line of the ListBox. I tried to solve this in the following way:
a) I created the ListBox (with the default font & font-size)
b) I setup columns
c) I put the buttons in the second column, as you can see in the below picture:

![image](https://user-images.githubusercontent.com/15177220/96096849-e6cc5980-0e95-11eb-8df6-e52a81ccef80.png)

As you can see, the Buttons are not aligned with the lines in the ListBox.
I was trying:
a) To increase the size-font. But I got the default font (horrible) distorted.
b) To change the font-type. But I understand this will change the font for the entire application (Am I correct?)
BUT, in whichever of both below scenarios, I need to manually correct / adjust the alignment of each line in the ListBox with the corresponding Button.
And I have to prevent the possibility of an unknown amount of elements in the ListBox. Consequence: great misalignment!
Maybe, I can provide manually aligned pairs of "one element in the list" with each corresponding Button, for a limited set of elements in the ListBox, but not for whichever amount of them.

My questions:
Is there a way to have this "automatically" configured? I mean (for instance):
a) having the Buttons inside the ListBox (mmm, sounds strange, right...? Like having 2 ListBox in parallel (in different columns, one ListBox with elements, and the other with Buttons... Of course, I understand that Buttons are controls and most probably will not work as such inside a ListBox with is another control, but just the display text... Even this text can be selected, my requirement specifies providing the functionality with Buttons).
b) Using another container different than a ListBox (some kind of grid...)
c) Maybe...(?) having a formula to calculate the line spacing among the elements in the ListBox and translating those positions to the Buttons. (Are the line spacing inside a ListBox modifiable?)
[Note: I found "disturbing" the controls' names displayed in the output. That is why I replaced them with dots (for instance). Is there a way to print them out in the background color, for instance? (Or, even better, not having them printed at all in the output?)].

Finally: another solution to have each Button on the exact line of each corresponding element in the ListBox?

Thanks in advance for your help!!

**Comment by ocornut** [comment]
You can use SmallButton or push a FramePadding of zero into the style before using Button.

ListBox are just child window... they can contains anything you want, use ListBoxHeader/Footer and inside the listbox you can create columns or add multiple items if you need. Please spent some time reading the ListBox function code and you’ll understand you can do anything with it.

**Comment by ocornut** [comment]
About the empty control names and you using a “.” instead, please read the FAQ as instructed in about one million locations including the Issue Template.

**Comment by pablocamacho** [comment]
Thanks, very much!!
