### ISSUE TITLE
Columns ignore CollapsingHeader

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#354]
I have 3 columns, a collapsing header and then 4 columns (as can be seen in the attached screenshot)

```cpp 
 ImGui::CollapsingHeader("CPU");
 ....
 ImGui::Columns(3);
 ...
 ImGui::Columns(1);
 ...
 ImGui::CollapsingHeader("Resources");
 ....
 ImGui::Columns(4);
 ...
 ImGui::Columns(1);
 ...
```

When I resize columns in the "CPU" section, columns in the "Resource" section are resized too. It asserts if I try to resize the fourth column. I tried to put the columns in children, however then one child takes the whole available area of the window.

![image](https://cloud.githubusercontent.com/assets/153526/10177279/a7382540-66f9-11e5-95d3-ef767b6bd9cc.png)

**Comment by ocornut** [comment]
You need to pass an identifier to your Columns set to differentiate them, else they share the same columns data. (perhaps I should forbid the empty second parameter to Columns() ?)

> I tried to put the columns in children, however then one child takes the whole available area of the window.

Not sure to understand, could you clarify?

**Comment by nem0** [comment]
It works fine when an identifier is passed to columns, thank you. I should have noticed the second parameter, my bad.

I do not use default values for parameters, because I got burned several times by them. But that's just personal preference. 

I meant this:
![image](https://cloud.githubusercontent.com/assets/153526/10178136/3a23ec50-66fe-11e5-92ba-ea06de448e0f.png)
Of course that's correct behaviour.

**Comment by ocornut** [comment]
ImGui relies on many useful default parameters but this particular one has been bothering a few time so I may actually remove it.

Still not sure what functions you are calling with the children/column thing to tell what's correct behaviour :)

**Comment by nem0** [comment]
It was something like 

```cpp
 if(ImGui::CollapsingHeader...
 {
  if(ImGui::BeginChild(...
  {
    ImGui::Columns(3);
    ...
    ImGui::Columns(1);
  }
  ImGui::EndChild();
 }

 if(ImGui::CollapsingHeader...
 {
  if(ImGui::BeginChild(...
  {
    ImGui::Columns(4);
    ...
    ImGui::Columns(1);
  }
  ImGui::EndChild();
 }
```

**Comment by ocornut** [comment]
> however then one child takes the whole available area of the window.

When calling BeginChild() you can specify size on each separate axis.

```
  w < 0.0f  >> right - w (align to right side)
  w = 0.0f  >> right (fill)
  w > 0.0f  >> cur_x + w (specify width)
```
That for both axis.

It may not make sense it, but typically you can something like (0.0f, height)

**Comment by nem0** [comment]
Yes, but that's only useful if I know height. Of course In my case I can compute it, but that is not always possible.

**Comment by ocornut** [comment]
Yeah but the point of child is generally to benefit from a scrolling region, but you can arbitrarily restrict height and vertically scroll within.

**Comment by nem0** [comment]
I understand, that's why I called it correct behaviour.

**Comment by ocornut** [comment]
All good then :+1: 

I'll investigate the default Columns parameter shortly.
