### ISSUE TITLE
How to set the width of a combo box to the width of the largest selection?

### ISSUE THREAD

**Issue by FractalMatt** [ocornut/imgui#3545]
This post has instructions for how to set the width of the combo box:
https://github.com/ocornut/imgui/issues/2691

Is it possible to instead set it's width to the size of the longest selectable item? Or even better for my specific use case: automatically shrink to fit the selected item. 

Doesn't seem like an available combobox option, I could manually change this width.. is it possible to know what the width of the item is? Seems like if I manually set numbers, then I change the font then all the widths will change which would be a pain.

**Comment by ocornut** [comment]
> Is it possible to instead set it's width to the size of the longest selectable item? Or even better for my specific use case: automatically shrink to fit the selected item.

That sounds extremely odd to me as it means your combo frame will resize according to its preview/selected value.

> is it possible to know what the width of the item is?

The preview text is a parameter of the `BeginCombo()` function so it is literally text that you are passing to it. 
So you can use `CalcTextSize(preview_text).x + style.FramePadding.x * 2.0f` to get a suitable width..

> Seems like if I manually set numbers, then I change the font then all the widths will change which would be a pain.

Every value should be factors of e.g. FontSize or other base..

PS: Please fill the requested template when opening issues.

**Comment by FractalMatt** [comment]
Sorry, will use template in the future.  Thanks ocornut, looks like what I want. One thing that does not account for: the size of the arrow to the right of the combo box. Is it possible to determine that width?

I know it's weird, trying to compress the width of rows as they are a little long and shortening them allows me to fit more, very specific to my use case.  Creating a new programming language that uses ImGui to create a 'block' language.. but fully typed.  So line widths don't benefit from extra padding.

Loving Dear ImGui, so much easier to work with than the last couple libraries I tried :)

**Comment by ocornut** [comment]
> One thing that does not account for: the size of the arrow to the right of the combo box. Is it possible to determine that width?

Look at the sources. The square items are GetTextLineWithPadding() on each axis.

Thank you!

**Comment by FractalMatt** [comment]
I have been looking through source a lot, it is nice how much of it there is in terms of examples.

For anyone else who stumbles across this: ImGui::GetTextLineHeightWithSpacing() is the instruction.  Thanks again ocornut.

**Comment by Argie-Daios** [comment]
You can use 
ImGui::Columns(2);
ImGui::SetColumnWidth(0, width);
ImGui::Text(text);
ImGui::NextColumn();
ImGui::SetColumnWidth(1, width2);

And then you begin your combo
