### ISSUE TITLE
ImGui muitiple OpenGL window

### ISSUE THREAD

**Issue by potentialee** [ocornut/imgui#3547]
![1212](https://user-images.githubusercontent.com/46181310/96534750-5180f900-12cb-11eb-84bb-4ead10b19834.png)

Hello, thank you for reading this.
I am developing GUI program like that above.
my problem is, making a multiple OpenGL window. i have one OpenGL window already left of uploaded image. (stream data)
I know that i have to use OpenGL texture to use ImGui OpenGL window.
so I made another class of handling OpenGL model loading and FBO to texture like this.

SMCShaderProgram* shaderProgram;
modelLoading* patient;

and i gave OpenGL texture made by model loading class to ImGui function, Imgui::image.
but i found that all ImGui window is gone. (error)

![example12](https://user-images.githubusercontent.com/46181310/96536328-c43fa380-12ce-11eb-8328-e8b5a68ae047.JPG)

is this because collision of OpenGL buffer transfer sequence (with another opengl window) or ImGui context?
or i need to make new OpenGL window and change the context for that?

thank you for reading

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
