### ISSUE TITLE
Does Dx11 not work because I need to install any support libraries?

### ISSUE THREAD

**Issue by liketheicymoon** [ocornut/imgui#3551]
I have DirectX version 11 on Windows, but Imgui dx11 version does not work, is there a support library I need to install? I am Windows 7.
![GIF](https://user-images.githubusercontent.com/73206218/96664492-749abf80-1342-11eb-9e05-2f123cf01de4.gif)

**Comment by ocornut** [comment]
It depends which compiler/settings were used.

**Comment by ocornut** [comment]
Can you run the DX11 exe from http://www.dearimgui.org/binaries/imgui-demo-binaries-20200918.zip ?

PS: Please fill the requested Issue Template form when opening an issue.

**Comment by liketheicymoon** [comment]
> 这取决于所使用的编译器/设置。

Okay, how do I go about setting up my compiler settings?

**Comment by liketheicymoon** [comment]
> 您可以从http://www.dearimgui.org/binaries/imgui-demo-binaries-20200918.zip运行DX11 exe吗？
> 
> PS：打开问题时，请填写要求的问题模板表格。

Yes,can.

**Comment by ocornut** [comment]
Then your question is not a Dear ImGui problem.

> Okay, how do I go about setting up my compiler settings?

Maybe search about for Windows 7 compatibility with recent Visual Studio compiler versions.

**Comment by liketheicymoon** [comment]
> 那么您的问题不是亲爱的ImGui问题。
> 
> > 好的，我该如何设置我的编译器设置？
> 
> 也许搜索Windows 7与最新Visual Studio编译器版本的兼容性。

Have you done anything to your compiler? Or are you using an older version?

**Comment by liketheicymoon** [comment]
> 那么您的问题不是亲爱的ImGui问题。
> 
> > 好的，我该如何设置我的编译器设置？
> 
> 也许搜索Windows 7与最新Visual Studio编译器版本的兼容性。

I want to know what settings you have changed or what compiler you are using, because mine will work on some Windows 7 and some will not, but yours will work on my non-running Windows 7.

**Comment by thedmd** [comment]
`example_win32_directx11` relies on `D3DCompiler_43.dll`. On Windows 7 you can get it from [old DX redistributable](https://www.microsoft.com/en-us/download/confirmation.aspx?id=35). This DLL also come with Windows 8 SDK or newer.
