### ISSUE TITLE
imgui_impl_metal: cmd-Q doesn't quit if text input is active

### ISSUE THREAD

**Issue by lfnoise** [ocornut/imgui#3554]
Version: 1.80 WIP (17905)
Branch: master
Back-ends: imgui_impl_metal.mm + imgui_impl_osx.mm
Compiler: clang/Xcode
Operating System: macos 10.15.4

In the apple metal demo app, if a text field is active, cmd-Q will not quit the app.
This works fine with the apple opengl2 back end.

To reproduce: 
1. build example/example_apple_metal, target: example_apple_metal_macos
2. launch, go to demo window/Widgets/Text Input/Multi-line Text Input
3. click in the text input box.
4. press cmd-Q
5. doesn't quit.

Do the same in the apple opengl2 example, and it does quit.

There's one other issue, which is that this line in imgui_impl_osx.mm:
```io.KeyMap[ImGuiKey_KeyPadEnter]     = 13;```
should be:
```io.KeyMap[ImGuiKey_KeyPadEnter]     = 3;```
Otherwise, pressing key pad enter doesn't do anything.

**Comment by ocornut** [comment]
Thank you @lfnoise for reporting this.

- We've fixed Keypad Enter mapping.
- We've also fixed the examples not forwarding inputs down. The code in Apple+Metal example was attempting to use the return value from `ImGui_ImplOSX_HandleEvent()` but at it happens, this value is not really useful for various reasons. Forwarding all inputs down to OS layer matches the behavior of other back-ends and is preferable for now.
