### ISSUE TITLE
UTF8 Chinese & Japanese text can't display normally (1.80WIP)

### ISSUE THREAD

**Issue by Demonese** [ocornut/imgui#3558]
**Version/Branch of Dear ImGui:**

Version: 1.80WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: any
Operating System: any

**My Issue/Question:**

UTF8 Chinese & Japanese text can't display normally.
I try different fonts (wenquanyi, Microsoft YaHei, Source Han Sans), but It doesn't work.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/57629614/97107518-015aca00-1703-11eb-99a9-98c2e79a5fdb.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```C++
ImFontConfig cfg;
cfg.OversampleH = 1;
static ImFontGlyphRangesBuilder range;
range.Clear();
static ImVector<ImWchar> gr;
gr.clear();
range.AddRanges(ImGui::GetIO().Fonts->GetGlyphRangesChineseFull());
range.AddRanges(ImGui::GetIO().Fonts->GetGlyphRangesJapanese());
range.BuildRanges(&gr);
ImGui::GetIO().Fonts->AddFontFromFileTTF("wqy-zenhei.ttc", 16.0f, &cfg, gr.Data);
```
```C++
ImGui::Text(u8"中文测试：你好，Dear-ImGui。");
ImGui::Text(u8"日本語テスト:こんにちは、Dear-ImGui。");
```

**Comment by Demonese** [comment]
I found something that confused:
Character "中" is convert to 20013 but "文" is convert to 65533.
![image](https://user-images.githubusercontent.com/57629614/97108311-aecfdc80-1707-11eb-88a8-10c6aa759e5b.png)
![image](https://user-images.githubusercontent.com/57629614/97108330-ceff9b80-1707-11eb-8ab0-10e8470419e1.png)

**Comment by ocornut** [comment]
Hello,
Thanks for reporting.
I can confirm there was a bug/regression added by the very last commit b3576dd35409a3a3ad742bb74122e14fcda2d886, pushed 2 days ago. (cc @rokups)
Looking at it.

**Comment by ocornut** [comment]
Reverted the commit as changes to the decoder broke it. Should be fixed now. Apologies for the regression!
