### ISSUE TITLE
window opened with button closes instantly

### ISSUE THREAD

**Issue by iLostMyXbox21** [ocornut/imgui#3559]
**Version/Branch of Dear ImGui:**

Version: 1.69 i believe
Branch: not sure

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.h, imgui_impl_dx9.h

**My Issue/Question:**

I am trying to make a button create a new window (kind of like how the demo project has, and yes i read the demo project and even when copy pasting from there it still did not work. The window opens for a split second then closes. holding the button does nothing, and when i use a checkbox and check if window_open = true it will force the checkbox back to false

if (ImGui::Button("Open Test Window")
{
ㅤㅤㅤㅤImGui::Begin("Test Window");
      ImGui::Text("works!");
      ImGui::End();
}

**Screenshots/Video**

None

**Additional Notes**
Apologies if i did not format something correctly or if this questions is batshit stupid. I have been looking for a fix for going on 2 days and cannot find one

**Comment by phicore** [comment]
Alert! ImgGui paradigm misconception....

**Comment by ocornut** [comment]
Hello,

@iLostMyXbox21, none of the demo code does what you are doing here.

Your code is executed every frame. `Button()` returns true ON THE FRAME it was clicked. So this is like an event polling. If you want this event to modify state that will dictate of the visibility of another window, you need to store that visibility (as e.g. a bool) somewhere and modify that on the button press. Otherwise your Begin/Text/End code will only execute a single time during the frame the button is pressed.

**Comment by iLostMyXbox21** [comment]
hi @ocornut thanks for the reply, 

thank you for informing me that a button only works on the frame it is clicked on. not sure if i missed where it says that or if my mind did not process that. i did try to use a checkbox yesterday but it was forcing the value to be false. Idk if i found the exact issue but i did fix it. so now my window opens with the press of a checkbox

thank you for the help mr ocornut. i will close this issue now that we have fixed the problem

**Comment by iamthebest77** [comment]
@iLostMyXbox21 I have a similar requirement as yours. Below is my code but it is not showing any window. Can you please help me out with this.
if(ImGui::IsWindowHovered(0) && ImGui::IsMouseClicked(ImGuiMouseButton_Left)) 
    {
        ImGui::Text("%d", ImGui::IsMouseClicked(0));
        
        m_keypad.showKeypadWindow = true;

        while(m_keypad.showKeypadWindow)
            m_keypad.showKeypad();
}

If I remove the while loop and just call the m_keypad.showKeypad(); function, then the keypad window appears momentarily.
