### ISSUE TITLE
This is a message for owner (forgot how to spell his name)

### ISSUE THREAD

**Issue by Dubhghallf** [ocornut/imgui#3561]
Can I please be unbanned on the discord, I was banned for tagging people and asking them questions I didn’t read the rules but now I have matured more and i will not do this again please unban me my discord name is q5a#4425 or q5a#6258 can’t remember maybe it’s something like that but it’s definitely q5a

Thanks for taking your time to read this please consider it.

**Comment by ocornut** [comment]
@Dubhghallf You were now unbanned. Please do carefully follow on the rules in the future if you want to participate, thank you.
