### ISSUE TITLE
Remove default tree node spacing

### ISSUE THREAD

**Issue by OverShifted** [ocornut/imgui#3567]
__new (edited) question:__
Hello everyone.
I want to get rid of the default spacing between tree nodes.
I am using an invisible button between nodes to set item order using drag and drop API.
But there is a lot of spacing between nodes which is annoying.
How can I disable that?

__old question:__
Hello everyone.
I want to have a `DragDropTarget` on an invisible element.
I tried this
```c++
ImGui::Dummy({ -1, 5 });
//ImGui::TextUnformatted("Hello");

if (ImGui::BeginDragDropTarget())
{
	if (const ImGuiPayload* payload = ImGui::AcceptDragDropPayload("_SCENE_HIERARCHY_ENTITY_DRAG"))
	{
		// Do something
	}
	ImGui::EndDragDropTarget();
}
```
a little white space is visible but I can't drop other `_SCENE_HIERARCHY_ENTITY_DRAG` payloads on it.
when I replace `Dummy` with `TextUnformatted`; everything is fine.
how can I set up an invisible "Drop-able" (`DragDropTarget`) widget?

**Comment by sonoro1234** [comment]
InvisibleButton?

**Comment by OverShifted** [comment]
Any invisable thing is acceptable.
I have a scene hierarchy in my game engine's editor.
right now I can use drag n drop to parent entities together.
But I wanna use drag n drop to also set child order. (just like unity and any other software with this feature)
I saw some thing in DemoWindow but I think it will become confusing when we are also using drag-drop for parenting.

**Comment by OverShifted** [comment]
But how to get rid of the default margin between tree nodes?

**Comment by OverShifted** [comment]
Fixed: 
```cpp
ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, { 0.0f, 0.0f });
bool nodeIsOpen = ImGui::TreeNodeBehavior(ImGui::GetCurrentWindow()->GetID((void*)(intptr_t)(entity.GetRuntimeID())), nodeFlags, name);
ImGui::PopStyleVar();
```

**Comment by ocornut** [comment]
One of the experiment we did was to allow for explicit "in between" drag targets for reordering, one of the issue being that calling that api would be quite cumbersome, but I don't see a way out.

![image](https://user-images.githubusercontent.com/8225057/98119751-563dd380-1ead-11eb-89fb-c78a812c09f6.png)

**Comment by OverShifted** [comment]
I think it's too late.
Is there any way to get source code for this experiment?

**Comment by rokups** [comment]
You can find it at https://github.com/rokups/imgui/tree/reorder-api

**Comment by OverShifted** [comment]
Thank you.
I found it here [https://github.com/rokups/imgui/blob/reorder-api/imgui_demo.cpp#L2052](https://github.com/rokups/imgui/blob/reorder-api/imgui_demo.cpp#L2052)
