### ISSUE TITLE
I try to write a safer win32 implement for some "working thread" + "Window GUI thread" applications and games.

### ISSUE THREAD

**Issue by Demonese** [ocornut/imgui#3569]
**Version/Branch of Dear ImGui:**

Version: 1.80 (WIP) (17905)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32_workingthread [(this is my fork)](https://github.com/Demonese/imgui)
Compiler: VS2019
Operating System: Windows 10 20H2

**My Issue/Question:**

My application using a "working thread" + "Window GUI thread" model so the default imgui_impl_win32 may behave in strange ways.
I try to write a safer implement and it works well but still lacks testing. I'm not sure if it has any other bugs.

**Screenshots/Video**

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

**Comment by Demonese** [comment]
Nice, I think it's stable enough (at least it works on "GUI thread" & "working thread" Windows application).
![image](https://user-images.githubusercontent.com/57629614/97892702-52a23380-1d6b-11eb-861c-72670ac92e7e.png)
* API set
![image](https://user-images.githubusercontent.com/57629614/97893297-11f6ea00-1d6c-11eb-95c2-dd95c43245f7.png)
* mouse capture
![1](https://user-images.githubusercontent.com/57629614/97894740-d52bf280-1d6d-11eb-8da5-c29dfa22cb14.gif)
* mouse cursor
_My GIF recorder can't record mouse cursor, I'm sorry. But the mouse cursor change has no problem._
* set mouse position
_My GIF recorder can't record mouse cursor, I'm sorry. But the mouse position change has no problem._
![1](https://user-images.githubusercontent.com/57629614/97895439-c0039380-1d6e-11eb-841e-bb9b2af17e45.gif)
* IME candidate list position
![1](https://user-images.githubusercontent.com/57629614/97895313-977b9980-1d6e-11eb-8a94-29fc1dd1be40.gif)

**Comment by Demonese** [comment]
OHHHH!
I'm so happy! Now it works on LuaSTG plus engine (a small 2D bullet hell game engine)!
LuaSTG plus using "GUI thread" + "working thread" model but imgui_impl_win32 not available (has many bugs).
[LuaSTGPlus engine](https://github.com/9chu/LuaSTGPlus)
I will continue to test this implement, thanks to ocornut's dear-imgui!
![image](https://user-images.githubusercontent.com/57629614/97949179-c2e1a100-1dcd-11eb-8188-63eddcd6fbaa.png)

**Comment by heroboy** [comment]
I see your code. I find you create d3d context in working thread, rendering in working thread. But the window is created in gui thread. Is it good and safe and have good performance?
In my opinions the "working thread" + "gui thread" should be like the remote branch of imgui, but in the same process. The whole 'imgui' is living in the working thread, and send the draw data to the gui thread. And the backend is living in the gui thread, and send the user interactive messages to the working thread.

**Comment by Demonese** [comment]
> I see your code. I find you create d3d context in working thread, rendering in working thread. But the window is created in gui thread. Is it good and safe and have good performance?
> In my opinions the "working thread" + "gui thread" should be like the remote branch of imgui, but in the same process. The whole 'imgui' is living in the working thread, and send the draw data to the gui thread. And the backend is living in the gui thread, and send the user interactive messages to the working thread.

Win32 "GUI thread" is the thread create window and process window messages. I didn't need to draw imgui in "GUI thread" because we have d3d and imgui didn't support GDI.

**Comment by Demonese** [comment]
> I see your code. I find you create d3d context in working thread, rendering in working thread. But the window is created in gui thread. Is it good and safe and have good performance?
> In my opinions the "working thread" + "gui thread" should be like the remote branch of imgui, but in the same process. The whole 'imgui' is living in the working thread, and send the draw data to the gui thread. And the backend is living in the gui thread, and send the user interactive messages to the working thread.

I think it's safe enough, but the performance will not increase. Now we can resize window or drag move window and "GUI thread" will not block "working thread". This is the only one benifitial, I think. (In fact I just want to embed imgui into LuaSTG plus engine.)
