### ISSUE TITLE
Drawing HBITMAP with Image/AddImage

### ISSUE THREAD

**Issue by mhooITU** [ocornut/imgui#3570]
**Version/Branch of Dear ImGui:**

Version: latest

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx12.cpp
Operating System: Win10

**My Issue/Question:**

Trying to follow https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#Example-for-DirectX12-users
I'm using example https://github.com/ocornut/imgui/tree/master/examples/example_win32_directx12

Trying to load a 200x200 HBITMAP "image" I've created by capturing a part of my screen .

However, I'm crashing at this line:
```cpp
for (int y = 0; y < image_height; y++) { // CRASHES AT y = 2
        memcpy((void*)((uintptr_t)mapped + y * uploadPitch), image_data + y * image_width * 4, image_width * 4);
    }
```
Provided from the image loading example.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
Use the two examples with this HBITMAP:
```cpp
// get the device context of the screen
		//HDC hScreenDC = CreateDC(L"DISPLAY", NULL, NULL, NULL);
		HDC hScreenDC = GetDC(g_HWND);
		// and a device context to put it in
		HDC hMemoryDC = CreateCompatibleDC(hScreenDC);

		//int width = GetDeviceCaps(hScreenDC, HORZRES);
		//int height = GetDeviceCaps(hScreenDC, VERTRES);

		// maybe worth checking these are positive values
		HBITMAP hBitmap = CreateCompatibleBitmap(hScreenDC, 200, 200);
		// get a new bitmap
		HBITMAP hOldBitmap = (HBITMAP)SelectObject(hMemoryDC, hBitmap);

		BitBlt(hMemoryDC, 5, 5, 200, 200, hScreenDC, 0, 0, SRCCOPY);
		hBitmap = (HBITMAP)SelectObject(hMemoryDC, hOldBitmap);
		hBitmapRadar = hBitmap;
		hBitmapRadarDC = hMemoryDC;


		//OpenClipboard(NULL);
		//EmptyClipboard();
		//SetClipboardData(CF_BITMAP, hBitmap);
		//CloseClipboard();
		// clean up
		//DeleteDC(hMemoryDC);
		DeleteObject(hOldBitmap);
		DeleteDC(hScreenDC);
```
Among other things, I have tried to convert the bitmap to `unsigned char * image_data`. This way (I believe this might be the issue):
```cpp
// Load from disk into a raw RGBA buffer
    int image_width = 200;
    int image_height = 200;
    unsigned char* image_data;
    BITMAPINFO bmpInfo;
    memset(&bmpInfo, 0, sizeof(BITMAPINFOHEADER));
    bmpInfo.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    GetDIBits(hBitmapRadarDC, hBitmapRadar, 0, 0, NULL, &bmpInfo, DIB_RGB_COLORS);
    bmpInfo.bmiHeader.biBitCount = 32;
    bmpInfo.bmiHeader.biCompression = BI_RGB;

    GetDIBits(hBitmapRadarDC, hBitmapRadar, 0, bmpInfo.bmiHeader.biHeight, &image_data, &bmpInfo, DIB_RGB_COLORS);
```

Love Dear ImGui so far BTW 👍  
Thanks.

**Comment by ocornut** [comment]
Sorry but this has nothing to do with dear imgui or with that texture loading tutorial. I’ll let you find the bugs in your code.
