### ISSUE TITLE
Change Button name when the user click on it

### ISSUE THREAD

**Issue by pablocamacho** [ocornut/imgui#3571]
**Version/Branch of Dear ImGui:**

Version: N / A 
Branch: N / A

**Back-end/Renderer/Compiler/OS**:  I am using ImGui with SFML

Back-ends: N / A
Compiler: g++-10
Operating System: Ubuntu 20.04

**My Issue/Question:**
I have a button named "Download".
I want to change its name to "Pause", when the user clicks on it.
And, then, I want to change its name to "Resume", when the user clicks on it again.
In such a way that the button displayed name shows always the next action the user can use the button for.
In the below snippet I have "mimic" the behaviour with a counter: after some frames, the button name changes.
Could you please let me know if this is a good implementation?

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
(...)
    long counter = 0;
    int flag = 0; // flag for 3 states: Download, Pause, Resume
    while (window.isOpen())
    {
       (...)
               ++counter;
               const char* ButtonName = "Download";
       (...)
       ImGui::InputText("##InputText3", LabelText, 10); // This names a label LabelText = "Action to take...";
        if( counter >= 200 ) flag = 1;
        if( counter >= 400 ) flag = 2;
        if( 1 == flag )
        {
           name = const_cast <const char*>(name);
           name = "Pause";
           name = const_cast <const char*>(name);
        }
        if( 2 == flag )
        {
           name = const_cast <const char*>(name);
           name = "Resume";
           name = const_cast <const char*>(name);
        }
       if (ImGui::Button( ButtonName ))
       {
           // Action to take according to the value of flag variable
       }
      (...)

ImGui::SFML::Shutdown();
```
The code is working and I am able to rename the button.
However, as mentioned before, I don't know if it's a "hair-raising" implementation or if it's a reasonable one.

SECOND QUESTION: In a previous question, you advise me to use "small buttons". But I was not able to find out an implementation of "small buttons" in ImGui.

Could you please advise on this?

Thanks in advance!

**Comment by ocornut** [comment]
Please ask for Discord for general programming advices.

Additionally: you should want to use the ### id operator (see FAQ) to make your three labels use the same underlying ID. It won’t make a difference when using the mouse but for gamepad/keyboard you’d want your focus to stay on the button as it renames.
