### ISSUE TITLE
How Do You Get Rid Of The Grey Backround In ImGui?

### ISSUE THREAD

**Issue by TrotzeyOnPC** [ocornut/imgui#3574]
Hello, I Was wondering how do you get rid of the grey backround. the 'grey backround' im talking about is when you first start up the ImGui example.exe and then it starts the window with a backround, please tell me how to get rid of this backround!
Thanks!

**Comment by phicore** [comment]
On behalf of ocornut I would say: "Sorry but #1586"

**Comment by TrotzeyOnPC** [comment]
> On behalf of ocornut I would say: "Sorry but #1586"

Im not 'cheating' or gamehacking, im just messing about coding and came about this cool framework GUI. all i want to know is how to get rid of the backround when you first start up the app?

**Comment by ocornut** [comment]
- Didn't follow requested guidelines or issue template. 
- Sorry but #1586.

Closing.
