### ISSUE TITLE
Assertion failed: g.IO.KeyMods with GLFW backend

### ISSUE THREAD

**Issue by michaelquigley** [ocornut/imgui#3575]
```
Dear ImGui 1.77 (17700)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1926
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

I'm running into something that I can't seem to get to the bottom of, and I'm hoping you can help. I'm using a framework on top of ImGui, which implements key bindings and actions. I'm running into a situation where when I execute an action from a key binding, and then I launch a native file dialog, I'm running into an assert in ImGui when the dialog returns control back to ImGui.

I get the following assert:

```
Assertion failed: g.IO.KeyMods == expected_key_mod_flags && "Mismatching io.KeyCtrl/io.KeyShift/io.KeyAlt/io.KeySuper vs io.KeyMods", file ..\imgui\imgui.cpp, line 6765
```

My code is structured like this:

```
inline void host::draw(const ImVec2& size) {
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    _app->draw(ImGui::GetIO().DisplaySize);
    _app->respond();

    ImGui::Render();
    glViewport(0, 0, size.x, size.y);
    glClearColor(_bg.x, _bg.y, _bg.z, _bg.w);
    glClear(GL_COLOR_BUFFER_BIT);
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    glfwSwapBuffers(_window);
}

void workspace_app::respond() {
    auto io = ImGui::GetIO();
    if(!io.WantCaptureKeyboard) {
        for(const auto& action : _actions) {
            if(action->triggered(io)) {
                action->execute();
                return;
            }
        }
    }
}

bool action::triggered(const ImGuiIO& io) const {
    return _key_binding->triggered(io);
}

bool key_binding::triggered(const ImGuiIO& io) const {
    return (io.KeyCtrl == ctrl && io.KeyAlt == alt && io.KeyShift == shift && ImGui::IsKeyPressed(key));
}
```

The `workspace_app::respond` is the concrete overload responding to the `_app->respond()` line in `host::draw` above. 

When I invoke this same code path through clicking on a user interface element, the code path works perfectly. It only triggers this assert when I use the keyboard shortcut (`CTRL-S`) in my case, to invoke the code path. If I change my keyboard shortcut to just `S` instead of `CTRL-S`, it also works perfectly. It only seems to hit this assert when modifier keys are involved.

Any insight would be very appreciated.

**Comment by ocornut** [comment]
Hello,

The assert generally triggers when you have code modifying the `io.KeyCtrl` `io.KeyAlt` or `io.KeyShift` modifiers after `ImGui::NewFrame()`. I think you should search in your codebase for such modifications.

**Comment by ocornut** [comment]
Note the comment exactly above this assert:
```cpp
// Verify that io.KeyXXX fields haven't been tampered with. Key mods should not be modified between NewFrame() and EndFrame()
// One possible reason leading to this assert is that your backends update inputs _AFTER_ NewFrame().
const ImGuiKeyModFlags expected_key_mod_flags = GetMergedKeyModFlags();
IM_ASSERT(g.IO.KeyMods == expected_key_mod_flags && "Mismatching io.KeyCtrl/io.KeyShift/io.KeyAlt/io.KeySuper vs io.KeyMods");
```

**Comment by michaelquigley** [comment]
Yes. I already saw that. But my code does is not directly modify those values at all. That was the first thing I looked for.

**Comment by michaelquigley** [comment]
In fact, if I add:

```
        auto io = ImGui::GetIO();
        auto mods = io.KeyMods;
        ImGui::NewFrame();
```

and after my code:

```
        ImGui::GetIO().KeyMods = mods;
        ImGui::Render();
```

I still get the same assertion.

**Comment by ocornut** [comment]
Well, something does and it's not core imgui.
The only piece of code that you are running which intentionally write to `io.KeyXXX` are the key handlers in imgui_impl_glfw.cpp which are generally triggerd when your app calls `glfwPollEvents()`.

> Could something be occuring because the dialog is blocking this loop for a period of seconds (or more)?

Yes if you keep polling GLFW events, as stated above.

> I still get the same assertion.

Because that's making it wrong. If you move the first `mods = ` assignment after `ImGui::NewFrame()` that's a correct check.

**Comment by michaelquigley** [comment]
I don't see how anything in my code could be modifying `ImGui::GetI().KeyMods` with in the following block, yet the assert persists:

```
inline void host::draw(const ImVec2& size) {
    _size = size;

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();
    auto saved_mods = ImGui::GetIO().KeyMods;
    
    _app->draw(ImGui::GetIO().DisplaySize);
    _app->respond();

    ImGui::GetIO().KeyMods = saved_mods;
    ImGui::Render();
    glViewport(0, 0, size.x, size.y);
    glClearColor(_bg.x, _bg.y, _bg.z, _bg.w);
    glClear(GL_COLOR_BUFFER_BIT);
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    glfwSwapBuffers(_window);
}
```

**Comment by ocornut** [comment]
I gave you all the information you need to debug your issue. You can use printf or a debugger to track it down.

**Comment by michaelquigley** [comment]
The following code resolves the issue. I'll take it from here. Thank you.

```
inline void host::draw(const ImVec2& size) {
    _size = size;

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();
    auto saved_ctrl = ImGui::GetIO().KeyCtrl;
    auto saved_alt = ImGui::GetIO().KeyAlt;
    auto saved_shift = ImGui::GetIO().KeyShift;
    auto saved_super = ImGui::GetIO().KeySuper;

    _app->draw(ImGui::GetIO().DisplaySize);
    _app->respond();
 
    ImGui::GetIO().KeyCtrl = saved_ctrl;
    ImGui::GetIO().KeyAlt = saved_alt;
    ImGui::GetIO().KeyShift = saved_shift;
    ImGui::GetIO().KeySuper = saved_super;
    ImGui::Render();
    glViewport(0, 0, size.x, size.y);
    glClearColor(_bg.x, _bg.y, _bg.z, _bg.w);
    glClear(GL_COLOR_BUFFER_BIT);
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    glfwSwapBuffers(_window);
}
```

**Comment by michaelquigley** [comment]
(Also, thank you for the help... Surely you can understand how these things go. My code doesn't directly alter those values. There's got to be some kind of a compiler side effect or some minor mistake or something. And I'm kind of puzzled how this only happens in this one specific case... but yes, _you're right_, something is changing those fields between those 2 statements, and it's ultimately my problem... But thanks!)

**Comment by ocornut** [comment]
As a quick test,

I've tried today to use https://github.com/mlabbe/nativefiledialog to create a long blocking dialog in the middle of the Dear ImGui frame, calling it while modifiers were held, and tested this with GLFW, SDL and Win32 backends without a problem.

Maybe your and @str0yd app have some kind of reentrant/threaded code calling GLFW back-end events during the blocking call. I'm not sure.

**Comment by str0yd** [comment]
This is strange. I use my own key callback:

```
void key_callback(GLFWwindow* window, GLint key, GLint scancode, GLint action, GLint mode)
{
	if (!ImGui::GetIO().WantCaptureKeyboard) 
	{ // event not handled by gui
		if (key >= 0 && key < 1024)
		{
			if (action == GLFW_PRESS)
				sps_visual.keys[key] = GL_TRUE;
			else if (action == GLFW_RELEASE) {
				sps_visual.keys[key] = GL_FALSE;
				sps_visual.keys_processed[key] = GL_FALSE;
			}
		}
	}
}
```
I first set all my callbacks:
```
glfwSetKeyCallback(window, key_callback);
glfwSetCharModsCallback(window, char_callback);
glfwSetMouseButtonCallback(window, mouse_click_callback);
glfwSetScrollCallback(window, scroll_callback);
glfwSetCursorPosCallback(window, mouse_callback);
```
Then I initialize ImGui:
```
ImGui_ImplGlfw_InitForOpenGL(window, true);
```
Usually ImGui should call my own key callback function at the right time, shouldn't it?

I don't use the callbacks anywhere else.

Could it maybe be something with the Windows Openfile dialog? I use the GetOpenFileNameA function: https://docs.microsoft.com/en-us/windows/win32/api/commdlg/nf-commdlg-getopenfilenamea

**Comment by michaelquigley** [comment]
> 
> 
> As a quick test,
> 
> I've tried today to use https://github.com/mlabbe/nativefiledialog to create a long blocking dialog in the middle of the Dear ImGui frame, calling it while modifiers were held, and tested this with GLFW, SDL and Win32 backends without a problem.
> 
> Maybe your and @str0yd app have some kind of reentrant/threaded code calling GLFW back-end events during the blocking call. I'm not sure.

I definitely do not have any threaded or re-entrant code as part of my application, and certainly none that interact with GLFW directly.

I _do_ have a callback registered with GLFW to invoke my draw loop when the host window gets resized. That draw loop contains this code:

```
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplGlfw_NewFrame();
ImGui::NewFrame();

ImGuiIO& io = ImGui::GetIO();
auto saved_ctrl = io.KeyCtrl;
auto saved_alt = io.KeyAlt;
auto saved_shift = io.KeyShift;
auto saved_super = io.KeySuper;

// Application Drawing Here

io.KeyCtrl = saved_ctrl;
io.KeyAlt = saved_alt;
io.KeyShift = saved_shift;
io.KeySuper = saved_super;
ImGui::Render();
glViewport(0, 0, size.x, size.y);
glClearColor(_bg.x, _bg.y, _bg.z, _bg.w);
glClear(GL_COLOR_BUFFER_BIT);
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
glfwSwapBuffers(_window);
```

But I'm pretty sure that's not causing this issue.

I've left my workaround in place because it doesn't seem to be adversely affecting the behavior of any part of my application. I've been through my codebase extensively... there does not seem to be anything that's directly changing the state of any ImGui structures in any way. Reading them... extensively. Changing them... no.

**Comment by ocornut** [comment]
You know which function in the GLFW backends is altering the key mods so I am surprised you haven’t set breakpoints to figure out exactly what’s calling it and when.

**Comment by str0yd** [comment]
I had no time to test it yet, will do this tomorrow.

**Comment by str0yd** [comment]
I think the problem is in the ImGui_ImplGlfw_KeyCallback. I press "Ctrl + S" to quicksave my things. While pressing "Ctrl + S" the Windows file dialog opens. I relase "Ctrl + S" and choose a file. As soon as I leave the file dialog the Keykallback is triggered (I relased Ctrl and S) and resets the io.KeyCtrl. After resetting the program runs and ASSERTS
```
g.IO.KeyMods == expected_key_mod_flags // same as GetMergedKeyModFlags()
// g.IO.KeyMods is 1, expected_key_mod_flags  is 0
```
This evaluates FALSE because the ImGui_ImplGlfw_KeyCallback has already reset the Ctrl flag (g.IO.KeyMods is set at the beginning of the frame).

I think this is a bug beacause if you could press and release the Ctrl button in one frame you should also get this error message.

I'm not sure when exactly GLFW calls the kallback function. If it is periodically or inerrupting. But if I'm right with my theory here it should call the callback interrupting.

**Comment by ocornut** [comment]
> I'm not sure when exactly GLFW calls the kallback function

You can set a breakpoint to find out but I've also written it above. They are called when you call `glfwPollEvents()` and the point is your should not call `glfwPollEvents()` in the middle of an ImGui frame, so you should look at where you are calling it.

**Comment by michaelquigley** [comment]
> You can set a breakpoint to find out but I've also written it above. They are called when you call `glfwPollEvents()` and the point is your should not call `glfwPollEvents()` in the middle of an ImGui frame, so you should look at where you are calling it.

My code does not call `glfwPollEvents` anywhere, ever, between `ImGui::NewFrame` and `ImGui::Render`, and still has this issue.

**Comment by str0yd** [comment]
I'm debugging the code right now. My main loop calls the pollevents before any imgui stuff:
```
glfwPollEvents();

...

// initialize GUI for new frame
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplGlfw_NewFrame();
// draw GUI
ImGui::NewFrame();
// get all the gui stuff
VisualGui::getInstance().DrawGui();
// render the gui
ImGui::Render();
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

...
```
Here is a image of the callstack:
![grafik](https://user-images.githubusercontent.com/29361982/98833405-40e12000-243e-11eb-85f3-391a8623e866.png)
As you can see the breakpoint is in the ImGui_ImplGlfw_KeyCallback function. I come from extern code. The curser (green arrow) points in my function VisualGui::openFile. In this function the curser is in the
```
iResult = GetSaveFileNameA(&ofn);
```
Sooo it looks like the GetSaveFileNameA (a Windows function) calls the glfwPollEvents.

**Comment by michaelquigley** [comment]
> ```
> glfwPollEvents();
> 
> ...
> 
> // initialize GUI for new frame
> ImGui_ImplOpenGL3_NewFrame();
> ImGui_ImplGlfw_NewFrame();
> // draw GUI
> ImGui::NewFrame();
> // get all the gui stuff
> VisualGui::getInstance().DrawGui();
> // render the gui
> ImGui::Render();
> ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
> 
> ...
> ```
> 
> I do not call the pollEvents anywhere else in my program.

My code is structured exactly the same.

**Comment by ocornut** [comment]
I looked at GLFW codebase and at a first glance it seems like only the _glfwPlatformPollEvents() function dispatch win32 messages which turns into callback events.

I have created a minimum repro calling `GetSaveFileNameA()` in the middle of the dear imgui frame and couldn't get things to trigger.

As this point if you would like to correctly get to the end of this, could you try creating a minimum repro for it?

**Comment by michaelquigley** [comment]
I can probably put something together this weekend.

**Comment by ocornut** [comment]
So GLFW is clearing keyboard input when the windows loses focus, and with those native modal dialog the events are pushed mid-frame.

With the current direct-write to IO i don't have a super satisfying solution right now. When we transitioning to queuing events (e.g. https://gist.github.com/ocornut/8417344f3506790304742b07887adf9f) it'll be trivial.

Considering the nature of that mid-frame modification my suggested solution would be to make the assert more lenient by only asserting on mid-frame presses rather than mid-frame release. This way, the assert would STILL catch on the common error it's trying to catch, while acting friendly on this sort of situation we stumbled on here.

**Comment by ocornut** [comment]
Commit with this fix: 3600ceb527bc4877691d5679f45292852932a115

Commit where the check was first added: ccf0cc85840a5edbeb7c4450cfd67949d0534512
It's an important check as a frequent error was to call events after `ImGui::NewFrame()` and while things would appear to mostly work, some of the nav queries done in NewFrame would essentially break.

Thanks all for your patience with this, glad we got this through.

**Comment by michaelquigley** [comment]
Confirmed. This fixes the issue in my codebase. Thank you!

**Comment by phynae** [comment]
I have a similar issue. When I press Ctrl + S the following error pops up. My BeginFrame -> EndFrame code looks like this.
![image](https://github.com/ocornut/imgui/assets/150086332/37c8e9e2-748a-45c6-b52b-d8f7ce864199)
![image](https://github.com/ocornut/imgui/assets/150086332/e267fa34-1fba-4317-99d9-5f49d16a3a32)

**Comment by ocornut** [comment]
> I have a similar issue. When I press Ctrl + S the following error pops up. My BeginFrame -> EndFrame code looks like this.

What’s in the draw() function then?
Try to narrow it down to a minimum repro.

I don’t think the 2020 issue is related anymore, as nowadays events are queued so even if a backend receives event’s asynchronously it won’t interfere with what the assert is complaining about. It may be a problem on your end.

**Comment by phynae** [comment]
the draw function itself only uses ImGui::GetBackgroundDrawList and ImGui::GetTextSize functions to draw "certain stuff" over video games. until that error occured i have never heard of KeyMods in any situation. Therefore I certainly do not modify them activley and knowingly. 

Fyi: I am internal, so maybe the game itself interfers with the keymods? idk i started that whole learning process a few weeks ago.

**Comment by ocornut** [comment]
> Therefore I certainly do not modify them activley and knowingly.

You’ll need to investigate on your own. We can’t really help with that amount of information.
