### ISSUE TITLE
netImgui integration with hooks

### ISSUE THREAD

**Issue by sammyfreg** [ocornut/imgui#3580]
**Version/Branch of Dear ImGui:**
Version: 1.80 beta
Branch: master

**My Issue/Question:**
I have successfully adapted **netImgui** to use the newly exposed hooks for automatic detection of _BeginFrame()/Render()_, with a few changes to **Dear ImGui**. These edits can be viewed [here ](https://github.com/sammyfreg/imgui/commit/be4b38c3270535d986cfe70b584f3637ed0a11ed). 

This issue's purpose is to know how to proceed forward. These changes allowed me to reach my goals, but might not be in line with your own ideas. I can create a pull request with my **Dear ImGui** fork, with some requested revisions, or you might prefer to make some changes yourself.

**Changes**
1. Expose Hooks to imgui.h (avoids asking the netImgui library user to provide a second path for imgui_internal.h).
2. Can remove hooks. To do that, _AddContextHook_ now returns an handle which can be used for removal. Removal is deferred to avoid potential issue of trying to remove a hook while iterating the hook vector.
3. Imgui function calling hooks, now set their working context after the callbacks have been invoked. (netImgui _BeginFrame()_ can assign a different context to work in empty context for discarded frame).

**Comment by ocornut** [comment]
Hello,

About 1: imgui_internal.h is always in the same folder as imgui.h, I am not sure I understand how that include path is done but if the users needs to pass in a path it should be imgui folder path rather than the path of imgui.h.
I’d rather not have those functions be unnecessarily added to imgui.h.

**Comment by sammyfreg** [comment]
For **netImgui** integration, I ask the user to give me access to _imgui.h_ in my config file ([here](https://github.com/sammyfreg/netImgui/blob/master/Code/Client/NetImgui_Config.h)). Some user can point to their own header file instead, which then conditionally include _imgui.h_. I have no knowledge of the path to be looking for, unless I use a second settings for _imgui_internal.h_. If you prefer not to expose this api publicly, I will go this route.

Thank you for the addition of hooks!

**Comment by ocornut** [comment]
Most extensions just include “imgui.h” or “imgui_internal.h”

(Also if you have code to disable warnings in imgui.h could you report those warnings along with the compiler so we can fix them)

**Comment by sammyfreg** [comment]
For the compiler warnings, they are happening under Warning level : All, under Visual Studio 2019 (MSVC compiler and Clang VStudio integration). It compiles fine under Warning level 4. If you wish, I can open open a new issue for this. It is fairly easy to reproduce.

**Comment by sammyfreg** [comment]
I have removed the public API changes (point 1). I am wondering about the remaining changes and how to proceed.
Differences with official **Dear ImGui:** https://github.com/ocornut/imgui/compare/master...sammyfreg:master

Thank you.

**Comment by ocornut** [comment]
Apologies for not looking at this recently, will do at some point but wanted to focus on shipping 1.80 first. Thanks for your patience Sammy.

**Comment by sammyfreg** [comment]
Understood, take your time.
