### ISSUE TITLE
Qucksave ASSERT problem

### ISSUE THREAD

**Issue by str0yd** [ocornut/imgui#3581]
I have a quick save function in my program. I added this feature with "Ctrl + S":
```
if(ImGui::GetIO().KeyCtrl && ImGui::IsKeyPressed('S'))
  showQuickSave = GL_TRUE;
```
If showQuickSave is true my program opens the Windows save dialog. If I then choose a file or abort the save ImGui throws 
```
M_ASSERT(g.IO.KeyMods == expected_key_mod_flags && "Mismatching io.KeyCtrl/io.KeyShift/io.KeyAlt/io.KeySuper vs io.KeyMods");
```
I understand why the ASSERT throws. I press Ctrl when I start the saving, the Windows save dialog is a blocking function. As soon as it returns i don't press the button anymore.
How I use the render stuff in my main loop:
```
glfwPollEvents();
// 
// update engine stuff here, process my keyboard inputs and so on
//
// initialize GUI for new frame
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplGlfw_NewFrame();
// draw GUI
ImGui::NewFrame();
// here is all my ImGui code:
VisualGui::getInstance().DrawGui();
ImGui::Render();
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

**Comment by ocornut** [comment]
﻿Same as last opened issue:
https://github.com/ocornut/imgui/issues/3575

Please read there and move the discussion there and provide requested information.
