### ISSUE TITLE
Change ColorEdit square size

### ISSUE THREAD

**Issue by marinjurjevic** [ocornut/imgui#3583]
**Version/Branch of Dear ImGui:**

Version: 1.80 wip
Branch: tables

**Back-end/Renderer/Compiler/OS**

Back-ends:  imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: g++ 10.2
Operating System: Linux 5.8.18-1-MANJARO

**My Issue/Question:**

I am unable to change ColorEdit widget square size. I checked the internals, and it is implicitly calculated from current FontSize in 
https://github.com/ocornut/imgui/blob/5789e69a6259f4cf91ed9a523604b911c4e41191/imgui_widgets.cpp#L5236. 
Currently I'm fetching ImGuiContext and changing FontSize directly while ColorEdit is handled. I don't like touching internal stuff so I propose we extend the ColorEditAPI.

**Screenshots/Video**

![big_square](https://user-images.githubusercontent.com/17838694/98560723-5b819080-22a8-11eb-917f-ce2a5d4c2228.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
    bool open = ImGui::TreeNode(file_desc->name().c_str());

    static ImVec4 color;
    
    ImGui::SameLine(); 
    ImGui::ColorEdit4("Mycolor#2", (float*)&color, ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_NoLabel);

```

**Suggestion:**

Extend ColorEdit API with `ImVec2 size` parameter which will just get delegated to ColorButton call inside ColorEdit impl
`IMGUI_API bool          ColorEdit4(const char* label, float col[4], ImGuiColorEditFlags flags = 0, ImVec2 size = ImVec2(0, 0) );`

This suggestion is shortsighted regarding future of this widget. I am still new to Dear ImGui, so I'm not sure if this acceptable to you. Maybe this widget will have an option to choose shape representing color in the future (e.g. circle). In that case ImVec2 is less convenient. Perhaps making it scalar value is best, as then all shapes can be scaled uniformly..

**Comment by rokups** [comment]
You could use `ImGui::SetWindowFontScale()` to tweak font size. Not ideal, but it is a public API.

**Comment by ocornut** [comment]
Hello,

(1)
`GetFrameHeight()` uses FramePadding so you could simply do:

```
ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0, 0));
ImGui::ColorEdit4("Mycolor#2", (float*)&color, ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_NoLabel);
ImGui::PopStyleVar();
```

However that would create the issue that the picker popup would use this zero FramePadding and looks cramped.

(2)
You could make your text/treenode line use padding by calling `AlignTextToFramePadding()` prior to `TreeNode()`. That would make that line higher and fit for any framed widget.

(3)
You could use `ColorButton()` and when it return true open a popup with a color picker.
Would work 100% but a little cumbersome (maybe wrap in a helper function):
```
if (ImGui::ColorButton("hi", color))
    ImGui::OpenPopup("hi-picker");
if (ImGui::BeginPopup("hi-picker"))
{
    ImGui::ColorPicker4("##picker", &color.x, ImGuiColorEditFlags_None, NULL);
    ImGui::EndPopup();
}
```

(4)
We could rework ColorButton() to implicitly make use of `window->DC.CurrLineTextBaseOffset` and adjust its height/size accordingly, but right now I feel we have accumulated a little bit too much of confusion/technical debt with handling of line-height, CurrLineTextBaseOffset and implicit height so I don't feel like going there very much presently (or at least not without a full on swiping refactor of text offset and line height handling).

**Comment by marinjurjevic** [comment]
> (3)
> You could use `ColorButton()` and when it return true open a popup with a color picker.
> Would work 100% but a little cumbersome (maybe wrap in a helper function):
> 
> ```
> if (ImGui::ColorButton("hi", color))
>     ImGui::OpenPopup("hi-picker");
> if (ImGui::BeginPopup("hi-picker"))
> {
>     ImGui::ColorPicker4("##picker", &color.x, ImGuiColorEditFlags_None, NULL);
>     ImGui::EndPopup();
> }
> ```

This actually works for me, and it's not cumbersome as I have helper function for drawing squares anyways (I draw them across multiple table rows in identical fashion). Thank you for help, this solves my troubles. I will leave issue status to you (idk if you want to leave it open or close it)
