### ISSUE TITLE
ColorEdit position is incosistent when used in Tables

### ISSUE THREAD

**Issue by marinjurjevic** [ocornut/imgui#3586]
**Version/Branch of Dear ImGui:**

Version: 1.80 wip
Branch: tables

**Back-end/Renderer/Compiler/OS**

Back-ends:  imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: g++ 10.2
Operating System: Linux 5.8.18-1-MANJARO

**My Issue/Question:**

I'm experimenting with Tables a lot lately, especially using Tree inside them. I am trying to add a ColorEdit at the beginning of the node name inside first column. I've noticed is that it's always appended at the end of the node name, even if I add it before calling TreeNode.

I have a hacky function for adding ColorEdit which sets custom square size (because of #3583) 

```cpp
static ImVec4 draw_color_edit_widget(ImVec4 current_color)
{
    struct ImGuiContext *ctx = ImGui::GetCurrentContext();
    
    float oldFontSize = ctx->FontSize;
    ctx->FontSize = 6.5f;
    ImGui::SameLine(); 
    ImGui::ColorEdit4("Mycolor#", (float*)&current_color, ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_NoLabel);
    ctx->FontSize = oldFontSize;

    return current_color;
}
```

In the main code I'm doing 

```cpp    
    ImGui::TableNextRow();
    ImGui::TableNextColumn();
    
    ImGui::PushID(msg_desc->full_name().c_str());
    static ImVec4 color;
    color = draw_color_edit_widget(color);
    ImGui::PopID();
    
    bool open = ImGui::TreeNode(msg_desc->name().c_str());

    // further columns etc
```

Beside the position of ColorEdit square, it disappears after expanding the node.

**Screenshots/Video**
Collapsed:
![collapsed_node](https://user-images.githubusercontent.com/17838694/98568980-fdf24180-22b1-11eb-8dbf-7544f3bd29f6.png)

Expanded:
![expanded](https://user-images.githubusercontent.com/17838694/98568991-0185c880-22b2-11eb-8b27-b290f9bc1324.png)

**Comment by ocornut** [comment]
Please provide an actual minimal and complete repro that we can paste into any file, your code is incomplete and its hard to tel what your issue is without more details.

**Comment by marinjurjevic** [comment]
I went to reproduce with minimal example and then it suddenly worked. The problem was calling SameLine() always before the ColorEdit widget which is wrong, I need to call it before when appending, and after when prepending which makes sense.  
```
TreeNode -> SameLine -> ColorEdit
ColorEdit -> SameLine -> TreeNode
```

I will close the issue as it was just my poor understanding of SameLine...

**Comment by ocornut** [comment]
Good to hear it is solved :) 
The reason we ask for actual repro like (https://stackoverflow.com/help/mcve) is that many time trying to make that repro helps find the issue.
