### ISSUE TITLE
DirectX 11 ImageButtons Not Working

### ISSUE THREAD

**Issue by MichaelAmorim4** [ocornut/imgui#3588]
Hi I was using Image Buttons in directX 11 and testing. I couldn't seem to get the image button to actually function properly and increment a placeHolder integer. I copied the exact code from the imgui_demo.cpp for image buttons and that wasnt working either. Here is the code I currently have where the normal button increments the placeHolder int but the Image Button does not. 

I have not been using ImGui very long so sorry if this question is a bit dumb or an easy fix but i couldnt find any solution through quick searches and thought here would be a good spot to ask for help
```
static int pressed_count = 0;

			ImGui::SetCursorPos(ImVec2(650, 380));
			if (ImGui::Button("Next", ImVec2(75, 30)))
				pressed_count += 1;

			ret = LoadTextureFromFile("projectile1.png", &my_texture, &my_image_width, &my_image_height);
			IM_ASSERT(ret);

			ImGui::SetCursorPos(ImVec2(500, 150));

			
			if (ImGui::ImageButton(my_texture, ImVec2(100, 100)))
				pressed_count += 1;
```

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.

Prefer using Discord for general programming help.
