### ISSUE TITLE
Quick Question about slider int increment value

### ISSUE THREAD

**Issue by patrikpatrik** [ocornut/imgui#3589]
Sorry if this has been answered before. But I'm using:
[code]
ImGui::SliderInt("sizeInt", &ROWCOL, 0, 200);
[/code]

Is there a way to increment by every even number instead of ++ ? Thanks in advance!

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
