### ISSUE TITLE
Text drawing at incorrect Y when combining columns and ListClipper

### ISSUE THREAD

**Issue by allender** [ocornut/imgui#3593]
**Version/Branch of Dear ImGui:**

Version: 1.8 WIP (5789e69a)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_SDL.cpp + imgui_impl_opengl2.cpp
Compiler: Visual Studio 2019 Command line tools (using VS code)
Operating System: Win 10 x86/x64

**My Issue/Question:**

I have a window with two columns.  One of the columns is using an ImGuiListClipper because of the potential for 65536 lines of text.   The other column is just a few short lines.  After drawing an entire the column and then issuing NextColumn, the drawing takes place at the y pos where the previous column left off.  I just upgraded from 1.53 (which is pretty old I know) and it wasn't behaving this way in that version and I can find no documentation that would indicate that this behavior has changed.   Below is a screenshot that shows the second column (drawn first) and then the first column (with the list clipper) drawn second, and you can see that it starts drawing at the next Y position.

**Screenshots/Video**

![2020-11-11 20_05_57-New Issue · ocornut_imgui](https://user-images.githubusercontent.com/1638265/98886779-477d9080-245a-11eb-8cc5-f0e509efbfb9.png)

**Standalone, minimal, complete and verifiable example:** 
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
		ImGui::Columns(2);
		ImGui::SetColumnOffset(1, ImGui::GetWindowContentRegionWidth() - 120.0f);

		ImGui::NextColumn();
		ImGui::Text("A");
		ImGui::Text("X");
		ImGui::Text("Y");
		ImGui::Text("PC");
		ImGui::Text("SP");


		ImGui::NextColumn();
		ImGuiListClipper clipper;
		clipper.Begin(1000, 15);
		while (clipper.Step()) {
			for (int line_i = clipper.DisplayStart; line_i < clipper.DisplayEnd; line_i++) {
				ImGui::Text("hello %d", line_i);
			}
		}
ImGui::End();
```

**Comment by allender** [comment]
Turns out that even a simpler example will suffice
```
ImGui::Begin("Example Bug");
ImGui::Columns(2);

ImGui::NextColumn();
ImGui::Text("A");
ImGui::Text("X");

ImGui::NextColumn();
ImGui::Text("Y");
ImGui::Text("PC");
ImGui::Text("SP");
ImGui::End();
```

![image](https://user-images.githubusercontent.com/1638265/98889261-3b480200-245f-11eb-9849-deb782fc895e.png)

**Comment by ocornut** [comment]
Hello,

NextColumn() advance columns and therefore create a new row the second time. Afaik that has always been the behavior. Why don’t you draw them in the right order?

**Comment by allender** [comment]
Hi - I used 1.5WIP (sorry, don't recall the specific commit) for a project that I have and that was not the behavior.  Specifically, I drew the left column first (which is a ListClipper) and then the right.  In 1.5WIP, the second column items drew at the top, where I expected them.  It sounds like that's a bug that has since been rectified and I will adjust.  I was just surprised.

As for why don't I draw them in the right order - I can't do the "right" order when using the ListClipper.  I could - maybe - but that sounds like a lot of work to figure out the logic.  I think that "right" can depend on what you are used to.  but at least here, I know what is expected and can adjust in the figure.

Thanks.
