### ISSUE TITLE
Collapsing headers side by side using same line function

### ISSUE THREAD

**Issue by Xeverous** [ocornut/imgui#3596]
**Version/Branch of Dear ImGui:**

acb8ef200610e0e3618182c8407681090eaa75ec (1.80 WIP (17905))

**Back-end/Renderer/Compiler/OS**

Back-ends: https://github.com/mosra/magnum-integration/tree/master/src/Magnum/ImGuiIntegration
Compiler: MinGW GCC 10.2.1
Operating System: Windows but probably irrelevant

**My Issue/Question:**

How to divide a window vertically to have collapsing headers in different columns?

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Put this in any window drawing:

```cpp
	ImGui::BeginGroup();
	ImGui::BeginChild("1");
	if (ImGui::CollapsingHeader("test left"))
		ImGui::Text("test 123");
	ImGui::EndChild();
	ImGui::EndGroup();

	ImGui::SameLine();

	ImGui::BeginGroup();
	ImGui::BeginChild("2");
	ImGui::Text("text on the right");
	if (ImGui::CollapsingHeader("test right"))
		ImGui::Text("test 456");
	ImGui::EndChild();
	ImGui::EndGroup();
```

I have tried:
- child windows
- groups
- both groups+child window

But nothing works. Either the second section does not render or (with groups alone) I get a broken result like this:

![image](https://user-images.githubusercontent.com/20820409/99013581-16cc5280-2551-11eb-95e6-b35e05480fa5.png)

**Comment by ocornut** [comment]
BeginGroup will lock the X position and capture bounding box at the end, this is now what you want.

BeginChild will need a width, if you don’t provide it you’ll use the entire available space. You may use BeginChild() with a size of (w, 0) where w = Max((GetAvailContentSize().x - style.ItemSpacing.x) / 2, 1) on each child, separated with SameLine().

Or you can use the Columns api or upcoming BeginTable to split the horizontal space in two.

**Comment by Xeverous** [comment]
Columns do fine now except 1 problem:

![image](https://user-images.githubusercontent.com/20820409/99116245-f99c9000-25f3-11eb-89dc-d20d8fef8853.png)

The text is clipped instead of wrapped to the next line. Is this expected behavior?

**Comment by Xeverous** [comment]
There is no `GetAvailContentSize`, did you mean `GetContentRegionAvailWidth`?

**Comment by Xeverous** [comment]
```cpp
const auto w = std::max((ImGui::GetContentRegionAvail().x - ImGui::GetStyle().ItemSpacing.x) / 2.0f, 1.0f);
ImGui::BeginChild("1", ImVec2(w, 0));
```

This works as well as columns and has the identical problem of clipped text. Is this expected? How do I fix the text to wrap to the next line?

**Comment by ocornut** [comment]
You can use `TextWrapped()`for wrapping.

**Comment by Xeverous** [comment]
Great, now everything works. Do I need to care about wrapping/clipping of any other elements than text?

**Comment by ocornut** [comment]
Yes. Not much is wrapping by default.

**Comment by Xeverous** [comment]
Ok, I will look into the demo and open an issue only if I can't anything there or in past issues.
