### ISSUE TITLE
window disappear when click on other window

### ISSUE THREAD

**Issue by coldgemini** [ocornut/imgui#3597]
![imgui](https://user-images.githubusercontent.com/33364009/99141981-8e060180-268b-11eb-8453-260ffbce4a41.PNG)

I draw two imgui windows, but somehow when I click one window the other will disappear. Do you have any clue why this is happening?

following is my code piece:
void GUI_Overlay::newFrame()
{
    static auto tPrev = std::chrono::high_resolution_clock::now();
    ImGui_ImplVulkan_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    ImGui::SetNextWindowPos(ImVec2(100, 100), ImGuiCond_FirstUseEver);
    ImGui::SetNextWindowSize(ImVec2(200, 200), ImGuiCond_FirstUseEver);

    if (show_demo_window)
        ImGui::ShowDemoWindow(&show_demo_window);

    ImGui::Begin("Example settings");
    ImGui::Checkbox("Demo Window", &show_demo_window);        // Edit bools storing our window open/close state

    auto tCur  = std::chrono::high_resolution_clock::now();
    auto tDiff = std::chrono::duration<double, std::milli>(tCur - tPrev).count();
    tPrev      = tCur;

    uint32_t lastFPS = static_cast<uint32_t>(1000.0 / tDiff);
    ImGui::Text("%.2f ms/frame (%.1d fps)", tDiff, lastFPS);

    if (ImGui::Button("TestButton 0"))
    {
        std::cout << "button 0 clicked" << std::endl;
    }

    auto state  = data_state::StateStore::getState<camera::State>();
    auto pos    = state.position;
    auto target = state.target;
    auto up     = state.up;
    auto dir    = state.dir;
    ImGui::Text("Camera State: ");
    {
        std::stringstream ss;
        ss << "position: " << pos.x << ", " << pos.y << ", " << pos.z << "\n";
        ImGui::Text(ss.str().c_str());
    }
    {
        std::stringstream ss;
        ss << "dir: " << dir.x << ", " << dir.y << ", " << dir.z << "\n";
        ImGui::Text(ss.str().c_str());
    }
    {
        std::stringstream ss;
        ss << "up: " << up.x << ", " << up.y << ", " << up.z << "\n";
        ImGui::Text(ss.str().c_str());
    }
    {
        static int lightType = 0;
        ImGui::RadioButton("Directional", &lightType, 0);
        ImGui::SameLine();
        ImGui::RadioButton("Point", &lightType, 1);
        ImGui::SameLine();
        ImGui::RadioButton("Spot", &lightType, 2);

        static float ambientStrength = 0.5f;
        ImGui::SliderFloat("ambientStrength", &ambientStrength, 0.0f, 1.0f);

        static float specularStrength = 0.5f;
        ImGui::SliderFloat("specularStrength", &specularStrength, 0.0f, 1.0f);

        static float shininess = 32.0f;
        ImGui::SliderFloat("shininess", &shininess, 0.0f, 100.0f);

        static float cutoff = 20.0f;
        ImGui::SliderFloat("cutoff", &cutoff, 0.0f, 90.0f);

        static float outer_cutoff = 30.0f;
        ImGui::SliderFloat("outer_cutoff", &outer_cutoff, 0.0f, 90.0f);

        static ImVec4 light_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);
        ImGui::ColorEdit3("light color", (float*) &light_color);

        glm::vec3 color = glm::vec3(light_color.x, light_color.y, light_color.z);

        data_state::StateStore::reactOn(light::Event{color, ambientStrength,
                                                     specularStrength, shininess,
                                                     cutoff, outer_cutoff,
                                                     lightType});
    }

    ImGui::End();

    ImGui::Render();
}

**Comment by coldgemini** [comment]
![cubemap_isssue](https://user-images.githubusercontent.com/33364009/99142999-1210b700-2695-11eb-8df7-c899b35abc1d.PNG)
the issue also exists on SaschaWillems/Vulkan repo "cubemap" example

**Comment by coldgemini** [comment]
issue fixed, I was mistaking ImDrawVert for ImDrawIdx

**Comment by ocornut** [comment]
Next time you open an issue please fill the issue template correctly and precisely. It’s here for a reason. Your last message makes things even more confusing as on one end you are suggesting using the Vulkan backends on another hand you are suggesting a custom renderer.
