### ISSUE TITLE
Tables output borders and background beyond right-most column

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#3605]
I would like to know why tables with fixed sizing policy are printing background and borders outside of item rect size
I would expect the area contained inside red rectangle to be as the background.
 
![tables_fixed](https://user-images.githubusercontent.com/1795930/99655043-7b107a00-2a5b-11eb-8aad-4c5ada108f98.png)

**Comment by sonoro1234** [comment]
Wrapping the table with BeginGroup-EndGroup and then 
`ig.GetWindowDrawList():AddRect(ig.GetItemRectMin(), ig.GetItemRectMax(), ig.U32(1,1,1,1));`
outputs this:

![table_group](https://user-images.githubusercontent.com/1795930/99656203-e6a71700-2a5c-11eb-90e5-a6b536f6e3e5.png)

**Comment by rokups** [comment]
I personally would not expect space beyond last one to be same as the background, because conceptually that space is part of the table. It would be confusing to have two sets of backgrounds in a single table i would think.

However, a quick search shows that UI toolkits do both variants. In that case, i suppose both are valid styles to have.

**Comment by sonoro1234** [comment]
> that space is part of the table.

But BeginGroup/EndGroup (surrounded by white border rectangle) is telling that this space is not part of the table.

**Comment by ocornut** [comment]
> But BeginGroup/EndGroup (surrounded by white border rectangle) is telling that this space is not part of the table.

It's an artifact of the fact that tables declare a certain contents size for windows auto-resize to function, and that's the size visible in EndGroup(). Same thing if you were to enclose a simple TreeNode or Selectable in a group (the visible highlight is larger than the minimum size which is the one declared for layout purpose).

As per your question, it's a valid concern but presently tables weren't designed for that.
However:

(1) You can set a specific outer-width for the Table:
Added this to demo now:
```cpp
if (ImGui::BeginTable("##table1", 3, ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg, ImVec2(TEXT_BASE_WIDTH * 30, 0.0f)))
{
    for (int row = 0; row < 5; row++)
    {
        ImGui::TableNextRow();
        for (int column = 0; column < 3; column++)
        {
            ImGui::TableNextColumn();
            ImGui::Text("Cell %d,%d", column, row);
        }
    }
    ImGui::EndTable();
}
ImGui::SameLine();
if (ImGui::BeginTable("##table2", 3, ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg, ImVec2(TEXT_BASE_WIDTH * 30, 0.0f)))
{
    for (int row = 0; row < 3; row++)
    {
        ImGui::TableNextRow(0, TEXT_BASE_HEIGHT * 1.5f);
        for (int column = 0; column < 3; column++)
        {
            ImGui::TableNextColumn();
            ImGui::Text("Cell %d,%d", column, row);
        }
    }
    ImGui::EndTable();
}
```
![image](https://user-images.githubusercontent.com/8225057/101198011-1c561d80-3663-11eb-853f-837f88c1db07.png)

I just fixed a bug to make this work btw, so you'll need to update to latest.

(2) To do exactly what you suggest we'd need to add an additional feature.
I can see various ways to approach the problem, will try to investigate it during Beta.
As I am hoping to rewrite the bg/borders rendered in a different way, if it runs a post-process pass in `EndTable()` as I expected to do it'll be easier to shrink the table at that point.

**Comment by ocornut** [comment]
FYI I have a working version of this:

![20201217_tables_no_host_extend_x](https://user-images.githubusercontent.com/8225057/102545995-4e31a000-40b7-11eb-8324-5f0234574bf8.gif)

It's not committed yet as 
- I am still working on related features now. 
- This make a off-by-one right-most-border issue a little more visible (and it's a surprisingly tricky issue but I'll fix it).
- I am not totally sure what is the right way to enable/disable this.
- There's currently a slight asymmetry between the seemingly-but-no-so-equivalent X/Y flags which needs some rethinking.

**Comment by ocornut** [comment]
This is now supported but not via the flag suggested in the previous post.
See https://github.com/ocornut/imgui/issues/2957#issuecomment-748205831

"
### BREAKING CHANGES (DEC 2020)

To support #3605 I made a little change to the default value and handling of the ImVec2 outer_size parameter.

`ImVec2 outer_size` previous default value is `ImVec2(0.0f, 0.0f)`
`ImVec2 outer_size` new default value is `ImVec2(-FLT-MIN, 0.0f)` (right-align)

The new meaning of `outer_size.x == 0.0f` is "automatic width".
If Scrolling is enabled or if any columns is set to Stretch,` outer_size.x == 0.0f` is the same as `outer_size == -FLT_MIN` (will right-align). If Scrolling is disabled and all columns are set to Non-Stretch, then `outer_size.x == 0.0f` allows to create tables which don't use the full window width while not having to specify a width ahead:

Effectively this is unlikely to break much code as outer_size is only required for scrolling tables.
(As a data point: The only things affected in the demo were demo tables which had a toggle to switch between scrolling and not-scrolling, and therefore had specific height provided and yet could have their scrolling disabled, which is not likely to appear in real code.)
"
