### ISSUE TITLE
Missing XInput1_4.dll Library

### ISSUE THREAD

**Issue by liketheicymoon** [ocornut/imgui#3607]
Missing XInput1_4.dll library Even if I copy one from another computer, it still shows that other libraries are missing, is there something missing on my computer?

**Comment by liketheicymoon** [comment]
Windows 7

**Comment by sonoro1234** [comment]
https://github.com/ocornut/imgui/issues/2716

**Comment by ocornut** [comment]
Also see #3248

**Comment by ocornut** [comment]
Fixed by https://github.com/ocornut/imgui/pull/3646
