### ISSUE TITLE
My Rust Gui is broken and i cant seem to fix it.

### ISSUE THREAD

**Issue by Caulin123** [ocornut/imgui#3608]
So my rust source is drawing an external transparent window with ImGui attached and everytime i load it up and click a feature it Flickers/Dosent select a feature on thr first try you have to spam click your mouse button to get the feature to select video down below. But when you are out of the game it selects on the first try but i have the menu getting the game position so i cant just drag the game aside. The video you can see is me trying to select a feature but it is just flickering i have tried the foreground and active window fixes but they seem to not work for me if anyone can help me with this issue it would be greatly appreciated, thanks!
https://cdn.discordapp.com/attachments/657710825976627250/779455594578968646/2020-11-20_12-10-11.mp4
https://cdn.discordapp.com/attachments/779263826582700056/779426785816215622/2020-11-20_11-21-56.mp4

**Comment by ocornut** [comment]
Sorry but #1586
