### ISSUE TITLE
Statick analysis warning on the use of strlen()

### ISSUE THREAD

**Issue by Keng80** [ocornut/imgui#3612]
**Version/Branch of Dear ImGui:**

Version: v1.80 WIP
Branch: master

**My Issue/Question:**

Hello, I ran Statick analysis on imgui.cpp and the "Flawfinder" tool is warning on the use of `strlen()` as it has the potential to over-read if the string isn't null-terminated. The passed strings are mainly function parameters which I'm not sure how to check and confirm that it will be null-terminated. Any thoughts on that?
Thank you

There are multiple examples in imgui.cpp

![image](https://user-images.githubusercontent.com/74933118/100016724-db7b2080-2da7-11eb-86d3-e035830e7e11.png)

**Comment by ocornut** [comment]
`strlen()` does and always did work by looking for a null terminator. That's its purpose. I don't see an issue with the pasted code.

If you want to report a warning emitted by a static analysis tool please actually provide details of the warning and details said tool and its settings.

We already run PVS-Studio on the CI server:
https://github.com/ocornut/imgui/actions?query=workflow%3Astatic-analysis

**Comment by Keng80** [comment]
Thank you for the reply. Here are the warning details from the Statick analysis / Flawfinder tool on the use of `strlen()`: (please note that the Statick analysis here ran on the v1.50 WIP version of imgui / imgui.cpp):
_imgui/imgui.cpp, Line - 899
TOOL: flawfinder
(buffer) strlen
Does not handle strings that are not \0-terminated; if given one it may perform an over-read (it could cause a crash if unprotected) (CWE-126).  
SEVERITY NORMAL_

Details on the Statick tool used can be found here FYI: 
![image](https://user-images.githubusercontent.com/74933118/100027450-d2477f00-2dba-11eb-8d35-2750d3f4fee8.png)

**Comment by ocornut** [comment]
Hello Keng80,

1.50 WIP is more than 3+ years old so reporting anything on this version is not useful.
Moreover that specific warning you quote:
> "Does not handle strings that are not \0-terminated; if given one it may perform an over-read (it could cause a crash if unprotected) (CWE-126)."

Is silly in a way I'd rather not elaborate on. C strings are zero terminated and the zero-terminator is the only way to process them. 
I will close this now. I realize you are trying to help but working with a 3 years old version and configuring a analyzer for meaningless reports is not helpful to the project, it's only grabbing attention.

Cheers.
