### ISSUE TITLE
How can i make it so the colours change

### ISSUE THREAD

**Issue by Kenmilll** [ocornut/imgui#3614]
Is there a way for me to make a sort of rainbow effect so it slowly changes colours thought it would look quite cool i don't really have a reference to anywhere and i don't know if this is enough info - if it isn't i'm sorry for wasting your time! 

Thanks in advance

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. Closing.

See Demo>Examples>Custom Rendering for some gradients.

Please use the Discord or any general programming forum.

**Comment by Kenmilll** [comment]
I was asking whether i can make it so it changes colours over time like a rainbow effect, not for gradients or does it show me somewhere how to do that and im just blind?
