### ISSUE TITLE
Rendering an image crashes at IM_ASSERT?

### ISSUE THREAD

**Issue by Bizzie2k** [ocornut/imgui#3616]
**Version/Branch of Dear ImGui:** 1.75 WIP

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Compiler: VS2019
Operating System: Windows 10

**My Issue/Question:** 

When trying to render an image using code (seen below) I found in a DX11 image rendering tutorial, the code will crash on the line `IM_ASSERT(ret);`. It never makes it to the part where I call `ImGui::Image();`, so I know that's not the issue (at least yet). Any help would be appreciated, and sorry for taking your time.

**Standalone, minimal, complete and verifiable example:** 

```// if (!init) {} statement
int my_image_width = 0;
int my_image_height = 0;
ID3D11ShaderResourceView* my_texture = NULL;
bool ret = LoadTextureFromFile("/images/Transient.png", &my_texture, &my_image_width, &my_image_height); 
//I have a folder titled "images" with an image called "Transient" saved in the png format
IM_ASSERT(ret); //The line where my code will crash

**Comment by ocornut** [comment]
Two things:

1) you’d have to understand what you are asking a question about a problem that has zero thing to do with dear imgui. You are failing to load a file, none of the meaningful code involved is dear imgui code.

2) the Fonts documentation has an explicit paragraph helping users understand how patha/filenames are handled - not specific to dear imgui. Please read it again. By trying to load a filename with “/Images/Transient.png” you are trying to load a file called Transient.png from a folder called Images at the root of your current working drive. This is most likely not what you intended. Please read about relative and absolute path names and please understand that the current working directory for your process is setup in your debugging/runtime environment.

**Comment by Bizzie2k** [comment]
Tried changing it to `../images/Transient` and still crashing. I'm just throwing that out there, but I'll close the issue with this comment as it isn't an issue with imgui. Thanks for your time.
