### ISSUE TITLE
TabBar buttons flickering when clicked

### ISSUE THREAD

**Issue by R0SK0** [ocornut/imgui#3619]
Hey, im new to c++ / ImGui and im trying to figure out why my TabBar is broken. 
So whenever I click on one of my tabs and It just flickers.

![](https://user-images.githubusercontent.com/52052725/100293246-0e144d00-2f51-11eb-8649-55220eeb47e0.gif)
```
ImGuiTabBarFlags tab_bar_flags = ImGuiTabBarFlags_None;
			if (ImGui::BeginTabBar("Test", tab_bar_flags))
			{

				if (ImGui::BeginTabItem("Schedule Changes"))
				{

				}

				if (ImGui::BeginTabItem("To-Do List"))
				{
					ImGui::Text("Test");
				}

			}
```

**Comment by ocornut** [comment]
Hello,
Look at the demo code where it is demoing using TabBar and TabItem and you'll see what your mistake is.
