### ISSUE TITLE
ImGui::Button issue

### ISSUE THREAD

**Issue by Kenmilll** [ocornut/imgui#3620]
**Newest version i think?**

Im using Windows and im using visual studio 2019

**My ImGui::Button doesn't work and I don't know why**

Whenever I click the button it doesn't work I was trying to change the integer variable and then when the variable was a certain number it would load something else but it wasn't working - so I tried to make it so when you click the button it loads the items that I wanted to load with the variable - this still didn't work the checkboxes, etc. appear for a split second and then just disappears again
```
// Here's some code anyone can copy and paste to reproduce your issue
if (ImGui::Button("test", ImVec2(118, 100)))
{
  tabs = 1;
}

if(tabs == 1)
{
ImGui::Checkbox("It's working finally", &test)
}
```

**Comment by Kenmilll** [comment]
If I load a checkbox or slider normally then it works fine - one test i haven't done is to start a new ImGui menu so I will try that.

**Comment by Folling** [comment]
`tabs` is probably not declared as static. Prepend that keyword to the variable declaration and it should work.
Dear ImGui is framebased, so your code is called some 60x per second (assuming a 60Hz monitor). This means that you recreate the `tabs` variable every frame, assign it to 1 if the button is clicked, only to have it overridden to zero 16ms later.
You'll want to read into the links on the wiki and the FAQ to get a better understanding of the IMGUI paradigm and how to work with it

**Comment by Kenmilll** [comment]
> `tabs` is probably not declared as static. Prepend that keyword to the variable declaration and it should work.
> Dear ImGui is framebased, so your code is called some 60x per second (assuming a 60Hz monitor). This means that you recreate the `tabs` variable every frame, assign it to 1 if the button is clicked, only to have it overridden to zero 16ms later.
> You'll want to read into the links on the wiki and the FAQ to get a better understanding of the IMGUI paradigm and how to work with it

Even when i put the code to be executed through the button it doesnt work

I tried this code here:
```
		if (ImGui::Button("test", ImVec2(118, 100))) //aimbot
		{
			ImGui::Begin("test");
			ImGui::Checkbox("Whats good it works", &test);
			ImGui::End();
		}
```

**Comment by Kenmilll** [comment]
> `tabs` is probably not declared as static. Prepend that keyword to the variable declaration and it should work.
> Dear ImGui is framebased, so your code is called some 60x per second (assuming a 60Hz monitor). This means that you recreate the `tabs` variable every frame, assign it to 1 if the button is clicked, only to have it overridden to zero 16ms later.
> You'll want to read into the links on the wiki and the FAQ to get a better understanding of the IMGUI paradigm and how to work with it

The same thing happens even when i put the code in the if statement of the button like this code
```
if (ImGui::Button("test" ImVec2(118, 100))) 
{
    ImGui::Begin("test");
    ImGui::Checkbox("Whats good it works", &test);
    ImGui::End();
}
```
The same thing happens it just dissapears

**Comment by ocornut** [comment]
You didn't follow requested guidelines or issue template. 
Please make sure you have read the guidelines. Please move this discussion elsewhere (e.g. on Discord) so you can get to understand how the IMGUI paradigm works.
Closing.
