### ISSUE TITLE
How to set Combo box item Height?

### ISSUE THREAD

**Issue by aligili** [ocornut/imgui#3623]
I can create combo box using this code:

ImGui::Combo("Camera", (int*) &m_systemParameter.cameraType, "Pinhole\0Fisheye\0Spherical\0\0", 200)

But how do you set the height of the item? The default item height is small.

**Comment by ocornut** [comment]
- You ignored the guidelines and issues template.
- Maybe using BeginCombo() with the appropriate flags e.g. `ImGuiComboFlags_HeightLarge` would solve your problem, but since your question is so ambiguous I'm not sure.

I'm closing this as lazy.

**Comment by xingyun86** [comment]
> * You ignored the guidelines and issues template.
> * Maybe using BeginCombo() with the appropriate flags e.g. `ImGuiComboFlags_HeightLarge` would solve your problem, but since your question is so ambiguous I'm not sure.
> 
> I'm closing this as lazy.

I use this flag, but not valid.

**Comment by xingyun86** [comment]
```
 if (ImGui::BeginCombo(u8"分类", combo_label.c_str(), ImGuiComboFlags_HeightLarge))
```
The combo item height also default.
