### ISSUE TITLE
Hide the close window button and the hide tab bar button in dock space

### ISSUE THREAD

**Issue by s1nisteR** [ocornut/imgui#3633]
**Version/Branch of Dear ImGui: Docking Branch

**Back-end/Renderer/Compiler/OS OpenGL

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 

I've been trying to disable the close window buttons and hide tab bar buttons for my windows which are in the dockspace but the close tab button still shows after doing this.
ImGui::Begin("Property", nullptr)

I'd like if someone guided me as to how to disable the hide tab bar buttons as well.

Tried this
ImGui::Begin("Property", nullptr, ImGuiWindowFlags_NoTitleBar);
But even the titlebar still shows.

**Comment by ocornut** [comment]
See discussion in #3521

The problem is that Windows can't have a full overwrite console on Docking Node otherwise multiple windows in a same Docking Node would conflict.

Setting the `DockNodeFlagsOverrideSet` / `DockNodeFlagsOverrideClear` members of `ImGuiWindowClass` + calling `SetNextWindowClass()` can trigger this override but it's experimental/undocumented and it doesn't solve said conflict so it can only work in constrained scenarios.

**Comment by s1nisteR** [comment]
I'm not sure, where should I set this flag at?
```DockNodeFlagsOverrideSet```

Shows up as undefined.

**Comment by s1nisteR** [comment]
Hello, thanks for the quick reply. What should I set the DockNodeFlagsOverrideSet flag to, for the close buttons and hide tab bar buttons to disappear?

**Comment by dgregorius** [comment]
I used this when building the dockspace:

```
ImGuiDockNode* Node = ImGui::DockBuilderGetNode( DockID );
Node ->LocalFlags |= ImGuiDockNodeFlags_NoWindowMenuButton | ImGuiDockNodeFlags_NoCloseButton;
```

**Comment by ocornut** [comment]
I pushed a small change 3d75f438bcc0228a720206f44674987d5ccd2a03
- 1. Removing the node greyed close button if none of the windows in the tab bar have a close button
- 2. Kept the node greyed close button when SOME of the windows in the tab bar have a close button
The later is debatable, I personally prefer current behavior....

**Comment by dgregorius** [comment]
With the update to the latest version using

ImGuiDockNode* Node = ImGui::DockBuilderGetNode( DockID );
Node->LocalFlags |= ImGuiDockNodeFlags_NoWindowMenuButton | ImGuiDockNodeFlags_NoCloseButton;

does not work anymore. Any idea how to get this working again?

Thanks,
-Dirk
