### ISSUE TITLE
When open file - ImHex crash with EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by 4B4DB4B3** [ocornut/imgui#3636]
Hello!
I found error in code -` ImGui::OpenPopup("Accept pattern");` (view_pattern.cpp)
After I drag the file to ImHex, it crashes. I decided to find out what the problem was and opened ImHex in the debugger. The error was in EXCEPTION_ACCESS_VIOLATION after calling OpenPopup.
Proofs:
![Screenshot_2](https://user-images.githubusercontent.com/72896991/101261066-40316600-372c-11eb-8295-aa75850d8dc0.png)
![Screenshot_1](https://user-images.githubusercontent.com/72896991/101261067-41fb2980-372c-11eb-9159-45499c0e91a0.png)
![Screenshot_3](https://user-images.githubusercontent.com/72896991/101261082-5c350780-372c-11eb-847b-f6ea29b90e45.png)

**Comment by ocornut** [comment]
You are submitting to the wrong repository, this seems to be an error in ImHex.
When submitting a crash (here or another else) also please provide a callback and details about the crash.
