### ISSUE TITLE
Couldn't change MenuBar background color

### ISSUE THREAD

**Issue by BaderEddineOuaich** [ocornut/imgui#3637]
**Version/Branch of Dear ImGui:**

Version: 1.79
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MSVC Visual Studio 2019 (v142)

**My Issue/Question:**

I tried to change Menu Bar background rect color with ImGui::PushStyleColor(ImGuiCol_MenuBarBg, color); which does not change anything.

**Screenshots/Video**
<img src="https://i.ibb.co/LZSzrXz/Issue.png" alt="Issue" border="0">

**Example:**
```cpp
	// Menu bar
	{
		ImGui::PushStyleColor(ImGuiCol_MenuBarBg, ImVec4(1.0f, 1.0f, 1.0f, 1.0f)); // Menu bar background color
		ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0.0f, 16.0f)); // Menu bar padding
		ImGui::PushFont(font_audiowide_regular_20);
		if (ImGui::BeginMenuBar())
		{
			if (ImGui::BeginMenu("Menu"))
			{
				if (ImGui::MenuItem("Exit")) { this->EndScene(); }
				ImGui::EndMenu();
			}
			if (ImGui::BeginMenu("Examples"))
			{
				ImGui::MenuItem("Example 1");
				ImGui::MenuItem("Example 2");
				ImGui::MenuItem("Example 3");
				ImGui::MenuItem("Example 4");
				ImGui::EndMenu();
			}
			if (ImGui::BeginMenu("Help"))
			{
				if (ImGui::MenuItem("About")) { this->ShowAboutDialog(); }
				ImGui::EndMenu();
			}

			ImGui::EndMenuBar();
		}
		ImGui::PopFont();
		ImGui::PopStyleVar(1);
		ImGui::PopStyleColor(1);
	}
```

**Comment by ocornut** [comment]
Hello Bader,

In the current version the menubar is actually renderer at the time of calling `Begin()` with the `ImGuiWindowFlags_MenuBar`.
Therefore if you move your `ImGui::PushStyleColor(ImGuiCol_MenuBarBg,[....] ImGui::PopStyleColor()` block to surround the Begin call it will solve your issue. I realize this may seem a little unobvious!

(In the case were you may intend to have all your windows use a same style you may as well alter the style once during initialization and not have to push it.)

Cheers,
Omar

**Comment by BaderEddineOuaich** [comment]
Hi Omar,
Its all clear now, thank you!
Have a great day
