### ISSUE TITLE
DragFloat not working on a Popup window

### ISSUE THREAD

**Issue by markitus18** [ocornut/imgui#3638]
**Version/Branch of Dear ImGui:**

Version: dear imgui, v1.77 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_SDL.cpp
Operating System: Windows 10 (running the program in x86)

**My Issue/Question:**
DragFloat slider behaviour is not working on a Popup window. SliderInt, however, works correctly.

**Comment by ocornut** [comment]
Hello,

Please provide a repro to back up your claim, as as far as we know DragFloat never broke in popup window.

**Comment by ocornut** [comment]
Will reopen this when more details or a repro have been provided.
