### ISSUE TITLE
Example build error

### ISSUE THREAD

**Issue by Romiro27** [ocornut/imgui#3642]
**Version/Branch of Dear ImGui:**

Version: 1.79
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: gcc 9.3.0
Operating System: Ubuntu 20.04

**My Issue/Question:**

I wanted to see an example in the example_glfw_opengl3 folder, ran make and got errors about #include, below is the log with screenshots

`                from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from ../../imgui.h:718,
                 from main.cpp:5:
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h:9:26: error: #include nested too deeply
    9 | # include_next <stdint.h>
      |                          ^`

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/53411896/101349954-91b23000-38a7-11eb-8a3d-dc6d55869aef.png)

**Comment by rokups** [comment]
Line [imgui.h:718](https://github.com/ocornut/imgui/blob/master/imgui.h#L718) is nowhere near any includes. Are you sure no other modifications are in cloned files?

**Comment by Romiro27** [comment]
> Line [imgui.h:718](https://github.com/ocornut/imgui/blob/master/imgui.h#L718) is nowhere near any includes. Are you sure no other modifications are in cloned files?

Ok, this is very strange, because I downloaded the version [v1.79](https://github.com/ocornut/imgui/releases/tag/v1.79) which caused an error, but by cloning the repo directly the project was compiled successfully, thanks for the help!
