### ISSUE TITLE
Help: How to integrate Scintilla with imgui?

### ISSUE THREAD

**Issue by kitepad** [ocornut/imgui#3652]
I want to use imgui as GUI lib to develop my script editor and want to use scintilla (www.scintilla.org) as engine.
I search related information in web, but I cann't get any valuable information (some information has been removed or deleted).

Anyone can give me some advices? My target platform is win32/win64.

Thanks.

**Comment by ocornut** [comment]
The wiki has reference to this thread
 https://github.com/ocornut/imgui/issues/108

Which is the only information we have and I believe the thread author stopped using scintilla and dear imgui a while ago.
If there are information from those people you'd like to recover please ask them on that thread.
I don't think anyone else is using Scintilla with dear imgui at the moment so I don't have specific advices to give you.

Other options listed in https://github.com/ocornut/imgui/wiki/Useful-Widgets include ImGuiColorTextEdit and Zep. I would recommend using those instead.
