### ISSUE TITLE
 How to distinguish the mouse floating state and the mouse up state on the mobile terminal?

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3659]
I am using Dear ImGui on my mobile device,
There is a problem that is not related to technology waiting for me to solve, but I have no idea:
The mouse on the PC has a Hovered state, but there is no such state on mobile devices.
I’m wondering, does ImGui provide an interface that can set the mouse state? 
At the beginning of each frame, it determines whether the mouse is in the Hovered state. 
If it is in the Hovered state, set it to the mouse up state. 
Operation, can this solve the problem of the conflict between the Hovered state and the up state of the mobile terminal?

I have no solution so far, if I have a solution, I will tell you here as soon as possible.

If you have encountered a similar problem, or have ideas, you can leave a message below this post,thanks~!

**Comment by PossiblyAShrub** [comment]
What's happening is that when you press your screen, an invisible "mouse cursor" is moved over the button. However, when you lift your finger, where do we put the mouse cursor? Often your [backend](https://github.com/ocornut/imgui/wiki/Glossary) will set it as the last place you pressed. **It sounds like you want to make a widget (eg. button) not appear *hovered* after pressing them.** A solution to that would be to edit your backend, such that when the user isn't touching their finger to the screen, we set the mouse cursor to be off screen. This means, every frame in your backend you would:

```c
pseduo code:
// collect input
if (screen_pressed) {
    mouse_pos = pressed_pos
} else {
    mouse_pos = (-1, -1) // off screen
}
```

**Comment by YuDang1024** [comment]
I understand，Modifying the back-end code can indeed solve my problem，感谢你~
