### ISSUE TITLE
DateChooser

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#366]
I'm trying to port another one of my "addon controls" to the new version of ImGui.
The control looks like this:
![selection_002](https://cloud.githubusercontent.com/assets/9608982/10346170/0b1b0840-6d2e-11e5-8673-00058df5ada4.png)
It was based on the <b>old</b> ImGui::ComboBox implementation: it just uses BeginChild()/EndChild() when the window opens (instead of the new "popup" syntax).

At this point all seems to look perfect, except that I cannot interact with the controls of the "child window" anymore. Is there a way to "wake up" a child window ?

**Comment by ocornut** [comment]
There's no concept of waking up something. Perhaps post the code and we can look at it!

**Comment by Flix01** [comment]
The code is too long. It here https://github.com/Flix01/imgui/blob/2015-10-Addons/addons/imguidatechooser/imguidatechooser.cpp

The BeginChild() call is at line 247 and the EndChild() call is at line 386.

**Comment by Flix01** [comment]
It should be fixed now.
The problem was that it was based on the old ImGui::Combo(...) implementation and probably there was some kind of hard-coded Combo Active window that was supposed to get the focus... or something like that.

However it's much better not to use ImGui internals at all whenever possible... that makes code more robust to ImGui changes.

**Comment by ocornut** [comment]
Yeah it's a bit tricky when you use them but hopefully it should stabilize with time.
For this type of stuff you should be able to do everything with the public popup API now!
