### ISSUE TITLE
[wanted] Raspberry Pi No X example

### ISSUE THREAD

**Issue by hippyau** [ocornut/imgui#3661]
I see some Raspberry Pi users are not using X, but using SDL?

Any examples on how to do this?

**Comment by rokups** [comment]
https://github.com/ocornut/imgui/tree/master/examples/example_sdl_opengl3
Make sure your build system defines any of `IMGUI_IMPL_OPENGL_LOADER_*` and `IMGUI_IMPL_OPENGL_ES2` or `IMGUI_IMPL_OPENGL_ES3`.

**Comment by ocornut** [comment]
There's a thread about Raspberry PI here: #2837
You can move the discussion there.
We don't even have a raw X backend since most unix-like users would be using SDL or GLFW to build their app.
