### ISSUE TITLE
Dynamic Font Size Adjustments

### ISSUE THREAD

**Issue by GeorgeBarlow** [ocornut/imgui#3662]
Hey all,

Is there any eta when this will be implemented, I need to be able to change the font size in real-time as and when the user performs various tasks, like on a slider etc

**Comment by ocornut** [comment]
There’s no ETA for anything, sorry.

**Comment by GeorgeBarlow** [comment]
Are there anyways to do this then, without going through Imgui for the time being?

**Comment by ocornut** [comment]
You can freely reload the fonts at a different size between one frame and the next if needed. See the FAQ entry about DPI.

**Comment by bvgastel** [comment]
Just created a pull request for scalable fonts, asking for feedback for now. See https://github.com/ocornut/imgui/pull/4056.

**Comment by ocornut** [comment]
Closing this generic issue (since the feature is widely mentioned elsewhere and there are PR such as #4056)

**Comment by ocornut** [comment]
FYI here is the ongoing work on `dynamic_fonts` branch toward 1.92 which should support this natively: https://github.com/ocornut/imgui/issues/8465.
