### ISSUE TITLE
How to change "grab to move window" behaviour?

### ISSUE THREAD

**Issue by NukeBird** [ocornut/imgui#3666]
**Version/Branch of Dear ImGui:**

Version: 1.73 (imgui/1.73@bincrafters/stable via conan)
Branch: I guess master one?

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Visual Studio 2019 (C++17 enabled)
Operating System: Windows 10 Professional

**My Issue/Question:**

After grabbing Image I don't wanna move the window. For example I wanna paint opengl texture via Image so I don't wanna move the window 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/32956315/102896307-3a9b8600-4477-11eb-97d4-cebf29d23cf6.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
Lest use part of imgui_demo.cpp:
```cpp
{
            ImGui::Text("%.0fx%.0f", my_tex_w, my_tex_h);
            ImVec2 pos = ImGui::GetCursorScreenPos();
            ImVec2 uv_min = ImVec2(0.0f, 0.0f);                 // Top-left
            ImVec2 uv_max = ImVec2(1.0f, 1.0f);                 // Lower-right
            ImVec4 tint_col = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);   // No tint
            ImVec4 border_col = ImVec4(1.0f, 1.0f, 1.0f, 0.5f); // 50% opaque white
            ImGui::Image(my_tex_id, ImVec2(my_tex_w, my_tex_h), uv_min, uv_max, tint_col, border_col);
            if (ImGui::IsItemHovered())
            {
                ImGui::BeginTooltip();
                float region_sz = 32.0f;
                float region_x = io.MousePos.x - pos.x - region_sz * 0.5f;
                float region_y = io.MousePos.y - pos.y - region_sz * 0.5f;
                float zoom = 4.0f;
                if (region_x < 0.0f) { region_x = 0.0f; }
                else if (region_x > my_tex_w - region_sz) { region_x = my_tex_w - region_sz; }
                if (region_y < 0.0f) { region_y = 0.0f; }
                else if (region_y > my_tex_h - region_sz) { region_y = my_tex_h - region_sz; }
                ImGui::Text("Min: (%.2f, %.2f)", region_x, region_y);
                ImGui::Text("Max: (%.2f, %.2f)", region_x + region_sz, region_y + region_sz);
                ImVec2 uv0 = ImVec2((region_x) / my_tex_w, (region_y) / my_tex_h);
                ImVec2 uv1 = ImVec2((region_x + region_sz) / my_tex_w, (region_y + region_sz) / my_tex_h);
                ImGui::Image(my_tex_id, ImVec2(region_sz * zoom, region_sz * zoom), uv0, uv1, tint_col, border_col);
                ImGui::EndTooltip();
            }
}
```

How to stop moving window if Image was clicked and mouse button is still pressed?

**Comment by ocornut** [comment]
Hello,

Two sides of the answer:

- `Image()` is not an interactive widget and therefore it let the click pass through to the window. If you use `ImageButton()` or e.g. `InvisibleButton()` it will catch the click.

- If I type into google _"imgui How to change "grab to move window" behaviour?"_ which is your subject line and the word "imgui" the first google result is https://github.com/ocornut/imgui/issues/899 which leads to the `io.ConfigWindowsMoveFromTitleBarOnly` flag which prevents windows from being moved by clicking on their body (unless they have no title bar), regardless of whether a widget has caught the click.
-

**Comment by NukeBird** [comment]
Oh! io.ConfigWindowsMoveFromTitleBarOnly will do its work, thanks!

**Comment by Chillance** [comment]
So, this is nice, but why not as a flag? I'm using https://github.com/inkyblackness/imgui-go and since this is not a flag, it seems tricky to set. Unless I'm missing something?

I'm aware of https://github.com/ocornut/imgui/issues/899 but doesn't clear this up for me either.

**Comment by rokups** [comment]
What is tricky about it? You instead of `Image()` use `ImageButton()` (which will catch clicks, but look like a button) or have `InvisibleButton()` + `Image()` rendered at same exact coordinates with same exact size, so `InvisibleButton()` will catch input and prevent it being handled by the window. Surely imgui-go must allow positioning a cursor and rendering these items as they are a part of public API.

**Comment by Chillance** [comment]
Intersting. I tried this:
imgui.SetCursorPos(imgui.Vec2{X: 0, Y: 0})
imgui.InvisibleButton("id", imgui.WindowContentRegionMax())

And that seems to be going in the right direction for sure. Just need to tweak some margins or something to get it to cover the whole thing.
