### ISSUE TITLE
Avoid crash between Render() and NewFrame() with gui calls

### ISSUE THREAD

**Issue by rickyviking** [ocornut/imgui#367]
Hi all, 
I've integrated ImGui into an engine where the call to NewFrame() takes place during an event callback, after all inputs are parsed.
The problem is that, when the application is about to exit, such callback doesn't get called, so the gui calls made in the last frame cause a crash (as explained here: https://github.com/ocornut/imgui/blob/master/imgui_internal.h#L645)

Is there anything I can do in the current ImGui implementation to avoid this issue?
Or is there an easy design modification to prevent the crash?

Thanks, Ricky

**Comment by ocornut** [comment]
Well I'm confused about why your application would want to make gui calls when it is closing. If you have to keep running gui code after the application started its exit process perhaps you can call a dummy NewFrame() once?

I can't think of an easy solution off-hand that wouldn't create a side-effect for the general use case.

**Comment by rickyviking** [comment]
Hi Omar,
I see your point.
However in osg the typical frame loop is:
```c++
while()
{
viewer.eventTraversal();  // << input events and NewFrame() called in a callback
// custom gui code here
viewer.updateTraversal(); // << Render() called here
viewer.rendereTraversal();
}
```
I'd like to leave the NewFrame() call in the callback, to add only the custom gui code in the main frame loop. But on the last frame, when the callback is not called, I get the crash.
The only workaround I can think of is moving the NewFrame() call within the main loop.

**Comment by ocornut** [comment]
Can't you keep a flag to keep track of whether NewFrame() was called during event traversal, and it is wasn't call it before updateTraversal().?

Also - you are suggesting that ImGui::Render() is called during your updateTraversal() but it would be more beneficial to call it as later as possible in your renderTraversal() to allow using ImGui elements for debugging/tweaking render code.

**Comment by rickyviking** [comment]
Keeping a flag to check before the custom gui code is in the end the same as calling the NewFrame() explicitly in the main loop.
I'll stick with that solution if I can't find anything better.

Thank you for the suggestion about Render() call.

One last question: I'm having issues with the double click, apparently it's never catched, but my DeltaTime is passed in correctly. Should I check anything else?

**Comment by ocornut** [comment]
Is your DeltaTime in SECONDS and not milliseconds?

**Comment by rickyviking** [comment]
it is - average value is 0.016 when  v sync in on.

**Comment by ocornut** [comment]
If you are calling NewFrame() more than once then you may also have problems with that (each frame counts as a unit of time as well).

**Comment by rickyviking** [comment]
No it's called only once.
Should the DeltaTime be set at a precise moment or anywhere before NewFrame() is fine? 
Before/after input events for instance?

**Comment by ocornut** [comment]
Anywhere before NewFrame. There's no Imgui code run before that.

**Comment by rickyviking** [comment]
Hi Omar,

double click issue fixed > osg passes the second mouse down as "doubleclick" event, which I was missing...

Thanks for your support and for the great project!
