### ISSUE TITLE
About the use of DearImGui in the mobile terminal multi-touch

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3670]
I use ImGui on the Android platform,
I want to use ImGui as a virtual joystick, and at this time I have made a simple version.
But there is a problem that ensues. When the left hand controls the joystick, the right hand also needs to do some click operations on the screen. At this time, it seems that ImGui does not support multi-point operations?
What should I do?

**Comment by ocornut** [comment]
You are right it doesn't support multi-touch inputs.

If you have a virtual joystick in your app you should query the touch inputs yourself using a suitable API nor using dear imgui inputs API.
