### ISSUE TITLE
 How to customize the background image of the window

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3673]
I created a window and I want to use a picture related to the game content as the background of my window.
I have not found a suitable API for the time being. 
Can anyone tell me? 
If I find or have a solution, I will leave a message here to tell everyone

**Comment by frink** [comment]
You'll have to render the image and then move the cursor back to where you want. For advanced stuff moving the cursor is a common part of doing ImGui.

**Comment by YuDang1024** [comment]
> You'll have to render the image and then move the cursor back to where you want. For advanced stuff moving the cursor is a common part of doing ImGui.


I don't quite understand what you mean, 
the image must be rendered,
but I don't know if there is an API that I can use, such as:SetNextWindowBackground()

**Comment by YuDang1024** [comment]
I am going to use a window with no border, no dragging, and the same size as the screen to achieve this function of mine. In this window, I draw a picture that matches the screen size, but after I set it, there is still a little gap in the border of the interface. , What else do I need to set?
![image](https://user-images.githubusercontent.com/55690445/103197900-de76ad00-4921-11eb-99d6-06c1fb5180e6.png)

The upper left corner of the window seems to be a little closer to the sum boundary, how should I improve this problem.
my code here:
`

{

	ImGuiContext& g = *GImGui;
	static bool windowWithBackGround = true;
	ImTextureID image_id = (GLuint *)winBgTexture;
	ImGuiIO& io = g.IO;
	int width = io.DisplaySize.x;
	int height = io.DisplaySize.y;
	ImGuiWindow* window = ImGui::GetCurrentWindow(); 
	ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0);
	ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(0.0, 0.0, 0.0, 0.0));
	ImGui::SetNextWindowSize(ImVec2(width, height));
	ImGui::SetNextWindowPos(ImVec2(-5,-5));
	ImGui::Begin("Image_Window", &windowWithBackGround, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar);
	ImGui::Image(image_id, ImVec2(width, height));
	ImGui::End();
	ImGui::PopStyleVar(1);
	ImGui::PopStyleColor(1);
}`

**Comment by ocornut** [comment]
You should push a value of 0,0 for WindowPadding.

Also note you can use ImGuiWindowFlags_NoDecoration as a shortcut for many flags including clearing WindowBg and WindowBorderSize.

**Comment by YuDang1024** [comment]
> You should push a value of 0,0 for WindowPadding. Also note you can use ImGuiWindowFlags_NoDecoration as a shortcut for many flags including clearing WindowBg and WindowBorderSize.

This is exactly what I need, what I am doing now, Dear ImGui has already packaged it for me, thank you so much
