### ISSUE TITLE
How to render an independent set of windows to an off-screen framebuffer?

### ISSUE THREAD

**Issue by datenwolf** [ocornut/imgui#3674]
I'd like to use the ImGui rendering functions to generate a passive (i.e. non user interactive) view, that's being rendered into an off-screen buffer, while also using ImGui to render the main user interface.

However I cannot of course do something like this

```
while( !quit){
    ImGui::NewFrame();
    render_main_UI();
    ImGui::Render();

    ImGui::NewFrame();
    render_auxiliary_view();
    ImGui::Render();
}
```

as these two rendering steps would interfere with their IDs.

What steps do I have to take to get two or more independent draw lists and ID stacks, that I can render to independently?

**Comment by ocornut** [comment]
You can create multiple dear imgui and select them accordingly.

**Comment by rokups** [comment]
> You can create multiple dear imgui **contexts** and select them accordingly.

FTFY :)

**Comment by ocornut** [comment]
Closed as answered.
