### ISSUE TITLE
 How to set the size of the item? Mainly height

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3677]
I am working on a login interface, but the input box for the account and password is too small for me. In order to adapt to more devices, I did not set the size of the window, just let it be in the middle of the window.
What API should I use to make the side of the account input box bigger, mainly because I want it to be taller, and the width is enough for me.
![image](https://user-images.githubusercontent.com/55690445/103254650-1d0f7480-49c1-11eb-8fe9-0507a62fbd04.png)

I only found: SetNextItemWidth().
But it doesn't seem to be:SetNextItemHeight()
How can I make the height of my input box larger.
Thanks~

**Comment by YuDang1024** [comment]
`	

my code is here:

    staic char buf5[64] = "";
	static char password[64] = "";
	static bool bAccountWindow = true;
	ImGuiContext& g = *GImGui;
	int width = g.IO.DisplaySize.x;
	int height = g.IO.DisplaySize.y;
	float windowsWidth = -1;
	ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(0.0, 0.0, 0.0, 0.0));
	ImGui::SetNextWindowPos(ImVec2(width/2,height/2),0,ImVec2(0.5,0.5));
	ImGui::Begin("AccountWindow", &bAccountWindow,ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_AlwaysAutoResize);
	ImGui::Text("Account  "); ImGui::SameLine();
	ImGui::InputText("##Account", buf5, sizeof(buf5), ImGuiInputTextFlags_CharsNoBlank);
	ImGui::Text("Password"); ImGui::SameLine();
	ImGui::InputText("##Password", password, sizeof(password), ImGuiInputTextFlags_Password);
	windowsWidth = ImGui::GetContentRegionAvailWidth();
	ImGui::PopStyleColor(1);

	if (ImGui::Button("Login", ImVec2(windowsWidth, 30)))
	{
	}

	if (ImGui::Button("Cancle", ImVec2(windowsWidth, 30)))
	{
	}

	ImGui::End();
`

**Comment by rokups** [comment]
Hello @YuDang1024,
Height is font size + some paddings from the style. You should add a font with different size and use `ImGui::PushFont(new_font)`/`ImGui::PopFont()` around widgets that you would like to use font of different size. See wiki on how to load fonts: https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#font-loading-instructions.

> ImGui::Text("Account  ");

Instead of adding spaces to the string you should be using `ImGui::SetCursorPosX()` (after `ImGui::SameLine()`) to set a new location where next widget will be rendered.

**Comment by YuDang1024** [comment]
> Hello @YuDang1024,
> Height is font size + some paddings from the style. You should add a font with different size and use `ImGui::PushFont(new_font)`/`ImGui::PopFont()` around widgets that you would like to use font of different size. See wiki on how to load fonts: https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#font-loading-instructions.
> 
> > ImGui::Text("Account  ");
> 
> Instead of adding spaces to the string you should be using `ImGui::SetCursorPosX()` (after `ImGui::SameLine()`) to set a new location where next widget will be rendered.


Thank you for your answer, my thinking is still stuck in ordinary JavaScript writing, DearImGui has its own style.
Your answer answered my question very well, thank you very much
