### ISSUE TITLE
Two bugs with a frozen column of a table

### ISSUE THREAD

**Issue by the-goodies** [ocornut/imgui#3678]
**Version/Branch of Dear ImGui:**

Version: 1.80
Branch: master

**Back-end/Renderer/Compiler/OS**

Backends: imgui_impl_opengl2.cpp + imgui_impl_glfw.cpp
OS: Windows 10

**My Issue/Question:**

Two bugs with a frozen column of a table:

1. Resizing a column with it's separator/line is still possible even when this line is beneath a frozen column.
2. If you hide a column(s) immediately after a frozen column, you get some weird flickering bug when trying to horizontally scroll to the end of a table.

**Screenshots/Video**

![table_frozen_column_bug_1](https://user-images.githubusercontent.com/22452788/103294095-d25e1e80-49f9-11eb-932f-b848f66b683d.gif)
![table_frozen_column_bug_2](https://user-images.githubusercontent.com/22452788/103294260-2f59d480-49fa-11eb-8674-732b27e90302.gif)

**Standalone, minimal, complete and verifiable example:**
```
ImGui::Begin("Table bug");
{
    int col_count = 10;
    if (ImGui::BeginTable("##table1", col_count, ImGuiTableFlags_Hideable|ImGuiTableFlags_Resizable|ImGuiTableFlags_ScrollX|ImGuiTableFlags_ScrollY)) {
        ImGui::TableSetupColumn("FROZEN COLUMN");
        ImGui::TableSetupColumn("column 1");
        ImGui::TableSetupColumn("column 2");
        ImGui::TableSetupColumn("column 3");
        ImGui::TableSetupColumn("column 4");
        ImGui::TableSetupColumn("column 5");
        ImGui::TableSetupColumn("column 6");
        ImGui::TableSetupColumn("column 7");
        ImGui::TableSetupColumn("column 8");
        ImGui::TableSetupColumn("column 9");

        ImGui::TableSetupScrollFreeze(1, 0);

        ImGui::TableHeadersRow();

        ImGui::TableNextRow();

        ImGui::TableNextColumn();
        static bool checkbox = false;
        ImGui::Checkbox("##checbox", &checkbox);

        for (int column = 1; column < col_count; column++) {
            ImGui::TableNextColumn();
            ImGui::Text("%d", column);
        }

        ImGui::EndTable();
    }
}
ImGui::End();
```

**Comment by ocornut** [comment]
Thank you for those bug reports.
Both issues have now been fixed by commit 0a5f399805b95472046630385b204ca159d88ad5
