### ISSUE TITLE
Asking....

### ISSUE THREAD

**Issue by HideakiAtsuyo** [ocornut/imgui#3683]
How am I supposed to impose a size on a window or make it stop moving?

**Comment by AndrasMumm** [comment]
When you create a window using
```cpp
ImGui::Begin(const char* name, bool* p_open, ImGuiWindowFlags flags)
```
You can use
```cpp
ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize
```
as the "flags" parameter to prevent the window from being resized or moved.

You can use
```cpp
ImGui::SetNextWindowSize(const ImVec2& size, ImGuiCond cond)
```
(where the cond parameter is optional)
before calling "ImGui::Begin" to force a window size.

Example:
```cpp
ImGui::SetNextWindowSize(ImVec2(500,500));
ImGui::Begin("Test Window", nullptr, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize);
//Your stuff
ImGui::End()
```

**Comment by HideakiAtsuyo** [comment]
Thanks bro ❤️
