### ISSUE TITLE
screen shot of window comes to only about 1/4th the io.DisplaySize and blank for  io.DisplaySize * io.DisplayFramebufferScale

### ISSUE THREAD

**Issue by binnytom** [ocornut/imgui#3688]
```
```
Dear ImGui 1.79 WIP (17803)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201402
define: __APPLE__
define: __GNUC__=4
define: __clang_version__=12.0.0 (clang-1200.0.32.28)
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigMacOSXBehaviors
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 7 fonts, Flags: 0x00000000, TexSize: 1024,1024
io.DisplaySize: 1680.00,997.00
io.DisplayFramebufferScale: 2.00,2.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**
I am trying to take a screen shot of my application window but the image size only comes to about 1/4th the DisplaySize.
but when I include  io.DisplayFramebufferScale the screen shot is Empty. Please see below screen Shots.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue

include this file
https://github.com/nothings/stb/blob/master/stb_image_write.h

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

// Main loop
    bool done = false;
#if defined(__EMSCRIPTEN__)
    // See comments around line 30.
    loop = [&]()
    // Note that this doesn't process the 'done' boolean anymore. The function emscripten_set_main_loop will
    // in effect not return, and will set an infinite loop, that is going to be impossible to break. The
    // application can then only stop when the brower's tab is closed, and you will NOT get any notification
    // about exitting. The browser will then cleanup all resources on its own.
#else
    while (!done)
#endif
    {
        // Poll and handle events (inputs, window resize, etc.)
        // You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
        // - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application.
        // - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application.
        // Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
        SDL_Event event;
        while (SDL_PollEvent(&event))
        {
            ImGui_ImplSDL2_ProcessEvent(&event);
            if (event.type == SDL_QUIT)
                done = true;
            if (event.type == SDL_WINDOWEVENT && event.window.event == SDL_WINDOWEVENT_CLOSE && event.window.windowID == SDL_GetWindowID(m_pWindow))
                done = true;
        }
        
        // Start the Dear ImGui frame
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplSDL2_NewFrame(m_pWindow);
        ImGui::NewFrame();
        
        //Start main window here
        ImGui::ShowDemoWindow();
        
```
        ImGui::Begin("Download PNG");
        static bool downloadPNG = false;
        if(ImGui::Button("Download ScreenShot"))
        {
            downloadPNG = true;
        }
        
        ImGui::End();
```
        
        // Rendering
        ImGui::Render();
        SDL_GL_MakeCurrent(m_pWindow, gl_context);
        glViewport(0, 0, (int)io.DisplaySize.x, (int)io.DisplaySize.y);
        
        ImVec4 clear_color = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
        glBlendColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
        SDL_GL_SwapWindow(m_pWindow);
        
```
         if(downloadPNG == true)
         {
             downloadPNG = false;
             
             ImGuiIO io = ImGui::GetIO();
             int x = 0;
             int y = 0;
             int nWidth = io.DisplaySize.x * io.DisplayFramebufferScale.x;
             int nHeight = io.DisplaySize.y * io.DisplayFramebufferScale.y;

             std::vector<unsigned char> pixels(4 * nWidth * nHeight);
             glReadPixels(x, y + nHeight, nWidth, nHeight, GL_RGBA, GL_UNSIGNED_BYTE, pixels.data());
             //GLenum error = glGetError(); returns 0 - No error

             stbi_flip_vertically_on_write(true);
             stbi_write_png("Assets/DemoWindow.PNG", nWidth, nHeight, 4, pixels.data(), 4 * nWidth);
         }
```
    };
#if defined(__EMSCRIPTEN__)
    // See comments around line 30.
    // This function call will not return.
    emscripten_set_main_loop(main_loop, 0, true);
    // A fully portable version of this code that doesn't use the lambda hack might have an #else that does:
    //    while (!done) main_loop();
#endif
    
    return 0;
}

**Comment by binnytom** [comment]
**Screenshots/Video**
Application Window
<img width="1676" alt="Screenshot 2021-01-02 at 14 45 03" src="https://user-images.githubusercontent.com/71374370/103454358-1d817580-4d09-11eb-899b-04a4b414f2e8.png">

ScreenShot comes to only about 1/4th screen size
int nWidth = io.DisplaySize.x;
int nHeight = io.DisplaySize.y;
![_DemoWindow](https://user-images.githubusercontent.com/71374370/103454668-52db9280-4d0c-11eb-8aa3-f3480489a397.PNG)

ScreenShot is blank when I use 
 int nWidth = io.DisplaySize.x * io.DisplayFramebufferScale.x;
 int nHeight = io.DisplaySize.y * io.DisplayFramebufferScale.y;
glError returns '0' - No error
![DemoWindow](https://user-images.githubusercontent.com/71374370/103454734-e8772200-4d0c-11eb-89aa-0b27a96d8d20.PNG)

**Comment by ocornut** [comment]
Sorry but this is not a dear imgui problem this is an OpenGL question, so I need to close this. Please use the discord or another programming community if you need to ask this question.

**Comment by binnytom** [comment]
At last got it working. here is the code.

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"


Add this to the end of while loop after rendering in complete.

void SaveScreenShot(string strFileName)
{
    ImGuiIO io = ImGui::GetIO();
    int x = 0;
    int y = 0;
    int nWidth =  io.DisplaySize.x *  io.DisplayFramebufferScale.x;
    int nHeight = io.DisplaySize.y * io.DisplayFramebufferScale.y;
    
    std::vector<unsigned char> pixels(4 * nWidth * nHeight);
    glReadPixels(x, y, nWidth, nHeight, GL_RGBA, GL_UNSIGNED_BYTE, pixels.data());
    
    stbi_flip_vertically_on_write(true);
    stbi_write_png(strFileName.c_str(), nWidth, nHeight, 4, pixels.data(), 4 * nWidth);
} 

include this file
https://github.com/nothings/stb/blob/master/stb_image_write.h
