### ISSUE TITLE
vulkan validation errors when buffer is resized.

### ISSUE THREAD

**Issue by andesengineering** [ocornut/imgui#3690]
Enabling validation error reporting causes two errors to occur:
 ...
Cannot call vkFreeMemory on VkDeviceMemory 0x400000000040[] that is currently in use by a command buffer.
...
Cannot free VkBuffer 0x380000000038[] that is in use by a command buffer.

These are both triggered by the first vkDestroyBuffer and  vkFreeMemory in CreateOrResizeBuffer() in imgui_impl_vulkan.cpp.  The errors can be squelched with a wait.  Replace:
    VkResult err;
with
    VkResult err = vkDeviceWaitIdle(v->Device);

Cheers.

**Comment by ocornut** [comment]
Hello,

I don't think your solution is right. Those vertex/index buffers are normally created for each frame in flight and that number can be adjusted in ImGui_ImplVulkan_InitInfo's `MinImageCount`, `ImageCount`.

- Please specify which version and branch are you on.
- If this happens on the main viewport or a secondary viewport.
- If this happens in the examples app or if your own app.

**Comment by andesengineering** [comment]
Hello,
Version is v1.80 WIP.   Branch is master.  This occurs on the main viewport and is validation error is triggered by the demoWindow.
But you are correct, I adjusted my ImageCount and the validation error is now gone.

Thanks!
