### ISSUE TITLE
Make a specific window always on top

### ISSUE THREAD

**Issue by MRDuzzz** [ocornut/imgui#3693]
**Version/Branch of Dear ImGui:**
Version: v1.67 WIP
Branch: master

**My Issue/Question:**
How can I do an ImGui::Begin stay always on top. I have 2 ImGui::Begins calls and When they cross, one of them draws over the other,  I want one to always stay above the other. How can I do that?

Well, Idk if you will understand my explanation, I'll attach a screenshot of the issue in this thread.

The second Begin is drawing above my First Begin:
![unknown](https://user-images.githubusercontent.com/76914812/103484801-3d2fa100-4dd0-11eb-9c95-02017cc93402.png)

Thank you and Happy New Year.

**Comment by ocornut** [comment]
It's unclear from your screenshot what the dear imgui window (Begin calls) correspond to.
You can use `GetForegroundDrawList()` if all you need is to render ImDrawList primitives, (GetOverlayDrawList in 1.67).

There's no AlwaysOnTop setting for windows but if you have a limited numbers of windows you can use `ImGuiWindowFlags_NoBringToFrontOnFocus` on the other window as well.

**Comment by ocornut** [comment]
Closing as answered
Linking to #1328, #983, #1892

The issue with a using a flag called "Always On Top" is when you have more than one window with the same flag you get an ambiguity. If we expose arbitrary z/depth settings (either as named enums or absolute flexible) it ends to quickly escalate toward extremes (literally toward the top) + it makes sharing code from different sources more difficult. I don't there is one perfect solution to this problem. Maybe we'll expose a finite number of named layer and allow windows within a same layer to be z-reordered.
