### ISSUE TITLE
How to input capital letters in Dear ImGui

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3697]
I use the openGL version of Dear ImGui,
But in order to better use it on the mobile terminal, I did not use GLFW,
So the keyboard message needs to be handled by myself.
I know that after calling: ImGui_ImplGlfw_Init function, you can use the "Backspace" button,
Now I press "shift" to make the input letter capitalized (press it all the time)
But after I press "Caps", the letters in the input box do not become capitals, which is strange.
Is there anything else I need to set?

**Comment by ocornut** [comment]
The characters are passed by your backend using `io.AddInputCharacterXXX` functions, so this is entirely up to your backends.
Characters are not the same thing as Key, dear imgui cannot make letters uppercase by itself.

**Comment by YuDang1024** [comment]
> The characters are passed by your backend using `io.AddInputCharacterXXX` functions, so this is entirely up to your backends.
> Characters are not the same thing as Key, dear imgui cannot make letters uppercase by itself.

So I should judge by myself whether there is currently: "Caps" key pressed?

**Comment by ocornut** [comment]
I don't think you should ever do that yourself, the OS input messages will provide you characters and you can pass them to dear imgui.

**Comment by YuDang1024** [comment]
> I don't think you should ever do that yourself, the OS input messages will provide you characters and you can pass them to dear imgui.

I used the windows function to determine the state of the "CAPS" key, which can solve this problem, thank you
