### ISSUE TITLE
how to set the menu bar opaque？

### ISSUE THREAD

**Issue by Corezcy** [ocornut/imgui#3698]
Version: 1.7.3
Branch: master
As the title, how to set the `Save as` and its sub-menu opaque???
![Screenshot-20210105144431-2560x1514](https://user-images.githubusercontent.com/33271784/103619070-08f0e780-4f6c-11eb-9404-8a05e819b6d2.png)

**Comment by ocornut** [comment]
Read the ImGuiCol enum or the style editor colors editor. There’s a color value called MenuBg.

**Comment by Corezcy** [comment]
> Read the ImGuiCol enum or the style editor colors editor. There’s a color value called MenuBg.

But the mesh in the background still can be seen even I set the `ImGui::GetStyle().Colors[ImGuiCol_MenuBarBg] = ImVec4(0.40f, 0.40f, 0.55f, 1.0f);`
