### ISSUE TITLE
example_emscripten example doesn't compile to a desktop/native program

### ISSUE THREAD

**Issue by Philius** [ocornut/imgui#3699]
libigl uses imgui and I'm trying to port it to emscripten.
As this process is similiar to cross compiling the first step is to compile it natively, which fails.
I can build it with emsdk and it works fine, but when I modify it to use libigl/Viewer the browser/debugger doesn't provide useful information.

**Comment by Philius** [comment]
I'm using google chrome on Debian amd64 bullseye.

**Comment by rokups** [comment]
Emscripten example is not meant to compile to a native executable. Other examples serve that purpose. You can debug C++ code in the browser if you do a debug build with source maps.

**Comment by Philius** [comment]
After googling "emsdk debug build with source maps" I found I wasn't adding a "-g" to the link step.
A few restarts of the apache web server along with a page refreshes in Google Chrome and I can now see the source code.
One problem is that SDL_init, SDL_InitSubSystem, SDL_EventsInit and SDL_QuitInit all point to glad.c line 86.

Maybe this is a task I should take to emscripten directly, it's meant to be a straight port - just swap clang/clang++ with em/em++.

**Comment by Philius** [comment]
I forked libigl - https://github.com/Philius/libigl
I made enough changes to build a header-only program that compiles to webassembly and as a native program on Debian/amd64 at least.
https://github.com/Philius/event-horizon-webassembly

**Comment by ocornut** [comment]
Hello Philip,

It's unclear to me what exactly you are asking of us there, and the whole issue is confusing to me as none of that blurb:
> libigl uses imgui and I'm trying to port it to emscripten.
As this process is similiar to cross compiling the first step is to compile it natively, which fails.
I can build it with emsdk and it works fine, but when I modify it to use libigl/Viewer the browser/debugger doesn't provide useful information.

Refers to anything in dear imgui.

Is there still a requested action on dear imgui side or can we close this?
Thank you!

**Comment by Philius** [comment]
The whole point of emscripten is that you should need only minimal code changes to allow your program/library to work in a browser.
I demonstrated this by porting libigl to emscripten so I can build natively and for the browser with just one makefile change.
The emscripten example dear imgui provides is as far from this goal as it is possible to get.
If you really can't understand this then go ahead, close it.

**Comment by Philius** [comment]
The example I provided uses dear imgui so there is a way.
The event loop runs constantly, using processor resources needlessly.
WebGL doesn't have wireframe but I'm busy getting it working with something called Barycentric Coordinates to shade the wireframe.

**Comment by ocornut** [comment]
The comment at the top of the file says:
```
// This is mostly the same code as the SDL2 + OpenGL3 example, simply with the modifications needed to run on Emscripten.
// It is possible to combine both code into a single source file that will compile properly on Desktop and using Emscripten.
// See https://github.com/ocornut/imgui/pull/2492 as an example on how to do just that.
```

You are right that we could tweak the other examples e.g. `example_glfw_xxxx`, `example_sdl_xxxx` to build on both desktop and Emscripten, just like we could tweak the Emscripten example to run on Desktop. But either way would currently hinder readability of those examples, as anything OpenGL on desktop is a glorious mess.

I'm going to investigate including the Desktop bits and see if we can make it clean.

Dear ImGui doesn't use wireframe rendering not sure how that is related?

**Comment by ocornut** [comment]
Pushed a test branch, I just diffed the two files and merge the Desktop parts back:
https://github.com/ocornut/imgui/compare/features/emscripten_desktop_build

The problem isn't really to make things works in both, that's implicitly documented by comparing both examples. The problem is that: it makes the example messier and it would requires a better build system to allow building for both (currently makefile only does emscripten). If you can rework the Makefile to support all builds.

**Comment by Philius** [comment]
Being able to build for desktop and web is the whole point of emscripten. Providing an example where you can't do that is bad.
I had no clue as to how to convert it to build a desktop version with the emscripten example which is how I got here.
I agree, it's messy and unclear, but having instructions in the README.me or whatever to the effect of

> set "USE_EMSCRIPTEN = 1" in the makefile for a web build, "USE_EMSCRIPTEN = 0" for a desktop build

would at least make it possible to start down the rabbit hole.
Incidentally, kdbg flat out refuses to load the executable, but gdb works happily. It's clumsy but it at least got me part of the way.
I think I'll bother libigl with how to proceed further.
I just pushed new commits to event-horizon-webassembly and my fork of libigl. They should build on someone elses machine now.
This shows a "dear imgui" menu with a bunny mesh but no wireframes on the web build yet.

**Comment by ocornut** [comment]
> Being able to build for desktop and web is the whole point of emscripten

Yes, but it's not the purpose of Dear ImGui repository to provide ready-to-go frameworks to build apps in every possible scenario. When you have a cross-platform app you need much more engineering that our slim examples/ would ever aim to provide. Merely providing examples that compiles in every possible scenario requires TONS of work which detract us from actually working on the core of dear imgui.

> I had no clue as to how to convert it to build a desktop version with the emscripten exampl

Since it's using SDL and OpenGL you could have stumbled on the "example_sdl_opengl3" folder and notice how closely similar the example are, which is what the highlighted comment intended to specify. Sorry it wasn't more clear.

> set "USE_EMSCRIPTEN = 1" in the makefile for a web build, "USE_EMSCRIPTEN = 0" for a desktop build

I'm not against that but it needs to be implemented by someone, it's not going to happen magically.

**Comment by Philius** [comment]
libigl is my focus now. I created the [event-horizon-webassembly](https://github.com/Philius/event-horizon-webassembly) that works with libigl, you would be the best one to consider changes for "dear imgui".

In case you're interested, here's the libigl issue [link](https://github.com/libigl/libigl/issues/1419#issuecomment-758719201)

**Comment by ocornut** [comment]
FYI : I've pushed 96ab68eee079620b9a2d0e12e9978ade9ad32711 and ce6e6da5102d79d49b34d50dac98150733f181a8 making the SDL+GL and GLFW+GL examples also build and run with Emscripten, without the need for a dedicated Emscripten example. So this is now solved.
