### ISSUE TITLE
Define ImGuiId as a size_t instead of an int for natural view-model mapping

### ISSUE THREAD

**Issue by aniongithub** [ocornut/imgui#3701]
**Version/Branch of Dear ImGui:**

Version: <all>
Branch: <all>

**Back-end/Renderer/Compiler/OS**

Back-ends: n/a
Compiler: n/a
Operating System: n/a

**My Issue/Question:**

`ImGuiId` is currently [defined in imgui.h](https://github.com/ocornut/imgui/blob/94a432275b8ce29fa1dfb36439cfaf325e12a1ab/imgui.h#L189) as an unsigned int. This means it's currently impossible for users to treat a pointer to a data object as an `ImGuiId`. 

Turning it into a `size_t` would let users cast an ImGuiId to whatever data wrapper (size_t -> void* -> _whatever_) they need instead of having to deal with this translation which could be complicated and problematic for large applications.

This would also  make no difference to people currently using it as a simple id (int -> size_t is a widening conversion and is therefore implicit), with some sort of map or other data structure relating the view-id to a view-model class pointer/handle.

**Screenshots/Video**
n/a

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
n/a

If there is interest in this, I'm glad to provide a PR that implements this change. I just wanted to make sure this was desirable before going forward.

Thanks for ImGui, it's one of the most powerful tools in my development arsenal. :+1:  Keep up the great work!

**Comment by ocornut** [comment]
You are not explaining WHY you would ever need to store a pointer in a ImGuID, it seems bizarre considering how ImGuiID are used. Are you aware that function like PushID and GetID can take `void*` to hash into the ID-Stack?

**Comment by aniongithub** [comment]
Thanks, yes - I am aware that's possible. However, my problem is when using pre-made widgets, not directly using ImGui within my application.

I don't see a consensus on how widgets handle user info that is needed for rendering the widget bits. In order to use PushID like you describe, I'd have to invasively change any widgets that accept an int as the id of, say, a selectable within it. I suggested this approach because it would allow widget creators to use a single way to address this issue.

Please correct me if my understanding is wrong.

**Comment by ocornut** [comment]
I think your understanding of how if and the id stack works is wrong and I’m finding it hard to even make sense of your proposal. So i am not sure what to answer you presently.

**Comment by aniongithub** [comment]
Closing this for now. I'll open a new issue with a minimal reproducible sample. It's heavily related to using different kinds of widgets with ImGui though - not ImGui itself.

Thanks for the quick responses.

**Comment by ocornut** [comment]
﻿Make sure you read the FAQ about how the id stack works, too.

**Comment by rokups** [comment]
@aniongithub you can cast `ImGuiID` to any other type by first casting it to `uintptr_t`. For example `void* void_id = (void*)(uintptr_t)id;`.
