### ISSUE TITLE
How I handle Tag name When Dynamically generate Item

### ISSUE THREAD

**Issue by gengzm** [ocornut/imgui#3703]
I have a custom widgets with much items, I want to dynamically generate items, such as InputText, InputInt, TreeNode, and I can unfold/fold them, editor them. As you known, each loop the same item must have same name.
 
Before, I use a self-add variable to name each tag, but there is some thing wrong with the open status when I use TreeNode.

So, How I handle Tag name When Dynamically generate Item.

**Comment by ocornut** [comment]
Please read the FAQ
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it

**Comment by gengzm** [comment]
thank you for you answer. A new problem ,how can i name PushID in recursive call

**Comment by ocornut** [comment]
You don't need to. Read the FAQ again.
