### ISSUE TITLE
OuterRect of Tables overlap what is placed on his right (cause issue for move scrollbar)

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#3704]
**Current/Master:**

Version: Current
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl.cpp 
Compiler: MSVC
Operating System: Win 10 x64

**My Issue/Question:**

I have an issue in my app when i use table with another widgets on the right side.
the scrollbar is difficult to manipulate due to overlaped widgets :

**Screenshots/Video**

![9JHmkMVdlz](https://user-images.githubusercontent.com/1434736/104088906-70f44600-526a-11eb-9320-b34ed065682f.gif)

**Standalone, minimal, complete and verifiable example:**

```
{
            ImGui::Begin("Table issue");
            static ImGuiTableFlags flags = ImGuiTableFlags_SizingPolicyFixed | ImGuiTableFlags_RowBg |
                ImGuiTableFlags_Hideable | ImGuiTableFlags_ScrollY | ImGuiTableFlags_NoHostExtendY;
            if (ImGui::BeginTable("##fileTable", 3, flags, ImVec2(300,0)))
            {
                ImGui::TableSetupScrollFreeze(0, 1); // Make header always visible
                ImGui::TableSetupColumn("aaaa", ImGuiTableColumnFlags_WidthStretch, -1, 0);
                ImGui::TableSetupColumn("bbbb", ImGuiTableColumnFlags_WidthAuto, -1, 1);
                ImGui::TableSetupColumn("cccc", ImGuiTableColumnFlags_WidthAuto, -1, 2);
                ImGui::TableHeadersRow();
                ImGui:ImGuiListClipper clipper;
                clipper.Begin(20, ImGui::GetTextLineHeightWithSpacing());
                while (clipper.Step())
                {
                    for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; i++)
                    {
                        if (i < 0) continue;

                        ImGui::TableNextRow();
                        if (ImGui::TableSetColumnIndex(0)) ImGui::Text("AAAA");
                        if (ImGui::TableSetColumnIndex(1)) ImGui::Text("BBBB");
                        if (ImGui::TableSetColumnIndex(2)) ImGui::Text("CCCC");
                    }
                }
                clipper.End();
                ImGui::EndTable();
            }

            ImGui::SameLine();

            ImGui::BeginChild("##FileTypes");
            static float sliderValue = 0.0;
            for (int i = 0; i < 20; i++)
                ImGui::SliderFloat("slider", &sliderValue, 0, 100);
            ImGui::EndChild();

            ImGui::End();
        }
```

the result with the repo. see whith scrollbar the OuterRect are overlaped's

![jt7CX5SNWg](https://user-images.githubusercontent.com/1434736/104088958-f7108c80-526a-11eb-93a8-1bb7307e627c.gif)

**Comment by ocornut** [comment]
Thank you. That’s definitely a bug with how scrolling tables declare their outer size to the layout system. Should be an easy fix.

**Comment by ocornut** [comment]
Fixed by not overwriting `outer_window->DC.CursorPosPrevLine.x` when using a child window (was previously checking ScrollX only). I made some other tweaks and comments to that code which ultimately should be moved to the layout system.

Thank you for the report.!

**Comment by aiekick** [comment]
Can this fix, be merged in docking too please ? thanks :)
