### ISSUE TITLE
higher

### ISSUE THREAD

**Issue by aFakeCmd** [ocornut/imgui#3707]
Dear ImGui v1.79

Compiler: Visual Studio 2019
Operating System: Win 10

Hello! Why is Text1 higher than Text2? How to fix it?

![image](https://user-images.githubusercontent.com/60480464/104122518-fd405f00-5377-11eb-9617-ff9a703eba07.png)

            ImGui::Text("Test 1");
            ImGui::SameLine();
            ImGui::Checkbox(u8"##123", &test1);
            ImGui::SameLine();
            ImGui::Text(u8"Test2");
            ImGui::SameLine();
            ImGui::Checkbox(u8"##3222", &test2);

**Comment by ocornut** [comment]
See Demo>Layout>Text Baseline Alignment.
