### ISSUE TITLE
 How does ImGui solve the multi-touch problem on the Android platform?

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3711]
**Problem：**
I am using ImGui on the Android platform, and now I have a problem: ImGui cannot perform multi-touch.
**Why should I implement multi-touch:**
I want to use ImGui to make a virtual joystick on the left side of the Android screen (already implemented), and then make some buttons on the right side of the screen to allow the player to control the movement of the NPC while performing some other operations.
**Solution 1**
At present I have a simple solution, but it cannot meet the needs of the future.
(I use half of the screen width as the dividing line) The virtual joystick on the left side of the screen, I use Dear ImGui to draw, and its touch can be controlled by DearImGui, and the touch on the right side of the screen I let Android control it.
This way the two parties will not affect, but the problem with this solution is: if there are two or more buttons on the right side of my screen, I need to use Android UI to draw to meet the specific coordinate point on the right side of the screen Click action.
This is not in line with the original cross-platform principle. So this plan is not appropriate.
**Solution 2**
In the previous exchange,
Someone recommended that SDL can be a solution in Android.
I studied SDL and found that if you want to use SDL, you must use SDL to create a window. In the window, SDL can receive and process screen touch messages.
So I tried to draw with DearImGui and use SDL to receive messages, but the user does not need to see anything in SDL in the interface. I did not find any interface in SDL that allows me to draw a fully transparent on the Android platform. Window,
When I use SDL's SDL_WINDOW_HIDDEN flag, it seems that the SDL window no longer accepts window messages.

It seems that the SDL method has some small details that I did not consider, or is there any solution that can be provided in the current version of DearImGui.
If you have any ideas, you can communicate with me here, thank you very much, this question is very important to me

**Comment by YuDang1024** [comment]
There is an interface to set the background color in SDL, but it seems that the background cannot be transparent
`SDL_SetRenderDrawColor(m_pRenderer, 0, 0, 0, SDL_ALPHA_TRANSPARENT);`

Some authors on the forum provide a method to use Windows API to set window transparency, but Windows API must not be used in Android.
Looking forward to your reply.

**Comment by PathogenDavid** [comment]
ImGui does not support multitouch. (https://github.com/ocornut/imgui/issues/165)

> I want to use ImGui to make a virtual joystick on the left side of the Android screen (already implemented), and then make some buttons on the right side of the screen to allow the player to control the movement of the NPC while performing some other operations.

My gut reaction is you are trying to use Dear ImGui for things it isn't designed to accomplish.

**Comment by ocornut** [comment]
> How does ImGui solve the multi-touch problem on the Android platform? 

It does not.
If you want multi-touch in your app you can use Android inputs facilities and make your custom widgets use those inputs.

**Comment by YuDang1024** [comment]
DearImGui has such a strong cross-platform, if it does not support multi-touch, it is really a pity, I have used DearImGui development on the mobile platform for a long time.
At present, there is only one problem left unsolved, which is very important to me.
I will think about other solutions.
If you see this post and have some suggestions, I hope you can leave a message for me and we can discuss it.
Thanks~!

**Comment by ocornut** [comment]
Closing as answered.
