### ISSUE TITLE
Is there a way for block navigation for custom widgets ?

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#3712]
its not an issue. 

in ImGuiFileDialog, i have implemented up/down return/backspace navigation for explore file/directory list

you navigation system work like a charm for select widgets.

but when the file list is focused i would like to have a way for block your navigation.
for have mine only working. like i can explore the list with my navigation system only when the file lsit is focused.

here you see my navigation work in parrallel of your and its annoying.
![d6RQXsQ2aQ](https://user-images.githubusercontent.com/1434736/104278153-6aeba880-54a8-11eb-8d17-0fe2311ea1a5.gif)

by ex i would like to press ctrl key when the file list is focused. and with ctrl key pressed navigate with my system

if i implement the imgui nav system in my filelist, it can be annoying when we have big file list

i not found a way in the src files for doing that. but maybe i miss something.

**Comment by ocornut** [comment]
For a specific window you can use the `ImGuiWindowFlags_NoNav` or `ImGuiWindowFlags_NoNavInputs` flag.

For specific widget there are internals facilities such as `ActiveIdUsingNavDirMask`, `ActiveIdUsingNavInputMask` but they are only partially supported and need to be improved on a per-need basis.

**Comment by aiekick** [comment]
thanks, will try that

**Comment by aiekick** [comment]
hello,

Finally i got a solution to my problem, 
but its like a hack (no imgui modification, but playing with some vars who are maybe not made for that :) )

when the NavId is the listview id, if i hit the enter key i active my list view nav system
if i hit the escape key i go back to the imgui navigation
 
![oIg7An1Fcb](https://user-images.githubusercontent.com/1434736/108575697-5b6b4500-731b-11eb-9e33-8265e5ddbe8b.gif)

but not sure if its robust enough
because i read and write directly g.LastActiveId

is there a better (more robust in time) way ?

i activate the item with both ImGui::ActivateItem and ImGui::SetActiveID.
at first i was using only ImGui::SetActiveID, but the nav highlight was disapearing, and i would like to keep it

here my code :

```cpp
bool canWeExplore = false;
bool hasNav = (ImGui::GetIO().ConfigFlags & ImGuiConfigFlags_NavEnableKeyboard);
			
ImGuiContext& g = *GImGui;
if (!hasNav && !g.ActiveId) // no nav and no activated inputs
    canWeExplore = true;

if (g.NavId && g.NavId == vListViewID)
{
    if (ImGui::IsKeyPressedMap(ImGuiKey_Enter) ||
        ImGui::IsKeyPressedMap(ImGuiKey_KeyPadEnter))
    {
        ImGui::ActivateItem(vListViewID);
        ImGui::SetActiveID(vListViewID, g.CurrentWindow);
    }
}
			
if (vListViewID == g.LastActiveId-1) // if listview id is the last acticated nav id (ImGui::ActivateItem(vListViewID);)
    canWeExplore = true;

if (canWeExplore)
{
    if (ImGui::IsKeyPressedMap(ImGuiKey_Escape))
    {
        ImGui::ClearActiveID();
        g.LastActiveId = 0;
    }

    // actions
}
```

what do you think about it ?

**Comment by ocornut** [comment]
See general answer in https://github.com/ocornut/imgui/issues/3560#issuecomment-1458502821
And examples in the demo of that temporary branch (will be merged in public demo when the API becomes public)
https://github.com/ocornut/imgui/compare/features/demo_input_owner_and_routing

You can claim ownership of a key ahead of time and Nav system won't use that key.
