### ISSUE TITLE
Strange behaviour of ImGui::PushStyleVars and ImGui::PopStyleVars

### ISSUE THREAD

**Issue by rdbo** [ocornut/imgui#3717]
**Version/Branch of Dear ImGui:**

Version: Latest Commit - 9e281c12a8b62d6262494669d560bf876209e632
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_directx9.cpp
Compiler: Microsoft Visual C++
Operating System: Windows 10 (up-to-date)

**My Issue/Question:**

I'm making a menu that relies on ImGui::PushStyleVar and ImGui::PopStyleVar. Basically, this menu has a top bar which does not contain any spacing or padding between items and the main window. After that menu is drawn, the style vars are reset to their original value by using ImGui::PopStyleVar. The problem is, after I push the style vars, they either don't apply on push or don't reset back on pop. If I push before calling ImGui::Begin, the style vars work and the padding/spacing is removed. But when I pop those same style vars before ImGui::End, nothing changes and whatever is drawn next still follows the previously pushed style vars (see Example 1). If I push after calling ImGui::Begin, the style vars aren't applied at all (see Example 2). This is a strange behaviour, as there would be no point (or at least, not that I can see) in implementing Push/Pop style vars if they can't be modified after the drawing has started.

**Screenshots/Video**

Example 1 Result (notice that the Text drawn after Pop doesn't have padding/spacing):
![imgui_style_1](https://user-images.githubusercontent.com/57117082/104692715-3154b080-56e7-11eb-9861-02b19cb0019b.png)

Example 2 Result (notice that the Style Vars are not applied):
![imgui_style_2](https://user-images.githubusercontent.com/57117082/104692760-45001700-56e7-11eb-9987-5026ad027ecc.png)

**Standalone, minimal, complete and verifiable example:**

Example 1 Code:
```c++
void DrawImGui()
{
    static const char*  MenuList[] = { "Tab1", "Tab2", "Tab3", "Tab4" };
    static const int    MenuCount = sizeof(MenuList) / sizeof(MenuList[0]);
    static const ImVec2 MenuTabSize = ImVec2(120.0f, 32.0f);
    static const float  MenuContentSpace = 300.0f;
    static const ImVec2 MenuWindowSize = ImVec2(MenuTabSize.x * MenuCount, MenuTabSize.y + MenuContentSpace);
    static int          TabActive = 0;

    //Set Menu Window Size
    ImGui::SetNextWindowSize(MenuWindowSize);

    //Remove spacing/padding while drawing the Top Menu Bar
    ImGui::PushStyleVar(ImGuiStyleVar_IndentSpacing, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0f, 0.0f));
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));

    ImGui::Begin("Dear ImGUI Window", 0, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse);

    ImGui::Columns(MenuCount, 0, false);
    for (int i = 0; i < MenuCount; i++)
    {
        if (ImGui::Button(MenuList[i], MenuTabSize)) TabActive = i;
        ImGui::NextColumn();
    }

    //Done drawing the Top Menu Bar, set padding/space values to default

    ImGui::PopStyleVar(3);

    //Draw content for each selected tab

    ImGui::Columns(1);

    switch (TabActive)
    {
    case 0:
    case 1:
    case 2:
    case 3:
        ImGui::Text("Testing Padding/Spacing. Active Tab: %i", TabActive);
        break;
    default:
        TabActive = 0;
        break;
    }

    ImGui::End();

}
```

Example 2 Code:
```c++
void DrawImGui()
{
    static const char*  MenuList[] = { "Tab1", "Tab2", "Tab3", "Tab4" };
    static const int    MenuCount = sizeof(MenuList) / sizeof(MenuList[0]);
    static const ImVec2 MenuTabSize = ImVec2(120.0f, 32.0f);
    static const float  MenuContentSpace = 300.0f;
    static const ImVec2 MenuWindowSize = ImVec2(MenuTabSize.x * MenuCount, MenuTabSize.y + MenuContentSpace);
    static int          TabActive = 0;

    //Set Menu Window Size
    ImGui::SetNextWindowSize(MenuWindowSize);

    ImGui::Begin("Dear ImGUI Window", 0, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse);

    //Remove spacing/padding while drawing the Top Menu Bar
    ImGui::PushStyleVar(ImGuiStyleVar_IndentSpacing, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0f, 0.0f));
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));

    ImGui::Columns(MenuCount, 0, false);
    for (int i = 0; i < MenuCount; i++)
    {
        if (ImGui::Button(MenuList[i], MenuTabSize)) TabActive = i;
        ImGui::NextColumn();
    }

    //Done drawing the Top Menu Bar, set padding/space values to default

    ImGui::PopStyleVar(3);

    //Draw content for each selected tab

    ImGui::Columns(1);

    switch (TabActive)
    {
    case 0:
    case 1:
    case 2:
    case 3:
        ImGui::Text("Testing Padding/Spacing. Active Tab: %i", TabActive);
        break;
    default:
        TabActive = 0;
        break;
    }

    ImGui::End();

}
```

**Comment by ocornut** [comment]
Sorry but #1586
