### ISSUE TITLE
Disable setting custom value of sliders

### ISSUE THREAD

**Issue by rekted2137** [ocornut/imgui#3719]
Hey!

When you press "tab", you can type a custom value of int (ImGui::SliderInt, ImGui::SliderFloat)
The problem is: using this, you can set value out of range. How can i disable this, or prevent
setting values out of range?

Thanks!

**Comment by ocornut** [comment]
You can use `ImGuiSliderFlags_AlwaysClamp` to have the input clamp value or `ImGuiSliderFlags_NoInput` to disable it.

(PS: Please make sure you have read the guidelines and please fill the Issue Template when opening a issue!)
