### ISSUE TITLE
Imgui with win32 and OpenGl

### ISSUE THREAD

**Issue by anshul-soni** [ocornut/imgui#372]
So I am using win32 api to create my window and opengl for rendering.
I am little bit confused on how to implement imgui withing my interface. I couldnt find any example which does that. 
Can you please help me out with the same ?
Thanks.

**Comment by ocornut** [comment]
You may want to look at those example too
https://github.com/ocornut/imgui/pull/281

**Comment by anshul-soni** [comment]
Okay that is helpful thanks a lot but I cannot use that because I am trying to integrate it in my engine, and my window creation and open gl initialization are being done in respective systems. But I got it working.
Except I am doing something wrong and I am not sure whats wrong would you possible know whats wrong in here ?
My code for drawing is
    static float f = 0.0f;
			ImGui::Text("Hello, world!");
			ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
			ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f /       ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);

![imgui](https://cloud.githubusercontent.com/assets/5556759/10496047/bbad2aa4-7273-11e5-8f82-cee777cb18f4.png)

**Comment by anshul-soni** [comment]
Thanks  a lot for that, thats really helpful !!
I actually cant do that, because my window is created by my window system and opengl is initialized in my graphics system. But I got it working. :+1:

**Comment by ocornut** [comment]
Good to hear. Anything you stumbled on? Looking for idea on how we can improve the documentation for future users.

**Comment by anshul-soni** [comment]
So I was able to do everything but the input.
My input call back method is inside windows system and its assigned to windows in there.
My editor is using the libraries of my engine to run, so I am not sure how to handle the input yet.

**Comment by anshul-soni** [comment]
```
enyin::Engine engine;
	engine.Start(hInstance);
	HWND hwnd = enyin::WindowSystem::GetInstance().getWindowHandler();
	ImGui_Init(hwnd);
	ImVec4 clear_color = ImColor(114, 144, 154);
	while (true)
	{

		engine.GameLoop();
		ImGui_NewFrame();
		{
			static float f = 0.0f;
			ImGui::Text("Hello, world!");
			ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
			ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
		}
		RECT rect;
		GetClientRect(hwnd, &rect);
		glViewport(0, 0, (float)(rect.right - rect.left), (float)(rect.bottom - rect.top));
		ImGui::Render();
	}
	//deletes all resources when the game finishes.
	engine.Release();
```

**Comment by anshul-soni** [comment]
So this is code of main in my editor, which lets me render the imgui. But still couldnt figure out how to handle inputs in imgui with this approach.
```
        Engine::Engine engine;
	engine.Start(hInstance);
	HWND hwnd = enyin::WindowSystem::GetInstance().getWindowHandler();
	ImGui_Init(hwnd);
	ImVec4 clear_color = ImColor(114, 144, 154);
	while (true)
	{

		engine.GameLoop();
		ImGui_NewFrame();
		{
			static float f = 0.0f;
			ImGui::Text("Hello, world!");
			ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
			ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
		}
		RECT rect;
		GetClientRect(hwnd, &rect);
		glViewport(0, 0, (float)(rect.right - rect.left), (float)(rect.bottom - rect.top));
		ImGui::Render();
	}
	//deletes all resources when the game finishes.
	engine.Release();
```

**Comment by ocornut** [comment]
Just call both, maybe call the ImGui wndproc help at the beginning of yours.

Also you probably want ImGui::NewFrame to be called early in your frame (aka inside or before GameLoop) and ImGui::Render() to be called at the very end.

**Comment by anshul-soni** [comment]
:+1:  So in each case inside the callback for imgui, I am in turn calling the callback of my engine. 
And it works.
Thanks a lot  :smile:

**Comment by anshul-soni** [comment]
ImGui::GetIO().Framerate doesnt work, its always -1

**Comment by ocornut** [comment]
You aren't setting DeltaTime every frame.

**Comment by anshul-soni** [comment]
Cool !! I didn't see that thing in newframe !!
Now looks like I got everything up and running.
