### ISSUE TITLE
Is it possible to make 2D polygon editor?

### ISSUE THREAD

**Issue by NukeBird** [ocornut/imgui#3720]
**Version/Branch of Dear ImGui:**

Version: 1.79 (from conan.io)
Branch: imgui_master
**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Visual Studio 2019
Operating System: Windows 10

**My Issue/Question:**

Is it possible to make polygon editor using imgui? I know its not in straight responsibility of library but any code snippet or advice will be appreciated. Polygon editor should be able to add new points, to move points around and to remove already spawned points. In advance I know that I will never need lots of points 

I need these polygons to map specific areas from one Image to another via OpenGL (I know how, it is not a problem). I know how to get uvs from positions relative to specific Image and etc.

**Comment by PathogenDavid** [comment]
It's definitely possible, but as you've noted it's not something ImGui will necessarily do for you.

Check out the [draw list API](https://github.com/ocornut/imgui/blob/6470681d87de83018aaf85e118a6f5ab4df65e67/imgui.h#L2317-L2324). In particular, you'd probably find `AddConvexPolyFilled` or the `Path*` functions to be useful.

There's an [example of using the draw list API in the demo](https://github.com/ocornut/imgui/blob/6470681d87de83018aaf85e118a6f5ab4df65e67/imgui_demo.cpp#L7012), which you can access via Examples > Custom Rendering.

![image](https://user-images.githubusercontent.com/278957/104782449-d1432600-5749-11eb-8678-07e9807b4687.png)

It even includes an example of a small canvas you can draw lines on that you could likely use as a basis for your editor:

![image](https://user-images.githubusercontent.com/278957/104782524-f6379900-5749-11eb-86b4-c6292e89b7d1.png)

**Comment by NukeBird** [comment]
Hmm... Looks like a good place to start, thanks! I can start from triangle and try to move its points around
What a good strategy to mark active and inactive points? To decide at which point I clicked guess I need to do dot x circle collision test (basically check distance between two points)

**Comment by PathogenDavid** [comment]
> What a good strategy to mark active and inactive points?

I feel like the easiest way is just to keep an index into your vector of points or something similar. Unless you meant visually, in which case just add circles to represent the points.

> To decide at which point I clicked guess I need to do dot x circle collision test (basically check distance between two points)

Yup. It'll probably take a lot of tweaking to make things feel right. (IE: Determining if a click means to change selection or to move a point.)

**Comment by NukeBird** [comment]
Thank you. Finally I finished it
