### ISSUE TITLE
ImFont::RenderChar not push the corresponding ImFont TextureID

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#3727]
**Version/Branch of Dear ImGui:**

Version: Current
Branch: master

**My Issue/Question:**

Not sure if its a bug or wanted for perf.

in my soft i needed to render char individualy and i see you have a method for that called : ImFont::RencerChar
but if im using an ImFont object who is not the current and decided to render this char, for have the good rendering,
i need to do window->DrawList->PushTextureID(font->ContainerAtlas->TexID;); before for make it work.

maybe its inentionnal for perf. i thinck the PushTextureID is made by PushFont.
but when we call a function like that we think she take into account the corresponding font texture.

i searched the issue from many 1 hour :)

**Comment by ocornut** [comment]
Hello Aiekick,

It is intended, every primitives in ImDrawList expect the FontAtlas to be bound.
I will add extra comments around those functions to clarify this.

**Comment by aiekick** [comment]
Hello,

ok thanks :)
