### ISSUE TITLE
Windows flags are not working.

### ISSUE THREAD

**Issue by LionHackerman** [ocornut/imgui#3729]
Hey, I've added the flags (ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoTitleBar) to ImGui::Begin() but they don't work. However it works when I use it on a 'if' statement down the line the flags work.

Here's the [code](https://pastebin.com/NbwRnM25)

**Comment by ocornut** [comment]
Sorry but #1586
