### ISSUE TITLE
How to make single selection when there are multiple TreeNodes？

### ISSUE THREAD

**Issue by YuDang1024** [ocornut/imgui#3732]
I need to display about 9 TreeNodes on the window. I hope that when I open one of the TreeNodes, the rest of the TreeNodes will be closed (not expanded).
But I did not find a suitable interface to do this.
Has anyone tried this, or is there any interface that can tell me.
Thanks~!

**Comment by PathogenDavid** [comment]
Have you ensured the separate tree nodes have different IDs? (By default the label is used as the ID. Therefore if they all have the same label, they'll all have the same ID. Which means that expanding one will expand the others too.)

See [this Q&A section](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-multiple-widgets-with-the-same-label) for more details.

**Comment by YuDang1024** [comment]
> Have you ensured the separate tree nodes have different IDs? (By default the label is used as the ID. Therefore if they all have the same label, they'll all have the same ID. Which means that expanding one will expand the others too.)
> 
> See [this Q&A section](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-multiple-widgets-with-the-same-label) for more details.

I am sure there are different IDs. Do you mean that I can use the ID to close the corresponding TreeNode?
So what interface should I use?

**Comment by YuDang1024** [comment]
> Have you ensured the separate tree nodes have different IDs? (By default the label is used as the ID. Therefore if they all have the same label, they'll all have the same ID. Which means that expanding one will expand the others too.)
> 
> See [this Q&A section](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-multiple-widgets-with-the-same-label) for more details.

If the ID is the same, then I open the first one, and the second one will also open. I understand this.
But now I think when I open the first one, the second one closes.
When the second one is opened, the first one is closed.

**Comment by PathogenDavid** [comment]
Oh, I misunderstood your question. Sorry about that!

You should be able to accomplish what you want using `SetNextItemOpen`. I don't believe this is something ImGui will automatically do for you.

**Comment by YuDang1024** [comment]
> Oh, I misunderstood your question. Sorry about that!
> 
> You should be able to accomplish what you want using `SetNextItemOpen`. I don't believe this is something ImGui will automatically do for you.

I have used the SetNextItemOpen interface.
I don't know if there is a problem with the method I used, it seems that he can't solve my problem.
The situation is like this:
In the initial state, TreeNodes with ID: 1-9 are all closed.
When I click on the TreeNode with ID: 1, it opens normally.
When I click on the TreeNode with ID: 2, ID: 1 needs to be closed,
But at this time, the TreeNode with ID: 1 is not the next one.
As far as I know, SetNextItemOpen can only close the next Item.
I wonder if I made it clear?

**Comment by PathogenDavid** [comment]
Yeah, you'd need to close ID 1 in response to ID 2 opening on the next frame.

Unfortunately would probably result in a brief frame where both are visible at once. You could avoid this by delaying showing the contents of ID 2 by a single frame.

Alternatively you might consider using radio buttons instead. They're probably the easiest way to accomplish this behavior without jank.

**Comment by YuDang1024** [comment]
> Yeah, you'd need to close ID 1 in response to ID 2 opening on the next frame. The way Dear ImGui works, once you submit something you generally can't change anything about it until you submit it again on the next frame.
> 
> Unfortunately would probably result in a brief frame where both are visible at once. You could avoid this by delaying showing the contents of ID 2 by a single frame.
> 
> Alternatively you might consider using radio buttons instead. They're probably the easiest way to accomplish this behavior without jank.

Then which interface should I use to close the TreeNode corresponding to the ID?
At the same time: radio buttons are a good solution

**Comment by PathogenDavid** [comment]
> Then which interface should I use to close the TreeNode corresponding to the ID?

You would need to keep track of your own state and use `SetNextItemOpen` on the next frame.

For example, you could do something like this:

```cpp
static int NodeToClose = -1;
static int CurrentNode = -1;

//-------------------------------------------------------------------------
// Submit node 0
//-------------------------------------------------------------------------
if (NodeToClose == 0)
{
    ImGui::SetNextItemOpen(false, ImGuiCond_Always);
    NodeToClose = -1;
}
if (ImGui::TreeNode("Node0"))
{
    if (CurrentNode == 0)
    {
        ImGui::Text("This is the contents of Node0");
    }
    else
    {
        NodeToClose = CurrentNode;
        CurrentNode = 0;
    }
    ImGui::TreePop();
}

//-------------------------------------------------------------------------
// Submit node 1
//-------------------------------------------------------------------------
if (NodeToClose == 1)
{
    ImGui::SetNextItemOpen(false, ImGuiCond_Always);
    NodeToClose = -1;
}
if (ImGui::TreeNode("Node1"))
{
    if (CurrentNode == 1)
    {
        ImGui::Text("This is the contents of Node1");
    }
    else
    {
        NodeToClose = CurrentNode;
        CurrentNode = 1;
    }
    ImGui::TreePop();
}

//-------------------------------------------------------------------------
// Submit node 2
//-------------------------------------------------------------------------
if (NodeToClose == 2)
{
    ImGui::SetNextItemOpen(false, ImGuiCond_Always);
    NodeToClose = -1;
}
if (ImGui::TreeNode("Node2"))
{
    if (CurrentNode == 2)
    {
        ImGui::Text("This is the contents of Node2");
    }
    else
    {
        NodeToClose = CurrentNode;
        CurrentNode = 2;
    }
    ImGui::TreePop();
}
```

**Comment by YuDang1024** [comment]
> > Then which interface should I use to close the TreeNode corresponding to the ID?
> 
> You would need to keep track of your own state and use `SetNextItemOpen` on the next frame.
> 
> For example, you could do something like this:
> 
> ```c++
> static int NodeToClose = -1;
> static int CurrentNode = -1;
> 
> //-------------------------------------------------------------------------
> // Submit node 0
> //-------------------------------------------------------------------------
> if (NodeToClose == 0)
> {
>     ImGui::SetNextItemOpen(false, ImGuiCond_Always);
>     NodeToClose = -1;
> }
> if (ImGui::TreeNode("Node0"))
> {
>     if (CurrentNode == 0)
>     {
>         ImGui::Text("This is the contents of Node0");
>     }
>     else
>     {
>         NodeToClose = CurrentNode;
>         CurrentNode = 0;
>     }
>     ImGui::TreePop();
> }
> 
> //-------------------------------------------------------------------------
> // Submit node 1
> //-------------------------------------------------------------------------
> if (NodeToClose == 1)
> {
>     ImGui::SetNextItemOpen(false, ImGuiCond_Always);
>     NodeToClose = -1;
> }
> if (ImGui::TreeNode("Node1"))
> {
>     if (CurrentNode == 1)
>     {
>         ImGui::Text("This is the contents of Node1");
>     }
>     else
>     {
>         NodeToClose = CurrentNode;
>         CurrentNode = 1;
>     }
>     ImGui::TreePop();
> }
> 
> //-------------------------------------------------------------------------
> // Submit node 2
> //-------------------------------------------------------------------------
> if (NodeToClose == 2)
> {
>     ImGui::SetNextItemOpen(false, ImGuiCond_Always);
>     NodeToClose = -1;
> }
> if (ImGui::TreeNode("Node2"))
> {
>     if (CurrentNode == 2)
>     {
>         ImGui::Text("This is the contents of Node2");
>     }
>     else
>     {
>         NodeToClose = CurrentNode;
>         CurrentNode = 2;
>     }
>     ImGui::TreePop();
> }
> ```
> 
> (This is just an example, obviously you'd want to package things up into nice functions to make it more readable.)

I forgot to reply to you. Your method is correct. Thank you for your help.
Thank you~~

**Comment by PathogenDavid** [comment]
No problem, glad I could help!
