### ISSUE TITLE
Child window popup with multi-viewport enabled does not respond to clicks under certain condition

### ISSUE THREAD

**Issue by zhicheng1458** [ocornut/imgui#3734]
**Version/Branch of Dear ImGui:**

Version: v1.80 WIP
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Microsoft Visual Studio
Operating System: Windows 10

**My Issue/Question:**

Child window popup with multi-viewport enabled does not respond to clicks when the following condition are met:
1. Popup are not fully encapsulated within the glfw window where it is called upon.
2. Clicks are made on the area of the popup that are within the glfw window.

Clicking on the popup outside of the glfw window has no issue.  The behavior seems to replicate a unfocused child window that gets drawn on top of the glfw window where it is called upon.

**Screenshots/Video**

https://user-images.githubusercontent.com/76796010/105149037-f4f2cd00-5ab7-11eb-901a-8be9df180bd3.mp4

https://user-images.githubusercontent.com/76796010/105146505-f078e500-5ab4-11eb-9d5a-33633b7ca248.mp4

**Standalone, minimal, complete and verifiable example:**
Paste the following into the demo's main.cpp
```
            ImGuiViewport* main_viewport = ImGui::GetMainViewport();
            //Set the next window near the bottom left corner of the application, but without going out of bound
            ImGui::SetNextWindowSize(ImVec2(300.0f, 50.0f), ImGuiCond_Once);
            ImGui::SetNextWindowPos(ImVec2(main_viewport->GetWorkPos().x + 5.0f, main_viewport->GetWorkPos().y + main_viewport->GetWorkSize().y - 150.0f), ImGuiCond_Once);
            ImGui::Begin("Test");
            ImGui::ColorEdit4("##color", (float*)&style.Colors[0]);
            ImGui::End();
```

**Comment by ThirdPartyNinjas** [comment]
Tested this and I get the same result on SDL+OpenGL3 on Windows 10.

I was typing up my own report, but I'm pretty sure it's the same focus issue:
If I drag a window into its own viewport, but leave it overlapped with the original, when I click on the title bar for the new window, the click goes through to the original window. If I instead click on the title bar outside the original window, it works fine.

**Comment by eclbtownsend** [comment]
Also ran into this issue after updating to 1.8 from 1.73 on sdl2 opengl3:
```
Dear ImGui 1.80 (18000)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: _WIN32
define: _WIN64
define: _MSC_VER=1916
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x0000C441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
 DpiEnableScaleViewports
 DpiEnableScaleFonts
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140A
 HasMouseCursors
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
 ```

![combo](https://user-images.githubusercontent.com/35241930/107413394-f10e0580-6acd-11eb-8ed9-d00822c75721.gif)

**Comment by eclbtownsend** [comment]
Found the issue I think! after the child popup is opened, the parent is getting it's topmost stamp count incremented by one so imgui state think it's more topmost than it's popup child.

This broke with https://github.com/ocornut/imgui/commit/6bc52667

Not sure if this is just a simple oversight or if there was more to it! I can put up a PR putting PlatformLastFocusedViewport back in if it's desired.

**Comment by ocornut** [comment]
Thank you @eclbtownsend for the report and investigation. Will look at it now and try to push a fix (or revert).

**Comment by ocornut** [comment]
I can confirm the issue is in the path inferring platform focus-order, used for backends which don't have the `ImGuiBackendFlags_HasMouseHoveredViewport` feature (both GLFW and SDL backends don't have this flag set).

The problem is that I think 6bc52667 is correct, the old behavior was semi accidentally fixing a bug.

We intentionally request some types of windows to have the `ImGuiViewportFlags_NoFocusOnAppearing` , there are two reasons for that:
- While dragging windows out of a host viewport we do it because stealing focus tends to steal inputs on high-level systems like GLFW/SDL.
- While showing short-lived popups and particularly those without decorations we do it so the main host title bar doesn't lose focus colors. It does make some sense but is at the heart of our issue as those popups shows in bugs above are flagged as such.

The problem is that z-order is not the same as focus and we currently maintain a focus stack while we should maintain a z-order stack. I'm going to work on it.

**Comment by ocornut** [comment]
I looked at this from various angles and concluded the best answer presently was to essentially revert 6bc52667, which I did with 3607c42bec99c9c9f5cfe17d5658de8179cd5355. Also added comments, and additional debug infos in Metrics.

Thank you everyone for your help and apologies for the late reaction to @zhicheng1458 post.
