### ISSUE TITLE
How I can add icon and text on button?(and why delete my previous issue)

### ISSUE THREAD

**Issue by xingyun86** [ocornut/imgui#3750]
How I can add icon and text on button?(and why delete my previous issue)
Now I can show image on button use imagebutton. But How to show image and text on button?

**Comment by xingyun86** [comment]
I solved it now. I rewrite a method to realized it. For all need it.

bool ImGui::ImageLabelButtonEx(ImGuiID id, ImTextureID texture_id, const ImVec2& image_size, const char* label, const ImVec2& label_size, const ImVec2& uv0, const ImVec2& uv1, const ImVec2& padding, const ImVec4& bg_col, const ImVec4& tint_col, ImGuiButtonFlags flags)
{
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = GetCurrentWindow();
    if (window->SkipItems)
        return false;

    const ImVec2 label_text_size = CalcTextSize(label, NULL, true);
    ImVec2 label_real_size = CalcItemSize(label_size, label_text_size.x + padding.x * 2.0f, label_text_size.y + padding.y * 2.0f);
    const ImRect bb(window->DC.CursorPos, window->DC.CursorPos + ImVec2(image_size.x + label_real_size.x, (image_size.y > label_real_size.y) ? image_size.y : label_real_size.y) + padding * 2.0f);
    ItemSize(bb);
    if (!ItemAdd(bb, id))
        return false;

    bool hovered, held;
    bool pressed = ButtonBehavior(bb, id, &hovered, &held);

    // Render
    const ImU32 col = GetColorU32((held && hovered) ? ImGuiCol_ButtonActive : hovered ? ImGuiCol_ButtonHovered : ImGuiCol_Button);
    RenderNavHighlight(bb, id);
    RenderFrame(bb.Min, bb.Max, col, true, ImClamp((float)ImMin(padding.x, padding.y), 0.0f, g.Style.FrameRounding));
    if (bg_col.w > 0.0f)
        window->DrawList->AddRectFilled(bb.Min + padding, bb.Max - padding, GetColorU32(bg_col));
    window->DrawList->AddImage(texture_id, bb.Min + padding, bb.Min + image_size + padding, uv0, uv1, GetColorU32(tint_col));
    RenderTextClipped(bb.Min + ImVec2(image_size.x, 0) + padding, bb.Max - padding, label, NULL, &label_text_size, g.Style.ButtonTextAlign, &bb);

    return pressed;
}
bool ImGui::ImageLabelButton(ImTextureID user_texture_id, const ImVec2& image_size, const char* label, const ImVec2& label_size, const ImVec2& uv0, const ImVec2& uv1, int frame_padding, const ImVec4& bg_col, const ImVec4& tint_col)
{
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = g.CurrentWindow;
    if (window->SkipItems)
        return false;

    // Default to using texture ID as ID. User can still push string/integer prefixes.
    PushID((void*)(intptr_t)user_texture_id);
    const ImGuiID id = window->GetID("#imagelabel");
    PopID();

    const ImVec2 padding = (frame_padding >= 0) ? ImVec2((float)frame_padding, (float)frame_padding) : g.Style.FramePadding;
    return ImageLabelButtonEx(id, user_texture_id, image_size, label, label_size, uv0, uv1, padding, bg_col, tint_col, ImGuiButtonFlags_None);
}

**Comment by ocornut** [comment]
Your previous post was moved to the Discussions panel:
https://github.com/ocornut/imgui/discussions/3745

> (and why delete my previous issue)

You ignored issue template.

**Comment by xingyun86** [comment]
> Your previous post was moved to the Discussions panel:
> #3745
> 
> > (and why delete my previous issue)
> 
> You ignored issue template.

ok。Now you can close it for me。 Thanks very much。
