### ISSUE TITLE
PushStyleColor and PopStyleColor are giving me trouble

### ISSUE THREAD

**Issue by MorganaBRKSRL** [ocornut/imgui#3755]
Hello! So, my problem comes from the 2 PushStyleColor in the beginning and the PopStyleColor(2) in the ending. The function Helpers::calculateColor(RNBW) is changing it's own value every frame, so it's changing it's color as I want to have my border and active tabs with a rainbow effect. However, if I Pop in the end( as in this example below ), the border stays and the other one refuses to appear. If I put both of them like this:
`
ImGui::PushStyleColor(ImGuiCol_Border, Helpers::calculateColor(RNBW));
ImGui::PushStyleColor(ImGuiCol_TabActive, Helpers::calculateColor(RNBW));
ImGui::PopStyleColor(2);
`
neither of them is working. What should I do ?
```
ImGui::Begin("interesting name", nullptr, windowFlags | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_AlwaysAutoResize);
ImGui::PushStyleColor(ImGuiCol_Border, Helpers::calculateColor(RNBW));
ImGui::PushStyleColor(ImGuiCol_TabActive, Helpers::calculateColor(RNBW));
if (ImGui::BeginTabBar("TabBar", ImGuiTabBarFlags_Reorderable | ImGuiTabBarFlags_FittingPolicyScroll | ImGuiTabBarFlags_NoTooltip)) {
        if (ImGui::BeginTabItem("Tab1")) {
            renderTab1Window(true);
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Tab2")) {
            renderTab2Window(true);
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Tab3")) {
            renderTab3Window(true);
            ImGui::EndTabItem();
        }
        Glow::tabItem();
        if (ImGui::BeginTabItem("Tab4")) {
            renderTab4Window(true);
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Tab5")) {
            renderTab5Window(true);
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Tab6")) {
            renderTab6Window(true);
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Tab7")) {
            renderTab7Window(true);
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Tab8")) {
            renderTab8Window(true);
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("Tab9")) {
            renderTab9Window(true);
            ImGui::EndTabItem();
        }
        ImGui::EndTabBar();
    }
    ImGui::PopStyleColor(2);
    ImGui::End();
```

**Comment by PathogenDavid** [comment]
Maybe I'm misunderstanding what you're trying to accomplish, but if you want to change the border of the `interesting name` window, you need to move your `PushStyleColor` calls to before `Begin` and your `PopStyleColor` after `End`.

**Comment by MorganaBRKSRL** [comment]
> Maybe I'm misunderstanding what you're trying to accomplish, but if you want to change the border of the `interesting name` window, you need to move your `PushStyleColor` calls to before `Begin` and your `PopStyleColor` after `End`.

Yes, that works. I wonder why, if you have time to give me a small explanation. Also, I don't think this other question deserves a new thread: so I have this now:
 ``` if (RGB_menu)
    {
        ImGui::PushStyleColor(ImGuiCol_Border, Helpers::calculateColor(RNBW));
        ImGui::PushStyleColor(ImGuiCol_TabActive, Helpers::calculateColor(RNBW));
        RGB_reset = true;
    }
    else if (RGB_reset)
    {
        RGB_reset = false;
        ImGui::StyleColorsDark();
    }
```
everything is done by a checkbox:
```        ImGui::Checkbox("RGB MENU", &RGB_menu);
```
Is there any other way to avoid that RGB_reset ? I was thinking if I can somehow check if after the box has been checked, if it was unchecked. Thanks a lot! Have a nice day/night!

**Comment by PathogenDavid** [comment]
> Yes, that works. I wonder why, if you have time to give me a small explanation.

ImGui uses the style color during `Begin`, so the color needs to be configured when you call it. (You were essentially changing the color after the window was already created with the old color.)

> Is there any other way to avoid that RGB_reset ?

I'm not sure why you're doing it in the first place. If you're using `PushStyleColor`/`PopStyleColor` you shouldn't ever have to reset the style like that. `PushStyleColor` changes the color, `PopStyleColor` undoes the change.

> Thanks a lot! Have a nice day/night!

No problem, you too!
