### ISSUE TITLE
Selectable press on click instead of release

### ISSUE THREAD

**Issue by yngccc** [ocornut/imgui#376]
I am trying to detect double mouse click on `Selectable`, `ImGuiSelectableFlags` doesn't have option to change the behavior to return on click, I see in the source code it is checking against `ImGuiSelectableFlags_Menu` but that is a private flag. Am I missing something?

```
// example
if (ImGui::Selectable("selectable",  x, ImGuiSelectableFlags_onClick)) {
  if (ImGui::IsMouseDoubleClicked(0)) {
     // double clicked
  }
}
```

**Comment by ocornut** [comment]
We could add an extra flag (that would be tested along with ImguiSelectableFlags_Menu)
But if you are trying to detect double-click you can also do:

```
ImGui::Selectable(...);
if (ImGui::IsMouseDoubleClicked(0) && ImGui::IsItemHovered))
{
}
```

**Comment by yngccc** [comment]
Neat, I am not aware you can do that, thanks!
