### ISSUE TITLE
About modal window position settings problem

### ISSUE THREAD

**Issue by Ghost-yc** [ocornut/imgui#377]
When invoke SetNextWindowPos(pos, ImGuiSetCond_Appearing ) function to set modal window. Location modal dialog boxes can not be applied.

**Comment by ocornut** [comment]
Should be fixed. The code for Begin() is rather complex so I have double-checked things but it's not impossible I might have added a subtle bug somewhere. Fingers crossed (yeah, that's an engineering method).
