### ISSUE TITLE
Bring/Force tab in dockspace to front

### ISSUE THREAD

**Issue by dgregorius** [ocornut/imgui#3775]
**Version/Branch of Dear ImGui:**

Version: 1.80
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 
Compiler: VS 2019
Operating System: Windows 10 Professional

**My Issue/Question:**

I want to force a tab in a dockspace to become active/visible in code. The use case is simple. I have a pretty basic scene editor. The user can now double click on some editable asset in the project (file) browser. When this happens I make the associated editor window visible. If this editor window was not visible it comes to front in the tab bar - great. But if it is already visible, but inactive in the tab bar I need it to come to front. I tried to give the associated editor window the focus, but this does not work unfortunately. What is the recommend way to do this?

Thanks,
-Dirk

**Comment by PathogenDavid** [comment]
> I tried to give the associated editor window the focus, but this does not work unfortunately. What is the recommend way to do this?

Are you referring to this? Where the tab and ImGui window get focused but the associated platform window is not brought to the front?

![image](https://user-images.githubusercontent.com/278957/106400774-35bae200-63e6-11eb-9e4e-bc04e7d74f69.png)

If so, I believe that's a duplicate of https://github.com/ocornut/imgui/issues/2605

**Comment by dgregorius** [comment]
Nope, in my case Tab1 is not coming forward when I essentially press Tab1 button your main widget (Hello World). Though my tabs are dock windows. Maybe that is the difference. Here is a screenshot:

<img width="1921" alt="Capture" src="https://user-images.githubusercontent.com/7042834/106401937-d8219800-63db-11eb-8009-637f5d8e0207.PNG">

If I double click 'Motus.graph' in the project window I want the "Graph' tab above to come forward.

**Comment by PathogenDavid** [comment]
Hmm, it seems to be working for me with both `DockSpaceOverViewport` or plain `DockSpace` as well. [Here's the changes I made to the demo for my test](https://github.com/PathogenPlayground/imgui/compare/577e7cb493cecf1e3dfbdc040c798fe4a978f229...fa3d38868ba3affe2e88e47d64e1b10ce492f011#diff-20d0a17de341651ca01671c6a26b3c8233ca0a2cd3ee2f258e922a318c58ace9) if you want to check and see if you can spot the difference.

**Comment by dgregorius** [comment]
I used the named SetWindowFocus( "WindowName" ) function as well. So exactly the same. What happens is that the editor window gets focus and then looses it again immediately. You can notice the quick flicker.

**Comment by ocornut** [comment]
Hello,
We would need a repro because as David pointed out that is supposed to work.

However there are so many possible way focus can be interfered with, and generally the code for focus authority is a bit of a scattered mess presently. Edge cases and repro are always useful and we can enter some into our regression testing suite.

As a suggestions, in `ImGui::FocusWindow()` you can uncomment this line
```
//IMGUI_DEBUG_LOG("FocusWindow(\"%s\")\n", window ? window->Name : NULL);
```
And try see what steals the focus back.
You can also set a breakpoing in FocusWindow() just before clicking your button to get more context and try to understand if it a user error or a bug in dear imgui (I'm absolutely not ruling that out, I know this code is currently quite clunky)

**Comment by dgregorius** [comment]
That is a good suggestion. I just refactored the code and now it is working. I think I was setting the focus after drawing the window., but I unfortunately don't have a repro right now. I close this for now and will re-open if I can reliably repro this.

Thanks for your help guys!
