### ISSUE TITLE
How to load texture from file using SDL2 + OpenGL2?

### ISSUE THREAD

**Issue by flamendless** [ocornut/imgui#3778]
The guide in the wiki for opengl users uses GLUT, but in the `imgui_impl_glut` it says that prefer using GLFW or SDL. Im using SDL but there's no guide regarding sdl2 + opengl2.

**Comment by ocornut** [comment]
Hello,

(1) The wiki guide ( https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples ) doesn't use GLUT and never refers to GLUT.
(2) The "Example for OpenGL user" section is valid for all uses of OpenGL, which include your use.

Please read that page again.
