### ISSUE TITLE
Sub menu becomes unexpectedly wide after upgrading to v1.80

### ISSUE THREAD

**Issue by paladin-t** [ocornut/imgui#3779]
**Version/Branch of Dear ImGui:**

Version: v1.80
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: custom SDL2 backend
Compiler: VC++ 2015
Operating System: Win7/Win10

**My Issue/Question:**

Sub menu becomes unexpectedly wide after upgrading from v1.79 to v1.80

Is it a bug or new design? How could I stick to the old appearance?

**Screenshots/Video**

v1.79

![before](https://user-images.githubusercontent.com/2062224/106589270-cd573680-6586-11eb-8a17-e0e33b3540ae.png)

v1.80

![after](https://user-images.githubusercontent.com/2062224/106589297-d3e5ae00-6586-11eb-903a-d0f7bad90274.png)

**Comment by ocornut** [comment]
Looks like a bug to me, will investigate.

**Comment by ocornut** [comment]
Fixed with a3f0393

Thank  you for the report!
I feel like this may be enough of a bug to warrant a 1.81 release soon (as we've already accumulated a nice amount of changes since 1.80)

**Comment by paladin-t** [comment]
Wow, that’s a rapid fix! Thanks!
