### ISSUE TITLE
API request for ImGui::TableGetColumnOffset(), ImGui::TableGetColumnWidth()

### ISSUE THREAD

**Issue by paladin-t** [ocornut/imgui#3780]
**Version/Branch of Dear ImGui:**

Version: v1.80/1.81 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: any
Compiler: any
Operating System: any

**My Issue/Question:**

I was using columns for a custom markdown table rendering. Word-wrap was dynamically determined for each grid content, by calculating something like text width, column offset/width, etc.

The new table API is great, and I'm up to replace all old columns to tables. However what preventing me doing so is that it's lacking in `ImGui::TableGetColumnOffset()`, `ImGui::TableGetColumnWidth()`. Is it possible to make these API for table equivalent to `ImGui::GetColumnOffset()`, `ImGui::GetColumnWidth()`?

**Screenshots/Video**

![columns](https://user-images.githubusercontent.com/2062224/106609723-db19b580-65a0-11eb-90e5-6802234e56a6.PNG)

**Comment by ocornut** [comment]
You can call `GetContentRegionAvail().x` within a column to tell how much space you have (which is the size of the columns minus padding which is variable). I don't see why you would need a "GetColumnOffset". You can query the current Cursor position when entering a column.

**Comment by ocornut** [comment]
Also you can use `PushTextWrapPos(-FLT_MIN)` in a column to force all calls to wrap, which is essentially the same thing `TextWrapped()` does.

**Comment by paladin-t** [comment]
Thanks, I’ll try tomorrow.

**Comment by paladin-t** [comment]
I've managed to migrate to the new table API.
Close this if there's no other reason.
