### ISSUE TITLE
can i use this library, for application sales

### ISSUE THREAD

**Issue by budibeta** [ocornut/imgui#3783]
please read slowly, for the maker of this library

I'm curious, in accordance with the written license, namely the mit license, the license allows dear imgui to be used for commercial use on the condition that "License and copyright notice" includes the license

according to the written [license](https://github.com/ocornut/imgui/blob/master/LICENSE.txt) "Commercial use"
can I use the source code dear imgui for selling applications like this

like this the details:
- I will use the dear imgui library or source code in my application
- I will put the license on the forder or I put the license in the "about us" section that I use the dear imgui library
- I will sell my application in binary form (.exe)

can I use the dear imgui library "like this" or "as I mentioned above" to legally get money like the permission that dear imgui has given

I asked if the dear imgui library owner was willing or sincere, if I used the dear imgui library to legally get money

if the owner of this library is not sincere, I will not use it

I just want to "make sure", that I am allowed to use the dear imgui library to legally earn money, please answer, thank you

I don't have a company, just a programmer, I want to legally sell my application

**Comment by ocornut** [comment]
Yes, this is what the Licence says
https://github.com/ocornut/imgui/blob/master/LICENSE.txt
I think your links and post already answers the question.
Just read the Licence or search about "MIT licence" on the internet.

**Comment by budibeta** [comment]
very well thanks, I hope there is no money income limitation

**Comment by rokups** [comment]
> very well thanks, I hope there is no money income limitation

Simply put license says you can do anything you want with the library, except falsely claim authorship.

**Comment by budibeta** [comment]
read carefully

this is a library, the application does not fully use the source code dear imgui

I mean, even though I use the dear imgui library in the application I created, I have my own code, for example I have an algorithm to find duplicate files

described like this:
1. The source code for "algorithm for finding duplicate files" is my own code
2. The source code for "create user interface" is code belonging to dear imgui

so I will write in "abous us" as below

I'm going to claim the app is mine, but I'm using the dear imgui library, and I'm going to tell the user that:

- 3rd party library: dear imgui
I will include the github link dear imgui, along with the license

as is done by the operamini browser, in including 3rd party library licenses

if according to ocornut "the way I put the license" is wrong, please rebuke me

**Comment by rokups** [comment]
You understand it correctly and have nothing to worry about regarding license.
