### ISSUE TITLE
How to apply SetActiveID to InputText?

### ISSUE THREAD

**Issue by mooko-dev** [ocornut/imgui#3788]
Hello!
I'm trying to programmatically activate InputText.
I have ImGuiID of InputText to activate, I call this:

```
            ImGui::SetActiveID(input_id, ImGui::GetCurrentWindow());
            ImGui::SetFocusID(input_id, ImGui::GetCurrentWindow());
            ImGui::FocusWindow(ImGui::GetCurrentWindow());
```
It works, but not always. It works if I previously activate that InputText using mouse or navigation and release activation.
I found out that SetActiveID works ok always because GImGui->LastActiveId sets correct, but GImGui->ActiveId clears after drawing that InputText.
I found the line where ActiveID clears (imgui_widgets.cpp line 3978 ImGui::InputTextEx):
```
    // We have an edge case if ActiveId was set through another widget (e.g. widget being swapped), clear id immediately (don't wait until the end of the function)
    if (g.ActiveId == id && state == NULL)
        ClearActiveID();
```
So, is it possible to programmatically activate InputText? How can I do it?
Thanks in advance!

**Comment by rokups** [comment]
I think you are looking for `ImGui::SetKeyboardFocusHere()` or `ImGui::SetItemDefaultFocus()`. Note that they should be called _after_ `ImGui::InputText()`.

**Comment by Marcets423** [comment]
Note: in v1.90.1, you have to call ImGui::SetKeyboardFocusHere() **before** ImGui::InputText() to activate the input. It might be the correct use case in the coming versions as well.

**Comment by ocornut** [comment]
> Note: in v1.90.1, you have to call ImGui::SetKeyboardFocusHere() **before** ImGui::InputText() to activate the input. It might be the correct use case in the coming versions as well.

The API for `SetKeyboardFocusHere()` hasn't changed in a long time. It can target the previous OR next item depending on the parameter passed to it.

```cpp
SetKeyboardFocusHere(-1); // previous Item
SetKeyboardFocusHere(0); // next item
```

This API is inconsistent with most other API which uses the terminology `Item` and `NextItem`, it's aimed to be eventually refactored but it will flag a bunch of other feature/flags that i haven't been able to fully design yet.
