### ISSUE TITLE
What version (revision) of STB is currently embedded in imgui?

### ISSUE THREAD

**Issue by ongamex** [ocornut/imgui#379]
In the latest stb revision "stbrp_init_target" is defined in stb_truetype.h. Signature:
static void stbrp_init_target(stbrp_context *con, int pw, int ph, stbrp_node *nodes, int num_nodes)

In you repository it is defined in stb_rect_pack.h Signature:
STBRP_DEF void stbrp_init_target(stbrp_context *context, int width, int height, stbrp_node *nodes, int num_nodes)

**Comment by ocornut** [comment]
Those functions are in both and stb_truetype.h is compatible with including stb_rect_pack.h priorhand. If you want to know their version number just open the files.

**Comment by ocornut** [comment]
Are you getting an error?

**Comment by ongamex** [comment]
My mistake, the symbol is defined in both truetype and rect_pack with differnet implementations and for some reason the code compile|links and in result the wrong function gets called. Probably the mistake is in my code or in STB.

**Comment by ocornut** [comment]
ImGui should build, have you made changes to the files?
