### ISSUE TITLE
This problem has never appeared before, even I use Multi-threaded (/ MT)

### ISSUE THREAD

**Issue by budibeta** [ocornut/imgui#3790]
i use the lib directx static library and use the Multi-threaded (/ MT) option, never problem and it can be run

but when I "including dear imgui" source code, error api-ms-xx-xx-xx-xx, even if the compilation succeeds and even I use Multi-threaded option (/ MT)

I use Multi-threaded (/ MT), but the api-ms-xx-xx-xx-xx error appears

I have installed all Visual Studio redistributable 2008 - 2019

what have you done with "dear imgui source code" did you use "std :: blah std :: blah std :: blah std :: blah"

even the WaitForSingleObject which is exported by kernel32.dll, requires "api-ms-xx-xx-xx-xx"

WaitForSingleObject prodecure not found inside "api-ms-xx-xx-xx-xx"

I know WaitForSingleObject is exported by kernel32.dll

but why does WaitForSingleObject need "api-ms-xx-xx-xx-xx"

i want static compilation, not like this, even if "open source".

did dear imgui import WaitForSingleObject from "api-ms-xx-xx-xx-xx"

![Screenshot_3](https://user-images.githubusercontent.com/68463485/106957949-3dbead00-676b-11eb-8fb6-084f5f35f01b.jpg)

I use Multi-threaded (/ MT), no import "api-ms-win-core" in the application I compile

but when running, the error "api-ms-win-core" appears

![Screenshot_4](https://user-images.githubusercontent.com/68463485/106958619-31871f80-676c-11eb-8bb6-fe2593073507.jpg)

the details are like this:
- use d3d9 without imgui = compiled and run success without the error "api-ms-win-core"
- using d3d9 with imgui = compiled and  and error "api-ms-win-core" appeared

what code do you use in the dear imgui library, so it takes "api-ms-win-core"

i can download "api-ms-win-core" manually
but what I want is dearr imgui to run without the need for additional runtime

i need a solution, thanks

**Comment by PathogenDavid** [comment]
(Please follow the issue template next time. You didn't provide all of the information that it requested and that information would've been helpful here.)

Those `api-ms-win-*` libraries are Windows API set forwarders, which is a concept introduced in Windows 10. ([You can read more about them here](https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-apisets))

Judging by your screenshots, you're on an older version of Windows which does not support API sets. Which means you're probably targeting a newer version of the Windows SDK than you're running on.

**Comment by ocornut** [comment]
Hello @budibeta,

In spite of all the information you posted we are missing a lots of information and it's difficult to understand your problem.

- Which compiler and settings.
- Which backends, if any (imgui_impl_win32.cpp?)

I don't think your issue is specific to dear imgui at all.
As with David I suspect it is a matter of which Windows SDK you are targetting for.

**Comment by metarutaiga** [comment]
I see the similar problems there.
[https://steamcommunity.com/app/1128000/discussions/0/2564160288806398178/](url)

You may try to unmark IMGUI_IMPL_WIN32_DISABLE_GAMEPAD in imgui_impl_win32.h
```
// Configuration
// - Disable gamepad support
//#define IMGUI_IMPL_WIN32_DISABLE_GAMEPAD
```
Or try to downgrade your Visual Studio Version to 2013 to prevent to use UCRT in MT library.
the UCRT is builtin in Windows 10 only.

I guess your OS is Windows 7 or below versions. (Windows XP?)
I guess your IDE is Visual Studio 2017 from your other repository.
So why I am boring to search your development informations ?
If you can't provide more informations here, nobody can help you.

**Comment by metarutaiga** [comment]
I see the similar problems there.
https://steamcommunity.com/app/1128000/discussions/0/2564160288806398178/

You may try to unmark IMGUI_IMPL_WIN32_DISABLE_GAMEPAD in imgui_impl_win32.h
```
// Configuration
// - Disable gamepad support
//#define IMGUI_IMPL_WIN32_DISABLE_GAMEPAD
```
Or try to downgrade your Visual Studio Version to 2013 to prevent to use UCRT in MT library.
the UCRT is builtin in Windows 10 only.

I guess your OS is Windows 7 or below versions. (Windows XP?)
I guess your IDE is Visual Studio 2017 from your other repository.
So why I am boring to search your development information ?
If you can't provide more informations here, nobody can help you.

**Comment by ocornut** [comment]
Note that as of #3646 (merged 17 days ago) the win32 backends for gamepads now loads xinput dynamically therefore the exe shouldn't have any hard link to a given DLL/version.

**Comment by metarutaiga** [comment]
> Note that as of #3646 (merged 17 days ago) the win32 backends for gamepads now loads xinput dynamically therefore the exe shouldn't have any hard link to a given DLL/version.

It maybe has a problem in the XInput.dll that downloaded a wrong versions(Windows 10?),
then the imgui show the dialog when imgui loads XInput.dll dynamically?

**Comment by budibeta** [comment]
thanks for your reply, iam very happy to use dear imgui, since this problem happened, i decide to not use dear imgui anymore.

are you understand of word "universal" mean

universal app / library, that is meaning "must working on all of windows version"

how it can be called universal, if problem appeared on some version of windows.

iam not judge to this library.

but i need to tell you, "people will not happy if app / library need runtime" or "only work on specific windows version"



some people answered need to unmark "IMGUI_IMPL_WIN32_DISABLE_GAMEPAD"
if its that true, then tell people to unmark IMGUI_IMPL_WIN32_DISABLE_GAMEPAD on your library homepage

in game language "rage quitting"
in programming language "people will retire using libraries"

anyway thanks for your reply i will reconsider whether i will use dear imgui

**Comment by ocornut** [comment]
There was indeed a problem with imgui_impl_win32.cpp linking to xinput.lib which has been fixed now so perhaps updating is a good idea.

In general term the problem you are discussing is not a Dear ImGui problem. 
It is mostly a problem with your build setup, with Visual Studio and with Windows SDK. 
Microsoft have a vested interest in making people upgrade to new technologies and as a result it can be confusing how to build software that works on e.g. Windows XP, and nowadays Windows 7 is increasingly not obvious.

**Comment by budibeta** [comment]
ocornut said : imgui_impl_win32.cpp linking to xinput.lib which has been fixed now

does that mean I won't see the error again, even if it doesn't unmark IMGUI_IMPL_WIN32_DISABLE_GAMEPAD
