### ISSUE TITLE
ImGui::InputText. The entered text is deleted automatically after switching to a new input field.

### ISSUE THREAD

**Issue by killtime777** [ocornut/imgui#3797]
Hi.
I have a problem.

I need to translate **string to char***, I did it.
next, I use strcpy in **ImGui::InputText**, but my entered text is _ERASED_. Why? what is the problem?
Code:
`char* chrstr = new char[user.username.length() + 1];`
 `char* chrstr1 = new char[user.passwd.length() + 1];`
`ImGui::InputText("Username", strcpy(chrstr, user.username.c_str()), IM_ARRAYSIZE(user_name));`
`ImGui::InputText("Password", strcpy(chrstr1, user.passwd.c_str()), IM_ARRAYSIZE(pass_word,ImGuiInputTextFlags_Password));`

Help me, pls.

Video:
https://user-images.githubusercontent.com/57942975/107416488-9a341a80-6b25-11eb-85ad-4c47d096e0cc.mp4

**Comment by ocornut** [comment]
Because you are never writing back to your source strings. 

To use InputText with std::string you can use the wrapper misc/cpp so you won’t need to do any manual copy.
