### ISSUE TITLE
Color Choice according to contrast between background and foreground color

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#3798]
Hello,

Version: Current
Branch: Any

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: MSVC
Operating System: Win10 x64

**My Issue/Question:**

This is not an issue.

i have a Bi-Color theme, i mean by bi-color, two text color accroding to background color of the widget.
Many widgets have, like Combo or ImputText two different background color but one text color.
in case we have a darker bg button color and a lighter framebg color, the text color will be in one case, visible and not visible  in the other case.

So i define a dark text color for light background color and an light text color for dark background color.
But in this case, i have no way to let the user tune himself the color theme.

After some search and experiment,
i think i have finally found the convenient way for all who can be integrated to imgui.
 
I Calculate a contrast ratio between the background and foreground colors. (foreground is the text color in this case)
The idea is :
 * if the calculated contrast ratio is inner than the user defined max contrast ratio => current color is applied
 * if the calculated contrast ratio is outer than the user defined max cotnrast ratio => inverse of the current color is applied (the alpha is preserved by the way)

here the result with a max contrast ratio of 2.0 (for my poor eyes :) ) :
![OgiQtZMB4V](https://user-images.githubusercontent.com/1434736/107410346-795fcb00-6b0d-11eb-8460-2f00471890fb.gif)

the code for calculate the contrast ratio
```cpp
// contrast from 1 to 21
// https://www.w3.org/TR/WCAG20/#relativeluminancedef
float CalcContrastRatio(const ImU32& backgroundColor, const ImU32& foreGroundColor)
{
    // real code https://www.w3.org/TR/WCAG20/#relativeluminancedef
    /*const auto colBG = ImGui::ColorConvertU32ToFloat4(backgroundColor);
    const auto colFG = ImGui::ColorConvertU32ToFloat4(foreGroundColor);
    float lumBG = 0.2126 * colBG.x + 0.7152 * colBG.y + 0.0722 * colBG.z;
    float lumFG = 0.2126 * colFG.x + 0.7152 * colFG.y + 0.0722 * colFG.z;
    return (ImMax(lumBG, lumFG) + 0.05) / (ImMin(lumBG, lumFG) + 0.05);*/

	float sa0 = ((backgroundColor >> IM_COL32_A_SHIFT) & 0xFF);
	float sa1 = ((foreGroundColor >> IM_COL32_A_SHIFT) & 0xFF);
	static float sr = 0.2126f / 255.0f;
	static float sg = 0.7152f / 255.0f;
	static float sb = 0.0722f / 255.0f;
	const float contrastRatio =
		(sr * sa0 * ((backgroundColor >> IM_COL32_R_SHIFT) & 0xFF) +
			sg * sa0 * ((backgroundColor >> IM_COL32_G_SHIFT) & 0xFF) +
			sb * sa0 * ((backgroundColor >> IM_COL32_B_SHIFT) & 0xFF) + 0.05f) /
		(sr * sa1 * ((foreGroundColor >> IM_COL32_R_SHIFT) & 0xFF) +
			sg * sa1 * ((foreGroundColor >> IM_COL32_G_SHIFT) & 0xFF) +
			sb * sa1 * ((foreGroundColor >> IM_COL32_B_SHIFT) & 0xFF) + 0.05f);
	if (contrastRatio < 1.0f)
		return 1.0f / contrastRatio;
	return contrastRatio;
}
```

in the case "no modification of imgui", i choose to work with a custom PushStyleColor function according to contrast

the first version i tested was this one. (in my case im using only white or black text color)
```cpp
bool ImGui::PushStyleColorWithContrast(ImGuiCol backgroundColor, ImGuiCol foregroundColor, float maxContrastRatio)
{
	const float contrastRatio = CalcContrastRatio(ImGui::GetColorU32(backgroundColor), ImGui::GetColorU32(foregroundColor));
	const auto colFG = ImGui::GetStyleColorVec4(foreGroundColor);
	if (contrastRatio < maxContrastRatio)
	{
		ImVec4 invColor = ImVec4(1, 1, 1, 1) - colFG; // inverse
                invColor.w = colFG.w;
		ImGui::PushStyleColor(foreGroundColor, invColor);
		return true;
	}
	return false;
}
```
We could incorporate the code of CalcContrastRatio for avoid a second extraction of color from the ImGuiCol foreGroundColor btw.

But this simple inverted color is not ideal for color with different R/G/B channels as you know. 
green become pink :)
btw in the case of the contrast, it work nice to me.

we could compute the inverted color with only the variation of the value in HSV.
but the contrast with non uniform color, is not very nice in all case to me haha
by ex this implementation
```cpp
bool ImGui::PushStyleColorWithContrast(ImGuiCol backGroundColor, ImGuiCol foreGroundColor, float maxContrastRatio)
{
	const float contrastRatio = CalcContrastRatio(ImGui::GetColorU32(backgroundColor), ImGui::GetColorU32(foregroundColor));
	auto colFG = ImGui::GetStyleColorVec4(foreGroundColor);
	if (contrastRatio < maxContrastRatio)
	{
		ImVec4 hsv;
		ImGui::ColorConvertRGBtoHSV(colFG.x, colFG.y, colFG.z, hsv.x, hsv.y, hsv.z);
		hsv.z = 1.0f - hsv.z; // darker or lighter
		ImGui::ColorConvertHSVtoRGB(hsv.x, hsv.y, hsv.z, colFG.x, colFG.y, colFG.z);
		ImGui::PushStyleColor(foreGroundColor, colFG);
		return true;
	}
	return false;
}
```
the RGB>HSV>RGB conversion have a cost and the result is not ideal also to me.

Finally i decided to freeze for the user the default and inverted text colors to use regarding contrast
but let the user tune all the others colors

we could do a progressive conversion but more costly, and not sure if really needed since a HSV value 0 is alwasy black :)

```cpp
void ImGui::PushStyleColorWithContrast(ImGuiCol backgroundColor, ImGuiCol foregroundColor, float maxContrastRatio)
{
	const float contrastRatio = CalcContrastRatio(ImGui::GetColorU32(backgroundColor), ImGui::GetColorU32(foregroundColor));
	auto colFG = ImGui::GetStyleColorVec4(foregroundColor);

	float inversioRatio = contrastRatio / (maxContrastRatio + 0.001f);

	ImVec4 hsv; ImGui::ColorConvertRGBtoHSV(colFG.x, colFG.y, colFG.z, hsv.x, hsv.y, hsv.z);
	hsv.z = inversioRatio - hsv.z; // value inversion darker or lighter
	ImGui::ColorConvertHSVtoRGB(hsv.x, hsv.y, hsv.z, colFG.x, colFG.y, colFG.z);
	ImGui::PushStyleColor(foregroundColor, colFG);
	return true;
} 
```

so this is what i retain finally 
```cpp
bool ImGui::PushStyleColorWithContrast(ImGuiCol backGroundColor, ImGuiCol foreGroundColor, ImU32 invertedColor, float maxContrastRatio)
{
	const float contrastRatio = CalcContrastRatio(ImGui::GetColorU32(backgroundColor), ImGui::GetColorU32(foregroundColor));
	if (contrastRatio < maxContrastRatio)
	{
		ImGui::PushStyleColor(foreGroundColor, invertedColor);
		return true;
	}
	return false;
} 
```

sample use :

in my case :
 * ImGuiCol_Text is black by default and not tunable for the user
 * i have a LighTextColor defined to white, not tunable too by the user
```cpp
bool pushed = ImGui::PushStyleColorWithContrast(ImGuiCol_Button, ImGuiCol_Text, LighTextColor, 2.0f);
bool res = ImGui::Button("toto");
if (pushed)
	ImGui::PopStyleColor();
```

for ImGui, i think theses two function can be usefull.
by the way ImGui have widgets in widgets in some cases : by ex "InputInt" who have buttons in the widget.
and in this case with a dark button color and a light frame color, we can't define the textcolor with this PushStyleColorWithContrast.
these is also the combo widget. etc..
in this case i have rewrote my widget just for that. but its not ideal :)

so maybe it can be a pain but a needed task to have :
 * a flag by ex ImGuiConfigFlags_ContrastedText (for define that we want to change text color according to contrast between background and text color) 
 * define the text color according to contrast with the background color of the text in this widget when flaged

If you think its a good way to add in ImGui, i can work on a PR.

final test with many colors :

![Tpj5dDsmo1](https://user-images.githubusercontent.com/1434736/107449374-c2cb0d00-6b43-11eb-876e-b99dd5500ae9.gif)

Thanks for reading :)

**Comment by aiekick** [comment]
in fact its a bit complicated and can cause perf issues.
the easier way could be just to a add a ImGuiCol_ButtonText.
to be used for all buttons widgets.
could be by default the same color as ImGuiCol_Text

because as far i know, in each widgets, there is just two contrasts case.
 * text over button
 * text over the rest (often time frame Color)

and button color are rarely the same color as frame Color

the issue with these themes is mostly for some defuatl widget who are embedding ofhter widget like buttons.

this is the case by ex of Combo and ImputInt.

but ok i know your position, explained in the issue #1706.

you can close this if you want

**Comment by ocornut** [comment]
> the easier way could be just to a add a ImGuiCol_ButtonText.
> to be used for all buttons widgets.
> could be by default the same color as ImGuiCol_Text
> because as far i know, in each widgets, there is just two contrasts case.
>    text over button
>    text over the rest (often time frame Color)

I think this would be desirable as part of style v2 to extend on those, e.g. discussions in #511 and #1223

> the issue with these themes is mostly for some defuatl widget who are embedding ofhter widget like buttons.
> this is the case by ex of Combo and ImputInt.
> but ok i know your position, explained in the issue #1706.

I think that's a different story and suggestion in #1706, you are suggesting to tie symbol to color, what we need is to change text/symbol color depending on background as you said in this thread here.

**Comment by aiekick** [comment]
in fact, it was the same demand.
in #1706 i was speaking about symbol color but it fact it was a bad name for "text for buttons."
like:
* ImGuiCol_Text => text for frames (could be in fact ImGuiCol_FrameText
* ImGuiCol_Symbol => text for buttons (could be in fact ImGuiCol_ButtonText)

i use my Contrasted systeme fro now, its working like a charm when user want to tune the theme.
, i rewrote some widgets. (who i hope will not more necessary in few times, for easier update)
