### ISSUE TITLE
Multiline Scroll

### ISSUE THREAD

**Issue by Gorkem95** [ocornut/imgui#3799]
Hello

**Version**: Current - Dx9
**Operating System**: Win7 x64

**My Issue/Question**
I was making an editor with multilines its has few pages settings etc. Its renders different items/widgets for each page but when i scroll down on multiline its not renders other items(if i use SetCursorPos) i will explain this with screenshots

**Its works when scroll bar on top**

![Image](https://i.ibb.co/TKTqFBG/1.png)

![Image](https://i.ibb.co/RhGLcZ7/2.png)

**But when i scroll down on multiline, its not rendering other items**

![Image](https://i.ibb.co/2yfQpgc/3.png)

![Image](https://i.ibb.co/vmSLxPF/4.png)

**Its only happens when i use SetCursorPos manualy. Btw i tried to create another windows for each page but same thing happening**

Here is settings page

```
ImGui::SetCursorPos(ImVec2(150,50)); 
ImGui::Text("Editor Path"); 
ImGui::SetCursorPos(ImVec2(150, 70)); 
ImGui::InputText("##Input3", editor._filepath, sizeof(editor._filepath));
ImGui::SameLine();
if (ImGui::Button("...##Path"))
{
 //some funcs     
}
ImGui::SetCursorPos(ImVec2(150, 100));
ImGui::Text("Server Path");
ImGui::SetCursorPos(ImVec2(150, 120));
ImGui::InputText("##Input4",editor._filepath2,sizeof(editor._filepath2));
ImGui::SameLine();
if (ImGui::Button("...##Path2"))
{
  //some funcs    
}
```

**Comment by PathogenDavid** [comment]
> ![Image](https://camo.githubusercontent.com/5a95818b5a2e14f3df19a29eeb6550cf0ed30e5570463f0cd72703194898c730/68747470733a2f2f692e6962622e636f2f544b54714642472f312e706e67)
> 
> ![Image](https://camo.githubusercontent.com/7bde5330a684838b29cd188f285dd2c4f71f909d7193ce2808d213b85c59f3a8/68747470733a2f2f692e6962622e636f2f5268474c635a372f322e706e67)

Can you share more context? It's not immediately apparent to me how these two screenshots are related.

It would be ideal if you could share a minified version of your entire window including both pages. I suspect the issue has to do with how you're structuring the entire window rather than the settings page its self.

**Comment by Gorkem95** [comment]
I Fix it, But Thanks David.
