### ISSUE TITLE
How to fix the sidebar rendering when a fade in animation started?

### ISSUE THREAD

**Issue by mooko-dev** [ocornut/imgui#3802]
Hello!
I'm developing a fade-in animation. I ran into a problem when an animation starts. If animated content size greater than ContentRegion - FadeInOffset then the scrollbar will appear. Example:
![animation](https://user-images.githubusercontent.com/78313188/107668915-344bae00-6c5f-11eb-86b2-b1946ff92664.gif)
Animation works on the principle of changing the cursor position, but I can change it. I want the scrollbar to appear only when the animated content size greater than the content region size, have behavior as if there is no animation and no changing start cursor position.
Hope for your help!

**Comment by PathogenDavid** [comment]
The easiest way to fix this would be to just disable the window's scrollbar. (Perhaps only while the animation is playing.)

```cpp
ImGui::Begin("Test", nullptr, animation_is_playing ? ImGuiWindowFlags_NoScrollbar : 0);
```

You could also use `BeginChild`/`EndChild` for more advanced scenarios if you want the scrollbar to be visible without changing during the animation. (For this to work you'd have to know how big to make the child window though, and you can't know until you submit the UI at least once. So you'd likely have to measure the window contents with it invisible and no offset for one frame or something like that.)

Another more advanced possibility would be to customize the backend to perform the translation instead and use `ImGui::GetWindowDrawList()->AddCallback(...)` to add a callback to apply the offset. (I didn't test this one, just an idea I had.)

-----------------

Alternatively, if you're willing to poke at Dear ImGui's internals you can trick the scrollbar into ignoring your offset by manipulating `ImGui::GetCurrentWindow()->DC.CursorMaxPos.y` right before your call to `ImGui::End`.

However, the usual disclaimers apply for mucking with Dear ImGui's internals:

> ```cpp
> // You may use this file to debug, understand or extend ImGui features but we don't provide any guarantee of forward compatibility!
> ```

That hack may stop working at any time, and may have unintended consequences.

**Comment by ocornut** [comment]
A third solution, maybe less flexible, would be to submit the text directly via ImDrawList::AddText() calls aka not going via the widget laying out route.

or you could submit text without the offset via widget calls, remenber the vertex size before and later and manually offset all vertexes directly. See #1286 for ideas of how to do that.
