### ISSUE TITLE
Multiple Payloads for Drag and Drop

### ISSUE THREAD

**Issue by PSMusicalRoc** [ocornut/imgui#3803]
The question I have is whether or not multiple drag and drop payloads are supported at this time. For instance, what I'm trying to accomplish is sending over a custom JSON object and its size at the same time, for better security. This is what I'm doing under `BeginDragDropTarget`

```c++
if (ImGui::TreeNodeEx(skinSrcText.c_str(), ImGuiTreeNodeFlags_Leaf | ImGuiTreeNodeFlags_NoTreePushOnOpen))
{
	if (ImGui::BeginDragDropSource())
	{
		size_t ObjSize = sizeof(testText["characters"][character_it]["skins"][skin_it]);
		ImGui::SetDragDropPayload("SkinObjSize", &ObjSize, sizeof(size_t));
		ImGui::SetDragDropPayload("SkinObj", &testText["characters"][character_it]["skins"][skin_it], ObjSize);

		ImGui::Text("Moving Image %s", skinSrcText.c_str());

		ImGui::EndDragDropSource();
	}
}
```

I tested this before with a static `std::vector<int>` and passing a single payload through, which worked wonderfully. When I try this, the `Dummy` object (which used to be outlined in blue when hovered with a dragable object) doesn't do anything, which I can only assume to mean I've done something wrong.

If you need more clarification on anything I've said thus far, I'd be happy to give it if needed.

**Comment by rokups** [comment]
Only one payload can be specified. Specifying second payload would override previous one. In this particular case you do not need to specify size separately, because `ImGui::SetDragDropPayload()` already sets it for you to `ImGuiPayload::DataSize`.

**Comment by ocornut** [comment]
Your use of sizeof() is incorrect, sizeof() gives the size of a data structure, you probably want to use the string length + 1.

Multiple payloads may be desirable in the future for different use (provide different data formats to target, or encode a lightweight payload for same process vs a promise for a fully serialized payload for a different process). However, for the example you are giving you absolutely must not use a multiple payload.

You can either just send the zero terminated string using .c_str() and .length()+1 and let the target use the string as is, or you may decide to “serialize” your string into a buffer holding both explicit size followed by data. Ihmo the first solution is just simpler for you.

Use a debugger to check your values and step into the drag and drop functions and you’ll understand how eg your use of sizeof() is incorrect.
