### ISSUE TITLE
Multiple screen support

### ISSUE THREAD

**Issue by hateom** [ocornut/imgui#3806]
Would it be possible to have imgui across 2 (or more) screens? Meaning multiple OpenGL contexts. Should work on Windows and macOS. 
many tips would be appreciated.

**Comment by ocornut** [comment]
This is generally what the multi-viewports function does:

https://github.com/ocornut/imgui/wiki/Multi-Viewports
https://github.com/ocornut/imgui/issues/1542

**Comment by hateom** [comment]
Fantastic! Thought this only works on Windows. I'm going to try it right away.

**Comment by ocornut** [comment]
It should work well on OSX.
