### ISSUE TITLE
Why is there no IsItemSelected()?

### ISSUE THREAD

**Issue by str0yd** [ocornut/imgui#3807]
Basically what the title says, why is there no IsItemSelected()? As far as I understand we can only check treenodes with doubleclick flag against IsItemClicked(). The treenode is rendered selected, so why is there no info about whenever the treenode is selected or not?

**Comment by PathogenDavid** [comment]
Maybe I'm misunderstanding the question, but tree nodes do not keep track of selection state in the first place. The concept of tree node selection is something you have to keep track of yourself, so if you want to know if a node is selected you inspect whatever mechanism you're using to keep track of that in the first place.

For example, the demo keeps track of selection state in a bitfield and updates it in response to clicks:

https://github.com/ocornut/imgui/blob/61b19489f1ba35934d9114c034b24eb5bff149e7/imgui_demo.cpp#L804-L812

**Comment by ocornut** [comment]
There's no selection state in item it's always passed by your code as your code want to owns the selection state.
