### ISSUE TITLE
Value being passed to SliderFloat is shared

### ISSUE THREAD

**Issue by zach2good** [ocornut/imgui#381]
When I'm designing my GUI I access a vector of structs in this format:
```
struct FloatDebug
{
	FloatDebug(const char* title, float* value, float min, float max) :
		title(title), value(value), min(min), max(max) {}

	const char* title;
	float* value;
	float min;
	float max;
};
```

which are then drawn in this loop:

```
for (int i = 0; i < floats.size(); i++) {
			FloatDebug fd = floats.at(i);
			ImGui::Text(fd.title);
			ImGui::SliderFloat("", fd.value, fd.min, fd.max);
		}
```

When I have a single FloatDebug struct the system works nicely for having references to floats passed in which I can change. Once I add more than one struct to the vector, changing the value with the slider changes all the in the loop (So if I'm tracking CameraX, CameraY and CameraZ then go to change CameraZ; all 3 values change). The same issue happens if I create multiple values without a loop:
```
		ImGui::Text(floats.at(0).title);
		ImGui::SliderFloat("", floats.at(0).value, floats.at(0).min, floats.at(0).max);

		ImGui::Text(floats.at(1).title);
		ImGui::SliderFloat("", floats.at(1).value, floats.at(1).min, floats.at(1).max);

		ImGui::Text(floats.at(2).title);
		ImGui::SliderFloat("", floats.at(2).value, floats.at(2).min, floats.at(2).max);
```

![error](https://cloud.githubusercontent.com/assets/1389729/10584922/b25569ea-768c-11e5-9d6c-62e3b71e98a5.png)

UPDATE:

I've built a similar system for bools and it works correctly, despite being laid out the same way as DebugFloat

```
struct BoolDebug
{
	BoolDebug(const char* title, bool* value) :
		title(title), value(value) {}

	const char* title;
	bool* value;
};

for (int i = 0; i < bools.size(); i++) {
			ImGui::Checkbox(bools.at(i).title, bools.at(i).value);
		}
```

Any ideas?

**Comment by warmist** [comment]
I think it's the id problem: you have same id for sliders, and different id's for checkboxes. Either pass the "floats.at(2).title" as first param or give unique ids (with "##some_id") for each slider

**Comment by ocornut** [comment]
Read this section in imgui.cpp
```
 Q: Can I have multiple widgets with the same label? Can I have widget without a label? (Yes)
 A: Yes. A primer on the use of labels/IDs in ImGui..
```

**Comment by zach2good** [comment]
@warmist quite right, its because the id of each field was ""...

**Comment by ocornut** [comment]
Here typically you could use "##X" "##Y" "##Z" if you don't want a label.

**Comment by zach2good** [comment]
@ocornut, whoops. Thanks guys!

**Comment by ocornut** [comment]
No problem. This is the most commonly asked question. As we steer toward having better visual doc + wiki + collision detection it'll probably be more useful. For now I tried to make it more prominent in the FAQ but people tend to skim over that :)

**Comment by ocornut** [comment]
If you aren't putting labels on the right side of your large widgets you can also surround your whole window with:

```
ImGui::PushItemWidth(-1.0f);
...
ImGui::PopItemWidth();
```
And they will fill all the available width.
