### ISSUE TITLE
Rendering ImGui content to surface 2x window dimensions

### ISSUE THREAD

**Issue by adv-sw** [ocornut/imgui#3811]
Just upgraded to 1.81
Windows, DX12 version.

As title, we render to a surface twice the window dimensions.

Previously, I was setting ImGuiIO::DisplaySize to the dimensions of our surface & that was rendering correctly.

Now, I have a regression & it appears ImGui is truncating to the window dimensions, resulting in my UI cutting off half way down due to clipping reject.

How should I do this, please if an alternative approach is required.

Thanks for your awesome work.

**Comment by PathogenDavid** [comment]
It's not clear exactly what you're trying to accomplish, it'd likely be helpful if you told us *why* you want to render at twice the dimensions.

If you just need the UI to render twice as large, the easiest method is likely to use the [docking branch](https://github.com/ocornut/imgui/tree/docking) and override the DPI. (DPI support is tied to multi-viewport support which is in the docking branch.)

In the Win32 backend, this is handled by `ImGui_ImplWin32_GetDpiScaleForMonitor`. Here's what the demo looks like with that function modified to return 2x:

![image](https://user-images.githubusercontent.com/278957/107878656-d1922680-6e99-11eb-8e3a-081dce11233b.png)

If you don't want to use the experimental branches, you can [accomplish a similar effect](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-should-i-handle-dpi-in-my-application) using `ImGuiStyle::ScaleAllSizes` and setting `ImGuiIO::FontGlobalScale`.

If the blurry fonts are a problem for the previous solutions, the easiest solution currently is to load your font at a higher resolution and update `ImGuiIO::FontGlobalScale` to compensate.

If you're set on keeping something similar to your old solution, it'd be helpful to know which version of Dear ImGui you're upgrading from.

**Comment by adv-sw** [comment]
Thanks for the quick response, David

Reason is because rendering surface is double screen resolution to anti-alias. Figured ImGui may as well go over that surface too & potentially benefit from multi-sample quality improvements.

It doesn't have to. If this is going to be a problem, ImGui can render over actual screen buffer surface instead.

Will try docking branch if that's the way to accomplish this, thanks.

**Comment by adv-sw** [comment]
Previous was 1.79

**Comment by adv-sw** [comment]
The issue isn't getting the UI to render twice as large to compensate - I have that covered.

The issue is preventing clipping to the base window size. Will step thru docking branch now I have it & see if I can figure out what the issue is. Cheers.

**Comment by adv-sw** [comment]
Issue is viewport dimensions. Looking for public API to set viewport dimensions to 2x standard ...

**Comment by adv-sw** [comment]
Also there's monitor thingy in there. We don't always render directly to what a monitor might consider to be the surface dimensions.

**Comment by adv-sw** [comment]
Tried :

      ImGuiViewport* main_viewport = ImGui::GetMainViewport();
//      main_viewport->DpiScale = 2.0f;
      main_viewport->WorkSize.x *= 2.0f;
      main_viewport->WorkSize.y *= 2.0f;
      main_viewport->Size.x *= 2.0f;
      main_viewport->Size.y *= 2.0f;


before and after :

      ImGui_ImplWin32_NewFrame();
      ImGui::NewFrame();
      
      
No joy. As this is non-essential, going to assume feature not present & will revert to drawing ImGui content over regular back buffer.

**Comment by adv-sw** [comment]
Reverted to rendering imgui over final 1:1 viewport. Wasn't clear there was a quality win & way less hassle :)

**Comment by PathogenDavid** [comment]
> The issue isn't getting the UI to render twice as large to compensate - I have that covered.

I was more thinking that if you used ImGui's internal support for scaling UIs you'd avoid the clipping issue, but in retrospect I was probably underthinking things.

> Also there's monitor thingy in there. We don't always render directly to what a monitor might consider to be the surface dimensions.

For something so specialized, I think you might be better off making your own backend. The Win32 backend is designed for traditional 2D windows and is only going to get in the way in a situation like this.

For example, you might just be fighting with this bit here:

https://github.com/ocornut/imgui/blob/61b19489f1ba35934d9114c034b24eb5bff149e7/backends/imgui_impl_win32.cpp#L262-L265
