### ISSUE TITLE
Can not pull the bar out from the edge

### ISSUE THREAD

**Issue by GrreyWang** [ocornut/imgui#3825]
![image](https://user-images.githubusercontent.com/11966418/108382079-68b50080-7243-11eb-9a09-0b9d99a7cf12.png)

As you see, the collapsed bar will not be pulled out from the edge if it is moved to the postion, even though the check box be selected and unselected.

**Comment by ocornut** [comment]
Hello,

Thanks for reporting that.
It's still possible to grab the window by clicking under the X button.
But I think we should rework something to automatically shrink the X button hit-area in this situation.

**Comment by GrreyWang** [comment]
I tried it, not work, even after I rebuild the solution, the bar still there.  -_-!

![image](https://user-images.githubusercontent.com/11966418/108383990-41f7c980-7245-11eb-81e1-82fafa9e93d9.png)

**Comment by GrreyWang** [comment]
> Hello,
> 
> Thanks for reporting that.
> It's still possible to grab the window by clicking under the X button.
> But I think we should rework something to automatically shrink the X button hit-area in this situation.

Got the small space that under the X botton.

**Comment by ocornut** [comment]
Pushed a tweak to make it easier
a8f76c23a481162c69e462a52ea7d6f4ade96b32
