### ISSUE TITLE
Working on Android? (regarding latest version of imguI)

### ISSUE THREAD

**Issue by playingoDEERUX** [ocornut/imgui#3826]
Hey, uhh just a quick question actually:
Is this repository (the official repo of imgui) compatible with Android & Android SDK out of the box?

Thanks.

**Comment by PathogenDavid** [comment]
Short answer: Yes, but batteries are not included.

Dear ImGui its self is platform agnostic and depends on using an appropriate backend to handle platform-specific concerns. This repo contains a [handful of generic backends](https://github.com/ocornut/imgui/tree/a8f76c23a481162c69e462a52ea7d6f4ade96b32/backends), but you can also pretty easily [make your own](https://github.com/ocornut/imgui/blob/a8f76c23a481162c69e462a52ea7d6f4ade96b32/imgui.cpp#L223-L367).

My understanding is that the SDL and and OpenGL3 backends can be used with Android, but I can't say I've ever tried it myself.

There [was some talk](https://github.com/ocornut/imgui/issues/1200#issuecomment-320495404) of having an Android example that would work out of the box, but I don't believe it went anywhere.

It is worth noting that while Dear ImGui does work with touch-centric devices, its heritage definitely makes it more well-suited for mouse-centric devices. (For example, Dear ImGui does not support multi-touch https://github.com/ocornut/imgui/issues/3711 and interacting with the soft keyboard can be difficult https://github.com/ocornut/imgui/issues/3817 https://github.com/ocornut/imgui/issues/3275)

**Comment by playingoDEERUX** [comment]
How do I get started? I have hooked a drawing function on a game which uses OpenGLES 2 and it now gets redirected to my call.

My first attempt was using imgui_impl_opengl3 since that one has OpenGLES 2 version integrated, then I also used imgui_impl_glfw however I start to see the first issues. I get weird errors like: fatal error: 'GL/glfw.h' file not found
#include <GL/glfw.h> or even if I change the directory so that it gets included, it then complains about glx.h not being found??!

Thanks in advance if you would have any idea. I am currently doing ImGui_ImplOpenGL3_Init(); however that will cause a crash without initialization of glfw.

**Comment by playingoDEERUX** [comment]
Check #3860 this person apparently has the same issue on the latest version, it doesn't wanna let us introduce glfw with OpenGL3??!

**Comment by ocornut** [comment]
Note there's a native Android backend PR in the work #3446 which is likely to be merged soon.

**Comment by ocornut** [comment]
Update:
- The native backend + example was merged in #3446 
- The SDL based example in #421 has been revamped a few years ago and I forgot about it, ihmo using SDL would be ideal. You can refer to this example looking at "Files changed" (that is until the 69 commits are neatly squashed)

I think we can close this and we will aim at tweaking and merging the equivalent of #421 as well.
