### ISSUE TITLE
A fullscreen issue SDL - GNOME

### ISSUE THREAD

**Issue by audetto** [ocornut/imgui#3835]
```
Dear ImGui 1.81 WIP (18003)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=10
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1661.00,1147.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```
**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Compiler: gcc 10.2.0
Operating System: Ubuntu 20.10

**Issue**

After I enable fullscreen in SDL and back to window

``SDL_SetWindowFullscreen(window, SDL_WINDOW_FULLSCREEN_DESKTOP);``

there is a 10-1 chance of the following happening: I move the main window from the top frame and it is only repainted in the original rectangle. All the part that is now outside the original rectangle is "transparent".

Things go back to normal if I force a repaint (e.g. bringing another window above SDL).
That resets the "original" rectangle and now the same happens again. Or it might be enough to wait a few seconds.

I'd blame GNOME or SDL, if this did not happen only when using SDL + ImGui.
If I draw the screen using plain SDL calls, then nothing bad happens.

The code is available here

https://github.com/audetto/AppleWin/blob/master/source/frontends/sdl/imgui/sdlimguiframe.cpp#L275

but it is not a small self contained case.

**Comment by ocornut** [comment]
In spite of that later statement, I don't think this has anything to do with dear imgui, it may be just that some GL calls are interacting with your X/GNOME/SDL/GL setup in an indesirable way.
Providing a screenshot/video would help and may contains extra hints.

If you need to dig further into what triggers this interaction
- first try to comment `ImGui_ImplOpenGL3_RenderDrawData()` and see if your problem still happen. If it does still happen it has nothing to do with dear imgui renderer.
- if it does _only_ happen with `ImGui_ImplOpenGL3_RenderDrawData()` uncommented then try to comment out chunks of that function starting from inner-most loop and then increase the commented part toward the outer part of the function (following the backup/restore symmetry) trying to find a hint there.

**Comment by audetto** [comment]
Bad luck today.
I only get the 9/10 when it works.

Will try your suggestion to narrow down the culprit.

**Comment by audetto** [comment]
I have not forgotten this, but it is really hard to reproduce. It can go days without showing up.

**Comment by audetto** [comment]
I know how absurd this sounds but I have another one.

This is definitely correlation rather than causation, if anybody ever observed it and found a solution.

gdb + gnome + breakpoints in some "imgui" (???) related code trap the mouse and clicks don't work any longer.
Keyboard is somehow still active and faking a log off allows to reset the state without actually logging off (Atf-F4, Ctrl-Alt-Del).

Observed while debugging in VSCode and emacs.

And I know again how absurd this is.

**Comment by ocornut** [comment]
I'm closing this until you can reproduce. In all likehood it has nothing to do with Dear ImGui but if there is a way we can improve the examples we should aim to do it.

As for the breakpoint while mouse is captured issues, it is best discussed in #3650

**Comment by audetto** [comment]
By coincidence I was looking at it.
Today it has been happening often.

I have seen it even when I removed this line
``ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());``

Guess this settles the question.
