### ISSUE TITLE
How to do long touch with button？

### ISSUE THREAD

**Issue by xingyun86** [ocornut/imgui#3839]
Now I need long touch with button. How can I do it without SDL?

**Comment by xingyun86** [comment]
I solved it now. Thanks also.

**Comment by xingyun86** [comment]
> Now I need long touch with button. How can I do it without SDL?
I add new function with ColorButtonLongTouch
```
bool ImGui::ColorButtonLongTouch(const char* desc_id, const ImVec4& col, bool* bLongTouch, ImGuiColorEditFlags flags, ImVec2 size)
{
    ImGuiWindow* window = GetCurrentWindow();
    if (window->SkipItems)
        return false;

    ImGuiContext& g = *GImGui;
    const ImGuiID id = window->GetID(desc_id);
    float default_size = GetFrameHeight();
    if (size.x == 0.0f)
        size.x = default_size;
    if (size.y == 0.0f)
        size.y = default_size;
    const ImRect bb(window->DC.CursorPos, window->DC.CursorPos + size);
    ItemSize(bb, (size.y >= default_size) ? g.Style.FramePadding.y : 0.0f);
    if (!ItemAdd(bb, id))
        return false;

    if (window->DC.ItemFlags & ImGuiItemFlags_ButtonRepeat)
        flags |= ImGuiButtonFlags_Repeat;
    bool hovered, held;
    bool pressed = ButtonBehavior(bb, id, &hovered, &held, flags);

    if ((bLongTouch != NULL) && (pressed == true) && ((flags & ImGuiButtonFlags_Repeat) == ImGuiButtonFlags_Repeat))
    {
        *bLongTouch = held & hovered;
    }

    if (flags & ImGuiColorEditFlags_NoAlpha)
        flags &= ~(ImGuiColorEditFlags_AlphaPreview | ImGuiColorEditFlags_AlphaPreviewHalf);

    ImVec4 col_rgb = col;
    if (flags & ImGuiColorEditFlags_InputHSV)
        ColorConvertHSVtoRGB(col_rgb.x, col_rgb.y, col_rgb.z, col_rgb.x, col_rgb.y, col_rgb.z);

    ImVec4 col_rgb_without_alpha(col_rgb.x, col_rgb.y, col_rgb.z, 1.0f);
    float grid_step = ImMin(size.x, size.y) / 2.99f;
    float rounding = ImMin(g.Style.FrameRounding, grid_step * 0.5f);
    ImRect bb_inner = bb;
    float off = 0.0f;
    if ((flags & ImGuiColorEditFlags_NoBorder) == 0)
    {
        off = -0.75f; // The border (using Col_FrameBg) tends to look off when color is near-opaque and rounding is enabled. This offset seemed like a good middle ground to reduce those artifacts.
        bb_inner.Expand(off);
    }
    if ((flags & ImGuiColorEditFlags_AlphaPreviewHalf) && col_rgb.w < 1.0f)
    {
        float mid_x = IM_ROUND((bb_inner.Min.x + bb_inner.Max.x) * 0.5f);
        RenderColorRectWithAlphaCheckerboard(window->DrawList, ImVec2(bb_inner.Min.x + grid_step, bb_inner.Min.y), bb_inner.Max, GetColorU32(col_rgb), grid_step, ImVec2(-grid_step + off, off), rounding, ImDrawCornerFlags_TopRight | ImDrawCornerFlags_BotRight);
        window->DrawList->AddRectFilled(bb_inner.Min, ImVec2(mid_x, bb_inner.Max.y), GetColorU32(col_rgb_without_alpha), rounding, ImDrawCornerFlags_TopLeft | ImDrawCornerFlags_BotLeft);
    }
    else
    {
        // Because GetColorU32() multiplies by the global style Alpha and we don't want to display a checkerboard if the source code had no alpha
        ImVec4 col_source = (flags & ImGuiColorEditFlags_AlphaPreview) ? col_rgb : col_rgb_without_alpha;
        if (col_source.w < 1.0f)
            RenderColorRectWithAlphaCheckerboard(window->DrawList, bb_inner.Min, bb_inner.Max, GetColorU32(col_source), grid_step, ImVec2(off, off), rounding);
        else
            window->DrawList->AddRectFilled(bb_inner.Min, bb_inner.Max, GetColorU32(col_source), rounding, ImDrawCornerFlags_All);
    }
    RenderNavHighlight(bb, id);
    if ((flags & ImGuiColorEditFlags_NoBorder) == 0)
    {
        if (g.Style.FrameBorderSize > 0.0f)
            RenderFrameBorder(bb.Min, bb.Max, rounding);
        else
            window->DrawList->AddRect(bb.Min, bb.Max, GetColorU32(ImGuiCol_FrameBg), rounding); // Color button are often in need of some sort of border
    }

    // Drag and Drop Source
    // NB: The ActiveId test is merely an optional micro-optimization, BeginDragDropSource() does the same test.
    if (g.ActiveId == id && !(flags & ImGuiColorEditFlags_NoDragDrop) && BeginDragDropSource())
    {
        if (flags & ImGuiColorEditFlags_NoAlpha)
            SetDragDropPayload(IMGUI_PAYLOAD_TYPE_COLOR_3F, &col_rgb, sizeof(float) * 3, ImGuiCond_Once);
        else
            SetDragDropPayload(IMGUI_PAYLOAD_TYPE_COLOR_4F, &col_rgb, sizeof(float) * 4, ImGuiCond_Once);
        ColorButtonLongTouch(desc_id, col, bLongTouch, flags);
        SameLine();
        TextEx("Color");
        EndDragDropSource();
    }

    // Tooltip
    if (!(flags & ImGuiColorEditFlags_NoTooltip) && hovered)
        ColorTooltip(desc_id, &col.x, flags & (ImGuiColorEditFlags__InputMask | ImGuiColorEditFlags_NoAlpha | ImGuiColorEditFlags_AlphaPreview | ImGuiColorEditFlags_AlphaPreviewHalf));

    return pressed;
}

```

**Comment by IceyChiu** [comment]
> > Now I need long touch with button. How can I do it without SDL?
> > I add new function with ColorButtonLongTouch
> 
> ```
> bool ImGui::ColorButtonLongTouch(const char* desc_id, const ImVec4& col, bool* bLongTouch, ImGuiColorEditFlags flags, ImVec2 size)
> {
>     ImGuiWindow* window = GetCurrentWindow();
>     if (window->SkipItems)
>         return false;
> 
>     ImGuiContext& g = *GImGui;
>     const ImGuiID id = window->GetID(desc_id);
>     float default_size = GetFrameHeight();
>     if (size.x == 0.0f)
>         size.x = default_size;
>     if (size.y == 0.0f)
>         size.y = default_size;
>     const ImRect bb(window->DC.CursorPos, window->DC.CursorPos + size);
>     ItemSize(bb, (size.y >= default_size) ? g.Style.FramePadding.y : 0.0f);
>     if (!ItemAdd(bb, id))
>         return false;
> 
>     if (window->DC.ItemFlags & ImGuiItemFlags_ButtonRepeat)
>         flags |= ImGuiButtonFlags_Repeat;
>     bool hovered, held;
>     bool pressed = ButtonBehavior(bb, id, &hovered, &held, flags);
> 
>     if ((bLongTouch != NULL) && (pressed == true) && ((flags & ImGuiButtonFlags_Repeat) == ImGuiButtonFlags_Repeat))
>     {
>         *bLongTouch = held & hovered;
>     }
> 
>     if (flags & ImGuiColorEditFlags_NoAlpha)
>         flags &= ~(ImGuiColorEditFlags_AlphaPreview | ImGuiColorEditFlags_AlphaPreviewHalf);
> 
>     ImVec4 col_rgb = col;
>     if (flags & ImGuiColorEditFlags_InputHSV)
>         ColorConvertHSVtoRGB(col_rgb.x, col_rgb.y, col_rgb.z, col_rgb.x, col_rgb.y, col_rgb.z);
> 
>     ImVec4 col_rgb_without_alpha(col_rgb.x, col_rgb.y, col_rgb.z, 1.0f);
>     float grid_step = ImMin(size.x, size.y) / 2.99f;
>     float rounding = ImMin(g.Style.FrameRounding, grid_step * 0.5f);
>     ImRect bb_inner = bb;
>     float off = 0.0f;
>     if ((flags & ImGuiColorEditFlags_NoBorder) == 0)
>     {
>         off = -0.75f; // The border (using Col_FrameBg) tends to look off when color is near-opaque and rounding is enabled. This offset seemed like a good middle ground to reduce those artifacts.
>         bb_inner.Expand(off);
>     }
>     if ((flags & ImGuiColorEditFlags_AlphaPreviewHalf) && col_rgb.w < 1.0f)
>     {
>         float mid_x = IM_ROUND((bb_inner.Min.x + bb_inner.Max.x) * 0.5f);
>         RenderColorRectWithAlphaCheckerboard(window->DrawList, ImVec2(bb_inner.Min.x + grid_step, bb_inner.Min.y), bb_inner.Max, GetColorU32(col_rgb), grid_step, ImVec2(-grid_step + off, off), rounding, ImDrawCornerFlags_TopRight | ImDrawCornerFlags_BotRight);
>         window->DrawList->AddRectFilled(bb_inner.Min, ImVec2(mid_x, bb_inner.Max.y), GetColorU32(col_rgb_without_alpha), rounding, ImDrawCornerFlags_TopLeft | ImDrawCornerFlags_BotLeft);
>     }
>     else
>     {
>         // Because GetColorU32() multiplies by the global style Alpha and we don't want to display a checkerboard if the source code had no alpha
>         ImVec4 col_source = (flags & ImGuiColorEditFlags_AlphaPreview) ? col_rgb : col_rgb_without_alpha;
>         if (col_source.w < 1.0f)
>             RenderColorRectWithAlphaCheckerboard(window->DrawList, bb_inner.Min, bb_inner.Max, GetColorU32(col_source), grid_step, ImVec2(off, off), rounding);
>         else
>             window->DrawList->AddRectFilled(bb_inner.Min, bb_inner.Max, GetColorU32(col_source), rounding, ImDrawCornerFlags_All);
>     }
>     RenderNavHighlight(bb, id);
>     if ((flags & ImGuiColorEditFlags_NoBorder) == 0)
>     {
>         if (g.Style.FrameBorderSize > 0.0f)
>             RenderFrameBorder(bb.Min, bb.Max, rounding);
>         else
>             window->DrawList->AddRect(bb.Min, bb.Max, GetColorU32(ImGuiCol_FrameBg), rounding); // Color button are often in need of some sort of border
>     }
> 
>     // Drag and Drop Source
>     // NB: The ActiveId test is merely an optional micro-optimization, BeginDragDropSource() does the same test.
>     if (g.ActiveId == id && !(flags & ImGuiColorEditFlags_NoDragDrop) && BeginDragDropSource())
>     {
>         if (flags & ImGuiColorEditFlags_NoAlpha)
>             SetDragDropPayload(IMGUI_PAYLOAD_TYPE_COLOR_3F, &col_rgb, sizeof(float) * 3, ImGuiCond_Once);
>         else
>             SetDragDropPayload(IMGUI_PAYLOAD_TYPE_COLOR_4F, &col_rgb, sizeof(float) * 4, ImGuiCond_Once);
>         ColorButtonLongTouch(desc_id, col, bLongTouch, flags);
>         SameLine();
>         TextEx("Color");
>         EndDragDropSource();
>     }
> 
>     // Tooltip
>     if (!(flags & ImGuiColorEditFlags_NoTooltip) && hovered)
>         ColorTooltip(desc_id, &col.x, flags & (ImGuiColorEditFlags__InputMask | ImGuiColorEditFlags_NoAlpha | ImGuiColorEditFlags_AlphaPreview | ImGuiColorEditFlags_AlphaPreviewHalf));
> 
>     return pressed;
> }
> ```

I use your code but it cant repeat click?

**Comment by brentfpage** [comment]
In case others may be interested in long-press buttons, here's another way:
- where you are calling `ImGui::Button`, define the following:
    - `std::chrono::steady_clock::time_point press_start` (initialized to any time in the past)
- Add custom button functions `longpress_Button` and its friend `longpress_ButtonEx`.  To start, make these functions exact copies of the genuine `ImGui::Button` and `ImGui::ButtonEx` functions.
- Add a pointer to `press_start` as an argument to `longpress_Button` and `longpress_ButtonEx`.
- Append the following block to the end of `longpress_ButtonEx`:
```
bool long_press = false;
if(held) {
    if(g.ActiveIdIsJustActivated) {
        *press_start = std::chrono::steady_clock::now();
    } else if (std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now() - *press_start).count() > 500) {
        long_press = true;
    }
}
return long_press
```
With this implementation, `longpress_Button("button_label", &press_start)` returns `true` whenever the button is pressed for longer than 500 ms and continues to return `true` until the button is released.

**Comment by ocornut** [comment]
> In case others may be interested in long-press buttons, here's another way:
> [...]  To start, make these functions exact copies of the genuine ImGui::Button and ImGui::ButtonEx functions.

Please do NOT do this.
It's both complicated and unnecessary.

When a button is active is you can read `g.ActiveIdTimer`.
For the same specs as what you described ('returns true whenever the button is pressed for longer than 500 ms and continues to return true until the button is released.") you can simply use:

```cpp
bool LongPressButton(const char* label)
{
   ImGui::Button(label);
   return ImGui::IsItemActive() && ImGui::GetCurrentContext()->ActiveIdTimer >= 0.50f;
}
```
