### ISSUE TITLE
imgui.cpp, line 8484: Compiler warning

### ISSUE THREAD

**Issue by ZahlGraf** [ocornut/imgui#384]
Hi

I'm getting the following compiler warning with IMGUI 1.46

imgui.cpp: In function ‘bool ImGui::ColorEdit4(const char*, float*, bool)’:
imgui.cpp:8484:193: warning: too many arguments for format [-Wformat-extra-args]

This is the code:
```cpp
ImGui::SetTooltip("Color:\n(%.2f,%.2f,%.2f,%.2f)\n#%08X", col[0], col[1], col[2], col[3], IM_F32_TO_INT8(col[0]), IM_F32_TO_INT8(col[1]), IM_F32_TO_INT8(col[2]), IM_F32_TO_INT8(col[3]));
```

Best regards

**Comment by ocornut** [comment]
Its already fixed if you update.

**Comment by ZahlGraf** [comment]
Oh yes, now I see. Thanks.
