### ISSUE TITLE
Assert firing when docking window into another window

### ISSUE THREAD

**Issue by BobbyAnguelov** [ocornut/imgui#3855]
Version: 732cd83 (1.82 WIP)
Branch: docking
Back-ends: example_win32_directx12 (example backed)
Compiler: MSVC 16.8
Operating System: Windows 10

When I enable the imgui asserts, and I try to dock a window into another window, the assert on line 7783 in migui.cpp fires. I repro'd this in the supplied example by creating two windows and just trying to dock one into the other.

You can add the below code to the main.cpp of the example and try to dock B into A with the asserts enabled.

```
static bool m_a = true;
static bool m_b = true;

ImGui::SetNextWindowBgAlpha( 0.75f );
if ( ImGui::Begin( "A", &m_a ) )
{
    ImGui::End();
}

ImGui::SetNextWindowBgAlpha( 0.75f );
if ( ImGui::Begin( "B", &m_b ) )
{
    ImGui::End();
}
```
![bug](https://user-images.githubusercontent.com/10767490/109424412-83a91280-79b1-11eb-8066-b990477a9a5f.png)
![Screenshot 2021-02-28 103819](https://user-images.githubusercontent.com/10767490/109424413-8441a900-79b1-11eb-9d5c-8761c4d42b33.png)

**Comment by ocornut** [comment]
There’s an API inconsistency with Begin/End BeginChild/EndChild, it’s also described in the comments in your screenshots.

We have a plan to enable a path toward changing this api to requires End/EndChild to check the return value but its not an easy transition to enable.

**Comment by BobbyAnguelov** [comment]
Ah, I completely misunderstood the comment... So much of my code is wrong *facepalm*

**Comment by ocornut** [comment]
It's a very unpleasant inconsistency :/ 
If you can think of better wording/comments to help let me know, in the meanwhile I'll close this.

In master `Begin()` only ever return false when a window is collapsed, while in docking it is much more frequent (any window not currently visible will return false).

We have a WIP branch providing that exact API change with a helper tool that facilitate transitioning code, initially I wanted to merge the change as part of 1.80 but it created too many side-effects. I think that transition should be its own version release (maybe 1.83, 1.84 etc.), it's definitively in the horizon.
