### ISSUE TITLE
DirectX9: Texture bug, IDirect3DStateBlock9 might contains invalid values.

### ISSUE THREAD

**Issue by Nemirtingas** [ocornut/imgui#3857]
**Version/Branch of Dear ImGui:**

Version: 
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: MSVC
Operating System: Windows 10 - 1909 - 18363.1379
CPU: Intel Core i5-7300HQ
GPU: NVidia GTX 1060 3Gb
GPU Driver: NVidia 452.06

**My Issue/Question:**
I'm building an in-game overlay, some games that use DX9 have an issue when using ImGui, some textures disapear when I open my overlay, it looks like the issue is triggered by the state block.

https://github.com/ocornut/imgui/blob/cdf1926f21d17a3d9be7f69434cc18dc65dd6609/backends/imgui_impl_dx9.cpp#L133-L134

Adding a call to `IDirect3DStateBlock9::Capture` fixed those issues.
```
    // Backup the DX9 state
    IDirect3DStateBlock9* d3d9_state_block = NULL;
    if (FAILED(g_pd3dDevice->CreateStateBlock(D3DSBT_ALL, &d3d9_state_block)))
        return;

    if (FAILED(d3d9_state_block->Capture()))
    {
        d3d9_state_block->Release();
        return;
    }
```

**Comment by Demonese** [comment]
interesting bug, but why?
CreateStateBlock and Capture should do the same thing, maybe a bug in d3d9?

**Comment by ocornut** [comment]
Hello,

Same reaction as Demonese.

Before we go on adding random workarounds like this, I would like that you carry the burden of proof here by providing a repro or a deeper study or sufficient documentation as to why this would be needed.

Providing info about the hooked software, drivers involved, and maybe a video or with/without would give extra context.

**Comment by Nemirtingas** [comment]
Hi,

I understand perfectly, I'm just reporting some buggy behavior. Of course, hooking into a process and redirecting the 3D Renderer is also not something common.

I'll try to provide you some video with the `Capture` call on and off.

For now, I uploaded my overlay here if you need to take a look: https://github.com/Nemirtingas/ingame_overlay/

I tweaked a bit Dear ImGui on my fork: https://github.com/Nemirtingas/imgui

**Comment by Nemirtingas** [comment]
Here, I've uploaded a video of the bug happening: https://imgur.com/a/6ayy2vp

**Comment by ocornut** [comment]
Thank you @Nemirtingas for the details and video.
I've committed the workaround in 61a0908713eb81de216831b89e4cfefbcd9058b3

**Comment by Nemirtingas** [comment]
Thank you.

**Comment by dumbasPL** [comment]
I can also confirm that this gitch occurs in other source games and this does in fact fix it.  
Thank you for finally fixing this.

**Comment by MMOForum** [comment]
Hi bro 
![Uploading Ekran_Alnts.PNG…]()

**Comment by MMOForum** [comment]
Hi bro texture problem 
![Uploading Ekran_Alnts.PNG…]()
