### ISSUE TITLE
Undefined reference 

### ISSUE THREAD

**Issue by fourtytwo** [ocornut/imgui#386]
Do i need to preload some libs or do anything but "just" include the headers? I am getting Undefined reference errors for all Imgui functions/objects.

**Comment by ZahlGraf** [comment]
You have two options: 
1.) You build your own lib out of IMGUI and this has to be linked to your project.
2.) Or you add all IMGUI source files (not only the headers) to your project and link those source objects also to your executable. 

Just include the IMGUI headers is not enough.

**Comment by ocornut** [comment]
Just do 2) and include all the files in your project. 
There's no point building your own lib.
