### ISSUE TITLE
Issue with opening another modal inside modal

### ISSUE THREAD

**Issue by flamendless** [ocornut/imgui#3863]
**Version/Branch of Dear ImGui:**

Version: 1.81 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl2.cpp + imgui_impl_glfw.cpp 
Compiler: clang
Operating System: Manjaro Linux x86_64

**My Issue/Question:**

Opening a Modal from within a modal (click of a button) opens the 2nd modal, but it is not rendered.

In the video, clicking on the "new project" button, shows the modal correctly.
But clicking on the "save" button (inside the settings popup modal), the alert modal is not rendering but it should be (as it logs "here" continuously, see code `alert.cpp`)

**Screenshots/Video**

https://user-images.githubusercontent.com/17418737/109671438-077c1e00-7baf-11eb-9d59-71358b600ce1.mp4

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
//main.cpp
//imgui begin frame

if (ImGui::Button("Settings))
  Settings::is_open = true;

if (Settings:is_open)
{
    ImGui::OpenPopup("SettingsPopup");
    Settings::draw();
}

Alert::draw();
//imgui end frame

//alert.hpp
struct Alert
{
  static bool is_open;
  static std::string message;
  static void open(const std::string& msg);
  static void draw();
};

//alert.cpp
void Alert::open(ALERT_TYPE type, std::string msg)
{
	Alert::message = msg;
	Alert::is_open = true;
}

void Alert::draw()
{
	if (Alert::is_open) ImGui::OpenPopup("AlertPopup");

	if (ImGui::BeginPopupModal("AlertPopup", &is_open, flags))
	{
		PLOGD << "here"; //this gets printed though the modal is not rendering);
		ImGui::Text("%s", Alert::message.c_str());
		ImGui::EndPopup();
	}
}

//project.cpp (where the "new project" button is
{
	ImGui::Begin("Project", &m_is_open, m_flags);
		if (ImGui::MenuItem("New Project"))
			Alert::open(ALERT_TYPE::SUCCESS, "New Project created successfully.\nPlease open the created project file"); //this works
       ImGui::End();
}

//settings.cpp
{
	if (ImGui::BeginPopupModal("SettingsPopup", &m_is_open, m_popup_flags))
        {
            	if (ImGui::Button(ICON_FA_CHECK " Save"))
	        {
	                //this is working? it opens the 2nd modal but that doesnt get drawn. Also weird is that this modal closes?
			Alert::open(ALERT_TYPE::SUCCESS, "Configurations saved! Please restart to see the changes.");
	        }
        }
}
```

**Comment by ocornut** [comment]
Your code has no call to open "SettingsPopup" therefore is not standalone and hasn't been tested and likely doesn't convey all the subtleties needed to asnwer.

However, calling `OpenPopup()` multiple times is incorrect as it will close other popups stacked over it so you'll want to look at this first.

**Comment by flamendless** [comment]
> Your code has no call to open "SettingsPopup" therefore is not standalone and hasn't been tested and likely doesn't convey all the subtleties needed to asnwer.

Oh, I thought that the video is sufficient to show the settings. I've updated the code above to show how the `SettingsPopup` is called and drawn. Also the codebase of my project is too large so I've put a simpler codebase as example above.

> However, calling OpenPopup() multiple times is incorrect as it will close other popups stacked over it so you'll want to look at this first.

Thing is, if I just trigger the `OpenPopup` call once (i.e, press of a button), the popup does not render. I think it may be due to the ID stack as I've read around the issues. But if that's the main cause of the issue, then i will have to rewrite my code.

**Comment by ocornut** [comment]
We would like to investigate this but you would like our life easier and would largely improve the odds of this getting looked at if you provided a repro which can be pasted in a single location and which doesn't depends on external code.

**Comment by flamendless** [comment]
Hi there, i have refactored the code and  forgot the issue. I'll close this for now since i cant provide a repro of the bug. Thanks.
