### ISSUE TITLE
InputText: How to update the value without resetting ?

### ISSUE THREAD

**Issue by Corezcy** [ocornut/imgui#3864]
**Version/Branch of Dear ImGui:**

Version: 1.81
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_OpenGL3.cpp + imgui_impl_glfw.cpp _
Compiler: bazel VScode 
Operating System: Ubuntu 18.04.5 LTS

**My Issue/Question:**
I have a `ImGui::InputText("aaa", b)`. At first, the string `b` is empty .The problem is that I will update the `b` outside(such as a button, when I enter the button , `b` will be assigned) , but in the next loop, the `b` is reset (actually b is empty again). So how can I update the `b` outside without resetting ? ? ? Or in outside I can change the content in the inputtext(`aaa`)? 
Thanks a lot !

**Comment by ocornut** [comment]
It's not possible via public api yet.
See PR #2890 and #1506
I will try to merge #2890 soon.
