### ISSUE TITLE
Get Y point of a control

### ISSUE THREAD

**Issue by BoozeAddict** [ocornut/imgui#3866]
**Version/Branch of Dear ImGui:**

Version: 1.81
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Compiler: Visual Studio 2019
Operating System: Windows 10

**My Issue/Question:**

I'd like to know if it's possible to get the Y coordinate programatically. I'd like to make a new window appear at the height of the button pressed, and to the side. I could work out the X point through window width, so it's not a problem. 

**Screenshots/Video**

My idea:
![example](https://user-images.githubusercontent.com/4051327/109698631-45ba1300-7b98-11eb-96e1-182b7c94778d.jpg)

If it's not possible, i suppose getting the button heights + padding + spacing would work, but it'd be unconvenient, since there're bound to be changes.

**Comment by ocornut** [comment]
You can use GetItemRectMin() and GetItemRectMax().

**Comment by BoozeAddict** [comment]
Thank you, works like a charm. I apologize if it was in the demo, i may be blind sometimes.
