### ISSUE TITLE
the difference of InputText styles

### ISSUE THREAD

**Issue by Corezcy** [ocornut/imgui#3869]
**Version/Branch of Dear ImGui:**

Version: 1.81
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_OpenGL3.cpp + imgui_impl_glfw.cpp _
Compiler: bazel VScode 
Operating System: Ubuntu 18.04.5 LTS

**My Issue/Question:**
Why sometimes there is a label behind the InputText,  sometimes isn't. How to cancel the label behind the InputText to unify the style???
Thanks a lot ! Confused me 3 month ago...
![image](https://user-images.githubusercontent.com/33271784/109784262-dac71580-7c45-11eb-9dac-a25b1e982d4a.png)
![image](https://user-images.githubusercontent.com/33271784/109784281-e31f5080-7c45-11eb-88c3-a440ffbca053.png)

**Comment by ocornut** [comment]
Please read the FAQ
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-widgets-with-an-empty-label
