### ISSUE TITLE
Information about which table rows are visible

### ISSUE THREAD

**Issue by audetto** [ocornut/imgui#3877]
```
Dear ImGui 1.82 WIP (18101)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=10
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1846.00,852.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```
**My Issue/Question:**

I have a long table which is generated at runtime, and I display via ``ImGui::BeginTable``. I would like to only generate the records currently visible and skip all the other ones.

If ``ImGui::TableNextRow()`` returned a ``bool`` to tell if the record is visible or not, I could skip the ones that are not.

Using a table is not mandatory, I looked at the demo on scrolling https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L2798 but it still generates 100 items when only a few are visible.

Is this possible at all?

**Comment by ocornut** [comment]
See the tables demo is has numerous reference to clipping and using the list clipper.

**Comment by audetto** [comment]
Oh, yes: ImGuiListClipper. Than you.
