### ISSUE TITLE
Vulkan macOS error VkResult = 1000001003 when resizing application window

### ISSUE THREAD

**Issue by Mat-R** [ocornut/imgui#3881]
From the demo window:
```
Dear ImGui 1.81 (18100)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: __APPLE__
define: __GNUC__=4
define: __clang_version__=12.0.0 (clang-1200.0.32.29)
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_vulkan
io.ConfigFlags: 0x00000000
io.ConfigMacOSXBehaviors
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 2.00,2.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.81
Branch: tag v1.81

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: AppleClang 12.0.0.12000032
Operating System: macOS 11.2.1
GLFW: v3.3.3
Vulkan: v1.2.170 (installed by [downloading the dmg](https://vulkan.lunarg.com/sdk/home#mac) and running the install_vulkan.py)

**My Issue/Question:**

Running the example_glfw_vulkan, when resizing the application window by dragging the mouse from a window corner, the `[vulkan] Error: VkResult = 1000001003` error is displayed several times.
Also, at the end of the video below, we can see after resizing that the mouse position seems to not be synchronised with the demo window. When one want to highlight some items, the mouse cursor needs to be outside the demo window on the right.

**Screenshots/Video**

https://user-images.githubusercontent.com/36885389/110095132-deb97b80-7d9c-11eb-9510-e49bb04de284.mov

**Standalone, minimal, complete and verifiable example:** 

The example_glfw_vulkan is used without any modification from the repository.
In the example_glfw_vulkan example's directory, the following commands are run:
```sh
cmake .
make
./example_glfw_vulkan
```

I am new and experimenting dear imgui. If you need clarifications or more information just let me know.

**Comment by Mat-R** [comment]
This error is happening when the `err` variable in the example main.cpp is assigned `VK_SUBOPTIMAL_KHR`. It looks like in this case a swap chain rebuild solves the resize problem ([see](https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation#page_Suboptimal-or-out-of-date-swap-chain)).

I modified the following line (the if() condition) in the `FrameRender()` function to add the `VK_SUBOPTIMAL_KHR` case:
```c++
    if (err == VK_ERROR_OUT_OF_DATE_KHR || err == VK_SUBOPTIMAL_KHR) {
        g_SwapChainRebuild = true;
        return;
    }
```

I do not know much about all of this so this is maybe not a proper solution.

**Comment by ocornut** [comment]
Hello @Mat-R, thanks for the report and research.
Based on the link you shared I think that solution is suitable. I committed 6e4770ea5cee412aca4ac3f9567f1a50f980bbce.
I would guess that OSX compositor is more lenient that other OS and provide this is a hint. It looks like it is safe/better to rebuild at that time.

What I'm not entirely sure with how our Vulkan examples are structured is if the early return can cause some frames to be missed (as in, never rendered). I would assume it doesn't matter much in those examples. The Multi-viewport viewport in the docking branch will need the same fix applied and I guess we'll find out eventually if that early out can be problematic.
