### ISSUE TITLE
node->TabBar == NULL when creating tab bar inside a docked window

### ISSUE THREAD

**Issue by vlmillet** [ocornut/imgui#3883]
Version: git pull on 04/03/2021 (i don't find version)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: own back end on vulkan/windows
Compiler: vs2019
Operating System: Windows

**My Issue/Question:**

Once i started to create a tab bar inside a docked window, I also started to see appearing annoying assert "node->TabBar == NULL" in line 13444 of imgui.cpp . 
I'm not sure this assert has a meaning in that case, I will comment it on my side but I guess this is something that need to be addressed.

**Screenshots/Video**

You can see a tab bar present on this image, just inside a docked window (FYI, EndTabBar() only called on BeginTabBar returning true, as it should)
![image](https://user-images.githubusercontent.com/19949016/110109235-6f985300-7dad-11eb-9784-f76a45fcd4fc.png)

**Comment by ocornut** [comment]
Hello,
I'm not sure I can do anything with it without a repro. Can you aim to create repro code for it?

**Comment by vlmillet** [comment]
It is complicated as the application is quite complex right now (there is lots of windows, and .ini layout saving/loading at runtime, which i guess is responsible for the mess).
The bug didn't appear instantly after code was made, but now it appears 100% when this View3D is displayed, so I guess the issue has been 'stored' inside the .ini itself.
Have you ever tried the case where a BeginTabBar si called just inside a Begin/End of a docked window and saving/loading the .ini ?
I can try to debug it also If you give me tips on what this assert is trying to prevent.

**Comment by ocornut** [comment]
> Have you ever tried the case where a BeginTabBar si called just inside a Begin/End of a docked window and saving/loading the .ini ?

Well, have you tried?

**Comment by vlmillet** [comment]
I guess you didn't then.
And "yes" I tried and ... got this bug ? And at the same time "no", not with imgui purely isolated, I don't have a cleanup imgui test bench right now.
I'm really open to debug it and it might be something I do bad on my side, but some tips would be greatly appreciated on what this assert is supposed to prevent ... There is no comment or message.

**Comment by ocornut** [comment]
I think the assert is pretty self explanatory, a split mode is a parent of two childs, it can’t have a tab bar. This shouldn’t interfere with a user created tab bars. 

I am sorry but as requested by issue template the burden is on you to make a repro.  There are too many issues for me to tackle everything especially with so little information. Its very probable that just adding a tab bar in a docked window won’t have a bug (if it does that would be a good thing! but it’s unlikely) so things will need digging.

Backup your ini file if you think it has value in the repro.

**Comment by vlmillet** [comment]
I was already digging, and I continue digging right now, the report was just to keep trace somewhere and maybe have some hints on an easy win or something i missed. 
I do understand you have a bunch of work to solve a bunch of issues ! 
I keep you in touch with what I might find during the Dig.

**Comment by ocornut** [comment]
This works:
```cpp
if (ImGui::Begin("Test #3883"))
{
    if (ImGui::BeginTabBar("tabbar"))
    {
        if (ImGui::BeginTabItem("111"))
        {
            ImGui::Text("Hi from 111");
            ImGui::EndTabItem();
        }
        if (ImGui::BeginTabItem("222"))
        {
            ImGui::Text("Hi from 222");
            ImGui::EndTabItem();
        }
        ImGui::EndTabBar();
    }
}
ImGui::End();
```
![image](https://user-images.githubusercontent.com/8225057/110118502-c0fb0f00-7dba-11eb-8b3d-1b900497ac5f.png)

If you can keep running with the assert commented out, I suggest you use Metrics/Debugger to inspect your nodes:

![image](https://user-images.githubusercontent.com/8225057/110118795-2cdd7780-7dbb-11eb-9de6-dec465fb0cd0.png)

Notice how the parent split node doesn't have a tab bar, and each of the child nodes have a tab bar.

(Actually the `SelectedTabID` value displayed in parent node is just the "last value" and ihmo should be zero-ed, it's misleading here as there's no tab bar on that parent node)
I'm closing this for now.
When you have more information please post them and we can reopen the issue and attempt to find a solution for whatever triggers the issue.

**Comment by vlmillet** [comment]
So, as my digging goes deeper, first, if I might, I would recommend to move the IM_ASSERT ahead in the execution when the state SplitNode/TabBar incompatilibity might appear first : 
I've added :
`IM_ASSERT(!node->IsSplitNode());` in `DockNodeAddTabBar` and the assert is triggered, as expected, during the loading of the .ini data
From that, I cannot find any test in the Load from the .ini relative to that Split / TabBar that should not co-exist.
Which leads me to say :
- there is a corruption in the .ini data at some point which was not "asserted" ahead (before save), or the assert was skipped and the issue was spread into the .ini (probably my bad).
- some tests might be added in the Dock window loading / assignment of tab bars to "fix" potential corruptions.

What i find which seems corrupted in the .ini is that a window (with a name) has a Dock ID referring to a Node which has a Split Y, which seem to me a problem considering how your code seems to work.

Here is the guilty .ini file (node creating problems is ID=0x00000001 which has a Split Y and is referenced in "Asset Palette"): 
```
[Window][ToolBar]
Size=72,1377
Collapsed=0

[Window][Debug##Default]
Pos=60,9
Size=400,400
Collapsed=0

[Window][AssetExplorer]
Pos=68,0
Size=2492,1377
Collapsed=0

[Window][Asset Explorer]
Size=483,1377
Collapsed=0

[Window][DragNDrop]
Size=2560,1400
Collapsed=0

[Window][Asset Browser]
Size=1032,768
Collapsed=0

[Window][Pinned Assets]
Pos=483,0
Size=148,1377
Collapsed=0

[Window][Asset Palette]
Pos=556,33
Size=2004,1367
Collapsed=0
DockId=0x00000001,0

[Window][Inspector]
Pos=2026,33
Size=534,719
Collapsed=0
DockId=0x00000024,1

[Window][SceneView]
Pos=74,0
Size=2486,1377
Collapsed=0

[Window][UndoHistory]
Pos=74,20
Size=413,367
Collapsed=0

[Window][##Application.Window]
Pos=0,33
Size=2560,1367
Collapsed=0

[Window][Scripts]
Pos=349,1083
Size=1700,317
Collapsed=0
DockId=0x0000000B,0

[Window][Messages]
Pos=349,1083
Size=1700,317
Collapsed=0
DockId=0x0000000B,1

[Window][Assets]
Pos=0,481
Size=387,919
Collapsed=0
DockId=0x0000001E,0

[Window][Scene]
Pos=0,33
Size=347,1367
Collapsed=0
DockId=0x00000020,0

[Window][SceneSettings]
Pos=0,862
Size=268,538
Collapsed=0
DockId=0x0000001F,0

[Window][WorkspaceData]
Pos=2151,896
Size=409,48
Collapsed=0
DockId=0x00000022,0

[Window][Perforce]
Pos=1877,33
Size=683,458
Collapsed=0
DockId=0x0000002A,0

[Window][JSON Inspector]
Pos=2051,1404
Size=509,56
Collapsed=0
DockId=0x0000000A,0

[Window][Wild Render Config]
Pos=1587,1035
Size=973,367
Collapsed=0
DockId=0x00000016,0

[Window][##DockPopupWindow]
Pos=1193,234
Size=256,700
Collapsed=0

[Window][##HubPopupWindow]
Pos=681,234
Size=512,700
Collapsed=0

[Window][##NewLayoutWindow]
Pos=326,0
Size=200,19
Collapsed=0

[Window][##ActionSelectionBoxWindow]
Pos=853,24
Size=853,700
Collapsed=0

[Window][Entities Debug]
Pos=60,60
Size=398,327
Collapsed=0

[Window][Asset Search]
Pos=0,33
Size=391,1367
Collapsed=0
DockId=0x00000019,0

[Window][Asset Search Pins]
Pos=393,33
Size=161,1367
Collapsed=0
DockId=0x0000001A,0

[Window][TinyHouse - Model]
Pos=1684,538
Size=236,502
Collapsed=0

[Window][TinyHouse - Pieces]
Pos=1684,33
Size=236,503
Collapsed=0

[Window][TinyHouse - Face Cut]
Pos=0,538
Size=1682,502
Collapsed=0

[Window][TinyHouse - Cut Order]
Pos=1684,33
Size=236,503
Collapsed=0

[Window][TinyHouse - WoodCut]
Pos=0,538
Size=1682,502
Collapsed=0

[Window][Undo History]
Pos=2051,530
Size=509,250
Collapsed=0
DockId=0x0000002E,0

[Window][##InputLockedWheel]
Pos=0,33
Size=2560,1367
Collapsed=0

[Window][Modeling]
Pos=2138,585
Size=422,178
Collapsed=0

[Window][Debug Picking]
Pos=1889,1150
Size=671,250
Collapsed=0
DockId=0x0000000C,0

[Window][Model Editor]
Pos=270,33
Size=1554,48
Collapsed=0
DockId=0x0000000F,0

[Window][LiveMemoryProfiler]
Pos=724,162
Size=1544,920
Collapsed=0

[Window][Model Editor Settings]
Pos=2195,946
Size=365,87
Collapsed=0
DockId=0x0000001D,0

[Window][Height Obj Editor]
Pos=2184,544
Size=376,176
Collapsed=0
DockId=0x00000015,0

[Window][WildRPCClient]
Pos=2080,33
Size=480,166
Collapsed=0
DockId=0x00000012,0

[Window][Wild Engine]
Pos=1587,946
Size=973,87
Collapsed=0
DockId=0x0000001C,0

[Window][DiedreAngles]
Pos=2044,779
Size=516,467
Collapsed=0

[Window][Cooker]
Pos=1597,0
Size=963,1377
Collapsed=0

[Window][Wild Cooker]
Pos=2051,782
Size=509,620
Collapsed=0
DockId=0x00000016,0

[Window][Profiler - PC]
Pos=60,60
Size=1024,464
Collapsed=0

[Window][Scene Graphics]
Pos=1587,896
Size=973,48
Collapsed=0
DockId=0x0000000E,0

[Window][Asset Search Results]
Pos=0,33
Size=240,887
Collapsed=0

[Window][View 3D]
Pos=349,33
Size=1700,1048
Collapsed=0
DockId=0x00000009,0

[Window][Asset Search List]
Pos=593,33
Size=1967,1367
Collapsed=0

[Window][Asset Search Preview]
Pos=593,33
Size=1967,1367
Collapsed=0

[Window][Inspector##1]
Pos=269,160
Size=1279,1226
Collapsed=0

[Window][Inspector##2]
Pos=1550,160
Size=1279,1226
Collapsed=0

[Window][Inspector##Inspector0]
Pos=1826,33
Size=734,563
Collapsed=0
DockId=0x00000023,0

[Window][Inspector##Inspector1]
Pos=2032,33
Size=528,719
Collapsed=0
DockId=0x00000024,1

[Window][Inspector 2##Inspector2]
Pos=270,33
Size=1760,946
Collapsed=0
DockId=0x00000009,2

[Window][Inspector 1##Inspector1]
Pos=270,33
Size=1760,946
Collapsed=0
DockId=0x00000009,1

[Window][Inspector 1]
Pos=2051,33
Size=509,747
Collapsed=0
DockId=0x0000002D,0

[Window][Inspector 2]
Pos=1877,468
Size=683,934
Collapsed=0
DockId=0x00000027,0

[Window][Inspector 3]
Pos=1877,764
Size=683,638
Collapsed=0
DockId=0x0000002B,0

[Window][Inspector 4]
Pos=1877,415
Size=683,618
Collapsed=0
DockId=0x0000002C,0

[Docking][Data]
DockSpace                           ID=0xCF77178C Window=0x736B2A3D Pos=0,33 Size=2560,1367 Split=X Selected=0x12A3AEA2
  DockNode                          ID=0x00000017 Parent=0xCF77178C SizeRef=554,1367 Split=X Selected=0x59602AB6
    DockNode                        ID=0x00000019 Parent=0x00000017 SizeRef=391,1367 Selected=0x59602AB6
    DockNode                        ID=0x0000001A Parent=0x00000017 SizeRef=161,1367 Selected=0xCA3CDE68
  DockNode                          ID=0x00000018 Parent=0xCF77178C SizeRef=2004,1367 Split=X
    DockNode                        ID=0x00000003 Parent=0x00000018 SizeRef=347,1367 Split=Y Selected=0x18B8C0DE
      DockNode                      ID=0x00000020 Parent=0x00000003 SizeRef=326,827 Selected=0x18B8C0DE
      DockNode                      ID=0x0000001B Parent=0x00000003 SizeRef=326,538 Split=Y
        DockNode                    ID=0x0000001E Parent=0x0000001B SizeRef=430,577 Selected=0x7E7D78B8
        DockNode                    ID=0x0000001F Parent=0x0000001B SizeRef=430,340 Selected=0x65B0746D
    DockNode                        ID=0x00000004 Parent=0x00000018 SizeRef=2211,1367 Split=X
      DockNode                      ID=0x00000001 Parent=0x00000004 SizeRef=1700,1367 Split=Y Selected=0xADB8177D
        DockNode                    ID=0x0000000F Parent=0x00000001 SizeRef=1605,0 HiddenTabBar=1 Selected=0xEAABAB29
        DockNode                    ID=0x00000021 Parent=0x00000001 SizeRef=1605,944 Split=Y Selected=0xE83F9B20
          DockNode                  ID=0x00000009 Parent=0x00000021 SizeRef=1700,1048 CentralNode=1 Selected=0xE83F9B20
          DockNode                  ID=0x0000000B Parent=0x00000021 SizeRef=1700,317 Selected=0x22747CC0
      DockNode                      ID=0x00000002 Parent=0x00000004 SizeRef=509,1367 Split=Y Selected=0xF02CD328
        DockNode                    ID=0x00000005 Parent=0x00000002 SizeRef=495,720 Split=Y Selected=0x41FFD4D5
          DockNode                  ID=0x00000010 Parent=0x00000005 SizeRef=516,747 Split=Y Selected=0x41FFD4D5
            DockNode                ID=0x00000012 Parent=0x00000010 SizeRef=516,166 Selected=0x41FFD4D5
            DockNode                ID=0x00000013 Parent=0x00000010 SizeRef=516,341 Split=Y Selected=0xF02CD328
              DockNode              ID=0x0000000D Parent=0x00000013 SizeRef=516,911 Split=Y Selected=0xF02CD328
                DockNode            ID=0x00000007 Parent=0x0000000D SizeRef=813,861 Split=Y Selected=0xFE2A9712
                  DockNode          ID=0x00000023 Parent=0x00000007 SizeRef=734,563 Selected=0x620716B7
                  DockNode          ID=0x00000024 Parent=0x00000007 SizeRef=734,154 Split=Y Selected=0xFE2A9712
                    DockNode        ID=0x0000002A Parent=0x00000024 SizeRef=973,430 Selected=0xFE2A9712
                    DockNode        ID=0x00000025 Parent=0x00000024 SizeRef=973,429 Split=Y
                      DockNode      ID=0x00000028 Parent=0x00000025 SizeRef=973,729 Split=Y Selected=0xC704EB8F
                        DockNode    ID=0x00000026 Parent=0x00000028 SizeRef=708,433 Split=Y Selected=0xC704EB8F
                          DockNode  ID=0x0000002D Parent=0x00000026 SizeRef=824,495 Selected=0xC704EB8F
                          DockNode  ID=0x0000002E Parent=0x00000026 SizeRef=824,250 Selected=0x0A6448CD
                        DockNode    ID=0x00000027 Parent=0x00000028 SizeRef=708,934 Selected=0x5E0DBA35
                      DockNode      ID=0x00000029 Parent=0x00000025 SizeRef=973,638 Split=Y Selected=0x290A8AA3
                        DockNode    ID=0x0000002B Parent=0x00000029 SizeRef=683,127 Selected=0x290A8AA3
                        DockNode    ID=0x0000002C Parent=0x00000029 SizeRef=683,438 Selected=0xB76E1F00
                DockNode            ID=0x00000008 Parent=0x0000000D SizeRef=813,48 Split=X Selected=0x6219CBC7
                  DockNode          ID=0x0000000E Parent=0x00000008 SizeRef=562,209 Selected=0x6219CBC7
                  DockNode          ID=0x00000022 Parent=0x00000008 SizeRef=409,209 Selected=0x158ABF3E
              DockNode              ID=0x00000014 Parent=0x00000013 SizeRef=516,87 Split=X Selected=0x687D0D84
                DockNode            ID=0x0000001C Parent=0x00000014 SizeRef=341,269 Selected=0x687D0D84
                DockNode            ID=0x0000001D Parent=0x00000014 SizeRef=340,269 Selected=0x36EFFBA5
          DockNode                  ID=0x00000011 Parent=0x00000005 SizeRef=516,620 Split=Y Selected=0xF0F0E583
            DockNode                ID=0x00000015 Parent=0x00000011 SizeRef=516,62 Selected=0xF0F0E583
            DockNode                ID=0x00000016 Parent=0x00000011 SizeRef=516,112 Selected=0x255367A4
        DockNode                    ID=0x00000006 Parent=0x00000002 SizeRef=495,-2 Split=Y Selected=0x69C4D12C
          DockNode                  ID=0x0000000A Parent=0x00000006 SizeRef=510,81 Selected=0x69C4D12C
          DockNode                  ID=0x0000000C Parent=0x00000006 SizeRef=510,81 Selected=0x4A28C17E


```

**Comment by ocornut** [comment]
> Here is the guilty .ini file (node creating problems is ID=0x00000001 which has a Split Y and is referenced in "Asset Palette"):

Indeed it looks like the .ini data is invalid.
One should argue that it could/should detect and fail more gracefully but my reasoning is that this sort of assert would help us discover bugs vs silently failing would not.

Note that e.g. 1.81 fixed a known docking which _might_ have triggered this situation.
My only suggestion at this point would be to kill the .ini data, and if you stumble on this again try to see what lead to it.

**Comment by vlmillet** [comment]
>my reasoning is that this sort of assert would help us discover bugs vs silently failing would not

I agree with that 100%. I guess both would be good:
- an assert which helps discover the bug, 
- and then, if the user continues the execution on its own risk, try to limit the spread of the bug.

Yes this is what i'm going to do as the .ini dates from before my docking branch update.
I keep you in touch !

**Comment by vlmillet** [comment]
Just for you to know, I fell again on the bug even after cleaning the .ini files, but after some executions. 
I will put more checks in your code to catch the moment when the save begans to be corrupted...

**Comment by ocornut** [comment]
Thank you. Maybe try to remember what docking/window move action led to it.
I imagine if we had a log of all Docking actions it may help...

**Comment by vlmillet** [comment]
And another thing I do and I guess I forgot to mention, is making multiple calls of LoadIniSettingsFromFile/SaveIniSettingsFromFile in the same application execution, I wonder If it was designed to be used like this in your design (I do this to handle multiple layouts/workspaces in the same application).
Do I have to do specific stuff in this case ? clearing something before the "switch" ?
Because globally it works pretty well and is very handy, but I wonder if it is not the cause of the corruption somewhere.

Another thing I've noticed is that, if let's say I load a "Layout0.ini" that is corrupted for the dockID of window "Window0" but that window is not displayed, no assert happens, no "problem". BUT if I switch in the same run to a "Layout1.ini" where the "Window0" is now displayed, and then switch back to "Layout0.ini", it asserts, even if the "Window0" is still not displayed in the Layout0. This means two "LoadIniSettingsFromFile" of the same "Layout0.ini" act differently depending on the "past" of the application. I wonder if it is not a symptom of some cache not cleared or else, but I don't know the code enough to tell...

**Comment by ocornut** [comment]
`LoadIniSettingsFromFile()` was reworked last year to allow loading docking data but it mileage may vary, as e.g. #3215 suggest some have having issue. So the exact specs and limitation are not fully known.
But you should avoid to call it mid-frame, instead call it once before NewFrame(().
