### ISSUE TITLE
Imgui Hook, Cannot use keyboard and mouse.

### ISSUE THREAD

**Issue by SPURSGO** [ocornut/imgui#3896]
I inject a dll to another exe.
In my dll , I hook d3d9/d3d11  EndScene/Present, in hooked function,  I use ImGui paint a window,
but I can't  use mouse and keyboard anymore.

I need your help~~~
Thank you~

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by nymda** [comment]
there are plenty of reasons to do this that arent making a cheat yknow
