### ISSUE TITLE
I want to draw a child or a rectangle, but it is not drawn from the very corner

### ISSUE THREAD

**Issue by xLamantine** [ocornut/imgui#3908]
![image](https://user-images.githubusercontent.com/45714660/111036719-dd4a1c00-844a-11eb-997d-e4a0d1295e6c.png)
Cursor pos is 0,0

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
Please use Discussions if you want the freedom of ignoring guidelines.
