### ISSUE TITLE
problem with russian symbols, porting old version to latest svn

### ISSUE THREAD

**Issue by e3dalive2** [ocornut/imgui#391]
previously i managed to get Cyrillic symbols to display properly by using this  
[code]
static const ImWchar ranges[] =
		{
			0x0020, 0x04ff/*0x0FFF*/, // Basic Latin + Latin Supplement+Cyrilic[http://jrgraphix.net/r/Unicode/?range=0400-04FF]
			0,
		};

		ImFontConfig icons_config; icons_config.MergeMode = false; icons_config.PixelSnapH = true;
		ImFont* my_font1 = io.Fonts->AddFontFromFileTTF("data/IMFonts/DroidSans.ttf", 16.0f, &icons_config, ranges);
[/code]
in latest svn this doesn't work anymore, i tried this "io.Fonts->GetGlyphRangesCyrillic()" but it wasn't working either.

**Comment by ocornut** [comment]
There's no cyrillic characters in the DroidSans.ttf font. Have you tried with Arial Unicode or another font which include those characters?

**Comment by e3dalive2** [comment]
I will try that, thank you, but before it worked with that font without problems.

**Comment by ocornut** [comment]
I tried with Arial Unicode and DroidSans.ttf and your code and all worked, so you were right.
I'm surprised that Droid has cyrillic characters.

Is your path to the font file correct?

![cyrillic](https://cloud.githubusercontent.com/assets/8225057/11017847/3d4e0404-85a5-11e5-84ee-661a1b70aa96.PNG)

![droid](https://cloud.githubusercontent.com/assets/8225057/11017850/63d2a26a-85a5-11e5-84fb-f20ef0b603fa.PNG)

**Comment by ocornut** [comment]
@e3dalive2 Any news?

**Comment by e3dalive2** [comment]
i have found that you've actually added passworded input, that's good, i will refractor my code and try again when i will have time.

**Comment by ocornut** [comment]
I'm closing it. Let me know if it is still a problem.

**Comment by ocornut** [comment]
FYI `GetGlyphRangesCyrillic()` was now marked obsolete as glyph baked is now automatic.
