### ISSUE TITLE
Nothing responds in example under emscripten + opengl

### ISSUE THREAD

**Issue by voidware** [ocornut/imgui#3914]
current github master version (also with 1.81 release);

UI comes up in browser, but cannot click on anything nor does anything update, browser = firefox.

tracked to IM_ASSERT failed in  `static void ImGui::ErrorCheckNewFrameSanityChecks()`

Changed to;

`    IM_ASSERT((g.IO.DeltaTime >= 0.0f || g.FrameCount == 0)              && "Need a positive DeltaTime!");`

So it appears that DeltaTime ios sometimes zero. Not sure why this is, but with this "hack", everything seems to work.

**Comment by voidware** [comment]
Forgot to add, emscripten version 2.0.10

**Comment by ocornut** [comment]
Probably because of #3644 ?

**Comment by voidware** [comment]
Wow! yes, that's it. Thanks.
