### ISSUE TITLE
Is there a way to improve text rendering?

### ISSUE THREAD

**Issue by voidware** [ocornut/imgui#3917]
using emscripten + sdl + opengl3 + firefox.

I switched to the freetype atlas and also load fonts at 48.0f together with ` io.FontGlobalScale = 0.5f`. Atlas comes out at 512x256
The text still looks blurred.
Can it be improved. Perhaps there is a way to oversample/multisample. I tried some ideas, but they didn't seem to work when run in a browser.
I added the freetype font adjustment dialog, but fiddling with the settings makes things worse.

screenshot:
![imgui1](https://user-images.githubusercontent.com/2482354/111090537-f8d72480-8527-11eb-8884-52b7862f3755.png)

Any ideas? thanks.

**Comment by Demonese** [comment]
It seems that high DPI support is not enabled.

**Comment by ocornut** [comment]
Never use `io.FontGlobalScale`, it's old and not useful.
I'm surprised there's any issues with font are 48.0f using FreeType. If you want 24.0f use 24.0f, not 48.0f + post global scale.
Please move this to a Discussions as this is too open-ended, lacking too many details and and I cannot be having this same discussion everytime in Issues.
