### ISSUE TITLE
Avoid mouse mask when using popup.

### ISSUE THREAD

**Issue by Gringoniceguy** [ocornut/imgui#3929]
**Version/Branch of Dear ImGui:**

Version: bf497d2
Branch: Shadow (Using master doesn't fix this issue.)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp 
Compiler: MSVC2019 
Operating System: Windows 10

**My Issue/Question:**

I am trying to make a sort of [snackbar](https://material.io/components/snackbars), i would like to-do this using popups, but i dont want to capture mouse inputs, it just needs to be a top window.
Is there any way to avoid capturing mouse inputs to-do this or should i make this myself?

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
ImGui::OpenPopup(text); //Open popup
if (ImGui::BeginPopup(text)) //Begin popup
{
	ImGui::Text("Test text"); //Some example text to make the popup bigger.
        ImGui::EndPopup(); //End it
}
```

**Comment by Gringoniceguy** [comment]
Oops did too little searching in the issues i found have found a issue which references this ([#718](https://github.com/ocornut/imgui/issues/718)), but i found that using a primitive drawlist implementation is much better performance wise and was easy to make.

**Comment by ocornut** [comment]
> Is there any way to avoid capturing mouse inputs to-do this or should i make this myself?

There is a `ImGuiWindowFlags_NoInputs` flag you could pass to `Begin()` or `BeginPopup()` as well.

`ImGuiWindowFlags_NoInputs               = ImGuiWindowFlags_NoMouseInputs | ImGuiWindowFlags_NoNavInputs | ImGuiWindowFlags_NoNavFocus,`

**Comment by Gringoniceguy** [comment]
Well a snackbar should be able to have a button which using no input would not allow, there is also the thing when you press any button the pop-up closes.
So using a regular window/child-window or a primitive drawlist solution is most likely the best.

**Comment by ocornut** [comment]
Do you mean that you wanted inputs to reach the window BUT also to reach other windows around/behind it? In which case, yes, the purpose of popups is specifically to disallow the later as they are designed to be closed by clicking outside of their bounds. So if I understand this properly, yes, using a regular windows would work.

**Comment by Gringoniceguy** [comment]
Yes that is my intent, i just got a bit of tunnel vision on using popups for this.
