### ISSUE TITLE
Crash in "custom rendering" in the example app

### ISSUE THREAD

**Issue by Witek902** [ocornut/imgui#393]
Reproduction: 
1. Examples > Custom rendering
2. Start drawing a line with left mouse button.
3. Press right mouse button while holding the left mouse button.

Result:
```opengl3_example: ../../imgui.h:827: void ImVector<T>::pop_back() [with T = ImVec2]: Assertion `Size > 0' failed.```

**Comment by ocornut** [comment]
Fixed, thanks!
