### ISSUE TITLE
set scroll window to +size

### ISSUE THREAD

**Issue by GVOLTZNYX** [ocornut/imgui#3930]
wassup everyone. i have problem with set scroll, my window ends on bottom with 6 pixels, me need set to 20 pixels (without increase window), how do that?

what i have on end thewindow:
![Screenshot_2](https://user-images.githubusercontent.com/80821791/111451350-6484e180-8722-11eb-9672-13e00741e35e.png)

what i need on end the window:
![Screenshot_1](https://user-images.githubusercontent.com/80821791/111451366-6b135900-8722-11eb-8cf7-22214d5d4960.png)

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
