### ISSUE TITLE
32 Unresolved Externals...

### ISSUE THREAD

**Issue by IllusionDevs** [ocornut/imgui#3933]
So recently I tried changing some of the code around in the files and I got a few errors so I just reinstalled fresh files into my project but it still just gives me the errors they are all coming from imgui files and they are all random using latest release of ImGui worked before what I just said...

**Comment by nicolasnoble** [comment]
Sorry, but you're not even providing any sort of log or context here. Evidently, imgui works for other people here, so something's broken on your end. Share your project maybe? Or build log? Or anything useful?

**Comment by IllusionDevs** [comment]
1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::EndColumns(void)" (?EndColumns@ImGui@@YAXXZ)
1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::DebugNodeTable(struct ImGuiTable *)" (?DebugNodeTable@ImGui@@YAXPAUImGuiTable@@@Z)
1>imgui.obj : error LNK2001: unresolved external symbol "float __cdecl ImGui::GetColumnOffsetFromNorm(struct ImGuiOldColumns const *,float)" (?GetColumnOffsetFromNorm@ImGui@@YAMPBUImGuiOldColumns@@M@Z)
1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::DebugNodeTableSettings(struct ImGuiTableSettings *)" (?DebugNodeTableSettings@ImGui@@YAXPAUImGuiTableSettings@@@Z)
1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableGcCompactSettings(void)" (?TableGcCompactSettings@ImGui@@YAXXZ)
1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableGcCompactTransientBuffers(struct ImGuiTable *)" (?TableGcCompactTransientBuffers@ImGui@@YAXPAUImGuiTable@@@Z)
1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::EndTable(void)" (?EndTable@ImGui@@YAXXZ)
1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableSettingsInstallHandler(struct ImGuiContext *)" (?TableSettingsInstallHandler@ImGui@@YAXPAUImGuiContext@@@Z)
1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableEndRow(struct ImGuiTable *)" (?TableEndRow@ImGui@@YAXPAUImGuiTable@@@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "struct ImGuiTableSortSpecs * __cdecl ImGui::TableGetSortSpecs(void)" (?TableGetSortSpecs@ImGui@@YAPAUImGuiTableSortSpecs@@XZ)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableSetBgColor(int,unsigned int,int)" (?TableSetBgColor@ImGui@@YAXHIH@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "int __cdecl ImGui::TableGetRowIndex(void)" (?TableGetRowIndex@ImGui@@YAHXZ)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "int __cdecl ImGui::TableGetColumnFlags(int)" (?TableGetColumnFlags@ImGui@@YAHH@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableSetupColumn(char const *,int,float,unsigned int)" (?TableSetupColumn@ImGui@@YAXPBDHMI@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "float __cdecl ImGui::GetColumnWidth(int)" (?GetColumnWidth@ImGui@@YAMH@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "char const * __cdecl ImGui::TableGetColumnName(int)" (?TableGetColumnName@ImGui@@YAPBDH@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "float __cdecl ImGui::GetColumnOffset(int)" (?GetColumnOffset@ImGui@@YAMH@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableHeadersRow(void)" (?TableHeadersRow@ImGui@@YAXXZ)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableSetupScrollFreeze(int,int)" (?TableSetupScrollFreeze@ImGui@@YAXHH@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableHeader(char const *)" (?TableHeader@ImGui@@YAXPBD@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "bool __cdecl ImGui::TableSetColumnIndex(int)" (?TableSetColumnIndex@ImGui@@YA_NH@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::NextColumn(void)" (?NextColumn@ImGui@@YAXXZ)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "bool __cdecl ImGui::TableNextColumn(void)" (?TableNextColumn@ImGui@@YA_NXZ)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "int __cdecl ImGui::TableGetColumnIndex(void)" (?TableGetColumnIndex@ImGui@@YAHXZ)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::Columns(int,char const *,bool)" (?Columns@ImGui@@YAXHPBD_N@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableNextRow(int,float)" (?TableNextRow@ImGui@@YAXHM@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "bool __cdecl ImGui::BeginTable(char const *,int,int,struct ImVec2 const &,float)" (?BeginTable@ImGui@@YA_NPBDHHABUImVec2@@M@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "int __cdecl ImGui::GetColumnIndex(void)" (?GetColumnIndex@ImGui@@YAHXZ)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::PushColumnsBackground(void)" (?PushColumnsBackground@ImGui@@YAXXZ)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TablePopBackgroundChannel(void)" (?TablePopBackgroundChannel@ImGui@@YAXXZ)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TablePushBackgroundChannel(void)" (?TablePushBackgroundChannel@ImGui@@YAXXZ)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::PopColumnsBackground(void)" (?PopColumnsBackground@ImGui@@YAXXZ)
1>C:\Users\Illusion\Desktop\Projects\IllusionHookXYZ\Release\IllusionHookXYZ.dll : fatal error LNK1120: 32 unresolved externals

**Comment by ocornut** [comment]
You are not compiling and linking with imgui_tables.cpp

**Comment by xMathematics** [comment]
> 您没有编译和链接 imgui_tables.cpp

Perfectly solved the problem, and how to local the issues in imgui_tables.cpp.
