### ISSUE TITLE
How can i set size of ImgGUI window(which has noresize flag) while main window resize event

### ISSUE THREAD

**Issue by EfeOsman** [ocornut/imgui#3937]
How can i set size of ImgGUI window with noresize flag?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.

**Comment by colesnicov** [comment]
> How can i set size of ImgGUI window with noresize flag?

Call `ImGui::SetNextWindowSize(...)` before `ImGui::Begin(...)`..

**Comment by colesnicov** [comment]
https://github.com/ocornut/imgui/issues/3683
