### ISSUE TITLE
About ImageButton Rounding

### ISSUE THREAD

**Issue by Ghost-yc** [ocornut/imgui#394]
Imagebutton not use frame rounding parameters

**Comment by ocornut** [comment]
I don't think it would be desirable to have rounding if you are displaying pictures. Clipping is done on a rectangle basis so pictures couldn't be clipped following a round shape.

**Comment by Ghost-yc** [comment]
In fact, I say that the imagebutton padding frame rect is not used rounding parameters to fill part(ImGui :: ImageButton of RenderFrame function). is not part of image rect

**Comment by ocornut** [comment]
OK I think I know what you mean, I fixed it.
