### ISSUE TITLE
can we tweak the speed when ImGuiWindowFlags_AlwaysAutoResize?

### ISSUE THREAD

**Issue by moebiussurfing** [ocornut/imgui#3947]
I would like to set the speed (faster) when a text input widget is being resized.
that's bc sometimes I preload longer or shorter text names when browsing presets.

**Comment by ocornut** [comment]
(1). Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
Closing.

(2) There's no "speed" for resizing. Resizing happens every frame to fit contents.

(3) The question is too ambiguous for us to provide a good answer.
