### ISSUE TITLE
Rendering Imgui on Direct2d overlay

### ISSUE THREAD

**Issue by chunkybo1** [ocornut/imgui#3948]
Hi, i was wondering if its possible for me to render imgui on an external Direct2d Overlay?

If this question has been answered or declined before, i sincerely apologize for bloating. I do plan on using this for game cheating, so i understand if you reject this question in advance, as these issues appear to be full of wannabe gamehacking "skids" and "pasters". Thanks, - Chunky

**Comment by Xiliusha** [comment]
direct2d + direct3d11.1 + dx11backend

**Comment by ocornut** [comment]
> Hi, i was wondering if its possible for me to render imgui on an external Direct2d Overlay?

The answer is almost always "Yes, but you may have to provide the rendering function yourself".
At which point - assuming no one published theirs - it is in your end to figure out the plumbing. It shouldn't be too hard if you are familiar with graphics API.

As answered, one possible route may be to initialize D3D over it.
Another possible route might be to use a software rasterizers (see https://github.com/ocornut/imgui/wiki/Useful-Widgets#software-rendererrasterizer)
