### ISSUE TITLE
imgui+sdl: SDL_CaptureMouse and unwanted side effects

### ISSUE THREAD

**Issue by audetto** [ocornut/imgui#3956]
```
Dear ImGui 1.81 WIP (18003)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=10
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1661.00,1147.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

This was originally mentioned here

https://github.com/ocornut/imgui/issues/3835#issuecomment-803447395

but I am seeing it on a Pi4, so with completely different Desktop environment and version of all the tools, libraries involved.
So I think it is a real bug somewhere.

What happens is that, when a breakpoint is triggered and the debugger pops up, the mouse does not work any longer. It moves around, but I cannot click anywhere.

Keyboard still works and I can use it to continue execution, at which point everything works again.

Is there anything anyone could thing of, about the mouse being captured by SDL/ImGui and not released? It should not even be possible, but I don't know what else to think of.

vscode was my first culprit, till I saw it in emacs. gdb?

where do I file a bug report?

**Comment by audetto** [comment]
Turns out that the reason why the mouse is captured by the app is this

https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_sdl.cpp#L275

and this is the documentation about it

https://wiki.libsdl.org/SDL_CaptureMouse

I think this explains what happens:

- user clicks on the imgui ui
- imgui tells SDL2 to capture the mouse
- breakpoint is triggered
- mouse is not available to the debugger

this is very similar to https://github.com/ocornut/imgui/issues/3650

what are the pros and cons of using SDL_CaptureMouse?
any way to use it without paying the heavy prices when debugging?

**Comment by ocornut** [comment]
It seems surprising that a debugger GUI wouldn't claim the capture back, seems like poor design of the debugger or windowing system interaction. I am using Visual Studio 2019 daily and never has such an issue.

It is extremely standard to capture the mouse on any interaction. It means that e.g. when clicking on imgui/3d viewport and dragging outside that viewport, element outside the window won't react to hovering.

As pointed out #3650 essentially disable capturing on RPI so if you are running your toolchain on RPI consider this solved.

**Comment by ocornut** [comment]
> As pointed out #3650 essentially disable capturing on RPI so if you are running your toolchain on RPI consider this solved.

My bad, I mistook #3650 for #3950 which is a different thing, my comment above doesn't apply.

**Comment by audetto** [comment]
I think this is a bug (or a feature) rotating around gdb / SDL / GNOME / LXDE / X11 / (maybe Wayland solves it)

Easy to see how this is a feature:

- gdb does not care about what is being debugged (and which resources might or might not have acquired)
- X11 does not care something is being debugged (and that it should release something to play well)

In Windows everything comes from the same source and they is full knowledge.

I will write to the SDL mailing list to see what they think about it.

**Comment by audetto** [comment]
Here is the link
https://discourse.libsdl.org/t/debugging-with-sdl-capturemouse/31014

Moreover, SDL_CaptureMouse is not implemented for all platforms.

https://github.com/libsdl-org/SDL/search?q=CaptureMouse

Wayland, for instance, does not support it.

And the Windows implementation does not see such a *sledgehammer*

https://github.com/libsdl-org/SDL/blob/bd06538778102f72bad8393ef07da5a1ec444217/src/video/windows/SDL_windowsmouse.c#L257

**Comment by ocornut** [comment]
To simplify tracking I'll close this as overlapping #3650 please post the useful info you posted here.
I realize there are two slightly different aspects involved:
- conflict with SDL_SetRelativeMouseMode()
- break during capture preventing further inputs.

For the later, I think this should be reported to SDL which would be in best position to find a workaround, but I also agree and understand we should aim to find a workaround in our backend and #3650 can be used for that.
