### ISSUE TITLE
Can you, please, expain the order of calls of render function in sdl2/opengl3 implementation?

### ISSUE THREAD

**Issue by xahon** [ocornut/imgui#3958]
https://github.com/ocornut/imgui/blob/59da01901ed71a53e5578c34d90d631757c3870d/examples/example_sdl_opengl3/main.cpp#L199-L204

Imgui render function is getting called first, then we call raw gl functions and then we call imgui render again  
Does that "interleaving" important? I'm trying to wrap all the code in methods and I have to define `RenderGUI` twice like `RenderGUIBefore` and `RenderGUIAfter` to call `RenderFrame` between them

**Comment by ocornut** [comment]
ImGui::Render() like any ImGui function doesn't interact with graphics API, therefore it would be misleading to move it lower in the function. This is the most logical order here.

Different engine with different constraints and different amount of parallelism may be tempted to have finer control over this, e.g. call Render(), start uploading vertices in GPU buffer so it's ready by the time rendering need to be done perhaps next frame etc. There's isn't one answer to this question but you can step at all the code and figure out what it is doing.

>  I'm trying to wrap all the code 

As a suggestion, make sure you are not manufacturing your own problem with excessive wrapping.
