### ISSUE TITLE
DragInt does not clamp the value to v_min/v_max when both are set to 0.

### ISSUE THREAD

**Issue by Myszkoj** [ocornut/imgui#3959]
There is some bug with DragInt when range values are equal.
I assumed that passing any value to that range would result in it being set to v_min(in my case 0).
I have tracked the issue and problem appears in this line:
![imgui_bug2](https://user-images.githubusercontent.com/9519504/112003430-30922d80-8b21-11eb-8131-7741bc29817e.png)

In my opinion it should be "const bool is_clamped = (v_min <= v_max);", or am I missing something?

**Comment by ocornut** [comment]
It cannot be changed as historically and to simplify the API the default min and max values have always been 0. The workaround used by e.g. `DragFloatRange2()` is to use the `ImGuiSliderFlags_ReadOnly` flag:

`ImGuiSliderFlags flags = (min_min == min_max) ? ImGuiSliderFlags_ReadOnly : 0;`

**Comment by Myszkoj** [comment]
So if I understand it correctly, the default behavior of any drag control is that it ignores the range if both values are the same?
Btw, why is ImGuiSliderFlags_ReadOnly kept in a separate enum? The first thing i checked when i stumbled upon this issue was ImGuiSliderFlags_.

**Comment by ocornut** [comment]
> So if I understand it correctly, the default behavior of any drag control is that it ignores the range if both values are the same?

Yes.
I can't say it's the one perfect solution but legacy wise it's going to be difficult to change. 
It's also quite a valuable convenience that default of 0,0 disable clamping, both for C++ users (and for users of foreign languages like C).

> Btw, why is ImGuiSliderFlags_ReadOnly kept in a separate enum? The first thing i checked when i stumbled upon this issue was ImGuiSliderFlags_.

Argh, you are right, it's only been added to the private enum so far (it is a pretty recent addition and I wanted/need to think about it a little more to make it extra clear what the difference between the more-general ReadOnly and Disabled item flags #211 are). So for now you would need to use imgui_internal.h

**Comment by Myszkoj** [comment]
I used your solution with ImGuiSliderFlags_ReadOnly.
Thx for the help and explanation :)
