### ISSUE TITLE
"Glfw Error 65544: X11: RandR gamma ramp support seems broken"

### ISSUE THREAD

**Issue by maxomous** [ocornut/imgui#3960]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.83 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: g++
Operating System: Raspbian GNU/Linux 10 (buster) on Raspberry Pi

**My Issue/Question:**

Compiles fine and runs absolutely fine but terminal displays: "Glfw Error 65544: X11: RandR gamma ramp support seems broken". Doesn't seem to effect usage though.

thanks

**Comment by ocornut** [comment]
Hello,
I believe this should be reported to GLFW rather than here, but it would be good to identify which functions exactly triggers this.

**Comment by ocornut** [comment]
I'll close this now and I would recommend reporting to GLFW.
