### ISSUE TITLE
ColorPicker popup immediately closes if spawned in separate viewport and clicked inside parent window 

### ISSUE THREAD

**Issue by Myszkoj** [ocornut/imgui#3969]
Hello :)

I use combination of imgui-tables and imgui-docking from 31.07.2020(VERSION 1.78 WIP (In Progress))
OS - Windows10, VisualStudio 2019 community

I noticed that if you open the color widget via ColorEdit4 (and maybe in any other way), as in a title of this issue, it will close unless you click outside the window that spawned it. 

I managed to repreduce this "bug" in docking branch demo.
So if you click inside the red region, popup will immediately close without the option to interact with it in any way. 
![imgui_bug3_c](https://user-images.githubusercontent.com/9519504/112505139-c7165700-8d8c-11eb-979f-f4156f54c433.png)
![imgui_bug3_d](https://user-images.githubusercontent.com/9519504/112505433-0e9ce300-8d8d-11eb-8b72-dd4ac9818d3b.png)

It looks that in order for this to happen, the color widget popup must be outside the main window(viewport).

I tested it with example_glfw_opengl3, but I have the same problem with sdl2.

**Comment by Myszkoj** [comment]
I forgot to add that after you click inside the blue region you can interact with whole popup.

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
**We cannot answer this without precise version number and backend used.**
Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing for now.

**Comment by Myszkoj** [comment]
> > Am I doing something wrong here?
> 
> Yes, you didn't follow requested guidelines and issue template.
> **We cannot answer this without precise version number and backend used.**
> Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
> 
> Closing for now.

Hope that helps :)

**Comment by ocornut** [comment]
I believe a bug has been fixed in 1.81 and you should try to update:
https://github.com/ocornut/imgui/releases/tag/v1.81
See #3734

**Comment by Myszkoj** [comment]
Oh, in that case, sorry for the problem and thx for the help :)

**Comment by ocornut** [comment]
Assuming the fix works for you please confirm that it is indeed the same bug! (and not another) Thank you!

**Comment by Myszkoj** [comment]
> Assuming the fix works for you please confirm that it is indeed the same bug! (and not another) Thank you!

Confirmed, problem disappeared after updating to 1.81, thx again.
