### ISSUE TITLE
PushStyleVar and BeginChild

### ISSUE THREAD

**Issue by aFakeCmd** [ocornut/imgui#3978]
**Version/Branch of Dear ImGui:**
35b1148
Version: 1.82
Branch: release

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Operating System: win 10 x64

**My Issue/Question:**

Hello, ocornut. How can I change ImGui StyleVar_WindowPadding correctly with beginchild so that my rectangle is at the very top of the ImGui window?

**Screenshots**

What does it look like for me:
![Безымянный](https://user-images.githubusercontent.com/60480464/112745028-632fa080-8fcf-11eb-8844-b60526209baf.png)
How I want:
![Безымянный](https://user-images.githubusercontent.com/60480464/112745079-dafdcb00-8fcf-11eb-833e-fa24c916a451.png)

**Code**
```
            ImGui::SetNextWindowSize(ImVec2(500, 500));
            ImGui::SetNextWindowPos(ImVec2(500, 500), ImGuiCond_Always, ImVec2(0.5, 0.5));
            ImGui::Begin("##test", 0, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar);

            ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2{ 0.f, 0.f });
            ImGui::BeginChild("##test2", ImVec2(500, 100), false, ImGuiWindowFlags_AlwaysUseWindowPadding);
            ImVec2 pos = ImGui::GetCursorScreenPos();
            ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(pos.x, pos.y), ImVec2(pos.x + 500, pos.y + 20), ImColor(ImVec4(0, 1, 0, 1)), 0);
            ImGui::EndChild();
            ImGui::PopStyleVar();

            ImGui::End();
```

**Comment by ocornut** [comment]
The padding you are seeing here is not the child window padding but the padding of the “##test” window, so you should push the zero padding earlier.

**Comment by aFakeCmd** [comment]
Is it possible to overlay a rectangle completely without edges?
![Безымянный](https://user-images.githubusercontent.com/60480464/112747899-831c8f80-8fe2-11eb-8032-1238112c868a.png)

**Comment by ocornut** [comment]
Need to disable host window borders, OR push a cliprect to draw over the borders.
