### ISSUE TITLE
Inaccuracies when large values in window scrolling with MouseWheel

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#398]
I have been recently coding a "ListView" that shows some realtime data coming from a decently sized database (couple of gigabytes, potentially millions of records). 
I think I am doing things properly with ImGuiListClipper approach to render only the visible part etc.

Everything works fine with one exception: when you start approaching the end of the list, inaccuracies in scrolling position become very annoying.
This is very noticeable when using mouses that allow for precise or inertial scrolling like the apple magic mouse or some trackpads, where you give small increments to the mousewheel.
When you're near the end of the list, you cannot scroll by small increments, but you have to force larger mousewheel quantities.

My intuition tells me that it's due to ImGui DC Cursor\* variables being floats.
I think I can find ways around that, by artificially limiting/re-offsetting this big range but I'm posting here for discussion.
I am not sure if this can be considered an actual issue, if it can be solved by using doubles in some limited places (Cursor and Scroll internal variables?) with proper casting or if it potentially requires to switch everything to double precision.

Thoughts?

A small test could be (of course you need a proper mouse to appreciate the issue):

``` cpp
        ImGui::SetNextWindowSize(ImVec2(200, 500), ImGuiSetCond_FirstUseEver);
        ImGui::Begin("Large scrolling test");
        float itemSizeY = 36;
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
        ImGuiListClipper clipper;
        clipper.Begin(1500000, itemSizeY);
        for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; i++)
        {
            ImGui::PushID(i);
            ImGui::Selectable("##selectable", false, 0, ImVec2(0, itemSizeY));

            ImGui::SameLine();
            ImGui::Text("Line %d", i);
            ImGui::PopID();
        }
        clipper.End();
        ImGui::PopStyleVar();
        ImGui::End();
```

**Comment by ocornut** [comment]
Hmm, I am guessing the simplest way to solve that would be assume the Scroll value always use integer numbers, avoid using sub-decimal and to store the sub-decimals into a separately accumulator.

This code
```
SetWindowScrollY(window, window->Scroll.y - g.IO.MouseWheel * window->CalcFontSize() * scroll_lines);
```

Would have to add the delta to a small persistent float and then transfer the integer part into to the main float.

```
// Decimals into a small accumulator
window->ScrollDecimals.y -= g.IO.MouseWheel * window->CalcFontSize() * scroll_lines;
// floor to int (handling negatives), add that to window->Scroll.y and subtract from window->ScrollDecimal
```

**Comment by ocornut** [comment]
15000000 * 36 = 54000000, that's 25+ bits for the integer part alone so you would probably still run into precision issues if you really have that number of items.

When flushing the excess integer amount of ScrollDecimals to Scroll we can convert Scroll to int again and check if the excess wasn't lost in translation, if it was don't remove the integer component of ScrollDecimals. So you may end up occasionally scrolling by increment of 2 pixels instead of 1 but I suppose that wouldn't be a problem.

**Comment by Pagghiu** [comment]
You're right on the 25+ bits...with these large numbers the integer part is not getting added correctly, even for smaller numbers than the ones shown in my example.

On my PC for example
```C
    float d = 18071932;
    double u = 1;
    printf("%f\n",d);
    d += u;
    printf("%f\n",d);
```
outputs
```
18071932.000000
18071932.000000
```

In my code I was trying to account for arbitrary number of records, and testing with very large data, but looks like I need to do some kind of "paging" to avoid entirely this kind of precision issues entirely.

Thanks for the input!

**Comment by Pagghiu** [comment]
Thanks to your inputs again, by digging in the code where you've been pointing me at I have been able to fix some problems due to other (my) issues.
FYI this is what I'm doing, it's a very large log book with data coming from an embedded SQLITE database linked inside the app. I am handling partial views, paging, query interruptions etc. asynchronously to avoid blocking the UI. The test dataset is about 500 Meg.

I'm trying to downsample to keep the GIF to a minimum with 30 FPS but it's still 2.5 Meg.
I'm sorry for anyone browsing this page using cellular data !
![largescrolling](https://cloud.githubusercontent.com/assets/5406873/10945015/3d33d060-831c-11e5-9c4d-58b0508335ae.gif)

**Comment by ocornut** [comment]
So does it works right now? I'm seeing occasional flickering in the GIF.

It is unclear what you are doing when selecting an item and the options appears. If you use the clipping helper it assume that items are of even height. In my application navigating big list I am using popups for further interaction to allow list items to stay the same height. It looks like you may be doing a similar thing by only displaying the option at the bottom (it is a popup?).

If you know which items are opened (maybe a single one?) and you have that information in a data structure that is cheap to access, you can do what the clipper does and fast-forward downward for whole blocks of collapsed items only. 

Now, realistically, is there a point in using mouse+scrollbar to browse a 1.5 million list of item?

**Comment by Pagghiu** [comment]
It works much better now, because I was incorrectly sizing the item height causing some scrolling issues with the clipper.
The initial issue with the "small increments in mouse-wheel" not getting accumulated correctly in the scroll position is still here but it's a lot more acceptable now. 
Definitively it's not worth for you to try a partial fix if it may be causing other issues.

Both the  ListView and the options are two separate manually sized child windows.

As you're saying, it's probably not the best experience to let the user scroll millions of items, but I was trying to push it to limits before deploying this into our production software.
My initial thoughts was that as this data comes from a real database, I wanted to be able to search and scroll the entire database independently of its size.

Now, what I will probably do is to have a sub-virtual view that preselects a smaller range of items that can be scrolled from the database. Then if the user scrolls up, I will enlarge the range properly. It will take users a good number of scrolls to the top before the list will approach the million item count, and even in that case, I could move the entire range up instead of just enlarging it, to avoid making it bigger than, let's say 300.000 items, that is still a huge number handled smoothly by the current code.

Does it makes sense to close the issue?

**Comment by ocornut** [comment]
Let's close it yes :)
We can revisit the decimal scrolling thing if that pops bakc out, it won't be a difficult fix if we want just that later.

**Comment by KnIfER** [comment]
how to.. scrollToPos?

**Comment by KnIfER** [comment]
![13 _li](https://user-images.githubusercontent.com/11593903/42917148-f11cdb84-8b3a-11e8-84d7-672a1ee51599.jpg)

I dont understand,with in total 106146 entrys, the first entry visible is at POS 104525, but clipper.getDisplayStart() START from 52262, which means the for loop has a run number of  (104525-52262=52263) to fetch just the  first visible entry ,why?
```
    		jimgui.Begin("list",null,myListStyle);
			ImGuiListClipper clipper = new ImGuiListClipper();
			int ItemSize = 18;
			clipper.Begin((int) md.getNumberEntries()/2,ItemSize);
			clipper.setStepNo(1);
	        for (int i = clipper.getDisplayStart(); i < clipper.getDisplayEnd(); i++)
	        {
	            jimgui.PushID(i);
	            jimgui.Selectable("##selectable", false, 0, new ImVec2(0, ItemSize));
	            
	            jimgui.SameLine();
	            jimgui.Text(md.getEntryAt(clipper.getDisplayStart()+i)+" !!!SATRT=="+clipper.getDisplayStart()+" !!!POS=="+(clipper.getDisplayStart()+i));
	            jimgui.PopID();
	        }
	        clipper.End();
    		jimgui.End();
```
