### ISSUE TITLE
make frame in fullscrean

### ISSUE THREAD

**Issue by s365z** [ocornut/imgui#3980]
Hi i want to make my frame in like full screen
![image](https://user-images.githubusercontent.com/54293041/112753050-5febe300-8fd6-11eb-9bea-9665cd5edd89.png)
i hope you can hep me thx.

**Comment by sonoro1234** [comment]
This depends on the plattform backend:

 In SDL
 `sdl.setWindowFullscreen`
 
in GLFW 
```Lua
monitor = glfw.glfwGetPrimaryMonitor() 
local mode = glfw.glfwGetVideoMode(monitor);			
glfw.glfwSetWindowMonitor(window, monitor, 0, 0, mode.width, mode.height, mode.refreshRate);
```

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template.  Closing, blocked.
