### ISSUE TITLE
How to display "label - value" consistently.

### ISSUE THREAD

**Issue by audetto** [ocornut/imgui#3983]
Situation is trivial.
I would like to display a grid of label / values, some of which are options, some are fixed.
![Screenshot from 2021-03-28 16-42-19](https://user-images.githubusercontent.com/212523/112758118-9597c880-8fe4-11eb-969b-951e9c6fb018.png)

CPU and Mode are **not** options, but just values I want to display.
I'd use a Text or a Selectable.

But I don't know how to attach a label.

What I tried to use is a Combo with no options (this asserts).
Now I am using a ReadOnly InputText (but you still able to put the mouse cursor there), but it still feels I am using a sledgehammer for something trivial.

What is the simplest solution?

**Comment by rokups** [comment]
Hey @audetto,
This works:
```cpp
float x = ImGui::GetCursorPosX();
ImGui::TextUnformatted("Custom value");
ImGui::SameLine();
ImGui::SetCursorPosX(x + ImGui::CalcItemWidth() + ImGui::GetStyle().ItemInnerSpacing.x);
ImGui::TextUnformatted("Custom label");
```
![image](https://user-images.githubusercontent.com/19151258/112801316-6c754780-9079-11eb-847c-16f740179a0c.png)

**Comment by audetto** [comment]
![Screenshot from 2021-03-29 09-33-50](https://user-images.githubusercontent.com/212523/112809438-eacdeb80-9071-11eb-93cc-9c70c5847689.png)

Your suggestion: ... 2
Using `ImGui::LabelText` ... 3

The latter seems to do a better job at vertical spacing too.

But what I wanted to achieve was the highlighted background that I get when I use a Combo (or a TextInput).

**Comment by rokups** [comment]
Oh i was not aware of LabelText.

To render a backround use `ImGui::GetWindowDrawList()->AddRectFilled(...)` with a color from style.

**Comment by ocornut** [comment]
Another possibility is to use BeginCombo() but do not fit any element in it (or the same element) and maybe use the ImGuiComboFlags value to hide the arrow when that’s the case.

**Comment by audetto** [comment]
This is the best I found
```
    ImGui::PushItemFlag(ImGuiItemFlags_Disabled, true);
    if (ImGui::BeginCombo(label, text, ImGuiComboFlags_NoArrowButton))
    {
      ImGui::EndCombo();
    }
    ImGui::PushItemFlag(ImGuiItemFlags_Disabled, false);
```
Without the "push" it still show an empty dropdown rectangle.

**Comment by ocornut** [comment]
Why not just submitting a dummy `Selectable()` inside the combo with the same value as `text`?

Either way, closing this as answered :)

**Comment by audetto** [comment]
If you are saying to add `Selectable()` rather than using `Push Disabled`, then I don't like it because it still shows a dropdown (with the same text), but still a dropdown.

What I added above is the best I could find so far.
Yesterday I had the impression it asserted because there were no choices, but this has not happened today.
So, a bit big, but results is spot on.
