### ISSUE TITLE
How to snap scrollbar to the bottom?

### ISSUE THREAD

**Issue by MohammadGhasemi** [ocornut/imgui#3984]
When I add items to a window with scrollbar at runtime, I want the scrollbar snap to the bottom, so that the last item is completely visible.
I tried this first:
ImGui::SetScrollY(ImGui::GetScrollMaxY());
but there remains just a little space between the scrollbar and the furthest place it can go down.
As a workaround I currently use this:
ImGui::SetScrollY(ImGui::GetScrollMaxY() * 2);
This one works except for the first time that the scrollbar appears on the screen at which it doesn't completely snap too.
Thank you!

**Comment by ocornut** [comment]
Using GetScrollMaxY() should work, so please provide repro code as requested by the issue template.

**Comment by MohammadGhasemi** [comment]
Thank you, I solved my problem. In short it was because I was calling GetScrollMaxY() before the frame was rendered and the newly added Item was displayed. So GetScrollMaxY() had not been updated yet.
It was a little tricky for me to solve it. Do you think it is worthwhile to explain it completely for others, in case they encounter the same problem?

**Comment by ocornut** [comment]
Nice to hear! Any subsequent explanation may be useful to others.

`GetScrollMaxY()` in updated in `Begin()` based on contents from the previous frame.

Depending on the timing of your scroll request and the timing of your other changes of the window content, you may want to use `SetScrollY(GetScrollMaxY()` (use last frame contents height) or use `SetScrollHereY(1.0f)` _after all items submission_ (use current frame bottom-most position to infer scroll on next frame).

**Comment by MohammadGhasemi** [comment]
Thank you, I just want to summarize.
Problem: You want the scrollbar to snap to its bottom exactly when a new item is added to it. But you don't want it to be stuck there so the user can move it freely.
Solution: You need a bool to indicate if an item is added say: bool item_is_added;

when you choose to snap the scrollbar to the bottom when a new item is added,  Say you have a bool i You want it to snap only when a new item is added and also

**Comment by MohammadGhasemi** [comment]
Thank you, no that's just about it. You explained it.
