### ISSUE TITLE
Checkbox tick thickness seems to change unexpectedly...

### ISSUE THREAD

**Issue by Hoek67** [ocornut/imgui#3987]
Quite new at using this... very small window. Works fine except the checkbox when ticked changes thickness? depending on whether another window is drawn first.

This is the window when it's the only one. Note the thickness of the checkbox tick.

![image](https://user-images.githubusercontent.com/18671600/112915763-cd208500-914a-11eb-8ff5-6dd6e6dcfd52.png)

I noticed when I render a small window 1st... suddenly the tickbox is thick and more visible.

![image](https://user-images.githubusercontent.com/18671600/112915840-00631400-914b-11eb-8ca3-644a5f949439.png)

When the 2 windows are there makes no difference  which one has focus etc... the tick remains thick.

code...

   ImGui::Begin("Game"); 
   ImGui::Text("Score:%05d", gGame.m_score);
   ImGui::SameLine();
   ImGui::Text("Lives:%d", gGame.m_lives);
   ImGui::End(); 

   ImGui::Begin("Options");
   static int curr_item = 0;
   char* arr_items[] = { "2048*1024", "1024*512", "512*260", "None" };
   
   ImGui::Combo("Shadow Map", &gGame.opt_shadowmap_size, "2048\0001024\000512\000256\000None", 10);
   ImGui::Checkbox("Graphics: Alien Arms", &gGame.opt_alien_arms);    
   ImGui::ColorEdit3("Background Color", (float*)&gGame.opt_clear_color[0]);
   ImGui::Text("%.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
   ImGui::End();		

I tried to make sure it's not a feature etc, however the tick is almost not visible when on a lone window.

**Comment by Hoek67** [comment]
Looks like may have some "side-effect" code that's doing this. Will hunt it down.

**Comment by ocornut** [comment]
@Hoek67 Do you remember what caused this? It would be useful to know (I'd like to create a checklist for backends)
