### ISSUE TITLE
How to show "Wait..." message before running a lengthy process?

### ISSUE THREAD

**Issue by hunar4321** [ocornut/imgui#3989]
I'm using ImGui with Openframeworks. Inside the drawing loop, I'm running a lengthy process. I want to use ImGui to show a "Wait..." notification to the user while the lengthy process still runs... When using the following code example

if (ImGui::Button("Run")) {
     ImGui::Text("Wait...");
     lengthy_process();
}

The Wait message only shows after the lengthy_process() finishes already. I kinda understand this happens because the UI only updates after the next frame and the next frame only comes after the lengthy_process finishes() so my workaround is the following code snippet:

if(run == true){
    lengthy_process();
    run = false;
}
if (ImGui::Button("Run")) {
     run = true
     ImGui::Text("Wait...");
}

The above code works for this simple purpose but when I want to show the "Wait..." text inside a popup message, again it only shows the popup window after the lengthy_process() finishes!
I was wondering if there are any more convenient ways to do this especially if I want to show a an animated spinner to notify the user about the lengthy_process()? 

Thanks a lot in advance

**Comment by PathogenDavid** [comment]
No problem, glad I could help!
