### ISSUE TITLE
84e6fe4 breaks popup auto positioning

### ISSUE THREAD

**Issue by SlavicPotato** [ocornut/imgui#3991]
Popups seem to always appear at mouse coordinates, prior to 84e6fe4 ImGui would attempt to reposition them avoiding any vertical overflow past the viewport area.

I've observed this in a simple popup filled with menu items:
```
if (ImGui::BeginPopup("<id>")) 
{
    for (int i = 0; i < n; i++) {
         ImGui::MenuItem(....)
    }
    ImGui::EndPopup();
}
````

Screenshot shows a popup with ~40 menu items overflowing the bottom border of the viewport.

![enb2021_3_31_17_00_39](https://user-images.githubusercontent.com/66538381/113166507-210e9500-9243-11eb-9c70-ab90139f736b.png)

**Comment by ocornut** [comment]
Thanks, I confirm the change for #3982 broke that two days ago. Will be looking at it shortly.

**Comment by SlavicPotato** [comment]
Confirmed, thanks for the quick fix!
