### ISSUE TITLE
undefined reference to 'glGetProgramInfoLog'

### ISSUE THREAD

**Issue by ennorehling** [ocornut/imgui#3992]
**Version/Branch of Dear ImGui:**

Version: dear imgui, v1.83 WIP
Branch: master
Git Revision 45c45d250618ccdd573f5eef01390c6689077c46

**Back-end/Renderer/Compiler/OS**

Backend/Renderer: 
Android Studio

Back-ends: imgui_impl_android.cpp + imgui_impl_opengl3.cpp
Compiler: ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe
Operating System: Windows 10

**My Issue/Question:**

Hi, I'm trying to build an Android app with imgui, and I started out by copying example_android_opengl3 into a new Android Studio project. After fixing the CMakeLists.txt file so it finds the imgui sources, I still cannot build, but get this error:

    src/main/cpp/imgui/backends/imgui_impl_opengl3.cpp:523: undefined reference to 'glGetProgramInfoLog'

I haven't made any changes of my own at this point, just trying to get the example to work inside a new project.

**Screenshots/Video**

I wish I could get this far.

**Standalone, minimal, complete and verifiable example:** 

Like I said, I haven't actually written any code of my own yet. Just trying to get the included android example to work in Android Studio.

**Comment by ocornut** [comment]
cc @duddel

**Comment by ennorehling** [comment]
Could this have been a case of dueling SDKs and the general fragility of the Java/Android/NDK ecosystem?

I removed all the ANDROID_HOME and other environment variables that my Qt Creator installation made me set, rebooted and reopened Android Studio, which then complained about app/build.gradle asking for an NDK version 21.4.x that I don't have installed. I changed that to ndkVersion "21.3.6528147" (which was installed), and everything built from scratch and runs fine. 

Now Android Studio (installed yesterday) tells me it has updates it wants to install, and I wonder if that's going to cause everything to break again. Java was a mistake.

Sorry, I can no longer reproduce the problem. Issue can probably be closed, but I'll report back if it happens again.

**Comment by ennorehling** [comment]
It came back. I didn't change anything, came back to the project today with the intention of writing some code of my own, and it no longer builds. Same line, same error message. Is there anything more you need me to provide, now that the patient is showing symptoms again?

**Comment by duddel** [comment]
Hard to tell as it seems to occur occasionally.
Is there any chance you forgot to link against the GL ES library (**GLESv3**)? This is done in the original CMakeLists.txt: `target_link_libraries(...)`

Can you reproduce the error case with the unchanged provided Android example project?

Even though I don't think the NDK version is the problem:
In the SDK manager (launched from Android Studio), you can install multiple NDK versions: SDK Manager -> SDK Tools -> Checkbox "Show Package Details" -> select version under NDK (Side by Side)

**Comment by ennorehling** [comment]
My CMakeLists.txt is unchanged, and contains
```
target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
  android
  EGL
  GLESv3
  log
)
```
As for the "unchanged provided Android example project", I can build and run that. I should probably put together and upload my minimal example after all.

**Comment by ennorehling** [comment]
This is what's selected under SDK Tools / NDK:
![image](https://user-images.githubusercontent.com/629521/113324539-83d16080-9317-11eb-9e5c-4ea2f1c6abc4.png)

This is a ZIP with my project:
https://www.eressea.kn-bremen.de/downloads/ImGuiExample.zip

**Comment by duddel** [comment]
I checked your project and linking fails becuase your `minSdkVersion 14` (app/build.gradle) is "too old" and does not support GL ES 3. Setting minSdkVersion to 18 fixes it (but you should use a more recent version).

Your project is based on the original GL ES 2 JNI example. The Dear ImGui example is GL ES 3 so you might need to adjust a few things, based on the GL ES version you want to use.

**Comment by ennorehling** [comment]
Thanks, I'll try that. You're right, the first project I tried to build was the GL2 sample, and I may have gotten the two samples mixed up with each other when I decided to try Dear ImGui. These versions and config files are just too many, in too different places. Why did they make this so complicated?

**Comment by ennorehling** [comment]
Can confirm that changing those settings made it work again. Here's hoping it's going to last this time.
