### ISSUE TITLE
Setup codelite

### ISSUE THREAD

**Issue by Skupje** [ocornut/imgui#3999]
Hi,

I was trying this on linux, seems like its the library I want to use. Hard enough as it is for me to figure linux out. I was trying in the dark to get a good install going. Is it possible to share some installation instructions or a list of dependencies? I have the conan install but it wasn't working for me in codelite.

Kind regards,

**Comment by aiekick** [comment]
i think you will have better chance, to ask on a programming forum. your issue is not related to imgui, so not sure if you will have your answers

**Comment by elect86** [comment]
I'd strongly suggest you to use CLion

Simply clone imgui, `cd` in and create the following [file](https://gist.github.com/rokups/f771217b2d530d170db5cb1e08e9a8f4)

Then open a project from it and you'll have right away glfw opengl2, 3 and vulkan available
