### ISSUE TITLE
ImGui::Begin() / ImGui::End()

### ISSUE THREAD

**Issue by edselmalasig** [ocornut/imgui#400]
ImGui::Begin() and End() crashes my program. I am stuck with a widget that has a Debug title.

can you guys help me how to use these two properly?

I am using sdl_opengl_imgui project examples

**Comment by ocornut** [comment]
Can you clarify what is the crash?

**Comment by ocornut** [comment]
It is probably an assert in which case the comment should tell you what you have missed. Most likely you aren't calling NewFrame().

**Comment by edselmalasig** [comment]
window->DrawList->PushTextureID(g.Font->ContainerAtlas->TexID);
line 3600 if imgui.cpp

**Comment by ocornut** [comment]
You probably haven't called NewFrame()

**Comment by edselmalasig** [comment]
it did on line 265 of imgui_impl_dsl.cpp

**Comment by edselmalasig** [comment]
how do i hide debug widget?

**Comment by edselmalasig** [comment]
when i call on NewFrame() and then Begin() it does not let me interact with the widget

**Comment by edselmalasig** [comment]
were do i contribute to the project? financially?

**Comment by edselmalasig** [comment]
i wanna buy a license with updates

**Comment by ocornut** [comment]
You are doing something wrong, perhaps post a link to your program.
What do you mean by "it does not let me interact with the widget"?
The debug window appears if you call any widget before calling Begin/End (there is just an implicit "Debug" window that exist to facilitate that, but it is hidden if you never call any widget before Begin/End).

The main github page has links to Patreon and PayPal if you want to contribute financially. There's no "license with updates" per se, this is free-software and everyone gets defacto update, but financial contribution helps me spending more time on development and support.

**Comment by edselmalasig** [comment]
ok first thanks for creating this multiplatfrom cross library ui.
second thanks for making it opensource.
third thanks so much

**Comment by ocornut** [comment]
Thanks :)
Did you get it working for you?
