### ISSUE TITLE
LabelText resizes incorrectly with multiline text

### ISSUE THREAD

**Issue by ptxmac** [ocornut/imgui#4004]
**Version/Branch of Dear ImGui:**

Version: 1.8.3
Branch: master
Commit: 00d570e280533bca9cf6e5652d0f2eb131d032e7

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: clang-1200.0.32.29
Operating System: macOS 11.2.3

**My Issue/Question:**

`LabelText` only resize its own height based on the label. If used with a value containing line breaks these will be clipped. (See 3rd row in the screenshot.

I would expect the sizing to be based on the biggest of the label and value texts

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/56919/113481134-1bf65380-9498-11eb-8028-35e9df9f3fc6.png)

**Standalone, minimal, complete and verifiable example:** 
```cpp
// Put this in any example program
ImGui::Begin("Multiline LabelText");
    ImGui::Separator();
    ImGui::LabelText("Single line label", "Single line text");
    ImGui::Separator();
    ImGui::LabelText("Multi\n line\n label", "Single line text");
    ImGui::Separator();
    ImGui::LabelText("Single line label", "Multi\n line\n text");
    ImGui::Separator();
    ImGui::LabelText("Single line label", "Single line text");
    ImGui::Separator();
ImGui::End();
```

**Comment by ocornut** [comment]
Should be be fixed by c283a1d.
I also noticed from your picture that the second case is vertically centered with is inconsistent with other widgets so fixed that as well. Thank you!

![image](https://user-images.githubusercontent.com/8225057/113747426-a98baa80-9707-11eb-80b2-6885447e7b8f.png)
