### ISSUE TITLE
"Trail" on SliderFloat

### ISSUE THREAD

**Issue by Death-Z** [ocornut/imgui#4006]
ImGui Version: v1.75
Using DirectX11
Compiler: VS 2019
OS: Windows

Recently I saw a panel created by ImGui and this panel had a SliderFloat, only that the Slider left a "trail", not only where the value moves, I was wondering how I could do that too, Is that a property?

What I want to do:
![What I want to do](https://user-images.githubusercontent.com/52619816/113486989-c9af3580-948b-11eb-9463-8fc72f9a7330.png)

My currently SliderFloat:
![My currently SliderFloat](https://user-images.githubusercontent.com/52619816/113487009-eea3a880-948b-11eb-9b64-4e7c09c1715d.png)

**Comment by PathogenDavid** [comment]
I don't believe there's a way to get that appearance without either creating your own slider widget or modifying Dear ImGui.

I was able to get a slider that looked similar to this with these quick and dirty changes:

```diff
diff --git a/imgui_widgets.cpp b/imgui_widgets.cpp
index d2a4d1dc..66bb8282 100644
--- a/imgui_widgets.cpp
+++ b/imgui_widgets.cpp
@@ -2695,8 +2695,8 @@ bool ImGui::SliderBehaviorT(const ImRect& bb, ImGuiID id, ImGuiDataType data_typ
         grab_sz = ImMax((float)(slider_sz / (v_range + 1)), style.GrabMinSize);  // For integer sliders: if possible have the grab size represent 1 unit
     grab_sz = ImMin(grab_sz, slider_sz);
     const float slider_usable_sz = slider_sz - grab_sz;
-    const float slider_usable_pos_min = bb.Min[axis] + grab_padding + grab_sz * 0.5f;
-    const float slider_usable_pos_max = bb.Max[axis] - grab_padding - grab_sz * 0.5f;
+    const float slider_usable_pos_min = bb.Min[axis];
+    const float slider_usable_pos_max = bb.Max[axis];
 
     float logarithmic_zero_epsilon = 0.0f; // Only valid when is_logarithmic is true
     float zero_deadzone_halfsize = 0.0f; // Only valid when is_logarithmic is true
@@ -2946,7 +2946,7 @@ bool ImGui::SliderScalar(const char* label, ImGuiDataType data_type, void* p_dat
 
     // Render grab
     if (grab_bb.Max.x > grab_bb.Min.x)
-        window->DrawList->AddRectFilled(grab_bb.Min, grab_bb.Max, GetColorU32(g.ActiveId == id ? ImGuiCol_SliderGrabActive : ImGuiCol_SliderGrab), style.GrabRounding);
+        window->DrawList->AddRectFilled(frame_bb.Min, ImVec2((grab_bb.Min.x + grab_bb.Max.x) / 2, frame_bb.Max.y), GetColorU32(g.ActiveId == id ? ImGuiCol_SliderGrabActive : ImGuiCol_SliderGrab));
 
     // Display value using user-provided display format so user can add prefix/suffix/decorations to the value.
     char value_buf[64];
```

![image](https://user-images.githubusercontent.com/278957/113489633-f6af1880-948a-11eb-827b-6541cf826f87.png)

(I only briefly tested this, so I make no claims it doesn't have unintended quirks. It definitely doesn't handle vertical sliders correctly and you can't selectively enable the feature.)

Obviously modifying `imgui_widgets.cpp` isn't super ideal, but you could copy+paste the relevant functions for your own use.

**Comment by Death-Z** [comment]
This solved my problem :), I will probably make a version of this so that I can have other SliderFloat without this effect, but thanks anyway!

**Comment by ocornut** [comment]
I think we should aim to rework some of the internals to at least make the changes in `SliderBehavior()/SliderBehaviorT<>()` unecessary, and down the line try to simplify `SliderScalar()` so it can be less unwieldy to copy and paste. This has been something we experimented with (writing totally custom widgets relying on low-level component) but haven't acted on internals yet.

**Comment by ocornut** [comment]
Note that this is close to what is covered #3599 (which I think we will work to adopt) and I think when I work on adopting #3599 I'll try to cleanup that reliance on grab size and remove the hardcoded padding too.
