### ISSUE TITLE
InputTextWithHint crashed when docked

### ISSUE THREAD

**Issue by altschuler** [ocornut/imgui#4008]
When using docking, and a frame with the `InputTextWithHint` is docked (only when it's docked!), the program crashed when the input is clicked. Specifically this assert fails: https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp#L627. `InputText` (without hint) works fine.

```
static char name_input2[100] = {};
ImGui::InputTextWithHint("", "Name", name_input2, sizeof(name_input2));
```

Results in 

```
[...]/imgui/imgui_widgets.cpp:627: bool ImGui::ButtonBehavior(const ImRect&, ImGuiID, bool*, bool*, ImGuiButtonFlags): Assertion `mouse_button >= 0 && mouse_button < ImGuiMouseButton_COUNT' failed.
```

System info:
```
Dear ImGui 1.83 WIP (18203)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=9
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.DisplaySize: 1091.00,1046.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 4.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Comment by ocornut** [comment]
Your empty ID is invalid.
Please read the FAQ.

**Comment by altschuler** [comment]
> 
> Your empty ID is invalid. Please read the FAQ.

Right, works with an id. Was confused because it works outside docking (although still wrong I guess). Thanks for such a speedy reply!

**Comment by ocornut** [comment]
The issue is that using "" in the root of a window conflict with the root id of the window which is used by the docking mechanism, creating those weird to understand bug. We have a task in the todo list to rework docking to not use this root id, but it would only be a maneuver to change the way the issue would manifest.
