### ISSUE TITLE
ImGui::Render(); segfaults

### ISSUE THREAD

**Issue by edselmalasig** [ocornut/imgui#401]
imgui.cpp::2448	            g.IO.RenderDrawListsFn(&g.RenderDrawData);
(gdb) n

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2aa45e0 in ?? () from /usr/lib/nvidia-346/libnvidia-glcore.so.346.96
(gdb) n

**Comment by ocornut** [comment]
Which imgui_impl* file are you using?
Could you compile your program with Debug options and find what's crashing? 
Can you post your program source somewhere?

**Comment by edselmalasig** [comment]
I am using SDL OpenGL and ImGui. When I try to use gl version 3.2 using sdl_opengl_example base code with modification so that i can use vbo to load obj models it crashes when i render ImGui::Render() line.

now i pin point the problem.

When i do:

	glGenVertexArrays(1, &VertexArrayID);
	glBindVertexArray(VertexArrayID);

it segfaults. but if i disable them it runs. the ui doesnt show though im still figuring it out
im using
imgui_impl_sdl.cpp

**Comment by ocornut** [comment]
Thanks, it's possible that using old GL2 calls along with new ones confuse the driver.

Someone created a SDL+GL3 examples by mixing both existing examples:
https://github.com/ocornut/imgui/pull/356
I haven't merged the code yet, buf perhaps if you grab the files from there perhaps it would work?

**Comment by edselmalasig** [comment]
actually i got it working. i cleaned up the code and everything but somehow the object and the ui doesnt show together on sdl. i have to disable either the object rendering or the ui rendering to show.
if both renderings are enabled in the code the ui doesnt show up.

**Comment by edselmalasig** [comment]
i fix the previous problem how do i close this

**Comment by paulsapps** [comment]
you can't mix SDL2 render target and OpenGL if thats what you where doing
