### ISSUE TITLE
Horizontal scrolling not working on macOS because of shift handling

### ISSUE THREAD

**Issue by ptxmac** [ocornut/imgui#4010]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfwcpp
Compiler: clang
Operating System: macOS 11.2.3

**My Issue/Question:**

Imgui has a feature to allow the shift key to flip between horizontal/vertical scrolling: https://github.com/ocornut/imgui/blob/master/imgui.cpp#L3757

Unfortunately, this conflicts with macOS's built-in feature which does the same.

When holding down shift while scrolling on macOS, the system sends horizontal events, but imgui also detects the shift key, and only look at the vertical events - effectively disabling horizontal scrolling!

**Standalone, minimal, complete and verifiable example:**

Run any example (tested with sdl and glfw) that contains a horizontal scrollbar (e.g. `demo menu / examples / log`)

**Suggested fix**

Add an option to disable the shift scrolling override feature

**Comment by ocornut** [comment]
Pushed a fix for this (92b7b1f72bc830cede5da5efe064c4f9e1a21838, slightly different from 2b0090c90fd32db8d4122772c764a07e8228ee33 initially pushed).

I tried a magic mouse (with support for swiping on both axis) and Shift didn't affect either, so I presume it only affect something on mouse that only have a single axis.
I installed drivers to try a magic mouse on my Windows and Shift altered the vertical wheel into horizontal scroll, but didn't alter horizontal wheel into vertical scroll.

Should be fixed.

We'll be looking at #3795 next
