### ISSUE TITLE
Loading Image with `glTexImage2D` and display single channel

### ISSUE THREAD

**Issue by xarthurx** [ocornut/imgui#4017]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.82
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: `imgui` inside `libigl`
Compiler: MSVC 
Operating System: Windows 10

**My Issue/Question:**

Following the image loading instructions here:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

I can successfully load image to my ImGui viewer.
However, when modifying the code to load only one channel of the image:

` glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data);`

**working** (showing red):
` glTexImage2D(GL_TEXTURE_2D, 0, GL_RED, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data);`

**not working** (try to show blue / green):
` glTexImage2D(GL_TEXTURE_2D, 0, GL_GREEN, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data);`

I'm not sure if this is the right place to ask, but after searching online for a while, I cannot find an answer to a similar question.

I'm guessing this is related to the OpenGL layer underneath?

**Screenshots/Video**

RGB:
![image](https://user-images.githubusercontent.com/1921878/113887134-87eef980-97c1-11eb-825e-97635c45c94e.png)

Red:
![image](https://user-images.githubusercontent.com/1921878/113887332-b2d94d80-97c1-11eb-9a75-4e26b0eaab6b.png)

Blue/Gree:
Showing nothing.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

**Only the above line is changed from the example.**

**Comment by ocornut** [comment]
> I'm guessing this is related to the OpenGL layer underneath?

Yes.

You probably would need a custom shader or render setup, which you can achieve by using `ImDrawList::AddCallback()` and use custom callback to alter the OpenGL state machine.

This isn't really a problem at the scope of Dear ImGui.

**Comment by xarthurx** [comment]
OK, thank you for the quick reply.
Closing the issue.
