### ISSUE TITLE
inputtext disappears focus?

### ISSUE THREAD

**Issue by aFakeCmd** [ocornut/imgui#4018]
**Version/Branch of Dear ImGui:**
35b1148
Version: 1.82
Branch: release

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Operating System: win 10 x64

**My Issue/Question:**

This behavior related to my inputtext, I guess the problem is in the WndProc hook. how can i fix this?

**Video**

https://user-images.githubusercontent.com/60480464/113918300-72eb8800-980c-11eb-8d60-b204af0a01af.mp4

**Code**
```
LRESULT WINAPI wProc(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
{
	if (openExample && wParam == VK_RETURN) return false;
	
	if (openExample && ImGui_ImplWin32_WndProcHandler(hWnd, Msg, wParam, lParam))
		return true;		
	return orig_wProc(hWnd, Msg, wParam, lParam);
}
```

**Comment by ocornut** [comment]
This is not how you are supposed to call `ImGui_ImplWin32_WndProcHandler()`. 
You should always call it as we need to track all events.

Instead, whichever flag you are using to disable your UI (e.g. `bool openExample`) should be used to control whether you submit your dear imgui windows.
