### ISSUE TITLE
Depth test with imgui primitives

### ISSUE THREAD

**Issue by Luke-Filewalker** [ocornut/imgui#4022]
Is it possible to only draw a line or text if it is visible (if it passes the depth test of the image it is drawn into)?

Example: I want to mark all the light sources in my scene with a simple filled point, but if a light source is occluded imgui should draw nothing.

Something like
Imgui::ActivateDepthTest
Imgui::DrawPoint (with z value)
Imgui::DeactivateDepthTest

**Comment by ocornut** [comment]
You can use AddCallback() on a given ImDrawList:: to register functions to be run during rendering and use callbacks to alter your render state (e.g. enable depth testing + enable a custom shader with uniform to write a specific Z value into the framebuffer). This will be dependent on your rendering backend so you'll need to be familiar with your graphics stack to do it, and will require a bit of plumbing.

**Comment by Luke-Filewalker** [comment]
I can see how this can works for openGL but how does it work with Vulkan?

**Comment by ocornut** [comment]
That’s a Vulkan question not a Dear ImGui question at this point.

**Comment by Luke-Filewalker** [comment]
I think it is a dear imgui question because with opengl you have a global state machine while with vulkan I would need to get to the renderpass used in imgui to activate a depth test.

**Comment by ocornut** [comment]
You would probably need to modify the Vulkan backend to export some state/variables indeed, but the expectation if you are using OpenGL and Vulkan is you would be using your own rendering layer anyway. Either way for the purpose of doing this rendering alteration it is out of scope of backends.
