### ISSUE TITLE
Ctrl-Tab not working

### ISSUE THREAD

**Issue by gvanem** [ocornut/imgui#4023]
Not sure it's me and my build that's to blame? 
But I fail to get `Ctrl-Tab` working in e.g. `example_glfw_opengl2.exe` on Windows-10.

When having many child-windows in this nice demo, it would be handy to `Ctrl-Tab` away from the Main-window or Debugger
window. But I've to resize one to  enable a click on another. I'd assume a `Ctrl-Tab`  should do that as in most MDI programs on Windows.

**Version/Branch:** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;From today's Git/master.
**Version:** &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1.8.3 WIP
**Back-end/Compiler**: &nbsp;glfw/OpenGL2/MSVC-2019 (x86).

But the combinations of backend, whatever does not seems to matter. Same *problem* in `example_sdl_directx11.exe`,
`example_win32_directx11.exe` etc.

I saw just a few [`CHANGELOG.txt`](docs/CHANGELOG.txt) items on `Ctrl-Tab` and some in [`TODO.txt`](docs/TODO.txt).
I hope this feature wasn't disabled (?)

**Comment by PathogenDavid** [comment]
> it would be handy to `Ctrl-Tab` away from the Main-window or Debugger window

Are you sure you aren't thinking of Alt+Tab?

Ctl+Tab for switching between individual Dear ImGui windows is supported in [the experimental docking branch](https://github.com/ocornut/imgui/tree/docking).

**Comment by ocornut** [comment]
Ctrl+Tab works on all branches including master but requires keyboard navigation to be enabled in the configuration flags.

**Comment by PathogenDavid** [comment]
Ah, didn't realize that was tied to keyboard navigation or that it was off by default in master. Thanks, Omar!

**Comment by gvanem** [comment]
> Are you sure you aren't thinking of Alt+Tab?

David, no. I meant `Ctrl-Tab`. And duh, I also know what `Alt-Tab` is.

> For example: uncomment this line to get it in example_glfw_opengl2

Thanks. I'll try that.

**Comment by gvanem** [comment]
>  but requires keyboard navigation to be enabled in the configuration flags.

Omar. Why is this disabled by default?

**Comment by ocornut** [comment]
> Omar. Why is this disabled by default?

Keyboard navigation does a lots more things than that and some of them can easily with how applications are using keyboard inputs. The master _NavEnable config flag is effectively a bit inconsistent since Tabbing between fields existed before Navigation appearing and is always always.

- I often thought that Ctrl+Tab in particular could be "always enabled" and moved out of _NavEnable flag.
- Perhaps should introduce more flags to opt-in/opt-out certain navigation features.

**Comment by ocornut** [comment]
CTRL+Tab has now been promoted and is always available regardless of using the `_NavEnableKeyboard`.
Commit: 8ce23b3ccd5b9338002f58679a3fc53559d3280b

As we evolve toward #3092 it is possible the configuration flags will evolve as well.

Note that some features such as moving/resizing window with keyboard are currently not available without `__NavEnableKeyboard` but should be shortly, currently addressing this too.
