### ISSUE TITLE
What‘s the substitute of ImGui::PiePopupSelectMenu in v1.80

### ISSUE THREAD

**Issue by LiuYinCarl** [ocornut/imgui#4024]
In v1.78, I find an API `ImGui::PiePopupSelectMenu` in file `imgui.h`, but I can't find it in v1.80. I looked up in the `imgui/docs/CHANGELOG.txt`, but can not find any information about it? so, is there any to come true `ImGui::PiePopupSelectMenu`'s effect in v1.80? thanks.

**Comment by PathogenDavid** [comment]
I don't believe `PiePopupSelectMenu` was ever actually part of Dear ImGui. It was a prototype Omar shared in https://github.com/ocornut/imgui/issues/434

**Comment by LiuYinCarl** [comment]
sorry, it's my mistake, my colleague add `PiePopupSelectMenu` into `imgui.h` which make me think it's an API of Dear ImGui. thank you.

**Comment by ocornut** [comment]
> my colleague add PiePopupSelectMenu into imgui.h 

You should never modify imgui files for this.
You can add the new functions in your own files, you can even add your new functions into the same `ImGui::` namespace.
