### ISSUE TITLE
Building the FontAtlas makes the hooked Application lag

### ISSUE THREAD

**Issue by Bones6924** [ocornut/imgui#4026]
Hello! I have an issue with loading Fonts.
My FPS on the hooked Application dropped from stable 60 to >5 FPS, only when i am loading custom Fonts.
Loading it without any custom loaded Font lets FPS stay stable.

Here is the code i am using:
```	ImGuiIO& io = ImGui::GetIO();
	io.Fonts->AddFontFromFileTTF("c:\\windows\\fonts\\arial.ttf", 18.0f);
	io.Fonts->Build();
```
I am using ImGui v1.82

**Comment by ocornut** [comment]
You should load the fonts once and not every frame.
