### ISSUE TITLE
How is this horizontal button working ? 

### ISSUE THREAD

**Issue by eetoa** [ocornut/imgui#4032]
**Version/Branch of Dear ImGui:**

Version: 1.79
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Compiler: vs2019
Operating System: windows 10

**My Issue/Question:**

This code implement a horizontal scrolling, But I don't understand how it works----
At imgui_demo.cpp line 2753:
```c++
float scroll_x = ImGui::GetScrollX();
float scroll_max_x = ImGui::GetScrollMaxX();
ImGui::EndChild();
ImGui::PopStyleVar(2);
float scroll_x_delta = 0.0f;
ImGui::SmallButton("<<");
if (ImGui::IsItemActive())
    scroll_x_delta = -ImGui::GetIO().DeltaTime * 1000.0f;
ImGui::SameLine();
ImGui::Text("Scroll from code"); ImGui::SameLine();
ImGui::SmallButton(">>");
if (ImGui::IsItemActive())
    scroll_x_delta = +ImGui::GetIO().DeltaTime * 1000.0f;
ImGui::SameLine();
ImGui::Text("%.0f/%.0f", scroll_x, scroll_max_x);
```
I don't understand how if I click the "<<" or ">>" button the text after these arrows change.

**Screenshots/Video**
![github](https://user-images.githubusercontent.com/25720572/114269970-60579580-9a3c-11eb-80cc-abe4e1a043b7.jpg)

___
By the way, I want to implement a  UI function with two `Imgui::smallbutton` like above. This function can replace the checkbox since whatever I click the left button or the right one, the relative value will change once.
My solution is :

Define a button class. Each button object can draw itself. What I have to do is change the value of the button I click.
```c++
class ArrowButtonLR
{
public:
	int id;
	bool idx;
	std::string name;
	MemuItemType type;
	ArrowButtonLR(){}
	ArrowButtonLR(int id, int idx, MemuItemType type, std::string name)
	{
		this->id = id;
		this->idx = idx;
		this->type = type;
		this->name = name;
	}
	void Draw();
};

// the draw function
void ArrowButtonLR::Draw()
{
	if (ImGui::SmallButton("<<"))
	{
		this->idx = !this->idx;
	}
	ImGui::SameLine();
	this->idx ? ImGui::TextColored(GREEN, "On") : ImGui::TextColored(RED, "Off");
	ImGui::SameLine();
	if (ImGui::SmallButton(">>"))
	{
		this->idx = !this->idx;
	}
}
```

Define a container which stored all these buttons.
```c++
std::vector<ArrowButtonLR*> container;

void MenuInit()
{
	ArrowButtonLR* button1 = new ArrowButtonLR(0, false, CHECK_BOX, "BUTTON1");
	ArrowButtonLR* button2 = new ArrowButtonLR(1, false, CHECK_BOX, "BUTTON2");
	ArrowButtonLR* button3 = new ArrowButtonLR(2, false, CHECK_BOX, "BUTTON3");
	container.push_back(button1);
	container.push_back(button2);
	container.push_back(button3);
}
```

And in render flow:
```c++
	for (int i = 0; i < container.size(); i++)
	{
		ImGui::Button("", { 10, 10 });
		ImGui::SameLine();
		container[i]->Draw();
	}
```
But, unfortunately, it doesn't work. If I define more than one button, only 1 works fine but the others can't get value updated.
I debugged this program, and it's indeed generated three objects with different addresses in memory.

![github1](https://user-images.githubusercontent.com/25720572/114270292-1f608080-9a3e-11eb-957a-e6382f538518.jpg)

Can I get some explanations?

**Comment by phicore** [comment]
It is a well-known fact that people open more easily an issue than they are willing to read the docs, despite in the present case it would have been much shorter than publishing all those details

hint: label=ID

**Comment by ocornut** [comment]
1. About empty id: Read the FAQ
2. In that demo code, the delta is applied lower in the code.
