### ISSUE TITLE
ImGui DirectX9_Init Error

### ISSUE THREAD

**Issue by Voidlessxyz** [ocornut/imgui#4035]
Hello, so after debugging and narrowing down I am getting an error coming from bool ImGui_ImplDX9_Init(IDirect3DDevice9*device)

The error comes exactly from this :

bool ImGui_ImplDX9_Init(IDirect3DDevice9* device)
{
    // Setup backend capabilities flags
    ImGuiIO& io = ImGui::GetIO();
    io.BackendRendererName = "imgui_impl_dx9";
    io.BackendFlags |= ImGuiBackendFlags_RendererHasVtxOffset;  // We can honor the ImDrawCmd::VtxOffset field, allowing for large meshes.

    g_pd3dDevice = device;
    g_pd3dDevice->AddRef(); <--------- Here Error: Exception thrown: read access violation.**g_pd3dDevice** was nullptr.
    return true;
}

I really dont know what is causing it

**Comment by ocornut** [comment]
You are passing a NULL reference to the tunction.
