### ISSUE TITLE
Problem with rendering ImGui

### ISSUE THREAD

**Issue by GZBland** [ocornut/imgui#4039]
I have a problem with rendering ImGui, I am not able to remove these black tips on ImGui.

![unknown](https://user-images.githubusercontent.com/55111228/114480182-6bdfc380-9bd8-11eb-90e2-fb24b9aaae3b.png)

**Comment by ocornut** [comment]
Set WindowRounding to 0.0f in your style if you want to fit a dear imgui window into a rectangular Platform Window.
