### ISSUE TITLE
[Solved]Can't catch the Chinese UTF-8 IME in Deepin OS

### ISSUE THREAD

**Issue by rookieWanZ** [ocornut/imgui#4044]
Build project in linux Deepin system v20.2
Build the project "examples/example_glfw_opengl3" 
The Widget text "UTF-8" demo using "ImGui::ShowDemoWindow" can't catch the input from the IME when input any Char.
It can copy and paste in the textbox by CTRL+CV.
And I change lots of ime layout include the "fcitx", nothing has effect.

`io.InputQueueCharacters.Size` is always zero when input by the ime

Give me some tips to solve this issue, Thank you!

**Comment by CallumDev** [comment]
glfw on Linux does not support IME as of yet. You will need to use SDL2 to input Chinese.

GLFW不能用输入法。如果要写中文的话你应该用SDL2。

**Comment by rookieWanZ** [comment]
Ok. I will try this solution.  thank u very much. 174557505 ***@***.*** Signature is customized by Netease Mail Master On 04/19/2021 21:32, Callum wrote: glfw on Linux does not support IME as of yet. You will need to use SDL2 to input Chinese. GLFW不能用输入法。如果要写中文的话你应该用SDL2。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rookieWanZ** [comment]
> glfw on Linux does not support IME as of yet. You will need to use SDL2 to input Chinese.
> 
> GLFW在Linux不能用输入法。如果要写中文的话你应该用SDL2。

Thanks again for the resolution and the bi-language reply!
The ime works for the example sdl_opengl2!!!

**Comment by ocornut** [comment]
As far as I know, unfortunately SDL breaks the IME under Windows :( so today there’s not a perfect cross platform solutions. I hope SDL fixes it or GLFW add fuller IME support.

**Comment by rookieWanZ** [comment]
Oh, sorry, I forget the detail that if I compile with makefile after antoreconf and configure.
It reminds me losing "libld.a".
So I remove the -ld in the Makefile by hand and compile it agian it passed but has huge size.
And It works normal and I have checked the data by the sqlitestudio3.3 except the size. 


`
[complie.log](https://github.com/ocornut/imgui/files/7028174/complie.log)
`
