### ISSUE TITLE
ImGui Not Showing

### ISSUE THREAD

**Issue by Voidlessxyz** [ocornut/imgui#4049]
Hello so I have created an Overlay with DirectX9 and I am trying to render ImGui onto it but it does not show up, I get no errors it just does not show. This is the code :

	if (GetAsyncKeyState(VK_INSERT)) {

		ImGui::CreateContext();
		ImGui_ImplWin32_Init(hWnd);
		ImGui_ImplDX9_Init(pDevice);

		ImGui_ImplDX9_NewFrame();
		ImGui_ImplWin32_NewFrame();
		ImGui::NewFrame();

		ImGui::Begin("Test");
		ImGui::End();

		ImGui::EndFrame();

		ImGui_ImplDX9_Shutdown();
		ImGui_ImplWin32_Shutdown();
		ImGui::DestroyContext();

	}

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. Closing, blocked.
