### ISSUE TITLE
Unnecessary includes

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#405]
There are some includes in imgui.h that are not necessary. Some of them are only necessary for the demo and some of them can be included just in cpp

**Comment by ocornut** [comment]
Which ones?
It's sometimes a bit tricky because depending on the os/system different includes may be needed.

**Comment by nem0** [comment]
stdlib.h can be just in demo
---
stdarg.h and stddef.h are included through some other std header on my platform, however it is not forced by standard

**Comment by ocornut** [comment]
If I remove stdlib.h from imgui.h with VS2010 i get errors with qsort() and atoi().
If I remove stdarg.h I get errors on va_start/va_end.

I recall adding stddef.h for ptrdiff_t for some platforms but I can't recall which.

**Comment by nem0** [comment]
if you put stdlib.h in imgui.cpp, there should be no error, since it is only used there

**Comment by ocornut** [comment]
Trying that now. We'll see if it it impact some platforms but it looks about right. Thanks!
