### ISSUE TITLE
Compiled executable will abort during startup with code 0xc0000139 after backend inclusion

### ISSUE THREAD

**Issue by sigmasoldi3r** [ocornut/imgui#4051]
**Version/Branch of Dear ImGui:**

Version: 1.82
Branch: master (conan center)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp 
Compiler: GCC 9.2.0 (Mingw64)
Operating System: Windows 10

**My Issue/Question:**

I've managed to compile and link both the library and the backend, but produces an executable that immediately stops with code `0xc0000139`. Removing the code related to ImGUI fixes the problem.

If I exclude the backend source code from compile step, the executable runs normally again.

Note: In order to link, I had to add `winmm` and `imm32` libraries to the linker, might be related?

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/13834659/115109289-270bb200-9f75-11eb-9dde-06eef6caf257.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
#include "VGUIActor.hpp"
#include <imgui.h>

float speed;
bool someBoolean;

void VGUIActor::update(const double &delta)
{
  ImGui::Begin("MyWindow");
  ImGui::Checkbox("Boolean property", &someBoolean);
  if (ImGui::Button("Reset Speed"))
  {
    // This code is executed when the user clicks the button
    speed = 0;
  }
  ImGui::SliderFloat("Speed", &speed, 0.0f, 10.0f);
  ImGui::End();
}
```

Aside there's the initialization and tear-down steps:
```cpp
int Engine::start(Game &game, int argc, char *argv[])
{
  auto title = game.getTitle();
  auto [w, h] = game.getScreenSize();
  window = SDL_CreateWindow(title.c_str(), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, w, h, SDL_WINDOW_OPENGL);
  context = SDL_GL_CreateContext(window);
  glewInit();
  std::vector<std::string> args(argc);
  for (int i = 0; i < argc; i++)
  {
    args[i] = std::string(argv[i]);
  }
  IMGUI_CHECKVERSION();
  ImGui::CreateContext();
  ImGui::StyleColorsDark();
  ImGui_ImplSDL2_InitForOpenGL(window, context);
  ImGui_ImplOpenGL3_Init();
  game.start(args);
  loop(game);
  ImGui_ImplOpenGL3_Shutdown();
  ImGui_ImplSDL2_Shutdown();
  ImGui::DestroyContext();
  SDL_GL_DeleteContext(context);
  SDL_DestroyWindow(window);
  SDL_Quit();
  return 0;
}
```
Consider this function a `int main(...)` wrapper, the function is static and the struct in both cases is trivial.

**Comment by PathogenDavid** [comment]
Can you build and run the official [`example_sdl_opengl3`](https://github.com/ocornut/imgui/blob/936f53229db4d45b445a3c26795718523262654e/examples/example_sdl_opengl3/Makefile) with MinGW?

`0xc0000139` means that a DLL dependency wasn't found. (Or the DLL was found but it's missing an expected export.) If you launch the process outside of GDB you should get a more helpful message from Windows telling you what the dependency was. (I think you can also check in Event Viewer under Windows Logs > Application)

If that doesn't give you something more useful, try checking your executable with [Dependencies](https://github.com/lucasg/Dependencies). You'll get an error icon on the left for anything which couldn't be loaded:

![image](https://user-images.githubusercontent.com/278957/115113173-97eba380-9f4e-11eb-9115-ae2bf5fa3ed1.png)

**Comment by sigmasoldi3r** [comment]
Dear lord... it was missing `SDL.dll`... but how could I open windows and render graphics before if that was the problem? that puzzles me the hell out... Maybe some SDL calls are just inlined OpenGL calls?

I mean, my program had calls like:
```c++
  window = SDL_CreateWindow(title.c_str(), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, w, h, SDL_WINDOW_OPENGL);
  context = SDL_GL_CreateContext(window);
  glewInit();
```
That's why I didn't even bother of thinking about that...

Anyway, it pretty solved the problem. Thanks ❤️ !
![image](https://user-images.githubusercontent.com/13834659/115115067-ac518f80-9f92-11eb-9dcb-d1ea7ce84bb2.png)

**Comment by PathogenDavid** [comment]
No problem!

The reason might be this bit:

> (Or the DLL was found but it's missing an expected export.)

It may be there's an older version of SDL somewhere on your environment PATH that got picked up. Calling older functions might work, but newer ones would cause issues like you saw. You can check by opening a command prompt and running `where SDL2.dll`.
