### ISSUE TITLE
Second PopupModal not showing

### ISSUE THREAD

**Issue by Lester702** [ocornut/imgui#4057]
**Version/Branch of Dear ImGui:**

Version: 1.80
Branch: Master
**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.h + imgui_impl_dx9.h _(or specify if using a custom engine/back-end)_
Compiler: Visual Studio 2019 _(if the question is related to building or platform specific features)_
Operating System: Windows 10

**My Issue/Question:**

I have a PopupModal for a dealership menu and when the player purchases a car I want to have another PopupModal show alerting the player that they have successfully purchased a vehicle. I used some code from "imgui_demo.cpp", but I haven't been getting it to work

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
            if (ImGui::Button("Dealership"))
                ImGui::OpenPopup("Dealership");
            // Always center this window when appearing
            ImVec2 center = ImGui::GetMainViewport()->GetCenter();

            ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));

            if (ImGui::BeginPopupModal("Dealership", NULL, ImGuiWindowFlags_AlwaysAutoResize))
            {
                ImGui::Text("Welcome to Rob's Dealership");
                ImGui::Separator();

                ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0, 0));
                ImGui::Text("These are the vehicles in store:");
                ImGui::Text("Model: %s, Color: %s, Price: %i", Slot1.Model, Slot1.Color, Slot1.Price);
                ImGui::Checkbox("Buy###BuyCivic", &civicBuy);

                if (civicBuy == true, PlayerBalance >= 12000)
                {
                    PlayerBalance = PlayerBalance - 12000;
                    std::cout << "Yes";
                    civicBuy = false;
                    PlayerOwnCar = true;

                }
                if (ImGui::BeginPopupModal("Alert", &civicBuy))
                {
                    ImGui::Text("Test");
                    if (ImGui::Button("Close"))
                        ImGui::CloseCurrentPopup();
                    ImGui::EndPopup();
                }
```

**Comment by ocornut** [comment]
There's no code here attempting to open "Alert" popup. `OpenPopup()` needs to be called.

**Comment by Lester702** [comment]
I have no idea why I can't figure out how to get this to open, but I tried a few different ways to get the "Alert" popup to open, but I still haven't been able to
```             
                if (civicBuy == true &&PlayerBalance >= 12000)
                {
                    civicBuy = false;
                    PlayerBalance = PlayerBalance - 12000;
                    PlayerOwnCar = true;

                    ImGui::OpenPopup("Alert");

                }
                if (ImGui::BeginPopupModal("Alert", &civicBuy))
                {
                    ImGui::Text("Test");
                    if (ImGui::Button("Close"))
                        ImGui::CloseCurrentPopup();
                    ImGui::EndPopup();
                }
```
This is one way I tried

**Comment by PathogenDavid** [comment]
I'm not sure what's wrong with your current code without more context, but maybe it will help to see an example which works:

```cpp
// GH-4057
ImGui::Begin("GH-4057 Test");
if (ImGui::Button("Show modal 1"))
{
    ImGui::OpenPopup("Modal1");
}

if (ImGui::BeginPopupModal("Modal1"))
{
    if (ImGui::Button("Show modal 2"))
    {
        ImGui::OpenPopup("Modal2");
    }

    if (ImGui::Button("Close"))
    {
        ImGui::CloseCurrentPopup();
    }

    if (ImGui::BeginPopupModal("Modal2"))
    {
        if (ImGui::Button("Close"))
        {
            ImGui::CloseCurrentPopup();
        }

        ImGui::EndPopup();
    }

    ImGui::EndPopup();
}

ImGui::End();
```

![image](https://user-images.githubusercontent.com/278957/115224862-09545f00-a0d3-11eb-85c1-b37b407a60a6.png)

Keep in mind that internally Dear ImGui's [IDs are part of a stack](https://github.com/ocornut/imgui/blob/936f53229db4d45b445a3c26795718523262654e/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it). The relationship between `OpenPopup` and `BeginPopupModal` is affected by this.

<details>
<summary>For example, the variation of this code listed below (click to expand) doesn't work because <code>Modal2</code> has a full ID of [<code>GH-4057 Test</code>, <code>Modal2</code>] but the <code>OpenPopup("Modal2")</code> call is trying to open [<code>GH-4057 Test</code>, <code>Modal1</code>, <code>Modal2</code>].
</summary>

```cpp
// GH-4057
ImGui::Begin("GH-4057 Test");
if (ImGui::Button("Show modal 1"))
{
    ImGui::OpenPopup("Modal1");
}

if (ImGui::BeginPopupModal("Modal1"))
{
    if (ImGui::Button("Show modal 2"))
    {
        ImGui::OpenPopup("Modal2");
    }

    if (ImGui::Button("Close"))
    {
        ImGui::CloseCurrentPopup();
    }

    ImGui::EndPopup();
}

if (ImGui::BeginPopupModal("Modal2"))
{
    if (ImGui::Button("Close"))
    {
        ImGui::CloseCurrentPopup();
    }

    ImGui::EndPopup();
}

ImGui::End();
```

</details>

**Comment by Lester702** [comment]
> I'm not sure what's wrong with your current code without more context, but maybe it will help to see an example which works:
> 
> ```c++
> // GH-4057
> ImGui::Begin("GH-4057 Test");
> if (ImGui::Button("Show modal 1"))
> {
>     ImGui::OpenPopup("Modal1");
> }
> 
> if (ImGui::BeginPopupModal("Modal1"))
> {
>     if (ImGui::Button("Show modal 2"))
>     {
>         ImGui::OpenPopup("Modal2");
>     }
> 
>     if (ImGui::Button("Close"))
>     {
>         ImGui::CloseCurrentPopup();
>     }
> 
>     if (ImGui::BeginPopupModal("Modal2"))
>     {
>         if (ImGui::Button("Close"))
>         {
>             ImGui::CloseCurrentPopup();
>         }
> 
>         ImGui::EndPopup();
>     }
> 
>     ImGui::EndPopup();
> }
> 
> ImGui::End();
> ```
> 
> ![image](https://user-images.githubusercontent.com/278957/115224862-09545f00-a0d3-11eb-85c1-b37b407a60a6.png)
> 
> Keep in mind that internally Dear ImGui's [IDs are part of a stack](https://github.com/ocornut/imgui/blob/936f53229db4d45b445a3c26795718523262654e/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it). The relationship between `OpenPopup` and `BeginPopupModal` is affected by this.
> 
> For example, the variation of this code listed below (click to expand) doesn't work because `Modal2` has a full ID of [`GH-4057 Test`, `Modal2`] but the `OpenPopup("Modal2")` call is trying to open [`GH-4057 Test`, `Modal1`, `Modal2`].

The example cleared it up for me.
Thank you
