### ISSUE TITLE
Very fast input handling on Win32

### ISSUE THREAD

**Issue by RusJJ** [ocornut/imgui#4058]
Hi there!
Lets do this fast: using Win32 Impl, using: ImGui_ImplWin32_WndProcHandler(hWnd, uMsg, wParam, lParam);
Typing in ImGui::InputText like "let's type 10 chars at once".
Is there any way to prevent this WITHOUT using Sleep &etc?

**Comment by ocornut** [comment]
I don’t understand your request. Please make effort to explain yourself. Please also don’t ignore issue submitting guidelines.

**Comment by PathogenDavid** [comment]
It sounds to me like you've messed up something in your message pump (probably around `PeekMessage` or `TranslateMessage`), but without more details all we can really do is guess.

The issue template is not there for fun. Even if you think the requested information seems pointless, it is crucial for helping us help you. (Particularly the standalone example section.)

**Comment by RusJJ** [comment]
Sure, i understand. Sorry for this, i was on mobile at that moment.
Looks like its fixed for me now. Forgot to make a loop with PeekMessage. I was doing it WITHOUT it... Thanks @PathogenDavid !
