### ISSUE TITLE
Exposing size / level of parameter stacks

### ISSUE THREAD

**Issue by lanyizi** [ocornut/imgui#4059]
Sometimes we'd need to push different style variables / style colors according to the situation, and over time...
```cpp
int varStackLevel = 0;
int colorStackLevel = 0;
if (x) {
  ImGui::PushStyleVar(...);
  varStackLevel += 1;
  if (y) {
    ImGui::PushStyleVar(...);
    ImGui::PushStyleVar(...);
    ImGui::PushStyleColor(...);
    varStackLevel += 2;
    colorStackLevel += 1;
  }
}
else if (z) {
  ImGui::PushStyleVar(...);
  ImGui::PushStyleColor(...);
  ImGui::PushStyleColor(...);
  varStackLevel += 1;
  colorStackLevel += 2;
}
// after use:
ImGui::PopStyleVar(varStackLevel);
ImGui::PopStyleColor(colorStackLevel);
```

As you can see, the code becomes quite complicated. While this complexity is "necessary" because the logic itself is complicated, the `varStackLevel` and `colorStackLevel` (which are used to correctly pop the stacks) could be simplified if we have access to the size of `ImGuiContext::ColorStack` (or any other parameter stacks).
Then the code could become this:
```cpp
auto varStackLevel = ImGui::GetStyleVarLevel();
auto colorStackLevel = ImGui::GetStyleColorLevel();
if (x) {
  ImGui::PushStyleVar(...);
  if (y) {
    ImGui::PushStyleVar(...);
    ImGui::PushStyleVar(...);
    ImGui::PushStyleColor(...);
  }
}
else if (z) {
  ImGui::PushStyleVar(...);
  ImGui::PushStyleColor(...);
  ImGui::PushStyleColor(...);
}
// after use:
ImGui::SetStyleVarLevel(varStackLevel);
ImGui::SetStyleColorLevel(colorStackLevel);
```
which would be a bit cleaner. 

This also facilitates the writing of RAII wrappers around ImGui stack operations. 
Currently, to correctly keep track of stack level, we'd have encapsulate every `ImGui::PushXXX` function (and we'd have to call `raiiWrapper::PushXXX` instead)
But if the stack level becomes available, we could just write
```cpp
template<auto Func> 
struct StackGuard { 
  ImGuiStackLevelType level;
  ~StackGuard() { Func(level); }
};

{
  StackGuard<ImGui::SetStyleVarLevel> varGuard{ ImGui::GetStyleVarLevel() };
  StackGuard<ImGui::SetStyleColorLevel> colorGuard{ ImGui::GetStyleColorLevel() };

  ImGui::PushStyleVar(...);
  // ...
  // when leaving the scope, ImGui::SetXXXLevel will automatically be called
}
```

**Comment by ocornut** [comment]
I don't imagine those "complex" functions are very common, as you are likely to wrap them somehow.
However nothing prevents you from accessing the stack sizes using `imgui_internal.h` if you wish to experiment with this, e.g. `g.StyleVarStack.Size`. Be mindful that restoring size doesn't mean restoring stack data: e.g. catching stack underflow or overwrite would also be useful.

See #2197 for RAII wrappers. 

I personally don't think they are a good-for-all-cases idea since precise control of pop/push scopes is often necessary and not all stacks should be "aligned" or restored the same. e.g. `PushStyleVar() / Begin() / PopStyleVar() / End()` sequences are common, and you less of of those possibilities when you use RAII wrapper. 

However they are easy to write as per #2197. If you were t use RAII wrappers then you might as well replace PushStyleVar with a simple wrapper and you don't need this stack level/restore?

**Comment by lanyizi** [comment]
Being able settings the stack level manually would make RAII wrappers a bit easier to write, but it's not limited to it. 
As you've said, RAII wrappers aren't good-for-all-cases idea since precise control of pop/push scopes is often necessary.
In that case, being able to get / set the stack levels could still make the things simpler, even when we are in the "traditional" mode.
For example, I can't really use RAII wrappers here:
```cpp
if (condition) {
    // the following doesn't work
    // as soon as you leave the scope, the color will be popped, even before they get used.
    // of course we could have stored them in an outer variable like std::optional<StyleColor>
    // but that would make things more complex instead of simplifying them.
    auto color1 = ImGui::StyleColor{...};
    auto color2 = ImGui::StyleColor{...};

    // it's still better to write in the "traditional way"
    // but then we'd have to manually keep track the stack level
    ImGui::PushStyleColor(...);
    ImGui::PushStyleColor(...);
    styleLevel += 2;

    // And it might be mental burden: 
    // What if, some day I added the following line of code, 
    // and I somehow forgot to correctly change the `stackLevel` variable?
    if (condition2) ImGui::PushStyleColor(...);
}
ImGui::Button(...);
ImGui::PopStyleColor(stackLevel);

// If I could get the initial level, 
// and if I could set the stack to the initial level after use
// then I won't have to manually keep track of that `stackLevel` variable
// there would be less mental burden and I could write code with more confidence.
 ImGui::SetStyleColorLevel(initialLevel);
```

**Comment by ocornut** [comment]
I already answered that you can get those using structs from the internal apis, so I’d suggest using that.

**Comment by ocornut** [comment]
Closing this as answered.
You can use `g.ColorStack.Size` `g.StyleVarStack.Size` and even wrap those in your own function if you wish so....

```cpp
namespace ImGui
{
  int GetStyleColorLevel() { ImGuiContext& g = *GImGui; return g.ColorStack.Size; }
  void SetStyleColorLevel(int n) { ImGuiContext& g = *GImGui; g.ColorStack.Size = n; }
}
```

But I suggest reading https://github.com/ocornut/imgui/issues/4059#issuecomment-825042971 again. You may want to complement your `SetStyleColorLevel()` implementation with `IM_ASSERT(n <= g.ColorStack.Size)` as a way to ensure stack underflows are not silently ignored.
