### ISSUE TITLE
ability to use listbox with capturing closure would be amazing

### ISSUE THREAD

**Issue by xaxxon** [ocornut/imgui#406]
Right now it's hard to build up a listbox from a simple datastructure.  Having to have strings laying around for populating it is a pain.  Allowing for capturing closures would be really handy.   

Right now, you can use the closure syntax, but if it closes anything, then it won't match the function prototype.   

I'm not sure exactly the best way, however.  I know using std::function would work, but I think that was introduced in c++11.   

Anyhow, if you know of any acceptable way to do this, it would be awesome.   Thank you :)

**Comment by ocornut** [comment]
You can use closure and pass the arguments you need to it via the void*
Or create yourself a wrapping helper using std::function.
Or just create the listbox yourself (it does call ListBoxHeader() / then Selectable() for each item / then ListBoxFooter()).

**Comment by ocornut** [comment]
@xaxxon ?

**Comment by xaxxon** [comment]
Yes, thank you for your help.  I ended up passing in the capturing closure wrapped up in a std::function as data into my c-style callback which just immediately calls the capturing closure.
