### ISSUE TITLE
How do I know that some data has been modified after imgui rendering?

### ISSUE THREAD

**Issue by warm-dawn** [ocornut/imgui#4061]
I have such a purpose, two users need to synchronize the elements of imgui.

Now facing a problem: If I want to know whether the int drawn by ImGui::DragInt has been changed by the user, I need to save a copy of this int before drawing.
When the drawing is completed, compare them again, if they are different, notify the other party to change.

If I want to know ImGui::InputText, I need to know it in ImGuiInputTextCallback callback.

Is there a way to avoid extra copies when drawing ImGui, and achieve my goal faster?

**Comment by ocornut** [comment]
All functions return a bool which says if the value was modified.
It is also equivalent to calling `IsItemEdited()`.
