### ISSUE TITLE
Group indentation question ?

### ISSUE THREAD

**Issue by Lumengine** [ocornut/imgui#4062]
Hi,
Is there a simple way to right aligned elements in a Group() ?

For example : 

![Dear_imgui_group](https://user-images.githubusercontent.com/45269243/115719543-7cccc980-a37c-11eb-89f8-00259601125d.PNG)

If there is no simple way, I should retrieve the final group size and then SetCursorPosX according to the text size I guess ?
But how did I get the final size of the group item as I'm doing a loop with the text to show ?

My goal here is to group the output pins of a node, so I want them to be right aligned to create the link. I didn't find my answer in the imgui_demo or in the opened issues.
I hope it's not a silly question as I'm still very new to dear imgui.

Thanks ! :)

**Comment by rokups** [comment]
There is no easy way to do this. Best you can do is to manually calculate cursor x position for each item and set it before rendering widget.

**Comment by Lumengine** [comment]
Thanks for the reply ! This is what I did, the main drawback is that I need to check first the max size of the group according to items.

**Comment by ocornut** [comment]
We are going to add a right-to-left layout mode tied to the WorkRect api, it requires us to change the prototype of ItemSize/ItemAdd so that'll be quite a breaking change for some but it is planned.
