### ISSUE TITLE
Is it possible to mix Dear ImGUI with Qt?

### ISSUE THREAD

**Issue by zurgeg** [ocornut/imgui#4065]
**Version/Branch of Dear ImGui:**

Version: v1.82
Branch: Master

**Back-end/Renderer/Compiler/OS**

Back-ends: N/A
Compiler: N/A
Operating System: Windows 10

**My Issue/Question:**

Dear ImGUI is designed only for use as a debug GUI system as per the README. 
Say I'm developing a game (which I happen to be doing), Dear ImGUI wouldn't seem like a good choice for the main game, but Qt does. 
My plan would be to use Dear ImGUI for the debugger and modding related things, Qt for menu and UI, and Panda3D for the rendering and such (although that's out of the scope of this issue).

Is this possible?
Thanks in advance.

**Comment by Xiliusha** [comment]
Qt+ opengl

**Comment by zurgeg** [comment]
> 
> 
> Qt+ opengl

I'm confused, do you mean to use OpenGL inside Qt with Dear ImGUI? That's not a bad idea actually.

**Comment by Xiliusha** [comment]
> > Qt+ opengl
> 
> I'm confused, do you mean to use OpenGL inside Qt with Dear ImGUI? That's not a bad idea actually.

Dear ImGui need a graphic api to rendering, opengl is the best choise (d3d didn't cross platform)

**Comment by ocornut** [comment]
Wherever you can render OpenGL you can render Dear ImGui.
Also see those Qt-related bindings:
https://github.com/ocornut/imgui/wiki/Bindings
