### ISSUE TITLE
Draw texture in ImGui window with relative coordinates 

### ISSUE THREAD

**Issue by peterwilson136** [ocornut/imgui#4067]
This might be impossible given the structure of ImGui, being a new line after each call, but I am wondering how can I use the relative coordinates to the window it is in to draw an image. I have seen this article https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples and the texture coordinates down the bottom, however it doesn't seem like this is possible since it restricts the dimensions of the texture, rather than changing JUST the x and y coordinates of the image. Is this possible?

Side note (/ extension), is it also possible that on something such as a `SliderFloat`, I can replace the rectangle that is used as the slider, with an image instead? 

Thanks!

**Comment by PathogenDavid** [comment]
I believe what you're looking for is `ImGui::SetCursorPos` (which affects all UI elements, not just images.)

> Side note (/ extension), is it also possible that on something such as a SliderFloat, I can replace the rectangle that is used as the slider, with an image instead?

Not easily, no. Your best bet is to make your own widget based off of the provided one and change [how the grabber is rendered](https://github.com/ocornut/imgui/blob/b493cae8c971843886d760bb816dcab661779d69/imgui_widgets.cpp#L2983-L2985).
