### ISSUE TITLE
ImFontAtlas::AddFontDefault() could have a default font size

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#407]
Currently the size of the default font is hard-coded to 13.f.
Why not change the method of the <b>ImFontAtlas</b> class from:
```c++
IMGUI_API ImFont*    AddFontDefault(const ImFontConfig* font_cfg = NULL);
```
to:
```c++
IMGUI_API ImFont*    AddFontDefault(const ImFontConfig* font_cfg = NULL,float defaultFontSize=13.f);
```
?

**Comment by ocornut** [comment]
Because it is a bitmap font that is designed for size 13 and it doesn't make much sense at any other size (perhaps 26 can be useful sometimes).

**Comment by Flix01** [comment]
OK.
It's just that I wanted to load another font of different size and be able to re-use the default font so that I could use them both on the same line without having fonts of different sizes.
But it's just OK for me: I can load two fonts instead of just one.

**Comment by Flix01** [comment]
Just a few other questions (without reopening this issue):
1) From the site: http://www.upperbounds.net/index.php?menu=download, if you click on
the info icon next to the proxy clean download:
> proggy clean information
Proggy Clean is probably the most popular programming font.
Use at point size 9 (bitmap font), 12 (truetype), or 16 (mac truetype)

Why have you used 13.f as default size ?

2) If you open ProggyClean.ttf with a font viewer, you can see that there are a bunch of extra fonts that  GetGlyphRangesDefault() does not import (for example at least the euro glyph (0x20AC) could be added).

**Comment by ocornut** [comment]
1) I'm not sure I think it is a side-effect of how font size are passed around, stb_truetype wants 13 perhaps it includes the spacing between? Perhaps proggy's author measured the size in pixels? I don't know if I native Windows API would require 12 or 13 here. But 12 with the current code will definitively get you a wrong result.

2) Why not, could you list the characters in question?

**Comment by Flix01** [comment]
1) Ok.
2) AFAICS now, in the ttf there are just the chars: 32-255 (0x020-0x0FF) and the euro glyphs 0x20AC.

**Comment by Flix01** [comment]
It's OK for me.
