### ISSUE TITLE
Implicit Conversion between glm::vec and ImVec doesn't work after defining macros in "imconfig"

### ISSUE THREAD

**Issue by gallickgunner** [ocornut/imgui#4071]
Version: 1.80
Branch: master
Back-ends: OpenGL3 + GLFW
Operating System: Win10

Hello, I just defined the conversion macros in `imconfig.h` like this

```
#define IM_VEC2_CLASS_EXTRA                                                 \
        ImVec2(const glm::vec2& f) { x = f.x; y = f.y; }                    \
        operator glm::vec2() const { return glm::vec2(x,y); }
```

Now I was expecting, that this would work

```
glm::vec2 a;
ImVec2 b;
glm::vec2 result = a + b;       // doesn't work. However "result = b" works.
```
But it doesn't. The strange thing is if I define `IMGUI_DEFINE_MATH_OPERATORS`, the above compiles. I thought you weren't supposed to enable that macro if you were using other vector types as it would cause possible collisions, etc. 

This might not be related to imgui but to C++ in general but I can't ask this on stackoverflow as the program compiles when I define the macro which pulls in all those static inline builtin overloaded operators. So i thought people here might know better what's going on. Thanks.

**Comment by jimgbuck** [comment]
Using `+` with an `ImVec` type naturally needs to have a binary `+` operator defined, which you only get if you enable `IMGUI_DEFINE_MATH_OPERATORS`. You should get the same error even if you weren't adding with your own type and only adding together two `ImVecs`.

**Comment by gallickgunner** [comment]
> Using `+` with an `ImVec` type naturally needs to have a binary `+` operator defined, which you only get if you enable `IMGUI_DEFINE_MATH_OPERATORS`. You should get the same error even if you weren't adding with your own type and only adding together two `ImVecs`.

glm already defines an overloaded binary operator taking two `glm:vec2`. I thought the compiler would notice that the arguments were `glm::vec2` and thus would try to find a way to convert `ImVec2` to `glm::vec2` and would use the implicit conversion operator defined in the macro but it doesn't work.

**Comment by ocornut** [comment]
I am not acquainted enough with how C++ perform those lookups. I don't have a suggestion other than defining more operators but that's messy.

However the general point of those macros to always use and convert from/to your native types, reducing the need for those mixed operators altogether.

**Comment by gallickgunner** [comment]
> I am not acquainted enough with how C++ perform those lookups. I don't have a suggestion other than defining more operators but that's messy.
> 
> However the general point of those macros to always use and convert from/to your native types, reducing the need for those mixed operators altogether.

Yeah, I understand. I'm not familiar with the lookups as well. It works If I cast it explicitly like
```
glm::vec2 a;
ImVec2 b;
glm::vec2 result = a + (glm::vec2) b;     
```

We can close it as we don't have much info on why it's happening. If somebody finds this and knows though, I'd be happy to know the cause.
