### ISSUE TITLE
How to control the width of ImGui::Text()

### ISSUE THREAD

**Issue by warm-dawn** [ocornut/imgui#4075]
How to make ImGui::Text("__") and ImGui::Text("++++++++++++++") have the same width.

For some fonts, I can’t make them display the same width. Because they are in different TreeNodes, I don’t know how to use the layout for this situation.
![image](https://user-images.githubusercontent.com/59309812/116043251-0264b800-a6a2-11eb-94a1-e8b710f18c8f.png)

**Comment by ocornut** [comment]
Usually in that situation
- you can use SetCursorX to change the X position.
- you might use Tables or Columns

What we are currently missing is a public-facing helper function to display Text using an ellipsis ("....") when not fitting. There are stuff of this kind in the imgui_internal.h API but they need wrapping to be used as a widget.

**Comment by warm-dawn** [comment]
thank you

**Comment by sweihub** [comment]
I found a easy solution in the demo
```cpp
 // Aligned to arbitrary position. Easy/cheap column.
        IMGUI_DEMO_MARKER("Layout/Basic Horizontal Layout/SameLine (with offset)");
        ImGui::Text("Aligned");
        ImGui::SameLine(150); ImGui::Text("x=150");
        ImGui::SameLine(300); ImGui::Text("x=300");
        ImGui::Text("Aligned");
        ImGui::SameLine(150); ImGui::SmallButton("x=150");
        ImGui::SameLine(300); ImGui::SmallButton("x=300");
```
