### ISSUE TITLE
ImGui:Selectable: double click only

### ISSUE THREAD

**Issue by gucio321** [ocornut/imgui#4082]
**Version/Branch of Dear ImGui:**

Version: 1.83 (WIP)
Branch: master

*Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp
Compiler: doesn't metter
Operating System: Fedora release 33 (Thirty Three)

**My Issue/Question:**

I'm trying to create something like file explorer using `DearI mGui`.
The directories uses TreeNodes and files - ImGui:Selectable. I'd want, to open files by Double click.
but it isn't currently possible. There is only a `ImGuiSelectableFlags_AllowDubleClick` but it allows single-clicks too.
Is it possible to add someghing like `ImGuiSelectableFlags_DoubleClickOnly`?

**Comment by ocornut** [comment]
"Clicking" on a Selectable perform no action, it only returns true.

You can use
```
if (Selectable(...), ImGuiSelectableFlags_AllowDoubleClick) && IsMouseDoubleClicked(0))
```
