### ISSUE TITLE
SliderScalar + keyboard

### ISSUE THREAD

**Issue by eRabbit0** [ocornut/imgui#4083]
**Fedora // Vulkan + SDL + Imgui (1.78)**

Tried to manipulate data from keyboard with SliderScalar, but have confusing behavior.

Simplified code:
```
double value = 0;
double min = -100.0, max = 100.0;

while (1) {
    bool ret = false;
    
    printf ("step 0: %f .. %d // ", value, ret);
    ret = SliderScalar ("label", ImGuiDataType_Double, &value, &min, &max, "%f");
    printf ("step 1: %f .. %d // ", value, ret);

    if (IsKeyPressed (SDL_SCANCODE_UP) && IsItemActive ())
             value += 1.0;

    printf ("step 2: %f .. %d\n", value, ret);
    Render ();
}
```

When i enter slider editing mode (through CTRL), and press 'UP' button once - data increments, but on the next frame it is cleared to its previous value with following output:
step 0:   0 .. 0 // step 1:   0 .. 0 // step 2:   1 .. 0
step 0:   1 .. 0 // step 1:   0 .. 1 // step 2:   0 .. 1

Manipulating slider without keyboard works perfectly. 
Any workaround to make slider work with keyboard for stepping or am i missing something obvious to make it happen?

Thanks in advance!

**Comment by eRabbit0** [comment]
Got some time to work on the issue.

Updated to 1.84 and as far as i understand ImGui caches data during the call to **TempInputScalar** inside SliderScalar which results in such behavior.

```
if (TempInputText(bb, id, label, data_buf, IM_ARRAYSIZE(data_buf), flags))
{
        // Backup old value
        size_t data_type_size = DataTypeGetInfo(data_type)->Size;
        ImGuiDataTypeTempStorage data_backup;
        memcpy(&data_backup, p_data, data_type_size);
         ...
}
````

All starts working as intended when i catch SDL_SCANCODE_UP on IsItemHovered without entering slider's 'editing mode' through CTRL + left mouse.

**Comment by ocornut** [comment]
You can enable Keyboard navigation then Space + Left/Right can edit any value already.
