### ISSUE TITLE
How to detect is user inputting text into ImGui::InputText()?

### ISSUE THREAD

**Issue by Czapa10** [ocornut/imgui#4085]
I need to check whether the user pressed the left/right/up/down arrow on the keyboard or not when he's inputting text into ImGui::InputText(), but checking whether ImGui::InputText() widget is currently active could be a more robust solution.
Is there a way to do that?

**Comment by ocornut** [comment]
Please explain precisely what you are actually trying to achieve to avoid a [XY Problem](https://xyproblem.info/).

**Comment by Czapa10** [comment]
I can select the entities in my level editor. When an entity is selected you can use arrow keys or awsd to move entity.
Some types of entities have text data that you can edit in the level editor. I use ImGui::InputText() for this. The problem is that when I change the position of the cursor in the text buffer by using arrow keys it also moves the selected entity in the world.
When I enter 'a' 'w' 's' or 'd' to text buffer the entity doesn't because I don't handle awsd/arrows shortcuts if ImGui::InputText() returned true. I'd like to also make this work for arrow keys.

**Comment by nitrix** [comment]
I think you're describing the `WantCaptureKeyboard` flag in `IO` (see `GetIO()`) that tells you whether or not a widget wants to intercept keyboard inputs.

You can check the flag in your game's input processing to filter for the events that are specifically meant to your game.

**Comment by Czapa10** [comment]
Yes, I had problems with mouse picking too. I used to solve the mouse picking problem with another unreliable workaround.
Now I use both WantCaptureMouse and WantCaptureKeyboard. It solves the whole issue.
Thank you.
