### ISSUE TITLE
Tables Static Column Width

### ISSUE THREAD

**Issue by aramoki** [ocornut/imgui#4092]
Is there any way to set the Column width static value. I couldn't find it in the demo.

For example, I want the first column to be 30px, and others will get the rest.

seems like `ImGui::SetColumnWidth(0, 30.0f);` doesn't work with new tables.

**Comment by aramoki** [comment]
Well. This seems to work. It would be nice to see this example in the demo. 
```
ImGui::TableSetupColumn("12", ImGuiTableColumnFlags_WidthFixed , 20.0f);
ImGui::TableSetupColumn("13", ImGuiTableColumnFlags_WidthStretch);
```

**Comment by ocornut** [comment]
If you are using the table api usually this is done with TableSetupColumn().

There are several dozen examples in the demo showcasing setting up width and resizable flags.
