### ISSUE TITLE
Docking on a NoMove window allows said window to be moved

### ISSUE THREAD

**Issue by XeroKimo** [ocornut/imgui#4096]
**Version/Branch of Dear ImGui:**

Version: 1.83 WIP
Branch: _docking_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp 
Compiler: MSVC 16.9.4
Operating System: Windows

**My Issue:**

I wanted to have a full screen docking on my main window so I placed a non-moveable, non-resizable ImGui window in the background. Docking worked, but it allowed that NoMove window to be moved around if you select the moveable window's title bar.

**Screenshots/Video**

![Animation](https://user-images.githubusercontent.com/38732789/116804692-c0e36b00-aaee-11eb-8298-6af0bd155a71.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
        ImGuiWindowFlags flags = {};
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_MenuBar;
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_NoNavFocus;
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_NoCollapse;
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_NoMove;
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_NoTitleBar;
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_NoNav;
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_NoBringToFrontOnFocus;
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_NoFocusOnAppearing;
        flags |= ImGuiWindowFlags_::ImGuiWindowFlags_NoResize;

        static bool alwaysOpen = false;
        if(ImGui::Begin("Hello", &alwaysOpen, flags))
        {
            RECT rect;
            GetClientRect(m_hwnd, &rect);

            ImGui::SetWindowSize(ImVec2(static_cast<float>(rect.right), static_cast<float>(rect.bottom)), ImGuiCond_::ImGuiCond_Always);
            ClientToScreen(m_hwnd, reinterpret_cast<LPPOINT>(&rect.left));
            ClientToScreen(m_hwnd, reinterpret_cast<LPPOINT>(&rect.right));

            ImGui::SetWindowPos(ImVec2(static_cast<float>(rect.left), static_cast<float>(rect.top)), ImGuiCond_::ImGuiCond_Always);

        }
```

**Comment by ocornut** [comment]
If you allow your window to be docking (not using _NoDocking) this is going to take over size and position.

The solution is exactly what DockspaceOverViewport() does - create a host window like yours but make it undockable, then inside that window create a dockspace.

See. demo>examples>dockspace showcasing this and you can use DockspaceOverViewport() so do what you are trying to do. Possition and Size are already known so no need to call GetClientRect().

**Comment by ocornut** [comment]
@XeroKimo Does that answer your question?

**Comment by XeroKimo** [comment]
Yea we're good
