### ISSUE TITLE
Drawing text over *everything* (including borders/padding)?

### ISSUE THREAD

**Issue by pnill** [ocornut/imgui#4097]
**Version/Branch of Dear ImGui:**

Version: v1.82 
Branch: master

Back-ends: sdl_opengl2
Compiler: gcc
Operating System: Linux

**My Issue/Question:**

Trying to draw text over *everything* currently displayed in a window making use of DrawList, also tried SetCursorPos prior to this and just ImGui::Text(), however my window has a border and the border clips the text... the border has to be large because of the purpose of it (20.0f x/y) but I'd like to be able to draw over it and currently everything I've tried hasn't worked.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/12246596/116846947-5853c700-ab9e-11eb-92ff-46b23c453ffd.png)

```

ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 20.0f);
ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(90.0f,20.0f));

static ImGuiWindowFlags flags = ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoSavedSettings;

  const ImGuiViewport* viewport = ImGui::GetMainViewport();
        ImGui::SetNextWindowPos(use_work_area ? viewport->WorkPos : viewport->Pos);
        ImGui::SetNextWindowSize(use_work_area ? viewport->WorkSize : viewport->Size);

bool show_demo_window = true;

if(ImGui::Begin("Window", &show_demo_window, flags))
{
          // some controls here.. ImGui::Text,ImGui::ImageButton stuff... (Renders over this fine)

        //very end of window
         ImDrawList* draw_list = ImGui::GetWindowDrawList();
         draw_list->AddText(ImVec2(20.0f,20.0f), ImColor(50.0f,45.0f,255.0f,255.0f),"My text is cut off my text is cut off my text is cut off");

}

ImGui::End();
```

**Comment by ocornut** [comment]
To ensure top-most rendering over all windows, See Demo>Examples>Custom Rendering for examples of using GetForegroundDrawList().

As for your issue, there is a ClipRect pushed on the stack which roughly removes WindowPadding.x*0.5 on each side. So you can either use zero WindowPadding and position cursor yourself, either use PushClipRect()/PopClipRect() to override the cliprect and draw anywhere.

(That cliprect thing is aimed to be reworked in the future so WindowPadding down the line won’t affect the initial ClipRect as much.)
