### ISSUE TITLE
ImGui::ImageButton using texture

### ISSUE THREAD

**Issue by anshul-soni** [ocornut/imgui#410]
So I want to put images in the ImageButton
And I have texture id stored in a map for each texture that I want to create the button with, the texture id is GLuint. But how do I pass it to the ImageButton to display it.
I tried typecasting the id to ImTextureID but that doesnt work as I expected it to.
This is what I did
```javascript
for (auto texture : textureList)
{
	ImTextureID id = (ImTextureID)enyin::TextureProvider::GetInstance().Get(texture)->GetTextureId();
	if (ImGui::ImageButton(id, ImVec2(32, 32), ImVec2(0, 0), ImVec2(32.0f, 32.0f), 2, ImColor(0, 0, 0, 255)))
	{
				
	}
}
```

**Comment by ocornut** [comment]
You can pass anything you want that fits in a void*, imgui doesn't know and doesn't care what it is. Only thing that matters is that you render function cast the void* back to your type and set the current texture for rendering.

That code you posted should work out of the box if your gettextureid() function is returning a GLUint that is an OpenGL texture identifier, because this is what the default renderer expect.

In your situation it'll probably be nicer to use if you pass your Texture* type casted as void* and your render function uses Texture* directly.

**Comment by anshul-soni** [comment]
'''javascript
enyin::Texture* tex = static_cast<enyin::Texture*>(pcmd->TextureId);
glBindTexture(GL_TEXTURE_2D, tex->GetTextureId());
'''

**Comment by anshul-soni** [comment]
```javascript
enyin::Texture* tex = static_cast<enyin::Texture*>(pcmd->TextureId);
					glBindTexture(GL_TEXTURE_2D, tex->GetTextureId());
```

**Comment by ocornut** [comment]
Yes that should work if that code is in the render function, and you are passing `Texture*` casted as `void*` as TextureId.

**Comment by anshul-soni** [comment]
So it just displayed the image buttons with different colors instead of the textures.
and if I put that thing in the render function instead of typecasting inside my for loop it breaks !
Texture* is my own class which stores textureID which is a int, height of the image and width of the image.

**Comment by anshul-soni** [comment]
So if I use the typecasting in my for loop I see all the buttons being created with different colors. But no images.

**Comment by ZahlGraf** [comment]
Maybe your GetTextureId() Method does not deliver an texture object that could be used by the render-method of your IMGUI renderer (for example an OpenGL render ID).
Then the texture that is taken by your renderer is some kind of random and thus - depending on the initialization of the memory - you get different colors for different texture IDs?
Just a quick guess... maybe I am wrong.

**Comment by adam4813** [comment]
Does your shader know to get its color values from a texture?

**Comment by ocornut** [comment]
ImGui does absolutely nothing but copy a void* for you and give it back to you. Maybe use a debugger and figure out what is wrong in your case. Perhaps your shader/render settings are incompatible with the texture you are using. Some people pass a high level "material" which embed texture and how to render it (shaders, etc.)  which may suit your need more. But most probably you aren't passing the right value in ImageButton or not reading it properly at render side. You haven't posted both sides of the code simultaneously so it hard to tell.

I have to close this as I can't devote my time to fix users bugs and need to focus on ImGui, but feel free to discuss it here if you want.
