### ISSUE TITLE
Strange behaviour when using drag and drop with a button on the same line

### ISSUE THREAD

**Issue by t0mke** [ocornut/imgui#4107]
Using ImGui::Text works just fine but with a button on the same line as a selectable it's like the sensitivity increases dramatically. I'm using the same code as the demo provided, just with a button added
```
            static const char* item_names[] = { "Item One", "Item Two", "Item Three", "Item Four", "Item Five" };
            for (int n = 0; n < IM_ARRAYSIZE(item_names); n++)
            {
                const char* item = item_names[n];
                ImGui::Button("button");
                ImGui::SameLine();

                ImGui::Selectable(item);

                if (ImGui::IsItemActive() && !ImGui::IsItemHovered())
                {
                    int n_next = n + (ImGui::GetMouseDragDelta(0).y < 0.f ? -1 : 1);
                    if (n_next >= 0 && n_next < IM_ARRAYSIZE(item_names))
                    {
                        item_names[n] = item_names[n_next];
                        item_names[n_next] = item;
                        ImGui::ResetMouseDragDelta();
                    }
                }
            }
```

**Comment by ocornut** [comment]
If your button is always called `"button"` and you have no `PushID()/PopID()` call around then you have an ID conflict and should read the FAQ:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-multiple-widgets-with-the-same-label

As per your repro code I am assuming this is your issue.
If your actual code is different and not suffering from an ID conflict please confirm it with a repro that doesn't have an ID conflict and we can open and look at this.

**Comment by t0mke** [comment]
thanks, code works great
