### ISSUE TITLE
What things in the Vulkan code should be changed for the ImGui window rendering?

### ISSUE THREAD

**Issue by prostargamer** [ocornut/imgui#4115]
**Version/Branch of Dear ImGui:**

Version: v1.82
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp +imgui_impl_vulkan.cpp
Compiler: MSVC 2019
Operating System: Windows 10

**My Issue/Question:**

What things should be replaced for integrating the ImGui render from the Vulkan point of view(not GLFW)?
The example is too confusing because it creates a window right away.
I **[have](https://github.com/mrjbom/GraphicsViewer/blob/master/src/MainWindow/MainWindow.cpp)** a code that draws a basic window, I need to embed an ImGui render in it.
As far as I understand I have to change the following things:
1. Add the code that creates the descriptor pool.
2. Add the code that will render the ImGui window when writing to the command buffer.
3. ???

What else do I need to do?
Tell us what things are added compared to the usual rendering.

**Comment by thomasherzog** [comment]
I've integrated ImGui in my own Vulkan renderer and you can find the project [here](https://github.com/Illuminai/Vision). The important files are `src/windowing/ImGuiWindow.cpp`, `src/windowing/VulkanWindow.cpp` and their headers. Below you'll find a small summary of the steps but I'd recommend looking into the source code of the above mentioned project.

### Important initialization steps
<details>
<summary>Descriptor pool creation (e.g. ImGui demo)</summary>
<br>

```c++
VkDescriptorPoolSize pool_sizes[] = {
    {VK_DESCRIPTOR_TYPE_SAMPLER,                1000},
    {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1000},
    {VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,          1000},
    {VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,          1000},
    {VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,   1000},
    {VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,   1000},
    {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,         1000},
    {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,         1000},
    {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC, 1000},
    {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC, 1000},
    {VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT,       1000}
};

VkDescriptorPoolCreateInfo pool_info = {};
pool_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
pool_info.flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
pool_info.maxSets = 1000 * IM_ARRAYSIZE(pool_sizes);
pool_info.poolSizeCount = (uint32_t) IM_ARRAYSIZE(pool_sizes);
pool_info.pPoolSizes = pool_sizes;

vulkan::checkError(vkCreateDescriptorPool(context->getDevice().getVkDevice(),
    &pool_info, nullptr, &descriptorPool), 
    "ImGui descriptor pool creation");
```
</details>

<details>
<summary>Initialization with ImGui_ImplGlfw_InitForVulkan and ImGui_ImplVulkan_Init</summary>
<br>

```c++
ImGui_ImplGlfw_InitForVulkan(window, true);

ImGui_ImplVulkan_InitInfo init_info = {};
init_info.Instance = context->getInstance().getVkInstance();
init_info.PhysicalDevice = context->getDevice().getVkPhysicalDevice();
init_info.Device = context->getDevice().getVkDevice();
init_info.QueueFamily = context->getDevice().getGraphicsQueueFamily();
init_info.Queue = context->getDevice().getGraphicsQueue();
init_info.DescriptorPool = descriptorPool;
init_info.MinImageCount = swapchain->imageCount;
init_info.ImageCount = swapchain->imageCount;
init_info.CheckVkResultFn = [](VkResult result) { vulkan::checkError(result, "Internal ImGui operation"); };
ImGui_ImplVulkan_Init(&init_info, renderPass);
```
</details>

<details>
<summary>Creation and upload of the font texture</summary>
<br>

```c++
context->executeTransient([](VkCommandBuffer commandBuffer) {
    return ImGui_ImplVulkan_CreateFontsTexture(commandBuffer);
});
ImGui_ImplVulkan_DestroyFontUploadObjects();
```
</details>

### Trivial ImGui UI rendering in the render loop (renders to an ImDrawData)
<details>
<summary>Start new ImGui Frame</summary>
<br>

```c++
ImGui_ImplVulkan_NewFrame();
ImGui_ImplGlfw_NewFrame();
ImGui::NewFrame();
```
</details>

<details>
<summary>Calling of UI component functions</summary>
<br>

```c++
// Your own UI
```
</details>

<details>
<summary>Rendering to an ImDrawData</summary>
<br>

```c++
ImGui::Render();
ImDrawData *main_draw_data = ImGui::GetDrawData();
```
</details>

<details>
<summary>Vulkan rendering (instructions in the next header section)</summary>
<br>

```c++
// Vulkan rendering
```
</details>

<details>
<summary>[Optional] Multi-viewport support</summary>
<br>

```c++
if (ImGui::GetIO().ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
    ImGui::UpdatePlatformWindows();
    ImGui::RenderPlatformWindowsDefault();
}
```
</details>



### Vulkan rendering procedure

<details>
<summary>Reset command pool, begin command buffer and begin render pass</summary>
<br>

```c++
vulkan::checkError(vkResetCommandPool(context->getDevice().getVkDevice(),
                                      commandPools[imageIndex].getVkCommandPool(), 0),
                   "Command buffer reset");

VkCommandBufferBeginInfo commandBufferBeginInfo = {};
commandBufferBeginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
commandBufferBeginInfo.flags |= VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
vulkan::checkError(vkBeginCommandBuffer(commandBuffers[imageIndex],
                                        &commandBufferBeginInfo),
                   "Command buffer begin");

VkRenderPassBeginInfo renderPassBeginInfo = {};
renderPassBeginInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
renderPassBeginInfo.renderPass = renderPass;
renderPassBeginInfo.framebuffer = framebuffers[imageIndex];
renderPassBeginInfo.renderArea.extent = swapchain->extent;
vkCmdBeginRenderPass(commandBuffers[imageIndex], &renderPassBeginInfo, VK_SUBPASS_CONTENTS_INLINE);
```
</details>

<details>
<summary>ImGui_ImplVulkan_RenderDrawData with the ImDrawData</summary>
<br>

```c++
ImGui_ImplVulkan_RenderDrawData(draw_data, commandBuffers[imageIndex]);
```
</details>

<details>
<summary>End render pass and end command buffer</summary>
<br>

```c++
vkCmdEndRenderPass(commandBuffers[imageIndex]);

VkPipelineStageFlags wait_stage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
VkSubmitInfo info = {};
info.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
info.waitSemaphoreCount = 1;
info.pWaitSemaphores = &syncObject.imageAvailableSemaphore;
info.pWaitDstStageMask = &wait_stage;
info.commandBufferCount = 1;
info.pCommandBuffers = &commandBuffers[imageIndex];
info.signalSemaphoreCount = 1;
info.pSignalSemaphores = &syncObject.renderFinishedSemaphore;

vulkan::checkError(vkEndCommandBuffer(commandBuffers[imageIndex]),
                   "Command buffer end");
```
</details>

<details>
<summary>Reset fences and submit to the graphics queue</summary>
<br>

```c++
vkResetFences(context->getDevice().getVkDevice(), 1, &syncObject.fence);

vulkan::checkError(vkQueueSubmit(context->getDevice().getGraphicsQueue(), 1, &info, syncObject.fence),
                   "Queue submit");
```
</details>


### Important destruction steps

<details>
<summary>Wait for device idle</summary>
<br>

```c++
vkDeviceWaitIdle(context->getDevice().getVkDevice());
```
</details>

<details>
<summary>Shutdown ImGui</summary>
<br>

```c++
ImGui_ImplVulkan_Shutdown();
ImGui_ImplGlfw_Shutdown();
```
</details>

<details>
<summary>Destroy descriptor pool</summary>
<br>

```c++
vkDestroyDescriptorPool(context->getDevice().getVkDevice(), descriptorPool, nullptr);
```
</details>

**Comment by prostargamer** [comment]
Great answer, I'm sure it will help me!
Thanks.

**Comment by ocornut** [comment]
Thanks @thomasherzog for the great answer.

There's also this blog post listed under [Articles](https://github.com/ocornut/imgui/wiki#articles-about-dear-imgui) in the Wiki:
https://frguthmann.github.io/posts/vulkan_imgui/

May be good to include that content in some form of wiki page ?
