### ISSUE TITLE
CmdListsCount is 0 on first pass

### ISSUE THREAD

**Issue by buzmeg** [ocornut/imgui#4118]
**Version/Branch of Dear ImGui:**

Version: v1.82
Branch: master

**Back-end/Renderer/Compiler/OS**

Compiler: Likely clang of some flavor
Operating System: OS X

**My Issue/Question:**

CmdListsCount comes back as 0 on first pass.  Is this expected?

Put the following lines below ImGui::Render() in the example_null main.cpp file:

```
        ImDrawData *pimdd = ImGui::GetDrawData();

        printf("Command lists count: %d\n", pimdd->CmdListsCount);
```

Output from example_null is:
```
NewFrame() 0
Command lists count: 0
NewFrame() 1
Command lists count: 2
NewFrame() 2
Command lists count: 2
```

Note that the first Command lists count is *zero*.

Is this expected?

Thanks.

**Comment by ocornut** [comment]
> Is this expected?

It depends on the arrangement of windows, if the windows have explicit sizes or not, if the windows have sizes pulled from .ini file, if the windows are docked.

Basically in the most situations, new windows are hidden for one frame so they can calculate a default size.
Usage of e.g. `SetNextWindowSize()` to enforce a size lift this constraint as a side-effect.
