### ISSUE TITLE
Docking: rendering to central node?

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#4119]
I'm using the docking branch (31290807dc169d4ee62b16f42bcb1d9a294be93b) and creating a default layout consisting of a sidebar and bottom panel:

![image](https://user-images.githubusercontent.com/77120437/117561035-f389e800-b047-11eb-873b-23c982fd18ba.png)

I want to draw something in the remaining space, in the central node. I've read that I should dock a window there and render a texture onto it. But docking a window there is not actually the behavior I want. I just want to draw there. So:

 * Can I dock a window there but remove the tab, title, everything, everything but my texture itself?
 * Can I make the window that I dock there... docked to begin with, but not allow undocking?

**Comment by invrainbow** [comment]
Never mind, I just solved this by using `ImGuiDockNodeFlags_PassthruCentralNode` and grabbing the render area from
```c++
auto node = ImGui::DockBuilderGetCentralNode(ImGui::GetID("main_dockspace"));
// use node->Pos & node->Size
```

**Comment by ocornut** [comment]
To answer your initial question. Its not well documented but you can:
- use ImGuiWindoeClass to make your central window not dockable with other windows
- grab the dock node from a window, and set flags to hide tab bar
