### ISSUE TITLE
Is there any plan that add script binding to imgui, like Lua?

### ISSUE THREAD

**Issue by tangyiyang** [ocornut/imgui#412]
This seems to be a really cool project. As for easier use, like Qt has QScript or QtPython. Is there any binding to this project?

**Comment by ocornut** [comment]
Looks for Bindings/Links in the homepage. There's an unofficial LUA binding among others.

However also note that the api was designed for C++ and some things don't translate well in Lua. The lack of pointers/references in particular.

**Comment by tangyiyang** [comment]
Cool! 
In normal use cases, we don't need all API from C++, we often need the most common used. 
Lack of pointers/refs would not be a problem, write a template to translate the values of the pointers to a Lua table is acceptable. :+1:

**Comment by ocornut** [comment]
The most common used isn't a problem, the potential problem is that ImGui API uses overloading (multiple functions with same names) and default parameters and it may feel very different and more verbose without that.

Cool, I'll let you discuss that binding with Patrick who is now working on it :)
https://github.com/patrickriordan/imgui_lua_bindings
