### ISSUE TITLE
Changing padding for menu items?

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#4129]
I have a normal menu bar:

![image](https://user-images.githubusercontent.com/77120437/117860530-3ebd1a00-b245-11eb-9622-a215893e8802.png)

Can the x-padding of the blue box around "Toggle Breakpoint" be customized? `ItemSpacing.y` is respected but not `ItemSpacing.x`. I've tweaked the different settings in the style editor & can't find anything that changes it.

**Comment by rokups** [comment]
Vertical menus do not use any spacings from the style. There are few things you can do:
* Change `WindowPadding` for entire popup. Not ideal as it will affect all items and create a gap between separator and borders.
* Use `ImGui::Indent()`/`ImGui::Unindent()` around `ImGui::MenuItem()`. Again not ideal as it will indent background as well.
* Prepend spaces to menu label. Stupid but works if you do not want to indent menu item background.

**Comment by invrainbow** [comment]
> Vertical menus do not use any spacings from the style.

I suppose I know that is currently the case, but my question is, why is that the case? And is there no plan to change it?

**Comment by ocornut** [comment]
> Vertical menus do not use any spacings from the style.

I'm not sure where you got it, menus use ItemSpacing properly:
![image](https://user-images.githubusercontent.com/8225057/119173388-7eff7200-ba67-11eb-855c-5eb9b81cc082.png)

The tricky aspect of this is:
![image](https://user-images.githubusercontent.com/77120437/117860530-3ebd1a00-b245-11eb-9622-a215893e8802.png)
There's only a single item on each line, so ItemSpacing.x is not used.

WindowPadding is used for the edges.
In addition there's the known "issue" that windows push a ClipRect that "eats" WindowPadding.x*0.5 on each side (we WILL make that zero), so if WindowPadding=8 your cliprect removes 4 on each side.

IHMO you only need to increase WindowPadding there?

**Comment by invrainbow** [comment]
Confirmed that I'm able to change the padding of the menu by pushing WindowPadding, which is a fantastic start:

![image](https://user-images.githubusercontent.com/77120437/119179315-9f0d4200-ba23-11eb-90f0-e55a00966b2a.png)

However, what I'm ultimately after is increasing the x-padding of the **menu item** itself, for aesthetic reasons. If not ItemSpacing, is there another style var that is used? Or is this currently not supported?

**Comment by ocornut** [comment]
Will look into it.

**Comment by englercj** [comment]
Adding `ImGuiSelectableFlags_SpanAllColumns` to the Selectable in `BeginMenuEx` and `MenuItemEx` allows you to modify the cursor position before calling these functions to get the spacing you want on the menu item content without affecting the selectable area.

Unfortunately there is no way to get this flag in that call without modifying ImGui source. Any other options would be great.
