### ISSUE TITLE
Docking padding issues

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#4130]
#### Problem 1

The dropdown tab selector menu doesn't have any top, left, or bottom padding and thus looks awkward:

![image](https://user-images.githubusercontent.com/77120437/117858440-c0f80f00-b242-11eb-974c-5abc6d2eda4f.png)

I've tested and `ItemSpacing` is respected, just not at the top, left, or bottom.

#### Problem 2

`ItemInnerSpacing` is respected in between tabs, but not between the dropdown selector and the first tab:

![image](https://user-images.githubusercontent.com/77120437/117859804-50ea8880-b244-11eb-9ba5-7c006c7b3c75.png)

In fact, all increasing `ItemInnerSpacing` does is push the hover circle more to the left (but not the arrow), instead of pushing the tabs rightward:

![image](https://user-images.githubusercontent.com/77120437/117859943-898a6200-b244-11eb-882a-ab23457dd674.png)

**Comment by ocornut** [comment]
> Problem 1
> The dropdown tab selector menu doesn't have any top, left, or bottom padding and thus looks awkward:
> I've tested and ItemSpacing is respected, just not at the top, left, or bottom.

This is using `WindowPadding` and it works in the demo, so when submitting an issue try to boil it to a minimum repro. This will allow both you and me to understand the problem better. I am not denying you have an issue in your screenshot but if you don't make the minimum repro you are just offloading the work to me. 

Note that that some style values are fetched at different points of the frame depending on the context, so if you have code altering the values mid-frame (using PushStyleVar/PopStyleVar) you may need to clarify how/where.

> Problem 2
> ItemInnerSpacing is respected in between tabs, but not between the dropdown selector and the first tab:

Confirmed as a bug. It doesn't behave the same on an undocked window where title is spaced with this value.

> In fact, all increasing ItemInnerSpacing does is push the hover circle more to the left (but not the arrow), instead of pushing the tabs rightward:

Confirmed as a bug. Thank you!

**Comment by ocornut** [comment]
> Confirmed as a bug. 

Actually it was intentional:
```cpp
if (node->HasWindowMenuButton && g.Style.WindowMenuButtonPosition == ImGuiDir_Left)
{
    r.Min.x += g.FontSize;// +g.Style.ItemInnerSpacing.x; // <-- Adding ItemInnerSpacing makes the title text moves slightly when in a docking tab bar. Instead we adjusted RenderArrowDockMenu()
}
```
In order for the precise position of the window title **TEXT** to stay still when docking. Look at the "Hello world" text:

![text position](https://user-images.githubusercontent.com/8225057/119007810-dd5a2100-b991-11eb-9ee9-a4d60ea4b497.gif)

With 105d82d13 I've now reworked that rendering to do the opposite and offset the first tab.

**Comment by invrainbow** [comment]
> This is using `WindowPadding` and it works in the demo, so when submitting an issue try to boil it to a minimum repro. This will allow both you and me to understand the problem better. I am not denying you have an issue in your screenshot but if you don't make the minimum repro you are just offloading the work to me.
> 
> Note that that some style values are fetched at different points of the frame depending on the context, so if you have code altering the values mid-frame (using PushStyleVar/PopStyleVar) you may need to clarify how/where.

Oops, sorry about that. I assumed it was a universal bug but you're right, I'd accidentally applied a `PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(2, 2))` to the entire dockspace instead of just the window.

> Confirmed as a bug. Thank you!

Thank you!
