### ISSUE TITLE
What can be obtained by obtaining the css property z-index similar to html between two windows

### ISSUE THREAD

**Issue by susan799** [ocornut/imgui#4131]
> ImGuiWindowFlags window_flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoCollapse;
bool* p_open = NULL;
if (ImGui::Begin(“win1”, p_open, window_flags))
{
ImGui::Text(sceneTxt);
}
ImGui::End();
if (ImGui::Begin(“win2”, p_open, window_flags))
{
ImGui::Text(sceneTxt);
}
ImGui::End();

Hello everyone, I would like to ask that I have two windows, win1 and win2. If the two windows overlap in position, what attribute can I use to determine whether win1 is above win2 or win1 is below win2? Thank you all

What can be obtained by obtaining the css property z-index similar to html between two windows，thanks

**Comment by PathogenDavid** [comment]
It would be helpful to know the problem you're actually trying to solve. As stated in the issue submission guidelines https://github.com/ocornut/imgui/issues/2261:

> * **Try to be explicit with your Goals, your Expectations and what you have Tried.** Be mindful of [The XY Problem](https://xyproblem.info/). What you have in mind or in your code is not obvious to other people. People frequently discuss problems and suggest incorrect solutions without first clarifying their goal. When requesting a new feature, please describe the usage context (how you intend to use it, why you need it, etc..). If you tried something and it failed, show us what you tried.

------------

If all you need to know is which of those two windows was most recently focused (which would generally mean it's on top), you can use `ImGui::IsWindowFocused`:

```cpp
static void GH4131_UsingIsWindowFocused()
{
    static int focusedWindow = 0;

    ImGui::Begin("Window 1");
    if (ImGui::IsWindowFocused())
    {
        focusedWindow = 1;
    }
    ImGui::Text("This window %s above the other.", focusedWindow == 1 ? "is" : "is not");
    ImGui::End();

    ImGui::Begin("Window 2");
    if (ImGui::IsWindowFocused())
    {
        focusedWindow = 2;
    }
    ImGui::Text("This window %s above the other.", focusedWindow == 2 ? "is" : "is not");
    ImGui::End();
}
```

![image](https://user-images.githubusercontent.com/278957/117927695-2dfdba00-b2c0-11eb-9c8d-b8fc1cc0912f.png)

------------

If you literally need to know the z index of the window, I do not believe that is something Dear ImGui exposes on the public API surface, but if you really need it you can infer it from the internal window list, which is ordered from back to front. Note that internal APIs aren't as stable as the public APIs, they might disappear or change in future versions of Dear ImGui.

```cpp
// The higher the value, the more towards the front the window is
static int GetCurrentWindowZIndex()
{
    ImGuiContext* g = ImGui::GetCurrentContext();
    ImGuiWindow* currentWindow = ImGui::GetCurrentWindowRead();

    for (int i = 0; i < g->Windows.Size; i++)
    {
        if (g->Windows[i] == currentWindow)
        {
            return i;
        }
    }

    return -1;
}

static void GH4131()
{
    ImGui::Begin("Window 1");
    ImGui::Text("Z Index = %d", GetCurrentWindowZIndex());
    ImGui::End();

    ImGui::Begin("Window 2");
    ImGui::Text("Z Index = %d", GetCurrentWindowZIndex());
    ImGui::End();
}
```

![image](https://user-images.githubusercontent.com/278957/117927781-4ff73c80-b2c0-11eb-90a4-19649e0e598a.png)

**Comment by susan799** [comment]
> static int GetCurrentWindowZIndex()
{
    ImGuiContext* g = ImGui::GetCurrentContext();
    //ImGuiWindow* currentWindow =  ImGui::GetCurrentWindowRead();

    for (int i = 0; i < g->Windows.Size; i++)
    {
        if (g->Windows[i] == g->CurrentWindow)
        {
            return i;
        }
    }

    return -1;
}

Thank you very much. I changed it in version 1.79. Thank you very much for your patience.

By the way, do you know of any event that can tell if the window size and position have changed? thank you

**Comment by PathogenDavid** [comment]
No problem!

> By the way, do you know of any event that can tell if the window size and position have changed? thank you

Dear ImGui isn't really event-driven. If you need to detect window movement, you can store and check the position/size using `ImGui::GetWindowPos` and `ImGui::GetWindowSize`. For example:

```cpp
static void GH4131_WindowMoving()
{
    static ImVec2 lastPosition(FLT_MAX, FLT_MAX);
    static ImVec2 lastSize(FLT_MAX, FLT_MAX);

    ImGui::Begin("Test Window");
    ImVec2 position = ImGui::GetWindowPos();
    ImVec2 size = ImGui::GetWindowSize();

    bool isMoving = lastPosition.x != position.x || lastPosition.y != position.y;
    bool isResizing = lastSize.x != size.x || lastSize.y != size.y;

    // Clear both moving/resizing if the window is just appearing on this frame
    // (Otherwise the window will always seem to have moved and resized on the first frame)
    if (ImGui::IsWindowAppearing())
    {
        isMoving = false;
        isResizing = false;
    }

    ImGui::Text("Window %s moving", isMoving ? "is" : "is not");
    ImGui::Text("Window %s resizing", isResizing ? "is" : "is not");

    lastPosition = position;
    lastSize = size;

    ImGui::End();
}
```

**Comment by ocornut** [comment]
As first answered, it is very surprising you are asking for those things and it may be a case of XY Problems (https://xyproblem.info/).
You should always explain WHY you think you need this and clarify more of the context, else the answers may push you more far in a wrong direction.

**Comment by susan799** [comment]
@PathogenDavid @ocornut Thank you. I see

**Comment by susan799** [comment]
@PathogenDavid @ocornut Thank you. I see

**Comment by susan799** [comment]
@PathogenDavid @ocornut Thank you. I see

**Comment by susan799** [comment]
thanks
