### ISSUE TITLE
having indent only in first column

### ISSUE THREAD

**Issue by damqui** [ocornut/imgui#414]
hi,

I'm trying to implement a "property view" (like http://www.openrtm.org/openrtm/sites/default/files/697/fig473TypePropertyView_en.png).
With this naive code :

    ImGui::Begin("PropView");
    ImGui::Columns(2);
    ImGui::Text("name1");
    ImGui::NextColumn();
    ImGui::Text("value1");
    ImGui::NextColumn();
    bool Tree = ImGui::TreeNode("tree1");
    ImGui::NextColumn();
    ImGui::NextColumn();
    if (Tree) {
        ImGui::Text("name2");
        ImGui::NextColumn();
        ImGui::Text("value2");
        ImGui::NextColumn();
        ImGui::TreePop();
    }
    ImGui::End();

i got this result : 
![imgui_column_indent](https://cloud.githubusercontent.com/assets/7070580/11420949/bfc404ac-9431-11e5-91c0-eb6d49589b07.png)

How to remove the indent in the second column ?
(didn't find any nice way of doing it)

thanks !

**Comment by ocornut** [comment]
I'll have to think about the best fix, but it probably involve the confusedly named ColumnsStartX (should be renamed to IndentX?) in the context be a per-column thing.

For now a possible workaround would be, after calling NextColumn() on the right column to to do:

```
#include <imgui_internal.h>
ImGuiWindow* window = GetCurrentWindow();
window->DC.CursorPos.x -= window->window->DC.ColumnsStartX;
```

**Comment by damqui** [comment]
ok.
tried the workaround, but it unindents too much.
btw, the indent is okay while dragging the column separator.

**Comment by Flix01** [comment]
Maybe something like:
```c++
ImGui::Begin("PropView");
ImGui::Columns(2);
ImGui::Text("name1");
ImGui::NextColumn();
ImGui::Text("value1");
ImGui::NextColumn();
static bool Tree = false;
if ((Tree=ImGui::TreeNode("tree1"))) ImGui::TreePop();
ImGui::NextColumn();
ImGui::NextColumn();
if (Tree) {
    ImGui::Text("name2");
    ImGui::NextColumn();
    ImGui::Text("value2");
    ImGui::NextColumn();
}
ImGui::End();
```

**Comment by ocornut** [comment]
Try
```
#include <imgui_internal.h>
ImGuiWindow* window = GetCurrentWindow();
window->DC.CursorPos.x -= window->window->DC.ColumnsStartX + window->WindowPadding.x;
```
(not tested. obviously this is just workaround)

**Comment by ocornut** [comment]
I've fixed the bug and added an example on a way to do a property editor using the columns api. 

![property_editor](https://cloud.githubusercontent.com/assets/8225057/11453072/fbd8a76c-95f4-11e5-87d5-4c6068900097.png)

There are a few subtle/minor issues with tree node rendering that I'm working on (related to #324, #282), but nothing really problematic.

**Comment by damqui** [comment]
Cool ! thanks !
