### ISSUE TITLE
is there a function for bool MouseClicked[5]?

### ISSUE THREAD

**Issue by baslr** [ocornut/imgui#4140]
**Version/Branch of Dear ImGui:**

Version / Branch: Tag https://github.com/ocornut/imgui/tree/v1.82

**Back-end/Renderer/Compiler/OS**  DirectX 11 / Windows 10

**My Issue/Question:**
Context:
With the internal `bool MouseClicked[5];` (https://github.com/ocornut/imgui/blob/v1.82/imgui.h#L1864) array it is possible to detect that the user started clicking the mouse (mouse button down).
I would like to use this functionality for other interactions. So I do not have to reinvent the wheel. User selected in an imgui window something and then clicks with the mouse on a 3d environment to place things previously selected in the window.

https://www.youtube.com/watch?v=9TvErFNbQOg

Question:
Since `MouseClicked` is internal, is there a function to check for mouse got from up to down?

**Comment by ocornut** [comment]
There’s literally a function called IsMouseClicked() which return a value from this array.

Please note that testing this specifically is not always the right way to handle all types of mouse interactions. InvisibleButton(), ButtonEx() and ButtonBehavior() will give you access to more features. Many interactions can be implemented with InvisibleButton() + IsItemActive() and other IsItemXXX functions.
