### ISSUE TITLE
ImGui::Text() with power formatting

### ISSUE THREAD

**Issue by peterwilson136** [ocornut/imgui#4142]
Is there any way to have either subscript or superscript in the formatting of text? I.e, when displaying `x^2`, it shows the `2` above the `x`?

Thanks!

**Comment by ocornut** [comment]
We don’t have geneal subscript/superscript features but many fonts include dedicated characters for common use cases such as power of two:
https://www.compart.com/en/unicode/U+00B2
So you can use this character.
