### ISSUE TITLE
Get assert while enable bitmap mode for freetype

### ISSUE THREAD

**Issue by xyc19970716** [ocornut/imgui#4145]
**Version/Branch of Dear ImGui:**

Version: 1.83 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: mingw64 gcc8.1.0
Operating System: windows 10 x64

**My Issue/Question:**

I use the clion to program my project. When i see the imgui_freetype.h/.cpp, it can enable bitmap mode. I want to use this function, but i get assert like next screenshot after i set like this pull [3879](https://github.com/ocornut/imgui/pull/3879).

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/20499955/118400633-05493c00-b695-11eb-99d5-b7ebc7a3877d.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
ImFontConfig font_config;
font_config.SizePixels = 13.0f;
font_config.FontBuilderFlags = ImGuiFreeTypeBuilderFlags_Bitmap;
io.Fonts->AddFontFromFileTTF("c:\\windows\\fonts\\msgothic.ttc", 13.0f, &font_config, io.Fonts->GetGlyphRangesJapanese());
```

**Comment by ocornut** [comment]
Hello,

If I try your code with my copy of msgothic.ttc (8780 KB) it works and I don't hit this assert.

Could you make those changes:

1. Replace the IM_ASSERT() with:
```cpp
const FT_Bitmap* ft_bitmap = src_tmp.Font.RenderGlyphAndGetInfo(&src_glyph.Info);
if (ft_bitmap == NULL)
{
    printf("RenderGlyphAndGetInfo() failed for codepoint %04X\n", src_glyph.Codepoint);
    continue;
}
```

2. In `RenderGlyphAndGetInfo()` replace the error handling with:
```cpp
if (error != 0)
{
    printf("RenderGlyphAndGetInfo() failed: %X \"%s\"\n", error, FT_Error_String(error));
    return NULL;
}
```

And then report on the glyphs (which glyphs are failing and why). Thank you!

**Comment by xyc19970716** [comment]
Thank you for your reply! 
I test your code, and get many prints like this.
![image](https://user-images.githubusercontent.com/20499955/118422103-2772a680-b6f5-11eb-8015-785fcb14b71e.png)

**Comment by ocornut** [comment]
0x13 in freetype is:
```
  FT_ERRORDEF_( Cannot_Render_Glyph,                         0x13,
                "cannot render this glyph format" )
```

What happen if you load this font AS A SECOND FONT (so first font work).

Then open `Demo>Tools>Style Editor>Fonts>` then Open your font
And look at the glyphes:

![image](https://user-images.githubusercontent.com/8225057/118692054-f8018e00-b809-11eb-8669-ffedbde0a582.png)

**Comment by xyc19970716** [comment]
Thank you! But what means AS A SECOND FONT? I just load this font.

**Comment by ocornut** [comment]
If you only load this font and all glyphes are missing you won’t be able to easily use the UI and use the viewer, that’s why as a second font the UI can use default font.

**Comment by xyc19970716** [comment]
Well, for your proposal, i get so few glyphs seeing on the editor.
![image](https://user-images.githubusercontent.com/20499955/118827073-9d8e2d80-b8ee-11eb-9a9f-6ed9a4b5cfed.png)
Is my system font file broken, or the code version of FreeType wrong?

**Comment by ocornut** [comment]
Maybe try to update Freetype, you can too use vcpkg to install recent version of Freetype.

**Comment by xyc19970716** [comment]
Thanks a lot! I use FreeType by the implmentation of vcpkg, that bitmap mode works well. But my project use cmake to install freetype, maybe i get mistake and i would fix it future. 
I think this issue can be closed. Very thanks!
