### ISSUE TITLE
DirectX11 examples failing on Windows 10 (Visual Studio)

### ISSUE THREAD

**Issue by micoloth** [ocornut/imgui#415]
My Imgui visual studio project worked nicely up until yesterday, but then i made the update to windows 10 and now it doesn't anymore.
I get it's more likely a directX problem, but is it known a quick fix to this?

What happens is the console shows up, but then program exits immediatly without even creating the application window.
Specifically, debugging it shows that in this part of main function:

    if (CreateDeviceD3D(hwnd) < 0)
        {
            CleanupDeviceD3D();
            UnregisterClass(L"ImGui Example", wc.hInstance);
            return 1;
        }

the function returns 1 every time, and nothing else happens.
I dont know, I'm not really into these things... Could it work if I reinstall directX11 competely?

Thanks! (cool library anyway)

**Comment by ocornut** [comment]
Are you running the DX9 or DX11 sample? Try both.
Try to set into CreateDeviceD3D() functions with a debugger and see where it fails.

**Comment by micoloth** [comment]
So i did some further testing.. I downloaded the last version of the code from here, and ran the directX11 example (it's the only directX i have installed) right out of the box, and it had the same behaviour my project had.
Debug just shows that in 'CreateDeviceD3D', the 'D3D11CreateDeviceAndSwapChain' function somehow returns 'E_FAIL', but i can't say why.
To be completely clear, im using VS2015, and going through the process of retargeting the solution every time, so maybe this is the broken part. But it's a shame, because as I said, it worked fine before i got windows 10.

**Comment by ocornut** [comment]
I haven't installed VS 2015 yet to test and only have Windows 8.1. You are on your own for figuring out what's wrong with the device creation settings and I'd be happy to hear the result :)

I don't imagine updating the solution would have any side-effect.
Note that the DX9 example should also work out of the box.

**Comment by jgavert** [comment]
Hello, the sample D3D11 works fine for me in Windows 10, VS 2015, Windows SDK 10 (the only sdk I have installed, also provides the directx sdk these days). Directx 9 was the only sample that didn't work for me. I seem to be missing some headers, I would assume that installing the legacy directx sdk(or windows 8.1 sdk) solves this issue.

VS retargetting doesn't cause any issues for me. Also verified this by with a fresh zip of repository and just opening the solution and trying to run each project. Also remember that on windows 10 you need to install the optional feature "Graphics Tools" for directx features. You can get a popup for it by trying to launch graphics diagnostics on a project.

**Comment by TheRealMJP** [comment]
I would try commenting out line 61 in main.cpp, the one that enables the D3D11_CREATE_DEVICE_DEBUG flag when creating the device. If you do that and creating the device succeeds, then the most likely explanation is that you don't have the DX developer runtime installed on your machine. The developer runtime is now one of the "optional features" that you can enable for Windows 10, as opposed to being included with the Windows SDK: http://blogs.msdn.com/b/chuckw/archive/2015/08/05/where-is-the-directx-sdk-2015-edition.aspx

FYI, the optional features seem to go through Windows Update. So if you're going through a WSUS server on your local network (some companies do this to manage which updates get pushed to the office), you might have to bypass the server in order to download any optional features: http://rajdude.com/blog/bypass-wsus-to-install-windows-updates/

**Comment by micoloth** [comment]
Nice, I must be missing that feature, because commenting that line out the current sample actually works.
I don't know if this is a definitive solution, but i'll stick with it for now.

While i'm at, i have a couple more problems changing the code back in my old project, which was basically build on the directx11 example from a couple months ago. It looks like the `stbtt_pack_range` class is different now, and this causes some problems in imgui_draw.
Is this linked with the feature i'm missing? How do I fix this?

**Comment by ocornut** [comment]
I'll path the DX11 example.
Please clarify the problem and open a separate issue. There's 2 version of the pack one in stb_truetype one in rect_pack, the one in rect_pack is used unless you have messed up with the files/includes.
