### ISSUE TITLE
InputText losing focus inside a tab

### ISSUE THREAD

**Issue by pcsagan** [ocornut/imgui#4158]
I'm using 1.79 WIP, and I have an issue with InputText where it's not retaining focus after being clicked on if it's inside a tab. I found that if I simply hold the mouse button down, then I can type/select/delete as usual, but when I release it the focus is lost. This doesn't seem to happen if the InputText is not inside a tab.

Here's a GIF showing what I mean. The InputText in the upper window wont retain focus unless I hold the mouse button down, but the InputText in the lower window does: https://imgur.com/a/1RBbrKa

**Comment by ocornut** [comment]
Please provide a repro (as requested by issue template) and make sure your text input has a suitable ID (as described in the FAQ).

Will reopen once you can provide minimal repro code.
