### ISSUE TITLE
How to render colored emoji?

### ISSUE THREAD

**Issue by AllenDang** [ocornut/imgui#4169]
**Version/Branch of Dear ImGui:**

Version: 1.82
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Operating System: MacOS

**My Issue/Question:**

How to render colored emoji?

Here is what I've done:
1. Add #define IMGUI_USE_WCHAR32 to imconfig.h.
2. Add "Apple Color Emoji.ttc" font with minimal glyph range "⌚️<-watch 😊<-smile" to test emoji rendering.
3. Create imgui.TextUnformated("⌚️<-watch 😊<-smile")

The emoji doesn't be rendered. Do I have to change anything in the renderer or platformer to render them correctly?

**Screenshots/Video**
![截屏2021-05-24 下午6 03 55](https://user-images.githubusercontent.com/18550/119331866-6e930580-bcba-11eb-9431-87efd8bbffc5.png)

**Comment by ocornut** [comment]
Hello,

If I type "How to render colored emoji" into the search box I find #3369

![image](https://user-images.githubusercontent.com/8225057/119334310-43dd8880-bc8b-11eb-82b8-e424df94a07a.png)

The short-answer is:
- It only work with imgui_freetype rasterizer (need Freetype library)
- You need to use the `ImGuiFreeTypeBuilderFlags_LoadColor` flag.
- Not every font will work.

When you load a font and have a problem, always use Style Editor>Fonts to browse the loaded fonts data.

I will now work on updating the FONTS.md documentation and imgui_freeytpe documentation to mention this. Thank you!

**Comment by ocornut** [comment]
> I will now work on updating the FONTS.md documentation and imgui_freeytpe documentation to mention this. Thank you!

Added a new section in FONTS.md now:
https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#using-colorful-glyphsemojis

And link to it from imgui_freetype/README as well.

**Comment by AllenDang** [comment]
@ocornut Thanks for the guidance!
