### ISSUE TITLE
ImGui::ShowFontAtlas is not exported

### ISSUE THREAD

**Issue by eliasdaler** [ocornut/imgui#4171]
Version: 1.83
Branch: master
Back-ends: ImGui-SFML
Compiler: MSVC 14
OS: Windows 10

---

After https://github.com/ocornut/imgui/commit/c708299ca9705f4e1f4150c34ca6ebfd93a33bcb I got [the following linking problem](https://github.com/eliasdaler/imgui-sfml/runs/2657065450#step:14:43):

```imgui.cpp.obj : error LNK2019: unresolved external symbol "void __cdecl ImGui::ShowFontAtlas(struct ImFontAtlas *)" (?ShowFontAtlas@ImGui@@YAXPEAUImFontAtlas@@@Z) referenced in function "void __cdecl ImGui::ShowMetricsWindow(bool *)" (?ShowMetricsWindow@ImGui@@YAXPEA_N@Z)```

My understanding is that `ShowFontAtlas` is not exported, but gets called in `ShowMetricsWindow` and doesn't get inlined, that's why we get a linking error.

I guess that `IMGUI_API` should get added to it or it should be a static function which will only be used in imgui.cpp.

**Comment by ocornut** [comment]
Does adding IMGUI_API to both forward declarations fixes it? (There’s one in imgui.cpp and one in imgui_demo.cpp)
If so, could you make a PR for it? Thank you!

**Comment by ocornut** [comment]
Or, it could be that you are not linking with imgui_demo at all, i’d be interested to know if that’s the case.

**Comment by ocornut** [comment]
This is not something we normally support this way, as there’s a dedicated define for it. I’d be tempted to enforce that to ensure people keep at least the source file on disk, but I understand being a new restriction it may need to be reworked.

**Comment by ocornut** [comment]
Pushed a fix with 3a941f95e96a6718427858c700fdca02e9bb5663

Changelog says
_"Demo: Fixed requirement in 1.83 to link with imgui_demo.cpp if IMGUI_DISABLE_METRICS_WINDOW is not set. (#4171). Normally the right way to disable compiling the demo is to set IMGUI_DISABLE_DEMO_WINDOWS, but we want to avoid implying that the file is required."_

**Comment by eliasdaler** [comment]
Thanks, that fixed the problem. I didn't link to `imgui_demo.cpp`, but that shouldn't be a requirement so I glad it's fixed now. :)
