### ISSUE TITLE
Table with Radio Button/CheckBox

### ISSUE THREAD

**Issue by m21-cerutti** [ocornut/imgui#4172]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + custom OpenInventor backend
Compiler: MSVC 14.16
Operating System: Windows 10

**My Issue/Question:**
Linked to https://github.com/ocornut/imgui/issues/125.

Hello, I am trying to do a table with radio button for selectionning one item in a table.
But the problem is it don't actualise the state, and never trigger that a radio button have been clicked.
I have also tried with CheckBox and Selectionable and slight difference in code, but same result.
There is also no demo from what i have seen in this version using this particular case.

**Screenshots/Video**

![2021_05_25_13-17-07_gui2d](https://user-images.githubusercontent.com/23432929/119489147-adc56300-bd5b-11eb-99be-267690eda3fc.png)

![radio_dearimgui](https://user-images.githubusercontent.com/23432929/119489111-9be3c000-bd5b-11eb-8108-fa75f8e7c80a.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
``` Cpp
struct ImGuiParameterState
{
  int selected_radio;
};

static ImGuiParameterState state;

if (ImGui::Begin("Control Panel"))
{
  if (ImGui::BeginTable("9x9_radio_table", 3))
  {
    int i;
    for (i = 0; i < 9; i++)
    {
      ImGui::TableNextColumn();
      if (ImGui::RadioButton("", &state.selected_radio, i))
      {
        std::cout << i << std::endl; // Never called
      }
    }
    ImGui::EndTable();
  }
  
  ImGui::End();
}
```

**Comment by ocornut** [comment]
Hello,
You have not read the FAQ (which is requested by issue template)
```
Q: Why is my widget not reacting when I click on it?
Q: How can I have widgets with an empty label?
Q: How can I have multiple widgets with the same label?
```
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it

**Comment by m21-cerutti** [comment]
Oh i'm verry sorry, i have read too quickly the usage.
I think despite it can be a good example, here the modified code :
```Cpp
if (ImGui::BeginTable("9x9_radio_table", 3))
{
  for (int i = 0; i < 9; i++)
  {
    ImGui::TableNextColumn();
    std::string id = "##radio_table_" + std::to_string(i);
    if (ImGui::RadioButton(id.c_str(), &state.selected_radio, i))
    {
      int row = ImGui::TableGetRowIndex();
      int col = ImGui::TableGetColumnIndex();
      std::cout << row << ";" << col << std::endl;
    }
  }
  ImGui::EndTable();
}
```

**Comment by ocornut** [comment]
Using `PushID(i)` would be simpler and faster here.
