### ISSUE TITLE
C++20: bitwise operations are deprecated between enumerations of different types

### ISSUE THREAD

**Issue by Fedr** [ocornut/imgui#4173]
**Version/Branch of Dear ImGui:**

1.83 + docking branch

**Back-end/Renderer/Compiler/OS**

Visual Studio 2019, stdcpplatest switch on (c++20)

**My Issue/Question:**

Compilation in C++20 mode ends with a few warnings about bitwise operations deprecated between enumerations of different types
```
imgui\imgui_internal.h(1257,79): warning C5054: operator '|': deprecated between enumerations of different types
...
```

**Comment by ocornut** [comment]
Hello,
Thank you. Now fixed with 04fd5072fbc635cc7a8814b8543d40836248d3a7.
Will we add CI tasks to test C++20. Catching up with ever-changing standards and warnings is a bit of a pain :/
