### ISSUE TITLE
ImDrawList callback with custom shader

### ISSUE THREAD

**Issue by marcizhu** [ocornut/imgui#4174]
**Version/Branch of Dear ImGui:**

Version: 1.84 WIP (commit 04fd5072)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: AppleClang
Operating System: macOS

**My Issue/Question:**

I'm trying to implement some custom rendering on top of ImGui. I tried using `ImDrawList::AddCallback()` to add a callback to a function that only changes the active shader. For some reason, I can't get anything to render there. However, when I remove the line that does the `glUseProgram()` so that it uses the default shader, then it renders properly. My shader does compile OK and it is indeed the same one the OpenGL3 backend uses, but for some reason I can't get it to work.

With the example I provide, one would expect a window called "FX", with size 1000x600 and a pink rectangle inside it. And this is exactly what I get when I disable my shader and instead rely on the default one, but when I use my shader the window is completely empty.

I know this is probably a dumb mistake by my side, but I've tried everything and I can't get it to work, and it should since the shader source is identical (I literally copied & pasted it). I shouldn't get an empty window with either shader.

**Standalone, minimal, complete and verifiable example:** 

<details>
<summary>Vertex Shader source</summary>

```glsl
#version 330 core
precision mediump float;
layout (location = 0) in vec2 Position;
layout (location = 1) in vec2 UV;
layout (location = 2) in vec4 Color;

uniform mat4 ProjMtx;
out vec2 Frag_UV;
out vec4 Frag_Color;

void main()
{
    Frag_UV = UV;
    Frag_Color = Color;
    gl_Position = ProjMtx * vec4(Position.xy,0,1);
}
```
</details>

<details>
<summary>Fragment Shader source</summary>

```glsl
#version 330 core
precision mediump float;

in vec2 Frag_UV;
in vec4 Frag_Color;
layout (location = 0) out vec4 Out_Color;

void main()
{
    Out_Color = Frag_Color;
}
```
</details>

<details>
<summary>ImGui rendering code</summary>

```cpp
ImGui::Begin("FX", NULL, ImGuiWindowFlags_AlwaysAutoResize);
ImVec2 size(1000.0f, 600.0f);
ImGui::InvisibleButton("canvas", size);
ImVec2 p0 = ImGui::GetItemRectMin();
ImVec2 p1 = ImGui::GetItemRectMax();
ImDrawList* draw_list = ImGui::GetWindowDrawList();

draw_list->PushClipRect(p0, p1);
draw_list->AddCallback([](const ImDrawList*, const ImDrawCmd*)
    {
         ImDrawData* draw_data = ImGui::GetDrawData();
         float L = draw_data->DisplayPos.x;
         float R = draw_data->DisplayPos.x + draw_data->DisplaySize.x;
         float T = draw_data->DisplayPos.y;
         float B = draw_data->DisplayPos.y + draw_data->DisplaySize.y;

         const float ortho_projection[4][4] =
         {
            { 2.0f/(R-L),   0.0f,         0.0f,   0.0f },
            { 0.0f,         2.0f/(T-B),   0.0f,   0.0f },
            { 0.0f,         0.0f,        -1.0f,   0.0f },
            { (R+L)/(L-R),  (T+B)/(B-T),  0.0f,   1.0f },
         };

         glUseProgram(shaderID); // If I remove this line, it works
         glUniformMatrix4fv(glGetUniformLocation(shaderID, "ProjMtx"), 1, GL_FALSE, &ortho_projection[0][0]);
    }, nullptr);

draw_list->AddRectFilled(p0, p1, 0xFFFF00FF);
draw_list->AddCallback(ImDrawCallback_ResetRenderState, nullptr);
draw_list->PopClipRect();

ImGui::End();
```
</details>

**Comment by ocornut** [comment]
At this point you’d understand that your question is an OpenGL question and not much of a Dear ImGui question. If they are other OpenGL states you rely on or not rely on you should set them.

You can use glGetError() and shader compilation reports to try to track on what is wrong in your code, perhaps the shaders haven’t been built or linked correctly. OpenGL _is_ a tricky mess in general but I am afraid there’s not much we can do here unfortunately. When you resolve it maybe posting the answer can be useful to others!

**Comment by marcizhu** [comment]
> If they are other OpenGL states you rely on or not rely on you should set them.

That's the thing, I don't rely on anything that changes the OpenGL state or anything. This is just like a small test program I've built with the code I provided.

I tried running `glGetError()` after each OpenGL command and all of them return `GL_NO_ERROR` and I specifically investigated the case that my shader is not compiling/linking properly.

After everything that I've tested I really have no clue on what is wrong. All I do is literally change the active shader _for another with the same code_...

I was hoping maybe you guys could give me some insight in what could be the issue here. Anyways, if I found out a fix for this, I will let you all know in case it is useful to anyone :)

**Comment by ocornut** [comment]
Have you tried using a graphics debugger like RenderDoc?

**Comment by marcizhu** [comment]
I'm on macOS now and sadly RenderDoc doesn't work on this platform. I will try using it tomorrow on Linux. Thanks for the tip :D

**Comment by PathogenDavid** [comment]
Your shaders and example code are working for me on Windows:

![image](https://user-images.githubusercontent.com/278957/119782456-d5b6e280-be91-11eb-9917-f89b601fbcbb.png)

(My square is red because I modified the shader to remove the blue channel just to show it's definitely being used.)

The only code I wrote was the shader compilation since you didn't show that. [Here's my full modified `example_glfw_opengl3` if you want to compare.](https://github.com/PathogenPlayground/imgui/commit/26d78ffb75d1907e4dc4145c891bb9059e79754b)

**Comment by PathogenDavid** [comment]
Did you check if there's any shader compilation errors printed to the terminal?

One thing that stands out to me is that the default vertex shader used by the OpenGL3 backend [does not explicitly specify the locations of the vertex attributes](https://github.com/ocornut/imgui/blob/04fd5072fbc635cc7a8814b8543d40836248d3a7/backends/imgui_impl_opengl3.cpp#L585-L587). (Presumably because specifying the location was added in newer versions of GLSL.) I assumed they'd have the same locations, but I wonder if this means the shader compiler is free to arrange them however it pleases. It might be worth comparing the values of `g_AttribLocationVtx*` and `glGetAttribLocation` with your shader in the debugger to see if they match.

**Comment by marcizhu** [comment]
> Did you check if there's any shader compilation errors printed to the terminal?

Yep, there are no errors on the terminal. I runned your code on Linux and it works no problem.

> One thing that stands out to me is that the default vertex shader used by the OpenGL3 backend does not explicitly specify the locations of the vertex attributes. [...]  I wonder if this means the shader compiler is free to arrange them however it pleases. It might be worth comparing the values of g_AttribLocationVtx* and glGetAttribLocation with your shader in the debugger to see if they match.

Indeed, on macOS I've got 1, 2 and 0 for the position, UV and color locations but my shader expects them to be 0, 1 and 2 respectively. When I change the attribute locations, this is what I get (finally!):

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/6199781/119802414-cdd15f80-bede-11eb-8d59-439ccbb42095.png">

Thank you so much! From here it should be easy to fix this :D

**Comment by ocornut** [comment]
OSX has specific constraint with OpenGL. The OSX path of example always use 3.2 Core with Forward Compat.

**Comment by PathogenDavid** [comment]
> The OSX path of example always use 3.2 Core with Forward Compat.

It uses 3.2 Core, but it uses the GLSL version string `#version 150`, which unless I'm missing something ends up using [`vertex_shader_glsl_130`](https://github.com/ocornut/imgui/blob/79e18896fee8c28f6dae0750b1e808c1b27d7807/backends/imgui_impl_opengl3.cpp#L583-L595) (which does not have attribute locations.)
