### ISSUE TITLE
Docking imgui, moveing rounding window out of the main window, will disable the rounding

### ISSUE THREAD

**Issue by willian12** [ocornut/imgui#4180]
When rounding windows is in the main window, everything is ok!
![1](https://user-images.githubusercontent.com/4452327/120085747-50d7fd00-c10d-11eb-9f22-577b30aebfeb.png)
But when I drag  the rounded corner window out of the main window, the rounded corner window becomes right-angled window.
![2](https://user-images.githubusercontent.com/4452327/120085824-ed9a9a80-c10d-11eb-978e-460a6d664396.png)
Is there any way to make the window corner always rounded?

**Comment by ocornut** [comment]
It’s not possible to have rounded windows as standalone secondary viewports, no.

**Comment by willian12** [comment]
> It’s not possible to have rounded windows as standalone secondary viewports, no.

Anyway, thanks alot!

**Comment by willian12** [comment]
> It’s not possible to have rounded windows as standalone secondary viewports, no.

But I think nothing is impossible.

**Comment by ocornut** [comment]
Nothing is impossible but fixes and features are competing for attention
.
It would requires interaction with the compositor and input+render transparency support (e.g. see comment https://github.com/ocornut/imgui/pull/2766#issuecomment-781335628). Perhaps some day we will.
