### ISSUE TITLE
IM_FMTARGS attributes not enabled for GCC on Linux

### ISSUE THREAD

**Issue by audetto** [ocornut/imgui#4183]
I am using the (as of now) latest version of ImGui,

https://github.com/ocornut/imgui/blob/79e18896fee8c28f6dae0750b1e808c1b27d7807/imgui.h#L95

Format warning are **not** enabled for GCC on Linux.

I was reading https://github.com/ocornut/imgui/issues/3592 and I believe excluding gcc was an unintentional side effect?

**Comment by ocornut** [comment]
Hello Andrea,
You are right. I've reworked the #ifdef block now. Thank you!
It becames
```
#if !defined(IMGUI_USE_STB_SPRINTF) && defined(__MINGW32__)
#define IM_FMTARGS(FMT)             __attribute__((format(gnu_printf, FMT, FMT+1)))
#define IM_FMTLIST(FMT)             __attribute__((format(gnu_printf, FMT, 0)))
#elif !defined(IMGUI_USE_STB_SPRINTF) && (defined(__clang__) || defined(__GNUC__))
#define IM_FMTARGS(FMT)             __attribute__((format(printf, FMT, FMT+1)))
#define IM_FMTLIST(FMT)             __attribute__((format(printf, FMT, 0)))
#else
#define IM_FMTARGS(FMT)
#define IM_FMTLIST(FMT)
#endif
```
(Based on the test and discussions in #3592 that gnu_printf is only required on MinGW32)
