### ISSUE TITLE
IsAnyItemHovered does not recognize the selected combo item after the combo dropdown has been clicked

### ISSUE THREAD

**Issue by Dvay** [ocornut/imgui#4188]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11cpp + imgui_impl_win32.cpp 
Compiler: Visual Strudio 2019
Operating System: Windows 10

**My Issue/Question:**

Im using ImGui::IsAnyItemHovered() and ImGui::IsMouseClicked() to checkwether the mouse is over an item the moment a left-click occurs. This is working for all items (sliders,checkboxes,buttons, and also combo-items). 

But **after** clicking a combo to open the dropdown list, the **current** selected item does not get recognized from IsAnyItemHovered() anymore (IsAnyItemHovered() returns false). While for all other combo items IsAnyItemHovered() still returns true.

I want to especially underline that it only does not work **after** the combobox is clicked and the dropdown list is **displayed**. If the box is closed, it is recognized correctly here.

**Screenshots/Video**

![imguibug](https://user-images.githubusercontent.com/5575161/120332081-ae776f80-c2ee-11eb-8f4a-ba558490a23a.png)

// Here's some code anyone can copy and paste to reproduce the issue
```
const char* items[] = { "Test0", "Test1", "Test2", "Test3" };
static int item_current = 0;

while(true) {
if (ImGui::IsAnyItemHovered())
     std::cout << "Item has been hovered" << std::endl;
     
ImGui::Begin("Example Bug");

ImGui::Combo("TestCombo", &item_current, items, IM_ARRAYSIZE(items));

ImGui::End();
}
```
```

**Comment by ocornut** [comment]
I suppose there's an ambiguity with what `IsAnyItemHovered()` does. 
When a popup is open is tends to block inputs on windows behind it.
`isAnyItemHovered()` will return true on accessible items.

The main and central question to avoid a [XY Problem](https://xyproblem.info/) is:

> Im using ImGui::IsAnyItemHovered() and ImGui::IsMouseClicked() to checkwether the mouse is over an item the moment a left-click occurs. 

Please explain precisely why you are using it and how you are using it.

**Comment by Dvay** [comment]
Hi,

im doing that because i want to hide all open windows if  i leftclick on anything but an item/window. So basically when i click on the "backend" - window i want to hide everything. There might be another approach but im new to imgui and that was the way i took. 

This approach works, but it also "hides" everything if i click on the combo as described above. 

for the sake of completeness:
im also checking for "isWindowHovered()", but this also returns false when hovering over the combobox. At least with this method, i would assume that it would always have to be true as long as my mouse position is between the edges of an imgui window.

**Comment by willian12** [comment]
> Hi,
> 
> im doing that because i want to hide all open windows if i leftclick on anything but an item/window. So basically when i click on the "backend" - window i want to hide everything. There might be another approach but im new to imgui and that was the way i took.
> 
> This approach works, but it also "hides" everything if i click on the combo as described above.
> 
> for the sake of completeness:
> im also checking for "isWindowHovered()", but this also returns false when hovering over the combobox. At least with this method, i would assume that it would always have to be true as long as my mouse position is between the edges of an imgui window.

I think you can solve the issues bypass the imgui,

**Comment by Dvay** [comment]
> > Hi,
> > im doing that because i want to hide all open windows if i leftclick on anything but an item/window. So basically when i click on the "backend" - window i want to hide everything. There might be another approach but im new to imgui and that was the way i took.
> > This approach works, but it also "hides" everything if i click on the combo as described above.
> > for the sake of completeness:
> > im also checking for "isWindowHovered()", but this also returns false when hovering over the combobox. At least with this method, i would assume that it would always have to be true as long as my mouse position is between the edges of an imgui window.
> 
> I think you can solve the issues bypass the imgui,

what do you mean by "bypass the imgui" ?

**Comment by willian12** [comment]
> > > Hi,
> > > im doing that because i want to hide all open windows if i leftclick on anything but an item/window. So basically when i click on the "backend" - window i want to hide everything. There might be another approach but im new to imgui and that was the way i took.
> > > This approach works, but it also "hides" everything if i click on the combo as described above.
> > > for the sake of completeness:
> > > im also checking for "isWindowHovered()", but this also returns false when hovering over the combobox. At least with this method, i would assume that it would always have to be true as long as my mouse position is between the edges of an imgui window.
> > 
> > 
> > I think you can solve the issues bypass the imgui,
> 
> what do you mean by "bypass the imgui" ?

And what 

> It looks like you want to use the io.WantCaptureMouse flag. Just display it using a ImGui::Text() call or printf and you’ll see it fits what you need. https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application

What he said  also can solve your problem , and easier.

**Comment by Dvay** [comment]
> It looks like you want to use the io.WantCaptureMouse flag. Just display it using a ImGui::Text() call or printf and you’ll see it fits what you need. https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application

ty gonna check that
