### ISSUE TITLE
Tab bar for multiple dockspaces

### ISSUE THREAD

**Issue by ToniPlays** [ocornut/imgui#4189]
Hi!

Would it be possible to add support for multiple dock spaces so that they could be used like Chrome tabs? Could have one or more window that could be docked like normal but only as a fullscreen one.  Then you could change between them or even drag one out to another display. Using tabs would allow working on multiple things without messing with too many windows at the same time, filling the whole UI. Sort of like Chrome where every tab contains its own dock space and is like a website. Then you could switch between them

I have tried to create this a few times already, always failing badly.

**Comment by ocornut** [comment]
Hello,

I am not sure I understand what is your problem, what you have tried and what failed. You are ignoring the requests of the issue guidelines by omitting to provide more context.

You can create multiple dockspaces and have one in each tabs of a parent dockspace. A frequent mistake is that dockspace that are not visible need to be kept alive. See #2720 and #2599.

If you have one parent dockspace using other ones, you may also want to use SetNextWindowClass() to restrict which windows can dock into which tab.

**Comment by ocornut** [comment]
I have pushed a little bit of extra commentary on using the `KeepAliveOnly` flag:
f53db3541afb638e230ba34292816714e0c93bc7
This is assuming I correctly understood your question. Let me know!

**Comment by ocornut** [comment]
Closing this but adding further references/links, which might or not be helpful.

#4815 

Also see this more complex example (this is quite elaborate/complicated as it does layout fork and copying)
https://github.com/ocornut/imgui/issues/2109#issuecomment-459409449
