### ISSUE TITLE
Missing __cplusplus check in stb_textedit.h ?

### ISSUE THREAD

**Issue by zryan3** [ocornut/imgui#419]
I wasn't sure if the
```c++
#ifdef __cplusplus
extern "C" {
#endif
```

and

```c++
#ifdef __cplusplus
}
#endif
```

is supposed to be in the stb_textedit.h file to prevent name mangling? Although I noticed it is not in the official [stb_textedit.h repo](https://github.com/nothings/stb/blob/master/stb_textedit.h) either. I was wondering if this is intentional or an oversight as it seems present in every other STB header.

**Comment by ocornut** [comment]
is that causing a problem? All the symbols are static to imgui.cpp anyway.

**Comment by zryan3** [comment]
No, I guess it just didn't feel symmetrical. Feel free to close this issue.

**Comment by ocornut** [comment]
It could probably be fixed but then it needs to be reported on STB's github. Thanks!
