### ISSUE TITLE
ImGui::ColorEdit4 ImGuiColorEditFlags_PickerHueWheel trembling

### ISSUE THREAD

**Issue by Grantim** [ocornut/imgui#4192]
```
Dear ImGui 1.84 WIP (18302)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=202004
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,256
io.DisplaySize: 1280.00,800.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 5.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```
Brunch: docking
Commit hash: 1ad1429c6df657f9694b619d53fa0e65e482f32b

Dear ImGui,

I have faced problem when picking color via ImGuiColorEditFlags_PickerHueWheel. Please help to stop it!

![2021-06-02_18h17_49](https://user-images.githubusercontent.com/10034350/120507092-2fa63380-c3cf-11eb-90e3-2cfa1ddcc78b.gif)

**Comment by ocornut** [comment]
Hello,
You are not providing enough details. This requires at least some repro code. 
Please read the Issue Guidelines again, edit this post and we can reopen this.

**Comment by ocornut** [comment]
To clarify, manipulating the hue wheel in demo doesn't exhibit the issue you are showing, so the burden of creating a repro in on you otherwise we don't have enough data to understand the issue.

Perhaps your code uses back and forth between float4 and packed u32? which combined with the RGB<>HSV roundtrips may triggers issues. If that's the indeed case it would be good to know the details, and see if we can aim to improve something in the picker.

**Comment by Grantim** [comment]
As you say demo do not behave that way. Here is some examples of code that triggers issue and not:

```c++
struct Color4u
{
    // [0-255]
    uint8_t r,g,b,a;
};

struct Color4f
{
    // normalized [0-1]
    float r,g,b,a;
};

void trembles()
{
    static Color4u coloru{uint8_t(0),uint8_t(0),uint8_t(0),uint8_t(0)};
    Color4f colorf{ float(coloru.r)/255.0f, float(coloru.g)/255.0f, float(coloru.b)/255.0f, float(coloru.a)/255.0f };
    ImGui::ColorEdit4( label, &colorf.r, ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_PickerHueWheel );
    coloru = { uint8_t(255*colorf.r), uint8_t(255*colorf.g), uint8_t(255*colorf.b), uint8_t(255*colorf.a) };
}

void not_trembles()
{
    static Color4f colorf{0.0f,0.0f,0.0f,0.0f};
    ImGui::ColorEdit4( label, &colorf.r, ImGuiColorEditFlags_NoInputs | ImGuiColorEditFlags_PickerHueWheel );
}
```
So you are right the thing is type conversions.

**Comment by ocornut** [comment]
Try using the float<>packed32 functions of dear imgui they may be more precise.

**Comment by Grantim** [comment]
I have tried it, unforchantly it does not help. As I see internal data of `Hue Wheel` expects the same floats each frame to stay stable, so simple workaround of storing colors in float while `Picker` is active works good for me.

**Comment by ocornut** [comment]
I believe maybe 30546bc0e7bccbebda0e328780e48bc95af3ae2c fixed some of those issues?
