### ISSUE TITLE
example_glfw_opengl2 and opengl3 build bug MT

### ISSUE THREAD

**Issue by budibeta** [ocornut/imgui#4195]
both opengl2 and opengl3 = MT
![Screenshot_2](https://user-images.githubusercontent.com/68463485/120569378-fbb72680-c43f-11eb-9de8-d227f8d82621.png)

both opengl2 and opengl3 = MD
![Screenshot_3](https://user-images.githubusercontent.com/68463485/120569413-0ec9f680-c440-11eb-9321-3635d1af9503.png)

i hate MD, i love MT

are you know why ?, i knew it, i will explain it
**glfw3.lib(win32_window.obj) : error LNK2001: unresolved external symbol __imp___strdup
1>glfw3.lib(win32_joystick.obj) : error LNK2001: unresolved external symbol __imp___strdup
1>glfw3.lib(monitor.obj) : error LNK2001: unresolved external symbol __imp___strdup
1>glfw3.lib(win32_monitor.obj) : error LNK2001: unresolved external symbol __imp__realloc**

because you, **dear imgui owner**  doesnt build **glfw3.lib** with MT option.
**you only build glfw3.lib with MD option but not MT**, so user will fail when they build with MT
i hope you fix it, thanks.

**Comment by ocornut** [comment]
We provide old binaries of glfw as a convenience but if you build your own app you should obtain GLFW yourself (eg: via vcpkg). So we don’t expect that settings of examples be changed this way.
