### ISSUE TITLE
Mouse release on breakpoint under Linux

### ISSUE THREAD

**Issue by ProtoByter** [ocornut/imgui#4197]
**Version/Branch of Dear ImGui:**

Version: a640d8a6d2bfd2e8f125c1dc72594543808ecddf (git commit)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp 
Compiler: GCC 11.1.0
Operating System: Linux (Arch)

**My Issue/Question:**

When I'm trying to debug my application, I sometimes get a segfault when changing a slider, my ide picks up on this, sets a breakpoint and shows me what went wrong
The mouse isn't released though, and I have to ALT+TAB to the window, press ALT-F4 and wait for KDE to ask if I want to terminate the app since it isn't responding, and then press enter

Would it be possible to detect this and release the mouse?

**Screenshots/Video**

https://user-images.githubusercontent.com/20995169/120769453-0e4f5f80-c515-11eb-9b4e-92a830abbf9b.mp4

**Standalone, minimal, complete and verifiable example:**
```
// Here's some code anyone can copy and paste to reproduce your issue
bool changedX, changedY, changedZ, changedW;
changedX = ImGui::SliderScalar("X",ImGuiDataType_U8,&curPos.x,&min, &max, "%d");
changedY = ImGui::SliderScalar("Y",ImGuiDataType_U8,&curPos.y,&min, &max, "%d");
changedZ = ImGui::SliderScalar("Z",ImGuiDataType_U8,&curPos.z,&min, &max, "%d");
changedW = ImGui::SliderScalar("W",ImGuiDataType_U8,&curPos.w,&min, &max, "%d");
if ((changedX || changedY || changedZ || changedW) && (interp.space.size()-1 <= curPos.w)) {
            curColour = interp.space[curPos.w][curPos.x][curPos.y][curPos.z]; // Segfaults here but I can't debug it
}
```

**Comment by ocornut** [comment]
Hello,
I believe this has been discussed in #3650
In particular this comment:
https://github.com/ocornut/imgui/issues/3650#issuecomment-805644268

**Comment by ProtoByter** [comment]
Oh sorry I didn't see that

**Comment by ocornut** [comment]
I just relabeled #3650 to increase discoverability, would be good to do another action but I'm not sure what. 
Maybe have a standardized way to request backend to not capture mouse (which is problematic for drag and drop operations)..
