### ISSUE TITLE
PushStyleColor for Selectable inside For Loop only colors first item

### ISSUE THREAD

**Issue by samygarcia** [ocornut/imgui#4199]
**Version/Branch of Dear ImGui:**

Version: v1.75 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: Filament
Operating System: web, cross-compiled to WASM

**My Issue/Question:**

I'm making a console log, and would like the background of each log to be color-coded depending on their type. I have a for loop going through all of the logs and making a Selectable for each log. However it only colors the first log in the loop. I've tried putting each selectable in their own window, and calling PushStyleColor before the window and PopStyleColor after the window end (as well as trying to call it inside the window). However, nothing seems to work. Any ideas how this works? Thanks!

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/72455300/120851612-0f998000-c547-11eb-94e1-871dbff319f9.png)

**Example Code:** 
```
ImGui::ListBoxHeader(
        "", (filter_log_) ? log_settings_[filter_by_].count : all_logs_.size());
    for (int i = 0; i < all_logs_.size(); ++i) {
      if (filter_log_ && all_logs_.at(i).output_kind != filter_by_) {
        continue;
      }
      ImGui::Image(
          log_settings_[all_logs_.at(i).output_kind].icon->GetTexture(),
          kLogImageSize);
      ImGui::SameLine();
      ImGui::PushStyleColor(
          ImGuiCol_Header,
          log_settings_[all_logs_.at(i).output_kind].background_color);
      ImGui::Selectable(all_logs_[i].message.c_str(),
                        (i == selected_item_index_));
      ImGui::PopStyleColor();
    }
    ImGui::ListBoxFooter();
```

**Comment by PathogenDavid** [comment]
[`ImGuiCol_Header` is only used when the item is selected.](https://github.com/ocornut/imgui/blob/v1.75/imgui_widgets.cpp#L5686-L5691) (Also note that it also might use `ImGuiCol_HeaderActive` or `ImGuiCol_HeaderHovered` if the item is held/hovered.)

Unless selected or hovered, `Selectable` widgets do not have a background at all. (The background you do see is from the containing list box.)

**Comment by ocornut** [comment]
In addition, you issue here was an ID conflict which would be solved with surrounding your loop body with `PushID(i) / PopID()`.

See FAQ entry:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system
