### ISSUE TITLE
InputText should handle enter key

### ISSUE THREAD

**Issue by xythobuz** [ocornut/imgui#42]
I'm trying to execute a command entered into an InputText when the user presses the enter key, but it doesn't seem to be possible.

InputText could return true not only if the text changed, but also if enter was pressed. Or a bool\* or callback parameter could be added.

**Comment by xaxxon** [comment]
Did anything ever come of this?  I want to write a mini-shell that runs the command typed in when enter is pressed but I'm not seeing anything.

**Comment by ocornut** [comment]
There is a flag ImGuiInputTextFlags_EnterReturnsTrue to do that.

**Comment by xaxxon** [comment]
thank you
