### ISSUE TITLE
How do i hook DirectDraw? Custom backend.

### ISSUE THREAD

**Issue by whiskasdietgirl** [ocornut/imgui#4203]
I'm a bit of a beginner and I love imgui. 
I worked a bit with Imgui on directx9. 
And there is this silly old game that i love and i want to mod using imgui that uses DirectDraw.
However i dont know anything about how to hook a custom backend that is not supported.
I'm willing to spend the time and effort to learn it, but i need resources or tutorials to understand how to do it.

Could you please help me, or provide me with the materials, keywords or links that i need to review?
Thank you.

**Comment by youneuoy** [comment]
> I'm a bit of a beginner and I love imgui.
> I worked a bit with Imgui on directx9.
> And there is this silly old game that i love and i want to mod using imgui that uses DirectDraw.
> However i dont know anything about how to hook a custom backend that is not supported.
> I'm willing to spend the time and effort to learn it, but i need resources or tutorials to understand how to do it.
> 
> Could you please help me, or provide me with the materials, keywords or links that i need to review?
> Thank you.

@whiskasdietgirl, maybe something like this will help: [DirectDraw-to-Direct3D9-Conversion](https://github.com/elishacloud/dxwrapper/wiki/DirectDraw-to-Direct3D9-Conversion)
I think this would be the most convenient option for you now.

**Comment by ocornut** [comment]
You could also technically use a software renderer but it may be a bit slow:
https://github.com/ocornut/imgui/wiki/Useful-Extensions#software-rendererrasterizer
