### ISSUE TITLE
Mismatching io.KeyCtrl/io.KeyShift/io.KeyAlt/io.KeySuper vs io.KeyMods

### ISSUE THREAD

**Issue by chadmortimer** [ocornut/imgui#4204]
With reference to fix https://github.com/ocornut/imgui/commit/3600ceb527bc4877691d5679f45292852932a115

I seem to be having a similar issue which this fix doesn't help with.

I have implemented my own Dear imgui bindings for libmatoya (https://github.com/matoya/libmatoya) and everything is working well except for this issue. The way things are constructed with matoya - I have separate event, render and app threads. My ImGui_ImplMTY_ProcessEvent is positioned inside the event thread (first few lines)

 Occasionally when releasing modifier keys (for some shortcuts that I have in my app) I get this error. Presumably the events are firing mid-frame due to the asynchronous nature of my app and triggering
 
Are there any other suggestions to overcome this issue?

**Comment by ocornut** [comment]
Simply speaking you should not pass/process inputs events (write to io. fields) mid-frame. None of dear imgui is designed to be threaded.

If your events are coming in a thread, store them somehow and process them before your next call to NewFrame().

**Comment by ocornut** [comment]
By the way that statement is incorrect:

> and everything is working well except for this issue

Many more things are probably behaving incorrectly but that asserts is the only explicit failure point you are encountering.

If anything, we should be adding more checks (for other inputs fields) to reduce situations like that, but the checks of key modifiers is usually enough and triggers easily.

**Comment by chadmortimer** [comment]
Thank you for the fast response.

My statement regarding everything else working well is merely an observation of the behaviour of my app while testing the functionality. I moved over from SDL to Matoya and I had a number of other issues which I've worked through; and this was just the next issue that I have encountered. There may very well be other sticking points but so far this is the only one that I have not fixed.

Anyway, I will have to see whether I can queue up the events somehow and then process them from my render thread prior to the start of any rendering. Thank you for the suggestion.

BTW would you consider updating your bindings for libmatoya? I would be willing to forward the work that I have done so far as a contribution.

**Comment by chadmortimer** [comment]
Issue resolved using queuing of events.

Compliments of Mataya group - merton NES / libretro frontend project providing some guidance-> https://github.com/matoya/merton
