### ISSUE TITLE
Ability to disable automatic setting of MousePos & DisplaySize

### ISSUE THREAD

**Issue by TylerTheFox** [ocornut/imgui#4210]
Allow the program / game to handle mouse input itself due to different input methods, speeds / acceleration.  This can cause, for example, the mouse in ImGui to go out of sync with the game. 

The method I used before was to just set hwnd to nullptr.  However, since a few update ago that is now checked with an assert at least in the win32 impl with `IM_ASSERT(g_hWnd != 0)`; in ImGui_ImplWin32_UpdateMousePos. 

Before frame begin we manually update the mouse position like
```
  // Update mouse
  auto & io = ImGui::GetIO();
  const auto & mpos = Input::getMouseXY();
  io.MousePos.x = mpos->X;
  io.MousePos.y = mpos->Y;
```

A workaround would be to update the mouse immediately after calling `ImGui_ImplWin32_NewFrame();`, but I think a better solution would be to have a flag / define to disable it.

**Comment by TylerTheFox** [comment]
A similar issue occurs with `ImGui_ImplWin32_NewFrame()` where it updates the DisplaySize automatically. 

```
  // Setup display size (every frame to accommodate for window resizing)
  RECT rect = { 0, 0, 0, 0 };
  ::GetClientRect(g_hWnd, &rect);
  io.DisplaySize = ImVec2((float)(rect.right - rect.left), (float)(rect.bottom - rect.top));
```

This causes issues with some of our graphics modes especially stretched mode. We have a custom method of setting DisplaySize depending on the graphics mode. This wasn't an issue recently until `IM_ASSERT(g_hWnd != 0); ` was added to `ImGui_ImplWin32_NewFrame();` forcing us to set the hwnd. 

There is no workaround for this issue over than putting the DisplaySize code above `ImGui_ImplWin32_NewFrame();` then commenting out the setup display in the win32 impl.

**Comment by ocornut** [comment]
For both I think you can simply overwrite the value after calling ImGui_ImplWin32_NewFrame(), I don’t see harm doing that.

**Comment by TylerTheFox** [comment]
You're right. I don't think I did a clean build after testing the second one. 

Seems to work, still might be nice to have a documented / standard way of doing it.

**Comment by ocornut** [comment]
Well you are using the win32 half-way this is quite unusual so either way there’s no guarantee this will work forever. Long term if there are changes you can probably just avoid calling Win32_NewFrame() and do what you need yourself.

**Comment by TylerTheFox** [comment]
I guess you're right considering all the functionality of Win32_NewFrame() is already implemented in the game engine anyways and can just be setup without calling it. Maybe this issue will  be useful to someone in the future /shrug.

**Comment by ocornut** [comment]
All the issues are useful this is why we encourage this instead of transient medium such as discord, and we make an effort to label and cross-references issues.
