### ISSUE TITLE
Docking: crash while pressing arrow keys and trying to drag a window (once again?)

### ISSUE THREAD

**Issue by Vuhdo** [ocornut/imgui#4211]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: docking (1.83 merge-in commit)

**Back-end/Renderer/Compiler/OS:**

Back-ends: imgui_impl_dx11.cpp 
Compiler: VS2019
Operating System: Windows 10

**My Issue/Question:**

I believe I have the same problem as reported in https://github.com/ocornut/imgui/issues/3025:

- Build and run `example_win32_directx11`.
- Focus on **Dear ImGui Demo** window.
- Press the `Down` arrow key and almost immediately after try to move the window (i.e. clicking on its title or any empty area).

~~~ C++
example_win32_directx11.exe!ImGui::BeginDockableDragDropSource(ImGuiWindow * window) Line 15570	C++
example_win32_directx11.exe!ImGui::Begin(const char * name, bool * p_open, int flags) Line 6834	C++
example_win32_directx11.exe!ImGui::ShowDemoWindow(bool * p_open) Line 357	C++
example_win32_directx11.exe!main(int __formal, char * * __formal) Line 131	C++
~~~

~~~ C++
...
void ImGui::BeginDockableDragDropSource(ImGuiWindow* window)
{
    ImGuiContext& g = *GImGui;
    IM_ASSERT(g.ActiveId == window->MoveId);     // <--------------- ASSERTS
    IM_ASSERT(g.MovingWindow == window);

    window->DC.LastItemId = window->MoveId;
    window = window->RootWindowDockTree;
    IM_ASSERT((window->Flags & ImGuiWindowFlags_NoDocking) == 0);
   ...
~~~

**Screenshots/Video**

https://user-images.githubusercontent.com/7080284/121392916-41f11600-c969-11eb-96a6-bae40bf6fad3.mp4

**Comment by ocornut** [comment]
Hello, 

I've pushed a better fix for this and #3025
Commit: db0338a1f2b1f0b05f910888222cacd17fec26e8
They were two race conditions involved (+ marked a place in docking code that may need less duplication)

Thanks for reporting!
