### ISSUE TITLE
Multiple viewports not merged if something has active focus.

### ISSUE THREAD

**Issue by magcius** [ocornut/imgui#4212]
**Version/Branch of Dear ImGui:**

```
Dear ImGui 1.80 (18000)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_DEFAULT_ALLOCATORS
define: _WIN32
define: _WIN64
define: _MSC_VER=1928
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: Propeller
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigDockingAlwaysTabBar
io.ConfigDockingTransparentPayload
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C02
 HasMouseCursors
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1553.00,825.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 1.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom backend on top of SDL2, Win32
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

I'm looking into issues in a work-in-progress game related to window resizing and platform window generation. I'm still narrowing things down, but I've found a weird behavior I believe is a bug. Viewports are only merged if `g.ActiveId == 0`:

https://github.com/ocornut/imgui/blob/db0338a1f2b1f0b05f910888222cacd17fec26e8/imgui.cpp#L11924-L11928

 I believe this intended to prevent a window from disappearing if it has focus, but since the ActiveId tracks global focus, windows are not merged. This seems wrong to me.

**Standalone, minimal, complete and verifiable example:**

This can be reproduced from the ImGui demo:

1. Open the Log example and About Dear ImGui window.
2. Drag the About Dear ImGui window to the side so that a new platform window is created.
3. Click in the Filter textbox on the Log example so that it gains focus.
4. Resize the parent window to be larger so that it now fully encompasses the About Dear ImGui window.
5. Expect it to be absorbed into the parent viewport, but it is not.
6. Click elsewhere to make the Filter textbox loses focus, and watch the About Dear ImGui get absorbed into the parent window.

**Comment by ocornut** [comment]
Hello,
Thanks for the report.

I think this was generally meant to avoid interference in some situations, e.g. while resizing down a window it won't merge immediately. Maybe other situations would be affected (using widgets which have effects on windows, drag and dropping).
The initial commit that added this test was 25f25d546d360a7653772fc712ee20c19f8048d5

`InputText()` holding on setting `ActiveId` is a bit of an exception. Technically testing `ActiveIdAllowOverlap` would detect this case, though it is a bit unfortunately obscure it is consistent with how we normally manage this so it may be a good fix. (and maybe `ActiveIdAllowOverlap` should be renamed or split into multiple distinct and explicit properties that happens to be set by `InputText`..)

**Comment by ocornut** [comment]
I pushed a "fix" for that.
It is a bit flaky but for lack of better data this is at least generally consistent with how we use those fields (added link back to this place to facilitate further reference for when we ever reevaluate that).

Thanks again!

**Comment by ocornut** [comment]
I pushed a "fix" for that.
It is a bit flaky but for lack of better data this is at least generally consistent with how we use those fields (added link back to this place to facilitate further reference for when we ever reevaluate that).

Thanks again!
