### ISSUE TITLE
Having buttons on the same line

### ISSUE THREAD

**Issue by Lester702** [ocornut/imgui#4213]
I was looking for a way to have buttons on the same line and came across https://github.com/ocornut/imgui/issues/934
Being that it's so old has the issue been fixed?
Edit: I'm also having the same issue

**Comment by ocornut** [comment]
Hello Lester,
Please clarify exactly what you need.

**Comment by Lester702** [comment]
> Hello Lester,
> Please clarify exactly what you need.

So right now the buttons are setup like this
![image](https://user-images.githubusercontent.com/63370028/121540764-bf9e3b80-c9d4-11eb-8f5a-eea640820d8b.png)
I want to have the buttons next to each other not below each other

**Comment by ocornut** [comment]
You can call `ImGui::SameLine()` between buttons. 
This is well demonstrated in many places in the Demo Window. 
When looking for something always explore the demo.
