### ISSUE TITLE
How do i change the opacity of a texture dynamically?

### ISSUE THREAD

**Issue by whiskasdietgirl** [ocornut/imgui#4214]
Maybe this isn't related to dear imgui and can only be done through directx.
The only way i have to change the opacity of a texture is by changing it in photoshop, saving it as a png.
And thats how i have been doing.

But what if i want to make an effect that fades in/fades out my image?
Is that possible? Or thats something not yet explored?

The ImGui::SetNextWindowBgAlpha(0.00F); is great for windows and does that effect. But it doesnt get applied to the images :(.
Im trying to make an image fade in slowly into a background. And then fade out.

**Comment by ocornut** [comment]
When drawing an image with `ImGui::image()` or `ImDrawList::AddImage()` you pass in a color mulitplier and altering the alpha component will alter opacity.

```cpp

static ImVec4 color_multipler(1, 1, 1, 1);

ImGui::Begin("DirectX11 Texture Test");
ImGui::Text("pointer = %p", my_texture);
ImGui::Text("size = %d x %d", my_image_width, my_image_height);

ImGui::ColorEdit4("color_multiplier", &color_multipler.x);

ImGui::Image((void*)my_texture, ImVec2((float)my_image_width, (float)my_image_height), ImVec2(0.0f, 0.0f), ImVec2(1.0f, 1.0f), color_multipler);
ImGui::End();
```

![image tinting](https://user-images.githubusercontent.com/8225057/121528430-be343980-c9fb-11eb-8706-68ae8f84f0f3.gif)
