### ISSUE TITLE
Rotated text

### ISSUE THREAD

**Issue by MrSmith33** [ocornut/imgui#422]
Is there an easy way to rotate text rendered with `ImDrawList.AddText()`?
I want to label Y-axis on a plot with it.

**Comment by ocornut** [comment]
There's no easy way right now. The code in ImFont::RenderText is fairly optimized for left-to-right and cpu-side clipping for axis aligned so it wouldn't be a trivial fit without altering performance.

If you don't care about cpu-side clipping (you probably don't) you could create yourself a alternative version of ImDrawList::AddTextRotated + ImFontRenderRotated and lay out transformed vertices yourself. You can also remove word-wrapping to make the code shorter.

**Comment by MrSmith33** [comment]
Thanks for help!

**Comment by ocornut** [comment]
I'll close that for now as I don't think it'll be added to master right now, but it should be pretty easy to use the aforementioned code and write your own text "renderer."

**Comment by mitjakukovec** [comment]
I am interested in presenting text rotated too but, if possible, I would not like to reinvent the wheel. If somebody from the community already accomplished this, then please let me know.

**Comment by ocornut** [comment]
I have added a ImFont::RenderChar() function along with render text that is helpful as reference.
You can build your own rotated rendertext, or copy RenderText() into your own function. Remove the feature you don't need from RenderText() such as word-wrapping.

When the original post was made the code from ImFont::RenderText() couldn't be used directly (there was a chain of even coming from ImDrawList::AddText which was required) but isn't the case anymore you can call RenderText() directly meaning you can call a function that does the same-but-rotated directly as well.

**Comment by ocornut** [comment]
@MrSmith33 @mitjakukovec Could you clarify if you are interested in 90 degrees rotated vertical text or arbitrary rotation as implied above? I should have asked the question but the problem are different. 90 degrees rotations are easier to do (lighter CPU-side clipping of polygons, etc.).
Moved tohttps://github.com/ocornut/imgui/issues/705

**Comment by mitjakukovec** [comment]
For me it is more then sufficient to have support for 90 degrees text rotation (clockwise and anticlockwise).

**Comment by ocornut** [comment]
You can use `ShadeVertsTransformPos()` to rotate already rendered text, as seen in `TableAngledHeadersRowEx()`, but beware of the fact the the initial `RenderText()` call will be affected by the active ClipRect and that `ShadeVertsTransformPos()` won't affect the ClipRect after rotation.

```cpp
float cos_a = ImCos(angle);
float sin_a = ImSin(angle);
int vtx_idx_begin = draw_list->_VtxCurrentIdx;
RenderText(....);
int vtx_idx_end = draw_list->_VtxCurrentIdx;
ShadeVertsTransformPos(draw_list, vtx_idx_begin, vtx_idx_end, pivot_in, cos_a, sin_a, pivot_out); // Rotate and offset
```

New text functions expected to be finished this year will probably support this better.

**Comment by PathogenDavid** [comment]
@OMNiON-Github It's declared in `imgui_internal.h` (the header reserved for advanced APIs that might change in the future):

https://github.com/ocornut/imgui/blob/c6236699671b2e5f94481c051cd19afe00cda583/imgui_internal.h#L3462

**Comment by ocornut** [comment]
> but upon reviewing the ImGui library

pro-tip: always run searches in all files of a folder (eg visual studio “Find in Files” to find contents.

**Comment by vinithpoojar** [comment]
I have been utilising the ImGui library for designing my user interface. While using it to create shape frames, I encountered a challenge with creating curved shapes, particularly ellipses. I aim to incorporate strokes with uniform gaps and equal dash lengths, mirroring the style depicted in the original image provided below .

![Screenshot 2024-03-21 at 3 44 39 PM](https://github.com/ocornut/imgui/assets/140804019/323af7fb-087e-48ba-8ffb-fd1f59cfdc05)

Despite multiple attempts, I have been unable to achieve the precise outcome illustrated in the reference image. Attached below is the image showcasing my current progress. Could you kindly provide guidance or a solution to address this issue
<img width="720" alt="Screenshot 2024-03-21 at 3 47 11 PM" src="https://github.com/ocornut/imgui/assets/140804019/9f1b599a-158e-42eb-ae1a-77ae551bb46d">

**Comment by ocornut** [comment]
> Despite multiple attempts, I have been unable to achieve the precise outcome illustrated in the reference image. Attached below is the image showcasing my current progress. Could you kindly provide guidance or a solution to address this issue

Your question is offtopic. You may post a new issue but consider there’s nothing specific to dear imgui in your question, it would be better asked on a general graphics programming, math or geometry forum. You want to step based on distance, not on parameter step (eg it seems you are using a angle step). Search for resources for drawing dashed shapes.

**Comment by cfillion** [comment]
It's unrelated to this issue (rotated text), but for that you need to load the glyphs for these symbols from a font file. See the [Using fonts](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md) documentation page.
