### ISSUE TITLE
does dear imgui remove gdi support

### ISSUE THREAD

**Issue by budibeta** [ocornut/imgui#4221]
is dear imgui can draw in gdi, where is references.

**Comment by rokups** [comment]
Dear ImGui does not have GDI backend, however you could implement one if that is something you need. Library itself is backed-agnostic. You get a list of draw commands which you execute using whatever means possible.

**Comment by ocornut** [comment]
You already opened an issue about this here: #4193

GDI is not really adequate for dear imgui, but there's an experiment backend here #2724 
I found it by searching for "GDI" in issues.
