### ISSUE TITLE
Linux X11 backend?

### ISSUE THREAD

**Issue by Nemirtingas** [ocornut/imgui#4224]
Hi,

As I'm developping my game overlay (windows/linux and probably macos if someday I understand how it works), I built a X11 backend. The code is here: https://github.com/Nemirtingas/imgui/tree/Linux_X11_backend

Would it be worth it to add it to Dear ImGui ?

**Comment by rokups** [comment]
Great effort 👍🏻 Though merging it wont be easy. At very least an example showcasing this backend should exist. But more importantly, we would also like to support docking branch and things get quite complicated there.

**Comment by ocornut** [comment]
Hello,

There is already a x11 native backend PR here https://github.com/ocornut/imgui/pull/3372
It would be good to compare both and decide where we'd like to go.

**Comment by Nemirtingas** [comment]
I didn't see it as I searched in the issues and not in the pull requests.

My implementation is pure X11, I'm not using Xcb. For what I needed, it works fine. I didn't test it much as I don't go often on Linux to try it. I never triied the Docking branch either.

#3372 seems more advanced than mine.

**Comment by Nemirtingas** [comment]
> Great effort 👍🏻 Though merging it wont be easy. At very least an example showcasing this backend should exist. But more importantly, we would also like to support docking branch and things get quite complicated there.

Hi, its been a while since I worked on this. I decided to create that example in case someone needs a pure X11/OpenGL3, its available here:
https://github.com/Nemirtingas/imgui/commit/849759f19f4dd5591d965caf76882d4d0768bfda

**Comment by ocornut** [comment]
Linking to #3372 and #7262 and closing this.

**Comment by lortkipa** [comment]
> Hi,
> 
> As I'm developping my game overlay (windows/linux and probably macos if someday I understand how it works), I built a X11 backend. The code is here: https://github.com/Nemirtingas/imgui/tree/Linux_X11_backend
> 
> Would it be worth it to add it to Dear ImGui ?

it says page not found. is it still awailable?

**Comment by ocornut** [comment]
If you look at their fork there is a branch with which appears has it.
https://github.com/Nemirtingas/imgui/tree/feature/xcb-backend

**Comment by lortkipa** [comment]
> If you look at their fork there is a branch with which appears has it. https://github.com/Nemirtingas/imgui/tree/feature/xcb-backend

thanks thats what i was looking for!

**Comment by Nemirtingas** [comment]
Hi, sorry, the branch doesn't exist anymore because it has been merged in my own main :
https://github.com/Nemirtingas/imgui/blob/my_master/backends/imgui_impl_x11.cpp

I strongly advise you to not look at the xcb-backend branch. Its a (abandoned?) xcb backend that I am/was working on.
