### ISSUE TITLE
Merge FA icons font with two other fonts?

### ISSUE THREAD

**Issue by patrickcjk** [ocornut/imgui#4230]
Basically what I want is to merge font awesome icons with my two fonts. Im using Tahoma Regular and Tahoma Bold. Id' like to be able to use both fonts using PushFont with icons. Currently, this works:

```c++
ImFont* font_tahoma_regular;
ImFont* font_tahoma_bold;
ImFont* font_fa;
ImFont* font_fa_2;

static const ImWchar icons_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };

ImFontConfig icons_config;
icons_config.MergeMode = true;
icons_config.PixelSnapH = true;

font_tahoma_bold = io->Fonts->AddFontFromMemoryTTF((void*)tahoma_bold, sizeof(tahoma_bold), 16.f);
font_fa = io->Fonts->AddFontFromMemoryTTF((void*)fa_solid_900, sizeof(fa_solid_900), 13.f, &icons_config, icons_ranges);

font_tahoma_regular = io->Fonts->AddFontFromMemoryTTF((void*)tahoma_regular, sizeof(tahoma_regular), 16.f);
font_fa_2 = io->Fonts->AddFontFromMemoryTTF((void*)fa_solid_900, sizeof(fa_solid_900), 13.f, &icons_config, icons_ranges);
```

But as you can see, it makes me loading the font twice.

**Comment by rokups** [comment]
Note that `font_fa == font_tahoma_bold` and `font_fa_2 == font_tahoma_regular`, because FA is merged to previous font. Why is loading font twice a problem to begin with? This is most likely done once on application startup, therefore there will be no performance impact. What you are doing is the right way to do it.

**Comment by patrickcjk** [comment]
> Note that `font_fa == font_tahoma_bold` and `font_fa_2 == font_tahoma_regular`, because FA is merged to previous font. Why is loading font twice a problem to begin with? This is most likely done once on application startup, therefore there will be no performance impact. What you are doing is the right way to do it.

Thank you for clearifying!
