### ISSUE TITLE
How do I check if docked tab window is open ?

### ISSUE THREAD

**Issue by vertexpotato** [ocornut/imgui#4231]
I'm using ```ImGui::GetForegroundDrawList()->AddRect()``` to draw a bunch of rects on top of an ImGui window, however when I switch the tab and go to another window the rects would still show up. Here is some images from inside my application : 

![docking1](https://user-images.githubusercontent.com/18310807/122189883-fb844580-ce99-11eb-9c92-a773d0ff3a23.PNG)

![docking2](https://user-images.githubusercontent.com/18310807/122189900-fe7f3600-ce99-11eb-8973-51140828d6f0.PNG)

Here is a rough code of how I draw the rects: 

```
auto rectmin = ImGui::GetItemRectMin();
auto rectmax = ImGui::GetItemRectMax();

auto drawlist = ImGui::GetForegroundDrawList();

drawlist->AddRect(rectmin, rectmax, IM_COL32(255, 255, 0, 255));
```

when I switch from sprite selector to material editor the rects would still show up.

I have looked for a way to check if the current window is hidden or not but I didn't find any, does ImGui support such thing ?

**Comment by ocornut** [comment]
Check the return value of Begin().

You may need to perform a basic visible check for the widget to handle first frame and/or scrolling. There are helpers IsRectViaible() etc

**Comment by vertexpotato** [comment]
@ocornut Thanks it worked, how couldn't I see it lol
