### ISSUE TITLE
unresolved external symbol

### ISSUE THREAD

**Issue by AnnoyingB** [ocornut/imgui#4237]
I keep getting this error I simply cannot fix!

imgui.obj : error LNK2019: unresolved external symbol "void __cdecl ImGui::ShowFontAtlas(struct ImFontAtlas *)" (?ShowFontAtlas@ImGui@@YAXPAUImFontAtlas@@@Z) referenced in function "void __cdecl ImGui::ShowMetricsWindow(bool *)" (?ShowMetricsWindow@ImGui@@YAXPA_N@Z)

`
#include "GL/glew.h"
#include <iostream>
//#include "ImGUI/imgui.h"
//#include "ImGUI/imgui_impl_glfw.h"
//#include "ImGUI/imgui_impl_opengl3.h"
#include "GLFW/glfw3.h"

using namespace std;

int main() {
	GLFWwindow* window;

	int h, w;

	if (!glfwInit()) cout << "Error with initializing" << endl;

	window = glfwCreateWindow(600, 500, "Acorn Engine", nullptr, nullptr);

	glfwMakeContextCurrent(window);

	GLenum err = glewInit();
	if (GLEW_OK != err)
		fprintf(stderr, "Error %s\n", glewGetErrorString(err));

	/*ImGui::CreateContext();
	ImGui_ImplGlfw_InitForOpenGL(window, true);
	ImGui_ImplOpenGL3_Init();
	ImGui::StyleColorsDark();*/
	

	while (!glfwWindowShouldClose(window)) {
		glfwGetWindowSize(window, &w, &h);
		//ImGui_ImplOpenGL3_NewFrame();

		/*Rendering*/
		glClear(GL_COLOR_BUFFER_BIT);

		//ImGui Rendering

		//ImGui::Text("Hello");

		//ImGui::Render();
		//ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

		/*End of rendering*/

		glfwSwapBuffers(window);

		glfwPollEvents();
	}

	//ImGui Shutdown

	//ImGui_ImplGlfw_Shutdown();
	//ImGui_ImplOpenGL3_Shutdown();
	//ImGui::DestroyContext();

	//Glfw Shutdown
	glfwDestroyWindow(window);
	glfwTerminate();
}
`

I have also compiled everything.

<img width="210" alt="Files" src="https://user-images.githubusercontent.com/81764357/122423549-e4228680-cf85-11eb-91b1-ae8e88115c7e.png">

**Comment by PathogenDavid** [comment]
It looks like you're hitting https://github.com/ocornut/imgui/issues/4171. The easiest solution is to add [your beloved friend `imgui_demo.cpp`](https://github.com/ocornut/imgui/blob/7c44d067e8d1662549db73f80099e01a9c1a5f46/imgui_demo.cpp#L12-L21).

--------------------

As an aside, you can't use a single \` for blocks of code which span multiple lines, you have to use three of them like this:

~~~markdown
```cpp
// ^__ It's technically optional, but putting a language name here will add syntax highlighting as well.
// Say hello:
printf("Hello, world!\n");
```
~~~

**Comment by AnnoyingB** [comment]
I still have the same error

**Comment by AnnoyingB** [comment]
It worked! Thanks

**Comment by AnnoyingB** [comment]
Now it shows:

Exception thrown: write access violation.
g.CurrentWindow was nullptr.

**Comment by PathogenDavid** [comment]
Compare against the examples and make sure [your main loop](https://github.com/ocornut/imgui/blob/v1.83/examples/example_glfw_opengl3/main.cpp#L150) has all the appropriate function calls. The code you showed above is missing quite a few things.

**Comment by AnnoyingB** [comment]
It works! Thanks

**Comment by AnnoyingB** [comment]
Is there any good dockable panel tutorial I could use?

**Comment by PathogenDavid** [comment]
Do you mean just having dockable panels in general? Check out [the experimental docking branch](https://github.com/ocornut/imgui/issues/2109).

If you meant something else you'll have to clarify exactly what you're wanting to do.

**Comment by AnnoyingB** [comment]
I want some example code. I looked at that but I had some functions unavailable to me.

**Comment by AnnoyingB** [comment]
How do you get the docking to work? I would like some example code and if I need any extra files i'd like a link to the download

**Comment by PathogenDavid** [comment]
The official examples show off most of the core features.

For the most part, docking just works. If you're having trouble getting it to work in general, make sure you [have it enabled](https://github.com/ocornut/imgui/blob/cce307a2be4d26c34cce7d4844381e18cc49f656/examples/example_glfw_opengl3/main.cpp#L121-L122). (And make sure it's enabled **before** you initialize the backends.)

There's [an article about docking on the wiki](https://github.com/ocornut/imgui/wiki/Docking).

You can browse docking-related issues using [this GitHub issue filter](https://github.com/ocornut/imgui/issues?q=is%3Aissue+label%3Adocking+-label%3Abug+is%3Aclosed+). (This link is filtered to closed issues, but open issues might have interesting information as well.)

Otherwise I'm not really aware of any resources beyond the comments in the header files.

In general it's a lot easier to learn (and a lot easier for us to help you) if you have a specific goal in mind.

**Comment by PathogenDavid** [comment]
Ah you just beat me.

> How do you get the docking to work? I would like some example code and if I need any extra files i'd like a link to the download

Make sure you're using [the docking branch](https://github.com/ocornut/imgui/tree/docking). You can identify whether or not you have the docking code by looking for `IMGUI_HAS_DOCK` in `imgui.h`:

https://github.com/ocornut/imgui/blob/cce307a2be4d26c34cce7d4844381e18cc49f656/imgui.h#L69

From there, the only thing you really need to do is enable it as mentioned earlier.

**Comment by AnnoyingB** [comment]
Okay thanks.

**Comment by PathogenDavid** [comment]
No problem, good luck!

**Comment by AnnoyingB** [comment]
I have the docking branch and how do you enable it?

**Comment by AnnoyingB** [comment]
Oh wait nvm

**Comment by AnnoyingB** [comment]
io is undefined?

**Comment by ocornut** [comment]
Hello, this is not a chat room and you are behaving as a help vampire.
Please be mindful to not abuse of the generous help David is providing by doing some researches on your side.
https://www.google.com/search?&q=help+vamprire

**Comment by AnnoyingB** [comment]
Sorry. My apoligies
