### ISSUE TITLE
Can't have 2 childs

### ISSUE THREAD

**Issue by g0dzcsgo** [ocornut/imgui#4248]
Hello, I have a problem.

Basically i am trying to have 2 childs, I use:

ImGui::BeginChild("##main", ImVec2(252, 283), true, ImGuiWindowFlags_NoScrollbar);
ImGui::EndChild();

And this is under:

ImGui::BeginChild("##other", ImVec2(224, 283), true, ImGuiWindowFlags_NoScrollbar);	
ImGui::EndChild();

First child and second child is showing, but all the contents of the second child is not showing (checkboxes, sliders, etc)

What is causing this?

**Comment by ocornut** [comment]
This perfectly work
```

ImGui::BeginChild("##main", ImVec2(252, 283), true, ImGuiWindowFlags_NoScrollbar);
ImGui::Text("Hello A");
ImGui::EndChild();

ImGui::BeginChild("##other", ImVec2(224, 283), true, ImGuiWindowFlags_NoScrollbar);
ImGui::Text("Hello B");
ImGui::EndChild();
```
Which means you are omitting context, haven't tested your repro nor read the issue guidelines.
Can't really help you if you make it harder for us to help you.

![image](https://user-images.githubusercontent.com/8225057/122741641-7035f600-d285-11eb-92a2-72bf65205105.png)
