### ISSUE TITLE
MacOS backend ObjectiveC types.

### ISSUE THREAD

**Issue by Nemirtingas** [ocornut/imgui#4249]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_osx.cpp 
Compiler: Apple Clang++ 9
Operating System: MacOS High Sierra

**My Issue/Question:**
Can you make the osx backend more portable like Win32/X11 backends by removing strongly typed parameters and using void* instead ? https://github.com/Nemirtingas/imgui/tree/Macos_osx_backend

**Comment by ocornut** [comment]
Can you confirm that existing examples and ObjC backends will compile with this?

**Comment by Nemirtingas** [comment]
I successfully compiled my project (is it because of cmake and because its a c++/ObjectiveC++ project?), with just switching to void* but the example_apple_opengl2 fails with some errors:
![image](https://user-images.githubusercontent.com/9432037/122766256-9c5f7000-d2a1-11eb-87c5-fbd3174a50f9.png)

Casting types to (__bridge void*) seems to fix those issues, but as I pretty new to ObjectiveC because of Apple, I don't have any insight on what problem that could cause. I guess that the best idea is to just keep this modification local to my project

**Comment by ocornut** [comment]
Thank you. If you/we find more about it we'll resume this discussion here.

**Comment by Nemirtingas** [comment]
Ok, fair enought, thanks.
