### ISSUE TITLE
FreeType + Shadows = StyleUpdateTexture bug

### ISSUE THREAD

**Issue by N1ceL** [ocornut/imgui#4255]
Version/Branch of Dear ImGui:

Version: ImGui with shadows v1.84 WIP
Branch: shadows

Back-end/Renderer/Compiler/OS

Back-ends: win32_directx10
Compiler: MSVC 19.29 x32
Operating System: Windows 10

My Issue/Question:
With FreeType when I changing in shadows settings "Corner size" or something else it just breaks fonts, shadow textures, but not rebuilds it
![image](https://user-images.githubusercontent.com/41979846/123004739-62ed4880-d3f8-11eb-8eff-00b88e345022.png)

**Comment by ocornut** [comment]
OK I understand what's happening. The reloading feature (added by the 2 "experimental" commits in that branch) weren't meant to be pushed. The texture reload experiment of those 2 commits will be superseded by #3761. Once we have #3761 shadows will be able to use it.

I have force-pushed to `features/shadows` without those two commits (and therefore without those 4 options).

The two "extra" commits with the old texture reload experiments are
https://github.com/ocornut/imgui/commit/f7a2b4f271436a7c26275b80ecab70c97bcb109a
https://github.com/ocornut/imgui/commit/77947716109fff7fbbdabd8893c4fb026431adfc

If you want to use shadows I suggest you use them without this.
I pushed shadows for visibility but it has been not as useful as expected in many situations (docking + usage of viewports), I am wondering how you are taking advantage of it? Do you have any screenshots to share?

For now I'm closing this as I've removed the 2 "faulty" commits so it shouldn't happen anymore.

**Comment by N1ceL** [comment]
Shadow reloading not really needed, better to build it once and using texture alpha as shadows size I think. I just tested the shadows in the demo, imgui looks very nice and simple. After creating a simple font system for reloading/loading fonts with freetype for tests I found this bug in demo
