### ISSUE TITLE
Rendering html?

### ISSUE THREAD

**Issue by pongalongg** [ocornut/imgui#4257]
Hi,

I was wondering if anyone has, or if it was even possible, to render html, or preferably render a web page from a URL for example, inside of a Dear ImGui frame? Would surely be useful for a multitude of things. Thanks in advance.

**Comment by ocornut** [comment]
You can use a HTML renderer such as Chromium to render into a texture and then render that texture in Dear ImGui.

Almost all the work involved to set that up would be with the tech you are using (e.g. Chromium) which may be difficult to setup (unrelated to Dear ImGui).

See
https://github.com/ocornut/imgui/issues/1902#issuecomment-449708903
https://github.com/ocornut/imgui/issues/1140
https://github.com/ocornut/imgui/issues/1075
https://twitter.com/ocornut/status/890210588600565762

**Comment by pongalongg** [comment]
> You can use a HTML renderer such as Chromium to render into a texture and then render that texture in Dear ImGui.
> 
> Almost all the work involved to set that up would be with the tech you are using (e.g. Chromium) which may be difficult to setup (unrelated to Dear ImGui).
> 
> See
> [#1902 (comment)](https://github.com/ocornut/imgui/issues/1902#issuecomment-449708903)
> #1140
> #1075
> https://twitter.com/ocornut/status/890210588600565762

Thank you!

Furthermore, is it possible to render an image directly from a url? So instead of defining an image path, i can just put it as a URL instead.

**Comment by ocornut** [comment]
> Furthermore, is it possible to render an image directly from a url? So instead of defining an image path, i can just put it as a URL instead.

We already have a rather extensive tutorial on loading textures because even if it is out of scope of Dear ImGui, that sorts of questions keeps on coming:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
Loading a file from the internet is more largely out of scope of this project.
