### ISSUE TITLE
Child and text behind other child not rendered correctly

### ISSUE THREAD

**Issue by sDylane** [ocornut/imgui#4265]
Version: v1.83
Branch: master

Greetings dear friends, I have trouble with childs:
https://streamable.com/3vjd0d

How i can fix this? I read about ImGuiWindowFlags_NoFocusOnAppearing and ImGuiWindowFlags_NoBringToFrontOnFocus
But that didn't help me figure out the problem. Sorry in advance for my english.

**Comment by ocornut** [comment]
Sorry but #1586
