### ISSUE TITLE
error C2039: "GetTexID"

### ISSUE THREAD

**Issue by IvaOsi** [ocornut/imgui#4270]
Hello, everyone.
trying to run a simple window example using imgui

I'm using the Opengl + glfw example to run

All the libraries are latest version i downloaded them recently (maybe a day ago)

But I get the following errors

`imgui_impl_opengl3.cpp(433): error C2039: "GetTexID": ­Ґ пў«пҐвбп з«Ґ­®¬ "ImDrawCmd".`

![image](https://user-images.githubusercontent.com/17671542/123422086-5a4a6d00-d5c6-11eb-8f93-fcc7e2a6ccc2.png)

I tried to look and there really is no such method :
![image](https://user-images.githubusercontent.com/17671542/123421721-e4de9c80-d5c5-11eb-9bcf-2f4ecc08b398.png)

Is there anything you can do to help me?

**Comment by ocornut** [comment]
You are using a recent backend version with an old version of dear imgui.

**Comment by IvaOsi** [comment]
> You are using a recent backend version with an old version of dear imgui.

Sorry but how to download new version of imgui using vcpkg

i see this 
![image](https://user-images.githubusercontent.com/17671542/123424654-cda1ae00-d5c9-11eb-809b-24c2907de407.png)

but i need 1.84

**Comment by ocornut** [comment]
> how to download new version of imgui using vcpkg

That's a question for vcpkg.

Regardless, you don't need a new version. You only need to make sure you don't use backends code from 1.84 with older dear imgui version. If you have an older dear imgui version, use a backend from same version.
