### ISSUE TITLE
imgui and realtime audio processing program

### ISSUE THREAD

**Issue by richieloro** [ocornut/imgui#4274]
Hello is imgui the best way to draw interface for a realtime audio processing program ?

Is there better way to do this, like static interfaces ?

Thank you.

**Comment by ocornut** [comment]
This is too much of an open-ended question to be answered.
There's rarely a "best way" for anything. It depends on your project type, the constraints you have, the experience and knowledge of your team with that type of technology. If you are comfortable with dear imgui use it, otherwise don't.
