### ISSUE TITLE
Click many buttons at same time.

### ISSUE THREAD

**Issue by vovan4ik123** [ocornut/imgui#4276]
Hello. Can you add possibility to click many buttons at same time on mobile devices?

Even if i touch screen outside of button and then do second touch on button it does not react.
Tested it on Android + SDL2 + OpenGL 3.

Thank you!

----

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.82
Branch: release

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: XXX

**My Issue/Question:**

XXX _(please provide as much context as possible)_

**Screenshots/Video**

XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Hello, we don't support multi-touch and there's no immediate plan to support it.
Ref #3711
