### ISSUE TITLE
Im having issues trying to update Dear Imgui version on my project

### ISSUE THREAD

**Issue by whiskasdietgirl** [ocornut/imgui#4277]
Im sorry if this is an obvious problem with an obvious solution. 
Im a beginner programmer. I made a small program using dear imgui.
Seeing that triangles outlines are a bit bugged, after searching for a solution I found that the issue was solved in an update, and that my version 1.74 is outdated.

So i tried to update my version. Made a back up just in case, because i know things can go wrong, and i can just not understand what happened.
I replaced all the imgui files with the new imgui files, meticulously.

And when trying to compile: I got a many errors. 33 unresolved externals.
Since my program took already weeks of work. Should i just back off and stay with the old version, and finish it?
Because its almost finished, and everything is working great except that little detail on triangles, that is ok.

After failing, I also tried to delete all the .obj files, so it rebuilds.
Can anyone help me? What have i done wrong? It seems there is some sort of conflict.
Please help me and remove this thread if this has an embarassing easy solution.

`libMinHook.x86.lib(hook.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance

1>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification

1>MSVCRTD.lib(initializers.obj) : warning LNK4098: defaultlib 'libcmt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::EndTable(void)" (?EndTable@ImGui@@YAXXZ)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::EndTable(void)" (?EndTable@ImGui@@YAXXZ)

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::EndColumns(void)" (?EndColumns@ImGui@@YAXXZ)

1>imgui.obj : error LNK2001: unresolved external symbol "float __cdecl ImGui::GetColumnOffsetFromNorm(struct ImGuiOldColumns const *,float)" (?GetColumnOffsetFromNorm@ImGui@@YAMPBUImGuiOldColumns@@M@Z)

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableEndRow(struct ImGuiTable *)" (?TableEndRow@ImGui@@YAXPAUImGuiTable@@@Z)

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableGcCompactTransientBuffers(struct ImGuiTable *)" (?TableGcCompactTransientBuffers@ImGui@@YAXPAUImGuiTable@@@Z)

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableGcCompactTransientBuffers(struct ImGuiTableTempData *)" (?TableGcCompactTransientBuffers@ImGui@@YAXPAUImGuiTableTempData@@@Z)

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableGcCompactSettings(void)" (?TableGcCompactSettings@ImGui@@YAXXZ)

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableSettingsInstallHandler(struct ImGuiContext *)" (?TableSettingsInstallHandler@ImGui@@YAXPAUImGuiContext@@@Z)

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::DebugNodeTable(struct ImGuiTable *)" (?DebugNodeTable@ImGui@@YAXPAUImGuiTable@@@Z)

1>imgui.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::DebugNodeTableSettings(struct ImGuiTableSettings *)" (?DebugNodeTableSettings@ImGui@@YAXPAUImGuiTableSettings@@@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "bool __cdecl ImGui::BeginTable(char const *,int,int,struct ImVec2 const &,float)" (?BeginTable@ImGui@@YA_NPBDHHABUImVec2@@M@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableNextRow(int,float)" (?TableNextRow@ImGui@@YAXHM@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "bool __cdecl ImGui::TableNextColumn(void)" (?TableNextColumn@ImGui@@YA_NXZ)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "bool __cdecl ImGui::TableSetColumnIndex(int)" (?TableSetColumnIndex@ImGui@@YA_NH@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableSetupColumn(char const *,int,float,unsigned int)" (?TableSetupColumn@ImGui@@YAXPBDHMI@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableSetupScrollFreeze(int,int)" (?TableSetupScrollFreeze@ImGui@@YAXHH@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableHeadersRow(void)" (?TableHeadersRow@ImGui@@YAXXZ)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableHeader(char const *)" (?TableHeader@ImGui@@YAXPBD@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "struct ImGuiTableSortSpecs * __cdecl ImGui::TableGetSortSpecs(void)" (?TableGetSortSpecs@ImGui@@YAPAUImGuiTableSortSpecs@@XZ)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "int __cdecl ImGui::TableGetColumnIndex(void)" (?TableGetColumnIndex@ImGui@@YAHXZ)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "int __cdecl ImGui::TableGetRowIndex(void)" (?TableGetRowIndex@ImGui@@YAHXZ)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "char const * __cdecl ImGui::TableGetColumnName(int)" (?TableGetColumnName@ImGui@@YAPBDH@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "int __cdecl ImGui::TableGetColumnFlags(int)" (?TableGetColumnFlags@ImGui@@YAHH@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TableSetBgColor(int,unsigned int,int)" (?TableSetBgColor@ImGui@@YAXHIH@Z)

1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::Columns(int,char const *,bool)" (?Columns@ImGui@@YAXHPBD_N@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::NextColumn(void)" (?NextColumn@ImGui@@YAXXZ)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "int __cdecl ImGui::GetColumnIndex(void)" (?GetColumnIndex@ImGui@@YAHXZ)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "float __cdecl ImGui::GetColumnWidth(int)" (?GetColumnWidth@ImGui@@YAMH@Z)
1>imgui_demo.obj : error LNK2001: unresolved external symbol "float __cdecl ImGui::GetColumnOffset(int)" (?GetColumnOffset@ImGui@@YAMH@Z)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::PushColumnsBackground(void)" (?PushColumnsBackground@ImGui@@YAXXZ)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::PopColumnsBackground(void)" (?PopColumnsBackground@ImGui@@YAXXZ)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TablePushBackgroundChannel(void)" (?TablePushBackgroundChannel@ImGui@@YAXXZ)
1>imgui_widgets.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::TablePopBackgroundChannel(void)" (?TablePopBackgroundChannel@ImGui@@YAXXZ)`

**Comment by ocornut** [comment]
Hello,

You need to compile and link imgui_tables.cpp into your project. Right now it is missing.

If you search for the missing functions/symbols in your folder you’ll find they all come from this file, which was added in 1.80.

If you search for the error code on the web, you’ll learn this is also a frequent error when a file is not compiled and linked into your project.

Cheers
