### ISSUE TITLE
DragDropTarget clipping issue

### ISSUE THREAD

**Issue by skaarj1989** [ocornut/imgui#4281]
**Version/Branch of Dear ImGui:**

Version: 1.84 WIP (18308)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: All of them

**My Issue/Question:**

A border around a drop target is drawn outside a window. I am not sure if this is expected behavior but it looks weird to me.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/34756939/123827502-f7780f00-d900-11eb-9ee9-0b9f64df003a.png)

**Standalone, minimal, complete and verifiable example:**

`Demo -> Widgets -> Drag and Drop`

**Comment by ocornut** [comment]
Pushed a fix with 4ddb6b46c314045d75b565fc29170e7cb2327eca
This intentional (see initial commit 4b94738c7e64a7a912a72b373063b42a407ec1bd) but I frankly can't remember nor understand why I thought it was a good idea back then...
Same issue as #3272

**Comment by ocornut** [comment]
I have reworked this with 085ed7b 

Before June 2021
![image](https://github.com/ocornut/imgui/assets/8225057/833e6e15-b0eb-4ce8-a5f6-9deb6245fb04)

June 2021
![image](https://github.com/ocornut/imgui/assets/8225057/ba740552-4a0f-4f85-91ad-5fea9b696735)

October 2023
![image](https://github.com/ocornut/imgui/assets/8225057/6bb5e5ce-68fc-443e-b674-476aa63425f9)

**Comment by ocornut** [comment]
This raised an issue, see #7049
