### ISSUE TITLE
ImGui Windows not showing

### ISSUE THREAD

**Issue by AnnoyingB** [ocornut/imgui#4287]
Sorry if this a stupid question, but, how does DockSpace work? I have no idea what a ImGuiID is but I'd just like to make a opengl window a dockspace, Thanks!

**Comment by ocornut** [comment]
There are examples in the demo and copious amount of comments.

**Comment by AnnoyingB** [comment]
Yes, I know, but I still don't understand it what so ever.

**Comment by PathogenDavid** [comment]
It sounds like `DockSpaceOverViewport` is what you're looking for. IE:

```cpp
ImGui::DockSpaceOverViewport(GetMainViewport());
```

If you want more control than it provides, you have to use `ImGui::DockSpace` directly. All that matters is the ID is unique, you can make an `ImGuiID` from a string using `ImGui::GetID`. IDs are further explained by [this FAQ](https://github.com/ocornut/imgui/blob/23a15834fa23226bd26a17f5142b00678617fec4/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it).

**Comment by AidanSun05** [comment]
You said that you didn't understand the demo code for the DockSpace. It's true that there's a lot going on inside the demo function, so here's a gist containing some more clarifying comments. This should help you to understand the functionality and usage more.

https://gist.github.com/AidanSun05/b342f1bf023e931695473e343569759c

**Comment by AnnoyingB** [comment]
Thanks @PathogenDavid

**Comment by AnnoyingB** [comment]
Now what happens is I get no ImGui windows... Odd

**Comment by PathogenDavid** [comment]
Not sure what to tell you besides that shouldn't happen. It'd help if you could share some of your code.

`DockSpaceOverViewport` should be called on its own (IE: not inside of a `Begin..End` block) and as early as possible (ideally right after `ImGui::NewFrame`.)

Are you on the latest version of the docking branch?

**Comment by AnnoyingB** [comment]
Yes.

**Comment by AnnoyingB** [comment]
```
ImGui_ImplOpenGL3_NewFrame();
	ImGui_ImplGlfw_NewFrame();
	ImGui::NewFrame();

	// Dockspace
	ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());

	/*Rendering*/
	glClear(GL_COLOR_BUFFER_BIT);

	//ImGui Rendering
	{

		//Menubar
		Core::RenderMenuBar();

		//Viewport
		

		//Console
		ImGui::Begin("Console");

		static ImGuiTableFlags flags = ImGuiTableFlags_ScrollY | ImGuiTableFlags_RowBg | ImGuiTableFlags_BordersOuter | ImGuiTableFlags_BordersV | ImGuiTableFlags_Reorderable | ImGuiTableFlags_Hideable;
		if (ImGui::BeginTable("", 2, flags))
		{
			ImGui::TableSetupScrollFreeze(0, 1);
			ImGui::TableSetupColumn("Information", ImGuiTableColumnFlags_None);
			ImGui::TableSetupColumn("Type", ImGuiTableColumnFlags_None);
			ImGui::TableHeadersRow();
			for (int i = 0; i < Core::consoleText.size(); i++) {
				for (int ii = 0; ii < Core::type.size(); ii++) {
					// Info List(IL)
					auto l_front = Core::consoleText.begin();
					std::advance(l_front, i);
					std::string string = *l_front;
					// Console Type List(CTL)
					auto l_frontt = Core::type.begin();
					std::advance(l_frontt, i);
					Core::ConsoleType ctypeo = *l_frontt;
					std::string ctype;
					switch (ctypeo) {
						case Core::ConsoleType::Message:
							ctype = "Message";
							break;
						case Core::ConsoleType::Warning:
							ctype = "Warning";
							break;
						case Core::ConsoleType::Error:
							ctype = "Error";
							break;
					}
					ImGui::TableNextColumn();
					ImGui::Text(string.c_str());
					ImGui::TableNextColumn();
					ImGui::Text(ctype.c_str());
				}
			}
		}

		ImGui::EndTable();
		ImGui::End();
	}

	ImGui::Render();
	ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

	if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
	{
		GLFWwindow* backup_current_context = glfwGetCurrentContext();
		ImGui::UpdatePlatformWindows();
		ImGui::RenderPlatformWindowsDefault();
		glfwMakeContextCurrent(backup_current_context);
	}

	/*End of rendering*/

	glfwSwapBuffers(window);

	glfwPollEvents();
```

**Comment by AidanSun05** [comment]
You might have to provide more details - what's inside of `Core::RenderMenuBar()`? Are `Core::consoleText` and `Core::type` strings, containers (e.g. vector, deque), or something else like your own class/struct?

In the meantime, there are some minor errors in your main loop's structure. It's a common convention to call `glfwPollEvents()` as the very first thing (you have it as the very last). `glClear(GL_COLOR_BUFFER_BIT)` should be near the end, along with other OpenGL function calls which you have missed.

```cpp
// Main loop
while (!glfwWindowShouldClose(window)) {
    // Handle the creation of a new frame
    glfwPollEvents(); // MOVED THIS
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    // Dockspace
    ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());

    //
    // [Put your window rendering code here]
    //

    // Handle the rendering of the main and detached viewports
    ImGui::Render();
    int w, h;                                 // ADDED THIS
    glfwGetFramebufferSize(window, &w, &h);   // ADDED THIS
    glViewport(0, 0, w, h);                   // ADDED THIS
    glClearColor(0.45f, 0.55f, 0.60f, 1.00f); // ADDED THIS
    glClear(GL_COLOR_BUFFER_BIT);             // MOVED THIS
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
        GLFWwindow* backup_current_context = glfwGetCurrentContext();
        ImGui::UpdatePlatformWindows();
        ImGui::RenderPlatformWindowsDefault();
        glfwMakeContextCurrent(backup_current_context);
    }

    glfwSwapBuffers(window);
}
```

**Comment by AnnoyingB** [comment]
Okay, Core::consoleText is text to show onto the console and Core::type is the type of message it is. Core::RenderMenuBar just has simple code to render a menu bar:

```
     if (ImGui::BeginMainMenuBar()) {
		if (ImGui::BeginMenu("File")) {
			if (ImGui::MenuItem("Save")) {
				
			}
			if (ImGui::MenuItem("Open")) {

			}
			if (ImGui::MenuItem("Close")) {

			}
			ImGui::EndMenu();
		}

		if (ImGui::BeginMenu("Edit")) {
			//if(ImGui::MenuItem("")) {}
			ImGui::EndMenu();
		}

		ImGui::EndMainMenuBar();
	}
```

**Comment by AnnoyingB** [comment]
Im confused. I tried tagging out the dockspaceoverviewport and there are still no windows

**Comment by AidanSun05** [comment]
Based on your repro and my main loop template, I made a quick test program (I can share it if you'd like).

Here's the result:

![image](https://user-images.githubusercontent.com/61399657/124020933-ebe81f00-d9b8-11eb-98f0-1f20aa76c4d8.png)

Is this the expected behavior?

**Comment by AnnoyingB** [comment]
Yes

**Comment by AnnoyingB** [comment]
Also, if you can, add info on what you changed or added. Thanks

**Comment by AidanSun05** [comment]
So I'm guessing it's something in your main loop, not something regarding Dockspaces.

Here's the full code: https://gist.github.com/AidanSun05/1b9023db840dd3ce95ffd3af37e488db

The main loop starts on line 162.

**Comment by AnnoyingB** [comment]
Hmm. Odd. I don't see much of a difference.

**Comment by AidanSun05** [comment]
It's mostly just the start and end of the main loop:

```cpp
// Handle the creation of a new frame
glfwPollEvents(); // MOVED THIS
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplGlfw_NewFrame();
ImGui::NewFrame();
```

```cpp
// Handle the rendering of the main and detached viewports
ImGui::Render();
int w, h;                                 // ADDED THIS
glfwGetFramebufferSize(window, &w, &h);   // ADDED THIS
glViewport(0, 0, w, h);                   // ADDED THIS
glClearColor(0.45f, 0.55f, 0.60f, 1.00f); // ADDED THIS
glClear(GL_COLOR_BUFFER_BIT);             // MOVED THIS
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
    GLFWwindow* backup_current_context = glfwGetCurrentContext();
    ImGui::UpdatePlatformWindows();
    ImGui::RenderPlatformWindowsDefault();
    glfwMakeContextCurrent(backup_current_context);
}

glfwSwapBuffers(window);
```

**Comment by AnnoyingB** [comment]
Or not even any changes.

**Comment by AnnoyingB** [comment]
Yes, I have changed that, and still, nothing

**Comment by AidanSun05** [comment]
Can you show a screenshot? In cases of unexpected behavior, this is almost always one of the best pieces of information you can provide (other than your code, of course).

**Comment by AnnoyingB** [comment]
Screenshot of what, exactly?

**Comment by AidanSun05** [comment]
Your Dear ImGui window (the whole thing). Like what I sent earlier.

**Comment by AnnoyingB** [comment]
Okay, here:
<img width="302" alt="Screenshot 2021-06-30 205119" src="https://user-images.githubusercontent.com/81764357/124022648-fae4c680-d9e4-11eb-9787-7f1691e8a74d.png">

**Comment by AnnoyingB** [comment]
Nothing else. No windows, no nothing, just this glfw window. The only thing working is the menu bar. Not the windows

**Comment by AnnoyingB** [comment]
Is this possibly a problem with ImGui?

**Comment by AidanSun05** [comment]
You copied my whole gist into your file and ran it, correct?

**Comment by AnnoyingB** [comment]
I didn't copy the entire thing but I changed my code from what you wrote.

**Comment by AnnoyingB** [comment]
As in I didn't copy the table

**Comment by AnnoyingB** [comment]
Worked perfectly before. But now, not for some odd reason

**Comment by AidanSun05** [comment]
There are two main sections you need to copy in, they're highlighted in one of my above comments. Remember to not leave anything out:

https://github.com/ocornut/imgui/issues/4287#issuecomment-871680825

**Comment by AnnoyingB** [comment]
Yes, I have made those changes. It did nothing.

**Comment by AidanSun05** [comment]
Then it's probably not the code.

Did you update or change any of the following recently?
* Dear ImGui
* GLFW or OpenGL
* Visual Studio (or whatever compiler you use)
* Your graphics driver
* Your OS
* Your computer's configuration (BIOS, hardware, etc.)

**Comment by AnnoyingB** [comment]
Hm. I remember re-installing my driver adapter and also repairing visual studio. But that's it

**Comment by AidanSun05** [comment]
Try to test your code on a different machine, this could just be a temporary issue.

Or, if you don't have another machine, you can reboot your computer, then try again.

**Comment by AnnoyingB** [comment]
I don't have a different machine and I just restarted my pc and still doesn't work.

**Comment by AidanSun05** [comment]
You said that it worked perfectly before, so there must be something that changed. It's most likely a program that auto-updated without you knowing.

If you're on Windows, you can go to Control Panel > Programs > Programs and Features to get a list of every installed program on your computer.

You should look for anything that has an install date that's very recent (within a week or two). In the screenshot below, my NVIDIA graphics driver was updated recently, so that's a possible candidate.

![image](https://user-images.githubusercontent.com/61399657/124026645-f2c66000-d9bf-11eb-88d1-6a3f156d3ed4.png)

**Comment by AnnoyingB** [comment]
I installed cosmos. If that could be a problem?

**Comment by AnnoyingB** [comment]
And docker possibly

**Comment by AidanSun05** [comment]
As long as it's not running in the background (you can check with Task Manager - Ctrl+Shift+Esc - under the heading "Background Processes") it should be okay.

**Comment by AnnoyingB** [comment]
Well, docker is on as a background process so.

**Comment by AidanSun05** [comment]
Is there anything that's gobbling up your system resources (Docker can potentially do so) or using a lot of power? If your CPU, GPU, or RAM is getting topped off, that may be hindering your code's rendering.

**Comment by AnnoyingB** [comment]
Uh, no not really.

**Comment by AidanSun05** [comment]
There's too many variables at play here.

Run my example test code (remember it's at https://gist.github.com/AidanSun05/1b9023db840dd3ce95ffd3af37e488db - paste in the whole thing) and reply with what happens. Maybe you didn't copy something in correctly earlier?

**Comment by AnnoyingB** [comment]
That didn't work

**Comment by AidanSun05** [comment]
Does the example in the main repository work for you? (Download the docking branch ZIP, extract it, open `imgui-docking/examples/imgui_examples.sln`, then run the `example_glfw_opengl3` project)

**Comment by jrynkiew** [comment]
I'm no expert, but from your code I noticed that you declared dockspace over viewport, but you never actually added any windows to the dockspace.

**Comment by AidanSun05** [comment]
Hello @jrynkiew,

Dockspaces can be declared in a one-liner. If you do it like this, it will have no windows docked inside it. This is because the point of a dockspace is not to contain other windows, but to provide slots to dock windows into (user drags windows into the slots), if that makes any sense.

**Comment by jrynkiew** [comment]
Yeah, I deleted my message since it didn't make sense. I only realized after I posted :P

Wysłane z mojego BlackBerry — najbezpieczniejszego urządzenia mobilnego
Od: ***@***.***
Wysłano: 30 czerwca 2021 23:57
Do: ***@***.***
Odp. do: ***@***.***
DW: ***@***.***; ***@***.***
Temat: Re: [ocornut/imgui] ImGui Windows not showing (#4287)


Hello @jrynkiew<https://github.com/jrynkiew>,

Dockspaces can be declared in a one-liner. If you do it like this, it will have no windows docked inside it. This is because the point of a dockspace is not to contain other windows, but to provide slots to dock windows into (user drags windows into the slots), if that makes any sense.

**Comment by ocornut** [comment]
﻿If the menu bar shows its not an external problem. OP very probably made a mistake somewhere in the ImGui using code or in their app structure but as we are only seeing incomplete blurbs of the code or confirmation that “yes I have copied your code correctly and it doesn’t work” its hard to guess what the mistake is.

Start by fullfilling the issue template and pasting the contents of the About box, then try to disable multi-viewport if enabled. That’s the only thing I could imagine could interfere if somehow you had a weird/broken backend, which again we don’t know anything about because you omitted those information from the issue template.

**Comment by ocornut** [comment]
@AnnoyingB instead of vaguely stating “that didn’t work” please be very explicit about what you did and the output. I am pretty convinced Aidan’s last blurb should work and you didn’t set it up correctly.

For what it is worth, the mistake may be even that your project/ide is setup wrongly. Some people spend hours not even building or running the right executable. It could be anything, but if you are not providing us enough precise details we can’t narrow things down.

 Try to start from dear imgui stock examples (sln file in the repo) and confirm that it works.

**Comment by AnnoyingB** [comment]
Okay, I used ImGui::ShowDemoWindow() and then I get this:
ucrtbased.pdb contains the debug information required to find the source for the module ucrtbased.dll

**Comment by AnnoyingB** [comment]
Could this be the problem for the windows?

**Comment by AnnoyingB** [comment]
ShowDemoWindow works fine. But my code doesn't

**Comment by AnnoyingB** [comment]
If I try running the glfw example, it shows errors that it can't find stuff.

**Comment by AidanSun05** [comment]
Please be more specific.

First of all, are they really errors, or are they warnings? These are terms that people constantly use interchangeably, yet they are completely different.

What kind of error/warning is it? Linker errors (LNK2001/2019)? "[something].dll not found"? Please attach the full message text, and include all of the messages you encountered.

**Comment by AnnoyingB** [comment]
It can't find ImGui files.

**Comment by AidanSun05** [comment]
Which ones?

**Comment by AnnoyingB** [comment]
Can't find any

**Comment by AidanSun05** [comment]
Usually, the Visual Studio examples work out of the box, no setup required. Perhaps your include path is set wrong.

In your VS Property Pages, go to C++ > General and look at the "Additional Include Directories" option. It should match the entry in my screenshot below:

![image](https://user-images.githubusercontent.com/61399657/124172501-eef61480-da77-11eb-96fa-d005d6811e07.png)

**Comment by AnnoyingB** [comment]
Yes it does

**Comment by AidanSun05** [comment]
Are the #include errors from linting (red squiggles under the directives) or from compiling?

Try to run your project with the green Run Button. Does it compile successfully? (IntelliSense glitches out in VS a lot, this error might not be real.)

**Comment by AnnoyingB** [comment]
Uh, I can't open any files and yes I do click the run button, thats what I always do.

**Comment by AnnoyingB** [comment]
Oh I can open them now

**Comment by AidanSun05** [comment]
Did you change anything in any way?

**Comment by AnnoyingB** [comment]
No, but suddenly it works

**Comment by AnnoyingB** [comment]
Now i got an sdk error :/

**Comment by AnnoyingB** [comment]
Where do you find the SDK version 8.1 I only see version 10

**Comment by AidanSun05** [comment]
The SLN examples in the main repo are pretty outdated, try upgrading your platform toolset to v142. Older versions might not work with the Win10 SDK, they may be trying to use the Win8.1 SDK.

![image](https://user-images.githubusercontent.com/61399657/124174003-d38c0900-da79-11eb-8257-13d28aedc6c9.png)

**Comment by AnnoyingB** [comment]
Okay that did work on that project but my project doesn't work. Do you need some pictures of files or anything?

**Comment by AidanSun05** [comment]
To clarify, the examples can run perfectly now, but your own code still has the issue from yesterday, correct?

**Comment by AnnoyingB** [comment]
Yes.

**Comment by AnnoyingB** [comment]
It worked the day before and I didn't change anything and now it doesn't work

**Comment by ocornut** [comment]
FYI every message you are posting here are being sent to the inbox of 1000 people. If either of you have the goodwill to help @AnnoyingB with general programming help, please find a suitable chatting spot, and then you may report the results here.

**Comment by AnnoyingB** [comment]
after some tweaking it's working and the dockspace works aswell. is there any way to make it not be made at the bottom of the screen and also automatically set it's dockspace place?

**Comment by jrynkiew** [comment]
You need to define the dockspaces first, and then add windows to them. Alternatively you can use a library like hello_imgui which will make your life easier.

To do it yourself from scratch, I wrote something like this: (it's probably not optimal but it works)

    if(interface->setup_docking)
    {
        ImGui::DockBuilderAddNode(interface->dockspaceID, ImGuiDockNodeFlags_DockSpace | ImGuiDockNodeFlags_NoWindowMenuButton); // Add empty node
        ImGui::DockBuilderSetNodeSize(interface->dockspaceID, ImGui::GetCurrentContext()->CurrentViewport->Size);

        ImGuiID dock_main_id = interface->dockspaceID; // This variable will track the document node, however we are not using it here as we aren't docking anything into it.
        ImGuiID dock_id_left_menu = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Left, (interface->getStyle()->iconSize.x / ImGui::GetCurrentContext()->CurrentViewport->Size.x), NULL, &dock_main_id);
        ImGuiID dock_id_right_panel = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Right, 0.25f, NULL, &dock_main_id);

        ImGui::DockBuilderDockWindow("MainMenu", dock_id_left_menu);
        ImGui::DockBuilderDockWindow("Introduction", dock_id_right_panel);

        ImGui::DockBuilderFinish(interface->dockspaceID);

        ImGuiDockNode* node = ImGui::DockBuilderGetNode(dock_id_left_menu);
     node->LocalFlags |= ImGuiDockNodeFlags_NoTabBar | ImGuiDockNodeFlags_NoResize;

        interface->setup_docking = false;
    }
}

Then just

ImGui::Begin("MainMenu", NULL);

And "MainMenu" will be docked

Wysłane z mojego BlackBerry — najbezpieczniejszego urządzenia mobilnego
Od: ***@***.***
Wysłano: 12 lipca 2021 21:55
Do: ***@***.***
Odp. do: ***@***.***
DW: ***@***.***; ***@***.***
Temat: Re: [ocornut/imgui] ImGui Windows not showing (#4287)


after some tweaking it's working and the dockspace works aswell. is there any way to make it not be made at the bottom of the screen and also automatically set it's dockspace place?

**Comment by AnnoyingB** [comment]
Oh okay thanks
