### ISSUE TITLE
How do i center my text in a window? Something seems to be off:

### ISSUE THREAD

**Issue by whiskasdietgirl** [ocornut/imgui#4288]
```
std::string msg = "Cat walked down the road";
float font_size = ImGui::GetFontSize() * msg.size();

ImGui::SetNextWindowBgAlpha(0.00F);
ImGui::SetNextWindowPos(ImVec2(1920 / 2 - (font_size / 2), 1080/ 2)); // This centers my window according to the size of the message. perfect

ImGui::Begin("Check Window", 0, window_flags);
ImGui::SetWindowSize(ImVec2(font_size+300, 200)); //this should create a window size proportional to the message string.
ImGui::SetCursorPos(ImVec2(ImGui::GetWindowSize().x / 2 - (font_size / 2), 50));  //this should set the message in the middle
ImGui::TextColored(ImVec4(1.0f, 1.0f, 1.0f, 1.0f), msg.c_str());

ImGui::End();
ImGui::PopStyleVar(2);
```

Is there something im missing? The text comes off a bit uncentered. Like a bit too much to the left. Can anyone tell me why this is? Could it be that the conversion of:
`
float font_size = ImGui::GetFontSize() * msg.size();`

is not very accurate, but just an approximation?

**Comment by ocornut** [comment]
> float font_size = ImGui::GetFontSize() * msg.size();

This is not right. Font size = font height. Text size depends on actual text, you can use ImGui::CalcTextSize() with a given string to calculate the size of that text given the current font.

**Comment by ocornut** [comment]
> The text comes off a bit uncentered. Like a bit too much to the left.

Would have been easier if you posted a screenshot, but it may be due to window padding:
Your cursor X position starts at (Window Pos + Window Padding.x) and as you are centering between this and (Window Pos + Window Size.x) (right-most edge) your centering will be off.

```
| padding | contents ....................................................... | padding |
```

If you use `GetContentRegionAvail().x` instead of `ImGui::GetWindowSize().x` you will receive the right amount of available space taking account for window padding.

**Comment by whiskasdietgirl** [comment]
Thank you so much.
By just replacing the:
float font_size = ImGui::GetFontSize() * msg.size();
By:
float font_size = ImGui::CalcTextSize(msg.c_str()).x;
It works perfectly.
