### ISSUE TITLE
Do I need to create a separate Vulkan renderpass for imgui?

### ISSUE THREAD

**Issue by prostargamer** [ocornut/imgui#4289]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: MSVC 2019
Operating System: Windows 10

I am creating different sets of command buffers for rendering my graphics and for rendering imgui, I'm going to send them to the render together, however, when allocating command buffers and when recording, it is required to set renderpass.
Should I create a separate renderpass for imgui?

**Comment by prostargamer** [comment]
It seems that it is really needed.
I will re-open the question if I am wrong.

**Comment by ocornut** [comment]
The intent is that we should aim to provide a imgui_impl_vulkan.cpp backend that works for every user situation.
So if you end up finding that something needs to be changed please let us know and we can see if we can design some changes to allow it to work for you.

PS: if you ever decide to touch/edit the backend, please take note that _yesterday_ we pushed refactoring that touched most source lines of the backend, so best to update before making any change.
