### ISSUE TITLE
InputText widget enters text in reverse order when highlighted right-to-left with mouse that goes out of window

### ISSUE THREAD

**Issue by dsusini** [ocornut/imgui#429]
I'm using the latest "dev" version of ImGui from the repo.

For a few days I was having an issue where sometimes when I highlighted some InputText() with the mouse it would enter in reverse order.  So for instance, if I typed "test" it would show as "tset".  I tried to  make it occur in your demo application but couldn't, so I ignored it for a few more days until I got fed up again and I decided it was time to figure this out.

I found that if I select text in an InputText() from right-to-left and continue holding the mouse button down as I type, this bug occurs, even in your demo app.  I then realized that the InputText in my application was very close to the left-hand side of the window.  I went and selected the InputText in your demo app and let the mouse cursor fall off the left-hand side of the window and released the button.  Now the text was entering in reverse.

This can happen pretty easily if you're working quickly in a windowed application with a "form" on the left-hand side of the window and may be confusing for others.  Maybe this could be prevented in future updates?

I appreciate any help you can offer.  I love the framework and am really starting to enjoy working with it.  Thank you.

**Comment by dsusini** [comment]
After more testing, it looks like this issue only happens when holding down the mouse button and typing.  I just realized that my input system wasn't clearing mouseDown flags when the mouse left the screen. So my issue isn't really the same as what was described above.  I'm not sure if it's working as designed that if you hold the mouse button after selecting the text it writes in reverse, but if I fix my input issue, it shouldn't really be a problem anymore.  I can't imagine anyone would type while holding the mouse button.

I'm glad it helped me find this bug in my input code though :)

**Comment by ocornut** [comment]
Dominique,
Nice find, I never noticed it before. Also thanks for making such a clear report.
It looks like a standard behavior (at least, tested with Windows) would be clear the mouse-selecting state if text has been input, but it gets restored if and only if the mouse move again past the usual initial threshold. It is a bit odd and the sort of behavior we rarely notice but it would help handling this case without losing the mouse control (which to a lesser degree would also be odd, but still better than current behavior). I will look into first this.

**Comment by ocornut** [comment]
OK I think I got the right fix for that (involved a change in stb_textedit which I will submit there!).

**Comment by dsusini** [comment]
Awesome.  Thanks Omar!
