### ISSUE TITLE
Docking without tabs

### ISSUE THREAD

**Issue by timeinpixels** [ocornut/imgui#4292]
Is it possible to use docking but disable the ability to dock multiple windows into the same area - basically to prevent creating tabs?

**Comment by ocornut** [comment]
Hello,

(1) First of all, to obtain a [XY Problem](https://xyproblem.info) question please always try to explain WHY you are asking for this.

(2) See #3492, you may get some success using

```cpp
ImGuiWindowClass window_class;
window_class.DockNodeFlagsOverrideSet = ImGuiDockNodeFlags_NoDockingOverMe;

ImGui::SetNextWindowClass(&window_class);
ImGui::Begin("Window1");
ImGui::End();

ImGui::SetNextWindowClass(&window_class);
ImGui::Begin("Window2");
ImGui::End();

ImGui::SetNextWindowClass(&window_class);
ImGui::Begin("Window3");
ImGui::End();
```

But it's rather experimental and would probably get you into various edge cases, depending on what you are docking into, if you are relying on empty dockspace, dock builder, if you are relying on persisting settings etc.

**Comment by ocornut** [comment]
I actually went through this and made various improvements:

9e8e5ac
Docking: Added `ImGuiDockNodeFlags_NoDockingOverEmpty`. Breaking older definition of `ImGuiDockNodeFlags_NoDockingOverOther` which now means "non empty node".
So if you update by using `ImGuiDockNodeFlags_NoDockingOverOther` it'll correctly allow to dock over an empty dockspace node if one was already there.

6136b38
Fixed various issues leading `DockNodeFlagsOverrideSet` flags coming from windows to stay in dockspace nodes after the windows has been removed. Not thoroughly but this should fix variety of issues, hence why linking to so many issues.

**Comment by timeinpixels** [comment]
> (1) First of all, to obtain a [XY Problem](https://xyproblem.info) question please always try to explain WHY you are asking for this.

Sorry for that - due to specific architecture of my app I would like to have all the windows visible at all times.
Allowing tabbed interface would require extra things to be implemented and I don't want to go there.

Seems the flag `ImGuiDockNodeFlags_NoDockingOverMe` does what I need - thanks!

**Comment by ocornut** [comment]
I think you’ll want to use `ImGuiDockNodeFlags_NoDockingOverOther | ImGuiDockNodeFlags_NoDockingOverMe`

Closing this!
