### ISSUE TITLE
Change imgui.ini saving location

### ISSUE THREAD

**Issue by CatoNator** [ocornut/imgui#4294]
I am using `1.78.0`, the latest stable NuGet version.

Right now by default imgui.ini is saved into the working directory of the program, which is dependent on various factors.

My program can be launched using file associations and it also uses the win32 file dialog, both of which change the location of the working directory. As a result, the program tends to plaster imgui.inis absolutely everywhere, which makes managing the windows a pain and also fills every folder on my PC with useless junk.

Is there a way to set imgui.ini to just save in one set location, like the location of the program itself?

**Comment by ocornut** [comment]
You change `io.IniFilename` to point to your own filename (pointer data owned by you)

Or you can set `io.IniFilename = NULL` and manage loading/saving yourself using the provided functions
`LoadIniSettingsFromDisk()`, `LoadIniSettingsFromMemory()`, `SaveIniSettingsToDisk()`, `SaveIniSettingsToMemory()` and by polling `io.WantSaveIniSettings` to know when to save.

**Comment by Gargaj** [comment]
There's an additional concern with this: If the application running ImGui changes the working directory (because e.g. it opened am open file dialog), the next imgui.ini will get written to a different place before because by default it has no explicit path to it.

I understand that the application can enforce an explicit path for the imgui.ini, however the out-of-the-box behaviour often litters the entire hard disk with imgui.ini-s which I feel can be frustrating default behaviour.

**Comment by ocornut** [comment]
@Gargaj I'm not sure what can possibly be a another (better) default behavior.?
It should be up to the application to change this value if it expects to be executed with different working directory. We can't really provide a better default in a portable manner :(

**Comment by Gargaj** [comment]
"Portable" is tricky (there is no good POSIX way to get the EXE path but you can at least use `getcwd()` for the starting dir), but I wonder if it'd be worth it to just fix it on Windows to cover the potentially most common use case.

Alternatively, it could be something that's slightly more documented or at least FAQ'd, just so that people get a more common Google result when they look for "`imgui.ini wtf everywhere site:github.com`"

**Comment by ocornut** [comment]
We could, but if in the backend we would stumble on init ordering issue, as people may initialize `io.IniFilename` _before_ the backend, so if we do it we'd need to it do inside core imgui (not out of question, depending where the exact functions we are calling are located in terms of standard libs)

> Google result when they look for "imgui.ini wtf everywhere site:github.com" :)

Well, NOW they will :)

**Comment by OverLorDXG** [comment]
If you are having problems regarding **ImGui** creating **".ini"** files when selecting a file using **Open File Dialog**, just add **OFN_NOCHANGEDIR** to the **OPENFILEDIALOG** Flags. For Example : 
`OPENFILENAME ofn;
    ofn.lStructSize  = sizeof( ofn );
    ofn.hwndOwner    = NULL;
    ofn.lpstrFilter  = ".ini File\0*.ini\0All Files\0*.*\0";
    ofn.lpstrFile    = YOUR_FILENAME_VAR;
    ofn.nMaxFile     = MAX_PATH;
    ofn.lpstrTitle   = "File Select";
    ofn.Flags        = OFN_DONTADDTORECENT | OFN_FILEMUSTEXIST | OFN_NOCHANGEDIR;`

**Comment by ocornut** [comment]
The default value is “imgui.ini” which means “in current directory”. A proper app would either not change current directly, either simply change IniFilename to point to an fully qualified directory (possibly created from the location of the exe, of in user’s appdata etc.)

**Comment by ravo10** [comment]
I made an installer and had to store the "imgui.ini" in the local appdata folder. Probably not the cleanest methode, but it works. It was tricky since I had to make a clean copy of the path, or else it failed... (a little unexperienced)

This is how I did it:

```
// For getting the AppData folder
#include <stdlib.h>
#include <shlobj_core.h>
#include <direct.h>

#include <string>
#include <filesystem>
```

```
inline char* CopyString(const char s[], int size)
{
    char* s2;
    s2 = (char*)malloc(((size + 1) * sizeof(char)));

    if (s2) strcpy(s2, s);
    return (char*)s2;
}
```

```
std::pair<bool, std::string> GetLocalAppDataFolder()
{
    // Get the AppData folder
    wchar_t* localAppData;
    if (SHGetKnownFolderPath(FOLDERID_LocalAppData, KF_FLAG_CREATE, NULL, &localAppData) == S_OK)
    {
        // Apply folder to AppData
        std::wstring ws(localAppData);
        std::string newDest(ws.begin(), ws.end());
        newDest.append("\\YourFolderName");

        // Create directory if it doesn't exist
        if (!std::filesystem::exists(newDest)) std::filesystem::create_directory(newDest);

        // Make the path ready for the folder for receiving files
        newDest.append("\\");

        return { true, newDest };
    }
    else return { false, "" };
}
```

_imgui.cpp => ImGuiIO::ImGuiIO()_:
```
 std::pair<bool, std::string> appDataFolderPath = GetLocalAppDataFolder();

    if (appDataFolderPath.first)
    {
        // Get the Local AppData path and add "imgui.ini" to it
        std::string path = appDataFolderPath.second;
        path.append("imgui.ini");

        // Create a clean char copy (is necessary)
        char* pathNew;
        pathNew = CopyString(path.c_str(), path.size());

        IniFilename = pathNew;
    }
```

**Comment by 0R0D** [comment]
> If you are having problems regarding **ImGui** creating **".ini"** files when selecting a file using **Open File Dialog**, just add **OFN_NOCHANGEDIR** to the **OPENFILEDIALOG** Flags. For Example :

This was very helpful.  Thank you.

**Comment by msimic** [comment]
Whoever closed this issue should aks himself: "has the issue been solved?".
The answer is no.
The file should be saved by default in the path of the binary that was launched not in the current working dir on closure which can be changed in a miriad of different scenarios and sometimes should not point at the location of the executable at all.

**Comment by msimic** [comment]
> If you are having problems regarding **ImGui** creating **".ini"** files when selecting a file using **Open File Dialog**, just add **OFN_NOCHANGEDIR** to the **OPENFILEDIALOG** Flags. For Example :
> 
> `OPENFILENAME ofn;` `ofn.lStructSize = sizeof( ofn );` `ofn.hwndOwner = NULL;` `ofn.lpstrFilter = ".ini File\0*.ini\0All Files\0*.*\0";` `ofn.lpstrFile = YOUR_FILENAME_VAR;` `ofn.nMaxFile = MAX_PATH;` `ofn.lpstrTitle = "File Select";` `ofn.Flags = OFN_DONTADDTORECENT | OFN_FILEMUSTEXIST | OFN_NOCHANGEDIR;`

This unfortunately works only when your code opens a dialog, and not when third parties do or chil processes.
It should be fixed by imgui by using the program location instead of the current working path.

**Comment by cfillion** [comment]
> Whoever closed this issue should aks himself: "has the issue been solved?".
> The answer is no.
> The file should be saved by default in the path of the binary that was launched,

So just set `io.IniFilename` to that? The default value is just that: the default. That API is there for customizing the path to anything you need (can even roll your own non-file-based storage mechanism!).

(The executable's directory is less likely to be user-writable than the working dir... I think the current default value of just "imgui.ini" keeps things simple, unassuming and is adequate for development.)

**Comment by ocornut** [comment]
> Whoever closed this issue should aks himself: "has the issue been solved?".
> The answer is no.

There is no single correct answer, let alone one on our end.
It is up to the application to do this based on where they prefer to store the data.

> Boost has a method called program_location to retrieve this.

You can absolutely use this if that's your preferred solution?
