### ISSUE TITLE
Getting Black patches when using custom Font.

### ISSUE THREAD

**Issue by techGuyAj** [ocornut/imgui#4300]
Hi All.
I am new to imgui . I tied to load the custom font with the following code below:

 ImGuiIO& io =ImGui::GetIO();
        ImFont* font1 = io.Fonts->AddFontFromFileTTF("./Assets/Fonts/Arial.ttf",48);
        io.Fonts->Build();
        ImGui::Text("Hello");
        ImGui::PushFont(font1);

But I am getting the black patches in the place of letters.
Am I missing something?
Please help.
Attached a screenshot below.
Thank you.
![Screenshot (98)](https://user-images.githubusercontent.com/71086462/124884152-a72f3a00-dfef-11eb-9426-c0c9fe859e59.png)

**Comment by techGuyAj** [comment]
Solved:

Initially, the code is in the render loop. I pulled the code out of the render and added it into the init . It Worked.

Thank you.

I am not deleting the issue because someone who is a beginner like me can use this.

**Comment by ocornut** [comment]
There is a FAQ entry:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-i-integrated-dear-imgui-in-my-engine-and-little-squares-are-showing-instead-of-text

**Comment by ocornut** [comment]
FYI, work on `dynamic_fonts` branch aimed to be merged in 1.92 (#8465) solves this, as glyphs are rasterized and packed on demand when they are used.
