### ISSUE TITLE
How can I detect the occurrence of AddRectFilled in another AddRectFilled?

### ISSUE THREAD

**Issue by Kronka** [ocornut/imgui#4302]
Hello everyone
Earlier I saw a topic somewhere here that you can check that a widget is included in another one. I needed to check the occurrence of addrect, but I don't know how to do it. Thank you in advance
For example, I want to check that this is true
![image](https://user-images.githubusercontent.com/33985574/124991724-b42d4700-e04a-11eb-9bc0-2bbfb23d2db2.png)
it is false
![image](https://user-images.githubusercontent.com/33985574/124991831-d626c980-e04a-11eb-9d9c-1973dd4d58cb.png)

**Comment by ocornut** [comment]
As phrased, you cannot.
