### ISSUE TITLE
Capture mouse wheel event

### ISSUE THREAD

**Issue by iamthebest77** [ocornut/imgui#4303]
Hi,

I want to capture the event when mouse is hovered and mouse wheel is scrolled on a rectangle in a window. Based on the mouse wheel event, I have to increment or decrement text value. 

The red circled portion in the below image is the rectangle. When the user moves mouse wheel over that rectangle, I want to increment or decrement the value '1150' depending upon direction of wheel movement.

I am developing this on Windows 10 and using v1.82 of Dear ImGUI.
P.S. : I am new to c++ and ImGUI.

![image](https://user-images.githubusercontent.com/13537446/125057536-f7c59680-e0c6-11eb-8c85-2b9f818c7ce4.png)

// Here's the code snippet
       
     draw_list->AddRectFilled(ImVec2(p.x + 6, p.y + 161), ImVec2(p.x + 64, p.y + 479), col_black);
   
    if(ImGui::IsItemClicked() || ImGui::IsItemHovered()) 
    {

        mouseFloat += ImGui::GetIO().MouseWheel;

    }

    std::stringstream ss;
    ss << mouseFloat;
    mouseString = ss.str();
    const char* floatval = mouseString.c_str();

    draw_list->AddText(ImVec2(p.x+44, p.y + 45), IM_COL32_WHITE, floatval); 

```

**Comment by PathogenDavid** [comment]
`AddRectFilled` only draws a rectangle on screen, it doesn't create an item. So `IsItemClicked`/`IsItemHovered` won't work on it.

The easiest solution would probably be to add an `InvisibleButton` item that covers your rectangle.

There are some examples for using it this way in the examples. In particular the [clipping sample](https://github.com/ocornut/imgui/blob/cc40ae2101acd1fb4e0585a46198e6fd12960617/imgui_demo.cpp#L3045-L3050) and the [canvas sample](https://github.com/ocornut/imgui/blob/cc40ae2101acd1fb4e0585a46198e6fd12960617/imgui_demo.cpp#L7244-L7263).

**Comment by ocornut** [comment]
In addition, note that by default mouse wheel will trigger scrolling.
To claim the mouse wheel you'll need to use `SetItemUsingMouseWheel()` currently declared in imgui_internal.h, you can call that function after your item. As suggested if you are drawing all elements yourself you'll probably want to use `InvisibleButton()`, so you would do:

```cpp
InvisibleButton(...)
SetItemUsingMouseWheel(....)
if (ImGui::IsItemHovered())
{
    // use io.MouseWheel
}
```
(linking to #4207, #3281, #2891)

**Comment by iamthebest77** [comment]
Thank you so much. It worked.

**Comment by pers0na2** [comment]
Wouldn't it be better to use ImGui::IsMouseHoveringRect()?
