### ISSUE TITLE
Imgui save/load controls state

### ISSUE THREAD

**Issue by aabilityuk** [ocornut/imgui#4306]
Hi, i am really new to ImGui and i want you to give me a help with a simple task.

How to save state of checkbox and load the last state on Imgui window stratup? Please give a code sample if it possible

**Comment by ocornut** [comment]
Hello,

Dear ImGui does NOT own the underlying data exposed in widgets, that's practically the whole point of this library.
You entirely own it and if there are things to load/save it is completely under your control and responsibility.

**Comment by aabilityuk** [comment]
@ocornut 

Thank you for reply! If you already have an experience how to implement load/save pattern could you share it please? I know how to serrialize/desserialize to/from file, but how to upload this state to checkbox or combobox or some other controls if they are all in the infinite loop...

**Comment by ocornut** [comment]
Sorry this is more of a generic programming question which doesn't have much to do with Dear ImGui itself, I don't have resources to provide answers for everything (maybe other will fancy helping but in term of Dear ImGui Issues I'm closing this).
