### ISSUE TITLE
Selectable tree node

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#431]
Hi,

I need a tree with selectable nodes. The current tree does not allow this. I have try using "Selectable+Indent" as leaf and normal tree node for inner nodes but:
- only the selectable are "selectable"
- the selectables (even with Indent) are not well aligned with the tree node.

So, I think to create my own TreeNode like widget, here is my current code:

```
bool SelectableTreeNode(const char* label, bool isSelected, bool hasChildren)
{
	// Selection
	if (isSelected)
	{
		ImU32 col = ImColor(ImGui::GetStyle().Colors[ImGuiCol_HeaderHovered]);
		/*x += os.x;
		y += os.y;
		ImGui::RenderFrame(ImVec2(x, y), ImVec2(x + itemFullWidth, y + itemFullHeight), col, true, 3.f);
		x -= os.x;
		y -= os.y;*/
	}

	ImGui::PushID(label);
	const bool opened = ImGui::CollapsingHeader(label, "", false);
	ImGui::PopID();

	if (opened)
		ImGui::TreePush(label);

	return opened;
}
```

But how can I :
- know the area of the treenode (see RenderFrame)
- Hide the Triangle/Arrow based on the "hasChildren" parameter

Any idea ?

**Comment by ocornut** [comment]
Could you move this to #190 ?

**Comment by ocornut** [comment]
Moved to #190
