### ISSUE TITLE
ImGui book

### ISSUE THREAD

**Issue by aabilityuk** [ocornut/imgui#4312]
Hi, is there any ImGui book or tutorial? I want to learn how to program custom nodes., i need to know how to set colors for different PinTypes, how to arrange the pins inside the node and so on/

Thank you

**Comment by rokups** [comment]
There is no book, however there is lots of useful information in the [wiki](https://github.com/ocornut/imgui/wiki) and [demo](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp).
