### ISSUE TITLE
Support for rendering 3d text

### ISSUE THREAD

**Issue by KOLANICH** [ocornut/imgui#4313]
It may be possible to implement rendering of text not via texture atlases, but as 3d objects. Though ih the most of use cases it would be inefficient,  as an optimization for the simplest cases of static not occluded glyphs a texture can still be used to cache 2d images of 3d-rendered glyphs. In more dynamic cases when all the glyphs are transfirmed uniformly again a texture can be used, but would have to be regenerated each time the glyphs are transformed. It may be possible to use a LRU cache here.

https://github.com/fetisov/ttf2mesh may be helpful for that. It is a library triangulating fonts.

**Comment by PathogenDavid** [comment]
See also: https://github.com/ocornut/imgui/issues/3365 https://github.com/ocornut/imgui/issues/3406 https://github.com/ocornut/imgui/issues/2365 https://github.com/ocornut/imgui/pull/4056 https://github.com/ocornut/imgui/pull/3761 https://github.com/ocornut/imgui/pull/2986 https://github.com/ocornut/imgui/issues/797 and finally https://gankra.github.io/blah/text-hates-you/

I don't think Dear ImGui's lack of better text rendering is for lack of ideas, it's more that it's a really hard problem to solve in a generic way which is both performant and flexible.

The [current plan](https://github.com/ocornut/imgui/pull/4056#issuecomment-824138402) is to merge https://github.com/ocornut/imgui/pull/3761 and then work towards updating the font atlas dynamically.

**Comment by ocornut** [comment]
Hello,

You didn’t explain what you are trying to solve with this, you are suggesting a solution to an unknown problem.
