### ISSUE TITLE
Menu and images colors are too bright

### ISSUE THREAD

**Issue by Skreamex** [ocornut/imgui#4314]
![issue](https://user-images.githubusercontent.com/6390209/125413502-227085af-2e5f-4842-82cf-207c4dbc3962.png)
Here is an example screenshot how same image looks
The original is being drawn from engine render
The d3d image ( pasted from example ) looks too bright

bool LoadTextureFromFile(ID3D11ShaderResourceView** out_srv)
{
	// Load from disk into a raw RGBA buffer
	int image_width = 128;
	int image_height = 128;
	unsigned char* image_data = (PBYTE) texture_bytes_d3d;// stbi_load(filename, &image_width, &image_height, NULL, 4);
	if (image_data == NULL)
		return false;

	// Create texture
	D3D11_TEXTURE2D_DESC desc;
	ZeroMemory(&desc, sizeof(desc));
	desc.Width = image_width;
	desc.Height = image_height;
	desc.MipLevels = 1;
	desc.ArraySize = 1;
	desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;// DXGI_FORMAT_B8G8R8A8_UNORM
	desc.SampleDesc.Count = 1;
	desc.Usage = D3D11_USAGE_DEFAULT;
	desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
	desc.CPUAccessFlags = 0;

	ID3D11Texture2D* pTexture = NULL;
	D3D11_SUBRESOURCE_DATA subResource;
	subResource.pSysMem = image_data;
	subResource.SysMemPitch = desc.Width * 4;
	subResource.SysMemSlicePitch = 0;
	pd3dDevice->CreateTexture2D(&desc, &subResource, &pTexture);

	// Create texture view
	D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc;
	ZeroMemory(&srvDesc, sizeof(srvDesc));
	srvDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
	srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
	srvDesc.Texture2D.MipLevels = desc.MipLevels;
	srvDesc.Texture2D.MostDetailedMip = 0;
	pd3dDevice->CreateShaderResourceView(pTexture, &srvDesc, out_srv);
	pTexture->Release();

	//stbi_image_free(image_data);

	return true;
}

Also other stuff like rects, lines are too bright

**Comment by ocornut** [comment]
It is either a gamma issue in the setup or a srgb/linear blending mismatch issue. 
Unfortunately it is out of our scope to be helping you with that. Try to use RenderDoc to compare render state to find out the difference or read about those topics.
