### ISSUE TITLE
DirectX 11 SubSystem set to Windows (/SUBSYSTEM:WINDOWS) not work

### ISSUE THREAD

**Issue by HODAKdev** [ocornut/imgui#4316]
Hi, I have a DirectX 11 project and when I include imgui .cpp and .h files and have it compiled so it shuts down right away.
![files](https://user-images.githubusercontent.com/82084934/125449311-6141fc02-9162-473b-bec5-f75d56d3f8b5.PNG)
Files I used.
https://user-images.githubusercontent.com/82084934/125449793-7f1b0233-af63-4eb1-b77b-e8c77e591fad.mp4
I didn't even use #include "imgui.h"...
In example project for directx 11 you used Console (/SUBSYSTEM:CONSOLE) but I would like it for the Windows (/SUBSYSTEM:WINDOWS) is possible?
![abc](https://user-images.githubusercontent.com/82084934/125450880-6671c60e-8180-4200-8737-177388b9e09f.PNG)
https://user-images.githubusercontent.com/82084934/125451168-3261e859-70ec-40f5-9091-95ef4d9eba66.mp4
Thank you for any help and sorry for my English. 😉

**Comment by PathogenDavid** [comment]
Building `example_win32_directx11` with `/SUBSYSTEM:WINDOWS` and the entry-point fixed `main` works just fine for me.

This doesn't really have anything to do with Dear ImGui, it doesn't care about stuff like this.

You need to use the debugger to determine why your app is exiting instantly. (For example: From the little you've shared I can see your app closes without error if `InitWindow` fails.)

**Comment by Demonese** [comment]
Windows subsystem need WinMain/wWinMain entry point, not main

**Comment by PathogenDavid** [comment]
Sorry that was a typo. I meant to imply I fixed it to `wWinMain`.

(Although you can still use the classic `main` if you explicitly enable it. That's what I originally did out of habit. but I confirmed `wWinMain` works as expected as well.)
