### ISSUE TITLE
Getting window data outside of Begin() / End()

### ISSUE THREAD

**Issue by Aang23** [ocornut/imgui#4327]
**Version/Branch of Dear ImGui:**

Version: 1.82
Branch: master

**My Issue/Question:**

Hi!
This is more of a quick question as I am not sure about the best way to approach a problem.

In my software using ImGui, the user can select different options which will then bring up a few resizable windows. But well, on each restart every window's position goes back to default requiring the user to move / resize them manually everytime.
Hence, I would want to serialize all positions / sizes in my persistent data json file alongside other settings and set them again when the user opens up the same thing again.

As of now, the only viable way I thought about to do this is to manually implement some kind of registry in every single window which would set / read all this data from GetWindowSize / GetWindowPosition etc.
But that would actually be quite some work and I've noticed ImGui already has data kept persistent well, until the context is destroyed.

Is there any way to get that data outside of the ImGui::Begin() / ImGui::End() setting? Something that would allow me save / restore such states would be pretty much perfect and in my case a lot cleaner than handling it manually.

Thanks!

**Comment by Aang23** [comment]
Actually, I believe I could just deal directly with the ImGuiContext, but I'm not quite sure how clean that would be.

**Comment by ocornut** [comment]
There’s already an ini settings systems and window pos/size are all saved by defaults.

So if things don’t save start looking at what’s interfering, what you disabled or which option you used.

**Comment by Aang23** [comment]
Oh thanks! I am currently using the glfw / opengl3 implementation with only minor modification to the provided example.

Where could I find some documentation this saving system? I just looked on the Wiki and did not seem to find much reference about it, though I will probably be better off looking directly in the source code.

**Comment by PathogenDavid** [comment]
> Where could I find some documentation this saving system?

It should just work automatically. The default is to save `imgui.ini` in your app's working directory.

You can configure it with these options in `ImGuiIO`:

https://github.com/ocornut/imgui/blob/17ec4f1f6fa64a08892d8dcfa61ace684bae53fc/imgui.h#L1802-L1803

and you can exert manual control over them using these functions:

https://github.com/ocornut/imgui/blob/17ec4f1f6fa64a08892d8dcfa61ace684bae53fc/imgui.h#L898-L904

If `IMGUI_DISABLE_DEFAULT_FILE_FUNCTIONS` is defined, then your implementation of `ImFileOpen`, etc will be used to read and write the file.

**Comment by ocornut** [comment]
@Aang23 I'm closing this for now as your question appears to be a [XY Problem](https://xyproblem.info) and you haven't clarified how your application is not saving since it is done by default.
If you have an actual issue with saving please investigate this and open a dedicated issue.
