### ISSUE TITLE
example_sdl_opengl3 rendering issue

### ISSUE THREAD

**Issue by kshanik** [ocornut/imgui#4329]
I compiled example_sdl_opengl3 on top of latest sdl2. I am getting following rendering issues. What could go wrong?

![image](https://user-images.githubusercontent.com/1548915/125958631-1ebd9cef-57d6-4fc9-9871-ac430f5f5b9a.png)

**Comment by PathogenDavid** [comment]
That's certainly...interesting.

Did you try updating your graphics drivers to rule out weirdness there?

**Comment by kshanik** [comment]
No I did not upgraded graphics driver anytime recently. Below is the load the gpus while example app is running.

![image](https://user-images.githubusercontent.com/1548915/125964538-9ea1de41-0abf-4d9a-af7b-40d396d12009.png)

Version of intel one is 

![image](https://user-images.githubusercontent.com/1548915/125964657-533ab8ac-5aed-40f8-a058-3a27c0b3ede0.png)

**Comment by PathogenDavid** [comment]
> Shall I upgrade graphics driver and check?

Since your issue is so weird and your drivers are so old that'd be my recommendation.

If you're feeling lazy, here's the drivers for both your Intel and NVIDIA cards respectively:

* https://downloadcenter.intel.com/download/30579/Intel-Graphics-Windows-DCH-Drivers
* https://www.nvidia.com/Download/driverResults.aspx/176854/en-us

**Comment by kshanik** [comment]
After switching to nvidia example application works fine.

![image](https://user-images.githubusercontent.com/1548915/125971055-71b8dd6f-2d31-454d-b3a4-fc55a8b15780.png)

Anyways I am updating the driver for both the gpus and will update what happens when i switch back to intel.

**Comment by kshanik** [comment]
After upgrading the driver everything works fine!

On both intel and nvidia.

@PathogenDavid  Thanks!
