### ISSUE TITLE
Make BeginPopupContextItem pass ImGuiWindowFlags_NoMove by default?

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#4330]
It's intuitively expected for context menus not to move.

More generally, it's inconvenient `BeginPopupContextItem()` doesn't take window flags. Problem is, `BeginPopupContextItem()` basically combines two separate pieces of logic, the "should we show context" check and the `BeginPopupEx()` call. If you want to pass in window flags, you basically have to rip out the "should we show context" check (which is more than a few lines) and call `BeginPopupEx()` yourself.

Possible solutions would include having a "IsItemRequestedContextMenu" function, or to have a "BeginPopupContextItemEx" function that takes window flags.

**Comment by ocornut** [comment]
> It's intuitively expected for context menus not to move.

This has been been discussed before: #2763 (appears when searching for `ImGuiWindowFlags_NoMove` + `popup`.

While I understand it is intuitively expected to be as such, it seems harmless to allow popups to be moved by default. Mimicking "standard behavior" yield no benefits IHMO, in fact we'd only be mimicking an unnecessary constraint. What is your issue with it?

**Comment by invrainbow** [comment]
In terms of design, my impression was that BeginPopupContextItem implies the popup is of a specific type: a context menu. I agree popups should probably move by default, but allowing context menus to be dragged around as if they're windows part of a larger workspace is a weird design. Arguably the name itself implies the menu should be pegged to a certain context, i.e. the place you right clicked.

That said, passing in ImGuiWindowFlags_NoMove manually isn't the end of the world. Issue with that is, as mentioned, right now BeginPopupContextItem doesn't let you pass window flags, so you basically have to copy paste the whole function so you can add flags to BeginPopupEx. Is it possible to make that process easier?
