### ISSUE TITLE
Penetration compatible components

### ISSUE THREAD

**Issue by DIXIN20** [ocornut/imgui#4332]
The mouse can penetrate without affecting the operation of the game, and can click on the components of imgui. At present, I can either penetrate the components that cannot be clicked on imgui, or can click and cannot operate the game.
----------------------------------------------------------------------------------------------------------------------------
	WNDCLASSEX wc;
	wc.cbClsExtra = NULL;
	wc.cbSize = sizeof(WNDCLASSEX);
	wc.cbWndExtra = NULL;
	wc.hbrBackground = (HBRUSH)CreateSolidBrush(RGB(0, 0, 0));
	wc.hCursor = LoadCursor(0, IDC_ARROW);
	wc.hIcon = LoadIcon(0, IDI_APPLICATION);
	wc.hIconSm = LoadIcon(0, IDI_APPLICATION);
	wc.hInstance = GetModuleHandle(0);
	wc.lpfnWndProc = WndProc;
	wc.lpszClassName = M_Name;
	wc.lpszMenuName = M_Name;
	wc.style = CS_VREDRAW | CS_HREDRAW;
	if (!RegisterClassEx(&wc))
		exit(1);

	hwnd = CreateWindowEx(WS_EX_TOPMOST | WS_EX_TOOLWINDOW | WS_EX_TRANSPARENT, M_Name, M_Name, WS_POPUP, 0, 0, 1000, 800, NULL, NULL, 0, NULL);
	DwmExtendFrameIntoClientArea(hwnd, &Margin);
	ShowWindow(hwnd, 10);                                       
	UpdateWindow(hwnd);                                        
	///SetWindowLong(hwnd, GWL_EXSTYLE, WS_EX_LAYERED);
SetWindowLong(hwnd, GWL_EXSTYLE, WS_EX_LAYERED | GetWindowLongA(hwnd, GWL_EXSTYLE));

**Comment by ocornut** [comment]
Sorry but #1586 
It’s been a while
