### ISSUE TITLE
Button clickable but other graphics needed not to be clickable

### ISSUE THREAD

**Issue by pp9999** [ocornut/imgui#4333]
Version/Branch of Dear ImGui:
Version: 1.83
Branch: docking

Back-end/Renderer/Compiler/OS
Windows 10
Microsoft Visual Studio Community 2019
Windows SDK: 10.0.18362.0
Platform toolset: v142
C++ standard: C++17
C: C17

My issue:
I use it for game debugging. I made some buttons to turn debug off/on that is fine.
But issue is that debug info gets in the way of mouse clicking. Mouse clicks stop on debug surface.
So how would one make so that buttons would be clickable but debug info wouldn't be?

**Comment by ocornut** [comment]
Hello,

> So how would one make so that buttons would be clickable but debug info wouldn't b

That's not possible because hovering needs to be process on a window basis.
However, if you separate your windows (one for buttons, one for text) then you can use the `ImGuiWindowFlags_NoInputs` flag on text to have inputs pass through that specific window.
