### ISSUE TITLE
Open and close specific tab without clicking on them

### ISSUE THREAD

**Issue by peterwilson136** [ocornut/imgui#4335]
Hello,
I am wondering if there is a way that you can set specified tab bars status without clicking on them. For example,
```
if (ImGui::Begin("Mainscreen", nullptr, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoMove)) {
        if (ImGui::BeginTabBar("Tab Bar")) {
            if (ImGui::BeginTabItem("Tab1")) {
                Homescreen::Mainloop();
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem("Tab2")) {
                ImGui::EndTabItem();
            }
            ImGui::EndTabBar();
        }
        ImGui::End();
    }
```

Within either of these tab bars, say in `Homescreen::Mainloop()` I click a button that says "Switch to tab bar 2" I would like it to close the tab bar "Tab1" and open "Tab2". Is this possible?

Thanks!

**Comment by WarEagle451** [comment]
Yes, there is a tab item flag called "ImGuiTabItemFlags_SetSelected", when this is called it will set that tab to the active tab for that bar. The easiest way I've found to do this is like this
`bool Tab(const char* label, bool* open, bool* wantSelected)`
`{`
`bool b = ImGui::BeginTabItem(label, &open, *wantSelected ? ImGuiTabItemFlags_SetSelected : 0));`
`if (*wantSelected) *wantSelected = false;`
`return b;`
`}`

**Comment by ocornut** [comment]
>  I would like it to close the tab bar "Tab1" and open "Tab2". Is this possible?

This is ambiguous. Given the full issue it's not sure if you want to only select "Tab2" (answered by @WarEagle451) or if you want to actually CLOSE "Tab1" which is another thing.

Tabs visibility is entirely up to what you submit, normally you'd carry the visibility state of your tabs the same way you'd carry the visibility state of your windows (e.g. by holding on a `bool IsTab1Visible, IsTab2Visible` and only submit when true. Therefore you can "close" a tab by setting your own state to false.

Also note you can pass an optional pointer to bool to `BeginTabItem()` and the bool will be set to false when the user clicks the close button of the tab.

**Comment by peterwilson136** [comment]
Not as in, have an "Open" tab, rather know which tab is active and toggle which one should be active without having to click on it. I.e. 
```
if (ImGui::BeginTabItem()){}
```
will return true if it is active, How can I say, "Don't set this tab bar to be active but still display it" from elsewhere in the code?

**Comment by ocornut** [comment]
Ah Noah answered, currently you can use the ImGuiTabItemFlags_SetSelected flag. Its a little bit awkward but should solve your problem.

(Strictly speaking the terminology is “selected”, not “active”. “Active” means something else in dear imgui land)

**Comment by peterwilson136** [comment]
Oh, My apologies, I had an initialized variable as `false`. Yes that solution does work @WarEagle451, and thank you for your fast replies!
