### ISSUE TITLE
How can I render whole DirectX11 scene into an ImGui window?

### ISSUE THREAD

**Issue by jkooooo99** [ocornut/imgui#4336]
Version: 1.83
Branch: master

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: vs2109
Operating System: win10
----------------------------------------------------------------------------------------------------------------------------------------------
My Question:

Sorry to interrupt，I am a newbie to everythings....

I am following a tutorial of DirectX11,and I have set up imgui in my tiny program.

![imgui](https://user-images.githubusercontent.com/81244845/126103553-3ec55a1c-bec8-4c87-95b4-d003a5697750.JPG)

and I want to make the whole scene be rendered in ImGui window.

I found that a lot of people who use opengl have asked similiar questions.
https://github.com/ocornut/imgui/issues/984

https://gamedev.stackexchange.com/questions/140693/how-can-i-render-an-opengl-scene-into-an-imgui-window

but It seems like that there is a big difference between DirectX11 and opengl......

really hope someone can help me!!

sorry for my english

**Comment by rokups** [comment]
You can render your scene into a texture and then render a texture using `ImGui::Image()`. How exactly to do that is out of scope of dear imgui as this is general 3D rendering question.

**Comment by ocornut** [comment]
You'll need to lookup "render to texture" in DX11. Closing this as out of scope of dear imgui.

**Comment by jkooooo99** [comment]
Thank you so much!!!!!!!!!!!!!!!!!!!!
