### ISSUE TITLE
Disable mouse events for underlying application when ImGUI is shown

### ISSUE THREAD

**Issue by Symbai** [ocornut/imgui#4337]
**Version/Branch of Dear ImGui:**

Version: 1.76
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp
Compiler: VS19
Operating System: Win11

**My Issue/Question:**

How can I completely disable the mouse/cursor for the underlying application? Setting `io.WantCaptureMouse` has no effect, if I move the cursor around, the cursor in the underlying application also moves.

**Screenshots/Video**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/14368203/126129554-f9ae8bb7-86fc-49b5-b60c-33b264ee346a.gif)

**Standalone, minimal, complete and verifiable example:** 
```c++
// ...
ImGui::NewFrame();
ImGui::GetIO().MouseDrawCursor = true;
ImGui::GetIO().WantCaptureMouse = true;
ImGui::Begin("Hello World!");
ImGui::Text("abcdef");
ImGui::EndFrame();
// ...
```

**Comment by ocornut** [comment]
The underlying application is under your control so the question doesn’t make sense.
The general idea is that when io.WantCaptureMouse is set to true you want your application code to ignore mouse inputs.

**Comment by PathogenDavid** [comment]
> Setting io.WantCaptureMouse has no effect

To add to what Omar said, you don't set `WantCaptureMouse`, Dear ImGui does. You only read it.
