### ISSUE TITLE
Imgui based node editor

### ISSUE THREAD

**Issue by aabilityuk** [ocornut/imgui#4338]
Hi, sorry if the question is old and I choose not the right place to post it! I am looking for a best stable node editor imgui based library. My purpose is to make a dynamic text code generation based on blueprint styled nodes and pins., I recently try an imgui node-editor library but it really has no documentation and code samples is not enough for me (dummy level) to understand the basic:
1. How to enumerate pins inside the node and read the current state;
2. How to change the pins collor;
3. How to read data from the pin to local variable ;
4. How to read/write data to the pin programmatically...

I would really appreciate if someone could advice me a starting point for dynamic code generation approach and library based on dear imgui that I can use for my task.

Thank you!!!

**Comment by rokups** [comment]
You can find a list of node editors in the wiki: https://github.com/ocornut/imgui/wiki/Useful-Extensions#node-editors

**Comment by aabilityuk** [comment]
> You can find a list of node editors in the wiki: https://github.com/ocornut/imgui/wiki/Useful-Extensions#node-editors

Thank you very much for reply! If you familiar with node editors could you please advise which one to choose (already investigate the #306 branch)

**Comment by rokups** [comment]
You should evaluate them according to your needs and pick one most suitable to the task at hand. There is no best or worst option, they are just different kinds of same thing.

**Comment by aabilityuk** [comment]
> You should evaluate them

Thank you
