### ISSUE TITLE
Add underline image below Image button on click

### ISSUE THREAD

**Issue by iamthebest77** [ocornut/imgui#4353]
Hi,

I want to add an image below an image button to underline it on click event.
When I add the underline image, the elements below the image button shift further down.
How to ensure that the position of other elements is not impacted after adding the underline image.

I am developing this on Windows 10 and using v1.82 of Dear ImGUI.
P.S. : I am new to c++ and ImGUI.

Image buttons : 
<img width="29" alt="imagebuttons" src="https://user-images.githubusercontent.com/13537446/126741977-cec1ecaf-8f0c-4a93-9706-84cbe460ea47.PNG">

Clicking on first image button shifts the position of the remaining image buttons :

<img width="26" alt="imagebuttonclicked" src="https://user-images.githubusercontent.com/13537446/126742053-4d986b7c-26c6-41fb-97f3-b0bd525cf63e.PNG">

// Here's the code snippet
       
     ImGui::ImageButton((void*)(intptr_t)_iconImageTexture.textureID,
                       ImVec2(_iconImageTexture.width / 1.5, _iconImageTexture.height / 1.5), ImVec2(0, 0),
                       ImVec2(1, 1), 0, ImVec4(0.15f, 0.15f, 0.15f, 0.0f), ImVec4(1.0f, 1.0f, 1.0f, 1.0f));

    if (ImGui::IsItemActive() && ImGui::IsItemClicked()) {
        ImGui::SetCursorPos(x,y);

        ImGui::Image((void*)(intptr_t)m_selectedIndicator.textureID,
                     ImVec2(m_selectedIndicator.width / 2, m_selectedIndicator.height / 2));
       }

}
```

**Comment by PathogenDavid** [comment]
The easiest way would probably be to use `ImGui::Dummy` to make sure the layout is the same even when you aren't drawing the underline image. Something along these lines:

```cpp
ImGui::ImageButton((void*)(intptr_t)_iconImageTexture.textureID,
                  ImVec2(_iconImageTexture.width / 1.5, _iconImageTexture.height / 1.5), ImVec2(0, 0),
                  ImVec2(1, 1), 0, ImVec4(0.15f, 0.15f, 0.15f, 0.0f), ImVec4(1.0f, 1.0f, 1.0f, 1.0f));

ImGui::SetCursorPos(x,y);

if (ImGui::IsItemActive() && ImGui::IsItemClicked()) {
    ImGui::Image((void*)(intptr_t)m_selectedIndicator.textureID,
                ImVec2(m_selectedIndicator.width / 2, m_selectedIndicator.height / 2));
} else {
    ImGui::Dummy(ImVec2(m_selectedIndicator.width / 2, m_selectedIndicator.height / 2));
}
```

**Comment by ocornut** [comment]
You can also use `ImGui::GetWindowDrawList()->AddImage(...)` to add the second image without interfering with layout.

**Comment by iamthebest77** [comment]
Hi Omar,

Is there a way to blend the underline image with the image button. In simpler words, is there any possible solution to blend two images in imgui?
