### ISSUE TITLE
GUI form builder for imgui ?

### ISSUE THREAD

**Issue by graysuit** [ocornut/imgui#4359]
**Compiler: VC++
Operating System: Windows**

**Background:**
Well, I have been using GUI forms builders like winforms, 
that have list of controls, 
and and you drag n drag any widget,
and edit starightly their using properties.
It can also show list of events from which can just click, and it will prepare most GUI code.

And rest, skeleton we code our self.

**Screenshots:**

![image](https://user-images.githubusercontent.com/54432616/126875501-fa28c43c-5dba-40f2-9a89-12991536fb15.png)
![image](https://user-images.githubusercontent.com/54432616/126875511-6b9d4ada-1270-449c-8553-6ab8f0ba3875.png)
![image](https://user-images.githubusercontent.com/54432616/126875543-37f82d0f-a70a-40f0-98c8-da5abe20124c.png)

**Winforms Experience:** 
I'm using winforms for more than 3 years, and I have no complain except UI is slow for extended or complicated widgets.
And  wanna replace all my winform UI with imgui in assumption that form speed and loadup will be fast.

**Current workaround:**
I found this [ImguiBuilder](https://github.com/Code-Building/ImGuiBuilder), but it has low no. of widgets, and also 
I have some problem while saving the generated code.

**final words:**
Well, I know there are tons of widgets and their customization in IMGUI, so it won't be possible to fit all. 
But I wanna use IMGUI as general widgets library, like wxwidgets. I love imgui UI.

I tried my best to share everything which I know to help viewer to understand. Still if there anything missing, kindly do let me know. Thanks.

**Comment by ocornut** [comment]
Hello @graysuit,

There are no immediate plan to provide something of that sort in dear imgui land, but if we ever do experiment with this we'll make sure that people know about it.

For some of our expected work on internal layout functions allowing this to be possible is among one of the checklist item (basically internals' ItemAdd/ItemSize replacement will allow changing items position/size, allowing an external data source to be used)
