### ISSUE TITLE
Global UI Scale parameter

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#436]
Hi,

I have notice that under some specific situations (by example using a Retina screen ... resolution is 5120×2880) the fonts are so smalls that it is unreadable and even the normal buttons/widgets size are so small that it is hard to click them.

So, to solve the problem we can use some "scaling" factor to scale the user interface, ie. the fonts but also all the positions and sizes.

Is there some mechanims that can help scaling the UI correctly ?

**Comment by ocornut** [comment]
Not right now but it is equivalent to scale the fonts + all the sizing parameters in Style (there's only a few of them).

**Comment by krys-spectralpixel** [comment]
Ok thanks

**Comment by ocornut** [comment]
Btw there is a FontGlobalScale setting you can use BUT it doesn't affect the Padding fields. I will add that to my todo list.
