### ISSUE TITLE
Font file rendering issue.

### ISSUE THREAD

**Issue by Stanlyhalo** [ocornut/imgui#4361]
Version: 1.83
Branch: docking

**My Issue/Question:** I'm trying to use a font I found (.ttf font), but whenever I type a space, it uses the incorrect character when rendering.

**Screenshot**
This is the statement to make the text:
![image](https://user-images.githubusercontent.com/36088749/126883970-2c9470ae-0065-44da-906d-1675e7e35f6b.png)
This is what it renders:
![image](https://user-images.githubusercontent.com/36088749/126883974-0a164e7d-eeb4-4ad8-b7fb-b247c4d708a8.png)
This is what it looks like when you open the .ttf file:
![image](https://user-images.githubusercontent.com/36088749/126883978-470800a8-520a-46f0-b103-675ca771f6f9.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
font_a = io.Fonts->AddFontFromFileTTF("a.ttf", 30.0f);
// ***
ImGui::PushFont(font_a);
ImGui::TextColored(ImVec4{ 1.0f,1.0f,1.0f,1.0f }, "COSMIC ENGINE");
```

**Comment by PathogenDavid** [comment]
Is the font publicly available?

If you look at the font in the metrics window (call `ImGui::ShowMetricsWindow`), does the font have a space glyph in it? (Space is glyph 0x0020, it'll be the first glyph on the third row--to the left of `!` and above `0`. If it's a dark gray outline that means it's missing.)

![image](https://user-images.githubusercontent.com/278957/126889086-dd3fcce0-531b-4fec-b00d-5442317eed2c.png)

**Comment by Stanlyhalo** [comment]
Oh, it appears it does not, how do I go about adding a space glyph to the font?

**Comment by Stanlyhalo** [comment]
Figured it out, using Font Forge is difficult to make an empty character, but it's working, thanks so much :]
