### ISSUE TITLE
Dragging the imgui window outside of the main window

### ISSUE THREAD

**Issue by GitOlli** [ocornut/imgui#4364]
https://user-images.githubusercontent.com/87951652/126917892-fe87a212-ff08-4f59-beb9-b2db323abe7d.mp4

Hello! How can i make the imgui window go outside of my glfw window like in the video i took from the "imgui examples"?
I tried looking at the code but didn't see anything unusual so how was it achieved in the "imgui examples"?

**Comment by cfillion** [comment]
See this page on the wiki: https://github.com/ocornut/imgui/wiki/Multi-Viewports.

**Comment by GitOlli** [comment]
Thank you
