### ISSUE TITLE
Closing ImGui window causes crash.

### ISSUE THREAD

**Issue by Stanlyhalo** [ocornut/imgui#4367]
Version: 1.83
Branch: docking

**My Issue/Question:** Whenever I go to close a window, I get a write access violation, how do I fix this?

In the imgui.cpp implementation file, I keep getting this error around line 6045: "access write violation".

The error shows up when imgui.cpp tries to set *p_open to false.
```cpp
    // Close button
    if (has_close_button)
        if (CloseButton(window->GetID("#CLOSE"), close_button_pos))
            *p_open = false;
```

**Comment by ocornut** [comment]
What value for `p_open` did you pass to `Begin()` ? It would crash if you pass an invalid pointer.

**Comment by Stanlyhalo** [comment]
I did (bool*)true, what am I suppose to pass?

**Comment by Stanlyhalo** [comment]
is it because the isClosed variable is inside the loop and should be outside the main loop?

**Comment by ocornut** [comment]
> I did (bool*)true, what am I suppose to pass?

This is incorrect understanding of the language.

There are ample amount of example in the dear imgui demo (imgui_demo.cpp) please check them.
