### ISSUE TITLE
12 Errors in Visual Studio on Running

### ISSUE THREAD

**Issue by YusufSuleman** [ocornut/imgui#4372]
The screen shot of the error list:
![image](https://user-images.githubusercontent.com/63107868/127108250-d674e6a8-c444-449d-9a28-56da6f4cb3b2.png)
![image](https://user-images.githubusercontent.com/63107868/127108297-639e9fc3-53be-4f2f-bedb-f033c9922284.png)
I don't know what it is. The Microsoft Docs are not helpful here.

**Comment by ocornut** [comment]
You are not compiling the cpp files into your project (nothing the red mark on your source files).
Linking errors are almost always due to missing files.
