### ISSUE TITLE
Imgui io.KeysDown problem

### ISSUE THREAD

**Issue by aabilityuk** [ocornut/imgui#4383]
Hi, i am using imgui in my C++ MFC project, imgui window draws directly in MFC Picture Control and placed on MFC window, and i can't find a way of how to handle keyboard events... 

Mouse events is working perfect and i handle the mouse events like this:

```
void CAlphaNodeEditor::oglDrawScene(void){
	wglMakeCurrent(hdc, hrc);
	ImGuiIO& io = ImGui::GetIO();


	io.MouseDown[0] = lmbtn;
	io.MouseDown[1] = rmbtn;
	io.MousePos.x = (float)mx;
	io.MousePos.y = (float)my;
	io.MouseWheel += mwhl;

	io.KeysDown[ImGuiKey_Delete] = key_flag;
	key_flag = false;

	mwhl = 0.0f;
	imgl.NewFrame();
	pSettingsDlg->Application_Frame();
	imgl.EndFrame();
	SwapBuffers(hdc);
	wglMakeCurrent(NULL, NULL);
}

void CAlphaNodeEditor::OnLButtonDown(UINT nFlags, CPoint point){
	lmbtn = true;

	CWnd::OnLButtonDown(nFlags, point);
}


void CAlphaNodeEditor::OnLButtonUp(UINT nFlags, CPoint point){
	lmbtn = false;
	CWnd::OnLButtonUp(nFlags, point);
}


void CAlphaNodeEditor::OnMouseMove(UINT nFlags, CPoint point){
	mx = point.x;
	my = point.y;
	CWnd::OnMouseMove(nFlags, point);
}


void CAlphaNodeEditor::OnRButtonDown(UINT nFlags, CPoint point)
{
	rmbtn = true;
	CWnd::OnRButtonDown(nFlags, point);
}


void CAlphaNodeEditor::OnRButtonUp(UINT nFlags, CPoint point){
	rmbtn = false;
	CWnd::OnRButtonUp(nFlags, point);
}

BOOL CAlphaNodeEditor::OnMouseWheel(UINT nFlags, short zDelta, CPoint pt) {
	mwhl = (float)zDelta / (float)WHEEL_DELTA;
	return CWnd::OnMouseWheel(nFlags, zDelta, pt);
}
```
But io.KeysDown events doesnt work at all (not chars input, not numeric, not specials VK_DELETE, Backspace and so on)

I was trying to handle keysdown event like it is commonly used in MFC:

```
BOOL CSettingsDlg::PreTranslateMessage(MSG* pMsg)
{
	// TODO: добавьте специализированный код или вызов базового класса
	if (pMsg->message == WM_KEYDOWN && pMsg->wParam == VK_DELETE)
	{
		
		key_flag = true;

		return true;
	}

	return CMFCPropertyPage::PreTranslateMessage(pMsg);
}
```

But there is no luck, even code doesnt trigger inside the if (pMsg->message == WM_KEYDOWN && pMsg->wParam == VK_DELETE)

also i tried to investigate the ImGui demo window keyboard status, nothing there...

Could you please help me to find a solution?

Thank you

**Comment by ocornut** [comment]
> i can't find a way of how to handle keyboard events...

If you use MFC it is up to you to figure out how to receive key events from MFC. Your question here doesn't have anything to do with dear imgui. Beside you are not generally not providing enough information to help you.

I think you would make your life easier by writing directly to the `ImGuiO` fields from your MFC event handlers, rather than attempting to store them somewhere and then apply to ImGuiIO elsewhere.

Assuming your `CSettingsDlg::PreTranslateMessage()` function gets you all raw Win32 events, you could simply call `ImGui_ImplWin32_WndProcHandler()` from imgui_impl_win32 with the four fields from your MSG structure and the win32 backend would do everything for you.

**Comment by aabilityuk** [comment]
Dear, ocornut! I understand that this is not imgui problem and this is not your business, but may i ask you to give me a hand with my MFC keyboard problem! I am struggling the second week on it and there is no solution for me...

I can't make keydown event work(( Tell me please what direct additional information you need and i will provide you the whole one

Thank you

**Comment by aabilityuk** [comment]
> > i can't find a way of how to handle keyboard events...
> 
> If you use MFC it is up to you to figure out how to receive key events from MFC. Your question here doesn't have anything to do with dear imgui. Beside you are not generally not providing enough information to help you.
> 
> I think you would make your life easier by writing directly to the `ImGuiO` fields from your MFC event handlers, rather than attempting to store them somewhere and then apply to ImGuiIO elsewhere.
> 
> Assuming your `CSettingsDlg::PreTranslateMessage()` function gets you all raw Win32 events, you could simply call `ImGui_ImplWin32_WndProcHandler()` from imgui_impl_win32 with the four fields from your MSG structure and the win32 backend would do everything for you.

Dear, ocornut! I understand that this is not imgui problem and this is not your business, but may i ask you to give me a hand with my MFC keyboard problem! I am struggling the second week on it and there is no solution for me...

I can't make keydown event work(( Tell me please what direct additional information you need and i will provide you the whole one

Thank you

**Comment by Namy3242** [comment]
I guess as below.

```
BOOL CSettingsDlg::PreTranslateMessage(MSG* pMsg)
{
	// TODO: добавьте специализированный код или вызов базового класса
	if (ImGui_ImplWin32_WndProcHandler(pMsg->hwnd, pMsg->message, pMsg->wParam, pMsg->lParam))
		return true;
	return CMFCPropertyPage::PreTranslateMessage(pMsg);
}
```
