### ISSUE TITLE
Getting an assertion error when trying to use PushItemFlag

### ISSUE THREAD

**Issue by julienta** [ocornut/imgui#4387]
**Version/Branch of Dear ImGui:**

Version: latest as of 31/07/2021
Branch: docking

**Back-end/Renderer/Compiler/OS**

backends: imgui_impl_win32.cpp + imgui_impl_opengl3.cpp
Compiler: msvc
Windows

**My Issue/Question:**

When I use ``ImGui::PushItemFlag(ImGuiButtonFlags_AllowItemOverlap, true);`` after an Invisible button the error gets triggered as soon as move the mouse.
the error is from this assert:
IM_ASSERT(item_flags == g.ItemFlagsStack.back());

Here is some code that I'm using. Not sure if this will help. But basically I want to make sure I register hovering and clicking properly on overlapping items. 
This is for a custom node graph I'm trying to implement.

```
draw_list->ChannelsSetCurrent(id*2);
ImGui::SetCursorScreenPos(currentRect.Min);
ImGui::InvisibleButton("node", currentRect.GetSize());
ImGui::PushItemFlag(ImGuiButtonFlags_AllowItemOverlap, true);
ImGui::SetItemAllowOverlap();
```

It looks like the the ``ImGui::SetItemAllowOverlap();`` is sufficient for me to register the clicks properly. But as I'm still very new to this api. I thought I would still report it.

Thanks!

**Comment by rokups** [comment]
Could you produce a full code sample that can reproduce this issue? Something we could paste to any example application and reproduce this issue.

**Comment by ocornut** [comment]
“ImGui::PushItemFlag(ImGuiButtonFlags_AllowItemOverlap, true);”

ButtonFlags != ItemFlags this is a wildly invalid statement.

**Comment by julienta** [comment]
``ButtonFlags != ItemFlags this is a wildly invalid statement.``
Sorry I thought all widgets except Windows were "Items" as I couldn't find a PushButtonFlag function. I just didn't think about passing that flag as an argument to the button creation. The same way we are doing it for windows.

It looks like though I forgot to put the ``ImGui::PopItemFlag()`` after. Which now works. 
Interestingly enough this was working before without it. Maybe it managed to go through the cracks. 

``Could you produce a full code sample that can reproduce this issue? Something we could paste to any example application and reproduce this issue.``
It looks like this won't be necessary, as I just realized my mistakes. I'm just going to close this issue.

Thanks!
