### ISSUE TITLE
Align text in InputText to the right when not active

### ISSUE THREAD

**Issue by keszegh** [ocornut/imgui#4391]
After searching a lot i still do not see a way to align the text in an inputtext to the right. this would be useful e.g. in a file viewer when the text does not fit then the end of the text contains more useful information than the beginning, so that is the one which should be visible.
is this possible somehow? if not, then please consider adding it via a flag or some other way.

while trying to find workarounds i thought about modifying (truncating) the text when editing is finished and then putting back the 'long' text and positioning at the right place the cursor in the long text when editing is started. for these i'd need some callbacks when editing is started/finished but i could not find such. isItemActivated and isItemDeactivatedAfterEdit are triggered at the right time but from these i don't know how to reach the text buffer of the inputtext (and positioning the cursor), is this possible? if not, i think some way to change the text buffer when editing is started/finished (e.g. using a callback) would be a useful addition in general, not just for my usecase.

**Comment by ocornut** [comment]
Same as #1442 #1440 which is still open, so I'd suggest moving the discussion there.

**Comment by ocornut** [comment]
Reopening as in fact this is different from #1442: if the aim is to e.g. see the significant portion of a filename then it doesn't necessarily mean we want to right-align the text at all time (although that if available would be a good workaround, but look odd when the filename is short).

(Also see WIP stuff such as https://github.com/ocornut/imgui/pull/5791#issuecomment-1380584289)

**Comment by ocornut** [comment]
This is now supported with `ImGuiInputTextFlags_ElideLeft` flag.
See https://github.com/ocornut/imgui/pull/1442#issuecomment-2528054644
