### ISSUE TITLE
I can't change the docked windows tab background.

### ISSUE THREAD

**Issue by Stanlyhalo** [ocornut/imgui#4393]
Version: 1.83
Branch: docking

**My Issue/Question:** I can't change the docked windows tab background.

So when I dock two windows together and they're not in the dockspace, whenever I have them active/selected, the background for the tab panel goes blue, and I can't seem to change that.

**Screenshots**
![image](https://user-images.githubusercontent.com/36088749/128084593-ab50890e-50ea-4e8c-bebe-04aa50da05bf.png)

**Comment by ocornut** [comment]
This is too ambiguous, please clarify.

**Comment by Stanlyhalo** [comment]
So when I take two windows and dock them together (not dock them into the dockspace), the tab background (the area where the tabs are) becomes blue, and I can't find a way to change the color even in the demo window.

**Comment by AidanSun05** [comment]
You're probably looking for the `TitleBg` or `TitleBgActive` style variable (which are both `ImVec4`s). The former sets the tab bar color for every window while the latter only affects the currently focused window.

In the image below I've set `TitleBgActive` to bright red, and you can see the focused dock node change its tab bar color accordingly.

![image](https://user-images.githubusercontent.com/61399657/128111942-4f5f71fb-7d55-43ea-b0ea-55472c1e965b.png)

**Comment by Stanlyhalo** [comment]
I have the TitleBgActive set to a specific color in my code, which shows up in the following picture, but it still occurs:
![image](https://user-images.githubusercontent.com/36088749/128223723-59c984cb-ac38-4ec5-ad29-be00115f98ef.png)

**Comment by AidanSun05** [comment]
Are you using `ImGui::PushStyleVar()` or directly setting the `TitleBgActive` member of the `ImGui::GetStyle()` struct? You should use the latter for this scenario.

**Comment by Stanlyhalo** [comment]
I'm doing `ImGui::PushStyleColor()`.

**Comment by AidanSun05** [comment]
So that's possibly why your window colors are always resetting. Modifying `TitleBgActive` before your main loop will permanently set the color until you change it again (which you probably won't). This is the desired behavior.

```cpp
// [BEFORE MAIN LOOP]
ImGuiStyle& style = ImGui::GetStyle();
style.Colors[ImGuiCol_TitleBgActive] = { 1.0, 0.0, 0.0, 0.0 }; // Set this to whatever ImVec4 you want
```

**Comment by Stanlyhalo** [comment]
Ooooh okay, thx so much, I guess I should also style some of my stuff like that huh? Seems like 20% of the colors only work through actually setting the ImGuiStyle/
