### ISSUE TITLE
Crash in RenderGlyphAndGetInfo of Imgui_freetype with freetype 2.11

### ISSUE THREAD

**Issue by metarutaiga** [ocornut/imgui#4394]
**Version/Branch of Dear ImGui:**

Version: 1.84
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom
Compiler: Visual Studio 2019
Operating System: Windows 10

**My Issue/Question:**

https://github.com/ocornut/imgui/blob/f99fe72c42bd5d578c2443409192b139b1c6623d/misc/freetype/imgui_freetype.cpp#L541-L542

Crash here because **FT_Render_Glyph** reported **Unimplemented_Feature** error in some fonts since freetype 2.11

https://github.com/ocornut/imgui/blob/f99fe72c42bd5d578c2443409192b139b1c6623d/misc/freetype/imgui_freetype.cpp#L254

It maybe a bug in freetype 2.11.

I found the two fonts that it can show this bug.
- msgothic.ttc
- mingliu.ttc

Edit : Someone also has the same problem.
https://gitlab.freedesktop.org/freetype/freetype/-/issues/1076

**Comment by ocornut** [comment]
Pushed a fix on imgui_freetype side for it, thank you.
As per #4145 I'd be curious to find which glyph it is failing on?
