### ISSUE TITLE
If multiple InputText's are created via loop, whenever I select one when running my app, it deselects it.

### ISSUE THREAD

**Issue by Stanlyhalo** [ocornut/imgui#4395]
Version: 1.83
Branch: docking

**My Issue/Question:** If multiple InputText's are created via loop, whenever I select one when running my app, it deselects it.

I've been creating a game engine in Vulkan, and the UI with imgui, but as I started to make my entity inspector, it seems when I create input text via looping, whenever I select an input, it deselects it, and if I select the input that was the last one created, it selects all of them and i can edit the text in all of the inputs.

Here's the code of what I have:
```cpp
for (int i = 0; i < storage.sel_gameEntities.size(); i++) {
	std::string s = std::to_string(storage.sel_gameEntities[i][0]->getId());
	if (ImGui::CollapsingHeader(std::string(std::string(storage.sel_gameEntities[i][0]->name) + "###" + s).c_str(), ImGuiTreeNodeFlags_None))
	{
		ImGui::InputText("Name", storage.sel_gameEntities[i][0]->buf_name, 64);
		storage.sel_gameEntities[i][0]->name = storage.sel_gameEntities[i][0]->buf_name;
	}
}
```

**Comment by Stanlyhalo** [comment]
I seem to have fixed it lol, for those of you wondering, I did this to set I guess the "id" of the input:
![image](https://user-images.githubusercontent.com/36088749/128224511-c4bad6dc-184d-4d72-a74b-28699db3d19b.png)

**Comment by ocornut** [comment]
Read the FAQ!!
