### ISSUE TITLE
Qs: Creating a grid-table

### ISSUE THREAD

**Issue by kfsone** [ocornut/imgui#4396]
I'm struggling to find a straightforward way to create a Table with every cell having the same height and width. Is this a misuse of Table? I'd gone to table for the dynamic sizing but what I really want is SizingStretchSameXY (or better still SizingStretchSameXYSquare :) 

See https://github.com/kfsone/imgui_grid esp https://github.com/kfsone/imgui_grid/blob/main/main.cpp (this uses [ImGuiWrap](https://github.com/kfsone/imguiwrap) but should still be legible)

![image](https://user-images.githubusercontent.com/323009/128252000-e6ef8cea-fca8-4daf-92e6-49b642a7ba25.png)

**Comment by ocornut** [comment]
We can’t automatically provide even row heights because rows are submitted without knowing of upcoming rows.

However you can probably provide the minimum height of a row in TableNextRow() to reproduce a square grid behavior.

**Comment by kfsone** [comment]
I think this is why Grid and Table layout are usually distinct options. Table can probably be coaxed to do what I want but I think just (colN * width, rowN * height) placement is probably the right way to go.
