### ISSUE TITLE
General question about performance and some aspect of widget drawing

### ISSUE THREAD

**Issue by r2com** [ocornut/imgui#4397]
Not having an issue, just familiarizing myself with library.

so from what I discovered, for example, in order to draw button (or any other widget) in different location within window, one first moves cursor using SetCursorPos(), and then instantiates Button at that position.

The SetCursorPos() in its turn is calling GetCurrentWindow() to get cursor position and add new one.

Correct me if I'm wrong, but does it mean that there will be at least 2 extra function calling (SetCursorPos() and GetCurrentWindow()) involved every time for a window which is literally ran by "progra" i.e. constantly being rendered every frame?

My concern is, what if there are many widgets, and the underlying hardware is not as powerful, isn't it too many function calls then every frame? Are there alternative ways of achieving this (positioning widgets at specific locations) without having to call extra functions?

Or if my understanding is wrong can you please elaborate, as I said, I just barely got it running, compiled, ran and trying to understand its internals first.

**Comment by rokups** [comment]
You are correct, every frame reassembles UI by calling functions of every widget. However calls themselves are so cheap that there is no point in worrying about it before you actually have a performance issue. Dear ImGui is built with performance in mind, so wherever it is possible to save performance it is done so. For example consider a scroll area with a tall list of buttons. While we do calls to `ImGui::Button()` for buttons that are scrolled out of view - only layoutting is performed, rest of logic is skipped (there is no point in trying to render text that we can not see). In the end you should define what is "not so powerful hardware", then make a test case and measure performance. People run Dear ImGui everywhere: phones, arduino boards (!), PCs, consoles, even stream drawlists to be rendered on a remoted machine. So while in theory immediate mode UI aproach does sound suboptimal, in reality it is hardly ever a problem.
