### ISSUE TITLE
16 more errors in Visual Studio

### ISSUE THREAD

**Issue by YusufSuleman** [ocornut/imgui#4398]
After following the solution on Issue #4372 and fixing some errors on my own. I now have new errors that I can't solve on my own.

Screenshots:
![image](https://user-images.githubusercontent.com/63107868/128320483-572d6cd8-02bc-4a0b-93ae-d3b2b8974c5b.png)
![image](https://user-images.githubusercontent.com/63107868/128320595-d022c1b5-762a-4026-8bd1-dbf587a73466.png)
![image](https://user-images.githubusercontent.com/63107868/128321017-07af44e3-68db-41b1-aa97-2157fdb93d8d.png)
I can't understand these errors.

**Comment by rokups** [comment]
If you are using freetype font rasterizer you should link freetype library. Also it is important that freetype is compiled using same settings as your project (should you be using prebuilt binaries).

**Comment by YusufSuleman** [comment]
@rokups I can't find a .lib file in the FreeType zip. So I can't link it. I still have included the include files.

**Comment by PathogenDavid** [comment]
@YusufSuleman You probably downloaded the source release. As far as I'm aware, the FreeType maintainers do not distribute pre-built binaries.

You either need to build it yourself or use [third-party pre-built binaries](https://github.com/ubawurinna/freetype-windows-binaries). (That repo is linked from [the FreeType download page](https://www.freetype.org/download.html), but I cannot personally vouch for it.)
