### ISSUE TITLE
Setting the thickness of `ImGui::Separator()`?

### ISSUE THREAD

**Issue by FahimFuad** [ocornut/imgui#4399]
Hello! Firstly thanks for this awesome UI library @ocornut !

Ima get straight into the topic, Is there is any way by which I can set the **thickness** of the `ImGui::Separator()`?

Thanks in advance! 🙂

**Comment by PathogenDavid** [comment]
You cannot, internally the thickness of the line is not specified:

https://github.com/ocornut/imgui/blob/f99fe72c42bd5d578c2443409192b139b1c6623d/imgui_widgets.cpp#L1397

which means it is defaulted to 1:

https://github.com/ocornut/imgui/blob/f99fe72c42bd5d578c2443409192b139b1c6623d/imgui.h#L2405

**Comment by ocornut** [comment]
It's not possible with the `Separator()` api. One reason Separator() is locked to 1.0f is that it doesn't submit its height to layout (which is inconsistent, but would break a fair amount of code to fix).

Note that implementing a separator is pretty simple.
You can call any of the ImDrawList function yourself and then `Dummy()` for layout.

**Comment by FahimFuad** [comment]
I see, thanks for the info, some demo code would be awesome!
