### ISSUE TITLE
Possible to hide certain windows from the ctrl+tab window switch feature?

### ISSUE THREAD

**Issue by Stanlyhalo** [ocornut/imgui#4401]
Version: 1.83
Branch: docking

**Question:** Possible to hide certain windows from the ctrl+tab window switch feature?

So I created a custom window titlebar with the window controls (close, maximize, and minimize), but when I press ctrl+tab, I can see these "windows" in the list, but I styled them so they arn't a window, but now I'm wondering, how can I remove them from the list?

**Screenshot**
![image](https://user-images.githubusercontent.com/36088749/128442108-c4abc458-c741-4061-8d37-c1ac50c41588.png)

**Comment by Stanlyhalo** [comment]
For further clarity, I want to remove the windows that start with the name "window-frame" from the list, is this possible, or do I have to go in and change things to make this work to how I want it to.

**Comment by ocornut** [comment]
There is a window flag to do exactly that. Have you checked the window flags?

**Comment by ocornut** [comment]
FYI the flag is 
```
ImGuiWindowFlags_NoNavFocus // No focusing toward this window with gamepad/keyboard navigation (e.g. skipped by CTRL+TAB)
```
