### ISSUE TITLE
Debug window randomly showing.

### ISSUE THREAD

**Issue by AnnoyingB** [ocornut/imgui#4404]
Whenever I run my code, I get a random window called "Debug". I have never written anything to create that "Debug" window but it pops up. I have seen another post like this, but It didn't help that much because I don't know what ImGui calls are used only in ImGui::Begin and ImGui::End. I have some ImGui calls but I am pretty sure they have nothing to do with it.

``` cpp
ImGui_ImplOpenGL3_NewFrame();
	ImGui_ImplGlfw_NewFrame();
	ImGui::NewFrame();

	// Dockspace
	ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());

	/*Rendering*/
	

	//ImGui Rendering
	{
		//Menubar
		Core::RenderMenuBar(window);

		//Viewport
		Viewport::RenderViewport(Core::texture);

		//Console
		Console::RenderConsole();
	}

	ImGui::Render();
	int w, h;
	glfwGetFramebufferSize(window, &w, &h);
	glViewport(0, 0, w, h);
	glClearColor(0.45f, 0.55f, 0.60f, 1.00f);
	glClear(GL_COLOR_BUFFER_BIT);
	ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

	if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
	{
		GLFWwindow* backup_current_context = glfwGetCurrentContext();
		ImGui::UpdatePlatformWindows();
		ImGui::RenderPlatformWindowsDefault();
		glfwMakeContextCurrent(backup_current_context);
	}

	/*End of rendering*/

	glfwPollEvents();
	glfwSwapBuffers(window);
```

**Comment by rokups** [comment]
"Debug" is implicitly created window that is hidden by default. It appears whenever you render UI elements outside of any other window, so make sure you do not try to render any widgets that are outside of `Begin()/End()`.

**Comment by AnnoyingB** [comment]
I think I found it, it was simply I forgot to put my ImGui::Image in my begin and end. Thanks.
