### ISSUE TITLE
text line horizontal align

### ISSUE THREAD

**Issue by iperov** [ocornut/imgui#442]
I want centered message on window
how ?

**Comment by ocornut** [comment]
You have to do it manually at the moment (using CalcTextSize + SetCursorPosX + Text).
There are internal api doing it but they aren't finalised.

**Comment by ocornut** [comment]
Closing this. I hope to add better alignment primitives in the future.

**Comment by littlewater** [comment]
thanks for the method !

**Comment by codecat** [comment]
Is this not in the API yet?

**Comment by ocornut** [comment]
No it isn't yet.

**Comment by Monika0000** [comment]
void TextCenter(std::string text) {
    float font_size = ImGui::GetFontSize() * text.size() / 2;
    ImGui::SameLine(
        ImGui::GetWindowSize().x / 2 -
        font_size + (font_size / 2)
    );

    ImGui::Text(text.c_str());
}
