### ISSUE TITLE
Issue with using buttons in SDL

### ISSUE THREAD

**Issue by Lester702** [ocornut/imgui#4423]
version: 1.82
branch: master
imgui_impl_sdl

I'm trying to setup a very basic menu for my game right now with just a start button and a quit button and when I get

```
void Engine::menu()
{
    ImGuiIO& io = ImGui::GetIO();


        
    SDL_SetRenderDrawColor(gRenderer, 0, 0, 0, 255);
    pollEventsMenu();
    tick();
    SDL_RenderClear(gRenderer);

    ImGui::NewFrame();
    ImGui::Begin("Menu", NULL, ImGuiWindowFlags_None);

    if (ImGui::Button("Start"))
    {
        std::cout << "Start";
    }
    ImGui::SameLine();

    if (ImGui::Button("Stop"))
    {
        std::cout << "Stop";
    }
    ImGui::SameLine();


    ImGui::End();
    ImGui::Render();
    ImGuiSDL::Render(ImGui::GetDrawData());

    SDL_RenderPresent(gRenderer);

}
```

**Comment by mathisloge** [comment]
You really need to be more explicit with what don't work and - as the template shows - add a minimal reproducible code, that can be dropped into a standard demo and shows what don't work. The button code ` if(ImGui::Button("...") ... ` is fine.

**Comment by ocornut** [comment]
Closing as lacking sufficient information.
