### ISSUE TITLE
Last stable commit of docking branch ?

### ISSUE THREAD

**Issue by TNtube** [ocornut/imgui#4424]
version: v1.83 ?
branch: docking

Hello 👋 

I want to use the docking branch for a personal project, however I would like to make sure that I can use a stable version of this branch. 
Can you please tell me the last stable commit of the docking branch? Also, could you tell me what is its equivalent in terms of version with the master branch? (currently the last one of master is v1.83, is it equivalent or not?)

Thanks you !

**Comment by AidanSun05** [comment]
For the most part, docking is pretty stable and you're generally fine with using the latest commit there (go to https://github.com/ocornut/imgui/tree/docking to see it). As of August 11, 2021 it is 80b5fb5

As for versioning, the two branches are of the same version. The master branch is regularly merged into the docking branch to get all mainstream features/patches into docking.

**Comment by TNtube** [comment]
Thank you very much ! That's all I wanted to know
