### ISSUE TITLE
How to handle custom window resizing?

### ISSUE THREAD

**Issue by shi-yan** [ocornut/imgui#4425]
**My Issue/Question:**

I want to create a custom window, within the window, I'd like to render a 3D scene.

I'm doing it using the suggested method: render everything on a FBO and then render the FBO texture to a window. My question is how I should handle window resizing properly?

```cpp
void Window::drawUI() {
    ImGui::Begin(m_title.c_str());
    //ImGui::GetWindowDrawList()->AddImage((void *)texColorBuffer, ImVec2(ImGui::GetCursorScreenPos()), ImVec2(ImGui::GetCursorScreenPos().x + 800 , ImGui::GetCursorScreenPos().y + 600 ), ImVec2(0, 1), ImVec2(1, 0));
    ImVec2 avail_size = ImGui::GetContentRegionAvail();
    if ( ImGui::IsMouseReleased( ImGuiMouseButton_Left) ){
        std::cout << avail_size.x << " " << avail_size.y << std::endl;
        // should I resize my FBO here
    }
    //draw FBO
    ImGui::Image((void *)m_frameBufferTextureID, avail_size, ImVec2(0, 1),ImVec2(1, 0));
    ImGui::End();
}
```

Here I'm using  ImGui::GetContentRegionAvail(); to get the size of the window's content area. But as I drag the window's frame, the avail_size will change constantly. I think it's necessary and slow to resize the FBO buffer as soon as the window size has changed. I would like to do it only when the current user has stopped dragging the window's frame. 

I have tried using IsMouseReleased to detect mouse release event. But it is not limited to the current window. it's global. 

And I don't find any other window_has_resized event?

What would be the right way to do it?

Thanks

**Comment by shi-yan** [comment]
here is my current code, which works, but I don't like the way it works.

```cpp
    bool open = false;
    ImGui::SetNextWindowSize(ImVec2(m_initialWidth, m_initialHeight), ImGuiCond_Once);
    ImGui::Begin(m_title.c_str() );
    //ImGui::GetWindowDrawList()->AddImage((void *)texColorBuffer, ImVec2(ImGui::GetCursorScreenPos()), ImVec2(ImGui::GetCursorScreenPos().x + 800 , ImGui::GetCursorScreenPos().y + 600 ), ImVec2(0, 1), ImVec2(1, 0));
    ImVec2 availableSize = ImGui::GetContentRegionAvail();

    if ( ImGui::IsMouseReleased( ImGuiMouseButton_Left) || m_width == 0 ){
        // std::cout << availableSize.x << " " << availableSize.y << std::endl;
        // should I resize my FBO here
        if (availableSize.x != m_width || availableSize.y != m_height)
        {
            m_width = availableSize.x;
            m_height = availableSize.y;
            m_isFrameBufferDirty = true;
        }
    }
    //draw FBO
    ImGui::Image((void *)m_frameBufferTextureID, availableSize, ImVec2(0, 1),ImVec2(1, 0));
    ImGui::End();
```

I think there should be a  `ImGui::hasWindowSizeChanged()`

```cpp
if (ImGui::hasWindowSizeChanged()) {

}
```

**Comment by 1025798851** [comment]
so?
```CPP
static ImVec2 availableSize;
ImVec2 CurSize = ImGui::GetCurrentWindow()->Size;
if (availableSize .x != CurSize.x || availableSize .y != CurSize.y)
  availableSize = ImGui::GetContentRegionAvail();
```

**Comment by ocornut** [comment]
Your current code is fine but i would remove the mouse button test. 
Instead use eg GetActiveID()==0 or IsAnyItemActive()==false to account for the possibility of resizing via gamepad or keyboard.

Your proposed/hypothetical function would be ambiguous, not provide the info most people want (change on every frame) and might be problematic with multiple consumers. It’s saner we provide you the current data and you can massage/compare it however you want.

I however think it would nicer for the end user if you simply resized your framebuffer every frame and you may be making things more complex for a lower quality result.

**Comment by PathogenDavid** [comment]
I agree with Omar. If you're worried about reallocating the frame buffer too frequently, you could over-size the frame buffer and only actually use a subset of it. (Modern desktop GPUs have pretty coarse alignment requirements so this is generally already happening under the hood even when you aren't doing it yourself.)

**Comment by shi-yan** [comment]
@PathogenDavid , Thank you, I think that should work for my use case.
