### ISSUE TITLE
Using ImDrawList in thread doesn't work

### ISSUE THREAD

**Issue by thewolfram** [ocornut/imgui#4426]
Hello! I have a main thread with while true loop doing imgui stuff. And I have second while true loop which is in thread and runs by thread detach. When I'm trying to draw in thread loop using ImguiDrawList it doesn't work. Also I noticed that if you try to draw before doing new frame the program will crash. I tried to do new frame inside of thread loop but that doesn't work/crash program.

**Comment by AidanSun05** [comment]
Dear ImGui's rendering isn't thread safe. Attempting to render things in separate threads at the same time can lead to UB or crashes (this applies to any non-thread-safe C++ operation). You should most likely add mutexes or some other locking mechanism to ensure that only one thread changes the rendering at a time.

**Comment by ocornut** [comment]
I admit I haven’t investigated but it may be possible that using ImDrawList api only on separate ImDrawList instances (no ImGui call) might actually be thread safe.
Until this is investigated and proven so I’d consider it not thread safe. It’s also unlikely we’ll ever provide this guarantee on a shared ImFontAtlas+ImDrawListSharedData set (both needed to support ImDrawList).
