### ISSUE TITLE
Dynamically adding input fields in a window

### ISSUE THREAD

**Issue by s0umyajeet** [ocornut/imgui#4432]
```
Dear ImGui 1.84 WIP (18313)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1928
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl2
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 720.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

Is there a functionality to dynamically add text fields(or any other widget) in my window? To put it simply, I have a bunch of text input fields on same line. (screenshot attached) I want a button, say "Add more" which when pressed adds one more row of text input fields. This is similar to adding an extra "row" to a table, but I couldn't find any functionality to do that using tables as well.

**Screenshots/Video**
Desired functionality: Pressing the button should give me one more row of text input fields similar to the one above it. Kindly guide me if this is possible using a table as well.
![add_row](https://user-images.githubusercontent.com/57451703/129346979-41449e19-f783-48e2-ab67-9c3e6b42f5ca.png)

**Comment by ocornut** [comment]
Think about how you did submit the first row.
All of this is under the control of your code.

**Comment by s0umyajeet** [comment]
Yes, it's actually a silly question sorry. I used static variables with loops to achieve the functionality. Thank you for your insight sir! 😊
