### ISSUE TITLE
scrollbar climbs on popup

### ISSUE THREAD

**Issue by monyfolity** [ocornut/imgui#4435]
i have rendered scrollbar with g.CurrentWindow->DrawList
![image](https://user-images.githubusercontent.com/77878680/129449172-1597f88d-1f02-47b4-bc7e-623b8577480d.png)

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
