### ISSUE TITLE
How is this done?

### ISSUE THREAD

**Issue by LucusStarlord** [ocornut/imgui#4437]
![image](https://user-images.githubusercontent.com/18100666/129468644-8474bde0-d845-4e89-95ac-9114992db67f.png)

I've been using Imgui for awhile but some things still avert me. Can I have some advice on how this is done? (The toolbar within the viewport). Thank you kindly!

**Comment by mathisloge** [comment]
Probably something with SetCursorPos and Buttons & SameLine

**Comment by ocornut** [comment]
Hello @LucusStarlord,
It is a little ambiguous exactly which aspect you are asking about.

- The icons are simple buttons likely using an Icon font (see [FONTS.md](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md))

- The toolbar could be an independent window (using `ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoDecoration`) automatically resized to fit its contents, or a child window.
- Or the icons simply emitted after the 3d viewport contents (which might be a single `Image()` call), by repositioning the cursor as suggested by @mathisloge answer.
