### ISSUE TITLE
progress bar ?

### ISSUE THREAD

**Issue by iperov** [ocornut/imgui#444]
how to ?
need just horizontal filling bar with text

**Comment by krys-spectralpixel** [comment]
You can simply use :

GetCurrentWindow()->DrawList->AddRect(...); // Border
GetCurrentWindow()->DrawList->AddRectFilled(...); // Fill

**Comment by ocornut** [comment]
```
void ImGui::ProgressBar(float fraction, const ImVec2& size_arg = ImVec2(-1,0), const char* overlay = NULL);
```

**Comment by ocornut** [comment]
It is a new API you would have to update to the latest master.

**Comment by iperov** [comment]
cool thx
