### ISSUE TITLE
imgui_impl_sdl.cpp:63 error: macro expansion producing 'defined' has undefined behavior 

### ISSUE THREAD

**Issue by pfirsich** [ocornut/imgui#4442]
**Version/Branch of Dear ImGui:**

Version: 2ad912bb85
Branch: master

Back-ends: imgui_impl_sdl.cpp
Compiler: Clang 11.0.1
Operating System: Ubuntu 20.04

**My Issue/Question:**

When compiling ImGui (no code of mine in there) I get the error:
```
[build] ../deps/imgui/backends/imgui_impl_sdl.cpp:174:5: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
[build] #if SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE
[build]     ^
[build] ../deps/imgui/backends/imgui_impl_sdl.cpp:63:77: note: expanded from macro 'SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE'
[build] #define SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE    (SDL_VERSION_ATLEAST(2,0,4) && !defined(__EMSCRIPTEN__) && !defined(__ANDROID__) && !(defined(__APPLE__) && TARGET_OS_IOS))
[build]                                                                             ^
```
And more like it for the other occurences of `defined`.
I would have PR-ed a fix, but I am very confused by this not having been reported by anyone so far.

I think that line should instead be:
```cpp
#if SDL_VERSION_ATLEAST(2,0,4) && !defined(__EMSCRIPTEN__) && !defined(__ANDROID__) && !(defined(__APPLE__) && TARGET_OS_IOS)
#define SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE 1
#endif
```

**Comment by ocornut** [comment]
This was reworded and moved into the define 2 weeks ago which is why the warning hadn’t been reported yet. Will fix tomorrow.

**Comment by ocornut** [comment]
Fixed this warning, also went through all CI logs and fixed some more zealous/recent warnings (Emscripten, Clang on Mac in particular).
