### ISSUE TITLE
User-friendly animation for toggling ImGui

### ISSUE THREAD

**Issue by s5bug** [ocornut/imgui#4446]
```
Dear ImGui 1.83 (18300)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1929
define: _MSVC_LANG=202002
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1600.00,900.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

There are times when I don't want ImGui to show _at all_ over my application, but I also don't want to give the impression that the ImGui overlay crashed, stopped working, or the windows were deleted. Is there some way I can easily toggle the ImGui rendering state so that users understand that their windows are being hidden and not deleted?

Ways to accomplish this might be something like a fade in opacity or an animation that makes windows fly away towards the boundaries of the screen. Is there anything like this easily achievable in ImGui?

**Comment by ocornut** [comment]
You can animate the style.Alpha value toward 0.0 and then back to 1.0 during transitions.

**Comment by s5bug** [comment]
Awesome, thank you!
