### ISSUE TITLE
How to use ImFont::RenderText for my engine that almost using only ImDrawList, ImFont and Vulkan?

### ISSUE THREAD

**Issue by mandaxyz** [ocornut/imgui#4450]
**Version/Branch of Dear ImGui:**
Version: v1.65 - I'm very sorry, I was told to update because its version is 3 years ago, I'm planning to make my engine to be perfect first and after a few years, I will update to the very latest ImGui. Reason: It's very difficult to update, the Vulkan Examples Base stucks on that old ImGui, but that base is giant.

**Back-end/Renderer/Compiler/OS**
Operating System: Vulkan 1.2.182.0 / Visual Studio 2015 / Windows 10

**My Issue/Question:**
I want to use the function ImFont::RenderText to render text on my custom button using Vulkan, I tried to use ImDrawList::AddText but if I understand, it's designed for ImGui interface only because it requires ImGui::PushFont and ImGui::PopFont, and it failed to render. But my problem is I cannot use ImFont::RenderText for some reasons, the FontSize is 0 (but I force change it) and the Glyphs are not loaded, and I don't know how load it?
![FindGlyph](https://user-images.githubusercontent.com/88787285/130224202-2c795df5-a6ef-4293-b0fb-90b654cd876c.jpg)

**Standalone, minimal, [in]complete and verifiable example:**
```
// Here's a code where only the bottom part can be copied and modified to test.

void prepareX()
{
    ImGuiIO& io = ImGui::GetIO();
    ImFont *font_default = io.Fonts->AddFontFromFileTTF("....../data/arial.ttf", 20);
    ...
}

void button_draw_callback(emc::DrawList *drawList, UIObject *object, emc::Rect &rect)
{
    // obj->_font is a pointer to that common font_default.

    Button *obj = (Button *)object;
    obj->_font->FontSize = 11; // I force change the FontSize because it's always zero, why?
    obj->_font->RenderText(drawList->_drawList, 100, ImVec2(10, 10), 0xFF0000FF, ImVec4(0, 0, 1000, 1000), "Hello", 0);
}

```

**Comment by PathogenDavid** [comment]
At a glance it sounds like you aren't building the font atlas after loading the font. Make sure to review [the fonts and text FAQ](https://github.com/ocornut/imgui/blob/cb00972b878a0a4722c9214e6f7d46d97f092c3f/docs/FAQ.md#qa-fonts-text) and [the dedicated fonts guide](https://github.com/ocornut/imgui/blob/cb00972b878a0a4722c9214e6f7d46d97f092c3f/docs/FONTS.md).

**Comment by mandaxyz** [comment]
Thanks for the reply, I visit the second link you gave to me and I realized from it that I must call io.Fonts->Build(); to fix the issue I was talking about.

```
io.Fonts->AddFontDefault(); // Load first font
font_arial = io.Fonts->AddFontFromFileTTF("....../data/arial.ttf", 11);
io.Fonts->Build(); // This line is required to fix the problem I talked in the previous comment in the forum.
```
Therefore, the issue is 50% solved but there remain another issue, the whole text of ImGui is destroyed and I don't know how to fix it, also the text I'm trying to render I was talking about in my custom button cannot be rendered, maybe because I'm using a very old ImGui, that's because I cannot even render a filled rectangle with it, only NOT filled rectangles just like in the image below, but I can render a filled triangle, so there's a bug.

Finally, I must update to the latest ImGui right now, because it encourages developers on the forum to help me, also it very probably fix the bug on filled rectangle rendering.
![Bug](https://user-images.githubusercontent.com/88787285/130249448-6759c13e-ba40-4d58-9fd3-97812128b992.jpg)

**Comment by mandaxyz** [comment]
Thanks, there are a lot of works waiting for me:
- Update to the latest ImGui (this is probably the most difficult).
- Use texture in my engine, because I didn't implement a texture image yet, before, I thought that texts are filled polylines.
- Try to RenderText on my custom button.
Bye.

**Comment by ocornut** [comment]
I still you are overestimating the difficulty of updating..
