### ISSUE TITLE
EndDisabled() after BeginDisabled(false) sets global alpha to 0

### ISSUE THREAD

**Issue by pezcode** [ocornut/imgui#4452]
**Version/Branch of Dear ImGui:**

Version: 1.84
Branch: master

**Back-end/Renderer/Compiler/OS**

*doesn't apply*

**My Issue/Question:**

`BeginDisabled(false)` , directly followed by `EndDisabled` incorrectly restores global style alpha to 0.0. `g.DisabledAlphaBackup` is not set inside `BeginDisabled`, but it's then read from in `EndDisabled`.

**Standalone, minimal, complete and verifiable example:**

```
// This code sets alpha to 0 and never restores it.
// After the first frame, UI is completely invisible
ImGui::BeginDisabled(false);
ImGui::EndDisabled();
```

**Comment by ocornut** [comment]
Damnit, i made a last minute change and messed it up?

**Comment by ocornut** [comment]
Pushed a hotfix

**Comment by pezcode** [comment]
Thanks for the quick reply! That perfectly fixed the alpha issue.

I'm noticing another issue now, where `BeginDisabled(false)` unconditionally sets `ImGuiItemFlags_Disabled`, despite the code comment indicating it's the equivalent of `PushItemFlag(ImGuiItemFlags_Disabled, was_disabled || disabled)`. Note how `disabled` is only ever read when deciding whether to change alpha.

```c++
if(was_disabled || disabled) // adding this if seems to fix it
    g.CurrentItemFlags |= ImGuiItemFlags_Disabled;
```

**Comment by ocornut** [comment]
Fixed with d84e409715b7f4e826493a693fa5db09f4d5a108, apologies.
Issued a new release as well: https://github.com/ocornut/imgui/releases/tag/v1.84.1

**Comment by Legulysse** [comment]
Thanks for the release on master !
I just grabbed the latest docking branch to test the feature and I stumbled upon a similar bug :

When stacking some combinations of Begin(true)/Begin(false) calls, everything related to imgui disappears from the screen, like if nothing was rendered.
More specifically, it seems like as soon as I call a Begin(true), any additional call to Begin() will break the render whatever the boolean value.
I can reproduce this behaviour with a simple call around the imgui-demo.
Maybe it' a bug from the backend I use (sfml) or my integration of the backend ?
I haven't setup a test project with an official backend yet, but I can see to it if needed.

backend : sfml
commit (docking) : 47fb332fb20921658732107e115aa397e9b08cbe
os : win7

```
      // Tested cases.
      // false + false : good
      // false + true : good
      // true + true : bad
      // true + false : bad
      // false + false + true : good
      // false + true + false : bad
      // false + true + true : bad
      // true + true + true : bad
      // true + false + true : bad

      static bool a = false;
      static bool b = false;
      static bool c = false;
      ImGui::Checkbox("TestDisabled A", &a);
      ImGui::Checkbox("TestDisabled B", &b);
      ImGui::Checkbox("TestDisabled C", &c);
      ImGui::BeginDisabled(a);
      ImGui::BeginDisabled(b);
      ImGui::BeginDisabled(c);

      ImGui::ShowDemoWindow();

      ImGui::EndDisabled();
      ImGui::EndDisabled();
      ImGui::EndDisabled();
```

**Comment by Legulysse** [comment]
Update : The bug seems fixed if I move this line :
`g.DisabledAlphaBackup = g.Style.Alpha;`
Inside the following if block :
`if (!was_disabled && disabled)`
