### ISSUE TITLE
SDL2 + OpenGL 3 ES Android: weird X's

### ISSUE THREAD

**Issue by stupidestmodder** [ocornut/imgui#4456]
![Screenshot_20210821-123437_SDL plugin for C4droid](https://user-images.githubusercontent.com/44854972/130327211-92315afe-f556-4cbd-800d-f09b133f8a91.jpg)
![Screenshot_20210821-123809_SDL plugin for C4droid](https://user-images.githubusercontent.com/44854972/130327216-fe578473-c16b-47ee-9fba-90a699c392cf.jpg)
![Screenshot_20210821-123530_Gallery](https://user-images.githubusercontent.com/44854972/130327217-2c6ba6ec-435b-4c37-bbdb-a4ad0f637e3d.jpg)
Any idea on why those x thingies are here?

Android 11

the source code is just the sdl example code with this #define at the top "#define IMGUI_IMPL_OPENGL_ES2"
If i don't do this it errors trying to create the window with the error: Could not initialize OpenGL / GLES library

thxs in advance

**Comment by rokups** [comment]
Looks like dithering to me. https://forums.libsdl.org/viewtopic.php?t=11915

> If you can call GLES functions directly, try glDisable(GL_DITHER).

**Comment by stupidestmodder** [comment]
> Looks like dithering to me. https://forums.libsdl.org/viewtopic.php?t=11915
> 
> > If you can call GLES functions directly, try glDisable(GL_DITHER).

ooo thank you, ye that fixed it
![Screenshot_20210821-135441_SDL plugin for C4droid](https://user-images.githubusercontent.com/44854972/130329333-aa766da3-75a6-45d8-a4e0-7cf4fa27cd27.jpg)
🙂

**Comment by stupidestmodder** [comment]
oh uh, something i just noticed... why is my color palette limited?
![Screenshot_20210821-140912_SDL plugin for C4droid](https://user-images.githubusercontent.com/44854972/130329683-c7af66f6-23d2-4b7d-a65d-a8b7709caeef.jpg)
do i need to do something to increase it?

**Comment by meshula** [comment]
I'm not an Android expert, but I can speak to the general problem. The quantization the undithered image shows is typical of having a low bit depth surface somewhere, something less than 8 bits per color channel. Dithering, as in your first image, is a trick to make low bit depth images look smoother and hide banding. The fact that dithering was on by default says that something in your set up is causing a low bit depth surface somewhere, or your device can't display high bit depth surfaces, and OpenGL or the driver is trying to smooth things out to compensate.

**Comment by stupidestmodder** [comment]
uh.. idk why that would be, I have tested imgui with sfml before and it was showing normal colors, it's just with sdl2 and idk why :/
