### ISSUE TITLE
example_glfw_vulkan not working  redefinition and missing backend file

### ISSUE THREAD

**Issue by Zauroa** [ocornut/imgui#4457]
Hello.
I have started making a GLFW Vulkan app and wanted to add ImGUI. I have noticed that I could not add it because of conflicts .After that I checked the xempel to see how it is done but the exemple iself is not working because its missing bakend\imgui_impl_vulkan.cpp and as some redefinition issues. 
Can someon fix it ?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.

Closing
