### ISSUE TITLE
example_glfw_vulkan: not working : missing back end files and, as a lot of redifination errors

### ISSUE THREAD

**Issue by zauroa2** [ocornut/imgui#4458]
**example_glfw_vulkan: not working **

v1.84.1,  GLFW/Vulkan/imgui-1.84.1\examples\example_glfw_vulkan ,windows 10 .

Exemple not working  missing bakend file (backends\imgui_impl_vulkan.cpp) and many redefinitions erros.

// Here's some code anyone can copy and paste to reproduce your issue in a new project that use Vulkan and GLFW
```
#include "x64/imgui/imgui.h"
#include "x64/imgui/imgui_widgets.cpp"
```

This issue is present on new project and in the exemple

ps: thanks for banning my main account for reporting a serious issue whit the latest version that render imgui unusable on vulkan glfw.

**Comment by ocornut** [comment]
The vulkan examples are running on the build machine on a daily basis (see “actions”) tab. I am blocking just-created account that blatantly ignore issue guidelines.

**Comment by zauroa2** [comment]
why do I get that mutch error if it work ? ![Capture](https://user-images.githubusercontent.com/89313315/130329374-ecdbc994-d129-49eb-9828-2addeaf175b6.PNG)

**Comment by ocornut** [comment]
Well you are doing something wrong and probably misunderstanding the C++ build/link process, but in the absence of details we can’t magically help. 

It’s nobody fault but from our point of view we don’t have resources to help everyone with their code, I suggest to take this to a general programming forum. You may also post your project to github in case someone here would be willing to investigate it for you.

**Comment by ocornut** [comment]
PS: when we formally reopen Discussions this sort of discussion may find their place. You may open a topic in Discussions for this and someone may help.
