### ISSUE TITLE
Unused variable in imgui_impl_glfw.cpp, line 914

### ISSUE THREAD

**Issue by JamesBoer** [ocornut/imgui#4459]
Version: 1.84.1
Branch: docking

In imgui_impl_glfw.cpp, there is an unused variable at line 914
`ImGui_ImplGlfw_Data* bd = ImGui_ImplGlfw_GetBackendData();`

`bd` is never used except in an assert, but this still leaves a warning in release mode, for those of us who compile with that option, and worse, an error if we treat warnings as errors.  So a better option would be to just put the entire thing inside the assert, like this:

`IM_ASSERT(ImGui_ImplGlfw_GetBackendData()->ClientApi == GlfwClientApi_Vulkan);`

**Comment by ocornut** [comment]
Pushed a fix for this, thanks!

(As an unrequested suggestion: I think your day to day optimized build should preserve asserts, they are immensely helpful. What I often do in large projects is to have a "Debug" build (unoptimized, full debugging experience), "Release" (optimized, lesser debugging experience, debug & tools including asserts, "Final" (optimized, no debug/tools)

**Comment by JamesBoer** [comment]
Yeah, leaving asserts in a release build is somewhat more common in game development, where you really can't effectively run the full debug build too often because of performance reasons, in which case having a "final" fully optimized build is more important.  Personally, I don't like changing the meaning of "Release", and prefer a name like "Development" for the intermediate build which is optimized, but still has some debug info.

I don't really do this too often with my own projects at home, which tend to be smaller and don't require three different levels, because I can actually run the debug versions just fine.  And since I use CMake now, it's also a bit easier to go with the standard targets that CMake generates for you (Debug, Release, RelWithDebInfo, MinSizeRel).  If needed, you could just repurpose RelWithDebInfo for that sort of intermediate development mode.
