### ISSUE TITLE
Question about event handling

### ISSUE THREAD

**Issue by jukea** [ocornut/imgui#446]
Hi,

As far as I've seen, example integrations don't show any way to have the app handle "left over" events, not captured by imgui. For example, I would have expected ImGui_ImplDX11_WndProcHandler to "grab" a mouse event only if it occurs inside a imgui window.

To use the mouse to move a camera in a 3d scene, I had to let my app peek at all events, even if they were in fact "belonging" to imgui. This causes the camera to move even for clicks in imgui windows.

What would be a correct pattern to handle correct event passing between imgui and host app ? 

thanks

**Comment by ocornut** [comment]
There is a flag io.WantMouseCapture that tells you if ImGui wants inputs based on the mouse position you gave it. Same for keyboard.

**Comment by jukea** [comment]
Hm but in what file is this ? I'm doing a global text search in the master branch and I find no occurence of "WantMouseCapture" .

**Comment by jukea** [comment]
Ok found it, it's named  "WantCaptureMouse"

**Comment by ocornut** [comment]
Sorry yes, mistyped that out of memory. Out of curiosity have you read the comments/instructions in imgui.cpp? You are right that I should add a reference to those fields in the example application to make the information more accessible. I'll add that to my notes.

Let us know how that works.
