### ISSUE TITLE
Move child window in a parent window with a click of a button.

### ISSUE THREAD

**Issue by Friendlyman66** [ocornut/imgui#4467]
----

```
Dear ImGui 1.84.1 (18403)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx9
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

Okay so what i'm trying to do is to lock a child window on a parent window and be able to move the child window with a click of a button, for an animation. To change the position of the child i'm using the SetNextWindowPos with ImGuiCond_FirstUseEver condition. The cond makes the child unable to move anymore so that didn't work out for me and without the cond when i move the parent window the child is locked in one place because its changing the pos in the loop. 

So what i was thinking to do is getting a position of the parent window and then changing the child window pos to the position of the parent window. Which could potentially work. But i feel like there has to be a better solution than that, or a function that i do not know about to make it simpler. 

The desired output would be like in the video below but with the child moving with the parent window.

**Screenshots/Video**

https://streamable.com/1gd6gu

```
// Here's some code anyone can copy and paste to reproduce your issue

            static float posX = 200;
            ImGui::SetNextWindowSize(ImVec2(600, 600));
            ImGui::Begin("Hello, world!", 0,  ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoCollapse);

            ImGui::PushStyleColor(ImGuiCol_ChildBg, IM_COL32(255, 0, 0, 100));

            ImGui::SetNextWindowPos(ImVec2(posX, 95));
            ImGui::BeginChild("nextWindow", ImVec2(150, 600), false);

            ImGui::SetCursorPos(ImVec2(75, 300));
            if(ImGui::Button("Change Position"))     
                posX = 500;

            ImGui::PopStyleColor();
            ImGui::EndChild();
            ImGui::End();

```

**Comment by ocornut** [comment]
> So what i was thinking to do is getting a position of the parent window and then changing the child window pos to the position of the parent window. Which could potentially work. But i feel like there has to be a better solution than that, or a function that i do not know about to make it simpler.

That would be the right solution. I'm not sure what else you imagine could be done.

Instead of storing an absolute position, store an offset from the origin.

**Comment by ocornut** [comment]
Here's a demo:
```cpp
ImGui::Begin("Test");
float t = (cosf(ImGui::GetTime() * 3.0f) + 1.0f) * 0.5f;

ImGui::Text("Hello from parent");

ImVec2 child_base_pos = ImGui::GetCursorScreenPos();
ImVec2 child_offset = ImVec2(t * 200.0f, 0.0f);
ImGui::SetNextWindowPos(child_base_pos + child_offset);
ImGui::PushStyleColor(ImGuiCol_ChildBg, ImVec4(1, 0, 0, 1));
ImGui::BeginChild("hi", ImVec2(200, 200));
ImGui::Button("Hello from child");
ImGui::EndChild();
ImGui::PopStyleColor();

ImGui::End();
```

![moving_child](https://user-images.githubusercontent.com/8225057/130454931-3140dce6-103c-4241-bbb3-35d6ed2b9985.gif)
