### ISSUE TITLE
epoxy as opengl loader?

### ISSUE THREAD

**Issue by blakat360** [ocornut/imgui#4469]
I use imgui in an application. Using GLEW clashes with another third party library I'm using. I patched the dear imgui source in a very hacky way to get it working with epoxy as the opengl loader. The idea of epoxy is that it's lazy so more flexible when working with other loaders. 

Is there any interest in getting this back into the project? I would make a PR but the state of the patch is embarrassing and would need guidance on neatening it up.

**Comment by ocornut** [comment]
Last week we literally removed the need and issues with GL loader:
https://github.com/ocornut/imgui/issues/4445
So this shouldn;'t be an issue anymore. You are free to use Epoxy for your code while our code will use its own loader.
