### ISSUE TITLE
Function marked `IM_NORETURN` that actually returns in release

### ISSUE THREAD

**Issue by parbo** [ocornut/imgui#4470]
**Version/Branch of Dear ImGui:**

Version: 1.84
Branch: docking

**Back-end/Renderer/Compiler/OS**

Compiler: clang
Operating System: Linux / macOS

**My Issue/Question:**

```
    inline IM_NORETURN void FocusableItemUnregister(ImGuiWindow* window) { IM_ASSERT(0); IM_UNUSED(window); }                              // -> unnecessary: TempInputText() uses ImGuiInputTextFlags_MergedItem
```

In release, the assert gets removed, so the function will return. If building with `-winvalid-noreturn` and `-werror` the build fails. Maybe there should be an `IM_ASSERT_NDEBUG` macro?

A workaround for this specific case is of course to define `IMGUI_DISABLE_OBSOLETE_FUNCTIONS`.

**Comment by ocornut** [comment]
> In release, the assert gets removed, so the function will return

Are you getting a warning for that?

What a mess... I added this IM_NORETURN because Clang OSX would complain otherwise...
It may be simpler to disable that warning for that block.
