### ISSUE TITLE
Unexpected behavior for PushStyleColor

### ISSUE THREAD

**Issue by Friendlyman66** [ocornut/imgui#4474]
----

```
Dear ImGui 1.84.1 (18403)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx9
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

Once again hello, hopefully last time.
Okay so in older imgui version as far as i can remember i was able to PushStyleColor if bool is true and then just pop it but now when i do something like (code below) the app will just crash giving me an 
```Assertion failed: Size > 0, file D:\Desktop\imgui\imgui-master\imgui.h, line 1722

D:\Desktop\imgui\imgui-master\examples\example_win32_directx9\Debug\example_win32_directx9.exe (process 77516) exited with code -2147483645.````
Error

I also tried to Pop the style in another if statement after the text i wanted to modify the color on but that didn't work as well.

I was  trying to make an ui for a main menu and change the color of the button text instead of the box around it when clicked/hovered. 

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/63115987/130654390-8e7be68c-0afb-4fb6-905d-d7348c837ded.png)


```
// Here's some code anyone can copy and paste to reproduce your issue

            static bool active;

            ImGui::Begin("Main window");

            if (active)
            {
                ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(255, 0, 0, 255));
            }

            if (ImGui::Button("Active"))
            {
                active = !active;
            }

            ImGui::PopStyleColor();

            ImGui::End();

```

**Comment by ocornut** [comment]
That code was always illegal.
A call to a Push of any kind needs to be matched with a Pop.

**Comment by ocornut** [comment]
> I also tried to Pop the style in another if statement after the text i wanted to modify the color on but that didn't work as well.

```cpp
if (active)
    ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(255, 0, 0, 255));

if (ImGui::Button("Active"))
    active = !active;

if (active)
   ImGui::PopStyleColor()
```

The reason that would fail is in the case the button is pressed, your Push/Pop become unbalance for a frame.

You would need to do:

```cpp
if (active)
    ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(255, 0, 0, 255));
bool pressed = ImGui::Button("Active"))
if (active)
   ImGui::PopStyleColor()
if (pressed)
   active = !active;
```

or

```cpp
bool changing_style = active;
if (changing_style)
    ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(255, 0, 0, 255));

if (ImGui::Button("Active"))
    active = !active;

if (changing_style)
   ImGui::PopStyleColor()
```

**Comment by Friendlyman66** [comment]
Even tho i do 
`            static bool active;

            ImGui::Begin("Main window");

            if (active)
                ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(255, 0, 0, 255));

            if (ImGui::Button("Active"))
            {
                active = !active;
            }

            if(active)
                ImGui::PopStyleColor();

            ImGui::End();`
            
I get the same crash.
