### ISSUE TITLE
Create a window "sizer" with the "look" of a splitter

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#448]
Hi,

I have 2 window in my application, the first one is locked on the left and the other on the right (Like for docked windows).

I need a way to change the width of theses windows, in order to do this I havce look at the splitter code...

I have do 99% of the code, but I still have 2 issues, maybe you have better ideas ?

1) Once I click the split bar and move, it seems that the mouse is no more active ! So, I can't handle the "delta" ! 

FIXED : I use "window->DC.LastItemID = id;" ... but not sure it is the right way to go ?

2) The "RenderFrame" looks clipped by the window !

Notice that I have only implemented the left split, I will do other once it is stable.

```
void WindowSizer(char* name, int orientation, float thickness, float* size, float min_size)
	{
		bool isLeft = orientation == 0;
		bool isRight = orientation == 1;
		bool isTop = orientation == 2;
		bool isBottom = orientation == 3;

		bool isHorizontal = isTop || isBottom;
		ImGuiWindow* window = ImGui::GetCurrentWindow();

		ImVec2 backup_pos = ImGui::GetCursorPos();
		if (isHorizontal)
		{
			ImGui::SetCursorPosY(backup_pos.y + *size);
		}
		else
		{
			ImGui::SetCursorPosX(backup_pos.x + *size);
		}

		ImGuiStyle& style = ImGui::GetStyle();

		ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(1.f, 0, 0, 0));
		ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0, 0, 0, 0));          // We don't draw while active/pressed because as we move the panes the splitter button will be 1 frame late
		ImGui::PushStyleColor(ImGuiCol_ButtonHovered, style.Colors[ImGuiCol_HeaderHovered]);
		
		ImGuiID id = ImGui::GetCurrentWindow()->GetID(name);

		bool hovered, pressed, held;
		if (isLeft)
		{
			ImVec2 pos = ImVec2(ImGui::GetContentRegionMax().x + 1, 3);
			ImVec2 size = ImVec2(thickness, ImGui::GetContentRegionMax().y - 6);
			ImRect bb(pos, pos + size);

			window->DC.LastItemID = id; // Necessary ! Do I break something ?

			pressed = ButtonBehavior(bb, ImGui::GetCurrentWindow()->GetID(name), &hovered, &held, 0);

			const ImU32 col = GetColorU32(pressed ? ImGuiCol_ButtonActive : hovered ? ImGuiCol_ButtonHovered : ImGuiCol_Button);
			RenderFrame(bb.Min, bb.Max, col, true, style.FrameRounding);
		}

		ImGui::PopStyleColor(3);

		if (GImGui->HoveredId == GImGui->CurrentWindow->DC.LastItemID)          // This is to allow having other buttons OVER our splitter. All of this should be moved to ImGui
			GImGui->HoveredIdAllowOverlap = true;
		if (GImGui->ActiveId == GImGui->CurrentWindow->DC.LastItemID)
			GImGui->ActiveIdAllowOverlap = true;

		// Mouse cursor
		if (GImGui->HoveredId == GImGui->CurrentWindow->DC.LastItemID)
			ImGui::SetMouseCursor(isHorizontal ? ImGuiMouseCursor_ResizeNS : ImGuiMouseCursor_ResizeEW);
		else
			ImGui::SetMouseCursor(ImGuiMouseCursor_Arrow);

		if (ImGui::IsItemActive())
		{
			float mouse_delta = isHorizontal ? ImGui::GetIO().MouseDelta.y : ImGui::GetIO().MouseDelta.x;

			// Minimum pane size
			if (mouse_delta < min_size - *size)
				mouse_delta = min_size - *size;

			// Apply resize
			*size += mouse_delta;
		}
		ImGui::SetCursorPos(backup_pos);
	}
```

**Comment by krys-spectralpixel** [comment]
Is there a way to extend the clipped region of a window ? or to render over a window ?

**Comment by ocornut** [comment]
> Is there a way to extend the clipped region of a window ? or to render over a window ?

draw_list->PushClipRect() / PopClipRect()

**Comment by krys-spectralpixel** [comment]
Thanks :-D

**Comment by krys-spectralpixel** [comment]
Just one last issue, it seems that the clipping region does not use the new clipping region !

Or is there another setting I can change please ?

**Comment by ocornut** [comment]
Sorry, the ImDrawList call only affect ImDrawList APi. The ImGui side equivalent of the same name is not available as a public API now.

**Comment by krys-spectralpixel** [comment]
Thanks,

Do you see any solution then ? Because only a portion of the split bar can be selected !

**Comment by ocornut** [comment]
Not sure why you commented and replaced code from the original. The things you have replaced are now wrong.
- GetContentRegionMax return position in window space not in screen space, probably affects your bounding box. 
- You replaced a correct call to a ButtonBehavior() function with a rectangle test which is going to fail most of the time as you move the mouse. MouseDelta is always correct but I imagine your Hovered test just fails most of the time.
If you are not sure what's going on, debug the thing by displaying colored rectangle on screen.

Ps: you can replace the 4 lines to handle overlap with SetItemAllowOverlap() now.

**Comment by ocornut** [comment]
(Ah, I commented based on the code from the notification e-mail but it looks like the code above has been changed now.)

**Comment by krys-spectralpixel** [comment]
Yes sorry.. I always post the last version !

I need the full window content size because I render the split inside the window. I can render outside the window, but not handle mouse events without window !

The last problem is now to correctly allow the mouse click on the splitter, the current version only allow to select the split on a part of the "rendered split" !

**Comment by ocornut** [comment]
Could you post a repro and a screenshot so I know what you are talking about?
