### ISSUE TITLE
WantCaptureMouse and popups

### ISSUE THREAD

**Issue by neclepsio** [ocornut/imgui#4480]
**Version/Branch of Dear ImGui:**

Version: 1.81
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: custom backend written in Go (based on glfw+opengl3 backend)
Compiler: Go + GCC
Operating System: Windows

**My Issue/Question:**

From my understanding of source code, `WantCaptureMouse` always returns true when non-modal popups are open. I think this is because a click outside the popup should close the popup. In my application I use center and right mouse button to move the view and I'd like to be able doing so with a popup open, but do not find a way to do so. 

I'd like to do something like:

    if (!io.WantCaptureMouseIgnoreNonModalPopups && !(io.AnyPopupOpen && button == left)) {
         // handle the event in my application
    }

But I don't find a way. Could you help me? Thank you.

**Comment by ocornut** [comment]
Technically speaking we could strive to replace the imgui_internal`s `GetTopMostPopupModal()` with a `ImGuiPopupFlags_AnyModal` flag that would do the same thing in the public API, but I think we would consider it if (1) suggested technique worked and (2) it was useful to more users.

**Comment by ocornut** [comment]
> This is my idea
```
g.IO.WantCaptureMouseExcludingPopupClose = (mouse_avail_to_imgui && (g.HoveredWindow != NULL || mouse_any_down)) || (GetTopMostPopupModal() != NULL);
g.IO.WantCaptureMouse = g.IO.WantCaptureMouseExcludingPopupClose || (g.OpenPopupStack.Size > 0);
```

This doesn't seem to work unfortunately: because on the initial click `MouseDownOwned[i]` gets set based on popups being open:
```
for (int i = 0; i < IM_ARRAYSIZE(g.IO.MouseDown); i++)
{
    if (g.IO.MouseClicked[i])
        g.IO.MouseDownOwned[i] = (g.HoveredWindow != NULL) || (g.OpenPopupStack.Size > 0);
```
Which leads to us thinking we owned the initial click:
```
const bool mouse_avail_to_imgui = (mouse_earliest_button_down == -1) || g.IO.MouseDownOwned[mouse_earliest_button_down];
```
Which leads to an incorrect report while that button is held.
```
g.IO.WantCaptureMouseExcludingPopupClose = (mouse_avail_to_imgui && (g.HoveredWindow != NULL || mouse_any_down));
```

Fixing this requires us tracking a second set of `MouseDownOwned` and `mouse_avail_to_imgui`.
I'll see how this can be done neatly.

**Comment by ocornut** [comment]
Pushed a solution for this: 4aea1c5adbd0d745367db56b8569a935da950271

Called `io.WantCaptureMouseUnlessPopupClose`

Added tests for it (thanks @rokups)

**Comment by neclepsio** [comment]
Thank you so much!
