### ISSUE TITLE
Can't find anything about "##extra" in the FAQ

### ISSUE THREAD

**Issue by Erkaman** [ocornut/imgui#449]
In the file `imgui.h`, line 220-222 says:

```C++
// ID scopes
// If you are creating widgets in a loop you most likely want to push a unique identifier so ImGui can differentiate them.
// You can also use "##extra" within your widget name to distinguish them from each others. Read the FAQ for more details.
```

But I can't find any information about this in the FAQ. And as far as I have looked, I can not find any information about this in the files `imgui.h` and `imgui.cpp`. So where can I find information about the things mentioned in the comment?

**Comment by ocornut** [comment]
There is an entire (and the biggest) paragraph about id and the use of ## in imgui.cpp

**Comment by Erkaman** [comment]
Oh, now I found it. Thanks for the quick reply!

**Comment by ocornut** [comment]
I have tweaked this paragraph now to make it more clear for new users.
