### ISSUE TITLE
example_android_opengl3 fails

### ISSUE THREAD

**Issue by ambitslix** [ocornut/imgui#4494]
**Version/Branch of Dear ImGui:**

Version: 1.85 WIP
Branch: 1.85 WIP _(master)_

**sdl2/OpenGL2/Clang/Android**
**sdl2/OpenGL3/Clang/Android**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl2.cpp
or
Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Compiler: Clang _(if the question is related to building or platform specific features)_
Operating System: Android

**My Issue/Question:**

I'm trying to cross compile example_sdl_opengl2 and example_sdl_opengl3 under Linux for Android. I have latest Android Studio and NDK. My Android ABI is

TARGET=x86_64-linux-android
minSdkVersion: API=21

Getting following error for **example_sdl_opengl2**

```
/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++ -I../.. -I../../backends -g -Wall -Wformat `/Linux_x86_64_Release_android-clang-x86_64-cross-compiler/bin/sdl2-config --cflags` -c -o imgui_impl_opengl2.o ../../backends/imgui_impl_opengl2.cpp
../../backends/imgui_impl_opengl2.cpp:56:10: fatal error: 'GL/gl.h' file not found
#include <GL/gl.h>
         ^~~~~~~~~
1 error generated.
make: *** [Makefile:80: imgui_impl_opengl2.o] Error 1
```

Getting the following error for **example_sdl_opengl3**

```
/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib/x86_64-linux-android/21/crtbegin_dynamic.o:crtbegin.c:function _start_main: error: undefined reference to 'main'

```

I assume that example_sdl_opengl2 isn't supposed to work under Android now or ever, but I'm not sure why example_sdl_opengl3 isn't building or missing main.

**Comment by ocornut** [comment]
Hello,
Could you clarify how did you solve this?
Thank you!

**Comment by ambitslix** [comment]
Hello,

My apologies I didn't want to confuse as I'm still investigating these issues so I temporarily closed the issue...So I was able to build 

**example_sdl_opengl3**

by modifying the Makefile and adding -fPIC and -shared to the compiler/linker flags. However the resulting binary crashes with a sigsegv on android.

Then I built(cmake) and tried running

**example_android_opengl3**

it also crashes the same way.

I tried importing example_android_opengl3 into AndroidStudio but it didn't work. Just wanted to see if it would. 

I build other native apps (non-opengl) via the same route and they work fine. I'm building everything native on the command line via cmake etc. It seems that whenever I link to opengl the resulting binary crashes even if it doesn't call any opengl. 

The resulting crashes are non-debuggable although they have symbols. It seems there maybe something wrong with some compiler flags or linker flags. I will need to debug Android Studio gradle build compiler/linker flags for opengl project and compare to see what is different. At this point I don't know what else to do.

**Comment by rokups** [comment]
`imgui_impl_opengl2.cpp` is a legacy OpenGL backend which should not be used. It was also considered when creating Android example. Name may be a little confusing, but you are supposed to use `imgui_impl_opengl3.cpp`, which works with both GLES2 and GLES3.

**Comment by ambitslix** [comment]
@rokups Thanks for the confirmation.
