### ISSUE TITLE
Dear imgui not properly linking in Xcode 12.4

### ISSUE THREAD

**Issue by DrakonMichael** [ocornut/imgui#4496]
Hey everyone, new c++ and OpenGL developer so sorry if this question is dumb or has a very simple fix.

**Version/Branch of Dear ImGui:**
Version: 1.85 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.h, imgui_impl_opengl3.h
Compiler: Xcode (?)
Operating System: macOS Catalina (10.15.7)

**My Issue/Question:**

I'm trying to use dear imgui in an OpenGL project with glfw3, and while importing the library doesn't fail, when running it I keep getting "Undefined symbol for architecture" errors.

The library was installed by simply copying the .h and .cpp files in the root of the repository, as well as the related backends to my /usr/local folder.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/38846459/131349425-bfa9e6b4-d47c-43da-a93d-70764fc6628a.png)

The files I have:
![image](https://user-images.githubusercontent.com/38846459/131349966-589ea6f9-604e-494e-81c1-943a891a7aa5.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"

... After setting up OpenGL context...

IMGUI_CHECKVERSION(); // Error here
```
The error: 
```
Undefined symbols for architecture x86_64: "ImGui::DebugCheckVersionAndDataLayout(char const*, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long)", referenced from:
      Game::loop() in engine_base.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm willing to provide as much information about environment or code as is needed, just let me know.

**Comment by DrakonMichael** [comment]
Oops, right, I didn't have imgui.cpp file, but the problem is still here.
Same code, but now I get a bunch of other errors:

![image](https://user-images.githubusercontent.com/38846459/131351336-b62c0364-5422-43d0-966b-68f6c4d14a6e.png)

I've searched the directory for a couple of these symbols but they all seem to be defined In one file or another..

**Comment by ocornut** [comment]
Those are all defined in `imgui_draw.cpp` it looks like you are not linking this file in your project.

**Comment by ocornut** [comment]
I'm not using Xcode, but somehow that file is not linked in your project.

**Comment by DrakonMichael** [comment]
Alright, I'll try to figure it out.

Thanks for the help! :)

**Comment by DrakonMichael** [comment]
Sorry for reopening this, but for anyone who has this same problem, make sure that you check the "Add to targets" checkbox next to your OpenGL project when adding the imgui files to your Xcode project.

**Comment by lvaight** [comment]
I had the same problem. "Add to targets" didn't work for me. The solution I found is to add the relevant CPP files to the Compile Sources (in Build Phases).
