### ISSUE TITLE
"Max string size" vs "Pixel width" ?

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#450]
Hi,

I currently display some text, but there is a constraints... it cannot be longer than X pixels !

By example, lets say I want to write "Have a merry Christmas" with max size of 150 pixels.

I will have "Have a merry..."

The text must be cutted, I need to know the number of characters I can display in 150 pixels.

Is there a way to do this with the current API ?

**Comment by ocornut** [comment]
The ImFont::CalcTextSizeA() function has a max_width parameter which you can use, retrieve the end of text from the "remaining" parameter, then pass this to regular text functions.

**Comment by krys-spectralpixel** [comment]
Perfect. Thanks a lot :-D

And Merry Christmas !

**Comment by ocornut** [comment]
np
"Have a merry..."
