### ISSUE TITLE
Unhandled exception thrown: read access violation. GImGui was nullptr.

### ISSUE THREAD

**Issue by smashfan04** [ocornut/imgui#4500]
Hello, i have read ur FAQ and could not find the answer to my quiestion.
When i worked on my Imgui project today i changed some things like normal and got hit with the debugger error
"Unhandled exception thrown: read access violation. GImGui was nullptr." I have tried everthing nothing worked though!
I would really appreaciate some help with my issue.
I sent an image of the error too!
Thank you!
![fehler](https://user-images.githubusercontent.com/77336268/131485089-8401bf39-824e-425b-8128-a0049f8d7c4b.JPG)

**Comment by ocornut** [comment]
Hello,
As requested by the Issue Guidelines (#2261) there's nothing we can do or you can do if you don't look at the callstack and share your callstack. Also make sure you have asserts enabled.

**Comment by smashfan04** [comment]
how would i do that, to provide the info you need ?

**Comment by ocornut** [comment]
The callstack is available in the debugger windos.

**Comment by smashfan04** [comment]
okay, i made a screenshot of my callstack. 
thanks in advance!
![call](https://user-images.githubusercontent.com/77336268/131490518-332e1a7e-92e0-4f94-abf8-a822ea324f4f.JPG)

**Comment by ocornut** [comment]
GImGui is likely null if you haven't called `ImGui::CreateContext()` but you should learn to use your debugger. 

Also, sorry but #1586 should have realized that before. Good luck!
