### ISSUE TITLE
Striketrough text

### ISSUE THREAD

**Issue by niclar** [ocornut/imgui#4503]
Hi, wonderful library.
-Is there anyway to implement strikethrough for ImGui::Text in a table row ?

I suspect some laborious use of `ImGui::GetWindowDrawList()->AddLine` might do the trick. 
In that case how do I get the coordinates for the start and endpoint respectively for the active cell (or row) ?

**Comment by niclar** [comment]
solved it as;

`
ImVec2 cursorScreenPos = ImGui::GetCursorScreenPos();
cursorScreenPos.y += 5;
ImGui::GetWindowDrawList()->AddLine(cursorScreenPos, ImVec2(cursorScreenPos.x + 50, cursorScreenPos.y), IM_COL32(255, 255, 255, 255), 3.0f);`

**Comment by ocornut** [comment]
Hello,

You may be better off using (int)(FontSize*0.5f) as an offset or (int)(font->Ascent * 0.5f)

Strikethrough is listed as a desirable feature for when we'll refactor text functions.

**Comment by niclar** [comment]
@ocornut Thanks
