### ISSUE TITLE
multi-viewport  memory leaks

### ISSUE THREAD

**Issue by straywriter** [ocornut/imgui#4504]
**Version/Branch of Dear ImGui:**

Version: dear imgui, v1.84 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: Visual Studio 2019
Operating System: Windows 10

**My Issue/Question:**

This example has memory leak in multi-viewport case, how to fix
I didn't change any code
This does not seem to be the case with the other examples

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/48555863/131940840-9bad107a-e637-45b2-97b6-25dbe3a8facc.png)

Memory leaks when the example moves out of the window
![aa](https://user-images.githubusercontent.com/48555863/131941594-f3029b06-1164-4eb1-a2b2-eed1551cba13.gif)

When the window is moved back, memory is restored
![bb](https://user-images.githubusercontent.com/48555863/131941802-f97c1898-6633-424e-abb6-22d4cd4c3e25.gif)

**Comment by ocornut** [comment]
Three issues below yours this one is listed: #4468. Moving there…
Can you confirm if the workaround discussed in #4468 fixes it for you?

**Comment by ocornut** [comment]
Please also provide details about GPU and Drivers version. And _after_ testing if the changes discussed in the other are fixing the issue for you, you can also try updating drivers and see if it works without the changes.

**Comment by straywriter** [comment]
Thank you. I will do some work according to relevant content and get back to you after completion

**Comment by straywriter** [comment]
@ocornut 
hi，I found a way to solve this problem。
I have done some debugging work, but I still haven't found the specific cause. It may be the cause of OpengL or the incompatibility between GLFW creation window and OpengL. However, I haven't tested the CASE of SDL, so I'm not sure.
However, I found that the main problem occurred here:

```cpp
static void ImGui_ImplOpenGL3_InitPlatformInterface()
{
    ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();
    platform_io.Renderer_RenderWindow = ImGui_ImplOpenGL3_RenderWindow;
}
```


I took advantage of OpengL's backward compatibility features to solve this problem for the time being. This solution may not seem perfect, but at least it will keep memory from leaking.
Porting opengL2 ImGui_ImplOpenGL2_RenderWindow to opengl3 can solve the problem effectively.

```cpp
static void ImGui_ImplOpenGL2_InitPlatformInterface()
{
    ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();
    platform_io.Renderer_RenderWindow = ImGui_ImplOpenGL2_RenderWindow;
}
```

![cc](https://user-images.githubusercontent.com/48555863/131997419-69714818-7164-4aa7-a2a8-27924e42e30b.gif)

**Comment by ocornut** [comment]
Hello @straywriter,
Please post in #4468 and try the change mentioned here:
https://github.com/ocornut/imgui/issues/4468#issuecomment-906503250
There is a `features/opengl_buffer_update` branch of the repository you can test.

**Comment by ocornut** [comment]
Reverted the changes of #4468 with b8b0f9d, not using glBufferSubData() anymore.
**PLEASE REPORT IF YOU STILL HAVE ISSUES AFTER TODAY**.
I temporarily kept the alternative code path even though bd->UseBufferSubData is always false, allowing potential experiment shall new issues arises. Finger crossed this doesn't bite us back.
