### ISSUE TITLE
ImGui lib and Mac OS GUI/GFX Conflict

### ISSUE THREAD

**Issue by deesto1** [ocornut/imgui#4506]
I get graphical clashes with plugins that use the ImGui lib for interface drawing under Mac OS Catalina/Sur and X-Plane 11. Namely, SimBrief Helper, and SmartCopilot 3 plug-ins, for example.

I'm using a fresh clean install of Zibo 3.49.16, latest X-Plane version 11 updated (also fresh installation), and literally nothing else, not even (custom) scenery was loaded.

The Main Panel DUs and MCP displays, and ET Clock display start to flicker in Windowed mode, and even turn completely blank/black in Full Screen Mode. FMC is all fine though. It only happens when you load/recall or bring the plugin windows from the Plugin Menu.

I have contacted both developers of the plugins, and sparker. And here's what Alexander Garzon from SimBrief Helper plugin had to say on the matter:

"This is certainly an issue between imgui library and Mac OS devices. So, nothing I can do from my script to fix it unfortunatelly. I do not have any mac device either so personally I cannot verify the issue, but I read about this kind of problems previously."

Can this be fixed? Is it here that I need to report this issue? Who develops this library?

**Comment by ocornut** [comment]
We are the developers of dear imgui but you aren't providing enough information to help you with anything.
Please talk to X-Plane developers.

**Comment by deesto1** [comment]
Hello,

Thank you for getting back, if nothing else.

I've described the issue. What else do you need me to supply? As mentioned, the X-Plane developers have both insisted they can't fix anything with their scripts that simply use your library. I will get them to contact you on my behalf in any case. But not sure what else I can do but to report the issue to you in regards to the library and Mac OS devices?
