### ISSUE TITLE
Dockspace Window Does not Resize As Host Window Is Being Resized

### ISSUE THREAD

**Issue by apaly** [ocornut/imgui#4516]
**Version/Branch of Dear ImGui:**

Version: 1.85 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_opengl3.cpp 
Compiler: VS 2019
Operating System:  Wndows 10

**My Issue/Question:**

1. When the host window is being resized the dockspace it is hosting doesn't resize accordingly. It seems the dockspace resizing is suspended until the host window resizing is done. I observed this issue in the example_win32_directx9 example as well. Please see the screenshot below. I would like dockspace to resize as its host window is being resize, is this possible?

2. I have been trying with out success to find an example on how to implementing docking programmatically in dockspace with BeginDocked(). Could you please provide an example?

Thanks.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/57704706/132350003-2554721b-a9e5-4c6e-a9f9-ddd69592f005.png)

**Comment by ocornut** [comment]
> When the host window is being resized the dockspace it is hosting doesn't resize accordingly. 

This is out of the scope of Dear ImGui: it is an issue with Windows resizing by default being "modal" (the application stops running during resizing). You can look on the internet at solution to workaround this (e.g. I think it involves reacting to `WM_SIZE` event and setting a WM_TIMER event.

> I have been trying with out success to find an example on how to implementing docking programmatically in dockspace with BeginDocked(). Could you please provide an example?

There are no example and "BeginDocked()" is a very-internal function you shouldn't call.
You can use the experimental DockBuilder API in imgui_internal.h

**Comment by apaly** [comment]
Thanks for your quick reply.

Are you implying that I should create the dockspace and its content from the appropriate Windows event handler during resizing?

I also observed that after resizing the host window, the Dear Imgui windows docked in the dockspace are not resized/scaled to fit the dockspace. How can I fix this?

Thanks.

**Comment by ocornut** [comment]
> Are you implying that I should create the dockspace and its content from the appropriate Windows event handler during resizing?

No. The problem you have is that none of your code is running during resizing (your process is stuck in Windows blocking handling of the resizing). By default any application on Windows will behave like that.
If you google something like "draw while resizing window C++" you'll find solutions.

> I also observed that after resizing the host window, the Dear Imgui windows docked in the dockspace are not resized/scaled to fit the dockspace. How can I fix this?

That shouldn't be the case. Please provide a video and/or repro.

**Comment by apaly** [comment]
> Thanks for your quick reply.
> 
> Are you implying that I should create the dockspace and its content from the appropriate Windows event handler during resizing?
> 
> I also observed that after resizing the host window, the Dear Imgui windows docked in the dockspace are not resized/scaled to fit the dockspace. How can I fix this?
> 
> Thanks.

Thanks once again.
The screenshots below show what I mean. The first one shows full screen mode while the second shows window after resizing.  You would observe that the docked window on the left is not scaled proportionally to the host window size.

![image](https://user-images.githubusercontent.com/57704706/132354390-677366dd-5fbe-4c1a-908b-0cfe1e59fffd.png)

![image](https://user-images.githubusercontent.com/57704706/132354416-b7637313-959b-45c9-8fc0-318ff0135ae8.png)

**Comment by ocornut** [comment]
That's because by default we have a concept of a "central node" which doesn't claim space (it is useful for when that node contains e.g. game).

We're missing a `ImGuiDockNodeFlags_NoCentralNode` flag to address that (#3168)

**Comment by apaly** [comment]
Okay.
Is it possible to use `drawList.AddCallback` with the central node so that I can render directly into it? If this is possible could you please provide an example?

**Comment by ocornut** [comment]
> Is it possible to use drawList.AddCallback with the central node so that I can render directly into it? If this is possible could you please provide an example?

An example would be dependent of your rendering API and largely be out of scope (you are asking for an OpenGL/Vulkan/DirectX manual here)

What most people do is to render to texture using e.g. OpenGL API and then simply render the texture inside that window using e.g. `ImGui::Image()`. e.g. https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

**Comment by apaly** [comment]
Thanks, please bear me as I would like to clarify this.
With a normal Dear imgui window one would use Begin/End to add content to a window. How do I "access" the central node?

**Comment by ocornut** [comment]
Well truth is that I would advise against finding it. 
If you got the render-to-texture way, you simply have a "Game" window and let user dock it in the empty space.

But there is a `DockBuilderGetCentralNode()` api.

**Comment by apaly** [comment]
Thanks for all your replies.

That would be all.
