### ISSUE TITLE
Deterministic ImGui behavior 

### ISSUE THREAD

**Issue by Orongto** [ocornut/imgui#4517]
Hi, 

I am working on a networked project where deterministic behavior is required. Is ImGui behavior deterministic? Would beginning a new frame and making a set of ImGui calls result into the same behavior regardless of previous frames? I know there are certain factors that can influence the behavior such as style, storage, and .ini files. Assuming these (and IO) are synchronized, would ImGui produce deterministic behavior?

**Comment by ocornut** [comment]
If by deterministic behavior you mean "deterministic output", yes I think so.

There might be rare edge cases, notably unexpected dependencies during iterations of pool or storage where ordering would be affected by pointers. I can't think of one right now but not ruling it out.

**Comment by ocornut** [comment]
As per the precise wording of your question:

> Would beginning a new frame and making a set of ImGui calls result into the same behavior regardless of previous frames? 

NOT AT ALL.
Of course not, there are quantity of states stored in the context (e.g. previous inputs, active/hovered items etc.).

But I think what you meant is "running multiple contexts on each network device with same functions calls done in each of them" then yes.

I think you would need to clarify what you are actually trying to achieve/solve in order in get a viable answer.

**Comment by Orongto** [comment]
Yeah, with deterministic behavior I mean ImGui.Button(), IsHovered, IsItemClicked, etc. give the same results independent of previous frames. Are there any factors other than style, storage, and .ini file that can influence this behavior?

**Comment by ocornut** [comment]
The entire content of ImGuiContext influence every behavior. 
You need to provide more clarification.

**Comment by Orongto** [comment]
I am working on a deterministic online game that is using a custom rollback netcode solution (like GGPO). Each client simulates the game state based only on the synchronized input. The state does not get synchronized so all gameplay needs to be deterministic.

As the UI influences gameplay, I have both players simulate the UI of themselves and each other, allowing UI events to influence the gameplay while remaining deterministic. I am currently achieving this with my own custom deterministic UI system and is working fine but am trying to move to ImGUI as my UI is garbage.

I’m probably not explaining this very well but imagine the engine loads gamestep 323 and simulates that gamestep. Afterwards the state rolls back to gamestep 320 and is going to simulate that step. The result of this gamestep should be the same regardless of if the previous step was 323 or 319. So, both players need to produce the same UI events across devices regardless of the players' previous gamesteps as the frame order is not deterministic. I can add the ImGUIContext information to the state of the gamestep, so that will get rolled back with the other state, but it would require ImGUI to be deterministic with the same ImGUIContext.

If this is not viable let me know, I do not want to take too much of your time.

**Comment by ocornut** [comment]
> As the UI influences gameplay, 

That's the part I don't understand. The UI should be an interface to trigger gameplay events.

> it would require ImGUI to be deterministic with the same ImGUIContext.

I think it is, but cloning a context is not particularly supported neither easy.

**Comment by Orongto** [comment]
> That's the part I don't understand. The UI should be an interface to trigger gameplay events.

If the UI influences gameplay and only the inputs are synchronized between clients, then the UI needs to be part of the deterministic simulation. There is no other way with only input sync. Other people have used some type of event system and synchronize that as well. I wanted to keep the non-engine parts clean of netcode specific designs, so that UI code can directly modify the gameplay state as it would in singleplayer games, without any intermediate synchronized event system. That is why I chose this route. 

> I think it is, but cloning a context is not particularly supported neither easy.

I will stick with my UI for now then, as the determinism has to be fully right and any small discrepancy would not work in my context. Thanks for the quick responses!
