### ISSUE TITLE
Images don't show at unrounded position?

### ISSUE THREAD

**Issue by Kingalidj** [ocornut/imgui#4521]
**Version/Branch of Dear ImGui:**

Version: Dear ImGui 1.84 WIP (18311)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: Windows 10

**My Issue/Question:**

I created two panels with one showing an image and the other one having a slider  that changes the value of io.FontGlobalScale.
The panel with the Texture contains nothing but the Image. The image is only visible if the value of FontGlobalScale is a whole number. This is not an issue if I put text, a slider, etc.. in the same panel as the image.
After some more testing I also found out that if the padding is not a whole number the image also won't show. This time putting a text in the same panel won't fix it either.

![grafik](https://user-images.githubusercontent.com/44316365/132601230-85dd592f-aebf-4c8c-ae55-db50df7ca1f0.png)

![grafik](https://user-images.githubusercontent.com/44316365/132601303-eceab1e4-6829-47ad-90c3-aeb2dfe353f6.png)

Adding a text to the panel fixed it:
![grafik](https://user-images.githubusercontent.com/44316365/132601359-8f59d6d2-d34e-4176-af5a-40d615263b5f.png)

Changing the padding to (0.1f, 0.1f):
![grafik](https://user-images.githubusercontent.com/44316365/132601424-3c769551-b762-4768-8bd4-a675c559f495.png)

```
//Code to show the Texture

ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));

ImGui::Begin("Viewport");
ImGui::Text("test");
ImGui::Image((void*)(size_t)m_RendererID, ImVec2(800, 800), ImVec2(0.0f, 1.0f) , ImVec2(1.0f, 0.0f));
ImGui::End();
ImGui::PopStyleVar();

//Code for the Slider
ImGui::Begin("Settings");
ImGui::DragFloat("global scale", &io.FontGlobalScale, 0.005f, 1, 10, "%.2f", ImGuiSliderFlags_AlwaysClamp); // Scale everything
ImGui::End();
```

**Comment by rokups** [comment]
![image](https://user-images.githubusercontent.com/19151258/132651813-cfa4c44f-5838-4691-813b-fce6b2fbee5e.png)

Tested on SDL/opengl3 sample.
```cpp

static void GH4521()
{
    ImGuiIO& io = ImGui::GetIO();
    ImGuiStyle& style = ImGui::GetStyle();
    static ImVec2 padding = style.WindowPadding;
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, padding);

    ImGui::Begin("Viewport");
    ImGui::Text("Padding: %.2f %.2f", padding.x, padding.y);
    ImGui::Image(io.Fonts->TexID, ImVec2(800, 800), ImVec2(0.0f, 1.0f) , ImVec2(1.0f, 0.0f));
    ImGui::End();
    ImGui::PopStyleVar();

    //Code for the Slider
    ImGui::Begin("Settings");
    ImGui::DragFloat("global scale", &io.FontGlobalScale, 0.005f, 1, 10, "%.2f", ImGuiSliderFlags_AlwaysClamp); // Scale everything
    ImGui::DragFloat2("window padding", &padding.x, 0.01f, 0.01f, 10, "%.2f", ImGuiSliderFlags_AlwaysClamp);
    ImGui::End();
}
```

@Kingalidj can you confirm this snippet reproduces issue in our official samples?

**Comment by ocornut** [comment]
This suggest that the Image doesn't display if it's starting position is not rounded position.
Many layout functions tend to round the cursor position on output so this is probably why it works after `Text()`.
Generally speaking, using non-integer positions is currently ill-defined / ill-supported and therefore, `io.FontGlobalScale` is not well supported. But even so, I can't comprehend why the Image wouldn't appear here.

Can you confirm by using tests such as:
```cpp
if (io.KeyShift) // Hold "SHIFT" to offset the image
{
    ImGui::SetCursorPosX(ImGui::GetCursorPosX() + 0.1f);
    ImGui::SetCursorPosY(ImGui::GetCursorPosY() + 1.2f);
}
ImGui::Image(...)
```
or even simply
```
ImGui::SetCursorPosX(ImGui::GetCursorPosX() + ((float)rand() / RAND_MAX) * 2.0f);
ImGui::SetCursorPosY(ImGui::GetCursorPosY() + ((float)rand() / RAND_MAX) * 2.0f);
ImGui::Image(...)
```

However it doesn't seem to repro in the demo so I believe there are missing information.
If not sure try reproducing in the unmodified Dear ImGui examples.

![image](https://user-images.githubusercontent.com/8225057/132651837-4476a27c-b442-4f5f-a55b-72346b600f52.png)

**Comment by Kingalidj** [comment]
Thanks alot for the quick answers. I removed all my ImGui code and tried your suggestions, but I was unable to recreate the issue. It works just fine now. It must have been an issue on my part, unfortunatelly I have no Idea what it was.
