### ISSUE TITLE
since 6b1e094 Combobox in modal doesn't work in Docking branch for SDL, GLFW, OpenGL3 Linux, master still works

### ISSUE THREAD

**Issue by Cazadorro** [ocornut/imgui#4527]
Short on time for this one, luckily should be reproducible with imgui demo (which is what I used). 

I used the imgui demo / popup and modal windows/ stackmodal and non of the elements are selectable, ie I hover mouse over the expanded combo box list, and I can't select anything. 
tested with OpenGL 4+ SDL, GLFW on Centos 7. 

* Non modal combo box works
* Doesn't work even if modal is docked in main window. 
* Doesn't work if I disable docking and viewports while on docking branch
* DOES work on the current master branch. 

Video example (SDL OpenGL 4+ using OpenGL 3 example).  

https://user-images.githubusercontent.com/8828023/132898499-9b311018-c5b3-4bf4-b280-722a14c4b106.mp4

For example, SDL comparison:

doesn't work for: 
```
Dear ImGui 1.85 WIP (18412)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=8
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1063.00,723.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

works for : 

```
Dear ImGui 1.85 WIP (18413)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=8
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000001
 NavEnableKeyboard
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Comment by Cazadorro** [comment]
Note I just ran git checkout HEAD~50 from docking and it works there, trying to narrow down the commit that must have caused the issue

**Comment by Cazadorro** [comment]
It looks like 6b1e094 introduced this bug, https://github.com/ocornut/imgui/commit/6b1e094cfbd353792ab926dc054125e25d8370d8, it works at HEAD~4, but doesn't at HEAD~3

**Comment by ocornut** [comment]
Thank you for the report and investigation. Will look into fixing soon.

**Comment by ocornut** [comment]
Pushed a temporary hotfix 92a39f78b97ddea0e4d23b37aca2c9d3e97fa834

My commit 6b1e094cfbd353792ab926dc054125e25d8370d8 (3 days ago) broke `IsWindowFocused()`/`IsWindowHovered()` from considering popups as "child" of the window below it. As per the naming of that function and its flags, it is "correct" to not treat popups as child, but I severely broke API with this as I imagine people could have relied on it.

I think this may evolve into adding a ImGuiWindowFocused_PopupHierarchy flags (which the modal logic would use, and which would be an api breaking change), OR adding a `ImGuiWindowFocused_NoPopupHierarchy` which won't be an api breaking change and might be a better default.
