### ISSUE TITLE
How can I detect if a popup is shown, like a color edit?

### ISSUE THREAD

**Issue by Thraka** [ocornut/imgui#4529]
I have two windows, one is showing a texture, a tile map. When the mouse is over that it uses `OpenPopup` to show a little window displaying information about the tile.

There is a second window, one with settings for the map. It has a color edit control. If the user clicks on the color edit to popup, to select a color from the palette, and the popup is over the texture window, the logic from the texture window kicks in and shows the new popup.

I want to detect if any popup is being displayed an prevent my tilemap popup from displaying. How can I do that?

![imgui2](https://user-images.githubusercontent.com/2672110/132933773-f1a3befc-1b1b-4c65-9172-ffde42b0dffe.gif)

**Comment by Thraka** [comment]
OK I was able to figure it out, in a different way. I'm not checking if the surface preview item returns true for `IsItemHovered`. I thought `Hovered` meant like holding the mouse over for a second or two, but I believe it's indicating if the mouse is over the object or not.

I'll leave this open to see if anyone can correct me on this or provide an actual answer to the question. Otherwise, project maintainers, feel free to close this. I'll close it in a week if no other comments are provided. Thanks!

**Comment by PathogenDavid** [comment]
> but I believe it's indicating if the mouse is over the object or not.

This is correct. I'd say your new approach sounds like the correct one.

**Comment by ocornut** [comment]
Using IsWindowHovered() or IsItemHovered() is the right approach, as they will handle extra subtleties such as popup inhibit the click to close them, or having an active item generally blocking hover on other items.

I am not even sure what you used before?

Not that the functions have additional flags to fine-tune some options (eg that popup thing).

**Comment by Thraka** [comment]
@ocornut I was just using the following:

1. Get the mouse position
2. Get the rect of the screen area covered by the object
3. See if they intersect.
