### ISSUE TITLE
Make titlebar and scrollbar transparent

### ISSUE THREAD

**Issue by vtushevskiy** [ocornut/imgui#4533]
When I use 'ImGuiWindowFlags_NoBackground' window flag or 'SetNextWindowBgAlpha', it does not apply to scroll bars and title bar of the window. Is there some way how to make it semi-transparent?

**Comment by ocornut** [comment]
They use their own colors you can use PushStyleColor() to alter them, or more simply alter global Alpha by using PushStyleVar(ImGuiStyleVar_Alpha, alpha)/PopStyleVar() surrounding the Begin() call.

**Comment by vtushevskiy** [comment]
Yes it works but it applies to the text on title bar as well. I want to apply it to the background of the title bar and keep title text not transparent

**Comment by vtushevskiy** [comment]
I would expect to have something like ImGuiStyleVar_BgAlpha instead of ImGuiStyleVar_Alpha

**Comment by ocornut** [comment]
Well that's not the case.

**Comment by ocornut** [comment]
>  I want to apply it to the background of the title bar 

Title bar is not part of the background.
You can alter all the `ImGuiCol_TitleBg` `ImGuiCol_TitleBgActive` `ImGuiCol_TitleBgCollapsed` values for that.
