### ISSUE TITLE
How to disable resizing via imgui and hide grips on secondary viewports?

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#4534]
Hello,

**Version/Branch of Dear ImGui:**

Version: 1.84.2
Branch: docking / viewport

**Back-end/Renderer/Compiler/OS**

Back-ends: glfw and opengl3
Compiler: msvc
Operating System: win10 64

**My Issue/Question:**

I have always the crash same issue (https://github.com/ocornut/imgui/issues/3321) when i try to resize a chid windows
I tested in GLFW3 and SDL2 and i have the same issues. 
There is many similar report for this issue in the forums of GLFW3 and SDL2.
So its not the fault of ImGui

I can avoid this crash by using the window resizing (if the decoration is enabled) instead of via imgui

But If i disable the decorations with that line 

```cpp
io.ConfigViewportsNoDecoration = false;
```

I always have the grip who is displayed on child windows. 

The crash happen via this grip, but not via the windows.
because when i resize via the windows borders, the fbo is re created after the end of the resizing, 
afaik i not see any crash issue.
if i resize with the grip, the fbo is constantly recreated during the resizing and the crash happen.

so i would like to disable the grip and the resizing feature (via grip or edges) of imgui for the child windows. (not for internal windows of a child windows, just for the child windows himself)

Is there a easy way for doing that without breaking ImGui ?

**Comment by aiekick** [comment]
Im embarassed because i found the solution jsut after writing this question :) sorry :)

here my solution :

```cpp
auto win = ImGui::GetCurrentWindowRead();
// test is the window is in another viewport than the default 
// and so disbale title bar a,d resizing (the grip will be hidden, and the resizng feature via imgui will be disabled)
if (win->ViewportId != 0) 
	vFlag |= ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar;
ImGui::Begin(windows_name, &opened, vFlag);
```
and not forgot to disable decoration with that code :
```cpp
io.ConfigViewportsNoDecoration = false;
```

so i close it now :)

**Comment by aiekick** [comment]
ni im itred it make no sense to detect that otuside of the begin() / end()

**Comment by aiekick** [comment]
btw when im using 

```cpp
ImGui::OpenPopup(name.c_str());
bool beg = ImGui::BeginPopupModal(name.c_str(), (bool*)nullptr,
	flags | ImGuiWindowFlags_NoScrollbar);
```

the decoration is not appearing :

![AXFyNtNR9H](https://user-images.githubusercontent.com/1434736/133011180-d8ff493c-4fc4-4d9f-bb5c-0831329e1e6e.gif)

**Comment by ocornut** [comment]
Decorations are off on popups and transient windows such as tooltips.
You can force it via:

```cpp
ImGuiWindowClass window_class;
window_class.ViewportFlagsOverrideClear = ImGuiViewportFlags_NoDecoration;
ImGui::SetNextWindowClass(&window_class);
```

The viewport configuration flags are a little bit of a mess, will refactor at some point.
Enabling OS decoration isn't even very well supported right now:
- dear imgui decorations should generally be hidden (the resize grips but also title bar)
- on Windows, OS decorations are enforcing a minimum sizes that is impossible to override (well it is possible by it creates visual glitches in the window manager of Windows) so they are not suitable in all use cases.

It sucks but I think if you are affected by this issue you should consider using DX11 on Windows.

**Comment by aiekick** [comment]
Ok thank for the trick :)

If the bug is on GLFW / SDL side, not sure if Directx will not have the issue. ?

By the way my app is a cross platform Opengl Shader editor, so i cant use directx, or use directx for app and opengl for rendering but not sure after to display GL texture on a Directx ui. too much complex if possible i guess.
And i have this bug also on linux. (less often time, but i had)

By the way the decoration is interesting too, for have split feature (magnetic splitting way) of windows on screen, like we have on win and linux. (i guess also on macos)
Not sure if the window spliting can be made without decoration.

so for the moment, its the best trick i found.
