### ISSUE TITLE
 Auto scroll with data dynamic table

### ISSUE THREAD

**Issue by wawahuy** [ocornut/imgui#4535]
**Version/Branch of Dear ImGui:**

Version: 1.84.2
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Visual Studio 2019
Operating System: Windows 10 21H1

**My Issue/Question:**

I am looking for a solution with table, dynamic data and every time I update a new row it scrolls to the end and when I scroll to see a certain row it doesn't scroll automatically.

**Comment by ocornut** [comment]
Both `Demo->Examples->Log` and `Demo->Examples->Console` are implementing this.

```cpp
// Set scroll to bottom
[submit all your items]
if (AutoScroll)
    ImGui::SetScrollHereY(1.0f);
```

```cpp
// Set scroll to bottom unless scrolled up by user
[submit all your items]
if (AutoScroll && ImGui::GetScrollY() >= ImGui::GetScrollMaxY())
    ImGui::SetScrollHereY(1.0f);
```

**Comment by wawahuy** [comment]
thank you, awesome
