### ISSUE TITLE
Customize save path of settings file (*.ini)

### ISSUE THREAD

**Issue by Ghost-yc** [ocornut/imgui#454]
Can you provide an interface to change the default path of setting file?

**Comment by ocornut** [comment]
Hello,
You can change the IniFilename pointer in the ImGuiIO structure to anything you want. It must be done before the first call to NewFrame() where the first is loaded.

Make it point to a buffer (eg: an array or std::string's c_str() of yours) that is persistent for the lifetime of ImGui.

**Comment by Ghost-yc** [comment]
Thanks

**Comment by laszloturanyi** [comment]
If someone would bump into this thread: it is solved now.

https://github.com/ocornut/imgui/blob/master/imgui.h#L888
