### ISSUE TITLE
How to save and restore cursor position with SameLine()

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#4540]
**Version/Branch of Dear ImGui:**

Version: 1.78
Branch: Master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui.net
Operating System: Windows 10

**My Issue/Question:**

Is it possible to use `GetCursorPosition()` , temporary override the cursor position with `SetCursorPosition()` and then restore the original position to continue building a list of ui-components?

It looks like `SameLine()` is referring to a position that cannot be set with `SetCursorPosition()`. 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/1732545/133296328-a45329fa-1939-4873-9d58-62b3c4ec4738.png)

```
            ImGui.Button("Element1");
            var keep = ImGui.GetCursorPos();
            ImGui.SetCursorPos(new Vector2(100,100));
            ImGui.Button("Element at 100x100");
            ImGui.SetCursorPos(keep);
            ImGui.SameLine();
            ImGui.Button("Should be next to Element1");
            
```

**Comment by ocornut** [comment]
Why don’t you call SameLine() before backuping the cursor position?

**Comment by pixtur** [comment]
Because it's a flexible layout that only sometimes requires a `SameLine()`

It looks like this: 
![image](https://user-images.githubusercontent.com/1732545/133297997-81853f57-f725-42a4-87df-d9fa22202766.png)

**Comment by ocornut** [comment]
It looks like you have all the bricks to do it. You can do SameLine, GetCursorPos, NewLine possibly?

> It looks like SameLine() is referring to a position that cannot be set with SetCursorPosition().

That position is `g.CurrentWindow->DC.CursorPosPrevLine`.
But tehnically tree fields used by SameLine() are `CursorPosPrevLine`, `PrevLineSize`, `PrevLineTextBaseOffset` in `g.CurrentWindow->DC` but unless you need to reinstate text base offset it will simpler to toy with the high-level functions. 

We have a few internal helpers to manipulate that stuff (e.g. `SetCursorPosYAndSetupForPrevLine()` but they are not adequate for external stuff).

**Comment by pixtur** [comment]
Thanks for this detailed explanation. 
I didn't manage to call `SameLine()`  before overriding the cursor position. But I found a workaround where I simulate that behavior by keeping line start positions and advancing those with the last `GetItemSize()` for each element.
