### ISSUE TITLE
Disable viewport resize handles on a per side basis

### ISSUE THREAD

**Issue by jeremykleve** [ocornut/imgui#4545]
Version: 1.85 WIP
Branch: docking

I would like to be able to disable different sides of a dockspace / nodes resize handles depending on the context that the layout is in. For example in the image I shared below I am resizing the main window but accidentally grabbed that right most  handle and it shows the black background during my resize. Is there currently anyway to disable handles on a case by case basis?

![image](https://user-images.githubusercontent.com/40273160/133522577-cb9473ff-bc7f-4782-804f-a41a2b130b66.png)

```

**Comment by ocornut** [comment]
Please provide more details about your use case so we are not answering a [XY Problem](https://xyproblem.info/).
There are ambiguities in your wording and screenshots.
If you want that content to always fill your platform window why isn't it docked to that viewport using e.g. `DockspaceOverViewport()` ?

**Comment by jeremykleve** [comment]
Ah ok, im still getting used to the docking and multi-viewport API. I didnt know about the DockspaceOverViewport() functionality yet. I rebuilt my layout with that and the issue resolved itself.
