### ISSUE TITLE
Crash in docking windows when use ImGui::InputTextMultiline()

### ISSUE THREAD

**Issue by RamilGauss** [ocornut/imgui#4548]
From example_win32_directx9 with my edits:

![imgui_docking_bug](https://user-images.githubusercontent.com/5641263/133555011-e1bfff51-26fe-46c2-b85f-0f6dbe09247b.gif)

**Comment by rokups** [comment]
Please provide a minimal code that reproduces the problem, ideally in one of our standard examples. Also please fill out issue template. It is there for a reason, and that reason is not to be ignored.

**Comment by ocornut** [comment]
Your InputTextMultiline calls don’t have a proper ID so they are conflicting with the window. Please read the FAQ about use of ID and ID stack. Same issue as already been submitted many times here.

**Comment by RamilGauss** [comment]
Thanks for feedback.

**Comment by ocornut** [comment]
Linking to same issues #4375  #4158  #4008  #2562 

Going to try finding a way to detect/report on this particular error more easily.
