### ISSUE TITLE
How to set focus on a InputText by default

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#455]
Hi,

I have a small window, with an input box and a buttons.

I have try to use the following code to set the focus by default to the input box.
But the problem is that now when I click on the button, it does not return true (not printf) !

How can I set the focus by default to this control ?

```
ImGui::SetKeyboardFocusHere(-1);
ImGui::InputText(...)
if (ImGui::Button("ok"))
{
 printf("OK");
}
```

**Comment by ocornut** [comment]
Your code is setting focus every frame, so that will steal the focus from the Button every frame and you can't click a button...

The SetKeyboardFocusHere() function is missing a conditional parameter (e.g. ImGuiSetCond_Appearing) to trigger the action only when opening the window. That's somewhere in my todo list but I'm not sure how easy that would be to implement.

You can replicate this by calling it once yourself at the time you open the window.

Alternatively so you can use various tests to only set focus in certain condition, e.g.

```
if (ImGui::IsRootWindowOrAnyChildFocused() && !ImGui::IsAnyItemActive() && !ImGui::IsMouseClicked(0))
   ImGui::SetKeyboardFocusHere(0);
```

PS: ImGui::SetKeyboardFocusHere() with the default parameter (0) is correct here, although it won't make a difference if you only have 1 focusable widget.

**Comment by jpreiss** [comment]
FYI for others trying to follow ocornut's previous comment https://github.com/ocornut/imgui/issues/455#issuecomment-167440172, it does not compile on newer versions.

Following a newer comment https://github.com/ocornut/imgui/issues/1382#issuecomment-351061083,

```IsRootWindowOrAnyChildFocused()```

should be updated to:

```IsWindowFocused(ImGuiFocusedFlags_RootAndChildWindows)```

**Comment by krulci** [comment]
> FYI for others trying to follow ocornut's previous comment [#455 (comment)](https://github.com/ocornut/imgui/issues/455#issuecomment-167440172), it does not compile on newer versions.
> 
> Following a newer comment [#1382 (comment)](https://github.com/ocornut/imgui/issues/1382#issuecomment-351061083),
> 
> `IsRootWindowOrAnyChildFocused()`
> 
> should be updated to:
> 
> `IsWindowFocused(ImGuiFocusedFlags_RootAndChildWindows)`

Where exactly does this go?
I am using IMGUI.NET.
```cs
public unsafe string InputText(string id, string value, int item_width = 50, string? lable = null)
        {
            var str = value ?? "";

            ImGui.PushID(id);
            ImGui.PushItemWidth(item_width);
            ImGui.InputText(lable ?? "", ref str, 1024, ImGuiInputTextFlags.CallbackAlways, data =>
            {
                str = Marshal.PtrToStringUTF8((IntPtr)data->Buf) ?? string.Empty;
                return 1;
            });
            ImGui.PopItemWidth();
            ImGui.PopID();

            return str;
        }
 ```
 ```cs
 private void InputOrEdit(int unit_index, int? edit_index = null)
        {
            ImGui.SetNextWindowPos(new System.Numerics.Vector2(ImGui.GetIO().DisplaySize.X * 0.5f, ImGui.GetIO().DisplaySize.Y * 0.5f), ImGuiCond.Always, new System.Numerics.Vector2(0.5f, 0.5f));
            var timeline = TimeLineData[SelectedTimeLine];
            if (ImGui.BeginPopupModal($"{PsImGuiWindows.InputUB}", ref p_open, ImGuiWindowFlags.NoDocking | ImGuiWindowFlags.NoCollapse | ImGuiWindowFlags.NoResize | ImGuiWindowFlags.AlwaysAutoResize))
            {
                if (ImGui.IsWindowFocused(ImGuiFocusedFlags.RootAndChildWindows) && !ImGui.IsAnyItemActive() && !ImGui.IsMouseClicked(0))
                    ImGui.SetKeyboardFocusHere(0);
                ImGui.Text("Input Execution Time");
                string execution_frameStr = "";
                execution_frameStr = InputText("InputOrEdit", execution_frameStr, 100, "frame");
                Console.WriteLine(execution_frameStr);
                ImGui.SetCursorPosX((ImGui.GetWindowSize().X - 2 * ImGui.CalcTextSize("OK").X) / 2); // Center the button
                if (ImGui.Button("OK"))
                {
                    float execution_frame;
                    Console.WriteLine(execution_frameStr);
                    if (float.TryParse(execution_frameStr, out execution_frame))
                    {
                        if (edit_index != null)
                        {
                            timeline.playerGroupData.UBExecTimeData[unit_index][edit_index.Value] = execution_frame;
                            timeline.playerGroupData.SortUbTimes();
                            p_open = false;
                        }
                        else
                        {
                            timeline.playerGroupData.UBExecTimeData[unit_index].Add(execution_frame);
                            timeline.playerGroupData.SortUbTimes();
                            p_open = false;
                        }
                    }
                }
                ImGui.EndPopup();
            }
        }
```
