### ISSUE TITLE
ImGui video recording

### ISSUE THREAD

**Issue by misah27973** [ocornut/imgui#4554]
Hello. I'm creating an admin panel in my game on imgui d3d11, but when recording a video in full screen mode, imgui's render is not visible, can I somehow fix it?

**Comment by ocornut** [comment]
Question has likely nothing to do with dear imgui, rather with your own recording software and how you wired your graphics library.
It is possible that exclusive fullscreen mode is preventing some software from recording, in which case you can use a different software or use borderless fulllscreen mode.
