### ISSUE TITLE
How to set Translucent Color with example ?

### ISSUE THREAD

**Issue by majiaoliya** [ocornut/imgui#4558]
I'm gitclone imgui and `make `the `example_sdl_opengl3` on linux , and now i want to know how to make the `MainWindow` (Dear ImGui SDL2+OpenGL3 example) 's backgroud `Translucent`.
  like this image show.
  what should i do ?  and what should i do if i use `windows10` to translucent  background ?
  thanks !!!
![图片](https://user-images.githubusercontent.com/35868195/133985693-4a9cff1f-c41e-4c7a-9b29-441061622ee7.png)

**Comment by ocornut** [comment]
Hello,
Question has nothing to do with dear imgui.
That's a clear color entirely under the control of your application. And making a window transparent is a question you have to look into from SDL point of view
