### ISSUE TITLE
Null reference crash

### ISSUE THREAD

**Issue by BattleAxeVR** [ocornut/imgui#4562]
![image](https://user-images.githubusercontent.com/11604039/134026107-d8d5f476-7961-4c75-a864-3fe5cc4461c2.png)

bd is null.

Happens 100% when I close my app. 

Tired of having to add a null check after every merge so I figured I might as well report it.

Before anyone says "just define IMGUI_IMPL_WIN32_DISABLE_GAMEPAD", no, that's not correct. 

Libraries shouldn't crash on nullptrs.

Thanks!

**Comment by PathogenDavid** [comment]
The backend data should not normally be null. It being null implies there's something else wrong with your app. (I won't dispute that it could be handled more gracefully, but IMO it should be an assert not a null check.)

Are you calling `ImGui_ImplWin32_Shutdown` without calling `ImGui_ImplWin32_Init`?

Are you calling `ImGui_ImplWin32_Shutdown` more than once?

Are you calling `ImGui::DestroyContext` before `ImGui_ImplWin32_Shutdown`?

Are you using `ImGui::SetCurrentContext`?

Are you building Dear ImGui (or the backend) as a shared library/DLL?

**Comment by BattleAxeVR** [comment]
Ahh, I just checked and I was calling my shutdown sequence twice, good catch. Still, it's good to add a null check anyway, (I would never allow that to pass a CR personally and neither would anyone at any of the myriad game studios I've worked at either).

If you're not supposed to call ImGui_ImplWin32_Shutdown twice (or risk having a nullptr crash), it would be better to put an assert to enforce the caller's behaviour adheres to the expectations of the API. But either way, thanks.

**Comment by ocornut** [comment]
Pushed c6ca327fb2c4a0bb35b92a1ca8633991379463df with more explicit asserts.

We are a low-level library and frequently crash on NULL pointers (rather than adding redundant asserts at the same location where the crash would happen), but on "key" functions like this I agree it makes sense to add an explicit assertion.
