### ISSUE TITLE
How to use Cmake build the example_sdl_opengl2 ?

### ISSUE THREAD

**Issue by majiaoliya** [ocornut/imgui#4564]
# How to use Cmake build the example_sdl_opengl2 ?
* **I have do this :**
   * git clone imgui
   * make example_sdl_opengl2 success
   * run example_sdl_opengl2  `success`

* **I want do this :**
     * use `QT creator` and `CMake` to build this example_sdl_opengl2 

* **Now problom**
    * i write `CMakeLists.txt`
      ```
        cmake_minimum_required(VERSION 2.8)
        
        project(main)
        
        set(IMGUI_DIR ./imgui)
        include_directories(/usr/include/SDL2)
        include_directories(${IMGUI_DIR} ${IMGUI_DIR}/backends)
        FILE(GLOB SC_FILES "*.cpp" "*.h" ${IMGUI_DIR}/"*.cpp" ${IMGUI_DIR}/"*.h")
        
        add_executable(${PROJECT_NAME} ${SC_FILES})
        
        target_link_libraries(main SDL2)

   
    * the project tree is 
       ![图片](https://user-images.githubusercontent.com/35868195/134053906-48fe2aa3-87f3-47bc-b823-70cd63d62f26.png)
       ![图片](https://user-images.githubusercontent.com/35868195/134054088-d1b42d8d-3e69-42f5-bacd-07b2b0a4cf02.png)


    * cmake is ok, but compile error
      ![图片](https://user-images.githubusercontent.com/35868195/134054454-95a0d53b-4354-4c85-80a8-ade5a005cbd1.png)

  * **What should i do now ? thanks**

**Comment by PathogenDavid** [comment]
This is more of a CMake question than a Dear ImGui question. (Also in the future, please read the issue template. The first sentence literally says that this isn't the appropriate place to ask this question.)

> ```cmake
>  FILE(GLOB SC_FILES "*.cpp" "*.h" ${IMGUI_DIR}/"*.cpp" ${IMGUI_DIR}/"*.h")
> ```

This line is not well-formed. The entire pattern needs to be within quotes, IE:

```cmake
 FILE(GLOB SC_FILES "*.cpp" "*.h" "${IMGUI_DIR}/*.cpp" "${IMGUI_DIR}/*.h")
```

**Comment by ocornut** [comment]
Moreover you will link to compile and link the backends of your choice (e.g. SDL + some renderer) and the appropriate libraries for them.

**Comment by majiaoliya** [comment]
> This is more of a CMake question than a Dear ImGui question. (Also in the future, please read the issue template. The first sentence literally says that this isn't the appropriate place to ask this question.)
> 
> > ```cmake
> >  FILE(GLOB SC_FILES "*.cpp" "*.h" ${IMGUI_DIR}/"*.cpp" ${IMGUI_DIR}/"*.h")
> > ```
> 
> This line is not well-formed. The entire pattern needs to be within quotes, IE:
> 
> ```cmake
>  FILE(GLOB SC_FILES "*.cpp" "*.h" "${IMGUI_DIR}/*.cpp" "${IMGUI_DIR}/*.h")
> ```

thank very much !!!

**Comment by majiaoliya** [comment]
> Moreover you will link to compile and link the backends of your choice (e.g. SDL + some renderer) and the appropriate libraries for them.

thanks very much !!!
