### ISSUE TITLE
ImGui::Image drawing off by one pixel on max of x/y axes

### ISSUE THREAD

**Issue by RandyGaul** [ocornut/imgui#457]
The line (from imgui.cpp):

    
        window->DrawList->AddImage(user_texture_id, bb.Min+ImVec2(1,1), bb.Max-ImVec2(1,1), uv0, uv1, GetColorU32(tint_col));

Seems to have +- ImVec(1,1) to the bounding box so that the image draws within the white outline rect, however, in this image we can see the rendering of the bottom right corner is *still* off by one, as seen by rendering a 1x1 white image, which appears as a 4x4 ImGui::Image rendering (ignore the "house_yellow.png" tooltip text):

![off by one](https://i.imgur.com/oM32QxX.png)

Here I've rendered a 4x4 image, blown up to render in a 16x16 pixel quad:

![off by one again](https://i.imgur.com/kySgD05.png)

Here is my attempted fix:

    void ImGui::Image(ImTextureID user_texture_id, const ImVec2& size, const ImVec2& uv0, const ImVec2& uv1, const ImVec4& tint_col, const ImVec4& border_col)
    {
        ImGuiWindow* window = GetCurrentWindow();
        if (window->SkipItems)
            return;
    
        ImRect bb(window->DC.CursorPos, window->DC.CursorPos + size);
        if (border_col.w > 0.0f)
            bb.Max += ImVec2(1,1);
        ItemSize(bb);
        if (!ItemAdd(bb, NULL))
            return;
    
        if (border_col.w > 0.0f)
        {
            window->DrawList->AddRect(bb.Min, bb.Max, GetColorU32(border_col), 0.0f);
            window->DrawList->AddImage(user_texture_id, bb.Min+ImVec2(1,1), bb.Max, uv0, uv1, GetColorU32(tint_col));
        }
        else
        {
            window->DrawList->AddImage(user_texture_id, bb.Min, bb.Max, uv0, uv1, GetColorU32(tint_col));
        }
    }

Resulting in:

![not off by one](https://i.imgur.com/sj2gjGy.png)

**Comment by ocornut** [comment]
Thanks, will look into it but there is a possibility this is already fixed by a few of the commits made two weeks ago.
https://github.com/ocornut/imgui/commit/b49a985324981ef77caf12f1eacf12b6bb93cd80

Are you running latest?

**Comment by RandyGaul** [comment]
Yes indeed I am, also it's broken in your latest version: https://github.com/ocornut/imgui/blob/master/imgui.cpp#L5361

A quick copy paste will fix the bug, but you might want to verify *why*, as I have no idea why there was an off-by-one issue in the first place -- the code logic looks solid to me (despite the visual bug), assuming AddRect does what it's assumed to do. So my fix might be band-aiding over something else.

**Comment by ocornut** [comment]
You are right, I've been investigating this now - AddRect is off by one pixel compared to a AddLine or AddRectFilled with same proportions.

**Comment by ocornut** [comment]
Fixed now.
I have fixed AddRect() and added a note about the 1 pixel different in the "api breaking change" section, shall it bother anyone, but I imagine it'd be an easy fix for people who did their own drawing.
