### ISSUE TITLE
How do I get a text label to appear on top of a filled triangle?

### ISSUE THREAD

**Issue by mesher1982** [ocornut/imgui#4572]
Hi,

I'm adding a text label to identify a node in a tri mesh. But the label is hidden behind the filled triangle. How do I get the label to appear on top of the filled triangle?

Thanks in advance.

Here is my current code

const ImColor color2 = ImColor(1.0f, 1.0f, 1.0f, 1.0f);
const ImU32 col2 = ImColor(color2);
std::string text = "test";
draw_list->AddText(ImVec2(pos[0], pos[1]), col2, &text[0], &text[0] + text.size());

const ImColor color = ImColor(1.0f, 0.0f, 1.0f, 1.0f);
const ImU32 col = ImColor(color);
draw_list->AddTriangleFilled(ImVec2(pos[0], pos[1]), 
						ImVec2(pos[2], pos[3]), 
						ImVec2(pos[4], pos[5]), col);

![image](https://user-images.githubusercontent.com/84014769/134181655-abb002cf-6ade-46a8-a868-c450c03bf555.png)

**Comment by ocornut** [comment]
Draw the triangle first and then the label…

**Comment by mesher1982** [comment]
I get the same issue when I draw the filled triangle first and then add the label.

Here's the revised code:

const ImColor color = ImColor(1.0f, 0.0f, 1.0f, 1.0f);
const ImU32 col = ImColor(color);
draw_list->AddTriangleFilled(ImVec2(pos[0], pos[1]), 
					      ImVec2(pos[2], pos[3]), 
			                      ImVec2(pos[4], pos[5]), col);

const ImColor color2 = ImColor(1.0f, 1.0f, 1.0f, 1.0f);
const ImU32 col2 = ImColor(color2);

std::string text = "test";
draw_list->AddText(ImVec2(pos[0], pos[1]), col2, &text[0], &text[0]+text.size());

![image](https://user-images.githubusercontent.com/84014769/134212682-e3af55aa-c8b9-46b1-97cb-49d590aa7479.png)

**Comment by ocornut** [comment]
Well you are probably rendering another triangle over the already drawn text...
Consider rendering all triangles first, then all text elements.

You can also use a `ImDrawListSplitter` to split rendering into 2 channels (one for all triangles, one for all texts) if its easier/faster to draw out of order for you.

**Comment by mesher1982** [comment]
Your suggestion worked. I rendered all the triangles first and then the text. Thank you!
