### ISSUE TITLE
Backgound hovered

### ISSUE THREAD

**Issue by vtushevskiy** [ocornut/imgui#4574]
Is there any way how to check if background canvas (where there is no ImGui window) hovered? 
I can check if ImGui window is hovered, but it is false when I drag some slider or interact with any buttons or popups.

**Comment by PathogenDavid** [comment]
Please read the FAQ next time. This exact question is addressed there, and it's even mentioned in the documentation for `IsWindowHovered`. Also be mindful of [the XY problem](https://xyproblem.info/), it's more helpful to tell us what you actually want to accomplish.

[The relevant FAQ entry can be found here.](https://github.com/ocornut/imgui/blob/fba756176d659a8de8f711f68a4a04c675add942/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application)

**Comment by ocornut** [comment]
Thanks David!
Adding some extra comments for searchability.

```
// Flags for ImGui::IsItemHovered(), ImGui::IsWindowHovered()
// Note: if you are trying to check whether your mouse should be dispatched to Dear ImGui or to your app, you should use 'io.WantCaptureMouse' instead! Please read the FAQ!
```
