### ISSUE TITLE
TexCoord Convention

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#458]
Hi.

This is just a simple question: I use openGL and I've noticed (if I've not doing something wrong)) that when I load images using <b>stb_image</b> then I have to specify texcoords using the Direct3D convention (I'm talking about ImGui::Image(...) and ImGui::ImageButton(...)). 

Now there's nothing bad about it. 

I was just wondering if there was a convention we have to use, because probably some code using those two methods is portable between OpenGL and Direct3D if one of them changes its texcoord convention.

P.S. I don't know if I had been clear enough: I know that I can flip the images vertically (after loading) to change the convention. For example in <b>stb_image</b>:
```c++
// flip the image vertically, so the first pixel in the output array is the bottom left
STBIDEF void stbi_set_flip_vertically_on_load(int flag_true_if_should_flip);
```
but I was just asking if there was some kind of "ImGui standard convention" to use.

Maybe adding an imgui example using ImGui::Image(...) and ImGui::ImageButton(...) on a sample image would clarify my doubt, but I know that that would trigger the additional dependency to stb_image.

[<b>Edit</b>] P.S.2: according to this link:
http://stackoverflow.com/questions/19770296/should-i-vertically-flip-the-lines-of-an-image-loaded-with-stb-image-to-use-in-o
imgui is actually using the OpenGL texture convention (UV origin for OpenGL is bottom-left), but if I want to use it, I have to flip the image. 
In any case ImGui::Image(...) ImGui::ImageButton(...) should be documented about it.

**Comment by ocornut** [comment]
UV coordinates used by the font system assume that (0,0) is top-left of the texture and (1,1) is bottom-right. 

However when it comes to passing UV coordinates for your own textures to Image/ImageButton it doesn't really matter what convention you use. It is merely passing the UV to your renderer, untouched and unknown.

The difficulty with adding an image to the sample it that it would require every sample to load/upload the texture.

**Comment by Flix01** [comment]
> UV coordinates used by the font system assume that (0,0) is top-left of the texture and (1,1) is bottom-right. 

Ok, then I'll use this convention for images too, even if I use OpenGL.

> However when it comes to passing UV coordinates for your own textures to Image/ImageButton it doesn't really matter what convention you use. It is merely passing the UV to your renderer, untouched and unknown.

That's OK, but, if I make a kind of library that exposes a "memory image" (char buffer) the user must load, and it uses internally ImGui::Image(...)/ImGui::ImageButton(...), then I have to choose an unique uv convention: I'm going to use the Direct3D one then.

> The difficulty with adding an image to the sample it that it would require every sample to load/upload the texture. 

I know, you're right.

**Comment by ocornut** [comment]
Thanks :)

This lack of image in the demo has been niggling me for a while. When we end up adding an API to register custom zones/images into the font atlas (which the mouse cursors will be able to use instead of hardcoding them) then it'd be more easy to add a function in imgui_demo.cpp and include a simple embedded image for the purpose of the demo.
