### ISSUE TITLE
ImGui not linking, can't even IMGUI_CHECKVERSION();

### ISSUE THREAD

**Issue by carlosdr02** [ocornut/imgui#4585]
### Discussed in https://github.com/ocornut/imgui/discussions/4584

<div type='discussions-op-text'>

<sup>Originally posted by **carlosdr02** September 25, 2021</sup>
I've just downloaded ImGui and included it in my Visual Studio project by Properties > C/C++ > General > Additional Include Directories, and the header files are added correctly, but seems like .cpp file aren't. I get the following error when trying to `IMGUI_CHECKVERSION();`:

`application.obj : error LNK2019: unresolved external symbol "bool __cdecl ImGui::DebugCheckVersionAndDataLayout(char const *,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64)" (?DebugCheckVersionAndDataLayout@ImGui@@YA_NPEBD_K11111@Z) referenced in function "public: __cdecl Application::Application(void)" (??0Application@@QEAA@XZ)`

It's about the function `ImGui::DebugCheckVersionAndDataLayout()`, which is what `IMGUI_CHECKVERSION()` calls. 

I have tried other ways of including the library, like just dragging the files into the folder where all my source code is, still not working. Any ideas?

Thx.</div>

**Comment by ocornut** [comment]
This is not an issue. Please don’t open duplicates. I answered in discussions.
