### ISSUE TITLE
proper way to initialize seperate ImDrawlists

### ISSUE THREAD

**Issue by ntsleeper** [ocornut/imgui#4586]
**Version/Branch of Dear ImGui:**

Version: dear imgui, v1.85 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_d3d11.cpp + imgui_impl_d3d11.cpp _(or specify if using a custom engine/back-end)_
Compiler: MSVC 2019
Operating System: Windows

**My Issue/Question:**

I am trying to figure out the proper way to initialize my own ImDrawlists for storing draw commands in a multithreaded manner.

**Screenshots/Video**
![download (6)](https://user-images.githubusercontent.com/70115728/134813224-a41f5f42-bbca-450d-a067-6624b32e9cc6.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
ImDrawList* custom_drawlist = new ImDrawList(ImGui::GetDrawListSharedData());
custom_drawlist->AddCircleFilled(ImVec2(200, 200), 200, IM_COL32(255, 0, 0, 255));
```

**Comment by ocornut** [comment]
You need to call `draw_list->_ResetForNewFrame()` then `draw_list->PushTextureID(font_atlas->GetTexID())` at least.

**Comment by ocornut** [comment]
For the record I have posted an example here:
https://github.com/ocornut/imgui/issues/6406#issuecomment-1563002902

I will aim to make this simpler.
