### ISSUE TITLE
Iam implement D3D8 but menu isnt shown

### ISSUE THREAD

**Issue by budibeta** [ocornut/imgui#4599]
we know that, D3D8 and D3D9 is similar function, not so different

 i was change **imgui_impl_dx9.h** and **imgui_impl_dx9.cpp** source to D3D8, and wowrking well
iam also change **main.cpp** source to D3D8 and working well

no code error

but no IMGUI show
![Screenshot_2](https://user-images.githubusercontent.com/68463485/135330066-e54bad10-6cd5-490e-9976-bbae5955a98d.jpg)
n

i was enable the demo window

![Screenshot_3](https://user-images.githubusercontent.com/68463485/135330621-7c78e73f-097e-4ce2-92d9-21648d0f43fc.jpg)
its only blank gui

hey dont judge me as beginner, i was experienced iin 5 years
iam no stupid (wrong typing declaration),
 i was change LPDIRECT3D8 to LPDIRECT3D9 , also another function

but why its not working

ofcourse its x86 version, because D3D8 isnt available in x64

**Comment by ocornut** [comment]
I'm sorry but we can't help you debug code you have written especially if you don't publish the code.
This is a DX8 question not much of a dear imgui question.
Feel free to share your code and other people may be tempted to help.
