### ISSUE TITLE
The problem with the indentation of table elements

### ISSUE THREAD

**Issue by NePutin94** [ocornut/imgui#4600]
I am using imgui 1.84.2. I want to arrange the elements in the form of a matrix and use a table for this, but a strange indentation appears there from somewhere. 
```C++
  if (ImGui::BeginTable("##table2", varCount + 2))
            {
                for (int row = 0; row < resCount; row++)
                {
                    ImGui::PushID(row);
                    ImGui::TableNextRow();
                    for (int column = 0; column < varCount; column++)
                    {
                        ImGui::TableNextColumn();
                        std::string label = "x" + std::to_string(column + 1);
                        ImGui::DragInt(label.c_str(), &val, 1, 0, 5);
                    }
                    ImGui::TableNextColumn();
                    if (ImGui::Button(signToStr(sign).c_str()))
                        ImGui::OpenPopup("sign_popup");
                    if (ImGui::BeginPopup("sign_popup"))
                    {
                        for (int i = 0; i < 3; i++)
                            if (ImGui::Selectable(signToStr((_sign)i).c_str()))
                                sign = (_sign)i;
                        ImGui::EndPopup();
                    }
                    ImGui::TableNextColumn();
                    ImGui::DragInt("Value", &val, 1, 0, 5);
                    ImGui::PopID();
                }
                ImGui::EndTable();
            }
```
![изображение](https://user-images.githubusercontent.com/25349002/135356202-bad688f7-5d34-418b-8552-0eadd2f6a81a.png)
If I use ```ImGui::Selectable``` here, then it can be seen that it is somehow strangely stretched here
![изображение](https://user-images.githubusercontent.com/25349002/135356525-83be103f-88ae-4745-a75a-82708f86b3b4.png)
Maybe it's because I use elements of different types? But then why doesn't he place the button or the selectable in the center or does not set the button size as the cell size?

**Comment by ocornut** [comment]
Note that using "Best Fit" policy is incompatible with using `SetNextItemWidth(-FLT_MIN)` to have a widget fill a column, since it becomes a chicken and egg problem. You can have your widget be a fixed width (e.g. `SetNextItemWidth(200)`) and then Fitting columns can work, or you can have column width independent of their contents and then have the contents be fit to the column.

**Comment by NePutin94** [comment]
Ok, ```ImGuiTableFlags_SizingStretchProp``` helped in my case, thanks
