### ISSUE TITLE
Default button(s) behaviors

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#461]
Hi,

Is there a "default" buttons behavior system we can use with ImGui ?

By example :

Press enter => OK
Press escape => Cancel

It is something we find on QT etc ...

**Comment by ocornut** [comment]
No there isn't. That you require specifying what is the default button, at this point isn't harder to check keyboard input yourself (along with perhaps checking if the window is focus).

**Comment by krys-spectralpixel** [comment]
Ok thanks
