### ISSUE TITLE
How to render "texts with textures" and "lines/rectangles without textures" in one "draw command"?

### ISSUE THREAD

**Issue by manda3dprojects** [ocornut/imgui#4620]
**Version/Branch of Dear ImGui:**

Version: v1.84
Branch: 

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_vulkan.cpp + imgui_impl_vulkan.cpp
Compiler: Visual Studio 2015
Operating System: Windows 10

**My Issue/Question:**
How did you do to render "texts with textures" and "lines/rectangles without textures" in one "draw command"?

Each edge of a rectangle has 6 indices. so 4 * 6 = 24 indices for a rectangle.
There are 4 rectangles, so 4 * 24 = 96 indices for all the rectagles.
There is a font text "A" with 6 indices, so there are total of 96+6=102 indices.

![buffers](https://i.imgur.com/DO7kVKb.jpg)
Note that in the image above, I forced render the rectangles by checking if their uv is equal to (0,0) so they don't use texture.

**The exact shader source code (ui.frag) of the render above:**
```
#version 450

layout (binding = 1) uniform sampler2D samplerColor;

// in
layout (location = 0) in vec2 in_uv;
layout (location = 1) in vec4 in_color;

// out
layout (location = 0) out vec4 outFragColor;

void main() 
{
    vec4 font = vec4(1, 1, 1, 1);
    if (in_uv.x != 0 || in_uv.y != 0) { // Note that this code is very complex, I don't know how did you do to render the rectangles/lines without this checking if uv is not equal to (0,0) for "Texts".
        font = texture(samplerColor, in_uv);
    }
    outFragColor = in_color * font;
}
```

**The official shader source code by imgui (. . . . .\vulkan_imgui\imgui_backend\vulkan\glsl_shader.frag)**
```
#version 450 core
layout(location = 0) out vec4 fColor;

layout(set=0, binding=0) uniform sampler2D sTexture;

layout(location = 0) in struct {
    vec4 Color;
    vec2 UV;
} In;

void main()
{
    fColor = In.Color * texture(sTexture, In.UV.st);
}
```
See, your shader source code is very simple, but when I do like that then the rectangles don't display because their uv is (0,0) and alpha=0 (check the point at the top left of the font atlas texture).

**Comment by manda3dprojects** [comment]
I cannot delete the thread, but I think I will use the following functions:
```
ImVector<ImTextureID>   _TextureIdStack;    // [Internal]

IMGUI_API void  PushTextureID(ImTextureID texture_id);
IMGUI_API void  PopTextureID();
```

**Comment by manda3dprojects** [comment]
I profit of this thread, and I found a bug.

```
// Initialize all Vulkan resources used by the ui
void initResources(VkRenderPass renderPass, VkQueue copyQueue, const std::string& shadersPath)
{
    ImGuiIO& io = ImGui::GetIO();
    g_fonts.push_back(io.Fonts->AddFontFromFileTTF("arial.ttf", 14.0f));
    g_fonts.push_back(io.Fonts->AddFontFromFileTTF("arial.ttf", 24.0f));

    ...

    // DEBUG
    {
        uint8_t *fontData_0;
        uint8_t *fontData_1;
        int width_0, height_0;
        int width_1, height_1;
        g_fonts[0]->ContainerAtlas->GetTexDataAsRGBA32(&fontData_0, &width_0, &height_0);
        g_fonts[1]->ContainerAtlas->GetTexDataAsRGBA32(&fontData_1, &width_1, &height_1);

        // width_0 = 512, height_0 = 512 <-- This is wrong, it must be 512 and 128
        // width_1 = 512, height_1 = 512
    }
}
```

If I only use arial with size 14.0 then width_0 height_0 are 512, 128

**Comment by PathogenDavid** [comment]
The Dear ImGui font atlas texture always has a 2x2 square of white pixels. The UV of the middle of the top-left pixel of that sqaure is what is used when shapes are drawn with `ImDrawList`.

You can access it via `ImGui::GetFont()->ContainerAtlas->TexUvWhitePixel`.

**Comment by manda3dprojects** [comment]
Thanks, and let me tell that my answer above your post is in wrong direction because I was trying to render multiple draw commands, but it's much better to render one single draw command with one texture.
