### ISSUE TITLE
Iframe browser in imgui opengl 3

### ISSUE THREAD

**Issue by AndroTwrpid** [ocornut/imgui#4623]
Just a question, is possible to add an iframe browser to a opengl 3 imgui project?

**Comment by AidanSun05** [comment]
If you're looking to display HTML (which is what I believe you meant by "iframe browser"), check out #2782 and #4257 which both discuss this topic. (https://github.com/ocornut/imgui/issues/4257#issuecomment-866970102 has some additional relevant links.)

There's no built-in support for this; you'll have to use an external renderer like CEF or litehtml to process the HTML page into something that Dear ImGui can understand (like an OpenGL texture). You can then render this inside a Dear ImGui window.
