### ISSUE TITLE
Disable ViewPort feature for a specific window

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#4624]
**Version/Branch of Dear ImGui:**

Version: 1.85
Branch: viewport/docking

**My Issue/Question:**

Is there a possibility to disable the viewport feature for a particular window.
i would like to prevent some popup or menu to be outside of the main windows.
would like to have these windows like if no viewport feature is enabled

**Screenshots/Video**

![AKRsBIy12V](https://user-images.githubusercontent.com/1434736/135775374-191c8d34-c282-4716-95c1-54aedefe7b1a.gif)

**Comment by PathogenDavid** [comment]
If you manually set the window's viewport to the main viewport, it will not let it create its own:

```cpp
ImGui::SetNextWindowViewport(ImGui::GetMainViewport()->ID);
```

**Comment by aiekick** [comment]
i was searching a very complex solution. this one is so simple haha :)

thanks you very mush. work like a charm.

**Comment by mwindowshz** [comment]
> If you manually set the window's viewport to the main viewport, it will not let it create its own:
> 
> ```c++
> ImGui::SetNextWindowViewport(ImGui::GetMainViewport()->ID);
> ```

Hi
Is there the opposite option?
All windows will be in main viewport, on the actual window, and some selected windows will be floating outside in their own viewport.
So for example main application GUI stays all in main window, but when opening some advance config window it will be floating outside 

Thanks

**Comment by PathogenDavid** [comment]
@mwindowshz

I don't think there's a simple way to do that beyond calling `SetNextWindowViewport` for most of your windows.
