### ISSUE TITLE
Seg Faults with xmake installation 

### ISSUE THREAD

**Issue by Kbz-8** [ocornut/imgui#4625]
Version/Branch of Dear ImGui:

Version: 1.84.2
Branch: I don't know, it was installed by xmake. I think it installs it from the releases.
This is where xmake get ImGui : https://github.com/xmake-io/xmake-repo/blob/master/packages/i/imgui/xmake.lua

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_vulkan.cpp + imgui_impl_sdl.cpp
Compiler: GCC 9.3
Operating System: linux Kubuntu x86_64

My Issue/Question:

I just switched the compilation of my game engine from premake5 to xmake (for dependency management like ImGui), the compilation works fine but I have seg faults that appeared in some functions: 
 - ImGui::GetMainViewport() in ImGui::BeginMainMenuBar()
 - ImGui::PushStyleVar()
 - ImGui::FindWindowByName() in ImGui::Begin()
and I didn't push it further because I have a feeling it won't stop...

With premake5 I made a git clone of the main branch and compiled it with premake. Now xmake is in charge of compiling ImGui, that's the only thing that has changed.

Standalone, minimal, complete and verifiable example:
```C++
ImGui::PushStyleVar(ImGuiStyleVar_Alpha, 1.0f);
if(!ImGui::Begin("Console", nullptr, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar))
{
        ImGui::PopStyleVar();
        ImGui::End();
        std::cout << "error with ImGui::begin()" << std::endl;
        return;
}
ImGui::PopStyleVar();
```
If someone could help me it would be a great help because I have no idea how to solve this.

**Comment by Kbz-8** [comment]
Firstly, thank you for the correction on the error message. 
Secondly, if you're talking about the includes in libs/include, it's the copied includes from the xmake repo so it's the same, it's temporary I'll change it quickly.

I will continue my research and come back to you if I find any answers so that other people don't have the same problem (if it's an ImGui problem, otherwise I will report it to xmake if it comes from them).

**Comment by ocornut** [comment]
This is most likely not a Dear ImGui issue yet people are happy to help you. But as mentioned by issue guidelines, if you get a crash or assert you should share details and callstack otherwise it is a pointless statement to make and people are not going to be able to help.
