### ISSUE TITLE
Append text to InputTextMultiline

### ISSUE THREAD

**Issue by AndroTwrpid** [ocornut/imgui#4627]
Hello, is possible to append data to InputTextMultiline?
I'm new to imgui

**Comment by rokups** [comment]
Append text to a buffer InputTextMultiline() uses. New text will show up if widget is inactive.

Also please follow issue template. It is there for a reason, and that reason is not to be ignored.

**Comment by ocornut** [comment]
Closing as duplicate of #3878, #2881
This is an open problem.
