### ISSUE TITLE
Memory leak loading OpenGL texture in to ImGui::Image()

### ISSUE THREAD

**Issue by jakerieger** [ocornut/imgui#4628]
**Version/Branch of Dear ImGui:**

Version: 1.85
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.h.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC 2019
Operating System: Windows 10

**My Issue/Question:**
I have an inspector panel on the right that will show properties based on the type of content selected. For textures, it'll just show a preview of the texture using `ImGui::Image()`. When I click on a texture, my memory usage shoots up and climbs until I run out of memory. If I selected something else removing the image preview, the memory isn't released. The FPS also drops **significantly** any time an image preview is being shown (from 1100+ FPS down to <40 FPS).

**Screenshots/Video**
https://user-images.githubusercontent.com/19679090/135903515-d2af99a0-5510-4ad4-b296-e1addd6071da.mp4

The function that loads the image from a file and creates the texture (straight from the ImGui docs):
```c++
bool LSUtilities::LoadTextureFromFile(const char* filename, GLuint* out_texture, int* out_width, int* out_height) {
	int image_width = 0;
	int image_height = 0;
	unsigned char* image_data = stbi_load(filename, &image_width, &image_height, NULL, 4);
	if (image_data == NULL)
		return false;

	GLuint image_texture;
	glGenTextures(1, &image_texture);
	glBindTexture(GL_TEXTURE_2D, image_texture);

	// Setup filtering parameters for display
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

	// Upload pixels into texture
#if defined(GL_UNPACK_ROW_LENGTH) && !defined(__EMSCRIPTEN__)
	glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
#endif
	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data);
	stbi_image_free(image_data);

	*out_texture = image_texture;
	*out_width = image_width;
	*out_height = image_height;

	glBindTexture(GL_TEXTURE_2D, 0);

	return true;
}
```

The code that uses this function to create the image preview (**this is inside the render loop**):
```c++
  int texture_preview_width = 0;
  int texture_preview_height = 0;
  GLuint texture_preview = 0;
  bool ret = LSUtilities::LoadTextureFromFile(Resources.textures[selectedItemID].c_str(), &texture_preview, &texture_preview_width, &texture_preview_height);
  IM_ASSERT(ret);

  ImVec2 previewSize = {
    ImGui::GetContentRegionAvailWidth(),
    (texture_preview_height * ImGui::GetContentRegionAvailWidth()) / texture_preview_width
  };

  ImGui::Image((ImTextureID)texture_preview, previewSize);
```

I've tried deleting the texture with `glDeleteTextures(1, &texture_preview)`  after the `ImGui::Image` call but the code above is inside the render loop and that appears to just delete the texture before ImGui can load it.

**Comment by mnesarco** [comment]
You should load the texture from outside the main loop (during init or by demand later), save the textureId somewhere and render it in mainloop. 

If you create the texture again and again on each frame you are exhausting the memory, and ImGUI defer all drawings to the end of the Frame so you must not delete the texture inside the mainloop before ImGui renders.

**Comment by jakerieger** [comment]
That's the problem, I don't know what image to load until the user selects one, and the check for that is done inside the render loop. Any function call I make when the user selects an image will be inside the render loop.

**Comment by mnesarco** [comment]
You can load the image in the render loop once the user provides the path and cache the textureId, so next frames use the already loaded texture. But you must no load it in every frame.

**Comment by jakerieger** [comment]
If I load it in the render loop and cache the ID, then I'm still loading it every frame. Are you saying to not call the OpenGL functions every frame or the STB functions every frame?

**Comment by mnesarco** [comment]
Cache means saving something for later reuse.

**Pseudo** code:
```
// Out of mainloop
textureId_cache = 0
selected_cache = default or null

// Main Loop
begin:

    // Get user input
    selected = get_user_selection(...)

    // Check if image selection has actually changed (by the euser) and update cache ONLY in that case
    if selected != selected_cache:
        selected_cache = selected
        textureId_cache = load_texture_from_disk(selected_cache)

    // render the cached texture if any
    if textureId_cache:
        render_texture(textureId_cache)

loop
```

There is no problem calling opengl from mainloop, the problem is to load the texture each time.

PS: In realworld applications you should load your assets in a different thread for optimal performance anyway.

**Comment by jakerieger** [comment]
I think I sorted it. I moved the following code to outside the main loop:

```c++
GLuint texture_preview;

glGenTextures(1, &texture_preview);
glBindTexture(GL_TEXTURE_2D, texture_preview);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
```

and then in the mainloop:

```c++
  int image_width = 0;
  int image_height = 0;
  unsigned char* image_data = stbi_load(Resources.textures[selectedItemID].c_str(), &image_width, &image_height, NULL, 4);
  glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data);
  stbi_image_free(image_data);

  ImVec2 previewSize = {
    ImGui::GetContentRegionAvailWidth(),
    (image_height * ImGui::GetContentRegionAvailWidth()) / image_width
  };

  ImGui::Image((ImTextureID)texture_preview, previewSize);
```

I then unbind and delete at the end outside the render loop. Fixes the memory leak.

**Comment by mnesarco** [comment]
You are now reusing the texture so no memory waste, but you are loading and copying the image data into texture in every frame. Now your are still wasting IO and CPU.

**Comment by jakerieger** [comment]
How would I defer the `stbi_load` call to outside the main loop if it needs a path?

**Comment by mnesarco** [comment]
> How would I defer the `stbi_load` call to outside the main loop if it needs a path?

https://github.com/ocornut/imgui/issues/4628#issuecomment-933833266

This will not put it outside the mainloop which is not required, but it will use it only as needed, without unnecessary reloading. To move it out of the mainloop you need another thread. But you can leave it single threaded by now, this is really basic stuff.

**Comment by jakerieger** [comment]
Fixed. FPS stays consistent now. I know what a cache is and what your code does. For some reason I was interpreting your code wrong. Thanks for the help, will look at implementing multithreading soon as that seems like the obvious solution and one I didn't consider for some reason.
