### ISSUE TITLE
sdl2 opengl3 example build error

### ISSUE THREAD

**Issue by edselmalasig** [ocornut/imgui#463]
1 warning generated.
Undefined symbols for architecture x86_64:
  "_CFBundleCreate", referenced from:
      open_libgl() in gl3w-d9977c.o
  "_CFBundleGetFunctionPointerForName", referenced from:
      get_proc(char const*) in gl3w-d9977c.o
  "_CFRelease", referenced from:
      close_libgl() in gl3w-d9977c.o
      get_proc(char const*) in gl3w-d9977c.o
  "_CFStringCreateWithCString", referenced from:
      get_proc(char const*) in gl3w-d9977c.o
  "_CFURLCreateWithFileSystemPath", referenced from:
      open_libgl() in gl3w-d9977c.o
  "___CFConstantStringClassReference", referenced from:
      CFString in gl3w-d9977c.o
  "_kCFAllocatorDefault", referenced from:
      open_libgl() in gl3w-d9977c.o
      get_proc(char const*) in gl3w-d9977c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
kilopopos-MBP-4:sdl_opengl3_example kilopopo$ g++ main.cpp imgui_impl_sdl_gl3.cpp ../../imgui*.cpp ~/Desktop/gl3w-master/src/gl3w.c -I ../.. -I /usr/local/include/SDL2/ -I ~/Desktop/gl3w-master/include/ `sdl2-config --§libs gl3w` -L ~/Desktop/gl3w-master/ -lgl3w  -lSDL2 -framework OpenGl -ldl -o sdl2example

How do i compile it properly

**Comment by ocornut** [comment]
Which operating system / compiler?
Have you looked for your problem on Google?

**Comment by ocornut** [comment]
Does the SDL2 OpenGL2 example work?
Try adding `-framework CoreFoundation` to your command-line and see if it makes a difference.

**Comment by edselmalasig** [comment]
hmmm i added the flag and it compiled but the problem now is it shows black screen without ui.

Can you help

**Comment by ocornut** [comment]
Does the SDL2 OpenGL2 example works for you?

I don't have a mac to test.

**Comment by edselmalasig** [comment]
yes it does

**Comment by ocornut** [comment]
Try messing with SDL_GL_CONTEXT_MAJOR_VERSION and SDL_GL_CONTEXT_MINOR_VERSION, setting them both to 3 and 3.

**Comment by edselmalasig** [comment]
I tried it it did not work and it still renders a blank screen

**Comment by edselmalasig** [comment]
is it possible that you are not including Opengl3.h headers

**Comment by ocornut** [comment]
Try to add
`SDL_GL_SetAttribute (SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG);`

**Comment by edselmalasig** [comment]
nope it doesnt work unfortunately

ill move on to glfw3

**Comment by ocornut** [comment]
Perhaps you could try comparing with a SDL2 sample that shows how to use modern OpenGL and see if it works on your Mac.

**Comment by edselmalasig** [comment]
yes

**Comment by ocornut** [comment]
You're welcome :)

**Comment by Cthutu** [comment]
I came late to the party but the OP is not linking with Core Foundation on
the Mac.  So if anyone else has the same issue that's your problem.

**Comment by ocornut** [comment]
@edselmalasig Code should be fixed now.
