### ISSUE TITLE
Debug tools: new "Stack Tool" window, ShowStackToolWindow()

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#4631]
## Introducing the stack tool

_(We've been using this internally as part of the unreleased automation feature but recently managed to redesign in a way allowing us to move it to the main library while not incurring significant cost.)_

The tool run queries on hovered id to display details about individual components that were hashed to create an ID. 
It helps both understanding the [ID stack system](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it) and debugging potential ID collisions.

![stack_tool_03b](https://user-images.githubusercontent.com/8225057/136235637-6d87c2b2-0afd-46b7-ac12-7d329068bea7.png)

![stack_tool_03](https://user-images.githubusercontent.com/8225057/136235657-a0ea5665-dcd1-423f-9be6-dc3f8ced8f12.png)

**Comment by ocornut** [comment]
Closing as this is now on Wiki and linked from many places:
https://github.com/ocornut/imgui/wiki/Debug-Tools

**Comment by cfillion** [comment]
"ID" is uppercase in other functions and types in the public API (ImGuiID, ImGuiTextureID, PushID, PopID, GetID, GetItemID, GetWindowDockID, SetNextWindowDockID, PushTextureID etc... exceptions being enums and some struct members). 

Shouldn't it be called `ShowIDStackToolWindow` for consistency?

**Comment by ocornut** [comment]
You are right. I have pushed this change as c21278e.
