### ISSUE TITLE
How to update only all UV(s) of texts in all drawlist(s) after fonts change?

### ISSUE THREAD

**Issue by mandaxyzw** [ocornut/imgui#4637]
**Version/Branch of Dear ImGui:**

Version: v1.84
Branch:

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_vulkan.cpp
Compiler: Visual Studio 2015
Operating System: Windows 10

**My Issue/Question:**
How to update only all UV(s) of texts in all drawlist(s) after fonts change?

I want to build a big project using dynamic fonts like resizing fonts at any time, for example zooming a node editor containing texts. And when I do that, the fonts list will be change a lot then all the other texts that are already drawn become expired.

**The texture of the font atlas (before / after)**
![texture](https://i.imgur.com/bZT0J7W.jpg)

**Imagery explanation of the problem which is just a theory image but not a real screenshot**
![Zoom](https://i.imgur.com/HmnHjSX.jpg)
The reason of the glitch in the image above: The texts on the right are already drawn in the beginning with old UV(s)'s locations, but when there is a new added font, then those UV(s) become expired because all texture atlases are packed into one texture, and only the new added font's UV(s) are updated to the latest UV(s).

The reason it's important for me to ask the question is it's a big decision for the entire project on UI, because if I don't ask the question then when there's a fonts change, I will re-draw all drawlist(s) including drawlist(s) that don't literally need update.

So, does updating only UV(s) of texts in all drawlist(s) exist? Or how to fix my issue? Thanks.

**Comment by ocornut** [comment]
FYI here is the ongoing work on `dynamic_fonts` branch toward 1.92: https://github.com/ocornut/imgui/issues/8465.

I have tried the approach of remapping UV mid-frames. It mostly works but gets tricky and error-prone when dealing with CPU-clipped glyphs. It did not seem like a good idea to have such fragile and CPU intensive code relegated to a rarely executed path. We still have a bunch of rarely exercised paths but they are more in line with code that's used normally.

https://github.com/user-attachments/assets/edf257b8-8433-456d-a2e0-5202713dead2
