### ISSUE TITLE
Question : modal window & other controls

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#464]
Hi,

I have notice that when a modal window is opened, the other controls are disabled and change their styles.

So, I have my owns controls and would like to apply the same rules... is there some helpers functions for that ? Or just let me know what I have to do exactly ?

Thanks

**Comment by ocornut** [comment]
> the other controls are disabled and change their styles.
> 

The other Windows are disabled, not controls. There's no change of style, just a transparent quad drawn behind the top-level modal window. That's all it does and it is tied to a modal window being in the stack.

**Comment by krys-spectralpixel** [comment]
Thanks,

But by example when the mouse hover a button, the "hovering" button is no more displayed !

With my control, it still detect the mouse movements !! Is it normal ? Is there something special to do ?

**Comment by ocornut** [comment]
I don't understand what your second sentence means.

You may want to look around the `IsWindowContentHoverable` function.

**Comment by krys-spectralpixel** [comment]
Perfect, it is what I need :-)

Thanks
