### ISSUE TITLE
ColorPicker width problem.

### ISSUE THREAD

**Issue by urjskhzk** [ocornut/imgui#4641]
**Version/Branch of Dear ImGui:**

Version: 1.84.2
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: win32 dx9
Compiler: vs2019
Operating System: Windows 10

**My Issue/Question:**

```
static float color[3] = { 0, 0, 0 };
ImGui::Begin("Hello, world!");
ImGui::SetNextItemWidth(-FLT_MIN);
ImGui::ColorPicker3("ColorPicker3", (float*)&color);
ImGui::End();
```

![1](https://user-images.githubusercontent.com/36331749/136931881-1a50aeb1-2960-450b-8ee9-ca28591d859f.gif)

**Screenshots/Video**

**Standalone, minimal, complete and verifiable example:**

**Comment by ocornut** [comment]
I'll close this as I don't have a better answer now.
