### ISSUE TITLE
Possibility to resurrect ConfigDockingWithShift?

### ISSUE THREAD

**Issue by sivu** [ocornut/imgui#4643]
I was updating to a latest version of ImGui and was horrified to find that ImGuiIO::ConfigDockingWithShift has been removed some time ago.

Would it be possible to get the behaviour back? I would rather have it as configuration flag as before instead of having to hack imgui behaviour to match after each update.

The reason is that we initially tried to use the default docking behaviour, but our users kept messing their window layouts because of accidental docking. Holding shift when docking was a real saver and the users are happy.

**Comment by ocornut** [comment]
Resurrected the option with 29653273c1c6cec453be68d9cbe625f5d5c69fe8 !

**Comment by mnesarco** [comment]
Hi @ocornut , today I upgraded to 1.87-docking, an apparently ConfigDockingWithShift was removed again.

```
[build] /home/xxx/app/ApplicationWindow_ImGui.cpp:38:8: error: no member named 'ConfigDockingWithShift' in 'ImGuiIO'
[build]     io.ConfigDockingWithShift = true;
[build]     ~~ ^
[build] 1 error generated.
```
