### ISSUE TITLE
TreeNodes/TreeView -> Scroll to make a node visible

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#465]
Hi,

It is a feature that exists in other UI framework and I would like to know the best way to acheive it with ImGui.

I'm looking for a way to "insure" that a specific tree node is visible, by setting the window scroll bar at the right place.

How can I do that please ?

**Comment by ocornut** [comment]
Are you running the demo code `ShowTestWindow()` to see what it is showing you?

**Comment by krys-spectralpixel** [comment]
Yes I have ! Why ?

**Comment by ocornut** [comment]
Because you'll find the answer there!

**Comment by krys-spectralpixel** [comment]
Ok. Thanks...

**Comment by timbeaudet** [comment]
FWIW, could we just put the answer here for future people searching? Especially since I'm now stuck looking through the demo window, so that I can then go look up in the code example?
