### ISSUE TITLE
example_emscripten_wgpu not rendering / black screen

### ISSUE THREAD

**Issue by eliam** [ocornut/imgui#4650]
Hi,

I was really excited to find imgui and emscripten however I seem to be falling at the first hurdle.  I'm trying the example (example_emscripten_wgpu) as is and everything compiles and runs but all I get in the browser is a black screen. 

successful build:
![image](https://user-images.githubusercontent.com/1518180/137223885-924cfd45-6f51-4417-83f5-3a260de2f911.png)

git log (current version from gitlab)
![image](https://user-images.githubusercontent.com/1518180/137223541-4bb48cc4-c7a5-4fad-930e-ba6ac9a2607d.png)

FYI, emscripten environment seems sane / working:
![image](https://user-images.githubusercontent.com/1518180/137224167-3d3a649c-91fa-4bae-a7ab-98965acb77d0.png)

Here's what I see in the browser:
![image](https://user-images.githubusercontent.com/1518180/137224394-f29971d6-8a12-44c1-8232-7805300f9cda.png)

Any hints / tips appreciated!

**Comment by ocornut** [comment]
Are you using a browser that supports wgpu and which has it enabled?

**Comment by ocornut** [comment]
WGPU has been such a moving api lately (with recent patches by contributors to catch up) that I would presume you need nightly.

**Comment by eliam** [comment]
Hi, thanks. :)  I'd googled this based on your earlier reply and found this page: https://hacks.mozilla.org/2020/04/experimental-webgpu-in-firefox/.  The config items were available in my FF but I'm going to assume nightly too.  I'm looking for something which would work in the browser for others, without needing to get custom versions to set config items so it seemed sensible to switch to the other example and start trying to understand that instead.

Any idea why the opengl example might work in edge but not firefox?  It's the same blank screen and no hints / errors in the browser console window.  Looks like everything 'should' be working so I'm still puzzled.

**Comment by eliam** [comment]
Yey, I've tracked it down.  Turns out, firefox doesn't support gamepads over untrusted connections (http).

-----------
Starting with Firefox 81, the Gamepad API will be restricted to what are known as “ secure contexts ” (bug 1591329). Basically, this means that Gamepad API will only work on sites served as “https://”. But don’t worry, it also works on http://localhost too while you are debugging!
-----------

I'm using v93.0 and that seems to die during the load.  You can see if in the console as "Error: Gamepads not supported".

Using https instead of http worked fine in Firefox.

A simple and dirty (python2) way of bringing up a https endpoint instead of http is in this gist: https://gist.github.com/dergachev/7028596

**Comment by eliam** [comment]
https://github.com/ocornut/imgui/pull/4662

**Comment by TheGreatRambler** [comment]
Is there a way to entirely disable gamepads so I can host my program on http? I have an https server but just so it's easier for others to host.
