### ISSUE TITLE
Draw image on the window background with overlay

### ISSUE THREAD

**Issue by csabakeszegh** [ocornut/imgui#466]
I'd like to use ImGui to draw polygons, lines and text over an image. In my solution I call `ImGui::GetCursorScreenPos()` before the `ImGui::Image`. I offset the primitive's coordinates to get window coordinates, which I can use with the DrawList API `ImGui::GetWindowDrawList()`. I'm wondering that is it possible to use DrawList API in a particular widget coordinate system?

What is the recommended way use ImGui to draw the window background, so the ImGui window matches the framebuffer size, and uses no ImGui decoration. I use `ImGuiWindowFlags` with `ImGui::Begin` but still have a few pixel shake when scrolling with the mouse.

Thanks in advance.

**Comment by ocornut** [comment]
All coordinates in the DrawList API are screen/display coordinates. You can't request the DrawList API to offset things for you, it is a rather low-level API and doesn't even know about your window or widgets.

(Mildly related but when it comes to offseting positions it may be a little annoying if you don't have a + operator defined. You can use the `IM_VEC2_CLASS_EXTRA` define in imconfig.h to define cast operators between ImVec2 and your own maths types to benefits from maths operators that you likely have defined in your engine, or define `IMGUI_DEFINE_MATH_OPERATORS` and include imgui_internal.h to use ImGui's own math operators.)

> What is the recommended way use ImGui to draw the window background, so the ImGui window matches the framebuffer size, and uses no ImGui decoration. I use ImGuiWindowFlags with ImGui::Begin but still have a few pixel shake when scrolling with the mouse.

You may use something like
```
ImGui::SetNextWindowPos(ImVec2(0,0));
ImGui::SetNextWindowSize(ImGui::GetIO().DisplaySize);
ImGui::Begin("foobar", NULL, ImVec2(0,0), 0.0f, ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoResize|ImGuiWindowFlags_NoMove|ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoScrollWithMouse);
```

Note: passing 0.0f background alpha +`ImGuiWindowFlags_NoScrollWithMouse` to disable mouse scrolling. You might also use `ImGuiWindowFlags_NoBringToFrontOnFocus` depending on what you are doing?

Note if you only really want an ImDrawList and not use any of the ImGui::widgets you may allocate one yourself and use that API and render it yourself.

**Comment by csabakeszegh** [comment]
Thank you for the quick reply and comments.
