### ISSUE TITLE
How to setup the mouse handler or mouse event of ImGui background? (use io.WantCaptureMouse)

### ISSUE THREAD

**Issue by mandaxyzw** [ocornut/imgui#4664]
**Version/Branch of Dear ImGui:**
Version: v1.84

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_sdl.cpp + imgui_impl_vulkan.cpp
Compiler: Visual Studio 2015
Operating System: Windows 10

**My Issue/Question:**
The real question is at the bottom of this paragraph. But the cause the issue is I use the code below:
```
ivec2 mousePos;
uint32_t mouseButtons = SDL_GetMouseState(&mousePos.x, &mousePos.y); // This causes the issue
io.MousePos = ImVec2(mousePos.x, mousePos.y);
io.MouseDown[0] = ((mouseButtons & SDL_BUTTON_LMASK) != 0);
io.MouseDown[1] = ((mouseButtons & SDL_BUTTON_MMASK) != 0);
io.MouseDown[2] = ((mouseButtons & SDL_BUTTON_RMASK) != 0);
g_window->modal_base(&io); // Calling the function of my project at the bottom.
```

![mouse](https://user-images.githubusercontent.com/26832285/137868410-42fae1b8-c6be-476d-a363-46cd364c4dc5.gif)

Code I read somewhere:
```
ImGuiIO& io = ImGui::GetIO();
io.WantCaptureMouse = true;
```

The code below is from: https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application
```
void MyLowLevelMouseButtonHandler(int button, bool down)
{
    // (1) ALWAYS forward mouse data to ImGui! This is automatic with default backends. With your own backend:
    ImGuiIO& io = ImGui::GetIO();
    io.MouseDown[button] = down;

    // (2) ONLY forward mouse data to your underlying app/game.
    if (!io.WantCaptureMouse)
        my_game->HandleMouseData(...);
}
```

My question is how to make the function MyLowLevelMouseButtonHandler to be the ImGui background mouse handler? Background means that there should not be mouse event on any ImGui window (see the red [error] in the Video Gif), except if the mouse clicks drag on the background and hovers above an ImGui window. I tried to read the documentation in the link but it doesn't talk about how setup the mouse handler.
___________________________________________________________________________________________

**Advanced details of my project**

```
struct ModalEvent
{
    vec2            mousePos; // Mouse position, in pixels. Set to vec2(-INFINITY, -INFINITY) if mouse is unavailable (on another screen, etc.)
    ModalEventType  type; // MODALEVENTTYPE_NONE, ..._LEFTMOUSE, ..._MIDDLEMOUSE, ..._RIGHTMOUSE, ..._MOUSEMOVE
    ModalEventValue value; // MODALEVENTVALUE_ANY, ...PRESS, ..._RELEASE, ..._CLICK, ..._DOUBLECLICK, ..._CLICKDRAG
};

void my_engine::Window::modal_base(ImGuiIO *io)
{
    // The only inputs used in 'io' are: io->MousePos, io->MouseDown[0 or 1 or 2]

    ModalEvent event = {};
    ...
    // Mouse Move
    ... { ... modal(event); }

    // Mouse Down (Press / Release)
    ... {
        ...
        modal(event); 

        // Click
        { ... modal(event); }
    }
    ...
}

void my_engine::Window::modal(ModalEvent event)
{
    <This function is very complex>
}
```

ImGui is my life, without it, I'm nothing. So please answer, thanks.

**Comment by ocornut** [comment]
```
ImGuiIO& io = ImGui::GetIO();
io.WantCaptureMouse = true;
``` 
This is incorrect you should NEVER write to this value. None of our comments and documentation suggests to do that.

Use
`ImGui::Text("io.WantCaptureMouse = %d", io.WantCaptureMouse);` 
To display the value on your screen and you'll understand how it works.
You only need to check this value to decide whether your background app can use mouse events.

You don't need anything more. Display the value and you will understand it then you can use it.

```
YourEvent()
{
if (io.WantCaptureMouse)
    return; // ignore

// your application handling
}
```
