### ISSUE TITLE
Wrong z-order with ImGuiViewportFlags_NoAutoMerge and owned windows

### ISSUE THREAD

**Issue by RT222** [ocornut/imgui#4665]
**Version/Branch of Dear ImGui:**

Version: 1.85
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: custom engine
Compiler: MSVC v14.29
Operating System: Windows 10

**My Issue/Question:**

I use a custom backend for my engine where child windows are owned by the main window, like in the win32 backend. It means that child windows are always displayed over the main window, independently of the current focused window. I don't specify the ImGuiBackendFlags_HasMouseHoveredViewport flag and let ImGUI compute the current hovered viewport.

It works fine until I create a child window with the ImGuiViewportFlags_NoAutoMerge flag. If this window is placed over the main viewport, and we gives focus to the latter, ImGUI will suppose that it is now under the main viewport, which is wrong because it's an owned window and it's still drawn at the top, and mouse hovering won't work for it.

I think we need a way to tell ImGUI that child windows are owned to allow it to compute the z-order accordingly.

**Screenshots/Video**

![ezgif-3-e5c759eb2312](https://user-images.githubusercontent.com/9922416/137972875-067c65c2-41e5-4cb2-b5a8-b78914445bdf.gif)

**Comment by ocornut** [comment]
> I think we need a way to tell ImGUI that child windows are owned to allow it to compute the z-order accordingly.

This would help but still lead us into a very imperfect situation. It is much better for the backend to simply honor the `ImGuiBackendFlags_HasMouseHoveredViewport` feature. I have just now relaxed specs for this feature a little to facilitate this: 1338eb3.

Any reason for your backend to not support it?

**Comment by RT222** [comment]
I just made a review of my imgui backend, and now that the specs for ImGuiBackendFlags_HasMouseHoveredViewport have been relaxed, I added support for it and this problem is gone.

I'm closing this issue as fixed, sorry I took so long.
