### ISSUE TITLE
Displaying an Image in IMGUI - Alternative Desired Behavior

### ISSUE THREAD

**Issue by Zrrr1997** [ocornut/imgui#4679]
Hello,

I have read the tutorial on displaying images in imgui at [Image Loading and Displaying Examples](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples)  but I am finding it difficult to achieve an alternative desired behavior.

The current tutorial shows how to display an image **inside** the imgui window by creating a Texture and Rendering the Texture itself. However, I am interested to know if imgui offers the possibility to render that Texture/Image directly in the "background" of the GLFW window as shown in this image on the **RIGHT**, instead of the behaviour which is achieved on the **LEFT** :
![desired_result](https://user-images.githubusercontent.com/40185241/139454137-f2dc9202-0d5a-4245-ad62-f83572dfef92.png)

I managed to follow the tutorial and got the results on the left, but would really like to have the image fill out the background instead. I should mention that I am really new to computer graphics and hope this issue is related to imgui, and not my understanding of OpenGL as a whole.

Please let me know if that is indeed the case. I would appreciate any pointers on how to achieve my desired results (right image of Lena).

**Comment by Zrrr1997** [comment]
Yup, that's exactly what I wanted and it works as intended!

I read about `GetBackgroundDrawlist()` in the FAQ, but it was only referenced for drawing shapes behind all the imgui widgets. I think you could add maybe one sentence in the [Image Loading and Displaying](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples) tutorial where it mentions that you can use this for drawing images in the background as it is very similar to drawing them in the imgui widget. It will also avoid confusion for newly starting people like me :D. 

Thanks a lot for the great work.

**Comment by homerliu1** [comment]
hi Zrrr1997,
could you please post your source code?
thanks.

**Comment by yaroslavhorokhovets** [comment]
hi Zrrr1997,
could you please post your source code?
thanks.

**Comment by GamebP** [comment]
I want the source code to the imgui image.
