### ISSUE TITLE
Cant resize ImGui menu in game

### ISSUE THREAD

**Issue by TrilloxR** [ocornut/imgui#4681]
So I was recently making a multihack for CSGO but I run into a really weird problem. I can't click my ImGui menu, and it looks not really good.

![unknown](https://user-images.githubusercontent.com/93406323/139495961-acdce9aa-c52a-4361-9db5-62d26b519523.png)
![image](https://user-images.githubusercontent.com/93406323/139496082-9b59d39a-6254-4d16-8771-e20c9dff6287.png)
![image](https://user-images.githubusercontent.com/93406323/139496116-e4374295-d897-420d-9d79-42cd013e1645.png)

And yea that's basically it what I have set up for ImGui i don't know if It's something with the code or something else interrupting

**Comment by ocornut** [comment]
Sorry but #1586
