### ISSUE TITLE
ImGui doesnt work ingame, Elements are not clickable but hoverable

### ISSUE THREAD

**Issue by GAFO** [ocornut/imgui#4683]
**Version/Branch of Dear ImGui:**

Version: v1.85
Branch: 55d35d8 / Release

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: MSVC (compiled as MT DLL)
Operating System: Win10
GPU Type: NVIDIA 

**My Issue/Question:**

Hello, 

Im basically writing an extension for a game and the problem is that when Im in Lobby ImGui works as it should but when 
I go ingame it does not.

Ingame the behavior is like if the ImGui menu doesnt get focused at all, the elements like the collapse arrow, or other elements inside the menu like CollapsingHeader etc hightlight when I hover them with the mouse but they cant be clicked.

For Init, Render and WndProc I do it like in the demo & other examples but as mentioned it only works in Lobby, not ingame.

While debugging I also noticed that when I print the window title of the hovered window aka game window it is the game window name in Lobby but when I go ingame it prints "?". 

Also I noticed that this problem does not appear on my friends PC which has also Win10 but a AMD GPU & based on that I tried to disable the Nvidia Gefore Experience Overlay on my PC but that didnt help either.

And the last thing I've noticed is that the toggling of the menu still works ingame (by e.g. VK_INSERT) so the wndproc should be fine.

I've also tried to modifiy the cursor flags when toggling the menu but that does not fix the problem either:
void ToggleMenu()
{
	Config.showMenu = !Config.showMenu;

	ImGuiIO& io = ImGui::GetIO();
	if (Config.showMenu)
	{
		io.ConfigFlags &= ~(ImGuiConfigFlags_NoMouseCursorChange);
		io.MouseDrawCursor = true;
	}				
	else
	{
		io.ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange;
		io.MouseDrawCursor = false;
	}

}

Any ideas what the problem could be ? 

Greetings GAFO

**Comment by ocornut** [comment]
Sorry but #1586
