### ISSUE TITLE
Window Rounding inconsistent after modication

### ISSUE THREAD

**Issue by chaosfissure** [ocornut/imgui#469]
Window Rounding does not persist in a global scope after being changed from a menu bar callback.

I have a callback function in a menu.  I load colors and configuration values from a file, and set them to ImGui::GetStyle().* from this callback.  When I display the value for WindowRounding in the callback function after the value has been set, the value shows up as 0.  However, in the main rendering loop, it considers itself "9". If I save the configuration from the menu from another menu callback, it saves WindowRounding as 0. 

Given that every other Color and Style element loads correctly, it seems like this value is getting temporarily overwritten or reset by some of your code somewhere, and I cannot figure out where this would occur -- as this value only is set in the constructor of ImGuiStyle.  Is there a behavior that I am missing that causes this to happen?

I would be happy to provide some relevant code if you feel that it would be helpful.  I intend to release this code on Github once I've developed it further.

Additional resources:

 - I have a menu button (View->Load Skin) that calls "Load Configuration" which parses and interprets key-value pairs. from a configuration file which is attached:
[guiconfig.txt] https://github.com/ocornut/imgui/files/76675/guiconfig.txt)

 - "Load Configuration" sets the values of ImGui::GetStyle() variables.  All the colors appear to be applied correctly, as do most of the settings.  See the images attached below as examples - the dark BG is the skin I apply, the light BG is the initial settings, and the console output shows the values loaded from, and subsequently saved from ImGui::GetStyle().WindowRounding.

![imgui_main_window_beforeloading](https://cloud.githubusercontent.com/assets/1724191/12079859/7da5fde8-b216-11e5-9598-dead2f1965f7.jpg)
![imgui_main_window_afterloading](https://cloud.githubusercontent.com/assets/1724191/12079861/811372c6-b216-11e5-90c9-d118b9b585d3.jpg)
![imgui_console_output](https://cloud.githubusercontent.com/assets/1724191/12080082/dc718dfe-b21d-11e5-868c-0f8df9615b29.jpg)

**Comment by nem0** [comment]
You are setting the value between BeginPopup and EndPopup (including menu)

callstack
```
ImGui::PopStyleVar(int count) Line 4462 <-- here it is reset to 9
ImGui::EndPopup() Line 3279
ImGui::EndMenu() Line 8464
```

**Comment by ocornut** [comment]
Hello,

I am not sure what you mean by menu callback as ImGui doesn't use much callback apart from mainly the RenderFn one.

Are you using DLL or unusual linkage scheme which could lead to multiple instance of the ImGuiState and ImGuiStyle globals? In doubt you can print the address of ImGui::GetStyle() and verify that it is consistent from all your locations.

If you are using PopStyleVar() incorrectly it may lead to this value being overwritten. Take note that the parameter to PopStyleVar() is a integer counter, 1 by default, and not the enum passed to PushStyleVar().

I am not aware of another writing spot. If that happens within ImGui it is definitively a bug but my intution is that the overwrite most likely happen in your code. If you try creating a repro it may help isolating the issue.

If you are using Visual Studio you might be able to locate the issue using conditional breakpoints.

**Comment by ocornut** [comment]
OK disregard my message, nem0 is totally right. Just looked at the code - BeginPopup does a PushStyleVar(ImGuiStyle_Rounding, 0.0f), EndPopup() does the matching PopStyleVar() so changes in WindowRounding style within the popup will be reverted.

As a workaround the best you could do is do make sure to change the style in a different place of your code, perhaps at the very beginning or end of your frame. Although you could here do a Pop/set/Push in your menu handler to solve this case it would be rather brittle and depends on whatever ImGui is doing. Also, changing your style entirely mid-frame would lead to a frame with style sheering which might look like an annoyance.

**Comment by chaosfissure** [comment]
@nem0 - That is correct.  I have my callbacks to change style evaluated after I draw that element, but before I call EndMenuBar().  I created a menu node hierarchy around the menus and could just recursively draw the entire menu from the root.  During this drawing, I also handled callbacks -- rather than after all the GUI state calls had been made.  I'll need to move the callback handling after (rather than during) the drawing pass.  Thanks for the help!

@ocornut - Thanks - that'd take care of the problem!  My configuration loading was occurring during a point that some style information was pushed and thus the changes were reverted afterwards. I assumed that `GetStyle().WindowRounding` would modify the base value, and that each drawing cycle these values would be updated as the first style list elements -- rather than GetStyle() pulling from the current internal state.

As this is a problem with my own code, I'll close this.  Thank you for the help, and apologies for the trouble!

**Comment by ocornut** [comment]
To clarify, in the vast majority of situations you should be able to process menu items presses immediately, aka follow the easy pattern of doing a simple `if (ImGui::MenuItem("foobar")) { do stuff }` as this is one of the nice and desirable aspects of ImGui. 

You are hitting a bit of a corner case here and for two different reasons it is better if you apply your style at the beginning or end of your frame. But feel free to keep your other callbacks processing immediately.
