### ISSUE TITLE
No Such File Or Directory Problem In VS Code

### ISSUE THREAD

**Issue by tbpaksoy** [ocornut/imgui#4696]
I have  done two things;
1-Put in same file.
2-Added to compilerPath.
But result is like  at down
![resim](https://user-images.githubusercontent.com/85836794/140527635-f15bb0bb-9ddb-42ca-874b-22e8f92d1144.png)
How can I solve this ?

**Comment by ocornut** [comment]
Sorry this is not a dear imgui related question.
