### ISSUE TITLE
Not all of window flags for BeginChild work

### ISSUE THREAD

**Issue by JaanDev** [ocornut/imgui#4699]
**Version/Branch of Dear ImGui:**

Version: v1.81
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: https://github.com/adafcaefc/Universal-OpenGL-2-Kiero-Hook
Compiler: cmake
Operating System: win10

**My Issue/Question:**

So I'm trying to create a normal window and a child one, but some window flags for the child window don't really seem to work. The ones from used that don't work are ImGuiWindowFlags_NoTitleBar and ImGuiWindowFlags_NoResize. The other ones do work. Also, the same flags for Begin() work well, as seen on the screenshot.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/67502867/140618121-368b4af1-8226-451a-b5fc-56d5eaa4eeda.png)

**Not a standalone, minimal, complete and verifiable example:**
```
ImGui::SetNextWindowSize(ImVec2(400, 600), ImGuiCond_FirstUseEver);
		ImGui::Begin("E", 0,
								ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
								ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse |
								ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoSavedSettings);

		ImGui::StyleColorsDark();
		ImGuiStyle& style = ImGui::GetStyle();
		style.WindowBorderSize = 0.0f;
		style.ChildBorderSize = 0.0f;
		style.WindowRounding = 7.f;
		style.ChildRounding = 7.f;
		style.Alpha = 1.f;
		style.Colors[ImGuiCol_WindowBg] = ImVec4(.05f, .05f, .05f, 1.f);
		style.Colors[ImGuiCol_ChildBg] = ImVec4(.05f, .05f, .05f, 1.f);

		mainWindow(); // function to add contents, works fine

		ImGui::End();

		ImGui::SetNextWindowSize(ImVec2(400, 600), ImGuiCond_FirstUseEver);

		ImGuiWindowFlags flgs = ImGuiWindowFlags_None;
		flgs |= ImGuiWindowFlags_NoTitleBar; // doesnt work
		flgs |= ImGuiWindowFlags_NoResize; // doesnt work
		flgs |= ImGuiWindowFlags_NoScrollbar;
		flgs |= ImGuiWindowFlags_NoScrollWithMouse;
		flgs |= ImGuiWindowFlags_NoCollapse;
		flgs |= ImGuiWindowFlags_NoSavedSettings;

		ImGui::BeginChild("ChildR", ImVec2(0, 0), false, flgs);
		modsWindow(); // function to add contents, works fine

		ImGui::EndChild();
```

**Comment by ocornut** [comment]
I don’t understand your request. Child windows don’t have a title bar so of course those flags have no effect.

**Comment by JaanDev** [comment]
Sorry, how is this called then?
![image](https://user-images.githubusercontent.com/67502867/140618480-07e92fbd-6a6e-44fa-9ea6-ca1d47d18f12.png)

**Comment by ocornut** [comment]
I see. If you call any function outside of a Begin/End pair the item gets added to a default “Debug” window.

Your problem is you are calling BeginChild() not inside a Begin/End pair. You should create a normal window to host child windows.

**Comment by JaanDev** [comment]
Ohhh thanks i was caling it after the end of the host window.

**Comment by JaanDev** [comment]
`ImGui::SetNextWindowSize(ImVec2(400, 600), ImGuiCond_FirstUseEver);
		ImGui::Begin("E", 0,
								ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
								ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse |
								ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoSavedSettings);	

		ImGui::StyleColorsDark();
		ImGuiStyle& style = ImGui::GetStyle();
		style.WindowBorderSize = 0.0f;
		style.ChildBorderSize = 0.0f;
		style.WindowRounding = 7.f;
		style.ChildRounding = 7.f;
		style.Alpha = 1.f;
		style.Colors[ImGuiCol_WindowBg] = ImVec4(.05f, .05f, .05f, 1.f);
		style.Colors[ImGuiCol_ChildBg] = ImVec4(.05f, .05f, .05f, 1.f);

		mainWindow();	

		ImGui::SetNextWindowSize(ImVec2(400, 600), ImGuiCond_FirstUseEver);

		ImGui::BeginChild("Mods", ImVec2(400, 600), false, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
								ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse |
								ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoSavedSettings);

		modsWindow();

		ImGui::EndChild();	

		ImGui::End();	`

Sorry, but the child window doesn't show up now...
