### ISSUE TITLE
Child window is not displayed

### ISSUE THREAD

**Issue by JaanDev** [ocornut/imgui#4700]
**Version/Branch of Dear ImGui:**

Version: v1.81
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: https://github.com/adafcaefc/Universal-OpenGL-2-Kiero-Hook
Compiler: cmake
Operating System: win10

**My Issue/Question:**

Even though I do BeginChild, only the main window is displayed. I tried to add text into the child but it didn't help. The child window just isnt rendered.

**A standalone, minimal, complete and verifiable example:**

`		ImGui::SetNextWindowSize(ImVec2(400, 600), ImGuiCond_FirstUseEver);
		ImGui::Begin("E", 0,
								ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize |
								ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse |
								ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoSavedSettings);	

		ImGui::StyleColorsDark();
		ImGuiStyle& style = ImGui::GetStyle();
		style.WindowBorderSize = 0.0f;
		style.ChildBorderSize = 0.0f;
		style.WindowRounding = 7.f;
		style.ChildRounding = 7.f;
		style.Alpha = 1.f;
		style.Colors[ImGuiCol_WindowBg] = ImVec4(.05f, .05f, .05f, 1.f);
		style.Colors[ImGuiCol_ChildBg] = ImVec4(.05f, .05f, .05f, 1.f);

		mainWindow();

		ImGui::BeginChild("child", ImVec2(0, 0), true);
        ImGui::EndChild();		

		ImGui::End();`

**Comment by ocornut** [comment]
This should works so you are omitting something and the omitted code is responsible for your issue.
