### ISSUE TITLE
I think LogFinish() should not append a new line.

### ISSUE THREAD

**Issue by mohammad-ghasemi-2549** [ocornut/imgui#4703]
// dear imgui, v1.77 WIP

The ImGui::LogFinish() appends a new line before stopping the log. I think that makes the API inflexible. Because it is something additional to finishing the log. I suggest ImGui::LogFinish(bool should_append_new_line = true) API. Because it is not a breaking change and also gives the option not to append a new line.
Thank you.

**Comment by ocornut** [comment]
Hello Mohammad,
In order to investigate this and take a more informed decision I would need a specific example of the issue you are trying to solve and where that new line is a problem for you.

**Comment by mohammad-ghasemi-2549** [comment]
OK. In my application I used the logging functions to let the user copy my bitcoin address to the clipboard (for donation). And I realized it also appends a new line at the end of the address. I don't know if the new line will produce an error in bitcoin wallets or not. But I thought lets just not create the new line as a precaution. Anyway the user sees the new line and probably hits the backspace to remove it. And I thought this is user-unfriendly to make him do so.

**Comment by ocornut** [comment]
Why not simply calling `ImGui::SetClipboardText()` ?

**Comment by mohammad-ghasemi-2549** [comment]
I didn't know about that :-)
Thank you.

**Comment by ocornut** [comment]
LogXXX api is designed to turn whole UI sections into text and it would be difficult to allow the user to expect a precise format. 
`SetClipboardText()` would work better for your case.
