### ISSUE TITLE
InputText show '???' when use IME

### ISSUE THREAD

**Issue by Geistyp** [ocornut/imgui#471]
VS2015 oF 0.9 win10 x64
![20160105165143](https://cloud.githubusercontent.com/assets/1510109/12111256/eba96852-b3ce-11e5-9c9d-8abb6f6641c9.png)

```c++
ImGuiIO * io = &ImGui::GetIO();
ImFontConfig font_config; 
font_config.OversampleH = 1; 
font_config.OversampleV = 1; f
ont_config.PixelSnapH = 1; 
ImFont* f = io->Fonts->AddFontFromFileTTF("data/Deng.ttf", 18.0f, &font_config, io->Fonts->GetGlyphRangesChinese());

io->ImeWindowHandle = ofGetWin32Window();
```

```c++
char buf[256];
ImGui::InputText(ofLocaleToUtf8("中文").c_str(), buf, 256);
```

**Comment by ocornut** [comment]
Display seems ok, but it looks like your user code (maybe OF code) isn't passing the correct inputs to io->AddInputCharacter().

**Comment by Geistyp** [comment]
oF use glfw, but not official version
```c++
void BaseEngine::onKeyPressed(ofKeyEventArgs& event)
{
	int key = event.keycode;
    io->KeysDown[key] = true;
    io->AddInputCharacter((unsigned short)event.codepoint);
	//io->AddInputCharactersUTF8((char*)event.codepoint);
}
```

codepoint in KeyEvent
```c++
/// \brief The Unicode code point you'd expect if this key combo (including modifier keys) was pressed in a text editor, or -1 for non-printable characters. 
unsigned int codepoint;
```

I think this codepoint is same if I use __glfwSetCharCallback()__

By the way, in this image, I haven't press space, that means "???????" is my composition text, not my final select text.
![2 q5jv j34n r4woomv vx](https://cloud.githubusercontent.com/assets/1510109/12112058/e6b4c35e-b3d4-11e5-9829-4bbd8a275598.png)

**Comment by Geistyp** [comment]
yes, codepoint not right.

I should use __glfwSetCharCallback()__ instead
```c++
auto ptr = static_cast<ofAppGLFWWindow*>(ofGetWindowPtr());
glfwSetCharCallback(ptr->getGLFWWindow(), ImGui_ImplGlfwGL3_CharCallback);
```

**Comment by ocornut** [comment]
You may want to log out the value that are passed to AddInputCharacter().
`BaseEngine::onKeyPressed` isn't GLFW so there must be some sort of translations happening.

**Comment by Geistyp** [comment]
tks, this should be oF core issue

**Comment by ocornut** [comment]
Cool. Maybe report it to the OF ImGui extension https://github.com/jvcleave/ofxImGui/ or OpenFrameworks.

**Comment by ocornut** [comment]
Note that raw GLFW 3.0 still has various issues with IME.
For example I have suggested this fix: https://github.com/glfw/glfw/issues/41#issuecomment-160421273
Without it I get the final "Enter" keypress of validating IME input to be fed into ImGui code. But there are other issues discussed and in the work.

**Comment by Geistyp** [comment]
Do you means that if I press “Enter" to confirm my selection ImGui will add "Enter" code to buffer string?

**Comment by ocornut** [comment]
In some instances, if you press Enter to confirm your IME input, GLFW also pass an Enter keypress to your application via the callback. Normally the application shouldn't receive this Enter keypress.

**Comment by Geistyp** [comment]
Yes, this issue exist in oF's glfw too. "Enter" code add to buffer, new input won't add to buffer now, unless I backspace that code.

**Comment by Geistyp** [comment]
https://github.com/arturoc/glfw/blob/feature-keysUnicode/src/win32_window.c#L320
```c++
case WM_SYSKEYDOWN:
        {
            const int scancode = (lParam >> 16) & 0x1ff;
            const int key = translateKey(wParam, lParam);
            if (key == _GLFW_KEY_INVALID)
                                break;
                        const int unicode = translateToUnicode(wParam,scancode);

                        _glfwInputKey(window, key, scancode, unicode, GLFW_PRESS, getKeyMods());
            break;
        }
```
oF already translate char to unicode, but ImGui need original char.
```c++
case WM_CHAR:
        {
            _glfwInputChar(window, (unsigned int) wParam, getKeyMods(), GL_TRUE);
            return 0;
        }
```

**Comment by ocornut** [comment]
That translation in the WM_KEYDOWN/WM_SYSKEYDOWN handler is probably incorrect in case of IME use.

**Comment by yinjimmy** [comment]
WOW, Chinese character coding input method.

**Comment by idodoyo** [comment]
小伙能否一起学习一下IMGUI , 求带入门啊!

**Comment by Geistyp** [comment]
@ocornut sorry to ask here, is there any example to save/load gui para? I want to save/load all UI para include this chinese input text.
I've read your post here https://forum.libcinder.org/topic/imgui#23286000002477025

I plan to use ofParameterGroup to store this, but first I need to get all UI element.
I try getstate from my window, but get empty data
```c++
ImGuiStorage* tmp = ImGui::GetStateStorage();
```

**Comment by ocornut** [comment]
This is quite out of the scope of what ImGui does.
I am not sure what you are trying to save exactly, what you mean by "all UI element". ImGui hold very little state, All the values, or whatever you refer to what "chinese input text" are user data, not ImGui data. The ImGuiStorage structure is typically used to store if a tree node was opened or closed.

**Comment by Geistyp** [comment]
Simply I want to save all slider value. 

Some other GUI library has save/load feature, so I wonder if ImGui have. I will go deep into ImGui to find a better way for my project. :)

**Comment by ocornut** [comment]
The question doesn't make sense: ImGui doesn't know anything about your slider values. It isn't keeping any state. The values are all your data, not ImGUi data.

**Comment by wangjieest** [comment]
`
    case WM_CHAR:
#ifdef _UNICODE
    {
// Surrogate pair : [0x10000, 0x10FFFF]
#define SurrogateMin 0x010000
#define SurrogateMax 0x10FFFF
#define SurrogateBaseHigh 0xD800
#define SurrogateBaseLow 0xDC00
#define SurrogateBitCount 10
#define SurrogateBitMask 0x3FF
        wchar_t CharBuf[2];
        if (wParam > 0 && wParam < SurrogateMin)
        {
            // char within 2 bytes
            io.AddInputCharacter((unsigned short)wParam);
        }
        else if ((wParam >= SurrogateMin) && (wParam <= SurrogateMax))
        {
            // Surrogate pair
            UINT Code = wParam - SurrogateMin;
            CharBuf[0] = SurrogateBaseHigh | ((Code >> SurrogateBitCount) & SurrogateBitMask);
            CharBuf[1] = SurrogateBaseLow | (Code & SurrogateBitMask);
            AppendInputString(CharBuf,2);
        }
        return true;
    }
#else //_UNICODE
    {
#define MAXANSIBUF (IM_CHAR_ARRAY_SIZE - 1)
        // Ime support for cjk
        static int LastBufferLen = 0;
        static char LastBuffer[MAXANSIBUF] = {0};

        if (wParam > 0 && wParam < 0x100)
        {
            wchar_t wsBuf[MAXANSIBUF];//16
            LastBuffer[LastBufferLen++] = static_cast<char>(wParam);
            if (LastBufferLen == MAXANSIBUF)
            {
                int cchBuf = MultiByteToWideChar(ImeACP, MB_ERR_INVALID_CHARS, LastBuffer, LastBufferLen, wsBuf, MAXANSIBUF);
                if (cchBuf > 0)
                    AppendInputString(wsBuf, cchBuf);
                LastBufferLen = 0;
                return true;
            }

            LastBuffer[LastBufferLen] = '\0';
            // try
            char* const pMax = LastBuffer + LastBufferLen;
            char* pNext = LastBuffer;
            char* pCur = LastBuffer;
            while (pNext < pMax && *pNext)
            {
                pCur = pNext;
                pNext = CharNextExA((WORD)ImeACP, pCur, 0);
            }

            if (pCur == pMax)
             {
                // convert the full part bytes
                int cchBuf = MultiByteToWideChar(ImeACP, 0, LastBuffer, pMax - LastBuffer, wsBuf, MAXANSIBUF);
                AppendInputString(wsBuf, cchBuf);
                LastBufferLen = 0;
                return true;
            }


            {
                // try convert the left bytes
                int cchBuf = MultiByteToWideChar(ImeACP, MB_ERR_INVALID_CHARS, pCur, pNext - pCur, wsBuf, MAXANSIBUF);
                if (cchBuf > 0) 
                {
                    AppendInputString(wsBuf,cchBuf);
                    LastBufferLen = 0;
                    return true;
                }
                else
                {
                    LastBufferLen = pNext - pCur;
                    MoveMemory(LastBuffer, pCur, LastBufferLen);
                    LastBuffer[LastBufferLen] = '\0';
                    return true;
                }
            }
        }
    }
#endif //_UNICODE
`
imgui just handle only WM_CHAR on unicode window correctly.
you should rehandle WM_CHAR or change the way creating window.
