### ISSUE TITLE
ImGuiInputTextFlags_CallbackEdit is unusable with InputScalar

### ISSUE THREAD

**Issue by Ou7law007** [ocornut/imgui#4712]
Version: v1.86 WIP
Branch: Docking

```
ImGui::InputScalar("whatever", ImGuiDataType_::ImGuiDataType_Float, &val, &s, &ss, "%.f", 
ImGuiInputTextFlags_::ImGuiInputTextFlags_CallbackEdit)
```
Internally, it will call InputText at: Line 3451 inside imgui_widgets.cpp with nullptr as callback (default args)

```
        if (InputText("", buf, IM_ARRAYSIZE(buf), flags)) // PushId(label) + "" gives us the expected ID from outside point of view
            value_changed = DataTypeApplyOpFromText(buf, g.InputTextState.InitialTextA.Data, data_type, p_data, format);
```
or at Line 3488 inside imgui_widgets.cpp with nullptr as callback (default args)
```
        if (InputText(label, buf, IM_ARRAYSIZE(buf), flags))
            value_changed = DataTypeApplyOpFromText(buf, g.InputTextState.InitialTextA.Data, data_type, p_data, format);
```
Is there any other way to load callbacks?

**Comment by ocornut** [comment]
That callback doesn’t make sense for scalar types why do you need it ?

All functions returns true when a value was edited and you can use IsItemXXX functions too.

**Comment by Ou7law007** [comment]
I'm using it with a slider. I want the user to be able to input values for the slider itself but the problem is that InputScalar doesn't support min and max so I want to do it manually.
It can be done with an if statement:
```
	ImGui::SliderScalar("", ImGuiDataType_Float, value, &min, &max, "%.f");

	if (ImGui::BeginPopupContextItem("asdasduj", ImGuiPopupFlags_::ImGuiPopupFlags_MouseButtonRight))
	{
		if (ImGui::InputScalar("dasdad", ImGuiDataType_::ImGuiDataType_Float, value, &step, &stepFast, "%.f", /*ImGuiInputTextFlags_CallbackEdit*/))
		{
			if (*value >= min && *value <= max)
			{
				oldVal = *value;
			}
			else
			{
				*value = oldVal;
			}
		}

		ImGui::EndPopup();
	}
```
But this doesn't update the InputScalar's visual buffer when the value is outside the range.
Did I explain it well enough? Or should make something like GIF or a video?
Also, if it doesn't make sense, I wonder why it's there for this function at all!

**Comment by ocornut** [comment]
Why not letting the user simply CTRL+Click on the slider + pass `ImGuiSliderFlags_AlwaysClamp` to `SliderFloat()` ?

**Comment by Ou7law007** [comment]
I have too small of a space with too many sliders, so I modified the source code a of SliderScalar to make sliders thinner (since you can't control slider thickness AFAIK, see https://github.com/ocornut/imgui/issues/2263). And now, CTRL + Mouse 1 produces a text field with a very tiny height (less than the height of the font itself).

Kind of a weird workaround but I find the popup to be a more elegant, so...

I'm not trying to get my code fixed here, hence this bug report. (At least what I believe to be a bug)

**Comment by ocornut** [comment]
> But this doesn't update the InputScalar's visual buffer when the value is outside the range.

It doesn't make sense to edit a text field while user is editing that field that would generally be undesirable.
But if you really want it to can call InputText() + callback + scanf or atof to turn the string back into a number, like InputScalar() does.
