### ISSUE TITLE
Imgui::Image showing a black canvas on OpenGL3

### ISSUE THREAD

**Issue by h4k1m0u** [ocornut/imgui#4716]
Hi, I know this issue has been reported before by others but in my case I can't debug it with RenderDoc as I'm constrained to use OpenGL3.0 (which isn't supported).
My code is more or less the same as the one in the tutorial but I'm getting a black canvas instead of the image (which does indeed exist on disk at the provided path). I checked with gdb that the pointer is pointing to filled image data.

- My main loop: https://github.com/OpenGL-Graphics/imgui-example/blob/master/src/main.cpp
- Dialog rendering: https://github.com/OpenGL-Graphics/imgui-example/blob/master/src/gui/dialog.cpp#L22
- Texture constructor: https://github.com/OpenGL-Graphics/opengl-texture/blob/f78dab519a5b07bac770295680814533b04d52a9/src/texture.cpp#L21

Is there another way to debug this (to check if texture is being filled)? I'm getting started with imgui so I'm not sure if I have to use a shader program the same way I used to do it with OpenGL to render ran image on it.

P.s: I already have a similar code based on the same Texure class that works correctly with GLSL shaders (without imgui).

**Update:**
Looks like I'm missing something related to my texture as imgui can perfectly show the font texture in `imgui_demo.cpp`:

```cpp
ImGuiIO& io = ImGui::GetIO();
ImTextureID my_tex_id = io.Fonts->TexID;

// show image from texture
m_texture.attach();  
void *ptr_img_id = &m_texture.id;
ImGui::Image(my_tex_id, ImVec2(m_texture.width, m_texture.height));
```

**Comment by h4k1m0u** [comment]
Finally found what was wrong with my function call, I was passing the wrong parameter to `ImGui::Image()`, I saw it accepts as a first parameter a `void *` and thought it should therefore get a `GLuint *` not a `GLuint` that was casted to a void* (as explained in the tutorial). This solved it:

```cpp
ImGui::Image((void*)(intptr_t) m_texture.id, ImVec2(m_texture.width, m_texture.height));
```

**Comment by ocornut** [comment]
Good to hear!
