### ISSUE TITLE
imgui content size inside beginchild (scrollbar glitch)

### ISSUE THREAD

**Issue by esealegenden** [ocornut/imgui#4718]
Version : 1.78
Branch: Master
-------------------------------x-----------------------------

I ran into a problem related to a scrollbar that doesn't want to pull down items in the menu. SetNextWindowContentSize(GetMaxContentSize.y) does not help, as well as GetScrollMaxY, only manual input of the y value helped, but it turned out not to be dynamic and does not change when the functions that complement the menu are disabled. How to solve this problem?
video - https://user-images.githubusercontent.com/71351988/104360101-99599a00-5521-11eb-878e-24931687e772.gif

**Comment by rokups** [comment]
> How to solve this problem?

1. Update Dear ImGui. v1.78 is quite old and this issue may (or may not) be fixed.
2. Fill issue template. It is there for a reason.
3. Also include a small code sample that we can copy into example application and reproduce issue.

**Comment by ocornut** [comment]
This may also a bug in one of your custom widget (eg layout/size of some widget depending on visibility). We can’t really magically guess without a detailed repro. Will reopen this issue if more details gets posted.
