### ISSUE TITLE
So this is code of main in my editor, which lets me render the imgui. But still couldnt figure out how to handle inputs in imgui and my engine with this approach. One thing I did was pass the wndproc from the imgui to my window system which lets the imgui handle the inputs, but my engine also needs the input !! Because object picking and movement will be handled by the engine not imgui !!

### ISSUE THREAD

**Issue by jacquesvaneeden** [ocornut/imgui#4724]
So this is code of main in my editor, which lets me render the imgui. But still couldnt figure out how to handle inputs in imgui and my engine with this approach. One thing I did was pass the wndproc from the imgui to my window system which lets the imgui handle the inputs, but my engine also needs the input !! Because object picking and movement will be handled by the engine not imgui !!

```
   enyin::Engine engine;
    engine.Start(hInstance, WndProc);
    HWND hwnd = enyin::WindowSystem::GetInstance().getWindowHandler();
    ImGui_Init(hwnd);
    while (true)
    {
        engine.GameLoop();
        ImGui_Update();
    }
    engine.Release();
```

_Originally posted by @anshul-soni in https://github.com/ocornut/imgui/issues/372#issuecomment-148237903_

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please make sure you have read the FAQ.
- This question is widely answered in comments and examples.

Closing.

**Comment by jacquesvaneeden** [comment]
I need a little help here, I have a win32 app with OpenGL rendering and would like to plug imgui into the existing system. I came across this old post that discussed this exact topic. I have no idea wat is suppose to be behind the ImGui_Init() and ImGui_Update() functions.
