### ISSUE TITLE
How to dsiable alpha in ImGui::Image?

### ISSUE THREAD

**Issue by l1ghtrider** [ocornut/imgui#4730]
Im working for a scene window using ImGui::Image to display my scene, there are translucent elements so the frame buffer shall shall contains texels with alpha factor after rendering the scene,
it seems the ImGui::Image take the alpha factor and blend to the window background (in my case, the window background is black)
is there some quick trick to render the color only?

**Comment by PathogenDavid** [comment]
The issue template isn't there just for fun 😘

**Comment by l1ghtrider** [comment]
> The issue template isn't there just for fun 😘

im serious, i need this feature and seems there aren't solution on net, 
it is an issue for me and if its not an "Issue" and just no such feature, apologies, i'll try otherway

**Comment by carterjwasd** [comment]
image transparent?

**Comment by l1ghtrider** [comment]
> image transparent?

yes

**Comment by ocornut** [comment]
If you cannot remove the alpha component from your texture, you would need to either disable alpha blending during the rendering of that image, or swap the shader to one which omits alpha. You can do that by registering a ImDrawList call with AddCallback() to a custom callback tailored for the rendering backend you are using (eg for an OpenGL backend your custom callback would eg disable blending, then you submit another callback after the image to reenable blending).

Variants of this question have been asked here before, and because you have ignored our guidelines and issue template I am closing this.

**Comment by l1ghtrider** [comment]
> If you cannot remove the alpha component from your texture, you would need to either disable alpha blending during the rendering of that image, or swap the shader to one which omits alpha. You can do that by registering a ImDrawList call with AddCallback() to a custom callback tailored for the rendering backend you are using (eg for an OpenGL backend your custom callback would eg disable blending, then you submit another callback after the image to reenable blending).
> 
> Variants of this question have been asked here before, and because you have ignored our guidelines and issue template I am closing this.

Thank you for help, this is exactly what im looking for, and sorry for ignoring the issue template , im just new to communicate on github and didn't realize that, i'll check it then.

**Comment by aboood40091** [comment]
I know this is an issue from 2 years ago, but in case someone comes through this, there is an easier solution than everything mentioned here for OpenGL, which is _swizzling_ (`GL_TEXTURE_SWIZZLE_RGBA`). Simply set the alpha channel swizzle to `GL_ONE`. Example:
```cpp
// Texture must be bound first
GLint swizzle[4] = {
    GL_RED,   // Shader Red   channel source = Texture Red
    GL_GREEN, // Shader Green channel source = Texture Green
    GL_BLUE,  // Shader Blue  channel source = Texture Blue
    GL_ONE    // Shader Alpha channel source = One
};
glTexParameteriv(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_RGBA, swizzle);
```

As mentioned, this is for OpenGL, but most graphics APIs have swizzling, you just need to figure out how to do it for your API.
