### ISSUE TITLE
problem with ImVec2 operators in v1.83

### ISSUE THREAD

**Issue by Cerraosso** [ocornut/imgui#4735]
hi there, i cant do any operator with Imvec2 in  v1.83 
can someone help?
![caralho](https://user-images.githubusercontent.com/53304993/142506515-a1ed412b-dfff-4943-a305-e080ae8d41b9.png)

exemple:

```
#include "imgui/imgui.h"
#include "imgui/imgui_impl_dx9.h"
#include "imgui/imgui_impl_win32.h"
#include "imgui/imgui_internal.h"

mVec2 vec = ImVec2(1, 1);
ImVec2 vec1 = center - ImVec2(1, 1); //(error operator  - )
```

**Comment by ocornut** [comment]
Read the first few lines of imgui_internal.h
