### ISSUE TITLE
WebGL context lost on Chromium v96 based browsers

### ISSUE THREAD

**Issue by egillij** [ocornut/imgui#4737]
**Version/Branch of Dear ImGui:**

Version: v1.86 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp
Compiler: Emscripten
Operating System: Chromium based browsers

**My Issue/Question:**

When using ImGui with WebGL there is a problem with the WebGL context getting lost (_WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost_). This only seems to happen in the latest release of Chromium (version 96). This can be reliably reproduced on the recently released Google Chrome Version 96.0.4664.45. 
Through some debugging we have managed to isolate the issue to the ***ImGui_ImplOpenGL3_RenderDrawData*** function. If that is commented out the rest of our application works fine. In more detail this seems to happen when populating the index buffers with data https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_opengl3.cpp#L429 . 

**Standalone, minimal, complete and verifiable example:** 
Unfortunately we can't share our own code, but we have been able to reproduce it in publicly available examples such as https://github.com/jnmaloney/WebGui .  The UI sometimes works for a few seconds and then the WebGL context is lost.

**Comment by mekhontsev** [comment]
I had the same issue. 
To resolve it, just comment out the following line in the imgui_impl_opengl3.cpp (for Emscripten)
`#define IMGUI_IMPL_OPENGL_USE_VERTEX_ARRAY`


[The commit causing this problem](https://github.com/ocornut/imgui/commit/2ab7f96f211bea8223bdd22ff100722d50cafa78)

**Comment by egillij** [comment]
Commenting out the define for Emscripten works, but that also forces us to disable the use of vertex arrays in our own renderer, while vertex arrays work fine without ImGui rendering. Perhaps this is a bug in the latest Chromium. We have tried running the same code with vertex arrays enabled in the dev channel of Chrome, and there it works just fine. Also it has worked for months in earlier releases of Chrome.

**Comment by RobertoMalatesta** [comment]
I suspect a BUG/REGRESSION in Chrome 96. 
Chromium 98 does not show the same behaviour and works OK.
I sent several messages via the "Report an issue..." browser menu to no avail.
R

**Comment by boardend** [comment]
This was really a Chromium regression... 😲

With the latest version (`96.0.4664.93`) and also latest canary (`98.0.4753.2`) everything works again as it did with `<= 94`, without any changes/recompilation

**Comment by ocornut** [comment]
Great to hear ! Closing this now.
