### ISSUE TITLE
During my first frame, ImDrawData does not contain any data about commands

### ISSUE THREAD

**Issue by prostargamer** [ocornut/imgui#4740]
**Version/Branch of Dear ImGui:**

Version: 1.86 WIP (18510)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: MSVC 2019
Operating System: Windows 10

**My Issue/Question:**

During the first execution of the code that sets the necessary things for ImGui, as a result I get an empty _ImDrawData_
I get a non-zero pointer to _ImDrawData_ which in its first frame not contains a data about commands.
![image](https://user-images.githubusercontent.com/37502620/142676274-3b4ba363-6d02-4512-8686-4d7058658e7e.png)
However, with next frames I have no problems.
It turns out that the first call of these functions does not lead to the correct result.
How to fix it?

That's what I do in my frame:
```
ImGui_ImplVulkan_NewFrame();
ImGui_ImplGlfw_NewFrame();
ImGui::NewFrame();
static bool windowOpened = true;
static bool showDemoWindow = false;
ImGui::Begin("Rendertime", &windowOpened, 0);
ImGui::Text("Frametime: %f", 1000.0f / ImGui::GetIO().Framerate);
ImGui::Checkbox("Show ImGui demo window", &showDemoWindow);
ImGui::End();
if (showDemoWindow) {
	ImGui::ShowDemoWindow();
}

ImGui::Render();
ImDrawData* main_draw_data = ImGui::GetDrawData();
```

**Comment by ocornut** [comment]
This is expected and has already been discussed in near identical issues.

You cannot “fix” it but you could run through two dear imgui frames, or not render/swap your first frame.

**Comment by ocornut** [comment]
See eg #1905
