### ISSUE TITLE
ImFileLoadToMemory fread error handling insufficient

### ISSUE THREAD

**Issue by ParticlePeter** [ocornut/imgui#4741]
Must be using one rare `libc` where, on `fread` reaching end of file, the incorrect count of read bytes is returned. Unfortunately that means that a false positive condition in `ImFileLoadToMemory` prevents me from loading a font file.

Detailed steps: calling `AddFontFromFileTTF` fails for me, the actual error occurs in `ImFileLoadToMemory`, imgui.cpp line 1635 (master branch, commit 7f38773b738e8d37b1a3c1d627205821300ef765a). The condition compares the count of bytes read by `ImFileRead` (which in turn calls and returns the result of `fread`), with the actual file size:
```
    if (ImFileRead(file_data, 1, file_size, f) != file_size)
    {
        ImFileClose(f);
        IM_FREE(file_data);
        return NULL;
    }
```
In my case the consola.ttf font file I read in has a size of 444760 bytes and `fread` always returns 258, the condition above is satisfied and loading the font fails.

I checked [this `fread` spec](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fread.html) and found a surprisingly wired wording:

>RETURN VALUE
    Upon successful completion, fread() shall return the number of elements successfully read which <ins>**is**</ins> less than nitems only if a read error or end-of-file is encountered.

My English is not the best, but to my understanding, due to the usage of <ins>**is**</ins>, this would mean that, if `eof` is reached, `fread` <ins>**must always**</ins> return a value which is smaller than the read elements count ... which would be bananas, right?

[CppReference](https://en.cppreference.com/w/c/io/fread) has a less restrictive wording:

>Return value
Number of objects read successfully, which <ins>**may be**</ins> less than count if an error or end-of-file condition occurs.

My suggestion is to follow CppRefernce wording and also handle possible file read errors:

```
    if (((ImFileRead(file_data, 1, file_size, f) != file_size) && !feof(f)) || ferror(f))
    {
        ImFileClose(f);
        IM_FREE(file_data);
        return NULL;
    }
```

To my knowledge this covers all the valid and error cases ... and also works for me :-)

Cheers, PP!

**Comment by ocornut** [comment]
Could you provide a repro with a file and more details. Opening file needs an explicit “b” open type otherwise Windows does conversion of CRLF on read which makes ftell size mismatch fread one.

**Comment by ParticlePeter** [comment]
You are spot-on, that's exactly what's going wrong. The repro is somewhat exotic, [here](https://github.com/KytoDragon/imgui) is a auto-generated (transpiled) DLang version of your code, beta and WIP. ImFileHandle, in that Repo, has a tiny error the wchar_t case replacing `b` of the `rb` mode with a terminating `\0`. Fixing it solves the problem. Would have never guessed that the problem might be already at the file opening state. Sorry for the fuzz, the fread spec misslead me there.  Closing!
