### ISSUE TITLE
ImGui::Image with a texture in grayscale

### ISSUE THREAD

**Issue by h4k1m0u** [ocornut/imgui#4748]
I have opened an RGB image with ImGui:

```cpp
glActiveTexture(m_index);
glBindTexture(m_type, id);
ImGui::Image((void*)(intptr_t) m_texture.id, ImVec2(m_texture.width, m_texture.height));
```

Then when I convert it to grayscale (manually pixel by pixel inside my code) and try to load it in a texture in `GL_RED`format, this is the result I'm obtaining:

![screenshot](https://user-images.githubusercontent.com/4227512/142742651-e48cca3a-091d-47be-a772-b7e0a32d9705.png)

Anyone has an explanation for what's causing this? knowing that I've already used `GL_RED` format textures to show freetype fonts. Besides, I couldn't find amongst `ImGui::Image()` arguments any parameter that pertains to image's number of channels.

The same thing happens when I load a grayscale image directly with `ImGui::Image()` and again set the format to `GL_RED`.
 
*Note:* The only workaround I found is to duplicate the same gray pixel value for red/green/blue components. In this case, I did get a grayscale image but with the same pixel value duplicated three times for every pixel.

**Comment by ocornut** [comment]
Same answer as #4730 

This is how the image would be displayed with a shader trying to fetch 4 components from the texture. You’ll need a custom shader to display a single component texture in greyscale. Once you understand the answer in #4730 (use AddCallback before and after your Image to have a chance to change the shaders and then restore it), other than that this is more of a GL question.

**Comment by aboood40091** [comment]
Also as I mentioned in the issue @ocornut referenced, you can use swizzling to do this:
```cpp
// Texture must be bound first
GLint swizzle[4] = {
    GL_RED,   // Shader Red   channel source = Texture Red
    GL_RED,   // Shader Green channel source = Texture Red
    GL_RED,   // Shader Blue  channel source = Texture Red
    GL_ONE    // Shader Alpha channel source = One
};
glTexParameteriv(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_RGBA, swizzle);
```
