### ISSUE TITLE
[Feature Request] Ability to hide widget names

### ISSUE THREAD

**Issue by Leopard20** [ocornut/imgui#4749]
For example in this window:
![image](https://user-images.githubusercontent.com/16115820/142768319-2b7111f5-9bf3-4c10-a5bf-031ecf545abe.png)
I want to keep the title bar, but hide the window name (`Right Menu`). And I want to hide the DragFloat names (the ones showing `posX`, `posY`, etc.)
As you know, using `""` is not an option because ImGui uses them as IDs.
The only way I found was setting the `ImGuiCol_Text` alpha to `0`, but in the case of the DragFloat widget, it hides the number too.

(I apologize if this feature already exists, but I couldn't find anything)

**Comment by ocornut** [comment]
> As you know, using "" is not an option because ImGui uses them as IDs.

The answer for this is in the FAQ.
