### ISSUE TITLE
How to render 3D scene within UI Element ? 

### ISSUE THREAD

**Issue by tanb0065** [ocornut/imgui#475]
Hi,

I am new to imgui. After done some reading, I notice there is a way to render 3D scene in UI Element which is using ImDrawCallBack. However, I still have no clue on how to use this function. 

Can show me an example on how to use this function ? Or is there any other simple way to do it.

Using OpenGL/GLFW.

**Comment by emoon** [comment]
The easiest way is likely to setup a new render target before you render the UI element and then use that render target later in your rendering which you want to render.

**Comment by ocornut** [comment]
If you use the callback system the render loop code will just call your function in the right order (ImGui render window back-to-front). What the callback does is all up to you. Typically you'd want to pass data in the void*, what to render, where to render it, etc. And then the callback can act upon that. 

Another solution is to render your scene in a texture/buffer and then use facilities such as ImGui::Image() to just draw this buffer within your UI. This is generally easier to play with, if you can get your scene in a texture first. (Using a callback would technically have the advantage that you can avoid an additional transfer of the pixels, if you are only rendering to a texture for imgui and it isn't needed by your game, but it may probably a bearable cost for flexibility).

**Comment by emoon** [comment]
I realise that I read the question wrong. I though the question was on how to render a UI element in a 3D world. Sorry about the confusion reply then :)

**Comment by tanb0065** [comment]
No problem emoon and thanks for the suggestions ocornut.

I will do offscreen rendering to texture using Frame Buffer Object(FBO) since its much more easier for me. I will close this now.

**Comment by krys-spectralpixel** [comment]
Thanks,

BTW... how to remove a callback ?

There is no "RemoveCallback" method :-(
