### ISSUE TITLE
GIF or MP4 as Embedd in ImGui?

### ISSUE THREAD

**Issue by Baseult** [ocornut/imgui#4751]
Hey, I am currently coding a winrate statistics menu for League of Legends (which got approved) using ImGui over Overwolf and I wonder if it is possible to display a GIF or MP4 on the Menu as a Preview or Usage Tutorial not from File/Memory but from an URL as I want to keep the File as small as possible for now.

You probably would have to use a filestream, downloading the file to tmp and then displaying it as a Texture?

I found a similar question, and I wonder if something since then has changed:
https://github.com/ocornut/imgui/issues/2680

Is it still required to use an additional GIF loader?
Thanks a lot for your work, really appreciate your effort :).

**Comment by ocornut** [comment]
Hello,

> You probably would have to use a filestream, downloading the file to tmp and then displaying it as a Texture?

You could probably do that, but none of that has anything to do with the scope and purpose of Dear ImGui.

> Is it still required to use an additional GIF loader?

If you want to load GIF file in your application you'll need a GIF loader. If you want to play/steam a video you'll need another solution. None of it is related to Dear ImGui so this is the wrong location to ask for support.

Once you have a texture in video memory you can use `ImGui::Image()` (as in this wiki page https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples)
