### ISSUE TITLE
Button on an ImGui Image?

### ISSUE THREAD

**Issue by Baseult** [ocornut/imgui#4752]
Hey, I am able to just draw an image, without any menu using:
"ImGuiWindowFlags_NoTitleBar" and "ImGuiWindowFlags_NoBackground".

And I'm basically trying to use a transparent image as a menu background, on which I can code buttons that are ofc useable.
Would something like that be possible with ImGui?
I haven't found any resources on how to code a Button onto an ImGui Image?

**Comment by ocornut** [comment]
There’s a function called ImageButton() and it is showcased in the Demo.
