### ISSUE TITLE
Begin() after MenuItem() doesn't work 

### ISSUE THREAD

**Issue by pelotyo** [ocornut/imgui#4755]
Hello,I'm very glad for this debug api using in UE4.  But I get some issue calling Begin() after MenuItem().
When I call my specific window the window show up and close quickly and I cant understand why this is happening.
Is there some specific function to keep open my Debug Window? 
`void ADebug_Window::ImGuiTick()
{
	ImGui::BeginMainMenuBar();
	NeptWorld = GetWorld();
	
		if (ImGui::BeginMenu("Parameters"))
		{
			static bool show_DebugWindow = true;
			if (ImGui::MenuItem("Character Param", NULL, &show_DebugWindow))
			{
				ImGui::Begin("Debug Window", &show_DebugWindow);
				return;
			}
			
			ImGui::Text("Test");
			if (show_DebugWindow == false)
			{
				ImGui::End();
			}
			ImGui:: EndMenu();
		}
}`

**Comment by PathogenDavid** [comment]
Your code has quite a few issues, I'd suggest you study the [Dear ImGui demo](https://github.com/ocornut/imgui/blob/4d9a3b19d5e348fafa5f680ffe1e49167b149aa0/imgui_demo.cpp) more thoroughly to improve your understanding of how you're supposed to be using Dear ImGui.

ImGui windows and widgets only exist for as long as you call their function. In your case, `MenuItem` returns true for a single frame so you only show your debug window for a single frame. You need to structure things more like this:

```cpp
void ADebug_Window::ImGuiTick()
{
    static bool show_DebugWindow = true;

    NeptWorld = GetWorld();
    if (ImGui::BeginMainMenuBar())
    {
        if (ImGui::BeginMenu("Parameters"))
        {
            // You don't need to handle the return value from MenuItem here since you're using `show_DebugWindow` for the `p_selected` state.
            ImGui::MenuItem("Character Param", NULL, &show_DebugWindow);
            ImGui:: EndMenu();
        }
        // Your code was missing this call:
        ImGui::EndMainMenuBar();
    }

    if (show_DebugWindow)
    {
        if (ImGui::Begin("Debug Window", &show_DebugWindow))
        {
            ImGui::Text("Test");
        }
        ImGui::End();
    }
}
```

**Comment by ocornut** [comment]
Thank you David! Marked as answered, feel free to ask more if confused.

**Comment by pelotyo** [comment]
Thank you so much for the answer , and I will try to study more deep and add much time in ImGui.
