### ISSUE TITLE
ParentViewportId == 0

### ISSUE THREAD

**Issue by skaarj1989** [ocornut/imgui#4756]
**Version/Branch of Dear ImGui:**

Version: _1.86 WIP 18510_
Branch: _docking_

**My Issue/Question:**

`ParentViewportId` for children windows equals 0 (after migration from `18508`  to `18510`)

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/34756939/143082380-92ccf466-2166-4c02-8a86-312de17e66bb.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Drag a window outside the main viewport window and check `ParentViewportId`

**Comment by ocornut** [comment]
Thanks for reporting.
This was broken by 2080d12bd930124ddaece6f61befe51f47436837 the change of constructor was incorrect was we zero-memset the whole structure. Will fix soon.

**Comment by ocornut** [comment]
> This was broken by 2080d12 the change of constructor was incorrect was we zero-memset the whole structure. Will fix soon.

(Similarly, the default value of `ImGuiWindowClass::DockingAllowUnclassed = true` inside windows got overwritten a while ago with 13258f59 but it didn't have any side-effect because that value is only meaningful when `ClassId != 0` which can only happen with a user overwrite)

**Comment by ocornut** [comment]
Fixed!
