### ISSUE TITLE
Some windows being undocked if the dockspace window is collapsed and we stop drawing previous elements

### ISSUE THREAD

**Issue by sdugloudYBG** [ocornut/imgui#4757]
_**Version/Branch of Dear ImGui:**_
Version: 1.85
Branch: docking

_**Summary:**_
I found a bug in the docking feature of ImGui, regarding the _Dockspace_.
When the dockspace is being hidden but kept alive, it can result in an unwanted undock of one or several windows if we stop submitting elements prior to the collapsed dockspace.
I don't know what would be the right fix for it though... That's why I'm reporting it here, instead of doing a pull request :S .

_**Repro:**_
In my case, I'm submitting a _MainMenuBar_ (which I don't want to be in the main dockspace), then the _Dockspace_ (and its associated window), and finally all my other dockable windows. But sometimes, I'm hidding the _MainMenuBar_ (not submitting it) based on the user needs. 
If I have docked windows in my dockspace, and the dockspace's window is collapsed **before** I stop submitting the _MainMenuBar_, the first submitted docked window is automatically undocked :( .

Here is a stripped-down code example to repro the issue:
```
static bool canDisplayImGuiMainMenuBar = true; // Enable/disable the main menu bar (to repro the bug)
if (ImGui::Button("Toggle main menu bar"))
{
	canDisplayImGuiMainMenuBar = !canDisplayImGuiMainMenuBar;
}

static bool redockAll = false;
redockAll = ImGui::Button("Redock all"); // Simple helper to try it again and again :P

// 1 - Submitting MainMenuBar (only if needed)
if (canDisplayImGuiMainMenuBar && ImGui::BeginMainMenuBar())
{
	// [... Some main menu ImGui code ...]
	ImGui::EndMainMenuBar();
}

// 2 - Submitting the Dockspace and its main window
ImGui::Begin("Dockspace", nullptr, ImGuiWindowFlags_NoDocking);
ImGuiID dockspaceID= ImGui::GetID("MyDockSpace");
ImGui::DockSpace(dockspaceID);

// 3 - Submitting a bunch of dockable windows
ImGui::SetNextWindowDockID(dockspaceID, redockAll ? ImGuiCond_Always : ImGuiCond_FirstUseEver);
ImGui::Begin("Dockable Window 1");
ImGui::End();
ImGui::SetNextWindowDockID(dockspaceID, redockAll ? ImGuiCond_Always : ImGuiCond_FirstUseEver);
ImGui::Begin("Dockable Window 2");
ImGui::End();

ImGui::End(); // Closing Dockspace main window
```
Running this, you simply have to collapse the dockspace with the docked windows, and then click on the "Toggle main menu bar" button to disable the main menu bar. You'll observe the "Dockable Window 1" getting automatically undocked.

In this case, it's only one window that gets undocked, but it can be in fact as many as the number of elements you've submitted prior to the dockspace and that you can stop submitting.
Basically, I can end up with N dockable windows being automatically undocked from my main dockspace, if the main dockspace window is collapsed and I stop submitting N other windows prior to the dockspace (windows that were not meant to be docked anyway - not related to the dockspace).

_**Investigation:**_
The issue seems to be caused by a discrepancy with the dockspace's _BeginOrderWithinContext_.
When the dockspace main window is collapsed, we keep it alive without actually calling the _Begin_ method on it. Its _BeginOrderWithinContext_ then remains the one from the last frame on which it was expanded.
In the example given above, the dockspace _BeginOrderWithinContext_ is 3, and remain 3 when collapsed. 
But the _BeginOrderWithinContext_ of the "Dockable Window 1" is 4 when the dockspace is expanded, 3 when it is collapsed, and 2 when we stop submitting the _MainMenuBar_.
As it become smaller than the _BeginOrderWithinContext_ of the dockspace, we undock it, as we suppose we've "submitted [it] earlier than the host window" (cf. in method _ImGui::BeginDocked_).

_**Workaround:**_
The workaround is to submit the dockspace window as early as possible. Not only before any window they can host (as recommended in the demo), but before any "dynamic" elements, even if they can't be docked.
This will ensure the _BeginOrderWithinContext_ of the dockspace to stay smaller than any other _BeginOrderWithinContext_ of any windows, even if the dockspace is kept alive while hidden and therefore not having its _BeginOrderWithinContext_ properly updated.

_______________________________
I hope this wall of text will help investigate and fix this issue, or at least provide a workaround to my fellow Dear ImGui users. 
Thanks for reading me that far ! XD

**Comment by ocornut** [comment]
Thank you for the bug report and great investigation!

In this a bit of an intricate issue, but mostly it is surprising that it hasn't manifested before... The reason is that because we encourage/require user-created dockspace to be submitted before other windows, in most situations there are no windows altering their visibility submitted before and somehow we never discovered this bug before. Thanks for stumbling on it :)

Code in `Begin()->BeginDocked()` does:
```cpp
// Undock if we are submitted earlier than the host window
if (window->BeginOrderWithinContext < node->HostWindow->BeginOrderWithinContext)
{
    DockContextProcessUndockWindow(ctx, window);
    return;
}
```
Shortly followed by:
```cpp
if (node->MergedFlags & ImGuiDockNodeFlags_KeepAliveOnly)
    return;
```
I think it is incorrect for us to read from `node->HostWindow` if `ImGuiDockNodeFlags_KeepAliveOnly` is set so I fixed it by using:

```cpp
// Undock if we are submitted earlier than the host window
if (!(node->MergedFlags & ImGuiDockNodeFlags_KeepAliveOnly) && window->BeginOrderWithinContext < node->HostWindow->BeginOrderWithinContext)
{
    DockContextProcessUndockWindow(ctx, window);
    return;
}
```

Pushed fix as 719d9313 !
