### ISSUE TITLE
example_win32_directx9.exe detected  as vírus.

### ISSUE THREAD

**Issue by Rs021** [ocornut/imgui#4760]
Version: 1.85
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: win32_directx9
Compiler: Visual Studio 2019 (MSVC 19)
Operating System: Windows 10 PRO

My Issue/Question:

I compiled the example and it was detected as a virus, will it be a false positive?

SHA256 master: B4B8D729246CC3D91640193931CDCCF6EF296DEE196824799E67E9005A4AED04

![Sem título](https://user-images.githubusercontent.com/75760003/143314646-50c8187e-0d19-4742-abda-1f2e009afbc1.png)

**Comment by ocornut** [comment]
> I compiled the example and it was detected as a virus,

As you said you compiled on your PC, if there is a virus it comes from your machine. Hope you get it fixed!

**Comment by Rs021** [comment]
I have antivirus
