### ISSUE TITLE
ImGuiInputTextCallback: NULL buffer when ReadOnly

### ISSUE THREAD

**Issue by actondev** [ocornut/imgui#4762]
Version: v1.85
Branch: master

When passing the ImGuiInputTextFlags_ReadOnly to InputText, the `callback_data.Buf` is null. Meanwhile, `BufTextLen` is (correctly) the text length.

Something like
```diff
                     callback_data.EventKey = event_key;
-                    callback_data.Buf = state->TextA.Data;
+                    callback_data.Buf = state->TextAIsValid ? state->TextA.Data : state->InitialTextA.Data;
                     callback_data.BufTextLen = state->CurLenA;
```
seems to be semantically correct, but then
```c++
IM_ASSERT(callback_data.Buf == state->TextA.Data);
```
will fail

**Comment by ocornut** [comment]
Thank you! Pushed a fix 5ac25e7c7a8f244f84b935ea5a5f69b67b72b6f4
