### ISSUE TITLE
DX11 texture mipmaps are disabled

### ISSUE THREAD

**Issue by Looyh** [ocornut/imgui#4764]
Back-ends: imgui_impl_dx11.cpp

**My Issue/Question:**

Hello,
In the function `ImGui_ImplDX11_SetupRenderState`, `bd->pFontSampler` is used for the sampler. But `desc.MaxLOD` is set to zero when creating the FontSampler. That disabled mipmaps for textures.

**Comment by rokups** [comment]
UI does not need mipmaps. Also previous sampler is backed up and restored after rendering. You should describe your problem more thoroughly and include a minimal code sample that reproduces the issue.

**Comment by ocornut** [comment]
I guess the underlying suggestion is, if you use eg Image() calls you may want mipmaps on your own textures without. Would there be any side-effect/issue on the UI of settings MaxLOD to a more reasonable “default” ?

**Comment by Looyh** [comment]
@ocornut Thanks for the reply. 
I used dds(and down scalcing) in the UI(DrawList image), and changed MaxLOD to D3D11_FLOAT32_MAX, it works fine. It does not affect textures that do not have mipmaps.
