### ISSUE TITLE
Undefined Behavior in the way widgets like ColorEdit4 interact with structs like ImVec4

### ISSUE THREAD

**Issue by thacks42** [ocornut/imgui#4765]
**Version/Branch of Dear ImGui:**

All

**My Issue/Question:**

a struct like ImVec4 looks like this:
```cpp
struct ImVec4{
  float x,y,z,w;
};
```

Which means that it does *not* contain an *array* of floats but rather 4 individual scalar objects of type float.
Widgets like ColorEdit4 (as used in the example code) take a pointer to a float and then continue to treat it as an array of size 4.
In particular they do operations like:

```cpp
ImGui::ColorEdit4(const char* label, float col[4], ImGuiColorEditFlags flags){
...
    float f[4] = { col[0], col[1], col[2], alpha ? col[3] : 1.0f };
...
````

here `col` is treated as if it were an array of size 4. However However if `col` points to a single float (in this case the first float in a struct of 4 floats), then pointer arithmetic such as `col[2]` is UB according to the C++ standard.

To solve this we need either a version of all widgets like `ColorEdit4` that take a pointer/reference to a struct of type `ImVec4` to be able to do proper accessing of struct members, or change structs like `ImVec4` to contain an array of floats instead of individual scalars.
One other method to solve this might be to invoke `memcpy` to copy the content of the struct into a local array on which pointer arithmetic is then again well defined.

**Comment by ocornut** [comment]
The layout of contiguous floats matches an array of floats. It works and I’m not interested in arguing with language lawyers about it.

However if you need like adding extra functions in your codebase nothing prevents you from doing so (you can add new functions in the ImGui:: namespaces).

**Comment by ocornut** [comment]
Closing this as fro my POV there’s nothing to fix. If you don’t trust that kind of evident, established behavior, I suggest you shouldn’t trust and use dear imgui.
