### ISSUE TITLE
CalcTextSize can produce a segfault

### ISSUE THREAD

**Issue by bit9tream** [ocornut/imgui#4769]
```
Dear ImGui 1.86 WIP (18511)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=11
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1920.00,1052.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.85
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: g++ 11.2.0
Operating System: gentoo

**My Issue/Question:**

Calling `CalcTextSize` like `ImGui::CalcTextSize("");` produces segfault, but calling it like `ImGui::CalcTextSize("", nullptr, true);` wont segfault.
String content doesn't affect presence of the error.

There is also what gdb says about that:
```
Thread 1 "finally" received signal SIGSEGV, Segmentation fault.
0x00005555555b9232 in ImFont::CalcTextSizeA (this=0x0, size=0, max_width=3.40282347e+38, wrap_width=-1, text_begin=0x55555562807d "", text_end=0x55555562807d "", remaining=0x0) at imgui/imgui_draw.cpp:3432
3432	    const float scale = size / FontSize;
```

**Comment by bit9tream** [comment]
Would like to add, that I'm calling `CalcTextSize` function after ImGui is initialized, just before the event loop.

Also, turned out that it doesn't segfault for me only when `hide_text_after_double_hash` is true and provided string is empty. Sorry for not including that in the original issue message.

But there is a gdb trace of segfault caused by `ImGui::CalcTextSize("asdf", nullptr, true);`
```
Thread 1 "finally" received signal SIGSEGV, Segmentation fault.
0x00005555555b9232 in ImFont::CalcTextSizeA (this=0x0, size=0, max_width=3.40282347e+38, wrap_width=-1, text_begin=0x55555562807d "asdf", text_end=0x555555628081 "", remaining=0x0) at imgui/imgui_draw.cpp:3432
3432	    const float scale = size / FontSize;
```

**Comment by thedmd** [comment]
Please check if font atlas is generated. If you do not do that by yourself atlas if generation is triggered by the backend while creating font atlas texture via `ImFontAtlas::GetTexDataAsXXX` call. This is probably after your call to `ImGui::CalcTextSize()`. Please call `ImFontAtlas::Build()` before calling text related functions before first frame.

**Comment by bit9tream** [comment]
Oh, thanks. But I cannot figure out how exactly I need to call `ImFontAtlas::Build()`.
Just doing `ImGui::GetIO().Fonts->Build();` doesn't seem to help.

**Comment by ocornut** [comment]
You may be simply missing a call to NewFrame(), it looks like the current font pointer is never set. A fuller repro would be helpful.

**Comment by bit9tream** [comment]
Yeah, if I put everything after a `NewFrame` call it works fine. Just don't want to recalculate the dimensions on every frame.
I guess I can just make a boolean indicator if it was already calculated or not. ¯\_(ツ)_/¯
