### ISSUE TITLE
Unable to pass two objects to ImDrawList::AddCallback()

### ISSUE THREAD

**Issue by h4k1m0u** [ocornut/imgui#4770]
As a follow-up to #4748, I've managed to use a custom shader to set a rectangle to a different color as explained in the example shown in #4174. While doing this I've sent my shader class instance as a 2nd argument to `ImDrawList::AddCallback()` and it worked fine.

Now I also want to send the texture to the same method in order to modify it. However, when I combine the shader program instance and the texture either in the same `struct` or in an `std::pair` and set AddCallback's 2nd argument to a pointer to this structure, I get a segmentation fault. I verified inside the lambda function that neither the program nor the texture were set (their ids were random), which wasn't the case when only the program shader instance was sent to the lambda function (via AddCallback).

Anyone familiar with `ImDrawList` has an explanation for why only a single variable could be sent as AddCallback's first argument? or maybe I should proceed differently?

```cpp
  auto callback_data = std::make_pair(&m_program, &m_texture);

  ImDrawList* draw_list = ImGui::GetWindowDrawList();
  draw_list->AddCallback([](const ImDrawList* parent_list, const ImDrawCmd* cmd) {
    // function pointer based on lambda fct cannot capture variables (passed as arg below)
    auto* callback_data = static_cast<std::pair<Program*, Texture2D*> *>(cmd->UserCallbackData);
    Program* program = callback_data->first;
    Texture2D* texture = callback_data->second;
    std::cout << "texture: " << callback_data->second->id << '\n';

    // projection matrix from viewport size (`GetDrawData()`: what to render)
    ImDrawData* draw_data = ImGui::GetDrawData();
    ImVec2 position = draw_data->DisplayPos;
    ImVec2 size = draw_data->DisplaySize;
    glm::mat4 projection2d = glm::ortho(0.0f, size.x, 0.0f, size.y);
    std::cout << "position: " << position.x << " " << position.y << '\n';
    std::cout << "size: " << size.x << " " << size.y << '\n';

    // pass shaders uniforms
    Uniforms uniforms = {
      {"ProjMtx", projection2d},
      {"texture", *texture}
    };
    program->use();
    program->set_uniforms(uniforms);
  }, &callback_data);
  // }, &m_program);
```

**Comment by PathogenDavid** [comment]
Your `std::pair` is allocated on the stack, so by the time the callback is executed it has been deallocated and replaced with garbage. You need to store the pair somewhere that's longer lived.

**Comment by h4k1m0u** [comment]
I think you were right, I've only had to put the callback in a static class method and the `AddCallback()` call (with the callback_data) in the same block and before `ImGui::Render()` for it to work.

**Comment by ocornut** [comment]
Usually you’d want to store your own data stream to carry data required by callbacks, and then in the callback you may only store e.g an index/offset into that stream.
I suppose it may be helpful to add an opaque user data only ImVector inside ImDrawList instances to made it easier (been asked for that before).

**Comment by h4k1m0u** [comment]
Now that I think about it, I could've sent directly the id of the shader and that of the texture (not sure if it would've made a difference). I'm just too lazy to memorize opengl functions, that's why I prefer to use my own wrapper classes.

**Comment by ocornut** [comment]
FYI this has been simplified with 98d52b7, `AddCallback()` now supports passing any amount of data that will be copied internally inside a buffer inside DrawList. This should make it easier to use callback for variety of usages.
