### ISSUE TITLE
Keyboard state example picks up keyboard keys but any other key input areas don't?

### ISSUE THREAD

**Issue by vexe** [ocornut/imgui#478]
I'm in a weird situation where I managed to get the example window compiling and running in my engine. 

In the "Keyboard, Mouse and Focus" section of the example, it seems that it picks up the keys I press. But when I try to input something in the Console, or a Filter it doesn't pick my keys.

This is a video demonstrating the issue: https://youtu.be/qEbzvgIiM5k

Basically input is detected in the platform layer and gets passed to the game as a key_state Keys[256] where key_state is an enum whether the key is down for a single frame, up for a single frame, held or none.

This is how I setup a new frame:

    void ImguiNewFrame(r32 DeltaTime, game_input *Input)
    {
        ImGuiIO& io = ImGui::GetIO();
        io.DeltaTime = DeltaTime;

        ForCount(256)
            io.KeysDown[i] = Input->Keys[i] == Key_Held || Input->Keys[i] == Key_Down;
    
        io.KeyCtrl = KeyHeld(KEY_CTRL);
        io.KeyShift = KeyHeld(KEY_SHIFT);
        io.MousePos = ImVec2(Input->Mouse.X, Input->Mouse.Y);
        io.MouseDown[0] = Input->Mouse.Left == Key_Down || Input->Mouse.Left == Key_Held;
        io.MouseDown[1] = Input->Mouse.Right == Key_Down || Input->Mouse.Right == Key_Held;

        ImGui::NewFrame();
    }

I have no idea what I'm missing or doing wrong.

Any help is appreciated, thanks
vexe

**Comment by ocornut** [comment]
You aren't passing character inputs via `io.AddInputCharacter`
Keys inputs are just raw characters keys and can't be easily and reliably translated into text.
Character inputs is localized text, taking account of keyboard layout, language and input method editor. Your OS or platform layer can typically provide them to you. (e.g. WM_CHAR under Windows).

**Comment by vexe** [comment]
It doesn't seem that I'm getting the WM_CHAR callback for some reason. So I'm using MapVirtualKey in the WM_KEYXXX and WM_SYSKEYXXX events. But with that I always get upper case characters and 'lower' punctuation/numbers i.e. '4' instead of '$'. Not sure how to handle that properly. I mean I can see if the key is alpha then add 32 to it if the shift key is not pressed, but this just feels like I'm missing a built-in function for this...

**Comment by ocornut** [comment]
Solve the real problem that you have instead of solving some scaffolding-workaround. The problem that you have is that you don't seem to get WM_CHAR.

They are being generated by the window message handler from a WM_KEYDOWN messages, so on WM_KEYDOWN you are supposed to call the default windows handler as well. See code in the dirextx example. (At this point it's not an ImGui issue)

**Comment by vexe** [comment]
Thank you very much. I had to call TranslateMessage and DispatchMessage in the WM_KEYXXX case then WM_CHAR got called.

**Comment by ocornut** [comment]
Nice!
