### ISSUE TITLE
Crash on Tables with child windows inside when window is very small

### ISSUE THREAD

**Issue by OriolCS2** [ocornut/imgui#4781]
Version: 1.83 (https://github.com/ocornut/imgui/releases/tag/v1.83)

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Operating System: Windows 10 pro

Hello, I think I have found a crash when using tables that contain two child windows inside.

https://user-images.githubusercontent.com/36154523/144672469-4b37e7b3-886d-4ee8-ba9c-cf6d1120c0e8.mp4

I attach the code of that window, I hope it helps to understand what is happening.

`    

    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0F, -2.0F));
    if (ImGui::Begin(panel_name.data(), &enabled, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse)) {

        ImGui::PushStyleVar(ImGuiStyleVar_CellPadding, ImVec2(0.0F, ImGui::GetStyle().CellPadding.y));

        if (ImGui::BeginTable("AnimationTimelineTable", 2, ImGuiTableFlags_Resizable)) {

            ImGui::TableSetupColumn("Properties", ImGuiTableColumnFlags_WidthStretch, 100.0F);
            ImGui::TableSetupColumn("Timeline", ImGuiTableColumnFlags_WidthStretch, 300.0F);

            ImGui::TableNextRow();
            ImGui::TableNextColumn();

            if (ImGui::BeginChild("Properties Root", ImVec2(), false, ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse | ImGuiWindowFlags_MenuBar)) {

                if (ImGui::BeginChild("Properties Data", ImVec2(), false, ImGuiWindowFlags_MenuBar)) {
                    ImGui::EndChild();
                }

                ImGui::EndChild();
            }
            ImGui::TableNextColumn();

            if (ImGui::BeginChild("AnimationTimeline Root", ImVec2(), false, ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse | ImGuiWindowFlags_MenuBar)) {

                if (ImGui::BeginChild("AnimationTimeline Data", ImVec2(), false, ImGuiWindowFlags_MenuBar)) {
                    ImGui::EndChild();
                }

                ImGui::EndChild();
            }

            ImGui::EndTable();
        }

        ImGui::PopStyleVar();
        ImGui::End();
    }
    ImGui::PopStyleVar();`

**Comment by ocornut** [comment]
Begin/End and BeginChild/EndChild are currently inconsistent with others functions and are misused in your code.

**Comment by OriolCS2** [comment]
Oh you are right, ImGui::End/EndChild() must be called always. So problem is fixed now, thanks!
