### ISSUE TITLE
How could I draw an Overlay with a Hidden Background?

### ISSUE THREAD

**Issue by YoAvrageBiTz** [ocornut/imgui#4782]
Hello, I am on Visual Studio 2019, and I am using Windows 10 64bit. 
I am coming here because I want to make a cross-hair for Escape From Tarkov, basically my goal is to get a simple window drawing with color options to allow for customization (example below)
![crosshairWindow](https://user-images.githubusercontent.com/72582558/144696243-4154c4f7-5cd5-45e1-9a32-df20ad413bed.PNG)

This works, and properly and can change the color of the rendered circle in the middle. My only issue now is that when I go to create the actual rendering window that just draws a single circle, I use "ImGuiWindowFlags_NoBackground" and it still just comes up completely black all the way around. I don't know if there is a better way to do this to actually make it invisible but it would help a ton.
(example of the backed out window)
![Capture](https://user-images.githubusercontent.com/72582558/144696452-3b6871b5-3181-4801-8b47-bc13b0325710.PNG)

This is the code I am using for drawing the circle, 

```
ImGui::Begin("CrosshairTest", 0, ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoInputs |  ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus);
{
     ImGui::SetWindowSize(ImVec2(1920, 1080), 0);
     ImGui::SetWindowPos(ImVec2(0, 0));

     auto draw = ImGui::GetBackgroundDrawList();
     draw->AddCircle(ImVec2(960, 540), 5, IM_COL32(255, 255, 255, 255), 100, 2.f);
}
```

Any help is much appreciated!
Edit: I think I'm on ImGui Version 1.80 "https://github.com/ocornut/imgui/releases/tag/v1.80"

**Comment by lukaasm** [comment]
Before ImGui::Begin, call:

`ImGui::SetNextWindowAlpha(` 0.0f )``

**Comment by YoAvrageBiTz** [comment]
> re

I don't seem to have this, I do however have `ImGui::SetNextWindowBgAlpha(0.0f);` but it does not seem to work. Maybe I need to update it or I could just add this call specifically to ImGui, or I am still doing it wrong.

**Comment by ocornut** [comment]
- _NoBackground should have same effect as `SetNextWindowBgAlpha(0.0f)` while also removing outer borders.
- You are drawing on `ImGui::GetBackgroundDrawList()` so that has nothing to do with the current window you are creating anyway.
- The fact that things are black comes from another element which you have omitted in your report.
- Sorry but #1586

**Comment by Old-Executor** [comment]
ImGui::Begin("##Master Dream", nullptr, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoScrollbar);

		auto draw = ImGui::GetBackgroundDrawList();
		draw->AddCircle(ImVec2(1920 / 2, 1080 / 2), Misc::sizef, Misc::FovColor, 100, 1.0f);

		ImGui::End();
