### ISSUE TITLE
How to make a primitive drawn on top of an image scroll with the image

### ISSUE THREAD

**Issue by Oudalally** [ocornut/imgui#4789]
Version: 1.85 WIP (18412)
Branch: Docking
Back-ends: imgui_impl_glfw, imgui_impl_opengl3
GLFW Version : GLFW 3.3
Operating System: Windows 10

Hello.

I'm trying to build a component which will draw an image, and render primitive rects over the top of it. 
This component will be part of a tool for viewing OCR data, and the rects will correspond to detected regions within the image. 
I am able to draw the rect initially onto the image, and the rect moves correctly when I draw the window, however when scrolling the image, the rect does not scroll relative to the image, rather the image scrolls underneath it.

I have tried a number of approaches, but I'm not sure what the best approach to this is.

Currently, I'm toying with either getting the rendered position of the viewport for the image, and drawing the rect relative to the position of that viewport, though I am deeply confused as to how to go about it.

I'm coming to this project from working with retained mode UI's, and my thought process was that if I could draw the primitive within the region, it would scroll with the other items in the region - this is clearly the wrong way to solve the problem, but I just can't see the solution. I've been through the examples for several days, but I cannot find one which has helped narrow this down - my apologies if there is one and I've just missed it.

I'd be grateful for any help anybody can offer, even if it's just pointing me to a pertinent example which I've missed.
Many thanks

https://user-images.githubusercontent.com/95626562/144852715-79ed9411-0a05-4e9c-861a-4e15add5c439.mov

```
ImGui::BeginChild("##scrolling", regionSize, false, ImGuiWindowFlags_HorizontalScrollbar);

int index = 1;
ImGui::PushID(index);

//NB. scaledImageSize is an ImVec2 calculated based on the size of the region
//which is read from ImGui::GetContentRegionAvail();
//TextureMeta is just a basic struct - glTextureRef is just a GLuint which in this case, returns 1 as I've only got one image loaded
ImGui::Image((void*)(intptr_t)TextureMeta.glTextureRef, scaledImageSize);
ImGui::PopID();

ImVec2 rectTopleft = { 10, -100 };
ImVec2 rectDimensions = { 300, 300 };

rectTopleft.x += ImGui::GetWindowPos().x;
rectTopleft.y += ImGui::GetWindowPos().y;
rectDimensions.x += ImGui::GetWindowPos().x;
rectDimensions.y += ImGui::GetWindowPos().y;

ImDrawList* drawList = ImGui::GetWindowDrawList();
drawList->AddRect(rectTopleft, rectDimensions, 0xFF0000FF, 4.0f);

ImGui::EndChild();
```

**Comment by Oudalally** [comment]
Oh wow!! Thank you @youneuoy - that's a massive help!!!!
I'll give it a try shortly. 
It looks like such an obvious solution reading it now, and I just couldn't see it!

**Comment by ocornut** [comment]
You should not have to worry about scrolling at all.

You can simply call `ImGui::GetCursorScreenPos()` before `ImGui::Image()` 
Or `ImGui::GetItemRectMin()/GetItemRectMax()` after `ImGui::Image()`.

**Comment by Oudalally** [comment]
I've only just got back in, so I'll get a solution coded up now.
Thank you, I've been trying to work this out for days and I just wasn't getting any closer!
I'll go with the `ImGui::GetCursorScreenPos() ` approach for tidiness to get my offsets. 
Many thanks for such a quick reply!
