### ISSUE TITLE
Modals backgrounds are transparent

### ISSUE THREAD

**Issue by bertrandboudaud** [ocornut/imgui#4790]
Dear ImGui team,

When running ShowDemoWindow, the modal dialog boxes background is transparent.

![image](https://user-images.githubusercontent.com/1705849/145047043-b4dcfcd3-b872-4cb3-825a-7157867b369d.png)

While the window on the background should be "transparent", and the modal opaque, like previously:

![image](https://user-images.githubusercontent.com/1705849/145047418-1963873f-20d6-4ae2-92b6-a59acdf01015.png)

I tried different commits in the master, and it seems the difference comes from this commit:
[23ef6c149ea14d8a5981cfec02994dcd7d21d09e](https://github.com/ocornut/imgui/commit/23ef6c149ea14d8a5981cfec02994dcd7d21d09e)

(I detected first the issue on the Docking branch)

```
Dear ImGui 1.86 WIP (18514)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=201703
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl2
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Comment by bertrandboudaud** [comment]
Hello, 

I am still getting the problem with the latest commit on master.

So if you cannot reproduce it, could be a setup issue on our side (I am running the demo inside our application, which I had however made as much as possible empty, but still there can be some code from us that leads to that defect).

We can close that and I will come back if I can identify something that would need your feedback.
thanks,

**Comment by ocornut** [comment]
We touched this code only a few days ago so it is likely we added a bug. One of the thing it does may have effects on some / not all backends, i’ll be testing this with your backend.

**Comment by ocornut** [comment]
Interestingly, this was a bug in the OpenGL2 backend: c80e8b9
The bug never had any visible impact before the change we just made to dimming code.
You can update or cherry-pick that commit to get the fix!

**Comment by Markot140415** [comment]
> Dear ImGui team,
> 
> 
> When running ShowDemoWindow, the modal dialog boxes background is transparent.
> 
> ![image](https://user-images.githubusercontent.com/1705849/145047043-b4dcfcd3-b872-4cb3-825a-7157867b369d.png)
> 
> While the window on the background should be "transparent", and the modal opaque, like previously:
> 
> ![image](https://user-images.githubusercontent.com/1705849/145047418-1963873f-20d6-4ae2-92b6-a59acdf01015.png)
> 
> I tried different commits in the master, and it seems the difference comes from this commit:
> [23ef6c149ea14d8a5981cfec02994dcd7d21d09e](https://github.com/ocornut/imgui/commit/23ef6c149ea14d8a5981cfec02994dcd7d21d09e)
> 
> (I detected first the issue on the Docking branch)
> 
> ```
> Dear ImGui 1.86 WIP (18514)
> --------------------------------
> sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
> define: __cplusplus=199711
> define: _WIN32
> define: _WIN64
> define: _MSC_VER=1929
> define: _MSVC_LANG=201703
> --------------------------------
> io.BackendPlatformName: imgui_impl_sdl
> io.BackendRendererName: imgui_impl_opengl2
> io.ConfigFlags: 0x00000000
> io.ConfigInputTextCursorBlink
> io.ConfigWindowsResizeFromEdges
> io.ConfigMemoryCompactTimer = 60.0
> io.BackendFlags: 0x00000006
>  HasMouseCursors
>  HasSetMousePos
> --------------------------------
> io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
> io.DisplaySize: 1280.00,720.00
> io.DisplayFramebufferScale: 1.00,1.00
> --------------------------------
> style.WindowPadding: 8.00,8.00
> style.WindowBorderSize: 1.00
> style.FramePadding: 4.00,3.00
> style.FrameRounding: 0.00
> style.FrameBorderSize: 0.00
> style.ItemSpacing: 8.00,4.00
> style.ItemInnerSpacing: 4.00,4.00
> ```
> 
>
