### ISSUE TITLE
[Feature request] External library

### ISSUE THREAD

**Issue by jackghg** [ocornut/imgui#4793]
Ok imgui should be integrated in my app, but wouldn't be great to have it as an external library too ?

**Comment by ocornut** [comment]
You can create a library yourself out of any source files.

**Comment by jackghg** [comment]
I mean one official library, like gtk

**Comment by ocornut** [comment]
Basically it means providing build scripts for a given build system, which we don’t because we are intentionally build-system agnostic. So the answer is no.

**Comment by jackghg** [comment]
this is not great.

**Comment by ocornut** [comment]
Sorry i have no energy to explain why this isn’t a good idea. I’ll close this issue. You can create libraries in your ide or build system.
