### ISSUE TITLE
Enabling "FrameBorder" causes multi-line text input to be offset from mouse clicks

### ISSUE THREAD

**Issue by dbr** [ocornut/imgui#4794]
**Version/Branch of Dear ImGui:**

Master branch, b0361375eeb25c37c548abcbca1f500edea6fe90 - also on 1.85 release

**Back-end/Renderer/Compiler/OS**

Back-ends: `example_glut_opengl2` and also the imgui-rs bindings using imgui-glow-renderer
Compiler: N/a
Operating System: Linux

**My Issue/Question:**

When toggling the "FrameBorder" option at the top of the Style Editor, the contents of the "Widgets > Text input > Multi-line Text Input" jumps around:

![toggling_moves_text](https://user-images.githubusercontent.com/509/145310266-3a10dac5-8359-4c5c-8911-1a91d28bb289.gif)

I've increased "window padding" to a larger value to make the issue more obvious, but it still happens with everything at default sizes.

This alone isn't a big problem, but when enabled the mouse clicks are offset the window padding amount:

![misaligned](https://user-images.githubusercontent.com/509/145310389-ff8613aa-8ec0-4fe7-a272-9bf15dbbda0a.gif)

**Screenshots/Video**
Included above.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Reproducible with `cd imgui/examples/example_glut_opengl2 && make && ./example_glut_opengl2`

**Comment by ocornut** [comment]
Confirmed and broken by d1a9efdd8f90b09df1ae380403992e8a997f7ede

**Comment by ocornut** [comment]
Fixed by 072caa4
