### ISSUE TITLE
Assertion failed for InputText without label

### ISSUE THREAD

**Issue by neclepsio** [ocornut/imgui#4796]
**Version/Branch of Dear ImGui:**

Version: 1.85
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw3.cpp + imgui_impl_opengl.cpp
Compiler: gcc
Operating System: Windows

**My Issue/Question:**

With the following example, as soon as I click on the InputText, I get this assertion failed:

    Assertion failed: mouse_button >= 0 && mouse_button < ImGuiMouseButton_COUNT, file ../../imgui_widgets.cpp, line 624

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

I modified example_glfw_opengl3 to add the following code before `ImGui::End()`. 

```
static char* text = 0;
if (text == 0) {
    text = new char[100];
    text[0] = 0;
}
ImGui::InputText("", text, 100);
```

**Comment by ocornut** [comment]
Please read the FAQ about how identifiers work.

**Comment by neclepsio** [comment]
Thank you for your prompt reply. I'm so sorry I made a stupid mistake like this, after having used this library for a long time. At least, if anyone makes the same mistake, they will find this issue now while searching for this assertion.

**Comment by ocornut** [comment]
> they will find this issue now while searching for this assertion.

This is the same as #2562, #2807, #4008, #4158, #4375, #4548, #4657 and maybe others.

It happens because:
- this is error prone
- people don't read the FAQ and don't understand how the ID Stack and ## operator works.

**I should have solved this earlier. I am now pushing a change to assert in that condition.**

I am now adding in `ItemAdd()`
```cpp
// [DEBUG] People keep stumbling on this problem and using "" as identifier in the root of a window instead of "##something". READ THE FAQ: https://dearimgui.org/faq
// Empty identifier are valid and useful in a small amount of cases, but 99.9% of the time you want to use "##something". READ THE FAQ: https://dearimgui.org/faq
IM_ASSERT(id != window->ID && "Cannot have an empty ID at the root of a window. If you need an empty label, use ## and read the FAQ about how the ID Stack works!");
```

Yay!

**Comment by neclepsio** [comment]
Usually I had collisions which result in a bad behavior, e.g. not being able to receive events; this was the first time I had a seemingly unrelated assertion fail. What surprises me is that #4008 is exactly the same error as mine, but google search only pointed me to the source code. My bad, next time I will search the issues in github. Thank you very much for the fix!
