### ISSUE TITLE
What is the most efficient way to color the underside of a curve in a custom widget?

### ISSUE THREAD

**Issue by AlexandreRouma** [ocornut/imgui#4798]
**Version/Branch of Dear ImGui:**

Version: 1.83
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

**My Issue/Question:**

I have a custom plotting widget (big simplification but it doesn't matter for this) that colors the under side of the plotted curve (for aesthetic reasons). Currently I'm drawing a vertical line for each pixel of the graph which is horrible....
Is there any more efficient way to do this without having to resort to custom shaders and such (aka I wanna stick to included functions as much as possible, especially since I don't want it to be backend dependent)?

**Comment by ocornut** [comment]
It would be helpful to share a screenshot so we can understand what it looks like, the scale and look of things in context. Hard to guess right now.

**Comment by AlexandreRouma** [comment]
this is the part of the widget in question. It plots the spectrum of a radio signal.
Here are a few screenshots of how the plot looks. First one doesn't have much of an area under the curve:
![image](https://user-images.githubusercontent.com/17126412/145577238-9305a85f-9c2a-4cc6-ada2-912117b16711.png)
But a lot of times it can have quite a large area:
![image](https://user-images.githubusercontent.com/17126412/145577356-7a5900c6-d3d2-41a3-ae07-6ac9f5a19bd8.png)

**Comment by ocornut** [comment]
You can go lower level and batch reserve submit vertices without calling AddRectFilled() it’ll be faster.
But otherwise it’s probably viable to create a texture and upload it in a backend compatible format.

**Comment by AlexandreRouma** [comment]
hmm, I'm not sure a texture would be more efficient than I'm doing now considering I'd have to generate it every frame on the CPU.

How can I submit vertices? is there a way to have only the top verticies (aka the plot) colored bright blue (see first screenshot). The sides and the bottom must stay uncolored.

**Comment by ocornut** [comment]
You have all the code at your disposal to study. This is too much of an open-ended question and we don't know what your code looks it.

I was just suggesting to look at what `AddRectFilled()` does and do things manually and in a batched way to do exactly what you need aka probably just call `PrimReserve()` once and then `PrimRect()` multiple time, or even inline it.
No magic here, it's not going to be free. 
You may also look at ImPlot source code for ideas.
