### ISSUE TITLE
Clicking on an InputFloat gives focus to InputText as well?

### ISSUE THREAD

**Issue by vexe** [ocornut/imgui#480]
Greetings!

I'm having a weird situation where I have an InputFloat and an InputText, if I give focus to the InputFloat, the InputText field gets focus too with the same value as in the InputFloat field!

Video demonstrating the issue and showing the code I'm using: https://youtu.be/DLK8VKl5IA0

Why is this happening? Pretty sure I'm missing something obvious...

Thanks
-vexe

EDIT: Interestingly, it's only the scale field that's buggy, the InputFloat3 for the position is working fine, (doesn't give focus to InputText)

**Comment by vexe** [comment]
Beginner mistake since I'm new to your framework. It seems that you're using the 'label' that gets passed to InputXXX as a hash value? Giving InputText a value for its label the issue is no longer. It would be nice if the label was positioned to the left instead of the right. There's probably a way to do that just have to dig in.

**Comment by vexe** [comment]
Is there anyway to give custom values to the hashes? For example, I have a ImGui::Text with value "Reset" and 3 buttons beside it on the same line "Position", "Rotation" and "Scale" (they reset the position, rotation or scale of the selected object etc)

And then at the bottom, I have an InputFloat with label "Scale" - now I have two controls with the same label (thus the same hash?), the "Scale" Button and InputFloat. If I give focus to the InputFloat, it unfocuses immediately. Unless I give them different labels e.g. "Reset Scale" and "Scale"

**Comment by nem0** [comment]
From docs:

```
 When passing a label you can optionally specify extra unique ID information within string itself. This helps solving the simpler collision cases.
     use "##" to pass a complement to the ID that won't be visible to the end-user:
       Button("Play");         // Label = "Play",   ID = hash of "Play"
       Button("Play##foo1");   // Label = "Play",   ID = hash of "Play##foo1" (different from above)
       Button("Play##foo2");   // Label = "Play",   ID = hash of "Play##foo2" (different from above)
```

**Comment by ocornut** [comment]
This is all discussed in the FAQ.
