### ISSUE TITLE
Error C2065" g_pd3dDevice  undeclared identifier "

### ISSUE THREAD

**Issue by KinGh2** [ocornut/imgui#4806]
The truth is, I did not know the solution to this problem. Is there anyone who can offer any solution to it?
![image](https://user-images.githubusercontent.com/55319853/145922030-83af8e0a-c263-41cf-a331-241ca49ce7c8.png)

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by IamZiroToxic** [comment]
@KinGh2 Hey <3 did you find to how to solve it?

**Comment by exebyt3** [comment]
> Sorry but #1586

ur so sigma
