### ISSUE TITLE
How to get the client area rect coordinates/size from the docking windows system ?

### ISSUE THREAD

**Issue by nekitu** [ocornut/imgui#4808]
I need to render things inside the client area, the empty area of the docking windowing system (middle).
So I need to get the rectangle coordinates and size.
Anyone knows how ? thanks

**Comment by ocornut** [comment]
See #4102
But most often when you are asking this question you are asking the wrong question and you should use `ImGui::Image()` and dock a window here.

Please read Issue Submitting Guidelines and Glossary (https://github.com/ocornut/imgui/wiki/Glossary) for further questions.

**Comment by nekitu** [comment]
No need (cannot) to use `Image` to render the scene into it, its fine that all UI is overlaid on the whole scene. Thanks, didnt know about the glossary, kind of tucked in the wiki :)
