### ISSUE TITLE
Ability to convert Imgui plots into an RGB image?

### ISSUE THREAD

**Issue by NathanBWaters** [ocornut/imgui#4809]
**My Question:**

My team and I love imgui + Implot for visualizing our SLAM engine.

![image](https://user-images.githubusercontent.com/4016602/146100930-94407d30-7864-49ce-b8b1-357a4d5da177.png)

However, we have another tool that compares that same sequence using different hyperparameters and combines them all into a single video.  Here's a 2x2 example:

![image](https://user-images.githubusercontent.com/4016602/146101007-9c092cf5-8884-4efa-8941-5eadfc696bd7.png)

We were wondering if there was a headless way to:
- create Imgui + Implot visualizations
- specify the width/height for that visualization.
- render the plot in those dimensions and get that as an image.

That way we would be able to add our residual/error charts into our combined video.

**Comment by thedmd** [comment]
There is no built-in method of capturing widgets as images. Effect you want can be achieved with a bit of work:

You can either:
* render ImGui to texture using GPU
* use software rasterizer like [imgui_software_renderer](https://github.com/emilk/imgui_software_renderer), to render directly into memory

Assuming you base UI measurements on `ImGuiIO::DisplaySize` you can seamlessly:
* create and set new temporary context
* you can either reuse font atlas or generate new instance
* set `ImGuiIO::DisplaySize` to resolution you're interested in
* call `ImGui::NewFrame()`
* render plots as usual
* pass result of `ImGui::GetDrawData()` to rasterizer (GPU or software)
* restore previous context and destroy temporary one

If ImPlot allow you to pass `ImDrawList` you can use `ImGui::GetForegroundDrawList()`.
If window is necessary, one can be created spanning whole visible area and ImPlot can be drawn as any regular widget. This work best if you have separate function that draw window content.

Hope that helps.

PS. As a bonus `ImGuiIO::DisplayFramebufferScale` can be used to increase pixel density in case printing is involved or having 1 pixel thick lines on 4k video does not make a cut. This part need some extra work and I can describe what is needed to achieve this today, if will be interested.

**Comment by NathanBWaters** [comment]
Thank you for all the information!  That was extremely helpful and I look forward to trying it out.
