### ISSUE TITLE
Minor issue with automatic horizontal contents size / scrolling bounds

### ISSUE THREAD

**Issue by ghost** [ocornut/imgui#481]
Hello!

ImGui::ShowTestWindow(): Layout->Horizontal scrolling
and scroll to the most right
and look at the very last item - it's not fully visible:
![sdp](https://cloud.githubusercontent.com/assets/8142124/12278631/42a6f934-b993-11e5-8584-4fa74edde989.png)

Is it me or ...?

**Comment by ocornut** [comment]
Thanks, will look into it. Marking it as minor, it looks like only a few pixels are missing here.
I think it worked when I first added the demo, so many subtle side-effects to other changes (one extra reason to use a more thorough testing protocol).

**Comment by ocornut** [comment]
Forgot to return to this issue but it has been apparenly fixed a while ago. Closing this now.
