### ISSUE TITLE
How to include backend header files

### ISSUE THREAD

**Issue by Jessie-xw** [ocornut/imgui#4811]
I want to include `imgui_impl_glfw.h` and `imgui_impl_opengl3.h` in my cpp file, but the direct way below doesn't seem to work.

``` 
#include <imgui.h>
#include <imgui_impl_glfw.h>
#include <imgui_impl_opengl3.h>
```
The compiler reported an error saying the source file (`imgui_impl_glfw.h` and `imgui_impl_opengl3.h`) not be found. Is there any way to include these two header files in cpp files?

**Comment by ocornut** [comment]
This is a question for your build/compiler setup, unrelated to dear imgui. If they can’t be found it probably means their folder was not added to include folders. You can add the backends/ folder to include folder, or directly use “#include “backends/imgui_impl_glfw.h” as well.

**Comment by Jessie-xw** [comment]
> This is a question for your build/compiler setup, unrelated to dear imgui. If they can’t be found it probably means their folder was not added to include folders. You can add the backends/ folder to include folder, or directly use “#include “backends/imgui_impl_glfw.h” as well.

Thank you. I solved the problem by copying these two header files to the path `.\vcpkg\installed\x64-windows\include`.
