### ISSUE TITLE
rendering / executing HTML/CSS/JS files in ImGui

### ISSUE THREAD

**Issue by nvx0** [ocornut/imgui#4812]
if it is possible to make an html UI in ImGui with a support for JS/CSS?

I wanted to make an html ui which you can interact with

HTML checkbox is clicked and the new window of imgui pops out.

I would be grateful for any useful answers.

Thanks

(used in DLL)

**Comment by ocornut** [comment]
The simple answer is no.

Note however there’s a Javascript port/backend available (see Wiki>Bindings) but that’s not HTML.

(Technically everything is always possible, but if you have to ask it is generally no)
