### ISSUE TITLE
How to use TreeNodeBehaviorIsOpen?

### ISSUE THREAD

**Issue by Stanlyhalo** [ocornut/imgui#4814]
Version: 1.83
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: vs2022
Operating System: win10

**My Issue/Question:**

I'm trying to create a custom container, a sort of box, similar to the collapsing header, however, I wanted to try to utilize `ImGui::TreeNodeBehaviorIsOpen` to store the bool value for checking whether it's opened or not. However, it always returns false except for when I click, than returns back to being false.

```cpp
ImGuiID __id = window->GetID(std::string("###MY_COLLAPSING_CONTAINER_" + s).c_str());
bool is_open = ImGui::TreeNodeBehaviorIsOpen(__id, 0);

// *** other code

if (ImGui::Button(std::string("###MY_COLLAPSING_CONTAINER_BTN_" + s).c_str())) (is_open == false) ? is_open = true : is_open = false;
```

If you're wondering, the `s` variable being used, is just an id from a class I have, it doesn't change.

**Comment by Stanlyhalo** [comment]
I'm still trying to figure out how the CollapsingHeader method utilizes it, but when I attempt to do the same, it just doesn't work, it only works for the frame that I click it, than it goes back to being false.

**Comment by ocornut** [comment]
> only works for the frame that I click it, than it goes back to being false.

Well you are not writing any modified value back, how would you expect it to work.

TreeNode does:

```
if (toggled)
{
    is_open = !is_open;
    window->DC.StateStorage->SetInt(id, is_open);
}
