### ISSUE TITLE
How to render raw pixel data to an imgui window? (besides abusing the drawlist or saving the data to a texture)

### ISSUE THREAD

**Issue by Vawlpe** [ocornut/imgui#4816]
**Version/Branch of Dear ImGui:**

Version: 1.78
Branch: ImGui.Net/master
(yes, I know some issues may be specific to imgui.net but I still think asking here is more appropriate in this case)
```
Dear ImGui 1.78 (17800)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: _WIN32
define: _WIN64
define: _MSC_VER=1916
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: NULL
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsMemoryCompactTimer = 60.0f
io.BackendFlags: 0x00000000
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1366.00,745.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: A custom implementation that allows switching between Monogame / Veldrid easily 
Operating System: Windows (Linux/OSX testing is still WIP)

**My Issue/Question:**
I'm currently trying to draw a 128x128 2D array of pixels (technically they're just indexes into a separate palette array but whatever) to an imgui window, my first idea was to abuse the drawlist to shove over 16k filled rects onto it, I've done the same thing before with a 16x16 array and although relatively difficult, eventually managed to get it working... now I'm trying to do the same thing, with similar code to before, but for some forsaken reason it ends up breaking all the UI around it, all tab items besides the current one disappear, the columns API and any other elements I try to draw after the custom rendered stuff just gets sucked into a black hole and disappears as well, etc...
The fact that the data is even drawing properly is most likely a miracle xD

Another idea I thought of was to take the raw data and palette and embed them into a texture and render that, however that would make hot-swapping palettes or modifying pixel data a lot more difficult...
Are there any other ways to draw a simple grid of (scaleable) pixels to an imgui window?

**Screenshots/Video**
Broken 128x128 example:
![image](https://user-images.githubusercontent.com/47921449/146676288-03b07609-3061-41de-97e5-c8d69362ec06.png)

Working 16x16 example:
![image](https://user-images.githubusercontent.com/47921449/146676169-6521a210-a62e-41fb-8358-20f88f72aa2c.png)

**Code:**
(yes I know this is c#, sue me, I'm not converting it to c++)
```cs
...
var RenderableData = new byte[128,128]; // the data
var sz = new Vector2(4,4) // scaleable pixels
var Pal = new uint[16]; // assuming ABGR format
// Render RenderableData to the screen
var drawlist = ImGui.GetWindowDrawList();
for (int i = 0; i < RenderableData.GetLength(0); i++)
{
    for (int j = 0; j < RenderableData.GetLength(1); j++)
    {
        var cursor = ImGui.GetCursorScreenPos();
        drawlist.AddRectFilled(
            cursor + (sz * new Vector2(i, j)), // start pos of rect
            cursor + (sz * new Vector2(i, j)) + sz, // end pos of rect
            Pal[RenderableData[i, j]] // index into Pal to get the color
        );
    }
}
// this dummy is only here to try to fix the UI layout, unfortunately, it doesn't do its job very well...
// this whole snippet gets called within a column, within a tab item, within a tab bar, within a window...
// there's supposed to be more stuff drawn in the next column, there's supposed to be 2 more tabs, etc...
// but no matter what i try, as seen in that screenshot above, this completely breaks ;-;
ImGui.Dummy(sz * new Vector2(RenderableData.GetLength(0), RenderableData.GetLength(1)));
...
```
As for the working example, which btw is also inside a column, inside a tab item, inside a tab bar, inside a window:
```cs
...
var PalZoom = 4; // scaleable
var CGRam = new uint[256]; // data
var drawList = ImGui.GetWindowDrawList();

for (int r = 0; r < 16; r++)
{
    for (int c = 0; c < 16; c++)
    {
        // Could probs simplify all the vector math in here like i did for the broken example
        var p = ImGui.GetCursorScreenPos();
        var x = p.X + (c * PalZoom);
        var y = p.Y + (r * PalZoom);

        drawList.AddRectFilled(
            new Vector2(x, y), // rect start pos
            new Vector2(x + PalZoom, y + PalZoom), // rect end pos
            CGRam[(r * 16) + c]) // index into data directly, this time there's no separate palette, also 1d array instead of 2d, but math fixes that
        );
    }
}

// Oh would you look at that, the same dummy, we meet again...
// why do you work perfectly this time???
ImGui.Dummy(new Vector2(PalZoom * 16, PalZoom * 16f));
...
```

**Comment by Vawlpe** [comment]
Also, this can happen while scaling the window... for some reason... ???
![image](https://user-images.githubusercontent.com/47921449/146677507-e38294c8-5cde-4db2-b63f-b0c5057e8822.png)

**Comment by thedmd** [comment]
You can use `drawList.AddCallback()` and implement custom pixel rendering. Assuming it is available on C# side.

Otherwise rendering to texture would be the next best thing I can think of.

**Comment by ocornut** [comment]
I agree with thedmd you would be better off simply updating a texture every frame and uploading it to the GPU. You may even skip the "palette" shader and simply regenerate a RGBA texture every frame, for that amount of contents it'll be negligible amount of time.

**Comment by ocornut** [comment]
For Wonder Boy: The Dragon's Trap because the Master System only has two available 16-color palettes, I want the lazy/dumb way and rendering every tile with both palettes and then code can use one of the other. The advantage of this lazy approach is I could render everything with ImDrawList API without any shader state change.
I think it would still scale reasonably for SNES 16x16 palettes but of course using a proper palette + shader would end up being more natural in the end.

![image](https://user-images.githubusercontent.com/8225057/146939717-2be80e17-576c-4ec1-b430-ef00f8b9d040.png)

**Comment by Vawlpe** [comment]
That is indeed an interesting (and relatively easy to scale) approach but overall, having a custom API specifically for this kind of rendering would be useful in general not only for this project but for future ones as well, so i think I'll probs just go with the texture reconstruction every frame idea, as it seems most scalable with different kinds of graphics and color/palette formats, etc...

**Comment by ocornut** [comment]
Closing this as answered.
