### ISSUE TITLE
ImGui::InputText(): Cutting to clipboard via Shift+Del does not work

### ISSUE THREAD

**Issue by corporateshark** [ocornut/imgui#4818]
**Version/Branch of Dear ImGui:**

Version:  1.86 (06d5f9297de441d229f717bf6284bb14e71970f9)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: custom input back-end + custom Vulkan renderer.
Compiler: VS 2022
Operating System: Windows 10

**My Issue/Question:**

`ImGui::InputText()` does not invoke `SetClipboardText()` when I press Shift+Del to cut the selected text to clipboard (Ctrl+Ins copies the same text just fine).

Tracing inside `bool ImGui::InputTextEx(...)` shows that `is_cut` (line 4309) is set to `true`. Later there is a long `if`-statement where the following branch takes control:

```
else if (IsKeyPressedMap(ImGuiKey_Delete) && !is_readonly)      { state->OnKeyPressed(STB_TEXTEDIT_K_DELETE | k_mask); }
```
The selected text is deleted and the branch `else if (is_cut || is_copy)`, which does actual clipboard manipulations, is never executed.

A fast fix might be to make sure the condition `(IsKeyPressedMap(ImGuiKey_Delete) && !is_readonly)` also checks that Shift/Ctrl modifiers are not active (can be `&& !is_cut`).

**Comment by ocornut** [comment]
Thank you, you are absolutely right.
Fixed by 0636f9a
Interestingly as per #1541 this never worked correctly: the first commit fd4d63a0c5f8ed9004d967b5aa011e31be6ba763 broke the second 933ee6cd5dac25c9103b6bcb1a4030be38a04aa1. Will be adding regression tests for it.
