### ISSUE TITLE
GLSL shader in a window ?

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#482]
Hi,

I would like to execute a GLSL shader into a ImGui window... the goal is to do a small animation.

Is it possible and how ?

**Comment by ocornut** [comment]
You can use callbacks to do your own stuff in-between regular draw list calls.
Otherwise ImGui doesn't know about your shaders etc, so you are free to do what you want.

**Comment by emoon** [comment]
Yeah a similar issue was asked about a while ago https://github.com/ocornut/imgui/issues/475

TL;DR. Render your animation to a separate render target and then use that to render inside the ImGui window.

**Comment by krys-spectralpixel** [comment]
Thanks a lot,

BTW... how to remove a callback ?

There is no "RemoveCallback" method :-(

**Comment by ocornut** [comment]
You don't remove a callback, everything is processed once and thrown away like other components of the imdrawlist.

**Comment by krys-spectralpixel** [comment]
Ok thanks,

Is there a way to push this callback at the end ?

I need all the ImGui rendering and would like to "shade" over the widgets ?

**Comment by ocornut** [comment]
> Is there a way to push this callback at the end ?

Yes, push it at the end by pushing it at the end.

> I need all the ImGui rendering and would like to "shade" over the widgets ?

The shader is already your responsibility so you don't need to use a callback to change your shader.

**Comment by krys-spectralpixel** [comment]
I have try to add the shader execution just after ImGui::Render(), but nothing appear !
Any idea of the issue ?

```
ImGui_ImplGlfw_NewFrame();

DrawContent();

ImGui::Render();

ExecuteGLShader();

glfwSwapBuffers(_window);
glfwPollEvents();
```

**Comment by ocornut** [comment]
This is probably in the Top 3 of your obtuse and irrespectful posts. 

Those lines of codes give absolutely no information about what you are doing and could be interpreted in an infinite number of ways. Regardless, It is up to you to figure you your graphics/GPU programming issues, it has nothing to do with ImGui. ImGui doesn't know anything about your GPU. Normally we could fairly discuss the many relevant points of trying to tighten the coupling with a graphics engine, there is after all lots of ideas to talk about, but you are really not trying and abusing us. Please discuss graphics programming on a graphics programming forum.

**Comment by krys-spectralpixel** [comment]
If I don't add any details it is just that there is nothing special !

BTW, it is not related to Graphics... the shader just draw as red everywhere. Notice that this shader work on other windows, and classes are used since years without problem !

Here is the code to render:

```
glUseProgram(prog);
    glBegin(GL_QUADS);
    glVertex2f(-1, -1);
    glVertex2f(1, -1);
    glVertex2f(1, 1);
    glVertex2f(-1, 1);
    glEnd();
glUseProgram(0);
```

If I remove the last "glUseProgram" it works but then ImGui widgets does not appear anymore, even if I don't call the shader anymore !

Remark: Sorry for that, but I really don't understand what else you can expect !
