### ISSUE TITLE
ImGuiListClipper behaviour with garbage collected instance (when not calling End)

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#4822]
Version: 1.86
Branch:docking

with LuaJIT-ImGui

running this program

```Lua
local igwin = require"imgui.window"
local win = igwin:GLFW(800,400, "list clipper")

function win:draw(ig)
    local cols = 10
    local clipper = ig.ImGuiListClipper()
    clipper:Begin(1000)
    while (clipper:Step()) do
        for line = clipper.DisplayStart,clipper.DisplayEnd-1 do
            for N=line*cols+1,line*cols+cols do
                if ig.Button(string.format("%d",N)) then
                    print(N)
                end
                if not ((N)%cols == 0) then ig.SameLine() end
            end
        end
    end
end

win:start()
```
I am getting this assertion:

```
Assertion failed!

Program: c:\anima\luajit.exe
File: C:\LuaGL\gitsources\anima\LuaJIT-ImGui\cimgui\imgui\imgui.cpp, Line 2443

Expression: data->ListClipper == this
```

I dont know if it is due to bug or misuse (Althought it used to work before)

**Comment by sonoro1234** [comment]
This does not happen with main.cpp modified for having ImGuiListClipper.
It does not happen in LuaJIT-ImGui if code is modified for making sure ImGuiListClipper is destroyed before creating a new one with code:

```Lua
local igwin = require"imgui.window"
local win = igwin:SDL(800,400, "list clipper")
local ig = win.ig

function win:draw(ig)
    local cols = 10
   if ig.Begin("testt") then
   local clipper = ig.ImGuiListClipper()
    clipper:Begin(1000)
    while (clipper:Step()) do
        for line = clipper.DisplayStart,clipper.DisplayEnd-1 do
            for N=line*cols+1,line*cols+cols do
                if ig.Button(string.format("%d",N)) then
                    print(N)
                end
                if not ((N)%cols == 0) then ig.SameLine() end
            end
        end
    end
	end
	ig.End()
	collectgarbage()
end

win:start()
```
But if collectgarbage is not used (it calls __gc on clipper) so that there are several ImGuiListClipper creations before destroy is called the problem reappears

**Comment by ocornut** [comment]
What happen if you simply call `clipper.End()` at the end of your loop ?

**Comment by sonoro1234** [comment]
> What happen if you simply call `clipper.End()` at the end of your loop ?

if collectgarbage is active there is a crash without assertion

**Comment by sonoro1234** [comment]
correction: with `clipper.End()` at the end of my loop problem is gone

**Comment by ocornut** [comment]
I will try to rework things to have the final step automatically do the End() before waiting for the destructor. I recall there was an issue preventing to do this easily but i’ll work it out.

**Comment by sonoro1234** [comment]
Having to call clipper.End at the end of Step loop seems to me a clearer pattern for the casual ImGui user

**Comment by ocornut** [comment]
>  seems to me a clearer pattern for the casual ImGui user

Yes but technically we have a regression now, and Rust users are also affected. I'll look into it now.
