### ISSUE TITLE
Access violation on the line of `glBufferSubData()`

### ISSUE THREAD

**Issue by neo-mashiro** [ocornut/imgui#4825]
**Version/Branch of Dear ImGui:**

Version: v1.86
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: `imgui_impl_opengl3.cpp` + `imgui_impl_glfw.cpp`
Compiler: MSVC
Operating System: Windows 10

Hi, I've been having this problem for a long time on my GTX 1050 Ti card, when line 428 below gets called, access violation occurs. Today I just tried the newest version 1.86 where `glBufferData()` was changed to `glBufferSubData()`, but the error is still there. I cannot find anything wrong such as null pointers in `cmd_list->VtxBuffer`, I searched a lot on google and also updated my driver, still no luck.

https://github.com/ocornut/imgui/blob/440824d4314b59049a196e9e6964d8e72aed25bd/backends/imgui_impl_opengl3.cpp#L422-L430

Here is a minimal example that reproduces the error:
```c++
glfwInit();
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 6);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
glfwWindowHint(GLFW_SAMPLES, 4);
glfwWindowHint(GLFW_OPENGL_DEBUG_CONTEXT, GLFW_TRUE);
window_ptr = glfwCreateWindow(width, height, title.c_str(), NULL, NULL);
glfwMakeContextCurrent(window_ptr);
glfwSwapInterval(0);

gladLoadGLLoader((GLADloadproc)glfwGetProcAddress);

ImGui::CreateContext();
ImGui_ImplGlfw_InitForOpenGL(Window::window_ptr, false);
ImGui_ImplOpenGL3_Init();

// register callbacks manually .....

while (true) {
    glClearColor(0.0f, 0.0f, 1.0f, 1.0f);
    glClearDepth(1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    ImGui::Text("test");  // doesn't matter what we draw

    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(GetDrawData());  // access violation inside this call

    glfwSwapBuffers(Window::window_ptr);
    glfwPollEvents();
}
```

I'm not sure if this is a problem of ImGui, just wonder if people have reported similar issues or solutions on this. It looks like a driver issue because it only happens on my NVIDIA 1050 ti card, but works fine on AMD 540 and Intel HD 620. The weird thing is that, this access violation is gone when I try to debug the app in RenderDoc, as long as I run it through RenderDoc, everything work as expected, but of course I can't debug line by line then.....

**Comment by ocornut** [comment]
Hello @neo-mashiro thanks for reporting this.

I reread your issue today and wanted to clarify what is a possible ambiguity because we can investigate.
Do you mean that you ALREADY had the crash on 1.85 and prior version? (except at the time it was on glBufferData and not on glBufferSubData ?).

**Comment by ocornut** [comment]
Additional question,
Do you get the same crash on vanilla GL example for 1.85 and 1.86 ? aka with the precise GL context setup done in the example (versus the setup of your app).

**Comment by neo-mashiro** [comment]
@ocornut Sorry for being late in response. I tried the vanilla GL example today and I think I found the solution.

Regarding your questions:

1. Yes I ALREADY had the crash on 1.85 and earlier versions, so the crash has nothing to do with `glBufferSubData()` in 1.86
2. Following the precise GL context setup in the example code DOES stop the crash, but if I add these it will crash again:

```c++
#define GLFW_INCLUDE_NONE
#include <glad/glad.h>
#ifdef APIENTRY
#undef APIENTRY
#endif
```

In fact, having `#include <glad/glad.h>` anywhere in my code will lead to crash. I did a little more experiment and found that, the line that triggers access violation is not necessarily `glBufferData()`, but can also be other calls such as `glViewport()`, so obviously it's not an issue of ImGui, but seems like my driver was not able to load OpenGL function pointers correctly. In my application, I use `#define GLFW_INCLUDE_NONE` and `#include <glad/glad.h>` to include the OpenGL header, the window is created for OpenGL 4.6 core profile, and I'm using `glDebugMessageCallback()` for debugging purposes (which seems to be the culprit):

```c++
glEnable(GL_DEBUG_OUTPUT);
glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS);
glDebugMessageCallback((GLDEBUGPROC)DebugMessageCallback, nullptr);
glDebugMessageControl(GL_DONT_CARE, GL_DONT_CARE, GL_DONT_CARE, 0, NULL, GL_TRUE);
```

As soon as I removed these 4 lines of code, the crash is gone! That also explains why I was able to run my app normally in RenderDoc, because RenderDoc has its own debugging facilities that would override my own (I believe so). Perhaps my card and driver is just too old to support `glDebugMessageCallback()` and the new OpenGL API properly.

Now that I can temporarily get around this issue by disabling the debug message callback, and will migrate to a new graphics card soon, I think it'd be safe to close this now since it's not related to ImGui. Thanks for your help!

**Comment by rokups** [comment]
Since v1.84 OpenGL backend uses it's own loader. Use of loader is limited to backend .cpp files though. You are supposed to use your own loader, which you do. I could see some collision happening if you use some kind of unity builds or if you `#include "imgui_impl_opengl3.cpp"` instead of adding this file to your build system. If that is the case - avoiding `#include` would be a fix here. Or you can define `IMGUI_IMPL_OPENGL_LOADER_CUSTOM` in order to make loader use your own loader instead of our custom one.

**Comment by ocornut** [comment]
Reverted the changes of #4468 with b8b0f9d, not using glBufferSubData() anymore.
**PLEASE REPORT IF YOU STILL HAVE ISSUES AFTER TODAY**.
I temporarily kept the alternative code path even though bd->UseBufferSubData is always false, allowing potential experiment shall new issues arises. Finger crossed this doesn't bite us back.
