### ISSUE TITLE
Incorrect array size for `imgl3wProcs.ptr` generated in imgui_impl_opengl3_loader.h

### ISSUE THREAD

**Issue by dymk** [ocornut/imgui#4830]
Dear ImGui Config/Build information:

```
Dear ImGui 1.86 (18600)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __APPLE__
define: __GNUC__=4
define: __clang_version__=13.0.0 (clang-1300.0.29.30)
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigMacOSXBehaviors
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1920.00,1027.00
io.DisplayFramebufferScale: 2.00,2.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

The [`ptr` member of `GL3WProcs`](https://github.com/ocornut/imgui/blob/389982eb5afbb9f93873d87f1201842ccbc82dec/backends/imgui_impl_opengl3_loader.h#L440) appears to be off-by-one member smaller than it should be to hold all the loaded function pointers from [`proc_names`](https://github.com/ocornut/imgui/blob/389982eb5afbb9f93873d87f1201842ccbc82dec/backends/imgui_impl_opengl3_loader.h#L688).

```cpp
static void load_procs(GL3WGetProcAddressProc proc)
{
    size_t i;
    for (i = 0; i < ARRAY_SIZE(proc_names); i++) // ARRAY_SIZE(proc_names) == 54
        imgl3wProcs.ptr[i] = proc(proc_names[i]); // ARRAY_SIZE(imgl3wProcs.ptr) == 53, results in buffer overrun
}
```

proc_names is 54 elements in length, and ptr is 53 elements in length, resulting in a buffer overrun + error reported in ubsan: 

```
vendor/imgui/backends/imgui_impl_opengl3_loader.h:751:9: runtime error: index 53 out of bounds for type 'GL3WglProc [53]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ./vendor/imgui/backends/imgui_impl_opengl3_loader.h:751:9 in
```

I figure this is a bug in https://github.com/dearimgui/gl3w_stripped/blob/gl3w_stripped/gl3w_gen.py somewhere, but I was unable to reproduce the issue (I'm not sure what `./extra_symbols.txt` were used for the file checked into Dear ImGui). When I do generate my own gl3w header, it ends up with 659 members in it, and the ptr member is 659 elements in size, which seems right.

**Comment by ocornut** [comment]
My bad for 389982eb5afbb9f93873d87f1201842ccbc82dec we probably mismerged something manually.
Fixed with 89a28209e89f69a5eda560d2ef9c13915c95616a now, will add an assert in that function to avoid that happening in the future.
Thank you!
