### ISSUE TITLE
SetDragDropPayload return value

### ISSUE THREAD

**Issue by caxapexac** [ocornut/imgui#4835]
Version/Branch of Dear ImGui:

Version: 1.86
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: webGL
Compiler: em++
Operating System: V8

My Issue/Question:

SetDragDropPayload returns bool
No usage in demo window
No documentation on return type
What is it?

Source code of return value:
```cpp
return (g.DragDropAcceptFrameCount == g.FrameCount) || (g.DragDropAcceptFrameCount == g.FrameCount - 1);
```
Can't get whats the purpose

**Comment by ocornut** [comment]
I suppose a comment is needed but the code you posted should make it obvious what it does..

**Comment by caxapexac** [comment]
I mean, what's the usecase?

**Comment by ocornut** [comment]
It can be useful for the source to know that a payload is or has been accepted.

**Comment by caxapexac** [comment]
Thanks so much)
