### ISSUE TITLE
Selectables appearing inside and outside their respective Combobox

### ISSUE THREAD

**Issue by Syndelis** [ocornut/imgui#4842]
**Version/Branch of Dear ImGui:**

```
Dear ImGui 1.85 WIP (18410)
--------------------------------

sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201402
define: __linux__
define: __GNUC__=9
--------------------------------

io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------

io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------

style.WindowPadding: 15.00,15.00
style.WindowBorderSize: 1.00
style.FramePadding: 5.00,5.00
style.FrameRounding: 4.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 12.00,8.00
style.ItemInnerSpacing: 8.00,6.00
```
Branch: master
Commit: 89a28209e89f69a5eda560d2ef9c13915c95616a

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: GCC/G++ _(if the question is related to building or platform specific features)_
Operating System: Ubuntu 20.04

**My Issue/Question:**

- **Short background**: I'm integrating ImGui on a Python engine of mine via Cython. As such, I'm re-exporting widgets defined im `imgui_widgets.cpp`. I understand if that's something out of scope to ask here, so feel free to close it and accept my apologies in advance.

- **The issue**: When creating a new Combobox with the `BeginCombo()`/`EndCombo()` pair and `Selectable()`s, although the selectables get registered to the Combobox, they also appear outside of it (refer to attached GIF). While that's an issue I'm attributing to the nature of the integration, I was wondering if anyone could point me to a function that I could call in-between `Selectable()`s to hide them when used in a Combobox, something like a workaround.

**Screenshots/Video**

![imgui](https://user-images.githubusercontent.com/25804378/147690883-841f3ae9-30f0-488f-990c-adebd99e925d.gif)

**Code**
Again, because of the integration, I'm afraid I can only provide as much code as the example I myself am using. If anyone wants to dig further into this, the compilation instructions are listed on [my repository](https://github.com/syndelis/eel-engine/tree/imguicpp), while the demo to be executed is [available here](https://github.com/Syndelis/eel-engine/blob/imguicpp/examples/dear-imgui.py).

Nevertheless, I'm writing here the relevant pieces of code for this issue. Beware that it is Python.

```py
imgui.Begin("Big test")
imgui.ProgressBar(.75)

imgui.BeginCombo("##combo", f"Sel: {selected}")

for i in range(5):
    if imgui.Selectable(f"Option {i}", selected==i):
        selected = i

imgui.EndCombo()

imgui.End()
```

**Comment by ocornut** [comment]
I am very appreciative that you took the effort to submit a well formed issue, but perhaps you should have consulted the Demo code for BeginCombo() as well as the comments around it.

Basically you should test the return value of BeginCombo() and only submit your items when it is true. That’s how it indicates that it is open.

Search for BeginCombo() in imgui_demo.cpp to see how it is used.

**Comment by Syndelis** [comment]
> I am very appreciative that you took the effort to submit a well formed issue, but perhaps you should have consulted the Demo code for BeginCombo() as well as the comments around it.
> 
> Basically you should test the return value of BeginCombo() and only submit your items when it is true. That’s how it indicates that it is open.
> 
> Search for BeginCombo() in imgui_demo.cpp to see how it is used.

Hey, there! Thanks for the reply, that was the solution. I had wrongly assumed that it'd return false only if an error had occurred. Thanks again and sorry for taking your time!
