### ISSUE TITLE
Tthe background color of popup modal is iincorrect grey.

### ISSUE THREAD

**Issue by AllenDang** [ocornut/imgui#4845]
**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 

**My Issue/Question:**

Tthe background of popup modal is iincorrect grey. I can repo it with imgui_demo.cpp.

**Screenshots/Video**

![bug](https://user-images.githubusercontent.com/18550/147813824-b0631f6c-25dd-497f-94fc-151ac2ad97fa.gif)

**Comment by ocornut** [comment]
Are you sure you are using imgui_impl_opengl3.cpp ? If you are using an old or other backend try updating, there was a bug in some old backends.

**Comment by AllenDang** [comment]
@ocornut I'm using the golang version backend, I'll check them line-by-line. Thanks.

**Comment by ocornut** [comment]
To clarify, this happens if the renderer backend doesn’t honor the IdxOffset field properly and tries to compute it itself.

See last version’s fix for GL2 and Allegro backends: https://github.com/ocornut/imgui/commit/c80e8b964cbb75c4202949ad86f4b0bb3ea6aa44

**Comment by AllenDang** [comment]
@ocornut Thanks for giving me the clue. I got it fixed.

**Comment by pezcode** [comment]
> To clarify, this happens if the renderer backend doesn’t honor the IdxOffset field properly and tries to compute it itself.

The comment for `IdxOffset` still says:
```c++
// Start offset in index buffer. Always equal to sum of ElemCount drawn so far.
```

Should that be changed then, or am I misinterpreting it?

**Comment by ocornut** [comment]
You are right, will fix !
