### ISSUE TITLE
Get image texture rendered by ImDrawList

### ISSUE THREAD

**Issue by h4k1m0u** [ocornut/imgui#4848]
**Version/Branch of Dear ImGui:**
Version: 1.85
Branch: master

**Back-end/Renderer/Compiler/OS**
OpenGL/G++/Ubuntu-20.04

**My Issue/Question:**
My question concerns a functionality not a bug. I have been looking at the `ImDrawList` struct and I'm not sure if there is a way to get the image texture (e.g. as an unsigned char*) rendered by ImDrawList?

```cpp
ImVec2 position_mouse_img = ImVec2(0.0f, 0.0f);
ImGui::GetForegroundDrawList()->AddCircleFilled(position_mouse_img, 5.0f, 0xFFFFFFFF);
```

What I want to do is merge the shapes drawn (e.g. filled circle in the code above) by the user with the mouse cursor and the image shown just below them (using `ImGui::Image()`), so I can save the resulting image afterwards.

**Comment by PathogenDavid** [comment]
> I'm not sure if there is a way to get the image texture (e.g. as an unsigned char*) rendered by ImDrawList?

There isn't one. Dear ImGui renders on the GPU, so getting this raw texture would involve fetching it from the GPU. (Which isn't something Dear ImGui will do for you.)

See [thedmd's comment here](https://github.com/ocornut/imgui/issues/4809#issuecomment-994236931) about strategies you might consider for rendering things from Dear ImGui into a separate texture.

**Comment by h4k1m0u** [comment]
Thanks, the solution in the link looks too elaborate for what I was trying to do. I'll just use OpenCV for now to edit the picture, then refresh the texture.
