### ISSUE TITLE
ColorPicker and ColorEdit issue

### ISSUE THREAD

**Issue by StarMasterBM2** [ocornut/imgui#4851]
Hello i have a question what am i doing wrong

soo when i use ColorPicker or ColorEdit and i change the color every checkbox, sliderint get changed like checkboxes toggled and sliderint number changed

float color = 00000000;
ImGui::ColorEdit4("Button Color", &color);

**Comment by ocornut** [comment]
Sorry we can't help you without more details and without filling the requested issue template and reading guidelines. This is perhaps an issue with your understanding of the language.
