### ISSUE TITLE
ImGui::IsWindowHovered but related to mouse pos?

### ISSUE THREAD

**Issue by RusJJ** [ocornut/imgui#4852]
**My Issue/Question:**

Is there any version of ImGui::IsWindowHovered that can find if your pointer is above the window BEFORE NewFrame?

**Comment by ocornut** [comment]
Why ?

**Comment by RusJJ** [comment]
Because im on Android and using a kinda different Implementation of IO, modifing a game. So i want to check if im touching a window/item so i can stop the game from handling touch

**Comment by RusJJ** [comment]
For example: do not move a camera if you're changing slider value

**Comment by ocornut** [comment]
Read the FAQ.
