### ISSUE TITLE
Angle Input widget

### ISSUE THREAD

**Issue by caxapexac** [ocornut/imgui#4855]
**My Issue/Question:**
I'm using DragFloat for angles right now it's very inconvenient

Is there something like this widget:

**Screenshots/Video**
![angle](https://user-images.githubusercontent.com/33996246/147890766-738c9267-61a6-4d4b-ba68-c0910666408c.gif)

Source of reference: http://www.effecthub.com/particle2dx

**Comment by ocornut** [comment]
How about the Knob listed here?
https://github.com/ocornut/imgui/wiki/Useful-Extensions#miscellaneous

**Comment by caxapexac** [comment]
Ouf somehow I missed it, thanks. Any other solutions?

**Comment by ocornut** [comment]
You can easily program a custom one from that base.
