### ISSUE TITLE
Detect when a window or any window is being dragged or moved

### ISSUE THREAD

**Issue by JSH32** [ocornut/imgui#4856]
I have a scene view window in my project and need to drag to move. The drag event is being passed in when I'm moving the scene view window around.

**Comment by ocornut** [comment]
Read the FAQ and search here. variations of this have been asked countless times here. You won’t get accurate help if you don’t put in the effort of explaining your issue in better details.

**Comment by ocornut** [comment]
Sorry for rude answer but as we get that form of posts so often it gets tedious.

Some links:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application

#4831
#4664

There are possibily things that are different in your case but it's difficult to guess/tell without more details.

**Comment by JSH32** [comment]
Yeah im sorry it was like 3am yesterday. My problem was a bit weird because I was trying to detect when click and drag for ImGui so I could detect when the window was selected and NOT being dragged. My use case was basically click and drag on a viewport within the window but when I was moving the actual window around it was also moving the viewport inside. Temporarily fixed it by just using right click instead of left click.
