### ISSUE TITLE
Issues with Modal Dialog and incorrect dimming

### ISSUE THREAD

**Issue by BobbyAnguelov** [ocornut/imgui#4863]
```
Dear ImGui 1.87 WIP (18602)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=201703
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000000
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C02
 HasMouseCursors
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1101.00,871.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

I've been having a really weird issue ever since I upgraded to the 1.86 version. I just rolled back to the 1.85 version to verify and the issue isn't present. I've tried to debug it but after around a day of chasing my tail, I dont understand what's going on. Everything is perfect, except for modal dialogs. The dim region is inverted and in the demo modal dialog, the 'H' from hello is missing. 

I tried to repro this using the examples provided but I cant so I assume there is something on my end that's causing this, but I have no idea what that could be, I've basically stripped it down to just call NewFrame/ShowDemoWindow/EndFrame. 

Does anyone have any idea what could be causing this or how to debug it. I stepped through "ImGui::RenderDimmedBackgrounds" and all the clipping rects and selection of the foremost window seems to be correct.

1.87 WIP - upgraded today in hopes it would fix the issue
![image](https://user-images.githubusercontent.com/10767490/148133202-43623e39-0080-4b8c-897f-2f3bae5fc19c.png)

1.85
![image](https://user-images.githubusercontent.com/10767490/148133102-bdf42f3f-9082-4ca3-a520-a6d1bc0eba3b.png)

**Comment by ocornut** [comment]
Same as #4845 (see comment https://github.com/ocornut/imgui/issues/4845#issuecomment-1003329113)

Your backend doesn't honor `ImDrawCmd::IdxOffset` correctly.
The annoying thing is that some backend didn't before 1.86 and it was never noticeable until now.
I could have done this dimming without it but I think we can take advantage of IdxOffset better for other features later.

I will edit the release note to that make more apparent.

**Comment by BobbyAnguelov** [comment]
Awesome! Thanks for the hint!

I dont know why I didn't see that issue when I searched :/ Sorry for the dupe!

**Comment by ocornut** [comment]
No worries.. I suspect other people will stumble on same issues so more references are better. There was already a line in the TL;DR; section of Release Change but I added some more too:

[com/ocornut/imgui/releases/tag/v1.86](https://github.com/ocornut/imgui/releases/tag/v1.86)

![image](https://user-images.githubusercontent.com/8225057/148134480-5ef533d2-f661-456a-9ebf-395e89429a94.png)

If anything if it can encourage people to update their backend I guess it's not a total loss..

**Comment by BobbyAnguelov** [comment]
Yeh, it was a really quick fix once you pointed me in the right place.
