### ISSUE TITLE
Unicode, format strings, C++20

### ISSUE THREAD

**Issue by tksuoran** [ocornut/imgui#4866]
**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: custom (erhe)
Compiler: Visual Studio 2022
Operating System: Windows 10

**My Issue/Question:**

How to put degree symbol to a format string?
How to use unicode in format strings?

In imgui.h I can find 

> we generally use UTF-8 encoded string in the API

but the API uses `const char*` for format strings, instead of `const char8_t*`.

Here is what I tried:
- `"%f°"` - does not work, I get ? in place of the degree symbol.
- `"%f\xb0"` - does not work, I get ? in place of the degree symbol.
- `u8"%f\u00b0"` - compiler error, as API wants `const char*`
- `reinterpret_cast<const char*>(u8"%f\u00b0")` - works but is ugly code

It would be so nice if imgui supported C++20 somehow and would allow one to pass `u8"%f\u00b0"` into format strings.
Is `reinterpret_cast<const char*>(u8"%f\u00b0")` the intended way, or is there some better way?

Thanks!

**Comment by ocornut** [comment]
> but the API uses const char* for format strings, instead of const char8_t*.

`const char*` can hold  UTF-8 just as well.

This has been discussed recently on Twitter and unfortunately C++20 specs are currently broken.

You should prefer to configure your compiler to treat "" as UTF-8 which is already the default in GCC/Clang AFAIK, and then both `"%f°"` and `"%f\xb0"` will work.
https://twitter.com/__phantomderp/status/1478288934404767746

Bonus ref:
https://twitter.com/__phantomderp/status/1477762809773572107

**Comment by thedmd** [comment]
As Omar mentioned GCC/Clang already assume files are saved in UTF-8 encoding by default.
For MSVC (2017+) `/utf-8 /Zc:char8_t-` is [new orange](https://www.quora.com/Why-is-that-Netflix-series-called-Orange-is-the-New-Black-Whats-the-meaning-behind-that-phrase/answer/Johan-Leclercq). `/utf-8` tells MSVC to read source as UTF-8, not current code page. `/Zc:char8_t-` get rid of `u8""` being `char8_t` in favor of `char`.

---

From my personal view `char8_t` is something to avoid for at least next nine years. Will Unicode support in C++ get better? Maybe. But not tomorrow, not today.

To keep sanity in check I assume my source live in UTF-8 world. Lack of support from Standard Library is major showstopper. Calls like `fopen(u8"test.txt", ...)` are not accepted and probably never will.
Our generation will be long dead before consensus will be reached on the matter if `fopen` should be templatized to accept `basic_string_view/basic_path_view` or just overloaded for every possible `charXX_t` type. I don't see myself writing code like:
```cpp
bool IsHtmlColorValid(const char*, const char* end = nullptr);
bool IsHtmlColorValid(const wchar_t*, const wchar_t* end = nullptr);
bool IsHtmlColorValid(const char8_t*, const char8_t* end = nullptr);
bool IsHtmlColorValid(const char16_t*, const char16_t* end = nullptr);
bool IsHtmlColorValid(const char32_t*, const char32_t* end = nullptr);
```
Arguably in C++ we would rather have:
```cpp
bool IsHtmlColorValid(string_view);
bool IsHtmlColorValid(wstring_view);
bool IsHtmlColorValid(u8string_view);
bool IsHtmlColorValid(u16string_view);
bool IsHtmlColorValid(u32string_view);
```
We know the tool to solve this issue, let's use templates:
```cpp
template <typename T>
bool IsHtmlColorValid(basic_string_view<T>);
```
Wait, I forgot something:
```cpp
template <typename T, typename Traits = std::char_traits<T>>
bool IsHtmlColorValid(basic_string_view<C, Traits>);
```
Now it is better, more generic, C++shy. Looking at the implementation is now a burden of the user.
User have to parse and compile this every time, probably in all translation units it utility
is common enough. Also do not change that ever, to avoid breaking ABI by mistake.

It is cute that C++ can do that, create problems and tools to solve them in recursive manner.

Ending that small rant I can say that what held be back when I tried `char8_t` was inability to convert that to `char` in `constexpr` context. Suddenly static data got run-time initializers, which was a big nope.

**Comment by tksuoran** [comment]
I added `/utf-8` and and made sure the source file is utf-8.
After this:

- `"°"` is shown correctly in both ImGui rendering and console log window
- `"\xb0"` is shown as `?` by ImGui and empty space in console log window

I have also done `std::setlocale(LC_CTYPE, ".UTF8")` and `SetConsoleOutputCP(CP_UTF8)`.
Visual Studio Code (extension) shows unicode for symbol under cursor and it shows U=00B0 for `°` in the string.

Any ideas why `"°"` and `"\xb0"` end up being treated differently?

**Comment by ocornut** [comment]
\xB0 is not correct encoding for U+00B0
There are interactive websites to show you the result of UTF-8 encoding.

**Comment by seanmiddleditch** [comment]
You probably still want `\u00B0` instead of `\x` escapes for Unicode codepoints. The Microsoft compiler will encode it as UTF-8 if `/utf-8` is provided.

https://godbolt.org/z/zWfeecjjP

**Comment by ocornut** [comment]
Specifically U+00B0 in UTF-8 is two bytes: C2 B0, so using \x codes it would be “\xc2\xb0” but as pointed using \u00B0 makes more sense.

I guess we can close this, let us know if you have further questions.
