### ISSUE TITLE
Hardcoded value related to column width, why ?

### ISSUE THREAD

**Issue by itamago** [ocornut/imgui#487]
Hello,

I'm using ImGUI with a METAL renderer on iOS and OSX, and I'm really impressed by the quality of your code (clear, usable, easy).

I've a question related to column sizes : you hardcoded a 0.65f ratio on the X axis which may be a problem in some cases. Is there a reason ?

```
ImGui::PushItemWidth(ImGui::GetColumnWidth() * 0.65f);  // FIXME: Move on columns setup
```

For instance, if I want to render a graph widget in a column, and make this graph use the full width of the column (by removing the text label written on the right of the graph), it is currently impossible due to this ratio => the graph will take 65% of the column width only.

Obviously, I removed this 0.65f ratio to test the result. It works fine for me, but it has some side-effects on the demo sample "Columns > Mixed Items".

As you commented in the source code, that would be great to configure this ratio during the setup.

Best regards,

- Pacôme.

(Omar, it seems we have a friend in common, Jerome Larrieu)

**Comment by ocornut** [comment]
Hello Pacôme,

Well there has to be a default somehow. 
- You can use `PushItemWidth(-1)` to use the full width of the column (right align).
- `PushItemWidth(200)` for fixed width items. 
- `PushItemWidth(ImGui::GetContentRegionAvailWidth() * 0.65f);` would be roughly equivalent to that default as well.

There is currently an issue that I would like to fix, currently the ItemWidth width isn't saved per column, each call to NextColumn() reset it for the next column. I intend to save this valuer column so you wouldn't need to call PushItemWidth() every time to change column, which is a little cumbersome. As the value isn't saved already it should break any code to get it saved in the future.

Hope it helps!
Nice to hear! I am moving back to Paris, perhaps I'll see Jerome again when he is up there.

**Comment by itamago** [comment]
Hello Omar,

Thanks, it works perfectly well with ```PushItemWidth(-1)```.
Just a remark about ```PlotLines```, I modified it to handle NULL labels (2 lines to add in ```ImGui::PlotEx```) which is useful when you want to avoid labels instead of putting an empty string as parameter (which requires string size calculation of the empty string, drawing the empty string, etc).

Jérôme comes to Paris 1 time a month. Hard to catch him, but send him an email, he will be happy.
I guess you know Bertrand too ? (Game developer world is so small..)

**Comment by ocornut** [comment]
Labels are widespread across ImGui as a way to also provide identifiers. The usual way to pass an empty label is to use the "##foobar" syntax, where you can use "foobar" to disambiguate ID. Now as it happens the PlotLines() function currently doesn't rely on the identifier because it has no lasting interaction but this is something that may change.

The size calculation for empty string should be fairly lightweight or very minor in the context, although I suppose I could add an extra test prior to calling `CalcTextSizeA`.

About label/identifiers, you may want to read that section of the FAQ in imgui.cpp
`Q: Can I have multiple widgets with the same label? Can I have widget without a label? (Yes)`

**Comment by itamago** [comment]
Understood. 
I'm new to ImGUI, so I may misunderstand lot of things for the moment :)
I will RTFM, good starting point. Thanks.

**Comment by Jaydee2190** [comment]
Is it possible to use PushItemWidth to have two different sized columns?  (The below doesn't seem to have any effect.

    ImGui::Columns(2, "mycolumns");
    ImGui::Separator();

    ImGui::Text("KEY"); ImGui::NextColumn();              
     ImGui::Text("VALUE"); ImGui::NextColumn();
     ImGui::Separator();
     for (int i=0;i<env.size();++i)
      {
         ImGui::PushItemWidth(20);
          ImGui::Text("TEST");
          ImGui::NextColumn();
          ImGui::PushItemWidth(210);
          ImGui::TextWrapped("test value");
          ImGui::NextColumn();
          ImGui::Separator();             
         }

**Comment by ocornut** [comment]
ItemWidth relate to the width of framed widgets such as sliders, etc.
In this situation it looks like you want to alter the column widths which can be set with SetColumn*() function.

Unfortunately those functions are quite primitives yet (the entire Colums feature has issues). If you want to set a default width but also allow user resizing you'd need to call this function only once (if you call it every frame then the user wouldn't be able to resize).

Ideally the Columns needs a big lifting so columns "specs" can be defined with more parameters. Probably in the shorter term we could add a conditional parameter to SetColumnOffset function to makes it easy to set initial offsets (similar to how SetNextWindowPos function has a conditional parameter).

**Comment by Jaydee2190** [comment]
That works well thanks! I should send another donation ;)
