### ISSUE TITLE
Remove focusing for all windows/viewports

### ISSUE THREAD

**Issue by ominusliticus** [ocornut/imgui#4872]
Dear Contributers,

This is my first issue with Dear ImGui, so I will be as pedantic as possible.
```
Dear ImGui 1.86 WIP (18514)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=202004
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: ImGui_SDL_Backend          
io.BackendRendererName: ImGui_Vulkan_Backend
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.DisplaySize: 1600.00,900.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 0.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```
I have pasted the Config/Build information from the Demo window.
Please note that the platform and renderer backend are in fact taken from here, but I have replaced struct and function names to conform to my preferred style of coding.
The issue below remains whether I use the files from here or my rewritten ones.

**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: docking (commit 06e4f4e3702c2e81833c3ebbdf88950f45a820e2)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_vulkan.cpp (only differences are struct and function names)
Compiler: MSVC
Operating System: Windows 11

**My Issue/Question:**

I want to disallow all focusing, i.e. title bars should not change color when the corresponding window is mouse picked.

Focused: ![focused](https://user-images.githubusercontent.com/44349307/148449175-37d05231-bf4e-4d3b-aab3-3bd2724ca6f0.png)
Unfocused: ![unfocused](https://user-images.githubusercontent.com/44349307/148449248-ab5ac3af-369b-467a-b8a5-74fbf9f4166c.png)

```C++
// Including all window, style and viewport code that goes into creating this window
ImGui::GetStyle().WindowRounding = 7.0f;
ImGui::GetStyle().WindowBorderSize = 0.0f;
ImGui::SetNextWindowBgAlpha(1.0);

ImGui::GetMainViewport()->Flags |= ImGuiViewportFlags_NoFocusOnAppearing;
ImGui::GetMainViewport()->Flags |= ImGuiViewportFlags_NoFocusOnClick;

ImGui::NewFrame()

ImGuiWindowFlags imgui_window_flags = ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoCollapse;
imgui_window_flags |= ImGuiWindowFlags_HorizontalScrollbar | ImGuiWindowFlags_NoFocusOnAppearing;

ImGui::Begin("Example Bug", (bool *)0,  imgui_window_flags);
ImText("Log: Lorem ipsum...");
ImGui::End();

ImGui::EndFrame();
```

I have also tried adding the lines 
```C++
ImGui::GetWindowViewport()->Flags |= ImGuiViewportFlags_NoFocusOnAppearing;
ImGui::GetWindowViewport()->Flags |= ImGuiViewportFlags_NoFocusOnClick;
```
after the `ImGui::Begin()` call, but this did not help.

I expect `ImGuiViewportFlags_NoFocusOnClick`  to accomplish what I wish, but so far nothing above has prohibit this focusing behavior.

**Comment by ocornut** [comment]
> I want to disallow all focusing

Why? What property are you looking for or trying to avoid specifically?

> i.e. title bars should not change color when the corresponding window is mouse picked.

Because if its only that you can of course change the colors to match…

**Comment by ominusliticus** [comment]
As to why: really it's a personal preference. 
Which property this corresponds to I don't know. I thought the `NoFocusOnClick` flag would have fixed this. So the question to me remains, what property does this tweak.

Your suggestion of changing colors sounds like what I need to do. Thank you.

**Comment by ocornut** [comment]
> As to why: really it's a personal preference.

That's not answering the question :)

> Your suggestion of changing colors sounds like what I need to do. Thank you.

That's answering the question and solving it !

**Comment by herve-lb** [comment]
comment changer la couleur du titre de la fenêtre lorsqu'elle est focus
