### ISSUE TITLE
Kanteran code-blocks project

### ISSUE THREAD

**Issue by HenryKaufman** [ocornut/imgui#4875]
Is the [Kanteran code-blocks project](https://github.com/ocornut/imgui/issues/3488#issuecomment-705559899) available anywhere (like github)? I'd like to check it out, if possible. (I've searched a bunch and can't find anything).

Are there any other blockly/scratch styled code editors made with imgui?
I am aware of all the node editors available - thanks for compiling those into a nice list already!

Thanks!

**Comment by ocornut** [comment]
Hello Henry,

> Is the Kanteran code-blocks project available anywhere (like github)? I'd like to check it out, if possible. (I've searched a bunch and can't find anything).

Seems like you answered your own question here?

Everything I know of has been linked in those issues or the wiki.

**Comment by HenryKaufman** [comment]
![image](https://user-images.githubusercontent.com/6425918/148627481-ca2163ba-5333-48cd-bb87-5ee800c3a7ab.png)

Thanks. I was wondering, because the image in the gallery (above) didn't have a github (or other code) link to it. I guess it's not an open source project.

**Comment by ocornut** [comment]
I don't even remember where I found it, maybe on twitter or on some discord, I don't have more information on it sorry.
