### ISSUE TITLE
sdl2 widget window how to create?

### ISSUE THREAD

**Issue by standtall007** [ocornut/imgui#488]
Hi i am relly new to imgui and i like what i see but i haven't been able to find any examples that directly shows how to embed the sdl content onto a imgui window (the ones inside the application!) if it is possible at all... i hope it is because there aren't too many easy to use gui's that make even fairly good use of sdl 2....
Thanks in advance and sorry for disturbing.
- David M.

**Comment by ocornut** [comment]
I am not sure if I understand your question well.
If you want to render custom texture or visuals within an ImGui window you can use the Image() API, see https://github.com/ocornut/imgui/issues/475 
As it does is passing your own texture identifier to the final render loop which you have control of.

You can also use Callback inside the drawlist of a window for more advanced interaction with your rendering but typically you can get lots of stuff done more easily with texture.

**Comment by standtall007** [comment]
hi omar, what i mean is i have created a simple 2d game engine and i want to create an editor window linke most game engines have :) and if possible then i want to use imgui...

**Comment by ocornut** [comment]
I'm still not sure what you question is precisely. Have you checked the ImGui example code and the ShowTestWindow() code for various examples?

**Comment by standtall007** [comment]
i mean i want to use sdl surface feature in sdl/sdl2 for creating an scene editor for my game engine, i am truly sorry if you still don't understand what i mean, i cannot specify it any deeper than this as i have tried every other methods... but i assume that this cannot be done with imgui... so currently i am trying some other options even though they aren't many. thanks anyway for your time :)

**Comment by ocornut** [comment]
I don't know what "sdl surface feature" means, I'm not using SDL.

You can create and use ImGui in SDL and you can render an SDL texture inside a ImGui window if you want. I don't think anything is missing for you.

**Comment by standtall007** [comment]
just one last question if you don't mind... is it possible to create a menubar like file menu, edit menu etc... in imgui? that is basically a requirement for my game engine as it will benefit from it :)

**Comment by ocornut** [comment]
Yes, it's already documented in the demo code.

**Comment by standtall007** [comment]
Thanks i completely forgot about it, sorry about that.
