### ISSUE TITLE
Add `ImGuiSliderFlags_EnterReturnsTrue` to ImGuiSliderFlags_ enum for `DragScalar` ?

### ISSUE THREAD

**Issue by peter1745** [ocornut/imgui#4885]
**Version/Branch of Dear ImGui:**

Version: 1.84.1
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfwcpp + imgui_impl_vulkan_with_textures.cpp
Operating System: Windows 11

**My Issue/Question:**

I'd like to propose an extension to the `DragScalar` / `TempInputScalar` function to enable the same behavior as the `ImGuiInputTextFlags_EnterReturnsTrue` flag enables for text inputs.
Currently when you're manually editing the value of a `DragScalar` widget (e.g double click on it), the `DragScalar` function returns true every time you press a key, e.g if I want to enter the value `15` the function would return true twice, once for the value `1` and once for the value `15`.

This can occasionally result in undesired behavior (e.g if the value represents the length of an array, and I want to resize the array but maintain the previous elements when the length is changed).

Instead I propose that a flag be added to the `ImGuiSliderFlags_` enum called something along the lines of `ImGuiSliderFlags_EnterReturnsTrue` which would enable the behavior I described above.

This could somewhat easily be done by changing the `TempInputScalar` function to take in e.g a boolean parameter called e.g `enterReturnsTrue`, or pass in a `ImGuiInputTextFlags` parameter (instead of defining those flags in the function body).

I also propose that this functionality would be disabled by default in order to not break existing code.

**Comment by ocornut** [comment]
Hello,
Are you sure you can't use `IsItemDeactivatedAfterEdit()` for your purpose?

**Comment by peter1745** [comment]
Wasn't aware that it was a thing 🙂 But yeah I tested it and it didn't work, it returned true immediately after I typed `1` unforutnately

**Comment by ocornut** [comment]
It works well when I test them in the Demo Window so you must have misused it.

![image](https://user-images.githubusercontent.com/8225057/148766462-b87ec7e3-e5c1-4f64-81ff-8b653aef087c.png)

**Comment by peter1745** [comment]
Alright, I tested it by using this code:
```cpp
ImGui::DragScalar("Length", ImGuiDataType_U64, &length, 1.0f, NULL, NULL, "%d", 0);

if (ImGui::IsItemDeactivatedAfterEdit())
{
	array.Resize(length);
	changed = true;
}
```
and `ImGui::IsItemDeactivatedAfterEdit` returns true immediately when I enter 1

**Comment by ocornut** [comment]
It doesn't happen here:
```
static ImU64 length = 0;
ImGui::DragScalar("Length", ImGuiDataType_U64, &length, 1.0f, NULL, NULL);
bool edited = ImGui::IsItemDeactivatedAfterEdit();
ImGui::Text("%s", edited ? "Edited!" : "");
```
So you must be doing something wrong that you are omitting from your description.

**Comment by peter1745** [comment]
Would using `ImGui::PushID` cause issues with this?

**Comment by ocornut** [comment]
That's a too ambiguous question to be answered
.

**Comment by peter1745** [comment]
Alright yeah I was able to narrow it down, and it seems to be due to some custom rendering that we're doing that's causing issues.
Thanks for letting me know about the `IsItemDeactivatedAfterEdit` function!
