### ISSUE TITLE
ImGui sizing issue with Vulkan

### ISSUE THREAD

**Issue by olivier-gerard** [ocornut/imgui#4886]
Hi everyone,

I've been using Dear ImGui for some month now, and wanted to take benefit of latest release to clear custom code made long ago and use ImGui_ImplVulkan_* instead.

My app is running ImGui 1.86 on Windows, with Vulkan and GLFW and was working fine until now.
After using the standard Vulkan implementation files all ImGui widgets are tiny in top left corner of the window instead of using the available space.

![app](https://user-images.githubusercontent.com/88795175/148799437-fd71cafa-ae02-4826-bb8f-942f64aaecd4.PNG)

The mouse is ok (I mean if the cursor is in top right corner it will interact with the widget supposed to be here).
My other displayed image (black image at the center) is off course unaffected.

I tried swapping the code in the render pas (ie calling ImGui_ImplVulkan_NewFrame before my stuff), setting full viewport and scissor with no effects.
If I change the scale in the push constants, or resize the window then widgets are zoomed, but remains only in the top left corner.

I'm sorry to bother you with this, I'm pretty sure I made an error somewhere, but I've been struggling to find what cold be wrong. As you can imagine I compared against example code, and with my previous working code and could not find what's wrong.
The whole code between ImGui::NewFrame(); and ImGui::Render(); is exactly unchanged.

Many thanks in advance if someone can help.

**Comment by olivier-gerard** [comment]
Hi,

I finally found my bug, the different VkSampleCountFlagBits fields were not at the same value.

I cannot understand why the validation messages didn't show up last days (I had even used VulkanConfigurator to show more messages than the standard config of my app, and off courses rebuilt many time my app), and finally decided to appear, but at least the topic is closed. Maybe my Vulkan SDK update reset something (it was previously to 1.2.189.2, so clearly not outdated).

I'm really sorry for the noise, you've got plenty of much more important things to do, but once again I posted after days of struggling and trying everything.

Apologies and thanks for your great work.

**Comment by ocornut** [comment]
This is useful to post, best to have a trace for future references.
Is there something we could do on the backend side to either fix it or facilate detecting it?

**Comment by olivier-gerard** [comment]
Well the validation message should have appeared, so basically it should be quickly fixed.
As I relied on the example, maybe just adding the field init_info.MSAASamples to a hard coded value could highlight its presence.

**Comment by ocornut** [comment]
> As I relied on the example, maybe just adding the field init_info.MSAASamples to a hard coded value could highlight its presence

Good point, now done with 6188e94
