### ISSUE TITLE
modals grayed area shows inside window

### ISSUE THREAD

**Issue by jvannugteren** [ocornut/imgui#4887]
**Version/Branch of Dear ImGui:**
Version: 1.87 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**
Back-ends: magnum-integration (SDL2)
Compiler: gnu gcc
Operating System: linux (manjaro)

**My Issue/Question:**
About a month ago the modal windows started being rendered incorrectly. The grayed out area is inside the window instead of outside. This was working correctly before. This visual bug can be reproduced using "stacked modals" with the demo window:

![image](https://user-images.githubusercontent.com/78733220/148838223-76a0a664-09e9-4cae-a168-f988ee4020d5.png)

The issue arises with all modal windows in my application. Thanks for looking at this.

**Comment by ocornut** [comment]
Read latest Releases Notes on github.

**Comment by ocornut** [comment]
Back on the computer, adding links:

https://github.com/ocornut/imgui/releases/tag/v1.86

also same issues #4863 and #4845

**Comment by jvannugteren** [comment]
Thanks. I probably missed it because I was searching for "open" issues. I'll have a look at my backend.
