### ISSUE TITLE
Usage of Virtual Memory High

### ISSUE THREAD

**Issue by johnfercher** [ocornut/imgui#489]
I'm writing a system using the imgui, but i have a issue, the use of virtual memory it's too big in comparison with the use in RAM. Thats normal? It may become a problem in future?

**Comment by ocornut** [comment]
I don't know what you mean, what is your use case, what is your code.
I assume what you are recording may depends on other factors in your application.
ImGui allocate very little, the number of alive allocations are recorded in the Metrics window and generally hover around a few hundred small allocations.

**Comment by johnfercher** [comment]
It's a robot soccer team (https://www.youtube.com/watch?v=YbFdpMkFnQQ) the imgui and the rest of the program working in different threads. http://pastebin.com/4aZB7kHE the class imgui, my use of VM before i add the class Vision was 200MB, after added has become 400MB, and now i added the class Communication and has become 1.2GB.

**Comment by ocornut** [comment]
I don't know what those classes are they are in your code. I don't expect ImGui to be allocating more than a few megabytes.

**Comment by jarikomppa** [comment]
running cppcheck, visual studio code analysis or some kind of memory leak
detector might help. ImGui shouldn't cause those kinds of allocations.
