### ISSUE TITLE
CheckBox() sometimes shows a square instead of a tick mark

### ISSUE THREAD

**Issue by rexrogers** [ocornut/imgui#4894]
Sometimes my ImGui code will show a square instead of a tick mark for a CheckBox().  It happened once when I went from debug mode to release mode (using Visual Studio 2022), and at other times it happens randomly after a change or seemingly randomly when I check a box or use some feature of my compiled ImGui UI.  Does this point to something fundamentally wrong w/ my code, i.e. a bug lurking in it.  Thanks.

**Comment by PathogenDavid** [comment]
Like this?

![tristate_checkbox](https://user-images.githubusercontent.com/8225057/60395144-526aa600-9b2f-11e9-8ca0-097a24033a10.gif)

If so, are you using this beta feature somewhere? https://github.com/ocornut/imgui/issues/2644 If so, make sure you aren't calling `PushItemFlag` without the corresponding `PopItemFlag`.

(Also it'd be helpful if you filled out the issue template next time. A screenshot in particular would be valuable here.)

**Comment by rexrogers** [comment]
I am not using PushItemFlag and PopItemFlag.  I was using a ImGui::BeginDisabled(true) and ImGui::EndDisabled() pair, and for a time it showed up when I was using that (as well as the time in debug mode).  The problem did appear like you show w/ the .gif => I could cycle it thru the 'tri-state' with clicks on other elements in my UI.  [Yes, will follow the template next time.]  Thank you.

**Comment by ocornut** [comment]
> It happened once when I went from debug mode to release mode (using Visual Studio 2022), and at other times it happens randomly after a change or seemingly randomly 

That suggest you might have a bug in your app code or building setup.

But honestly we cannot really do much without a repro and details, so I am going to have to close this without more details.

`Checkbox()` checks for the `ImGuiItemFlags_MixedValue` flag in ItemFlags. Why this is set I don't really know.

**Comment by rexrogers** [comment]
Thank you.  I am 2nd time beginner w/ ImGui, so it surely could be a misuse situation.

**Comment by ocornut** [comment]
Let us know if you find more information and we can reopen.
