### ISSUE TITLE
Adding custom Icons

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#490]
Hi,

How do you add custom icons to Imgui?

http://imgur.com/a/CFrxL

Basically I need to take the top row and the left icons into one bar going cross below the menubar.

Vivienne

**Comment by ocornut** [comment]
You can use Image(), ImageButtion() widgets, or create new widgets based on what they do.

**Comment by vivienneanthony** [comment]
I'll check out ImageButton()
