### ISSUE TITLE
How do I make an InputText that accepts wstring?

### ISSUE THREAD

**Issue by Reimnop** [ocornut/imgui#4912]
I know this question has probably been asked before, but I would like to support multiple languages in my application. I've looked everywhere but couldn't find any example or documentation to use wstring with ImGui.

**Comment by ocornut** [comment]
This is not supported. We support UTF-8 everywhere shall you need localization.

**Comment by ocornut** [comment]
Closing this as answered. FYI utf-8 is afaik a more common solution for encoding than utf-16, due to how a larger majority of software can support it and/or at least fallback to display the ASCII part of it.
You might want to consider using char*/string with utf-8 data rather than wstring.

**Comment by Ou7law007** [comment]
> Closing this as answered. FYI utf-8 is afaik a more common solution for encoding than utf-16, due to how a larger majority of software can support it and/or at least fallback to display the ASCII part of it. You might want to consider using char*/string with utf-8 data rather than wstring.

Not sure how you define _more common_. Chinese, Russian, Arabic, Korean, Japanese etc... basically everything else other than 255 ASCII characters aren't _common_?

So it's impossible to display non ASCII characters like 你好?

**Comment by PathogenDavid** [comment]
@Ou7law007 Dear ImGui uses UTF8. UTF8 can encode all of the languages you mentioned. Dear ImGui can display Chinese.
