### ISSUE TITLE
Assert with Alpha set to 0 and usage of new Table API

### ISSUE THREAD

**Issue by Froyok** [ocornut/imgui#4916]
**Version/Branch of Dear ImGui:**

- Version: **1.86**
- Branch: **master & docking**

**Back-end/Renderer/Compiler/OS**

- Back-ends: **example_sdl_opengl3** (with custom code, see below)
- Compiler: **g++ (GCC) 11.1.0** (+ make file from example)
- Operating System: **Linux (Kernel: 5.15.12-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: KDE Plasma 5.23.4 Distro: Manjaro Linux base: Arch Linux)**

**My Issue:**

Setting the global style alpha to 0.0 and using the Table API raises the following assert when running the code:

```
$ ./example_sdl_opengl3 
example_sdl_opengl3: ../../imgui_tables.cpp:1401: void ImGui::TableSetupColumn(const char*, ImGuiTableColumnFlags, float, ImGuiID): Assertion `table != __null && "Need to call TableSetupColumn() after BeginTable()!"' failed.
Aborted (core dumped)
```

As far I can see, I don't see any reason why this triggers an assert. It works in some situations with Push/Pop style. So I'm guessing this is a bug.

**Example code to reproduce:** 
Below is the code I added to the default `example_sdl_opengl3` example, at the end of the simple window demo code:

```
	// Start of custom code for repro steps
	ImGui::Separator();

	ImGui::GetStyle().Alpha = 0.0;

	ImGuiTableColumnFlags TableFlagsStatic = ImGuiTableColumnFlags_WidthFixed | ImGuiTableColumnFlags_NoResize | ImGuiTableColumnFlags_NoReorder;
	ImGuiTableColumnFlags TableFlagsStretch = ImGuiTableColumnFlags_WidthStretch | ImGuiTableColumnFlags_NoReorder;

	ImGui::BeginTable( "TableLayout", 3 );
	ImGui::TableSetupColumn( "LeftColumn", TableFlagsStatic, 10.0 );
	ImGui::TableSetupColumn( "MiddleColumn", TableFlagsStretch );
	ImGui::TableSetupColumn( "RightColumn", TableFlagsStatic, 10.0 );

	ImVec2 DummySize;
	DummySize.x = 0;
	DummySize.y = 1;

	ImGui::TableNextColumn();
	ImGui::Dummy( DummySize );
	ImGui::TableNextColumn();
	ImGui::Text( "Test" );
	ImGui::TableNextColumn();
	ImGui::Dummy( DummySize );

	ImGui::EndTable();

	ImGui::End();
} // End of "2. simple window" demo code
```

**Note:**
In this example I raise the assert by changing the Style.Alpha global variable, but in more complex code inside my own project I can also raise the assert when calling the Push/Pop style function if done before the Begin/End table. If I do the Push/Pop inside a column the assert doesn't appear, or if the Push/Pop at the Begin and End of Window (and not in the middle around the Table).

I hope I'm clear enough. Hopefully the global example is enough to debug the issue. :)

**Comment by ocornut** [comment]
You should test the return value of `BeginTable()` and honor it (not submit the tables if it returns false)
This is exactly what the assert suggests, and the 42 uses of `BeginTable()` in demo are all honoring that return value, it is curious you are not :)

**Comment by ocornut** [comment]
Basically when Alpha is 0.0f some contents are eagerly clipped. Other situation like a scrolling tables (with a known size not affecting the container window) would also lead to `BeginTable()` returning false if outside view.

**Comment by Froyok** [comment]
Ha I see, I totally forgot about the proper Begin/End behavior (too used to having my window always visible, so I didn't scope them). Sorry for that.

Right now, if I scope the BeginTable properly, when Alpha is 0, then it returns False. I was hoping of using Table as a way to layout invisible widgets for my custom UI. Is it the expected behavior ? Or should it return True if the table is inside the view ?

**Comment by ocornut** [comment]
`Begin()` sets the window in full coarse clipping mode when Alpha==0.0f which is technically taking a little too much freedom (hence the "eagerly") but it's been like that for a while.

Technically using alpha ~0.00001f will end up also skipping most rendering while not enabling coarse clipping at the window level.

**Comment by Froyok** [comment]
Ha, great to know about the little threshold, I will take advantage of that then. :)
(Taking the liberty to close the issue then since it's the expected behavior.)
