### ISSUE TITLE
Unicode rendering of Tone contour via Tone letters

### ISSUE THREAD

**Issue by immetoo** [ocornut/imgui#4922]
**Version/Branch of Dear ImGui:**

Version: 1.86

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_java_impl_glfw via opengl3
Operating System: Debian

**My Issue/Question:**

Trying to get imgui to render the tone contours which are defined by tone letter sequences.
After adding a few fonts imgui renders the tone letters correct, but never the tone contours.

For example the sequence (without spaces) of "˧ ˩ ˥" should render as; ˧˩˥

**Screenshots/Video**

![imgui-tone-letters](https://user-images.githubusercontent.com/18482607/150397855-9aeb8ec8-ec32-4c2e-a717-9c7ab5e4a36c.png)

**Standalone, minimal, complete and verifiable example:** 

As background i'm trying to render the matrix. (to have unlimited minecraft world space)

Absolute coordinate system
　　˧˥˩ ＿＿＿＿＿＿＿＿ ˧˥˦
　　｜＼　　　　　　　：＼
　　｜　＼　　　　　　：　＼
　　｜　　＼　　　　　：　　＼
　　｜　　　˧˥˥－－－－－－－－－˧˦˦
　　｜　　　：　　　　： 　　　 ：
　　˧˩˥ ＿＿＿ ：＿＿＿＿˧˩˨　　　　：
　　＼　　　： 　　　　 ＼　　　：
　　　＼　　： 　　　　　 ＼　　：
　　　　＼　： 　　　　　　 ＼　：
　　　　　＼˧˩˩＿＿＿＿＿＿＿＿＿˧˨˨

Relative coordinate system

　　　 ˩˩˧　　 ˥˦˧　　 ˦˦˧
　　　　＼　｜　／
　　　　　＼｜／
　　　 ˩˥˧－－ Ｏ －－˥˩˧
　　　　　／｜＼
　　　　／　｜　＼
　　　 ˨˨˧　　 ˩˨˧ 　　 ˥˥˧　

Exponential WordQᵤ₈ₑ Tone⋇Kali Darthᵛᴬᴰᴰᴱᴿ

EW₁T5D⁴ = Startrek HEX
˧˥˩˧˩˥˧˥˦˧˩˨˧˦˦˧˨˨˧˥˥˧˩˩˥˩˧˩˥˧˥˦˧˩˨˧˦˦˧˨˨˧˥˥˧˩˩˧

EW₂T5D⁴ = Dīpāvalī Routing
˧˥˩⁰˧˩˥¹˧˥˦²˧˩˨³˧˦˦⁴˧˨˨⁵˧˥˥⁶˧˩˩⁷˥˩˧⁸˩˥˧⁹˥˦˧ᵃ˩˨˧ᵇ˦˦˧ᶜ˨˨˧ᵈ˥˥˧ᵉ˩˩˧ᶠ

EW₃T5D⁴ = 3Dᵛᴼˣᴱˡ Numbers
˧˥˩⁰˧˩˥¹˧˥˦²˧˩˨³˧˦˦⁴˧˨˨⁵˧˥˥⁶˧˩˩⁷˥˩˧⁸˩˥˧⁹˥˦˧ᵃ˩˨˧ᵇ˦˦˧ᶜ˨˨˧ᵈ˥˥˧ᵉ˩˩˧ᶠ = red
˧˥˩₀˧˩˥₁˧˥˦₂˧˩˨₃˧˦˦₄˧˨˨₅˧˥˥₆˧˩˩₇˥˩˧₈˩˥˧₉˥˦˧ₐ˩˨˧₆˦˦˧꜀˨˨˧ₔ˥˥˧ₑ˩˩˧բ = blue
OR
⁰˧˥˩₀¹˧˩˥₁²˧˥˦₂³˧˩˨₃⁴˧˦˦₄⁵˧˨˨₅⁶˧˥˥₆⁷˧˩˩₇⁸˥˩˧₈⁹˩˥˧₉ᵃ˥˦˧ₐᵇ˩˨˧₆ᶜ˦˦˧꜀ᵈ˨˨˧ₔᵉ˥˥˧ₑᶠ˩˩˧բ

That is the basis for relative or unlimited voxel math in 3D space.

**Comment by ocornut** [comment]
> For example the sequence (without spaces) of "˧ ˩ ˥" should render as; ˧˩˥

This is not supported and we don't expect to support parsing of Unicode sequences like that, sorry.

**Comment by immetoo** [comment]
Yes i noticed, so i asked, as it works in (almost) all other applications.
Will try to draw them manually or use an texture as a workaround.
Thank for the quick reply.

**Comment by ocornut** [comment]
> as it works in (almost) all other applications.

We use our own text rendering with really dumb text shaping. There aren't many solutions, bringing in e.g. harfbuzz would largely outweight the library size by one order of magnitude and wouldn't work without massive caching of everything which is far off from how dear imgui is designed. So the TL;DR; is it is unlike we'll ever support that sort of fancy Unicode feature in main line soon, but some people have had success doing that (e.g. #4227). Let's close this to #4227 if anything.
