### ISSUE TITLE
Set Image Position

### ISSUE THREAD

**Issue by HitSploit** [ocornut/imgui#4929]
Hello,

I want to draw an image with imgui but I can't seem to find any parameter that allows me to set the position of the image on the screen. 

I load my texture using:
`HRESULT hr = D3DXCreateTextureFromFileInMemory(g_pd3dDevice, dataImg, sizeof(dataImg), &img);
		if (hr != S_OK) return false;`

Once the texture is successfully loaded I draw it on my overlay using:
`ImGui::GetOverlayDrawList()->AddImage(img, ImVec2(10, 10), ImVec2(0, 0)`

The image is successfully displayed on the screen but it's stuck on top left, could you please guide me so i can set the position of it?

Thank you.

**Comment by ocornut** [comment]
The second parameter you passed is the position.
