### ISSUE TITLE
Proper way to detect click-and-drag ?

### ISSUE THREAD

**Issue by r-lyeh** [ocornut/imgui#493]
What is the best/correct way to deal with click-and-drag behavior?

Ideally, I'd like to know when click, drag and release happens at any moment, and
1) click origin in screen coordinates (absolute)
2) click origin in widget coordinates (relative)
3) the current absolute drag position from the origin

I guess I can determinate (3) by doing by subtracting (1) from current mouse position.

Advices please? :)

**Comment by krys-spectralpixel** [comment]
You can use ImGui::IsMouseDragging(mouseButtonId)

**Comment by ocornut** [comment]
And ImGui::GetMouseDragDelta()
Also check io.MouseClickedPos

**Comment by r-lyeh** [comment]
:+1:

**Comment by moonfrvgs** [comment]
i made something to detect if the user is dragging the UI:

    auto compare_imvec2 = [=](ImVec2 a, ImVec2 b) -> bool {
        if (a.x != b.x)
            return false;
        if (a.y != b.y)
            return false;
        return true;
        };

            if(ImGui::IsKeyDown(ImGuiKey_MouseLeft) && compare_imvec2(mouse_pos, ImGui::GetMouseDragDelta()) == false)
                ImGui::SetMouseCursor(ImGuiMouseCursor_ResizeAll);
