### ISSUE TITLE
Can't make popup appear.

### ISSUE THREAD

**Issue by Stanlyhalo** [ocornut/imgui#4935]
Version: 1.83
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: vs2022
Operating System: win11

**My Issue/Question:**

I have used the `BeginPopupContextItem` before, so I know how to use it mainly. But I wanted for a certain window the ability to press space, and the popup appears where your cursor is (or in the center of the screen). This is essentially my code so far:
``` cpp
static bool spaceDown = false;
ImGuiIO& io = ImGui::GetIO();
if (ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_Space), false)) {
   spaceDown = true;
}
if (spaceDown == true) {
   if (ImGui::BeginPopup("MyPopup##CREATE")) {
      // Stuff goes here
      ImGui::EndPopup();
   }
}
```
I have tested this, and it appears that the spaceDown does become true, and the popup should appear, but nothing happens, am I suppose to specify before the if statement for the `BeginPopup` where the item will be positioned?

**Comment by ocornut** [comment]
You should call OpenPopup() to open a popup. Read demo code and the code of BeginPopupItem() as well.

**Comment by Stanlyhalo** [comment]
Awesome, thanks! Worked like a charm, read into `BeginPopupContextItem()` and saw how that uses the PopupEx methods, and did the same, and worked first try.
