### ISSUE TITLE
Strategy to use user GLFW callbacks with multi-viewports

### ISSUE THREAD

**Issue by ahmidou** [ocornut/imgui#4937]
Version: v1.87
Branch: docking

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: VisualStudio 2022
Operating System: Windows11

In both case of using installed callbacks or not when having user callbacks, if a viewport  is detached the `ImGui_ImplGlfw_Data->Window` is different than the one passed to the callback.
So unless I'm mistaken, the user callbacks are never called in those viewport
it seems to work well, but I was wondering if modifying the backend in `ImGui_ImplGlfw_CreateWindow(ImGuiViewport* viewport)` like this was safe?

```    // Install GLFW callbacks for secondary viewports
    glfwSetWindowFocusCallback(vd->Window, bd->PrevUserCallbackWindowFocus);
    glfwSetCursorEnterCallback(vd->Window, bd->PrevUserCallbackCursorEnter);
    glfwSetCursorPosCallback(vd->Window, bd->PrevUserCallbackCursorPos);
    glfwSetMouseButtonCallback(vd->Window, bd->PrevUserCallbackMousebutton);
    glfwSetScrollCallback(vd->Window, bd->PrevUserCallbackScroll);
    glfwSetKeyCallback(vd->Window, bd->PrevUserCallbackKey);
    glfwSetCharCallback(vd->Window, bd->PrevUserCallbackChar);```

**Comment by ocornut** [comment]
First question will always be: why do you need callbacks to be called on secondary viewports ? Which ones will you need ?

**Comment by ahmidou** [comment]
I'm trying to find a way to swap mouse/key behaviors based on Tool/Manipulator contexts in multiple 3D/2D viewports.

The idea is also to keep the drawing code separated from the mouse/keys handling as much as possible so I'd like to have them handled in callbacks vs inside ImGui::Begin()/ImGUi::End().
This also makes the behavior localized in the relevant classes instead of having complex switch case or conditions
I'm using the method explained here:
[https://stackoverflow.com/a/21800960/2301924](https://stackoverflow.com/a/21800960/2301924)

It's working well, but as soon as a viewport is detached, it loses the ability to swap the callbacks as it's just using the backend provided ones.

**Comment by ocornut** [comment]
Technically you could rewire `platform_io.Platform_CreateWindow()` to call your own function, call the original function, then install new callbacks and make them call our callbacks.

**Comment by ahmidou** [comment]
Thanks for the suggestion, that a good idea and it's working well!

**Comment by ocornut** [comment]
I'll close this then.
