### ISSUE TITLE
Screen goes black for a second when opening ``example_glfw_opengl3`` on macOS 10.15.7

### ISSUE THREAD

**Issue by gaze** [ocornut/imgui#4939]
**Version/Branch of Dear ImGui:**

Version: HEAD (08f3aa8)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: ``imgui_impl_glfw.cpp``/``imgui_impl_opengl3.cpp``
Operating System: macOS 10.15.7

**My Issue/Question:**

When launching the example ``example_glfw_opengl3``, I see the icon in the tray expand about half way, then the screen goes completely black for between half a second and a second, and when the screen returns I see the example program and it's completely functional.

**Standalone, minimal, complete and verifiable example:**

The ``example_glfw_opengl3`` example available in the repository.

**Comment by ocornut** [comment]
Hello,

That almost certainly has nothing to do with Dear ImGui but something in the GLFW/GL combo. Would be good to confirm by stripping away all the ImGui calls from that application.
