### ISSUE TITLE
IM_ASSERT(viewport->RendererUserData == NULL && viewport->PlatformUserData == NULL) in ImGui_ImplWin32_Shutdown() 

### ISSUE THREAD

**Issue by SimpsonGSD** [ocornut/imgui#4941]
**Version/Branch of Dear ImGui:**

Version: f1a073186c859facfc75823302b5c5b04f43293f
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_vulkan.cpp
Compiler: msvc
Operating System: Windows 10

**My Issue/Question:**

Hi, I am getting the assert `IM_ASSERT(viewport->RendererUserData == NULL && viewport->PlatformUserData == NULL);` when calling `ImGui_ImplWin32_Shutdown() `. 

I have `ImGuiConfigFlags_DockingEnable` but not `ImGuiConfigFlags_ViewportsEnable`. 

Should the call to `ImGui_ImplWin32_ShutdownPlatformInterface();` be wrapped in `if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)` like `ImGui_ImplWin32_InitPlatformInterface()`? 
Doing this fixes my issue but it could also be user error on my part.

Thanks.

**Comment by ocornut** [comment]
> ImGui_ImplDX12_Shutdown
> imgui_impl_vulkan.cpp

Please clarify the inconsistency above.

Also please test and see if it happens with stock examples.
Thank you :)

**Comment by SimpsonGSD** [comment]
Apologies! Updated - it should say Win32 not DX12..
I will test the examples.

**Comment by ocornut** [comment]
Basically the assert imply you should shutdown the renderer backend before the platform backend.
But as per #4656 and bac748fa95ac003c7b354139980f8b4b7f6ac5da we supposedly lifted that, so it is strange.
If I swap the calls in `example_win32_directx11/main.cpp` it still works.
So you will need to investigate what else you may be doing wrong....

Normally either backend would end up calling `ImGui::DestroyPlatformWindows()` which will call through the `g.PlatformIO.Renderer_DestroyWindow()` and `g.PlatformIO.Platform_DestroyWindow()` handler for all viewports.

**Comment by SimpsonGSD** [comment]
I tested the examples and could not reproduce - though there is no combination of win32+vulkan I still couldn't repro in examples that used one of these. 
I am indeed shutting down the platform before the renderer. I will try reversing them.

**Comment by SimpsonGSD** [comment]
I called `ImGui_ImplVulkan_Shutdown()` before `ImGui_ImplWin32_Shutdown()` but then I get a different assert:
`IM_ASSERT(bd != NULL && "No platform backend to shutdown, or already shutdown?");`

**Comment by SimpsonGSD** [comment]
Found the issue.
Originally I was calling 
`ImGui_ImplWin32_Shutdown()` then 
`ImGui_ImplVulkan_Shutdown()`

I swapped them around and got a different assert but what I actually found was this order
`ImGui_ImplVulkan_Shutdown()`
`ImGui::DestroyContext()`
`ImGui_ImplWin32_Shutdown()`

Changing it to the expected order is fine:
`ImGui_ImplVulkan_Shutdown()`
`ImGui_ImplWin32_Shutdown()`
`ImGui::DestroyContext()`
