### ISSUE TITLE
Unicode right-to-left mark (RLM+LRM) for Hebrew

### ISSUE THREAD

**Issue by immetoo** [ocornut/imgui#4943]
**Version/Branch of Dear ImGui:**

Version: 1.86

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_java_impl_glfw within libGDX
Operating System: Debian

**My Issue/Question:**

Could the unicode directions marks be supported for auto reversal of the text code points ?

left-to-right mark (LRM) - 0x200E
right-to-left mark (RLM) - 0x200F

Now when rendering Hebrew, the text is reversed and the vowels are misaligned.
With an hardcoded reversal workaround, the text renders correct in Imgui.

**Screenshots/Video**

![imgui-hebrew-wallet](https://user-images.githubusercontent.com/18482607/151152108-bab883b0-0f91-4300-8ef9-08a7ba47a306.png)

**Standalone, minimal, complete and verifiable example:**

As seen in source, the Hebrew is displayed reversed in Imgui and breaks the font vowel rendering.
```
		String[] walletData = {
				"ה","מ","מָ","ח","חֱ","חֱ‎מָא",
				"א","בד","ב","ד","ץףן",
				"הזפץ","מספר","צצצצ","ץאאא","דואר"
			};
		for (String data:walletData) {
			HebrewGê̄ld geld = new HebrewGê̄ld(data);
			ImGui.tableNextRow();
			ImGui.tableNextColumn();
			ImGui.text(data.length()==2||data.length()==3?"OUT":"IN");
			ImGui.tableNextColumn();
			ImGui.text(data);
			ImGui.tableNextColumn();
			ImGui.text(geld.toHebrewString(true)); // true=reverse for ImGui
			ImGui.tableNextColumn();
			ImGui.text(Double.toString(geld.getTotalDecimalValue()));
		}
```

**Comment by ocornut** [comment]
Hello,
We don't support RTL text not text shaping.

> Could the unicode directions marks be supported for auto reversal of the text code points ?

Probably not anytime soon but the best would be to move that discussion to #4227.

**Comment by immetoo** [comment]
Clear will wait until #4227 gets merged.
