### ISSUE TITLE
Is it possible to render ImGui UI to Texture instead of BackBuffer?

### ISSUE THREAD

**Issue by sparkskapil** [ocornut/imgui#4946]
I am working on my game engine and I am using ImGui for the user interface for the Editor.
I also want the game to use ImGui for Menu and UI, so I want to know is it possible to render ImGui Frame to Texture.
My Engine renders the game to a texture when working with Editor and Editor displays it on ImGui Window.
I would like to do the same for ImGui UI for game. User should be able to create UI with my ECS and see the result in the IMGui Window.

**Comment by PathogenDavid** [comment]
Please don't ignore the issue template, it's there for a reason. 

Dear ImGui doesn't care what you render to. It doesn't actually render anything at all until you invoke the rendering backend (IE: with `ImGui_Impl***_RenderDrawData`.) If you have the back buffer bound it renders to that. If a render target texture bound then it renders to that.

If your texture won't line up with your output window you will need to mess with the platform backend (or make your own.)

**Comment by ocornut** [comment]
Closing as answered, this is not really a question related to dear imgui.

> If your texture won't line up with your output window you will need to mess with the platform backend (or make your own)

That said, if standard backends for some renderer are getting in the way of allowing render-to-texture without having to make a change to the backend, we're open to make changes to facilitate it.

**Comment by sparkskapil** [comment]
Thanks for the help.
