### ISSUE TITLE
ImGui::InputText() spamming the first character typed into the text box.

### ISSUE THREAD

**Issue by Riser777** [ocornut/imgui#4958]
I'm using ImGui with SFML and I'm trying to make a text-box that stores a file path.

![image](https://user-images.githubusercontent.com/71282865/151623792-a7a7f2c3-9afa-4be8-8ead-92e3918189d9.png)

I followed what DJLink did in #2487 but what keeps happening is that the textbox will start repeating the first character typed into it until the entire buffer is filled with the same repeated character, example:

![image](https://user-images.githubusercontent.com/71282865/151623831-4b789318-8240-4961-b2c3-a7ba2d96a23f.png)
![image](https://user-images.githubusercontent.com/71282865/151623901-e28ca0c0-b660-459f-aeed-cd4d2079fc7e.png)

I also tried moving the buffer inside the loop and got the same result, what am I doing wrong?

**Comment by ocornut** [comment]
Hello,

As we don't know what SFML::Update does, please ask on SFML imgui issue tracker.
