### ISSUE TITLE
Customize the window scrollbar

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#496]
Hi,

I currently have a scrollbar on a window, but I would like to customize it this way :

![image](https://cloud.githubusercontent.com/assets/6149696/12452963/5a14b206-bf91-11e5-9268-3aa83db904b6.png)

On this image you see a "slider" and the window's scrollbar.

The goal is to have the scrollbar to only scroll a portion (the red zone) of the window content !

Is it possible to do such feature ? By example, can I create my own scrollbar and rescale the scroll-x value ?

**Comment by ocornut** [comment]
I am not sure to understand your question. It is about individual framed scrolling or about the scrollbar themselves? Child windows have independent scrolling, this is the point of child windows. You can create child windows anywhere and controls their scroll with a scrollbar or with API calls (various Scroll functions).

**Comment by krys-spectralpixel** [comment]
In fact I need to create my own horizontal scrollbar but I haven't see any scrollbar widget, right ?

Simply because this scrollbar is not related to the whole window content, but just a part of it !

**Comment by ocornut** [comment]
But if you want the horizontal scrollbar just below your scrollable contents why not using a child window?

**Comment by krys-spectralpixel** [comment]
Because I'm currently doing something similar to this :

![image](https://cloud.githubusercontent.com/assets/6149696/12453851/5f98b368-bf95-11e5-99d1-f6932e3df957.png)

There is a tree on the left:
- the horizontal scrollbar concern only the right part
- the vertical scrollbar concern both the tree and the right part

**Comment by ocornut** [comment]
OK so Scrollbar() isn't exposed but you can copy that and have it apply its output to the child window that carries the right-side. Or you can have both scrollbars inside the child window that carries the right-side and copy the scroll Y value from the child to the parent.

**Comment by krys-spectralpixel** [comment]
Thanks,

I have find a solution by using the "columns", but it remain a stupid issue... I need to set the first column width (in pixels) at initialization. How can I do ?

I have try this (pseudo code):

```
ImGui::Columns(2, "AB");
ImGui::SetColumnOffset(0, 300.f);
    
// Draw tree here

 ImGui::NextColumn();

// Draw graph here

```

I only put pseudo code to avoid adding to much code and adding confusion !
Is it the way it should work ? It is the right method to use ?

**Comment by ocornut** [comment]
I don't understand how columns are related, I gave you two possible solutions above. Use BeginChild/EndChild and transfer the vertical scrolling data from one window to another.

**Comment by ocornut** [comment]
`
BeginChild("left", ImVec2(left_width, 0));
...
EndChild()
SameLine()
BeginChild("right", ImVec2(0, 0))
float y = GetScrollY()
EndChild()
BeginChild("left");
SetScrollY(y);
EndChild();
`

**Comment by krys-spectralpixel** [comment]
I have completely redo the design of the control... something more clean and easier to maintain. 
The columns are there because I have 2 windows:
1) the first contains the tree (no horizontal scroll)
2) the second contains the graph (with scrollable zone)

The columns also allow to resize the tree width.

Everything looks to work, except the left colum size that is too big !

**Comment by krys-spectralpixel** [comment]
My code looks like yours :

```
ImGui::Columns(2, "AB");

	BeginChild("left", ImVec2(left_width, 0)); 
		// Draw tree here
	EndChild()

ImGui::NextColumn();
 

	BeginChild("right", ImVec2(0, 0)); 
		// Draw graph
	EndChild();
```

**Comment by ocornut** [comment]
Set than ImGui::SetColumnOffset() on start.

**Comment by krys-spectralpixel** [comment]
Thanks, it is fixed :-P

**Comment by ocornut** [comment]
Cool.
