### ISSUE TITLE
Style question

### ISSUE THREAD

**Issue by AbbyIOM** [ocornut/imgui#4961]
**My Issue/Question:**

Hello, i'm using DX9 as a renderer for imgui and so far i'm enjoying it! But i wonder how could i replicate something like this. (screenshot below). I was reading few articles but i'm not familiar with shaders at all. Is there any clear documentation on how to apply a effect like this over a imgui drawings? I tried adding a shader but the result was very pixelated and wasn't even close to that picture.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/89664487/151657654-5cee1cae-a7df-49a1-9972-bed2778f8a0c.png)

Regards,
Abby

**Comment by PathogenDavid** [comment]
This is outside the scope of what Dear ImGui will do for you. You're probably better off figuring out blurring outside the context of Dear ImGui and then working on applying it to it.

That being said, see similar question with answer at https://github.com/ocornut/imgui/issues/1117 (Note that Unrimp does not appear to use this affect anymore, so you'll want to look at the codebase as it was when it was linked: [cofenberg/unrimp@45aa431286](https://github.com/cofenberg/unrimp/tree/45aa431286ce597c018675c1a9730d98e6ccfc64))

**Comment by AbbyIOM** [comment]
Hi, thank you.
I'm looking at it and i'm little confused where is it being applied.

**Comment by ocornut** [comment]
This is not really a question about dear imgui but rather about how you want implement a custom render with those custom blur shaders. It's not a trivial thing to setup and at the moment we don't have resources to open that kind of tangential open-ended questions, this is more something to ask on graphics programming forums.

**Comment by ocornut** [comment]
Also note this post on the topic
https://github.com/ocornut/imgui/issues/5886#issuecomment-1517035334
