### ISSUE TITLE
Graphical OpenGl issues when working in dockspace

### ISSUE THREAD

**Issue by Itschowthing** [ocornut/imgui#4968]
I'm having an issue where the panels when passing over other objects will glitch out and cause artefacts. I was experiencing issue with my own project so I went to the demo and I'm still getting the same issue. does anyone know how to help?
 
https://user-images.githubusercontent.com/98675655/151684350-c7dfaa3f-eb63-4fec-8294-092300c7bf7b.mp4

**Comment by debater-coder** [comment]
I also experience this issue, but for me it happens when the window moves outside the main viewport.

**Comment by ocornut** [comment]
Hello,
This has nothing to do with docking but rather with multi-viewports. It appears to be the same issue as #4832 so closing as duplicate. Will try to solve before we release 1.87 but you can apply the fix listed in that thread.
