### ISSUE TITLE
Specify side for docking

### ISSUE THREAD

**Issue by NePutin94** [ocornut/imgui#4969]
I want to specify for ```DockSpace``` side (top, left, etc.) to which the window will be attached, can I do this? .inl file remembers side, but it's not very convenient. I am using latest version of imgui from docking branch.

**Comment by ocornut** [comment]
Currently for programmatic manipulation of docking state you can use the DockBuilderXXX\ api in imgui_internal.h that's the only way.

**Comment by NePutin94** [comment]
Can you give a small example please?

**Comment by NePutin94** [comment]
I did something like this:
```C++
host-window
ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), ImGuiDockNodeFlags_None);
once-block:
 id = ImGui::DockBuilderSplitNode(node->ID, ImGuiDir_::ImGuiDir_Left, 0, &id1, &id2);
 ImGui::DockBuilderFinish(dockspace_id);
 ImGui::SetNextWindowDockID(id1);
render-window
```
Is it right?
After ```DockBuilderSplitNode``` i will get 3 nodes: root and two new id1, id2. But why is the window attached to "id2" in the center, if the center is root node(parent for id1, id2).
