### ISSUE TITLE
IsItemClicked() does not work when tab is newly selected

### ISSUE THREAD

**Issue by nobody-special666** [ocornut/imgui#4970]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_allegro5.cpp
Compiler: gcc
Operating System: ubuntu

**My Issue/Question:**

Hi all,
I'm trying to detect whenever a tab is clicked.
If the "Broccoli" tab is already the current tab, then isItemClicked() returns true and my popup appears, as expected.
But if another tab is current, and the "Broccoli" tab is then clicked, then isItemClicked() returns false and there is no popup.
Is this behavior intentional, and if so then how do I catch when the tab is newly selected?

Thanks for any help.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/901271/151704337-33d99610-a0c4-4820-a966-05a5727c96a2.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```C++
        IMGUI_DEMO_MARKER("Widgets/Tabs/Basic");
        if (ImGui::TreeNode("Basic"))
        {
            ImGuiTabBarFlags tab_bar_flags = ImGuiTabBarFlags_None;
            if (ImGui::BeginTabBar("MyTabBar", tab_bar_flags))
            {
                if (ImGui::BeginTabItem("Avocado"))
                {
                    ImGui::Text("This is the Avocado tab!\nblah blah blah blah blah");
                    ImGui::EndTabItem();
                }
                if (ImGui::BeginTabItem("Broccoli"))
                {
                    // BUG: popup doesn't show when tab is newly selected
                    {
                        if (ImGui::IsItemClicked())
                            ImGui::OpenPopup("MyTestPopup");
                        if (ImGui::BeginPopup("MyTestPopup"))
                        {
                            ImGui::Text("You clicked me!");
                            ImGui::EndPopup();
                        }
                    }
                    ImGui::Text("This is the Broccoli tab!\nblah blah blah blah blah");
                    ImGui::EndTabItem();
                }
```

**Comment by Nightfallen** [comment]
You are calling `IsItemClicked` inside if statement, so until it's clicked and "Broccoli" selected, popup wouldn't be revealed on the screen.
I'm not sure whether there is more elegant solution but you can try to rewrite code like this
```cpp
auto bResult = ImGui::BeginTabItem("Broccoli");
if (ImGui::IsItemClicked())
{
	printf("Broccoli clicked\n");
	ImGui::OpenPopup("MyTestPopup");
}
if (ImGui::BeginPopup("MyTestPopup"))
{
	ImGui::Text("You clicked me!");
	ImGui::EndPopup();
}

if (bResult)
{
	ImGui::Text("This is the Broccoli tab!\nblah blah blah blah blah");
	ImGui::EndTabItem();
}
```
But somewhy popup still doesn't seem to appear, maybe i'm missing something

**Comment by nobody-special666** [comment]
Found a fix. It seems I have to test for IsItemClicked() both inside and after the BeginTabItem/EndTabItem() clause.
Thanks for the help.

```C++
                if (ImGui::BeginTabItem("Broccoli"))
                {
                    if (ImGui::IsItemClicked())
                    {
                        ImGui::OpenPopup("MyTestPopup");
                    }
                    ImGui::Text("This is the Broccoli tab!\nblah blah blah blah blah");
                    ImGui::EndTabItem();
                }
                if (ImGui::IsItemClicked())
                {
                    ImGui::OpenPopup("MyTestPopup");
                }
                if (ImGui::BeginPopup("MyTestPopup"))
                {
                    ImGui::Text("%s", "You clicked me!");
                    ImGui::EndPopup();
                }
```
