### ISSUE TITLE
Tab Windows

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#498]
Hello

Do anyone know how I can setup tab windows? 

Like

https://www.youtube.com/watch?v=8BRFPY7QSvo

Vivienne

**Comment by Roflraging** [comment]
I think you've already seen this https://github.com/ocornut/imgui/issues/261 and https://gist.github.com/Roflraging/fe9a582cb7a79400b667.  The sections of interest are:

https://gist.github.com/Roflraging/fe9a582cb7a79400b667#file-gistfile1-cpp-L1-L19
https://gist.github.com/Roflraging/fe9a582cb7a79400b667#file-gistfile1-cpp-L180-L213
https://gist.github.com/Roflraging/fe9a582cb7a79400b667#file-gistfile1-cpp-L243-L296

A lot of the code there is specific to the game I'm working on, but you should be able to figure out the general approach pretty easily from those sections.

**Comment by ocornut** [comment]
Also check https://github.com/ocornut/imgui/issues/351
