### ISSUE TITLE
ImGui stops working when used with two surfaces/windows/renderloops/contexts etc.

### ISSUE THREAD

**Issue by CarloWood** [ocornut/imgui#4980]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: commit 4fb0c1f9639679402ea005ec70b807d96a072505 (master)

**Back-end/Renderer/Compiler/OS**

Back-ends: custom xcb/xkb, custom vulkan (opensource, its on github)

Operating System: linux

**My Issue/Question:**

When I run _one_ window (aka, one vulkan surface, one swapchain, one render graph, one render loop, ...)
everything works perfectly.

When I open two windows (doesn't matter what, as long as both use imgui; ie, twice the same window), it SHOULD work perfectly (it does without imgui; or when only one uses imgui): I then have two of everything; two render loops (at different FPS) etc. But what happens is that imgui stops working correctly.

It took me a while to realize that this is to be expected, since I am using for both a single ImGui context by executing:

    ImGuiIO& io = ImGui::GetIO();
    
which seems to be a global function that cannot be aware of which window is calling it %-).

Then I realized that there is support for something like this with `Multiple Viewports` on the docking branch.
I read https://github.com/ocornut/imgui/wiki/Multi-Viewports but I have some questions left:

My vulkan engine and (custom) imgui backends are 100% object oriented and will not have ANY problem running multiple windows in parallel; yet that page states "If you are using a custom back-end, refer to the ImGuiPlatformIO structure and existing backends/ + examples/ to implement support for multi-viewports in your engine. This is not particularly easy to add."

It also says "The feature tends to be broken on Linux/X11 with many window managers."

I do not understand why that would be the case.  All I need is a way to separate all (currently global) variables of imgui. Two contexts, two whatever - absolutely nothing that is static or global.  Is this not supported? Why would you need to have window positions? My engine works exclusively with coordinates relative to the window (I get the absolute coordinates too in XCB messages, but I ignore them as not interesting). Every XCB event that I receive tells me which window the event is about. There can not be a problem that I can think of having many other windows that do that same thing.

**Comment by PathogenDavid** [comment]
I think you have a fundamental misunderstanding of what the multi-viewport feature actually does. I would suggest running the examples from the `docking` branch and interacting with it yourself.

> All I need is a way to separate all (currently global) variables of imgui. Two contexts, two whatever - absolutely nothing that is static or global. Is this not supported?

You need to use `ImGui::SetCurrentContext` to switch between your two contexts.

If you need to be able to use the two separate contexts at the same time from two different threads you can redefine `GImGui` to be thread-local.

**Comment by CarloWood** [comment]
Thanks for the quick response. And yeah, having learned more about the multi-viewport feature, that is not what I need. What I need is having thread-safe multiple contexts that do not require locking :/. That seems to mean that you have to pass the context to every ImGui function, which makes me wish they were simply class methods.

Calling `ImGui::SetCurrentContext` doesn't sound like it can work without also a mutex around the whole section where the context is being used, which seems a bit silly when that is just to protect a global variable that only exists to avoid passing the context to every function call separately. Alternatively, the global could be thread-local; then this could work.

Heh - ok. So next I looked at `ImGui::SetCurrentContext` to find out if maybe it was already thread-local and found the #define's hackery, and the comments that come with

    #ifndef GImGui
    ImGuiContext*   GImGui = NULL;
    #endif

This looks like promising hooks. Maybe I am still missing other global variables though?
My engine is 100% unforgiving when it comes to sharing variables: I have 32 threads in a pool that run pieces of code in a random order. The only reason I could use a thread-local pointer is it is set for each code block (that is obviously then executed by a thing thread); which is probably the design idea of imgui.

Still wishing everything was a C++ class - but that's just me I guess :/.

**Comment by PathogenDavid** [comment]
> Maybe I am still missing other global variables though?

`GImGui` is the only mutable global variable.

> which is probably the design idea of imgui.

Dear ImGui isn't really designed with multi-threaded use in the first place. Make sure you don't have multiple threads submitting UI to the same context at the same time or things will go bang.

**Comment by CarloWood** [comment]
I got it working. In case someone else runs into this problem and sees this; here are the changes that I needed to make to get it to work: https://github.com/CarloWood/linuxviewer/commit/c4a7ebec1632d37fd6b98f6dcbde707b1ac147b5
