### ISSUE TITLE
GLFW Callbacks after ImGui initialization

### ISSUE THREAD

**Issue by cajallen** [ocornut/imgui#4981]
**Version/Branch of Dear ImGui:**

Version: 1.87 WIP (18608)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

**My Issue/Question:**
How are custom callbacks supposed to be set with GLFW post ImGui initialization? I would prefer to allow ImGui to install it's callbacks and not have to worry about calling them in my own code, which seems to be supported outside of this case.

**Screenshots/Video**
None

**Standalone, minimal, complete and verifiable example:**
```cpp
int main () {
    // Window Creation... etc...
    glfwSetKeyCallback(window, my_key_callback);
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
    ImGui_ImplGlfw_InitForOpenGL(window, true); 
    // At this point,  ImGui_ImplGlfw_GetBackendData()->PrevUserCallbackKey is my_key_callback
    ImGui_ImplOpenGL3_Init("#version 450");
    
    glfwSetKeyCallback(window, my_new_key_callback);
    // How to set state so that GLFW key callback is ImGui's, and 
    // ImGui_ImplGlfw_GetBackendData()->PrevUserCallbackKey is my_key_callback?
}
```

**Comment by ocornut** [comment]
```
    glfwSetKeyCallback(window, my_new_key_callback);
    // How to set state so that GLFW key callback is ImGui's, and 
    // ImGui_ImplGlfw_GetBackendData()->PrevUserCallbackKey is my_key_callback?
```

You can't do that, what you need to do is to call `ImGui_ImplGlfw_KeyCallback()` from my_new_key_callback().

You may store the return value of glfwSetKeyCallback() which in this case will be == ImGui_ImplGlfw_KeyCallback.

I guess in theory we could provide a `ImGui_ImplGlfw_InstallCallbacks()` helper to do that later, but that would need to work for multi-viewports and its pushing extra complexity on our end.

**Comment by ocornut** [comment]
I added `ImGui_ImplGlfw_InstallCallbacks()` to help with that..

**Comment by ocornut** [comment]
The typical way would be to initialize your callbacks before initializing the backend.
This new addition indeed makes it a little more fiexible.

**Comment by dhruvthanki** [comment]
Hello @ocornut @cajallen!
I am facing a similar issue. If I understand correctly, I just need to install my glfw callbacks before calling `ImGui_ImplGlfw_InitForOpenGL` with a `true` bool in the second argument and that should basically chains the callbacks. But the result is still not what I am looking for. When I try and move an imgui window around in the glfw window it also moves the 3d scene in the background as long as the imgui window is still inside the glfw window. Once I pull the imgui window out of the glfw window everything freezes and then when I pull it back into the glfw window, the imgui window disappears and everything freezes except the other imgui windows. [Github Code](https://github.com/dhruvthanki/ImMuJoCo.git)

**Comment by dhruvthanki** [comment]
Hello @ocornut @cajallen!
I am facing a similar issue. If I understand correctly, I just need to install my glfw callbacks before calling `ImGui_ImplGlfw_InitForOpenGL` with a `true` bool in the second argument and that should basically chains the callbacks. But the result is still not what I am looking for. When I try and move an imgui window around in the glfw window it also moves the 3d scene in the background as long as the imgui window is still inside the glfw window. Once I pull the imgui window out of the glfw window everything freezes and then when I pull it back into the glfw window, the imgui window disappears and everything freezes except the other imgui windows. [Github](https://github.com/dhruvthanki/ImMuJoCo.git) code, this is what I have:
```cpp
int main () {
    // Window Creation... etc...
    glfwSetKeyCallback(window, my_key_callback);
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
    ImGui_ImplGlfw_InitForOpenGL(window, true); 
    ImGui_ImplGlfw_SetCallbacksChainForAllWindows(true);
    ImGui_ImplOpenGL3_Init("#version 450");
    while (!glfwWindowShouldClose(window)) {
    ... Imgui stuff ...
    }
}
```
Any help or a mwe of how it should be would be greatly appreciated. Thank you!

**Comment by PathogenDavid** [comment]
@dhruvthanki Chained callbacks are always called for the main viewport (IE: The window you created.)

To avoid handling inputs when Dear ImGui wants to use them, you can check the value of `ImGuiIO::WantCaptureMouse` and `ImGuiIO::WantCaptureKeyboard`:

https://github.com/ocornut/imgui/blob/9a5da23553bccaa138651f0410bcc8c5c05cc255/imgui.h#L2091-L2092

------------------

> Once I pull the imgui window out of the glfw window everything freezes and then when I pull it back into the glfw window, the imgui window disappears and everything freezes except the other imgui windows.

This sounds like a different/unrelated issue and will likely take more investigation on your part.

A good strategy is to go through `main.cpp` for the applicable Dear ImGui example line by line and compare it to your code to make sure nothing is missing.

If you're still stuck after investigating more on your own, you should open a separate issue. Make sure you fill out the issue template.

**Comment by dhruvthanki** [comment]
@PathogenDavid The solution for the first problem worked! I will look more into the second problem. Thank you!
