### ISSUE TITLE
LV2 plugin crashes host on creation of second instance.

### ISSUE THREAD

**Issue by tomasguillen** [ocornut/imgui#4983]
**Version/Branch of Dear ImGui:**
```
commit 31762a81734301e620f4f075a7ddaf41ab8f9de7 (HEAD -> docking, origin/docking)
Author: ocornut <omarcornut@gmail.com>
Date:   Thu Feb 3 12:04:11 2022 +0100

    Docking: fixed potential crash if a passthrough dock node is submitted without a child intermediate (currently not possible via API)
```

**Back-end/Renderer/Compiler/OS**
SDL2/GL3/gcc/archlinux

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
#include "imgui_impl_sdl.h"
#include "imgui_impl_opengl3.h"

Compiler: GCC, compiling as SHARED LIBRARY for Ardour LV2
Operating System: Archlinux

**My Issue/Question:**
I have an LV2 plugin that I'm developing. It works perfectly with one window as an LV2 plugin. The way LV2 works is I compile my app as a shared library, and then my DAW (ardour) searches in a specific path and loads it. I'm not supposed to export symbols other than what lv2 specification tells me to, my plugin works perfectly with one instance. IE: I add a plugin(my IMGUI app) to an audio track, it breaks when I add a second instance to another audio track.

Here is what I've tried:
Looking at the coredump for ardour after it crashes:

Keep in mind custom_imgui_impl_sdl.cpp is just a copy of the original. It was different previously because there were some issues with focusing but that has been fixed in recent versions.
```
#4  0x00007f0750d5b94b in ImGui_ImplSDL2_Init (window=0x556b1ae64ca0, sdl_gl_context=0x556b1ae66348)
    at /home/tom/builds/midirealtimeprojects/MidiWrangler/ui_libraries/custom_imgui_impl_sdl.cpp:350
350         IM_ASSERT(io.BackendPlatformUserData == NULL && "Already initialized a platform backend!");
```
Full backtrace: https://pastebin.com/3NarDhUP

So after seeing that assert failing I tried conditionally initializing the new context:
```
  if(io.BackendPlatformUserData == NULL){
  // Setup Platform/Renderer backends
    ImGui_ImplSDL2_InitForOpenGL(window, gl_context);
    ImGui_ImplOpenGL3_Init(glsl_version.c_str());
  }
```
That got me past that assert, however, it still didn't work because now I get a new assert error when I add the second instance:
```
#4  0x00007f6bf8d7c574 in ImGui::ErrorCheckNewFrameSanityChecks ()
    at /home/tom/builds/midirealtimeprojects/MidiWrangler/ui_libraries/imgui/imgui.cpp:8549
8549        IM_ASSERT(g.IO.Fonts->IsBuilt()                                     && "Font Atlas not built! Make sure you called ImGui_ImplXXXX_NewFrame() function for renderer backend, which should call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()");
```
BT: https://pastebin.com/EZAzE1GH

I've added ImGui_ImplSDL2_NewFrame() to frame loop just before ImGui::NewFrame(); I also tried:
```
ImFontAtlas* atlas = new ImFontAtlas();
ImGui::CreateContext(atlas);
```
Results are the same. I tried switching to docking branch but I feel like now I would have to somehow restructure my program so that it has a main loop and it manages both instances from there? I'm not sure if that is possible with the way LV2 is architectured.

Is there any way I can have two separate instances that use the same context somehow? or use 2 different contexts?

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
I find it really hard to create this, it's dependent on loading the app as a shared library, I'm hoping someone who is knowledgeable on ImGui can tell me if it's even possible to use different contexts when it's being loaded as a shared library (.so file). Or how else can I manage the same context from different frame loops.

Thank you for your time!

**Comment by rokups** [comment]
It really is hard to offer any advice given we do not have a faintest idea of how your code is structured.

**Comment by tomasguillen** [comment]
Okay, let me try to explain. Let's say to use a certain framework where you must compile the SDL/opengl3 example as a shared library. When you go to use your application it's loaded fine the first time, the second time it will fail because of the above coredumps. It doesn't depend on how my code is structured at all. It could just be the example application. Let me know if that makes sense

**Comment by rokups** [comment]
Dear ImGui is specifically written in a way to make it possible for multiple application contexts to coexist. Are you sure you are properly switching between contexts using `ImGui::SetCurrentContext()`? If you believe it is a library error you could try to replicate crash in a sample application. It is really hard to offer any help when we can not reproduce the issue and we do not know anything about your source code.

**Comment by sonoro1234** [comment]
Perhaps threading issue?
Context should be compiled with TLS (thread local storage)

**Comment by tomasguillen** [comment]
Thank you everybody for your help. I just got some time to work on this and I've resolved the issue. For those interested or if in the future someone stumbles up this by googleing for "how to create an app with multiple context for imgui". The way I fixed this was by finding out what LV2 was doing when adding the second plugin. Turns out I didn't need TLS because it was all running in the same thread.

1. The first thing I did was to store the SDL_GLContext opengl context and SDL_Window in a class that is initialized every time a new instance of the plugin is started.
2. Store the imgui context in a class that is initialized every time a new instance of the plugin is started.
```
auto *imgui_context = ImGui::CreateContext();
ImGui::SetCurrentContext(imgui_context);
necessary_runtime_data.runtime_imgui_context = imgui_context;
```
3. At the start of every new frame, call SetCurrentContext to switch to the correct imgui context and also call SDL_GL_MakeCurrent to switch to the correct opengl and sdl window.
```
ImGui::SetCurrentContext(necessary_runtime_data.runtime_imgui_context);
SDL_GL_MakeCurrent(backend_runtime_data.window, backend_runtime_data.gl_context);
```
4. If you try to load the pluging at this point, the application will not crash and it should look like the graphical part is working properly, but the window events will apply to both windows at the same time (if you hover with the mouse over an element it will also hover over the same place for the other window. For this you need to change the way the SDL event polling to only take into account the events that are meant for each window. I did it the following way, there are better ways but this is good enough for my use:
```
  SDL_Event event;
  // vector to store the polled events this window doesn't use 
  std::vector<SDL_Event> events_to_requeue{};

  while (SDL_PollEvent(&event)) {
    // check if polled event was meant for this instance
    const bool event_meant_for_this_window =
      event.window.windowID == SDL_GetWindowID(backend_runtime_data.window);

    // if event not meant for this window store it in the vector for it to be requeued after the while loop
    if(!event_meant_for_this_window){
      events_to_requeue.push_back(event);
      continue;
    }
    // give the event to imgui to process it
    ImGui_ImplSDL2_ProcessEvent(&event);
    // additionally handle SDL_WINDOWEVENT_CLOSE and or SDL_QUIT if needed
    ....
  }
  // requeue all the events we didn't use in the while loop
  for(auto event_to_be_requeued: events_to_requeue){
    SDL_PushEvent(&event_to_be_requeued);
  }
```
5. Change the cleanup to use the contexts we stored in the classes
```
  ImGui::DestroyContext(imgui_context);

  SDL_GL_DeleteContext(backend_runtime_data.gl_context);
  SDL_DestroyWindow(backend_runtime_data.window);
```
6. You may need to additionally omit usage of SDL_Quit() or your application might crash when closing one of the windows.
