### ISSUE TITLE
Doc comment for bool* p_opened in ImGui::Begin should change

### ISSUE THREAD

**Issue by serge-rgb** [ocornut/imgui#499]
version 1.47. imgui.h, line 118
> 'bool* p_opened' creates a widget on the upper-right to close the window (which sets your bool to false)

If I am not mistaken, the call to ImGui::Begin calls CloseWindowButton which *toggles* the bool.

So, this usage is valid, even though it contradicts the documentation of the function.

```
bool closed = false;

ImGui::Begin(...., &closed, ..);
if ( closed ) {
   do_something_when_closed();
}
```

**Comment by Roflraging** [comment]
I believe you're misunderstanding the comment.  It's simply saying that if you provide the parameter, the library will enable the close window button, and if you close the window with the button, that boolean will be set to false.

**Comment by Roflraging** [comment]
Ah, sorry, yes you may be right on this.  I just checked the implementation and it does the following in CloseWindowButton():

```
    if (p_opened != NULL && pressed)
        *p_opened = !*p_opened;
```

**Comment by ocornut** [comment]
I fixed the code to explicitly set it to false.
 
Begin() doesn't really expect and handle that boolean to ever be false. It could possibly handle it and avoid ANY drawing but we'd need still allow widget code to fail gracefully (probably open the window data in collapsed mode). Typically you want to not call the code when your boolean is false.
