### ISSUE TITLE
Detect Windows Docked Together & Get Window Data Outside The Loop

### ISSUE THREAD

**Issue by Alex-vZyl** [ocornut/imgui#4992]
I have two questions, please let me know if I should rather open 2 issues.

**Version/Branch of Dear ImGui:**

Version: 1.84
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: OpenGL, GLFW
Operating System: Windows 10 (Gross)

**My Goal:**

I am writing an application and working on the event dispatcher.  It is not a use case where I have Dear ImGUI on top of a game world.  The application uses Dear ImGUI windows to display graphics scenes (as much as the user wants to display).  The idea was to have different layers (layers can contain any type of Dear ImGUI window and some layers contain graphics scenes inside the window).  Then, based on certain data (such as is the layer hovered or focused?), events get dispatched to specific layers.   (This ties in to my second question, it would be a lot easier if I was able to call `ImGui::IsWindowHovered("MyWindow")`, instead of implementing my own layering system so that I do not have to wait for the loop.)

**My Questions:**

I started implementing the layers and the layer stack and I am very close to done.  There is only one thing stopping me from finishing it completely - the ordering of the layers changes depending on how windows are docked.  For example, if 2 windows are docked together and one of them comes into focus, both the windows have to be moved to the front (if they are not docked in the main viewport).

However, this is something that you obviously have already implemented in Dear ImGUI.   This leads me to my first question:  Is there a way to determine if specific windows are docked together?  Or rather, is there a way to use Dear ImGUI's underlying window ordering in my event dispatcher?

My second question is more related to the ImGUI paradigm.  Currently (AFAIK) if I want get data that is related to a specific window it has to be called in the loop, for example:
```
ImGui::Begin("MyWindow", &isOpen);
m_size = ImGui::GetWindowSize();  // This is a class member.
//  Window contents...
ImGui::End();
```
However, sometimes I want to dispatch an event, but I am unable to get the updated window data, since I have to wait for the specific window to be called in the loop for the data to be updated.  I saw there is a function `ImGui::SetWindowFocus("MyWindow")` that can be used to set the window focus outside of the loop.  Would it be possible to have similar functions like this for other window data?  If not, are there any other solutions? 

Screenshot to give some context!  Most of the windows will be docked, but that does not change the questions.

![image](https://user-images.githubusercontent.com/81622310/152873353-662bb93c-6715-4453-a9f6-41905c233e02.png)

**P.S.**

This is an amazing library and I love working with it.  Really amazing work you guys are doing here.

**Comment by AlexEnerdyne** [comment]
I feel a bit stupid.  Is `FindWIndowByName(const char* name)` going to give what I want in question 2?

**Comment by AlexEnerdyne** [comment]
I changed the function as can be seen below and it seems to work perfectly.

```
    bool IsWindowHovered(ImGuiWindow* window, ImGuiHoveredFlags flags)
    {
        IM_ASSERT((flags & ImGuiHoveredFlags_AllowWhenOverlapped) == 0);   // Flags not supported by this function
        ImGuiContext& g = *GImGui;
        if (g.HoveredWindow == NULL)
            return false;

        if ((flags & ImGuiHoveredFlags_AnyWindow) == 0)
        {
            // ImGuiWindow* window = g.CurrentWindow;  Remove this line so that we can pass our own window to check.
            switch (flags & (ImGuiHoveredFlags_RootWindow | ImGuiHoveredFlags_ChildWindows))
            {
            case ImGuiHoveredFlags_RootWindow | ImGuiHoveredFlags_ChildWindows:
                if (g.HoveredWindow->RootWindow != window->RootWindow)
                    return false;
                break;
            case ImGuiHoveredFlags_RootWindow:
                if (g.HoveredWindow != window->RootWindow)
                    return false;
                break;
            case ImGuiHoveredFlags_ChildWindows:
                if (!ImGui::IsWindowChildOf(g.HoveredWindow, window))
                    return false;
                break;
            default:
                if (g.HoveredWindow != window)
                    return false;
                break;
            }
        }
```

**Comment by Alex-vZyl** [comment]
I see that from `ImGuiWindow` I am able to get the `ImGuiDockNode`.  From that node I can get its parent and get the windows contained in the parent, allowing me to access the windows docked together.  I am pretty sure this solves all of my questions.  

If anyone has any better methods, do let me know, but I am closing this issue since I am satisfied.
