### ISSUE TITLE
Trying to understand why I am losing input events.

### ISSUE THREAD

**Issue by CarloWood** [ocornut/imgui#4998]
Version: 1.87 (master)
Backends: custom

I now understand why input events are being lost when `IO.ConfigInputTrickleEventQueue` is 0.
I now set that to 1, but still losing input event (mouse clicks).

In an attempt to understand what is going on I added extensive debug output to imgui itself.
Here is an example of when a button click vanished. I show the debug output interleaved with comments that either explain what is going on (when it is my code) or when I don't understand something (when it is imgui's code).
Debug output that starts with '>>>>>>>>>>>>>>' or 'NOTICE' is imgui (except for where the output is 'Setting m_debug_button_clicked to true').

    VKFRAME       : | Deep Button Entering SynchronousWindow::consume_input_events() [0x7f0080004e10]

"Deep Button" is just a prefix, it is the name of the window. The fact that this `SynchronousWindow` means we entered already the beginning of the render loop and everything that follows is the same thread that is dealing with a single imgui context (in fact, every debug output line is also prefixed with `ThreadPool02`, the name of the thread, but I leave that out).

    VKFRAME       : | Deep Button   Calling m_input_event_buffer.pop() = {{mouse_position:{144, 16}, modifier_mask:None, flags:{mouse_buttons:None, event_type:EventType::button_release}, button:0}}

All these events (two in total) happened already and were queued. They are now synchronously being processed at the start of the renderloop and passed to imgui. This first event is the release of button 0. That it is a release is because ImGui::Button() returns true on button release (not press).

    NOTICE        : | Deep Button   Setting m_debug_button_clicked to true.

Just a variable that is set so I can find back things in the debug output. This means that the mouse button was released over the imgui button.

    IMGUI         : | Deep Button   Entering ImGui::on_mouse_move(144, 16)    // io.AddMousePosEvent(144, 16);
    IMGUI         : | Deep Button   Entering ImGui::update_modifiers(0)   // io.AddKeyModsEvent(0);
    IMGUI         : | Deep Button   Entering ImGui::on_mouse_click(0, 0) //  io.AddMouseButtonEvent(0, 0);

The single mouse button release event is split up into three imgui events that are added to imgui here.

    IMGUI         : | Deep Button   ImGui::want_capture_mouse() = 1
    VKFRAME       : | Deep Button   Calling m_input_event_buffer.pop() = {{mouse_position:{150, 16}, modifier_mask:None, flags:{mouse_buttons:None, event_type:EventType::window_leave}}}

The second event that happened before this frame is the mouse left the window.

This was the main reason I was losing events before, but I am assuming that using `ConfigInputTrickleEventQueue = 1` should also fix this (and it seems like that at first sight, looking at imgui's code).

    IMGUI         : | Deep Button   Entering ImGui::on_mouse_enter(150, 16, 0) //  io.AddMousePosEvent(-FLT_MAX, -FLT_MAX);

We left the window.

    VKFRAME       : | Deep Button   Calling m_input_event_buffer.pop() = nullptr

That was the last accumulated event this frame.

    IMGUI         : | Deep Button   ImGui::want_capture_mouse() = 1
    VKFRAME       : | Deep Button Entering SingleButtonWindow::draw_frame() [0x7f0080004e10]
    VKFRAME       : | Deep Button   Entering SynchronousWindow::start_frame()

This is were `NewFrame()` is called. So, the following debug output is from within imgui.

    >>>>>>>>>>>>>>: | Deep Button     Starting InputEventsQueue(true) with Size = 4 (mouse_moved and mouse_button_changed reset)

That's the 4 events we just added to imgui.

    >>>>>>>>>>>>>>: | Deep Button     Processing event ImGuiInputEventType_MousePos at (144, 16)
    >>>>>>>>>>>>>>: | Deep Button       mouse coordinates changed (last value: (121, 19)
    >>>>>>>>>>>>>>: | Deep Button       io.MousePos set to (144, 16) and mouse_moved set to true.

Looks all very sane.

    >>>>>>>>>>>>>>: | Deep Button     Processing event ImGuiInputEventType_MouseButton for button 0 with io.MousePos = (144, 16)
    >>>>>>>>>>>>>>: | Deep Button       io.MouseDown[button = 0] is now 0
    >>>>>>>>>>>>>>: | Deep Button       io.MouseClicked[button = 0] is now 0 (io.MouseDownDuration[0] = 0.0900433)

Huh? This is the reason that the mouse click is lost it seems. Why is `MouseClicked` set to 0?
Nevertheless, lets first look at the rest of the debug output:

    >>>>>>>>>>>>>>: | Deep Button       not setting io.MouseClickedPos[button = 0] to (144, 16) because io.MouseClicked[0] is false.
    >>>>>>>>>>>>>>: | Deep Button       mouse_button_changed is now 0x1.

The imgui code here is in `InputEventsQueue()` thus and the relevant code (sans added debug code) looks like:

                io.MouseDown[button] = e->MouseButton.Down;
                io.MouseClicked[button] = io.MouseDown[button] && io.MouseDownDuration[button] < 0.0f;  
                if (io.MouseClicked[button])
                  io.MouseClickedPos[button] = io.MousePos;
                mouse_button_changed |= (1 << button);

    >>>>>>>>>>>>>>: | Deep Button     Processing event ImGuiInputEventType_MousePos at (-3.40282e+38, -3.40282e+38)

That is the mouse leaving the window event.

    >>>>>>>>>>>>>>: | Deep Button       mouse coordinates changed (last value: (144, 16)
    >>>>>>>>>>>>>>: | Deep Button       stopping because mouse_button_changed=0x1 != 0
    >>>>>>>>>>>>>>: | Deep Button     Entering ImGui::UpdateMouseInputs() [io = 0x7f007aaf4b98]
    ...
    WARNING       : | Deep Button     Window was not deleted.

meaning the event was lost.

I tried to understand why `io.MouseDownDuration[0] = 0.0900433` in the above, because that is apparently the reason that the mouse button release event was ignored. Prior to the above debug output I found (and this is just the previous frame):

    VKFRAME       : | Deep Button Entering SynchronousWindow::consume_input_events() [0x7f0080004e10]

Previous frame of window 0x7f0080004e10

    VKFRAME       : | Deep Button   Calling m_input_event_buffer.pop() = nullptr

There were no events.

    IMGUI         : | Deep Button   ImGui::want_capture_mouse() = 1
    VKFRAME       : | Deep Button Entering SingleButtonWindow::draw_frame() [0x7f0080004e10]
    VKFRAME       : | Deep Button   Entering SynchronousWindow::start_frame()
    >>>>>>>>>>>>>>: | Deep Button     Starting InputEventsQueue(true) with Size = 0 (mouse_moved and mouse_button_changed reset)

No left over trickle events.

    >>>>>>>>>>>>>>: | Deep Button     Entering ImGui::UpdateMouseInputs() [io = 0x7f007aaf4b98]
    NOTICE        : | Deep Button       io.MouseClicked[0] set to 0 because io.MouseDown[0]=1 and io.MouseDownDuration[0]=0 (< 0.0f?)
    NOTICE        : | Deep Button       io.MouseReleased[0] set to 0 because io.MouseDown[0]=1 and io.MouseDownDuration[0]=0 (>= 0.0f?)
    NOTICE        : | Deep Button       io.MouseDownDurationPrev[0] set to io.MouseDownDuration[0] = 0
    NOTICE        : | Deep Button       io.MouseDownDuration[0] set to 0.0900433 because io.MouseDown[0]=1, io.MouseDownDuration[0]=0, io.DeltaTime=0.0900433
    VKFRAME       : | Deep Button     Entering LogicalDevice::wait_for_fences(<0xa7cc1e00000000d6>, 0, 1000000000)

etc.

My conclusion is that `io.MouseDownDuration[0] set to 0.0900433` because that's how long the mouse was pressed. But note that there are no events. The mouse is *still* pressed at this point. If setting `MouseDownDuration` here leads to ignoring the mouse release event the next frame, then should be set at all here? Or what is going on?

**Comment by CarloWood** [comment]
In case it matters, the frame before THAT is where the mouse button was pressed and looks like this (only showing the imgui debug output here):

    >>>>>>>>>>>>>>: | Deep Button     Starting InputEventsQueue(true) with Size = 6 (mouse_moved and mouse_button_changed reset)
    >>>>>>>>>>>>>>: | Deep Button     Processing event ImGuiInputEventType_MousePos at (-3.40282e+38, -3.40282e+38)
    >>>>>>>>>>>>>>: | Deep Button       mouse coordinates changed (last value: (70, 49)
    >>>>>>>>>>>>>>: | Deep Button       io.MousePos set to (-3.40282e+38, -3.40282e+38) and mouse_moved set to true.
    >>>>>>>>>>>>>>: | Deep Button     Processing event ImGuiInputEventType_Focus for Focused = 1
    >>>>>>>>>>>>>>: | Deep Button     Processing event ImGuiInputEventType_MousePos at (121, 19)
    >>>>>>>>>>>>>>: | Deep Button       mouse coordinates changed (last value: (-3.40282e+38, -3.40282e+38)
    >>>>>>>>>>>>>>: | Deep Button       io.MousePos set to (121, 19) and mouse_moved set to true.
    >>>>>>>>>>>>>>: | Deep Button     Processing event ImGuiInputEventType_MousePos at (121, 19)
    >>>>>>>>>>>>>>: | Deep Button       Ignored because mouse didn't move. 
    >>>>>>>>>>>>>>: | Deep Button     Processing event ImGuiInputEventType_MouseButton for button 0 with io.MousePos = (121, 19)
    >>>>>>>>>>>>>>: | Deep Button       io.MouseDown[button = 0] is now 1
    >>>>>>>>>>>>>>: | Deep Button       io.MouseClicked[button = 0] is now 1 (io.MouseDownDuration[0] = -1)
    >>>>>>>>>>>>>>: | Deep Button       io.MouseClickedPos[button = 0] is now (121, 19)
    >>>>>>>>>>>>>>: | Deep Button       mouse_button_changed is now 0x1.
    >>>>>>>>>>>>>>: | Deep Button     Entering ImGui::UpdateMouseInputs() [io = 0x7f007aaf4b98]
    NOTICE        : | Deep Button       io.MouseClicked[0] set to 1 because io.MouseDown[0]=1 and io.MouseDownDuration[0]=-1 (< 0.0f?)
    NOTICE        : | Deep Button       io.MouseReleased[0] set to 0 because io.MouseDown[0]=1 and io.MouseDownDuration[0]=-1 (>= 0.0f?)
    NOTICE        : | Deep Button       io.MouseDownDurationPrev[0] set to io.MouseDownDuration[0] = -1
    NOTICE        : | Deep Button       io.MouseDownDuration[0] set to 0 because io.MouseDown[0]=1, io.MouseDownDuration[0]=-1, io.DeltaTime=0.0900501

**Comment by ocornut** [comment]
Hello,
I am afraid this is too verbose. Please try to narrow this to a simple and explicit bug report rather than a long wall of text (you can keep the existing wall of text if you feel it is valuable, but provide a short version.)

**Comment by CarloWood** [comment]
At some point you might want to look at the details of what is going on (its just debug output), so I'll leave the above.

The short version, that hopefully shows there is a possible bug is:

1) I set `IO.ConfigInputTrickleEventQueue = 1` but
2) I am still losing mouse click events.
3) I tracked losing an event down to `ImGui::UpdateInputEvents` at the line:

    io.MouseClicked[button] = io.MouseDown[button] && io.MouseDownDuration[button] < 0.0f;

during the processing of a mouse button release event (that is normally the trigger for `ImGui::Button()` to return true) where this sets ` io.MouseClicked[button]` to 0 because at that point `io.MouseDownDuration[button]` is larger than zero.

This seems to be the reason the event is simply lost (`MouseClicked[0]` being set to 0).

I don't understand why this happens, because I don't understand the idea behind the values of `MouseDownDuration` (-1, 0 and larger values).

It seems that the value it has at that point is the result of that the button press event was two frames ago, and one frame ago (while there was no event, but the button was still pressed) the `MouseDownDuration` was set to `io.DeltaTime`. That seems ok . So why does this cause the mouse release event, the third frame, to be ignored?

**Comment by ocornut** [comment]
> 2. I am still losing mouse click events.

Please provide a minimum, complete, verifiable repro to back this up so we can investigate. That’s the only desirable source of truth. Anything else beside that may be incorrect or misleading.

**Comment by ocornut** [comment]
> but I guess you want (minimal) code. That is kinda hard isn't it - vulkan and minimal :/.

Vulkan has nothing to do with it. If you narrow things down to their essence you’ll likely find your issue. 

You don’t need to look further than providing a MCVE. 

DownDuration is set to < 0.0f when a button or key is not held. A “clicked/key pressed” state happen for one frame when a button or key goes from not being held to being held, at that point DownDuration is 0.0f and increase for as long as the button or key is held. It’s pretty much spelled out in the code.

My gut feeling suspicion being that you have an overengineered spacecraft creating yourself a bug, from my pov i can’t debug your code but if you prove that dear imgui has a bug given a MCVE then I can look at it and will happily fix it.

> Please note that tthis was never intended and is not a bug report. 

thanks for the clarification, that’s helpful to know.

**Comment by CarloWood** [comment]
> Most Button() are considered pressed after a sequence of: clicked + released within the same bounding box.

That is a different use of words than, for example, XCB where `XCB_BUTTON_PRESS` means the button when from not held to held - and `XCB_BUTTON_RELEASE` the other way around. So thanks for the clarification.  `held` is also new to me, but I'll assume this is the same as `down` - not a state transition but a given state (of being held / down).

> My gut feeling suspicion being that you have an overengineered spacecraft creating yourself a bug

That is unfortunate. That is certainly not the case :/ (and I have no idea what makes you say that, other then that I have very good debugging tools (that in your eyes are too verbose)... I already shortened it to its essence (this application currently producces over 2000 lines of debug output per second) and I added a line by line explanation so it is extremely easy to follow...)

Anyway - what you describe is what I see:

* Frame 1: button is held (from not held to held)
* Frame 2: button is still held and MouseDownDuration is set to > 0.
* Frame 3: button is released, but since MouseDownDuration > 0 that is just thrown away and Button() does not return true.

**Comment by CarloWood** [comment]
I withdraw this issue :/. Sorry to -again- having wasted your time. But at least your explanation of the meaning of DownDuration helped.

**Comment by ocornut** [comment]
Maybe if you post details about what you found it could be helpful for other users?

> That is a different use of words than, for example, XCB where XCB_BUTTON_PRESS means the button when from not held to held - and XCB_BUTTON_RELEASE the other way around. So thanks for the clarification. held is also new to me, but I'll assume this is the same as down - not a state transition but a given state (of being held / down).

That's correct, and it is correct that our terminology for "pressed" is inconsistent with e.g. Qt and XCB :/
Held/Down do refer to the same thing yes.

> Anyway - what you describe is what I see:
> Frame 1: button is held (from not held to held)
> Frame 2: button is still held and MouseDownDuration is set to > 0.
> Frame 3: button is released, but since MouseDownDuration > 0 that is just thrown away and Button() does not return true.

Your description for Frame 1 and 2 are correct.
In Frame 3 you are confusing the logic for "mouse button" and "Button() widget".
MouseDownDuration > 0 means the Mouse Button is never "pressed now", but this is not at al what `Button()`/`ButtonBehavior()` are looking at. They are looking at the fact there were made active (here in Frame 1) and now the mouse button is released while still hovering the same Button(), and Button() will return true.

> that in your eyes are too verbose

Was not referring to the tools but the initial message, hard for someone not acquainted with your problem to dive at it without a TL;DR.


For debugging this is what I generally use:

```cpp
static void DebugLogInputEvent(const ImGuiInputEvent* e)
{
    switch (e->Type)
    {
    case ImGuiInputEventType_MousePos:
        IMGUI_DEBUG_LOG_IO("Event: MousePos (%.1f %.1f)\n", e->MousePos.PosX, e->MousePos.PosY);
        break;
    case ImGuiInputEventType_MouseButton:
        IMGUI_DEBUG_LOG_IO("Event: MouseButton %d %s\n", e->MouseButton.Button, e->MouseButton.Down ? "Down" : "Up");
        break;
    case ImGuiInputEventType_MouseWheel:
        IMGUI_DEBUG_LOG_IO("Event: MouseWheel (%.1f %.1f)\n", e->MouseWheel.WheelX, e->MouseWheel.WheelX);
        break;
    case ImGuiInputEventType_Key:
        IMGUI_DEBUG_LOG_IO("Event: Key \"%s\" %s\n", ImGui::GetKeyName(e->Key.Key), e->Key.Down ? "Down" : "Up");
        break;
    case ImGuiInputEventType_Char:
        IMGUI_DEBUG_LOG_IO("Event: Char: U+%08X (%c)\n", e->Text.Char, e->Text.Char);
        break;
    case ImGuiInputEventType_Focus:
        IMGUI_DEBUG_LOG_IO("Event: AppFocused %d\n", e->AppFocused.Focused);
        break;
    case ImGuiInputEventType_None:
    default:
        break;
    }
}
```

Then in `UpdateInputEvents()` BEFORE clearing/resizing the input queue:

```cpp
    if (event_n != 0)
    {
        IMGUI_DEBUG_LOG_IO("Processed inputs:\n");
        for (int n = 0; n < event_n; n++)
            DebugLogInputEvent(&g.InputEventsQueue[n]);
    }
````
And after clearing/resizing the queue:
```cpp
    if (event_n != 0)
    {
        IMGUI_DEBUG_LOG_IO("Remaining inputs:\n");
        for (int n = 0; n < g.InputEventsQueue.Size; n++)
            DebugLogInputEvent(&g.InputEventsQueue[n]);
    }
```

**Comment by ocornut** [comment]
It's unfortunate you removed all your posts, making the information in this thread not useful for other users and my answers less useful.

**Comment by CarloWood** [comment]
To make it up, here is a MCVE that other users (also) can use if they have input problems like this.
Adapted from `example_null`.

```
#include "imgui.h"
#include <cstdio>

int main()
{
    IMGUI_CHECKVERSION();
    ImGui::CreateContext(true);
    ImGuiIO& io = ImGui::GetIO();

    // Build atlas
    unsigned char* tex_pixels = nullptr;
    int tex_w, tex_h;
    io.Fonts->GetTexDataAsRGBA32(&tex_pixels, &tex_w, &tex_h);

    bool last_frame = false;
    for (int n = 0; n < 20; n++)
    {
        io.DisplaySize = ImVec2(150, 50);
        io.DeltaTime = 1.0f / 60.0f;

        switch (n)
        {
          case 0:
//            io.AddFocusEvent(true);
            break;
          case 1:
            io.AddMousePosEvent(75, 25);
            io.AddMouseButtonEvent(0, true);
            break;
          case 2:
//            break;
//          case 3:
            io.AddMousePosEvent(-FLT_MAX, -FLT_MAX);
            io.AddMousePosEvent(76, 24);
            io.AddMouseButtonEvent(0, false);
            io.AddMousePosEvent(-FLT_MAX, -FLT_MAX);
            break;
          default:
            last_frame = true;
            break;
        }
        if (last_frame)
          break;

        printf("NewFrame() %d\n", n);
        ImGui::NewFrame();

        ImGui::SetNextWindowPos(ImVec2(0.0f, 0.0f));
        ImGui::SetNextWindowSize(io.DisplaySize);
        ImGui::Begin("SingleButton", nullptr,
            ImGuiWindowFlags_NoDecoration |
            ImGuiWindowFlags_NoMove |
            ImGuiWindowFlags_NoSavedSettings);

        if (ImGui::Button("Trigger Event", ImVec2(134, 134)))
          printf(">>>>>>>>>>> Button clicked!\n");
        else
          printf(">>>>>>>>>>> Button not clicked!\n");

        ImGui::End();

        ImGui::EndFrame();
        ImGui::Render();
    }

    printf("DestroyContext()\n");
    ImGui::DestroyContext();
}
```

This shows that.... I can't reproduce the problem / I'm an ass / imgui works.

Thanks again!
