### ISSUE TITLE
Nested listboxes?

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#500]
Hi,

Does imgui support multilevel nested listbox?

Vivienne

**Comment by ocornut** [comment]
Please label your question properly.
It depends what you mean by "multilevel nested lostbox". Imgui is a low-level api with which you can build most things yourself if given the effort, so the answer is probably yes.

**Comment by vivienneanthony** [comment]
No problem. I seen the listbox code. The only thing I can think of giving the appearance of nested is formatting the text with spaces like tab delimited.
