### ISSUE TITLE
Mouse buttons not working when updating from imgui 1.86 to 1.87

### ISSUE THREAD

**Issue by dpelle** [ocornut/imgui#5003]
### Discussed in https://github.com/ocornut/imgui/discussions/5002

<sup>Originally posted by **dpelle** February  9, 2022</sup>
I just tried to upgrade imgui in a GUI application (internal to the company where I work, so I cannot share it) from imgui-1.86.0 to imgui-1.87.0 and the main menu bar does not open menus anymore when clicking on them.  If I hover over the menu items, they change color, but left or right click do not open menus anymore. It worked fine with the previous version imgui-1.86.0.

Is this a known issue?
Any hints to debug it?
Is there a workaround to open items?

The menu items are created like this for example:
```
 if (ImGui::BeginMainMenuBar()) {
    if (ImGui::BeginMenu("Settings")) {
      ImGui::MenuItem("Log mouse events", nullptr, &log_mouse_events_);
      ImGui::MenuItem("DPI scaling", nullptr, &show_dpi);
      ImGui::MenuItem("Show fps", nullptr, &show_fps);
      ImGui::MenuItem("Cap fps", nullptr, &cap_fps);                                                           
      ImGui::MenuItem("Log level", nullptr, &show_log_level);
      ImGui::EndMenu();
    }   
    ImGui::EndMainMenuBar();
  }
```
I'm using xubuntu-18.04.6.
Backend: glfw-3.3.1.

**Comment by PathogenDavid** [comment]
Which commit of Dear ImGui are you using?

Can you repro this in the official examples?

**Comment by PathogenDavid** [comment]
You mentioned in the other thread that mouse interactions with your map work, but I imagine your map is something custom. Do mouse interactions work with other Dear ImGui windows/widgets?

**Comment by dpelle** [comment]
> Which commit of Dear ImGui are you using?

I'm using https://github.com/ocornut/imgui/commit/c71a50deb5ddf1ea386b91e60fa2e4a26d080074  (i.e the version tagged v1.87).

> Can you repro this in the official examples?

I will try that later and report here.

> Do mouse interactions work with other Dear ImGui windows/widgets?

I will also try that soon.  I'll e.g. try the tracy profiler.

**Comment by ocornut** [comment]
You don’t need to try the Tracy profiler, just call ImGui::ShowDemoWindow() and see if you can interact with it.

**Comment by dpelle** [comment]
@ocornut wrote:

> You don’t need to try the Tracy profiler, just call ImGui::ShowDemoWindow() and see if you can interact with it.

I did that.  I can see the demo window that pops up (titled "Dear ImGui Demo").
But it has the same issue i.e. the menus do not open when clicking.  The Tree view with the ▸ symbols also do not expand when clicking with ImGui::1.87.0. Going back to ImGui::11.86.0, it works fine.

I could try to bissect, but this will have to wait for the weekend as I do not have time now.
I will also try to upgrade glfw in case that helps.

**Comment by dpelle** [comment]
I have upgraded glfw from 3.3.1 to 3.3.6 but it does not help to fix the issue.

@ocornut  asked:

> Are you calling ImGui_ImplGlfw_InitXXX() with install_callback = true ?

I'm not familiar with this, but I see this:
```
  // Do not install GLFW callbacks - we need to decide when to dispatch them to ImGui and when to
  // Michi
  ImGui_ImplGlfw_InitForOpenGL(window, false);                                                              
  ImGui_ImplOpenGL3_Init(glsl_version);
```

> If NOT are you correctly forwarding all callbacks to GLFW ?

How do I check this?

> Can you confirm this with the example application?

I built `imgui/examples/example_glfw_opengl3/example_glfw_opengl3` from imgui-1.87.0 and it works fine.  So something must be wrong with my application.  However, this application works fine with imgui <= 1.86.0 and is only broken in imgui-1.87.0 so something is not compatible.

**Comment by dpelle** [comment]
@ocornut asked:

> If NOT are you correctly forwarding all callbacks to GLFW ?

TBH, I don't know how this works. But I see this:
```
      // Do not install GLFW callbacks - we need to decide when to dispatch them to ImGui and when to
      // Michi
      ImGui_ImplGlfw_InitForOpenGL(window, false);
      ImGui_ImplOpenGL3_Init(glsl_version);
  
      // Our state
      ImVec4 clear_color = ImVec4(0.0f, 0.0f, 0.0f, 1.00f);
  
      glfwSetMouseButtonCallback(window, MouseButtonCallback);
      glfwSetScrollCallback(window, ScrollCallback);
      glfwSetKeyCallback(window, KeyCallback);
      glfwSetCharCallback(window, CharCallback);
```
Probably the relevant callback is the one registered with `glfwSetMouseButtonCallback()` which is:

```
void MouseButtonCallback(GLFWwindow* window, int button, int action, int /*mods*/) {                                                           
  Event::MouseButton* event_button = nullptr;
  if (button == GLFW_MOUSE_BUTTON_LEFT) {
    event_button = &event.left_mouse_button;
  } else if (button == GLFW_MOUSE_BUTTON_MIDDLE) {
    event_button = &event.middle_mouse_button;
  } else if (button == GLFW_MOUSE_BUTTON_RIGHT) {
    event_button = &event.right_mouse_button;
  }
  if (event_button == nullptr) {
    return;
  }
  ImGuiIO& io = ImGui::GetIO();
  if (io.WantCaptureMouse) {
    return;
  }
  
  if (action == GLFW_PRESS) {
    double x, y;
    std::tie(x, y) = GetCursorCanvasPos(window);
    event_button->origin = {(int)x, (int)y};
    event_button->state = Event::MouseButtonState::Pressed;
  }
  if (action == GLFW_RELEASE) {
    event_button->state = Event::MouseButtonState::Released;
  }
}
```

**Comment by thedmd** [comment]
> If NOT are you correctly forwarding all callbacks to GLFW ?

Notice that all `glfwSetXXXCallback` function return function pointer. To correctly forward callback your callback must call one returned by `glfwSetXXXCallback` (if not NULL). When you're done with GLFW you need to call `glfwSetXXXCallback` with callback you got originally. On top of that you need to make sure you tear down your setup in reverse order than you initialized it.

**Comment by ocornut** [comment]
If you register a mouse button callback so you must call `ImGui_ImplGlfw_MouseButtonCallback()` from your callback.
You are never calling it so the backend can't see your mouse clicks.

Other solutions that are simpler:
- Install your callbacks
- THEN Initialize backend with install_callbacks = true
- Our callbacks will automatically call yours.

OR:
- Initialize backend with install_callbacks = false
- Install your callbacks
- THEN call ImGui_ImplGlfw_InstallCallbacks()
- Our callbacks will automatically call yours.

**Comment by DominiquePelle-TomTom** [comment]
Sorry for the belated response. Thanks @ocornut .
I called `ImGui_ImplGlfw_MouseButtonCallback(...)` at the beginning of my `MouseButtonCallback(...)` function (the one in my previous comment) and that fixed it indeed.

**Comment by pegvin** [comment]
> If you register a mouse button callback so you must call `ImGui_ImplGlfw_MouseButtonCallback()` from your callback. You are never calling it so the backend can't see your mouse clicks.
> 
> Other solutions that are simpler:
> 
>     * Install your callbacks
> 
>     * THEN Initialize backend with install_callbacks = true
> 
>     * Our callbacks will automatically call yours.
> 
> 
> OR:
> 
>     * Initialize backend with install_callbacks = false
> 
>     * Install your callbacks
> 
>     * THEN call ImGui_ImplGlfw_InstallCallbacks()
> 
>     * Our callbacks will automatically call yours.

thanks alot!!! it was really helpful as when i was refactoring my codebase, the order of registering the callbacks changed.
