### ISSUE TITLE
[Features/Shadows] ShadowRectUvs is NULL

### ISSUE THREAD

**Issue by TheNachoBIT** [ocornut/imgui#5007]
Hello!

I've been trying to merge the "shadow" feature into my current ImGui version.
Everything compiles fine and runs fine, the issue is that i get an error on the `ImDrawList::AddShadowRect` function inside `imgui_draw.cpp`.

When this line of code is executed: 
```
const ImVec4 uvs = _Data->ShadowRectUvs[uv_index];
```

that can be found inside a for loop
```
for (int x = 0; x < 3; x++)
    {
        for (int y = 0; y < 3; y++)
        {
            const int uv_index = x + (y + y + y); // y*3 formatted so as to ensure the compiler avoids an actual multiply
            const ImVec4 uvs = _Data->ShadowRectUvs[uv_index];...
```

returns an error, which is that `_Data->ShadowRectUvs` is 0x000... (its all zeros after the x), meaning that the entire array is pointing to NULL

I tried looking if my merging went wrong (because it can happend), but based on what i got its fine.
I tried to see where the ShadowRectUvs get created, but found no trace of that in the code.
So i don't know if i'm the one making a mistake or if the part where the Shadow UVs get created is missing in the source code.

Any kind of help is appreciated :D
Thanks!

**Comment by TheNachoBIT** [comment]
All right, i fixed it, turns out that `imgui.cpp` is the one that didn't updated it correctly during the merge.

So for those who stumbled upon the same issue that i had, you need to update the `ImGui::SetCurrentFont()` void that is in the same .cpp file that i mentioned earlier, to this:

```// Important: this alone doesn't alter current ImDrawList state. This is called by PushFont/PopFont only.
void ImGui::SetCurrentFont(ImFont* font)
{
    ImGuiContext& g = *GImGui;
    IM_ASSERT(font && font->IsLoaded());    // Font Atlas not created. Did you call io.Fonts->GetTexDataAsRGBA32 / GetTexDataAsAlpha8 ?
    IM_ASSERT(font->Scale > 0.0f);
    g.Font = font;
    g.FontBaseSize = ImMax(1.0f, g.IO.FontGlobalScale * g.Font->FontSize * g.Font->Scale);
    g.FontSize = g.CurrentWindow ? g.CurrentWindow->CalcFontSize() : 0.0f;

    ImFontAtlas* atlas = g.Font->ContainerAtlas;
    g.DrawListSharedData.TexUvWhitePixel = atlas->TexUvWhitePixel;
    g.DrawListSharedData.TexUvLines = atlas->TexUvLines;
    g.DrawListSharedData.Font = g.Font;
    g.DrawListSharedData.FontSize = g.FontSize;
    g.DrawListSharedData.ShadowRectIds = &atlas->ShadowRectIds[0];
    g.DrawListSharedData.ShadowRectUvs = &atlas->ShadowRectUvs[0];
}
```
Have a good day

**Comment by ofaruka** [comment]
thank you haha
