### ISSUE TITLE
How to change the postition of columns?

### ISSUE THREAD

**Issue by ShortMika** [ocornut/imgui#5008]
I am using the new Table columns api and I was wondering how you would change the position of the column.
For example if you have 2 columns, the second one starts in the middle of the window, but I'd like to make it so it starts at about 1/3 of the windows width and i haven't found a method to actually move the column.

![grafik](https://user-images.githubusercontent.com/61615177/153671612-533c0444-ae0a-4cc3-b765-647acfca2ee1.png)

As you can see, the second column starts at half the windows width and I'd like to shift it to the left without using **ImGuiTableFlags_Resizable**.

Thanks in advance!

**Comment by ocornut** [comment]
The Tables demo is littered with examples doing things like that…
