### ISSUE TITLE
ImGui::EndDisabled() called before ImGui::BeginDisabled() when deactivating button on click

### ISSUE THREAD

**Issue by h4k1m0u** [ocornut/imgui#5011]
**Version/Branch of Dear ImGui:**

Version: 1.85
Branch: master _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp _(or specify if using a custom engine/back-end)_
Compiler: gcc _(if the question is related to building or platform specific features)_
Operating System: Ubuntu 20.04

**My Issue/Question:**
I'm adding a button which is deactivated when we click on it (boolean variable `b` set to false initially). The output in the terminal for the code below is:

```
Button clicked
End disabled
```

This means that `ImGui::BeginDisabled()` isn't called before `ImGui::EndDisabled()` which logically makes my program crash with the following error message:
```
/imgui/imgui.cpp:6662: void ImGui::EndDisabled(): Assertion `g.DisabledStackSize > 0' failed.
```
Is this the normal behavior and is there a way to avoid this issue?
I actually didn't expect the `on-click` block to be called before the `beginDisabled` block, even though it's located before it in the code!

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
// Here's some code anyone can copy and paste to reproduce your issue
if (b) {  
  std::cout << "Begin disabled" << '\n';
  ImGui::BeginDisabled(true);
}                       

if (ImGui::Button(ICON_FA_CIRCLE, { 2*size_font, -1.0f })) {
  b = true;
  std::cout << "Button clicked" << '\n';
}  
                 
if (b) {
  std::cout << "End disabled" << '\n';
  ImGui::EndDisabled(); 
}                       

```

**Comment by PathogenDavid** [comment]
Instead of conditionally calling `BeginDisabled` you can just pass `b` to `BeginDisabled` and always call both methods. IE:

```cpp
ImGui::BeginDisabled(b);
if (ImGui::Button(ICON_FA_CIRCLE, { 2*size_font, -1.0f })) {
    b = true;
}
ImGui::EndDisabled();
```
