### ISSUE TITLE
GetCurrentModalWindow ?

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#502]
Hi,

Is there a method that returns the current "modal" popup window ?

In some of my components I need to check if my current window is the current modal one or not ?

Thanks

**Comment by ocornut** [comment]
Why do you need to do that?
There is a private function that does that `GetFrontMostModalRootWindow()` and could be declared in imgui_internal.h but I would like to know of a use case for it.

**Comment by ocornut** [comment]
"Current" isn't the correct function terminology to use, the current window is always the window you last Begin() into and then you should always know if it is a modal.

**Comment by krys-spectralpixel** [comment]
Because I have some "split" widgets in my application, sometimes they are over a window, sometimes not because they allow to resize a simple window.

So, I need to know if I can "drag" them to resize my window, it is why I need to know if there is a modal window (to avoid dragging) !

I have try with "IsWindowHovered" etc... but of course it only work when I'm over a window.

**Comment by ocornut** [comment]
So your question is flawed here. Widgets by default don't react if they are in a window that's isn't the front-most root Popup or Modal. 
e.g. ButtonBehavior() calls IsHovered() which calls IsWindowContentHoverable() which tells if the widgets of a window should be presently usable according to those rules of popup/modal inhibiting access to lower windows. This pretty much that what all widgets do and you shouldn't need more to provide consistent interaction with popups.
It's hard to know what you are doing without seeing your code,
