### ISSUE TITLE
Understanding Font Glyph definition in imgui.net

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#5020]
**Version/Branch of Dear ImGui:**

Version: 1.84
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui .net
Operating System: win10

**My Issue/Question:**
I'm trying to wrap my head around the UV-Range definition. The documation looks pretty clear...

```
// Hold rendering data for one glyph.
// (Note: some language parsers may fail to convert the 31+1 bitfield members, in this case maybe drop store a single u32 or we can rework this)
struct ImFontGlyph
{
    unsigned int    Colored : 1;        // Flag to indicate glyph is colored and should generally ignore tinting (make it usable with no shift on little-endian as this is used in loops)
    unsigned int    Visible : 1;        // Flag to indicate glyph has no visible pixels (e.g. space). Allow early out when rendering.
    unsigned int    Codepoint : 30;     // 0x0000..0x10FFFF
    float           AdvanceX;           // Distance to next character (= data from font + ImFontConfig::GlyphExtraSpacing.x baked in)
    float           X0, Y0, X1, Y1;     // Glyph corners
    float           U0, V0, U1, V1;     // Texture coordinates
};
```

But in my code I seem go get an arbitrary mixture of UV and pixel coordinates. I was able to figure out the mapping with the help of the font atlas, measuring the expected coordinates and writing a mapping function. 

![ImGui-FontGlyph-Definition](https://user-images.githubusercontent.com/1732545/154100899-db48851d-09f3-41ee-9d21-3b82c6796613.png)

I'm not sure, if this is related to the imgui.net backend.
This workaround now fixed it for me...

```
        private static ImRect GetCorrectUvRangeFromGlyphStructure(ImFontGlyphPtr g)
        {
            return new ImRect(             //-- U  -- V ---
                              new Vector2(g.X1,   g.Y1),    // Min    
                              new Vector2(g.U0, g.V0)   // Max
                              );
        }
```

 If this is the expected mapping you can close this issue.

**Comment by ocornut** [comment]
"// (Note: some language parsers may fail to convert the 31+1 bitfield members, in this case maybe drop store a single u32 or we can rework this)"

I don't know how the cimgui -> net setup converts the fields that are respectively 1 bit, 1 bit, 30 bits in that structure, but it is possible that the structure has no .net equivalent if .net doesn't support bit-sized fields and then your structure is the wrong size and all things go havoc.

**Comment by ocornut** [comment]
The structure looks correct in cimgui.h:
https://github.com/cimgui/cimgui/blob/master/cimgui.h#L1117
```
struct ImFontGlyph
{
    unsigned int Colored : 1;
    unsigned int Visible : 1;
    unsigned int Codepoint : 30;
    float AdvanceX;
    float X0, Y0, X1, Y1;
    float U0, V0, U1, V1;
};
```
But is wrong in imgui.net:
https://github.com/mellinoe/ImGui.NET/blob/master/src/ImGui.NET/Generated/ImFontGlyph.gen.cs
```
        public uint Colored;
        public uint Visible;
        public uint Codepoint;
```
This is a problem with however imgui.net is generated.

Need work on imgui.net side:
https://stackoverflow.com/questions/14464/bit-fields-in-c-sharp

I'll let you move this to imgui.net or push a PR/fix for it.

**Comment by pixtur** [comment]
Thanks for looking into this!
