### ISSUE TITLE
How i can remove underline from BeginTabBar

### ISSUE THREAD

**Issue by TruXe** [ocornut/imgui#5022]
Hello, i have little problem.

I want remove under line, under the BeginTabItem.
I can't find func. that rendering the line.

![image](https://user-images.githubusercontent.com/48220922/154145165-eeecc65d-3498-43b1-82f3-58e14f8799c5.png)
Here is image for show the underline what i mean.

**Comment by PathogenDavid** [comment]
You can set the colors associated with the underline to be invisible.

Example from @nobody-special666's comment here: https://github.com/ocornut/imgui/issues/4859#issuecomment-1004922688

> ```cpp
> ImGui::PushStyleColor(ImGuiCol_TabActive, IM_COL32(0,0,0,0));
> ImGui::PushStyleColor(ImGuiCol_TabUnfocusedActive, IM_COL32(0,0,0,0));
> 
> bool bTabBar = ImGui::BeginTabBar("MyTabBar", tab_bar_flags);
> 
> ImGui::PopStyleColor();
> ImGui::PopStyleColor();
> ```
