### ISSUE TITLE
vulkan.h is missing from the folder backends/vulkan!

### ISSUE THREAD

**Issue by ShaysFrame** [ocornut/imgui#5027]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: XXX
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: Windows 11 Home

**My Issue/Question:**

Why vulkan.h is missing from the backends/vulkan folder? Can someone help me understand what's vulkan is and why the example_glfw_vulkan's main.cpp file is showing red underline under the #include <vulkan/vulkan.h>?? 

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/74078575/154548503-7d297b13-0448-481d-9c9e-c97a729e510e.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
You need to install the VulkanSDK to compile code using Vulkan.

**Comment by Jopro1990** [comment]
> You need to install the VulkanSDK to compile code using Vulkan. This will install a copy of vulkan.h on your system.

I love you bro
