### ISSUE TITLE
Lots of lag with ListBoxHeader

### ISSUE THREAD

**Issue by AMac200** [ocornut/imgui#5028]
Version: Latest
Branch: master

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp _(or specify if using a custom engine/back-end)_
Operating System: Windows 10 (20H2)

**My Issue/Question:**

ListBoxHeader causes tons of lag when there are 1000+ items in listbox

**Screenshots/Video**
https://gyazo.com/c0043c43262905231d4871c994b45e32

**Comment by ocornut** [comment]
You are not providing a code snippet so we can't tell what you are doing wrong.

Generally speaking for flat list you should use ImGuiListClipper to only submit what's visible.

But even with no clipper, submitting 5000 items shouldn't get performances THAT bad so it is possible your code has more overhead than dear imgui (e.g. constructing strings on the heap, or pulling data from sources that are not fast to access).

Either way once you use the ImGuiListClipper  your code won't be exercised so much so OK if it is slow.
