### ISSUE TITLE
Discussions page is no longer there:

### ISSUE THREAD

**Issue by time-killer-games** [ocornut/imgui#5029]
https://github.com/ocornut/imgui/discussions

might want to update the "please read first" issue template

I was in the middle of getting help on there, it's a shame its gone.

**Comment by ocornut** [comment]
I’ve removed it yesterday as people kept misposting there. Will update it the issue template accordingly, thank you.

**Comment by ocornut** [comment]
I reopened discussions to leave the Build/Link/Font Loading issues there and will aggressively erase off-topic posts from it.

**Comment by time-killer-games** [comment]
Thank you! I really appreciate it!
