### ISSUE TITLE
Suggestion: Replace POSIX with WinAPI on Windows

### ISSUE THREAD

**Issue by time-killer-games** [ocornut/imgui#5030]
Couldn't help but notice there are a quite a bit of deprecated POSIX functions used on Windows, and it ultimately would be better to use purely Windows API (or at the very least, non-deprecated POSIX functions like _wfopen_s() and such) although only WinAPI will allow for UWP builds without needing to modify and make your own manual fork of imgui.

I was going to make a pull request which addresses this, I was just wondering if this idea would be approved of in advance.

**Comment by ocornut** [comment]
Hello,
Could you list what the functions are and what is the minimum Windows SDK version the requires?

**Comment by time-killer-games** [comment]
UWP doesn't support posix at all, but the _wopen() was one i found. I haven't had the chance to take a big look yet, I was just wondering if it was ok for me to gut out all the posix usage and replace it with WinAPI on windows (and before submintting my pull request, i'll make sure in advance it compiles ok for UWP).

I can look more in advance and let you know what I find. Currently busy with something brief.

**Comment by ocornut** [comment]
> I was just wondering if it was ok for me to gut out all the posix usage and replace it with WinAPI on windows

It mostly depends how noisy it makes the code and how alter compatibility with variety of compilers so I don't have a yes/no answer since I don't know what the changes would entail.

Are you talking about code in imgui.cpp sources file, or code in imgui_imp_win32.cpp ?

**Comment by time-killer-games** [comment]
imgui.cpp

**Comment by PathogenDavid** [comment]
> deprecated POSIX functions

What makes you think these functions are deprecated? [They aren't *recommended* on UWP](https://docs.microsoft.com/en-us/cpp/cppcx/crt-functions-not-supported-in-universal-windows-platform-apps) because they're synchronous, but using async file IO would not make sense in the context of Dear ImGui anyway.

(Also `fopen` isn't a POSIX thing, it and the related functions Dear ImGui uses are more related to the [C standard library](http://open-std.org/JTC1/SC22/WG14/www/docs/n2310.pdf#page=238) than POSIX.)

> needing to modify and make your own manual fork of imgui.

You shouldn't need to do this. You can either define `IMGUI_DISABLE_DEFAULT_FILE_FUNCTIONS` and provide your own file functions or define `IMGUI_DISABLE_FILE_FUNCTIONS` and skip our on the few features of Dear ImGui that require the file system in the first place.

> replace it with WinAPI on windows

If your goal is to support UWP and we're gonna play API pedant, using the Win32 APIs (like `CreateFile`) isn't the right thing to do either since you should really be using the new storage APIs.

**Comment by ocornut** [comment]
People are already using dear imgui with UWP using the aforementioned define (I even think they are enabled by default on UWP?).

**Comment by time-killer-games** [comment]
Sure, will do! :)

**Comment by PathogenDavid** [comment]
> Also in visual studio I do get deprecated function warnings for _wfopen(). Maybe deprecated wasn't the word they used. All I know is they MS seems to not want us using that.

Microsoft has been beating the drum about the `_s` variants of the standard C functions for a thousand years now. They definitely encourage secure-by-default code and are a great idea in Windows-only code, but in the context of something like Dear ImGui it's better to just implement things correctly with the cross-platform non-`_s` variants IMO.

> if you mean using std::wifstream/std::wofstream then yes that would be better as I believe that might actually be supported by UWP.

Oops, I forgot to add a link. I was referring to the [modern storage APIs](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-reading-and-writing-files).

> Although, platform dependency is impossible to get away from

To clarify I'm not concerned about the platform dependency here. I'm more concerned you're trying to solve a problem which doesn't really exist.

**Comment by time-killer-games** [comment]
To say i am trying to solve a problem that doesn't exist is rather counter-productive to your cause, especially in this context, code is always subject to improvement. You provide functionality out of the box to do file loading in a way which only works on certain systems and even provide a macro to omit the code and allow people to write their own external file loaders.

I'm not saying you have to support every system on earth, but if you are going to even support open source toy OS's like Linux or *BSD's that have less than 0.1% of the market-share, it would make more sense you'd be willing to expand the code which is already reasonably cross-platform to "just work" on something as common as UWP, since I'm offering to do that for you.

Seeing as most of the code does go by the cross-platform goal in mind, and works on nearly any system imaginable, to see something as common as UWP getting neglected just because you don't think it deserves recognition as a platform, show you must not care that much about having a complete thought in your code and are more satisfied with a near complete fragment.

I mean that in the kindest way possible. This is a great tool, and I'd like to help. I don't think scaring away potential contributions is a good idea, whether big or small, an improvement is just that - an improvement. This is not really that big of a task.
