### ISSUE TITLE
Weird TextInput problem

### ISSUE THREAD

**Issue by Skovv** [ocornut/imgui#5035]
Hi there, i have some weird problem. Check code:
```
class UiWindow_ProjectSettings : public UiWindow {
public:
std::string Name, Author;
char* name;
char* author;

void Create() {
    Name = ProjectName;// i had some crashes and same problems thats why this way
    Author = ProjectAuthor;
    name = (char*)Name.c_str();
    author = (char*)Author.c_str();
}
void Update() {
    if (isOpen) {// = true
        ImGui::Begin("Project Settings", &isOpen, ImGuiWindowFlags_HorizontalScrollbar);

        ImGui::InputText("name", name, 50);
        if (ProjectName.length() > 0) ProjectName = name;

       // ImGui::SetNextItemWidth(500);
        ImGui::InputText("author", author, 20);
        if (ProjectAuthor.length() > 0) ProjectAuthor = author;

        ImGui::End();
    }
}
};
auto win = new UiWindow_ProjectSettings;
win->Create();

... loop:
win->Update();
```

I was checking this and even i have 10 InputTexts and max length of them is <= 20 then there is no problem. If i set 50 then the result is:
![aaa](https://user-images.githubusercontent.com/1405919/154794576-4da8f7b1-1853-471e-9cd0-e612127d7b6d.png)

when i am writing in first TextInput after 29chars it's starting to writing in both of them.. Before i had like it's just crash the app when i had 1 TextInput. What am I doing wrong?

**Comment by ocornut** [comment]
You are misunderstanding how strings works in C/C++, but you can simply use the std::string version of InputText() located in the misc/stdlib/ folder.
