### ISSUE TITLE
Style question, fade animation

### ISSUE THREAD

**Issue by AbbyIOM** [ocornut/imgui#5040]
Hello everyone, recently I started playing with widgets and I've been trying to give them some fade in/out animations. 
And I got into one little problem that I can't really figure out yet. I created a TabBar with 5 tabs and what I'm trying to achieve is that when I press one tab and it get's activated it will fade the opacity in (from 0 to 1), 

https://user-images.githubusercontent.com/89664487/154856826-78b735d0-3982-4a9b-a04e-dee9910965ec.mp4

that's the easy part, and then to give it a smoother look I'm trying to fade out the last tab when another tab gets opened. However I can't really figure out a way how could I do that without having to store the opacity values somewhere outside the tab function.

Inside TabItemEx
`    // Render tab shape
    ImDrawList* display_draw_list = window->DrawList;
    
    ImU32 tab_col = GetColorU32(ImGuiCol_TabActive);
    const ImVec4 color = ColorConvertU32ToFloat4(tab_col);
    

    tab_col = ColorConvertFloat4ToU32(ImVec4(color.x, color.y, color.z, 0));

    float t = tab_contents_visible ? 1.0f : 0.0f;

    if (g.LastActiveId == g.CurrentWindow->GetID(label))// && g.LastActiveIdTimer < ANIM_SPEED)
    {
        float time = ImSaturate(g.LastActiveIdTimer / 0.5f);
        t = time;

    }

     tab_col = ColorConvertFloat4ToU32(ImVec4(color.x, color.y, color.z, ImLerp(0.f, 1.0f, t)));

    

    TabItemBackground(display_draw_list, bb, flags, tab_col);`

I've been looking at it for some time and I ran out of ideas already. One thing that i think could work is that i could save the ID of the last window and then fade it out, but i don't really want to do that, i think that there has to be some better solution. 

Regards.

**Comment by AbbyIOM** [comment]
Hello @ebachard, thank you.

I understand the principle behind the fading however I don't understand how could I get fade out a button once it's not active anymore. I can only get the current active button or all unactive buttons, but I can't get the one specific button that was active before the current active button.

**Comment by ocornut** [comment]
You'll need storage somehow but also for fading out you'll probably need to alter the layout function to keep the space used during TabBarLayout() while a tab is fading out, and probably you'll want to also animate the horizontal offset of tabs so they don't teleport once the fading out tab is disabled (e.g. split tab->Offset into tab->OffsetAnim and tab->OffsetTarget).

Either way you are asking about a change we won't merge so you are on your own and this is mostly about figuring your own code.
