### ISSUE TITLE
REQUEST: Ability to whitelabel ImGui

### ISSUE THREAD

**Issue by gamagan** [ocornut/imgui#5041]
Please consider adding the ability to white-label ImGui. By this, I mean the ability to change ImGui's output name in things such as the Metrics window. The reason is to control the branding of the end-product if, for instance, we want to include tools such as the Metrics window. The end-users of the gui App, which are not necessarily developers, don't know what "Dear ImGui" is.
https://en.wikipedia.org/wiki/White-label_product

I think this could be done by using a #define for the default ImGui name, and then allowing its override in the config file.

```
#define ImGui_WHITELABEL "Guitopia"

#ifdef ImGui_WHITELABEL
#define ImGui_NAME ImGui_WHITELABEL
#else
#define ImGui_NAME "Dear ImGui"
#endif
```

**Comment by ocornut** [comment]
No thank you. Not going to add extra layers for the purpose of hiding our own “brand” if any. 

You can easily maintain a fork with an extra commit if you want ( but remember that MIT requires named attribution if you link with the project ).

**Comment by ocornut** [comment]
Beside Metrics is clearly full of dear imgui centric contents, this doesn’t seem to make much sense to me.
