### ISSUE TITLE
how to fix the left node width ? _NoResizeX doesn't work。

### ISSUE THREAD

**Issue by houchr** [ocornut/imgui#5042]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw3.cpp + imgui_impl_opengl3.cpp
Compiler: vistual studio 2019
Operating System: windows 11

**My Issue/Question:**

how to fix the left node width ? _NoResizeX doesn't work。

![image](https://user-images.githubusercontent.com/3382139/154901899-ba5b579f-330e-4615-a72a-fe6e25fe8889.png)

**code** 
```
    ImGuiID dockspace_id = ImGui::GetID("##Default");
    if (ImGui::DockBuilderGetNode(dockspace_id) == NULL) {
        ImGui::DockBuilderRemoveNode(dockspace_id);
        ImGuiDockNodeFlags dockspace_flags = ::ImGuiDockNodeFlags_NoResizeX | ImGuiDockNodeFlags_NoTabBar | ImGuiDockNodeFlags_NoDockingSplitMe;
        dockspace_id = ImGui::DockBuilderAddNode(dockspace_id, dockspace_flags);
        ImGui::DockBuilderSetNodeSize(dockspace_id, {1280,720});
        ImGuiID dock_left_id = dockspace_id;
        ImGuiID dock_right_id = ImGui::DockBuilderSplitNode(dock_left_id, ImGuiDir_Right, 0, nullptr, &dock_left_id);
        ImGui::DockBuilderSetNodeSize(dock_right_id, {1180,720});
        ImGui::DockBuilderSetNodeSize(dock_left_id, {100,720});
        ImGui::DockBuilderDockWindow("right", dock_right_id);
        ImGui::DockBuilderDockWindow("left", dock_left_id);
        ImGui::DockBuilderFinish(dockspace_id);
    }
```

**Comment by ocornut** [comment]
I'll close this so it can be moved to the other topics if necessary.
The correct feature (constraint support) will be posted here and all topics if/once developed.

**Comment by houchr** [comment]
thank you. it's working fine.
