### ISSUE TITLE
Questions about ImGuiIO::DeltaTime ?

### ISSUE THREAD

**Issue by tomazos** [ocornut/imgui#5043]
Couple of quick imgui questions if you have time...

The first code comment on `ImGuiIO`s Configuration section says `fill once`.  Is it not ok to modify the configuration between each frame?  (`example_null`, at least, seems to set `DisplaySize` and `DeltaTime` prior to each `NewFrame` / `Render`. ?)

The code comment on `ImGuiIO::DeltaTime` states:

   > Time elapsed since last frame, in seconds.

Our engine has a mailbox mode where frames are continuously rendered and the most recent render is presented at vsync-time.  In this mode, should I set `DeltaTime` to the time elapsed since last render or since last present?  (ie What is `DeltaTime` used for?)

What should `DeltaTime` be set to for the first frame, since there is no last frame?  Is zero okay? or is that going to break things?

Thanks

**Comment by ocornut** [comment]
That “fill once” comment is incorrect and will be changed now. All backends are submitting real wall clock time every time, its ok if it changes. 

DeltaTime=0.0 is accepted on the first frame to faciliate this. On subsequent frames it generally leads to an assert as it is considered a user mistake.

**Comment by tomazos** [comment]
Sure, thanks.
