### ISSUE TITLE
ConfigWindowsMoveFromTitleBarOnly issues with docked windows

### ISSUE THREAD

**Issue by CobaltXII** [ocornut/imgui#5044]
Hi, if you set ConfigWindowsMoveFromTitleBarOnly it prevents you from dragging windows above the main menu bar (as expected). This is good because it's impossible to lose your windows. However if you dock two windows together they can now be dragged above the menu bar and then lost. You have to restart the program for it to fix.

**Comment by ocornut** [comment]
Thanks for reporting! 
This is now fixed by 64519c6
