### ISSUE TITLE
 functionality InputTextMultiline 

### ISSUE THREAD

**Issue by tickox** [ocornut/imgui#5046]
Hello,

I'm trying to create a simple custom text editor that includes whatever functionality vim has.

I use InputTextMultiline.
I can't do several things:
  1) If 'k' is pressed, I would like to move the cursor to the right without displaying 'k'.
  2) I would like to have an event when Alt, Ctrl etc are clicked.
  3) I would like to be able to insert text whenever I want.

I'm not sure that all this is possible without directly touching the source code...

I'm on the docking branch.

thank you

**Comment by ocornut** [comment]
Would Zep solve your need ?
https://github.com/ocornut/imgui/wiki/Useful-Extensions#text-editors
