### ISSUE TITLE
Question about `ImGuiKey_ModXXX` ?

### ISSUE THREAD

**Issue by tomazos** [ocornut/imgui#5047]
There are four `ImGuiKeys` starting with `Mod`:

    ImGuiKey_ModCtrl
    ImGuiKey_ModShift
    ImGuiKey_ModAlt
    ImGuiKey_ModSuper

These are distinct from the keys:

    ImGuiKey_LeftCtrl
    ImGuiKey_LeftShift
    ImGuiKey_LeftAlt
    ImGuiKey_LeftSuper
    ImGuiKey_RightCtrl
    ImGuiKey_RightShift
    ImGuiKey_RightAlt
    ImGuiKey_RightSuper

I'm sending imgui `AddKeyEvent` (up and down) for the `LeftXXX` and `RightXXX` versions, but not for the `ModXXX` versions.  I suspect I'm supposed to send up/down for the `ModXXX` versions too, right?

The code comment on `ModXXX` says:

> * This is mirroring the data also written to io.KeyCtrl, io.KeyShift, io.KeyAlt, io.KeySuper, in a format allowing them to be accessed via standard key API, allowing calls such as IsKeyPressed(), IsKeyReleased(), querying duration etc.
> * Code polling every keys (e.g. an interface to detect a key press for input mapping) might want to ignore those and prefer using the real keys (e.g. ImGuiKey_LeftCtrl, ImGuiKey_RightCtrl instead of ImGuiKey_ModCtrl).
> * In theory the value of keyboard modifiers should be roughly equivalent to a logical or of the equivalent left/right keys.  In practice: it's complicated; mods are often provided from different sources. Keyboard layout, IME, sticky keys and backends tend to interfere and break that equivalence. The safer decision is to relay that ambiguity down to the end-user...

Sorry but I don't follow this.  So when the user presses the LSHIFT key I send:

    io.AddKeyEvent(ImGuiKey_LeftShift, true);

do I also have to send:

    io.AddKeyEvent(ImGuiKey_ModShift, true);

as well?

(It's not entirely clear why Imgui can't do that itself by tracking the down state of the `LeftXXX` and `RightXXX` versions.)

**Comment by ocornut** [comment]
The comment you quoted exactly says why and there are 5 backends to refer to.

**Comment by ocornut** [comment]
If in your framework you consider that eg ModXXX = LeftXxx || RightXxx you can submit the value as such.

But your framework should also gives you mod keys and somehow they are bizarre artifacts from decade ago and a bunch of software are piling in to have their say into what their value are, and you’ll notice that if you use a low level backend eg win32 that assertion that ModXxx = LeftXxx || RightXxx isn’t right anymore with all keyboards and layouts and IME setup.

**Comment by tomazos** [comment]
I see in SDL it is doing:

    io.AddKeyEvent(ImGuiKey_ModCtrl, (sdl_key_mods & KMOD_CTRL) != 0);
    io.AddKeyEvent(ImGuiKey_ModShift, (sdl_key_mods & KMOD_SHIFT) != 0);
    io.AddKeyEvent(ImGuiKey_ModAlt, (sdl_key_mods & KMOD_ALT) != 0);
    io.AddKeyEvent(ImGuiKey_ModSuper, (sdl_key_mods & KMOD_GUI) != 0);

on every keyevent.

and I'm trying equivalently:

    io.AddKeyEvent(ImGuiKey_ModCtrl, is_key_down(wKey::LCTRL) || is_key_down(wKey::RCTRL));
    io.AddKeyEvent(ImGuiKey_ModShift, is_key_down(wKey::LSHIFT) || is_key_down(wKey::RSHIFT));
    io.AddKeyEvent(ImGuiKey_ModAlt, is_key_down(wKey::LALT) || is_key_down(wKey::RALT));
    io.AddKeyEvent(ImGuiKey_ModSuper, is_key_down(wKey::LGUI) || is_key_down(wKey::RGUI));

in our engine.

It just caught me a little by suprise.  I think the comment on the `ModXXX` version could be improved by making it clearer initially that the contract is that `ModXXX` AddKeyEvents need to be sent in addition to the `LeftXXX` and `RightXXX` versions.

**Comment by tomazos** [comment]
In particular, the phrase that is unclear is "This is mirroring the data also written to XXX".

Anyway, thanks again for your help.

**Comment by ocornut** [comment]
Right. I’ll add better commentary (old vs new backend do it the opposite way which can be confusing). Thank you !
