### ISSUE TITLE
Feature Request: Font Subpixel Rendering

### ISSUE THREAD

**Issue by tomazos** [ocornut/imgui#5049]
Sorry in advance if you already know all this (or already support the feature)...

(LCD) Subpixel rendering refers to a technique used primarily in font rendering where the physical displacement of the RGB cells of an LCD display is used to smooth out the edges of a border.  A simple implementation is to render the image (font glyph) to a 3x wide greyscale image (that is, rather than creating a WxH size glyph use a 3W x H size glyph), and then pack each row by taking consecutive sequences of 3 pixels P0, P1, P2, and packing them into one RGB pixel in RGB order (R = P0, G = P1, B = P2) - turning the 3W x H greyscale image into a WxH RGB image. (see https://www.grc.com/ctwhat.htm)

The technique is used by all modern operating systems and web browsers to render fonts, as you can tell by taking a screen shot and zooming in on the pixels and see the left edge is redish and the right edge is bluish.  It's why they look cripser than non-subpixel rendered fonts.  (In freetype, for example, the relevant setting is https://freetype.org/freetype2/docs/reference/ft2-lcd_rendering.html.)

The default imgui font ProggyClean as a 1-bit bitmap font, so subpixel rendering has no impact on it, but for other fonts it does.

I think it could be implemented in imgui by changing the font atlas to a real RGB image rather than greyscale, and doing subpixel rendering when generating it, and then requiring backends to use GetTexDataAsRGBA32 and not GetTexDataAsAlpha8.  (Although I'm not 100% clear on the details of how alpha blending works with colored fonts in the shaders, I'm sure it could be figured out.  I think multiplication `texture(font_atlas) * params.col` should continue to work mostly fine.)

**Comment by tomazos** [comment]
Oops, I guess this is a dupe of https://github.com/ocornut/imgui/issues/2468

**Comment by ocornut** [comment]
And  #2986
