### ISSUE TITLE
Combo drop down list shortened when close to the bottom of ImGui display

### ISSUE THREAD

**Issue by RyokoAkizuki** [ocornut/imgui#505]
Especially when the combo is the last widget of a gui window, I see no way to access it except moving the window which is not very convenient.
Maybe a minimum height should be set and align its bottom to sys window like hover tips of graphs do.
![image](https://cloud.githubusercontent.com/assets/968003/12544280/aadcab2c-c373-11e5-92cb-92fb0e1b7f25.png)

**Comment by ocornut** [comment]
So the issue isn't about "the last widget of a gui window" but the fact that the combo popup is clipped by your display size, not by any window size. I would need to alter the positioning accordingly to move the popup over the combo when possible. It's usually a little tricky to handle all corners cases with small windows.

**Comment by RyokoAkizuki** [comment]
Well I was confused with these two sizes then. What I wanted to say is that when a combo is
* the last widget in a window,
* very close to the bottom of the window,
and
* the bottom of the window is very close to rendering window,
I'll have to move the windows in order to use the combo because there is no more space to scroll down anymore.
Anyway, an improvement on this would be great.

**Comment by ocornut** [comment]
Which can be shortened as:
- When a combo is close to the bottom of the rendering window

I don't know when I'll be able to look into it, will do eventually.

**Comment by texisthelex** [comment]
I've fixed this problem adding this code after line 8052 in imgui.cpp:
```
		// If the rectangle goes below the DisplaySize
		if (popup_rect.Max.y > g.IO.DisplaySize.y)
		{
			float delta = popup_rect.Max.y - g.IO.DisplaySize.y;
			popup_rect = ImRect(ImVec2(frame_bb.Min.x, frame_bb.Max.y - delta), ImVec2(frame_bb.Max.x, frame_bb.Max.y + popup_height - delta));
		}
```

**Comment by ocornut** [comment]
@texisthelex That would be ok but it overlaps the main widget. 
I have now made it that the combo move above the widget if there's not enough space below AND there's more space above than below. It should be ok in most cases (tried a few difference cases) and never overlap the parent widget.
