### ISSUE TITLE
Setting flags on child within table

### ISSUE THREAD

**Issue by dbr** [ocornut/imgui#5050]
**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: docking

Via imgui-rs

**My Issue/Question:**

I am using the new tables API, creating a table within a child view.

Based on some condition, I set `ImGuiWindowFlags_NoInputs` flag on the containing child window to avoid it capturing scroll wheel events

This works fine, *unless* the table uses `SCOLL_X` or `SCROLL_Y` - in this case, the table creates another child window which doesn't appear to inherit the no-input flag

I guess this is has two parts:

1. Is it intentional the child windows ignore the `No*Inputs` flags  from their parents? (I suspect so)
2. Is there a way to set the flags on the child window (maybe-)created by the table API?

(I suspect this might be a hole in the imgui-rs bindings and has an obvious answer in C++ API)

**Comment by ocornut** [comment]
Using ScrollX / ScrollY flag implies content not fitting and user scrolling through it, and _NoInputs would inhibit interacting with scrollbars and mouse wheeling, so this is a little bit strange. What is the use case?

1. I don't recall designing for a specific intent. Apparently we only discussed that inheritance in the context of mouse wheeling (e.g. #1380) so this probably needs to be thought.
2. No. We could side-step "solving" the general design issue of point 1 by having tables take on the responsibility of this _NoInputs forwarding, similar to what we did for #3367 (commit eb18636) for another flag, tho in essence this opens the same question just at a different scope.

**Comment by dbr** [comment]
> and _NoInputs would inhibit interacting with scrollbars and mouse wheeling, so this is a little bit strange. What is the use case?

Permenantly setting NoInput would indeed be weird, but I'm only setting it in certain conditions.

Specifically I am displaying a table inside something along the lines of [imnodes](https://github.com/Nelarius/imnodes) - when the node is selected, the table works as usual (scrollwheel scrolls the table etc), but when the node is deselected I want to set the `NoInput` flag to avoid it interfering with navigation shortcuts

Essentially trying to disable the table - I did also also try using the "disable" feature to achieve the same thing, but this passes through scroll events:

![scrolling a disabled list box widget](https://user-images.githubusercontent.com/509/155824489-2cb354f4-d277-4f85-9af7-f9ac59d34149.gif)

**Comment by ocornut** [comment]
I don't have a good answer for you yet but interestingly the InputOwner feature I've been recently working on should have been to solve this.

**Comment by ocornut** [comment]
> Specifically I am displaying a table inside something along the lines of [imnodes](https://github.com/Nelarius/imnodes) - when the node is selected, the table works as usual (scrollwheel scrolls the table etc), but when the node is deselected I want to set the NoInput flag to avoid it interfering with navigation shortcuts

Which navigation shortcuts would be interfering, if the node is unselected the table probably isn't focused?

> I did also also try using the "disable" feature to achieve the same thing, but this passes through scroll events:

That's interesting and I can confirm that on a `BeginDisabled(), BeginTable()` sequence scrolling can be be activated with the mouse wheel, because this scrolling doesn't use the scrollbar widget per se (you can scroll without a scrollbar).

Those changes I mentioned have been pushed a few months ago.

You can use:
```
ImGui::SetKeyOwner(ImGuiKey_MouseWheelY, ImGui::GetID("Whatever"));;
```
or
```
ImGui::SetKeyOwner(ImGuiKey_MouseWheelY, 0, ImGuiInputFlags_LockThisFrame);
```

Under a specific conditional test (e.g. Table hovered?) to disable this input + BeginDisabled() and I think that would solve your problem.
