### ISSUE TITLE
click on Inputtext no refreshing text

### ISSUE THREAD

**Issue by kmilo9999** [ocornut/imgui#5054]
**Version/Branch of Dear ImGui:**

Version: 1.73
Branch: XXX _(master/viewport/docking/etc.)_

OpenGL/ Visual studio 2019/ 

Back-ends: Custom engine

Operating System: Windows 10

I have a modal window that contains an input text field. Using the keyboard events from my custom engine, I update a char array that I linked to the the input text field. However, when I click on the input field (I guess to do focus on it), the input text field doesnt refresh from the data in my char array. If I click outside the input field (lose focus), the input refresh with the char array (check the gif below). 

Any thoughts why this could be happening?

**Screenshots/Video**

![inputtext-issue](https://user-images.githubusercontent.com/16551165/155621142-cca29cfc-888a-463f-8625-a9e05b6d1a02.gif)

```
// Here's some code anyone can copy and paste to reproduce your issue
 ImGui::OpenPopup(modal_window_name.c_str());
if (ImGui::BeginPopupModal(modal_window_name.c_str(), &m_open_modal))
{
  char* writable = new char[m_copy_name.size() + 1];
  std::copy(m_copy_name.begin(), m_copy_name.end(), writable);
  writable[m_copy_name.size()] = '\0'; // don't forget the terminating 0
   ImGui::InputText("##textcameraname", writable, IM_ARRAYSIZE(writable));
}
ImGui::EndPopup();
```

**Comment by Ressley** [comment]
Use static size for writable

**Comment by jokteur** [comment]
I suppose that `m_copy_name` is a `std::string` ?
In which case, you can include [imgui_stdlib](https://github.com/ocornut/imgui/blob/master/misc/cpp/imgui_stdlib.h) and directly use your std::string:
```cpp
#include "misc/cpp/imgui_stdlib.h"

[...]
ImGui::InputText("##textcameraname", &m_copy_name);
```

**Comment by kmilo9999** [comment]
I tried both suggested approaches, none of them worked :(
- Set a static size for `writable`  did not change the behavior.
```
       char writable[50];
      std::copy(m_copy_name.begin(), m_copy_name.end(), writable);
      writable[m_copy_name.size()] = '\0'; // don't forget the terminating 0
      ImGui::InputText("##textcameraname", writable, IM_ARRAYSIZE(writable));
```
- Switch to misc/cpp/imgui_stdlib.h 
```
 #include "./imgui_stdlib.h"
 ImGui::InputText("##textcameraname",&m_copy_name );
```
In this case, the inputtext only refresh if there's no focus on the ui element.

What could be the main root of the issue? I could debug specific parts if you can point them out.
My educated guess is, there are problems relating the active window and the on-focused element. I have code on my custom engine where the active imgui-window is the one the mouse is hovering. I dont know if that is affecting the focus properties of the InputField.

**Comment by ocornut** [comment]
`InputText()` owns a copy of the data when active, it won't reload text from the user arg when active.
See #3878 , #2890 , #2881 , #1506

**Comment by kmilo9999** [comment]
implementing the #3290 workaround did the trick.
