### ISSUE TITLE
When exactly is the InputText() "CallbackEdit" callback executed?

### ISSUE THREAD

**Issue by dj-bauer** [ocornut/imgui#5056]
**Demo-Config About information**
```
Dear ImGui 1.88 WIP (18709)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=11
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1050.00,1170.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master
**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp _(or specify if using a custom engine/back-end)_
Compiler: G++ _(if the question is related to building or platform specific features)_
Operating System: Linux

**My Issue/Question:**

When is the edit-callback of a Text field exactly executed?
Because I try to do some kind of real time translation or encryption application and try to make the two text-fields editable and instantly influence the other one.
But it seems like when I type in some text into the first one, the second one is always staying one letter behind.
This lead me to the assumption, that the callback is called before the actual underlying text is changed.
Is that true and is there a way to have a callback after the content is changed?

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
string a;
string b;
struct Callbacks {
	static int ACallback(ImGuiInputTextCallbackData* data) {
		if(data->EventFlag == ImGuiInputTextFlags_CallbackEdit)
			b.assign(a);
		return 0;
	}
	static int C_ClearCallback(ImGuiInputTextCallbackData* data) {
		if(data->EventFlag == ImGuiInputTextFlags_CallbackEdit)
			a.assign(b);
		return 0;
	}
};

ImGui::Begin("Example Bug");
ImGui::InputTextMultiline("Text-A", &a, ImVec2(0,0), ImGuiInputTextFlags_CallbackEdit, Callbacks::ACallback);
ImGui::InputTextMultiline("Text-B", &b, ImVec2(0,0), ImGuiInputTextFlags_CallbackEdit, Callbacks::BCallback);

ImGui::End();
```

**Comment by ocornut** [comment]
If you want that state in the callback simply use the `data->Buf` field passed to the callback.

**Comment by dj-bauer** [comment]
Ah, thank you
I looked through all the demos and headers and I found the data->Buf piece.
I must have missunderstood its function then because I assumed it would just return me a pointer to the underlying string object.

**Comment by ocornut** [comment]
The internals of InputText() are unfortunately a little bit complicated right now (tho we have an upcoming refactor to simplify it and maybe that pointer will point to the same address in some instance, but there are also various cases in need of a “only write on validation” which will defeat that).
