### ISSUE TITLE
Tree name and InputText inside of it.

### ISSUE THREAD

**Issue by Skovv** [ocornut/imgui#5059]
Hi, fast question...

` ...
if (handle->vRename[i]) {
                        ImGui::SetNextItemOpen(true);
                        //handle->vRename[i] = false;
                    }
if (ImGui::TreeNode((char*)((*handle->vName)[i]+" ##" + std::to_string(uid)).c_str())) {
                        if (handle->vRename[i]) {
                            ImGui::SetKeyboardFocusHere();// (*handle->vName)[i].size() - 1);
                            handle->vRename[i] = false;
                        }
                        if (ImGui::InputText(("Name ##nm" + std::to_string(i)).c_str(), &(*handle->vName)[i])) handle->vRename[i] = true;
...`

Like you see: i have TreeNode and inside TextInput. TreeNode name is InputText string. The problem: when i TreeNode name is changing then it's closing but i did it to autoopen. How to set InputText activate(and cursor on the end of text) when tree name is changed?

**Comment by ocornut** [comment]
There's no "fast question". You may want to use a stable ID for the TreeNode() that doesn't include the ID (e.g. use "###" to dissociate name from ID).

Didn't follow requested guidelines or issue template. 
- Please make sure you have carefully read the FAQ and guidelines (https://github.com/ocornut/imgui/issues/2261)
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and a Minimal, Complete and Verifiable Example, and then reply here when edited.

Closing.
