### ISSUE TITLE
the widget in horizontal scrolling demo flickers when its horizontal scrolling bar intersects with menus

### ISSUE THREAD

**Issue by RyokoAkizuki** [ocornut/imgui#506]
![flicker](https://cloud.githubusercontent.com/assets/968003/12544345/4a7d8fde-c374-11e5-865c-94973dc8772b.gif)

**Comment by ocornut** [comment]
How do you get it to permanently flicker like that?
I can get the scrollbar to disappear (which is a minor issue but needs fixing) but not flicker.

**Comment by ocornut** [comment]
Didn't get your exact repro but I think it is fixed now. Let me know!

**Comment by RyokoAkizuki** [comment]
Yes it's fixed now.
