### ISSUE TITLE
Freeing ID3D11ShaderResourceView memory after drawing

### ISSUE THREAD

**Issue by Stefan0Schulz** [ocornut/imgui#5060]
**Version/Branch of Dear ImGui:**

Version: 1.88 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: MSVC 2019
Operating System: Windows 10

**My Issue/Question:**

When changing the size of the texture, the memory starts to increase, but if you do not touch the size, then the memory will not change.
When debugging, I realized that if you do not call PSSetShaderResources, then the problem with increasing memory disappears. Also, if you completely remove the SRV release code, then the memory will increase constantly, regardless of the change in texture size.
Creation of SRV taken from the wiki.

**Screenshots/Video**
![srv_issue](https://user-images.githubusercontent.com/100529912/155895330-4a1728cb-32d5-45e5-b711-d17547ce3b98.gif)

```
//srv create
static ImVec2 size = ImVec2(40, 10);
static ID3D11ShaderResourceView* resource = nullptr;
create_srv(&resource, size.x, size.y);

ImGui::GetBackgroundDrawList()->AddImage(resource, ImVec2(0, 0), size);

/*other code, ImGui::Render(); etc.*/

//release
//there is no difference in which part of the code the srv will be freed, the problem does not disappear from this
//ID3D11ShaderResourceView::Release() returns 0
if(resource) { resource->Release(); resource = nullptr; }
```

**Comment by ocornut** [comment]
That question has nothing to do with Dear ImGui this is a DirectX11 question.
