### ISSUE TITLE
Why do some mobile phones have black screens when they are turned on?

### ISSUE THREAD

**Issue by LarissaLycoris** [ocornut/imgui#5063]
Huawei's Kirin chip and MediaTek chip's mobile phone will turn on imgui mobile phone with black screen. Why? thank you

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template.  Please make sure you have the guidelines. Question probably has nothing to do with Dear ImGui.
Closing.

**Comment by LarissaLycoris** [comment]
> Didn't follow requested guidelines or issue template. Please make sure you have the guidelines. Question probably has nothing to do with Dear ImGui. Closing.

I tested the problem. Huawei Qilin and MediaTek chips caused the black screen because the Chinese font could not be loaded. Is there a compatible Chinese font loading method? If it is not suitable for Chinese font, there will be no problem. If the system comes with the font, there will be a black screen. If you don't use the font, there will be no problem. Because the project must use Chinese, is there any way to fix it?
