### ISSUE TITLE
Where can I use ImGui?

### ISSUE THREAD

**Issue by artemko22** [ocornut/imgui#5064]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: XXX _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Operating System: Windows

**My Issue/Question:**
Hello, I have some questions. Where can I use ImGui?
Can I use it to create an interface in my game?
Thank you in advance for the answer.

**Comment by Chomiczjakub** [comment]
Well ImGui is mostly for Debug usage.
But If you don't want to make your own Gui for your game then yes u could use it for it I bealive. 
Everything u need to know is in here: https://github.com/ocornut/imgui/blob/master/LICENSE.txt

**Comment by artemko22** [comment]
Thanks for the answer

**Comment by ocornut** [comment]
You can use it almost everywhere. As to whether you’d want to use it for your game interface, it depends if you want your game interface to look and behave like Dear ImGui. Up to you.
