### ISSUE TITLE
When will Android 12 be supported

### ISSUE THREAD

**Issue by 577477776** [ocornut/imgui#5069]
When will Android 12 be supported

**Comment by rokups** [comment]
Android backend is minimalistic enough that there should be no issues on new android versions. If you have some issue you should describe it.

**Comment by 577477776** [comment]
Full screen can not penetrate the touch screen to repaint and flash many repetitions. It is a memory leak.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rokas ***@***.***&gt;; 
发送时间: 2022年3月3日(星期四) 下午4:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ocornut/imgui] When will Android 12 be supported (Issue #5069)






Android 后端是足够简约,不应该有新的 Android 版本的问题.如果你有什么问题，你应该描述一下。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
使用 GitHub Mobile 随时随地发送分流通知IOS 系统或Android.

**Comment by rokups** [comment]
Does this happen with an official example?

**Comment by 577477776** [comment]
I don't know ,After work,&nbsp; I'm going to have a test




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rokas ***@***.***&gt;; 
发送时间: 2022年3月3日(星期四) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ocornut/imgui] When will Android 12 be supported (Issue #5069)





 
Does this happen with an official example?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ocornut** [comment]
Either way the answer is, if there’s an issue on official example+backends please provide clear description of the issue + ideally provide a fix. We are ourselves mostly not Android users so issues are reliant on users.
