### ISSUE TITLE
ImGui::InputText : ImGuiInputTextFlags_ XXX : lost focus

### ISSUE THREAD

**Issue by krys-spectralpixel** [ocornut/imgui#507]
Hi,

I'm looking for a way to "validate" my content when, not only when we press enter, but also we it loss the focus. I just need a way to avoid to validate the content each time I press a key.

Is it possible ?

**Comment by ocornut** [comment]
You can't tell when the focus is lost but may be able to track it yourself comparing the state of IsItemActive() over frames.
