### ISSUE TITLE
TableNextRow crashes if the table is invisible

### ISSUE THREAD

**Issue by anszom** [ocornut/imgui#5070]
**Version/Branch of Dear ImGui:**

Commit fa2b318dd6190852a6fe7ebc952b6551e93899e0

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + custom Xlib adapter (irrelevant)
Compiler: gcc (irrelevant)
Operating System: Linux (irrelevant)

**My Issue/Question:**

TableNextRow doesn't check if CurrentTable is not null. If the table was culled (for example by "folding" the enclosing window), and the code doesn't make an early-out return when the Begin* calls return false, TableNextRow will crash.

As far as I understand, early-out is recommended but not required.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
	ImGui::Begin("whatever");
	ImGui::BeginTable("else", 2);
	ImGui::TableNextRow();
	ImGui::TableNextColumn();
	ImGui::TableNextColumn();
	ImGui::EndTable();
	ImGui::End();
```

**Comment by ocornut** [comment]
You should always test the return value of BeginTable(), all the comments and examples are stating so.

**Comment by anszom** [comment]
For some reason I'm not able to find these comments you mention. I've searched again and found only the comment next to EndTable stating "only call EndTable() if BeginTable() returns true!". Perhaps this should be better documented (or I'm just blind).

**Comment by ocornut** [comment]
I’ll add more comments.

The only inconsistent api are Begin() and BeginChild() which we will fix someday (tricky change).
