### ISSUE TITLE
External overlay crashes with DX12 and multi-viewports

### ISSUE THREAD

**Issue by jeremykleve** [ocornut/imgui#5071]
Version: 1.85 and up
Branch: docking

DX12

Back-ends: imgui_impl_dx12.cpp + imgui_impl_win32.cpp 
Operating System: Win10

**My Issue/Question:**
I am running into an issue where when I have multi-view enabled and am trying to run the external software Riva Tuner Statistics Server that comes with MSI Afterburner the demo version DX12 imgui will crash when Riva tries to detect the window. . Is there a known workaround for this besides disabling multi-view?

More specifically the demo will crash when trying to move any secondary window from within the main view to the desktop or vice-versa.  

![image](https://user-images.githubusercontent.com/40273160/156684956-9da6e0d1-e517-42b0-b733-6da87aa78540.png)

Setting the Application Detection Level to none for the specific app will prevent Riva from trying to detect and overlay the demo and it will then function properly. The problem with using this workaround is that it only covers that one specific case. It seems that most any software that overlays can cause this issue.

Edit1: Appended Callstacks
The breakpoint always seems to happen at the call to swapchain->present(1,0)

![image](https://user-images.githubusercontent.com/40273160/157094481-a48c500c-119a-4114-ad9a-09b7f7d40165.png)
First callstack has dxgi debug enabled

![image](https://user-images.githubusercontent.com/40273160/157094864-a18d2b43-613c-463c-a95c-b185181f5903.png)
Second callstack has dgxi debug disabled

**Comment by ocornut** [comment]
Sounds like a bug in Riva but if you report a crash you should always report a callstack (as instructed in issue submission guidelines) which as much symbols decoded as possible, otherwise your report is harder to take action on.

**Comment by ocornut** [comment]
>  It seems that most any software that overlays can cause this issue.

What makes you say such a statement ? Have you seen other software crash in the same way ?

**Comment by jeremykleve** [comment]
> Sounds like a bug in Riva but if you report a crash you should always report a callstack (as instructed in issue submission guidelines) which as much symbols decoded as possible, otherwise your report is harder to take action on.

I appended my call stacks, one with and without dxgi debug. Most of the symbols are related to the directx stuff which im still kinda new to in general. The RTSSHooks64.dll is specific to Riva.


> > It seems that most any software that overlays can cause this issue.
> 
> What makes you say such a statement ? Have you seen other software crash in the same way ?

I spoke with the developer behind Riva and he told me it is usually related to the D3D12 debug layer or multiple swapchains being generally incompatible with overlays. Hence my generalization there. I also had the same issue with EVGA PrecisionX at one point. I am trying to do my own research on this but having difficulty finding related info. Ill be looking to post in some D3D12 forums but wanted to see if there was any known workarounds in this community? If not feel free to close the issue outright since its not specifically caused by ImGui itself. 

I would have preferred somewhere else to post the question but I saw that the discussions section is only for build/run failures. Is there a forum/discord/discussion group where questions like this might be more acceptable?

**Comment by ocornut** [comment]
I don't know of a workaround but it seems like a bug either in Riva / RTSS either in Dx11on12.
I think if there is a fix or workaround to make it would probably be on the overlay's end.

> I would have preferred somewhere else to post the question but I saw that the discussions section is only for build/run failures. Is there a forum/discord/discussion group where questions like this might be more acceptable?

This is a good location to ask.
(The discussion system of github is poor (I really wish github has a Discussions tabs which was EXACTLY like Issues just with a different name, but nope, they decided to make something inferior and remove the useful stuff of Issues) and Discord has been closed because it has negative usefulness IHMO on overall support and information availability.)

**Comment by ocornut** [comment]
Closing this as answered.

**Comment by sherief** [comment]
For future readers coming across this, it's due to a bug in RivaTuner: It hooks Present() so the swapchain buffers are usually in the COMMON / PRESENT resource state, but it doesn't properly transition the swap chain buffers to RENDER_TARGET before executing command lists with Draw*() calls - you would be seeing debug output like this: 

```
D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: Using Draw on Command List (0x000002907928E5F0:'Unnamed ID3D12GraphicsCommandList Object'): Resource state (0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]) of resource (0x000002903B485EF0:'Swapchain Buffer #0') (subresource: 0) is invalid for use as a render target.  Expected State Bits (all): 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET, Actual State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Missing State: 0x4: D3D12_RESOURCE_STATE_RENDER_TARGET. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR EXECUTION #538: INVALID_SUBRESOURCE_STATE ]
```

It's unrelated to multiple swap chains, happens on systems with single GPU or multi GPU.
