### ISSUE TITLE
[imstb_truetype] Request on Upgrade to latest version

### ISSUE THREAD

**Issue by Jony01** [ocornut/imgui#5075]
**My Issue:**
I found on Ubuntu font _"/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf"_  [NotoColorEmoji.zip](https://github.com/ocornut/imgui/files/8187238/NotoColorEmoji.zip). When I try to initialize the font by function `stbtt_InitFont`. InitFunction ends inside `stbtt__find_table`, which return 0 and disallow initialization of the font.

**To Reproduce:**
Run test and see it is uninitializabled font.
```
TEST_CASE("Initialize NotoColorEmoji") {
    std::string font_path = "NotoColorEmoji.ttf";
    FILE *file = fopen(font_path.c_str(), "rb");
    REQUIRE(file != nullptr);
    // find size of file
    REQUIRE(fseek(file, 0L, SEEK_END) == 0);
    size_t size = ftell(file);
    REQUIRE(size != 0);
    rewind(file);
    std::vector<unsigned char> buffer(size);
    size_t count_loaded_bytes = fread((void *) &buffer.front(), 1, size, file);
    REQUIRE(count_loaded_bytes == size);
    int font_offset = stbtt_GetFontOffsetForIndex(buffer.data(), 0);
    REQUIRE(font_offset >= 0);
    stbtt_fontinfo font_info;
    CHECK(stbtt_InitFont(&font_info, buffer.data(), font_offset) != 0); 
}
```

**New version of stb_truetype**
I checked that latest version v1.26 of stb_truetype [[link](https://github.com/nothings/stb/blob/master/stb_truetype.h)] can initialize this font. 

ImGui version of file [imstb_truetype.h](https://github.com/ocornut/imgui/blob/master/imstb_truetype.h) is v1.20 (contain imgui modifications).

**Comment by quetzalsly** [comment]
I hope all of the stb libs get updated, theres been lots of changes to them and imgui last updated them 8 months ago.

**Comment by ocornut** [comment]
I have now updated all STB libs, however I can't seem to load my copy of `NotoColorEmoji.ttf` with stb_truetype 1.26 still.
