### ISSUE TITLE
Vulkan Dynamic window resizing

### ISSUE THREAD

**Issue by Chomiczjakub** [ocornut/imgui#5076]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: Docking

**Backend/Render/Compiler/OS**

Backend: GLFW
API: Vulkan
Compiler: MSVC
OS: Windows

----

**My Issue/Question:**

Hi not that long ago I started learning Vulkan.
I just went through simple implementation and when I was on swapchain and renderpasses topic I decided to Implement ImgGui,
because I believe that is the fastest way to see anything what is going on in my program and everything is fine it works perfectly,
but one thing just irritates me... When I try to resize my window this happens.

**Screenshots/Video**

![Untitledxd](https://user-images.githubusercontent.com/72545872/156850455-e63f762c-9a79-4464-8f11-aadbc8065d05.png)

I know that it is more like Vulkan problem but as I'm aware pipeline is created on dear ImGui site,
so I can't really give it Dynamic State. Anybody have some ideas/tips how can it be done? 
I would be really grateful for some help with this.

**Comment by jeremykleve** [comment]
When you finish resizing does the white portion snap to the new dimensions?

**Comment by Chomiczjakub** [comment]
Ok then. if it's not imgui issue then i will close it and try to think about the fix myself. Thanks for your answer!
