### ISSUE TITLE
How to set placeholder in an inputbox

### ISSUE THREAD

**Issue by ABPozharliev19** [ocornut/imgui#5077]
I'm trying to reproduce a login form, and I would like to set a placeholder of the InputText box. Is that possible and how?

**Comment by ABPozharliev19** [comment]
Nvm, found out about `InputTextWithHint`

**Comment by zaun** [comment]
Hint is an odd term to use. Hits normally is small text below the input giving some help about what should be inputted, like current char count/max count, or to display an error message.

Placeholder is always the term I've seen used for text that is display when no use input has been entered.

Just my 2 cents 😀
