### ISSUE TITLE
SameLine doesn't seem to work across multiple columns

### ISSUE THREAD

**Issue by RyokoAkizuki** [ocornut/imgui#508]
As a layout like #324 has, it would be more comfortable to look at it if the text of tree node labels align with that in the first widget on the right side. However when I try to achieve that I found that neither call SameLine before nor after NextColumn would work.
```
ImGui::Columns(2);
ImGui::Text("ABCD");
ImGui::SameLine();
ImGui::NextColumn();
ImGui::Button("Push");
ImGui::Columns(1);
```
Or
```
ImGui::Columns(2);
ImGui::Text("ABCD");
ImGui::NextColumn();
ImGui::SameLine();
ImGui::Button("Push");
ImGui::Columns(1);
```
(In the second case the button is nearly invisible)

**Comment by ocornut** [comment]
I don't understand what you could even mean or what you are trying to achieve.
both SameLine() and NextColumns() are setting the cursor position so it feels contradictory to use them together.

**Comment by RyokoAkizuki** [comment]
Sorry it might due to my awful use of English...so embarassing
Maybe using a picture from #324 to explain would be more clear.
![image](https://cloud.githubusercontent.com/assets/968003/12580383/437b563e-c46a-11e5-96f8-42d7fd8bbc9e.png)
I mean that are there any way to make text of two widgets in different columns in the same line. For example a TreeNode in column 0 and a LabelText in column 1.
Thank you very much.

**Comment by RyokoAkizuki** [comment]
Or just add paddings to / set heights of tree node labels?

**Comment by ocornut** [comment]
They are already aligned in that picture.. so I'm not sure what you are asking.
If you check the Property Editor demo code you will see it is using AlignFirstTextHeightToWidgets as a helper to vertically align a small line of text (normal text or tree node) to a large line of items (widgets).

**Comment by RyokoAkizuki** [comment]
No I moved them down by 4 pixels....Ok I'll check it out. Thank you.

**Comment by RyokoAkizuki** [comment]
It works like a charm.

**Comment by ocornut** [comment]
Cool !
Please have a closer look at the running demo and the demo code when possible, it has answer to a lot of questions :)

**Comment by RyokoAkizuki** [comment]
I tried but without precious clues from developer it appears to be somewhat difficult...

**Comment by ocornut** [comment]
No worry. I'll keep improving the demo/docs. Also look at the comment in imgui.h/imgui.cpp when possible. I just want to make sure you are doing your share of homework and research before asking, because all the time I take to answer user questions I'm not putting it into improving the library and time has been limited lately.

**Comment by RyokoAkizuki** [comment]
Of course :)

**Comment by RyokoAkizuki** [comment]
I finally found this kind of layout demonstrated in ShowExampleAppPropertyEditor in the demo....
