### ISSUE TITLE
How to use the built-in code to implement the drawing function?（just need help）

### ISSUE THREAD

**Issue by 1111mp** [ocornut/imgui#5080]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_Vulkan.cpp
Operating System: Windows/MacOS

**My Issue/Question:**

I am following the `example_glfw_vulkan`. I've looked in a lot of places, but I can't see exactly how to draw something (like a triangle) based on this example. I saw that in the `imgui_impl_vulkan.cpp` file there is already state data about Shaders and VertexBuffer and IndexBuffer needed for drawing. Is it possible to set these data directly and then be able to draw a triangle, or is there a corresponding method to do this. Maybe I'll need to rewrite everything I need to do Vulkan rendering myself, as in this [blog](https://tstullich.github.io/posts/vulkan-sandbox/) post. I'm just starting to learn Vulkan and ImGui and I'm really overwhelmed at the moment. I hope to be able to get help, really appreciate it.

Maybe like this:
```
ImDrawData* main_draw_data = ImGui::GetDrawData();
        const bool main_is_minimized = (main_draw_data->DisplaySize.x <= 0.0f || main_draw_data->DisplaySize.y <= 0.0f);
        wd->ClearValue.color.float32[0] = clear_color.x * clear_color.w;
        wd->ClearValue.color.float32[1] = clear_color.y * clear_color.w;
        wd->ClearValue.color.float32[2] = clear_color.z * clear_color.w;
        wd->ClearValue.color.float32[3] = clear_color.w;
```

Code in `imgui_impl_vulkan.cpp`:
```
// Vulkan data
struct ImGui_ImplVulkan_Data
{
    ImGui_ImplVulkan_InitInfo   VulkanInitInfo;
    VkRenderPass                RenderPass;
    VkDeviceSize                BufferMemoryAlignment;
    VkPipelineCreateFlags       PipelineCreateFlags;
    VkDescriptorSetLayout       DescriptorSetLayout;
    VkPipelineLayout            PipelineLayout;
    VkPipeline                  Pipeline;
    uint32_t                    Subpass;
    VkShaderModule              ShaderModuleVert;
    VkShaderModule              ShaderModuleFrag;

    // Font data
    VkSampler                   FontSampler;
    VkDeviceMemory              FontMemory;
    VkImage                     FontImage;
    VkImageView                 FontView;
    VkDescriptorSet             FontDescriptorSet;
    VkDeviceMemory              UploadBufferMemory;
    VkBuffer                    UploadBuffer;

    // Render buffers for main window
    ImGui_ImplVulkanH_WindowRenderBuffers MainWindowRenderBuffers;

    ImGui_ImplVulkan_Data()
    {
        memset(this, 0, sizeof(*this));
        BufferMemoryAlignment = 256;
    }
};
```
```
struct ImGui_ImplVulkanH_FrameRenderBuffers
{
    VkDeviceMemory      VertexBufferMemory;
    VkDeviceMemory      IndexBufferMemory;
    VkDeviceSize        VertexBufferSize;
    VkDeviceSize        IndexBufferSize;
    VkBuffer            VertexBuffer;
    VkBuffer            IndexBuffer;
};
```
```
static void ImGui_ImplVulkan_SetupRenderState(ImDrawData* draw_data, VkPipeline pipeline, VkCommandBuffer command_buffer, ImGui_ImplVulkanH_FrameRenderBuffers* rb, int fb_width, int fb_height)
{
 ...
// Bind Vertex And Index Buffer:
    if (draw_data->TotalVtxCount > 0)
    {
        VkBuffer vertex_buffers[1] = { rb->VertexBuffer };
        VkDeviceSize vertex_offset[1] = { 0 };
        vkCmdBindVertexBuffers(command_buffer, 0, 1, vertex_buffers, vertex_offset);
        vkCmdBindIndexBuffer(command_buffer, rb->IndexBuffer, 0, sizeof(ImDrawIdx) == 2 ? VK_INDEX_TYPE_UINT16 : VK_INDEX_TYPE_UINT32);
    }
 ...
}
```
```
// Render function
void ImGui_ImplVulkan_RenderDrawData(ImDrawData* draw_data, VkCommandBuffer command_buffer, VkPipeline pipeline)
{
...
if (draw_data->TotalVtxCount > 0)
    {
        // Create or resize the vertex/index buffers
        size_t vertex_size = draw_data->TotalVtxCount * sizeof(ImDrawVert);
        size_t index_size = draw_data->TotalIdxCount * sizeof(ImDrawIdx);
        if (rb->VertexBuffer == VK_NULL_HANDLE || rb->VertexBufferSize < vertex_size)
            CreateOrResizeBuffer(rb->VertexBuffer, rb->VertexBufferMemory, rb->VertexBufferSize, vertex_size, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT);
        if (rb->IndexBuffer == VK_NULL_HANDLE || rb->IndexBufferSize < index_size)
            CreateOrResizeBuffer(rb->IndexBuffer, rb->IndexBufferMemory, rb->IndexBufferSize, index_size, VK_BUFFER_USAGE_INDEX_BUFFER_BIT);
...
}
```

**Comment by PathogenDavid** [comment]
So for the sake of clarity: Dear ImGui is not meant to be a library which helps you render arbitrary things with Vulkan.

As you noted, learning Vulkan can be really overwhelming. It'd probably be better to get the basics down without Dear ImGui being involved at all.

(Also if you're new to graphics programming in general, I would **strongly** suggest you start with OpenGL or Direct3D 11 instead of Vulkan.)

---------

All that being said, Dear ImGui *can* be used as a basic 2D vector graphics library. You can find some examples in the demo under Examples > Custom Rendering. The actual code for these examples can be found in [`ShowExampleAppCustomRendering` in `imgui_demo.cpp`](https://github.com/ocornut/imgui/blob/0f14933577a1de01d90f8e87622296c466146f21/imgui_demo.cpp#L7396).

But with these APIs you aren't learning how to use Vulkan, you're learning how to use Dear ImGui.

**Comment by 1111mp** [comment]
Okay, I can finally stop worrying about this. Thank you for your prompt reply.

**Comment by PathogenDavid** [comment]
No problem, glad I could help!
