### ISSUE TITLE
SDL backend: Drag&Drop On docking branch, Drag out of current viewport will cause exception

### ISSUE THREAD

**Issue by DickyQi** [ocornut/imgui#5082]
Version/Branch of Dear ImGui:

Version: 18709

Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: SDL/OpenGL3 (Modified the example_sdl_opengl3 example)
Operating System: MacOS

My Issue/Question:
I am getting exception at function ImGui_ImplSDL2_SetWindowPos, file backends/imgui_impl_sdl.cpp, line 807.
Steps:
1. start example_sdl_opengl3
2. open "Dear ImGui Demo"-> "Widgets" -> "Drag and Drop"
3. select "Bobby" button(or any other drag-able button) and drag out of main view port

current pos value is (-2.14748365E+9, -2.14748365E+9)
BTW: if BeginDragDropSource without preview tooltip, then exception will not appear.

**Comment by ocornut** [comment]
Hmm, can you confirm if your copy include this recently commit ? f3373780668fba1f9bd64c208d05c20b781c9a39 (from #5012) 
(We didn't increment version number so it is 18709 before and after this commit, hence my question)

Thank you!

**Comment by ocornut** [comment]
Confirmed, also happens on windows (no assertion but flickering tooltip due to invalid mouse pos).
The fix for #5082 was not enough and/or exacerbated the problem.

**Comment by ocornut** [comment]
> can be reproduced by just dragging the color square of a ColorEdit widget.

In fact, multi-viewports has nothing to do with this problem.
Even in `master` branch: we broke the fact that SDL backend can report mouse position when click inside and drag outside (~mouse capture in Win32 terminology). Clicking any DragFloat() and dragging outside host window should preserve valid mouse position.
