### ISSUE TITLE
io.Fonts->AddFontFromFileTTF causes crashes.

### ISSUE THREAD

**Issue by Kpoop123** [ocornut/imgui#5084]
After updating from 1.79 to 1.87 the AddFontFromFileTTF function causes crashes.

`
ImGui::CreateContext();
`
`
ImGuiIO& io = ImGui::GetIO();
`
`
auto font = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Arial.ttf", 15); //  Causes crashes
`

I've checked the API BREAKING CHANGES but I didn't find an answer there.

**Comment by jokteur** [comment]
Well, it does not crash on my computer.
Can you provide more details ? Is it because abort() is called ? Do you have any debug message ?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. Didn’t post in the right location.
Please make sure you have read the guidelines.

Closing.
