### ISSUE TITLE
Docking not working on Main Platform Window but viewports among them works fine

### ISSUE THREAD

**Issue by Cober22** [ocornut/imgui#5086]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: master/viewport/docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Operating System: Windows 10 x64

**My Issue/Question:**

Im working on implementing docking for my SDL Windows based on OpenGL. The flags docking enable and viewports enable works fine, but i cannot docking anything to the SDL Window, althought, the imgui multi-viewports works fine and dock among them

**Screenshots/Video**

https://user-images.githubusercontent.com/67199037/157235535-b82c74b2-5a55-4b28-94eb-bd26bef4e97a.mp4

**Standalone, minimal, complete and verifiable example:** 

Window:

		_window = SDL_CreateWindow("Cober Engine",					// Window title
				SDL_WINDOWPOS_CENTERED,	// posX on screen
				SDL_WINDOWPOS_CENTERED,	// posY on screen
				_screenWidth,					// width of the window
				_screenHeight,					// height of the window
				SDL_WINDOW_RESIZABLE | SDL_WINDOW_OPENGL);		// flags

	void ImGuiLayer::Begin() 
	{
		// Setup Dear ImGui context
		IMGUI_CHECKVERSION();
		ImGui::CreateContext();
		ImGuiIO& io = ImGui::GetIO(); (void)io;
		io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;

		io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
		io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;

		io.BackendFlags |= ImGuiBackendFlags_HasMouseCursors;
		io.BackendFlags |= ImGuiBackendFlags_HasSetMousePos;
		io.BackendFlags |= ImGuiBackendFlags_HasMouseHoveredViewport;

		ImGui::StyleColorsDark();

		ImGuiStyle& style = ImGui::GetStyle();
		if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) 
                {
			style.WindowRounding = 0.0f;
			style.Colors[ImGuiCol_WindowBg].w = 1.0f;
		}
	}

	void ImGuiLayer::End() {

		ImGuiIO& io = ImGui::GetIO();
		Application& app = Application::Get();
		io.DisplaySize = ImVec2((float)app.GetWindowWidth(), (float)app.GetWindowHeight());
	
		ImGui::Render();
		ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

		if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
		{
			SDL_Window* backup_current_window = SDL_GL_GetCurrentWindow();
			SDL_GLContext backup_current_context = SDL_GL_GetCurrentContext();
			ImGui::UpdatePlatformWindows();
			ImGui::RenderPlatformWindowsDefault();
			SDL_GL_MakeCurrent(backup_current_window, backup_current_context);
		}
	}

```
Thanks!!

**Comment by PathogenDavid** [comment]
This is the expected behavior. Windows do not dock onto the sides of the main viewport by default.

You need to create an explicit dock space for the main viewport. You can do this in the official examples by going to Examples > Dockspace. The code for this example can be found in [`ShowExampleAppDockSpace`](https://github.com/ocornut/imgui/blob/f3373780668fba1f9bd64c208d05c20b781c9a39/imgui_demo.cpp#L7731).

The easiest way to add it in your app is to call `DockSpaceOverViewport` right after calling `ImGui::NewFrame`.
