### ISSUE TITLE
imgui failed to build with "error LNK2001: unresolved external symbol glfwGetClipboardString" with MSVC on windows

### ISSUE THREAD

**Issue by YangYang129** [ocornut/imgui#5087]
imgui failed to build with "error LNK2001: unresolved external symbol glfwGetClipboardString" with MSVC on windows. It can reproduces on version https://github.com/ocornut/imgui/commit/0f14933577a1de01d90f8e87622296c466146f21. Could you please help look at this issue? Thank you very much

**Environment**
Compiler version: VS2019 (16.11.9)
Operating system: Windows server 2019

**Steps to reproduce:**
1. open VS2019 x64 tools command
2. git clone https://github.com/ocornut/imgui F:\imgui
3. cd imgui
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
5. powershell.exe -NoProfile -ExecutionPolicy Bypass "F:\gitP\ocornut\tools\FixProjects.ps1"
6. cd examples
7. set SDL2_DIR=F:\gitP\ocornut\tools\SDL2-2.0.10
8. set VULKAN_SDK=C:\VulkanSDK\1.2.154.1
9. xcopy "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22000.0\um\arm64\OpenGL32.Lib" "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\arm64" /k/r/e/i/s/c/h/f/y
10. Replace x64 to ARM64 in "imgui_examples.sln" "example_win32_directx9.vcxproj“ ”example_win32_directx12.vcxproj“ "example_glfw_opengl3.vcxproj" "example_win32_directx10.vcxproj" "example_win32_directx11.vcxproj" "example_glfw_opengl2.vcxproj" "example_glfw_vulkan.vcxproj" fold
11. msbuild /m /p:Platform=arm64 /p:Configuration=Release imgui_examples.sln /t:Rebuild

**Build.log:**
[imgui_msbuild.log](https://github.com/ocornut/imgui/files/8213475/imgui_msbuild.log)

**Error info:**
"F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj" (Rebuild target) (4) ->
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetClipboardString [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetInputMode [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetWindowAttrib [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetTime [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetMonitorCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetFramebufferSize [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetClipboardString [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetCursorEnterCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetWindowSize [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetMouseButtonCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetCursor [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwDestroyCursor [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetKeyCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetScrollCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetInputMode [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwCreateStandardCursor [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetJoystickAxes [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetJoystickButtons [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetCursorPos [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetWin32Window [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetCursorPosCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetKeyName [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwGetCursorPos [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetWindowFocusCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetErrorCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         imgui_impl_glfw.obj : error LNK2001: unresolved external symbol glfwSetCharCallback [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwSwapBuffers [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwSwapInterval [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwTerminate [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwPollEvents [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwInit [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwCreateWindow [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwWindowHint [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwMakeContextCurrent [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwDestroyWindow [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         main.obj : error LNK2001: unresolved external symbol glfwWindowShouldClose [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]
         F:\imgui\examples\example_glfw_opengl3\Release\example_glfw_opengl3.exe : fatal error LNK1120: 36 unresolved externals [F:\imgui\examples\example_glfw_opengl3\example_glfw_opengl3.vcxproj]

**Comment by ocornut** [comment]
You need to provide and link with glfw3 library for your target architecture (ARM64).

We provide binaries for an old version of glfw3 in our example folder as a convenience to help building examples easily, but the glfw3 binaries are not provided for ARM64 and generally you should use your own glfw3  library.

It is unnecessary to set SDL_DIR since here you are compiling an example using GFLW, not using SDL.

(This is not a Dear ImGui issue.)

**Comment by Zhaojun-Liu** [comment]
I used a patch to cross build ImGui, host is amd64 machine, and target is arm64, and it build pass. 
Steps: (with VS2022)
1. git clone https://github.com/ocornut/imgui C:\gitP\ocornut\imgui
2. cd /d C:\gitP\ocornut\imgui & git apply imgui_ARM64_vcxproj.patch
3. (enter the vcpkg folder) vcpkg.exe install --recurse glfw3 sdl2 vulkan --triplet arm64-windows --clean-after-build
4. cd /d C:\gitP\ocornut\imgui\examples
5. devenv /upgrade imgui_examples.sln
6. echo ^<Project^>^<Import Project="C:\gitP\Microsoft\vcpkg\scripts\buildsystems\msbuild\vcpkg.props" /^>^</Project^> > Directory.Build.props
7. echo ^<Project^>^<Import Project="C:\gitP\Microsoft\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets" /^>^</Project^> > Directory.Build.targets
8. set SDL2_DIR=C:\gitP\Microsoft\vcpkg\installed\arm64-windows
9. msbuild /m /p:Platform=arm64 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.22621.0 imgui_examples.sln /t:Rebuild

Patch file:
[imgui_ARM64_vcxproj.patch](https://github.com/user-attachments/files/16467706/imgui_ARM64_vcxproj.patch)

**Comment by KovidKhanna** [comment]
Hello can someone guide me with the same issue but I have manually installed all the files and linked them

**Comment by KovidKhanna** [comment]
Actually I am having an error with the imgui_impl_glfw.obj. Here

1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetClipboardString
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetInputMode
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetWindowAttrib
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetTime
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetKey
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetMonitorCallback
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetFramebufferSize
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetClipboardString
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetCursorEnterCallback
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetWindowSize
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetMouseButtonCallback
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetCursor
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwDestroyCursor
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetKeyCallback
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetScrollCallback
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetInputMode
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwCreateStandardCursor
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetError
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetCursorPos
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetWin32Window
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetGamepadState
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetCursorPosCallback
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetKeyName
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwGetCursorPos
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetWindowFocusCallback
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetErrorCallback
1>imgui_impl_glfw.obj : error LNK2001: unresolved external symbol _glfwSetCharCallback
1>C:\Users\darkv\OneDrive\Desktop\graphics\Graphics\Release\Graphics.exe : fatal error LNK1120: 27 unresolved externals
1>Done building project "Graphics.vcxproj" -- FAILED.

Actually I am a student and wanted to use it in my project

**Comment by ocornut** [comment]
You need to link with the GLFW library, it's generally called glfw3.lib or glfw3dll.lib for the version using a DLL.

**Comment by KovidKhanna** [comment]
![image](https://github.com/user-attachments/assets/f92cd002-fd2a-41d4-8262-f8d370400628)

**Comment by KovidKhanna** [comment]
fixed

**Comment by ocornut** [comment]
Good to hear!
Maybe a good idea to share details on your problem here so other people might learn from it.
