### ISSUE TITLE
Tooltip for disabled items (IsItemHovered and BeginDisabled/EndDisabled)

### ISSUE THREAD

**Issue by neclepsio** [ocornut/imgui#5088]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: custom, based on glfw and opengl3
Compiler: Go
Operating System: Windows

**My Issue/Question:**

`IsItemHovered` always returns false if item is disabled, so I cannot build a tooltip for disabled items. If this is by design, is there a way to workaround it?

Thank you

**Comment by ocornut** [comment]
There is a flag for IsItemHovered() to return true on disabled item. See ImGuiHoveredFlags list.

**Comment by ocornut** [comment]
The flag is

`ImGuiHoveredFlags_AllowWhenDisabled // Return true even if the item is disabled`   

Closing as answered.
