### ISSUE TITLE
Getting Current Label Pressed/Hovered.

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#509]
Hello,

Last major question, It doesn't seem clear how to find out if a Label or Item is pressed. Basically, I put a hash on all UI/Elements or Items but need to get if something is pressed.

I looked for GetLabel but not finding something similiar.

Vivienne

**Comment by ocornut** [comment]
It's not really clear what you are trying to do. Most items return "true" when triggered so at the time of calling the widget you can tell if it is triggered (= pressed for a button).

You can use IsItemActive() to tell is the last item is being used or held. A button is being "active/held" as long as you hold the mouse button, and Button() will only return true when you release the mouse button.

It's not possible to retrieve any labels from anywhere, the labels are never stored anywhere.

**Comment by vivienneanthony** [comment]
Hmm.

**Comment by adam4813** [comment]
I could see where getting the current label under the cursor would be
useful for showing contextual tooltip explaining what an option is or does.

**Comment by ocornut** [comment]
If you are going to do that you can use IsItemHovered() and record that.

Alternatively you can use GetId(label) and compare the value to GImGui->ActiveId exposed by including imgui_internal.h but this is unsupported and may break.

**Comment by vivienneanthony** [comment]
I wanted to assign it label with a hash. Then in the main editor code do something like ImGui::GetHeld, GetPressed, or whatever. I probably can make the some global variable that my code sets when it creates the ImGui interface passing the held, pressed, or whatever.

**Comment by ocornut** [comment]
That's quite contrary to the design of the library. The entire point of ImGui is to process things on the go to avoid carrying information and state around.
But you can record and carry the right amount of data you need yourself as you call the widgets.

**Comment by vivienneanthony** [comment]
I might be able to send a event on Urho3D event code when generating the ImGui Interface. So, I might not have to modify ImGui at all. I'm not sure but its my today WIP  to get the two to play friendly.

**Comment by vivienneanthony** [comment]
This is what I'm working on https://www.youtube.com/watch?v=g92xG8ZMMA0

**Comment by ocornut** [comment]
Closing this.
