### ISSUE TITLE
Any simple way to draw only a subsection of the string?

### ISSUE THREAD

**Issue by quetzalsly** [ocornut/imgui#5091]
I am trying to achieve an effect where the text is displayed character by character with various speeds.
Just using Text() with single characters and incrementing each frame works but the window is resized with this. I need to have the window think its a full string but only render some of it.

I really hope there is an easy solution to this without having to rewrite some parts of imgui code that loops over glyphs. If only there was an , int len) in the Text function.

I thought about making the string the same size but replacing each char with a space but that would assume that each char is same width?

Any ideas?
Thanks

**Comment by ocornut** [comment]
To display the partial text you can use:

ImVec2 p = GetCursorPos();
TextUnformatted(s_begin, s_end);
or
Text(“%.*s”, (int)(s_end - s_begin), s_begin);

And then:

SetCursorPos(p);
Dummy(CalcTextSize(s_begin));
