### ISSUE TITLE
Retrieve selected text region in text input programatically.

### ISSUE THREAD

**Issue by dtp555-1212** [ocornut/imgui#5093]
Hello,

I have searched the web and reviewed the demo program but I can’t seem to find a function that returns the selected region of text in a text input box. I can see that the demo program indeed can select a region and even copy/paste the selected region with a text input, but I don’t see how to retrieve that selected region of text within the program itself. Can you help me with that?

Thanks

Version 1.76
linux
gnuc 9

master
Note: I tried to paste the config ... It would work back into an input box in the program but not in any other window on the remote desktop.

**Comment by jokteur** [comment]
I would suggest using a callback along with the `ImGuiInputTextFlags_CallbackAlways` flag.
Example:
```C++

int mycallbackfct(ImGuiInputTextCallbackData* data) {
    if (data->HasSelection()) {
        std::cout << data->SelectionStart << " " << data->SelectionEnd << std::endl;
    }
    return 0;
}
ImGui::InputText("myTextinput", str, length, ImGuiInputTextFlags_CallbackAlways, mycallbackfct);
```
