### ISSUE TITLE
problem loading fonts

### ISSUE THREAD

**Issue by LarissaLycoris** [ocornut/imgui#5094]
MediaTek and Huawei mobile phones use this code to get fonts and the screen will be black ->GetGlyphRangesChineseFull()
Replace ->GetGlyphRangesChineseSimplifiedCommon() The black screen will be solved, but some Chinese will not be displayed, and the display will be: "?". How to solve this problem? thanks

**Comment by ocornut** [comment]
docs/FONTS.md document mention strategies to reduce font atlas size, eg reduce oversampling.

**Comment by LarissaLycoris** [comment]
> docs/FONTS.md 文档提到了减少字体图集大小的策略，例如减少过采样。

Ok thanks, I'll take a look at the documentation, thanks, I can close the question

**Comment by ocornut** [comment]
FYI, work on `dynamic_fonts` branch aimed to be merged in 1.92 (#8465) solves this, as specifying Glyph Ranges is now unnecessary and glyphs are rasterized on demand as needed.
