### ISSUE TITLE
Docking is not working

### ISSUE THREAD

**Issue by Serkan4152** [ocornut/imgui#5101]
Version: v1.87
Branch: docking

Operating System: windows 10

Back-ends: imgui_impl_sdl2.cpp + imgui_impl_dx11.cpp

docking is not working

![d](https://user-images.githubusercontent.com/84353627/158031240-c8f34cc3-fdff-493e-b344-65889e97873e.png)

```

	IMGUI_CHECKVERSION();
	ImGui::CreateContext();
	ImGuiIO& io = ImGui::GetIO(); (void)io;
	io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
	ImGui_ImplSDL2_InitForD3D(window);
	ImGui_ImplDX11_Init(this->_device, this->_context);

//update
	ImGui::DockSpaceOverViewport(ImGui::GetMainViewport(), ImGuiDockNodeFlags_PassthruCentralNode);

```

**Comment by ocornut** [comment]
It probably is seeing this is the code we use everywhere, so your repro is not a correct repro and is omitting something.

**Comment by Serkan4152** [comment]
but the real problem is that it used to work

**Comment by ocornut** [comment]
Well there's something else you are not showing us that is causing your problem. Clearly the `ImGuiConfigFlags_DockingEnable` flag ends up not being set, somewhere in your code. We can't magically debug your code, even less so if we don't see it.
