### ISSUE TITLE
How to set the focus and not immediately lose it in the next frame

### ISSUE THREAD

**Issue by AlphaNERD-** [ocornut/imgui#5105]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.85 WIP (18417)
Branch: (couldn't determine the branch)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp
Operating System: Playstation Vita 3.60 (henkaku)

**My Issue/Question:**

I'm working on Space Cadet Pinball for the PS Vita. When a round ends, i want the user to put in their name and then display the highscore. I want to focus the InputText in the highscore window so that once i'm done entering the text, i can send the text to InputText using the SDL_TEXTINPUT event. When i set the focus through my code and the keyboard appears, the focus doesn't stay on InputText. Sending the text through SDL_TEXTINPUT to the InputText also doesn't work in that case. However if i tap the InputText and the keyboard appears, the focus remains on the InputText. I can then send the text through SDL_TEXTINPUT to the InputText and it arrives in InputText.

How can i fix this issue?

The code file in question is available here:
https://github.com/AlphaNERD-/SpaceCadetPinball_Vita/blob/Quality-of-Life/SpaceCadetPinball/high_score.cpp

**Comment by ocornut** [comment]
Hello,

We cannot usually debug your code without a minimum repro. 
You shouldn't use SetActiveID/SetFocusID directly as your code seems to do.
To focus an `InputText()` widget you can use `SetKeyboardFocusHere()` as shown in various places of imgui_demo.

If focus is taken away it usually means something else has taken it.

**Comment by AlphaNERD-** [comment]
Okay, `SetKeyboardFocusHere()` solved my problem. I had another problem with the contents not being replaced by the new contents but `ImGuiInputTextFlags_AutoSelectAll` fixed that also.
