### ISSUE TITLE
Prevent scrolling when Item is hovered

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#5108]
**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui.net
Operating System: win10

**My Issue/Question:**

I want to implement an edit interaction that increments/decrements numeric values when the mouse wheel is used while hovering these values. The basic concept is easy enough to implemented, but I didn't find a nice solution to combine it with scrolling: I want to prevent scrolling ONLY if an numeric field is hovered. Is something like this possible?

One work around would be a global "number value hovered" flag that is used to prevent scrolling. But this might cause frame delay issues.

**Screenshots/Video**

https://user-images.githubusercontent.com/1732545/158083843-e052571e-939f-4821-b40e-8d6b2783d6af.mp4

**Comment by pixtur** [comment]
Update: I couldn't detect any side effects of the hover-flag method. So this solution is good enough for me.

**Comment by ocornut** [comment]
You can be using `SetItemUsingMouseWheel()` however you want, see #2891, #4303, #4207
Note we are redesigning this currently, in the future this will be generalized and you'll be able to use e.g. `SetItemInputOwner(ImGuiKey_MouseWheelY);` or `SetInputOwner(ImGuiKey_MouseWheelY, id)`.

**Comment by pixtur** [comment]
Awesome thank you!

**Comment by ocornut** [comment]
Update: I have now pushed a more generic system for input ownership, and as I result obsoleted `SetItemUsingMouseWheel()`. There is still a redirection function but I expect to delete it sooner than the typical 2-3 years obsolescence schedule.

You can now use:
```cpp
SetItemKeyOwner(ImGuiKey_MouseWheelY);
```
Note that `SetItemUsingMouseWheel()` used to lock both wheel axises.
If you need both you can call the function with `ImGuiKey_MouseWheelX` and `ImGuiKey_MouseWheelY`.

Also note that using SetKeyOwner() and SetItemKeyOwner() flags allow for variety of other behaviors outside the scope of this thread.

(cross posted to #2704, #2891, #5108)
