### ISSUE TITLE
Error LNK2001

### ISSUE THREAD

**Issue by tazetheKing** [ocornut/imgui#5111]
how to fix this: Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: void __thiscall ImDrawList::AddText(class ImFont const *,float,struct ImVec2 const &,unsigned int,char const *,char const *,float,struct ImVec4 const *)" (?AddText@ImDrawList@@QAEXPBVImFont@@MABUImVec2@@IPBD2MPBUImVec4@@@Z)	CSGO Solution	C:\Users\razez\Desktop\idk\CSGO Solution\imgui.obj	1	

![image](https://user-images.githubusercontent.com/95387001/158242295-e2a02f0a-0ac8-42d6-ab08-d929d74c7355.png)

**Comment by ocornut** [comment]
Sorry but #1586
