### ISSUE TITLE
Passing mouse events through transparent child windows

### ISSUE THREAD

**Issue by Guistac** [ocornut/imgui#5113]
Hello,

I'm developing a little sequencer library using dear ImGui.
I've run into a situation in which I'd like to give the user some space to draw their own widgets on top of my library's widgets.
To do this I'm starting a child window in which the user submits their widgets.
The problem that I'm encountering is that I'd still like to read mouse events below the users child window, as if it were transparent.

<img width="546" alt="Screenshot 2022-03-15 at 18 32 49" src="https://user-images.githubusercontent.com/42607186/158437898-0e6660fc-7475-460a-9198-a2f5f1c42218.png">

Here I'd like the user to draw their widgets to the right of each track header, but I'd still like to know if the header was hovered or clicked between the users buttons.
Currently the child window takes ownership of the mouse cursor unless I pass `ImGuiWindowFlags_NoInputs` which doesn't solve my problem.

The user code roughly looks like this: 
```
if(Sequencer::beginTrack("TrackName")){
	ImVec2 userSpaceSize = Sequencer::getUserSpaceSize();
	//do custom user drawing here
	Sequencer::endTrack();
}
```

Here is a distilled idea of how I'm trying to approach the problem in the library code:
`BackgroundInteractionCatcher` does not get hovered or clicked if the mouse is inside the `UserSpaceChildWindow`.
What I'm imagining is some sort is something like `ImGuiWindowFlags_AllowMousePassthrough`

```
ImGui::SetNextWindowSize(ImVec2(512, 512));
ImGui::Begin("ExampleWindow");

ImGui::SetCursorPos(ImVec2(16,128));
ImGui::Button("BackgroundInteractionCatcher", ImVec2(480, 256));

if(ImGui::IsItemHovered()) std::cout << "background is hovered" << std::endl;
else std::cout << "background not hovered" << std::endl;

ImGui::SetCursorPos(ImVec2(128, 64));
ImGui::BeginChild("UserSpaceChildWindow", ImVec2(256, 384), true);

for(int i = 0; i < 4; i++){
	ImGui::PushID(i);
	ImGui::Button("User Submitted Button", ImVec2(200, 30));
	ImGui::PopID();
}

ImGui::EndChild();

ImGui::End();
```
<img width="538" alt="Screenshot 2022-03-15 at 18 23 05" src="https://user-images.githubusercontent.com/42607186/158437071-492c7248-59d2-4262-b7fe-87adc5405d15.png">

I managed to get the result I wanted by setting `ImGui::SetItemAllowOverlap()` before each user submitted widget.
But it does not work inside a child window, which has the advantage of greatly simplifying the layout of user submitted widgets.
I don't want the user to have to call `ImGui::SetCursorPos()` and `ImGui::SetItemAllowOverlap()` before each of their widgets.

I might also be approaching this In a completely inefficient way, any tips are greatly appreciated !

Branch: Docking (Latest)
Back-ends: GLFW + OpenGL
Compiler: Xcode
Operating System: MacOs

**Comment by ocornut** [comment]
> which has the advantage of greatly simplifying the layout of user submitted widgets.

Quick answer (haven’t dug into this yet). Why are you creating a child window in the first place? What layout thing is simplified? Couldn’t the user/plugin submit their button in the same window then you wouldn’t have this problem?

Why is your purpose for catching inputs “behind” ? Can’t you can’t the same inputs from within the child window itself, with eg IsWindowHovered() && !IsAnyItemHovered()?

**Comment by Guistac** [comment]
The idea of the child window was to have a closed off space for user submitted widgets.
But you're right, it isn't necessarily the best solution, event though I got it somehow working using `IsAnyItemHovered()`
I got rid of the child window idea, since it complicated things.

The main issue I then encountered was the following:

If two items are overlapping, it's not possible to know if the one below is really hovered before submitting the overlapping one.
This is from imgui.cpp about setItemAllowOverlap():
`Allow last item to be overlapped by a subsequent item. Both may be activated during the same frame before the later one takes priority.`
This is easily fixed by just comparing the overlapping item with the previous hovered id `g.HoveredIdPreviousFrame` since it contains the last really hovered item of the previous frame.

My main concern is now that `setItemAllowOverlap()` has to be called before any overlapping widget.
Is there any way to push and pop this state?

![Untitled](https://user-images.githubusercontent.com/42607186/158560121-a9c7c603-524e-4345-a307-594dfcedcb7d.gif)

**Comment by ocornut** [comment]
Not currently. The “allow overlap “ system is currently quite a mess (part of the behavior is also guided by a ButtonFlags un ButtonBehavior). Not currently on my PC but there is thread that explain the current state of it fairly thoroughly and its not good enough to be promoted to an item flags (but eventually it should i agree).

**Comment by Guistac** [comment]
Interesting, I'll look into that !
For now this works well enough, with the repeated setItemAllowOverlap() just being a minor inconvenience.
Also I ended up getting almost the same effect as a child window by just using a clipping rectangle and setting the cursor position before any user submitted widgets.
I'm quite amazed at the flexibility of imgui when it comes to making completely new interfaces like this.
Thanks a lot for your help !

**Comment by ocornut** [comment]
We’ll introduce a PushWorkRect() api which will do a similar thing eventually.

**Comment by Guistac** [comment]
Do you mean as a sort of in-between of `BeginGroup()` & `BeginChild()` ?

**Comment by ocornut** [comment]
Yes. 
BeginGroup() is a ill defined mess but has purpose to group certain states, and is often used for its x-cursor locking feature which is technically a different feature it has.

BeginWorkRect() would be a more complete feature in term of layout/clipping.
