### ISSUE TITLE
SaveIniSettingsToDisk(g.IO.IniFilename) freezes the entire application for a while when dragging any imgui frame for a long time.

### ISSUE THREAD

**Issue by ezorzin** [ocornut/imgui#5117]
Version: 1.87
Branch: master, commit: 6fae29679a8f9b163f6ef11bd643c4aa859cc31b

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: VS2022
Operating System: Windows 10

Hi, 

recently I added myself to the discussion of the [issue 5095](https://github.com/ocornut/imgui/issues/5095).
I was initially happy because I believed I solved my problem, but after a more careful test I found the original problem was still there.
Now I opened this new issue because I believe I found more specific and reproducible problem.

The problem is: if I drag any imgui frame and making it moving (slow or fast, does not matter) CONTINUOUSLY without interrupting the motion of the mouse (e.g. I drag it in a slow circular trajectory inside the window), after a while (e.g. 15-20 seconds) everything freezes for a short time (e.g. 1-2 seconds). When this happens, if I continue dragging the frame the problem manifest itself again, with the same periodicity. During the "frozen" period everything hangs within the application.

I found the problem arises in the imgui.cpp file:
```
void ImGui::UpdateSettings()
{
    // Load settings on first frame (if not explicitly loaded manually before)
    ImGuiContext& g = *GImGui;
    if (!g.SettingsLoaded)
    {
        IM_ASSERT(g.SettingsWindows.empty());
        if (g.IO.IniFilename)
            LoadIniSettingsFromDisk(g.IO.IniFilename);
        g.SettingsLoaded = true;
    }

    // Save settings (with a delay after the last modification, so we don't spam disk too much)
    if (g.SettingsDirtyTimer > 0.0f)
    {
        g.SettingsDirtyTimer -= g.IO.DeltaTime;
        if (g.SettingsDirtyTimer <= 0.0f)
        {
            if (g.IO.IniFilename != NULL)
                SaveIniSettingsToDisk(g.IO.IniFilename);  // <------------------ PROBLEM -----------------
            else
                g.IO.WantSaveIniSettings = true;  // Let user know they can call SaveIniSettingsToMemory(). user will need to clear io.WantSaveIniSettings themselves.
            g.SettingsDirtyTimer = 0.0f;
        }
    }
}
```

By modifying the code this way:
```
...
if (g.IO.IniFilename != NULL)
                {}//SaveIniSettingsToDisk(g.IO.IniFilename);  // <---- ELIMINATED INSTRUCTION (notice the curly brackets) --------------
            else
                g.IO.WantSaveIniSettings = true;  // Let user know they can call SaveIniSettingsToMemory(). user will need to clear 
...
```

the problem is solved!

My guess is that by continuously dragging the imgui frame, the harddisk gets too busy in saving the location of it (to my understanding, for later usage when running the application again after having closed it) and this freezes the entire application for a while.

Is it possible to disable this "SaveIniSettingsToDisk" by some imgui function? Conversely, is there a better way to handle this situation?

Thanks

Best regards,

Erik

**Comment by ocornut** [comment]
It is very abnormal that this would freeze.

Can you check the size and contents of your .ini file for any abnormal thing?

Try to break in the debugger during the freeze to find out exactly what is stalling.

**Comment by ezorzin** [comment]
The file looks like this (1K):
```
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][SIMULATION CONTROL:]
Pos=60,60
Size=416,608
Collapsed=0

[Window][FALSE VACUUM PARAMETERS:]
Pos=766,318
Size=607,307
Collapsed=0

```

Now I am trying to analyze this issue in deeper detail, as you suggested.

**Comment by ocornut** [comment]
Under Windows I would throw in some guesses: it is a mapped network drive or abnormally slow drive or file system, you may have third-party programs, drivers, malicious software interfering etc. But I find it mostly surprising that you say you have the same problem on both Windows and Linux. If that is actually the case, I have no explanation to provide, and certainely it isn’t a problem for Dear ImGui to solve. Opening and Writing to files is a thing that happens many times every second in all major oses. 

To answer your question: yes you can disable saving to disk. If you read the line of code right above the one you commented out you’ll find how.

**Comment by ezorzin** [comment]
On both Windows and Linux I have the app (it's the same app, I can compile it on both systems) running from an external USB thumb drive, I was trying to do something that could work for some embedded system too (not necessarily a usual desktop PC).

Anyway, you are right! if I copy the app to the internal harddisk of my PC then it works without interruptions!

But I have two questions:
1. I did not completely understand what you suggest me to do in order to disable the creation of the imgui.ini file.
2. don't you think it could be better to save the instantaneous locations of the imgui frames in some sort of internal array in imgui, and save them on a file eventually when in one those functions: `ImGui_ImplOpenGL3_Shutdown();`, `ImGui_ImplGlfw_Shutdown();`, `ImGui::DestroyContext();` only before terminating the application? I don't see a clear advantage of having that information continuously written on the disk at high pace: only the last positions are needed to restore the imgui frame where they were located, for a subsequent run of the application. As far as I understand, now every single mouse motion event triggers the function that writes on that log file.

**Comment by ezorzin** [comment]
..."I did not completely understand what you suggest me to do in order to disable the creation of the imgui.ini file." -----> ok, I found how to do it, simply by setting:
`io.IniFilename        = NULL;`

However, the second question is still open. Maybe it could be a new feature?

**Comment by PathogenDavid** [comment]
> As far as I understand, now every single mouse motion event triggers the function that writes on that log file.

This is incorrect. It's rate limited to once every 5 seconds. (By default, you can change `ImGuiIO::IniSavingRate` to change the rate.)

> save them on a file eventually [...] only before terminating the application?

Dear ImGui is frequently used for development tools. Development tools crash a lot or are forcibly stopped by an attached debugger. It's nice to have your window layouts remembered in these scenarios.

I don't think it's an intended feature, but I think you can actually get this behavior by setting `ImGuiIO::IniSavingRate` to infinity.

----------

All that being said, I wonder if performance would be better in this scenario if we kept the settings file open and truncated and rewrote it in `LogToFile` instead reopening it every time. (Unfortunately I don't think there's a cross-platform way to truncate files that are already open.)

**Comment by ocornut** [comment]
What David said.

> All that being said, I wonder if performance would be better

OP is the first person in many years to mention this as an issue so I think it's more of a problem with their setup (thumb drive, and even so I don't think I noticed something similar with mine tbh).

> but you can actually get this behavior by setting ImGuiIO::IniSavingRate to infinity.

That's supported and it makes sense if you want to save on quit only. You can also set IniFilename to NULL and manually save yourself before shutting down the context.


I'll close this as answered but I suspect either your thumb drive is surprisingly low quality either there's external software interfering.
