### ISSUE TITLE
Incorrect text clipping

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#512]
![imgui_clip_error](https://cloud.githubusercontent.com/assets/153526/12628298/bc5f7494-c542-11e5-9234-ab23827dfa83.png)

With ~~ImGui::PushItemWidth and~~ FramePadding > 0, text is not correctly clipped in ImGui::InputText

It seems to be caused by [this](https://github.com/ocornut/imgui/blob/master/imgui.cpp#L7578):

```
    const ImVec4 clip_rect(frame_bb.Min.x, frame_bb.Min.y, frame_bb.Min.x + size.x + style.FramePadding.x*2.0f, frame_bb.Min.y + size.y + style.FramePadding.y*2.0f);

```

With FramePadding == 0, everything looks ok

**Comment by itamago** [comment]
Yeah, I have the same issue with ImGuiListClipper and InputText.
And it is flickering when dragging the scrollbar.
Without ImGuiListClipper, everything is clipped correctly (but more expensive in terms of CPU)

**Comment by ocornut** [comment]
I think your issue is completely different here. Nem0 is referring to the input box contents not being clipped within the frame properly, because i'm miscalculating the aabb for cpu-side clipping of the vertices.

**Comment by itamago** [comment]
ok, sorry

**Comment by ocornut** [comment]
Fixed. I think the issue started appearing along with my cleanups of last week, e.g.
https://github.com/ocornut/imgui/commit/570a9dadc4bfeeba4cf36fc9fda1b120ebe78d0d
