### ISSUE TITLE
Gefroce Experience record program

### ISSUE THREAD

**Issue by eXtreames** [ocornut/imgui#5121]
I use imgui, a edition with win32, tried both opengl32 + win32 and directx9 + win32. The problem is that Geforce Experience/ShadowPlay is recording my program, and I don't need it (instant replay). How to solve it? Code exactly according to the template from /examples and from here https://github.com/ocornut/imgui/issues/2022.

**Comment by ocornut** [comment]
I don’t understand your question, you haven’t filled the requested issue template, and this seems unrelated to dear imgui.
