### ISSUE TITLE
[Metal] Cannot create weak reference in file using manual reference counting

### ISSUE THREAD

**Issue by whale02** [ocornut/imgui#5122]
Using Macbook pro M1 

Tested in Version: [6fae296](https://github.com/ocornut/imgui/commit/6fae29679a8f9b163f6ef11bd643c4aa859cc31b)

compile error: https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_metal.mm#L586 

```
error: cannot create weak reference in file using manual reference counting
    weak id weakSelf = self;
```

This error is generated using minimal metal example (glfw).

**Comment by ocornut** [comment]
Merged #5123
