### ISSUE TITLE
Change Button Text color on hovering

### ISSUE THREAD

**Issue by arjunair86** [ocornut/imgui#5126]
**Version/Branch of Dear ImGui:**

Version: 1.88 WIP (18709)
Branch: _docking_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: macOS

Hi
Is it possible to change text color of a button on hovering? I see that there is a flag for ButtonHovered, ButtonActive, but these can be used to only push style color for the button itself, and not the text inside it.

**Comment by ocornut** [comment]
At the moment it isn't possible via the public API, no. 
(Other than writing your own Button() function based on ButtonBehavior, which is pretty simple).

**Comment by rihok** [comment]
Is this something that is being considered being added to the public API? I'd say it's one of the more significant things missing from the styling aspect of ImGui. It quite severely limits what you can do in terms of styling. For example, it's pretty common to flip the colors of a button on hover (text becomes bg color, bg becomes text color).

**Comment by ocornut** [comment]
Yes Styling v2 will include it.

**Comment by ocornut** [comment]
It is not possible at the moment, no (unless rewriting a custom button widget).

**Comment by Bourdon94m** [comment]
_This can maybe help you :_ 

**The definitions** :
```
void ButtonHoveredChangeColor(
    const char* text,
    const ImVec2& size,
    const ImVec4& hoveredTextColor,
    ImFont* font,
    const std::function<void()>& onClick // Callback
)
{
    ImVec2 min = ImGui::GetCursorScreenPos();
    ImVec2 max = ImVec2(min.x + size.x, min.y + size.y);

    bool hovered = ImGui::IsMouseHoveringRect(min, max);

    if (hovered)
        ImGui::PushStyleColor(ImGuiCol_Text, hoveredTextColor);
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0,0,0,0));
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0,0,0,0));

    if (font)
        ImGui::PushFont(font);

    if (ImGui::Button(text, size))
    {
        onClick(); 
    }

    if (font)
        ImGui::PopFont();

    if (hovered)
        ImGui::PopStyleColor();
        ImGui::PopStyleColor();
        ImGui::PopStyleColor();
}
```

**How we call the function in my example** 

```
ButtonHoveredChangeColor(ICON_FA_TRASH, ImVec2(30.0f, 30.0f), ImVec4(1, 0, 0, 1), nerdFont,
    []()
    {
        ImWidget::ScannerTab::processAttachedName = "";
        ImWidget::ScannerTab::isProcessAttached = false;
    });

```

https://github.com/user-attachments/assets/1172b2cb-6ef2-41a0-bb25-4a3b3b992966

**Comment by GamingMinds-DanielC** [comment]
> ```
>     if (hovered)
>         ImGui::PushStyleColor(ImGuiCol_Text, hoveredTextColor);
>         ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0,0,0,0));
>         ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0,0,0,0));
> 
>     // ...
> 
>     if (hovered)
>         ImGui::PopStyleColor();
>         ImGui::PopStyleColor();
>         ImGui::PopStyleColor();
> ```

C++ compilers don't care for indentation, so the second and third Push/Pop in your code are unconditional. Your indentation suggests that you wanted them to be conditional. Btw. `PopStyleColor()` has an optional parameter to pop multiple values at once.
