### ISSUE TITLE
Dockspace host window cancels inputs when a window with no mouse input is docked on it.

### ISSUE THREAD

**Issue by mriquier** [ocornut/imgui#5130]
**Version/Branch of Dear ImGui:**

Version: 1.80
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp
Operating System: Windows

**My Issue/Question:**

Hello I have an issue using the dockspace system while trying to render my game inside an Imgui window. Here's what I'm trying to do:
1/ I have a main ImGui window that takes all viewport size, with no mouse inputs, no focus and no background. I attach a dockspace to it, this window only purpose is to host this dockspace, on which I will dock my other windows on. The dockspace has the ImGuiDockNodeFlags_PassthruCentralNode flag.
2/ I have several debug windows I can dock and move around in this dockspace.
3/ I setup my game to render in a bitmap, that I then display in an ImGui window using ImGui::Image(...). Let's call that window the Game window. I force it to be docked to the central node of my dockspace, that way it will always take the maximum space available (main window size - size of other windows that are docked).
The game window needs to let the inputs pass through to let my game back-end get input focus instead of Imgui. In order to do that, I set the ImGuiWindowFlags_NoMouseInputs flag in the Begin(...) call. 

The issue: My game doesn't get the inputs, because the test ImGui::IsWindowHovered(ImGuiFocusedFlags_AnyWindow) returns true.
By debugging I found that in FindHoveredWindow(), my window is skipped as expected, however the function instead sets the window that is created by the Dockspace() function as hovered.

If I add the ImGuiWindowFlags_NoMouseInputs to the Dockspace() host window it works, but then I can't move around my other debug windows as they don't get mouse input too which is not what I want.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/102165269/159515746-e11d5547-4080-40c4-9814-6d78bb87f8f0.png)
![image](https://user-images.githubusercontent.com/102165269/159519912-983851be-fd0f-4825-9b85-2f6036149b1b.png)

**Standalone, minimal, complete and verifiable example:** 
I can't really write a complete example as my game is very complex and uses several viewports and a custom input handling, but I can write a small example that should reproduce the host window being hovered issue.
```
//Init main window
ImGuiWindowFlags window_flags = ImGuiWindowFlags_NoDocking;
ImGuiViewport* viewport = ImGui::GetMainViewport();
ImVec2 dockingWindowPos = viewport->Pos;
ImVec2 dockingWindowSize = viewport->Size;

ImGui::SetNextWindowPos(dockingWindowPos);
ImGui::SetNextWindowSize(dockingWindowSize);
ImGui::SetNextWindowViewport(viewport->ID);
ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
window_flags |= ImGuiWindowFlags_NoTitleBar
| ImGuiWindowFlags_NoCollapse
| ImGuiWindowFlags_NoResize
| ImGuiWindowFlags_NoMove
| ImGuiWindowFlags_NoBringToFrontOnFocus
| ImGuiWindowFlags_NoNavFocus;
| ImGuiWindowFlags_NoMouseInputs
| ImGuiWindowFlags_NoBackground;

ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
static bool bShowDockSpace = true;
ImGui::Begin("Dockspace", &bShowDockSpace, window_flags);
ImGui::PopStyleVar();

ImGui::PopStyleVar(2); // PopStyles WindowRounding and WindowBorderSize.

// Init DockSpace
ImGuiID dockspace_id = ImGui::GetID("DevModeDockSpace");
ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), ImGuiDockNodeFlags_PassthruCentralNode);
ImGui::End();

m_pCentralDockNode = ImGui::DockBuilderGetCentralNode(dockspace_id);
if (m_pCentralDockNode)
{
  while (m_pCentralDockNode->ParentNode != nullptr)
  {
	  m_pCentralDockNode = m_pCentralDockNode->ParentNode;
  }
}

ImGui::DockBuilderDockWindow("Game", m_pCentralDockNode->ID); //Force our window to be docked on central node

//Game window
static bool isOpen = true;
ImGui::SetNextWindowBgAlpha(1.f);
auto window_flags = ImGuiWindowFlags_NoResize
| ImGuiWindowFlags_NoMove
| ImGuiWindowFlags_NoCollapse
| ImGuiWindowFlags_NoScrollbar
| ImGuiWindowFlags_NoScrollWithMouse
| ImGuiWindowFlags_NoMouseInputs;

if (ImGui::Begin("GameWindow", &isOpen, window_flags))
{
  //Whatever drawing 
}
ImGui::End();
```

Thanks in advance for your time and help.

**Comment by ocornut** [comment]
My intuition is:
- Don't set any NoInputs flags anywhere. Let Dear ImGui get all inputs.
- Make your game simply receive inputs based on another criteria than just using `io.WantCaptureMouse` etc. e.g. so you can decide that when your Game window is hovered OR focused then the game engine will receive inputs (and needs to reproject them according to the position of that window).

Sounds simpler and more flexible?

**Comment by mriquier** [comment]
Thanks for your quick answer. I would have expected a way to make a window "pass through" even when docked but yeah I guess I will try your suggestion instead. 

Have a good day

**Comment by ocornut** [comment]
You can make the central node passthrough with the corresponding flag, and then not dock any window in there and use that space to render your game view.

You can also set the function to override WantCaptureMouse etc from your UI code to not have to interact with your lower-level code.

**Comment by mriquier** [comment]
Yes that's what I was actually trying, will see if I can make it work, but I like your first suggestion too.
