### ISSUE TITLE
imgui + sokol + emscripten + GLES2, keyboard problems

### ISSUE THREAD

**Issue by voidware** [ocornut/imgui#5133]
Hi,

I'm using imgui+sokol under emscripten, GLES2. I've got the latest imgui master and sokol. Both of these appear to have been updated for the new keycode handling. Indeed everything works fine on desktop browser.

But (as usual), i have problems with android browser. Using Firefox on android (updated).

I cannot get `InputText` to work properly. Normal keys like letters and numbers work. Backspace does not work and nor does enter/return. In fact, i am unable to get _anything_ to enter.

A while back i had it all working, but had to update because, annoyingly the virtual keyboard kept overlaying the input line. That, at least, appears to work now as the browser area resizes for the virtual keys.

I've been poring over the code today, but i can't find out what it is.

importantly - this may not be an imgui problem at all!!

Has anyone got any ideas or seen this problem. I tried a different mobile virtual keyboard but no difference.

thanks,

**Comment by voidware** [comment]
Just to add the imgui demo cannot be operated. For some (unknown) reason, clicking anywhere on the panel causes it to move, but none of the widgets can be opened.

**Comment by ocornut** [comment]
Well you should debug it by printing inputs events from backend.

>  Normal keys like letters and numbers work. Backspace does not work and nor does enter/return. I

Letters and numbers used by InputText are not KEYS they are CHARACTERS. It is a different concept.
This suggest you get characters but not keys.
I guess the virtual keyboard you are using would need to be emitting Keys as well as Characters.
