### ISSUE TITLE
Regression: assertion when creating a context if another is current

### ISSUE THREAD

**Issue by cfillion** [ocornut/imgui#5135]
Creating more than one context (without clearing the current one in between) asserts since commit 28ba54a32ae604f57430ee311dc5b1d1aeeaa4ca. `AddSettingsHandler` uses the last active context (which already has the handlers installed) rather than the new one `Initialize` is preparing.

```cpp
ImGui::CreateContext();
//ImGui::SetCurrentContext(nullptr); // workaround
ImGui::CreateContext(); // IM_ASSERT(FindSettingsHandler(handler->TypeName) == NULL);
```

**Comment by ocornut** [comment]
Thank you. Pushed a fix now and added a basic regression test for it.
