### ISSUE TITLE
Tree view of directory

### ISSUE THREAD

**Issue by ZaWarudo111** [ocornut/imgui#5137]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Compiler: Visual Studio 2019
Operating System: Windows 10

**My Issue/Question:**

How could i make a tree view of specific directory (image below)?  I can read files with `std::filesystem`
, but i have no idea how could i do the sorting logic. 

I don't want to read the files every frame, so i want to store them in a vector. Also the count of files and folders can change. 

I came up with an idea, that i could put the files in `std::vector` as `std::pair` (first item is file name, second tells is it folder or file), for example:
```cpp
std::vector<std::pair<std::string, bool>> files = { { "SomeFolder", true }, //folder
{ "SomeFolder/notes.txt", false }, //file
{ "SomeFolder/files", true }, //folder
{ "SomeFolder/files/main.cpp", false }, //file
{ "SomeFolder/files/header.h", false } }; //file
```

but i still have no idea how could i "sort" the strings into a tree view. So any help would be appreciated!

I know this is not directly related into imgui, but imgui's tree view system is unique, and i think i can't find help from anywhere else.

**Screenshots/Video**

![treeview_of_directory](https://user-images.githubusercontent.com/79928133/159864859-81c673bf-acd7-40e0-8205-e760254f5129.png)

**Comment by ZaWarudo111** [comment]
Tried 100 things, still no luck 😕

**Comment by samyuu** [comment]
The simplest way to model a tree is usually using a list of connected nodes which you can then traverse using recursion.
To build a simple directory tree you could for example:
```cpp
struct DirectoryNode
{
	std::string FullPath;
	std::string FileName;
	std::vector<DirectoryNode> Children;
	bool IsDirectory;
};

void RecursivelyAddDirectoryNodes(DirectoryNode& parentNode, std::filesystem::directory_iterator directoryIterator)
{
	for (const std::filesystem::directory_entry& entry : directoryIterator)
	{
		DirectoryNode& childNode = parentNode.Children.emplace_back();
		childNode.FullPath = entry.path().u8string();
		childNode.FileName = entry.path().filename().u8string();
		if (childNode.IsDirectory = entry.is_directory(); childNode.IsDirectory)
			RecursivelyAddDirectoryNodes(childNode, std::filesystem::directory_iterator(entry));
	}

	auto moveDirectoriesToFront = [](const DirectoryNode& a, const DirectoryNode& b) { return (a.IsDirectory > b.IsDirectory); };
	std::sort(parentNode.Children.begin(), parentNode.Children.end(), moveDirectoriesToFront);
}

DirectoryNode CreateDirectryNodeTreeFromPath(const std::filesystem::path& rootPath)
{
	DirectoryNode rootNode;
	rootNode.FullPath = rootPath.u8string();
	rootNode.FileName = rootPath.filename().u8string();
	if (rootNode.IsDirectory = std::filesystem::is_directory(rootPath); rootNode.IsDirectory)
		RecursivelyAddDirectoryNodes(rootNode, std::filesystem::directory_iterator(rootPath));

	return rootNode;
}
```
And to then display it using Dear ImGui:
```cpp
void RecursivelyDisplayDirectoryNode(const DirectoryNode& parentNode)
{
	ImGui::PushID(&parentNode);
	if (parentNode.IsDirectory)
	{
		if (ImGui::TreeNodeEx(parentNode.FileName.c_str(), ImGuiTreeNodeFlags_SpanFullWidth))
		{
			for (const DirectoryNode& childNode : parentNode.Children)
				RecursivelyDisplayDirectoryNode(childNode);
			ImGui::TreePop();
		}
	}
	else
	{
		if (ImGui::TreeNodeEx(parentNode.FileName.c_str(), ImGuiTreeNodeFlags_NoTreePushOnOpen | ImGuiTreeNodeFlags_Leaf | ImGuiTreeNodeFlags_SpanFullWidth))
		{
			// ... handle file click interaction
		}
	}
	ImGui::PopID();
}

static DirectoryNode rootNode = CreateDirectryNodeTreeFromPath(L"C:/SomeFolder");

void SomeUpdateFunction()
{
	if (ImGui::Begin("Example Directory Tree Window", nullptr, ImGuiWindowFlags_NoSavedSettings))
		RecursivelyDisplayDirectoryNode(rootNode);
	ImGui::End();
}
```

There are several problems with a naive approach like this. For one, `std::filesystem` loves throwing exceptions left and right so you'd either wanna try+catch all filesystem calls or use a more sane API entirely.

Creating the entire directory tree up front may work perfectly fine for small folders but will fall apart quickly when for example trying to iterate over an entire drive.

An easy solution is to only populate the node children when the corresponding `ImGui::TreeNode`  is expanded for the first time (and even better if also done on a separate thread entirely).
 
You may also want to further sort your nodes in some deterministic order (see `StrCmpLogicalW` for example on windows).

At large scales manual clipping may also become necessary (see `ImGuiListClipper`, although definitely a lot more tricky with variable sized nodes).

**Comment by ZaWarudo111** [comment]
Thanks!
