### ISSUE TITLE
[Request]How can I add Tabs/Tables like this

### ISSUE THREAD

**Issue by az-sam-retard** [ocornut/imgui#5138]
This menu was made with IMGUI, I would like to know how could I create tabs like these (Chat,Misc,Resources,Settings) tabs , anyone could please help me?

Thanks

https://i.imgur.com/bVXb9XO.png
![tabs](https://user-images.githubusercontent.com/77434830/159929130-deb4a6f7-a999-41a2-b261-9991bccbc8c9.png)

**Comment by ocornut** [comment]
Sorry but #1586
