### ISSUE TITLE
Assertion failure with ONE SliderFloat (other ones work fine) in Debug-Mode (also works in Release-Mode)

### ISSUE THREAD

**Issue by mulder146t** [ocornut/imgui#5147]
```
Dear ImGui 1.86 WIP (18519)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1600.00,1000.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

I am getting an assertion failure when I click on one particular SliderFloat. The problem arises in `imgui_widgets.cpp` line 631 and 632:

`            const int mouse_button = g.ActiveIdMouseButton;
            IM_ASSERT(mouse_button >= 0 && mouse_button < ImGuiMouseButton_COUNT);
`
The value for `mouse_button` is -1. This problem only occurs with this ONE SliderFloat and not others and only in Debug-Mode, not Release-Mode. When I comment out the line `IM_ASSERT` and simply add 1 in the next line `if (g.IO.MouseDown[mouse_button + 1])` to avoid an array-element -1 being called, the slider works perfectly. Unfortunatly I can't really give you a minimal and verifiable example, because the code is massive. The error occurs here in my code:

```
        ImGui::SliderFloat("Playback speed", &PlaybackSpeed, 0.1, 10.0, "%.1f", ImGuiSliderFlags_Logarithmic);
        if (Playback)
        {
            if (getFrame(NumFrame, &Pos))
                NumFrame += PlaybackSpeed;
            else if (repeat)
                NumFrame = 0;
            else
                Playback = false;
        }
        if (ImGui::SliderFloat("Pos", &NumFrame, 0, RecordData.size(), "%.1f")) // This slider causes the isssue
            getFrame(NumFrame, &Pos);

```

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
Sorry, that is basically impossible...

```

**Comment by ocornut** [comment]
> Unfortunatly I can't really give you a minimal and verifiable example, because the code is massive

The whole point of this is that trying to isolate the issue you are likely to find the cause. Not doing so you are asking us to work for you.

I would guess you may have an ID collision with this slider, but maybe it is something else. In the absence of more details we can’t spend so much energy on this.
