### ISSUE TITLE
InputText password with spaces

### ISSUE THREAD

**Issue by iangodin** [ocornut/imgui#515]
When I set  the password flag for InputText, spaces still show up as spaces (i.e. they are not *).
Most password don't have spaces, but I think a star should still be shown.
Using the sdl_opengl3_example, on OS X (in case it's system specific?).
If I figure out the cause and/or a fix, I'll pass it along.
But I just started playing with ImGui, so it might take me a while.

![screenshot](https://cloud.githubusercontent.com/assets/2567207/12697780/5cbc5dc2-c740-11e5-8b9f-06ccc8b0fae2.png)

**Comment by ocornut** [comment]
The font renderer doesn't render Space (assume empty glyph) as an optimization. I would suggest instead to just add an extra default filter to disable inputting spaces and have it used in the password exemple.

**Comment by ocornut** [comment]
I applied the workaround which I think is acceptable here (normal passwords never have blanks, only passphrase may have them, and we have yet to see if someone really intend to use imgui for that) and has no performance penalty on rendering.

**Comment by ocornut** [comment]
This is now fixed in master!

![image](https://user-images.githubusercontent.com/8225057/74266812-37872380-4d05-11ea-99ce-419413647505.png)
