### ISSUE TITLE
Line broken issue when using D3D11_FILTER_MIN_MAG_MIP_POINT filter in the sampler

### ISSUE THREAD

**Issue by zaafar** [ocornut/imgui#5156]
**Version/Branch of Dear ImGui:**

Version: 1.88 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp
Operating System: windows 10
Graphic Card: RTX 2080 (Nvidia)

**My Issue/Question:**
Hi, I am from the .net C# world and I have already figured out how to solve this issue. All details can be found here: https://github.com/mellinoe/ImGui.NET/issues/261 (sorry for making you visit another url to understand the issue).

The reason I am opening this issue over here is to make sure that this is the intended behaviour and/or not in the scope of this library. If that's the case then sorry for wasting your time and feel free to close the issue.

**Screenshots/Video/Steps to reproduce**
Following is the patch you can apply to this repository to re-produce the issue. After applying this patch, please run `example_win32_directx11` example.

```diff --git a/backends/imgui_impl_dx11.cpp b/backends/imgui_impl_dx11.cpp
index a7407d66..2e5c70e5 100644
--- a/backends/imgui_impl_dx11.cpp
+++ b/backends/imgui_impl_dx11.cpp
@@ -352,7 +352,7 @@ static void ImGui_ImplDX11_CreateFontsTexture()
     {
         D3D11_SAMPLER_DESC desc;
         ZeroMemory(&desc, sizeof(desc));
-        desc.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
+        desc.Filter = D3D11_FILTER_MIN_MAG_MIP_POINT;
         desc.AddressU = D3D11_TEXTURE_ADDRESS_WRAP;
         desc.AddressV = D3D11_TEXTURE_ADDRESS_WRAP;
         desc.AddressW = D3D11_TEXTURE_ADDRESS_WRAP;
diff --git a/examples/example_win32_directx11/main.cpp b/examples/example_win32_directx11/main.cpp
index 8dc486a4..b163fcdf 100644
--- a/examples/example_win32_directx11/main.cpp
+++ b/examples/example_win32_directx11/main.cpp
@@ -107,7 +107,13 @@ int main(int, char**)
         {
             static float f = 0.0f;
             static int counter = 0;
-
+            float x = 0.0f;
+            float y = 619.500f;
+            float w = 351.0f;
+            float h = 248.0f;
+            ImVec2 p = ImVec2(x, y);
+            ImVec2 q = ImVec2(x + w, y + h);
+            ImGui::GetBackgroundDrawList()->AddRect(p, q, 0xFFFFFFFF);
             ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.

             ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)

```

==when using D3D11_FILTER_MIN_MAG_MIP_LINEAR==
![before](https://user-images.githubusercontent.com/5079646/161122044-e5f66b03-2e95-48e7-91c5-65c5add1b4fc.png)

==when using D3D11_FILTER_MIN_MAG_MIP_POINT==
![after](https://user-images.githubusercontent.com/5079646/161122068-2a3b63c3-0509-4df2-bc03-79a0a29cb8a9.png)

**Comment by ocornut** [comment]
Our texture-based path for anti-aliasing (#3245) indeed do requires linear sampling.

Before building the atlas:
```
io.Fonts->Flags |= ImFontAtlasFlags_NoBakedLines;
```
Would lift that constraint.

I am now going to add extra comments to clarify that requirement.

Thank you.

**Comment by zaafar** [comment]
nice! it's amazing to see those comments. thank you for the amazing lib and amazing support. :)
