### ISSUE TITLE
How to center text to a image

### ISSUE THREAD

**Issue by SplatTab** [ocornut/imgui#5159]
I want to center a text to the middle of a image how would I go about doing that? I also need to center the image according to the text

For reference here's what I have and as you can see everything is off centered
![Capture](https://user-images.githubusercontent.com/81938880/161358268-7a581e0c-1e54-4a19-b986-9a7c338ded51.PNG)

**Comment by Alex-vZyl** [comment]
@SplatTab If you solved this, maybe just show how you did it for when other people come looking for the same thing.

**Comment by SplatTab** [comment]
> @SplatTab If you solved this, maybe just show how you did it for when other people come looking for the same thing.

I was able to get a decent design using the Tables API with ImGui::TableHeadersRow()
![Capture](https://user-images.githubusercontent.com/81938880/161608819-6d48ac81-ce28-48bb-bf9d-d8ec5514d53c.PNG)

**Comment by Alex-vZyl** [comment]
If you know how wide the column is you can use a combination of `ImGui::SetCursorPosX()` and `ImGui::CalcTextSize()` to achieve your goal.
