### ISSUE TITLE
Is there a way to get the ImGui Window handle just like using FindWindow?

### ISSUE THREAD

**Issue by Juesril** [ocornut/imgui#5160]
I would like to get the ImGui Window Handle just to Set the display affinity of a specific ImGui Window

**Comment by Alex-vZyl** [comment]
Is this what you want?

https://github.com/ocornut/imgui/blob/377b864bb4a9ed9a25674b04f64f63baf221060d/imgui_internal.h#L2720-L2721

**Comment by Juesril** [comment]
> Is this what you want?
> 
> https://github.com/ocornut/imgui/blob/377b864bb4a9ed9a25674b04f64f63baf221060d/imgui_internal.h#L2720-L2721

Kind of, but I need to get HWND to set the display affinity, SetWindowDisplayAffinity which need specific HWND

**Comment by ocornut** [comment]
The HWND is not known nor used by core Dear ImGui that’s known by your application.

**Comment by Juesril** [comment]
Its not my application its an API SetWindowDisplayAffinity  is an API

**Comment by Alex-vZyl** [comment]
Yes, ocornut is saying that imgui does not use/is responsible for HWND.  That belongs to the window library you are using I believe.

**Comment by Juesril** [comment]
Oh Okay thanks for the reply anyway <3

**Comment by Alex-vZyl** [comment]
If you are using GLFW.

https://stackoverflow.com/questions/64348676/how-to-get-hwnd-with-glfwwindow-pointer
