### ISSUE TITLE
Calculate text size of wide string

### ISSUE THREAD

**Issue by lexika979** [ocornut/imgui#5164]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: features/shadows

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: MSVC
Operating System: Windows (11)
Using freetype for font rasterization

**My Issue/Question:**

Hello,
I'm trying to calculate the text size of a wide string.
I know about the ImFont::CalcTextSizeA function, but there does not seem to be a function for wide strings.
Is there a function that provides said functionality?

Thanks in advance!

**Comment by PathogenDavid** [comment]
`CalcTextSizeA` accepts UTF8, you should pass UTF8 to it directly. (The `A` is a historical artifact and slightly misleading. It isn't ASCII-only.)

As an aside, depending on your needs `ImGui::CalcTextSize` might be more suitable.

**Comment by lexika979** [comment]
> `CalcTextSizeA` accepts UTF8, you should pass UTF8 to it directly. (The `A` is a historical artifact and slightly misleading. It isn't ASCII-only.)
> 
> As an aside, depending on your needs `ImGui::CalcTextSize` might be more suitable.

I'm trying to render UTF16

**Comment by PathogenDavid** [comment]
Dear ImGui is a UTF8-focused library. There are a handful of functions which take wider characters but they're only rare exceptions.
