### ISSUE TITLE
Disable imgui.ini

### ISSUE THREAD

**Issue by kyamant** [ocornut/imgui#5169]
Version: v1.86 WIP
Branch: master

Visual Studio 2019

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: Visual C++
Operating System: Windows 10

I am not able to **disable** **imgui.ini**.
I have tried 

```
auto imGuiIO{ ImGui::GetIO() };
imGuiIO.IniFilename = NULL;
imGuiIO.LogFilename = NULL;
```
Using `nullptr` or `""` instead of `NULL` above did not change anything

**Comment by ocornut** [comment]
> auto imGuiIO{ ImGui::GetIO() };

You are making A COPY of the IO structure and modifying it.
Use a reference.
