### ISSUE TITLE
Selectable capturing click and not forwarding to other widgets

### ISSUE THREAD

**Issue by itamago** [ocornut/imgui#517]
Hello,

I have a question regarding 'Selectable' : I use it to select a full line in a table (please see the capture below).

<img width="1303" alt="screen shot 2016-02-02 at 17 51 35" src="https://cloud.githubusercontent.com/assets/16628136/12756841/d42134ea-c9d5-11e5-9f98-05ee3bd46c35.png">

As Selectable capture the mouse-click, all the other widgets don't react anymore to the mouse clic ; I cannot enable/disable checkboxes, I cannot expand combo, etc.

Does someone know a simple way to make Selectable forward the mouse-click event instead of capturing it ?

Thanks for your help

**Comment by ocornut** [comment]
So this a little tricky. 
Do you want to have the line selected when a checkbox/combo is used?
Are you using selectable just as a visual aid or a permanent selection?

- So, here you are using a Selectable that spans all the line coverage.
If you call SetItemAllowOverlap() after Selectable() other items will be usable. However in this context Selectable() will react to mouse-release, so if another widget is active (e.g. clicked on the checkbox) it'll steal activity from the Selectable and as a result Selectable won't return true.
If you want the line selection to happens you can set the selection yourself when the other widgets are activated. You'd need to include imgui_internal.h to use SetItemAllowOverlap() but I've been considering moving it to imgui.h

- Another possibility is to not use the SpanAllColumns flag of the selectable.

- Another possibility would be to request Selectable() to draw spanning all columns but only handle interaction on the first column (if that is an acceptable behaviour for you). We'd need to expose this option to Selectable in some way. I could invesgigate that for you if you want.

**Comment by itamago** [comment]
Thank you very much !
Calling SetItemAllowOverlap() just after Selectable() provide a behaviour better than the one I expected.
I'm able to select a line and continue to modify another line at the same time. Perfect :)
