### ISSUE TITLE
Multi-Viewports

### ISSUE THREAD

**Issue by noisewuwei** [ocornut/imgui#5175]
Multi-Viewports cannot be work on metal+glfw? It can be work on glfw+opengl.

**Comment by PathogenDavid** [comment]
Correct, [the Metal backend does not support multiple viewports](https://github.com/ocornut/imgui/blob/505f19e3b00d54623566dda354980c7f3410f2b5/backends/imgui_impl_metal.mm#L8).

**Comment by noisewuwei** [comment]
> Correct, [the Metal backend does not support multiple viewports](https://github.com/ocornut/imgui/blob/505f19e3b00d54623566dda354980c7f3410f2b5/backends/imgui_impl_metal.mm#L8).

thanks

**Comment by ocornut** [comment]
Now added support via #4821
