### ISSUE TITLE
Use a list of fallback fonts for each character?

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#5176]
On MacOS, CoreText can give you a list of fallback fonts to try in order when your character isn't available:

https://developer.apple.com/documentation/coretext/1509992-ctfontcopydefaultcascadelistforl?language=objc

Many programs use this list in the following way. When it needs to render a character, it goes through the list of fonts, stops at the first font containing the character, and grabs the glyph. Effectively, this makes it so no character is ever missing, because it will always be covered by some fallback font.

I'd like to do this in ImGui. However, it doesn't seem possible, because right now the API requires you to add fonts ahead of time with predefined ranges. I don't know which fonts contain which ranges. I want to just, for each character, try each font until it finds one that supports the character. Is that possible at all with ImGui?

**Comment by ocornut** [comment]
This is not currently possible indeed.

**Comment by invrainbow** [comment]
> This is not currently possible indeed. (Thanks for the API link, this will be a useful reference, eventually we ought to try honoring that)

Got it, good to know. In that case,

a) Is there a general recommendation for apps that need to support arbitrary Unicode? Maybe by dynamically adding and removing ranges as they're needed?
b) Is there like a "render character" or "create texture" hook for us to write our own character rendering logic?

**Comment by ocornut** [comment]
a) Add as needed and rebuild. For apps with known localization data (and no user input) you can build the range on startup.
b) No. It's not a simple problem. We are working on it.
