### ISSUE TITLE
 InputFlags = ImGuiInputTextFlags_EnterReturnsTrue Windows fail but Linux works InputFloat

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#518]
Hello

I'm trying to implement ImGui::InputFloat but we are getting fails in Visual Basic basically Windows when we try   InputFlags = ImGuiInputTextFlags_EnterReturnsTrue; for the window flag. I have no problem with Linux.

This is a more detailed
http://imgur.com/a/2RfHe

The code is for example

```
ImGuiInputTextFlags inputFlags = 0;
inputFlags |= ImGuiInputTextFlags_EnterReturnsTrue; -
 

// Snap Scale
    ImGui::Text("Snap Scale");
    ImGui::NextColumn();
    if(ImGui::InputFloat("###SnapScale_", &SnapScale, 0.01f, 0.05f, -1, inputFlags))
    {
        if(SnapScale>1.0f)SnapScale=1.0f;
        if(SnapScale<0.0f)SnapScale=0.0f;

        if(ImGui::IsItemHovered()&&GImGui->ActiveIdIsJustActivated)
        {
            SendImGuiEvent[ImGuiViewSettingsEvent::P_IMGUIELEMENT]= String("###SnapScale_");
            SendImGuiEvent[ImGuiViewSettingsEvent::P_IMGUIELEMENTPARM1] = SnapScale;

            thisInterface->SendImGuiEvent(E_IMGUI_VIEWSETTINGS, SendImGuiEvent);
        }
    }
```

Any ideas of the cause?

Vivienne

**Comment by vivienneanthony** [comment]
The source we are using is https://github.com/GarageDoorProductions/Urho3D-Hangars/tree/development/Source/AlphaEngine/ThirdParty/ImGui 

Which was modified just a little to work with Urho3D.

**Comment by ocornut** [comment]
You aren't initializing your flags to 0 so the value is undefined. You should raise your compiler warnings and read them.

**Comment by ocornut** [comment]
PS: 
        `if(ImGui::IsItemHovered()&&GImGui->ActiveIdIsJustActivated)` looks unnecessary. The widget will return true when modified.

**Comment by vivienneanthony** [comment]
I that it was initialized at the same time I defined it. I'll go back and look.

If I click a button -/+ it returns true but if I alter the actual text it doesn't automatically. It seems but I'll again.

**Comment by ocornut** [comment]
In the debugger screenshot it shows that the variable isn't initialized to zero.
Also please don't use links to imgur to post the picture on github, thanks!
