### ISSUE TITLE
opengl3_loader is overlapping with glew in windows 10

### ISSUE THREAD

**Issue by afraidofdark** [ocornut/imgui#5180]
**Version/Branch of Dear ImGui:**

Version: 1.88 WIP
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Compiler: vs community 2019
Operating System: 10

**My Issue/Question:**

I am using glew 2.1.0, visual studio Jumbo(Unity) build with my project.
I decided to upgrade from 1.84 to 1.88, I have noticed that imgui start using its own gl loader.
it is overlapping with my glew files. The reason can be jumbo build, since its putting all the sources into a single file before compile,
the macros can conflict or become defunct in that single file.
Here is the error logs:

2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(446,42): error C3646: 'BindTexture': unknown override specifier
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(446,53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(461,42): error C3646: 'DeleteTextures': unknown override specifier
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(461,56): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(465,42): error C3646: 'DrawElements': unknown override specifier
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(465,54): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(470,42): error C3646: 'GenTextures': unknown override specifier
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(470,53): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(502,1): warning C4005: 'glActiveTexture': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1427): message : see previous definition of 'glActiveTexture'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(503,1): warning C4005: 'glAttachShader': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1910): message : see previous definition of 'glAttachShader'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(504,1): warning C4005: 'glBindBuffer': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1703): message : see previous definition of 'glBindBuffer'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(505,1): warning C4005: 'glBindSampler': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(6177): message : see previous definition of 'glBindSampler'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(507,1): warning C4005: 'glBindVertexArray': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(7785): message : see previous definition of 'glBindVertexArray'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(508,1): warning C4005: 'glBlendEquation': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1572): message : see previous definition of 'glBlendEquation'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(509,1): warning C4005: 'glBlendEquationSeparate': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1912): message : see previous definition of 'glBlendEquationSeparate'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(510,1): warning C4005: 'glBlendFuncSeparate': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1573): message : see previous definition of 'glBlendFuncSeparate'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(511,1): warning C4005: 'glBufferData': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1704): message : see previous definition of 'glBufferData'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(512,1): warning C4005: 'glBufferSubData': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1705): message : see previous definition of 'glBufferSubData'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(515,1): warning C4005: 'glCompileShader': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1913): message : see previous definition of 'glCompileShader'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(516,1): warning C4005: 'glCreateProgram': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1914): message : see previous definition of 'glCreateProgram'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(517,1): warning C4005: 'glCreateShader': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1915): message : see previous definition of 'glCreateShader'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(518,1): warning C4005: 'glDeleteBuffers': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1706): message : see previous definition of 'glDeleteBuffers'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(519,1): warning C4005: 'glDeleteProgram': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1916): message : see previous definition of 'glDeleteProgram'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(520,1): warning C4005: 'glDeleteShader': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1917): message : see previous definition of 'glDeleteShader'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(522,1): warning C4005: 'glDeleteVertexArrays': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(7786): message : see previous definition of 'glDeleteVertexArrays'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(523,1): warning C4005: 'glDetachShader': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1918): message : see previous definition of 'glDetachShader'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(526,1): warning C4005: 'glDrawElementsBaseVertex': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(4602): message : see previous definition of 'glDrawElementsBaseVertex'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(528,1): warning C4005: 'glEnableVertexAttribArray': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1921): message : see previous definition of 'glEnableVertexAttribArray'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(529,1): warning C4005: 'glGenBuffers': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1709): message : see previous definition of 'glGenBuffers'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(531,1): warning C4005: 'glGenVertexArrays': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(7787): message : see previous definition of 'glGenVertexArrays'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(532,1): warning C4005: 'glGetAttribLocation': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1925): message : see previous definition of 'glGetAttribLocation'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(535,1): warning C4005: 'glGetProgramInfoLog': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1926): message : see previous definition of 'glGetProgramInfoLog'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(536,1): warning C4005: 'glGetProgramiv': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1927): message : see previous definition of 'glGetProgramiv'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(537,1): warning C4005: 'glGetShaderInfoLog': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1928): message : see previous definition of 'glGetShaderInfoLog'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(538,1): warning C4005: 'glGetShaderiv': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1930): message : see previous definition of 'glGetShaderiv'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(540,1): warning C4005: 'glGetStringi': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(2237): message : see previous definition of 'glGetStringi'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(541,1): warning C4005: 'glGetUniformLocation': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1931): message : see previous definition of 'glGetUniformLocation'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(543,1): warning C4005: 'glLinkProgram': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1940): message : see previous definition of 'glLinkProgram'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(548,1): warning C4005: 'glShaderSource': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1941): message : see previous definition of 'glShaderSource'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(551,1): warning C4005: 'glUniform1i': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1947): message : see previous definition of 'glUniform1i'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(552,1): warning C4005: 'glUniformMatrix4fv': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1963): message : see previous definition of 'glUniformMatrix4fv'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(553,1): warning C4005: 'glUseProgram': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(1964): message : see previous definition of 'glUseProgram'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(554,1): warning C4005: 'glVertexAttribPointer': macro redefinition
2>C:\Users\MSI\Documents\ToolKit\Dependency\Glew\include\GL\glew.h(2002): message : see previous definition of 'glVertexAttribPointer'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3.cpp(495,17): error C2039: 'BindTexture': is not a member of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(441): message : see declaration of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3.cpp(501,17): error C2039: 'DrawElements': is not a member of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(441): message : see declaration of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3.cpp(513,5): error C2039: 'BindTexture': is not a member of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(441): message : see declaration of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3.cpp(555,5): error C2039: 'GenTextures': is not a member of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(441): message : see declaration of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3.cpp(556,5): error C2039: 'BindTexture': is not a member of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(441): message : see declaration of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3.cpp(568,5): error C2039: 'BindTexture': is not a member of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(441): message : see declaration of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3.cpp(579,9): error C2039: 'DeleteTextures': is not a member of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(441): message : see declaration of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3.cpp(802,5): error C2039: 'BindTexture': is not a member of 'GL3WProcs::<unnamed-type-gl>'
2>C:\Users\MSI\Documents\ToolKit\Editor\ImGui\imgui_impl_opengl3_loader.h(441): message : see declaration of 'GL3WProcs::<unnamed-type-gl>'

**Comment by afraidofdark** [comment]
As I suspected, GL/glew.h was making its way into "imgui_impl_opengl3_loader.h" unintentionally,
There should be preventing mechanisim inside the loader for common gl loaders. This will be encountered frequently. I have solved my problem by removing glew.h from header files. So it can not make its way into imgui gl loader.

**Comment by ocornut** [comment]
> As I suspected, GL/glew.h was making its way into "imgui_impl_opengl3_loader.h" unintentionally,

The later doesn't include the earlier, but if you include both in the same compilation unit they'll clash.
If you `#define IMGUI_IMPL_OPENGL_LOADER_CUSTOM` before including `imgui_impl_opengl3_loader.h` then existing loader symbols will be used so that'll work with your copy GLEW.
