### ISSUE TITLE
InputText / DragInt / ... inside table space wasted between columns

### ISSUE THREAD

**Issue by tksuoran** [ocornut/imgui#5188]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: docking

**My Issue/Question:**

Is there a way to make InputText / DragInt etc. without visible label and no space wasted between columns?
I am asking because I would like to put lots of these inside a table. Even when using empty labels (`"##..."`) there is empty space between columns. In Screenshot below, DragInt 0 and 99 have empty space between them.

**Screenshot**

![image](https://user-images.githubusercontent.com/994606/162984947-f3d215e2-ef88-46b6-b96b-e671cef9d8a0.png)

**Comment by ocornut** [comment]
Hello,

That has nothing to do with the label but with the width of framed items, which default to about 2/3 of the parent width. You can use PushItemWidth(-FLT_MIN) or SetNextItemWidth(-FLT_MIN) to right-align framed items.

**Comment by ocornut** [comment]
The Tables Demo has a section demonstrating this:

![777D30E7-B46B-416F-8C97-4CA3595B32BC](https://user-images.githubusercontent.com/8225057/163050085-6daeba33-10ec-4a9a-ac22-675e15696928.jpeg)
