### ISSUE TITLE
Horizontal scrollbar clipping problems

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#519]
Hi.

I've rarely used horizontal scroll bars so far.
However I've tried using a horizontal scroll bar together with a "column layout", and I've discovered that last column text gets clipped like in the image:
![columnsandhorscrollbaclipping](https://cloud.githubusercontent.com/assets/9608982/12820336/e2c82316-cb5e-11e5-974b-fd60e9323d8e.gif)

I'm not sure if it's my fault or not. Do you have some advice about it ?

**Comment by ocornut** [comment]
I'll look into it. Columns are still full of issues. eConsider setting an explicit content width.

**Comment by Flix01** [comment]
OK, but it might be something in my code: it's an old piece of code where I explicitly used ImGui::SetColumnOffset(...) (every frame or so)... maybe that did not take ImGui::GetScrollX() into consideration (horizontal scroll bars did not exist when I wrote that code...).

**Comment by Eoghanenigma** [comment]
I've just run into this issue myself. 
I have a few columns, the left hand columns are small and so i used SetColumnOffset to restrict their width.
The final column contains a longer string so I'd like it to be flexibly sized. 

Just as the gif shows above, the columns will track with the scroll bar correctly, but the clipping on the final column shrinks until the last column is completely cutoff.

**Comment by sonoro1234** [comment]
Happens for example in Example app Log: Last line is partially covered by horizontal scrollbar

**Comment by ocornut** [comment]
@sonoro1234 The bug you are referring to is unrelated to this thread, I think it is #665 which I have just fixed.

**Comment by ocornut** [comment]
This should be fixed now. @Flix01 
Not that `Columns` will FIT within the given space they have and therefore if you want an horizontally scrollable columns set you likely need to set a content width explicitly. See `SetNextWindowContentWidth`.

```
if (ImGui::TreeNode("Horizontal Scrolling"))
{
    ImGui::SetNextWindowContentWidth(1500);
    ImGui::BeginChild("##scrollingregion", ImVec2(0, 120), false, ImGuiWindowFlags_HorizontalScrollbar);
    ImGui::Columns(10);
    for (int i = 0; i < 20; i++)
        for (int j = 0; j < 10; j++)
        {
            ImGui::Text("Line %d Column %d...", i, j);
            ImGui::NextColumn();
        }
    ImGui::Columns(1);
    ImGui::EndChild();
    ImGui::TreePop();
}
```

![image](https://user-images.githubusercontent.com/8225057/29495298-06f225c4-85ef-11e7-8aa6-ff59a8437e45.png)

Let me know if it all works for you. Additionally I just applied a bunch of Columns related changes, so interested in hearing feedback if anything broken/improved.

**Comment by Flix01** [comment]
> Let me know if it all works for you. Additionally I just applied a bunch of Columns related changes, so interested in hearing feedback if anything broken/improved.

Seems to work, and I'm not seeing anything broken so far... :+1:
