### ISSUE TITLE
Is it possible to update font for each frame?

### ISSUE THREAD

**Issue by yiminli** [ocornut/imgui#5193]
**Version/Branch of Dear ImGui:**

Version: 1.88 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp imgui_impl_sdl.cpp
Operating System: Linux

**My Issue/Question:**
Adding a Chinese font consumes a lot of time. It is even slower when multiple sizes are required.
Instead, I want to call AddFontFromFileTTF for all characters inputted by the user in frame rendering loop.
To simplify the code, I use AddFontDefault instead. The basic idea is to call
```
        io.Fonts->Clear();
        io.Fonts->AddFontDefault();
```
for each frame. I saw this assert:
```
    IM_ASSERT(g.IO.Fonts->IsBuilt()                                     && "Font Atlas not built! Make sure you called ImGui_ImplXXXX_NewFrame() function for renderer backend, which should call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()");
```
but
```
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplSDL2_NewFrame();
```
is called already.
Did I miss anything?

**Standalone, minimal, complete and verifiable example:**
Modify example_sdl_opengl3/main.cpp as below:
```
 #include <SDL_opengl.h>
 #endif

+int UpdateFonts()
+{
+       static ImGuiIO &io = ImGui::GetIO();
+       io.Fonts->Clear();
+       io.Fonts->AddFontDefault();
+
+    return 0;
+}
+
 // Main code
 int main(int, char**)
 {
@@ -114,6 +123,11 @@ int main(int, char**)
                 done = true;
         }

+        if (0)
+            static auto tmp = UpdateFonts();        // works if only called once
+        else
+            UpdateFonts();                          // does not work
+
         // Start the Dear ImGui frame
         ImGui_ImplOpenGL3_NewFrame();
         ImGui_ImplSDL2_NewFrame();
```

**Comment by ocornut** [comment]
1. One restriction is atlas needs to be build before ImGui::NewFrame(). That, you got right.
2. Texture needs to be reuploaded to the backend. In your case you'll need to call `ImGui_ImplOpenGL3_DestroyFontsTexture()` followed by `ImGui_ImplOpenGL3_CreateFontsTexture();`. We are going to standardize that accross backends and make it automatic with #3761. I'm sort of hoping we can finish this for <1.89 and it will enable new features.
