### ISSUE TITLE
SDL_Renderer + OpenGL drawn graphic background covered up by empty/black Imgui

### ISSUE THREAD

**Issue by Fredrum** [ocornut/imgui#5197]
**Version/Branch of Dear ImGui:**

Version: [fa2b318](https://github.com/ocornut/imgui/tree/fa2b318dd6190852a6fe7ebc952b6551e93899e0)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: SDL + OpenGl3
Compiler: gcc version 10.2.1 20210110 (Debian 10.2.1-6)
Operating System: RaspberryOS Bullseye 
Linux raspberrypi 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

**My Issue/Question:**

I'm trying to draw a textured window backdrop underneath my Imgui gui using regular GL polygons+shaders but Imgui draws over with black even if I'm not emitting any Imgui windows or other widgets to be drawn. 
Iv'e got some in the code but I have now commented out all the Imgui widget emits and I still gets a black screen.

In my gui loop on each frame I now do,
```
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplSDL2_NewFrame();
ImGui::NewFrame();
```
then invoking my graphics refresh like this,
```
glViewport(glViewGeom[0], glViewGeom[1], glViewGeom[2], glViewGeom[3]);

if(guiActive)
		ImGui::Render();
	
glClearColor(0,0,0,0);
glClear(GL_COLOR_BUFFER_BIT);
	
glBindTexture(GL_TEXTURE_2D, bg_texture);
glUseProgram(bg_program);
glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

if(guiActive)
	ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

SDL_RenderPresent(sdl_renderer);
```
The above results in a black screen.
But If I comment out/remove the RenderDrawData part then I see what I expect, the image drawn by GL with the shader on polys. Like this,
```
glViewport(glViewGeom[0], glViewGeom[1], glViewGeom[2], glViewGeom[3]);

if(guiActive)
		ImGui::Render();
	
glClearColor(0,0,0,0);
glClear(GL_COLOR_BUFFER_BIT);
	
glBindTexture(GL_TEXTURE_2D, bg_texture);
glUseProgram(bg_program);
glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);


SDL_RenderPresent(sdl_renderer);
```

It looks as if Imgui composits a black/empty screen using a white alpha and thereby covering up my previous gl draw. But that's just my guess.

Any idea why its behaving like this and if there's a way around it?

Cheers!

**Comment by ocornut** [comment]
Seems like SDL_Renderer carries and expect a bunch of GL global state and it doesn't play very well with other GL uses.
There are probably answers buried in one of the thread discussing mixing SDL_Renderer with raw GL code, before we introduced the SDL_Renderer backend:
  https://github.com/ocornut/imgui/issues?q=SDL_Renderer

If you find it would be good. Basically you can comment chunks of `ImGui_ImplOpenGL3_RenderDrawData()` to find what's interfering with the state expected by `SDL_RenderPresent()`.

As a workaround, maybe using our `imgui_impl_sdl_renderer` backend (with latest SDL version) can side-step this issue but it would also be good to get to the end of that properly.

**Comment by Fredrum** [comment]
Thank you for the hints and advice!
I'll do what you suggest it's probably going to be a few days but I'll report back here!

**Comment by Fredrum** [comment]
this seems a bit tricky to figure out. I started in ImGui_ImplOpenGL3_RenderDrawData() but ended up having to go to ImGui_ImplOpenGL3_SetupRenderState() and then  ImGui_ImplOpenGL3_GetBackendData(). 
So far not able to find a single fault point.  I first thought maybe it was a blend mode thing but it seems more to do with glScissor'ing. Maybe. Partly at least?

Here's two images I got from two different sets of 'commenting out' in the mention3ed functions. Sorry no clean problem point. 

https://imgur.com/a/EsTN9E1

The bottom image shows the best Iv'e got. I was expecting that wide border to be clear like in that sceen grab. But the center large Imgui window should be partially transparent and tinting the background image seen at the border.

**Comment by ocornut** [comment]
> EDIT: I'll change over to try adding another Imgui window behind and draw with AddImage() on that.
> EDIT2: Yes I got that working already so that'll be my solution for now! :)

Could you clarify if you made change to backend, or what was the exact solution?
May be helpful to others.
