### ISSUE TITLE
Menu click through on Android problematic because of submenu overlays

### ISSUE THREAD

**Issue by mholzel** [ocornut/imgui#5198]
This is sort of a difficult problem to describe. So please ask whatever clarifying questions are necessary. 

The Android implementation works beautifully accept for one small issue that I am not sure how to deal with... 

Consider the Demo showcase, when we try to click through the recursive menu: 

Open Recent -> More.. -> Recurse.. -> Open Recent

![Screenshot from 2022-04-14 15-56-41](https://user-images.githubusercontent.com/7227349/163409513-6effdd1b-d4e1-4045-a602-f80698df8525.png)

This is where the problem arises... 

On the desktop, the hover behavior is used to open the next submenu. That it, we hover over "Open Recent", and a new submenu appears. 

On Android, we have to click to open this submenu. 

Now the appearance of the menus will vary from device to device based on screen size, text size, dpi, etc, but I have observed the same behavior on various emulators and real devices. 

But basically, notice that the submenus are not drawn on top of the one that came before them until we get to this last one shown in the example above. When I click "Recurse.. " a new submenu is drawn overtop of that word in the middle of the screen. This is problematic because if I click "Open Recent " again then I get different behavior depending on where I click on the "Open Recent " line. If I click on the arrow on the right side of the line, then we properly see the next submenu: 

![Screenshot from 2022-04-14 15-58-57](https://user-images.githubusercontent.com/7227349/163409390-59ffc512-19e6-4eb4-b9c1-4cd38e9f0812.png)

However, if you click on the words "Open Recent", then this is precisely where the next menu is drawn, and so before you know it, you have selected "fish_hat.c" and the menu closes. It seems that this is expected because when you click on the "Open Recent" word, the new submenu is opened, and since your finger is on the "fish_hat.c" by the time the next frame rolls around, Imgui thinks that you are clicking on that option. 

Oof. That was a long-winded explanation. Here is an attempt to capture the undesired behavior: 

https://youtu.be/DJpSB9lpLT8

Anyways... the question is quite simple... How should I overcome this? 

- I think the easiest way would be to sort of force the next submenu to be drawn to the side. 
- The other alternative would be to insert some delay in the click behavior. 

I would appreciate some ideas for how to accomplish either of these. I am not aware of which functions I should use to accomplish either of these.

**Comment by ocornut** [comment]
Seems similar/same as #5171 would you mind posting your same message there?

**Comment by feathers-hook5** [comment]
> Seems similar/same as [#5171](https://github.com/ocornut/imgui/issues/5171) would you mind posting your same message there?





https://assertive9.github.io/fnF7kGK4gBFz1hkylPWrfbDhDo2RL1c80G2W7fvkiiqNgXMF/
