### ISSUE TITLE
LoadIniSettingsFromDisk doesn't work fine with dock subwindow (in docking branch)

### ISSUE THREAD

**Issue by hebohang** [ocornut/imgui#5199]
**My environment:**
Windows10
Visual Studio 2019
MSVC
C++17
opengl3 + glfw

**My problem**
When I use the function LoadIniSettingsFromDisk, it seems the [Docking][Data] in imgui.ini file doesn't work fine.

Thank you in advance

**Comment by ocornut** [comment]
It should. If you don't provide a repro and proper details and search related issues we are not going to help.
