### ISSUE TITLE
Docking and keyboard issue on X11

### ISSUE THREAD

**Issue by andreagen0r** [ocornut/imgui#5201]
Hi, I'm getting some issues with the docking branch on Ubuntu X11. 
I just run the example_glfw_opengl3.
The docking area appears to be offset when dragging over.
Sometimes the window cannot be moved before resized
Sometimes delete key does not work on text input 

Version: 1.87
Branch: docking

Back-ends: OpenGL
Compiler: GCC 10.3.0
Operating System: Ubuntu 20.04

[**Video**](https://youtu.be/MxFI8estZpA)

**Comment by ocornut** [comment]
Hello, please post the video in #2117.
I'm closing as duplicate.

> Sometimes delete key does not work on text input

This would be good to clarify.
