### ISSUE TITLE
Dim background on standard popups

### ISSUE THREAD

**Issue by Willy-JL** [ocornut/imgui#5205]
I wanted to ask if it is possible to dim the background of normal popups, or alternatively allow closing modal popups by clicking on the background. I would like to have both the dimming and the ability to close by clicking outside the popup but I haven't been able to find anything through the issues here or in the demo window... no biggie if this is not possible though, this is just an aesthetic request and it doesn't matter much.

**Comment by ocornut** [comment]
Hello,
Its not currently possible. I don’t think we should provide the feature (as eg a flag or style option) because it would lead different apps to have varying behavior which isn’t going to be good for end-user.

**Comment by Willy-JL** [comment]
I see where you're coming from, makes sense. Either way thanks for developing this awesome library!
