### ISSUE TITLE
Listbox is repeating

### ISSUE THREAD

**Issue by MaloCow** [ocornut/imgui#5210]
Hello, i just made a listbox that grab FiveM resources list of a server, so this is my code : 

`static const char* resources[] =`
`{ `
`resource->GetName().c_str()`
`};		`		

`static int selectedResource = 0;`

`ImGui::ListBox("", &selectedResource, resources, IM_ARRAYSIZE(resources));`

When the main resource of FiveM show it's working perfectly, so in my ListBox i have only wrote "cfx_internal"
but when all server resources is showing, the ListBox is repeating everytime that a resource is showing
Like at the end of the load of the server, i got probably 200 listbox in 1 window, and i want to show resources in only 1 listbox.
What should i do?

**Comment by ocornut** [comment]
Your widgets should have unique identifiers otherwise same identifier will append. You are using “”. Read the FAQ.
