### ISSUE TITLE
How to create multiple windows in the same thread or different threads through glfw in linux

### ISSUE THREAD

**Issue by DU-gl** [ocornut/imgui#5213]
Please, how does linux create multiple windows in the same thread or in different threads through glfw, is there any feasible way? I have only tried it successfully as a subprocess here.

**Comment by ocornut** [comment]
Lacking more details we cannot help you.
Maybe Multi-Viewports (https://github.com/ocornut/imgui/wiki/Multi-Viewports) are what you want, but you can also create 1 imgui context per platform window. Also see Glossary (https://github.com/ocornut/imgui/wiki/Glossary).
