### ISSUE TITLE
how does linux create multiple windows in the same thread or in different threads through glfw

### ISSUE THREAD

**Issue by DU-gl** [ocornut/imgui#5214]
Please, how does linux create multiple windows in the same thread or in different threads through glfw, is there any feasible way? I have only tried it successfully as a subprocess here.

I mean, for example, I originally created a native window that imgui uses glfw to render, and now I want to create multiple windows at the same time. When I continue to create windows through glfwCreateWindow, ImGui_ImplGlfw_InitForOpenGL(window, true); The association is failed , the error is as follows

example_glfw_opengl3: ../../backends/imgui_impl_glfw.cpp:445: bool ImGui_ImplGlfw_Init(GLFWwindow*, bool, GlfwClientApi): Assertion `io.BackendPlatformUserData == __null && "Already initialized a platform backend!"' failed.

**Comment by ocornut** [comment]
If you create multiple Dear ImGui Contexts with `ImGui::CreateContext()` you need to switch contexts accordingly with `ImGui::SetCurrentContext()`. If you don't you are initializing the backend twice for the same context.

**Comment by DU-gl** [comment]
Does imgui support simultaneous rendering of multiple windows on linux

**Comment by ocornut** [comment]
> Does imgui support simultaneous rendering of multiple windows on linux

It depends on the backend. SDL and GLFW backends support it (not perfectly, some issues with some WM).

**Comment by moyutanyy** [comment]
I am very sorry, I don't know if there is any hand of IMGUI under Linux (GLFW + OpenGL3) to create multiple windows？

**Comment by moyutanyy** [comment]
another，Does master branch or docking branch support multi-window (glfw+opengl)? Or another branch?

**Comment by moyutanyy** [comment]
I tried to create two windows in the following way, but the following error will be reported, how do I need to modify

example_glfw_opengl3: ../../backends/imgui_impl_glfw.cpp:445: bool ImGui_ImplGlfw_Init(GLFWwindow*, bool, GlfwClientApi): Assertion `io.BackendPlatformUserData == __null && "Already initialized a platform backend!"' failed.
已放弃 (核心已转储)

`    GLFWwindow *window_one = glfwCreateWindow(1280, 720, "Dear do_render_one ImGui GLFW+OpenGL3 example", NULL, NULL);
    glfwMakeContextCurrent(window_one);
    GLFWwindow *window_two = glfwCreateWindow(1280, 720, "Dear do_render_two ImGui GLFW+OpenGL3 example", NULL, window_one);
    glfwMakeContextCurrent(window_two);
    glfwSwapInterval(1); // Enable vsync

    // Setup Dear ImGui context
    ImGuiContext *ctx_one = ImGui::CreateContext();
    ImGui::StyleColorsDark();
    ImGui_ImplGlfw_InitForOpenGL(window_one, true);
    ImGui_ImplOpenGL3_Init("#version 130");

    ImGuiContext *ctx_two = ImGui::CreateContext();
    ImGui::StyleColorsDark();
    ImGui_ImplGlfw_InitForOpenGL(window_two, true);
    ImGui_ImplOpenGL3_Init("#version 130");`

**Comment by PathogenDavid** [comment]
@moyutanyy You need to call `SetCurrentContext` after the second `CreateContext`. It doesn't implicitly set the context when there's already one set.
