### ISSUE TITLE
Background image via GetBackgroundDrawList() not rendering as expected

### ISSUE THREAD

**Issue by YTN0** [ocornut/imgui#5217]
**Version/Branch of Dear ImGui:**

Version: Latest (via ImGui.NET nuget)

**Back-end/Renderer/Compiler/OS**

Back-ends: custom 
Compiler: Visual Studio 
Operating System: Windows 11

**My Issue/Question:**

XXX _(please provide as much context as possible)_

I have integrated ImGui into my renderer without any issues. Fonts, windows etc render without any issues. I am trying to render a background image *under* the ImGui windows and components and am running into an issue. I am aware that I could use my engine to directly render the background image, however, I would prefer to do this via ImGui due to the way I structured things and have screen management working.

I am trying to render the image using ImGui.GetBackgroundDrawList().AddImage(). I have it such that I can render the image without any issues, but the ImGui Window that is overlayed on top of it is messed up and isn't rendered correctly. I have attached some screenshots to indicate the problems. The first image is of the ImGui window without any background. The second image is after I enable the background image and have the ImGui window render over it. In that particular case, I also have PushStyleVar(ImGuiStyleVar.WindowRounding, 5.0f) enabled. If I remove the PushStyleVar()  and PopStyleVar(), I end up with the third image... a little better, but still not correct.

I have tried moving the GetBackgroundDrawList(),AddImage() to within the Begin() and End(), but that doesn't solve the problem (and makes things a little worse).

My Sequence of calls are:

GetBackgroundDrawList(),AddImage()
PushStyleVar()
Begin()
{Draw Components}
End()
PopStyleVar()

Any pointers would be appreciated!

**Screenshots/Video**

![imgui-expected](https://user-images.githubusercontent.com/5132310/164120021-529d28b8-8d61-4eaa-a7e5-859135046d62.jpg)

![imgui-got1](https://user-images.githubusercontent.com/5132310/164120055-923b3ba6-aec7-4fea-9b67-bdb2b7510a4d.jpg)

![imgui-got2](https://user-images.githubusercontent.com/5132310/164120075-cd7754f4-66b8-4608-a163-bb1c9e8c6c62.jpg)

**Comment by YTN0** [comment]
Anyone have any ideas or recommendations on how I might be able to solve this? I have tried googling and searching through the GitHub issues, but have not found any similar issue.

Thanks.

**Comment by PathogenDavid** [comment]
If you submit multiple windows do the other windows look correct?

The fact that several widgets are missing and the blend mode appears to be wrong makes me think your custom backend isn't implemented correctly.

**Comment by YTN0** [comment]
@PathogenDavid Appreciate the response! If I submit 2 windows, one renders, and the other does not. If I click the one it shows the other (and hides the first), and vice versa. I have gone back through my render code and I must be missing something.

I can render the demo window and Metrics windows without issues... but can't show both at the same time. If I try that, I get a crash on cmdList.VtxBuffer.Data with an index out of range error (with cmdList being drawData.CmdListsRange[n] and n being 1 with a count of 2). I get a crash in the same spot if I try to navigate to some spots in the demo window (like lists).

I have attached screenshots of the demo and metrics windows.

![imgui-demo](https://user-images.githubusercontent.com/5132310/164570937-7be5988f-0e6b-4804-9b34-505812a93278.jpg)

![imgui-metrics](https://user-images.githubusercontent.com/5132310/164570955-d9e3e4b7-8975-4077-ae37-c2d0ff35304d.jpg)

**Comment by YTN0** [comment]
Found the bug in my code that was causing this. Problem is now resolved!

**Comment by ocornut** [comment]
> Found the bug in my code that was causing this

It would be helpful to describe it for future references, in case other people stumble on same issue.

**Comment by YTN0** [comment]
Don't know if it's going to help anyone else since the bug was specific to my implementation... but basically my issue was as I was iterating over the CmdLists, I was doing:

`&_vertices[vtxOffset * sizeof(ImDrawVert)]` 

instead of 

`&_vertices[vtxOffset]`

since _vertices is an array of ImDrawVerts and not an array of bytes.

This was always working for the first window since the initial window always had vtxOffset = 0.
