### ISSUE TITLE
Secondary viewports and transparency (was: Window position affects Window Flags)

### ISSUE THREAD

**Issue by FabianPaci** [ocornut/imgui#5218]
(the numbers are seen in the video for reference)
https://user-images.githubusercontent.com/58243358/164129274-f18be578-a50f-4240-8590-04764da8e943.mp4

- 1: OBS (recording software) didn't pick it up but the window causes flickering (flashes black) (on the main window, not the whole screen) to occur when dragged out of main window.
- 2: the window almost completely ignores the `ImGuiWindowFlags_NoBackground` window flag when dragged out of main window. 
- 3: the `ImGuiWindowFlags_NoBackground` window flag effects the collapsing header's like it would normally.
- 4: `ImGuiWindowFlags_NoBackground` is the only window flag that is effected in this case.

(extra weird stuff)
https://user-images.githubusercontent.com/58243358/164131082-50019822-f444-4abc-baff-8d8bf31c548d.mp4

- 5: Menu's get moved to the left side of the screen when changing virtual desktops (they keep their y position). If you move virtual desktops to a new one (not the original desktop or the main window), the menu disappears. Also, menus keep menu items only in the virtual desktop you opened them in, else they will disappear.
- 6: An orphan window (any window that left the main window) will get pushed to the top left portion of the screen when leaving the main windows virtual desktop.
- 7: moving an orphan window to the bottom or the right border of the screen will result in an offset mouse (depending on how and where you dragged the window), and will position the window back to the middle (not center, it keeps its y position) of the main window. it  can also freeze the orphan window.
- 8: 
> it  can also freeze the orphan window.

(its a bit confusing so just ask questions if you need to)

**Comment by FabianPaci** [comment]
Im using DWM as a window manager. so its not totally a Dear ImGui issue.

**Comment by ocornut** [comment]
Secondary viewports don't properly support transparency by default. See #2766, #4629. (Closing as duplicate)

We would need to add support on a per backend basis, but you can probably wire things on your end.

You didn't fill the issue template, I won't help with the rest. Probably related to #2117.
