### ISSUE TITLE
How does InputText know when its hovering over selectable text?

### ISSUE THREAD

**Issue by Akandesh** [ocornut/imgui#5225]
**Version/Branch of Dear ImGui:**

Version: 1.83 W.I.P
Branch: Master

**My Issue/Question:**

Trying to modify the InputText and add centering of text, got everything visually correct but when drag selecting text it only "listens" at the old position i.e left centered. Where is this set?

 I see it's related to state->Stb.select_start and state->Stb.select_end but both of these pretty understandable and shouldn't cause an issue right? They're set with stb_textedit_drag. 

```
    const ImVec4 clip_rect(frame_bb.Min.x, frame_bb.Min.y, frame_bb.Min.x + inner_size.x, frame_bb.Min.y + inner_size.y); // Not using frame_bb.Max because we have adjusted size
    ImVec2 draw_pos = is_multiline ? draw_window->DC.CursorPos : frame_bb.Min + style.FramePadding;
    ImVec2 text_size(0.0f, 0.0f);

    // this is what I've added
    if (is_centered_text) {
        draw_pos = frame_bb.Min + (ImVec2{frame_bb.GetWidth() - CalcTextSize(buf).x, 0} / 2) + style.FramePadding;
    }
```

**Comment by Akandesh** [comment]
Here's the code related to it: https://github.com/ocornut/imgui/blob/4df57136e9832327c11e48b5bfe00b0326bd5b63/imgui_widgets.cpp#L4522

**Comment by ocornut** [comment]
I am sorry we don’f have the bandwidth to randomly answer questions of that nature, it seems a bit lazy to ask. If you work a feature it is up to you to understand what’s going on.

**Comment by Akandesh** [comment]
You're right. Didn't take me much more debugging to find that Stb.select_* counted characters and not pixels and then found what fed them data etc. 

Here's my solution for anyone who stumbles across this in the future. 

```cpp
static void    STB_TEXTEDIT_LAYOUTROW(StbTexteditRow* r, STB_TEXTEDIT_STRING* obj, int line_start_idx)
{
    const ImWchar* text = obj->TextW.Data;
    const ImWchar* text_remaining = NULL;
    const ImVec2 size = InputTextCalcTextSizeW(text + line_start_idx, text + obj->CurLenW, &text_remaining, NULL, true);
    const size_t offset = (obj->UserFlags & ImGuiInputTextFlags_CenteredText) != 0 ? 100 : 0;
    r->x0 = offset - size.x / 2.f;
    r->x1 = size.x / 2.f + offset;
    r->baseline_y_delta = size.y;
    r->ymin = 0.0f;
    r->ymax = size.y;
    r->num_chars = (int)(text_remaining - (text + line_start_idx));
}
```
Had to hardcode the width offset though. I use `ImGui::PushItemWidth( 200 );` so had to give it 100 here. Didn't find how to get the width dynamically from in this function.

**Comment by ocornut** [comment]
Sorry for the initial answer, but amount of open issues/pr is rather overwhelming.
I think we will probably merge #1442 #3853 for centering of drag/sliders, even if the values move to be left aligned when editing. For InputText() it'll need the centering at lower-level in the widget.
