### ISSUE TITLE
ImGui demo window not registering input from keyboard or mouse

### ISSUE THREAD

**Issue by Maratonec** [ocornut/imgui#5226]
**Version/Branch of Dear ImGui:**
Version: Latest
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_sdlrenderer.cpp
Compiler: MSVC
Operating System: Windows

**My Issue/Question:**

I am trying to build simple application using Sdl2 renderer and ImGui. For testing I just copied code from the example and put it in my program. It is completely same with the only difference being that it is not in main and I am not initializing SDL in main so I have to define SDL_MAIN_HANDLED.

The problem I am experiencing is that the demo windows does not respond (I cant move it, open menus, click buttons), but everything works as expected in the example. 

Can this be happening due to SDL_MAIN_HANDLED?

**Standalone, minimal, complete and verifiable example:**
https://pastebin.com/Dz3CPmx2

**Comment by ocornut** [comment]
> It is completely same with the only difference being that it is not in main

That's absolutely not true. You don't have a `SDL_PollEvent()` loop forwarding events to `ImGui_ImplSDL2_ProcessEvent()`.

**Comment by Maratonec** [comment]
Oh sorry. I don't know how I missed that
