### ISSUE TITLE
Imgui Window leaves trails when moving them around

### ISSUE THREAD

**Issue by Ishan-Chaudhari** [ocornut/imgui#5228]
So I've been following this - https://youtu.be/lZuje-3iyVE  (@TheCherno 's  Hazel Game Engine Series) 
And I've been through my code a lot of time but still this keeps happening. Here's the Link to my repo  - https://github.com/Ishan-Chaudhari/Electron

https://user-images.githubusercontent.com/96462931/164608123-9fcb6db6-8dae-46e9-9868-b63dd8c63b95.mp4

**Comment by ocornut** [comment]
You are not clearing your framebuffer (e.g. `glClear(GL_COLOR_BUFFER_BIT)` in a typical OpenGL setup). 
This is not a Dear ImGui question but you can check our myriad of example code.
