### ISSUE TITLE
CalcItemWidth() inside a Column gives wrong width

### ISSUE THREAD

**Issue by MINIONBOTS** [ocornut/imgui#523]
I placed a ListBox inside a Column and the width of the ListBox is only 3/4 of the available space. The problem comes from 
''
float w = window->DC.ItemWidth;
''
inside CalcItemWidth() inside the ListBoxHeader code, but I am not sure where the exact origin is...
![aaaa](https://cloud.githubusercontent.com/assets/2842405/12973335/ef7aea60-d0ab-11e5-9666-e64e4c1d887d.png)

Is this wanted behavior or a bug ?

**Comment by ocornut** [comment]
Use PushItemWidth(-1) to use the full width of a given region (assuming your listbox has no label).

**Comment by MINIONBOTS** [comment]
And that solved the issue :) thanks you very much!
