### ISSUE TITLE
How can I autofocus an input and then call a function when item is not focused anymore?

### ISSUE THREAD

**Issue by GasimGasimzada** [ocornut/imgui#5230]
I want to implement the following flow:

1. User clicks right click menu and click a menu item
2. The menu item toggles a state that creates an input **and focuses it**
3. When user changes the focus from the input (e.g clicks somewhere), an action gets called.

Here is something that I tried:

```
// Don't do anything if item is not clicked
if (menuItemClicked) {
  // If first time, focus the next widget
  if (mFirstTime) {
    ImGui::SetKeyboardFocusHere();
  }
  // Render input and store the value in an `std::string`
  if (ImGui::InputText("###NewEntryName", mTemporaryName,
                       IM_ARRAYSIZE(mTemporaryName))) {
    mTemporaryEntry.clippedName = mTemporaryName;
  }
  
  // Call action when input is not focused anymore
  // I tried `ImGui::IsItemActive()` as well but that did not work either
  if (!ImGui::IsItemFocused()) {
    handleEntryCreate();
  }
}
```

What happens is that, the action gets called every time as if the input is not focused. However, if I remove the action logic (just commenting it out), I see that the input gets autofocused due to `SetKeyboardFocusHere`.

**Comment by ocornut** [comment]
You can use IsItemDeactivated() or IsItemDeactivatedAfterEdit(). They are well demonstrated in the Demo.

**Comment by GasimGasimzada** [comment]
Thank you!
