### ISSUE TITLE
Lagging in my UI

### ISSUE THREAD

**Issue by MaloCow** [ocornut/imgui#5231]
Hello, just realized that i'm losting 20 FPS when i make show my interface, and when i remove my checkbox, all my fps come back, what i did wrong ? 

Checkbox example :

`bool antiheadshot = false;`
`ImGui::Checkbox("Anti headshot", &antiheadshot);`

`if (antiheadshot) {`

`uint64_t PlayerPedId = Invoker::InvokeNative<uint64_t>(0xD80958FC74E988A6);`
`Invoker::InvokeNative<void>(0xEBD76F2359F190AC, PlayerPedId, false);`
`}`
`else {`
`uint64_t PlayerPedId = Invoker::InvokeNative<uint64_t>(0xD80958FC74E988A6);`
`Invoker::InvokeNative<void>(0xEBD76F2359F190AC, PlayerPedId, true);`

`}`

If someone can help me, it will be greatful !

**Comment by ocornut** [comment]
Sorry but #1586
