### ISSUE TITLE
What is the closest thing to an HTML div in IMGUI

### ISSUE THREAD

**Issue by czsd** [ocornut/imgui#5237]
I'm trying build out some kind of layered UI where child elements have their x y relative to the parent UI. Is there something that represent an HTML div or simple box that can accept other boxes? I'm trying to build out a system where I can define a module and reuse it as a sub-module to a larger UI layout.

**Comment by ocornut** [comment]
BeginChild() or BeginGroup() would be the closest right now. Earlier would be bounded to a specific rectangle, later would lock the starting X coordinates. Please refer to the demo.

**Comment by czsd** [comment]
Sorry to reopen, ImGui::SetNextWindowPos(ImVec2(100, 100), ImGuiCond_Always) seems to position the child window as an absolute position, how do I do it relative to the parent?

**Comment by ocornut** [comment]
Use ImGui::GetWindowPos() and offset accordingly.
