### ISSUE TITLE
Does the Linux platform support imgui using glfw+OpenGL3 to render multiple main windows at the same time?

### ISSUE THREAD

**Issue by mtosdjs** [ocornut/imgui#5238]
Hello,
      Does the Linux platform support the use of glfw+OpenGL3 to create multiple main windows, and imgui can perform independent and simultaneous context creation and rendering in each main window?

**Comment by ocornut** [comment]
Yes.

May i ask you something. We’ve had half a dozen of the same type of questions last week. Are you part of a class, or following a guide/tutorial ?

**Comment by mtosdjs** [comment]
I just try if it works on ubuntu，out of interest. Also, I am using the default branch, can this be achieved? Or just docking?
