### ISSUE TITLE
New Flag Request: Add ImGuiDockNodeFlags_NoTabBarSeparator to disable tab bar separator (when not using custom tab bar)

### ISSUE THREAD

**Issue by peter1745** [ocornut/imgui#5239]
As the title says, I'd like to suggest a new `ImGuiDockNodeFlags` flag, which is to add a `ImGuiDockNodeFlags_NoTabBarSeparator` flag, which would disable the rendering of the default tab bar separator.

This can already be done by using a custom tab bar and changing the color of the separator as #5022 shows. But that only works for a custom tab bar, since the separator uses the same color as the tab items do.

It would be really handy to either be able to disable the separator when using the default tab bar (added by `ImGui::DockSpace`) by adding the flag I suggested or by making the separator have its own `ImGuiCol_` value, e.g `ImGuiCol_TabBarSeparator`.

I've already added this flag in my local copy of ImGui, and implemented it by wrapping the separator rendering code in this if:
```cpp
if (dock_node && (dock_node->SharedFlags & ImGuiDockNodeFlags_NoTabBarSeparator) == 0)
{
    // Draw separator
}
```
This lets us pass the `ImGuiDockNodeFlags_NoTabBarSeparator` flag to `ImGui::DockSpace`, allowing us to easily disable it.

Again, this can already be achieved by using a custom tab bar, and changing the color, but it would be really nice to be able to disable it when using the default tab bar provided by `ImGui::DockSpace`

**Comment by peter1745** [comment]
Closing this as I've realized you can just do this:
```cpp
ImGui::PushStyleColor(ImGuiCol_TabActive, ImVec4(0.0f, 0.0f, 0.0f, 0.0f));
ImGui::PushStyleColor(ImGuiCol_TabUnfocusedActive, ImVec4(0.0f, 0.0f, 0.0f, 0.0f));
ImGui::DockSpace(m_DockSpaceID, ImVec2(0.0f, 0.0f), dockspace_flags);
ImGui::PopStyleColor(2);
```
and achieve the same look.

**Comment by ocornut** [comment]
FYI
Now added a style.TabBarBorderSize variable,
So `ImGui::PushStyleVar(ImGuiStyleVar_TabBarBorderSize, 0.0f)` will also work.
