### ISSUE TITLE
Windows with nothing but a UserCallback draw cmd are stripped during Render()

### ISSUE THREAD

**Issue by deltaluca** [ocornut/imgui#524]
I presume this relates to : AddDrawListToRenderList of imgui.cpp

eg:
````
if (ImGui::BeginChild("Test"))
{
    auto* cmd = ImGui::GetWindowDrawList();
    cmd->AddCallback([](const ImDrawList*, const ImDrawCmd*)
    {
        std::cout << "helllooooo??" << std::endl;
    }, nullptr);
    ImGui::EndChild();
}
````

I presume it's because AddDrawListToRenderList is checking for a non-empty vertex buffer (and here it would be empty..)

And certainly adding any bits of gui like an ImGui::Button(".."); does then cause the callback to also be triggered.

**Comment by ocornut** [comment]
I suppose this block

```
    if (!draw_list->CmdBuffer.empty() && !draw_list->VtxBuffer.empty())
    {
        if (draw_list->CmdBuffer.back().ElemCount == 0)
            draw_list->CmdBuffer.pop_back();
```

Could be changed to:

```
    if (!draw_list->CmdBuffer.empty() && draw_list->CmdBuffer.back().ElemCount == 0)
        draw_list->CmdBuffer.pop_back();
    if (!draw_list->CmdBuffer.empty())
    {
```

But I will need to test it a little more.

**Comment by ocornut** [comment]
Note that even though it is a bug and should be fixed, if you only need a callback you probably don't need a window for it ? (aka if it is a child then the callback can be in the parent window, etc.)

**Comment by deltaluca** [comment]
That is true, I could just create an empty child or dummy element after adding the callback to reserve the space the calback renders into.

**Comment by ocornut** [comment]
No, I meant, there's no point in creating a child window if you are only adding a callback it. You could just have added the callback to the parent window.

I have fixed this bug now. However note that some of the rendering code calling front() on the VtxBuffer vectors may need to add a test to avoid an assert here. I'm leaving this as for now as people using callback are very likely to be messing up with their renderer.
