### ISSUE TITLE
ImGui::Button doesn't apply ImGuiCol_TextDisabled color when ImGuiItemFlags_Disabled is set

### ISSUE THREAD

**Issue by peter1745** [ocornut/imgui#5240]
**Version/Branch of Dear ImGui:**

Version: 1.87 (18701)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan_with_textures.cpp
Compiler: MSVC
Operating System: Windows 11

**My Issue:**
Currently when setting a button to be disabled, it does prevent the user from clicking it, and it doesn't respond to hover / focus. But at the moment it doesn't change the text color to the disabled color (`ImGuiCol_TextDisabled`).
While it's simple to hack around this (just set `ImGuiCol_Text` to have the same value as `ImGuiCol_TextDisabled`), it's not the expected behavior.

**Example code to reproduce**:
```
static bool disableButton = false;
ImGui::Checkbox("Disabled", &disableButton);
ImGui::PushItemFlag(ImGuiItemFlags_Disabled, disableButton);
ImGui::Button("Some Button");
ImGui::PopItemFlag();
```

**Comment by ocornut** [comment]
As per https://github.com/ocornut/imgui/issues/4478#issuecomment-905568839 and generally #211 the existence of `ImGuiCol_TextDisabled` became a little inconsistent with the new `BeginDisabled()/EndDisabled()` API. Generally we don't expect `ImGuiCol_TextDisabled` to be used much (until we redesign styling).

`ImGui::PushItemFlag(ImGuiItemFlags_Disabled, disableButton);` is an internal/documented API which only alter interactions.
See the comment
```
ImGuiItemFlags_Disabled = 1 << 2, // Disable interactions but doesn't affect visuals. See BeginDisabled()/EndDisabled(). See github.com/ocornut/imgui/issues/211
```

You should use `BeginDisabled()/EndDisabled()` it will have an effect on all colors.

**Comment by peter1745** [comment]
Ah, hadn't noticed that one, I'll be sure to switch to using that! Thanks for the quick reply 🙂
