### ISSUE TITLE
Selectable drag source with overlapping DragInt drop target

### ISSUE THREAD

**Issue by caxapexac** [ocornut/imgui#5241]
Version/Branch of Dear ImGui:

Version: 1.86
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: webGL
Compiler: em++
Operating System: V8

My Issue/Question:

How to drag DragInt using Selectable on the same line (or something like this). I want to have every field being draggable in the inspector

Example:

```cpp
ImGui::Selectable("SOURCE");
if (ImGui::BeginDragDropSource())
{
    ImGui::SetDragDropPayload(type, nullptr, 0); // Somehow saving
    ImGui::Text("dragging");
    ImGui::EndDragDropSource();
}
ImGui::SameLine();
ImGui::DragInt(label, v, v_speed, v_min, v_max, format, flags);
if (ImGui::BeginDragDropTarget())
{
    if (const ImGuiPayload* payload = ImGui::AcceptDragDropPayload(type))
    {
        // *v = somehow droppping
    }
    ImGui::EndDragDropTarget();
}
```

I suppose Selectable should become DragSource
But DragInt becomes DragSource too so I can't drag it anymore:

https://user-images.githubusercontent.com/33996246/165069186-792e81ef-7034-48d4-8125-ac3e9f867cc1.mp4

I want "SOURCE" to be drag source and DragInt to be drag target

**Comment by caxapexac** [comment]
Seems like Selectable has unlimited width

**Comment by ocornut** [comment]
> Seems like Selectable has unlimited width

Well yes it default to the equivalent of -FLT_MIN for width, aka right-align.

You can either specify a width for the Selectable() using the Size parameters (e.g. `ImVec2(ImGuI::CalcTextSize(label).x, 0.0f)`)
Or you can use the `ImGuiSelectableFlags_AllowItemOverlap` flag to make further items be prioritized for hit testing.

**Comment by caxapexac** [comment]
Thanks it actually works!
@ocornut  Btw I haven't found in the useful extensions wiki any unity-like array/map/list inspector widget extensions. Are they exist? Maybe you've heard about any solution for this?
i.e. something for editing std::vector<int> (add, remove, drag-drop, insert, reorder)
