### ISSUE TITLE
Multi window ERROR

### ISSUE THREAD

**Issue by 00BUG00** [ocornut/imgui#5244]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

Version:  1.86 WIP (18513)
Branch: master

**Renderer**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: G++
Operating System: Ubuntu 20.04（WSL2）

My Issue/Question:

Create two glfw windows. When imgui is used in each window, close the first glfw, and the program exits abnormally. The error message is as follows:

X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x0
  Serial number of failed request:  7067
  Current serial number in output stream:  7068

**Comment by ocornut** [comment]
You are not providing enough information. Please use a debugger to track down the issue.
