### ISSUE TITLE
Proper NestedTree Help

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#525]
Hello,

I have a question. I'm trying to create a nested tree. Specifically GameAssets->Resource Category-> and Resource. A function is called per frame to generate a table that Imgui friendly.  The problem I am having is the list doesn't show the category resource nodes in the right treenode.

Meaning the fourth category shows resource nodes of category  up to three. The first category shows nothing. The second category shows the first category.

I can't seem to represent the information correctly.

Vivienne.

```
// kep this static
    static int TotalCategories = ImGuiFriendlyCategories.Size();

    // Create ImGui Window
    if(ImGui::Begin("Game Assets",p_opened,ImVec2(DEFAULTWIDTH, DEFAULTHEIGHT ),0.5, window_flags))
    {
        // If not initialized position the window
        if(!m_bInitialized)
        {
            // get windows size
            unsigned int WindowWidth = g_pApp->GetGraphics()->GetWidth();
            unsigned int WindowHeight = g_pApp->GetGraphics()->GetHeight();
            // Set window position
            ImGui::SetWindowPos(ImVec2((WindowWidth/2)-(DEFAULTWIDTH/2),(WindowHeight/2)-(DEFAULTHEIGHT/2)));
        }

        // force width
        ImGui::PushItemWidth(-1);

        // Produce list
        if(ImGui::TreeNode("GameAssets"))
        {
            for(int Categories = 0; Categories<TotalCategories; Categories++)
            {
                // create tree
                if(ImGui::TreeNode(ImGuiFriendlyCategories.At(Categories).m_Name))
                {
                    for(int Resource  = 0; Resource< ImGuiFriendlyCategories.At(Categories).Resources.Size(); Resource++)
                    {
                        if(ImGui::TreeNode(ImGuiFriendlyCategories.At(Categories).Resources.At(Resource).m_Name))
                        {
                            ImGui::TreePop();
                        }
                    }
                      ImGui::TreePop();
                }
            }

            ImGui::TreePop();
        }
    }
```

**Comment by ocornut** [comment]
I don't understand your question. The code flow looks correct. Show us the data and the result. You ideally shoudn't need to "convert" your data and you'd better use your raw original data to avoid mistakes.. 

That code will only work if your category names are unique and within a category your resource names are unique, else the ID will conflict and you may be unable to open some node. You can fix that by passing a more unique identifier as the first parameter to TreeNode() and a format string/label in the remaining parameter.

**Comment by vivienneanthony** [comment]
Hi

I  tried not to convert the data but it was problematic. As to showing the data, the results.. I have a picture of it but since one of my recent post I was asked more so told not to post any picture. I refrained from showing it. Illustrating the problem.

Anyway, I'm closing this issue.  I find another solution

Vivienne

**Comment by SimantoR** [comment]
Hi, I wanted to revisit this as a user and admirer of ImGui. I think discord server allows more people who handle things to reduce the effort core contributors. Discord for asking for help, in particular, seems useful. For decision making and discussion, it should always be github for the transparency and record-keeping but discord might tackle the problem of people coming to the issue section and creating duplicates.
