### ISSUE TITLE
Get Old Draw Data To Display If Not Rendered New Data

### ISSUE THREAD

**Issue by DEVLOPRR** [ocornut/imgui#5252]
**Version/Branch of Dear ImGui:**

Version: [1.87](https://github.com/ocornut/imgui/releases/tag/v1.87)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Clang++
Operating System: Manjaro Linux

**Question:**
I am drawing UI for my [pixel art tool](https://github.com/DEVLOPRR/CSprite) using ImGui, but since UI isn't updated very often i want to use the old render data to display until and unless new data is rendered, for example:

```cpp
unsigned char uiShouldRender = 1; // Global Variable
...
// Here's some code anyone can copy and paste to reproduce your issue
if (uiShouldRender == 1) {
	ImGui_ImplOpenGL3_NewFrame();
	ImGui_ImplGlfw_NewFrame();
	ImGui::NewFrame();

	ImGui::Begin("SelectedToolWindow", NULL, window_flags);
	ImGui::SetWindowPos({0, 0});
	ImGui::Text("Square Eraser - (Size: %d)", brush_size);
	ImGui::End();

	ImGui::Render();
	uiShouldRender = 0;
}
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

In this code the if statement is executed atleast once causing ImGui to draw the data, now this statement will only run again when in event handler the `uiShouldRender` is set to `1` again, 

This whole code is inside my window loop:
```cpp
while (!glfwWindowShouldClose(window)) {
	glfwPollEvents();
	process_input(window);
	glClearColor(0.075, 0.075, 0.1, 1.0);
	...
	glfwSwapBuffers(window);
}
```
Problem is i see everything normal on my screen except my UI, my canvas and etc are working Normally except the UI doesn't show up.

I am doing this so that i won't need render everytime even when it is not needed, i know ImGui is a immediate mode rendering UI system but it would be help full if it was possible to use the old draw data if new isn't rendered.

Output I Get:
![image](https://user-images.githubusercontent.com/75035219/165697970-0e6f88ff-fdc3-4a02-a041-faefdde404b7.png)

Output I Get When I Just Draw The UI Every Frame:
![image](https://user-images.githubusercontent.com/75035219/165698308-126727cb-510a-4b56-b0c7-132180cd7acd.png)

**Comment by ocornut** [comment]
> but since UI isn't updated very often i want to use the old render data to display until and unless new data is rendered,
> [...] I am doing this so that i won't need render everytime even when it is not needed, i know ImGui is a immediate mode rendering UI system but it would be help full if it was possible to use the old draw data if new isn't rendered.

But what ? What is the reason you want to do that ? Serious question.
Could you simply skip rendering your entire app (not just UI) on idle ?

If I look at your repro / pseudo code it looks correct: if you don't call NewFrame/Render the draw data won't elapse. So I presume there's something else in your code that's different from that piece of code.

We will eventually probably merge #2749 / #4076 but I don't have visibility on when.

**Comment by DEVLOPRR** [comment]
For idle state i know, but when using the application the UI isn't updated until and unless user selects a new tool or pans around or zooms in or out, so i don't want to render the same thing again, i want to use the old render data to display and render again only when the user selects a tool or something like that.

**Comment by ocornut** [comment]
> so i don't want to render the same thing again

You haven't answered my question "why?" but I suspect you are over-engineering for a non-problem here.
As stated above you repro should be correct since the draw data won't be changed if you don't call any function, so you are omitting something and I cannot magically guess what it is and debug your code.

**Comment by DEVLOPRR** [comment]
Hey @ocornut Sorry for the mess i created, I basically didn't want to render the same thing again because i thought it might cost me some performance, but i ran some tests and didn't found any major performance difference.
I figured out how to render only when i need to but it wasn't worth it.
I am sorry.
Thanks
