### ISSUE TITLE
Use of `VK_*_MAX_ENUM`

### ISSUE THREAD

**Issue by StellaSmith** [ocornut/imgui#5254]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_vulkan.cpp
Compiler: GCC 11.2.0
Operating System: Manjaro

**My Issue:**

`VK_*_MAX_ENUM` constants should not be used by applications
see: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#fundamentals-validusage-enums
```
imgui_impl_vulkan.h:151:23: error: ‘VK_PRESENT_MODE_MAX_ENUM_KHR’ was not declared in this scope; did you mean ‘VK_PRESENT_MODE_MAILBOX_KHR’?
  151 |         PresentMode = VK_PRESENT_MODE_MAX_ENUM_KHR;
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       VK_PRESENT_MODE_MAILBOX_KHR
```

**Comment by StellaSmith** [comment]
Please note that `VK_PRESENT_MODE_FIFO_KHR` is ensured to be present, so using this as a fallback is safe.
see: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPresentModeKHR.html

**Comment by PathogenDavid** [comment]
I don't think the intent of using `VK_PRESENT_MODE_MAX_ENUM_KHR` here is to enable auto-detection or be a sensible fallback. I believe it's to be purposefully invalid so that something goes bang if you forget to populate it. If we want to preserve that intent without `VK_PRESENT_MODE_MAX_ENUM_KHR` it should probably just be `(VkPresentModeKHR)~0`.

**Comment by ocornut** [comment]
> I don't think the intent of using VK_PRESENT_MODE_MAX_ENUM_KHR here is to enable auto-detection or be a sensible fallback. I believe it's to be purposefully invalid so that something goes bang if you forget to populate it

You are right. Thank you for looking it up!
Pushed a fix. Thank you both.
