### ISSUE TITLE
How to position sub windows inside the main window?

### ISSUE THREAD

**Issue by rockandsalt** [ocornut/imgui#5259]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: glfw+opengl3
Compiler: msvc
Operating System: XXX

**How to position and lock window inside the main window**

I am trying to position a window inside the main window (the upper left corner to be exact) and slave it to the main window (moving/resize the main window will resize the child window). kinda of like doing a layout inside the main window. But I am noticing when I call `ImGui::GetWindowPos()` the value doesn't change when I move the main window. The value also doesn't correspond to the position of the main window either since the window "example" spawns outside of it. How is positioning done in Imgui?

```
bool show = true;
while (!glfwWindowShouldClose(m_window))
{
  glfwPollEvents();
  ImGui_ImplOpenGL3_NewFrame();
  ImGui_ImplGlfw_NewFrame();
  ImGui::NewFrame();

  auto vec = ImGui::GetWindowPos();
  ImGui::SetNextWindowPos(vec, ImGuiCond_Once);

  ImGui::Begin("example", &show, ImGuiWindowFlags_NoMove);
  ...
  ImGui::End();

  ImGui::Render();
  ...
}
```

**Comment by ocornut** [comment]
Use GetMainViewport()->Pos and Size as instructed by the many examples in the Demo doing so.

(GetWindowPos() here is a little confusingly getting you the position of the previous window in the stack which is the implicit and auto-hidden “Debug” window.)
