### ISSUE TITLE
Rendering truncated text with an ellipsis

### ISSUE THREAD

**Issue by JumpyLionnn** [ocornut/imgui#5267]
**Version/Branch of Dear ImGui:**

Version: v1.87
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: windows10

**My Issue/Question:**

I wanted to add a text that will overflow and go out of the window border.
Is there a feature to truncate the text and add 3 dots at the end?
I have seen this feature in the tabs but I didn't see any specific styling for that in the ImGui demo window source file.

**Screenshots**
this is what I got:
![image](https://user-images.githubusercontent.com/79366074/166146413-befdb47f-7e67-41d4-9f9a-02fda375ca46.png)
and this is what I want:
![imguiscreenshot](https://user-images.githubusercontent.com/79366074/166146406-61b0ec08-1ab6-4abe-9ffc-c0e5a826f0c5.png)

thanks for the help

**Comment by ocornut** [comment]
It’s not currently easily possible. We have internals low level helpers which provide some of that facility but its not exposed in the public api as we’ve got a lot more things to design.

**Comment by ocornut** [comment]
FYI the imgui_internal.h function is
`RenderTextEllipsis(ImDrawList* draw_list, const ImVec2& pos_min, const ImVec2& pos_max, float clip_max_x, float ellipsis_max_x, const char* text, const char* text_end, const ImVec2* text_size_if_known);`
It's fairly usable if you manage to call things yourself, but as with others API may break in the future.
Although to be honest I expect that it'll only break the day we reorganize all text functions into a new nicer API.

**Comment by Gl1tchs** [comment]
it is pretty easy to estimate here is my utility function

```cpp
std::string TruncateText(const std::string& p_text, float p_truncated_width) {
	std::string truncated_text = p_text;

	const float text_width =
			ImGui::CalcTextSize(p_text.c_str(), nullptr, true).x;

	if (text_width > p_truncated_width) {
		constexpr const char* ELLIPSIS = " ...";
		const float ellipsis_size = ImGui::CalcTextSize(ELLIPSIS).x;

		int visible_chars = 0;
		for (size_t i = 0; i < p_text.size(); i++) {
			const float current_width = ImGui::CalcTextSize(
					p_text.substr(0, i).c_str(), nullptr, true)
												.x;
			if (current_width + ellipsis_size > p_truncated_width) {
				break;
			}

			visible_chars = i;
		}

		truncated_text = (p_text.substr(0, visible_chars) + ELLIPSIS).c_str();
	}

	return truncated_text;
}
```
