### ISSUE TITLE
NSKeyUp is deprecated, use NSEventTypeKeyUp instead.

### ISSUE THREAD

**Issue by mihaitoaca** [ocornut/imgui#5268]
**Filename:** imgui_impl_osx.mm 
**Line:** 447

`NSEventMask eventMask = NSEventMaskFromType(NSKeyUp) | NSEventMaskFlagsChanged;`

to 

`NSEventMask eventMask = NSEventMaskFromType(NSEventTypeKeyUp) | NSEventMaskFlagsChanged;`

**Comment by ocornut** [comment]
Should have been fixed along with e66fc2205744a3b84422ed208933b29c31093f18
Thanks!
