### ISSUE TITLE
imgui without backend

### ISSUE THREAD

**Issue by sho94os** [ocornut/imgui#5271]
is it possible to use imgui without backend i mean without opengl and direktx.
only a small program c++ code and imgui code

**Comment by Trider12** [comment]
You can't use ImGui without a backend, however the fastest way (that comes to my mind) to get ImGui up and running, which also fits your description of "without OpenGL and DirectX" and "only a small program c++ code and imgui code" is [this](https://github.com/eliasdaler/imgui-sfml).

**Comment by ocornut** [comment]
Closing as answered. Thank you @Trider12
