### ISSUE TITLE
Table declaring incorrect auto-fit width when using non-resizable weighted columns

### ISSUE THREAD

**Issue by PaltryProgrammer** [ocornut/imgui#5276]
Please see attached GIF demonstrates slight bug in auto fit Thank You - Best - Cheerio

![example_win32_directx12 incorrect auto fit](https://user-images.githubusercontent.com/48535920/166239165-5d5a4ca7-2a69-4940-ab2a-6e26593e3ff6.gif)

**Comment by ocornut** [comment]
Thanks for reporting! I think it was logged in some todo list but never addressed.
I have pushed a fix for it now 3e5dde9a2606addd702726b4769c7f93314bf7ac
