### ISSUE TITLE
close button in BeginPopupModal

### ISSUE THREAD

**Issue by Extrawurst** [ocornut/imgui#528]
Is there a way to have the ususal close button "X" in Modal Popups ? If not, why ?

**Comment by ocornut** [comment]
I am sure to understand the question.
BeginPopupModal has a `bool* p_opened` pointer and it is functional afaik.

**Comment by Extrawurst** [comment]
yeah sorry totally oversaw that, was looking for a window flag to define the button being there - dunno why -.-

**Comment by ocornut** [comment]
I suppose this case is a little odd, as you can perfectly use a locally defined (not persistent) `bool opened = true;`and pass it to the function and it would work. So it's fair to be expecting a flag. I suppose a flag could in theory be added but it may just add unnecessary confusion.

**Comment by ratchetfreak** [comment]
Not to mention you can add

```
if(Button("Close")){
     opened = false;
}
```

assuming opened is persisted across frames. And you have a button/event that sets it to true again.

**Comment by Extrawurst** [comment]
@ratchetfreak yeah but thats looks shitty and inconsistent with all the other windows with close buttons ;)

**Comment by ratchetfreak** [comment]
scratch that you can use `CloseWindowButton(&opened)`
