### ISSUE TITLE
`ColorButton` Not Registering Clicks.

### ISSUE THREAD

**Issue by DEVLOPRR** [ocornut/imgui#5285]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: [GitHub 1.87 Release](https://github.com/ocornut/imgui/releases/tag/v1.87)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Clang
Operating System: Manjaro Linux

**My Issue/Question:**
I am working on a [pixel art tool](https://github.com/DEVLOPRR/CSprite), and i am using `ColorButton` for making a simple Color Palette, but when i am clicking on a `ColorButton` it sometimes does register the click & sometimes doesn't.

**Screenshots/Video**

https://user-images.githubusercontent.com/75035219/166822149-2eea7336-ea56-4d66-bd29-3cc756e5aa50.mp4

A minimal example:

```c++
ImGui::Begin("ColorPaletteWindow", NULL, ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove);
ImGui::SetWindowPos({0, (float)WINDOW_DIMS[1] - 35});
for (int i = 1; i < palette_count; i++) {
	if (i != 1) ImGui::SameLine();
	if (ImGui::ColorButton(palette_index == i ? "Selected Color" : "Color", {(float)palette[i][0]/255, (float)palette[i][1]/255, (float)palette[i][2]/255, (float)palette[i][3]/255})) {
		palette_index = i;
	}
};
ImGui::End();
```

Here the `palette` is an array of RGBA colors:
```c++
unsigned char palette[17][4] = {
	{ 0,   0,   0,   0   }, // Black Transparent/None
	// Pico 8 Color Palette - https://lospec.com/palette-list/pico-8
	{ 0,   0,   0,   255 }, // Black Color
	{ 29,  43,  83,  255 }, // Dark Violet
	{ 126, 37,  83,  255 }, // Dark Pink
	{ 0,   135, 81,  255 }, // Dark Green
	{ 171, 82,  54,  255 }, // Dark Orange
	{ 95,  87,  79,  255 }, // Dark Brown
	{ 194, 195, 199, 255 }, // Grey
	{ 255, 241, 232, 255 }, // Seashell
	{ 255, 0,   77,  255 }, // Redish Pink
	{ 255, 163, 0,   255 }, // Orange
	{ 255, 236, 39,  255 }, // Yellow
	{ 0,   228, 54,  255 }, // Green
	{ 41,  173, 255, 255 }, // Blue
	{ 131, 118, 156, 255 }, // Light Purple
	{ 255, 119, 168, 255 }, // Pink
	{ 255, 204, 170, 255 }  // Pale Orange
};
```
And the `palette_index` is the index at which currently selected color is.
a possible answer i can think of is that the mouse click and if statement inside the for loop somehow match.
would love to see anyother option to make a color palette.

Note: My FPS is Locked To 60 Frames A Second.

**Comment by ocornut** [comment]
Changing label at the time of a click will change the item identifier and may mess up with interaction. See FAQ on how to change label while preserving identifier.

**Comment by DEVLOPRR** [comment]
Thanks Alot, This Fixed The Issue.

```c++
for (int i = 1; i < palette_count; i++) {
	...
	if (ImGui::ColorButton(palette_index == i ? "Selected Color" : ("Color##" + std::to_string(i)).c_str(), {(float)palette[i][0]/255, (float)palette[i][1]/255, (float)palette[i][2]/255, (float)palette[i][3]/255})) {
	...
	}
};
```
