### ISSUE TITLE
ImGui::Image and the blending options

### ISSUE THREAD

**Issue by vd3d** [ocornut/imgui#529]
Hi there,

I'm currently using ImGui::Image to mix 2 images. The first one is the main image and the second is a "selection mask".

I do the following
'''
ImGui::Image((void*)(intptr_t)_mainTexID, ImVec2(w, h), ImVec2(0.f, 1.f), ImVec2(1.f, 0.f));
if (condition)
ImGui::Image((void*)(intptr_t)_selectionTexID, ImVec2(w, h), ImVec2(0.f, 1.f), ImVec2(1.f, 0.f), ImVec4(1.f, 0.f, 0.f, .5f));
'''

The problem I have is that "condition" is true (when applying the second image) the first one becomes darker.

Notice that the second image contains either the red color either transparent color.

Do you see a solution ? Or is there a possibility to add such option please ?

Thanks for your support

**Comment by ocornut** [comment]
Hello,
It is a little hard to help you here. You aren't providing much context.

If you are using one of the default rendering and your texel colors are indeed transparent (alpha 0) it shouldn't affect the underlying color.

- I don't understand what you are trying to do, "mixing 2 images" and "selection mask", can refer to a million things. What does "add such option" means?
- You aren't providing the texture making it harder to help you.
- ImGui just adds the vertexes to a list and you are responsible for drawing them, including setting up your blending settings. I don't know what your texture looks like, I don't know what you renderer looks like. There's little to no transformation of colors performed by the library here. 

If you need to change blending options per widget you might be able to use the callback system to instruct your renderer to change blending state.

**Comment by vd3d** [comment]
Thanks,

Using the callback system solved my issue. It allow to change the OpenGL blend mode.

Thanks for your support
