### ISSUE TITLE
Its possible to block ALT navigation and focus?

### ISSUE THREAD

**Issue by KennyProgrammer** [ocornut/imgui#5292]
Hey everyone!

Its possible to block **ALT** navigation and focus on window? Its very useful and great feature but problem because in my application ALT key already using for rotation camera and other edit modes. 
And when I click on the **ALT** to start rotating the camera, I have an Imgui window that I don't want to choose, and it turns out when I often click on the alt when the camera rotates, the windows are not highlighted, and this causes discomfort. I tried using **ImGuiWindowFlags_NoNav** or **ImGuiWindowFlags_NavFocus** but this only disables appearing window when press on **CTRL+Tab**.

![image](https://user-images.githubusercontent.com/56895345/167252488-d54ce5da-dd16-4505-aec9-ad04d1413802.png) ![image](https://user-images.githubusercontent.com/56895345/167252524-86c666d1-148f-4039-a959-6b95081924aa.png)

So can i somehow disable this or change key navigation from **ALT** to only **Right-ALT** or other key?

**Comment by ocornut** [comment]
Are those Docked windows or a manually submitted tab bar ?

I am currently working on a solution for this and hope to publish it in May.

**Comment by KennyProgrammer** [comment]
Thanks for the reply. Yes, this is a docked window . But it seems to me that when you press **ALT**, even a separate window will be highlighted.
I'm not sure about the manually sent tab bars because I haven't checked this case.

**Comment by ocornut** [comment]
I've posted an answer for this in [#3560](https://github.com/ocornut/imgui/issues/3560#issuecomment-1458502821)
You can now generally use SetItemKeyOwner(ImGuiMod_Alt, ...) or SetKeyOwner(ImGuiMod_Alt, ...) to claim ownership of a key.

**Comment by KennyProgrammer** [comment]
Its been late, but thanks anyway :) I already fixed this by modified some ImGui internal code add flag or something (dangerous), but if now ImGui has public API i revisit this.
