### ISSUE TITLE
Imgui Crash

### ISSUE THREAD

**Issue by FF69B3** [ocornut/imgui#5293]
`int ImDrawList::_CalcCircleAutoSegmentCount(float radius) const`
`{`
   ` // Automatic segment count`
  `  const int radius_idx = (int)(radius + 0.999999f); // ceil to never reduce accuracy`

`    if (radius_idx < IM_ARRAYSIZE(_Data->CircleSegmentCounts))`
     `   return _Data->CircleSegmentCounts[radius_idx]; // Crash Here`
  `  else`
  `      return IM_DRAWLIST_CIRCLE_AUTO_SEGMENT_CALC(radius, _Data->CircleSegmentMaxError);`
`}`

I Use Inject ImguiDx11 Dll , When I draw the rect, and I use rounding, crash in some cases, and when I debug the code, it crashes here.    return _Data->CircleSegmentCounts[radius_idx]; 

I don't know why。

 `   return radius * 2;`

I use like this, no crash

**Comment by rokups** [comment]
See #1586.

**Comment by ocornut** [comment]
Also same issue as #5249

**Comment by FF69B3** [comment]
> See #1586.

I'm just submitting questions and solutions, is there anything about cheating in my question?

**Comment by FF69B3** [comment]
> Also same issue as #5249

Thank  You.

**Comment by rokups** [comment]
DLL injection is commonly used for cheating and is a _very_ unsupported configuration where million things can go wrong, 999999 of them have nothing to do with Dear ImGui.
