### ISSUE TITLE
How do I prevent clicking background when I click the IMGUI button

### ISSUE THREAD

**Issue by xiaoyxue** [ocornut/imgui#5294]
How do I prevent clicking background when I click the IMGUI button

**Comment by Alex-vZyl** [comment]
How are we supposed to know what background you are referring to?  Also, we have no idea how you handle events.

**Comment by ocornut** [comment]
This is probably thiS FAQ entry:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application
