### ISSUE TITLE
What happened to ImGuiConfigFlags_ViewportsEnable in 1.87?

### ISSUE THREAD

**Issue by slava-aes** [ocornut/imgui#5298]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp - DIRECTX11
Compiler: MSVC
Operating System: Windows 10

I was using an old imgui template which used ` io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable; `

I'm now trying to create a new template but appareantly this flag is no longer in 1.87? How do I get a simillar effect?

**Comment by rokups** [comment]
`ImGuiConfigFlags_ViewportsEnable` is available in docking branch.
