### ISSUE TITLE
BeginCombo not opening a drop down

### ISSUE THREAD

**Issue by mking1999** [ocornut/imgui#5306]
Hello, quick question, I tried to make a combo and it worked before, but since then something has happened and broken it. I get no errors when I try to open it just doesn't work.

```
if (ImGui::BeginCombo("Combo", combo_preview_value))
    {
        for (int n = 0; n < 10; n++)
        {
            if (ImGui::Selectable(components[n]))
                item_current_idx = n;
        }
        ImGui::EndCombo();
    }
```

Any idea what could possibly be causing issues?

**Comment by rokups** [comment]
Your code snippet is correct and works without issues, tested in official examples.

**Comment by ocornut** [comment]
Failing to read our guidelines and providing an actual repro. Will reopen once you make an effort to follow those guidelines and provide the correct information.
