### ISSUE TITLE
glyph_ranges memory ownership

### ISSUE THREAD

**Issue by caxapexac** [ocornut/imgui#5309]
Version/Branch of Dear ImGui:

Version: 1.86
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: webGL
Compiler: em++
Operating System: V8

My Issue/Question:

AddFontFromMemoryTTF accepts `const ImWchar* glyph_ranges` but won't copy it:
```
if (glyph_ranges)
        font_cfg.GlyphRanges = glyph_ranges;
```

I have api like this:
```
m_imgui->setFontComposite("composite",
  {{"fonts/roboto-regular.ttf",      m_fontSize},
  {"fonts/fa-solid-900.ttf", 18, ICON_MIN_FA, ICON_MAX_FA}});
// another fonts comes here
m_imgui->initFonts(); // uses glyph_ranges pointer, saved by imgui. Generating atlas
```

ICON_MIN_FA, ICON_MAX_FA parameters creates temporary ImVector<ImWchar> which destroys itself before I call initFonts() so I get an error:
```
SetCurrentFont ( font && font->IsLoaded())
```

I've tried to save ranges into my internal internal ranges cache but it looks ugly and doesn't work either somehow (maybe something wrong with copying ImVector?)

**Comment by caxapexac** [comment]
Solved by using `io.Fonts->Build();` after places where glyph_ranges is used. Is this the only solution?

**Comment by heroboy** [comment]
I have asked same question.  https://github.com/ocornut/imgui/issues/2052

**Comment by ocornut** [comment]
It is documented that your glyph ranges must be valid during building and is not copied by Dear ImGui.
```
THE ARRAY DATA NEEDS TO PERSIST AS LONG AS THE FONT IS ALIVE.
```
In future version building/rebuilding may happen later and be more dynamic (though at that point we'll probably have reworked the font loading API). I don't think the current API is very good tbh but for now the simplest is to persist your glyph range data during the lifetime of your fonts. We'll post here and in #2052 when this changes.
