### ISSUE TITLE
Help With Overlapped Widgets

### ISSUE THREAD

**Issue by AlexvZyl** [ocornut/imgui#5312]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Operating System: Windows 10 

**My Issue/Question:**

I am trying to create an overlay for my scene, as seen here.  Notice the button in the top left and the child in the bottom right.

![image](https://user-images.githubusercontent.com/81622310/168334831-86b7a041-efed-43aa-ab37-18408f719c7f.png)

I want the button to block events to the scene.  Basically, I just need to know if the texture is hovered and then I can respond accordingly.  I have tried the following:

```C++
// The image.
ImGui::Image(m_textureID, m_contentRegionSize, { 0, 1 }, { 1, 0 });
ImGui::SetItemAllowOverlap();
if (ImGui::IsItemHovered()) m_engine->m_isHovered = true;
else         	            m_engine->m_isHovered = false;

// I have drag and drop items here, if that might have an effect.

// The button.
ImGui::SetCursorPos(ImGui::GetWindowContentRegionMin());
ImGui::Button("Test");
ImGui::SetItemAllowOverlap();

// Render child here.
```

The child seems to be working correctly, but I suspect this has nothing to do with overlapping and just how children work in Dear ImGui.  `m_engine->m_isHovered` is being set to true, even if the button is being hovered.  Am I missing something?

**Comment by rokups** [comment]
You could try this:
```cpp
static ImDrawListSplitter splitter;
splitter.Split(ImGui::GetWindowDrawList(), 2);

// Render button first, however, put it to the top layer so it is rendered on top of viewport image.
splitter.SetCurrentChannel(ImGui::GetWindowDrawList(), 1);
if (ImGui::Button("Button"))
    printf("Button pressed\n");  // Interacting with the button will prevent interacting with the image.

// Render viewport image later, but it wont cover previously rendered button.
splitter.SetCurrentChannel(ImGui::GetWindowDrawList(), 0);
ImGui::SetCursorPos(ImGui::GetWindowContentRegionMin());
ImGui::Image(io.Fonts->TexID, ImVec2(200, 200));
if (ImGui::IsItemClicked())
    printf("Viewport pressed\n");

// Debug info: image is hovered when hovering "Button", but hovered state gets reset when "Button" is pressed down.
ImGui::Text("Viewport hovered: %d", ImGui::IsItemHovered());
splitter.Merge(ImGui::GetWindowDrawList());
```

**Comment by ocornut** [comment]
Hello,

This should now all be fixed by changes outlined here:

https://github.com/ocornut/imgui/issues/6512#issuecomment-1611369198

- `SetNextItemAllowOverlap()` works better.
- `IsItemHovered()` previously was never aware of it. It is now aware of it and it can be opted out with `ImGuiHoveredFlags_AllowWhenOverlappedByItem`.

Thanks for your patience.
