### ISSUE TITLE
Text Input

### ISSUE THREAD

**Issue by poppypoppop** [ocornut/imgui#532]
Hi. I am a student in Australia and I am using your library to create a game engine for my course. I have created a fly cam using GLFW and when I try to input text, it overrides your input and moves the camera. Is there anyway I can prevent this?

**Comment by poppypoppop** [comment]
I apologise if this is a little weird, I have just given up googling after several hours and my teachers are no help either :P

**Comment by Extrawurst** [comment]
Without a little code of what you are doing it is more than unlikely that someone will/can help you

**Comment by jethac** [comment]
As Omar says in the imgui readme, most of the documentation is the header file. Is there any reason why you couldn't check IsRootWindowOrAnyChildFocused() and disable input to your camera?

**Comment by ocornut** [comment]
Read the comments nearby the ImGuiIO structure.
You can check io.WantCaptureKeyboard after calling ImGui::Update() and hide the inputs from the rest of your app when true.

**Comment by ocornut** [comment]
This is a frequent question but it's also documented in the Programmer Guide in imgui.cpp and other places. I may add it to the FAQ.

**Comment by poppypoppop** [comment]
If you would like when I have free time I can go through your files and add doxygen to them so you have some online documentation

**Comment by ocornut** [comment]
Unfortunately that wouldn't be super useful and make the code way too noisy for what is a library that people need to read. 

There is already a plan for documentation discussed in #435 which we'll work on with a programmatic approach.

**Comment by poppypoppop** [comment]
ImGui Doesn't have ImGui::Update() :P Did you mean ImGui_ImplGlfwGL3_NewFrame();

**Comment by ocornut** [comment]
Sorry I meant NewFrame()

**Comment by poppypoppop** [comment]
No worries :) Just checking haha.
