### ISSUE TITLE
Undocking interrupts drag with ConfigDockingAlwaysTabBar enabled.

### ISSUE THREAD

**Issue by etkramer** [ocornut/imgui#5324]
**Version/Branch of Dear ImGui:**
Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_win32cpp + imgui_impl_dx12.cpp
Compiler: MSVC
Operating System: Windows 11

**My Issue/Question:**
With ConfigDockingAlwaysTabBar enabled, windows seem to "forget" that they're being dragged after undocking, and the user has to start a new drag in order to get it moving again.

**Screenshots/Video**

![10rVEcP9bn](https://user-images.githubusercontent.com/5407061/169191002-09868116-2c0f-430b-b6a6-7a92292a3137.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::GetIO().ConfigDockingAlwaysTabBar = true;
ImGui::Begin("Example Bug");
ImGui::End();
```

**Comment by ocornut** [comment]
Thanks for reporting!
Pushed a fix 36055213c544683fbd41fbbc06ff096dfe0a567e by @rokups.
