### ISSUE TITLE
Use imgui::image() to play video

### ISSUE THREAD

**Issue by mtosdjs** [ocornut/imgui#5326]
Platform: Linux-ubuntu
Backend: glfw+OpenGL3
branch：docking

![image](https://user-images.githubusercontent.com/104288199/169291514-5e58954f-8ffb-4270-851f-72470a56614c.png)

Hello, 
1. I use ImGui::Image() to display the video frame of glfw, but the window of glfw itself is still displayed together, how can I only display it in the ImGui tab
2. Another question, I want to play different videos in different imgui tabs, what method can I use? I tried to create multiple instances, but I found that the imgui tab in the newly created glfw window cannot be separated from the main viewport

Maybe I didn't find a way, hope I can get guidance

**Comment by ocornut** [comment]
It's hard to understand your messages. Please make an effort to clarify and reduce ambiguities then we can reopen this issue.

**Comment by mtosdjs** [comment]
![image](https://user-images.githubusercontent.com/104288199/169433318-8b5010c2-5fbc-4262-a55d-2452bf2a996d.png)
This is the glfw main viewport
![image](https://user-images.githubusercontent.com/104288199/169433405-dcc8abfa-1a1e-4031-8a05-6d489da14e2c.png)
This is the imgui tab

I want to switch the video played in the main viewport to the imgui tab to play, so I used ImGui::Image((GLuint *)(uintptr_t)texId, ImGui::GetContentRegionAvail()); to achieve this, but The current situation is that the main viewport and the imgui tab play the same video at the same time, how can I make the main viewport not play the video?

**Comment by rokups** [comment]
Video will play wherever you display an image.
1. Display `Image()` in the tab (i guess you know how to)
2. Display `Image()` in a borderless window that covers entire main viewport. I guess this is your issue.
  - Use `ImGuiWindowFlags_NoDecoration` flag and maybe `ImGuiWindowFlags_NoInputs` depending on your requirements.
  - Use `SetNextWindowPos()` + `SetNextWindowSize()` to make window cover size of main viewport, which you can get using `GetMainViewport()`.

**Comment by mtosdjs** [comment]
@rokups 
hello，
Thanks for your reply, I want to play different videos in multiple imgui tabs, but the second video cannot be played
![image](https://user-images.githubusercontent.com/104288199/169480364-c29834c2-9177-4a66-b388-cb5dd1a9a335.png)
