### ISSUE TITLE
how to set close button?

### ISSUE THREAD

**Issue by jinfagang** [ocornut/imgui#5327]
hi, I am currently got this:

<img width="569" alt="image" src="https://user-images.githubusercontent.com/21303438/169316902-72a43223-695c-463f-b5e9-0f7694caef54.png">

Does these old code can not be use anymore?

**Comment by ocornut** [comment]
See 1.60 changelog:
https://github.com/ocornut/imgui/releases/v1.60
"Removed ImGuiCol_CloseButton, ImGuiCol_CloseButtonActive, ImGuiCol_CloseButtonHovered style colors as the closing cross uses regular button colors now."

Always search in "API BREAKING CHANGES" section of imgui.cpp and Changelog when you have a compile regression.

**Comment by jinfagang** [comment]
thanks, then How can I enable such close button (without a black cross, but just a white circle)
