### ISSUE TITLE
After creating multiple glfw windows by instance, imgui detaching from main viewport has no effect

### ISSUE THREAD

**Issue by mtosdjs** [ocornut/imgui#5329]
Platform: Linux-ubuntu
Backend: glfw+OpenGL3
branch：docking
![image](https://user-images.githubusercontent.com/104288199/169442457-caa31ff6-a9b0-4738-98bb-3ac0472b1ef4.png)

Hello, I create multiple instances by means of C++ classes, but starting from the second instance, the way imgui is separated from the main viewport is invalid

```
    RenderScene *scene = NULL;
    scene = new RenderScene();
    scene->sciter_opengl_init();

    RenderScene *scene1 = NULL;
    scene1 = new RenderScene();
    scene1->sciter_opengl_init();
    while(1){
        scene->Main_loop(NULL);
        scene1->Main_loop(NULL);
    }
```

**Comment by rokups** [comment]
Dear ImGui does not support multiple main viewports at this time. Instead of creating secondary windows yourself you may simulate this behavior by creating imgui windows with OS decorations and requesting them to not be merged into main viewport.
```cpp
io.ConfigViewportsNoDecoration = false;  // Always use OS decorations for viewport windows

// <...>

ImGuiWindowClass cls;
cls.ViewportFlagsOverrideSet = ImGuiViewportFlags_NoAutoMerge;  // Always create outside of main viewport
ImGui::SetNextWindowClass(&cls);
ImGui::Begin(..., ImGuiWindowFlags_NoDecoration);  // No standard decorations, since OS provides them
// Your second native window content
ImGui::End();
```

**Comment by mtosdjs** [comment]
thank you for your reply

**Comment by mtosdjs** [comment]
How can I make the image fill the entire imgui tab, as shown in the figure below, there will be a circle of blue boxes
![image](https://user-images.githubusercontent.com/104288199/169480817-efd4def0-1356-474d-94a1-1785430e69c4.png)

**Comment by rokups** [comment]
```cpp
ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 0));
ImGui::Begin(...);
// ...
ImGui::End();
ImGui::PopStyleVar();
```

**Comment by mtosdjs** [comment]
thank you very much

**Comment by ocornut** [comment]
> Dear ImGui does not support multiple main viewports at this time.

I'm not sure how the question can be answered since the question is ambiguous in about one millions ways.
It seems like they suggest they have multiple dear imgui contexts in which case it should be possible, but right now we are shooting in the dark given how little information the question provide. @mtosdjs please read the Glossary (https://github.com/ocornut/imgui/wiki/Glossary) and read Issues Guidelines next time ask you have question.
