### ISSUE TITLE
Don't CaptureMouseFromApp()

### ISSUE THREAD

**Issue by dkrikun** [ocornut/imgui#533]
I have a small scene to render *inside* imgui window. So I am rendering it to a texture and then displaying it in an image (as you've recommended in #530), and everything works great.

The problem is, I would like imgui NOT to handle mouse events when the focus is inside my image.
But `CaptureMouseFromApp()` only allows to force capture the input.

**Comment by nem0** [comment]
Does #532 help?

**Comment by ocornut** [comment]
What does "NOT to handle mouse events" means?
Do you want to prevent the window from being moved?
If you want just want your application to use mouse inputs, then just ignore the WantCaptureMouse flag.

**Comment by dkrikun** [comment]
You say in #532:

> You can check io.WantCaptureKeyboard after calling ImGui::Update() and hide the inputs from the rest of your app when true.

I would like to achieve exactly the opposite: to hide the inputs from ImGui. Ok, you could say, I have the control over the `ImGui::GetIO() ` etc., but this is global.

Yeah, I would like to prevent the window from moving and scrolling, and instead let the "inner" scene to handle mouse events.

**Comment by ocornut** [comment]
Clicking an Image() shouldn't move the window. You can disable mouse wheel scrolling with a flag in Begin or BeginChild.
Just test for IsItemHovered(), set your own flag and test this flag in your code that checks WantCapture* flags.

**Comment by ocornut** [comment]
You don't need to hide the input from ImGui, you need your application to read the inputs.
Clicking an Image() shouldn't move the window. You can disable mouse wheel scrolling with a flag in Begin or BeginChild.

Just test for IsItemHovered(), set your own flag and test this flag in your code that checks WantCapture* flags to accept the inputs when set.

**Comment by dkrikun** [comment]
I think it does move the window, I'll check it.

**Comment by dkrikun** [comment]
Dragging the image moves the window that contains it

**Comment by ocornut** [comment]
Use ImageButton()

**Comment by ocornut** [comment]
@dkrikun I have added a bool parameter to CaptureKeyboardFromApp() and CaptureKeyboardFromApp() so that may be used to easily communicate the information down to the main code.

The demo code does:
```
            ImGui::Button("Holding me clears the\nthe keyboard capture flag");
            if (ImGui::IsItemActive())
                ImGui::CaptureKeyboardFromApp(false);
```

I also tested that you can use ImageButton() or InvisibleButton() to prevent moving the window. Let me know if that works for you!

**Comment by dkrikun** [comment]
Thanks :)
