### ISSUE TITLE
Segfault upon free-ing loaded font from memory

### ISSUE THREAD

**Issue by ibldzn** [ocornut/imgui#5330]
```
Dear ImGui 1.88 WIP (18722)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1932
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

I made a cpp file containing the raw bytes of my font using `xxd -i`, add it to my source list on cmake, do
```c++
...
ImGuiIO& io = ImGui::GetIO();
extern unsigned char notosans[];
extern unsigned int notosans_size;
io.Fonts->AddFontFromMemoryTTF(notosans, notosans_size, 16.f);
...
```

then upon exiting the program, it segfaults, happens on both windows 10 iot ltsc and arch linux. on windows I got 7 error message box, saying heap corruption detected. [the relevant(?) part](https://imgur.com/a/t5MehD7)

**Screenshots/Video**

<details>
  <summary>Screenshot of where it crashed</summary>
  <img src="https://i.imgur.com/uJ2UAeF.png" alt="Screenshot" />
</details>

<details>
  <summary>Callstack</summary>
  <img src="https://i.imgur.com/55SWfyj.png" alt="Callstack" />
</details>

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

copy and paste the opengl glfw3 example, then right below the `ImGuiIO& io = ImGui::GetIO();` line add this:
```c++
extern unsigned char notosans[];
extern unsigned int notosans_size;
io.Fonts->AddFontFromMemoryTTF(notosans, notosans_size, 16.f);
```
[notosanscjk-bold.zip](https://github.com/ocornut/imgui/files/8747261/notosanscjk-bold.zip)

**Comment by mnesarco** [comment]
As your data is static, you need to instruct ImGui to not take ownership of it:

```cpp
    ImWchar ranges[] = { StartCode , EndCode, 0 };
    ImFontConfig dconf;
    dconf.FontDataOwnedByAtlas = false; // <------ THIS IS THE TRICK
    io.Fonts->AddFontFromMemoryTTF(data, data_size, font_size, &dconf, ranges);

```
This is my font loading code: https://github.com/mnesarco/bawr/blob/main/examples/build/my-icons_loader.hpp

**Comment by ibldzn** [comment]
that fixed it! thank you very much
