### ISSUE TITLE
DPI Scaling

### ISSUE THREAD

**Issue by LedLoaf** [ocornut/imgui#5332]
Hello,

So I have a 17" Game Laptop that does 4K resolution. I'm trying out someones software called RPG-TOOLS and it uses imgui. Long story short, the font is so small it's impossible to see. I was wondering if you can edit the imgui config file to fix this without waiting for them to solve the issue? If I set the software executable to use DPI system it looks great, but the rest of it is cut off.

I could solve this myself by just lowering my resolution, but that's such a huge inconvenience in requiring a restart ect. So can this be edited on my side at all?

Thanks

**Comment by ocornut** [comment]
See FAQ entry
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-should-i-handle-dpi-in-my-application
