### ISSUE TITLE
I Can't Type Or Show Persian Words

### ISSUE THREAD

**Issue by azadybashar** [ocornut/imgui#534]
Hi
I have a big problem in typing persian words in Imgui inputs
and have problem in showing persian text in imgui textboxes
I changed my font but my problem is still a live
please help me.
thanks

**Comment by ocornut** [comment]
Unfortunately right-to-left text display isn't supported and probably won't be supported in ImGui.
I once gave it a look but it would have very large effects on the design and performance of the code to the point that a lot of the library purpose of quick and lightweight debugging would be defeated.

Sorry :(

**Comment by azadybashar** [comment]
how to write persian words?
yeah there is not way for right to left

**Comment by azadybashar** [comment]
excuse me for my poor english
can you say me some libs like imgui to support persian with directx 9

**Comment by ocornut** [comment]
You can input any Unicode character via your usual input method (keyboard) but ImGui cannot display them. Text shaping required by persian/arabic scripts isn't even supported.

I don't know myself about the other libraries, sorry.

**Comment by ocornut** [comment]
Because ImGui is designed to create tools for developers, the limitation usually aren't a big problem.
Of course it isn't an ideal situation, but it is unrealistic to support full Unicode internalisation in ImGui.

**Comment by MrModarator** [comment]
Hi tnx for your great work,
I need a arabic fonts to be suported...
:(

**Comment by ocornut** [comment]
Sorry it is way to much work for me and in a way that can be kept optimal.
