### ISSUE TITLE
Question: Is there a Graphic Eq graph plot component available?

### ISSUE THREAD

**Issue by monteoma** [ocornut/imgui#5341]
I am newbie on ImGui and I am trying to create an editor for a digital Graphic Eq and would like to have the standard frequency graph as a visual display. I would like to input centre frequency, Q and Gain (+/- dB) of filters and have a component draw the graph for me.
I would like so when I changed a value (Freq/Q/gain) the graph would redraw/update in real-time.
Something like this..

![image](https://user-images.githubusercontent.com/71559595/169851923-796c9c4c-2aa4-4e07-be87-f58392b7a824.png)

Does anyone know how to achieve this?

Thanks!

**Comment by ocornut** [comment]
The wiki has a list of known widgets/librairies. If its not on the wiki we don’t know about one.
