### ISSUE TITLE
List Box invisible after clicking on buttons

### ISSUE THREAD

**Issue by CODE-Yasser** [ocornut/imgui#5345]

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited. Do NOT open a new issue.

Closing.

**Comment by CODE-Yasser** [comment]
ye i found the problem thanks anyway mr.omar
