### ISSUE TITLE
Font failed to load

### ISSUE THREAD

**Issue by MasonJohnHawver42** [ocornut/imgui#5349]
![image](https://user-images.githubusercontent.com/33504840/170367914-c6547737-799c-4bb6-8a13-15a36846797d.png)

I ran your code the font was fine. I ported it over to my C++ project with raylib 4.0, and raylib is unable to load the image data generated from cimgui. How can I load raylibs default font into this.

I have already tried:
`Font font = GetFontDefault();

  Image font_image = LoadImageFromMemory(".png", pixels, width * height);
  Texture2D font_texture = font.texture;
  io->Fonts->TexID = (void *)&font.texture.id;`

**Comment by ocornut** [comment]
This appears to be an issue with your use of non-dear imgui code, best to ask on raylib support channels (although afaik raylib has a dear imgui backend). Seems strange to pass a “.png” string to load raw pixels.

**Comment by MasonJohnHawver42** [comment]
hey sorry wrong repo
