### ISSUE TITLE
Error in features/premake5

### ISSUE THREAD

**Issue by ploirliu** [ocornut/imgui#5352]
when run premake in feature/premake5, it generator vs solution

get error in example_glfw_opengl3,show as bellow
“..\libs\gl3w\GL\gl3w.c”: No such file or directory

it seems shuld remove something in example/premake5.lua

remove "libs/gl3w/GL/gl3w.c" in line 201 and 271 works fine for me

**Comment by ocornut** [comment]
Thank you, I have updated the branch without those.
