### ISSUE TITLE
Viewport causing crash with resize in example_glfw_opengl3 + possible memory leak

### ISSUE THREAD

**Issue by dgm3333** [ocornut/imgui#5354]
Using the latest docker branch (downloaded this morning although same error on older ones)
Randomly on resizing a child viewport window which is outside the bounds of the main window it crashes the program.

Using win10, 4k dual monitors
CPU: AMD Ryzen 9
GPU: AMD Radeon RX 5700 XT

To replicate
compile a vanilla version of example_glfw_opengl3
(either Release or Debug as happens with both) 
As per pic below: Drag the child somewhere outside the boundary of the main window (I haven't managed to get it to to crash while borders of the child remain inside the boundary of the main window)
Grab the "Dear ImGui Demo" or "Hello, world!" window resize triangle (bottom RHS) and just drag it around for a while
At some point after a second or so it crashes (I haven't giffed as it literally just stops)...

Also possible memory leak:
If I repeatedly drag the child out of the main window and drop it then back in and drop it I get this memory consumption (each step up is a new drop outside of the main - but the memory doesn't seem to be released when the window is dropped back inside the main)
If I stop dragging and dropping it then it settles but not by much
![image](https://user-images.githubusercontent.com/51210/170819217-b772d31c-8049-4b3e-a1c1-2fbc40e5ff65.png)

These are the screens of the main drag and drop crash:-
![image](https://user-images.githubusercontent.com/51210/170819078-1230bce8-d63e-4388-abab-b243efd81f12.png)

![image](https://user-images.githubusercontent.com/51210/170818794-8093d509-83c2-4579-b840-aa3bff6dd20b.png)

**Comment by dgm3333** [comment]
Sorry but it doesn't seem to have worked
The identical action (dragging and dropping Hello, World! in and out) still has a large memory consumption profile (which even beyond a minute of leaving it running with the child sitting in the main window is never released):

![image](https://user-images.githubusercontent.com/51210/171102762-db59543d-0b91-48a9-a1bb-cfc1a7191f98.png)

**Comment by rokups** [comment]
Crash happens in atio6axx.dll, this DLL comes with AMD graphics driver. Similar crash is reported [here](https://community.amd.com/t5/drivers-software/amd-driver-problem/td-p/474097) (suggests uninstalling "AMD Adrenalin Software"). In general "atio6axx.dll crash" query on a search engine returns plenty of results. Looks like AMD software is quite buggy. See if you can disable any invasive features in Radeon Software (any kind of overlays and similar).

**Comment by dgm3333** [comment]
Woah, I don't think I've ever seen so many expletives in such close proximity to ANY word on the internet as nahimic - any systemware where "malware" is one of the NICE things that people say about it has got to raise questions...
So I'm not even going to ask what the heck a piece of audio software is doing jamming itself into a graphics process...
Anyway it doesn't have an uinnstall option, so after killing the 6 running instances (2x64bit, 2x32 bit and a couple of services.) And deleting as many files as windows administrator priviledges would allow me to remove (not all of them :-(  ) I tried again.

Memory consumption is now less than the previous baseline and DROPS (!!!) with resizing and drag/dropping.
I couldn't get the example to crash either...
So I think your piece of s*** comment (now mysteriously vanished) is pretty appropriate...
[sadly various sites say that Nahimic keeps reinstalling itself so I might have to find an anti-nahimic service to keep it off my computer]

![image](https://user-images.githubusercontent.com/51210/171261540-5b6d76cc-d06b-4818-b11f-a93fea011c88.png)
