### ISSUE TITLE
Distinguish TreeNode arrow click from generic item click

### ISSUE THREAD

**Issue by eugeneko** [ocornut/imgui#5356]
**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: docking

**My Issue/Question:**

I am using TreeNode API and I would like to implement fairly common behaviour for my tree.
I want to have item *selected* when I click the item itself, and I want item to expand *without selection* if I click arrow specifically. Windows Explorer works this way, Unity hierarchy window works this way, etc.

So, basically, I need a way to distinguish arrow clicks from all other clicks.
ImGUI obviosuly already have a code that does it, but the result is not exposed publicly.

I propose to have query API similar to `IsItemHovered` or `IsItemClicked`, except it would be `IsTreeNodeArrowClicked` or `IsTreeNodeArrowHovered` or something like this. I would be able to call it after `TreeNode` and implement my custom behaviors differently.

@rokups, @gleblebedev

**Comment by ocornut** [comment]
See the demo section that has this comment:
“ To alter selection we use IsItemClicked() && !IsItemToggledOpen(), so clicking on an arrow doesn't alter selection.”

**Comment by eugeneko** [comment]
Now I feel dumb xD
I didn't even think to look at this problem this way.
Thank you.

**Comment by ocornut** [comment]
I agree it’s not obvious, so the more references/links we have the better.
