### ISSUE TITLE
Textbox/text inputs randomly freezes whole application

### ISSUE THREAD

**Issue by Rex109** [ocornut/imgui#5357]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Operating System: Windows 10

**My Issue/Question:**

ImGui 1.87 seems to **randomly** freeze the whole game just as i click on a textbox and/or an editable text field. The result is not consistent and seems to be related to 1.87 as 1.86 does not cause this problem. I've looked though the new 1.87 changelog and i see you guys reworked the IO API, maybe the problem is related to that?

**Screenshots/Video**

https://user-images.githubusercontent.com/8615649/170886244-41ab10cb-0dad-446a-a684-7ac501c97641.mp4

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/Rex109/D3D9-Hook-CoD4-Velometer/releases/tag/1.6.1)_

**Comment by ocornut** [comment]
Sorry that doesn't constitute a minimal and verifiable example. 
The issue is most certainly on your side, so without a minimal and verified example we can't look at it.

**Comment by Rex109** [comment]
> Sorry that doesn't constitute a minimal and verifiable example. The issue is most certainly on your side, so without a minimal and verified example we can't look at it.

Unfortunately i can only post a medium sized example since i honestly don't know where the problem is, let me know if i can post it. Plus it seems that the issue can be fixed temporarly on the game by disabling the render on a separate thread (i repeat: the issue only shows up in 1.87, not even older releases like 1.67).

**Comment by ocornut** [comment]
The point is converging toward a minimal example is to narrow things down, only you can do that.
