### ISSUE TITLE
How to make thecontent of ImGui::ImageButton() is displayed on top of the content of ImGui::Image()

### ISSUE THREAD

**Issue by mtosdjs** [ocornut/imgui#5358]
Platform: Linux-ubuntu
Backend: glfw+OpenGL3
branch：docking

In a tab created by ImGui::Begin(),
How to make thecontent of ImGui::ImageButton() is displayed on top of the content of ImGui::Image()
I try， but it will be displayed in two parts, as shown in the picture below.
```
        ImGui::Begin();
        ImGui::Image();
        ImGui::ImageButton()
```
![image](https://user-images.githubusercontent.com/104288199/170973072-313b223d-2063-4af2-8506-8fdd3b203421.png)

**Comment by ocornut** [comment]
Use GetCursorScreenPos() to backup a position and SetCursorScreenPos() to restore it.
