### ISSUE TITLE
Multiple different inputs are being selected and edited at the same time

### ISSUE THREAD

**Issue by AlexGomezCortes** [ocornut/imgui#5360]
### Docking branch (but I recall having this issue some years ago as well, using the main branch).

VS compiler

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Windows

**Multiple inputs are being selected and edited at the same time**

First of all, thank you a lot for your time :). I have a vector of (pair <string, std::any>) and I am iterating it in order to draw some inputs (text, float, int, vec3, etc.), and when I try to edit one of them, every of the inputs drawn is selected and edited.

![1](https://user-images.githubusercontent.com/25607313/171253677-d47f193f-9ef0-4d21-99c4-20a884366d45.png)

This is how it looks when I do not interact with it:

![2](https://user-images.githubusercontent.com/25607313/171253753-1ed93cf0-15cc-4e20-b256-f0f6b382f77a.png)
![3](https://user-images.githubusercontent.com/25607313/171253772-8cf6e73a-9f99-421a-af8d-d84c6baef03d.png)

**Code of the loop** 

// Here's some code anyone can copy and paste to reproduce your issue
```
for (auto& uniform : uniforms)
	{
		ImGui::SetNextItemWidth(ImGui::GetWindowWidth() / 4.0f);
		ImGui::InputText("", &uniform.first);
		ImGui::SameLine();
		
		if (uniform.second.type() == typeid(int))
		{
			auto& val = std::any_cast<int&>(uniform.second);
			ImGui::InputInt("Value", &val);
			continue;
		}

		if (uniform.second.type() == typeid(float))
		{
			auto& val = std::any_cast<float&>(uniform.second);
			ImGui::InputFloat("Value", &val);
			continue;
		}

		if (uniform.second.type() == typeid(glm::vec4))
		{
			auto& val = std::any_cast<glm::vec4&>(uniform.second);
			ImGui::InputFloat4("Value", &(val.x));
			continue;
		}

		if (uniform.second.type() == typeid(glm::vec3))
		{
			auto& val = std::any_cast<glm::vec3&>(uniform.second);
			ImGui::InputFloat3("Value", &(val.x));
			continue;
		}

		if (uniform.second.type() == typeid(glm::vec2))
		{
			auto& val = std::any_cast<glm::vec2&>(uniform.second);
			ImGui::InputFloat2("Value", &(val.x));
			continue;
		}
	}
```

**Comment by PathogenDavid** [comment]
You have a widget ID collision. [See this FAQ entry for details](https://github.com/ocornut/imgui/blob/74f7ac04a166c77ef1cbbbebff51e5bfc4fcfa5d/docs/FAQ.md#q-about-the-id-stack-system).

**Comment by ocornut** [comment]
You'll probably want to use `PushID()/PopID()` in each loop iteration with the uniform name there (or index if you don't have a name).

**Comment by AlexGomezCortes** [comment]
> Thanks for the detailed report and for filling out the template!
> 
> You have a widget ID collision, [see this FAQ entry for details](https://github.com/ocornut/imgui/blob/74f7ac04a166c77ef1cbbbebff51e5bfc4fcfa5d/docs/FAQ.md#q-about-the-id-stack-system).

Thank you for the info!:) I proceeded with what Omar told me on the next comment!
