### ISSUE TITLE
Can't write a value (ctrl + click) in any control (textbox, dragfloat, slider...)

### ISSUE THREAD

**Issue by Ar-Ess** [ocornut/imgui#5364]
**Version/Branch of Dear ImGui:**
Version: v1.87
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl.cpp
Operating System: Windows 10

**My Issue/Question:**

I am trying to overwrite the value of an ImGui::DragFloat(), but when double-clicking it and trying to type in, it won't add any number.
It happens as well with any other control related to typing, such as textbox or text inputs.
In the "ImGui::ShowExampleWindow()", in the input/navigation part, it detects the keyboard and the input of the specific key, but it does not write anything when I try to write in an ImGui::DragFloat().

![Captura](https://user-images.githubusercontent.com/20298478/171291621-311595bd-e56c-4261-b70d-1602ae61e69f.JPG)

**Comment by ocornut** [comment]
It might be that you have an ID Stack conflict if you call Draw() multiple times, have you [Read the FAQ](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system)?
Closing in the absence of proper details.

**Comment by ocornut** [comment]
You are recreating your items every frame and not persisting anything so of course their value won’t persist over frames.

Try to get toward an actual repro this is usually the best way to find your issue.

**Comment by Ar-Ess** [comment]
I'm aware of that, and that's why I sayd that the error is independent of that.
My problem is not that the value does not persist over the frames, my problem is that when I try to write a value on
the DragFloat by doubleclicking it, it does not write anything. When I press the Key "1", "2", "3", "4", "A", "B"... on my keyboard, it is not writting anything.

In this code, what is suposed to happen is that by doubleclicking the dragsfloat, ImGui detects when I press a number key and writes in the dragfloat. Then, when I pres RETURN, it should change the value and then return to 0 because I am initializing the variable each frame.

But the problem is that it does not type the number actually in the DragFloat, I cant type "3450.34" (for example) in it.
The example code I show to you is initializing the variables each frame, but in my code it is not. That variables are initialized in a "Start()" function and are not overwrited anymore, and it keeps happening the same.

Try this code, it should recreate my code:

        // Example code to reproduce what's happenning
	// Summarizing "recipients" is a vector<> of "Recipient" struct
        struct Recipientt
        {
	float money = 0;
	const char* name = "New";
	//Draw function showed in the screenshot
	void Draw()
	{

		ImGui::Text(name); ImGui::SameLine();
		ImGui::Text(":"); ImGui::SameLine();
		ImGui::PushItemWidth(150.0f);
		ImGui::DragFloat("##Drag", &money, 1.0f, 0.0f, 340282000000000000000000000000000000000.0f, "%.2f EUR");
		ImGui::PopItemWidth();
	}

    };

    std::vector<Recipientt*> recipientss;
	recipientss.push_back(new Recipientt());
	recipientss.push_back(new Recipientt());
	recipientss.push_back(new Recipientt());

    while (true) // Main loop
    {

    if (ImGui::Begin("Main", nullptr, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | 
    ImGuiWindowFlags_NoTitleBar))
    {

	size_t size = recipientss.size();
	int i = 0;
	for (std::vector<Recipientt*>::const_iterator it = recipientss.begin(); it != recipientss.end(); ++it)
	{
		Recipientt* r = (*it);
		bool reordered = false;
		ImGui::PushID(i);

		if (ImGui::TreeNodeEx("   ", ImGuiTreeNodeFlags_DefaultOpen | ImGuiTreeNodeFlags_FramePadding))
		{
			r->Draw();

			ImGui::TreePop();
		}

		ImGui::PopID();

		++i;
		if (reordered) break;
	}

	ImGui::End();
    }
    }

This is exactly what is happening in my program but summarized.

**Comment by Ar-Ess** [comment]
Maybe it is meaningfull to say that I have a input system running apart from ImGui's one using SDL. I don't know whether this could generate any conflict not allowing me to type in any widget of ImGui's library...

**Comment by ocornut** [comment]
This is exactly why you should test your repro in eg a standalone imgui example. You should also be able to confirm whether the repro actually exhibit the problem
or is just a guess.

**Comment by Ar-Ess** [comment]
Okey, you're totally right. I'll try that on my own and I'll get back to you if I have new information.
Thanks so much for the help and guidance!
