### ISSUE TITLE
Is there a way to set different text colors for active and inactive tabs?

### ISSUE THREAD

**Issue by GasimGasimzada** [ocornut/imgui#5368]
**Version/Branch of Dear ImGui:**

Version: v1.87
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom render backend + Imgui GLFW window
Compiler: MVSC
Operating System: Windows

**My Issue/Question:**

I would like to change the **text** color of a tab and identify tabs using font color instead of background color. Is that possible to do/

**Comment by GasimGasimzada** [comment]
@PathogenDavid Could you please explain how the first example works? I have tabs defined in the following way:

```cpp
if (ImGui::BeginTabBar("inspector-tabs")) {
  if (ImGui::BeginTabItem("Entity")) {

  }

  if (ImGui::BeginTabItem("Environment")) {

  }

  ImGui::EndTabBar();
}
```

How would this work? Do you basically manage the active state of the tab manually?

```cpp
if (tabActive == "Entity") {
  // red
  ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1, 0, 0, 1));
} else {
  // blue
  ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(0, 0, 1, 1));
}
if (ImGui::BeginTabItem("Entity")) {
  tabActive = "Entity";
}

ImGui::PopStyleColor();

if (tabActive == "Environment") {
  // red
  ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1, 0, 0, 1));
} else {
  // blue
  ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(0, 0, 1, 1));
}
if (ImGui::BeginTabItem("Environment")) {
  tabActive = "Environment";
}

ImGui::PopStyleColor();
```

**Comment by PathogenDavid** [comment]
Oh, normal tab bars are slightly different. I thought you were referring to the window tabs since you're on the docking branch. (This is part of why we ask you to share a snippet of code in the issue template, BTW.)

You don't need to manage the active state manually, but you do need to keep track of it.

For normal tab bars I'd declare a helper similar to this:

```cpp
bool MyBeginTabItem(const char* label, ImGuiID* active_tab, bool* p_open = nullptr, ImGuiTabItemFlags flags = 0)
{
    ImGuiID id = ImGui::GetID(label);
    bool wasActive = *active_tab == id;

    if (!wasActive)
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1, 0, 0, 1));

    bool isActive = ImGui::BeginTabItem(label, p_open, flags);

    if (!wasActive)
        ImGui::PopStyleColor();

    if (isActive)
        *active_tab = id;

    return isActive;
}
```

Using it would look something like this:

```cpp
static ImGuiID activeInspectorTab;
if (ImGui::BeginTabBar("inspector-tabs")) {
    if (MyBeginTabItem("Entity", &activeInspectorTab)) {
        ImGui::Text("Hello, entity!");
        ImGui::EndTabItem();
    }

    if (MyBeginTabItem("Environment", &activeInspectorTab)) {
        ImGui::Text("Hello, environment!");
        ImGui::EndTabItem();
    }

    ImGui::EndTabBar();
}
```

(As with windows, you can simplify things and eliminate the `activeInspectorTab` variable if you're willing to poke at internals, although it's slightly more involved.)
