### ISSUE TITLE
SliderFloat - How to avoid strict bounding

### ISSUE THREAD

**Issue by vd3d** [ocornut/imgui#537]
Hi,

I use a SliderFloat, but the value that I use can be out of the [min, max]. It is expected.

Is there a way to avoid that SliderFloat resets my value to min or max when it is not due to a change by playing with this widget ?

Example :
```
float value = 150;
ImGui::SliderFloat("test", &value, 0, 100);

>>> Here value should remain = 150 !
```

Thanks

**Comment by ocornut** [comment]
I'm not sure what you are saying, it is already the case.
SliderFloat() and all widgets do not modify your value unless you interact with the widget.
What is the problem?

```
	float f = 150.0f;
	ImGui::SliderFloat("test", &f, 0, 100);
	ImGui::Text("output: %f", f);
```

![capture](https://cloud.githubusercontent.com/assets/8225057/13319720/052acaba-dbc4-11e5-9850-33c977ab9fd3.PNG)

**Comment by vd3d** [comment]
Ok, so for sure it is a bug on our side ! Sorry !
