### ISSUE TITLE
ImGUI linking error.

### ISSUE THREAD

**Issue by MrWeiShanxiang** [ocornut/imgui#5375]
(Click "Preview" above ^ to turn URL into clickable links)

1. FOR FIRST-TIME USERS ISSUES COMPILING/LINKING/RUNNING or LOADING FONTS,  please use [GitHub Discussions](https://github.com/ocornut/imgui/discussions).

2. PLEASE CAREFULLY READ: [FAQ](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md)

3. PLEASE CAREFULLY READ: [Contributing Guidelines](https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md)

4. PLEASE MAKE SURE that you have: read the FAQ; explored the contents of `ShowDemoWindow()` including the Examples menu; searched among Issues; used your IDE to search for keywords in all sources and text files; and read the links above.

5. Be mindful that messages are being sent to the e-mail box of "Watching" users. Try to proof-read your messages before sending them. Edits are not seen by those users.

6. Delete points 1-6 and PLEASE FILL THE TEMPLATE BELOW before submitting your issue.

Thank you!

----

Version: v1.87
Branch: docking

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: VS 2020
Operating System: Windows 10

**My Issue/Question:**
Why does ImGUI docking branch show symbols not resolved when I build my own project?

**Screenshots/Video**
![Error](https://user-images.githubusercontent.com/88918065/172038262-836d37e6-a54e-489b-a160-1526a11ad039.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```C++
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
static int y;
ImGui::SliderInt("Set window position", &y, 0, 1080);
glfwSetWindowPos(window, 0, y);
ImGui::End();
```

**Comment by ocornut** [comment]
Because you are not linking the object files containing those symbols. The error says what it says.
