### ISSUE TITLE
Add support for dx8/d3d8

### ISSUE THREAD

**Issue by KsaNL** [ocornut/imgui#5379]
I tried to make dx8 backend for imgui,and half done.
Not sure why render crash while 2 window exist at the same time.
Here is my code and the image.
![image](https://user-images.githubusercontent.com/73447685/172144442-5c6e44ed-576c-4db8-8b63-11223840a1e8.png)

Maybe here can be replace but i am not sure.
![image](https://user-images.githubusercontent.com/73447685/172144484-97fa55d6-8d52-4b84-8330-a6bea4b11174.png)
[example_win32_directx8.zip](https://github.com/ocornut/imgui/files/8843773/example_win32_directx8.zip)
[Microsoft DirectX 8.1 SDK Lite.zip](https://github.com/ocornut/imgui/files/8843774/Microsoft.DirectX.8.1.SDK.zip)

**Comment by KsaNL** [comment]
Here is the lib with debug info. The dx8 not support at x64platform.
[Microsoft DirectX 8.1 SDK Lib.zip](https://github.com/ocornut/imgui/files/8849468/Microsoft.DirectX.8.1.SDK.Lib.zip)
This image shows the prob i mentioned last post.
![JXGS2_E`_0JRA3 7UL)R_3](https://user-images.githubusercontent.com/73447685/172279763-64995c8d-5703-43ed-9856-0d5ee25d8ff8.png)

**Comment by KsaNL** [comment]
Microsoft DirectX 8.1B Complete SDK, 
if you should debug, 
download this you will feel a little different to dx9

Add Environment Variable $(DXSDK_81) 
C:\Program Files (x86)\Microsoft DirectX 8.1 SDK\
[Microsoft DirectX 8.1 SDK.rar](https://lanzoux.com/i27CS060hhof)

**Comment by KsaNL** [comment]
d3d8 wndproc need add 

case WM_PAINT:
        //Render(); ?
        ValidateRect(hWnd, NULL);
        return 0;

**Comment by KsaNL** [comment]
Other trouble were found, no solution yet.

OutofRange
![OutofRange](https://user-images.githubusercontent.com/73447685/172320916-079a9f07-0b4b-4220-b3a2-aa1902849824.png)
The help maker is the multi window as well.
![CoverHelperMaker](https://user-images.githubusercontent.com/73447685/172320922-cfc4f387-c5c5-4644-8677-fb60360914ae.png)

**Comment by ocornut** [comment]
Hello,

Hopefully you’ll get it solved soon. If you get a working DX8 backend please host it in a github repo (as eg: imgui_impl_dx8.cpp) and we’re link to it. 

However please be mindful this place is not a chat room, please refrain from posting too often as your messages are landing in people inbox.

cheers

**Comment by KsaNL** [comment]
Here backends with source, have uploaded yesterday.
[example_win32_directx8.zip](https://github.com/ocornut/imgui/files/8843773/example_win32_directx8.zip)

I won't reply still i solve this. cheers.

**Comment by dhanax26** [comment]
> Other trouble were found, no solution yet.
> 
> OutofRange ![OutofRange](https://user-images.githubusercontent.com/73447685/172320916-079a9f07-0b4b-4220-b3a2-aa1902849824.png) The help maker is the multi window as well. ![CoverHelperMaker](https://user-images.githubusercontent.com/73447685/172320922-cfc4f387-c5c5-4644-8677-fb60360914ae.png)
can be fixed adding the following pieces of code for creating/capturing/deleting the state block of d3d8

`
    bd->pd3dDevice->CaptureStateBlock(d3d8_state_block);
    if (bd->pd3dDevice->CaptureStateBlock(d3d8_state_block) < 0)
    {
        bd->pd3dDevice->DeleteStateBlock(d3d8_state_block);
        return;
    }

and at the end of ImGui_ImplDX8_RenderDrawData

    bd->pd3dDevice->ApplyStateBlock(d3d8_state_block);
    bd->pd3dDevice->DeleteStateBlock(d3d8_state_block);
`
