### ISSUE TITLE
Backends: Win32: Why are we updating mouse cursor here?

### ISSUE THREAD

**Issue by zaafar** [ocornut/imgui#5390]
Hi Omar,

I was reading the code of [imgui_impl_win32](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_win32.cpp) file and I couldn't understand why we are calling `ImGui_ImplWin32_UpdateMouseCursor` at newframe time (https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_win32.cpp#L359) when it's already being called here (https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_win32.cpp#L620). I did try commenting out the following lines and executing the code and it had no impact on mouse icon (with or without "MouseDrawCursor" flag). I am pretty sure I am missing something obvious so please help me try to understand the logic behind this. thanks!

```
// Update OS mouse cursor with the cursor requested by imgui
    ImGuiMouseCursor mouse_cursor = io.MouseDrawCursor ? ImGuiMouseCursor_None : ImGui::GetMouseCursor();
    if (bd->LastMouseCursor != mouse_cursor)
    {
        bd->LastMouseCursor = mouse_cursor;
        ImGui_ImplWin32_UpdateMouseCursor();
    }
```

**Comment by ocornut** [comment]
`WM_SETCURSOR` is called when Windows notice mouse is moving back from decoration area into client area whereas the other is called for our own cursor change and need to be done every frame.

If you comment the `WM_SETCURSOR` section you'll notice hovering on e.g. win32 resize decoration has windows switch to resize cursor but then the regular cursor is not restored when moving over client area.

**Comment by zaafar** [comment]
Thank you for the quick reply!!!

Would hovering over the following area of ImGui demo window be considered as `for our own cursor change`? I am asking this because `WM_SETCURSOR` is called when I hover it. Also, commenting out this block of code have no impact on mouse-icon-change (https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_win32.cpp#L359).

![mouse_hover_image](https://user-images.githubusercontent.com/5079646/173340888-4cd533f8-a93e-4b60-a702-e32378b51e43.png)

> If you comment the WM_SETCURSOR section you'll notice hovering on e.g. win32 resize decoration has windows switch to resize cursor but then the regular cursor is not restored when moving over client area.

yeah, this is 100% true, thanks for this.

**Comment by zaafar** [comment]
Thank you!!!! <3

**Comment by zaafar** [comment]
@PathogenDavid  based on the discussion maybe following code will reduce some redundant `ImGui_ImplWin32_UpdateMouseCursor` call.


```
$ git diff backends/imgui_impl_win32.cpp
diff --git a/backends/imgui_impl_win32.cpp b/backends/imgui_impl_win32.cpp
index 89ef37a2..04e5b5a2 100644
--- a/backends/imgui_impl_win32.cpp
+++ b/backends/imgui_impl_win32.cpp
@@ -190,13 +190,12 @@ void    ImGui_ImplWin32_Shutdown()
     IM_DELETE(bd);
 }

-static bool ImGui_ImplWin32_UpdateMouseCursor()
+static bool ImGui_ImplWin32_UpdateMouseCursor(ImGuiMouseCursor imgui_cursor)
 {
     ImGuiIO& io = ImGui::GetIO();
     if (io.ConfigFlags & ImGuiConfigFlags_NoMouseCursorChange)
         return false;

-    ImGuiMouseCursor imgui_cursor = ImGui::GetMouseCursor();
     if (imgui_cursor == ImGuiMouseCursor_None || io.MouseDrawCursor)
     {
         // Hide OS mouse cursor if imgui is drawing it or if it wants no cursor
@@ -429,7 +428,7 @@ void    ImGui_ImplWin32_NewFrame()
     if (bd->LastMouseCursor != mouse_cursor)
     {
         bd->LastMouseCursor = mouse_cursor;
-        ImGui_ImplWin32_UpdateMouseCursor();
+        ImGui_ImplWin32_UpdateMouseCursor(mouse_cursor);
     }

     // Update game controllers (if enabled and available)
@@ -695,8 +694,16 @@ IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hwnd, UINT msg, WPARA
             io.AddInputCharacterUTF16((unsigned short)wParam);
         return 0;
     case WM_SETCURSOR:
-        if (LOWORD(lParam) == HTCLIENT && ImGui_ImplWin32_UpdateMouseCursor())
-            return 1;
+        if (LOWORD(lParam) == HTCLIENT)
+        {
+            ImGuiMouseCursor mouse_cursor = io.MouseDrawCursor ? ImGuiMouseCursor_None : ImGui::GetMouseCursor();
+            bd->LastMouseCursor = mouse_cursor;
+            if (ImGui_ImplWin32_UpdateMouseCursor(mouse_cursor))
+            {
+                return 1;
+            }
+        }
+
         return 0;
     case WM_DEVICECHANGE:
         if ((UINT)wParam == DBT_DEVNODES_CHANGED)
```
