### ISSUE TITLE
BeginMenu away from popup border

### ISSUE THREAD

**Issue by mtosdjs** [ocornut/imgui#5391]
Use popup to pop up the menu, but BeginMenu will have a part outside the border, how can BeginMenu and ImGui::Button stay away from the border

I tried using ImGui::GetStyle().ButtonTextAlign = ImVec2(0.5f, 0.5f); but it didn't work
![image](https://user-images.githubusercontent.com/104288199/173332920-ad0ebc98-e119-480e-9208-62b624eaf849.png)

**Comment by ocornut** [comment]
You have probably set a WindowPadding of (0,0) or too small.
Lacking information that's what we can guess.

Please pay attention to provide required information next time.
