### ISSUE TITLE
docking Disable input

### ISSUE THREAD

**Issue by mtosdjs** [ocornut/imgui#5398]
platform：Ubuntu  opengl+glfw
branch： docking

Hello, I use the docking branch to make the imgui window detach from the glfw window, and then disable the input through ImGui_ImplGlfw_InitForOpenGL(window, false);, but the strange thing is that the imgui window that is detached from the glfw window can still be controlled with the mouse, how to disable input of imgui window at this moment and register my own callback

![image](https://user-images.githubusercontent.com/104288199/173766077-3cb07c90-767c-4105-96f7-6129ec1da0be.png)

**Comment by ocornut** [comment]
Why do you want to disable inputs on a whole viewport? What is the intent?

**Comment by mtosdjs** [comment]
hi， @ocornut

**Comment by mtosdjs** [comment]
hi, @ocornut 
I want to register my own mouse and keyboard callbacks and then pass some data

**Comment by rokups** [comment]
Maybe a better place to tap into input stream would be modifying backend code and handle events before they get passed to the library? It still is not quite clear what you are doing there. Best you could do with `glfwSetKeyCallback()` side by side original event processing would be observing events only, you would not be able to modify or filter input stream that way.

**Comment by mtosdjs** [comment]
hi,
Like the following, I want to get the keyboard callback and then do some processing

```
window = glfwCreateWindow(666, 666, "glfw windows", NULL, NULL);
glfwSetMouseButtonCallback(window, key_press_callback);

static void key_press_callback( GLFWwindow* window, int button, int action, int mods )
{
    printf("hhahaha key_press_callback\n");
	if ((key == GLFW_KEY_ESCAPE) && (action == GLFW_PRESS))
	{
		glfwSetWindowShouldClose(window, GL_TRUE);
	}
	if (action == GLFW_PRESS)
	{
		keys[key] = GLFW_TRUE;
	}
	else if (action == GLFW_RELEASE)
	{
		keys[key] = GLFW_FALSE;
	}
}
```

**Comment by rokups** [comment]
It still is not clear what is your purpose. Same thing can be done using imgui input functions. Why do you need a glfw callback?

**Comment by mtosdjs** [comment]
How to use the imgui input function to get keyboard events?

**Comment by rokups** [comment]
https://github.com/ocornut/imgui/blob/2ed9e21eba92df4f374ea028bff50f8309fdcab5/imgui.h#L880-L882

**Comment by mtosdjs** [comment]
Suppose, I press a key on the keyboard at random, and then I will receive the value and press state of the key passed to me by imgui, what do I need to do?

**Comment by rokups** [comment]
```cpp
if (ImGui::IsKeyPressed(key_you_observe))
{
    // do things
}
```
Do this for as many keys as you want. You can check all keys by iterating key value from `ImGuiKey_NamedKey_BEGIN` to `ImGuiKey_NamedKey_END`.

If you are really sure you need a glfw callback then there is something you do, but this is largely undocumented and you should avoid doing it if possible. You can also override `ImGui::GetPlatformIO().Platform_CreateWindow`, which gets called when window is detached from main viewport. So in your function you should first call the original function and then install your callback (which of course must call original callback).

**Comment by mtosdjs** [comment]
I think I know the way to do it
Thank you very much for your answer and wish you a happy life
