### ISSUE TITLE
Display circular image in imgui?

### ISSUE THREAD

**Issue by SrinSS01** [ocornut/imgui#5399]
`Imgui::Image` always renders a square image, is there any way to render a circular image?

**Comment by PathogenDavid** [comment]
There is no circular image widget, but you can draw circular images using `ImDrawList::AddImageRounded`. You can pretty easily leverage this to make your own widget:

```cpp
void CircleImage(ImTextureID user_texture_id, float diameter, const ImVec2& uv0 = ImVec2(0, 0), const ImVec2& uv1 = ImVec2(1, 1), const ImVec4& tint_col = ImVec4(1, 1, 1, 1))
{
    ImVec2 p_min = ImGui::GetCursorScreenPos();
    ImVec2 p_max = ImVec2(p_min.x + diameter, p_min.y + diameter);
    ImGui::GetWindowDrawList()->AddImageRounded(user_texture_id, p_min, p_max, uv0, uv1, ImGui::GetColorU32(tint_col), diameter * 0.5f);
    ImGui::Dummy(ImVec2(diameter, diameter));
}
```

**Comment by ocornut** [comment]
Thank you David!
Note how `AddImageRounded()` is implemented: it's filling a white a shape and then calling `ShadeVertsLinearUV()` over the range of vertices emitted. Similarly you could use PushTextureID() + AddCircleFilled() + ShadeVertsLinearUV() + PopTextureID() or will any shape.
