### ISSUE TITLE
Problems using ImGui::SetLastItemData()

### ISSUE THREAD

**Issue by TheClockIT** [ocornut/imgui#5402]
**Version/Branch of Dear ImGui:**

Version: v1.88 WIP
Branch: v1.88 WIP_(docking)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx12.cpp + imgui_impl_win32.cpp 
Operating System: Windows 10 21H2

**My Issue/Question:**

ImGuiItemStatusFlags set with ImGui::SetLastItemData() before ImGui::InputTextMultiline() will be cleared by ItemAdd().
I want to put him in front of ItemAdd().

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/39299695/174004883-14c6af5d-2bae-48dc-a927-22295ef9bfd3.png)

**Standalone, minimal, complete and verifiable example:
``` cpp
if (hasSelect)
    ImGui::SetLastItemData(0, 0, ImGuiItemStatusFlags_FocusedByTabbing, ImRect());
ImGui::InputTextMultiline("##TestMultiline", str, ImVec2(0.0f, 0.0f), ImGuiInputTextFlags_CallbackAlways, MyCallback);
```

**Comment by ocornut** [comment]
Hello,
That’s a XY Problem question. Please read the guidelines. Notice “ SetLastItemData “ says “Last” and it is an internal function you shouldn’t call it.
Instead state what you want to achieve. It seems documented and exhibited in the demo window under the Focus section.

**Comment by ocornut** [comment]
> I want to select text in ImGui::InputTextMultiline() after clicking the button.

This is the correct question, thank you.
It is demonstrated in `Demo > Inputs, Navigation & Focus > Focus From Code` using the `ImGui::SetKeyboardFocusHere()` function.
