### ISSUE TITLE
ColorPicker fullscreen close button?

### ISSUE THREAD

**Issue by mumin16** [ocornut/imgui#5405]
i work for mobile so i need big dialogs(fullscreen). But ColorPicker don't have close button(rightup). how to close color picker dialog.
      ImGui::SetNextWindowPos(ImVec2(0,0));
      ImGui::SetNextWindowSize(ImVec2(app.view_width,app.view_height));      
      ImGui::ColorEdit3(output.first, (float *)&output.second.icolor, ImGuiColorEditFlags_NoInputs|ImGuiColorEditFlags_NoTooltip);

**Comment by ocornut** [comment]
Maybe don't make them fullscreen and leave space on the edge of screen for regular closing.

There's no way to override the content of picker spawned by ColorEdit3. But if you open a popup yourself you can call ColorPicker3 inside the popup and then add a Close button if you need.
