### ISSUE TITLE
Proposal: Move Widgets to a separate namespace?

### ISSUE THREAD

**Issue by oktonion** [ocornut/imgui#5407]
The general idea is to logically separate `namespace ImGui` items into groups. For starters proposal is to move all ImGui widgets in separate `namespace ImGui::Widgets` (since we already have `imgui_widgets.cpp` as separated piece of code).

```cpp
namespace ImGui {
    namespace Widgets {
        IMGUI_API void          TextUnformatted(const char* text, const char* text_end = NULL); // raw text without formatting. Roughly equivalent to Text("%s", text) but: A) doesn't require null terminated string if 'text_end' is specified, B) it's faster, no memory copy is done, no buffer size limits, recommended for long chunks of text.
        // ...all ImGui widgets there
    
    } // namespace Widgets
} // namespace ImGui 
```

 It could be then integrated again in `namespace ImGui` for backward compatibility if needed.
```cpp
namespace ImGui {
    namespace Widgets {
        // all ImGui widgets there
    } // namespace Widgets
   
    using namespace Widgets; // for bw comp only
} // namespace ImGui 
```

Actually since we have already groups of widgets divided by comments like `// Widgets: Text`, `// Widgets: Main` and so on it would be nice to group widgets into separate namespaces and it that can be easily implemented:

```cpp
namespace ImGui {
    namespace Widgets {
        namespace Keyboard {
             // all ImGui Keyboard  widgets there
        } // namespace Keyboard
        namespace RegularSliders {
             // all ImGui Regular Sliders widgets there
        } // namespace Keyboard
...
        using namespace Keyboard ; // for bw comp only
        using namespace RegularSliders ; // for bw comp only
...
    } // namespace Widgets
   
    using namespace Widgets; // for bw comp only
} // namespace ImGui 
```

**Comment by ocornut** [comment]
> ```
> namespace ImGui {
>     namespace Widgets {
>         namespace Keyboard {
>              // all ImGui Keyboard  widgets there
>         } // namespace Keyboard
>         namespace RegularSliders {
>              // all ImGui Regular Sliders widgets there
>         } // namespace Keyboard
> ...
>         using namespace Keyboard ; // for bw comp only
>         using namespace RegularSliders ; // for bw comp only
> ...
>     } // namespace Widgets
>    
>     using namespace Widgets; // for bw comp only
> } // namespace ImGui 


Sorry I don't think this would add value, quite the contrary I think this is doing to be detrimental to use of the API and working on the codebase. Many functions would have an ambiguous category as well. Seems quite undesirable to me.
