### ISSUE TITLE
Android: Unknown input issue on 1.87

### ISSUE THREAD

**Issue by vovan4ik123-engine** [ocornut/imgui#5408]
I am using SDL2 + openglES 3 + ImGUI on Android application.
On version ImGUI 1.87 all GUI elements stopped respond to screen touch
(check boxes, sliders, buttons and ImGUI demo dont react to screen touch).
SDL2 recognize screen touches but ImGUI elements ignore them.

On 1.86 version screen touches works good and ImGUI demo is clickable.

Im using Cmake for build ImGUI during all versions tested.
Here is CmakeLists.txt

cmake_minimum_required(VERSION 3.10)

add_definitions(-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS)
add_definitions(-DIMGUI_DISABLE_OBSOLETE_KEYIO)

add_library(ImGUI-static STATIC  imgui.cpp
                                                     imgui_demo.cpp
                                                     imgui_draw.cpp
                                                     imgui_tables.cpp
                                                     imgui_widgets.cpp
                                                     backends/imgui_impl_sdl.cpp
                                                     backends/imgui_impl_opengl3.cpp)

target_include_directories(ImGUI-static PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}   ../SDL2/include)

**Comment by ocornut** [comment]
Does it happen with the unmodified examples/ applications?

**Comment by vovan4ik123-engine** [comment]
Yes it happens for clear download and unpack source code from Release 1.87 page.
Previously i had 1.81 version and GUI elements works good. Last working version is 1.86

**Comment by rokups** [comment]
I am unable to replicate this in official example. Tested in emulator. I added `IMGUI_DISABLE_OBSOLETE_FUNCTIONS=1 IMGUI_DISABLE_OBSOLETE_KEYIO=1` as it seems like this is only customization you did. Could you test the same?

**Comment by ocornut** [comment]
Closing as stale and lacking information. Feel free to comment with details.
