### ISSUE TITLE
`VK_LAYER_LUNARG_monitor` is incompatible with multiple viewport

### ISSUE THREAD

**Issue by alanjian85** [ocornut/imgui#5410]
**Version/Branch of Dear ImGui:**

Version: 1.88 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: MSVC v143
Operating System: Windows 11 Pro Build 22000.739

**My Issue/Question:**

ImGui creates a new viewport window every time I move a widget out of the main window, but this action would cause the framerate counter on the title bar created by the layer `VK_LAYER_LUNARG_monitor` enabled during the instance creation stage stop working, this subtle bug makes it hard to profile my program and freeze the title in a strange text.

**Screenshots/Video**

https://user-images.githubusercontent.com/71581428/174438940-953f4842-e9d5-4e8e-950f-a32b62caf885.mp4

**Comment by PathogenDavid** [comment]
This is almost certainly this bug in VK_LAYER_LUNARG_monitor: https://github.com/LunarG/VulkanTools/issues/1590

(If you disable `ImGuiIO::ConfigViewportsNoDecoration` you will probably find that the monitor has switched to the title of the secondary viewport.)

You're probably better off drawing your own FPS counter.
