### ISSUE TITLE
Get Size of Icon Fonts Glyph in Pixels

### ISSUE THREAD

**Issue by apaly** [ocornut/imgui#5417]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: iimgui_impl_win32.cpp + imgui_impl_opengl3.cpp
Compiler: VS 2022
Operating System: Windows 11

**My Issue/Question:**

Hello,
I merged icon fonts with the default font Dear ImGui font. The icon fonts are rendered using `drawList->AddText`. I will like to know the size of the rendered icon Fonts glyph in pixels. What function can I use?

Thanks.

**Comment by ocornut** [comment]
You can use `ImGui::CalcTextSize()` or `drawList->CalcTextSizeA()`.

**Comment by apaly** [comment]
Thanks for your reply.
I couldn't find `CalcTextSizeA()` in `drawList`.

**Comment by ocornut** [comment]
My mistake: CalcTextSizeA() is not in ImDrawList but ImFont.
You can either use ImGui::CalcTextSize() is your AddText calls are using current font + current font size, otherwise if you used AddText() with a custom font as parameter use that font to call CalcTextSizeA().
