### ISSUE TITLE
Question: How do you disable the dockspace background?

### ISSUE THREAD

**Issue by rxantos** [ocornut/imgui#5418]
I am following the ShowExampleAppDockSpace() 

I want t transparent dockspace that does not show a background as it covers everything in the process.

How do I do this?

**Comment by PathogenDavid** [comment]
Specify `ImGuiDockNodeFlags_PassthruCentralNode` when you call `DockSpaceOverViewport`.

To test it in the demo, activate the flag under the `Options` menu at the top of the main viewport.
