### ISSUE TITLE
About ToggleButton and GetOverlayDrawList

### ISSUE THREAD

**Issue by AkuSukaKucingHitam** [ocornut/imgui#5419]
is ToggleButton and GetOverlayDrawList is already in ImGUI? or I made it myself?.
Thanks for reading this!

**Comment by ocornut** [comment]
`ToggleButton()` is your onw stuff.
`GetOverlayDrawList()` was renamed to `GetForegroundDrawList()` in 1.69 (March 2019).
If you search for names in the codebase you'll find those references.
