### ISSUE TITLE
Getting texture image data.

### ISSUE THREAD

**Issue by dimethylethylamine** [ocornut/imgui#5424]
**Version/Branch of Dear ImGui:**

Version: Dear ImGui 1.88
Branch : master

**My Question:**

Hello, is there any way to get the texture image data of whatever is currently being rendered? I am using the DirectX 9 implementation and I've been trying to find a way to do this for a while now, help would be appreciated.

Thank you.

**Comment by Demonese** [comment]
https://github.com/microsoft/DirectXTex/blob/main/ScreenGrab/ScreenGrab9.h

**Comment by ocornut** [comment]
Question is not related to Dear ImGui.
