### ISSUE TITLE
ImGui window and widgets not getting focus

### ISSUE THREAD

**Issue by NovaChron0** [ocornut/imgui#5426]
Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: [imgui-SFML](https://github.com/eliasdaler/imgui-sfml)
Compiler: MSVC
Operating System: Windows 10 Pro

**My Issue/Question:**

I made a simple application with sfml, imgui and [WebView2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/) embedded in my application. Every works great. However when I interact on the webview and then press on any imgui window/button/input nothing happens. Imgui does not detect focus even if I click on it's window or buttons. Please note that it only happens with imgui since I can click on other parts of the screen and interact with my application just fine. I can resolve this pressing window's key on keyboard and then opening my application again from taskbar.

I don't understand if it is something specific to webview stuff. Since so far I have not faced any such issue with imgui. Let me know how I can provide more context and information to resolve this issue.

**Screenshots showing a button not getting highlighted on hover (unfortunately windows is not displaying mouse) after interaction with webview**

![Screenshot (13)](https://user-images.githubusercontent.com/75472917/175872629-304aaa86-7533-40d8-bf92-5c4a66834c0a.png)

**Comment by rokups** [comment]
From your description it seems like input events stop being routed to Dear ImGui. `ProcessEvent()` function has `if (s_currWindowCtx->windowHasFocus)` condition which prevents passing any events to Dear ImGui if window is not focused. You should ensure that clicking outside of webview focuses SFML window again.

**Comment by NovaChron0** [comment]
Clicking outside of webview, SFML window can detect all clicks and inputs. It's just imgui that doesn't respond to them.

**Comment by rokups** [comment]
It does not respond because it does not get any events.

**Comment by ocornut** [comment]
We don't have enough information to help you debug this, but it is likely either a problem with imgui-sfml, either a problem with how you are using it or routing inputs.

You can display various important fields on the screen e.g. `ImGui::Text("MousePos %f %f Button %d, ImGui::GetMousePos().x, ImGui::GetMousePos().y, ImGui::IsMouseDown(0))` and you will likely notice that dear imgui is not getting those inputs, at this point it isn't dear imgui fault, and you can add more printf or breakpoint in other locations to find what's happening, but as pointed by @rokups the `s_currWindowCtx->windowHasFocus` check in imgui-sfml may be a good starting point.
