### ISSUE TITLE
Buttons/other widgets not triggering when running more than 1 viewport

### ISSUE THREAD

**Issue by BillyTheSquid21** [ocornut/imgui#5427]
I'm trying to run multiple windows at the same time through this process (with unnecessary code left out):

//Function to start frame:
```
void GameGUI::StartFrame()
{
	ImGui_ImplOpenGL3_NewFrame(); 
	ImGui_ImplGlfw_NewFrame(); 
	ImGui::NewFrame(); 
}
```

//Function to end frame:
```
void GameGUI::EndFrame()
{
	ImGuiIO& io = ImGui::GetIO();

	ImGui::Render(); 
	ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData()); 

	// Update and Render additional Platform Windows
	if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
	{
		ImGui::UpdatePlatformWindows();
		ImGui::RenderPlatformWindowsDefault();
	}
}
```

//Called in render function:
```
void MyGUI::render()
{
        ImGui::Begin("Debug Menu", 0, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize);
	ImGuiIO& io = ImGui::GetIO();
        ImGui::BeginChild(name, ImVec2(width, height), ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoScrollbar);
        
        //Button
        if (ImGui::Button(m_ButtonText.c_str(), ImVec2(ImGui::GetContentRegionAvail().x - 10.0f, 50))) {
		*m_Trigger = true;
	}
	else
	{
		*m_Trigger = false;
	}

        ImGui::EndChild();
        ImGui::End();
}

```

Then in the application render thread I call it as such:
```

void render()
{
    //Window 1
    GameGUI::StartFrame();
    gui1.render();
    GameGUI::EndFrame();
 
    //Window 2
    GameGUI::StartFrame();
    gui2.render();
    GameGUI::EndFrame();
}
```

The result draws both windows fine, with the buttons and other things, however the buttons (and other widgets when I try) don't click/change color, or trigger at all. Any idea why this this?

**Comment by PathogenDavid** [comment]
From the looks of things you're using the docking branch, why aren't you using Dear ImGui's support for multiple viewports instead of trying to do it yourself?

**Comment by ocornut** [comment]
>  (with unnecessary code left out):

You left out too much code. If you are trying to use multiple contexts (instead of single-context multi-contexts) you should create two contexts with `ImGui::CreateContext()`, initialize each backends twice, and change context manually with `ImGui::SetCurrentContext()`. Your issue is most likely related to missing out some steps.
