### ISSUE TITLE
ImGui::Image draws garbage in modal window

### ISSUE THREAD

**Issue by Hyldrean** [ocornut/imgui#5438]
```
Dear ImGui 1.88 (18800)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=202002
define: __linux__
define: __GNUC__=11
--------------------------------
io.BackendPlatformName: imgui_impl_sfml
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000007
 HasGamepad
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 3 fonts, Flags: 0x00000000, TexSize: 512,1024
io.DisplaySize: 1200.00,800.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.88 ([commit](https://github.com/ocornut/imgui/commit/9aae45eb4a05a5a1f96be1ef37eb503a12ceb889))

**Back-end/Renderer/Compiler/OS**

Back-ends: [ImGui-SFML](https://github.com/eliasdaler/imgui-sfml)
Operating System: Debian bookworm

**My Issue/Question:**

When calling '''ImGui::Image''' in a modal window, it renders garbage for the first call, then works fine. In popup window it works perfectly fine. It seems to be a bug and I don't know whether it is a SFML related issue or not, so I posted it here.
I have tried with '''ImGui::ImageButton''' too, the bug is the same (except all calls fail to draw the texture).
I have resized the image to see it bigger. It appears it is the font texture.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/65984054/176726623-22ac5499-d34e-4a93-a5d7-f9630053c375.png)
![image](https://user-images.githubusercontent.com/65984054/176726519-a442a482-ffa5-4535-99fc-99d7a409f43e.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
#include <SFML/Graphics.hpp>
#include "imgui-SFML.h"
#include "imgui.h"

int main()
{
    sf::RenderWindow window(sf::VideoMode(1200, 800), "My window");
    ImGui::SFML::Init(window);

    sf::Texture texture;
    texture.loadFromFile("assets/dice/red_1.png");

    sf::Clock clock;

    while (window.isOpen()) {
        //poll events
        sf::Event event{};
        while (window.pollEvent(event)) {
            ImGui::SFML::ProcessEvent(event);

            if (event.type == sf::Event::Closed)
                window.close();
        }

        //
        window.clear();

        //clock
        sf::Time elapsed = clock.restart();

        //update ImGui
        ImGui::SFML::Update(window, elapsed);

        //draw main window
        ImGui::Begin("main");

        if (ImGui::Button("Open popup"))
            ImGui::OpenPopup("popup");

        if (ImGui::Button("Open modal"))
            ImGui::OpenPopup("modal");

        //draw popup
        if (ImGui::BeginPopup("popup")) {
            ImVec2 image_size(50.f, 50.f);

            //draw them
            for (int i = 0; i < 5; ++i) {
                ImGui::Image(texture, image_size);
                ImGui::SameLine();
            }

            ImGui::EndPopup();
        }

        //draw modal
        if (ImGui::BeginPopupModal("modal")) {
            ImVec2 image_size(50.f, 50.f);

            //draw them
            for (int i = 0; i < 5; ++i) {
                ImGui::Image(texture, image_size);
                ImGui::SameLine();
            }


            ImGui::EndPopup();
        }

        ImGui::End();

        //
        ImGui::SFML::Render(window);
        window.display();
    }

    return 0;
}
```

**Comment by ocornut** [comment]
Given the screenshot it looks like a bug in your version of the imgui-SFML backend ?

Fixed by https://github.com/eliasdaler/imgui-sfml/commit/004efd85a590343e8c9d166dc9d2524c199c9450

See "Got visual Glitches?" in https://github.com/ocornut/imgui/releases/tag/v1.86
Same as https://github.com/ocornut/imgui/issues/4845, https://github.com/ocornut/imgui/issues/4863, https://github.com/ocornut/imgui/issues/4887, https://github.com/ocornut/imgui/issues/4888 and https://github.com/ocornut/imgui/issues/5406 and others

Can you confirm it?

**Comment by Hyldrean** [comment]
It works with the commit 004efd85a590343e8c9d166dc9d2524c199c9450 and above. Thank you for your time, I didn't found the issue you mentioned even though I searched.
