### ISSUE TITLE
blue screen

### ISSUE THREAD

**Issue by husiluanxiang** [ocornut/imgui#5440]
1.when I generate my program, I get blue screen,
![1b83c36cb6d6ccf8766429ce8f7edee](https://user-images.githubusercontent.com/38007233/176815534-a5e6123b-129f-4500-a4ef-213e3afea0fd.jpg)
but I use example it no errors

**Comment by PathogenDavid** [comment]
This isn't really a Dear ImGui issue. You should investigate the faulting module, `tdfsflt.sys`. A cursory search suggests it might be a virus, so you probably want to get that taken care of.

**Comment by husiluanxiang** [comment]
![Uploading image.png…]()
