### ISSUE TITLE
Set height for Menu and MenuItem ?

### ISSUE THREAD

**Issue by dnhuy4869** [ocornut/imgui#5442]
Version: 1.86
Back-ends: imgui_impl_dx9.cpp

is there any way to change the height of Menu and MenuItem widget ?

![Screenshot_6](https://user-images.githubusercontent.com/73681373/176921965-a5f62a47-4c7b-44f3-8bcd-919d6ddce528.png)
i tried FramePadding but doesn't work 

```
ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(10.f, 80.f));
if (ImGui::BeginMenu(displayText.c_str()))
{
    ImGui::EndMenu();
}
ImGui::PopStyleVar();
```

**Comment by ocornut** [comment]
Unframed widgets don't use FramePadding.
In the case of menus the size comes from FontSize + ItemSpacing only (as Selectable/Menu overlaps the spacing between items).

**Comment by dnhuy4869** [comment]
i can change height with ImGuiStyleVar_ItemSpacing now but window doesn't auto resize to fix with new padding in menu

![Screenshot_7](https://user-images.githubusercontent.com/73681373/176926772-8604f6bc-dcd2-4326-8122-85d80a691348.png)

here is code i use
```
ImGui::SetNextWindowPos(
		ImVec2(50, 50),
		ImGuiCond_Once
	);
ImGui::SetNextWindowSizeConstraints(ImVec2(240.0f, -1.f), ImVec2(INFINITY, -1.f));
ImGui::Begin(
	"##mainMenu",
	0,
	ImGuiWindowFlags_NoDecoration
	| ImGuiWindowFlags_NoBringToFrontOnFocus
	| ImGuiWindowFlags_AlwaysAutoResize
);

ImGuiStyle* style = &ImGui::GetStyle();

for (const auto& [menuName, menu] : m_MenuComponents)
{
	ImGui::SetNextWindowSizeConstraints(ImVec2(240.0f, -1.f), ImVec2(INFINITY, -1.f));
	ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(style->ItemSpacing.x, 20.0f));

	std::string displayText = menu->DisplayName + "##" + menu->Name;
	if (ImGui::BeginMenu(displayText.c_str()))
	{

		ImGui::EndMenu();
	}

	ImGui::PopStyleVar();
}

ImGui::End();
```
