### ISSUE TITLE
Alternate colours for Radio Button - other than blue?

### ISSUE THREAD

**Issue by svkvarun43** [ocornut/imgui#5444]
**Version/Branch of Dear ImGui:**

Version: V1.87
Branch: master

**My Issue/Question:**

By default the colour of radio button is "blue" , could be change the colour when the button is pressed to be other colours?

**Screenshots**

![image](https://user-images.githubusercontent.com/98422353/176980563-1af3b6dd-c81a-40df-86a4-e0be83353b49.png)

```
static int e = 0;
ImGui::RadioButton("radio a", &e, 0); 
ImGui::SameLine();

```

**Comment by PathogenDavid** [comment]
Adjust the `ImGuiCol_CheckMark` color. IE:

```cpp
ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1.f, 0.f, 0.f, 1.f));
ImGui::RadioButton("radio a", &e, 0);
ImGui::PopStyleColor();
```

(Alternatively adjust it in `ImGuiStyle::Colors` to affect all widgets instead of just a particlar span. As the name implies, this will affect checkboxes too.)

**Comment by svkvarun43** [comment]
Thank you that worked :) 
I will close the issue
