### ISSUE TITLE
modify the style of Selectable()

### ISSUE THREAD

**Issue by Boglon333** [ocornut/imgui#5445]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: XXX

**My Issue/Question:**

I draw with function ImGui::Selectable() in the first picture, how should I modify it to achieve the format of the second picture. When I select a row, the selected row turns gray instead of light blue, and don't show the blue background when the mouse moves hover each row, just like the second picture. Should I choose another function to implement this style?

**Screenshots/Video**

<img width="165" alt="067A0D6F-BE72-4ced-9D2A-364479E858D5" src="https://user-images.githubusercontent.com/108468290/176989611-734a5dc8-04ff-4423-b330-7327c702a704.png">

![image](https://user-images.githubusercontent.com/108468290/176989685-24b8a03f-bc75-4c25-9686-47eeb68e692c.png)

**Comment by PathogenDavid** [comment]
The colors used for the background of selectables are `ImGuiCol_Header`, `ImGuiCol_HeaderHovered`, and `ImGuiCol_HeaderActive`.

You can change them for specific widgets using `PushStyleColor` and `PopStyleColor`.

You can also change them for everything changing the values in `ImGuiStyle::Colors`. However this will affect things besides selectables.

A good way to discover these things is via the style editor. It can be found in the "Tools" menu of the demo window.

**Comment by Boglon333** [comment]
Oh, thank you very much. I have done it. But I have another issue, the background box of  selectables  in the second image is symmetric up and down with the text, so what I can do to achieve this style?

**Comment by lukaasm** [comment]
Call
```
ImGui::AlignTextToFramePadding();
ImGui::TextUnformatted("Medium");
```

**Comment by Boglon333** [comment]
Hi lukaasm, my text information is printed on the screen by ```ImGui::Selectable("Medium",...) ```. I just tried ```ImGui::AlignTextToFramePadding(); ImGui::TextUnformatted("Medium");``` and it doesn't change my style. 
My original codes are shown below:
```
if (ImGui::Selectable("Medium", nowSelected == i, ImGuiSelectableFlags_AllowItemOverlap, ImVec2(0.0f, 22.0f)))
{
	nowSelected = i;
}
```

**Comment by lukaasm** [comment]
> @lukaasm Hi lukaasm, my text information is printed on the screen by `ImGui::Selectable("Medium",...) `. I just tried `ImGui::AlignTextToFramePadding(); ImGui::TextUnformatted("Medium");` and it doesn't change my style. My original codes are shown below:
> 
> ```
> if (ImGui::Selectable("Medium", nowSelected == i, ImGuiSelectableFlags_AllowItemOverlap, ImVec2(0.0f, 22.0f)))
> {
> 	nowSelected = i;
> }
> ```

Ah, yes sorry, for text in selectable use:
```
ImGui::PushStyleVar(ImGuiStyleVar_SelectableTextAlign, ImVec2( 0.0f, 0.5f ) );
ImGui::Selectable( ... )
ImGui::PopStyleVar()
```

**Comment by Boglon333** [comment]
@lukaasm Thank you very much, it works well!
