### ISSUE TITLE
How to draw a vertical dividing line?

### ISSUE THREAD

**Issue by Boglon333** [ocornut/imgui#5448]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: XXX

**My Issue/Question:**
I want to draw a vertical line that can divide a window as two part. It works like the function ```ImGui::Columns()```.  I have drawn a left window and a right window _(the code is below)_ , but I need a vertical line. In picture two, when mouse clicks on the vertical line it turns dark blue, it also turns dark blue when mouse moves hover the line. In picture three and four, I can drag the vertical line from left to right or from right to left so that I will change the size of left window and right window. I think it works like the column in the table, but I can't fulfill my demands with ```ImGui::Columns()``` . 

**Screenshots/Video**
picture one<img width="138" alt="AF4F55EB-6E23-40e9-B35C-56A3FC0F6E55" src="https://user-images.githubusercontent.com/108468290/177040521-5845bc97-21cc-47cb-8178-72c71953e1d6.png">picture two<img width="124" alt="50520B8F-6722-4498-86B3-656C8BE01908" src="https://user-images.githubusercontent.com/108468290/177040560-e9aebfe7-16d1-4886-9a22-db10c1afa74a.png">picture three<img width="38" alt="A170C485-D4DB-4f2c-AC8D-BFDC97E457DA" src="https://user-images.githubusercontent.com/108468290/177040571-1a323f5d-8bb6-4651-b3ba-c6f74165b656.png">
picture four<img width="303" alt="AE620150-5AF4-46e2-A728-5080F49009A0" src="https://user-images.githubusercontent.com/108468290/177040584-1ce4a825-e69a-41c4-b159-04705b0d0868.png">

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
ImGui::BeginChild("left window", ImVec2(200, 0), false);
...
ImGui::EndChild();
ImGui::BeginChild("right window", ImVec2(0, -ImGui::GetFrameHeightWithSpacing()),false);
...
ImGui::EndChild();
```

**Comment by rokups** [comment]
It is unclear what you are trying to achieve and why `ImGui::Columns()` does not fulfill your needs. To achieve similar thing you could use tables (`ImGui::BeginTable()`) without header row and outter borders. Depending on what you are trying to achieve, you may want to check out docking branch in case its that what you are trying to do.

**Comment by Boglon333** [comment]
Oh, I'm  sorry. Please ignore what I said earlier. Now I want to use ```ImDrawList* draw_list = ImGui::GetWindowDrawList(); draw_list->AddLine()``` to draw this vertical line, but how can I select this line like picture two. _(In picture two, when mouse clicks on the vertical line it turns dark blue, it also turns dark blue when mouse moves hover the line.)_
![image](https://user-images.githubusercontent.com/108468290/177135086-ca0b29c4-ebbf-4abd-b969-6a646d70fe66.png)

**Comment by rokups** [comment]
It looks like you want to create a custom widget. Look into `ButtonBehavior()` (include `imgui_internal.h`). This will allow line to behave like a button and give you some hints on it's state.

**Comment by ocornut** [comment]
@Boglon333 You should clarify your actual problems rather than focus on what you think is a possible workaround otherwise you are falling into XY Problem (https://xyproblem.info). **You are not explaining why Tables or Columns are not working for you, you should focus on that.**

Should you actually need a custom widget there is a SplitterBehavior() helper in imgui_internal (see #319)
