### ISSUE TITLE
Add some widget on titlebar

### ISSUE THREAD

**Issue by OmhaRobin** [ocornut/imgui#5449]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: win10

**My Issue/Question:**

How can I add a input widget by ```ImGui::InputText()``` on the right of titlebar as the figure shown? I have let the window has the same size as the GLFW window and used ```ImGui::Begin("##my window", nullptr, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize);``` to change the titlebar settings. Please ignore the texture image on the left.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/108620252/177050384-76deecba-823a-4112-b684-24aca7d98340.png)

**Comment by OmhaRobin** [comment]
```ImGui::RenderWindowTitleBarContents()```: Should I change this function to put a texture image or input widget on titlebar?

**Comment by ocornut** [comment]
I guess you would generally need to push a clip rect, see what BeginMenuBar() is doing, you'd want to do something similar.

Also see #5115 (which I left answered in spite of being well crafted, apologies to Simon). And #4385. #4137, #3882.

**Comment by OmhaRobin** [comment]
@ocornut Thank you, I'll try what you said.
