### ISSUE TITLE
Allow option to work with wchar text.

### ISSUE THREAD

**Issue by ratchetfreak** [ocornut/imgui#546]
One of the issues with text input is that the backing text editor depends on a utf16 character buffer.

So why not forward this to the user and let him choose to avoid the expensive conversion back and forth.

**Comment by ocornut** [comment]
Agree in theory. In practice it would too much effort to support both modes so realistically I don't think it'll ever be done. Not much point in requesting features if they aren't going to happen.
My hope is to remove the conversions all-together, clean up the code and stay with UTF-8 support only.

**Comment by ocornut** [comment]
Closing that as dropped because I don't think it'll happen. If you feel like seriously working on solving this yourself feel free to :)
