### ISSUE TITLE
Imgui just renders the bottom of the text 

### ISSUE THREAD

**Issue by JeysDev** [ocornut/imgui#5461]
Version: 1.87

I'm creating a basic ImGui program but any code i write just results in the text cut in half

![image](https://user-images.githubusercontent.com/72159225/178221123-e7fc7982-1118-48e6-b668-1607e1145373.png)

Any help would be appreciated, thanks

**Comment by ocornut** [comment]
Closing until OP decide to read guidelines and provide the right information.
