### ISSUE TITLE
Issue in imgui.cpp

### ISSUE THREAD

**Issue by ogenjas** [ocornut/imgui#5462]
![image](https://user-images.githubusercontent.com/79533618/178222980-55127764-f061-438e-8e1f-eb9a8800faa6.png)

I have this error every time i want to go into cfg tab

**Comment by rokups** [comment]
Issue template is there not for you to ignore it so fill it out, its there for a reason. It is hard to provide any help without no context, but from what i see it looks like bug in your own code.

**Comment by ocornut** [comment]
Sorry but #1586
