### ISSUE TITLE
 How can i ColorEdit ImU32 ?

### ISSUE THREAD

**Issue by Facepunch309** [ocornut/imgui#5467]
Hey everyone !!!
I Just want to color edit my OverlayDrawlist() which the color is ImU32,
but there isnt a ImU32 Color editor !
So how can i colorEfit ImU32 ?

**Comment by ocornut** [comment]
You need to convert back with `ColorConvertFloat4ToU32()` and forth with `ColorConvertFloat4ToU32()` (only when edited).
ImColor() helper does that conversion for you.
