### ISSUE TITLE
How would I put a ImGui::BeginChild into a specific pos

### ISSUE THREAD

**Issue by SightDev** [ocornut/imgui#5469]
Ive been trying to get a ImGui::Child into a certain position but I tried trying to find a solution and couldn't find much the child just keeps going to the bottom of the window, Any ideas?

**Comment by rokups** [comment]
Child window is created at current cursor (not mouse cursor!) position so use `ImGui::SetCursorPos()` to set where you want top-left corner of child window to be. You probably want to specify child window size in `ImGui::BeginChild()` call as well.

**Comment by ocornut** [comment]
In this specific case you can use either `SetCursorPos()`/`SetCursorScreenPos()` (since the child is an Item from the point of view of the parent window) or `SetNextWindowPos()` (since the child is a window itself).
