### ISSUE TITLE
OpenGL examples: Strange results when minimize the system window

### ISSUE THREAD

**Issue by laizy** [ocornut/imgui#547]
Hi，it is my first time to use imgui. when i build the opengl_example code with visual studio  and run it.
It is ok , but when i minimize the system window and then restore it will lead to strange results  like the image below. note: build the example with the code version 1.47  don't have this problem. ;)

![default](https://cloud.githubusercontent.com/assets/4203231/13546582/25b1b41c-e2ed-11e5-9888-11f07f07c706.PNG)

**Comment by ocornut** [comment]
Appears to be caused by https://github.com/ocornut/imgui/commit/2813a44dccef1549feed57e42acdbaad51fbe2e5

**Comment by ocornut** [comment]
Ouch. Caused by https://github.com/ocornut/imgui/commit/2813a44dccef1549feed57e42acdbaad51fbe2e5 which change a lots of state without restoring it on early return.

**Comment by ocornut** [comment]
Fixed.

**Comment by laizy** [comment]
thanks！
