### ISSUE TITLE
I use SDL backend but I don't know how to get the textid

### ISSUE THREAD

**Issue by Victor2kyang** [ocornut/imgui#5474]
Version/Branch of Dear ImGui:  1.87/master

Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: 
#include "backends/imgui_impl_sdl.h"
#include "backends/imgui_impl_sdlrenderer.h"
Compiler: MSVC
Operating System: Windows 10

My Question:

I read the documentation in the following URL ： https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
There are examples of opengl and dx3d.
But I just want to use only SDL to display the image .
However, I still don't understand the meaning of ImTextureID in SDL.

If anyone knows how to get the **ImTextureID**  in the SDL backend, it would be greatly appreciated!

```
    int frame_padding = 2;      
    ImGuiIO& io = ImGui::GetIO();
    ImTextureID textid = io.Fonts->TexID;
    float my_tex_w = (float)io.Fonts->TexWidth;
    float my_tex_h = (float)io.Fonts->TexHeight;
    ImVec4 bg_col = ImVec4(0.0f, 0.0f, 0.0f, 1.0f); 
    ImVec4 tint_col = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);
    ImVec2 size = ImVec2(32.0f, 32.0f);                     // Size of the image we want to make visible
    ImVec2 uv0 = ImVec2(0.0f, 0.0f);                        // UV coordinates for lower-left
    ImVec2 uv1 = ImVec2(32.0f / my_tex_w, 32.0f / my_tex_h);

    if (ImGui::ImageButton(textid, size, uv0, uv1, frame_padding, bg_col, tint_col))
            std::cout << "ImageButton clicked " << std::endl;
```

**Comment by rokups** [comment]
Issue template and reading documentation is greatly appreciated! 🙏 

You should create `SDL_Texture*` (`SDL_CreateTexture` API) and pass this pointer as texture.

```cpp
SDL_Texture* texid = SDL_CreateTexture(...);  // Remember to store pointer somewhere and not recreate texture of a static image on every frame!
// ...
ImGui::ImageButton((ImTextureID)(intptr_t)texid);
```

While wiki does not have an example for SDL Renderer, you can find one in SDL Renderer backend code [here](https://github.com/ocornut/imgui/blob/8731cc2914a4c08f555bf70d93b54658d5d942ce/backends/imgui_impl_sdlrenderer.cpp#L214-L222).

**Comment by Victor2kyang** [comment]
> SDL_Texture

Thank you so much for your patient reply, it was very helpful! ! !

**Comment by Victor2kyang** [comment]
> Issue template and reading documentation is greatly appreciated! 🙏
> 
> You should create `SDL_Texture*` (`SDL_CreateTexture` API) and pass this pointer as texture.
> 
> ```c++
> SDL_Texture* texid = SDL_CreateTexture(...);  // Remember to store pointer somewhere and not recreate texture of a static image on every frame!
> // ...
> ImGui::ImageButton((ImTextureID)(intptr_t)texid);
> ```
> 
> While wiki does not have an example for SDL Renderer, you can find one in SDL Renderer backend code [here](https://github.com/ocornut/imgui/blob/8731cc2914a4c08f555bf70d93b54658d5d942ce/backends/imgui_impl_sdlrenderer.cpp#L214-L222).
