### ISSUE TITLE
How to configure a scrollable window to fill empty space at bottom.

### ISSUE THREAD

**Issue by slgoldberg** [ocornut/imgui#5481]
**Version/Branch of Dear ImGui:**

Version: v1.84 WIP
Branch: main (I think)

**Back-end/Renderer/Compiler/OS**

Back-ends: n/a (higher level question)
Compiler: n/a (higher level question)
Operating System: n/a (higher level question)

**My Issue/Question:**

For context, I'm I guess you could say an "advanced" (to possibly low-end "expert") level user of ImGui (v1.84 WIP) as I've built a lot of very high-functioning UI on top of this framework, and I have to say I love it. :-)  (@ocornut , Jérémie L-E, avec qui je travaillais pendant 10+ ans chez Google, m'a dit qu'il te connaissait de l'Université, et il me l'a recommandé (à ImGui, that is)! :-) )

Also for context, I happen to be using ImGui for my C++ plugin for the X-Plane flight simulator. (My plugin is called "A-Better-Camera for X-Plane", and it is free, but not yet open-source.  I'm using the C++ bindings to ImGui v1.84 WIP, with the ImgWindow open-source mapping to X-Plane's plugin API.)

I am pretty sure I already know the answer to this question, but I have to ask anyway:

With the standard scrolling in ImGui windows and frames, is there a way for me to configure it so that the scrollbar correctly shows the end of the scrollable content, but then also allows the user to continue scrolling "past" the end of the contents, so that the top "item" (for some definition) can be displayed at the top of the visible portion of the scrolled window if the user likes?

In other words, normally as you know, when you scroll to the bottom of a window or frame with scrolling enabled (whether or not the scrollbar is visible), you cannot scroll any more once you get to the "bottom" (end of content).  However, a user interface may require being able to _continue_ scrolling past the "end", so that the last item ends up at the top (with intentional blank space below to fill the rest of the window).

I can of course easily do this by adding some blank space myself to the end of the window's/frame's content, but it is not a great user experience, because the built-in scrollbar (which I'm using) shows that there's more content, even though really there's just blank space. :-) And I have to calculate exactly how much space to add, which I'm admittedly having some trouble with at the moment. But I can work that out.. My question is whether I'm wasting my time implementing that. :-)

I have my own scrolling management where I always put the "current" item in the list of items at the top of the scrolling list, though of course when you reach the bottom of the list, I can't do that anymore (and that's fine, my UI works that way, it's just suboptimal).

Any ideas on ways I could approach this, if you understand it?  I can add screen shots of my particular UI if you like, but before going too deep, I just wanted to make sure I wasn't missing an obvious (documented or not) configuration that somehow I could be taking advantage of, to accomplish this with the existing scrolling implementation.

Thank you.

**Screenshots/Video**

Available on request.

**Standalone, minimal, complete and verifiable example:**

n/a (This is a high-level question about ImGui scrolling for frames and windows.)

If this was the wrong place to post this query, I apologize. I didn't see a better place.

**Comment by rokups** [comment]
I assume you use child windows for this? There is no built-in method for virtual space at the end and you would have to come up with your own solution. Dirty and simple approach would indeed be adding some space at the end and let library handle the rest, anything else would be way more complicated. If you use a child window, then at the try end of content doing `ImGui::SetCursorPosY(ImGui::GetCursorPosY() + height_of_child_window - style.WindowPadding.y * 2 - height_of_last_content_line)`. `height_of_last_content_line` should be `ImGui::GetFontSize()` for simple text.

**Comment by slgoldberg** [comment]
@rokups wrote:

> If you use a child window, then at the try end of content doing ImGui::SetCursorPosY(ImGui::GetCursorPosY() + height_of_child_window - style.WindowPadding.y * 2 - height_of_last_content_line). height_of_last_content_line should be ImGui::GetFontSize() for simple text.

Wow, I don't know why I didn't think of that -- good idea. I'll see if I can make it work doing it that way, thanks.

@ocornut wrote:

>  You can extend by then using ImGui::Dummy(0.0f, g.CurrentWindow->InnerClipRect.GetHeight() - item_height);

Thanks. I am trying to avoid using private ImGui interfaces, and sticking to just the public API.  But that does seem like a good way, too, thanks.

I guess I got the main answer I was looking for:  No, it's not already handled by the core framework, so I wasn't missing something obvious! :-)

> I am just sure I follow the logic here. If the built-in scrollbar didn't account for that extra blank space you added, it wouldn't be possible to scroll to by dragging the mouse. How else would you envision that to work?

Well, first of all, I may be wrong about this particular nuance -- I guess my assumption was it would feel more natural if the "thumb" (you call it "grab" I think) indicated visually where you are when scrolled within the _content_ as opposed to the possibly ending blank space as well.

In that model, the blank space is just to allow users who like to have content scrolled up to the top (i.e., so they can see it better, e.g., if they have vision issues reading at an angle) to be able to do that (I guess that's "scrolling past the end of the available content"), with the maximum being that the last line of text (in the example of scrollable text) is shown at the top and can't be scrolled off the top since it's the end of the content.

I was going to point to Visual Studio Code as one of many examples, but I think I am wrong here at least as far as VS Code is concerned.  It seems to allow you to scroll past the end (to where the final page is entirely clear), and it seems to account for that space in the scrollbar as well.  I guess maybe that's a hack, then. :-)  I don't recall just now what the option is, but it's a common option with text editors, to allow you to only have 1/2 a page of scroll area after the text, or a full page, or none (which seems to be the default on lots of editors).

Either way, I was hoping to reproduce that sort of UI in my application, where I have the last item in my (per-item) scrolling area be able to be scrolled all the way to the top.  (In my case, "items" are often 1/4 to 1/2 the size of the whole viewing window, so I'd just be letting them scroll halfway on the last page, so they could see the last item at the top half instead of the bottom.)

Thanks again.

  Steve

**Comment by slgoldberg** [comment]
Update after trying both ideas above:

I believe Omar's suggestion wins again! :-)

@ocornut wrote:

    You can extend by then using ImGui::Dummy(0.0f, g.CurrentWindow->InnerClipRect.GetHeight() - item_height);

This worked perfectly!  With the drawback as  mentioned above, that the scrollbar treats that blank space as "content" from the perspective of the grab size and position...  But of course, it's consistent, and works like some other UIs (just not the one I had envisioned).

So this is great and problem solved! :-)

Thanks again.

   Steve

P.S. I'm leaving it "open" just to ensure my last two messages are read by the two folks who so nicely weighed in.  @ocornut , feel free to close it when you've read it, unless you want to carry on the discussion about possibly having the scrollbar act "differently" as per my response above.  Thanks again very much!
