### ISSUE TITLE
Radial gradient

### ISSUE THREAD

**Issue by BrokenVoodooDoll** [ocornut/imgui#5483]
How can I draw radial gradient like this?
![image](https://user-images.githubusercontent.com/44895553/179757583-ba4faeff-3f82-4aa2-a3dc-a4ed0295517c.png)
And is it possible at all? I want to draw this not only in a rectangle but also in a circle.
Thanks for help!

**Comment by ocornut** [comment]
You may use the ImDrawList api to draw a fan of triangle around a center point, and set color/alpha so that the central point is white with full alpha and outer points are white with zero alpha.

**Comment by BrokenVoodooDoll** [comment]
I suppose a *ShadeVertsLinearColorGradientKeepAlpha*-like function isn't going to help me with it? Your suggestion is good but looks more like a workaround. And I think it won't work if I want to make, for example, an arc with a radial gradient.

**Comment by ocornut** [comment]
Here's a sample function:

```cpp
// https://github.com/ocornut/imgui/issues/5483
// Assuming col_out's alpha is zero means we don't need to draw and outer AA fringe as AddCircleFilled() would.
void AddRadialGradient(ImDrawList* draw_list, const ImVec2& center, float radius, ImU32 col_in, ImU32 col_out)
{
    if (((col_in | col_out) & IM_COL32_A_MASK) == 0 || radius < 0.5f)
        return;

    // Use arc with automatic segment count
    draw_list->_PathArcToFastEx(center, radius, 0, IM_DRAWLIST_ARCFAST_SAMPLE_MAX, 0);
    const int count = draw_list->_Path.Size - 1;

    unsigned int vtx_base = draw_list->_VtxCurrentIdx;
    draw_list->PrimReserve(count * 3, count + 1);

    // Submit vertices
    const ImVec2 uv = draw_list->_Data->TexUvWhitePixel;
    draw_list->PrimWriteVtx(center, uv, col_in);
    for (int n = 0; n < count; n++)
        draw_list->PrimWriteVtx(draw_list->_Path[n], uv, col_out);

    // Submit a fan of triangles
    for (int n = 0; n < count; n++)
    {
        draw_list->PrimWriteIdx((ImDrawIdx)(vtx_base));
        draw_list->PrimWriteIdx((ImDrawIdx)(vtx_base + 1 + n));
        draw_list->PrimWriteIdx((ImDrawIdx)(vtx_base + 1 + ((n + 1) % count)));
    }
    draw_list->_Path.Size = 0;
}
```

Usage example
```cpp
AddRadialGradient(ImGui::GetForegroundDrawList(), ImGui::GetMousePos(), 64.0f, IM_COL32(255, 255, 255, 220), IM_COL32(255, 255, 255, 0));
```

![image](https://user-images.githubusercontent.com/8225057/179979919-bcfcc1cb-6ff2-4c4f-9aad-cf94180891b3.png)

If you need a different falloff you may better use either a prebaked texture (simple but will introduce texture changes if you interleave different shapes), either a custom pixel shader (will introduce shader change).
