### ISSUE TITLE
Scrolling multiline text

### ISSUE THREAD

**Issue by dimanchique** [ocornut/imgui#5484]
Hello! Is it possible to code-scroll multiline text input widget? 
I'm using this type widget for program output data, and I would like to create auto-scroll option, but ImGui::SetScrollY doesn't work with multiline. I saw issue where you suggested to use TextUnformatted, but I need to work with this widget as editable text (I mean selecting, coping etc.). Does ImGui has any options for auto scrolling multiline text?

**Comment by rokups** [comment]
There is no such option, but you can scroll to the end from a 

```cpp

int ScrollToEndCallback(ImGuiInputTextCallbackData* data)
{
    if (data->EventFlag == ImGuiInputTextFlags_CallbackEdit)
        data->CursorPos = data->BufTextLen;
    return 0;
}

static char buf3[1024];
ImGui::InputTextMultiline("Edit", buf3, 1024, ImVec2(), ImGuiInputTextFlags_CallbackEdit, &ScrollToEndCallback);
```

This snippet sets current cursor position to the end of the text and cursor is scrolled to the view. You will have to customize it to not reset c

**Comment by rokups** [comment]
There is no such option, but you can force text input to scroll down by using internal details:
```cpp
static char buf3[1024];
ImGui::InputTextMultiline("Edit", buf3, 1024);

ImGuiContext& g = *GImGui;
const char* child_window_name = NULL;
ImFormatStringToTempBuffer(&child_window_name, NULL, "%s/%s_%08X", g.CurrentWindow->Name, "Edit", ImGui::GetID("Edit"));
ImGuiWindow* child_window = ImGui::FindWindowByName(child_window_name);
ImGui::SetScrollY(child_window, child_window->ScrollMax.y);
```

⚠️ Note that this code uses `imgui_internal.h` and other internal details, which will break without notice. ⚠️

**Comment by ocornut** [comment]
May be easier to manipulate cursor position of the inputtext data, and see the flag to request to track scrolling?

**Comment by rokups** [comment]
Manipulating cursor position would indeed be simpler, but it can not be manipulated if widget is not active. You would have a non-scrolling text input which scrolls to the end once user clicks it. Most likely not a desired outcome.

**Comment by dimanchique** [comment]
@rokups so is it possible to scroll it automatically? Maybe I should use another widget? Let me explain my idea. I'm making Serial port monitor, so you can connect to COM-device and send/receive some data. Received data needs to be shown in some output (and in a lot of cases you need do copy some data to work with after). Unformatted text works great, but I can't select text. If multiline text input can't autoscroll - I'm unable to finish my project)

**Comment by rokups** [comment]
I posted a code snippet for you which scrolls `InputTextMultiline()` to the end. Turn it into a function, adapt to your needs, call when you need to scroll to the end and ⚠️ fix it when it breaks ⚠️ once we rework `InputText()` internals 😉
