### ISSUE TITLE
How to apply post processing to a window that shows the image of my Framebuffer

### ISSUE THREAD

**Issue by dame-time** [ocornut/imgui#5485]
I tried to represent my framebuffer inside a window like this:
```
        ImGui::Begin("Scene");
            ImGui::BeginChild("Game Render");
                ImVec2 wSize = ImGui::GetWindowSize();

                ImGui::Image((ImTextureID)textureColorbuffer, wSize, ImVec2(0, 1), ImVec2(1, 0));
            ImGui::EndChild();
        ImGui::End();
```

and I wish to apply over this image my simple fragment shader:

```
#version 330 core
out vec4 FragColor;
  
in vec2 TexCoords;

uniform sampler2D screenTexture;

void main()
{ 
    FragColor = vec4(vec3(1.0 - texture(screenTexture, TexCoords).xyz), 1.0);
}
```

I also tried to run my screen shader before the rendering, but nothing seems to happen:
```
        screenShader.use();
        glBindVertexArray(screenVAO);
        glBindTexture(GL_TEXTURE_2D, textureColorbuffer);
        glDrawArrays(GL_TRIANGLES, 0, 6);

        createDockSpace();

        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

I know that there's a way to set up a callback, tho I'm not sure this is the right thing to do (also it's not really clear to me how to set up this)!

My result is:
![NotShaded](https://user-images.githubusercontent.com/61808196/179793735-931215fd-2427-4656-918c-583ef69b0f38.png)

What I'd like to obtain inside a window is:
![Shaded](https://user-images.githubusercontent.com/61808196/179793545-64c32eda-291b-4a3a-bbdc-718bfac12583.png)

The last image shows what I obtain if I simply comment the part where I do create the Dockspace!

**Comment by PathogenDavid** [comment]
Ideally you probably just want to render your "framebuffer" texture into another render target with your shader and call `ImGui::Image` that render target instead since that'd be closer to what your app would be doing if Dear ImGui was not involved.

> I also tried to run my screen shader before the rendering, but nothing seems to happen:

It's not totally clear exactly what you're trying to do here.

> I know that there's a way to set up a callback, tho I'm not sure this is the right thing to do (also it's not really clear to me how to set up this)!

Not my personal preference, but this is also a viable/reasonable strategy. Using it would look something like this:

```cpp
static void UseShader(const ImDrawList*, const ImDrawCmd* command)
{
    YourShaderType* shader = (YourShaderType*)command->UserCallbackData;
    shader->use();
}

// ...

ImDrawList* draw_list = ImGui::GetWindowDrawList();

draw_list->AddCallback(&UseShader, &screenShader); // Note: Your callback won't be called until much later. Make sure screenShader is still alive at the same location when ImGui_ImplOpenGL3_RenderDrawData is called!

ImVec2 wSize = ImGui::GetWindowSize();
ImGui::Image((ImTextureID)textureColorbuffer, wSize, ImVec2(0, 1), ImVec2(1, 0));

// Restore Dear ImGui's internal shader
draw_list->AddCallback(ImDrawCallback_ResetRenderState, nullptr);
```

**Comment by dame-time** [comment]
Thanks for the fast reply!
I tried the second method proposed, and though it does not seem to work, I decided to instantiate a new Shader inside the heap in order to have it there, also I made it static, though the result does not show anything inside the window!

My new code:

```
    // Static method
    void Window::useShader(const ImDrawList*, const ImDrawCmd* command)
    {
        Window::screenShader->use();
    }

// ...
        ImGui::Begin("Scene");
            ImGui::BeginChild("Game Render");
                ImDrawList* drawList = ImGui::GetWindowDrawList();
                drawList->AddCallback(&useShader, nullptr);
                ImVec2 wSize = ImGui::GetWindowSize();

                ImGui::Image((ImTextureID)textureColorbuffer, wSize, ImVec2(0, 1), ImVec2(1, 0));
                drawList->AddCallback(ImDrawCallback_ResetRenderState, nullptr);
            ImGui::EndChild();
        ImGui::End();
```
Any idea why that happens?

Also, I'm quite new to OpenGL, how can I achieve that?
>
Ideally you probably just want to render your "framebuffer" texture into another render target with your shader and call ImGui::Image that render target instead since that'd be closer to what your app would be doing if Dear ImGui was not involved.
>
