### ISSUE TITLE
Linker error using ImPlot with ImGui v1.88

### ISSUE THREAD

**Issue by bentialy** [ocornut/imgui#5486]
I am using ImGui with the newest version of ImPlot in Unreal Engine. And the project compiles and builds with ImGui version 1.87 but I am getting a linker error when I update to version 1.88 of ImGui: the error occurs whenever I reference something from ImPlot.

Do you know if ImPlot is compatible with version 1.88 of ImGui?

**Comment by PathogenDavid** [comment]
As stated at the very top of the issue template (which you seem to have ignored), build issues should be created as [GitHub Discussions](https://github.com/ocornut/imgui/discussions).

In my experience ImPlot works just fine with Dear ImGui v1.88, something is wrong in your build environment.

**Comment by ocornut** [comment]
You are likely not linking with ImPlot.
