### ISSUE TITLE
(Drag-)selecting pixels in an image

### ISSUE THREAD

**Issue by EmielBoss** [ocornut/imgui#5492]
**Version/Branch of Dear ImGui:**

Version: v1.84b
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: GCC 11.1.0
Operating System: Ubuntu 21.04

**My Issue/Question:**

I want the pixels (texels?) in an image to be drag-selectable. That is, I managed to display a small-ish (say from 25x25 up to something like 100x100) OpenGL texture with `ImGui::Image`, and now I would like the user to be able to select pixels by clickholding and dragging the mouse across the image (as if they were painting on top of the image). If a pixel is crossed a second time while dragging, it should be deselected. In the end, I want to obtain the row-major pixel IDs of the selected pixels (so I don't need the pixel data itself), and I want to visualize the current selection.

Is this at all possible? If so, what would be the most straightforward way of getting here? I am thinking of two methods: 1) Overlay a transparent button over each pixel in the `ImGui::Image`, which becomes opaque once it is selected. Each such button will need to be exactly positioned, scaled and aligned, and will need a row-major ID. 2) Instead of an image, use a table, in which each cell is toggleable and visualizes pixel intensity.
Will one of these work? Are there other (better) solutions, maybe? I'm not very well familiar with all of Dear ImGui's offerings, and I think some initial guidance would save me quite some time investigating different possibilities. I did read some documentation and browsed through this [interactive `imgui_demo.cpp`](https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html).

**Screenshots/Video**

A small illustration of how it looks in my head:
![Pixel selection example](https://user-images.githubusercontent.com/12033908/180108223-d780e45d-3334-4f62-bcb5-021969622083.jpg)

**Standalone, minimal, complete and verifiable example:**

The above image (without the Photoshopped selection stuff) was rendered using:
```
if (_showingSelectionAverage = ImGui::CollapsingHeader("Selection average image", ImGuiTreeNodeFlags_DefaultOpen)) {
    ImGui::Spacing();
    ImGui::Image((void*)(intptr_t) textureHandle, ImVec2(256, 256));
    ImGui::Spacing();
}
```

**Comment by ocornut** [comment]
Overlay a single InvisibleButton() (or use ImageButton() directly), then test IsItemActive(), IsItemHovered() etc and calculate coordinate yourself using mouse position and item position. No need for one button per pixel.

**Comment by EmielBoss** [comment]
Thank you very much! :)

My code snippet for future readers:

```
ImGui::ImageButton((void*)(intptr_t)_minimizationBuffers.selectionAverageTexture, ImVec2(256, 256), ImVec2(0,0), ImVec2(1,1), 0);
if(ImGui::IsItemActive()) {
  uint coordX = (ImGui::GetMousePos().x - ImGui::GetItemRectMin().x) / 256 * _params.imgWidth;
  uint coordY = (ImGui::GetMousePos().y - ImGui::GetItemRectMin().y) / 256 * _params.imgHeight;
  ImGui::Text("%i, %i", coordX, coordY);
}
```
