### ISSUE TITLE
Using ImGuiListClipper to clip splitted lines into one line

### ISSUE THREAD

**Issue by etaZetaKaTheta** [ocornut/imgui#5493]
Version: 1.89
Branch: docking

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: mingw gcc 12.1.0
Operating System: Windows 10

Hello,
I am trying to use the ImGuiListClipper to clip a vector of internally splitted strings.

Example of such a vector:
"Hello, my", "name", "is etaZetaKaTheta,", "nice", "to meet you.", "\n"

This is so I can render the split of words or expressions seperately.

My current "solution" for this problem is to call ImGui::TextUnformatted() for every single element in one line and then go to the next line when I hit \n. This does not really work, it doesnt allow me to scroll for some reason.

My current code:
```c++
ImGuiListClipper clipper;

            int offset; //Offset to current line in outputBuffer

            clipper.Begin(outputBufferSize, ImGui::GetTextLineHeightWithSpacing());
            while (clipper.Step())
            {
                for (int line_no = clipper.DisplayStart; line_no < clipper.DisplayEnd; line_no++)
                {
                    for (int i = offset; i < outputBuffer.size(); i++)
                    {
                        std::string currentToken = outputBuffer.at(i);
                        ImGui::TextUnformatted(currentToken.c_str());
                        /* Ignore this, this is for colorization std::vector<std::string> tokenizedInput = tokenizeString(input, ",");
                        if (containsStrings(currentToken, tokenizedInput))
                        {
                            ImGui::PushStyleColor(ImGuiCol_Text, filterColor);
                            ImGui::TextUnformatted((currentToken).c_str());
                            ImGui::PopStyleColor();
                        }
                        else
                        {
                            ImGui::TextUnformatted((currentToken).c_str());
                        }*/

                        offset++;
                        
                        if (!(currentToken == "\n"))
                        {
                            ImGui::SameLine();
                        }
                        else
                        {
                            break;
                        }
                    }
                }
            }
            clipper.End();
```
Best regards,
etaZetaKaTheta

**Comment by ocornut** [comment]
You are calling clipper code and not doing anything with it (not using the line_no value) nor honoring its request. 

You need your data structure to make it possible to randomly access the items of any line N once you have that you can use the clipper.

**Comment by etaZetaKaTheta** [comment]
Thank you for your comment, i'll try to keep track of the size of each line, so that i can use line_no to jump to the line via the index. I'll report my possible solution later.

**Comment by etaZetaKaTheta** [comment]
News:
It is kinda working, but the clipper is displaying it weirdly cut in half.

My code:

```c++
ImGuiListClipper clipper;

            clipper.Begin(outputBufferSize, ImGui::GetFrameHeightWithSpacing());
            while (clipper.Step())
            {
                for (int line_no = clipper.DisplayStart; line_no < clipper.DisplayEnd; line_no++)
                {
                    int offset = 0;
                    for (int i = 0; i < line_no; i++)
                    {
                        offset += lineIndexOffset.at(i);
                    }

                    for (int i = offset; i < offset + lineIndexOffset.at(line_no); i++)
                    {
                        std::string currentToken = outputBuffer.at(i);
                        ImGui::TextUnformatted(currentToken.c_str());
                        /* Ignore this, this is for colorization std::vector<std::string> tokenizedInput = tokenizeString(input, ",");
                        if (containsStrings(currentToken, tokenizedInput))
                        {
                            ImGui::PushStyleColor(ImGuiCol_Text, filterColor);
                            ImGui::TextUnformatted((currentToken).c_str());
                            ImGui::PopStyleColor();
                        }
                        else
                        {
                            ImGui::TextUnformatted((currentToken).c_str());
                        }*/

                        

                        if (!(currentToken == "\n"))
                        {
                            ImGui::SameLine();
                        }
                       
                    }
                }
            }
            clipper.End();
```
I just made a vector of ints, that are storing the sizes for each line and I am calculating the offset of those.
My single problem is that it is cut in half:
![Screenshot 2022-07-21 121715](https://user-images.githubusercontent.com/72048877/180191386-6e4ebed6-856c-4eec-a660-040c4c068599.png)

Why is it doing that?

Best regards,
etaZetaKaTheta

**Comment by etaZetaKaTheta** [comment]
It crashes, when I don't specify "ImGui::GetFrameHeightWithSpacing()".
Error: Assertion failed: ItemsHeight > 0.0f && "Unable to calculate item height! First item hasn't moved the cursor vertically!"

**Comment by ocornut** [comment]
You have bugs in your code keeps hammering at it.

**Comment by etaZetaKaTheta** [comment]
Hello,
I fixed the bugs and everything is working flawlessly. Thank you, I really appreciate it. 
Should I comment my fixed code for others, or is that unnecessary?
Best regards,
etaZetaKaTheta

**Comment by ocornut** [comment]
> Should I comment my fixed code for others, or is that unnecessary?

Well would you like to potentially help others after you’ve been given help? I think you should post the fixed code!

**Comment by etaZetaKaTheta** [comment]
This is the fixed code: 

![Screenshot 2022-07-21 152354](https://user-images.githubusercontent.com/72048877/180224424-ca35dd7f-4e53-474e-a807-05e06f577fdf.png)

The main culprit is my idiotism, because I accidentally pushed a "\n" after every line, which caused the clipper to be confused.

**Comment by ocornut** [comment]
You could avoid recalculating offset like right now your code will be O(N*log N) ish, keep offset outside the clipper loop, and change the for to a while.

**Comment by etaZetaKaTheta** [comment]
Do you mean the clipper.step() loop or the for loop underneath?

**Comment by etaZetaKaTheta** [comment]
Sorry if I asked something stupid right now.

**Comment by etaZetaKaTheta** [comment]
Thank you!
