### ISSUE TITLE
How do you render on the background of the window.

### ISSUE THREAD

**Issue by rxantos** [ocornut/imgui#5495]
I tried to use a window rectangle and draw to it. Works except that the title of the window is Hidden by the texture. I need to be able to draw during the background phase of a window. Before the title is drawn.

Is this possible to do this without rewriting internal parts of the library?

**Comment by ocornut** [comment]
Your question is too ambiguous. Please provide more details.

**Comment by ocornut** [comment]
Closing as lacking details. also this appear to relate to your other questions which you haven't provided enough details about it. Please be mindful about this. You can add details to your existing questions if you want them.
