### ISSUE TITLE
GetWindowDrawList and debug window

### ISSUE THREAD

**Issue by pp9999** [ocornut/imgui#5498]
Version/Branch of Dear ImGui:

Version: 1.88
Branch: master
Back-ends: imgui_impl_opengl3.cpp, ImGui_ImplWin32
Operating System: windows
Compiler: VS2022, cpp

So when I try to render some lines and text on screen it creates debug window. That window is not needed.
```
auto pDrawList = ImGui::GetWindowDrawList();
pDrawList->AddRect(ImVec2(10, 10), ImVec2(100, 100), ImColor(255, 0, 0));
```

**Comment by ocornut** [comment]
If you ask for the the draw list of that implicit debug window is enables the window. This is normal.

You may want to use GetForegroundDrawList() or GetBackgroundDrawList(). Check Demos->Examples->Custom Rendering.
