### ISSUE TITLE
interpolation widget

### ISSUE THREAD

**Issue by velkyel** [ocornut/imgui#55]
i'm missing simple interpolation widget editor like http://cubic-bezier.com , simply t=<0, 1>, two movable inner points.  through sliders it's unintuitive for editing.  Do you planning something like that?  if not, i'll try to implement myself as imgui_user.inl

**Comment by r-lyeh** [comment]
Code continued from @jarikomppa 's in #123

https://gist.github.com/r-lyeh/40d4fd0ea157ab3a58a4

![image](https://cloud.githubusercontent.com/assets/878187/13051011/3b464e14-d3f7-11e5-9ab0-8edd05ebd157.png)


Walking thru the curve at a fixing step is not exactly the best way to create it anyways :P

**Comment by r-lyeh** [comment]
v1.2

![image](https://cloud.githubusercontent.com/assets/878187/13077101/1d1d7f28-d4b7-11e5-997b-9fef05faa4d8.png)

Feat. [smooth spline curves from iq's](http://iquilezles.org/www/articles/minispline/minispline.htm). Get smooth/interpolated value with `CurveValueSmooth()`

**Comment by ocornut** [comment]
Closing this and moving to #786
