### ISSUE TITLE
How to render result of each step from recursive function without drawing new frame in side the recursive function itself

### ISSUE THREAD

**Issue by tongvietdung** [ocornut/imgui#5500]
**Version/Branch of Dear ImGui:**

Version: 1.89 WIP
Branch: docking _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp 
Compiler: GNUC 12 
Operating System: EndeavourOS Linux x86_64

**My Issue/Question:**
This is not an issue but more of a question. I am really new to GUI in general and I really cannot figure out how to solve this problem.
I'm trying to visualize each step of a backtracking algorithm so solve sudoku. What I've done so far is calling the recursive solve function inside the main loop, clear/draw/render the current result inside the recursion itself. However, if I want to render any more stuff, I have to write the render data inside the recursive function too. Is there any other more elegant way to visualizing a backtracking algorithm? Or any way to pass the result of each recursive step out side the recursion and render it, then continue with the recursion?

main.cpp:
```
while (!glfwWindowShouldClose(window)) {
     if (!(*finished) {
          result = solve(sudoku, finished, window);
     } else {
          \* Render the end result nornally *\
     }
}
```

solve function:
```
bool solve(vector<vector<int>> sudoku, bool* finished, GLFWwindow* window){
        glClearColor(0.45f, 0.55f, 0.60f, 1.00f);
        glClear(GL_COLOR_BUFFER_BIT);

	ImGui_ImplOpenGL3_NewFrame();
	ImGui_ImplGlfw_NewFrame();
	ImGui::NewFrame();
        
        \* draw current result *\

        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        int display_w, display_h;
        glfwGetFramebufferSize(window, &display_w, &display_h);
        glViewport(0, 0, display_w, display_h);
        glfwSwapBuffers(window);

        solve(new_sudoku, finished, window);
}
```

**Comment by ocornut** [comment]
Sorry this is not an imgui related question we can’t be answering those.
