### ISSUE TITLE
Insert current frame keyboard input while focusing InputText

### ISSUE THREAD

**Issue by Willy-JL** [ocornut/imgui#5505]
**Version/Branch of Dear ImGui:**

Version: 1.82
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: GLFW (via pyimgui)
Operating System: Arch Linux

**My Issue/Question:**

I have a single window with a `InputText` search bar and I wanted to make it so that when the user starts typing it automatically focuses the `InputText`.
The focusing part is easy with a simple `SetKeyboardFocusHere()` call when any of `io.KeysDown` is true, my issue is that by doing that the first input that triggered the focus is lost.

The closest I got is by iterating over `io.KeysDown` and converting the index to a character with `glfwGetKeyName()` and `glfwGetKeyScancode()` and then adding that character with `io.AddInputCharactersUTF8()` between `SetKeyboardFocusHere()` and `InputText()`, but this only works for lowercase characters, it does not consider modifiers such as shirt and ctrl, and also backspace and analogous don't work.
I tried with `CaptureKeyboardFromApp(true)` and setting the keyboard focus, but nothing. Also tried keeping my own copy of each frame's chars with `glfwSetCharCallback()` and then manually readding those with `io.AddInputCharacter()` right before `InputText()`, but nothing.

How should I go about doing this, or is this not even reasonably possible?

**Comment by rokups** [comment]
You can access pending text input through `ImGui::GetIO().InputQueueCharacters`.

**Comment by Willy-JL** [comment]
> You can access pending text input through `ImGui::GetIO().InputQueueCharacters`.

Ah, I missed that since it's in the internal section and so it's not directly available  in pyimgui.
I'll work on exposing it myself, but will that also make modifiers like ctrl and special keys like backspace work properly?

**Comment by rokups** [comment]
`InputQueueCharacters` is just a final text fed to imgui by the backend, so it will be whatever keyboard produced (text based on keyboard layout, upper/lower case etc). You can append it to `InputText()` buffer before setting keyboard focus (however if you start typing and press ESC - imgui wont clear such manually appended character, so it is not perfect). Backspace you will also have to handle yourself. There should not be many keys that need such handling.

```cpp
ImGui::Begin("Auto-focus");
static char buf[100];
ImGui::InputText("Input", buf, IM_ARRAYSIZE(buf));
ImGuiContext& g = *GImGui;
if (!ImGui::IsItemActive())
{
    if (ImGui::IsKeyDown(ImGuiKey_Backspace))
    {
        if (int len = strlen(buf))
            buf[len - 1] = 0;
        ImGui::SetKeyboardFocusHere(-1);
    }
    else
    {
        for (ImGuiKey k = ImGuiKey_NamedKey_BEGIN; k < ImGuiKey_NamedKey_END; k++)
            if (ImGui::IsKeyDown(k))
            {
                if (!io.InputQueueCharacters.empty())
                {
                    char text[10];
                    ImTextStrToUtf8(text, IM_ARRAYSIZE(text), io.InputQueueCharacters.begin(), io.InputQueueCharacters.end());
                    strcat(buf, text);
                }
                ImGui::SetKeyboardFocusHere(-1);
                break;
            }
    }
}
if (ImGui::IsItemActivated())
    g.InputTextState.ClearSelection();
ImGui::End();
```

**Comment by Willy-JL** [comment]
Very nice snippet, thanks! In the end I had to do things a little different in order to not have to modify the python bindings but the concept is the same you suggested. Also this might be useful to someone else, maybe mark as `useful widgets`? Either way thank you again!
