### ISSUE TITLE
How to check GImGui->CurrentWindow->DC.LastItemId in newer ImGui version?

### ISSUE THREAD

**Issue by icehuli** [ocornut/imgui#5507]
**Version/Branch of Dear ImGui:**

Version: v1.89
Branch: 

**My Issue/Question:**

How to implement the following logic in newer ImGui version? 

```
  if (g.ActiveIdPreviousFrame)
    return g.ActiveIdPreviousFrame == GImGui->CurrentWindow->DC.LastItemId;
```

**Comment by rokups** [comment]
Use `GImGui->LastItemData.ID`.

**Comment by icehuli** [comment]
I was trying to check if `enter` is pressed on a given `InputInt2`. 
Finally I came up with the following. Is it correct?
```
  ImGui::InputInt2("indices", ...);
  const auto input_indices_entered = (ImGui::IsItemDeactivated() && ImGui::IsKeyPressed(ImGuiKey_Enter));
```
