### ISSUE TITLE
New version Cocos2d-x implement

### ISSUE THREAD

**Issue by namkazt** [ocornut/imgui#551]
Hi,

i just rewrote a new version with fix and improve from C0i version.

Features: 
Programable pipline
Add ImageButton create with SpriteFrameCached
Add Toggle state for ImageButton
Fix Cocos2d-x Implement
Auto add ImGUI layer on top whenever create or change Scene

Link: https://github.com/namkazt/cocos2d-x-ImGui

**Comment by tangyiyang** [comment]
this is cool

**Comment by ocornut** [comment]
It would be nice if you organized this as an Example application following exactly the same standard of all other folders under examples/

Right now I cannot do anything with this code.

**Comment by yinjimmy** [comment]
Would you like to send a pr to https://github.com/c0i/imguix ?

**Comment by ocornut** [comment]
It would be more useful to make a PR for imgui if one of you would be willing to follow the structure or other imgui examples :)

**Comment by namkazt** [comment]
yeah, i will prepare if have some time.






*
              Best Regards.Mr. Nam NguyễnPhone No. : 012.9595.8685*

*Skype Account : nam.kazt*



2016-03-22 15:08 GMT+07:00 omar <notifications@github.com>:

**Comment by ocornut** [comment]
Closing this as dropped/outdated.
Please refer to the new examples/ design if someone wants to resurrect this into a standalone imgui_impl_cocos2dx.cpp binding.

**Comment by Mjarkiew** [comment]
Hey, it seems like I was able to resurrect this, at least I've migrated it to OpenGL 3 using provided examples and it seems to be working fine, I've added a demo here:

https://github.com/Mjarkiew/cocos2dx-imgui

**Comment by yinjimmy** [comment]
OK, I'll check your code and update https://github.com/c0i/imguix .

**Comment by halx99** [comment]
News:
Currently I integrate cocos2d-x-4.0 https://github.com/Xrysnow/cocos2d-x-imgui to [egnx](https://github.com/c4games/engine-x/tree/master/extensions/ImGuiEXT) which is another fork of cocos2d-x-4.0 and do some improvements:
* Simple API, more easy to use ```addRenderLoop/removeRenderLoop``` present ImGui GUI widgets
* Optimize call pipeline flow, support add/remove Node to Scene at ImGui render loop without container iterator damage
* Calculate deltaTime at ```ImGui_ImplCocos2dx_NewFrame``` to avoid error when ```cc.Director``` paused
* Refine ```Init/Shutdown```, Restore all callbacks for glfw to solve recreate ```ImGuiEXT``` instance support
* Use FOURCC for key of ImGui render loop
Notes: And multi-viewports works well on windows, but doesn't works on mac osx, see follow screenshot:
![image](https://user-images.githubusercontent.com/6977319/92308797-03da5680-efd3-11ea-9a3e-f0dbb562de99.png)

**Comment by yinjimmy** [comment]
NEWS:
https://github.com/c0i/imguix updates with docking branch and supports multi-viewport.

Sorry for disturbing you.

**Comment by halx99** [comment]
Does it works on macOS?

**Comment by yinjimmy** [comment]
> Does the multi-view works on macOS with cocos2d-x-4.0 metal?

No, example_apple_metal / example_sdl_metal not support multi-view.
So, I think cocos2d-x-4.0 can not support it too.

**Comment by yinjimmy** [comment]
> Does the multi-view works on macOS with cocos2d-x-4.0 metal?

backends/imgui_impl_metal.mm:
// Missing features:
//  [ ] Renderer: Multi-viewport / platform windows.
