### ISSUE TITLE
How to open webpages through imgui widgets ??? 

### ISSUE THREAD

**Issue by svkvarun43** [ocornut/imgui#5510]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master

**My Issue/Question:**

Hi, I am interested to know if we can add hyperlinks (url) to open up using Imgui

eg:

Press button widget -> open up a webpage (for example google)

Sorry that i cannot provide any information, but if there is an API to get this feature, please do share

**Comment by ocornut** [comment]
Opening a webpage or external applications is out of the scope of Dear ImGui.

If I type "how to open a webpage in imgui" on google I stumble on this question:
https://stackoverflow.com/questions/71712920/how-to-open-a-webpage-in-imgui

Which I have answered myself, and copying answer here:

----

It's not really a dear imgui question, more about how to use your OS API to perform that.

Something like that would work:

```cpp
void OsOpenInShell(const char* path)
{
#ifdef _WIN32
    // Note: executable path must use backslashes!
    ::ShellExecuteA(NULL, "open", path, NULL, NULL, SW_SHOWDEFAULT);
#else
#if __APPLE__
    const char* open_executable = "open";
#else
    const char* open_executable = "xdg-open";
#endif
    char command[256];
    snprintf(command, 256, "%s \"%s\"", open_executable, path);
    system(command);
#endif
}
```

**Comment by ocornut** [comment]
This was formalized today in a portable manner with the `io.PlatformOpenInShellFn` handler and new `TextLinkOpenURL()` widget, see https://github.com/ocornut/imgui/issues/7660#issuecomment-2203540631
![hyperlink](https://github.com/ocornut/imgui/assets/8225057/9b4be2e2-5e03-4101-ba74-0c93f37a7afd)

**Comment by beekayer** [comment]
The feature works great but my terminal is flood with messages from ImGui whenever the link is clicked.
OS:  Ubuntu 24.04
ImGui Version: 1.91.9b
frontend/backend config:  SDL2/SDL2 renderer
test engine is enabled but not being used

terminal output when link is pressed (note, Chrome opened to link no problem, everything works)

`MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_3D_FEATURES
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_CAPSET_QUERY_FIX
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_RESOURCE_BLOB
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_HOST_VISIBLE
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_CROSS_DEVICE
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_CONTEXT_INIT
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_SUPPORTED_CAPSET_IDs
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_EXPLICIT_DEBUG_NAME
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_CREATE_FENCE_PASSING
MESA: info: virtgpu backend not enabling VIRTGPU_PARAM_CREATE_GUEST_HANDLE
MESA: error: DRM_IOCTL_VIRTGPU_GET_CAPS failed with Permission denied
MESA: error: DRM_IOCTL_VIRTGPU_CONTEXT_INIT failed with Permission denied, continuing without context...
MESA: error: DRM_VIRTGPU_RESOURCE_CREATE_BLOB failed with Permission denied
MESA: error: Failed to create virtgpu AddressSpaceStream
MESA: error: vulkan: Failed to get host connection
MESA: error: DRM_VIRTGPU_RESOURCE_CREATE_BLOB failed with Permission denied
MESA: error: Failed to create virtgpu AddressSpaceStream
MESA: error: vulkan: Failed to get host connection
MESA: error: DRM_VIRTGPU_RESOURCE_CREATE_BLOB failed with Permission denied
MESA: error: Failed to create virtgpu AddressSpaceStream
MESA: error: vulkan: Failed to get host connection
MESA: error: DRM_VIRTGPU_RESOURCE_CREATE_BLOB failed with Permission denied
MESA: error: Failed to create virtgpu AddressSpaceStream
MESA: error: vulkan: Failed to get host connection
MESA: error: DRM_VIRTGPU_RESOURCE_CREATE_BLOB failed with Permission denied
MESA: error: Failed to create virtgpu AddressSpaceStream
MESA: error: vulkan: Failed to get host connection
MESA: error: DRM_VIRTGPU_RESOURCE_CREATE_BLOB failed with Permission denied
MESA: error: Failed to create virtgpu AddressSpaceStream
MESA: error: vulkan: Failed to get host connection
[11450:11450:1004/094150.484794:ERROR:ui/events/platform/wayland/wayland_event_watcher.cc:47] libwayland: warning: queue 0x2eec02229040 destroyed while proxies still attached:

[11450:11450:1004/094150.484887:ERROR:ui/events/platform/wayland/wayland_event_watcher.cc:47] libwayland:   wl_buffer#42 still attached

[11450:11450:1004/094150.484931:ERROR:ui/events/platform/wayland/wayland_event_watcher.cc:47] libwayland:   wl_buffer#45 still attached

[11450:11450:1004/094150.484968:ERROR:ui/events/platform/wayland/wayland_event_watcher.cc:47] libwayland:   wl_shm_pool#47 still attached
`
