### ISSUE TITLE
Anyone can edit the wiki pages

### ISSUE THREAD

**Issue by MorsGames** [ocornut/imgui#5511]
I'm not sure if this is the right place to report this, but it seems like there's no limitation to who can edit the wiki pages, and some people seem to be taking advantage of this.
![image](https://user-images.githubusercontent.com/16962745/181294951-f812983c-81f6-4ce9-bf7a-0faaadd18ee9.png)

I reverted back the changes (which honestly was an accident, I didn't think GitHub would actually let me, hope you guys don't mind!) but I think it would be a good idea to restrict editing to collaborators only so no future incidents like this happen again.

EDIT: Ended up reading through the wiki and including the part about community help being needed. As much as I like community contribution with open source projects I feel like with a project of this size it's kind of risky to make editing the wiki fully public. I mean, this time it was just some IP grabbers, but I could see the phishing sites being added too.

This is probably something up to debate, but I thought I'd bring that to attention regardless.

**Comment by ocornut** [comment]
Thank you for reverting and bringing back to attention.
At the moment we are general lacking quality contributions and I don't think it's worth restricting access. Vandalism is fairly rare.
