### ISSUE TITLE
Sub-menu items being ignored on click 

### ISSUE THREAD

**Issue by billyeatcookies** [ocornut/imgui#5512]
**Version/Branch of Dear ImGui**

Version: 1.89 WIP (18805)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC
Operating System: Windows 10

<details>
<summary>Config/Build Information</summary>
<pre>
Dear ImGui 1.89 WIP (18805)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1932
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
</pre>
</details>

**My Issue/Question:**
I'm providing a sample to explain the issue. 
```cpp
if (ImGui::BeginPopup("ContextMenu")) {
    if (ImGui::MenuItem("First")) print("First");
    if (ImGui::MenuItem("Second")) print("Second");
    ImGui::EndPopup();
}

if (ImGui::IsMouseReleased(1))
    ImGui::OpenPopup("ContextMenu");
```
Here i have simple popup menu, which have items -- first and second, on click, will print some text. The menu items are printing text as they are supposed to. 

Now, I add a sub menu to the popup as follows:
```cpp
if (ImGui::BeginPopup("ContextMenu")) {
    if (ImGui::MenuItem("First")) print("First");
    if (ImGui::MenuItem("Second")) print("Second");
    
    if (ImGui::BeginMenu("More")) {
        if(ImGui::MenuItem("Third")) print("Third");
        ImGui::EndMenu();
    }
    ImGui::EndPopup();
}

if (ImGui::IsMouseReleased(1))
    ImGui::OpenPopup("ContextMenu");
```
While all the items in main popup are doing what they are supposed to do, the items in sub menu are not doing anything. My breakpoint for the sub menu item Third was ignored, the if statement was never executed. 

The item Third on click was supposed to print "Third", but its not doing it. 

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");

if (ImGui::BeginPopup("ContextMenu")) {
    if (ImGui::MenuItem("First")) print("First");
    if (ImGui::MenuItem("Second")) print("Second");
    
    if (ImGui::BeginMenu("More")) {
        if(ImGui::MenuItem("Third")) print("Third");
        ImGui::EndMenu();
    }
    ImGui::EndPopup();
}

if (ImGui::IsMouseReleased(1))
    ImGui::OpenPopup("ContextMenu");

ImGui::End();
```

**Comment by PathogenDavid** [comment]
I can't reproduce this using your snippet at the current head of `master` (e99c4fc6688e218a0e5da50f56638aebab45da9b)

Can you double check the issue happens in `example_glfw_opengl3`?

**Comment by billyeatcookies** [comment]
I just rechecked my sample code. You are right, sorry, it doesn't reproduce my issue. Still I'm facing this issue on my actual application, yet I'm not sure what is going wrong. I will do more debugging to see whats wrong.

**Comment by ocornut** [comment]
There is now a Debug Log you can access in Demo>Tools>Debug Log, enable [X] Popups and [X] Focus, it may help you understand if something is conflicting with that menu item being opened.

Note that using IsMouseReleased(1) to open a popup is likely going to interfere with things. It’s incorrect you should be testing for hovering. There are helpers functions to OpenPopup based on that common condition.

**Comment by billyeatcookies** [comment]
@ocornut that is right, but I'm pretty new to the library so I was using a boilerplate from ImNodes libarary by @rokups. 

Also I just figured out what was going wrong with my menus. 
```cpp
ImGui::Begin("Example Bug");

if (ImGui::BeginPopup("ContextMenu")) {
    if (ImGui::MenuItem("First")) print("First");
    if (ImGui::MenuItem("Second")) print("Second");
    
    if (ImGui::BeginMenu("More")) {
        if(ImGui::MenuItem("Third")) print("Third");
        ImGui::EndMenu();
    }

    // This part was unnecessary
    if (ImGui::IsAnyMouseDown() && !ImGui::IsWindowHovered())
        ImGui::CloseCurrentPopup();

    ImGui::EndPopup();
}

if (ImGui::IsMouseReleased(1) && ImGui::IsWindowHovered() && !ImGui::IsMouseDragging(1))
{
    ImGui::FocusWindow(ImGui::GetCurrentWindow());
    ImGui::OpenPopup("NodesContextMenu");
}

ImGui::End();
```
I didn't include this in my example, because I thought it might not be the problem causing part, sorry.
```cpp
 if (ImGui::IsAnyMouseDown() && !ImGui::IsWindowHovered())
     ImGui::CloseCurrentPopup();
```
I think on mouse down event, this closes the popup first, so then the sub menu items are also gone. Removing this part of code fixed the issue.

---

I'm looking for an API documentation for ImGui, it would be nicer to have documentation written than looking at the demo and figuring it out theirselves for some users. I hope you will consider it, I would also love to participate in this project. Keep it going always, you are spending alot of time for the community, thank you omar, and all other contributors.

**Comment by PathogenDavid** [comment]
> I'm looking for an API documentation for ImGui, it would be nicer to have documentation written than looking at the demo and figuring it out theirselves for some users.

Make sure you read through `imgui.h`, the majority of the API documentation lives there.

**Comment by billyeatcookies** [comment]
Sure okay, thats good. But also, having a documentation site would be nice too right? that would also be more beginner friendly mayhaps 🤗

**Comment by ocornut** [comment]
```
if (ImGui::IsMouseReleased(1) && ImGui::IsWindowHovered() && !ImGui::IsMouseDragging(1))
{
    ImGui::FocusWindow(ImGui::GetCurrentWindow());
    ImGui::OpenPopup("NodesContextMenu");
}
```
This is also technically incorrect and too complicated, you can use BeginPopupContextWindow() in place of the BeginPopup() call.

**Comment by billyeatcookies** [comment]
@ocornut Thank you so much for pointing that out, I wasn't aware of that function, its handled a lot cleanly now 🤗
