### ISSUE TITLE
Appending to an exiting dock node's tab bar, using DockNodeBeginAmendTabBar, causes an assert when closing a window.

### ISSUE THREAD

**Issue by Luci404** [ocornut/imgui#5515]
**Version/Branch of Dear ImGui:**
Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**
Appending to an exiting dock node's tab bar, using DockNodeBeginAmendTabBar, causes an assert when closing a window.
It only crashes if the window is closed with a button inside the window. This leads be to believe that it's a focus issue.

```c++
ImGuiID dockspace_id = ImGui::GetID("DockSpace");
ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), dockspace_flags, window_class);

// If this section is commented out, the crash will not occur.
ImGuiDockNode* dockNode = (ImGuiDockNode*)GImGui->DockContext.Nodes.GetVoidPtr(dockspace_id);
if (ImGui::DockNodeBeginAmendTabBar(dockNode))
{
	/* Render tab item... */
	ImGui::DockNodeEndAmendTabBar();
}
```

```
Assertion failed: window == window->RootWindow, file C:\Dev\KhaosSystems\Raijin\Vendor\Amaterasu\Vendor\imgui\imgui.cpp, line 7333
```

https://gyazo.com/956366478d78709d7f165422ed93708c

This might just be me using this incorrectly, but I am unable to find any example of the intended use.

**Comment by ocornut** [comment]
Pushed fixes e926a66 + 0e95cf0 + 0abe7d1 + b12e056 this should work now.
Some of the changes for WindowBG rendering caused issues with this and it's not a very tested/supported path yet, although we certainly aim for it to be. We'll add regression tests for it.

Interesting in hearing how you used it.
I think we'll add facilities for requesting space at either end which could be used for logo/branding.

**Comment by Luci404** [comment]
Perfect, it now works as expected!

> Interesting in hearing how you used it.
I am using using it for a menu button. We choose not to have a file menu to allow for some additional screen space and ecurage the use of shortcut keys as well as our command system(works very much like vscode or blenders search menu), so we added a leading button for stuff that normally goes in the title-menus.

![image](https://user-images.githubusercontent.com/36606323/183583580-fb42f1e2-9603-49cc-9aac-12b8f8755c1a.png)
![image](https://user-images.githubusercontent.com/36606323/183583620-a371f2ce-d155-4361-ac60-f6d3db399c79.png)

**Comment by Luci404** [comment]
> I think we'll add facilities for requesting space at either end which could be used for logo/branding.

This would be amazing! Since we are using a custom window title, window functionality is currently rendered kinda awkwardly on top just hijacking the cursor position.

![image](https://user-images.githubusercontent.com/36606323/183584535-cdc20dd0-268d-43e4-a6aa-0c6d3dde6a36.png)
