### ISSUE TITLE
Imgui Image aspect ratio not fixed

### ISSUE THREAD

**Issue by Krish2882005** [ocornut/imgui#5516]
Hello,

I am rendering my SDL2 scene to a texture and then rendering it via Imgui Image

However, this `	ImGui::Image(Scene::GetCurrent()->GetTexture().texture, ImGui::GetWindowSize());
` ofcourse make it change it's aspect ratio according to the window

So is there way to maintain the aspect ratio of the actual scene, which can be for example, 1920x1080?

Version: SDL's SDL Renderer, Latest Docking Branch

**Comment by PathogenDavid** [comment]
There isn't a built-in way to do this since Dear ImGui doesn't know the size of your texture. You'll have to do the math yourself.
