### ISSUE TITLE
ImGui::Button(Char*) not working

### ISSUE THREAD

**Issue by Sammyueru** [ocornut/imgui#5520]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: Releases

**GLFW3/MSVC++/Windows**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp + imgui_impl_opengl3_loader.cpp
Operating System: Windows

**Why doesn't this work:**
So I'm trying to create a search system but once it's supposed to do ImGui::Button(it->cname) is stops working and it->cname is a
const char * but yet still nothing works even it->name.c_str() doesn't work

**CODE:**
```
if (ImGui::Begin("Node Editor - Add Node - Search - Results", &nodeEANSeResultsOpen))
{
	ImGui::InputText("Node Search", nodeEditorAddNodeSearch, 32, ImGuiInputTextFlags_CharsUppercase);
	ImGui::Text("Search Results:");

	int i = 0;

	for (ENode* it : node_types)
	{
		if (it->name.find(std::string(nodeEditorAddNodeSearch)))
		{
			//continue;
			//ImGui::Text(node_types[i]->cname);
			ImGui::Button(it->cname);
		}

		i++;
	}

	ImGui::End();
}
```
Here's what seems to be happening:
![image](https://user-images.githubusercontent.com/60794497/181847696-d78f63a5-7313-42d0-9528-d8f185a508c5.png)
But I can't figure out how to fix it.

Thanks in advance.

**Comment by ocornut** [comment]
Than an issue in your code, your pointer/data is invalid or not zero-terminated. A printf() call would lead to same issue.
