### ISSUE TITLE
Is there a "box" like widget that spans to the content that it has?

### ISSUE THREAD

**Issue by GasimGasimzada** [ocornut/imgui#5525]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp 
Operating System: Windows

**My Issue/Question:**

Is there a widget in ImGui that I can create like how we create windows and just style the widget however I like without needing to worry about the sizing. Something like this:

```cpp
// Push styles that is only applied
// to this box
ImGui::BoxBegin("Light");
  ImGui::InputText(...);
  ImGui::Label(...);
ImGui::BoxEnd();
```

I tried to use the "child window" widget (`Begin/EndChild`) but this widget spans to the end of the window vertically. I want it to span horizontally but not vertically.

Is there a widget like this (maybe there is a flag in child window one but I couldn't find one)? If not, what do I need to do to create a custom one? Is there a baseline that I can use (e.g `ImGui::Begin` to handle the IDs etc; and calculate sizing somehow)? 

For a custom implementation, I have some ideas. I can get the current position when the `Begin` is called and get the new position after `End` is called and determine the height that way. However, I am not sure where I can store the "initial height" within ImGui. Does ImGui have a way to store custom properties and reuse them later or do I need to handle this manually in my own structures?

**Screenshots/Video**

Here is what I am trying to achieve.

![image](https://user-images.githubusercontent.com/807231/181887962-44344e56-3301-4703-b04c-089ef792a6c0.png)

**Comment by ocornut** [comment]
See #1496 
The simplest is to use BeginGroup/EndGroup and then draw a rectangle using GetContentSizeAvail().x for width and GetItemRectMin().y GetItemRectMax().y for vertical coordinates, but that issue has many ideas of that kind. Best to post your messages there.

**Comment by GasimGasimzada** [comment]
Thank you! Posted my question there
