### ISSUE TITLE
Collapsing a window with a table (as root child) causes segfault

### ISSUE THREAD

**Issue by pfaion** [ocornut/imgui#5526]
**Config/Build Information**

```
Dear ImGui 1.89 WIP (18804)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201402
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: __linux__
define: __GNUC__=4
define: __clang_version__=10.0.0 
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

I use the docking branch, currently on commit cb8ead1f7198924f97e52973d115e1d4eaeda2f3.

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl.cpp
Compiler: clang via CMake
Operating System: Ubuntu 20.04.4

**My Issue/Question:**

I have a table as the only element of a window. Minimal example:

```cpp
ImGui::Begin("Main");

ImGui::BeginTable("test_table", 2);
ImGui::TableNextRow();
ImGui::TableNextColumn();
ImGui::Text("left");
ImGui::TableNextColumn();
ImGui::Text("right");
ImGui::EndTable();

ImGui::End();
```

When I collapse this window, I get a segfault at: https://github.com/ocornut/imgui/blob/cb8ead1f7198924f97e52973d115e1d4eaeda2f3/imgui_tables.cpp#L1679

Originally I hit this issue when I wanted to add another window as a tab to the window with the table, which caused the same segfault.

I was a bit confused since the tables in the demo window actually don't have this problem. But the demo window only has tables nested somewhere in child frames. I tried the following:

```cpp
ImGui::Begin("Main");
ImGui::BeginChild("Child");

ImGui::BeginTable("test_table", 2);
ImGui::TableNextRow();
ImGui::TableNextColumn();
ImGui::Text("left");
ImGui::TableNextColumn();
ImGui::Text("right");
ImGui::EndTable();

ImGui::EndChild();
ImGui::End();
```

And this does **not** cause the segfault anymore. So it appears the issue only happens when the table is not nested into a child frame. This actually seems to be a good workaround for me, but I thought it might still be worth reporting this.

I hope this helps, let me know if you need any more information from me.

**Comment by ocornut** [comment]
Read any of the 20+ examples of using BeginTable() in the demo and you’ll find what your issue is.

I will however add an additional assert with explicit comment in TableNextRow().

**Comment by pfaion** [comment]
Oh wow, I looked at this so much, but missed that the whole table has to be wrapped in an `if()`...

Thanks for the pointer. Sorry for the noise!

**Comment by ocornut** [comment]
No worries. We’d rather have those posted here so at least other people can stumble on it.

I did have asserts in variety of other functions but TableNextRow() was missing one and it’ll definitely be an improvement to add it there!

**Comment by ocornut** [comment]
No worries. I’d rather have those posted here so at least other people can stumble on it.

I did add asserts in variety of other functions but TableNextRow() was missing one and it’ll definitely be an improvement to add it there!
