### ISSUE TITLE
Windows won't dock to dockspace

### ISSUE THREAD

**Issue by TheExeQ** [ocornut/imgui#5530]
```
Dear ImGui 1.89 WIP (18804)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1932
define: _MSVC_LANG=202004
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,681.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: latest
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Compiler: MSVC 2022
Operating System: Win 10

**My Issue/Question:**

I can't dock my windows to dockspace? the demo window works fine but mine doesn't unless they are already docked to eachother then it kind of works but not really as expected either cus it breaks up the docked windows and only one gets docked and also when i resize the application the imgui window stays the same size and doesn't adapt to the new size of the application. I have looked in the demo file to find anything that might get it to work but havn't had any success

**Screenshots/Video**

https://user-images.githubusercontent.com/26822321/182049379-17a5c56f-7c05-42f9-8b12-71a753609c72.mp4

**Comment by PathogenDavid** [comment]
Make sure you submit any dockspaces must be submitted before the windows which they host. ([See documentation here](https://github.com/ocornut/imgui/blob/cb8ead1f7198924f97e52973d115e1d4eaeda2f3/imgui.h#L801). Since you're using the demo's dockspace, this means you need to call `ImGui::ShowDemoWindow()` before any calls to `ImGui::Begin`.)

--------

For example, given the following:

```cpp
ImGui::Begin("Window A");
ImGui::End();

ImGui::DockSpaceOverViewport();

ImGui::Begin("Window B");
ImGui::End();
```

`Window B` will be able to dock into the dockspace, but `Window A` will not.
