### ISSUE TITLE
Image is replaced by Font Image

### ISSUE THREAD

**Issue by FurrySoM** [ocornut/imgui#5531]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Cmake
Operating System: Ubuntu 20.04

**My Issue/Question:**

My Image is replaced by Font Image,The image data seems to be read properly from the filesystem, since the box size is the correct one.I do that like Image Display Sample.

**Screenshots/Video**

![Screenshot from 2022-08-01 17-15-37](https://user-images.githubusercontent.com/64591615/182115824-6113dd19-c99d-43e7-af9a-31bbe17bdcff.png)

**Standalone, minimal, complete and verifiable example:
```
bool LoadTextureFromFile(const char* filename, GLuint* out_texture, int* out_width, int* out_height);

int my_image_width = 0;
int my_image_height = 0;
GLuint my_image_texture = 0;
bool ret = LoadTextureFromFile("./assets/logo.jpg", &my_image_texture, &my_image_width, &my_image_height);
IM_ASSERT(ret);
```

```
 if(ImGui::Begin("Demo window",p_open,window_flags))
        {
            ImGui::Image((void*)(intptr_t)my_image_texture, ImVec2(my_image_width, my_image_height));
            ImGui::SliderFloat("Alpha", &alpha, 0.0f, 1.0f);
            ImGui::SliderInt("PointSize", &pointSize, 1, 10);
            // if(ImGui::Button("RGB")){
            //     IsRGB = true;
            //     IsIntensity = false;
            // }
            // if(ImGui::Button("Intensity")){
            //     IsRGB = false;
            //     IsIntensity = true;
            // }
            ImGui::RadioButton("RGB", &a, 0);
            ImGui::SameLine();
            ImGui::RadioButton("Intensity", &a, 1);
            ImGui::Text("pointer = %p", &my_image_texture);
            ImGui::Text("size = %d x %d", my_image_width, my_image_height);
            // ImGui::Image((void*)(intptr_t)my_image_texture, ImVec2(my_image_width, my_image_height));

            ImGui::End();
        }
```

```
bool LoadTextureFromFile(const char* filename, GLuint* out_texture, int* out_width, int* out_height)
{
    // Load from file
    int image_width = 0;
    int image_height = 0;
    unsigned char* image_data = stbi_load(filename, &image_width, &image_height, NULL, 4);
    if (image_data == NULL)
        return false;

    // Create a OpenGL texture identifier
    GLuint image_texture;
    glGenTextures(1, &image_texture);
    glBindTexture(GL_TEXTURE_2D, image_texture);
    printf("pointer = %p", &image_texture);


    // Setup filtering parameters for display
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE); // This is required on WebGL for non power-of-two textures
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE); // Same

    // Upload pixels into texture
    #if defined(GL_UNPACK_ROW_ALIGNMENT) && !defined(__EMSCRIPTEN__)
        glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
    #endif
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data);
    stbi_image_free(image_data);

    *out_texture = image_texture;
    printf("pointer = %p", image_texture);
   
    *out_width = image_width;
    *out_height = image_height;

    return true;
}
```

**Comment by PathogenDavid** [comment]
Your code works fine for me and I see nothing obviously wrong with it:

![Screenshot of Dear ImGui example application with a photo of a black lab German shepherd mix puppy with huge ears (she looks very happy.)](https://user-images.githubusercontent.com/278957/182201329-2d26f48b-ba53-40e3-9a96-1df443f512c7.png)

You're going to have to do some more debugging on your end. Make sure that the GL calls in `LoadTextureFromFile` are actually succeeding.

**Comment by ocornut** [comment]
You might have an issue with another OpenGL state interfering, its not possible to cater for every case but either way it is not a dear imgui issue. 

You may use Metrics>DrawList to browse the draw call and verify that the texture id is different for your image and not the same. Then maybe use glError() and RenderDoc to pinpoint your issue.

Where you find it, it’d be nice to post about it here to augment the collective knowledge base.

**Comment by ocornut** [comment]
Note that “ ImGui::Text("pointer = %p", &my_image_texture);” or equivalent printf() given that “my_image_texture” is a little pointless and may not be the value you’d want to care about (it’ll be the address of your local variable). Instead use Text(“%d”, my_image_texture) to see the ID generated by OpenGL.

**Comment by FurrySoM** [comment]
Well Issues fix now

Thank for Reply and I'm so sorry to waste your time.

Author write docs particular here : [https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples](url)

### **this problem cause by my careless and I make an  apology here**

My Problem solve Step Below:

Debug by Imgui Metrics/Debugger

```
static bool show_app_metrics = false;
ImGui::ShowMetricsWindow(&show_app_metrics);
```

check texture pointer address at Metrics → drawList, check that the texture id is different for your image and not the same

check img TextureId
```
*out_texture = image_texture;
printf("pointerValue = %d\n", image_texture);
printf("pointer = %p\n",&image_texture);
printf("out_pointerValue = %d\n", out_texture);
printf("out_pointer = %p\n",&out_texture);
*out_width = image_width;
*out_height = image_height;
```

cout:
```
pointerValue = 21959
pointer = 0x7ffda9bdabac
out_pointerValue = -1447187464
out_pointer = 0x7ffda9bdab90
```

```
ImGui::Text("pointer = %p", &my_image_texture);
ImGui::Text("pointervalue = %d", my_image_texture);
```
seem TextureID is same as image

![Screenshot from 2022-08-02 10-04-45](https://user-images.githubusercontent.com/64591615/182292117-22d44dba-7e9f-492c-82ba-bf90391f9f29.png)

```
ImGui::Image((void*)(intptr_t)my_image_texture, ImVec2(my_image_width, my_image_height));
std::cout << glGetError() << std::endl; 
```

glGetError() return 0 at first, but return 1282 after two time.

same code in example_glfw_opengl3. work nicely

![Screenshot from 2022-08-02 11-00-59](https://user-images.githubusercontent.com/64591615/182292397-96e12f1f-3aeb-4336-a3b8-a2a8d69c7060.png)

```
ImGui::Image((void*)(intptr_t)my_image_texture, ImVec2(my_image_width, my_image_height));
std::cout << glGetError() << std::endl; 
```
glGetError() return 0

What wrong?

After long time consideration.I find who I am . I'm idiot!

I put the LoadTexture code before initializing OpenGL loader

I put the code after this at first

```
glfwInit();
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
glfwWindowHint(GLFW_RESIZABLE, GL_FALSE);

int my_image_width = 0;
int my_image_height = 0;
GLuint my_image_texture = 0;
bool ret = LoadTextureFromFile("./assets/logo.jpg", &my_image_texture, &my_image_width, &my_image_height);
IM_ASSERT(ret);
```
well then I found there are other method I put in initialize behind

```
glfwMakeContextCurrent(window);
glfwSetFramebufferSizeCallback(window, framebuffer_size_callback);
glfwSetCursorPosCallback(window, mouse_callback);
glfwSetScrollCallback(window, scroll_callback);
```
well now image work perfectly , I'm so sorry and thank for reply.

**Comment by PathogenDavid** [comment]
> I put the LoadTexture code before initializing OpenGL loader

That'd definitely do it 😅

No worries at all, glad to hear you got it working!

> ```cpp
? ImGui::Image((void*)(intptr_t)my_image_texture, ImVec2(my_image_width, my_image_height));
> std::cout << glGetError() << std::endl; 
> ```

FYI, `ImGui::Image` doesn't directly issue any OpenGL commands, so `glGetError` doesn't make a ton of sense here. You'd want to check it after the GL commands in `LoadTextureFromFile` to make sure loading the texture was working.

**Comment by FurrySoM** [comment]
> FYI, ImGui::Image doesn't directly issue any OpenGL commands, so glGetError doesn't make a ton of sense here. You'd want to check it after the GL commands in LoadTextureFromFile to make sure loading the texture was working.

OK, I'll take note of this next time.Thank again and have a nice day

**Comment by ocornut** [comment]
Thanks for posting details of your bug tracking!
