### ISSUE TITLE
Cannot create multiple buttons with same texture?

### ISSUE THREAD

**Issue by Krish2882005** [ocornut/imgui#5533]
Hello

I am creating a texture which loads an icon like so

`SDL_Texture* Texture = Load("SomePath.png");`

I then create two buttons with the same texture 

`ImGui::ImageButton(Texture, SomeSize);`

`ImGui::ImageButton(Texture, SomeSize);`

When doing this, only the first button works... Isn't the SDL_Texture pointer the id for the image button?

**Comment by Krish2882005** [comment]
We can use PushID to give ID to the button

**Comment by ocornut** [comment]
It is an API oversight see #4471 #1390,
I am reopening this because I would like to rework/promote a new API with an explicit identifier (there is a `ImageButtonEx()` in imgui_internal.h already)

**Comment by ocornut** [comment]
I have pushed a refactor in 4a2ae06ca4996ca478b3e5e2f8f08e3b90ed2fe4

**Changed signature of ImageButton() function: (#5533, #4471, #2464, #1390)**

- Added `const char* str_id` parameter + removed `int frame_padding = -1` parameter.
- Old signature: `bool ImageButton(ImTextureID tex_id, ImVec2 size, ImVec2 uv0 = ImVec2(0,0), ImVec2 uv1 = ImVec2(1,1), int frame_padding = -1, ImVec4 bg_col = ImVec4(0,0,0,0), ImVec4 tint_col = ImVec4(1,1,1,1));`
   - used the ImTextureID value to create an ID. This was inconsistent with other functions, led to ID conflicts, and caused problems with engines using transient ImTextureID values.
   - had a FramePadding override which was inconsistent with other functions and made the already-long signature even longer.
- New signature: `bool ImageButton(const char* str_id, ImTextureID tex_id, ImVec2 size, ImVec2 uv0 = ImVec2(0,0), ImVec2 uv1 = ImVec2(1,1), ImVec4 bg_col = ImVec4(0,0,0,0), ImVec4 tint_col = ImVec4(1,1,1,1));`
   - requires an explicit identifier. You may still use e.g. PushID() calls and then pass an empty identifier.
   - always uses style.FramePadding for padding, to be consistent with other buttons. You may use PushStyleVar() to alter this.
- As always we are keeping a redirection function available (will obsolete later).

**Comment by luis605** [comment]
What is the new usage of ImageButton? imgui_demo doesn't seem to be update.

What is str_id and what do I need to pass as that argument? For what I understand, ImageButtons with the same texture would have had the same id and they wouldn't be selected correctly, am I right? And I believe that I can pass an empty string if the texture is only used once or if I manually push an ID, correct?
