### ISSUE TITLE
Color Picker not selecting the color.

### ISSUE THREAD

**Issue by TooFast4ya** [ocornut/imgui#5536]
I'm not sure if I'm suppose to Push something after or..
But every time I chose a color in the color picker it seems to return to original value.

Here's a video: [https://streamable.com/dh4r18](url)

`ImGui::ColorEdit3("Text Color", (float*)&style.Colors[ImGuiCol_Text]);`

**Comment by rokups** [comment]
You most likely are reinitializing color value somewhere.
