### ISSUE TITLE
Hiding the main menu bar

### ISSUE THREAD

**Issue by inolen** [ocornut/imgui#554]
I'd like to be able to somehow disable the main menu bar, so that a.) it doesn't render and b.) calls to `ImGui::BeginMainMenuBar` return false.

I tried collapsing the main menu bar before anything that appended to it did so:
```
if (ImGui::BeginMainMenuBar()) {
    ImGui::SetWindowCollapsed(!enable_main_menu_);
    ImGui::EndMainMenuBar();
}
```

This makes `ImGui::BeginMainMenuBar` return false, however the background for the main menu bar is still rendered. Is this state that I should just track myself (checking an additional bool before each call to BeginMainMenuBar),or is there some paradigm that already exists that I should be following?

**Comment by Cthutu** [comment]
Don't call BeginMainMenuBar?

**Comment by ocornut** [comment]
Not calling the function is indeed the way to go!

**Comment by Cthutu** [comment]
I see that a lot of people using your library are missing that fundamental
idea.  I think we need that documentation sooner rather than later :)
