### ISSUE TITLE
animated "bouncing/dancing" buttons

### ISSUE THREAD

**Issue by timprepscius** [ocornut/imgui#5542]
Hey there,

I need to make one of my buttons "dance" when an arbitrary event happens-
and of course I don't want that "dance" to affect the layout of other items in the window.

I found:
https://github.com/ocornut/imgui/issues/1167
"Very simple animated image button"

They basically:
1. make a bounding box
2. do ButtonBehavior
3. add an image to the draw list based on the hover state, etc.

I think I can adapt to it by:
Making a bounding box for the original image (like they do)

and instead of AddImage depending on the image state, I would
AddImageQuad, where the coordinates of the quad, "dance" over time.

--

Is this the best way?  Or is there a better way?

Thanks,

-tim

**Comment by ocornut** [comment]
Whatever works for you..

**Comment by timprepscius** [comment]
Thanks a lot, very helpful.
