### ISSUE TITLE
Window resizing  depending of what content a tab has.

### ISSUE THREAD

**Issue by aurhack** [ocornut/imgui#5549]
i don't remember what version i had :/

**Back-end/Renderer/Compiler/OS**
Windows 10 Home

**My Issue/Question:**

I want to make every tab resizable, i mean, like if i go to tab 1, it resizes to what content it contains, but i have tried with so many flags, pushstyles, etc i don't know what i'm doing bad

**Screenshots/Video**
other tab that has the same default size
![Captura de pantalla (63)](https://user-images.githubusercontent.com/72323046/183254538-9e1314c7-70d9-4607-bb51-d98c8a79a9d1.png)

Other tab that has the same default size
![Captura de pantalla (64)](https://user-images.githubusercontent.com/72323046/183254543-58198e7a-b2ad-4504-b344-34a67df908ad.png)

The thing here is that i want to fit  it depending on what content a tab has. Is this supported?

**Comment by ocornut** [comment]
Sorry but #1586
PS: There are no Tabs in your screenshots.
