### ISSUE TITLE
Implement backend for SFML

### ISSUE THREAD

**Issue by sam20908** [ocornut/imgui#5550]
**My Issue/Question:**

Hello! I have been using Dear ImGui for my projects, and it's amazing! I've used it with SFML, through this backend https://github.com/eliasdaler/imgui-sfml. However, the maintainer of that backend isn't really working on it anymore (see https://github.com/eliasdaler/imgui-sfml/issues/185 for his message), and it might cause problems due to the project falling behind new Dear ImGui versions. I've also noticed there's already a backend for SDL, so why not do the same for SFML? Thank you!

**Comment by gamecoder-nz** [comment]
I'm in the same situation.  I am planning on creating one.

**Comment by ocornut** [comment]
If Elias doesn't want to maintain this they should find a maintainer and hand things over to them.

Personally I don't think we `imgui/` should carry nor maintain too many backends. They have a tendency to be vampirizing too much attention away from main imgui dear features (It's already a mistake IHMO that we have an Allegro backend).
I think it's simply saner that imgui-sfml finds a new focused/competent maintainer. Elias kindly asked for help, if you want to see things moving you can consider helping them (takes focus and dedication to do things right, hasty PR are not helpful to maintainers).
