### ISSUE TITLE
Why IsWindowFocused() hasn't flag like ImGuiFocusedFlags_NoModalPopupHierarchy?

### ISSUE THREAD

**Issue by DimaKoltun** [ocornut/imgui#5555]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp _(or specify if using a custom engine/back-end)_
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: Windows

**My Issue/Question:**

I want to process shortcuts only if window or it's childs(including popups, but not modal)  have focus, but i can't do that, because ImGuiFocusedFlags doesn't have flag like ImGuiFocusedFlags_NoModalPopupHierarchy, why not add it?

**Comment by ocornut** [comment]
Hello,

Can you clarify which type of input you are checking and where?
Reason is I am surprised you want to include popups in your check.
I'm currently working on input routing stuff, and it seems like a UI oddity to me you would want parent of a popup to trigger shortcuts while a popup is open.

**Comment by DimaKoltun** [comment]
Yeah, we thought about ux/ui of this solution and decided that we shouldn't check shortcuts if any popup is opened. closed.
