### ISSUE TITLE
Can I clear just a specific CircleFilled from the window?

### ISSUE THREAD

**Issue by HackingSgravato** [ocornut/imgui#5556]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: VisualStudio 2022
Operating System: Windows 11 Version 21H2 (build SO 22000.795)

**My Issue/Question:**

I made this custom animated button that when you click on it then appears a animated dot.
What I want is to remove the dot from the window when the animation is completed, so when the variable "t" is equals to 1.0f.
I was working on this "issue" for hours.

Thanks a lot, I appreciate a lot your work. PS: "I'm Italian"

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/94282136/183468640-a0cf29c1-c950-419b-bf1c-f6c2bb37c289.png)

```
bool Button(const char* str_id, bool* v, const char* fmt, ...)
	{
		ImVec2 p = ImGui::GetCursorScreenPos();
		ImDrawList* draw_list = ImGui::GetWindowDrawList();
		ImGuiContext& g = *GImGui;

		ImVec2 p2 = p;

		va_list args;
		va_start(args, fmt);
		ImGui::TextV(fmt, args);
		va_end(args);

		const char* text, * text_end;
		ImFormatStringToTempBufferV(&text, &text_end, fmt, args);
		auto text_size = ImGui::CalcTextSize(text, text_end);

		ImGui::SetCursorPosX(p2.x);
		ImGui::SetCursorPosY(p2.y);

		ImGui::InvisibleButton(str_id, text_size);

		if (ImGui::IsItemClicked())
			*v = !*v;

		float t = *v ? 1.0f : 0.0f;

		float t_anim = 0.000f;
		float ANIM_SPEED = 0.500f;

		if (g.LastActiveId == g.CurrentWindow->GetID(str_id))// && g.LastActiveIdTimer < ANIM_SPEED)
		{
			float t_anim = ImSaturate(g.LastActiveIdTimer / ANIM_SPEED);
			t = *v ? (t_anim) : (1.0f - t_anim);
		}
		
		draw_list->AddCircleFilled(ImVec2((text_size.x + p.x) / 2 + 4, p.y + ImGui::GetFontSize() + 6), 2.000f, ImColor(1.000f, 1.000f, 1.000f, t), 100);

		if (t == 1.0f)
		{

		}

		return *v ? true : false;
	}
```

**Comment by ocornut** [comment]
Sorry this sound like a general programming question, please ask elsewhere. Thank you.
