### ISSUE TITLE
Synced tables across windows?

### ISSUE THREAD

**Issue by WeirdRubberDuck** [ocornut/imgui#5557]
I have a use case where I want two tables in different windows to mimic each other's settings,  with column order etc.. However, the synced table instance using the same ID only works if the tables are in the same window

Is there any way to sync the table settings between two tables in different windows? Appreciate any help!

**Comment by ocornut** [comment]
You may try to call internal’s PushOverrideID() with a same version in both windows before submitting the table. However I am not entirely sure it’ll work and will be void of problem (if eg the windows don’t have same width). Let us know.

**Comment by WeirdRubberDuck** [comment]
Update: It seems to work for column selection and reordering, but not for triggering the sorting of data (see video below). 

Still, I can work with that. Thanks for the input!

https://user-images.githubusercontent.com/8808894/183616975-49c84ca9-a8c2-4995-8424-6337511093c8.mov

**Comment by ocornut** [comment]
> Update: It seems to work for column selection and reordering, but not for triggering the sorting of data (see video below). This makes sense though, since the sortspecs implementation uses the "current table", which is set from the current window

It appears to work. 
What's probably throwing you off and is a little unspecced is that the expected user logic is:

```
if (ImGuiTableSortSpecs* sorts_specs = ImGui::TableGetSortSpecs())
    if (sorts_specs->SpecsDirty)
    {
        // Perform sorting
        sorts_specs->SpecsDirty = false;
    }
```
Since you have two data sets you'd need to keep track of the fact the sort specs were dirty to sort all your data sets.

**Comment by ocornut** [comment]
Closing as seemingly OK.
In our test suite `table_multi_instances` demonstrate it.
