### ISSUE TITLE
Colouring individual table header columns

### ISSUE THREAD

**Issue by MynachMelyn** [ocornut/imgui#5558]
**Version/Branch of Dear ImGui:**

Version: 1.75
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: _Unsure; we seem to have all of them in our codebase's IMGUI library (sorry)_
Operating System: Windows 10

**My Issue/Question:**

According to [this issue](https://github.com/ocornut/imgui/issues/3422), one can't simply use _PushStyleColor()_ on a table column header, as the header row is submitted by _TableHeadersRow()_, and you must instead push the colour before calling that instead. 
That works for entire rows, but I'm trying to colour the text in individual column titles - is there a way to do this?

A workaround I imagine might work would be to set up the table header without colour, and then perhaps go into the header cells and change their content to coloured text, but I'm not sure if that's even possible im IMGUI due to way commands are used to draw elements. Alternatively, I could essentially copy the contents of _TableHeadersRow()_ and put in the push/pop colour commands around where the text is actually drawn into the cell, but that's both very convoluted and would likely be invalidated by any updates to IMGUI that change the _TableHeadersRow()_ code. 

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Doesn't apply colour because it's not actually the command where the table header is drawn
ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(255,255,0,255));
ImGui::TableSetupColumn("Column Title", eTableColumnFlags_None);
ImGui::PopStyleColor();
ImGui::TableHeadersRow();

// Applies colour to the entire header row
ImGui::TableSetupColumn("Column Title", eTableColumnFlags_None);
ImGui::PushStyleColor(ImGuiCol_Text, IM_COL32(255,255,0,255));
ImGui::TableHeadersRow();
ImGui::PopStyleColor();
```

**Comment by ocornut** [comment]
TableHeadersRow() in principle is intended to be only only public facing calls. In practice there are two internal things it uses (the function is decently commented), which we will strive to simplify. But the simple loop calling TableHeader() on each column will give you 90% of its behavior.

**Comment by MynachMelyn** [comment]
Wonderful, thank you! btw IMGUI is an absolute joy to work with <3
