### ISSUE TITLE
Text Width calculated as 1 character too long

### ISSUE THREAD

**Issue by SimDietrich** [ocornut/imgui#556]
If I do
<code>
**TextUnformatted("A"); SameLine(); TextUnformatted("B");**
</code>
I get 
<code>
'A B ';
</code>
to fix it in my case,
imgui.cpp : 1543 becomes : 
<code>
        const ImVec2 text_size = CalcTextSize(text_begin, text_end - 1, false, wrap_width);
</code>

**Comment by ocornut** [comment]
Are you sure it isn't the ItemSpacing added by a default call to SameLine() ?
You can call SameLine(0, 0) to remove extra spacing.

**Comment by SimDietrich** [comment]
You are right! Thanks a bunch!
