### ISSUE TITLE
Not optimal memory type binding with vertex and index buffer on Vulkan backend.

### ISSUE THREAD

**Issue by ShenCiao** [ocornut/imgui#5561]
----
```
Dear ImGui 1.88 (18800)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1932
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_vulkan
```
CPU: AMD 4800H
GPU: RTX 3060

**My Issue/Question:**
In the official Vulkan implementation, I found that vertex and index buffer's memory is created with memory type `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT`. On my laptop, it get created with CPU side memory and GPU need to fetch the data every frame when drawing.

The image blow shows a GPU tracing when drawing 500k vertices and 700k indices inner ImGui. The PCIe throughputs (blue one) are pretty high during a drawing. It goes around 6.5GB/s.
![Screenshot 2022-08-10 085539](https://user-images.githubusercontent.com/24319509/183788111-ae72c2e5-6a46-4fbb-975e-b9bc33520eef.jpg)

It's ok on my own laptop. As you can see from the image it's a CPU-limit case. But I'm not sure if it's desired to fetch CPU memory in each frame. Does CmdLists operate in a "lazy mode"? "Lazy mode" means it only update the vertex buffer data needs to be updated. If so, it loses the performance benefits since the memory type.

You can search for the function `ImGui_ImplVulkan_MemoryType` in `imgui_impl_vulkan.cpp` and watch for all buffer memory created with it. I notice that the font image memory is created with `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT` and updated with a staging buffer, which is optimal for performance.

**Comment by ocornut** [comment]
Drawlists are recreated every frame from scratch, there’s no concept of lazy recreation.

This specific screen you showed of ImPlot is known to be abnormally heavy (I think they have a shader version of it).

**Comment by ShenCiao** [comment]
Thanks! It's really helpful. 

By the way I'm working on an interesting research project, which will offer versatile line and polygon rendering solution on GPU. Maybe it would be useful for developing UI framework in the future.

It's not mature enough to be showed off but I won't be harmful to be pasted here?
![six](https://user-images.githubusercontent.com/24319509/183880439-073a5528-e43c-4182-b6d2-cbaabfdc734b.gif)
https://github.com/ShenCiao/Ciallo

**Comment by ocornut** [comment]
Drawlists are recreated every frame from scratch.
This specific screen you showed of ImPlot is known to be abnormally heavy (I think they have a shader version of it).
