### ISSUE TITLE
Does imgui still supports windows 7?

### ISSUE THREAD

**Issue by NRicode** [ocornut/imgui#5562]
Is the latest version of imgui supports windows 7? I downloaded the latest binary from http://www.dearimgui.org/binaries/ and tried to run it on windows 7 (64 bit), it doesn't work and it shows this error 
![image](https://user-images.githubusercontent.com/106366188/183902551-fa43fe0a-355f-4931-a5d6-fd6d94a10cb4.png)
It is a win32 directx9 sample. 

I've also tried older version from 2017 and it also didnt work

**Comment by ocornut** [comment]
It could be missing DLLs. Dear ImGui per se is OS agnostic, working on Windows 7 would be a matter of compiler settings generally.

**Comment by NRicode** [comment]
> It could be missing DLLs. Dear ImGui per se is OS agnostic, working on Windows 7 would be a matter of compiler settings generally.

wouldn't missing .dll will show you an error like "The program can't start because x.dll is missing" or something like it? I've included the missing dll when I first installed and it still shows this error, or can missing windows dll also cause these kind of error? This seem like a crash

**Comment by NRicode** [comment]
I've figured it out, I was testing the sample on windows 7 in a virtual machine, turns out the virtual machine uses a windows standard vga graphics adapter (very old stuff) and I don't know what went wrong but it just won't work. I think It is a good idea to add the following lines on the examples so that imgui application can still run without hardware acceleration (for weak computers). This only seem to work on dx10 and above, I'm not sure how to do it in dx9.

```cpp
HRESULT res = D3D10CreateDeviceAndSwapChain(NULL, D3D10_DRIVER_TYPE_HARDWARE, NULL, createDeviceFlags, D3D10_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice);
    if (res = DXGI_ERROR_UNSUPPORTED) {
       
        //use software rendering if hardware is not available (because driver too old / doesn't exist), not sure how it works with dx9
        res = D3D10CreateDeviceAndSwapChain(NULL, D3D10_DRIVER_TYPE_WARP, NULL, createDeviceFlags, D3D10_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice);
        if (res != S_OK) {

            //something else
            return false;

        }
    
    }
```

**Comment by ocornut** [comment]
> I think It is a good idea to add the following lines on the examples so that imgui application can still run without hardware acceleration (for weak computers). 

I think it is best we keep that barrier on in the default examples. 
If anything we don't want to attract more casual users of legacy or lower specs setup, this would basically be calling for more problems. People who intently want their 3D app to support software can figure this out.

For DX10
```cpp
    HRESULT res = D3D10CreateDeviceAndSwapChain(NULL, D3D10_DRIVER_TYPE_HARDWARE, NULL, createDeviceFlags, D3D10_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice);
    if (res == DXGI_ERROR_UNSUPPORTED) // Try high-performance WARP software driver if hardware is not available.
        res = D3D10CreateDeviceAndSwapChain(NULL, D3D10_DRIVER_TYPE_WARP, NULL, createDeviceFlags, D3D10_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice);
    if (res != S_OK)
        return false;
```
For DX11
```cpp
    D3D_FEATURE_LEVEL featureLevel;
    const D3D_FEATURE_LEVEL featureLevelArray[2] = { D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_0, };
    if (D3D11CreateDeviceAndSwapChain(NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, createDeviceFlags, featureLevelArray, 2, D3D11_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice, &featureLevel, &g_pd3dDeviceContext) != S_OK)
    HRESULT res = D3D11CreateDeviceAndSwapChain(NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, createDeviceFlags, featureLevelArray, 2, D3D11_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice, &featureLevel, &g_pd3dDeviceContext);
    if (res == DXGI_ERROR_UNSUPPORTED) // Try high-performance WARP software driver if hardware is not available.
        res = D3D11CreateDeviceAndSwapChain(NULL, D3D_DRIVER_TYPE_WARP, NULL, createDeviceFlags, featureLevelArray, 2, D3D11_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice, &featureLevel, &g_pd3dDeviceContext);
    if (res != S_OK)
        return false;
```
DX9 can use `D3DDEVTYPE_SW` + `D3DCREATE_SOFTWARE_VERTEXPROCESSING` but the later became even more discouraged by Win10 recently.

I'll close this as solved.

**Comment by ocornut** [comment]
Applied the WARP support change with 9c1dac3
