### ISSUE TITLE
The lua c++ bindings is inactive (patrickriordan's imgui_lua_bindings)

### ISSUE THREAD

**Issue by megumumpkin** [ocornut/imgui#5565]
So I've been looking at the library mentioned in here for c++ lua bindings (patrickriordan's imgui_lua_bindings - link: [here](https://github.com/patrickriordan/imgui_lua_bindings)), but the code is for older dear imgui version and seems to be inactive for two years (there are 1 pull request waiting to be merged from March 2022).

Not only that, not all functions are exposed, and this also affects the core functions (like can't use TextLabel for instance).
I have a new one here which has the more latest version of dear imgui and has covered all core functions (I believe) in here: [link to my fork](https://github.com/megumumpkin/imgui_lua_bindings) which also merges changes from one pending PR from the original repo.

And I plan to make a guide on how to keep updating the code to latest Imgui versions.
[Here's the mentioned link page for the recommendation.](https://github.com/ocornut/imgui/wiki/Bindings) (seek to Lua segment)

**Comment by rokups** [comment]
I added URL of your fork to the wiki. Thanks! 🙏

**Comment by ocornut** [comment]
Thank you @megumumpkin ! Closing this as resolved.
