### ISSUE TITLE
Calling SliderAngle to work with object's member in object's method

### ISSUE THREAD

**Issue by Artalus** [ocornut/imgui#557]
In my program I have a following call order:
1. init program (create two objects `Link link1, link2`, init ImGui and call `ImGui_ImplSdl_NewFrame()`)
2. step logic (call `link1.Update(); link2.Update();`)
3. step render (call `ImGui::Render(); ImGui_ImplSdl_NewFrame()`)
4. loop to 2.
During `Link::Update()` I call `ImGui::SliderAngle("Link pitch (update)", &(this->pitch))` to change rotation of the object. However, for some reason when I work with one slider, all changes are instantly applied to the second one - in fact, the highlighting looks like I'm changing both sliders simultaneously:
![1](https://cloud.githubusercontent.com/assets/10381253/13899217/9c949aba-edf9-11e5-94cb-1c051f452c1d.png)

However, if instead of calling `.Update()` I'd directly access pitch value via `ImGui::SliderAngle("Link pitch (update)", &(link1.pitch)); ImGui::SliderAngle("Link pitch (update)", &(link2.pitch));`, everything works fine:
![2](https://cloud.githubusercontent.com/assets/10381253/13899224/b8de752e-edf9-11e5-88cf-3fdc03efd795.png)

At first I thought that there are some problems with getting address of object's member in its method, but everything is OK - `this` value differs in each `.Update()`, as well as `&(this->pitch)` value.
I can keep to the direct access to pitch instead of accessing it from the `.Update()`, but it still puzzles me. Am I doing something wrong, or is there some bug in the library?

**Comment by ocornut** [comment]
It looks like an id collision problem.
Read the FAQ about id. If your widgets have the same name in the same scope, you likely want to enclose them within a PushId() / PopId() block.
