### ISSUE TITLE
convert dxt5 to R8G8B8A8

### ISSUE THREAD

**Issue by Sperma4ez** [ocornut/imgui#5571]
is it possible? i need to draw dxt5 image on dx11 with imgui, but something's wrong: the picture is very bad
https://i.imgur.com/Rj885sJ.png instead https://i.imgur.com/aEvwCmx.png

**Comment by rokups** [comment]
This question is unrelated to Dear ImGui. You should inquire on discussion platforms related to graphics rendering, like stackoverflow for example.

You also may salvage some code from other game engines: https://github.com/urho3d/Urho3D/blob/347eecd9eadb85a1f13cd03ce2b46059e51d270a/Source/Urho3D/Resource/Decompress.cpp#L215-L263

**Comment by ocornut** [comment]
As I understand since imgui_impl_dx11 takes “ ID3D11ShaderResourceView*” as ImTextureId user can setup the SRV for whichever format is supported by DX11. Unsure of details for dxt5 but as pointed out this is not a Dear ImGui question, and lack of details/templates doesn’t help.

**Comment by Sperma4ez** [comment]
ty very much♥ this will be help me

> This question is unrelated to Dear ImGui. You should inquire on discussion platforms related to graphics rendering, like stackoverflow for example.
> 
> You also may salvage some code from other game engines: https://github.com/urho3d/Urho3D/blob/347eecd9eadb85a1f13cd03ce2b46059e51d270a/Source/Urho3D/Resource/Decompress.cpp#L215-L263
