### ISSUE TITLE
Some scrollwheels can cause ImGui to lag. 

### ISSUE THREAD

**Issue by tmsrise** [ocornut/imgui#5573]
```
Dear ImGui 1.88 (18800)
--------------------------------

sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1931
define: _MSVC_LANG=202002
--------------------------------

io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000022
 NavEnableGamepad
 NoMouseCursorChange
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------

io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 4096,8192
io.DisplaySize: 1920.00,1080.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------

style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 5.00,2.00
style.FrameRounding: 3.00
style.FrameBorderSize: 1.00
style.ItemSpacing: 6.00,6.00
style.ItemInnerSpacing: 6.00,6.00
```

**My Issue/Question:**

Some Logitech mice (and probably many others) have a button to unlock the scrollwheel to freescroll. These mice usually have near frictionless scrolling (can spin fast and for long periods of time). Simply moderately flicking these types of scrollwheels lags imgui even if there is nothing to scroll.

**Screenshots/Video**

https://streamable.com/0vb4l4
The video initially shows that scrolling normally is fine, but flicking the wheel has imgui devolving into attempting to "catch up" to my mouse.

**Comment by PathogenDavid** [comment]
Thanks for filling out the issue template and providing the video! This is the same as https://github.com/ocornut/imgui/issues/5545

As a workaround you can disable `ImGuiIO::ConfigInputTrickleEventQueue`.

**Comment by ocornut** [comment]
Closing as duplicate.
