### ISSUE TITLE
would be good if imgui was more OO

### ISSUE THREAD

**Issue by Joilnen** [ocornut/imgui#558]
I mean, if I want a InputText with a Checkbox 
ImGui::Checkbox(ImGui::InputText...

**Comment by Roflraging** [comment]
I'm not sure what you're actually trying to achieve and how this is related
to OO (object oriented)?

**Comment by ocornut** [comment]
Your pseudo code doesn't make much sense and that isn't OO.

You can call Checkbox, SameLine, InputText in sequence if you want 2 widgets next to each others.

**Comment by aaronhyperum** [comment]
I don't really care for this, but I'm pretty sure Joilnen is commenting on the use of push(), pop(), sameLine(), and functions of that sort.

**Comment by Joilnen** [comment]
I don't mean a widget next other but create one of other two mixed, in this case checkbox getting a text and we have a checkbox were label is a edit.

**Comment by aaronhyperum** [comment]
That's probably going to be quite a lot of work on the library. I don't think it's really going to be worth it.
