### ISSUE TITLE
premake in linux bind glfw error

### ISSUE THREAD

**Issue by ploirliu** [ocornut/imgui#5581]
In the branch premake , I try run it on ubuntu 
it shows:

/usr/bin/ld: obj/x86_64/Debug/example_glfw_opengl2/imgui_impl_glfw.o: in function `ImGui_ImplGlfw_GetClipboardText(void*)':

/../../backends/imgui_impl_glfw.cpp:128: undefined reference to `glfwGetClipboardString'
.....

it seem the glfw not successful linked, is there any solution?

**Comment by ocornut** [comment]
If you look at the premake file it looks like it has no directive to link the glfw library for unix systems other than osx. Someone would need to make a PR for it.

**Comment by ocornut** [comment]
Can you verify if adding directives in the premake file fixes it for you on Linux?
```
		filter { "system:linux" }
			links { "glfw3" }
```
Under `project "example_glfw_opengl2"` in your case.

**Comment by ocornut** [comment]
I've amended the file f831000
