### ISSUE TITLE
Keeping an InputText element focused for console-style input after other (transparent) windows are clicked?

### ISSUE THREAD

**Issue by mmp** [ocornut/imgui#5586]
**Version/Branch of Dear ImGui:**

Version: 1.89 WIP
Branch: master @ 268565079c56600c197602683391a1bc8afba014

**Back-end/Renderer/Compiler/OS**

Back-ends: glfw
Operating System: OS X

**My Issue/Question:**

(First, many many thanks for imgui. It's a delight!)

I have an app where I am trying to keep an InputText element more or less always focused (unless the user goes to the menu bar or opens up a window for configuration.) Otherwise, I have the main window partitioned into a region where I draw things (sometimes with OpenGL and sometimes with imgui) and a region where there is a console for CLI control of the app. (The console code is heavily inspired by the console example--thanks!) The drawing region has a transparent imgui window painted on top of it (so that I can for example draw text using imgui) and if the user clicks in that region, it consumes the mouse events to update what is drawn.

While I can successfully focus the InputText for the console at application startup, if the user clicks on the transparent window, I lose focus. I haven't been able to found a way to refocus the input text without breaking other UI elements (like, the menu stops responding.)

I'm not sure if my issue is the same one noted in https://github.com/ocornut/imgui/issues/4966#issuecomment-1030132985.
> Investigated this, the problem is that `SetKeyboardFocusHere()` essentially isn't handled by `InputText()` when the input is already active. I believe there are some situation where both behaviors are desirable.

**Screenshots/Video**

Here's a screenshot of my repro app.

<img width="703" alt="image" src="https://user-images.githubusercontent.com/102567/185483105-1177c26d-d682-4ed5-9bb0-42e4bb1e6e45.png">

**Standalone, minimal, complete and verifiable example:** 

Dropping this as a replacement for `ShowDemoWindow()` does the trick. When it starts, you can start typing commands and hitting enter and you'll see the last one entered. But if you then click on the text in the upper part of the window, focus is lost in the InputText. A few things I've tried to bring it back are commented out in the below...

```
void ImGui::ShowDemoWindow(bool* p_open)
{
    using namespace ImGui; // #yolo

    static bool drawConfigWindow;

    if (BeginMainMenuBar()) {
        if (BeginMenu("Menu")) {
            if (MenuItem("Configure...")) {
                drawConfigWindow = true;
            }
            EndMenu();
        }
        EndMainMenuBar();
    }

    if (drawConfigWindow) {
        if (Begin("Configure", &drawConfigWindow)) {
            static char buf[1024];
            InputText("Type something", buf, sizeof(buf));
            if (Button("Close"))
                drawConfigWindow = false;
            End();
        }
    }

     bool reclaimConsoleFocus = false;

    // Top half of the main window: area we click in to do stuff...
    SetNextWindowPos(ImVec2{0, 0}, ImGuiCond_Always);
    int height = 720;  // hardcoded...
    SetNextWindowSize(ImVec2{0, height / 2.f}, ImGuiCond_Always);
    ImGuiWindowFlags transparentFlags = ImGuiWindowFlags_NoBackground;
    transparentFlags |= ImGuiWindowFlags_NoDecoration;
    transparentFlags |= ImGuiWindowFlags_NoSavedSettings;
    transparentFlags |= ImGuiWindowFlags_NoNav;
    transparentFlags |= ImGuiWindowFlags_NoFocusOnAppearing;
    transparentFlags |= ImGuiWindowFlags_NoMouseInputs;

    static ImVec2 textpos{ 100., 100. };
    if (Begin("transparent window", nullptr, transparentFlags)) {
        SetCursorPos(textpos);
        Text("click me!");

        if (!GetIO().WantCaptureMouse && IsMouseClicked(0)) {
            textpos = GetMousePos();
            reclaimConsoleFocus = true;
        }

        End();
    }

    ImGuiWindowFlags consoleFlags = ImGuiWindowFlags_NoBackground;
    consoleFlags |= ImGuiWindowFlags_NoDecoration;
    consoleFlags |= ImGuiWindowFlags_NoSavedSettings;
    consoleFlags |= ImGuiWindowFlags_NoNav;
    SetNextWindowPos(ImVec2{0, height/2.f}, ImGuiCond_Always);
    SetNextWindowSize(ImVec2{0, height/2.f},  ImGuiCond_Always);

    static bool firstDraw = true;
    if (firstDraw || reclaimConsoleFocus) {
        SetNextWindowFocus();
    }
    // https://github.com/ocornut/imgui/issues/455 suggestion; breaks menu bar when used here
    /*
    if ((IsWindowFocused(ImGuiFocusedFlags_RootWindow) ||
         IsWindowFocused(ImGuiFocusedFlags_AnyWindow)) &&
        !IsAnyItemActive() && !IsMouseClicked(0))
        SetNextWindowFocus();
    */

    if (Begin("console", nullptr, consoleFlags)) {
        static char last[1024];
        Text("Last command:");
        SameLine();
        Text(last);

        // https://github.com/ocornut/imgui/issues/455 suggestion; breaks menu bar when used here
        /*
        if ((IsWindowFocused(ImGuiFocusedFlags_RootWindow) ||
             IsWindowFocused(ImGuiFocusedFlags_AnyWindow)) &&
            !IsAnyItemActive() && !IsMouseClicked(0))
            SetKeyboardFocusHere(0);
        */

        static char command[1024];
        ImGuiInputTextFlags textFlags = ImGuiInputTextFlags_EnterReturnsTrue;
        if (InputText("##command", command, 1024, textFlags /* callback */)) {
            strcpy(last, command);
            command[0] = '\0';
            reclaimConsoleFocus = true;
        }

        if (firstDraw || reclaimConsoleFocus) {
            reclaimConsoleFocus = false;
            SetKeyboardFocusHere(-1);
        }

        End();
    }

    firstDraw = false;
}
```

**Comment by rokups** [comment]
```cpp
if ((ImGui::IsWindowFocused() || !ImGui::IsWindowFocused(ImGuiFocusedFlags_AnyWindow)) && !ImGui::IsAnyItemActive())
    SetKeyboardFocusHere(-1);
```
Try this. It will focus console input if no widget is being interacted with and either console window has focus or no window has focus.

**Comment by mmp** [comment]
That does it--thank you!!
