### ISSUE TITLE
How would I add a background image of my application

### ISSUE THREAD

**Issue by SightDev** [ocornut/imgui#5587]
Hello,
    I have looked at some other issues / question and couldn't find any answers 
to my problem I could just be stupid if so I appoligize. How would I add a background as my background
 of my ImGui application?

**Comment by ocornut** [comment]
You might use GetBackgroundDrawLisf()->AddImage(), see FAQ and Wiki about textures. Generally this isn’t really a dear imgui question, but the aforementioned way can be a good solution for you.
