### ISSUE TITLE
Seeking guidance - Menu not dropping down (but title is highlighting)

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#5588]
This isn't a bug in ImGui that I'm aware of but I'm looking for some guidance.

Every now and then after I've done an operation in my software the menu entries will cease to appear but the menu category title does highlight.  All other functions of the software remain operational.

What are some of the thing that can cause/inhibit the ImGui menu to expand down when clicked?

Attached is an image of what it appears like.

The mouse clicks work fine for the content and right-hand-side bar.

![Screenshot at 2022-08-19 13-55-43](https://user-images.githubusercontent.com/5660591/185539712-1a74102f-c2e1-435c-8ee9-7d077794f74a.png)

**Comment by ocornut** [comment]
If you are on a recent version we now have a “Tools>Debug Log” window, you can open it ahead, enable the Popup category and see if it can give you a hint about your problem when it happens.

I suppose first of all you would want to understand if your menus never gets opened, or if it gets opened but immediately closed. Based on that you may setup breakpoints in the code. One trick is to setup conditional breakpoints, eg add “if (io.KeyShift) printf(“”);” in your code and when the bug repro you can add the breakpoint on the print statement, get in the state you want and hold Shift.

**Comment by inflex** [comment]
I'll look at the Tools->Debug Log window, thank you.  
I had tried a few breakpoints with printf()'s and it would appear the 
 ```if (BeginMenu()) { .... }```  isn't succeeding.
 
```
 	if (ImGui::BeginMainMenuBar()) {
		m_menu_height = ImGui::GetWindowHeight();
		
		if (auth.isValid()) {
			fprintf(stderr,"%s:%d: Auth is valid\n", FL);

			if (ImGui::BeginMenu("File")) {
				m_file_menu_was_open = true;
				m_tooltips_enabled = false;

			        fprintf(stderr,"%d:%d: begin file menu\n", FL);
```

**Comment by inflex** [comment]
The ImGui Debug window has helped already - here's what I see change.  Thank you again Ocornut.


![Screenshot at 2022-08-19 20-26-37](https://user-images.githubusercontent.com/5660591/185599559-7c9f0aec-5f25-41f4-9851-49a78585bf6a.png)

**Comment by inflex** [comment]
SOLVED:  The problem was that the "Error Notice" popup had been changed to a slightly different name "Error Notification"; so trying to open it resulted in a error of course.

That's debug log a wonderful resource to have been added Orconut, thank you again.
