### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Slaine066** [ocornut/imgui#5589]
### Discussed in https://github.com/ocornut/imgui/discussions/5585

<div type='discussions-op-text'>

<sup>Originally posted by **Slaine066** August 19, 2022</sup>
Hey!

I tried running the example project (directx 9/win32) and it works fine.
But, when I add the imgui files to my project I get the following errors.

![image](https://user-images.githubusercontent.com/45803419/185468405-4b56b342-0a58-4b55-9c6f-946024869b57.png)

I added the following files to my project:
![image](https://user-images.githubusercontent.com/45803419/185469505-8cd68ce3-c76b-449c-9a8f-b64f6d7a0e37.png)

Do you happen to know why?
Let me know if you need more info! 

(I'm using precompiled header, but I deactivated them on the ImGui *.cpp files so that shouldn't be a problem)</div>

**Comment by ocornut** [comment]
This is not the place, please keep it in the Discussion thread.
