### ISSUE TITLE
How to block IME input

### ISSUE THREAD

**Issue by Victor2kyang** [ocornut/imgui#5590]
Hi，
I want block any IME input，like MS IME or other IME，how can i do it？ T。T

&&

How can I display IME input selection window？like this：
![AD5E8080-3FF7-43a6-932E-EE05A4ABD312](https://user-images.githubusercontent.com/42526605/185556742-a54ef884-4159-4073-a133-166779e25c35.png)

**Comment by ocornut** [comment]
We can’t answers questions like that without more context.

i don’t understand the first question.
Second question: IME suggestion box is already opened when typing in an InputText() field. If you need anything else please explain it and search in the code.

**Comment by Victor2kyang** [comment]
Sorry for the unclear description.
first question:
Is there any other way to make 'ImGui::InputText' only accept characters like 'ImGuiInputTextFlags_CharsHexadecimal'? Because I want him to receive something like '~! @#$%...&*()' and other symbols, but I don't want him to receive utf8 strings from IME. It's like not using an IME.

Second question:
When I use 'ImGui::InputText', the IME suggestion box does open, and when I hit space it does indeed input the string into 'ImGui::InputText', but I can't see the IME suggestion box.



> 如果没有更多的上下文，我们无法回答这样的问题。
> 
> 我不明白第一个问题。 第二个问题：在 InputText() 字段中输入时，IME 建议框已打开。如果您需要其他任何内容，请解释并在代码中搜索。

**Comment by Victor2kyang** [comment]
> We can’t answers questions like that without more context.
> 
> i don’t understand the first question. Second question: IME suggestion box is already opened when typing in an InputText() field. If you need anything else please explain it and search in the code.

Sorry for the unclear description.
first question:
Is there any other way to make 'ImGui::InputText' only accept characters like 'ImGuiInputTextFlags_CharsHexadecimal'? Because I want him to receive something like '~! @#$%...&*()' and other symbols, but I don't want him to receive utf8 strings from IME. It's like not using an IME.

Second question:
When I use 'ImGui::InputText', the IME suggestion box does open, and when I hit space it does indeed input the string into 'ImGui::InputText', but I can't see the IME suggestion box.

**Comment by rokups** [comment]
> Is there any other way to make 'ImGui::InputText' only accept characters like 'ImGuiInputTextFlags_CharsHexadecimal'?

You can use a callback with `ImGuiInputTextFlags_CallbackCharFilter` flag. Demo has an example, ctrl+f for "FilterImGuiLetters".

> Second question:

I dont see a question :eyes: It sounds to me that maybe you want to temporarily disable IME input? If so, you can try unsetting `io.SetPlatformImeDataFn` around widget you do not want IME for.
```cpp
ImGuiIO& io = ImGui::GetIO();
auto ime_fn_bkp = io.SetPlatformImeDataFn;
io.SetPlatformImeDataFn = NULL;
ImGui::InputText(...);
io.SetPlatformImeDataFn = ime_fn_bkp;
```
P.S. Untested.

**Comment by Victor2kyang** [comment]
> > Is there any other way to make 'ImGui::InputText' only accept characters like 'ImGuiInputTextFlags_CharsHexadecimal'?
> 
> You can use a callback with `ImGuiInputTextFlags_CallbackCharFilter` flag. Demo has an example, ctrl+f for "FilterImGuiLetters".
> 
> > Second question:
> 
> I dont see a question 👀 It sounds to me that maybe you want to temporarily disable IME input? If so, you can try unsetting `io.SetPlatformImeDataFn` around widget you do not want IME for.
> 
> ```c++
> ImGuiIO& io = ImGui::GetIO();
> auto ime_fn_bkp = io.SetPlatformImeDataFn;
> io.SetPlatformImeDataFn = NULL;
> ImGui::InputText(...);
> io.SetPlatformImeDataFn = ime_fn_bkp;
> ```
> 
> P.S. Untested.


io.SetPlatformImeDataFn  do not work ,but thanks for the method！：D

**Comment by heroboy** [comment]
Try this `io.SetPlatformImeDataFn` implement:
```c++
static void SetPlatformImeDataFn_DefaultImpl(ImGuiViewport* viewport, ImGuiPlatformImeData* data)
{
    // Notify OS Input Method Editor of text input position
    HWND hwnd = (HWND)viewport->PlatformHandleRaw;
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    if (hwnd == 0)
        hwnd = (HWND)ImGui::GetIO().ImeWindowHandle;
#endif
    if (hwnd == 0)
        return;

    //::ImmAssociateContextEx(hwnd, NULL, data->WantVisible ? IACE_DEFAULT : 0);
    if (HIMC himc = ::ImmGetContext(hwnd))
    {
        if (::ImmGetOpenStatus(himc))
        {
            ::ImmSetOpenStatus(himc, FALSE);
        }
        ::ImmReleaseContext(hwnd, himc);
    }
    ::ImmAssociateContext(hwnd, NULL);
}
```
Reference: https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
