### ISSUE TITLE
Allow configuring `IM_TABSIZE` through `imconfig.h`

### ISSUE THREAD

**Issue by codecat** [ocornut/imgui#5593]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: docking

**My Issue/Question:**

I would like to change `IM_TABSIZE`, but it is only defined in `imgui_internal.h`, so I can't override it in `imconfig.h`.

**Comment by ocornut** [comment]
It only needs an `#ifndef` block and then you can override in imconfig. Added this now.
I'd prefer to make a variable but in term of ImDrawList<>ImGui dependencies and since this is fairly fringe at this point this should work until we add support for proper tabbing.
