### ISSUE TITLE
Hidden Title Bar Button is showing when a window is docked.

### ISSUE THREAD

**Issue by NoahR02** [ocornut/imgui#5597]
**Version/Branch of Dear ImGui:**

Version: v1.88
Branch: docking

```
Dear ImGui 1.88 (18800)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=11
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: GLFW
io.BackendRendererName: OpenGL
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 2 fonts, Flags: 0x00000000, TexSize: 1024,2048
io.DisplaySize: 1600.00,900.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

How do I get rid of the top left blue title bar button? It appears when a window is docked with no title bar. I want a window with no title bar.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/51396418/185823000-53d840f3-3f5e-4ed7-afd3-6305ba4a2d3d.png)
![image](https://user-images.githubusercontent.com/51396418/185823170-11c5b7a4-35e6-4804-a3f9-7dd5116acfcb.png)
![image](https://user-images.githubusercontent.com/51396418/185823049-16b7a103-1c0c-4e59-9af7-2dcb9e2c4056.png)

**Standalone, minimal, complete and verifiable example:**
```
Language: Odin
Operating System: Linux
Backends: 
GLFW
https://github.com/NoahR02/odin-imgui/blob/docking/impl/glfw/glfw.odin
OpenGL
https://github.com/NoahR02/odin-imgui/blob/docking/impl/opengl/opengl.odin
```
```cpp
 imgui.dock_space_over_viewport(imgui.get_main_viewport())

 window_class: imgui.Window_Class
 window_class.dock_node_flags_override_set = .AutoHideTabBar
 imgui.set_next_window_class(&window_class)

  imgui.begin("##", nil, .NoTitleBar)
    imgui.text("Test")
  imgui.end()
```

**Comment by ocornut** [comment]
```
 window_class: imgui.Window_Class
 window_class.dock_node_flags_override_set = .AutoHideTabBar
 imgui.set_next_window_class(&window_class)
```
Since you know how to use this feature (which is deemed experimental as it's unclear what happens when multiple windows are docked together) you can simply use the equivalent `NoTabBar` flag (it is `ImGuiDockNodeFlags_NoTabBar` in imgui_internal.h)

Perhaps your bindings doesn't import the imgui_internal.h flags?

**Comment by NoahR02** [comment]
Thank you, that was it!
```cpp
NoTabBar = 1 << 12 
```

**Comment by ocornut** [comment]
`NoTabBar = 1 << 12 `

Please note that we don't provide ABI backward compatibility, the value of `1 << 12` may change, always use the real value from imgui.h.

I think this should be moved to imgui.h exactly for the use you are providing, though we need to clarify a few things in term of which flags are persistent (in .ini file) and which are inherited/shared. Persistence of docking data with merge/split operations is a tricky beast.

**Comment by NoahR02** [comment]
> `NoTabBar = 1 << 12 `
> 
> Please note that we don't provide ABI backward compatibility, the value of `1 << 12` may change, always use the real value from imgui.h.
> 
> I think this should be moved to imgui.h exactly for the use you are providing, though we need to clarify a few things in term of which flags are persistent (in .ini file) and which are inherited/shared. Persistence of docking data with merge/split operations is a tricky beast.

Got it! I was thinking about putting the imgui_internal functions inside of their own package in Odin. Sometimes you do need to see internal stuff.

Onto the issue at hand, here is the info you requested:

Note: The normal `begin(..., .NoTitleBar)` flag is set on DockNode 0x01.

When Window[#] is Docked and the internal NoTabBar dock node flag is used:
```cpp
[Window][DockSpaceViewport_11111111]
Pos=0,0
Size=1600,900
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][#]
Pos=0,0
Size=1600,87
Collapsed=0
DockId=0x00000003,0

[Window][Browser]
Pos=312,89
Size=1288,811
Collapsed=0
DockId=0x00000002,0

[Window][Shortcuts]
Pos=0,89
Size=310,811
Collapsed=0
DockId=0x00000001,0

[Docking][Data]
DockSpace     ID=0x8B93E3BD Window=0xA787BDB4 Pos=0,0 Size=1600,900 Split=Y
  DockNode    ID=0x00000003 Parent=0x8B93E3BD SizeRef=1600,87 HiddenTabBar=1 Selected=0x70659EFF
  DockNode    ID=0x00000004 Parent=0x8B93E3BD SizeRef=1600,811 Split=X Selected=0x9C79AD2F
    DockNode  ID=0x00000001 Parent=0x00000004 SizeRef=310,811 Selected=0x6FC2F711
    DockNode  ID=0x00000002 Parent=0x00000004 SizeRef=1288,811 CentralNode=1 Selected=0x9C79AD2F


```

When the Window[#]  is taken out of the dock:
```cpp
[Window][DockSpaceViewport_11111111]
Pos=0,0
Size=1600,900
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][#]
Pos=263,237
Size=1440,87
Collapsed=0

[Window][Browser]
Pos=312,0
Size=1288,900
Collapsed=0
DockId=0x00000002,0

[Window][Shortcuts]
Pos=0,0
Size=310,900
Collapsed=0
DockId=0x00000001,0

[Docking][Data]
DockSpace   ID=0x8B93E3BD Window=0xA787BDB4 Pos=0,0 Size=1600,900 Split=X
  DockNode  ID=0x00000001 Parent=0x8B93E3BD SizeRef=310,811 Selected=0x6FC2F711
  DockNode  ID=0x00000002 Parent=0x8B93E3BD SizeRef=1288,811 CentralNode=1 Selected=0x9C79AD2F


```

Let me know if you need more info.

**Comment by NoahR02** [comment]
Some more observations:
HiddenTabBar=1 gets set on the DockNode(in the ini file) when the .AutoHideTabBar(Dock_Node_Flags(public)) is set.

It seems like the the internal .NoTabBar enum does not persist in the ini file.
