### ISSUE TITLE
SDL2 with OpenGL 2.x and imgui for ui problems can you help

### ISSUE THREAD

**Issue by edselmalasig** [ocornut/imgui#560]
Hi i have this project and i tried to implement a SDL2 and imgui window and ui instead of glut but it only renders a blank screen. The ui isn't drawn as well. can you help ocornut. 

Here is my code

https://github.com/edselmalasig/sndpeek-imgui

**Comment by ocornut** [comment]
Sorry i can't help, this isn't an imgui issue.
When you ask questions you need to narrow it to very clear facts and amount of code. It also helps if you say thank you! Either way this isn't an imgui issue and I don't have the resources to debug everybody's rendering code.
