### ISSUE TITLE
Text Box Label

### ISSUE THREAD

**Issue by drdisconnect872** [ocornut/imgui#5604]
![GIF Recording 2022-08-23 at 12 36 51 PM](https://user-images.githubusercontent.com/73930619/186093578-1d5d6343-dbe6-402f-b69b-8aba67bf0dd5.gif)
How can I do this or how can I add a label inside the text field that will disappear when we click? I have searched the whole internet.

**Comment by rokups** [comment]
Use `ImGui::InputTextWithHint()`.
