### ISSUE TITLE
Compliments about your job !!!

### ISSUE THREAD

**Issue by luca2125** [ocornut/imgui#5605]
Hi,

I have tested your code inside a game and francally is incredible the final result ....

The custom window offer so much options that I think this work seem infinite.

I have tried many projects on gitub and your is the ONLY ONE the allow to draw to a game in fullscreen (the other work only on windowed mode or not work or not compile).

To be honest I need only draw some lines and rectangles in trasparent mode directly inside a game (your project use always menu).

At the moment with these lines:

    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = GetCurrentWindow();

    // Draw a rectangle
    ImVec2 RectTopCorrer = ImVec2(100, 100);
    ImVec2 RectDownCorner = ImVec2(200, 150);
    ImVec4 RectColor = ImVec4(1.0f, 1.0f, 1.0f, 0.5f); // 50% opaque white

    window->DrawList->AddRect(RectTopCorrer, RectDownCorner, GetColorU32(RectColor));

    // Draw a line
    ImVec2 LinePoint1 = ImVec2(150, 250);
    ImVec2 LinePoint2 = ImVec2(190, 250);
    ImU32  LineColor = ImGui::GetColorU32(RectColor);

    window->DrawList->AddLine(LinePoint1,  LinePoint2, LineColor, 1.0f);

I can draw lines and rectangle but I need to draw in trasparent mode  (without the window below).

There is a way to do it ?

Thanks and compliments again !!

**Comment by Kek5chen** [comment]
#1586 _prolly_

**Comment by ocornut** [comment]
> that draw simply a line or rectangle inside a DX11 game without add background ?

you can do this with dear imgui but you’ll have to put a minimum of effort since this is documented in the demo and has been answered here several times already.
