### ISSUE TITLE
Error When Building ImGui

### ISSUE THREAD

**Issue by Veronizlada** [ocornut/imgui#5607]
I get the following error when building Imgui:
error C2006: '#include': expected "FILENAME" or <FILENAME>
This is because of the code:

#ifdef IMGUI_USE_STB_SPRINTF
#define STB_SPRINTF_IMPLEMENTATION
#ifdef IMGUI_STB_SPRINTF_FILENAME
#include IMGUI_STB_SPRINTF_FILENAME
#else
#include "stb_sprintf.h"
#endif
#endif

In the file Imgui.cpp

Could you please help?

**Comment by ocornut** [comment]
> Could you please help?

No. You haven’t put the slightest effort reading issue guidelines, filling templates, providing enough information for people to help you. Therefore no we can’t help.
