### ISSUE TITLE
How to properly handle the mouse cursor?

### ISSUE THREAD

**Issue by kaishian** [ocornut/imgui#5610]
**Version/Branch of Dear ImGui:**

Version: v1.88

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Compiler: g++
Operating System: Ubuntu-20.04

**My Issue/Question:**

In order not to overwrite the newer mouse cursor state, shall we use following lines
```
if (g.MouseCursor == ImGuiMouseCursor_None) {
	g.MouseCursor = ImGuiMouseCursor_Arrow;
}
```

instead of this line ([line](https://github.com/ocornut/imgui/blob/master/imgui.cpp#L4549)) ?
```
g.MouseCursor = ImGuiMouseCursor_Arrow;
```

Any advice would be greatly appreciated.

**Comment by thedmd** [comment]
Your widget should call `ImGui::SetMouseCursor()` every frame it wants for cursor to be different.

As you already notice, it goes back to default at the start of every frame. Backend code run before new frame and have an opportunity to change OS cursor.
