### ISSUE TITLE
Programmatically remove text input focus

### ISSUE THREAD

**Issue by Clamb94** [ocornut/imgui#5611]
Version: v1.84 WIP 18302

Back-ends: custom
Operating System: windows

**My Issue/Question:**

Hi,
I'm looking for a way to programmatically remove the focus from something like an `ImGui::InputText` box.
Ideally I'm looking for a single command to remove the focus from any text box etc. in a window. 
So that `io.WantTextInput` returns false again.

Any idea how to do this?
Thanks!

**Comment by ocornut** [comment]
Hello,
While this is a legit question by itself (right now you cannot using the public api, but you can using the imgui_internal.h API) i would always start by asking the context and when/why you need to do that? We often derive better solutions when the context is known.
Cheers.

**Comment by Clamb94** [comment]
I'll look into imgui_internal.h, thanks.
The implementation I'm using let's ImGui run in a separate window, and mouse clicks will be passed through to ImGui, but only if I click within this separate window.
Which means, the text box will remain focused, even when I click somewhere else in my main program.
(I hope this was understandable)

**Comment by ocornut** [comment]
That’s understandable and makes sense. Showing a blinking cursor here would be misleading.

In this case, I believe using SetWindowFocus(NULL) (public API) may be the right thing to do to completely unfocus imgui windows.

The internal api would be eg SetNavID(0) which would unfocus an input text but leave a window focused from imgui point of view (leaving a blue title bar).

**Comment by Clamb94** [comment]
I'll give it a try, thanks!

**Comment by ocornut** [comment]
Closing as answered, let us know if that doesn't solve it.

**Comment by GrimMaple** [comment]
If anyone is looking for a way to actually remove focus from the text input (eg if you want to only allow entering one symbol), here is a hacky solution I came up with (C#):
```cs
ImGui.SameLine();
ImGui.Text("");
ImGui.SetKeyboardFocusHere();
```

This will basically make an invisible Text thing for 1 frame and set focus there, removing focus from InputText
