### ISSUE TITLE
Best way to hide/show the window or some elements inside

### ISSUE THREAD

**Issue by luca2125** [ocornut/imgui#5612]
Hi,

I'am studying the source code and the demos. For the moment I have created this code:

```
    static bool no_titlebar = true;
    static bool no_scrollbar = true;
    static bool no_menu = true;
    static bool no_move = true;
    static bool no_resize = true;
    static bool no_collapse = true;
    static bool no_close = true;
    static bool no_nav = true;
    static bool no_background = true;
    static bool no_bring_to_front = true;

    ImGuiWindowFlags window_flags = 0;
    if (no_titlebar)        window_flags |= ImGuiWindowFlags_NoTitleBar;
    if (no_scrollbar)       window_flags |= ImGuiWindowFlags_NoScrollbar;
    if (!no_menu)           window_flags |= ImGuiWindowFlags_MenuBar;
    if (no_move)            window_flags |= ImGuiWindowFlags_NoMove;
    if (no_resize)          window_flags |= ImGuiWindowFlags_NoResize;
    if (no_collapse)        window_flags |= ImGuiWindowFlags_NoCollapse;
    if (no_nav)             window_flags |= ImGuiWindowFlags_NoNav;
    if (no_background)      window_flags |= ImGuiWindowFlags_NoBackground;
    if (no_bring_to_front)  window_flags |= ImGuiWindowFlags_NoBringToFrontOnFocus;
    if (no_close)           p_open = NULL; // Don't pass our bool* to Begin

    if (!ImGui::Begin("Example: Custom rendering", p_open, window_flags))
    {
        ImGui::End();
        return;
    }

    // Set screen resolution to full screen
    ImVec2 Pos{ 0,0 };
    ImVec2 Size{ 1920, 1080 };
    ImGui::SetWindowPos(Pos, 0);
    ImGui::SetWindowSize(Size, 0);

    ImDrawList* draw_list = ImGui::GetWindowDrawList();

    // Draw a rectangle
    ImVec2 RectTopCorrer = ImVec2(100, 100);
    ImVec2 RectDownCorner = ImVec2(200, 150);
    ImVec4 RectColor = ImVec4(1.0f, 1.0f, 1.0f, 0.5f); // 50% opaque white

    draw_list->AddRect(RectTopCorrer, RectDownCorner, ImGui::GetColorU32(RectColor));

    // Draw a line
    ImVec2 LinePoint1 = ImVec2(150, 250);
    ImVec2 LinePoint2 = ImVec2(190, 250);
    ImU32  LineColor = ImGui::GetColorU32(RectColor);

    draw_list->AddLine(LinePoint1, LinePoint2, LineColor, 1.0f);

    ImGui::End();
```
that draw correctly a rectangle and a line on transparent window and work.

Now I need (if possible) to clear the content for drawing other rectangles / lines / etc,,

The first think that I was thiked is review all methods of "ImDrawList" and I have found:

_ResetForNewFrame();

but after call "draw_list->_ResetForNewFrame();"  before "ImGui::End();" the dll  crash. 

Probably I need to write other implementation for do it or this is not the right way.

Can you please suggest me the best approch to it ?

Thanks !

**Comment by ocornut** [comment]
> Now I need (if possible) to clear the content for drawing other rectangles / lines / etc,,

You shouldn’t need to “clear” anything. If you don’t want contents displayed, don’t draw them. The contents is cleared every frame and reflect your submission for that frame.

**Comment by luca2125** [comment]
In my case I need to draw a rectangle by pressing a key and when I press another key all rectangles must be delete and then I need to draw other rectangles (by pressing other keys) to other coordinates. Is possible do it ? Thanks !

**Comment by luca2125** [comment]
Thank you I have solved the problem myself now all work perfectly.

P.S.

Only for my curiosity I have another project where I studying DX11:

http://www.directxtutorial.com/Lesson.aspx?lessonid=11-4-5

In this project there is "swapChain->Present(1, 0);" while in your project not use it,

I think with the method "Present" it's the easiest way but I don't think it's the best. How can I use Draw without using "swapchain.Present"?

Thank you again !

**Comment by ocornut** [comment]
> In my case I need to draw a rectangle by pressing a key and when I press another key all rectangles must be delete and then I need to draw other rectangles (by pressing other keys) to other coordinates. Is possible do it ? Thanks !

Dear ImGui display whatever you submit to it. This is all under the control of your program code.
I realize you may be confused about how this works but I am sure you'll figure it out :)

> In this project there is "swapChain->Present(1, 0);" while in your project not use it,

We also call `Present()` in the `examples/example_win32_directx11/main.cpp` example.
Remaining questions are unrelated to dear imgui and are DX11/Graphics Programming question.
