### ISSUE TITLE
Menu closing on hover (Was: How to draw menu-item to the left from menu in right-aligned sidebar?)

### ISSUE THREAD

**Issue by OneForgottenMan** [ocornut/imgui#5614]
**Version/Branch of Dear ImGui:**

Version: 1.89 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Compiler: msvc
Operating System: Windows 7

**My Issue/Question:**

I'm trying to make menu-items in right-aligned sidebar, but i have a problem. When i hovering menu is drawing menu-items outside of window, so when i trying move cursor to select item, sometimes, it closes instantly because losing the hovering of menu.
Is there a way to force menu draw its items to the left from it?

**Screenshots/Video**

![2022-08-28_055311](https://user-images.githubusercontent.com/58083488/187055585-7ca12609-24c8-441e-96d5-b226f51714c2.jpg)

**Standalone, minimal, complete and verifiable example:**
```
if (ImGui::BeginViewportSideBar(
    "##RightToolbar",
    NULL,
    ImGuiDir_Right,
    164.f,
    ImGuiWindowFlags_NoDocking
))
{
    if (ImGui::CollapsingHeader("Scene", ImGuiTreeNodeFlags_DefaultOpen))
    {
        if (ImGui::BeginMenu("File"))
        {
            ImGui::MenuItem("Open");
            ImGui::EndMenu();
        }
    }
    ImGui::End();
}
```

**Comment by ocornut** [comment]
Hello, thanks for posting.

> so when i trying move cursor to select item, sometimes, it closes instantly because losing the hovering of menu.

This is an XY Problem question. We should absolutely focus on this. If you have viewports enabled, menus can appear on the right. Should focus on why it closes instantly. Can you make a video of it ?

Can you recreate the issue when using unmodified example_win32_dx9 example ?

**Comment by OneForgottenMan** [comment]
GIF of this issue in my app:
![Menu bar problem](https://user-images.githubusercontent.com/58083488/187068080-8811b3cc-ff8a-442d-a4fc-25cfd9153461.gif)

GIF of this issue in example_win32_dx9:
![Menu bar problem in example](https://user-images.githubusercontent.com/58083488/187068291-ab1533cd-a466-4bc6-9dc3-cf9533fb5d6a.gif)

**Comment by ocornut** [comment]
We pushed b3ea01d8 and 03fc9a0b1, the combination of those should fix this bug.

We basically always (and still have) a couple of subtle issue with using BeginMenu() from a regular window that isn't a menu or a popup. Some are tricky to fix some not. Working on this I fixed another, it wasn't possible to open such menu with the Right Arrow (9445776). And it is still not possible to close them via Left Arrow.

Thanks for reporting.
Please let us know if for some reason things aren't fixed for you.
