### ISSUE TITLE
Table Cell Height + Selectable, does not highlight the full item's height + padding.

### ISSUE THREAD

**Issue by NoahR02** [ocornut/imgui#5615]
**Version/Branch of Dear ImGui:**

Version: v1.88
Branch: docking

My Issue/Question:
How do I make `ImGui::Selectable` take the whole cell height, including padding? I tried setting FramePadding on various elements inside the cell and then removing the CellPadding, but I suspect that doesn't work because of how the Table API lays out items. I also tried setting the size of the `Selectable` and getting the cell height + the padding but that seems to add extra cell height.

It is my assumption that the padding should be taken into account because if you hover over a ImGuiButton with FramePadding added to it, the selection will take up the whole item's height + the item's padding.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/51396418/187071179-2d84f805-fba6-43c5-94f1-50200cb52bfd.png)
![image](https://user-images.githubusercontent.com/51396418/187072422-be4a386e-e0e6-4d66-a1dd-be73cfd6e300.png)

**Standalone, minimal, complete and verifiable example:**
```cpp
  imgui.push_style_var_vec2(imgui.Style_Var.CellPadding, {15, 15})
  if imgui.begin_table("", 3, .PadOuterX | .Resizable) {

    for row := 0; row < len(file_ctx.files); row += 1 {
      id_str_buf: [4]byte
      imgui.table_next_row()

      imgui.table_set_column_index(0)
      file_name_icon := file_ctx.files[row].is_dir ? ICON_FA_FOLDER : ICON_FA_FILE

      imgui.push_id(strings.concatenate({"BROWSER-ROW-", strconv.itoa(id_str_buf[:], row)}, context.temp_allocator))
      if imgui.selectable_bool("", {}, .SpanAllColumns | .AllowDoubleClick, {0,  0}) {
            //... Internal Logic
      }
      // Potential Bug? Without same_line(), the text will go on a newline.
      imgui.same_line()
      imgui.text("%s  %s", file_name_icon, file_ctx.files[row].name)

      size: [500]byte
      size_str := strconv.itoa(size[:], int(file_ctx.files[row].size / 1000))
      imgui.table_set_column_index(1)
      imgui.text("%s %s", size_str, "KB")

      imgui.table_set_column_index(2)
      imgui.text("Date Modified")
      
      imgui.pop_id()
    }
    imgui.end_table() 
    imgui.pop_style_var(1)
```
Off topic (feel free to ignore this): Is there a way to get multiple selections with `ImGui::Selectable()`?

**Comment by rokups** [comment]
Actual minimal test case with a fix:
```cpp
ImGui::Begin("Test");
ImGuiStyle& style = ImGui::GetStyle();
ImGui::PushStyleVar(ImGuiStyleVar_CellPadding, {15, 15});
if (ImGui::BeginTable("table", 1, ImGuiTableFlags_PadOuterX | ImGuiTableFlags_Resizable | ImGuiTableFlags_Borders))
{
    ImGui::TableNextRow();
    ImGui::TableSetColumnIndex(0);
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(style.ItemSpacing.x, style.CellPadding.y * 2)); // Fix
    ImGui::Selectable("...", false, ImGuiSelectableFlags_SpanAllColumns | ImGuiSelectableFlags_AllowDoubleClick);
    ImGui::PopStyleVar();
}
ImGui::EndTable();
ImGui::PopStyleVar();
ImGui::End();
```

Curious detail is that we counter-intuitively have to use `style.CellPadding.y * 2` for vertical `ImGuiStyleVar_ItemSpacing`, as `Selectable()` uses half-size of `ImGuiStyleVar_ItemSpacing` to expand it's size.

**Comment by NoahR02** [comment]
> nter-intuitively have to use `style.CellPadding.y * 2` for ver

Thank you! That fixed it and everything is working now :)

**Comment by ocornut** [comment]
> Off topic (feel free to ignore this): Is there a way to get multiple selections with ImGui::Selectable()?

Selection is under your control. You may handle Ctrl+Click style selection manually and fairly easily (this is demonstrated in the demo window).

Shift+Click style and Shift+PageUp etc are more complex to implement in particular if you want to use a list clipper. this is what the api in the range_select branch aims to solve. I think i am going to finish/polish this api and include it in 1.90
