### ISSUE TITLE
BeginDragDropSource() not working with ImageButtonEx Item

### ISSUE THREAD

**Issue by dame-time** [ocornut/imgui#5623]
I'm trying to make an ImageButtonEx draggable, though it doesn't seem to work.
I've also tried to use the code that @ocornut posted here [Issue #3885](https://github.com/ocornut/imgui/issues/3885) but I still can't see any improvements.

Here is a sample of my code:
```
#pragma warning(push)
#pragma warning(disable : 4312)                
ImGui::ImageButtonEx(
                            UUID(),
                            (ImTextureID)buttonImages.sceneTextureID, 
                            { thumbnailSize, thumbnailSize },
                            { 0, 0 },
                            { 1, 1 },
                            { 10, 10 },
                            { 0, 0, 0, 0 },
                            { 1, 1, 1, 1 }
                    );
#pragma warning(pop)
ImGuiWindow* window = ImGui::GetCurrentWindow();
ImGui::ButtonBehavior(ImRect(ImGui::GetItemRectMin(), ImGui::GetItemRectMax()), ImGui::GetItemID(), NULL, NULL, 
 ImGuiButtonFlags_MouseButtonMiddle | ImGuiButtonFlags_MouseButtonRight | ImGuiButtonFlags_MouseButtonLeft);
if (ImGui::BeginDragDropSource())
{
    ImGui::SetDragDropPayload("SCENE_ITEM", path.string().c_str(), path.string().size(), ImGuiCond_Once);
    ImGui::EndDragDropSource();
}
```

though if I change from ImageButtonEx to TreeNode everything works fine (but I would prefer to stick with ImageButtonEx).
Any idea of why this happens?

**Comment by dame-time** [comment]
> Edit: Any chance you are doing something funky in `UUID()` and you are getting an ID collision?

That was the issue. For some strange reason, I have a `UUID()` issue that made my button clickable but not draggable. I'm not too sure why this happens, but I'll stick to `ImageButton()` for now and I'll try to fix my `UUID()` class.

Thank you! :)

**Comment by rokups** [comment]
Are you sure you need `UUID()` at all? Dear ImGui uses ID stack where IDs are seeded with ID on top of the stack. You can reuse same IDs provided they are on different levels in ID stack. For example:

```cpp

ImGui::Begin("Window 1");
ImGui::ImageButtonEx(ImGui::GetID("Button"));  // OK
ImGui::ImageButtonEx(ImGui::GetID("Button"));  // Not OK, button with same ID above
ImGui::PushID(1);                              // Create new ID stack level
ImGui::ImageButtonEx(ImGui::GetID("Button"));  // OK due to PushID()
ImGui::PopID();
ImGui::End();

ImGui::Begin("Window 2");
ImGui::ImageButtonEx(ImGui::GetID("Button"));  // OK, different windows have separate ID stacks
ImGui::End();
```

**Comment by dame-time** [comment]
> Are you sure you need `UUID()` at all?

Well, actually no, I didn't need them, I could have used ImGui IDs! 
But I adopted the `UUID()` in order to avoid the *pushing* and *popping* of IDs inside the code, to make everything cleaner and less confusing! That being said if I can't fix my class I'll probably switch to the ImGui IDs.

Thanks for the help!

**Comment by ocornut** [comment]
Also see FAQ about the ID Stack.

For this specific function, we recently (finally) introduced a ImageButton() that takes a string identifier so you can use that and not have to call GetID() directly.
