### ISSUE TITLE
Hitting tab key in the input text box makes it loop endlessly between boxes

### ISSUE THREAD

**Issue by svkvarun43** [ocornut/imgui#5626]
**Version/Branch of Dear ImGui:**

Version: V1.88
Branch: master

**My Issue/Question:**

Hitting tab key in the input text box makes it loop endlessly between boxes, no way to recover without restarting the application

**Screenshots/Video**

https://user-images.githubusercontent.com/98422353/187671429-123b6d14-054f-41c6-a97e-a1c5224e6b21.mp4

**Standalone, minimal, complete and verifiable snippet:**
```
ImGui::InputTextWithHint("Host Machine", "eg : localhost, 10.0.0.4", input.hostmachine, IM_ARRAYSIZE(input.hostmachine));
ImGui::InputTextWithHint("Port", "eg : 9090", input.port, IM_ARRAYSIZE(input.port), ImGuiInputTextFlags_CharsDecimal);
ImGui::InputTextWithHint("Topics/Robots", "eg : /Oct5Boom, Oct5Boom", input.subjectnames, IM_ARRAYSIZE(input.subjectnames));
```
As I believe using tab to switch fields is a common shortcut, is there any way around this issue please?

**Comment by ocornut** [comment]
What is your backend ? (THIS IS REQUESTED BY ISSUE TEMPLATE)
Can you verify under Demo>Inputs that your tab key is not stuck (aka dear imgui stills sees it as down) ?

**Comment by ocornut** [comment]
(Sorry closed accidentally, reopening)

**Comment by svkvarun43** [comment]
@ocornut 
Sure

Currently using imgui forked from [https://github.com/WiggleWizard/UnrealImGui](https://github.com/WiggleWizard/UnrealImGui)

The inputs are working with tab in the ShowDemoWindow

So not sure why it doesn't work there.

**Comment by ocornut** [comment]
Well, your repro doesn't work, when I test it things work fine.
```cpp
ImGui::Begin("Test #5626");
static char hostmachine[128] = "";
static char port[128] = "";
static char subjectnames[128] = "";
ImGui::InputTextWithHint("Host Machine", "eg : localhost, 10.0.0.4", hostmachine, IM_ARRAYSIZE(hostmachine));
ImGui::InputTextWithHint("Port", "eg : 9090", port, IM_ARRAYSIZE(port), ImGuiInputTextFlags_CharsDecimal);
ImGui::InputTextWithHint("Topics/Robots", "eg : /Oct5Boom, Oct5Boom", subjectnames, IM_ARRAYSIZE(subjectnames));
ImGui::End();
```

![issue_5626](https://user-images.githubusercontent.com/8225057/187872555-0037041e-1929-43e0-ac14-f879f8b9aa18.gif)

So your repro is missing something which is interfering. We can't magically debug/audit your code without a repro.
You'll have to find what's interfering, if it is an issue with handling of the Tab key, or if you have code setting focus.

If you are on a recent version maybe `Demo>Tools>Debug Log` can help you find why focus is moving.
