### ISSUE TITLE
How to use cyrillic in IMGUI

### ISSUE THREAD

**Issue by UnrealKaraulov** [ocornut/imgui#5630]
```c++
 char cell_size[256] = { '\0' };
 ...
 ImGui::Begin("Hello, world!");      
 ...
 ImGui::InputText("##text1", cell_size, sizeof(cell_size));
 ...
 ImGui::End();
```

I see only '??????????????'

Please fix this fatal error!

**Comment by nicolasnoble** [comment]
You'd need to load a font for non-Latin1 display. See https://github.com/ocornut/imgui/blob/master/docs/FONTS.md for details.

**Comment by UnrealKaraulov** [comment]
@nicolasnoble imgui need support Cyrillic in default font

**Comment by nicolasnoble** [comment]
> @nicolasnoble imgui need support Cyrillic in default font

No.

**Comment by UnrealKaraulov** [comment]
> > @nicolasnoble imgui need support Cyrillic in default font
> 
> No.

Yes! Not support!

**Comment by UnrealKaraulov** [comment]
@ocornut please sorry for ping :) But may be possible to add Cyrillic to default imgui font ?((( or do you think everyone who uses the Cyrillic alphabet is bad people unworthy of using a standard font? 🤣

**Comment by ocornut** [comment]
Just load your own font.
We can't add too many character to the default font it is an old bitmap font designed to be embedded in the source code.

**Comment by UnrealKaraulov** [comment]
> Just load your own font. We can't add too many character to the default font it is an old bitmap font designed to be embedded in the source code.
@ocornut 
I tried to load font via https://github.com/ocornut/imgui/blob/master/misc/fonts/binary_to_compressed_c.cpp with -base85 encoding.  But got same result. "??????????????" instead of cyrillic. And `AddFontFromMemoryCompressedBase85TTF` cause crash. Works only `AddFontFromMemoryCompressedTTF`

I use font 'calibri' 
![image](https://user-images.githubusercontent.com/88730285/189484219-c607550c-0959-4be4-8fea-3120636f3e2c.png)

**Comment by UnrealKaraulov** [comment]
![image](https://user-images.githubusercontent.com/88730285/189484251-b03bdd01-1ab1-4255-90ac-d8c0084016d3.png)

**Comment by UnrealKaraulov** [comment]
@ocornut you can't add native support for Russian ? I can't use cyrillic :(

**Comment by ocornut** [comment]
You can use Metrics>Fonts to browse and confirm loaded fonts, you can use Metrics>Tools>UTF8 encoding viewer and associated function to confirm encoding of your text data.
