### ISSUE TITLE
 A window without a title bar with only bottom rounding corners

### ISSUE THREAD

**Issue by SC5Shout** [ocornut/imgui#5632]
**My Issue/Question:**

Is there an easy way to create a window without a title bar with only bottom rounding corners? I'd like the top corners to be square.

I see there's no `ImGui::PushStyleVar(ImGuiStyleVar_WindowRoundingCorners, ImDrawCornerFlags_Bot)` or something like this.
I could make my own window function with this parameter but I don't want to modify `imgui.h/cpp` files.
To not modify `imgui.h/cpp` files I could make my own `Window` or something like this file, copy and paste the `ImGui::Begin` function and modify it as I need, but it's like ~2k of code (I don't know exactly, I gave up after copying ~1k.  
I could also include ImGui.cpp but it'd include a whole file which is large

**Comment by ocornut** [comment]
> Is there an easy way to create a window without a title bar with only bottom rounding corners?

No there isn't without modifying the code as you found.

I think your best bet is to create a patch and rebase your branch (keep the patch) when updating dear imgui. Git is pretty good at those stuff, the main difficulty is learning to use git but rebasing a small feature branch is commonly documented.

Right now it's unlikely we'll want to be adding that sort of style settings before reoverhauling the style structure

**Comment by SC5Shout** [comment]
:/ Thanks, doe
