### ISSUE TITLE
Random Crashing & Flickering Screen when I have no vSync

### ISSUE THREAD

**Issue by Arefu** [ocornut/imgui#5633]
(Click "Preview" above ^ to turn URL into clickable links)

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.89
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-ends: Win32, DirectX11
Compiler: VS2022 v143 Windows SDK 10
Operating System: Windows 11,

**My Issue/Question:**
I've managed to successfully link and get the Example Windows to show, however these are my issues

1.  When I launch the program with no vSync I get a very visually pleasing eye watering flicker, it flashes all sorts of colors, I'm not sure if this is due to my logic on how I am drawing the menu's (view attached file called Flicker for a video)
2. When launching my program, it randomly crashes almost instantly, I am not sure what I am doing here differently when I get it to run with no issues, 

**Screenshots/Video**
[Flicker.webm](https://user-images.githubusercontent.com/11144734/188125879-73246e60-7864-4bc3-b198-4b72cdb6a7a3.webm)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
https://pastebin.com/pdEkhCVa
https://pastebin.com/iHTQBsp3

This is all being called from the context of an Injected DLL using Microsoft Detours, I've injected my DLL using Detours and using CreateProcessWtihDllEx so I assume it shouldn't be causing any grief, my UIMod::SetupGUI is called part of the DllAttatch event using a new Thread so I am not holding up things. I'm also aware of this project's stance on cheaters, I can assure you I am not doing anything of the sort, you can check my other repos and see I have one called Wolf, this project I am currently working on is related to the game, however it is your discretion.

**Comment by rokups** [comment]
You have two directx contexts fighting for which will render into same window. Sometimes one context wins, sometimes another one. If i remember correctly, you are supposed to hook directx's `Present()` function and do your rendering before calling original function. In any case, this is unrelated to Dear ImGui and you are using library in a totally unsupported context, so you are on your own :) Internet is full of examples though, you will figure it out.

**Comment by ocornut** [comment]
What @rokups said, I believe you should hook into the existing context rather than have two.
It's an issue on your end, and unfortunately we don't have resource to start debugging people's project.

**Comment by Arefu** [comment]
That's fine, I had a sneaking suspicious feeling as I was going to bed that creating two DirectX context's would be a bad time. 

I'll see what I can come up with and get back to you if I've got anything extra to ask

**Comment by Arefu** [comment]
Resolved this after a lot of "huh" today, I guess I might not be super up tot his, but oh well I am gonna keep cracking at it.

I can create a new issue for this if you prefer, but I don't know, I feel like this should be a simple thing.
The demo looks fine, however my program does not, everything is blurry and the mouse cursor is offset
https://pastebin.com/irw3VtqS

That's the code I'm using to show the basic example box, it works and looks fine whern the app is in fullscreen 1080, but not at all even if it starts from any other resolution.

**Comment by rokups** [comment]
Do not create a new issue. What you are doing is completely out of scope of Dear ImGui. We do not have resources to develop projects of other people, nor we want to. Internet is full of examples, like [this one](https://github.com/rdbo/ImGui-DirectX-11-Kiero-Hook/tree/master/ImGui%20DirectX%2011%20Kiero%20Hook) i found in 30s of googling.
