### ISSUE TITLE
AddFontDefault not working!

### ISSUE THREAD

**Issue by UnrealKaraulov** [ocornut/imgui#5635]
Function `AddFontDefault` not working for Windows. Used `unknown` font instead of default Windows font (`Segoe UI`).

**Comment by PathogenDavid** [comment]
The purpose of `AddFontDefault` is not to load the operating system's default font ([Proggy Clean by Tristan Grimmer](https://github.com/bluescan/proggyfonts#proggy-original).)

The purpose of `AddFontDefault` is to load Dear ImGui's default font. It is intended for scenarios where you want to keep the default font loaded in addition to another (such as an icon font.)
