### ISSUE TITLE
Ctrl+clicking SliderFloat/DragFloat keeps returning true even without change

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#564]
Steps to reproduce:

1. Open imgui's test window
2. doubleclick on Widgets -> drag float
3. press "5"
4. do not press anything else, keep the DragFloat "opened"
5. put a breakpoint in https://github.com/ocornut/imgui/blob/master/imgui.cpp#L7624
6. observe it is hit all the time

Note: edit_state.TempTextBuffer.Data == "5", buf == "5.000"
Note: DragInt works fine

Expected result: DragFloat should not return true unless the value is changed

Tested on revision 5b8aa0dc844af7bac20af204e462c7f199db2fd4

**Comment by ocornut** [comment]
FYI also happens with SliderFloat() it seems, it is the turn-into-text-edit behavior that does that.
Working on it.

( 
First thought it was related to this change 18 days ago, but it isn't
https://github.com/ocornut/imgui/commit/9ea093ddd0c0ef9523d0918099f1a3a59eb6a42b
)

**Comment by ocornut** [comment]
Fixed.
Also fixed stuff like:
InputFloat() "1.0000" : inputting additional zero "1.000000000000" would return true.

**Comment by nem0** [comment]
Works like a charm, thanks
