### ISSUE TITLE
Extension of ImGuiWindow to hold arbitrary pointer to other data.

### ISSUE THREAD

**Issue by slajerek** [ocornut/imgui#5640]
Hello!

For my purposes, I need to extend ImGuiWindow with an arbitrary pointer to my data. Whenever I upgrade ImGui I need to patch ImGuiWindow to add my pointer to engine structures for features like full-screen view, store/restore layouts, etc. Is there something like `void *anything` in the ImGuiWindow I can store somewhere? I already patched platform code some time ago but this requires updates too. A simple extension of whatever data programmer needs void* pointer is quite simple and works for me and I am able to achieve what I want.

I normally just add:
```
public:	void *userData;
```
in the ImGuiWindow, which actually sometimes points to an additional child view that is implemented with its own other GUI engine.

This enhancement could be a simple compile-time switch defined in imconfig.h

Or... what is a correct way to achieve the above case?

Thanks,
Marcin

**Comment by ocornut** [comment]
> Or... what is a correct way to achieve the above case?

Use GetWindowStorage()->SetVoidPtr(ImGuiID, void*) etc.

**Comment by ocornut** [comment]
Closing as answered.

**Comment by slajerek** [comment]
Thanks, @ocornut I wasn't aware of this!
