### ISSUE TITLE
Disable CTRL+Tab switcher popup?

### ISSUE THREAD

**Issue by invrainbow** [ocornut/imgui#5641]
I'm on commit `77637fd9`.

I'm building an IDE-like program and relying heavily on docking to draw the main user interface. I have an "empty section" where I draw my own application. Before, when the user did not have any tab/window focused, I would assume they had the "empty section" focused, and handle Ctrl+Tab manually.

I'm not sure when this happened, but recently I upgraded to commit `77637fd9`. Now when the user presses Ctrl+Tab, no matter where they are, this tab switcher popup thingy opens.

![image](https://user-images.githubusercontent.com/77120437/188307453-2815c310-3a3c-4b89-948b-28ae2d32d5f7.png)

Questions in descending order of optimality:

1. Can I just disable this popup completely?
2. If not, can I have it only open when a tab is focused, and not *globally*?
3. If not, can I exclude the main menu from the list?
4. If not, how can I find the commit where this was introduced?

Thanks!

**Comment by PathogenDavid** [comment]
> 1. Can I just disable this popup completely?
> 2. If not, can I have it only open when a tab is focused, and not *globally*?

Currently you cannot without modifying Dear ImGui.

> 3. If not, can I exclude the main menu from the list?

Pass `ImGuiWindowFlags_NoNavFocus` to `ImGui::Begin`.

> 4. If not, how can I find the commit where this was introduced?

The feature its self has been there for ages, but previously it was tied to keyboard navigation. It was enabled by default in https://github.com/ocornut/imgui/commit/8ce23b3ccd5b9338002f58679a3fc53559d3280b as a part of https://github.com/ocornut/imgui/issues/4023.

**Comment by ocornut** [comment]
We have a change hopefully coming in 1.89 which will make it possible to disable ctrl-tab among other things.

**Comment by ocornut** [comment]
The reason the main menu bar doesn't use `ImGuiWindowFlags_NoNavFocus` is because we don't have a mechanism to globally use ALT to move to that menu bar, therefore it is often the only way to access it with the keyboard. You may however write a copy of the `BeginMainMenuBar()` and add the flag if wanted.

**Comment by invrainbow** [comment]
Thanks for all the info!

After digging through imgui.cpp I successfully disabled ctrl+tab by setting `GImGui->NavWindowingTarget = NULL` after `ImGui::NewFrame()` in my code (also nice because I don't have to modify imgui). Do you see anything problems down the road with doing this?

**Comment by ocornut** [comment]
Pushed a few new features and you can now do:

```cpp
#include "imgui_internal.h"

// Disable CTRL+Tab shortcuts (global): assign a "None" route to steal the route to our two shortcuts
ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiKeyOwner_None);
ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab, ImGuiKeyOwner_None);
```
or
```cpp
// Disable CTRL+Tab shortcuts (if focused): assign a "None" route to steal the route to our two shortcuts, applies focus testing so will only apply if window is in focus chain
ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiKey_Tab, ImGuiKeyOwner_None, ImGuiInputFlags_RouteFocused);
ImGui::SetShortcutRouting(ImGuiMod_Ctrl | ImGuiMod_Shift | ImGuiKey_Tab, ImGuiKeyOwner_None, ImGuiInputFlags_RouteFocused);
```

However, as per #4828 we made the exception to allow remapping CTRL+Tab windowing system. Therefore technically the right shortcut needs to be pulled:

```cpp
if (g.ConfigNavWindowingKeyNext)
    ImGui::SetShortcutRouting(g.ConfigNavWindowingKeyNext, ImGuiKeyOwner_None);
if (g.ConfigNavWindowingKeyPrev)
    ImGui::SetShortcutRouting(g.ConfigNavWindowingKeyPrev, ImGuiKeyOwner_None);
```
But this is only if you want to both allow remapping AND disabling of the shortcuts.

(cross posted to #3255 and #5641)
