### ISSUE TITLE
imgui_impl_opengl3 macro redefinitions using GLAD, GLFW, OPENGL

### ISSUE THREAD

**Issue by petrasvestartas** [ocornut/imgui#5642]
Hi,

I have a lot of macros redefined mainly coming from #include "imgui_impl_opengl3.h" and  "imgui_impl_opengl3.cpp"
I am using GLAD, GLFW, OPENGL, and recent IMGUI. How can I avoid these redefinitions?

![image](https://user-images.githubusercontent.com/18013985/188308678-d5085c56-29a9-485a-b459-c603404e9231.png)

After including this  **#define IMGUI_IMPL_OPENGL_LOADER_CUSTOM**
I get 4 unsafe warnings, maybe I am to picky but I would like to resolve those:
![image](https://user-images.githubusercontent.com/18013985/188309808-47d2cade-1ae0-4b70-9f10-255e32b270cc.png)

**Comment by PathogenDavid** [comment]
For future reference, build issues should be opened as [GitHub Discussions](https://github.com/ocornut/imgui/discussions).

> imgui_impl_opengl3.cpp

Generally speaking, you should not include `.cpp` files. They should be built separately and then linked, which avoids this issue.

As you've found though, if you're doing a unity build you can define `IMGUI_IMPL_OPENGL_LOADER_CUSTOM` to avoid the duplicate definitions.

> I get 4 unsafe warnings, maybe I am to picky but I would like to resolve those:

Not sure why you're getting those warnings unless you modified `imgui_impl_opengl3.cpp`, it's supposed to disable them:

https://github.com/ocornut/imgui/blob/edcd5b113e1e6700a1e9fa1aba466bc335bd127f/backends/imgui_impl_opengl3.cpp#L88-L90

The "secure" variants of those functions are Microsoft-specific. Dear ImGui is cross-platform so we can't use them.

**Comment by ocornut** [comment]
If the standard headers are included before the define you’d get the warning, therefore it makes sense they would get the warnings on a unity/jumbo build.

**Comment by PathogenDavid** [comment]
Oh right, that'd do it too 😅

**Comment by ocornut** [comment]
I have added extra comments in the header of this file, hoping it'd help people find the issue.
