### ISSUE TITLE
Updating DirectX9 imgui in real-time while resizing window

### ISSUE THREAD

**Issue by DynamicalCreator** [ocornut/imgui#5645]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Operating System: Windows 10 Home

**My Issue/Question:**

I have a DirectX9 application, and my imgui window is in fullscreen. While i'm resizing the window, the imgui window doesn't update in real-time (see the attachments below), instead it covers the new area in black. However, in DirectX12 the imgui window updates in real-time, while resizing. How could i achieve similar action in DirectX9?

**Screenshots/Video**

Resizing in DirectX9 (the background is red to see the difference easier):

https://user-images.githubusercontent.com/79928133/188329785-b400ebbc-7bd4-443b-895c-7982f5383980.mov

Resizing in DirectX12:

https://user-images.githubusercontent.com/79928133/188329803-96845017-0f49-44b3-b415-957e0a5eb447.mov

**Comment by ocornut** [comment]
This has been asked many times. This is not a Dear ImGui question this is a Win32 API question.
See e.g.
https://github.com/ocornut/imgui/issues/5274#issuecomment-1115952986

**Comment by DynamicalCreator** [comment]
> This has been asked many times. This is not a Dear ImGui question this is a Win32 API question. See e.g. [#5274 (comment)](https://github.com/ocornut/imgui/issues/5274#issuecomment-1115952986)

Oh, didn't see that. Thanks for fast reply.
