### ISSUE TITLE
CodeQL security scan finds some possible problems

### ISSUE THREAD

**Issue by ItsSunnyMonster** [ocornut/imgui#5646]
**Version/Branch of Dear ImGui:**

Version: 1.89 WIP
Branch: docking

**My Issue/Question:**

My CodeQL security scan finds a few problems regarding multiplication overflows and it marked it with a severity of `high`.
Since I do not know how ImGui works, I don't know if this issue is relevant or not, but I will still open the issue just in case. 
(The line numbers will be where the line is in the docking branch **at the time of writing** so it would probably be a better idea to control+f for the code.)
- at `imgui_widgets.cpp` line `2749`:
```c++
FLOATTYPE v_new_off_f = (SIGNEDTYPE)(v_max - v_min) * t;
``` 
CodeQL message: `Multiplication result may overflow 'float' before it is converted to 'double'. `

- at `imgui_draw.cpp` line `764`: 
```c++
ImVec2* temp_normals = (ImVec2*)alloca(points_count * ((use_texture || !thick_line) ? 3 : 5) * sizeof(ImVec2)); //-V630
```
CodeQL message: `Multiplication result may overflow 'int' before it is converted to 'unsigned long long'. `

- at `imgui_draw.cpp` line `2532`:
```c++
memset(atlas->TexPixelsAlpha8, 0, atlas->TexWidth * atlas->TexHeight);
```
CodeQL message: `Multiplication result may overflow 'int' before it is converted to 'size_t'. `

- at `imgui_draw.cpp` line `2531`:
```c++
atlas->TexPixelsAlpha8 = (unsigned char*)IM_ALLOC(atlas->TexWidth * atlas->TexHeight);
```
CodeQL message: `Multiplication result may overflow 'int' before it is converted to 'size_t'. `

- at `imstb_truetype.h` line `3750`:
```c++
gbm.pixels = (unsigned char *) STBTT_malloc(gbm.w * gbm.h, info->userdata);
```
CodeQL message: `Multiplication result may overflow 'int' before it is converted to 'size_t'. `

- at `imstb_truetype.h` line `3833`:
```c++
STBTT_memset(pixels, 0, pw*ph); // background of 0 around pixels
```
CodeQL message: `Multiplication result may overflow 'int' before it is converted to 'size_t'. `

- at `imstb_truetype.h` line `3992`:
```c++
STBTT_memset(pixels, 0, pw*ph); // background of 0 around pixels
```
CodeQL message: `Multiplication result may overflow 'int' before it is converted to 'size_t'. `

- at `imstb_truetype.h` line `4619`:
```c++
data = (unsigned char *) STBTT_malloc(w * h, info->userdata);
```
CodeQL message: `Multiplication result may overflow 'int' before it is converted to 'size_t'. `

**Comment by ocornut** [comment]
Thanks for submitting those. They are all technically valid but in the grand context of Dear ImGui i don't think it is worth fixing much of those, and they connect to other things which are less likely to budge soon. 
The most interesting one ihmo is `FLOATTYPE v_new_off_f = (SIGNEDTYPE)(v_max - v_min) * t;` but it would only make a difference when editing very large 64-bit integer ranges with a Slider or Drag, which is pretty meaningless in the first place.

IHMO it is saner to just ignore those.
