### ISSUE TITLE
Lower-than-expected frame rate with higher swap interval and refresh rate

### ISSUE THREAD

**Issue by RealOfficialTurf** [ocornut/imgui#5651]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: I used the one in Release page, so "master"

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Windows 10

**My Issue/Question:**

I set my swap interval value using glfwSwapInterval(2) and expected that, in my monitor display set to 120 Hz refresh rate, I would get 60 fps.

But for a reason unknown to me, I only managed to get around 21.5 fps (when the window is focused). When I click away from the window (thus unfocusing the window), the frame rate rose back to 60 fps, which is what I've expected.

**However**, when I changed my monitor display refresh rate to 60 Hz (not changing swap interval value), I get a steady 30 fps, focused or not.

I also tested this on 75 Hz and 144 Hz. Both of them experience frame rate drops the same way as the 120 Hz one.

For curiosity, I also tested this on Win32 and DX11 back-end. Still experienced frame rate drop.

So, what makes the frame rate drop when the window is focused, with higher swap interval value and refresh rate set to other than 60 Hz? Was it because of the Dear ImGui itself? Or was it Windows issue?

**Standalone, minimal, complete and verifiable example:**

For imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp back-ends:
1. Ensure that your display refresh rate is set to anything else other than 60 Hz.
2. Open the provided example application `example_glfw_opengl3`.
3. Replace the code `glfwSwapInterval(1)` with `glfwSwapInterval(2)`.
4. Build and run.
5. Notice the frame rate counter given by the example application.

**Comment by ocornut** [comment]
Hello,

This seemingly has to do with Dear ImGui and probably won't repro on all setups.
It may be a combination of GPU Drivers, Drivers Settings, Application Settings/Code. If you confirm it also happens with Win32 backends I assume GLFW has nothing to do with it either.

Unfortunately this is not a good place to ask.

On laptop there's typically an e
