### ISSUE TITLE
Support for ISO-8859-1 encoding?

### ISSUE THREAD

**Issue by Jastcher** [ocornut/imgui#5657]
Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: clang
Operating System: Arch linux

**My Issue/Question:**

Would be nice if ISO-8859-1 encoding was added to ImGui::Text, is this possible?

**Comment by ocornut** [comment]
It won't be possible. UTF-8 is the defacto standard nowadays. You can convert your source code or data source into UTF-8 from whatever legacy encoding your data is.
