### ISSUE TITLE
Crash on shutdown

### ISSUE THREAD

**Issue by kmilo9999** [ocornut/imgui#5658]
**Version/Branch of Dear ImGui:**

Version: v1.87

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp
Compiler: Visual studio 2019
Operating System: Windows

**My Issue/Question:**

I am using imgui on my app,  when I build it on release mode it crashes on closing the GLFW window. The "debug" process takes me to the following line:
```
void ImGui::Shutdown(ImGuiContext* context){
..
..
 g.Windows.clear_delete();
..
..
}
```

The debug build doesnt crash. 
I dont know what could be a possible problem for this. Any thoguhts?

**Screenshots/Video**

![clip-crash](https://user-images.githubusercontent.com/16551165/188965398-015fe0a5-d631-4cd0-842c-b149588c56f6.gif)

**Comment by kmilo9999** [comment]
I activated Window's application verifier and now the crash points to:
```
void ImGui_ImplOpenGL3_DestroyFontsTexture()
{
    ImGuiIO& io = ImGui::GetIO();
    ImGui_ImplOpenGL3_Data* bd = ImGui_ImplOpenGL3_GetBackendData();
    if (bd->FontTexture)
    {
        glDeleteTextures(1, &bd->FontTexture);
        io.Fonts->SetTexID(0);     /// IT CRASHES HERE.
        bd->FontTexture = 0;
    }
}
```

Any thoughts ?
Thanks

**Comment by ocornut** [comment]
Please read if you can repro with example_glfw_opengl3/ first.

If you can’t, your application code is probably interfering with something and you’ll need to track that down (maybe by disabling chunks of your app).

**Comment by ocornut** [comment]
> If you can’t, your application code is probably interfering with something and you’ll need to track that down (maybe by disabling chunks of your app).

but first make sure you are doing exactly the same thing as example_glfw_opengl3.

**Comment by ocornut** [comment]
You most likely have a memory corruption or another bug in your app. 

Until you provide a repro within our example app (e.g. `example_glfw_opengl3`) it is difficult for us to help.
Please provide more information and we can easily reopen this issue and try to help.

**Comment by kmilo9999** [comment]
Yes, I finally tracked down the error. It was on my side of the app.
