### ISSUE TITLE
Docking does not work for the window that is set up with viewport's WorkPos and WorkSize

### ISSUE THREAD

**Issue by MichaelKv** [ocornut/imgui#5660]
Hello,
I use the latest docking branch. imgui.h reads the following:
// Version
// (Integer encoded as XYYZZ for use in #if preprocessor conditionals. Work in progress versions typically starts at XYY99 then bounce up to XYY00, XYY01 etc. when release tagging happens)
#define IMGUI_VERSION               "1.89 WIP"
#define IMGUI_VERSION_NUM           18814
#define IMGUI_CHECKVERSION()        ImGui::DebugCheckVersionAndDataLayout(IMGUI_VERSION, sizeof(ImGuiIO), sizeof(ImGuiStyle), sizeof(ImVec2), sizeof(ImVec4), sizeof(ImDrawVert), sizeof(ImDrawIdx))
#define IMGUI_HAS_TABLE
#define IMGUI_HAS_VIEWPORT          // Viewport WIP branch
#define IMGUI_HAS_DOCK              // Docking WIP branch

On Windows 2016 Server, Visual Studio 2022, I build 64-bit directx12 Imgui demo application.
Let us make ImGui::ShowDemoWindow to fill native window completely the following way (I have just changed the existing lines):
    ImGui::SetNextWindowPos(main_viewport->WorkPos); // AAAA
    ImGui::SetNextWindowSize(main_viewport->WorkSize);
Let us try to dock another sample window (I use Console example) to this main demo window. It will not work. If we comment AAAA line then docking begins working but main demo window leaves the native OS window.
Is there a way to provide the docking functionality of the window that fills the native OS window completely?
Thanks.

**Comment by PathogenDavid** [comment]
This is happening because moving a window implicitly undocks it.

> Is there a way to provide the docking functionality of the window that fills the native OS window completely?

Use `ImGui::DockSpaceOverViewport` to create a dockspace over the main viewport and `ImGui::SetNextWindowDockID` to lock your window into that dockspace. IE:

```cpp
// Make sure you call `DockSpaceOverViewport` before submitting *any* windows.
// Ideally just call it immediately following `ImGui::NewFrame`
ImGuiID dockspace = ImGui::DockSpaceOverViewport();

ImGui::SetNextWindowDockID(dockspace);
ImGui::Begin("Hello, world!");
ImGui::Text("This is some useful text.");
ImGui::End();
```

-----------

As an aside, you really should not use the demo window to test the `SetNextWindow***` functions since internally `ShowDemoWindow` submits multiple windows (the "Dear ImGui Demo" window is actually the last one it submits.)

**Comment by MichaelKv** [comment]
> Use ImGui::DockSpaceOverViewport to create a dockspace over the main viewport and ImGui::SetNextWindowDockID to lock your window into that dockspace. 

This was definitely not a defect but the “how to” question and your answer is just perfect. Thank you. I will try to close the issue.
> // Make sure you call `DockSpaceOverViewport` before submitting *any* windows.
// Ideally just call it immediately following `ImGui::NewFrame`

I begin to think I will need to write a window manager to guarantee this in the future. I will no doubt forget about it and may reorganize the code.
