### ISSUE TITLE
Detect mouse wheel scroll in current frame

### ISSUE THREAD

**Issue by UnrealKaraulov** [ocornut/imgui#5666]
ImGui version: https://github.com/ocornut/imgui/commit/3e6f948851ba657ea87dd1a36886bee0ef12d8b1 + glfw3
OS : Windows 10 x64

```
ImGuiWindow* window = ImGui::GetCurrentWindow();
ImGuiID active_id = ImGui::GetActiveID();
bool any_scrollbar_active = active_id && (active_id == ImGui::GetWindowScrollbarID(window, ImGuiAxis_X) || active_id == ImGui::GetWindowScrollbarID(window, ImGuiAxis_Y));
```

from https://github.com/ocornut/imgui/issues/1185#issuecomment-472386476 is works, but in my case, i need also detect **mouse whell scroll**.

How to do it, need something like` ImGui::IsMouseWheelActive()`? 
(It needed for save scroll position for all similar windows, example below)

```c++
if (any_scrollbar_active/* || any_mousewheel_scroll_active*/)
{
  scroll_x = ImGui::GetScrollX();
  scroll_y = ImGui::GetScrollY();
}
else
{
  ImGui::SetScrollX(scroll_x);
  ImGui::SetScrollY(scroll_y);
}
```

**Comment by ocornut** [comment]
> Detect mouse wheel scroll in current frame

Why do you need to do that?

**Comment by UnrealKaraulov** [comment]
@ocornut You can see full code here https://github.com/UnrealKaraulov/UnrealMapDrawTool/blob/fe39ee557224edce8bc29ad38e47b8c04787e825/main.cpp#L837

I need save scroll position from one window, and pass it to any other window in next frame if this window activated.

**Comment by ocornut** [comment]
> I need save scroll position from one window, and pass it to any other window

Then just read scroll value every frame and pass it to other window.

You don't need to care whether scrollbar or mouse wheel is active.
Scroll can be triggered with code, gamepad, keyboard and many other things.
