### ISSUE TITLE
ImGui::Text("%") does not render percent sign

### ISSUE THREAD

**Issue by anotherzooanimal** [ocornut/imgui#567]
In post  "Unable to render character symbols #565 ", I have resolved how to display symbols and special characters in ImGui, and so far this works great.  However one character seems to be plaguing me with issues being the percent sign.

All attempts to render this character has been unsuccessful so far.  From the previous post, I noticed that @ocornut went the to following website to establish the hex value for the character.

http://www.fileformat.info/info/unicode/char/0025/index.htm
and established that the % sign should be 
UTF-8 (hex) 	0x25 (25)

So I've tried the following and for some reason I get nothing in return:
ImGui::Text("\x25");

I've also tried:
ImGui::Text("%");
ImGui::Text("%%");
ImGui::Text("\u0025");

All with similar results.

The font that I'm using is Arial:

static const ImWchar ranges[] =
{
	0x0020, 0x00FF, // Note: 0025 should be captured within here.
	0,
}; 

arial16 = io.Fonts->AddFontFromFileTTF("C:\\windows\\fonts\\arial.ttf", 16.0f, &config, ranges);

The best workaround that I could find is using the Arabic percent sign:
http://www.fileformat.info/info/unicode/char/066a/index.htm

ImGui::Text("\xD9\xAA");

This one worked but it's not the same.  Any help would be appreciated on getting a normal percent sign to display.

**Comment by ocornut** [comment]
All functions taking format+ellipsis or format+va_arg are using printf-style formatting.

To output a single % you want Text("%%"); which you say you have tried but you must have overlooked the result.
You can also use TextUnformatted("%");
