### ISSUE TITLE
Runtime Font

### ISSUE THREAD

**Issue by ypujante** [ocornut/imgui#5673]
After doing much research, I understood that in order to load a font at runtime, I must do it before the call to `ImGui::NewFrame()` which is what I do.

I simplified the code to not even load a font (commented out) and this is what gets executed:

```cpp
    auto &io = ImGui::GetIO();
    io.Fonts->Clear();
    io.Fonts->AddFontDefault();
    // io.Fonts->AddFontFromFileTTF("/Library/Fonts/Andale Mono.ttf", 13.0f);
    io.Fonts->Build();
    return;
```

When I execute this code (after setting a flag when pushing a button so that it gets executed **before** `ImGui::NewFrame()`) the display gets completely garbled, as seen in the screenshot:

![imgui-runtimefont](https://user-images.githubusercontent.com/357116/189493718-69618c6d-db7d-49c1-85b3-c25fe43bcef8.gif)

Note that if I move this code entirely at the beginning of my program, then I can load the font fine...

Am I using the API improperly? Is this a bug?

```
Dear ImGui 1.88 (18800)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __APPLE__
define: __GNUC__=4
define: __clang_version__=11.0.0 (clang-1100.0.33.17)
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_metal
io.ConfigFlags: 0x00000000
io.ConfigMacOSXBehaviors
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMoveFromTitleBarOnly
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 2.00,2.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Comment by PathogenDavid** [comment]
You also need to tell the backend to reload the font texture by calling `ImGui_ImplMetal_DestroyFontsTexture` and `ImGui_ImplMetal_CreateFontsTexture`. (What you're seeing is the new font atlas coordinates being used with the old font texture.)

(You can also actually skip the call to `ImFontAtlas::Build`, it'll happen automatically in `ImGui_ImplMetal_CreateFontsTexture`.)

**Comment by ypujante** [comment]
Thank you. This did the trick! I am just wondering if I missed it in the documentation...

**Comment by ocornut** [comment]
We are working on standardizing this via #3761 so eventually it’ll be automatic.
