### ISSUE TITLE
Keyboard input being passed back to game but mouse is captured by imgui window

### ISSUE THREAD

**Issue by Arefu** [ocornut/imgui#5674]
**Version/Branch of Dear ImGui:**

Version: 1.89
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-ends: Win32, DirectX11
Compiler: VS2022 v143 Windows SDK 10
Operating System: Windows 11,

**My Issue/Question:**
My window appears to capture the mouse fine, but passes keyboard inputs back through to the original application, I do not want this, and I can't work out why this is happening.

```
LRESULT YuGiOh_ImGui::Hooked_YuGiOhImGuiWndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
	switch (uMsg)
	{
	case WM_KEYUP:
		switch (wParam)
		{
		case VK_HOME:
			*(long long*)0x14332A391 = 1;
			break;
		case VK_F2:
			YuGiOh_ImGui::g_ShowMenu = !YuGiOh_ImGui::g_ShowMenu;
			break;
		case VK_OEM_3:
			YuGiOh_ImGui::g_ConsoleOpen = !YuGiOh_ImGui::g_ConsoleOpen;
			break;
		default:
			break;
		}
		break;
	default:
		break;
	}

	if (YuGiOh_ImGui::g_ShowMenu || YuGiOh_ImGui::g_ConsoleOpen)
	{
		ImGui_ImplWin32_WndProcHandler(hWnd, uMsg, wParam, lParam);
		return true;
	}
	else
	{
		CallWindowProc(YuGiOh_ImGui::_WndProcHandler, hWnd, uMsg, wParam, lParam);
		return true;
	}
}
```

I have hooked the WndProc and this is being called correctly, I just can't work out why they keyboard is the only thing being passed back to the game. Mouse is fine, I can interact with the demo window, and input text, but when I type the keys also go back to the game when I don't want them to, I've tried reading from GetIO for wanting Keyboard capture, but I can't seem to make it work to hook and not pass back through.

any ideas?

**Comment by ocornut** [comment]
Maybe the game is reading raw keyboard inputs and not relying on WndProc. There are many possible answers to this, hard to guess and out of the scope of dear imgui of guessing how other software work.
