### ISSUE TITLE
Add Greek glyph range to ImFontAtlas

### ISSUE THREAD

**Issue by azonenberg** [ocornut/imgui#5676]
I'm working on an scientific computing application that makes fairly heavy use of Greek letters in the UI.

It would be convenient if ImFontAtlas had a GetGlyphRangesGreek() method so I didn't have to add every Greek letter to the atlas manually.

**Comment by ocornut** [comment]
Feel free to make a PR for it, thank you.

**Comment by azonenberg** [comment]
I don't have a fork handy that I can push to and have some other things to work on.

But the Greek and Coptic Unicode range is U+370 to U+3FF. Here's what I have in my code now.

```
for(wchar_t i=0x370; i<=0x3ff; i++)	//Greek and Coptic
	builder.AddChar(i);
```

**Comment by azonenberg** [comment]
I'm not sure as I don't actually speak the Greek language, I just use the letters in math :)

**Comment by azonenberg** [comment]
What about adding a GreekFull glyph range, similar to what you have with Chinese, that adds that range as well as the base one?

**Comment by ocornut** [comment]
Thanks for the PR. I think i'll merge as is for now, I prefer getting feedback on incomplete ranges.
(Anyhow hopefully those functions will eventually be gotten rid of..)

**Comment by ocornut** [comment]
FYI, on-going work on `dynamic_fonts` aimed for 1.92 (#8465) will make use of glyph range functions unnecessary, so GetGlyphRangesGreek() will eventually be removed once the work on dynamic_fonts is over.
