### ISSUE TITLE
Problem with OpenGL code using framebuffers

### ISSUE THREAD

**Issue by Rocketmagnet** [ocornut/imgui#5678]
**Version/Branch of Dear ImGui:**

Version: 1.88 WIP  (18722)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Visual Studio 2019
Operating System: Windows 10

**My Issue/Question:**

Summary: My OpenGL code which was working under wxWidgets does not seem to work when ported to Dear ImGui. It is a basic demo I wrote which implements a Bloom effect using framebuffers and shaders.

I can happily render some basic GL_QUADS into the ImGui window. I do this the old fashioned way, using glBegin(GL_QUADS); etc.

![image](https://user-images.githubusercontent.com/3330595/189764125-fcc04317-d1af-4aab-8e72-e4ea0f812bdb.png)

However, if I try to initialise the framebuffers needed for the Bloom effect, it causes the rendering to fail badly. The window contents rapidly alternates between this and a black window, and no ImGui controls are seen:

![image](https://user-images.githubusercontent.com/3330595/189764587-d84cdaac-8383-4883-90cf-d8f38f6750b2.png)

I am not using any of ImGui's own functions for creating framebuffers or images. Should I be using those instead. Would you expect there to be some difficulties porting some working OpenGL code into ImGui?

Unfortunately, I cannot easily paste a minimal example of the code which causes the problem, because I'm not exactly sure where the problem is happening. But I'm happy to offer a link to a .ZIP of my project (which isn't that big actually)

Many thanks in advance for any insight
Hugo

**Comment by nicolasnoble** [comment]
Rendering to a framebuffer should be working fine, and I'm heavily using it for my own project. You may just need to unbind the framebuffer after writing to it or even restoring the previously assigned one, like so:

```c++
GLuint oldFB;
glGetIntegerv(GL_DRAW_FRAMEBUFFER_BINDING, &oldFB);

glBindFramebuffer(GL_DRAW_FRAMEBUFFER, myFB);
[... issue draw call ...]

glBindFramebuffer(GL_DRAW_FRAMEBUFFER, oldFB);
```

**Comment by ocornut** [comment]
>  Would you expect there to be some difficulties porting some working OpenGL code into ImGui?

Expect some difficulties working with ANY sort OpenGL code :)
You can may to use a GPU debugger such as RenderDoc to debug state.

> Unfortunately, I cannot easily paste a minimal example of the code which causes the problem, because I'm not exactly sure where the problem is happening. 

This is exactly why we ask for a minimal example. It is an exercise that makes you narrow things down.

Generally speaking it is out of our scope to help people debug their OpenGL related issues so I need to close this.
However feel free to keep discussing it and perhaps post details/solutions if you find something. It's always good to leave more reference searchable.
