### ISSUE TITLE
Add IM_COLOR_CLASS_EXTRA for user Color classes?

### ISSUE THREAD

**Issue by EliasD** [ocornut/imgui#568]
Seeing as **IM_VEC2(4)_CLASS_EXTRA** is already a thing, it will be useful to be able to add constructor and operator() for **ImColor**. (Many libraries have their own color classes: **SDL** has **SDL_Color**, **SFML** has **sf::Color**, etc.)

**Comment by ocornut** [comment]
ImColor() isn't meant to be a stored thing, i should probably clarify that. It is just a helper to convert into either U32 ou ImVec4.
It needs rework as the color helpers are all over the place and messy :(

**Comment by EliasD** [comment]
Okay, thanks for the info. :)
I'll close the issue.
