### ISSUE TITLE
Alert/Confirmation Dialogs?

### ISSUE THREAD

**Issue by DomRe** [ocornut/imgui#5680]
Version: 1.88
Branch: master/docking

Back-ends: GLFW3 + OpenGL 4.6
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

Is there plans to support some simple pre defined popups that we could do in one line? Something similar to javascripts ```alert``` or ```confirm``` functions?

I.e.
```ImGui::Alert("Msg");```

```ImGui::Confirm("Msg", ok_func, cancel_func);```

or

```
if (ImGui::Confirm("Msg"))
{
    ...
}
```

**Comment by ocornut** [comment]
I think this would best be experimented with as a third-party library, until and if we nail down an API.

Rokas did one of such here:
https://github.com/rokups/imgui/commit/f0b38269ac9737846122db505e2e516c6fafc11c

One of the issue being that we don't yet have semantic to forward keyboard navigation events such as Enter/Escape into certain buttons, should work toward standardizing that too.

**Comment by DomRe** [comment]
Simple mockup I did.
```
void imgui_alert(const char* msg, bool* open) noexcept
{
	if (*open)
	{
		ImGui::OpenPopup(msg);
		imgui_center_next_window();

		*open = false;
	}

	if (ImGui::BeginPopup(msg))
	{
		ImGui::Text("Alert");

		ImGui::Separator();
		ImGui::Spacing();

		ImGui::Text(msg);

		ImGui::EndPopup();
	}
}

void imgui_confirm(const char* button, const char* popup, const std::function<void(void)>& yes, const std::function<void(void)>& no) noexcept
{
	if (ImGui::Button(button))
	{
		ImGui::OpenPopup(popup, ImGuiPopupFlags_NoOpenOverExistingPopup);
		imgui_center_next_window();
	}

	if (ImGui::BeginPopup(popup))
	{
		ImGui::Text("Are you sure you want to proceed?");
		ImGui::Spacing();

		if (ImGui::Button("Yes"))
		{
			if (yes)
			{
				yes();
			}

			ImGui::CloseCurrentPopup();
		}

		ImGui::SameLine();

		if (ImGui::Button("No"))
		{
			if (no)
			{
				no();
			}

			ImGui::CloseCurrentPopup();
		}

		ImGui::EndPopup();
	}
}

void imgui_center_next_window() noexcept
{
	static ImVec2 mid = {0.5f, 0.5f};

	const auto center = ImGui::GetMainViewport()->GetCenter();
	ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, mid);
}
```
