### ISSUE TITLE
ImGui changing color of text fields of OS

### ISSUE THREAD

**Issue by McAzz1337** [ocornut/imgui#5682]
**Version/Branch of Dear ImGui:

Version: 1.89
Branch: docking

Back-end/Renderer/Compiler/OS
Back-ends: x64, OpenGL (imgui_impl_opengl3.cpp + imgui_impl_glfw,cpp)
Compiler: Visual Studio 2022 (v143) Windows SDK 10.0
Operating System:  Windows 11

My Issue

I wrote some code to customize the look of ImGui and if I launch the application text fields and drop down menus etx. in my operating system change to the one i use in ImGui, I searched the Internet if someone else had the same problem, but didn't find anything. I don't know why this happens, because it didn't happen  before but then suddenly started happening. 

Screenshots

As you can see, the backgrounf color of the text field is dark gray when it should be white
<img width="283" alt="Screenshot imgui issue" src="https://user-images.githubusercontent.com/99556184/190285823-0d95d4e6-9c31-423d-bcc2-3085a2a35114.png">

Unfortunately I cannot provide any small example to reproduce the issue, since I wrote
some classes that handle the Imgui windows.
What i can provide is a link to the Git Hub repo of my project producing the issue:
https://github.com/McAzz1337/Architect/tree/feature

The code handling Imgui windows is located in: src/gfx/gui/gui_s.cpp

**Comment by ocornut** [comment]
The purpos of the small example is to narrow down your issue else you cannot investigate this.

It’s also extremely unlikely that dear imgui has anything to do with this. Please provide at least an uncut video showing before/after before you can engage in a making a repro.
