### ISSUE TITLE
Can't open a normal or modal popup inside a MenuBar + Menu inside it

### ISSUE THREAD

**Issue by memory-hunter** [ocornut/imgui#5684]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: cl.exe
Operating System: Windows 10

**My Issue/Question:**

I am having an issue when trying to make a modal popup inside a Menu bar and a Menu inside it.
I had trouble making a normal popup straight away in the Menu bar, but #331 was of help, so that's fine.
I utilized the same way of making the popup but inside a Menu this time, doesn't seem to work.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/59766692/190373099-e57a0141-ef62-4190-bf52-8f5e389fd4ca.png)
![image](https://user-images.githubusercontent.com/59766692/190373275-c8f053e6-c577-4d6d-a525-201a7ae8b306.png)

**Standalone, minimal, complete and verifiable example:**
```cpp
static bool popup_prompts[] = {false, false};
ImGui::Begin("drinkKahvi", nullptr,
                 ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize |
                 ImGuiWindowFlags_NoMove | ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoSavedSettings);
    if (ImGui::BeginMenuBar()) {
        if (ImGui::BeginMenu("Settings")) {
            components::directory_modal_handle(popup_prompts[0]);
            if (ImGui::BeginMenu("Theme")) {
                if (ImGui::MenuItem("Dark")) {
                    ImGui::StyleColorsDark();
                }
                if (ImGui::MenuItem("Light")) {
                    ImGui::StyleColorsLight();
                }
                ImGui::EndMenu();
            }
            ImGui::EndMenu();
        }
        components::about_popup_handle(popup_prompts[1]);
        if (ImGui::MenuItem("Exit")) {
            glfwSetWindowShouldClose(win, true);
        }
        ImGui::EndMenuBar();
    }
    ImGui::End();
```

I have taken out the popup code in an outside header in `inline` blocks of function

```cpp
inline void about_popup_handle(bool &open) {
        open = ImGui::MenuItem("About");
        if (open) {
            ImGui::OpenPopup("About");
            open = false;
        }
        ImGui::SetNextWindowPos(ImVec2(ImGui::GetIO().DisplaySize.x / 2, ImGui::GetIO().DisplaySize.y / 2),
                                ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
        if (ImGui::BeginPopup("About", ImGuiWindowFlags_AlwaysAutoResize)) {
            ImGui::Text("drinkKahvi");
            ImGui::Separator();
            ImGui::Text("A simple KahviBreak entry exporter to .zip for curations");
            ImGui::Text("Made by: memoryhunter");
            ImGui::EndPopup();
        }
    }

    inline void directory_modal_handle(bool &open) {
        open = ImGui::MenuItem("KahviBreak directory");
        if (open) {
            ImGui::OpenPopup("KahviBreak directory");
            open = false;
        }
        ImGui::SetNextWindowPos(ImVec2(ImGui::GetIO().DisplaySize.x / 2, ImGui::GetIO().DisplaySize.y / 2),
                                ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
        if (ImGui::BeginPopup("KahviBreak directory", ImGuiWindowFlags_AlwaysAutoResize)) {
            ImGui::Text("KahviBreak directory");
            ImGui::Separator();
            ImGui::Text("Please select the KahviBreak directory:");
            std::string directory{};
            ImGui::InputText("##KahviBreak directory", &directory);
            ImGui::EndPopup();
        }
    }
```

**Comment by PathogenDavid** [comment]
The issue is that you're submitting the popup within the scope of the if statement for `ImGui::BeginMenu("Settings")`: As soon as the menu closes when you click the button, `BeginMenu` no longer returns true so your code for submitting the popup is no longer being executed.

Unfortunately this isn't as simple as moving your `BeginPopup`..`EndPopup` outside of the menu because `OpenPopup(const char*)` opens a popup in the current [ID stack scope](https://github.com/ocornut/imgui/blob/8731cc2914a4c08f555bf70d93b54658d5d942ce/docs/FAQ.md#q-about-the-id-stack-system), and `BeginMenu` creates a new ID stack scope.

You can either use the `OpenPopup(ImGuiID)` overload instead (which uses an explicit unscoped ID) or you can keep track of the open state yourself and manually open it before you call `BeginPopup`. (For more detailed examples, see the last section of my comment here: https://github.com/ocornut/imgui/issues/5468#issuecomment-1184017711 starting with "However an issue you're likely to run into".)

**Comment by memory-hunter** [comment]
> The issue is that you're submitting the popup within the scope of the if statement for `ImGui::BeginMenu("Settings")`: As soon as the menu closes when you click the button, `BeginMenu` no longer returns true so your code for submitting the popup is no longer being executed.
> 
> Unfortunately this isn't as simple as moving your `BeginPopup`..`EndPopup` outside of the menu because `OpenPopup(const char*)` opens a popup in the current [ID stack scope](https://github.com/ocornut/imgui/blob/8731cc2914a4c08f555bf70d93b54658d5d942ce/docs/FAQ.md#q-about-the-id-stack-system), and `BeginMenu` creates a new ID stack scope.
> 
> You can either use the `OpenPopup(ImGuiID)` overload instead (which uses an explicit unscoped ID) or you can keep track of the open state yourself and manually open it before you call `BeginPopup`. (For more detailed examples, see the last section of my comment here: [#5468 (comment)](https://github.com/ocornut/imgui/issues/5468#issuecomment-1184017711) starting with "However an issue you're likely to run into".)

Thank you a lot for the reply. Got it working. So, now I know to handle the popups outside the `Begin()`

Solution for others to look:
```cpp
if (ImGui::BeginMenuBar()) {
        if (ImGui::BeginMenu("Settings")) {
            if (ImGui::MenuItem("KahviBreak directory")) {
                popups.kahvi_dir_popup = true;
            }
            if (ImGui::BeginMenu("Theme")) {
                if (ImGui::MenuItem("Dark")) {
                    ImGui::StyleColorsDark();
                }
                if (ImGui::MenuItem("Light")) {
                    ImGui::StyleColorsLight();
                }
                ImGui::EndMenu();
            }
            ImGui::EndMenu();
        }
        if (ImGui::MenuItem("About")) {
            popups.about_popup = true;
        }
        if (ImGui::MenuItem("Exit")) {
            glfwSetWindowShouldClose(win, true);
        }
        ImGui::EndMenuBar();
    }
    ImGui::End();
    if (popups.about_popup) {
        ImGui::OpenPopup("About");
    }
    components::about_popup_handle();
    if (popups.kahvi_dir_popup) {
        ImGui::OpenPopup("KahviBreak directory");
    }
    components::directory_modal_handle();
    ImGui::ShowDemoWindow();
```
