### ISSUE TITLE
example_glfw_opengl3 viewports crashed with NULL vd->Window

### ISSUE THREAD

**Issue by sweihub** [ocornut/imgui#5687]
Dear Imgui

Refer to #1542
I'm playing with the magical Viewports, but it crashed with a NULL window pointer, see the screenshots.

**Reproduce**
1. Clone the code from https://github.com/sweihub/photon
2. Open and build the project on Windows with VS2017, otherwise, you may need to `retarget projects`
3. Remove `imgui.ini` if any, debug and run
4. Click `Demo Candlestick`
5. Drag the window `Demo Candlestick` out of the main window, in order to activate viewports
6. Resize the `Demo Candlestick` 
7. Crashed with NULL pointer

![image](https://user-images.githubusercontent.com/5334841/190549193-b103c738-cb64-47ca-9418-3ac45e97f4cc.png)

![image](https://user-images.githubusercontent.com/5334841/190541602-92081e87-67e0-404d-8ef5-96ad475183e0.png)

**Comment by ocornut** [comment]
Hello,
I cannot seem to repro.
What are the values passed to the failing `glfwCreateWindow()` call ?

**Comment by sweihub** [comment]
Hi @ocornut 

I updated the GLFW library to lib-vc2017, but the problem remains the same, I can reproduce on my Windows 11, but it works fine on my Macbook.

I will try to debug as I can, but I am still not familiar with the GLFW stuff, I have noticed a abnormal situation, the `DestroyPlatformWindow()` called frequently inside `void ImGui::UpdatePlatformWindows()`, that means the viewport (idx = 1) was destroyed 60 times in a second, why should we do this?

![image](https://user-images.githubusercontent.com/5334841/190956056-378934f6-2562-4d66-a99b-c4e8ef3688c3.png)

**Comment by sweihub** [comment]
Hi @ocornut 

I updated the GLFW to v3.8, and corresponding library to lib-vs2017, the problem remains the same, I can reproduce it on my Windows 11, but it works on my Macbook. I will try to debug, but I am not familiar with GLFW.

Please check the screenshots, the `ImGui_ImplGlfw_CreateWindow` was called but immediately crashed with vd->Windows NULLpointer.

![image](https://user-images.githubusercontent.com/5334841/190959980-cef03185-448b-45a6-8aff-ead08fbdaeae.png)

**The Call Stack**
![image](https://user-images.githubusercontent.com/5334841/190960132-f4127f32-07b0-410f-a155-d1a7b49725c2.png)

**void ImGui::UpdatePlatformWindows()**
![image](https://user-images.githubusercontent.com/5334841/190960635-bb6aa0d3-05bd-42e3-9089-148a53540bdf.png)

**Comment by sweihub** [comment]
Hi @ocornut 

The code is complete, I did not missing anything, GLFW error message for your reference

```cpp
static void glfw_error_callback(int error, const char* description)
{
	fpintf(stderr, "Glfw Error %d: %s\n", error, description);
}
```
Output
`
Glfw Error 65543: WGL: Failed to create OpenGL context
`

Shoud it be video card driver issue?

**Comment by sweihub** [comment]
Hi @ocornut 

The code is complete, I did not missing anything, GLFW error message for your reference

```cpp
static void glfw_error_callback(int error, const char* description)
{
	fpintf(stderr, "Glfw Error %d: %s\n", error, description);
}
```
Output
`
Glfw Error 65543: WGL: Failed to create OpenGL context
`

Shoud it be video card driver issue?

**Comment by sweihub** [comment]
Hi @ocornut 

I tested `example_win32_directx11` on my Windows 11, which solved the issue,  apparently either driver or GLFW is buggy on Windows. So I have to go with direct11 for Windows, GLFW for mac.

I wil close the issue, the thread hopefully will solve the same issue for potentianl users.

**Comment by mwindowshz** [comment]
I have also this problem on different line
file: imgui_impl_glfw.cpp
function: ImGui_ImplGlfw_CreateWindow

glfwCreateWindow fails
Glfw Error 65546: The specified window has no context.7822

Also when I drag the window out side of the main window. sometimes even inside the window.
![image](https://user-images.githubusercontent.com/17617515/191761622-10609a8b-4055-4d9d-a8da-5606cf447956.png)
