### ISSUE TITLE
Custom Escape key handling in Input functions

### ISSUE THREAD

**Issue by s9w** [ocornut/imgui#5688]
**Version/Branch of Dear ImGui:**

Version: v1.88
Branch: master

**My Issue/Question:**

In any input widget, pressing the escape key currently has a hard-wired behavior: It removes the last-added portion of the text. It's debatable if that behavior is correct - other programs usually delete the entire input. However the greater problem is that this behavior can neither be changed nor disabled. It's not altered by `ImGuiWindowFlags_NoNavInputs` for example, but rather fixed behavior [in imgui_widgets.cpp](https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp#L4331).

This makes it impracticable to use the escape key for more advanced logic. For example I was planning to delete the current selected input if it's not empty, and go back to a menu window otherwise. But this collides with imgui's own logic that clears an input field - but only if it's the *first* input - a nightmare to reverse-engineer and couteract.

I would welcome any way to mitigate this - could be hiding this behind a flag or whatever.

**Comment by ocornut** [comment]
I am currently working on a larger feature which will allow this.

**Comment by ocornut** [comment]
> I am currently working on a larger feature which will allow this.

While I'm working on a generic system for routing and owning keys and shortcut, I also realize the behavior your mention is fairly common, so I also added it as a dedicated flag: `ImGuiInputTextFlags_EscapeClearsAll`. It clears inputs if not empty otherwise deactivate the widget.

**Comment by s9w** [comment]
Hey that solves my use case, thanks a lot!
