### ISSUE TITLE
 How to make Dear ImGui running in a thread

### ISSUE THREAD

**Issue by edenauditore** [ocornut/imgui#5696]
Version: 1.89 WIP
Branch: docking

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl2.cpp
Compiler: qmake linux-g++
Operating System: Ubuntu 16.04 LTS

I'd like to integrate IMGUI into my program to visualize some data in it. To achieve it, I tried to init and run IMGUI in a standalone thread other than in the main function (the reason is that if I run IMGUI in the main function it would block the rest code of main funtion).

I creat a IMGUI function according to the example, and creat a thread in my main function to run this function. However, when I compile the program, compiler shows the error: `no type named 'type' in 'class std::result_of<int()>'`. It seems that I need to pass some parameter to IMGUI function, but I didn't require any parameter when I define this function.

I'd like to know how to make IMGUI runing in a thread correctly, thank you!

The IMGUI function I modified according to the example is as below:
```c++
static int GuiPlotMain()
{

    GLFWwindow* window = glfwCreateWindow(1280, 720, "Plan Control Info", NULL, NULL);

    glfwMakeContextCurrent(window);
    glfwSwapInterval(0); // Enable vsync

    // Setup Dear ImGui context
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;       // Enable Keyboard Controls
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;           // Enable Docking
    io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;         // Enable Multi-Viewport / Platform Windows

    // Setup Dear ImGui style
    ImGui::StyleColorsDark();
    //ImGui::StyleColorsLight();

    // When viewports are enabled we tweak WindowRounding/WindowBg so platform windows can look identical to regular ones.
    ImGuiStyle& style = ImGui::GetStyle();
    if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
    {
        style.WindowRounding = 0.5f;
        style.Colors[ImGuiCol_WindowBg].w = 1.0f;
    }

    // Setup Platform/Renderer backends
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL2_Init();

    // Our state
    ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);

    // Main loop
    while (!glfwWindowShouldClose(window))
    {
        glfwPollEvents();
        // Start the Dear ImGui frame
        ImGui_ImplOpenGL2_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();

        // My code has not been filled yet

        // Rendering
        ImGui::Render();
        int display_w, display_h;
        glfwGetFramebufferSize(window, &display_w, &display_h);
        glViewport(0, 0, display_w, display_h);
        glClearColor(clear_color.x * clear_color.w, clear_color.y * clear_color.w, clear_color.z * clear_color.w, clear_color.w);
        glClear(GL_COLOR_BUFFER_BIT);

        ImGui_ImplOpenGL2_RenderDrawData(ImGui::GetDrawData());

        // Update and Render additional Platform Windows
        if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
        {
            GLFWwindow* backup_current_context = glfwGetCurrentContext();
            ImGui::UpdatePlatformWindows();
            ImGui::RenderPlatformWindowsDefault();
            glfwMakeContextCurrent(backup_current_context);
        }

        glfwSwapBuffers(window);
    }

    // Cleanup
    ImGui_ImplOpenGL2_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();

    glfwDestroyWindow(window);
    glfwTerminate();
}
```

I created the thread in my main function as blow:
```c++
    std::thread PlotThread(GuiPlotMain());
    PlotThread.detach();
```

**Comment by ocornut** [comment]
> (the reason is that if I run IMGUI in the main function it would block the rest code of main funtion).

Let me question that as I don't understand it. The design of Dear ImGui if that UI code runs every frame/iteration of your application and it should only take a negligible amount of it (or up to a few milliseconds for large interfaces). Dear ImGui is not blocking in any way.

> no type named 'type' in 'class std::result_of<int()>'. It seems that I need to pass some parameter to IMGUI function, but I didn't require any parameter when I define this function.

The question as worded seems to have nothing to do with Dear ImGui so it'd be difficult for us to help you. 

Note that Dear ImGui is NOT thread-safe, however your question is to run the entirety of your Dear ImGui stuff in a different thread, that's fine and has no incidence on Dear ImGui itself. Your problem seems more about using C++ threading API.

**Comment by edenauditore** [comment]
Sorry I didn't make myself clear, what I was trying to do is Integrating the whole Dear ImGui into one function or a thread just like below
```c++
int main()
{
    myfunction1;
    DearImGui(); // or DearImGuiThread
    myfunction2;
}
```
But your answer has inspired me the new method which is Integrate the internal codes in the example's main function with codes in my main function, and put the rendering loop into my main loop. Finally it works, althought it's not my original ideas but it works anyway.

Really thank you for your quick reply and instructions!

**Comment by ocornut** [comment]
> Integrate the internal codes in the example's main function with codes in my main function, and put the rendering loop into my main loop.

Yes this is how you should do it.
