### ISSUE TITLE
Assert happening despite me not seeing any apparent reason why.

### ISSUE THREAD

**Issue by tricksurf** [ocornut/imgui#5705]
**Version/Branch of Dear ImGui:**

Version: v1.88
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Operating System: Windows 11

**My Issue/Question:**

This assert happens randomly and I can't figure out why. I don't use any custom fonts or anything so the way to fix the issue isn't immediately apparent to me. I only use the default font that Dear ImGui uses. This is my first time using ImGui so I'm not quite sure what the problem is. My menu renders fine and often times gets destroyed properly when I uninject my dll.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/30512384/192083483-41ff1afa-4e22-4543-a202-627dc550a438.png)

**Standalone, minimal, complete and verifiable example:**
Not exactly sure what code I could provide here to help get the root of the problem.

**Comment by ocornut** [comment]
> This assert happens randomly and I can't figure out why.
> Not exactly sure what code I could provide here to help get the root of the problem.

It's your job to narrow things down.
Please understand there's no such thing as "happens randomly" so there is a reason.

Right now I can't think of reasons other than:
- Using multiple atlas / fonts.
- You messing with those fields (intentionally or unintentionally: e.g. memory corruption).

Unfortunately we can't help without more information. If you can narrow things down or provide more information we can reopen this.
