### ISSUE TITLE
In the same ImGui context, can use  ImGui_RenderDrawData more than once in a rendering loop?

### ISSUE THREAD

**Issue by sudongg** [ocornut/imgui#5706]
I am integrating ImGui into my render tree.
When rendering I need to use RenderDrawData multiple times to draw different ui.

I try to call two RenderDrawData and it crashes.

After calling RenderDrawData for the first time, create a new ImGui::NewFrame(); 
and call RenderDrawData again, there is no error, two ImGui::Frames are successfully rendered。
but I can't input, am I doing something wrong? Or that ImGui doesn't allow it.

**Comment by PathogenDavid** [comment]
I think there might be a fundamental disconnect here between your expectations and how Dear ImGui is meant to work. Is there a reason you're not just submitting multiple windows?

**Comment by sudongg** [comment]
I just want to do multiple RenderDrawData, not necessarily ImGui::NewFrame().
but NewFrame is the method I found so far that can achieve multiple RenderDrawData, but can't input.

**Comment by PathogenDavid** [comment]
Sure, but why do you want to do that? That isn't how people normally use Dear ImGui.

This feels like an [XY problem](https://xyproblem.info/).

**Comment by sudongg** [comment]
My project already has its own gui (hereafter referred to as mygui), I just want to integrate ImGui into mygui.

example:
mygui draws a window, then I use ImGui to draw the content, I only call RenderDrawData after mygui draws a window to ensure that what ImGui draws is on top of the mygui draw window.

I've only been able to do this once so far, if I have multiple windows and they all have their own order, I'll need to call RenderDrawData multiple times to make sure the ui is rendered in the correct order.

**Comment by ocornut** [comment]
It's fine to call _RenderDrawData() multiple times.

You are not providing enough information to receive meaningful help. 
If you aren't reading the [Contributing Guidelines](https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md) carefully and fulfilling it I doubt anyone can help.

**Comment by sudongg** [comment]
Hi. @ocornut 

```
Yes.
It's fine to call _RenderDrawData() multiple times.
```
this is my code:

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();

    ImGui::NewFrame();
    ImGui::Begin("Hello, world!");
    ImGui::End();
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    ImGui::EndFrame();

    // Do Some things

    ImGui::NewFrame();
    ImGui::Begin("Hello, world! 2");
    ImGui::End();
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    ImGui::EndFrame();

Result: Rendering successfully, but unable to control input, why?

My title already states the same context and not multiple contexts, since I may be calling RenderDrawData a dozen times in one render, I don't want to build a dozen contexts in one render.

Please give correct answer based on my question, thanks

**Comment by ocornut** [comment]
It's fine to call _RenderDrawData() multiple times. Your question is not a problem with _RenderDrawData().

- It's not fine to use a same context for different contents.
- It's not fine to update a backend once and run two frames in same context etc.

> Since I may be calling RenderDrawData a dozen times in one render, I don't want to build a dozen contexts in one render.

Then exactly as stated, you cannot.

**Comment by sudongg** [comment]
@ocornut 
It turns out that _RenderDrawData() cannot be called multiple times in the same context, otherwise the input will not be possible.

solution:
I comment the EndFrame() in Render() and don't use EndFrame() , I will render correctly and can input.

I don't want to understand why multiple contexts are needed to be able to call _RenderDrawData() multiple times, since the same context is the premise of the problem.

If this is imgui's design, (a context can only call _RenderDrawData() once) then I can only modify the code manually.
