### ISSUE TITLE
imgui Disabled after mouse click callback

### ISSUE THREAD

**Issue by BigMac0599** [ocornut/imgui#5708]
Version: 1.88
Branch: Master _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: Visual Studios 2022
Operating System: Windows

**My Issue/Question:**

Hello, I am currently using imgui for a project for that draws a polygon and is able to move and rotate around the screen. A part of the project includes clicking on 4 points within the window, and then using these 4 points to control the direction of the shape. I am using the "glfwSetMouseButtonCallback" method to record the coordinates of each of these clicks. However, once this method is called, I can no longer use the imgui buttons. Even if I use an if statement and booleans, the method is continuously being called and it essentially renders the GUI useless and I need to be able to use it again after recording these 4 points. I am not sure if this is an imgui issue or gflw issue or if I don't understand what is going on, but any help would be appreciated!

![image](https://user-images.githubusercontent.com/70345141/192307426-0ade4b9d-0196-4a04-b105-411cf0b8cb1a.png)
![image](https://user-images.githubusercontent.com/70345141/192307582-7024a69b-6c03-406a-acea-a26c65c4a4d4.png)
![image](https://user-images.githubusercontent.com/70345141/192308137-b8e65b0e-0d4f-4b44-a980-9cebb2aa2c6e.png)

**Comment by BigMac0599** [comment]
Solved after finding another similar issue

**Comment by ocornut** [comment]
It’s best not to delete posts and contents in order to help others, just like you did get help. Now you’ve deleted your code sample so people are unable to grasp the context, and you mention finding a solution but not linking to it.

I would suggest not overriding GLFW callbacks for that purpose. You can use eg InvisibleButtom() + IsItemClicked(), IsItemActive() etc to do this kind of stuff while keeping your code portable. See demo>examples>custom rendering>canvas for one example of doing that.

**Comment by BigMac0599** [comment]
Hello, I apologize. It was late last night for me and I got a little paranoid about posting my code and did not think they were good screenshots and I was in a rush to get to bed. As stated, I do not really use GitHub much and did not think straight. My solution came from 
https://github.com/ocornut/imgui/issues/1759#issue-316130528, where this user was using the imgui mouse wheel but it got disabled when using glfwSetScrollCallback(window, scroll_callback). I took note of your solution and went to imgui_impl_glfw.cpp and found the corresponding mouse click function. ImGui_ImplGlfw_MouseButtonCallback(GLFWwindow* window, int button, int action, int mods). When I added this to my callback function, everything seemed to work. 

![image](https://user-images.githubusercontent.com/70345141/192306693-ba8f1791-8f20-4591-9849-6f026ed00a8d.png)

I will add back my snippets now. Apologies once again

**Comment by ocornut** [comment]
Thanks for the details.

Again as suggested for UI purpose it may simply use ImGui-style input polling (e.g. `IsMouseClicked()`).

Here's a simple case:
```cpp
static ImVec2 my_points[4];
static int my_points_defined_count = 0;

ImGui::Begin("Demo #5708");

ImVec2 canvas_pos = ImGui::GetCursorScreenPos();
ImVec2 canvas_size(512, 512);
ImGui::InvisibleButton("##canvas", canvas_size);

if (ImGui::IsItemClicked())
{
    ImVec2 mouse_pos = ImGui::GetMousePos();
    my_points[my_points_defined_count] = ImVec2(mouse_pos.x - canvas_pos.x, mouse_pos.y - canvas_pos.y);
    my_points_defined_count = (my_points_defined_count + 1) % 4;
}

// Draw polygon
ImDrawList* draw_list = ImGui::GetWindowDrawList();
draw_list->AddRectFilled(canvas_pos, ImVec2(canvas_pos.x + canvas_size.x, canvas_pos.y + canvas_size.y), IM_COL32(100, 100, 100, 255));
for (int segment_n = 0; segment_n < 4; segment_n++)
{
    ImVec2 p1 = ImVec2(canvas_pos.x + my_points[segment_n].x, canvas_pos.y + my_points[segment_n].y);
    ImVec2 p2 = ImVec2(canvas_pos.x + my_points[(segment_n + 1) % 4].x, canvas_pos.y + my_points[(segment_n + 1) % 4].y);
    draw_list->AddLine(p1, p2, IM_COL32(255, 0, 0, 255), 2.0f);
}

ImGui::End();
```
![image](https://user-images.githubusercontent.com/8225057/192311100-29e98787-10ed-42f9-a256-3d1c091f916d.png)

**Comment by BigMac0599** [comment]
Also, I am trying to look into what you posted to see if I should add the functions you specified like IsItemClicked() in case it might be better. I am having trouble finding the path demo>examples>custom rendering>canvas but did find imgui_demo.cpp. Is this the correct file?

**Comment by BigMac0599** [comment]
Ok as soon as I posted that, the screen refreshed and I saw your new comment. Lol

**Comment by ocornut** [comment]
![image](https://user-images.githubusercontent.com/8225057/192314502-e1bbfb93-f3e8-4da3-b98e-309fe52c56cd.png)

**Comment by toegobler** [comment]
how do i use dwMouseEnable?
