### ISSUE TITLE
Cannot input after multiple calls to RenderDrawData.

### ISSUE THREAD

**Issue by sudongg** [ocornut/imgui#5715]
According to the answer of #5706, it is possible to do multiple RenderDrawData.
Then I use the code below in the OpenGL3 example

```
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();

    ImGui::NewFrame();
    ImGui::Begin("Hello, world!");
    ImGui::End();
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    ImGui::EndFrame();

    // Do Some things

    ImGui::NewFrame();
    ImGui::Begin("Hello, world! 2");
    ImGui::End();
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    ImGui::EndFrame();
```

Two windows are drawn successfully! but can't input, what am I doing wrong?

**Comment by ocornut** [comment]
Please don't open a new issue, use existing issue.
If you reuse same context from the pov of imgui you have window appearing and disappearing. You should use multiple contexts.
