### ISSUE TITLE
Assertion error: Forgot to call End(); or Render(); at end even though I did...

### ISSUE THREAD

**Issue by PsychoCoffee** [ocornut/imgui#5716]
Hey guys, I wanted to create a pop up dialog that opens up whenever you want to exit the game, so it asks you if you want to save your progress or not.
The issue I have come across when doing it, is that it keeps giving me the assertion error that I did not call End(); or Render(); at end of it even though I did!

I am not sure if I should even be using Popups for this, or if there is a better way of doing it.

There isn't much for me to do to try to trouble shoot it, after all I am a beginner at this so I don't know any better way.
There also weren't many mentions of the issue on the internet which was also bad.

I did try to use/do:

1. Begin
2. BeginChild
(None of which worked, and gave me more errors)

**----- The function where I call / draw the main menu (Its a ImGui window with invisible BG, so only buttons are visible.)----**
``` void Graphics::drawMainMenu() {
	ImGui_ImplDX11_NewFrame();
	ImGui_ImplWin32_NewFrame();
	ImGui::NewFrame();
	ImGui::SetNextWindowSize(ImVec2(1000, 1000));
	ImGui::SetNextWindowPos(ImVec2(150, 310));
	ImGui::SetNextWindowFocus();
	if(ImGui::Begin("##title", NULL, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse)) {
		if (ImGui::Selectable("New Game", false, NULL, ImVec2(65, 15))) {
			newGame();
		}
		ImGui::NewLine();
		if (ImGui::Selectable("Load Game", false, NULL, ImVec2(65, 15))) {
			loadGame();
		}
		ImGui::NewLine();
		if (ImGui::Selectable("Options", false, NULL, ImVec2(65, 15))) {
			SettingsMenuMain(&show_settings_menu);
		}
		ImGui::NewLine();
		if (ImGui::Selectable("Quit", false, NULL, ImVec2(65, 15))) {
                         exitGame();
		}
	}
	ImGui::End();
	ImGui::Render();
	ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
	} ```

**--Function that draws the popup for the dialog--**

``` void Graphics::exitGame() {
	ImGui::BeginPopup("##title");
	ImGui::Text("Are you sure you want to exit the game without saving?");
	ImGui::EndPopup();
	ImGui::Render();
} ```

**Comment by ocornut** [comment]
```cpp
	ImGui::BeginPopup("##title");
	ImGui::Text("Are you sure you want to exit the game without saving?");
	ImGui::EndPopup();
```
(1) This is not how to use BeginPopup(), you should always check its return value and only call `EndPopup()` if it returns true. See comments and demo code.

Basically `End()` and `EndChild()` are the only (inconsistent) exception right now not needing to check return value.

(2) You shouldn't call `Render()` twice a frame.

**Comment by PsychoCoffee** [comment]
> ```c++
> 	ImGui::BeginPopup("##title");
> 	ImGui::Text("Are you sure you want to exit the game without saving?");
> 	ImGui::EndPopup();
> ```
> 
> (1) This is not how to use BeginPopup(), you should always check its return value and only call `EndPopup()` if it returns true. See comments and demo code.
> 
> Basically `End()` and `EndChild()` are the only (inconsistent) exception right now not needing to check return value.
> 
> (2) You shouldn't call `Render()` twice a frame.

Oh, thanks for the tip! It actually runs the first part, but the issue I keep getting is that it now says:
Expression: window->Flags & ImGuiWindowFlags_Popup

The error comes up only when I  click on the exit button.

I tried to put the flag ImGuiWindowFlags_Popup in the beginpopup function but it still didn't work.

**Comment by ocornut** [comment]
Those assertions are hints to what you are doing wrong. Read the comments each time you are getting an assertion.
Can't guess what you are doing wrong without a repro.

**Comment by PsychoCoffee** [comment]
So

**Comment by PsychoCoffee** [comment]
Sorry about that and for making this so long.
Anyway, I did get it to run, but nothing pops up.
I used the code from demo.cpp file, but it doesn't show up.
No errors at least!

```
void Graphics::exitGame() {
	if (ImGui::BeginPopupModal("##text", NULL, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse))
	{
		ImGui::Text("All those beautiful files will be deleted.\nThis operation cannot be undone!\n\n");
		ImGui::Separator();

		//static int unused_i = 0;
		//ImGui::Combo("Combo", &unused_i, "Delete\0Delete harder\0");

		static bool dont_ask_me_next_time = false;
		ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0, 0));
		ImGui::Checkbox("Don't ask me next time", &dont_ask_me_next_time);
		ImGui::PopStyleVar();

		if (ImGui::Button("OK", ImVec2(120, 0))) { ImGui::CloseCurrentPopup(); }
		ImGui::SetItemDefaultFocus();
		ImGui::SameLine();
		if (ImGui::Button("Cancel", ImVec2(120, 0))) { ImGui::CloseCurrentPopup(); }
		ImGui::EndPopup();
	}
}

void Graphics::drawMainMenu() {
	ImGui_ImplDX11_NewFrame();
	ImGui_ImplWin32_NewFrame();
	ImGui::NewFrame();
	ImGuiStyle& styleMenuMain = ImGui::GetStyle();
	drawMainMenuStyle();
	ImGui::SetNextWindowSize(ImVec2(1000, 1000));
	ImGui::SetNextWindowPos(ImVec2(150, 310));
	ImGui::SetNextWindowFocus();
	if(ImGui::Begin("##title", NULL, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse)) {
		if (ImGui::Selectable("New Game", false, NULL, ImVec2(65, 15))) {
			newGame();
		}
		ImGui::NewLine();
		if (ImGui::Selectable("Load Game", false, NULL, ImVec2(65, 15))) {
			loadGame();
		}
		ImGui::NewLine();
		if (ImGui::Selectable("Options", false, NULL, ImVec2(65, 15))) {
			SettingsMenuMain(&show_settings_menu);
		}
		ImGui::NewLine();
		if (ImGui::Selectable("Quit", false, NULL, ImVec2(65, 15))) {
			exitGame();
		}
	}
	ImGui::End();
	ImGui::Render();
	ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
	}
```

**Comment by ocornut** [comment]
```
if (ImGui::Selectable("Quit", false, NULL, ImVec2(65, 15))) {
			exitGame();
		}
```
This will only call the exit popup code ONCE when clicking on the selectable.

You should do something more like:
```
if (ImGui::Selectable("Quit", false, NULL, ImVec2(65, 15)))
     ImGui::OpenPopup("Exiting Game?");
if (ImGui::BeginPopup("Exiting Game?"))
{
    ..
}
```
