### ISSUE TITLE
Drawing a Rectangle in the Foreground displays artifacts when dragging outside of (+, +) X-Y regions

### ISSUE THREAD

**Issue by vjotchere** [ocornut/imgui#5718]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx12.cpp
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

Hello and huge thanks for creating and maintaining this codebase.

I'm attempting to implement a way to select items in a Table by dragging and highlighting the items in the table, similar to how you can drag and highlight to select items in a Windows Folder.

Currently I'm working on displaying the selection rectangle and I'm seeing strange artifacts when drawing a rectangle in the foreground when using GetForegroundDrawList()->AddRectFilled(). Note that the artifacts only appear when dragging in (-, -), (+, -), and (-, +) X-Y regions relative to the initial mouse click

**Screenshots/Video**

![DrawingRectangleInForeground](https://user-images.githubusercontent.com/43732572/192606236-4a5c1072-2c0f-45de-ab45-184b6ea9387a.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
static bool m_DrawSelectionRectangle = false;
static ImVec2 m_DrawSelectBeginCoordinate;
static ImVec2 m_EndCoordinate;
auto& io = ImGui::GetIO();

if (io.MouseDown[0]) {
    if (false == m_DrawSelectionRectangle) {
        m_DrawSelectionRectangle = true;
        m_DrawSelectBeginCoordinate = io.MousePos;
    }

    m_EndCoordinate = io.MousePos;
}

if (io.MouseReleased[0]) {
    m_DrawSelectionRectangle = false;
}

ImGui::GetForegroundDrawList()->AddRectFilled(m_DrawSelectBeginCoordinate, m_EndCoordinate, ImColor(255, 0, 0, 150), 2.0f); // Draw a line between the button and the mouse cursor
```

**Comment by ocornut** [comment]
PS: We don't attempt to "swap" in `AddRectFilled()` because some other functions requires clockwise-awareness anyway and it may be inconsistent to support things in some functions and not other.

**Comment by vjotchere** [comment]
Interesting, that makes sense and I think I have enough information to close this issue. Thank you!

For anyone following along in the future, this is a possible implementation.

```
if ((m_EndCoordinate.x - m_DrawSelectBeginCoordinate.x > 0) && (m_EndCoordinate.y - m_DrawSelectBeginCoordinate.y > 0)) {
    ImGui::GetForegroundDrawList()->AddRectFilled(m_DrawSelectBeginCoordinate, m_EndCoordinate, ImColor(255, 0, 0, 150), 2.0f);
}
else if ((m_EndCoordinate.x - m_DrawSelectBeginCoordinate.x > 0) && (m_EndCoordinate.y - m_DrawSelectBeginCoordinate.y < 0)) {
    // Calculate TopLeft/BottomRight coordinates... Mouse Position at TopRight coordinate
}
else if ((m_EndCoordinate.x - m_DrawSelectBeginCoordinate.x < 0) && (m_EndCoordinate.y - m_DrawSelectBeginCoordinate.y > 0)) {
    // Calculate TopLeft coordinate... Mouse Position at BottomRight coordinate
}
else if ((m_EndCoordinate.x - m_DrawSelectBeginCoordinate.x < 0) && (m_EndCoordinate.y - m_DrawSelectBeginCoordinate.y < 0)) {
    // Calculate BottomRight coordinate... Mouse Position at TopLeft coordinate
}
```

**Comment by ocornut** [comment]
Assuming you have min/max functions you can do:

```cpp
static inline ImVec2 ImMin(const ImVec2& lhs, const ImVec2& rhs) { return ImVec2(lhs.x < rhs.x ? lhs.x : rhs.x, lhs.y < rhs.y ? lhs.y : rhs.y); }
static inline ImVec2 ImMax(const ImVec2& lhs, const ImVec2& rhs) { return ImVec2(lhs.x >= rhs.x ? lhs.x : rhs.x, lhs.y >= rhs.y ? lhs.y : rhs.y); }

[...]

ImGui::GetForegroundDrawList()->AddRectFilled(
 ImMin(m_DrawSelectBeginCoordinate, m_EndCoordinate), 
 ImMax(m_DrawSelectBeginCoordinate, m_EndCoordinate), 
 ImColor(255, 0, 0, 150), 2.0f); // Draw a line between the button and the mouse cursor
```

**Comment by vjotchere** [comment]
Nice! Both achieve the desired effect but I'd assume your snippet is more optimal since it avoids branching 🙌
