### ISSUE TITLE
How to keep a window within viewport bounds while it is being dragged/resized?

### ISSUE THREAD

**Issue by aybe** [ocornut/imgui#5719]
**Config/Build Information:**

```
Dear ImGui 1.87 (18700)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: _WIN32
define: _WIN64
define: _MSC_VER=1930
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: NULL
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000000
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000008
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,256
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Visual Studio
Operating System: Windows 10

**My Issue/Question:**

Using IMGUI from within [Silk.NET](https://github.com/dotnet/Silk.NET),

I'm trying to solve a simple problem without much luck so far: keep the window in the viewport while it's being dragged.

The following snippet works, the window stays in viewport, but only once the mouse is released, while dragging the window you can still move it outside viewport.

I tried numerous things, SetWindowPos, SetNextWindowPos both outside ImGui.Begin but the window cannot be dragged anymore then.

There's also a flaw with this approach, if you try resize the window, it will expand beyond viewport although the lower right corner always stays visible which allows to somehow resize it down and recover it.

**Screenshots/Video**

![TestDI_iThjU57AM6](https://user-images.githubusercontent.com/1537591/192604227-4d1d4359-e2ba-4e80-a370-a056974d34f0.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

```
        if (ImGui.Begin("testing!"))
        {
            var xy = ImGui.GetWindowPos();
            var sz = ImGui.GetWindowSize();
            ImGui.Text("some text");
            ImGui.Text($"xy: {xy}");
            ImGui.Text($"sz: {sz}");
            var min = Vector2.Zero;
            var max = ImGui.GetMainViewport().Size - sz;
            var pos = Vector2.Clamp(xy, min, max);
            ImGui.SetWindowPos(pos);
        }

        ImGui.End();
```

**Comment by ocornut** [comment]
Linking to #2827 #4356. This is best discussed in #4356.

While not answering your issue as worded, please note two things may indirectly solve your problem:
- `io.ConfigWindowsMoveFromTitleBarOnly` enforce title bar being always visible.
- `style.DisplayWindowPadding` ensure at least that amount of windows are visible.

**Comment by aybe** [comment]
Alright, continuing the discussion over there, thank you.
