### ISSUE TITLE
Russian input in ImGuiInputText

### ISSUE THREAD

**Issue by or75** [ocornut/imgui#5725]
Fix in ImGui_ImplWin32_WndProcHandler:

![image](https://user-images.githubusercontent.com/5619678/192779165-3b18232c-e4a8-4bd8-a7fd-cacec30550ae.png)
![image](https://user-images.githubusercontent.com/5619678/192779292-bb52b0b2-ac67-4fa6-b888-015d2cd72f3f.png)
![image](https://user-images.githubusercontent.com/5619678/192779596-08c3171f-60eb-4d49-9311-eb9c451902ec.png)

without fix:
![image](https://user-images.githubusercontent.com/5619678/192779756-641a5b90-e4d2-471f-a3e3-0b0a93ac355e.png)
![image](https://user-images.githubusercontent.com/5619678/192779939-c6b2ff7e-898c-44c7-93f0-1e873405a1a0.png)

use arial windows font:
![image](https://user-images.githubusercontent.com/5619678/192780151-85340732-6b6f-4837-a572-a65c8b5db085.png)

???

**Comment by ocornut** [comment]
The result and need for fix may depends on whether the application was compiled in Unicode vs MB mode.

Could you try both modes, with and without the fix?

![image](https://user-images.githubusercontent.com/8225057/192785881-407b31cd-77c0-4789-9e7f-b26000a6df03.png)

**Comment by or75** [comment]
Use dll (MB same):

unicode without fix:
![image](https://user-images.githubusercontent.com/5619678/192789795-3bd1a720-e033-4678-95ee-5272cf063a8c.png)

unicode fix:
![image](https://user-images.githubusercontent.com/5619678/192790048-b2e1b99d-1261-488f-ac06-fbaa86ca1207.png)

**Comment by ocornut** [comment]
If I compile my application in Unicode I don't need your fix:

```cpp
io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\segoeui.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesCyrillic());
```
Pressing here:
![image](https://user-images.githubusercontent.com/8225057/192792567-c9b5d325-ef78-470a-9283-463238c31eb2.png)

I am getting:
![image](https://user-images.githubusercontent.com/8225057/192792633-e79544dd-236a-4b56-a774-d84bdc8be883.png)

So this only affect programs compiled in multi-byte mode.
Will investigate.

**Comment by or75** [comment]
without fix imgui 1.88 use dll (WTF):

![image](https://user-images.githubusercontent.com/5619678/192793784-cc072989-74e4-43e6-bc17-425ab9b79cb5.png)
![image](https://user-images.githubusercontent.com/5619678/192794085-f64fb24d-95f0-4a26-bd1b-2af16eb0cf62.png)

**Comment by or75** [comment]
use exe without fix (example_win32_directx9):

![image](https://user-images.githubusercontent.com/5619678/192794822-b5b3902e-8b14-436e-bfcd-da5f15f2e06e.png)

**Comment by ocornut** [comment]
I can't read your language so I don't know if your copy of imgui_impl_win32 is compiled in Unicode or MB mode.

Before fix:
```
imgui_impl_win32 unicode:   OK
imgui_impl_win32 mbcs: not OK
imgui_impl_glfw  unicode:   OK
imgui_impl_glfw  mbcs: OK
imgui_impl_sdl   unicode:   OK
imgui_impl_sdl   mbcs: OK
```
So it is indeed a bug in imgui_impl_win32 backend.

**~~But you should simply compile `imgui_impl_win32` with Unicode enabled perhaps?~~**
**You should register your window class using `RegisterClassW()` or compile the code calling it in Unicode mode and call `RegisterClass()`**.

Your fix breaks when compiled with Unicode.
So let's assuming we change it to
```cpp
    case WM_CHAR:
#ifdef _UNICODE
        // You can also use ToAscii()+GetKeyboardState() to retrieve characters.
        if (wParam > 0 && wParam < 0x10000)
            io.AddInputCharacterUTF16((unsigned short)wParam);
#else
        wchar_t wch;;
        ::MultiByteToWideChar(CP_ACP, MB_PRECOMPOSED, (char*)&wParam, 1, &wch, 1);
        io.AddInputCharacter(wch);
#endif
        return 0;
```

I have two issues:
- I don't know if your conversion is correct in all systems and cases/locals. In fact, it is NOT correct on my system right now.
- I don't well understand use of surrogate (added by #2541 #2815)

Looking at GLFW/SDL etc things are confusing.
- There is a WM_IME_CHAR message.
- There is a WM_UNICHAR message.
- Also notice #3653 (uses WM_IME_CHAR).

SDL does:
```cpp
    case WM_UNICHAR:
        if (wParam == UNICODE_NOCHAR) {
            returnCode = 1;
        } else {
            char text[5];
            if (WIN_ConvertUTF32toUTF8((UINT32)wParam, text)) {
                SDL_SendKeyboardText(text);
            }
            returnCode = 0;
        }
        break;

    case WM_CHAR:
        /* When a user enters a Unicode code point defined in the Basic Multilingual Plane, Windows sends a WM_CHAR
           message with the code point encoded as UTF-16. When a user enters a Unicode code point from a Supplementary
           Plane, Windows sends the code point in two separate WM_CHAR messages: The first message includes the UTF-16
           High Surrogate and the second the UTF-16 Low Surrogate. The High and Low Surrogates cannot be individually
           converted to valid UTF-8, therefore, we must save the High Surrogate from the first WM_CHAR message and
           concatenate it with the Low Surrogate from the second WM_CHAR message. At that point, we have a valid
           UTF-16 surrogate pair ready to re-encode as UTF-8. */
        if (IS_HIGH_SURROGATE(wParam)) {
            data->high_surrogate = (WCHAR)wParam;
        } else if (IS_SURROGATE_PAIR(data->high_surrogate, wParam)) {
            /* The code point is in a Supplementary Plane.
               Here wParam is the Low Surrogate. */
            char text[5];
            if (WIN_ConvertUTF16toUTF8((UINT32)data->high_surrogate, (UINT32)wParam, text)) {
                SDL_SendKeyboardText(text);
            }
            data->high_surrogate = 0;
        } else {
            /* The code point is in the Basic Multilingual Plane.
               It's numerically equal to UTF-32. */
            char text[5];
            if (WIN_ConvertUTF32toUTF8((UINT32)wParam, text)) {
                SDL_SendKeyboardText(text);
            }
        }
        returnCode = 0;
        break;
```

GLFW does:
```
        case WM_CHAR:
        case WM_SYSCHAR:
        case WM_UNICHAR:
        {
            const GLFWbool plain = (uMsg != WM_SYSCHAR);

            if (uMsg == WM_UNICHAR && wParam == UNICODE_NOCHAR)
            {
                // WM_UNICHAR is not sent by Windows, but is sent by some
                // third-party input method engine
                // Returning TRUE here announces support for this message
                return TRUE;
            }

            _glfwInputChar(window, (unsigned int) wParam, getKeyMods(), plain);

            if (uMsg == WM_SYSCHAR && window->win32.keymenu)
                break;

            return 0;
        }
[...]
void _glfwInputChar(_GLFWwindow* window, unsigned int codepoint, int mods, GLFWbool plain)
{
    if (codepoint < 32 || (codepoint > 126 && codepoint < 160))
        return;

     [...] // Omitting Key Mods related code
    if (!window->lockKeyMods)
        mods &= ~(GLFW_MOD_CAPS_LOCK | GLFW_MOD_NUM_LOCK);
    if (plain)
    {
        if (window->callbacks.character)
            window->callbacks.character((GLFWwindow*) window, codepoint);
    }
}
```

Notes:
- (1) In both Unicode or MBCS compile mode, I can't seem to get WM_UNICHAR emitted.
- (2) GLFW doesn't seem to do any specific processing.

Given:
```
Unicode Character “ô” (U+00F4)
Unicode Character “ф” (U+0444)
```

Debugging our Win32+DX11 test app in MBCS mode:
- I get WM_CHAR with 0xF4
- Passing 0xF4 to `MultiByteToWideChar(CP_ACP, MB_PRECOMPOSED, ...)` returns 0xF4.

Debugging GLFW in MBCS mode:
- I get WM_CHAR with 0x0444

https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-char
> The WM_CHAR message uses UTF-16 (16-bit Unicode Transformation Format) code units in its wParam if the Unicode version of the [RegisterClass](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerclassw) function was used to register the window class.

GLFW calls `RegisterClassW()`. Our test application calls `RegisterClass()` which is redirected to `RegisterClassA()` or `RegisterClassW()`. SDL also enforces `_UNICODE` and therefore calls `RegisterClassW()` always.
So it's not something to do with `_UNICODE` define but with this registration.

Does this works for you?
```
case WM_CHAR:
    if (::IsWindowUnicode(hwnd))
    {
        // You can also use ToAscii()+GetKeyboardState() to retrieve characters.
        if (wParam > 0 && wParam < 0x10000)
            io.AddInputCharacterUTF16((unsigned short)wParam);
    }
    else
    {
        wchar_t wch = 0;
        ::MultiByteToWideChar(CP_ACP, MB_PRECOMPOSED, (char*)&wParam, 1, &wch, 1);
        io.AddInputCharacter(wch);
    }
    return 0;
```

I can't get it to work but presumably using `RegisterClassA()` means you depend on current system codepage.
I can commit this partial fix but you'd better call `RegisterClassW()`.


Благодарю вас!

**Comment by or75** [comment]
working, thanks
```
case WM_CHAR:
    if (::IsWindowUnicode(hwnd))
    {
        // You can also use ToAscii()+GetKeyboardState() to retrieve characters.
        if (wParam > 0 && wParam < 0x10000)
            io.AddInputCharacterUTF16((unsigned short)wParam);
    }
    else
    {
        wchar_t wch = 0;
        ::MultiByteToWideChar(CP_ACP, MB_PRECOMPOSED, (char*)&wParam, 1, &wch, 1);
        io.AddInputCharacter(wch);
    }
    return 0;
```

![image](https://user-images.githubusercontent.com/5619678/192812533-2fd01e5d-f226-49cb-b9e1-4a5b002423c8.png)

**Comment by ocornut** [comment]
Pushed a229a7f (make examples always use Unicode) + 0a7054c (fallback for your case).
