### ISSUE TITLE
Vulkan backend: Please support VK_EXT_debug_utils

### ISSUE THREAD

**Issue by azonenberg** [ocornut/imgui#5726]
It would be nice if the Vulkan backend made use of VK_EXT_debug_utils if available.

Among other things, this extension allows you to call vkSetDebugUtilsObjectNameEXT() to assign a human readable text name to a Vulkan handle. This will make it easier to identify imgui-related objects in a frame debugger or validation layer error messages.

**Comment by ocornut** [comment]
Hello,
A thorough pull request would be welcome.

**Comment by azonenberg** [comment]
I'll work on it when time permits. It might take me a while as I'm used to using the vulkan-hpp C++ wrapper layer not raw vkXXX function calls.

**Comment by ocornut** [comment]
I’ll close this for now. If someone makes a PR for it we’ll probably want to merge it.
