### ISSUE TITLE
Resize the main viewport every time when OS size callback/message is called

### ISSUE THREAD

**Issue by KennyProgrammer** [ocornut/imgui#5728]
Version/Branch of Dear ImGui:

Version: 1.88
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: opengl3, directx10/11, win32, glfw
Compiler: vc++
Operating System: windows
My Issue/Question:

How i can tell ImGui, that redraw the main viewport (viewports[0]) context every time when OS called its callback to resize the window?
For example for Win32 and DirectX11,  when WM_SIZE message called that means that window was change its size. So at this point i call my code for resizing the swap chan. And also later in my render code i also resize my main framebuffer, that attach to main ImGui viewport. Its works perfectly, but when im continue resizing without releasing the mouse button, content of main viewport turns black or weird, and ImGui apply property size on main viewport ONLY when i release the mouse button (stop resizing). 
![image](https://user-images.githubusercontent.com/56895345/192862127-1154fa04-51ba-4260-9f9b-434e3a1da4f3.png) 
![image](https://user-images.githubusercontent.com/56895345/192862187-0c1e8001-906c-438c-badc-94e0d88323c7.png)

But when im begin new platform window with ImGui for example Viewports[1] or Viewports[2] and resize the same way it works perfectly (i.e window and imgui window content resize dynamically every WM_SIZE). Any suggestion for main viewport?

**Comment by ocornut** [comment]
This is not a dear imgui issue but a win32 issue. Please search for the many reference to WM_SIZE, WM_TIMER etc.

**Comment by KennyProgrammer** [comment]
So im fixed this issue. You right that was Win32 problem. When `WM_SIZE `is sended and after application receive and send size to window we need to completely redraw the user main rendering scene, and also ImGui scene (i.e `ImGui::NewFrame() ImGui::BeginFrame(); ... ImGui::EndFrame()`) and then calls OS or graphics or user abstract `SwapBuffers/Present` from its window on Win32 thread. Because while we resizing Win32 grip/`WS_THICKFRAME`, Win32 block our main rendering loop (where user/imgui rendering happens) or main update loop (where deltaTime/timeStep is calculated).
