### ISSUE TITLE
Input fields do not keep focus when used in tables

### ISSUE THREAD

**Issue by danbrown3** [ocornut/imgui#5729]
**Version/Branch of Dear ImGui:**

Version: v1.85
Branch: Not sure

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp
Operating System: Windows

**My Issue/Question:**

When using inputs in a table (I tested with InputInt), the text field does not keep focus in between frames.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
const int numCols = 3;
static ImGuiTableFlags flags = ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg;
if (ImGui::BeginTable("TrackerTable", numCols, flags))
{
	ImGui::TableSetupColumn("Title", ImGuiTableColumnFlags_WidthFixed);
	ImGui::TableSetupColumn("Tracking Type", ImGuiTableColumnFlags_WidthFixed);
	ImGui::TableSetupColumn("Current Value", ImGuiTableColumnFlags_WidthFixed, 100);

	ImGui::TableHeadersRow();

	for (auto& myThing : m_myThings)
	{
		ImGui::TableNextRow();
		ImGui::TableNextColumn();

		//Title
		ImGui::Text("%s", myThing.title);
		ImGui::TableNextColumn();
		
		//Tracking Type
		ImGui::Text("Int");
		ImGui::TableNextColumn();

		//Current Value
		ImGui::InputInt("", &myThing.intVal);
		ImGui::TableNextColumn();
	}

	ImGui::EndTable();
}
```

**Comment by ocornut** [comment]
Read the FAQ
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

**Comment by danbrown3** [comment]
Well, there's nothing in that FAQ about text field focus, but I'm guessing you are trying to imply that the focus bug is caused by an ID clash. Would have appreciated something better than RTFM, but I'll give that a try and get back to you.

**Comment by danbrown3** [comment]
Yes, giving each input a custom ID does fix the problem.

**Comment by ocornut** [comment]
Generally speaking if you have a loop you’d want to use PushID(index) or another variant in your loop body, if you want the name to match.
