### ISSUE TITLE
Help with NavEnableGamepad and BeginMenu in Window (Not inside MainMenuBar)  

### ISSUE THREAD

**Issue by squirrelroad** [ocornut/imgui#5730]
```
Dear ImGui 1.89 WIP (18825)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201103
define: __APPLE__
define: __GNUC__=4
define: __clang_version__=12.0.5 (clang-1205.0.22.11)
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: imgui_impl_sdlrenderer
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigMacOSXBehaviors
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```
**Version/Branch of Dear ImGui:**

Version: v1.88
Branch: tag v1.88

**My Issue/Question:**

Hi,
I would like to build my cheat menu with BeginMenu inside Window. 
I am having trouble reaching MenuItem2 on the screenshot below using gamepad and keyboard.

Can you advice on how to solve this gamepad/keyboard navigation issue? Ideally I would like to use imgui solely on a gamepad (for console platforms)

Tested on Win64 as well.

Kind regards,

**Screenshots/Video**
![Screen](https://user-images.githubusercontent.com/349861/192903982-9f8f7917-c578-47ec-8c82-42e86b71496d.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

using example_sdl_sdlrenderer:
```
//
// ... ImGui::CreateContext();
// ... ImGuiIO& io = ImGui::GetIO(); (void)io;
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;     // Enable Keyboard Controls
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;      // Enable Gamepad Controls


/// ... ImGui::NewFrame();

        ImGui::Begin("MainMenu");
        if (ImGui::BeginMenu("Menu1"))
        {
            ImGui::MenuItem("MenuItem1");
            ImGui::EndMenu();
        }
        // ImGui::PushID("foo")
        if (ImGui::BeginMenu("Menu2"))
        {
            static float ff = 0.5;
            ImGui::SliderFloat("float1", &ff, 0.f, 1.f);
            ImGui::MenuItem("MenuItem2");
            ImGui::EndMenu();
        }
        // ImGui::PopID()
        if (ImGui::BeginMenu("Menu3"))
        {
            ImGui::MenuItem("MenuItem3");
            ImGui::EndMenu();
        }
        if (ImGui::BeginMenu("Menu4"))
        {
            ImGui::EndMenu();
        }
        ImGui::End();

```

**Comment by ocornut** [comment]
It appears like an issue with navigation code. 
More-over I am noticing that menus don't close properly which may be a recently introduced bug as well.

**Comment by ocornut** [comment]
Ought to clarify: we've been having issues with using menus **inside windows that are not menus themselves**, this is what causing your issue here.

**Comment by ocornut** [comment]
I've been working on a fix and while I'm there I'll try to clarify/fix a few oddities with keyboard/gamepad menu in root of menusets. Stay tuned.

**Comment by ocornut** [comment]
Done, Pushed a few fixes:
3532ed1
bd2355a
0749453

Issue as reported should be fixed. Also fixed being able to leave that menu with Left arrow.

Note that using mouse and keyboard/gamepad simultaneously in menu can still lead to a few odd navigation things, but they are unrelated issues.

**Comment by squirrelroad** [comment]
Thanks a lot! I'll try them out
