### ISSUE TITLE
DX12 resized window rendering incorrectly

### ISSUE THREAD

**Issue by EuropianSD** [ocornut/imgui#5732]
Dear ImGui 1.89 WIP (18825)

Version: 1.89
Branch: (master/docking)
Back-ends: imgui_impl_win32.cpp + imgui_impl_dx12.cpp
Operating System: Windows

**My Issue/Question:**

When using win32 and dx12, after resizing the window, the rendering/mouse position is offset and the only way I have found to fix it is to move the main window. The dx11 and openGL samples do not have this issue. Any suggestions on how to solve this?

Thanks.

**Screenshots/Video**

![ImguiDX12_3gif](https://user-images.githubusercontent.com/32756974/192942982-78d040dd-0560-464f-893d-f43803ac5cfd.gif)

**Standalone, minimal, complete and verifiable example:** 

This issue can be seen in the example_win32_directx12 sample with no code changes.

**Comment by ocornut** [comment]
> This issue can be seen in the example_win32_directx12 sample with no code changes.

I cannot seem to repro here unfortunately. May I suggest updating your GPU drivers and seeing if you have any odd third-party software installed?

It's hard to tell if this is coming from the platform backend (input offset in imgui_impl_win32) or rendering backend (render offset in imgui_impl_dx12). I would start by enabling `Tools->Debug Log`, check `IO` and look at the mouse values printed out. What do you get when you hover need the top-left of the viewport? (values should be near (0,0) assuming multi-viewports are disabled).

**Comment by ocornut** [comment]
If the mouse pos say ~(0,0) near top left while display is off, it suggests it's an issue on the rendering side (or rendering wasn't notified). It's honestly hard to guess/tell you would have to investigate.

**Comment by EuropianSD** [comment]
I think it is driver/graphics card related as another PC with a different graphics card did not have the same issue.
Thanks.
