### ISSUE TITLE
ImGui::Columns() and ImGuiWindowFlags_AlwaysAutoResize

### ISSUE THREAD

**Issue by Kiojeen** [ocornut/imgui#5733]
Hi, I am using `ImGui::Columns(`) and it looks that `ImGuiWindowFlags_AlwaysAutoResize` only resizes the window to the first column hiding the second one.
So I wonder if I am missing something or if there is a way around this.
Thanks.

my code looks like this..

```
if(ImGui::Begin(id, nullptr, 64))
{
	ImGui::Columns(2, "###clmn1", false);
	ImGui::SetColumnOffset(1, 115);
        // content
        ImGui::NextColumn();
        // content.
        ImGui::End();
}
```

**Comment by ocornut** [comment]
See #2142 #1363
Unfortunately Columns() is a legacy API which we don’t really plan to upgrade anymore, as Tables are the full features replacement to them. You should really use Tables.
