### ISSUE TITLE
Keeping ImGui responsive despite GPU intense tasks

### ISSUE THREAD

**Issue by thegabman** [ocornut/imgui#5734]
Hi, 
first of all I want to let you know that this is more of a question about usage / architecture than an issue.
I hope it is okay to leave it here anyway. If not, feel free to delete / close this Issue. Thank you!

**Question:**
I have some very GPU intense calculations taking up to 20 seconds.  What would be the best way of keeping ImGui responsive?
It would be even enough to just be able to show some kind of loading spinner.
I absolutely could split the one huge task into smaller tasks running just milliseconds and distribute it through multiple frames, but that would make the whole application way more complex regarding its architecture.
Right now it is implemented as a fragment shader because I am working on textures. But if the only way would be to switch to compute shaders, this would absolutely not be an issue. 

Thank You, 
Gabriel

**Comment by ocornut** [comment]
I suppose the most natural solution would be that your main/UI application thread shouldn’t be the one running lenghty or blocking tasks.

I am however unsure how your graphics API works and if you can get those shader work done in a separate thread.

**Comment by thegabman** [comment]
I am using bgfx to be flexible API and OS wise. I already thought about the approach you are suggesting. Right now I am using bgfx in single threaded mode. I think I could switch to multi threaded mode, but I have to look deeper into that topic. I don't know yet how GPU resources need to be handled than and if I could run shaders on a separate thread. 

Thank you for pointing me into that direction. I will have a look than :)

**Comment by ocornut** [comment]
I'll close this now but if you have any questions, thought or breakthrough feel free to post here!
