### ISSUE TITLE
Provide an API to free texture descritpors allocated by Vulkan backend

### ISSUE THREAD

**Issue by azonenberg** [ocornut/imgui#5738]
Right now, there is an ImGui_ImplXXX_AddTexture function, but there doesn't appear to be a corresponding function to free a texture you don't need anymore without making raw platform API calls (e.g. vkFreeDescriptorSets) yourself.

**Comment by ocornut** [comment]
The `ImGui_ImplVulkan_AddTexture()` function is a peculiarity of the Vulkan backend (see #914) and is already close to being a raw platform API call. 

Can you confirm that calling `vkFreeDescriptorSets(g_Device, g_DescriptorPool, 1, &descriptor_set);` would work and be enough here? We could potentially wrap it.

The function names are misleading and handling of ImTextureID for Vulkan may evolve.

**Comment by azonenberg** [comment]
Yes, this is how I do things in my code now. It just seems weird to have one end wrapped and not the other.

**Comment by ocornut** [comment]
Added a588f00
