### ISSUE TITLE
How to get hardware cursor to show something else than the arrow?

### ISSUE THREAD

**Issue by aybe** [ocornut/imgui#5739]
**Config/Build Information:**

```
Dear ImGui 1.87 (18700)
--------------------------------

sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: _WIN32
define: _WIN64
define: _MSC_VER=1930
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------

io.BackendPlatformName: NULL
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000000
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000A
 HasMouseCursors
 RendererHasVtxOffset
--------------------------------

io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,256
io.DisplaySize: 3840.00,2066.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------

style.WindowPadding: 12.00,12.00
style.WindowBorderSize: 1.00
style.FramePadding: 6.00,4.00
style.FrameRounding: 0.00
style.FrameBorderSize: 1.00
style.ItemSpacing: 12.00,6.00
style.ItemInnerSpacing: 6.00,6.00
```

**Version/Branch of Dear ImGui:**
Version: 1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Visual Studio
Operating System: Windows 10

**My Issue/Question:**

This has ended up for me to be slightly more complex than a walk in the park, let me try to explain in a simple way.

I am using imgui through [Silk.NET](https://github.com/dotnet/Silk.NET), which itself uses [ImGui.NET](https://github.com/mellinoe/imgui.net) which itself uses [cimgui](https://github.com/cimgui/cimgui) which itself finally uses the real imgui 🤣.

That said, I'm unable to figure out why the mouse cursor doesn't change, for instance, to an IBeam when I hover a text input.

When I call `GetMouseCursor()` it always return `Arrow`.

I've tried adding `io.BackendFlags |= ImGuiBackendFlags.HasMouseCursors;` but that didn't change anything.

I've retrieved the values to compare them with what you do in here:

https://github.com/ocornut/imgui/blob/83a0030c0a70042a84c3896be810607e0b1673ec/backends/imgui_impl_glfw.cpp#L574-L575

`ImGuiConfigFlags_NoMouseCursorChange` is not set nor `GLFW_CURSOR_DISABLED` but still, nothing happens.

Obviously, if I do `io.MouseDrawCursor = true;` I can get software cursors to show up but there's no comparison with hardware ones.

Do you have any idea on where I should look at in order to get hardware cursor to change like software one does?

Thank you!

**Comment by aybe** [comment]
Alright, as I'm unable to figure out what's going on under the hood, I've asked both authors since there doesn't seem to be the necessary plumbing in them.

https://github.com/cimgui/cimgui/issues/218

https://github.com/mellinoe/ImGui.NET/issues/354

Keeping this thread open for now, I will come back and update it once I hear back from them.

Thank you.

**Comment by ocornut** [comment]
I don't think this has anything to do with cimgui it has to do with which backend is running. You implied that imgui_impl_glfw was running but maybe it isn't and Silk.net/imgui.net have their own backend.

**Comment by aybe** [comment]
You are right, they all have the plumbing in place except on the managed side.

Until OpenTK and GLFW.NET get updated, one can fallback onto this, it's not fully featured but trivial to add:

```
private void UpdateCursor()
{
    Cursor = ImGui.GetMouseCursor() switch
    {
        ImGuiMouseCursor.None       => MouseCursor.Empty,
        ImGuiMouseCursor.Arrow      => MouseCursor.Default,
        ImGuiMouseCursor.TextInput  => MouseCursor.IBeam,
        ImGuiMouseCursor.ResizeAll  => MouseCursor.Default,
        ImGuiMouseCursor.ResizeNS   => MouseCursor.VResize,
        ImGuiMouseCursor.ResizeEW   => MouseCursor.HResize,
        ImGuiMouseCursor.ResizeNESW => MouseCursor.Default,
        ImGuiMouseCursor.ResizeNWSE => MouseCursor.Default,
        ImGuiMouseCursor.Hand       => MouseCursor.Hand,
        ImGuiMouseCursor.NotAllowed => MouseCursor.Default,
        ImGuiMouseCursor.COUNT      => MouseCursor.Default,
        _                           => throw new ArgumentOutOfRangeException()
    };
}
```

Thank you @ocornut.

**Comment by aybe** [comment]
I finally solved the problem, here is the solution for those who may have the same issue.

I closely followed your Win32 implementation but with one exception: always update the cursor.

This is because there is something in OpenTK that updates the cursor at every single frame.

Since they already do that, there's no harm to as well, this, until we get an update with extra GLFW cursors.

Using OpenTK + ImGui.NET + Vanara.PInvoke.User32, call this right after `ImGui::NewFrame`:

```
private void UpdateMouseCursor()
{
    if (OperatingSystem.IsWindows())
    {
        UpdateMouseCursorWindows();
    }
}

[SupportedOSPlatform("windows")]
private void UpdateMouseCursorWindows()
{
    // we have to forcibly update cursor else it will only appear briefly because of GLFW

    var io = ImGui.GetIO();

    if ((io.ConfigFlags & ImGuiConfigFlags.NoMouseCursorChange) != ImGuiConfigFlags.None)
    {
        return;
    }

    var cursor = ImGui.GetMouseCursor();

    if (io.MouseDrawCursor)
    {
        cursor = ImGuiMouseCursor.None;
    }

    Window.CursorState = cursor == ImGuiMouseCursor.None ? CursorState.Hidden : CursorState.Normal;

    // ReSharper disable once SwitchExpressionHandlesSomeKnownEnumValuesWithExceptionInDefault

    var resource = cursor switch
    {
        ImGuiMouseCursor.None       => ResourceId.NULL,
        ImGuiMouseCursor.Arrow      => User32.IDC_ARROW,
        ImGuiMouseCursor.TextInput  => User32.IDC_IBEAM,
        ImGuiMouseCursor.ResizeAll  => User32.IDC_SIZEALL,
        ImGuiMouseCursor.ResizeNS   => User32.IDC_SIZENS,
        ImGuiMouseCursor.ResizeEW   => User32.IDC_SIZEWE,
        ImGuiMouseCursor.ResizeNESW => User32.IDC_SIZENESW,
        ImGuiMouseCursor.ResizeNWSE => User32.IDC_SIZENWSE,
        ImGuiMouseCursor.Hand       => User32.IDC_HAND,
        ImGuiMouseCursor.NotAllowed => User32.IDC_NO,
        _                           => throw new InvalidEnumArgumentException(null, (int)cursor, typeof(ImGuiMouseCursor))
    };

    User32.SetCursor(User32.LoadCursor(HINSTANCE.NULL, resource));
}

```

**Comment by copygirl** [comment]
I just want to note I ran into a similar issue, and couldn't quite make sense of it. It appears calling `GetMouseCursor` right after `NewFrame` was the mistake in my case, since presumably, it is reset there, so I only ever got `Arrow` as a result. I moved my `GetMouseCursor` call to before `NewFrame` instead. Presumably after `Render` would work too. Just wanted to note this here in case someone makes the same mistake as me.

**Comment by ocornut** [comment]
That's a good point, thank you. I'll add a comment about this or may rework this.
Supposedly `GetMouseCursor()` should only be used by the platform backend, and the platform backend should only interact before `NewFrame()` and after `Render()`.

**Comment by aybe** [comment]
[My previous suggestion](https://github.com/ocornut/imgui/issues/5739#issuecomment-1268734162) using `User32.SetCursor` ended up being problematic in some cases.

Spoke with people at GLFW and they suggested to set GLFW's cursor instead:

```
    [SupportedOSPlatform("windows")]
    private static unsafe Cursor* CreateMouseCursorWindows(ImGuiMouseCursor mouseCursor)
    {
        // ReSharper disable once SwitchExpressionHandlesSomeKnownEnumValuesWithExceptionInDefault

        var resourceId = mouseCursor switch
        {
            ImGuiMouseCursor.Arrow      => User32.IDC_ARROW,
            ImGuiMouseCursor.TextInput  => User32.IDC_IBEAM,
            ImGuiMouseCursor.ResizeAll  => User32.IDC_SIZEALL,
            ImGuiMouseCursor.ResizeNS   => User32.IDC_SIZENS,
            ImGuiMouseCursor.ResizeEW   => User32.IDC_SIZEWE,
            ImGuiMouseCursor.ResizeNESW => User32.IDC_SIZENESW,
            ImGuiMouseCursor.ResizeNWSE => User32.IDC_SIZENWSE,
            ImGuiMouseCursor.Hand       => User32.IDC_HAND,
            ImGuiMouseCursor.NotAllowed => User32.IDC_NO,
            _                           => throw new InvalidEnumArgumentException(null, (int)mouseCursor, typeof(ImGuiMouseCursor))
        };

        using (var hCursor = User32.LoadCursor(HINSTANCE.NULL, resourceId))
        using (var hIcon = new User32.SafeHICON(hCursor.DangerousGetHandle()))
        {
            var iconInfo = new User32.ICONINFO();

            if (!User32.GetIconInfo(hIcon.DangerousGetHandle(), iconInfo))
                Win32Error.ThrowLastError();

            Debug.Assert(iconInfo.fIcon is false, "iconInfo.fIcon is false");

            using (var icon = Icon.FromHandle(hIcon.DangerousGetHandle()))
            using (var bitmap = icon.ToBitmap())
            {
                var data = bitmap.LockBits(new Rectangle(Point.Empty, bitmap.Size), ImageLockMode.ReadOnly, bitmap.PixelFormat);

                var image = new Image(bitmap.Width, bitmap.Height, (byte*)data.Scan0.ToPointer());

                var cursor = GLFW.CreateCursor(image, iconInfo.xHotspot, iconInfo.yHotspot);

                bitmap.UnlockBits(data);

                return cursor;
            }
        }
    }

```

```
		<PackageReference Include="OpenTK" Version="4.7.5" />
		<PackageReference Include="System.Drawing.Common" Version="6.0.0" />
		<PackageReference Include="Vanara.PInvoke.User32" Version="3.4.10" />
```

`Icon.FromHandle` does all the heavy lifting here, if you're not using C#, it will be slightly more involved than that:

- get the [cursor information](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-iconinfo)
- if your cursor is colored, XOR `hbmColor` and `hbmMask`, flip them vertically first if their stride is negative
- if your cursor is monochrome, you'll only have to deal with `hbmMask`
- pass that new bitmap along hotspot coordinates to [glfwCreateCursor](https://www.glfw.org/docs/3.3/group__input.html#ga556f604f73af156c0db0e97c081373c3)

You will want to cache these cursors in a dictionary when initializing your controller.
