### ISSUE TITLE
 Increasing code quality by adding a single line

### ISSUE THREAD

**Issue by TYSON-Alii** [ocornut/imgui#5740]
i think its' so cool

![image](https://user-images.githubusercontent.com/65432197/193405353-12daec2a-fa93-4385-819d-739483215b8f.png)

```cpp
#define im ImGui::
```

**Comment by ocornut** [comment]
Thank you for the idea.

I think some IDE or code formatting tool might be confused by preprocessor tricks that don’t follow the language grammar. Another way would be to creste an alias for the namespace:

namespace im = ImGui;

i’ll close this as there’s no issue involved.
