### ISSUE TITLE
Why chaining flags in ImGui::Begin() with | and not with & or && or ||

### ISSUE THREAD

**Issue by githubuser872349** [ocornut/imgui#5743]
hello
my question is really just the title:
Why chaining flags in ImGui::Begin() with | and not with & or && or ||

**Comment by ocornut** [comment]
Each flag is a power-of-two value and they are combined with a Binary Or | operator (read about Binary Or https://en.m.wikipedia.org/wiki/Bitwise_operation) to be stored in an integer.

Think of them as booleans packed together in a single integer. An 32-bit integer can store 32 of them. It’s a common peogramming idiom. 

Read about the difference between Binary Or (|), Binary And (&), Logical Or (||), Logical And (&&).

**Comment by githubuser872349** [comment]
@ocornut 
thank you for the fast answer.
