### ISSUE TITLE
Remember if window is closed/open in imgui.ini

### ISSUE THREAD

**Issue by Thomas-Shaer** [ocornut/imgui#5744]
Hi, is it possible to extend the imgui.ini file to include the open/close state of a window?

Something like this:
```
[Window][Documentation]
Pos=1177,271
Size=500,600
Collapsed=0
Open=0
```

Thanks.

**Comment by ocornut** [comment]
No it isn't. 
This would be akin to provide a helper serialization system for the user (#437) which isn't out of question but is largely not a priority. We'll keeping #437 open for that reason.

That "open" bool would need to drive the flow of your code and you'll inevitably want to manipulate its value yourself, at which point it becomes bizarre and redundant to store it as part of .ini data.
