### ISSUE TITLE
custom glyph codepoint (remap)

### ISSUE THREAD

**Issue by MungoBerry** [ocornut/imgui#5748]
Hi, 

it is possible to set custom glyph codepoint for fonts ?
Suppose I've a symbol font and I want to remap e.g. codepoint U+4DC0 to 'a'.
Can be achieved ?
I know I can create my custom font atlas using ImFontGlyphRangesBuilder but I would to change codepoints too.

Thank you.

**Comment by ocornut** [comment]
If you search for the word "remap" in imgui.h you'll find:

```cpp
// Makes 'dst' character/glyph points to 'src' character/glyph. Currently needs to be called AFTER fonts have been built.
ImFont::AddRemapChar(ImWchar dst, ImWchar src, bool overwrite_dst = true);
```

**Comment by MungoBerry** [comment]
> If you search for the word "remap" in imgui.h you'll find:
> 
> ```c++
> // Makes 'dst' character/glyph points to 'src' character/glyph. Currently needs to be called AFTER fonts have been built.
> ImFont::AddRemapChar(ImWchar dst, ImWchar src, bool overwrite_dst = true);
> ```

Thank you, I think should be added to FONTS.md doc
