### ISSUE TITLE
Help with using imgui with a window that can be clicked thrrough

### ISSUE THREAD

**Issue by SNO2207** [ocornut/imgui#5752]
Hello! I've been recently experimenting with imgui and all it has to offer and I've come across an issue I can't figure out. Im running ImGui with GLFW3 with opengl and I am using a transparent window to render Imgui. However, this transparent window cannot be clicked through. Yes I understand there is a "_glfwSetWindowAttrib(window, GLFW_MOUSE_PASSTHROUGH, GLFW_TRUE)_" code to bypass this however I cannot click on the ImGui window when I do this. Is there any way someone can help me with this issue?

-SNO

**Comment by ocornut** [comment]
Hello,

The *purpose* of `glfwSetWindowAttrib(window, GLFW_MOUSE_PASSTHROUGH, GLFW_TRUE)` is to make your window  not catch mouse click. Please be more detailed and explicit with your issue and read guidelines carefully and fill an issue template otherwise we cannot help you.
