### ISSUE TITLE
set windwos size and set visibile question..

### ISSUE THREAD

**Issue by tiantianaixuexi** [ocornut/imgui#5754]
**Version/Branch of Dear ImGui:**

Version: v1.87
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_Win32.cpp + imgui_impl_dx12.cpp _(or specify if using a custom engine/back-end)_
Compiler: VisualStudio2020 c++20
Operating System: Windows

**My Issue/Question:**

I want to make an animation that after a button is clicked it shrinks a window to 0 and then disappears, it works fine. But when there is only 1/10 left, it will Disappear without finishing

**Screenshots/Video**

![Histogram Select](https://user-images.githubusercontent.com/31758095/193881775-5ec080d1-9bde-4db7-9642-518c2df8441d.gif)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
			int width = 0;
			int height = 0;
			RECT rect;
			if (GetWindowRect(hwnd, &rect))
			{
				width = rect.right - rect.left;
				height = rect.bottom - rect.top;
			}

                        {
					static float f = 0.0f;
					static int counter = 0;
					static bool MainMenu_Open = true;
					static float size = width * 0.15f;
					if (MainMenu_Open) {
						
						ImGui::Begin("ShineWindows",&MainMenu_Open,ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoScrollbar);
						ImGui::SetWindowPos(ImVec2(0.f, 0.f));
						ImGui::SetWindowSize(ImVec2(size, height));
						ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(0.31f, 0.33f, 0.36f, 1.f));
						ImGui::BeginChild((const char*)def::MainMenu_Name.data(), ImVec2((float)(width * 0.15f), height));                          // Create a window called "Hello, world!" and append into it.

						if (AnimationPlay == true) {

							size -= 5;
							if (size <= 0.0) {
								AnimationPlay = false;
								MainMenu_Open = false;
							}
						}

						if (ImGui::Button("AnimButton")) {
							AnimationPlay = true;
						}
						ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
						ImGui::EndChild();
						ImGui::PopStyleColor();
						ImGui::End();
					}
                         }
```

**Comment by ocornut** [comment]
You should use SetNexrWindowPos/Size prior to the Begin() + alter the WindowMinSize variable by using PushStyleVar(ImGuiStyleVar_WindowMinSize, ImVec2(1,1));/PopStyleVar()

However things are not designed to display windows of that size so expect small glitches but may be ok during an animation.
