### ISSUE TITLE
Dynamic structure (not just dynamic data in structures)

### ISSUE THREAD

**Issue by dtp555-1212** [ocornut/imgui#5757]
Dynamic structure (not just dynamic data in structures)

I would like to create a different structure dynamically depending on input data… For example, if I have an XML, (or JSON, or any format) string… I want to create an indented nest of collapsing headers, that may contain varying number of text items.

Statically, for one specific case, it would be something like this…
ImGui::Begin("TEST");
    if (ImGui::CollapsingHeader("I1: XXX")) {
        ImGui::Indent();
        if (ImGui::CollapsingHeader("xxx")) {
                ImGui::Text("v: 1");
        }
        if (ImGui::CollapsingHeader("yyy")) {
                ImGui::Text("v: 2");
                ImGui::Text("attr: t");
        }
        ImGui::Unindent();
    }
    if (ImGui::CollapsingHeader("I2: YYY")) {
        ImGui::Indent();
            if (ImGui::CollapsingHeader("zzz")) {
                ImGui::Text("v: 9");
                ImGui::Text("attr: f");
            }
        ImGui::Unindent();
    }
    ImGui::End();

However, the number of CollapsingHeader peers, and the number of text items, all can vary.

1) Is this possible with IMGUI?
2) If not, I am able to get it ‘close’ but not quite working… e.g. it displays all the parts, but the ‘CollapsingHeaders’ are not associated with the text items, like they are in the static example. (Is there some hidden effect with scoping or something like that?)

Any advice would be appreciated.

Thanks in advance

**Comment by ocornut** [comment]
> Is this possible with IMGUI?

Yes. The purpose of Dear ImGui is that it follows your code, so you are free to have dynamic UI.
In other words, the reason you are asking is likely not a dear imgui problem but a problem in your code.

> If not, I am able to get it ‘close’ but not quite working… e.g. it displays all the parts, but the ‘CollapsingHeaders’ are not associated with the text items, like they are in the static example. (Is there some hidden effect with scoping or something like that?)

I don't understand this paragraph. You'll need to be way more explicit and precise in your explanation.
Your code seems to do what it says:

![image](https://user-images.githubusercontent.com/8225057/194393370-d15d2d06-142b-4bfd-a9da-755fbe5dea3c.png)

**Comment by dtp555-1212** [comment]
Thanks for your quick response.... I probably wasn't clear... Yes, The code in the example does work, but it is static in structure. It was just an example of 1 specific instance. I am looking to dynamically layout variations of that, that have arbitrary number of peers for the CollapsingHeaders, nesting of collapsing headers, N number of text items per CollapsingHeaders.

I have some code that attempts to dynamically create the layout, but with that (the dynamic) version the layout is fine, but the open/close of the collapsingHeader does not rollup its children like the static version.

Hope that clarifies the goal. With that understanding, you still say IMGUI should allow dynamic structure creation at runtime? If so, is there an example of a dynamic structure version that I can refer to?

Thanks again

**Comment by ocornut** [comment]
>  If so, is there an example of a dynamic structure example that I can refer to?

The entire demo window is a dynamic structure. Heck, everything you do is dear imgui is a dynamic structure.

You may be hitting an ID conflict if you are trying to use the same label twice which disambiguation through the ## operator or PushID() calls.  Read the FAQ entry https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

**Comment by dtp555-1212** [comment]
The term 'dynamic structure' may be ambiguous... What I am trying to say, is in the 'example' above... The code will do exactly one thing... 2 peer CollapsingHeaders, 1 with 2 children, the other with one, and those children have exactly 1, 2, and 2 text children respectively. You can change the contents of the fields, but the structure is static, by my definition. I am looking for a way to change the 'structure' at runtime. I haven't seen any examples where that is actually done. Hope that helps in the terminology.

I will try the pushID idea and see if that helps...

Thanks

**Comment by ocornut** [comment]
Well your code is incorrect and I see no dear imgui bug there. 
Unfortunately this is not a place here for us to help you debug your code but if you step in with a debugger you'll see that **you are submitting all your items** regardless of the state and return value of `CollapsingHeader()`. The next iteration simply keeps submitting all subsequent items.

There's no explicit concept of parent/child relation in your data set. Assuming that the data correctly contains balanced indent/unindent you could make it that when a CollapsingHeader() returns false you count I/U nodes and skip until when the count pass the outer-most unindent. Probably you can use a better structure (e.g. a json source would hold an actual tree). 

Either way none of this is a dear imgui question at this point. Good luck!

**Comment by dtp555-1212** [comment]
Thanks... it was a misunderstanding of the return code of CollapsingHeader... I had been told it was an error return that couldn't happen, but it is really an open indicator... Code works great now!

P.S. the data structure obviously does not get hardcoded in the real application, but gets dynamically generated from dynamically created XML/JSON.
