### ISSUE TITLE
ImDrawList doesn`t work on win7

### ISSUE THREAD

**Issue by Elllkere** [ocornut/imgui#5758]
**Version/Branch of Dear ImGui:**

Version: v1.85
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends:
imgui.cpp/h, imgui_draw.cpp, imgui_impl_dx11.cpp/h, imgui_impl_win32.cpp/h, imgui_internal.h, imgui_tables.cpp, imgui_widgets.cpp, imstb_rectpack.h, imstb_textedit.h, imstb_truetype.h
Compiler: (Don't know, must be on default for Visual Studio 2017)
Operating System: Win7, win10

**My Issue/Question:**

Im compiling a dll on win10 for injecting it into the game and rendering menu with ImDrawList (some text).
On win10 it`s working, but i gave it to man who has win7 and nothing renders (and dll is injected, other functions working).
Also tried to use ImGui::RenderText with "TEEEEEEEEEEEEEEXT" and when im on win10 get TEEEEEEEEEEEEEEXT, user on win7 get EEE

**Screenshots/Video**

Test with ImGui::RenderText(ImVec2(0, 0), "TEEEEEEEEEEEEEEXT");
win10
![2525125](https://user-images.githubusercontent.com/96520236/194389379-4781e8c1-428d-49b3-bdb5-5ac98d999cfe.png)

win7
![2525125](https://user-images.githubusercontent.com/96520236/194389498-b05f60ee-51c2-4e8a-991e-5704270ad50e.png)

```
ID3D11Device* pDevice = NULL;
ID3D11DeviceContext* pContext = NULL;
ID3D11RenderTargetView* mainRenderTargetView;

//PresentHook
if (!Create)
{
	if (FAILED(pSwapChain->GetDevice(__uuidof(ID3D11Device), (void**)& pDevice)))
		return p_PresentEnd(pSwapChain, SyncInterval, Flags);

	pDevice->GetImmediateContext(&pContext);

	DXGI_SWAP_CHAIN_DESC sd;
	pSwapChain->GetDesc(&sd);

	ID3D11Texture2D* pBackBuffer;
	pSwapChain->GetBuffer(0, __uuidof(ID3D11Texture2D), (LPVOID*)& pBackBuffer);
	pDevice->CreateRenderTargetView(pBackBuffer, NULL, &mainRenderTargetView);
	pBackBuffer->Release();

	ImGui::CreateContext();

	ImGui_ImplWin32_Init(window);
	ImGui_ImplDX11_Init(pDevice, pContext);

	Create = 1;
}

ImGui_ImplWin32_NewFrame();
ImGui_ImplDX11_NewFrame();
ImGui::NewFrame();

ImGui::Begin("#menu", false, ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoInputs);

ImDrawList* draw_list = ImGui::GetCurrentWindowRead()->DrawList;	

draw_list->AddText(ImVec2(100, 400), ImColor(255, 255, 255), "Test");

ImGui::End();
ImGui::Render();

pContext->OMSetRenderTargets(1, &mainRenderTargetView, NULL);
ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
```

**Comment by nicolasnoble** [comment]
#1586
