### ISSUE TITLE
Centering ImGui::InputText

### ISSUE THREAD

**Issue by MoatLovescs** [ocornut/imgui#5764]
i want to center the inputtext and i want the text "License" to be in the top corner left of the inputtext. how?????
![image](https://user-images.githubusercontent.com/100001861/194767458-4a1efdde-8d64-4a2d-b91c-c162f1cb542c.png)

**Comment by v-atamanenko** [comment]
Basically you do three things to achieve this:
1) Set cursor position X to available content region width minus item width divided by two.
2) Use ::Text() for your label.
3) Suppress original label using something like "##dummy".

```c++
bool InputTextCentered(const char* label, char* buf, size_t buf_size, ImGuiInputTextFlags flags = 0, ImGuiInputTextCallback callback = NULL, void* user_data = NULL) {
    const float input_width = ImGui::CalcItemWidth();
    ImGui::SetCursorPosX((ImGui::GetWindowContentRegionMax().x - input_width) / 2.f);
    ImGui::Text("%s", label);
    ImGui::SetCursorPosX((ImGui::GetWindowContentRegionMax().x - input_width) / 2.f);
    return ImGui::InputText("##dummylabel", buf, buf_size, flags, callback, user_data);
}
```

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/11796486/195087852-9e92d14d-9d63-4c8b-be1d-a109721bf61a.png">

**Comment by MoatLovescs** [comment]
> 

Hi and thanks! what if i wanted to add a button in the bottom left corner? Thanks!

**Comment by MoatLovescs** [comment]
> Just another `ImGui::SetCursorPosX((ImGui::GetWindowContentRegionMax().x - input_width) / 2.f);` and `ImGui::Button(...)`. Keep in mind that InputText and Button are both non-void, so you need to come up with a way to preserve both return values (if you need them both, that is). For example, adding `bool*` argument and saving input text return value there.

thank You <3!
