### ISSUE TITLE
I can't center the crosshair image in the game i am making. Please help

### ISSUE THREAD

**Issue by Iacaka** [ocornut/imgui#5765]
I can't center the image (.png) i use as a crosshair. I looked and the image itself is centered, but i can't get it to work in my game. Here is some code:
int a = 20;
void RenderImGuiCrosshair() {
			//[TO DO] - fix possitionning / fix crosshair filter
			ImGui::SetNextWindowPos(ImVec2((window.GetSize().x - a)/2 , (window.GetSize().y - a)/2 ));
			ImGui::Begin("crosshair", NULL, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoScrollbar);
			ImGui::Image(crosshair, ImVec2(a, a));
			ImGui::End();
		}

"a" is just a value that i change frequently, because i was experimenting. 
The Crosshair is just a bit of the side, not quite centered. I made so my mouse i stuck to the center (i can't show the cursor of my mouse in the screenshots).
Best way i can show it:
![image](https://user-images.githubusercontent.com/93211222/194775482-192b9a05-4b43-42f3-b954-6b774c07c7f7.png)

**Comment by ocornut** [comment]
You are not accounting for window padding.
Since your window has no background you may have it fill the whole viewport or directly draw into GetBackgroundDrawList().
