### ISSUE TITLE
Exception handling advice

### ISSUE THREAD

**Issue by ypujante** [ocornut/imgui#5769]
I am trying to build a friendly user interface where I want to display a modal/popup whenever an unhandled exception is detected and allow the user to save the work done so far.

I tried something like this:

```cpp

// std::optional<std::exception_ptr> fException{};

bool Application::render() noexcept
{
  if(fException)
  {
     return doRenderException();
  }
  else
  {
    try
    {
      return doRender();
    }
    catch(...)
    {
      fException = std::current_exception();
      return true; // will render a popup
    }
  }
}
```

The problem I am bumping into, is that if the exception gets thrown in between a Begin() / End(), then the exception is properly caught but them ImGui aborts with the following message:

```
Assertion failed: ((g.CurrentWindowStack.Size == 1) && "Mismatched Begin/BeginChild vs End/EndChild calls: did you forget to call End/EndChild?"), function ErrorCheckEndFrameSanityChecks, file imgui.cpp, line 9038.
```

Is there something I can do in the `catch(...)` statement to tell ImGui something like "discard this frame"?

If this is not the proper way to ask this kind of question, can you kindly inform me of where I can ask this kind of question?

Thank you

**Comment by ocornut** [comment]
You may call `ErrorCheckEndFrameRecover()` prior to `EndFrame()`.
Linking to #1651

**Comment by ypujante** [comment]
Thank you. I did not see because it was in the `imgui_internal.h` header file.

**Comment by ocornut** [comment]
Closing as answered. Feedback on said function would be greatly useful!

**Comment by ypujante** [comment]
I added it to my code and it works in most instances, which is great. I ended up in a situation where I was accessing a key in a map that did not exist (`std::map::at` which throws `std::out_of_range`) from within a table and it does not recover.

It might be my use case only, but for me, I don't care about "recovering" per se: when an exception occurs, what I would like to do is literally call something like `ImGui::Reset()` which resets everything back to the state of when I started the application (`main`), the state that `ImGui` is in when it is instantiated. I just want to display a modal window with the fact that there was an error, what it was and an option to save the work that was in process and then exits. But to do that I need to use `ImGui`...

**Comment by ocornut** [comment]
> I ended up in a situation where I was accessing a key in a map that did not exist (std::map::at which throws std::out_of_range) from within a table and it does not recover.

A repro would be helpful so we can attempt to fix it.

You may use a second context for the error message.

**Comment by ypujante** [comment]
I will try to provide a self contained repro (using one of the small example built-in).

I don't know what you mean by "a second context for the error message"

**Comment by ocornut** [comment]
You can create a second imgui context and use it within a blocking/modal loop over the first context that handled an exception.

**Comment by ypujante** [comment]
Here is a small repro (copied `example_win32_directx11`)

[main_5769.zip](https://github.com/ocornut/imgui/files/9792699/main_5769.zip)

When you run it, you can open a popup modal which contains a table which contains a button triggering the exception.

There are 2 other buttons `Click me! (works)` where recovery works fine.

Or if you just want the code:

```cpp
void ClickMeForError(bool willFail)
{
  if(ImGui::Button(willFail ? "Click Me! (fails)" : "Click Me! (works)"))
  {
    std::string s{};
    s.at(1);
  }
}

void renderWithException()
{
  if(ImGui::Begin("My Window", nullptr, ImGuiWindowFlags_AlwaysAutoResize))
  {
    auto id = ImGui::GetID("My Popup");
    if(ImGui::Button("Open Popup"))
    {
      ImGui::OpenPopup(id);
    }
    ClickMeForError(false);

    if(ImGui::BeginPopupModal("My Popup", nullptr, ImGuiWindowFlags_AlwaysAutoResize))
    {
      if(ImGui::BeginTable("StringListEdit", 1, ImGuiTableFlags_Borders))
      {
        ImGui::TableSetupColumn("Action");

        ImGui::TableNextRow(ImGuiTableRowFlags_Headers);

        ImGui::TableSetColumnIndex(0);
        const char* column_name = ImGui::TableGetColumnName(0); // Retrieve name passed to TableSetupColumn()
        ImGui::PushID(0);
        ImGui::TableHeader(column_name);
        ImGui::PopID();

        ImGui::TableNextRow();
        ImGui::TableSetColumnIndex(0);

        ImGui::PushID("Dest.");
        ClickMeForError(true); // <---- trigger the non recoverable state
        ImGui::PopID();

        ImGui::EndTable();
      }


      ClickMeForError(false);
      ImGui::EndPopup();
    }
  }
  ImGui::End();

}

bool render() noexcept
{
  try
  {
    renderWithException();
    return true;
  }
  catch(...)
  {
    fprintf(stderr, "Detected exception, trying to recover...\n");
    ImGui::ErrorCheckEndFrameRecover(nullptr);
    fprintf(stdout, "Recovery success!!!\n");
    return false;
  }
}
```
