### ISSUE TITLE
Multiple clicks to open a menu

### ISSUE THREAD

**Issue by sggrissom** [ocornut/imgui#577]
I apologize in advance because I'm almost certainly doing something wrong. But my current simple application has a menu bar with a drop down menu with several options. Below is a simplified version of the very simple menu.

Everything works perfectly with normal items, but with my OpenFile() call, it opens a windows explorer popup. When finishing with the windows popup the menu closes (as I would expect). The problem is if I try to select the menu again, or another button or anything, it will often take an extra click (though not always). The behavior is as if I moved the mouse off of the popup and need to click elsewhere to close the popup before interacting with the ui again.

I can't see anything obvious to help with this situation. I've tried the various close popup calls but apparently the pop is actually closing, so I'm not sure what's holding up the interactions. Is this something that's been seen before? Any ideas what I can try?

```
ImGui::Begin("Title Bar Menu", 0, WindowFlags);
if(ImGui::BeginMenuBar())
{
    if(ImGui::BeginMenu("Menu"))
    {
        if(ImGui::MenuItem("Choose File", "Ctrl+O"))
        {
            OpenFile(Window, ReadFile);
        }
        if(ImGui::MenuItem("Process File"))
        {
            DoStuff();
        }
        ImGui::EndMenu();
    }
    ImGui::EndMenuBar();
}
ImGui::End();
```

**Comment by ocornut** [comment]
Isn't it just a case where your application isn't feeding ImGui with mouse inputs when your main window isn't focused? What happen if you first click on your OS window title bar to give it back focus?

Try to display the mouse position with `ImGui::Text("%f %f", ImGuI::GetIO().MousePos.x, ImGuI::GetIO().MousePos.y);` and see what your values are after you have clicked and lost focus.

**Comment by sggrissom** [comment]
That was exactly it and it works great now. Thank you!
