### ISSUE TITLE
InputEventsQueue access synchronization problem

### ISSUE THREAD

**Issue by Krasjet** [ocornut/imgui#5772]
**Version/Branch of Dear ImGui:**

Version: edf522b58a8f74dee3225a0d5bc71565b1b8f6e0
Branch: master/docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + custom backend (with JUCE)
Compiler: GCC/Clang (confirmed)
Operating System: Linux/macOS (confirmed)

**My Issue/Question:**

In very rare cases, `AddKeyAnalogEvent` will try to access a zero-sized `InputEventsQueue` and cause an assertion error
```
a.out: /home/kst/imgui-src/imgui.h:1871: T& ImVector<T>::operator[](int) [with T = ImGuiInputEvent]: Assertion `i >= 0 && i < Size' failed.
zsh: IOT instruction (core dumped)  ./a.out
```
This problem will only happen when `AddKeyAnalogEvent` is not invoked on the rendering thread. This shouldn't be a problem for GLFW/SDL, but for JUCE, the key press callback and rendering happen on different threads. Because `InputEventsQueue` is flushed in `UpdateInputEvents` of every new frame,

```cpp
    printf("flush\n");
    if (event_n == g.InputEventsQueue.Size)
        g.InputEventsQueue.resize(0);
    else
        g.InputEventsQueue.erase(g.InputEventsQueue.Data, g.InputEventsQueue.Data + event_n);
```
it is possible that the queue is flushed between `n` is initialized and accessed.

```cpp
    printf("before loop\n");
    for (int n = g.InputEventsQueue.Size - 1; n >= 0; n--)
    {
        printf("access\n");
        ImGuiInputEvent* e = &g.InputEventsQueue[n];
        if (e->Type != type)
            continue;
        if (type == ImGuiInputEventType_Key && e->Key.Key != arg)
            continue;
        if (type == ImGuiInputEventType_MouseButton && e->MouseButton.Button != arg)
            continue;
        return e;
    }
```
This leads to the following execution pattern when you fire keypress events rapidly
```
...
before loop
access
before loop
access
before loop
flush
access
a.out: /home/kst/imgui-src/imgui.h:1871: T& ImVector<T>::operator[](int) [with T = ImGuiInputEvent]: Assertion `i >= 0 && i < Size' failed.
zsh: IOT instruction (core dumped)  ./a.out
```
We need some access synchronization for this queue to prevent the crash.

**Comment by ocornut** [comment]
Hello,

> We need some access synchronization for this queue to prevent the crash.

Dear ImGui is not thread safe. Your custom backend should probably queue JUCE events and submit them in batches before `NewFrame()`.

**Comment by ocornut** [comment]
Actually reopening this, because in various places we realized that pushing to event queue was 99% thread-safe and this is maybe the only leftover thing that fails to make this 100% working (to be confirmed).
The workaround in the meanwhile would be to mutex `io.AddXXXEvent()` calls with the calling of `ImGui::NewFrame()`, but we could potentially narrow the later down.
