### ISSUE TITLE
Crashed when using multi-viewport  on the expand screen in windows 10

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#5774]
**Version/Branch of Dear ImGui:**

Version: 1.88#1
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_SDL.cpp + imgui_impl_OpenGL3.cpp
Compiler: MSVC of Visual Studio 2019
Operating System: Windows 10

**My Issue/Question:**

Steps below:
* Create Dock Window
* Create Normal Window (imgui::begin, imgui::end)
* Move Dock Window to another expand screen in windows 10 (there are two expand screens in my pc)
* Then drag out the Normal Window from dock space
* And it crashed which need to kill the process

**Screenshots/Video**

NONE

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
	const ImGuiViewport* viewport = ImGui::GetMainViewport();
	ImGui::SetNextWindowPos(viewport->WorkPos);
	ImGui::SetNextWindowSize(viewport->WorkSize);
	ImGui::SetNextWindowViewport(viewport->ID);
	ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
	ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
	ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
	ImGuiWindowFlags window_flags = ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoDocking;
	window_flags |= ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove;
	window_flags |= ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus;
	ImGui::Begin(m_Name.getValue().c_str(), nullptr, window_flags);
	ImGui::PopStyleVar(3);
	auto dockspace_id = ImGui::GetID(m_Name.getValue().c_str());
	ImGuiDockNodeFlags dockspace_flags = ImGuiDockNodeFlags_None;
	ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), dockspace_flags);
	ImGui::End();
```

**Comment by PathogenDavid** [comment]
I can't reproduce this, but your code snippet isn't totally self-contained either. Can you provide a stack trace of the crash? Do you experience this crash in the official examples?

**Comment by ChivenZhang** [comment]
> I can't reproduce this, but your code snippet isn't totally self-contained either. Can you provide a stack trace of the crash? Do you experience this crash in the official examples?

I have tried official example [example_sdl_opengl3.cpp] in other computer, It works well. 
My own pc is dell g15 which contains one screen integrated and an expand screen which using gpu accelerate.
You can visit website below for more product infomation about the expand screen, i guess it caused by hardware.
https://www.dell.com/support/kbdoc/zh-cn/000131820/dell-amd-freesync-monitors-that-are-nvidia-g-sync-compatible?lang=en

**Comment by ChivenZhang** [comment]
> I can't reproduce this, but your code snippet isn't totally self-contained either. Can you provide a stack trace of the crash? Do you experience this crash in the official examples?

I'll take you the stack trace after working.

**Comment by ChivenZhang** [comment]
> I can't reproduce this, but your code snippet isn't totally self-contained either. Can you provide a stack trace of the crash? Do you experience this crash in the official examples?

The process was just block here when I drag out the normal window from Dock space on the second screen.

Source Code:
![image](https://user-images.githubusercontent.com/48938612/195961566-b8c35d65-97f2-4d35-847e-8d5898ab061f.png)

Viewport Block:
![image](https://user-images.githubusercontent.com/48938612/195961639-586ab519-3402-4a61-8a82-ae4b08dbd398.png)

Stack Trace:
![image](https://user-images.githubusercontent.com/48938612/195961702-a052d97c-e6d2-4117-8d55-02a3b88cd63c.png)

**Comment by ocornut** [comment]
Hello, looks related to multi-viewports and has nothing to do with docking. Please check the other threads about problems on Windows with OpenGL eg #4468 and #4832.

Please also make sure you don’t have broken software like Nahimic installed #3321 #5354.

**Comment by ChivenZhang** [comment]
> Hello, looks related to multi-viewports and has nothing to do with docking. Please check the other threads about problems on Windows with OpenGL eg #4468 and #4832.
> 
> Please also make sure you don’t have broken software like Nahimic installed #3321 #5354.

I am sure that I used a single thread for both opengl swapbuffer and imgui draw. Of course not using Nahimic software .etc.

**Comment by PathogenDavid** [comment]
Since the crash is happening in external code above the implementation of `SDL_GL_SwapWindow` this is probably being caused by something injected into your process or buggy drivers. If you right-click the call stack window and select "Show External Code" you can get more details.

It would also be helpful to see the list of modules loaded into the process during the crash. You can open the list under Debug > Windows > Modules (default shortcut is Ctrl+Alt+U.) You can copy+paste from that table into [a GitHub Gist](https://gist.github.com/) and share it here.

**Comment by ChivenZhang** [comment]
Umm, It's ok to develop my application without viewport feature. So I Just close this issure.
