### ISSUE TITLE
[SDL2 + OpenGL3 for Debian10] Window turns black when it is outside the main window

### ISSUE THREAD

**Issue by OriolCS2** [ocornut/imgui#5779]
Version/Branch of Dear ImGui:

Version: 1.88 WIP
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl2.cpp
Compiler: g++
Operating System: Debian 10

My Issue/Question:

When I move a window outside of the main window, it turns black as the image below. This only happens in Debian 10, my game engine is cross platform and ImGui is working fine in other systems.
This issue is like https://github.com/ocornut/imgui/issues/2600 , but it was created for windows so I decided to open another issue because now it is in Debian 10.

Here the panel on the right (Hierarchy) is still inside the main window so it is working fine.
![image](https://user-images.githubusercontent.com/36154523/195977628-48afd86e-ac68-46ca-a65e-37d919807dec.png)

But if I move it outside it turns black but the input is still working (I can select everything inside it).
![image](https://user-images.githubusercontent.com/36154523/195977633-7273c0db-0d35-4b59-8cbe-de4c28914ede.png)

**Comment by PathogenDavid** [comment]
It would be helpful to know what GPU and driver you're using. Can you share the output of `glxinfo | grep OpenGL`?

**Comment by OriolCS2** [comment]
As @PathogenDavid said, I opened the example_sdl_opengl3 and it worked fine. So the only difference was that I am self compiling the sdl library and I missed to add a CPPDEFINE (SDL_VIDEO_OPENGL). After adding it and compiling again sdl it worked as expected. I close the issue, thanks!
