### ISSUE TITLE
How can I use imGui to draw a single pixel without using Graphic API

### ISSUE THREAD

**Issue by Wayne693** [ocornut/imgui#5780]
Hi,I want to make a software renderer by imGui,and I want to know which API can I use to draw a signal pixel(or set the rgb of the pixel), I hope there is an API use like DrawPoint(x,y,color) ,mains set the pixel color which position is (x,y) on imGui window

**Comment by PathogenDavid** [comment]
Dear ImGui's drawing API is fundamentally vector-based, not raster. You can draw pixel-sized rectangles using `ImDrawList::AddRectFilled`, but it's not going to be very efficient.

You would be much better off rendering to your own pixel buffer, uploading that to a GPU, and drawing that texture with `ImGui::DrawImage`.

Also in the future please fill out the issue template when asking questions.

**Comment by Wayne693** [comment]
Thank you for answering my question. It's very helpful to me.
