### ISSUE TITLE
Wierd behavior when dragged all of windows from the custom defined docking layout

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#5782]
**Version/Branch of Dear ImGui:**

Version: 1.88#1
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp _(or specify if using a custom engine/back-end)_
Compiler: MSVC VS2019
Operating System: Windows 10

**My Issue/Question:**
Operations as below:
* Create Docking space window and define dock layout customly using dockbuild api
* Create the relative sub windows which specified in step 1
* Drag alll of sub windows out of docking space
* Try to merge any of sub windows into docking space, but it failed

**Screenshots/Video**
![166585068076620221016021502](https://user-images.githubusercontent.com/48938612/195997175-8fe0b0b1-c33b-40f6-9617-b53562ecf4d7.gif)

**Source Code**
```
const ImGuiViewport* viewport = ImGui::GetMainViewport();
ImGui::SetNextWindowPos(viewport->WorkPos);
ImGui::SetNextWindowSize(viewport->WorkSize);
ImGui::SetNextWindowViewport(viewport->ID);
ImGuiWindowFlags window_flags = ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoDocking;
window_flags |= ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove;
window_flags |= ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus;

if (ImGui::Begin("Desktop", nullptr, window_flags))
{
	auto dockspace_id = ImGui::GetID("Desktop");
	if (ImGui::DockBuilderGetNode(dockspace_id) == false)
	{
		ImGui::DockBuilderRemoveNode(dockspace_id);
		ImGui::DockBuilderAddNode(dockspace_id, ImGuiDockNodeFlags_None);

		ImGuiID dock_main_id = dockspace_id;
		ImGuiID dock_up_id = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Up, 0.05f, nullptr, &dock_main_id);
		ImGuiID dock_right_id = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Right, 0.2f, nullptr, &dock_main_id);
		ImGuiID dock_left_id = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Left, 0.2f, nullptr, &dock_main_id);
		ImGuiID dock_down_id = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Down, 0.2f, nullptr, &dock_main_id);
		ImGuiID dock_down_right_id = ImGui::DockBuilderSplitNode(dock_down_id, ImGuiDir_Right, 0.6f, nullptr, &dock_down_id);

		ImGui::DockBuilderDockWindow("Actions", dock_up_id);
		ImGui::DockBuilderDockWindow("Hierarchy", dock_right_id);
		ImGui::DockBuilderDockWindow("Inspector", dock_left_id);
		ImGui::DockBuilderDockWindow("Console", dock_down_id);
		ImGui::DockBuilderDockWindow("Project", dock_down_right_id);
		ImGui::DockBuilderDockWindow("Scene", dock_main_id);

		// Disable tab bar for custom toolbar
		ImGuiDockNode* node = ImGui::DockBuilderGetNode(dock_up_id);
		node->LocalFlags |= ImGuiDockNodeFlags_NoTabBar;

		ImGui::DockBuilderFinish(dock_main_id);
	}
	ImGuiDockNodeFlags dockspace_flags = ImGuiDockNodeFlags_None;
	ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), dockspace_flags);
	ImGui::End();
}
```

**Comment by ocornut** [comment]
If you are using SDL 2.0.22+
Can you verify if your copy of imgui_impl_sdl.cpp has this fix ?
```
//  2022-09-26: Inputs: Disable SDL 2.0.22 new "auto capture" (SDL_HINT_MOUSE_AUTO_CAPTURE) which prevents drag and drop across windows for multi-viewport support + don't capture when drag and dropping. (#5710)
```
Otherwise try to update. Otherwise may be another issue!

**Comment by ChivenZhang** [comment]
> If you are using SDL 2.0.22+ Can you verify if your copy of imgui_impl_sdl.cpp has this fix ?
> 
> ```
> //  2022-09-26: Inputs: Disable SDL 2.0.22 new "auto capture" (SDL_HINT_MOUSE_AUTO_CAPTURE) which prevents drag and drop across windows for multi-viewport support + don't capture when drag and dropping. (#5710)
> ```
> 
> Otherwise try to update. Otherwise may be another issue!

Yes there is. Note that my testcase runs without ImGuiConfigFlags_ViewportsEnable tag and has used Dock Build API for arranged layout. It just contains 2 normal window in dockspace.

![image](https://user-images.githubusercontent.com/48938612/196567488-f017530e-4530-4e88-a48c-aec2055f57ca.png)

**Comment by yiivon** [comment]
@ChivenZhang I got the same issue
