### ISSUE TITLE
Error when ImGui sets glfw window position

### ISSUE THREAD

**Issue by AnnoyingB** [ocornut/imgui#5783]
I get an error on this line:
![image](https://user-images.githubusercontent.com/81764357/196030742-d6b2e02f-b06a-4631-bb46-a79e165ecca8.png)

Here is my code:
```
IMGUI_CHECKVERSION();
		ImGui::CreateContext();
		ImGuiIO& io = ImGui::GetIO(); (void)io;
		io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
		io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
		io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
		
		ImGui::StyleColorsDark();

		ImGui_ImplGlfw_InitForOpenGL((GLFWwindow*)window.get(), true);
		ImGui_ImplOpenGL3_Init("#version 410");

		window->Vsync(true);

		float lastTime = glfwGetTime();

		while (window->ShouldClose()) {
			Andromeda::Renderer::ClearCol(1, 0, 0, 1);

			ImGui_ImplOpenGL3_NewFrame();
			ImGui_ImplGlfw_NewFrame();
			ImGui::NewFrame();

			float delta = glfwGetTime() - lastTime;
			lastTime = glfwGetTime();

			{
				ImGui::Begin("Hello World!");
				ImGui::Text("beans");
				ImGui::End();
			}

			ImGui::Render();
			int display_w, display_h;
			glfwGetFramebufferSize((GLFWwindow*)window.get(), &display_w, &display_h);
			glViewport(0, 0, display_w, display_h);
			ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

			if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
				GLFWwindow* backupWindow = glfwGetCurrentContext();
				ImGui::UpdatePlatformWindows();
				ImGui::RenderPlatformWindowsDefault();
				glfwMakeContextCurrent(backupWindow);
			}

			sandbox->Update(delta);

			window->Poll();
		}

		ImGui_ImplOpenGL3_Shutdown();
		ImGui_ImplGlfw_Shutdown();
		ImGui::DestroyContext();
```

I built it into a lib if that could do anything to make it break.

**Comment by ocornut** [comment]
You need to specify which error and fill the exact issue template so we know eg which OS you are using.

**Comment by AnnoyingB** [comment]
I am running on windows, I am on the docking branch and I just get an error that says "exception thrown at ..."

**Comment by PathogenDavid** [comment]
@AnnoyingB A stack trace and the the full exception message would be helpful here. We can't just divine what's wrong with your program, especially when the code snippet provided is not self-contained.

**Comment by AnnoyingB** [comment]
![image](https://user-images.githubusercontent.com/81764357/196041675-92e0ad3a-d910-46a5-8f0e-07b121d5dfb2.png)

**Comment by PathogenDavid** [comment]
Looking at your screenshot it appears the call to `glfwCreateWindow` failed since `vd->Window` is null.

I'm not seeing an obvious reason it would be failing here.

If your engine is multi-threaded, make sure you aren't accessing the main window's OpenGL context from a different thread from the one where you call `ImGui::UpdatePlatformWindows`.

You should configure [a GLFW error callback](https://www.glfw.org/docs/latest/group__init.html#gaff45816610d53f0b83656092a4034f40) to get the error message. (See [`example_glfw_opengl3`'s usage](https://github.com/ocornut/imgui/blob/08752b372e5ebeb39adec59387590dac9d9e68f7/examples/example_glfw_opengl3/main.cpp#L31) for an example.)

**Comment by AnnoyingB** [comment]
![image](https://user-images.githubusercontent.com/81764357/196044351-7c670eba-5def-41ea-b150-1183b24e6d9a.png)

**Comment by PathogenDavid** [comment]
This appears to be the same as https://github.com/ocornut/imgui/issues/5687, which unfortunately didn't really have a resolution.

Does this issue happen with the official `example_glfw_opengl3` example?

Looking around the internet, it sounds like you probably just need to update your GPU drivers.

--------------------

Also screenshots of consoles make it harder for people to search. Copy+pasting the error for the sake of searchability:

> WGL: Failed to create OpenGL context

**Comment by AnnoyingB** [comment]
![image](https://user-images.githubusercontent.com/81764357/196045897-256cfe37-2e4e-4325-b9c6-1a690290108d.png)
it is up-to-date :\

**Comment by AnnoyingB** [comment]
it works in the example

**Comment by AnnoyingB** [comment]
this is my glfw init code:
```
		const GLFWvidmode* mode = nullptr;
		GLFWmonitor* monitor = nullptr;

		if (!glfwInit()) {
			const char* description; 
			glfwGetError(&description);
			printf(description);
			return false;
		}

		if (props->fullscreen) {
			mode = glfwGetVideoMode(monitor);
			monitor = glfwGetPrimaryMonitor();

			glfwWindowHint(GLFW_RED_BITS, mode->redBits);
			glfwWindowHint(GLFW_GREEN_BITS, mode->greenBits);
			glfwWindowHint(GLFW_BLUE_BITS, mode->blueBits);
		}

		if (props->api == 0) {
			glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
			glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
			glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

			Andromeda::Logger::Print("OpenGL 4.1", LogType::Info);
		}

		if (props->api == 1) {
			glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
			glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
			glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

			Andromeda::Logger::Print("OpenGL 3.3", LogType::Info);
		}

		glfwWindowHint(GLFW_DECORATED, props->decorated);

		window = glfwCreateWindow(mode ? mode->width : props->sizeX, mode ? mode->height : props->sizeY, props->title.data(), monitor ? monitor : nullptr, nullptr);
		if (!window) {
			const char* description;
			glfwGetError(&description);
			Andromeda::Logger::Print(description, LogType::Critical);
			return false;
		}

		// For ImGui
		glfwMakeContextCurrent(window);

		Andromeda::Logger::Print("Window made", LogType::Info);

		return true;
```

**Comment by AnnoyingB** [comment]
I fixed it. I had the class "Window" stored as a unique ptr witch glfw didn't like. I just had to make it a normal variable.
