### ISSUE TITLE
glfw: init doesn't fully swallow cursor errors as comment implies

### ISSUE THREAD

**Issue by mitchellh** [ocornut/imgui#5785]
**Version/Branch of Dear ImGui:**

Version: 1.88
Also Branch: master (08752b372e5ebeb39adec59387590dac9d9e68f7)

**Back-end/Renderer/Compiler/OS**

Back-ends: glfw (and opengl3 but irrelevant to this issue)
Operating System: NixOS aarch64 (irrelevant to this issue, though, except for X11 usage)

**My Issue/Question:**

Glfw initialization states in a comment that X11 may cause cursor errors, and that Imgui wants to swallow them (see: https://github.com/ocornut/imgui/blob/08752b372e5ebeb39adec59387590dac9d9e68f7/backends/imgui_impl_glfw.cpp#L472-L476). It does this by setting the error handler callback to null, then resetting it later. When X11 does cause cursor errors, unfortunately the error state is still available via `glfwGetError`, which may cause further issues.

For applications that do not use the error handling callback and use `glfwGetError` directly, this unfortunately still retains the last error code (even with a null callback). Therefore, the next successful call to glfw APIs that use `glfwGetError` after the call will still return an error.

This is extremely easy to workaround by calling `glfwGetError` directly after initialization, but I wanted to report this in case imgui wanted to handle this directly.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
    // Setup Dear ImGui context
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;

    // Setup Platform/Renderer backends
    ImGui_ImplGlfw_InitForOpenGL(window, true);

    // boom
    assert(glfwGetError(NULL) == GLFW_NO_ERROR);
```

Perhaps around here: https://github.com/ocornut/imgui/blob/08752b372e5ebeb39adec59387590dac9d9e68f7/backends/imgui_impl_glfw.cpp#L493 

We should add a throwaway call to `glfwGetError` to clear the error code (if exists).

**Comment by ocornut** [comment]
Hello, 
Pushed a fix ab6e48b as suggested. Function was added in GLFW 3.3 so it needs to be enclosed in an #if clause.
Thank you for reporting!
