### ISSUE TITLE
Creating textures for ImGui::Image

### ISSUE THREAD

**Issue by illegal-instruction-co** [ocornut/imgui#5786]
For ImGui image rendering, I'm wondering how I can create textures with https://github.com/microsoft/DirectXTex/.
Unfortunately the methods in the documentation don't work for me.

**Comment by ocornut** [comment]
Hello,
This isn't a dear imgui question but a question about DirectX or using DirectXTex, so we are not equipped to help you further than the examples we already provided in https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
