### ISSUE TITLE
A question about CollapsingHeader

### ISSUE THREAD

**Issue by FratexEn** [ocornut/imgui#5787]
I was wondering if it's possible to have two different collapsing headers with the same id on the two different places in the code and make them appear as one collapsing header.

```
if (ImGui::CollapsingHeader("name1"))
{
	ImGui::Text("1");
}

// Some other code 

if (ImGui::CollapsingHeader("name1"))
{
	ImGui::Text("2");
}
```
_How it looks now_
![image](https://user-images.githubusercontent.com/108738819/196257082-4cda55a3-714d-45bd-9237-54b947c3c7d0.png)

_How I would like it to look_
![image](https://user-images.githubusercontent.com/108738819/196257215-6db6b71d-d0e1-4ae7-abbe-851bb3a74651.png)

Version: v1,88
Branch: master
**glfw/opengl3/Win10**

**Comment by ocornut** [comment]
Hello,

We have an aptly called FAQ which answers your question:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-multiple-widgets-with-the-same-label
