### ISSUE TITLE
CollapsingHeader - close header

### ISSUE THREAD

**Issue by KozmoK** [ocornut/imgui#579]
Is it possible to close a Collapsing header section?

You have the ability for windows to collapse in this function:

   IMGUI_API void          SetWindowCollapsed(const char* name, bool collapsed, ImGuiSetCond cond = 0);

It would be nice to see a 

    IMGUI_API void          SetCollapsedHeader(const char* name, bool collapsed, ImGuiSetCond cond = 0);

The issue:

I would like to control the which headers are open, as to not get the menu scrolling far down.
In my situation they only need to be in one section at at time.

**Comment by ocornut** [comment]
Hello,

1.
CollapsingHeader are actually using part of the TreeNode code under the hood so this is working:

```
if (ImGui::Button("Open"))
    ImGui::SetNextTreeNodeOpened(true);
if (ImGui::Button("Close"))
    ImGui::SetNextTreeNodeOpened(false);
if (ImGui::CollapsingHeader("Help"))
{
```

It should probably be clarified.

2.
You can also directly access the storage map, e.g.

```
if (ImGui::Button("Open2"))
    ImGui::GetStateStorage()->SetInt(ImGui::GetID("Help"), 1);
if (ImGui::Button("Close2"))
    ImGui::GetStateStorage()->SetInt(ImGui::GetID("Help"), 0);

if (ImGui::CollapsingHeader("Help"))
{
```

3.
You might also use the `SetStateStorage` `GetStateStorage` facility to provide your own storage which you can clear independently.

4.
If you need custom behavior, you can copy and strip CollapsingHeader out of most of the code you don't need.. at the end of the day it is merely a glorified button accessing a boolean value from storage, but it may make more sense to provide the state yourself. Lots of the code in there you don't need if you write a customized version (handling tree nodes/header modes, calling TreeNodeBehaviorIsOpened to query from storage and honor calls to SetNextTreeNode functions, handling of Log).

**Comment by ocornut** [comment]
Just committed a bunch of TreeNode/CollapsingHeader related change, and the ImGuiTreeNodeFlags type along with the location and code of CollapsingHeader should make it much more obvious now that CollapsingHeader is just a helper calling TreeNode, and therefore that SetNextTreeNode* functions are functional. Closing this!
