### ISSUE TITLE
Is the Imgui's coordinate system based on Vulkan's NDC coordinate system?

### ISSUE THREAD

**Issue by GasimGasimzada** [ocornut/imgui#5792]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + custom Vulkan based backend (but the question is regarding other backends)
Compiler: MSVC and LLVM
Operating System: Windows, macOS

**My Issue/Question:**

Why do [Metal](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_metal.mm#L181), [WebGPU](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_wgpu.cpp#L298) and [DX12](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_dx12.cpp#L103) backends pass an orthographic projection matrix while the Vulkan backend [only passes translation and scale values](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_vulkan.cpp#L431). Is the ImGui coordinate system based on Vulkan's coordinate system?

I am trying to create a coordinate system in my custom render backen to match the ones in Metal, DX12, and WebGPU; and currently, with my Vulkan implementation where I use negative viewport to flip the viewport, the UI is flipped upside down.

**Source Code Example:**

```cpp
// In my imgui renderer
commandList.setViewport({0, 0}, {fbWidth, fbHeight}, {0.0f, 1.0f});

// In the plug and playable Vulkan backend
void VulkanCommandBuffer::setViewport(const glm::vec2 &offset,
                                      const glm::vec2 &size,
                                      const glm::vec2 &depthRange) {
  // Notice that the Y position starts from height and the height is flipped
  VkViewport viewport{offset.x, size.y - offset.y,       size.x,
                      -size.y,  depthRange.x, depthRange.y};

  mStats.addCommandCall();
}
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/807231/196446754-3b814564-e6f2-4b32-a4da-0db961ee1994.png)

**Comment by ocornut** [comment]
> Why do [Metal](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_metal.mm#L181), [WebGPU](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_wgpu.cpp#L298) and [DX12](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_dx12.cpp#L103) backends pass an orthographic projection matrix while the Vulkan backend [only passes translation and scale values](https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_vulkan.cpp#L431).

Those two things are equivalent.

Flip your UV coordinates or viewport if your thing is flipped.

**Comment by GasimGasimzada** [comment]
I am making my rendering abstraction to be similar to DX12's coordinate system and using the same orthographic projection defined for Metal, WebGPU, and DX12 solved my issue. This way, I won't need to change my shader even if the backend is not Vulkan.
