### ISSUE TITLE
Is there a better way to implement Split layout instead of using dockspacing?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#5793]
Just a Question: I want to implement automatic layout using json file specified. Most of control is easy to handle, according to tag in json and construct relative widget instance which contains imgui api. But It is difficult to wrap split layout using dockspace. Can you offer a better way to solve this problem ? Thank you.

![image](https://user-images.githubusercontent.com/48938612/196579053-750f41e6-8274-4a41-98b0-c45727719d8b.png)

**Comment by ChivenZhang** [comment]
I have solved it.

![image](https://user-images.githubusercontent.com/48938612/196623275-2d32ca90-ca91-4a64-9bcc-d6c63b2bf2b3.png)

**Comment by ocornut** [comment]
You didn't really describe your problem properly so it's difficult to learn/share anything about this.

**Comment by ChivenZhang** [comment]
> You didn't really describe your problem properly so it's difficult to learn/share anything about this.

I want to using json format to serialize/deserialize the layout like qml in QT. I were in trouble when handle dock layout. but now I had solved it. It's a problem of design not technology.
