### ISSUE TITLE
CI issue: Windows builds compiling twice

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#5795]
https://github.com/ocornut/imgui/actions/runs/3280260830/jobs/5400828504

If someone is familiar with CI and VS build it'd be nice to get a fix for this.
The build log of many examples suggest that files are compiled twice:

```
Build started 10/19/2022 9:19:21 AM.
Project "D:\a\imgui\imgui\examples\example_sdl_opengl3\example_sdl_opengl3.vcxproj" on node 1 (default targets).
InitializeBuildStatus:
  Creating "D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\example_.BBAEB705.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  All outputs are up-to-date.
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\CL.exe /c /I..\.. /I..\..\backends /I"D:\a\imgui\imgui\SDL2-devel-2.0.10-VC\SDL2-2.0.10\\include" /Iinclude\SDL2 /Zi /nologo /W4 /WX- /diagnostics:column /O2 /Oi /GL /D _MBCS /Gm- /EHsc /MD /GS- /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\\" /Fd"D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\vc142.pdb" /external:W4 /Gd /TP /FC /errorReport:queue ..\..\imgui.cpp ..\..\imgui_demo.cpp ..\..\imgui_draw.cpp ..\..\imgui_tables.cpp ..\..\imgui_widgets.cpp ..\..\backends\imgui_impl_opengl3.cpp ..\..\backends\imgui_impl_sdl.cpp main.cpp
  imgui.cpp
  imgui_demo.cpp
  imgui_draw.cpp
  imgui_tables.cpp
  imgui_widgets.cpp
  imgui_impl_opengl3.cpp
  imgui_impl_sdl.cpp
  main.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /ERRORREPORT:QUEUE /OUT:"D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\example_sdl_opengl3.exe" /NOLOGO /LIBPATH:"D:\a\imgui\imgui\SDL2-devel-2.0.10-VC\SDL2-2.0.10\\lib\x64" opengl32.lib SDL2.lib SDL2main.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\example_sdl_opengl3.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /LTCGOUT:"D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\example_sdl_opengl3.iobj" /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\example_sdl_opengl3.lib" /MACHINE:X64 D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\imgui.obj
  D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\imgui_demo.obj
  D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\imgui_draw.obj
  D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\imgui_tables.obj
  D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\imgui_widgets.obj
  D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\imgui_impl_opengl3.obj
  D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\imgui_impl_sdl.obj
  D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\main.obj
  Generating code
  Compiler switch has changed, fall back to full compilation.
  All 2113 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  example_sdl_opengl3.vcxproj -> D:\a\imgui\imgui\examples\example_sdl_opengl3\Release\example_sdl_opengl3.exe
```

I guess first step would be to see if this can be replicated locally (following scripts from https://github.com/ocornut/imgui/blob/master/.github/workflows/build.yml)

**Comment by PathogenDavid** [comment]
I haven't had my coffee yet so I might be missing something, but I'm not seeing anything being built twice unintentionally. Each example is intentionally built twice for x86 and x64. The only twiceness of the log snippet you shared is each file being listed separately for both compiling and linking.

**Comment by ocornut** [comment]
I was referring to those two lines:
```
  Compiler switch has changed, fall back to full compilation.
  All 2113 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
```
Emitted during linking?

**Comment by nicolasnoble** [comment]
This doesn't mean it's compiling twice. It means it's trying to do incremental compilation, realized it can't as there's no previous compilation artifacts, and just goes to do full compilation instead.

**Comment by PathogenDavid** [comment]
Yeah, that's expected. Every time CI runs it's running in a fresh VM that's never seen Dear ImGui before so it won't have any previously built artifacts.

There are [ways to cache things between builds](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows), but it's meant for things that take a **ton** of time. (IE: Optimizing a pipeline that takes 2 hours, not 10 minutes.) (It also explicitly doesn't work super great with how most C/C++ build systems do incremental compilation without extra work anyway.)

**Comment by ocornut** [comment]
> This doesn't mean it's compiling twice. It means it's trying to do incremental compilation, realized it can't as there's no previous compilation artifacts, and just goes to do full compilation instead.

If you mean "incremental linking" ? why referring to the word compilation in linking phase? isn't the message confusing them?

(Not expecting to further optimized but wanted to avoid double-compilation IF ANY, because the daily Windows build of fifty millions examples apps takes several minutes)

**Comment by nicolasnoble** [comment]
By default the compiler does link-time optimization in release mode, so link time is also compilation time :-)

**Comment by nicolasnoble** [comment]
(and yes, the message is horribly confusing)

**Comment by ocornut** [comment]
Closing this! Thanks!
