### ISSUE TITLE
Can I detect when ContextPopup is opened using IsItemActivated() ?

### ISSUE THREAD

**Issue by KRC2000** [ocornut/imgui#5799]
A general question from a newcomer. Following code is written in c#.
I was expecting that this code will print "Popup opened!" one time, when I open popup context menu with RMB. It doesn't happen.
The question is: Can I detect when ContextPopup is opened using IsItemActivated()? Can I detect when ContextPopup is opened using imgui method/tool or it is only possible to do that by yourself using bool flags that will track the popup status?
```
if (ImGui.BeginPopupContextItem())
{
     if (ImGui.IsItemActivated()) Console.WriteLine("Popup opened!");

     ImGui.Button("Button text");

     ImGui.EndPopup();
}
```

The only idea I had so far to detect when ContextPopup is opened using bool flags that will track the popup status:
```
bool previousStatus = currentStatus;
bool currentStatus = ImGui.BeginPopupContextItem();

if (currentStatus)
{
     ImGui.Button("Button text");

     ImGui.EndPopup();
}

if (currentStatus && !previousStatus) Console.WriteLine("Popup opened!");
```

**Comment by ocornut** [comment]
You may use IsWindowAppearing().

**Comment by KRC2000** [comment]
> You may use IsWindowAppearing().

Does exactly what I wanted, thank you for help and this great peace of open source software.
