### ISSUE TITLE
ImGui::TextWrapped window very narrow and long

### ISSUE THREAD

**Issue by kamelfanger83** [ocornut/imgui#5800]
I use Version 1.40 and the docking branch.

I use the glfw and opengl3 backends and am on windows.

If I create an ImGui window only containing TextWrapped and nothing else, when I start the program without a imgui.ini file (for the first time), that window is very narrow and extremely long. I think it wants to make the window only as narrow as it needs to be to fit the thing with the most width which is very little for TextWrapped. 

I am not sure whether this is intentional. Is this a bug or is there a recommended fix for this (other than just inserting something that is not TextWrapped in the window)? 

Here is a screenshot of what I mean:

![image](https://user-images.githubusercontent.com/71465612/196971023-6ac0809f-78e4-41a0-a006-78e69151e03e.png)
```
// Here's some code anyone can copy and paste to reproduce my issue
ImGui::Begin("Example Bug");
ImGui::TextWrapped("Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem.");
ImGui::End();
```

**Comment by PathogenDavid** [comment]
The width of a `TextWrapped` is based on the width of the window, and by default the width of the window is based on the contents.

As you might imagine this creates a conundrum in your case.

The easiest workaround is to set the window's size upon first use, IE:

```cpp
// (Specifying 0 for y means that the window will still be automatically sized vertically.)
ImGui::SetNextWindowSize(ImVec2(300.f, 0.f), ImGuiCond_FirstUseEver);
ImGui::Begin("Example Bug");
ImGui::TextWrapped("Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem.");
ImGui::End();
```

Another alternative depending on your app would be to change `ImGuiStyle::WindowMinSize` to something higher to prevent tiny windows in the first place.
