### ISSUE TITLE
Possible to create multiple host/os windows with sdl2 and opengl3

### ISSUE THREAD

**Issue by githubuser872349** [ocornut/imgui#5801]
hello
i am using version 1.88 and the docking branch.
i want to create multiple host/os windows with sdl2 and opengl3 in one application.
is there a way to implement this with the given imgui_impl sdl2 and opengl3 or do i have to change that in order to create multiple host/os windows.
i tried to create multiple windows but i got the error message "already initialized a platform backend".
from what i have red in the imgui backend code i think that it is currently layed out to support just one window.
am i right with that assumption? and in that case are you working on that feature?

**Comment by nicolasnoble** [comment]
Try the docking branch. It has the ability to create multiple windows.

**Comment by PathogenDavid** [comment]
Why do you want to manually create multiple of your own windows when you're using the docking branch?

If your goal is to have multiple windows rendered by your app, you should render to a framebuffer object and render that into a Dear ImGui window (using `ImGui::Image` or something similar.)

------------------

> from what i have red in the imgui backend code i think that it is currently layed out to support just one window.
> am i right with that assumption?

Generally speaking, yes.

You *can* have multiple app-owned windows if you use multiple contexts (call `ImGui::CreateContext` multiple times and switch between them with `ImGui::SetCurrentContext`.) However, this isn't recommended or well-tested and is known to have [some minor issues](https://github.com/ocornut/imgui/blob/de1593d5c00c136081eb415e5fe4e9a35954c578/backends/imgui_impl_sdl.cpp#L98-L101) with the SDL backend.

Additionally, each Dear ImGui context will be completely independent. You will not be able to dock windows from one context with windows from another.

**Comment by githubuser872349** [comment]
@PathogenDavid 
thanks for the quick answer.
i want to create multiple windows because the application should have multiple windows and the the host/os windows fit in with the style of the other application windows and they have better resize options than the imgui windows.
so `ImGui::CreateContext` is the only option that comes with imgui to fulfill that purpose?

**Comment by ocornut** [comment]
@githubuser872349 David's message says:
> Why do you want to manually create multiple of your own windows when you're using the docking branch?

See: https://github.com/ocornut/imgui/wiki/Multi-Viewports

**Comment by githubuser872349** [comment]
@ocornut
yes i know that you can create multiple imgui windows with the docking branch but the os/host windows would be better for my purpose.

**Comment by PathogenDavid** [comment]
> i want to create multiple windows because the application should have multiple windows and the host/os windows fit in with the style of the other application windows and they have better resize options than the imgui windows.

You can set `ImGuiIO::ConfigViewportsNoDecoration` to false.

To avoid double window decorations you can pass `ImGuiWindowFlags_NoDecoration` to `ImGui::Begin` and disable viewport auto-merge by setting `ImGuiIO::ConfigViewportsNoAutoMerge` to true.

All of this does not play nice with docking so you'll probably want to disable it by clearing `ImGuiConfigFlags_DockingEnable` from `ImGuiIO::ConfigFlags`.

---------

If you only want this behavior for some windows, you can use `ImGuiWindowClass`:

```cpp
ImGuiWindowClass windowClass;
windowClass.ClassId = ImGui::GetID("DecoratedWindow");
windowClass.ViewportFlagsOverrideClear = ImGuiViewportFlags_NoDecoration;
windowClass.ViewportFlagsOverrideSet = ImGuiViewportFlags_NoAutoMerge;
ImGui::SetNextWindowClass(&windowClass);
ImGui::Begin("GH-5801", nullptr, ImGuiWindowFlags_NoDocking | ImGuiWindowFlags_NoDecoration);
ImGui::Text("This is a test of the emergency broadcast system.");
ImGui::End();
```

Which results in a window which looks like this:

![Screenshot of the window resulting from the above code.](https://user-images.githubusercontent.com/278957/197267390-e78874eb-331c-40da-aead-b3a6f2029fa8.png)

**Comment by githubuser872349** [comment]
@PathogenDavid
thanks that is what i was looking for.
Why can't `GetID() `be used outside of `ImGui::NewFrame(); `?

**Comment by ocornut** [comment]
Because the result of GetID() depends on your location. See FAQ entry about the ID Stack.

**Comment by githubuser872349** [comment]
@ocornut 
ok thank you.

**Comment by githubuser872349** [comment]
i have one more question.
now that i have set right the window start to jump a short moment in the opposite direction when moving it, but then finally goes in the right direction. however this is really annoying.
i know that it is possible to disable the dragging in the inside of the window but i like that option and find it very useful.
is the reason of the jumping known ?
i have set the framerate to different values: 20,60,100 to test is but there is no difference.
when i use the tilebar instead of the window inside i can move it very smoothly.
