### ISSUE TITLE
How can I avoid the Moire effect when using imgui::Image to render 3d scene ?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#5806]
**My Issue/Question:**

Just A Question. I have rendered 3d scene texture and want to display it by image control, but I found serious Moire effect after I have done. So is there a better way to solved it? Thank you.
Note that I used a fixed texture dimension as big as the screen, and It displayed clearly without imgui::Image. I need help to keep both render equality and GUI expansibility.

**Screenshots/Video:**

After Using Image Control:
![image](https://user-images.githubusercontent.com/48938612/197177809-6ebc1ac1-ab1c-45c4-bfb6-648be1893ffc.png)

Before Using Image Control:
![image](https://user-images.githubusercontent.com/48938612/197178809-644fbec1-6b53-410e-902c-c0a2caa31387.png)

**Comment by ocornut** [comment]
Hello,
Unfortunately this question has nothing to do with dear imgui so we have to close. It's a graphics programming question.

We provide draw_list->AddCallback() functionality to facilitate passing information to your rendering backend shall you need to alter rendering state.

**Comment by ChivenZhang** [comment]
> Hello, Unfortunately this question has nothing to do with dear imgui so we have to close. It's a graphics programming question.
> 
> We provide draw_list->AddCallback() functionality to facilitate passing information to your rendering backend shall you need to alter rendering state.

I have enable mipmap in render and solve it. Thank you anyway.
