### ISSUE TITLE
How to display a video using ImGui?

### ISSUE THREAD

**Issue by dalvqw** [ocornut/imgui#5808]
Hi!
After loading the picture by ImGui::Image, I want to know how to load the GIF. I know I can split my video into several frames and display each frames one after the other but I haven't learned anything about opengl. So I encountered some problems that I couldn't solve by myself, I hope someone can provide relevant examples.

**Comment by ocornut** [comment]
This is not really a question related to Dear ImGui, I'll be closing that.

See #4751 #2680
