### ISSUE TITLE
Disable unconditional mouse capturing when dragging

### ISSUE THREAD

**Issue by Vennor** [ocornut/imgui#5810]
Version: 1.85

I'm building a game editor where I want to implement dragging entities from UI into the game world.

I'm already using drag & drop to move these entities between UI elements, implemented using the `BeginDragDropSource`, `BeginDragDropTarget`, `SetDragDropPayload` etc. functions.

I'd like to preserve this and also achieve the following:
1. when dragging and mouse pointer is over any UI element - only have the UI drag & drop popup;
2. when dragging and mouse pointer is over the game world - additionally have a game world preview of how the entity would look when created there.

I didn't dive into the internals but it looks like `BeginDragDropSource` is overriding `WantCaptureMouse` (and `WantCaptureMouseUnlessPopupClose`) and makes them `true` as long as dragging continues. I think that if I could disable this behavior I could do what I need. Is this currently possible maybe?

Alternatively, maybe there's another solution for my case that I'm missing?

**Comment by ocornut** [comment]
WantCaptureMouse & co are flags are Dear ImGui provide to you but we need use them internally, you are the only user of those variables.

If your app need to perform any filtering or advanced conditional based on additional state eg: drag&drop state you have everything that you need for that.

**Comment by Vennor** [comment]
That should work but I'm missing how to detect if the mouse pointer is over a window (or, the other way around, over void) during drag & drop. I tried `ImGui::IsWindowHovered(ImGuiHoveredFlags_AnyWindow)` but it's always `false` when dragging.

**Comment by ocornut** [comment]
> mouse pointer is over a window

Err that’s what WantCaptureMouse is for, use that.

**Comment by ocornut** [comment]
I am saying you are free to combine checking WantCaptureMouse value and Drag and Drop state and any other state to perform your inputs filtering.

**Comment by ocornut** [comment]
IsWindowHovered() has flags to allow detecting over by rectangle and omit input inhibition as well.

**Comment by Vennor** [comment]
> Err that’s what WantCaptureMouse is for, use that.

But that one is always true when dragging, even when the mouse pointer is not over a waindow, so not really.

> IsWindowHovered() has flags to allow detecting over by rectangle and omit input inhibition as well.

That would require me to store all window rectangles on my own, right?

**Comment by Vennor** [comment]
Ah, `ImGuiHoveredFlags_AllowWhenBlockedByActiveItem` seems to do the trick!

**Comment by Vennor** [comment]
For anyone who stumbles upon this question, here's what I did.

I normally consume mouse input when `WantCaptureMouseUnlessPopupClose == true` so that the game doesn't get it.

Now after the above I also check for `ImGui::GetDragDropPayload() != nullptr` and `ImGui::IsWindowHovered(ImGuiHoveredFlags_AnyWindow | ImGuiHoveredFlags_AllowWhenBlockedByActiveItem) == false`. If both are true I resign from consuming mouse input.

Thanks for pointing me in the right direction @ocornut!

**Comment by ocornut** [comment]
Excellent! Glad it works. 
Closing this!
