### ISSUE TITLE
Additional DragScalar, SliderScalar etc... helpers

### ISSUE THREAD

**Issue by Andersama** [ocornut/imgui#5815]
**My Issue/Question:**

Was looking through the codebase for a function to add some integer inputs, namely for a date/time control. Didn't have any luck finding one (if there is one, feel free to point to me towards it). In any case this lead me to try adding the DragInt / SliderInt functions which seemed fine.

Since I only wanted to bother with hours and seconds to start, I figured I should try DragInt2 and SliderInt2. These would otherwise work, except as I quickly realized, the minimum and maximum values are applied for all the sliders. Since I'm making a basic 24 hour timer control, I'd need two different min and max value pairs, 0-23 and 0-59. Since the underlying function appears to be taking the minimum and maximum as a pointer, it seems like a pretty small edit would make for some additional handy utility functions.

Consider for example:
```c
bool ImGui::SliderScalarNMM(const char* label, ImGuiDataType data_type, void* v, int components, const void* v_min, const void* v_max, const char* format, ImGuiSliderFlags flags)
{
    ImGuiWindow* window = GetCurrentWindow();
    if (window->SkipItems)
        return false;

    ImGuiContext& g = *GImGui;
    bool value_changed = false;
    BeginGroup();
    PushID(label);
    PushMultiItemsWidths(components, CalcItemWidth());
    size_t type_size = GDataTypeInfo[data_type].Size;
    for (int i = 0; i < components; i++)
    {
        PushID(i);
        if (i > 0)
            SameLine(0, g.Style.ItemInnerSpacing.x);
        value_changed |= SliderScalar("", data_type, v, v_min, v_max, format, flags);
        PopID();
        PopItemWidth();
        v = (void*)((char*)v + type_size);
        v_min = (const void*)((const char*)v_min + type_size); //like with the original data pointer, we bump these forward
        v_max = (const void*)((const char*)v_max + type_size);
    }
    PopID();

    const char* label_end = FindRenderedTextEnd(label);
    if (label != label_end)
    {
        SameLine(0, g.Style.ItemInnerSpacing.x);
        TextEx(label, label_end);
    }

    EndGroup();
    return value_changed;
}
```

Can't be sure because I didn't scour the codebase, but if there were functions which used different types for the minimum/maximum values compared to the input data type, that'd be a trivial edit, This also could be used to somewhat cheat the existing function's effect, provided there were a datatype entry purposefully added with `0` size. Although it'd probably be simplest to add some other condition and conditionally increment the pointers if needed. Maybe new `ImGuiSliderFlags_` value if possible.

Another consideration is possibly adding an additional parameter for a count of minimum / maximum pairs, and perhaps a flag for defaulting to the first or last set if for whatever reason there are less.

**Comment by ocornut** [comment]
Feels like it'd be simpler to not make it generic and do, e.g.

```cpp
bool SliderDayMonth(...)
{
   PushMultiItemsWidths(2, CalcItemWidth());
   SliderInt("##DD", &v[0], 1, 31);
   SameLine(0.0f, style.ItemInnerSpacing.x);
   PopItemWidth();
   SliderInt("##MM", &v[01, 1, 12);
   PopItemWidth();
}
SameLine(0.0f, style.ItemInnerSpacing.x);
TextUnformatted(label);
```

Regardless you'll probably want some special handling for number-of-day and a less-generic widget accordingly.

**Comment by ocornut** [comment]
`InputInt()` `InputFloat()` already shows arrows, thought to be fair we should probably change the left<>right arrow into up/down ones packed vertically.

**Comment by Andersama** [comment]
Seems like the `InputInt()` function doesn't have a min/max range, but I'm sure I'll get a few hours to edit it to what I need. So all good here.

**Comment by ocornut** [comment]
It wouldn't make sense to clamp while editing, but you can apply it after the edit using `if (IsItemDeactivatedAfterEdit())` or even simply always clamp the value while editing but it won't apply to the text edit box.
