### ISSUE TITLE
Custom Center() alignement-logic is unaffected by ImGui::SetCursorPos()

### ISSUE THREAD

**Issue by Shpendicus** [ocornut/imgui#5820]
**Version/Branch of Dear ImGui:**
1.87.3 Stable/master , using C# Binding.

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_187.cpp
Compiler: .NET 7/ C# (using binding)

**My Issue/Question:**
Hey ppl, I am pretty new to ImGui, I have actually so far made the effort to study the FAQ/ DemoWindow, (_forgive when I may ask indeed smth which already covered in the Demo, but its very large_ :/) was making a 2D puzzle game with a simple GUI for it, and I have an entire Game-Overlay window which is as large as the Game-Window on top of the GameWindow, (_for now its not hidden while I debug but ofc later it will be fully visible ofc_ )

I have written this code here to align my text always centered and keep it multilines if need  be:

` public static void Center(string text)
   {
        float winWidth = ImGui.GetWindowSize().X;
        float textWidth = ImGui.CalcTextSize(text).X;

        // calculate the indentation that centers the text on one line, relative
        // to window left, regardless of the `ImGuiStyleVar_WindowPadding` value
        float textIndentation = (winWidth - textWidth) * 0.5f;

        // if text is too long to be drawn on one line, `text_indentation` can
        // become too small or even negative, so we check a minimum indentation
        const float minIndentation = 20.0f;
        
        if (textIndentation <= minIndentation) 
            textIndentation = minIndentation;
        
        ImGui.SetCursorPosY(ImGui.GetContentRegionAvail().Y * 0.5f);   //--> does not make the text push begin at the middle-height of the window?
        ImGui.SameLine(textIndentation);
        ImGui.PushTextWrapPos(winWidth - textIndentation);
        ImGui.TextWrapped(text);
        ImGui.PopTextWrapPos();
  }`

Now I do not understand why that is, when I exchange the entire "Center(text)" function with **ImGui.Text("....")**  OR **ImGui.Label("ABC", "DEFG");** they both get affected by the  **ImGui.SetCursorPosY()** but not the stuff inside my function? 

Thx alot already for any comment on this :) 

XXX _(please provide as much context as possible)_

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/28008874/197836807-4599ed9d-0d51-413a-9aa1-118ab862c964.png)
![image](https://user-images.githubusercontent.com/28008874/197837011-daf3c5fb-9b93-450e-aee1-0f801a6c4440.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
//I made the actual C# code bit more like C++ so maybe its better to read for all of u:

// Here's some code anyone can copy and paste to reproduce your issue
if (ImGui::Begin("Example Bug  -  Screen Overlay")
{
        ImGui::SetWindowPos(default);           
        ImGui::SetWindowSize(GetScreenCoord());
                        
        ImGui::SetCursorPos(GetScreenCoord() * 0.5f);
        UIRenderer::Center("HELLO WORLD HOW ARE YOU TODAY");
        //ImGui::LabelText("TEST_ID", "TEST1 TEST2 TEST3");
ImGui::End();
```

I hope I provided enough infos on this, and I hope also, that I did not oversee the answer for my question in the demo window or the faq, but afaik, I looked carefully on those :)+

Have a good evening !

Shpendicus

**Comment by Shpendicus** [comment]
Note: Maybe some of you are surmising that its a possible bug in the C# binding, but I scratched one already out because, the imgui functions all are bullet tested and it works also perfectly fine for Imgui.Text() as well for Label() or ColoredText(), only somehow not before the custom logic in this case. or maybe other cases swell but for now idk.

**Comment by ocornut** [comment]
I am not sure I fully understand your problem, but why not using a single SetCursorPos() call instead of SetCursorPosY() + SameLine() ?

**Comment by Shpendicus** [comment]
> 
Very good question! Easy answer, because I am monkey sometimes! Thx man, it does what I want kekw....

**Comment by ocornut** [comment]
Also note a change in 1.88 (after your version):

```
- Layout: Fixed mixing up SameLine() and SetCursorPos() together from creating situations where line
  height would be emitted from the wrong location (e.g. 'ItemA+SameLine()+SetCursorPos()+ItemB' would
  emit ItemA worth of height from the position of ItemB, which is not necessarily aligned with ItemA).
```

SetCursorPos()+SameLine() in that order is however ill-defined or at least not what you expect. `SameLine()` needs to preserve the top-left position of the line rectangle and restore data from previous widgets, so SetCursorPos() is likely here to be ignored.

**Comment by Shpendicus** [comment]
> ...so SetCursorPos() is likely here to be ignored.

This is what I recognized, it will set Y always to StartPos() which is top-left , right?

Could it be an option to add:
ImGui::SameLine(Vector2) ?

**Comment by ocornut** [comment]
> This is what I recognized, it will set Y always to StartPos() which is top-left , right?

SameLine() will restore the previous line rectangle and set Y to the Y1 of that rectangle.
