### ISSUE TITLE
ImGui.PopStyleVar() crashes with code 139 after End()

### ISSUE THREAD

**Issue by Shpendicus** [ocornut/imgui#5821]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**
1.88/master/stable

**Back-end/Renderer/Compiler/OS**
.NET-7 RC2 / C#11 / ImGui.NET 

Back-ends: imgui_impl_1.88.cpp 

Operating System: macosx catalina 10.15.7

**My Issue/Question:**
When doing;

![image](https://user-images.githubusercontent.com/28008874/198039905-207e9865-9eb9-4f3c-b147-98f12560e938.png)

I have repositioned that function in all different positions, either before End() or after() or elsewhere, always same error code. and crash!

the Program crashes with exit code: 139 and no further informations are provided.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue

 ImGui.PushStyleVar(ImGuiStyleVar.WindowPadding, 0f);
            
            if (ImGui.Begin("Screen Overlay"))
            {
                ImGui.SetWindowPos(default);
                ImGui.SetWindowSize(new(1280, 
           }
  ImGui.End();
  ImGui.PopStyleVar();

```

Idk what could cause this.

**Comment by ocornut** [comment]
`ImGui.PushStyleVar(ImGuiStyleVar.WindowPadding, 0f);` is invalid, as WindowPadding is a ImVec2 you should be passing a imvec2/vector2.

Normally this would have asserted. It looks like your asserts are not enabled/visible which is going to make any use of Dear ImGui very tricky. You absolutely need to make sure that a native call to e.g. `IM_ASSERT()` is going to be visible when failing.

**Comment by Shpendicus** [comment]
Thanks mate!  yea the IM_ASSERT() is not implemented in the C# binding, I will have to discuss this with the owner of that binding.

**Comment by ocornut** [comment]
Yes, I strongly discourage ever using Dear ImGui without lib asserts on..

**Comment by Shpendicus** [comment]
I was wondering at the beginning, as if like "How am I able to understand what went wrong" xd but now it makes sense haha
