### ISSUE TITLE
Toggle buttons

### ISSUE THREAD

**Issue by Fearqueesha** [ocornut/imgui#5824]
I found these people online and they have these interesting toggle buttons I want, seen below. I tried adding the other round toggle buttons but I can't figure out how to make them square like in the picture. does anybody know how to make these or make ones similar? 
![image](https://user-images.githubusercontent.com/109046048/198161152-ea663761-4396-4071-b120-1aeb58589213.png)

**Comment by PathogenDavid** [comment]
See https://github.com/ocornut/imgui/issues/1537

**Comment by ocornut** [comment]
In the linked code, rendering calls to eg AddRectFilled() are specifying a rounding value.
