### ISSUE TITLE
Child border overriding rect and text

### ISSUE THREAD

**Issue by guikaua12** [ocornut/imgui#5827]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp.
Compiler: XXX
Operating System: Windows 11

**My Issue/Question:**

Hi, sorry if i'm being dumb, i'm trying to repeat [this](https://b.catgirlsare.sexy/H1OIfKgNBRZv.png), as you can see it seems to be a BeginChild() with border and a label. Ok, i got [this](https://b.catgirlsare.sexy/Zx2PImGDxf8o.png), as you can see (please zoom it), the child border is overriding the label, so i thougth of doing a `DrawList->AddRectFilled()` with background color, so this rect will override the border. Okay i did it, but the border is overriding the rect as you can see [here](https://b.catgirlsare.sexy/1E27bHK4hT7e.png), can you suggest anything i can do to solve that?

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
parent_window->DrawList->AddRectFilled(ImVec2(GetCursorPos().x + 20, GetCursorPos().y - 10), ImVec2((GetCursorPos().x + 20) + 50, (GetCursorPos().y - 10) + 20), ImColor(255,255,255));
ImGui::RenderText(ImVec2(ImGui::GetCursorPos().x + 20, ImGui::GetCursorPos().y - 10), "General");
```

**Comment by ocornut** [comment]
Hello,
You are not providing enough information about where each draw submission is done. You may not need a BeginChild() as all, but be mindful that child are rendered above parent, but child decorations are occasionally drawn in parent.
Anyhow, it may be simpler to not use BeginChild() border and draw the whole border yourself once you have decided on the shape.
And... I just realized I can close this as #1586.
