### ISSUE TITLE
How do I stop the ImGui window from moving when I move the application window?

### ISSUE THREAD

**Issue by PsychoCoffee** [ocornut/imgui#5839]
Version/Branch of Dear ImGui:

Version: 1.89 WIP
Branch: master

Back-end/Renderer/Compiler/OS

Back-ends:
.cpp: imgui.cpp, imgui_draw.cpp, imgui_impl_dx11.cpp, imgui_impl_win32.cpp, imgui_tables.cpp, imgui_widgets.cpp,
.h: imconfig.h, imgui.h, imgui_impl_dx11.h, imgui_impl_win32.h, imgui_internal.h, imstb_rectpack.h, imstb_textedit.h, imstb_truetype.h
Operating System: Windows 10

**My Issue/Question:**
So basically, when creating a new window it works perfectly, but whenever I move the actual application window around the screen, the ImGui window stays in that one place in the screen and doesn't move around with the application's window.
All the window flags I use:
ImGuiWindowFlags_NoDocking | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoScrollbar

**Screenshots/Video**

https://user-images.githubusercontent.com/89361918/198896375-b318639c-3dcf-4126-8d12-ef25eae74b0f.mp4

**Comment by ocornut** [comment]
It looks like you are not on master branch but on docking branch, with multi-viewports enabled, and you have code forcing the window position to an absolute position instead of using a position relative to the main viewport.

**Comment by PsychoCoffee** [comment]
Ohh I see! I fixed it by removing a config flag (forgot which one it was).
