### ISSUE TITLE
InputText output Chinese garbled characters

### ISSUE THREAD

**Issue by WeiduKe** [ocornut/imgui#5844]
I'm a rookie and ask for help.

![1](https://user-images.githubusercontent.com/86420844/199428354-da40a812-6284-4bb6-a3df-40eacc507656.png)
![2](https://user-images.githubusercontent.com/86420844/199428362-bca9901a-a3de-414e-8282-01f67bbbfebc.png)

**Comment by ocornut** [comment]
Sorry but #1586 
You didn’t fill issue template, didn’t explain your issue (your shot shows characters displayed correctly), didn’t read the FAQ and FONTS documents which should answer your question.
