### ISSUE TITLE
Any solution to disable gamepad toggle 

### ISSUE THREAD

**Issue by KsaNL** [ocornut/imgui#5848]
Version: 1.88
Branch: master
Back-ends: DirectX11
Operating System: Windows

I set every possible ImGuiWindowFlags in order to let a window can't toggle move by gamepad, but no use.
Maybe i missed any details after browse a lot of issues?
If somebody knows, i'll be deeply grateful!
```
// Any sample can
		ImGui::Begin("News", nullptr, 
			ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | 
			ImGuiWindowFlags_NoTitleBar | 
			ImGuiWindowFlags_NoBackground | 
			ImGuiWindowFlags_NoBringToFrontOnFocus |
			ImGuiWindowFlags_NoNav
		);
		ImGui::TextUnformatted("    >>>>>News<<<<<");
		ImGui::End();
```

**Comment by KsaNL** [comment]
Solved
```
10857 >> const bool start_windowing_with_gamepad = allow_windowing && !g.NavWindowingTarget && IsNavInputTest(ImGuiNavInput_Menu, ImGuiNavReadMode_Pressed) && !(g.NavWindow->Flags & ImGuiWindowFlags_NoNav);
```

**Comment by ocornut** [comment]
> && !(g.NavWindow->Flags & ImGuiWindowFlags_NoNav);

I don't think this check is correct, it prevents ever leaving the window for another.
If you want help you need to explain what you are trying to achieve and the reasons for it, otherwise we don't have enough context to aim for the best solution.

**Comment by KsaNL** [comment]
![image](https://user-images.githubusercontent.com/73447685/199783574-597c19e2-100d-43ed-97a8-919199ad11f1.png)

**Comment by KsaNL** [comment]
Edit at here better 
`g.NavWindowingTarget = (g.NavWindow->Flags & ImGuiWindowFlags_NoNav) ? NULL : g.NavWindowingTargetAnim = window->RootWindow;`
