### ISSUE TITLE
Assertion Failed stacked popup modal window->IDstack.Size > 1

### ISSUE THREAD

**Issue by irizkyw** [ocornut/imgui#5850]
every I click the modal popup button I get a crash.
![image](https://user-images.githubusercontent.com/78690451/199881183-cf924476-1679-4cad-b3a2-8b9f03bdb688.png)

im trying using code :

![image](https://user-images.githubusercontent.com/78690451/199881294-5f49537b-4275-4407-88f4-61a364c74a69.png)

**Comment by PathogenDavid** [comment]
You're missing a call to `ImGui::EndPopup`.

Here's an example of proper usage from the demo:

https://github.com/ocornut/imgui/blob/1eac0024c0ca7f4a903875794fbdfac0094e4228/imgui_demo.cpp#L3567-L3573
