### ISSUE TITLE
about ’os input method widget‘

### ISSUE THREAD

**Issue by take-off-lans** [ocornut/imgui#5851]
Version: v1.89 WIP
Branch: master
Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: msvc:vs2022
Operating System: windows 10

https://imgur.com/a/Qjug1l2

when we use 'multi-line text input' ,windows os always know exactly where the ’os input method widget‘ should be displayed,Even if I use the UP/DOWN keys to move the 'imgui blinking cursor', windows os still knows where to show the ’os input method widget‘.

I looked at the imgui_impl_win32.cpp content and I did not find any code about this content. This phenomenon is not caused by SetCursor and SetCursorPos.
SetCursorPos is not called when I use UP/DOWN to move the 'imgui blinking cursor'. Can someone explain to me: "How does windows os determine where to display the ’os input method widget‘"?

**Comment by vkedwardli** [comment]
In `imgui_impl_win32.cpp`'s `ImGui_ImplWin32_Init(void* hwnd)`, the window handle is stored:
```cpp
// Set platform dependent data in viewport
ImGui::GetMainViewport()->PlatformHandleRaw = (void*)hwnd;
```

Then in `ImGuiIO::ImGuiIO()`, imgui is providing a default implementation for the Windows IME
```cpp
SetPlatformImeDataFn = SetPlatformImeDataFn_DefaultImpl;
```

Finally this is the implementation:
```cpp
static void SetPlatformImeDataFn_DefaultImpl(ImGuiViewport* viewport, ImGuiPlatformImeData* data)
{
    // Notify OS Input Method Editor of text input position
    HWND hwnd = (HWND)viewport->PlatformHandleRaw;
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    if (hwnd == 0)
        hwnd = (HWND)ImGui::GetIO().ImeWindowHandle;
#endif
    if (hwnd == 0)
        return;

    ::ImmAssociateContextEx(hwnd, NULL, data->WantVisible ? IACE_DEFAULT : 0);

    if (HIMC himc = ::ImmGetContext(hwnd))
    {
        COMPOSITIONFORM composition_form = {};
        composition_form.ptCurrentPos.x = (LONG)data->InputPos.x;
        composition_form.ptCurrentPos.y = (LONG)data->InputPos.y;
        composition_form.dwStyle = CFS_FORCE_POSITION;
        ::ImmSetCompositionWindow(himc, &composition_form);
        CANDIDATEFORM candidate_form = {};
        candidate_form.dwStyle = CFS_CANDIDATEPOS;
        candidate_form.ptCurrentPos.x = (LONG)data->InputPos.x;
        candidate_form.ptCurrentPos.y = (LONG)data->InputPos.y;
        ::ImmSetCandidateWindow(himc, &candidate_form);
        ::ImmReleaseContext(hwnd, himc);
    }
}
```

So when imgui is passing `PlatformImeData` to `SetPlatformImeDataFn`, Windows would know where to draw the composition and candidate list

**Comment by take-off-lans** [comment]
> In `imgui_impl_win32.cpp`'s `ImGui_ImplWin32_Init(void* hwnd)`, the window handle is stored:
> 
> ```c++
> // Set platform dependent data in viewport
> ImGui::GetMainViewport()->PlatformHandleRaw = (void*)hwnd;
> ```
> 
> Then in `ImGuiIO::ImGuiIO()`, imgui is providing a default implementation for the Windows IME
> 
> ```c++
> SetPlatformImeDataFn = SetPlatformImeDataFn_DefaultImpl;
> ```
> 
> Finally this is the implementation:
> 
> ```c++
> static void SetPlatformImeDataFn_DefaultImpl(ImGuiViewport* viewport, ImGuiPlatformImeData* data)
> {
>     // Notify OS Input Method Editor of text input position
>     HWND hwnd = (HWND)viewport->PlatformHandleRaw;
> #ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
>     if (hwnd == 0)
>         hwnd = (HWND)ImGui::GetIO().ImeWindowHandle;
> #endif
>     if (hwnd == 0)
>         return;
> 
>     ::ImmAssociateContextEx(hwnd, NULL, data->WantVisible ? IACE_DEFAULT : 0);
> 
>     if (HIMC himc = ::ImmGetContext(hwnd))
>     {
>         COMPOSITIONFORM composition_form = {};
>         composition_form.ptCurrentPos.x = (LONG)data->InputPos.x;
>         composition_form.ptCurrentPos.y = (LONG)data->InputPos.y;
>         composition_form.dwStyle = CFS_FORCE_POSITION;
>         ::ImmSetCompositionWindow(himc, &composition_form);
>         CANDIDATEFORM candidate_form = {};
>         candidate_form.dwStyle = CFS_CANDIDATEPOS;
>         candidate_form.ptCurrentPos.x = (LONG)data->InputPos.x;
>         candidate_form.ptCurrentPos.y = (LONG)data->InputPos.y;
>         ::ImmSetCandidateWindow(himc, &candidate_form);
>         ::ImmReleaseContext(hwnd, himc);
>     }
> }
> ```
> 
> So when imgui is passing `PlatformImeData` to `SetPlatformImeDataFn`, Windows would know where to draw the composition and candidate list

You may have misunderstood me, I was asking "how does the current imgui_win32_impl do this", not "how does it"

**Comment by vkedwardli** [comment]
The current imgui_win32_impl do this by setting `ImGui::GetMainViewport()->PlatformHandleRaw`, just this single line only...

**Comment by ocornut** [comment]
Closing as answered. Thank you  @vkedwardli .
