### ISSUE TITLE
Viewports option will let window WindowRounding set  not take affect!!!

### ISSUE THREAD

**Issue by sxzxs** [ocornut/imgui#5852]
Version/Branch of Dear ImGui:

Version: 1.88
Branch: docking

Back-end/Renderer/Compiler/window

Back-ends: win32 + dx11
Operating System: Windows 10

My Issue/Question:
When imgui window out of win32 window,
Viewports option will let window WindowRounding set not take affect!!!
And the window transparency changes do not take effect

**Comment by ocornut** [comment]
Yes it isn’t supported.
