### ISSUE TITLE
How to get screen pos of the GLFW window in single viewport application?

### ISSUE THREAD

**Issue by AlfredXiaSF** [ocornut/imgui#5854]
**Version/Branch of Dear ImGui:**

Version: 1.89WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC
Operating System: Win11

**My Issue/Question:**

According to this [#4027](https://github.com/ocornut/imgui/issues/4027#issuecomment-816835763) and [#4590](https://github.com/ocornut/imgui/discussions/4590#discussioncomment-1392239), I Know that:
> About the coordinate system. Your main viewport origin are (0,0) if multi-viewports are disable, and match your OS desktop coordinates if multi-viewports are enabled. GetMainViewport()->Pos will give you coordinates of the main viewport.

>(0, 0) is at the top-left of your window for single viewport applications.
For multi-viewport applications (IE: on the docking branch), (0, 0) is the top-left of the primary monitor. Use ImGui::GetMainViewport() or ImGui::GetWindowviewport() to get the relevant viewport and use the Pos to get the top-left of the primary viewport.

 The main window is crated by GLFW in my application, how can i get the screen pos of this windows if multi-viewports are disable?

**Comment by ocornut** [comment]
You are asking a GLFW question:
https://www.glfw.org/docs/latest/window_guide.html#window_pos
There is a `glfwGetWindowPos()` function to do that.
