### ISSUE TITLE
Trying to make hotkey

### ISSUE THREAD

**Issue by Frouk3** [ocornut/imgui#5862]
**Version/Branch of Dear ImGui:**

Version: 1.76 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Compiler: Visual Studio Community 2022
Operating System: Windows 10
**My Issue/Question:**

```cpp
void KeyBind::Hotkey(const char* label, unsigned int* k) noexcept
{
	static bool waitingforkey = false;
	ImGui::TextUnformatted(label);
	ImGui::SameLine();
	char name[128];
	auto scanCode = MapVirtualKey(*k, MAPVK_VK_TO_VSC);
	switch (*k)
	{
	case VK_LEFT: case VK_UP: case VK_RIGHT: case VK_DOWN:
	case VK_RCONTROL: case VK_RMENU:
	case VK_LWIN: case VK_RWIN: case VK_APPS:
	case VK_PRIOR: case VK_NEXT:
	case VK_END: case VK_HOME:
	case VK_INSERT: case VK_DELETE:
	case VK_DIVIDE:
	case VK_NUMLOCK:
		scanCode |= KF_EXTENDED;
	default:
		GetKeyNameText(scanCode << 16, (LPSTR)name, 128);
	}
	if (!waitingforkey) {
		if (ImGui::Button((*k == 0) ? "None" : name))
			waitingforkey = true;
	}
	else
	{
		ImGui::Button("...");
		Sleep(20);
		for (auto& Key : KeyCodes)
		{
			if (ImGui::IsKeyPressed(VK_LBUTTON) || ImGui::IsKeyPressed(VK_RBUTTON) || ImGui::IsKeyPressed(VK_MENU) /* unexpected random alt presses */)
				continue;

			if (ImGui::IsKeyPressed(VK_ESCAPE))
			{
				*k = KeyCodes[0];
				waitingforkey = false;
				break;
			}

			if (ImGui::IsKeyPressed(Key)) {
				*k = Key;
				waitingforkey = false;
				break;
			}
		}
	}
}
```
So the problem is when i making re-bind for a key on the same tab item, it's access the first one (i have two hotkeys: Visor hotkey and Time Stop hotkey), when i'm trying to access to the second one, it still access to the first one(instead of changing Time Stop hotkey, its changing Visor Hotkey)

**Comment by ocornut** [comment]
Sorry but #1586

**Comment by rendere** [comment]
lmao how is that cheat related💀💀💀💀

**Comment by ocornut** [comment]
The rules (https://github.com/ocornut/imgui/blob/03d3343e215f78945d149621bd5655a95db59bfc/docs/CONTRIBUTING.md)
States: "If you are involved in cheating schemes (e.g. DLL injection) for competitive online multiplayer games, ..." and OP very clearly is if you check their profile. And I could guess it without even checking the profile given the contents of the posts. This specific population of users tends to ask the worst and laziest questions, vampirizing our time.

**Comment by aXXo-dev** [comment]
You took your time to check his Github profile page for any "hacking"-related repos to then send this answer?

**Comment by aXXo-dev** [comment]
> The rules (https://github.com/ocornut/imgui/blob/03d3343e215f78945d149621bd5655a95db59bfc/docs/CONTRIBUTING.md) States: "If you are involved in cheating schemes (e.g. DLL injection) for competitive online multiplayer games, ..." and OP very clearly is if you check their profile. And I could guess it without even checking the profile given the contents of the posts. This specific population of users tends to ask the worst and laziest questions, vampirizing our time.

You took your time to check his Github profile page for any "hacking"-related repos to then send this answer?

**Comment by K1lez** [comment]
> > The rules (https://github.com/ocornut/imgui/blob/03d3343e215f78945d149621bd5655a95db59bfc/docs/CONTRIBUTING.md) States: "If you are involved in cheating schemes (e.g. DLL injection) for competitive online multiplayer games, ..." and OP very clearly is if you check their profile. And I could guess it without even checking the profile given the contents of the posts. This specific population of users tends to ask the worst and laziest questions, vampirizing our time.
> 
> You took your time just to check his Github profile page for any "hacking"-related repos to then send this obnoxious answer?

Absolute insanity. "competitive online multiplayer games", such as? METAL GEAR RISING???!? GTA SAN ANDREAS?!?!
They aren't competitive online multiplayer games, not even multiplayer games.
The trainers he FORKED are just single-player games, mods for single-player games...
