### ISSUE TITLE
ImGui OpenGL 3 + My Backend with emscripten - Yandex Browser memory leak

### ISSUE THREAD

**Issue by InfiniteCoder01** [ocornut/imgui#5863]
**Version/Branch of Dear ImGui:**

Version: Commit 5728f2e15fe5354c84254cddcf1f01713c10374a
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imguiImpl.cpp _(Compiled with -D IMGUI_IMPL_OPENGL_ES2)_
Compiler: em++
Operating System: Windows/YandexBrowser

**My Issue/Question:**

As soon as I open webpage (Using live server vs code extension), I have 1-3 sec before yandex browser reloads the page and tells me that I have not enough memory.
I've tested it with Microsoft Edge and UR Browser, but it only occurs with yandex browser

Mova (Develop Branch): https://github.com/InfiniteCoder01/Mova

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
#include <Mova.h>

int main(int argc, const char** argv) {
  MvWindow window("Ore Asset Editor", openGLRenderer);
  renderer->defaultShader();

  ImGui_ImplMova_Init();

  while (true) {
    ImGui_ImplMova_NewFrame();
    ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());

    ImGui::ShowDemoWindow();

    ImGui::Render();
    renderer->clear(Color::darkgray);
    ImGui_ImplMova_Render();
    Mova::nextFrame();
  }

  ImGui_ImplMova_Shutdown();
  return 0;
}
```

**Comment by ocornut** [comment]
You are asking us to debug your code or debug Yandex browser. We cannot do that sorry.

**Comment by InfiniteCoder01** [comment]
Also, Everything works if I comment ImGui::Render();

**Comment by ocornut** [comment]
Then comment it ;)

Render() only allocates to grow buffers which are amortized and rarely allocate on subsequent frames. It is unlikely to be the issue.
