### ISSUE TITLE
Missing ImGuiKey_ named values for many ASCII graphic characters.

### ISSUE THREAD

**Issue by lindseyspratt** [ocornut/imgui#5865]
The ImGuiKey_ enum has named values for many common ASCII characters. E.g. '-' is ImGuiKey_Minus. There are many ASCII 'graphic' characters that are not named. Some of these are:
```
!@#$%^&*()_+<>?{}
```

Many of these unnamed graphic characters (e.g. '>', '<') are used in menu item shortcuts and it seems that the named ImGuiKey_ constants are intended to support shortcuts.

**Comment by lindseyspratt** [comment]
This issue is not a problem.

I misunderstood the distinction between 'key' (from a keyboard) and 'character'. For instance,  the 1 key has the '!' as an alternative (with shift). All of the common keyboard keys are covered by the named ImGuiKey_ enums.

**Comment by ocornut** [comment]
That distinction is correct and important.

However, in the case of shortcuts (while holding modifier keys) we don’t receive characters and need to rely on key data, so it may be difficult to support shortcuts with translated keys. This was actually one of the reason we delayed populating that enum for years…
