### ISSUE TITLE
`ImGui::PushStyleColor` not working for ImageButton

### ISSUE THREAD

**Issue by CybernetHacker14** [ocornut/imgui#5868]
**Version/Branch of Dear ImGui:**

Version: 1.89 beta
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_dx11.cpp
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

I have an image button, and I am doing 3 color changes for the button, namely `ImGuiCol_Button`, `ImGuiCol_ButtonHovered` and `ImGuiCol_ButtonActive` using `ImGui::PushStyleColor()` and also doing `ImGui::PopStyleColor()` after the button code. However, only one of the style is rendered on the screen - the color set for `ImGuiCol_Button` style.

In the image posted below, you can see that no color is depicted when cursor is hovered over the button

**Screenshots/Video**

![Screenshot_1](https://user-images.githubusercontent.com/26383905/200368965-7801973c-4b2e-49b2-8664-b5823030308f.png)

**Standalone, minimal, complete and verifiable example:**
```
ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.0f, 0.0f, 0.0f, 0.0f));
ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0.24f, 0.24f, 0.24f, 0.0f));
ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0.91f, 0.1f, 0.15f, 0.0f));
if (ImGui::ImageButton("Close", (ImTextureID)Sentinel::Texture2DAPI::GetResource(m_CloseTex), {20, 20})) {
    m_Window->SecondaryShutdown();
}
ImGui::PopStyleColor(3);
```

I am also posting the code commit pertaining to this issue - [commit e05cd8edab94a76ed2191a386ffc7a908a62a86f](https://github.com/CybernetHacker14/Sentinel/commit/e05cd8edab94a76ed2191a386ffc7a908a62a86f)

**Comment by PathogenDavid** [comment]
You are setting the alpha to 0 for all three colors which makes it effectively no color at all.

**Comment by ocornut** [comment]
Closing as answered. Alpha = 0.0f indeed effectively means the color won't be seen.
