### ISSUE TITLE
Window Text Cutting Off

### ISSUE THREAD

**Issue by xSellix777** [ocornut/imgui#5872]
When I try to make my text go past the end of the window, it just cuts off. I have tried looking on google for almost 2 hours and tried everything I know. I just want it like in the image. sorry if its easy but I'm just lost. 
![image](https://user-images.githubusercontent.com/114774765/200469619-943807ae-df89-41bb-a4e0-b86a502d76d5.png)

**Comment by ocornut** [comment]
Didn't follow any of the requested guidelines or issue template, unfortunately we can't really afford the time/energy to help you.
