### ISSUE TITLE
Programmatically setup Multiple Viewports

### ISSUE THREAD

**Issue by r2d2Proton** [ocornut/imgui#5873]
**Version/Branch of Dear ImGui:**
Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS:**
Back-ends: imgui_impl_win32/imgui_impl_dx12
Visual Studio 2022
Operating System: Windows 11

**My Issue/Question:**
First, thank you for making this available to the public. It looks really nice.
I am trying to create viewports programmatically. I am uncertain of the setup, and I believe I may be doing a lot of work that may already be done. In my main loop I am performing the following:

```
// Start the Dear ImGui frame
ImGui_ImplDX12_NewFrame();
ImGui_ImplWin32_NewFrame();
ImGui::NewFrame();

ImGuiContext* pImGuiContext = ImGui::GetCurrentContext();
if (pImGuiContext != nullptr)
{
    for (ImVector<ImGuiViewportP*>::iterator itr = pImGuiContext->Viewports.begin(); itr != pImGuiContext->Viewports.end(); ++itr)
    {
        ImGuiViewportP* viewport = *itr;
        ImGui::SetCurrentViewport(nullptr, viewport);
        OnGUI(pAppData->stepTimer);
    }
}

ImGui::Render();
```

During the OnGUI part of the code I am trying to render into the viewports:
```
void OnGUI(StepTimer const& stepTimer)
{
    MainMenu();
    :
}

void MainMenu()
{
    string title = "Window Title";
    ImGui::PushFont(pFont);

    ImGuiStyle style = ImGui::GetStyle();
    ImVec4* pColors = style.Colors;
    ImGui::PushStyleColor(ImGuiCol_TitleBg, pColors[ImGuiCol_MenuBarBg]);
    ImGui::PushStyleColor(ImGuiCol_TitleBgActive, pColors[ImGuiCol_MenuBarBg]);
    ImGui::PushStyleColor(ImGuiCol_TitleBgCollapsed, pColors[ImGuiCol_MenuBarBg]);

    if (ImGui::BeginMainMenuBar(title.c_str()))
    {
        FileMenu();
        ViewportMenu();
        :
        ImGui::EndMainMenuBar();
    }
    ImGui::PopStyleColor(3);
    ImGui::PopFont();
}

void ViewportMenu()
{
    if (ImGui::BeginMenu("Viewport"))
    {
        if (ImGui::MenuItem("Add Viewport"))
        {
            AddViewport();
        }
        ImGui::EndMenu();
    }
}
```

At the time of creating a new viewport I can force the main_viewport to half screeen. And it does work but I am not sure of the way I am doing so:
```
void GUIManager::AddViewport()
{
    ImGuiViewportP* main_viewport = (ImGuiViewportP*)ImGui::GetMainViewport();

    ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();
    platform_io.Platform_SetWindowPos(main_viewport, ImVec2(0.0f, 0.0f));
    platform_io.Platform_SetWindowSize(main_viewport, ImVec2(1920.0f, 540.0f));
    platform_io.Renderer_SetWindowSize(main_viewport, ImVec2(1920.0f, 540.0f));
   :
}
```
And here is where it gets interesting. Creating the viewport doesn't appear to be straightforward:
```
    ImGuiViewportP* viewport = new ImGuiViewportP();
    *viewport = *main_viewport;

    viewport->ID = main_viewport->ID + 1;
    viewport->Pos = ImVec2(0.0f, 540.0f);
    viewport->Size = ImVec2(1920.0f, 540.0f);
    viewport->Flags = main_viewport->Flags;
    viewport->DpiScale = main_viewport->DpiScale;
    viewport->Alpha = main_viewport->Alpha;
    viewport->LastAlpha = main_viewport->LastAlpha;

    platform_io.Platform_CreateWindow(viewport);
    platform_io.Platform_SetWindowSize(viewport, ImVec2(1920.0f, 540.0f));
    platform_io.Platform_SetWindowPos(viewport, ImVec2(0.0f, 540.0f));

    ImGuiContext* pImGuiContext = ImGui::GetCurrentContext();
    viewport->Window = new ImGuiWindow(pImGuiContext, "Viewport");
    viewport->Window->Pos = ImVec2(0.0f, 0.0f);
    viewport->Window->Size = ImVec2(1920.0f, 540.0f);
    viewport->Window->Active = true;
    viewport->Window->Hidden = false;

    platform_io.Platform_ShowWindow(viewport);
    platform_io.Platform_UpdateWindow(viewport);
    platform_io.Renderer_CreateWindow(viewport);
    platform_io.Renderer_SetWindowSize(viewport, ImVec2(1920.0f, 540.0f));

    if (pImGuiContext != nullptr)
        pImGuiContext->Viewports.push_back(viewport);
}
```
And back in the main loop shown above the iteration of the newly added viewport goes through the motions but no ImGui widgets are displayed.

A few things I did note is that viewport[0] does not need to have the Window. All others do.
There are a few static functions relating to viewports but are not publically exposed:
```
static ImGuiViewportP*  AddUpdateViewport(ImGuiWindow* window, ImGuiID id, const ImVec2& platform_pos, const ImVec2& size, ImGuiViewportFlags flags);
static void             DestroyViewport(ImGuiViewportP* viewport);
static void             UpdateViewportsNewFrame();
static void             UpdateViewportsEndFrame();
static void             WindowSelectViewport(ImGuiWindow* window);
:
```

Is my approach above correct?
Is there a simpler way to create a new viewport?

The final part of the loop deals with the main_viewport D3DDevice, Descriptor Heaps, Command Queue, Command List, Fence, Swap Chain, which is kept separately for each created viewport in the ImGui_ImplDX12_Data structure.

By chance, do you have any code that shows how you are doing this?

Thank you in advance for your help.

**Comment by ocornut** [comment]
> I am trying to create viewports programmatically. 
[...]

Why ?
Our first question is always to be going a why, because many of those end up being [XY Problems](https://xyproblem.info/).

> Is my approach above correct?
> Is there a simpler way to create a new viewport?
[...]

The whole thing appears to be very bizarre to me and I don't understand what you are trying to achieve.
Creating any Dear ImGui window with `Begin()` should always create a viewport if necessary.

**Comment by r2d2Proton** [comment]
Thank you for the reply. There are several reasons. 
How do I perform a Begin() for a new viewport? I could certainly do so.
Begin returns a bool, which has limited use.

```
if (Begin(...))
{
    ImGuiContext* context = ImGui::GetCurrentContext();
    ImGuiViewportP* viewport = (ImGuiViewportP*)ImGui::GetCurrentViewport();
   :
   ImGuiWindowP* window = ImGui::GetCurrentWindow();
   viewport = window->Viewport;
   viewport->Pos = ...;
   viewport->Size = ...;
   window->Pos = ...;
   window->Size = ...;
}
```
It is certainly easy enough to replace the ImGuiPlatformIO with my own functions:
```
ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();
platform_io.Platform_CreateWindow = ImGuiCreateWindow;
platform_io.Platform_DestroyWindow = ImGuiDestroyWindow;
platform_io.Platform_ShowWindow = ImGuiShowWindow;
:
platform_io.Platform_GetWindowDpiScale = ImGuiGetWindowDpiScale;
platform_io.Platform_OnChangedViewport = ImGuiOnChangedViewport;
:
platform_io.Renderer_CreateWindow = ImGuiDX12CreateWindow;
```
And change the dwStyle, dwExStyle, wndclass, and wndproc. Two comments, the structs are private and it is necessary to duplicate them or make changes to the source:
```
struct ImGui_ImplWin32_Data
{
    HWND                        hWnd;
    :
};

struct ImGui_ImplWin32_ViewportData
{
    HWND    Hwnd;
    :
};
```
And the window style I like to set to none:
```
    // remove all Window styles
    ::SetWindowLongA(hWnd, GWL_STYLE, 0);
};
```
Also, I did change to WNDCLASSEXA, CreateWindowExA, and DefWindowProcA versions of the Win32 API. It is worth noting the I do compile with /std:c++latest, /std:c17, and /utf-8.

I am interested to see if the SetWindowTitleA behaves without the MultiByteToWideChar call.

**Comment by ocornut** [comment]
> How do I perform a Begin() for a new viewport? I could certainly do so.

Just call Begin().... there's nothing else to do.
It creates a viewport if it needs to, aka if not fully contained within an existing host window).

If you absolutely need every Begin() to create its own viewport (which lends itself to the question WHY).
```
ImGuiWindowClass window_class;
window_class.ViewportFlagsOverrideSet = ImGuiViewportFlags_NoAutoMerge;
ImGui::SetNextWindowClass(&window_class);
ImGui::Begin(....);
```

I still can't understand any of your explanation about what you are trying to achieve and what you are not achieving by calling `Begin()`. Please try to explain not in terms of what you believe is a possible solution, but in terms of what you are trying to achieve.

**Comment by PathogenDavid** [comment]
> How do I perform a Begin() for a new viewport?

You can just create a window outside of the main viewport and Dear ImGui will spawn a viewport for it.

> Also, I did change to WNDCLASSEXA, CreateWindowExA, and DefWindowProcA versions of the Win32 API. It is worth noting the I do compile with /std:c++latest, /std:c17, and /utf-8.
>
> I am interested to see if the SetWindowTitleA behaves without the MultiByteToWideChar call.

You should not do this, internally Windows is just widening the characters for you and even if it wasn't this is an egregiously unnecessary micro-optimization. The A-suffixed functions/structures use the system codepage when your application isn't manifested for UTF-8, which is not what `/utf-8` enables. Using the UTF-8 codepage is primarily meant for localizing legacy applications and porting.

**Comment by r2d2Proton** [comment]
I am trying to position and resize the main_viewport to be just the top half of the display (any size and position is the target).
Then I am trying to display a new viewport in bottom of of the display, and display the widgets:
```
void AddViewport()
{
    ImGuiWindowFlags windowFlags = ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize;
    if (ImGui::Begin("##HiddenWindow", nullptr, windowFlags))
    {
        ImGuiViewportP* main_viewport = (ImGuiViewportP*)ImGui::GetMainViewport();
        main_viewport->Pos = ImVec2(0.0f, 0.0f);
        main_viewport->Size = ImVec2(1920.0f, 540.0f);

        ImGuiWindow* window = ImGui::GetCurrentWindow();
        ImGuiViewportP* viewport = (ImGuiViewportP*)window->Viewport;
        viewport->Pos = ImVec2(0.0f, 540.0f);
        viewport->Size = ImVec2(1920.0f, 540.0f);

        ImGui::End();
    }
}
```
Ideally all viewports should be movable and sizeable. Similar to the D3D12_VIEWPORT.

**Comment by ocornut** [comment]
> I am trying to position and resize the main_viewport to be just the top half of the display (any size and position is the target).

This problem normally has nothing to do with Dear ImGui, it's a thing in your app, you can call Windows's API `SetWindowPos()` etc. (https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos)

However, as you found out because our backend need to wrap those things up, you can use `platform_io.Platform_SetWindowPos()` to perform the same function in a backend-generic manner.

> Then I am trying to display a new viewport in bottom half of the display, and display the widgets:

If by "display" you mean monitor/platform display, you can use `platform_io.Monitors[0]`'s `Pos/Size` or `WorkPos/WorkSize`.
If by "display" you mean you main viewport mentioned above, you can use GetMainViewport()'s `Pos/Size` or `WorkPos/WorkSize`.

```cpp
ImVec2 display_pos = GetPlatformIO().Monitors[0].WorkPos;
ImVec2 display_size = GetPlatformIO().Monitors[0].WorkSize;
ImGui::SetNextWindowPos(ImVec2(display_pos.x, display_pos.y + display_size.y * 0.5f));
ImGui::SetNextWindowSize(ImVec2(display_size.x, + display_size.y * 0.5f));
ImGui::Begin(.....);
....
```

You should never have to use `ImGuiViewportP` and other private stuff.

**Comment by r2d2Proton** [comment]
Currently I have:
```
    ImGuiWindowFlags windowFlags = ImGuiViewportFlags_IsPlatformWindow
                                 | ImGuiViewportFlags_NoDecoration
                                 | ImGuiViewportFlags_NoTaskBarIcon
                                 | ImGuiViewportFlags_NoAutoMerge
                                 | ImGuiViewportFlags_CanHostOtherWindows
                                 | ImGuiWindowFlags_MenuBar
                                 | ImGuiWindowFlags_NoCollapse
                                 | ImGuiWindowFlags_NoResize;

    if (ImGui::Begin("##HiddenWindow", nullptr, windowFlags))
    {
        ImGuiViewportP* main_viewport = (ImGuiViewportP*)ImGui::GetMainViewport();
        main_viewport->Pos = ImVec2(0.0f, 0.0f);
        main_viewport->Size = ImVec2(1920.0f, 540.0f);

        ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();
        platform_io.Platform_SetWindowPos(main_viewport, ImVec2(0.0f, 0.0f));
        platform_io.Platform_SetWindowSize(main_viewport, ImVec2(1920.0f, 540.0f));
        platform_io.Renderer_SetWindowSize(main_viewport, ImVec2(1920.0f, 540.0f));

        ImGuiWindow* window = ImGui::GetCurrentWindow();
        ImGuiViewportP* viewport = (ImGuiViewportP*)window->Viewport;
        viewport->Pos = ImVec2(0.0f, 540.0f);
        viewport->Size = ImVec2(1920.0f, 540.0f);

        platform_io.Platform_SetWindowPos(viewport, ImVec2(0.0f, 540.0f));
        platform_io.Platform_SetWindowSize(viewport, ImVec2(1920.0f, 540.0f));
        platform_io.Renderer_SetWindowSize(viewport, ImVec2(1920.0f, 540.0f));

        ImGui::End();
    }
```

The call to the (original) Platform code does change the main_viewport. I will try what you provided above. . .

**Comment by PathogenDavid** [comment]
In addition to what Omar said:

> Ideally all viewports should be movable and sizeable. Similar to the D3D12_VIEWPORT.

Dear ImGui viewports are not the same as Direct3D's viewports. Dear ImGui viewports are simply operating system windows.

-----------

It would be helpful to know what sort of user experience you're trying to create.

**Comment by r2d2Proton** [comment]
And a nearly complete D3D pipeline objects:
```
struct ImGui_ImplDX12_Data
{
    ID3D12Device*               pd3dDevice;
    ID3D12RootSignature*        pRootSignature;
    ID3D12PipelineState*        pPipelineState;
    DXGI_FORMAT                 RTVFormat;
    ID3D12Resource*             pFontTextureResource;
    D3D12_CPU_DESCRIPTOR_HANDLE hFontSrvCpuDescHandle;
    D3D12_GPU_DESCRIPTOR_HANDLE hFontSrvGpuDescHandle;
    ID3D12DescriptorHeap*       pd3dSrvDescHeap;
    UINT                        numFramesInFlight;
};
```
One creates the device:
```
D3D12CreateDevice(NULL, featureLevel, IID_PPV_ARGS(&pd3dDevice))
```
The backend shares it, along with the number of back buffers, DXGI_FORMAT, CBV_SRV_HEAP, and descriptor handles.

**Comment by r2d2Proton** [comment]
> It would be helpful to know what sort of user experience you're trying to create.

As noted above, upon command (pragmatically) I am trying to resize the current viewport, which is the main_viewport, to a different size and position on the current display. Then create another viewport with a different size and position, and render the GUI and other items into it.

Eventually I will manage which monitors is being used. It should be flexible enough to control which monitor is being used.

**Comment by ocornut** [comment]
I'm giving up on this since, you are ignoring our requests, being obtuse about what you are trying to do and bringing topics which seems completely unrelated.

**Comment by r2d2Proton** [comment]
That is completely false. Give up if you want. Nothing I stated would be construed as hard to understand.
Actually, this should be trivial to do. And a simple example demonstrating how to do so helpful to many people.
If my reworked setup above is the approach you would take the new window viewport is using the main_viewport (0x11111111). It is not creating a new viewport, which what I was expecting it to do.

**Comment by ocornut** [comment]
The answer to "Programmatically setup Multiple Viewports" is to call `SetNextWindowPos()`+`SetNextWindowSize()`+`Begin()` which we already answered.

You aren't explaining why didn't doesn't satisfy you and showering us with extraneous information related to potentially misinformed digging which is number 1 exhibit of a [XY Problem](https://xyproblem.info). It's real difficult to untangle your intent and actual core problem from this.

**Comment by r2d2Proton** [comment]
In the main loop (mostly as your original code) I start the ImGui frame with:
```
// Start the Dear ImGui frame
ImGui_ImplDX12_NewFrame();
ImGui_ImplWin32_NewFrame();
ImGui::NewFrame();
```
Then I loop through the viewports to display my ImGui widgets in:
```
ImGuiContext* pImGuiContext = ImGui::GetCurrentContext();
if (pImGuiContext != nullptr)
{
    for (ImVector<ImGuiViewport*>::iterator itr = pImGuiContext->Viewports.begin(); itr != pImGuiContext->Viewports.end(); ++itr)
    {
        ImGuiViewport* viewport = *itr;
        ImGui::SetCurrentViewport(nullptr, viewport);
        OnGUI(pAppData->stepTimer);
}
```
I am expecting the main_viewport to already be established.
Let ImGui know which viewport I want to add widgets to (render in), hence the call to SetCurrentViewport.
The OnGUI code displays the menu and other widgets. Nothing is changing the viewport (at least not intentionally).

A menu option is there to AddViewport, which should resize the current viewports and create another one sized and positioned accordingly.

The AddViewport code is now:
```
ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();

ImGuiViewport* main_viewport = ImGui::GetMainViewport();

platform_io.Platform_SetWindowPos(main_viewport, ImVec2(0.0f, 0.0f));
platform_io.Platform_SetWindowSize(main_viewport, ImVec2(1920.0f, 540.0f));
platform_io.Renderer_SetWindowSize(main_viewport, ImVec2(1920.0f, 540.0f));

ImVec2 display_pos(1920.0f, 540.0f);
ImVec2 display_size(1920.0f, 540.0f);
ImGui::SetNextWindowPos(display_pos);
ImGui::SetNextWindowSize(display_size);

ImGuiWindowFlags windowFlags = ImGuiViewportFlags_IsPlatformWindow
                                 | ImGuiViewportFlags_NoDecoration
                                 | ImGuiViewportFlags_NoTaskBarIcon
                                 | ImGuiViewportFlags_NoAutoMerge
                                 | ImGuiViewportFlags_CanHostOtherWindows
                                 | ImGuiWindowFlags_MenuBar
                                 | ImGuiWindowFlags_NoCollapse
                                 | ImGuiWindowFlags_NoResize;

if (ImGui::Begin("##HiddenWindow", &pAppData->isOpen, windowFlags))
{
    ImGui::End();
}
```
Back in the main loop, it appears that the new window is not added to ImGuiContext::Viewports. The intent with the code is to pickup the newly created viewport, select it, and render the OnGUI widgets:

```
for (ImVector<ImGuiViewport*>::iterator itr = pImGuiContext->Viewports.begin(); itr != pImGuiContext->Viewports.end(); ++itr)
{
    ImGuiViewport* viewport = *itr;
    ImGui::SetCurrentViewport(nullptr, viewport);
    OnGUI(pAppData->stepTimer);
}
```

The additional call to OnGUI adds a second copy of my widgets in the main_viewport window.

Previously I was able to get the new viewport added to Viewports. And the call for rendering the second set of widgets (OnGUI_ did not error out but did not render correctly either.

At the end, ImGui::Render is called along with other pipeline requirements:
```
ImGui::Render();

ImGui_ImplDX12_Data::FrameContext* frameCtx = pViewportData->WaitForNextFrameResources();
UINT backBufferIdx = pViewportData->pSwapChain->GetCurrentBackBufferIndex();
:
pViewportData->pSwapChain->Present(1, 0); // Present with vsync

UINT64 fenceValue = pViewportData->fenceLastSignaledValue + 1;
pViewportData->pd3dCommandQueue->Signal(pViewportData->fence, fenceValue);
pViewportData->fenceLastSignaledValue = fenceValue;
frameCtx->FenceValue = fenceValue;
```

**Comment by ocornut** [comment]
> Then I loop through the viewports

You should never do that, it is backward, doesn't make sense and therefore rest of the post doesn't matter since you are in undefined territory. I think you are misunderstanding what the viewports are and seeing the whole thing backwards.

You can use `SetNextWindowViewport()` to specify the viewport of a window.

**Comment by r2d2Proton** [comment]
Trying to rework with the SetNextWindowViewport(). . . will update this comment when I am done

**Comment by r2d2Proton** [comment]
I changed my main loop to:
```
// Start the Dear ImGui frame
ImGui_ImplDX12_NewFrame();
ImGui_ImplWin32_NewFrame();
ImGui::NewFrame();

ImGuiViewport* main_viewport = ImGui::GetMainViewport();
ImGuiID id = main_viewport->ID ;
OnGUI(pAppData->stepTimer, id);

for (UINT i = 1; i <= playerCount; ++i)
{
    ImGuiID id = main_viewport->ID + i;
    OnGUI(pAppData->stepTimer, id);
}

ImGui::Render();
```
And my OnGUI:
```
void OnGUI(StepTimer const& stepTimer, ImGuiID id)
{
    ImGui::SetNextWindowViewport(id);

    MainMenu();
    MainWindows();
}
```
And the AddViewport:
```
void AddViewport()
{
    ImGuiPlatformIO& platform_io = ImGui::GetPlatformIO();

    ImGuiViewport* main_viewport = ImGui::GetMainViewport();

    platform_io.Platform_SetWindowPos(main_viewport, ImVec2(0.0f, 0.0f));
    platform_io.Platform_SetWindowSize(main_viewport, ImVec2(1920.0f, 540.0f));
    platform_io.Renderer_SetWindowSize(main_viewport, ImVec2(1920.0f, 540.0f));

    AddPlayer();

    ImVec2 display_pos(1920.0f, 540.0f);
    ImVec2 display_size(1920.0f, 540.0f);
    ImGuiID id = main_viewport->ID + 1;

    ImGui::SetNextWindowViewport(id);
    ImGui::SetNextWindowPos(display_pos);
    ImGui::SetNextWindowSize(display_size);
}
```
With AddPlayer simply incrementing a value:
```
void AddPlayer() { playerCount++; }
```

The initial window output is:
![ImGuiViewports-01](https://user-images.githubusercontent.com/4054178/200664721-ab168e8b-49e2-4393-bde7-d59aa8712574.png)

With menu option:
![ImGuiViewports-02](https://user-images.githubusercontent.com/4054178/200664837-d99d44f1-5234-4a6a-a24a-81c939229af7.png)

And the final display:
![ImGuiViewports-03](https://user-images.githubusercontent.com/4054178/200664917-135baa4c-d41b-4fe1-9aaf-723a2ce16357.png)

**Comment by r2d2Proton** [comment]
I think my issue is that SetNextWindowPos and SetNextWindowSize are not placed at the correct location. I am reworking to be used in the OnGUI function. And also wrapping the Menu and other windows under the HiddenWindow one (not sure this window is needed):

```
void OnGUI(StepTimer const& stepTimer, ImGuiID id)
{
    ImGui::SetNextWindowViewport(id);

    ImVec2 display_pos(1920.0f, 540.0f);
    ImVec2 display_size(1920.0f, 540.0f);

    ImGui::SetNextWindowPos(display_pos);
    ImGui::SetNextWindowSize(display_size);

    ImGuiWindowFlags windowFlags = ImGuiViewportFlags_IsPlatformWindow
                                 | ImGuiViewportFlags_NoDecoration
                                 | ImGuiViewportFlags_NoTaskBarIcon
                                 | ImGuiViewportFlags_NoAutoMerge
                                 | ImGuiViewportFlags_CanHostOtherWindows
                                 | ImGuiWindowFlags_MenuBar
                                 | ImGuiWindowFlags_NoCollapse
                                 | ImGuiWindowFlags_NoResize;

    if (ImGui::Begin("HiddenWindow", &pAppData->isOpen, windowFlags))
    {
        :
    }
}
```

**Comment by r2d2Proton** [comment]
I am sorry I have to go. I will come back shortly. As a test, I tried moving the sizing and positioning calls into the start of the rendering but that didn't help. For a quick test, I am checking if the id is the main_viewport::ID, and if not calling the needed Size/Pos functions for the new viewport:

```
void OnGUI(StepTimer const& stepTimer, ImGuiID id)
{
    ImGui::SetNextWindowViewport(id);

    if (id != mainID)
    {
        ImVec2 display_pos(1920.0f, 540.0f);
        ImVec2 display_size(1920.0f, 540.0f);

        ImGui::SetNextWindowPos(display_pos);
        ImGui::SetNextWindowSize(display_size);
    }

    ImGuiWindowFlags windowFlags = ImGuiViewportFlags_IsPlatformWindow
                                 | ImGuiViewportFlags_NoDecoration
                                 | ImGuiViewportFlags_NoTaskBarIcon
                                 | ImGuiViewportFlags_NoAutoMerge
                                 | ImGuiViewportFlags_CanHostOtherWindows
                                 | ImGuiWindowFlags_MenuBar
                                 | ImGuiWindowFlags_NoCollapse
                                 | ImGuiWindowFlags_NoResize;

    if (ImGui::Begin("HiddenWindow", &isOpen, windowFlags))
    {
        :
        ImGui::End();
    }
}

**Comment by r2d2Proton** [comment]
I am refactoring some older code now to make it easier to test.  It appears that I should use the SetNext functions, which are easy enough and straightforward:
```
const ImGuiViewport* viewport = ImGui::GetMainViewport();
ImGui::SetNextWindowPos(viewport->WorkPos);
ImGui::SetNextWindowSize(viewport->WorkSize);
ImGui::SetNextWindowViewport(viewport->ID);
```
What happens if the ID does not exist? Does Imgui create the viewport with the ID?
The SetNextWindowViewport() adds to the NextWindowData.Flags, and sets its ViewportId:
```
void ImGui::SetNextWindowViewport(ImGuiID id)
{
    ImGuiContext& g = *GImGui;
    g.NextWindowData.Flags |= ImGuiNextWindowDataFlags_HasViewport;
    g.NextWindowData.ViewportId = id;
}
```
It may take about an hour to finish folding existing code into my new project. Then I will test it again. But my simple test above looks like it should have worked.
