### ISSUE TITLE
Right align a text in global menu bar

### ISSUE THREAD

**Issue by husnoo** [ocornut/imgui#5875]
I found this question:
https://discourse.dearimgui.org/t/still-need-help-program-menubar-like-the-custom-engine-picture-on-dear-imgui-github/258

which included an image:
https://cloud.githubusercontent.com/assets/8225057/20628927/33e14cac-b329-11e6-80f6-9524e93b048a.png

With a global menubar with menu buttons on the left, but some text and other buttons on the right (with nothing in between).

My current code:

```
    if (ImGui::BeginMainMenuBar()) {
        if (ImGui::BeginMenu("System")) {
            if (ImGui::MenuItem("Exit", "CTRL+Q")) {
                exit(0);
            }            
            ImGui::EndMenu();
        }
        ImGui::Separator();
        ImGui::Text("Some Text");
        ImGui::EndMainMenuBar();
    }
```
produces this:
![screen_2022-11-08-20-55-53](https://user-images.githubusercontent.com/2923338/200673542-bfc0a271-a3cf-4c17-806f-234b2d3ed694.png)

I'm hoping to make the text appear on the right end of the screen.

Thanks for any help!

(Using dearimgui 1.89 on Linux)

**Comment by ocornut** [comment]
> which included an image:

That's my code from 2016.
We don't have right-to-left layout mode right now (this is waiting one certain refactor that may come in a few versions), the way to achieve that is to manually call SetCursorScreenPos(), SetCursorPosX() etc knowing the width of items.

Wonder Boy: The Dragon's Trap did it in a particularly dirty way since I just hardcoded an offset:

```cpp
ImGui::SameLine(ImGui::GetWindowWidth() - 710);

ImGui::PushButtonRepeat(true);
if (ImGui::Button("Step")) g_Game.StepFrame(); 
ImGui::SameLine();
ImGui::PopButtonRepeat();


bool pause = g_Game.GamePaused;
if (ImGui::Checkbox("Pause", &pause)) g_Game.SetGamePaused(pause); ImGui::SameLine();
ImGui::Checkbox("NewObj", &g_Config.NewObjs); ImGui::SameLine();
ImGui::PushItemWidth(38.0f);
ImGuiEx::DragPercent("NewBg", &g_Config.NewBgAlpha); ImGui::SameLine();
ImGuiEx::DragPercent("OldBg", &g_Config.OldBgAlpha); ImGui::SameLine();
if (ImGuiEx::DragPercent("Slide", &g_Config.NewBgCoverageAnim)) 
{ 
	g_Game.SetRetroVisuals(g_Config.NewBgCoverageTarget < 1.0f, true); 
	g_Config.NewBgCoverageTarget = g_Config.NewBgCoverageAnim;
}
ImGui::SameLine();
ImGui::PopItemWidth();
ImGui::Checkbox("NoMon", &g_Config.HackNoMonsters); ImGui::SameLine();
ImGui::Checkbox("NoDmg", &g_Config.HackNoDamage); ImGui::SameLine();
ImGui::Text(" %.2f FPS (%.2f ms)", ImGui::GetIO().Framerate, 1000.0f / ImGui::GetIO().Framerate);
```

Technically you should calculate the width of each items ahead of time (until we add right-to-left layout mode).

Note that you can avoid doing the SameLine() calls by using:

```cpp
#include "imgui_internal.h"
...
ImGui::GetCurrentWindow()->DC.LayoutType = ImGuiLayoutType_Horizontal;;
// your stuff without SameLine calls
ImGui::GetCurrentWindow()->DC.LayoutType = ImGuiLayoutType_Vertical;
```

**Comment by husnoo** [comment]
Thank you! I was coming to that conclusion, using ImGui::CalcTextSize
probably.

thanks!

**Comment by shriramters** [comment]
I was wondering if there's any news on a right-to-left layout mode. It would really be a lifesaver.
