### ISSUE TITLE
Render is clipped and mouse clicks don't register!

### ISSUE THREAD

**Issue by lolitsanub** [ocornut/imgui#5877]
**Version/Branch of Dear ImGui:**

Version: v1.89 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: Apple Clang using arm64 architecture
Operating System: MacOS Venture (13.0)

**My Issue/Question:**

Dear ImGui render is clipped off when it is supposed to cover the whole screen. The checkbox at the top left of the screenshot does not activate when clicked. __Sometimes__, it highlights on hover. The code works perfectly fine on Windows (MSVC) and Linux (g++).

The rest of my code, which uses GLFW and Vulkan with MoltenVK, works perfectly fine with detecting mouse clicks with no clipping issues.

I'm on a Mac mini using an external (non-retina) display.
**Screenshots/Video**
<img width="1872" alt="Screenshot 2022-11-09 at 5 53 42 PM" src="https://user-images.githubusercontent.com/75549263/200984806-e21632fe-ecfb-4167-a4a8-df573302930a.png">

(The green circle in the screenshot is rendered by me, which seems to render properly without any clipping/click detection issues)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
The issue can be reproduced with anything. Even the Dear ImGui official ``ImGui::ShowDemoWindow()`` seems to have the same issue.

**Comment by ocornut** [comment]
> The issue can be reproduced with anything. Even the Dear ImGui official ImGui::ShowDemoWindow() seems to have the same issue.

Does it happens in the official example using GLFW + Vulkan?

**Comment by lolitsanub** [comment]
I apologize for leaving that out! I just tested the official GLFW + Vulkan example and it renders perfectly. However the stops responding after presenting the first frame!

![0EEC8A5B-1EFF-4669-BE4F-B1F77AB95443](https://user-images.githubusercontent.com/75549263/201241685-13dde1db-05cf-4375-9bc9-d1acfa476df9.jpeg)

**Comment by lolitsanub** [comment]
The issue was resolved by moving my own GLFW mouse callbacks before dear imgui was initialized and by DISABLING Metal API validation. (As a person who is completely new to moltenvk, I didn't see this mentioned anywhere in the moltenvk repos! Weird!)

Closing.

**Comment by PathogenDavid** [comment]
Glad you were able to solve your issue, and thanks for coming back to share your solution!

> DISABLING Metal API validation. (As a person who is completely new to moltenvk, I didn't see this mentioned anywhere in the moltenvk repos! Weird!)

There's some issues on the MoltenVK repo implying that it *should* work with the Metal validation layer enabled. It might be worth investigating further and reporting to them directly.
