### ISSUE TITLE
Home key doesn't work if cursor is at the end of the buffer in InputTextMultiline()

### ISSUE THREAD

**Issue by sergof** [ocornut/imgui#588]
Simple way to reproduce:
In the "Multi-line Text Input" widget of the demo window delete the last line so that the cursor is at the end of "eax", press the home key and see nothing happen.

After looking into this for a bit it seems that the case when the cursor is at the end of the buffer (and pointing at ’\0’) is not handled correctly in the multi line mode (stb_textedit.h lines: 506-516).
Not sure if it's a problem with stb_textedit or the way it's used.

I'd try to fix this myself, but it would probably take to much time to understand how stb_textedit works and how it's used in dear imgui, so sorry for that.

**Comment by ocornut** [comment]
Confirmed. I'll look at it eventually. I don't know much about stb_textedit either, have to dig.

**Comment by johanwendin** [comment]
You can get around this by editing stb_textedit.h as a temporary fix.

Search for "case STB_TEXTEDIT_K_LINESTART:"
Change it from:

```
case STB_TEXTEDIT_K_LINESTART: {
         StbFindState find;
         stb_textedit_clamp(str, state);
         stb_textedit_move_to_first(state);
         stb_textedit_find_charpos(&find, str, state->cursor, state->single_line);
         state->cursor = find.first_char;
         state->has_preferred_x = 0;
         break;
      }
```
to:

```
case STB_TEXTEDIT_K_LINESTART: {
         StbFindState find;
         stb_textedit_clamp(str, state);

         int n = STB_TEXTEDIT_STRINGLEN(str);
         if (state->cursor >= n) state->cursor = n-1;

         stb_textedit_move_to_first(state);
         stb_textedit_find_charpos(&find, str, state->cursor, state->single_line);
         state->cursor = find.first_char;
         state->has_preferred_x = 0;
         break;
      }
```

It's not the prettiest solution, but it should get you by for now. (similar fixes needed for up-arrow as well)

**Comment by blackhole89** [comment]
It seems like the error in the logic is in `stb_textedit_find_charpos` here:
```c
   if (n == z) { 
      // if it's at the end, then find the last line -- simpler than trying to
      // explicitly handle this case in the regular code
```

**Comment by ocornut** [comment]
Should be fixed now.
