### ISSUE TITLE
Can I open popup dialog in window A which created in window B ?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#5883]
Just a Question. I have found that if popup dialog was created in window A, and i couldn't open it in other window. Is that possible for me to control popup dialog visibility cross different window ? 

<pre>
// Code in window A.
	ImGuiWindowFlags flags = 0;
	if (m_Visible.getValue() && ImGui::BeginPopupModal("dialogA", &m_Visible.getValue(), flags ))
	{
		ImGui::EndPopup();
	}
</pre>

<pre>
// Code in window B.
	ImGui::Text("aaa");
	ImGui::OpenPopupOnItemClick("dialogA", ImGuiPopupFlags_MouseButtonRight);
</pre>

**Comment by PeterJohnson** [comment]
The easiest way to do this is to set your own flag, and then in the other window check the flag and call OpenPopup() there (and reset the flag).
e.g. Global:
```
bool openIt = false;
```
Window A:
```
if (openIt) {
  ImGui::OpenPopup("dialogA");
  openIt = false;
}
if (ImGui::BeginPopupModal(...)) {
  ...
  ImGui::EndPopup();
}
```
Window B:
```
if (...) {
  openIt = true;
}
```

**Comment by ChivenZhang** [comment]
Yes, I had finished coding, it works well. Thanks
