### ISSUE TITLE
The problem of ImGui::Dragfloat3() in for-loop

### ISSUE THREAD

**Issue by Wayne693** [ocornut/imgui#5884]
**Version/Branch of Dear ImGui:**

Version: v1.89
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl2.cpp 
Operating System: Windows10

**My Issue/Question:**

Hi, I'm having an issue after using DragFloat3 in the for-loop. In my soft raster project I have a lot of models, and I want to control the translation, rotation, and scaling of the model through the UI panel, so that I can iterate through all the models with a for-loop and modify the properties of the model through DragFloat3. Unfortunately, there is a bug here, when I drag the properties of model one, the properties corresponding to the other models will also change, and I hope that the operation for them is separate. Now I don't know what's wrong, can you help me?

**Screenshots/Video**

This is part of my code :
![image](https://user-images.githubusercontent.com/63634197/201857111-5bb340aa-0195-44ff-9ade-6314e91cedba.png)

**Comment by ocornut** [comment]
You need to use `PushID()` / `PopID()` in for-loops. Read FAQ:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-multiple-widgets-with-the-same-label
