### ISSUE TITLE
Bind to texture change on render to switch shaders

### ISSUE THREAD

**Issue by DeadlyKom** [ocornut/imgui#5885]
branch https://github.com/ocornut/imgui/tree/docking

I need to use my own shader for each image (ImGui::Image/AddImage).
I tried to subscribe to the ImGui::GetWindowDrawList()->AddCallback event, but the texture ID arguments are always the same.
those. I assumed that at the stage of forming the list of commands, installation and subscription take place, and during the output of the image, earlier subscriptions are triggered by events that switch the necessary shaders for a given texture, but alas...
maybe you can tell me, I rummaged through a lot of different resources in search of similar examples, but I didn’t find it, I just don’t want to change IMGUI but find a solution using the means that you laid down.

draw:
```
[example first]
ImGui::GetWindowDrawList()->AddCallback(OnDrawCallback, nullptr);
ImGui::Image(ImageA->Texture);
ImGui::Image(ImageB->Texture);
ImGui::GetWindowDrawList()->AddCallback(ImDrawCallback_ResetRenderState, nullptr);

[example second]
ImGui::GetWindowDrawList()->AddCallback(OnDrawCallback, nullptr);
ImGui::GetWindowDrawList()->AddImage(ImageA->Texture);
ImGui::GetWindowDrawList()->AddImage(ImageB->Texture);
ImGui::GetWindowDrawList()->AddCallback(ImDrawCallback_ResetRenderState, nullptr);
```
hadler:
```
OnDrawCallback(const ImDrawList* ParentList, const ImDrawCmd* CMD)
{
   if (CMD->GetTexID() == ImageA->Texture)
   {
      // map the pixel shader constant buffer and fill values
      {
         // transfer shader options from shaderOptions to our backend specific pixel shader constant buffer
         {
   }
   else if (CMD->GetTexID() == ImageB->Texture)
   {
      // map the pixel shader constant buffer and fill values
      {
         // transfer shader options from shaderOptions to our backend specific pixel shader constant buffer
      {
   }
}
```

**Comment by ocornut** [comment]
Your message is confusing.
There's no TextureID in the callback command. The callback gets the parameter you give to AddCallback().
If you want to change shader in a callback, pass the shader/material info to the callback...
