### ISSUE TITLE
It's error when use more than one docking window.

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#5890]
I create a custom-layout dock window in main dock window, but when i switch sub windows by clicking title bar, that's wrong. Can anyone help?

## Video

![AAA](https://user-images.githubusercontent.com/48938612/202082279-a1ac010b-1c3d-4817-b08c-d5bcb4229f03.gif)

**Comment by ocornut** [comment]
I am not sure I understand your issue, but if you stop submitting a `Dockspace()` all windows docked into it will be undocked.
If a Dockspace() is hidden you need to submit it with the `ImGuiDockNodeFlags_KeepAliveOnly` flag.

```cpp
// Demonstrate using DockSpace() to create an explicit docking node within an existing window.
// Note: You can use most Docking facilities without calling any API. You DO NOT need to call DockSpace() to use Docking!
// - Drag from window title bar or their tab to dock/undock. Hold SHIFT to disable docking.
// - Drag from window menu button (upper-left button) to undock an entire node (all windows).
// - When io.ConfigDockingWithShift == true, you instead need to hold SHIFT to _enable_ docking/undocking.
// About dockspaces:
// - Use DockSpace() to create an explicit dock node _within_ an existing window.
// - Use DockSpaceOverViewport() to create an explicit dock node covering the screen or a specific viewport.
//   This is often used with ImGuiDockNodeFlags_PassthruCentralNode.
// - Important: Dockspaces need to be submitted _before_ any window they can host. Submit it early in your frame! (*)
// - Important: Dockspaces need to be kept alive if hidden, otherwise windows docked into it will be undocked.
//   e.g. if you have multiple tabs with a dockspace inside each tab: submit the non-visible dockspaces with ImGuiDockNodeFlags_KeepAliveOnly.
// (*) because of this constraint, the implicit \"Debug\" window can not be docked into an explicit DockSpace() node,
// because that window is submitted as part of the part of the NewFrame() call. An easy workaround is that you can create
// your own implicit "Debug##2" window after calling DockSpace() and leave it in the window stack for anyone to use.
```

**Comment by ChivenZhang** [comment]
> 

There is a fullscreen dock window and a sub dock window in the gif above. Notice that the window contains flame icon belongs to sub dock window, when I drag it into fullscreen dock window to merge with another empty sub window, the flame icon changed its owner. And when I switch window title to previous one, the flame window has gone. It's not correct.

**Comment by ocornut** [comment]
> Is it legal to use more than one dockwindow in imgui ?

Yes. We do it in the demo and in our tests.
Please read my answer above and make sure you not stopping to submit the sub-dockspace.. must submit it using `ImGuiDockNodeFlags_KeepAliveOnly`.

**Comment by ChivenZhang** [comment]
> > Is it legal to use more than one dockwindow in imgui ?
> 
> Yes. We do it in the demo and in our tests. Please read my answer above and make sure you not stopping to submit the sub-dockspace.. must submit it using `ImGuiDockNodeFlags_KeepAliveOnly`.

I'll try it later, thank you

**Comment by ocornut** [comment]
You can also use `Tools->Debug Log->Docking` to check why a window is undocked.

**Comment by ChivenZhang** [comment]
I have changed code to keep one docking window, so maybe there'is no more than one docking space in my system. I'll try that "ImGuiDockNodeFlags_KeepAliveOnly" flags in the future If I need. Thanks. I'll close this issue.

**Comment by ChivenZhang** [comment]
> > Is it legal to use more than one dockwindow in imgui ?
> 
> Yes. We do it in the demo and in our tests. Please read my answer above and make sure you not stopping to submit the sub-dockspace.. must submit it using `ImGuiDockNodeFlags_KeepAliveOnly`.

I have solved it ,thanks

![image](https://user-images.githubusercontent.com/48938612/209424229-0416959e-099c-42d8-a695-dc86f904c005.png)

**Comment by ChivenZhang** [comment]
> > Is it legal to use more than one dockwindow in imgui ?
> 
> Yes. We do it in the demo and in our tests. Please read my answer above and make sure you not stopping to submit the sub-dockspace.. must submit it using `ImGuiDockNodeFlags_KeepAliveOnly`.

Please help me, When I used ImGuiDockNodeFlags_KeepAliveOnly to keep invisible docking window alive , I found I couldn't hide the tab bar of window.

https://user-images.githubusercontent.com/48938612/210180059-2147f3e8-9fdd-46f8-bfc4-e281664df581.mp4
