### ISSUE TITLE
How to use Dear ImGui as a GUI system in-game and then using it as editor too in the same app?

### ISSUE THREAD

**Issue by roig** [ocornut/imgui#5891]
Version: 1.87
Branch: docking

**My Issue/Question:**
Currently I have a game that uses imgui (with a customized style) as the in-game GUI. 
As you can see in the image the menu textures, texts, buttons, input texts, etc.. is drawn using imgui .
The background is rendered using the game internal gl renderer.

![image](https://user-images.githubusercontent.com/389619/202181635-74c96a84-96be-497f-aeb1-934361a4a773.png)

Now I want to add an editor layer on top of that, that draws the game inside a window.
What I'm currently doing is, rendering the game to a texture and then begin an editor imgui window and using imgui::image to render that texture.
This is the result of it:

![image](https://user-images.githubusercontent.com/389619/202182399-fcb5c6a7-7f33-45d3-b217-f756682d4a1d.png)

**The problem** as you can see, the in-game imgui elements are not drew.. Because I'm drawing imgui later, but I can't draw my in-game elements later with the editor layer because those elements belongs to the in-game window... >_<

One solution could be to render first the in-game imgui primitives and then in the same frame clear all the primitives and state of imgui and add the editor stuff and render it. This means rendering imgui 2 times in the same frame.. and it feels ugly...

I searched solutions for this problem and I found that I can use two imgui contexts, one for the in-game elements and one for the editor. Is this the better approach? Or maybe using viewports? I'm a bit lost here...

If using two imgui contexts is the best solution, how do you handle the inputs in the in-game imgui context that is being drawn inside the other imgui context window.. ?

Thank you!

**Comment by GamingMinds-DanielC** [comment]
About the input handling, the basic process is pretty simple:
With your editor context as the current context, pass mouse and keyboard events to ImGui. After that, check `ImGui::GetIO().WantCaptureMouse` or `WantCaptureKeyboard` depending on the event. If ImGui dowsn't want it, switch to your game context and pass the events to ImGui again, then switch back to your editor context.

I haven't done this with a second ImGui context, just with a 3D viewport that gets the inputs that ImGui doesn't want. But the principle is the same.

**Comment by roig** [comment]
Thank you! I managed to do it :) 
I did the 2 contexts approach 👍  and works flawlessly!
