### ISSUE TITLE
Error with OpenGL ES2.0

### ISSUE THREAD

**Issue by YujieLu** [ocornut/imgui#5892]
Version: 1.89
Branch: master

file: examples/example_glfw_opengl3/main.cpp
Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: gcc
Operating System: linux
chip: rk3588

I'm trying to migrate my code to Arm-linux platform.  It seems rk3588 can only support Opengl ES, so I use opengl3 + ES2 + glfw. I found that I need to add another line after line 41
```
 glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
```
 in order to running the example code sucessfully.  or i will get an error like
```
Glfw Error 65542: GLX: No GLXFBConfigs returned
Glfw Error 65545: GLX: Failed to find a suitable GLXFBConfig
```

**Comment by ocornut** [comment]
Sorry but this has nothing to do with Dear ImGui. It is a problem around the intersection of OpenGL, GLFW and your setup.
