### ISSUE TITLE
Remove default menu in table / localize menu entries

### ISSUE THREAD

**Issue by llxiaoyuan** [ocornut/imgui#5895]
how remove default menu in table with ImGuiTableFlags_Resizable ? 

![image](https://user-images.githubusercontent.com/36320938/202657907-7c4bb11d-a7b9-4f8d-a205-fde3bdfe15e1.png)

**Comment by ocornut** [comment]
Why are you trying to remove the header menu?

**Comment by llxiaoyuan** [comment]
I want to add a switch to change default text between Chinese/English，or remove it

**Comment by ocornut** [comment]
With ffe0abb I have added a minimal localization system (experimental).

```cpp
#include "imgui_internal.h"

static const ImGuiLocEntry GLocalizationEntriesEnUS[] =
{
    { ImGuiLocKey_TableSizeOne,         "Size column to fit###SizeOne"          },
    { ImGuiLocKey_TableSizeAllFit,      "Size all columns to fit###SizeAll"     },
    { ImGuiLocKey_TableSizeAllDefault,  "Size all columns to default###SizeAll" },
    { ImGuiLocKey_TableResetOrder,      "Reset order###ResetOrder"              },
    { ImGuiLocKey_WindowingMainMenuBar, "(Main menu bar)"                       },
    { ImGuiLocKey_WindowingPopup,       "(Popup)"                               },
    { ImGuiLocKey_WindowingUntitled,    "(Untitled)"                            },
};
[...]
LocalizeRegisterEntries(GLocalizationEntriesEnUS, IM_ARRAYSIZE(GLocalizationEntriesEnUS));
```

English is registered by default. You may create your own entry and register them in your code:

```cpp
static const ImGuiLocEntry GLocalizationEntriesTestChinese[] =
{
    { ImGuiLocKey_TableSizeOne,         u8"尺寸列适合###SizeOne"          },
    { ImGuiLocKey_TableSizeAllFit,      u8"调整所有列的大小以适合###SizeAll"     },
    { ImGuiLocKey_TableSizeAllDefault,  u8"将所有列的大小设置为默认值###SizeAll" },
    { ImGuiLocKey_TableResetOrder,      u8"重置订单###ResetOrder"              },
};
ImGui::LocalizeRegisterEntries(GLocalizationEntriesTestChinese, IM_ARRAYSIZE(GLocalizationEntriesTestChinese));
```

Let us know how it works!

![image](https://user-images.githubusercontent.com/8225057/203581037-c8197c3b-7cc6-4856-974a-b592111f713a.png)

**Comment by zyylvsSwe** [comment]
> With [ffe0abb](https://github.com/ocornut/imgui/commit/ffe0abbfc2672b1d44a51f7f7b36c9075e4409f4) I have added a minimal localization system (experimental).
> 
> ```c++
> #include "imgui_internal.h"
> 
> static const ImGuiLocEntry GLocalizationEntriesEnUS[] =
> {
>     { ImGuiLocKey_TableSizeOne,         "Size column to fit###SizeOne"          },
>     { ImGuiLocKey_TableSizeAllFit,      "Size all columns to fit###SizeAll"     },
>     { ImGuiLocKey_TableSizeAllDefault,  "Size all columns to default###SizeAll" },
>     { ImGuiLocKey_TableResetOrder,      "Reset order###ResetOrder"              },
>     { ImGuiLocKey_WindowingMainMenuBar, "(Main menu bar)"                       },
>     { ImGuiLocKey_WindowingPopup,       "(Popup)"                               },
>     { ImGuiLocKey_WindowingUntitled,    "(Untitled)"                            },
> };
> [...]
> LocalizeRegisterEntries(GLocalizationEntriesEnUS, IM_ARRAYSIZE(GLocalizationEntriesEnUS));
> ```
> 
> English is registered by default. You may create your own entry and register them in your code:
> 
> ```c++
> static const ImGuiLocEntry GLocalizationEntriesTestChinese[] =
> {
>     { ImGuiLocKey_TableSizeOne,         u8"尺寸列适合###SizeOne"          },
>     { ImGuiLocKey_TableSizeAllFit,      u8"调整所有列的大小以适合###SizeAll"     },
>     { ImGuiLocKey_TableSizeAllDefault,  u8"将所有列的大小设置为默认值###SizeAll" },
>     { ImGuiLocKey_TableResetOrder,      u8"重置订单###ResetOrder"              },
> };
> ImGui::LocalizeRegisterEntries(GLocalizationEntriesTestChinese, IM_ARRAYSIZE(GLocalizationEntriesTestChinese));
> ```
> 
> Let us know how it works!
> 
> ![image](https://user-images.githubusercontent.com/8225057/203581037-c8197c3b-7cc6-4856-974a-b592111f713a.png)

  This scheme requires all strings to be written in an array. However, in many projects, English strings are scattered in different files. For example:
```cpp
//a.cpp
ImGui::Text("abc###SizeName");
//b.cpp
ImGui::Text("address:ABCD.###SizeAddress");
```
When the above situation is encountered, this solution is not so effective.

**Comment by ocornut** [comment]
> This scheme requires all strings to be written in an array. However, in many projects, English strings are scattered in different files. For example:

This is not a solution to localize your software. 
This is only a solution to localize the very few strings that Dear ImGui uses internally that are visible to end use. Therefore this is not a problem.

**Comment by zyylvsSwe** [comment]
So, does Deal ImGui plan to develop the localization function of the software?

**Comment by ocornut** [comment]
Nothing prevents you from localizing your software already.
