### ISSUE TITLE
Info about Dear ImGui language bindings

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#5896]
Just made a Lua script to get info about github repos. I dont know if it is valuable but I am sharing it just in case.
It lists the different language bindings (as provided in the wiki) sorted by stars number. (Some of them use cimgui and some not)
Third colum shows language (although it is not necessarily the target language)

My main surprise is the small number or stars compared to 43.3k stars in Dear ImGui repo, which seems to mean that the main Dear ImGui usage is from C++ language and the language binding usage is quite low.

| name | stars | language |
| ---- | ---- | ---- |
| covscript/covscript-imgui | 4 | C++ |
| MultiPain/Gideros_ImGui | 7 | C++ |
| hippyau/pb-cimgui | 7 | C++ |
| dbousamra/imgui-haskell | 11 | Haskell |
| JuJuBoSc/imgui-chaiscript | 11 | C++ |
| Inochi2D/bindbc-imgui | 13 | D |
| cammm/deargui | 13 | C++ |
| chromy/cyimgui | 17 | Python |
| RogueMacro/imgui-beef | 19 | Beef |
| nsf/imgui-rust | 19 | Rust |
| MSeys/sol2_ImGui_Bindings | 19 | C++ |
| thenumbernine/lua-ffi-bindings | 21 | Lua |
| michaelfairley/rust-imgui-opengl-renderer | 28 | Rust |
| haddock7/hlimgui | 29 | C++ |
| OGRECave/ogre-imgui | 30 | C++ |
| dpethes/imgui-pas | 31 | Pascal |
| ThisDevDane/odin-imgui | 39 | Odin |
| Aidan63/linc_imgui | 40 | Haxe |
| SpexGuy/Zig-ImGui | 49 | C++ |
| Extrawurst/DerelictImgui | 49 | D |
| oprypin/crystal-imgui | 50 | Crystal |
| mnmly/Swift-imgui | 59 | Swift |
| Dominaezzz/kotlin-imgui | 72 | Kotlin |
| ctreffs/SwiftImGui | 87 | C++ |
| haskell-game/dear-imgui.hs | 93 | Haskell |
| nimgl/imgui | 106 | Nim |
| erickjung/SwiftGUI | 114 | Swift |
| patrickriordan/imgui_lua_bindings | 132 | C++ |
| ice1000/jimgui | 157 | Java |
| sonoro1234/LuaJIT-ImGui | 160 | Lua |
| podgorskiy/bimpy | 182 | C++ |
| Gnimuc/CImGui.jL | 191 | Julia |
| SpaiR/imgui-java | 317 | Java |
| flyover/imgui-js | 724 | TypeScript |
| inkyblackness/imgui-go | 791 | C++ |
| pyimgui/pyimgui | 918 | Cython |
| mellinoe/ImGui.NET | 1313 | C# |
| imgui-rs/imgui-rs | 1963 | Rust |
| hoffstadt/DearPyGui | 9095 | C++ |

**Comment by ocornut** [comment]
Thanks for this!

Intuitively I would say most users of Dear ImGui are from C++, but Stars are a relatively poor indicator of usage IMHO.
I think many people use Stars to "bookmark" a repository, so of course since UI is such a widespread problem people would star Dear ImGui. Conversely, I suspect people who use Dear ImGui or bindings don't necessary star them (I know that I use repository that I don't feel the need to star).
