### ISSUE TITLE
Focused selectable item is not centered within BeginCombo selectable items list

### ISSUE THREAD

**Issue by the-goodies** [ocornut/imgui#5902]
Focused (SetItemDefaultFocus) selectable item is not centered when BeginCombo is opened, it always shows on top. It's very annoying having to scroll up in order to see what is available, and I'm sure it used to be centered (don't remember version).

Tested with 1.87 and 1.89 versions.

https://user-images.githubusercontent.com/22452788/203066730-a03bcdae-5bfa-48a6-945d-2b4109308bea.mp4

**Comment by ocornut** [comment]
Thank you for reporting.
Seems like this was broke by 44f8011 and following 8f495e55.

Not sure when I'll finishing investigating/fixing but:

- [ ] I'm currently confused as to why the _CenterY behaviors of `ScrollToRectEx()` are not using 0.5f in the `SetScrollFromPosY()` call.
- [ ] `can_be_fully_visible_y` is false anyhow as the window is appearing and popup have a small size before auto-resizing, those bool may also need to be set differently on an auto-resizing frame.

**Comment by ocornut** [comment]
Should be fixed by 27c58c3, thank you for reporting!
