### ISSUE TITLE
About touching or clicking on the imgui window

### ISSUE THREAD

**Issue by LarissaLycoris** [ocornut/imgui#5903]
As for touching or clicking on the imgui window, Begin will be highlighted, but if you click other places outside the imgui window, Begin will not be highlighted. May I ask, where is the judgment value for judging whether the imgui window is touched or selected? I've been looking for a while and can't find it!

**Comment by ocornut** [comment]
Which problem are you trying to solve?

**Comment by LarissaLycoris** [comment]
I want to solve the problem of touch penetration, and I need to find out whether I have clicked on the imgui window, so I need this judgment value


This is to select the imgui window, and Begin will be highlighted
![1](https://user-images.githubusercontent.com/99528736/203069656-f1e59d92-8db0-4388-8b40-547e3d74bc1c.jpg)

This is the unselected imgui window, Begin will not be highlighted
![2](https://user-images.githubusercontent.com/99528736/203069742-1a0abac6-6ced-48e2-9317-b44abf2544d0.jpg)

I want to know where this judgment value is

**Comment by ocornut** [comment]
> I want to solve the problem of touch penetration,

I don't understand what that means.

Are you sure you don't simply want to use `io.WantCaptureMouse` to decide whether your background app should get inputs?

https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application

Try to display this value:
```cpp
ImGui::Text("io.WantCaptureMouse = %d", ImGui::GetIO().WantCaptureMouse);
```

**Comment by LarissaLycoris** [comment]
> 


Thanks, solved it with your code!
