### ISSUE TITLE
glfw: key callback needs to clear error code with glfwGetError

### ISSUE THREAD

**Issue by mitchellh** [ocornut/imgui#5908]
**Version/Branch of Dear ImGui:**

Version: 1.88
Also Branch: master (5bb287494096461f90eb5d18135f7c4809efd2f5)

**Back-end/Renderer/Compiler/OS**

Back-ends: glfw (and opengl3 but irrelevant to this issue)
Operating System: NixOS aarch64 (irrelevant to this issue)

**My Issue/Question:**

The glfw backend attempts to untranslate the key using `glfwGetKeyName` (see below). This can set an error code. For applications that do not use the error handling callback and use `glfwGetError` directly, this unfortunately still retains the last error code. Therefore, the next successful call to glfw APIs that use `glfwGetError` after the call will still return an error.

Since this code is called _after_ the user key callback, we also have no opportunity to cleanly clear this error code so a workaround is painful. 

https://github.com/ocornut/imgui/blob/5bb287494096461f90eb5d18135f7c4809efd2f5/backends/imgui_impl_glfw.cpp#L308

I think we have to add another `(void)glfwGetError(NULL);` call right after this for glfw 3.3+.

This is similar to my other issue: https://github.com/ocornut/imgui/issues/5785

**Comment by ocornut** [comment]
Thank you for reporting! Posted the fix 16476f9
