### ISSUE TITLE
Linux SIGFPE in ImGui_ImplVulkan_RenderDrawData

### ISSUE THREAD

**Issue by Kbz-8** [ocornut/imgui#5913]
Version: 1.87 docking release

Backend: Vulkan / SDL2
Compilers: g++ or clang++ (same error on both)
OS: Ubuntu 20.04 LTS

I'm making a game engine using ImGui for GUIs and it works fine when I compile and run it on PCs with Nvidia drivers.
But when I compile and run it on PCs with open source MESA drivers I get an error "signal SIGFPE: integer divide by zero" comming from `ImGui_ImplVulkan_RenderDrawData()`.
I don't have any messages from Vulkan validations layers.

I don't even know if it comes from ImGui or from the drivers but I would like to let you know that this can happen.

PS : the computer I got the issue on uses the Intel integrated GPU but it can run Vulkan (`vkcube` from the LunarG SDK works fine).

![Screenshot from 2022-11-23 18-30-26](https://user-images.githubusercontent.com/71275324/203612008-43ebf14e-b93a-40fa-a08d-fb703691b8d2.png)

**Comment by ocornut** [comment]
Please use a debugger to provide more information, eg a callstack.

**Comment by Kbz-8** [comment]
I found were the error is coming from.

gdb :
![Screenshot from 2022-11-23 20-47-00](https://user-images.githubusercontent.com/71275324/203634463-140a34ec-de96-4ee5-9e7a-64c7dc6cf773.png)
lldb :
![Screenshot from 2022-11-23 20-48-41](https://user-images.githubusercontent.com/71275324/203634467-e6de62e0-1163-4f4c-a3a3-ed26b2f28bc5.png)

https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_vulkan.cpp#L459

**Comment by Kbz-8** [comment]
I managed to go back even further and it turns out that it doesn't come from ImGui but from Vulkan !
`vkGetPhysicalDeviceSurfaceCapabilitiesKHR()` returns me the capabilities of the surface and it gives a minImageCount of 3 and a maxImageCount of 0 that I pass to ImGui.

**Comment by Kbz-8** [comment]
Nevermind it was not an error from ImGui, i fixed it and it works fine now, my bad...
