### ISSUE TITLE
Github: Convert all issue templates to issue forms

### ISSUE THREAD

**Issue by Panquesito7** [ocornut/imgui#5915]
## Description

We should use the newly provided GitHub issue forms. This can prevent blank issues or issues without enough information.
We can mark fields as optional or as required, which will make things much more efficient and easier, IMO.

You can check GitHub's blog post about this https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

### Alternate Solutions

Improve the current issue templates, such as adding links to the contributing guidelines, disabling blank issues, etc..

### Additional information

I removed the current template as I don't think it fits this kind of issue. Apologies if that's a problem.
If you like the idea of updating the templates, let me know, and I'd like to work on this (if possible). 🙂

Thank you.

**Comment by Panquesito7** [comment]
May I work on this?

**Comment by ocornut** [comment]
Absolutely it would be great :)
Thank you!

**Comment by Panquesito7** [comment]
Thank you! I'll be making a PR soon. 😄

**Comment by ocornut** [comment]
Moving to #5927 as I don't feel we need to keep an issue open for this.
Thanks!
