### ISSUE TITLE
Gamepad/Keyboard navigation wrap-around

### ISSUE THREAD

**Issue by Tryum** [ocornut/imgui#5916]
Version: 1.88
Branch: master
Back-ends: imgui_impl_win32 + imgui_impl_dx12
Operating System: Win10

Hi,
Is there a way to make a table loopable/wrappable when navigating with gamepad/keyboard ?
The intent is to go to same column, first row when the user press down on the last row.

I saw somme ImGuiNavMoveFlags_ flags related to the behavior I'm looking for, unfortunatly, it's not exposed to the public API.

Thanks,
Thibault

**Comment by ocornut** [comment]
The internal API way to do that is currently to call this _BEFORE_ End()/EndChild()/EndTable():

```cpp
ImGui::NavMoveRequestTryWrapping(ImGui::GetCurrentWindow(), ImGuiNavMoveFlags_WrapY);
```

However, this currently won't work correctly if you are using frozen rows (typically `ImGui::TableSetupScrollFreeze(0, 1)`).
Relates to #5143 and #3692
It's rather embarassing that those haven't been fixed yet.. I'll try to schedule them for 1.90.

**Comment by Tryum** [comment]
Thanks, that works great.
