### ISSUE TITLE
version 1.89.1docking (master also)

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#5918]
Is docking still WIP? (also master)

https://github.com/ocornut/imgui/blob/docking/imgui.h#L1
vs
https://github.com/ocornut/imgui/blob/docking/imgui.h#L25

**Comment by ocornut** [comment]
Forgot to change the string, doesn’t matter much but will fix in a next commit.

**Comment by sonoro1234** [comment]
Should I wait it to generate cimgui?

**Comment by sonoro1234** [comment]
Just done

**Comment by ocornut** [comment]
Pushed the string fix to master and docking, thank you!
