### ISSUE TITLE
Creating a viewport window with an InitInfo.Subpass greater than 0 causes validation error spam.

### ISSUE THREAD

**Issue by TheCurle** [ocornut/imgui#5922]
**Version/Branch of Dear ImGui:**

Version: v1.89 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_vulkan.cpp
Operating System: Windows 11

**My Issue/Question:**

`ImGui_ImplVulkanH_CreateWindowSwapChain` hardcodes a subpassCount of 1 when creating the RenderPass:
```
        info.subpassCount = 1;
        info.pSubpasses = &subpass;
```

When passing a Subpass of >0 to the InitInfo:
```
ImGui_ImplVulkan_InitInfo init_info = {}; 
init_info.Subpass = 1;
```
and binding a Pipeline that renders ImGui objects in a second subPass, this creates a whole bunch of spam from the Validation layers **if and only if** any widget is in a detached viewport.

It seems this is because the Pipeline that ImGui uses takes the Subpass from the InitInfo, but is bound and used regardless, causing this issue:
```
    VkGraphicsPipelineCreateInfo info = {};
    ...
    info.renderPass = renderPass;
    info.subpass = subpass;
```

The validation errors:
```
Validation Error: [ VUID-vkCmdDrawIndexed-renderPass-02684 ] Object 0: handle = 0x421a0f0000000074, type = VK_OBJECT_TYPE_RENDER_PASS; Object 1: handle = 0x2cfba2000000001c, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x8cb637c2 | vkCmdDrawIndexed: RenderPasses incompatible between active render pass w/ VkRenderPass 0x421a0f0000000074[] with a dependencyCount of 1 and pipeline state object w/ VkRenderPass 0x2cfba2000000001c[] with a dependencyCount of 3. The Vulkan spec states: The current render pass must be compatible with the renderPass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-renderPass-02684)

Validation Error: [ VUID-vkCmdDrawIndexed-subpass-02685 ] Object 0: handle = 0xb991fa0000000024, type = VK_OBJECT_TYPE_PIPELINE; | MessageID = 0x38baf2c6 | vkCmdDrawIndexed: Pipeline was built for subpass 1 but used in subpass 0. The Vulkan spec states: The subpass index of the current render pass must be equal to the subpass member of the VkGraphicsPipelineCreateInfo structure specified when creating the VkPipeline bound to VK_PIPELINE_BIND_POINT_GRAPHICS (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-subpass-02685)
```

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
 ImGui_ImplVulkan_InitInfo init_info = {};
 init_info.Subpass = 1;
 ...
 
 ImGui::Begin("sup?");
 ImGui::End();
 // Take the window outside of the viewport to create a new window, observe spam.
```

**Comment by ocornut** [comment]
Hello @TheCurle,
Sorry for my very late answer. 
I am afraid I'm not familiar with Vulkan enough to move forward without further indications.

However, with ebb8d78 merged 3 weeks ago we are creating a pipeline for secondary viewport, which uses a subpass of 0.
Could you reevaluate your post under the light of this new change?
I would presume it is fixed, so I am preemptively closing this, but let me know if it isn't.

I am not exactly sure how to apply your repro of altering main.cpp
> ImGui_ImplVulkan_InitInfo init_info = {};
> init_info.Subpass = 1;

As it requires larger changes which I am not familar with, otherwise naturally I get:
```cpp
[vulkan] Debug report from ObjectType: 18
Message: Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-renderPass-06046 ] Object 0: handle = 0xcb3ee80000000007, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x9391d499 | vkCreateGraphicsPipelines(): pCreateInfos[0].subpass (1) is out of range for this renderpass (0..0). The Vulkan spec states: If renderPass is not VK_NULL_HANDLE, subpass must be a valid subpass within renderPass (https://vulkan.lunarg.com/doc/view/1.3.280.0/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-renderPass-06046)
```
