### ISSUE TITLE
Creating a window inside a window

### ISSUE THREAD

**Issue by 333testing** [ocornut/imgui#5926]
my question is very simple, can i create a imgui window thats inside a imgui window?
i dont want them separated from each other.

**Comment by 333testing** [comment]
because i want to implement https://github.com/patrickcjk/imgui-notify (notifications) to my admin panel.

**Comment by ocornut** [comment]
This is what BeginChild() does but since your question is ambiguous about actual needs and intent we have no way to tel if that’s a useful answer.

**Comment by 333testing** [comment]
yes i know about imgui childs but because i want to use https://github.com/patrickcjk/imgui-notify i cant use childs, but thanks for trying to help i appreciate it. i will keep looking for answers

**Comment by ocornut** [comment]
Question is too ambiguous and requirements missing, please ask in the imgui-notify repository.
