### ISSUE TITLE
making ImGui::InputText taller

### ISSUE THREAD

**Issue by 333testing** [ocornut/imgui#5928]
Hello!
a simple question, can i change the height of ImGui::InputText?

**Comment by ocornut** [comment]
If I search for "inputtext center" I can find:
#3277
#3853
#5764 
Answer is no.

**Comment by ocornut** [comment]
Ah you have changed the subject and the main message of your post from "can I center the text in InputText()" to "can I change the height of InputText?" which is a different question.

Height of framed widget is `FontSize + style.FramePadding.y * 2.0f`
So you change font size of increase FramePadding.y.
