### ISSUE TITLE
How do i achieve Centering buttons/text in this gui

### ISSUE THREAD

**Issue by Nota0x7** [ocornut/imgui#5929]
ok so i wanna be able to center all of this (odv with it still like stacking on each-other) but i dont know how. 😎 
![image](https://user-images.githubusercontent.com/119354382/204359644-8c5533ac-2c1e-4254-85d3-09c6421b3ce9.png)

**Comment by Nota0x7** [comment]
is it possible or do i need to find the stuff myself

**Comment by ocornut** [comment]
Sorry but #1586
