### ISSUE TITLE
SetItemUsingMouseWheel Obsoleted?

### ISSUE THREAD

**Issue by michaelquigley** [ocornut/imgui#5930]
Version: v1.89.1

What happened to `SetItemUsingMouseWheel`? What's the current mechanism to achieve this in 1.89.1?

```
    // Obsolete functions
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    inline void     SetItemUsingMouseWheel()                                            { SetItemKeyOwner(ImGuiKey_MouseWheelY); }      // Changed in 1.89
```

**Comment by michaelquigley** [comment]
According to the above, it looks like I can maintain the functionality using:

```
ImGui::SetItemKeyOwner(ImGuiKey_MouseWheelY);
```

Will ImGui maintain this capability going forward? It looks like the `SetItemKeyOwner` stuff is "experimental"?

**Comment by zao** [comment]
See https://github.com/ocornut/imgui/pull/2891#issuecomment-1307753952 for some info on this deprecated function and a suggestion to use `SetItemKeyOwner` as part of the more generic system that replaces it.

**Comment by ocornut** [comment]
Also linking to #4207, cross-posting
Everything in imgui_internal.h is technically not guaranteed to be stable, but `SetItemKeyOwner()` is the way forward.
As `SetItemUsingMouseWheel()` was mentioned in #5108 #4303 #4207 #2891 #2704  I added a redirection function in imgui_internal.h but those are fairly exceptional and the `SetItemUsingMouseWheel()` inline function will eventually be removed.

There is a very small change that SetItemKeyOwner() will evolve but either way the feature will be preserved.
