### ISSUE TITLE
Empty windows with SDL2 renderer on macOS

### ISSUE THREAD

**Issue by JacobCZ** [ocornut/imgui#5931]
**Version/Branch of Dear ImGui:**

Version: 1.89.1
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.h, imgui_impl_sdlrenderer.h; SDL2 using Metal
Compiler: Apple clang 14.0.0 (am64-apple-darwin22.1.0)
Operating System: macOS Ventura 13.0

**My Issue/Question:**

I'm trying to render the demo window and one additional window. The window frames are both shown but only the additional window has a title and both of the windows are completely empty. The mouse also seems to be strangely offset. At first I thought this might somehow be a font issue because of the missing text but adding a custom font made no difference.

**Screenshots/Video**

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1533848/204470222-c288ad5c-783d-4c77-b9a2-e1e9ccdbad55.png">

**Standalone, minimal, complete and verifiable example:**

(error handling omitted for brevity)

```cpp
int main(it argc, char* argv[]) {
  // Create SDL window and renderer
  SDL_Init(SDL_INIT_EVERYTHING);
  window = SDL_CreateWindow("Hello World", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 640, 480, SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI | SDL_WINDOW_METAL);
  renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);

  // ImGui Init
  IMGUI_CHECKVERSION();
  ImGui::CreateContext();
  ImGuiIO& io = ImGui::GetIO();
  io.Fonts->AddFontDefault();
  ImGui_ImplSDL2_InitForSDLRenderer(window, renderer);
  ImGui_ImplSDLRenderer_Init(renderer);
  ImGui::StyleColorsDark();

  SDL_Event evt;
  while(true) {
    while(SDL_PollEvent(&evt)) {
      ImGui_ImplSDL2_ProcessEvent(&evt);
    }

    ImGui_ImplSDLRenderer_NewFrame();
    ImGui_ImplSDL2_NewFrame();
    ImGui::NewFrame();

    ImGui::ShowDemoWindow();

    ImGui::Begin("Debug");
    ImGui::Text("Hello World");
    ImGui::End();

    ImGui::Render();
    SDL_SetRenderDrawColor(renderer, 0x0, 0x0, 0x0, 0xFF);
    SDL_RenderClear(renderer);
    ImGui_ImplSDLRenderer_RenderDrawData(ImGui::GetDrawData());
    SDL_RenderPresent(renderer);
  }
}
```

**Comment by ocornut** [comment]
1. can you confirm that `example_sdl_sdlrenderer/main.cpp` is exhibit the same issue?

2. The rendering issue seems like the scissoring is off:
- either related to FrameBufferScale
- either the same offset you have with the mouse are applied to scissoring rectangle, meaning text is clipped.

3. Perhaps mouse issue is also a FrameBufferScale issue?

Out of curiosity try to remove the `SDL_WINDOW_ALLOW_HIGHDPI` flag.

We haven't really standardized setting/applying framebufferscale but it is currently a bit of a mess, hence my rather obtuse answer.

Links:
https://github.com/ocornut/imgui/issues?q=label%3Aosx%2Fios+label%3Adpi

Notice in `ImGui_ImplSDLRenderer_RenderDrawData()`:

```cpp
// If there's a scale factor set by the user, use that instead
// If the user has specified a scale factor to SDL_Renderer already via SDL_RenderSetScale(), SDL will scale whatever we pass
// to SDL_RenderGeometryRaw() by that scale factor. In that case we don't want to be also scaling it ourselves here.
float rsx = 1.0f;
float rsy = 1.0f;
SDL_RenderGetScale(bd->SDLRenderer, &rsx, &rsy);
ImVec2 render_scale;
render_scale.x = (rsx == 1.0f) ? draw_data->FramebufferScale.x : 1.0f;
render_scale.y = (rsy == 1.0f) ? draw_data->FramebufferScale.y : 1.0f;
```

**Comment by JacobCZ** [comment]
`example_sdl_sdlrenderer/main.cpp` has the same issue...
<img width="704" alt="image" src="https://user-images.githubusercontent.com/1533848/204522522-2c93d6ec-8361-406f-9733-aa0c4e9abfd1.png">

Removing `SDL_WINDOW_ALLOW_HIGHDPI` seems to fix the issue and everything seems to be rendering at a reasonable scale for a 14 inch retina screen (with a very slightly blurry text with the default font). Also solves the mouse offset issue.

**Comment by ocornut** [comment]
Can you debug step into the beginning of ImGui_ImplSDLRenderer_RenderDrawData() and report all the values?

They are not hard problems to solve but I don’t have a Mac, I’ll want to spend more time on backend dpi issue on Mac for 1.90

**Comment by ocornut** [comment]
Hello,
I have added ` SDL_RenderSetScale()` in 5a3f82e2f4f30e529f765d38aaa76866653b245a to make this consistent across examples for now. Fuller hi-dpi support on Mac in the examples app will be address separately but this fixes this issue.
