### ISSUE TITLE
Undefined symbol "_OBJC_CLASS_$_GCController" error on Mac

### ISSUE THREAD

**Issue by TheMostDiligent** [ocornut/imgui#5938]
**Version/Branch of Dear ImGui:**

Version: 1.89.1
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_osx.mm + [custom](https://github.com/DiligentGraphics/DiligentTools/tree/master/Imgui/src)
Compiler: AppleClang 13.1.6.13160021 (XCode 13.4)
Operating System: MacOS (M1, arm64)

**My Issue/Question:**

After updating to the latest version (my was ~3 years old), I started getting the following linking errors when building on MacOS:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GCController", referenced from:
      objc-class-ref in libDiligent-Imgui.a(imgui_impl_osx.o)
ld: symbol(s) not found for architecture arm64
```

There seems to be nothing special about how `imgui_impl_osx.mm` is being built compared to other objective-c++ files, and I ran out of ideas of what may be wrong. Googling "\_OBJC_CLASS_$_GCController" gives exactly zero relevant results.
I tried:

- Building with ARC on and off (the entire project is built with ARC off), which made no difference
- Add some frameworks (Coca, CoreFoundation, etc.), which also did not make any difference

Any suggestion would be highly appreciated.
Thank you!

**Comment by TheMostDiligent** [comment]
OK, after comparing the example XCode project settings line-by-line I finally found that Mac implementation now requires the `GameController` framework. Linking with it fixed the problem.
It may be worth adding a note in `imgui_impl_osx.mm` that this framework is now a requirement.

**Comment by ocornut** [comment]
Thank you, will add comments in an incoming commit.
