### ISSUE TITLE
Question: Can I launch a native GUI application inside my application?

### ISSUE THREAD

**Issue by ceremcem** [ocornut/imgui#5945]
I probably need a "yes" or "no" type answer here. If "yes", then I'll read the whole documentation to find my way out. 

I have an idea, [described here](https://github.com/ceremcem/creat-ide), which basically "Create an application and launch/display different applications within my application: 

![image](https://user-images.githubusercontent.com/6639874/205136002-311e29f8-0c43-498e-8cbc-fe83779b621b.png)

Someone [has suggested that](https://github.com/ceremcem/creat-ide/issues/1#issuecomment-1308914816) I may create this kind of application with ImGUI. 

Is it possible? Should I dive into the documentation?

**Comment by nicolasnoble** [comment]
Yes, using the docking branch.

**Comment by nicolasnoble** [comment]
Or, rather, you can *build* an application that has individual windows inside that can dock against each other, and tabs and whatnot. I'm not 100% certain I understand the "launch a native GUI" part of your question.

**Comment by ceremcem** [comment]
> Yes, using the docking branch.

That's so exciting! At last! XD

> I'm not 100% certain I understand the "launch a native GUI" part of your question.

Think that I created an application with ImGUI, that has two sub-windows inside it, like so: 

![image](https://user-images.githubusercontent.com/6639874/205139138-40e0afb9-1702-4c3a-8182-bfb0056b2466.png)

When I clicked the red button, my application will start a chromium instance inside the left window:

![image](https://user-images.githubusercontent.com/6639874/205140194-97cf821f-dd4c-4c05-865b-9b2e264666b9.png)

When I clicked the green button, my application will start a VLC instance within the right window: 

![image](https://user-images.githubusercontent.com/6639874/205140934-83b0b5f8-fef2-48c4-8a2d-800d8bd063b2.png)

**Comment by nicolasnoble** [comment]
Right. This might be a bit complex all in all, as the "other app" will need its own window management access. It's not something ImGui or really any other framework can solve for you, unfortunately. You'd need to simulate a desktop for the other app, and capture its contents, to display as a texture, and also forward relevant events such as key presses, resizes, and mouse events.

That's not going to be easy, regardless of the UI framework you'd use at the end of the day.

**Comment by ceremcem** [comment]
> It's not something ImGui or really any other framework can solve for you, unfortunately.

Oh, thank you for the correction. I was thinking so. 

It will wait a bit more, I guess.
