### ISSUE TITLE
How can I achive the Alighment Layout ?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#5946]
Just A Question.  Is there any way to achive the layout below ? 
To keep the width of the right widget not chaned whenever parent region changes. 
Thanks

![image](https://user-images.githubusercontent.com/48938612/205366426-ccade811-58f5-474e-acab-2c165f42ccc7.png)

**Comment by ocornut** [comment]
It's not lightweight, but you may use the Tables API for this. Check the demo code.

**Comment by ChivenZhang** [comment]
> It's not lightweight, but you may use the Tables API for this. Check the demo code.

OK, I'll think about it. Thanks

**Comment by zhangew** [comment]
if (ImGui::BeginTable("table1", 3))
        {
            // We could also set ImGuiTableFlags_SizingFixedFit on the table and all columns will default to ImGuiTableColumnFlags_WidthFixed.
            ImGui::TableSetupColumn("one", ImGuiTableColumnFlags_WidthFixed, 80.0f); // Default to 100.0f
            ImGui::TableSetupColumn("two", ImGuiTableColumnFlags_WidthStretch); // Default to 200.0f
            ImGui::TableSetupColumn("three", ImGuiTableColumnFlags_WidthFixed,32.0f);       // Default to auto
            ImGui::TableHeadersRow();
            for (int row = 0; row < 4; row++)
            {
                ImGui::TableNextRow();
                for (int column = 0; column < 3; column++)
                {
                    ImGui::TableSetColumnIndex(column);
                    if (row == 0)
                        ImGui::Text("(w: %5.1f)", ImGui::GetContentRegionAvail().x);
                    else
                        ImGui::Text("Hello %d,%d", column, row);
                }
            }
            ImGui::EndTable();
        }
