### ISSUE TITLE
Warning/error: cast between incompatible function types with GCC 12 (MinGW)

### ISSUE THREAD

**Issue by kemiisto** [ocornut/imgui#5947]
I have a custom of starting with `-Wall -Wextra -pedantic -Werror` flags when using GCC. And with that choice of flags compiling IMGUI using OpenGL 3 backend with GCC 12 (MinGW) results in the following error :
```
In file included from imgui/backends/imgui_impl_opengl3.cpp:142:
imgui/backends/imgui_impl_opengl3_loader.h: In function 'int open_libgl()':
imgui/backends/imgui_impl_opengl3_loader.h:620:28: error: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'GL3WglGetProcAddr' {aka 'long long int (* (*)(const char*))()'} [-Werror=cast-function-type]
  620 |     wgl_get_proc_address = (GL3WglGetProcAddr)GetProcAddress(libgl, "wglGetProcAddress");
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
```
Of course, without `-Werror` there will be "just a warning" that can be ignored, but this seems to be a known "false negative" warning of GCC >=8 that is "fixed" in many other open source projects. See, for instance, [this workaround in `boost::thread`](https://github.com/boostorg/thread/commit/c5e756d196f387076227b5fb705b7908816fc43b).

**Comment by ocornut** [comment]
Thank you for reporting!
Pushed fix 713e034
