### ISSUE TITLE
Set control position problem

### ISSUE THREAD

**Issue by LLZWWY** [ocornut/imgui#5948]
Dear ImGui, I'm a newcomer. I want to set the display position of the control myself (for example, button, text, image). I don't know how to continue. How should it be implemented?

**Comment by PathogenDavid** [comment]
`SetCursorPos` is most likely what you're looking for.

See this section of the `imgui.h` for more options and documentation:

https://github.com/ocornut/imgui/blob/844e0ae6884e6481b77fcce3339ac0fbaf659cdf/imgui.h#L431-L460
