### ISSUE TITLE
Child Windows Rendering doesn't preserve order of creation

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#595]
I am hitting some edge cases with some usage of IMGUI I am doing.
If you create a number of overlapping child windows inside the same parent window, I would expect the window sorting to follow the order of creation (if you don't change focus etc.).
In other words, this code should generate a nice sequence of ordered and colored child windows (sorry for not factoring this into a loop...)

```cpp
    ImGui::SetNextWindowPos(ImVec2(0,0),ImGuiSetCond_FirstUseEver);
    ImGui::SetNextWindowSize(ImVec2(1000,1000),ImGuiSetCond_FirstUseEver);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0);
    ImGui::Begin("container", nullptr);

    ImGui::SetNextWindowPos(ImVec2(0,0),ImGuiSetCond_FirstUseEver);
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImColor(255,0,0,255));
    ImGui::SetCursorScreenPos(ImVec2(0,0));
    ImGui::BeginChild("Test1",ImVec2(300,300));
    ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(0,0), ImVec2(300,300), ImColor(255,0,0,255));
    ImGui::EndChild();
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImColor(0,255,0,255));
    ImGui::SetCursorScreenPos(ImVec2(50,50));
    ImGui::BeginChild("Test2",ImVec2(300,300));
    ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(50,50), ImVec2(50+300,50+300), ImColor(0,255,0,255));
    ImGui::EndChild();
    ImGui::SetCursorScreenPos(ImVec2(100,100));
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImColor(0, 0,255,255));
    ImGui::BeginChild("Test3",ImVec2(300,300));
    ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(100,100), ImVec2(100+300,100+300), ImColor(0, 0,255,255));
    ImGui::EndChild();
    ImGui::SetCursorScreenPos(ImVec2(150,150));
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImColor(0,255,255,255));
    ImGui::BeginChild("Test4",ImVec2(300,300));
    ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(150,150), ImVec2(150+300,150+300), ImColor(0,255,255,255));
    ImGui::EndChild();
    ImGui::SetCursorScreenPos(ImVec2(200,200));
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImColor(255,255,0,255));
    ImGui::BeginChild("Test5",ImVec2(200+300,200+300));
    ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(200,200), ImVec2(200+300,200+300), ImColor(255,255,0,255));
    ImGui::EndChild();
    ImGui::SetCursorScreenPos(ImVec2(250,250));
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImColor(255,128,70,255));
    ImGui::BeginChild("Test6",ImVec2(300,300));
    ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(250,250), ImVec2(250+300,250+300), ImColor(255,128,70,255));
    ImGui::EndChild();
#define SHOW_ME_THE_BUG 0
#if SHOW_ME_THE_BUG
    ImGui::SetCursorScreenPos(ImVec2(300,300));
    ImGui::PushStyleColor(ImGuiCol_WindowBg, ImColor(255,0,255,255));
    ImGui::BeginChild("Test7",ImVec2(300,300));
    ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(300,300), ImVec2(300+300,300300), ImColor(255,0,255,255));
    ImGui::End();
    ImGui::PopStyleColor();
#endif
    ImGui::PopStyleColor();
    ImGui::PopStyleColor();
    ImGui::PopStyleColor();
    ImGui::PopStyleColor();
    ImGui::PopStyleColor();
    ImGui::PopStyleColor();
    ImGui::End();
    ImGui::PopStyleVar();
```
And it does!
![screen shot 2016-04-19 at 5 30 28 pm](https://cloud.githubusercontent.com/assets/5406873/14645056/84bd1eee-0654-11e6-8f88-07798de10b9b.jpg)

Now on my system , if I  set SHOW_ME_THE_BUG to 1 I get the following output.
(I am running inside Xcode 7.3, this behavior  probably depends on qsort implementation).

![screen shot 2016-04-19 at 5 30 46 pm](https://cloud.githubusercontent.com/assets/5406873/14645064/886b5d58-0654-11e6-8683-ae2043a9707e.jpg)

Tracking down the reason I can see that AddWindowToSortedBuffer is using qsort to sort children windows, but in the case that all windows have no difference in flags (so that ChildWindowComparer always returns 0), the sort is not stable, i.e. it doesn't preserve the input child window order.

```cpp
// FIXME: Add a more explicit sort order in the window structure.
static int ChildWindowComparer(const void* lhs, const void* rhs)
{
    const ImGuiWindow* a = *(const ImGuiWindow**)lhs;
    const ImGuiWindow* b = *(const ImGuiWindow**)rhs;
    if (int d = (a->Flags & ImGuiWindowFlags_Popup) - (b->Flags & ImGuiWindowFlags_Popup))
        return d;
    if (int d = (a->Flags & ImGuiWindowFlags_Tooltip) - (b->Flags & ImGuiWindowFlags_Tooltip))
        return d;
    if (int d = (a->Flags & ImGuiWindowFlags_ComboBox) - (b->Flags & ImGuiWindowFlags_ComboBox))
        return d;
    return 0;
}

static void AddWindowToSortedBuffer(ImVector<ImGuiWindow*>& out_sorted_windows, ImGuiWindow* window)
{
    out_sorted_windows.push_back(window);
    if (window->Active)
    {
        int count = window->DC.ChildWindows.Size;
        if (count > 1)
        {
            qsort(window->DC.ChildWindows.begin(), (size_t)count, sizeof(ImGuiWindow*), ChildWindowComparer);
        }
        for (int i = 0; i < count; i++)
        {
            ImGuiWindow* child = window->DC.ChildWindows[i];
            if (child->Active)
                AddWindowToSortedBuffer(out_sorted_windows, child);
        }
    }
}
```
If you're relying on the definition order to account for Z-Ordering (I do in some special cases), this is clearly a problem.
My Simple fix is to skip qsort when ChildWindowComparer always returns 0, but it's not solving the 100% of cases.

```cpp
static void AddWindowToSortedBuffer(ImVector<ImGuiWindow*>& out_sorted_windows, ImGuiWindow* window)
{
    out_sorted_windows.push_back(window);
    if (window->Active)
    {
        int count = window->DC.ChildWindows.Size;
        if (count > 1)
        {
            bool needsSort = false;
            for(int i = 0; i < count-1; i++)
            {
                if(ChildWindowComparer(window->DC.ChildWindows.begin()+i, window->DC.ChildWindows.begin()+i+1) != 0)
                {
                    needsSort = true;
                }
            }
            if(needsSort)
            qsort(window->DC.ChildWindows.begin(), (size_t)count, sizeof(ImGuiWindow*), ChildWindowComparer);
        }
        for (int i = 0; i < count; i++)
        {
            ImGuiWindow* child = window->DC.ChildWindows[i];
            if (child->Active)
                AddWindowToSortedBuffer(out_sorted_windows, child);
        }
    }
}
}
```
The right behavior would be to use a stable sorting algorithm that doesn't "randomly shuffle" the order of items that are "equal" in terms of their compare function.
I am not sending a pull request because this is not fixing general case.

**Comment by ocornut** [comment]
Thanks! Yes you are right, we need to look into a stable sort perhaps, I haven't even thoroughly looked at the performances of qsort() since the number of elements is supposed to be that small.

The simple fix would be to add an extra integer in the child window that we can use to sort. Will do that.

PS: I am hoping that you aren't using child window to do a single rectangle. I keep getting reminded that ImGui-side PushClipRect isn't exposed outside of `imgui_internal.h` and this may lead people to use child window when they could simply use a clipping rectangle sometimes.

**Comment by Pagghiu** [comment]
No, I am doing something fancier ! 😆 
I am remoting an entire "Imgui" session running inside a window that runs on another machine (Similar to the remoteimgui in browser support).
I want to re-use exiting functionality for "dumping" an array of drawlists (coming from this "remote" imgui session) into an existing window.

In the gif below, the upper software is the "master" running imgui.
The software below is a kind of "browser" that can enumerate instances of the software running on the network and connects to them, re-rendering the draw lists from the master "remote" imgui.
In a short time I will also allow input from remote etc, now it's view only.

![childwindows](https://cloud.githubusercontent.com/assets/5406873/14646337/6b49fa04-0659-11e6-8ad9-16248ff60de7.gif)

**Comment by ocornut** [comment]
!!!!!!!!

**Comment by Pagghiu** [comment]
Oh, I can do also concurrent sessions too, mixed from browser or the native app, with each view being able to do input too 😁 
Next on the list would be to create a separate Imgui Context per session, so that each unique user can interact with the gui independently (and also have a custom resolution), so it will look like a collaborative google docs session! 😎 

![cortexv5multiuser](https://cloud.githubusercontent.com/assets/5406873/14646732/e7945a68-065a-11e6-9065-0eed6b32394c.gif)

**Comment by ocornut** [comment]
Fixed.

Here's the repro
```
ImGui::Begin("Bug #595");
static int count = 6;
ImGui::DragInt("child count", &count, 0.5f);
ImVec2 base_pos = ImGui::GetCursorScreenPos();
for (int i = 0; i < count; i++)
{
    char buf[64];
    sprintf(buf, "child%d", i);
    ImGui::SetCursorScreenPos(ImVec2(base_pos.x+i*100.0f,base_pos.y+i*100.0f));
    ImGui::BeginChild(buf, ImVec2(220,220));
    ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(base_pos.x+i*100.0f,base_pos.y+i*100.0f), ImVec2(base_pos.x+i*100.0f+220.0f,base_pos.y+i*100.f+220.0f), ImColor::HSV(i*0.04f, 0.7f, 0.7f));
    ImGui::EndChild();
}
ImGui::End();
```

![bug_595](https://cloud.githubusercontent.com/assets/8225057/14647223/0c95c7f0-065d-11e6-9840-d938755cb1cf.PNG)

**Comment by Pagghiu** [comment]
:+1:  fast as always

**Comment by ocornut** [comment]
NP. Your project is totally getting showcased in the next release notes!

**Comment by Pagghiu** [comment]
The first gif still has some bugs to be fixed (svg logos are not transferred correctly...), and in the second you can see Internet Explorer lagging several seconds behind for unknown reasons.
When bugs will be fixed I can provide updated gifs that look nicer 😁 
Thanks again for fixing this one.

**Comment by ocornut** [comment]
@Pagghiu In the contexts of columns/tables v2 I would like to make a change so that the decoration of child window (border, background if any, scrollbar) would be rendered within the parent draw list. This would also remove an extraneous draw call.

The side effect of doing this is that _overlapping_ child window won't be rendered correctly. Since you were doing funky things with child window for this and animation experiment, do you know how that may affect you?

It would probably be possible to add an explicit workaround if needed. For now I'd be interested in learning any side-effect of that potential change.

**Comment by Pagghiu** [comment]
I have definitively some places where I have explicitly used overlapping child windows, controlling their rendering order.
I have 2 use cases, I think I can easily find a workaround for 1 but not so sure what to do as workaround for 2 (probably just use regular windows controlling their XY origin).

1. Breaking a very long draw list

One of the things that happened in some cases I was drawing a very long 2D path.
Such paths have many points and sometimes I have to split them in batches not bigger than 20.000 vertices to keep my imgui remote code happy on all supported backends (browser, native etc.).
So what I did to "break" the draw call and reset _VtxCurrentIdx was to start drawing in a child, then end the child when _VtxCurrentIdx > 20.000 and re create a child at the same location of the previous, "overlapping" it.
There is probably a smarter way to break the drawcall (pushing a clip rect equal to the current one?) but back in the days when I was writing this, that was the first thing that I've been trying and it worked well so no reason to touch it ;)
This is probably easily fixable with some alternative, but what I am doing is along the lines of:

```cpp
const ImVec2 wpos = ImGui::GetWindowPos();
ImGui::SetCursorScreenPos(wpos);
ImGui::BeginChild(++currentChild);
ImDrawList* dl = ImGui::GetWindowDrawList();
const int numPoints = HIGH_NUMBER; 
for (int i = 0; i < numPoints; ++i)
{
    if (dl->_VtxCurrentIdx > 20000)
    {
        ImGui::EndChild();
        ImGui::SetCursorScreenPos(wpos);
        ImGui::BeginChild(++currentChild);
        dl = ImGui::GetWindowDrawList();
    }

    // Some drawing code here that increments number of vertices
    dl->AddCircle(...);
    dl->AddCircleFilled(...);

}
```



2. Restoring a (network) dump of ImDrawLists inside a child window

When I am doing my native imgui remoting, targeting a native app (and not the web browser) I literally serialize ImDrawLists over network.
When I rebuild them at the other side I want to draw them inside a child window of the "main" application that shows the remoted view.
I adjust vertices and cliprects considering window origin and manually copy CmdBuffers, VtxBuffers and IdxBuffers like this:


```cpp
void draw()
{
    const ImVec2 windowOrigin = ImGui::GetCursorScreenPos();
    char         childName[10];
    ImDrawList* drawLists = reinterpret_cast<ImDrawList*>(drawListRawMemory);
    for (int i = 0; i < drawListsNumber; ++i)
    {
        const ImDrawList& currentDrawList = drawLists[i];
        sprintf(childName, "child%d", i);

        ImGui::BeginChild(childName, ImVec2(-1, -1), false, ImGuiWindowFlags_NoFocusOnAppearing | ImGuiWindowFlags_NoBringToFrontOnFocus);
        this->viewWidth                 = ImGui::GetContentRegionAvail().x;
        this->viewHeight                = ImGui::GetContentRegionAvail().y;
        ImDrawList& destinationDrawList = *ImGui::GetWindowDrawList();
        ImGui::EndChild();

        // Copying commands
        destinationDrawList.CmdBuffer.resize(currentDrawList.CmdBuffer.size());
        for (int idx = 0; idx < currentDrawList.CmdBuffer.size(); idx++)
        {
            destinationDrawList.CmdBuffer[idx] = currentDrawList.CmdBuffer[idx];
            destinationDrawList.CmdBuffer[idx].ClipRect.x += windowOrigin.x;
            destinationDrawList.CmdBuffer[idx].ClipRect.y += windowOrigin.y;
            destinationDrawList.CmdBuffer[idx].ClipRect.z += windowOrigin.x;
            destinationDrawList.CmdBuffer[idx].ClipRect.w += windowOrigin.y;
        }

        // Copying vertices
        destinationDrawList.VtxBuffer.resize(currentDrawList.VtxBuffer.size());
        for (int idx = 0; idx < currentDrawList.VtxBuffer.size(); idx++)
        {
            destinationDrawList.VtxBuffer[idx] = currentDrawList.VtxBuffer[idx];
            destinationDrawList.VtxBuffer[idx].pos.x += windowOrigin.x;
            destinationDrawList.VtxBuffer[idx].pos.y += windowOrigin.y;
        }

        // Copying indices
        destinationDrawList.IdxBuffer.resize(currentDrawList.IdxBuffer.size());
        for (int idx = 0; idx < currentDrawList.IdxBuffer.size(); idx++)
        {
            destinationDrawList.IdxBuffer[idx] = currentDrawList.IdxBuffer[idx];
        }

        // Fix Vertex and Index pointers so that asserts on ::End() will not be triggered
        destinationDrawList._VtxWritePtr   = destinationDrawList.VtxBuffer.Data + destinationDrawList.VtxBuffer.Size;
        destinationDrawList._IdxWritePtr   = destinationDrawList.IdxBuffer.Data + destinationDrawList.IdxBuffer.Size;
        destinationDrawList._VtxCurrentIdx = destinationDrawList.VtxBuffer.size();
        ImGui::SetCursorScreenPos(windowOrigin);
    }
}

```

**Comment by ocornut** [comment]
Thank you Stefano for your detailed answered.

Afaik (1) would not be affected, since your windows are likely to not rely on overlapping outer decorations:

- Background (ChildBg)
- Menu bar background
- Scrollbar
- Border

Those are the ones I am currently intending to move to the parent window.

Number (2) may be affected at the point where are you grabbing the ImDrawList data, **if** you are only selectively grabbing **some** drawlists from the emitting machine. However I don't think you are? There's no very reliable way to associate an ImDrawList with a specific window apart if you used the `_OwnerName` field? If you are copying all the draw lists and not just some of them it won't be a problem.

FYI for number (2), instead of offsetting vertices and clip rect I would suggest using a callback to provide this offset to your renderer, then the renderer can use a projection matrix + only offset clip rects.

**Comment by Pagghiu** [comment]
Oooh, I have been reading too fast your previous message, missing the "decorations" specifier :D 

Ok, I think (1) is not affected at all at this point.

Regarding (2) I am grabbing all drawlists, so it shouldn't be a problem either. It could be cool to selectively grab a single window drawlist for remoting single windows of an application but honestly I don't have an immediate need. When and if this becomes an actual need I will figure out a solution, and there is also the issue you're mentioning of not knowing which ImDrawList belongs to a given window.

Thanks for the callback tip! 
It should save some cpu time allowing me to do a straight memcpy on the destination drawlist. Or I could literally use the original deserialized drawlist in such callback without even copying anything, making just sure that it survives until the callback gets called.

**Comment by ocornut** [comment]
@Pagghiu FYI, on "Breaking a very long draw list", the recently added `ImGuiBackendFlags_RendererHasVtxOffset` should now allow for it.
