### ISSUE TITLE
Help with ImGui styling

### ISSUE THREAD

**Issue by NielsenDev** [ocornut/imgui#5954]
Hi Im Nielsen and Im new to c++ I did a 30 hour course on basics and instantly fell in love with Imgui. I found this repository as it was the first thing that popped up when I searched for Imgui base. I would like to learn more about imgui especially styling rounded corners. I left c# due to the fact that my work was being frowned upon by people as I used a gui editor and didn't actually code and the exe required multiple dll example Binufu, guna and more but Imgui is a standalone exe which I admire in conclusion what I need is help with Imgui styling I hope you can help me and Im deeply apologetic for the long message It would be great if you helped Have a nice day and thank you for reading.

**Comment by PathogenDavid** [comment]
Hey Nielsen, while your enthusiasm is greatly appreciated it'd be easier for us if you separated things out a bit to make your question more obvious.

> I would like to learn more about imgui especially styling rounded corners.

You can customize the style for your entire application by modifying `ImGuiStyle` before calling `ImGui::NewFrame`. You'll find several settings in there related to rounding.

(Do note though that `WindowRounding` does not work on the `docking` branch.)

https://github.com/ocornut/imgui/blob/713e034d95f6cc8a57ca504d52cb4f60da6359d9/imgui.h#L1821-L1875

If you want to customize individual windows or widgets it's better to use the `PushStyle`/`PopStyle` family of functions:

https://github.com/ocornut/imgui/blob/713e034d95f6cc8a57ca504d52cb4f60da6359d9/imgui.h#L399-L407

---------------

As an aside:

> I left c# due to the fact that my work was being frowned upon by people as I used a gui editor

Everything in this industry is frowned upon by people for one reason or another. I'd recommend sticking to whatever makes you happy and productive (and money--if that's important to you) and ignore the haters.

Writing software with C# and WPF is of no less value than with C++ and Dear ImGui. They're different tools created to meet different needs with different goals and use-cases.

**Comment by NielsenDev** [comment]
I need help with moving positions I figured stuff out

**Comment by JustaSimpleUser** [comment]
I completely identify with @NielsenDev's situation, although for different reasons.

I'm already stuck understanding the utility of the Pushxxx/Popxxx functions.  I think I understand their function - to 'save' a particular setting that applies to subsequent UI element creation calls - but I'm not seeing why they're useful.  The examples I've seen, albeit simplistic ones, seem to push a style, create an object and immediately pop the style.

I know it's my limited comprehension, because I've tried to understand the API code, but what's the real advantage/reason for using Pushxxx() and Popxxx() functions?

**Comment by GamingMinds-DanielC** [comment]
> I know it's my limited comprehension, because I've tried to understand the API code, but what's the real advantage/reason for using Pushxxx() and Popxxx() functions?

Push() and Pop() are basic stack functions. Pushing a new value on top keeps the previous value intact, popping the value from the top of the stack restores the previous value. It is just a convenient way to undo your changes once you are done. Pushing and popping is equivalent to retrieving the old value and storing it, setting your new value and after you're done, setting the value you retrieved earlier. Besides being convenient, is is less error-prone. A stack has a size, so it can be checked if it has the correct size if you are done with a window (see f.e. `ImGui::ErrorCheckEndFrameRecover()`).

If your question is why you should restore the previous value after you're done, that's simple: you don't want to potentially break the rest of the UI just to style one element.

**Comment by NielsenDev** [comment]
what?

**Comment by JustaSimpleUser** [comment]
> If your question is why you should restore the previous value after you're done, that's simple: you don't want to potentially break the rest of the UI just to style one element.

Thanks.  I completely understand the stack mechanism, but it was the logic of using it that I didn't appreciate.  I see now the return to previous style (Pop) is simpler and more reliable, avoiding potential style mismatches in different areas of the code.  Hadn't thought about that.
