### ISSUE TITLE
How to set BeginComboPreview height

### ISSUE THREAD

**Issue by llxiaoyuan** [ocornut/imgui#5963]
```C++

        if (ImGui::BeginCombo("##combo_path", NULL, ImGuiComboFlags_CustomPreview))
        {

            ...

            ImGui::EndCombo();
        }

        if (ImGui::BeginComboPreview())
        {
            ImGui::Button("dwabudciawg", { 0,200 });
            ImGui::EndComboPreview();
        }

```

![image](https://user-images.githubusercontent.com/36320938/206145867-58e34845-2985-4dd9-b4ee-0128166885ac.png)

How to set BeginComboPreview height, show button fully

**Comment by ocornut** [comment]
Framed Item height are always == `GetFrameHeight()` == `FontSize + style.FramePadding.y`, you currently can't see that height otherwise than changing e.g. FramePadding.

**Comment by ocornut** [comment]
Cross-posting for visibility:
Info: `BeginComboPreview()` has been updated in 1.93.0 WIP (IMGUI_VERSION_NUM >= 19296)
The `ImGuiComboFlags_CustomPreview` flag is not needed anymore. Read details at:
https://github.com/ocornut/imgui/issues/1658#issuecomment-5589399024
