### ISSUE TITLE
iconfont does not display

### ISSUE THREAD

**Issue by shimenga** [ocornut/imgui#5971]
![image](https://user-images.githubusercontent.com/77818664/206727733-c9d58664-6f5d-414b-a1b5-85d3ac84ecd9.png)
![image](https://user-images.githubusercontent.com/77818664/206727801-24061785-04d8-48c5-b527-11a5ef62c2cb.png)
![image](https://user-images.githubusercontent.com/77818664/206727827-46d3c44d-886b-4b43-92a3-a6e5b7c2e169.png)
![image](https://user-images.githubusercontent.com/77818664/206727902-80e19dac-2ae8-49f7-9816-3be737fc8ed7.png)
I created icontont using www.iconfont.cn

**Comment by mnesarco** [comment]
Hi, you can also use bawr to manage icon fonts locally :)
https://github.com/mnesarco/bawr
It auto generates ImGui code ready to use from your svg/font files.

**Comment by shimenga** [comment]
> Hi, you can also use bawr to manage icon fonts locally :) https://github.com/mnesarco/bawr It auto generates ImGui code ready to use from your svg/font files.
I know about this library, and I want to use it, but
![image](https://user-images.githubusercontent.com/77818664/206822775-7daf0549-2025-4eff-9499-a713116dce75.png)

**Comment by mnesarco** [comment]
@shimenga I am sorry, I don't know how to run python on windows, it looks like it cannot find fontforge which is required as well as inkscape and accessible from PATH. Maybe some windows user can assist you with that.

**Comment by PathogenDavid** [comment]
@shimenga There's two issues that stand out to me in your code:

> ![image](https://user-images.githubusercontent.com/77818664/206727733-c9d58664-6f5d-414b-a1b5-85d3ac84ecd9.png)

By default Dear ImGui will only use basic English letters from your font. Icon fonts don't use these characters, so nothing will be read. You need to specify the range used by your icon font using `glyph_ranges`.

See [this example using FontAwesome](https://github.com/ocornut/imgui/blob/91b356cf8e3f56c5457100ddbe93785e54048f22/docs/FONTS.md#using-icon-fonts) for a more concrete example.

You can confirm you've loaded the icons correctly using [the metrics window](https://github.com/ocornut/imgui/blob/91b356cf8e3f56c5457100ddbe93785e54048f22/docs/FONTS.md#readme-first).

> ![image](https://user-images.githubusercontent.com/77818664/206727801-24061785-04d8-48c5-b527-11a5ef62c2cb.png)

`&#xe68e` is the syntax for HTML entities. Dear ImGui will not parse these.

You need to encode them as UTF-8 directly. For example, the C++ equivalent of `&#xe68e` should be `\xEE\x9A\x8E`.

You can use [this online tool](https://unicode-table.com/en/E68E/) to view UTF-8 encoding of various characters. Most people use something like [IconFontCppHeaders](https://github.com/juliettef/IconFontCppHeaders) to avoid worrying about this in the first place.

-------------

As an aside, please do not post code in screenshots. It's text, just copy+paste it and use the Markdown code block syntax.
