### ISSUE TITLE
NewFrame() function takes very long to execute

### ISSUE THREAD

**Issue by FlorinSirghi** [ocornut/imgui#5972]
**Version/Branch of Dear ImGui:**

Version: 1.89.1
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler:  Clion
Operating System: Ubuntu 22.04

**My Issue/Question:**

It seems as if ImGui::NewFrame() takes very long to execute. The application gets in non responsive state, and if I press wait a couple of times it runs fine. When I run the debugger it executes ImGui::NewFrame() then I have to wait and keep pressin wait on the non-responsive prompt like 1 minute for it to get to the next instruction.

Here is my initialization function : 

int Graphics::init()
{
    if(glfwInit() == 0)
        return -1;
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE,GLFW_OPENGL_CORE_PROFILE);

    window = glfwCreateWindow(1000, 800, "Castle Wars", NULL, NULL);
    if(window == NULL)
    {
        std::cout << "Failed to create the window !\n";
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(window);
    glfwSwapInterval(1);
    glViewport(0, 0, 800, 600);

    const char* glsl_version = "#version 130";
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    ImGui::StyleColorsDark();
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init(glsl_version);

    return 1;
}

Here is the function where I use NewFrame() : 

void Graphics::draw()
{
    ImGui_ImplOpenGL3_NewFrame();

    ImGui_ImplGlfw_NewFrame();

    ImGui::NewFrame();
    ImGui::Render();

    glClearColor(0.0f, 0.6f, 1.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);

    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
}

And here is the loop, where draw gets called : 

while(!glfwWindowShouldClose(graphicsHandler.window))
{
    processInput(window);

    draw();

    glfwSwapBuffers(window);

    glfwPollEvents();
}

**Comment by ocornut** [comment]
What was your issue?

**Comment by FlorinSirghi** [comment]
I had a problem where NewFrame() function would take very long to execute,
but it was happening only when I was running my program from clion ide,
when I ran the program in command line it was fine.

sâm., 17 dec. 2022, 02:40 omar ***@***.***> a scris:
