### ISSUE TITLE
OS window title appears truncated

### ISSUE THREAD

**Issue by eleriaqueen** [ocornut/imgui#5975]
**Version/Branch of Dear ImGui:**

Version: 91b356cf8e3f56c5457100ddbe93785e54048f22
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx10 imgui_impl_win32
Compiler: GCC 12.2.0 i686-w64-mingw32
Operating System: Win10 Version 10.0.19044 Build 19044

**My Issue/Question:**

OS Window title appears truncated, should display string "Dear ImGui DirectX10 Example" but only displays "D".

**Screenshots/Video**

![Capture021-bug](https://user-images.githubusercontent.com/4411178/206849203-5d2cb5d4-2721-401b-93ec-7eb7f602089e.PNG)

**Standalone, minimal, complete and verifiable example: 

Use one of the imgui examples.

**Comment by ocornut** [comment]
Seems the same as #5961, there’s possibly an action we can do to, I gusss compile-settings may affect the Examples.

**Comment by ocornut** [comment]
The changes done for #5725 (a229a7f39 and 0a7054c7e) are breaking examples apps when compiling without `/D UNICODE`

Fixed with 98928b3 by @markreidvfx
