### ISSUE TITLE
Deployment target of OSX example is too high.

### ISSUE THREAD

**Issue by Erkaman** [ocornut/imgui#598]
In the Xcode project of the OSX example, the deployment target is set to 10.11, which is the newest version of OSX. However, this means that only people with version 10.11 installed can compile the example. And I did not have 10.11, so I could not compile...

But this is completely unnecessary, because the project does not really use any new features of 10.11.  I found that the deployment target can safely be lowered all the way to 10.7. 

We can easily lower the version by first going to `imgui/examples/apple_example/imguiex.xcodeproj/project.pbxproj`, then going to line 369:

```
MACOSX_DEPLOYMENT_TARGET = 10.11;
```

and changing it to 

```
MACOSX_DEPLOYMENT_TARGET = 10.7;
```

and then we also need to go to line 392:

```
MACOSX_DEPLOYMENT_TARGET = 10.11;
```
and change it to

```
MACOSX_DEPLOYMENT_TARGET = 10.7;
```

so by making the above two changes, we can easily lower the version.

**Comment by ocornut** [comment]
Thanks! I have applied this (blindly).
