### ISSUE TITLE
How to increase the drawlist limit?

### ISSUE THREAD

**Issue by alireza98dev** [ocornut/imgui#5986]
Hi, it seems when there are lots of elements in the draw list, ImGui could not render all of them. 
I guess it has a limit for the draw list.
When I decrease/limit the number of elements, it works fine, but when there are lots of elements that should be rendered it doesn't render the rest of my application UI.
How can I increase its limit to render all of those elements?

**Comment by ocornut** [comment]
Make sure you have asserts enabled (eg: IM_ASSERT(false) should abort your debugger and show a message). Then see if ImDrawList throws an assert and read the comments and messages are it.

We are not equipped to answer questions not following guidelines. This is too much work distracting us from working on useful topics. There are plenty of information out there, please make an effort reading what’s available and filling what we are asking you to fill.
