### ISSUE TITLE
Warning/Error: Using logical '!' when bitwise '~' was probably intended.

### ISSUE THREAD

**Issue by Zvendson** [ocornut/imgui#5987]
https://github.com/ocornut/imgui/blob/91b356cf8e3f56c5457100ddbe93785e54048f22/imgui.cpp#L1981

probably a small "error". Here is a suggestion to avoid the warning:
`int wanted = len ? len : 1;`

**Comment by ocornut** [comment]
I confirmed that `int wanted = len + (len ? 0 : 1);` gave me same codegen with various setup, whereas `len ? len : 1` didn,t so went for the earlier. Pushed 55b8ce9
