### ISSUE TITLE
Question about empty table

### ISSUE THREAD

**Issue by eclipseAce** [ocornut/imgui#5990]
It seems tables will disappear when empty.
How to keep column row visible when no rows present(empty table)?

**Comment by PathogenDavid** [comment]
The header row should appear regardless of whether there's any content.

If your table has no header row, you need to manually submit an empty row.

Please fill out the issue template. Without seeing your code we can only guess what's wrong with it.

**Comment by eclipseAce** [comment]
Sorry for the mistake, I finally got the problem after digging into the go binding libaray' s code, there is a special logic, it stops table rendering if table has no rows😂
