### ISSUE TITLE
Columns Spacing

### ISSUE THREAD

**Issue by 333testing** [ocornut/imgui#5992]
Hello how do i remove columns spacing
like this theres a little bit of spacing, the child is inside the first column.
![image](https://user-images.githubusercontent.com/119223928/207381253-6ecacd0a-9774-4056-a537-1fe3910b59ae.png)

i Tried:
`ImGuiStyle& style = ImGui::GetStyle();
style.FramePadding = ImVec2(0, 0);
style.WindowPadding = ImVec2(0, 0);`

Help!

**Comment by 333testing** [comment]
more "clear" photo:
![image](https://user-images.githubusercontent.com/119223928/207381897-c00fd5f3-5bd4-4b38-be7f-e5e1ac2a9a45.png)

**Comment by ocornut** [comment]
Question is too ambiguous to be answered. Please follow issue guidelines more precisely.
