### ISSUE TITLE
Popup windows do not disappear

### ISSUE THREAD

**Issue by Aarkham** [ocornut/imgui#5993]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.89.1
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp, also in custom engine.
Operating System: Windows

**My Issue/Question:**

I have a periodic table implementation with imgui and when I click in an element appears a pop up showing more information about that element.

Everything works fine, but I have seen that in the Windows List of the Metrics Debugger, the windows that are created for the popup do not disappear. Is this behavior the expected one?

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/8093144/207403492-1176a81a-6c9d-4c0b-81a0-f678b9943ea4.png)

![image](https://user-images.githubusercontent.com/8093144/207403353-57c4438a-58e0-43f7-bf7d-9426058667d7.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

This is the code I'm using to show the pop up, You can find the complete code in https://github.com/Aarkham/ImPeriodicTable

```

void ShowPeriodicTable()
{
  ImGui::SetNextWindowPos(ImVec2(0.0f,0.0f),ImGuiCond_Appearing);
  ImGui::SetNextWindowSize(ImVec2(kWindowInitWidth,kWindowInitHeight),ImGuiCond_Appearing);
  if(ImGui::Begin("Test",nullptr/*,ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoResize|ImGuiWindowFlags_NoMove/*|ImGuiWindowFlags_NoBackground*/))
    {
      ImGuiWindow* window = ImGui::GetCurrentWindow();

      float window_width=ImGui::GetWindowWidth();
      float window_height=ImGui::GetWindowHeight();

      ImGui::SetWindowFontScale(1.4f*window_width/kWindowInitWidth);

      float kElementWidth=(window_width-2.0f*kElementsColumns*kElementBorder-(kElementsColumns-1.0f)*kElementSeparation)/kElementsColumns;
      float kElementHeight=kElementWidth;

      if(!window->SkipItems)
        {
          for(const Element& element:kPeridicTable)
            {
              if(Button(element,kElementWidth,kElementHeight,window))
                {
                  ImGui::OpenPopup(element.m_Name);
                }
              if (ImGui::BeginPopupModal(element.m_Name,nullptr,ImGuiWindowFlags_AlwaysAutoResize))
                {
                  const float popup_width=window_width*0.7f;
                  const float popup_height=window_height*0.7f;
                  constexpr float button_width=190.f;
                  constexpr float button_height=60.f;

                  ImGui::BeginChild("popup",ImVec2(popup_width,popup_height));
                    ElementPopup(element);
                  ImGui::EndChild();

                  if (ImGui::Button("Ok", ImVec2(button_width,button_height)))
                    {
                      ImGui::CloseCurrentPopup();
                    }

                  ImGui::EndPopup();
                }
            }
        }

      ImGui::End();
    }
}
```

**Comment by PathogenDavid** [comment]
Thank you for filling out the whole issue template! 💜

> Everything works fine, but I have seen that in the Windows List of the Metrics Debugger, the windows that are created for the popup do not disappear. Is this behavior the expected one?

Yes, this is expected behavior. Dear ImGui remembers windows even when they're inactive.

It does this to ensure that they will appear in the same state if you start submitting them again. (EG: If the user hides and then shows a window, they ideally want it to reappear in the same location scrolled to the place where they last left off.)

Some ancillary data will be freed if the window is inactive for some time (1 minute by default), but as far as I'm aware windows are never completely forgotten until `ImGui::Shutdown` is called.

**Comment by ocornut** [comment]
Thanks David for your detailed, spot-on answer.
Closing this!
