### ISSUE TITLE
ImGui::InputInt jumps with diffrent values

### ISSUE THREAD

**Issue by DanielMartensson** [ocornut/imgui#5996]
**Version/Branch of Dear ImGui:**
Version: 1.88.1 
Branch: Using vcpkg

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_opengl3.cpp, also in custom engine.
Operating System: Windows

**My Issue/Question:**

I have this code

```
inputIntLimit("ECU Destination address:", (int*)&j1939->information_this_ECU.this_ECU_address, 0, 253); // 254 is the error address and 255 is broadcast address
inputIntLimit("Identity number:", (int*)&j1939->information_this_ECU.this_name.identity_number, 0, 2097151);
inputIntLimit("Manufacture code:", (int*)&j1939->information_this_ECU.this_name.manufacturer_code, 0, 2047);
inputIntLimit("Function instance:", (int*)&j1939->information_this_ECU.this_name.function_instance, 0, 31);
inputIntLimit("ECU instance:", (int*)&j1939->information_this_ECU.this_name.ECU_instance, 0, 7);
inputIntLimit("Function:", (int*)&j1939->information_this_ECU.this_name.function, 0, 255);
inputIntLimit("Vehicle system:", (int*)&j1939->information_this_ECU.this_name.vehicle_system, 0, 127);
inputIntLimit("Vehicle system instance:", (int*)&j1939->information_this_ECU.this_name.vehicle_system_instance, 0, 15);
inputIntLimit("Industry group:", (int*)&j1939->information_this_ECU.this_name.industry_group, 0, 7);
inputIntLimit("Arbitary address capable:", (int*)&j1939->information_this_ECU.this_name.arbitrary_address_capable, 0, 1);

void inputIntLimit(const char* label, int* v, int min, int max) {
	if (ImGui::InputInt(label, v)) {
		if (*v < min) {
			*v = min;
		}
		if (*v > max) {
			*v = max;
		}
	}
}
````

**The problems with ImGui::InputInt**

 * They jump from 0 to 243534543564 in just one step
 * They keep changing other fields with large steps.

![image](https://user-images.githubusercontent.com/28505229/207466043-fbd20338-c410-42c4-9793-e07402c3b513.png)

Still, my real values looks like this. Why does this happening? Is it because the pointer cast?

![image](https://user-images.githubusercontent.com/28505229/207465800-87abce5a-f8d5-4438-b31b-80b0e8abb0d2.png)

**How to reproduce this issue:**

First clone my Git repository: https://github.com/DanielMartensson/OpenSourceLogger

Then install these

```
	VCPKG dependencies
	- imgui[core,glfw-binding,opengl3-binding]:x64-windows
	- opengl:x64-windows
	- boost-asio:x64-windows
	- mysql-connector-cpp:x64-windows
	- nlohmann-json:x64-windows
```

When you are starting it, then right click to get the Main Menu, then select his button

![image](https://user-images.githubusercontent.com/28505229/207467709-f8707f96-da75-4453-99bc-9b5f09eb671b.png)

**Comment by ocornut** [comment]
> does this happening? Is it because the pointer cast?

well it depends if your values are int in the first place or not… if they are smaller types and you are using InputInt() dear imgui will read and write bytes from nearby values.

You can copy smaller value in an int on the stack to prevent this, or use InputScalar() for smaller data types. See Demo>Widgets>Data Types.

**Comment by DanielMartensson** [comment]
It's working,
