### ISSUE TITLE
Getting index of the TabItem

### ISSUE THREAD

**Issue by romansvozil** [ocornut/imgui#5997]
Hey, is there any way how could I get the current index of element in BeginTabBar/EndTabBar while having enabled ImGuiTabBarFlags_Reorderable? Was browsing the demo, but sadly didn't find anything related to that. Thanks for any answers.

Edit:
```cpp
inline static int GetTabItemIndex()
{
    ImGuiContext& g = *GImGui;
    ImGuiTabBar* tab_bar = g.CurrentTabBar;
    return tab_bar->Tabs[tab_bar->LastTabItemIdx].IndexDuringLayout;
}
```
After some checking of the implementation of the TabItems, I found out I can write something like this and so far looks like it does what I was looking for. Gonna leave it here in case someone else will need it.

**Comment by ocornut** [comment]
Also see #5853 
It seems odd to me that you would want this index. For which purpose would you use it ?

**Comment by romansvozil** [comment]
It's for my small VFX editor, where each tab is VFX object, so for my usage, it's more convenient to move the order of objects (which matters) using the ImGuiTabBarFlags_Reorderable. I understand that it's probably not made for those use-cases, but for me it works.

**Comment by ocornut** [comment]
Sorry for my late answer, I have now pushed 3d8885c with a handful of internal/low-level helpers to facilitate this.

It may little more mouthful as I didn't want to add extraneous/unnecessary helpers, but something like this should work:

```cpp
ImGuiTabBar* tab_bar = GetCurrentTabBar();
int tab_order = TabBarGetTabOrder(TabBarGetCurrentTab());
for (int n = tab_order + 1; n < tab_bar.Tabs.Size; n++)
     if (ImGuiTabItem* tab = TabBarFindTabByOrder(tab_bar, n))
         TabBarCloseTab(tab_bar, tab);
```
