### ISSUE TITLE
InputTextMultiline: Incorrect cursor navigation from end of multiline input text

### ISSUE THREAD

**Issue by spp-mattp** [ocornut/imgui#6000]
**Version/Branch of Dear ImGui:**

Version: 1.87
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32 + imgui_impl_dx11
Compiler: MSVC 2022 (v143 build tools)
Operating System: Windows 10

**My Issue/Question:**

If the cursor is at the very end of the last line of a multiline input text (that is not empty) and the user presses the Up arrow key, the cursor will move to the beginning of the last line of text, instead of moving up by one line.

**Standalone, minimal, complete and verifiable example:**
```c++
static char * text = "aaaaaaaaaaaaaaaaaaaa\nbbbbbbbbbbbbbbbbbbbb\nccccccccccccccccccccccccccc";
ImGui::InputTextMultiline("##test", text, strlen(text) + 1);
```

**Comment by ocornut** [comment]
This has been a long standing niggle in stb_textedit
I've looking into it and I think I've got a fix now:

Fix 57a5b73a4cd86ec8f7d4295010d7d082a07b806c
+ regression test https://github.com/ocornut/imgui_test_engine/commit/54061717d5395bb58704919c3695bd866cca133d

I'll let that simmer for a while before attempting a PR in stb repository.

**Comment by Voyager1th** [comment]
imstb_textedit's multiline **wordwrap** cann't suppert

**Comment by ocornut** [comment]
> I'll let that simmer for a while before attempting a PR in stb repository.

Turn out there was a bug in this change, which is now fixed:
https://github.com/ocornut/imgui/issues/6783#issuecomment-1708005641
