### ISSUE TITLE
Help! The input control missing when scrolling

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#6004]
**Version/Branch of Dear ImGui:**

Version: v1.89
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl.cpp + imgui_impl_sdl2.cpp=
Compiler: msvc
Operating System: windows 10

**My Issue/Question:**
The image below shows layout contains a table within a tree node. When I expand all of tree node and scroll window, the bottom of input controls gone missing.
Please help me because I have used imgui in company's project, and this is a serious bug I cannot fix !

Before:
![image](https://user-images.githubusercontent.com/48938612/208244587-949e3dec-e22e-433d-9bf8-b7801f738424.png)
After:
![image](https://user-images.githubusercontent.com/48938612/208244694-e8502db5-b048-44d0-84ea-4af11b4ad354.png)

![image](https://user-images.githubusercontent.com/48938612/208245918-9712d668-7591-4c47-83ab-ed89e34fb7cc.png)

**Screenshots/Video**

https://user-images.githubusercontent.com/48938612/208246189-35e957f9-8704-4740-88ff-6fda0abf2e00.mp4

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

<pre>
// The code below shows how I draw table layout which contains input controls.

ImGuiTableFlags flags = ImGuiTableFlags_SizingStretchProp | ImGuiTableFlags_PadOuterX | ImGuiTableFlags_NoBordersInBody;
if (ImGui::BeginTable((m_Text.getValue() + "##" + m_Name.getValue()).c_str(), m_ColumnNum.getValue(), flags))
{
	for (size_t i = 0; i < getChildWidgetList().getElementNum(); ++i)
	{
		if ((i % m_ColumnNum.getValue()) == 0) ImGui::TableNextRow();
		ImGui::TableNextColumn();
		ImGui::BeginGroup();
		getChildWidgetList().getElementAt(i)->update(time);
		ImGui::EndGroup();
	}
	ImGui::EndTable();
}
</pre>

**Comment by GamingMinds-DanielC** [comment]
My best guess would be that your ID stack gets messed up with multiple "identical" items, that can have weird effects. Can you verify that the items that are missing have unique IDs? If not, you can use `PushID( ... )` and `PopID()` at the appropriate places (f.e. around the contents of an expanded tree node) to ensure proper IDs.

**Comment by ChivenZhang** [comment]
> My best guess would be that your ID stack gets messed up with multiple "identical" items, that can have weird effects. Can you verify that the items that are missing have unique IDs? If not, you can use `PushID( ... )` and `PopID()` at the appropriate places (f.e. around the contents of an expanded tree node) to ensure proper IDs.

I have used std::atomic_int to allocate unique id by function fetch_add(1), and it seemed like no change. 

https://user-images.githubusercontent.com/48938612/208271654-38b99d0a-e7d0-47a0-9f21-ba033afb2699.mp4

**Comment by ocornut** [comment]
I am not sure what could cause this but it certainly looks weird. I suspect the easiest solution is you keep narrowing the code to a minimum that exhibits the bug.

You can also use Metrics/Debugger>Tools>View Table Rectangle and try to find which rectangle(s) looks incorrect for the parent table.

**Comment by ChivenZhang** [comment]
> I am not sure what could cause this but it certainly looks weird. I suspect the easiest solution is you keep narrowing the code to a minimum that exhibits the bug.
> 
> You can also use Metrics/Debugger>Tools>View Table Rectangle and try to find which rectangle(s) looks incorrect for the parent table.

This is debug info of missing table, but I cannot understand what it means.

![image](https://user-images.githubusercontent.com/48938612/208304389-6ae455e4-fa15-4045-ace1-fdd3e9864fe0.png)

**Comment by ChivenZhang** [comment]
> I am not sure what could cause this but it certainly looks weird. I suspect the easiest solution is you keep narrowing the code to a minimum that exhibits the bug.
> 
> You can also use Metrics/Debugger>Tools>View Table Rectangle and try to find which rectangle(s) looks incorrect for the parent table.

I have solved it because program has passed table layout when available width or height is negetive.
It works wrong as personal reason. Thanks everyone for help.

![image](https://user-images.githubusercontent.com/48938612/208307798-ba5b0da5-8752-4af8-b7e6-6f07db7e4bc5.png)
