### ISSUE TITLE
Concatenating two strings via SameLine breaks when first string has newline

### ISSUE THREAD

**Issue by avetharun** [ocornut/imgui#6006]
**Version/Branch of Dear ImGui:**

Version: 1.89.2 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_sdlrenderer.cpp 
Operating System: Windows

**My Issue/Question:**

When trying to concatenate a string to another via `ImGui::SameLine()` when the first string has a newline causes it to concatenate to the topmost line

**Screenshots/Video**
Not using custom symbol font:
![image](https://user-images.githubusercontent.com/80366076/208393255-e895fc01-4986-46eb-ab16-0134606dcfe0.png)
Using symbol font:
![image](https://user-images.githubusercontent.com/80366076/208393264-d73701c7-8dd9-4ecf-afd3-ffe6a5bfd3c9.png)

**Standalone, minimal, complete and verifiable example:** 
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
ImGui::Text("The bug appears here->\nbut not here ->");
ImGui::SameLine();
ImGui::Text("some_text");
ImGui::End();
```

The specific code used is as follows:
```
std::string text = "The character should not be here ->\nit should instead be here->";
ImGui::Text(text.c_str());
ImGui::SameLine();
//ImGui::PushFont(CWLGlobals::SymbolFont);
ImGui::Text("_");
//ImGui::PopFont();
```
which would produce something similar to 
![image](https://user-images.githubusercontent.com/80366076/208393779-f108a23b-9467-445f-a4be-9f4c902109f1.png)

**Comment by GamingMinds-DanielC** [comment]
That's not a bug, it just behaves different than you expected. ImGui doesn't really do text layouting, `Text( ... )` produces just a single item. An item like buttons, checkboxes and all the other widgets. ImGui arranges those items according to the instructions, but can only take the item bounding boxes into account for that. The line that `SameLine()` operates on has nothing to do with text lines internal to the item.

If you want to do append to the last text line itself, there are a few options:
- You could construct the complete text first and submit it as a single item. Same text style only.
- If you want f.e. different text colors, you could split the text on line breaks and submit them one part at a time, then `SameLine()` should work as you expect. But if you f.e. want to have different fonts with different heights in a single line, it won't allign on the base line, that gets more complicated. Automatic line breaks would also be a problem.
- There are most likely a few implementations for rich text out there, if none of them does what you need it's always possible to write a custom version.
