### ISSUE TITLE
Cursor rendering bug for a text field

### ISSUE THREAD

**Issue by Cthutu** [ocornut/imgui#601]
Hi,

When the content of one of the InputFloat3 text fields is larger than the actual text field, when you first click on it, the content is all selected but the cursor is rendered outside the text field.  You can recreate this using the demo.

![imgui_bug](https://cloud.githubusercontent.com/assets/348614/14725502/41251168-07ea-11e6-9ec5-075846efe825.png)

1. Open the Widgets collapsing header in the ImGui demo window.
2. Resize the width of the window so that the input float3 widgets are smaller than the numbers inside them.
3. Click on the first text field (out of the 3).
4. You will see the cursor in the second box.

**Comment by Cthutu** [comment]
It seems that the cursor is being rendered after the contents of the text field, but doesn't respect the size of the text field and try to scroll the text left to accomodate.

**Comment by ocornut** [comment]
I have a bizarre deja-vu of seeing this bug but no trace of a fix, in fact I had fixed it for the selection box but not the cursor.

There's two parts for the bug:
- [ ] Horizontal scrolling should probably track the cursor in this case? I don't know what may feel better considering there's no room to display the entire value here. 
- [ ] Either way the cursor should be clipped (as horizontal scrolling can be disabled with `ImGuiInputTextFlags_NoHorizontalScroll` anyway).

**Comment by ocornut** [comment]
I looked into horizontal scrolling tracking the cursor when selecting-all but it seemed wrong (more confusing) and not particularly beneficial. If there's no room to fit an entire value in the box then keeping the visual stable is less confusing. Select-all is meant to replace the entire value. 

As soon as you press right-arrow assuming you want to "edit" the value while preserving some of the content then the horizontal scrolling with follow and this felt right.

If you want to try the aborted-change you can add this line in InputTextEx():
```
    if (select_all || (hovered && !io.DoubleClickSelectsWord && io.MouseDoubleClicked[0]))
    {
        edit_state.SelectAll();
        edit_state.SelectedAllMouseLock = true;
++      edit_state.CursorFollow = true;
    }
```

Closing this as the initial reported bug is fixed :)
