### ISSUE TITLE
IM_STRV_CLASS_EXTRA requires empty IM_STRC_CLASS_EXTRA define

### ISSUE THREAD

**Issue by pezcode** [ocornut/imgui#6011]
**Version/Branch of Dear ImGui:**

Version: latest (https://github.com/ocornut/imgui/commit/2107c66bc80d0e4656c61080a98fdb7899982fbe)
Branch: features/string_view

**My Issue:**

This code:
https://github.com/ocornut/imgui/blob/2107c66bc80d0e4656c61080a98fdb7899982fbe/imgui.h#L291-L293

inserts `IM_STRV_CLASS_EXTRA` only if it finds `IM_STRC_CLASS_EXTRA` (note the STR**C** instead of STR**V**). Can be worked around easily, but I thought I'd bring it up.

**Comment by ocornut** [comment]
Apologies this was clearly a typo that happened during a rebase. I have now fixed it and rebased+force pushed the feature branch. Thank you!
