### ISSUE TITLE
Metal backend: secondary viewports are not rendered

### ISSUE THREAD

**Issue by dmirty-kuzmenko** [ocornut/imgui#6015]
Version: 18916
Branch: **<ins>docking</ins>**
Backend: **<ins>imgui_impl_metal.mm</ins>** + (imgui_impl_sdlrenderer.cpp or imgui_impl_glfw.cpp or imgui_impl_osx.mm)
Operating System: macOS 12.5 (monterey)

**My Issue/Question:**

The following happens even with example code provided by this repo.
On the **<ins>docking</ins>** branch with **<ins>metal</ins>** backend "child" windows are not rendered if they are outside of the main window (or some part of them is outside, for example a popup or something). Depending on the implementation (sdl vs glfw vs osx) they either completely greyed out or not shown at all. In terminal I get `[CAMetalLayer nextDrawable] returning nil because device is nil.` every frame.

Replacing line `id<MTLDevice> device = [bd->SharedMetalContext.depthStencilState device];` in the `imgui_impl_metal.mm` file with `id<MTLDevice> device = bd->SharedMetalContext.device;` fixes the issue (shown on the video), but I did not investigate this "fix" seriously.

**Screenshots/Video**
![imgui](https://user-images.githubusercontent.com/121183702/208950562-3b8fd913-6780-4bfb-a15c-c37f5b25f936.gif)

**Comment by ocornut** [comment]
Applied your fix, it makes sense to use `device` directly.

I consider this fixed, but but simultaneously I'm not sure I understand why this didn't happen before.?
ImGui_ImplMetal_NewFrame() does:
```cpp
if (bd->SharedMetalContext.depthStencilState == nil)
    ImGui_ImplMetal_CreateDeviceObjects(bd->SharedMetalContext.device);
```
and
```cpp
bool ImGui_ImplMetal_CreateDeviceObjects(id<MTLDevice> device)
{
    ImGui_ImplMetal_Data* bd = ImGui_ImplMetal_GetBackendData();
    MTLDepthStencilDescriptor* depthStencilDescriptor = [[MTLDepthStencilDescriptor alloc] init];
    depthStencilDescriptor.depthWriteEnabled = NO;
    depthStencilDescriptor.depthCompareFunction = MTLCompareFunctionAlways;
    bd->SharedMetalContext.depthStencilState = [device newDepthStencilStateWithDescriptor:depthStencilDescriptor];
    ImGui_ImplMetal_CreateDeviceObjectsForPlatformWindows();
    ImGui_ImplMetal_CreateFontsTexture(device);

    return true;
}
```
I would assume `depthStencilState.device` would be set there?

Previous code added by @stuartcarnie, commit 6868d11669e9a598189bfc65c05e7a40c87aa0f1 (#4821, #2778)
