### ISSUE TITLE
Crash when resizing secondary viewport window

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#6020]
**Version/Branch of Dear ImGui:**

Version: 1.89.1
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: vs2019 msvc
Operating System: windows 10

**My Issue/Question:**

I have pull the newest version of imgui, and choose gflw+opengl3 backend in vs2019 to launch. And then I enabled viewport feature and drew hello-world window out of main window, and resize it frequently, it crashed in "ImGui::RenderPlatformWindowsDefault()". It also happens when using sdl2+opengl3 backend.
Note: video below may cannot watch in webpage, you can download and have local watching.

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/48938612/209428804-a16353e9-2c48-4d41-98aa-86173c8b1d07.png)

https://user-images.githubusercontent.com/48938612/209428930-4520d7f6-e674-40fe-8bc4-e593a6d94ecb.mp4

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```

```

**Comment by ocornut** [comment]
Try to Load Symbols in the callstack to provide a full callstack, and seeif you don't have software such as Nahimic interfering?

Nahimic (and rebranded versions of it) is known to cause crashes. See #3204 #3321 #4542 #5354

**Comment by ChivenZhang** [comment]
> Try to Load Symbols in the callstack to provide a full callstack, and seeif you don't have software such as Nahimic interfering?
> 
> Nahimic (and rebranded versions of it) is known to cause crashes. See #3204 #3321 #4542 #5354

It's possible no crash in some other PC, I have tested it. So It may isnot a problem for all the user. I'll close this issue.
