### ISSUE TITLE
When you hover over a ImageButton or a Button and hold down left click the ImGui::IsWindowHovered function returns false. 

### ISSUE THREAD

**Issue by jkatsanis** [ocornut/imgui#6021]
If you hover over a button and hold down right click it returns true this is why i think this is a issue. Here is example code

```
ImGui::Begin("Windw");
if(ImGui::Button("IH", ImVec2(100, 100)))
{

}
std::cout << ImGui::IsWindowHovered();
ImGui::End();
```

**Comment by ocornut** [comment]
This is intended as the desirable default behavior. activating an item inhibit hovering over other things by default. You can see the effect eg: other buttons are not highlighted while dragging from a first button. Same thing happens with windows.

If you look at the flags for IsWindowHovered() you will find among them various ways to disable those behaviors, eg:

```
ImGuiHoveredFlags_AllowWhenBlockedByActiveItem  = 1 << 7,   // Return true even if an active item is blocking access to this item/window. Useful for Drag and Drop patterns.
```

**Comment by ocornut** [comment]
Closing and linking to same issue #5810 #5637 #1479 and #1382
