### ISSUE TITLE
ImGui simple keyinput doesnt work

### ISSUE THREAD

**Issue by sadcatttt** [ocornut/imgui#6022]
Hey so Ive been trying to code a keysystem, but the inputtext wont work
`    if (ImGui::Begin("Login", NULL, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse))
    {
        bool logged = false;
        char inputkey;
        std::string key = "test";

        ImGui::Text("Input Key:");
        ImGui::InputText("##keyinput", &inputkey, CHAR_MAX);

        if (ImGui::Button("Login"))
        {
            if (&inputkey == key)
            {
                logged = true;
            }
        }
        if (logged)
        {
        do something(I have something here, but its way to much code)
        }`
        when i try to put input, it just says ?P?? in the Inputtext and I dont find the solution :(
        I appreciate your help

**Comment by ocornut** [comment]
Sorry but #1586
