### ISSUE TITLE
I still got redefinition Error : C2572

### ISSUE THREAD

**Issue by StableOn** [ocornut/imgui#6023]
![image](https://user-images.githubusercontent.com/60432309/209723444-889075dd-cf6d-4493-a83c-d1acb6274fb4.png)

This in ( **imgui.h** file ) : 

`IMGUI_API bool          ImageButton(ImTextureID user_texture_id, const ImVec2& size, const ImVec2& uv0 = ImVec2(0,0),  const ImVec2& uv1 = ImVec2(1,1), int frame_padding = -1, const ImVec4& bg_col = ImVec4(0,0,0,0), const ImVec4& tint_col = ImVec4(1,1,1,1)); `

This in (**imgui_widgets.cpp file**) : 

` bool ImGui::ImageButton(ImTextureID user_texture_id, const ImVec2& size, const ImVec2& uv0, const ImVec2& uv1, int frame_padding, const ImVec4& bg_col, const ImVec4& tint_col)`

And I still got redefinition error!

**Comment by ocornut** [comment]
Sorry but #1586
