### ISSUE TITLE
Correct way to populate a table from a container with a large number of items

### ISSUE THREAD

**Issue by mat-r** [ocornut/imgui#6025]
```
Dear ImGui 1.89.2 WIP (18916)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201103
define: __APPLE__
define: __GNUC__=4
define: __clang_version__=14.0.0 (clang-1400.0.29.202)
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl2
io.ConfigFlags: 0x00000041
 NavEnableKeyboard
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigMacOSXBehaviors
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001406
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 800.00,600.00
io.DisplayFramebufferScale: 2.00,2.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.89.2
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl2.cpp
Compiler: Clang 14.0.0
Operating System: macOS 13.1

**My Question:**
I read and tried the table basic example. The data to populate the table is generated on the fly and in each loop iteration we generate it again.

Now, let us say I have a data set composed of two columns but thousands or even millions of rows.
The way I do it now (it is just an example to show the principle so I use only two rows):
```c++
    ImGui::Begin("Table");

    // Data represents a row in the 2-column table (id, val)
    struct Data {
        Data(int id, std::string val)
        : id{id}, val{std::move(val)} {}

        int id;
        std::string val;
    };

    // this vector is used to populate the table
    static std::vector<struct Data> vec{};

    // This flag is needed to add some data to the vector only one time.
    // Without it, data will be appended to the vector at each loop and the
    // table will grow indefinitely.
    static bool is_first_loop{true};
    if (is_first_loop) {
        vec.emplace_back(0, "a");
        vec.emplace_back(1, "b");
        is_first_loop = false;
    }

    if (ImGui::BeginTable("Table populating", 2))
    {
        // each loop, the vector is read again to populate the table
        for (const auto& row : vec) {
            ImGui::TableNextRow();
            ImGui::TableNextColumn();
            ImGui::Text("%d", row.id);
            ImGui::TableNextColumn();
            ImGui::Text("%s", row.val.c_str());
        }
        ImGui::EndTable();
    }

    ImGui::End();
```
1. As you can see, I have to use a flag (is_first_loop) to generate the data only once.
Would you handle it in a different way?

2. Each loop, the vector is read again to populate again the table.
Is there a recommended way to read the data only once, not every loop, or is it just common with immediate mode to proceed this way? If I have a large numbers of row, I suppose it is significantly wasting CPU time for no benefit.

**Comment by ocornut** [comment]
You can use the ImGuiListClipper for this purpose.
See “Demo->Tables->Vertical Scrolling, with Clipping”.

**Comment by mat-r** [comment]
1. It was just a simple example. My data is loaded from CSV files into a vector of struct and have several columns with different types. I suppose either I have to use the is_first_loop flag or the data loading should be done before the main loop.

2. Indeed the clipping feature seems to be a solution. Thanks.

**Comment by ocornut** [comment]
If you are loading a CSV file: yes, it makes sense to only load it once. Where/when you load it is up to you and what’s convenient in your codebase.

Closing as answered. Let us know if you have issues using the clipper!
