### ISSUE TITLE
Magnifying glass widget

### ISSUE THREAD

**Issue by ib00** [ocornut/imgui#6026]
Has anybody written a "magnifying glass" widget?

**Comment by ocornut** [comment]
If you didn’t find one searching here and on google it would seem not.

That would requires reading from the framebuffer into a texture, it’s not possible to do in a backend-agnostic manner.
Once you can capture your framework into a texture then it would be a matter of displaying part of that texture based on mouse position.

**Comment by ib00** [comment]
Thanks!

The closest thing I found was this:
https://github.com/andyborrell/imgui_tex_inspect

So, it looks like it's possible.

Want something more like this:
![image](https://user-images.githubusercontent.com/59011747/209978152-68a0c802-1099-4dae-8c18-67098638efd2.png)

**Comment by ocornut** [comment]
Of course it is possible but you need to obtain your framebuffer into a texture, and that's a thing you would do with your graphics API not with dear imgui.

e.g. DX11: https://stackoverflow.com/questions/10623787/directx-11-framebuffer-capture-c-no-win32-or-d3dx
OpenGL: https://community.khronos.org/t/need-fastest-way-to-grab-frame-buffer/40390

Once previous frame's framebuffer is in a texture you can display it however you like.
If you want to display a circle portion you'll need to submit vertices manually.
You can use the same trick that `AddImageRounded()` use:

```cpp
void ImDrawList::AddImageRounded(ImTextureID user_texture_id, const ImVec2& p_min, const ImVec2& p_max, const ImVec2& uv_min, const ImVec2& uv_max, ImU32 col, float rounding, ImDrawFlags flags)
{
    if ((col & IM_COL32_A_MASK) == 0)
        return;

    flags = FixRectCornerFlags(flags);
    if (rounding < 0.5f || (flags & ImDrawFlags_RoundCornersMask_) == ImDrawFlags_RoundCornersNone)
    {
        AddImage(user_texture_id, p_min, p_max, uv_min, uv_max, col);
        return;
    }

    const bool push_texture_id = user_texture_id != _CmdHeader.TextureId;
    if (push_texture_id)
        PushTextureID(user_texture_id);

    int vert_start_idx = VtxBuffer.Size;
    PathRect(p_min, p_max, rounding, flags);
    PathFillConvex(col);
    int vert_end_idx = VtxBuffer.Size;
    ImGui::ShadeVertsLinearUV(this, vert_start_idx, vert_end_idx, p_min, p_max, uv_min, uv_max, true);

    if (push_texture_id)
        PopTextureID();
}
```
Pseudo code:
```cpp
void AddImageCircle(ImTextureID user_texture_id, const ImVec2& center, float radius, const ImVec2& uv_min, const ImVec2& uv_max, ImU32 col, ImDrawFlags flags)
{
    if ((col & IM_COL32_A_MASK) == 0)
        return;

    PushTextureID(user_texture_id);
    int vert_start_idx = VtxBuffer.Size;
    AddCircleFilled(center, radius, IM_COL32_WHITE);
    int vert_end_idx = VtxBuffer.Size;
    ImGui::ShadeVertsLinearUV(this, vert_start_idx, vert_end_idx, center - ImVec2(radius,radius), center + ImVec2(radius,radius), uv_min, uv_max, true);
    PopTextureID();
}
```

Hope that helps.
