### ISSUE TITLE
Detecting when popup goes from open to closed?

### ISSUE THREAD

**Issue by Roflraging** [ocornut/imgui#603]
Sorry if I am missing something that is very obvious here, but it doesn't seem like I can detect when a popup gets closed through the popup API.

https://github.com/ocornut/imgui/blob/7ce6c18bbe662e9c6a80dd6c702952152a166e33/imgui.h#L353-L361

```
    // Popups
    IMGUI_API void          OpenPopup(const char* str_id);
    IMGUI_API bool          BeginPopup(const char* str_id);
    IMGUI_API bool          BeginPopupModal(const char* name, bool* p_opened = NULL, ImGuiWindowFlags extra_flags = 0);
    IMGUI_API bool          BeginPopupContextItem(const char* str_id, int mouse_button = 1);
    IMGUI_API bool          BeginPopupContextWindow(bool also_over_items = true, const char* str_id = NULL, int mouse_button = 1);
    IMGUI_API bool          BeginPopupContextVoid(const char* str_id = NULL, int mouse_button = 1);
    IMGUI_API void          EndPopup();
    IMGUI_API void          CloseCurrentPopup();
```

I have code that allocates memory on the start of a popup to do work inside the popup.  I'm not sure how to detect when the popup is closed so that I can be sure to free the memory.

```
    if (ImGui::IsItemHovered() && ImGui::IsMouseClicked(1))
    {
        ImGui::OpenPopup("batch edit");
        BatchEditBegin(gui, *desc, desc);
    }

    if (ImGui::BeginPopup("batch edit"))
    {
        BatchEditUpdate(gui, desc);
        ImGui::EndPopup();
    }

    // How do I know when to call BatchEditEnd() which should be called when the popup closes?
```

The best I've come up with is:

```
    if (ImGui::IsItemHovered() && ImGui::IsMouseClicked(1))
    {
        ImGui::OpenPopup("batch edit");
        BatchEditBegin(gui, *desc, desc);
    }

    if (ImGui::BeginPopup("batch edit"))
    {
        BatchEditUpdate(gui, desc);

        if (!ImGui::IsMouseHoveringWindow() && ImGui::IsMouseClicked(0))
        {
            BatchEditEnd(gui);
        }

        ImGui::EndPopup();
    }
```

This seems to work for me, but I wasn't sure if this is the best way to go about doing this?  My specific use case won't allow for Selectables() to close the popup, so I don't think I need to be worried about this here?

-Dale Kim

**Comment by ocornut** [comment]
One way would be to set a flag at the time of calling OpenPopup(), when BeginPopup() return false and that flag was set then you've noticed your popup closing.

That would still rely on you running the code, so you need to pay attention to that (perhaps if the wnidow/tool stops running you may need to cleanup is that flag was set).

I could perhaps add a helper that would tell you if a window was just closed but similarly you'd have to run that code to cleanup, so storing a state flag may be easier/better for now?

**Comment by Roflraging** [comment]
Works like a charm, thanks Omar!

With regards to the helper, it would be nice to make it obvious from the API perspective that you can detect the closure of a window.  It did not immediately occur to me that I could do this.  My imgui skill has been waning these last few weeks!

-Dale Kim

**Comment by ocornut** [comment]
Well, I not sure how to phrase that to allow users to see that pattern better. `BeginPopup` says `return true if popup if opened`. If it's not opened it's closed. If you opened it and it is now closed then it has been.. closed :P
A helper would only detect closure during a certain frame whereas doing your own compare-flag-to-what-BeginPopup returns is actually more flexible.

**Comment by Roflraging** [comment]
Yeah, I chalk this one up to just me forgetting how imgui fundamentally works.

Just requires the programmer to understand what's going on.

Part of it might just be that I almost always split my 1920x1080 text screen in two vertical sections so lots of the comments get cut off for me and is difficult to notice while just browsing through the headers.  Not a huge issue with the design of your API, in my opinion!
