### ISSUE TITLE
Weird rounding issue on scrolling

### ISSUE THREAD

**Issue by aw1875** [ocornut/imgui#6030]
**Version/Branch of Dear ImGui:**
Version: 1.89.1
Branch: Docking

**Back-end/Renderer/Compiler/OS**
DirectX 11

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Operating System: Windows 11

**My Issue/Question:**
I'm currently working on making a custom dropdown but I've noticed that I get this weird rounding issue when scrolling. To get this working I'm currently using rendering my items in a new window that has a position relative to the dropdown button. I wanted to get this fixed before I work out all the styling of the application. There very well could be an issue with how I set it up so any help is appreciated. Thanks!

**Screenshots/Video**

![2022-12-30 00-08-43](https://user-images.githubusercontent.com/4970015/210037052-6023fc00-a789-4584-b5ba-5a42fc29983c.gif)

Sorry that the gif is a little slow but hopefully it still shows the issue appropriately.

**Standalone, minimal, complete and verifiable example:**
This is an example of my code block that should be easy to reproduce. The only thing missing here would be my `items` which is just a vector of strings.
```cpp
ImGui::Begin(label, &isOpen, ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground);
ImGui::BeginListBox(label, ImVec2(ImGui::GetContentRegionAvail().x, items.size() > 6 ? ImGui::GetContentRegionAvail().y - size.y + 4 : items.size() * size.y + 4));
for (std::string item : items)
{
    if (ImGui::Button(item.c_str(), ImVec2(-1, size.y)))
    {
        selectedValue = item;
        isOpen = !isOpen;
    }
}
ImGui::EndListBox();
ImGui::End();
```

I've also tried pushing both style vars and the issue is still present:
```cpp
ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 5.f);
ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 5.f);
```

**_Edit:_** I just want to clarify that I want the corners to be rounded and the issue is that they aren't if you've scrolled the opposite way to the max (top is not rounded when scrolled to bottom, etc).

**Comment by PathogenDavid** [comment]
Thanks for filling out the whole issue template! In the future though, it'd be ideal if you could provide something we can just copy+paste into one of the official example apps.

I had to make some assumptions about your style parameters, but here's a more minimal repro I came up with:

```cpp
static void GH6030()
{
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 20.f);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, { 0.f, 20.f });
    ImGui::PushStyleColor(ImGuiCol_Button, { 0.35f, 0.40f, 0.61f, 1.f });
    ImGui::SetNextWindowSize({ 200.f, 100.f });
    ImGui::Begin("GH-6030", nullptr, ImGuiWindowFlags_NoDecoration);
    ImGui::Button("Button", { -1.f, 32.f });
    ImGui::Button("Button", { -1.f, 32.f });
    ImGui::Button("Button", { -1.f, 32.f });
    ImGui::Button("Button", { -1.f, 32.f });
    ImGui::Button("Button", { -1.f, 32.f });
    ImGui::End();
    ImGui::PopStyleColor();
    ImGui::PopStyleVar(2);
}
```

What I believe is happening in your app (and what is definitely happening in my repro) is that as your scroll your buttons are entering the rounded area.

Dear ImGui only handles rectangles for fine-grained clipping using the GPU's scissor rect. Not sure if this is something Omar plans on improving, solving it properly would be non-trivial.

Things which appear to be clipped by rounding parameters like [the resize grip](https://github.com/ocornut/imgui/blob/e57871bb95faec757e51214bc0e1ae29b13258ab/imgui.cpp#L5841) are actually special-cased.

------------

For an app like yours, an easy workaround might be adding your own special `Begin`/`End` helpers to submit the window as normal and then manually draw inverted curved corners using the background color.

Anything more robust would probably involve modifying the backend to use the stencil buffer or something like that.

**Comment by aw1875** [comment]
Hi David,

Really appreciate the quick response. I must have been super tired when I submitted the issue because I now realize I'm missing quite a bit from my code sample. I wanted to resend a sample to see if you noticed anything else.

```c++
// My initial styles
ImGuiStyle* style = &ImGui::GetStyle();
style->WindowPadding = ImVec2(0, 0);
style->WindowRounding = 0.f;
style->WindowBorderSize = 0.f;
style->FrameBorderSize = 0.f;

style->Colors[ImGuiCol_WindowBg] = ImColor(26, 166, 183, 255);
style->Colors[ImGuiCol_FrameBg] = ImColor(255, 65, 77, 255);

style->Colors[ImGuiCol_Button] = ImColor(217, 236, 242, 255);
style->Colors[ImGuiCol_ButtonHovered] = ImColor(217, 236, 242, 255);
style->Colors[ImGuiCol_ButtonActive] = ImColor(217, 236, 242, 225);

style->Colors[ImGuiCol_Text] = ImColor(255, 65, 77, 255);


// Variables being passed in
ImVec2 pos = ImVec2(10, 50);
ImVec2 size = ImVec2(ImGui::GetContentRegionAvail().x - 20, 40);
ImColor col = ImColor(217, 236, 242, 255);
ImColor hoverCol = ImColor(200, 236, 242, 255);
static bool isOpen = true;    // being toggled with a button of course
std::vector<std::string> items = {
    "Example",
    "Example",
    "Example",
    "Example",
    "Example",
    "Example",
    "Example",
    "Example",
    "Example",
};
std::string selectedValue = "Select Item";

// Dropdown example
ImGui::SetNextWindowPos(ImVec2(pos.x, pos.y * 2));
ImGui::SetNextWindowSize(ImVec2(ImGui::GetContentRegionAvail().x - 20, items.size() > 6 ? ImGui::GetContentRegionAvail().y - size.y + 4 : items.size() * size.y + 4));
ImGui::PushStyleColor(ImGuiCol_FrameBg, (ImVec4)col);
ImGui::PushStyleColor(ImGuiCol_ButtonHovered, (ImVec4)hoverCol);
ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 5.f);
ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 5.f);
ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0, 0));

ImGui::Begin("##dropdownExample", &isOpen, ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground);
ImGui::BeginListBox("##dropdownExample", ImVec2(ImGui::GetContentRegionAvail().x, items.size() > 6 ? ImGui::GetContentRegionAvail().y - size.y + 4 : items.size() * size.y + 4));
for (std::string item : items)
{
    if (ImGui::Button(item.c_str(), ImVec2(-1, size.y)))
    {
        selectedValue = item;
        isOpen = !isOpen;
    }
}

ImGui::PopStyleVar();
ImGui::PopStyleVar();
ImGui::PopStyleVar();
ImGui::PopStyleColor();
ImGui::PopStyleColor();
ImGui::EndListBox();
ImGui::End();
```

If you don't notice anything different with this example (which should be complete now) I can look more into your suggestion above. Thanks!

**Comment by ocornut** [comment]
As answered by @PathogenDavid, region clipping is done using scissoring rectangles.

**As such, items near the rounding corners won't be clipped correctly.
This is usually not a problem as generally we use style values where `Rounding <= Padding`.
If `Rounding > Padding` then items will appears in the rounding region and you'll have this issue.**

I am not expecting to provide a better solution for this anytime soon.
I would simply recommend changing settings: either you increase Padding, either you decrease Rounding.

There are workaround as David mentioned but there are quite complicated.
- Inverted curves overlapping parent background may not work as 1) it's a convex shape, and 2) childs are always drawn after parent.
- If you do custom rendering for those button background you can mitigate the issue and maybe get away with it, but text will exhibit same issue, not only the background shape, so when you resize things to be small you'll need the issue again. 
- Unless you use, e.g. stenciled rendering (which requires deeper understanding of GPU/graphics programming, may be overkill but possible) you'll always end up with this issues. If you don't know what a stencil buffer is, it's probably not worth investigating this route.

(Note that `BeginListBox()` uses `ImGuiStyleVar_FramePadding`: it basically copy FramePadding to WindowPadding when doing the `Begin()` call).
