### ISSUE TITLE
imgui_impl_sdl.cpp + imgui_impl_sdl_renderer.cpp use #include "SDL.h" instead of #include "SDL2/SDL.h" - SDL3 is under development so this is relevant now.

### ISSUE THREAD

**Issue by jkmunson** [ocornut/imgui#6031]
**Version/Branch of Dear ImGui:**

Version: 1.89.1
Branch: Master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_sdl_renderer.cpp
Operating System:  Any

**My Issue**

SDL is meant to have the /include/ directory included by the compiler, not /include/SDL2/. This allows differentiating between SDL.h (sdl1), SDL.h (sdl2), and SDL.h(sdl3). For some reason the popular LazyFoo sdl2 tutorials have linux #include "SDL2/SDL.h" properly, but on windows instructs the user to do #include "SDL.h", which is likely where the issue stems from.

I would just submit a PR, but I realize this can break people's existing build processes.

SDL3 is under development, so this is relevant now.

Change
#include "SDL.h"
to
#include "SDL2/SDL.h"

In both files, then fix the build process.

**Comment by ocornut** [comment]
Hello,

This has already been discussed in #5234, I think your conclusions are incorrect, “SDL.h” is the right name to include as reported by sdl-config.

The fact that SDL3 is in development, and even assuming that it would break some API doesn’t change a thing: we can perfectly make our backend support both versions.

**Comment by jkmunson** [comment]
It looks like this is already a decided issue already, discussed at length in #5234 .
