### ISSUE TITLE
Question: Clickable bars in PlotHistogram

### ISSUE THREAD

**Issue by samuelpmish** [ocornut/imgui#6033]
Hi,

First, Dear ImGui has been incredibly useful in my personal projects, so thanks for creating/maintaining this library!

My question is: is there a way to detect mouse interaction with a PlotHistogram widget? 

I'm using it to report statistics on some objects in my scene, and was hoping to maybe highlight the objects associated with a given bin when hovering over / clicking that bin in the histogram, if that's possible. The bins in the plot already highlight when hovering them, is there a way to register a callback to events like that, or query if the mouse cursor is hovering over a specific bin?

Thank you

**Comment by ocornut** [comment]
This is similar to #201 and #2670
But at this point those ImGui Plot functions are almost legacy functions and unlike to be improved, as we’d favor using ImPlot which has many more features:
https://github.com/epezent/implot
