### ISSUE TITLE
Why a "Debug" dialog popup when closing the window ?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#6037]
**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_SDL2.cpp + imgui_impl_OpenGL3.cpp
Compiler: vs2019 msvc
Operating System: windows 10

**My Issue/Question:**

Hello, I would like to know why does imgui popup an empty dialog when I closed a window which using the docking feature ?
How can I solve it ? Thanks.

**Screenshots/Video**

Before close window:
![image](https://user-images.githubusercontent.com/48938612/210163363-cb7e3f1f-7d5c-46cd-97c3-6c4887fb4ea5.png)
After close window:
![image](https://user-images.githubusercontent.com/48938612/210163379-1ae0ae1a-24fe-4925-8d4c-c40493308963.png)
Codes relative in imgui.cpp.NewFrame()
![image](https://user-images.githubusercontent.com/48938612/210163386-205b2660-f880-4ed1-be8b-b604ce40124c.png)

**Comment by ocornut** [comment]
Normally the implicit Debug window is only visible is something was submitted to it. It means, unless there is a bug, that you are performing an action outside of a Begin/End block when that window is closed.

You’ll need to check your code for it.

Happy new year!

**Comment by ChivenZhang** [comment]
> 

Happy new year, emmm, another tough time for me.

**Comment by ChivenZhang** [comment]
> > 
> 
> Happy new year, emmm, another tough time for me.

Thanks, I have solved it.

**Comment by ChivenZhang** [comment]
> Normally the implicit Debug window is only visible is something was submitted to it. It means, unless there is a bug, that you are performing an action outside of a Begin/End block when that window is closed.
> 
> You’ll need to check your code for it.
> 
> Happy new year!

![image](https://user-images.githubusercontent.com/48938612/210299821-746f4639-79cd-4aad-bc2e-514b99964fda.png)

I'm confused about the logic above. I need to create a docking layout window, as the codes, when it runs into the visible branch, it works well. But when I close the window, it should keep the docking layout which line 17 make. The problem is that If I do this, it will popup a "Debug" dialog. So what should I do to close docking window correctly and not to popup debug dialog? 
Thanks.

**Comment by ocornut** [comment]
Hello,
Thanks for clarifying.
This was indeed a bug: when using `ImGuiDockNodeFlags_KeepAliveOnly` the `DockSpace()` function is not meant to emit an item, and therefore shouldn't mark the current window as written to.
This is now fixed with 824baa6a4d01acf588cda09a27f5320f6d066ac9

Thanks for reporting.

**Comment by ChivenZhang** [comment]
> Hello, Thanks for clarifying. This was indeed a bug: when using `ImGuiDockNodeFlags_KeepAliveOnly` the `DockSpace()` function is not meant to emit an item, and therefore shouldn't mark the current window as written to. This is now fixed with [824baa6](https://github.com/ocornut/imgui/commit/824baa6a4d01acf588cda09a27f5320f6d066ac9)
> 
> Thanks for reporting.

It solved my problem, Thanks
