### ISSUE TITLE
Dock invisible window to keep user settings for disappearing windows

### ISSUE THREAD

**Issue by mgerhardy** [ocornut/imgui#6038]
```
Dear ImGui 1.89.2 WIP (18916)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: IMGUI_DISABLE_OBSOLETE_KEYIO
define: __linux__
define: __GNUC__=12
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl
io.BackendRendererName: testimgui
io.ConfigFlags: 0x0000C041
 NavEnableKeyboard
 DockingEnable
 DpiEnableScaleViewports
 DpiEnableScaleFonts
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 3 fonts, Flags: 0x00000000, TexSize: 2048,4096
io.DisplaySize: 2560.00,1440.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 4.00,4.00
style.WindowBorderSize: 1.00
style.FramePadding: 6.00,4.00
style.FrameRounding: 3.00
style.FrameBorderSize: 2.00
style.ItemSpacing: 6.00,2.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.89.2 WIP (18916)
Branch: docking - 693967637266ff48fd247821acd0c6cdf66eda6d

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp
Operating System: Linux

**My Issue/Question:**

I'm writing an editor with multiple modes for the main viewport. One mode has a few windows that aren't visible in other modes. These windows are docked by

```c++
	_dockIdMain = ImGui::GetID("DockSpace");
	const bool existingLayout = ImGui::DockBuilderGetNode(_dockIdMain);
	ImGui::DockSpace(_dockIdMain);

	if (!existingLayout && viewport->WorkSize.x > 0.0f) {
		ImGui::DockBuilderAddNode(_dockIdMain, ImGuiDockNodeFlags_DockSpace);
		ImGui::DockBuilderSetNodeSize(_dockIdMain, viewport->WorkSize);
		ImGuiID dockIdLeft = ImGui::DockBuilderSplitNode(_dockIdMain, ImGuiDir_Left, 0.13f, nullptr, &_dockIdMain);
		ImGuiID dockIdRight = ImGui::DockBuilderSplitNode(_dockIdMain, ImGuiDir_Right, 0.20f, nullptr, &_dockIdMain);
		ImGuiID dockIdLeftDown = ImGui::DockBuilderSplitNode(dockIdLeft, ImGuiDir_Down, 0.35f, nullptr, &dockIdLeft);
		ImGuiID dockIdRightDown = ImGui::DockBuilderSplitNode(dockIdRight, ImGuiDir_Down, 0.50f, nullptr, &dockIdRight);
		ImGuiID dockIdMainDown = ImGui::DockBuilderSplitNode(_dockIdMain, ImGuiDir_Down, 0.20f, nullptr, &_dockIdMain);

		ImGui::DockBuilderDockWindow(TITLE_SCRIPT_EDITOR, dockIdMainDown);
		ImGui::DockBuilderDockWindow(TITLE_ANIMATION_TIMELINE, dockIdMainDown);
	}
```

https://github.com/mgerhardy/vengi/blob/425b971552db090420fa92173e194643e8a2f0ef/src/tools/voxedit/modules/voxedit-ui/MainWindow.cpp#L570

It's about the windows with the ids `TITLE_SCRIPT_EDITOR` and `TITLE_ANIMATION_TIMELINE`.

to preserve the user settings, i do check if the dock node already exists. Thus i don't have the `dockIdMainDown` in a second run of the application.

I've tried various ways with `ImGui::SetNextWindowDockID(dockId, ImGuiCond_Appearing);` and somehow get to the correct dock id. But all of this is a hack and didn't work properly in all situations.

My question is this: Is it possible to dock an invisible window somehow? Such that I can keep the user settings in the ini files persisted but don't see the empty windows? If the user closes the application with some of the windows being invisible (no `ImGui::Begin()`) then the settings are lost, too.

This is rendering the window title - but nothing inside the window - but there is no window flag (afaik) that registers but doesn't render a window.

```cpp
       if (ImGui::Begin(TITLE_SCRIPT_EDITOR)) {
               if (editMode != EditMode::Scene) {
                       ImGui::End();
                       return false;
               }
              [....]
       }
```

**Screenshots/Video**

Animation view visible
![Bildschirmfoto vom 2023-01-02 19-49-32](https://user-images.githubusercontent.com/577713/210269399-89579415-e940-4b8f-9f67-e2c6c83bb752.png)

Changing the editor mode will hide the animation window (not executing the code path at all
![Bildschirmfoto vom 2023-01-02 19-49-28](https://user-images.githubusercontent.com/577713/210269400-5d584b3b-7aea-4e3b-98f8-21a5eb49f13e.png)

Always rendering the windows - even if they should be invisible (due to the editor mode)
![Bildschirmfoto vom 2023-01-02 20-04-49](https://user-images.githubusercontent.com/577713/210270419-af271746-70a6-4256-97b0-cbe0f0272907.png)

**Comment by ocornut** [comment]
Hello Martin,
I am not sure I fully understand what's going on.

> to preserve the user settings, i do check if the dock node already exists. Thus i don't have the dockIdMainDown in a second run of the application.

Yes, that makes sense.

> I've tried various ways with ImGui::SetNextWindowDockID(dockId, ImGuiCond_Appearing); and somehow get to the correct dock id. But all of this is a hack and didn't work properly in all situations.

I don't understand this. You already called `DockBuilderDockWindow()`, why would you need to call `SetNextWindowDockID()` ?

> My question is this: Is it possible to dock an invisible window somehow? 

This is what `DockBuilderDockWindow()` does.
`DockBuilderDockWindow()` **DOES** handle non-visible windows, it doesn't matter for it whether the window is visible or not.
It also handle windows that are not existing yet (weren't created in the session):

```cpp
void ImGui::DockBuilderDockWindow(const char* window_name, ImGuiID node_id)
{
    // We don't preserve relative order of multiple docked windows (by clearing DockOrder back to -1)
    ImGuiID window_id = ImHashStr(window_name);
    if (ImGuiWindow* window = FindWindowByID(window_id))
    {
        // Apply to created window
        SetWindowDock(window, node_id, ImGuiCond_Always);
        window->DockOrder = -1;
    }
    else
    {
        // Apply to settings
        ImGuiWindowSettings* settings = FindWindowSettings(window_id);
        if (settings == NULL)
            settings = CreateNewWindowSettings(window_name);
        settings->DockId = node_id;
        settings->DockOrder = -1;
    }
}
```

**Comment by mgerhardy** [comment]
Thanks a lot for your answer. It led my into the right direction. With the confirmation that it should work out of the box I was able to solve the issue. It was a wrong free running flag `ImGuiWindowFlags_NoSavedSettings` that I put there because the title initially changed with the scene name - but this was removed and the flag was wrong. Sorry for the noise - it works perfectly now.

**Comment by ocornut** [comment]
Good to hear!

FYI if you want to get back to title changing with scene name, you may use `###` to lock an identifier, e.g. `My Filename###MainEditor`.
- Ref: Demo -> Examples -> Manipulating Window Titles.
- And https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#qa-usage
