### ISSUE TITLE
Opening a combo box in a popup dialog makes the background fade back in

### ISSUE THREAD

**Issue by marcojez** [ocornut/imgui#604]
In my application I have a main window, a modal popup within the context of that window, and a combo box (among other widgets) in the popup. When the modal pops up (first picture), it correctly fades the background out to the color I've specified. But if I click on the combo box so that its items become visible (second picture), then the background fades in. It then fades out again when the combo box loses focus.

Any help? Is it a bug, or do I need to take special measures to prevent it from happening?

![shot1](https://cloud.githubusercontent.com/assets/15309612/14748487/447af7ee-08ba-11e6-8d1b-e2f5d3958128.jpg)

![shot2](https://cloud.githubusercontent.com/assets/15309612/14748488/46d495e0-08ba-11e6-9850-c590bac2ef3e.jpg)

**Comment by ocornut** [comment]
Looks like a bug to me!

**Comment by ocornut** [comment]
Fixed!

**Comment by marcojez** [comment]
Great, thank you!
