### ISSUE TITLE
Multi-viewport memory leak with GLFW/OpenGL3 on W10

### ISSUE THREAD

**Issue by altaitai** [ocornut/imgui#6041]
**Version/Branch of Dear ImGui:**

Version: 1.89.2 WIP (18916)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: VS2019 SDK 10.0 (v142)
Operating System: Windows 10

**My Issue/Question:**

I noticed a memory leak on the stack when running the multi-viewport branch in my project. It's currently reproducible in the `example_glfw_opengl3` project in the official VS solution. The leak happens in `ImGui_ImplOpenGL3_RenderDrawData` and `ImGui::RenderPlatformWindowsDefault` specifically when we move a window outside of the main viewport. When the window is moved in, the leak stops and the memory usage comes back to the idle state.

**Screenshots/Video**

![2023-01-03_14-22-13](https://user-images.githubusercontent.com/31286897/210426929-2a7ec6d6-c701-4d0c-9c40-f21868b5a6de.gif)

**Standalone, minimal, complete and verifiable example:**

[GLFW/OpenGL3 Example](https://github.com/ocornut/imgui/blob/docking/examples/example_glfw_opengl3/main.cpp)

**Comment by ocornut** [comment]
We've circled around this forever and it seems to be a bug in Intel GPU drivers that apparently was fixed last year?

- Please confirm/provide GPU and Driver Version + after please try to update drivers?

- Reference: see b8b0f9d02e81060a96f17bf8359b2a95e8d646e4 (issues #4468, #4504, #3381, #2981, #4825, #4832, #5127)

- Try to change `bd->UseBufferSubData = false;` to `= true` in imgui_impl_opengl3.cpp.

**Comment by altaitai** [comment]
> We've circled around this forever and it seems to be a bug in Intel GPU drivers that apparently was fixed last year?
> 
> * Please confirm/provide GPU and Driver Version + after please try to update drivers?
> * Reference: see [b8b0f9d](https://github.com/ocornut/imgui/commit/b8b0f9d02e81060a96f17bf8359b2a95e8d646e4) (issues [Memory leak with with viewports when using OpenGL3 backend #4468](https://github.com/ocornut/imgui/issues/4468), [multi-viewport  memory leaks #4504](https://github.com/ocornut/imgui/issues/4504), [Memory leak on resize of secondary viewport #3381](https://github.com/ocornut/imgui/issues/3381), [Possible memory leak. opengl3 #2981](https://github.com/ocornut/imgui/issues/2981), [Access violation on the line of `glBufferSubData()` #4825](https://github.com/ocornut/imgui/issues/4825), [Multi-viewports rendering artifacts with OpenGL backend on 1.86 #4832](https://github.com/ocornut/imgui/issues/4832), [Windows Blinking On OpenGL3 Problem #5127](https://github.com/ocornut/imgui/issues/5127))

Thanks for the quick reply, this is most likely the issue. Drivers on the test machine are outdated (January 2021) and I cannot update them, but fortunately I was able to re-test on another GPU which worked fine. Closing as a duplicate of the mentioned issue.
