### ISSUE TITLE
Custom draw widget/Using images in widgets?

### ISSUE THREAD

**Issue by wn2000** [ocornut/imgui#6044]
I’ve been using ImGui for some simple UI need and like it a lot.

I do feel that the look and feel of the widgets are very “structured”, in the sense that they resemble those in a desktop application. And most efforts to customize it are limited to colors and styles.

Is it possible to completely customize how a widget is drawn? I know there’s an ImageButton. What about using an image (or two) for a SliderFloat for example?
If so are there any examples how this can be done? I want to create an “unstructured” effect like UIs in a game.

**Comment by ocornut** [comment]
You'll need to dig into widget code and write your own widgets.
Stuff like `SliderFloat()` have underlying low-level helpers such as `SliderBehavior()` which can be used.
Be wary you are pushing against the tide here, may or not be worth the effort, depending on your confidence and experience.
