### ISSUE TITLE
How can I use "PushID()" to identify different window ?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#6046]
Hello, I want to use PushID() instead of "##ID" label to identify different windows, but when I create two window in this way, there is only one window all the time. So how can I achieve this ? Thanks.
Codes below shows what I want to do. 

<pre>
{
	static bool visible1 = true;
	if (visible1)
	{
		ImGui::PushID(111);
		ImGui::SetNextWindowSize(ImVec2(500, 500), ImGuiCond_Appearing);
		if (ImGui::Begin("WIN", &visible1))
		{
		}
		ImGui::End();
		ImGui::PopID();
	}
}

{
	static bool visible1 = true;
	if (visible1)
	{
		ImGui::PushID(222);
		ImGui::SetNextWindowSize(ImVec2(500, 500), ImGuiCond_Appearing);
		if (ImGui::Begin("WIN", &visible1))
		{
		}
		ImGui::End();
		ImGui::PopID();
	}
}
</pre>

**Comment by ocornut** [comment]
Window names are not affected by the ID stack. 
You can generate a window name that include some hash/value derived from the ID stack though:

ImGui::PushID(111);
sprintf(“window_%08x”, ImGui::GetID(“”));
ImGui::PopID();
