### ISSUE TITLE
Moving Image issue with scrollbars

### ISSUE THREAD

**Issue by ypujante** [ocornut/imgui#6051]
First I want to apologize for the title of this issue, as I am not too sure how to name it.

It is much better described with an image:

![imgui-frame-issue](https://user-images.githubusercontent.com/357116/211079606-0a69c64c-bb09-4e4c-b528-592ffffa38ab.gif)

This is the code that generates this issue:

```cpp
  static float zoom = 3.0f;
  static bool slowFrameRate = false;

  if(ImGui::Begin("re-edit", nullptr, ImGuiWindowFlags_AlwaysAutoResize))
  {
    if(ImGui::InputFloat("zoom", &zoom, 0.5f, 1.0f))
    {
      if(zoom < 1.0f)
        zoom = 1.0f;
    }
    ImGui::SliderFloat("zoom2", &zoom, 1.0f, 5.0f);

    ImGui::Checkbox("artificially slow frame rate", &slowFrameRate);
    if(slowFrameRate)
    {
      // need to include <thread> and <chrono> for this to compile
      std::this_thread::sleep_for(std::chrono::milliseconds(250));
    }
  }
  ImGui::End();

  if(ImGui::Begin("image", nullptr, ImGuiWindowFlags_HorizontalScrollbar))
  {
    ImGuiIO& io = ImGui::GetIO();
    ImTextureID my_tex_id = io.Fonts->TexID;
    float my_tex_w = (float)io.Fonts->TexWidth;
    float my_tex_h = (float)io.Fonts->TexHeight;
    {
      ImGui::Text("%.0fx%.0f", my_tex_w, my_tex_h);
      ImVec2 uv_min = ImVec2(0.0f, 0.0f);                 // Top-left
      ImVec2 uv_max = ImVec2(1.0f, 1.0f);                 // Lower-right
      ImVec4 tint_col = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);   // No tint
      ImVec4 border_col = ImVec4(1.0f, 1.0f, 1.0f, 0.5f); // 50% opaque white
      ImGui::Image(my_tex_id, ImVec2(my_tex_w * zoom, my_tex_h * zoom), uv_min, uv_max, tint_col, border_col);
    }
  }
  ImGui::End();
```

I have used the code from the ImGui demo to generate the image. The size of the image is driven by the zoom factor.

To reproduce:

* once you open the project, make sure the "image" window is small enough to show the scrollbars
* scroll all the way to the right
* reduce the zoom and notice how the image keeps on moving left/right (the capture before is only at 10fps so it doesn't show quite well what is happening)
* You can enable the artificial slow frame rate to really get a grasp of what is happening: the entire image moves left then right giving this jarring effect of instability

Note that if you are scrolled all the way to the left (or in the middle) it does not happen. It only happens when the scroll is all the way to the right

**Comment by ocornut** [comment]
Scrolling range is updated with a one-frame latency based on the contents size of previous frame.
Using `ImGui::SetNextWindowContentSize()` you may specify (prior to `Begin()`) the content size that will be used for scrolling.

**Comment by ypujante** [comment]
I confirm that using this code instead:

```cpp
    ImGuiIO &io = ImGui::GetIO();
    ImTextureID my_tex_id = io.Fonts->TexID;
    float my_tex_w = (float) io.Fonts->TexWidth;
    float my_tex_h = (float) io.Fonts->TexHeight;
    ImVec2 imageSize{my_tex_w * zoom, my_tex_h * zoom};

    ImGui::SetNextWindowContentSize(imageSize);
    
    if(ImGui::Begin("image", nullptr, ImGuiWindowFlags_HorizontalScrollbar))
    {
      {
        ImGui::Text("%.0fx%.0f", my_tex_w, my_tex_h);
        ImVec2 uv_min = ImVec2(0.0f, 0.0f);                 // Top-left
        ImVec2 uv_max = ImVec2(1.0f, 1.0f);                 // Lower-right
        ImVec4 tint_col = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);   // No tint
        ImVec4 border_col = ImVec4(1.0f, 1.0f, 1.0f, 0.5f); // 50% opaque white
        ImGui::Image(my_tex_id, imageSize, uv_min, uv_max, tint_col, border_col);
      }
    }
    ImGui::End();
```

fixes the issue entirely

**Comment by ypujante** [comment]
I have another similar issue due to scrolling (which is why I am reopening this issue vs creating another one, but let me know if you'd rather have another one). I am trying to do a zoom with a target (in this instance a cross) being centered.

I wrote the following code:

```cpp
{
  static float zoom = 1.3f;
  static float previous_zoom = zoom;
  static constexpr ImVec4 tint_col = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);   // No tint
  static constexpr ImVec4 border_col = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);
  static bool slowFrameRate = false;

  static ImVec2 scroll{};
  static ImVec2 maxScroll{};

  ImGuiIO &io = ImGui::GetIO();
  ImTextureID my_tex_id = io.Fonts->TexID;
  ImVec2 panelSize{static_cast<float>(io.Fonts->TexWidth), static_cast<float>(io.Fonts->TexHeight)};

  static ImVec2 cross{panelSize / 2.0f};

  if(ImGui::Begin("re-edit", nullptr, ImGuiWindowFlags_AlwaysAutoResize))
  {
    ImGui::SliderFloat("zoom", &zoom, 0.1f, 2.0f);
    ImGui::SameLine();
    if(ImGui::Button("+")) { zoom += 0.1; }
    ImGui::SameLine();
    if(ImGui::Button("-")) { zoom -= 0.1; }
    auto mpos = ImGui::GetMousePos();
    ImGui::Text("abs. mouse pos=%.0fx%.0f", mpos.x, mpos.y);
    ImGui::Text("scroll=%.0fx%.0f, max=%.0fx%.0f", scroll.x, scroll.y, maxScroll.x, maxScroll.y);
    ImGui::Checkbox("artificially slow frame rate", &slowFrameRate);
    if(slowFrameRate)
    {
      // need to include <thread> and <chrono> for this to compile
      std::this_thread::sleep_for(std::chrono::milliseconds(250));
    }
  }

  ImGui::End();

  ImVec2 imageSize = panelSize * zoom;

  if(ImGui::Begin("image", nullptr, ImGuiWindowFlags_HorizontalScrollbar))
  {
    auto cp = ImGui::GetCursorPos();
    ImGui::Image(my_tex_id, imageSize, {}, {1.0f, 1.0f}, tint_col, border_col);
    ImGui::SetCursorPos(cp);
    DrawX(cross, zoom);
    if(previous_zoom != zoom)
    {
      auto const csp = ImGui::GetCursorScreenPos();
      auto smp = csp + (cross * zoom) ;
      ImGui::SetCursorScreenPos(smp);
      ImGui::Dummy({1.0, 1.0});
      ImGui::SetScrollHereX();
    }

    scroll = { ImGui::GetScrollX(), ImGui::GetScrollY() };
    maxScroll = { ImGui::GetScrollMaxX(), ImGui::GetScrollMaxY() };

  }
  ImGui::End();
  previous_zoom = zoom;
}
``` 

![imgui-scroll-issue](https://user-images.githubusercontent.com/357116/212559720-3d82cfcd-6f65-4b02-867a-6b2270851bd2.gif)

I am not sure if I am doing something wrong and/or if there is a way to do better. I see that there is a `ImGui::SetNextWindowScroll` api, I tried using it as well, but it has the same result.

Is there a way for me to fix this issue?

Thank you 

PS: the `Draw` functions are defined this way, although they are irrelevant for the issue (but if you just need to copy/paste... here they are)

```cpp
void DrawLine(const ImVec2& iP1, const ImVec2& iP2, float iZoom, ImU32 iColor, float iThickness = 1.0f)
{
  auto const cp = ImGui::GetCursorScreenPos();
  auto drawList = ImGui::GetWindowDrawList();
  drawList->AddLine(cp + iP1 * iZoom, cp + iP2 * iZoom, iColor, iThickness);
}

void DrawX(ImVec2 const &iPosition, float iZoom = 1.0f)
{
  static constexpr auto kSize = 10.0f;
  static constexpr ImU32 kColor = 4278255615;
  DrawLine({iPosition.x - kSize, iPosition.y - kSize}, {iPosition.x + kSize, iPosition.y + kSize}, iZoom, kColor);
  DrawLine({iPosition.x - kSize, iPosition.y + kSize}, {iPosition.x + kSize, iPosition.y - kSize}, iZoom, kColor);
}
```

**Comment by ypujante** [comment]
I am going to close this issue. In the end I decided to implement my own canvas concept (inspired by the one from the demo) and removed the scrollbar entirely. As can be seen in this short animation, I handle click drag to move the canvas around (offset), as well as zooming in/out (in this video via the mouse wheel) and preserving the focus point to wherever the mouse is located (which is why when I zoom in/out on top of the knob, the knob remains in the "same" position... what happens is the canvas get offsetted accordingly). The end result is super smooth (animation is recorded at 10fps so doesn't show...) with no hiccups and I am very satisfied with how it turned out.

![re-edit-canvas](https://user-images.githubusercontent.com/357116/213771138-48b40424-7767-42df-b4fd-63a26544a9c2.gif)

If you are interested in the source code, it is publicly available on github:

- the [Canvas.h](https://github.com/pongasoft/re-edit/blob/v1.2.0/src/cpp/re/edit/Canvas.h) api
- the [Canvas.cpp](https://github.com/pongasoft/re-edit/blob/v1.2.0/src/cpp/re/edit/Canvas.cpp) implementation
- the [canvas begin/end call](https://github.com/pongasoft/re-edit/blob/v1.2.0/src/cpp/re/edit/PanelState.cpp#L209)
- the [main usage](https://github.com/pongasoft/re-edit/blob/v1.2.0/src/cpp/re/edit/Panel.cpp#L91) which includes keyboard/mouse wheel handling

**Comment by ocornut** [comment]
Good to hear. I should have specified that scrolling/scrollbar is merely a high-level concept that can be ignored for custom view, typically node editors are doing the same thing.

![image](https://user-images.githubusercontent.com/8225057/213774001-52f07bae-e1c1-42b7-b0cf-1c265501c137.png)

The Canvas in the Demo does this:
```cpp
ImGui::InvisibleButton("canvas", canvas_sz, ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_MouseButtonRight);
[...]
const float mouse_threshold_for_pan = opt_enable_context_menu ? -1.0f : 0.0f;
if (is_active && ImGui::IsMouseDragging(ImGuiMouseButton_Right, mouse_threshold_for_pan))
    scrolling += io.MouseDelta;
```
Then contents are offset by the value of `scrolling`. You don't need much more.


The "issue" with scrollbar is we visually display the range and need to maintain that range based on submitted contents, so there's often an ordering problem for that kind of issue.

**Comment by ypujante** [comment]
@ocornut yes, seeing this demo about the canvas, especially the dragging behavior, inspired me to implement it in a similar fashion
