### ISSUE TITLE
I'm getting an error. I couldn't identify the cause.(ImGuiListClipper) 

### ISSUE THREAD

**Issue by leth4lweap0n** [ocornut/imgui#6054]
I get an error when I filter..

![Capture1](https://user-images.githubusercontent.com/24867168/211102490-58d19017-7b7b-48f9-9792-30e3d1cacf8e.PNG)
![Capture2](https://user-images.githubusercontent.com/24867168/211102525-1dd0cbf2-cc8f-4c5d-a4e3-30bd196412aa.PNG)
![Capture3](https://user-images.githubusercontent.com/24867168/211102529-42ad8a1a-1f0f-4ccf-afc4-273d996b1460.PNG)

```cpp
if (static ImGuiTableFlags flags = ImGuiTableFlags_RowBg | ImGuiTableFlags_BordersOuter | ImGuiTableFlags_BordersV | ImGuiTableFlags_NoBordersInBody | ImGuiTableFlags_ScrollY; ImGui::BeginTable("##ItemSettingsTable", 2, flags, ImVec2(0.0 f, 200. f), 0.0 f)) {
   if (!Engine.SupplyItemSettings.empty()) {
      ImGui::TableSetupColumn(reinterpret_cast <
         const char * > (u8 "İtem Adı"), ImGuiTableColumnFlags_WidthFixed, 250.0 f);
      ImGui::TableSetupColumn(reinterpret_cast <
         const char * > (u8 "İşlem Durumu"), ImGuiTableColumnFlags_WidthFixed, ImGui::GetContentRegionAvail().x);
      //ImGui::TableSetupScrollFreeze(0, 1);
      ImGui::TableHeadersRow();

      std::string search_string(search_text);
      ranges::transform(search_string, search_string.begin(), ::tolower);

      int row_n = 0;
      for (auto & x: Engine.SupplyItemSettings) {
         std::string item_name_lower(x -> ItemName);
         ranges::transform(item_name_lower, item_name_lower.begin(), ::tolower);
         if (search_string.empty() || item_name_lower.find(search_string) != std::string::npos)
            row_n++;

      }

      ImGuiListClipper clipper;
      clipper.Begin(row_n);
      while (clipper.Step()) {
         for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; i++) {
            auto & item = Engine.SupplyItemSettings[i];
            std::string item_name_lower(item -> ItemName);
            ranges::transform(item_name_lower, item_name_lower.begin(), ::tolower);
            if (search_string.empty() || item_name_lower.find(search_string) != std::string::npos) {
               ImGui::PushID(i);
               ImGui::TableNextColumn();
               ImGui::Text(item -> ItemName.c_str());
               ImGui::TableNextColumn();
               ImGui::PushItemWidth(150. f);
               int selected_index = item -> ProcessType;
               if (ImGui::Combo("##PTC", & selected_index, process_type_names, IM_ARRAYSIZE(process_type_names))) {
                  item -> ProcessType = static_cast < e_ItemProcessType > (selected_index);
               }
               ImGui::PopItemWidth();
               ImGui::PopID();
            }
         }
      }
      clipper.End();
   }

   ImGui::EndTable();
}
```

**Comment by leth4lweap0n** [comment]
I updated the code like this, the problem is gone. But there is a fps problem. There is a maximum of 3700 items in this list.
what should I do?

`if (static ImGuiTableFlags flags = ImGuiTableFlags_RowBg | ImGuiTableFlags_BordersOuter | ImGuiTableFlags_BordersV | ImGuiTableFlags_NoBordersInBody | ImGuiTableFlags_ScrollY; ImGui::BeginTable("##SellTable", 2, flags, ImVec2(0.0 f, 200. f), 0.0 f)) {
  if (!Engine.SupplyItemSettings.empty()) {
    ImGui::TableSetupColumn(reinterpret_cast <
      const char * > (u8 "İtem Adı"), ImGuiTableColumnFlags_WidthFixed, 250.0 f);
    ImGui::TableSetupColumn(reinterpret_cast <
      const char * > (u8 "İşlem Durumu"), ImGuiTableColumnFlags_WidthFixed, ImGui::GetContentRegionAvail().x);
    ImGui::TableSetupScrollFreeze(0, 1);
    ImGui::TableHeadersRow();

    std::string search_string(search_text);
    ranges::transform(search_string, search_string.begin(), ::tolower);

    vector < DWORD > rows_to_display;
    ranges::for_each(Engine.SupplyItemSettings, [ & ](const SSupplyItemSettings * x) {
      std::string item_name_lower(x -> ItemName);
      boost::to_lower(item_name_lower);
      ranges::transform(item_name_lower, item_name_lower.begin(), ::tolower);
      if (search_string.empty() || item_name_lower.find(search_string) != std::string::npos)
        rows_to_display.push_back(x -> ID - 1);
    });

    ImGuiListClipper clipper;
    clipper.Begin(static_cast < int > (rows_to_display.size()), 20. f);
    while (clipper.Step()) {
      for (int row = clipper.DisplayStart; row < clipper.DisplayEnd; row++) {
        auto & x = Engine.SupplyItemSettings[rows_to_display[row]];
        ImGui::PushID(static_cast < int > (x -> ID));
        ImGui::TableNextColumn();
        ImGui::Text(x -> ItemName.c_str());
        ImGui::TableNextColumn();
        ImGui::PushItemWidth(150. f);
        int selected_index = x -> ProcessType;
        if (ImGui::Combo("##PTC", & selected_index, process_type_names, IM_ARRAYSIZE(process_type_names)))
          x -> ProcessType = static_cast < e_ItemProcessType > (selected_index);
        ImGui::PopItemWidth();
        ImGui::PopID();
      }
    }
    //vector<DWORD>().swap(rows_to_display);
    clipper.End();
  }

  ImGui::EndTable();
}`

**Comment by ocornut** [comment]
Sorry but #1586 

If you have performances issues use random debug-break to do some simple profiling, or a real profiler, and you’ll find out where your bottleneck is. Your bottleneck is probably not in the clipper loop but in the earlier one: vector allocations not amortized (so multiple reallocs + copies), many other allocations/copies with your use of strings. Even if you were running the full filter over 3600 elements every frame it could be ten times faster if you avoid the multiple allocations and copies. Other than that you can also preserve that filtered list as a last resort.
