### ISSUE TITLE
Weird imgui window style

### ISSUE THREAD

**Issue by xbyte3** [ocornut/imgui#6055]
I don't know why, but it looks like this.
And I can't click on any of buttons and e.t.c.
![image](https://user-images.githubusercontent.com/74019853/211138909-caec62e8-5228-4f40-a500-a4cd8a8e02bc.png)
```
extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

LRESULT _stdcall WndProc(const HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam) {
    if (ImGui_ImplWin32_WndProcHandler(hwnd, uMsg, wParam, lParam))
        return true;
    return CallWindowProc(oWndProc, hwnd, uMsg, wParam, lParam);
}
```
Windows 10, DX9

**Comment by ocornut** [comment]
Hello,

> I don't know why, but it looks like this.

This is a srgb/gamma correction issue. 
You may roughly correct it by applying a pow(1.0f/2.2f) in the pixel shader.


> And I can't click on any of buttons and e.t.c.

Cannot help without more details and effort on your side.
Please carefully refer to `examples/example_win32_directx9/` for reference.
