### ISSUE TITLE
Calculate correct image round when it is a shifted background image

### ISSUE THREAD

**Issue by HCCix** [ocornut/imgui#6058]
**Hi, im using this useful lib and i met with a problem and i would like to ask for some support.**

Im using images as background in some rounded rectangle, those images shifted on x and y axis by different px from rectangle's base x and y position.

The problem is that, when i give round on rencangle and of course on images too, the image has same round like rectangle, but it is not correct, because of image's x and y  position y is not same as rectangle's x and y and that should not inherit same round from parent rectangle. 

I would like to corp the image corners currectly and give a correct round to the image included in the shifted x and y position which.
For exmaple when the rectangle size is 420x310px and its position is x: 40px, y: 40px and its background image size is 400x290px and its position is x: 43px (rectangle position x + 3), y: 47px (rectangle position y + 7) then the image's round is different (lower) then the rectangle's round and corped by the rectangles rounds.

Here is the current image render code, its supports the different corner rounds:
```
int VertextStartIDX = DrawList->VtxBuffer.Size;
for (int i = CORNER_TOP_LEFT; i < CORNER_NUM; i++)
{
	float Rounded = 10.0f;
	if (Rounded >= 1.0f)
	{
		Rounded = ImMin(Rounded, ImFabs(m_Max.x - m_Min.x) * 0.5f - 1.0f);
		Rounded = ImMin(Rounded, ImFabs(m_Max.y - m_Min.y) * 0.5f - 1.0f);
	}

	switch (i)
	{
		case CORNER_TOP_LEFT: DrawList->PathArcToFast(ImVec2(m_Min.x + Rounded, m_Min.y + Rounded), Rounded, 6, 9); break;
		case CORNER_TOP_RIGHT: DrawList->PathArcToFast(ImVec2(m_Max.x - Rounded, m_Min.y + Rounded), Rounded, 9, 12); break;
		case CORNER_BOTTOM_RIGHT: DrawList->PathArcToFast(ImVec2(m_Max.x - Rounded, m_Max.y - Rounded), Rounded, 0, 3); break;
		case CORNER_BOTTOM_LEFT: DrawList->PathArcToFast(ImVec2(m_Min.x + Rounded, m_Max.y - Rounded), Rounded, 3, 6); break;
	}
}

DrawList->PathFillConvex(IM_COL32_WHITE);
int VertextEndIDX = DrawList->VtxBuffer.Size;
ImGui::ShadeVertsLinearUV(DrawList, VertextStartIDX, VertextEndIDX, m_Min, m_Max, m_Uv0, m_Uv1, true);
```

I attached a presentation what i would like say, i marked the wanted result with red line and the current result with yellow line:
https://imgur.com/a/8F2nw9G
![present-problem](https://user-images.githubusercontent.com/121184485/211200947-903d0a64-32bd-4612-aedb-661b5a5f935d.jpg)

Thank you for suggestions and helps.

**Comment by HCCix** [comment]
The problem is like this:
https://stackoverflow.com/questions/10616668/how-to-hide-canvas-content-from-parent-rounded-corners-in-any-webkit-for-mac

Another presentation of problem:
![another-prew](https://user-images.githubusercontent.com/121184485/211215246-b74cf693-abb6-4c17-880f-a9133e327d4f.jpg)

**Comment by ocornut** [comment]
Seems like the same as #6030 
Rounded clipping is not supported and won’t be supported.
