### ISSUE TITLE
GetWindowSize() without the title bar

### ISSUE THREAD

**Issue by ypujante** [ocornut/imgui#6060]
I am trying to implement a "zoom to fit" feature for my application. My code looks something like this:

```cpp
  static float zoom = 1.0f;

  ImGuiIO &io = ImGui::GetIO();
  ImTextureID my_tex_id = io.Fonts->TexID;
  ImVec2 my_tex_size{static_cast<float>(io.Fonts->TexWidth), static_cast<float>(io.Fonts->TexHeight)};

  if(ImGui::Begin("re-edit", nullptr, ImGuiWindowFlags_AlwaysAutoResize))
  {
    if(ImGui::Button("Zoom to fit"))
    {
      if(ImGui::Begin("image", nullptr, ImGuiWindowFlags_HorizontalScrollbar))
      {
        auto windowSize = ImGui::GetWindowSize();
        auto const &style = ImGui::GetStyle();
        auto factor = (windowSize - (style.WindowPadding * 2)) / my_tex_size;
        zoom = std::min(factor.x, factor.y);
      }
      ImGui::End();
    }
  }
  ImGui::End();

  ImVec2 imageSize = my_tex_size * zoom;

  ImGui::SetNextWindowContentSize(imageSize);

  if(ImGui::Begin("image", nullptr, ImGuiWindowFlags_HorizontalScrollbar))
  {
    {
      ImVec2 uv_min = ImVec2(0.0f, 0.0f);                 // Top-left
      ImVec2 uv_max = ImVec2(1.0f, 1.0f);                 // Lower-right
      ImVec4 tint_col = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);   // No tint
      ImVec4 border_col = ImVec4(1.0f, 1.0f, 1.0f, 0.5f); // 50% opaque white
      ImGui::Image(my_tex_id, imageSize, uv_min, uv_max, tint_col, border_col);
    }
  }
  ImGui::End();
```

I have tried really hard to find an answer while looking at issues and the source code, but I am kind of stuck so here are my questions:

1) I could not find a way to get access to the size of a window without using the `ImGui::Begin() / ImGui::End()` from within the button trigger. It doesn't seem that there is a `ImGui::GetWindowSize("image")` API available (for example there is a `FindWindowByName` API but it is not exposed outside the internal code)

2) this code works well for the width but not for the height. It seems that `ImGui::GetWindowSize()` returns the height of the window which includes the title bar. I really need something like `ImGui::GetWindowSize().y - height_of_title_bar_if_not_collpased` (because of course the title bar can be collapsed). I have looked at other variants of the API, but none of them seems to return what I need. (Note that I am using the docking branch so when the window is docked there is an icon to collapse the title bar entirely)

Thank you

**Comment by ocornut** [comment]
`GetWindowSize()` is rarely useful.
I think you want to use e.g. `GetContentRegionAvail()` after `Begin()` to get the size of the contents region assuming no scrolling, then you don't need to remove window padding manually.
Use `Metrics/Debugger->Tools` to see what rectangle correspond to.

**Comment by ypujante** [comment]
`GetContentRegionAvail()` does not work at all in my case (I do not know what I might be doing wrong).

Using the tool you point to, I see this:

<img width="1216" alt="Screen Shot 2023-01-08 at 11 38 47" src="https://user-images.githubusercontent.com/357116/211215476-64c7e82a-8caf-4f28-8cbf-e40c0bda158d.png">

It clearly seems that I need access to the `InnerRect` section and from the source code, that seems to be exactly what I need:

```cpp
struct IMGUI_API ImGuiWindow
{
// ...
    ImRect InnerRect; // Inner rectangle (omit title bar, menu bar, scroll bar)
// ...
};
```

I just don't see how I to access this API from outside and `GetContentRegionAvail()` is not returning this info.

**Comment by ypujante** [comment]
After more digging and trial and error, this is what actually works:

```cpp
    auto const &style = ImGui::GetStyle();
    auto windowSize = ImGui::GetCurrentWindowRead()->OuterRectClipped.GetSize();
    auto factor = (windowSize - (style.WindowPadding * 2)) / my_tex_size;
    zoom = std::min(factor.x, factor.y);
```

Thank you for you help.

**Comment by ocornut** [comment]
GetContentRegionAvail() is the correct api to use but you are not specifying what’s wrong with it nor how you tried to use it. Use those internals fields at your own risk.

**Comment by ocornut** [comment]
Good point. There's no public API for that either, but using window->ScrollbarSizes.x/.y should work.
