### ISSUE TITLE
ImGui::InputText takes size_t as buffer size argument, internally uses int

### ISSUE THREAD

**Issue by skuyuy** [ocornut/imgui#6061]
**Version/Branch of Dear ImGui:**

Version: 1.89 WIP (`#define IMGUI_VERSION_NUM 18832`)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl.cpp
Compiler: MSVC 14.30.30705
Operating System: Windows 11

**My Issue/Question:**
I realized this while debugging:

The ImGui::InputText takes a argument `buf_size` as a `size_t`. This in turn calls `InputTextEx` which takes `buf_size` as an `int`.  This is fine as long as `size_t` is as big as an unsigned int, but breaks as soon as the size_t value is bigger, which can potentially happen on all the operating systems where size_t is a bigger data type (see example). Cant be reproduced with buffers of type `char[]` since the maximum array length is `INT_MAX` as well, but can be reproduced with char pointers or buffers of unknown size (in my example, a `std::string` buffer). The same issue arises if `size_t` is an alias of `unsigned int`, since `unsigned int` can still have bigger values than `int` and would therefore be casted wrongly. Due to the downcast of `size_t` to `int`, `buf_size` gets changed to -1.
While I know there are more than enough workarounds for this, it would still be nice if that type safety was guaranteed.

**Screenshots/Video**
![devenv_eqMLYjUmCh](https://user-images.githubusercontent.com/42264311/211218477-fc145112-3301-4327-bec5-f0a3a489c0db.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
std::string str;
ImGui::InputText("Using SIZE_MAX", str.data(), SIZE_MAX); // asserts buf_size >= 0 is false
ImGui::End();
```

**Comment by ocornut** [comment]
Dear ImGui is designed to run on safe data and focused on solving productivity issues. It is not designed toward supporting cases of that sort. If you start looking for those I guarantee you’ll find many more.

As such this is a won’t fix.
