### ISSUE TITLE
ImGui window failing to render after another external window is running

### ISSUE THREAD

**Issue by sFIsAnExpert** [ocornut/imgui#6069]
As a beginner in using ImGui, I'm having issues to where as the title states the ImGui window fails to render anything after I run it before opening up another external window such as the game "Rainbow Six Siege". After debugging the errors I have found are all related to nullptr errors resulting from the following functions. "ImGui_ImplDX9_SwapBuffers", and "ImGui_ImplDX9_RenderWindow". Which both call ImGuiViewportDataDx9* which is the structure that ends up being null. After checking if its not nullptr the exceptions stop but this then causes ImGui to fail its rendering. I am very confused, also note that in ImGui_ImplDX9_RenderWindow function, LPDIRECT3DSURFACE9 rendertarget & LPDIRECT3DSURFACE9 lastrendertarget causes a nullptr exception aswell.

        g_pd3dDevice->GetRenderTarget(0, &last_render_target); //nullptr exception here
        g_pd3dDevice->SetRenderTarget(0, render_target); //same with here
        ImGuiViewportDataDx9* data = (ImGuiViewportDataDx9*)viewport->RendererUserData; //just calling this in any function causes a nullptr.

Remember this only happens AFTER I load up an external window that takes up my entire screen. And note what I mean by failing to render is that sliders dont move and checkboxes arent checked but in the backend they are functioning properly.

**Comment by GamingMinds-DanielC** [comment]
What happens here is that the game requests exclusive full screen access, basically taking the device away from your backend. Not specifically ImGui related, I would expect similar problems with other apps that use Direct3D for rendering. Potentially other APIs as well.

You should first look in the graphics options of Rainbow Six Siege if it supports alternate modes. Most games today use a full screen window that doesn't need exclusive access, maybe something like that is an option in Siege as well, even though it is a bit older now.

Have you tried detecting device loss and resetting? Take a look at `ResetDevice()` in `examples/example_win32_directx9/main.cpp` as a reference. If that doesn't work for you, do you specifically need a DX9 renderer or can you use others that might not have the same problem? If you need DX9, do you need GPU acceleration or would f.e. a software based reference rasterizer suffice?

**Comment by sFIsAnExpert** [comment]
@GamingMinds-DanielC ah I see what you mean, and I tried to look in the graphic settings for R6 and I did not find anything dealing with alternate modes. I failed to mention earlier I am multi-threading in a ImGui::Checkbox and detaching it from the main thread. Which this is where my rendering issues started happening with r6, I am trying to find a solution to this and I know ImGui isn't thread safe but the thread is necessary for my program. I haven't tried detecting device loss or resetting, I am kind of confused on the matter. I can't call ResetDevice() anywhere nor access that file. I don't need it to be specifically DX9/ImGui. Anything would suffice really I just want a clean Gui so my friends can use the program without confusion. Thanks for all the help!

**Comment by GamingMinds-DanielC** [comment]
> I haven't tried detecting device loss or resetting, I am kind of confused on the matter. I can't call ResetDevice() anywhere nor access that file.

That file is not part of the API, you won't be able to call that function if you don't have it in your sources. It is part of the examples, usually taken as a starting point or as a reference, in your case a reference. You can just take a look at the examples subfolder to see many implementations. In this case to copy the `ResetDevice()` function and take a look at when to call it.

About "multi-threading in a ImGui::Checkbox"... do you mean you commit a checkbox to ImGui from a different thread than the main thread (or whichever thread constructs the rest of your UI)? That sounds dangerous. Unless you properly synchronize those different threads, then it sounds very tedious. It is usually best to keep the UI on a single thread. Just as a suggestion, you could f.e. push value changes into message queues for other threads for asynchronous handling. Those threads could post results (or other messages) into a message queue for the main thread which can then process these at the start of the UI update loop.

**Comment by ocornut** [comment]
I appreciate the helping intent but:
- Gives little details nor repro, our starting point is ambiguous.
- OP is #1586 adjacent if not it.
- Adds a whole new ambiguous amount of can of worm mentioning multi-threading.

This is all fixable but it's probably more of an issue with your setup than something to change in our backends.

Giving our time and energy solving esoteric issues, for potentially unethical uses, with people that are making it harder to be helped is detrimental to progress of Dear ImGui and of helping a larger majority of users. I'm afraid we need to keep a focusing stance. It's a deep pit of attention hogs and help vampires out there. We've all been there, many of us have been that person, I do have empathy for them, but in the larger scheme of things they are detracting us from doing better and being helpful to more people :/

I'm closing this being not a Dear ImGui issue, but feel free to discuss it here if desired.

**Comment by GamingMinds-DanielC** [comment]
>     * OP is [Community stance: the situation with cheaters #1586](https://github.com/ocornut/imgui/issues/1586) adjacent if not it.

Took a look at the OPs other repos just now and you are absolutely right. There's even a "fake" virus that is still real computer sabotage, lots of red flags. From the initial question I just assumed device loss due to otherwise unrelated games.
