### ISSUE TITLE
ListBox Add Option for list of Highlighted Indices?

### ISSUE THREAD

**Issue by odbee** [ocornut/imgui#6070]
Hey, i would like to aks for a feature that would help me out a ton in my development, and maybe it helps a few other people as well. The current ListBox command takes a list and an index and highlights the index in the list. what I would like to ask for, is to add another optional input, where you can put a list of indices, to display in an alternative color.

I have made a quick mockup to further explain my request. Please let me know if it is possible.
![mockup](https://user-images.githubusercontent.com/28735705/211729929-954a0e25-3f76-4401-8176-6c37f92d1b4b.jpg)

**Comment by ocornut** [comment]
Hello,
Using BeginListBox() / EndListBox() you can easily submit any kind of contents in your listbox. Typically you would submit Selectables and you can alter their selected state and color however you like.
