### ISSUE TITLE
Icon font in title bar bug

### ISSUE THREAD

**Issue by pavanakumar** [ocornut/imgui#6072]
When I use Icon fonts in title bar of ImGui windows the mouse position goes bizarre. It adds some offset to the mouse position that makes clicking and dragging impossible.

I use the GLFW3+GLAD+OpenGL backend and see this problem both on Mac and Linux.

**Comment by ocornut** [comment]
I don't think those two things are any related.
Please provide evidence and a repro. Lacking those we can consider this. 
If you post evidence and a repro we'll reopen the issue.

Consider adding a toggle to enable/disable the icon in title bar (e.g. `io.KeyShift ? "Title Without Icon###Title" : "Title With Icon###Title`) so you can rule out other factors.
