### ISSUE TITLE
After render ImGui::Dummy change size box

### ISSUE THREAD

**Issue by Barashuk** [ocornut/imgui#6075]
Version: ImGui 1.89.2 WIP (18916)
Brach: master
Back-ends: imgui_impl_dx9.cpp + imgui_impl_win9.cpp
Compiler: _MSC_VER=1929
Operating System: Windows 10

Question: I'm trying to make a selection of the entire row and I have it in two lines. I tried using Imgui::Selectable, but I ran into a problem that only one line is allocated. I decided to render using DrawList::QuadFilled. The size is determined as I need. I also decided to add an item for him through ImGui::Dummy, so that you can use the methods for working with items. After adding it noticed that the Dummy changes size.

Without ImGui::Dummy
![image](https://user-images.githubusercontent.com/8094947/212427393-4fe00585-7f0a-4642-9e66-fda2f201e156.png)

With ImGui::Dummy
![DirectX_9_App_LYYF4eprE8](https://user-images.githubusercontent.com/8094947/212427298-83763b90-3677-4f62-8e8b-5a3e96bf750d.png)

```
auto drawBox = [](const ImVec2& pos, const ImVec2& size, const ImU32 &color) {
	auto list = ImGui::GetWindowDrawList();
	list->AddQuadFilled({ pos.x, pos.y }, { pos.x + size.x, pos.y }, { pos.x + size.x, pos.y + size.y }, { pos.x, pos.y + size.y }, color);
};
ImGui::BeginChild("##songs_player_mp3", ImVec2(0, -25));
if (PlaylistID == -1) {
	ImGui::EndChild();
	return;
}
auto& songs = Playlists.at(PlaylistID).Songs;
auto& currentSong = Playlists.at(PlaylistID).curSongID;
auto& style = ImGui::GetStyle();
if (ImGui::BeginTable("##songs_table", 3)) {
	ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthFixed, 30);
	ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthFixed, 275);
	ImGui::TableSetupColumn("", ImGuiTableColumnFlags_WidthFixed, 70);
	clipperPlaylist.Begin(songs.size());
	while (clipperPlaylist.Step()) {
	for (int id = clipperPlaylist.DisplayStart; id < clipperPlaylist.DisplayEnd; id++) {
			auto& song = songs.at(id);
			ImGui::TableNextRow();
			ImGui::TableNextColumn();
			const ImVec2 size = ImVec2(ImGui::GetWindowWidth(), ImGui::GetFrameHeight() * 2 - style.ItemSpacing.y);
			auto winPos = ImGui::GetWindowPos();
			auto pos = ImGui::GetCursorPos();
			ImGui::Dummy(size);
			drawBox(pos + winPos + ImVec2(0, -2), size, ImGui::ColorConvertFloat4ToU32(style.Colors[ImGuiCol_HeaderHovered]));
			ImGui::SetCursorPos(pos);
			ImGui::Text("%d", id + 1);
			ImGui::TableNextColumn();
			ImGui::Text(song.Name.data());
			ImGui::Text(song.Artist.data());
			ImGui::TableNextColumn();
			ImGui::Text(song.DurationText.data());
		}
	}
	ImGui::EndTable();
}
ImGui::EndChild();
```

**Comment by ocornut** [comment]
Hello,

> After adding it noticed that the Dummy changes size.

`Dummy()` submit an item and items are vertically separated by `style.ItemSpacing.y` during layout.
You may alter the spacing with e.g. `ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));`

> Question: I'm trying to make a selection of the entire row and I have it in two lines. I tried using Imgui::Selectable, but I ran into a problem that only one line is allocated.

I think you can use `Selectable()`. Since later you said you have calculated the size yourself, you can pass that size to `Selectable()`.

The canonical way to use Selectable in this context is generally:

```cpp
ImGuiSelectableFlags flags = ImGuiSelectableFlags_SpanAllColumns | ImGuiSelectableFlags_AllowItemOverlap;
ImGui::Selectable("###identifier", is_selected, flags, size);
```

**Comment by ocornut** [comment]
Closing as answered.
