### ISSUE TITLE
how to correctly get unicode char from InputTextMultiline text?

### ISSUE THREAD

**Issue by baofengyujue** [ocornut/imgui#6077]
![Recording 2023-01-14 at 10 18 34](https://user-images.githubusercontent.com/19611447/212447632-412ce468-63a6-48ed-a1fe-4f0a040822a8.gif)
currently i'm having issue getting the right char to my variable after i entered a chinese character
here's the code part:
![a](https://user-images.githubusercontent.com/19611447/212447740-5e231e2f-dbcf-447e-a7ce-a25c1a05f373.png)

entered "你" but get "浣?"
![image](https://user-images.githubusercontent.com/19611447/212448802-8d454d00-f328-4878-a1c5-d067ef1d51ca.png)
not only displayed wrong in console, also wrong with my "text_before" varaible, so i cannot deal with them correctly.

a complete example code would be great😀

**Comment by baofengyujue** [comment]
after i studied the FONTS.md docs and other imgui docs, didn't find a simple answer

**Comment by heroboy** [comment]
I think this is Chinese. And I don't see any issue in your gif.

**Comment by baofengyujue** [comment]
@heroboy get "浣?" but i entered "你"
![image](https://user-images.githubusercontent.com/19611447/212448548-9bf1fbb4-0475-443b-874a-46fea5f3126c.png)

**Comment by baofengyujue** [comment]
not only displayed wrong in console, also wrong with my "text_before" varaible, so i cannot deal with them correctly.

**Comment by heroboy** [comment]
You actually entered "你"。But it is encoded in utf8, so it can be correctly shown in imgui. Console encoding is not utf8.

**Comment by baofengyujue** [comment]
> You actually entered "你"。But it is encoded in utf8, so it can be correctly shown in imgui. Console encoding is not utf8.

you are right, after i use `SetConsoleOutputCP(65001);`, the cosole print "ab你" correctly

but, when i dealing with the `text_before` variable, i'm having trouble

here's the code:
![2023-01-14_120222 - Copy](https://user-images.githubusercontent.com/19611447/212450160-9767f70e-19e0-4114-a20e-a660d6077723.png)

i cannot extract `text_before` char correctly

result:
![image](https://user-images.githubusercontent.com/19611447/212450261-cebe35e3-0bc0-45c8-9a54-b5a8b2c9c5d9.png)
the `content` is empty

but after i manually preassigned `text_before` to "ab你" `content` prints correctly
