### ISSUE TITLE
bug: UB: TextColoredV can use fmt nullptr value

### ISSUE THREAD

**Issue by dalerank** [ocornut/imgui#6082]
**Version/Branch of Dear ImGui:** : Any
**Back-end/Renderer/Compiler/OS**: Any
Operating System: Any

**My Issue/Question:**
```
void ImGui::TextColoredV(const ImVec4& col, const char* fmt, va_list args)
{
    PushStyleColor(ImGuiCol_Text, col);
    if (fmt[0] == '%' && fmt[1] == 's' && fmt[2] == 0)
        TextEx(va_arg(args, const char*), NULL, ImGuiTextFlags_NoWidthForLargeClippedText); // Skip formatting
    else
        TextV(fmt, args);
    PopStyleColor();
}
```

Bug:
If the fmt variable passed to the function is a null pointer, the behavior of the program is undefined. The program will likely crash when the function attempts to access the memory location pointed to by the null pointer.

Possible solution:
```
 if (fmt && fmt[0] == '%' && fmt[1] == 's' && fmt[2] == 0)
 ```

**Comment by ocornut** [comment]
The majority if not all functions taking a fmt argument will similarly crash if that argument is null. It’s a user error and we’d rather crash or assert as soon as we can. There’s however no value adding asserts when there is a guaranteed crash, so we don’t spam the code with asserts in that situation.

This is by specs and which would be a net negative to silently allow a null pointer here.
