### ISSUE TITLE
ImGui window (docking branch) flickers when trying to dock to the left or right

### ISSUE THREAD

**Issue by Anuhas-Jayawardana2008** [ocornut/imgui#6083]
I recently integrated imgui docking branch with GLFW and in my `void CreateDockspace()` I pasted in the exact code from the example dockspace app from the imgui demo. It works fine when docking fullscreen or top and bottom. (sometimes docking to the bottom also breaks the window) But docking the second time or docking to left or right just makes the imgui window flicker and not make it able to be draggable anymore
contact me at brownies#9148 if needed..

edit : I've noticed that this behavior is caused mainly when the modal window is slightly dragged out of the parent window. how can I make the modal window not floatable?

**Comment by ocornut** [comment]
This is not an acceptable issue.
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
- Add precise repro, details, videos etc.

Closing.
