### ISSUE TITLE
How to pass through mouse drag to parent window?

### ISSUE THREAD

**Issue by Yamahari** [ocornut/imgui#6084]
Version: 1.89.2
Branch: docking

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: GCC 12.1.0 (MinGW)
Operating System: Windows 10

I am tinkering with implementing an UI designer using imgui. I was hoping I could use the existing docking functionality to create new window instances that are filled out completely by whatever widget you decided to add. You could then use the docking functionality to sort of arrange your UI elements in a way that suits you best. But I am stuck on the following.  The newly created window has no title bar  (because that would obviously kill the illusion of having movable widgets) and is for example filled out completely by a button.

```c++
ImGui::Begin("SomeUniqueId", nullptr, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoNav);

if (ImGui::Button("TestButton", ImGui::GetContentRegionAvail()))
{
    // do stuff
}

ImGui::End();
```

The issue now is, that I can no longer drag the window around because the button captures all the input into the window (at least that's my understanding of what's happening).
So how do I pass through the mouse to the window, if the mouse is being dragged?

```c++
ImGui::Begin("SomeUniqueId", nullptr, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoNav);
        

if(ImGui::IsMouseDragging(ImGuiMouseButton_Left)) 
{
    // how to tell window to move?
}

if (ImGui::Button("TestButton", ImGui::GetContentRegionAvail()))
{
    // do stuff
}

ImGui::End();
```

https://user-images.githubusercontent.com/40495288/212538335-f661e79c-1475-4e5a-96ce-d95ef1ca1e52.mp4

I tried searching for keywords like passthrough, window and dragging, but I couldn't find any related issue nor did I find something related in the demo, but maybe I am just blind . x)

**Comment by PathogenDavid** [comment]
You can get the behavior you want using a dummy child window with input disabled:

```cpp
ImGui::Begin("Outer window");
ImGui::BeginChild("Child", { 100, 100 }, false, ImGuiWindowFlags_NoInputs);
ImGui::Button("Button", { 100, 100 });
ImGui::EndChild();
ImGui::End();
```

Your approach is interesting, but this feels like a somewhat odd and hacky way to make a UI editor. Not sure if this will generalize well to all widgets or provide a good UX overall.

I'd be more inclined to handle all the dragging logic yourself and have the dummy UI widgets live in a separate Dear ImGui context with a custom platform backend that doesn't receive any input.

**Comment by Yamahari** [comment]
Hi, thanks for your asnwer. Unfortunately this approach doesn't seem to work for 2 reasons:
1) You can no longer dock the window when dragging the dummy child window around
2) You can no longer press the button  if your mouse is not dragging

**Comment by PathogenDavid** [comment]
> 1. You can no longer dock the window when dragging the dummy child window around

Windows can only be docked with the mouse by dragging them from the title bar. I don't think this can be configured.

> 2. You can no longer press the button if your mouse is not dragging

Correct. I took your "UI designer" description at face value and missed the motivation bit.

I don't think you're getting a fully drag-able UI that you can still interact with without significant effort on your part.

I'd probably lean towards having a checkbox somewhere to allow the user to toggle between edit and interact mode.
