### ISSUE TITLE
How do I create a right click context menu that is triggered only on an ImGui::Selectable?

### ISSUE THREAD

**Issue by Anuhas-Jayawardana2008** [ocornut/imgui#6088]
I've been making a game engine for the past week and I implemented a hierarchy panel and made it possible to right click to get a context menu and add new entities/game objects. But, I'm wondering how I can make it so I can right click on a certain entity (I'm using ImGui::Selectables btw) and get a new ImGui::OpenPopupContextWindow() that is only triggered when clicking on the selectables but not on the empty spaces...

**Comment by GamingMinds-DanielC** [comment]
Take a look at `BeginPopupContextItem()`, it operates on the last item submitted to ImGui.

**Comment by ocornut** [comment]
There's no `OpenPopupContextWindow()` function in the API so I'm not sure if you are referring to third-party helper code.
But yes basically you can use `BeginPopupContextItem()`, which is more or less a shortcut for:

```cpp
    if (IsMouseReleased(...) && IsItemHovered(...))
        OpenPopup(...);
    return BeginPopup(...);
```

See BeginPopupContextItem() for exact details, and `Demo->Popups & Modal Windows->Context Menu` for a demo of using this on selectables.
