### ISSUE TITLE
refactor: use inline template variadic instead unparametrized function call

### ISSUE THREAD

**Issue by dalerank** [ocornut/imgui#6091]
Version: Last
Branch: Last

Compiler: ANY
Operating System: ANY

```
void ImGui::TextDisabled(const char* fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    TextDisabledV(fmt, args);
    va_end(args);
}
```

Why:
variadic templates in C++ provide a more type-safe, efficient, and readable way of handling variable numbers of arguments than va_list. However, variadic templates have a steeper learning curve compared to va_list and in some cases, it could be more complex to use them.

Solution:
```
template<typename ... Args>
inline void ImGui::TextDisabled(const char* fmt, const Args &... args) {
    TextDisabledV(fmt, args...);
}
```

**Comment by PathogenDavid** [comment]
This feels like a dogmatic suggestion without understanding the complexities involved. Your "solution" is woefully under-simplified from what would actually be required to make this work.

It could be somewhat interesting to use vardic templates to provider proper unformatted vs formatted functionality as overloads, but this betrays expectations and would be a breaking change.

Unless I'm missing something else, any efficiency gain is going to be microscopic ABI differences that would be dwarfed by the cost of doing string formatting.

Either way, Dear ImGui has always presented a C-like API with little-to-no template usage. For many people this is an important feature.

**Comment by ocornut** [comment]
What David says. We don’t rely on modern C++ features nor headers for variety of reasons. In this case it wouldn’t be a good tradeoff.

**Comment by dalerank** [comment]
Fully agree with you, but 
1. If I understood imgui c++ project 
2. Unparametrized functions can be  wrapped inside c-wparrer
3. More clean code in header
