### ISSUE TITLE
Flickering when using multiple panels

### ISSUE THREAD

**Issue by Linuxuser1234** [ocornut/imgui#6092]
`
	while (!glfwWindowShouldClose(window))
	{
		glClearColor(0.00f, 0.00f, 0.00f, 0.0f);
		glClear(GL_COLOR_BUFFER_BIT);
		ImGui_ImplOpenGL3_NewFrame();
		ImGui_ImplGlfw_NewFrame();
		ImGui::NewFrame();
		glDrawArrays(GL_TRIANGLES, 0, 3);
		//Panel1
		ImGui::Begin("Panel1");
		ImGui::Text("Test" );
		ImGui::End();
		ImGui::Render();
		ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
		glfwSwapBuffers(window);
		glfwPollEvents();
		//Panel2
		
		/*ImGui_ImplOpenGL3_NewFrame();
		ImGui_ImplGlfw_NewFrame();
		ImGui::NewFrame();
		ImGui::Begin("Panel2");
		ImGui::Text("00/00/0000");
		ImGui::End();
		ImGui::Render();
		ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
		glfwSwapBuffers(window);*/
	}`

**Comment by GamingMinds-DanielC** [comment]
You are not drawing two panels in a frame, but two frames per update loop with alternating panels. That pretty much guarantees flickering. Try separating your UI logic from your frame handling for better clarity. There should be absolutely no frame handling interleaved with UI logic. The sources in the example directory are a good reference for basic update loops.
