### ISSUE TITLE
Render external Win32 window in ImGui window

### ISSUE THREAD

**Issue by pavledev** [ocornut/imgui#6099]
Version/Branch of Dear ImGui:

Version: 1.89.2
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx12.cpp
Compiler: VS2022
Operating System: Windows 10

My Issue/Question:

Is it possible to render Win32 window in ImGui window?

**Comment by ocornut** [comment]
Everything is possible on a computer but this looks like outside the boundaries/scopes of what Dear ImGui would be responsible for, and it doesn't sound easy, and it sounds potentially like a [XY Problem](https://xyproblem.info). It would be better if you gave more context about what you are trying to achieve and why.

**Comment by GamingMinds-DanielC** [comment]
> I want to render window of game in editor that I am creating for it so that I could display and modify properties of entity selected in game using mouse

Assuming you have control over the game engine and it's not a 3rd party game you want to make an editor for...
You don't need to integrate another OS window. Not only is it not feasible, it would create a lot of problems as well, f.e. if you want to move a tool window within the editor in front of the game/engine view. That wouldn't work without properly integrating the engine view into your editor. You most likely need to have it running in the same process anyway for communication (selection, parameter changes, ...).

The usual approach is this:
* Put your engine into a library project that you can link to other projects.
* Put window creation, device initialization and so on into a "game" project and link the engine library, supply the device to the engine instance.
* Make the engine capable of rendering into a supplied render target (can be back buffer or texture) and view port (if you are rendering to the back buffer directly).
* Put the editor into another project and link the engine library as well. Here you should have full control over the engine instance as well and can render it into a texture that you can then display where you want it in your UI.

**Comment by pavledev** [comment]
> > I want to render window of game in editor that I am creating for it so that I could display and modify properties of entity selected in game using mouse
> 
> Assuming you have control over the game engine and it's not a 3rd party game you want to make an editor for... You don't need to integrate another OS window. Not only is it not feasible, it would create a lot of problems as well, f.e. if you want to move a tool window within the editor in front of the game/engine view. That wouldn't work without properly integrating the engine view into your editor. You most likely need to have it running in the same process anyway for communication (selection, parameter changes, ...).
> 
> The usual approach is this:
> 
> * Put your engine into a library project that you can link to other projects.
> * Put window creation, device initialization and so on into a "game" project and link the engine library, supply the device to the engine instance.
> * Make the engine capable of rendering into a supplied render target (can be back buffer or texture) and view port (if you are rendering to the back buffer directly).
> * Put the editor into another project and link the engine library as well. Here you should have full control over the engine instance as well and can render it into a texture that you can then display where you want it in your UI.

How I can play game from editor if I render it into the texture?

**Comment by GamingMinds-DanielC** [comment]
> How I can play game from editor if I render it into the texture?

The same way you would play it if you rendered into the back buffer: by forwarding the relevant inputs to your engine instance. But those topics are basic engine design, not ImGui specific.

**Comment by ocornut** [comment]
I'll close this as not particularly Dear ImGui related.
@pavledev it would be best you ask this question on a more general game/graphics/tech programming forum, especially now that you have more pointers. It's a rather open-ended question.
