### ISSUE TITLE
Demo: custom rendering example resize problem

### ISSUE THREAD

**Issue by erson** [ocornut/imgui#610]
i was playing with the demo.i realised that if i resize canvas it is not hiding all drawing area.

![1](https://cloud.githubusercontent.com/assets/1500710/14777615/e4e5f274-0ad6-11e6-8377-c6c82380b892.png)
![2](https://cloud.githubusercontent.com/assets/1500710/14777616/e4e72022-0ad6-11e6-8574-f95034133c98.png)

there seems to be rendering bug with drawing canvas.i didnt dig in to it.it could be happening just on demo implementation.

**Comment by ocornut** [comment]
Yes it is a bug in the demo code, I have noted it in imgui.cpp as:
`!- demo: custom render demo pushes a clipping rectangle past parent window bounds. expose ImGui::PushClipRect() from imgui_internal.h?`

The code is doing a `draw_list->PushClipRect()` regardless of the old parent clipping rectangle (which is useful in many cases). I need to expose additional parameter to PushClipRect() to allow doing the union with the parent clipping rectangle and have the demo use that.

**Comment by ocornut** [comment]
Fixed and exposed high-level ImGui::PushClipRect() that I've been wanting to expose for a while.
