### ISSUE TITLE
Library dont work on real android devices with SDL2 + GLES 3

### ISSUE THREAD

**Issue by vovan4ik123** [ocornut/imgui#6105]
Version 1.89.2 tested on real android devices (Samsung and Xiaomi) with SDL2 + OpenGL ES 3
All GUI elements dont react to any screen touch. The are only drawing.

ImGUI 1.83 works good. React to screen touches on android real devices with SDL2 + OpenGL ES 3

**Comment by okvik** [comment]
I'm building an application which uses version 1.89.2 ImGui and SDL2 + OpenGL ES3 backends. It builds and works fine on Android.

However, I have a very similar problem with the same application when built for PC (Linux). Sometimes:
* when the application is running fullscreen,
* on some of the monitors (for example on my big screen but not on a laptop screen),

I observe a similar issue where widgets aren't reacting to inputs, or are only intermittently reacting to input. When, for example, I manage to grab a window i can drag it around just fine, but afterwards it's hard / impossible to do it again. Same for clicking on buttons, menus, etc. 1/20 times it works.

I'm using the input event processing exactly as in the example backend for this combo and aren't doing anything else with inputs.

**Comment by vovan4ik123** [comment]
I found that i have assert:  IM_ASSERT(sz_io == sizeof(ImGuiIO) && "Mismatched struct layout!");
In method bool ImGui::DebugCheckVersionAndDataLayout(...........

**Comment by PathogenDavid** [comment]
> I found that i have assert: IM_ASSERT(sz_io == sizeof(ImGuiIO) && "Mismatched struct layout!");

That assert usually indicates that you have multiple conflicting versions of Dear ImGui in your build environment. (IE: You're including `imgui.h` from one version and linking to a different version.)

Double check your build setup.

**Comment by vovan4ik123** [comment]
@PathogenDavid I found that reason of assert inside IMGUI_CHECKVERSION();
was 2 lines in CmakeLists.txt file:
add_definitions(-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS)
add_definitions(-DIMGUI_DISABLE_OBSOLETE_KEYIO)

I removed them and now no asserts. But Library still dont react to any screen touch on android devices.

**Comment by vovan4ik123** [comment]
Ok. Problem solved.
My code miss call - ImGui_ImplSDL2_ProcessEvent(&event);
inside while(SDL_PollEvent(&event)) {}

Also please check why IMGUI_CHECKVERSION(); throws assert when CmakeLists.txt has
add_definitions(-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS)
add_definitions(-DIMGUI_DISABLE_OBSOLETE_KEYIO)

**Comment by PathogenDavid** [comment]
> My code miss call - ImGui_ImplSDL2_ProcessEvent(&event);

That'd definitely do it! Glad you were able to figure it out.

> Also please check why IMGUI_CHECKVERSION(); throws assert when CmakeLists.txt has

It sounds like you're building your app and Dear ImGui separately, and you're only specifying `IMGUI_DISABLE_OBSOLETE_KEYIO` for one of them.

They need to match, otherwise the `ImGuiIO` struct will differ between the two.

**Comment by ocornut** [comment]
Usually people would either modify imconfig.h with all configuration defines in therr, or define IMGUI_USER_CONFIG to the path of your own configuration file. But all compilation units that are using imgui.h should be built with the same configuration settings. That assert is here to detect the mistake.

closing as answered. Thank you David for the help!
