### ISSUE TITLE
Is there a flag to make the resize grip always on top?

### ISSUE THREAD

**Issue by billgan1024** [ocornut/imgui#6106]
**My Issue/Question:**
Is there a flag to make the resize grip always on top of the child content? Currently, when I am drawing images that completely cover a window using
`ImGui::Image(reinterpret_cast<void *>(textureID), ImGui::GetContentRegionAvail(), ImVec2(0, 1), ImVec2(1, 0));`
I noticed that the triangle in the bottom-right corner was covered by the image even though I could resize, and I would like the triangle to be visible.

**Comment by PathogenDavid** [comment]
The resize grips are [rendered by `ImGui::RenderWindowDecorations`](https://github.com/ocornut/imgui/blob/91667430a88f88187c56ea8debb9a5f5f30435d4/imgui.cpp#L5813-L5818) which is [called during `ImGui::Begin`](https://github.com/ocornut/imgui/blob/91667430a88f88187c56ea8debb9a5f5f30435d4/imgui.cpp#L6484).

As such they will always be rendered before your window's contents. This is not configurable.

-----------

If you think it's worth the effort, your best bet would be to render your own resize grip using the same logic as `ImGui::RenderWindowDecorations`.

The tricky part would be to determine the appropriate color to use (IE: Whether to use `ImGuiCol_ResizeGrip`, `ImGuiCol_ResizeGripActive`, or `ImGuiCol_ResizeGripHovered`.)

I think you should be able to do so by querying `ImGui::GetHoveredID` and `ImGui::IsMouseDown(ImGuiMouseButton, ImGuiID)` with the resize grip's ID, which you can get from `ImGui::GetWindowResizeCornerID`.

These are all internal functions defined in `imgui_internal.h`, so be aware these APIs could change without notice. (In particular, the `ImGuiID` variant of `ImGui::IsMouseDown` is *very* new and experimental.)

**Comment by ocornut** [comment]
Closing as answered. Let us know if you make progress on this or have additional questions!
