### ISSUE TITLE
Popupmodals don't show when using MSVC's optimization feature (\O1,\O2,\Ox)

### ISSUE THREAD

**Issue by Stehsaer** [ocornut/imgui#6107]
**Version/Branch of Dear ImGui:**

```
Dear ImGui 1.89.1 WIP (18910)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1933
define: _MSVC_LANG=201703
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000001, TexSize: 1024,968
io.DisplaySize: 1280.00,768.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,4.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 4.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MSVC (Microsoft Visual Studio 2022 Community Version built-in)
Operating System: Windows 11 Home Edition

**My Issue/Question:**

I'm current writing a class to show popup modals in imgui.
Everything worked fine in **debug mode**, but when I switch to **release mode**, popup modals can't show up.
After turning off **optimizations** (\O1,\O2,\Ox) and use \Od, issue's gone. Tweaking other options of optimizations doesn't affect the issue.
Since it **works fine in debug mode**, I'm convinced that there's no mistake in my code.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```C++
enum dialog_state_enum
{
    closed=0,
    open_requested=1,
    opened=2,
    close_requested=3
};

//in a function that is called every frame:
if(dialog_state==open_requested)
{
    // codes inside this bracket can be executed
    ImGui::OpenPopup(dialog_name);
    dialog_state=opened;
}
if(dialog_state==opened)
{
    bool open;
    bool* openptr = (bool*)0;
    if (has_close_button) openptr = &open; // add close button to the popup modal window

    // codes above can be executed too

    if (ImGui::BeginPopupModal(dialogName, openptr, dialog_flag))
    {
        // codes within this bracket can't execute, WHYYY?
        std::cout<<"the code inside this bracket should be executed"<<std::endl;
        dialog_result result=callback();
        ...
    }
}
```
after setting dialog_state to open_requested, ImGui::BeginPopupModal(dialogName.c_str(), openptr, dialogFlag) should be true

**Comment by emoon** [comment]
Your `bool open;` is uninitialized

**Comment by Stehsaer** [comment]
> Your `bool open;` is uninitialized

Thank you so much for help! Issue solved!
By the way, why does an uninitialized bool only affect optimization but not debug? it's kinda weird that the uninitialized bool is assumed true in debug mode but with optimization it's assumed false

**Comment by emoon** [comment]
It's really undefined what the variable will be regardless of debug or release mode. You just happened to be "luck" in one case. An uninitialized value can end up being anything, it all depends on how the stack frame looks at that point.

**Comment by ocornut** [comment]
Thank you Daniel for your answer!
With default “Debug” settings Visual Studio compiler will generally clear local variables with a 0xCC pattern (or another one I forgot exactly which) which in turn will makes your bool true. But that’s absolutely compiler and settings defined.
