### ISSUE TITLE
DockSpace OpenGL performance

### ISSUE THREAD

**Issue by Grieverheart** [ocornut/imgui#6113]
**Version/Branch of Dear ImGui:**

Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_opengl3.cpp
Compiler: Apple clang version 11.0.3 (clang-1103.0.32.62)
Operating System: MacOS 12.6.2

**My Issue/Question:**

Running the DockSpace example, `example_sdl_opengl3`, I noticed that quite a bit of time was being spent in rendering the UI when using high dpi mode on a 2019 16-inch macbook pro with an AMD Radeon Pro 5500M 4 GB.

To profile, I used glGenQueries/glBeginQuery functions and surrounded the rendering function, `ImGui_ImplOpenGL3_RenderDrawData`. What I found was that running the example and docking both windows took 4.5ms to render when maximized (resolution of 3584x2134). If `PassthruCentralNode` is set, it drops to 2.5ms per frame.

Now, I'm trying to understand if, first of all, these numbers are normal, given the high rendering resolution, and what exactly causes the performance to be nearly doubled when setting `PassthruCentralNode`. On the latter, my understanding is that dear imgui is rendering a big rectangle, but would that have such a big impact on performance? Does blending have something to do with it perhaps?

**Comment by Grieverheart** [comment]
So, indeed, I found out that if I change the WindowBg alpha to 255, performance increases again, so at least that can be explained by the rendering of the dock space background.

**Comment by ocornut** [comment]
Those numbers seems quite high... but I've noticed a tendency of laptop manufacturers to ship 4K screens with GPU that are sometimes unable to support decent workload at that resolutions.

It'd be interesting to see if on the same HW you get different performances with Metal and Vulkan backends. It could be that better supported drivers may have better optimizations that OpenGL ones.

It's also interesting that this confirms that there's still some value that I minimize overdraw. We have some code in here intently performing unusual/tricky maneuvers to reduce overdraw, initiated by the fact that we want correct/consistent blending, but effectively also generally reducing GPU use.

**Comment by Grieverheart** [comment]
Unfortunately, I have no experience with ObjC and Metal, so please correct me if what I did was wrong. I basically put changed the backend code to include the following `printf`:
```ObjectiveC
    [commandBuffer addCompletedHandler:^(id<MTLCommandBuffer> cmd)
    {
        dispatch_async(dispatch_get_main_queue(), ^{
            ImGui_ImplMetal_Data* bd = ImGui_ImplMetal_GetBackendData();
            printf("%f\n", ([cmd GPUEndTime] - [cmd GPUStartTime]) * 1000.0);
            if (bd != nullptr)
            {
                @synchronized(bd->SharedMetalContext.bufferCache)
                {
                    [bd->SharedMetalContext.bufferCache addObject:vertexBuffer];
                    [bd->SharedMetalContext.bufferCache addObject:indexBuffer];
                }
            }
        });
    }];
```
Now the weird thing is that at first I get about 3.5ms with default window size and dockspace. Then, when I double click the window to maximize, it drops to 1.5ms? Then if I double click again it drops to about 0.8ms! The other weird thing is that the time also drops to 0.8ms without maximizing->un-maximizing, but if I instead start the MacOS snapshot tool.

This weirdness, makes me think I might not be measuring properly.

**Comment by ocornut** [comment]
I believe it may be simpler to disable vsync in order to run the application unthrottled (maximum possible framerate) and then compare the time costs.

**Comment by Grieverheart** [comment]
Ok, after further investigation, it appears the issue might be due to SDL. In the GLFW backend, I get lower numbers. In SDL the times are printed to the console in bursts, while in GLFW it's smooth.

I disabled VSYNC in both, and the GLFW backend with dockspace reports 0.5-1.5ms for the command buffer to complete, while frame rates are 150-180fps. 

For SDL2, the numbers are as reported. When fullscreen the time reported is also 0.5-1.5ms, but many more times are 1.5ms, and there are stutters every now and then, although the reported timings stay the same, so the stutters must be coming from somewhere else. The fps is pretty much capped at 120 (note that the display refresh rate on this model is up to 60Hz).

Not sure how to proceed investigating if this is truly an SDL bug, or a backend bug.

**Comment by ocornut** [comment]
It's probably not "a bug in SDL" but a subtlety in configuring the OpenGL context and how drivers reacts to it. May be worth chasing.

> EDIT: Another weird behavior: GLFW fps can for unknown reasons, after having the window open for some time (turbo boost or something?), go up to 700fps.

Drivers are complicated, laptops even more so as they have varying logic kicking in to reduce power consumption. 700 fps means 1.42 ms for the entire-frame which I would intuitively guess would be a more reasonable time on a 4K laptop, more so than your 150-180 FPS (5.55 ms to 6.66 ms per frame). 

For reference, on my desktop PC, with NVIDIA RTX 2080 Ti, running example app 4K fullscreen-ish, enabling docking demo:

- win32+dx11: main loop takes ~0.250 ms with bg filling all screen, ~0.160 ms with passthru flag.
- glfw+opengl3: ~0.350 ms with bg fill, ~0.280 ms with passthru flag.
- sdl+opengl3: ~0.350 ms with bg fill, ~0.280 ms with passthru flag.
- glfw+vulkan: ~0.380 ms with bg fill, ~0280 ms with passthru flag.

There are probably ways to squeeze time on some backends/setups, but generally that amount of care is rare and left to custom-backend users.

**Comment by ocornut** [comment]
Also note that if you have a fullscreen dockspace you may as well skip on clearing your framebuffer and save bandwidth there.

**Comment by Grieverheart** [comment]
Thanks, I think I'll have to ask further at SDL, because there is definitely more weirdness. For example, the SDL_PollEvent loop can sometimes take 4-5ms with no input events, although usually it sits at 0.7ms, which is still high compared to GLFW's <0.1ms.

**Comment by ocornut** [comment]
I'll close this as it is likely unrelated to dear imgui, but if you find anything don't hesitate to post details!

**Comment by Grieverheart** [comment]
To whomever might be interested in this, I have created an issue on SDL [here](https://github.com/libsdl-org/SDL/issues/7151).

**Comment by Grieverheart** [comment]
@ocornut After some back and forth in the linked SDL issue, it was found that the culprit is `SDL_SetCursor`, which calls `invalidateCursorRectsForView`. In the SDL backend, `SDL_SetCursor` is called every time `NewFrame` is called, which leads to slow down. I think either you wait for a fix, which might take some time, or alternatively, cache the cursor and only call `SDL_SetCursor` whenever there is a change.

Note that e.g. GLFW calls `[mouseCursor set]` which causes the mouse cursor to not change back to normal when it leaves the window. It does change back when the application exits, though.
