### ISSUE TITLE
My shader program seems to conflict with imGUI

### ISSUE THREAD

**Issue by PatronBernard** [ocornut/imgui#612]
I am using these [fragment](https://github.com/PatronBernard/RTDH/blob/master/RTDH/fragment_src.glsl) and [vertex](https://github.com/PatronBernard/RTDH/blob/master/RTDH/vertex_src.glsl) shaders. 

As soon as I load these (see pseudocode below, entire project can be found [here](https://github.com/PatronBernard/RTDH/tree/master/RTDH) ), I cannot draw any imGUI windows anymore. Does anyone have an elementary example that e.g. draws a triangle with some shader and also displays an imGUI window? Or if you see a mistake, I'd be glad to hear about it!

Thank you in advance.

`int main(){
	//The usual stuff that is not relevant
	initializeGLFW( bla bla);
	initialize imGUIGlfwBinding();

	/* Open gl vertex array and vertex buffer stuff */
	
	
	/* As soon as I call this part (normally embedded in a function, 
	I cannot draw any imGUI windows anymore, just the backgroud color remains */
	
	GLuint shaderprogram;
	char* vertex_src = read_txt("vertex_src.glsl");
	char* fragment_src = read_txt("fragment_src.glsl");
	GLint shader_ok;
	int buffersize = 1024;
	char* logbuffer = (char*)malloc(sizeof(char)*buffersize);

	GLuint vertex_shader = glCreateShader(GL_VERTEX_SHADER);
	glShaderSource(vertex_shader, 1, (const GLchar**)&vertex_src, 0);
	glCompileShader(vertex_shader);

	glGetShaderiv(vertex_shader, GL_COMPILE_STATUS, &shader_ok);
	if (!shader_ok) {
		fprintf(stderr, "Failed to compile %s:\n", "vertex_src.glsl");
		glGetShaderInfoLog(vertex_shader, buffersize, NULL, logbuffer);
		fprintf(stderr, "%s \n", logbuffer);
		glDeleteShader(vertex_shader);
		exit(EXIT_FAILURE);
	}

	GLuint fragment_shader = glCreateShader(GL_FRAGMENT_SHADER);
	glShaderSource(fragment_shader, 1, (const GLchar**)&fragment_src, 0);
	glCompileShader(fragment_shader);

	glGetShaderiv(fragment_shader, GL_COMPILE_STATUS, &shader_ok);
	if (!shader_ok) {
		fprintf(stderr, "Failed to compile %s:\n", "fragment_src.glsl");
		glGetShaderInfoLog(fragment_shader, buffersize, NULL, logbuffer);
		fprintf(stderr, "%s \n", logbuffer);
		glDeleteShader(fragment_shader);
		exit(EXIT_FAILURE);
	}

	GLuint shaderprogram = glCreateProgram();

	glAttachShader(shaderprogram, vertex_shader);
	glAttachShader(shaderprogram, fragment_shader);

	glBindAttribLocation(shaderprogram, 0, "in_Position");
	glBindAttribLocation(shaderprogram, 1, "in_Magnitude");

	glLinkProgram(shaderprogram);
	glUseProgram(shaderprogram);
	
	while(!glfwWindowShouldClose(window)){		
		glfwPollEvents();
		ImGui_ImplGlfw_NewFrame();

		// 1. Show a simple window
		// Tip: if we don't call ImGui::Begin()/ImGui::End() the widgets appears in a window automatically called "Debug"
		{
			static float f = 0.0f;
			ImGui::Text("Hello, world!");
			ImGui::SliderFloat("float", &f, 0.0f, 1.0f);
			ImGui::ColorEdit3("clear color", (float*)&clear_color);
			if (ImGui::Button("Test Window")) show_test_window ^= 1;
			if (ImGui::Button("Another Window")) show_another_window ^= 1;
			ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
		}

		// Rendering
		int display_w, display_h;
		glfwGetFramebufferSize(window, &display_w, &display_h);
		glViewport(0, 0, display_w, display_h);
		glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
		glClear(GL_COLOR_BUFFER_BIT);
		ImGui::Render();
		glfwSwapBuffers(window);
	}
	
	/*Usual cleanup stuff */
	
}`

**Comment by ocornut** [comment]
call glUseProgram(0) before ImGui::Render()

https://github.com/ocornut/imgui/blob/master/examples/opengl_example/imgui_impl_glfw.cpp
```
// If your context is GL3/GL3 then prefer using the code in opengl3_example.
// You *might* use this code with a GL3/GL4 context but make sure you disable the programmable pipeline by calling "glUseProgram(0)" before ImGui::Render().
// We cannot do that from GL2 code because the function doesn't exist. 
```

**Comment by PatronBernard** [comment]
Thank you so much for the quick response. This issue can be closed because it's in the FAQ if I'm not mistaken.
