### ISSUE TITLE
example_sdl_sdlrenderer is not showing widgets correctly in m1

### ISSUE THREAD

**Issue by handrake0724** [ocornut/imgui#6121]
**Version/Branch of Dear ImGui:**

Version: 1.89.3
Branch: master/docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_sdlrenderer.cpp 
Compiler: Apple clang version 14.0.0
Operating System: macOS ventura 13.0.1

**My Issue/Question:**

when example_sdl_sdlrenderer is compiled and run, the widgets are gone and just window which contains the widgets.
Also, it seems like mouse coordinates are not correct such that the mouse clicking is not working right on the window but away from the window.

I have tested example_sdl_opengl2 and example_sdl_metal and they show correct behavior.

**Screenshots/Video**

<img width="1280" alt="Screenshot 2023-01-28 at 2 45 15 PM" src="https://user-images.githubusercontent.com/18005991/215248539-8161f201-b93a-4999-8110-03798499cbae.png">

**Comment by ocornut** [comment]
Hello,
I have added ` SDL_RenderSetScale()` in 5a3f82e2f4f30e529f765d38aaa76866653b245a to make this consistent across examples for now. Fuller hi-dpi support on Mac in the examples app will be address separately but this fixes this issue.
