### ISSUE TITLE
Set flags for ImageButton?

### ISSUE THREAD

**Issue by indjev99** [ocornut/imgui#6126]
I've been using `ButtonEx` to set additional flags. In particular, I was setting `ImGuiButtonFlags_AllowItemOverlap`, because my buttons represent cards that may be partially on top of each other (and I want presses to count for the top most card). However, as I was now switching to `ImageButton`, I found that `ImageButtonEx` has no such field. Is there a workaround?

Note: I am pretty sure I know how to mod the library to have this, but I'd rather not.

**Comment by ocornut** [comment]
Hello,
I agree this is missing.
For now most of those flags are in internal so I've added the additional parameter to `ImageButtonEx()` but not the outer public-layer yet. Pushed change in d719776

Thank you!
