### ISSUE TITLE
The use of the Cyrillic alphabet?

### ISSUE THREAD

**Issue by Qazwar** [ocornut/imgui#613]
Hello! Sorry for my bad english (using Google Translate)
Faced with the problem of the Cyrillic output.

![irpxgie](https://cloud.githubusercontent.com/assets/18671550/14826914/cfe865c4-0c01-11e6-9e1c-b2fd80106a53.png)

Submitting your font. It is used normally, but does not display Cyrillic
![hro8dhd](https://cloud.githubusercontent.com/assets/18671550/14827176/ea0f05e2-0c02-11e6-8db2-4eb4d04ddc64.png)

using the program crash:
`ImFontConfig config;
config.MergeMode = true;`

**Comment by ocornut** [comment]
See https://github.com/ocornut/imgui/issues/609
