### ISSUE TITLE
How to increase length of Combo dropdown window

### ISSUE THREAD

**Issue by mistahmikey** [ocornut/imgui#6130]
Is there a way to make the window length arbitrarily large?

**Comment by ocornut** [comment]
There are flags to BeginCombo() to configure the height to preset values, and you can also call SetNextWindowSize() prior to BeginCombo() to set an explicit height.

**Comment by mistahmikey** [comment]
Thanks for the quick response.  Unfortunately, the SetNextWindowSize is not having any affect.  I  am using a lua binding, and my code looks roughly like this:
local dropdownSize = #items*GUI:GetFrameHeight()
GUI:SetNextWindowSize(0.0,dropdownSize,GUI.SetCond_Always)

if GUI:BeginCombo(label,selectedItem,flags) then
for i = 1,#items do
local item = tostring(items[i])
local isSelected = (item == selectedItem)
if GUI:Selectable(item,isSelected) then
if not isSelected then
newItem = item
changed = true
end
end

GUI:EndCombo()

end
I've verified the size is getting calculated correctly, but the combobox window remains at the default size. Let me know if I am misunderstanding this.


Thanks,

Mike
On 1/30/2023 4:17:06 PM, omar ***@***.***> wrote:
There are flags to BeginCombo() to configure the height to preset values, and you can also call SetNextWindowSize() prior to BeginCombo() to set an explicit height.

**Comment by mistahmikey** [comment]
FYI, I am constrained to using version 1.63, if that matters.

**Comment by ocornut** [comment]
That explains why it doesn’t work. You can still use the flags to set policies assuming they were available in 1.63.

You should update because 1.63 is brutally ancient in Dear ImGui terms.

**Comment by mistahmikey** [comment]
Yeah, I think the flags are available.  And I can't upgrade, as much as I would like to - it's in an embedded product over which I have no control.  So just to be clear - in v1.63, there is no way to make the dropdown as long as the number of items it contains (beyond what the flags allow, at least), correct?
On 1/30/2023 6:49:52 PM, omar ***@***.***> wrote:
That explains why it doesn’t work. You can still use the flags to set policies assuming they were available in 1.63.
You should update because 1.63 is brutally ancient in Dear ImGui terms.

**Comment by ocornut** [comment]
> So just to be clear - in v1.63, there is no way to make the dropdown as long as the number of items it contains (beyond what the flags allow, at least), correct?

I don't know, I can't be looking at solving problems for a 4.5 years old version.
But the flags e.g. `ImGuiComboFlags_HeightLargest` are available since 1.53.

>  and you can also call SetNextWindowSize() prior to BeginCombo() to set an explicit height.

FYI I was wrong here:
BeginCombo() supported `SetNextWindowSizeConstraints()` but not `SetNextWindowSize()`, until newly pushed f14288708.

**Comment by mistahmikey** [comment]
Yep, I understand.  Thanks for getting back to me anyway. You can close this one again.
On 1/31/2023 5:25:32 AM, omar ***@***.***> wrote:
So just to be clear - in v1.63, there is no way to make the dropdown as long as the number of items it contains (beyond what the flags allow, at least), correct?
I don't know, I can't be looking at solving problems for a 4.5 years old version.
But the flags e.g. ImGuiComboFlags_HeightLargest are available since 1.53.
and you can also call SetNextWindowSize() prior to BeginCombo() to set an explicit height.
FYI I was wrong here:
BeginCombo() supported SetNextWindowSizeConstraints() but not SetNextWindowSize(), until newly pushed f142887 [https://github.com/ocornut/imgui/commit/f142887088c9e94f17aa5a5b263b30add5d6a10a].
