### ISSUE TITLE
Some errors with ImVec2 + math while coding a custom checkbox.

### ISSUE THREAD

**Issue by Liam5750** [ocornut/imgui#6137]
**Version/Branch of Dear ImGui:**

Version: DX9
Branch: It's just the latest version with all the essential files.

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: Visual Studio 2022 Community
Operating System: Revision OS Windows 11 Pro

**My Issue/Question:**

So I am adding a custom checkbox and here is the line of code causing me all the trouble:
`const ImRect bb(pos, pos + pos);`
The error is:
No operator "+" matches these operands: operand types are: ImVec2 + ImVec2

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/74884194/216459934-22ecff2f-a97e-4103-9d2b-fb6e6c5c5d3d.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
const ImRect bb(pos, pos + pos);
```

**Comment by ocornut** [comment]
See the definition of ImVec2 we don’t define maths operators for it by default, as they could collide with your own maths operators in the case you setup ImVec2 to auto-cast to your own math types.

You can import our maths operator by using:
```
#define IMGUI_DEFINE_MATH_OPERATORS
#include "imgui_internal.h"
```

**Comment by xXxNozz4rrxXx** [comment]
> See the definition of ImVec2 we don’t define maths operators for it by default, as they could collide with your own maths operators in the case you setup ImVec2 to auto-cast to your own math types.
> 
> You can import our maths operator by using:
> 
> ```
> #define IMGUI_DEFINE_MATH_OPERATORS
> #include "imgui_internal.h"
> ```

hello i have the same error even if i define the :
> #define IMGUI_DEFINE_MATH_OPERATORS
> #include "imgui_internal.h"
still have this error 
![image](https://github.com/ocornut/imgui/assets/76511149/3ac96af8-51b8-41b6-9b9e-e4d2cbeb62b5)
![image](https://github.com/ocornut/imgui/assets/76511149/dbefb6b0-92e8-4f4c-8844-77eeba5275e1)

**Comment by Bourdon94m** [comment]
Hello, 

It can be useful for people.

Create helper class and add :

```
// Addition
inline ImVec2 operator+(const ImVec2& lhs, const ImVec2& rhs) {
	return ImVec2(lhs.x + rhs.x, lhs.y + rhs.y);
}
inline ImVec2& operator+=(ImVec2& lhs, const ImVec2& rhs) {
	lhs.x += rhs.x; lhs.y += rhs.y; return lhs;
}

// Sub
inline ImVec2 operator-(const ImVec2& lhs, const ImVec2& rhs) {
	return ImVec2(lhs.x - rhs.x, lhs.y - rhs.y);
}
inline ImVec2& operator-=(ImVec2& lhs, const ImVec2& rhs) {
	lhs.x -= rhs.x; lhs.y -= rhs.y; return lhs;
}

// Mult by scalar
inline ImVec2 operator*(const ImVec2& lhs, float scalar) {
	return ImVec2(lhs.x * scalar, lhs.y * scalar);
}
inline ImVec2 operator*(float scalar, const ImVec2& rhs) {
	return ImVec2(rhs.x * scalar, rhs.y * scalar);
}
inline ImVec2& operator*=(ImVec2& lhs, float scalar) {
	lhs.x *= scalar; lhs.y *= scalar; return lhs;
}

// Div by scalar
inline ImVec2 operator/(const ImVec2& lhs, float scalar) {
	return ImVec2(lhs.x / scalar, lhs.y / scalar);
}
inline ImVec2& operator/=(ImVec2& lhs, float scalar) {
	lhs.x /= scalar; lhs.y /= scalar; return lhs;
}
```
