### ISSUE TITLE
Adding ImGui::IsWindowOrAnyChildHovered

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#615]
I need a function to tell me if a window or any of its children is hovered.

I see an ImGui::IsWindowHovered in the API:

```cpp
bool ImGui::IsWindowHovered()
{
    ImGuiState& g = *GImGui;
    return g.HoveredWindow == g.CurrentWindow && IsWindowContentHoverable(g.HoveredRootWindow);
}

```

I need more an ImGui::IsWindowOrAnyChildHovered. 
My hack at this would be something like:

```cpp
bool ImGui::IsWindowOrAnyChildHovered()
{
    ImGuiState& g = *GImGui;
    return (g.HoveredWindow && (g.HoveredWindow->RootWindow == g.CurrentWindow->RootWindow) && IsWindowContentHoverable(g.HoveredRootWindow));
}
```

but this may not be correct for the 100% of cases, so I'm asking help here ;-)

**Comment by ocornut** [comment]
That would be `IsRootWindowOrAnyChildHovered()` according the naming convention used by the other functions (bit of a confusing name unfortunately).

Imagine a window tree where Ax are child of A, etc:
- A
- AA
- AAA
- AAB
- AB
- ABA
- ABB

Your function works as expected if you call it in the context of A.
But if you are in the context of AA while AB is hovered (both being childs of A, so AA and AB are sibling) it will allow return true, which may not be a issue for your use case but contradicts the function name.

So the simplest here would be to add your function as `IsRootWindowOrAnyChildHovered()`

**Comment by ocornut** [comment]
To implement `IsWindowOrAnyChildHovered` we need to store a ParentWindow in ImGuiWindow, and move backward from g.HoveredWindow down the parent chain, that's an easy change I could also add if `IsRootWindowOrAnyChildHovered` isn't what you want.

**Comment by Pagghiu** [comment]
IsRootWindowOrAnyChildHovered() is what I was looking for, and anything you're writing here makes perfectly sense.
I will let you know if I'll ever need a real IsWindowOrAnyChildHovered 👍 
Thanks!
