### ISSUE TITLE
[Question] Background layer as a window?

### ISSUE THREAD

**Issue by ngortheone** [ocornut/imgui#6152]
I apologize if this question was already answered somewhere, I couldn't find any relevant info.

Is it possible to have a "default" window/layer that occupies the entire viewport where widgets can be placed?
By default it is just a solid color and all widgets are located in windows. 

I am trying to get similar behavior as can be seen here: 
https://www.egui.rs/#demo

There is a default "main" window in the background where some widgets are located, other widgets are in windows, and windows are "above" the main window.

Is this possible with imgui?
Thanks

P.S. I've tried declaring widgets outside of any window, but they still appear in a "Debug" window

**Comment by ocornut** [comment]
Isn't that what `Demo->Examples->Fullscreen Window` does?

Something like:

```cpp
ImGuiWindowFlags flags = ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoSavedSettings
const ImGuiViewport* viewport = ImGui::GetMainViewport();
ImGui::SetNextWindowPos(viewport->Pos);
ImGui::SetNextWindowSize(viewport->Size);
if (ImGui::Begin("##Fullscreen window", p_open, flags))
...
```

You may then use other window flags e.g. _NoBackground.

**Comment by ngortheone** [comment]
@ocornut `Demo->Examples->Fullscreen Window` is almost what I want, but fullscreen widow is "above" all other windows, so I can't use normal windows. Instead of "above" I want it to be "below"

**Comment by ocornut** [comment]
You need to submit it first and use the ImGuiWindowFlags_NoBringToFrontOnFocus flag.

**Comment by ngortheone** [comment]
Thanks! It worked
