### ISSUE TITLE
is it possible to dynamically modify items content of Combo ? 

### ISSUE THREAD

**Issue by evgeshkastrong** [ocornut/imgui#6156]
Hi!  Imgui::Combo should show content of directory when click on it, content of files may change from time to time. Is it possible by means of imgui to dynamically update it's combo items ? if possible - in what way it can be done ?

**Comment by Half-People** [comment]
Yes. you can use `ImGui::BeginCombo()` `ImGui::EndCombo()` `ImGui::SelectBar()`try to create Combo.I hope I can help you

**Comment by ocornut** [comment]
The entire point and philosophy of dear imgui is that everything is dynamic. Every frame you resubmit your current contents, whatever it is.
