### ISSUE TITLE
no MainViewPort update when child window detached to outside frame

### ISSUE THREAD

**Issue by uraymeiviar** [ocornut/imgui#6158]
**Version/Branch of Dear ImGui:**

Version: 1.8.3
Branch: docking

**glfw/opengl3/vs2022/windows10x64**

Back-ends: opengl3 + GLFW
Compiler: visual studio 2022
Operating System: Windows 10 x64

```
io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
```

**My Issue/Question:**

it seems the parent window or mainviewport is leave un-updated if one or more child window is moved outside of frame (multi-viewport), I need to know what was the cause, and how to make it keep updating the parent window (MainWindow)

I am using GLFW, with No decoration + transparent framebuffer

**Screenshots/Video**

this video is if transparent framebuffer is enabled

![imgui1](https://user-images.githubusercontent.com/4237078/218266580-1cb90932-b859-418b-93d3-7a4a81af5bdb.gif)

this video is I check with disabled transparent frame buffer and commented out `glClear()`

![imgui2](https://user-images.githubusercontent.com/4237078/218266628-a0c74d31-a5ba-4e0d-bf47-be425e7833a0.gif)

the point is, why parent window only updated/rendered if no multiviewport running (as in some window detached from mainviewport)

```
// main render loop
glfwMakeContextCurrent(this->glfwWindow);
glfwSwapInterval(0);
glfwPollEvents();

ImGui::SetCurrentContext(this->imguiContext);

glClear(GL_COLOR_BUFFER_BIT); //can be disabled to check
ImGui_ImplOpenGL3_NewFrame();
ImGui_ImplGlfw_NewFrame();
ImGui::NewFrame();

ImGui::Begin("MainWindow", NULL,
	ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoDocking);
{
	ImGui::BeginChild("test");
	ImVec2 mousePos = ImGui::GetMousePos();
	ImGui::Text(fmt::format("mouse pos {:.1f} , {:.1f}", mousePos.x, mousePos.y).c_str());
	ImGui::EndChild();
	
	ImGui::ShowDemoWindow(&this->run);
}
ImGui::End();			

ImGui::Render();
ImGui::UpdatePlatformWindows();
ImGui::RenderPlatformWindowsDefault();

ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

glfwSwapBuffers(this->glfwWindow);
```

**Comment by ocornut** [comment]
Please provide a correct repro. It is clear that the code you posted doesn’t match what we see on the screen. Make sure your issue can be recreated in the GLFW+GL3 example.

**Comment by uraymeiviar** [comment]
the problem can be solved if I enable the `io.ConfigViewportsNoAutoMerge = true;` but the problem with this is, I will have one blank window on the taskbar, so it seems there are 3 active window there:

![image](https://user-images.githubusercontent.com/4237078/218268040-5e2a5486-733e-4b52-ada7-661294bcefba.png)

**Comment by ocornut** [comment]
I am closing this until you provide correct information. When you do we can reopen.

Please also read the wiki glossary to ensure you are using accurate terms, otherwise it is difficult to makes sense of things at this topic is not simple.
