### ISSUE TITLE
How could I know whether a Selectable is double-clicked?

### ISSUE THREAD

**Issue by RyokoAkizuki** [ocornut/imgui#616]
I want to copy the Columns/Basic example to create a resource explorer, where I could view the metainfo when I click on a directory and open it when double click. However I've found that there is only an IsMouseDoubleClicked() function for buttons. I'd like to know is there any way to achieve this. Thank you.

**Comment by Roflraging** [comment]
This should suffice:

```
        ImGui::Selectable("selectable", selectableDoubleClicked);

        if (ImGui::IsItemHovered() && ImGui::IsMouseDoubleClicked(0))
        {
            // Do stuff on Selectable() double click.                                                                                                                                                                                                                           
            selectableDoubleClicked = !selectableDoubleClicked;
        }
```

**Comment by RyokoAkizuki** [comment]
It appears that I misunderstood the parameter of IsMouseDoubleClicked. Thank you.

**Comment by ocornut** [comment]
There is a flag to Selectable() which you can use to allow it returning true on double-click then you can call if IsDoubleClicked when Selectable() returns true.
