### ISSUE TITLE
lottie animation widget for imgui

### ISSUE THREAD

**Issue by dalerank** [ocornut/imgui#6160]
Version: 1.88
Branch: master

Back-ends: dx11 (another will be add later)
Compiler: msvc
Operating System: win10
Dependencies: rapidjson

lottie animation widget for imgui 
repo: https://github.com/dalerank/imlottie

**Screenshots/Video**
![lottie](https://user-images.githubusercontent.com/918081/218279291-cec0a389-13e4-4131-a027-9caaf97ccc87.gif)

```
// minimal setup

    ImLottie::init();
    while (!done) {
         ImLottie::LottieAnimation(_("speaker.json").c_str(), ImVec2(48, 48), true, 0);

        ImLottie::sync(g_pd3dDevice, g_pd3dDeviceContext);
   }
```

**Comment by Half-People** [comment]
nice

**Comment by dalerank** [comment]
Sure, will add soon

**Comment by dalerank** [comment]
![ezgif-2-aa61193f63](https://github.com/ocornut/imgui/assets/918081/4c4caee5-6c27-4964-9570-9be3002e6d32)
500x250 here @ocornut

**Comment by ocornut** [comment]
Could you add it to the wiki in the section I linked to?

**Comment by dalerank** [comment]
Done

**Comment by ocornut** [comment]
Hello,
You didn’t add it to the right section, you added a new section and cut the Spinner section in the middle. Please add it to the Miscellaneous section as requested above, it seems more adequate.

**Comment by dalerank** [comment]
Fixed

**Comment by ocornut** [comment]
Thank you this is great !
