### ISSUE TITLE
Center window only works after imgui.ini has been written

### ISSUE THREAD

**Issue by dacobi** [ocornut/imgui#6161]
Branch master
Backend sdlrenderer in Ubuntu 22.04 using g++

I'm trying to center a window in my main SDL window by using "ImGui::SetWindowPos(center-winsize/2, ImGuiCond_Once)"

I get the window size by calling ImGui::GetWindowSize() before ImGui::End() and center is from my main SDL window.

The problem is that it only works after the imgui.ini file has been written even though the values of winsize are correct the first time. The first time the program runs the window will be placed starting at center.x/y

Is there a correct way to do this? I found posts on ImGui::SetNextWindowPosCenter, but that's no longer available.

```
render(int xpos, int ypos){

...

     ImVec2 cWinSize = ImGui::GetWindowSize();
     ImVec2 cWinPos;

     cWinPos.x = xpos;
     cWinPos.y = ypos;

     if(bDialogCenter){
	    cWinPos.x -=  cWinSize.x/2;
	    cWinPos.y -=  cWinSize.y/2;
     }

     ImGui::SetWindowPos(cWinPos, ImGuiCond_Once); 

     ImGui::End(...);
}
```

**Comment by ocornut** [comment]
To center a window you should use:

```
ImGui::SetNextWindowPos(ImGui::GetMainViewport()->GetCenter(), ImGuiCond_Once, ImVec2(0.5f, 0.5f));
ImGui::Begin(…);
```

**Comment by ocornut** [comment]
Btw the reason for your code to not work is that during the first frame of a new window without saved data, we don’t know its window size until the next frame. Therefore your call to GetWindowSize() returns a dummy small size that is used while the window is hidden on its first frame.

Using SetNextWindowPos() + the pivot parameter set to center (0.5f, 0.5f) side-step this and allows the window to be centered as soon as it is displayed.

This is what modal popups use by default.

**Comment by dacobi** [comment]
Yes, I saw that winsize wasn't correct the first time. I must have been
watching the wrong variable while debugging.
