### ISSUE TITLE
Add click and drop to drag and drop

### ISSUE THREAD

**Issue by Iacaka** [ocornut/imgui#6163]
Hello, sorry if this is already covered, but i have a small question. I have a working drag and drop (switch) widget, like the one in the Demo and everything is working just fine. So, my question is, how do i make it not only drag and drop, but click and click again to drop on a second place. Thanks in advance! Here is my code:
 
```
for (int n = 0; n < 9; n++)
					{
						ImGui::PushID(n);
						ImGui::SameLine();
						if (p.inventory.data[n].itemID != 0) {
							ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(0.0f, 0.0f));
							ImGui::ImageButton(AssetManager::m_Textures[itemData[p.inventory.data[n].itemID].textureID], ImVec2(90, 90), ImVec2(0.f, 0.f), ImVec2(1.f, 1.f)); // Image Buttons
							ImGui::PopStyleVar();

							int adder = 0;
							if (p.inventory.data[n].amount >= 10) adder = 7; // placement change for double digets
							float txtX = (window.GetSize().x - 904) / 2 + 97 + 8 * (int)(n % 9) + 90 * (int)(n % 9) - adder; //.X
							float txtY = window.GetSize().y - 125 + 85 + 4 * (int)(n / 9);//.Y
							ImGui::GetWindowDrawList()->AddText(ImVec2(txtX, txtY), 0xFFFFFFFF, std::format("{0}", p.inventory.data[n].amount).c_str()); // showing values
						}
							
						else {
							ImGui::Button("", ImVec2(90, 90)); // empty button
						}

						if (ImGui::BeginDragDropSource(ImGuiDragDropFlags_SourceNoPreviewTooltip))
						{
							ImGui::SetDragDropPayload("DND_DEMO_CELL", &n, sizeof(int));
							ImGui::EndDragDropSource();
						}
						if (ImGui::BeginDragDropTarget())
						{
							if (const ImGuiPayload* payload = ImGui::AcceptDragDropPayload("DND_DEMO_CELL"))
							{
								IM_ASSERT(payload->DataSize == sizeof(int));
								int payload_n = *(const int*)payload->Data;

								auto tmp = p.inventory.data[n];
								p.inventory.data[n] = p.inventory.data[payload_n];
								p.inventory.data[payload_n] = tmp;

							}
							ImGui::EndDragDropTarget();
						}
						ImGui::PopID();
					}
```

**Comment by ocornut** [comment]
> how do i make it not only drag and drop, but click and click again to drop on a second place. 

This is not supported.
It would require two things:
- Rework the starting condition in `BeginDragDropSource().`
- Rework the dropping condition in `AcceptDragDropPayload()`, `EndFrame()`, (search for `g.DragDropMouseButton`).
- Add a cancelling condition.
It might be possible to rework things this way so I don't see that happening.

**Comment by Iacaka** [comment]
> It might be possible to rework things this way so I don't see that happening.
So it's possible if i spend big enough portion of my time? 
Well, i may try i guess, if i decide it's important for my project. Thanks again, looking forward adding it as a feature.

**Comment by Iacaka** [comment]
Hey @ocornut. I changed the starting condition and now it pickups when i simply click the item, which is great, but while was trying to rework the dropping condition in AcceptDragDropPayload(), i ran into some problems. I can't really get it to work. I tried some stuff:

1. make a bool is_item_holding (which surely has an ImGui alternative done already, i just didn't know what to use) with starting value as false, and then change/invert when i use left click (bool = !bool), but after i ran tests and debugged it, it just stayed false the entire time. here is the code:
` if (g.IO.MouseClicked[mouse_button])payload.is_item_picked = !payload.is_item_picked;`
and then tried this:
`payload.Delivery = was_accepted_previously && payload.is_item_picked && g.IO.MouseClicked[mouse_button];`
it picks it up, and show an yellow outline (by default) on the hovered item, but it doesn't drop it after i click. Then i removed the is_item_picked condition (because it was all false no mater what i did) and left it like this:
`payload.Delivery = was_accepted_previously && g.IO.MouseClicked[mouse_button];`
and the same issue still ocured.

I surely missed something, and made a mistake somewhere, but I'm not sure exactly what to do and how to do it.

Note: with only the starting condition changed, after just a click, it swaps with the first collided item, so that means pick up works, i just don't know how to set the dropping condition

here are vids of what i have and what's going on:

https://user-images.githubusercontent.com/93211222/220997049-d9a4bc3c-eee9-48bd-b57a-58e8c76fb3eb.mp4


https://user-images.githubusercontent.com/93211222/220997053-c0685c58-6e81-459a-937f-493f594bd024.mp4


https://user-images.githubusercontent.com/93211222/220997054-a46990f7-ba9e-415b-b871-80b8064b7382.mp4

**Comment by Iacaka** [comment]
It's done, sorry for the late update. For starting condition i used:
`if (g.IO.MouseClicked[mouse_button] && !g.DragDropActive)`
originally on line 120052 (may differ because i have an older version of imgui.cpp)
and for dropping condition:
` payload.Delivery = was_accepted_previously && g.DragDropActive && IsMouseClicked(ImGuiMouseButton_Left);`
originally on line 12247

It works for me, so if anybody needs it.
