### ISSUE TITLE
Clipper Item Height when only a single row is supplied

### ISSUE THREAD

**Issue by vjotchere** [ocornut/imgui#6165]
**Version/Branch of Dear ImGui:**

Version: 1.89.2 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

Hello,

I'm working with a Clipper inside of a Table. Tables typically have enough rows to justify the need for a Clipper however occasionally a table may only have a single row. Since different parts of my application need to know when a Selectable row inside of a Table is interacted with (Left/Right Clicks, Double Clicks, Hovers, Drag Selections), I'm calculating which Selectable rows are interacted using Mouse Position, Clipper Scroll Offset, Display Start Offset and Clipper Item Height. I'm able to get almost everything working as expected, however when there is only one item in the Clipper, the Clipper returns the Item Height as -1.

I understand the clipper determines the Item Height after the first frame so this information isn't available until after the first row has been rendered. My question is, is it possible to determine the Item Height in a Clipper with a single item? Alternatively, is there a way for me to calculate the Selectable that a user is interacting with in this case (a workaround for this specific case)? Are there other ways to determine user interactions with a table (including Clicks and Hovers) that I may have overlooked (to refactor how I handle item in table interactions in general)?

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/43732572/218848593-3f3ac3bb-65f0-4a42-bdc1-d61a2104cdb8.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
    const int clipperRows = 2;

    static ImGuiTableFlags flags = ImGuiTableFlags_None;

    if (ImGui::BeginTable("Table", 3, flags))
    {
        // Create columns
        ImGui::TableSetupScrollFreeze(0, 1);
        ImGui::TableSetupColumn("Row #", ImGuiTableColumnFlags_NoSort | ImGuiTableColumnFlags_WidthFixed, 0.0f);
        ImGui::TableSetupColumn("Clipper Item Height", 0, 0.0f);
        ImGui::TableSetupColumn("Empty", ImGuiTableColumnFlags_WidthFixed, 0.0f);

        ImGui::TableHeadersRow();

        ImGuiListClipper clipper;
        clipper.Begin(clipperRows);
        while (clipper.Step())
        {
            for (int row = clipper.DisplayStart; row < clipper.DisplayEnd; row++)
            {
                ImGui::TableNextRow();

                // Column 1
                ImGui::TableSetColumnIndex(0);
                ImGui::TextUnformatted(std::format("  {}", row + 1).c_str());

                // Column 2
                ImGui::TableSetColumnIndex(1);
                ImGui::TextUnformatted(std::format("{}", clipper.ItemsHeight).c_str()); // Always -1

                // Column 3
                ImGui::TableSetColumnIndex(2);
                ImGui::TextUnformatted("Empty");
            }
        }
        ImGui::EndTable();
    }
```

**Comment by GamingMinds-DanielC** [comment]
> I understand the clipper determines the Item Height after the first frame so this information isn't available until after the first row has been rendered. My question is, is it possible to determine the Item Height in a Clipper with a single item?

The item height is calculated when you call `Step()` after submitting your first item. You won't be able to get the height from the clipper before that point, so not while you are still in the process of submitting that very first item.

If you really need to have the height while processing your single item, you can ask for the item height after you are done with the list and memorize it for the next frame. But be aware that you have 1 frame of latency this way. Other than that you would have to calculate the item height beforehand.

**Comment by ocornut** [comment]
+1 on message above.

> My question is, is it possible to determine the Item Height in a Clipper with a single item? 

Yes but only at the end of that first step...
Note that you submitting those items so you should be able to tell their height via a different route if need.

But this is a little suspicious to read:

> I'm calculating which Selectable rows are interacted using Mouse Position, Clipper Scroll Offset, Display Start Offset and Clipper Item Height.

You shouldn't need to compute those things, merely submit items as requested and use their result/status.
So you'd probably need to clarify why you think you need to read that `ItemsHeight` value in the first place.

**Comment by vjotchere** [comment]
Thanks for both responses. 

> If you really need to have the height while processing your single item, you can ask for the item height after you are done with the list and memorize it for the next frame. But be aware that you have 1 frame of latency this way.

This answers my question. Admittedly I was so fixated on solving this problem within 1 frame that it hadn't even occurred to me that I could just wait a frame and move on. I'm not too concerned with the latency.

> You shouldn't need to compute those things, merely submit items as requested and use their result/status.
So you'd probably need to clarify why you think you need to read that ItemsHeight value in the first place.

You're right, I think the issue at hand is how my program is internally handling selected items and that's the root of the problem I'm having now.

I was using the ItemHeight to calculate the location of items in the table so I can internally process selections that occur from events other than a click. I can just leverage the PushID/PopID pattern to find out which elements of the table are being interacted with. I'd learned about the IDing system after implementing the table so it hadn't occurred to me I could solve internal item handling more efficiently.

Thanks again! Closing this issue.

**Comment by vjotchere** [comment]
Re-opening as this is an extension to my original problem and not a new issue.

Is there a way to prevent tables with Selectables from appending additional information to the end of the top level ID, I'm having quite a bit of trouble understanding where this appended information is being added in the code and this increases the difficulty of calculating IDs slightly. I've noticed this in my program and the demo as well, as pictured below...

![image](https://user-images.githubusercontent.com/43732572/219899376-60a90976-6b0b-4891-b0c9-0b9b3d3d42b6.png)

> "Dear ImGui Demo/table_advanced_DA36A7EO" [window]

I'm referring to the "/table_advanced_DA36A7EO" portion

**Comment by ocornut** [comment]
Why are you calculating Ids manually, for what purpose?

**Comment by vjotchere** [comment]
I'm fine tuning a feature in a program, which allow users to select rows in a table by using a click and drag action, similar to the Windows Explorer feature. I've previously posted a separate unrelated issue about this same feature which I'm linking for clarity and added context (https://github.com/ocornut/imgui/issues/5718)

To answer your question, I want to  manually calculate IDs to give users the ability to select rows in a table without directly interacting with that row, a possible user scenario that I would like to handle. Currently I'm handing this issue using the aforementioned technique

> I'm calculating which Selectable rows are interacted using Mouse Position, Clipper Scroll Offset, Display Start Offset and Clipper Item Height.

As you pointed out, this isn't the ImGui approach and is error-prone as well. I believe if I'm able to calculate IDs for rows in the clipper, I can "ask" the widgets their exact screen coordinates. With this information I can then determined which rows are within the selection rectangle and add them to my selected vector.

In the Gif below, notice how rows in the table are being selected without the mouse actually hovering over these rows
![Drag Select Selection](https://user-images.githubusercontent.com/43732572/220162427-6593d862-59ad-411b-800d-b89634ad3d9b.gif)

**Comment by ocornut** [comment]
Your approach seems unnecessarily complicated. You can query your cursor start position before submitting items + clipper item height (or item height if you know it yourself) that’s all you need to tell where each here, you don’t need more info than ItemHeight from the clipper, and ids have nothing to do with it.

**Comment by vjotchere** [comment]
I see, I think it comes down to a code organization problem that once solved, will simplify and reduce the amount of code. Thanks again!
