### ISSUE TITLE
Multithreaded ImDrawList usage causing flicks

### ISSUE THREAD

**Issue by Skreamex** [ocornut/imgui#6167]
**Version/Branch of Dear ImGui:**

Version: v1.89.3
Branch: features/shadows and master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Operating System: Windows 10

**My Issue/Question:**

Hello. I was using 1.84 WIP to use separated drawlists.
Fist thread fills some draw data to draw list, locks mutex and copies to rendering list
Main d3d9 thread 
**Begin()** function
```
m_draw_list->_ResetForNewFrame();
m_draw_list->PushTextureID(ImGui::GetIO().Fonts->TexID);
m_draw_list->PushClipRectFullScreen();
```

**End()** function 
```
render_mutex.lock();
*m_draw_list_act = *m_draw_list;
render_mutex.unlock();
```

Get data to draw
```
ImDrawList* CD3DRender::GetScene() {

    if (render_mutex.try_lock()) {
      *m_draw_list_rendering = *m_draw_list_act;
      render_mutex.unlock();
    }
    
    return m_draw_list_rendering;
}
```

D3D call looks like 
```
ImGui::EndFrame();
ImGui::Render(pRenderer->GetScene());
```

```
void ImGui::Render(ImDrawList* list)
{
    ImGuiContext& g = *GImGui;
    IM_ASSERT(g.Initialized);

    if (g.FrameCountEnded != g.FrameCount)
        EndFrame();
    const bool first_render_of_frame = (g.FrameCountRendered != g.FrameCount);
    g.FrameCountRendered = g.FrameCount;
    g.IO.MetricsRenderWindows = 0;

    CallContextHooks(&g, ImGuiContextHookType_RenderPre);

    // Add background ImDrawList (for each active viewport)
    for (int n = 0; n != g.Viewports.Size; n++)
    {
        ImGuiViewportP* viewport = g.Viewports[n];
        viewport->DrawDataBuilder.Clear();
        if (viewport->DrawLists[0] != NULL)
            AddDrawListToDrawData(&viewport->DrawDataBuilder.Layers[0], GetBackgroundDrawList(viewport));

       // Add data from other thread
        if(!list->CmdBuffer.empty())
            AddDrawListToDrawData(&viewport->DrawDataBuilder.Layers[0], list);
    }
   . . .
```

After upgrade I ran into problem that all vertexes are flickering
I've started to search what causes it and after some compares realized that **ImDrawListSharedData** has new member
```
ImVector<ImVec2> TempBuffer;
```

So it means two thread accesses same TempBuffer variable in same time

I've done simpe quick fix to solve problem 
TempBuffer member now function
```
ImVector<ImVec2>& ImDrawListSharedData::TempBuffer() {
	static std::unordered_map<unsigned long, ImVector<ImVec2>*> frame_buffers;
	auto thread_id = GetCurrentThreadId();
	auto it = frame_buffers.find(thread_id);

	if (it != frame_buffers.end()) {
		return *(it->second);
	}
	else {
		auto inst = new ImVector<ImVec2>();
		frame_buffers[thread_id] = inst;
		return *inst;
	}
}
```
And some replacements like 
```
void ImDrawList::AddPolyline(const ImVec2* points, const int points_count, ImU32 col, ImDrawFlags flags, float thickness)
{
...
 _Data->TempBuffer().reserve_discard(points_count * ((use_texture || !thick_line) ? 3 : 5));
...
}
```

Now it works fine without any glitches

**Comment by ocornut** [comment]
> So it means two thread accesses same TempBuffer variable in same time

Only if actual Draw functions are called at the same time, **which never worked even before (as they would manipulate VtxBuffer IdxBuffer etc.) so I don't think this is your issue** and you are looking at and fixing a wrong thing.

FYI this is likely incorrect:
`*m_draw_list_act = *m_draw_list;` 
There's no deep copy constructor of draw list.

**Comment by ocornut** [comment]
*EDIT* You can use `ImDrawList::CloneOutput()` but I think I will now look at reworking this function signature to allow passing a preinstanciated version.

**Comment by Skreamex** [comment]
I've spent whole day to determine what causes it.
Even without copying 
```
init(){
  m_draw_list = new ImDrawList(ImGui::GetDrawListSharedData());
}

render(){
  m_draw_list->_ResetForNewFrame();
  m_draw_list->PushTextureID(ImGui::GetIO().Fonts->TexID);
  m_draw_list->PushClipRectFullScreen();
  m_draw_list->AddRect( ... );
  End(); // EMPTY function
}
```
You can simply reproduce this bug with **CreateThread** winapi function and code above

AddRect calls:
1.  PathRect -> is ok, adds points to array
2. PathStroke -> goes into **AddPolyline** which accesses that variable ( TempBuffer )
```
// Temporary buffer
// The first <points_count> items are normals at each line point, then after that there are either 2 or 4 temp points for each line point
_Data->TempBuffer.reserve_discard(points_count * ((use_texture || !thick_line) ? 3 : 5));
```
And other thread can also access this variable while menu is building vertexes to pass to d3d_impl

**Comment by Skreamex** [comment]
> > So it means two thread accesses same TempBuffer variable in same time
> 
> Only if actual AddXXX functions are called at the same time, **which never worked even before (as they would manipulate VtxBuffer IdxBuffer etc.) so I don't think this is your issue** and you are looking at and fixing a wrong thing.
> 
> FYI this is likely incorrect: `*m_draw_list_act = *m_draw_list;` There's no deep copy constructor of draw list.

Yes, but version with allocators worked fine with that.
How it was in 1.84 WIP
```
void ImDrawList::AddPolyline(const ImVec2* points, const int points_count, ImU32 col, ImDrawFlags flags, float thickness) {
. . .
  // Temporary buffer
  // The first <points_count> items are normals at each line point, then after that there are either 2 or 4 temp points for each line point
  ImVec2* temp_normals = (ImVec2*)alloca(points_count * ((use_texture || !thick_line) ? 3 : 5) * sizeof(ImVec2)); //-V630
  ImVec2* temp_points = temp_normals + points_count;
. . .
}
```
![image](https://user-images.githubusercontent.com/6390209/219085664-2484b7f7-211f-4426-87d0-f8c302956c99.png)

**Comment by ocornut** [comment]
> You can simply reproduce this bug with CreateThread winapi function and code above

This is ambiguous, please clarify.

> And other thread can also access this variable while menu is building vertexes to pass to d3d_impl

I repeat, you can never call ImDrawList functions from those threads. This was never allowed.
Render() calls a few functions in ImDrawList().
This has nothing to do with the TempBuffer which has the same lifetime and locking requirements as other elements.

**Comment by ocornut** [comment]
> You can simply reproduce this bug with CreateThread winapi function and code above

Sorry for multiple messages. I think I understand what you meant.

This example suggestion appending to different draw lists at the same time.

`m_draw_list = new ImDrawList(ImGui::GetDrawListSharedData());`

Notice this is called GetDrawListSharedData() and the type is ImDrawListSharedData.
If you want to do this, you indeed it to create a unique ImDrawListSharedData instance per thread.
It was still lucky that your ImGui code wasn't manipulating other fields of the ImDrawListSharedData structure.

This is different from copying a drawlist so it can be rendered later (B), which is more common when a Render thread runs in parallel with an Update thread. For this, you can swap or clone your drawlist in the Update thread after calling EndFrame()/Render(), then store that data and let the Render thread process is later.

If I understand you are trying to do (A) ?

**Comment by Skreamex** [comment]
Yes, you are right. Here is working example of what I mean https://github.com/Skreamex/mtrenderer_issue
Build in x86 Release
As you said about creation shared data, I've tried this, but no output on screen, I dont know what I have to copy from main ImDrawListSharedData, so I decided to split TempBuffer for each thread

**Comment by ocornut** [comment]
> As you said about creation shared data, I've tried this, but no output on screen, I dont know what I have to copy from main ImDrawListSharedData, so I decided to split TempBuffer for each thread

You may initialize your ImDrawListSharedData instance with a copy of `*ImGui::GetDrawListSharedData()`.

Other ImGui functions may perfectly interfere with this data, e.g. if you call ImGui::PushFont() from one thread and use the drawlist with same shared data from another thread, the ImDrawListSharedData::Font/FontSize fields will change. So your solution is not correct.

**Comment by ocornut** [comment]
You'll need to investigate how the fields are set to find out where.
But I think if you copy after ImGui ran for 1 frame you may be good.

**Comment by Skreamex** [comment]
Ok, thanks for information.
Now its solved.
Hope this thread will help someone.
