### ISSUE TITLE
Can't type in Chinese

### ISSUE THREAD

**Issue by yingnierxiao** [ocornut/imgui#617]
the utf-8 input can't input in Chinese IME

**Comment by ocornut** [comment]
Please provide repro code. As far as I know it works and it works in Japanese too.
Does display works?

Its your job to provide input characters via io.AddInputCharacter().

**Comment by yingnierxiao** [comment]
open imgui/examples/apple_example  run the demo ，macsox，utf-8 input，input display  en char，no chinese char

**Comment by ocornut** [comment]
You need to load a font.

**Comment by ocornut** [comment]
You need to load a font with appropriate character ranges. Read the FAQ in imgui.cpp and extra_fonts/README

**Comment by yingnierxiao** [comment]
ImGuiIO& io = ImGui::GetIO();
    io.Fonts->AddFontFromFileTTF("extra_fonts/Aparajita.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesChinese());
  display chinese,but input is the same display en char

**Comment by ocornut** [comment]
Looks like a bug in this Apple demo bindings or GLFW bindings.

The code in imgui_impl_glfw.cpp does:
```
void ImGui_ImplGlfw_CharCallback(GLFWwindow*, unsigned int c)
{
    ImGuiIO& io = ImGui::GetIO();
    if (c > 0 && c < 0x10000)
        io.AddInputCharacter((unsigned short)c);
}
```

You can breakpoint here or `printf("%04X\n", c);` to check the values.
If you can confirm that, maybe your version of GLFW has a bug on Mac with IME?

**Comment by ocornut** [comment]
@ngnierxiao Any news?

**Comment by ocornut** [comment]
@yingnierxiao any news on this?

**Comment by boruis** [comment]
hello, i met this problem too. when i add breakpoint at ImGui_ImplGlfw_CharCallback function.
i got ascii value of what i type.

**Comment by ocornut** [comment]
There's no Chinese ASCII characters. Which language are you using?
Are the value valid Unicode points?
Please provide repro code so we can see the bug in your application, but I think it's pretty likely the bug is in your application or data side, not imgui there.

**Comment by boruis** [comment]
thanks for reply.  am using this repo https://github.com/c0i/imguix    its cocos game engine with imgui.
and i have add this 2 line code, display chinese is ok. but input did't work.
    // setup font
    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->AddFontFromFileTTF("res/FZCUYUAN.TTF", 18.0f, NULL, io.Fonts->GetGlyphRangesChinese());
