### ISSUE TITLE
Selectable renders differently within BeginChild

### ISSUE THREAD

**Issue by ypujante** [ocornut/imgui#6173]
I have the following code:

```cpp
  if(ImGui::Begin("re-edit"))
  {
    static bool useChild = true;

    ImGui::Checkbox("use_child", &useChild);

    if(useChild)
    {
      if(ImGui::BeginChild("Content"))
      {
        ImGui::Selectable("select1", true);
        ImGui::Selectable("select2", true);
      }
      ImGui::EndChild();
    }
    else
    {
      ImGui::Selectable("select1", true);
      ImGui::Selectable("select2", true);
    }
  }
  ImGui::End();
```

This produces the following result:

<img width="128" alt="Screen Shot 2023-02-16 at 11 08 41" src="https://user-images.githubusercontent.com/357116/219463802-2dfbf211-d78f-431b-868d-f4b912cb5cbf.png">
<img width="128" alt="Screen Shot 2023-02-16 at 11 08 47" src="https://user-images.githubusercontent.com/357116/219463811-c7816bdf-1ebd-4827-88bf-c2f7d1898442.png">

I don't understand why `Selectable` completely looses the spacing when embedded inside a `BeginChild`. It looks really bad that the text touches the edges of the box. 

I dug through the code and it is not obvious why there is such a behavior. From my understanding, a child is a section that has its independent scrolling/clipping region (which is why I use it: I have a row of buttons, then a list of selectables which can be long and thus need scrolling, but I want the buttons to always be visible => the selectables are in a child)

If this is not a bug and is intended to behave this way, can you please let me know how to add the lost spacing back within the `BeginChild`. 

Thank you

```
Dear ImGui 1.89.3 (18930)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __APPLE__
define: __GNUC__=4
define: __clang_version__=13.0.0 (clang-1300.0.29.30)
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_metal
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigMacOSXBehaviors
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMoveFromTitleBarOnly
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,256
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 2.00,2.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Comment by ocornut** [comment]
This is exactly the same issue as #6170, please post there !

**Comment by Slion** [comment]
Same issue:

<img width="156" height="67" alt="Image" src="https://github.com/user-attachments/assets/ea96038a-6fe4-4eec-b69c-f99e114aae5d" />

Why would the selectable render outside the window and be clipped. It is even worse for the first item as it is clipped at the top too.

If you add `ImGuiChildFlags_AlwaysUseWindowPadding` then you have too much spacing. 
<img width="166" height="125" alt="Image" src="https://github.com/user-attachments/assets/5054e195-a14e-4a08-a8ef-075a3893dc19" />

**Comment by ocornut** [comment]
> Why would the selectable render outside the window and be clipped. It is even worse for the first item as it is clipped at the top too.

It's a complex design issue. Selectable extrude themselves by half ItemSpacing on each side which was intended to cover gaps between them (which is desirable in many situation). Clearly this design has and is causing issue and will be reevaluated at some point.

> If you add ImGuiChildFlags_AlwaysUseWindowPadding then you have too much spacing.

You can set WindowPadding to ItemSpacing*0.5f if you want things to match.

**Comment by Slion** [comment]
Thanks that does the trick:

```cpp
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(ImGui::GetStyle().ItemSpacing.x*0.5f, ImGui::GetStyle().ItemSpacing.y * 0.5f));
    // Left column: vertical tab list
    ImGui::BeginChild("##SettingsTabBar", ImVec2(tabBarWidth, 0), ImGuiChildFlags_Borders);
```

<img width="164" height="127" alt="Image" src="https://github.com/user-attachments/assets/c3461609-0a50-434f-9091-4d84bd378184" />
