### ISSUE TITLE
Is there an image viewer widget?

### ISSUE THREAD

**Issue by Andersama** [ocornut/imgui#6174]
**Version/Branch of Dear ImGui:**
Version: any
Branch: any

**Back-end/Renderer/Compiler/OS**

Back-ends: any
Compiler: any
Operating System: any

**My Issue/Question:**

In the process of writing a gui to help someone label image files to train an AI. After going through the documentation again I'm pretty sure there isn't a image viewer widget on it's own. I'm fine with writing my own, but I hope I didn't miss something obvious to do the basics of what I'm after. The goal would be to like in many image editors have an area where some fixed content is displayed (an image) but can be moved and zoomed in and out on by mouse. For this use case the widget wouldn't be particularly complex so I figure it might be a good starting point for other editors.

Here are a few potential useful features:
*A shortcut / button to recenter the view
*A shortcut / button to set the zoom back to 100%

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/25020235/219550645-9d1a9316-9337-4d4f-bd75-13798dac3bf7.png)

**Example code:**
```
// Here's some code anyone can copy and paste to reproduce your issue
if(ImGui::BeginViewport("Example Bug", content_size)) { //creates a window like ImGui::Begin()?
   ImGui::GetViewportSize() // returns the size of the "content" area
   ImGui::GetViewportPos() // think ImGui::GetCursorScreenPos(), returns top left coordinate of the "content" area
}
ImGui::End();
```

**Comment by ocornut** [comment]
Everything I know of has been listed in the Wiki:
https://github.com/ocornut/imgui/wiki/Useful-Extensions

I suppose imgInspect and ImGuiTexInspect might be good reference but are more complex things.
Your thing is pretty much down to calling Image() or ImDrawList::AddImage() and managing a transform.
Also see e.g. Demo->Examples->Custom Rendering->Canvas for an idea of how to pan.

**imgInspect**
<BR> [github/CedricGuillemet/imgInspect](https://github.com/CedricGuillemet/imgInspect)
<BR> ![image](https://user-images.githubusercontent.com/8225057/118988474-83515f80-b981-11eb-8ce1-4818ddc3195a.png)

**ImGuiTexInspect**
<BR> [github/andyborrell/imgui_tex_inspect](https://github.com/andyborrell/imgui_tex_inspect) ([discussion](https://github.com/ocornut/imgui/issues/4352), [online demo](https://andyborrell.github.io/imgui_tex_inspect))
<BR> <a href="https://user-images.githubusercontent.com/5911521/126656032-b045b65b-5f42-4065-9c49-c1a22e866a28.png"><img src="https://user-images.githubusercontent.com/5911521/126656032-b045b65b-5f42-4065-9c49-c1a22e866a28.png" alt="Screenshot of ImGuiTexInspect" width="500" /></a>

**Comment by ocornut** [comment]
You can use InvisibleButton() to capture inputs, this is what the canvas demo does.

**Comment by Andersama** [comment]
Not exactly great control wise yet, but here's a rough mockup for anyone else.
```c
	if (ImGui::Begin(imgui_id.c_str())) {
		ImDrawList* draw_list = ImGui::GetWindowDrawList();

		// Get the current ImGui cursor position
		ImVec2 canvas_p0   = ImGui::GetCursorScreenPos();    // ImDrawList API uses screen coordinates!
		ImVec2 canvas_size = ImGui::GetContentRegionAvail(); // Resize canvas to what's available

		// Garuntee a minimum canvas size
		canvas_size.x = std::max(canvas_size.x, 256.0f);
		canvas_size.y = std::max(canvas_size.y, 250.0f);

		ImVec2 canvas_p1 = ImVec2{canvas_p0.x + canvas_size.x, canvas_p0.y + canvas_size.y};

		const ImVec2 origin(canvas_p0.x + open_images[i].transform.translate.x,
						canvas_p0.y + open_images[i].transform.translate.y); // Lock scrolled origin
		const ImVec2 mouse_pos_in_canvas(imio.MousePos.x - origin.x, imio.MousePos.y - origin.y);

		ImGui::InvisibleButton("##canvas", canvas_size,
						ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_MouseButtonRight |
										ImGuiButtonFlags_MouseButtonMiddle);

		const bool canvas_hovered = ImGui::IsItemHovered(); // Hovered
		const bool canvas_active  = ImGui::IsItemActive();  // Held

		// const ImVec2 canvas_p0 = ImGui::GetItemRectMin(); // alternatively we can get the rectangle like this
		// const ImVec2 canvas_p1 = ImGui::GetItemRectMax(); 

		// Draw border and background color
		ImGuiIO&    io        = ImGui::GetIO();
		draw_list->AddRectFilled(canvas_p0, canvas_p1, IM_COL32(50, 50, 50, 255));
		draw_list->AddRect(canvas_p0, canvas_p1, IM_COL32(255, 255, 255, 255));

		// TODO: shift or ctrl to slow zoom movement
		//if (canvas_active) {
			float zoom_delta = io.MouseWheel;
			open_images[i].transform.scale.x += zoom_delta;
			open_images[i].transform.scale.y += zoom_delta;
			// 2.0f -> 2x zoom in
			// 1.0f -> normal
			// 0.5f -> 2x zoom out
			// TODO: clamp based on image size, do we go pixel level?
			open_images[i].transform.scale.x = std::clamp(open_images[i].transform.scale.x, 0.01f, 100.0f);
			open_images[i].transform.scale.y = std::clamp(open_images[i].transform.scale.y, 0.01f, 100.0f);
		//}

		// 0 out second parameter if a context menu is open
		if (canvas_active && ImGui::IsMouseDragging(ImGuiMouseButton_Left, 1.0f)) {
			open_images[i].transform.translate.x += ImGui::GetIO().MouseDelta.x;
			open_images[i].transform.translate.y += ImGui::GetIO().MouseDelta.y;
		}

		// we need to control the rectangle we're going to draw and the uv coordinates
		const ImVec2 image_p1 = {origin.x + (open_images[i].transform.scale.x * open_images[i].width),
						origin.y + (open_images[i].transform.scale.x * open_images[i].height)};
		draw_list->AddImage(open_images[i].texture_id, origin, image_p1);
	}
	ImGui::End();
```

**Comment by Andersama** [comment]
@ocornut would there be a quick way to render only part of some region? I patched up the example but
```c
  draw_list->AddImage(open_images[i].texture_id, origin, image_p1);
```
will draw beyond the bounds of the provided canvas rectangle if the image is large enough.

**Comment by Andersama** [comment]
I've run into something strange, when using mouse inputs left clicks and scroll wheeling seem to be properly handled in the right window, but right clicks are falling through to the first window rendered?

**Comment by ocornut** [comment]
Those are two questions unrelated to the original question and need to be asked in a new issue with the same amount of care and details as any new issues, otherwise 90% of the time we don’t have enough data to answer you correctly.

Read FAQ entry about drawing textures and using texture coordinates.

**Comment by Andersama** [comment]
Ok, well for context then although I've got it solved now. I had forgotten to limit right-clicking conditions to the canvas that was being hovered, so while the initial right mouse down would appear to work because the number of times it was processed wouldn't matter the release would be processed by the first window rendered.
