### ISSUE TITLE
Window with NoBackground flag looses its see-through-ness when docked (Docking, SDL2)

### ISSUE THREAD

**Issue by Electronicks** [ocornut/imgui#6175]
Version: 1.89.4 WIP
Branch: Docking

Windows SDL2

Back-ends: imgui_impl_sdlrenderer.cpp
Compiler: msvc (v143 aka VS2022)
Operating System: Windows 10

When using dockable windows, if the window is created with Begin("Name", ..., **ImGuiWindowFlags_NoBackground** ) it will be possible to see what is being rendered in the background (with SDL2 in my case). But If I were to dock that window in tha main viewport, all of a sudden the background returns and the rendered image is obstructed. See screenshots provided. Notice how when the window is undocked, the picture is clearly visible, but is still overwritten by the menu bar items. The bright red background is just to expose the issue.

An undocked window has no background
![undocked](https://user-images.githubusercontent.com/2488182/219763194-5b026e10-6525-41ee-9bee-3555ac4bc125.png)

A docked window has a background
![docked](https://user-images.githubusercontent.com/2488182/219763190-fbe9e172-7df0-4489-9988-16eaa6dac362.png)

You can currently find my source code at this location:
[https://github.com/Electronicks/JoyShockMapper/blob/dimgui/JoyShockMapper/src/dimgui/Application.cpp](https://github.com/Electronicks/JoyShockMapper/blob/dimgui/JoyShockMapper/src/dimgui/Application.cpp)

This behaviour is reproducible in the demo example for docking by adding the flag ImGuiWindowFlags_NoBackground to the Begin("Hello, world!") function call . I have not tried with other backends.
Is this a bug or intended behaviour? Can I have a docked window be transparent?

Thanks for looking into this.

**Comment by Electronicks** [comment]
As a workaround, I can use the following since all my windows will be transparent,:

style.Colors[ImGuiCol_WindowBg].w = 0; // Window background has 0% alpha

But I believe there is still a misbehaviour

**Comment by ocornut** [comment]
It seems to work here:
![image](https://user-images.githubusercontent.com/8225057/220600835-cfefee80-ace4-49c6-9f0b-4d6a13efddaa.png)

I think your issue is that the window hosting your dockspace has a non-transparent background.

You can change the WindowBG value for that window:

```cpp
PushStyleColor(ImGuiCol_WindowBg, ImVec4(0,0,0,0));
DockSpaceOverViewport(); // call Begin()
PopStyleColor();
```

**Comment by Electronicks** [comment]
That does work. Also looks like a better solution than my workaround since the style edit only applis to that window. Thanks!
