### ISSUE TITLE
Is it possible to use ImGui::InputText without a buffer?

### ISSUE THREAD

**Issue by DeadNIIctoVII** [ocornut/imgui#6180]
Is it possible to use ImGui::InputText without a buffer?

For example, if I need to create around 100 ImGui::InputText, and store the InputText in a buffer (Because I want to put the InputText in a buffer in that local scope, put the buffer in a function that I created, just for a context)

Like: ImGui::InputText("Label", "NoBuffer")
const char* LocalBuffer = whatever is placed in the InputText
FunctionWithString(Buffer)

I was also a bit confused, maybe I can also do it by ID, I'm not sure
eg: ImGui::InputText("Label", "##1")

(Sorry if this is a stupid question, I'm just learning how to use IMGUi, by the way, is there anywhere else I can study IMGUi? (with screenshots of what a function looks like, for example IMGUi::BeginCombo())

**Comment by DeadNIIctoVII** [comment]
> 



> For example, if I need to create around 100 ImGui::InputText
Would I have to create 100 Buffers?

**Comment by DeadNIIctoVII** [comment]
> For example, if I need to create around 100 ImGui::InputText

Would I have to create 100 Buffers?

**Comment by DeadNIIctoVII** [comment]
Maybe it got a little confusing, basically I just want to use ImGui::InputText without having to create global Buffers (Or during that .cpp file)
And the user only needs to insert the text, and if possible, would there be any way to put what was inserted there in a function that needs a const char?

(that's why I talked about putting the InputText in a buffer :VV but my focus is using the InputText specifically, without buffers)

**Comment by RegiSimkus** [comment]
> > For example, if I need to create around 100 ImGui::InputText
> 
> Would I have to create 100 Buffers?

I believe you'll have to if you want to store 100 unique inputs. May be best to create a 2d array to keep things tidy.

**Comment by ocornut** [comment]
> is there anywhere else I can study IMGUi? (with screenshots of what a function looks like, for example IMGUi::BeginCombo())

You can run and study the demo. 
also see https://pthom.github.io/imgui_manual_online/

As for your main question, dear imgui is designed to not hold on user data. There is actually a weird design side-effect with InputText() that should make it possible but I think it is safer and saner to pretend it is not possible.

I believe your underlying question isn’t as much related to dear imgui but a more general question about organizing your data in a program.
