### ISSUE TITLE
Moving Native Window From ImGui Element

### ISSUE THREAD

**Issue by pegvin** [ocornut/imgui#6182]
**Version/Branch of Dear ImGui:**

Version: v1.89.1
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_sdlrenderer.cpp
Compiler: GCC + G++
Operating System: Manjaro Linux

**My Issue/Question:**
I have a simple imgui app and i wanted to know if i can move the window by moving a imgui element (MainMenuBar in this case)

this is what my UI looks like

![image](https://user-images.githubusercontent.com/75035219/220109871-e673f52c-51a8-4d0e-878c-45bac4c20a67.png)

and i want to be able to move around the window by grabbing the empty area in MainMenuBar, is there a API or a resource or anything for this?

also thanks alot to ocornut and other contributors for this beautiful library.

**Comment by ocornut** [comment]
Nice style!

The Win32 native way would be to report a section as non-client area (HTCAPTION) see #6162 I don't know if there is a SDL equivalent or if you could hook the message handler for that purpose.

More far fetched but: I believe we could eventually take advantage of the [multi-viewports](https://github.com/ocornut/imgui/wiki/Multi-Viewports) setup in `docking` branch to provide a similar feature. Technically we already do this for the title bar of secondary viewports and we could/should probably rework the system to make it easier to do this in more custom ways. Currently this uses SetWindowPos calls but the feature could also perfectly use HTCAPTION-like features on other systems that needs something like that (e.g. SetWindowPos-ish calls won't work in Wayland).

**Comment by pegvin** [comment]
your welcome!

do i close this issue, or wait till it's implemented or something?

**Comment by ocornut** [comment]
Always happy to close issues! unless you want to discuss things in more details here.
I'll tag this issue and others if we make progress on this. There are definitively planed stuff ahead.

**Comment by pegvin** [comment]
i believe you guys will do it.
thanks for such a beautiful library.
