### ISSUE TITLE
imgui_impl_sdl.h and imgui_impl_sdlrenderer.h DO NOT WORK with the Ubuntu package structure

### ISSUE THREAD

**Issue by mym4n** [ocornut/imgui#6184]
imgui_impl_sdl.h and imgui_impl_sdlrenderer.h include imgui.h with "imgui.h"
![image](https://user-images.githubusercontent.com/87930611/220512779-db41b2c1-0339-4697-8770-7afd1df5a4ca.png)
![image](https://user-images.githubusercontent.com/87930611/220512825-9c35e101-ebf2-49db-9968-a9608a1f9702.png)
this causes an error because imgui.h is in the parent directory.

**Comment by ocornut** [comment]
Building code with dear imgui requires those files (imgui.h etc) to be in include paths. If they are not your build setup is at fault.
