### ISSUE TITLE
Imgui widget after table not visible in frame without scrolling

### ISSUE THREAD

**Issue by vikram-lodhi** [ocornut/imgui#6185]
```
auto TradingApp::minimalWorkingCode() -> void {
	static ImGuiTableFlags Flags = ImGuiTableFlags_RowBg
								   | ImGuiTableFlags_Resizable
								   | ImGuiTableFlags_ScrollX
								   | ImGuiTableFlags_ScrollY
								   | ImGuiTableFlags_Borders
								   | ImGuiTableFlags_Reorderable
								   | ImGuiTableFlags_NoHostExtendX
								   | ImGuiTableFlags_NoHostExtendY;
	if (ImGui::Begin("WindowTitle")) {
		ImGui::AlignTextToFramePadding();
		ImGui::Text("Begin");
		ImGui::SameLine();
		for (int i = 0; i < 5; ++i) {
			ImGui::Button(std::string("button").append(std::to_string(i)).data());
			ImGui::SameLine();
		}
		ImGui::Text("End");
		ImGui::Separator();

		if (ImGui::BeginChild("Separate scolling")) {
			if (ImGui::BeginTable("MainTable", 5, Flags)) {
				ImGui::EndTable();
			}
		}
		ImGui::EndChild();
		ImGui::Text("make text visible in window without scrolling");
	}
	ImGui::End();
}
```

![image](https://user-images.githubusercontent.com/123872971/220520724-1211d318-dcd8-4ce2-afca-1aad5dc1285d.png)

As frame/window drawn text is push to bottom with scroll bar..

**Comment by ocornut** [comment]
Your call to BeginChild() with unspecified size will use the leftover remaining width and height in the parent client area, so after your child submission you are below.

Similarly, a call to BeginTable() with scrolling enabled creates its own child and with unspecified size would behave the same. (Here it doesn’t matter as your table is inside the child so it takes all the child space).

What you likely want to do is to make the child less tall by using eg ImVec2(-FLT_MIN, -padding) where padding is amount of space to leave below the child. Check the Console and Log examples, one of them does the same thing.
