### ISSUE TITLE
ImGuiIO::MouseWheelDelta

### ISSUE THREAD

**Issue by Pagghiu** [ocornut/imgui#619]
It would be useful to have an io.MouseWheelDelta on the same style as io.MouseDelta.
Of course it can be tracked on user side but for consistency it would be great for it to be together with all the other delta(s) kept by imgui.

I am adding this myself on imgui.cpp and .h but it would be great if this addition goes into the master so I don't have to add it every time I update ;)

**Comment by Pagghiu** [comment]
oops I've just discovered that MouseWheel is already a delta...so I guess this becomes "renaming" MouseWheel to MouseWheelDelta for consistency when we're allowed to break the API ;)

**Comment by ocornut** [comment]
I'd assume mouse wheel values always come in as event/delta, as a wheel has no upper/lower bound nobody uses an absolute value.

Added a note for renaming candidate in my 2.0 text file :)
Closing ok?
