### ISSUE TITLE
Is the cursor in the title bar of the tree node?

### ISSUE THREAD

**Issue by artemko22** [ocornut/imgui#6190]
**Version/Branch of Dear ImGui:**

Version: v1.89.3 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler:  IDE - Visual Studio 22
Operating System: Windows 10

**My Issue/Question:**

How do I find out if the mouse cursor is in the header row of a tree node

**Screenshots/Video**

![Безымянный](https://user-images.githubusercontent.com/81826990/220991256-7f837399-53f4-4758-822c-44f1cf5c231e.png)

**Comment by ocornut** [comment]
You are asking two different questions between the initial message and the edited message.

Generally you can use IsItemHovered() after any item.
If you use it after a Begin() call it returns the hovered state of the title bar.

**Comment by artemko22** [comment]
@ocornut, I apologize, in the first two changes I asked the wrong question

**Comment by ocornut** [comment]
I already answered it.

```cpp
bool is_open = TreeNode(…);
bool is_hovered = IsItemHovered();
if (is_open)
{
    // child contents
    TreePop();
}
```

**Comment by artemko22** [comment]
Thank you for answering my question

**Comment by ocornut** [comment]
Also see "Demo>Widgets>Querying Item Status" for more demo and details about various available state.
