### ISSUE TITLE
Reading the value(s) of ANY unknown key(s) pressed.

### ISSUE THREAD

**Issue by lailoken** [ocornut/imgui#6191]
Regarding the new keyboard event handling:
  https://github.com/ocornut/imgui/issues/4921

How do I go about finding out which (any/unknown) key is pressed? (For cases where I want to write code to configure a shortcut/hotkey system etc.)

Currently I need to call IsKeyPressed() for every single possible ImGuiKey enum. yet I don't know when those will change either?
I see the ImGui Manual sample conveniently loops over io.KeysData and uses enums like ImGuiKey_KeysData_OFFSET and ImGuiKey_COUNT, yet these (seem to be) marked as "[internal]", so I'm not comfortable using these (but am currently as it makes the most sense)

What is the proper/correct/efficient way to go about this?

(It may also help if there was function I can call that would just return a bool if there was any key pressed, may make a big different to my CPU load if such info was available...)

**Comment by GamingMinds-DanielC** [comment]
> Currently I need to call IsKeyPressed() for every single possible ImGuiKey enum. yet I don't know when those will change either?

The inputs are updated in `ImGui::NewFrame()`, so whenever you call that you can retrieve keys that are valid for the entire frame.

> I see the ImGui Manual sample conveniently loops over io.KeysData and uses enums like ImGuiKey_KeysData_OFFSET and ImGuiKey_COUNT, yet these (seem to be) marked as "[internal]", so I'm not comfortable using these (but am currently as it makes the most sense)

If you don't need legacy keys, you can iterate from `ImGuiKey_NamedKey_BEGIN` to `ImGuiKey_NamedKey_END`. Still technically internal though.

> (It may also help if there was function I can call that would just return a bool if there was any key pressed, may make a big different to my CPU load if such info was available...)

If you iterate over the keys once per frame, you can count them or set a flag to use during the frame. Or even memorize them in a list. Unless there is something really wrong with your frame handling, there shouldn't be any significant CPU load from this. Here is an example helper function (untested) that returns a (constant reference to a) vector of pressed keys, updated only when the frame changes (so no extra iterations when you use it multiple times) and a shortcut to see if there are any keys pressed:

```c++
const std::vector<ImGuiKey>& GetPressedKeys()
{
	static std::vector<ImGuiKey> pressedKeys;
	static int                   frameCount = -1;

	int newFrameCount = ImGui::GetFrameCount();
	if ( frameCount != newFrameCount )
	{
		frameCount = newFrameCount;

		pressedKeys.clear();
		for ( int key = ImGuiKey_NamedKey_BEGIN; key < ImGuiKey_NamedKey_END; ++key )
			if ( ImGui::IsKeyPressed( (ImGuiKey)key ) )
				pressedKeys.push_back( (ImGuiKey)key );
	}

	return pressedKeys;
}

bool IsAnyKeyPressed()
{
	return !GetPressedKeys().empty();
}
```

If you use helper functions like these, you should maybe separate them from your UI logic, f.e. put them in a namespace `ImGuiEx` where you collect everything that is general purpose or uses internals. Makes it easier to adjust if there are ever any API changes.

**Comment by ocornut** [comment]
Indeed, this use case is misdocumented. 
As replied you can use ImGuiKey_NamedKey_BEGIN / ImGuiKey_NamedKey_END for this purpose.
This won't break nor change.

(I however would not recommend using ImGuiKey_KeysData_SIZE /ImGuiKey_KeysData_OFFSET).

> (It may also help if there was function I can call that would just return a bool if there was any key pressed, may make a big different to my CPU load if such info was available...)

It won't make a difference. Iterating all keys will approximately bring 160x16 = 2240 bytes of cold data into L1 cache which is in the context of a whole frame is negligible. Especially so as your use case is a modal key mapper.

> !GetPressedKeys().empty();

There's no need to need to build an entire vector if you only call `.empty()` on it:

```cpp
bool IsAnyKeyPressed()
{
    for ( int key = ImGuiKey_NamedKey_BEGIN; key < ImGuiKey_NamedKey_END; ++key )
        if ( ImGui::IsKeyPressed( (ImGuiKey)key ) )
            return true;
    return false;
}
```

**Comment by GamingMinds-DanielC** [comment]
> There's no need to need to build an entire vector if you only call `.empty()` on it:

Sure, that would be a waste if that is all that's done. But if the very next step in case of pressed keys is to iterate over the pressed keys, might as well build it early and use the vector (or any other container) that is needed anyway. And if there are no pressed keys, a single `clear()` (not even a deallocation, just an internal reset of the size) per frame is all there is.

**Comment by ocornut** [comment]
> But if the very next step in case of pressed keys is to iterate over the pressed keys, might as well build it early and use the vector (or any other container) that is needed anyway.

But that data is already available via `ImGui::IsKeyPressed()` it also accesses an array.

> And if there are no pressed keys, a single clear() (not even a deallocation, just an internal reset of the size) per frame is all there is.

Yes I noted you used an amortized array here 👍

**Comment by ocornut** [comment]
I pushed a few changes and comments to increase the discoverability of this:
bfce7750b168b5a857b4379596236dda7b58bd39

Closing as answered.

**Comment by GamingMinds-DanielC** [comment]
> But that data is already available via `ImGui::IsKeyPressed()` it also accesses an array.

A very sparse array, so it could make a difference if iterated often in a frame. But then again, pressed keys should only be relevant to selected/active/hovered items/windows anyway, so they shouldn't need to be iterated often. A cached condensed array might be convenient, but if it has an impact on performance, that's a good indicator that something in the UI handling is very wrong.

> Yes I noted you used an amortized array here 👍

Always aiming for zero allocations/deallocations on a normal frame. 😄

**Comment by lailoken** [comment]
Thanks @GamingMinds-DanielC , I'll use your suggestion and sample code, I may change it slightly to separate mods from keys (I find that Super is left out from io.KeyMods yet it is present in the KeysData array)

Thanks @ocornut , the clearer example code will help!

My main concern about using BEGIN and END is addressed.

Yes, I primarily use this for key config, my actual activation code would be driven by a cached subset (so relatively small at the moment) where I can call IsKeyPressed(). But I may start adding more and more hotkey options in future. But I think you're correct, my concern about performance was premature.
