### ISSUE TITLE
Any Talks/Resources On Styling V2?

### ISSUE THREAD

**Issue by pegvin** [ocornut/imgui#6192]
**Version/Branch of Dear ImGui:**

Version: 1.89.2
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl.cpp + imgui_impl_sdlrenderer.cpp
Compiler: GCC + G++
Operating System: Manjaro Linux

**My Issue/Question:**
imgui is a great library but still lacks various features in styling, the main feature i'm concerned about is changing text color on hover of a button/menu item or anything with button like behavior.

a issue was raised by a fellow user ["Change Button Text color on hovering"](https://github.com/ocornut/imgui/issues/5126), and a comment stated:

> Yes Styling v2 will include it.

but i can't find any place where styling v2 is being discussed or is being developed, is there something am i missing?

**Comment by ocornut** [comment]
There are no particular place where this is being discussed. I have checklists and notes and experiments but it isn’t being properly in development yet.

**Comment by pegvin** [comment]
then i'm leaving this issue open as a reminder and maybe even a tracker.

**Comment by ocornut** [comment]
There is no need and that isn’t desirable. When Styling V2 appears it’ll be very evident. I also regularly tags old issues when related progress is made.
