### ISSUE TITLE
Getting height of the wrapped text

### ISSUE THREAD

**Issue by neoedmund** [ocornut/imgui#6193]
**Version/Branch of Dear ImGui:**

Version: HEAD
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: any
Compiler: gcc
Operating System: Linux Debian

**My Issue/Question:**

When I want to get the height of the wrapped text after AddText()
I found no way but to make a change as: (tested Okay)
https://github.com/neoedmund/imgui/commit/4ccb09e8688ee34f5f138e1bf0f694c2fba32c27

Is there any other way without change, or should I make a pull request or keep cool?

**Screenshots/Video**

**Standalone, minimal, complete and verifiable example:** 
```
return ImGui :: GetForegroundDrawList ( ) -> AddText ( NULL , 0.0f ,
		ImVec2 ( x , y ) , ImColor ( c [ 0 ] * 255 , c [ 1 ] * 255 , c [ 2 ] * 255 , 255.0f ) ,
		text , text + str . length ( ) , warpWidth , NULL ) ;
```

**Comment by PathogenDavid** [comment]
You should use `CalcTextSize` to explicitly calculate the height, which is [what `TextEx` does](https://github.com/ocornut/imgui/blob/2496b973f931186a43c723eda57baa092df6be61/imgui_widgets.cpp#L171-L181) to calculate its item size.

Your change returns the height as affected (roughly) by the clipping rectangle. (Even though you didn't pass your own clipping rectangle there's always one implicitly associated with the draw list.)

That might be OK for your purposes, but it'd be incorrect for others and would be confusing—so I don't think a PR would be appropriate.

------------

As an aside, your `ImColor` constructor is incorrect. The `float` constructor already expects values within `0..1`.

**Comment by neoedmund** [comment]
Thank you.  `CalcTextSize` and `ImColor` got it.

**Comment by ocornut** [comment]
Note that is is IMHO an issue with the existing API that you need to often need to compute that size twice. Among other sizes, the size computed for layout would be of great use if passed to text drawing function, in order to allow early clipping when finishing above the clip min y line.

The new text functions I am working on should allow this sorts of things.

**Comment by marcrleonard** [comment]
> The new text functions I am working on should allow this sorts of things.

Any idea when this new feature will be in?
