### ISSUE TITLE
Need Font additional information for monospaced / proportional / tabular handling.

### ISSUE THREAD

**Issue by lailoken** [ocornut/imgui#6196]
_Version: v1.89.4 WIP
Branch: docking
Backends: Windows / emscripten_

I'm using fonts in a tabular way (financial data), I also allow for dynamic changing and loading of fonts (I have this all working perfectly). I allow for users to pick a font but would like to limit the choice of font under certain conditions to be based on some internal font metrics such as monospace (and possibly sans-serif).

My main requirement from ImGui is to find whether a font is monospaced (This I can read from the TTF `OS/2` table's `panose` field - basically from `bProportion` == 9).

Ideally all I need to know is whether the numeric glyphs are tabular (But I'm not even sure if this is recorded in fonts).

Currently I have some values hard-coded for a select list of fonts, or I can measure if there is a difference between 'l' and 'm', but these may not be great solutions...

PS: These are the low hanging fruits, what would be the ideal is being able to select the (sometimes available variant) alternate tabular numeric glyph sets in certain fonts (alternate glyphs in general could be very useful). But I'm sure not many people even know these exist or need them, and the work here is not trivial. (Just mentioning it)

**Comment by pegvin** [comment]
I have some friends who are actively developing a text editor, I had raised the same issue of how do I detect whether font is monospace, sans-serif or serif and they said there's no certain way.

If you're just working with ASCII, I'd say try calculating the width of each glyph and see if they match.

Or you can just calculate the width of `i` and `m` that works too.

`CalcTextSize` should work fine.

**Comment by lailoken** [comment]
Yeah, will be doing that for now (a simple measure).

As for your friends, let them know they should look at the `os2` table in the `sfamilyclass` property. The lower byte when having values 1,2,3,4,5,7 are likely serif, 8 is sans-serif, 9 I would see as fantasy, and 10 cursive. Failing a mapping here (if there is no value), You can try an infer it from the `panose` property on `os2` table. That's a little bit more complex, just need to read the docs. Failing all these, you can also do a simple match on the font name... this is only a last resort.

Generally I found this method to match about 99% of the fonts I threw at it to the correct html generic font family.

**Comment by pegvin** [comment]
then i probably miss-understood them, i'll share it with them!

**Comment by lailoken** [comment]
No, I can see where they are coming from, I too initially thought it impossible. I spent years writing a low-level TTF font and PDF API. After a lot of reading I came up with these pointers. They don't ALWAYS work, and I still had an option for user override. But generally it is only for poorly fleshed-out fonts.

**Comment by lailoken** [comment]
> You can read it what more do you need?

The internal font API in ImGui has access to these tables/values whereas I did not, I wanted ImGui to expose them.
But the measurement of the numeric glyphs will work for me! (This works for my case since I load fonts twice already)

Currently I synthesize tabular numerics (where only the numerics are forced monospaced) using the GlyphMinAdvanceX+GlyphMaxAdvanceX trick on the numeric digits only. However this does not look great when rendering the more narrow glyphs like "1" and ".".

It is working at least, but the ideal would have been to use the internal font `GSUB` table to find the tabular numerics glyph alternates and use those instead. The thing is, that may be too much work if the library which ImGui uses does not support this already...

For reference:

[Numeric - tabular vs proportional, oldstyle vs lining](https://fonts.google.com/knowledge/introducing_type/understanding_numerals)

[Glyph alternates via GSUB table](https://learn.microsoft.com/en-us/typography/opentype/spec/gsub#EX2
)

**Comment by ocornut** [comment]
> The internal font API in ImGui has access to these tables/values whereas I did not, I wanted ImGui to expose them.

If you mean data in imgui_internal.h or field marked internal in imgui.h you can use it, but I don't think any meaningful font data is in there.

Otherwise, we use stb_truetype and freetype for loading and rasterization, tho but I don't expect us to burden ourselves with supporting/wrapping such data or anything more than we already need for our purpose.

You may use the stb_truetype.h library which we embed to access that data yourself.
