### ISSUE TITLE
Windows with (0,0) size should fit content

### ISSUE THREAD

**Issue by ebriney** [ocornut/imgui#62]
It's strange to get a window without any content with null size.

And I didn't find any method to adjust window size to fit his content !

**Comment by ocornut** [comment]
FYI I reorganised the Begin() functions which was full of traps (subtle ordering dependencies). It should be better and healthier now but there is the possibility that I've created bugs or changes of behavior related to window size. Let me know if you notice anything unusual.

The changes are spread over many commits ending with this
https://github.com/ocornut/imgui/commit/d84b5737a6526a6ecce40ed8d1fc35d0f5a0a9a6
(spreading them should make it easier to bissect for bugs shall we need to)
