### ISSUE TITLE
ImGuiTextFilter hints, flags

### ISSUE THREAD

**Issue by phraktle** [ocornut/imgui#6206]
**Version/Branch of Dear ImGui:**

Version: 1.86

**My Issue/Question:**

It would be nice to be able to control the rendering of `ImGuiTextFilter` a bit better, such as providing a hint for the input field or set flags.

**Comment by ocornut** [comment]
Please be more specific. Why do you want to set flags for?

Note you can use a filter instance and draw the InputText() yourself using its buffer.

**Comment by phraktle** [comment]
The primary need is to show the text field with a hint (instead of the label next to it).

An additional complication is that I'm using the [imgui-java](https://github.com/SpaiR/imgui-java) bindings, which doesn't expose the internal buffer  – if that's the way to go, I guess I could file that as an improvement request there.

**Comment by ocornut** [comment]
Yes I think bindings need to provide access to this.

**Comment by phraktle** [comment]
Ok thanks, closing this.

**Comment by ocornut** [comment]
A `DrawWithHint()` function was now added.

I have also obsoleted the `, float width` parameters of `Draw()` to make API consistent and favor using `SetNextItemWidth()`.

```cpp
IMGUI_API bool      Draw(const char* label = "Filter");
IMGUI_API bool      DrawWithHint(const char* label = "Filter", const char* hint = "incl -excl");
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
inline bool         Draw(const char* label, float width)  { if (width != 0.0f) ImGui::SetNextItemWidth(width); return Draw(label); }
#endif
```

```
- ImGuiTextFilter:
  - (Breaking) removed `float width` parameter of `Draw(const char* filter, float width)`:
     prefer using `SetNextItemWidth(float)` which is standard. Kept inline redirection function.
  - Added `DrawWithHint()` function. (#6206, #6395, #6447)
  - Added a "incl,-excl" hint by default when the search field is empty. (#6206, #6395, #6447)
```

Will push more improvements to `ImGuiTextFilter` soon.
