### ISSUE TITLE
WantCaptureMouse behavior

### ISSUE THREAD

**Issue by pdoane** [ocornut/imgui#621]
This may be a misunderstanding of how WantCaptureMouse is intended to work, but following the documentation I assume that I should not be passing mouse click events to the application when this value is true.

If I click on a text input widget making it active, the value of WantCaptureMouse is always true even when the mouse is no longer over any ImGui window.  I would expect that in one click I can deactivate the text input widget and pass through to the application.

If this line is modified:

`g.IO.WantCaptureMouse = (mouse_avail_to_imgui && (g.HoveredWindow != NULL || mouse_any_down)) || (g.ActiveId != 0) || (!g.OpenedPopupStack.empty());`

To not include g.ActiveId then the behavior is working as I am expecting but that may have other unintended consequences.

**Comment by ocornut** [comment]
Hello,

You are right - however that behaviour would need to depend on the widget. It is this test that makes the mouse captured when holding mouse down on a SliderFloat or DragFloat while you move outside the imgui window.
We'd need to introduce say, a `g.ActiveIdCaptureMouse` and have each widget code set that accordingly. Corresponding flag for Keyboard also desirable.

Replacing `(g.ActiveId != 0)` with `(g.ActiveId != 0 && !g.ActiveIdAllowOverlap)` will get you more close-to-correct behavior here but it isn't totally the correct test to do. It is probably not harmful to use that as a temporary fix.

-Omar

**Comment by pdoane** [comment]
It may be fine without the g.ActiveId.  The SliderFloat/DragFloats continue to work outside of imgui windows because of the mouse_any_down check.

**Comment by ocornut** [comment]
I would have to review other widgets and see if that test always makes sense, aka mouse_any_down is a sufficient and correct indicator that need to keep capturing. May be up to the widget to decide based on its behavior.

**Comment by ocornut** [comment]
@pdoane Merging this now, as you suggested it. It also seem to behave as expected in the Navigation branch. Until one hypothetical/edge case is reported there's no point is not trying this.

Out of curiosity: have you been already using this patch in your local codebase since you posted this? (If so, were you using the master or Navigation branch?)

**Comment by pdoane** [comment]
Yes we have been using that based on the master branch and haven't noticed any problems.
