### ISSUE TITLE
Getting Errors when building for SerenityOS

### ISSUE THREAD

**Issue by scaredcode** [ocornut/imgui#6214]
**Version/Branch of Dear ImGui:**

Version: lastet from github
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl2 + imgui_impl_opengl3
Compiler: x86_64-pc-serenity-g++
Operating System: ![SerenityOS](https://github.com/SerenityOS/serenity)

**My Issue/Question:**

Errors when building, OpenGL loader errors

**Screenshots/Video**

![errors](https://i.ibb.co/VVmJSKf/image.png)

```
Code: default example sdl2+opengl3

**Comment by scaredcode** [comment]
when i use sdlrenderer, window not creating

![picture](https://i.ibb.co/t3tYskJ/image.png)

**Comment by drunderscore** [comment]
Disregarding your issue entirely as you certainly don't show remotely enough information -- I doubt SerenityOS would even be able to render ImGui with OpenGL 3, seeing as it's only barely OpenGL 1.3 compatible.

This is certainly no ImGui issue, this is something for you to debug and work towards yourself.
