### ISSUE TITLE
Actual split size of DockBuilderSplitNode is inconsistent. Each running can come with a different size.

### ISSUE THREAD

**Issue by WeakKnight** [ocornut/imgui#6217]
**Version/Branch of Dear ImGui:**

Version: v1.89.4
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: GLFW + OpenGL 3
Compiler: MSVC
Operating System: Windows

**My Issue/Question:**

I use the following code to create a layout with two equally-sized docker node, 

``` cpp
            ImGui::DockBuilderRemoveNode(mainDockSpaceId);
            ImGui::DockBuilderAddNode(mainDockSpaceId, ImGuiDockNodeFlags_DockSpace);
            ImGui::DockBuilderSetNodeSize(mainDockSpaceId, dockspace_size);

            ImGuiID dock_id_left;
            ImGuiID dock_id_right = ImGui::DockBuilderSplitNode(mainDockSpaceId, ImGuiDir_Right, 0.5f, NULL, &dock_id_left);

            ImGui::DockBuilderDockWindow("AAA", dock_id_left);
            ImGui::DockBuilderDockWindow("BBB", dock_id_right);
```

but the actual split size of DockBuilderSplitNode is inconsistent. Each running can come with a different size.

**Screenshots/Video:**

The First Run:
<img width="651" alt="企业微信截图_16778460183691" src="https://user-images.githubusercontent.com/12985760/222723840-d68a0df3-dcfe-4266-8093-25742fc9fab8.png">
The Second:
<img width="651" alt="企业微信截图_16778460279144" src="https://user-images.githubusercontent.com/12985760/222723878-cea96e13-d252-4ddc-8892-6b3ce1b2bb7e.png">
The Third:
<img width="651" alt="企业微信截图_16778460404245" src="https://user-images.githubusercontent.com/12985760/222723918-c9e384c1-f6bb-41e1-bc46-db04e6394079.png">

**Standalone, minimal, complete and verifiable example:**

To reproduce this bug, paste the following code between `ImGui::NewFrame();` and `ImGui::Render();`

``` cpp
        static ImGuiDockNodeFlags dockspace_flags = ImGuiDockNodeFlags_None | ImGuiDockNodeFlags_NoCloseButton;
        static bool dockspaceOpen = true;

        ImGuiWindowFlags window_flags = ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoDocking | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoNavFocus | ImGuiWindowFlags_NoMove;

        ImGuiViewport* viewport = ImGui::GetMainViewport();
        ImGui::SetNextWindowPos(viewport->Pos);
        ImGui::SetNextWindowSize(viewport->Size);
        ImGui::SetNextWindowViewport(viewport->ID);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
        ImGui::Begin("MainWindow", &dockspaceOpen, window_flags);
        ImGui::PopStyleVar();

        ImGuiID mainDockSpaceId = ImGui::GetID("MainDockSpace");
        ImGui::DockSpace(mainDockSpaceId, ImVec2(0.0f, 0.0f), dockspace_flags);
        const ImVec2 dockspace_size = ImGui::GetContentRegionMaxAbs();

        ImGui::Begin("AAA", nullptr);
        {

        }
        ImGui::End();

        ImGui::Begin("BBB", nullptr);
        {

        }
        ImGui::End();

        static bool sFirstFrame = true;
        if (sFirstFrame)
        {
            sFirstFrame = false;

            ImGui::DockBuilderRemoveNode(mainDockSpaceId);
            ImGui::DockBuilderAddNode(mainDockSpaceId, ImGuiDockNodeFlags_DockSpace);
            ImGui::DockBuilderSetNodeSize(mainDockSpaceId, dockspace_size);

            ImGuiID dock_id_left;
            ImGuiID dock_id_right = ImGui::DockBuilderSplitNode(mainDockSpaceId, ImGuiDir_Right, 0.5f, NULL, &dock_id_left);

            ImGui::DockBuilderDockWindow("AAA", dock_id_left);
            ImGui::DockBuilderDockWindow("BBB", dock_id_right);

            ImGui::DockBuilderFinish(mainDockSpaceId);
        }

        ImGui::End();
```

**Comment by ocornut** [comment]
Hello,
Thanks for submitting a repro.

(1) Your issue is your misuse of this function:
```cpp
const ImVec2 dockspace_size = ImGui::GetContentRegionMaxAbs();
```
**This is absolute coordinate of the bottom-right of your window.**
When viewport are enabled, your coordinate systems matches your OS coordinates. 
So depending where your host/platform window appears, that value will differ.

You can obtain the correct size with:
```cpp
const ImVec2 dockspace_size = ImGui::GetContentRegionAvail();
ImGui::DockSpace(mainDockSpaceId, ImVec2(0.0f, 0.0f), dockspace_flags);
```

In theory you should be able to also do this but there is a bug querying this which I am going to look into fixing:
```cpp
ImGui::DockSpace(mainDockSpaceId, ImVec2(0.0f, 0.0f), dockspace_flags);
const ImVec2 dockspace_size = ImGui::GetItemRectSize();
```

This will get you an evenly split 50/50% thing.

(2)
HOWEVER.

Calling `ImGui::DockBuilderAddNode(mainDockSpaceId, ImGuiDockNodeFlags_DockSpace);` will create one "central node" which has the property of using remaining space, in this case after the split the left side will have the CentralNode flag and things won't say 50/50 if you resize.

If you instead use `ImGui::DockBuilderAddNode(mainDockSpaceId, ImGuiDockNodeFlags_None);` it should be OK.

That "central node" behavior is something that has been discussed in many issues and should be eventually redesigned.

**Comment by WeakKnight** [comment]
Thanks for solution! My problem got perfectly solved!
![image](https://user-images.githubusercontent.com/12985760/227092833-192c30b1-2b00-4e44-9976-809e890e363a.png)
