### ISSUE TITLE
How do I set an imgui window as the central node in a dockspace?

### ISSUE THREAD

**Issue by techie-guy** [ocornut/imgui#6219]
**Version/Branch of Dear ImGui:**
Branch: docking
Version: Latest (Cloned from Github)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw3.cpp + imgui_impl_opengl3.cpp
Compiler: MSYS2 Clang
Operating System: Windows 10

**My Issue/Question:**
How do I set an imgui window as the central node in a dockspace and dock it as if it were dragged and put into the center (see the second screenshot below)?

I have 2 windows, Test 1 and Test 2.
How do I make the Test 2 window be the central node?

**Screenshots/Video**
Expected Output
![image](https://user-images.githubusercontent.com/79499324/222800202-50fe1fac-72aa-4c3f-bb12-d078da46d140.png)

Dragging the window and docking it into the center
![image](https://user-images.githubusercontent.com/79499324/222800683-f014a105-b332-44a5-9042-27c6a09c49b1.png)

Current Output (On deleting the imgui.ini file)
![image](https://user-images.githubusercontent.com/79499324/222800786-73fec312-efc8-4ade-9d62-116da8d3dcf5.png)

**Currently, I do it like this**
```cpp
ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());

ImGuiWindowClass test2_flags;
test2_flags.DockNodeFlagsOverrideSet = ImGuiDockNodeFlags_CentralNode;

ImGui::Begin("Test 1");
ImGui::End();

ImGui::SetNextWindowClass(&test2_flags);
ImGui::Begin("Test 2");
ImGui::End();
```

**Comment by ocornut** [comment]
Sorry never got to answer this.
You should be using the DockBuilder api for this.

- `DockBuilderGetNode(your_id) == 0` to tell if the dockspace was already created. Only create if doesn't exist.
- `DockBuilderAddNode(your_id, ImGuiDockNodeFlags_DockSpace);`
- `DockBuilderSplitNode(your_id, ImGuiDir_Left, 0.3f, &left_id, &right_id);`
- `DockBuilderDockWindow("Test 1", left_id)`,  `DockBuilderDockWindow("Test 2", right_id)`.

**EDIT** There's now a bit of a DockBuilder example in https://github.com/ocornut/imgui/wiki/Docking#programmatically-setting-up-docking-layout-dockbuider-api

**Comment by techie-guy** [comment]
Thank You Very Much!
