### ISSUE TITLE
Dear Imgui background 

### ISSUE THREAD

**Issue by Github-user-44** [ocornut/imgui#6228]
Version: v1.89.4 WIP
Branch: Master

Back-ends: DX9
Compiler: Visual Studio 2022
Operating System: Windows 10 pro

So I'm just getting back into Dear Imgui and I'm using the DirectX9 example provided by your GitHub but I can't seem to get rid of the background, I don't mean my menus background Im on about the background the menu displays on.

I had a look through some of the documentation and couldn't find anything to help me, as well as looking at other examples from other users but still can't find anything to help, Thanks.

```
ImGui_ImplDX9_NewFrame();
ImGui_ImplWin32_NewFrame();
ImGui::NewFrame();
{
     ImGui::Begin("Test", nullptr, NULL);
     ImGui::Text("Hello, world!");
     ImGui::End();
 }
 ImGui::EndFrame();
```

![image](https://user-images.githubusercontent.com/96966682/223293460-d44bb672-e643-4b45-b2f9-9794dec59b63.png)
![image](https://user-images.githubusercontent.com/96966682/223293751-67047983-7305-473f-bb2f-20ac1a7aa0f8.png)

I'm trying to get rid of the blue background that the menu renders within.

**Comment by GamingMinds-DanielC** [comment]
The obvious place to start would be `ImVec4 clear_color = ...;`. After all, that is the color the render target is cleared in and happens to be kinda blue.

**Comment by ocornut** [comment]
If there is a window there need to be something displayed in it. I don’t even understand what “getting rid of the background” would mean in this context, what do you replace it with.

I am afraid this isn’t much of a dear imgui question.

**Comment by Github-user-44** [comment]
> If there is a window there need to be something displayed in it. I don’t even understand what “getting rid of the background” would mean in this context, what do you replace it with.
> 
> I am afraid this isn’t much of a dear imgui question.

what I mean by "getting rid of the background" is this, Photo below.

![image](https://user-images.githubusercontent.com/96966682/223535970-7c922dd3-d0ba-4c1d-be34-5c374f10563a.png)
In this photo above the GUI renders on the desktop only

![image](https://user-images.githubusercontent.com/96966682/223293460-d44bb672-e643-4b45-b2f9-9794dec59b63.png)
Whereas this photo has that background on it if that makes sense.

Sorry about the bad context on the Original post

**Comment by ocornut** [comment]
This would be part of multi-viewports feature and is discussed in #3350
In fact, we did some work already to make it possible for the main viewport to be a monitor (used as a fallback), so technically speaking there's no a lots of work left to do to allow running with no main platform window, and I suspect it is doable on user's end. But it's not our priority since it will attract waves of new users and multi-viewports are not solid enough yet. I think we will tackle idle mode and then rewrite viewports v2 to offer this and other things, but until then best to consider that it is not possible.

**Comment by Matrives** [comment]
you found a fix struggling on this
