### ISSUE TITLE
Single line InputText without visible label

### ISSUE THREAD

**Issue by pdoane** [ocornut/imgui#623]
I would like to be able to have a text input box without a label that extends to the full width of the window.  E.g. the Console in the demo application has the label "Input" on the text input line rather than extending across the entire line.

Multiline text boxes support this layout but have other behavior changes that are not desirable.  The internal function InputTextEx appears to be able to support what I'm looking for if I pass in a size_arg to override the 'x' value.

**Comment by ocornut** [comment]
```
PushItemWidth(-1);
InputText("##label", ..);
PopItemWidth();
```

**Comment by pdoane** [comment]
Thanks!

**Comment by 1vanK** [comment]
How to precalc button size?

![изображение](https://github.com/user-attachments/assets/2e9966de-53f2-4036-b486-0a8181211237)

```
        Text("Source file path");
        PushItemWidth(-120); // Need precalc button size
        InputText("##src_font_path", &src_font_path);
        PopItemWidth();
        ImGui::SameLine();
        ImGui::Button("Open");
```

How to precompute Button size?
