### ISSUE TITLE
Can't get multiple viewports to work : blinking bug when a window leaves the main viewport

### ISSUE THREAD

**Issue by Kiloutre** [ocornut/imgui#6235]
Version: **v1.89.4 WIP**
Branch: **docking**
(I should mentionn i have tried getting imgui this very instant, both from vcpkg [docking-experimental] and directly from sources files commit e2cede6542d2d6c83598d4d34dc51de84aeb282f , this issue is present in both for me)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp (i also tried SDL2 + SDL2 and SDL2 + OpenGL3) (all backends libraries and renderer libraries obtained through vcpkg)
Compiler: MSVC 19.35.32215
Operating System: Windows 10 19045.2604

**My Issue/Question:**

Dragging an imgui window outside of the viewport bounds or having any tooltip/popup/anything drawn even one pixel outside of the viewport bounds causes imgui to start blinking incontrollably and events such as mouse and kb to act very sporadically. Dragging back windows in the main viewport will render them invisible (only if they are fully in), but still movable, and they become visible again when exiting the viewport.

**Screenshots/Video**

https://user-images.githubusercontent.com/11745692/224233541-b7059caf-9c80-41ba-bc6d-16276d0601d6.mp4

**Standalone, minimal, complete and verifiable example:**
I have made a small branch in my project with minimal files & code still showing the issue, available here:
https://github.com/Kiloutre/TKMovesets/tree/imgui-tests/TKMovesets2

**Comment by ocornut** [comment]
Does it happen with the vanilla examples, e.g. examples/example_glfw_opengl3/main.cpp ?

It is unclear why your code intentionally does thing different from the example. There's no framebuffer clearing in your code, no viewport setup.

Our example do:
```cpp
        // Rendering
        ImGui::Render();
        int display_w, display_h;
        glfwGetFramebufferSize(window, &display_w, &display_h);
        glViewport(0, 0, display_w, display_h);
        glClearColor(clear_color.x * clear_color.w, clear_color.y * clear_color.w, clear_color.z * clear_color.w, clear_color.w);
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        // Update and Render additional Platform Windows
        // (Platform functions may change the current OpenGL context, so we save/restore it to make it easier to paste this code elsewhere.
        //  For this specific demo app we could also call glfwMakeContextCurrent(window) directly)
        if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
        {
            GLFWwindow* backup_current_context = glfwGetCurrentContext();
            ImGui::UpdatePlatformWindows();
            ImGui::RenderPlatformWindowsDefault();
            glfwMakeContextCurrent(backup_current_context);
        }

        glfwSwapBuffers(window);
```

You are doing:
```cpp
		ImGui::Render();
		if (io.ConfigFlags & ImGuiConfigFlags_DockingEnable) {
			ImGui::UpdatePlatformWindows();
			ImGui::RenderPlatformWindowsDefault();
		}
		ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

		glfwSwapBuffers(window);
```

Which is visibly not the same thing, so please first confirm if you have a problem with the unmodified example.

**Comment by Kiloutre** [comment]
Doing it the example's way fixed it, it seems my problem was mostly a combination of not using glfwMakeContextCurrent() and calling ImGui_ImplOpenGL3_RenderDrawData() after the viewport-specific code instead of before
As for why i did it that way, i was following an apparently bad tutorial that showed things this way, sorry for not looking more closely at the official examples!
