### ISSUE TITLE
Flicker/Content Region Fight Between Image and Scrollbar

### ISSUE THREAD

**Issue by Th-Stehle** [ocornut/imgui#6244]
**Version/Branch of Dear ImGui:**

Version: 1.89.4 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVS 2019
Operating System: Windows 10

**My Issue/Question:**

I want to display an image/texture in a window and make it the same width as the window. I use `GetContentRegionAvail()` to get the current content width so that I can make the image width the same. It works but runs into an ugly flicker once the window wants to display a scroll bar. It seems we are then stuck in a situation where the scroll bar toggles and thus the content width toggles and thus the image width toggles. It's easy to reproduce the problem (see below) and I tried to capture the behaviour in an animated GIF. The framerate of the GIF doesn't do the real problem justice, however. In reality, the flicker matches the framerate of the app.

**Screenshots/Video**

![2023-03-15_09h47_16](https://user-images.githubusercontent.com/127936604/225257569-693d26de-27e2-4aa2-a88d-3e80f3b4674f.gif)

**Standalone, minimal, complete and verifiable example:**
```
ImGui::Begin("Test");
const ImVec2 contentRegion = ImGui::GetContentRegionAvail();
const float size = std::min(static_cast<float>(m_texture.get_width()), contentRegion.x);
ImGui::Image((ImTextureID)(uintptr_t)(m_texture.get_handle().id), {size, size});
ImGui::End();
```

**Comment by Th-Stehle** [comment]
Thanks for the feedback. Is there a way to properly get the space occupied by the scrollbar? Then I could make the image just as wide to not interfere with the potential scrollbar, no matter if it's there or not.

**Comment by GamingMinds-DanielC** [comment]
Yes, you can get the size with `ImGui::GetStyle().ScrollbarSize`. No extra padding that I'm aware of, but just to be sure you should measure available size with and without the scrollbar and check if the difference matches the value.

**Comment by Th-Stehle** [comment]
Yeah, so just subtracting `ImGui::GetStyle().ScrollbarSize` doesn't change the issue, since `GetContentRegionAvail()` still toggles between two sizes. What workes as a workaround for me is using `GetWindowSize()` instead and subtracting some constant from it.

**Comment by ocornut** [comment]
Also see #4539

**Comment by GamingMinds-DanielC** [comment]
> Yeah, so just subtracting `ImGui::GetStyle().ScrollbarSize` doesn't change the issue, since `GetContentRegionAvail()` still toggles between two sizes.

Subtract only if `GetScrollMaxY() == 0.0f`, that should do the trick.

**Comment by Th-Stehle** [comment]
@GamingMinds-DanielC Thanks! This works very well for me as a workaround.
