### ISSUE TITLE
IMGUI_DEFINE_MATH_OPERATORS new behaviour

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#6245]
with Version/Branch of Dear ImGui:1.89.4 master and docking

It is breaking ImGuizmo, imnodes and implot.

If it is not going to change again, some PR should be done in the above repos

**Comment by ocornut** [comment]
I have already made pr for implot and imguizmo and they were merged. Yesterday made a pr for imgui-node-editor. Feel free to make pr for other projects.

**Comment by sonoro1234** [comment]
Sorry for not checking before
