### ISSUE TITLE
`GetCursorScreenPos` always returns the same value

### ISSUE THREAD

**Issue by Gellert5225** [ocornut/imgui#6246]
**Branch of Dear ImGui:**

Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: msvc++
Operating System: Windows

**My Issue/Question:**

I am trying to get the cursor position in screen space using:

```
ImVec2 screen_pos = ImGui::GetCursorScreenPos();

NB_INFO("CursorPos(Screen): {0}, {1}", screen_pos.x, screen_pos.y);
```

But when I move my mouse around, it always prints the same value, unless I move my window, in which case it will print
the viewport top left position. 

What am I doing wrong here?

**Comment by ocornut** [comment]
`GetCursorScreenPos()` is the "layouting position" where submitted Items are output.

The mouse cursor is `ImGui::GetMousePos()`.

**Comment by Gellert5225** [comment]
> ImGui::GetMousePos()

Thank you @ocornut
