### ISSUE TITLE
GLFW: The ctrl or shift key are not detected in secondary viewports

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#6248]
Hello,

**Version/Branch of Dear ImGui:**

Version: 1.89.4
Branch: viewport/docking_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_Glfw.cpp + imgui_impl_Opengl.cpp
Compiler: Msvc
Operating System: Win10 x64

**My Issue/Question:**

In my lib ImGuiFileDialog, i have implemented a multi selection for select many files at same time.
in main viewport all is working as expected. but when the dialog is outside so becoming a second viewport, 
the Ctrl and shift keys are not catched.

**Screenshots/Video**

![devenv_kKbWzPo45N](https://user-images.githubusercontent.com/1434736/225457631-eab40980-45c6-4c0c-8a05-c163e7e0ad45.gif)

After some search i found a fix, so i decided to share it. 
btw im not sure if there is not a better and easy fix, or maybe is just a settings im not aware of it :)

in imgui_impl_glfw.cpp
i see than the function ImGui_ImplGlfw_UpdateKeyModifiers is not called for each windows, but just for the main viewport if i understood well.

![image](https://user-images.githubusercontent.com/1434736/225457976-ef5ab94b-6a30-4dc7-a134-63db092e33d5.png)

so i modified it like that :

![image](https://user-images.githubusercontent.com/1434736/225458199-6fedf1b9-8009-40fe-8fad-b22bc56e5369.png)

and called it like before with the current windows as params in the function ImGui_ImplGlfw_KeyCallback

![image](https://user-images.githubusercontent.com/1434736/225458365-2d9d26b6-c544-45cd-9849-478c38b7e4cb.png)

and the result is :

![NVIDIA_Share_AcVh3dkqqM](https://user-images.githubusercontent.com/1434736/225458538-80588ad1-0764-4821-84a6-f1553df461bf.gif)

i have not created a pull request because its a very small fix and maybe im wrong, but if you want i can.

Kind Regards

**Comment by ocornut** [comment]
Ouch, this was indeed broken by 1f6e62a4a (#6034) for multi-viewports It's a shame we don't have a better way to formally test backends
Will push your fix now.

**Comment by ocornut** [comment]
Fixed with 91577c7f519f127298a42c9fac78260cb11aa6e9 
I attributed you the commit
Thanks a lot !

**Comment by aiekick** [comment]
Thank you too 😀
