### ISSUE TITLE
'opened' vs 'open'

### ISSUE THREAD

**Issue by petrihakkinen** [ocornut/imgui#625]
The usage of word "opened" in API functions and their descriptions confuses me. For example, 

"Begin(const char* name, bool* p_opened = NULL"
"BeginPopup... return true if popup if opened..." (typo, second "if" should be "is")
"ImGuiTreeNodeFlags_NoTreePushOnOpen... Don't do a TreePush() when opened"
(I think there are other places too)

I think these are misleading, because the word "opened" is not the opposite of "closed". "Opened" usually means, something that was just opened a moment ago.So instead of "opened", the correct word to use would be "open".

E.g. the current wording "BeginPopup... return true if popup is opened..." means to me, return true on the event of opening the pop up (single frame event), not continuously when the pop up is open.

Therefore I would change the text to "BeginPopup... returns true if the popup is open." Other API functions could be clarified similarly.

**Comment by petrihakkinen** [comment]
While this may sound like nitpicking, this actually had me confused quite a while, when figuring out how the API works.

**Comment by ocornut** [comment]
That makes senses. I was thinking about that just yesterday as the CollapsingHeader() with CloseButton situation may it even more confusing.

**Comment by ocornut** [comment]
Went through all of them, done. Large commit!
I have also renamed `SetNextTreeNodeOpened` to `SetNextTreeNodeOpen` and (unusually) haven't left a redirect function because the renaming should be obvious and duplicate functions with those names would be bit ugly.
