### ISSUE TITLE
error to show many text after AddFontFromFileTTF

### ISSUE THREAD

**Issue by zdy-gggg** [ocornut/imgui#6251]
My Issue/Question:
How do I show many text after AddFontFromFileTTF?

I need show many text the same time using ImGuI::Text()

I've adopted the code to my needs:
 ```
ImGui::Begin("Another Window", &show_another_window);
ImGui::SetWindowPos(ImVec2(0, 0), ImGuiCond_Always);
ImGui::SetWindowSize(ImVec2(nW, nH));
 for (int y = 0; y < 50; ++y)
 {
       for (int x = 0; x < 100; ++x)
        {
              ImGui::Text("Test");
               ImGui::SameLine();
         }
        ImGui::Text("TestEnd");
 }
 ImGui::End();
```
This works correctly with the default font 
![image](https://user-images.githubusercontent.com/69285635/225806340-ad71956d-ff26-43eb-974e-516c0350c0ff.png)

but If I load the font such as ` io.Fonts->AddFontFromFileTTF( "Imgui\\misc\\fonts\\Roboto-Medium.ttf",10, NULL);`
![image](https://user-images.githubusercontent.com/69285635/225806900-484b0831-c2be-4e9e-a1f0-8e9634a907cb.png)

**Comment by PathogenDavid** [comment]
This has come up before but I can't for the life of me remember what the underlying cause was. I *think* it was due to an outdated backend and/or a buggy custom backend.

It would be helpful if you filled out the issue template, particularly the parts about what version of Dear ImGui and what backends you're using.

**Comment by zdy-gggg** [comment]
Thank you for your reply

Version/Branch of Dear ImGui:
Version: 1.89 WIP
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVS 2019
Operating System: Windows 11

**Comment by PathogenDavid** [comment]
Thank you for providing those details!

Are you using an Intel GPU?

And either way: Can you please try updating your drivers and see if the issue goes away?

--------------

This appears to be related to https://github.com/ocornut/imgui/issues/5617, https://github.com/ocornut/imgui/issues/5655, and https://github.com/ocornut/imgui/issues/5709#issuecomment-1258332428

I think we've been assuming those were related to https://github.com/ocornut/imgui/issues/4832, but you're using a version of Dear ImGui that was supposed to fix 4832...so maybe not.

**Comment by zdy-gggg** [comment]
> Thank you for providing those details!
> 
> Are you using an Intel GPU?
> 
> And either way: Can you please try updating your drivers and see if the issue goes away?
> 
> This appears to be related to #5617, #5655, and [#5709 (comment)](https://github.com/ocornut/imgui/issues/5709#issuecomment-1258332428)
> 
> I think we've been assuming those were related to #4832, but you're using a version of Dear ImGui that was supposed to fix 4832...so maybe not.
Thank you for your reply
My GPU is RTX3060 and I think I'm using the latest driver
Sorry, I provided the wrong version information. Previously, I used imgui_ impl_ opengl2.cpp。
It can work normally after using imgui_impl_opengl3.cpp

Thank you for your help

**Comment by zdy-gggg** [comment]
> Thank you for providing those details!
> 
> Are you using an Intel GPU?
> 
> And either way: Can you please try updating your drivers and see if the issue goes away?
> 
> This appears to be related to #5617, #5655, and [#5709 (comment)](https://github.com/ocornut/imgui/issues/5709#issuecomment-1258332428)
> 
> I think we've been assuming those were related to #4832, but you're using a version of Dear ImGui that was supposed to fix 4832...so maybe not.

Thank you for your reply
My GPU is RTX3060 and I think I'm using the latest driver
Sorry, I provided the wrong version information. Previously, I used imgui_ impl_ opengl2.cpp。
It can work normally after using imgui_impl_opengl3.cpp

Thank you for your help

**Comment by GamingMinds-DanielC** [comment]
That much text definitely exceeds what 16 bit indices can do in a single batch. With the non-default font at least, with the default one enough seems to be clipped out to make it fit again. If you draw shorter, but more lines, it should happen with the default font as well. Switching to 32 bit indices should circumvent the problem.

**Comment by ocornut** [comment]
You should have gotten an assert for that, if your build setup doesn't show assert you are going to have severe problems using this library.

**Comment by zdy-gggg** [comment]
> In addition to what Daniel and Omar pointed out: Is there a reason you were using the legacy `imgui_impl_opengl2` backend? It really only exists for utterly ancient codebases and as Daniel pointed out it doesn't support large meshes unless you enable 32-bit indices.

Thank you for your reply
I tried to modify ImDrawIdx To use 32-bit indexes(typedef unsigned int ImDrawIdx;)，but whether you use the default font or AddFontFromFileTTF。
The operation results are as follows 
![image](https://user-images.githubusercontent.com/69285635/226494411-c173697b-4354-4a90-af8c-bb8022d096b1.png)

**Comment by zdy-gggg** [comment]
> You should have gotten an assert for that, if your build setup doesn't show assert you are going to have severe problems using this library.

Thank you for your suggestion. I'll try something
