### ISSUE TITLE
Code Editor widget and scrolling per line

### ISSUE THREAD

**Issue by vdweller84** [ocornut/imgui#6253]
Hello,

I  am making a code editor widget. Using regex I am parsing the code text into tokens and render each line's token group according to token text/color. Each line is not an actual ImGui thing, I just use Push/PopClipRect + draw lists.

An initial thought was to add a dummy with dimensions (max line width, text height) in order to produce a scrollbar. So far, so good:

![image](https://user-images.githubusercontent.com/96083791/225946072-2359c2fa-6c88-4d71-99e4-22a425ad63e6.png)

However this approach has the following issue: Vertical scrolling is smooth, which is not desirable in a code editor. Ideally, the following should happen:
User clicks up/down button -> text goes up/down one line
User drags bar -> text goes up/down but still snaps to lines

I was wondering if there is a method to achieve this effect with a child windows' vertical scrollbars, or if I should ditch scrollbars altogether and just add horizontal/vertical sliders disguised as scrollbars.

Any info would be appreciated.

EDIT: It just occurred to me that scrollbars also lack buttons. Since I am going to have to add them, and this will not look good in conjunction with "default" window scrollbars, I will just try adding slider widgets/buttons.

**Comment by ocornut** [comment]
> EDIT: It just occurred to me that scrollbars also lack buttons. Since I am going to have to add them, and this will not look good in conjunction with "default" window scrollbars, I will just try adding slider widgets/buttons.

I think this is still a viable thing we could incorporate in the scroll systems, and i wouldn’t mind adding buttons if there was a good design for configuring them.

Not that you should be able to call the scrollbar widget code and round values yourself too. Then add buttons manually.
