### ISSUE TITLE
compiler warnings with -pedantic and -Wextra on gcc

### ISSUE THREAD

**Issue by freanux** [ocornut/imgui#626]
Firstly, thanks for this very useful library. Please compile your library with following flags:
`-Wall -pedantic -Wextra`

You will see that the function ShowMetricsWindow needs to be fixed or the warning should be muted with:
`#pragma GCC diagnostic ignored "-Wformat"`

**Comment by ocornut** [comment]
Please report the actual warnings. 

Travis is running Makefile with `-Wall` https://travis-ci.org/ocornut/imgui
I suppose I could increase the warning level of those Makefile but in my experience it creates more daily maintenance than not, considering I'm not running GCC here.

**Comment by freanux** [comment]
`In file included from imgui_impl_sdl.cpp:10:0:
/usr/include/SDL2/SDL_syswm.h:108:18: warning: comma at end of enumerator list [-Wpedantic]
     SDL_SYSWM_MIR,
                  ^
imgui_impl_sdl.cpp:189:9: warning: unused parameter ‘window’ [-Wunused-parameter]
 bool    ImGui_ImplSdl_Init(SDL_Window* window)
         ^
../../imgui.cpp: In static member function ‘static void ImGui::ShowMetricsWindow(bool*)::Funcs::NodeDrawList(ImDrawList*, const char*)’:
../../imgui.cpp:9437:114: warning: format ‘%p’ expects argument of type ‘void*’, but argument 2 has type ‘ImDrawCallback {aka void (*)(const ImDrawList*, const ImDrawCmd*)}’ [-Wformat=]
                         ImGui::BulletText("Callback %p, user_data %p", pcmd->UserCallback, pcmd->UserCallbackData);
                                                                                                                  ^
../../imgui.cpp: In static member function ‘static void ImGui::ShowMetricsWindow(bool*)::Funcs::NodeWindow(ImGuiWindow*, const char*)’:
../../imgui.cpp:9484:132: warning: format ‘%p’ expects argument of type ‘void*’, but argument 6 has type ‘ImGuiWindow*’ [-Wformat=]
                 if (!ImGui::TreeNode(window, "%s '%s', %d @ 0x%p", label, window->Name, window->Active || window->WasActive, window))
                                                                                                                                    ^
In file included from ../../imgui.h:28:0,
                 from ../../imgui_draw.cpp:15:
../../stb_rect_pack.h: In function ‘void stbrp_pack_rects(stbrp_context*, stbrp_rect*, int)’:
../../stb_rect_pack.h:545:34: warning: comparison is always true due to limited range of data type [-Wtype-limits]
       STBRP_ASSERT(rects[i].w <= 0xffff && rects[i].h <= 0xffff);
                                  ^
../../imgui_draw.cpp:71:28: note: in expansion of macro ‘IM_ASSERT’
 #define STBRP_ASSERT(x)    IM_ASSERT(x)
                            ^
../../stb_rect_pack.h:545:7: note: in expansion of macro ‘STBRP_ASSERT’
       STBRP_ASSERT(rects[i].w <= 0xffff && rects[i].h <= 0xffff);
       ^
../../stb_rect_pack.h:545:58: warning: comparison is always true due to limited range of data type [-Wtype-limits]
       STBRP_ASSERT(rects[i].w <= 0xffff && rects[i].h <= 0xffff);
                                                          ^
../../imgui_draw.cpp:71:28: note: in expansion of macro ‘IM_ASSERT’
 #define STBRP_ASSERT(x)    IM_ASSERT(x)
                            ^
../../stb_rect_pack.h:545:7: note: in expansion of macro ‘STBRP_ASSERT’
       STBRP_ASSERT(rects[i].w <= 0xffff && rects[i].h <= 0xffff);
       ^
`

**Comment by ocornut** [comment]
Thanks. PS use triple backword apostrophe to quote a block of code.

**Comment by freanux** [comment]
Okay. Thanks.

**Comment by ocornut** [comment]
Should be all fixed now.
