### ISSUE TITLE
Is it possible to have a widget like a ListView in ImGui?

### ISSUE THREAD

**Issue by ThewyRogue99** [ocornut/imgui#6260]
**Version/Branch of Dear ImGui:**

Version: 1.89.2
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: Microsoft Visual C++
Operating System: Windows 11

**My Issue/Question:**

I render a scene hierarchy panel in my game engine with ImGui::Selectable widget. When I run a stress-test to measure performance of my game engine, I render 100000 entities but rendering this much ImGui::Selectable widgets cause a huge performance loss and only 15 of them are visible. In other UI libraries(ex. Flutter) there is a widget called ListView. So i was wondering that if this can be fixed with a widget similar to ListView where i can give the count of the list and only render visible items. Also If there is a way to achieve this in the current version of the ImGui can you please help me how to implement it?

**Standalone, minimal, complete and verifiable example:**
```
// Here's the code i run for every entity in my SceneHierarchyPanel

auto& tag = entity.GetComponent<TagComponent>().Tag;

std::string tag_str = TypeUtils::FromUTF16(tag);

if(ImGui::Selectable(tag_str.c_str(), SelectedEntity == entity, ImGuiSelectableFlags_SpanAvailWidth))
{
	SetSelectedEntity(entity);
}

if (ImGui::BeginPopupContextItem(entity.GetUUID().GetString().c_str()))
{
	if (ImGui::MenuItem("Delete Entity"))
	{
		Context->DestroyEntity(entity);

		if (SelectedEntity == entity)
			SetSelectedEntity({ });
	}
	ImGui::EndPopup();
}
```

**Comment by GamingMinds-DanielC** [comment]
Look for `ImGuiListClipper` in the demo sources. That clipper can do exactly what you want with the assumption that every item has the same height.

**Comment by ThewyRogue99** [comment]
@GamingMinds-DanielC Thanks for your help and quick response, I looked for ImGuiListClipper and changed my scene hierarchy panel to use it and it worked like a charm. I will leave my code here for anyone that wants to use it:

```
auto& view = Context->SceneRegistry.view<TagComponent>();

ImGuiListClipper clipper;
clipper.Begin(view.size());

while (clipper.Step())
{
	for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; i++)
	{
		// Get the entity ID
		Entity entity(*(std::next(view.begin(), i)), Context);

		auto& tag = entity.GetComponent<TagComponent>().Tag;

		std::string tag_str = TypeUtils::FromUTF16(tag);

		if (ImGui::Selectable(tag_str.c_str(), SelectedEntity == entity, ImGuiSelectableFlags_SpanAvailWidth))
		{
			SetSelectedEntity(entity);
		}

		if (ImGui::BeginPopupContextItem(entity.GetUUID().GetString().c_str()))
		{
			if (ImGui::MenuItem("Delete Entity"))
			{
				Context->DestroyEntity(entity);

				if (SelectedEntity == entity)
					SetSelectedEntity({ });
			}
			ImGui::EndPopup();
		}
	}
}

clipper.End();
```
