### ISSUE TITLE
fade animation

### ISSUE THREAD

**Issue by augis01** [ocornut/imgui#6261]
im a begginer with imgui and i would like to add a fade animation to these two voids:

void Active() 
{ 
    ImGuiStyle* Style = &ImGui::GetStyle(); 
    Style->Colors[ImGuiCol_Button] = ImColor(51, 63, 99); 
    Style->Colors[ImGuiCol_ButtonActive] = ImColor(51, 63, 99); 
    Style->Colors[ImGuiCol_ButtonHovered] = ImColor(51, 63, 99); 
}

void Hovered() 

{ 
    ImGuiStyle* Style = &ImGui::GetStyle(); 
    Style->Colors[ImGuiCol_Button] = ImColor(51, 63, 99); 
    Style->Colors[ImGuiCol_ButtonActive] = ImColor(31, 0, 43); 
    Style->Colors[ImGuiCol_ButtonHovered] = ImColor(31, 0, 43); 
}

but i dont know how can i do it

**Comment by ocornut** [comment]
Questions is ambiguous and probably mostly as general programming question. Can't answer and closing as a variant of #1586

**Comment by mingss5567** [comment]
> Questions is ambiguous and probably mostly as general programming question. Can't answer and closing as a variant of #1586

are you gay ?
