### ISSUE TITLE
Drawing a polygon/line on top of an image causes the font texture to get drawn on top of the image

### ISSUE THREAD

**Issue by samrisxxl** [ocornut/imgui#6262]
**Version/Branch of Dear ImGui:**

Version: 1.89.4
Branch: docking

```
Dear ImGui 1.89.4 (18940)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1934
define: _MSVC_LANG=202004
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_ripples
io.BackendRendererName: imgui_impl_ripples
io.ConfigFlags: 0x00000041
 NavEnableKeyboard
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000080E
 HasMouseCursors
 HasSetMousePos
 HasMouseHoveredViewport
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 0.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: My own proprietary implementation based on GLFW and Vulkan
Compiler: MSVC, C++20, symbols are enabled
Operating System: Windows 10

**My Issue/Question:**

Drawing any primitive (I have tested AddTriangleFilled and AddLine) on top of an image causes the font texture to get drawn on top of the image. I encountered this issue when incorporating ImGuizmo into my 3d editor. I tacked down the cause to the pushing of new vertices to the draw list AFTER calling ImGui::Image(...). If I draw the image after the primitive the issue is gone but the primitive will of course be drawn over by the image. If I exit early from AddConvexPolyFilled before any data is pushed to the draw list the issue is gone.

It seems highly likely that this is not an issue with Dear ImGui and that I have made a mistake in my backend implementation, I was hoping that someone could point me in the right direction of what might be causing an issue like this.

Lines 1034-1051 from ImDrawList::AddConvexPolyFilled in imgui_draw.cpp:
```
    else
    {
        // return <-- If I exit early here the issue is gone but nothing gets drawn of course
        // Non Anti-aliased Fill
        const int idx_count = (points_count - 2)*3;
        const int vtx_count = points_count;
        PrimReserve(idx_count, vtx_count);
        for (int i = 0; i < vtx_count; i++)
        {
            _VtxWritePtr[0].pos = points[i]; _VtxWritePtr[0].uv = uv; _VtxWritePtr[0].col = col;
            _VtxWritePtr++;
        }
        for (int i = 2; i < points_count; i++)
        {
            _IdxWritePtr[0] = (ImDrawIdx)(_VtxCurrentIdx); _IdxWritePtr[1] = (ImDrawIdx)(_VtxCurrentIdx + i - 1); _IdxWritePtr[2] = (ImDrawIdx)(_VtxCurrentIdx + i);
            _IdxWritePtr += 3;
        }
        _VtxCurrentIdx += (ImDrawIdx)vtx_count;
    }
```

I don't have a good enough understanding of how the vertex batching works to guess why this code would add an extra primitive with a texture, especially when removing the "ImDrawListFlags_AntiAliasedFill" flag (see below) which should not utilize textures to draw the polygon(?)

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/16017293/226707531-add0aa9e-fc1b-4562-a310-e31a6c15c739.png)

![image](https://user-images.githubusercontent.com/16017293/226705363-983d869a-347f-4845-82a7-3b73dcb259a9.png)

The font atlas texture is scaled along with the image, not the window or the primitive drawn
```
//ImGui::Image((void*)sceneRenderingNode.getRenderTargetTextureCollection().get(), viewportExtent, ImVec2{ 0, 1 }, ImVec2{ 1, 0 });
ImGui::Image((void*)sceneRenderingNode.getRenderTargetTextureCollection().get(), ImVec2(viewportExtent.x, viewportExtent.y/2.0f), ImVec2{0, 1}, ImVec2{1, 0});
```
![image](https://user-images.githubusercontent.com/16017293/226711622-0cde3a9c-c37b-467d-a9d9-2f43f8ab7ee6.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// getRenderTargetTextureCollection() returns a type representing a VkDescriptorSet
ImGui::Image((void*)sceneRenderingNode.getRenderTargetTextureCollection().get(), viewportExtent, ImVec2{ 0, 1 }, ImVec2{ 1, 0 });

auto drawList = ImGui::GetWindowDrawList();
// I modify the draw list flag here to get the less complex, easier to debug path in ImDrawList::AddConvexPolyFilled but the issue is the same with the flags unchanged
drawList->Flags = drawList->Flags &	~ImDrawListFlags_AntiAliasedFill; 
// The coordinates of the primitive does not seem to matter but setting color alpha to 0 causes the function to exit early and therefore the issue is gone, any other color values seem to cause the same issue.
drawList->AddTriangleFilled(ImVec2(0, 0), ImVec2(0, 0), ImVec2(0, 0), ImGui::ColorConvertFloat4ToU32(ImVec4(0, 0, 0, 1)));
```

**Comment by ocornut** [comment]
You can look at Metrics->DrawList to see the draw call we are emitting and confirm if the triangles for those polygons/lines are using the right texture (dear imgui's font atlas) or the wrong texture (previous image's texture).

**Comment by samrisxxl** [comment]
```
ImVec2 viewportExtent = ImGui::GetContentRegionAvail();

sceneRenderingNode.setRenderTargetResolution(glm::vec2(viewportExtent.x, viewportExtent.y));
void* renderTargetPtr = (void*)sceneRenderingNode.getRenderTargetTextureCollection().get();
ImGui::Image(renderTargetPtr, viewportExtent, ImVec2{ 0, 1 }, ImVec2{ 1, 0 });

RP_ENGINE_INFO("renderTargetPtr: {0}", renderTargetPtr);
RP_ENGINE_INFO("font tex id: {0}", ImGui::GetIO().Fonts->TexID);

auto drawList = ImGui::GetWindowDrawList();
drawList->Flags = drawList->Flags &	~ImDrawListFlags_AntiAliasedFill;
auto minClip = drawList->GetClipRectMin();
drawList->AddLine(ImVec2(minClip.x + 200, minClip.y + 10), ImVec2(minClip.x + 200, minClip.y + 100), ImGui::ColorConvertFloat4ToU32(ImVec4(1, 1, 1, 1)));
```

![image](https://user-images.githubusercontent.com/16017293/226893118-5d9b853b-cbf4-4bd3-928c-14f506adf100.png)

![image](https://user-images.githubusercontent.com/16017293/226893185-40ed643e-b1c8-4ecc-a329-998f3f9243c2.png)

So the image is using the correct texture id (the scene render target that I am providing) and the line draw has the font texture id set but I assume that is by default?

**Comment by ocornut** [comment]
To clarify:

> It seems highly likely that this is not an issue with Dear ImGui and that I have made a mistake in my backend implementation, I was hoping that someone could point me in the right direction of what might be causing an issue like this.

I'm not sure there's much to say: maybe check for error codes in your texture binding calls and/or use RenderDoc, you'll probably end up finding your issue (and you can share it here in case it's useful for others). I don't think it is going to e helpful digging further inside vertex or draw call emitting code if you can confirm in Metrics that Dear ImGui ends up giving you those ImDrawCmd with the correct texture. There's just something broken with your texture binding code, which hopefully is not going to be too complex to track down!

**Comment by samrisxxl** [comment]
Thanks for the help! It's good to able to reduce the number of potential issues at least. I am probably going to look over the entire back end (maybe even reimplement some parts) as it was implemented when the engine had an older version of Dear ImGui.

I will report back when/if I find the issue!

**Comment by samrisxxl** [comment]
Found the issue when I started re-implementing the backend based on the imgui_impl_vulkan.h/.cpp and imgui_impl_glfw.h/.cpp. I had simply set the vertex and index offsets incorrectly:

```
command.indexCount = cmd_list->IdxBuffer.Size;
command.firstIndex = global_idx_offset;
command.vertexOffset = global_vtx_offset;
```

Should be:
```
command.indexCount = pcmd->ElemCount;
command.firstIndex = pcmd->IdxOffset + global_idx_offset;
command.vertexOffset = pcmd->VtxOffset + global_vtx_offset;
```

Later used in my vulkan implementation here:
```
vkCmdDrawIndexed(m_commandBuffer, indexCount, instanceCount, firstIndex, vertexOffset, firstInstance);
```

Super trivial, but that's usually the hardest ones to find I guess...
