### ISSUE TITLE
'DC': identifier not found in imgui.cpp

### ISSUE THREAD

**Issue by ItsNovaAndCrap** [ocornut/imgui#6265]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.88
Branch: TheCherno/imgui (docking) (I would've gone to that repo's issues page but it doesn't have one)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp (I'm using Glad as a custom loader)
Compiler: msvc
Operating System: Windows 10 Enterprise

**My Issue/Question:**

For context, I am following TheCherno's game engine tutorial. I am currently on the episode 45 (Shader Library) in the playlist.
This might be an issue exclusive to his fork, but whenever I try to build my engine, the ImGui project I have in solution throws an error from these lines of code inside of `imgui.cpp` in the function `ImGui::SetActiveID`:
```cpp
3838 |     for (int i = 0; i < DC.Layouts.Data.Size; i++)
---------------------------------------------------------------------
3840 |         ImGuiLayout* layout = (ImGuiLayout*)DC.Layouts.Data[i].val_p;
```
It says the the variable DC doesn't exist. I tried to fix it by adding `window->` right before both mentions of DC, but whenever I build it throws an exception saying that `window` is nullptr.

**Screenshots/Video**

![imguierr](https://user-images.githubusercontent.com/69518097/227016847-61a21f6d-99e4-4020-b8d6-d67808e39268.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
None, because I don't think this has anything to do with my code, all of the errors are coming from `imgui.cpp`

**Comment by ItsNovaAndCrap** [comment]
I cannot stress enough that this issue is from this fork of imgui!
[https://github.com/TheCherno/imgui]()

**Comment by ocornut** [comment]
You have already asked this question in https://github.com/ocornut/imgui/discussions/6195
You are using a modified version of Dear ImGui we can't really help. This code doesn't exist in our version. 
TheCherno's version has #846 merged and what else I don't know.

Their changes are:
https://github.com/ocornut/imgui/compare/docking...TheCherno:imgui:docking

It seems like you should be using their version or asking for support in Hazel's issue tracker.

**Comment by yanshuicc** [comment]
there is a pr to fix this problem. https://github.com/TheCherno/imgui/pull/18/commits/af7c4231576a21ef45822b85dc12feb9ed6a4afe

**Comment by NiceHills** [comment]
> there is a pr to fix this problem. [TheCherno@af7c423](https://github.com/TheCherno/imgui/commit/af7c4231576a21ef45822b85dc12feb9ed6a4afe)

You are a superhero

**Comment by NiceHills** [comment]
> there is a pr to fix this problem. [TheCherno@af7c423](https://github.com/TheCherno/imgui/commit/af7c4231576a21ef45822b85dc12feb9ed6a4afe)

Careful. It won't run without a " if (window != NULL)".
