### ISSUE TITLE
Understanding Widget Focus?

### ISSUE THREAD

**Issue by voidware** [ocornut/imgui#6270]
Version: 1.89.5 WIP (18942)
Branch: master
backend: sokol/emscripten

Can someone explain a bit about mouse focus?

Get the demo window and open `Widgets`. look for the Radio button (a, b & c) and
 the input "Hello, world!";

When i click on the radio buttons they work. You can see the inner blue circle highlight. But if i put the keyboard focus on "Hello world" by clicking there, I get the little flashing "i-beam". Now click on a radio button and it _doesn't work_! Click _again_ and it's ok.

Its appears it takes a click to remove the focus from the input. But the radio button is not after keyboard focus, only the mouse?

I would like for the radio button click to work, _even when_ the "hello world" has keyboard focus.

How to do this?

Thanks for helping.

**Comment by ocornut** [comment]
It works here.
I would say it might be bug in your backend or input system? Are you using a mouse or a touch screen?

**Comment by voidware** [comment]
Oh no, not another sokol problem!

Sorry, this might not be imgui at all. This is on desktop, no touch screen.

I'll investigate. thanks for checking.

**Comment by ocornut** [comment]
The IO function for backends to call are pretty simple and I'd be surprised if sokol_imgui did anything fancy.

To help understand this, you can open `Demo->Metrics->Inputs` and `Metrics->Internal State`, watch HoveredId, ActiveId.
Also maybe `Demo->Tools->Debug Log` enable ActiveID and IO.

**Comment by voidware** [comment]
Appears to be the result of an UNFOCUSED event in Sokol with emscripten.

```
    emscripten_set_blur_callback(EMSCRIPTEN_EVENT_TARGET_WINDOW, 0, true, _sapp_emsc_blur_cb);
```

```
SOKOL_API_IMPL bool simgui_handle_event(const sapp_event* ev) {
              ...
    switch (ev->type) {
        case SAPP_EVENTTYPE_FOCUSED:
            _simgui_add_focus_event(io, true);
            break;
        case SAPP_EVENTTYPE_UNFOCUSED:
            _simgui_add_focus_event(io, false);  // <- HERE
            break;
        case SAPP_EVENTTYPE_MOUSE_DOWN:
       ....
````
If i prevent this "blur callback", it seems to fix it, and I can't find anything broken. But there must be.

What things rely on unfocus events. Imgui reports focus lost when i click on another widget. So that seems ok.

Now I've updated everything, mobile enter key doesn't work. ho hum!

**Comment by ocornut** [comment]
I would think this is something to report on Sokol's repository.
They can use the Debug Log to inspect IO events.

Unfocused app tends to clear inputs.

**Comment by ocornut** [comment]
Do you have any Input Method Editor or other input facility tool or a Virtual Keyboard?
I’m wondering is perhaps selecting a InputText() which sets io.WantTextInput is used by the backend in a way to ask the ask to display an IME, and perhaps in Emscripten this leads to a perceived app loss of focus ?
