### ISSUE TITLE
Is there an easy way to get vertex data for rendering a text out of ImGui?

### ISSUE THREAD

**Issue by darthdeus** [ocornut/imgui#628]
[Originally I asked here](http://gamedev.stackexchange.com/questions/120964/how-can-i-use-imgui-to-render-simple-text-instead-of-using-stb-truetype-directly), but then realized this is probably a better place.

ImGui already can load/process truetype fonts and render them, so I thought it would make sense to use this for my own font rendering purposes, instead of using stb_truetype directly.

To put it simply, I'm either looking to render text outside of ImGui windows, or just use ImGui to generate vertex data to use in conjuction with its font textures to render the text myself.

**Comment by ocornut** [comment]
https://github.com/ocornut/imgui/issues/530
https://github.com/ocornut/imgui/issues/545

Will add something about this in the FAQ.

**Comment by ocornut** [comment]
I added this in the FAQ and it is really the simplest way:
```
 Q: How can I use the drawing facilities without an ImGui window? (using ImDrawList API)
 A: The easiest way is to create a dummy window. Call Begin() with NoTitleBar|NoResize|NoMove|NoScrollbar|NoSavedSettings|NoInputs flag, zero background alpha, 
    then retrieve the ImDrawList* via GetWindowDrawList() and draw to it in any way you like.
```

Let me know if that works for you.

**Comment by anentropic** [comment]
The info no longer appears on the FAQ page, as far as I can tell...

Is this still a valid way to achieve this?

**Comment by ocornut** [comment]
This Q/A is a more complete version of it:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-custom-shapes-using-low-level-imdrawlist-api
