### ISSUE TITLE
Dynamic Glyph Loading

### ISSUE THREAD

**Issue by Sumandora** [ocornut/imgui#6287]
I know that I can technically build the font with a big glyph range, but I don't think that is the memory efficient way that I'm looking for.
There are font renderers dynamically loading characters whenever they are needed.
Is there a similar feature in ImGui?
I saw an old issue (https://github.com/ocornut/imgui/issues/921#issuecomment-263123979)
The solution proposed there would be to rebuild the fonts every time you want to add a glyph, which I think is a bad solution... for the user at least.
Because it would require me, to go through my entire application to search for ImGui render calls with strings which could contain unicode in some way (respecting user-input).
The other problem I have with this solution is that it would require me to implement some system to check whether a reload is required or not.
This puts additional overhead on the application.
I'm curious if such a feature is planned (or exists already and I'm just blind)

Just in case the question arises: Yes, my font (Noto Sans) has all the characters merged in a single file

**Comment by ocornut** [comment]
Closing as "answered", this is among the most request thing and I imagine should be fixed by 2.0.

**Comment by ocornut** [comment]
FYI, work on `dynamic_fonts` branch aimed to be in 1.92 (#8465) solves this.
