### ISSUE TITLE
How to disable antialiased rendering fonts?

### ISSUE THREAD

**Issue by iperov** [ocornut/imgui#629]
subj

**Comment by ocornut** [comment]
There's no "antialiased rendering fonts" options. Fonts are just rasterized with stb_truetype. If you want a crisp / bitmap looking font choose a crisp / bitmap looking TTF file like the default ProggyClean font.

**Comment by ocornut** [comment]
Closing this assuming it is ok. Let me know if there's more to provide. Perhaps explain the reasoning or what actual problems you have, if there's something you think can be done. Using entire sentences would help as well :)
