### ISSUE TITLE
How to add widgets to the left of a Tree or CollapsingHeader 

### ISSUE THREAD

**Issue by thewoz** [ocornut/imgui#6294]
Hello everyone,
sorry to bother again. 
I am trying to figure out how to implement something like this.

<img width="308" alt="test" src="https://user-images.githubusercontent.com/907951/229375883-2101a11b-78c3-4247-89ca-01fbc11aaca7.png">

Where the eye and the checkmark are buttons.

I tried to read the following posts #282 #460 #2920  and couldn't quite figure out how to do it.
Basically I would like to use a CollapsingHeader but if it was possible to do it just with tree that would be fine too.

**Comment by ocornut** [comment]
Also see #600

You would need to pass the `ImGuiTreeNodeFlags_AllowOverlapMode ` flag to your `CollapsingHeader()` or `TreeNode()`.
Then use SameLine() or SetCursorScreenPos() to position yourself to the desired button location and submit the button.

**Comment by thewoz** [comment]
hi Omar,
thank you for your reply!
sorry i didn't see #600
I think ImGuiTreeNodeFlags_AllowOverlapMode became ImGuiTreeNodeFlags_AllowItemOverlap.
Using ImGuiTreeNodeFlags_AllowItemOverlap and SameLine() everything works! Thanks!

Also saw #846 do you think it will become official sooner or later?

**Comment by ocornut** [comment]
> I think ImGuiTreeNodeFlags_AllowOverlapMode became ImGuiTreeNodeFlags_AllowItemOverlap.

Correct.

> Using ImGuiTreeNodeFlags_AllowItemOverlap and SameLine() everything works! Thanks!

Good to hear, closing.


I have no eta for anything, but the aim is to make enough change to our layout system to make that PR possible as an extension.
