### ISSUE TITLE
Call to data->DeleteChars(0, data->BufTextLen) from within a callback for InputTextMultilineWithHint being called twice.

### ISSUE THREAD

**Issue by 0xPerseus** [ocornut/imgui#6296]
**Version/Branch of Dear ImGui:**

Version: 1.89.4
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: Visual Studio 2022
Operating System: Windows 11

**My Issue/Question:**

I'm not sure if the problem I'm experiencing is because of the way I've implemented this function or if it's intended / expected. I'm using "ImGui::InputTextMultilineWithHint" that has a callback function that checks the text entered against a license validation function in my application. The license check function only runs if the length of the entered text matches a max_length I've defined. If the license check fails, I delete all the characters in the text buffer so the user can enter a valid license via "data->DeleteChars(0, data->BufTextLen);" However, this causes the function to be called twice if the user pastes the license key using Ctrl+V.

From what I can see, it looks like data->DeleteChars(0, data->BufTextLen); is invoking the callback a second time as it's "modifying" data in the text buffer. I know that if you individually type in each character, the callback will run for each entered character as per the ImGuiInputTextFlags_CallbackEdit flag, but that's not what's occurring here.

This unexpected behavior isn't observed when the call to "data->DeleteChars(0, data->BufTextLen);" is removed from the callback function.

The relevant code is as follows:

```
constexpr long text_input_flags = ImGuiInputTextFlags_CallbackEdit | ImGuiInputTextFlags_CharsNoBlank;

static int process_reg_input(ImGuiInputTextCallbackData* data)
{
	if (data->EventFlag == ImGuiInputTextFlags_CallbackEdit)
	{
		if (data->BufTextLen == license_helper::max_license_length) //only process if the key length matches.
		{
			std::vector buf_vector(data->Buf, data->Buf + data->BufTextLen);
			if ((license_helper::lic_regged = license_helper::process_serial_lookup(buf_vector, false)) == false)
			{
				data->DeleteChars(0, data->BufTextLen); //<- This causes the callback to be executed a second time.
			}
		}
	}
	return 0;
}

static void gui::help_marker(const char* desc, const ImVec4 color)
{
	ImGui::TextDisabled("[?]");
	if (ImGui::IsItemHovered(ImGuiHoveredFlags_DelayShort))
	{
		ImGui::BeginTooltip();
		ImGui::PushTextWrapPos(ImGui::GetFontSize() * 20.0f);
		ImGui::PushStyleColor(ImGuiCol_Text, color);
		ImGui::TextUnformatted(desc);
		ImGui::PopStyleColor();
		ImGui::PopTextWrapPos();
		ImGui::EndTooltip();
	}
}

ImGui::Text(SECSTR("Registration Key:"));
ImGui::SameLine();
help_marker(
	"Copy & paste your license key in the text area below.\n\nThe key will be automatically applied and saved if it's valid.",
	ImVec4(255, 255, 255, 255));

ImGui::InputTextMultilineWithHint("##registration_key", "<Paste your license key here>", regkey, sizeof regkey, ImVec2(get_x() + 5, get_y() / 2 + 48), text_input_flags, &process_reg_input, nullptr);
```

**Comment by ocornut** [comment]
It seems to make sense that any edit would call that callback.

In this specific case, it's a recursive call which to be honest I haven't been expected nor tested, so without further inspection I would guess there's _maybe_ some form of bug in it. 
It's not clear what's your problem with that, since the callback code you pasted wouldn't be affected by the second call either way.

Also I honestly don't think the behavior you are aiming at is good user experience. I would let the user clear the buffer if they make a mistake.

**Comment by 0xPerseus** [comment]
> It seems to make sense that any edit would call that callback.
> 
> In this specific case, it's a recursive call which to be honest I haven't been expected nor tested, so without further inspection I would guess there's _maybe_ some form of bug in it. It's not clear what's your problem with that, since the callback code you pasted wouldn't be affected by the second call either way.
> 
> Also I honestly don't think the behavior you are aiming at is good user experience. I would let the user clear the buffer if they make a mistake.

Thanks for the response and feedback. I'm trying to avoid the users having to type out the license key manually as it's >1000 characters in length. I encourage them pasting it directly from the clipboard to avoid any potential mistakes as typing the key in manually isn't feasible nor advised, due to the length of the key. The expected behavior being that the license is pasted, it's automatically applied, then subsequently saved so that it doesn't have to be entered again or until the license expires.

Interestingly, I validated via my debug output text that pasting the blob of text only causes the event to fire once, not once per each character in the string, which is desired here. The problem is only observed when an invalid key is provided, which runs the data->DeleteChars(0, data->BufTextLen) function (the one causing the duplicative / recursive call).

I didn't mention that the output of what the application is doing is communicated to the end-user via a console window. Since the function is being called twice by this behavior, it's outputting twice to the console as seen below. Please ignore the debug prompts as those are not present in the release build.

![I7HSykxmEv](https://user-images.githubusercontent.com/48509097/229620561-48f410e8-5336-4a7d-b0da-38c6d4c38bab.png)

**Comment by GamingMinds-DanielC** [comment]
> Interestingly, I validated via my debug output text that pasting the blob of text only causes the event to fire once, not once per each character in the string, which is desired here. The problem is only observed when an invalid key is provided, which runs the data->DeleteChars(0, data->BufTextLen) function (the one causing the duplicative / recursive call).

The single call for a paste operation is not unexpected. As the name of the flag implies, the callback is once per edit, not necessarily per character. And a paste operation is just a single edit, no matter how many characters are getting added.

The recursive callback seems correct as well, After all, it just tells you of another edit that actually happened. But you can easily guard against it:
```c++
static int process_reg_input(ImGuiInputTextCallbackData* data)
{
	static bool entered = false;
	int result = 0;
	if (!entered)
	{
		entered = true;
		// rest of processing, maybe alter result
		entered = false;
	}
	return result;
}
```
As for the input text field itself, it doesn't seem like the right choice if you don't want users to enter the license key manually. Have you considered a set of buttons with f.e. "import from clipboard" and "import from file"? A text input could be another option (hiding in a popup window behind a button "enter manually"), but I wouldn't clear the text on wrong inputs. A line below the input indicating the wrong key format (too short or other reasons) or an incorrect key (can even dynamically be colored red) would be the normal way.

**Comment by ocornut** [comment]
Closing as answered, thank you!

We'll be looking into validating that the recursive call does more or less the right thing (aka no glaring bug).

**Comment by ocornut** [comment]
> From what I can see, it looks like data->DeleteChars(0, data->BufTextLen); is invoking the callback a second time

I actually verified this now and it is not the case. We don't even call that callback in that situation (using API InsertChars/DeleteChars). Whether it is the best design or not I don't know and is not a priority to tell, but your issue is something else. Either you have modified code, or you omitted something in your repro etc.
