### ISSUE TITLE
real time data display problem

### ISSUE THREAD

**Issue by kdxq** [ocornut/imgui#6297]
I used imgui and implot for real-time display of temporal data and found the following problem:

When a series of data values remain constant (the bool variable is most pronounced and often remains in a state), after a few hours, the curve no longer displays. picture as follow

Some of the codes are as follows:

------------------------------------------------------------------------------------

						if (ImPlot::BeginPlot("",ImVec2(-1,0),ImPlotFlags_NoMenus) ){
							ImPlot::SetupAxisScale(ImAxis_X1, ImPlotScale_Time);
					
							if (i == rows - 1)
							{
								ImPlot::SetupAxes("", NULL, flags_axis, flags_axis);
							}
							else {
								ImPlot::SetupAxes("", NULL, flags_axis | ImPlotAxisFlags_NoTickLabels, flags_axis);
							}

							for (int k = 0; k <= pltManager.pltVec[i].yMax; k++)
							{
								ImPlot::SetupAxis(ImAxis_Y1 + k, "", flags_axis);
							}

							ImPlot::SetupAxisLimits(ImAxis_X1, t - history, t, paused ? ImGuiCond_Once : ImGuiCond_Always);
							ImPlot::SetupAxisLimits(ImAxis_Y1, 0, 1);
							ImPlot::SetNextFillStyle(IMPLOT_AUTO_COL, 0.5f);

							

							if (pltManager.pltVec.size() > 0)
							{
								for (int n = 0; n < pltManager.pltVec[i].plt.size(); n++)
								{
									
									int k = pltManager.pltVec[i].plt[n].lineIndex;

									if (vecPltItem[k].isBIT)
									{
										ImPlot::SetupAxisLimits(ImAxis_Y1, 0, 1, ImGuiCond_Always);
									}
									else {
										ImPlot::SetupAxisLimits(ImAxis_Y1, 0, 1);
									}

									ImPlot::SetAxis(pltManager.pltVec[i].plt[n].yIndex);
									ImPlot::SetNextLineStyle(vecPltItem[k].Color);
								
									if (vecPltItem[k].buffer.Data.size() == 0) continue;

								
									if (vecPltItem[k].isBIT)
									{
										ImPlot::PlotDigital(
											&vecPltItem[k].Label[0],
											&vecPltItem[k].buffer.Data[0].x,
											&vecPltItem[k].buffer.Data[0].y,
											vecPltItem[k].buffer.Data.size(),
											0,
											vecPltItem[k].buffer.Offset,
											2 * sizeof(double));
									}
									else {
										ImPlot::PlotLine(
											&vecPltItem[k].Label[0],
											&vecPltItem[k].buffer.Data[0].x,
											&vecPltItem[k].buffer.Data[0].y,
											vecPltItem[k].buffer.Data.size(),
											0,
											vecPltItem[k].buffer.Offset,
											2 * sizeof(double));
									}
------------------------------------------------------------------------------------

Please help me see how to troubleshoot this problem?
![image](https://user-images.githubusercontent.com/43022212/229658300-45f4e65b-a999-4702-b7c7-4408c3b93e3e.png)

----

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: XXX
Branch: XXX _(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: XXX

**My Issue/Question:**

XXX _(please provide as much context as possible)_

**Screenshots/Video**

XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
This seems like an ImPlot issue there this is the wrong repository to ask, I’ll close this.

> Please help me see how to troubleshoot this problem?

Looks in demo>tools>metrics to confirm drawlist output, then use a debugger to step into the code.
