### ISSUE TITLE
WindowRounding Not Affecting External Overlay Windows

### ISSUE THREAD

**Issue by 0aspect** [ocornut/imgui#6298]
Version: 1.80
Branch: Master

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Operating System: Windows 10

My Issue:

While working on a application in the example_win32_directx9.sln I noticed that once you convert the project, to a external overlay window, applying rounding from either the default style or using a PushStyleVar just does not work.

External Demo and Style Editor
![image](https://user-images.githubusercontent.com/96223830/229728143-9078e05b-083c-4f04-9a76-36f89b980367.png)

Directx9 Example
![image](https://user-images.githubusercontent.com/96223830/229729149-641a984c-b041-44e5-aff3-1341bf354f58.png)

If there is a fix for this please let me know. Thanks in advance!

**Comment by ocornut** [comment]
This is not supported. Example are disabling this:

https://github.com/ocornut/imgui/blob/docking/examples/example_win32_directx9/main.cpp#L58
```cpp
    // When viewports are enabled we tweak WindowRounding/WindowBg so platform windows can look identical to regular ones.
    ImGuiStyle& style = ImGui::GetStyle();
    if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
    {
        style.WindowRounding = 0.0f;
        style.Colors[ImGuiCol_WindowBg].w = 1.0f;
    }
```

This has already been discussed in #5852 #4180

(Ditto with Docking: #6151 #5527 for this one the fix may be easier. For viewports much more backend work https://github.com/ocornut/imgui/issues/4180#issuecomment-851551400)
