### ISSUE TITLE
Overlapped/Nested button not receiving any events

### ISSUE THREAD

**Issue by mungaihehe** [ocornut/imgui#6303]
**Version/Branch of Dear ImGui:**

Version: 1.89.5 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

**My Problem**
![nested buttons](https://user-images.githubusercontent.com/46344262/230004168-d33edeff-7b71-461a-a01c-9c462d486605.jpg)

The inner button (or input text) isn't receiving any mouse events

Is there any way to have a nested button that can be activated? 

Thanks in advance

**Comment by emoon** [comment]
Without you showing any of your code it's hard to say, but make sure to validate against this https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-why-is-my-widget-not-reacting-when-i-click-on-it

**Comment by ocornut** [comment]
See this comment https://github.com/ocornut/imgui/issues/3909#issuecomment-799328231
About using `SetItemAllowOverlap()` and overlapping mode.
By default, the first submitted widget gets mouse hit, with AllowOverlap mode that order is reversed.

**Comment by ocornut** [comment]
@mungaihehe sorry for late answer. A behavior change in 1.89 changed this. See https://github.com/ocornut/imgui/issues/3909#issuecomment-799328231
At the moment you need to also pass `ImGuiButtonFlags_AllowItemOverlap` to `InvisibleButton()` to get this to work.

**Comment by ocornut** [comment]
This is now fixed but required an API change, see https://github.com/ocornut/imgui/issues/6512#issuecomment-1611369198
