### ISSUE TITLE
How to Make Text in Button Black Bold 

### ISSUE THREAD

**Issue by MacQuant** [ocornut/imgui#6311]
Hello,

Could you please give me an example of how to make a text in Imgui::Button Black **Bold**. I know I think I have to change the style to make it BOLD but not sure how.

please!!

**Comment by ocornut** [comment]
You would currently need to load a different font (a bold one) and change the font when rendering the button. Aka, it is currently not particularly easy.

**Comment by MacQuant** [comment]
I see thank you, will do without until it’s easy I guess considering my skills using the library so far.
