### ISSUE TITLE
DirectX9: Font Render Issue

### ISSUE THREAD

**Issue by monyfolity** [ocornut/imgui#6312]
![изображение](https://user-images.githubusercontent.com/77878680/230717307-ec114949-d8eb-4312-bd8a-3df3cb77c141.png)
https://imgur.com/a/yVuBKud
50% of app users have this issue.
font initializing:
io.Fonts->AddFontFromFileTTF( "c:\\Windows\\Fonts\\msyh.ttc", 15.f, 0, ranges );
icons font initializing:
io.Fonts->AddFontFromMemoryTTF( ( void* )icons_binary, sizeof( icons_binary ), 16.f ); ( this renders as filled squares )

all users have msyh,ttc on pc, but some users get this error

**Comment by ocornut** [comment]
Tired of answering things which are amply answered in FAQs and docs.
