### ISSUE TITLE
ImGui text editor with all the gems -- discussion etc.

### ISSUE THREAD

**Issue by ChemistAion** [ocornut/imgui#6321]
@vdweller84 @slajerek @dfranx @arabine @santaclose @slajerek @justinbowes @shakfu
...and ofc @BalazsJako

Let's collect here all the ideas and approaches regarding the Editor thing... similarly to NodeEditor #306
No credits to me, I've @dfranx fork (https://github.com/BalazsJako/ImGuiColorTextEdit) with "all" the bugs fixed:
https://github.com/ChemistAion/ImTextEdit

@ocornut: ...waiting for your blessing, to move IT from Gallery

**Comment by ocornut** [comment]
Hello,
I am not sure we particularly need an extra thread for this,
But please post your link under BalazsJako's one in https://github.com/ocornut/imgui/wiki/Useful-Extensions#text-editors for visibility? I occasionally post them again in release notes.

> waiting for your blessing, to move IT from Gallery

I'm not sure I understand what you mean? blessing for what?

**Comment by ChemistAion** [comment]
@ocornut:
By using the term "blessing," I meant that we as a community are seeking your actual approval to move the editor from the Gallery section (similar to #306).

IMHO there is a need for dedicated thread for discussing ideas related to the Editor-thingy.
This would make it easier for people to contribute and collaborate on new features, and prevent unrelated issues from cluttering up the discussion. It would also provide a "centralized" location for people to find information and updates related to the Editor.

**Comment by LucLoubat** [comment]
Hi,
Just to flag that this version of the TextEditor won't work as is.
It is tight with SDL and use the legacy SDL_ScanCode for all heys related logic.
And there is a dependency need with SpvGenTwo for the SPIR-V language wicth is deeply implemented in the TextEditor.
Clear all this is just very annoying and burn the benefice of "all the bugs fixed".

**Comment by slajerek** [comment]
Thanks. This reminds me that I still haven't found any reliable, simple but also reasonably elegant text editor for ImGui... I've given a pass on this long time ago.

**Comment by ChemistAion** [comment]
@LucLoubat, @slajerek:
Here is @BalazsJako ImGuiColorTextEdit widget improved by @dfranx patches with some mods (e.g.: SPIR-V removed on my madX branch), enjoy: https://github.com/ChemistAion/ImTextEdit

**Comment by LucLoubat** [comment]
Hi @ChemistAion,
Sorry, i was forget to take look at the branches on your depo.
Thanks a lot for this additional notes and the other links, it is appreciate.

**Comment by LucLoubat** [comment]
@ChemistAion,
Sorry if i don't understand.
In you madX branch the SPIR-V continue to be in use and SPIRVParser.cpp just fail.
The #include "spvgentwo/Spv.h" is comment out but the complete code continue to have all the ref to spvgentwo::spv everywhere in it.
This simply don't work.
What do i miss ?

**Comment by ChemistAion** [comment]
@LucLoubat: 
Ohh...
I will check what's wrong there then (my branch).
I haven't worked with it in a while, but I'm pretty sure that "spvgentwo::spv" was the first thing I removed (or "disabled").
Perhaps there are some missing pushes; I will clean it up.

Give me one day tops - I need some time to switch back there.

**Comment by LucLoubat** [comment]
Hi @ChemistAion,
Thx for the answer.

Yes i know the BalazJako original one with limited functionalities but simple and fully functional.
It is the one i use as base to my version in which i have simply added Python in the language definition.

For sure i was interested with the dfranx version that add so much functionalities, but it is full of dependencies and so on.

It will be awesome if your vesion bring a light on this domain.
So thx, i am lokking arround for your cleaned version :)

**Comment by ChemistAion** [comment]
Hi @LucLoubat,
I just did a quick run on it (madX-branch as-is) and indeed, this version requires `[SpvGenTwo](https://github.com/rAzoR8/SpvGenTwo)` available within the project for **AutoCompletion**.

I've looked around but couldn't find one with **AutoCompletion** stripped down... sadly, I can't just jump into it now and remove that feature (to cut off SpvGenTwo dependency).

I will leave you with these suggestions for now:
* just add [SpvGenTwo](https://github.com/rAzoR8/SpvGenTwo) and you will get super nice tool-tips and auto-completion for GLSL and HLSL;
* remove AC containers and cleanup the code references it:
https://github.com/ChemistAion/ImTextEdit/blob/81ec756b5627dd351fe0dac26a7403982349df68/ImTextEdit.h#L454-L457

In regards of missing `_editor.hpp` - just remove it, this is a PCH leftover.

**Comment by LucLoubat** [comment]
Hi @ChemistAion
Thx for the answer and your time.
well, it look's like a back to the starting point to me.
