### ISSUE TITLE
Adding Underlines for Alt key shortcuts in ImGui File Menu

### ISSUE THREAD

**Issue by marzRX** [ocornut/imgui#6323]
**Version/Branch of Dear ImGui:**
Version: 1.89
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-end: GLFW + OpenGL3
Compiler: g++(MinGW)
OS: windows7

**My Question:**
I have a question about the file menu of ImGui. I understand how to use shortcut keys such as Ctrl+O and Ctrl+S, but I would like to know how to add an underline to the F in "File" and the E in "Edit" on the menu items. I would like to be able to open the file menu with Alt+F. In code, this feature can be achieved by writing "&File" or "&Edit". How can I represent this feature in ImGui?

**Comment by ocornut** [comment]
It is not currently possible other than yourself manually drawing a line (which involve calculating position of a given character).
This will be part of work for #456 but not currently done and if we adopt Windows's convention we may need low-level support in the text rendering routines.

**Comment by marzRX** [comment]
Thank you for your response. I understand it is not currently supported.
I've seen #126 before, though it's also linked from #456. So, I just wondered if that would allow me to do it, so I asked.  :)

**Comment by ocornut** [comment]
FYI this is in my checklist for the new text functions I've been writing (I put a few weeks of work on them several months ago but then had to prioritize other things). 

If we decide to restrict that feature to MenuItem inside menus, we can easily do some adhoc parsing there and it doesn't even need to be super-efficient, but my hope was that this could ideally be supported more globally (e.g. `ImGui::Button("&Save");` in a regular window) where it would need a little bit more low-level system. Ideally at the same time we perform a CalcTextSize() for layout we extract this data. It also means we need an optimal scheme for still allowing a `&` to be expressed e.g. `\\&` or `&&` before a letter.

**Comment by marzRX** [comment]
Thank you for sharing this information. I am not in a hurry. I am looking forward to the new text functions, including the implementation of the underlined Alt key shortcuts. 

Recently, I've noticed that some applications do not support Alt key shortcuts. I personally find them very useful and convenient, as I use them quite often.
