### ISSUE TITLE
Cannot enter text in editor with 1.89.3

### ISSUE THREAD

**Issue by leiradel** [ocornut/imgui#6324]
**Version/Branch of Dear ImGui:**
**Back-end/Renderer/Compiler/OS**

```
Dear ImGui 1.89.3 (18930)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1933
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_sdl2
io.BackendRendererName: imgui_impl_opengl2
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.DisplaySize: 1536.00,801.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

I have a terminal widget that I use as a Lua REPL inside my application, [ImGuiAl::Terminal](https://github.com/leiradel/ImGuiAl/tree/master/term). I also use [ImGuiColorTextEdit](https://github.com/BalazsJako/ImGuiColorTextEdit) to allow the user to write more complex Lua code that needs some iterations to get right, as doing this in the REPL is cumbersome. The application is very simple for now:

![image](https://user-images.githubusercontent.com/357536/231549303-3c7cd790-bf93-4193-b954-348c7bce83f0.png)

I've used these two together previously without problems, but as of Dear ImGui version 1.89.3, I started having an input issue.

I can write text to the editor without problems, but as soon as I enter commands in the input text, the editor won't accept input anymore. It accepts arrows and control commands, but when it comes to check other keys with `io.InputQueueCharacters.empty()`, it's always empty and no characters can be entered in the editor. The input text continues to work without issues.

Version 1.89.2 does **not** have the issue, it was introduced in 1.89.3. I've found that if I change this line in `imgui_impl_sdl2.cpp`

```cpp
io.SetPlatformImeDataFn = ImGui_ImplSDL2_SetPlatformImeData;
```

to set the function to `nullptr`, input works just fine.

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
        if (ImGui::Begin("Editor")) {
            static TextEditor editor;
            editor.Render("Editor");
        }

        ImGui::End();

        if (ImGui::Begin("REPL")) {
            static char buffer[256];
            ImGui::InputText("Command", buffer, sizeof(buffer));
        }

        ImGui::End();
```

Thanks in advance.

**Comment by ocornut** [comment]
Thanks! we stumbled on this last week and fixed it with commit a7703fe6f74a78db58040813f9baae66b4fd053d so it's already fixed in last version.

**Comment by leiradel** [comment]
Oh nice! Thanks for the prompt response!

**Comment by ocornut** [comment]
Sorry having you fill that issue. Not sure if you had a chance to search for e.g. "SetPlatformImeDataFn" but I feel github could do better at exposing closed issues by default. I'm improving the label of both issues for increased discoverability.

**Comment by leiradel** [comment]
That's totally fine, I should've tried to search for closed issues after finding about `SetPlatformImeDataFn`.
