### ISSUE TITLE
GUI Turns black on resize

### ISSUE THREAD

**Issue by NicholasDrian** [ocornut/imgui#6330]
GL Vendor            : ATI Technologies Inc.
GL Renderer          : AMD Radeon(TM) Graphics
GL Version (string)  : 4.6.14761 Compatibility Profile Context 21.30.40.04 30.0.13040.4003
GLSL Version         : 4.60
OS: Windows11
Branch: Master (Checked out about 6 weeks ago)

On the fourth time that I resize the glfw window, the GUI goes black like this:

<img width="581" alt="imgui_bug" src="https://user-images.githubusercontent.com/87615169/231988730-9affd8b2-5904-47b2-b78a-81cb0a2be038.png">

When I try to resize my framebuffer using glfw's resize callback, the GUI goes black on the first resize. Any ideas about what the issue is? Pease let me know if you have any questions about details.

Thanks!

**Comment by ocornut** [comment]
This is likely not a Dear ImGui issue.
Please refer to provided example_glfw_opengl3/ app to confirm that it works without an issue.
Then carefully compare your app code to `example_glfw_opengl3/` and you'll likely find a clue toward your issue. But generally we can't be debugging people's own graphics app here I'm afraid :(

**Comment by imisumi** [comment]
I had the same issue that when I resized my framebuffer all docking panels would turn black, I found out that when I call ImGui_ImplOpenGL3_CreateFontsTexture(); at the end of my framebuffer resize function it all rendered properly again. I have no clue why but the panels rendered as normal again :)
