### ISSUE TITLE
Imgui OpenGL3 backend calls ImGui_ImplOpenGL3_CreateFontsTexture only once

### ISSUE THREAD

**Issue by quinor** [ocornut/imgui#6336]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: v1.89.4
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Linux

**My Issue/Question:**

I'm trying to reload the font while application is running (before calling `ImGui::NewFrame()` )"
```cpp
io.Fonts->ClearFonts();
io.Fonts->AddFontFromFileTTF("misc/DejaVuSans.ttf", font_size);
````

When I try that, the application fails on an assert:

```
main: /home/quinor/kody/tsparter/build/_deps/imgui-src/imgui.cpp:8976: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `g.IO.Fonts->IsBuilt() && "Font Atlas not built! Make sure you called ImGui_ImplXXXX_NewFrame() function for renderer backend, which should call io.Fonts->GetTexDataAsRGBA32() / GetTexDataAsAlpha8()"' failed.
```

What happens is, `ImGui_ImplOpenGL3_NewFrame` only reloads fonts (`ImGui_ImplOpenGL3_CreateFontsTexture`) first time NewFrame is called because of logic [here](https://github.com/ocornut/imgui/blob/1ebb91382757777382b3629ced2a573996e46453/backends/imgui_impl_opengl3.cpp#L366)

Is this a bug or intended behavior (ie. I'm not supposed to reload fonts while running)?

**Comment by ocornut** [comment]
We are working on a standardization of font reload mechanism accross all backends but until then you can call that function yourself again if needed.

**Comment by quinor** [comment]
I already hacked around it for my usecase. I'm waiting for the new features!

**Comment by ocornut** [comment]
Your problem was calling ClearFonts() without ClearInputData(). Same as https://github.com/ocornut/imgui/discussions/8174.
I am fixing this now by making ClearFonts() automatically call ClearInputData(), as it doesn't make sense to only clear output fonts, and ClearFonts() is a misleading name.
