### ISSUE TITLE
Removing bullets on TreeNodeEx nodes

### ISSUE THREAD

**Issue by Cthutu** [ocornut/imgui#634]
Hi,

I've added a new flag to ImGui called `ImGuiTreeNodeFlags_NoBullet` that removes the bullet.  I think it's an important feature since the bullet is not necessarily functional like the arrow.  It disables the `RenderBullet()` call in `TreeNodeBehavior()`.  I had my own TreeNodeEx function to implement a folders/file view (think resource view in Unity) and I updated to see your new version.  These bullets suddenly appeared and it looked ugly to me.

I tried to create a pull request but it failed (permissions problem).

What do you think of the idea?

**Comment by ocornut** [comment]
We already have an open topic for exactly this, let's preferably keep it there. #581 

Puzzled about the permissions problem, normally anyone can submit a PR. What gave you permission problem, github website?

**Comment by Cthutu** [comment]
Yes, the github website.  Should I fork imgui on github first and upload
the branch and try it through github?

**Comment by ocornut** [comment]
This is how it works normally, yes. However if you are stuck for that feature the PR is an obvious two lines so it's ok to skip this one. But it would have to wait until my mind is back on tree stuff :)
