### ISSUE TITLE
Can't correctly position Windows when dealing with the INI settings myself

### ISSUE THREAD

**Issue by leiradel** [ocornut/imgui#6340]
**Version/Branch of Dear ImGui:**
**Back-end/Renderer/Compiler/OS**

```
Dear ImGui 1.89.5 (18950)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1933
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl2
io.BackendRendererName: imgui_impl_opengl2
io.ConfigFlags: 0x00000040
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C06
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.DisplaySize: 1536.00,801.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

I'm trying to load INI settings myself, but I can't seem to find the correct place to do it. When I leave `io.IniFilename` alone, or set it to `nullptr` but call `ImGui::LoadIniSettingsFromDisk("imgui.ini");` before entering the main loop (before any drawing takes place), windows positions are correctly restored:

![ManuallyPositioned](https://user-images.githubusercontent.com/357536/232531626-03a33a7e-7c8f-45c7-96bd-48c4cde9e180.png)

However, when I set `io.IniFilename` to `nullptr`, **don't** call `ImGui::LoadIniSettingsFromDisk("imgui.ini");`, and call `ImGui::LoadIniSettingsFromMemory(imgui.c_str(), imgui.length());` myself after opening a "project" for my application that embeds the INI file, this is what I get:

![PositionedByIni](https://user-images.githubusercontent.com/357536/232532531-7ddad76b-5d65-467c-a495-35694fe97f91.png)

(Window1 is behind Window2.)

Do I have to tear down ImGui and re-initialize it when opening a project with the embedded INI? Or am I missing something easier?

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
    ImGui::Begin("Window1"); ImGui::End();
    ImGui::Begin("Window2"); ImGui::End();
    ImGui::Begin("Window3"); ImGui::End();
    ImGui::Begin("Window4"); ImGui::End();
```

This is my project file with the embedded INI:

```json
{"views":[],"imgui":"[Window][DockSpaceViewport_11111111]\nPos=0,20\nSize=1536,781\nCollapsed=0\n\n[Window][Window1]\nPos=0,20\nSize=1195,260\nCollapsed=0\nDockId=0x00000003,0\n\n[Window][Window2]\nPos=0,20\nSize=1195,260\nCollapsed=0\nDockId=0x00000003,1\n\n[Window][Window3]\nPos=0,282\nSize=1195,519\nCollapsed=0\nDockId=0x00000004,0\n\n[Window][Window4]\nPos=1197,20\nSize=339,781\nCollapsed=0\nDockId=0x00000002,0\n\n[Window][Debug##Default]\nPos=60,60\nSize=400,400\nCollapsed=0\n\n[Docking][Data]\nDockSpace     ID=0x8B93E3BD Window=0xA787BDB4 Pos=0,20 Size=1536,781 Split=X\n  DockNode    ID=0x00000001 Parent=0x8B93E3BD SizeRef=1195,781 Split=Y\n    DockNode  ID=0x00000003 Parent=0x00000001 SizeRef=1195,260 CentralNode=1 Selected=0xCF4A9051\n    DockNode  ID=0x00000004 Parent=0x00000001 SizeRef=1195,519 Selected=0xF22AB9E1\n  DockNode    ID=0x00000002 Parent=0x8B93E3BD SizeRef=339,781 Selected=0x400A65F1\n\n"}
```

(The `views` array would contain the Windows properties like the contents of editors, terminal command history etc., but it's not important here.)

The embedded reads as this:

```ini
[Window][DockSpaceViewport_11111111]
Pos=0,20
Size=1536,781
Collapsed=0

[Window][Window1]
Pos=0,20
Size=1195,260
Collapsed=0
DockId=0x00000003,0

[Window][Window2]
Pos=0,20
Size=1195,260
Collapsed=0
DockId=0x00000003,1

[Window][Window3]
Pos=0,282
Size=1195,519
Collapsed=0
DockId=0x00000004,0

[Window][Window4]
Pos=1197,20
Size=339,781
Collapsed=0
DockId=0x00000002,0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Docking][Data]
DockSpace     ID=0x8B93E3BD Window=0xA787BDB4 Pos=0,20 Size=1536,781 Split=X
  DockNode    ID=0x00000001 Parent=0x8B93E3BD SizeRef=1195,781 Split=Y
    DockNode  ID=0x00000003 Parent=0x00000001 SizeRef=1195,260 CentralNode=1 Selected=0xCF4A9051
    DockNode  ID=0x00000004 Parent=0x00000001 SizeRef=1195,519 Selected=0xF22AB9E1
  DockNode    ID=0x00000002 Parent=0x8B93E3BD SizeRef=339,781 Selected=0x400A65F1
```

Thanks in advance for any insights!

**Comment by ocornut** [comment]
When/where are you calling LoadIniSettingsFromMemory() ?
I believe it should work when called BEFORE NewFrame() otherwise the docking node won’t be existing when you call Begin() after the ini change.

What seems to happen in your case is the window get undocked. You can use Metrics>Tools>DebugLog>Docking to get a log of why a window is undocked.

**Comment by leiradel** [comment]
> When/where are you calling LoadIniSettingsFromMemory() ?

I'm calling it in a menu handler, meaning it's in between `NewFrame()` and `Render()`. However, in the real application the windows are created in the same function `LoadIniSettingsFromMemory()` is called, so after everything is setup a `Render()` will be called, and then a `NewFrame()`, and **then** the loaded windows will have their `Begin()` called the first time.

Maybe I have to do all that outside `NewFrame()` and `Render()`? I'll make a test.

> What seems to happen in your case is the window get undocked. You can use Metrics>Tools>DebugLog>Docking to get a log of why a window is undocked.

Ah nice, will try.

Thanks for the prompt reply.

**Comment by ocornut** [comment]
Some elements of the docking logic are processed in NewFrame() so generally it is better to defer that ini reload before it.

**Comment by leiradel** [comment]
The windows are correctly positioned and docked when I load the INI contents outside `NewFrame()` and `Render()`, thanks!
