### ISSUE TITLE
trouble with sdl2 directly in code (not install in system)

### ISSUE THREAD

**Issue by wir19** [ocornut/imgui#6350]
g++ -o example_sdl2_sdlrenderer [...]
/usr/bin/ld: imgui_impl_sdlrenderer.o: in function `ImGui_ImplSDLRenderer_RenderDrawData(ImDrawData*)':
imgui_impl_sdlrenderer.cpp:192: undefined reference to `SDL_RenderGeometryRaw'
collect2: error: ld returned 1 exit status

i use ~/SDL2/sdl2-config  and have trouble with compiling sdl2 renderer example
all compiling corectly but not linked

**Comment by ocornut** [comment]
If you have undefined reference to a function it means you are not linking with its library, or linking with a version that doesn't have the function.
`SDL_RenderGeometryRaw()` was introduced in SDL 2.0.18.
If you can **COMPILE** it means you are using header from SDL 2.0.18+
If you cannot **LINK** it means you are probably using an older lib.

This is not a dear imgui issue.

**Comment by wir19** [comment]
~/SDL2/sdl2-config --version
2.26.5

no I have new library

**Comment by ocornut** [comment]
Well you can see this question is unrelated to Dear ImGui either way. We are not able to debug the build system of everyone.
