### ISSUE TITLE
SliderFloat Formatting as Percentage Help

### ISSUE THREAD

**Issue by 0aspect** [ocornut/imgui#6355]
Version/Branch of Dear ImGui:

Version: v1.80 WIP
Branch: master

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Operating System: Windows 10

My Issue/Question:

This isnt exactly a issue but may be a dumb question but is there a format to strip the leading 0 from a float on a ImGui::SliderFloat? I assumed it would be a formatting flag but I cannot seem to find one that fits my needs. What I want to do is make my sliders range from 0.01f to 1.0f and have it display as a percentage where 1.f displays as 100% and 0.01f displays as 1%. Is there anything like that in ImGui?

**Comment by 0aspect** [comment]
I have solved this using the following code:

```
char value_buf[64];
const char* value_buf_end = value_buf + DataTypeFormatString(value_buf, IM_ARRAYSIZE(value_buf), data_type, p_data, format);

    if (strlen(value_buf) >= 2) {
        // check for leading zero and remove it if it exists
        if (value_buf[0] == '0' && value_buf[1] != '.') {
            memmove(value_buf, value_buf + 1, strlen(value_buf));
        }

        // convert to whole percentage
        float value_f = (float)atof(value_buf);
        int value_i = (int)(value_f * 100.0f + 0.5f);
        sprintf(value_buf, "%d%%", value_i);
        value_buf_end = value_buf + strlen(value_buf);

        // check for '00%' and remove the second zero if necessary
        if (value_buf[0] == '0' && value_buf[1] == '0' && value_buf[2] == '%') {
            memmove(value_buf + 1, value_buf + 2, strlen(value_buf) - 2 + 1); // +1 to include the null terminator
            value_buf_end--;
        }
    }

    RenderTextClipped(ImVec2(grab_bb.Min.x - 15, total_bb.Min.y + 8), ImVec2(grab_bb.Max.x + 14, total_bb.Min.y + 20), value_buf, value_buf_end, NULL, ImVec2(0.5f, 0.5f));
```
This can be implemented by adding it into the ImGui::SliderScalar in imgui_widgets.cpp as seen in the image I have attached but I have made a widget specifically for this.
I am unsure if their is a better way to do this but I am on a time constraint so this will do for now. 

![image](https://user-images.githubusercontent.com/96223830/233538463-537bb92c-9fcd-4eab-84b3-e4215b9aa2c2.png)
Results: 
![image](https://user-images.githubusercontent.com/96223830/233540095-47e786fa-2088-4b68-b60d-ba466625f55d.png)

**Comment by GamingMinds-DanielC** [comment]
You could just use the standard widget, but give it a preformatted string as the format string. Just make sure that you escape your percent sign as `%%`, then that string should be displayed exactly as you formatted it beforehand. So basically format first with `"%d%%%%"` -> `"42%%"` -> displayed as `42%`.

**Comment by ocornut** [comment]
Yes you absolutely shouldn’t modify internal code for that purpose. When you can do:

float f = MyValue * 100;
if (SliderFloat(…., &f, “%.0f%%))
     MyValue = f / 100.0f:

And then you can wrap this into a small helper called eg: SliderPercent() if you like.
