### ISSUE TITLE
DX11 example and ID3D11DepthStencilState 

### ISSUE THREAD

**Issue by josiahmanson** [ocornut/imgui#636]
When I added ImGui to my program, I was confused because a dark window appeared but with no contents. I tracked this down to being that I had set the depth comparison to LESS, and in ImGui, window contents are drawn at the same depth and therefore subsequent draws failed the depth test. I suggest creating a ID3D11DepthStencilState in the implementation source and doing the same saving and restoring of state for the depth stencil as is done for other state. I have made this modification and could make a pull request if you want.

**Comment by ocornut** [comment]
Hello,
You are right this is missing from both DX10 and DX11 example (which are very similar). A pull request to fix it would be good. I assume the function to call is `OMSetDepthStencilState`.

It is actually surprising that it hasn't been caught before. I assume people using the DX11 example code (perhaps a minority) just disabled z-testing or haven't raised the issue.

Thanks!

**Comment by josiahmanson** [comment]
Yes, `CreateDepthStencilState` to make your own during initialization. During render, `OMGetDepthStencilState` into a temporary, `OMSetDepthStencilState` with your own state, and `OMSetDepthStencilState` to restore the temporary. :-)

**Comment by ocornut** [comment]
If you have the code I'll take a PR otherwise will look at it later.

**Comment by josiahmanson** [comment]
I have some code that I can give you tomorrow.

**Comment by ocornut** [comment]
Applied #640, thanks!
