### ISSUE TITLE
Compilation issue  example_glut_opengl2

### ISSUE THREAD

**Issue by daniel-petrovic** [ocornut/imgui#6360]
**System:** 
Linux 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 GNU/Linux

**Compiler:** 
g++ (GCC) 11.3.0

**Issue:**
Compiling **example_glut_opengl2**

Running 'make' fails:

![image](https://user-images.githubusercontent.com/1634408/233824556-26c48c67-7a5e-44fc-9478-49b8a660253d.png)

g++ -std=c++11 -I../.. -I../../backends -g -Wall -Wformat -c -o main.o main.cpp
main.cpp: In function 'void MainLoopStep()':
main.cpp:135:79: error: 'io' was not declared in this scope
  135 |         ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / io.Framerate, io.Framerate);
      |                                                                               ^~
make: *** [Makefile:60: main.o] Error 1

Fixed  in PR #6361

**Comment by ocornut** [comment]
Thank you! Did a slight refactor of that printout recently and got mislead by the local in narrower scope. May want to add this example to CI as well.
