### ISSUE TITLE
Change TreeNode hovered effect size

### ISSUE THREAD

**Issue by jkatsanis** [ocornut/imgui#6363]
Hello,
is there any way of reducing the hovered effect, size of a TreeNode built in. So when you hover over a tree node it fills in the complete region available with the hover effect. I kind of added a feature by peaking into the ``ImGui::TreeNodeBehaviour();`` function and changing the following code: `` frame_bb.Max.x = window->WorkRect.Max.x - g.NextItemData.Width`` .  But this thing that i added is not working very well. Thats why i wanted to create a Issue. 
Thanks for the awesome library

**Comment by ocornut** [comment]
Why do you need to do that, what's the context?

**Comment by jkatsanis** [comment]
Okay so Im programming a game engine and there is a parent child thing with game objects. And when you drag a child (``ImGui::MenuItem``) under a ``ImGui::MenuItem`` (in this case the parent) it becomes a ``ImGui::"TreeNode`` node and the child stays a menu item. So you can click at the menu item and it gets selected and you can edit it in the editor and stuff. But when you want to select a parent (TreeNode)   it collapses the tree since you are clicking on the TreeNode. So i found out if the hover effect is smaller it won't collapse it and everything works fine

**Comment by ocornut** [comment]
I'm not sure I fully understand your message, but it sounds like maybe you want to use the `ImGuiTreeNodeFlags_OpenOnArrow` flag if you want to use the body/label of the tree-node for selection and the arrow for opening.

**Comment by jkatsanis** [comment]
Yes technically would this solve my problem, but this flag sounds like it just opens/collapse the tree when it's opened/closed it would just look better if the hover effect (in my case) would just be over the small little arrow.

**Comment by ocornut** [comment]
That's not possible without modifying the code, and I wouldn't recommend it. 
The hover effect will always show behind subsequent items.

**Comment by jkatsanis** [comment]
I did actually modify the code to make it like half work but I just wanted to know if there is a built in way for this:

``` 
Func
{
   ImGui::SetNextItrmWidth(200)
  // imagine if the ContentAvailable is 800px, the width will be 600, that's why I said "it's working half" 
   //Tree node with 600px hovered effect 
   ImGui::TreeNode() 
} 
ImGui::TreeNodeBehaviour


frame_bb.Max.x = window->WorkRect.Max.x - g.NextItemData.Width
```

**Comment by ocornut** [comment]
It's not supported and there's no intent to support it presently, sorry.

**Comment by jkatsanis** [comment]
No problem :D
Thank you for your time, I really appreciate it.
Also sorry for wasting your time. Maybe leave this issue open and when someone has this problem they should find this issue and do the same thing I did.

**Comment by ocornut** [comment]
We close issues when there's nothing to act on, it is always recommended to search closed issues when searching for information.

Because what you are doing is really non-standard, it is possible that in some time you will decide to revert a more standard approach.

**Comment by ocornut** [comment]
Btw looking at your hack attempt you seems to be "inverting" the purpose of Width.

```cpp
frame_bb.Max.x = window->WorkRect.Max.x - width;`
```
Should be more like:
```
frame_bb.Max.x = ImMin(frame_bb.Min.x + width, window->WorkRect.Max.x);
```
