### ISSUE TITLE
combobox in the TabItem has an error

### ISSUE THREAD

**Issue by ashe27** [ocornut/imgui#6364]
The first parameter of BeginCombo cannot be left blank, otherwise it will not pop up correctly under the TabItem. I'm not sure if this is a bug.
```
if (ImGui::BeginTabItem("Test"))
{
    if (ImGui::BeginCombo("", "None"))
    {
        ImGui::EndCombo();
    }
    ImGui::EndTabItem();
}
```

**Comment by cfillion** [comment]
It needs a non-empty label to compute the combo box's unique ID. The label can be hidden by prepending `##` to it: `ImGui::BeginCombo("##my_combo", ...)`.

https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

**Comment by ashe27** [comment]
> It needs a non-empty label to compute the combo box's unique ID. The label can be hidden by prepending `##` to it: `ImGui::BeginCombo("##my_combo", ...)`.
> 
> https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

thanks
