### ISSUE TITLE
imgui_impl_dx12.cpp - PFN_D3D12_SERIALIZE_ROOT_SIGNATURE not declared.

### ISSUE THREAD

**Issue by Red-Or-Blue** [ocornut/imgui#6372]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx12.cpp + imgui_impl_win32.cpp
Compiler: g++
Operating System: Windows

**My Issue:**

PFN_D3D12_SERIALIZE_ROOT_SIGNATURE definition does not exist.

I needed to add the following for it to work:
        `typedef HRESULT(WINAPI * PFN_D3D12_SERIALIZE_ROOT_SIGNATURE) (const D3D12_ROOT_SIGNATURE_DESC *pRootSignature, D3D_ROOT_SIGNATURE_VERSION Version, ID3DBlob **ppBlob, ID3DBlob **ppErrorBlob);`

**Comment by Red-Or-Blue** [comment]
Duplicated and intended it seem.

**Comment by ocornut** [comment]
See #4604 #4594
But I am surprised you suggest that merely adding a forward declaration worked for you. Did it link and run?
If so we should be doing that I guess.
