### ISSUE TITLE
table crash

### ISSUE THREAD

**Issue by mumin16osx** [ocornut/imgui#6379]
Version: 1.89
Branch: main

When i minimize window(i use sdl2), i have error: Assertion failed: table != 0 && "Only call EndTable() if BeginTable() returns true!", file C:/Users/x64/VSCodeProjects/third_party/include/imgui/imgui_tables.cpp, line 1237

**Comment by ocornut** [comment]
There's literally a likely solution to your problem spelled out in the error message, and you are not providing a repro. We can't magically guess what's in your code.

**Comment by mumin16osx** [comment]
https://www.youtube.com/watch?v=KlibzU3yW_Y

**Comment by GamingMinds-DanielC** [comment]
That's just a video version of stating what the assertion says. No code, no repro. Just check your code and make sure that you follow the instructions spelled out in the assertion.
