### ISSUE TITLE
ImGui::CalcTextSize does not seem to be able to properly Calc size when the font size is too small(or big)？

### ISSUE THREAD

**Issue by BaiFeng666** [ocornut/imgui#6380]
Version: 1.89
Branch: mian

`// Calculate text size. Text can be multi-line. Optionally ignore text after a ## marker.
// CalcTextSize("") should return ImVec2(0.0f, g.FontSize)
ImVec2 ImGui::CalcTextSize(const char* text, const char* text_end, bool hide_text_after_double_hash, float wrap_width)
`
ImGui::CalcTextSize does not return the correct result when I am calculating the size of multiple lines of text. I think it is because this not using the font size as a parameter to calculate?（Maybe we can optimize this algorithm in the future
）

There may be another way. I don't know. Any help would be appreciated

**Comment by ocornut** [comment]
It should work. Being an ImGui:: function it use the current bound font size.
Please provide a minimum repro if you claim there’s an issue (it is requested by issues guidelines). Thank you.

**Comment by ocornut** [comment]
Never mind, sorry but #1586
