### ISSUE TITLE
PushStyleColor() Doesn't Work with Checkmarks

### ISSUE THREAD

**Issue by muellerryan** [ocornut/imgui#6383]
**Version/Branch of Dear ImGui:** v1.89

Version: v1.89 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: Visual C++20
Operating System: Win11

**My Issue/Question:**

I had some issues trying to use PushStyleColor() and PopStyleColor() with Checkboxes, specifically changing the checkmark color. The checkmark disappears when Pushing/Popping. I have successfully been able to change the checkmark color with help from https://github.com/ocornut/imgui/issues/1486, but it would be useful to just use the Push/PopStyleColor() functions instead of manually changing the ImGui::Style.  Since I have already solved this in a roundabout way, I just want to make sure that this is the most elegant way to achieve what I'm trying to do. 

With the manual code:
![image](https://user-images.githubusercontent.com/43647235/235168818-6fbef16b-8ed7-4846-8aea-e30c4db3ba04.png)
With Push/PopStyleColor():
![image](https://user-images.githubusercontent.com/43647235/235169084-00c5ebd4-0b37-4092-b5ec-7ff5ed9f415d.png)

Manual code:
```			
ImGui::Begin("Checkbox");
static bool checkMark = true;
ImGuiStyle& style = ImGui::GetStyle();
ImVec4 oldCheck = style.Colors[ImGuiCol_CheckMark];
style.Colors[ImGuiCol_CheckMark] = style.Colors[ImGuiCol_NavHighlight];
ImGui::Checkbox("Checkbox", &checkMark);
style.Colors[ImGuiCol_CheckMark] = oldCheck;

if (checkMark)
{
    ImGui::SameLine();
    ImGui::Text("CHECKED!");
}
ImGui::End();
```

Push/PopStyleColor() code:
```				
ImGui::Begin("Checkbox");
static bool checkMark = true;
ImGui::PushStyleColor(ImGuiCol_CheckMark, ImGuiCol_NavHighlight);
ImGui::Checkbox("Checkbox", &checkMark);
ImGui::PopStyleColor();

if (checkMark)
{
    ImGui::SameLine();
    ImGui::Text("CHECKED!");
}
ImGui::End();
```

**Comment by ocornut** [comment]
`ImGui::PushStyleColor(ImGuiCol_CheckMark, ImGuiCol_NavHighlight);`

This is incorrect, you are passing a enum which is interpreted like a U32 packed color.

I think you want to do:

`ImGui::PushStyleColor(ImGuiCol_CheckMark, style.Colors[ImGuiCol_NavHighlight];`

Check the prototypes for this:

```cpp
void          PushStyleColor(ImGuiCol idx, ImU32 col);                        // modify a style color. always use this if you modify the style after NewFrame().
void          PushStyleColor(ImGuiCol idx, const ImVec4& col);
```

**Comment by muellerryan** [comment]
This was it, thank you for pointing out my mistake.  I was referencing a different part of my code that handled everything as straight ImVec4s and could have sworn for some reason the enums were ImVec4s - apologies.
