### ISSUE TITLE
Drawing OpenGL on main GLFW window not working when using Dear ImGui

### ISSUE THREAD

**Issue by keince** [ocornut/imgui#6389]
**Version/Branch of Dear ImGui:**

Version: 1.89.2 WIP
Branch: Viewport WIP branch, Docking WIP branch

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: Visual Studio 2019
Operating System: Windows 10

**My Issue/Question:**

I have a simple glfw app that I'm using to draw a line on the main window using OpenGL. It works fine until I introduce Dear ImGui. Once I add a simple Dear ImGui window for display, the OpenGL line no longer draws on the main window. If I move the call `drawOGL(...)` in the code below past the `ImGui::ImplOpenGL3_RenderDrawData(ImGui::GetDrawData())` call, then the Dear ImGui window disappears and my OpenGL line displays. 

Can someone tell me how I can draw both OpenGL in the main window and the Dear ImGui windows at the same time so they both show up?

**Screenshots/Video**

I cannot provide screenshots or video because the app is running on a secure network/machine.

**Standalone, minimal, complete and verifiable example:**
```
#include <GLFW/glfw3.h>
#include <imgui.h>
#include <imgui_impl_glfw.h>
#include <imgui_impl_opengl3.h>

void drawOGL(GLFWwindow* window)
{
    int displayW, displayH;
    glfwGetFramebufferSize(window, &displayW, &displayH);
    glViewport(0, 0, displayW, displayH);
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    glOrtho(0, displayW, 0, displayH, 0, 1);

    glClearColor(0, 0, 0, 1);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    glColor4f(1, 1, 1, 1);
    glBegin(GL_LINES);
    glVertex2f(50, 80);
    glVertex2f(20, 20);
    glEnd();
}

auto main() -> int
{
    if (!glfwInit())
        return -1;

    int mainWinWidth = 800;
    int mainWinHeight = 600;

    GLFWwindow* mainWindow = glfwCreateWindow(mainWinWidth, mainWinHeight, "grafix windo", nullptr, nullptr);
    if (!mainWindow)
    {
        glfwTerminate();
        return -1;
    }

    glfwMakeContextCurrent(mainWindow);
    glfwSwapInterval(1);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
    ImGui::StyleColorsDark();
    
    ImGui_ImplGlfw_InitForOpenGL(mainWindow, true);
    ImGui_ImplOpenGL3_Init();

    while (!glfwWindowShouldClose(mainWindow))
    {
        glfwPollEvents();

        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplGlfw_NewFrame();
        ImGui::NewFrame();
        ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());

        ImGui::Begin("simple window");
        ImGui::End();

        drawOGL(mainWindow);

        ImGui::Render();
        ImGui::ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

        glfwSwapBuffers(mainWindow);
    }

    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();

    glfwDestroyWindow(mainWindow);
    glfwTerminate();

    return 0;
}
```

**Comment by ocornut** [comment]
Your drawOGL() function is using legacy GL features which I am not sure are well supported by drivers when using more modern features alongside them.
Try with the imgui_impl_opengl2 backend first.

**Comment by keince** [comment]
Thank you for the feedback.

Per your recommendation, I switched to using the imgui_impl_opengl2 backend. The results are the same. No OpenGL line drawn in the parent window. Just the Dear ImGui window on top of the parent GLFW window.

**Comment by GamingMinds-DanielC** [comment]
If possible on the secure machine, you could try to capture and analyze the exact graphics states with RenderDoc. I don't know if support goes back to those old drawing commands, but that tool is always my first stop when I need to check issues with rendering.

Otherwise, you could flush at the end of the frame, introduce wait times (slow down frame rate so that you can see every individual frame), skip ImGui rendering for the first few frames. The interesting thing then would be: is there a single frame where both your line and the ImGui window is visible?

Also, moving your `drawOGL`-call past the ImGui rendering would "hide" the window since that call contains a clear.

**Comment by keince** [comment]
Thanks to all who have provided input thus far.

I was able to isolate the problem.

In the code above, I did the following changes...

1. The first thing I did was to move the `drawOGL(mainWindow)` call after `ImGui::Render()` but before `ImGui_ImpleOpenGL3_RenderDrawData(ImGui::GetDrawData())`. This did not fix the issue.

2. The next thing I did was to comment out the call `ImGui::DockSpaceOverViewport(ImGui::GetMainViewport())`. Once I did this, everything started to work as expected.  The OpenGL line rendered in the parent window along with the Dear ImGui window.

Perhaps it is user error on my part on how to properly use this call? We need this call so we can dock the Dear ImGui window to the main parent window.

Any suggestions on the proper usage of `ImGui::DockSpaceOverViewport(...)` call so it doesn't break the rendering in the parent window?

**Comment by keince** [comment]
Just a follow-up to my previous post...

If I add the flag `ImGui::DockSpaceOverViewport(ImGui::GetMainViewport(), ImGuiDockNodeFlags_PassthruCentralNode)`, then everything works as it should...:)

**Comment by ocornut** [comment]
Ha! So it wasn’t a backend/GL issue at all! Apologies for the misleading conversation. Glad you solved it.

**Comment by keince** [comment]
I appreciate your help and feedback...:)
