### ISSUE TITLE
Undeclared identifier 'focused_window'

### ISSUE THREAD

**Issue by jo-codegirl** [ocornut/imgui#6391]
**Version/Branch of Dear ImGui:**

Version: 1.89.6 WIP
Branch: master (7c291ba3)

**Back-end**

Back-ends: imgui_impl_sdl3.cpp
Compiler: Android Studio Dolphin, SDK 32
Operating System: Ventura 13.3.1

**My Issue/Question:**

When building in Android, SDL_HAS_CAPTURE_AND_GLOBAL_MOUSE is set to 0. Later, in ImGui_ImplSDL3_UpdateMouseData, code is defined by this flag. A variable is not initialized in the #else so there is a build error when it is used:

/imgui/backends/imgui_impl_sdl3.cpp:460:35: error: use of undeclared identifier 'focused_window'

Also, see https://github.com/ocornut/imgui/issues/6386#issue-1689728091

**Screenshots/Video**

<img width="1013" alt="Screenshot 2023-05-02 at 6 11 51 AM" src="https://user-images.githubusercontent.com/103441421/235662718-0f8a5143-611a-42fb-b55b-5f09b02afa6f.png">

**Standalone, minimal, complete and verifiable example:** 
```
// I got it to compile in my local repo by setting focused_window to bd->window, is this desired initialization in this case?
SDL_Window* focused_window = bd->Window;
```

**Comment by ocornut** [comment]
Apologies, this was an overlook in this specific SDL3 backend condition. Pushed your fix as 5dc6013
