### ISSUE TITLE
Trouble trying to draw a rectangle

### ISSUE THREAD

**Issue by Lester702** [ocornut/imgui#6392]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui: 1.82 Release**

Version: 1.82
Branch: Release

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl.cpp _(or specify if using a custom engine/back-end)_
Operating System: Windows 10

**My Issue/Question:**

I'm trying to get a rectangle to draw and am using the demo window to guide me to just try and get something to draw before I make a more permanent implementation and I'm getting a exception thrown when trying to draw the rectangle

**Screenshots/Video**

![image](https://user-images.githubusercontent.com/63370028/235699037-ce947702-254b-4e34-9673-fcdcd083364c.png)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
This is in my draw function of my program

```
    static float sz = 36.0f;
    static float thickness = 3.0f;
    static int ngon_sides = 6;
    static bool circle_segments_override = false;
    static int circle_segments_override_v = 12;
    static bool curve_segments_override = false;
    static int curve_segments_override_v = 8;

    static ImVec4 colf = ImVec4(1.0f, 1.0f, 0.4f, 1.0f);
    const ImVec2 p = ImGui::GetCursorScreenPos();
    const ImU32 col = ImColor(colf);
    const float spacing = 10.0f;
    const ImDrawFlags corners_tl_br = ImDrawFlags_RoundCornersTopLeft | ImDrawFlags_RoundCornersBottomRight;
    const float rounding = sz / 5.0f;
    const int circle_segments = circle_segments_override ? circle_segments_override_v : 0;
    const int curve_segments = curve_segments_override ? curve_segments_override_v : 0;
    float x = p.x + 4.0f;
    float y = p.y + 4.0f;

    for (int n = 0; n < 2; n++)
    {
        float th = (n == 0) ? 1.0f : thickness;
        draw_list->AddNgon(ImVec2(x + sz * 0.5f, y + sz * 0.5f), sz * 0.5f, col, ngon_sides, th);                 x += sz + spacing;
    }
ImGui::Image((void*)(intptr_t)lemonStandInt, ImVec2(lemonStandW, lemonStandH));

    //Rendering
    ImGui::Render();
    glViewport(0, 0, (int)io.DisplaySize.x, (int)io.DisplaySize.y);
    glClearColor(clearCol_R, clearCol_G, clearCol_B, 255);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    
    calculateFps();

    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    SDL_GL_SwapWindow(window);```

**Comment by thedmd** [comment]
Your's `draw_list` appears to be `nullptr`. `ImGui::GetWindowDrawList()` will return `nullptr` if you're out of the scope of the window (aka. `ImGui::Begin()`/`ImGui::End()`).

Consider using `ImGui::GetForegroundDrawList()` or `ImGui::GetBackgroundDrawList()` to get draw list that does not require a window.

**Comment by ocornut** [comment]
Sorry but #1586 and this appear to be a C++ literacy question and there’s way too much random noise in the example, but most likely thedmd’s answer is right.
