### ISSUE TITLE
Set TabItem focus from TabBar

### ISSUE THREAD

**Issue by Spuckwaffel** [ocornut/imgui#6394]
Hey there, I was wondering if there's any way to set a Tab Item to focus/selected.
I just saw that it's possible to check if a Tab Item is selected (e.g ImGui::BeginTabItem), but haven't seen a way to select a specific tab by ID.
Any way to do this?
Thanks in advance.

**Comment by GamingMinds-DanielC** [comment]
Try adding the flag `ImGuiTabItemFlags_SetSelected` to `ImGui::BeginTabItem()` for the desired tab in the frame where you want to trigger the selection.

**Comment by Spuckwaffel** [comment]
Sorry for the late reply, but thank you very much! This solved my issue.
