### ISSUE TITLE
ImageButton does not respond to clicks

### ISSUE THREAD

**Issue by catal4n** [ocornut/imgui#6399]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.85

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui.cpp + imgui_demo.cpp + imgui_draw.cpp + imgui_impl_dx9.cpp + imgui_imp_win32.cpp + imgui_tables.cpp + imgui_widgets.cpp
Compiler: Visual Studio 2019
Operating System: Win 10

ImageButton loads the texture but button doesn't work when clicked. If i use the texture id from demo it's running.

**Screenshots/Video**

If i use the imagebutton from the example it runs great but if i try to load my texture, the texture is loaded correctly but button doesnt reponds to clicks, i tried to handle the cursor pos.etc but it doesn't work.

// Here's is my code:
	//STYLING
	ImGuiStyle& style = ImGui::GetStyle();
	style.FrameRounding = 50;

	ImGuiIO& io = ImGui::GetIO();
	io.ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange;

	LPDIRECT3DTEXTURE9 texture;
	D3DXCreateTextureFromFile(D3D9Device, L"C:\\Users\\LocalAdmin\\Downloads\\button.png", &texture);

	ImGui::SetNextWindowSize(ImVec2(70, 60));
	ImGui::SetNextWindowPos(ImVec2(373, 645));
	if (ImGui::Begin("Test", NULL, ImGuiWindowFlags_NoResize |
		ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoBackground))
	{
		bool butpress = false;
		ImVec2 buttonSize = ImVec2(40, 40);
		ImGui::SetCursorPos(ImVec2(5, 3));
		ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.f, 0.f, 0.f, 0.f));
		ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0.f, 0.f, 0.f, 0.f));
		//ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0.f, 0.f, 0.f, 0.f));

		ImTextureID textureID = io.Fonts->TexID;	
		//ImTextureID textureID = texture;

		ImGui::PushID(1);                               
		if (ImGui::ImageButton(textureID, buttonSize)) {
		//if (ImGui::Button("Button", buttonSize)) {
			butpress = true;
		}
		ImGui::PopID();

		if (butpress == true)
			ImGui::OpenPopup("Modal Window");
		
		ImGui::PopStyleColor(2);
		bool open = true;
		ImGui::SetNextWindowSize(ImVec2(550, 310));
		if (ImGui::BeginPopupModal("Modal Window", &open))
		{
			ImGui::Text("Modal Window Content");
			if (ImGui::Button("Close"))
                        {
				ImGui::CloseCurrentPopup();
                                butpress = false;
                        }
			ImGui::EndPopup();
		}
	}
	ImGui::End();

**Comment by ocornut** [comment]
Assuming the texture display correctly, I can't imagine how the code above exactly as state would have an issue.

Try to change your code to reduce confusion and ease debuggabiity:

```cpp
static int count1 = 0;
static int count2 = 0;
if (ImGui::ImageButton(io.Fonts->TexID, buttonSize))
   count1++;
if (ImGui::ImageButton(texture, buttonSize))
   count2++;
ImGui::Text("Counters: %d %d", count1, count2);
```

To absolutely make sure the texture id creates a difference.
You may:
- use a debugger to confirm the value of 'texture'.
- use Demo->Tools->Metrics to investigate the draw calls of both button and confirm the
- use Demo->Tools->Stack Tool to investigate the item ID of both buttons.

**Comment by ocornut** [comment]
Using `IsItemClicked()` "works" because unlike a normal button this is a stateless reaction to mouse-down happening within the item rectangle. A regular button needs a mouse-down, then mouse-up on same item, which is why it needs to record the active ID to perform that compare across multi-frames.

> Yes, I reviewed the code multiple times and cannot find any issue

I gave you suggestions of tools to use to inspect this and you haven't provided any feedback/reaction on using those tools.

Try to use `Tools->Debug Log->ActiveId` and see what value you get for your button.

**Comment by ocornut** [comment]
In the absence of reaction on your side after being given the information you need to debug this, i’m closing this.

**Comment by catal4n** [comment]
Problem fixed. I was not reading the bool correctly...
