### ISSUE TITLE
why does imgui crash on android devices?

### ISSUE THREAD

**Issue by Makaka23404** [ocornut/imgui#6400]
I use imgui for android devices, on some it works properly and on some it - crashes. What can be done about it?

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue", more details about context and your crash, and reply here when edited.

Closing.

**Comment by Abdo99980** [comment]
I have imgui as lgl Mod Menu but the ImGui menu is not showing 

https://github.com/ocornut/imgui/assets/87795539/56d3f555-8342-40be-8307-18244ace61b0

This is source code I'm using

https://github.com/NepMods/Aide-Imgui
