### ISSUE TITLE
Grid and model render order

### ISSUE THREAD

**Issue by pavledev** [ocornut/imgui#6402]
Version/Branch of Dear ImGui:

Version: 1.89.2
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: VS2022
Operating System: Windows 10

My Issue/Question:

I am using [DrawGrid](https://github.com/CedricGuillemet/ImGuizmo/blob/master/ImGuizmo.cpp#L2693) function from ImGuizmo to draw grid and I use DirectXTK to draw model and problem is that I can see grid through bottle model. How I can draw grid before model?
![image](https://user-images.githubusercontent.com/11335680/236437786-6180229a-b61e-48e1-87bb-b7eef65b2c4c.png)

**Comment by ocornut** [comment]
Closing as this is not a dear imgui question but likely a general rendering question.
