### ISSUE TITLE
Inconsistent Mouse Cursor over InputText with NavEnableKeyboard

### ISSUE THREAD

**Issue by estrac** [ocornut/imgui#6417]
#### Configuration
```
Dear ImGui 1.89.6 WIP (18954)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1935
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000006
 HasMouseCursors
 HasSetMousePos
--------------------------------
[snip]
```

#### Issue:
With `ImGui::GetIO.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard` the "edit mouse cursor" is lost after `Enter` is pressed in `ImGui::InputText` in the `Console` example in `imgui_demo.cpp`. This does not happen when `NavEnableKeyboard` is off, which I think is desirable because the user still has their mouse in the `InputText` (see video).

Reproduces in Demo on GLFW+OpenGL3 example in Dear ImGui on Windows, also observed on SDL2+OpenGL3 on Ubunto Linux.

#### Video:

https://user-images.githubusercontent.com/26418855/236992096-196a25bc-7cd2-4dd9-a426-a18ce9769b34.mp4

Note that the mouse is moved slightly to restore the edit cursor after it is lost by hitting `Enter`.

#### Standalone, minimal, complete and verifiable example:
No new code needed to reproduce

**Comment by ocornut** [comment]
This seems to not be general, but caused by the `SetKeyboardFocusHere()` call in the console code.
It switches to keyboard mode and then in this situation mouse hovering doesn't highlight items anymore.

I have pushed a workaround for it 349af87
I may decide to generalize this a little bit further in the future.

Thanks for reporting and sorry for my late answer!

**Comment by estrac** [comment]
Thanks for the fix!
