### ISSUE TITLE
Will OpenGL ES 2.0 work from under OpenGL ES 3.0?

### ISSUE THREAD

**Issue by VadimBoev** [ocornut/imgui#6423]
Version: 1.89.5
Branch: release

Good afternoon dear ImGui. I need to create an Android application that will be based on OpenGL ES 2.0. I found an example for OpenGL ES 3.0, but I also saw in it that you can use ES 2.0. Thus, questions arise:   
1.) Will it really work for ES 2.0?   
2) Does it guarantee 100% performance on all devices? (because ES 3.0 is not available, as I know, on all phones).  
3) Let's say the application is running on OpenGL ES 2.0, but from under OpenGL ES 3.0 (imgui_impl_opengl3.cpp )/ And if the phone does not have OpenGL ES 3, the application will not start?

**Comment by ocornut** [comment]
1) 3)`imgui_impl_opengl3.cpp` supports ES2 you need to `#define IMGUI_IMPL_OPENGL_ES2` globally or in your imconfig.h file for it to work, and use GLSL `"#version 100"` string during init.

Performances should be good, but ES2 doesn't support `glDrawElementsBaseVertex()` so it may be preferable to also use `#define ImDrawIdx unsigned int` to use 32-bit indices for large mesh support.

**Comment by huguang6** [comment]
Hi, there is a question for me, on the arm paltform OpenGL ES 2.0,  32-bit indices is not support and also glDrawElementsBaseVertex(), so how to use "pcmd->VtxOffset" when set flag "ImGuiBackendFlags_RendererHasVtxOffset"

**Comment by ocornut** [comment]
If it cannot support it then the backend shouldn’t set ImGuiBackendFlags_RendererHasVtxOffset.

**Comment by huguang6** [comment]
> If it cannot support it then the backend shouldn’t set ImGuiBackendFlags_RendererHasVtxOffset.
Thanks! I found the soultion int  #3163
