### ISSUE TITLE
Mouse Input Misalignment Affecting SliderFloat Operation in Custom OpenGL Context

### ISSUE THREAD

**Issue by marzRX** [ocornut/imgui#6425]
**Version/Branch of Dear ImGui:**
Version: 1.89.5, 1.89.1
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-end: Win32 + OpenGL3
Compiler: g++(MinGW)
OS: windows7

**My Issue/Question:**
I'm currently developing an application using ImGui in combination with Win32, and I've noticed a peculiar behavior. I'm rendering ImGui UI elements, such as a slider, on a panel that I've placed on a dialog. However, the slider only responds when I move the cursor to a specific position on the dialog, not on the panel.

If I use the coordinate system with the upper left corner of the panel as the origin (let's call it 'panel coordinates'), the slider might be positioned at (30, 30) for example. Yet, the slider doesn't react when I hover over it with my cursor. On the other hand, if I move the cursor to (30, 30) in the coordinate system with the dialog's upper left corner as the origin (let's call it 'dialog coordinates'), the slider does respond.

Given these observations, it seems like ImGui might be using the dialog coordinates without accounting for the panel coordinates. I'm not sure if this is an expected behavior of ImGui, or if it might be an oversight. Is this the designed behavior (spec) or could this possibly be an issue? I would be grateful for any insight or advice on this matter

--
Since I wanted to enable ImGui_ImplWin32_WndProcHandler for the build, I modified the macro switch in imgui_impl_win32.{cpp,h} from #if 0 to #if 1. Also, to address an error related to LRESULT, I included <windows.h> in imgui_impl_win32.h.

**Screenshots/Video**
![ezgif-2-b44a4edc4c_2_](https://github.com/ocornut/imgui/assets/69402777/d9d7b567-dbae-409b-a5bf-47e812bb2861)

**Standalone, minimal, complete and verifiable example:**
```
  // Create OpenGL context for Panel
  CreateGlContext(hPanel); // ----- IMPORTANT ----- ( hPanel )

  // initialize
  IMGUI_CHECKVERSION();
  ImGui::CreateContext();
  ImGuiIO& io = ImGui::GetIO(); (void)io;

  // Setup Platform/Renderer bindings
  ImGui_ImplWin32_Init(hPanel); // ----- IMPORTANT ----- ( hPanel )
  ImGui_ImplOpenGL3_Init("#version 150");

  isImGuiReady = true;

  ShowWindow(hWnd, nCmdShow);
  UpdateWindow(hWnd);

  // Setup Dear ImGui style
  ImGui::StyleColorsLight();

  static float sliderValue = 0.0f;
  MSG msg;
  while (GetMessage(&msg, NULL, 0, 0)) {
    TranslateMessage(&msg);
    DispatchMessage(&msg);

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplWin32_NewFrame();
    ImGui::NewFrame();

    // Creating an ImGui window of the same size as the panel
    ImGui::SetNextWindowSize(ImVec2(panel_width, panel_height));
    ImGui::SetNextWindowPos(ImVec2(0, 0));

    ImGui::Begin("Fixed Window", nullptr, ImGuiWindowFlags_NoCollapse |
                 ImGuiWindowFlags_NoTitleBar |
                 ImGuiWindowFlags_NoMove |
                 ImGuiWindowFlags_NoResize);

    ImGui::Text("Hello, ImGui!");
    ImGui::SliderFloat("Slider", &sliderValue, 0.0f, 1.0f);
    ImGui::End();

    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
    SwapBuffers(g_HDCDeviceContext);
  }

  return (int)msg.wParam;
}
```
[prog1.zip](https://github.com/ocornut/imgui/files/11459168/prog1.zip)

**Comment by marzRX** [comment]
I apologize for my use of the term "dialog". In fact, what I've created is a window. (I am using WS_EX_DLGMODALFRAME to give it a "dialog-like" appearance, however...)
Regarding your suggestion to use a custom control as a target, I'm curious to know how that would differ from the method I'm currently using, which involves using a panel as a target. Could you please clarify?

**Comment by marzRX** [comment]
By the way, I have managed to find a temporary fix using the following code. However, it's not perfect and causes flickering:
```
io.MousePos.x = static_cast<float>(mouse_pos.x - panel_x);
io.MousePos.y = static_cast<float>(mouse_pos.y - panel_y);
```
If anyone has any other ideas, I'd love to hear them.

**Comment by GamingMinds-DanielC** [comment]
Just saw that you linked the entire source as well, before that I thought that `hPanel` maybe was your dialog. Well, your problems stems from calling `ImGui_ImplWin32_WndProcHandler` in the handler of the main window, which will generate coordinates relative to the main window. Try registering a proper class including a message handler for your panel window and forward messages from there, then coordinates should be translated correctly to your panel.

**Comment by marzRX** [comment]
Success! It works perfectly now! Thank you. Especially, your advice to apply the window procedure to each window was truly helpful. I really appreciate your help!

Thank you for taking the time to look at my source code. :)
