### ISSUE TITLE
Metal macOS multi-viewport issue (secondary monitor negative position)

### ISSUE THREAD

**Issue by timeinpixels** [ocornut/imgui#6432]
**Version/Branch of Dear ImGui:** 

Version: dear imgui, v1.89.6 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_metal.cpp + imgui_impl_osx.cpp
Compiler: clang / Xcode
Operating System: macOS

**My Issue/Question:**

I have noticed an issue with multi-viewports when working on dual-monitor setup.
My monitor on the right is the main monitor (with the taskbar).
When I open my application on my left monitor (screen coordinates are negative, relative to the main monitor) then when I try to move the ImGui window out of the main application window - it disappears right when the window starts going out of the main window bounds. 
The issue doesn't happen on the main monitor (with positive screen coordinates).

![2023-05-14_multi-viewports](https://github.com/ocornut/imgui/assets/30871510/96a79907-1c11-4f15-8346-574d1418ae5f)

**Comment by ocornut** [comment]
Hello,
Can you check in Metrics:
- the respective coordinates of each monitor
- values for this viewport while dragging

You may need to investigate this further.

**Comment by timeinpixels** [comment]
The values seem to be correct:

![2023-05-14_multi-viewport-2](https://github.com/ocornut/imgui/assets/30871510/8e9f423f-b603-4bde-9fa5-e34abdd3f0bb)

**Comment by ocornut** [comment]
This should now normally be fixed with a683033e49592dfe04fc037a41f8bc8f0bf8a953

**Comment by timeinpixels** [comment]
Fantastic, works as expected!
