### ISSUE TITLE
Input Float with step size does not increment with given step size

### ISSUE THREAD

**Issue by kingofknights** [ocornut/imgui#6434]
**Version/Branch of Dear ImGui:**

```
Dear ImGui 1.89.6 WIP (18951)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1935
define: _MSVC_LANG=202002
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl3
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C06
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 1024,2048
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl3.cpp + imgui_impl_opengl3.cpp 
Compiler: MSVC143
Operating System: Window11

**My Issue/Question:**
`
static float Price = 0.05;
if (ImGui::InputFloat("Price", &Price, 0.050000000000f, 0, "%.2f")) {
		if (Price < 0) Price = 0;
	}`

on Loading
![image](https://github.com/ocornut/imgui/assets/27801739/e520489b-d23d-40dd-9dab-b96cd1faff34)

after long press or fast press on `+` button
![image](https://github.com/ocornut/imgui/assets/27801739/d3d9d5cc-7203-4502-9eeb-7f9735140c72)

**Comment by ocornut** [comment]
Hello,
Thanks for filling the template and providing a clear repro!

This seems to come from accumulating float imprecision,

Notice how:
```cpp
float f0 = 17442.65f;
ImGui::Text("%f", f0 + 0.05f * 13.0f);
ImGui::Text("%f", f0 + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f + 0.05f);
```
Respectively prints 17443.300781 vs 17443.310547

Whereas if you start with a smaller value e.g. 0.65f you'll find there would be little to no differences, and that difference will increase as value increase. Some ref:

- https://www.h-schmidt.net/FloatConverter/IEEE754.html (notice 17442.65 is actually stored as 17442.650390625)
- https://blog.demofox.org/2017/11/21/floating-point-precision

We can't really solve this if the only criteria are 0.05 increments, but you could "round" the value to multiple of 0.05:

```cpp
const float step = 0.05f;
if (ImGui::InputFloat("Price", &Price, step, 0, "%.2f"))
   Price = round(Price / step) * step;
```
Which will get you closer to what you want.

You might also use a double and `InputDouble()` as a workaround.

**Comment by ocornut** [comment]
Closing this as answered.
