### ISSUE TITLE
Is it possible having imgui window outside the glfw viewport?

### ISSUE THREAD

**Issue by bipul-mohanto** [ocornut/imgui#6435]
Hi! `imgui` is just an awesome code-base. I would sincerely love to thanks the authors. I am using the `master` branch. For my purpose, can I dock the window outside (right side) the `glfw` viewport and that should be fixed whenever I run the program. I would appreciate if you suggest any solution. 

<img width="1008" alt="Capture" src="https://github.com/ocornut/imgui/assets/12484581/4b4d0afb-0a51-4e89-a487-be5af16231dc">

**Comment by ocornut** [comment]
Every branch has those files.

**Comment by bipul-mohanto** [comment]
My bad, those were additional files from previous project. Thanks for assistance.

**Comment by ocornut** [comment]
Those files are in the `backends/` folder.
