### ISSUE TITLE
Docking a viewport window causes crash with title-less (WS_POPUP) window rendered with DX9 backend

### ISSUE THREAD

**Issue by dgm3333** [ocornut/imgui#6440]
Version: 1.89.5
Branch: docking
Back-ends: imgui_impl_dx9.cpp
Compiler: Visual Studio
Operating System: Windows 10

**My Issue/Question:**

Using vanilla ImGui example I wanted a window without the console-like title bar.
I thus set the window creation to WS_Popup
    HWND hwnd = ::CreateWindowW(wc.lpszClassName, L"Dear ImGui DirectX9 Example", WS_POPUP , 100, 100, 1280, 800, nullptr, nullptr, wc.hInstance, nullptr);

This works flawlessly using example_win32_opengl3
![image](https://github.com/ocornut/imgui/assets/51210/39b47ed6-8175-4b58-856c-57f1c435fbec)

However using dx9 it initially renders OK, but when you dragging any viewport managed windows over the main window it immediately causes an ImGui crash

![image](https://github.com/ocornut/imgui/assets/51210/11a2a7e8-22c3-4aa7-ae80-2ceea559c51b)

**Comment by ocornut** [comment]
It looks like a bug in example_win32_directx9/main.cpp introduced in 031e152d2. (#6374)
I have pushed a fix c8579ab
Thanks!

(Note that none of this is due to actual Dear ImGui library but is a bug in the example code)

**Comment by dgm3333** [comment]
Thanks ocornut - seriously speedy fix!

Incidentally I checked and it works for SDL2 - just in case other people wanted an example of code for this too:-

    SDL_Window* window = SDL_CreateWindow("Dear ImGui SDL2+OpenGL3 example", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 1280, 720, window_flags);
    SDL_SetWindowBordered(window, SDL_FALSE);
