### ISSUE TITLE
Don't display Chinese

### ISSUE THREAD

**Issue by wangjin55** [ocornut/imgui#645]
hello,

I was just using IMGUI,I encountered a problem can not display Chinese.
the code to 
    //Gets the font
    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->AddFontFromFileTTF("simsun.ttc", 18.0f, NULL, io.Fonts->GetGlyphRangesChinese());
	
    //Display  font 
    static char buf[32];
    ImGui::Text("中文字体");
    ImGui::InputText("UTF-8 Input", buf, IM_ARRAYSIZE(buf));
    ImGui::Text(buf);
![1111](https://cloud.githubusercontent.com/assets/19189815/15148956/4b14bcd6-16fa-11e6-9f9d-8db772c0903a.jpg)

If the initialization buf[32] with the Chinese
   static char buf[32]="中文字体";
   ImGui::Text("中文字体");
   ImGui::InputText("UTF-8 Input", buf, IM_ARRAYSIZE(buf));
   ImGui::Text(buf);
![2222](https://cloud.githubusercontent.com/assets/19189815/15148957/4d3f4bca-16fa-11e6-964a-2513c504ff68.jpg)

Now,How to solve this problem.

**Comment by ocornut** [comment]
Please read the FAQ 

```
 Q: How can I display and input non-Latin characters such as Chinese, Japanese, Korean, Cyrillic?
 A: When loading a font, pass custom Unicode ranges to specify the glyphs to load. 
    All your strings needs to use UTF-8 encoding. Specifying literal in your source code using a local code page (such as CP-923 for Japanese or CP-1251 for Cyrillic) will not work.
    In C++11 you can encode a string literal in UTF-8 by using the u8"hello" syntax. Otherwise you can convert yourself to UTF-8 or load text data from file already saved as UTF-8.
    You can also try to remap your local codepage characters to their Unicode codepoint using font->AddRemapChar(), but international users may have problems reading/editing your source code.
```

**Comment by paulsapps** [comment]
Maybe you should add an example label to the demo panel, this seems to come up a lot :s

**Comment by wangjin55** [comment]
Thank you,ocornut.

**Comment by ocornut** [comment]
@paulsapps there is one example and a comment about UTF-8 literal in the code but the example doesn't load TTF file. Would need to find a way to load fonts in the examples. With path/file-system issues, it may be simpler to just load a font embedded in code that also would be confusing/misleading to users. Perhaps would be easier to tweak the VisualStudio project to start in the same directory as the .sln and then the code can just refer to ../../extra_fonts/xxxx.ttf file and perhaps have a fallback.
