### ISSUE TITLE
GL_POLYGON defined even for opengl es

### ISSUE THREAD

**Issue by sivansh11** [ocornut/imgui#6450]
On trying to build imgui for opengl es 3.2 on linux x86 gcc compiler, imgui_impl_opengl3_loader.h defines GL_POLYGON_MODE which defines IMGUI_IMPL_HAS_POLYGON_MODE in imgui_impl_opengl3.cpp.
GL_POLYGON_MODE should not be defined for opengl es

I am using a hack to get it to work 

added #undef GL_POLYGON_MODE before the line that checks for this and defines IMGUI_IMPL_HAS_POLYGON_MODE

what would be the proper way to use opengl es ? there are no specific examples for this

**Comment by ocornut** [comment]
> opengl es 3.2

You need to `#define IMGUI_IMPL_OPENGL_ES3` in imconfig.h or globally or in the compilation unit of imgui_impl_opengl3.cp

**Comment by ocornut** [comment]
Added extra comments in 52e1911

**Comment by sivansh11** [comment]
I had tried adding IMGUI_IMPL_OPENGL_ES3 as a compiler define (globally), its causing undefined references to many opengl functions

**Comment by ocornut** [comment]
That's because you are not linking with the library containing those functions.

**Comment by sivansh11** [comment]
I did try linking it to glad which should have resolved all the undefined references ?

**Comment by ocornut** [comment]
It depends what the undefined references are but probably not.
You are not being specific and expecting us to magically guess what you missed in your project..

**Comment by sivansh11** [comment]
It was a compiler error, but not for very obvious reasons.

my approach to getting it to compile is defining IMGUI_IMPL_OPENGL_LOADER_CUSTOM and then including glad.h in imconfig.h

Is there a better way than polluting imconfig.h ? or is what I have done the best way to resolve this problem

I am sorry if I am not being very specific and I definitely dont expect you guys to magically guess what I might have missed, what information do you need to better understand my problem ?

**Comment by ocornut** [comment]
> It was a compiler error, [...] what information do you need to better understand my problem ?

If you want help for a compiler or link error you should post it.

> my approach to getting it to compile is defining IMGUI_IMPL_OPENGL_LOADER_CUSTOM and then including glad.h in imconfig.h

You should only use `IMGUI_IMPL_OPENGL_ES3` if you want to use ES3.

> Is there a better way than polluting imconfig.h ?

You can add the define in your build system.

**Comment by sivansh11** [comment]
okay, so I as I said I was facing undefined reference error 
heres the output of from the compiler https://pastebin.com/xFZLK2Xr

I did add IMGUI_IMPL_OPENGL_ES3 to the build system using 
```
target_compile_definitions(imgui 
    PUBLIC IMGUI_IMPL_OPENGL_ES3
)```

this is my cmake file for imgui 
```
cmake_minimum_required(VERSION 3.10)

project(imgui)

set(SRC_FILES imgui/backends/imgui_impl_opengl3.cpp imgui/backends/imgui_impl_glfw.cpp  imgui/imgui_demo.cpp imgui/imgui_draw.cpp imgui/imgui_tables.cpp imgui/imgui_widgets.cpp imgui/imgui.cpp imgui/misc/cpp/imgui_stdlib.cpp)

add_library(imgui ${SRC_FILES})

target_compile_definitions(imgui 
    PUBLIC IMGUI_IMPL_OPENGL_ES3
)

target_include_directories(imgui
    PUBLIC imgui
    PUBLIC ../glfw/include
)
```

what should I link against to get the definitions of these opengl functions ? I normally use glad as my loader, I did read about IMGUI_IMPL_OPENGL_LOADER_XXX in imgui_impl_opengl3.h, so I tried adding IMGUI_IMPL_LOADER_GLAD, this also didnt work

**Comment by ocornut** [comment]
If you use `IMGUI_IMPL_OPENGL_ES3` we don't need a loader we are using standard ES includes and symbols.

There must be a library to link to get the GL ES function. The question is "how do you use ES 3 on Linux".
