### ISSUE TITLE
IM_ASSERT Monitors.Size > 0 failing in glfw example

### ISSUE THREAD

**Issue by JaedanC** [ocornut/imgui#6459]
**Version/Branch of Dear ImGui:**

Version: [19b436f68da9ceaef3684900c90ec7a9622f941a](https://github.com/ocornut/imgui/commit/19b436f68da9ceaef3684900c90ec7a9622f941a)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

The commit above using the `example_glfw_opengl3` will cause an exception to be raised.

https://github.com/ocornut/imgui/blob/19b436f68da9ceaef3684900c90ec7a9622f941a/imgui.cpp#L9712

Confirmed not working using the `build_win32.bat` script provided in `example_glfw_opengl3`.

In the commit I can see that if a GlfwMonitor is found, it will exit the function early resulting in the platform monitors not being initialised.

I can fix the bug by commenting out the early exit and allowing the platform monitors to be made, but this is effectively undoing https://github.com/ocornut/imgui/issues/5683. Fixing both may require some investigation.

**Comment by hamyyy** [comment]
I was just about to open an issue but here you are :D

I tracked it down to this line:

https://github.com/ocornut/imgui/blob/19b436f68da9ceaef3684900c90ec7a9622f941a/backends/imgui_impl_glfw.cpp#L882-L885

I think it's supposed to be: (missing "!")

```c++
 if (!monitors_count)
     return; 
```
But I could be mistaken

**Comment by JaedanC** [comment]
With that change, the only thing that would be different from before the commit is that:

https://github.com/ocornut/imgui/blob/19b436f68da9ceaef3684900c90ec7a9622f941a/backends/imgui_impl_glfw.cpp#L887

would not be called. I'm just not sure if this change fixes https://github.com/ocornut/imgui/issues/5683 too.

**Comment by ocornut** [comment]
Apologies for the typo, pushed fix 2e810d575cb5c8708340f53e301424c237ebca80 (first time I do a code edit directly on github!).

**Comment by adamsepp** [comment]
Hi @ocornut,  
while investigating a similar issue when hotplugging all monitors or waking up after Windows power saving (screen off / sleep), I found that the problem might actually be in the GLFW backend.  

It looks like GLFW does not always recover monitor information correctly after these events.  
Therefore I have raised a GLFW issue here for further tracking:  
https://github.com/glfw/glfw/issues/2764
