### ISSUE TITLE
combo box in popup window doesn't work

### ISSUE THREAD

**Issue by marcojez** [ocornut/imgui#646]
I've updated the source tree to try out the resolution of #604 (which, as far as I can tell, has been solved). Now, combo boxes created within popup windows don't work anymore. The list of items opens up correctly when clicked, but then the whole widget becomes unresponsive to mouse events, so it's impossible to select any item. Any clues?

Marco

**Comment by ocornut** [comment]
Could you post a repro because it seems to work here.

**Comment by ocornut** [comment]
OK you mean Modal window just a regular popup.

**Comment by marcojez** [comment]
Yes sorry, modal window.

**Comment by marcojez** [comment]
Do you still need the repro?

**Comment by ocornut** [comment]
No I am good. The bug was definitively introduced by https://github.com/ocornut/imgui/commit/544ba36bf66e877b4ce69eb03a9d93736e6dab24

**Comment by ocornut** [comment]
Fixed in https://github.com/ocornut/imgui/commit/8648346eab5a485c5006a6a9473fe6c9d3eb4fe6 (I referencing the wrong commit number in the commit message).

**Comment by marcojez** [comment]
Fix confirmed, thank you!
