### ISSUE TITLE
Bug in rendering AddRectFilledMultiColor with OpenGL3

### ISSUE THREAD

**Issue by eXtreames** [ocornut/imgui#6466]
Hi, i use imgui with opengl3 + win32 implementation and i have found bug in rendering (ImGui::ColorPicker4, imgui_widgets.cpp:5358-5359), while rendering gradient. 
![image](https://github.com/ocornut/imgui/assets/45105308/5aa2084d-fe77-41b3-9341-0f5fc7ee6802)

**Comment by ocornut** [comment]
I don't understand what I am looking at.
Please read Issue Guidelines, feel the form and be explicit.
