### ISSUE TITLE
Unexpected behavior when making 2 sliders with text on the left using Text, SameLine, Slider

### ISSUE THREAD

**Issue by swpq** [ocornut/imgui#6472]
**Version/Branch of Dear ImGui:**

Version: 1.89.6 WIP / 18959 (latest)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx9.cpp
Compiler: MSVC
Operating System: Win64

**My Issue/Question:**

When you make 2 sliders using Text, SameLine & Slider (any) (to make the text on the left side), the sliders are both affected when being dragged. (Instead of just one)

**Screenshots/Video**
https://github.com/ocornut/imgui/assets/44510312/622832ff-1124-4ce2-a32c-2942c0132714

```
ImGui::Begin("Example Bug");

ImGui::Text("First Slider");
ImGui::SameLine();
ImGui::SliderFloat("", &v, 0, 1.0, "%.1f");

//--------

ImGui::Text("Second Slider");
ImGui::SameLine();
ImGui::SliderFloat("", &v1, 0, 1.0, "%.1f");

ImGui::End();
```

**Comment by swpq** [comment]
If you add
`
ImGui::Dummy(ImVec2(0.0f, 1.0f));
`
in-between the sliders, it works as expected.

**Comment by ocornut** [comment]
This is answered in the FAQ.
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system
