### ISSUE TITLE
How to add Image button in ImGui in which the button only takes the shape of the svg?

### ISSUE THREAD

**Issue by gupta-ish** [ocornut/imgui#6476]
I want to add arrow shaped/curved/circle buttons (using my own svg images) but they should not be clickable outside the image.

sample 
`ImGui::ImageButton((void*)(intptr_t)texture_, ImVec2(ImGui::GetMainViewport()->WorkSize.x/15, ImGui::GetMainViewport()->WorkSize.y/10),ImVec2(0,0),ImVec2(1,1),0,Im_light_blue, ImVec4(1,1,1,1));
`

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. Issue is too ambiguous.
I am sorry but I have no patience for this. Closing.
