### ISSUE TITLE
InputFloat doesn't work with scientific notation

### ISSUE THREAD

**Issue by josiahmanson** [ocornut/imgui#648]
I'd like to be able to type a value in scientific notation. Ex. `2.34e-5`. I will need to make a custom widget, but this seems like it would be a reasonably common thing for a user to want to do.

**Comment by josiahmanson** [comment]
I made a scientific input widget and am posting the code here in case anyone else want to use it or use this as a starting point for adding into ImGui.

imgui.h
```
IMGUI_API bool			InputFloatScientific( const char* label, float* v, const char *display_format = "%.3g", ImGuiInputTextFlags extra_flags = 0);

```

imgui_internal.h
```
IMGUI_API bool          InputScalarScientific(const char* label, ImGuiDataType data_type, void* data_ptr, const char* scalar_format, ImGuiInputTextFlags extra_flags);
```

imgui.cpp
```
static bool DataTypeApplyOpFromTextScientific( const char* buf, const char* initial_value_buf, ImGuiDataType data_type, void* data_ptr, const char* scalar_format )
{
	scalar_format = "%f";
	float* v = (float*)data_ptr;
	const float old_v = *v;
	*v = (float)atof( buf );
	return *v != old_v;
}

bool ImGui::InputScalarScientific( const char* label, ImGuiDataType data_type, void* data_ptr, const char* scalar_format, ImGuiInputTextFlags extra_flags )
{
	ImGuiWindow* window = GetCurrentWindow();
	if ( window->SkipItems )
		return false;

	ImGuiState& g = *GImGui;
	const ImGuiStyle& style = g.Style;
	const ImVec2 label_size = CalcTextSize( label, NULL, true );

	ImGui::BeginGroup();
	ImGui::PushID( label );
	
	char buf[64];
	DataTypeFormatString( data_type, data_ptr, scalar_format, buf, IM_ARRAYSIZE( buf ) );

	bool value_changed = false;
	extra_flags |= ImGuiInputTextFlags_AutoSelectAll;
	if ( ImGui::InputText( "", buf, IM_ARRAYSIZE( buf ), extra_flags ) )
		value_changed = DataTypeApplyOpFromTextScientific( buf, GImGui->InputTextState.InitialText.begin(), data_type, data_ptr, scalar_format );

	ImGui::PopID();

	if ( label_size.x > 0 )
	{
		ImGui::SameLine( 0, style.ItemInnerSpacing.x );
		RenderText( ImVec2( window->DC.CursorPos.x, window->DC.CursorPos.y + style.FramePadding.y ), label );
		ItemSize( label_size, style.FramePadding.y );
	}
	ImGui::EndGroup();

	return value_changed;
}

bool ImGui::InputFloatScientific( const char* label, float* v, const char *display_format, ImGuiInputTextFlags extra_flags )
{
	return InputScalarScientific( label, ImGuiDataType_Float, (void*)v, display_format, extra_flags );
}
```

**Comment by ocornut** [comment]
> this seems like it would be a reasonably common thing for a user to want to do.

You are the first person to ever ask!

Note that you can use the public API and make your function just call InputText(), SameLine(), Text(), scanf.

**Comment by josiahmanson** [comment]
I thought about using the public API and InputText, but decided against it because that would require me to keep around a text buffer for each float that I want to modify, which seemed like seemed like at least as much of a hassle as modifying the functions in ImGui. I have to say that it is very convenient to have the source. :-)

**Comment by josiahmanson** [comment]
Now that I think about it I could just have used a local text buffer. Oh well. It wasn't that hard to modify.

**Comment by ocornut** [comment]
No, I mean you can create your helper, named exactly the same way, same API as InputFloatScientific() but you can implement that function in your own code and just call sprintf / InputText, etc. so your custom extensions to ImGui don't have to necessary modify the core code.

**Comment by ocornut** [comment]
So just to clarify, essentially the change here is that you are using `atof` instead `scanf("%f")` and that is enough to get scientifc notation parsed? (as per your comment in #642). Doesn't scanf handle the same float parsing features as `atof` ?

I don't have all the answers/time but I'm interested in all this feedback by the way, it shall eventually lead into allowing those cases to be used more naturally.

**Comment by josiahmanson** [comment]
The change of `scanf` to `atof' doesn't have anything to do with parsing the string correctly. It is just more efficient to directly call `atof` than having `scanf` parse a format string to figure out that it should call `atof`. Also, `atof` automatically eats leading whitespace, so the while loop doing that is redundant.

The real issues are:
1) There was some filtering of the keypresses that prevent typing nondecimal characters like `e`.
2) The input `decimal_precision` variable (i forget the exact name) as it is implemented can't deal with scientific notation, and there needs to be a format string that is passed in instead to allow `%e` and `%g` formats.

**Comment by ocornut** [comment]
0) Ok. Though here we are dealing with a maximum of 1 call per user-interaction so the cost should be invisible. It isn't a call that's done on every widget. But you are right.

1) We could add extra flag to support that. Of perhaps just make any Float() function just add support for `e` by default. Anything other than `e` ?

2) OK.

Will look into at all eventually. I am not really familiar with using scientific notation so this was overlooked. If you want to dig into it further it'd be helpful.

You should probably move your new code outside of imgui.cpp to entice you to use vanilla code and merge more easily, since that code can live in any file.

**Comment by josiahmanson** [comment]
The only other thing I can think of right now is that I noticed there is some code that checks for `+` and `-` to increment and decrement. I guess are least that is what it is doing. Anyhow, that code could interfere with typing valid numbers like `23e-4` and `56e+7`. Note that the `+` and `-` are just indicating the sign of the exponent rather than an addition or subtraction.

**Comment by ocornut** [comment]
Tho normally this transformation done in `DataTypeApplyOpFromText` only look for a leading `+` or `-` and not affect scientific notation input? But we should add a flag to disable that transform.

**Comment by ocornut** [comment]
I have added `InputFloat()` entry points that takes a format string, which is more flexible and consistent with other API. You can now uses `InputFloat()` exactly as you used your `InputFloatScientific()`.
I think this issue should be solved now.

(I'm not using atof yet, one of the issue with it in some code path is that it doesn't allow checking for parsing errors, whereas scanf allows it.)

**Comment by evouga** [comment]
This has not been pulled into the main libigl yet? I'm not seeing this version of InputFloat. Also, just a note that an InputDouble version would be very useful.

**Comment by ocornut** [comment]
@evouga This is the imgui repo I don't know what's being pulled or not by libigl. There's now an `InputDouble` in dear imgui as well as DragScalar, SliderScalar, InputScalar which all support `double`.
