### ISSUE TITLE
Strange crash in docking branch (commit 3418d50)

### ISSUE THREAD

**Issue by slajerek** [ocornut/imgui#6480]
**Version/Branch of Dear ImGui:**

Version: commit 3418d509490c0f1dd4bc6c3ba2a9312e8efc0ff9
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl2.cpp 
Compiler: Xcode 
Operating System: macOS 

**My Issue/Question:**

I updated ImGui after very long time. It compiles fine, no code changes required on my end, but now I get immediately during startup procedure a crash in imgui_draw.cpp, line 3223:
`EllipsisWidth = EllipsisCharStep = FindGlyph(EllipsisChar)->X1;`

The FindGlyph returns FallbackGlyph, and that is NULL. I am using default font, it is pretty simple init procedure, do I miss something, was API changed or I need to additionally init font or something?

Thanks in advance.

**Comment by slajerek** [comment]
Oh, it seems that's my bug, I had in the font setup code:
`font_cfg.EllipsisChar = (ImWchar)0x0085;`

It seems that font is there.

**Comment by ocornut** [comment]
Thank you, I can confirm that it shouldn't crash bluntly. I'll look now.

**Comment by ocornut** [comment]
Fixed with 075b975
