### ISSUE TITLE
FPS Counter

### ISSUE THREAD

**Issue by Minimob-vRP** [ocornut/imgui#6481]
So im trying to make an FPS counter using the ImGui::GetIO( ).DeltaTime.

My problem is i wanna make it smooth, so make the thread sleep for 500 milliseconds or something before updating. I tried using the Chronos thread sleep, but it dosent seem to work since it will just make everything else sleep/laggy. 

Any help will be really appreciated thank you :)

**Comment by ocornut** [comment]
Hello,
I am afraid the question has nothing to do with dear imgui so I have to close this.

**Comment by samiryandundin-gif** [comment]
#include "imgui.h"

void DrawWatermark() {
    // Настройки окна: без фона, без рамок, фиксированная позиция
    ImGui::SetNextWindowPos(ImVec2(10, 10), ImGuiCond_Always); // Позиция (x, y)
    ImGui::SetNextWindowBgAlpha(0.35f); // Прозрачность фона
    
    ImGuiWindowFlags textWindowFlags = 
        ImGuiWindowFlags_NoDecoration | 
        ImGuiWindowFlags_AlwaysAutoResize | 
        ImGuiWindowFlags_NoSavedSettings | 
        ImGuiWindowFlags_NoFocusOnAppearing | 
        ImGuiWindowFlags_NoNav | 
        ImGuiWindowFlags_NoMove; // Окно нельзя двигать

    if (ImGui::Begin("Watermark", nullptr, textWindowFlags)) {
        // Получаем FPS
        float fps = ImGui::GetIO().Framerate;
        
        // Выводим текст
        ImGui::Text("ProjectName | FPS: %.1f", fps);
        ImGui::Text("User: Admin");
    }
    ImGui::End();
}
