### ISSUE TITLE
【D3D12、WIN32】multi window

### ISSUE THREAD

**Issue by 061999** [ocornut/imgui#6484]
请问如何用多【D3D12、WIN32】实现多窗口，不同的UI界面
![捕获](https://github.com/ocornut/imgui/assets/88932040/1641b01f-5fd6-4d87-8470-96324e374f66)
我尝试了一下，但是有许多问题
两个窗口处理的消息会冲突
附上我的代码

请您一定要帮助我一下，谢谢，谢谢

===============================Codd==========================================
// Dear ImGui: standalone example application for DirectX 12
// If you are new to Dear ImGui, read documentation from the docs/ folder + read the top of imgui.cpp.
// Read online: https://github.com/ocornut/imgui/tree/master/docs

// Important: to compile on 32-bit systems, the DirectX12 backend requires code to be compiled with '#define ImTextureID ImU64'.
// This is because we need ImTextureID to carry a 64-bit value and by default ImTextureID is defined as void*.
// This define is set in the example .vcxproj file and need to be replicated in your app or by adding it to your imconfig.h file.

#include "imgui.h"
#include "imgui_internal.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx12.h"
#include <d3d12.h>
#include <dxgi1_4.h>
#include <tchar.h>
#include <iostream>

#ifdef _DEBUG
#define DX12_ENABLE_DEBUG_LAYER
#endif

#ifdef DX12_ENABLE_DEBUG_LAYER
#include <dxgidebug.h>
#pragma comment(lib, "dxguid.lib")
#endif

struct FrameContext
{
    ID3D12CommandAllocator* CommandAllocator;
    UINT64                  FenceValue;
};

constexpr unsigned int frame_buffer_count{ 3u };
constexpr unsigned int window_count{ 2u };

struct WindowInfo
{
    UINT frame_index{};
    HWND window_header{};
    IDXGISwapChain3* swapchain{};
    ID3D12DescriptorHeap* srv_desc_heap{};
    ID3D12DescriptorHeap* rtv_desc_heap{};
    ID3D12Resource* render_target_resource[frame_buffer_count]{};
    D3D12_CPU_DESCRIPTOR_HANDLE cpu_desc_handle[frame_buffer_count]{};
    ImGuiContext* imgui_context{};
    FrameContext frameContext[frame_buffer_count] = {};
    const char* main_window_title{};
    ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);
}windows[window_count];

// Data
static int const                    NUM_FRAMES_IN_FLIGHT = 3;
static UINT                         g_frameIndex = 0;

static int const                    NUM_BACK_BUFFERS = 3;
static ID3D12Device*                g_pd3dDevice = NULL;
//static ID3D12DescriptorHeap*        g_pd3dRtvDescHeap = NULL;
//static ID3D12DescriptorHeap*        g_pd3dSrvDescHeap = NULL;
static ID3D12CommandQueue*          g_pd3dCommandQueue = NULL;
static ID3D12GraphicsCommandList*   g_pd3dCommandList = NULL;
static ID3D12Fence*                 g_fence = NULL;
static HANDLE                       g_fenceEvent = NULL;
static UINT64                       g_fenceLastSignaledValue = 0;
//static IDXGISwapChain3*             g_pSwapChain = NULL;
//static HANDLE                       g_fence_event = NULL;
//static ID3D12Resource*              g_mainRenderTargetResource[NUM_BACK_BUFFERS] = {};
//static D3D12_CPU_DESCRIPTOR_HANDLE  g_mainRenderTargetDescriptor[NUM_BACK_BUFFERS] = {};

// Forward declarations of helper functions
bool CreateDeviceD3D();
//void CleanupDeviceD3D();
void CreateRenderTarget();
//void CleanupRenderTarget();
//void WaitForLastSubmittedFrame();
FrameContext* WaitForNextFrameResources(WindowInfo&info);
LRESULT WINAPI WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

// Main code
int main(int, char**)
{
    // Create application window
    //ImGui_ImplWin32_EnableDpiAwareness();
    WNDCLASSEXA wc = { sizeof(wc), CS_CLASSDC, DefWindowProcA, 0L, 0L, GetModuleHandle(NULL), NULL, NULL, NULL, NULL, "ImGui Example", NULL };
    ::RegisterClassExA(&wc);
    windows[0].main_window_title = "title1";
    windows[1].main_window_title = "title2";
    for(auto& window : windows)
    {
        window.window_header = ::CreateWindowA(wc.lpszClassName, window.main_window_title, WS_OVERLAPPEDWINDOW, 100, 100, 1280, 800, NULL, NULL, wc.hInstance, NULL);
        ::ShowWindow(window.window_header, SW_SHOWDEFAULT);
        SetWindowLongPtrA(window.window_header, GWLP_USERDATA, reinterpret_cast<LONG_PTR>(&window));
        SetWindowLongPtrA(window.window_header, GWLP_WNDPROC, reinterpret_cast<LONG_PTR>(WndProc));
    }

    

    //HWND hwnd = windows[0].window_header;

    // Initialize Direct3D
    if (!CreateDeviceD3D())
    {
        //CleanupDeviceD3D();
        //::UnregisterClassW(wc.lpszClassName, wc.hInstance);
        return 1;
    }

    // Setup Dear ImGui context
    IMGUI_CHECKVERSION();
    for(auto& win : windows)
    {
        win.imgui_context = ImGui::CreateContext();
        ImGui::SetCurrentContext(win.imgui_context);

        ImGuiIO& io = ImGui::GetIO();
        //io.ConfigFlags = ImGuiConfigFlags_NoMouse;       // Enable Keyboard Controls
        //io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;           // Enable Docking
        
        ImGui_ImplWin32_Init(win.window_header);
        ImGui_ImplDX12_Init(g_pd3dDevice, NUM_FRAMES_IN_FLIGHT,
            DXGI_FORMAT_R8G8B8A8_UNORM, win.srv_desc_heap,
            win.srv_desc_heap->GetCPUDescriptorHandleForHeapStart(),
            win.srv_desc_heap->GetGPUDescriptorHandleForHeapStart());
    }

    bool show_demo_window = true;
    bool show_another_window = false;
    

    // Main loop
    bool done = false;
    int indexsss{};
    while (!done)
    {
        // Poll and handle messages (inputs, window resize, etc.)
        // See the WndProc() function below for our to dispatch events to the Win32 backend.
        
        //Sleep(20);
        // Start the Dear ImGui frame
        for(auto& item : windows)
        {
            //std::cout << item.imgui_context->InputEventsQueue.Size << std::endl;
            MSG msg;
            /*while (::PeekMessage(&msg, NULL, 0U, 0U, PM_REMOVE))
            {
                ::TranslateMessage(&msg);
                ::DispatchMessage(&msg);
                if (msg.message == WM_QUIT)
                    return 0;
            }*/
            GetMessageA(&msg, nullptr, 0u, 0u);
            ::TranslateMessage(&msg);
            ::DispatchMessage(&msg);
            if(msg.message == WM_QUIT)
                return 0;

           // Sleep(10);
            item.swapchain->Present(1, 0);
            //printf("asdf%d\n",indexsss++);
            ImGui::SetCurrentContext(item.imgui_context);
            //ImGui::GetIO().ConfigFlags = ImGuiConfigFlags_NoMouse;
            ImGui_ImplDX12_NewFrame();
            ImGui_ImplWin32_NewFrame();
            ImGui::NewFrame();

             //1. Show the big demo window (Most of the sample code is in ImGui::ShowDemoWindow()! You can browse its code to learn more about Dear ImGui!).
            //if (show_demo_window)
            //    ImGui::ShowDemoWindow(&show_demo_window);

            //// 2. Show a simple window that we create ourselves. We use a Begin/End pair to create a named window.
            {
                static float f = 0.0f;
                static int counter = 0;

                ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.

                ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
                ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
                ImGui::Checkbox("Another Window", &show_another_window);

                ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f
                ImGui::ColorEdit3("clear color", (float*)&item.clear_color); // Edit 3 floats representing a color

                if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)
                    counter++;
                ImGui::SameLine();
                ImGui::Text("counter = %d", counter);

                ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / ImGui::GetIO().Framerate, ImGui::GetIO().Framerate);
                ImGui::End();
            }

            // 3. Show another simple window.
            if (show_another_window)
            {
                ImGui::Begin("Another Window", &show_another_window);   // Pass a pointer to our bool variable (the window will have a closing button that will clear the bool when clicked)
                ImGui::Text("Hello from another window!");
                if (ImGui::Button("Close Me"))
                    show_another_window = false;
                ImGui::End();
            }

            ImGui::Begin(item.main_window_title);
            ImGui::Text("fuck");
            ImGui::End();

            // Rendering
            ImGui::Render();
            //ImGui::GetIO().ConfigFlags = ImGuiConfigFlags_None;

            FrameContext* frameCtx = WaitForNextFrameResources(item);
            UINT backBufferIdx = item.swapchain->GetCurrentBackBufferIndex();
            frameCtx->CommandAllocator->Reset();

            D3D12_RESOURCE_BARRIER barrier = {};
            barrier.Type                   = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
            barrier.Flags                  = D3D12_RESOURCE_BARRIER_FLAG_NONE;
            barrier.Transition.pResource   = item.render_target_resource[backBufferIdx];
            barrier.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
            barrier.Transition.StateBefore = D3D12_RESOURCE_STATE_PRESENT;
            barrier.Transition.StateAfter  = D3D12_RESOURCE_STATE_RENDER_TARGET;
            g_pd3dCommandList->Reset(frameCtx->CommandAllocator, NULL);
            g_pd3dCommandList->ResourceBarrier(1, &barrier);

            // Render Dear ImGui graphics
            const float clear_color_with_alpha[4] = { item.clear_color.x * item.clear_color.w,
                item.clear_color.y * item.clear_color.w,
                item.clear_color.z * item.clear_color.w,
                item.clear_color.w };
            g_pd3dCommandList->ClearRenderTargetView(item.cpu_desc_handle[backBufferIdx], clear_color_with_alpha, 0, NULL);
            g_pd3dCommandList->OMSetRenderTargets(1, &item.cpu_desc_handle[backBufferIdx], FALSE, NULL);
            g_pd3dCommandList->SetDescriptorHeaps(1, &item.srv_desc_heap);
            ImGui_ImplDX12_RenderDrawData(ImGui::GetDrawData(), g_pd3dCommandList);
            barrier.Transition.StateBefore = D3D12_RESOURCE_STATE_RENDER_TARGET;
            barrier.Transition.StateAfter  = D3D12_RESOURCE_STATE_PRESENT;
            g_pd3dCommandList->ResourceBarrier(1, &barrier);
            g_pd3dCommandList->Close();

            g_pd3dCommandQueue->ExecuteCommandLists(1, (ID3D12CommandList* const*)&g_pd3dCommandList);

            // Update and Render additional Platform Windows
           

            //item.swapchain->Present(1, 0); // Present with vsync
             // Present with vsync
            //g_pSwapChain->Present(0, 0); // Present without vsync

            UINT64 fenceValue = g_fenceLastSignaledValue + 1;
            g_pd3dCommandQueue->Signal(g_fence, fenceValue);
            g_fenceLastSignaledValue = fenceValue;
            frameCtx->FenceValue = fenceValue;
        }
    }

    //WaitForLastSubmittedFrame();

    //// Cleanup
    //ImGui_ImplDX12_Shutdown();
    //ImGui_ImplWin32_Shutdown();
    //ImGui::DestroyContext();

    //CleanupDeviceD3D();
    ////::DestroyWindow(hwnd);
    //::UnregisterClassW(wc.lpszClassName, wc.hInstance);

    return 0;
}

// Helper functions
bool CreateDeviceD3D()
{
    // Setup swap chain
    DXGI_SWAP_CHAIN_DESC1 sd;
    {
        ZeroMemory(&sd, sizeof(sd));
        sd.BufferCount = NUM_BACK_BUFFERS;
        sd.Width = 0;
        sd.Height = 0;
        sd.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
        sd.Flags = DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING;
        sd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
        sd.SampleDesc.Count = 1;
        sd.SampleDesc.Quality = 0;
        sd.SwapEffect = DXGI_SWAP_EFFECT_FLIP_DISCARD;
        sd.AlphaMode = DXGI_ALPHA_MODE_UNSPECIFIED;
        sd.Scaling = DXGI_SCALING_STRETCH;
        sd.Stereo = FALSE;
    }

    // [DEBUG] Enable debug interface
#ifdef DX12_ENABLE_DEBUG_LAYER
    ID3D12Debug* pdx12Debug = NULL;
    if (SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&pdx12Debug))))
        pdx12Debug->EnableDebugLayer();
#endif

    // Create device
    D3D_FEATURE_LEVEL featureLevel = D3D_FEATURE_LEVEL_11_0;
    if (D3D12CreateDevice(NULL, featureLevel, IID_PPV_ARGS(&g_pd3dDevice)) != S_OK)
        return false;

    // [DEBUG] Setup debug interface to break on any warnings/errors
#ifdef DX12_ENABLE_DEBUG_LAYER
    if (pdx12Debug != NULL)
    {
        ID3D12InfoQueue* pInfoQueue = NULL;
        g_pd3dDevice->QueryInterface(IID_PPV_ARGS(&pInfoQueue));
        pInfoQueue->SetBreakOnSeverity(D3D12_MESSAGE_SEVERITY_ERROR, true);
        pInfoQueue->SetBreakOnSeverity(D3D12_MESSAGE_SEVERITY_CORRUPTION, true);
        pInfoQueue->SetBreakOnSeverity(D3D12_MESSAGE_SEVERITY_WARNING, true);
        pInfoQueue->Release();
        pdx12Debug->Release();
    }
#endif

    {
        D3D12_DESCRIPTOR_HEAP_DESC desc = {};
        desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_RTV;
        desc.NumDescriptors = frame_buffer_count;
        desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_NONE;
        desc.NodeMask = 1;
        SIZE_T rtvDescriptorSize = g_pd3dDevice->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV);
        for(auto& item : windows)
        {
            if (g_pd3dDevice->CreateDescriptorHeap(&desc, IID_PPV_ARGS(&item.rtv_desc_heap)) != S_OK)
                return false;

            D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle = item.rtv_desc_heap->GetCPUDescriptorHandleForHeapStart();
            for (auto& desc_item : item.cpu_desc_handle)
            {
                desc_item = rtvHandle;
                rtvHandle.ptr += rtvDescriptorSize;
            }
        }

        
    }

    {
        D3D12_DESCRIPTOR_HEAP_DESC desc = {};
        desc.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
        desc.NumDescriptors = 1;
        desc.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
        for(auto& item : windows)
        {
            if (g_pd3dDevice->CreateDescriptorHeap(&desc, IID_PPV_ARGS(&item.srv_desc_heap)) != S_OK)
                return false;
        }
    }

    {
        D3D12_COMMAND_QUEUE_DESC desc = {};
        desc.Type = D3D12_COMMAND_LIST_TYPE_DIRECT;
        desc.Flags = D3D12_COMMAND_QUEUE_FLAG_NONE;
        desc.NodeMask = 1;
        if (g_pd3dDevice->CreateCommandQueue(&desc, IID_PPV_ARGS(&g_pd3dCommandQueue)) != S_OK)
            return false;
    }

    for(auto& item : windows)
    {
        for (UINT i = 0; i < NUM_FRAMES_IN_FLIGHT; i++)
            if (g_pd3dDevice->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(&item.frameContext[i].CommandAllocator)) != S_OK)
                return false;
    }

    if (g_pd3dDevice->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT, windows[0].frameContext[0].CommandAllocator, NULL, IID_PPV_ARGS(&g_pd3dCommandList)) != S_OK ||
        g_pd3dCommandList->Close() != S_OK)
        return false;

    if (g_pd3dDevice->CreateFence(0, D3D12_FENCE_FLAG_NONE, IID_PPV_ARGS(&g_fence)) != S_OK)
        return false;

    g_fenceEvent = CreateEvent(NULL, FALSE, FALSE, NULL);
    if (g_fenceEvent == NULL)
        return false;

    {
        IDXGIFactory4* dxgiFactory = NULL;
        if (CreateDXGIFactory1(IID_PPV_ARGS(&dxgiFactory)) != S_OK)
            return false;
        for(auto& item : windows)
        {
            IDXGISwapChain1* swapChain1 = NULL;
            if (dxgiFactory->CreateSwapChainForHwnd(g_pd3dCommandQueue, item.window_header, &sd, NULL, NULL, &swapChain1) != S_OK)
                return false;
            if (swapChain1->QueryInterface(IID_PPV_ARGS(&item.swapchain)) != S_OK)
                return false;

            swapChain1->Release();
            //item.swapchain->SetMaximumFrameLatency(NUM_BACK_BUFFERS);
        }
        dxgiFactory->Release();
        
        //g_hSwapChainWaitableObject = g_pSwapChain->GetFrameLatencyWaitableObject();
    }

    CreateRenderTarget();
    return true;
}

void CleanupDeviceD3D()
{
    /*CleanupRenderTarget();
    if (g_pSwapChain) { g_pSwapChain->SetFullscreenState(false, NULL); g_pSwapChain->Release(); g_pSwapChain = NULL; }
    if (g_hSwapChainWaitableObject != NULL) { CloseHandle(g_hSwapChainWaitableObject); }
    for (UINT i = 0; i < NUM_FRAMES_IN_FLIGHT; i++)
        if (g_frameContext[i].CommandAllocator) { g_frameContext[i].CommandAllocator->Release(); g_frameContext[i].CommandAllocator = NULL; }
    if (g_pd3dCommandQueue) { g_pd3dCommandQueue->Release(); g_pd3dCommandQueue = NULL; }
    if (g_pd3dCommandList) { g_pd3dCommandList->Release(); g_pd3dCommandList = NULL; }
    if (g_pd3dRtvDescHeap) { g_pd3dRtvDescHeap->Release(); g_pd3dRtvDescHeap = NULL; }
    if (g_pd3dSrvDescHeap) { g_pd3dSrvDescHeap->Release(); g_pd3dSrvDescHeap = NULL; }
    if (g_fence) { g_fence->Release(); g_fence = NULL; }
    if (g_fenceEvent) { CloseHandle(g_fenceEvent); g_fenceEvent = NULL; }
    if (g_pd3dDevice) { g_pd3dDevice->Release(); g_pd3dDevice = NULL; }*/

#ifdef DX12_ENABLE_DEBUG_LAYER
    IDXGIDebug1* pDebug = NULL;
    if (SUCCEEDED(DXGIGetDebugInterface1(0, IID_PPV_ARGS(&pDebug))))
    {
        pDebug->ReportLiveObjects(DXGI_DEBUG_ALL, DXGI_DEBUG_RLO_SUMMARY);
        pDebug->Release();
    }
#endif
}

void CreateRenderTarget()
{
    for(auto& item : windows)
    {
        for (UINT i = 0; i < frame_buffer_count; i++)
        {
            item.swapchain->GetBuffer(i, IID_PPV_ARGS(&item.render_target_resource[i]));
            g_pd3dDevice->CreateRenderTargetView(item.render_target_resource[i], NULL, item.cpu_desc_handle[i]);
        }
    }
}

void CleanupRenderTarget()
{
    //WaitForLastSubmittedFrame();

    //for (UINT i = 0; i < NUM_BACK_BUFFERS; i++)
    //    if (g_mainRenderTargetResource[i]) { g_mainRenderTargetResource[i]->Release(); g_mainRenderTargetResource[i] = NULL; }

}

void WaitForLastSubmittedFrame(WindowInfo& info)
{
    FrameContext* frameCtx = &info.frameContext[g_frameIndex % NUM_FRAMES_IN_FLIGHT];

    UINT64 fenceValue = frameCtx->FenceValue;
    if (fenceValue == 0)
        return; // No fence was signaled

    frameCtx->FenceValue = 0;
    if (g_fence->GetCompletedValue() >= fenceValue)
        return;

    g_fence->SetEventOnCompletion(fenceValue, g_fenceEvent);
    WaitForSingleObject(g_fenceEvent, INFINITE);
}

FrameContext* WaitForNextFrameResources(WindowInfo& info)
{
    UINT nextFrameIndex = ++info.frame_index;
    
    FrameContext* frameCtx = &info.frameContext[nextFrameIndex % frame_buffer_count];
    UINT64 fenceValue = frameCtx->FenceValue;
    if (fenceValue < g_fence->GetCompletedValue()) // means no fence was signaled
    {
        frameCtx->FenceValue = 0;
        g_fence->SetEventOnCompletion(fenceValue, g_fenceEvent);
        WaitForSingleObject(g_fenceEvent, INFINITE);
    }

    return frameCtx;
}

// Forward declare message handler from imgui_impl_win32.cpp
extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

// Win32 message handler
// You can read the io.WantCaptureMouse, io.WantCaptureKeyboard flags to tell if dear imgui wants to use your inputs.
// - When io.WantCaptureMouse is true, do not dispatch mouse input data to your main application, or clear/overwrite your copy of the mouse data.
// - When io.WantCaptureKeyboard is true, do not dispatch keyboard input data to your main application, or clear/overwrite your copy of the keyboard data.
// Generally you may always pass all inputs to dear imgui, and hide them from your application based on those two flags.
LRESULT WINAPI WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
{

    /*if(ImGui::GetCurrentContext() != nullptr)
    {
        ImGui::GetIO().ConfigFlags = ImGuiConfigFlags_NoMouse;
        if(ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam))
        {
            ImGui::GetIO().ConfigFlags = ImGuiConfigFlags_None;
            return true;
        }
        ImGui::GetIO().ConfigFlags = ImGuiConfigFlags_None;
    }*/

    std::cout << "Current : " << ImGui::GetCurrentContext() << std::endl;

    if(ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam))
    {
        return true;
    }

    /*auto info = reinterpret_cast<WindowInfo*>(GetWindowLongPtrA(hWnd, GWLP_USERDATA));
    if (info!= nullptr)
    {
        ImGui::SetCurrentContext(info->imgui_context);
        if(ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam))
        {
            return true;
        }
    }*/

    

    switch (msg)
    {
    case WM_SIZE:
        if (g_pd3dDevice != NULL && wParam != SIZE_MINIMIZED)
        {
            /*WaitForLastSubmittedFrame();
            CleanupRenderTarget();
            HRESULT result = g_pSwapChain->ResizeBuffers(0, (UINT)LOWORD(lParam), (UINT)HIWORD(lParam), DXGI_FORMAT_UNKNOWN, DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT);
            assert(SUCCEEDED(result) && "Failed to resize swapchain.");
            CreateRenderTarget();*/
        }
        return 0;
    case WM_SYSCOMMAND:
        if ((wParam & 0xfff0) == SC_KEYMENU) // Disable ALT application menu
            return 0;
        break;
    case WM_DESTROY:
        ::PostQuitMessage(0);
        return 0;
    }
    return ::DefWindowProcW(hWnd, msg, wParam, lParam);
}

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.
- Please provide actual details.

Closing.
