### ISSUE TITLE
How to handle DPI correctly?

### ISSUE THREAD

**Issue by nikitanodar** [ocornut/imgui#6485]
**Version/Branch of Dear ImGui:**

Version: 1.89.2
Branch: don't know

**Back-end/Renderer/Compiler/OS**

Back-ends: custom `Vulkan` integration
Compiler: rustc 1.69.0
Operating System: Ubuntu 20.04.6

**My Issue/Question:**

I am using a rust crate, but I believe it's a straightforward port of the _original_ `imgui`. I am using a 4K monitor with 200% scale and trying to achieve a correct ui behavior in my application. When creating a window (with `winit` crate) I'm providing the DPI scale factor, which is 2.0 in my case. I have no idea what this means, but this is what the window API provides. Now, If I draw the ui normally, I get the following:

![1](https://github.com/ocornut/imgui/assets/132362566/757a27f4-329c-4f48-81d7-dd46271ef91a)

It looks so sharp and nice, but unfortunately, the ui is cut of in the middle of the window. Also, my mouse is offset by factor of 2, i.e. I can't just hover over the windows header and grab it, I need to move mouse right and bottom. On the screenshot above there's a highlighted item - in fact, the mouse was not over it during taking a picture.

As suggested, I tried to find a solution in FAQ and here what it says:

> The short answer is: obtain the desired DPI scale, load your fonts resized with that scale (always round down fonts size to the nearest integer), and scale your Style structure accordingly using style.ScaleAllSizes().

So I added this call in the beginning and here what I got:

![2](https://github.com/ocornut/imgui/assets/132362566/3d443503-ace6-4e32-b5a7-d6dc56edc82b)

The image is still sharp and good, but it seems nothing have changed, except margins and spacing between items. The window is still cut of in the middle of the window.

This cut of looks like a scissor problem. I modified the scissor by obtaining the dimensions from  the `draw_data`:

![3](https://github.com/ocornut/imgui/assets/132362566/54c600bb-c01e-482a-be0f-587159196c23)

It looks like all the window content is moved away. Indeed, if I move windows, I can find a place where the content is shown, so maybe it's a matrix problem?

I modified the matrix, by taking data from `draw_data` again:

![4](https://github.com/ocornut/imgui/assets/132362566/7131a416-8c6e-43cc-84ca-33adf15b6d13)

Now it works correct the mouse hovers over, the content is in place, the sizes seems correct, but it looks bad - the content was just scaled blurring the font. On this screenshot it looks ok, but if I make the font smaller, it becomes really really bad.

How to use this DPI thing correctly? What are the necessary steps and what I should pay attention to? Unfortunately, there's no example showing how to do it:

> The demo applications are not DPI aware so expect some blurriness on a 4K screen. For DPI awareness in your application, you can load/reload your font at a different scale and scale your style with `style.ScaleAllSizes()`

whis, as you see, does not work.

**Comment by ocornut** [comment]
I am afraid I need to take the blame for not providing DPI-compliant examples yet.
It's a seemingly simple problem but has many solutions and confusion points (Mac use different framebuffer<>window coordinates, Windows requires explicit per-process enabling etc.).

Use Metrics>Viewports to confirm the resolution perceived by dear imgui. I'm too busy at the moment but hoping to put a serious dent at this in a few versions. Currently trying to sort 1.90 then maybe I can look at formalizing standardized solutions for this before the amount of https://github.com/ocornut/imgui/labels/dpi issues explode.

**Comment by nikitanodar** [comment]
@ocornut In the Metrics->Viewports I see that indeed my single viewport  receives half of resolution in each axis. This probably comes from these lines:
```
io.display_framebuffer_scale = [hidpi_factor as f32, hidpi_factor as f32]; // hidpi_factor is 2
io.display_size = [logical_size.width as f32, logical_size.height as f32]; // logical size is [1440.0, 900.0]
```
I do not quite understand what does this mean The requested logical size is 1440x900. Since the scaling factor in the OS settings set to 200%, the actual window size is 2880x1800, the swapchain and surface sizes are also created with 2880x1800.

**Comment by ocornut** [comment]
In your situation I think you should leave framebuffer_scale as 1.0f and multiply display_size by hidpi_factor.
(It's a little bit different on a Mac however. I think on Mac we should provide backend support for scale/remap input coordinates. I'm not elaborating until done because I don't know to say incorrect things).

**Comment by nikitanodar** [comment]
Still doesn't work. I think there's something with rust's `winit` crate itself, because if I change the scale factor in OS settings, all the desktop elements are scaled, but the imgui stays the same. I.e. the font size 16 looks exactly the same on 100% and 200% scale. I don't know how this works, though.

Anyway, I'll wait the _official_ dpi examples. Thank you for the answers and for the great library.

**Comment by ocornut** [comment]
I don't think you are very far from solving it...

> I.e. the font size 16 looks exactly the same on 100% and 200% scale

When a app is DPI Aware it is supposed to handle scaling itself, so this looks right to me.
If the scale if 200% you should load a size 16*2 font and call style.ScaleAllSizes(2.0f) once.
Combine that with correct io.DisplaySize value and should are 99% there.

**Comment by nikitanodar** [comment]
No I am afraid I'm very far from cracking this puzzle :). I always load a fixed size font, never call `ScaleAllSizes`, but somehow it works on 100% and 200% scaling factors - the OS interface changes visually, the application's window size changes visually too, but the imgui's ui stays the same, nothing is blurred. I checked the font texture - it's also has the same size.

**Comment by ocornut** [comment]
If you follow the steps listed above it should work:

- io.DisplaySize should be correct
- io.DisplayFrameBufferScale should be 1,1
- Then load scaled font + call ScaleAllSizes

**Comment by ocbjsys** [comment]
@ocornut 

> I am afraid I need to take the blame for not providing DPI-compliant examples yet. It's a seemingly simple problem but has many solutions and confusion points (Mac use different framebuffer<>window coordinates, Windows requires explicit per-process enabling etc.).
> 
> Use Metrics>Viewports to confirm the resolution perceived by dear imgui. I'm too busy at the moment but hoping to put a serious dent at this in a few versions. Currently trying to sort 1.90 then maybe I can look at formalizing standardized solutions for this before the amount of [ dpi](https://github.com/ocornut/imgui/labels/dpi) issues explode.

It would be great if you did provide DPI-compliant examples. 

Part of what makes ImGui great is that it's cross-platform. 
I feel to claim being a cross-platform GUI is synonymous with with consistent rendering. 

We shouldn't have to dig around issues to tackle the DPI problem, given it's fairly simple.

**Comment by ocornut** [comment]
> It would be great if you did provide DPI-compliant examples.

Yes. But there are 100 other "if would be great" things. In the absence of focused help - since nearly no-one has been remotely trying to solve the problem globally, everybody submit one local fix not being considerate of how it would interfere with alternatives approach - we're stuck waiting until I have bandwidth available.

> We shouldn't have to dig around issues to tackle the DPI problem, given it's fairly simple.

It's not fairly simple. The solution have various issues I don't have a good solution for yet.

**Comment by AnubhavUjjawal** [comment]
Hi.

Full disclosure: I am trying C++ to create projects for the first time.I have had experience with it when doing leetcode in college.

For anyone trying to use SDL3 with imgui, and finding the text too grainy, I found this link effective:
https://pthom.github.io/imgui_bundle/faq.html#_high_dpi_with_dear_imgui

For macOS, they say to use:
`float windowDevicePixelRatio = NSScreen.mainScreen.backingScaleFactor;`

But you can simply create the following function:
```cpp
int get_window_device_pixel_ratio() {
    int wp, hp;
    SDL_GetWindowSizeInPixels(window, &wp, &hp);

    int w, h;
    SDL_GetWindowSize(window, &w, &h);

    return wp / w;
}
```

and use this method instead of using `NSScreen`. I have no idea what `NSScreen` is actually.
