### ISSUE TITLE
Suspicious function call in _ImGui::Columns_

### ISSUE THREAD

**Issue by septag** [ocornut/imgui#649]
I was running PVSStudio through your code and one of the warnings was in this part of code :
imgui.cpp (func: ImGui::Columns):
```
ButtonBehavior(column_rect, column_id, &hovered, &held, true);
```
The fifth argument seems to be an invalid type.

**Comment by ocornut** [comment]
Broken in 3eabad0321b7b7e949a87b3c6339fc5bea3403e7
It would have no side-effect, as true == `ImGuiButtonFlags_Repeat` and we were not using the return value of `ButtonBehavior` here which is the only thing affected by this flag.

Thanks!
