### ISSUE TITLE
Render many unicode characters cause fps drop a lot

### ISSUE THREAD

**Issue by dnhuy4869** [ocornut/imgui#6493]
Version: v1.89
Back-ends: imgui_impl_opengl3.cpp + imgui_impl_androidcpp

I want to render all unicode characters  in ArialUnicode.ttf using imgui, everything fine if i add a small glyph like Vietnamese, but if i add too much glyph as Chinese, fps will drop very much. I have tried all solution:

- Set font config oversapmle to 1
`fontConfig.OversampleH = 2;
fontConfig.OversampleV = `1;

-  Set io.Font flags
`io.Fonts->Flags |= ImFontAtlasFlags_NoPowerOfTwoHeight;
io.Fonts->Flags |= ImFontAtlasFlags_NoMouseCursors;`

Seem like nothing work, fps still drop a lot, is there any chance to render all unicode characters without fps drop ?

**Comment by GamingMinds-DanielC** [comment]
Your problem is a bit unclear. Do you actually want to render all Unicode characters every frame? That would be a lot of dynamically generated geometry, consider proper clipping to what is currently on screen. Or do you want to have all characters in the font atlas and render a subset of them? That would just be a huge texture and shouldn't be a real problem as long as everything needed still fits.

**Comment by dnhuy4869** [comment]
> Your problem is a bit unclear. Do you actually want to render all Unicode characters every frame? That would be a lot of dynamically generated geometry, consider proper clipping to what is currently on screen. Or do you want to have all characters in the font atlas and render a subset of them? That would just be a huge texture and shouldn't be a real problem as long as everything needed still fits.

 i want to have all characters in the font atlas and render a subset of them, but look like imgui will rasterize all glyphs in font atlas even it's not used

**Comment by GamingMinds-DanielC** [comment]
If you have control over which glyphs are actually used (f.e. for displaying static texts), you could scan your texts for the glyphs used and build your font atlas with only those needed glyphs. You can even occasionally (f.e. when loading a text file) rebuild your atlas.

If you potentially need all glyphs at any time (f.e. for dynamic inputs), you are currently out of luck. There is something in the making to handle this, but as far as I know it is an open ended effort, no idea when this will be finished:
https://github.com/ocornut/imgui/pull/3471
