### ISSUE TITLE
PDF Generation of ImGui Window

### ISSUE THREAD

**Issue by khaledelmonajjed** [ocornut/imgui#6494]
Operating System: Windows 11

Hey! I would just like to ask if it is possible to generate a PDF of a child window. There is no specific case really. Just a child window that has some text and images in it. I am just inquiring to see if anyone here has ever tried something like that or knows of a way that can take whatever is in a child window and print it the same way you would do to in Print -> Microsoft Print to PDF.
Thanks!

**Comment by InusualZ** [comment]
Well, since `imgui` emit vertices to the gpu through the selected backend. I think you can intercept all the vertex in a frame and convert them to pdf path. It should be do-able. I don't know if anyone have tried before. _You have have sparked some interest_.

**Comment by ClaasJG** [comment]
Maybe the approach from #6384 is useful.

**Comment by khaledelmonajjed** [comment]
Thanks! That's the info I was hoping to get. Appreciate that!
