### ISSUE TITLE
DELETE TEXT IN INPUT

### ISSUE THREAD

**Issue by dvtruong1001** [ocornut/imgui#6498]
Hello Everyone

I have a problem I hope you can help me

I am writing 1 imgui cheat menu for unity android game. i have unity_nativeInjectEvent function hook in libunity to handle keyboard input events. everything was fine until i hit the delete button.it didn't work. I have tried many ways but still can't work. hope you can help. here is my code: 

jboolean (*orig_unity__nativeInjectEvent)(JNIEnv *env, jobject object, jobject inputEvent);

jboolean unity_nativeInjectEvent(JNIEnv *env, jobject object, jobject inputEvent) {
	ImGuiIO &io = ImGui::GetIO();
	
	jclass motionEventClass = env->FindClass(OBFUSCATE("android/view/MotionEvent"));
	
	if (env->IsInstanceOf(inputEvent, motionEventClass)) {
		jmethodID getActionMethod = env->GetMethodID(motionEventClass, OBFUSCATE("getAction"), OBFUSCATE("()I"));
		jint getAction = env->CallIntMethod(inputEvent, getActionMethod);
		
		jmethodID getXMethod = env->GetMethodID(motionEventClass, OBFUSCATE("getX"), OBFUSCATE("()F"));
		jfloat getX = env->CallFloatMethod(inputEvent, getXMethod);
		
		jmethodID getYMethod = env->GetMethodID(motionEventClass, OBFUSCATE("getY"), OBFUSCATE("()F"));
		jfloat getY = env->CallFloatMethod(inputEvent, getYMethod);
		
		jmethodID getPointerCountMethod = env->GetMethodID(motionEventClass, OBFUSCATE("getPointerCount"), OBFUSCATE("()I"));
		jint getPointerCount = env->CallIntMethod(inputEvent, getPointerCountMethod);
		
		switch(getAction) {
			
		case 0:
			io.MouseDown[0] = true;
			break;
		case 1:
			io.MouseDown[0] = false;
			break;
		case 2:
			if (getPointerCount > 1) {
				io.MouseDown[0] = false;
			} else {
				io.MouseWheel = 0;
            }
			break;
		}
		io.MousePos = ImVec2(getX, getY);
		
		
	
	}
	
	jclass KeyEventClass = env->FindClass(OBFUSCATE("android/view/KeyEvent"));
	if (env->IsInstanceOf(inputEvent, KeyEventClass)) {
		jmethodID getActionMethod = env->GetMethodID(KeyEventClass, OBFUSCATE("getAction"), OBFUSCATE("()I"));
		if (env->CallIntMethod(inputEvent, getActionMethod) == 0) {
			jmethodID getKeyCodeMethod = env->GetMethodID(KeyEventClass, OBFUSCATE("getKeyCode"), OBFUSCATE("()I"));
			jmethodID getUnicodeCharMethod = env->GetMethodID(KeyEventClass, OBFUSCATE("getUnicodeChar"), OBFUSCATE("(I)I"));
			jmethodID getMetaStateMethod = env->GetMethodID(KeyEventClass, OBFUSCATE("getMetaState"), OBFUSCATE("()I"));
			jint keyCode = env->CallIntMethod(inputEvent, getKeyCodeMethod);
			if (keyCode == 67) { 
                

            }else{
			
			io.AddInputCharacter(env->CallIntMethod(inputEvent, getUnicodeCharMethod, env->CallIntMethod(inputEvent, getMetaStateMethod)));
			
			}
		}
	}
	
	
	
	return orig_unity__nativeInjectEvent(env, object, inputEvent);
}

**Comment by dvtruong1001** [comment]
I tried 
io.AddInputCharacter(ImGuiKey_Backspace);
io.KeysDown[ImGuiKey_Backspace] = true;
but nothing worked .
plz help me

**Comment by dvtruong1001** [comment]
![Screenshot_20230607-065441](https://github.com/ocornut/imgui/assets/113319562/13a43df1-49f2-4c76-8b31-82bea4c0323d)

**Comment by emoon** [comment]
https://github.com/ocornut/imgui/issues/1586

**Comment by ocornut** [comment]
Backspace is a key as well as a character it needs to be registered using `io.AddKeyEvent(ImGuiKey_Backspace, true); io.AddKeyEvent(ImGuiKey_Backspace, false);`
