### ISSUE TITLE
How can I drag and drop a file into some button and receive it address

### ISSUE THREAD

**Issue by w3arthur** [ocornut/imgui#6500]
Hi, I like to use this application a lot and trying to create some gui schemes from data files like CSV

I tried lots of ways to drag& drop files into InputText or a Button but it did not show me any result.
How can I apply the drag and drop of the file inside some area (like a Button) and receive its full address (like C:\file.csv )

Thanks for your help and for the great work on this great program.

**Comment by ocornut** [comment]
Didn't follow requested guidelines or issue template. 
- Please make sure you have read the guidelines and are providing desired information.
- Please edit your post (don't create a new post) with the Issue Template shown in "New Issue" and reply here when edited.

Closing.
