### ISSUE TITLE
First column of some tables aren't resizable.

### ISSUE THREAD

**Issue by sarchar** [ocornut/imgui#6503]
**Version/Branch of Dear ImGui:**

Version: 1.89.6
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC 2022
Operating System: Windows 11

**My Issue/Question:**

The first column of some tables aren't resizable.  Perhaps I'm misunderstanding a feature (rather than this being a bug).  Most of the tables in the example/demo have all columns resizable except the table in the Advanced tree.

This happens in example_glfw_opengl3.

I really think this is me misunderstanding how resizing works, but I am certain the "NoResize" flag is not set on the column and that Resizable *is* set on my tables.  

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/4928176/d001a7d7-031b-41c1-9fe4-d2c4ff47182f)

**Comment by ocornut** [comment]
Hello,
It appears to be a recent bug, where the combination of a table fix (f799a293c8 + d6ea56dfd9) and minor change to child windows 47579f8a40 revealed a ID collision. It happens on the first column of any table that has ScrollX or ScrollY enabled.

**Comment by ocornut** [comment]
I have pushed a fix 4fab72b and will work on a regression test when I have the time. Thanks for reporting!
