### ISSUE TITLE
Unable to render supplementary multilingual plane (SMP) characters

### ISSUE THREAD

**Issue by keriefie** [ocornut/imgui#6504]
I am trying to render characters from the Latin Extended-F block. But this applies to all Unicode characters above and including U+10000. They render as a question mark `?` despite adding them to the `GlyphRangesBuilder`
![image](https://github.com/ocornut/imgui/assets/124537276/f1a04da0-eafd-4cac-92a6-66dcace16526)
```c++
FontRanges defranges;
ImFontGlyphRangesBuilder builder;
builder.AddRanges(defranges.GetGlyphRangesLatinFull());
builder.AddRanges(defranges.GetGlyphRangesGreekFull());
builder.AddRanges(defranges.GetGlyphRangesCyrillicFull());

ImVector<ImWchar> ranges;
builder.BuildRanges(&ranges);

ImFont* font = io.Fonts->AddFontFromFileTTF("../../misc/fonts/unifont-15.0.06.otf", 28.0f, NULL, ranges.Data);
io.Fonts->AddFontFromFileTTF("../../misc/fonts/unifont_upper-15.0.06.otf", 28.0f, NULL, ranges.Data);
io.Fonts->Build();
```
`defranges.GetGlyphRangesLatinFull()` provides the ranges of Latin Extended-A to Latin Extended-F as well as Basic, Supplement, and Additional. (For use in IPA transcriptions)

It is already difficult to input SMP characters in C++ as the `U"\U10794"` escape character doesn't seem to do anything. I tried a variety of ways such as just inputting the character into the string `U"𐞔"`
```c++
std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> convert;
std::string sf = convert.from_bytes(U"𐞔");

ImGui::Text(sf.c_str());
```
But this also renders a question mark. 
So does this (Using ICU):
```c++
UChar32 c = UChar32(0x10794);

icu::UnicodeString s(c);

std::string sf;
s.toUTF8String(sf);

ImGui::Text(sf.c_str());
```
Why UTF-8 is still used when UTF-32 exists is beyond me.

**Comment by ocornut** [comment]
Have you read https://github.com/ocornut/imgui/blob/master/docs/FONTS.md ?

Namely the [About UTF-8 Encoding](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#about-utf-8-encoding) and [Debug Tools](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#debug-tools) section?

**Comment by ocornut** [comment]
I am actually going to close this as we provide detailed help in the links above, and without evidence that:

- (1) you have checked that your encoding is correct, using the tools we provide
- (2) you have checked that the glyphs you want and referenced in the text are properly loaded, using the tools we provide.

Our attempt to help would be wasted. It's generally one or the other. If it's not, please provide actual details and I will very happily reopen this issue and help.

**Comment by keriefie** [comment]
This isnt the right codepoint. 
![image](https://github.com/ocornut/imgui/assets/124537276/4b70eb1b-5969-447f-9f7d-f78538e4f128)
![image](https://github.com/ocornut/imgui/assets/124537276/890a1f0c-cedc-4847-9fdd-0dc2860ebefd)

**Comment by ocornut** [comment]
> This isnt the right codepoint.

Did you add `#define IMGUI_USE_WCHAR32` in your imconfig.h file?
We don't support characters past U+FFFF without it.

I have been considering making this the default and will evaluate that possibility later.

**Comment by keriefie** [comment]
Better, but still does not work
![image](https://github.com/ocornut/imgui/assets/124537276/f066bdef-e72c-4efb-bfc0-26f7cd89a9bd)
![image](https://github.com/ocornut/imgui/assets/124537276/54e68e0e-d725-40f5-8ab1-6df5209d60cd)

**Comment by keriefie** [comment]
These should correspond with MODIFIER LETTER SMALL CAPITAL G WITH
HOOK and BRAHMI LETTER JA respectively

**Comment by ocornut** [comment]
So encoding is right now.
Then you can look at the Glyphs inside the Fonts section and see what's loaded.

**Comment by keriefie** [comment]
From unifont-upper
![image](https://github.com/ocornut/imgui/assets/124537276/4be4c5fd-b542-4281-8d74-8d839fc7704e)
![image](https://github.com/ocornut/imgui/assets/124537276/695591aa-b959-460c-8e75-93220ef07b6f)

**Comment by keriefie** [comment]
Ah no nevermind got it
