### ISSUE TITLE
bd->GlProfileIsES3 not set for IMGUI_IMPL_OPENGL_ES3

### ISSUE THREAD

**Issue by jsm174** [ocornut/imgui#6508]
Hello.

I finally upgraded to the `v1.89.6` imgui which included the fix for the `glBindSampler` in https://github.com/ocornut/imgui/pull/6375

Unfortunately I still noticed the flicker. 

After stepping through the code on iOS, `GlProfileIsES3` is not true.

I think the `#ifdef` order is not correct (or needs to be reworked):

https://github.com/ocornut/imgui/blob/4fab72b40e2972f5d56fc884ed5797446238844e/backends/imgui_impl_opengl3.cpp#L286-L318

You end up skipping the `IMGUI_IMPL_OPENGL_ES3` path because of the `!defined(IMGUI_IMPL_OPENGL_ES2)`

Also, should `bd->GlVersion = 200` be `bd->GlVersion = 300` ?

**Comment by ocornut** [comment]
You are correct, my bad. 

The first commit dd9db5e8 introduced the bug, and my comment `bd->GlVersion = 200; // Don't raise version as it is intended as a desktop version check for now.` was incorrect as I had misunderstood that the upper path was taken for ES3.
I have no supposedly fixed both.

I have (I think) fixed this with dec082f

Unfortunately I do not have a ES2/ES3 testing path so those things are going blind hence this issue.
If someone wants to help setting up instructions for me to test some of ES3 on Windows it'd be appreciated.

**Comment by jsm174** [comment]
Just wanted to say I did test this on Android and iOS, and it is now working! Thank you!
