### ISSUE TITLE
docs don't mention that glyph_range needs to be persistent

### ISSUE THREAD

**Issue by paniq** [ocornut/imgui#651]
I had a puzzling hour yesterday figuring out why AddFont* wouldn't parse my glyph_range argument correctly, even crash at times, before I realized that the array has to remain persistent for an unspecified amount of time. Declaring the array as a static constant did indeed fix the problem.

Would it be possible to add to the header a short documentation for AddFont* that makes this known to the user, so future users (e.g. me in a year, having forgotten about all of this) don't run into the same problem?

**Comment by ocornut** [comment]
You are right, this is an overlook. It was already added by Doug as a comment in the extra_fonts/README file but it isn't mentioned everywhere.

FYI the "Unspecified amount of time" is currently until you call the `GetTexDataXXX` or `Build` function, but it may change as we introduce more dynamic atlas, so it is indeed unspecified. 

I will clarify the comments for now. May look into just copying the data.

**Comment by emoon** [comment]
In cases like this I wish there was a nice cross-platform way to do ```is_on_stack(pointer)``` I know it would be a bit tricky to support in edge-cases but still would be nice to have.

**Comment by ocornut** [comment]
I love that sort of helper. Perhaps we could approximate a portable version by comparing the distance between a local variable and the pointer. Bit dodgy but I can't see how it would ever fail to function?

**Comment by emoon** [comment]
might work but it highly depends then on how much stack space the caller uses which can be vary quite a bit (from next to nothing to several megs)

**Comment by ocornut** [comment]
I guess better have false negatives than false negatives. But yeah :/

**Comment by ocornut** [comment]
Added extra comment, @paniq do you think you would have stumbled on those comments?

**Comment by ratchetfreak** [comment]
It's undefined behavior to do ptr1 - ptr2 and use the output if they don't come from the same array (or aren't the same pointer). Ergo `bool is_on_stack(void* pointer){void* local; return abs(pointer - &local)>0x100000;}` is undefined.

Not to mention it won't help if the buffer was loaded into a `std::vector`. I feel that using such a helper would create more problems than it would solve.

**Comment by ocornut** [comment]
Fair points.

**Comment by paniq** [comment]
@ocornut yup, that fixes it for me. I always check the header declaration for comments. :)
