### ISSUE TITLE
Overlapped item gets click - even with SetItemAllowOverlap

### ISSUE THREAD

**Issue by abau** [ocornut/imgui#6512]
**Version/Branch of Dear ImGui:**

Version: 1.89.7 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl2.cpp + imgui_impl_sdl2.cpp
Compiler: gcc 13.1.1
Operating System: Linux

**My Issue/Question:**

I tried the example given in https://github.com/ocornut/imgui/issues/3909#issuecomment-799328231 with `SetItemAllowOverlap` after button 1, but unlike stated in the comment, when clicking into the intersection of both buttons, button 1 registers the click - not button 2. Did I miss anything?

**Comment by ocornut** [comment]
I believe my example in the linked comment is incorrect.

Low-level `ImGuiButtonFlags_AllowItemOverlap` needs to be set on the potentially overlapped item:

`ImGui::ButtonEx("11111", ImVec2(50, 50), ImGuiButtonFlags_AllowItemOverlap)`

As designed, I believe `SetItemAllowOverlap()` API is a little useless.

I believe this needs to be redesigned into, e.g. at minimum a `SetNextItemAllowOverlap()` variant.

**Comment by ocornut** [comment]
> I believe my example in the linked comment is incorrect.

Sorry it was too hasty to me to say that when it's not that simple.

Prior to 1.89 the code in https://github.com/ocornut/imgui/issues/3909#issuecomment-799328231 + all descriptions of behavior were fully accurate.

In 1.89 we internally started using a system for input-ownership (which wasn't really publicly advertised as a whole, but part of it was used in answers to specific problem). The way this system work broke the behavior of said snippet.
I am investigating and will post more details soon.

**Comment by abau** [comment]
`ImGuiButtonFlags_AllowItemOverlap` works. Thanks.

> I believe this needs to be redesigned 

From my point-of-view as a new Imgui-user, I expected that - by default - all subsequent widgets would take precedence when it comes to handling events. And in case this is not what the user wants, some kind of `ImGuiButtonFlags_Passthrough` flag could be set of subsequent widgets.

Anyways, thanks for your help.
