### ISSUE TITLE
ImGui_ImplOpenGL3_CreateFontsTexture failed randomly

### ISSUE THREAD

**Issue by dnhuy4869** [ocornut/imgui#6513]
Version: 1.89
Back-ends: imgui_impl_opengl3.cpp + imgui_impl_android.cpp

Currently i want to rebuild font atlas every new frame if there are new unicode characters found, but weird thing is it work fine in 30 -> 40 minutes or long time program run, and font texture recreate will fail somehow with error 0x500 (GL_INVALID_ENUM) or 0x502 (GL_INVALID_OPERATION) everything become black
If i try to recreate device object or font texture after error occur, i will get the same error. After font texture create failed i have to wait few minutes, and then it create successfully again, here is my code, i call it before ImGui::NewFrame

**Comment by dnhuy4869** [comment]
i hardcode TexWidth and TexHeight is 512 x 512, is this a problem ?

**Comment by nicolasnoble** [comment]
Smells like resource leak somehow.

**Comment by dnhuy4869** [comment]
> Smells like resource leak somehow.

do you mean memory leak ? i delete all texture and font before build and recreate font texture as you see above. Can you give me more detail ?

**Comment by dnhuy4869** [comment]
> Use RenderDoc to debug your application and find potentially leaking resources.

i'm pretty sure error come from font atlas rebuild only, because after i add unicode characters support everything still fine. I deleted all texture and font data before loading new into memory. What can be the problem here ?

`bool Renderer::DestroyFontsData()
{
	// Destroy old fonts data
	ImGuiIO& io = ImGui::GetIO();
	io.Fonts->Clear();
	io.Fonts->TexID = 0;

	GlyphRanges.clear();
	GlyphBuilder.Clear();

	return true;
}

bool Renderer::BuildGlyphRanges(ImVector<ImWchar>* outRanges, CArray<NAME_CACHE_DATA*>* customGlyphs)
{
	ImGuiIO& io = ImGui::GetIO();

	GlyphBuilder.AddRanges(io.Fonts->GetGlyphRangesVietnamese());

	// Add custom glyph from text
	if (customGlyphs && !customGlyphs->Empty())
	{
		int count = customGlyphs->Count;
		for (int i = 0; i < count; i++)
		{
			NAME_CACHE_DATA* data = customGlyphs->Data[i];
			if (!data)
			{
				continue;
			}

			GlyphBuilder.AddText(data->PlayerName.c_str());
		}
	}

	GlyphBuilder.BuildRanges(outRanges);

	return true;
}

bool Renderer::CreateFontsData(CArray<NAME_CACHE_DATA*>* customGlyphs)
{
	ImGuiIO& io = ImGui::GetIO();

	//io.Fonts->Flags |= ImFontAtlasFlags_NoPowerOfTwoHeight;
	io.Fonts->Flags |= ImFontAtlasFlags_NoMouseCursors;
	io.Fonts->TexDesiredWidth = 512;
	io.Fonts->TexDesiredHeight = 512;

	if (!BuildGlyphRanges(&GlyphRanges, customGlyphs))
	{
		return false;
	}

	if (!ArialFontData)
	{
		if (!LoadFileToMemory(&ArialFontData, ArialFontPath.c_str(), "rb"))
		{
			return false;
		}
	}

	if (!IconFontData)
	{
		if (!LoadFileToMemory(&IconFontData, IconFontPath.c_str(), "rb"))
		{
			return false;
		}
	}

	ImFontConfig fontConfig;
	fontConfig.OversampleH = 2;
	fontConfig.OversampleV = 1;
	fontConfig.FontDataOwnedByAtlas = false;

	if (!LoadFontFromMemory(
		&Renderer::Instance->MainFont, 
		ArialFontData->Data,
		ArialFontData->Size,
		FontPixelSize,
		&fontConfig,
		GlyphRanges.Data))
	{
		return false;
	}

	ImFontConfig mergeConfig;
	mergeConfig.OversampleH = 2;
	mergeConfig.OversampleV = 1;
	mergeConfig.MergeMode = true;
	mergeConfig.FontDataOwnedByAtlas = false;

	if (!LoadFontFromMemory(
		&Renderer::Instance->IconFont, 
		IconFontData->Data,
		IconFontData->Size,
		FontPixelSize, 
		&mergeConfig,
		GetGlyphRangesIcon()))
	{
		return false;
	}

	io.Fonts->Build();

	//CONSOLE_PRINT("TexWidth: %d", io.Fonts->TexWidth);
	//CONSOLE_PRINT("TexHeight: %d", io.Fonts->TexHeight);

	return true;
}`

**Comment by dnhuy4869** [comment]
i can't find any example about rebuild font atlas in imgui document, what i'm doing wrong here ? or there is any better way to render all unicode characters ?

**Comment by ocornut** [comment]
Did you solve your problem?
