### ISSUE TITLE
ImGui::InputText Doesnt Works Cant Write Or Delete Anything

### ISSUE THREAD

**Issue by VinieClara** [ocornut/imgui#6514]
char cfgcode[255] = "me";

ImGui::InputText("cfgcodd", cfgcode, IM_ARRAYSIZE(cfgcode));

basicly this is my imgui inputtext, on menu i see its rendered and i see it writes "me" inside i can aslo select text etc but i cant write anything or delete anything or do anything to that text help please, i use directx11 imgui

**Comment by ocornut** [comment]
Sorry but #1586
