### ISSUE TITLE
 imgui_impl_win32.cpp + imgui_impl_opengl3.cpp demo bug

### ISSUE THREAD

**Issue by yenixing** [ocornut/imgui#6516]
Version/Branch of Dear ImGui:

Version: Most recent version (cloned it from github)
Branch: master

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_win32.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC
Operating System: Windows 10 Pro Version 21H2

I just found a bug in [Line 233 in examples/example_win32_opengl3/main.cpp](https://github.com/ocornut/imgui/blob/master/examples/example_win32_opengl3/main.cpp#L233).

I think using ::DefWindowProcW instead of ::DefWindowProc

**Comment by ocornut** [comment]
You are right, I have pushed a fix 3cc9d20
Thank you !
