### ISSUE TITLE
  How to quickly select multiple rows 

### ISSUE THREAD

**Issue by iamasbcx** [ocornut/imgui#6518]
Version/Branch of Dear ImGui:

Version: 1.89.3 WIP
Branch: [docking](https://github.com/ocornut/imgui/issues/new)

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_dx11.cpp + imgui_impl_dx11.cpp
Compiler: VS 2019
Operating System: Win10

My Issue/Question:
Table & Colums      How to quickly select multiple rows when there are 10,000 rows, such as 500 rows   

   CTRL +left click ?   click line by line?

**Comment by ocornut** [comment]
This is currently not trivial to handle when a clipper is used.

This is exactly what the [range_select](https://github.com/ocornut/imgui/tree/features/range_select) branch is aiming to solve and support. I am aiming/hoping this will be finished and merged in master in 1-2 months, but if you want to try it it would be super helpful.

range_select branch can be merged in docking without conflict, so perhaps you can try it?

**Comment by iamasbcx** [comment]
very good   Compilation tests can be done using

**Comment by ocornut** [comment]
Hello,

The multi-select feature has now been merged in master.

You can find many demos in **Demo->Widgets->Selection State & Multi-Select**

Also see https://github.com/ocornut/imgui/wiki/Multi-Select
![image](https://github.com/user-attachments/assets/186e2a83-07a6-4853-b304-78dce292df6c)
