### ISSUE TITLE
Disappearing Revert button in style editor

### ISSUE THREAD

**Issue by petrihakkinen** [ocornut/imgui#652]
When a color is set to 0,0,0,0, the Revert button next to the color in the style editor disappears.

**Comment by ocornut** [comment]
Doesn't happen here. Revert button appears when the button is different from the reference style (which can be passed in parameter). I suppose it can be misleading since you may expect it to remember what has been changed.

**Comment by petrihakkinen** [comment]
Yes, I was expecting it to remember previous values, but now that I think of it, it's best handled on client side. Hmm, maybe the unexpected behavior happens only when ref is null. I'll check tomorrow (out of office). Any case, it would help if the 'ref' parameter was documented in the function description.

**Comment by ocornut** [comment]
Do you think that would be enough? (shall we close?)

The style editor could have more infrastructure to do that storage itself but it would stray a little from the patterns generally used in IMGUI. It is true that it isn't ultra obvious, perhaps the added comment can more naturally direct people into organizing their flow to work with that.

**Comment by petrihakkinen** [comment]
Looks good to me! I'll mark this as closed now.
