### ISSUE TITLE
Tables: Extra empty bottom row

### ISSUE THREAD

**Issue by Sinan-Karakaya** [ocornut/imgui#6524]
**Version/Branch of Dear ImGui:**

Version: 1.89.5
Branch: docking (0ea3b87bd63ecbf359585b7c235839146e84dedb)

**Back-end/Renderer/Compiler/OS**

Back-ends: Using ImGui-SFML
C++20
Operating System: WSL Ubuntu 22.04 LTS

**My Issue/Question:**

Hi. I am trying to display a simple table inside a tab that should display an array of strings. However, after trying different ways of 'navigating' inside my table while filling its cells, I keep having the same issue. I keep having an extra bottom row that is awfully big.

I have probably made a mistake in my code as I could not find any similar problem online. However, after searching for a few hours what the problem could be, I am simply at a loss as to where the problem is coming from. Thank you in advance for any help

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/91690021/d38927e9-847a-403a-9ead-20673eb8cb75)

_(As you can see, quite a big bottom row)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
inline static const std::array<std::string, 8> g_elevationGuide = {
    "elevation players linemate deraumere sibur mendiane phiras thystame",
    "1->2 1 1 0 0 0 0 0",
    "2->3 2 1 1 1 0 0 0",
    "3->4 2 2 0 1 0 2 0",
    "4->5 4 1 1 2 0 1 0",
    "5->6 4 1 2 1 3 0 0",
    "6->7 6 1 2 3 0 1 0",
    "7->8 6 2 2 2 2 2 1"
};

ImGui::Begin("Test");
if (ImGui::BeginTabBar("Panels") {
    // some panels
    // ....

    if (ImGui::BeginTabItem("Guides")) {
        ImGui::Text("Elevation Ritual Guide");
        if (ImGui::BeginTable("Ritual Guide", 8, ImGuiTableFlags_Resizable | ImGuiTableFlags_NoSavedSettings |
        ImGuiTableFlags_Borders | ImGuiTableFlags_ScrollX | ImGuiTableFlags_NoHostExtendY)) {

            const auto headers = zp::Utils::split(g_elevationGuide[0], ' ');
            for (auto &header : *headers) {
                ImGui::TableSetupColumn(header.c_str());
            }
            ImGui::TableHeadersRow();

            for (int idx = 0; auto &guide : g_elevationGuide) {
                if (idx == 0) {
                    ++idx;
                    continue;
                }
                const auto tokens = zp::Utils::split(guide, ' ');
                for (auto &elem : *tokens) {
                    ImGui::TableNextColumn();
                    ImGui::Text("%s", elem.c_str());
                }
            }
            ImGui::EndTable();
        }
        ImGui::EndTabItem();
    }
ImGui::End();
```

**Comment by ocornut** [comment]
If you use ScrollX it creates a child window and those need an explicit size and we don’t support auto-resizing child windows. With ScrollX, NoHostExtendY unfortunately has no effect here.

**Comment by Sinan-Karakaya** [comment]
I see, I removed it and it has the correct behavior indeed. Guess i'll have to stick to that, not that it's a huge problem in my case. Thanks for the help!

However I'm interested as to why ScrollX needs to create a child window?

**Comment by ocornut** [comment]
Child windows are providing a scrolling region.

**Comment by ocornut** [comment]
Technically speaking we could end up:
- Adding support for manually resizable child window (that's mostly an issue of settings persistence).
- Adding support for single-axis auto-resize of child window.

Those are requested/discussed in #1496 #1395 #1710 #1666.
So perhaps this can we improved later.

**Comment by Sinan-Karakaya** [comment]
I see, I'm looking forward for when those will be implemented. Thank you for your time!
