### ISSUE TITLE
How to drag file get path?   MFC ->DragQueryFile

### ISSUE THREAD

**Issue by iamasbcx** [ocornut/imgui#6533]
Version/Branch of Dear ImGui:

Version: 1.89.3 WIP
Branch: [docking](https://github.com/ocornut/imgui/issues/new)

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_dx11.cpp + imgui_impl_dx11.cpp
Compiler: VS 2019
Operating System: Win10

My Issue/Question:
How to drag file get path?        MFC ->DragQueryFile

**Comment by ocornut** [comment]
On Win32 see #2602
