### ISSUE TITLE
Non-working sliders when iterating through vector

### ISSUE THREAD

**Issue by mruegenberg** [ocornut/imgui#654]
I've found a pretty weird behavior where I can't influence slider values (I can drag, but the slider always snaps back to the original value).

Basically, the following fails:

    std::vector<float> foos;
    foos.push_back(0.3);
    // ...
    for(float s : foos) {
        ImGui::SliderFloat("float x", &s, 0.0f, 1.0f);
    }

but this works:

    std::vector<float> foos;
    foos.push_back(0.3);
    // ...
    for(float &s : foos) {
        ImGui::SliderFloat("float x", &s, 0.0f, 1.0f);
    }

I'm not sure if this is expected behavior and/or can even be reproduced on other systems (I compiled with g++ 6.1.1), but I'd be interested in the reasons for the failure.

In the attachment, there is a full `main.cpp` (as a txt, because Github only allows those)
[main.cpp.txt](https://github.com/ocornut/imgui/files/262186/main.cpp.txt)
 which can be dragged into `opengl_example` to reproduce the issue.

**Comment by aytekaman** [comment]
In the first case, you work on copied data so actual values in foo don't change. Second example works since you work on the actual elements in the container.

**Comment by ocornut** [comment]
Hello,

What @aytekaman said. The `for (float s : foos)` is making a copy of your value so you aren't editing the value in your array.

For the second, you need to resolve ID collision somehow as you can't have multiple fields in the same location with the same "float x" identifier. Please read the FAQ entry about usage of ID.

You can do 
```
for (int n = 0; n < foos.size(); n++)
{
   ImGui::PushId(n);  // push a unique id to remove ambiguity
   ImGui::SliderFloat("float x", &foos[n], 0.0f, 1.0f);
   ImGui::PopId();
}
```

If your values are pointers you can often push the pointer into the id stack.
