### ISSUE TITLE
Dynamically modify the font

### ISSUE THREAD

**Issue by Half-People** [ocornut/imgui#6547]
(Click "Preview" above ^ to turn URL into clickable links)

1. FOR FIRST-TIME USERS ISSUES COMPILING/LINKING/RUNNING or LOADING FONTS,  please use [GitHub Discussions](https://github.com/ocornut/imgui/discussions).

2. PLEASE CAREFULLY READ: [FAQ](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md)

3. PLEASE CAREFULLY READ: [Contributing Guidelines](https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md)

4. PLEASE MAKE SURE that you have: read the FAQ; explored the contents of `ShowDemoWindow()` including the Examples menu; searched among Issues; used your IDE to search for keywords in all sources and text files; and read the links above.

5. Be mindful that messages are being sent to the e-mail box of "Watching" users. Try to proof-read your messages before sending them. Edits are not seen by those users.

6. Delete points 1-6 and PLEASE FILL THE TEMPLATE BELOW before submitting your issue.

Thank you!

----

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: new
Branch: docking_(master/viewport/docking/etc.)_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_GLFW.cpp + imgui_impl_OpenGl.cpp _(or specify if using a custom engine/back-end)_
Compiler: vs2019_(if the question is related to building or platform specific features)_
Operating System: win10

**My Issue/Question:**

I am now updating the "HImGuiEditor" tool and need to add or modify fonts during rendering. I have written the function after the end of the frame and before the start of the frame. Normally, there should be no problem, but I have an error `Invalid style setting!`.
(The function I want to achieve is that the user can add or modify the fonts in the running)
 _(please provide as much context as possible)_

**Screenshots/Video**
![image](https://github.com/ocornut/imgui/assets/56476339/3c0ef0f8-3e83-43fa-a903-c7eb5393c5c3)
Video : [Youtube](https://youtu.be/zmVIXhPWEFY)
XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

```
//Below is just a shortest code that can reproduce the problem
io.Fonts->AddFontFromFileTTF("DependentFile\\kaiu.ttf", 20);

ImFont * TestFont;
int i = 0;
while(true)
{
        i++;
        if(i==2)
        {
             TestFont = io.Fonts->AddFontFromFileTTF("DependentFile\\arial.ttf", 20);  //<--- this will error 
         }

	glClear(GL_COLOR_BUFFER_BIT);

	ImGui_ImplOpenGL3_NewFrame();
	ImGui_ImplGlfw_NewFrame();
	ImGui::NewFrame();

        ImGui::Begin("bar bar bar");
        ImGui::PushFont(TestFont);
        ImGui::Text("BarBar");
        ImGui::PopFont();
        //Bar Bar Bar Bar Bar
        ImGui::End();


	ImGui::Render();
	ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

	glfwSwapBuffers(Windows);
	glfwPollEvents();
}
```

**Comment by Half-People** [comment]
I did not report an error after adding `buile` but all text disappeared
![image](https://github.com/ocornut/imgui/assets/56476339/2fb305a2-4013-408d-86fa-6c68a7288aec)

**Comment by Half-People** [comment]
> (Click "Preview" above ^ to turn URL into clickable links)
> 
> 1. FOR FIRST-TIME USERS ISSUES COMPILING/LINKING/RUNNING or LOADING FONTS,  please use [GitHub Discussions](https://github.com/ocornut/imgui/discussions).
> 2. PLEASE CAREFULLY READ: [FAQ](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md)
> 3. PLEASE CAREFULLY READ: [Contributing Guidelines](https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md)
> 4. PLEASE MAKE SURE that you have: read the FAQ; explored the contents of `ShowDemoWindow()` including the Examples menu; searched among Issues; used your IDE to search for keywords in all sources and text files; and read the links above.
> 5. Be mindful that messages are being sent to the e-mail box of "Watching" users. Try to proof-read your messages before sending them. Edits are not seen by those users.
> 6. Delete points 1-6 and PLEASE FILL THE TEMPLATE BELOW before submitting your issue.
> 
> Thank you!
> 
> _(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_
> 
> **Version/Branch of Dear ImGui:**
> 
> Version: new Branch: docking_(master/viewport/docking/etc.)_
> 
> **Back-end/Renderer/Compiler/OS**
> 
> Back-ends: imgui_impl_GLFW.cpp + imgui_impl_OpenGl.cpp _(or specify if using a custom engine/back-end)_ Compiler: vs2019_(if the question is related to building or platform specific features)_ Operating System: win10
> 
> **My Issue/Question:**
> 
> I am now updating the "HImGuiEditor" tool and need to add or modify fonts during rendering. I have written the function after the end of the frame and before the start of the frame. Normally, there should be no problem, but I have an error `Invalid style setting!`. (The function I want to achieve is that the user can add or modify the fonts in the running) _(please provide as much context as possible)_
> 
> **Screenshots/Video** ![image](https://user-images.githubusercontent.com/56476339/248421647-3c0ef0f8-3e83-43fa-a903-c7eb5393c5c3.png) Video : [Youtube](https://youtu.be/zmVIXhPWEFY) XXX _(you can drag files here)_
> 
> **Standalone, minimal, complete and verifiable example:** _(see #2261)_
> 
> ```
> //Below is just a shortest code that can reproduce the problem
> io.Fonts->AddFontFromFileTTF("DependentFile\\kaiu.ttf", 20);
> 
> ImFont * TestFont;
> int i = 0;
> while(true)
> {
>         i++;
>         if(i==2)
>         {
>              TestFont = io.Fonts->AddFontFromFileTTF("DependentFile\\arial.ttf", 20);  //<--- this will error 
>          }
> 
> 	glClear(GL_COLOR_BUFFER_BIT);
> 
> 	ImGui_ImplOpenGL3_NewFrame();
> 	ImGui_ImplGlfw_NewFrame();
> 	ImGui::NewFrame();
> 
>         ImGui::Begin("bar bar bar");
>         ImGui::PushFont(TestFont);
>         ImGui::Text("BarBar");
>         ImGui::PopFont();
>         //Bar Bar Bar Bar Bar
>         ImGui::End();
> 
> 
> 	ImGui::Render();
> 	ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
> 
> 	glfwSwapBuffers(Windows);
> 	glfwPollEvents();
> }
> ```

I did not report an error after adding `buile` but all text disappeared
![image](https://github.com/ocornut/imgui/assets/56476339/2fb305a2-4013-408d-86fa-6c68a7288aec)

**Comment by Half-People** [comment]
https://github.com/ocornut/imgui/assets/56476339/59d8a557-fe49-419c-9d29-91e1fa92bac5

I am very sorry that I have tested it but it still has no effect. I would like to ask if it is a problem with the ImGui version. :(

> 首先，定義您的構建字體函數：
> 
> ```c++
> void BuildFont(float fontSize)
> {
>     ImGuiIO& io = ImGui::GetIO();
>     io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\segoeui.ttf", fontSize);
>     io.Fonts->Build();
> }
> ```
> 
> 添加方法來指示需要重新加載/更改字體
> 
> ```c++
> bool reloadFont = false;
> ```
> 
> 在主循環中的之前`ImGui_Implxxx_NewFrame`，添加以下內容：
> 
> ```c++
> if (reloadFont)
> {
>     reloadFont = false;
>     io.Fonts->Clear();
>     BuildFont(fontSize);
> 
>     ImGui_ImplXXX_DestroyDeviceObjects(); // or ImGui_ImplXXX_InvalidateDeviceObjects();
>     ImGui_ImplXXX_CreateDeviceObjects();
> }
> ```
> 
>  錄音.2023-07-13.225131.mp4

**Comment by sakiodre** [comment]
There is a problem in `RootWindow->ReCreateObject()`, you are missing the `()`:
It should looks like:
```cpp
    ImGui_ImplOpenGL3_DestroyDeviceObjects();
    ImGui_ImplOpenGL3_CreateDeviceObjects();
```

**Comment by Half-People** [comment]
My God, I actually made such a low-level error. It has been successfully run. Thank you very much for your help.
