### ISSUE TITLE
Viewport sizing errors

### ISSUE THREAD

**Issue by dgm3333** [ocornut/imgui#6548]
Version: 1.89.5
Branch: docking
Back-ends: (imgui_impl_opengl3 | imgui_impl_dx11) & (imgui_impl_win32.cpp | imgui_impl_glfw)
Compiler: Visual Studio
Operating System: Windows 10

I'm think it's probably related to the various screen dimension errors in https://github.com/ocornut/imgui/issues/6444 but not totally sure so submitted it separately

This code:
```
        if (ImGui::Begin("square", NULL, ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoInputs)) {

            ImGui::SetWindowPos({ 10.0f, 10.0f });
            ImGui::SetWindowSize({ 10.0f, 10.0f });

        }
        ImGui::End();
```

Produces these viewports - which are correctly positioned where I would expect it to be, but nowhere near the correct size.

GLFW ogl3:
![image](https://github.com/ocornut/imgui/assets/51210/89643ce1-4edc-4e4f-8a6c-2d85daad63ff)

Win32 ogl3 (without dpi awareness)
![image](https://github.com/ocornut/imgui/assets/51210/a4ab27c5-fee6-4045-98c3-6509003d69ca)

Win32 ogl3 (with ImGui_ImplWin32_EnableDpiAwareness())
![image](https://github.com/ocornut/imgui/assets/51210/df93531e-e19b-4954-97c2-f680c8e22a6a)

Win32 dx11 (without dpi awareness)
![image](https://github.com/ocornut/imgui/assets/51210/c627793d-8983-44ac-8913-2bbac28a4822)

Win32 dx11 (with ImGui_ImplWin32_EnableDpiAwareness())
![image](https://github.com/ocornut/imgui/assets/51210/1edc2bed-3fb2-4d20-b6ee-e8010006d310)

This is plain background just for comparison (the standard Visual Studio window)
![image](https://github.com/ocornut/imgui/assets/51210/ef6a47b9-5aa7-44c7-ad84-149fec06aefc)

**Comment by ocornut** [comment]
- GLFW always enable DPI awareness. 
- in style there’s a WindowMinSize value which is larger than 10x10 by default.

**Comment by dgm3333** [comment]
oh thanks
