### ISSUE TITLE
Filtering events when enabling install_callbacks on GLFW

### ISSUE THREAD

**Issue by grazianobolla** [ocornut/imgui#6550]
(Click "Preview" above ^ to turn URL into clickable links)

1. FOR FIRST-TIME USERS ISSUES COMPILING/LINKING/RUNNING or LOADING FONTS,  please use [GitHub Discussions](https://github.com/ocornut/imgui/discussions).

2. PLEASE CAREFULLY READ: [FAQ](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md)

3. PLEASE CAREFULLY READ: [Contributing Guidelines](https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md)

4. PLEASE MAKE SURE that you have: read the FAQ; explored the contents of `ShowDemoWindow()` including the Examples menu; searched among Issues; used your IDE to search for keywords in all sources and text files; and read the links above.

5. Be mindful that messages are being sent to the e-mail box of "Watching" users. Try to proof-read your messages before sending them. Edits are not seen by those users.

6. Delete points 1-6 and PLEASE FILL THE TEMPLATE BELOW before submitting your issue.

Thank you!

----

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.89.6
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Linux

**My Issue/Question:**

When initializing the ImGui context, the second paramenter in `ImGui_ImplGlfw_InitForOpenGL(window, false);` specifies whenever to install callbacks or not, if set to true, GLFW callbacks for ImGui will be installed automatically without me having to do anything, and all callbacks set previously will be chain-called, which is cool and works OK.

The problem is, if I use that option (which allows me to not have to mess with my custom input code), ImGui runs perfectly, but any inputs that I generate that should be directed only to ImGui also get passed to my game engine, so if I type X key on a ImGui input my player will also jump lets say.

So I opted for not installing callbacks and instead did this (which I found on the Faq):

```cpp
void mk::Input::key_input_callback(GLFWwindow *window, int key, int code, int action, int mods) // my callback
{
    bool imGuiOnlyEvent = mk::ImGUIHelper::add_keyboard_event(key, action == GLFW_PRESS);

    if (imGuiOnlyEvent == false)
    {
        mk::Engine *engine = static_cast<mk::Engine *>(glfwGetWindowUserPointer(window));
        engine->on_input(InputEvent{
            .type = TYPE::KEYBOARD,
            .code = key,
            .action = action});
    }
}

//other file
bool mk::ImGUIHelper::add_keyboard_event(int key, bool pressed)
{
    imgui_io->AddKeyEvent(key_from_glfw(key), pressed);
    return imgui_io->WantCaptureKeyboard;
}
```

Is not the big deal but I would like to know if I can avoid this, or what are the best practices regarding this topic with GLFW and ImGui.

**Comment by ocornut** [comment]
> inputs that I generate that should be directed only to ImGui also get passed to my game engine,

Why not simply testing io.WantCaptureKeyboard in your chained handler? It seems like you know what the solution is but you are implementing it in a cumbersome way instead of the straightforward way.

**Comment by ocornut** [comment]
Ping @grazianobolla ?

**Comment by grazianobolla** [comment]
You can close the issue. Thanks
