### ISSUE TITLE
Problem In my game resize  :( 

### ISSUE THREAD

**Issue by Cornato** [ocornut/imgui#6554]
i have my own game and when imgui run on my own game and the player make resize for game window not the imgui there is some thing wrong happ i will make small video for it, look at the video and u will see what wall happ when i try to resize my game window the <3  

using imgui Dx9 and make detours to make it in my own game 

https://github.com/ocornut/imgui/assets/56580276/87a72022-f340-4616-a07c-d5e38add6788

**Comment by ocornut** [comment]
Following our private messages, I have given you another chance to submit an issue but it looks like you wasted it.
