### ISSUE TITLE
How to select tab programmatically?

### ISSUE THREAD

**Issue by pozemka** [ocornut/imgui#6555]
Version: 1.89.6

Hello. Sorry if I miss something obvious. But is there a way to select tabs programmatically?

For example if I creating tabs dynamically and requested tab is already open I need to switch to it.

I understand how to implement it with child windows, but what about tabs?

**Comment by ocornut** [comment]
Do you mean a docked window (for which you need to set focus for) or a tab manually created with BeginTabItem (for which there is a flag to select).

**Comment by pozemka** [comment]
Oh my! Somehow I missed that BeginTabItem() has flags and was completely sure that `p_open` is the last parameter. Probably was looking on something else.
Yes `ImGuiTabItemFlags_SetSelected` is what I was looking for.
