### ISSUE TITLE
clicking - / + on numeric input fields counts twice

### ISSUE THREAD

**Issue by paniq** [ocornut/imgui#656]
When clicking on any of the + / - buttons of numeric inputs in the demo window (e.g. "Widgets -> input int"), both the click and the mouse button release cause a change in the number, allowing to only change numbers by stepsize 2 rather than 1.

This happens with the SDL2 / GL3 example backend.

**Comment by ocornut** [comment]
Thanks. Affects `ImGuiButtonFlags_Repeat flag` Looks like it was introduced 12 days ago during this refactor: https://github.com/ocornut/imgui/commit/547f34cf22640526b63f02f50c73ef9409e8acab
So it shouldn't be in 1.48 at least. Fixing now.

**Comment by ocornut** [comment]
Also fixed a minor century-old bug where holding a repeating button `ImGuiButtonFlags_PressedOnClickRelease | ImGuiButtonFlags_Repeat` would also return true on release whereas it shouldn't. It was barely noticeable unless the RepeatRate is very slow.

**Comment by ocornut** [comment]
Btw thanks for switching to latest/master. I really need some people to be up to date because it is the only way to find bugs early. Not to pretend that tagged releases are any less buggy :)
