### ISSUE TITLE
How to nest a ImGui::Begin

### ISSUE THREAD

**Issue by aliule2020** [ocornut/imgui#6562]
why it failed? How to correct?  
    ImGui::Begin("act", 0, ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoBackground | 
     ImGuiWindowFlags_NoTitleBar);
    ImGui::SetWindowSize(ImVec2{ 400,100 });
    ImGui::SetWindowPos(ImVec2{ 0, 25 });
    ImGui::PushStyleColor(ImGuiCol_Button, ImVec4{0,255,0,255});
    ImGui::PushStyleColor(ImGuiCol_Text, ImVec4{ 0,0,0,1 });
    if (ImGui::Button("start", ImVec2{ 100,100 }))
    {
        ImGui::Begin("input", &inputbool, ImGuiWindowFlags_Modal);
        ImGui::SetWindowPos(ImVec2{ 500, 350 });
        ImGui::SetWindowSize(ImVec2{ 600,150 });
        ImGui::SetWindowFontScale(1.5);
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4{ 0,0,0,1 });
        ImGui::InputDouble(strinputmsg.c_str(), pinputv);
        if (ImGui::Button("OK", ImVec2{ 100,50 }))
        {
            inputbool = false;
        }
        ImGui::End();  
    }
    ImGui::PopStyleColor(2);
    ImGui::End();

**Comment by MidTerm-CN** [comment]
You can use the ImGui::OpenPopup and ImGui::BeginPopup

**Comment by aliule2020** [comment]
it doesn‘t work. Can you give a example

**Comment by ocornut** [comment]
Your code suggest a misunderstanding of how dear imgui works.
`Button()` will return true during the 1 frame where the button is pressed.

Refer to the imgui demo window about how to use popups, there are amble example.
You should have the demo available in your app, but it's also there: https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html
