### ISSUE TITLE
Blank screen when porting to DirectX 8

### ISSUE THREAD

**Issue by luxploit** [ocornut/imgui#6564]
**Version/Branch of Dear ImGui:**

Version: 1.89.7 WIP (655aae5)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx8.cpp + imgui_impl_win32.cpp
Compiler: MSVC (Visual Studio 2015)
Operating System: Windows 11 22H2

**My Issue**

I've been trying to port ImGui to DirectX 8.1b. So far I've managed to spawn the window and draw the background color, however none of the ImGui windows itself are displaying. They are however being created and are clickable, as I've set `ImGuiDebugLogFlags_EventMask_ ` on DebugLogFlags to see if they were even being created. 

I've attached the ported code aswell as the Installer for the DirectX 8.1b. To compile this however you will need to add an environment variable called DXSDK81 as the older DirectX SDK doesn't set one by itself. 
Additionally you may need to edit the line `typedef void * POINTER_64 PVOID64;` in winnt.h, as compiling with the DirectX 8.1 SDK causes an error on some machines, to `typedef void * POINTER_64, * PVOID64;`. 
This requires changing ownership of the file (Located at C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h` from SYSTEM to your own user, and giving yourself the "Full Control" permission flag.

**Attachments**
[example_win32_directx8.zip](https://github.com/ocornut/imgui/files/11926921/example_win32_directx8.zip)

![image](https://github.com/ocornut/imgui/assets/113054610/912dfb7d-d683-4749-9b21-9f16c4f2c4f5)
![image](https://github.com/ocornut/imgui/assets/113054610/5be8f65e-bd15-4ae7-9279-28fda697a29a)

**Comment by ocornut** [comment]
Hello,

Not much of this is a dear imgui question.
You are essentially asking us to debug your DX8 code here.

I personnally don’t know DX8 but hope you get it working, I see no reason for it to not work.

**Comment by GamingMinds-DanielC** [comment]
It has been ages since I used DX8. At a quick glance I couldn't see any obvious mistakes in your backend. I don't know how good RenderDoc is with DX8, but you should give it a try. If it works with that version, it's a great tool to debug rendering of any kind.

**Comment by EthernalRaine** [comment]
![image](https://github.com/ocornut/imgui/assets/113054610/4c94e326-7924-4db0-9fce-79029df16d93)
I seem to have fixed the core rendering issue, I didn't set the stream source correctly. Now I have to find an alternative to SetScissorRect as that API doesn't exist on DirectX 8

**Comment by GamingMinds-DanielC** [comment]
As an alternative, you can set the render viewport and a properly configured projection matrix.

**Comment by ocornut** [comment]
Using a vertex shader may be more natural.

**Comment by EthernalRaine** [comment]
> As an alternative, you can set the render viewport and a properly configured projection matrix.

![image](https://github.com/ocornut/imgui/assets/113054610/fd2b9a88-17aa-44e3-994a-64eb14744b92)
![image](https://github.com/ocornut/imgui/assets/113054610/46439289-3012-440e-ac94-bb1aae127445)

I've been trying with clip it using the viewport, didn't quite work out.

```c
 // Clip overflow using viewport
const RECT r = { (LONG)clip_min.x, (LONG)clip_min.y, (LONG)clip_max.x, (LONG)clip_max.y };

D3DVIEWPORT8 clipped_viewport = {
    r.left, r.top,
    r.right - r.left,
    r.bottom - r.top,
    0.f, 1.f
};
bd->pd3dDevice->SetViewport(&clipped_viewport);
```

**Comment by GamingMinds-DanielC** [comment]
That looks strange. Did you adjust the projection as well? And did you reset the viewport to the old value at the end?

**Comment by ocornut** [comment]
Even if you can get it to work this way (and I think you can) I suspect altering viewport may be flushing too many things in the pipeline, I would recommend using a vertex shader.

**Comment by EthernalRaine** [comment]
I'll try out using clip planes later today. 
     
     
      
     
    
    
     
      
       
      
      
       
      
     
    
    
    
     
     
       On Wednesday, Jul 05, 2023 at 3:13 pm, Daniel Cremers ***@***.***> wrote: 
       
      
      
       
      I don't think a vertex shader would help much since it doesn't know about the triangles that the vertex is part of. 
      As for the adjustment of the projection matrix:: just as it is set up at the end of your ImGui_ImplDX8_SetupRenderState() function, but with the clip rect taken into account. 
      Another alternative would be to set up four clip planes using IDirect3DDevice8::SetClipPlane(). The documentation states how to set up the clip planes. Don't forget to enable them in the render states. 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/ocornut/imgui/issues/6564#issuecomment-1621732974","url": "https://github.com/ocornut/imgui/issues/6564#issuecomment-1621732974","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by leeqiufeng** [comment]
> I'll try out using clip planes later today.

hello , have you fixed imgui with dx8 ?

**Comment by EthernalRaine** [comment]
I have not worked on this for a while no. But you're welcome to try it out, I'll upload the latest zip of my dx8 port later this week when I return home.

**Comment by leeqiufeng** [comment]
> 

Looking forward to your new version

**Comment by darkmathew** [comment]
@luxploit Could you tell us what you did and how you managed to compile the application with DirectX 8? I'm on Windows 10, with Visual Studio 2022. I know that the Windows SDK is too advanced to work with D3D8, because of this we have (several) problems with "winnt.h" but I would like to know how to do it. Thanks in advance.

**Comment by ocornut** [comment]
Closing as stale. AFAIK there's no released DX8 backend, so if you have one it would be nice to publish it e.g. on github and we could add it to https://github.com/ocornut/imgui/wiki/Bindings#frameworkengine-backends
