### ISSUE TITLE
ImageButton inside loop

### ISSUE THREAD

**Issue by ParkSeungwon** [ocornut/imgui#6567]
In case there are Many ImageButtons inside loop, only the first one can be executed when clicked. Is this bug? If I change it to a normal Button , it works fine.
```
for(int i=0;   i<10; i++ ) {
  if(ImageButton()) {
     cout << i;
  }
}
```
First button works, prints 0. Other button does not work.

Maybe this is due to same texturID?

**Comment by ocornut** [comment]
Use PushID() in loops.
This is explained in the FAQ.
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system
