### ISSUE TITLE
ImGui::Image() disable transparency?

### ISSUE THREAD

**Issue by Zydak** [ocornut/imgui#6569]
**Version/Branch of Dear ImGui:**

Version: 1.89.6
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: GCC
Operating System: Manjaro Linux

**My Issue/Question:**

I'm using Vulkan, i have 2 render passes first one is Geometry render pass, it has framebuffer where i draw all my geometry and the second one is ImGui render pass it has separate framebuffer where i draw UI. Geometry render pass executes first and then in ImGui render pass i take image view of the geometry frame buffer color image create, descriptor of it using ImGui_ImplVulkan_AddTexture() and pass this descriptor into ImGui::Image(). I am doing it this way to have my geometry drawn inside resizable viewport. Everything works except one thing and this thing is transparent texture inside geometry framebuffer. I'm 100% sure that geometry pass works as intended because i captured frame using nvidia nsights and in geometry frame buffer this transparent texture looks like this: 
![image1](https://github.com/ocornut/imgui/assets/104147005/bd53f4b6-5dbb-4bd2-9e7d-a7ed02ac7221) 
but when I'm printing the same geometry framebuffer using ImGui::Image() this texture looks like this: 
![image2](https://github.com/ocornut/imgui/assets/104147005/aa7ccfa5-5a8b-4f1d-b373-97d226e5f14e)
white color comes from ImGui, it is white because i set it to light theme using ImGui::StyleColorsLight() so it is better visible. So i guess ImGui just clears transparency with it's own clear color? How can I prevent this so texture in viewport will look like on the first image? Can I somehow disable "transparency clearing"? I can't find any way to get this working.

**Screenshots/Video**

Geometry frame buffer image: 
![image3](https://github.com/ocornut/imgui/assets/104147005/1592aa62-8c98-4ef4-aaab-0d647305d1ea)

printing Geometry frame buffer image with ImGui::Image() :
![image4](https://github.com/ocornut/imgui/assets/104147005/e1c0eefd-222d-4d21-abc1-70238c8dc60f)

**Standalone, minimal, complete and verifiable example:**

**// Create image view of image with 2 textures with transparent one on top of the other one**
VkDescriptorSet descriptor = (VkDescriptorSet)ImGui_ImplVulkan_AddTexture(sampler, image_view, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
ImGui::Begin("Viewport");
ImGui::Image(descriptor, {x, y});
ImGui::End();

**Comment by Demonese** [comment]
Can you provide the pixel value (RGBA) of the transparent part of the Geometry frame buffer through RenderDoc?

**Comment by Zydak** [comment]
(0.01, 0.01, 0.01, 0.00)
![image5](https://github.com/ocornut/imgui/assets/104147005/5dc371f3-6779-4283-82f0-ae5bc86c37c0)
![image6](https://github.com/ocornut/imgui/assets/104147005/0d64702d-6d76-4c88-b3d7-a3ef77b27f89)

RGB depends on what's behind it but Alpha is always zero

**Comment by ocornut** [comment]
Image() only creates 4 vertices mapped with this texture and uv it doesn’t do much. See how the vulkan backend is rendering textures (eg blending equations) it may or not match your desired output but you basically have access to all the code there. Divide and conquer by trying with manually loaded texture.

**Comment by Zydak** [comment]
Ok thanks for the info! I'll see what I can do. I guess I'll close this issue then as it is related to Vulkan and not ImGui.

**Comment by ocornut** [comment]
I think there’s a possibility backend could be improved but you’d have to dig. With most other backends, we suggest using ImDrawList::AddCallback() to be able to alter the render state of rendering loop (eg if people need different blending setup), but I am not entirely sure yet it is your problem it may be something else. And altering render state of the Vulkan or DX12 may be a bit challenging without access to its data structure so we may need to alter design somehow.

**Comment by hassanjor** [comment]
Having the same problem right now 

Rendering scene to an ImGuiTexture using ImGui::Image
![Image](https://github.com/user-attachments/assets/e6463e5f-54f2-4992-aed1-31f282b0261b)

Rendering scene normally to the swapchain pass with no imgui
![Image](https://github.com/user-attachments/assets/1ec20993-b788-4763-9246-624972da7414)


PS. dont worry about how objects look in the different images its because in the first image im setting material data to different values so they look better so it has nothing to do with ImGui. But regarding transparency yea I have no clue why rendering to an ImGui::Image messes up transparency? could also be something related to how I create my offscreen renderpass.

**Comment by Zydak** [comment]
I solved it by changing the blending a little bit. The problem was that when rendering transparent object the Alpha inside the framebuffer is set to 0, when you pass that image with alpha 0 to imgui, it will render it transparent (you have dark theme in imgui hence the black quads). The solution is to never have alpha below 1 on a pixel inside framebuffer when passing it to imgui. So either call `discard` in fragment shader on transparent pixels or change the blending to:

```
srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
alphaBlendOp = VK_BLEND_OP_ADD;
```
so the pixel will get the transparency of whatever is behind it.

**Comment by hassanjor** [comment]
> I solved it by changing the blending a little bit. The problem was that when rendering transparent object the Alpha inside the framebuffer is set to 0, when you pass that image with alpha 0 to imgui, it will render it transparent (you have dark theme in imgui hence the black quads). The solution is to never have alpha below 1 on a pixel inside framebuffer when passing it to imgui. So either call `discard` in fragment shader on transparent pixels or change the blending to:
> 
> ```
> srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
> dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
> alphaBlendOp = VK_BLEND_OP_ADD;
> ```
> 
> so the pixel will get the transparency of whatever is behind currently rendered object.

That solved it, thanks!
