### ISSUE TITLE
Any method to use online font texture atlas builder like fontstash in IMGUI?

### ISSUE THREAD

**Issue by zeroxer** [ocornut/imgui#6571]
Is there anyway to intergrate [fontstash](https://github.com/memononen/fontstash) to IMGUI? Generating font textrues what current frame needs is very elegant for gui application.

Any method or example is helpful.

**Comment by ocornut** [comment]
It's not currently possible but we aim to provide an equivalent solution. 
We need to finish #3761 first.

Currently you can only rebuild the full atlas.
