### ISSUE TITLE
New platform window resizing behaviour?

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#6572]
After upgrading to 1.89.7 docking on glfw and sdl backends (with opengl3): while resizing main window all content is resized until main window resizing is finished. I could not find references in the changelog
![resizeGIF](https://github.com/ocornut/imgui/assets/1795930/d1db2fde-a364-4d60-9338-8adf2e9a6736)

**Comment by ocornut** [comment]
This has nothing to do with dear imgui it's something handled by your app, or perhaps SDL.
It's not likely this has changed at all..

By default in Windows resizing using native decorations goes into a modal blocking loop for the application, and application needs special code to handle that.
But resizing using ImGui decorations in multi-viewports is smooth.

**Comment by Demonese** [comment]
Scaling is done by the Desktop Window Manager (DWM).
All updates and rendering will be blocked when the window is sizing, DWM will use the last rendering result to scale.

**Comment by sonoro1234** [comment]
> My intuition is this never worked for Victor before but they just noticed it. The fact that it works better on secondary viewports managed by imgui backends can make this confusing.

Yes, thats the case!!
I still have not been able to tell the relevant difference between imgui and cimgui sdl2_opengl3 examples (where the content of platform window is freezed while resizing) and LuaJIT-ImGui window (where the content is scaled)
