### ISSUE TITLE
[Demo] Selectable covering Button on the same line, is this by design?

### ISSUE THREAD

**Issue by Demonese** [ocornut/imgui#6574]
**Version/Branch of Dear ImGui:**

Version: 1.89.7
Branch: features/range_select

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: MSVC 19.36.32535
Operating System: Windows 11 22H2

**My Issue/Question:**

Is this by design?

_EX: I didn't find any API that can change the z-order of widgets, maybe some related APIs should be added_

**Screenshots/Video**

![D9F336B8960E14478878702A81492E2F](https://github.com/ocornut/imgui/assets/57629614/6fda840d-e371-40fa-8089-576ee7caf60b)

**Standalone, minimal, complete and verifiable example:**

**Comment by GamingMinds-DanielC** [comment]
Hard to say without any code, but it seems you have `ImGuiTreeNodeFlags_SpanAvailWidth` active. Using the available with is the purpose of that flag.

**Comment by PathogenDavid** [comment]
You need to call `SetNextItemAllowOverlap` to explicitly enable support for overlapping widgets.

IE:

```cpp
static bool selected[3] = { false, false, false };
ImGui::SetNextItemAllowOverlap(); ImGui::Selectable("main.c",    &selected[0]); ImGui::SameLine(); ImGui::Button("Link 1");
ImGui::SetNextItemAllowOverlap(); ImGui::Selectable("Hello.cpp", &selected[1]); ImGui::SameLine(); ImGui::Button("Link 2");
ImGui::SetNextItemAllowOverlap(); ImGui::Selectable("Hello.h",   &selected[2]); ImGui::SameLine(); ImGui::Button("Link 3");
```

**Comment by Demonese** [comment]
> You need to call `SetNextItemAllowOverlap` to explicitly enable support for overlapping widgets.

This is a new API, I didn't understand what it did at first, thanks for the answer!

**Comment by ocornut** [comment]
Thank you for pointing this out.
Actually I think it was a mistake that I committed it in range_select branch, I recall it was a test and I didn't finish the thing.
I will rework this section so the button look the right size + use `SetNextItemAllowOverlap()` here and there.

**Comment by ocornut** [comment]
I have pushed 9a15730 with some use of SetNextItemAllowOverlap() in the demo.
