### ISSUE TITLE
Allow to specify "size_pixels" to AddFontDefault

### ISSUE THREAD

**Issue by marius-luca-87** [ocornut/imgui#658]
Hi,

It would be helpful to expose controlling the default font size in case we want to initialize the atlas differently using the embedded font file:
IMGUI_API ImFont*           AddFontDefault(const ImFontConfig* font_cfg = NULL);
to
IMGUI_API ImFont*           AddFontDefault(float size_pixels = 13.f, const ImFontConfig* font_cfg = NULL);

Thanks

**Comment by ocornut** [comment]
The default font doesn't really scale nor it meant to scale. 
If you knowingly really intend to do so you can use:
```
const char* ttf_compressed_base85 = GetDefaultCompressedFontDataTTFBase85();
ImFont* font = AddFontFromMemoryCompressedBase85TTF(ttf_compressed_base85, 13.0f, &font_cfg, GetGlyphRangesDefault());
```
