### ISSUE TITLE
Cannot click on menuItem or buttons in a context menu in a modal window

### ISSUE THREAD

**Issue by system64MC** [ocornut/imgui#6584]
Hi, I try to create a context menu inside of a modal window, however, I can't click on any entry or on any button in this context menu.
Here is the code I wrote : 
`if(igBeginPopupModal(winName.cstring, nil)):
    var size: ImVec2
    igGetWindowSizeNonUDT(size.addr)
    if(size.x < 512):
        igSetWindowSize(winName.cstring, ImVec2(x: 512, y: size.y))
    if(size.y < 512):
        igSetWindowSize(winName.cstring, ImVec2(x: size.x, y: 512))
    if(igButton("Close")):
        igCloseCurrentPopup()
    
    if(igBeginTable("tableBox", 16, (ImGuiTableFlags.SizingFixedSame.int or ImGuiTableFlags.ScrollX.int or ImGuiTableFlags.ScrollY.int).ImGuiTableFlags)):
        for i in 0..<16:
            igTableNextRow()
            for j in 0..<16:
                igTableNextColumn()
                let bIndex = i * 16 + j
                
                igBeginChild(($bIndex).cstring, ImVec2(x: 256, y: 256), true, ImGuiWindowFlags.NoResize)
                module.drawModuleBox(bIndex, module.moduleList)
                # igButton(("x:" & $j & " y:" & $i).cstring, ImVec2(x: 256, y: 256))
                igEndChild()
                if(igBeginPopupContextItem(("moduleContextBox" & $bIndex).cstring)):
                    if(igButton("test")):
                        echo "button Test"
                        igCloseCurrentPopup()
                    if(igMenuItem("test")):
                        echo "Test 1"
                    if(igMenuItem("Test 2")):
                        echo "Test 2"
                    igEndPopup()
                # drawModuleCreationContextMenuBox(bIndex, module.moduleList, module.outputIndex)
                # drawModuleCreationContextMenu(index)
                continue
        scrollPoint.x = igGetScrollX()
        scrollPoint.y = igGetScrollY()
        igEndTable()
    igEndPopup()`

What can I do to solve this problem?
Thanks for your help!

Infos about ImGUI and compilation : 

Version: 1.85
Branch: Master

Back-ends: NimGL's ImGUI bindings
Compiler: Nim's compiler and GCC
Operating System: Windows 11

**Comment by ocornut** [comment]
What was your problem?

**Comment by system64MC** [comment]
Hi,
Sorry if I closed the issue. Someone told me the I reported the issue the wrong way and recommanded me to close it to avoid problems.

But what happens is I can't interact with this context menu in a popup modal, while it works properly in the main window.
![image](https://github.com/ocornut/imgui/assets/42580501/54018357-3964-4232-984c-e7b0c48eb299)
