### ISSUE TITLE
Docking title rendered multiple times.

### ISSUE THREAD

**Issue by Nuxar1** [ocornut/imgui#6589]
Had a very basic issue when using docking. 

The title of the window was rendered over the tab bar causing it to have 2 texts ontop of each other.
A simple fix would be to add a simple check in the RenderWindowTitleBarContents function at the top to not render the title on docked windows:

```c++
void ImGui::RenderWindowTitleBarContents(ImGuiWindow* window, const ImRect& title_bar_rect, const char* name, bool* p_open, bool* maximize)
{

    if (window->DockIsActive)
        return;
```

**Comment by ocornut** [comment]
This function is not called on docked windows.
Sorry but #1586
