### ISSUE TITLE
Allow InputIntN and InputFloatN to accept arrays of pointers

### ISSUE THREAD

**Issue by EliasD** [ocornut/imgui#659]
I have a struct which looks like this:

```cpp
struct Vector2i {
    int x;
    int y;
}
```

And I want to be able to modify it easily with InputInt2. It would be nice to be able to do this:

```cpp 
int* arr[] = {&vec.x, vec.y};
ImGui::InputInt2("some vector", arr);
```

But right now it's impossible as I have to create new array of ints which is not very easy to do when I have to create such array for each Vectror2i I want to modify with InputInt2.

The implementation would be quite straightforward and won't differ from InputIntN much (because it already passes int* to InputInt):

```cpp
bool ImGui::InputIntN(const char* label, int** v, int components, ImGuiInputTextFlags extra_flags) {
   ... // same code as in InputIntN(const char* label, int* v, int components, ImGuiInputTextFlags extra_flags)
      value_changed |= ImGui::InputInt("##v", v[i], 0, 0, extra_flags); // v[i] instead of &v[i]
   ...
}
```

**Comment by ocornut** [comment]
You can just pass &vec.x to InputInt2().

**Comment by EliasD** [comment]
This works because of how struct's ints are structured inside the memory, but doesn't really look safe, because if for some reason I decide to change the order of ints in struct like this:
```cpp
struct Vector2i {
    int y;
    int x;
}
```

Then the code won't work anymore (in fact, this will crash the program), while the code I proposed will because it doesn't depend on the order at all.

**Comment by ocornut** [comment]
Yee, but are you actually going to invert x and y EVER in your Vector2 class?

Those are the most common cases and they aren't going to change. For other cases you can copy the data. I don't think there is a need to create new api entry points for a theoritical case.

**Comment by EliasD** [comment]
Yes, this example is kinda absurd, but it's possible to have struct where the order of variables is not determined. They also may have other members, there also may be some alignment, etc...

Copying the data is not a problem, it's just impossible to do with free functions which accept such structs. (static int[] won't work in that case, because the function may be used for different vectors).
Here's a function I need to make:

```cpp
void f(Vector2i& v) {
     ...
     int* arr[] = {&vec.x, &vec.y};
     ImGui::InputInt2("some vector", arr);
     ...
}
```

If this still isn't strong enough argument, then the issue may be closed and I'll just write my own version of InputIntN based on the same code.

**Comment by ocornut** [comment]
> Yes, this example is kinda absurd, but it's possible to have struct where the order of variables is not determined. They also may have other members, there also may be some alignment, etc...

And would you need to call InputInt2() on them?
Is that a problem you are having right now?

> Copying the data is not a problem, it's just impossible to do with free functions which accept such structs. (static int[] won't work in that case, because the function may be used for different vectors).

Not sure to understand the meaning of this.

Why don't you do:
```
int arr[2] = { vec.x, vec.y )
if (ImGui::InputInt2(..., arr))
   { vec.x = arr[0]; vec.y = arr[1]; }
```
And you can do wrap that.
I don't understand why a new core function need to be added since the copying around cost is so marginal here.

**Comment by EliasD** [comment]
Okay, fair enough, I though that this was a useful function to have. Thanks for suggestion. :)

P.S. Your second example is like this, but with two ints:
```cpp
int newInt = oldInt;
if (ImGui::InputInt(..., &newInt)) {
     oldInt = newInt;
}
```

While right now I can do this:
```cpp
ImGui::InputInt(..., &oldInt);
```

So I expected to be able to do this:

```cpp
ImGui::InputInt2(..., &oldInt1, &oldInt2) // or the way I suggested
```

**Comment by ocornut** [comment]
You can create a InputInt2() in your sources files that takes 2 `int*` if you want, copy them to an array to be contiguous and call regular InputInt2() that takes contiguous int.

**Comment by EliasD** [comment]
Yes, that's what I'm going to do then. :)
Thanks again.

**Comment by ocornut** [comment]
np
