### ISSUE TITLE
IsKeyPressed() triggered twice in a row

### ISSUE THREAD

**Issue by sarchar** [ocornut/imgui#6590]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: 1.89.7 (18971)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC 2022 17.6.2
Operating System: Win11

**My Issue/Question:**

I'm getting double fires on ImGui::IsKeyPressed(...).  IOW, IsKeyPressed returns true for two frames in a row.

**Screenshots/Video**

I pressed 'e' with no modifiers:

frame 0x2054:

![image](https://github.com/ocornut/imgui/assets/4928176/8ec53b5a-70c9-4f9e-9ec2-d68e7c739860)

frame 0x2055:

![image](https://github.com/ocornut/imgui/assets/4928176/5397161b-be1d-4494-a728-3697e066f7f4)

I would be happy to run/test this in the demo app but I'm unsure where to look.

**Comment by jeffkdev** [comment]
The second event be a repeat key, try `false` for the second parameter in IsKeyPressed (default is true).
```IMGUI_API bool          IsKeyPressed(int user_key_index, bool repeat = true);               // was key pressed (went from !Down to Down)? if repeat=true, uses io.KeyRepeatDelay / KeyRepeatRate```

**Comment by sarchar** [comment]
Would it be better to figure out the repeat rate instead of passing false to every call of IsKeyPressed? This is one single frame difference.

**Comment by sarchar** [comment]
Oh, well I made a silly.  The reason it's happening two in a row is because of the debugger stopping on the first. I'll close out the issue.
