### ISSUE TITLE
Dock in center with dock builder

### ISSUE THREAD

**Issue by wilricknl** [ocornut/imgui#6593]
**Version/Branch of Dear ImGui:**

Version: 1.89.6
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.h + imgui_impl_opengl3.h 
Operating System: Windows/Linux

**My Issue/Question:**

DockBuilder provides `DockBuilderSplitNode` to split nodes in all directions except the center. Is there a way to programmatically dock one node in the center of another node? I'm ending up with quite a lot of windows and I would like to dock some in center of each other upon program launch.

```cpp
ImGuiID dockViewportSettingsWindow;
ImGuiID dockSnapshotWindow;
ImGui::DockBuilderSplitNode(dockViewportSettingsWindow, ImGuiDir_Down, 0.5f, &dockSnapshotWindow, &dockViewportSettingsWindow);
```

For example, split down (code above) puts one window below another window.

![image](https://github.com/ocornut/imgui/assets/83393813/e7d5d219-fe75-4915-b8a2-8c4775f8c503)

What I want is to dock to the center of another window as shown below, but it's not clear to me how to achieve that via code.

![image](https://github.com/ocornut/imgui/assets/83393813/7fb10f27-3897-4efc-bece-dc31bb2c3ecd)

**Comment by GamingMinds-DanielC** [comment]
Don't split the node, just use `ImGui::SetNextWindowDockID()` to dock the second window into the exact same node as the first.

**Comment by wilricknl** [comment]
Aha, I thought an `ImGuiID` was unique per window. Now after splitting the dockspace I use one of the ids for multiple windows which puts them in the same node. Thanks!

```cpp
ImGuiID dockViewportSettingsWindow;
ImGui::DockBuilderDockWindow("Viewport Settings", dockViewportSettingsWindow);
ImGui::DockBuilderDockWindow("Snapshot", dockViewportSettingsWindow);
```
