### ISSUE TITLE
Remap Tab key

### ISSUE THREAD

**Issue by darkvad1010** [ocornut/imgui#6595]
I was using this code to "remap" tab and shift+tab, now with the updated API, this is obsolete. I've tried to use addkeyevent but when I press the key, it repeatedly advances the cursor in a infinite loop it seems. Clearly I'm doing something wrong, not sure I have the best understanding of these functions.

```
// Old code:

if (ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_RightArrow)))
{
      g.FocusedTabPressed = true;
}

// New code:

if (ImGui::IsKeyPressed(ImGuiKey_RightArrow))
{
      io.AddKeyEvent(ImGuiKey_Tab, true); 
      ImGui::SetKeyEventNativeData(ImGuiKey_Tab, 9, 0x000F);
      io.AddKeyEvent(ImGuiKey_Tab, false);
      ImGui::SetKeyEventNativeData(ImGuiKey_Tab, 9, 0x000F);
}
```

**Comment by ocornut** [comment]
You'll need to either modify your backend to emit the right key, or modify the input queue after the backend submitted to it and before Dear ImGui has a chance to consume events.

You can use code like this one:
https://github.com/ocornut/imgui/pull/5723#issuecomment-1260905083
