### ISSUE TITLE
Add #ifndef IMGUI_DISABLE to all the backends

### ISSUE THREAD

**Issue by yosoymin** [ocornut/imgui#6601]
Version: all
Branch: all

Back-ends: all
Operating System: all

I'm disabling imgui by configuration, because I don't want to distribute my application with imgui. I'm using imgui for internal tools, so the Distribution build defines IMGUI_DISABLE, but I have to modify some backends in order to avoid compilation errors when compiling that configuration. I've tried ignoring the files in cmake with expressions like this:

`set_source_files_properties(${backendSourceList} PROPERTIES HEADER_FILE_ONLY $<IF:$<CONFIG:Distribution>,TRUE,FALSE>)`

but set_source_files_properties doesn't allow generator expressions. So at the end I have to add `#ifndef IMGUI_DISABLE` manually to the backends I use. This is an inconvenience when I want to update imgui library.

If anyone knows another way to achiveve this, please let me know.
Thanks.

**Comment by ocornut** [comment]
Hello,
I am pretty sure this is something you can solve with your build system and that cmake can do this.
However for sake of completeness I don’t mind adding support for this in the backends.

**Comment by GamingMinds-DanielC** [comment]
Easy fix:
You can exclude the backend sources from the build without modifying them. If you want to control this with defines, you can just not add them to the project and instead include them in a redirector like this:
```c++
// imgui_impl_custom_redirect.cpp
#ifndef IMGUI_DISABLE
#include "imgui_impl_any_backend.cpp"
#endif
```

**Comment by ocornut** [comment]
Modified all backends to support this: 33e13c8
