### ISSUE TITLE
ImGui keyboard events are not recognized when keys are rebinded

### ISSUE THREAD

**Issue by sodamouse** [ocornut/imgui#6604]
**Version/Branch of Dear ImGui:**

Version: 1.89.7
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl.opengl3.cpp
Compiler: clang++
Operating System: Archlinux

**My Issue/Question:**

Hi, my users report that in cases where they have rebound keys (eg. CapsLock -> LCTRL), ImGui is not able to to recognize the key presses. I have confirmed this myself. To reproduce in Linux under X11:

```
xmodmap -e "remove lock = Caps_Lock"
xmodmap -e "add control = Caps_Lock"
xmodmap -e "keycode 66 = Control_L"
```

Perhaps I'm not using the API correctly (example below)?

**Screenshots/Video**

None

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
if (ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_LeftCtrl)) &&
    ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_Q)))
{
    glfwSetWindowShouldClose(window, true);
}

if (ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_LeftCtrl)) &&
    ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_S)))
{
    save_database_to_file(Amelie::activeDbPath);
}

if (ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_LeftCtrl)) &&
    ImGui::IsKeyPressed(ImGui::GetKeyIndex(ImGuiKey_N)))
{
    create_entry();
}
```

**Comment by ocornut** [comment]
Use the debug log to see what the backend is emitting and look at backend code.

Btw GetKeyIndex() is a unnecessary no-op with new backends you can remove it.

**Comment by ocornut** [comment]
Also you ought to use ImGuiMo_Ctrl for a mod. The exact relationship between mods and correspond L/R keys is ambiguously platform defined, as many platforms have specific handling for mods (eg sticky keys under windows).

**Comment by sodamouse** [comment]
According to debug log, imgui is still identifying the rebinded key as CapsLock.

**Comment by ocornut** [comment]
Then presumably dear imgui has nothing to do with this and this is what GLFW reports…

**Comment by sodamouse** [comment]
Yes this is just related to the glfw backend. This issue can be closed.

**Comment by sodamouse** [comment]
This issue can be marked as resolved thanks to feedback provided in the comments.
