### ISSUE TITLE
Rounding error when setting up openGL viewport   (with -ffast-math)

### ISSUE THREAD

**Issue by m9710797** [ocornut/imgui#6606]
Hi,

I've fixed a rounding error in `imgui_impl_opengl3.cpp`:

```
diff --git a/imgui_impl_opengl3.cpp b/imgui_impl_opengl3.cpp
index b603fff87..a985d40af 100644
--- a/imgui_impl_opengl3.cpp
+++ b/imgui_impl_opengl3.cpp
@@ -457,8 +457,8 @@ static void ImGui_ImplOpenGL3_SetupRenderState(ImDrawData* draw_data, int fb_wid
 void    ImGui_ImplOpenGL3_RenderDrawData(ImDrawData* draw_data)
 {
     // Avoid rendering when minimized, scale coordinates for retina displays (screen coordinates != framebuffer coordinates)
-    int fb_width = (int)(draw_data->DisplaySize.x * draw_data->FramebufferScale.x);
-    int fb_height = (int)(draw_data->DisplaySize.y * draw_data->FramebufferScale.y);
+    int fb_width = (int)(draw_data->DisplaySize.x * draw_data->FramebufferScale.x + 0.5f);
+    int fb_height = (int)(draw_data->DisplaySize.y * draw_data->FramebufferScale.y + 0.5f);
     if (fb_width <= 0 || fb_height <= 0)
         return;
```

The problem was that `FramebufferScale.x` contained the value `0.999999940395` instead of `1.0`. And that resulted in `fb_width=1279` instead of `1280` (which further leads to blurry fonts).
In `imgui_impl_sdl2.cpp` this value gets calculated as:
```
    int display_w = ...
    int w = ...
    io.DisplayFramebufferScale = ImVec2((float)display_w / w, ...);
```
In my case `display_w` and `w` have the same integer value, but the resulting float division was not exactly `1.0`. This problem only occurs when I'm compiling with the (gcc) compiler flag `-ffast-math`. 

Question: is compiling Dear ImGui with `-ffast-math` a supported use case? Because in my current setup it's not easy to specify different compiler flags for different .cpp files.

**Comment by m9710797** [comment]
I compared `imgui_impl_sdl2.cpp` with `imgui_impl_glfw.cpp`. The latter calculates `DisplayFramebufferScale` as:
```
io.DisplayFramebufferScale = ImVec2((float)display_w / (float)w, ...);
```
So cast both numerator and denominator to float (the sdl2 version only casts the numerator). Unfortunately that does not fix the rounding error :(

**Comment by ocornut** [comment]
See #6529

**Comment by m9710797** [comment]
Thanks for the quick response.
That's indeed exactly the same problem (with a different solution).
I missed it when searching for existing issues. Sorry about that.
I'm closing this issue.

**Comment by ocornut** [comment]
Seeing you both stumbled on this “facade” issue and you suggest a solution not using a double, I am not against fixing this one particular issue. However I am confident there are likely going to be many other issues which may become harder to spot and understand, so answer from other thread standa.

**Comment by sergeyn** [comment]
On x86 using _mm_div_ss directly prevents use of reciprorals

**Comment by m9710797** [comment]
For me it would be useful if you could import this fix. But I'd also understand if you don't want to support this use case. Thanks either way.

So far this is the only issue I encountered when running with `-ffast-math`. I'm using a reasonable subset of all features, but not everything of course.

**Comment by martin-ejdestig** [comment]
Just ran into this issue (blurry text when building with -ffast-math). I am going to solve it with just disabling -ffast-math when building ImGUI.

However, I wonder. Is this not an error that can occur without -ffast-math? Going from float to int by just casting can potentially produce unwanted values?
