### ISSUE TITLE
Suggestion: Change cast style for IM_COL32

### ISSUE THREAD

**Issue by Aarkham** [ocornut/imgui#6608]
**Version/Branch of Dear ImGui:**

Version: 1.89.6 WIP 
Branch: viewport/docking

**Back-end/Renderer/Compiler/OS**

I think this is not important.
Back-ends: custom engine/back-end, 
Compiler: Visual Studio
Operating System: Windows

**My Issue/Question:**

I'm using Qt Creator and it uses clang to help while writing code with tips and warnings in the margin.
Every time that the macro IM_COL32 is used it will inform you that there is a "Use of old style cast".

If I change the definition of the macro from 
```
#define IM_COL32(R,G,B,A)    (((ImU32)(A)<<IM_COL32_A_SHIFT) | ((ImU32)(B)<<IM_COL32_B_SHIFT) | ((ImU32)(G)<<IM_COL32_G_SHIFT) | ((ImU32)(R)<<IM_COL32_R_SHIFT))
```

to

```
#define IM_COL32(R,G,B,A)    ((static_cast<ImU32>(A)<<IM_COL32_A_SHIFT) | ((static_cast<ImU32>(B)<<IM_COL32_B_SHIFT) | (static_cast<ImU32>(G)<<IM_COL32_G_SHIFT) | static_cast<ImU32>(R)<<IM_COL32_R_SHIFT))
```

The warnings dissapear.  So I suggest change the macro definition.

Thanks

  Carlos

**Screenshots/Video**
![image](https://github.com/ocornut/imgui/assets/8093144/f51f175e-55cf-475d-b0d3-18ed3fd9f3c7)

**Comment by ocornut** [comment]
Hello,

It probably follow the warnings enabled in your codebase. Therefore you can disable the warning or use another macro. But we won’t make that change in our codebase as we use that style in many more other places.
