### ISSUE TITLE
Redundant scrollbar with BeginChild inside a table 

### ISSUE THREAD

**Issue by nem0** [ocornut/imgui#6619]
**Version/Branch of Dear ImGui:**

Version: 07d1709ca2759ab78a19c26c141a99cf8080b2a9 (the latest)
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp, but also custom backend
Compiler: VS2022
Operating System: Win10

**My Issue/Question:**

I'm trying to use table API instead of old columns API to create layout like in the attached screenshot, but there is unnecessary scrollbar, caused by child window inside table.  It works fine when using columns API.

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/153526/a23de7f5-6fde-497b-8a29-74197665a6ce)

**Standalone, minimal, complete and verifiable example:**
```
    if (ImGui::Begin("test3")) {
        if (ImGui::BeginTable("tab", 2, ImGuiTableFlags_Resizable))    {
            ImGui::TableNextRow();
            ImGui::TableNextColumn();
            ImGui::BeginChild("foo");
            ImGui::EndChild();
            ImGui::TableNextColumn();
            ImGui::EndTable();
        }
    }
    ImGui::End();
```

**Comment by ocornut** [comment]
Hello,
Thanks for the report.
I am working on the correct answer for this. The full picture is a little complicated.
In the meanwhile, the temporary workaround would be to reduce child height:

```cpp
ImGui::BeginChild("foo", ImVec2(0.0f, -ImGui::GetStyle().CellPadding.y));
```
(It's only temporary as once fixed you would not need it as it would add unnecessary padding)

**Comment by ocornut** [comment]
I pushed a fix for a tangential issue 2bc5d17 (+ test https://github.com/ocornut/imgui_test_engine/commit/03da9cd5f29d931d3559f8329c7d74a21cb98a6a) I need to fix before yours, but this is not the fix you need yet.

**Comment by ocornut** [comment]
I pushed a fix db66e33. If you cherry-pick both 2bc5d17 and db66e33 it'll merge in docking branch.

Not done with the tests, but for reference here's my test bed
```cpp
if (ImGui::Begin("Test #6619"))
{
    static ImGuiTableFlags table_flags = ImGuiTableFlags_Resizable | ImGuiTableFlags_Borders;
    static ImVec2 table_size = ImVec2(0.0f, 0.0f);
    ImVec2 sz1 = ImGui::GetContentRegionAvail();
    ImVec2 sz2;
    ImGui::ColorButton("##blah1", { 1,1,0,0.5f }, 0, { 50,300 });
    ImGui::SameLine();
    if (ImGui::BeginTable("Table", 2, table_flags, table_size))
    {
        ImGui::TableNextRow();
        ImGui::TableNextColumn();
        sz2 = ImGui::GetContentRegionAvail();
        if (0)
        {
            ImGui::Button("Fill", ImVec2(-FLT_MIN, -FLT_MIN));
        }
        else
        {
            ImGui::PushStyleColor(ImGuiCol_ChildBg, { 0,1,0,0.5f });
            ImGui::BeginChild("foo");// , ImVec2(0.0f, -ImGui::GetStyle().CellPadding.y * 2.0f));
            ImVec2 child_size = ImGui::GetWindowSize();
            ImGui::Text("\n\n\nChild %.2f, %.2f", child_size.x, child_size.y);
            ImGui::EndChild();
            ImGui::PopStyleColor();
        }
        ImGui::TableNextColumn();
        ImGui::ColorButton("##blah1", { 1,0,1,0.5f }, 0, { 50,250 });
        ImGui::EndTable();
    }
    ImGui::Begin("test4");
    ImGui::Text("Avail %f %f", sz1.x, sz1.y);
    ImGui::Text("Avail %f %f", sz2.x, sz2.y);
    ImGui::CheckboxFlags("NoHostExtendY", &table_flags, ImGuiTableFlags_NoHostExtendY);
    ImGui::CheckboxFlags("ScrollY", &table_flags, ImGuiTableFlags_ScrollY);
    ImGui::InputFloat2("TableSize", &table_size.x);
    ImGui::End();
}
ImGui::End();
```

**Comment by ocornut** [comment]
Closing this as solved.

**Comment by nem0** [comment]
Thank you, it does fix my issue.
