### ISSUE TITLE
ImGuiListClipper seeking

### ISSUE THREAD

**Issue by cosmy1** [ocornut/imgui#662]
Hello,

Is possible to seek the position of the vertical scrollbar when using ```ImGuiListClipper```?

I tried to seek to the end of the list by placing this code before creating the clipper.
```ImGui::SetScrollY(ImGui::GetScrollY() + itemHeight * rows.Size());```
But it doesn't work.

What would be the best approach to solve this? (Excluding the looping through all items).

**Comment by ocornut** [comment]
I don't think the question has anything to do with ImGuiListClipper here.
You can use `SetScrollHere()` at the end of your list. Or use `SetScrollFromPosY()` given a cursor position.

If you do `ImGui::SetScrollY(ImGui::GetScrollY() + itemHeight * rows.Size());` you are increasing the scrolling value every frame so it's definitively not correct.

**Comment by cosmy1** [comment]
I modified the code in ```ExampleAppConsole::Draw()``` to use ```ImGuiListClipper```.

```cpp
        ImGui::BeginChild("ScrollingRegion", ImVec2(0,-ImGui::GetItemsLineHeightWithSpacing()), false, ImGuiWindowFlags_HorizontalScrollbar);
        if (ImGui::BeginPopupContextWindow())
        {
            if (ImGui::Selectable("Clear")) ClearLog();
            ImGui::EndPopup();
        }
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(4,1)); // Tighten spacing
        ImGuiListClipper clipper(Items.Size, ImGui::GetTextLineHeightWithSpacing());
        for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; ++i)
        {
            const char* item = Items[i];
            if (!filter.PassFilter(item))
                continue;
            ImVec4 col = ImColor(255,255,255); // A better implementation may store a type per-item. For the sample let's just parse the text.
            if (strstr(item, "[error]")) col = ImColor(255,100,100);
            else if (strncmp(item, "# ", 2) == 0) col = ImColor(255,200,150);
            ImGui::PushStyleColor(ImGuiCol_Text, col);
            ImGui::TextUnformatted(item);
            ImGui::PopStyleColor();
        }
        if (ScrollToBottom)
            ImGui::SetScrollHere();
        ScrollToBottom = false;
        clipper.End();
        ImGui::PopStyleVar();
        ImGui::EndChild();
        ImGui::Separator();
```

It doesn't move the cursor to the end as expected.
![prova2](https://cloud.githubusercontent.com/assets/1329119/15275016/fa6bed16-1ac0-11e6-88e6-e2d509685f4f.gif)

**Comment by ocornut** [comment]
You need to call clipper.End() right at the end of the loop so it position the cursor at the end of the list. Calling `SetScrollHere` before meaning you will jump to the end of the visible portion as calculated by the clipper.

Anyway - you cannot use the clipper like that along with the filter and a `continue` in your branch.
The filter/continue will make items disappear in which case the items count assumption are false.
You would need go through all your items and all least do the filtering before.
`for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; ++i)`
Need to display items from DisplayStart to DisplayEnd, if you are filtering those are indices among the set that passed filtering, not the whole set.
A typical solution would to store a contiguous array of the indices passing the filter, and updating that when the user type in something into the filter, and appending to it when new elements are appended.

It is a little too much code to add to that example which is why I didn't use the clipper here.

Note that I'm just now working on improving the clipper in #661
To allow a) not having to pass height and b) making items_count optional.
The points above are still valid.

**Comment by cosmy1** [comment]
Even if i remove the filter it have the same behaviour. (In the example I didn't use any filter).
And yes I like how you want to improve it :+1:.

**Comment by ocornut** [comment]
This should work.

**Comment by cosmy1** [comment]
![prova3](https://cloud.githubusercontent.com/assets/1329119/15275154/e25331fa-1ac3-11e6-92c9-30c46f17967d.gif)

**Comment by ocornut** [comment]
OK it is a bug. 

SetScrollHere has been changed a few months ago to use the previous line cursor position `window->DC.CursorPosPrevLine.y` along with the line height `window->DC.PrevLineHeight` and the clipper doesn't set those values correctly.

**Comment by cosmy1** [comment]
What is your plan?

**Comment by ocornut** [comment]
Fixing it.

**Comment by ocornut** [comment]
Should provide a fix today along with improved clipper (it's ready but I was testing some edge cases).

**Comment by cosmy1** [comment]
:+1:

**Comment by ocornut** [comment]
Should be done now. Let me know how it works for you.
New clipper more robust, can calculate item height itself, always seek at end.

**Comment by cosmy1** [comment]
Ok, works now. Thank you!

**Comment by cosmy1** [comment]
I found a bug which is not related to the ```ImGuiListClipper``` but the above code is useful to reproduce it. Sorry for writing here but I don't have time to open a new issue.

Horizontal tab is not taken in account and ```ImGui::SetScrollHere();``` doesn't work correctly.


Test code:
```cpp
    ExampleAppConsole()
    {
        ClearLog();
        memset(InputBuf, 0, sizeof(InputBuf));
        HistoryPos = -1;
        Commands.push_back("HELP");
        Commands.push_back("HISTORY");
        Commands.push_back("CLEAR");
        Commands.push_back("CLASSIFY");  // "classify" is here to provide an example of "C"+[tab] completing to "CL" and displaying matches.
        
        for (int i = 0; i < 150; i++)
            AddLog("Welcome to ImGui!Welcome to ImGui!Welcome to ImGui!Welcome to ImGui!Welcome to ImGui!");
    }
```

![htab](https://cloud.githubusercontent.com/assets/1329119/15303572/b8cbf97a-1bb8-11e6-9dc2-bbeec99b840a.png)

When I open the console it show me the second-last line.

**Comment by ocornut** [comment]
Please create a new issue (I don't have much time either and doing you a free service of answering questions and fixing bugs).
Looks like a problem when the scroll is calculated at before scrollbar is activated, it becomes slightly off after scrollbar shows. If you add extra text the seeking work, and adding `|ImGuiWindowFlags_AlwaysHorizontalScrollbar` to the child window also fixes it.

**Comment by cosmy1** [comment]
Excuse me to look like that, its not my intention. I just want to help improving the library and report bugs I find. If you consider it a bug I will open a new issue. Just tell me :smiley:

**Comment by ocornut** [comment]
Its definitely a bug :) just another one!
