### ISSUE TITLE
SetClipboardData heap corruption when Address Sanitizer is enabled and using dx11 backend.

### ISSUE THREAD

**Issue by voidstorm** [ocornut/imgui#6620]
Version/Branch of Dear ImGui:
Branch: master
```
Dear ImGui 1.89.8 WIP (18973)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1936
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00

OS: Windows 11
```

**My Issue/Question:**

I recently turned on Address Sanitizer in MSVC 2022 in one of my projects when I realized copying/pasting anything from ImGui causes the application to crash. Naturally I suspected my own code, but it turns out it is behaving the same way in the ImGui Example project.
Note that this _only_ happens for me when using the DirectX11 backend, it does _not_ seem to happen with any of the other backends.

I'm pretty sure the heap corruption has nothing to do with the clipboard code itself, it just seems to uncover something that happend earlier, presumably linked to the dx11 backend code...
When searching for similar issues, I found this closed issue: Access violation in imgui_impl_dx11.cpp #5898 which was only happening in a custom application as it seems, but maybe these issues are somehow related after all.

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/15369658/d24f1cf7-f3c7-4ee2-8dd8-6e6b1dd8ef68)

![imgui2](https://github.com/ocornut/imgui/assets/15369658/3357715e-12d5-4d1a-b4f7-8e1866316a1c)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

- Open example_win32_directx11
- Set build to Debug
- Enable Address Sanitizer
- Start example
- Do anything that involves copying stuff to the clipboard, e.g select a field and hit Ctrl+C. Opening the About Dialog and hitting Config/build copy to clipboard also does the trick.

**Comment by ocornut** [comment]
I can reproduce this after a few attempts, and see the `SetClipboardData()` call failing.
But I can also repro with GLFW+OpenGL backends and SDL+OpenGL backends just as well, where our function `SetClipboardTextFn_DefaultImpl()` is not used.

I would say this may be an issue with AddressSanitizer not dealing correctly with `GlobalAlloc()`,`GlobalLock` etc.

**Comment by voidstorm** [comment]
Yes, you are right it happens in the other backends as well. I just realized I forgot to turn on the address sanitizer when starting the other backened examples, haha. So yeah, it might just be a problem with the address sanitizer itself.

**Comment by voidstorm** [comment]
You are correct, it is a problem with the adress sanitizer. This small sample also triggers the issue when the sanitizer is enabled.

```c++
#include <Windows.h>
#include <iostream>

int main() {
    // The string to be copied to the clipboard
    const char* strToCopy = "hello world";

    // Step 3: Initialize the Win32 API environment
    if (!OpenClipboard(nullptr)) {
        std::cerr << "Failed to open clipboard." << std::endl;
        return 1;
    }

    // Step 4: Allocate global memory for the string
    HGLOBAL hMem = GlobalAlloc(GMEM_MOVEABLE, strlen(strToCopy) + 1);
    if (!hMem) {
        std::cerr << "Failed to allocate global memory." << std::endl;
        CloseClipboard();
        return 1;
    }

    // Step 5: Copy the string to the global memory
    char* pMem = static_cast<char*>(GlobalLock(hMem));
    if (!pMem) {
        std::cerr << "Failed to lock global memory." << std::endl;
        GlobalFree(hMem);
        CloseClipboard();
        return 1;
    }

    strcpy_s(pMem, strlen(strToCopy) + 1, strToCopy);
    GlobalUnlock(hMem);

    // Empty the clipboard and set the new data
    EmptyClipboard();
    SetClipboardData(CF_TEXT, hMem);

    // Step 6: Close the clipboard
    CloseClipboard();

    std::cout << "String copied to clipboard: " << strToCopy << std::endl;

    return 0;
}

```

**Comment by ocornut** [comment]
I'll close this as not a dear imgui issue. However I guess it needs to be investigated, if you find any clue/update please post them here as it may be useful to other stumbling on similar issue.

**Comment by ReggThims** [comment]
I have recently reported this issue to Microsoft with a trivial example project. The next release of Visual Studio has a 'keep going on ASAN error' option, which at least blunders past the problem.
