### ISSUE TITLE
How to make a global keyboard shortcut on ImGuiKey_Space not trigged by InputText ?

### ISSUE THREAD

**Issue by olivier-gerard** [ocornut/imgui#6621]
_On ImGui v1.89.7 master_

Hi,

I am using the Space key to trigger an action, for it is easily accessible.
I want the shortcut to be active at all time (whatever the active window or widget), but not when the user is using an InputText. It seems logical to disable it as well when keyboard navigation is used, as the space key is already used to activate an item.

The issue is about not trigging the action when the user is inputting a text.

Until now it was ok with `!io.WantCaptureKeyboard && ImGui::IsKeyPressed(ImGuiKey_Space)`, but I just turned on keyboard navigation (which I find very nice!), so the io.WantCaptureKeyboard is always set (even if no widget is selected by the blue rectangle), so it does not work any more.

I tried with a test on `ImGui::Shortcut(ImGuiKey_Space, 0, ImGuiInputFlags_RouteGlobalLow)`, but it get trigged when inputting a text.

Would you please have a hint, or shall I just change of key ?

Regards,
Olivier

**Comment by ocornut** [comment]
`InputText()` doesn't claim many keys as it mostly uses as characters (ImGuiKey_Space, ImGuiKey_C) since it uses the Keys not character.
So similarly `ImGui::IsKeyPressed(ImGuiKey_Space, ImGuiKeyOwner_None)` won't work.

**Comment by ocornut** [comment]
(sorry, mis-sent previous message as I was typing it. Deleted unfinished message and reposting now)

InputText() doesn't claim keys that it uses as characters (so it doesn't claim ImGuiKey_Space, ImGuiKey_A, etc), which itself is an interesting topic I hadn't thought about in term of routing, thought usually one would filter with a `g.ActiveId == 0` check in the first place. So similarly as your `Shortcut()` attempt, `ImGui::IsKeyPressed(ImGuiKey_Space, ImGuiKeyOwner_None)` won't work.

> Until now it was ok with !io.WantCaptureKeyboard && ImGui::IsKeyPressed(ImGuiKey_Space), but I just turned on keyboard navigation (which I find very nice!), so the io.WantCaptureKeyboard is always set (even if no widget is selected by the blue rectangle), so it does not work any more.

Even when the blue rectangle isn't active, stuff like arrow keys, page up page down are meant to work.

Why not using `ImGui::IsAnyItemActive() == false && ImGui::IsAnyItemFocused()` as a primary filter? 

You said "I want the shortcut to be active at all time (whatever the active window or widget)" but I'm not sure you used "active window or widget" in the same sense as imgui terminology.

**Comment by olivier-gerard** [comment]
Thanks for the hint ! 
I'm always a bit confused with active widgets, but your suggestion works fine ! (just changed it `ImGui::IsAnyItemActive() == false && ImGui::IsAnyItemFocused() == false` which seemed more logical).
