### ISSUE TITLE
Happy Cake Day 🎉

### ISSUE THREAD

**Issue by excellentcucumber** [ocornut/imgui#6625]
Nine years ago, on this day, @ocornut pushed the initial commit fa1e09ec80a8189084b6c4929952b14f7d430d36 that would go on to have a significant impact on the world.

On this special day, let us celebrate the impact that Dear ImGui has had on the gaming industry and the countless hours of work it has saved developers worldwide. Thank you, ocornut, for your invaluable contribution! 🎉

**Comment by misuke0** [comment]
For me personally, imgui has taught me c++, I was stuck in tutorial hell without actually coding anything useful, one reason is that i don't like making console application, until I learn about imgui and it helped me write gui application which massively boost my interests in learning c++.

Thank you @ocornut, you are amazing, we don't appreciate your work enough!

**Comment by ocornut** [comment]
Thank you for the kind words.
I’ve had this date in mind and I hope by next year we can hop into bigger changes :)

I recall prototyping this near Christmas 2012 while working on Tearaway for Vita, we suddenly were able to built a bunch of runtime debug tools which helped toward shipping. Had no idea I would still be involved with this so long later! Likewise when I dropped it on github.
