### ISSUE TITLE
How to Round Imgui::Checkbox?

### ISSUE THREAD

**Issue by LowModDev** [ocornut/imgui#6628]
How to Round Imgui::Checkbox? Please Help Me

**Comment by sakiodre** [comment]
Use `ImGuiStyleVar_FrameRounding`:
```cpp
ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 5.f);
ImGui::Checkbox(...);
ImGui::PopStyleVar();
```

**Comment by ocornut** [comment]
You can only increase FrameRounding but not make them entirely circular, otherwise they would visually conflict with RadioButton() logic.

**Comment by LowModDev** [comment]
rg

> You can only increase FrameRounding but not make them entirely circular, otherwise they would visually conflict with RadioButton() logic.

thank good night or good day
