### ISSUE TITLE
InputFloat clipping/rounding large values

### ISSUE THREAD

**Issue by mattcops** [ocornut/imgui#6630]
Version: v1.89.7 (tag)

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Operating System: Win 11

When using InputFloat and InputFloat3, I noticed that it clips/rounds off large numbers. For example, if I input "100000.005" it becomes "100000.008". If I input "100000.090" it becomes "100000.094".  "3154145.700" becomes "3154145.750". 

As I understand, a float can have a maximum value of around 3.4 E+38, which I am obviously far off, so I am confused as to why this is an issue.

I have tried using "InputDouble" and that doesn't appear to have the same issue. However, there is no "InputDouble3". I'm currently using 2 InputFloat3's, and they look a lot nicer than if I were to split it into 6 InputDouble's.  I had a look at InputFloat3 to see if I could implement it for myself using doubles, but it seems like it wouldn't be trivial, but please correct me if I am wrong.

Video:
https://github.com/ocornut/imgui/assets/41787498/ae1a0cf1-b066-4979-b38b-840c5d1fe676

Reproduction:

{
    static float test = 0.0;
    ImGui::Begin("Test Float Input");
    ImGui::InputFloat("Test Float", &test);
    ImGui::End();
}

**Comment by zao** [comment]
Making a small visit to Octave land to ask for the distance between adjacent floating point numbers:
```octave
>> arr = [100000.005, 100000.090, 3154145.700]
arr =
   1.000000050000000e+05   1.000000900000000e+05   3.154145700000000e+06

>> eps(arr)
ans =
   1.455191522836685e-11   1.455191522836685e-11   4.656612873077393e-10

>> eps(single(arr))
ans =
   7.8125000e-03   7.8125000e-03   2.5000000e-01
```

Key to reasoning around floating point numbers is that their precision varies across their range. There's way more numbers closer to zero than in the higher end of the range, the higher you go the further spaced apart adjacent numbers.

As shown in the output near 3154145 in single-precision the numbers are 0.25 apart, the closest number to 3154145.7 is 3154145.75 so that's what the parse function returns.
Similarly down by 100000 the granularity is 0.078125 and the values are rounded accordingly.

Hand-waving a bit, this is due to how floating point numbers separately represents the mantissa (and the exponent) in a fixed number of bits, so for each step in the exponent, there's roughly as many numbers to spread out evenly across each ever-larger band of values.

**Comment by ocornut** [comment]
What @zao said, this is a property of float types.

You can use InputScalarN variant to reimplement InputDouble2/3 in one or two lines of code.

**Comment by mattcops** [comment]
> Making a small visit to Octave land to ask for the distance between adjacent floating point numbers:
> 
> ```matlab
> >> arr = [100000.005, 100000.090, 3154145.700]
> arr =
>    1.000000050000000e+05   1.000000900000000e+05   3.154145700000000e+06
> 
> >> eps(arr)
> ans =
>    1.455191522836685e-11   1.455191522836685e-11   4.656612873077393e-10
> 
> >> eps(single(arr))
> ans =
>    7.8125000e-03   7.8125000e-03   2.5000000e-01
> ```
> 
> Key to reasoning around floating point numbers is that their precision varies across their range. There's way more numbers closer to zero than in the higher end of the range, the higher you go the larger the spacing is between adjacent numbers.
> 
> Hand-waving a bit, this is due to how floating point numbers separately represents the mantissa in a fixed number of bits, so for each step in the exponent, the same count of numbers has to be spread out evenly across each ever-larger band.
> 
> As shown in the output near 3154145 in single-precision the numbers are 0.25 apart, the closest number to 3154145.7 is 3154145.75 so that's what the parse function returns. Similarly down by 100000 the granularity is 0.0078125 and the values are rounded accordingly.
> 
> In short, the widget stores the closest representable value in the variable, much like how `scanf`, `std::cin` or `strtof` would.

Thanks very much for the explanation, I didn't know  it worked that way.

**Comment by mattcops** [comment]
> What @zao said, this is a property of float types.
> 
> You can use InputScalarN variant to reimplement InputDouble2/3 in one or two lines of code.

OK, thanks. I'll have a look  at doing that.

**Comment by ocornut** [comment]
See `Demo->Data Types` and `Demo->Multi Components Widgets` for example of doing that.
