### ISSUE TITLE
"Assertion failed: window->IDStack.Size > 1" Error

### ISSUE THREAD

**Issue by LightShade12** [ocornut/imgui#6634]
Version/Branch of Dear ImGui:
Version: 1.89.7 WIP (18967)
Branch: docking

Back-end/Renderer/Compiler/OS:
Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: Windows 10

My Issue/Question:
I'm trying to run ImGui in debug mode and I get the error:
```
Assertion failed: window->IDStack.Size > 1, file D:\dev0\projects\MiniRay\MiniRay\extern\imgui\imgui_widgets.cpp, line 6337
```
I previously got the "cannot have empty id at root of window" error so i checked and replaced all "" labels to "###" style labels (they were only in the inputTextwithHint widgets). Now I get this error. 

What does this error mean? How can I fix?

Thank you.

**Comment by ocornut** [comment]
Please read guidelines and try to isolate/provide repro code. We cannot magically guess what your code is doing.

**Comment by ocornut** [comment]
You are probably calling `TreePop()` too many times. Causing for lack of details/repro.
