### ISSUE TITLE
OpenGL3 example altering GL state? (How to draw behind imgui windows?)

### ISSUE THREAD

**Issue by Blaxxun75** [ocornut/imgui#664]
Hello,
since iam completly new to C++ and imgui my questions may sound a bit weird.
I started with the opengl3 demo and i was able to make it use GLEW instead of gl3w, since the tuts iam following are using GLEW.

However, i try to draw a simple line in the background with standard Opengl commands which works in a minimalistic opengl window.
Now when i pack this code into a function and try to call it from the imgui project i cant see anything.

Iam calling my function directly before the imgui rendering part  //Rendering.

```
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

void Chart(GLFWwindow *window)
{
	glViewport(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT); // specifies the part of the window to which OpenGL will draw (in pixels), convert from normalised to pixels
	glMatrixMode(GL_PROJECTION); // projection matrix defines the properties of the camera that views the objects in the world coordinate frame. Here you typically set the zoom factor, aspect ratio and the near and far clipping planes
	glLoadIdentity(); // replace the current matrix with the identity matrix and starts us a fresh because matrix transforms such as glOrpho and glRotate cumulate, basically puts us at (0, 0, 0)
	glOrtho(0, SCREEN_WIDTH, 0, SCREEN_HEIGHT, 0, 1); // essentially set coordinate system
	glMatrixMode(GL_MODELVIEW); // (default matrix mode) modelview matrix defines how your objects are transformed (meaning translation, rotation and scaling) in your world
	glLoadIdentity(); // same as above comment

	GLfloat lineVertices[] =
	{
		0.0f, 0.0f, 0.0f,
		100.0f, 100.0f, 0.0f
	};
		glClear(GL_COLOR_BUFFER_BIT);
		glLineWidth(10);
		glEnableClientState(GL_VERTEX_ARRAY);
		glVertexPointer(3, GL_FLOAT, 0, lineVertices);
		glDrawArrays(GL_LINES, 0, 2);
		glDisableClientState(GL_VERTEX_ARRAY);
}
```

My goal is to read from a csv file and plot the values in a chart.
Maybe someone could give me a hint how to draw in the background.

I really like imgui because its leightweight. Unfortunatly i couldnt find a lot in the internet or forums to ask there, so i have to ask here.

Thanks for this great library,
ChriS

**Comment by ocornut** [comment]
That question doesn't have much to do with imgui apart from the fact that perhaps the example OpenGL3 may alter render-state in an undesirable manner.

Try commenting out code from the render function in the `imgui_impl_glfw_gl3.cpp` file until your own code works. There we can find out which call of the render function is altering a GL render state. You can start by commenting our the render loop in the middle, then try commenting the code setting the render state above the render loop. Then try commenting the code restoring all the state at the bottom. Then last restore commenting the code that saves all the state at the top.

**Comment by Blaxxun75** [comment]
Hello Omar, thanks for the swift reply. I will follow your recommendation.
Thanks for the hints.
Greets from Austria,
ChriS

**Comment by Blaxxun75** [comment]
Okay, i ended up to comment out the whole "ImGui_ImplGlfwGL3_RenderDrawLists(ImDrawData* draw_data)" function without seeing anything.

To make it short. 
I really wanna use imgui and i really need this to work. So i need a starting point.
Since i dont have the knowledge i can only offer money.
How much would it cost to provide a working minimalistic Opengl3+ starting project ?

Thanks,
ChriS

PS: I had to edit my header since "GL state is absoltly meaningless to noobs like me"

**Comment by ocornut** [comment]
Chris,

> Okay, i ended up to comment out the whole "ImGui_ImplGlfwGL3_RenderDrawLists(ImDrawData* draw_data)" function without seeing anything.

Then it means that your standalone code isn't functional?

Or there might be another minor state change done in ImGui_ImplGlfwGL3_CreateDeviceObjects() so you may try to comment chunks of that as well.

This IS a minimalistic OpenGL3 starting project. Money can't fix the fact that getting started with OpenGL can be tedious and tackling those issues can be tedious when starting a small project from scratch and learning OpenGL. Literally every programmer have starred for hours at a black screen trying to figure out with their lines/cube/texture won't display. It is very common in particular when writing simple code.

The state of OpenGL is defined by the sum of all its states/parameters which are manipulated by OpenGL functions, e.g. glEnable(GL_BLEND) is altering a boolean somewhere (to simplify thing). Unfortunately they are so many of them and they are confusingly labelled or not always easy to understand. It's not always trivial to tell which function is modifying what. The ImGui OpenGL examples are trying to backup and restore any state they modify but it is possible that something isn't backuped/restored and that your program is implicitly relying into it. If you were explicitly relying on something you would have written the code to set the state and wouldn't have the problem.

For example your code is implicitly relying on NO shader being used, rather than explicitly. You could call `glUseProgram(0);` to make that explicit. So if my code was setting up a shader and not disabling it at the end it would break your code. Most codebase as they grow tend to be explicit about what they need.

Try selectively commenting out everything from `ImGui_ImplGlfwGL3_CreateDeviceObjects` see if your display works again first.
Note that this place isn't a place for learning and teaching OpenGL. So a lot a of this is very off-topic. The reason I'm keeping this up is that I'm eager to remove any unintentional state changes in the OpenGL examples, if any is left, for the purpose of making usage by beginners easier. (As mentioned above because of this implicit/explicit thing, when you have very little code you are more likely to run into an implicit state requirement than if you had lots of code).

**Comment by Blaxxun75** [comment]
Hello Omar, thanks for taking your time to describe me whats probably wrong. I really appretiate it.
I know that OpenGL is a kind of a state machine. 
I need to dig deeper and get a better understanding before i can successfully use imgui.

I will try to find whats wrong since you gave me plenty of hints. 
Thanks for that.

If i found what the problem was i will report it here.

Greets,
ChriS

**Comment by Blaxxun75** [comment]
Hi Omar,

I finally found out what the showstopper was.
I dont really understand it, but now i can draw a line in the background.
It was basically this 2 lines of code:
`glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3); //Line not visible anymore`
`glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);// Crash`

I guess one can specify the version of OpenGL to be used or so.
I guess further that i dont use the proper version commands to draw my line.
What GLFW_OPENGL_PROFILE does is not clear to me yet.

I know i wont get direct help here and i also know that this is not the right place here, but however,
here is my main.cpp code so far. Maybe it helps someone sometime:

```
#include <imgui.h>
#include <imgui_impl_glfw_glew.h>
#include <stdio.h>
#include <GL/glew.h>
#include <GL/glfw3.h>
#include <iostream>

#define IM_ARRAYGroesse(_ARR)  ((int)(sizeof(_ARR)/sizeof(*_ARR)))
#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

static void error_callback(int error, const char* description)
{
	fprintf(stderr, "Error %d: %s\n", error, description);
}


void Chart(GLFWwindow *window)
{
	GLfloat lineVertices[] =
	{
		100, 300, 0,
		800, 500, 0
	};

	GLfloat colour[] =
	{
		255,0,0,
		0,255,0
	};

	// Render OpenGL here
	glEnable(GL_LINE_SMOOTH);
	glEnable(GL_LINE_STIPPLE);
	glPushAttrib(GL_LINE_BIT);
	glLineWidth(10);
	glLineStipple(1, 0x00FF);
	glEnableClientState(GL_VERTEX_ARRAY);
	glEnableClientState(GL_COLOR_ARRAY);
	glVertexPointer(3, GL_FLOAT, 0, lineVertices);
	glColorPointer(3, GL_FLOAT, 0, colour);
	glDrawArrays(GL_LINES, 0, 2);
	glDisableClientState(GL_VERTEX_ARRAY);
	glDisableClientState(GL_COLOR_ARRAY);
	glPopAttrib();
	glDisable(GL_LINE_STIPPLE);
	glDisable(GL_LINE_SMOOTH);
}


int main(int, char**)
{
	// Setup window
	glfwSetErrorCallback(error_callback);

	if (!glfwInit())
	return 1;

	glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
	//glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3); //Nicht mehr sichtbar
	//glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);// Crash
	GLFWwindow *window = glfwCreateWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "Hello World", NULL, NULL);

	glfwMakeContextCurrent(window);
	glewExperimental = GL_TRUE;
	glewInit();

	// Setup ImGui binding
	ImGui_ImplGlfwGL3_Init(window, true);
	ImVec4 clear_color = ImColor(24, 24, 24);
	
	//glViewport(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT); // specifies the part of the window to which OpenGL will draw (in pixels), convert from normalised to pixels
	glMatrixMode(GL_PROJECTION); // projection matrix defines the properties of the camera that views the objects in the world coordinate frame. Here you typically set the zoom factor, aspect ratio and the near and far clipping planes
	glLoadIdentity(); // replace the current matrix with the identity matrix and starts us a fresh because matrix transforms such as glOrpho and glRotate cumulate, basically puts us at (0, 0, 0)
	glOrtho(0, SCREEN_WIDTH, 0, SCREEN_HEIGHT, 0, 1); // essentially set coordinate system
	glMatrixMode(GL_MODELVIEW); // (default matrix mode) modelview matrix defines how your objects are transformed (meaning translation, rotation and scaling) in your world
	glLoadIdentity(); // same as above comment

	// Main loop --------------------------------------------------------------------------------------------------------------------------
	while (!glfwWindowShouldClose(window))
	{
		glfwPollEvents();
		ImGui_ImplGlfwGL3_NewFrame();

		//Fenster --------------------------------------

		ImGuiWindowFlags Fenster_flags = 0;
		Fenster_flags |= ImGuiWindowFlags_NoTitleBar;
		Fenster_flags |= ImGuiWindowFlags_NoResize;;
		Fenster_flags |= ImGuiWindowFlags_NoMove;
		Fenster_flags |= ImGuiWindowFlags_NoCollapse;

		int w, h;
		glfwGetWindowSize(window, &w, &h);
		
		ImGui::Begin("Window", 0, Fenster_flags);
		ImGui::SetWindowPos(ImVec2(0, 0));
		ImGui::SetWindowSize(ImVec2(250, h), 0);
		//ImGui::Text("Guten Tag!");
		if (ImGui::CollapsingHeader("Header"))
		{
			static bool test1 = true;
			ImGui::Checkbox("Test", &test1);
			static bool test2 = true;
			ImGui::Checkbox("Test2", &test2);
			static float arr[] = { 0.6f, 0.1f, 1.0f, 0.5f, 0.92f, 0.1f, 0.2f };
			ImGui::PlotLines("Plot", arr, IM_ARRAYGroesse(arr),0,"Test");
		}
		ImGui::End();

		// Rendering
		int display_w, display_h;
		glfwGetFramebufferSize(window, &display_w, &display_h);
		glViewport(0, 0, display_w, display_h);
		glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
		glClear(GL_COLOR_BUFFER_BIT);

		Chart(window);
		ImGui::Render();
		glfwSwapBuffers(window);
	}

	// Cleanup
	ImGui_ImplGlfwGL3_Shutdown();
	glfwTerminate();
	return 0;
}
```

Greets,
ChriS

**Comment by ocornut** [comment]
Those functions select the OpenGL version and afaik disable forward compatibility (which is a requirement on recent OSX I think). So I suppose some of imagine OpenGL code isn't compatible with OpenGL 3.3 but compatible with 3.0.?
