### ISSUE TITLE
Dx9 CreateVertexBuffer usage

### ISSUE THREAD

**Issue by RobinWilhelm** [ocornut/imgui#6643]
In the Dx9 render implementation, the vertexbuffers are created with D3DUSAGE_DYNAMIC | D3DUSAGE_WRITEONLY.
According to the microsoft documentation the usage MUST be 0, if the device is created with D3DCREATE_HARDWARE_VERTEXPROCESSING. (https://learn.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3ddevice9-createvertexbuffer).

Even the dx9 example is created with hardware vertex processing, so might this be an issue?

I just stumbled upon this while investigating directx related crashes to my application. They are *most likely* not related to this but i got a little bit paranoid fixing dx9 crashes :)

**Comment by GamingMinds-DanielC** [comment]
Dynamic and writeonly vertex buffers are not in conflict with hardware vertex processing, no issue there.

This restriction applies only to usage flags related to where vertex processing takes place, basically just `D3DUSAGE_SOFTWAREPROCESSING` and nothing else. The wording in the documentation is misleading when you look at hardware vertex processing in isolation, but when you take the descriptions for software and mixed vertex processing into account, it should become clear that they mean only this single flag.

**Comment by RobinWilhelm** [comment]
I see it now, thanks for the clarification.
