### ISSUE TITLE
Dual list box 

### ISSUE THREAD

**Issue by darkvad1010** [ocornut/imgui#6648]
How could one achieve this type of dual list box widget, using imgui listboxes and buttons? With this component, you can add or remove a selected item from one list to another. You can also add or remove all items in one list to the other.

![vue-listbox-multiselect~2](https://github.com/ocornut/imgui/assets/58582403/629f174f-56c7-45ac-a52d-352137dcaadc)

**Comment by GamingMinds-DanielC** [comment]
Take a look a tables in the demo sources. If you rather want to define your layout manually, you can use `GetContentRegionAvail()` to get the available size, `SetCursorPos()` to place your items and give an explicit size when committing your items.

**Comment by ocornut** [comment]
You can achieve this with two child window or listbox, submitting items in either of them depending on their inclusion in the set, with stored selection on both sides and buttons to move from one to the other.

I think it would be a worthy demo to add, in particular with the addition of the range-select branch. I’ll try to work on one next month.

**Comment by darkvad1010** [comment]
> You can achieve this with two child window or listbox, submitting items in either of them depending on their inclusion in the set, with stored selection on both sides and buttons to move from one to the other.
> 
> I think it would be a worthy demo to add, in particular with the addition of the range-select branch. I’ll try to work on one next month.

Do you mind sharing some pseudo-code?

**Comment by ocornut** [comment]
FYI I've been doing some research on this as part of the multi-select features and being an expected demo.
Turns out it hasn't been simple to design and formalize the right demo for this this and other multi-select features, one problem being that multi-select generally requires quite some involvement from user code. 

![image](https://github.com/ocornut/imgui/assets/8225057/b42d18bb-b3b1-452f-ab88-9b12a238766b)

No ETA.

**Comment by ocornut** [comment]
A dual list box demo has now been merged as part of the multi-select integration into master.

You can find it in **Demo->Widgets->Selection State&Multi-Select->Dual List Box**

![image](https://github.com/user-attachments/assets/834e091e-8574-4f76-86db-c78694fcd6af)
