### ISSUE TITLE
Horizontal scrollbar issue

### ISSUE THREAD

**Issue by cosmy1** [ocornut/imgui#665]
Hello,

This is a summary of #662 last replies.
I will describe the issue with an example code and a visual rappresentation of the bug.

I will use `ExampleAppConsole` struct to describe it

``` c++
// I modified the constructor by adding some initial dummy text
ExampleAppConsole()
{
    ClearLog();
    memset(InputBuf, 0, sizeof(InputBuf));
    HistoryPos = -1;
    Commands.push_back("HELP");
    Commands.push_back("HISTORY");
    Commands.push_back("CLEAR");
    Commands.push_back("CLASSIFY");  // "classify" is here to provide an example of "C"+[tab] completing to "CL" and displaying matches.

    // Add a bunch of long texts to make the scrollbar visible
    for (int i = 0; i < 150; i++)
        AddLog("Welcome to ImGui!Welcome to ImGui!Welcome to ImGui!Welcome to ImGui!Welcome to ImGui!");
}
```

What I expect to see is the last line but instead i see the scrollbar at a wrong offset:
![htab](https://cloud.githubusercontent.com/assets/1329119/15303572/b8cbf97a-1bb8-11e6-9dc2-bbeec99b840a.png)

**Comment by ocornut** [comment]
Thanks! So as stated in #662 the horizontal scrollbar is already taken into account. But in this situation. the scrolling request happens on the same frame as the one where we first decide that a scrollbar must appears, and it affects the scrolling offset. So it's probably a subtle lag/offset in one of the involved calculations.

Adding the `ImGuiWindowFlags_AlwaysHorizontalScrollbar` flag to the child window fixes it (at the cost of always showing a scrollbar even when it isn't needed).

**Comment by cosmy1** [comment]
Ops removed the mistakenly left line.

**Comment by ocornut** [comment]
Better late than never, this bug is now fixed. cc: @cosmy1
