### ISSUE TITLE
In Windows, calling 'SaveIniSettingsToDisk' causes' GetLastError 'to be set

### ISSUE THREAD

**Issue by lance5** [ocornut/imgui#6650]
**Version/Branch of Dear ImGui:**

Version: 
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: All
Compiler: Visual Studio Community 2019 Release - arm64
Operating System: Windows 10

**My Issue/Question:**

If SaveIniSettingsToDisk is frequently called, '_wfopen 'always sets' GetLastError' to 'ERROR'_ ALREADY_ EXISTS (183) ', do you want to remove this error to prevent it from being caught by others.

[Related discussions](https://www.gamedev.net/forums/topic/601159-c-fstremopen-causes-error-already-exists/)

**Screenshots/Video**

![企业微信截图_acaa34b7-8fd4-4e20-876c-272b08505b77](https://github.com/ocornut/imgui/assets/19624447/82fed32e-1ccd-4033-a3e1-56e0ce9fc0d9)

You might consider a work around such as `calling GetLastError() before opening the file and SetLastError() afterwards`, preserving the applications error status.

**Comment by lance5** [comment]
Please replace RestoreLastError with SetLastError. Think you.

**Comment by lance5** [comment]
@PathogenDavid Thank you for your reply. And I agree with your point of view that the consequences of calling a function should be borne by myself. However, I did not have the opportunity to perceive the errors that would occur in those functions in ImGui until they were caught and crashed by another closed source software, and I knew nothing about them. I wasted 4 hours on tracking and debugging.
I did not directly call SaveIniSettingsToDisk, but was indirectly called by NewFrame, and I cannot read all the implementations of this function in a short period of time.
ERROR_ ALREADY_ EXISTS is not a mandatory error, but rather an expected warning. Should we directly use CreateFileW and proactively eliminate this warning? If you lack the time to make changes, I can fix this issue, but I'm not sure if I want to do it.
Thank you very much again for taking the time to reply.

**Comment by PathogenDavid** [comment]
I definitely sympathize with going through a long and arduous debugging process over this, but I think you're looking at this the wrong way.

> I cannot read all the implementations of this function in a short period of time.

This is exactly my point. You can't, and you shouldn't try to do this. If it wasn't `SaveIniSettingsToDisk` it would've been something else. (Including things which aren't Dear ImGui.)

This is a bug in the closed source software and should be reported to its vendor. It is *not* a bug in Dear ImGui. (Chances are they're incorrectly handling one of the Win32 functions with ambiguous error semantics like [`SetWindowLongPtrW`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptrw#return-value).)

If the vendor is slow or stubborn, you should workaround the issue by calling `SetLastError(ERROR_SUCCESS);` before calling into their functions.

**Comment by lance5** [comment]
@PathogenDavid You have made the right change in my view on error markers, and your handling of errors is correct. I agree with your point of view. Thank you very much for taking the time to answer my confusion. Sincerely wish you a wonderful day. I will close this question.

**Comment by PathogenDavid** [comment]
No problem, I hope you have a great day as well!
