### ISSUE TITLE
Trouble sorting table

### ISSUE THREAD

**Issue by sodamouse** [ocornut/imgui#6654]
**Version/Branch of Dear ImGui:**

Version: 1.89.7
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl.opengl3.cpp
Compiler: clang++
Operating System: Archlinux

**My Issue/Question:**

I am trying to sort a table using the snippet of code provided below. This works, in the sense that on starting my application, the entries are sorted alphabetically based on the first column. However I am not able to resort the same column based on ascending/descending, or use any other column headers as sort basis at all.

**Screenshots/Video**

N/A

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
        if (auto* sortSpecs = ImGui::TableGetSortSpecs())
        {
            if (sortSpecs->SpecsDirty)
            {
                std::sort(
                &ENTRIES[0], &ENTRIES[entryIdx],
                [&sortSpecs](const Entry& lhs, const Entry& rhs) -> bool {
                    for (size_t i = 0; i < sortSpecs->SpecsCount; ++i)
                    {
                        // clang-format off
                        const ImGuiTableColumnSortSpecs* currentSpecs = &sortSpecs->Specs[i];
                        switch (currentSpecs->ColumnUserID)
                        {
                            case 0: {
                                auto numeric = lhs.title.compare(rhs.title);
                                bool sort = numeric <= 0 ? true : false;
                                return ImGuiSortDirection_Ascending ? sort : !sort;

                            }; break;

                            .
                            .
                            .

                            default: {
                            // same as case 0
                            }; break;
                        }
                        // clang-format on
                    }
                });
            }

            sortSpecs->SpecsDirty = false;
        }
```

**Comment by ocornut** [comment]
Please provide more details, eg confirming the state and contents of our sort specs by printing it out, or to provide a repro provide that it is a dear imgui issues.

**Comment by sodamouse** [comment]
It's a little unclear to me how to provide useful printouts, but a basic investigation shows me that currentSpecs->ColumnUserID is always 0 no matter what header I click on.

**Comment by ocornut** [comment]
`ColumnUserID` correspond to the optional 3rd parameter passed to `TableSetupColumn()`, you didn't include those calls in your repro, but most likely you are using the wrong field and want to use `ColumnIndex`.

**Comment by sodamouse** [comment]
Thanks, that was it. This takes care of being able to sort by any column, but I still can't reverse the sorting order. Perhaps i'm doing something wrong here?
```
auto numeric = lhs.title.compare(rhs.title);
bool sort = numeric <= 0 ? true : false;
return ImGuiSortDirection_Ascending ? sort : !sort;
```

**Comment by sodamouse** [comment]
This actually cases the application to crash. I can sort by the columns in one direction, but trying to reverse it is ctd.

**Comment by ocornut** [comment]
(1) Is the value in `SortDirection` correct or not? If it is correct it is a problem of yours (Most likely you are making a mistake using std::sort). If it is incorrect it is problem of dear imgui. But right now you are being ambiguous not specifying this.

(2) Please never state that there is a crash without providing details e.g. in the form of a callstack.

> It's a little unclear to me how to provide useful printouts

Print all the ImGuiTableColumnSortSpecs content or use a debugger to confirm if there are correct or not.

**Comment by sodamouse** [comment]
@ocornut Thanks I realized that there was a logical error in how I was using currenSpecs->SortDirection. This issue can be marked as resolved.

**Comment by GamingMinds-DanielC** [comment]
Your problem was that you just flipped the comparison result, not the comparison.
Ascending: `a < b`
Descending: `a > b` or `b < a`
Your version: `!(a < b)` or `a >= b` or `b <= a`

That difference is quite fatal to algorithm that expect strict weak ordering and are thrown of in case of equality, since both operands compare to "less than" the other at the same time, a logical impossibility.

Since you already know this, this info is for other people that stumble upon this issue. You probably know how it is when you have a problem, do some research, find threads of people with the same problem, just for them to end it by saying "I solved it" without any details. Please always state what the actual solution was, that helps more people in the long run.
