### ISSUE TITLE
Addrect does not draw on the title bar Window.

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#6660]
Sorry - this is not a bug report, I just wanted to ask if it's possible to draw on the window's titlebar with the standard Imgui methods - such as Addrect, AddLine and the like?

**Comment by ocornut** [comment]
You’ll need to use PushClipRect() to push a clipping rectangle larger than the one the window initially uses.

**Comment by ElectroidDes** [comment]
Very Big Thanks! It works.

**Comment by ocornut** [comment]
Good to hear. Closing.
Linking to similar issues #6002 #5115 #4636 #3882

**Comment by pudding186** [comment]
why only use PushClipRect() can draw on titlebar
