### ISSUE TITLE
Window resize issue

### ISSUE THREAD

**Issue by raselmandol** [ocornut/imgui#6663]
**Version/Branch of Dear ImGui:**

Version: v1.89.8 WIP
Branch: docking/examples/example_glfw_vulkan

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp
Compiler: Using Visual Studio (Installed GCC latest version), Vulkan SDK
Operating System: Windows 11

**My Issue/Question:**

In example_glfw_vulkan, I am adding a new test window in the same way of "another window" -checkbox method by adding the following code:

    bool show_rasel_window = false;
    ImGui::Checkbox("Test Window", &show_rasel_window);
        if (show_rasel_window)
        {
            ImGui::Begin("Testing Window", &show_rasel_window);   // Pass a pointer to our bool variable (the window will have a closing button that will clear the bool when clicked)
            ImGui::Text("Hello from test window!");
            if (ImGui::Button("Close Me"))
                show_rasel_window = false;
            ImGui::End();
        }

now this window is opening beside the test window checkbox with a small size. So I have tried to change the size of the window in this way by adding these lines

    ImGui::SetNextWindowSize(ImVec2(800, 600));
    ImGui::Begin("Testing Window", &show_rasel_window, ImGuiWindowFlags_AlwaysAutoResize);
   
    but the resizing option is not working. I can't totally resize the window, it's fixed. Then I have tried this 
    
    ImGui::Begin("Testing Window", &show_rasel_window, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoSavedSettings);
    
    still not working, then tried this:
    
    
 bool show_rasel_window = false;
ImGui::Checkbox("Test Window", &show_rasel_window);
if (show_rasel_window)
{
    ImVec2 windowSize(800, 600);
    ImGui::Begin("Testing Window", &show_rasel_window, ImGuiWindowFlags_AlwaysAutoResize);
    if (ImGui::GetWindowSize().x != windowSize.x || ImGui::GetWindowSize().y != windowSize.y)
        windowSize = ImGui::GetWindowSize();
    ImGui::Text("Hello from the test window!");
    if (ImGui::Button("Close Me"))
        show_rasel_window = false;
    ImGui::End();
    ImGui::SetNextWindowSize(windowSize, ImGuiCond_Always);
}

still not working. I can't resize or move the window. Then tried this

if (show_rasel_window)
{
    ImVec2 windowSize(800, 600);
    ImVec2 windowPos(100, 100);

    ImGui::SetNextWindowPos(windowPos);

    ImGui::Begin("Testing Window", &show_rasel_window, ImGuiWindowFlags_NoSavedSettings);
    ImGui::SetWindowSize(windowSize);

    windowSize = ImGui::GetWindowSize();
    windowPos = ImGui::GetWindowPos();

    ImGui::Text("Hello from the test window!");
    if (ImGui::Button("Close Me"))
        show_rasel_window = false;
    ImGui::End();

    ImGui::SetNextWindowSize(windowSize);
    ImGui::SetNextWindowPos(windowPos);
}
commented this line (glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);) , still not working. 
I have tried all possible solutions but couldn't fix this.
    
**Screenshots/Video**

![Screenshot (4)](https://github.com/ocornut/imgui/assets/130071257/17066f77-446f-4a4c-a9f8-8f0a68ded0a6)

// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
> I have tried all possible solutions but couldn't fix this.

You have not tried the simplest one which is to use SetNextWindowSize().

If you also set ImGuiWindowFlags_AlwaysAutoResize you are requesting two opposite things.

> I can't totally resize the window, it's fixed

Use an ImGuiCond parameter to SetNextWindowSize() which is not ImGuiCond_Always to only set a size the first time.

**Comment by raselmandol** [comment]
thanks a lot @ocornut , the solution worked, I was trying other methods except the easiest one ::>
