### ISSUE TITLE
Lots of fonts and black text screen

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#6664]
Imgui Version: 1.89.6

I noticed this strange thing:

I load hieroglyphs from an external TTF file and just create one very ordinary Imgui window with the name of the title.
Everything is fine here:

![Imgui_OK_wnd_1](https://github.com/ocornut/imgui/assets/140515246/2af3f04b-fb2b-433d-8251-dc1065340e2e)

But I noticed when I start loading a "large" number of characters, for example 8 thousand characters from a TTF file of size 25 OR a smaller number of characters, but in a larger font, for example 2 thousand characters of size 100, then for the place of the window title - a black bar is simply drawn and nothing else:

![Imgui_black_wnd_1](https://github.com/ocornut/imgui/assets/140515246/7b64da57-3adc-45c2-a391-ff4b68c48d40)

It even somehow affects the Imgui demo window:

![Imgui_black_wnd_2](https://github.com/ocornut/imgui/assets/140515246/a5a0e711-1d5c-484d-94d8-e035f1e7654f)

Why might this be?

**Comment by ocornut** [comment]
Your font texture is too big and fails to upload,
see "Font Atlas too large?" in https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#fonts-loading-instructions
Most likely you can reduce OversampleH to reduce size.

I will update FAQ and docs soon.

**Comment by ocornut** [comment]
I created a better Troubleshooting section now:
https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#troubleshooting

**Comment by ocornut** [comment]
FYI, the ongoing work on `dynamic_fonts` branch toward 1.92 which should make this a non-issue, as glyphs are rendered on demand. Therefore languages like Chinese shouldn't have issues anymore. See https://github.com/ocornut/imgui/issues/8465.
