### ISSUE TITLE
create new window

### ISSUE THREAD

**Issue by Kasi** [ocornut/imgui#6665]
Use the following code on the main window to create a new child window
````
bool show_dialog = true;

ImGui::SetNextWindowSize(ImVec2(400, 200));

ImGui::SetNextWindowPos(ImVec2(100, 100)); // Set the position of the new window

ImGui::Begin("Dialogx1", &show_dialog, ImGuiWindowFlags_NoCollapse);

ImGui::End();
```
`
But the new window disappears immediately

**Comment by ElectroidDes** [comment]
> Use the following code on the main window to create a new child window
> But the new window disappears immediately
> ```

Are you creating a window in your render backend loop? Or did you call Begin/End - only once?

**Comment by Kasi** [comment]
> 

No, on a submenu, I create child a window

`if (ImGui::BeginMenu("Test"))
		{

			if (ImGui::MenuItem("t1"))
			{
		
				ImGui::BeginChild("Another WindowX", ImVec2(300, 200), true);   // Pass a pointer to our bool variable (the window will have a closing button that will clear the bool when clicked)
				ImGui::Button("Hello from another window!");

				ImGui::EndChild();

			}
			
			ImGui::EndMenu();
		
		}`

**Comment by Kasi** [comment]
> > Use the following code on the main window to create a new child window
> > But the new window disappears immediately
> 
> Are you creating a window in your render backend loop? Or did you call Begin/End - only once?

I solved the problem
