### ISSUE TITLE
Problem with UTF-8 encoding 

### ISSUE THREAD

**Issue by Kolhun** [ocornut/imgui#6670]
There was a problem when adding a range with Russian characters, when output it gives "??" and when entering into TextInput and when debagging, everything works fine. What could be the reason?

![image](https://github.com/ocornut/imgui/assets/36815965/0c35d892-e7b3-4719-8cb7-98e2b2736101)
![image](https://github.com/ocornut/imgui/assets/36815965/08fe9a66-407b-4d20-b04a-c6d394db1fd7)
![image](https://github.com/ocornut/imgui/assets/36815965/2163cbc6-e34c-4cec-980d-94285b5e3e78)

**Comment by ocornut** [comment]
The problem is your source code encoding is not utf-8.
It’s a compiler based settings.

**Comment by Kolhun** [comment]
> [ElectroidDes](/ElectroidDes)

Yep

**Comment by Kolhun** [comment]
> The problem is your source code encoding is not utf-8. It’s a compiler based settings.

![image](https://github.com/ocornut/imgui/assets/36815965/a0365e85-3d6a-4d64-b899-7409b25d4523)

I tried this option, it didn't really help

**Comment by ElectroidDes** [comment]
> > The problem is your source code encoding is not utf-8. It’s a compiler based settings.
> 
> ![image](https://user-images.githubusercontent.com/36815965/257728464-a0365e85-3d6a-4d64-b899-7409b25d4523.png)
> 
> I tried this option, it didn't really help

And from the TTF file were the Unicode code points corresponding to Russian characters loaded exactly?


You can try to check:

ImFont_p is a pointer to your downloaded font.

for (int i = 0; i < (*ImFont_p).Glyphs.size(); i++)
{
   std::cout<< (*ImFont_p).Glyphs[i].Codepoint<<std::endl;;
}

**Comment by Kolhun** [comment]
> 

![image](https://github.com/ocornut/imgui/assets/36815965/7915be1d-9702-4ad1-8683-cec2ede65d62)
As I understand it, the output should be viewed here?...

**Comment by Kolhun** [comment]
> The font is not your issue. Your issue is encoding of your source code literal. The fonts documentation explain compiler parameters to use for correct encoding. The compiler option for unicode/multibyte is an option for Win32 library mode but doesn’t impact string literals encoding.

![image](https://github.com/ocornut/imgui/assets/36815965/f766c962-56ae-4f53-a7a9-4a897f067298)
![image](https://github.com/ocornut/imgui/assets/36815965/9214bee7-5c42-4b00-8e28-36dc407294ee)
Using the manual it is possible that I am using pragma incorrectly

**Comment by ocornut** [comment]
I don’t understand what’s causing this but you can see in the debug panel that the compiler output 5 bytes in local cyrillic/russian codepage instead of outputing utf-8 (will be longer than 5 bytes). It may be a file save settings (try save as>using another encoding) or another settings overridding this.
Would be good to understand and share the cause if you find it.
