### ISSUE TITLE
Hovering over menu entry not detected reliably

### ISSUE THREAD

**Issue by GamingMinds-DanielC** [ocornut/imgui#6671]
**Version/Branch of Dear ImGui:**

Version: 1.89.8 WIP (18974)
Branch: docking (have not tested in master)

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: VS 2019 and VS 2022
Operating System: Windows 10 x64

Those shouldn't matter due to the nature of the behavior

**My Issue**

Every now and then I click on the wrong items in some menus. I mostly attributed it to misclicking when moving too fast, but now I took a closer look when it happened again. Sometimes, when switching between menu items with sub menus each, depending on the mouse movement, the selectable of the correct menu item gets hovered, but the wrong one still is active, keeping its sub menu open. This behavior is easy to reproduce on the right side where the arrow icon is, but I have seen it happen further left as well. It is easiest to reproduce with slow, purely vertical mouse movement. Horizontal movement reduces the reproduction rate.

**Screenshots/Video**

![menu_switching](https://github.com/ocornut/imgui/assets/77451134/267a8420-e6a6-49ac-91a0-dca49a6e00cc)

**Standalone, minimal, complete and verifiable example:**

After noticing it in my editor, I checked with an older executable I still had, it happens in 1.89.1 WIP as well. I also reproduced it in the demo window (see animated GIF) with the current version, so no custom code is needed at all. Since the underlying selectable gets visibly hovered, I'm sure it has to be an issue in the menu logic itself, independent of any back-ends.

**Comment by zeh** [comment]
Can reproduce this in Windows, example_win32_directx9 example, VS Community 2022 (17.7.4), against current master (v1.89.9+).

**Comment by ocornut** [comment]
Hello,

Your claim is "I click the wrong item", but if you repro the behavior highlighted in your GIF and click it does always trigger the correct item. Only the open sub-menu looks incorrect. We need some intentional leeway to allow for diagonal move to not accidentally close parent menu. I'm not saying the code cannot be improved (with a mixture of better geometry logic + timer involved), and I am going to look at #6926 but my base heuristic is I cannot trust a change like that if it is submitted without sharing debug visualization.

**Comment by ocornut** [comment]
I ended up adding a fallback timer to reopen another sub-menu: 2ee40d3

I have tried to rework the geometry logic to use a quad where left edge would trail behind the mouse when not over the menu-item: (see where the fallback timer):
![menu_slack_quad](https://github.com/ocornut/imgui/assets/8225057/f1175c22-b03b-4586-ba63-7930bdd4bacc)
But every attempt made vertical navigation annoyingly slower as it would rely on the timer. The extremely tight fit of the current triangle seems to be a good compromise when the timer is on.
