### ISSUE TITLE
Click through window background but not widgets

### ISSUE THREAD

**Issue by pozemka** [ocornut/imgui#6673]
Hello!

![image](https://github.com/ocornut/imgui/assets/1259724/2e5550f8-5598-4257-ab22-880f1f012957)
On this picture the "aaaaa" button is on the "hover" window and the "upgrade me" button is on the window underneath. I need the ability to click on both of them

Is there a way to pass through clicks on widnow background but handle clicks on widgets?

I tired window with `ImGuiWindowFlags_NoBackground` flag, but clicks are not going to underlying window.

If I use `ImGuiWindowFlags_NoMouseInputs` flag then button on my window doesn't handle click bu all other clicks are going throgh.

I've read through FAQ and closest thig is [this](https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-tell-whether-to-dispatch-mousekeyboard-to-dear-imgui-or-my-application) but can't figure how it could help me.

**Comment by pozemka** [comment]
See #8360

**Comment by ocornut** [comment]
Good catch :) I indeed posted a useful blurb in #8360 recently.

Please note that my answer here specifically said "it's not possible between two root windows". It still isn't possible and your question as formulated isn't possible still.

The workaround in #8360 for a root window having input transparency so input can land in the background app.
