### ISSUE TITLE
Added window size constraints

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#668]
Adding this topic so I can link a few commits to it.

We want to be able to specify a minimum and maximum size per-window and per-axis. So it can be possible to have vertical-only resize windows, etc.

This should play decently well with various way of automatically or programatically resizing windows. e.g. we may want to restrict horizontal resizing, but still have vertical size to be automatically computed based on window contents.

We want to able to enforce resizing at certain custom steps (not necessarily linear steps), probably requiring programmatic validation by end-the user.

**Comment by ocornut** [comment]
Added. cc @jarikomppa

`ImGui::SetNextWindowSizeConstraint()`.

Is `Constraint` the right wording? Should be be `Constraints` here?

![resize](https://cloud.githubusercontent.com/assets/8225057/15450808/7f05365a-1fa7-11e6-8b52-84bf7d0151d1.gif)

**Comment by ocornut** [comment]
May now want to add some helper to figure out the difference between window size and "client rect" ?

**Comment by ItsCubeTime** [comment]
@ocornut I cant quite figure out, how do I set a minimum window size on only a specific axis?  The SetNextWindowSizeConstraint function only takes 2 arguments it seems, max and min.

Im using the `WINDOW_ALWAYS_AUTO_RESIZE` flag atm as I want my window to fit the text size, but I also want to make sure that it doesnt just collapse entirely on the horizontal axis if I were to say only use wrapped text in my window

**Comment by PathogenDavid** [comment]
@ItsCubeTime The `min` and `max` parameters are `ImVec2`. As noted on [the documentation for `SetNextWindowSizeConstraints`](https://github.com/ocornut/imgui/blob/1ba2905017ea81545b2fd1d45fee093a4982d9b1/imgui.h#L356), you set the axis you don't care about to -1.

For example, this creates an auto-resized window which has a minimum width of 300:

```cpp
#include <math.h>

static void GH668_ItsCubeTimeComment()
{
    ImGui::SetNextWindowSizeConstraints(ImVec2(300.f, -1.f), ImVec2(INFINITY, -1.f));
    ImGui::Begin("Test", nullptr, ImGuiWindowFlags_AlwaysAutoResize);
    ImGui::TextWrapped("Hello world, the fox jumped over the lazy dog.");
    ImGui::End();
}
```

You can also set `ImGuiStyle::WindowMinSize` during initialization if you want a different minimum size across all windows, or `ImGuiStyleVar_WindowMinSize` with `PushStyleVar`/`PopStyleVar` if you want a different minimum for some subset of windows.
