### ISSUE TITLE
freetype oversampling?

### ISSUE THREAD

**Issue by voidware** [ocornut/imgui#6680]
Version 1.89.5
backend: Sokol
branch: master

Sorry if this has come up already but;

Is there a way to get oversampling on freetype text?

I think I'm right in saying `OversampleH` & `OversampleV` are ignored in freetype? In which case, is there a workaround?

x2 would most likely be fine. Has someone done this already? I could try hacking the code, but thought I'd better check first.

Thanks for any info.

**Comment by Demonese** [comment]
Freetype can generate perfectly rasterized (through techniques such as hint) bitmaps, so Oversample is not necessary.

**Comment by voidware** [comment]
The Atlas it currently generates is only 512x512. if this were bigger, it would look much better when drawn.

**Comment by ocornut** [comment]
You can see by yourself it’s not supported and you are being suggested (here and in docs) that it’s unlikely to be necessary. What else do you need/want? If you absolutely want to see it by yourself you can indeed try hacking the code to support it.

**Comment by ocornut** [comment]
> The Atlas it currently generates is only 512x512. if this were bigger, it would look much better when drawn.

That’s a wrong statement. If it was eg. Exactly twice bigger it would be down sampled on the GPU to average the contents of 2x2 pixels into one. What makes you think the result of that operation would yield a better quality output than the calculation made by Freetype for a given resolution?

**Comment by voidware** [comment]
You're saying the GPU resamples down badly. I'm which case, a 2x atlas wont help. But, If i generate a 2x atlas _then_ scaled it down on the CPU, it might help.
It certainly looks better if i capture the screenshot and scale it.

I might give it a try. Yes close the issue.
