### ISSUE TITLE
Centering an image in a window while permitting scrolling?

### ISSUE THREAD

**Issue by Warwolt** [ocornut/imgui#6684]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Version: Dear ImGui 1.86 (18600)
Branch: docking 

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl2.cpp
Operating System: Windows 10 

**My Issue/Question:**

I'm trying to center an image vertically and horizontally inside of a window. I'm currently doing this by calling `ImGui::SetCursorScreenPos` before calling `ImGui::Image`, but if the window gets resized to be smaller than the image, I get a scroll bar with the behavior that no matter how much I scroll, the image is still displayed the same (which I think makes sense, considering I'm setting the cursor at a fixed position?).

Is there anyway of centering the image in the window, but still allow the window to be resized and scrolled normally? 

**Screenshots/Video**
With issue:
![scrolling](https://github.com/ocornut/imgui/assets/23612880/0df3b247-53fe-499d-9a33-bbf8713aecdb)

Without issue:
![scrollingok](https://github.com/ocornut/imgui/assets/23612880/680f52b8-f329-4395-8f20-aa70f934c613)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
With issue:
```c++
ImGui::Begin("Image Example");
ImGuiIO& io = ImGui::GetIO();
ImTextureID tex_id = io.Fonts->TexID;
float tex_w = (float)io.Fonts->TexWidth;
float tex_h = (float)io.Fonts->TexHeight;
ImVec2 window_pos = ImGui::GetWindowPos();
ImVec2 window_size = ImGui::GetWindowSize();
ImVec2 pos = ImVec2(
    window_pos.x + (window_size.x - tex_w) * 0.5,
    window_pos.y + (window_size.y - tex_h) * 0.5
);
ImGui::SetCursorScreenPos(pos);
ImGui::Image(tex_id, ImVec2(tex_w, tex_h));
ImGui::End();
```

Without issue (can scroll as expected):
```c++
ImGui::Begin("Image Example");
ImGuiIO& io = ImGui::GetIO();
ImTextureID tex_id = io.Fonts->TexID;
float tex_w = (float)io.Fonts->TexWidth;
float tex_h = (float)io.Fonts->TexHeight;
ImGui::Image(tex_id, ImVec2(tex_w, tex_h));
ImGui::End();
```

**Comment by sakiodre** [comment]
Since you're using screen pos, you need to compensate for the window scroll:
```cpp
ImVec2 pos = ImVec2(
    window_pos.x + (window_size.x - tex_w) * 0.5,
    window_pos.y + (window_size.y - tex_h) * 0.5
);
pos.x -= ImGui::GetScrollX();
pos.y -= ImGui::GetScrollY();
```
Also, to avoid blurry image you might want to round its position.

**Comment by ocornut** [comment]
You should probably not use GetWindowPos() nor GetWindowSize() this is only asking for troubles as you have to take account of decoration sizes and scrolling. Instead use `GetCursorScreenPos()` and `GetContentRegionAvail()`. 

Seems like the right solution would be:
```cpp
ImGui::Begin("Image Example", NULL, ImGuiWindowFlags_HorizontalScrollbar);
ImGuiIO& io = ImGui::GetIO();
ImTextureID tex_id = io.Fonts->TexID;
float tex_w = (float)io.Fonts->TexWidth;
float tex_h = (float)io.Fonts->TexHeight;
ImVec2 avail_size = ImGui::GetContentRegionAvail();
ImVec2 pos = ImGui::GetCursorScreenPos();
pos.x += ImCeil(ImMax(0.0f, (avail_size.x - tex_w) * 0.5f));
pos.y += ImCeil(ImMax(0.0f, (avail_size.y - tex_h) * 0.5f));
ImGui::SetCursorScreenPos(pos);
ImGui::Image(tex_id, ImVec2(tex_w, tex_h));
ImGui::End();
```

**Comment by JaydenSu** [comment]
Is this "problem" related to this question:

https://github.com/ocornut/imgui/issues/6641

https://user-images.githubusercontent.com/128853845/255595573-cbe2b9db-7521-4a8c-8120-70f20df3d3ac.mp4

?

**Comment by Warwolt** [comment]
> You should probably not use GetWindowPos() nor GetWindowSize() this is only asking for troubles as you have to take account of decoration sizes and scrolling. Instead use `GetCursorScreenPos()` and `GetContentRegionAvail()`.
> 
> Seems like the right solution would be:
> 
> ```c++
> ImGui::Begin("Image Example", NULL, ImGuiWindowFlags_HorizontalScrollbar);
> ImGuiIO& io = ImGui::GetIO();
> ImTextureID tex_id = io.Fonts->TexID;
> float tex_w = (float)io.Fonts->TexWidth;
> float tex_h = (float)io.Fonts->TexHeight;
> ImVec2 avail_size = ImGui::GetContentRegionAvail();
> ImVec2 pos = ImGui::GetCursorScreenPos();
> pos.x += ImCeil(ImMax(0.0f, (avail_size.x - tex_w) * 0.5f));
> pos.y += ImCeil(ImMax(0.0f, (avail_size.y - tex_h) * 0.5f));
> ImGui::SetCursorScreenPos(pos);
> ImGui::Image(tex_id, ImVec2(tex_w, tex_h));
> ImGui::End();
> ```

This worked like a charm, texture is centered and can be scrolled as expected.
