### ISSUE TITLE
Sources Imgui DX11 and vcpkg

### ISSUE THREAD

**Issue by Kolhun** [ocornut/imgui#6686]
Hi, I installed vcpkg according to the instructions, but at the same time new empty projects see installed libraries and imgui sources do not display vcpkg even in the configuration settings (and does not see libraries). What could be the reason?

Example IGui
![image](https://github.com/ocornut/imgui/assets/36815965/cacd2a1d-a42f-42b1-9fe7-020bf9a82492)

New project
![image](https://github.com/ocornut/imgui/assets/36815965/6b71385e-c6e0-4ab4-80b1-b3515d6270df)

**Comment by ocornut** [comment]
I think vcpkg has an issue where it only works if the platform tooltip used has an IDE installed, so if you use vs2015 (v140) platform toolset you need vs2015 ide installed for vcpkg. You can probably simply fix it by selecting latest **Platform Toolset**.
Beside I'm not even sure vcpkg supports vs2015 toolset anymore, so best to use latest.

**Comment by Kolhun** [comment]
> I think vcpkg has an issue where it only works if the platform tooltip used has an IDE installed, so if you use vs2015 (v140) platform toolset you need vs2015 ide installed for vcpkg. You can probably simply fix it by selecting latest **Platform Toolset**. Beside I'm not even sure vcpkg supports vs2015 toolset anymore, so best to use latest.

In this case, the img ui will no longer work? Which just under 140v works

**Comment by Kolhun** [comment]
Oh, my God, it is! And imgui only works with a low version of the SDK and not the IDE itself, even with 142m earned!

**Comment by ocornut** [comment]
dear imgui works on every setup. It's a matter of you enabling vcpkg integration with your visual studio setup, and making sure the project version use a version you have.
