### ISSUE TITLE
Clarify behavior around building the fonts texture

### ISSUE THREAD

**Issue by heyx3** [ocornut/imgui#6688]
Quick note: I'm using bindings for a niche language, and it's currently stuck on v1.82, so apologies if the code snippets look out-of-date or are using incorrect syntax. But I assume the underlying behavior is unchanged.

I built my own renderer backend, where I use a constant texture handle to represent the font texture atlas. Because I was using a constant handle, I did not think to call `io.Fonts->SetTexID(1)` every single time the font atlas is rebuilt. However, it seems this is  necessary, otherwise the texture associated with text draw calls is null.

It might be helpful in the backend docs to explain somewhere that the currently-set font texture handle gets nulled out when you rebuild the font texture atlas.

**Comment by ElectroidDes** [comment]
> I built my own renderer backend, where I use a constant texture handle to represent the font texture atlas. Because I was using a constant handle, I did not think to call `io.Fonts->SetTexID(1)` every single time the font atlas is rebuilt. However, it seems this is necessary, otherwise the texture associated with text draw calls is null.

Moreover, after rebuilding the texture atlas, you need to convert it and load it again into GPU memory, and you must remember to unload the previous loaded GPU atlas texture, otherwise you will get a memory leak.

**Comment by ocornut** [comment]
You are right, butI'll close this as an upcoming version will rework this anyhow and make SetTexID() obsolete.

**Comment by ocornut** [comment]
FYI here is the ongoing work on `dynamic_fonts` branch toward 1.92: https://github.com/ocornut/imgui/issues/8465.
