### ISSUE TITLE
Minimum Imgui window size by height

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#6689]
The height window does not fully resize to zero, leaving a small area.
Is there a setting in Imgui that allows you to completely resize the Imgui window in height, so that it looks like when it collapses?

![Imgui size](https://github.com/ocornut/imgui/assets/140515246/4018c26a-f966-4aaf-8bde-124a2ec4c239)

**Comment by ocornut** [comment]
There is a WindowMinSize setting in style that you can reduce or alter with PushStyleVar().
