### ISSUE TITLE
Open a child window on top of another

### ISSUE THREAD

**Issue by TheJAXi** [ocornut/imgui#6691]
Im not using the template as this is not an issue with any version per se, more of a general question. 

How could I make a button render another child window on top of the window that the button was on, and have a back button to return to that previous child closing the opened one?

Im trying to make a menu for my game using ImGui, I'm pretty much done other than this slide menu & making the slider handles match my game's theme (Is that possible? To have custom shape? It'd be a Norse style shape)

**Comment by ocornut** [comment]
Sorry but #1586
