### ISSUE TITLE
No way to remove text from slider

### ISSUE THREAD

**Issue by OneAvargeCoder193** [ocornut/imgui#6692]
**Version/Branch of Dear ImGui:**

Version: 1.89.9
Branch: master

**My Issue/Question:**

Is there any way to make a slider without any text? I was looking through the backends and there wasn't any flag for this. I don't know if this is added already or if it isnt a feature in Dear ImGui yet.

Maybe something like this could work?
```
ImGui::SliderFloat("Labelless slider", &x, 0, 1, "%.3f", ImGuiSliderFlags_NoLabel)
```

**Comment by sakiodre** [comment]
Any text after "##" will be hidden, use it as an unique id:
```
ImGui::SliderFloat("##Labelless slider", &x, 0, 1, "%.3f");
```

**Comment by ocornut** [comment]
You may read more about this in the FAQ under "How can I have widgets with an empty label?"
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-widgets-with-an-empty-label
