### ISSUE TITLE
Disable or wrap namespace truetype 

### ISSUE THREAD

**Issue by aabilityuk** [ocornut/imgui#6694]
Hello, i am using ImGui 1.76, and i need to fully disable or hide truetype methods inside of uniqe namespace to make the imgui_draw.cpp  not conflict with openCV library (the last version of opencv_5.x using truetype as background and i am not able to disable it).

1. I tried to use #define IMGUI_STB_NAMESPACE  ImStb in imgui_draw.cpp and i've got the following errors:

```
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_rectpack.h(279,4): error C2668: 'ImStb::stbrp_setup_allow_out_of_mem': ambiguous call to overloaded function
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_rectpack.h(242,16): message : could be 'void ImStb::stbrp_setup_allow_out_of_mem(stbrp_context *,int)'
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_rectpack.h(151,16): message : or       'void stbrp_setup_allow_out_of_mem(stbrp_context *,int)' [found using argument-dependent lookup]
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_rectpack.h(279,4): message : while trying to match the argument list '(stbrp_context *, int)'
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1556,37): error C2668: 'ImStb::stbtt_FindGlyphIndex': ambiguous call to overloaded function
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1461,15): message : could be 'int ImStb::stbtt_FindGlyphIndex(const stbtt_fontinfo *,int)'
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(746,15): message : or       'int stbtt_FindGlyphIndex(const stbtt_fontinfo *,int)' [found using argument-dependent lookup]
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1556,37): message : while trying to match the argument list '(const stbtt_fontinfo *, int)'
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1556,11): error C2660: 'stbtt_GetGlyphShape': function does not take 2 arguments
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(835,15): message : see declaration of 'stbtt_GetGlyphShape'
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1556,11): message : while trying to match the argument list '(const stbtt_fontinfo *, stbtt_vertex **)'
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1608,35): error C2668: 'ImStb::stbtt_FindGlyphIndex': ambiguous call to overloaded function
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1461,15): message : could be 'int ImStb::stbtt_FindGlyphIndex(const stbtt_fontinfo *,int)'
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(746,15): message : or       'int stbtt_FindGlyphIndex(const stbtt_fontinfo *,int)' [found using argument-dependent lookup]
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1608,35): message : while trying to match the argument list '(const stbtt_fontinfo *, int)'
1>C:\Users\User\Desktop\ARC\imgui\include\imstb_truetype.h(1608,11): error C2661: 'stbtt_GetGlyphBox': no overloaded function takes 5 arguments
```
2.  I tried to use #define IMGUI_DISABLE_STB_TRUETYPE_IMPLEMENTATION in imgui_draw.cpp, project compiles without errors but fails on start;

3. I tried to use #define IMGUI_DISABLE_STB_RECT_PACK_IMPLEMENTATION in imgui_draw.cpp and i've got the following errors:
```
2>imgui.lib(imgui_draw.obj) : error LNK2001: unresolved external symbol _stbrp_pack_rects
2>.\Release\ARC.exe : fatal error LNK1120: 1 unresolved externals
```
Help me please complytele disable trutype in imgui (if that possible) or make it completely isolated from other libraries in my project. Thank you!

**Comment by ocornut** [comment]
I am not sure if the underlying design changed, but unfortunately I can’t give support for 1.76 as it is 40 months old. If you can confirm same issues with latest I’d be more inclined to investigate.

You can probably investigate the three paths independently, but getting (2) to work would be ideal.

**Comment by aabilityuk** [comment]
> If you can confirm same issues with latest I’d be more inclined to investigate.
Ok, i'll let you know the result. Thank you

**Comment by aabilityuk** [comment]
Excuse me, but i was not able to test the last version of ImGui because i am using imgui node editor based on imgui and the last version it support is 1.84 WIP. I was able to build my project with 1.84 WIP version and i struggled with the same problems, i followed the second way you suggested (2), but with no luck :(( also i tried all three ways independently with no success! May i ask you to take a brief look at truetype disabling code please?

**Comment by aabilityuk** [comment]
Finally i disabled node editor and gave a try with the last version of imgui_1.89.8 + opencv_5.x(with built in truetype) with no success!!! OpenCV have no options to disable truetype at all... i confirm the same errors and i think the one option for me is somehow hide the imgui internal truetype methods from outside , but #define IMGUI_STB_NAMESPACE doesn't work

**Comment by aabilityuk** [comment]
ocornut, exuse me for wasting your time, question should be closed. I found a linkage bug in my code
