### ISSUE TITLE
Treenode will not expand if in a selectable row of a table

### ISSUE THREAD

**Issue by MauganRa** [ocornut/imgui#670]
This happens when:
- First column has ImGui::Selectable that spans all columns
- A treenode is placed in a row that can be selected

Does making a row selectable prevent the click event from reaching the treenode?
Is there a different way to highlight a row?

Example code to reproduce the issue:
```
#include <ctime>
#include <cstdlib>
#include <vector>
#include <string>
#include <sstream>
#include <iomanip>

static void playground_window2(bool* p_open)
{
	static bool show_treeivew = true;
	static long start_time = 0;
	static std::vector<std::string> IDs;

	if (start_time == 0)
	{
		start_time = GetTickCount();
		srand(time(0));

		for (int i = 0; i < 100; i++)
		{
			std::stringstream ss;
			ss << "0x" << std::hex << (rand() % 2000000);
			IDs.push_back(ss.str());
		}
	}

	long current_time = GetTickCount();

	ImGui::Begin("Messages", &show_treeivew, ImVec2(800, 800));

	ImGui::Columns(2, "mycolumns");
	ImGui::Separator();
	ImGui::Text("Time"); ImGui::NextColumn();
	ImGui::Text("Message ID"); ImGui::NextColumn();

	ImGui::Separator();

	static int selected = -1;

	for (int i = 0; i < 100; i++)
	{
		char label[64];
		unsigned char can_data[8] = { rand() % 255, rand() % 255, rand() % 255, rand() % 255, rand() % 255, rand() % 255, rand() % 255, rand() % 255 };
		double trace_time = (current_time - start_time) / 1000.0;

		// If this is moved into the second column everything works
		// If this is ImGui::Text instead of ImGui::Selectable then everything works
		sprintf(label, "%0.4f", trace_time);
		if (ImGui::Selectable(label, selected == i, ImGuiSelectableFlags_SpanAllColumns))
		{
			selected = i;
		}
		ImGui::NextColumn();

		if (i % 2 == 0)
		{
			// This does not work, the tree will not expand
			if (ImGui::TreeNode(IDs[i].c_str()))
			{
				for (int j = 0; j < 8; j++)
				{
					sprintf(label, "Test Signal Name %d:\t%2x", j, can_data[j]);
					ImGui::BulletText(label);
					//ImGui::TreeNodeEx
				}
				ImGui::TreePop();
			}
		}
		else
		{
			// Add blank text in front of the treenode and then it can be expanded
			ImGui::Text("");
			if (ImGui::TreeNode(IDs[i].c_str()))
			{
				for (int j = 0; j < 8; j++)
				{
					sprintf(label, "Test Signal Name %d:\t%2x", j, can_data[j]);
					ImGui::BulletText(label);
					//ImGui::TreeNodeEx
				}
				ImGui::TreePop();
			}
		}
		ImGui::NextColumn();
	}
	ImGui::End();
}

```

**Comment by ocornut** [comment]
Well, a Selectable() is a button so if it covers the entire columns it will take the click.

1) Is what you want that both the Selectable() and the TreeNode() to receive the click when clicking on tree node?
2) Or would you like the Selectable() to only receive clicks on the first column but render its state spanning all columns?

For 1) you may call SetItemAllowOverlap() after the Selectable() to allow the TreeNode() to take hovered/active state over the previous item. Both will however draw as "Hovered".

We may want to introduce 1B) a flag to Selectable() to explicitly allow that and make the Selectable() NOT detect hovering when hovering over TreeNode(), at the cost of introducing a frame of lag to detect entering within the Selectable() region (no frame of lag in the inside>clicked transition, just the outside>inside transition). This is what #600 is doing.

for 2) We would need to add an extra flag in Selectable() to separate rendering from hit-testing.

**Comment by ocornut** [comment]
PS: Unrelated to your question but a matter of style/performance, TreeNode() takes format string, so instead of doing
```
    static std::vector<std::string> IDs;

    if (start_time == 0)
    {
        start_time = GetTickCount();
        srand(time(0));

        for (int i = 0; i < 100; i++)
        {
            std::stringstream ss;
            ss << "0x" << std::hex << (rand() % 2000000);
            IDs.push_back(ss.str());
        }
    }
```

You could store integer and use TreeNode(id, "0x%08X", id);
I know this is merely an example and they are only created once here, but it's good to avoid using std:;string when possible, can easily sink your perf if used for UI traversal.

**Comment by MauganRa** [comment]
#1 works for me!  Thank you!

I'll keep the string formatting in mind, in the actual app they'll definitely be stored as regular integers.
