### ISSUE TITLE
SDL2 mulitple windows VS imgui

### ISSUE THREAD

**Issue by neoedmund** [ocornut/imgui#6701]
I'm trying to modify the sample "example_sdl2_sdlrenderer2" to allow multiple windows.
Although sdl2 supports multiple windows, but imgui seems to model it's API on just one window.
Although I temporarily commented out the following source, two windows are shown, one of which is of course is not painted.

```
ocornut/imgui/backends/imgui_impl_sdl2.cpp, line 370
		(Assertion failed: io.BackendPlatformUserData == nullptr && "Already initialized a platform backend!")
ocornut/imgui/backends/imgui_impl_sdlrenderer2.cpp, line 62
		(Assertion failed: io.BackendRendererUserData == nullptr && "Already initialized a renderer backend!")
ocornut/imgui/imgui.cpp, line 9198
		(Assertion failed: g.IO.DisplaySize.x >= 0.0f && g.IO.DisplaySize.y >= 0.0f && "Invalid DisplaySize value!")
```

the testing source,
https://gist.github.com/neoedmund/0a8a659611c9b3d068b38bb8d0837fbf

Comments and thoughts please.

Thank you!

**Comment by neoedmund** [comment]
I found out it's something to do with "Multi Viewports" ( https://github.com/ocornut/imgui/wiki/Multi-Viewports#how-can-i-enable-multi-viewports- )
which available in branch `docking`
But I still cannot invoke 
```
	ImGui_ImplSDL2_InitForSDLRenderer ( window , renderer ) ;
	ImGui_ImplSDLRenderer2_Init ( renderer ) ;
```
for multi windows, because  cannot pass the assertion
```
Assertion failed: io.BackendPlatformUserData == nullptr && "Already initialized a platform backend!", 
file ocornut/imgui/backends/imgui_impl_sdl2.cpp, line 418
```
What did I missed?

**Comment by neoedmund** [comment]
Well, I see it's "Missing feature" for SDLRenderer2 , maybe I'll try vulkan or opengl later.

**Comment by ocornut** [comment]
You seem to be creating 1 imgui context and 2 SDL windows + initializing 2 backends, this is never going to work.
You can install 1 backend for 1 context, or 2 backends for 2 contexts.

In multi-viewport mode you can have multiple windows created automatically with 1 backend 1 context, but it's not supported for SDLRenderer2 backend. Someone needs to add support for it.

**Comment by neoedmund** [comment]
@ocornut  Could specify how to or any examples?
I created 2 instances of  `window` and `gl_context` but cannot call `ImGui_ImplSDL2_InitForOpenGL ( window , gl_context ) ;`  twice?

**Comment by neoedmund** [comment]
I see the samples, click on the 'demo window' now it show in a standalone window, so that's the thing, right?
I thought I can create two window by myself and make them to work, which is not "Multi View" meaning.
Anyway there IS a way to create multi windows, so it's okay.

**Comment by ocornut** [comment]
> but cannot call ImGui_ImplSDL2_InitForOpenGL ( window , gl_context ) ; twice?

If you want to call this twice you need to create 2 imgui context `ImGui::CreateContext()` and change context with `ImGui::SetCurrentContext()`.

Probably better to work on add multi-viewport support to SDLRenderer2 backend.

**Comment by neoedmund** [comment]
> If you want to call this twice you need to create 2 imgui context `ImGui::CreateContext()` and change context with `ImGui::SetCurrentContext()`.

I can create multi windows for sdl2+sdl2renderer now using `CreateContext` . 
Sample at https://gist.github.com/neoedmund/99d98df3aec20c469aaa21fdfa3bd67c
Thanks for your help!
