### ISSUE TITLE
Objects overlapping ImGui window.

### ISSUE THREAD

**Issue by xzripper** [ocornut/imgui#6705]
**Version/Branch of Dear ImGui:**

Version: v1.89.8
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: SFML, OpenGL (https://github.com/SFML/imgui-sfml)
Compiler: GCC (G++)
Operating System: Windows 10

**My Issue/Question:**

Any objects I create, are overlapping the ImGui window.

**Screenshots/Video**

![Screenshot_4](https://github.com/ocornut/imgui/assets/94743980/89837364-d452-46cc-9291-5ef05fda9cb2)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
#include "SFML/Graphics.hpp"

#include "imgui/include/imgui.h"
#include "imgui/include/imgui-SFML.h"

int main(void) {
    sf::RenderWindow window(sf::VideoMode(800, 800), "SFML Window.");

    ImGui::SFML::Init(window);

    sf::RectangleShape rectangle(sf::Vector2f(100, 100));

    rectangle.setPosition(100, 100);

    rectangle.setRotation(40);

    sf::Clock clock;

    while(window.isOpen()) {
        sf::Event event;

        while(window.pollEvent(event)) {
            ImGui::SFML::ProcessEvent(event);

            if(event.type == sf::Event::Closed) {
                window.close();
            }
        }

        ImGui::SFML::Update(window, clock.restart());

        ImGui::Begin("Simple window.");

        if (ImGui::Button("Rotate")) {
            rectangle.rotate(1);
        }

        ImGui::End();

        window.clear(sf::Color::Black);

        ImGui::SFML::Render(window);

        window.draw(rectangle);

        window.display();
    }

    return 0;
}

```

**Comment by ElectroidDes** [comment]
So you are drawing the rectangle with SFML and not with Imgui ?
If so, why do you think that your drawn figure should not overlap the Imgui window?

**Comment by xzripper** [comment]
I don't need an rectangle inside of window, I want to draw rectangle on my SFML window, and my ImGui window be on top of the screen.

**Comment by PapaNaxos** [comment]
It may be as simple as putting 

`ImGui::SFML::Render(window);`

as the last line before 

`window.display()`

**Comment by xzripper** [comment]
![Screenshot_5](https://github.com/ocornut/imgui/assets/94743980/543526a3-19a8-4ae5-8914-e85281113db5)
Thank you, now it works!
