### ISSUE TITLE
Pure java port in progress

### ISSUE THREAD

**Issue by elect86** [ocornut/imgui#671]
Hi guys, 

we (me at the very moment) are working on a pure java port of imgui [here](https://github.com/jovr/imgui)

don't hesitate join and participate, we need help trying to make it as good as the original :)

**Comment by Roflraging** [comment]
Are you doing a full port of the original source?  Is it not possible to
just create bindings that call into the public imgui API?  Seems like it
would be a monumental task otherwise...

On Tue, May 24, 2016 at 8:51 AM, Giuseppe Barbieri <notifications@github.com

**Comment by elect86** [comment]
Yep.

My intention is to have a pure java imgui in oder to greatly simplify the dependency, just add a jar and having the whole imgui available.

It's possible of course to create the binding, but this would imply to deal with all the C world headaches..

My goal is to do the most fedele port as possible in order to reduce at minimum all the future modifications. I already did that for glm and gli, in progress for assimp, and it works great, I can catch up months of commits in few hours.

I already ported (almost) all `imgui.cpp`, `imgui.h` and `imgui_internal.h`. I am on my way now on `imgui_draw.h` and `imgui_impl_gl3`.

I paid also attention to report all the original comments, regarding functions/structs/variables

**Comment by ocornut** [comment]
> simplify the dependency, 
> It's possible of course to create the binding, but this would imply to deal with all the C world headaches..

But you are less likely to fully complete and maintain a full port, so using a binding sounds more pragmatic and realistic to me. Either way, it is your project :) I don't know anything aobut the Java ecosystem.

**Comment by elect86** [comment]
Yep, that's the only disadvantage. 

Let's say it's the typical double edge sword, althought even the binding option requires some sort of minimal mantainance if any call/arguments in the original code changes, less likely of course but always present

**Comment by ocornut** [comment]
Closing this as agreed. I have an entry to https://github.com/ocornut/imgui/wiki/Links

**Comment by elect86** [comment]
So.... after jumping on the Kotlin train, I took back this project and upgraded to this new cool jvm language, totally Java compatible...

I also synchronized it to the very last modification: tens of commits in just an hour or so

Fixing a couple of bugs, but the core is there!

![Imgur](http://i.imgur.com/SZIRAvc.png)

**Comment by ocornut** [comment]
Nice! How much of it is functional at the moment?
Monumental amount of work, it still sounds quite crazy to maintain that sort of thing!

**Comment by elect86** [comment]
At the very moment, windows (and its component: tilebar, tooltip), glyphs/text, windows selection, moving and resizing

I am hunting a couple of bugs down now about the window resizing, the minimum size doesnt get respected and another about screwing the text when you resize the window too small and then make it bigger again

Well, it's about 16k loc.. kotlin is quite expressive

Regarding all the stb stuff, at the very first I attempted a port, but then I ended up using lwjgl binding, this offloaded me of a lot of shit work..

It may sound weird, but actually maintenance is really a light task. Since I sticked as much as possible to the original code (as far as possible in the terms of a cpp -> kotlin translation), I can catch up really quickly, even by simply browsing the commits on github and looking at the deltas.

**Comment by elect86** [comment]
Hi Omar!

so, I am on my way to catch up with your fantastic gui.

I am using the test window to test (and finish to implement) all the stuff.

But I noticed something wrong... this

![Imgur](http://i.imgur.com/Q8mKzi6.png)

render this

![Imgur](http://i.imgur.com/BED3WHO.png)

and `Scrolling Text %d` is not completely visible.. is this a bug or misuse?

**Comment by ocornut** [comment]
It's a misuse/feature lacking, the child window here is created with a width of (0) with uses the remaning parent (menu) window size. There's currently no way for a child window to feed it's size back into the parent.

**Comment by elect86** [comment]
shouldn't be this [line](`https://github.com/ocornut/imgui/blob/master/imgui.cpp#L6400)

` else { *v = arg0; } `

instead 

` else { *v = arg1; }` ?

**Comment by ocornut** [comment]
It is correct. In doubt run the C++ code and test it.
The `ImGuiDataType_Int` is scanning and using an int for assignment, only the binary operators are using a float value for the right-side.

**Comment by ocornut** [comment]
Perhaps for clarity the variables should be named `arg0i` and `arg1f` in the `ImGuiDataType_Int` path, and `arg0f` `arg1f` in the `ImGuiDataType_Float` path to reduce confusion for the reader.
