### ISSUE TITLE
Integration of ImGui in mapbox/maplibre 

### ISSUE THREAD

**Issue by wecand0** [ocornut/imgui#6710]
Hello, my little team and me write map-project. We use linux+opengl3+glfw. In this project there is support of glfw, so we can render a lot of custom things and etc, but now want to integrate Dear ImGui, before I have used this great project, it is awesome.

As I understand we have to get framebuffer texture and to call lsuch thing ->` ImGui::Image((void *)tex, size);`

Here it is the link to glfw part  https://github.com/maplibre/maplibre-native/tree/main/platform/glfw

Maybe we have to look at some here 
https://github.com/maplibre/maplibre-native/blob/5a4d3915232235105efd3689592f5a1f04721081/src/mbgl/gl/context.cpp#L181

For this moment(for 2+ weeks) we stuck. Thanks for any help! If it will work with imgui, I will push screenshots, it is intersting.
And one more addition: for the first time we create two windows, one for map, the second for Dear ImGui and it works, but not what we want.

**Comment by ocornut** [comment]
Hello,

You are not even asking a question here and not providing meaningful context but I guess your issue has to do with understanding OpenGL and GLFW concepts and therefore this is not the right location to discuss this.
We have some references in:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

Apologies no patience to deal with this kind of support if you ignored guidelines and recommendations.
