### ISSUE TITLE
Opening a modal causues incorrect TotalVtx/IdxCount

### ISSUE THREAD

**Issue by ZingBallyhoo** [ocornut/imgui#6716]
**Version/Branch of Dear ImGui:**

Version: 1.89.9 WIP (18982)
Branch: docking (unable to reproduce on master)

**Back-end/Renderer/Compiler/OS**

Back-ends: Multiple (tested on custom, imgui_impl_dx11.cpp & imgui_impl_opengl3.cpp)
Compiler: MSVC
Operating System: Windows 10

**My Issue/Question:**

When opening a modal on recent docking branch (upgrading from 1.89.4), the sum of vertex/index buffer counts across all draw lists becomes greater than TotalVtx/IdxCount. A backend that uses these values directly for buffer copying will have graphical corruption (I noticed this due to missing modal backgrounds)

**Standalone, minimal, complete and verifiable example:**

Add the following code to any ImGui_ImplXXX_RenderDrawData
```cpp
int actualVertexCount = 0;
int actualIndexCount = 0;
for (int n = 0; n < draw_data->CmdListsCount; n++)
{
    const ImDrawList* cmd_list = draw_data->CmdLists[n];
    actualVertexCount += cmd_list->VtxBuffer.Size;
    actualIndexCount += cmd_list->IdxBuffer.Size;
}
printf("%d %d - %d %d\n", draw_data->TotalVtxCount, actualVertexCount, draw_data->TotalIdxCount, actualIndexCount);
```
Open any modal (e.g Demo -> Popups & Modal Windows -> Modals -> Delete)
Observe that the reported total (left part of pair) becomes less than the actual sum (right part of pair)

**Comment by ocornut** [comment]
I have pushed a fix f422e7826f57d09ba4e8eb069353ef5eec0a41ef
Thank you for reporting !
