### ISSUE TITLE
Useless texture binding

### ISSUE THREAD

**Issue by elect86** [ocornut/imgui#672]
In the opengl3 example you don't have to call always `glUniform1i` during runtime in the `ImGui_ImplGlfwGL3_RenderDrawLists`, you can call it just once in the `ImGui_ImplGlfwGL3_CreateDeviceObjects`

Ps: program must be bound and you may even skip declaring `g_AttribLocationTex`

**Comment by ocornut** [comment]
It's just unnecessarily weird to split that code across two locations and clearer for the reader to have it there. The perf gain would be very minor.
