### ISSUE TITLE
Unable to edit text in InputText

### ISSUE THREAD

**Issue by xzripper** [ocornut/imgui#6720]
**Version/Branch of Dear ImGui:**

Version: v1.89.8
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: SFML, OpenGL (https://github.com/SFML/imgui-sfml)
Compiler: GCC (G++)
Operating System: Windows 10

**My Issue/Question:**

I'm trying to write dynamic text into input, but it's impossible to edit it.

**Screenshots/Video**

![ld2d_yu81gFlPlw](https://github.com/ocornut/imgui/assets/94743980/1d4732b7-e8cf-4310-b629-22132de454be)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
                ImGui::Text("Editing...: LevelObjectType::TEXT.");

                static char objectName[28];

                strcpy(objectName, object.lobjectname.c_str());

                static char text[MAX_OBJECTS_TEXT_SIZE];
                static char font[MAX_OBJECTS_TEXT_SIZE / 2];

                strcpy(text, object.text.value().c_str());
                strcpy(font, object.font.value().c_str());

                static int fontSize = object.fontSize.value();

                static int objectX = object.objectX;
                static int objectY = object.objectY;

                static int objectRotation = object.objectRotation.value_or(0);

                ImGui::InputText("Object Name.", objectName, IM_ARRAYSIZE(objectName));

                ImGui::InputText("Text.", text, IM_ARRAYSIZE(text));

                ImGui::InputText("Font.", font, IM_ARRAYSIZE(font));
```

How to make text input have already pre-defined content that you can edit?

**Comment by GamingMinds-DanielC** [comment]
What do you mean "impossible to edit"? You are editing the text in the animated GIF.

All of those static variables in your code suggest that you don't know what the keyword `static` actually does. Better read up on it. Also, you omitted copying back the edited values. You are aware that they don't copy themselves back, right?

**Comment by xzripper** [comment]
is there any way to fix it using flags? like ImGuiInputTextFlags_CallbackResize

**Comment by ocornut** [comment]
Hello @xzripper,

`static` essentially means `global`. As pointed by Daniel, and assuming you are referring to the "Text" field reverting, you are copying `object.lobjectname.c_str()` to `objectName[]` every frame, which acts as a revert as soon as the InputText() is inactive.

To edit `std::string` strings you may want to `#include "misc/cpp/imgui_stdlib.h" + link with `misc/cpp/imgui_stdlib.cpp` and use those versions:
https://github.com/ocornut/imgui/blob/master/misc/cpp/imgui_stdlib.h

**Comment by xzripper** [comment]
Thank you! Now it works!
But I still don't understand, is writing static bad? Because I saw in the ImGui manual that every variable is static.

(Working code):
```cpp
static std::string text = object.text.value();
static std::string font = object.font.value();

ImGui::InputText("Text.", &text);
ImGui::InputText("Font.", &font);
```

**Comment by ocornut** [comment]
There's no "good" or "bad" it all depends on the context, but arguably using static this way tends to be a little odd and inedequate to scaling.

We explain the reason we use it this way in the demo:
https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L29

```cpp
//--------------------------------------------
// ABOUT THE MEANING OF THE 'static' KEYWORD:
//--------------------------------------------
// In this demo code, we frequently use 'static' variables inside functions.
// A static variable persists across calls. It is essentially a global variable but declared inside the scope of the function.
// Think of "static int n = 0;" as "global int n = 0;" !
// We do this IN THE DEMO because we want:
// - to gather code and data in the same place.
// - to make the demo source code faster to read, faster to change, smaller in size.
// - it is also a convenient way of storing simple UI related information as long as your function
//   doesn't need to be reentrant or used in multiple threads.
// This might be a pattern you will want to use in your code, but most of the data you would be working
// with in a complex codebase is likely going to be stored outside your functions.
```

**Comment by xzripper** [comment]
> > static std::string text = object.text.value();
> > static std::string font = object.font.value();
> > ImGui::InputText("Text.", &text);
> > ImGui::InputText("Font.", &font);
> 
> Note that doing so you are NOT editing the object.text value, you are COPYING the object.text value into another variable and editing that other variable.

Yes, I know. About static - without the keyword 'static' my recent code did not work.

**Comment by GamingMinds-DanielC** [comment]
> Thank you! Now it works! But I still don't understand, is writing static bad? Because I saw in the ImGui manual that every variable is static.

Was about to post the comments regarding `static` that Omar just posted. Regardless, I would say it is "bad" to write code you don't understand just because you saw it somewhere. Always try to understand code or snippets you copy, look up functions or keywords you don't know and learn about them. Otherwise you are in for a lot of unwanted bugs and side effects.

**Comment by xzripper** [comment]
So I was having problems with static

```cpp
static std::string objectName = object.lobjectname;

ImGui::InputText("Object Name.##rect", &objectName);
```

Whenever `object.lobjectname` changes, objectName stays the same.
But when I remove the 'static' objectName starts to change, but then I can't edit it in 'InputText'.

How to fix it???

**Comment by ocornut** [comment]
This is what I mentioned in my message:
https://github.com/ocornut/imgui/issues/6720#issuecomment-1678680799

> How to fix it???

Call `InputText()` on the value you want to edit...
```cpp
ImGui::InputText("Object Name.##rect", &object.lobjectname);
```

**Comment by xzripper** [comment]
No, it doesn't fix the bug, I still can't edit text like in GIF.

**Comment by xzripper** [comment]
@ocornut, any thoughts???

**Comment by ocornut** [comment]
You are not posting code exhibiting a bug. As the bug is in your code, we can't help you if we don't see the code.

**Comment by xzripper** [comment]
I don't have any bugs in the code, even if I do, they're not exactly problems for this type of problem.

**Comment by sakiodre** [comment]
Is `object.lobjectname` an std::string? If so, `InputText("...", &object.lobjectname);` won't work because it takes a `char*`, `InputText("...", (char*)object.lobjectname.c_str());` won't work either because you'll need to update the size of that string.

If you want to use InputText with std::string, see [imgui_stdlib.h](https://github.com/ocornut/imgui/blob/master/misc/cpp/imgui_stdlib.h).

**Comment by xzripper** [comment]
@sakiodre,
> Is `object.lobjectname` an std::string? If so, `InputText("...", &object.lobjectname);` won't work because it takes a `char*`, `InputText("...", (char*)object.lobjectname.c_str());` won't work either because you'll need to update the size of that string.
> 
> If you want to use InputText with std::string, see [imgui_stdlib.h](https://github.com/ocornut/imgui/blob/master/misc/cpp/imgui_stdlib.h).

i'm already using imgui_stdlib.h, but I have other issue - #6728
