### ISSUE TITLE
CPU usage rises with size of window even without controls

### ISSUE THREAD

**Issue by dtp555-1212** [ocornut/imgui#6723]
I see some odd CPU usage behavior that I can explain… using a cut down example for example_glfw_opengl3… if you have a completely empty application (just the frame) it is using about 2-3 CPUs. (Note: even using the stock example unchanged, the window stretching CPU increase is evident)

If you add in an ‘empty’ Window, the CPU usages can jump up to over 7 CPUs. (stretch the window to see different usages) Note: The high usage is not just during the stretching time, but when the program is idle.

I stumbled upon this odd behavior when I actually closed a CollapsingHeader which should have ‘less’ work to do, and the CPU usage actually went up.

Any ideas on what’s going on? 

P.S. Being a single threaded application, I would not have even suspected more than 2 threads (1 for polling, and 1 to handle the graphics)

OS Ubuntu Linux 22.04 LTS
g++ 11.3
Repeat behavior on latest imgui-master downloaded today (8/15/2023)

example program called out above example_glfw_opengl3... either stock OR with replacing the layout with just
ImGui::Begin("WIN");
ImGui::End();

**Comment by ocornut** [comment]
Issue is not particularly related to dear imgui, rather to a mixture of GL drivers and Linux and GLFW. I doubt some of the assertions are valid (“7 cpu”) but either way here isn’t really the place to discuss it unfortunately.

**Comment by dtp555-1212** [comment]
Do you think there is a better backend to use?

**Comment by ocornut** [comment]
> Do you think there is a better backend to use that might not have this weakness?

It should be easy to try so perhaps you should try SDL+OpenGL and GLFW+Vulkan.

My gut feeling is that the issues lies in OpenGL setup/drivers on your machine. It's very well possible that under some conditions waiting for vsync would dumbly monopolize several cores.

Please also double check the framerate displayed in the example application. It is 60 or tied to your screen refresh rate? Or it is a very unthrolled value (e.g. 4000 FPS) ?
Note that the example apps rely on vertical-sync for throttling and have no particular idle mechanism, so on a 240 HZ screen the example would naturally use more CPU than on a 60 HZ screen, but the amount you are seeing are not right.

**Comment by dtp555-1212** [comment]
On the FPS, when the window is smaller, it is getting an FPS of around 650, when the window is stretched out, it drops down to a bit less than 200 FPS. It just uses 'a lot' of CPU.  Obviously, I don't need 650 FPS. If there is a setting to cap that, 'maybe' that would help? 

I will try some other backends, and let you know if this is a wider spread issue. Thanks for your help, and all your hard work on this great project! Hopefully, together we can find a reason (and a solution).

**Comment by dtp555-1212** [comment]
Well… when a make a very small window, I too get around 1800 FPS… I was reporting the 600 FPS on a usable sized window, so I could see everything in the demo app.

--
The ones I can readily build on linux.
glfw_opengl2, sdl2_opengl2, sdl_sdlrenderer2 all have the same behavior

You mentioned ‘vulkan’, but all the imgui examples seem to be set up to build those on windows, not linux.
P.S. you mention driver setup as 'inefficient'... they are out of the box drivers in the Ubuntu system. If there are some changes that you suggest to people, I would love to hear that. I haven't seen any documentation (so far) that suggests anything in the vein.
–

Some additional info… this is a server class machine (yes, as you saw in the screen shot, I am 512 GB of memory). The graphics are going to a virtual screen, then displayed remotely, so, I would not expect it to be throttled by any vsync, since not actually on an actual monitor locally. I want to ultimately use 'many' of these instances, but since each one is very resource intensive when it comes to CPUs that greatly reduces the potential scalability.

The screen size is 2560x1600… it does not 'have' to be that big, but I am remote on a 4K screen

If any of that triggers any ideas, I am all ears. Thank again
