### ISSUE TITLE
Visual glitches on SDL2 + OpenGL3

### ISSUE THREAD

**Issue by OneForgottenMan** [ocornut/imgui#6726]
**Version/Branch of Dear ImGui:**

Version: 1.89.9 WIP
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC
Operating System: Windows 7

**My Issue/Question:**

I have visual glitches with elements drawing when, I suppose, there is more than one window (including opened menu-item's) inside draw area. It works correctly on my friend PC and laptop, but on mine laptop I have these glitches.

**Screenshots/Video**

![opengl3_glitch](https://github.com/ocornut/imgui/assets/58083488/93bdb79c-a68d-41b5-b61e-ebe0f5e8e89e)

**Comment by GamingMinds-DanielC** [comment]
If the same executable works as intended on other machines, it is most likely a driver issue. What GPU does your machine have and which driver version do you have installed? If you don't use the latest available drivers, try upgrading them first.

**Comment by OneForgottenMan** [comment]
Oh, I apologize for disturbing you. It really turned out that it was not the latest drivers. Everything works fine now.
