### ISSUE TITLE
Incorrect Color data on Big Endian hardware

### ISSUE THREAD

**Issue by austinharms** [ocornut/imgui#6732]
**Version/Branch of Dear ImGui:**

Version: 1.89.9 WIP (18983)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: Custom Backend Using libogc for Wii/Gamecube
Compiler: GCC/G++
Hardware: Wii

**My Issue:**
Texture and Vertex color data (RGBA32) are always in little endian regardless of the hosts architecture
I fixed the issue by simply byte swapping (__builtin_bswap32) the color data before uploading and rendering it
but that is more of a quick fix then solving the root issue

**Screenshots**
Note: the applied style was `ImGui::StyleColorsDark();` for all images and only the default font was loaded, I have not tried loading fonts from file
Expected Result:
![Expected](https://github.com/ocornut/imgui/assets/43386423/e410b8d3-fae3-4a7a-9832-dfbc0bdb9175)
Actual Result:
![Result](https://github.com/ocornut/imgui/assets/43386423/946613ff-d499-4ec3-8cac-371852b32fbd)
Result with fixed texture atlas only(not vertex data):
![FixedAtlas](https://github.com/ocornut/imgui/assets/43386423/61fc6236-81f2-43e8-9775-d4599832c082)

**Comment by ocornut** [comment]
Have you tried  IMGUI_USE_BGRA_PACKED_COLOR or to create an alternative macro?

**Comment by austinharms** [comment]
`IMGUI_USE_BGRA_PACKED_COLOR` Did not work but defining the following did
```
#define IM_COL32_R_SHIFT    24
#define IM_COL32_G_SHIFT    16
#define IM_COL32_B_SHIFT    8
#define IM_COL32_A_SHIFT    0
#define IM_COL32_A_MASK     0x000000FF
```
Thanks and sorry for the inconvenience
