### ISSUE TITLE
Trying to make a 2-Column custom widget using Tables API

### ISSUE THREAD

**Issue by richardeakin** [ocornut/imgui#6739]
I am trying to make  a widget using `imguizmo.quat' and some `DragFloat`s that looks like the following:

![widget-imgui-table-want](https://github.com/ocornut/imgui/assets/5132127/c4784c59-f63f-44a0-81ea-7f13a93450f1)

but I'm struggling to get the three floats aligned to the right. Instead, my widget currently looks like:

![widget-imgui-table-wip](https://github.com/ocornut/imgui/assets/5132127/b57307e3-4b14-41d2-a18a-72f48b9b468b)

which was done with the following function:

```cpp
bool Direction( const char *label, glm::vec3 *v )
{
	BeginTable( label, 2 );

	bool edited = false;

	TableNextRow();
	TableSetColumnIndex( 0 );
	Text( label );
	TableSetColumnIndex( 1 );
	PushStyleColor( ImGuiCol_FrameBg, vec4( 0 ) );
	edited |= gizmo3D( "##direction arrow", *v, IMGUIZMO_DEF_SIZE, imguiGizmo::modeDirection );
	PopStyleColor();

	TableNextRow();
	TableSetColumnIndex( 0 );

	edited |= DragFloat( "x", &v->x );
	edited |= DragFloat( "y", &v->y );
	edited |= DragFloat( "z", &v->z );

	EndTable();

	return edited;
}

void updateUI()
{
    vec3 lightDir = { 0, -1, 0 };
    Direction( "light dir", &lightDir );
}

```

What is the proper way for placing the three floats in a colum to the right of the arrow? In this case, the row heights are not the same between columns 0 and 1.

Using Dear ImGui Version: v1.89.8
Branch: docking

Thanks for any tips,
Rich

**Comment by Bartis1313** [comment]
Applying the direction arrow is a widget taking rectangle-like space for itemsize, code can be like this: (I commented all custom stuff)
```c++
struct Vec3 { float x; float y; float z; };
bool Direction(const char* label, /*glm::vec3*/ Vec3* v)
{
    ImGui::BeginTable(label, 2, ImGuiTableFlags_SizingStretchProp);
    bool edited = false;

    ImGui::TableNextColumn();
    ImGui::Text(label);

    ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4{ 0, 0, 0, 0 });
    ImGui::Image(nullptr, { ImGui::CalcTextSize(label).x, 40 }); // edited |= gizmo3D( "##direction arrow", *v, IMGUIZMO_DEF_SIZE, imguiGizmo::modeDirection );
    ImGui::PopStyleColor();

    ImGui::TableNextColumn();

    edited |= ImGui::DragFloat("x", &v->x);
    edited |= ImGui::DragFloat("y", &v->y);
    edited |= ImGui::DragFloat("z", &v->z);

    ImGui::EndTable();

    return edited;
}
```
![image](https://github.com/ocornut/imgui/assets/69613796/b4bb539f-48a5-4b18-a3b1-454e1997bb9c)

[check tables from demo](https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L3903)

**Comment by ocornut** [comment]
Richard I am little bit confused by your question, since your code request to display the drags in column 0 (left) and the arrow in column 1 (right) so this is what's happening indeed.

Thank you Bartis for your answer. Basically the answer suggest you can fit both the label and the gizmo in the same cell, so your table would have one row.

Please note that although this will work, as outlined by Bartis answer, the Tables API has quite some overhead which in theory I would myself consider inadequate for this purpose. If you submitted hundreds of this widget it would means hundreds of Tables and it is likely to use more CPU than strictly needed for this. It probably doesn't matter in the grand scheme of things but I wanted to point this out.

Another way to achieve the desired layout would be:

```
BeginGroup();
Text("Label");
DragFloat( "x", &v->x );
DragFloat( "y", &v->y );
DragFloat( "z", &v->z );
EndGroup();
SameLine();
Gizmo3D();
```

Which may be a little harder to tweak or iterate on, but for this specific layout likely to be much faster.

**Comment by richardeakin** [comment]
Thanks for the answers! I didn't know about `NextColumn()`, still learning the new Tables API and I llike how flexible it is.

@ocornut not sure if there is a way to get my arrow on the left without the tables API is there? I suppose I can manually move the cursor pos.. I'm more or less recreating a widget in imgui here that I have using other UI toolkits in the past, one that I found useful for manipulating normalized directions.

**Comment by ocornut** [comment]
> @ocornut not sure if there is a way to get my arrow on the left without the tables API is there? I

This is exactly what the code in my message is doing.

**Comment by ocornut** [comment]
> not sure if there is a way to get my arrow on the left without the tables API is there? I

For clarity, here's the code variation for arrow on the left (as my example put it on the right).

```cpp
BeginGroup();
Text("Label");
Gizmo3D();
EndGroup();
SameLine();
BeginGroup();
DragFloat( "x", &v->x );
DragFloat( "y", &v->y );
DragFloat( "z", &v->z );
EndGroup();
```

Basically BeginGroup() will lock the starting X posiiton.
