### ISSUE TITLE
The label is on the left.

### ISSUE THREAD

**Issue by zhouxs1023** [ocornut/imgui#674]
where to set label on the left as below:
![image](https://cloud.githubusercontent.com/assets/905931/15570923/dd4f030a-236a-11e6-9135-f0c34e91064e.png)

**Comment by ocornut** [comment]
Duplicate, this is part of WIP https://github.com/ocornut/imgui/issues/395
But trust me, it is a fake good-idea.

Right now you can work-around it by using Text, SameLine, Widget("##hidelabel", ..);

**Comment by Alan-FGR** [comment]
There's one problem with SameLine: the label won't be centered vertically :(

**Comment by rationalcoder** [comment]
@Alan-FGR AlignTextToFramePadding() does the job for now.

**Comment by Alan-FGR** [comment]
@rationalcoder i'll give that a try. thank you :+1:
