### ISSUE TITLE
Feature Request: Word wrapped InputText

### ISSUE THREAD

**Issue by iwubcode** [ocornut/imgui#6741]
**Version/Branch of Dear ImGui:**

Version: 1.89.7
Branch: master

**Back-end/Renderer/Compiler/OS**

Custom backend
Visual Studio
Windows 11

**My Issue/Question:**

Not seeing any specific way to support word wrapping in a `InputText`.  Looked at the previous issues (all about Multiline) and also the demo code (wrap examples but nothing for `InputText`).  I'm rather new to Imgui but I would have assumed `Text` and `InputText` used the same functionality for drawing text under the hood.

**Screenshots/Video**

Wrapped Text:
![text_wrapped](https://github.com/ocornut/imgui/assets/15224722/d77155f0-5ef3-458e-8535-a933e555905b)

vs

InputText:
![text_input](https://github.com/ocornut/imgui/assets/15224722/ef5961e0-cfe5-4b11-b1dc-112a5cc47924)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Imgui supports something like this:

```
ImGui::WrappedText("My really really really really really really long text");
```

But ideally should have:

```
std::string my_string = "My really really really really really really long text";

// From imgui_stdlib
ImGui::WrappedInputText("##MyText", &my_string);

// Do something with the contents of the text
```

I'm not aware of any open issues or requests for this.  Thank you for this wonderful library!

**Comment by ocornut** [comment]
Hello,

This is a known missing feature and there is an open issue for it #3237

I have been working on the side on new lower-level text functions to support wrapping as a more first-class citizen and in a more optimal manner but I don't know when I'll be able to finish this work.
![20230112-text_funcs](https://github.com/ocornut/imgui/assets/8225057/cb8bfcc2-5e47-4c5e-b95d-6b63accc122d)

I'm also afraid `InputText()` is likely going to need a larger rework, part of it has been done in private branches but likewise it needs bandwidth to be as a desirable quality level. 

Will post here when solved.

**Comment by iwubcode** [comment]
Thank you @ocornut for our continued work on this project.  Will look forward to your progress!

**Comment by sakiodre** [comment]
While we're at this, what do you think we should do to implement highlightable/selectable text? #950

I had tried to implement it multiple times with no success. We need some kind of an ID system like the widgets to save the states but still allow duplicated texts, and there's the position/order problem. One thing I tried is to wrap the texts in an `ImGui::Highlightable` to give them an ID, but messing with the low-level text rendering really affects the performance (when dragging the mouse) because it needs to do collision-checking for every single glyph.

**Comment by ocornut** [comment]
@sakiodre moving this to #950
