### ISSUE TITLE
Stack corruption in imgui_demo.cpp

### ISSUE THREAD

**Issue by davecamp** [ocornut/imgui#6742]
Hiya,
First off... thank you for such an incredible Gui !

However I've found a small and potentially nasty bug within the imgui_demo.cpp file.
In the tree node for 'MousePosition Cursors' you have a for-loop to display the names of all of the mouse cursors. The names are put into a char buffer of 32 bytes but some names, along with the pre-text require more than 32 bytes causing a buffer over-run and stack corruption. Some texts being put into the buffer by the sprintf are 33 and 34 bytes plus the null terminator. Obviously just a simple increase in the size of the buffer resolves the issue.

```
for (int i = 0; i < ImGuiMouseCursor_COUNT; i++)
{
    char label[32];       // <---------------------------- Buffer is too small for all variants in the following line
    sprintf(label, "MousePosition cursor %d: %s", i, mouse_cursors_names[i]);
    ImGui::Bullet(); ImGui::Selectable(label, false);
    if (ImGui::IsItemHovered())
        ImGui::SetMouseCursor(i);
}
```

Thank you again for a 1st class immediate mode GUI 👍

**Comment by ocornut** [comment]
Hello,
Thanks for reporting. I checked multiple branches and our code says:
```
sprintf(label, "Mouse cursor %d: %s", i, mouse_cursors_names[i]);
```
Which fits.

It looks like you have a modified version of the demo.

**Comment by davecamp** [comment]
Hiya,

Indeed it must have been changed in the last couple of weeks as I cloned the repo from here on 07 August 2023.
The version number I have here is 'dear imgui, v1.89.9 WIP', quoted from the top of the demo cpp file.

Anyway, main take away is that the issue isn't there any more. I'll pull the latest version this evening. 👍 

Thanks and regards.

**Comment by ocornut** [comment]
According to git blame it hasn't changed for a while, for both branches the last change was 45736443be1e18a2441e599395dd12a4928eed5e

In a normal codebase I'd suggest using snprintf of course (or better, an idiom [like this helper class](https://github.com/ocornut/Str) but we try to not litter the demo code with noise so we often use raw sprintf() here. Not that Visual Studio replaces them with template versions automatically filling the buffer size.

**Comment by davecamp** [comment]
I wondered what has happening here so I checked our main code repo using git blame too to see if had changed locally and to my surprise the file was changed and checked in locally on our repo on 8th August 2023 🤦‍♂️

I'm so sorry for raising this embarrassingly false issue.

Regards.
