### ISSUE TITLE
first SameLine coordinates per NewLine is wrong

### ISSUE THREAD

**Issue by tourkit** [ocornut/imgui#6743]
```
Dear ImGui 1.89.7 WIP (18965)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=202002
define: _WIN32
define: _WIN64
define: __MINGW32__
define: __MINGW64__
define: __GNUC__=11
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000440
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 800.00,600.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.89.7
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: glfw & opengl3
Compiler: gcc
Operating System: win10

**My Issue/Question:**

when using a series of SameLine(x_coord) it seems that the first occurence of each line only applies half of the desired offset

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/63537158/75aeb433-fea4-4ced-b078-8e3951738260)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("test sameline");
for (int i = 0; i < 40; i++) {

    if (!(i % 10)) ImGui::NewLine();

    ImGui::SameLine((i%10)*30); 

    ImGui::Text("0");

}
ImGui::End();
```

**Comment by tourkit** [comment]
Ok , Im very sorry for bothering you guys ... value 0 is actualy , as the doc says , for aligne with last element, solution I found was adding .00000001 . I guess you can close this issue, again, very sorry

**Comment by ocornut** [comment]
> for aligne with last element, solution I found was adding .00000001 

Yes. The prototype is:
```cpp
void SameLine(float offset_from_start_x=0.0f, float spacing=-1.0f)
```
I'm actually a bit displeased with the behavior of `float offset_from_start_x` as I don't think it is a good design, but it was designed as a way to be a simplistic version of columns.

(
I unfortunately cannot suggest using "spacing" instead, e.g.
```cpp
for (int i = 0; i < 40; i++) 
{
    if ((i % 10) > 0)
        ImGui::SameLine(0.0f, 30.0f);
    ImGui::Text("0");
}
```
Because that logic wouldn't work if the contents has different size (different numbers).
)

An alternative is to use `BeginTable()`.

In the future I am also intending to introduce a way to use tabbing (as in `\t\`) to align to desired offsets.
