### ISSUE TITLE
ColorPicker panel defaults to black

### ISSUE THREAD

**Issue by OVOAOVO** [ocornut/imgui#6746]
Why is padding needed twice here?
![image](https://github.com/ocornut/imgui/assets/88096545/7f32dc9c-f339-4ffa-8300-88474207a6c9)
It made my box black :(

**Comment by OVOAOVO** [comment]
![image](https://github.com/ocornut/imgui/assets/88096545/6fbe5887-bf32-4673-b616-b87e9f830670)
like this

**Comment by GamingMinds-DanielC** [comment]
No padding there, just filled rects. The second rect is for the fade to black at the bottom, top left and top right are fully transparent black while bottom left and bottom right are solid black. Do you use a custom backend for rendering? If yes, check your blending setup.

**Comment by OVOAOVO** [comment]
Thank you for your answer, it has been very helpful to me.
