### ISSUE TITLE
Vulkan backend crash on click "Display Desktop" Button(or WIN+D on windows)

### ISSUE THREAD

**Issue by neoedmund** [ocornut/imgui#6747]
https://github.com/ocornut/imgui/blob/040e818d7215b648e216c25fa51c6093e273f651/backends/imgui_impl_vulkan.cpp#L1312

I just "fix" the bug by change the line to `        if (cap.currentExtent.width == 0xffffffff || cap.currentExtent.width <= 0) `

but since I do not catch why it use `cap.width` instead of parameter `width` , so I'd rather leave the real fix to the author. 

Thanks.

**Comment by neoedmund** [comment]
It's on Windows 11 with Intel Iris GPU. I cannot access the machine until Monday, so maybe detailed report until then.
atm I can only say vulkan reports cap size is 0, but SDL2 window size is not. at this point, it's safe to add `|| cap.currentExtent.width == 0`

> * does it happens in vanilla examples or only in your app?

examples not checked yet. 

> * are multi-viewports on or off?

off

> * what's the crashing callstack?

vulkan driver error

> * debug layer report?

say like "cannot use size 0*0"

> * vulkan sdk version?

less lastest 1.3.250.1

**Comment by ocornut** [comment]
When minimizing a window the reported client size becomes (0,0).

Our example code only resize swapchain when we get a valid value back:
```cpp
        // Resize swap chain?
        if (g_SwapChainRebuild)
        {
            int width, height;
            glfwGetFramebufferSize(window, &width, &height);
            if (width > 0 && height > 0)
            {
                ImGui_ImplVulkan_SetMinImageCount(g_MinImageCount);
                ImGui_ImplVulkanH_CreateOrResizeWindow(g_Instance, g_PhysicalDevice, g_Device, &g_MainWindowData, g_QueueFamily, g_Allocator, width, height, g_MinImageCount);
                g_MainWindowData.FrameIndex = 0;
                g_SwapChainRebuild = false;
            }
        }
```

Perhaps your app is not handling this correctly?

**Comment by neoedmund** [comment]
I used SDL2 but should be  the same. Here `glfwGetFramebufferSize()` get a positive value, but in 
`ImGui_ImplVulkanH_CreateOrResizeWindow`
https://github.com/ocornut/imgui/blob/040e818d7215b648e216c25fa51c6093e273f651/backends/imgui_impl_vulkan.cpp#L1312
`cap.currentExtent.width` == 0 and != `width` (the parameter).
`if (width > 0 && height > 0)` not worked for `cap.currentExtent`

**Comment by neoedmund** [comment]
The samples code has no such problem. 
So the problem should be in my own program. Though the flow is very same,  and `SDL_GetWindowSize` returns 800x600, but in `ImGui_ImplVulkanH_CreateOrResizeWindow()` the cap returns 0x0 which is odd. However I will look into the situation later. 
Since the sample is good, closing the issue.

**Comment by ocornut** [comment]
Please post it when you find your answer :)
