### ISSUE TITLE
Clip Image Display To A Region ?

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#675]
Hello,

What is a quick way to display image but clipping it? Basically the image texture is 640x480. In the window I have the space of maybe 300,200. I want to add a image showing 300x200 maybe the center of 640x480 without any scaling.

http://i.imgur.com/CZnZ7Ql.png

I looked at the addimage function but I think the backend part of it scales.

Vivienne

**Comment by ocornut** [comment]
Use 320,200 as size and change uv to display a different section of the image.
For example (0.25,0,25) (0.75,0.75) will be the center of the image.

Divide texture position in pixels by the texture size to get uv in the (0,0) ... (1,1) range.

PS: please don't use imgur for pictures. You can attach pictures to issues by dragging one within your text.
