### ISSUE TITLE
Input Events?

### ISSUE THREAD

**Issue by neoedmund** [ocornut/imgui#6750]
I read demos and find we can use `ImGui::IsKeyPressed(k)` and `io.InputQueueCharacters` for inputed text.
But is there a `event` when any key is pressed? because I don't want to check all the keys to find out that. 
I'm writing a text editor, if a shortcut is undefined, I need to show message like "unknown keystoke <kbd>ctrl-alt-F12</kbd>"
Any advice? thank you.

I guess there are 2 ways:
1. consider open up internal struct `InputEventsQueue` for external use?
2. my program talk to backend like sdl2 directly.

**Comment by ocornut** [comment]
> because I don't want to check all the keys to find out that.

Why? It's a 2 line for loop?

Consider that there are analog inputs (e.g. gamepad sticks) which may always be pressed on some circumstances.
Also obscure OS features like sticky keys may lead to mod being held etc. So you likely need to do some filtering to select which keys to consider.

> my program talk to backend like sdl2 directly.

You need a `SDL_PollEvent()` polling loop anyway, you can indeed check `event->type == SDL_KEYDOWN`.

**Comment by ocornut** [comment]
Also see #6191

**Comment by neoedmund** [comment]
Thanks you for the information. with loop 
```
   for ( int key = ImGuiKey_NamedKey_BEGIN; key < ImGuiKey_NamedKey_END; ++key )
        if ( ImGui::IsKeyPressed( (ImGuiKey)key ) )
            return true;
    return false;
```
 I guess both ways are reasonable. What I need to do is to find out which way fit my need better. By the way, as a text editor, I don't want to have 120 fps, I'd like to refresh only when change made to save the GPU power. 
Thanks and closing the issue.
