### ISSUE TITLE
Finer control over ImGuiWindowFlags_NoMouseInputs Flag

### ISSUE THREAD

**Issue by Sundava** [ocornut/imgui#6752]
**My Issue/Question:**

I would like to be able to ignore rightclick only.
Looking at the possible flags, I see that there is a flag avaiable to ignore all mouse inputs, `ImGuiWindowFlags_NoMouseInputs`, but this would prevent all type of clicks to be handled.

The feature I would like to see is either several flags for different types of click, or a way to specify which mouse events should be ignored.

I am thinking the enum would look along the line of something like this: 
```C#
enum ImGuiWindowFlags_
{
    ...
    ImGuiWindowFlags_NoMouseInputs_LeftClick          = 1 << 9,   // Disable catching mouse left click, hovering test with pass through.
    ImGuiWindowFlags_NoMouseInputs_RightClick        = 1 << 10,   // Disable catching mouse right click, hovering test with pass through.
    ...
    ImGuiWindowFlags_NoMouseInputs          = ImGuiWindowFlags_NoMouseInputs_LeftClick | ImGuiWindowFlags_NoMouseInputs_RightClick,
    ImGuiWindowFlags_NoInputs               = ImGuiWindowFlags_NoMouseInputs | ImGuiWindowFlags_NoNavInputs | ImGuiWindowFlags_NoNavFocus,
};
```

Is this something feasible, or should I simply not use the `ImGuiWindowFlags_NoMouseInputs` flag and filter the mouse input flags manually ?

**Comment by ocornut** [comment]
> I would like to be able to ignore rightclick only. 

Why? Please clarify context.

**Comment by Sundava** [comment]
A popular plugin for FFXIV, DelvUI, uses ImGui to draw health bars on the screen.
One of the controls to move the camera around in the game is left/right clicking anywhere on the screen and dragging the mouse.

These health bar should be left clickable to target the related enemy, but there is no need for them to handle a right click input.

When right clicking or left clicking these bars, the "Camera move" action is ignored, as I am assuming the mouse event is consumed by the ImGui window.

Setting the `ImGuiWindowFlags_NoMouseInputs` flag restores the camera movement functionnality, but disables the left click to target functionality. Having a way to ignore input for a specific type of click would solve the problem.

I assume the other way of solving it would be not using `ImGuiWindowFlags_NoMouseInputs` and ignoring/forwarding any right mouse click event back to the game, but a Left Click/Right Click separation for clickthrough seems like a useful feature that could be applied to other use cases.

**Comment by ocornut** [comment]
It’d be unfortunately very difficult to implement. We need to decide and lock a hovered window at the beginning of the frame, which solely depends on mouse position.

Given the description of your use I’d say you shouldn’t need to use individual windows for each overlayed healthbar, which sounds a little bit overkill.
I would suggest to create 1 window covering the screen, make it invisible (no decorations, background etc) then you can draw healthbars in there and do hit-testing.

To perform hit-testing when you submit healthbars you can use eg InvisibleButton() or lower level ButtonBehavior().
Before that submit a single large button covering the screen with the AllowOverlap flag and you can use that for camera logic, OR you don’t need a button for camera logic you can just process it when the window is hovered and no item is hovered.

You might even decide to only submit a single button for the whole viewport including healthbars if you need finer, non-rectangle based hit-testing.

**Comment by Sundava** [comment]
I see, that's unfortunate.
I was under the assumption that the `ImGuiWindowFlags_NoMouseInputs` flag played a part at the mouse click listener level, but it looks like I was wrong.  

Thanks for taking the time to answer me, and thanks for spending time maintaining this project !

**Comment by GamingMinds-DanielC** [comment]
You don't have to set the same flags every frame. So a potential easy fix for your specific situation would be to specify `ImGuiWindowFlags_NoMouseInputs` only while the right mouse button is currently down or just released. Or while the left mouse button is neither down nor just released in case you want it handled while both are pressed.
