### ISSUE TITLE
How to make the background of  a docking window transparent ? 

### ISSUE THREAD

**Issue by absss** [ocornut/imgui#6759]
i want to build a docking window above the main window ,it is outside the main window, i can not let it to be transparent, i  try use the flag "ImGuiWindowFlags_NoBackground" or " ImGui::PushStyleColor(ImGuiCol_WindowBg, { 0, 0, 0, 0.0 });" but all of these  is not work, what should i do? i look forward to your help, thank you very much!

**Comment by ocornut** [comment]
See similar issues #2766 #6558 #4629

It requires a backend change, it's not widely supported yet.

Please note that even when this will be supported for rendering, inputs will likely always be caught by a rectangular area.

**Comment by dgm3333** [comment]
This is my solution... https://github.com/ocornut/imgui/issues/6558
