### ISSUE TITLE
How to set position and size of a Popup Modal

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#676]
Hi.

I'm trying to set the window position and size of a popup modal window.
I've tried with:
```c++
    if (ImGui::BeginPopupModal(...)) {
        ImGui::SetWindowPos(wndPos);
        ImGui::SetWindowSize(wndSize);
        ...
        ImGui::EndPopup();
    }
```
but it doesn't seem to work... 

Actually it seems that the window is always centered... am I missing some flag ?

**Comment by ocornut** [comment]
Always use SetNextWindowPos,
      SetNextWindowSize()
      SetWindowPos/SetWindowSize may be removed.
      
      
      On 29/05/2016 13:41, Flix wrote:
    
    
      Hi.
      I'm trying to set the window position and size of a popup modal
        window.
        I've tried with:
      
            if (ImGui::BeginPopupModal(...)) {
        ImGui::SetWindowPos(wndPos);
        ImGui::SetWindowSize(wndSize);
        ...
        ImGui::EndPopup();
    }
      
      but it doesn't seem to work... 
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on
          GitHub, or mute
          the thread.

**Comment by Flix01** [comment]
Thanks!

**Comment by ocornut** [comment]
Does it actually fix your issue?

**Comment by Flix01** [comment]
Yes! Although I had also one frame delay before SetNextWindowPos was actually applied.
Not sure if that is something dealing with my specific (very complex) code...

Basically I had to call SetNextWindowPos(...) at the frame after the one in which I called for the first time ImGui::OpenPopup() and ImGui::BeginPopupModal().

However this frame-lag issue was very easy to handle for me.
