### ISSUE TITLE
Duplicate window instances?

### ISSUE THREAD

**Issue by talkalotwhenim** [ocornut/imgui#6768]
Wondering if you could possibly clone a window at the click of a button. Say for instance, I opened up the demo window and in there, there was a button I could press that would make a new demo window, but wouldn't close the previous one. What would be an efficient way of doing this that isn't just copy and paste logic used to create the original window? Ultimately I'd like to be able to create as many as the users system could handle. In each window there would be an option to make another

**Comment by ocornut** [comment]
You can create any window you need, provided they all have a different identifier.

Use the "##" suffix to add contents to the identifier without displaying it:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

```
for (int n = 0; n < 10; n++)
{
   char name[50];
   sprintf(name, "My Window##%d", n);
   ImGui::Begin(name);
   ...
   ImGui::End();
}
```
Here it'll show 10 different windows all showing a visible title of "My Window".

**Managing your state cloning logic etc is up to you. Dear ImGui display the things you send at it.**

You however cannot do it with e.g the Demo Window for the simple reason that the identifier of that window is out of the your control and has been fixed to "Dear ImGui Demo Window".
