### ISSUE TITLE
Handling events on a per-window basis

### ISSUE THREAD

**Issue by mrb0nk500** [ocornut/imgui#6769]
**Version/Branch of Dear ImGui:**

Version: 1.89.9 WIP
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp
Operating System: Linux

**My Issue/Question:**

I've been wanting to use ImGui in [Lightspark](https://github.com/lightspark/lightspark), but the issue is that because Lightspark is inherently event driven, if I want it to be rendered in it's own window, it becomes a lot harder to deal with input events.

One of the reasons this is hard is because there's no real way to check if a window is focused, or hovered without a current window. If we had a way of doing that, it'd make this a lot easier.

It's kinda hard to give an example of this on my own, but this issue is similar to #4234, but unlike that one, we have to do things in an event driven manner, there's no getting around that.

Is there a good way of properly solving this problem?

**Comment by mrb0nk500** [comment]
btw, the reason for wanting to use ImGui in Lightspark is because we've also been wanting to make a native web version, much like [Ruffle](https://github.com/ruffle-rs/ruffle), and ImGui has web support.

**Comment by ocornut** [comment]
> but the issue is that because Lightspark is inherently event driven, if I want it to be rendered in it's own window, it becomes a lot harder to deal with input events.

I don't understand this.
It doesn't matter than Lightspark is event driven. Lightspark use its events, Dear ImGui use its logic, both can cohabit.
You need to be more explicit as to which problem you think you cannot solve. What exactly do you think is hard?

> One of the reasons this is hard is because there's no real way to check if a window is focused, or hovered without a current window. 

You can check `g.NavWindow` or `g.HoveredWindow` and compare them to whatever you like. 
This is simple but however I worry that you are currently asking about a [XY Problem](https://xyproblem.info/) and don't actually need to do this.

> It's kinda hard to give an example of this on my own

You will have to.

> Is there a good way of properly solving this problem?

Very probably but it will only start by you exposing your actual problem rather than being vague :)

**Comment by mrb0nk500** [comment]
> You can check g.NavWindow or g.HoveredWindow and compare them to whatever you like.
Doesn't that require including `imgui_internal.h`?

**Comment by ocornut** [comment]
> Doesn't that require including imgui_internal.h?

Yes it does. But again it is probable this is not the right solution, but without being given the right problem we cannot give you the right solution.

**Comment by mrb0nk500** [comment]
> You need to be more explicit as to which problem you think you cannot solve. What exactly do you think is hard?

The issue is that just including `imgui.h` on it's own doesn't really give you a way of checking if a window is focused/hovered, without having a current window, but because we need to know this during the event loop, we don't have a current window.

**Comment by mrb0nk500** [comment]
> It doesn't matter than Lightspark is event driven. Lightspark use its events, Dear ImGui use its logic, and whatever it is, both can perfectly cohabit.

It does matter if you want it to render in it's own window, since like I said, this requires knowledge of whether that window is focused, and/or hovered.

And the reason for wanting to render in it's own window is so that we can have a context menu, and/or a menu bar.

**Comment by ocornut** [comment]
I don't understand your question or problem.

**Comment by mrb0nk500** [comment]
The whole point is that there should be some externally visible way of being able to deal with input events on a per-window basis.

**Comment by mrb0nk500** [comment]
If we didn't need a context menu, or menu bar, then I wouldn't have made this issue in the first place.

**Comment by mrb0nk500** [comment]
> The whole point is that there should be some externally visible way of being able to deal with input events on a per-window basis.

And the simplest way of doing that is to be able to check if a window is focused/hovered, but without a **current window**.

**Comment by mrb0nk500** [comment]
> > but **without a current window**.
> 
> I believe this violates the very principles of immediate-mode UIs which don't really have much persistent state.

No, it doesn't, since others like [egui](https://github.com/emilk/egui) don't have this issue.

**Comment by mrb0nk500** [comment]
I mentioned egui specifically because that's what Ruffle uses, and they haven't had any issues like this.

**Comment by mrb0nk500** [comment]
I think it's possible for an Immediate-mode UI to do something like this, or at least similar to it.

Maybe it can be done with a more portable event loop, and let each window have their own callback that let's them deal with that event, and can then tell the event loop whether it handled it, or not.

**Comment by mrb0nk500** [comment]
After all, windows are preserved between frames. Since that's pretty much a requirement.

**Comment by mrb0nk500** [comment]
And if we need the user to set the callback on each frame, we can add a `SetNextWindowXXX()` function for this.

**Comment by mrb0nk500** [comment]
The only reason I haven't done that is because that requires having a portable event loop in the first place, and that's quite the task, especially for what I wanted to do.

**Comment by ocornut** [comment]
This is not a chat room, every message you write here gets sent to 1000 people.
You are not explaning your problem, you are discussing your guessed solution.
Please read the issues guidelines VERY carefully. If your next message doesn’t provide a clear problem I will ask you to leave this place. Thank you.

**Comment by mrb0nk500** [comment]
> This is not a chat room, every message you write here gets sent to the email of 1000 people.
> 
> You seem to be misunderstanding something but it’s hard to know whay, you are not explaning your problem, you are discussing your guessed solution. Please read the issues guidelines VERY carefully. If your next message doesn’t provide a clear problem I will ask you to leave this place. Thank you.

See #4234
