### ISSUE TITLE
Implementing ImGUI with custom window library

### ISSUE THREAD

**Issue by ziacko** [ocornut/imgui#677]
Hey Ive been trying to implement iMGUI with my own OpenGL window system by following the GLFW example to a tee but all i get is slighlty scrambled text [here](https://drive.google.com/open?id=0B-G4BV7qacYmRjFWYW8tMGhQWEE) It appears that only the text renders. I am sure I a simply missing a function call or something of that nature. Here is the [repo ](https://github.com/ziacko/Portfolio/tree/master/Examples/Scene) in the scene example.

**Comment by ziacko** [comment]
I found and fixed the issue. sorry about that

**Comment by ocornut** [comment]
I quickly skimmed at your repo, and I am not sure to understand why you aren't just copying and using/adapting `imgui_impl_glfw.cpp` code instead of rewriting the code in a way that won't easily update with new versions and probably has new issues.

**Comment by ziacko** [comment]
Iwas trying to get it to work last night. After i fixed the bug Ive been re-writing the imGUI rendering system from scratch now that I have a better understanding.
