### ISSUE TITLE
Dynamically creating new instances of CheckBox

### ISSUE THREAD

**Issue by P8ON-code** [ocornut/imgui#6770]
**Version/Branch of Dear ImGui:**

Version: 1.89.8
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: DirectX 12

**My Issue/Question:**

Let's keep it simply. I'm searching for a way to dynamically creating new CheckBox (or other interactable elements).
 As far, I wasn't able to come with the idea by myself, so I'm sorry if my question may sound basic or ignorant.

**Comment by ocornut** [comment]
The whole premise of Dear ImGui is that everything is dynamic all the time. If you call a `Checkbox()` function in your main loop, a checkbox will appear. If you don't call it, the checkbox won't appear.

Consider this:

```cpp
if (ImGui::GetIO().KeyShift)
    ImGui::Checkbox(.....);
```
The checkbox will only appear when holding Shift.

**Comment by P8ON-code** [comment]
Thanks for reply, I'm really impressed by amount of work you put in ImGui.

It's really nice concept with "Shift".

I'm trying to do something similar to to-do list, so creating new CheckBoxes as needed while program is running is what I'm looking for.
I'm thinking about something like:
```
if (ImGui::Button ("Add New Task"))
    CreateNewCheckBox(label, &boolean);
```
I have tried few approaches and so far, but new CheckBoxes would appear for like 1 frame and then disappear.

Do I need to someway save a reference to CheckBox? Their ImGuiID? Or maybe I'm missing something?

**Comment by nicolasnoble** [comment]
> Do I need to someway save a reference to CheckBox? Their ImGuiID? Or maybe I'm missing something?

Please read Omar's message again. There is no notion of persistence in an immediate-mode UI. If you want a checkbox to appear on the screen, you have to explicitly draw it every single frame. If you want to accomplish what you're talking about, you need to hold the persistence of the state yourself.

```c++
if (ImGui::Button("Add New Task")) {
  someInternalStorage->push_back(new SomeInternalClassForCheckBoxes())
}

for (auto & c : someInternalStorage) {
  ImGui::Checkbox(c.label, &c.value);
}
```

In this case, you are responsible for writing the internal storage class and the checkbox class that's suitable for your application.

**Comment by P8ON-code** [comment]
WOW!

**Comment by P8ON-code** [comment]
It worked, thank you for help.
Great explanations and great help. Thank you both and wish you good luck and Happy Life!

I hope, someday, I will be able to help others just like you did help me!
