### ISSUE TITLE
How to check if there are delayed events?

### ISSUE THREAD

**Issue by neoedmund** [ocornut/imgui#6773]
I heard that ImGui will do things like separate a keystroke into several frames, then there will be more events than what caught from backends like SDL2.
My question is : Is there a function like `HasDelayedEvents()` ? 
Because I control the FPS by myself in Vulkan(when there are no events, I keep the renderer idle) I need to draw more frames in this situation. Thanks.

**Comment by ocornut** [comment]
Using imgui_internal.h you can access g.InputsEventQueue and check if it’s empty or not at the end of the frame or after NewFrame().

I would however advise against doing so and simply letting the library do its thing. Trickled events are relatively rare at good/interactive framerates and generally not perceived as a concern based on feedback received here.
