### ISSUE TITLE
What is ImGui's philosophy on Table vs ContentRegion, responsive design, and nesting?

### ISSUE THREAD

**Issue by elanhickler** [ocornut/imgui#6775]
The way that seems like an obvious way to work is to setup tables and other box elements to create a layout. This allows for responsive and clean design. As a new user I somewhat expect the GetContentRegion functions to give values based on the box that we are in, be it  a table or not.

Ok, you can actually nest tables, so the functionality is already here.

I'm sure no one minds just coming up with a set of functions to handle all this. But, this seems like a missed opportunity. Also, if someone started an issue about this already, the GitHub search function is horrendous.

**Comment by elanhickler** [comment]
you know what, my code must be bad.

**Comment by elanhickler** [comment]
Ok, re-opening the issue. Maybe there's something to talk about. I can't actually find a function like GetContentRegionMax that gives width, height, x, y. I'm only seeing width.

**Comment by elanhickler** [comment]
One thing I am starting to notice is the difficulty of knowing what functions to call to get areas and positions due to x1y1 functions being named differently from x2y2 fuinctions such as ConentRegion functions and FrameHeight vs ContentRegion.

I'm currently putting together a guide for this, as you can see, I'm marking out all regions and padding. Having trouble getting my knobs to be centered in tables and columns. Not asking for help on that.

![image](https://github.com/ocornut/imgui/assets/9116575/44f21295-088c-4103-973b-9539928c9d82)

**Comment by ocornut** [comment]
Please try to ask explicit questions. Right now your first message and second do not contains a question and I am not sure what to make out of them.

>  OK, cursor position is going to give me the x1y1, ContentRegion stuff will give me x2y2 hopefully.

I'd recommend to only use `GetCursorScreenPos()` (current x,y) and `GetContentRegionAvail()` (avail width/height from current position).

It's a legacy design flaw that `GetCursorPos()`, `GetContentRegionMax()`, `GetWindowContentRegionMin()`, `GetWindowContentRegionMax()` are in some arbitrary window-local coordinates space (basically add `GetWindowPos()` to make them absolute). I would like them to be absolute coordinates but it's not an easy transition. In addition the Max of that value is typically aligned to the window size without possible scrolling, so those functions are not very useful when scrolling is involved. Calling `SetNextWindowContentSize()` allow specifying a content size for a window, in which case content region max is aligned to it. 

**I suggest to use the Metrics/Debugger window to visualize all those rectangles.**

We will probably do a switch to absolute coordinates when we introduce a the concept of Working Rectangle, which should sort of be an improved version of what's currently referred as ContentRegion (with the possibility of doing e..g `PushWorkRect()` to lock yourself into a smaller area) with more design clarity when scrolling involved.

> One thing I am starting to notice is the difficulty of knowing what functions to call to get areas and positions due to x1y1 functions being named differently from x2y2 functions such as FrameHeight vs ContentRegion vs CursorPos.

I am not sure I understand the second half of that sentence.
I believe the biggest confusion comes from the local-coordinates functions. 

In addition to tools in Metrics/Debugger, consider using `GetForegroundDrawList()->AddXXX()` calls to display position and geometry if unsure. I frequently use idioms like:

```cpp
if (io.KeyShift)
   ImGui::GetForegroundDrawList()->AddCircle(my_pos, ...);
```
To debug display.

**Comment by elanhickler** [comment]
All good, everything is working.

![SoEmAdditiveGUI_djjBazHfxF](https://github.com/ocornut/imgui/assets/9116575/8bc01788-14de-43aa-9fdc-df5cd9286a8f)


```cpp
ImVec2 toVec2(float n) {
    return ImVec2(n, n);
}
ImVec2 addVec2(std::initializer_list<ImVec2> vecs) {
    ImVec2 point;
    for (auto& v : vecs) {
        point.x += v.x;
        point.y += v.y;
    }
    return point;
}

void drawTarget(ImVec2 center_px, ImU32 color, float size_px = 9.0f) {
    float half      = size_px * 0.5;
    float stroke_px = 1.0f;

    ImVec2 p1 = { center_px.x - half, center_px.y };
    ImVec2 p2 = { center_px.x + half, center_px.y };
    ImVec2 p3 = { center_px.x, center_px.y - half };
    ImVec2 p4 = { center_px.x, center_px.y + half };
    ImGui::GetWindowDrawList()->AddLine(p1, p2, color, stroke_px);
    ImGui::GetWindowDrawList()->AddLine(p3, p4, color, stroke_px);
}

class SubtractiveSynthUI {
  public:
    void Render(bool* open) {
        if (!*open) {
            return;
        }

        // if (!ImGui::Begin("Synth", NULL, ImGui::GetCurrentWindow()->Flags)) {
        //     ImGui::End();
        //     return;
        // }

        ImGui::DragFloat("Slider", &dragFloatCapture_, .0001f, 0.f, 1.f, "%.6f", flags_);

        const ImVec2 SCROLL_DELTA = ImVec2(-1.0f * ImGui::GetScrollX(), -1.0f * ImGui::GetScrollY());

        const float STROKE_PX   = 1;
        const ImVec2 STROKE_ADJ = toVec2(STROKE_PX * 0.5f - 0.5f);

        const int TABLE_ROWS    = 2;
        const int TABLE_COLUMNS = 3;

        if (ImGui::BeginTable("table1", TABLE_COLUMNS)) {
            for (int row = 0; row < TABLE_ROWS; row++) {
                ImGui::TableNextRow(ImGui::GetFrameHeight());
                for (int column = 0; column < TABLE_COLUMNS; column++) {
                    ImGui::TableSetColumnIndex(column);

                    ImVec2 offset = addVec2({ ImGui::GetWindowPos(), ImGui::GetCursorPos(), SCROLL_DELTA, STROKE_ADJ });
                    ImVec2 p2     = { offset.x + ImGui::GetContentRegionAvail().x, offset.y + ImGui::GetFrameHeight() };
                    ImGui::GetWindowDrawList()->AddRect(offset, p2, COLOR_BLUE);

                    std::string s = std::string("Knob") + std::to_string(row) + "." + std::to_string(column);
                    ImGui::KnobFloat(s.c_str(), &dragFloatCapture_, .01f, 0.f, 1.f, "%.6f", flags_);
                }
            }
            ImGui::EndTable();
        }

        { /* SHOW PADDING AFTER TABLE */
            float width   = ImGui::GetContentRegionMax().x - ImGui::GetStyle().WindowPadding.x;
            float height  = ImGui::GetStyle().ItemSpacing.y;
            ImVec2 offset = addVec2({ ImGui::GetWindowPos(), ImGui::GetCursorPos(), SCROLL_DELTA });

            // padding
            ImVec2 p1 = { offset.x, offset.y - height };
            ImVec2 p2 = { p1.x + width, p1.y + height };
            ImGui::GetWindowDrawList()->AddRect(p1, p2, COLOR_RED, 0.0f, 0, STROKE_PX);
        }

        { /* SHOW WINDOW AREA */
            ImVec2 offset = addVec2({ ImGui::GetWindowPos(), STROKE_ADJ });
            ImVec2 p2     = addVec2({ offset, ImGui::GetWindowSize() });
            ImGui::GetForegroundDrawList()->AddRect(offset, p2, COLOR_RED, 0.0f, 0, STROKE_PX);
        }

        { /* SHOW WINDOW AREA WITH PADDING */
            ImVec2 windowSize = ImGui::GetWindowSize();
            ImVec2 offset     = addVec2({ ImGui::GetWindowPos(), STROKE_ADJ });
            ImVec2 padding    = ImGui::GetStyle().WindowPadding;
            float titleHeight = ImGui::GetCurrentWindow()->TitleBarHeight();

            ImVec2 p1 = { offset.x + padding.x, offset.y + padding.y + titleHeight };
            ImVec2 p2 = { offset.x + windowSize.x - padding.x, offset.y + windowSize.y - padding.y };
            ImGui::GetForegroundDrawList()->AddRect(p1, p2, COLOR_BLUE, 0.0f, 0, STROKE_PX);
        }

        { /* SHOW WIDGET AREA AND PADDING */
            float width   = ImGui::GetContentRegionMax().x - ImGui::GetStyle().WindowPadding.x;
            float height  = ImGui::GetFrameHeight();
            ImVec2 offset = addVec2({ ImGui::GetWindowPos(), ImGui::GetCursorPos(), SCROLL_DELTA, STROKE_ADJ });

            // area
            ImVec2 p2 = { offset.x + width, offset.y + height };
            ImGui::GetWindowDrawList()->AddRect(offset, p2, COLOR_YELLOW, 0.0f, 0, STROKE_PX);

            // padding
            ImVec2 p3 = { offset.x, offset.y + height };
            ImVec2 p4 = { offset.x + width, offset.y + ImGui::GetFrameHeightWithSpacing() };
            ImGui::GetWindowDrawList()->AddRect(p3, p4, COLOR_RED, 0.0f, 0, STROKE_PX);
        }

        { /* TARGET WIDGET AREA AND PADDING */
            // upper left
            ImVec2 offset = addVec2({ ImGui::GetWindowPos(), ImGui::GetCursorPos(), SCROLL_DELTA });

            // lower right
            float width  = ImGui::GetContentRegionAvail().x - 1.0f;
            float height = ImGui::GetFrameHeightWithSpacing() - 1.0f;
            ImVec2 p2    = { width + offset.x, height + offset.y };

            drawTarget(offset, ImColor(1.0f, 1.0f, 1.0f, 1.0f));
            drawTarget(p2, ImColor(1.0f, 1.0f, 1.0f, 1.0f));
        }

        { /* SHOW TEXT AREA */
            ImVec2 offset      = addVec2({ ImGui::GetWindowPos(), ImGui::GetCursorPos(), SCROLL_DELTA });
            float width        = ImGui::GetContentRegionAvail().x;
            float height       = ImGui::GetFontSize();
            float height_delta = ImGui::GetFrameHeight() - height;

            // adding extra space to represent where text will be cut off
            float clippingExtension = ceilf(ImGui::GetStyle().WindowPadding.x * 0.5f);

            ImVec2 p1 = { offset.x + 1.0f, offset.y + height_delta - 1.0f };
            ImVec2 p2 = { offset.x + width + clippingExtension, offset.y + height + 1.0f };
            ImGui::GetWindowDrawList()->AddRectFilled(p1, p2, COLOR_WHITE, 0.0f, 0);

            ImGui::AlignTextToFramePadding();
            ImGui::Text("ABC abc Q q i j t p ");
            ImGui::Text("ABC abc Q q i j t p ");
        }

        { /* SHOW WINDOW PADDING */
            ImVec2 win_pos   = ImGui::GetWindowPos();
            float win_width  = ImGui::GetWindowWidth();
            float win_height = ImGui::GetWindowHeight();
            float titlebar   = ImGui::GetCurrentWindow()->TitleBarHeight();
            float pad_horiz  = ImGui::GetStyle().WindowPadding.x;
            float pad_verti  = ImGui::GetStyle().WindowPadding.y;

            ImVec2 p1, p2;

            // left padding
            p1.x = win_pos.x;
            p2.x = p1.x + pad_horiz;
            p1.y = win_pos.y + titlebar + pad_verti;
            p2.y = win_pos.y + win_height - pad_verti;
            ImGui::GetForegroundDrawList()->AddRectFilled(p1, p2, COLOR_GREEN, 0.0f, 0);

            // right padding
            p1.x = win_pos.x + win_width;
            p2.x = p1.x - pad_horiz;
            p1.y = win_pos.y + titlebar + pad_verti;
            p2.y = win_pos.y + win_height - pad_verti;
            ImGui::GetForegroundDrawList()->AddRectFilled(p2, p1, COLOR_GREEN, 0.0f, 0);

            // top padding
            p1.x = win_pos.x;
            p2.x = p1.x + win_width;
            p1.y = win_pos.y + titlebar;
            p2.y = p1.y + pad_verti;
            ImGui::GetForegroundDrawList()->AddRectFilled(p1, p2, COLOR_WHITE, 0.0f, 0);

            // bottom padding
            p1.x = win_pos.x + win_width;
            p2.x = win_pos.x;
            p1.y = win_pos.y + win_height;
            p2.y = win_pos.y + win_height - pad_verti;
            ImGui::GetForegroundDrawList()->AddRectFilled(p2, p1, COLOR_WHITE, 0.0f, 0);
        }

        // ImGui::End();
    }

  private:
    const float defVal_ = 0.123f;
    float dragFloatCapture_{ defVal_ };
    ImGuiSliderFlags flags_{ ImGuiSliderFlags_AlwaysClamp };
};
```

**Comment by ocornut** [comment]
Some feedback

(1) I don't think you need to do that:
```cpp
ImVec2 offset = addVec2({ ImGui::GetWindowPos(), ImGui::GetCursorPos(), SCROLL_DELTA, STROKE_ADJ });
```
You can use `ImGui::GetCursorScreenPos()` instead (and add STROKE_ADJ).

(2) This looks incorrect
```
float width   = ImGui::GetContentRegionMax().x - ImGui::GetStyle().WindowPadding.x;
```
Using `float width = ImGui::GetContentRegionAvail().x` is probably correct.

(3) You should never need to use GetWindowWidth(), GetWindowHeight(). I am even tempted to remove those functions because 99% of uses are incorrect.

**Comment by ocornut** [comment]
Your "/* SHOW WINDOW PADDING */" block also suggest you haven't been using the Tools in Metrics/Debugger else you wouldn't need to write it.

If you follow the instructions above you'll end up with simpler code., but start by removing every call to GetWindowPos(), GetScrollX(), GetScrollY(), and instead use GetCursorScreenPos().

As a suggestion: I also find it curious how people frequently tend to call the same function over and over again, e.g. `ImGui::GetForegroundDrawList()` it makes the code both longer to write, slower to execute, and more annoying to use a debugger with. I would suggest it is preferable to cache any value locally that you can.

**Comment by elanhickler** [comment]
Thanks, I will take all your suggestions. The reason my code is like this is so that you can easily copy-paste and/or remove without breaking it. I have a few more goals with this, once those are done I will start writing proper code that involves classes and caching.

**Comment by ocornut** [comment]
I didn’t suggest that “using classes and caching” was generally proper, I meant local variable caching :)

**Comment by elanhickler** [comment]
![image](https://github.com/ocornut/imgui/assets/9116575/a11bdf4f-a26d-4e6d-9b6f-c7e6a4f8001b)
![image](https://github.com/ocornut/imgui/assets/9116575/767ce171-308a-418c-9e8b-8e1675c324c0)
![image](https://github.com/ocornut/imgui/assets/9116575/5d84c84e-3b06-4e4f-819b-be19ab080bb0)
![image](https://github.com/ocornut/imgui/assets/9116575/e1b9145c-8c5a-4a11-b3dc-58804e75945a)
![image](https://github.com/ocornut/imgui/assets/9116575/782cf2cc-e607-4c25-9a39-6596d9f33c0c)

**Comment by elanhickler** [comment]
![SoEmAdditiveGUI_8Xk2ttD5mG](https://github.com/ocornut/imgui/assets/9116575/2f5e52ae-8f5d-4568-a7a4-7176b11fe8ac)

![image](https://github.com/ocornut/imgui/assets/9116575/fbb365cb-1832-4493-a3e8-af84ae387432)

![SoEmAdditiveGUI_QUZtzzbkPv](https://github.com/ocornut/imgui/assets/9116575/ba6394ac-4985-4cae-a07e-34ffcf349fe1)

![SoEmAdditiveGUI_0RnKeIgT1G](https://github.com/ocornut/imgui/assets/9116575/0ff76079-acb7-4a15-b9b6-7978f57a3bca)

![SoEmAdditiveGUI_EVui33O9BZ](https://github.com/ocornut/imgui/assets/9116575/86c2baad-3eb6-485c-bd0f-4089ae8f4619)
