### ISSUE TITLE
How do I print filesystem::path which contains unicode?

### ISSUE THREAD

**Issue by tksuoran** [ocornut/imgui#6776]
Simply calling filesystem::path::string() throws an exception for some unicode paths like `res\\assets\\glTF-Sample-Models\\2.0\\Unicode❤♻Test`:

![image](https://github.com/ocornut/imgui/assets/994606/41392977-b24b-4fd5-85a7-2c6e78786266)

What is the recommended way to get `filesystem::path` into something I can ask ImGui to render as text? Thanks!

**Comment by nicolasnoble** [comment]
That's not exactly an ImGui question.

You simply need to use the correct conversion function from the C++ standard: https://en.cppreference.com/w/cpp/filesystem/path/string

**Comment by ocornut** [comment]
Bit surprising of you to post this @tksuoran as indeed it doesn't really seem to be a dear imgui issue.
I don't know those std-lib functions myself and even the documentation seems ambiguous to me, but does `u8string()` + cast works for you?

**Comment by tksuoran** [comment]
My apologies, indeed this is not really ImGui related issue. As long as I get path as string with UTF8 encoding, and my font has used characters, I should be able to render paths with ImGui. I have it working sufficiently for now; I did run into some issues but they are not ImGui related.

**Comment by ocornut** [comment]
For reference, can you confirm if using `filesystem::path::8string()` was the solution or not?

**Comment by tksuoran** [comment]
I am currently using this:
```
std::string to_string(const std::filesystem::path& path)
{
    auto utf8 = path.u8string();
    auto s = std::string(reinterpret_cast<char const*>(utf8.data()), utf8.size());
    return s;
}
```
Things like `std::isalnum()` not to work with `std::string` when it contains UTF8 encoded string, so those need to be avoided.

**Comment by mdhvg** [comment]
If you want to just display it using `ImGui::Text(...)`, you can use `%ls` for the paths.
```cpp
for (auto const& path : imagePaths) {
    ImGui::Text("Path: %ls", path.c_str());
}
```
