### ISSUE TITLE
Add unsigned int overload for Combo and ListBox?

### ISSUE THREAD

**Issue by EliasD** [ocornut/imgui#678]
Conceptually there's no point of using ComboBox and ListBox with signed integers, because indexes of their items there are non-negative. So it's natural to use these GUI elements with unsigned int variables, which is not currently possible, because there's only int* support. 

Maybe there's a reason behind Combo and ListBox not having unsigned int overloads, but looking at their code, I see that they use Items_ArrayGetter and idx is int index, which can be unsigned int/size_t without losing much (what's the point of calling items[idx] with negative value anyway?).

**Comment by ocornut** [comment]
It is possible to specify -1 when no item is selected (within a combo box).
We don't typically add overload for every type to minimize API explosion and because you can always cast your unsigned int* to int*, literally adding `(int*)` before your pointer when calling a function.
