### ISSUE TITLE
How can I change the color of the box of a checkbox? (Index for checkbox colors)

### ISSUE THREAD

**Issue by AlphaCrystal2** [ocornut/imgui#6791]
**Version/Branch of Dear ImGui:**

Version: Current ()
Branch: Master

**Back-end/Renderer/Compiler/OS**

Back-ends: dx9
Compiler: VS 2022 
Operating System: Windows

**My Issue/Question:**

Hey everybody,

I am just looking for the index for styling/coloring checkmark boxes.

I can color the checkmark, but not the box itself. I cannot find this on styles for some reason.

I am looking to change the color of the BOX not the check itself.

My code to change a checkbox (even tho u wont need it lmao)

void styleColors() {
     ImGui::GetStyle().Colors[ImGuiCol_CheckMark] = ImVec4(1.f, 1.f, 1.f, 1.f);
}

thanks!

**Comment by ocornut** [comment]
It is `ImGuiCol_FrameBg`, shared color for all framed items, you can quickly discover them into the style editor.

**Comment by GamingMinds-DanielC** [comment]
If you want to change all checkbox frame backgrounds and nothing else, you can make a custom wrapper for the checkbox. Just duplicate the interface and pass all parameters to the original. Push the desired color(s) first with `ImGui::PushStyleColor()` and restore afterwards with a call to `ImGui::PopStyleColor()`.
