### ISSUE TITLE
Convert whatever float ColorPicker3 returns to IM_COL32

### ISSUE THREAD

**Issue by AlphaCrystal2** [ocornut/imgui#6792]
Hey,

So I have this color picker:

ImGui::ColorEdit3("Color", &clr);

and I am trying to make it the color of a circle.

The only problem is that coloredit3 returns a float instead of the IMCOL_32 type.

how can I convert this float into IMCOL_32 (or a Vector4 rgb)?

thanks!

**Comment by GamingMinds-DanielC** [comment]
`ImGui::ColorEdit3()` doesn't return a float, it edits an array of 3 floats. Use them to construct an `ImVec4` (4th component is alpha, set it to 1.0f) and give that to `ImGui::ColorConvertFloat4ToU32()`.

**Comment by ocornut** [comment]
Also note the `ImColor()` helper struct can easily convert from one to the other.

**Comment by AlphaCrystal2** [comment]
> `ImGui::ColorEdit3()` doesn't return a float, i

But the argument is a pointer to a float, no?

**Comment by GamingMinds-DanielC** [comment]
> But the argument is a pointer to a float, no?

Technically yes since an array is basically a pointer to the first element. But take a look at the function declaration:
```c++
IMGUI_API bool ColorEdit3(const char* label, float col[3], ImGuiColorEditFlags flags = 0);
```
Here you can see that `col` expects an array of 3 floats to edit. That is a pointer to the first of 3 consecutive floats containing the R, G and B values.
