### ISSUE TITLE
Guide on custom widgets, animations, and drawing on top of the menu instead of below

### ISSUE THREAD

**Issue by AlphaCrystal2** [ocornut/imgui#6794]
Hey guys,

So the info that was requested doesn't really matter.

I want to learn how to create something like this: https://www.youtube.com/watch?v=wAEoE0s_OHw

I could probably make most of the basic loader, but the spinning circle (0:02) is very clean and is probably a ton of math, but I think you can do it without having to do a draw list (since that draws underneath the window)

The button animation (0:07) is also very clean and I would like to learn how to do that as well.

And finally, the loading bar (0:15-0:17) is really nice and it would be cool on how to do that too.

I know that this would probably take a while, so I'm not asking you to write it for me because none of you have the time to throw away on me. I just want a guide, or an explanation of how he did that with the lines.

thank you again.

**Comment by ocornut** [comment]
Sorry but #1586
