### ISSUE TITLE
AddFontFromFileTTF: unresolved external

### ISSUE THREAD

**Issue by NoName1335** [ocornut/imgui#6795]
**Version/Branch of Dear ImGui:**

Version: 1.90 WIP (18991)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_vulkan.cpp + imgui_impl_glfw.cpp
Compiler: MSVC (Visual Studio 2022)
Operating System: Windows 10 Pro

**My Issue/Question:**

I recently switched from the docking branch to the master branch. Now, AddFontFromFileTTF throws an unresolved external. I am linking imgui.cpp, imgui_tables.cpp, imgui_widgets.cpp, imgui_demo.cpp and imgui_draw.cpp. AddFontDefault() works even though it's defined in the same file as AddFontFromFileTTF. AddFontFromMemoryTTF also throws an unresolved external f.e. I tried using IMGUI_API with my function but that didn't change anything. I am pretty certain that I'm linking everything correctly as it worked before switching branches and if I just use AddFontDefault everything works as it should.

**Standalone, minimal, complete and verifiable example:**

```cpp
// Init function
ImGuiIO& io = ImGui::GetIO();

static ImFontConfig cfg;
cfg.FontBuilderFlags |= ImGuiFreeTypeBuilderFlags_LoadColor;
m_Font = io.Fonts->AddFontFromFileTTF("fonts/seguiemj.ttf", 15, &cfg);

// DrawUi Function
ImGui::ShowDemoWindow();
```

**Comment by ocornut** [comment]
Given the description of your issue I believe there's an omission or a mistake being made on your side and you'll find it. Perhaps you have an issue with your build system setup.

**Comment by CoolFox29281819** [comment]
Make sure you have all of the files included that you need

Also ,
`ImFont* m_Font  = io.Fonts->AddFontFromFileTTF("D:\\directory\\font.ttf", 13.f)`

**Comment by Shpendicus** [comment]
> Make sure you have all of the files included that you need
> 
> Also , `ImFont* m_Font = io.Fonts->AddFontFromFileTTF("D:\\directory\\font.ttf", 13.f)`

Is it possible to load also .otf files or really ONLY .ttf files? cause i get the same exception when trying to load .otf files

**Comment by PathogenDavid** [comment]
@Shpendicus If you're getting an unresolved external, that's a linker error--not an exception. The format of your font would not a linker error.

As noted in [the fonts guide](https://github.com/ocornut/imgui/blob/001f102f3871a175a2b83b6ef99babab7d579a1d/docs/FONTS.md#fonts-loading-instructions), OTF fonts are supported.
