### ISSUE TITLE
how to draw and animate shapes on top of a window

### ISSUE THREAD

**Issue by CoolFox29281819** [ocornut/imgui#6796]
Backend: Direct X 9
Version: newest as of sept 7th

Hello,

So I want to make a remake of the application of the screenshot that I have attached.

I would like to have it be as close to exact as possible.

there is a rounded loading bar that goes from one side to another and I would like to learn how to do that, as well as a frame with a gradient as it’s border. Can you guys help me? Thanks

Why draw on top of a window? How else would I get the line (if there is a way please let me know and I’ll change the title)

**Comment by CoolFox29281819** [comment]
![CEC066E2-08D4-4A0F-B6C7-18486EEEA254](https://github.com/ocornut/imgui/assets/144345472/85437df2-f6f7-4865-b7a0-63d10a0b489b)

**Comment by ocornut** [comment]
This is a rather open ended question and your post suggests you don't have much experience nor a starting points so I'll provide some, but we can't hand-hold you through the process.

See: 

(1)
FAQ entry: https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-custom-shapes-using-low-level-imdrawlist-api

(2)
`Demo->Examples->Custom Rendering` demo.

(3)
Suggestions such as #4722 (this is going to be more difficult to achieve given your assumed experience with dear imgui)

(4)
Reference custom widgets that are mostly drawing nice shapes (e.g. imgui-knobs, imspinner)
https://github.com/ocornut/imgui/wiki/Useful-Extensions
