### ISSUE TITLE
Using Docking only for resizable sub-areas within a main window

### ISSUE THREAD

**Issue by vdweller84** [ocornut/imgui#6799]
Hello,

I am building an editor and, for some windows, I use child windows separated by "drag buttons" in order to resize them within the window, like so:

![image](https://github.com/ocornut/imgui/assets/96083791/da2b3ee2-637a-4035-9d7c-489d078c0580)

It works fine, but then I began wondering whether docking can be used for the same purpose. That is, create a set of pre-docked windows within a main window. The docked windows cannot be undocked/closed, only their borders resized. Those docked windows cannot themselves be dock targets for other windows.

This creates another question. Consider the following scenario:

![image](https://github.com/ocornut/imgui/assets/96083791/4e38bd76-d205-4d8f-bd44-fab286b52e3a)

Window A has inside it the docked windows B, C, D.
Window E has inside it the docked windows F, G.

As per the above rules, windows B, C, D can't be undocked/closed from within window A. Same for Windows F, G for window E. Only their borders can be resized. Now, is the following possible with the current state of the docking API:

- Window E and its contents can be docked inside window A (or undocked from it). It should not "split" the docked windows layout of window A, nor can it be docked inside windows B, C, D. Same for window A in regards to window E.

Let me know if there is functionality for this and if I have to elaborate more. If things are currently too messy/convoluted for such a scheme, I can always stay with my trusty drag buttons for each window!

**Comment by ocornut** [comment]
- You can submit a `DockSpace()` in A and E.

- You can then use the `ImGuiWindowClass::ClassId` facility to have your top-level window A and E share a window class so they can only be docked with each others. The code I shared in #6487 describe a full-fledged example of that but it's probable largely overkill/too complex for your needs. Just setting basic ClassId for your window would be enough in your case.

- Pre-docking B,C,D into A and F,G into E is going to require of the DockBuilderXXX api from imgui_internal.h, which is notorious for being not great (it's one thing I will tackle eventually).

- Preventing B,C,D and F,G from being undocked the simplest way is to set the `ImGuiWindowFlags_NoMove` flag.

I would suggest you may consider to drop the last two points in favor of letting user do it, but then you can also drop ALL those points, use zero api call and let end-user dock their stuff manually and freely, If you have few users of your app and don't absolutely need a default setting this might be the best plan. You can also ship code that "load" a default dock settings pulled from a copy of .ini data.

**Comment by vdweller84** [comment]
Thanks for the quick response @ocornut . I thought about using docked windows in order to arrange several sub-panels of a window (that make sense only within the context of that window, thus undocking is not really good in that case) in a more convenient way rather than creating "Drag Buttons" between child windows. While using other tricks can provide the same functionality, achieving it by the docking API itself should probably be considered in a positive light.

Alright. By digging around I managed to concoct something that seemingly works.

```
    void ShowTestDockWindow() {
        static ImGuiDockNodeFlags dockFlags = ImGuiDockNodeFlags_None | ImGuiDockNodeFlags_NoWindowMenuButton;
        static ImGuiID dockspaceID = 0;
        static ImGuiID leftID = 0;
        static ImGuiID rightID = 0;
        static ImGuiID leftTopID = 0;
        static ImGuiID leftBottomID = 0;

        static ImGuiWindowClass windowClass;
        
        ImGui::SetNextWindowSize(ImVec2(400, 300), ImGuiCond_Once);

        ImGui::Begin("Main");

        dockspaceID = ImGui::GetID("mainDock");

        if (!ImGui::DockBuilderGetNode(dockspaceID)) {
            ImGui::DockBuilderRemoveNode(dockspaceID);
            ImGui::DockBuilderAddNode(dockspaceID, ImGuiDockNodeFlags_DockSpace);

            ImVec2 r1 = ImGui::GetWindowContentRegionMin();
            ImVec2 r2 = ImGui::GetWindowContentRegionMax();
            ImGui::DockBuilderSetNodeSize(dockspaceID, ImVec2(r2.x - r1.x, r2.y - r1.y));
            ImGui::DockBuilderSplitNode(dockspaceID, ImGuiDir_Left, 0.3f, &leftID, &rightID);
            ImGui::DockBuilderSplitNode(leftID, ImGuiDir_Up, 0.6f, &leftTopID, &leftBottomID);

            // Dock windows to the resulting nodes
            ImGui::DockBuilderDockWindow("LeftTop", leftTopID);
            ImGui::DockBuilderDockWindow("LeftBottom", leftBottomID);
            ImGui::DockBuilderDockWindow("Right", rightID);

            ImGui::DockBuilderFinish(dockspaceID);
        }

        
        ImGui::DockSpace(dockspaceID, ImVec2(0, 0), dockFlags);

        windowClass.ClassId = dockspaceID;
        windowClass.DockingAllowUnclassed = false;
        windowClass.DockNodeFlagsOverrideSet = ImGuiDockNodeFlags_NoTabBar | ImGuiDockNodeFlags_NoWindowMenuButton;

        ImGui::End();

        ImGui::SetNextWindowClass(&windowClass);
        ImGui::SetNextWindowDockID(leftTopID);
        ImGui::Begin("##leftTop");
        //...
        ImGui::End();

        ImGui::SetNextWindowClass(&windowClass);
        ImGui::SetNextWindowDockID(leftBottomID);
        ImGui::Begin("##leftBottom");
        //...
        ImGui::End();

        ImGui::SetNextWindowClass(&windowClass);
        ImGui::SetNextWindowDockID(rightID);
        ImGui::Begin("##right");
        //...
        ImGui::End();

    }
```

Result:

![image](https://github.com/ocornut/imgui/assets/96083791/ceda7b11-732c-4265-8434-3e6053103269)

This seems to fulfill my requirements:

- Docked windows can only have their "borders" moved, they can't be undocked/closed.
- Other windows can be docked inside the "container" window but not inside the docked windows.

Let me know if I'm doing something dumb!
