### ISSUE TITLE
General styling questions

### ISSUE THREAD

**Issue by CoolFox29281819** [ocornut/imgui#6804]
hello pro imgui'ers

I have 2 questions about styling:

1: How can I have two text widgets with separate colors, sizing, etc... (different styling)

2: How can I add frames and make them different colors?

Example of frames:

(figma) https://imgur.com/a/wVdnQNT

Thanks!

(I am new to imgui if you couldnt tell please dont make fun of me xD)

(If there is an ImGui discord please lmk so I can ask simpler questions there instead of making big posts here)

**Comment by ocornut** [comment]
You can use PushStyleVar()/PopStyleVar() and PushStyleCol()/PopStyleCol() to alter style sizes and colors.
See demo for varied use of them.

If you have known styles you'll probably want to create your small helper functions to push multiple settings together.

**Comment by CoolFox29281819** [comment]
Thank you,

How can I change the text size? I don't see a style for it, I appear to only be able to change it when I load the font from memory/ttf file.

Thanks

**Comment by ocornut** [comment]
That’s correct. It’s not currently easy to change text size. You can load multiple fonts and switch between them, but it’s not possible to scale a font while preserving output quality.

**Comment by CoolFox29281819** [comment]
Ah, alright. Thank you!

hopefully it's added soon. i'll be watching the releases!

Thanks for all your help again.

**Comment by ocornut** [comment]
> hopefully it's added soon. i'll be watching the releases!

Not soon but I'm hoping it should happen before 2.00. It's been very much requested but requires quite some rework to be doable with the quality and performances I'd like to preserve.

Closing this now! Good luck!
