### ISSUE TITLE
Trying to render a circular image

### ISSUE THREAD

**Issue by tritonas00** [ocornut/imgui#6806]
Hi. As the title says im trying to render a circular image which is a mini survey map for a game (Rigs of Rods)

This is what i do:

```
ImDrawList* drawlist = ImGui::GetWindowDrawList();

ImVec2 p_min = ImGui::GetCursorScreenPos();
ImVec2 p_max = ImVec2(p_min.x + view_size.x, p_min.y + view_size.y);

drawlist->AddImageRounded(reinterpret_cast<ImTextureID>(tex->getHandle()), p_min, p_max, ImVec2(0, 0), ImVec2(1, 1), ImGui::GetColorU32(ImVec4(1,1,1,1)), view_size.x * 0.5);
```

which produces:

![screenshot_2023-09-11_16-33-43_1](https://github.com/ocornut/imgui/assets/2660424/0842ae8e-7a13-4356-a66e-068c61358117)

Any idea how to make it a full smooth circle? Thanks.

We use dear imgui, v1.73.

**Comment by ocornut** [comment]
> Any idea how to make it a full smooth circle? Thanks.
> We use dear imgui, v1.73.

Yes, you need to update. 1.73 is extremely old and this has been changed since then.

**Comment by GamingMinds-DanielC** [comment]
If you can't update, make your own function for drawing. In the current version that would be something like pushing the texture id first, then drawing a filled ellipse, then popping the texture id again. I don't know what is and isn't available in the old version, but you have the sources right there. Copy the function that doesn't work for you and fix the problematic part in your copy.

**Comment by ocornut** [comment]
It's going to be easier to update, and is always recommended.

The exact change involved to "fix" this is non-trivial, but you can rewrite the function using `PushTextureID()`+`AddCircleFilled()`+`ShadeVertsLinearUV()`+`PopTextureID()`.

**Comment by tritonas00** [comment]
Worked:

![screenshot_2023-09-11_19-36-08_1](https://github.com/ocornut/imgui/assets/2660424/5c17a660-2f61-4ffc-b0fb-cc46e14260ae)

Thanks!
