### ISSUE TITLE
The way to prevent scalar input chars filtering

### ISSUE THREAD

**Issue by Grantim** [ocornut/imgui#6810]
Is there a way to prevent alphabet characters filtering in input/drag scalar?

I find out that there is 
https://github.com/ocornut/imgui/blob/6eb2681c0988d8ccd82be5f0a6581a0e577bea86/imgui_widgets.cpp#L3390-L3396
function, that is forced here:
https://github.com/ocornut/imgui/blob/6eb2681c0988d8ccd82be5f0a6581a0e577bea86/imgui_widgets.cpp#L3415
and here:
https://github.com/ocornut/imgui/blob/6eb2681c0988d8ccd82be5f0a6581a0e577bea86/imgui_widgets.cpp#L3460-L3461

one way to hack this behaviour is to define custom function in `IMGUI_USER_CONFIG` like this:
```c++
typedef int ImGuiInputTextFlags;
typedef int ImGuiDataType;
namespace ImGui
{
static inline ImGuiInputTextFlags InputScalar_DefaultCharsFilter( ImGuiDataType, const char* )
{
    return 0;
}
}
```

so it is used before original one is found. 

Is there a native way to it?

**Comment by ocornut** [comment]
> Is there a way to prevent alphabet characters filtering in input/drag scalar?

Could you explain why would you want to do that ?

**Comment by Grantim** [comment]
We think of it like a possible option for better UX

**Comment by ocornut** [comment]
You are not answering the question.
Why do you want to input eg arbitrary alphabetical letter in a scalar input field? Why not using InputText() ?

**Comment by Grantim** [comment]
I want it to have drag behaviour and to have numerical argiments, but also I want it not to "ignore" user writing alphabet symbols (accidentaly or specialy)

**Comment by ocornut** [comment]
You are not answering the question which is WHY do you want that?

What do you expect to happen with the DragFloat() when text character are entered, value set to 0.0f ?
Pressing Enter would entirely lose the textual content.

**Comment by Grantim** [comment]
I think it should hold last valid value, at least with the hack I use it works this way, it would be nice to have ability to check explicitly if input is valid or not

**Comment by ocornut** [comment]
You have not answered the question yet. I would appreciate if you did, at least if you expect an answer.

**Comment by Grantim** [comment]
Our users complain that our Dear ImGui based application behaves not like other applications in numeric edit boxes. When they by mistake enter not digits (e.g. due to special language settings on their keybords), nothing appears on the screen, and it looks to them that the appliation does not respond at all. That is why we want to show all entered text in numeric edit fields even if it is invalid

**Comment by ocornut** [comment]
Thank you. I understand better. 
Will need to think about this and ask some users. It should be doable to provide a global setting for that but it also seems interesting to reconsider the current behavior completely.

**Comment by ocornut** [comment]
Did some soul searching and applied this change now :)
(This will also allow #7096)

**Comment by Grantim** [comment]
Thanks!

**Comment by Guillaume227** [comment]
I have also been coincidentally looking for a similar feature, so that change is very timely, thanks! 

My motivation is that I want users to be able to enter NAN or INF which filtering on chars prevents. 

I happen to be on the docking branch where those changes are not present yet. 
So I have two questions @ocornut : 
1. what is the sync schedule between master and docking?
2. docking has been around for a long time - is it still a feature branch that is meant to be merged to master at some point or is it going to live a separate life indefinitely (I did search but haven't been able to find that information in readme material)?

**Comment by ocornut** [comment]
> what is the sync schedule between master and docking?

Roughly every week or two weeks, depending on commits contents.

> s it still a feature branch that is meant to be merged to master at some point or is it going to live a separate life indefinitely (I did search but haven't been able to find that information in readme material)?

I am not happy with the code quality so I aim to rewrite it a third time first, see https://github.com/ocornut/imgui/wiki/Docking#why-is-not-merged-to-master

One of the reason for building the imgui test suite (https://github.com/ocornut/imgui_test_engine) was to get more coverage of docking features to facilitate the rewrite. Code is imho too brittle currently.
