### ISSUE TITLE
How to render a pool of textures with ImGui::Image

### ISSUE THREAD

**Issue by wecand0** [ocornut/imgui#6813]
I use opengl3+glfw+linux. I want to render some scene that is stored in a pool of textures( `std::vector<GLuint> texturePool`).
Is it possible to render not only one(1) texture like it is in here [https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#example-for-opengl-users](url) in ImGui window?

**Comment by ocornut** [comment]
Yes... Just pass the texture ID you want in `Image()` call...
