### ISSUE TITLE
Splitting DockBuilderGetCentralNode into 2 different regions

### ISSUE THREAD

**Issue by Osmanyasal** [ocornut/imgui#6815]
Hello, I'm a newbie in Imgui so if my question is a bit silly please forgive me.
I'm using the docking branch with OpenGL backend, I can successfully display my framebuffer in the central node, however when I want to divide that into two nodes ( one for OpenGL context on the left and some scene information on the right ) I get errors and couldn't what to do. Here's my code
`

    uint32_t ImguiLayer_glfw_opengl_impl::create_dockspace()
    {
        uint32_t dockspace_id = ImGui::DockSpaceOverViewport(ImGui::GetMainViewport());
        return dockspace_id;
    }
    void ImguiLayer_glfw_opengl_impl::create_default_layout(uint32_t layout_id)
    {
        uint32_t dockspace_id = create_dockspace();
        create_menu();

        // Retrieve the dockspace's node ID
        ImGuiDockNode *dockspace_node_id = ImGui::DockBuilderGetCentralNode(dockspace_id);
        if (dockspace_node_id->ID)
        {
            // Split the central node to create a new window on the right
            ImGuiID left_node_id;
            ImGuiID right_node_id;

            // Split an existing node to the left with a 70/30 ratio
            ImGui::DockBuilderSplitNode(dockspace_node_id->ID, ImGuiDir_Left, 0.7f, &left_node_id, &right_node_id);

            // Dock the "Scene" window into the left node
            ImGui::DockBuilderDockWindow("Scene", left_node_id);
            ImGui::DockBuilderDockWindow("Right Window", right_node_id);
            ImGui::DockBuilderFinish(dockspace_id);

            if (ImGui::Begin("Scene"))
            {
                const float window_width = ImGui::GetContentRegionAvail().x;
                const float window_height = ImGui::GetContentRegionAvail().y;

                fb->rescale_framebuffer(window_width, window_height);
                glViewport(0, 0, window_width, window_height);

                ImVec2 pos = ImGui::GetCursorScreenPos();
                ImGui::GetWindowDrawList()->AddImage(
                    (void *)fb->texture.meta.texture_id,
                    ImVec2(pos.x, pos.y),
                    ImVec2(pos.x + window_width, pos.y + window_height),
                    ImVec2(0, 1),
                    ImVec2(1, 0));
                ImGui::End(); // End the "Scene" window
            }
            // Dock the "Right Window" into the right node
            if (ImGui::Begin("Right Window"))
            {
                ImGui::Text("Inspector comes here!");

                ImGui::End(); // End the "Right Window"
            }
        }
    }
`

Here's the output
```
recursion.engine: imgui.cpp:9897: void ImGui::ErrorCheckEndFrameSanityChecks(): Assertion `(g.CurrentWindowStack.Size == 1) && "Mismatched Begin/BeginChild vs End/EndChild calls: did you forget to call End/EndChild?"' failed.
make: *** [Makefile:172: run] Aborted (core dumped)
```

**Comment by GamingMinds-DanielC** [comment]
The error tells you that you have mismatching `Begin()`/`End()` calls. If you look up these functions in the header file (that's where they are documented), you will find this: "Always call a matching End() for each Begin() call, regardless of its return value!"

**Comment by Osmanyasal** [comment]
Yes, I know this error however I didn't miss any end calls, in the code, If you comment out the DockBuilderSplitNode and draw the "Scene" to the dockspace_id, it works.

**Comment by GamingMinds-DanielC** [comment]
You missed the "regardless of its return value" part.

Wrong:
```c++
    if ( ImGui::Begin( "..." ) )
    {
        // window content
        ImGui::End();
    }
```

Correct:
```c++
    if ( ImGui::Begin( "..." ) )
    {
        // window content
    }
    ImGui::End();
```

**Comment by Osmanyasal** [comment]
That worked. this time I cannot see the content of the windows, and the split ratios are a bit odd.

![image](https://github.com/ocornut/imgui/assets/22853419/f9c6edc0-1691-4860-b4c7-1d253ccaf858)

here's my updated code (I did what you said) 

`
        uint32_t dockspace_id = create_dockspace();
        create_menu();

        // Retrieve the dockspace's node ID
        // Use DockBuilderSplitNode to create a simple layout
        ImGuiDockNode *dockspace_node_id = ImGui::DockBuilderGetCentralNode(dockspace_id);
        ImGuiID left_node_id;
        ImGuiID right_node_id;
        ImGui::DockBuilderSplitNode(dockspace_node_id->ID, ImGuiDir_Left, 0.7f, &left_node_id, &right_node_id);
        ImGui::DockBuilderDockWindow("Scene", left_node_id);
        ImGui::DockBuilderDockWindow("Right Window", right_node_id);
        ImGui::DockBuilderFinish(dockspace_node_id->ID);

        // Start the "Scene" window
        if (ImGui::Begin("Scene"))
        {
            const float window_width = ImGui::GetContentRegionAvail().x;
            const float window_height = ImGui::GetContentRegionAvail().y;

            fb->rescale_framebuffer(window_width, window_height);
            glViewport(0, 0, window_width, window_height);

            ImVec2 pos = ImGui::GetCursorScreenPos();
            ImGui::GetWindowDrawList()->AddImage(
                (void *)fb->texture.meta.texture_id,
                ImVec2(pos.x, pos.y),
                ImVec2(pos.x + window_width, pos.y + window_height),
                ImVec2(0, 1),
                ImVec2(1, 0));
        }
        ImGui::End();

        // Start the "Right Window"
        if (ImGui::Begin("Right Window"))
        {
            // ImGui::Text("Inspector comes here!");
        }
        ImGui::End();`

**Comment by Osmanyasal** [comment]
Okay after checking [this](https://github.com/ocornut/imgui/issues/6217) out, the following modification fixed my second issue 
``` 
        static bool sFirstFrame = true;
        if (sFirstFrame)
        {
            sFirstFrame = false;
            ImGuiDockNode *dockspace_node_id = ImGui::DockBuilderGetCentralNode(dockspace_id);
            ImGuiID left_node_id;
            ImGuiID right_node_id;
            ImGui::DockBuilderSplitNode(dockspace_node_id->ID, ImGuiDir_Left, 0.7f, &left_node_id, &right_node_id);
            ImGui::DockBuilderDockWindow("Scene", left_node_id);
            ImGui::DockBuilderDockWindow("Right Window", right_node_id);
            ImGui::DockBuilderFinish(dockspace_node_id->ID);
        }
```

![image](https://github.com/ocornut/imgui/assets/22853419/9ae1a2b1-8805-4523-883b-8299700e9cfb)
