### ISSUE TITLE
Optimization of table cells

### ISSUE THREAD

**Issue by Kolhun** [ocornut/imgui#6817]
Hello everyone, there was a question about optimizing large lists, of course I looked at the demo gui, but there is only text information, which, as I understand it, is glued into one line, but how to make such an option for tables?

**Comment by ocornut** [comment]
> but there is only text information, which, as I understand it, is glued into one line

I don't understand what this means.

The `Demo->Tables & Columns->Vertical Scrolling, with Clipping` section showcase how to use `ImGuiListClipper` in order to optimize for large lists.
