### ISSUE TITLE
ImGuiPushStyle is assertion-prone

### ISSUE THREAD

**Issue by aparks5** [ocornut/imgui#6818]
IMO it should not be the end-user's responsibility to individually count and track items on the global style stack and figure out the style scope. It is extremely frustrating to debug in a large UI with different styles and PopStyleColor() also prohibits popping all items off the style stack recursively.

Some suggestions:
- Style could be scoped instead of using a style stack
- PopStyleColor could have a related method to pop all style items off the stack
- ImGui::End() could pop all items off the style stack

**Comment by GamingMinds-DanielC** [comment]
`PopStyleColor()` and `PopStyleVar()` already have a `count` parameter that pops multiple entries off at once, no need to pop them individually. As to who is responsible for popping those values: whoever pushes them. Unless your code is overly convoluted, there should be no need to "track" those values. Push them as needed, submit your items, pop the values again.

If you need it to be scoped, that should be easy enough to implement without altering ImGui sources. Make a class to wrap pushes (and pops for finer control) and update counters accordingly, pop the remaining items in the destructor that gets called automatically when the instance goes out of scope.

**Comment by aparks5** [comment]
Thanks for the clarification @GamingMinds-DanielC, closing

**Comment by ocornut** [comment]
Some people want to use RAII style syntax.
See "imgui_scoped", "imgui_sugar" and "imguiwrap" here:
https://github.com/ocornut/imgui/wiki/Useful-Extensions#cness

However note that there are distinct stacks, and sometimes this type of patterns is useful in dear imgui:

```cpp
ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ....);
ImGui::Begin(...);
ImGui::PopStyleVar();

// window code
ImGui::End(...);
```

Most RAII wrappers make this not possible, and therefore you would tend to forget that it is possible and can be useful.
It's mostly good to _remember_ that _you can_ do that if you need.
Of course you can mix using a RAII wrapper for 90% cases and use Push/Pop in occasion where this is desired.
