### ISSUE TITLE
How can I hide central node in docking layout ?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#6821]
**Version/Branch of Dear ImGui:**

Version: 1.89
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_OpenGL3.cpp + imgui_impl_SDL2.cpp
Compiler: vs2019 msvc
Operating System: windows 11

**My Issue/Question:**

I want to hide central node in docking layout. I remember there was a IMGUI_DOCK_FLAGS_NO_CENTRAL_NODE enum before, but it's missed now. How can I hide it using latest api? Thanks.

![image](https://github.com/ocornut/imgui/assets/48938612/b9e07ef9-8f09-4b9c-a32e-d8499e2d56bf)

![image](https://github.com/ocornut/imgui/assets/48938612/26f8bf67-63dc-4eab-9d3a-9c0f9c22ec02)

**Comment by ocornut** [comment]
If the node is created with `DockBuilderAddNode()` you should not pass the `ImGuiDockNodeFlags_DockSpace` flag the first time you create it. Sorry it is confusingly named, this has been a common issue to correct.

**Comment by GamingMinds-DanielC** [comment]
If you don't specify `ImGuiDockNodeFlags_NoDockingInCentralNode` and `ImGuiDockNodeFlags_PassthruCentralNode`, you should be able to use the central node like any normal node. So if you just dock windows into the central node, it should be central only as a formality, same effect as if you didn't have one.

**Comment by ocornut** [comment]
Note that Central Node has different sizing behavior as normal node, as it always use "remaining size" rather than preserving its size.

**Comment by ChivenZhang** [comment]
The reason why I hide central node is that I need all dock widgets to be no-central node which would share same ratio when maximum the whole window.

**Comment by ChivenZhang** [comment]
If I place any widget in the central node, it would not keep its size radio when resizing the window. So the question is how to keep the resize ratio among all dock widgets ?

**Comment by ChivenZhang** [comment]
> Note that Central Node has different sizing behavior as normal node, as it always use "remaining size" rather than preserving its size.

I think It's more natual for no-central node to use remaining size when there's no central node. It just my personal advice that from the experience of using Qt's QMainWindow and QDockWidget.

**Comment by ocornut** [comment]
I answered your question. When you create the node don't use the `ImGuiDockNodeFlags_DockSpace` flag you will have no central node. You may need to delete/clean your .ini data from past data.

**Comment by ChivenZhang** [comment]
I don't create node by dock builder, I just drag dock widget to dock layout and save its layout. Can it be possible to cancel the central area when dragging docking window ?
![image](https://github.com/ocornut/imgui/assets/48938612/a6e469e4-9a4b-443b-b0ca-fbbae0f430dd)

**Comment by ocornut** [comment]
Where are you dragging into? an already created window or a dockspace?

**Comment by ChivenZhang** [comment]
> Where are you dragging into? an already created window or a dockspace?
It's into dockspace.

**Comment by ocornut** [comment]
Hello, any reason for closing those 3 issues simultaneously?
Thanks.

**Comment by ChivenZhang** [comment]
Sorry for delaied reply. This is a project of my last company and it was done few month ago. But the dock
 problem is still exist if there is no central dock node. I think
 it's better to fill remaining space by side docks if there is no central one. Thanks a lot for the helps you'v given.
