### ISSUE TITLE
ConfigDockingWithShift for undocking

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#6823]
Version/Branch of Dear ImGui:

Version: 1.89
Branch: docking

Back-end/Renderer/Compiler/OS

cimgui
Back-ends: imgui_impl_OpenGL3.cpp + imgui_impl_glfw.cpp
Compiler : gcc
Operating System: windows 10

My Issue/Question:

When ConfigDockingWithShift is set to true, pressing shift is necessary for docking but not for undocking.

**Comment by ocornut** [comment]
Hello Victor,
This is as designed. The purpose of the option is to reduce visual clutter when moving windows around, but I don't see a point preventing a move/undock. Why do you think it would be desirable?

**Comment by sonoro1234** [comment]
https://github.com/ocornut/imgui/blob/72dbe45adce69bc180d7682aa2df125994e2e77f/imgui.h#L824

Seems to say this: you instead need to hold SHIFT to _enable_ docking/undocking.
The reason would be to lock docking.

**Comment by ocornut** [comment]
I have now added a `ImGuiDockNodeFlags_NoUndocking` flag which may be used on e.g. a DockSpace() or a programmatically created node to lock its content.
Moving the rest of this conversation to #6780
