### ISSUE TITLE
How to create sub menu-bars under BeginMainMenuBar?

### ISSUE THREAD

**Issue by Osmanyasal** [ocornut/imgui#6824]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: docking

Back-ends: imgui_impl_opengl.cpp + imgui_impl_glfw.cpp _(or specify if using a custom engine/back-end)_
Compiler: GCC / C++11 
Operating System: Linux / Ubuntu 

**I wanna add sub-menubars below BeginMainMenuBar()** 

I want to put start-stop-pause buttons in an area right below the "file view...." menubar but I cannot create any other menubars
![Untitled](https://github.com/ocornut/imgui/assets/22853419/a67d5781-1429-4ec6-aa0f-6bd3558f7674)

``` 
    void ImguiLayer_glfw_opengl_impl::create_menu()
    {
        static float original_padding = ImGui::GetStyle().FramePadding.y;
        ImGui::GetStyle().FramePadding.y = 30;
        if (ImGui::BeginMainMenuBar())
        {
            create_menu_icon();
            create_menu_file();
            create_menu_edit();
            create_menu_window();
            create_menu_tools();
            create_menu_build();
            create_menu_select();
            create_menu_actor();
            create_menu_help(); 
        }
        ImGui::GetStyle().FramePadding.y = original_padding;
        ImGui::EndMainMenuBar();
    }
    
    void ImguiLayer_glfw_opengl_impl::create_default_layout(uint32_t layout_id)
    {
        uint32_t dockspace_id = create_dockspace();
        create_menu();

        // Retrieve the dockspace's node ID
        // Use DockBuilderSplitNode to create a simple layout

        static bool sFirstFrame = true;
        if (sFirstFrame)
        {
            sFirstFrame = false;
            ImGuiDockNode *dockspace_node_id = ImGui::DockBuilderGetCentralNode(dockspace_id);
            ImGuiID scene_node_id;
            ImGuiID inspector_node_id;
            ImGuiID game_object_node_id;
            ImGuiID log_node_id;
            ImGui::DockBuilderSplitNode(dockspace_node_id->ID, ImGuiDir_Right, 0.25f, &inspector_node_id, &scene_node_id);
            ImGui::DockBuilderSplitNode(scene_node_id, ImGuiDir_Down, 0.40f, &log_node_id, &scene_node_id);
            ImGui::DockBuilderSplitNode(scene_node_id, ImGuiDir_Left, 0.25f, &game_object_node_id, &scene_node_id);
            ImGui::DockBuilderDockWindow("Scene", scene_node_id);
            ImGui::DockBuilderDockWindow("Inspector Window", inspector_node_id);
            ImGui::DockBuilderDockWindow("Object Window", game_object_node_id);
            ImGui::DockBuilderDockWindow("Log Window", log_node_id);
            ImGui::DockBuilderDockWindow("Project Window", log_node_id);
            ImGui::DockBuilderFinish(dockspace_node_id->ID);
        }
        // Start the "Scene" window
        if (ImGui::Begin("Scene"))
        { 
        }
        ImGui::End();

        // Start the "Right Window"
        if (ImGui::Begin("Inspector Window"))
        {
            ImGui::Text("Inspector comes here!");
        }
        ImGui::End();

        if (ImGui::Begin("Object Window"))
        {
            ImGui::Text("Objects comes here!");
        }
        ImGui::End();

        if (ImGui::Begin("Project Window"))
        {
        }
        ImGui::End();

        if (ImGui::Begin("Log Window"))
        { 
        }
        ImGui::End();
     } 

```

**Comment by ocornut** [comment]
It's unclear if you want your button to be part of the three tab bars under.

(1)
You can append to the tab-bar of a docking node `DockNodeBeginAmendTabBar()/DockNodeEndAmendTabBar()` (`imgui_internal.h`) then add buttons using `TabItemButton()` but I am not sure this is what you want.

(2)
You can have individual windows have their own tab-bar, e.g. 
```cpp
if (ImGui::Begin("Scene", NULL, ImGuiWindowFlags_MenuBar))
{ 
   if (ImGui::BeginMenuBar())
   { 
      ....
```

(3)
Otherwise you can manually create an unmovable windows and add menu items inside it... separated by SameLine().
Maybe in create_dockspace() simply submit your buttons/items in one long, THEN after you can call DockSpace() so the DockSpace() is below that line of items.


PS:
Your EndMainMenuBar() is misplaced:
```cpp
if (ImGui::BeginMainMenuBar())
{
    ...
}
ImGui::EndMainMenuBar();
```
Should be:
```
if (ImGui::BeginMainMenuBar())
{
    ...
    ImGui::EndMainMenuBar();
}
```

**Comment by Osmanyasal** [comment]
Hello, 
What I want is to create another menu-like bar that will be placed right below my "file edit.." bar just like it but this time I'm gonna place the start/stop buttons at the center of it. you can consider the unity editor below that's what I want.
This could either be an extension like you talked about `DockNodeBeginAmendTabBar` or its imgui version. 

ps: I tried `DockNodeBeginAmendTabBar` but I probably misplaced, I'm totally new to imgui if you show me where to place I'd be very happy.

Thanks in advance.

![Untitled](https://github.com/ocornut/imgui/assets/22853419/e1302f5b-7216-4338-af22-f070dbeb8e67)

**Comment by ocornut** [comment]
You should go for solution 3. Create your content in your main window before submitting the dockspace.

If you temporarily set `window->DC.LayoutType = ImGuiLayoutType_Horizontal;` and restore to vertical after submitting you can avoid using `SameLine()` between items.

**Comment by Osmanyasal** [comment]
Indeed,
I split the upper side of the window like I created other panels, It's working now however do you have any idea how to remove the following red marked parts?
![Untitled](https://github.com/ocornut/imgui/assets/22853419/c3131058-c990-4883-83e2-e747aa503c5b)

The one with the arrow and light gray line placed above the buttons

I want it to look like the following
![image](https://github.com/ocornut/imgui/assets/22853419/1602eb0e-ca44-4927-9a13-e9e64617999f)

here's my updated code

` static bool sFirstFrame = true;
        if (sFirstFrame)
        {
            sFirstFrame = false;
            ImGuiID toolbar_node_id;
            ImGuiID scene_node_id;
            ImGuiID inspector_node_id;
            ImGuiID game_object_node_id;
            ImGuiID log_node_id;
            ImGui::DockBuilderSplitNode(dockspace_node_id->ID, ImGuiDir_Up, 0.10f, &toolbar_node_id, &scene_node_id);
            ImGui::DockBuilderSplitNode(scene_node_id, ImGuiDir_Right, 0.25f, &inspector_node_id, &scene_node_id);
            ImGui::DockBuilderSplitNode(scene_node_id, ImGuiDir_Down, 0.35f, &log_node_id, &scene_node_id);
            ImGui::DockBuilderSplitNode(scene_node_id, ImGuiDir_Left, 0.25f, &game_object_node_id, &scene_node_id);
            ImGui::DockBuilderDockWindow("###toolbar", toolbar_node_id);
            ImGui::DockBuilderDockWindow("Scene", scene_node_id);
            ImGui::DockBuilderDockWindow("Inspector Window", inspector_node_id);
            ImGui::DockBuilderDockWindow("Object Window", game_object_node_id);
            ImGui::DockBuilderDockWindow("Log Window", log_node_id);
            ImGui::DockBuilderDockWindow("Project Window", log_node_id);
            ImGui::DockBuilderFinish(dockspace_node_id->ID);
        }

        if (ImGui::Begin("###toolbar", nullptr, ImGuiWindowFlags_NoDecoration | 
                                                ImGuiWindowFlags_NoMove | 
                                                ImGuiWindowFlags_Tooltip | 
                                                ImGuiWindowFlags_NoScrollbar | 
                                                ImGuiWindowFlags_NoScrollWithMouse))
        {
            ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(0, 2));
            ImGui::PushStyleVar(ImGuiStyleVar_ItemInnerSpacing, ImVec2(0, 0));
            ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0, 0, 0, 0));
            auto &colors = ImGui::GetStyle().Colors;
            const auto &buttonHovered = colors[ImGuiCol_ButtonHovered];
            ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(buttonHovered.x, buttonHovered.y, buttonHovered.z, 0.5f));
            const auto &buttonActive = colors[ImGuiCol_ButtonActive];
            ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(buttonActive.x, buttonActive.y, buttonActive.z, 0.5f));

            ImVec4 tintColor = ImVec4(1, 1, 1, 1);

            float size = 35.0f;
            ImGui::SetCursorPosX((ImGui::GetWindowContentRegionMax().x * 0.5f) - (size * 0.5f));

            static opengl::render::OpenGLTexture play_btn{"../icon/editor/PlayButton.png"};
            if (ImGui::ImageButton((ImTextureID)(uint64_t)play_btn.meta.texture_id, ImVec2(size, size), ImVec2(0, 0), ImVec2(1, 1), 0, ImVec4(0.0f, 0.0f, 0.0f, 0.0f), tintColor))
            {
            }

            ImGui::SameLine();
            static opengl::render::OpenGLTexture pause_btn{"../icon/editor/PauseButton.png"};
            if (ImGui::ImageButton((ImTextureID)(uint64_t)pause_btn.meta.texture_id, ImVec2(size, size), ImVec2(0, 0), ImVec2(1, 1), 0, ImVec4(0.0f, 0.0f, 0.0f, 0.0f), tintColor))
            {
            }
            ImGui::SameLine();
            static opengl::render::OpenGLTexture stop_btn{"../icon/editor/StopButton.png"};
            if (ImGui::ImageButton((ImTextureID)(uint64_t)stop_btn.meta.texture_id, ImVec2(size, size), ImVec2(0, 0), ImVec2(1, 1), 0, ImVec4(0.0f, 0.0f, 0.0f, 0.0f), tintColor))
            {
            }

            ImGui::PopStyleVar(2);
            ImGui::PopStyleColor(3);
        }
        ImGui::End();
`

**Comment by Osmanyasal** [comment]
adding following after `ImGui::DockBuilderFinish(dockspace_node_id->ID);` resolved the issue.

``` 
            ImGuiDockNode* toolbar_node = ImGui::DockBuilderGetNode(toolbar_node_id);
            toolbar_node->LocalFlags |=  ImGuiDockNodeFlags_NoTabBar;
```

**Comment by ocornut** [comment]
That's one way to solve the issue but you didn't do as I suggested and created additional docking nodes.

What I said was, instead of creating your dockspace like that:

```cpp
ImGui::Begin("##YourDockspaceHost", NULL, ImGuiWindowFlags_NoDecoration | ...);
ImGui::DockSpace();
ImGui::End();
```

Well simply use that window to add your buttons:

```cpp
ImGui::Begin("##YourDockspaceHost", NULL, ImGuiWindowFlags_NoDecoration | ...);
// Add your button here, draw some stuff, background, separator etc..
ImGui::DockSpace(); // Use remaining space.
ImGui::End();
```
