### ISSUE TITLE
Opengl framebuffer shows up black in imgui image 

### ISSUE THREAD

**Issue by Darius000** [ocornut/imgui#6832]
Version : latest
Branch : docking

When trying to render a framebuffer image it shows up black or doesn't show at all, tried it with a regular texture and it displays just fine and don't know why it does, before in earlier version I can use it but now no, I also can submit the framebuffer color attachment id to a shader and it displays correctly. I included the framebuffer class I am using. The id type used is uint32_t

	`namespace Utils
	{
		static GLenum TextureTarget(bool multisampled)
		{
			return multisampled ? GL_TEXTURE_2D_MULTISAMPLE : GL_TEXTURE_2D;
		}

		static bool IsDepthFormat(TextureFormat format)
		{
			switch (format)
			{
			case TextureFormat::Depth: return true;
			}

			return false;
		}

		static void CreateTexture(bool multisampled, uint32_t* texture, size_t count)
		{
			glCreateTextures(TextureTarget(multisampled), (GLsizei)count, texture);
		}

		static void BindTexture(bool multisampled, uint32_t texture)
		{
			glBindTexture(TextureTarget(multisampled), texture);
		}

		static void AttachTexture(uint32_t texture, uint32_t samples, TextureFormat format, GLenum attachmentType, uint32_t width, uint32_t height)
		{
			bool multisampled = samples > 1;
			auto internal_format = Utilities::TextureFormatToInternalGL(format);
			auto _format = Utilities::TextureFormatToGL(format);

			if (multisampled)
			{
				glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, samples, internal_format, width, height, GL_FALSE);
			}
			else
			{
				if (format != TextureFormat::Depth)
				{
					glTexImage2D(GL_TEXTURE_2D, 0, internal_format, width, height, 0, _format, GL_UNSIGNED_BYTE, nullptr);
				}
				else
				{
					glTexStorage2D(GL_TEXTURE_2D, 1, _format, width, height);
				}
				

				glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
				glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
				glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
				glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
				glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);

			}

			glFramebufferTexture2D(GL_FRAMEBUFFER, attachmentType, TextureTarget(multisampled), texture, 0);
		}
	}

	OpenglFramebuffer::OpenglFramebuffer(const FramebufferSpecification& spec)
		:m_RendererID(-1), m_DepthAttachment(-1), m_Specification(spec)
	{
		for (auto& attachment : spec.m_Attachments.m_Attachments)
		{
			if (Utils::IsDepthFormat(attachment.m_TextureFormat))
			{
				m_DepthAttachmentSpecification = attachment;
			}
			else
			{
				m_ColorAttachmentSpecifications.push_back(attachment);
			}
		}

		Invalidate();
	}

	OpenglFramebuffer::~OpenglFramebuffer()
	{
		Delete();
	}

	void OpenglFramebuffer::Bind()
	{
		glBindFramebuffer(GL_FRAMEBUFFER, m_RendererID);
		glViewport(0, 0, m_Specification.m_Width, m_Specification.m_Height);
	}

	void OpenglFramebuffer::UnBind()
	{
		glBindFramebuffer(GL_FRAMEBUFFER, 0);
	}

	void OpenglFramebuffer::Invalidate()
	{
		if (m_RendererID)
		{
			Delete();

			m_ColorAttachments.clear();
			m_DepthAttachment = 0;
		}

		glCreateFramebuffers(1, &m_RendererID);
		glBindFramebuffer(GL_FRAMEBUFFER, m_RendererID);

		bool multisampled = m_Specification.m_Samples > 1;

		if (m_ColorAttachmentSpecifications.size())
		{
			m_ColorAttachments.resize(m_ColorAttachmentSpecifications.size());
			Utils::CreateTexture(multisampled, m_ColorAttachments.data(), m_ColorAttachments.size());

			for (size_t i = 0; i < m_ColorAttachments.size(); i++)
			{
				auto& specs = m_ColorAttachmentSpecifications[i];
				Utils::BindTexture(multisampled, m_ColorAttachments[i]);
				Utils::AttachTexture(m_ColorAttachments[i], m_Specification.m_Samples, specs.m_TextureFormat, GL_COLOR_ATTACHMENT0 + (int)i,
					m_Specification.m_Width, m_Specification.m_Height);
			}
		}
		

		if (m_DepthAttachmentSpecification.m_TextureFormat != TextureFormat::None)
		{
			Utils::CreateTexture(multisampled , &m_DepthAttachment, 1);
			Utils::BindTexture(multisampled, m_DepthAttachment);
			Utils::AttachTexture(m_DepthAttachment, m_Specification.m_Samples, m_DepthAttachmentSpecification.m_TextureFormat, GL_DEPTH_STENCIL_ATTACHMENT,
				m_Specification.m_Width, m_Specification.m_Height);
		}

		if (m_ColorAttachments.size() > 1)
		{
			BH_CORE_ASSERT(m_ColorAttachments.size());
			std::vector<GLenum> buffers;

			for (size_t i = 0; i < m_ColorAttachments.size(); i++)
			{
				buffers.push_back(GL_COLOR_ATTACHMENT0 + (int)i);
			}

			glDrawBuffers((GLsizei)buffers.size(), buffers.data());
		}
		else if(m_ColorAttachments.empty())
		{
			//only depth-pass
			glDrawBuffer(GL_NONE);
		}

		if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
		{
			BH_CORE_ERROR("Failed to create framebuffer!");
		}

		glBindFramebuffer(GL_FRAMEBUFFER, 0);
	}
`
framebuffer usage as texture
`

		ImGui::Begin("Viewport");

		auto viewport_image = m_FinalFramebuffer->GetColorAttachmentRendererID();
		auto viewportsize = ImGui::GetContentRegionAvail();
		m_ViewportSize = { viewportsize.x, viewportsize.y };

		ImGui::Image((ImTextureID)(viewport_image), {m_ViewportSize.x, m_ViewportSize.y}, ImVec2{ 0, 1 }, ImVec2(1, 0));

		ImGui::End();
`

**Comment by ocornut** [comment]
Hello,
This is entirely an OpenGL issue. Please use a GPU debugger such as RenderDoc to find the cause, or ask this question on a suitable forum. We unfortunately cannot be providing OpenGL support here.
