### ISSUE TITLE
Undefined reference to 'ImGui::CreateContext'

### ISSUE THREAD

**Issue by Bekobii** [ocornut/imgui#6834]
### Discussed in https://github.com/ocornut/imgui/discussions/6833

<div type='discussions-op-text'>

<sup>Originally posted by **Bekobii** September 18, 2023</sup>
Hey,

I've been installing ImGUI via VCPKG and always get the same error as stated in the title. 

`undefined reference to ImGui::Begin(char const*, bool*, int)`

This is how I import it via CMake.

```
find_package(glfw3 CONFIG REQUIRED)
find_package(imgui CONFIG REQUIRED)
target_link_libraries(TestApp PRIVATE glfw)
target_link_libraries(TestApp PRIVATE imgui::imgui)
```

GLFW does work but not imgui</div>

**Comment by ocornut** [comment]
Hello @Bekobii,
no need to open another issue. The discussion in #6833 is adequate.
