### ISSUE TITLE
ImageButton doesn't work

### ISSUE THREAD

**Issue by Bobkk-k** [ocornut/imgui#6835]

**Comment by Bobkk-k** [comment]
> _No description provided._

**Comment by ocornut** [comment]
In your code you are calling the same button twice:

```cpp
std::cout << ImGui::ImageButton((void*)(intptr_t)my_opengl_texture, ImVec2(26, 26)) << std::endl;
if (ImGui::ImageButton((void*)(intptr_t)my_opengl_texture, ImVec2(26, 26)))
```

So only the first one with react due to ID conflict.
The image you posted doesn't match the code you posted so it's going to be difficult to help you.

If you want to display the button return value, store it instead of submitting two buttons:

```cpp
bool pressed = ImGui::ImageButton((void*)(intptr_t)my_opengl_texture, ImVec2(26, 26));
if (pressed)
   open_txt_points(...);

ImGui::Text("Button returned %d", pressed);

**Comment by Bobkk-k** [comment]
> In your code you are calling the same button twice:
> 
> ```c++
> std::cout << ImGui::ImageButton((void*)(intptr_t)my_opengl_texture, ImVec2(26, 26)) << std::endl;
> if (ImGui::ImageButton((void*)(intptr_t)my_opengl_texture, ImVec2(26, 26)))
> ```
> 
> So only the first one with react due to ID conflict. The image you posted doesn't match the code you posted so it's going to be difficult to help you.
> 
> If you want to display the button return value, store it instead of submitting two buttons:
> 
> ```c++
> bool pressed = ImGui::ImageButton((void*)(intptr_t)my_opengl_texture, ImVec2(26, 26));
> if (pressed)
>    open_txt_points(...);
> 
> ImGui::Text("Button returned %d", pressed);
> ```

oh! You responded so quickly, Thank you for your reply. I found the reason is I wrote the code before the imagebutton into the loop, and I'm going to delete this question.

**Comment by ocornut** [comment]
> oh! You responded so quickly, Thank you for your reply. 

Or, you posted too quickly ;)
Good luck on your path learning dear imgui !
