### ISSUE TITLE
Making popups work from within a modal pre-docked window

### ISSUE THREAD

**Issue by vdweller84** [ocornut/imgui#6836]
Hello,

Suppose I create a modal window with 2 other windows pre-docked within it. The issue is, pressing the left panel's button to show a (non-modal) popup makes everything related to that pre-docked setup disappear.

Kindly consider the following minimal example:

```
    void ShowTestDockWindow(const std::string& name, bool* open) {
        if (!*open) return;
        struct DockInfo {
            ImGuiID dockspaceID = 0;
            ImGuiID leftID = 0;
            ImGuiID rightID = 0;
            ImGuiWindowClass windowClass;
        };

        static EDIT_UMAP<std::string, DockInfo> mapDockInfo;
        if (mapDockInfo.find(name) == mapDockInfo.end()) {
            DockInfo info;
            mapDockInfo.insert({ name, info });
        }

        DockInfo* dockInfo = &mapDockInfo[name];

        ImGui::SetNextWindowSize(ImVec2(400, 300), ImGuiCond_Once);

        if (ImGui::BeginPopupModal(name.c_str(), open)) {

            dockInfo->dockspaceID = ImGui::GetID(name.c_str());

            if (!ImGui::DockBuilderGetNode(dockInfo->dockspaceID)) {
                ImGui::DockBuilderRemoveNode(dockInfo->dockspaceID);
                    ImGui::DockBuilderAddNode(dockInfo->dockspaceID, ImGuiDockNodeFlags_DockSpace);
                    ImGui::DockBuilderSetNodeSize(dockInfo->dockspaceID, ImGui::GetContentRegionAvail());
                    ImGui::DockBuilderSplitNode(dockInfo->dockspaceID, ImGuiDir_Left, 0.3f, &dockInfo->leftID, &dockInfo->rightID);
                ImGui::DockBuilderFinish(dockInfo->dockspaceID);
            }

            ImGui::DockSpace(dockInfo->dockspaceID);

            dockInfo->windowClass.ClassId = dockInfo->dockspaceID;
            dockInfo->windowClass.DockingAllowUnclassed = false;
            dockInfo->windowClass.DockNodeFlagsOverrideSet = ImGuiDockNodeFlags_NoTabBar | ImGuiDockNodeFlags_NoWindowMenuButton;
            ImGui::EndPopup();
        }
        
        ImGui::DockSpace(dockInfo->dockspaceID, ImVec2(0, 0), ImGuiDockNodeFlags_KeepAliveOnly);

        if (open) {
            //LEFT PANEL
            ImGui::SetNextWindowClass(&dockInfo->windowClass);
            ImGui::SetNextWindowDockID(dockInfo->leftID);
            if (ImGui::Begin((name + "left").c_str())) {
                if (ImGui::Button("test")) {
                    ImGui::OpenPopup("popup");
                }
                if (ImGui::BeginPopup("popup")) {
                    ImGui::Text("Hello");
                    ImGui::EndPopup();
                }
            }
            ImGui::End();

            //RIGHT PANEL
            ImGui::SetNextWindowClass(&dockInfo->windowClass);
            ImGui::SetNextWindowDockID(dockInfo->rightID);
            if (ImGui::Begin((name + "right").c_str())) {
                //...
            }
            ImGui::End();
        }

    }
```

If I comment the line:
`ImGui::DockSpace(dockInfo->dockspaceID, ImVec2(0, 0), ImGuiDockNodeFlags_KeepAliveOnly);`
it does show the popup menu but also instantly undocks the 2 windows and makes the "main" modal window disappear.

Is there a way to maintain the popup ID of the pre-docked window to a functional state without messing things up?

**Comment by ocornut** [comment]
Hello,
I tried replacing your EDIT_UMAP with std::map and adding missing includes, but it crashes on the first call to `DockSpace()` as the provided id is zero.

I am really puzzled as to what you are trying to do, you seems to be using the docking engine as a transient layout system?

**Comment by vdweller84** [comment]
@ocornut Please try replacing EDIT_UMAP with std::unordered_map , it will work as intended.

You are correct, I am using docking (in addition to, well, being able to dock windows) as a layout system in order to avoid hassle with splitters (also see #6826).

**Comment by ocornut** [comment]
Use the Debug Log -> [X] Popups, [X] Docking etc. section to visualize what's happening.
![image](https://github.com/ocornut/imgui/assets/8225057/33b3700c-bf3c-471d-ada6-5c2810844d3d)

This
```cpp
ImGui::OpenPopup("popup");
```
Is closing the modal, it is as designed.

Popups can be nested but they can also be not nested and a sibling would close its sibling.
If you want to open a popup above the modal it needs to be opened in the stack of the modal.

> You are correct, I am using docking (in addition to, well, being able to dock windows) as a layout system in order to avoid hassle with splitters (also see https://github.com/ocornut/imgui/issues/6826).

Please understand you are likely to step on a minefield plus have uncollected .ini data growing.
You may use BeginTable() to perform a simpler split.
I reckon "the hassle with splitters" may be less hassle than what you are doing even, but tables will be a better solution ihmo.

**Comment by vdweller84** [comment]
That is understandable. I will try tables then. Thanks for the quick response. Closing.
