### ISSUE TITLE
WantSetMousePos does not work properly with GLFW callbacks

### ISSUE THREAD

**Issue by bertaye** [ocornut/imgui#6837]
I am trying to create a simple mouse wrapping feature for dragScalar behaviour, and I accomplished it but I needed to alter source code slightly.

I set wantSetMousePos to true, but ImGui still accepts the GLFW callbacks for that frame and thus enqueues latest position of the cursor eventhough I want to set it manually. This creates conflict for DragBehaviourT and results with large mouseDelta along with undesired change in scalar value.

I managed to fix the issue as I show in the image below:
![image](https://github.com/ocornut/imgui/assets/39909689/649d6425-b1af-4813-b125-05dff57257ec)

**I am not sure about if this is the correct way to handle my issue, I am open to suggestions if I did something wrong because I am fairly new to ImGui and still learning the framework**
```
void ImGuiIO::AddMousePosEvent(float x, float y)
{
    ImGuiContext& g = *GImGui;
    IM_ASSERT(&g.IO == this && "Can only add events to current context.");
	if (!AppAcceptingEvents || g.IO.WantSetMousePos)
        return;

```

**Comment by ocornut** [comment]
Hello Bertay,

I have tried to repro this and confirmed your findings.

I believe the right location for the fix to add filtering in `UpdateInputEvents()`.
There might be additional issues related to the inputs queue and low-framerates, I may revise this later.

Pushed ff36fe3 6c022f9 + linking to #228.

I also took the occasion to add an internal function `TeleportMousePos()`.

**Comment by ocornut** [comment]
Also posted extra code here:
https://github.com/ocornut/imgui/issues/228#issuecomment-1723778093

**Comment by bertaye** [comment]
Hi, could you please also apply the fix to docking branch too?

**Comment by ocornut** [comment]
You can cherry-pick the commit until the branch gets merged (at least once a week).
