### ISSUE TITLE
Passing Focus Back to Previous Window

### ISSUE THREAD

**Issue by GudBoiNero** [ocornut/imgui#6838]
Version: ``v1.90 WIP``
Branch: ``docking``

**SDL2/Opengl3/VSCode 22/Windows 10**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl2.cpp
Operating System: Windows 10/11

**My Issue/Question:**

I'm attempting to make a menu that shows up on top of everything. It's meant to be a top-level window that has buttons on it. That's the basics. And my main issue right now is making sure that the menu doesn't take up the focus of the other windows. 
https://github.com/GudBoiNero/PrimedKeys/issues/8

As you can see, my focus is on VSCode yet my MacroMenu is still on top of it. That's exactly what I want. 
![image](https://github.com/ocornut/imgui/assets/80719767/b1500009-cfbc-4acd-83c1-1f4823b3721d)

HOWEVER. When I click on my MacroMenu, VSCode loses focus, I want my focus to stay on VSCode whenever I press on my MacroMenu
![image](https://github.com/ocornut/imgui/assets/80719767/86d8daae-5aa6-452d-afcc-303da620b87d)

I can't find much documentation for this. Help appreciated. 

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
_My repository for this project's master branch is minimal, you shouldn't need much of a setup. Locate `render.h`._
```c
// I pass these flags into my main window, then I hide the window 
// then I create a separate ImGui window and set that as my main viewport. 
inline SDL_WindowFlags window_flags = (SDL_WindowFlags)(
	SDL_WINDOW_OPENGL |
	SDL_WINDOW_ALLOW_HIGHDPI |
	SDL_WINDOW_SKIP_TASKBAR |
	SDL_WINDOW_HIDDEN |
	SDL_WINDOW_ALWAYS_ON_TOP);
```

**Comment by ocornut** [comment]
Hello,

When calling `SDL_ShowWindow()` it calls `::ShowWindow()` with takes focus.

Our multi-viewport support for SDL has to deal with the same issue and has a Windows-specific hack:
https://github.com/ocornut/imgui/blob/docking/backends/imgui_impl_sdl2.cpp#L889
```cpp
static void ImGui_ImplSDL2_ShowWindow(ImGuiViewport* viewport)
{
    ImGui_ImplSDL2_ViewportData* vd = (ImGui_ImplSDL2_ViewportData*)viewport->PlatformUserData;
#if defined(_WIN32)
    HWND hwnd = (HWND)viewport->PlatformHandleRaw;

    // SDL hack: Hide icon from task bar
    // Note: SDL 2.0.6+ has a SDL_WINDOW_SKIP_TASKBAR flag which is supported under Windows but the way it create the window breaks our seamless transition.
    if (viewport->Flags & ImGuiViewportFlags_NoTaskBarIcon)
    {
        LONG ex_style = ::GetWindowLong(hwnd, GWL_EXSTYLE);
        ex_style &= ~WS_EX_APPWINDOW;
        ex_style |= WS_EX_TOOLWINDOW;
        ::SetWindowLong(hwnd, GWL_EXSTYLE, ex_style);
    }

    // SDL hack: SDL always activate/focus windows :/
    if (viewport->Flags & ImGuiViewportFlags_NoFocusOnAppearing)
    {
        ::ShowWindow(hwnd, SW_SHOWNA);
        return;
    }
#endif

    SDL_ShowWindow(vd->Window);
}
```

If you call `::ShowWindow(hwnd, SW_SHOWNA);` instead of `SDL_ShowWindow()` it seems to do the job for us.

That's not really a Dear ImGui question you are asking, rather a SDL question, so I need to close this but I hope this is useful.
