### ISSUE TITLE
Columns: selectable with SpanAllColumns & overlaid button does not work

### ISSUE THREAD

**Issue by petrihakkinen** [ocornut/imgui#684]
Please see the attached pic. I would like to overlay a small button on top of a columns view that has a selectable with ImGuiSelectableFlags_SpanAllColumns in the first column but unfortunately it does not seem to work. When I click on one of the 'E' buttons, the selectable underneath steals the mouse press.

![span_all_issue](https://cloud.githubusercontent.com/assets/2853615/15816782/53da5f04-2bdd-11e6-9a48-e1978ddbec85.png)

**Comment by ocornut** [comment]
I suppose we'd need to add an `_AllowOverlapMode`. You can also just call SetItemAllowOverlap(), have you tried that?

**Comment by petrihakkinen** [comment]
Oh, I'm sorry, I did not know about SetItemAllowOverlap() (it was missing from my Lua binding so I suppose it was added by some ImGui update semi-recently). This fixes the issue. Sorry for the noise, and thanks for the quick reply!

Should this issue be closed, or do you want to keep it open for _AllowOverlapMode?

**Comment by sprinkle131313** [comment]
Bit related to this, using ImGuiSelectableFlags_SpanAllColumns cause the columns to not be resizeable anymore. The hover/click done on the Column border is sent to the Selectable instead.

![render](https://cloud.githubusercontent.com/assets/8701667/19417059/878d16de-9370-11e6-8539-2093d85e9c06.gif)

**Comment by ocornut** [comment]
Yes that's known, As stated above, I think calling `SetItemAllowOverlap()` would fix it. I may look into making that automatic for the column resizing border.

**Comment by ocornut** [comment]
Closing this old issue I forgot to close at the time of adding the `ImGuiSelectableFlags_AllowItemOverlap` flag shortcut.
