### ISSUE TITLE
Strange things with ImVector

### ISSUE THREAD

**Issue by Kolhun** [ocornut/imgui#6843]
Hello everyone, I'm trying to implement an example from demo Tables/Sorting and a question arose: the program crashes during static initialization (example below) although everything works fine in imgui_demo, what could be the reason?

```c
static ImVector<MyItem> items;
```
My example (then everything is commented out as the program goes down during static initialization)

![image](https://github.com/ocornut/imgui/assets/36815965/717dbf7c-51ea-4448-bc7b-31255222c3e6)

Example from the demo

![image](https://github.com/ocornut/imgui/assets/36815965/365f333b-9789-4f29-a851-a894d28a47fe)

**Comment by ocornut** [comment]
Anyhow please don't use ImVector<> please use std::vector<>

```
//   Do NOT use this class as a std::vector replacement in your own code! 
```

**Comment by Kolhun** [comment]
static std::vector<MyItem> items; also causes the program to crash, I don't know how to debug or check it

**Comment by Kolhun** [comment]
What kind of call stacks and additional information are we talking about? Can there be a conclusion?

![image](https://github.com/ocornut/imgui/assets/36815965/778bf958-573a-43bc-ae66-20f08acf3f77)

**Comment by PathogenDavid** [comment]
@Kolhun That's a build failure due to a compiler error, not a crash.

(And like Omar said this really isn't the right place for general C++ questions.)

**Comment by Kolhun** [comment]
![image](https://github.com/ocornut/imgui/assets/36815965/193b345a-68c7-40e0-b137-af3187080907)
![image](https://github.com/ocornut/imgui/assets/36815965/612a12a7-17d3-4946-a209-312de634d9ca)

Code from the example imgui_demo
```c
struct MyItem
{
    int         ID;
    const char* Name;
    int         Quantity;

    // We have a problem which is affecting _only this demo_ and should not affect your code:
    // As we don't rely on std:: or other third-party library to compile dear imgui, we only have reliable access to qsort(),
    // however qsort doesn't allow passing user data to comparing function.
    // As a workaround, we are storing the sort specs in a static/global for the comparing function to access.
    // In your own use case you would probably pass the sort specs to your sorting/comparing functions directly and not use a global.
    // We could technically call ImGui::TableGetSortSpecs() in CompareWithSortSpecs(), but considering that this function is called
    // very often by the sorting algorithm it would be a little wasteful.
    static const ImGuiTableSortSpecs* s_current_sort_specs;

    // Compare function to be used by qsort()
    static int IMGUI_CDECL CompareWithSortSpecs(const void* lhs, const void* rhs)
    {
        const MyItem* a = (const MyItem*)lhs;
        const MyItem* b = (const MyItem*)rhs;
        for (int n = 0; n < s_current_sort_specs->SpecsCount; n++)
        {
            // Here we identify columns using the ColumnUserID value that we ourselves passed to TableSetupColumn()
            // We could also choose to identify columns based on their index (sort_spec->ColumnIndex), which is simpler!
            const ImGuiTableColumnSortSpecs* sort_spec = &s_current_sort_specs->Specs[n];
            int delta = 0;
            switch (sort_spec->ColumnUserID)
            {
            case MyItemColumnID_ID:             delta = (a->ID - b->ID);                break;
            case MyItemColumnID_Name:           delta = (strcmp(a->Name, b->Name));     break;
            case MyItemColumnID_Quantity:       delta = (a->Quantity - b->Quantity);    break;
            case MyItemColumnID_Description:    delta = (strcmp(a->Name, b->Name));     break;
            default: IM_ASSERT(0); break;
            }
            if (delta > 0)
                return (sort_spec->SortDirection == ImGuiSortDirection_Ascending) ? +1 : -1;
            if (delta < 0)
                return (sort_spec->SortDirection == ImGuiSortDirection_Ascending) ? -1 : +1;
        }

        // qsort() is instable so always return a way to differenciate items.
        // Your own compare function may want to avoid fallback on implicit sort specs e.g. a Name compare if it wasn't already part of the sort specs.
        return (a->ID - b->ID);
    }
};
const ImGuiTableSortSpecs* MyItem::s_current_sort_specs = NULL;
}
```

**Comment by GamingMinds-DanielC** [comment]
> Code from the example imgui_demo

What about that code? It defines a `struct MyItem`, so it can use that struct. In your code, the compiler clearly doesn't know about any type with that name, at least it explicitly said so with an error when you tried to use the type. The other errors are follow up errors.

If you need to use a custom type, you must make that type known to the compiler, either by defining it yourself or by including a file that does so. It is not enough if the type is defined in another compilation unit in the same project. I would strongly recommend to look up C++ tutorials that discuss custom types, includes, compilation units and so on. It is very important to learn the basics first before diving into the deep end.

Also, the errors all have error codes for a reason, this way they are easy to look up. If you google C2065, you will find lots of information.

**Comment by Kolhun** [comment]
Thank you, I will
