### ISSUE TITLE
How to simulate smooth cursor/caret movment

### ISSUE THREAD

**Issue by CoolFox29281819** [ocornut/imgui#6844]
hello,

I am on the latest version of imgui and wondering how to simulate smooth caret movment.

Examples:
https://www.youtube.com/watch?v=FCUi_dRU0tY
https://marketplace.visualstudio.com/items?itemName=SergeyVlasov.SmoothCaret

Thanks!

**Comment by ocornut** [comment]
It's currently not supported and not expecting to support this soon, but if we rewrite `InputText()` i would consider it.
