### ISSUE TITLE
[wiki] Update package manager links

### ISSUE THREAD

**Issue by uilianries** [ocornut/imgui#6845]
Hello!

It's not possible to send PRs suggesting changes over project's Wiki, it's a Github limitation.

So I opened this issue to suggest a change related to your Wiki:

On the section [Packaging Cruft](https://github.com/ocornut/imgui/wiki#building--packaging-cruft) is documented that the better way to obtain Imgui via Conan is from Bincrafters and Bintray. However, Imgui is now officially supported by Conan Center, a repository maintained by Conan team.

So, it would be better having this information updated with the follow statement:

```
Conan [github/conan-center-index/conan-imgui](https://github.com/conan-io/conan-center-index/tree/master/recipes/imgui), [conan-center](https://conan.io/center/recipes/imgui)
```

The recipe is stored in Github, and packages in JFrog Artifatory. However, it will be better pointing the Conan Center page, which has a friendly interface, helping to install the package.

Regards.

**Comment by ocornut** [comment]
Hello,
Sounds good. Feel free to edit the wiki with those extra two links, that’s what the Wiki is for!

**Comment by uilianries** [comment]
@ocornut Done! Thank you!
