### ISSUE TITLE
where to find d3dx9tex.h

### ISSUE THREAD

**Issue by CoolFox29281819** [ocornut/imgui#6848]
Just looking for a download for d3dx9tex.h

I have the directx9 sdk downloaded and this one doesnt appear to work:

https://github.com/apitrace/dxsdk/blob/master/Include/d3dx9tex.h

![image](https://github.com/ocornut/imgui/assets/144345472/68e2a79e-9e2a-4365-aba8-6c0d0cacb58d)

**Comment by sakiodre** [comment]
If I remember correctly, you must download and install [DirectX SDK](https://www.microsoft.com/en-US/download/details.aspx?id=6812), and remember to add `$(DXSDK_DIR)Include` to your additional include directories.

**Comment by CoolFox29281819** [comment]
Thanks! That appears to work.

**Comment by CoolFox29281819** [comment]
Hello, do you know how I can fix this?

![image](https://github.com/ocornut/imgui/assets/144345472/e656a832-58bd-4384-8a87-9d99f8059414)

I am only including d3dx9tex.h once.

**Comment by nicolasnoble** [comment]
You now need to also link in the library, not just set its include path, probably `d3d9.lib`.

Note that this isn't an issue with ImGui itself.

**Comment by ocornut** [comment]
Closing as answered.
Coolfox you've opened 7 issues and never really cared about issue opening guideline and issue template, we'll need you to throttle down and put a little more effort reading the information and guidelines we are providing.
