### ISSUE TITLE
Load images by memory and not by file (directx9)

### ISSUE THREAD

**Issue by CoolFox29281819** [ocornut/imgui#6849]
Hello,

I am wondering how to load images via memory (like we do with fonts) and not by actual directory. thanks

**Comment by nicolasnoble** [comment]
Check https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples and https://github.com/nothings/stb/blob/5736b15f7ea0ffb08dd38af21067c314d6a3aae9/stb_image.h#L421-L432
