### ISSUE TITLE
IndexLookup.Size range too small ? 

### ISSUE THREAD

**Issue by MINIONBOTS** [ocornut/imgui#685]
https://github.com/ocornut/imgui/commit/727ca4bd17da6c07bf375e336062574cf1751f19

This commit breaks it for me, because my IndexLookup.Size is 65520, and when I look at the code, shouldn't the "int" get replaced by an "unsigned short" instead of a "short" here ?

**Comment by ocornut** [comment]
Why would you have 0xFFF0 in your glyph ranges? What is the repro?

**Comment by MINIONBOTS** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2842405/15838055/73419f06-2c3c-11e6-9c9b-d133578d96ca.png)

This is the code which loads 4 seperate language files in addition to the default one, which you can find here: http://pastebin.com/NWAhjQJV

What do you mean with "repro" ?

**Comment by ocornut** [comment]
A repro is standalone code that I can compile or paste into the example app that would reproduce the issue. Based on the glyphs ranges provided I don't see how IndexLookup.Size can be 65520.

**Comment by MINIONBOTS** [comment]
I'm a bit busy with work right now, won't have much time in the next days, to put a standalone project together. But since the IndexLookup.Size can never be negative and I obviously managed to reach the 65520 size, why not just go with the unsigned short, it uses the same amount of memory in the end.

Is there anythingelse involved in creating that index size besides the language files ?
Would it help if I link you the language files which I add additionally ?

I'll make that standalone project, but I think it won't be possible before friday :/

**Comment by ocornut** [comment]
>  I obviously managed to reach the 65520 size
This first needs to be explained. I can't fix issue B if I don't understand why A is happening. Having so many glyphs is abnormal. How manys fonts do you have?
What a "language file"? 

It doesn't need to be a standalone project it can be just a bit of code than I can paste into the demo/examples and get the bug.

**Comment by MINIONBOTS** [comment]
well yes, I do have tons of glyphs due to the "asia" languages being crazy. This is the resulting texture size with glyphes:
![untitled](https://cloud.githubusercontent.com/assets/2842405/15848656/82e28aea-2c8e-11e6-9939-d3072a6fe146.png)

Here are the 4 additional fonts I merge into the default one from above:
[LangPack.zip](https://github.com/ocornut/imgui/files/302007/LangPack.zip)

**Comment by MINIONBOTS** [comment]
I don't want to waste your time, so maybe just wait till friday, when I have copied / tested it in the demo project of imgui. I "copied" the demo console, when I bring it up after that "int to short" change, it trows an exception / crashes.

**Comment by ocornut** [comment]
Your code above seems to be a sort of repro except you pasted a picture instead of actual code.

**Comment by ocornut** [comment]
So, there was an IM_ASSERT triggering in BuildLookupTable() that you didn't mention, or are you ignoring asserts?

I have now increased the maximum number of glyph per font to 0xFFFE (~64k - 2).

In the absence of a dynamically populated atlas, it is really unreasonable to merge all those fonts and glyph ranges together at the moment. What is your use case? Can't you narrow glyph ranges to what your content narrow?

**Comment by ocornut** [comment]
Commit is 65a525550ecf48e14f20681b081b1d9c8c136563

**Comment by MINIONBOTS** [comment]
Oh yes, it was the assert ....I guess I didn't notice it at the end of the day, after going manually through 3 months of commits to find my culprit. 

Regarding the fonts & glyph ranges, maybe I have not understood how this is supposed to be used for my case: The language needs to be able to display always the latin characters, and in addtion to that, Russian, Korean, Japanese and Chinese ones. This works when I have them all merged together, but my inexperience with these asia languages leaves me in a place where I don't know which glyphes are "usually" needed to present all their "alphabet" or whatever it is they are using on a daily basis ;). 
I first had therefore 4 times the latin + 1 foreign font file merged together, letting the user choose what language he prefers. But I found that solution also not optimal. 

Thank you for your amazing work, I just started the recurring support ;)

**Comment by MINIONBOTS** [comment]
( I had NDEBUG defined btw.)

**Comment by ocornut** [comment]
Hmm unfortunately until the atlas can update dynamically, which is a task by itself, there isn't a perfect solution right now. Baking 32K glyphs will be rather heavy on boot. Typically for games what people do is to gather glyphs _actually_ used in localization data and only bake those in the font. If you are doing a game where users can input any character then a better solution is needed (and a dynamic atlas will provide that). Otherwise for Chinese there's probably table sorted by frequency somewhere, so you could include say, top 5000. Thanks for the support :)
