### ISSUE TITLE
Double buffer for InputTextMultiline?

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#6850]
I tried using the ImGui::InputTextMultiline function with a callback to dynamically change the line, like this:

```

static int MyCallback_TEXT_INPUT_Resize_buff(ImGuiInputTextCallbackData* data)
{
   
        std::string* string_p = (std::string*)data->UserData;
        string_p->resize(data->BufTextLen);
        std::cout << string_p->size() << std::endl;
        data->Buf = &(*string_p)[0];

        (*string_p)[0] = 'A';
    
        return 0;
   
}


ImGui::Begin("TEXT_INPUT_MULTI");

 static std::string string_static = "";
 ImVec2 size_multi_input = { 100, 100 };

 ImGui::InputTextMultiline("Name_1", &string_static[0], string_static.size(), size_multi_input , ImGuiInputTextFlags_CallbackResize, MyCallback_, &string_static);  

ImGui::End();
```

As you can see in the callback, I specifically change the first character to the character “A” - HOWEVER, every time the callback is called, in place of my set character - the character entered from the keyboard is there.

It seems that Imgui uses an internal buffer to store text entered by the user and copies it to my user buffer each time.

Please tell me - is this true?

**Comment by ocornut** [comment]
> Please tell me - is this true?

Yes.

But anyhow you shouldn’t use the buffer resize callback to be modifying anything, this doesn’t make sense. This is a callback for resizing a buffer (already provided in misc/cpp/ for std::string). If you want to do something else use the right callback and you’ll find the provided data structure has helpers to modify the string.

**Comment by ElectroidDes** [comment]
Understood. Thanks for the explanation.
