### ISSUE TITLE
Question about text display

### ISSUE THREAD

**Issue by Kolhun** [ocornut/imgui#6852]
Hello everyone, there is a question does not write to a variable of type const char* (item.Name ) at the same time, there is an output to the console via printf. When trying to debug, it outputs screen 1 (everything is OK), but it outputs it to the table as a question mark... screen 2 what could be the problem?

```c
std::string textDebug;
static char bufTextDebug[100] = "";
for (auto row = sections.begin(); row != sections.end(); ++row)
{
    std::string defId = row->pItem;
    const char* defIdChar = defId.c_str();

    items.resize(dataResult["data"].size(), MyItem());
    for (int n = 0; n < items.size(); n++)
    {
        const int template_n = n % IM_ARRAYSIZE(template_items_names);
        MyItem& item = items[n];
        if (item.Name == "")
        {
            item.ID = n;
            item.Name = ini.GetValue(defIdChar, "name", "noone");
            textDebug = ini.GetValue(defIdChar, "name", "noone");
            item.Quantity = (n * n - n) % 20;
            printf("%s\n", ini.GetValue(defIdChar, "name", "noone"));
            break;
        }
    }
}
```
screen 1
![image](https://github.com/ocornut/imgui/assets/36815965/26fabf43-e791-47d9-bc9f-bc12d73745f0)

screen 2
![image](https://github.com/ocornut/imgui/assets/36815965/e3276250-d6e3-46cc-8cd2-f92c40975fde)

**Comment by ocornut** [comment]
This is a not a question about Dear ImGui.
We don't have resources to teach people about C or C++ here, sorry. If we start doing that it sucks up our resources.

We have no idea what ini.GetValue() does and what is the lifetime of the returned value.
Always use std::string for storage if you are not confident about understanding the lifetime of data.
