### ISSUE TITLE
ColorEdit4/3 Issue

### ISSUE THREAD

**Issue by il2ex** [ocornut/imgui#6856]
Hey everyone. Currently I am facing with a provlem with ColorEdit4 and 3.

So if I click on it the colorpicker should show up. But it doesnt. It just bugging and nothing shows up.

**Comment by sakiodre** [comment]
This is extremely vague, can you follow the issue template and post a reproducible code, and maybe a video of the problem?

**Comment by greeneyes1337** [comment]
You have written several Cheats for Kernel-Mode protected games but cant send a code snippet for a color picker?

Also, https://github.com/ocornut/imgui/issues/1586

**Comment by il2ex** [comment]
Yeah ik I was pretty dumb there lmao.. But I just couldnt fix it, but I realized it was overcalling some shit + I had problems with render. 

But I fixed it 👍🏻
