### ISSUE TITLE
"remember" selected tab after updating tab name?

### ISSUE THREAD

**Issue by briaguya-ai** [ocornut/imgui#6857]
**My Issue/Question:**

I would like to be able to update the names of tabs as a way to indicate a status. However, when updating the tab name that tab loses focus (focus returns to the first tab).

I couldn't find an example or issue mentioning this, so any advice would be greatly appreciated!

**Screenshots/Video**

https://github.com/ocornut/imgui/assets/70942617/d09784f7-3c87-4479-81d1-813a8685b619

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```cpp
static bool additionalText[4] = {false, false, false, false};
ImGui::BeginTabBar("##ExampleTabs");
for (int i = 0; i < 4; i++) {
    char name[16];
    snprintf(name, IM_ARRAYSIZE(name), "Name %s##%d", additionalText[i] ? "and" : "", i);
    if (ImGui::BeginTabItem(name)) {
        ImGui::Checkbox("Additional Text", &additionalText[i]);
        ImGui::EndTabItem();
    }
}
ImGui::EndTabBar();
```

**Comment by briaguya-ai** [comment]
i feel like there's probably a cleaner solution out there, but this gets the example working
```cpp
static bool additionalText[4] = {false, false, false, false};
static bool openTab[4] = {false, false, false, false};
ImGui::BeginTabBar("##ExampleTabs");
for (int i = 0; i < 4; i++) {
    char name[16];
    snprintf(name, IM_ARRAYSIZE(name), "Name %s##%d", additionalText[i] ? "and" : "", i);
    if (ImGui::BeginTabItem(name, __null, openTab[i] ? ImGuiTabItemFlags_SetSelected : ImGuiTabItemFlags_None)) {
        for (int ti = 0; ti < 4; ti++) {
            openTab[ti] = false;
        }
        if (ImGui::Checkbox("Additional Text", &additionalText[i])) {
            openTab[i] = true;
        }
        ImGui::EndTabItem();
    }
}
ImGui::EndTabBar();
```

**Comment by PathogenDavid** [comment]
You can use `###` instead of `##` to ignore the human-readable part of a widget's name for the purposes of calculating its ID, which is meant for exactly this sort of scenario.

IE, change your `snprintf` to the following:

```cpp
snprintf(name, IM_ARRAYSIZE(name), "Name %s###%d", additionalText[i] ? "and" : "", i);
```

**Comment by briaguya-ai** [comment]
beautiful! thank you!

**Comment by ocornut** [comment]
Also see FAQ for a fuller explanation of using ## and ### in labels.
