### ISSUE TITLE
Imgui crashes with following steps

### ISSUE THREAD

**Issue by zaafar** [ocornut/imgui#6858]
```
Dear ImGui 1.89.9 (18990)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1937
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000443
 NavEnableKeyboard
 NavEnableGamepad
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

ImGui crashes when I open+close `ShowFontSelector` combo box and do not crash when I do not open+close `ShowFontSelector` combo box.

** Steps to re-produce the issue **

step-1: apply this diff to the example project

NOTE: This diff is not really  a use-case, it's a minimal code change to re-produce the issue. The actual issue I encounter is in the C# world and I am not sure if its me doing something wrong or just a imgui bug. I know how to change fonts and I know how to bypass this issue. Sorry in advance if this is me doing something wrong. I am just making sure it isn't an imgui bug. If this isn't feel free to close the issue

```
$ git diff
diff --git a/backends/imgui_impl_dx11.cpp b/backends/imgui_impl_dx11.cpp
index b53fa09c..4bb67d70 100644
--- a/backends/imgui_impl_dx11.cpp
+++ b/backends/imgui_impl_dx11.cpp
@@ -311,6 +311,7 @@ void ImGui_ImplDX11_RenderDrawData(ImDrawData* draw_data)
     ctx->IASetInputLayout(old.InputLayout); if (old.InputLayout) old.InputLayout->Release();
 }

+
 static void ImGui_ImplDX11_CreateFontsTexture()
 {
     // Build texture atlas
@@ -373,6 +374,8 @@ static void ImGui_ImplDX11_CreateFontsTexture()
     }
 }

+void ImGui_ImplDX11_foobar() { ImGui_ImplDX11_CreateFontsTexture(); }
+
 bool    ImGui_ImplDX11_CreateDeviceObjects()
 {
     ImGui_ImplDX11_Data* bd = ImGui_ImplDX11_GetBackendData();
diff --git a/backends/imgui_impl_dx11.h b/backends/imgui_impl_dx11.h
index 5737393d..0629c737 100644
--- a/backends/imgui_impl_dx11.h
+++ b/backends/imgui_impl_dx11.h
@@ -26,5 +26,6 @@ IMGUI_IMPL_API void     ImGui_ImplDX11_RenderDrawData(ImDrawData* draw_data);
 // Use if you want to reset your rendering device without losing Dear ImGui state.
 IMGUI_IMPL_API void     ImGui_ImplDX11_InvalidateDeviceObjects();
 IMGUI_IMPL_API bool     ImGui_ImplDX11_CreateDeviceObjects();
+IMGUI_IMPL_API void     ImGui_ImplDX11_foobar();

 #endif // #ifndef IMGUI_DISABLE
diff --git a/examples/example_win32_directx11/main.cpp b/examples/example_win32_directx11/main.cpp
index 65601317..1c25a28f 100644
--- a/examples/example_win32_directx11/main.cpp
+++ b/examples/example_win32_directx11/main.cpp
@@ -137,7 +137,7 @@ int main(int, char**)
             static int counter = 0;

             ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.
-
+            ImGui::ShowFontSelector("FooBar");
             ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
             ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
             ImGui::Checkbox("Another Window", &show_another_window);
@@ -180,6 +180,14 @@ int main(int, char**)

         g_pSwapChain->Present(1, 0); // Present with vsync
         //g_pSwapChain->Present(0, 0); // Present without vsync
+
+        if (show_another_window)
+        {
+            io.Fonts->Clear();
+            io.Fonts->AddFontDefault();
+            ImGui_ImplDX11_foobar();
+            show_another_window = false;
+        }
     }

     // Cleanup
```

step-2: Start example project and press `Another window` checkbox as many times as you want.

step-3: now click FooBar `ShowFontSelector` combobox one time

step-4: press `another window` checkbox again and there will be a crash

**Comment by PathogenDavid** [comment]
I cannot reproduce using the latest `docking` (specifically at 2c0007731f464ec13bfd21976baac2244462440c)

Can you share more details of the crash? (Namely a stack trace. Ideally from running a modified example and not through C#, but if you do use C# make sure mixed-mode debugging is enabled.)

**Comment by zaafar** [comment]
I have tested it on 2c00077 and it's crashing there.
Did you apply the diff and follow the steps? here are the screenshots.

step-2 click "Another window" checkbox
![image](https://github.com/ocornut/imgui/assets/5079646/a3fbc4e6-11bf-4016-aab3-2836b6ad918c)


step-3: click "proggy clean"
![image](https://github.com/ocornut/imgui/assets/5079646/038a026a-d434-4171-8787-9d3023eba73f)

step-4: click "another window" checkbox again


here's the screenshot of the failure
![image](https://github.com/ocornut/imgui/assets/5079646/22084b10-49e5-4b8b-b759-532725145bea)

**Comment by PathogenDavid** [comment]
Ah, I see now. Thank you for clarifying. I took your original step 3 too literally and didn't actually make a selection.

What's happening is Dear ImGui is trying to start the new frame with the default font as the current font:

https://github.com/ocornut/imgui/blob/2c0007731f464ec13bfd21976baac2244462440c/imgui.cpp#L4760

`ImGui::GetDefaultFont` is implemented such that if `ImGuiIO::FontDefault` is null (which it is by default), it will just return the first font:

https://github.com/ocornut/imgui/blob/2c0007731f464ec13bfd21976baac2244462440c/imgui_internal.h#L3126

When you make a selection with `ImGui::ShowFontSelector`, you're setting `ImGuiIO::FontDefault` to point to a specific font.

Finally when you call `ImFontAtlas::Clear` you end up freeing that old font, but `ImGuiIO::FontDefault` will still be pointing to the now-invalid font.

This eventually triggers an assert `ImGui::SetCurrentFont` because the font is messed up internally from being freed.

---------------------

The easiest fix on your end is to simply set `ImGuiIO::FontDefault` to null in your font reload logic.

Ideally Dear ImGui would do this for you, but it's kinda tricky since `ImFontAtlas` doesn't really know about `ImGuiIO`.

There is a planned general rework of how Dear ImGui handles loading new fonts and glyphs at runtime, so I suspect a proper fix may be deferred until that happens.

(As an aside, your example code is leaking the old font texture view. I assume you just left releasing it out to keep the diff small but I thought I should mention it just in case.)

**Comment by zaafar** [comment]
> The easiest fix on your end is to simply set ImGuiIO::FontDefault to null in your font reload logic.

Thank you this is what I wanted.

> (As an aside, your example code is leaking the old font texture view. I assume you just left releasing it out to keep the diff small but I thought I should mention it just in case.)

**Comment by ocornut** [comment]
> Ideally Dear ImGui would do this for you, but it's kinda tricky since ImFontAtlas doesn't really know about ImGuiIO.

Thank you David for pointing this out. I took note of this as part of things to remember when I get to rework font system.
