### ISSUE TITLE
using Imgui with Oculus rift dk2

### ISSUE THREAD

**Issue by azadybashar** [ocornut/imgui#686]
Hi
i have a DK2 and use imgui for my project but when i render in oculus , I can't see my imgui windows
please help me

**Comment by ocornut** [comment]
I'm sorry this question has nothing to do with ImGui. If you have an issue with rendering with provide more infos about which rendering backend you are using and possibly a repro.

In a stereo-render type of setup you can typically render your ImGui scene on both side of the screen, or perhaps on the shared/PC screen only buffer if that makes sense.
