### ISSUE TITLE
ImVector<std::unique_ptr<T>> calls destructor on push_back

### ISSUE THREAD

**Issue by rayment** [ocornut/imgui#6860]
**Version/Branch of Dear ImGui:**

Version: `1.89.9`
Branch: `master`

**Back-end/Renderer/Compiler/OS**

Back-ends: `imgui_impl_sdl2.cpp` + `imgui_impl_opengl3.cpp`
Compiler: `g++ (Gentoo Hardened 12.3.1_p20230526 p2) 12.3.1 20230526`
Compiler options: `-Wall -Wextra -pedantic -fdiagnostics-show-option`
Compiler debug options: `-O0 -g3 -ggdb`
Operating System: `Linux 6.1.41-gentoo-x86_64 #1 SMP PREEMPT_DYNAMIC`

**My Issue/Question:**

Calling `push_back` on an `ImVector<std::unique_ptr<T>>` is calling the destructor on class `T` when moving the instance into the vector. This invalidates the data the moment it is inserted and any further read is undefined.

When substituting `ImVector<std::unique_ptr<MyStruct>>` for the type `std::vector<std::unique_ptr<MyStruct>>`, this is no longer an issue. As such, I am currently unable to use `ImVector` to store unique allocations at all.

Given that only a subset of C++11 is actually used in this project (which I totally understand), I don't expect this to be fixed. Then let us leave it here so that the next person doesn't spend many hours scratching their head as I have done. 

**Standalone, minimal, complete and verifiable example:**

```
struct MyStruct
{
    std::string text;
    int x, y;
    MyStruct(const std::string &text, int x, int y) : text(text), x(x), y(y) {}
};

ImVector<std::unique_ptr<MyStruct>> lines;
// the following line calls the destructor of the unique ptr, invalidating it immediately
lines.push_back(std::move(std::make_unique<MyStruct>("Hello, world!", 0, 0)));
```

**Comment by rayment** [comment]
I was originally using it as part of an adaptation of the console window provided in the demo code and then wanted to store smart pointers rather than `char *` which was being used. I've learned my lesson.

**Comment by ocornut** [comment]
I will try to leave more comments/references to the suggestion that you shouldn’t be using imvector with non trivial constructors/destructors.

Personally I find it a bit disheartening to find people using high-level concepts such as unique_ptr by habit, but I guess i’ll just retreat in my own habits :)

**Comment by rayment** [comment]
> Personally I find it a bit disheartening to find people using high-level concepts such as unique_ptr by habit, but I guess i’ll just retreat in my own habits :)

To be fair, I've only just started out using this library and coming from a C background myself, it's very pleasant to work with. A big thanks to you.
