### ISSUE TITLE
This is not an issue but rather suggestion or question is there a way to open a window from code? I mean can i somehow create new instance of class by clicking on button and then render new window based on its properties? Something like in photoshop when you are clicking on add layer button. I am trying it for some time already and tried many things but nothing seems to be working. Tried it on docking & master branch using opengl3 & glfw implementation. Every suggestion is appreciated.

### ISSUE THREAD

**Issue by joniship** [ocornut/imgui#6868]
Branch: master & docking

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: windows

This is not an issue but rather suggestion or question is there a way to open a windows from code? I mean can i somehow create new instance of class by clicking on button and then render new window based on its properties? Something like in photoshop when you are clicking on add layer button. I am trying it for some time already and tried many things but nothing seems to be working. Tried it on docking & master branch using opengl3 & glfw implementation. Every suggestion is appreciated.

**Comment by ocornut** [comment]
Everything is done in code is dear imgui land, so the answer to your question is yes.
You can run and browse any of the examples/ main.cpp and they are doing that.

I reckon your question has more to do with being unfamiliar with programming and unsure about how to setup your own application state and manage it, so I would suggest asking in a different location.
