### ISSUE TITLE
Question: Check whether mouse click was handled by any widget?

### ISSUE THREAD

**Issue by cgloeckner** [ocornut/imgui#687]
Hi, is there a way to check whether a mouse click was handled by **any** widget? My question is about using ImGui for a map editor, where UI-related clicks (e.g. selecting a tile in the preview) must not trigger placing a tile on the map.  Setting a flag like
```c++
bool flag = false;
if (ImGui::Button("foo")) { flag = true; handleBtn(); }
if (ImGui::Combo("bar", ...)) { flag = true; handleCombo(); }
if (!flag) {
  // handle all incomming click events
  // ...
}
```
is way too ugly for larger UIs.

Thanks in advance!

**Comment by ocornut** [comment]
Use the `io.WantCaptureMouse` flag.
Please read the FAQ.
