### ISSUE TITLE
Error when compiling: : no member named 'DebugIDStackTool' in 'ImGuiContext'; did you mean 'DebugIdStackTool'?

### ISSUE THREAD

**Issue by unix-based-system** [ocornut/imgui#6871]
Version: 1.90 WIP latest MASTER

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp/imgui_impl_opengl3.cpp --> Emscripten

**My Issue/Question:**

Hi,

We seem to have a typo in one of the source files. Will try to rename myself for now as compiling fails at the moment.
Seems to be related to the change listed as: " - Debug Tools: Renamed ShowStackToolWindow() ("Stack Tool") to ShowIDStackToolWindow() ("ID Stack Tool")"

Thanks in advance,
Pim

![error](https://github.com/ocornut/imgui/assets/54240100/2d9f2a33-bd9e-4fdd-b283-892acd6bf176)

**Comment by ocornut** [comment]
Apologies commit N-1 had an accidental chunk revert which I've fixed already:
https://github.com/ocornut/imgui/commit/03e2a7f58417f0eba7f8276b7dcaea0f5b981e40

**Comment by unix-based-system** [comment]
Ah, I see, Thanks :-)
