### ISSUE TITLE
Changing the window name

### ISSUE THREAD

**Issue by Kolhun** [ocornut/imgui#6872]
Good afternoon, is it possible to dynamically change window titles?

**Comment by ocornut** [comment]
Yes, see `Demo -> Examples -> Manipulating Window Titles` and `ShowExampleAppWindowTitles()` demo function.

You need to use the `###` operator which is described in the FAQ:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

> Occasionally/rarely you might want to change a label while preserving a constant ID. This allows you to animate labels. For example, you may want to include varying information in a window title bar, but windows are uniquely identified by their ID. Use "###" to pass a label that isn't part of ID:

```cpp
Button("Hello###ID");  // Label = "Hello",  ID = hash of (..., "###ID")
Button("World###ID");  // Label = "World",  ID = hash of (..., "###ID")  // Same ID, different label

sprintf(buf, "My game (%f FPS)###MyGame", fps);
Begin(buf);            // Variable title,   ID = hash of "MyGame"
```
