### ISSUE TITLE
(Suggestion) ImGuiState access refactor to support multiple context in multiple threads

### ISSUE THREAD

**Issue by Galloman** [ocornut/imgui#688]
Currently, a lot of functions access the `ImGuiState` (aka context) in that way:

`ImGuiState& g = *GImGui;`

That's fine for a single context, or multiple context (windows) updating on the same thread changing it with `ImGui::SetInternalState`, but that doesn't work well if we have different windows on different threads. Changing the entire interface to require a `ImGuiState*` as a parameter for every function is madness, it not only implies functions that directly access to state but functions that also call those, which means the entire imgui interface. So, a solution could be just replacing the `*GImGui;` (~245) access with a call to `GetInternalState()` .

This way the user (programmer) can modify `GetInternalState` function to manage how to access the context and use a unique thread id like the c++11 one http://en.cppreference.com/w/cpp/thread/get_id, to access a per-thread `ImGuiState`, just think in a `std::map<std::thread_id, ImGuiState*>`. Ok, it asumes that every imgui call is performed in the thread that holds the `ImGuiState` where it wants to draw something, but makes sense, and it doesn't mean that a thread can only hold one `ImGuiState`, It can even be mixed with threads that hold multiple context just modifying GetInternalState to work that way with those threads, similar to how we are currently working calling `SetInternalState` to change it. 

For some functions (mainly little functions used internally) where a call to a complex version of `GetInternalState` may suppose a performance impact, well, maybe for those there is no better solution than passing the context as a parameter...

What do you think about this possible solution for multi-threaded/windows applications?

**Comment by ocornut** [comment]
Please post this in
https://github.com/ocornut/imgui/issues/586
