### ISSUE TITLE
help with my tool

### ISSUE THREAD

**Issue by LIBBBhhh** [ocornut/imgui#6886]
Does anyone know how to automate the autosave function? While (true) does not help in this case because the window freezes

Code:

´´´

void AutoSave() {
	
          
	
			  
		  
		//Dont use LOGE Cout This!!
		
	std::string filename = "Imgui.ini";

    
    std::ofstream outputFile(filename);

    
    if (outputFile.is_open()) {
        
        
        outputFile.close();

     
    } else {
        
    }
		
		
    ImGui::SaveIniSettingsToDisk("Imgui.ini"); 
		
       
  
}
´´´

**Comment by ocornut** [comment]
Sorry but #1586
