### ISSUE TITLE
ImGui docking crash!

### ISSUE THREAD

**Issue by TitanCheat** [ocornut/imgui#6887]
Hello, I'm using imgui directx9 docking branch, 
When the imgui app is running ( the example app that is available in github ) and I go to a fullscreen app then minimize it, the ImGui app will crash.
```
RenderPlatformWindowsDefault->ImGui_ImplDX9_RenderWindow
vd->SwapChain->GetBackBuffer(0, D3DBACKBUFFER_TYPE_MONO, &render_target);

Exception thrown: read access violation.
vd was nullptr.
```

**Comment by sakiodre** [comment]
#1586

**Comment by ocornut** [comment]
I feel there's probably a legit edge case here but I can't seem to find how to reproduce it.
None of the backends are protected against a possible null value in `viewport->RendererUserData` as in, it shouldn't happen at the time of calling the `platform_io.Renderer_RenderWindow()` handler.

Barring more evidence and more details (versions) I'd close it on #1586 heuristic
