### ISSUE TITLE
(D3D9 / Hooked Device ) Issues with integration, code is locking up

### ISSUE THREAD

**Issue by PermaNulled** [ocornut/imgui#689]
So I haven't been able to track down what exactly is causing my problem and my implementation/integration isn't an normal scenario I was hoping someone here would be able to help figure out what's going wrong.

To explain my project in a short way Xbox Live for halo 2 on windows was shut down I've created a mod which restores it by mirroring all of the XLive functionality in my own DLL but over LAN an added advantage was that I had access to the functions which GFWL (Games for Windows Live) used to render it's own overlays/hud on top of the game it was interacting with.

Such as 

```
HRESULT XLiveOnCreateDevice(
          IUnknown *pD3D,
         VOID *pD3DPP
 )
 HRESULT XLiveInitialize(
          XLIVE_INITIALIZE_INFO *pPii
)
HRESULT XLiveRender()

```
> XLiveRender is called by games in the render loop after BeginScene is called and all rendering has completed. XLiveRender is called before the last EndScene method call in the render loop.

With this I wanted to add my own GUI to the mix, and have choose to attempt integration of imgui, so far I've just been trying to get the d3d9 example to render in the game but It's locking up at 

> 09/06/2016 04:45:41.662 ImFontAtlas::Build() - for_loop #3 - stbtt_PackFontRangesRenderIntoRects( RangesCount: 1 )

Which appears to happen in ImGui_ImplDX9_NewFrame();
https://github.com/PermaNulled/cartographer/blob/imgui_attempt/GUI.cpp#L311

Originally I thought this was due to my lack of HWND handle as I was passing NULL so I made it wait until that was filled by another handler of XLive which the game passes it's window handle into.

Once the game does that I call ImGui_ImplDX9_Init()
https://github.com/PermaNulled/cartographer/blob/imgui_attempt/GUI.cpp#L120

I've commented everything else out because i can't seem to get past this point things are locked up from here if I wait up to 30 or so seconds it will still not be functioning it doesn't crash it's just frozen/in a dead lock state.

Based on strings I've added in this is as far as it gets,
https://github.com/PermaNulled/cartographer/blob/imgui_attempt/imgui/imgui_draw.cpp#L1432

I would appreciate any help any one has to offer on the matter, I also apologize for my sloppy code I'm not exactly a 'professional' or someone looking for a career in programming.

**Comment by ocornut** [comment]
Are you using any non-default font setting?
This is odd as this specific function and not depending on any device/etc. so it should always work. Unless perhaps some combination of font settings/inputs are breaking it.

**Comment by PermaNulled** [comment]
This is 100% just copy and paste of the example stuff for d3d9... I haven't tried passing input to it yet the only two functions I'm trying to call from the example so far are the NewFrame and Initialization

**Comment by ocornut** [comment]
I can't explain it then. There's something fishy, perhaps something you have overlooked, perhaps some of your code is overwriting memory somewhere. Tracing in with a debugger from the first call to GetTextDataXXXX would be useful.

**Comment by PermaNulled** [comment]
I'm guessing it has to be something I've personally done wrong like the device not being valid or something of the sort, or the fact I was originally not passing a HWND handle but after solving those issues I was still stumped.

Would the font creation for my own drawing cause issues that I mentioned in my previous edit?

**Comment by ocornut** [comment]
> I'm guessing it has to be something I've personally done wrong like the device not being valid or something of the sort, or the fact I was originally not passing a HWND handle but after solving those issues I was still stumped.

That code has nothing to do with device or HWND or anything non-portable. It's pure platform-independent C code working with ImGui own data (assuming you aren't feeding custom fonts).

> Would the font creation for my own drawing cause issues that I mentioned in my previous edit?

Do you mean ImGui fonts or unrelated?
That hanging code is the code building the font data for ImGui, you told me about that you aren't using any non-default font.

**Comment by PermaNulled** [comment]
> That code has nothing to do with device or HWND or anything non-portable. It's pure platform-independent C code working with ImGui own data (assuming you aren't feeding custom fonts).

I understand that, like I said I had fixed those problems which were causing IM_ASSERT issues when attempting to create the font.

> Do you mean ImGui fonts or unrelated?
That hanging code is the code building the font data for ImGui, you told me about that you aren't using any non-default font.

I don't mean anything related to ImGui but I do create my own fonts for drawing text outside of the ImGui Framework I'm just wondering if that could some how interfere with it on a d3d level.

I'm not really too familiar with d3d development it's rather new to me, so I'm at a loss here but I'll keep trying to go deeper and figure out what my exact cause is.

**Comment by ocornut** [comment]
The point is, ImGui NewFrame() and stbtt_PackFontRangesRenderIntoRects() don't do ANYTHING with your d3d device, it's not a concept they know about. The only code that touches your D3D device is the example code in imgui_impl_xxx files.

**Comment by PermaNulled** [comment]
I understand that I was just clarifying why I had mentioned it in general, I'll do additional debugging and report back here with what I find.

**Comment by paulsapps** [comment]
Why not just trace the params that cause the hang and then try it in a standalone demo to repro?

**Comment by ocornut** [comment]
Any news? FYI i have never seen this code hang and it entirely depends on embedded data so I can't imagine it to be a bug in ImGui. Note that GImGui and io.Fonts both points to globals by default which in the context of DLL-style compiling, unloading, dynamic loading, or custom hot-reloading could means that different part of your code might see a different value, or you may have a dangling pointers somewhere.

Printing GImGui and io.Fonts from different position of your code would help to clarify that. You can create your own context, set as default, and your own ImFontAtlas, set as io.Fonts if you need to ensure that the data is persistent over your unload/reload etc.

**Comment by PermaNulled** [comment]
The only news I have is that it was machine dependent and I wasn't able to fix it on my main machine but another person involved in development had it working fine, though it was running at an extremely low FPS it worked in general.

**Comment by ocornut** [comment]
@PermaNulled Closing this as AFAIK those issues are probably not related to ImGui but to third party code. If you get more information/understanding or if there is any way ImGui can be improved happy to hear about it.
