### ISSUE TITLE
Backends: Missing call to SDL_GameControllerClose() ?

### ISSUE THREAD

**Issue by m9710797** [ocornut/imgui#6890]
Hi,

I don't see anything going wrong, but I think there's a bug nevertheless. OK to give this low priority.

In imgui/backends/imgui_impl_sdl2.cpp, in the function ImGui_ImplSDL2_UpdateGamepads(), there's a call to SDL_GameControllerOpen(). But there's no corresponding call to SDL_GameControllerClose().

I've checked the SDL2 implementation of SDL_GameControllerOpen(). Opening the same game controller multiple times increments a reference count (so it's relatively cheap and returns the same result each time). However, without a matching number of calls to SDL_GameControllerClose(), this counter will eventually(*1) overflow. That's probably a bug.

This could be fixed by adding a call to SDL_GameControllerClose() or by calling SDL_GameControllerOpen() just once (I mean not every frame) and reusing the result.

Thanks.

Wouter

(*1) It's a 32-bit signed integer. When doing 60 calls per second, it'll take more than a year to actually overflow.

**Comment by ocornut** [comment]
See discussion at #6559

**Comment by m9710797** [comment]
This issue is indeed a duplicate of 6559. I'll close this one.

**Comment by ocornut** [comment]
Feel free to help in the other issue! Thanks!

**Comment by ocornut** [comment]
Should be fixed by bf1c96d now.
