### ISSUE TITLE
Correctly rendered opengl scene and model in default window not at the right size and position in a imgui window.

### ISSUE THREAD

**Issue by sirlis** [ocornut/imgui#6894]
- **Version/Branch of Dear ImGui:**

Version: latest
Branch: docking

- **Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: gcc-13.1.0
Operating System: windows

- **My Issue/Question:**

I rendered a earth which is supposed to be at the center of the scene and be a standard sphere. It is rendered correctly when rendered purely at the original opengl main window with default frame buffer. After I create an extra frame buffer (+render buffer) and bind the earth to it and put it in the imgui window the scene as well as the earth went wrong (**screenshot 1 and 2**).

- **Screenshots/Video**

**screenshot 1**: correctly rendered scene/model in default window (background, default frame buffer).
![image](https://github.com/ocornut/imgui/assets/12960298/be56792f-b792-4790-978e-ecc854a8ede7)
**screenshot 2**: incorrectly rendered scene/model in imgui window.
Earth is not at the center and there is a small deformation.
![image](https://github.com/ocornut/imgui/assets/12960298/ed62543c-80da-41b2-9c86-82ceea2e7fb9)

- **Standalone, minimal, complete and verifiable example:**

The creation of FBO **before the main render loop** is as follows, and I faced the first problem to define the size of the buffer/texture? according to the imgui window:

```cpp
    // generate frame buffer object
    unsigned int FBO;
    glGenFramebuffers(1, &FBO);
    glBindFramebuffer(GL_FRAMEBUFFER, FBO);
    // generate texture
    unsigned int FBO_textureColorBuffer;
    glGenTextures(1, &FBO_textureColorBuffer);
    glBindTexture(GL_TEXTURE_2D, FBO_textureColorBuffer);
    // glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, _3dpanel_width, _3dpanel_height, 0, GL_RGB, GL_UNSIGNED_BYTE, NULL);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, 879, 578, 0, GL_RGB, GL_UNSIGNED_BYTE, NULL); // <-- how to change the size according to imgui window?
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glBindTexture(GL_TEXTURE_2D, 0);
    // attach it to currently bound framebuffer object
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, FBO_textureColorBuffer, 0);
    // generate a render buffer object
    unsigned int RBO;
    glGenRenderbuffers(1, &RBO);
    glBindRenderbuffer(GL_RENDERBUFFER, RBO);
    glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH24_STENCIL8, 879, 578); // <-- how to change the size according to imgui window?
    glBindRenderbuffer(GL_RENDERBUFFER, 0);
    // attach it to frame buffer
    glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_STENCIL_ATTACHMENT, GL_RENDERBUFFER, RBO);
    if (glCheckFramebufferStatus(GL_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE)
        std::cout << "ERROR::FRAMEBUFFER:: Framebuffer is not complete!" << std::endl;
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
```

The main render loop is as follows. Delete **4 lines with comment** to render the scene in default FBO shows exactly **sceenshot 1**. Ande use the fixed value of window size (e.g., 1280 800 in the code) will produce correct center-rendered earth but will get blurry when fullscreen (4K), apparently.
```c
while(!glfwWindowShouldClose(MainWindow))
{
    //...
    
    glBindFramebuffer(GL_FRAMEBUFFER, FBO);
    glBindTexture(GL_TEXTURE_2D, FBO_textureColorBuffer);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, _3dpanel_width, _3dpanel_height, 0, GL_RGB, GL_UNSIGNED_BYTE, NULL);
    // glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, 1280, 800, 0, GL_RGB, GL_UNSIGNED_BYTE, NULL);
    
    glBindRenderbuffer(GL_RENDERBUFFER, RBO);
    glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH24_STENCIL8, _3dpanel_width, _3dpanel_height);
    // glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH24_STENCIL8, 1280, 800); // <-- how to change the size according to imgui window?
    
    glClearColor(0.0, 0.0, 0.0, 1.0);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    
    
    glBindFramebuffer(GL_FRAMEBUFFER, FBO); // <--- delete to render in default window
    glClearColor(0.0, 0.0, 0.0, 1.0); // <--- delete to render in default window
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // <--- delete to render in default window
    renderOpenGLContent(SunShader, EarthShader, VehicleShader, CelebodyShader,
                        SkyboxShader, Sun, Earth, Moon, Spacecraft,
                        skybox, texture_sun, texture_earth, texture_earth_night,
                        texture_earth_cloud, texture_earth_watermask,
                        texture_earth_normal, texture_moon);
    glBindFramebuffer(GL_FRAMEBUFFER, 0); // <--- delete to render in default window
        
    //...
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();
    
    ImGui::Begin("3D Panel", &window_renderpanel_visible, 0);
    if (ImGui::BeginChild("3DRender"))
    {
        // Get the size of the child (i.e. the whole draw size of the windows).
        ImVec2 wsize = ImGui::GetWindowSize();
        _3dpanel_width = wsize.x;
        _3dpanel_height = wsize.y;
        // Because I use the texture from OpenGL, I need to invert the V from the UV.
        ImGui::Image((void *)(intptr_t)FBO_textureColorBuffer, wsize, ImVec2(0, 1), ImVec2(1, 0));
        ImGui::EndChild();
    }
    ImGui::End();

}
```
in `renderOpenGLContent()` function, I set view and projection matrix as follows:

```c
glm::dmat4 view(1.0);
glm::dmat4 projection(1.0);
if (usCurrentCamera == CAMERA_ORBIT)
{
    view = camera.GetViewMatrix();
    projection = glm::perspective((GLdouble)glm::radians(camera.Fov),
                                  (GLdouble)_3dpanel_width / (GLdouble)_3dpanel_height,
                                  NearPlane,
                                  FarPlane);
}
else if (usCurrentCamera == CAMERA_FIXED)
{
    view = cameraOnboard.GetViewMatrix();
    projection = glm::perspective((GLdouble)glm::radians(cameraOnboard.Fov),
                                  (GLdouble)_3dpanel_width / (GLdouble)_3dpanel_height,
                                  NearPlane,
                                  FarPlane);
}
```

**Comment by PathogenDavid** [comment]
This is not really the right place to ask as this is more of an OpenGL question than a Dear ImGui one.

One thing that stands out to me at a glance is that you aren't calling `glViewport` anywhere I can see, which means you're rendering to your FBO with a window-sized viewport.

Tools like [RenderDoc](https://renderdoc.org/) are invaluable for debugging graphics code.

**Comment by sirlis** [comment]
> This is not really the right place to ask as this is more of an OpenGL question than a Dear ImGui one.
> 
> One thing that stands out to me at a glance is that you aren't calling `glViewport` anywhere I can see, which means you're rendering to your FBO with a window-sized viewport.
> 
> Tools like [RenderDoc](https://renderdoc.org/) are invaluable for debugging graphics code.

It really helps, thank you. And apologize for the inappropriately placed question.

**Comment by PathogenDavid** [comment]
No worries, thanks for thoroughly filling out the issue template!
