### ISSUE TITLE
Comments refer to non-existent function `GetScreenCursorPos`

### ISSUE THREAD

**Issue by tom-seddon** [ocornut/imgui#6898]
**Version/Branch of Dear ImGui:**

Version: 1.90-wip
Branch: master (also affects docking branch, which I was using when I noticed this)
Commit: a63e2f0a33261562e7111151f6e37780609f4720

**My Issue/Question:**

Two references in comments to `GetScreenCursorPos`, which I'm guessing should be `GetCursorScreenPos`:

https://github.com/ocornut/imgui/blob/a63e2f0a33261562e7111151f6e37780609f4720/imgui.h#L357
https://github.com/ocornut/imgui/blob/a63e2f0a33261562e7111151f6e37780609f4720/imgui.h#L358

**Comment by ocornut** [comment]
Thank you! I have fixed this typo in 0dd756bceb64757be80f33155287b06cf806d69f and used to occasion to shuffle some of those comments and encourage people to use absolute coordinates.
