### ISSUE TITLE
Remove the side of the window's border 

### ISSUE THREAD

**Issue by greeneyes1337** [ocornut/imgui#6899]
Hello,

I am trying to re-create this winforms login page in Dear ImGui: https://www.youtube.com/watch?v=vYDyGxoq9JU

But when I try to create the square for the buttons on the left of the application, the window border makes it look strange (even though the start position for this rectangle is at -10, -10): 

![image](https://github.com/ocornut/imgui/assets/145867345/cb180e97-59c4-40c3-a743-392adf232437)

I have set the window to have a border width of 0. This still happens. How can I fix this?
Thanks

**Comment by ocornut** [comment]
Hello, please read [Contributing Guidelines](https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md) if you would like to receive help.

**Comment by ocornut** [comment]
Closing as lacking information. Please don't open a duplicate issue, you can add necessary details here and we can consider to reopen when added.
