### ISSUE TITLE
Inconsistency between p_open Functionality and Documentation in BeginPopupModal

### ISSUE THREAD

**Issue by sakiodre** [ocornut/imgui#6900]
**Version/Branch of Dear ImGui:**

Version: 1.89.9 WIP
Branch: master

**My Issue/Question:**

The comment for `BeginPopupModal`, added in commit [`#f1c75964`](https://github.com/ocornut/imgui/commit/f1c75964#diff-cee9beb740469eb5192dfe94aaee7320932590adade9d9b1d2ee392ac2e1e88cR6611), mentions that:
> popup visibility status is owned by Dear ImGui (and manipulated with e.g. OpenPopup) so the actual value of *p_open is meaningless here.

However, when `p_open` is set to false when passed to the function, [this condition](https://github.com/ocornut/imgui/blob/2c07d581de7396753ea873fb765ffc7d411fecad/imgui.cpp#L10603) evaluates to false, which returns false and hides the popup. Tracing back through the git history, this if block dates back to [`#8c790a32`](https://github.com/ocornut/imgui/commit/8c790a32#diff-cee9beb740469eb5192dfe94aaee7320932590adade9d9b1d2ee392ac2e1e88cR3250) when `p_open` was first added.

The code clearly indicates that if `p_open` is false, the popup will not be displayed, contradicting the comment. Could you clarify the intended behavior?

**Standalone, minimal, complete and verifiable example:**
```cpp
ImGui::Begin("window");

if (ImGui::Button("open"))
    ImGui::OpenPopup("popup window");

bool p_open = false;

if (ImGui::BeginPopupModal("popup window", &p_open))
{
    ImGui::EndPopup();
}

ImGui::End();
```

**Comment by ocornut** [comment]
I think we should preserve the current behavior and amend the comment.

Note however it is inconsistent with `Begin()` with currently _DOES_ ignore the value of `*p_open` (I don't recall the reason presently, in believe in theory `Begin()` could assert to prevent misuse). Either way the current popup behavior is the desirable behavior.
