### ISSUE TITLE
ImGui::SeparatorText() followed by HelperMarker("xxx") at same line appears strange.

### ISSUE THREAD

**Issue by sirlis** [ocornut/imgui#6902]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: all

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp 
Compiler: any
Operating System: windows

**My Issue/Question:**

`ImGui::SeparatorText()` followed by `HelperMarker("xxx")` at same line appears strange.

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/12960298/e10e5f5c-9c3a-4469-b589-5919cdb0c6a9)

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
ImGui::SeparatorText("Resolution");
ImGui::SameLine();
HelpMarker("Will take effect at next startup.");
```

**Comment by ocornut** [comment]
They are not possible to combine at `SeparatorText()` draws a line after it.
I did however consider this idiom and imgui_internal.h' s `SeparatorTextEx()` adds an `float extra_w` parameter which may be leverage for this purpose, if you pass the width for a following item ahead of time:

```cpp
ImGui::SeparatorTextEx(0, "Resolution", NULL, ImGui::CalcTextSize(" (?)").x);
ImGui::SameLine();
HelpMarker("Will take effect at next startup.");
```

**Comment by sirlis** [comment]
> They are not possible to combine at `SeparatorText()` draws a line after it. I did however consider this idiom and imgui_internal.h' s `SeparatorTextEx()` adds an `float extra_w` parameter which may be leverage for this purpose, if you pass the width for a following item ahead of time:
> 
> ```c++
> ImGui::SeparatorTextEx(0, "Resolution", NULL, ImGui::CalcTextSize(" (?)").x);
> ImGui::SameLine();
> HelpMarker("Will take effect at next startup.");
> ```

Thank you. Solved.
