### ISSUE TITLE
Window resizing when dragged out of monitor (with flags used) (Up Direction)

### ISSUE THREAD

**Issue by greeneyes1337** [ocornut/imgui#6903]
**Version/Branch of Dear ImGui:**

Version: Current ( v1.89.9 )
Branch: Master

**Back-end/Renderer/Compiler/OS**

Back-ends: Direct X 11
Operating System: Windows

**My Issue/Question:**

Hello, I am trying to create a login forum. I have noticed that wen dragged out of screen, my window resizes (not horizontally, vertically, and down, but up). I am using these flags: 

ImGui::Begin(
    "winforms login recreation",
    nullptr,
    ImGuiWindowFlags_NoResize |
    ImGuiWindowFlags_NoNav |
    ImGuiWindowFlags_NoMove |
    ImGuiWindowFlags_NoTitleBar |
    ImGuiWindowFlags_NoCollapse |
    ImGuiWindowFlags_NoDecoration
);

and I am using these: 

ImGui::SetNextWindowPos(ImVec2(0, 0));
ImGui::SetNextWindowSize(ImVec2(SCREEN_WIDTH, SCREEN_HEIGHT));
ImGui::SetNextWindowSizeConstraints(ImVec2(SCREEN_WIDTH, SCREEN_HEIGHT), ImVec2(SCREEN_WIDTH, SCREEN_HEIGHT));

SCREEN_WIDTH AND SCREEN_HEIGHT are both constants. there is nothing in the window that uses cursor pos. (No custom sizing and things of that nature)

I have also tried to remove the WM_SIZE from my (ocornut's) WndProc. That didn't work.

**Screenshots/Video**

**Standalone, minimal, complete and verifiable example:**

// Handle window resize (we don't resize directly in the WM_SIZE handler)
if (g_ResizeWidth != 0 && g_ResizeHeight != 0)
{
    CleanupRenderTarget();
    g_pSwapChain->ResizeBuffers(0, g_ResizeWidth, g_ResizeHeight, DXGI_FORMAT_UNKNOWN, 0);
    g_ResizeWidth = g_ResizeHeight = 0;
    CreateRenderTarget();
}

// Start the Dear ImGui frame
ImGui_ImplDX11_NewFrame();
ImGui_ImplWin32_NewFrame();
ImGui::NewFrame();

ImGui::SetNextWindowPos(ImVec2(0, 0));
ImGui::SetNextWindowSize(ImVec2(SCREEN_WIDTH, SCREEN_HEIGHT));
ImGui::SetNextWindowSizeConstraints(ImVec2(SCREEN_WIDTH, SCREEN_HEIGHT), ImVec2(SCREEN_WIDTH, SCREEN_HEIGHT));

ImGui::Begin(
    "winforms login recreation",
    nullptr,
    ImGuiWindowFlags_NoResize |
    ImGuiWindowFlags_NoNav |
    ImGuiWindowFlags_NoMove |
    ImGuiWindowFlags_NoTitleBar |
    ImGuiWindowFlags_NoCollapse |
    ImGuiWindowFlags_NoDecoration
);

 

//Sidebar

ImGui::GetWindowDrawList()->AddRectFilled(
    ImVec2(0, 0),
    ImVec2(300, 800),
    SIDEBAR,
    0.f
);

//debug purposes only

if (GetAsyncKeyState(VK_RETURN))
{
    ImGui::Begin("debug");
    ImGui::SliderInt("debug x1", &ui::a, -10000, 10000);
    ImGui::SliderInt("debug y1", &ui::aa, -10000, 10000);
    ImGui::SliderInt("debug x2", &ui::b, -10000, 10000);
    ImGui::SliderInt("debug y2", &ui::bb, -10000, 10000);
    ImGui::End();
}

ImGui::End();

This could also be something I am handling/not handling (win32 issue) so if it is please let me know. 

Thank you for your help!

**Comment by greeneyes1337** [comment]
I'm so sorry I forgot the video!

https://streamable.com/2vvyae

**Comment by ocornut** [comment]
I'm pretty sure none of the code you posted is culprit and you may be omitting something else.

**Comment by greeneyes1337** [comment]
Im not really sure what you mean, this is my main loop... Also what im trying to make is this: https://www.youtube.com/watch?v=vYDyGxoq9JU

**Comment by ocornut** [comment]
I mean the code you posted doesn’t have issue. The issue is in code that you didn’t post.
