### ISSUE TITLE
MultiView: Mouse Cursor Position Shifting in PopupModal

### ISSUE THREAD

**Issue by DKingAlpha** [ocornut/imgui#6904]
**Version/Branch of Dear ImGui:**

Version: latest
Branch: docking (viewport)

**Back-end/Renderer/Compiler/OS**

Back-ends: `imgui_impl_glfw.cpp` + `imgui_impl_opengl3.cpp`
Operating System: Arch Linux, KDE Plasma + X11 session
Screen Height: 1440

**My Issue/Question:**

In multiview mode, if a PopupModal's whole content height exceed screen height, the modal will occupy all the screen height and apply scrollbar inside. However, **in some occasions** the PopupModal status in `imgui.ini`  looks like this
```
[Window][Viewport PopupModal]
ViewportPos=1482,-143
ViewportId=0x9319ECC9
Size=238,1434     # screen height minus some padding I guess
Collapsed=0
```
This will make imgui's virtual cursor looks like shifting  143 pixels from actual mouse position.

Values of ViewportPos looks random to me. It's likely to happen when I try to drag the PopupModal title around.

**Screenshots/Video**
![Screenshot_20231006_051108](https://github.com/ocornut/imgui/assets/15340687/611febad-d0eb-41c2-8af7-88ce1a9258d7)

Code to reproduce:
```cpp

    // set next window size if necessary

    if (ImGui::Begin("CheatNG", &main_window_open)) {
        // test viewport popup
        {
            bool viewport_popupmodal_open = true;
            if (ImGui::BeginPopupModal("Viewport Popup"_x, &viewport_popupmodal_open)) {
                for (int i=0; i<100; i++) {
                    ImGui::Selectable("Hello from Viewport Popup");
                }
                ImGui::EndPopup();
            }
            if (ImGui::Button("Open Test Popup")) {
                ImGui::OpenPopup("Viewport Popup");
            }
        }
    }
    ImGui::End();

```

**Comment by ocornut** [comment]
This seems unrelated to modals and the same as #2117, WM not honoring a requested position which throws off dear imgui off. It’s documentsd in that thread but since no Linux users are interested in spending the time to **thoroughly** investigate what it takes to fix this, its been unfixed for years.
