### ISSUE TITLE
The modal window is always positioned behind other windows when the app is opened.

### ISSUE THREAD

**Issue by yangkangnevergiveup** [ocornut/imgui#6912]
![image](https://github.com/ocornut/imgui/assets/44560513/531bf118-92d1-4116-9a43-34cbe1244a94)
As expected, the modal window should be on top of the main window, but I am unsure how to achieve that.

system: macOS 13.5.2.
imgui: 1.89.7.

**Comment by ocornut** [comment]
Please read https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md carefully and provide more details, config options, repro code, video etc. We can't consider issues without those details.

**Comment by yangkangnevergiveup** [comment]
yeah, this bug was caused by my low-level mistake, so just kindly ignore it.
