### ISSUE TITLE
Skin support / example?

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [ocornut/imgui#6913]
I know imgui supports styles, but I was wondering if anyone had any success applying a skin? If there are any third party addons or examples that would be great. Or advice about how i could go about this myself.

**Comment by PathogenDavid** [comment]
Dear ImGui's current styling system is relatively limited, and as a result most UIs created with it have a similar feel. 

That being said, some people accomplish quite a bit with what's available (sometimes with copious amounts of custom drawing and widgets.) [The gallery threads](https://github.com/ocornut/imgui/labels/gallery) are a good place to find examples of this. Here's some random ones I found/remembered:

* https://github.com/ocornut/imgui/issues/5886#issuecomment-1537522567
* https://github.com/ocornut/imgui/issues/5886#issuecomment-1552739132
* https://github.com/ocornut/imgui/issues/3488#issuecomment-702666334
* https://github.com/ocornut/imgui/issues/2847#issuecomment-585179499
* https://github.com/ocornut/imgui/issues/6478#issuecomment-1712234029

Another useful thread is the [styles/themes thread](https://github.com/ocornut/imgui/issues/707), which provides a multitude of simpler examples.

> If there are any third party addons

There's a fairly exhaustive [list of third-party extensions on the wiki](https://github.com/ocornut/imgui/wiki/Useful-Extensions). They're mostly for custom widgets, but maybe they can help you accomplish the vibe you're wanting to go for.

> Or advice about how i could go about this myself.

In general Dear ImGui's widget rendering is fairly limited, for example here's the code that renders buttons:

https://github.com/ocornut/imgui/blob/5053d79a2431d2367b55a805a394af45d532952b/imgui_widgets.cpp#L706-L709

https://github.com/ocornut/imgui/blob/5053d79a2431d2367b55a805a394af45d532952b/imgui.cpp#L3439-L3451

`ButtonEx` calls down to `RenderFrame` more or less just draws a couple (rounded) rectangles with solid colors. However, you'll find that many widgets are implemented using `RenderFrame`, so depending on what you're wanting to accomplish you might be able to just modify `RenderFrame` and call it a day. 

There is no general guide to customizing Dear ImGui beyond what `ImGuiStyle` provides, you'll need to get comfortable digging around in Dear ImGui's source code.

**Comment by GamingMinds-DanielC** [comment]
Depending on the effect you want, you could do a lot without customizing widgets already. Instead of rendering to the back buffer directly, you could render to a texture and use some custom post processing. Together with custom styles (f.e. to color code for post processing effects) you could do some interesting stuff. Or you could use your own backend with custom shaders. This may be enough as long as you can limit yourself to sampling based on the screen position. If not, custom widgets are the way to go.

**Comment by ocornut** [comment]
Closing as answered, let us know if you have other questions!
