### ISSUE TITLE
InputText with popup

### ISSUE THREAD

**Issue by pavledev** [ocornut/imgui#6915]
Version/Branch of Dear ImGui:

Version: 1.90 WIP
Branch: docking

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_win32.cpp + imgui_impl_dx11.cpp
Compiler: VS2022
Operating System: Windows 10

My Issue/Question:

Code for rendering InputText with popup from here https://github.com/ocornut/imgui/issues/718#issuecomment-1249822993 causes `IM_ASSERT(window == window->RootWindow);` assert to fail https://github.com/ocornut/imgui/blob/docking/imgui.cpp#L7693 after popup and window are closed

**Comment by ocornut** [comment]
I think the assert (added in 936f53229) was incorrect here, pushed fix 0860671.
I will work on a regression test as this is rather subtle / fringe case to combine the Popup and Child flags and not tested enough.
Thank you!
