### ISSUE TITLE
Why does ImGui attempt to free memory that I (the user) have created?

### ISSUE THREAD

**Issue by johannesugb** [ocornut/imgui#6916]
**Version/Branch of Dear ImGui:**

Version: v1.89.9
Branch: _master_

**Back-end/Renderer/Compiler/OS**

Back-ends: `imgui_impl_glfw.cpp` + `imgui_impl_vulkan.cpp` 
Compiler: VS version v17.7.4, MSVC version 19.37.32824
Operating System: Windows 10, Windows 11

**My Issue/Question:**

I am using `AddFontFromMemoryTTF` to successfully load a TTF font from memory. What I don't understand is that I am not the one responsible for deleting the allocated memory, as it appears. This looks like a violation of responsibility principles. 

Here's how I load the TTF font:

```cpp
ImGuiIO& io = ImGui::GetIO();
io.Fonts->Clear();
auto  font_cfg = ImFontConfig();
ImFormatString(font_cfg.Name, IM_ARRAYSIZE(font_cfg.Name), "%s, %.0fpx", "MyFont.ttf", 13.f);
uint8_t* data= new uint8_t[] { 0x0, 0x1, 0x0, 0x0, 0x0, 0x11, 0x1, 0x0, 0x0, 0x4, ...  };
size_t data_size = 273900;
io.Fonts->AddFontFromMemoryTTF(data, (int)data_size, fontSize, &font_cfg, nullptr);
```

The crucial part here is the line where I allocate the font data: `uint8_t* data= new uint8_t[] { ... };`

Now, I would expect that I (the user of ImGui) has to delete `data` after uploading the fonts (which in my case means after `ImGui_ImplVulkan_CreateFontsTexture` and `ImGui_ImplVulkan_DestroyFontUploadObjects` and using a fence for these operations to have completed) and execute a `delete [] data;` afterwards.

**But** if I execute that `delete [] data`, then my compiler points out that that ImGui attempts to free that memory again on its own, namely here: 
```cpp
static void    FreeWrapper(void* ptr, void* user_data)        { IM_UNUSED(user_data); free(ptr); }
```
which is in `imgui.cpp`, line `1146`.

The comments indicate that I could "SetAllocatorFunctions() to change them"... but why should I actually? I only want to free that data on my own and not have ImGui free my data. 

What are your thoughts on this?         
What is the intended way of handling this?

**Comment by ocornut** [comment]
See docs: [Loading Font Data from Memory](https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#loading-font-data-from-memory)

```cpp
ImFont* font = io.Fonts->AddFontFromMemoryTTF(data, data_size, size_pixels, ...);
```

>IMPORTANT: AddFontFromMemoryTTF() by default transfer ownership of the data buffer to the font atlas, which will attempt to free it on destruction. This was to avoid an unnecessary copy, and is perhaps not a good API (a future version will redesign it). If you want to keep ownership of the data and free it yourself, you need to clear the FontDataOwnedByAtlas field:

```cpp
ImFontConfig font_cfg;
font_cfg.FontDataOwnedByAtlas = false;
ImFont* font = io.Fonts->AddFontFromMemoryTTF(data, data_size, size_pixels, &font_cfg);
```

**Comment by johannesugb** [comment]
Sorry for not reading the docs better & thank you. 🙏
