### ISSUE TITLE
emscripten rendering should keep the aspect ratio

### ISSUE THREAD

**Issue by ypujante** [ocornut/imgui#6918]
I built the example program `example_emscripten_wgpu` without any issue.

When I load it in my browser (Chrome), I noticed that as the window gets resized the ratio is not preserved, thus leading to a situation like this screenshot

<img width="488" alt="Screenshot 2023-10-12 at 11 36 34" src="https://github.com/ocornut/imgui/assets/357116/e739ff5f-2d3e-4b68-9661-62c55a62336f">

Obviously this is an extreme scenario, but the reason why I am reporting it is because the first time I opened it in my browser, my browser was not 1280x720 and as a result, the text/font looked really bad. So it seems that something was broken with the build or rendering. Also, it is not really easy to make the browser window exactly 1280x720 to have no artifacts due to stretching.

Note that I cannot copy/paste the build info because "Copy to clipboard" does not seem to work in this environment.

It is the latest commit on the docking branch `83c433682883aaa6f9583a4a84d1ae4bd8d1e977` built on macOS (13.5.2) with emscripten

```text
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 3.1.45 (ef3e4e3b044de98e1811546e0bc605c65d3412f4)
```

This is the "about" window, with a more "normal" size, yet the font rendering does not look very good.

<img width="513" alt="Screenshot 2023-10-12 at 11 47 56" src="https://github.com/ocornut/imgui/assets/357116/18f42516-5e01-4b9c-a89c-d02a95818d38">

**Comment by ocornut** [comment]
I think this is covered by #6751

**Comment by ypujante** [comment]
When I get a change I will try to apply the changes included in this other issue and report back. Thanks

**Comment by ypujante** [comment]
I confirm that the patch from #6751 fixes this issue.
