### ISSUE TITLE
ImGUI events' issues

### ISSUE THREAD

**Issue by aSongDai** [ocornut/imgui#6927]
**Version/Branch of Dear ImGui:**

Version: 1.89.3 WIP

**Back-end/Renderer/Compiler/OS**

Operating System: Windows

**My Issue/Question:**

I use the showdemowindow function in imgui.h and it run well. but if i have some events in the window such as click, it will be broken. And the process by which this error is woken up is: Update()[this is my function]->NewFrame()->XXXBehavior()/UpdateXXX()->ClearActiveID()->SetActiveID(). The ClearActiveID function invoke SetActiveID function and give it a nullptr. And the nullptr->DC will break the application. But I don't know how to deal with it, please give me a hand. 

```
ImGui_ImplOpenGL3_NewFrame();
ImGui::NewFrame();	
	
static bool show = true;
ImGui::ShowDemoWindow(&show);

ImGui::Render();
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
```

**Comment by ocornut** [comment]
Hello,
Please provide a detailed callstack. We can’t guess what your “XXX” stands for.
Which platform backend are you using and did you call the equivalent _NewFrame() call for it ?

**Comment by aSongDai** [comment]
Version: 1.89.3 WIP

Back-end/Renderer/Compiler/OS
imgui_impl_opengl3.cpp
imgui_impl_opengl3.h

Thank you, 
Such as if i move the ImGuiwindow, my application will invoke ImGui::NewFrame() -> ImGui::UpdateMouseMovingWindowNewFrame() -> ClearActiveID() -> SetActiveID(). And the ClearActiveID function will give a nullptr to SetActiveID function, this is the ImGui::SetActiveID() in version 1.89.3:
```
void ImGui::SetActiveID(ImGuiID id, ImGuiWindow* window)
{
    ImGuiContext& g = *GImGui;
    for (int i = 0 ; i < window->DC.Layouts.Data.Size; i++)
    {...}
    ...
}
```
And now I have commented out this piece of code, and my application run well.

**Comment by ocornut** [comment]
This code doesn’t exist in any standard dear imgui branches. You are using a modified version which we can’t support.
