### ISSUE TITLE
Inconsistent rendering of imgui rendering fonts

### ISSUE THREAD

**Issue by blackchicken20** [ocornut/imgui#6928]
```
Dear ImGui 1.89.6 WIP (18953)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=201703
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 2048,2048
io.DisplaySize: 1264.00,845.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.89.6
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Compiler: msvc
Operating System: windows

**My Issue/Question:**

Inconsistent rendering of imgui rendering fonts

I am using Song typeface (simsun. ttc), and using the DrawFont function in dx9 resulted in a serious inconsistency between rendering and imgui.

**Screenshots/Video**

![Snipaste_2023-10-15_21-19-05](https://github.com/ocornut/imgui/assets/58726436/eb0001c5-4dd4-457c-9c78-b20c78dc80e3)

![Snipaste_2023-10-15_21-19-30](https://github.com/ocornut/imgui/assets/58726436/c0b24246-0e37-410a-8b21-9b1bd218dcdb)

left：dx9
right: imgui

There are two different exe on the left and right sides

**Standalone, minimal, complete and verifiable example:** 
```
in dx9 project
    D3DXFONT_DESC FontDescription{};
    ZeroMemory(&FontDescription, sizeof(D3DXFONT_DESC));
    wcscpy(FontDescription.FaceName, L"宋体");
    FontDescription.Height = 15;
    FontDescription.Quality = 5;
    FontDescription.OutputPrecision = 0;
    D3DXCreateFontIndirectW(device, &FontDescription, &ppfont);
    INT length = (INT)wcslen(s);
    RECT r = { 100,100,100,100 };
    ppfont->DrawTextW(nullptr, L"设置", length, &r, 0, D3DCOLOR_ARGB(255, 255, 255, 255));

in imgui.cpp
    io.Fonts->AddFontDefault();
    ImFontConfig fontConfig;
    fontConfig.MergeMode = true;
    fontConfig.OversampleH = 1;
    fontConfig.OversampleV = 1;
    fontConfig.PixelSnapH = 1;
    fontConfig.RasterizerMultiply = 2.0f;

    ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\simsun.ttc", 15.0f, &fontConfig, io.Fonts->GetGlyphRangesChineseSimplifiedCommon());
    ImGui::Text(u8"设置");
```
my english is poor. i use translate engine.sorry.

**Comment by ocornut** [comment]
The default truetype renderer provided by stb_truetype doesn’t behave well enough for small size. You can try using freetype + misc/imgui_freetype renderer for higher quality as this path will support font hinting.

**Comment by blackchicken20** [comment]
I used FreeType, but the results were even worse.

```  
    ImFontConfig fontConfig;
    fontConfig.MergeMode = true;
    fontConfig.OversampleH = 2;
    fontConfig.OversampleV = 1;
    fontConfig.RasterizerMultiply = 1.0f;
    fontConfig.FontBuilderFlags |= ImGuiFreeTypeBuilderFlags_Monochrome;  
    ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\simsun.ttc", 16.0f, &fontConfig, io.Fonts->GetGlyphRangesChineseSimplifiedCommon());
    ```

![Snipaste_2023-10-16_00-43-27-A](https://github.com/ocornut/imgui/assets/58726436/73a1015e-ca82-4ba7-bb34-ff4712d0bbe9)

    
![Snipaste_2023-10-16_00-43-46-B](https://github.com/ocornut/imgui/assets/58726436/ce18cdf3-7106-45a7-9b34-cfef29cbc87a)

I found some information through search engines.
It seems to be related to this.

`http://kasicass.blog.163.com/blog/static/3956192009125112338305/`

`对于普通的 TrueType，都是通过样板缩放得到特定大小的 glyph 的。但为了让较小的字符看起来也非常清晰，字体中的某些字号可能会是特殊制作的点阵字符(fixed size)，比如 windows 的宋体(simsun.ttf/ttc)中的 9pt~12pt`

`For ordinary TrueTypes, specific sized glyphs are obtained by scaling through templates. But in order to make smaller characters appear very clear, some font sizes may be specially made fixed sizes, such as 9pt~12pt in Windows' Simsun. ttf/ttc`

**Comment by blackchicken20** [comment]
I solved it.

```
    fontConfig.FontBuilderFlags |= ImGuiFreeTypeBuilderFlags_Bitmap;
    fontConfig.FontBuilderFlags |= ImGuiFreeTypeBuilderFlags_Monochrome;  
```

thanks imgui.
