### ISSUE TITLE
DirectX ImGui Mouse Interaction Not Working 

### ISSUE THREAD

**Issue by LaymPuppeh** [ocornut/imgui#6932]
**Version/Branch of Dear ImGui:**

Version: v1.89.9
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx11.cpp + imgui_impl_win32.cpp
Operating System: Windows 11

**My Issue/Question:**

I am unable to interact with my newly created ImGui windows
It's a little difficult to explain and also I am new to DirectX 11 and ImGui so sorry if i don't know much.
It allows me to hover over elements and register the hover, but it doesn't let me move or scale my Imgui windows. Is this a side effect of the docking branch?
If anyone can help it would be highly appreciated

**Screenshots/Video**

*A video showing the error*
https://github.com/ocornut/imgui/assets/65513977/a2683aee-f72a-4343-8e8c-ccc2123023b0

**example of some of my code**
```
        ImGui::SetNextWindowSize(ImVec2(500, 750));
        //ImGui::ShowStyleSelector("Style Selector"); commented out because it was behind the main window.
        ImGui::Begin("Chrono Engine Properties");
        ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / io.Framerate, io.Framerate);
        if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)
            
        ImGui::End();

        ImGui::Render();
        ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
```
**The initalization**
```
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;     // Enable Keyboard Controls
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;      // Enable Gamepad Controls
    io.DisplayFramebufferScale = ImVec2(1920, 1080); // Set appropriate scale factors
    ImGui::StyleColorsDark();
    ImGui_ImplWin32_Init(hwnd);
    ImGui_ImplDX11_Init(d3d11Device, d3d11DeviceContext);
```

Thank you!

**Comment by ocornut** [comment]
See https://github.com/ocornut/imgui/wiki/Getting-Started#example-if-you-are-using-raw-win32-api--directx11

I guess you forgot the step of calling `ImGui_ImplWin32_WndProcHandler()` in your WndProc handler.

**Comment by LaymPuppeh** [comment]
Thank you @ocornut !
