### ISSUE TITLE
The mouse coordinates are shifted when you drag the window to the right or lower-right corner of the screen

### ISSUE THREAD

**Issue by houchr** [ocornut/imgui#6934]
**Version/Branch of Dear ImGui:**

Version: v1.89.x
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_sdl3.cpp + imgui_impl_opengl3.cpp or imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp or imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: gcc
Operating System: debian/ubuntu 22.04 and kylin desktop v10 sp1

**My Issue/Question:**

The mouse coordinates are shifted(offset) when you drag the window to the right edge or bottom-right corner of the screen。as the figure shows，the blue arrow is the actual position of the mouse, and the orange arrow is the mouse position it responds to, with a big deviation. When I try to move the window, as long as it moves successfully, the mouse no longer shifts(offset). 

The shifted(offset) mouse causes incorrect operation, this problem also occurs when using the imgui demo。

**Screenshots/Video**

![bf4175ea7b0b1c7196d18865ad814f9](https://github.com/ocornut/imgui/assets/3382139/8e2fd073-c1fd-447f-ad80-c71cb6904bff)

**Standalone, minimal, complete and verifiable example:**
```
// Here's some code anyone can copy and paste to reproduce your issue
this problem also occurs when using the imgui demo。
please use imgui demo, open a window, and drag it to right edge or bottom-right coner of screen。
```

**Comment by houchr** [comment]
By the way, the window shouldn't be too small

**Comment by ocornut** [comment]
Same question same answer as #6904
Disable multi-viewports on Linux or Wayland for now.
