### ISSUE TITLE
GL/glew.h static linking macro redefinition

### ISSUE THREAD

**Issue by Intervel** [ocornut/imgui#6935]
what i already tried to fix this issues :
`#define IMGUI_IMPL_OPENGL_LOADER_CUSTOM`

![header](https://github.com/ocornut/imgui/assets/86478025/8b4eac4a-5e58-4f3c-ba4f-957fee34de80)

macro redefinition still occurs.

i compile ImGui library as static. 
and i also compile glew as static too.

![lib](https://github.com/ocornut/imgui/assets/86478025/f8ac386a-ee5c-44e3-8be6-de9c4c992a76)

then i define it :
`#define GLEW_STATIC`
![define](https://github.com/ocornut/imgui/assets/86478025/2974450d-5f14-4cd9-91d7-be829a448b6e)

![static](https://github.com/ocornut/imgui/assets/86478025/a037c345-9bcc-46ea-9cce-52583f48ed0b)

is this because i staticlly link glew?

**Comment by ocornut** [comment]
You shouldn’t include our loader header file, it’s only to be used to us.

**Comment by ocornut** [comment]
You also don’t need to uss IMGUI_IMPL_OPENGL_LOADER_CUSTOM, what are you trying to achieve using it? Global defines shouldn’t be defined locally but in project settings or in your imconfig file but either way you shouldn’t need it.

Let our imgui_impl_opengl3.cpp code use its loader, and have your code use whatever loader you like.

**Comment by Intervel** [comment]
![ProjectY 10_17_2023 2_11_05 PM](https://github.com/ocornut/imgui/assets/86478025/b8840db8-a1b6-45f8-86c8-7a3c125c468f)

thanks @ocornut :) got it working! also thank you so much for making this awesome tool free to use! :)
