### ISSUE TITLE
Creating a colour palette (grid of pre-defined colours to select from)

### ISSUE THREAD

**Issue by xcodedave** [ocornut/imgui#694]
Hi,

I'm having trouble achieving what I'd like, which is to build a grid of clickable coloured rectangles. This is to use as an on-screen colour palette selection tool. Perhaps my approach needs to change, as I'm basically trying to position invisible buttons over the coloured rectangles I'm adding to the draw list. This doesn't seem to work though, and I'm not sure where I'm going wrong? Perhaps I've misunderstood the coordinate space adding buttons is working with, or perhaps I have misunderstood how the position setting affects button creation? Any help would be most appreciated. Below is the code I have so far:

    ImGui::BeginChild("colors", child_size, true);
    
    //build a list of colour palette cells
    for (uint32_t color_column = 0; color_column<num_columns; color_column++)
    {
    	for (uint32_t color_row = 0; color_row<num_rows; color_row++)
    	{
    		//make sure we only render 0-255 from the palette, so as not to overflow the buffer
    		if (cell_num<256)
    		{
    			//work out the rectangle bounds for the palette cell
    			float top = color_row * padded_cell_size;
    			float left = color_column * padded_cell_size;
    			float bottom = top + cell_size;
    			float right = left + cell_size;
    			
    			//get the 32bit colour from the loaded uint8palette buffer
    			uint32_t color_index = ((color_row*num_columns)+color_column)*3;
    			uint8_t r = uint8Palette[color_index];
    			uint8_t g = uint8Palette[color_index+1];
    			uint8_t b = uint8Palette[color_index+2];
    			uint8_t a = 255;
    			uint32_t rgba = (a<<24) + (r<<16) + (g<<8) + b;
    	
    			//draw the rectangle filled with this colour, representing a single palette cell
    			ImGui::GetWindowDrawList()->AddRectFilled(ImVec2(pos.x + left, pos.y + top), ImVec2(pos.x + right, pos.y + bottom), rgba);

    			//create an ID for the invisible button
    			char colorCellId[10];
    			sprintf(colorCellId, "cell##%i", cell_num);
    			
    			//set the position of the button to the cursor_pos
                        ImVec2 cursor_pos = ImVec2(pos.x + left, pos.y + top);
    			ImGui::SetCursorPos(cursor_pos);
    			
    			//check if the user clicked the invisible button, and log the palette index
    			if (ImGui::InvisibleButton(colorCellId, ImVec2(padded_cell_size, padded_cell_size)))
    			{
    				printf("clicked %i\n", cell_num);
    			}
    			
    		}
    		
    		cell_num ++;
    			
    	}
    	
    }
    			
    ImGui::EndChild();

**Comment by ocornut** [comment]
Just to clarify:
- All positions used with the DrawList api uses screen coordinates
- Whereas `SetCursorPos` uses coordinates relative to the window. However you can also uses `SetCursorScreenPos` to pass in screen coordinates.

What you doing should work (but I haven't checked in detail).
You can also uses ImageButton() using a tint color and ImGui::GetFontTexUvWhitePixel() as both UV to have a solid color button and combine both. But it'd be good to solve the problem with your current approach if only to make sure you understand it.

Also there's an IM_COL32 helper macro.
```
ImU32 rgba = IM_COL32(uint8Palette[color_index], uint8Palette[color_index+1], uint8Palette[color_index+2], 255);
```

One oddity is that color types are rather inconsistent, ImageButton only takes ImVec4/float4 perhaps going to change/fix that eventually.

**Comment by xcodedave** [comment]
Thanks for the useful info regarding coordinate spaces; I modified my `SetCursorPos` to be in screen space using `SetCursorScreenPos` to match the DrawList api, and this resolved my issue :)
RE: API methods using colours, perhaps you could have overloaded methods for any method which accepts colours? Though I do realise it's yet another thing to maintain! :)

**Comment by ocornut** [comment]
Cool, closing this then :)

> RE: API methods using colours, perhaps you could have overloaded methods for any method which accepts colours? Though I do realise it's yet another thing to maintain! :)

Yes I may probably just end up doing that, won't be a big issue. I want to wait until I have a pass at providing new color themes because I also want to tweak underlying data structures (precompute packed values given current global, currently we do a lot of float4 to u32 conversion for rendering).

**Comment by mgerhardy** [comment]
Posting my version in the hope that it might be useful for someone else, too.

```c++
static bool palettePanel(const char *title, const ImVec4* colors, int nColors, const ImVec2 &colorButtonSize, int *selectedPalIdx, int highlightPalIdx = -1, ImGuiWindowFlags flags = 0u) {
	if (ImGui::Begin(title, nullptr, flags)) {
		const ImVec2 &pos = ImGui::GetCursorScreenPos();
		bool colorHovered = false;
		ImDrawList* drawList = ImGui::GetWindowDrawList();
		const ImDrawListFlags backupFlags = drawList->Flags;
		drawList->Flags &= ~ImDrawListFlags_AntiAliasedLines;

		const ImU32 redColor = ImGui::GetColorU32(core::Color::Red);
		const ImU32 yellowColor = ImGui::GetColorU32(core::Color::Yellow);
		const ImU32 darkRedColor = ImGui::GetColorU32(core::Color::DarkRed);

		const float windowWidth = ImGui::GetWindowContentRegionMax().x;
		ImVec2 globalCursorPos = ImGui::GetCursorScreenPos();
		for (int palIdx = 0; palIdx < nColors; ++palIdx) {
			const float borderWidth = 1.0f;
			const ImVec2 v1(globalCursorPos.x + borderWidth, globalCursorPos.y + borderWidth);
			const ImVec2 v2(globalCursorPos.x + colorButtonSize.x, globalCursorPos.y + colorButtonSize.y);

			drawList->AddRectFilled(v1, v2, ImGui::GetColorU32(colors[palIdx]));

			const core::String &id = core::string::format("##palitem-%i", palIdx);
			if (ImGui::InvisibleButton(id.c_str(), colorButtonSize)) {
				*selectedPalIdx = palIdx;
			}
#if 0
			const core::String &contextMenuId = core::string::format("Actions##context-palitem-%i", palIdx);
			if (ImGui::BeginPopupContextItem(contextMenuId.c_str())) {
				ImGui::EndPopup();
			}
#endif
			if (!colorHovered && ImGui::IsItemHovered()) {
				colorHovered = true;
				drawList->AddRect(v1, v2, redColor);
			} else if (palIdx == highlightPalIdx) {
				drawList->AddRect(v1, v2, yellowColor);
			} else if (palIdx == *selectedPalIdx) {
				drawList->AddRect(v1, v2, darkRedColor);
			}
			globalCursorPos.x += colorButtonSize.x;
			if (globalCursorPos.x > windowWidth - colorButtonSize.x) {
				globalCursorPos.x = pos.x;
				globalCursorPos.y += colorButtonSize.y;
			}
			ImGui::SetCursorScreenPos(globalCursorPos);
		}
		const ImVec2 cursorPos(pos.x, globalCursorPos.y + colorButtonSize.y);
		ImGui::SetCursorScreenPos(cursorPos);

		// restore the draw list flags from above
		drawList->Flags = backupFlags;
		return true;
	}
	return false;
}
```

Extracted from https://github.com/mgerhardy/engine/blob/master/src/tools/voxedit/modules/voxedit-ui/PalettePanel.cpp
