### ISSUE TITLE
Something not working in ImGui::Begin? [Help]

### ISSUE THREAD

**Issue by Stehsaer** [ocornut/imgui#6944]
**Version/Branch of Dear ImGui:**

Version: 18995
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: msvc, vs2022, release x64
Operating System: Windows 11 Professional

**My Issue/Question:**

Can't control the windows' visibility with p_open parameter in `ImGui::Begin("title", &this_bool_cant_control)`
Clicking the X at the top-right corner doesn't work at all.
However the demo is working fine, what should I do to correct my mistake?
The codes are in the screenshot below.

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/54050160/fb74d233-b1a5-4d1e-91d4-29213e0c183e)
<img width="369" alt="image" src="https://github.com/ocornut/imgui/assets/54050160/20737a72-6043-4033-b1e9-1a96fe715d09">
No changes are made to the bool

**Comment by cfillion** [comment]
Clicking on the 'X' button writes false into that boolean. It's up to you to check it and only submit the window when it's true. Also, `End` should be called unconditionally (it's inconsistent with the other End* functions).

```cpp
static bool show_test = true;
if(show_test) {
  if(ImGui::Begin("Test", &show_test)) {
    ImGui::Text("Test");
  }
  ImGui::End();
}
```

**Comment by Stehsaer** [comment]
Thanks for your help and have a great day!
