### ISSUE TITLE
Selectable with right click and double click

### ISSUE THREAD

**Issue by krulci** [ocornut/imgui#6945]
**Version/Branch of Dear ImGui:**

Version: 1.89.4.0
Branch: sneusse/ImGui.NET

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp _(or specify if using a custom engine/back-end)_
Compiler: dotnet
Operating System: Windows 11

**My Issue/Question:**

I am trying to implement double click and right click event in a selectable. Double click works. Single left click works. But, single right click don't work.

**Screenshots/Video**

XXX _(you can drag files here)_

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_
```
// Here's some code anyone can copy and paste to reproduce your issue

                            if (ImGui.Selectable(listBoxItems[i], isSelected, ImGuiSelectableFlags.AllowDoubleClick))
                            {
                                autoub.selectedItem = i;
                                if (ImGui.IsMouseDoubleClicked(ImGuiMouseButton.Left))
                                {
                                    Console.WriteLine("ImGuiMouseButton.Left");
                                }
                                if (ImGui.IsMouseReleased(ImGuiMouseButton.Right))
                                {
                                    Console.WriteLine("ImGuiMouseButton.Right");
                                }
                            }
```

**Comment by GamingMinds-DanielC** [comment]
A right click won't trigger a state change, therefore `Selectable()` won't return true. You need to check regardless of the return value if the item is hovered (`IsItemHovered()`, checks the last item submitted) combined with your mouse button changes.

**Comment by krulci** [comment]
> A right click won't trigger a state change, therefore `Selectable()` won't return true. You need to check regardless of the return value if the item is hovered (`IsItemHovered()`, checks the last item submitted) combined with your mouse button changes.
> 
> 
> 
> So basically this:
> 
> ```c#
> 
>     if (ImGui.Selectable(listBoxItems[i], isSelected, ImGuiSelectableFlags.AllowDoubleClick))
> 
>         autoub.selectedItem = i;
> 
> 
> 
>     if (ImGui.IsItemHovered())
> 
>     {
> 
>         if (ImGui.IsMouseDoubleClicked(ImGuiMouseButton.Left))
> 
>         {
> 
>             Console.WriteLine("ImGuiMouseButton.Left");
> 
>         }
> 
>         if (ImGui.IsMouseReleased(ImGuiMouseButton.Right))
> 
>         {
> 
>             Console.WriteLine("ImGuiMouseButton.Right");
> 
>         }
> 
>     }
> 
> ```

Thanks. That works.
But then what is the purpose of the return value of Selectable?

**Comment by GamingMinds-DanielC** [comment]
The purpose is to signal that the selectable has just been selected in an easy to use way. Checking the mouse alone is no replacement for that, checking for selection by keyboard and gamepad as well would make the whole thing very cumbersome. The separate code to check for right clicks doesn't replace that.

**Comment by ocornut** [comment]
Also see #5816

**Comment by krulci** [comment]
> The purpose is to signal that the selectable has just been selected in an easy to use way. Checking the mouse alone is no replacement for that, checking for selection by keyboard and gamepad as well would make the whole thing very cumbersome. The separate code to check for right clicks doesn't replace that.

Oh I get it now.
That's why left click works but right click don't work.
Because left click triggers the selection.
So does a double left click.
But right click does not so putting the check on right click in the scope of selectable don't work.
That's probably why when I clicked both button it triggers the print when I had the check for right click in the scope of selectable.
Makes sense makes sense.
Thanks a lot.
