### ISSUE TITLE
Font atlas texture fails to upload to GPU.

### ISSUE THREAD

**Issue by Cream-Caramel** [ocornut/imgui#6948]
![2023-10-21_202453](https://github.com/ocornut/imgui/assets/29514732/d71399f3-7822-4765-a204-6fc400dbc895)

when i tried use io.Fonts->Build(); to build the atlas,it appeared.

**Comment by ocornut** [comment]
https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#troubleshooting
