### ISSUE TITLE
how to integrate other engine(such as ogre3d  irrlicht) into the imgui,the,scene was displayed in the imgui 

### ISSUE THREAD

**Issue by zhouxs1023** [ocornut/imgui#695]
i want to use imgui to do engine  editor,but i do not know how to integrate engine scene onto imgui,whether there is a basic process for beginner?thanks for your reply!

**Comment by ocornut** [comment]
The documentation is partly at the top of imgui.cpp partly to be inferred from the existing examples app, such as opengl_examples/. I don't know about Ogre but it is merely a case of interfacing the inputs and rendering textured triangles, which I assume Ogre can do.

There's no basic tutorial for beginner. Somebody needs to come make and release a binding for Ogre3d. Someone who knows Ogre3d well should be able to do it in a few hours.

There is already an Irrlicht binding, see
https://github.com/ocornut/imgui/wiki/Links

**Comment by jarikomppa** [comment]
From a quick glance there's been at least a couple threads on the ogre
forums regarding integrating ImGui, but no ready answers.

**Comment by ocornut** [comment]
@zhouxs1023 Unless you have a specific question, I am going to close this. You can example to all the existing code in the examples/ folder to understand how the library needs to be integrated. An official Ogre3d backend would be nice.
