### ISSUE TITLE
DirectX9 ImGui Display/Render Location Issue

### ISSUE THREAD

**Issue by tarandrus** [ocornut/imgui#6950]
_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

Version: 1.89.9
Branch: master

Windows11
DirectX9
Visual Studio 2022

Creating a simple hook into an old game that uses DirectX9, hooks in fine, but displaying is a bit wonky as explained below.

If I hook into the game while on a non-settings screen, I only see ImGui rendering on the settings screen.

Hook here... 
![image](https://github.com/ocornut/imgui/assets/94143842/4dfd4b80-b4c6-4dca-baec-2a0418351b2f)

But see here...
![image](https://github.com/ocornut/imgui/assets/94143842/58aa9818-893a-4a7a-aff4-defde3c6b341)

I can interact with the ImGui window using my mouse, change size, minimize, close, etc. just fine. 

However, if I hook while the settings screen is open, I then see it on the main screen but can no longer interact with it using my mouse.
![image](https://github.com/ocornut/imgui/assets/94143842/4d3c6151-39fa-4f1c-a7de-0a79e2b5a6cd)

**Comment by sakiodre** [comment]
The game is rendering over imgui, without further information, it is impossible to help you, are you sure you hooked the correct `EndScene` function?

**Comment by ocornut** [comment]
Closing as not providing enough details. Feel free to post more details here and we could reopen.
