### ISSUE TITLE
Modifying one checkbox modifies all of them

### ISSUE THREAD

**Issue by talkalotwhenim** [ocornut/imgui#6953]
I know theres a lot of issues and docs on IDs and stuff but for whatever reason I can't get this to work. I want the checkbox to control the corresponding window. Right now it controls both windows.

**Standalone, minimal, complete and verifiable example:** 
```
for (int n = 0; n < 2; n++)
{
   ImGuiWindowFlags window_flags = 0;
   static bool no_background = false;
   if (no_background)
      window_flags |= ImGuiWindowFlags_NoBackground;
   char name[50];
   sprintf(name, "My Window##%d", n);
   ImGui::Begin(name, (bool*)1, window_flags);
   ImGui::Checkbox("No background" + *std::to_string(n).c_str(), &no_background);
   ImGui::End();
}
```

**Comment by GamingMinds-DanielC** [comment]
Classic ID conflict:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

All of your checkboxes have the same ID. You need to rectify that by either modifying the ID for each loop or by modifying the ID stack (with `PushID(...)` / `PopID()`).

**Comment by talkalotwhenim** [comment]
> Edit: skimmed through it to quickly.
> 
> That example code is quite incomplete, especially the line where you call `Checkbox()`. In this form the code wouldn't even compile.

My apologies, I have updated the code

**Comment by ocornut** [comment]
Now your checkbox have unique identifiers, but they all refer to the same data (“bool no_background”) so their value is all the same.

**Comment by GamingMinds-DanielC** [comment]
OK. Your problem here is that you use a static bool for both windows, every loop iteration uses the exact same one. Put that outside of the loop into a bool array with as many elements as you need and index that array with n accordingly.

Other mistakes: if you don't have a controlling bool for the window open state, give it a NULL pointer, your `(bool*)1` is a timebomb. Also don't commit items to a window if `Begin()` returns false.

```c++
static bool no_background[2] = {};

for (int n = 0; n < 2; n++)
{
    ImGuiWindowFlags window_flags = 0;
    if (no_background[n])
        window_flags |= ImGuiWindowFlags_NoBackground;
    char name[50];
    sprintf(name, "My Window##%d", n);
    if (ImGui::Begin(name, NULL, window_flags))
    {
        ImGui::Checkbox("No background" + *std::to_string(n).c_str(), &no_background[n]);
    }
    ImGui::End();
}
```

**Comment by ocornut** [comment]
Closing as answered. Let us know if you don't understand what's going on, but the core principle of dear imgui is that you tend to own your data and dear imgui always edit your own data.
