### ISSUE TITLE
Vulkan hpp backend?

### ISSUE THREAD

**Issue by khiner** [ocornut/imgui#6954]
Is a [Vulkan-Hpp](https://github.com/KhronosGroup/Vulkan-Hpp) backend in scope? I would like to use `vulkan.hpp` in my application, rather than `vulkan.h`, but ImGui only provides a backend using the C-style `vulkan.h` header.

I've found [two](https://github.com/yknishidate/imgui-vulkan-hpp-backend) [repos](https://github.com/takiyu/ImGui-VulkanHpp) that implement such a backend, but one is archived and obviously both are not officially supported. Is there any possibility of an officially-supported vulkan-hpp backend in the future?

**Comment by ocornut** [comment]
Can’t you use Vulkan.hpp in your main code/application, and let the backend use Vulkan.h ? Is including vulkan.h in the source file where you implement the backend an issue ?

**Comment by khiner** [comment]
I don't think there is a collision problem with including both `vulkan.hpp` and `vulkan.h` in the same context, but my use case is to use the same Vulkan context variables for both ImGui and other application uses.

```cpp
struct VulkanContext {
    VkInstance Instance = VK_NULL_HANDLE;
    VkPhysicalDevice PhysicalDevice = VK_NULL_HANDLE;
    VkDevice Device = VK_NULL_HANDLE;
    uint32_t QueueFamily = (uint32_t)-1;
    VkQueue Queue = VK_NULL_HANDLE;
    ...
    ```
    
    Typically we'd use a single instance/device/queues and share it across multiple rendering pipelines, but the ImGui Vulkan functions expect a `VkInstance`, rather than a `vk::Instance` c++ class instance. ImGui methods also expect/manage a `VkAllocationCallbacks` instance, which the hpp headers don't make use of (as far as I can tell) since they manage memory automatically.
    
I'm new to Vulkan, so perhaps there is a way to create and configure `vk::Foo` variables and store them in my context, but then extract the underlying `vkFoo` variables, including a `VkAllocationCallbacks` object managed under the hood?

**Comment by PathogenDavid** [comment]
I don't have experience with Vulkan-Hpp, but it appears that [it still allows you to access the underlying non-C++ types via casting](https://github.com/KhronosGroup/Vulkan-Hpp/blob/de5821703f9e28a6dfc8d858364e97441594bfa3/vulkan/vulkan_handles.hpp#L15916-L15919).

As for `VkAllocationCallbacks`, my understanding is that using it is strictly optional. (It doesn't look like it's even initialized from null in `example_glfw_vulkan`.) When you *do* want to use `VkAllocationCallbacks` it seems you're the one responsible for creating it.

**Comment by khiner** [comment]
Thanks @PathogenDavid! I didn't realize the allocator remains null throughout the lifetime of the example application. I'll try this out and report back!

**Comment by khiner** [comment]
Actually it turns out the hpp to h type casting happens automatically, so this was super easy - I didn't even have to touch the ImGui code! Just updated my `VulkanContext` types and all their setup (following examples from [Vulkan-Samples](https://github.com/KhronosGroup/Vulkan-Samples)). I then just pass all these instances directly (with a `nullptr` `VkAllocationCallbacks`) and everything works 😎 

```
struct VulkanContext {
    vk::Instance Instance;
    vk::PhysicalDevice PhysicalDevice;
    vk::Device Device;
    uint32_t QueueFamily = (uint32_t)-1;
    vk::Queue Queue;
    vk::PipelineCache PipelineCache;
    vk::DescriptorPool DescriptorPool;
```

Thanks again!
