### ISSUE TITLE
Combo Box not shown on the modal dialog.

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#6956]
**Version/Branch of Dear ImGui:**

Version: 1.89
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_SDL2.cpp + imgui_impl_GL3.cpp
Compiler: msvc 2019
Operating System: windows 10

**My Issue/Question:**

I placed a combo box on the modal dialog, and it cannot be shown, I want to know why and find the right way to do it. Thanks.

**Comment by GamingMinds-DanielC** [comment]
Even though you just closed the issue: without posting any code of what you did, there is no chance to tell what you did wrong.
