### ISSUE TITLE
Resizing an image within code without changing the original image file

### ISSUE THREAD

**Issue by Seraphim19119** [ocornut/imgui#6959]
Is it possible to somehow load an image via D3DX11CreateShaderResourceViewFromFile and then resize it?
I tried to load the image through third-party libraries, then modify it, save it in a variable, and then load it through D3DX11CreateShaderResourceViewFromMemory.
I will now attach to you what I tried to use (it was generated by ChatGPT)

`    // Function to resize the image
    CImg<unsigned char> resizeImage(const CImg<unsigned char>& inputImage, int maxWidth) {
        CImg<unsigned char> image = inputImage;

        // Determine the width and height of the image
        int width = image.width();
        int height = image.height();

        // Calculate new dimensions taking into account the maximum length
        if (width > maxWidth) {
            double scale = static_cast<double>(maxWidth) / width;
            width = static_cast<int>(width * scale);
            height = static_cast<int>(height * scale);
        }

        // Resize the image while maintaining the aspect ratio
        return image.resize(width, height);
    }

    // Function to encode an image to JPEG and save it to bytes
    std::vector<unsigned char> encodeImageToJPEG(const CImg<unsigned char>& image, int quality) {
        std::vector<unsigned char> imageBytes;

        // Use the stb_image library to encode to JPEG
        int width = image.width();
        int height = image.height();
        int numChannels = 3; // 3 channels for RGB image

        imageBytes.reserve(width * height * numChannels); // Pre-allocate memory

        if (stbi_write_jpg_to_func([](void* context, void* data, int size) {
            auto& bytes = *reinterpret_cast<std::vector<unsigned char>*>(context);
            unsigned char* byteData = reinterpret_cast<unsigned char*>(data);
            bytes.insert(bytes.end(), byteData, byteData + size);
            }, &imageBytes, width, height, numChannels, image.data(), quality) == 0) {
            std::cerr << "Error when encoding image to JPEG." << std::endl;
        }

        return imageBytes;
    }

    ID3D11ShaderResourceView* loadImage(ID3D11Device* g_pd3dDevice, const char* imageFile, int maxSize) {
        cout_ok_("Start loading image: ");
        cout_ok(imageFile);
        // Load an image using CImg
        CImg<unsigned char> image(imageFile);

        // Resize the image
        CImg<unsigned char> resizedImage = resizeImage(image, maxSize);

        // Encode the image into JPEG and save it to bytes
        int quality = 95; // Качество сжатия (от 0 до 100)
        std::vector<unsigned char> imageBytes = encodeImageToJPEG(resizedImage, quality);

        // Create a shader resource from an in-memory image using DirectX
        ID3D11ShaderResourceView* pTextureSRV = nullptr;

        // Assuming you have DirectX SDK installed and configured
        // and you have a device object D3D11* pd3dDevice

        D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, imageBytes.data(), imageBytes.size(),
            nullptr, nullptr, &pTextureSRV, nullptr);

        if (pTextureSRV) {
            cout_ok("Seccsesful loading image");
            return pTextureSRV;
            //pTextureSRV->Release();
        }

        cout_fail("Load image");
        return 0;
    }`
Unfortunately this code crashes :(

P.s. I'm writing a mod manager for a game, my program downloads pictures from the site, the problem is that the pictures have different resolutions, and they are all in horizontal format, and my button is square (180 by 180)
![image](https://github.com/ocornut/imgui/assets/76170770/5a2536e0-6c48-45a8-b607-3228ba6e44c4)

original image:

![image_no_back_image_1](https://github.com/ocornut/imgui/assets/76170770/8a734751-b278-4720-b75d-7b199313ff0c)

![image_1](https://github.com/ocornut/imgui/assets/76170770/17868bdd-bedf-4eba-8e22-d4d56d584245)

SORRY FOR MY GOOGLE TRANSLATE

**Comment by ocornut** [comment]
Hello,
Nothing in your question is specific or related to dear imgui. This isn’t the right place to ask unfortunately.
