### ISSUE TITLE
How to display label in drag_float2/float3 as below picture:

### ISSUE THREAD

**Issue by zhouxs1023** [ocornut/imgui#696]
I want to display label in multi-component  in drag_float2/float3 or input float as below:
![image](https://cloud.githubusercontent.com/assets/905931/16044396/dc870bf0-3276-11e6-8a5d-9fd988689a3d.png)

code as below,but can not compile,how to set?
ImGui::DragFloat2("drag float2", vec4f, 0.01f, 0.0f, 1.0f,"X:%.3f","Y:%.3f");

**Comment by ocornut** [comment]
It's not possible because DragFloat2 takes only a single format string.

You can recreate DragFloat2 by doing:
```
PushItemWidth(CalcItemWidth()/2);
DragFloat("##X", ...");
SameLine();
DragFloat("##Y, ...");
PopItemWidth();
```

**Comment by zhouxs1023** [comment]
Thank you very much,
Whether or not you can add this feature later

**Comment by ocornut** [comment]
No problems
Will not add it as to avoid/confusing extra API entry points.
Note that it is a strictly cosmetic feature :)
