### ISSUE TITLE
Image flickers while updating the frame from a separate update thread when imgui render is running in the main program loop

### ISSUE THREAD

**Issue by KBasakC** [ocornut/imgui#6960]
I am trying to do the following:

- capture live webcam images using opencv in one update thread
- render the opencv images converted to opengl texture and display it along with some imgui gui elements

The goal is to keep the fast rendering (60fps) while the slow opencv videocapture gets the frames at low fps (30fps). However, the live video flickers often. The stream is not stable. I tried to use mutex lock/unlock during the opencv frame update or clone and still the live video stream flickers. 

Here is the structure of my code:

`
// OpenCV Mat to OpenGL texture function
void CVMat2GLTexture(cv::Mat &image, GLuint &image_texture)
{
    if (image.empty())
    {
        std::cout << "image empty" << std::endl;
    }
    else
    {
        // Create a OpenGL texture identifier
        glGenTextures(1, &image_texture);
        glBindTexture(GL_TEXTURE_2D, image_texture);

        // Setup filtering parameters for display
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR); 
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

        // Set texture clamping method
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP); 
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP); 

        cv::cvtColor(image, image, cv::COLOR_BGR2RGB);

        glTexImage2D(GL_TEXTURE_2D,    
                     0,                
                     GL_RGB,           
                     image.cols,      
                     image.rows,      
                     0,                
                     GL_RGB,          
                     GL_UNSIGNED_BYTE, 
                     image.ptr());    
    }
}

void CaptureNProcess(cv::VideoCapture &cap, cv::Mat &frame) 
{
    cv::Mat frame_cap;

    while (!stopped) // While application is running
    {
        
        cap.read(frame_cap);
        
        if (frame_cap.empty())
        {
            std::cerr << "ERROR! blank frame grabbed with cam on\n";
            break;
        }
        
        mtx.lock();
        frame = frame_cap.clone();
        mtx.unlock();
    }
}

main()
{
// imgui setup
//opencv videocapture setup

// start the capture and update thread
std::thread CaptureNProcess_thread(CaptureNProcess, std::ref(cap), std::ref(frame));

while (!glfwWindowShouldClose(window))
    {
            glfwPollEvents();

            // Start the Dear ImGui frame
            ImGui_ImplOpenGL3_NewFrame();
            ImGui_ImplGlfw_NewFrame();
            ImGui::NewFrame();

            CVMat2GLTexture(frame, frame_tex);
            ImGui::Begin("Camera window", &cam_window);
            ImGui::Text("Cam Id: 0");
            ImGui::Text("Image size = %d x %d", frame.rows, frame.cols);
            ImGui::Image((void *)(intptr_t)frame_tex, ImVec2(frame.cols, frame.rows));
            ImGui::End();

}
`

Please help!

**Comment by ocornut** [comment]
ImGui_ImplOpenGL3_RenderDrawData() will submit opengl polygons with the texture id value you gave it. Anything else to know is not related to dear imgui and that question isn’t much of a dear imgui question. I am closing this as an offtopic question.
