### ISSUE TITLE
ImGui::IsItemHovered() - incorrectly determines the collision.

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#6961]
When I create any element in a window, button or InputText or any other ImGui element and when after the element creation line I call ImGui::IsItemHovered(ImGuiHoveredFlags_None):

```
if (ImGui::Button(&title_button_name[0], button_size))
{
//So the button was pressed: some code
}
bool collision = ImGui::IsItemHovered(ImGuiHoveredFlags_None);

std::cout<<collision <<std::endl;
```

Well, when the mouse cursor is on the button object, ImGui::IsItemHovered returns “true” - this is actually how it should be. BUT as soon as I quickly move the mouse cursor completely outside the backend window, then ImGui::IsItemHovered still returns "true", if I do it slowly, I move the mouse cursor outside the window, then ImGui::IsItemHovered returns "false" " - as it should be.

Please tell me - Is this a small Imgui error or is it an error somewhere in my Imgui backend setup?

**Comment by sakiodre** [comment]
It's hard to tell what's wrong with the lack of information in your post. What backend are you using? Did you modify the existing backends or use your own backend? Also, is the button still drawn as hovered or is it just the `IsItemHovered` function return true?

**Comment by ocornut** [comment]
Please don’t ask questions about your backend setup without specifying what your backend setup is.
Have io.MousePos be displayed on screen and you may notice your setup is incorrectly updating mouse position.

You can easily run any of the examples or precompiled binary and compare with them.

**Comment by ocornut** [comment]
PS: @ElectroidDes you have opened a dozen issues here and not once fullfilled the issue template and issue submitting guidelines, which is a little rude of you. Please make a substantial effort improving the quality of your support requests. Thank you !
