### ISSUE TITLE
Is there a header which uses C++ lifetimes to gaurd part of the api?

### ISSUE THREAD

**Issue by Andersama** [ocornut/imgui#6963]
**My Issue/Question:**
A lot of the api uses begin / end paired functions, in fact a lot of these functions do additional asserts to make sure that to some degree that these stay in some amount of sync.

```c
ImGui::Begin("Example Code");
...etc...
ImGui::End();
```

I'm curious if there's a header or project which might've wrapped these function calls to provide a struct which calls the appropriate destructor. Think the trick used to defer a lambda function to the end of a function call.

```c
#include <iostream>
// Note: this isn't a great example, just a rough mockup
template<typename Callback>
struct defer {
    Callback cb;
    defer(Callback func) {
       cb = func;
    }
    ~defer(){
       cb();
    }
}

int some_func() {
   defer later{[](){
       //called after "first" because structs would get cleaned up right before the function returns
       std::cout << "last\n";
   }};
   std::cout << "first\n";
}
```

So for example the api might look like:
```c
ImGuiBeginGaurd begin_result = ImGuiGaurd::Begin("Example Window");
//
//behind the scene we can now be sure that ~ImGuiBeginGaurd() would get called and
//presumably the correct "End" call
```

The only slight concern I have if this doesn't exist already would be the parts of the api which don't require a paired "End" call which may make things confusing.

**Comment by emoon** [comment]
See https://github.com/ocornut/imgui/issues/2096 and https://github.com/ocornut/imgui/pull/2197

**Comment by Andersama** [comment]
Much appreciated, thank you.

**Comment by ocornut** [comment]
Combo() and ListBox() are not BeginXXX functions so don’t need this.

Traditionally my reluctance with this that Push/Pop functions may be interleaved in asymmetrical manners with other functions, and that adopting this style tends to prevents it.
Eg: 
PushStyleVar() / Begin() / PopStyleVar() / … / End()
Is a valid and very useful pattern.

Your idiom may only be safely used if the user opens a scope for every begin/end, not doing so may lead to undesired behavior.

**Comment by Andersama** [comment]
Yeah I've already run into an issue that without upping the warning level `[[nodiscard]]` isn't helping because the destructor isn't being executed as expected.
