### ISSUE TITLE
Custom font crash the window

### ISSUE THREAD

**Issue by HojdaAdelin** [ocornut/imgui#6970]
Hi!
So I wanted to add a custom font:
```
 ImGuiIO& io = ImGui::GetIO();
 ImFont* main_font = io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\Arial.ttf", 13.0f);
```

And I used:
`ImGui::PushFont(main_font);`
before Begin:
```
ImGui::Begin("Forge V1.0",nullptr, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize | 
ImGuiWindowFlags_NoCollapse);
```

While debugging I got this error when crash:
`(process 6156) exited with code -1073741819.`

I mention this project was created for a game and it's attached to the game and I used debugging from VS.

Sorry for not respect the issue model but I don't know how to use it :)

**Comment by Chilledheart** [comment]
If the font is loaded after the first call of `ImGui_ImplDX11_NewFrame`, then you need to rebuild the font cache inside the backend by invalidating the previous font sampler such as `ImGui_ImplDX11_InvalidateDeviceObjects`.

**Comment by HojdaAdelin** [comment]
Thank you! I created the GUI in a another file "GUI.cpp" and I used here the font instead to use before the new frame so this was the problem.
