### ISSUE TITLE
Auto-resize window flag + high DPI scaling / FontGlobalScale?

### ISSUE THREAD

**Issue by JC3** [ocornut/imgui#6978]
When the auto-resize window flag is set and the system scaling is not 100%, the dialog size seems to be incorrect.

E.g. the following dialog (Python via `pyimgui`, sorry, hopefully you get the idea):

```
        with imgui.begin_popup_modal("A Dialog", flags=imgui.WINDOW_ALWAYS_AUTO_RESIZE | imgui.WINDOW_NO_COLLAPSE) as dialog:
            if dialog.opened:
                
                imgui.columns(2)
                
                imgui.text("Option:")
                imgui.next_column()
                imgui.input_text("", "value")
                imgui.next_column()

                imgui.text("Option 2:")
                imgui.next_column()
                imgui.input_text("", "value")
                imgui.next_column()

                imgui.columns(1)
                
                ok_button = imgui.button("Ok", 120)
                if ok_button:
                    imgui.close_current_popup()
```

Displays at a reasonably correct size with system scaling at 100%:

![image](https://github.com/ocornut/imgui/assets/5651184/767878c4-c64f-411f-8d3c-65c5a5a948ba)

But is too small with system scaling set at 250%:

![image](https://github.com/ocornut/imgui/assets/5651184/62085bd6-915f-4ea9-b4d8-ff2ccbb0f874)

Is this a bug? 

Is there some way to make this work on high DPI displays? Is there a dialog size scaling setting somewhere that I can set?

**Comment by JC3** [comment]
An important point I forgot to mention:

I'm setting FontGlobalScale and DisplayFramebufferScale to the system scale factor:

```
        self._imgui_impl.io.font_global_scale = max(scale)
        self._imgui_impl.io.display_fb_scale = scale
```

So I'm thinking maybe the dialog auto-resize isn't taking FontGlobalScale into account?

**Comment by ocornut** [comment]
Columns() is an old API and is a container where the content inside a column isn't taken into account to report content to the outer window. In both code the only size which is taken into account is the same of your "OK" button which you have hardcoded as 120 in both cases.

You can multiply that 120 by your scale to make both image similar.
If you want the actual column contents to be measured you should use BeginTable().

**Comment by JC3** [comment]
Gotcha, thank you. I will switch to tables.
