### ISSUE TITLE
Input text in tables has 0 width

### ISSUE THREAD

**Issue by JC3** [ocornut/imgui#6979]
The following code (Python via `pyimgui`):

```
        with imgui.begin_popup_modal("A Dialog", flags=imgui.WINDOW_ALWAYS_AUTO_RESIZE | imgui.WINDOW_NO_COLLAPSE) as dialog:
            if dialog.opened:
                
                imgui.begin_table("", 2)
                
                imgui.table_next_row()
                imgui.table_set_column_index(0)
                imgui.text("Option:")
                imgui.table_set_column_index(1)
                imgui.input_text("", "value")

                imgui.table_next_row()
                imgui.table_set_column_index(0)
                imgui.text("Option 2:")
                imgui.table_set_column_index(1)
                imgui.input_text("", "value")

                imgui.end_table()
                
                ok_button = imgui.button("Ok")
                if ok_button:
                    imgui.close_current_popup()
```

Seems to produce input_texts with 0 width (aside from the padding):

![image](https://github.com/ocornut/imgui/assets/5651184/7acc7ff5-f531-4d8a-aefc-d9a26558860c)

Note the skinny blue slivers on the right.

Setting the window size explicitly, or allowing the window to be resizeable, doesn't seem to help and the inputs remain 0-width.

Additionally, if I call SetNextItemWidth on the second text input:

```
                imgui.begin_table("", 2)
                
                imgui.table_next_row()
                imgui.table_set_column_index(0)
                imgui.text("Option:")
                imgui.table_set_column_index(1)
                imgui.input_text("", "value")

                imgui.table_next_row()
                imgui.table_set_column_index(0)
                imgui.text("Option 2:")
                imgui.table_set_column_index(1)
                imgui.set_next_item_width(120)
                imgui.input_text("", "value")

                imgui.end_table()
```

Then the first input becomes the correct size:

![image](https://github.com/ocornut/imgui/assets/5651184/0f7e968b-938a-4240-b308-7151bc497c46)

So it seems like maybe the column width isn't being calculated properly for text inputs unless their widths are explicitly set.

Is there a way to get the column width to be the automatically calculated width of the text inputs?

**Comment by JC3** [comment]
> There's no "right" width for an input text widget.

Hm, but what about that default width that the first one gets (when I specify the second one to be larger)? That *feels* "right".

**Comment by ocornut** [comment]
The default width is always about 2/3 of the column width (I just realize that's not mentioned in "Demo->Layout->Widgets Width" maybe it should), and the column width was extrapolated from `InputText()` for which you set an explicit width.
Note that this scheme wouldn't work if every row relied on the default width.

**Comment by ocornut** [comment]
Closing as answered.
