### ISSUE TITLE
The width of "with border" varies with the scroll bar on the right.  in imgui-1.49(as below picture)

### ISSUE THREAD

**Issue by zhouxs1023** [ocornut/imgui#698]
The mouse on the right scroll bar up and down movement, the width will be changed，but There is no such a situation in imgui-1.48 
![1](https://cloud.githubusercontent.com/assets/905931/16085705/7d352f86-334f-11e6-9c45-2b183a3ad74a.PNG)
![2](https://cloud.githubusercontent.com/assets/905931/16085712/841f8cb0-334f-11e6-8716-04723f9dfa40.PNG)

**Comment by ocornut** [comment]
I can't reproduce the bug. Are you on the latest unmodified version of ImGui ?

**Comment by zhouxs1023** [comment]
source code from here as picture
![default](https://cloud.githubusercontent.com/assets/905931/16088825/63125366-335b-11e6-8421-c9f64063f7a5.PNG)

**Comment by ocornut** [comment]
Try to get latest.

**Comment by zhouxs1023** [comment]
thank you!
