### ISSUE TITLE
How can I scroll 5 child windows as one window?

### ISSUE THREAD

**Issue by Nitr0-G** [ocornut/imgui#6981]
**Version/Branch of Dear ImGui:**

Version: 1.89.9
Branch: master

**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_win32.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC/Clang-cl
Operating System: Windows 10

**My Issue/Question:**
Hello to all readers!
How can I scroll 5 child windows as one window?
I have a certain number of windows like in the screenshot 
![IMG](https://github.com/ocornut/imgui/assets/120374383/cccac436-9f14-4f87-8120-9955bac0c3bf)
and they are all in one main window with invisible borders, how can I scroll them all as one? Is there something like scroll callback or other parameter/function in imgui?
That is, now if I scroll the first window, then the second window will not scroll, and I need it to scroll with the first window, as well as the remaining 3.
**Standalone, minimal, complete and verifiable example:**
```

void GUI::ChildWindowRender(const char* id, const ImVec2& pos, const ImVec2& size, WindowCodes Code, const bool border, ImGuiWindowFlags WindowFlags)
{
    if ((size.x <= 0.0f) || (size.y <= 0.0f)) { return; }

    ImGui::SetCursorPos(pos);

    if (ImGui::BeginChild(id, size, border, WindowFlags))
        ChildWindowDispatcher(Code);
        ImGui::EndChild();
    return;
}

void GUI::InterlnalDiasmWindowRender()
{
    const int splitterSize = 4;

    static float splitter1_relPosX = 0.5;
    static float splitter2_relPosY = 1.0019;

    SizesAndPositions objSizesAndPositions(TitleBarHeight, splitterSize, splitter1_relPosX, splitter2_relPosY, WindowCodes::DisasmWindow);
    ChildWindowRender("LeftWindowInternalDisasmWindow_1", objSizesAndPositions.LeftTopPosition, objSizesAndPositions.LeftTopSize, WindowCodes::LeftWindowInternalDisasmWindow_1, false);
    ChildWindowRender("RightWindowInternalDisasmWindow_2", objSizesAndPositions.RightTopPosition, objSizesAndPositions.RightTopSize, WindowCodes::RightWindowInternalDisasmWindow_2, false);
}

void GUI::LeftWindowInternalDisasmWindowRender_1()
{
    const int splitterSize = 4;

    static float splitter1_relPosX = 0.5;
    static float splitter2_relPosY = 1.0019;

    SizesAndPositions objSizesAndPositions(TitleBarHeight, splitterSize, splitter1_relPosX, splitter2_relPosY, WindowCodes::DisasmWindow);
    ChildWindowRender("JmpsFromAToMapDisasmWindow", objSizesAndPositions.LeftTopPosition, objSizesAndPositions.LeftTopSize, WindowCodes::JmpsFromAToMapDisasmWindow, true);
    ChildWindowRender("RightWindowOfLeftWindowInternalDisasmWindow_3", objSizesAndPositions.RightTopPosition, objSizesAndPositions.RightTopSize, WindowCodes::RightWindowOfLeftWindowInternalDisasmWindow_3, false);
}

void GUI::RightWindowInternalDisasmWindowRender_2()
{
    const int splitterSize = 4;

    static float splitter1_relPosX = 0.5;
    static float splitter2_relPosY = 1.0019;

    SizesAndPositions objSizesAndPositions(TitleBarHeight, splitterSize, splitter1_relPosX, splitter2_relPosY, WindowCodes::DisasmWindow);
    ChildWindowRender("MnemonicsDisasmWindow", objSizesAndPositions.LeftTopPosition, objSizesAndPositions.LeftTopSize, WindowCodes::MnemonicsDisasmWindow, true);
    ChildWindowRender("CommentsDisasmWindow", objSizesAndPositions.RightTopPosition, objSizesAndPositions.RightTopSize, WindowCodes::CommentsDisasmWindow, true);
}

void GUI::RightWindowOfLeftWindowInternalDisasmWindowRender_3()
{
    const int splitterSize = 4;

    static float splitter1_relPosX = 0.5;
    static float splitter2_relPosY = 1.0019;

    SizesAndPositions objSizesAndPositions(TitleBarHeight, splitterSize, splitter1_relPosX, splitter2_relPosY, WindowCodes::DisasmWindow);
    ChildWindowRender("AddrsABpsDisasmWindow", objSizesAndPositions.LeftTopPosition, objSizesAndPositions.LeftTopSize, WindowCodes::AddrsABpsDisasmWindow, true);
    ChildWindowRender("OpcodesDisasmWindow", objSizesAndPositions.RightTopPosition, objSizesAndPositions.RightTopSize, WindowCodes::OpcodesDisasmWindow, true);
}

void GUI::JmpsFromAToMapDisasmWindowRender()
{
    for (int i = 0; i < 60; i++)
        ImGui::Text("Hello, sailor! Making this line long enough for the example.", i, "");
}
```

**Comment by ocornut** [comment]
If they have the same height and same scrolling, why not use a single child window?

**Comment by ocornut** [comment]
Call `BeginTable()` with the `ImGuiTableFlags_Resizable`, refer to Demo->Tables and docs for details about sizing policies.

**Comment by Nitr0-G** [comment]
> Call `BeginTable()` with the `ImGuiTableFlags_Resizable`, refer to Demo->Tables and docs for details about sizing policies.

Thanks!!!
Maybe it will help someone - here is an issue that indirectly helped me solve some problems.
https://github.com/ocornut/imgui/issues/6945
https://github.com/ocornut/imgui/pull/5816
https://github.com/ocornut/imgui/issues/759
https://github.com/ocornut/imgui/issues/3151

I would also like to know how I can attach the table headers so that when scrolling the table they are always on top?
For example, I have a similar table
![IMG](https://github.com/ocornut/imgui/assets/120374383/b73d5176-c425-43c0-b5c3-5a0ea4fdc0e2)
When I try to scroll through this table, the headers come off, can I use some flag and something like that to attach them and have them always on top?
![IMGG](https://github.com/ocornut/imgui/assets/120374383/b87a2077-d6c1-4031-a266-6f556b8da4e4)

**Comment by ocornut** [comment]
You can use TableSetupScrollFreeze(0, 1).

You should execute and browse the Demo. All your questions are answered in the demo.
