### ISSUE TITLE
Regression: imgui.ini no more reloaded correctly

### ISSUE THREAD

**Issue by Lecrapouille** [ocornut/imgui#6982]
**Version/Branch of Dear ImGui:**

Version: somewhere between SHA1 04e9a2fac164ae9f397551346c6c82fe3a1aa809 and 4cde40dbe1e265865a7c3ff2ebf904fd2c3abd4b
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: any
Compiler: any
Operating System: any

**Standalone, minimal, complete and verifiable example:**

I'm tracking the HEAD of your docking branch. I'm now on SHA1 4cde40dbe1e265865a7c3ff2ebf904fd2c3abd4b but it seems that when quitting the application and starting it again, all widgets are messed up like if the imgui.ini was not parsed. This happens every time. Reverting to SHA1 04e9a2fac164ae9f397551346c6c82fe3a1aa809 seems ok. I did not make a git bisect to see which SHA1 introduces this regression.

**Comment by ocornut** [comment]
Apologies, during the merge of 9298e31 following #1710 yesterday I broke something with settings on docking.
Working on it now.

**Comment by ocornut** [comment]
I have pushed the fix 208b824. 
Apologies for the regression, and thank you for tracking HEAD, you are among the heroes I need :)
I'll work on adding some better regression tests for Settings.

**Comment by Lecrapouille** [comment]
@ocornut thank you quick fix :)
