### ISSUE TITLE
End Window by given ID or stop Window Content Appending to existing Window

### ISSUE THREAD

**Issue by ClonkAndre** [ocornut/imgui#6988]
**Version/Branch of Dear ImGui:**

Version: 1.89.8
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32 + imgui_impl_dx9
Compiler: VS2022 MSVC
Operating System: Windows 11

**My Issue/Question:**

Is it possible to End a Window by its ID? If not, how could i possibly implement such a function myself?
Or is it possible to stop Window Content to append to a already opened Window and just create a new one and deleting the old Window?

**My Situation:**

I have a single ImGui instance in a DLL. This DLL is a C++/CLI Project. From this DLL, we load a C# Script, which acts as a Manager, which then loads more C# Scripts that are present in the Directory. From the C# Script, we can access a managed Layer for ImGui that i added to the C++/CLI DLL (The C# Scripts reference the C++/CLI DLL) from which we can simply create a Window and add Content to it.

Now the thing is, the Manager has a Console from which we can reload all the scripts. When we do that, content just gets appended to the already opened Window by the Script..

**What i would like to achieve:**

The ImGui Window created by the Script should be completely destroyed so it can be recreated.

**What i tried to far:**

When a C# Script calls the Begin function of my managed Layer, it will create the Window, get the ID of the current window and store the ID of the Window in a list so we know which Windows where created by the Script.
When we reload the scripts the following happened: I looped through the list of Window IDs for that Script, in the C++/CLI DLL i used "FindWindowByID", then i used the "SetCurrentWindow" method to set the current window to the window we found via the ID, and then i tried to call End after we found and set the Window by ID to End the current Window. Didn't work.

**A little visual representation of what the C++/CLI DLL, the C# Manager Script and individual C# Scripts do**

![pic](https://github.com/ocornut/imgui/assets/39125931/bca4e535-1df0-4d6a-9e9d-2a43332ff4c3)

**Comment by GamingMinds-DanielC** [comment]
Sounds like what you are trying to achieve goes against the core principles of immediate mode (that's what the "Im" in Dear ImGui stands for) GUIs. The way to "delete" windows or items from one frame to the next is to just not submit them in the next frame, then they are gone. There is no mechanism to delete windows or items already submitted in this very frame. Such a mechanism would needlessly complicate the internals.

To achieve what you want, you either need to switch to a GUI system that is not immediate mode, or you need to buffer your windows/items yourself. Collect them in persistent containers, add some, delete some and when you are ready to submit them, submit only those that you want to actually be shown.

**Comment by ocornut** [comment]
Your explanation and schematic doesn’t include temporal elements, so your question is hard to make sense of. There’s nothing to delete, every frame what is submitted appears. You seems to be misunderstanding how dear imgui works but i am fairly certain what is you think is remaining is something you are resubmitting. If each script stops resubmitting its contents you wouldn’t see a window.

I can’t make sense of Daniel’s answer either. It seems to be attempting to literally answer your imho-invalid question and may be even more misleading to you.

**Comment by GamingMinds-DanielC** [comment]
> I can’t make sense of Daniel’s answer either. It seems to be attempting to literally answer your imho-invalid question and may be even more misleading to you.

I basically just said to only submit what should be shown and that there is no mechanism to delete already submitted stuff from the current frame. The rest was a short explanation as to why a request like that wouldn't fit with an immediate mode GUI.

**Comment by ocornut** [comment]
But they didn’t talk about a single frame glitch so i assume they are just storing and resubmitting contents.

**Comment by ocornut** [comment]
Closing as answered.

**Comment by iosiddhu** [comment]
Learning only,
once in loop you cannot destroy window. either you choose to render it or dont based on state . You can fake what you want by creating two windows control the information you show on the window through variables. you can also change the properties of the windows while running.
i know it does not solve your problem.
