### ISSUE TITLE
TableSetupScrollFreeze is not freezing header row

### ISSUE THREAD

**Issue by mauer** [ocornut/imgui#6989]
Good Morning,

I'm currently using the latest version of ImGui and try to create a table where the first row with all header titles is always visible.

According to the documentation `TableSetupScrollFreeze` should do exactly what I want. Unfortunately, it's not working. I tried to place the function call on different lines (before creating the columns, right at the end, ...) but it never works.

Here is an example of my source code:

```
  if (ImGui::BeginTable("tableTextMessages", 3, ImGuiTableFlags_SizingFixedFit | ImGuiTableFlags_Resizable)) {
      ImGui::TableSetupColumn("Message Date/Time", ImGuiTableColumnFlags_WidthFixed, 200);
      ImGui::TableSetupColumn("Message Type", ImGuiTableColumnFlags_WidthFixed, 120);
      ImGui::TableSetupColumn("Message Text", ImGuiTableColumnFlags_WidthStretch);

      ImGui::TableSetupScrollFreeze(0, 1);
      ImGui::TableHeadersRow();
      ...
```

Am I doing something wrong or did I miss understand the function?

Many thanks,
Marco

**Comment by ocornut** [comment]
Your table is not a scrolling table (ImGuiTableFlags_ScrollY) so freezing has not effect. When you scroll in our outer window you are scrolling the whole table area rather than its contents.

**Comment by mauer** [comment]
I added ImGuiTableFlags_ScrollY to the table flags, but it still doesn't work.

![image](https://github.com/ocornut/imgui/assets/148722/96b01316-49f5-4ad0-adac-12cd5f7408cc)

As you can see in the screenshot above, the table is scrollable.

**Comment by ocornut** [comment]
The code you are showing as code you used doesn’t match the screenshot. You may be looking at the wrong place.

**Comment by mauer** [comment]
OMG, I'm so stupid...

You know, I have been looking at the source code all morning. It's working now - many thanks for your help!!!
