### ISSUE TITLE
Minor clipping issue on window title

### ISSUE THREAD

**Issue by leiradel** [ocornut/imgui#699]
When the title of the window is clipped at the right side, it's also clipped at the top, it's easy to see it on the video windows at the right side:

![lrcmdr](https://cloud.githubusercontent.com/assets/357536/16095697/32a8e828-331c-11e6-86fb-d3a776976e74.png)

Also, how can I vertically align the contents of the two rightmost cells in the table inside the **Available Plugins** header?

**Comment by ocornut** [comment]
I confirmed the bug, will look at this.

The easy repro with the default font is to load it with something like:
```
    ImGuiIO& io = ImGui::GetIO();
    ImFont* font = io.Fonts->AddFontDefault();
    font->DisplayOffset.y -= 6;
```

For your second question, you can call `AlignFirstTextHeightToWidgets()`.

**Comment by ocornut** [comment]
On that second question, I would need to experiment with preserving the text baseline accross different column, it would make more sense. In NextColumn() currently we always set `CurrentLineTextBaseOffset` back to 0.0f but perhaps it should only be reset on Column 0.

**Comment by ocornut** [comment]
Applied a fix/workaround for the first issue. Note that it is probably actually an issue with the font straying over the expected top line, which is possible as you have merged an icon font there. I fixed the clipping to start from the top of the window rather than the top of the text which gives you style.FramePadding.y (default 3) extra pixels there.

**Comment by ocornut** [comment]
Closing and moved the second topic to the old/big Columns thread for later reference.

**Comment by ocornut** [comment]
By the way by the look of it your Icon font could be moved down by one pixel.
ImFont* font = io.Fonts->AddFontXXX;
font->DisplayOffset.y += 6;

**Comment by leiradel** [comment]
Thanks for the fix, I'll try it. Without the fix, `font->DisplayOffset.y += 1;` still clips the top of the icon. `font->DisplayOffset.y += 2;` make the text too low in the widgets.

**Comment by leiradel** [comment]
Yes, it's fixed, thanks!

**Comment by ocornut** [comment]
Yeah I was talking regardless of the fix, your icon font in this picture seems a pixel too high compared to the text font.

**Comment by leiradel** [comment]
> Yeah I was talking regardless of the fix, your icon font in this picture seems a pixel too high compared to the text font.

Yeah, my font is 10, and the icon font is 12. It looked bad at 10.
