### ISSUE TITLE
ImGui Viewports lose color when SDL_GL_MULTISAMPLESAMPLES is too high 

### ISSUE THREAD

**Issue by yockey88** [ocornut/imgui#6991]
Version: 1.89.9 WIP (18983)
Branch: docking

Back-ends: imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp 
Compiler: MSVC
Operating System: Windows 11

When enabling viewports with  `io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable` and setting `SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES , ...)` the viewport will lose color when the value given is above 16 (At least that is when I begin to lose color). When I query max samples with `glGetIntegerv(GL_MAX_SAMPLES , ...)` I get that my max samples is 32. I couldn't find anything in the issues here about this and reading through the code there doesn't seem to be anything saying it can't be that high (as far as I can tell I haven't read all the way through yet). Obviously it doesn't need to be that high since 16 is plenty of samples, but I am curious as to why this might be happening. My first thought was maybe the call was failing for some reason when passing in something > 16, but it returns 0 so it seems like it should work.

https://github.com/ocornut/imgui/assets/64506168/222749cc-a31e-4a11-93bd-eb4fe250ec84

Here the problem lines are commented and when the value is 16 everything works as expected but when set higher at all.
```
#include <Windows.h>
#include <iostream>

#include <SDL.h>
#include <glad/glad.h>
#include <imgui/imgui.h>
#include <imgui/backends/imgui_impl_sdl2.h>
#include <imgui/backends/imgui_impl_opengl3.h>

int _main() {
    if (SDL_Init(SDL_INIT_EVERYTHING) != 0) {
        std::cout << "SDL_Init Error: " << SDL_GetError() << std::endl;
        return 1;
    }

    SDL_Window* window = SDL_CreateWindow("Test ImGui" , 100 , 100 , 640 , 480 , SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE);
    if (window == nullptr) {
        std::cout << "SDL_CreateWindow Error: " << SDL_GetError() << std::endl;
        return 1;
    }

    SDL_GLContext gl_context = SDL_GL_CreateContext(window);
    if (gl_context == nullptr) {
        std::cout << "SDL_GL_CreateContext Error: " << SDL_GetError() << std::endl;
        return 1;
    }

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK , SDL_GL_CONTEXT_PROFILE_CORE);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION , 4);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION , 6);
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER , 1);
    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE , 8);
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS , 1);
    SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES , 16); // viewports work fine
    // SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES , 20); // viewports lose color outside of main window
    
    SDL_GL_SetSwapInterval(1);

    if (gladLoadGLLoader(SDL_GL_GetProcAddress) == 0) {
        std::cout << "Failed to initialize GLAD" << std::endl;
        return 1;
    }

    glClearColor(
        48 / 255.f  , 56 / 255.f , 
        126 / 255.f , 1.0f
    );
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();
    ImGui::StyleColorsDark();

    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable | ImGuiConfigFlags_ViewportsEnable; 

    ImGui_ImplSDL2_InitForOpenGL(window , gl_context);
    ImGui_ImplOpenGL3_Init("#version 460");
    
    bool running = true;
    while (running) {
        SDL_Event e;
        while (SDL_PollEvent(&e)) {
            switch (e.type) {
                case SDL_WINDOWEVENT:
                    switch (e.window.event) {
                        case SDL_WINDOWEVENT_CLOSE: running = false; break;
                        case SDL_WINDOWEVENT_RESIZED: glViewport(0 , 0 , e.window.data1 , e.window.data2);break;
                        default: break;
                    }
                break;
                case SDL_KEYDOWN:
                    switch (e.key.keysym.sym) {
                        case SDLK_ESCAPE: running = false; break;
                        default: break;
                    }
                case SDL_QUIT: running = false; break;
                default: break;
            }
            ImGui_ImplSDL2_ProcessEvent(&e);
        }
       
        glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplSDL2_NewFrame(window);
        ImGui::NewFrame();

        ImGui::DockSpaceOverViewport(ImGui::GetMainViewport()  , ImGuiDockNodeFlags_PassthruCentralNode);

        if (ImGui::Begin("Test Window")) {
            ImGui::Text("Why this go dim outside of the window?");
        }
        ImGui::End();

        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
        ImGui::UpdatePlatformWindows();
        ImGui::RenderPlatformWindowsDefault();
        SDL_GL_MakeCurrent(window , gl_context);
    
        SDL_GL_SwapWindow(window);
    }
        
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplSDL2_Shutdown();
    ImGui::DestroyContext();

    SDL_GL_DeleteContext(gl_context);
    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}

int WINAPI WinMain(HINSTANCE hInstance , HINSTANCE hPrevInstance , LPSTR lpCmdLine , int nCmdShow) {
    return _main();
}
```

**Comment by ocornut** [comment]
I don't know.
The issue looks like the framebuffer target has been change to use sRGB colorspace, but I don't know why this would have anything to do with multisampling. Maybe you should research this using raw OpenGL names rather than SDL specific ones to find more clues.

> Obviously it doesn't need to be that high since 16 is plenty of samples, but I am curious as to why this might be happening. 

Backends related issues have been very overwhelming and distracting from main library work, so if you don't have an actual problem I would prefer to not spend time investigating this.

**Comment by yockey88** [comment]
So far from my experiments it seems this only occurs when setting that specific SDL GL attribute for anti-aliasing the entire window, and I have yet to find any open gl calls that cause it so I think it might be SDL specific. No worries on if you can't get to it, I'll see if I can figure it out, if you do have a chance to look at this that would be cool but I understand wanting to focus on the main library.

**Comment by ocornut** [comment]
Causing this now. If you ever find the underlying reason would always be good to post it here for reference. And in the case there is something we can do about it from imgui backends point of view we would attempt to.
