### ISSUE TITLE
display large  image ( 16000 * 10000) using  ImGui::Image() 

### ISSUE THREAD

**Issue by zirid** [ocornut/imgui#6992]
I used the examples [Image Loading and Displaying Examples](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples)  to display  2000 * 2000 and 16000  * 10000 images .

for  the test I just modified the  (example_win32_directx11) demo and added the following : 

```
int my_image_width = 0;
int my_image_height = 0;
ID3D11ShaderResourceView* my_texture = NULL;
bool ret = LoadTextureFromFile("Path_to_Dir\\large_image.jpg", &my_texture, &my_image_width, &my_image_height);
```

 and in the update loop  :  

```
 ImGui::Text("pointer = %p", my_texture);
 ImGui::Text("size = %d x %d", my_image_width, my_image_height);
 ImGui::Image((void*)my_texture, ImVec2(my_image_width, my_image_height));
```

The image was loaded for both cases but was not displayed for the large image (16000 * 10000).

2000*2000
![display](https://github.com/ocornut/imgui/assets/31682698/9f5b5fac-504b-4948-878d-a559c7b8bae1)

16000 * 10000
![display2](https://github.com/ocornut/imgui/assets/31682698/c8981b20-91a1-4c0c-84dd-b3273051dcde)

**Comment by ocornut** [comment]
Hello,
If its RGBA uncompressed that’s a 1 GB image, it may not fit or not be accepted by the dx11 or driver layer.
You should use specialized texture formats or manage textures differently. This is not a dear imgui question but rather a dx11 so we cannot help you more here.
