### ISSUE TITLE
ColorEdit picker popup window issue 

### ISSUE THREAD

**Issue by chu65536** [ocornut/imgui#6996]
Hi!
I ve got several issues with ColorEdit. Especially with popup window.

**1. Preview outline color**
Is it possible to change preview square outline color?
I tried doing so with:
`ImGui::PushStyleColor(ImGuiCol_FrameBg, сolor);`
And it works perfectly, but this also affects popup window style. But i dont want it.

Outline indeed changed it color
![image](https://github.com/ocornut/imgui/assets/94391872/24fb9137-b3a8-45a6-b3e8-9b8eac2f9659) 
But popup window is now ruined 
![image](https://github.com/ocornut/imgui/assets/94391872/754fa549-2766-4ea8-a7a9-ad77bd2bfb9f)

**2. Popup window configuration** 
Is it possible to somehow configure colorpicker popup window?
I tried 
`ImGui::SetNextWindowSize(size);`
But this is not working as expected and also affects size of the square preview popup window.

Also i have noticed that picker popup window size depends on the font size, which is  kinda strange for me

ColorEdit with default font
![image](https://github.com/ocornut/imgui/assets/94391872/cb43ebec-1464-4993-8ee7-5f634cde0577)

ColorEdit with my custom font
![image](https://github.com/ocornut/imgui/assets/94391872/3d767920-2f94-48c0-a044-3af08451fc6d)

**Comment by ocornut** [comment]
We don't aim to support every possible styling variation.
It'd be simpler if you recreate this popup yourself, by assembling all elements (a ColorButton opening a popup, then inside the popup you can use ColorPicker, ColorButton, ColorEdit4 however you want).

**Comment by chu65536** [comment]
Yeah, sounds reasonable enough. I found workaround anyway. But the last thing (colorpicker popup size depends on the font size) is not so intuitive, isnt it?

**Comment by ocornut** [comment]
It needs to use an arbitrary size, and all arbitrary size should ideally be factor of font metrics to scale in all conditions. 
We currently use `12 * GetFrameHeight()`.

Possibly we need to expose better standardized metrics ("font height", "width of M", "average width of digits") but it won't make a big difference here.

**Comment by chu65536** [comment]
I see.
Thank you, issue is resolved then!
