### ISSUE TITLE
How do I dock to the sides of the window?

### ISSUE THREAD

**Issue by kaitabuchi314** [ocornut/imgui#6998]
I try to dock to the sides of the window with `ImGui::DockSpaceOverViewport();`. But now my SDL sprite disappears and my background color changes.

**Comment by PathogenDavid** [comment]
By default the dockspace has a background color (`ImGuiCol_DockingEmptyBg`) to represent the area of the central node when it is empty.

You can pass the `ImGuiDockNodeFlags_PassthruCentralNode` flag to `ImGui::DockSpaceOverViewport` to disable this behavior.

**Comment by kaitabuchi314** [comment]
Thanks! Works better than my hacky fix rendering imgui under everything!
