### ISSUE TITLE
Accepting input on text field losing 'focus'.

### ISSUE THREAD

**Issue by Cthutu** [ocornut/imgui#700]
I'm trying to solve a problem with input text fields.  Currently they only return true when enter is pressed (due to ImGuiInputTextFlags_EnterReturnsTrue flag), but I also want it to return true when TAB is pressed to go to next input field, or if the mouse is clicked elsewhere. 

A good example of where this is useful is in InputInt3 where pressing TAB is quite natural for people to accept an entry for the first int and move to the next int.

Any advice or is it just not possible with the current implementations?

**Comment by ocornut** [comment]
Hi,
Isn't just the default behavior aka returning true whenever changed, enough?

**Comment by Cthutu** [comment]
It doesn't behave the same way as Windows or Mac.  When tabbing to the next field or click outside the input field, the user doesn't expect their previous input to be reset.  The only time it is reset in these OS's is by pressing ESC.

For example, open notepad and go to the 'Save As...' dialog box.  Enter a filename and press TAB.  The filename you enter doesn't disappear.

It's not a showstopper, but I do try to aim for the Principle of Least Surprise when it comes to UIs.

**Comment by ocornut** [comment]
Err, the value should never be reset in ImGui unless you press Esc. If that this the case then it is a bug and that should be fixed instead of adding a new flag.

**Comment by Cthutu** [comment]
Interesting: in the demo, input float3 works when tab is pressed.  Let me
look at this more closely.

**Comment by Cthutu** [comment]
OK, the demo doesn't use the EnterReturnsTrue flag, which is why it works.  For example, I change the code in the demo to be:

```
if (ImGui::InputFloat3("input float3", vec4a, -1, ImGuiInputTextFlags_EnterReturnsTrue))
{
    ImGui::LogText("Changed");
}
```

When you press TAB now, it resets.

**Comment by ocornut** [comment]
Isn't that the point of that flag?
`ImGuiInputTextFlags_EnterReturnsTrue    = 1 << 5,   // Return 'true' when Enter is pressed (as opposed to when the value was modified)`

**Comment by Cthutu** [comment]
That flag is the only way to return true once when the input is done with.  Currently knowing when the input is done with is when you press 'enter', which is all well and good.  However, on modern operating systems, they decide when you've finish editing by 'enter', 'tab' or clicking elsewhere.  So, I am guess I am saying I really want this flag:

```ImGuiInputTextFlags_EnterTabClickElsewhereReturnsTrue```

:)

Of course, a ImGuiInputTextFlags_InputDoneReturnsTrue would be more sensible a name!

**Comment by ocornut** [comment]
Granted, ye then we'd need a new flag and to rework InputText accordingly. 
Though I am wondering if you are having issue with immediate update and what sort of issues? (I myself sometimes wanted non-immediate update)

**Comment by Cthutu** [comment]
Setting the xyz values of an object is something you don't live update on,
otherwise the object will be jumping about as you type :)
