### ISSUE TITLE
imgui_impl_sdl3.cpp includes an SDL3 file that has been deleted called "#include <SDL3/SDL_syswm.h>" and depends on it

### ISSUE THREAD

**Issue by spikeyamk** [ocornut/imgui#7000]
Unless I'd rewrite imgui_impl_sdl3.cpp it's impossible to build imgui against SDL3.

https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_syswmh

**Comment by ocornut** [comment]
SDL3 is not released and keeps evolving so breakage are common.
A PR fixing for latest would be welcome, otherwise I'll try to look next week.

**Comment by begui** [comment]
It appears there has been another recent change (in the last 24 hours) regarding gamepad support that is also causing a build failure. Fortunately, an easy fix

https://github.com/libsdl-org/SDL/commit/2991b9f6ac9b48cdb079ce36e62d1ccac935090f

**Comment by ocornut** [comment]
Pushed fixes add915b and 0941adc

**Comment by begui** [comment]
@ocornut one suggestion 
static void ImGui_ImplSDL3_SetupPlatformHandles(ImGuiViewport* viewport, SDL_Window* window)

SDL_Window is no longer used in this function ... this will fail with the -Werror-unused-parameter is set

**Comment by ocornut** [comment]
The value is used on some OS and also in docking branch. Pushed a fix for warning.
Which OS were you on @begui ? I worried that my new ifdef didn't work reliably:

```cpp
static void ImGui_ImplSDL3_SetupPlatformHandles(ImGuiViewport* viewport, SDL_Window* window)
{
    IM_UNUSED(window);
    viewport->PlatformHandleRaw = nullptr;
#if defined(__WIN32__) && !defined(__WINRT__)
    viewport->PlatformHandleRaw = (HWND)SDL_GetProperty(SDL_GetWindowProperties(window), "SDL.window.win32.hwnd", NULL);
#elif defined(__APPLE__) && defined(SDL_VIDEO_DRIVER_COCOA)
    viewport->PlatformHandleRaw = (void*)SDL_GetProperty(SDL_GetWindowProperties(window), "SDL.window.cocoa.window", NULL);
#endif
}
```
which part of the code executes for you?
