### ISSUE TITLE
problem with resizing on Vulkan+SDL2

### ISSUE THREAD

**Issue by HXMCPP** [ocornut/imgui#7003]
here is an example of what is happening, nothing is changed it's compiled from the examples : 
https://github.com/ocornut/imgui/assets/116516702/84dbd8a6-08d0-40fc-92a9-ef3906f3d1fa

**Comment by ocornut** [comment]
This is not a dear imgui specific issue but a Win32 API issue that needs a workaround on app side.
See #3672 #5728 #5076 #6010 #5728
