### ISSUE TITLE
Why won't the window open?

### ISSUE THREAD

**Issue by sy-project** [ocornut/imgui#7006]
Version/Branch of Dear ImGui
```
Version: 1.90 WIP
Branch: Docking
```

My Issue/Question:
I cant open ImGui Window in dx11.
what could be the problem?

My full source code is here
```
https://github.com/sy-project/yuuna
```
class "cSystem, Camera, Environment" called ImGui.

I initialized in cSystem Class.
ImGui Initialize Code is here
```c++
    IMGUI_CHECKVERSION();

    ImGui::CreateContext();

    ImGuiIO& io = ImGui::GetIO(); (void)io;
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
    io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;

    ImGui::StyleColorsDark();

    ImGuiStyle& imgui_style = ImGui::GetStyle();
    if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
    {
        imgui_style.WindowRounding = 0.0f;
        imgui_style.Colors[ImGuiCol_WindowBg].w = 1.0f;
    }

    ImGui_ImplWin32_Init(g_hWnd);
    ImGui_ImplDX11_Init(Device::Get()->GetDevice(), Device::Get()->GetDeviceContext());
```
And I rendering code is here. but I cant see the Test Window, show only DemoWindow.
```c++
    ImGui_ImplDX11_NewFrame();
    ImGui_ImplWin32_NewFrame();
    ImGui::NewFrame();
    static bool show_test = true;
    if (show_test) {
        if (ImGui::Begin("Test", &show_test, 1024)) {
            ImGui::Text("Test");
        }
        ImGui::End();
    }
    ImGui::ShowDemoWindow(&show_demo_window);
    Environment::Get()->PostRender();
    ImGui::Render();
    ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
    ImGui::UpdatePlatformWindows();
    ImGui::RenderPlatformWindowsDefault();
```
![image](https://github.com/ocornut/imgui/assets/42532250/dcf6897e-9d63-4cec-8edd-78b84030facd)

**Comment by GamingMinds-DanielC** [comment]
Same answer as in the discussion (saw that one first)...

From the Demo Window menu bar, select "Tools" -> "Metrics/Debugger". In that window expand "Windows" and take a closer look. Maybe your window is at a position where you cannot see it, in case you configured it in a strange way first and then those settings got saved. Deleting your imgui.ini might remedy that. If your window isn't listed there, you need to step through your code to find out why it doesn't get submitted.

Btw, it's a bad idea to use direct values like "1024" for flags, it just makes code harder to read, and error prone in case those values ever change in a new version. You can and should use the named enum values directly, `ImGuiWindowFlags_MenuBar` in this case.

**Comment by sy-project** [comment]
I selected "Tools" -> "Metrics/Debugger". But I cant find "Windows".
![image](https://github.com/ocornut/imgui/assets/42532250/9f160cbb-c4a1-4d92-9d62-2800f580be62)

I added debug pointer in Test Window. But it goes inside as you can see, but the window doesn't create like the image below.
![image](https://github.com/ocornut/imgui/assets/42532250/b3603d77-c730-4bd1-b759-30bb3aa5fd0e)

![image](https://github.com/ocornut/imgui/assets/42532250/0677eeda-bfef-4319-bb29-e86c9557c74f)

and i changed rendering source.

```c++
    ImGui_ImplDX11_NewFrame();
    ImGui_ImplWin32_NewFrame();
    ImGui::NewFrame();
    static bool show_test = true;
    if (show_test) {
        if (ImGui::Begin("Test", &show_test)) {
            ImGui::Text("Test");
        }
        ImGui::End();
    }
    ImGui::ShowDemoWindow(&show_demo_window);
    Environment::Get()->PostRender();
    ImGui::Render();
    ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
    ImGui::UpdatePlatformWindows();
    ImGui::RenderPlatformWindowsDefault();
```

**Comment by ocornut** [comment]
I suspect you are rendering everything just fine except your render is covered by a subsequent clear or another render. Try to click and drag around the viewport see if you can move the windows out to verify this.

**Comment by GamingMinds-DanielC** [comment]
> I selected "Tools" -> "Metrics/Debugger". But I cant find "Windows".

Metrics/Debugger should have opened another window where you then could have expanded a section called "Windows". But it seems you don't see any windows besides the demo window.

> I added debug pointer in Test Window. But it goes inside as you can see, but the window doesn't create like the image below.

A little bit of programming terminology: that's called a breakpoint.

> and i changed rendering source.

What do you mean by "rendering source"? The only thing different in this code snippet is that you changed the window flags from having a menu to not having a menu.

I took a quick look into your linked repository where you said your full source code was. I noticed there that you have an `imgui.ini` inside your repository. That doesn't belong there, it is automatically created in the working directory, seems you don't have that properly configured in Visual Studio. Anyway, in this ini file the demo window is the only one that references an explicit viewport, all of the other windows are part of your main window.

Like Omar, I also suspect that your windows do get rendered and that they are just invisible to you due to something else. Either the back buffer gets cleared or rendered over with something else, or you have the wrong render target configured when you render your windows.

Best tool for the job (as with any other rendering problems) is RenderDoc, make a capture there and you can analyze every single draw if needed.

**Comment by sy-project** [comment]
I deleted imgui.ini file. So, I can see my window. But I cant see multi window.

Now, I can see ImGui window in "Camera" class.
![image](https://github.com/ocornut/imgui/assets/42532250/ba269dc5-b522-4b61-b17e-57eb23021d2b)

But I want to see ImGui window in "Environment", "cSystem" class.
"Environment" class has "Environment" window, "cSystem" class has "Test" window.

in "cSystem" class
```c++
    ImGui_ImplDX11_NewFrame();
    ImGui_ImplWin32_NewFrame();
    ImGui::NewFrame();
    static bool show_test = true;
    if (show_test) {
        if (ImGui::Begin("Test", &show_test)) {
            ImGui::Text("Test");
        }
        ImGui::End();
    }
    ImGui::ShowDemoWindow(&show_demo_window);
    Environment::Get()->PostRender();
    ImGui::Render();
    ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
    ImGui::UpdatePlatformWindows();
    ImGui::RenderPlatformWindowsDefault();
```

in "Environment" class
```c++
	mainCamera->PostRender();
	//if(!ImGui::Begin("Test", &a, window_flags))
	//	ImGui::End();
	ImGui::Begin("Environment");
	ImGui::IsWindowAppearing();
	ImGui::Text("LightInfo");
	ImGui::ColorEdit4("AmbientColor", (float*)&lightBuffer->data.ambient);
	ImGui::ColorEdit4("AmbientCeilColor", (float*)&lightBuffer->data.ambientCeil);
	
	if (ImGui::Button("AddLight"))
	{
		lightBuffer->Add();
	}
	for (UINT i = 0; i < lightBuffer->data.lightCount; i++)
	{
		string name = "Light " + to_string(i);
		if (ImGui::BeginMenu(name.c_str()))
		{
			ImGui::Checkbox("Active", (bool*)&lightBuffer->data.lights[i].active);
			ImGui::SliderInt("Type", (int*)&lightBuffer->data.lights[i].type, 0, 3);
			ImGui::SliderFloat3("Direction", (float*)&lightBuffer->data.lights[i].direction, -1, 1);
			ImGui::SliderFloat3("LightPosition", (float*)&lightBuffer->data.lights[i].position, -100, 100);
			ImGui::SliderFloat("LightRange", (float*)&lightBuffer->data.lights[i].range, 0, 100);
			ImGui::ColorEdit4("LightColor", (float*)&lightBuffer->data.lights[i].color);			
			ImGui::SliderFloat("LightInner", (float*)&lightBuffer->data.lights[i].inner, 0, 90);
			ImGui::SliderFloat("LightOuter", (float*)&lightBuffer->data.lights[i].outer, 0, 180);
			ImGui::SliderFloat("LightLength", (float*)&lightBuffer->data.lights[i].length, 0, 180);			

			ImGui::EndMenu();
		}		
	}

	ImGui::End();
```

in "Camera" class
```c++
	ImGui::Begin("Camera");
	ImGui::IsWindowAppearing();
	ImGui::Text("CameraInfo");
	ImGui::Text("CamPos : %.1f, %.1f, %.1f", position.x, position.y, position.z);
	ImGui::Text("CamRot : %.1f, %.1f, %.1f", rotation.x, rotation.y, rotation.z);
	if (target == nullptr)
	{
		ImGui::SliderFloat("MoveSpeed", &moveSpeed, 0, 100);
		ImGui::SliderFloat("RotSpeed", &rotSpeed, 0, 10);
	}
	else
	{
		ImGui::SliderFloat("CamDistance", &distance, -10.0f, 100.0f);
		ImGui::SliderFloat("CamHeight", &height, -10.0f, 100.0f);
		ImGui::SliderFloat("CamMoveDamping", &moveDamping, 0.0f, 30.0f);
		ImGui::SliderFloat("CamRotDamping", &rotDamping, 0.0f, 30.0f);
		ImGui::SliderFloat3("CamOffset", (float*)&offset, -20.0f, 20.0f);
	}
	ImGui::Spacing();
	ImGui::End();
```

**Comment by GamingMinds-DanielC** [comment]
It doesn't help if you just post incomplete snippets of your code like this. First, step through your code with the debugger. It will help to see if your windows get submitted properly if you add the items conditionally based on the return value of `ImGui::Begin()`. If they get submitted, check your rendering with RenderDoc.

**Comment by sy-project** [comment]
I put this code in front of 「ImGui::Begin()」, and it's solved.
thanks.
```c++
    IM_ASSERT(ImGui::GetCurrentContext() != NULL && "Missing Dear ImGui context. Refer to examples app!");
    const ImGuiViewport* main_viewport = ImGui::GetMainViewport();
    ImGui::SetNextWindowPos(ImVec2(main_viewport->WorkPos.x + viewport_x, main_viewport->WorkPos.y + viewport_y), ImGuiCond_FirstUseEver);
    ImGui::SetNextWindowSize(ImVec2(550, 680), ImGuiCond_FirstUseEver);
    ImGuiWindowFlags window_flags = 0;
    window_flags |= ImGuiWindowFlags_MenuBar;
```

**Comment by ocornut** [comment]
Things points in the direction that you main viewport is redrawn over AFTER you render imgui. Please read our previous messages carefully.
