### ISSUE TITLE
StyleColor Push and Pop won't crash on release build

### ISSUE THREAD

**Issue by MayitaMayoso** [ocornut/imgui#7013]
```
Dear ImGui 1.89.7 WIP (18967)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=8
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000041
 NavEnableKeyboard
 DockingEnable
io.ConfigViewportsNoTaskBarIcon
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 2048,4096
io.DisplaySize: 2560.00,1362.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Version/Branch of Dear ImGui:**

Version: 1.89.7
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.h + imgui_impl_opengl3.h
Compiler: GNUC
Operating System: Debian 10

**My Issue/Question:**

On release build, the assert that checks the StyleColor stack won't work. This will make the program not crash when having mismatched push and pops for the colors on the elements and make the whole app behave unexpectedly.
This is not a problem itself since many compilers stripes the assertions but here the issue is that when fixing the code and adding the missing PopStyleColor or even deleting the PushStyleColor we made on the first place, the Colors stack will still be filled with the color we used on the previous wrong execution. No matter if we rebuild the project, delete ImGui.ini or restart the computer in case of rubbish data persisting on ram.

As an example to recreate this issue it would be as simple as the following
```
ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(1.0, 0.0, 0.0, 1.0));
ImGui::Begin("Test");
ImGui::End()
```
Here we can see how the PushStyleColor is missmatched then on a bigger application this will turn everything red. Next if we rebuild and execute the very same code but with the PushStyleColor commented or deleted, the color will still be there.
```
// ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(1.0, 0.0, 0.0, 1.0));
ImGui::Begin("Test");
ImGui::End()
```

**Comment by ocornut** [comment]
> Here we can see how the PushStyleColor is missmatched then on a bigger application this will turn everything red. Next if we rebuild and execute the very same code but with the PushStyleColor commented or deleted, the color will still be there.

This is almost certainly an incorrect statement. You are omitting something, there's no way this would happen.

As for your main question: IM_ASSERT is here to catch programming errors, you should keep them enabled in optimized builds.
If you have disabled them then, well, they ar edisabled as you intended it. You probably shouldn't disable asserts for dear imgui.

**Comment by MayitaMayoso** [comment]
The decision of turning on or off the asserts on the compiler is not mine since this is a project at my workplace. Actually my question is more on the side of how could I "clean" the status of imgui after execution because if I have a missmatched StyleColor, execute, then fix the error on the code and then execute again, the color will persist. So far the way of fixing this for me was to commit the same mistake but with the original color.
Also I wanna clarify this happens on the render event so this mismatched PushStyleColor will increase the color stack by 1 on every frame. There comes my conclusion that the color stack is keeping its values between executions.

**Comment by ocornut** [comment]
> The decision of turning on or off the asserts on the compiler is not mine since this is a project at my workplace. A

If it is your workplace by definition you can contribute to changes there. 
Everyone has a different definition of what a "Release build" is (optimized, with/without assert, internal/shipping) but you could perfectly enable dear imgui asserts without enabling other asserts in your engine.

Your initial message suggested that could rebuild application, delete ini files and there would be leftovers data. This is misleading and most likely incorrect.
I suspect you are referring to some hot reload mechanism during a same running session, which is a different thing.

You may call `ErrorCheckEndFrameRecover()` from imgui_internal.h before `EndFrame()` to clear the state.

**Comment by MayitaMayoso** [comment]
After further investigation it turns out we have a thirdParty [SaveStyle](https://gist.github.com/Flix01/2c6e06b4a4f93016c334) function that among other things, it reads the content of ImGui::GetStyle().Colors and saves them into a file to later read them on another execution to have the same colors. I'm not familiar with how the colors and stacks work internally but I'm certain there was a collision there. I leave this comment in case someone faces the same issue as me. Thank you Omar for guiding me into the solution!
