### ISSUE TITLE
Can imgui use same label for ImGui::Combo  or ImGui::InputInt ?

### ISSUE THREAD

**Issue by liulover5** [ocornut/imgui#7019]
req:
1，Can imgui use same label for ImGui::Combo  or ImGui::InputInt （two widget neighbouring ）?
2，Can imgui  Hide（or without） label for ImGui::Combo  or ImGui::InputInt ？
3，Can I display label  on the left of widget （ImGui::Combo  or ImGui::InputInt）？

code:
			const char* items[] = { "AAAA", "BBBB", "CCCC", "DDDD" };
			static int item_current = 0;
			ImGui::Combo("combo", &item_current, items, IM_ARRAYSIZE(items));

			const char* keys[] = { "AAAA", "BBBB", "CCCC", "DDDD"};
			static int keys_current = 0;
			ImGui::Combo("combo", &keys_current, keys, IM_ARRAYSIZE(keys));

			static int counter = 0;
			ImGui::InputInt("label", &counter);
			static int number = 0;
			ImGui::InputInt("label", &number);

**Comment by ocornut** [comment]
1 and 2 are answered in the FAQ.
3: no, but you can use tables for this.
