### ISSUE TITLE
Multiple window creation component no message event

### ISSUE THREAD

**Issue by 1540781622** [ocornut/imgui#7023]
Version/Branch of Dear ImGui:
Version: 1.90.1 WIP
Branch: master

Compiler  vs2022
OS: windows10

My Issue/Question:
Hello, I am currently working on a project that requires the creation of two Windows windows. I'm looking to create components separately in each window, and I'm wondering if you have any examples related to this. The reason is that my own code has some bugs, such as issues with moving and clicking events, which are not functioning properly.

My code:
`#define GLFW_EXPOSE_NATIVE_WIN32
#include "GLFW/glfw3.h"
#include "GLFW/glfw3native.h" 

#include "ImGui/imgui.h"
#include "ImGui/imgui_impl_glfw.h"
#include "ImGui/imgui_impl_opengl3.h"
#include <Windows.h>
#include <d3d11.h>
#define HEAD_TO_FONT19(FONTSIZE)  io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\msyhbd.ttc", FONTSIZE, nullptr, io.Fonts->GetGlyphRangesChineseFull());

bool open = true;

int main() {
    if (!glfwInit()) {
        return -1;
    }
    
    //glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE);
    glfwWindowHint(GLFW_DECORATED, GLFW_FALSE);
    glfwWindowHint(GLFW_FLOATING, GLFW_TRUE); 
    GLFWwindow* window1 = glfwCreateWindow(700, 600, "Window 1", NULL, NULL);

    glfwWindowHint(GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_FALSE);
    glfwWindowHint(GLFW_DECORATED, GLFW_TRUE);
    glfwWindowHint(GLFW_FLOATING, GLFW_TRUE); 
    GLFWwindow* window2 = glfwCreateWindow(700, 600, "Window 2", NULL, window1);

    if (!window1 || !window2) {
        if (window1) glfwDestroyWindow(window1);
        if (window2) glfwDestroyWindow(window2);
        glfwTerminate();
        return -1;
    }

    HWND hwnd1 = glfwGetWin32Window(window1);
    HWND hwnd2 = glfwGetWin32Window(window2);
    LONG style1 = GetWindowLong(hwnd1, GWL_EXSTYLE);
    LONG style2 = GetWindowLong(hwnd2, GWL_EXSTYLE);
    SetWindowLong(hwnd1, GWL_EXSTYLE, style1 | WS_EX_LAYERED | WS_EX_TRANSPARENT);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();

    glfwMakeContextCurrent(window1);
    ImGui_ImplGlfw_InitForOpenGL(window1, true);

    glfwMakeContextCurrent(window2);
    ImGui_ImplGlfw_InitForOpenGL(window2, true);

    ImGui_ImplOpenGL3_Init(); 

    ImGuiIO& io = ImGui::GetIO(); (void)io;
    HEAD_TO_FONT19(18.f)

    while (!glfwWindowShouldClose(window1) && !glfwWindowShouldClose(window2)) {

        glfwPollEvents();

        glfwMakeContextCurrent(window1);
        ImGui_ImplGlfw_NewFrame();

        ImGui_ImplOpenGL3_NewFrame();
        ImGui::NewFrame();

        ImGui::Begin("BEGIN 1 !");
        //ImGui::Text("This is some text in an ImGui window.");
        ImGui::Text("%.0fFPS", io.Framerate);
        ImGui::End();
        //—————————————————————
        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
        glfwSwapBuffers(window1);
        //—————————————————————

        glfwMakeContextCurrent(window2);
        ImGui_ImplGlfw_NewFrame();
        ImGui_ImplOpenGL3_NewFrame();
        ImGui::NewFrame();

        ImGui::SetNextWindowSize({ 390,390 }, 0 << 3);
        ImGui::Begin("BEGIN 2 !", &open);
        ImGui::Text(u8"text2");

        ImGui::End();

        //—————————————————————
        ImGui::EndFrame();
        ImGui::Render();
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
        glfwSwapBuffers(window2);
    }

    
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();

    glfwDestroyWindow(window1);
    glfwDestroyWindow(window2);
    glfwTerminate();
    return 0;
}`

**Comment by ocornut** [comment]
```cpp
IMGUI_CHECKVERSION();
ImGui::CreateContext();
```

You need to call `CreateContext()` twice, store the context pointer and use `ImGui::SetCurrentContext()` to change context.

**Comment by 1540781622** [comment]
Could you give me a rough example?

**Comment by ocornut** [comment]
Anytime you call a ImGui:: or ImGui backend function it behave on the current context.

```cpp
ImGuiContext* ctx1 = ImGui::CreateContext();
ImGuiContext* ctx2 = ImGui::CreateContext();
```

```cpp
ImGui::SetCurrentContext(ctx1);
glfwMakeContextCurrent(window1);
ImGui_ImplGlfw_InitForOpenGL(window1, true);

ImGui::SetCurrentContext(ctx2);
glfwMakeContextCurrent(window2);
ImGui_ImplGlfw_InitForOpenGL(window2, true);
```
etc.

Then each window will work on its context.

**Comment by 1540781622** [comment]
Thanks, I've successfully achieved what I wanted.

**Comment by ocornut** [comment]
This may not work if you use pre-installed GLFW callbacks, see #7155
