### ISSUE TITLE
ImGui window background alpha becomes black when value 0.0f

### ISSUE THREAD

**Issue by Juesril** [ocornut/imgui#7029]
So I want to create a program that will run only with an ImGui, so first of all I did create a program for imgui to render to in d3d9
and then I modified the resolution size to 30x30 and Update the window to SW_HIDE so the ImGui Window will be forced outside the window it was a success, then I decided to modify the opacity of the imgui window.

If the window is active then make the opacity 1.0f if not active then make it 0.3f, but then it does not do any effect, the opacity 0.0f will just give me a dark background and doesn't have the effect I was hoping for.

Edit: It wasn't dark background, there's really no effect like no transparent effect of window

**Comment by ocornut** [comment]
Hello,
See #6558 #5988 #2766 #2764
