### ISSUE TITLE
DragInt text gets cut off

### ISSUE THREAD

**Issue by learn-more** [ocornut/imgui#7030]
**Version/Branch of Dear ImGui:**

```
Dear ImGui 1.90.0 (19000)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1937
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000443
 NavEnableKeyboard
 NavEnableGamepad
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoAutoMerge
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**My Issue/Question:**

The text inside my DragInt is falling off the screen, although it seems that there should be enough space for it, seeing the window is already fairly wide.

**Screenshots/Video**

(The word 'Size' is falling off the window completely)
![image](https://github.com/ocornut/imgui/assets/610685/1a8c41a3-410f-46e3-84fb-85f00d53c7fe)

**Standalone, minimal, complete and verifiable example:**
```
    ImGui::SetNextWindowSize(ImVec2(500, 600), ImGuiCond_FirstUseEver);
    static bool open = true;
    ImGui::Begin("Job object debug", &open);
    if (ImGui::CollapsingHeader("Basic Limits"))
    {
        ImGui::Indent();

        static int LimitFlags = 0;
        ImGui::CheckboxFlags("JOB_OBJECT_LIMIT_WORKINGSET", &LimitFlags, 1);
        if (LimitFlags & 1)
        {
            ImGui::Indent();

            static int minimumWS = 0;
            static int maximumWS = 0;
            ImGui::DragInt("MinimumWorkingSetSize", &minimumWS, 1, 0, 0x10000, "%d kb", ImGuiSliderFlags_AlwaysClamp);
            ImGui::DragInt("MaximumWorkingSetSize", &maximumWS, 1, 0, 0x10000, "%d kb", ImGuiSliderFlags_AlwaysClamp);

            ImGui::Unindent();
        }

        ImGui::Unindent();
    }

    ImGui::End();
```

I have made some small changes to the example 'main' code, but I *expect* that they do not influence this:
* Disabled the `::ShowWindow(hwnd, SW_SHOWDEFAULT);` call, so the 'main' window stays hidden
* Added:
  * `io.IniFilename = nullptr;`
  * `io.ConfigViewportsNoAutoMerge = true;`
  * (Both before the `ImGui::StyleColorsDark();`)

**Comment by PathogenDavid** [comment]
The width of item-style widgets like `DragInt` does not take into account the size of the label. (The default behavior is that they're [65% of the window width](https://github.com/ocornut/imgui/blob/3733b5064e1820dc8517fedba2b34bfbdef569ab/imgui.cpp#L6842-L6846))

You can control this width using `Push/PopItemWidth` or `SetNextItemWidth`:

https://github.com/ocornut/imgui/blob/3733b5064e1820dc8517fedba2b34bfbdef569ab/imgui.h#L428-L431

If you can enumerate all of your labels you could calculate the width of the longest one and use that to calculate your item size, for example:

```cpp
static int minimumWS = 0;
const char* label = "MinimumWorkingSetSize";
ImGui::SetNextItemWidth(-(ImGui::CalcTextSize(label).x + ImGui::GetStyle().ItemInnerSpacing.x));
ImGui::DragInt(label, &minimumWS, 1, 0, 0x10000, "%d kb", ImGuiSliderFlags_AlwaysClamp);
```

(Although do note this specific example potentially allows the widgets to be squished into a 1 pixel-wide sliver.)

**Comment by ocornut** [comment]
Also see "Demo->Layout & Scrolling->Widgets Width" for details about aforementioned API.

You might also use a table (`BeginTable()` etc.) with two columns, use -FLT_MIN width and hidden label (`"##label"`) on the first column, and visible labels in the second column.

**Comment by learn-more** [comment]
Awesome, thanks for the support!
