### ISSUE TITLE
Internal ImGui IME visible problem

### ISSUE THREAD

**Issue by xChoi-Kta** [ocornut/imgui#7034]
I am coding an internal Imgui program with win32 directx9. But I have a problem with IME (Input Method Editor) for transform to Chinese.
When I coding external imgui program with this same codes, the IME successfully showing. But when I coding internal imgui program, the IME box unfortunately not visible.
I pressing a button on keyboard, IME not visible but when I click 1 button, Chinese character writing successfully.
Since I couldn't solve this problem, I added an external input dialog editor. But the problem is the same. Again IME does not appear.

I am opening this issue here. because I only have IME problem on ImGui. and I don't know how to use IME with ImGui.

I added this: [SGInputBox](https://github.com/haephrati/SGInputBox)

(my ImGui version: dear imgui, v1.80 WIP)

external :

https://github.com/ocornut/imgui/assets/62267222/a557e451-6551-4af2-8904-d5fceedb8f5e

internal : (IME box not visible, but I pressed "1", and writing Chinese characters successfully.)

https://github.com/ocornut/imgui/assets/62267222/dc465659-6bc5-41b2-8a7b-454cf11b7cd7

I already added these to my project :

`#include` <imm.h>
#pragma comment(lib, "imm32")
#pragma execution_character_set("utf-8")

io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\simsun.ttc", 16, nullptr, io.Fonts->GetGlyphRangesChineseFull());
`io.Fonts->Build();`

my WndProc funct:

LRESULT CALLBACK WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
	if (Options::IsMenuVisible)
	{
		ImGuiIO& io = ImGui::GetIO();
		io.ImeWindowHandle = hWnd;
		switch (msg)
		{
		case WM_LBUTTONDOWN:
			io.MouseDown[0] = true;
			break;
		case WM_LBUTTONUP:
			io.MouseDown[0] = false;
			break;
			case WM_RBUTTONDOWN:
			io.MouseDown[1] = true;
			break;
		case WM_RBUTTONUP:
			io.MouseDown[1] = false;
			break;
		case WM_MBUTTONDOWN:
			io.MouseDown[2] = true;
			break;
		case WM_MBUTTONUP:
			io.MouseDown[2] = false;
			break;
		case WM_MOUSEWHEEL:
			io.MouseWheel += GET_WHEEL_DELTA_WPARAM(wParam) > 0 ? +1.0f : -1.0f;
			break;
			break;
		case WM_MOUSEMOVE:
			io.MousePos.x = (signed short)(lParam);
			io.MousePos.y = (signed short)(lParam >> 16);
			break;
		case WM_KEYDOWN:
			if (wParam < 256)
				io.KeysDown[wParam] = 1;
			break;
		case WM_KEYUP:
			if (wParam < 256)
				io.KeysDown[wParam] = 0;
			break;
		case WM_CHAR:
			if (wParam > 0 && wParam < 0x10000)
				io.AddInputCharacter((unsigned short)wParam);
			break;
		}

		if (io.WantCaptureMouse || io.WantCaptureKeyboard || io.WantTextInput)
		{
			return true;
		}
	}
	return CallWindowProc(oWndProc, hWnd, msg, wParam, lParam);
}

**Comment by xChoi-Kta** [comment]
Even if I remove the function named SGInputBox that I added, the problem is the same. IME box does not appear.


https://github.com/ocornut/imgui/assets/62267222/f45e17a6-0d5e-4a22-bd8d-672591690b02

**Comment by xChoi-Kta** [comment]
Looks like I found the source of the problem. But I'm not exactly sure. I used a different project that used ImGui. This project uses Detours for DirectX hook operation. And IME appears without any problems. I use Polyhook2 for DirectX hook operation in my own project. I suspect the problem may be in the hook system or the EndScene or ResetScene functions.

**Comment by ocornut** [comment]
Closing as self answered. I don't think we would have enough data to help you either way. Question has little to do with dear imgui.
