### ISSUE TITLE
ImGui Docking Transparent Window ( MUST CHECK!!! )

### ISSUE THREAD

**Issue by Juesril** [ocornut/imgui#7035]
This is a window with WindowBg Color of ImVec4(0,0,0,0) inside the window
![image](https://github.com/ocornut/imgui/assets/45968231/af8fde9d-fd9e-413e-8602-2dccf3f68f10)

And this is how it looks outside its windows
![image](https://github.com/ocornut/imgui/assets/45968231/6393d281-9542-4b81-90f8-e69ee1038249)

and this is the window when Im about to dock it onto the other imgui window
![image](https://github.com/ocornut/imgui/assets/45968231/d3ea57fc-7537-470e-8102-a9581a500b36)

Why does opacity effect gone when outside of parent window, but works when docking it????

**Comment by Juesril** [comment]
I want a floating text on the desktop, please help me make this..

**Comment by sakiodre** [comment]
In order to achieve this, you must make a little modification to imgui. Because you didn't care enough to fill out the issue template, I'm just gonna assume you use DirectX 11 on Windows.

imgui_impl_win32.cpp [`ImGui_ImplWin32_CreateWindow`](https://github.com/ocornut/imgui/blob/ce0d0ac8298ce164b5d862577e8b087d92f6e90e/backends/imgui_impl_win32.cpp#L1044)

```diff
@@ -1042,6 +1042,9 @@ static void ImGui_ImplWin32_CreateWindow(ImGuiViewport* viewport)
     vd->HwndOwned = true;
     viewport->PlatformRequestResize = false;
     viewport->PlatformHandle = viewport->PlatformHandleRaw = vd->Hwnd;
+
+    MARGINS margins = { -1 };
+    DwmExtendFrameIntoClientArea(vd->Hwnd, &margins);
 }
```

imgui_impl_dx11.cpp [`ImGui_ImplDX11_RenderWindow`](https://github.com/ocornut/imgui/blob/ce0d0ac8298ce164b5d862577e8b087d92f6e90e/backends/imgui_impl_dx11.cpp#L709C5)
```diff
@@ -706,10 +706,9 @@ static void ImGui_ImplDX11_RenderWindow(ImGuiViewport* viewport, void*)
 {
     ImGui_ImplDX11_Data* bd = ImGui_ImplDX11_GetBackendData();
     ImGui_ImplDX11_ViewportData* vd = (ImGui_ImplDX11_ViewportData*)viewport->RendererUserData;
-    ImVec4 clear_color = ImVec4(0.0f, 0.0f, 0.0f, 1.0f);
+    ImVec4 clear_color = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
     bd->pd3dDeviceContext->OMSetRenderTargets(1, &vd->RTView, nullptr);
-    if (!(viewport->Flags & ImGuiViewportFlags_NoRendererClear))
-        bd->pd3dDeviceContext->ClearRenderTargetView(vd->RTView, (float*)&clear_color);
+    bd->pd3dDeviceContext->ClearRenderTargetView(vd->RTView, (float*)&clear_color);
     ImGui_ImplDX11_RenderDrawData(viewport->DrawData);
 }
```

imgui.cpp [`RenderWindowDecorations`](https://github.com/ocornut/imgui/blob/ce0d0ac8298ce164b5d862577e8b087d92f6e90e/imgui.cpp#L6489)
```diff
@@ -6486,7 +6486,6 @@ void ImGui::RenderWindowDecorations(ImGuiWindow* window, const ImRect& title_bar
             ImU32 bg_col = GetColorU32(GetWindowBgColorIdx(window));
             if (window->ViewportOwned)
             {
-                bg_col |= IM_COL32_A_MASK; // No alpha
                 if (is_docking_transparent_payload)
                     window->Viewport->Alpha *= DOCKING_TRANSPARENT_PAYLOAD_ALPHA;
             }
```
![image](https://github.com/ocornut/imgui/assets/136492105/3dd7e8b6-4357-4e9a-ae39-7a321a0d2c7d)

## Important Note
`DwmExtendFrameIntoClientArea` only works with `DXGI_SWAP_EFFECT_DISCARD` so this won't work for DirectX 12. If you want to use DirectX 12, you must find other methods to make the window transparent.

**Comment by ocornut** [comment]
Also see https://github.com/ocornut/imgui/issues/6558 https://github.com/ocornut/imgui/issues/5988 https://github.com/ocornut/imgui/pull/2766 https://github.com/ocornut/imgui/issues/2764

**Comment by Juesril** [comment]
> In order to achieve this, you must make a little modification to imgui. Because you didn't care enough to fill out the issue template, I'm just gonna assume you use DirectX 11 on Windows.
> 
> imgui_impl_win32.cpp [`ImGui_ImplWin32_CreateWindow`](https://github.com/ocornut/imgui/blob/ce0d0ac8298ce164b5d862577e8b087d92f6e90e/backends/imgui_impl_win32.cpp#L1044)
> 
> ```diff
> @@ -1042,6 +1042,9 @@ static void ImGui_ImplWin32_CreateWindow(ImGuiViewport* viewport)
>      vd->HwndOwned = true;
>      viewport->PlatformRequestResize = false;
>      viewport->PlatformHandle = viewport->PlatformHandleRaw = vd->Hwnd;
> +
> +    MARGINS margins = { -1 };
> +    DwmExtendFrameIntoClientArea(vd->Hwnd, &margins);
>  }
> ```
> 
> imgui_impl_dx11.cpp [`ImGui_ImplDX11_RenderWindow`](https://github.com/ocornut/imgui/blob/ce0d0ac8298ce164b5d862577e8b087d92f6e90e/backends/imgui_impl_dx11.cpp#L709C5)
> 
> ```diff
> @@ -706,10 +706,9 @@ static void ImGui_ImplDX11_RenderWindow(ImGuiViewport* viewport, void*)
>  {
>      ImGui_ImplDX11_Data* bd = ImGui_ImplDX11_GetBackendData();
>      ImGui_ImplDX11_ViewportData* vd = (ImGui_ImplDX11_ViewportData*)viewport->RendererUserData;
> -    ImVec4 clear_color = ImVec4(0.0f, 0.0f, 0.0f, 1.0f);
> +    ImVec4 clear_color = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
>      bd->pd3dDeviceContext->OMSetRenderTargets(1, &vd->RTView, nullptr);
> -    if (!(viewport->Flags & ImGuiViewportFlags_NoRendererClear))
> -        bd->pd3dDeviceContext->ClearRenderTargetView(vd->RTView, (float*)&clear_color);
> +    bd->pd3dDeviceContext->ClearRenderTargetView(vd->RTView, (float*)&clear_color);
>      ImGui_ImplDX11_RenderDrawData(viewport->DrawData);
>  }
> ```
> 
> imgui.cpp [`RenderWindowDecorations`](https://github.com/ocornut/imgui/blob/ce0d0ac8298ce164b5d862577e8b087d92f6e90e/imgui.cpp#L6489)
> 
> ```diff
> @@ -6486,7 +6486,6 @@ void ImGui::RenderWindowDecorations(ImGuiWindow* window, const ImRect& title_bar
>              ImU32 bg_col = GetColorU32(GetWindowBgColorIdx(window));
>              if (window->ViewportOwned)
>              {
> -                bg_col |= IM_COL32_A_MASK; // No alpha
>                  if (is_docking_transparent_payload)
>                      window->Viewport->Alpha *= DOCKING_TRANSPARENT_PAYLOAD_ALPHA;
>              }
> ```
> 
> ![image](https://user-images.githubusercontent.com/136492105/284308610-3dd7e8b6-4357-4e9a-ae39-7a321a0d2c7d.png)
> 
> ## Important Note
> `DwmExtendFrameIntoClientArea` only works with `DXGI_SWAP_EFFECT_DISCARD` so this won't work for DirectX 12. If you want to use DirectX 12, you must find other methods to make the window transparent.

I am so sorry for not giving you details, I hope you provide the code once again with dx9 :( im really sorry

**Comment by Juesril** [comment]
Already fixed, Thank you so much sakiodre <3
