### ISSUE TITLE
render quad / polygonal text

### ISSUE THREAD

**Issue by Ripz1337** [ocornut/imgui#7037]
does anyone know how to draw perspective text (like AddImageQuad)?

**Comment by GamingMinds-DanielC** [comment]
https://github.com/ocornut/imgui/issues/6977

**Comment by GamingMinds-DanielC** [comment]
> I did not find the answer in the topic you indicated

There is no answer to your question. It is not supposed to be an answer to your question. But there is a detailed explanation for why you can't expect an answer to a lazy question like this. If a topic gets closed with a good reason, you don't get to just open another identical one while completely ignoring the stated reason.

**Comment by sakiodre** [comment]
Just to be clear, AddImageQuad is **not** perspective, this is because `ImDrawVert` doesn't have a z position, and the default vertex shader doesn't output the W position. As suggested in #3994, this is outside of Dear ImGui's scope and you'll have to figure out how to do that on your own.
