### ISSUE TITLE
Request/Inquiry: Node-RED like indicators 

### ISSUE THREAD

**Issue by muellerryan** [ocornut/imgui#7038]
There's no bug or issue here, I'm just not sure where else to ask questions about third-party add-ons. 

Has anybody seen or found a repo for Node-RED-like of indicators for imgui? See below image:
![image](https://github.com/ocornut/imgui/assets/43647235/7b0fc1a4-fd5f-40de-9682-ed264d1add91)

I have an application that is going to be monitoring various types of data points, and spoofing a loading bar or implot-type graph to show the data visually doesn't sound very appealing for both me or the end-user.  

I'm aware that I can make my own shapes, and I have started working with that.  I was just wondering if anybody made such a tool, similar to dalerank's imspinner repo where one can simply decide on style, and give the parameters you want into the spinner function. 

I have also looked at the gallery's and the third-party extension page with little luck. 

Any help would be appreciated!

**Comment by GamingMinds-DanielC** [comment]
> I'm aware that I can make my own shapes, and I have started working with that.

Looks like this is the way to go. Luckily, making custom widgets is not as hard as it may seem at first. If you just need them as displays and don't need them to be configurable in detail, it can be as simple as submitting an invisible button, getting its position and dimensions as reference, getting the draw list and drawing whatever you need.

**Comment by ocornut** [comment]
See extensions such as imgui-knobs and imspinner for inspiration/references of how to code this kind of things.

https://github.com/ocornut/imgui/wiki/Useful-Extensions#knobs
https://github.com/ocornut/imgui/wiki/Useful-Extensions#spinners

It may be useful to create a small library of the same kind as those to display widgets like the ones you want.

**Comment by muellerryan** [comment]
> Looks like this is the way to go. Luckily, making custom widgets is not as hard as it may seem at first. If you just need them as displays and don't need them to be configurable in detail, it can be as simple as submitting an invisible button, getting its position and dimensions as reference, getting the draw list and drawing whatever you need.

It certainly feels daunting trying it out. I probably just need to spend some time on it. Thanks for the tip!
If I am feeling extra motivated I'll create a small repository myself to share. 

> See extensions such as imgui-knobs and imspinner for inspiration/references of how to code this kind of things.

Thanks for the reference. I'm looking at those two right now trying to work on this.

**Comment by ocornut** [comment]
Closing as answered. Feel free to post updates/screenshotsif you ended up writing nice widgets!
