### ISSUE TITLE
Are `ImGuiKey` enum's integer values static?

### ISSUE THREAD

**Issue by smilediver** [ocornut/imgui#7042]
My question is, are the new `ImGuiKey` enum's integer values static, or they can change in the future? If they are not, I would suggest moving towards freezing them in the future. Also it would be great to clarify this in `ImGuiKey`'s comments.

Our use case is that we have a possibility to use ImGui remotely by connecting through a browser. Right now we convert web keys to an intermediate key code, and on the app side convert it to `ImGuiKey`. Freezing enum's values would help to get rid of this intermediate step and just use `ImGuiKey` everywhere.

**Comment by ocornut** [comment]
We don’t guarantee forward ABI compatibility, so everything can change even if in practice those are unlikely to change much.

Well behaved software such as netImgui or imgui-ws in theory should be compiled from same version, or I suppose could send the key name/value pairs accross the network, you can do the same if you want. You should convert web values to key name and send that accross the network.
