### ISSUE TITLE
ImGui color mismatch

### ISSUE THREAD

**Issue by Annien2067122** [ocornut/imgui#7048]
When I draw a rectangle with RGB Color[210, 77, 210] in ImGui, I’m getting the color difference between actual color and Imgui displayed color.

I have attached screenshots showing the color difference. First one is the actual RGB Color and second screenshot is ImGui plotted color.

Can you please explain what is the issue here.

Thank you!

Version : v1.87
Back-end : OpenGL
Operating System : macOS
Development Environment: Visual Studio Code

<img width="297" alt="Original_RGB_color" src="https://github.com/ocornut/imgui/assets/151706413/b5f440dd-aa9e-4664-a3d5-6db230a85df3">
<img width="246" alt="ImGui_RGB_Color" src="https://github.com/ocornut/imgui/assets/151706413/26bd2fdb-321a-4801-b188-0e2a449949a3">

**Comment by ocornut** [comment]
You have asked the same question yesterday #7040 and the answer is the same. Maybe ask on graphics programming forums. This may have to do with srgb framebuffer setup.
