### ISSUE TITLE
Drag and drop draw rect not expanded for Selectable inside a table

### ISSUE THREAD

**Issue by arnaud-neny** [ocornut/imgui#7049]
Version: 1.90
Branch: docking

Compiler: win32
Operating System: Windows10

When doing a drag and drop after a Selectable inside a table, the draw rect of the drag and drop is not expanded anymore to the selectable but only to the first column width. This was working fine on the previous versions (1.89.90)

![imguidnd](https://github.com/ocornut/imgui/assets/11290167/326d8b26-0936-4c4e-a01a-518206f24e8c)

// Here's some code anyone can copy and paste to reproduce your issue (add it after the Selectable in the advanced table sample in the demo)
if (ImGui::BeginDragDropSource(ImGuiDragDropFlags_SourceNoPreviewTooltip))
{
  ImGui::SetDragDropPayload("TESTDRAW", nullptr, 0);
  ImGui::EndDragDropSource();
}
if (ImGui::BeginDragDropTarget())
{
  ImGui::AcceptDragDropPayload("TESTDRAW");
  ImGui::EndDragDropTarget();
}
```

**Comment by ocornut** [comment]
Pushed fix bce4db0.
