### ISSUE TITLE
Add support for Push Descriptors in lieu of Descriptor Pools/Sets.

### ISSUE THREAD

**Issue by Yaazarai** [ocornut/imgui#7051]
Version: N/A
Branch: N/A
Back-ends: GLFW/VULKAN
Compiler: MSVC++
Operating System: Win11

Currently IMGUI requires you to create and pass a descriptor pool with support for "VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER" for font images.

Please add support for push descriptors in lieu of descriptor pools/sets.

**Comment by ocornut** [comment]
I do not know what that means and I would need someone to thoughtfully explore the design space for it and convey it to me with eg maybe a PR. If you want to move this forward.

**Comment by Yaazarai** [comment]
Okay this was my bad, I jumped the gun and didn't realize ImGUI creates its own back-end graphics pipeline. Anyways Push Descriptors essentially allow the drivers to manage your descriptor allocations instead of you, but it has limitations.

In this case all I needed to do was match the example, pass in a `VkDescriptorPool` specifically for `VK_COMBINED_IMAGE_SAMPLER` descriptors and voila.
