### ISSUE TITLE
docking tab selection on touch screens

### ISSUE THREAD

**Issue by jrynkiew** [ocornut/imgui#7052]
Version: 1.90.0 (190000)
Branch: docking

imgui_impl_sdl2.cpp + imgui_impl_sdlrenderer.cpp
Compiler: emcc
Operating System: Web

I am using imgui in my C++ project and compiling it into wasm using emscripten.
Everything works well except for the touch selection of tabs and docking separators.

I have identified the issue for the tabs selection and modified the code in imgui_widgets.cpp

```
// Click to Select a tab
ImGuiButtonFlags button_flags = ((is_tab_button ? ImGuiButtonFlags_PressedOnClickRelease : ImGuiButtonFlags_PressedOnClick) | ImGuiButtonFlags_AllowOverlap);
```

to be 

```
// Click to Select a tab
ImGuiButtonFlags button_flags = ImGuiButtonFlags_PressedOnClick;
```

https://github.com/ocornut/imgui/assets/63042547/aa150eec-de62-46e1-95d2-b498e4678fd5

I cannot find where I should modify the dockspace separators to also require only 1 touch click.

I think the issue is coming from the fact that on a regular mouse interface, you assume that the mouse is already hovered over the separator or the tab, so it is already initially highlighted, or"selected", and the click "doubly selects it". 
On the touch interface you cannot know where the user is hovering over the window, so you need to make these buttons and separators react immediately to any hover or click event.

Can you help me find the correct resolution to this issue? It's bugging me quite a bit. Do I need to modify the widgets, or can I set this somewhere in my app's imgui button flags settings?

**Comment by ocornut** [comment]
Your backend needs to call io.AddMouseSourceEvent() to specify that the mouse inputs comes from a touch screen to fix this. What does the SDL backends submits? (You may print it or browse it inside ImGui’s Debug Log window).

**Comment by ocornut** [comment]
The SDL backend does this:

ˋ``
io.AddMouseSourceEvent(event->button.which == SDL_TOUCH_MOUSEID ? ImGuiMouseSource_TouchScreen : ImGuiMouseSource_Mouse);
``ˋ
It is possible that SDL incorrectly sets it on Emscripten, in which case we should report this to Emscripten.

I however imagine in the meanwhile we could come up with a heuristic workaround on Emscripten: when mouse down events and repeatedly submitted right after a mouse pos event, we could decide by some heuristic that the source is likely a touch.

**Comment by jrynkiew** [comment]
> I however imagine in the meanwhile we could come up with a heuristic workaround on Emscripten: when mouse down events and repeatedly submitted right after a mouse pos event, we could decide by some heuristic that the source is likely a touch.

Very interesting. I will look into the io.AddMouseSourceEvent() and your workaround another day, but thank you very much for your helpful insight!

**Comment by jrynkiew** [comment]
@ocornut 
![image](https://github.com/ocornut/imgui/assets/63042547/2b1f520d-025e-4a7a-ab67-64cdef0cdbc0)
The input source appears to be correctly identified as TouchScreen

**Comment by jrynkiew** [comment]
@ocornut 
I just changed this section in imgui_widgets.cpp

```
// FIXME: AFAIK the only leftover reason for passing ImGuiButtonFlags_AllowOverlap here is
// to allow caller of SplitterBehavior() to call SetItemAllowOverlap() after the item.
// Nowadays we would instead want to use SetNextItemAllowOverlap() before the item.
ImGuiButtonFlags button_flags = ImGuiButtonFlags_FlattenChildren;
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    button_flags |= ImGuiButtonFlags_AllowOverlap;
#endif
```

to 
```
ImGuiButtonFlags button_flags = ImGuiButtonFlags_FlattenChildren;
#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS
    button_flags |= ImGuiButtonFlags_PressedOnClick;
#endif
```

and it works as intended :) Thanks for your help!

**Comment by ocornut** [comment]
This is not the correct fix. AllowOverlap is required for other things. We need to figure out why the input trickling is not behaving as expected.

**Comment by ocornut** [comment]
Can you verify that `io.ConfigInputTrickleEventQueue` is not disabled ?
Can you enable `Debug Log -> [X] IO` and log what is happened when performing a touch with the issue?

**Comment by jrynkiew** [comment]
@ocornut 
![image](https://github.com/ocornut/imgui/assets/63042547/219da57c-0278-4158-a234-39ec64299b7f)
Sorry I didn't follow up, there were other issues that were bugging me that I switched my focus to - like when touching the canvas, on an area outside of ImGui::GetIO().WantCaptureMouse - > I need to touch twice. Because the first touch will set ImGui::GetIO().WantCaptureMouse as false, but it's still true at the beginning of the mousedown event.

I pretty much left this issue alone after I fixed it with the workaround.

**Comment by ocornut** [comment]
> This is the log when touching and dragging the docking separator with the workaround "fix"

I would like to see the log without the workaround.

> - like when touching the canvas, on an area outside of ImGui::GetIO().WantCaptureMouse - > I need to touch twice. Because the first touch will set ImGui::GetIO().WantCaptureMouse as false, but it's still true at the beginning of the mousedown event.

Right this is a known issue we should find a out-of-stock solution for..
One workaround is to call `UpdateHoveredWindowAndCaptureFlags()` on a teleport.

> Edit: io.ConfigInputTrickleEventQueue is enabled by default, I didn't modify it. It's enabled

Thanks for confirming.

**Comment by jrynkiew** [comment]
I have no idea what you did in the recent updates, but coming back to this issue a few months later, the demo code from the imgui docking branch now works correctly and has the single click tab and separator functionality, whereas my own code now functions incorrectly. Is there a flag I must set now?

**Comment by ocornut** [comment]
I haven't changed anything about this so I'm surprised by its resolution. We'll see if it comes back.
