### ISSUE TITLE
UpdateInputEvents assert

### ISSUE THREAD

**Issue by plakapenka** [ocornut/imgui#7054]
Imgui ver: imgui, v1.89.7
Vendor: android, custom opengl

I rarely but accurately get an application crash with assert:
```
imgui/imgui.cpp:8895: void ImGui::UpdateInputEvents(bool): assertion "button >= 0 && button < ImGuiMouseButton_COUNT" failed
android_sigaction signal 6 (-1 0 6)
```

my click registration code:

```
bool CGUI::OnTouchEvent(int &type, int &num, int &x, int &y)
{
	if(!CKeyBoard::OnTouchEvent(type, num, x, y)) return false;

	ImGuiIO& io = ImGui::GetIO();
	
	io.AddMousePosEvent((float)x, (float)y);

	switch(type)
	{
		case TOUCH_PUSH:
		{
			io.AddMouseButtonEvent(ImGuiMouseButton_Left, true);
			return true;
		}

		case TOUCH_POP:
		{
			io.AddMouseButtonEvent(ImGuiMouseButton_Left, false);
			return true;
		}
		default:
		{
			return true;
		}
	}
}
```

I also use in initialization:
`io.AddMouseSourceEvent(ImGuiMouseSource_TouchScreen);`

**Comment by ocornut** [comment]
Hello,
There's probably something else you omitted that is interfering. We would need a standalone repro.

**Comment by ocornut** [comment]
I'm closing this for lack of correct details. Feel free to post details if you have them and we can reopen.
