### ISSUE TITLE
Imgui is not responsive

### ISSUE THREAD

**Issue by Nastihan** [ocornut/imgui#7055]
My engine works with win32 and dx12 and I am using imgui version : v1.89.8
I have set up imgui correctly but U can not interact with imgui. It draws the demowindow but I can not use mouse buttons with it. If I hover the cursor it changes the color of the window buttons but I can not click on them.
I don't believe that I am doing something wrong!;( 
here is my msgproc handling :
LRESULT Window::MainWndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
	if (msg == WM_NCCREATE)
	{
		const CREATESTRUCTW* const pCreate = reinterpret_cast<CREATESTRUCTW*>(lParam);
		Window* const pWnd = static_cast<Window*>(pCreate->lpCreateParams);
		return pWnd->MsgProc(hwnd, msg, wParam, lParam);
	}
	return ::DefWindowProc(hwnd, msg, wParam, lParam);
}

LRESULT Window::MsgProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{

	if (ImGui_ImplWin32_WndProcHandler(hwnd, msg, wParam, lParam))
		return true;

	switch (msg)
	{

		case WM_SIZE:
		{
			if (Core::Application::Instance().RendererInitialized())
			{
				width = LOWORD(lParam);
				height = HIWORD(lParam);
				Dante::Core::Application::Instance().OnResize();
			}
			else
			{
				return ::DefWindowProc(hwnd, msg, wParam, lParam);
			}
			return 0;

		}

		case WM_DESTROY:
		{
			::PostQuitMessage(0);
			return 0;
		}

		default:
		{
			return ::DefWindowProc(hwnd, msg, wParam, lParam);
		}
	}
}

std::optional<int> Window::ProcessMessages() noexcept
{
	MSG msg;
	while (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE))
	{
		if (msg.message == WM_QUIT)
		{
			return (int)msg.wParam;
		}

		TranslateMessage(&msg);
		DispatchMessage(&msg);
	}
	return {};
}

**Comment by ocornut** [comment]
> I have set up imgui correctly but U can not interact with imgui.

Don’t write things like this : it only allows you to not see the problem. Debugging an issue is being open to the possibility that anything you think is correct may not be. Obviously if you cannot interact it means you haven’t set things up correctly. 

You code doesn’t call your WndProc message handler UNLESS the message is WM_NCCREATE. All other messages are not passed to dear imgui. I am not surprised that it doesn’t work.
You are adding extra indirection that are breaking things. If you follow what the example app does you wouldn’t have this issue.

**Comment by GamingMinds-DanielC** [comment]
As Omar said, you basically don't forward anything. No key presses or releases, no mouse button events, no wheel events, nothing except `WM_NCCREATE`. The only reason why hilighting under the mouse cursor works is that the backend polls the mouse position itself instead of retrieving it from `WM_MOUSEMOVE` events.

This might sound a bit harsh, but: why would you just assume that your code works? Even the best and most experienced programmers wouldn't dare that. Placing a single breakpoint in your `Window::MsgProc` would have already told you that something must be wrong on your end.
