### ISSUE TITLE
 Issue with Assertion failed in imgui_impl_glfw.cpp

### ISSUE THREAD

**Issue by Oskar-Pietrzko** [ocornut/imgui#7057]
Hello ImGui Team,

I hope this message finds you well. I'm currently experiencing an issue with ImGui in my project, specifically related to the Assertion failed error in imgui_impl_glfw.cpp.

### Error:
```plaintext
Assertion failed: io.BackendPlatformUserData == nullptr && "Already initialized a platform backend!", file C:\**\imgui_impl_glfw.cpp, line 568
```
----
### Code Fragment:
```c++
// Setup Dear ImGui context
IMGUI_CHECKVERSION();
ImGui::CreateContext();

ImGuiIO& io = ImGui::GetIO(); (void)io;
io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;

ImGuiStyle& style = ImGui::GetStyle();

if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
    style.WindowRounding = 0.0f;
    style.Colors[ImGuiCol_WindowBg].w = 1.0f;
}

Application& application = Application::Get();
GLFWwindow* window = static_cast<GLFWwindow*>(application.GetWindow().GetNativeWindow());

// Setup Platform/Renderer bindings
ImGui_ImplGlfw_InitForOpenGL(window, true);
ImGui_ImplOpenGL3_Init();
```
----
I want to highlight that I'm not reinitializing ImGui multiple times, and the error seems to be related to the initialization of the platform backend.

Any guidance or suggestions on how to resolve this issue would be greatly appreciated. If there are specific areas or aspects of my code that you think I should investigate further, please let me know.

Thank you for your time and assistance.

Best regards,

Oskar Pietrzko

**Comment by sonoro1234** [comment]
On a first look, this assert is not on line 568 on last master!!!

**Comment by Oskar-Pietrzko** [comment]
I don't use the master branch, I use the docking branch.

**Comment by Oskar-Pietrzko** [comment]
OK I fixed problem.

**Comment by ocornut** [comment]
What was your issue?

**Comment by freezin-fire** [comment]
> OK I fixed problem.

what was the fix?
