### ISSUE TITLE
Wrapped text becomes a single line when the expected item rectangle is not in the viewport

### ISSUE THREAD

**Issue by RyokoAkizuki** [ocornut/imgui#706]
![wordwrap](https://cloud.githubusercontent.com/assets/968003/16171162/ef85ab9a-359a-11e6-8db0-ddaf6e10cc75.gif)

I'm making a resource manager displaying item groups consist of a thumbnail and a name respectively, and I'm wrapping the name text like the Windows Explorer does because I don't want it to expand the width of the group. However this strange behavior happens when I moves the manager window around, and disturbs the layout.

I've found that if TextWrapPos == -1.f is used to determine whether wrapping is enabled, but I can't see any difference changing it, so I suspect there might be some other positional / clipping calculations involed.

I hope this could be fixed or an corrected code replacing the old in the demo. Thank you.

**Comment by ocornut** [comment]
Good catch!

**Comment by ocornut** [comment]
Fixed!
