### ISSUE TITLE
ImGui_ImplAndroid_HandleInputEvent should take const AInputEvent*

### ISSUE THREAD

**Issue by wicstas** [ocornut/imgui#7060]
(Click "Preview" above ^ to turn URL into clickable links)

_(you may also go to Demo>About Window, and click "Config/Build Information" to obtain a bunch of detailed information that you can paste here)_

**Version/Branch of Dear ImGui:**

Branch: _master_

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_android.cpp + imgui_impl_opengl3.cpp

**My Issue/Question:**

As the title says. I found this because I'm not using NativeActivity, so I need to send motion event from Kotlin to c++. This requires me to use `const AInputEvent* AMotionEvent_fromJava(JNIEnv* env, jobject motionEvent)`, so it returns `const AInputEvent*`. Since all code inside `ImGui_ImplAndroid_HandleInputEvent` only uses `const AInputEvent*`, the function should use `const AInputEvent*` too.

**Comment by ocornut** [comment]
Thank you! I amended the code with 86891b0.
