### ISSUE TITLE
Child window (auto-fit) scrollbar appearing when it should not

### ISSUE THREAD

**Issue by Devyre** [ocornut/imgui#7063]
Hello,

I have been using ImGui (docking) for an editor of my game engine and updated to 1.90 for the content auto-fit of child windows.

It seems to work great but I noticed an issue where a scrollbar appeared in both child window and main window, when the child is supposed to grow within the main window.

I made sure to pass ImGuiChildFlags_AutoResizeY.
I actually stepped through it all and narrowed down the reason why the scrollbar appeared.

While debugging I noticed that **window->Size/SizeFull** were always 2 pixels lower than the content size.
It seems that child windows use the **CalcWindowAutoFitSize** function, which makes use of **style.DisplaySafeAreaPadding**.
I assume this style variable is only meant to be applied when it is a real window and not a child window.

Once I set **style.DisplaySafeAreaPadding** to 0 the scrollbar of the child disappeared.

The specific line of code causing this problem:
https://github.com/ocornut/imgui/blob/bce4db00bcccef072cd5a596b2f123395561e869/imgui.cpp#L5792

**Comment by ocornut** [comment]
Thank you, I confirmed this and pushed a fix f37f6f6

Repro was:
```cpp
ImGui::Begin("Bug #7063");
ImGui::BeginChild("blah", ImVec2(0, 0), ImGuiChildFlags_AutoResizeY);
for (int n = 0; n < 1000; n++)
    ImGui::Text("...");
ImGui::EndChild();
ImGui::End();
```
