### ISSUE TITLE
imgui performance?

### ISSUE THREAD

**Issue by dddd545r** [ocornut/imgui#7065]
I have a question: Does anyone know or can someone provide me with a straightforward answer regarding rendering ImGui widgets?
I haven't found a specific answer to this yet. For instance, if I attempt to render 150 DragFloat widgets in a loop (less than 150 iterations), I experience significant performance drops (measured in milliseconds per frame (high resolution clock)).

Do any of you have a solution to this issue? The loop with 150 iterations seems quite extensive. Once it reaches the beginning of the main ImGui loop, the milliseconds per frame aren't the same as when I have a loop with less than 10 iterations.

Is there a way to render 150 widgets on the screen while maintaining a maximum of 1 millisecond per frame, similar to how a smaller loop (<10 iterations) performs?

**Comment by sakiodre** [comment]
This sounds like premature optimization to me. Why do you need <1ms per frame (i.e. >1000fps) anyway? I believe the CPU is the bottleneck here, so if you really want that kind of performance, you should just make your widgets.

**Comment by ocornut** [comment]
1 ms is a meaningful amount of time in game engine terms, but I also certain that submitting 150 widgets wouldn’t cost that much with dear imgui, so i think something is wrong with your measurements.

**Comment by sakiodre** [comment]
> I also certain that submitting 150 widgets wouldn’t cost that much with dear imgui

I just perf-tested and it took an average of 7 microseconds (0.007 ms) on my 12900k with /O2, it shouldn't take anywhere near 1 ms even on older hardware. OP didn't specify which backend and hardware they used but I doubt that it takes that much time for the GPU to render less than 1000 vertices.

**Comment by GamingMinds-DanielC** [comment]
Could be a Debug build (but even for that it seems rather slow), could be the loop itself. Without code to see, who knows if there are f.e. expensive allocations in each loop iteration?

**Comment by ocornut** [comment]
For reference, I disabled vsync/throlling in Win32+DX11 example and tested this:

```
ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / io.Framerate, io.Framerate);
static int count = 10;
ImGui::DragInt("Count", &count);
for (int n = 0; n < count; n++)
{
    static float f = 0.0f;
    ImGui::PushID(n);
    ImGui::DragFloat("float", &f);
    ImGui::PopID();
}
```
With VS2015 in Debug Mode, going from `count == 0` to `count == 150` increased the frame time by about 0.2 ms (with about 1/4 of them visible and 3/4 under scrolling line visible). With `count == 1500` i get a 1.2 ms increase.

Compiling dear imgui in optimized mode (with assert enabled). with `count == 150` or `count == 1500` I couldn't measure the difference. With `count == 15000` i got about a ~0.650 ms increase. However note that in situations where you have 1000+ items you are likely needing to use ImGuiListClipper anyway.

I think you have another issue in your code so I am closing this, but feel free to post details if you need further help.

**Comment by dddd545r** [comment]
With the first approach, I indeed achieve the same (similar) result, a maximum of 0.4 ms/frame. 
static int count = 150;
ImGui::DragInt("Count", &count);
for (int n = 0; n < count; n++)
{
    static float f = 0.0f;
    ImGui::PushID(n);
    ImGui::DragFloat("float", &f);
    ImGui::PopID();
}

However, with my second approach, I am getting different results, up to max 1.1 ms/frame. What could be the reason for this discrepancy? Shouldn't it be the same?

        static float drag_f = 0.5f;
        for (int n = 0; n < 150; n++)
        {
            ImGui::DragFloat(("xx" + std::to_string(n)).c_str(), &drag_f);
        }
        
![image](https://github.com/ocornut/imgui/assets/118204708/b295b11a-83a0-4b36-818e-321c4ec72ac5)

**Comment by GamingMinds-DanielC** [comment]
String conversion and concatenation adds expensive allocations. Try formatting into a local buffer instead.

**Comment by ocornut** [comment]
In addition to the extra heap allocations, std:: functions are stupidly slow in debug mode.

Using:
```cpp
char buf[64];
sprintf(buf, "%d", n);
ImGui::DragFloat(buf, &f);
```
Which I would write as:
```cpp
ImGui::DragFloat(Str64f("%d, n).c_st(), &f);
```
Using https://github.com/ocornut/Str

I get higher times that without formatting, but much better that using `std::tostring(n)`.

in Release mode the 15000 items takes about +1.5 ms with sprintf formatting. 

stb_printf is apparently ~4 times faster than stock sprintf for this case:
https://github.com/nothings/stb/blob/master/stb_sprintf.h

**Comment by ocornut** [comment]
I compared all fours:
```cpp
                char buf[64];
                if (mode == 0)
                {
                    ImGui::DragFloat("xx", &f);
                }
                else if (mode == 1)
                {
                    sprintf(buf, "xx%d", n);
                    ImGui::DragFloat(buf, &f);
                }
                else if (mode == 2)
                {
                    stbsp_sprintf(buf, "xx%d", n);
                    ImGui::DragFloat(buf, &f);
                }
                else if (mode == 3)
                {
                    ImGui::DragFloat(("xx" + std::to_string(n)).c_str(), &f);
                }
```
```
DEBUG (VS 2015)

Mode 0 no formatting
   0 : 0.150
 150 : 0.350
1500 : 1.350
15000: 11.450

Mode 1 sprintf (vs15)
   0 : 0.150
 150 : 0.430
1500 : 2.200
15000: 19.600

Mode 2 stb_printf
   0 : 0.150
 150 : 0.370
1500 : 1.650
15000: 14.690

Mode 3 std::to_string + append
   0 : 0.150
 150 : 1.450
1500 : 12.600
15000: 123.500

RELEASE (VS 2015)

Mode 0 no formatting
   0 : 0.150
 150 : 0.150
1500 : 0.150
15000: 0.700

Mode 1 sprintf (vs15)
   0 : 0.150
 150 : 0.150
1500 : 0.223
15000: 1.850

Mode 2 stb_printf
   0 : 0.150
 150 : 0.150
1500 : 0.190
15000: 1.470

Mode 3 std::to_string + append
   0 : 0.150
 150 : 0.150
1500 : 0.190
15000: 1.470
```

to_string() is pretty efficient in optimized mode, but absolutely terrible in debug mode (as with everything in std).
One advantage of using sprintf is being a library you can control the compile setting off, you can use it in always-optimized mode even when the rest of your projects needs debugging.

**Comment by dddd545r** [comment]
Thank you
