### ISSUE TITLE
Dockspace Image

### ISSUE THREAD

**Issue by krulci** [ocornut/imgui#7067]
Version/Branch of Dear ImGui:

Version: 1.89.4.0
Branch: sneusse/ImGui.NET

Back-end/Renderer/Compiler/OS

Back-ends: imgui_impl_XXX.cpp + imgui_impl_XXX.cpp (or specify if using a custom engine/back-end)
Compiler: dotnet
Operating System: Windows 11

**My Issue/Question:**

Would like to know how to set a background image to dockspace?

**Comment by ocornut** [comment]
What for?

If you are using `ImGuiDockNodeFlags_PassthruCentralNode` you can simply do this:

```cpp
ImGuiID dockspace_id = ImGui::GetID("MyDockSpace");
ImDrawList* draw_list = ImGui::GetWindowDrawList();
ImVec2 p = ImGui::GetCursorScreenPos();
draw_list->AddRectFilled(p, ImVec2(p.x + 100, p.y + 100), IM_COL32(255, 0, 0, 255));
ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), dockspace_flags);
```

Where you would replace AddRectFilled() by a AddImage() call.

Generally speaking, and even if you are not using `ImGuiDockNodeFlags_PassthruCentralNode`, you can use:

```cpp
ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), dockspace_flags);
if (ImGuiDockNode* node = ImGui::DockBuilderGetNode(dockspace_id))
    if (node->HostWindow != NULL && node->LastFrameActive == ImGui::GetFrameCount())
    {
        ImDrawList* draw_list = node->HostWindow->DrawList;
        int backup_channel = draw_list->_Splitter._Current;
        draw_list->_Splitter.SetCurrentChannel(draw_list, 0);
        draw_list->AddRectFilled(node->Pos, ImVec2(node->Pos.x + node->Size.x, node->Pos.y + node->Size.y), IM_COL32(255, 0, 0, 255));
        draw_list->_Splitter.SetCurrentChannel(draw_list, backup_channel);
    }
```

Please note this is technically undocumented/unguaranteed but I will make an effort to post here if something related ever changes.

**Comment by krulci** [comment]
> What for?
> 
> 
> 
> If you are using `ImGuiDockNodeFlags_PassthruCentralNode` you can simply do this:
> 
> 
> 
> ```cpp
> 
> ImGuiID dockspace_id = ImGui::GetID("MyDockSpace");
> 
> ImDrawList* draw_list = ImGui::GetWindowDrawList();
> 
> ImVec2 p = ImGui::GetCursorScreenPos();
> 
> draw_list->AddRectFilled(p, ImVec2(p.x + 100, p.y + 100), IM_COL32(255, 0, 0, 255));
> 
> ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), dockspace_flags);
> 
> ```
> 
> 
> 
> Where you would replace AddRectFilled() by a AddImage() call.
> 
> 
> 
> Generally speaking, and even if you are not using `ImGuiDockNodeFlags_PassthruCentralNode`, you can use:
> 
> 
> 
> ```cpp
> 
> #include "imgui_internal.h"
> 
> ..
> 
> ImGui::DockSpace(dockspace_id, ImVec2(0.0f, 0.0f), dockspace_flags);
> 
> if (ImGuiDockNode* node = ImGui::DockBuilderGetNode(dockspace_id))
> 
>     if (node->HostWindow != NULL && node->LastFrameActive == ImGui::GetFrameCount())
> 
>     {
> 
>         ImDrawList* draw_list = node->HostWindow->DrawList;
> 
>         int backup_channel = draw_list->_Splitter._Current;
> 
>         draw_list->_Splitter.SetCurrentChannel(draw_list, 0);
> 
>         draw_list->AddRectFilled(node->Pos, ImVec2(node->Pos.x + node->Size.x, node->Pos.y + node->Size.y), IM_COL32(255, 0, 0, 255));
> 
>         draw_list->_Splitter.SetCurrentChannel(draw_list, backup_channel);
> 
>     }
> 
> ```
> 
> 
> 
> Please note this is technically undocumented/unguaranteed but I will make an effort to post here if something related ever changes.

Thanks

GetWindowDrawList works
