### ISSUE TITLE
ImGui::BeginViewportSideBar() how has margins

### ISSUE THREAD

**Issue by huiseliming** [ocornut/imgui#7073]
Version/Branch of Dear ImGui:

Version: 1.89.8
Branch: docking

Back-end/Renderer/Compiler/OS
Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Compiler: MSVC
Operating System: Windows

My Issue/Question:
ImGui::BeginViewportSideBar() Internal item widget have no margin , only padding.
![1701220775466](https://github.com/ocornut/imgui/assets/16591229/c98e52c6-e623-4355-ae8a-6dba93678f63)

**Comment by huiseliming** [comment]
Adding ImGuiStyleVar_WindowPadding only has no effect in vertical direction, only in horizontal direction

**Comment by ocornut** [comment]
I don't understand your question or issue, I don't understand what to look at in your screenshot, I don't understand your subject line ("how has margins"?).
Please be more specific, provide repro code and more explanation.

We currently apply WindowPadding*0.5f on both left and right side on the default ClipRect (see #3312) we may remove that at some point.

**Comment by huiseliming** [comment]
![1701266174683](https://github.com/ocornut/imgui/assets/16591229/c6407a79-9390-4892-931c-194fc457ce65)
I didn't find properties or options available to implement the changes

**Comment by ocornut** [comment]
What problem are you trying to solve? Why pushing (256,256) WindowPadding ?

`BeginMenuBar()` uses `window->MenuBarOffset` which is initialized in `Begin()` as:

```cpp
window->DC.MenuBarOffset.x = ImMax(ImMax(window->WindowPadding.x, style.ItemSpacing.x), g.NextWindowData.MenuBarOffsetMinVal.x);
window->DC.MenuBarOffset.y = g.NextWindowData.MenuBarOffsetMinVal.y;
```
