### ISSUE TITLE
ReadOnly ItemFlag is partially working with ColorEdit

### ISSUE THREAD

**Issue by sneakyevil** [ocornut/imgui#7079]
**As the title says.**

Code example:
```cpp
ImGui::PushItemFlag(ImGuiItemFlags_ReadOnly, true);

ImGui::ColorEdit4("Color", g_Colour); // Still can be edited in some places.

ImGui::PopItemFlag();
```
I wanted to use ColorEdit as color preview for one of my tool and prevent user to edit it, but doing pushing item flag readonly for coloredit will prevent only the dragfloat inputs, but they still can be edited by double clicking on it and changing the values. 
This same behaviour exist when clicking the colorbutton that popups the modal for color editing. This isn't really much issue for me, but couldn't find anyone mention it and might someone use it in future and would be good to have it working.

Here is preview of the issue:

https://github.com/ocornut/imgui/assets/29150970/dd3d7ca7-97de-421f-a548-ca6e0a9a3bec

**Comment by ocornut** [comment]
ReadOnly is curfently very partially supported by a few widgets. Note there is a public Disabled flag, used via BeginDisabled()/EndDisabled() which might solve your needs?

**Comment by ocornut** [comment]
I pushed 5768de7 adding better support for ImGuiItemFlags_ReadOnly in `InputText()` and `ColorEdit4()`, `ColorPicker4()`.
