### ISSUE TITLE
Filtering possible sliders values / Handle location

### ISSUE THREAD

**Issue by Nahor** [ocornut/imgui#7082]
**My Issue/Question:**

In my application, I need to restrict the values of a slider to be a divisor of another number.
Currently, when dragging the handle, it shows where the mouse cursor is (or snaps to the nearest rounded value matching the format). Then when I release the mouse, the handle snaps to the nearest divisor. My issue is I'd like for the handle to snap to the divisor even while dragging.

The root of the issue is that the handle is drawn after computing the new value (call to `SliderBehavior`) but before the execution returns to the application. If `SliderBehavior` was called after all the rendering, I believe it would fix the issue, at the cost of a 1 frame delay between value selection and rendering update.

**Standalone, minimal, complete and verifiable example:**
When dragging, the slider snaps to whole integers (0.0, 1.0, 2.0, 3.0) because of the format string, but not to multiple of 3 (0.0, 3.0, 6.0) to match the actual value set by the application. It only snaps to the multiple of 3 after the mouse button is released.
```C++
static float foobar = 0.0f;
if (ImGui::SliderFloat("Foobar", &foobar, 0.0f, 15.0f, "%.0f")) {
    foobar = std::round(foobar / 3.0f) * 3.0f;
}
ImGui::Text("%f", foobar);
```

**Comment by ocornut** [comment]
Hello,

A workaround would be pass the pre-formatted value in the format field. This would effectively do the same thing as if we were to swap behavior handling and rendering, except in an opt-in manner, as you are locking display for the frame.

I believe this align with #1815 but for both I don't have a good solution at the moment other that aforementioned workaround.

**Comment by ocornut** [comment]
You are right about handle location and keyboard controls too.
I suppose this would be a good justification for a callback/hook even if it was undocumented/internal.
