### ISSUE TITLE
Exception thrown in ImGui::Shutdown

### ISSUE THREAD

**Issue by pvpswaghd** [ocornut/imgui#7091]
**Version/Branch of Dear ImGui:**

Version: 1.90.1

**Back-end/Renderer/Compiler/OS**

Back-ends: ImGUI-SFML, ImPlot, ImGui
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: Windows 11

**My Issue/Question:**

I have been developing a project using the three backends mentioned above. However, everytime I close the window, it always pop up to `Exception thrown: read access violation. g.IO.Fonts was 0xFFFFFFFFFFFFFFE7`. I believe the issue only occurs when I call `ImGui::CreateContext()`, because when I try to run the sample code [here](https://github.com/SFML/imgui-sfml), it does not encounter any errors. The exception is as below.

P.S. Not sure if this is an ImGui problem or something else, I am pretty new to this library. I have tried to remove `ImGui::SFML::Shutdown` to see if this is an issue specific to `imgui-sfml`, but it still shows the same exception.
**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/44018990/00aed41f-4769-4847-b9f1-6494cccf5d55)
![image](https://github.com/ocornut/imgui/assets/44018990/a87a9b7c-1996-45e8-855d-9429df5ce336)

```
// Here's some code anyone can copy and paste to reproduce your issue
int main() {
    sf::ContextSettings contextSettings;

    sf::RenderWindow window(sf::VideoMode(1290, 720), "Bubble Sort", sf::Style::Default, contextSettings);
    ImGui::SFML::Init(window);
    ImGui::CreateContext();
    ImPlot::CreateContext();

    sf::Clock deltaClock;

    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            ImGui::SFML::ProcessEvent(window, event);
            if (event.type == sf::Event::Closed) {
                window.close();     
            }
        }
        ImGui::SFML::Update(window, deltaClock.restart());
        window.clear();
        draw(window); // just a function that draws stuff on the GUI
        ImGui::SFML::Render(window);
        window.display();
    }
    
    ImPlot::DestroyContext();
    std::cout << "ImPlot Destroyed" << std::endl;
    ImGui::DestroyContext();
    std::cout << "ImGui Destroyed" << std::endl;
    ImGui::SFML::Shutdown();
    std::cout << "SFML Destroyed" << std::endl;
    return 0;
}
```

**Comment by lukaasm** [comment]
you are trying to access ImGuiContext, after calling: `ImGui::DestroyContext();` move it after ImGui::SFML::Shutdown()

**Comment by ocornut** [comment]
Yes I guess you should follow what imgui-sfml example is doing:
https://github.com/SFML/imgui-sfml/blob/2.6.x/examples/minimal/main.cpp

Unfortunatelyy imgui-SFML is not following the practices of our other backends so always follow their examples.

SFML::ShutDown() is calling ImGui::DestroyContext() already. It's obfuscated by stupid C++ habits but if you search for DestroyContext you'll find it:
https://github.com/SFML/imgui-sfml/blob/2.6.x/imgui-SFML.cpp
