### ISSUE TITLE
Adds 12s to build of hello world-ish program (not even yet #included), is this normal? Or newbie mistake?

### ISSUE THREAD

**Issue by metaleap** [ocornut/imgui#7092]
Not addressed in the FAQs AFAICT.

I'm a bit new to C++ (decades of coding behind me though, mostly Go, C#, some C) and I guess there's no incremental-compilation except for actual lib "installs".

I'm wondering why just including imgui's `*.{cpp|h}` files in my `g++` compile-and-link build step bumps the build time of a basically-hello-worldish program (based on and not much more complex than [this](https://www.sfml-dev.org/tutorials/2.6/start-linux.php#compiling-a-sfml-program)) turns the build time from ~0.9s up to ~12.5s!

Wondering if I ~~include~~ compile it wrong?

Without imgui:

```
$ g++ mo2d/main.cpp --debug -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -o /home/_/.local/bin/mo2d_dbg

real	0m0.983s
user	0m0.875s
sys	0m0.108s
```

With imgui:

```
$ g++ libdeps/imgui/*.cpp libdeps/imgui/*.h mo2d/main.cpp --debug -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -o /home/_/.local/bin/mo2d_dbg
libdeps/imgui/imconfig.h:15:9: warning: #pragma once in main file
   15 | #pragma once
      |         ^~~~
libdeps/imgui/imgui.h:50:9: warning: #pragma once in main file
   50 | #pragma once
      |         ^~~~
libdeps/imgui/imgui_internal.h:40:9: warning: #pragma once in main file
   40 | #pragma once
      |         ^~~~

real	0m12.493s
user	0m11.474s
sys	0m0.985s
```

Well? Is this par-for-the-course in C++ land in general, or might I have missed certain gcc options tweaks that I should learn about?  =)

(Linux 64bit, 64GB RAM, somewhat-dated "Intel Xeon E-2186M (12 cores) @ 2.900GHz" reported by `neofetch`)

**Comment by emoon** [comment]
Build the imgui code to a lib once and then link with that library. Otherwise you will recompile the imgui code all the time (and you likely won't change that code)

**Comment by metaleap** [comment]
Merci @emoon , will give it a go!

**Comment by emoon** [comment]
Also the way you usually do it in c/cpp land is to have a build system (such as cmake,make,etc) that rebuilds files when it detects something has changed and then use the already built files (that hasn't changed) and link with those.

**Comment by cfillion** [comment]
> $ g++ libdeps/imgui/*.cpp libdeps/imgui/*.h mo2d/main.cpp ... -o executable

This rebuilds all source files each time. (Also the header files should not be listed there, only the source files.)

To avoid this each source file can be individually compiled into an object file after they (or one of the included header) have been modified. Then the object files can be linked together to produce the final executable.

The command line above is actually a shortcut to performing all those steps (compilation + linking) with a single command.

```sh
$ gcc -c file1.cpp
$ gcc -c file2.cpp
$ gcc -c file3.cpp
$ gcc file1.o file2.o file3.o -o executable
```

...which gets unmanageable very quickly.

Build systems such as Make, Meson, CMake, and many others exist to do take care of that work. They detect which object files are stale and need rebuilding then run the needed compiler commands automatically.

**Comment by metaleap** [comment]
From the recommendations comes a further newbie curiosity, in case anyone's still listening in here (and sorry for the non-urgent ping/distraction if so =)

- Assuming having a build system which keeps around the latest `.o`s of compile units somewhere
- Assuming we're talking about one's own lib-ish code that is _not_ of the "won't update more often than 1x a month/quarter" category
- Assuming a project structure of `program1`, `program2`, `shared_by_both` top folders

Would one with more experience than me usually expect (on average) any build-duration benefit to the latter being an `.so` linked into the former 2 programs, vs. simple including-the-headers-and-linking-the-`.o`s? Like I said, all 3 would be developed alongside, aka. not a 3rd-party dep that's concerned here in this question/consideration...

I know it's not a C++ forum here but if you care to share your instinct on this, merci; if not, no prob, time will tell me too  =)
