### ISSUE TITLE
Make widgets fill the remaining window space

### ISSUE THREAD

**Issue by leiradel** [ocornut/imgui#710]
This is not really an issue but I don't know where else to ask...

I have an window with some widgets, and I want two of them to occupy the remaining window space as the user resizes the window. I've managed to do it, the widgets that resize along with the window are the PlotLines:

![lrcmdr](https://cloud.githubusercontent.com/assets/357536/16286145/ea21fd70-38b0-11e6-96e9-bc3257efc35b.png)

But when I make the window too small, strange things happen:

![lrcmdr2](https://cloud.githubusercontent.com/assets/357536/16286154/fb9077da-38b0-11e6-88d6-053cbd8fab95.png)

The code that draws the window is (`ImGui::Begin` and `End` are issued by the caller):

```C++
Instance* self = (Instance*)instance;

ImGui::Checkbox( "Mute", &self->mute );
ImGui::SameLine();
ImGui::Checkbox( "Active", &self->active );

if ( ImGui::CollapsingHeader( "Visualizer" ) )
{
  struct Getter
  {
    static float Left( void* data, int idx )
    {
      Instance* self = (Instance*)data;
      return self->samples[ idx * 2 ] * self->scale;
    }

    static float Right( void* data, int idx )
    {
      Instance* self = (Instance*)data;
      return self->samples[ idx * 2 + 1 ] * self->scale;
    }
    
    static float Zero( void* data, int idx )
    {
      return 0.0f;
    }
  };
  
  ImVec2 min = ImGui::GetWindowContentRegionMin();
  ImVec2 max = ImGui::GetWindowContentRegionMax();
  
  max.x = ( max.x - min.x ) / 2;
  max.y -= min.y + ImGui::GetItemsLineHeightWithSpacing() * 3;
  
  if ( CoreInfo->get_core_state() == LRCMDR_RUNNING && self->samples != NULL )
  {
    ImGui::PlotLines( "", Getter::Left, self, self->frames, 0, NULL, -32768.0f, 32767.0f, max );
    ImGui::SameLine( 0.0f, 0.0f );
    ImGui::PlotLines( "", Getter::Right, self, self->frames, 0, NULL, -32768.0f, 32767.0f, max );
  }
  else
  {
    ImGui::PlotLines( "", Getter::Zero, NULL, 2, 0, NULL, -32768.0f, 32767.0f, max );
    ImGui::SameLine( 0.0f, 0.0f );
    ImGui::PlotLines( "", Getter::Zero, NULL, 2, 0, NULL, -32768.0f, 32767.0f, max );
  }
  
  ImGui::PushItemWidth( -1.0f );
  ImGui::SliderFloat( "##empty", &self->scale, 1.0f, 3.0f, "Scale = %.3f");
  ImGui::PopItemWidth();
}
```

Is there some other way to do it?

**Comment by leiradel** [comment]
Hm, I've solved this by only plotting the lines if `max.y` is greater than zero. Sorry for the noise.

**Comment by ocornut** [comment]
Yeah you need to handle that sort of layout yourself, negative sizes usually has a "fill" meaning but somehow it is not supported in Plot() which is an overlook. Normally we want to support it so you can just pass `ImVec2(half_width, -ImGui::GetItemsLineHeightWithSpacing() * 3)` do to the same thing without calling the ContentRegion etc. In this case you would still need it for the half_width.

Note that you can call `ImGui::GetContentRegionAvail()` instead of `Max-Min`, it is roughly equivalent to `== GetContentRegionMax() - GetCursorPos()`.

(And in the remote future we might create helpers to run a two-pass layout).

**Comment by leiradel** [comment]
If I just use `ImGui::GetContentRegionAvail()`, the slider float at the bottom of the window is always clipped out of the window. If I do `max.y -= ImGui::GetItemsLineHeightWithSpacing()` it works just like my version, so yes, I'll switch to `ImGui::GetContentRegionAvail()`, but I still have to check if `max.y` is greater than zero.
