### ISSUE TITLE
missing release of `FontCommandBuffer` in `ImGui_ImplVulkan_DestroyDeviceObjects` leads to a crash in `ImGui_ImplVulkan_CreateFontsTexture`

### ISSUE THREAD

**Issue by micb25** [ocornut/imgui#7104]
**Version/Branch of Dear ImGui:**

Version: 1.90.0
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_vulkan.cpp
Compiler: GCC
Operating System: Linux

**My Issue/Question:**

The allocated `FontCommandBuffer` is not being freed and reset in `ImGui_ImplVulkan_DestroyDeviceObjects`. When the font atlas is being recreated on the fly, it leads to a situation in `ImGui_ImplVulkan_CreateFontsTexture` where a new `FontCommandPool` is recreated, but the old `FontCommandBuffer` is still being used. This leads to an immediate crash on my system when `vkBeginCommandBuffer` is called with the old invalid `FontCommandBuffer`.

**Suggestion:**
Since `ImGui_ImplVulkan_DestroyDeviceObjects` controls the life time of `bd->FontCommandPool`, the `bd->FontCommandBuffer` should be freed before `bd->FontCommandPool` gets destroyed:

```
void    ImGui_ImplVulkan_DestroyDeviceObjects()
{
    // ...

    // the following line was added and fixes the issue
    if (bd->FontCommandBuffer)    { vkFreeCommandBuffers(v->Device, bd->FontCommandPool, 1, &bd->FontCommandBuffer); bd->FontCommandBuffer = VK_NULL_HANDLE; }
    if (bd->FontCommandPool)      { vkDestroyCommandPool(v->Device, bd->FontCommandPool, v->Allocator); bd->FontCommandPool = VK_NULL_HANDLE; }

    // ...
}
```

**Comment by ocornut** [comment]
Thanks for reporting this.
This didn't happen in my test bed because it shouldn't be required to call `ImGui_ImplVulkan_DestroyDeviceObjects()` more than once. Calling `ImGui_ImplVulkan_CreateFontsTexture()` is enough to reload font atlas.

In fact `ImGui_ImplVulkan_DestroyDeviceObjects()` is only called from `ImGui_ImplVulkan_Shutdown()` and not elsewhere so I am unsure how it is is possible to get in a situation where that is called and the backend keeps running.
Can you clarify ?

**Comment by micb25** [comment]
Thanks for your clarification. 

I was not aware that `ImGui_ImplVulkan_DestroyDeviceObjects()` should be called only once, because it is a public function and in the header file listed just below `// Called by user code`. 

Basically, my program does the following pseudo-code to recreate all Vulkan objects on-the-fly which then crashes the app in `ImGui_ImplVulkan_CreateFontsTexture()`:

```C++
    vkDeviceWaitIdle(device);
    ImGui_ImplVulkan_DestroyDeviceObjects();
    ImGui_ImplVulkan_CreateDeviceObjects();
    ImGui::GetIO().Fonts->Clear();
    // build glyph ranges ...
    ImGui::GetIO().Fonts->Build();
    ImGui_ImplVulkan_CreateFontsTexture();
```

Since `bd->FontCommandBuffer` is never freed and reset to `VK_NULL_HANDLE`, it leads to a situation where the command buffer is only created the first time `ImGui_ImplVulkan_CreateFontsTexture()` is called. The command pool, however, can be destroyed and recreated several times via calling `ImGui_ImplVulkan_DestroyDeviceObjects()` and `ImGui_ImplVulkan_CreateDeviceObjects()`. The call to `vkBeginCommandBuffer(bd->FontCommandBuffer, &begin_info)` then crashes the app, due to an combination of an invalid command buffer and a new command pool.

To solve this issue, I can imagine the following solutions:

1. In `ImGui_ImplVulkan_DestroyDeviceObjects()`: explicitly free `bd->FontCommandBuffer` and reset its value to `VK_NULL_HANDLE`  (_vide supra_)
2. Just reset `bd->FontCommandBuffer` to `VK_NULL_HANDLE` in `ImGui_ImplVulkan_DestroyDeviceObjects()`, since according to the Vulkan [spec](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkDestroyCommandPool.html) all command buffers of a command pool are freed anyway when the command pool gets destroyed.

**Comment by ocornut** [comment]
ImGui_ImplVulkan_DestroyDeviceObjects() isn’t a public function in 1.90 afaik.

**Comment by micb25** [comment]
Mea culpa! You're absolutely right. I have a few minor patches applied in the Vulkan backend code and made both functions public for some reason some time ago.

Anyway, I think it would be still beneficial to fix that issue in case the backend code changes in the future.

**Comment by ocornut** [comment]
I have pushed 8764a1b to address that use case and because I agree it is saner/consistent.
I believe you should however attempt to remove those mods or justify their existence (in which case we can contemplate making those functions public). Since 1.90 calling `ImGui_ImplVulkan_CreateFontsTexture()` should be enough to reload fonts.

**Comment by micb25** [comment]
Thanks a lot! I definitely will and sorry for all the confusion.
