### ISSUE TITLE
Bad Y value on CalcWindowMinSize()

### ISSUE THREAD

**Issue by n0bodysec** [ocornut/imgui#7106]
**Version/Branch of Dear ImGui:**

Version: 1.90
Branch: master

**Back-end/Renderer/Compiler/OS**

N/A

**My Issue/Question:**

The `CalcWindowMinSize()` function is parsing a bad `Y` value (actually getting the `X` value).
See: https://github.com/ocornut/imgui/blob/69f524ba959c694a304dd71765d84e1422ce1eb2/imgui.cpp#L5677C7-L5677C7

It should be:
```cpp
size_min.y = ((window->Flags & ImGuiWindowFlags_AlwaysAutoResize) == 0) ? g.Style.WindowMinSize.y : 4.0f;
```

**Screenshots/Video**

N/A

**Standalone, minimal, complete and verifiable example:**

N/A

**Comment by ocornut** [comment]
Thank you, I have pushed a fix for this now.

**Comment by n0bodysec** [comment]
You are welcome.
I also noticed that it is no longer possible to enter values manually (ctrl + click) in SliderFloat (I did not try the other sliders). Is this a feat or a bug?

**Comment by ocornut** [comment]
It works here and this roughly tested by test suite so I believe you have another issue on your site.

**Comment by n0bodysec** [comment]
Weird. It works on v1.89.9. I'm gonna check again!

Regards.

**Comment by n0bodysec** [comment]
I compiled an example project using the latest ImGui from master and it's working as expected. This is still weird since on my own project v1.89.9 works fine but I'm experimenting this issue on v1.90 and master.
