### ISSUE TITLE
The outline is cut at the end when rendering a texture

### ISSUE THREAD

**Issue by SC5Shout** [ocornut/imgui#7108]
I'm trying to create a custom widget that looks more/less like this:

![image](https://github.com/ocornut/imgui/assets/43299401/c01cd3b2-f642-448a-b8ee-8a7a2bbd160b)

The black rectangle is available space for this widget (it's not rendered). The red rectangle is the outline.

This widget will be used in a table. This is the code:

```cpp
void MyWidget(const char* label, ImTextureID drawableRight)
{
	using namespace ImGui;
	
	ImGuiWindow* window = GetCurrentWindow();
	if (window->SkipItems)
		return;

	ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2{ 0, 0 });

	ImGuiContext& g = *GImGui;
	const ImGuiStyle& style = g.Style;
	const ImGuiID id = window->GetID(label);
	const ImVec2 label_size = CalcTextSize(label, NULL, true);

	float height = label_size.y + style.FramePadding.y * 2.0f;
	const ImVec2 size = ImVec2(GetContentRegionAvail().x, label_size.y + style.FramePadding.y * 2.0f);

	ImGui::BeginHorizontal(label, size);

	{		
		const ImVec2 pos = window->DC.CursorPos;
		const ImRect bb(pos, pos + size);
		ItemSize(size, style.FramePadding.y);
		ItemAdd(bb, id);

		bool hovered, held;
		bool pressed = ButtonBehavior(bb, id, &hovered, &held);

		RenderNavHighlight(bb, id);
		RenderFrame(bb.Min, bb.Max, GetColorU32(ImGuiCol_Button), true, style.FrameRounding);

		RenderTextClipped(bb.Min + style.FramePadding, bb.Max - style.FramePadding, label, NULL, &label_size, ImVec2(0.0f, 0.0f), &bb);

		//outline full width
		{
			constexpr float borderThickness = 1.0f;
			const ImRect fullwithBb = ImRect(bb.Min - ImVec2(borderThickness, borderThickness), bb.Max + ImVec2(borderThickness, borderThickness));

			window->DrawList->AddRect(fullwithBb.Min, fullwithBb.Max, 0xff0000ff, 0.0f, 0, borderThickness);
		}
	}

	ImGui::Spring();

	Widget::ShiftCursorX(-height);
	ImGui::Image(drawableRight, { height, height});

	ImGui::EndHorizontal();

	ImGui::PopStyleVar();
}
```
result:
![image](https://github.com/ocornut/imgui/assets/43299401/41a49f10-ab19-4fb0-9e6c-77fcf5841241)

as you can see the red outline is cut at the end of the widget. So I've tried to draw a rect instead of the image to see if the outline will still be cut.

So instead of
```cpp
ImGui::Image(drawableRight, { height, height});
```
I did:

```cpp
{
    const ImVec2 pos = window->DC.CursorPos + ImVec2(1.0f, 1.0f);
    const ImVec2 size = { height - 2.0f, height - 2.0f };
    const ImRect bb(pos, pos + size);

    window->DrawList->AddRectFilled(bb.Min, bb.Max, 0xffff00ff, style.FrameRounding);
}
```
I've also changed the size a bit. The rest of the code is the same. Result:

![image](https://github.com/ocornut/imgui/assets/43299401/cb3e98bd-7582-4a35-99a7-027c6092d239)

And now there's the red outline finished correctly. So then I changed `AddRectFilled` to `window->DrawList->AddImage(drawableRight, bb.Min, bb.Max);`. 

And now, again the outline is cut at the end...

So I copied the code from `AddImage` function and used it instead:

```cpp
const bool push_texture_id = drawableRight != window->DrawList->_CmdHeader.TextureId;
if (push_texture_id)
	window->DrawList->PushTextureID(drawableRight);

window->DrawList->PrimReserve(6, 4);
window->DrawList->PrimRectUV(bb.Min, bb.Max, ImVec2(0.0f, 0.0f), ImVec2(1.0f, 1.0f), 0xffff00ff);

if (push_texture_id)
	window->DrawList->PopTextureID();
```

again, the outline is cut at the end, so I commented out `window->DrawList->PushTextureID` and `window->DrawList->PopTextureID`

```cpp
//const bool push_texture_id = drawableRight != window->DrawList->_CmdHeader.TextureId;
//if (push_texture_id)
//	window->DrawList->PushTextureID(drawableRight);

window->DrawList->PrimReserve(6, 4);
window->DrawList->PrimRectUV(bb.Min, bb.Max, ImVec2(0.0f, 0.0f), ImVec2(1.0f, 1.0f), 0xffff00ff);

//if (push_texture_id)
//	window->DrawList->PopTextureID();
```

the result is kinda weird, but the outline is finished correctly now:

![image](https://github.com/ocornut/imgui/assets/43299401/99cbc8a8-0e60-40c9-8476-47f6c73b338a)

any idea why the outline is cut when rendering a texture? How can I get it right?

**Comment by ocornut** [comment]
The last assertion (removing the PushTextureID()/PopTextureID() making that difference) is really surprising. What I would suggest to do is to condition those toggles on the state of a key mod (e.g. `if (push_texture_id && ImGui::GetIO().KeyCtrl)` and also for the Image/AddImage calls with another key/mod) in attempt to try to understand if all the shapes are at the same location when doing those changes. It is possible that some combination are shifting things a little.

BeginHorizontal() and Spring() are not stock dear imgui function so I don't really know how they work and it's hard for me to get into details (I believe that code occasionally alter vertices and it may have bugs in a situation where additional ImDrawCmd are interleaved). It would be better to see raw dear imgui code.

**Comment by SC5Shout** [comment]
`BeginHorizontal()` and `Spring()` functions shouldn't cause the problem, but to be sure I've removed them and used `ImGui::SameLine(label_size.x + height);`. 

I've also added the key mod `if (push_texture_id && ImGui::GetIO().KeyCtrl)`. The result is the same:

https://github.com/ocornut/imgui/assets/43299401/32dd71bf-0d36-4db6-9b8d-363a3932d468


full code:

```cpp
void MyWidget(const char* label, ImTextureID drawableRight)
{
	using namespace ImGui;
	
	ImGuiWindow* window = GetCurrentWindow();
	if (window->SkipItems)
		return;

	ImGuiContext& g = *GImGui;
	const ImGuiStyle& style = g.Style;
	const ImGuiID id = window->GetID(label);
	const ImVec2 label_size = CalcTextSize(label, NULL, true);

	float height = label_size.y + style.FramePadding.y * 2.0f;
	const ImVec2 size = ImVec2(GetContentRegionAvail().x, label_size.y + style.FramePadding.y * 2.0f);

	{		
		const ImVec2 pos = window->DC.CursorPos;
		const ImRect bb(pos, pos + size);
		ItemSize(size, style.FramePadding.y);
		ItemAdd(bb, id);

		bool hovered, held;
		bool pressed = ButtonBehavior(bb, id, &hovered, &held);

		RenderNavHighlight(bb, id);
		RenderFrame(bb.Min, bb.Max, GetColorU32(ImGuiCol_Button), true, style.FrameRounding);

		RenderTextClipped(bb.Min + style.FramePadding, bb.Max - style.FramePadding, label, NULL, &label_size, ImVec2(0.0f, 0.0f), &bb);

		//outline full width
		{
			constexpr float borderThickness = 1.0f;
			const ImRect fullwithBb = ImRect(bb.Min - ImVec2(borderThickness, borderThickness), bb.Max + ImVec2(borderThickness, borderThickness));

			window->DrawList->AddRect(fullwithBb.Min, fullwithBb.Max, 0xff0000ff, 0.0f, 0, borderThickness);
		}
	}

	ImGui::SameLine(label_size.x + height);
	
	{
		const ImVec2 pos = window->DC.CursorPos + ImVec2(1.0f, 1.0f);
		const ImVec2 size = { height - 2.0f, height - 2.0f };
		const ImRect bb(pos, pos + size);

		const bool push_texture_id = drawableRight != window->DrawList->_CmdHeader.TextureId;
		if (push_texture_id && ImGui::GetIO().KeyCtrl)
			window->DrawList->PushTextureID(drawableRight);

		window->DrawList->PrimReserve(6, 4);
		window->DrawList->PrimRectUV(bb.Min, bb.Max, ImVec2(0.0f, 0.0f), ImVec2(1.0f, 1.0f), 0xffff00ff);

		if (push_texture_id && ImGui::GetIO().KeyCtrl)
			window->DrawList->PopTextureID();
	}
}
```

**Comment by ocornut** [comment]
If I can run your code but I see no difference while holding Alt.
Have you tested the repro? What's the context/calling code?

**Comment by ocornut** [comment]
If I do this I can repro your issue:
```cpp

ImGui::Begin("Issue #7108");
if (ImGui::BeginTable("table", 2))
{
    ImGui::TableNextRow();
    ImGui::TableNextColumn();
    ImGui::TableNextColumn();
    MyWidget("Hello", 0);
    ImGui::EndTable();
}
ImGui::End();
```

See your first post:

![image](https://github.com/ocornut/imgui/assets/43299401/c01cd3b2-f642-448a-b8ee-8a7a2bbd160b)

> The black rectangle is available space for this widget (it's not rendered). The red rectangle is the outline.

This suggests you are rendering the red outline OUTSIDE the available space.

**Indeed there is a mismatch between your declared layout size and your rendered output:**

**Your calls to `ItemSize()` and `ItemAdd()` are using bb/size, whereas you are drawing outside thoses boundary with your `AddRect()` calls.** 

The table system uses layout boundaries to detect if elements drawn in a given column are straying out of the column or not.  Direct ImDrawList calls are not accounted (\*). When everything drawn in a column stays without boundaries then we can merge the columns draw call with its parent.
The "bug" is in fact correct column clipping, the "non-cut" version is a bug following our optimization.

The reason that the use of AddImage() makes a difference is that the table merging code doesn't attempt to merge when there are multiple draw calls in the same column.

You should change your AddRect() calls to draw within the declared layout boundaries.

(\*: Note that we have an old work-in-progress change to record vertices bounding box in ImDrawCmd. This is unfinished but when done it'll be possible for use to detect the bounding box of direct ImDrawList calls).

**Comment by SC5Shout** [comment]
Oh, alright. I get it.

Thank you for your time
