### ISSUE TITLE
ImGuiPushStyle() - Assertion Fails

### ISSUE THREAD

**Issue by AndrewDCox** [ocornut/imgui#711]
I'm trying to set the style of a window (the edge rounding, specifically) and am getting a failed assertion error. I've added some code to the opengl_example project in `main.cpp`, at line 80.

    ImGui::SetNextWindowPos(ImVec2(0,0));
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);

    ImGui::Begin("My Window");
    if(ImGui::Button("Push Me!")){
        // Do something
    }
    ImGui::PopStyleVar();
    ImGui::End();

The code compiles, but when I run the executable I get the following error

    Assertion failed: (*p_backup == current && "PushStyleVar/PopStyleVar Mismatch!"), function CheckStacksSize, file ../../imgui.cpp, line 3624.
    Abort trap: 6

If I move the `PushStyleVar` line to the line after `ImGui::Begin`, the code will run without the failed assertion, but the specified style changes are not applied to the window. Finally, with this modification, if I remove the `PopStyleVar` command, I once again receive the failed assertion error. This seems like a bug to me, but I could just be misinformed on the usage of the Push/Pop Style commands. How can I adjust the style of a window if the style editing command has to be placed after `ImGui::Begin` ?

My setup: OS X 10.11.5, Macbook Pro (Retina, mid 2015)

**Comment by ocornut** [comment]
You can move the PopStyleVar() call added the End().

**Comment by AndrewDCox** [comment]
> You can move the PopStyleVar() call added the End()

after the `End()`? That works beautifully, thanks for your help!

Code that works:

    ImGui::SetNextWindowPos(ImVec2(0,0));
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);

    ImGui::Begin("My Window");
    if(ImGui::Button("Push Me!")){
        // Do something
    }
    ImGui::End();
    ImGui::PopStyleVar();
