### ISSUE TITLE
Enable multi viewport for WGPU Desktop

### ISSUE THREAD

**Issue by Zelif** [ocornut/imgui#7110]
**Version/Branch of Dear ImGui:**

Version: 1.90.1 (19002)
Branch: docking

**Backends/Renderer/Compiler/OS**

Back-ends: imgui_impl_GLFW.cpp + imgui_impl_WGPU.cpp
Compiler: [VS-MSVC, gcc, emscripten
Operating System: Windows/Linux/Web

**My Issue/Question:**
Would we be able to have multi viewport enabled on the webGPU renderer? 
Silly enough I didn't listen to the wise comments telling me not to attempt this.. soo..
Someone better than I should attempt this :D

***My attempt:***
Following roughly the vulkan implementation, I have managed to get it working, there are a couple of issues though. I do not know imgui/webgpu well enough and resorted to using the dawn header for glfw, and some objects I do not yet know how to expand to just webgpu.h. 

Only functions that require reworking would be:
 - ~~`ImGui_ImplWGPU_CreateWindow` - (Not sure how to create the surface while being platform agnostic without using a bunch of if defs for each platform/OS. I did notice what I thought was the same issue with the vulkan renderer, thus needing the CreateWindowVK for the platform side I assume?)~~
- ~~`ImGui_ImplWGPU_RenderWindow` - (I do not know the lower workings of webGPU enough to replicate the whole render pass/command buffer steps so this relies too heavy on the dawn C++ header)~~

I had changed the `ImGui_ImplWGPU_Init` to pass in and store the insance(For creating the surface) as well, so would be a breaking change unless there is a better way to handle that?

The other functions were easy enough to figure out. 

**Screenshots/Video**
https://github.com/ocornut/imgui/assets/666945/5afde189-32f2-460e-9229-4947bbe25cc5

I might in the coming days add an example or modify the webgpu example to compile with dawn.
Code changes. (Not ready to merge in until issues are sorted)
[Commit ](https://github.com/ocornut/imgui/commit/85a5d341edbbbf99cdf4a291a067f8f66268a9d8)
[Fixed Render window](https://github.com/Zelif/imgui/commit/b6671d974bf1628dc45687d7a9d98acdd2c2c35d)
[Fixed create window](https://github.com/Zelif/imgui/commit/739b9548ed20bc898c01985e716929857efb71e1)
[last update](https://github.com/Zelif/imgui/commit/40c95de161e4e5e156e80d4ca6aa33c3cc461898)

**Updated**
Removed all webgpu_cpp.h references, only known working on windows, there is a ifdef in the `ImGui_ImplWGPU_CreateWindow`  that i am unsure how the other platforms are handled I was looking in `imgui_impl_glfw.cpp` and `imgui_impl_sdl2.cpp` and did not see how the handle for linux (wayland/X11)  are sourced/set is it just in `viewport->PlatformHandle`? 

I guess this is why the surface stuff in vulkan has it's own platform creation. 

**Standalone, minimal, complete and verifiable example:** _(see https://github.com/ocornut/imgui/issues/2261)_

Changes - add and link dawn

Add config flag
```
io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
```

Update init function add instance
```
ImGui_ImplWGPU_Init(device.Get(), 3, WGPUTextureFormat::WGPUTextureFormat_BGRA8Unorm, WGPUTextureFormat::WGPUTextureFormat_Undefined);
```
to
```
ImGui_ImplWGPU_Init(instance.Get(), device.Get(), 3, WGPUTextureFormat::WGPUTextureFormat_BGRA8Unorm, WGPUTextureFormat::WGPUTextureFormat_Undefined);
```

Add platform renderings after main rendering
```
    if (ImGui::GetIO().ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
    {
        ImGui::UpdatePlatformWindows();
        ImGui::RenderPlatformWindowsDefault();
    }
```

**Comment by ocornut** [comment]
It would be better to open a pull-request (even if not ready to merge) rather than an issue with multiple commit links. You can freely update the PR by pushing to its branch.

Until now I have also assumed that WebGPU was a technology for web-browsers only, so I would also need an example updated to compile on desktop to test this.

**Comment by Zelif** [comment]
Will do, I had only really planned to do the first commit as I had no idea how any of it worked :D 
I will work on updating the emscirpten example as that is already 95% of the way there.

**Comment by ocornut** [comment]
Closing this as the PR is enough to track this. Thanks!
