### ISSUE TITLE
How to disable auto focus moving to random pop-up window after close current window

### ISSUE THREAD

**Issue by KarKarKarKarkarkar** [ocornut/imgui#7113]
How to disable auto focus moving to random pop-up window after close current window?

I has multiple windows, and when close one, focus moved to random another window, how to disable this feature ?

**Comment by ocornut** [comment]
If the focused window is closed, focus is normally given to the window under it in the focus stack. I am surprised this is bothering you.

Please provide more details about your use case and situation.

**Comment by KarKarKarKarkarkar** [comment]
In my tool I uses check "if no window focused - allow camera/movement controls", and I got big problems with "auto focus" feature added in imgui, you can allow to disable this feature?

**Comment by GamingMinds-DanielC** [comment]
Keep track of your windows. On a new frame, `ImGui::SetWindowFocus(nullptr);` if the window that had the focus last frame is no longer open.

Other that that, maybe consider clicking or right clicking into your viewport to focus it for camera/movement controls. That would prevent accidental movements as well.

**Comment by ocornut** [comment]
> In my tool I use "if no windows focused - allow camera/movement controls",

This may be a XY Problem, i think you should use the io.WantCaptureMouse signal instead, as discussed in the FAQ.

**Comment by KarKarKarKarkarkar** [comment]
@ocornut if no windows focused, it anyway do focus one of windows.

For example I select window WIN1 , it focused, I do click in app (now no windows focused) then I close WIN2, and now WIN1 is focused.

Behaviour that I wait: if no windows focused before close, no need do focus window.

Or possibility to fully disable "recover focus" feature. 
You can add something like DISABLE_AUTO FOCUS flag in imgui initialization?

**Comment by KarKarKarKarkarkar** [comment]
@ocornut for example OS Windows, no has this feature, and it nice, no problems. If possible, please add possibility to disable auto focus like in Windows OS

**Comment by KarKarKarKarkarkar** [comment]
I think autofocus is really bad feature and want to disable this option by default....

**Comment by ocornut** [comment]
You should explain why io.WantCaptureMouse doesn’t do what you want first. And I will need you to carefully explains and prove your statements.

**Comment by KarKarKarKarkarkar** [comment]
@ocornut autofocus is bad, also it used not for mouse, for key input (hotkeys). Without mouse no problems

**Comment by KarKarKarKarkarkar** [comment]
If no imgui focused - allow controls like hotkeys/mouseclick etc

**Comment by ocornut** [comment]
I don’t have time for this sorry, you are blocked.
We are overwhelmed by requests, if you don’t follow the rules you are out.
