### ISSUE TITLE
How can ImGui allow a window opened by a specific ‘begin’ to automatically detach (or cancel the automatic merge) from the main window (for a specific window, not all)

### ISSUE THREAD

**Issue by muchenspace** [ocornut/imgui#7117]
How can ImGui allow a window opened by a specific ‘begin’ to automatically detach (or cancel the automatic merge) from the main window (for a specific window, not all)

**Comment by ocornut** [comment]
The answer is here:
https://github.com/ocornut/imgui/issues/7105#issuecomment-1848954140

Please make sure to read the Glossary (https://github.com/ocornut/imgui/wiki/Glossary) and issue guidelines when opening new issues.
