### ISSUE TITLE
How to redock a window during runtime?

### ISSUE THREAD

**Issue by talkalotwhenim** [ocornut/imgui#7122]
**My Issue/Question:**

Is it possible to programmatically redock a window? In my example I have a checkbox that is initially checked so my window will be docked. When I uncheck the checkbox, I pass the no docking flag to the window. This works as expected but when I check the box again I would like to have the window be redocked, not just gain the ability to dock the window again. So I would like to dock the window without having to drag and drop it. I'm not sure how to go about this. I've tried changing the condition to always but that didn't work.

**Standalone, minimal, complete and verifiable example:** 
```
ImGuiWindowFlags window_flags = 0;
static bool undocked = false;

if (undocked)
     {
window_flags |= ImGuiWindowFlags_NoDocking;
     }
if (ImGui::Begin("Window", NULL, window_flags))
{
     ImGui::Checkbox("Toggle", &docked);
ImGui::SetWindowDock(ImGui::GetCurrentWindow(), node_id, ImGuiCond_Once);
    
}
ImGui::End();


```

**Comment by GamingMinds-DanielC** [comment]
Try `ImGui::DockBuilderDockWindow(...)`, you need to know or find the dock node id you want to dock into first. When done, call `ImGui::DockBuilderFinish(...)` This interface is not yet public, so you need to include `imgui_internal.h` for it and it isn't guaranteed to remain stable.

**Comment by GamingMinds-DanielC** [comment]
Even in the updated example code `ImGuiWindowFlags_NoDocking` is still without any function, it never gets passed to the window.

**Comment by talkalotwhenim** [comment]
> Even in the updated example code `ImGuiWindowFlags_NoDocking` is still without any function, it never gets passed to the window.

Updated

**Comment by ocornut** [comment]
The code doesn't compile and is still incomplete. Without intending it, but are basically omitting the important information by not providing a complete, real, actually tested/pastable repro.
Also we don't know what `node_id` refers to.

**Comment by GamingMinds-DanielC** [comment]
> Updated

Besides the unknown `node_id`, the checkbox refers to the now unknown `docked` while there is a static variable `undocked`. In this latest update, `SetWindowDock` suddenly gets called every frame regardless of the value of any flag. Please put a bit of effort into your repro case, make sure it compiles and actually reproduces your issue. This is not to help us, but to enable us to help you.
