### ISSUE TITLE
Changing window with glfw

### ISSUE THREAD

**Issue by Po4ti** [ocornut/imgui#7124]
**Back-end/Renderer/Compiler/OS**
Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
Operating System: Windows 11

**My Issue/Question:**

I want to change window pointer during window loop, it works perfectly with bare glfw, however, imgui causes the following assertion throw:
```
Assertion failed: g.IO.DisplaySize.x >= 0.0f && g.IO.DisplaySize.y >= 0.0f && "Invalid DisplaySize value!"
```
Is there any way to handle window changing process?

**Standalone, minimal, complete and verifiable example:** 
Code snippet from the end of window loop
```
if (glfwGetKey(window, GLFW_KEY_E) == GLFW_PRESS)
{
  GLFWwindow* temp_window_ptr;
  createWindow(temp_window_ptr); //Basic window creation
  glfwDestroyWindow(window);
  window = temp_window_ptr;
  temp_window_ptr = NULL;
  
  int width, height;
  glfwGetFramebufferSize(window, &width, &height);
  cout << "w: " << width << "h: " << height << "\n"; // Returns 1280 x 720
}
```

**Comment by GamingMinds-DanielC** [comment]
Shutdown your platform backends before destroying the old window, then initialize them again for the new one. If necessary, destroy and recreate the ImGui context as well.

**Comment by Po4ti** [comment]
It works, thanks!
