### ISSUE TITLE
Imgui Linker Errors

### ISSUE THREAD

**Issue by Jillinger** [ocornut/imgui#7128]
(1) **Decide which branch to pull**: Docking
Done

(3) **Add files to your project or build system of your choice, so they get compiled and linked into your app.**
- Add all source files in the root folder: imgui/{*.cpp,*.h}.
- Add selected imgui/backends/imgui_impl_xxxx{.cpp,.h} files corresponding to the technology you use from the imgui/backends/ folder (e.g. if your app uses SDL2 + DirectX11, add imgui_impl_sdl2.cpp, imgui_impl_dx11.cpp etc.). If your engine uses multiple APIs you may include multiple backends.
- Visual Studio users: Add misc/debugger/imgui.natvis and misc/debugger/imgui.natstepfilter to improve the debugging experience.

Done

Most users with linking problems are in fact having problems because of the underlying windowing or graphics tech they use. ... **If you already have an app running then by definition you shouldn't have a problem including corresponding header files and linking libraries.**

I already have an app running, but getting linker errors. So 
- I  created a new project from scratch - Win32 Desktop Application.
- Link to my include folders - Project Settings -> C/C++ -> Additional Include Directories (Add folders : imgui; imgui/backends; imgui/misc/debugger)

(1) **Add imgui/ to include paths**. Include header files for main lib (#include "imgui.h") + backends (e.g. #include "imgui_impl_win32.h", #include "imgui_impl_dx11.h").
Done

Example: If you are using Raw Win32 API + DirectX11
Add to Includes:
```
#include "imgui.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx11.h"
```
Done

Add to Initialization:
```
// Setup Dear ImGui context
IMGUI_CHECKVERSION();
```

**Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "bool __cdecl ImGui::DebugCheckVersionAndDataLayout(char const *,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64)" (?DebugCheckVersionAndDataLayout@ImGui@@YA_NPEBD_K11111@Z) referenced in function wWinMain**

Did I fail to do something? I apologize, because the instructions seem so easy to follow.
I don't understand why I am getting this problem.

**Comment by ocornut** [comment]
```cpp
Error LNK2019 unresolved external symbol "bool __cdecl ImGui::DebugCheckVersionAndDataLayout(char const ,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64)" 
```
Is that the only linking error?
This would look like you haven't added imgui.cpp to your build, but normally other errors would show as well.

**Comment by Jillinger** [comment]
Other linking errors occur when I add more lines of imgui code, but I figured one was enough, so I just added the first line of code, and posted the error it returned.
If you want to see the errors for the following lines of code, I can post those.

I copied all the .cpp, and .h files in the root directory. The imgui.cpp file is among them.

**Comment by GamingMinds-DanielC** [comment]
Did you just copy the files to your source directory? You need to add them to your project as well, otherwise they won't be part of the build.

**Comment by Jillinger** [comment]
That would be the part I missed, or perhaps I did not understand.
I assumed "build system of your choice" meant following the standard way of linking folders using the project settings.
I guess that's homework for me.

Does this mean I need to put the imgui folder inside the project, and then use 
Add -> Existing Items for each file?

**Comment by GamingMinds-DanielC** [comment]
In Visual Studio you can create folders with `Add -> New Filter`, name it (f.e. "ImGui"), then you can right click on that and `Add -> Existing Item...`. You can select multiple items, you don't have to do them one by one. Or you can drag & drop from the file explorer to the folder in your Visual Studio project. The important part is that the project needs to know about all the files it has to build.

**Comment by Jillinger** [comment]
Okay, thanks.
The first method doesn't add folders.
However, the most important thing is what matters.
The errors are gone. (I got new ones, but that's another issue) Thanks for your help.
