### ISSUE TITLE
Using the SDL renderer will crash when removing the device

### ISSUE THREAD

**Issue by pipiwoaini** [ocornut/imgui#7134]
When using d3d11 as the SDLRender rendering backend, when disabling the graphics card in computer management, the IMGUI will crash。
![1](https://github.com/ocornut/imgui/assets/51773992/d8a03d2f-37c2-4568-ad77-6ef0e53ac360)
![3](https://github.com/ocornut/imgui/assets/51773992/fa63ed45-7c8f-47dc-88cf-7901b10179b3)

**Comment by ocornut** [comment]
> "when disabling the graphics card in computer management, the IMGUI will crash" 

??
I am not sure we ought to support esoteric use cases like that. It this is mostly up to the application to handle if a context or device gets remove, not up to the backend.
Lacking more details there's not much we can do on our end.
