### ISSUE TITLE
Missing users

### ISSUE THREAD

**Issue by OliverLetterer** [ocornut/imgui#7138]
It would be nice to have the people using Dear ImGui listed in the appropriate section in the README!

**Comment by ocornut** [comment]
The readme has:

“Who uses Dear ImGui?

See the [Quotes](https://github.com/ocornut/imgui/wiki/Quotes), [Sponsors](https://github.com/ocornut/imgui/wiki/Sponsors), and [Software using Dear ImGui](https://github.com/ocornut/imgui/wiki/Software-using-dear-imgui) Wiki pages for an idea of who is using Dear ImGui. Please add your game/software if you can! Also, see the https://github.com/ocornut/imgui/issues/6897! “

What more would you like?
