### ISSUE TITLE
Multi-line text input at Test Window has memory leak when we use ctrl-c, ctrl-v at the window

### ISSUE THREAD

**Issue by dodo1004** [ocornut/imgui#714]
Multi-line text input at Test Window has memory leak when we use ctrl-c, ctrl-v at the window

you can detect it you just copy the window text and past at the same text window.

**Comment by ocornut** [comment]
Are you talking about an actual leak or a growing buffer? Can you show samples of your detection?

**Comment by dodo1004** [comment]
I am now busy at a project so can not see it deeply.
but what I saw is that when I see a memory leak the Pasted memory is not freed 

Detected memory leaks!
Dumping objects ->
{102535} normal block at 0x0F487ED0, 322 bytes long.
 Data: </*  The Pentium > 2F 2A 0A 20 54 68 65 20 50 65 6E 74 69 75 6D 20 
Object dump complete.

and it is not a growing buffer.
I am using VS 2015 and memory leak check option is like this
_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF | _CRTDBG_CHECK_EVERY_1024_DF);

**Comment by ocornut** [comment]
I cannot seem to repro. Did you call ImGui::Shutdown() ?
All the memory held by the text edit state is carried in ImVector<> which has a destructor.

**Comment by dodo1004** [comment]
void ImGui_ImplDX11_Shutdown()
{
    ImGui_ImplDX11_InvalidateDeviceObjects();
    ImGui::Shutdown();
    g_pd3dDevice = NULL;
    g_pd3dDeviceContext = NULL;
    g_hWnd = (HWND)0;
}

Detected memory leaks!
Dumping objects ->
{90594} normal block at 0x0F085100, 349 bytes long.
 Data: <*  The Pentium F> 2A 0A 20 54 68 65 20 50 65 6E 74 69 75 6D 20 46 
Object dump complete.

yes i checked it again.

**Comment by dodo1004** [comment]
and I will try to  check it out too.

**Comment by ocornut** [comment]
Interesting/weird, I get it with the DX11 sample but not with the OpenGL one.

**Comment by ocornut** [comment]
Oh I see, it isn't InputTextMultiline(), but the default clipboard helper for Windows:

```
static const char* GetClipboardTextFn_DefaultImpl()
{
    static char* buf_local = NULL;
    if (buf_local)
    {
        ImGui::MemFree(buf_local);
        buf_local = NULL;
    }
```

There's a local buffer.

**Comment by ocornut** [comment]
Fixed, thanks!
It was a one-time end of application leak so really not causing a problem in the long run, but obviously correct to fix.

**Comment by dodo1004** [comment]
Nice Job.

It is good to run now.
