### ISSUE TITLE
Vulkan Backend: validation error/exception on ImGui_ImplVulkan_AddTexture() call to vkUpdateDescriptorSets()

### ISSUE THREAD

**Issue by shawnhatori** [ocornut/imgui#7140]
**Version/Branch of Dear ImGui:**

Version: 1.90 (latest)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.cpp + imgui_impl_vulkan.cpp
Compiler: MSVC
Operating System: Windows 11

**My Issue/Question:**
NOTE: I am using C bindings generated by `dear_bindings`. They seem to be working as expected and from what I can tell are unrelated to this issue.

I have a Vulkan renderer that I am trying to integrate ImGui into using the provided backends. The ImGui Vulkan backend was recently changed so I am trying to use the new, simpler API. My code looks something like this:
```
// Initialization.

ImGui_ImplVulkan_InitInfo imgui_ii = {.Instance = vk->i,
                                        .PhysicalDevice = vk->pd,
                                        .Device = vk->d,
                                        .QueueFamily = vk->queue_family_idx,
                                        .Queue = vk->q,
                                        .DescriptorPool = vk->dp,
                                        .MinImageCount = 2,
                                        .ImageCount = 2};
ok = cImGui_ImplVulkan_Init(&imgui_ii, vk->rp);
if (!ok)
{
    return false;
}

for (;;)
{
        cImGui_ImplVulkan_NewFrame();
        cImGui_ImplWin32_NewFrame();
        ImGui_NewFrame();

        // Update uniform buffers.

        // Draw.

        imgui_ui();
        ImGui_Render();
        cImGui_ImplVulkan_RenderDrawData(ImGui_GetDrawData(), vk->cb);

        vkCmdEndRenderPass(vk->cb);
        err = vkEndCommandBuffer(vk->cb);
        if (err)
        {
            return false;
        }

        // Submit queue, wait, and present.
}
```

I am getting the following error when I run this code, when `cImGui_ImplVulkan_NewFrame()` is called.
```
Validation Error: [ UNASSIGNED-GeneralParameterError-RequiredParameter ] | MessageID = 0x99fb7dfd | vkUpdateDescriptorSets: required parameter pDescriptorWrites[0].dstSet specified as VK_NULL_HANDLE
[12/17/2023 7:06:23 PM] Exception thrown at 0x00007FFAF77B2554: 0xC0000005: Access violation reading location 0x0000000000000088.
```

Looking at the relevant code:
1. ImGui_ImplVulkan_CreateFontsTexture() calls ImGui_ImplVulkan_AddTexture() [line 695](https://github.com/ocornut/imgui/blob/0d582dabf34e9e31f072b1ee5c353c18351b4424/backends/imgui_impl_vulkan.cpp#L695)
2. ImGui_ImplVulkan_AddTexture() calls vkUpdateDescriptorSets() [line 1174](https://github.com/ocornut/imgui/blob/0d582dabf34e9e31f072b1ee5c353c18351b4424/backends/imgui_impl_vulkan.cpp#L1174C11-L1174C11)
3. vkUpdateDescriptorSets() uses VkWriteDescriptorSet where `dstSet = descriptor_set`. `descriptor_set` is created in the previous block, but it seems that after `vkAllocateDescriptorSets` it is still null.

**Comment by ocornut** [comment]
Does `vkAllocateDescriptorSets()` returns an error?

Note that our example are creating a descriptor pool, your app/code will need one as well.
See our main.cpp code:
```cpp
    // Create Descriptor Pool
    // The example only requires a single combined image sampler descriptor for the font image and only uses one descriptor set (for that)
    // If you wish to load e.g. additional textures you may need to alter pools sizes.
    {
        VkDescriptorPoolSize pool_sizes[] =
        {
            { VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1 },
        };
        VkDescriptorPoolCreateInfo pool_info = {};
        pool_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
        pool_info.flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
        pool_info.maxSets = 1;
        pool_info.poolSizeCount = (uint32_t)IM_ARRAYSIZE(pool_sizes);
        pool_info.pPoolSizes = pool_sizes;
        err = vkCreateDescriptorPool(g_Device, &pool_info, g_Allocator, &g_DescriptorPool);
        check_vk_result(err);
    }
```

**Comment by shawnhatori** [comment]
Ah I see. I was passing my application's own descriptor pool and I thought I was increasing `maxSets` and `poolSize` sufficiently for it to work, but I switched over to using a dedicated pool for ImGui and it worked. Is that the expected and recommended use?

For the DX12 backend, I just had to add an SRV descriptor to the end of my existing descriptor heap and point to it. It was a very nice API and well documented in the [header file](https://github.com/ocornut/imgui/blob/8340a30d277db0831676eb1e1be7deed2d3ce294/backends/imgui_impl_dx12.h#L30).

Two documentation suggestions for `imgui_impl_vulkan.h`:
1. Have a similar comment that details how to integrate with the API.
2. Clearly indicate which of the `ImGui_ImplVulkan_InitInfo` members are required for `ImGui_ImplDX12_Init()` to succeed. I had to find this out by reading the implementation code.

Based on your reply, I'd be happy to help contribute to providing greater clarity here.

**Comment by shawnhatori** [comment]
As a sidenote, is there a reason why in `ImGui_ImplVulkan_Init()`, `VkRenderPass` is a separate parameter and not part of the `ImGui_ImplVulkan_InitInfo` struct (code link)[https://github.com/ocornut/imgui/blob/8340a30d277db0831676eb1e1be7deed2d3ce294/backends/imgui_impl_vulkan.h#L77C101-L77C101]? It felt a bit awkward to write, but I just want to make sure I am using the API correctly.

**Comment by shawnhatori** [comment]
The documentation concerns are addressed in this PR: https://github.com/ocornut/imgui/pull/7166

**Comment by shawnhatori** [comment]
See: https://github.com/ocornut/imgui/issues/7140#issuecomment-1864927358

I refactored my Vulkan renderer and providing my own descriptor pool (not one specifically for ImGui) worked. I was likely incorrectly setting the appropriate number of sets and descriptors required. I will adjust the documentation change in my PR to make this explicit

As well, the existing implementation requires setting `VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT` to silence validation errors because RemoveTexture() tries to free a descriptor on shutdown. I don't think this should happen. Since it's a caller-supplied pool, it should be the caller's responsibility to free. Removing that call removes a major restriction on the pool a user can provide.

https://github.com/ocornut/imgui/pull/7166
