### ISSUE TITLE
How does io.WantCaptureXXX work?

### ISSUE THREAD

**Issue by kevyuu** [ocornut/imgui#7154]
Should I call io.WantCaptureXXX after ImGui::NewFrame() or before it? Or maybe after Render()? 
From the faq example, It is called right after AddMouseButtonEvent, but when I check the implementation, I don't see any modification to those variable in that function?

Seems like it is modified after called to NewFrame()? How exactly does it work? Will ImGui check the input against previous frame. Since before call to EndFrame(), ImGui will have no idea what ui component is active in current frame.

**Comment by ocornut** [comment]
> Should I call io.WantCaptureXXX after ImGui::NewFrame() or before it? Or maybe after Render()?

You don't "call" io.WantCaptureXXXX it is a bool value. It is modified by `NewFrame()` but it shouldn't matter to you when it is modified (but it's not modified by `io.AddInputXXX()` function).

- Your input handler should always pass inputs to Dear ImGui
- Your input handler should not pass mouse inputs to underlying application if `io.WantCaptureMouse` is set.

- In the FAQ example, the order doesn't matter:
```cpp
void MyLowLevelMouseButtonHandler(int button, bool down)
{
    // (1) ALWAYS forward mouse data to ImGui! This is automatic with default backends. With your own backend:
    ImGuiIO& io = ImGui::GetIO();
    io.AddMouseButtonEvent(button, down);

    // (2) ONLY forward mouse data to your underlying app/game.
    if (!io.WantCaptureMouse)
        my_game->HandleMouseData(...);
}
```
Will be the same as
```cpp
void MyLowLevelMouseButtonHandler(int button, bool down)
{
    // (2) ONLY forward mouse data to your underlying app/game.
    if (!io.WantCaptureMouse)
        my_game->HandleMouseData(...);

    // (1) ALWAYS forward mouse data to ImGui! This is automatic with default backends. With your own backend:
    ImGuiIO& io = ImGui::GetIO();
    io.AddMouseButtonEvent(button, down);
}
```

What problem are you trying to solve?
We unfortunately don't have spare resources to explain you how the codebase work if you don't have a problem.

**Comment by ocornut** [comment]
Closing as answered. Let us know if you have further questions and we can reopen.
