### ISSUE TITLE
Multi-window creation component context cannot be used normally

### ISSUE THREAD

**Issue by Augenstern-create** [ocornut/imgui#7155]
Version:1.90
Branch: master

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Compiler: MSVC
Operating System: Windows10 -64

**My Issue/Question:**

Hi, I'm currently working on a project that requires the creation of two Windows windows. I wish to create components individually in each window and I was wondering if you have any examples related to this. The reason is that my own code has some errors, such as white screen flashback, context alignment and other issues, and these errors cannot run normally.

**Screenshots/Video**

![imgui-Debug](https://github.com/ocornut/imgui/assets/88466224/0bc541e9-1304-4d42-a69a-7cbe31e1d1d1)

**Standalone, minimal, complete and verifiable example:** 
```
#define GLFW_EXPOSE_NATIVE_WIN32
#include "imgui.h"
#include "imgui_impl_glfw.h"
#include "imgui_impl_opengl3.h"
#include < Windows.h>
#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include "GLFW/glfw3native.h"
#include "Include.h"

int UIPlay2() {
    if (!glfwInit()) {
        LOGE("Failed to initialize GLFW\n");
        return -1;
    }

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    // Create the first window
    GLFWwindow* window1 = glfwCreateWindow(640, 480, "Window 1", NULL, NULL);
    if (!window1) {
        LOGE("Failed to create GLFW window 1\n");
        glfwTerminate();
        return -1;
    }
    IMGUI_CHECKVERSION();
    ImGuiContext* ctx1 = ImGui::CreateContext();
    ImGui::SetCurrentContext(ctx1);
    glfwMakeContextCurrent(window1);
    ImGui_ImplGlfw_InitForOpenGL(window1, true);

    if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
        LOGE("Failed to initialize GLAD for window 1\n");
        glfwDestroyWindow(window1);
        glfwTerminate();
        return -1;
    }

    // Create the second window
    GLFWwindow* window2 = glfwCreateWindow(640, 480, "Window 2", NULL, NULL);
    if (!window2) {
        LOGE("Failed to create GLFW window 2\n");
        glfwDestroyWindow(window1);
        glfwTerminate();
        return -1;
    }
    IMGUI_CHECKVERSION();
    ImGuiContext* ctx2 = ImGui::CreateContext();
    ImGui::SetCurrentContext(ctx2);
    glfwMakeContextCurrent(window2);
    ImGui_ImplGlfw_InitForOpenGL(window2, true);

    if (!gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)) {
        LOGE("Failed to initialize GLAD for window 2\n");
        glfwDestroyWindow(window1);
        glfwDestroyWindow(window2);
        glfwTerminate();
        return -1;
    }

    ImGui_ImplOpenGL3_Init();
    ImGuiIO& io = ImGui::GetIO();

    // Main loop
    while (!glfwWindowShouldClose(window1) && !glfwWindowShouldClose(window2)) {
        glfwPollEvents();
        // Render to window 1

        ImGui::SetCurrentContext(ctx1);
        glfwMakeContextCurrent(window1);
        ImGui_ImplGlfw_NewFrame();
        ImGui_ImplOpenGL3_NewFrame();
        ImGui::NewFrame();
        ImGui::Begin("BEGIN 1 !");
        ImGui::Text("%.0fFPS", io.Framerate);
        ImGui::End();
        ImGui::Render();
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
        glfwSwapBuffers(window1);

        // Render to window 2

        ImGui::SetCurrentContext(ctx2);
        glfwMakeContextCurrent(window2);
        ImGui_ImplGlfw_NewFrame();
        ImGui_ImplOpenGL3_NewFrame();
        ImGui::NewFrame();
        ImGui::Text(u8"text2");
        ImGui::End();
        ImGui::EndFrame();
        ImGui::Render();
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
        glfwSwapBuffers(window2);
    }

    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();

    // Cleanup
    glfwDestroyWindow(window1);
    glfwDestroyWindow(window2);
    glfwTerminate();

    return 0;
}
```

**Comment by Augenstern-create** [comment]
> You only called `ImGui_ImplOpenGL3_Init();` for one of your context. This should have triggered an assert when calling `ImGui_ImplOpenGL3_NewFrame()` on ctx1. Are your assert properly enabled? (try calling `IM_ASSERT(false)` and verify you get a visible error and debug break).
> 
> (Also there's no need to initialize GLAD twice if you use GLAD)

https://github.com/ocornut/imgui/assets/88466224/d9efbb94-594a-46b0-876f-497c6d37234b


Thank you for your answer. It allows me to handle the context of the two forms correctly, but a new problem arises. When I click and drag the Begin form in the Windows1 form, the Begin form in the Windows2 form is in the Mobile, how to solve this problem?

**Comment by ocornut** [comment]
**I forgot that our standard backends don't all provide multi-context support out of the box.**

Namely, when you call `glfwPollEvents()` it will dispatch all GLFW events to the current context, indiscriminate of which window emitted them.

```cpp
// FIXME: multi-context support is not well tested and probably dysfunctional in this backend.
// - Because glfwPollEvents() process all windows and some events may be called outside of it, you will need to register your own callbacks
//   (passing install_callbacks=false in ImGui_ImplGlfw_InitXXX functions), set the current dear imgui context and then call our callbacks.
// - Otherwise we may need to store a GLFWWindow* -> ImGuiContext* map and handle this in the backend, adding a little bit of extra complexity to it.
// FIXME: some shared resources (mouse cursor shape, gamepad) are mishandled when using multi-context.
```

While with SDL2 API design you can switch context before calling `ImGui_ImplSDL2_ProcessEvent()`, it's a little harder with GLFW backend right now.

The solution is currently:
- Call `ImGui_ImplGlfw_InitForOpenGL()` with install_callback=false.
- Install all 7 callbacks using `GLFWwindow* window` to your own function. In your function, change the imgui context based on window, then call the corresponding `ImGui_ImplGlfw_XXXX` callback declared in imgui_impl_glfw.h

**Comment by Augenstern-create** [comment]
> **I forgot that our standard backends don't all provide multi-context support out of the box.**
> 
> Namely, when you call `glfwPollEvents()` it will dispatch all GLFW events to the current context, indiscriminate of which window emitted them.
> 
> ```c++
> // FIXME: multi-context support is not well tested and probably dysfunctional in this backend.
> // - Because glfwPollEvents() process all windows and some events may be called outside of it, you will need to register your own callbacks
> //   (passing install_callbacks=false in ImGui_ImplGlfw_InitXXX functions), set the current dear imgui context and then call our callbacks.
> // - Otherwise we may need to store a GLFWWindow* -> ImGuiContext* map and handle this in the backend, adding a little bit of extra complexity to it.
> // FIXME: some shared resources (mouse cursor shape, gamepad) are mishandled when using multi-context.
> ```
> 
> While with SDL2 API design you can switch context before calling `ImGui_ImplSDL2_ProcessEvent()`, it's a little harder with GLFW backend right now.
> 
> The solution is currently:
> 
> * Call `ImGui_ImplGlfw_InitForOpenGL()` with install_callback=false.
> * Install all 7 callbacks using `GLFWwindow* window` to your own function. In your function, change the imgui context based on window, then call the corresponding `ImGui_ImplGlfw_XXXX` callback declared in imgui_impl_glfw.h
> * For `ImGui_ImplGlfw_MonitorCallback()` you need to call it for every context.

I understand what you mean. The first method is exactly what I expected. Thank you again for your support.
