### ISSUE TITLE
How can I confine the overlay of the modal window to the current window when it pops up?

### ISSUE THREAD

**Issue by o-3-o** [ocornut/imgui#7161]
When popping up a modal window, all child windows are being locked, which is not the behavior I desire. I want the modal overlay to be limited to the current child window. How can I achieve this?

To elaborate, my main window is a fullscreen window containing several child windows. In one of these child windows, I've added a modal window. When clicking a button, this modal window appears. However, the issue is that the overlay for the modal affects all child windows, and I want it to be confined to the current child window. What steps should I take to address this?

```
Dear ImGui 1.90.1 WIP (19001)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1938
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000443
 NavEnableKeyboard
 NavEnableGamepad
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

**Comment by CreatingBug** [comment]
![QQ截图20231222125934](https://github.com/ocornut/imgui/assets/51990072/e0f0e131-438c-4156-ae4e-b2b1983de91f)

This kind of effect!

**Comment by ocornut** [comment]
Please read Glossary on the wiki and make sure you are using precise and correct terminology here. You are using “child window” in a way that seems unrelated to dear imgui’s own concept of “child window”, and its not clear if viewports and platform windows are involved here.
