### ISSUE TITLE
Use InputText() with stdin and stdout

### ISSUE THREAD

**Issue by MrDeblasio** [ocornut/imgui#7162]
**Version/Branch of Dear ImGui:**

Version: v1.90
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp
Operating System: Windows

**My Issue/Question:**

How can I use the InputText() as a console to receive and transmit using stdout and stdin? I am making an app that creates a child process and captures its std handles. I am currently writing to and reading from them but I would like to integrate this into my existing InputText in my app. Is this possible? I know that stdout will be quite simple but I wonder if its possible to do this for stdin and stdout at the same time. Might just be a bunch of parsing and string math.

**Comment by MrDeblasio** [comment]
I've thought of a solution to use multiple text boxes, one multi-line for stdout and one single-line for stdin and then pass through the data from the single-line input to stdin when committed.
Would still like to know if above is possible.

**Comment by MrDeblasio** [comment]
I just looked through the demo and realized that the separate input box method is how the demo console does it too. Guess that is the right way to do it!

**Comment by ocornut** [comment]
From my point of view, your question is too vague/ambiguous to be answerable.

**Comment by MrDeblasio** [comment]
I've realized that it isn't possible to use InputText with an out stream and an in stream as a console in one input, you have to use a separate input for the in stream, like how the Demo window implements it.
I apologize for the badly worded and unnecessary question.

**Comment by ocornut** [comment]
I'm not sure I understand what it would mean to have the input and output in the same item. You may alter the style temporarily to hide the frame if you want to make the bottom line user-editable and yet look indistinguishable from other lines.

**Comment by MrDeblasio** [comment]
I was thinking along the lines of how CMD works, basically just one big text box that uses both the in and out streams in the same "text box", instead of a separate input for the in stream.

**Comment by ocornut** [comment]
You are repeating similar statement but it is still difficult to precisely understand what you mean.
Maybe draw a diagram or annotate screenshot.
You may move the `InputText()` at the current cursor position so it can change location.

**Comment by MrDeblasio** [comment]
![image](https://github.com/ocornut/imgui/assets/43344427/7253e751-4c73-460e-8745-574dbd145ee4)

Here is what I'm thinking of. Like in CMD, the program outputs and the user inputs to the same area. Is this possible?

To contrast I sketched the design of the ImGui console under CMD, using two text boxes.

I apologize for the confusion and late reply, thank you for humoring me!

**Comment by Bunny-B** [comment]
static char textToSendMessage[255] = "Enter a number ...";

	if (ImGui::InputTextWithHint(XOR("##MessageInput"), "", textToSendMessage, sizeof(textToSendMessage), ImGuiInputTextFlags_EnterReturnsTrue)) {
		//remove Enter a number ... from the string and get result
	}

you can manipulate the char array in a way to show the "program output" 
else you can use hint 

bool ImGui::InputTextWithHint(const char* label, const char* hint, char* buf, size_t buf_size, ImGuiInputTextFlags flags, ImGuiInputTextCallback callback, void* user_data)

it will display you message and erase it at user input
