### ISSUE TITLE
How to get single key press programmatically

### ISSUE THREAD

**Issue by aabilityuk** [ocornut/imgui#7165]
Hello, i need to get single ENTER key press programmatically, how can i do that, please help to find a solution.

I am trying this way, but it doesn't work:

```
if (ImGui::Button(u8"test"))
{
ImGui::GetIO().KeysDown[VK_RETURN] = true;
ImGui::GetIO().KeysDown[VK_RETURN] = false;
}
```

**Comment by Bunny-B** [comment]
ImGui help you drawing ui 
i dont think imgui have any way to simulate a click .
maybe look on that 
https://learn.microsoft.com/fr-fr/windows/win32/api/winuser/nf-winuser-keybd_event

**Comment by aabilityuk** [comment]
> ImGui help you drawing ui
> i dont think imgui have any way to simulate a click .
> maybe look on that
> https://learn.microsoft.com/fr-fr/windows/win32/api/winuser/nf-winuser-keybd_event

Thank you for reply! I gave keyb_event a try, but it doesn't work for me, button click event is not triggered

**Comment by ocornut** [comment]
You can queue an imgui keypress exactly the same way a backend would queue one,

io.AddKeyEvent(ImGuiKey_Enter, true);
io.AddKeyEvent(ImGuiKey_Enter, false);

Note that this will be only be perceived by imgui and code using imgui inputs. If you want to inject a key event at a lower level you may want to send a win32 event but this is outside the scope of this project and place.
