### ISSUE TITLE
Keep window on top

### ISSUE THREAD

**Issue by emoon** [ocornut/imgui#717]
As outlined in this issue https://github.com/emoon/ProDBG/issues/183

"Right now different views' z-indexes are controlled by Imgui. When view is clicked, it floats up. If viewdock's (background) view is clicked, it could cover floating window completely. Since background views cannot be moved, floating windows will be buried forever. Is there a way to say Imgui "This view should always be higher then these views"? Or something like this to prevent "burying" floating windows"

Is this possible?

**Comment by ocornut** [comment]
Right now there's no way to explicitly control all of the ordering yet. 
However in your situation, if your background/docked windows don't overlap, you can use the `ImGuiWindowFlags_NoBringToFrontOnFocus` flag on them and it may solve your problem?

**Comment by emoon** [comment]
That might work. Thanks!

**Comment by emoon** [comment]
Closing this for now.
