### ISSUE TITLE
Problem with positioning controls under a ImGui::SameLine() control

### ISSUE THREAD

**Issue by HeitorBarella** [ocornut/imgui#7170]
**Version/Branch of Dear ImGui:**

Version: 1.78 WIP (17703)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_dx9.cpp + imgui_impl_win32.cpp
Compiler: XXX _(if the question is related to building or platform specific features)_
Operating System: Windows11

**My Issue/Question:**

I don't know how to explain my issue, but I will try my best. Basically, I'm copying windows 98 login window in Dear ImGui using [JakeCoxon's win98 style](https://github.com/JakeCoxon/imgui-win98). I was creating the controls once I found an issue with positioning which I can fix by using a really bad method but it would break the padding and make the overall code inconsistent ( ImGui::SetCursorPosY(NEGATIVE_VALUE) ). Bascially, I have a text at the top of the window, and by using ImGui::SameLine(); I add a button to the right of that text, and right under the text I tried adding an input (for username) BUT the Y position respects the button Y position not the text Y position even thought the X position of the input is right under the text X position not the button X position. Like I said I don't know how to explain but it is probably clear what I mean in the video.

    

**Screenshots/Video**

https://github.com/ocornut/imgui/assets/141191921/46f0cd6e-6563-4c9e-864c-2d5759bb2e33

---

Code responsible for the window Text, Button and InputText:
```cpp
ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, { 25.f, 10.f });
{
    ImGui::SetCursorPosX(90);
    ImGui::Text("Type an user name and password to log on to Windows.");
    ImGui::SameLine();
    ImGui::BeginGroup();
    {
        ImGui::Button("OK", { 75, 25 });
        ImGui::Button("Cancel", { 75, 25 });
    }
    ImGui::EndGroup();
    ImGui::BeginGroup();
    {
        ImGui::SetCursorPosX(90);
        ImGui::Text("User name:");
        ImGui::SameLine();
        ImGui::SetNextItemWidth(135);
        ImGui::SetCursorPosY(ImGui::GetCursorPosY() - 3.f); // Ignore (used for centering text to the input)
        ImGui::InputText("##Username", &username);
    }
    ImGui::EndGroup();
}
```

**Comment by HeitorBarella** [comment]
I also tried without BeingGroup() But it still didn't work, since I don't know what this issue is I don't know what to search for, sorry if it is blatant at the Dear ImGui Demo code or somewhere in the github issues

**Comment by Bunny-B** [comment]
remove the sameline()

ImGui::Text("Type an user name and password to log on to Windows.");
    ImGui::SameLine(); //Remove this line else it will put your groups at the left of your text
    ImGui::BeginGroup();

**Comment by HeitorBarella** [comment]
> remove the sameline()
> 
> ImGui::Text("Type an user name and password to log on to Windows."); ImGui::SameLine(); //Remove this line else it will put your groups at the left of your text ImGui::BeginGroup();

Is there a way to not remove SameLine? Because it puts the Buttons at the right of the text as intended, otherwise I will need to manually set the button X position, but thanks I will try it out right now

**Comment by HeitorBarella** [comment]
![image](https://github.com/ocornut/imgui/assets/141191921/bebd4bc2-efea-46b2-b3d8-d71ae335e16e)

Welp, the issue is definitely not with `SameLine()`; As the `InputText` still respects the Button region, not the text region. I want the `InputText` to respect the Text position, not the buttons position.

Without buttons (correct):
![image](https://github.com/ocornut/imgui/assets/141191921/0957ef1e-ea48-45cc-9161-9849a7e8d3f3)

With buttons (incorrect):
![image](https://github.com/ocornut/imgui/assets/141191921/b3e7064e-8eae-47e5-9b21-7d0475323a39)

**Comment by HeitorBarella** [comment]
Sorry, issue fixed. I grouped the text with the inputs and everything worked as plannned!
![image](https://github.com/ocornut/imgui/assets/141191921/d5c5ddf5-343d-4eb8-a644-6cefa9c044d7)

```cpp
ImGui::BeginGroup();
{
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, { 25.f, 30.f });
    ImGui::Text("Type an user name and password to log on to Windows.");
    ImGui::PopStyleVar();
    ImGui::BeginGroup();
    {
        
        ImGui::Text("User name:");
        ImGui::SameLine();
        ImGui::SetNextItemWidth(135);
        ImGui::InputText("##Username", &username);
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, { 28.f, NULL }); // Fixing X padding issue due to Password being smaller than User name
        {
            ImGui::Text("Password:");
            ImGui::SameLine();
            ImGui::SetNextItemWidth(135);
            ImGui::InputText("##Password", &password, ImGuiInputTextFlags_Password);
        }
        ImGui::PopStyleVar();
    }
    ImGui::EndGroup();

}
ImGui::EndGroup();
ImGui::SameLine();
ImGui::BeginGroup();
{
    ImGui::Button("OK", { 75, 25 });
    ImGui::Button("Cancel", { 75, 25 });
}
ImGui::EndGroup();
```
