### ISSUE TITLE
How to adapt 4k resolution?

### ISSUE THREAD

**Issue by ChivenZhang** [ocornut/imgui#7173]
**Version/Branch of Dear ImGui:**

Version: 1.89
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_SDL2.cpp + imgui_impl_GL3.cpp
Compiler: msvc 2019
Operating System: windows 10

**My Issue/Question:**

I developed an application for company using imgui on 3d rendering. Before I released it I found there was few problem about resolution adapting for large screen, like 4k screen. This problem caused the control widget overlapping the text. Please help me, thanks.
(Note: I apply the fixed size for widget on small resolution screen. )

**Screenshots/Video**

![image](https://github.com/ocornut/imgui/assets/48938612/bc427fb5-68bd-42db-82b7-fd61cd3609e9)

**Comment by ocornut** [comment]
There are five millions issues and FAQ entries discussing this and you are not putting the smallest effort explaining what your code does. No patience for this, sorry.
