### ISSUE TITLE
DX11 Image process memory 

### ISSUE THREAD

**Issue by jackdiddilysquad** [ocornut/imgui#7179]
Hello, i am using the latest dx11 imgui example and i have discovered a unsuspected error, 
i am getting extremely high process memory when loading a image, i have looked over the "Image-Loading-and-Displaying-Examples" index in the imgui wiki and i have copped everything from the dx11 example, i am also not using any vsync.

i will provide the code below:

```
int my_image_width = 100;
int my_image_height = 260;
ID3D11ShaderResourceView* my_texture = NULL;
bool ret = LoadTextureFromFile("C:\\photo.png", &my_texture, &my_image_width, &my_image_height);
IM_ASSERT(ret);

 if (previewobject) {
    ImGui::SetCursorPosX(61);
    ImGui::Image((void*)my_texture, ImVec2(my_image_width, my_image_height));
 }
            
bool LoadTextureFromFile(const char* filename, ID3D11ShaderResourceView** out_srv, int* out_width, int* out_height)
{
    // Load from disk into a raw RGBA buffer
    int image_width = 0;
    int image_height = 0;
    unsigned char* image_data = stbi_load(filename, &image_width, &image_height, NULL, 4);
    if (image_data == NULL)
        return false;

    // Create texture
    D3D11_TEXTURE2D_DESC desc;
    ZeroMemory(&desc, sizeof(desc));
    desc.Width = image_width;
    desc.Height = image_height;
    desc.MipLevels = 1;
    desc.ArraySize = 1;
    desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage = D3D11_USAGE_DEFAULT;
    desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    desc.CPUAccessFlags = 0;

    ID3D11Texture2D* pTexture = NULL;
    D3D11_SUBRESOURCE_DATA subResource;
    subResource.pSysMem = image_data;
    subResource.SysMemPitch = desc.Width * 4;
    subResource.SysMemSlicePitch = 0;
    g_pd3dDevice->CreateTexture2D(&desc, &subResource, &pTexture);

    // Create texture view
    D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc;
    ZeroMemory(&srvDesc, sizeof(srvDesc));
    srvDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
    srvDesc.Texture2D.MipLevels = desc.MipLevels;
    srvDesc.Texture2D.MostDetailedMip = 0;
    g_pd3dDevice->CreateShaderResourceView(pTexture, &srvDesc, out_srv);
    pTexture->Release();

    *out_width = image_width;
    *out_height = image_height;
    stbi_image_free(image_data);

    return true;
}
```

i also tried jpg instead of png and i tried swapping photos but nothing has changed.
any help would be appricated

**Comment by ocornut** [comment]
Your code is ambiguous and you are not providing complete enough information, but it suggests that you are loading the file every frame and never clearing anything. You should generally load assets only once.

**Comment by jackdiddilysquad** [comment]
> Your code is ambiguous and you are not providing complete enough information, but it suggests that you are loading the file every frame and never clearing anything. You should generally load assets only once.

All i did was copy the code presented for dx11 in your image loading and displaying examples, is there somewhere where that presents examples for loading assets and clearing them, i have taken a look around but i have not found anything.
thanks

**Comment by ocornut** [comment]
The wiki page clearly spells it out:

"At initialization time, load our texture:"

then

"Now that we have an DirectX11 texture and its dimensions, we can display it in our main loop:"

If you are loading the texture every iteration of the main loop it is going to be slow and consume lots of memory. You should load once, display every frame.

Also again you are NOT providing us unambiguous code of what you actually did, just code snippets without the calling context, so I am only making a guess here. If you want to receive help you get to share the actual information about what you are doing.
