### ISSUE TITLE
Mac OSX imgui.ini seems not be loaded

### ISSUE THREAD

**Issue by Lecrapouille** [ocornut/imgui#7183]
**Version/Branch of Dear ImGui:**

Version: HEAD of Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: any i guess
Operating System: Mac OS X

**My Issue/Question:**

With Mac OSX it seems the imgui.ini file is not loaded and all widgets are messed when the application is started. I have no issue with Linux and Emscripten.

I tried to set:
```
    ImGuiIO &io = ImGui::GetIO();
    io.IniFilename = "/my/full/path/imgui.ini"
```
before NewFrame() but that changed nothing.

My application is compiled both as bundle application (.app folder) and without bundle: both cases are the same. I have access to Mac just for a couple a day and I'm not a mac dev, so maybe I missed something. I guess there is some logs to activate showing if the imgui.ini file is found and parsed ?

**Comment by PathogenDavid** [comment]
> I guess there is some logs to activate showing if the imgui.ini file is found and parsed ?

There are no such logs. Your best bet is to put a breakpoint in [`ImGui::LoadIniSettingsFromDisk`](https://github.com/ocornut/imgui/blob/240ab5890b2e8da294937a1710b021ac3f271472/imgui.cpp#L13222) and step through to see where things go wrong.

**Comment by Lecrapouille** [comment]
@PathogenDavid thank you ! I understood now. Not an issue. The dear file is correctly loaded and one of my issue comes from I did not give a static string to io.IniFilename (I returned a std::string::c_str() from a method that in addition was erroneous).
