### ISSUE TITLE
Drawing custom shapes (was: improving Custom Title Bar)

### ISSUE THREAD

**Issue by luis605** [ocornut/imgui#7185]
dear imgui, v1.89.2
Branch: docking

**Back-end/Renderer/Compiler/OS**
Back-ends: rlImGui
Operating System: Linux Mint 21.1 Vera

**My Question:**
 I made a custom title bar for my game engine using dear imgui. At the moment, the title bar is too basic. So, I want to add more detail to it. I believe I can add more detail to it using dear imgui, but I don't know how. I came here with a possible design in mind, and I'd like to know how I implement it.

**Screenshots**
Original Title Bar:
![Screenshot at 2024-01-01 14-18-11](https://github.com/ocornut/imgui/assets/60551627/5bbf3a9c-4179-47f0-a0d2-c15bb986dc67)

Photoshoped Title Bar:
![image](https://github.com/ocornut/imgui/assets/60551627/6477afa2-5e0e-44a0-9685-c3acb66c5764)

**How did I implement my title bar:**
The code uses `BeginMainMenuBar()` to create the title bar. It draws Lit Engine's logo at the left of the title bar using `ImGui::Image()`. It also displays "Lit Engine" in the middle of the bar as well as other buttons and menus.

**Comment by ocornut** [comment]
It seems like your question is solely a drawing question.
You can use ImDrawList functions `PathLineTo()`, `PathArcTo()` to create a path, then `PathFillConvex()` to fill it. Note that it will only support convex shapes, so it is best is you create your shape in multiple convex parts. 

Concave shapes are more difficult to draw (a concave polygon triangular was posted https://github.com/ocornut/imgui/issues/760#issuecomment-1871741125)

**Comment by luis605** [comment]
It is working. Thank you!
