### ISSUE TITLE
Performance issue when using LunaSvg as a font loader (link to LunaSvg issue)

### ISSUE THREAD

**Issue by pthom** [ocornut/imgui#7187]
This ImGui issue is for information only, as it refers to [an issue](https://github.com/sammycage/lunasvg/issues/150) that was posted to the [lunasvg](https://github.com/sammycage/lunasvg) repository.

I saw some performance issues with ImGui when it uses LunaSvg (v2.3.9) in order to load some Svg fonts: we can load some fonts with a very good performance. However, with some others, the performance drops and it takes about 2 seconds per glyph to load. In order to facilitate the analysis I prepared a [repro repository](https://github.com/pthom/lunasvg_perf_issue).

**Comment by pthom** [comment]
Update: this is likely an issue inside Freetype. See [issue posted to Freetype](https://gitlab.freedesktop.org/freetype/freetype/-/issues/1265#note_2225386)

**Comment by pthom** [comment]
Updating since a lot happened on the LunaSvg Side: see https://github.com/sammycage/lunasvg/issues/150
Please refer to the issue on the LunaSvg repository for more details

**Comment by ocornut** [comment]
FYI, the ongoing work on `dynamic_fonts` branch toward 1.92 should make this problem largely obsolete as glyphs will be rasterized on demand: https://github.com/ocornut/imgui/issues/8465.
