### ISSUE TITLE
Demo binaries -> Trojan:Win21/NSISInject!pz

### ISSUE THREAD

**Issue by pluberd** [ocornut/imgui#7193]
The Defender thinks the demo is a trojan.

**Comment by ocornut** [comment]
I don't see this here. Perhaps it happens on your local machine because yours infects it?
Can you ZIP the files after extracting/trying to run them, and check their checksums?
![image](https://github.com/ocornut/imgui/assets/8225057/8c0feff6-dc85-4539-931b-60c4794396bc)

**Comment by ocornut** [comment]
Realized that I just assumed you were talking about precompiled demo binaries linked from README.

But if you are talking about binaries that you compiled yourself, I am afraid the culprit is 100% inside your computer (actual virus/trojan or faulty detection). Could you clarify?

**Comment by pluberd** [comment]
Hi, the precompiled binaries you can download at github.

**Comment by ocornut** [comment]
Thanks for confirming.
Can you do as asked by https://github.com/ocornut/imgui/issues/7193#issuecomment-1876828761 ?
(unzip, zip again, cheeck size+crc)

**Comment by pluberd** [comment]
I do an online check at the download url of the demo:

https://www.virustotal.com/gui/url/25a4afc7e8881a70421c9ca0e1526fa85cdff89d61cf57efa019b77970e6cb20

Only BitDefender find a malware:

![grafik](https://github.com/ocornut/imgui/assets/113139382/53ea5958-96a2-483b-81c5-780646f838eb)

I don't know why. Maybe a false positive.

**Comment by pluberd** [comment]
The reported file is: binary_to_compressed_c.exe

SHA256: B6EE1288925ABC884C6E585AB1B688D23453277705C7D0F4ECAF6F2E3E3CB904

**Comment by pluberd** [comment]
Online scanner for only the file: binary_to_compressed_c.exe

https://www.virustotal.com/gui/file/b6ee1288925abc884c6e585ab1b688d23453277705c7d0f4ecaf6f2e3e3cb904

![grafik](https://github.com/ocornut/imgui/assets/113139382/77726853-e408-4dbe-a030-6a05eb6fc560)

**Comment by ocornut** [comment]
Thanks for clarifying.

I have toyed with my binaries build scripts, and confirmed that building this tool VS15 in 32-bit more created an .exe locally reported by my Windows 10 Defender. Switching to VS19 (same command line) fixed it.

I updated binaries to recent version and it seems to be ok for me now:
https://www.dearimgui.com/binaries/imgui-demo-binaries-20240105.zip
