### ISSUE TITLE
ImGui Window Position based on Screen Coordinates

### ISSUE THREAD

**Issue by apxcoding** [ocornut/imgui#7196]
**Version/Branch of Dear ImGui:**

Version: 1.90
Branch: Docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_win32.h + imgui_impl_dx9.h
Compiler: C++ 17
Operating System: Windows 10

**My Issue/Question:**

Hello,

how do I get the Position of the ImGui Window based on the Coordinates that are calculated from the Screen and not the Window the ImGui window is rendering in?

**Comment by ocornut** [comment]
If multi-viewports are disabled, ImGui Window positions are relative to your Platform/OS window.
Dear ImGui doesn't know the position of your Platform/OS window. You'll get to get that yourself in a platform dependent manner (e.g. `::GetWindowPos()` in Win32 land) and add them up.

If multi-viewports are enabled, all windows coordinates are matching platform/ios coordinates.
