### ISSUE TITLE
Strange problem, the top of the two groups are not aligned

### ISSUE THREAD

**Issue by uusdnfdsfhnttyh** [ocornut/imgui#7198]
### Version/Branch of Dear ImGui:

Version 1.9, Branch: master

### Platform back-end:

imgui_impl_glfw.cpp

### Rendering back-end:

imgui_impl_opengl3.cpp

### Compiler:

MSVC 2022

### Operating System:

Windows 11

### Details:

Why is there no horizontal alignment at the top of the window?

### Minimal, Complete and Verifiable Example code:

code:
```cpp
    ImGui::BeginGroup();
    ImGui::BeginGroup();
    ImGui::Text("OOO:");
    static char buf22[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##test", buf22, 1);

    ImGui::Text("111:");
    static char buf11[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##111", buf11, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    ImGui::Text("333:");
    static char buf33[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##333", buf33, 1);
    ImGui::Text("444:");

    static char buf44[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##444", buf44, 1);
    ImGui::EndGroup();
```
Code in demo `"Layout/Groups"` result:
![image](https://github.com/ocornut/imgui/assets/142380608/55112fa0-87f9-468b-a78e-298d07e46909)

Code in my single window app:
![image](https://github.com/ocornut/imgui/assets/142380608/c0e13d55-11bc-4ab2-8555-52fc41c3921b)

default font and style.

```cpp
    ....
    ImGui::NewFrame();
    ImGuiViewport* viewport = ImGui::GetMainViewport();
    ImGui::SetNextWindowPos(viewport->Pos);
    ImGui::SetNextWindowSize(viewport->WorkSize);
    ....
    ImGui::Begin(...)
```

**Comment by uusdnfdsfhnttyh** [comment]
![image](https://github.com/ocornut/imgui/assets/142380608/c76e0609-e2a6-404b-aadd-e06f6091b060)
```cpp
    ImGui::BeginGroup();
    ImGui::Text("OOO:");
    static char buf22[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##test", buf22, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    ImGui::Text("111:");
    static char buf11[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##111", buf11, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    ImGui::Text("333:");
    static char buf33[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##333", buf33, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    ImGui::Text("444:");
    static char buf44[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##444", buf44, 1);
    ImGui::EndGroup();
```

**Comment by uusdnfdsfhnttyh** [comment]
```cpp
ImGui::BeginGroup();
    auto y = ImGui::GetCursorPosY();
    printf("y == %f \n", y);
    ImGui::Text("OOO:");
    static char buf22[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##test", buf22, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    printf("y == %f \n", y);
    ImGui::Text("111:");
    static char buf11[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##111", buf11, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    printf("y == %f \n", y);
    ImGui::Text("333:");
    static char buf33[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##333", buf33, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    printf("y == %f \n", y);
    ImGui::Text("444:");
    static char buf44[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##444", buf44, 1);
    ImGui::EndGroup();
    exit(1);
```
Output:
```
y == 6.000000
y == 6.000000
y == 6.000000
y == 6.000000
```

**Comment by uusdnfdsfhnttyh** [comment]
Update test:
```cpp
    ImGui::BeginGroup();
    auto y = ImGui::GetCursorPosY();
    printf("y == %f \n", y);
    ImGui::Text("OOO:");
    static char buf22[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##test", buf22, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    y = ImGui::GetCursorPosY();
    printf("y == %f \n", y);
    ImGui::Text("111:");
    static char buf11[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##111", buf11, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    y = ImGui::GetCursorPosY();
    printf("y == %f \n", y);
    ImGui::Text("333:");
    static char buf33[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##333", buf33, 1);
    ImGui::EndGroup();

    ImGui::SameLine();

    ImGui::BeginGroup();
    y = ImGui::GetCursorPosY();
    printf("y == %f \n", y);
    ImGui::Text("444:");
    static char buf44[1];
    ImGui::SetNextItemWidth(50.0f);
    ImGui::InputText("##444", buf44, 1);
    ImGui::EndGroup();
    exit(1);
```
Output:
```
y == 6.000000
y == 6.000000
y == 6.000000
y == 6.000000
```

**Comment by uusdnfdsfhnttyh** [comment]
Update:
I found the source of 6.0, which is `style.WindowPadding.y`.
The y value of the cursor of the first widget(ImGui::Text) at the beginning of the first group is 0.0f.
When the second group is created, the y value of the cursor is the value of `style.WindowPadding.y`, is this normal? @ocornut

**Comment by ocornut** [comment]
It's a tricky issue stemming from the fact that `Text()` and some other "thin" widget don't use FramePadding, and so we try maintain a "text baseline".

From demo:
![image](https://github.com/ocornut/imgui/assets/8225057/72e2c257-1603-4d99-a716-89f8a39f4722)

First line: Text, SameLine, Button (text misaligned because it doesn't know in advance that line will be taller)
Second line: AlignTextToFramePadding, Text, SameLine, Button
Third line: Button, Text, SmallButton (here the text is correctly vertically aligned)

Problems is that multiple groups on sameline can't reliably communicate text baseline, we don't have enough information for it, and the second BeginGroup() just notice that previous item is taller and assume it has a text baseline offset.

The workaround is to call `AlignTextToFramePadding()` before your first group, and then everything will be aligned.

However, in your specific example, you may also use a table, e.g. `BeginTable("##4ways", 4, ImGuiTableFlags_SizingFixedSame);` it will be more natural.

**Comment by uusdnfdsfhnttyh** [comment]
Thank you very much for your answers and help

> 这是一个棘手的问题，因为`Text()`其他一些“薄”小部件不使用 FramePadding，因此我们尝试维护“文本基线”。
> 
> 来自演示： ![图像](https://private-user-images.githubusercontent.com/8225057/294531637-72e2c257-1603-4d99-a716-89f8a39f4722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Njg4NzksIm5iZiI6MTcwNDQ2ODU3OSwicGF0aCI6Ii84MjI1MDU3LzI5NDUzMTYzNy03MmUyYzI1Ny0xNjAzLTRkOTktYTcxNi04OWY4YTM5ZjQ3MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTUyOTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc3YzU1NWRlZGQ0OGYyZTc1M2Y0ODA5ZTVkZTIyNjkwOWYwOWI0MWI2OGQ3ZjU2OTI5ODgxMzg3OWQ1Mzc4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jwkVKYxzTHIJbteSF2xuV8rZzmJlycJfNCV5vgs-XFk)
> 
> 第一行：Text、SameLine、Button（文本未对齐，因为它事先不知道该行会更高） 第二行：AlignTextToFramePadding、Text、SameLine、Button 第三行：Button、Text、SmallButton（此处文本正确垂直）对齐）
> 
> 问题是同一行上的多个组无法可靠地传达文本基线，我们没有足够的信息，第二个 BeginGroup() 只是注意到前一项更高并假设它有文本基线偏移。
> 
> 解决方法是在第一组之前打电话`AlignTextToFramePadding()`，然后一切都会协调一致。
> 
> 但是，在您的具体示例中，您也可以使用表格，例如`BeginTable("##4ways", 4, ImGuiTableFlags_SizingFixedSame);`它会更自然。

Thank you very much for your answers and help

> It's a tricky issue stemming from the fact that `Text()` and some other "thin" widget don't use FramePadding, and so we try maintain a "text baseline".
> 
> From demo: ![image](https://private-user-images.githubusercontent.com/8225057/294531637-72e2c257-1603-4d99-a716-89f8a39f4722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjkwMjgsIm5iZiI6MTcwNDQ2ODcyOCwicGF0aCI6Ii84MjI1MDU3LzI5NDUzMTYzNy03MmUyYzI1Ny0xNjAzLTRkOTktYTcxNi04OWY4YTM5ZjQ3MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTUzMjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVlNmEzOTVmNzViNmI2YjUyNTMxNWM4MTFhNjE1NjM1NWMxYjY5NTM4Y2NkZWI5ZjA2MWJlNjFmNjMxMTY5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qkXDDqsDX9XxaBWVifwJBmM0Stdqch2JVL08W4Ciifc)
> 
> First line: Text, SameLine, Button (text misaligned because it doesn't know in advance that line will be taller) Second line: AlignTextToFramePadding, Text, SameLine, Button Third line: Button, Text, SmallButton (here the text is correctly vertically aligned)
> 
> Problems is that multiple groups on sameline can't reliably communicate text baseline, we don't have enough information for it, and the second BeginGroup() just notice that previous item is taller and assume it has a text baseline offset.
> 
> The workaround is to call `AlignTextToFramePadding()` before your first group, and then everything will be aligned.
> 
> However, in your specific example, you may also use a table, e.g. `BeginTable("##4ways", 4, ImGuiTableFlags_SizingFixedSame);` it will be more natural.

Thank you very much for your answers and help
