### ISSUE TITLE
Win32 + DX12 hook from present, initializing ImGui and on rendering a frame crashes my entire GPU.

### ISSUE THREAD

**Issue by TheBarii** [ocornut/imgui#7207]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: shadows

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx12.cpp

### Compiler, OS:

Win11 + MSVC 2022

### Full config/build information:

Release build

### Details:

**My Issue/Question:**

I am on an AMD Radeon 6700 xt GPU, with 23.12.1 drivers (even tried PRO Edition drivers).
as the title suggests, it crashes my gpu with the error message "Something caused a driver timeout, would you like to report this issue?" 
But, on other PCs with Nvidia or Intel dGPUs or iGPUs, they don't crash, even other AMD iGPUs. If I rollback my drivers to Microsoft Display Drivers, no crashes occur, but of course everything is like 10 fps.

I'm hooking into Minecraft: Bedrock Edition to render a simple square.

I have found that NOT doing this fixes the issue:

		    if (ImGuiDX12::frameContext->mainRenderTargetResource)
		    	ImGuiDX12::frameContext->mainRenderTargetResource->Release();
		    	
		    if (ImGuiDX12::allocator)
		    	ImGuiDX12::allocator->Release();    
		    	
		    	
but if i don't do this, obviously, a memory leak occurs. Do note, even if its the currentFrameContext, it crashes me. It might be hard to understand from such small amount of code on what im doing, but if this gets a response, ill make my project public so that you can see.

This is really annoying and i can't work on my project at all lol, im gonna need some kind of solution

I will gladly provide any other information required to help you debug this,

### Minimal, Complete and Verifiable Example code:

nevermind, i can include code here. Wait.

PresentHooks.cpp:

#include "PresentHooks.hpp"

#include "../../../Flarial/Event/EventManager.hpp"
#include "../../../GUI/Renderer.hpp"
#include "../../../GUI/ScreenData.hpp"

bool killed = true;
bool Init = false;
bool once = false;

namespace {
    // Present Hook
    typedef void(__thiscall* PresentOriginal)(IDXGISwapChain3* ppSwapChain, UINT syncInterval, UINT flags);
    inline PresentOriginal oPresent = nullptr;

	void PresentCallback(IDXGISwapChain3* ppSwapChain, UINT syncInterval, UINT flags) {
		static auto window = FindWindow(nullptr, xorstr("Minecraft"));

		auto onRndr = [&] {
			ScreenData::uiSize = Vec2(D2D::context->GetSize().width, D2D::context->GetSize().height);
			const RenderEvent event(D2D::context);
			eventMgr.onRender(event);

            PositionComponent p(50, 50);
            SizeComponent s(50, 50);
            ColorComponent c("FFFFFF");
            Renderer::drawRoundedRect(PositionComponent(0.1, 0.1), SizeComponent(0.1, 0.1), ColorComponent(255, 255, 255, 255), 0);
		};

		if (DX11on12::d3d11Device == nullptr && DX11on12::d3d12Device == nullptr) {
			if (FAILED(ppSwapChain->GetDevice(IID_PPV_ARGS(&DX11on12::d3d11Device))) && FAILED(ppSwapChain->GetDevice(IID_PPV_ARGS(&DX11on12::d3d12Device))))
				return oPresent(ppSwapChain, syncInterval, flags);
		}

		if (DX11on12::d3d11Device) {
			if (!Init) {
				ImGui::CreateContext();

				constexpr D2D1_CREATION_PROPERTIES properties {
						D2D1_THREADING_MODE_MULTI_THREADED,
						D2D1_DEBUG_LEVEL_NONE,
						D2D1_DEVICE_CONTEXT_OPTIONS_ENABLE_MULTITHREADED_OPTIMIZATIONS
				};

				IDXGISurface1* eBackBuffer;
				ppSwapChain->GetBuffer(0, IID_PPV_ARGS(&eBackBuffer));

				D2D1CreateDeviceContext(eBackBuffer, properties, &D2D::context);

				D2D1_BITMAP_PROPERTIES1 props = D2D1::BitmapProperties1(D2D1_BITMAP_OPTIONS_TARGET | D2D1_BITMAP_OPTIONS_CANNOT_DRAW,
				    D2D1::PixelFormat(DXGI_FORMAT_UNKNOWN, D2D1_ALPHA_MODE_PREMULTIPLIED), 96.0, 96.0);
				D2D::context->CreateBitmapFromDxgiSurface(eBackBuffer, props, &DX11on12::d2d1Bitmap);

				if (eBackBuffer)
					eBackBuffer->Release();

				RECT desktop;
				auto hDesktop = GetDesktopWindow();
				GetWindowRect(hDesktop, &desktop);

				ScreenData::screenSize = Vec2(static_cast<float>(desktop.right), static_cast<float>(desktop.bottom));

				Init = true;
			}

			ID3D11RenderTargetView* mainRenderTargetView = nullptr;
			ID3D11DeviceContext* ppContext = nullptr;
			ID3D11Texture2D* pBackBuffer = nullptr;

			DX11on12::d3d11Device->GetImmediateContext(&ppContext);

			if (ppContext) {
				if (SUCCEEDED(ppSwapChain->GetBuffer(0, __uuidof(ID3D11Texture2D), reinterpret_cast<LPVOID*>(&pBackBuffer)))) {
					if (SUCCEEDED(DX11on12::d3d11Device->CreateRenderTargetView(pBackBuffer, nullptr, &mainRenderTargetView))) {
						ImGui_ImplWin32_Init(window);
						ImGui_ImplDX11_Init(DX11on12::d3d11Device, ppContext);

						ImGui_ImplDX11_NewFrame();
						ImGui_ImplWin32_NewFrame();
						ImGui::NewFrame();
						D2D::context->BeginDraw();

						onRndr();

						D2D::context->EndDraw();
						ImGui::EndFrame();
						ImGui::Render();

						ppContext->OMSetRenderTargets(1, &mainRenderTargetView, nullptr);
						ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
					}
				}
			}

			if (pBackBuffer)
				pBackBuffer->Release();

			if (mainRenderTargetView)
				mainRenderTargetView->Release();
		}
		else if (DX11on12::d3d12Device) {
		    if (!DX11on12::queue)
		    	return oPresent(ppSwapChain, syncInterval, flags);

		    if (!Init)
		    	ImGui::CreateContext();

		    DXGI_SWAP_CHAIN_DESC sdesc;
		    ppSwapChain->GetDesc(&sdesc);
		    sdesc.Flags = DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH;
		    sdesc.OutputWindow = window;
		    sdesc.Windowed = (GetWindowLongPtr(window, GWL_STYLE) & WS_POPUP) == 0;

		    ImGuiDX12::buffersCounts = sdesc.BufferCount;
		    ImGuiDX12::frameContext = new FrameContext[ImGuiDX12::buffersCounts];

		    D3D12_DESCRIPTOR_HEAP_DESC descriptorImGuiRender = {};
		    descriptorImGuiRender.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
		    descriptorImGuiRender.NumDescriptors = ImGuiDX12::buffersCounts;
		    descriptorImGuiRender.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;

		    if (ImGuiDX12::d3d12DescriptorHeapImGuiRender || SUCCEEDED(DX11on12::d3d12Device->CreateDescriptorHeap(&descriptorImGuiRender,
		        IID_PPV_ARGS(&ImGuiDX12::d3d12DescriptorHeapImGuiRender)))) {
		    	if (SUCCEEDED(DX11on12::d3d12Device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT, IID_PPV_ARGS(&ImGuiDX12::allocator)))) {
		    		for (size_t i = 0; i < ImGuiDX12::buffersCounts; i++) {
		    			ImGuiDX12::frameContext[i].commandAllocator = ImGuiDX12::allocator;
		    		}

		    		if (SUCCEEDED(DX11on12::d3d12Device->CreateCommandList(0, D3D12_COMMAND_LIST_TYPE_DIRECT,
		    		    ImGuiDX12::allocator, nullptr, IID_PPV_ARGS(&ImGuiDX12::d3d12CommandList)))) {
		    			D3D12_DESCRIPTOR_HEAP_DESC descriptorBackBuffers;
		    			descriptorBackBuffers.Type = D3D12_DESCRIPTOR_HEAP_TYPE_RTV;
		    			descriptorBackBuffers.NumDescriptors = ImGuiDX12::buffersCounts;
		    			descriptorBackBuffers.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_NONE;
		    			descriptorBackBuffers.NodeMask = 1;

		    			if (SUCCEEDED(DX11on12::d3d12Device->CreateDescriptorHeap(&descriptorBackBuffers, IID_PPV_ARGS(&ImGuiDX12::d3d12DescriptorHeapBackBuffers)))) {
		    				const auto rtvDescriptorSize = DX11on12::d3d12Device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV);
		    				D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle = ImGuiDX12::d3d12DescriptorHeapBackBuffers->GetCPUDescriptorHandleForHeapStart();

		    				for (size_t i = 0; i < ImGuiDX12::buffersCounts; i++) {
		    					ID3D12Resource* pBackBuffer = nullptr;

		    					ImGuiDX12::frameContext[i].mainRenderTargetDescriptor = rtvHandle;
		    					ppSwapChain->GetBuffer(i, IID_PPV_ARGS(&pBackBuffer));
		    					DX11on12::d3d12Device->CreateRenderTargetView(pBackBuffer, nullptr, rtvHandle);
		    					ImGuiDX12::frameContext[i].mainRenderTargetResource = pBackBuffer;
		    					rtvHandle.ptr += rtvDescriptorSize;

		    					pBackBuffer->Release();
		    				}

		    				if (!Init) {
		    					ImGui_ImplWin32_Init(window);
		    					ImGui_ImplDX12_Init(DX11on12::d3d12Device, static_cast<int>(ImGuiDX12::buffersCounts),
		    						DXGI_FORMAT_R8G8B8A8_UNORM, ImGuiDX12::d3d12DescriptorHeapImGuiRender,
		    						ImGuiDX12::d3d12DescriptorHeapImGuiRender->GetCPUDescriptorHandleForHeapStart(),
		    						ImGuiDX12::d3d12DescriptorHeapImGuiRender->GetGPUDescriptorHandleForHeapStart());

		    					ID3D12Device5* device;

		    					if (SUCCEEDED(ppSwapChain->GetDevice(IID_PPV_ARGS(&device))) &&
		    						kiero::getRenderType() == kiero::RenderType::D3D12) {
		    						ID3D11Device* d3d11device;
		    						D3D11On12CreateDevice(device,
		    							D3D11_CREATE_DEVICE_BGRA_SUPPORT, nullptr, 0,
		    							reinterpret_cast<IUnknown**>(&DX11on12::queue), 1, 0, &d3d11device, &DX11on12::context,
		    							nullptr);

		    						d3d11device->QueryInterface(IID_PPV_ARGS(&DX11on12::d3d11On12Device));

		    						D2D1_DEVICE_CONTEXT_OPTIONS deviceOptions = D2D1_DEVICE_CONTEXT_OPTIONS_ENABLE_MULTITHREADED_OPTIMIZATIONS;
		    						ID2D1Factory7* d2dFactory;
		    						D2D1_FACTORY_OPTIONS factoryOptions{};
		    						D2D1CreateFactory(D2D1_FACTORY_TYPE_MULTI_THREADED, __uuidof(ID2D1Factory7), &factoryOptions,
		    							reinterpret_cast<void**>(&d2dFactory));

		    						IDXGIDevice* dxgiDevice;
		    						DX11on12::d3d11On12Device->QueryInterface(__uuidof(IDXGIDevice), reinterpret_cast<void**>(&dxgiDevice));

		    						ID2D1Device6* device2;
		    						d2dFactory->CreateDevice(dxgiDevice, &device2);

		    						device2->CreateDeviceContext(deviceOptions, &D2D::context);

		    						DXGI_SWAP_CHAIN_DESC1 swapChainDescription;
		    						ppSwapChain->GetDesc1(&swapChainDescription);

		    						DX11on12::bufferCount = swapChainDescription.BufferCount;

		    						DX11on12::dxgiSurfaces.resize(DX11on12::bufferCount, nullptr);
		    						DX11on12::d3d11Resources.resize(DX11on12::bufferCount, nullptr);
		    						DX11on12::d2d1Bitmaps.resize(DX11on12::bufferCount, nullptr);

		    						auto dpi = static_cast<float>(GetDpiForSystem());

		    						D2D1_BITMAP_PROPERTIES1 props = D2D1::BitmapProperties1(
		    							D2D1_BITMAP_OPTIONS_TARGET | D2D1_BITMAP_OPTIONS_CANNOT_DRAW,
		    							D2D1::PixelFormat(DXGI_FORMAT_UNKNOWN, D2D1_ALPHA_MODE_PREMULTIPLIED), dpi, dpi);

		    						D3D12_DESCRIPTOR_HEAP_DESC heapDescriptorBackBuffers = {};
		    						heapDescriptorBackBuffers.Type = D3D12_DESCRIPTOR_HEAP_TYPE_RTV;
		    						heapDescriptorBackBuffers.NumDescriptors = DX11on12::bufferCount;
		    						heapDescriptorBackBuffers.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_NONE;
		    						heapDescriptorBackBuffers.NodeMask = 1;

		    						device->CreateDescriptorHeap(&heapDescriptorBackBuffers,
		    							IID_PPV_ARGS(&DX11on12::d3d12DescriptorHeap));

		    						uintptr_t rtvDescriptorSize = device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_RTV);
		    						D3D12_CPU_DESCRIPTOR_HANDLE rtvHandle = DX11on12::d3d12DescriptorHeap->GetCPUDescriptorHandleForHeapStart();

		    						for (int i = 0; i < DX11on12::bufferCount; i++) {
		    							ID3D12Resource* backBufferPtr;
		    							ppSwapChain->GetBuffer(i, IID_PPV_ARGS(&backBufferPtr));
		    							device->CreateRenderTargetView(backBufferPtr, nullptr, rtvHandle);
		    							rtvHandle.ptr += rtvDescriptorSize;

		    							D3D11_RESOURCE_FLAGS d3d11_flags = { D3D11_BIND_RENDER_TARGET };

		    							DX11on12::d3d11On12Device->CreateWrappedResource(backBufferPtr, &d3d11_flags,
		    								D3D12_RESOURCE_STATE_RENDER_TARGET,
		    								D3D12_RESOURCE_STATE_PRESENT, IID_PPV_ARGS(
		    									&DX11on12::d3d11Resources[i]));
		    							DX11on12::d3d11Resources[i]->QueryInterface(&DX11on12::dxgiSurfaces[i]);

		    							DX11on12::d2d1Bitmaps[i] = nullptr;

		    							D2D::context->CreateBitmapFromDxgiSurface(DX11on12::dxgiSurfaces[i], props,
		    								&DX11on12::d2d1Bitmaps[i]);
		    							backBufferPtr->Release();
		    						}

		    						device->Release();
		    						device2->Release();
		    						d3d11device->Release();
		    						dxgiDevice->Release();
		    						d2dFactory->Release();
		    					}

								RECT desktop;
								auto hDesktop = GetDesktopWindow();
								GetWindowRect(hDesktop, &desktop);

								ScreenData::screenSize = Vec2(static_cast<float>(desktop.right), static_cast<float>(desktop.bottom));

		    					Init = true;
		    				}

							DX11on12::currentBitmap = static_cast<int>(ppSwapChain->GetCurrentBackBufferIndex());

							ID3D11Resource *resource = DX11on12::d3d11Resources[DX11on12::currentBitmap];
							DX11on12::d3d11On12Device->AcquireWrappedResources(&resource, 1);

							D2D::context->SetTarget(DX11on12::d2d1Bitmaps[DX11on12::currentBitmap]);
		    				ImGui_ImplDX12_NewFrame();
		    				ImGui_ImplWin32_NewFrame();
		    				ImGui::NewFrame();
							D2D::context->BeginDraw();

		    				onRndr();

							D2D::context->EndDraw();
							D2D::context->SetTarget(nullptr);
							DX11on12::d3d11On12Device->ReleaseWrappedResources(&resource, 1);

							DX11on12::context->Flush();
		    				FrameContext& currentFrameContext = ImGuiDX12::frameContext[ppSwapChain->GetCurrentBackBufferIndex()];
		    				currentFrameContext.commandAllocator->Reset();

		    				D3D12_RESOURCE_BARRIER barrier;
		    				barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
		    				barrier.Flags = D3D12_RESOURCE_BARRIER_FLAG_NONE;
		    				barrier.Transition.pResource = currentFrameContext.mainRenderTargetResource;
		    				barrier.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
		    				barrier.Transition.StateBefore = D3D12_RESOURCE_STATE_PRESENT;
		    				barrier.Transition.StateAfter = D3D12_RESOURCE_STATE_RENDER_TARGET;

		    				ImGuiDX12::d3d12CommandList->Reset(currentFrameContext.commandAllocator, nullptr);
		    				ImGuiDX12::d3d12CommandList->ResourceBarrier(1, &barrier);
		    				ImGuiDX12::d3d12CommandList->OMSetRenderTargets(1,
		    				    &currentFrameContext.mainRenderTargetDescriptor, FALSE, nullptr);
		    				ImGuiDX12::d3d12CommandList->SetDescriptorHeaps(1, &ImGuiDX12::d3d12DescriptorHeapImGuiRender);

		    				ImGui::EndFrame();
		    				ImGui::Render();

		    				ImGui_ImplDX12_RenderDrawData(ImGui::GetDrawData(), ImGuiDX12::d3d12CommandList);

		    				barrier.Transition.StateBefore = D3D12_RESOURCE_STATE_RENDER_TARGET;
		    				barrier.Transition.StateAfter = D3D12_RESOURCE_STATE_PRESENT;

		    				ImGuiDX12::d3d12CommandList->ResourceBarrier(1, &barrier);
		    				ImGuiDX12::d3d12CommandList->Close();

		    				DX11on12::queue->ExecuteCommandLists(1, reinterpret_cast<ID3D12CommandList* const*>(&ImGuiDX12::d3d12CommandList));

		    			}
		    		}
		    	}
		    }

		    if (ImGuiDX12::d3d12CommandList)
		    	ImGuiDX12::d3d12CommandList->Release();

		    if (ImGuiDX12::d3d12DescriptorHeapBackBuffers)
		    	ImGuiDX12::d3d12DescriptorHeapBackBuffers->Release();

		    delete ImGuiDX12::frameContext;
		}

	    return oPresent(ppSwapChain, syncInterval, flags);
    }

    // CommandList Hook
	typedef void(__thiscall* commando)(ID3D12CommandQueue* queue, UINT numCommandLists, const ID3D12CommandList** ppCommandLists);
	commando oList = nullptr;

	void listCallback(ID3D12CommandQueue* queue, UINT numCommandLists, const ID3D12CommandList** ppCommandLists) {
		if (!once) {
			DX11on12::queue = queue;
			once = true;
		}

		return oList(queue, numCommandLists, ppCommandLists);
	}

    // Resize Hook
	typedef void(__thiscall* ResizeOriginal)(IDXGISwapChain* pSwapChain, UINT bufferCount, UINT width, UINT height, DXGI_FORMAT newFormat, UINT flags);
    inline ResizeOriginal oResize = nullptr;

	void ResizeCallback(IDXGISwapChain* pSwapChain, UINT bufferCount, UINT width, UINT height, DXGI_FORMAT newFormat, UINT flags) {
		Init = false;
		oResize(pSwapChain, bufferCount, width, height, newFormat, flags);
	}
}

void PresentHooks::initPresentHooks() {
    int present;
	int commandList = 0;
	int resize;

    if (init(kiero::RenderType::D3D12) == kiero::Status::Success) {
        present = 140;
		commandList = 54;
		resize = 145;
    }
    else if (init(kiero::RenderType::D3D11) == kiero::Status::Success) {
        present = 8;
		resize = 13;
    }

	if (commandList)
		kiero::bind(commandList, reinterpret_cast<void**>(&oList), &listCallback);

    kiero::bind(present, reinterpret_cast<void**>(&oPresent), &PresentCallback);
	kiero::bind(resize, reinterpret_cast<void**>(&oResize), &ResizeCallback);
}

PresentHooks.hpp:

#pragma once

class PresentHooks {
public:
    static void initPresentHooks();
};

class DX11on12 {
public:
    static inline ID3D11Device* d3d11Device;
    static inline ID3D12Device5* d3d12Device;
    static inline ID3D12CommandQueue* queue;
    static inline std::vector<IDXGISurface1*> dxgiSurfaces;
    static inline std::vector<ID2D1Bitmap1*> d2d1Bitmaps;
    static inline std::vector<ID3D11Resource*> d3d11Resources;
    static inline IDXGISwapChain3* swapchain;
    static inline ID3D12DescriptorHeap* d3d12DescriptorHeap;
    static inline ID3D11On12Device* d3d11On12Device;
    static inline ID2D1Bitmap1* d2d1Bitmap;
    static inline ID3D11DeviceContext* context;
    static inline uintptr_t bufferCount;
    static bool hasResized;
    static inline int currentBitmap;
    static inline UINT flagsreal;
};

struct FrameContext {
	ID3D12CommandAllocator* commandAllocator;
	ID3D12Resource* mainRenderTargetResource;
	D3D12_CPU_DESCRIPTOR_HANDLE mainRenderTargetDescriptor;
};

class ImGuiDX12 {
public:
    static inline ID3D12DescriptorHeap* d3d12DescriptorHeapImGuiRender;
    static inline ID3D12DescriptorHeap* d3d12DescriptorHeapBackBuffers;
    static inline ID3D12GraphicsCommandList* d3d12CommandList;
    static inline ID3D12CommandQueue* d3d12CommandQueue;
    static inline ID3D12CommandAllocator* allocator;

    static inline uint64_t buffersCounts;
    static inline FrameContext* frameContext;
};

**Comment by emoon** [comment]
https://github.com/ocornut/imgui/issues/1586

**Comment by ocornut** [comment]
This is outside of our support scope. Little of this has anything to do with dear imgui itself, it’s more of a dx12 question. Closing this.

**Comment by TheBarii** [comment]
> This is outside of our support scope. Little of this has anything to do with dear imgui itself, it’s more of a dx12 question. Closing this.

Can you at least link me to a place that can help me?
