### ISSUE TITLE
Animate on open everytime

### ISSUE THREAD

**Issue by RequiDev** [ocornut/imgui#721]
Hello.

When the start size of an window is 0, 0 and AlwaysAutoResize is set it will animate the opening kind of. Is there a way to do that on every reopening of the window? Right now it only does it when opening it the first time, but having it all the time would be great.

Thanks in advance,
Requi

**Comment by ocornut** [comment]
Its not expected to animate and probably a size calculation bug based on the way the window is being populated. Could you investigate and provide repro code so that i can look info it?

**Comment by RequiDev** [comment]
I just set the starting size of ImGui::Begin to 0, 0 and put the flag ImGuiFlags_AlwaysAutoResize. That will cause the Gui to kind of animate to the size it's going to be.

Or what exactly do you need?

**Comment by ocornut** [comment]
Whats actually in the window.

The "size it is going to be" vary depending on that and some functions or default settings may lead to a size>contents>size feedback loop when the AlwaysAutoResize flag is set.

**Comment by RequiDev** [comment]
http://pastebin.com/raw/mbWmGJJx Here's the full menu code. Maybe you can tell by that what I mean.

**Comment by ocornut** [comment]
Could you strip it until you get the issue with the minimum amount of code with little dependencies?
Thanks!
