### ISSUE TITLE
Outdated link in README

### ISSUE THREAD

**Issue by sanjeetsuhag** [ocornut/imgui#7211]
### Version/Branch of Dear ImGui:

master

### Back-ends:

n/a

### Compiler, OS:

n/a

### Full config/build information:

n/a

### Details:

**My Issue/Question:**

The link to `ProggyClean.ttf` in the main README leads to a potentially inappropriate site. I believe the domain may have renewed and it is now utilized by some scammy dating website thing. It should be updated. I have attached a screenshot of the website.

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/5172619/52620069-eb28-442b-924b-1397bdcfbdda)

**Comment by ocornut** [comment]
Thank you! Should be fixed with f1ae47c4b9eea0fefe96af00585ebdf6dac0ec16
