### ISSUE TITLE
Closing TreeNode/CollapsingHeader

### ISSUE THREAD

**Issue by mitjakukovec** [ocornut/imgui#722]
Is there a way to collapse (close) a TreeNode / CollapsingHeader programmatically? I have a usage case where I would like to close a tree node from the software which would behave like that if the user has closed it with a click of the mouse.

**Comment by ocornut** [comment]
Have you looked in imgui.h around the location where TreeNode and CollapsingHeader are defined?

![capture](https://cloud.githubusercontent.com/assets/8225057/16513087/00c3da0a-3f62-11e6-8b13-e7ea8d59a7f5.PNG)

**Comment by mitjakukovec** [comment]
I have no idea how I missed that one and feel a little bit embarrassed right now. :-) I will try it out and see how it works for me. Thank you very much!

**Comment by ocornut** [comment]
No problem :) sorry I am a little rough with my answers sometimes, reducing overhead when possible.
