### ISSUE TITLE
Viewport can't receive evnts when viewport is partially outside of the window

### ISSUE THREAD

**Issue by lyzirving** [ocornut/imgui#7221]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: docking

### Back-ends:

imgui_impl_opegl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Windows 10 Visual Studio 2022

### Details:

**My Issue:I enable multiple viewport. When Viewport is partially or totally outside of the window, the viewport can not receive input events**

If i start dragging and release the move when viewport is partially outside of the window, the viewport can no longer receive events.
I have uploaded a video to show this.

### Screenshots/Video:

https://github.com/ocornut/imgui/assets/31678071/39a02451-09c9-4a79-b6be-001c10ef2e03

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
```

**Comment by lyzirving** [comment]
i have searched google for a long time, and still have no idead.
i also doubted whether there is some thing wrong in my code, but i have checked my code with imgui demo for times, still have no ideas.

**Comment by ocornut** [comment]
Does the glfw+opengl3 example code works on your system?

**Comment by lyzirving** [comment]
> Does the glfw+opengl3 example code works on your system?

The demo alone can run correctly on my system.
Is there something wrong in my code ?

**Comment by ocornut** [comment]
> The demo alone can run correctly on my system.

Then check the difference between our example code and your code.

> Is there something wrong in my code ?

Yes. You have answered this question yourself above already.

We cannot help you as you are not providing your code. We cannot magically guess what's wrong in your code if you don't provide it. You can freely compare your code to ours to find your mistake, our example code is < 200 lines.

**Comment by lyzirving** [comment]
> > The demo alone can run correctly on my system.
> 
> Then check the difference between our example code and your code.
> 
> > Is there something wrong in my code ?
> 
> Yes. You have answered this question yourself above already.
> 
> We cannot help you as you are not providing your code. We cannot magically guess what's wrong in your code if you don't provide it. You can freely compare your code to ours to find your mistake, our example code is < 200 lines.

Here is my code:
https://github.com/lyzirving/Pionner/blob/main/engine/src/Application.cpp
https://github.com/lyzirving/Pionner/blob/main/engine/src/platform/opengl/GLRenderAPI.cpp

i am sorry i make it complicated, but i have already compared my code and demo, and could not find out the error.
Application::run() described the main loop.
GLRenderAPI::initImGui(), beginFrame(), endFrame() described how i use imgui. ImGui is created and used in a render thread which is different from the main loop.

i am really gratefull if you can check my code.

**Comment by ocornut** [comment]
I am sorry we cannot be debugging your code, it's presently large and complicated and you stated the raw example works, so you'll need to do research yourself. You can probably start by verifying is your threading system is not causing the issue.
You may also use Dear ImGui Debug Log -> IO to visualize the IO events submitted to dear imgui.
