### ISSUE TITLE
How to set individual elements and tables to have no spacing directly

### ISSUE THREAD

**Issue by SnowMeteors** [ocornut/imgui#7222]
### Version/Branch of Dear ImGui:

Version 1.90.1 WIP, Branch:docking

### Back-ends:

imgui_impl_dx12.cpp + imgui_impl_win32.cpp

### Compiler, OS:

windows10 + vs2019

### Details:

**My Issue/Question:**

I have reviewed the examples and found that ImGuiStyleVar_ CellPadding, spacing can be set, but individual elements cannot be set with cellpadding

### Screenshots/Video:

运行后
![image](https://github.com/ocornut/imgui/assets/47601098/4edb1579-6b7c-43bb-882c-0d1ee7ee24f7)
You can see that the InputText element has spacing, and I want it to fill the entire space

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::Begin("begin");
if (ImGui::BeginTable("hostTable", 2, ImGuiTableFlags_NoHostExtendY | ImGuiTableFlags_ScrollX | ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_ScrollY | ImGuiTableFlags_Resizable))
{
  ImGui::TableSetupColumn("test", ImGuiTableColumnFlags_WidthFixed, 100);
  ImGui::TableSetupColumn("test2", ImGuiTableColumnFlags_WidthFixed, 100);
  
  ImGui::TableNextRow();
  
  ImGui::TableNextColumn();
  ImGui::Text("this is text");
  
  static ImVec2 cell_padding(0.0f, 0.0f);
  static std::string text;
  
  ImGui::PushStyleVar(ImGuiStyleVar_CellPadding, cell_padding);
  // Provide a good background color for debugging and viewing
  ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(0.2f, 0.2f, 0.2f, 1.0f));
  ImGui::TableNextColumn();
  ImGui::SetNextItemWidth(-FLT_MIN);
  
  // only set InputText item no padding (Fill the entire space)
  ImGui::InputText("##HostRemark", &text);
  
  ImGui::PopStyleColor();
  ImGui::PopStyleVar();
  
  ImGui::EndTable();
}
ImGui::End();
```

**Comment by ocornut** [comment]
> I have reviewed the examples and found that ImGuiStyleVar_ CellPadding, spacing can be set, but individual elements cannot be set with cellpadding

CellPadding.x is locked in `BeginTable()` and cannot be changed afterwards. Before fitting/sizing options are dependent on that.
CellPadding.y is locked in TableNextRow() so if you want to change it for a row you need to change it before `TableNextRow()`.

You can use `TableSetBgColor()` to alter the color of a cell bg, may be a good alternative.

**Comment by SnowMeteors** [comment]
> > I have reviewed the examples and found that ImGuiStyleVar_ CellPadding, spacing can be set, but individual elements cannot be set with cellpadding
> 
> CellPadding.x is locked in `BeginTable()` and cannot be changed afterwards. Before fitting/sizing options are dependent on that. CellPadding.y is locked in TableNextRow() so if you want to change it for a row you need to change it before `TableNextRow()`.
> 
> You can use `TableSetBgColor()` to alter the color of a cell bg, may be a good alternative.

I'm not changing a certain row, I want to change the ImGui:: InputText ("# # HostRemark",&text) of a certain column; How should I set it to fill the space of the entire cell

**Comment by ocornut** [comment]
I answered your question.
Please read answer carefully again.

CellPadding.y can only be changed for a row.

Changing cell bg color and inputtext bg color can give you same effect as you want.
