### ISSUE TITLE
DX9 stops drawing on Resize/Minimize

### ISSUE THREAD

**Issue by nyaruku** [ocornut/imgui#7227]
### Version/Branch of Dear ImGui:

dear imgui, v1.89.9

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx9.cpp

### Compiler, OS:

MSVC 2022

### Details:

I have this code inside if (g_pd3dDevice->BeginScene() >= 0)
Where I want to draw the audo data that I got with the help of the BASS library,
but the window stops re-drawing when i try to resize or minimize...
(everything else is unmodified: imgui dx9 example code was used)

### Code:

`if (g_pd3dDevice->BeginScene() >= 0)
{
	ImGui::Render();

	// Define the number of lines

	// Create an array to hold the start and end points of each line
	D3DXVECTOR2 dblines[numLines * 2];
	D3DXVECTOR2 hzlines[numLines * 2];
	for (int i = 0; i <= numLines; i++) {
		//db
		dblines[i * 2] = D3DXVECTOR2(float((i + 1)) / float((float(numLines) / float((1280 * 1)))), ((viewport->WorkSize.y - 2) + (30 / log10f((fft[i + 1]))))); // Line end
		dblines[i * 2 + 1] = D3DXVECTOR2(float((i + 1)) / float((float(numLines) / float((1280 * 1)))), viewport->WorkSize.y - 2); // Line start
		//magnitude
		hzlines[i * 2] = D3DXVECTOR2(float((i + 1)) / float((float(numLines) / float((1280 * 1)))), ((viewport->WorkSize.y - 2) - (fft[i + 1]) * 1000)); // Line end
		hzlines[i * 2 + 1] = D3DXVECTOR2(float((i + 1)) / float((float(numLines) / float((1280 * 1)))), viewport->WorkSize.y - 2); // Line start
	}

	// Now you can draw the lines using the array

	dxLine->SetAntialias(false);
	dxLine->SetWidth(1);

	dxLine->Begin();
	for (int i = 0; i < numLines; i++)
	{
		dxLine->Draw(&dblines[i * 2], 2, D3DCOLOR_ARGB(255, 255, 255, 255));
		dxLine->Draw(&hzlines[i * 2], 2, D3DCOLOR_ARGB(80, 0, 0, 255));
	}
	dxLine->End();

	ImGui_ImplDX9_RenderDrawData(ImGui::GetDrawData());
	g_pd3dDevice->EndScene();
}`

### Screenshots/Video:

How it looks like:
https://github.com/ocornut/imgui/assets/38096703/bcd98d7a-dc6c-4133-b3b9-ac73e617ecb0

**Comment by ocornut** [comment]
Hello,

I don't think the question or issue has anything to with Dear ImGui.
You can check our DX9 example to see how to handle reseting the DX9 device on resize.
