### ISSUE TITLE
In future version,whether  you can add the toolbar for imgui?

### ISSUE THREAD

**Issue by zhouxs1023** [ocornut/imgui#723]
Because the toolbar is very useful,whether  to consider add toolbar for imgui?

**Comment by ongamex** [comment]
Could you be a bit more specific?
There is already a Menu Bar, and if you want a Maya/3ds Max style toolbar you could easily create one with borderless windows and a bunch of Image buttons.

**Comment by zhouxs1023** [comment]
toolbar style as below:
![-5ed06af43a0c1bdf](https://cloud.githubusercontent.com/assets/905931/16539421/60d23436-4008-11e6-95b2-dc900ec882a7.jpg)

can you provide a simple code for me?

**Comment by ocornut** [comment]
There's no simple code, you have to dig into ImGui.
You can use ImGui::ImageButton() to create clickable icon, or implement your own.
An easy technique is to merge an icon TTF font such as FontAwesome

**Comment by ocornut** [comment]
There's no simple code, you have to dig into ImGui.
You can use ImGui::ImageButton() to create clickable icon, or implement your own.

An easier technique is to merge an icon TTF font such as FontAwesome ( http://fontawesome.io ) into your main font, and use those icons from within your text. You can find ready-made header files to access the code points here: https://github.com/juliettef/IconFontCppHeaders
So you never use images but just text and it becomes easier.

At that point your toolbar could almost be a regular menu (BeginMenu, MenuItem, SameLine, etc.).

**Comment by zhouxs1023** [comment]
Thks!

**Comment by zhouxs1023** [comment]
Thks!

**Comment by colesnicov** [comment]
hello zhouxs1023,

Check this [https://github.com/Flix01/imgui/tree/2015-10-Addons/addons/imguitoolbar](https://github.com/Flix01/imgui/tree/2015-10-Addons/addons/imguitoolbar)

**Comment by FOLOME** [comment]
link not work ?

**Comment by ocornut** [comment]
https://github.com/Flix01/imgui/tree/imgui_with_addons/addons/imguitoolbar

**Comment by FOLOME** [comment]
thanks :)
