### ISSUE TITLE
Making imgui full multi-context multi-thread capable out of the box

### ISSUE THREAD

**Issue by FunMiles** [ocornut/imgui#7234]
### Version/Branch of Dear ImGui:

1.90.1

### Back-ends:

Any

### Compiler, OS:

Any with atomics

### Details:

I believe almost modern systems, whether computers, game stations, mobile phones, tablet and even embedded MCU are multi-core system that can benefit from multi threading in all aspects of the applications, including data presentation and UI.
Isolation application components is also a good practice in modern development.

ImGui was started with a view of the world that is single threaded single context. IMHO, it is time ImGui offered a multi-threaded multi-context API out of the box.

@Dragnalith has done a great job of preparing the terrain for an out-of-the box multi-context ImGui (#5856). 
After adding support for glfw/vulkan to his work, it became clear that the missing piece is in dealing with multi-threading. The good news is that at least for a graphic API such as vulkan, which support multi-threading out of the box, the difficulty of thread safety is confined *almost exclusively* to the backend. Essentially the places where threads matter are:

1. Creating windows: some OSs require window creation/destruction be done on the main thread.
1. Dispatching events: the events are likely to be dealt with call-backs on the main thread. They need to be safely dispatched  to the threads doing the rendering.

For Vulkan at least, these are the only two things I've seen that need to be dealt with.
Point 1 can -and should- be dealt with by the user. It does not really involve ImGui. The user can easily create a window and retrieve whatever state is necessary for rendering on the main thread and pass it to the rendering thread.
The second point is the point I want to address in this issue and in a PR that will come from it.

Why we are so close: ImGui already creates a queue of events in its context. If the incoming events from the main thread can safely be fed to that queue, each thread/context can work independently of each other.

The stumbling blocks: the queue of events is a ImGui specific equivalent of `std::vector`. It is not thread safe. ImGui has a guiding principle of not using any library and that includes the standard library. As many of us know, it is not possible to make a thread-safe design without proper lock/sync mechanisms (e.g. mutex or atomics). These do require using a system-provided library.

A possible solution: a way of keeping any locking/synchronization mechanism from within ImGui's core would be to put such mechanism in the backend and have ImGui pull the data from a backend-provided source. To do so would require one or two pointers to be added to the `ImGuiContext`. If the pointers are `nullptr`, ImGui works as it does now, if not, instead of pulling events from `InputEventsQueue`, it pull them from the backend via a fixed API.

I will be working on making a PR to effect the above proposed solution and am happy to listen to suggestions or constructive criticism.

**Comment by ocornut** [comment]
(cc #5856)

> My motivation is that modern development does require multi-threading. With it comes also the need for better encapsulation/isolation of entities, components, objects, whatever your favorite term of the day is. I also abhor global variables 
like many programmers. 😄 You may thus understand my interest in this change.

You are not saying anything concrete here, sorry. If anything, it comforts me in the understanding you don't need what you claim you want.

> One of my application is in scientific visualization. Right now, I can only view one model at a time. I have to close that visualization to be able to add another one. I do not want the creation of the visualization objects to be done on the main thread via some form of time slice on the main thread. It's not practical nor desirable.

But this has nothing to do with what you are discussing. The bulk of that time is not the `ImGui::Image()` nor any of the ImGui functions calls, it's the computation and rendering of your model. An hypothetically multi-threaded ImGui won't help you. You can compute your models however you like in your highly threaded application, and have the single ImGui thread render last finished result and associated tooling. ImGui is not your bottleneck here.

> When I do a google search with imgui multiple context or imgui multi-threading I find enough results to know my use is not esoteric. [...]  I want to make ImGui thread safe. [...]

Multiple-contexts is indeed desirable for some uses, I'm not denying it. A typical AAA engine may want to use ImGui in domains running in parallel, and #5856 would allow getting rid of the TLS variable (BUT ALL OF IT IS ALREADY DOABLE WITH A TLS VARIABLE, it'll just be nicer and slightly faster without). We can also certainly improve that use-case by providing helpers to facilitate the video and inputs compositing of multiple-contexts on a same screen.

But appending to a same context from multiple-threads is pragmatically not at reach at all in the current design, I'm not sure there is way to make that possible at all. (AFAIK no UI toolkit is multi-threaded in the sense of multiple threads interacting/submitting to a same UI context in meaningfully more efficient way).

I am closing this and I am afraid absolutely don't have the energy to waste time discussing this further. 
I know you mean well and it would be nicer if I spent the time explaining this further, but unlike #5856 this is just a time-wasting topic.

**Comment by ocornut** [comment]
I must apologies again if seems like a rude answer, but this is an attention-economy. Dear ImGui only decently makes progress when I have time to focus on the right thing, and this seems like wacky and largely under-thought proposal to a problem that you don't actually have. Reading:

> "Right now, I can only view one model at a time. I have to close that visualization to be able to add another one. I do not want the creation of the visualization objects to be done on the main thread via some form of time slice on the main thread. It's not practical nor desirable."

It is clear you have multitude more solutions to your problem than going "single-context in multiple-threads".
It's also very unlikely you need "multi-contexts each in its contexts", but this you as you have missing is to use a custom backend or tweak/fix backends, but this is a much simpler and narrower scope that your vague proposal here.

To protect Dear ImGui I need to protect my time from this kind of time-sink.
