### ISSUE TITLE
Apparent contradiction in documentation

### ISSUE THREAD

**Issue by bradrn** [ocornut/imgui#7239]
### Version/Branch of Dear ImGui:

Version 1.90.0, Branch: docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Linux + GCC

### Details:

The comments for `ImGuiInputTextCallbackData` claim that the `Buf` field should never be replaced:

https://github.com/ocornut/imgui/blob/cab7edd135fb8a02b3552e9abe4c312d595e8777/imgui.h#L2363

However, `misc/cpp/imgui_stdlib` appears to do precisely that:

https://github.com/ocornut/imgui/blob/cab7edd135fb8a02b3552e9abe4c312d595e8777/misc/cpp/imgui_stdlib.cpp#L36

So it seems to me that either the documentation must be wrong, or the code is…

**Comment by ocornut** [comment]
> The comments for ImGuiInputTextCallbackData claim that the Buf field should never be replaced:

it says “[Resize] Can replace pointer”

**Comment by bradrn** [comment]
> it says “[Resize] Can replace pointer”

Ah, so it does! I feel a little stupid for not noticing that, but I can see how the comments are formatted now.

**Comment by ocornut** [comment]
No worries. I think the compact structure seems to work nicely if I reread it now?

**Comment by bradrn** [comment]
Yep, the compact structure works well *if* you’re aware that it’s there. Perhaps it’s worth explicitly describing the structure somewhere… but I’m not sure that it is.
