### ISSUE TITLE
ARGB color Edit4

### ISSUE THREAD

**Issue by Barashuk** [ocornut/imgui#724]
How can I change the color in the RGB palette when using colorEdit4? I try convert ARGB to RGBA, but it not helped. 
code http://pastebin.com/RVwTzLqX
Video https://www.youtube.com/watch?v=Dyr3dlOAuTs

**Comment by ocornut** [comment]
I don't understand your question. Your code looks alright, but you should only convert/apply back when the ColorEdit function returns true.

**Comment by ocornut** [comment]
Closing this as per lack of answer and not being actually a directly ImGui related question.
