### ISSUE TITLE
WebGPU pipeline is hardcoded to not use multisampling

### ISSUE THREAD

**Issue by radgeRayden** [ocornut/imgui#7240]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: docking_inter (through cimgui)

### Back-ends:

imgui_impl_wgpu.cpp + imgui_impl_sdl2.cpp

### Compiler, OS:

Linux + GCC 13

### Details:

As per https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_wgpu.cpp#L569 the pipeline object has a non configurable multisample count of 1. This means the main renderpass cannot be reused if MSAA is enabled. It's not a big inconvenience but I figured it could be desirable to have this be an init parameter or something.

**Comment by ocornut** [comment]
What do you suggest would be a good solution?
Let the user pass a `WGPUMultisampleState` structure?

Perhaps we could rework WebGPU backend interface to take a struct, similar to Vulkan one.

**Comment by radgeRayden** [comment]
> What do you suggest would be a good solution? Let the user pass a `WGPUMultisampleState` structure?
> 
> Perhaps we could rework WebGPU backend interface to take a struct, similar to Vulkan one.

From a quick assessment it seems like there's not much more missing to make the internal pipeline consistent with the render pass. The depth buffer format is already passed as a parameter, so as long as it has the sample count such that it is compatible with the color and depth attachments, it should be fine. Currently what I have to do is create a dedicated render pass for it and not use a depth attachment at all for that pass.

**Comment by ocornut** [comment]
Reworked API with 831d42c and added PipelineMultisampleState with 5fc0a36
Thanks!
