### ISSUE TITLE
ImGui::InputText - Passing in first argument as empty string ("") makes the text box constantly lose focus

### ISSUE THREAD

**Issue by dontna** [ocornut/imgui#7246]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Arch Linux + G++

### Details:

If you pass in an empty string into the first argument of **ImGui::InputText** whenever it gets rendered it will unfocus, and you cannot type anything.

`ImGui::InputText("", coolTextField, sizeof(coolTextField);`

Everything compiles completely fine, you only see the issue once you run the compiled binary.

It can be an annoyance if you don't want any text to display next to the box, my hacky workaround was to pass in a "\t" like so:

`ImGui::InputText("\t", coolTextField, sizeof(coolTextField));`

Apologies in advance if I did something wrong, or this has been posted. I did look but I couldn't find anything myself.

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("InputText Bug: Empty label unfocus");
char coolTextField[32];
ImGui::InputText("", coolTextField, sizeof(coolTextField));
ImGui::End();
```

**Comment by ocornut** [comment]
This is an invalid ID.
You can use "###anything" as an ID.

This is answered in the first "Usage" section of the FAQ, with 5 items listed in bold in the index:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-widgets-with-an-empty-label

**Comment by ocornut** [comment]
In addition, and this is VERY IMPORTANT.
We DO detect this case and assert against it.
If I try to run your code I get this message:

![image](https://github.com/ocornut/imgui/assets/8225057/cb0d303e-743f-4a41-af2a-2b489343c5bf)

That you didn't get the message means your asserts are not working or disabled. It is going to be really problematic using Dear ImGui if you don't have asserts enabled.

**Comment by dontna** [comment]
Ahh I'm sorry for that, I completely missed it in the FAQ; that's my bad.

Also you're also correct, I checked and my assert's were disabled.

I messed up, my apologies; I'll be more careful next time!

Thank you for your response anyway!
