### ISSUE TITLE
Strict-aliasing violation in FormatTextureIDForDebugDisplay()

### ISSUE THREAD

**Issue by d235j** [ocornut/imgui#7256]
### Version/Branch of Dear ImGui:

Version around Jan 6 2024, no modifications

### Back-ends:

n/a

### Compiler, OS:

gcc 13.2.1 20230801 on Arch Linux x86_64

### Full config/build information:

n/a (build warning)

### Details:

The following warnings are produced:
```
/sources_ssd/scopehal-apps/src/imgui/imgui.cpp: In function ‘void FormatTextureIDForDebugDisplay(char*, int, ImTextureID)’:                 
/sources_ssd/scopehal-apps/src/imgui/imgui.cpp:20263:55: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]                            
20263 |         ImFormatString(buf, buf_size, "0x%p", (void*)*(intptr_t*)(void*)&tex_id);                                                                                           
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~                                                                                             
/sources_ssd/scopehal-apps/src/imgui/imgui.cpp:20265:50: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]                            
20265 |         ImFormatString(buf, buf_size, "0x%04X", *(int*)(void*)&tex_id);                                                                                                     
      |                                                  ^~~~~~~~~~~~~~~~~~~~
```

**Comment by ocornut** [comment]
Thank you David, I think this should now be fixed by 81e0be8.
I added `-fstrict-aliasing` to some of my building/test scripts too.

**Comment by d235j** [comment]
Note that using unions for type-punning is valid C but not valid C++ (though GNU compilers avoid undefined behavior here). In C++ you have a few options, the easiest being std::bit_cast but this is only introduced in C++20.
I suspect this would only be an issue on odd compilers (which is unfortunately common in gamedev) or with newer optimizations. I’m not sure if there’s a warning that would flag this.

More information:
https://tttapa.github.io/Pages/Programming/Cpp/Practices/type-punning.html
https://stbuehler.de/blog/article/2014/05/25/type_punning_with_unions.html

**Comment by ocornut** [comment]
We are using both unions and memcpy here, so I'm not sure but only skimmed through articles. 
Thanks for reference! I guess we'll leave this simmering and see if anyone has any problem.
