### ISSUE TITLE
ASCII ImGUI

### ISSUE THREAD

**Issue by Barashuk** [ocornut/imgui#726]
Will the ASCII support for ImGUI? I can render ASCII text, but for this i convertering ASCII to UTF8 text

**Comment by ratchetfreak** [comment]
Here's a little secret, utf8 is mostly compatible with ascii. That is to say that if you only use alphanumeric characters plus a some punctuation there will be no difference between the utf8 and ascii.

**Comment by ocornut** [comment]
Barashuk,

I am not really sure what you are asking for here. UTF-8 is a superset of ASCII already.
What exactly are you trying to do that doesn't work with imgui?

Omar
