### ISSUE TITLE
Widgets Not Dynamically Squashing and Stretching While Resizing Single Window Application

### ISSUE THREAD

**Issue by jewade20** [ocornut/imgui#7261]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: docking

### Back-ends:

imgui_impl_dx9.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 10 + MSVS22

### Details:

Hello, I'm wondering if it is possible to have the widgets/items in my Imgui window dynamically squash and stretch while I am resizing the entire application window by dragging the bottom corner, as seen in the attached gif? I am making a single-window app (one ImGui window that resizes to the viewport) using Windows 10 and DX9.

The demo app window handles squashing and stretching beautifully, for example, but only when scaling that window from within the application and not while scaling the entire application itself. The various widgets in the ImGui window will not budge while you are dragging to resize the entire application window, such as in File Explorer, Docker, or Visual Studio.

This happens with all of the projects I have made so far in ImGui, and in the example gif I added the following code to make the window full screen:

    ImGuiViewport* viewport = ImGui::GetMainViewport();
    ImGui::SetNextWindowPos(viewport->Pos);
    ImGui::SetNextWindowSize(viewport->Size);

I'm new to gui programming and have only written scripts for a few years in my career, so this is my first dive into anything graphical. Any advice or info would be appreciated! 

### Screenshots/Video:

![ImGuiScaleDragging02](https://github.com/ocornut/imgui/assets/126632912/63e69753-e141-4a3a-8288-f580987d878c)

### Minimal, Complete and Verifiable Example code:

This is what you see in the gif and is essentially the "Hello, World!" demo window with the first 3 lines of code added to set the window size to that of the viewport each frame:    

        ImGuiViewport* viewport = ImGui::GetMainViewport();
        ImGui::SetNextWindowPos(viewport->Pos);
        ImGui::SetNextWindowSize(viewport->Size);

        {
            static float f = 0.0f;
            static int counter = 0;

            ImGui::Begin("Hello, world!", nullptr, ImGuiWindowFlags_NoResize);                          // Create a window called "Hello, world!" and append into it.

            ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)

            ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f
            ImGui::ColorEdit3("clear color", (float*)&clear_color); // Edit 3 floats representing a color

            if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)
                counter++;
            ImGui::SameLine();
            ImGui::Text("counter = %d", counter);

            ImGui::End();
        }

**Comment by seanmiddleditch** [comment]
See https://github.com/ocornut/imgui/issues/3672

**Comment by ocornut** [comment]
Added more information about this at https://github.com/ocornut/imgui/issues/3672#issuecomment-1907878355
