### ISSUE TITLE
ImGuiConfigFlags_NavEnableKeyboard - Auto clicking selected item.

### ISSUE THREAD

**Issue by Woitek1993** [ocornut/imgui#7268]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Visual Studio 2017

### Details:

Is there any way to enable auto-clicking selected item when navigating using arrows? I would love to achieve the same effect with it as with the mouse button click and ImGui::IsItemClicked function.

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Is this for Selectables?
Please fill issue template entirely and read guidelines to explain your problem in more details.
