### ISSUE TITLE
i need help in pixelshader using

### ISSUE THREAD

**Issue by MichaelConors** [ocornut/imgui#7269]
### Version/Branch of Dear ImGui:

Version 1.82.2

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

Windows 10 + msvc 2022

### Details:

Im new to pixelshaders, im trying to make a simple pixel shader ( for example, shader that returns color )
here is the code of the pixel shader:
```
float4 main(float4 color : COLOR) : SV_TARGET
{   
    return color;
}
```

here is how i initialize my image and shader:

```
D3DX11CreateShaderResourceViewFromFile( g_pd3dDevice, std::filesystem::path( std::filesystem::current_path( ) / "GUI" / "resources" / "avatar.png" ).c_str( ), NULL, NULL, &avatar, NULL );

g_pd3dDevice->CreatePixelShader( reinterpret_cast< const DWORD* >( shaderd ), sizeof( shaderd ), NULL, &shader );
```

now, how im trying to use this:
```
void begin( const ImDrawList* drawList, const ImDrawCmd* cmd ) {
    g_pd3dDeviceContext->PSSetShaderResources( 0, 1, &avatar );
    g_pd3dDeviceContext->PSSetShader( shader, 0, 0 );
}

void end( const ImDrawList* drawList, const ImDrawCmd* cmd ) {
    g_pd3dDeviceContext->PSSetShader( nullptr, 0, 0 );
}
```

```
ImGui::GetForegroundDrawList( )->AddCallback( begin, 0 );
ImGui::GetForegroundDrawList( )->AddImage( avatar, { 450, 250 }, { 500, 300 } );
ImGui::GetForegroundDrawList( )->AddCallback( end, 0 );
ImGui::GetForegroundDrawList( )->AddImage( avatar, { 450, 250 }, { 500, 300 } );
```

and nothing works, my picture is black. but my image is okay.
didnt manage to found info in the internet, sorry if my question is stupid

**Comment by wyxather** [comment]
try using sample eg:
`
Texture2D TEX : register(t0);
sampler TEX_SAMPLER : register(s0);
struct PS_INPUT
{
    float4 pos : SV_POSITION;
    float4 col : COLOR0;
    float2 uv : TEXCOORD0;
};
float4 main(PS_INPUT input) : SV_TARGET
{
    float4 color = TEX.Sample(TEX_SAMPLER, input.uv);
    return input.col;
}
`

**Comment by GamingMinds-DanielC** [comment]
While your own shader doesn't sample any textures, it should at least have produced white output instead of black, so maybe it doesn't initialize correctly. Depends very much on how you defined `shared`. If you haven't done so already, you should enable the debug layer for your device. Also, RenderDoc is always a great tool to analyze rendering problems.

**Comment by ocornut** [comment]
I think the got the ImGui side elements perfectly right, so the problem must have to do with your DX11 shader syntax.
Enable debug layer and check all return values.

**Comment by ocornut** [comment]
Closing as answered, feel free to post details if you end up finding your issue.
