### ISSUE TITLE
Bug with the ID for ImageButton

### ISSUE THREAD

**Issue by VadimBoev** [ocornut/imgui#7270]
### Version/Branch of Dear ImGui:

Version ImGui v1.89.5 (release)

### Back-ends:

custom engine

### Compiler, OS:

Windows 10, VS 2022, CLang for compile Android library

### Full config/build information:

![Screenshot_2024-01-28-23-36-09-284_com dropclub game](https://github.com/ocornut/imgui/assets/33985574/0b4d5517-8813-441b-8dde-71e98af08c3d)
![Screenshot_2024-01-28-23-36-02-068_com dropclub game](https://github.com/ocornut/imgui/assets/33985574/e98de577-1944-4704-b40a-e1ac2f2a4f3b)

### Details:

**When two ImageButton (in turn), the second button does not respond to click:**

Hello. I ran into the problem that when I use two buttons with image, the second one does not click, and accordingly (if you look at the example) the message was not displayed. I was finding a solution from this topic (https://github.com/ocornut/imgui/issues/2464), but before that I thought that it should automatically generate an ID inside itself, as ImGui::Button does.   
I understand that the generation of the ID in ImGui::Button depends on the 'label' and specifying the ID and so on. However, could it have been done differently for ImageButton to solve the problem? And how reliable is the use of ImGui::PushID(11) in this case, will there be any failures or bugs?

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce my issue
ImGui::Begin("ImageButton ID Bug");
if (ImGui::ImageButton(arrow, ImVec2(110, 110)))
{
    Log("button up clicked");
}

if (ImGui::ImageButton(arrow, ImVec2(110, 110), ImVec2(1,1), ImVec2(0,0)))
{
    Log("button down clicked");
}
ImGui::End();

// This solution helped me fix the problem:
ImGui::Begin("ImageButton ID Maybe fix");
if (ImGui::ImageButton(arrow, ImVec2(110, 110)))
{
    Log("button up clicked");
}

ImGui::PushID(11);
if (ImGui::ImageButton(arrow, ImVec2(110, 110), ImVec2(1,1), ImVec2(0,0)))
{
    Log("button down clicked");
}
ImGui::PopID();

ImGui::End();

```

**Comment by ocornut** [comment]
You are using the obsolete function signature for ImageButton(), which uses the texture id as a unique identifier.
Use the ImageButton() call that takes an explicit identifier.

**Comment by VadimBoev** [comment]
Thank you very much!
