### ISSUE TITLE
Build Font Async

### ISSUE THREAD

**Issue by control0forver** [ocornut/imgui#7271]
### Version/Branch of Dear ImGui:

Version v1.90.0

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

WIndows 10 + MSVC

### Full config/build information:

```
Dear ImGui 1.90.0 (19000)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: IMGUI_DISABLE_OBSOLETE_KEYIO
define: _WIN32
define: _WIN64
define: _MSC_VER=1938
define: _MSVC_LANG=202004
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 2 fonts, Flags: 0x00000000, TexSize: 4096,8192
io.DisplaySize: 1366.00,768.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 0.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 5.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**
I tried to load font with GlyphRangesChineseFull, but it will take long time (about 6-10 seconds) at game frame presenting

I loaded font using this call:
```
ImGui::GetIO().Fonts->AddFontxxx
```

but imgui did't build font yet, until I call this:
```
ImGui_ImplDX11_NewFrame
```

I traced it to **ImFontBuilderIO::FontBuilder_Build** function:
```
ImGui_ImplDX11_NewFrame->
    ImGui_ImplDX11_CreateDeviceObjects->
        ImGui_ImplDX11_CreateFontsTexture->
            ImFontAtlas::GetTexDataAsRGBA32->
                ImFontAtlas::GetTexDataAsAlpha8->
                    ImFontAtlas::Build->
                        ImFontBuilderIO->
                            ImFontBuilderIO::FontBuilder_Build
```

I tried to using std::thread or std::async with lambda expressions to solve it like this but failed with some error
```
#include <thread>
static std::thread thBuildFont = std::thread([&]{ BuildFont(); });
```

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/80107206/1b7360b6-2f03-46cd-ad65-d22d0660a581)
![image](https://github.com/ocornut/imgui/assets/80107206/3d565624-2dc9-47f3-bc7a-5d4dc1ceb48c)
![image](https://github.com/ocornut/imgui/assets/80107206/70457117-f17b-44f3-b1f8-42a2938d1301)

### Minimal, Complete and Verifiable Example code:

```
// Load font
        fonts["NotoSans_Bold_18"] = ImGui::GetIO().Fonts->AddFontFromMemoryCompressedTTF(
            notosanssc_bold_ttf_compressed_data, notosanssc_bold_ttf_compressed_size, 18.f, NULL, io.Fonts->GetGlyphRangesChineseFull());
```

**Comment by ocornut** [comment]
Running in a thread doesn't make sense if the other thread needs the font data. I don't think there is a good straightforward solution: our model with prebuilding glyphs is flawed and problematic but we should fix it this year. 

Until now, you can:
- make sure you build dear imgui in optimized mode.
- use imgui_freetype (also released/optimized mode)
- use a custom glyph range and feed in the characters you need https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#using-custom-glyph-ranges

**Comment by ocornut** [comment]
Closing as answered.

**Comment by Nanokoli** [comment]
you can load ImFontAtlas async,ImFont is base on it,when you finish ImFontAtlas's load(Texture UpLoad To GPU device),you can set font anywhere
