### ISSUE TITLE
The width parameter of the inputfloat()'s input field

### ISSUE THREAD

**Issue by Champion-zzy** [ocornut/imgui#7275]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Windows 10

### Details:

Dear author, hello!
 I want to shorten the length of inputfloat(), and place the text of inputfloat() under the input field.
![1706691801059](https://github.com/ocornut/imgui/assets/103919590/7145bfad-382c-4602-af81-194e324f2a80)

### Minimal, Complete and Verifiable Example code:

if (ImGui::InputFloat("Ht/Rad", &param_, info.step, 0.0f, "%.2f"))

**Comment by GamingMinds-DanielC** [comment]
Use `ImGui::SetNextItemWidth()` before submitting the widget. Give the widget an "empty" label (must still be unique, see https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system for reference). You can submit anything you want below it as a separate item.
