### ISSUE TITLE
How to upload your image to ImGui

### ISSUE THREAD

**Issue by Kolhun** [ocornut/imgui#7276]
### Version/Branch of Dear ImGui:

Version 1.90

### Back-ends:

mgui_impl_demo.cpp

### Compiler, OS:

Windows 10 + DirectX 9

### Details:

Hello, dear ImGui, I could not solve the question about how to add my texture to the ImageButton project? I try as an option below, but it leads to an error :(. Tell me the alternative options. Thanks

### Minimal, Complete and Verifiable Example code:

```cpp
ImGuiIO& io = ImGui::GetIO();
ImTextureID myImageTexture = io.Fonts->AddFontFromFileTTF("img_copy.png",16.0f);

if(ImGui::ImageButton(myImageTexture, ImVec2(32, 32)))
{

}
```

**Comment by PathogenDavid** [comment]
See [the wiki page on loading images](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples).

Make sure you only load the image only once. If your code had worked you would've been loading your image every single frame.

**Comment by Kolhun** [comment]
> See [the wiki page on loading images](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples).
> 
> Make sure you only load the image only once. If your code had worked you would've been loading your image every single frame.

Yes, I am aware, this code is exceptional for an example
