### ISSUE TITLE
OpenGL ES as a backend instead of OpenGL 3

### ISSUE THREAD

**Issue by shrit** [ocornut/imgui#7277]
### Version/Branch of Dear ImGui:

master version pulled from github

### Back-ends:

opengl 3 - > openGL ES

### Compiler, OS:

g++

### Details:

Hi,

Does any one know if OpenGL ES would work as a backend instead of opengl 3? did anyone gave it a try ? if yes, do you know how we can link it or if we need to modify anything on imgui level i

Many thanks

**Comment by ocornut** [comment]
I don’t understand your question.
You can use the imgui_impl_opengl3 backend code with GL ES 2 / ES 3 / WebGL.

**Comment by shrit** [comment]
Perfect, thanks, I only need to link against the them in this case. :+1:
