### ISSUE TITLE
Colored TreeNode possible ?

### ISSUE THREAD

**Issue by JamesAMD** [ocornut/imgui#728]
Hello and thanks for the awesome library !

I've been experimenting with the features of `TreeNode`s, and I was wondering, if it is possible to use color for them.
The test window displayed by `ImGui::ShowTestWindow()` seemingly uses no color for `TreeNode`s,
and I see no overload for `ImGui::TreeNode` that takes something like `const ImVec4& col` as an argument, like `ImGui::TextColored` does.

Would love to be able to use this feature.

Thanks in advance !

**Comment by ocornut** [comment]
You can use PushStyleCol(ImGuiCol_Text, ...)/PopStyleCol() to alter the text color.

If you use this a lot maybe wrap it in a function.

**Comment by JamesAMD** [comment]
Thank you ! That cleared it up for me :)
