### ISSUE TITLE
PushClipRect Rounding

### ISSUE THREAD

**Issue by ueak** [ocornut/imgui#7288]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: Master

### Back-ends:

imgui_impl_GLFW.cpp + imgui_impl_OPENGL3.cpp + imgui_impl_win32.cpp

### Full config/build information:

I am creating small software which uses quite a lot of rounding in the interface. I noticed that when using PushClipRect you cannot have any kind of rounding pushed. This is quite cruicial for modern day UI's, so Is there any chance of having rounding functionality in PushClipRect, i could not find any other solution to push the rounding either.

If there is no functionality done already i would like to ask what would such a thing require. Thanks for advance

### Details:

Approach is to have PushClipRect take in account rounding.

**Comment by PathogenDavid** [comment]
Dear ImGui uses the GPU's scissor clipping which only supports rectangles. Rounding is not supported, adding it would be non-trivial.

Improving this is not planned. (See https://github.com/ocornut/imgui/issues/6030#issuecomment-1369108041)

There's ways to perform more complex clipping on the GPU, but help doing so is outside the scope of the what we can realistically provide here.

**Comment by ocornut** [comment]
Thank you David for answering.
That’s all correct.
If you use rounding try to not display contents near that area, so it is preferable to adjust outer padding to match rounding.
