### ISSUE TITLE
How do I draw the content over the filled rect?

### ISSUE THREAD

**Issue by Vaneeyo** [ocornut/imgui#7291]
### Version/Branch of Dear ImGui:

I use this version: https://github.com/adamhlt/ImGui-Standalone

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Details:

**My Issue/Question:**

How can I put the filled rectangle layer wise under the group?

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::BeginGroup();
ImGui::ColorEdit3("Healthbar Color", health_color);
ImGui::EndGroup();

ImGui::GetWindowDrawList()->AddRectFilled(ImGui::GetItemRectMin(), ImGui::GetItemRectMax(), ImGui::GetColorU32(ImGuiCol_Text), 5.f);
```

**Comment by GamingMinds-DanielC** [comment]
Two ways basically. The first way is to draw the background first and the foreground later (in this case you must calculate positions before submitting the item). The second way is to use `ImDrawListSplitter`. Split your window draw list, submit the items into channel 1, then your background into channel 0 and merge again.

**Comment by Vaneeyo** [comment]
> Two ways basically. The first way is to draw the background first and the foreground later (in this case you must calculate positions before submitting the item). The second way is to use `ImDrawListSplitter`. Split your window draw list, submit the items into channel 1, then your background into channel 0 and merge again.

`                ImGui::BeginGroup();

                ImDrawList* drawList = ImGui::GetWindowDrawList();

                ImDrawListSplitter splitter;
                splitter.Split(drawList, 2);

                splitter.SetCurrentChannel(drawList, 0);
                drawList->AddRectFilled(ImGui::GetItemRectMin(), ImGui::GetItemRectMax(), IM_COL32(255, 0, 0, 128)); // Red background color, adjust alpha as needed

                splitter.SetCurrentChannel(drawList, 1);
                ImGui::Text("Test");

                splitter.Merge(drawList);

                ImGui::EndGroup();`
                This doesn't work, do you see the error by any chance?

**Comment by ocornut** [comment]
Seems like your call to Text() is incorrectly done after GetItemRectMin()/GetItemRectMax(), so the later would not get you the expected item rectangle....

You can change it to:
```cpp
splitter.SetCurrentChannel(drawList, 1);
ImGui::Text("Test");

splitter.SetCurrentChannel(drawList, 0);
drawList->AddRectFilled(ImGui::GetItemRectMin(), ImGui::GetItemRectMax(), IM_COL32(255, 0, 0, 128));
```

However, creating a splitter every frame and not preserving this is going to be very costly.
You can use the splitter available in the drawList:

```cpp
drawList->ChannelsSplit(2);
drawList->ChannelsSetCurrent(1);
ImGui::Text("Test");

drawList->ChannelsSetCurrent(0);
drawList->AddRectFilled(ImGui::GetItemRectMin(), ImGui::GetItemRectMax(), IM_COL32(255, 0, 0, 128));
drawList->ChannelsMerge();
```

**Comment by ocornut** [comment]
Closing as answered.
