### ISSUE TITLE
SDL3 2.30.0 Added SDL_FColor, SDL_RenderGeometryRaw() have been changed to use floating point colors, in the range of [0..1].

### ISSUE THREAD

**Issue by berkay-g** [ocornut/imgui#7292]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: docking

### Back-ends:

imgui_impl_sdl3.cpp + imgui_impl_sdlrenderer3.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Details:

**My Issue/Question:**

imgui_impl_sdlrenderer3.cpp

SDL_RenderGeometryRaw() and SDL_Vertex have been changed to use floating point colors, in the range of [0..1] for SDR content.

### Minimal, Complete and Verifiable Example code:

void ImGui_ImplSDLRenderer3_RenderDrawData(ImDrawData* draw_data);

```cpp
const SDL_Color* color = (const SDL_Color*)(const void*)((const char*)(vtx_buffer + pcmd->VtxOffset) + offsetof(ImDrawVert, col)); // SDL 2.0.19+

// Bind texture, Draw
SDL_Texture* tex = (SDL_Texture*)pcmd->GetTexID();
SDL_RenderGeometryRaw(bd->SDLRenderer, tex,
    xy, (int)sizeof(ImDrawVert),
    color, (int)sizeof(ImDrawVert),
    uv, (int)sizeof(ImDrawVert),
    cmd_list->VtxBuffer.Size - pcmd->VtxOffset,
    idx_buffer + pcmd->IdxOffset, pcmd->ElemCount, sizeof(ImDrawIdx));
```

**Comment by ocornut** [comment]
Moving this to #7293 opened almost simultaneously, as the later contains more details and a workaround.
