### ISSUE TITLE
PushStyleVar does not support TabBorderSize

### ISSUE THREAD

**Issue by MortezaAghazamani** [ocornut/imgui#7297]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: docking

### Back-ends:

imgui_impl_sdl2.cpp

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

Hello **Dear ImGui** world!

Is there any reason that **ImGuiStyleVar_TabBorderSize** is not defined? So **PushStyleVar** doesn't support **TabBorderSize** as a parameter. However **TabBorderSize** is used directly in demo->StyleEditor.

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::PushStyleVar(ImGuiStyleVar_TabBorderSize, 1.f); // Identifier (ImGuiStyleVar_TabBorderSize) is undefined 
```

**Comment by ocornut** [comment]
Not all values of ImGuiStyle have a corresponding ImGuiStyleVar as it is not expected that you would want to change this value often during the frame (seems like a one-time only setting done during initial style setup). 

If you feel you need it, I can add the missing enum but please clarify your use case.

**Comment by MortezaAghazamani** [comment]
Thank you for your reply. I received my answer, and you are right. Applying some settings once at initial startup is sufficient. Additionally, using this method is quite simple and convenient.
```cpp
ImGuiStyle& style = ImGui::GetStyle();
style.TabBorderSize = 1.f;
```
