### ISSUE TITLE
Padding of a single dock

### ISSUE THREAD

**Issue by NGoedix** [ocornut/imgui#7298]
### Version/Branch of Dear ImGui:

Version 1.90.2, Branch: docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 10 + Msys with GCC

### Details:

Is possible to remove the padding of a single dock? I saw that in the example you can remove the windowPadding but is in general, from all the docks, I would like to remove or modify the padding of a single dock.
![image](https://github.com/ocornut/imgui/assets/91873998/3a765e50-a094-471e-aaf9-20eb8ecb3f31)

**Comment by ocornut** [comment]
I believe #3481 discuss a similar but not exactly the same thing (specifically unmerged commit https://github.com/ocornut/imgui/pull/3481/commits/6af04436ca75e80781e6058d812a31cb98065468)
Though the semantic of whether this is considered as part of the separator or as part of padding would alter the coloring.

I don't have a good answer for this now, I guess it's not possible.

Auto-created dock node are done in `NewFrame()` so it would alter the value of WindowPadding before/after that call it should only affect docked windows.

**Comment by NGoedix** [comment]
Will the possibility be added in the future then of being able to manipulate the padding of each tab and overwrite that of the window itself? But individually, something like

```
ImGui::Begin("ExampleScene");
ImGui::SetItemPadding(ImVec2(x, y));
ImGui::End();
```

Something of that style to modify individually, taking into account that to be optimal that call is made once and not for each frame

**Comment by ocornut** [comment]
I don't understand your question.

**Comment by NGoedix** [comment]
I have solved my problem modifying the ImGui::Image and removing the padding (Creating another method as "ImageWithoutPadding") to get the wanted result.

**Comment by ocornut** [comment]
You can use `PushStyleVar(ImGuiStyleVar_FramePadding, { 0, 0 }); Image(...); PopStyleVar();` to disable the image padding, which only appears when image has a border.

However, you never mentioned `Image()` in your previous question so this is wholly confusing.
If you ask questions here please be mindful of removing ambiguities from your posts, because whereas you are thinking of one specific thing, with what you wrote I can imagine several different things.

**Comment by NGoedix** [comment]
I didn't know that the padding is added when inserting each item, i thought that all the components of a tab were added to any list and after being placed with the padding

**Comment by NGoedix** [comment]
![image](https://github.com/ocornut/imgui/assets/91873998/a1f17bb3-2ee8-4b50-a97f-4ab00b184fef)

```
    GLuint texID = workSceneRenderer->getTexture();
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, { 0, 0 });
    ImVec2 imageSize(width, height);
    ImGui::Image((void*)(intptr_t)texID, imageSize);
    ImGui::PopStyleVar();
```

It doesn't work

**Comment by ocornut** [comment]
Understood. This is also why it's always preferable that you explain you actual concrete issue. We spend lots of time here dealing with e.g. [XY Problem](https://xyproblem.info/) questions, which would be avoided if people were more explicit.

**Comment by NGoedix** [comment]
(See the padding at the left and top)

**Comment by ocornut** [comment]
This is the WindowPadding you are seeing. This is not a chat room, please take the time to think through things and investigate issues.
