### ISSUE TITLE
Cannot display image of size 410x410 pixels

### ISSUE THREAD

**Issue by kjoshi** [ocornut/imgui#730]
Sorry for another beginner question about displaying images with imgui. 
I've read as many of the previous issues as I could find, but none seem to report the same problem that I'm having.

I have created a series of test images by taking screenshots of my desktop, and writing the raw image data as an array of `uint8` using OpenCV and the following simple Python script:

```
import numpy as np
import cv2

img408 = cv2.imread("img408.png")
img408.tofile("img408.dat")

img410 = cv2.imread("img410.png")
img410.tofile("img410.dat")

img412 = cv2.imread("img412.png")
img412.tofile("img412.dat")
```
The filename of each image gives it x- and y-size in pixels. So I have three images with sizes: 408x408, 410x410 and 412x412 pixels. (I'm happy to provide these files for testing).

I have modified `opengl_example/main.cpp` to attempt to read the raw image data from the .dat files, and display it (I am using `imgui_impl_glfw.cpp` without any changes).

My opengl_example/main.cpp is:

```
#include <imgui.h>
#include "imgui_impl_glfw.h"
#include <stdio.h>
#include <GLFW/glfw3.h>

#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>

using std::cout;
using std::endl;
using std::vector;

static void error_callback(int error, const char* description)
{
    fprintf(stderr, "Error %d: %s\n", error, description);
}

int main(int argc, char** argv)
{
    if(argc != 2) {
        cout << "Please give the image width in pixels" << endl;
        return 1;
    }
    
    int image_size = std::atoi(argv[1]);

    // Setup window
    glfwSetErrorCallback(error_callback);
    if (!glfwInit())
        return 1;
    GLFWwindow* window = glfwCreateWindow(600, 600, "Test", NULL, NULL);
    glfwMakeContextCurrent(window);

    // Setup ImGui binding
    ImGui_ImplGlfw_Init(window, true);

    ImVec4 clear_color = ImColor(114, 144, 154);

    // Read image data into a vector
    std::stringstream filename;
    filename << "img" << image_size << ".dat";
    std::ifstream ifs(filename.str(), std::ios::binary|std::ios::ate);
    std::ifstream::pos_type pos = ifs.tellg();
    std::vector<char> result(pos);
    ifs.seekg(0, std::ios::beg);
    ifs.read(&result[0], pos);

    // Give the image data to OpenGL
    GLuint textureID;
    glGenTextures(1, &textureID);
    glBindTexture(GL_TEXTURE_2D, textureID);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, image_size, image_size, 0, GL_BGR, GL_UNSIGNED_BYTE, result.data());

    // Main loop
    while (!glfwWindowShouldClose(window))
    {
        glfwPollEvents();
        ImGui_ImplGlfw_NewFrame();

        ImGui::ColorEdit3("clear color", (float*)&clear_color);

        ImGui::Image((GLuint*)textureID, ImVec2(image_size,image_size));

        // Rendering
        int display_w, display_h;
        glfwGetFramebufferSize(window, &display_w, &display_h);
        glViewport(0, 0, display_w, display_h);
        glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui::Render();
        glfwSwapBuffers(window);
    }

    // Cleanup
    ImGui_ImplGlfw_Shutdown();
    glfwTerminate();

    return 0;
}
```

Trying to use this simple program to display my three test images gives the following results:

408x408:
![408](https://cloud.githubusercontent.com/assets/1217533/16730320/3073a2d4-476a-11e6-96b1-b3aada9a9e1b.png)

410x410:
![410](https://cloud.githubusercontent.com/assets/1217533/16730337/438a8cfc-476a-11e6-9479-82c62e09cbf5.png)

412x412
![412](https://cloud.githubusercontent.com/assets/1217533/16730342/4dfc2d94-476a-11e6-99bc-28fc75061f27.png)

I have not been able to figure out what is going wrong with the 410x410 image.
There seems to be no problem with img410.dat, since i can open it and display the image successfully using OpenCV (And it was created in the same way as the other raw data files).

Am I making a stupid mistake somewhere, or is there something about a 410x410 pixel image that is causing a bug somewhere?

**Comment by nem0** [comment]
What's filesize of the 3 images?

**Comment by kjoshi** [comment]
```
ls -l img*.dat
-rw-r--r--  1 kjoshi  staff  499392 11 Jul 13:16 img408.dat
-rw-r--r--  1 kjoshi  staff  504300 11 Jul 13:16 img410.dat
-rw-r--r--  1 kjoshi  staff  509232 11 Jul 13:16 img412.dat
```

They're saved as BGR, with 1 byte per colour per pixel.

**Comment by sfalexrog** [comment]
Seems like a pixel alignment issue. Try calling

`glPixelStorei(GL_UNPACK_ALIGNMENT, 1);`

before your texture upload (`glTexImage2D` etc), see if it helps.

**Comment by kjoshi** [comment]
Calling `glPixelStorei(GL_UNPACK_ALIGNMENT, 1);` right before `glTexImage2D(...)` worked!

Thanks for the suggestion!

However I don't quite understand why, though I guess it's an OpenGL question rather than an imgui one...
Isn't the image width and the data type enough to determine when the next row of pixels should begin?

Thanks again for the help.

**Comment by ocornut** [comment]
Sorry this is an OpenGL question and I have to close it. Other people may still answer here if they can help you.

**Comment by ratchetfreak** [comment]
>  GL_PACK_ALIGNMENT
>      Specifies the alignment requirements for the start of each pixel row in memory. The allowable values are 1 (byte-alignment), 2 (rows aligned to even-numbered bytes), 4 (word-alignment), and 8 (rows start on double-word boundaries).

by default it is 4 so opengl will assume that each row is padded out  to align it to 4 bytes, for 408 and 412 it is not problem because they are dividable by 4 but 410 is not.
