### ISSUE TITLE
Direct use of malloc/free in Demo

### ISSUE THREAD

**Issue by crazydef** [ocornut/imgui#7300]
### Version/Branch of Dear ImGui:

Present in the master branch on github

### Back-ends:

n/a

### Compiler, OS:

n/a

### Full config/build information:

n/a

### Details:

**My Issue**

In the file `imgui_demo.cpp` from around line 7006, the functions `ClearLog` and `AddLog` (indirectly through `Strdup`) are using `malloc` and `free` directly.

These should use the ImGui allocator functions so they can be correctly wrapped.

### Minimal, Complete and Verifiable Example code:

n/a

**Comment by ocornut** [comment]
Amended with 5cdc4a2, thanks.
