### ISSUE TITLE
How do I prevent `MenuItem` from closing after click?

### ISSUE THREAD

**Issue by pegvin** [ocornut/imgui#7302]
### Version/Branch of Dear ImGui:

Version 1.89.5, Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Linux + GCC

### Full config/build information:

*not required*

### Details:

Trying to Add a "refresh" menu item that would refresh the sub-menu entries, but I can't seem to find anything to implement the behavior I want.

Any menu/sub-menu entry closes automatically on click, which is prefect, correct & fine behavior, But I want to implement a different logic for my "refresh" menu item, I don't want it to close automatically on close.

### Screenshots/Video:

<img width="609" alt="UI Design Complexity LOL" src="https://github.com/ocornut/imgui/assets/75035219/46263af0-5117-447c-a89f-be9de99ae187">

### Minimal, Complete and Verifiable Example code:

```cpp
#define BEGIN_MENU(label) if (ImGui::BeginMenu(label)) {
#define END_MENU() ImGui::EndMenu(); }

#define BEGIN_MENUITEM(label, shortcut) if (ImGui::MenuItem(label, shortcut)) {
#define END_MENUITEM() }

BEGIN_MENU("Palette")
	BEGIN_MENUITEM("Refresh", NULL)
		PaletteHelper::UpdateEntries();
	END_MENUITEM()
	PaletteHelper::ListAll([&](const char* fileName) {
		BEGIN_MENUITEM(fileName, NULL)
			const String filePath = FileSystem::GetPalettesDir() + PATH_SEP_CHAR + fileName;
			Palette pal;
			if (PaletteParser::Parse(pal, filePath)) {
				dState.palette = std::move(pal);
				dState.PaletteIndex = 0;
				dState.tManager.primaryColor = dState.palette[dState.PaletteIndex];
			}
		END_MENUITEM()
	});
END_MENU()
```

This is my current code for reference or to make it more clear to understand?

**Comment by PathogenDavid** [comment]
You can accomplish this by enabling `ImGuiItemFlags_SelectableDontClosePopup` via `ImGui::PushItemFlag`.

It should be noted though that API *is* internal. However, there [is an intent to maybe make it public some day](https://github.com/ocornut/imgui/blob/536090303a8fca7d896f77d6d63dc59249bc87f4/imgui_internal.h#L804) and it was [introduced nearly 8 years ago](https://github.com/ocornut/imgui/commit/8828889d5ec1d8fb9ddb72bab16d5e21ba8425c6)--so I wouldn't worry about it going away or changing.

```cpp
ImGui::PushItemFlag(ImGuiItemFlags_SelectableDontClosePopup, true);
if (ImGui::MenuItem("Refresh"))
    printf("Refreshing palettes...\n");
ImGui::PopItemFlag();
```

----------------------------------

Another alternative is to simply use `ImGui::Button` or `ImGui::SmallButton` instead.

These won't close the menu popup, and as a possible bonus they're visually distinct from other menu items to give the user a hint that it'll act differently.

**Comment by pegvin** [comment]
Thanks Alot! Solved My Issue.

> These won't close the menu popup, and as a possible bonus they're visually distinct from other menu items to give the user a hint that it'll act differently.

Indeed I think I will do just that because I think the distinct look is better.

**Comment by ocornut** [comment]
It is now possible to control this for Selectable, MenuItem() using the public API:
```
ImGui::PushItemFlag(ImGuiItemFlags_AutoClosePopups, false);
ImGui::MenuItem(....);
ImGui::PopItemFlags();
```
