### ISSUE TITLE
ImGui::GetFontSize() returns 0.00000000

### ISSUE THREAD

**Issue by PaltryProgrammer** [ocornut/imgui#7304]
### Version/Branch of Dear ImGui:

v1.90.1 WIP

### Back-ends:
imgui_impl_win32.cpp + imgui_impl_dx10.cpp

### Compiler, OS:
Windows 10 Pro Visual Studio C++ 20

### Full config/build information:
sorry but i do not understand the instructions given here . id est i do not see "Demo : Tools : About Dear ImGui" anywhere on this site or my build system

### Details:
greetings kind regards
re/ example_win32_directx10 i am attempting to set the width of the ProgressBar in terms of the width of a set number of characters . I am accepting the default font . calling `ImGui::CalcTextSize()` results in a thrown exception . it is called immediately prior to the `while(!done)` loop in example_win32_directx10 : main.c : line 89 . also ImGui::GetFontSize() returns exactly zero . i seek your kind assistance .
thank you kindly
### Screenshots/Video:
![ ImGui-CalcTextSize() throws exception](https://github.com/ocornut/imgui/assets/48535920/77816c23-108a-4728-9ce2-c88be98bcc3a)
![null ImFont ptr value](https://github.com/ocornut/imgui/assets/48535920/45f1290c-8468-43f1-ab26-32ba17beb3c2)
### Minimal, Complete and Verifiable Example code:
to reproduce merely insert two lines below immediately prior to `while(!done)` loop in project : example_win32_directx10 file : main.c line : 89 .
`auto font_size = ImGui::GetFontSize();`
`auto text_size = ImGui::CalcTextSize("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ");`
the returned value from `ImGui::GetFontSize();` is `font_size = 0.00000000` .
`ImGui::CalcTextSize(...);` throws an exception .

**Comment by ocornut** [comment]
This gets the current font size. There's no current font and no current window if you are not within the scope of the Dear ImGui frame - aka between `NewFrame()` and `Render()` - so your call is invalid.

> sorry but i do not understand the instructions given here . id est i do not see "Demo : Tools : About Dear ImGui" anywhere on this site or my build system

This refers to the Demo window of Dear ImGui. Open "Tools" menu and click "About Dear ImGui".
