### ISSUE TITLE
Support multiple input/pointing devices (e.g., for VR and multi-user interactions)

### ISSUE THREAD

**Issue by AberrantWolf** [ocornut/imgui#7309]
### Version/Branch of Dear ImGui:

Version 1.90.2, Branch: master

### Back-ends:

imgui_impl_dx12.cpp + imgui_impl_vulkan.cpp + imgui_impl_opengl3.cpp 

### Compiler, OS:

Windows 10/11

### Details:

**We need support for multiple (arbitrary-many) pointing devices**

We are adapting our system, which uses DearImGui, to show UI in VR (potentially with multiple users via a Cloud server), and also possibly multiple PC users over a network.

Even in the single-VR users case, most VR systems have two controllers which each represent a pointing device in 3D space. I'm perfectly fine needing to flatten input into UI widget space for input handling, but AFAICT there's no support for multiple, arbitrary pointing devices on ImGui UIs. I see there is the ability to select a mouse source from "mouse," "touch," and "pen," but we expect at a minimum to have input from mouse, left controller, and right controller in the same window; but also then potentially multiple desktop users (mice) and multiple VR/AR users (controllers, touch screens).

The expectation would be that highlighting, dragging, activating, etc... would track its source, and as such you could have (for example) multiple buttons (A and B) highlighted, and when input A is "pressed", only its highlighted button A would become pressed.

I haven't seen anywhere this is a planned feature or even other bugs/suggestions, so I submit this suggestion here. Let me know if there's already another issue I can follow-up with instead.

**Comment by ocornut** [comment]
Same answer as #7322

**Comment by ocornut** [comment]
I'll close this as similar to #7322 which I understand. Some form of multi-touch at a high level is probably possible, but multiple pointing devices are largely out of scope with current design. Even if we had resources I'm not sure it would be a reasonable design change, but given limited resources it becomes a no-brainer.

I suppose the closest you can do at your backend level is to manage the priority of different input source so the backend would make it possible to easily switch (automatically or manual) between sources but only feed one to dear imgui.
