### ISSUE TITLE
Undefined behavior in ImVector::reserve

### ISSUE THREAD

**Issue by guillaumechereau** [ocornut/imgui#731]
This is not a big deal, but when I compile imgui on linux (gcc amd64) with -fsanitize=undefined, I get a runtime error:

    imgui.h:888:9: runtime error: null pointer passed as argument 2, which is declared to never be null

The line in question is:

    memcpy(new_data, Data, (size_t)Size * sizeof(value_type));

This is probably totally harmless, but adding a test before the memcpy would remove some useless warnings of fsanitize.

**Comment by ocornut** [comment]
Let's do that! Thanks Guillaume.
