### ISSUE TITLE
Preferred method of determining if a popup is already open ( so I can inhibit tooltips )

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#7311]
### Version/Branch of Dear ImGui:

1.90WIP

### Back-ends:

SDL software rendering

### Compiler, OS:

g++ 13.2.0

### Details:

Is there a function to call to ascertain if *any* popup/dialog/window is currently open?

I typically have a function for determining if I'm hovering over certain objects but I want to suspect that if I have a dialog/popup window open;   currently I've been using a bool state variable but for some reason my logic is flawed somewhere, so I was thinking it might be easier for me to just have something akin to;

```
if (ImGui::IsAnyDialogOpen()) {
  return; // don't show tooltips
}
```

You can see the tooltip in the attached screenshot which is floating around with the mouse pointer after the dialog has already opened up.

### Screenshots/Video:

![Screenshot at 2024-02-13 19-11-48](https://github.com/ocornut/imgui/assets/5660591/c47895a8-b13d-477b-9788-6c45dc2d117c)

**Comment by GamingMinds-DanielC** [comment]
Take a look at `ImGui::IsPopupOpen()`. You can check for specific popups, any popup at the current level or even at any level, documentation is in the header where the function is declared.

**Comment by inflex** [comment]
> Take a look at `ImGui::IsPopupOpen()`. 

Thank you, I did read your suggestion about IsWindowHovered() but the IsPopupOpen() actually provided the behaviour I wanted ( when any popup is present I want my tooltip call to just return immediately ).

```
void render_tooltip() {
 
   if (ImGui::IsPopupOpen(NULL, ImGuiPopupFlags_AnyPopupId + ImGuiPopupFlags_AnyPopupLevel)) return;
   ...
}
```

**Comment by ocornut** [comment]
> if any popup/dialog/window is currently open?

Technically checking for "ANY popups" would be `g.OpenPopupStack.Size > 0` but I don't think this is a correct approach, as you can technically have nested popups with meaningful contents inside them.

Moreover I believe your question is a XY Problem in the first place: your issue is in the code submitting the tooltip, you are not using the correct flavor of hovering test. **You should clarify the code/logic leading to that tooltip appearing.**

Normal widgets use `IsItemHovered()` which verifies that the window is hovered, it doesn't only do a rect check. 
I don't know what you are doing but your hover test leading to tooltips is wrong.

**Comment by inflex** [comment]
Maybe it's a communications / description issue with what I'm presenting;

When I hover over a specific drawn object on the normal viewport I draw a tooltip describing what the object is (in this case, electronic component, and potentially a network name / details.  It's only relevant to be displayed when no popups are present.

Which component/pin is hovered only needs to be determined if I'm in the normal viewing/inspecting mode of the program.

See attached image illustrating when  I hover over the Pin-2 of the L7310 block/component it brings up the tooltip which contains the information about that specific part/network.

![Screenshot at 2024-02-14 00-46-09](https://github.com/ocornut/imgui/assets/5660591/3491c3e7-6764-4e44-99f7-2cd76e23de80)

The simplest way I can describe the routine is roughly;

```
DrawUI();
DrawBoard();
if (!ImGui::IsPopupOpen(...))) {
   convertMousePosToCircuitBoardPos()
   checkForHoveredItems()
   if (partIsHovered || pinIsHovered) {
    drawPartPinTooltip()
   }
}
```

At this point from a user perspective,  the behaviour is now what I  am was wanting to achieve and for now it's more robust than the method that was being utilised previously ( have each popup assert/de-assert a bool to manage the behaviours )
