### ISSUE TITLE
Tables having glitching width

### ISSUE THREAD

**Issue by Angelo-Aurelio** [ocornut/imgui#7323]
### Version/Branch of Dear ImGui:

Version 1.90 WIP (18995), Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Visual Studio 2022 on Windows 11

### Details:

I actually don't know much of programming, neither my english is perfect, as I am brazilian, but I'll give as much info as I can.

My program is being made in Debug X64 with the mentioned backends. C++ 2017, OpenGL 3.3, Dear ImGUI 1.90 WIP.

The Debug works with sucess. This is no crash issue, but actually a visual bug. Tables with visual bug in width. I'll send a video of it showing the bug.

Big description: The window that shows this bug is the "Resultados da Análise Estrutural", and it has lots of tables. They are all made with the same flags. The first ones doesn't show any bug, but the later ones does. This "later ones" is not specific, as sometimes more of them has this bug, sometimes less. Also, there are times some of them in the end of the window actually has no glitch/bug. This randomness occurs mostly when I close the debugging and open it again, but a few times I closed the window or resized it and some tables stopped to glitch and other ones begun. The collapsing headers were separator texts before, and this bug kept even with this change. The variables has nothing to do with it, because I can change them inside the program and the glitch still happens.

Video description: I show the opened window with the tables, some okay, some not. The visual bug prevents me to resize the width of the tables, while the other ones is okay with it. Some tables did only a few times the glitch, but the resizing feature was not working even when not glitching. I can make more videos changing values but they doesn't change the bugging windows.

Code description: I am passing THE WHOLE window code. There shows the variables ss, str, flags and outer_size declared outside the collapsing headers. So, the variables that are inside the tables, besides the chars being written directly on it, are ALL int, float or double. All being put with ImGui::Text(). I don't know what else matters to say here to begin with, so I hope these info will help.

### Screenshots/Video:

https://github.com/ocornut/imgui/assets/148796370/bbe13254-f1da-42c7-8a5e-f713fc7286dc

### Minimal, Complete and Verifiable Example code:

```cpp

void ImGui::janelaresultados(bool* p_open) {
    if (!ImGui::Begin("Glitching window", p_open, window_flags))
    {
        ImGui::End();
        return;
    }
    std::stringstream ss;
    const char* str;
    static ImGuiTableFlags flags = ImGuiTableFlags_Resizable | ImGuiTableFlags_BordersOuter | ImGuiTableFlags_BordersV | ImGuiTableFlags_ScrollX | ImGuiTableFlags_ScrollY | ImGuiTableFlags_RowBg;
    ImVec2 outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 7);
    if (ImGui::CollapsingHeader("Table 1"))
    {
        if (ImGui::BeginTable("tableone", 6, flags, outer_size))
        {
            ImGui::TableSetupScrollFreeze(1, 1);
            ImGui::TableNextRow();
            TableSetColumnIndex(0);
            ImGui::Text("first line");
            for (int i = 0; i < 5; i++)
            {
                TableSetColumnIndex(i + 1);
                ImGui::Text("Row %d", i);
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("second line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("third line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("fourth line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("fifth line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("sixth line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("Table 2"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 10);
        if (ImGui::BeginTable("tabletwo", 4, flags, outer_size))
        {
            ImGui::TableSetupScrollFreeze(1, 1);
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("Line two");
            for (int i = 0; i < 3; i++)
            {
                ImGui::TableSetColumnIndex(i + 1);
                ImGui::Text("Row %d", i);
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("second line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" %d", column);
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("third line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" %d", column - 1);
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("fourth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("fifth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("sixth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("seventh line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("eighth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("ninth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("More tables"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 7);
        for (int i = 0; i < 3; i++)
        {
            ImGui::Spacing();
            ImGui::Text("Another table %d", i);
            ss << "matriz_rigidez_" << i;
            str = ss.str().c_str();
            if (ImGui::BeginTable(str, 6, flags, outer_size))
            {
                for (int j = 0; j < 6; j++)
                {
                    ImGui::TableNextRow();
                    for (int k = 0; k < 6; k++)
                    {
                        ImGui::TableSetColumnIndex(k);
                        ImGui::Text(" 0.000000");
                    }
                }
                ImGui::EndTable();
            }
        }
    }
    if (ImGui::CollapsingHeader("Bigger table"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 5 * 3 + ImGui::GetTextLineHeightWithSpacing());
        if (ImGui::BeginTable("supermatriz", 5 * 3, flags, outer_size))
        {
            for (int line = 0; line < 5 * 3; line++)
            {
                ImGui::TableNextRow();
                for (int column = 0; column < 5 * 3; column++)
                {
                    ImGui::TableSetColumnIndex(column);
                    ImGui::Text(" 0.000000");
                }
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("Smaller table"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * tamanhofinalSM + ImGui::GetTextLineHeightWithSpacing());
        if (ImGui::BeginTable("supermatrizfinal", 6, flags, outer_size))
        {
            for (int line = 0; line < 6; line++)
            {
                ImGui::TableNextRow();
                for (int column = 0; column < 6; column++)
                {
                    ImGui::TableSetColumnIndex(column);
                    ImGui::Text(" 0.000000");
                }
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("Array 1"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        if (ImGui::BeginTable("forcaexterna", 5 * 3, flags, outer_size))
        {
            ImGui::TableNextRow();
            for (int i = 0; i < 5 * 3; i++)
            {
                ImGui::TableSetColumnIndex(i);
                ImGui::Text(" 0.000000");
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("Array 2"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        if (ImGui::BeginTable("deslocamentototal", 5 * 3, flags, outer_size))
        {
            ImGui::TableNextRow();
            for (int i = 0; i < 5 * 3; i++)
            {
                ImGui::TableSetColumnIndex(i);
                ImGui::Text(" 0.000000");
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("More arrays"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        for (int i = 0; i < 3; i++)
        {
            ImGui::Spacing();
            ImGui::Text("Small array %d", i);
            ss << "vetor_deslocamento_" << i;
            str = ss.str().c_str();
            if (ImGui::BeginTable(str, 6, flags, outer_size))
            {
                ImGui::TableNextRow();
                for (int j = 0; j < 6; j++)
                {
                    ImGui::TableSetColumnIndex(j);
                    ImGui::Text(" 0.000000");
                }
                ImGui::EndTable();
            }
        }
    }
    if (ImGui::CollapsingHeader("Even more arrays"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        for (int i = 0; i < 3; i++)
        {
            ImGui::Spacing();
            ImGui::Text("Array also small %d", i);
            ss << "vetor_forca_global_" << i;
            str = ss.str().c_str();
            if (ImGui::BeginTable(str, 6, flags, outer_size))
            {
                ImGui::TableNextRow();
                for (int j = 0; j < 6; j++)
                {
                    ImGui::TableSetColumnIndex(j);
                    ImGui::Text(" 0.000000");
                }
                ImGui::EndTable();
            }
        }
    }
    if (ImGui::CollapsingHeader("The end of arrays"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        for (int i = 0; i < 3; i++)
        {
            ImGui::Spacing();
            ImGui::Text("Last array %d", i);
            ss << "vetor_forca_local_" << i;
            str = ss.str().c_str();
            if (ImGui::BeginTable(str, 6, flags, outer_size))
            {
                ImGui::TableNextRow();
                for (int j = 0; j < 6; j++)
                {
                    ImGui::TableSetColumnIndex(j);
                    ImGui::Text(" 0.000000");
                }
                ImGui::EndTable();
            }
        }
    }
    ImGui::End();
}


```

Edit:
I forgot to put the labels, and I can't find a way to edit it... Sorry guys! Labels are probably: bug, glitch, issue, tables/columns.

**Comment by Angelo-Aurelio** [comment]
I forgot to put the labels, and I can't find a way to edit it... Sorry guys!

Labels are probably: bug, glitch, issue, tables/columns.

**Comment by ocornut** [comment]
I don't know what is happening either.
We would need you to reduce and simplify your code until it becomes a Minimum, Complete, Verifiable example. Doing that you are likely to narrow down the issue to something that is easier to understand.

**Comment by Angelo-Aurelio** [comment]
Well, I'll paste the code that is now reduced and it can be ferifiable. Just call this window as it's called any other ImGui::windowfunction(bool* open) and it should appear. It doesn't seem reduced, but that it seems to be the point. I replaced all variables to zeros and respective values of iterations for the tables. So, all of the float and double values shows now 0.000000 and the int values are placed by the "i" iteractor that is used. This decreased the bug greatly, but it still happens as I show in the video. Following is the code of the window:


void ImGui::janelaresultados(bool* p_open) {
    if (!ImGui::Begin("Glitching window", p_open, window_flags))
    {
        ImGui::End();
        return;
    }
    std::stringstream ss;
    const char* str;
    static ImGuiTableFlags flags = ImGuiTableFlags_Resizable | ImGuiTableFlags_BordersOuter | ImGuiTableFlags_BordersV | ImGuiTableFlags_ScrollX | ImGuiTableFlags_ScrollY | ImGuiTableFlags_RowBg;
    ImVec2 outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 7);
    if (ImGui::CollapsingHeader("Table 1"))
    {
        if (ImGui::BeginTable("tableone", 6, flags, outer_size))
        {
            ImGui::TableSetupScrollFreeze(1, 1);
            ImGui::TableNextRow();
            TableSetColumnIndex(0);
            ImGui::Text("first line");
            for (int i = 0; i < 5; i++)
            {
                TableSetColumnIndex(i + 1);
                ImGui::Text("Row %d", i);
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("second line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("third line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("fourth line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("fifth line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("sixth line");
            for (int column = 0; column < 5; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("Table 2"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 10);
        if (ImGui::BeginTable("tabletwo", 4, flags, outer_size))
        {
            ImGui::TableSetupScrollFreeze(1, 1);
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("Line two");
            for (int i = 0; i < 3; i++)
            {
                ImGui::TableSetColumnIndex(i + 1);
                ImGui::Text("Row %d", i);
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("second line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" %d", column);
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("third line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" %d", column - 1);
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("fourth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("fifth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("sixth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text("0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("seventh line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("eighth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::TableNextRow();
            ImGui::TableSetColumnIndex(0);
            ImGui::TextUnformatted("ninth line");
            for (int column = 0; column < 3; column++)
            {
                ImGui::TableSetColumnIndex(column + 1);
                ImGui::Text(" 0.000000");
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("More tables"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 7);
        for (int i = 0; i < 3; i++)
        {
            ImGui::Spacing();
            ImGui::Text("Another table %d", i);
            ss << "matriz_rigidez_" << i;
            str = ss.str().c_str();
            if (ImGui::BeginTable(str, 6, flags, outer_size))
            {
                for (int j = 0; j < 6; j++)
                {
                    ImGui::TableNextRow();
                    for (int k = 0; k < 6; k++)
                    {
                        ImGui::TableSetColumnIndex(k);
                        ImGui::Text(" 0.000000");
                    }
                }
                ImGui::EndTable();
            }
        }
    }
    if (ImGui::CollapsingHeader("Bigger table"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 5 * 3 + ImGui::GetTextLineHeightWithSpacing());
        if (ImGui::BeginTable("supermatriz", 5 * 3, flags, outer_size))
        {
            for (int line = 0; line < 5 * 3; line++)
            {
                ImGui::TableNextRow();
                for (int column = 0; column < 5 * 3; column++)
                {
                    ImGui::TableSetColumnIndex(column);
                    ImGui::Text(" 0.000000");
                }
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("Smaller table"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * tamanhofinalSM + ImGui::GetTextLineHeightWithSpacing());
        if (ImGui::BeginTable("supermatrizfinal", 6, flags, outer_size))
        {
            for (int line = 0; line < 6; line++)
            {
                ImGui::TableNextRow();
                for (int column = 0; column < 6; column++)
                {
                    ImGui::TableSetColumnIndex(column);
                    ImGui::Text(" 0.000000");
                }
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("Array 1"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        if (ImGui::BeginTable("forcaexterna", 5 * 3, flags, outer_size))
        {
            ImGui::TableNextRow();
            for (int i = 0; i < 5 * 3; i++)
            {
                ImGui::TableSetColumnIndex(i);
                ImGui::Text(" 0.000000");
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("Array 2"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        if (ImGui::BeginTable("deslocamentototal", 5 * 3, flags, outer_size))
        {
            ImGui::TableNextRow();
            for (int i = 0; i < 5 * 3; i++)
            {
                ImGui::TableSetColumnIndex(i);
                ImGui::Text(" 0.000000");
            }
            ImGui::EndTable();
        }
    }
    if (ImGui::CollapsingHeader("More arrays"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        for (int i = 0; i < 3; i++)
        {
            ImGui::Spacing();
            ImGui::Text("Small array %d", i);
            ss << "vetor_deslocamento_" << i;
            str = ss.str().c_str();
            if (ImGui::BeginTable(str, 6, flags, outer_size))
            {
                ImGui::TableNextRow();
                for (int j = 0; j < 6; j++)
                {
                    ImGui::TableSetColumnIndex(j);
                    ImGui::Text(" 0.000000");
                }
                ImGui::EndTable();
            }
        }
    }
    if (ImGui::CollapsingHeader("Even more arrays"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        for (int i = 0; i < 3; i++)
        {
            ImGui::Spacing();
            ImGui::Text("Array also small %d", i);
            ss << "vetor_forca_global_" << i;
            str = ss.str().c_str();
            if (ImGui::BeginTable(str, 6, flags, outer_size))
            {
                ImGui::TableNextRow();
                for (int j = 0; j < 6; j++)
                {
                    ImGui::TableSetColumnIndex(j);
                    ImGui::Text(" 0.000000");
                }
                ImGui::EndTable();
            }
        }
    }
    if (ImGui::CollapsingHeader("The end of arrays"))
    {
        outer_size = ImVec2(0.0f, ImGui::GetTextLineHeightWithSpacing() * 2);
        for (int i = 0; i < 3; i++)
        {
            ImGui::Spacing();
            ImGui::Text("Last array %d", i);
            ss << "vetor_forca_local_" << i;
            str = ss.str().c_str();
            if (ImGui::BeginTable(str, 6, flags, outer_size))
            {
                ImGui::TableNextRow();
                for (int j = 0; j < 6; j++)
                {
                    ImGui::TableSetColumnIndex(j);
                    ImGui::Text(" 0.000000");
                }
                ImGui::EndTable();
            }
        }
    }
    ImGui::End();
}

And now the video of how it is now... uh... okay... there it is:

https://github.com/ocornut/imgui/assets/148796370/84ab078b-250f-44b8-a098-17d93fe598f4

This is really awkward. It was bugging even like this, but now it's no longer glitching. In fact, it only happens now while I scroll through the window. But now the resizing is not possible in most of the tables. It should be all resizable...

I also tried to take out some of the tables, to see if it is the amount of tables. Took off the first two and the bigger table. The others remained the same. Now glitching only while scrolling through the window or collapsing the headers, but still preventing me to resize the widths of them.

**Comment by ocornut** [comment]
The issue is that is invalid:

```cpp
const char* str;
[....]
str = ss.str().c_str();
if (ImGui::BeginTable(str, 6, flags, outer_size))
```

`const char* str = ss.str().c_str();` you are creating a temporary string (`.str()` call) and pointing to its content (`const char* xxx = xxx.c_str()`. The temporary std::string gets destroyed before you can pass it to `BeginTable()` which receives random/garbage data:

![image](https://github.com/ocornut/imgui/assets/8225057/a8bcfd53-dc61-4dc0-8fd7-4096c89fa818)


If you open `Metrics/Debugger->Tables` you can see that that even though 3 tables are visible many more are created depending on the garbage data you pass as table ID.

![image](https://github.com/ocornut/imgui/assets/8225057/2f907506-0157-4027-bda5-fcf2820d13b4)


Solutions:
- 1. If you change `const char* str` to `std::string str` your string will be stored.
- 2. You may also use `(ImGui::BeginTable(ss.str().c_str(), 6, flags, outer_size))`. When you do this you have a guarantee that the temporary won't be destroyed before returning from the function.
- 3. Or many other alternatives like fmt.

I personally use https://github.com/ocornut/Str because std::string allocate on heap and I find std:: style concatenation and formatting to be tedious. So it would become `ImGui::BeginTable(Str30f("matriz_rigidez_%d", i).c_str(), ...)`.

**Comment by Angelo-Aurelio** [comment]
YES! IT WORKED!!! I used the Str.h and it worked perfectly! This const char*/string passed in the BeginTables were taking a toll on me for long time, and that type of string were one that worked so I thought there was no problem on it. Well, learning and getting better! Thank you for your time, and sorry for the inconvenience!
