### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by ElectroGamesDev** [ocornut/imgui#7326]
### Version/Branch of Dear ImGui:

Version 1.90.0, Branch: docking

### Back-ends:

imgui_impl_raylib.h

### Compiler, OS:

WIndows 10  MSVC

### Details:

Hey there, so I have a few questions.

With tree nodes, when I select the node (no matter if I click the arrow or not), it opens/closes the node. How could I make it so it only opens/closes the node if I click on the arrow?

How can I check if a tree node is open or closed? I tried using IsItemToggledOpen(), but that seems to only run if the node is open/closed during that frame.

How can I change the height of a Menu Bar Button? I took a look at the function and it seems changing the font size will increase the size of it, but I would prefer to not have to change the size of my text as I don't want the text to be too big. 

Final question, I'm having some slight issues with building docks. One of my windows ("File Explorer") is docking to below my "Viewport" window and in between the "Hierarchy" and "Properties" windows, but I would like to dock below everything else. How might I do that? I have attached my code and screenshots of the result and of what I'm trying to do.

Thanks!

### Screenshots/Video:

![Screenshot 2024-02-17 020655](https://github.com/ocornut/imgui/assets/34932094/060950b7-a0c6-4178-b2cd-5eaa803f68fc)
![Screenshot 2024-02-17 020716](https://github.com/ocornut/imgui/assets/34932094/7b71177a-5f13-4137-9b1a-c8fa59b2b6be)

### Minimal, Complete and Verifiable Example code:

```cpp
    if (ImGui::DockBuilderGetNode(dockspaceID) == NULL)
    {
        ImGui::DockBuilderRemoveNode(dockspaceID);
        ImGui::DockBuilderAddNode(dockspaceID, ImGuiDockNodeFlags_NoWindowMenuButton | ImGuiDockNodeFlags_NoCloseButton);
        ImGui::DockBuilderSetNodeSize(dockspaceID, ImGui::GetWindowSize());

        ImGuiID dock_main_id = dockspaceID;
        ImGuiID dock_id_left = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Left, 0.15f, NULL, &dock_main_id);
        ImGuiID dock_id_right = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Right, 0.20f, NULL, &dock_main_id);
        ImGuiID dock_id_bottom = ImGui::DockBuilderSplitNode(dock_main_id, ImGuiDir_Down, 0.20f, NULL, &dock_main_id);

        ImGui::DockBuilderDockWindow("Hierarchy", dock_id_left);
        ImGui::DockBuilderDockWindow("Viewport", dock_main_id);
        ImGui::DockBuilderDockWindow("Properties", dock_id_right);
        ImGui::DockBuilderDockWindow("File Explorer", dock_id_bottom);
        ImGui::DockBuilderDockWindow("Console", dock_id_bottom);
        ImGui::DockBuilderFinish(dockspaceID);
    }
```

**Comment by ocornut** [comment]
Hello,
Please open separate issues for unrelated questions, otherwise it becomes useless for future readers. Some of the questions also suggest you haven’t done homework exploring the demo or header file.
