### ISSUE TITLE
Load the TTF file

### ISSUE THREAD

**Issue by alanyangbo** [ocornut/imgui#733]
code:
-----code.h--------------------
	unsigned char* pixels;
	int width ;
	int height, bytes_per_pixels;
-----code.cpp----------------------------
ImGuiIO& io = ImGui::GetIO();
io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\simhei.ttf", 13.0f, NULL,io.Fonts->GetGlyphRangesChinese());
io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height,&bytes_per_pixels);
----------------------------------------------
Is that anything wrong?

**Comment by ocornut** [comment]
I don't think so, assuming that font file exists.
What is your problem?

**Comment by alanyangbo** [comment]
![Uploading window.png…]()

**Comment by alanyangbo** [comment]
The problem is all the letters become a black square:(

**Comment by ocornut** [comment]
Have you uploaded the texture into video memory with whatever backend/engine you are using?
Which renderer are you using? The rendering code needs to bind a texture.
Read about ImTextureId and the different examples.

**Comment by stfx** [comment]
I had this happen too when you use a font with many glyphs like chinese and with too large of a font scale. Seems like the generated font texture got too big for the GPU to handle

**Comment by MINIONBOTS** [comment]
Same here, had 4 ttf files, goal was to cover all of the language in one texture. It kept crashing on smaller GPUs, ocornut did a change later on ( https://github.com/ocornut/imgui/commit/65a525550ecf48e14f20681b081b1d9c8c136563 ) which solved it for me.

**Comment by MINIONBOTS** [comment]
This is what I am doing right now, maybe it helps you:
![index](https://cloud.githubusercontent.com/assets/2842405/16943709/488190fa-4d9d-11e6-86e7-65a3469cb569.png)

**Comment by ratchetfreak** [comment]
I don't think that `(path+"\\...").c_str()` will work. Unless I'm mistaken the temporary (can) gets cleaned up before the function is called.

Instead do something like:

```C
std::string filename = path+"\\...";
io.Font->AddFontFromFileTTF(filename.c_str(), ...);
```

**Comment by alanyangbo** [comment]
My backend/engine is opengl.How to upload and bind the the texture? I know about opengl little.I just use it as gui for c++:( :::::

**Comment by paulsapps** [comment]
@ratchetfreak you are wrong, because its const its life time is extended.

**Comment by ocornut** [comment]
@alanyangbo Closing this now, hope it is ok.
