### ISSUE TITLE
InputText illegally overwrites the modified content

### ISSUE THREAD

**Issue by MidTerm-CN** [ocornut/imgui#7333]
### Version/Branch of Dear ImGui:

Version 
Discover: v1.89.7, Branch: master
New Test: v1.90.3, Branch: master ( still exist )

### Back-ends:

imgui_impl_dx11.cpp

### Compiler, OS:

Windows 11 23H2

### Details:

**My Issue/Question:**

This bug occur in 2 frames.
In the first frame, set the string. If normal, In the second frame, it should be updated to the new value.
However, in the second frame, it is not updated and my variable's value is changed to original value.

### Screenshots/Video:

![59623b10123b64adc3c81055ff226152](https://github.com/ocornut/imgui/assets/83219310/c3b7c716-dbf0-4f5b-b111-0040b18ffeb8)
![{8452D532-1486-49ed-96D4-6CF45B32DD3D}](https://github.com/ocornut/imgui/assets/83219310/785df3e8-4177-4dee-8c5d-9a57dfd3a34d)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
static std::string currentInput = "";
if (ImGui::InputText("#Input", &currentInput, ImGuiInputTextFlags_EnterReturnsTrue))
{
currentInput = "";
}
if (ImGui::IsKeyPressed(ImGuiKey_UpArrow))
{
currentInput = "new value";
}
```

**Comment by ocornut** [comment]
`InputText()` currently holds on a copy of the value when active, this is a known issue that is described in 10+ topics here.
I hope the behavior can be reworked this year. In the meanwhile you can use
```cpp
currentInput = "new value";
if (ImGuiInputTextState* input_state = ImGui::GetInputTextState(ImGui::GetID("#input"))
    input_state->ReloadUserBufAndSelectAll();
```

Please note that the `ImGuiInputTextFlags_CallbackHistory` feature of `InputText()` was designed to implement history through callbacks. See "Demo->Widgets->Text Input->Completion, History, Edit Callbacks" and "Demo->Examples->Console" for demos of using this.
