### ISSUE TITLE
After transplanting to kernel D3D11 imgui, the text rendering is incomplete.

### ISSUE THREAD

**Issue by EFTNice** [ocornut/imgui#7334]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

windows 10

### Full config/build information:

no

### Details:

**My Issue/Question:**

hi guys !

I tried to port imgui to the kernel for use

Now rendering lines, rectangles and circles everything works fine!

Only rendering text has problems. Just like the picture I posted, the text rendering is incomplete. Can someone tell me what part of the code I should check? I've never had this problem before and don't know what to do now

thx's

### Screenshots/Video:

![photo_2024-02-19_13-38-00](https://github.com/ocornut/imgui/assets/61795399/f3f077a7-19e8-413e-b5fd-b8effffc6b0b)

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui_ImplDX11_NewFrame(HUD);
ImFont* Font = Fonts->Fonts[0];
if (Font) {
	              ImFontAtlas* atlas = Font->ContainerAtlas;
	              DrawListSharedData->TexUvWhitePixel = atlas->TexUvWhitePixel;
	              DrawListSharedData->TexUvLines = atlas->TexUvLines;
	              DrawListSharedData->Font = Font;
	              DrawListSharedData->FontSize = Font->FontSize;
              
	              DrawListSharedData->ClipRectFullscreen = ImVec4(0, 0, HUD->Width, HUD->Height);
	              DrawListSharedData->CurveTessellationTol = 1.25f;
	              DrawListSharedData->SetCircleTessellationMaxError(0.300000012f);
	              DrawListSharedData->InitialFlags = ImDrawListFlags_None;
	              DrawListSharedData->InitialFlags |= ImDrawListFlags_AntiAliasedLines;
	              DrawListSharedData->InitialFlags |= ImDrawListFlags_AntiAliasedLinesUseTex;
	              DrawListSharedData->InitialFlags |= ImDrawListFlags_AntiAliasedFill;
	              DrawListSharedData->InitialFlags |= ImDrawListFlags_AllowVtxOffset;
              
	              DrawList->_ResetForNewFrame();
	              DrawList->PushClipRectFullScreen();
	              DrawList->PushTextureID(Fonts->TexID);


			DrawList->AddRectFilled(ImVec2(100, 100), ImVec2(400, 400), 0xFFFF00FF);
			DrawList->AddText(NULL, 0, ImVec2(600, 600), 0xFF00FFFF, "ABCD0123456789{}[]mnbh[Dkkyuyuod");

			drawData->Clear();
			drawData->Valid = true;
			drawData->DisplayPos = ImVec2(1.0f, 1.0f);
			drawData->DisplaySize = ImVec2(HUD->Width, HUD->Height);
			drawData->FramebufferScale = ImVec2(1.0f, 1.0f);
			drawData->AddDrawList(DrawList);
			ImGui_ImplDX11_RenderDrawData(HUD, drawData);
}
```

**Comment by GamingMinds-DanielC** [comment]
With basically no information given and only a snippet of code that is far from complete, there isn't really a chance to see what goes wrong. So basically a few common hints:
- Test in debug mode with assertions enabled and check if ImGui will tell you what you are doing wrong.
- Check the font atlas in the "Dear ImGui Metrics/Debugger" window if it is intact.
- Capture a frame in RenderDoc and check your draw calls and resources there.

**Comment by ocornut** [comment]
Sorry but #1586
