### ISSUE TITLE
call SetDescriptorHeaps for secondary viewport in UserCallback 

### ISSUE THREAD

**Issue by shinji12345** [ocornut/imgui#7336]
### Version/Branch of Dear ImGui:

Version 1.90.1 WIP, Branch: docking (master/docking/etc.)

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_dx12.cpp

### Compiler, OS:

Windows10 + msvc 2022

### Full config/build information:

```
Dear ImGui 1.90.1 WIP (19002)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1937
define: _MSVC_LANG=202002
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_dx12
io.ConfigFlags: 0x00000441
 NavEnableKeyboard
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMoveFromTitleBarOnly
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 600.00,480.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

I would like to display images in ImGui.

Since the number of images is not known, the size of the DescritporHeap cannot be determined at the beginning.

So I thought it would be better to create a Heap for Font and a Heap for Image, and switch between them before and after the ImGui::Image call.

That worked for a single Viewport, but not for multiple Viewports.

The command list for the second Viewport is created in imgui_impl_dx12.cpp, so I can't touch it.

Also, I am not able to know the detailed type of ImGuiViewport::RendererUserData.

Could you please let me know if there is a solution to this problem.

### Minimal, Complete and Verifiable Example code:

```cpp
struct MyViewport
{
    ID3D12DescriptorHeap* image_texture_heap;

    ID3D12GraphicsCommandList* imgui_command_list_for_mainviewport;
    ID3D12DescriptorHeap* imgui_font_heap;

    void* renderer_user_data;

    void render()
    {
        if (ImGui::Begin("viewport")) {

            this->renderer_user_data = ImGui::GetWindowViewport()->RendererUserData;

            ImGui::GetWindowDrawList()->AddCallback([](const ImDrawList* parent_list, const ImDrawCmd* cmd)
            {
                MyViewport* viewport = (MyViewport*)(cmd->UserCallbackData);
                ID3D12DescriptorHeap* heap_ptrs[1]{ viewport->image_texture_heap };
                viewport->imgui_command_list_for_mainviewport->SetDescriptorHeaps(1, heap_ptrs);
            }, this);

            const ImVec2 window_size = ImGui::GetWindowSize();
            ImGui::Image((ImTextureID)(this->image_texture_heap->GetGPUDescriptorHandleForHeapStart().ptr), window_size);

            ImGui::GetWindowDrawList()->AddCallback([](const ImDrawList* parent_list, const ImDrawCmd* cmd)
            {
                MyViewport* viewport = (MyViewport*)(cmd->UserCallbackData);
                ID3D12DescriptorHeap* heap_ptrs[1]{ viewport->imgui_font_heap };
                viewport->imgui_command_list_for_mainviewport->SetDescriptorHeaps(1, heap_ptrs);
            }, this);
        }
    }
};

```

**Comment by PathogenDavid** [comment]
You should basically never switch descriptor heaps.

[General Microsoft guidance](https://docs.microsoft.com/en-us/windows/win32/direct3d12/descriptor-heaps-overview#switching-heaps):

> On some hardware, this can be an expensive operation, requiring a GPU stall to flush all work that depends on the currently bound descriptor heap.
>
> As a result, if descriptor heaps must be changed, applications should try to do so when the GPU workload is relatively light, perhaps limiting changes to the start of a command list.

[NVIDIA guidance](https://developer.nvidia.com/dx12-dos-and-donts#worksubmit):

> Make sure to use just one CBV/SRV/UAV/descriptor heap as a ring-buffer for all frames if you want to aim at running parallel asynchronous compute and graphics workloads

[Intel guidance](https://software.intel.com/content/www/us/en/develop/articles/developer-and-optimization-guide-for-intel-processor-graphics-gen11-api.html#inpage-nav-3-1):

> Minimize descriptor heap changes. Changing descriptor heaps severely stalls the graphics pipeline. Ideally, all resources will have views appropriated out of one descriptor heap.

---------------------------

> Since the number of images is not known, the size of the DescritporHeap cannot be determined at the beginning.

Just allocate a bigger one. A lot of people just allocate a CBV/SRV/UAV heap of 1,000,000 descriptors. (IE: [the common limit supported by all D3D12 hardware](https://learn.microsoft.com/en-us/windows/win32/direct3d12/hardware-support).)

Descriptors are pretty tiny (32 bytes each on my system), it's not worth sweating over them. You can shoot for a bit lower if the full 1M makes you itchy.

**Comment by shinji12345** [comment]
Thanks for your response and information.

I will use a bigger descriptor heap.
