### ISSUE TITLE
ImGuiWindowFlags_AlwaysAutoResize does not work properly with Columns.

### ISSUE THREAD

**Issue by atom0s** [ocornut/imgui#734]
If you setup a simple window with columns and add data to them, the window will not resize to the items widths properly and instead cuts things off.

This is what is expected:
![http://i.imgur.com/7BVMRzb.png](http://i.imgur.com/7BVMRzb.png)

And this is the results:
![http://i.imgur.com/CucL5GB.png](http://i.imgur.com/CucL5GB.png)

**Comment by ocornut** [comment]
That isn't supported, Columns currently have no way at all of auto-resizing, they spread over the space they already have and not the contrary.

I'll close this to batch the request along with the big Columns thread #125, they need to be redone and obviously we should aim to have individual columns calculating their individual contents to auto-resize. That would require an initial frame of calculation which is usually what new window do but it may be problematic for column sets appearing within an existing window.
