### ISSUE TITLE
Can't center the "InputInt" text to the center of the widget nor the center of imgui window

### ISSUE THREAD

**Issue by mhoivik** [ocornut/imgui#7344]
### Version/Branch of Dear ImGui:

latest, docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

g++, windows & Linux

### Full config/build information:

Make & g++(my repo should give more info if needed)

### Details:

Hi, i am trying to create a app with ImGui, C++, OpenGL and glfw. The idea is to create a app that picks a number in the range selected by the user in the settingsmenu and create to host Bazaars.
It is still in early development, but you can check it out at: https://github.com/mhoivik/BasarApp/tree/cpp.
Anyway i am trying to get the app to center align, but i face some issues with trying to center the "InputInt" and "InputText" component. I have Google a ton, asked Chat GPT and tried to read the docs.

Your help is apprecated!

**Comment by ocornut** [comment]
It is not supported yet.

**Comment by mhoivik** [comment]
Do you know when it will be?
