### ISSUE TITLE
SDL3/OpenGL3 ImGui InputText not accepting keyboard input

### ISSUE THREAD

**Issue by umpiring** [ocornut/imgui#7345]
### Version/Branch of Dear ImGui:

Version 1.90.4 Branch: Master

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_sdl3.cpp

### Compiler, OS:

MSVC2022, Windows10

### Details:

**SDL3/OpenGL3 ImGui InputText not accepting keyboard input**

I was wondering why my keyboard inputs aren't being inputted in the text box? I am using OpenGL3/SDl3
I have tried applying some fixes but its not working unless Im missing something that is key somewhere. I've tried looking for the reasoning and I'm not sure why this is. I've used Dx11/9 & 12 before but never have had such issue. 

Am I missing anything anywhere? If you need more information let me know and I can provide code snippets but it isn't changed much from the actually ImGui example from the release.

### Minimal, Complete and Verifiable Example code:

```cpp
        SDL_Event event;
        while (SDL_PollEvent(&event))
        {
            ImGui_ImplSDL3_ProcessEvent(&event);
            if (event.type == SDL_EVENT_QUIT)
                done = true;
        }
```

```cpp
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplSDL3_NewFrame();
        ImGui::NewFrame();
        ImGui::SetKeyboardFocusHere();
```
        
```cpp
 ImGui::InputText("File Name", buf, sizeof(buf));
```

**Comment by GamingMinds-DanielC** [comment]
`SetKeyboardFocusHere()` is meant to be called within the scope of an opened window, before submitting the item that should get the focus. Calling it directly after `NewFrame()` will effectively put the focus on an invisible dummy window that basically exists to prevent some potential crashes on user errors (like setting the keyboard focus outside of a window).

**Comment by umpiring** [comment]
> `SetKeyboardFocusHere()` is meant to be called within the scope of an opened window, before submitting the item that should get the focus. Calling it directly after `NewFrame()` will effectively put the focus on an invisible dummy window that basically exists to prevent some potential crashes on user errors (like setting the keyboard focus outside of a window).

Well i added that after and neither way worked, I'm still confused as to why this won't work. DirectX seems just fine...

**Comment by ocornut** [comment]
If I paste this to example_sdl3_opengl3/main.cpp after `NewFrame()` it works:

```cpp
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplSDL3_NewFrame();
        ImGui::NewFrame();

        static char buf[32];
        ImGui::SetKeyboardFocusHere();
        ImGui::InputText("File Name", buf, sizeof(buf));
```

So you have an issue elsewhere or the code causing issue is omitted from your details.

Or it might be due to an issue with SDL3 ?

**Comment by umpiring** [comment]
Issue fixed, found the issue 

It was a bug with my SDL, i was using a version where something wasn't supported and I removed it
