### ISSUE TITLE
Toggling collapsing headers

### ISSUE THREAD

**Issue by Sandwich4780** [ocornut/imgui#7349]
### Version/Branch of Dear ImGui:

Version 1.90.4 WIP

### Back-ends:

imgui_impl_win32.cpp

### Compiler, OS:

Windows 10

### Details:

Is there a way to open/close collapsing headers with other mouse buttons? I'm trying to toggle a collapsing header with right-click but I can't figure out any way to do it. Maybe in the future there could be some sort of field/flag for using other mouse buttons.

**Comment by PathogenDavid** [comment]
Could you explain why you want this behavior? It sounds very non-standard.

There is no built-in way to accomplish this, but you could tweak `TreeNodeBehavior` to pass `ImGuiButtonFlags_MouseButtonRight` to `ButtonBehavior` here:

https://github.com/ocornut/imgui/blob/277ae93c41314ba5f4c7444f37c4319cdf07e8cf/imgui_widgets.cpp#L6297

You'd probably want to add your own flag to `ImGuiTreeNodeFlags_` to enable this behavior since `TreeNodeBehavior` affects more than just `ImGui::CollapsingHeader`.

**Comment by Sandwich4780** [comment]
> Could you explain why you want this behavior? It sounds very non-standard.
> 
> There is no built-in way to accomplish this, but you could tweak `TreeNodeBehavior` to pass `ImGuiButtonFlags_MouseButtonRight` to `ButtonBehavior` here:
> 
> https://github.com/ocornut/imgui/blob/277ae93c41314ba5f4c7444f37c4319cdf07e8cf/imgui_widgets.cpp#L6297
> 
> You'd probably want to add your own flag to `ImGuiTreeNodeFlags_` to enable this behavior since `TreeNodeBehavior` affects more than just `ImGui::CollapsingHeader`.

I want it to behave like that so I can have both a checkbox and a header in one. I'll try your suggested method but anyways ty for the help

**Comment by PathogenDavid** [comment]
> I want it to behave like that so I can have both a checkbox and a header in one.

In that case you might actually be better served by using `ImGuiTreeNodeFlags_AllowOverlap` and `ImGui::SameLine` to put a checkbox on the header. Something like this:

```cpp
static bool CheckableCollapsingHeader(const char* label, bool* v, ImGuiTreeNodeFlags flags = 0)
{
    ImGui::PushID(label);
    bool is_open = ImGui::CollapsingHeader("##CollapsingHeader", flags | ImGuiTreeNodeFlags_AllowOverlap);
    ImGui::SameLine();
    ImGui::Checkbox("##Checkbox", v);
    ImGui::SameLine();
    ImGui::Text("Header"); // (Label submitted as text so the user can click it to toggle the header instead of the checkbox)
    ImGui::PopID();
    return is_open;
}

static void GH7349()
{
    ImGui::Begin("GH-7349");
    static bool toggle;
    if (CheckableCollapsingHeader("Header", &toggle))
    {
        ImGui::Text("Expanded!");
    }

    ImGui::Text("Header %s checked!", toggle ? "is" : "is not");
    ImGui::End();
}
```

Here's what that looks like:

![Screenshot of the above code with the header expanded and the checkbox checked](https://github.com/ocornut/imgui/assets/278957/84ea5fa3-1cff-4d7c-9efe-6a1ea7cfb27f)

(Linking to related issues: https://github.com/ocornut/imgui/issues/6294 https://github.com/ocornut/imgui/issues/2396)

**Comment by Sandwich4780** [comment]
> > I want it to behave like that so I can have both a checkbox and a header in one.
> 
> In that case you might actually be better served by using `ImGuiTreeNodeFlags_AllowOverlap` and `ImGui::SameLine` to put a checkbox on the header. Something like this:
> 
> ```c++
> static bool CheckableCollapsingHeader(const char* label, bool* v, ImGuiTreeNodeFlags flags = 0)
> {
>     ImGui::PushID(label);
>     bool is_open = ImGui::CollapsingHeader("##CollapsingHeader", flags | ImGuiTreeNodeFlags_AllowOverlap);
>     ImGui::SameLine();
>     ImGui::Checkbox("##Checkbox", v);
>     ImGui::SameLine();
>     ImGui::Text("Header"); // (Label submitted as text so the user can click it to toggle the header instead of the checkbox)
>     ImGui::PopID();
>     return is_open;
> }
> 
> static void GH7349()
> {
>     ImGui::Begin("GH-7349");
>     static bool toggle;
>     if (CheckableCollapsingHeader("Header", &toggle))
>     {
>         ImGui::Text("Expanded!");
>     }
> 
>     ImGui::Text("Header %s checked!", toggle ? "is" : "is not");
>     ImGui::End();
> }
> ```
> 
> Here's what that looks like:
> 
> ![Screenshot of the above code with the header expanded and the checkbox checked](https://private-user-images.githubusercontent.com/278957/307669424-84ea5fa3-1cff-4d7c-9efe-6a1ea7cfb27f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTY0MzcsIm5iZiI6MTcwODk5NjEzNywicGF0aCI6Ii8yNzg5NTcvMzA3NjY5NDI0LTg0ZWE1ZmEzLTFjZmYtNGQ3Yy05ZWZlLTZhMWVhN2NmYjI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QwMTA4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2RjNmQ4Y2Q3OGVkNWExY2QzOGY2NzVkNGY1NmNhOWJkZTM5YmYwMDFmMmMxNzNiYmU5ZWIxMjczNGNlY2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0SfdTx88kGvtAl1trEqimUoB0MaaPQ7D1lU6S59UCEs)
> 
> (Linking to related issues: #6294 #2396)

Oh this will work pretty good, I’ll do this instead. Thank you for the help
