### ISSUE TITLE
Icon can not be centered using IconFont

### ISSUE THREAD

**Issue by zhouxs1023** [ocornut/imgui#735]
I used Iconfont for Icon, but compile turn on that Icon can not be centered 
Code as below:

#include "IconsFontAwesome.h"

ImGuiIO& io = ImGui::GetIO();
 io.Fonts->AddFontDefault();

 // merge in icons from Font Awesome
static const ImWchar icons_ranges[] = { ICON_MIN_FA, ICON_MAX_FA, 0 };
ImFontConfig icons_config; icons_config.MergeMode = true; icons_config.PixelSnapH = true;
io.Fonts->AddFontFromFileTTF( fontFile.c_str(), 16.0f, &icons_config, icons_ranges);

// in an imgui window somewhere...
ImGui::Button(ICON_FA_FILE_O, ImVec2(24, 24));

![default](https://cloud.githubusercontent.com/assets/905931/16845395/5600be34-4a1b-11e6-8fdb-c42114d82413.PNG)

**Comment by ocornut** [comment]
Change the size to match default font (~13) and add a pixel offset. Read the README in extra_fonts.
If you merge font the first one define the font height.
