### ISSUE TITLE
Horrible ImDrawList::AddImage Performance

### ISSUE THREAD

**Issue by corgifist** [ocornut/imgui#7351]
### Version/Branch of Dear ImGui:

Version 1.90.4, Branch: docking

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Linux + GCC

### Full config/build information:

```
Dear ImGui 1.90.4 (19040)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=202002
define: __linux__
define: __GNUC__=13
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00008041
 NavEnableKeyboard
 DockingEnable
 DpiEnableScaleFonts
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMoveFromTitleBarOnly
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 3 fonts, Flags: 0x00000000, TexSize: 2048,2048
io.DisplaySize: 1920.00,1011.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 4.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

I'm currently making a timeline for my video editor and I'm using `ImGui::GetWindowDrawList()->AddImage(...)` to draw thumbnails of assets. Drawing 10 of those thumbnails really decreases FPS from 100+ to barely 40. The problem is not in my renderer, because when I disable thumbnail rendering comes back to normal 100-120.

Code for thumbnail rendering is pretty simple:
```cpp
        /* Calculating upperLeft, bottomRight and getting asset pointer (these operations are almost cheap) */
        ImTextureID texID = (ImTextureID) (uint64_t) asset->pboGpuTexture;
        ImGui::GetWindowDrawList()->AddImage(texID, upperLeft, bottomRight);
```

-- EDIT --
I forgot to mention that ImTextureID for all thumbnails in provided screenshots/videos is the same, so ImGui could batch them in some way

### Screenshots/Video:

![Screenshot from 2024-02-26 15-54-25](https://github.com/ocornut/imgui/assets/86985149/dbfdaf11-c41f-4d67-9316-ef6102cd626a)
[Screencast from 2024-02-26 16-04-32.webm](https://github.com/ocornut/imgui/assets/86985149/24f5ec8f-765d-43ed-bb83-44b55cac1b80)

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::Begin("Example Bug");
for (int i = 0; i < 15; i++) {
    ImGui::GetWindowDrawList()->AddImage(someTexID, ImGui::GetCursorScreenPos(), ImGui::GetCursorScreenPos() + ImVec2{100, 100});
}
ImGui::End();
```

**Comment by ocornut** [comment]
I don't believe and see no reason for it to be the cause of your slowdown, unless you used a custom backend which did really unusual things (or unless your underlying OpenGL support was particularly odd)
Your video also doesn't bring any proof since many more state of your apps are changed.

You can confirm that this is or not the cause of your slowdown by using a narrower filter e.g.
```cpp
if (!ImGui::GetIO().KeyShift)
   ImGui::GetWindowDrawList()->AddImage(texID, upperLeft, bottomRight);
```
Press SHIFT and compare performances.

**Comment by ocornut** [comment]
Good to hear. Your software looks nice. It I may, it seems odd that it is called "Electron" when there's a widespread web/ui-on-native stack called Electron, this might confuse some people :)
