### ISSUE TITLE
AddConvexPolyFilled may not effectively fill all types of shapes.

### ISSUE THREAD

**Issue by Cody12gs** [ocornut/imgui#7353]
### Version/Branch of Dear ImGui:

v1.87

### Back-ends:

OpenGL

### Compiler, OS:

macOS

### Details:

I have drawn a path using the AddBezierCurve method with the following points: M 180 314 C 180 314 322 183 322 183 C 322 183 318 257 318 257 C 318 257 137 257 137 257 C 137 257 180 314 180 314. Subsequently, I attempted to fill the path using the AddConvexPolyFilled method.

I have attached screenshots showing the path fill. The first image depicts the actual path I want to display, while the second image demonstrates how the path is being filled in ImGui.

 Could you please provide code that can fill all types of shapes?

Thank you !

### Screenshots/Video:

![Screenshot 2024-02-22 at 2 37 01 PM](https://github.com/ocornut/imgui/assets/161419874/1e87eb8e-f22e-4a61-9b42-db608163c0b0)
<img width="325" alt="Screenshot 2024-02-20 at 5 02 26 PM" src="https://github.com/ocornut/imgui/assets/161419874/2e49dc4c-8449-4c51-8961-c075203dc459">

**Comment by ocornut** [comment]
Concave poly fill is not supported (coincidentally may be soon) but crossing paths won’t be supported. You may want to use a more full-featured vector drawing library to do so.

**Comment by ocornut** [comment]
`AddConcavePolyFilled()` and `PathFillConcave()` should be added in next version (#760)
But as mentioned intersecting shapes won't be supported and are unlikely to be.
![image](https://github.com/ocornut/imgui/assets/8225057/adb62130-cbec-49b2-97ca-50ea1c0284da)

**Comment by GamingMinds-DanielC** [comment]
When you add support for concave polygons, maybe add "only simple polygons (no self-intersections, no holes) can be filled" or something in that direction to the "Primitives"-section of the `ImDrawList` header documentation. Simple polygon is the official geometric term and includes both convex and concave polygons.

**Comment by ocornut** [comment]
Thank you, will do so.

**Comment by ocornut** [comment]
Now added `AddConcavePolyFilled()` and `PathFillConcave()` functions courtesy of @thedmd (see #760)
