### ISSUE TITLE
Drawlist issues when using cimgui-go wrapper + ebiten, possibly stemming from imgui

### ISSUE THREAD

**Issue by damntourists** [ocornut/imgui#7372]
### Version/Branch of Dear ImGui:

i believe cimgui uses the docking branch by default. wrapper i'm using is this one: https://github.com/AllenDang/cimgui-go

### Back-ends:

https://github.com/damntourists/cimgui-go-ebiten

### Compiler, OS:

ubuntu

### Full config/build information:

git clone https://github.com/damntourists/cimgui-go-ebiten.git
cd cimgui-go-ebiten
go run -tags exclude_cimgui_glfw,exclude_cimgui_sdli examples/basic/main.go

### Details:

**My Issue/Question:**

Hi there, I apologize in advance if this is the wrong place to post this! I posted here because I saw a couple other issues that seemed to be similar that occurred in the past and have since been resolved for others. 

I'm currently using AllenDang's cimgui-go wrapper, which shows the following in one of the generated files:
```
//This file is automatically generated by generator.lua from https://github.com/cimgui/cimgui
//based on imgui.h file version "1.90.4" 19040 from Dear ImGui https://github.com/ocornut/imgui
```

I was using this drawlist rendering code as reference, which seemed to work fine with older versions of imgui https://github.com/gabstv/ebiten-imgui/blob/master/render.go#L52 to allow me to render drawlists on a frame rendered with [ebitengen](https://ebitengine.org/). Never encountered any drawlist issues with the version used on gabstv's repository, however the version used there is forked and old. 

Unfortunately, using the same rendering code caused a number of display issues with a more up to date version of imgui which I believe have to do with the cliprect for the scrolling areas. 
![imgui_drawlist_issue](https://github.com/ocornut/imgui/assets/1501643/826253db-aef0-41c6-b850-33cdf10ed484)

In the attached image, I've enabled the debug windows to show the cliprects and you can see that the cyan colored rect for the text exceeds the size of the magenta cliprect. This is also happening with other widgets as well (child scroll areas or hovered items for example) Sometimes they'll be visible outside of the window when scrolling. 
![imgui_drawlist_issue2](https://github.com/ocornut/imgui/assets/1501643/6b01be6f-c842-4897-91ae-b492c94245d8)

Another issue I encountered was with modal dialogs appearing with the dim background covering the modal itself. 
![imgui_drawlist_issue3](https://github.com/ocornut/imgui/assets/1501643/86494bb7-e013-4579-9371-c4b740298cc9)

I am unsure if this has something to do with the wrappers, or if it's underlying code in imgui that is causing issues. 

Any insight would be helpful!

### Minimal, Complete and Verifiable Example code:

```
git clone https://github.com/damntourists/cimgui-go-ebiten.git
cd cimgui-go-ebiten
go run -tags exclude_cimgui_glfw,exclude_cimgui_sdli examples/basic/main.go
```

**Comment by ocornut** [comment]
> In the attached image, I've enabled the debug windows to show the cliprects and you can see that the cyan colored rect for the text exceeds the size of the magenta cliprect. 

That's correct. The cyan rectangle here represent the bounding box of all vertices (maybe it should be made yellow) and the magenta is cliprect indeed.

Your issue is likely that your renderer seems to not be honoring the ImDrawCmd::ClipRect value correctly. Perhaps the `if mask == nil` is always taken. It's difficult to understand what you are doing in the render loop, but it seems like you are trying to software emulate a feature that your GPU and graphics API should provide, and it's likely going to be extremely slow even if it appears to work. It's going to be saner if you figure out a way to actually set that cliprect in the renderer.

**Comment by damntourists** [comment]
Great info! Thanks so much Omar! I'll give that a shot in a bit and let you know how it goes!

**Comment by damntourists** [comment]
> > In the attached image, I've enabled the debug windows to show the cliprects and you can see that the cyan colored rect for the text exceeds the size of the magenta cliprect.
> 
> Nothing wrong with it here. The cyan rectangle here represent the bounding box of all vertices (maybe it should be made yellow) and the magenta is cliprect indeed.
> 
> Your issue is likely that your renderer seems to not be honoring the ImDrawCmd::ClipRect value correctly. Perhaps the `if mask == nil` path is always taken, which ignores ClipRect.It's difficult to understand what you are doing in the render loop, but it seems like you are trying to software emulate a feature that your GPU and graphics API should provide, and it's likely going to be extremely slow even if it appears to work. It's going to be saner if you figure out a way to actually set that cliprect in the renderer.

Also good info! I'll reach out to the ebiten discord and see if anyone has any idea of how to do this.

**Comment by damntourists** [comment]
![imgui_modal_fixed](https://github.com/ocornut/imgui/assets/1501643/bae53ada-81a1-48ee-ad8e-661da5e0fc35)
Your recommendation for `ImDrawCmd::IdxOffset` worked! I'll continue on the cliprect bug and see if I can figure anything out...

**Comment by damntourists** [comment]
I talked with some users in the ebiten discord and got a few pointers. The issue appears to be within these two functions:
```
func getVerticesx32(vbuf unsafe.Pointer, vblen, vsize, offpos, offuv, offcol int) []ebiten.Vertex {
	n := vblen / vsize
	vertices := make([]ebiten.Vertex, 0, vblen/vsize)
	if offpos != 0 || offuv != 8 || offcol != 16 {
		panic("TODO: invalid vertex layout")
	}

	rawverts := (*[1 << 28]cImDrawVertx32)(vbuf)[:n:n]
	for i := 0; i < n; i++ {
		v := ebiten.Vertex{
			SrcX:   rawverts[i].UV.X,
			SrcY:   rawverts[i].UV.Y,
			DstX:   rawverts[i].Pos.X,
			DstY:   rawverts[i].Pos.Y,
			ColorR: float32(rawverts[i].Col&0xFF) / 255,
			ColorG: float32(rawverts[i].Col>>8&0xFF) / 255,
			ColorB: float32(rawverts[i].Col>>16&0xFF) / 255,
			ColorA: float32(rawverts[i].Col>>24&0xFF) / 255,
		}
		vertices = append(vertices, v)
	}
	return vertices
}
... 
func getIndices(ibuf unsafe.Pointer, iblen, isize int) []uint16 {
	n := iblen / isize
	switch isize {
	case 2:
		// direct conversion (without a data copy)
		//TODO: document the size limit (?) this fits 268435456 bytes
		// https://github.com/golang/go/wiki/cgo#turning-c-arrays-into-go-slices
		return (*[1 << 28]uint16)(ibuf)[:n:n]
	case 4:
		slc := make([]uint16, n)
		for i := 0; i < n; i++ {
			slc[i] = uint16(*(*uint32)(unsafe.Pointer(uintptr(ibuf) + uintptr(i*isize))))
		}
		return slc
	case 8:
		slc := make([]uint16, n)
		for i := 0; i < n; i++ {
			slc[i] = uint16(*(*uint64)(unsafe.Pointer(uintptr(ibuf) + uintptr(i*isize))))
		}
		return slc
	default:
		panic(fmt.Sprint("byte size", isize, "not supported"))
	}
}
```

This code came from https://github.com/gabstv/ebiten-imgui/blob/master/render.go#L52, so I am not the original author.  I was going to attempt to update these so that I can pass the clipRect to the function and cull verts from the list that fall outside of the cliprect and adjust the indices accordingly... Does that seem like a reasonable thing to do in my case? I don't believe I have access to scissor operations in this api unfortunately.  Do you happen to know of a better way? I also confirmed that multiple drawtriangle operations get batched and sent to the gpu in ebiten, so hopefully it doesn't slow it down too much..

**Comment by ocornut** [comment]
There’s an image based clipping path in the render loop but you ought to check that it’s indeed taken, it needs a buffer to work as you can see in the code i mentioned in my message above.

Otherwise i honestly think it’d be easier and more reasonable to add clipping to ebiten API.

**Comment by ocornut** [comment]
> I talked with some users in the ebiten discord and got a few pointers. The issue appears to be within these two functions:

To clarify, I don't see any relation between those functions and the issue.

The problematic code in question is likely the code in `render()`:

```go
clipRect := cmd.ClipRect()
texid := cmd.TextureId()
tx := txcache.GetTexture(texid)
vmultiply(vertices, vbuf, tx.Bounds().Min, tx.Bounds().Max)
if mask == nil || (clipRect.X == 0 && clipRect.Y == 0 && clipRect.Z == float32(targetSize.X) && clipRect.W == float32(targetSize.Y)) {
	target.DrawTriangles(vbuf, indices[indexBufferOffset:indexBufferOffset+ecount], tx, opt)
} else {
	mask.Clear()
	opt2.GeoM.Reset()
	opt2.GeoM.Translate(float64(clipRect.X), float64(clipRect.Y))
	mask.DrawTriangles(vbuf, indices[indexBufferOffset:indexBufferOffset+ecount], tx, opt)
	target.DrawImage(mask.SubImage(image.Rectangle{
		Min: image.Pt(int(clipRect.X), int(clipRect.Y)),
		Max: image.Pt(int(clipRect.Z), int(clipRect.W)),
	}).(*ebiten.Image), opt2)
}
```

Where you have a path for image based clipping (slow but functional) and a path without.
Either the image-based clipping is not taken because `mask == nil` (you should verify that) either that path got broken somehow. That's where you should investigate.

**Comment by damntourists** [comment]
Omar, I want to add that I I'm sorry if I wasted your time on this. I understand you're busy and I see now that my issue wasn't even an imgui issue at all. 

I admire your work. Your commitment to those who follow your work is also admirable. Thank you for everything you've done.

**Comment by ocornut** [comment]
Thank you Brett for your kind words. 
Good to hear I could help to solve your issue.
