### ISSUE TITLE
Sliders change unwanted on clicking other slider

### ISSUE THREAD

**Issue by Lulu-Games** [ocornut/imgui#7375]
### Version/Branch of Dear ImGui:

1.90.4

### Back-ends:

IrrImGUI

### Compiler, OS:

MSVC (Windows)

### Details:

Look at code/video

### Screenshots/Video:

[error_w_sliders.webm](https://github.com/ocornut/imgui/assets/128484007/6994bfbf-4d31-49a9-8718-56f9bc7aaf55)

### Minimal, Complete and Verifiable Example code:

```cpp
        static int o_selection=1;
	ImGui::SetNextItemWidth(p(screenSize.Width,68));
	ImGui::SliderInt("", &o_selection, 1, 2, "");

	if(o_selection==1) { ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.0f, 0.0f, 0.0f, 1.0f)); }
	ImGui::Text(translate("Online Multiplayer").c_str());
	if(o_selection==1) { ImGui::PopStyleColor(); } else { ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.0f, 0.0f, 0.0f, 1.0f)); }
	ImGui::SameLine();
	ImGui::SetCursorPosX(p(screenSize.Width,69)-ImGui::CalcTextSize(translate("Local Singleplayer").c_str()).x);
	ImGui::Text(translate("Local Singleplayer").c_str());
	if(o_selection==2){ ImGui::PopStyleColor(); }

	ImGui::SeparatorText(translate("Difficulty").c_str());
	static float difficulty=0.5;
	ImGui::SetNextItemWidth(p(screenSize.Width,68));
	ImGui::SliderFloat("", &difficulty, 0.5f, 10.0f);
```

**Comment by PathogenDavid** [comment]
See this FAQ entry: https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-about-the-id-stack-system

**Comment by ocornut** [comment]
ID must generally be unique as stated in FAQ. You can use "##SomeName" to hide the label. See link posted by David.

**Comment by PathogenDavid** [comment]
Also make sure you have asserts enabled (usually that just means running a debug build instead of release), there's one that would've alerted you to your empty ID mistake:

https://github.com/ocornut/imgui/blob/286cd5bd41e8bf0062a9a5f6373dc1a091fe6ed2/imgui.cpp#L9902-L9905

**Comment by Lulu-Games** [comment]
Ah nice! Thanks the ID is the name?

**Comment by PathogenDavid** [comment]
Yes, but also no. You should read the full FAQ for the details.

The label and the ID are separate concepts. The ID is also influenced by the label, but also by the window which contains the widget. Additionally the visible part of the label isn't used for the ID when using `###`.
