### ISSUE TITLE
GImAllocatorAllocFunc NULL point 

### ISSUE THREAD

**Issue by ccdescipline** [ocornut/imgui#7378]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

windows10 ollvm18   (https://github.com/killvxk/llvm-msvc-ex)

### Details:

When I initialize ImGui in my DLL and call ImGui::CreateContext(), the value of printf(GImAllocatorAllocFunc) is NULL when I use ImGuiContext ctx = IM_NEW(ImGuiContext)(shared_font_atlas); However, I don't encounter this issue when I switch to the MSVC compiler. I'm wondering why this happens or if there's any solution. I would greatly appreciate any advice.
![批注 2024-03-09 140358](https://github.com/ocornut/imgui/assets/32140464/236b0b90-1317-448f-ac2b-3dbb7a7028ed)

### Screenshots/Video:

![批注 2024-03-09 140358](https://github.com/ocornut/imgui/assets/32140464/a2a40477-408e-4549-b569-7d8c9d5558d8)

### Minimal, Complete and Verifiable Example code:

void DX11Hook::initImGui(IDXGISwapChain* dxSwapChain) {
	LogE("initImGui start");

	ID3D11Texture2D* renderTarget = 0;
	ID3D11Texture2D* backBuffer = 0;
	D3D11_TEXTURE2D_DESC backBufferDesc = { 0 };

	//dxSwapChain->GetDevice(__uuidof(ID3D11Device), (PVOID*)&DX11Hook::G_Device);
	VCall(dxSwapChain, 7, __uuidof(ID3D11Device), (PVOID*)&DX11Hook::G_Device);
	LogE("initImGui start2");

	//DX11Hook::G_Device->GetImmediateContext(&DX11Hook::immediateContext);
	VCall(DX11Hook::G_Device, 40, &DX11Hook::immediateContext);

	//dxSwapChain->GetBuffer(0, __uuidof(renderTarget), (PVOID*)&renderTarget);
	VCall(dxSwapChain, 9, 0, __uuidof(renderTarget), (PVOID*)&renderTarget);

	//DX11Hook::G_Device->CreateRenderTargetView(renderTarget, nullptr, &DX11Hook::renderTargetView);
	VCall(DX11Hook::G_Device, 9, renderTarget, nullptr, &DX11Hook::renderTargetView);

	//renderTarget->Release();
	VCall(renderTarget, 2);

	//dxSwapChain->GetBuffer(0, __uuidof(ID3D11Texture2D), (PVOID*)&backBuffer);
	VCall(dxSwapChain, 9, 0, __uuidof(ID3D11Texture2D), (PVOID*)&backBuffer);

	//backBuffer->GetDesc(&backBufferDesc);
	VCall(backBuffer, 10, &backBufferDesc);

	GlobalData::width = backBufferDesc.Width;
	GlobalData::height = backBufferDesc.Height;

	//backBuffer->Release();
	VCall(backBuffer, 2);

	DXGI_SWAP_CHAIN_DESC sd;
	//dxSwapChain->GetDesc(&sd);
	VCall(dxSwapChain, 12, &sd);

	DX11Hook::hwnd = sd.OutputWindow;

	ImGui::CreateContext();

	ImGuiIO& io = ImGui::GetIO();

	FlowerMenu::SetupImGuiStyle();

	//加载字体
	//io.Fonts->AddFontFromFileTTF(E("c:\\Windows\\Fonts\\msyh.ttc"), 15, 0, io.Fonts->GetGlyphRangesChineseFull()); //simhei
	GlobalData::drawfont = io.Fonts->AddFontFromFileTTF(E("c:\\Windows\\Fonts\\msyh.ttc"), 12, 0, io.Fonts->GetGlyphRangesChineseFull());
	//GlobalData::drawfont = io.Fonts->AddFontFromFileTTF(E("C:\\Fonts\\apex_fonts.ttf"), 12, 0, io.Fonts->GetGlyphRangesChineseFull());

	io.MouseDrawCursor = false;
	io.ConfigFlags = ImGuiConfigFlags_NoMouseCursorChange;
	//io.WantSaveIniSettings = false;
	ImGui_ImplWin32_Init(DX11Hook::hwnd);
	ImGui_ImplDX11_Init(DX11Hook::G_Device, DX11Hook::immediateContext);

	LogE("initImGui success");

	//初始化绘制utils
	drawUtils = new IMGuiDrawUtil();

}

**Comment by ocornut** [comment]
Each DLL boundaries will carry a copy of the variables. I would imagine them to be always initialized as specified in imgui.cpp:

```
static ImGuiMemAllocFunc    GImAllocatorAllocFunc = MallocWrapper;
static ImGuiMemFreeFunc     GImAllocatorFreeFunc = FreeWrapper;
static void*                GImAllocatorUserData = NULL;
```

But you may need to `ImGui::SetAllocatorFunctions()` to initialize them yourself (with a copy of MallocWrapper and FreeWrapper as specified in imgui.cpp).
