### ISSUE TITLE
Disabling viewport support on osx on docking branch?

### ISSUE THREAD

**Issue by meshula** [ocornut/imgui#7386]
### Version/Branch of Dear ImGui:

docking, top of tree

### Back-ends:

imgui_impl_osx + imgui_impl_metal

### Compiler, OS:

macOS + clang

### Details:

**My Issue/Question:**

The following code in the latest merge to docking, in the osx init function, is the only accessible way to call `ImGui_ImplOSX_InitPlatformInterface` since the function is declared as static, and it doesn't appear to be called in any other manner.

```
    if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
        ImGui_ImplOSX_InitPlatformInterface();
```

If `ImGui_ImplOSX_InitPlatformInterface()` is not called, one cannot run, as the system quickly asserts that the platform interface function pointers are NULL. It thus seems, possibly, that running without viewports enabled is not supported.

My first naive attempt at fix which simply set the flag in io.Config failed, with many of my docked windows opening as blank native windows. Although this is concerning, my program UI design is explicitly designed for docking and needs to NOT be able to drag ImGui windows out of the main window to begin new platform windows :]. So I wish not to set the `ImGuiConfigFlags_ViewportsEnable` flag at all.

Before I dig too deeply (perhaps there is a window flag I can set to prevent the behavior?), I wanted to know, is the docking branch, on osx, intended to work with the viewports feature disabled?

### Minimal, Complete and Verifiable Example code:

I have not provided a sample, because my question is simply whether 

(1) I must attempt to make my program viewport compatible if I wish to update my copy of the docking branch, or, 

(2) if disabling viewports is expected to work, and I should investigate exposing `ImGui_ImplOSX_InitPlatformInterface` so that I can call it directly.

**Comment by ocornut** [comment]
> If ImGui_ImplOSX_InitPlatformInterface() is not called, one cannot run, as the system quickly asserts that the platform interface function pointers are NULL

Where is that reported? Do you have a callstack?
Running without viewports enabled should be supported by all backends. Normally it should just be a matter of not setting this flag before initializing backends.

**Comment by meshula** [comment]
Here's the stack

```
#4	0x0000000102ea6214 in ImGui::ErrorCheckNewFrameSanityChecks() at /Users/nick/dev/LabExcelsior/LabImGui/imgui/imgui.cpp:10265
#5	0x0000000102ea4304 in ImGui::NewFrame() at /Users/nick/dev/LabExcelsior/LabImGui/imgui/imgui.cpp:4756
#6	0x0000000102d191e4 in +[DearImGui beginFrame:renderPass:commandBuffer:queue:] at /Users/nick/dev/LabExcelsior/LabImGui/dear.mm:287
```

And now that I look at the config flags, I see that the viewport flag *is* set. So the problem is me. Searching my code, I find that I had set the flag in two places and commented it out only in one due to a copy and paste error :(

My apologies for taking up your time, but I appreciate your noting that disabling is expected to work as it caused me to search more thoroughly in my code.
