### ISSUE TITLE
Color Discrepancy Between OpenCV and Photoshop Hue Adjustments

### ISSUE THREAD

**Issue by Cody13rb** [ocornut/imgui#7387]
### Version/Branch of Dear ImGui:

v1.87

### Back-ends:

SDL, OpenGL

### Compiler, OS:

macOS

### Details:

I'm encountering an issue with color while applying a selected hue value to image data using OpenCV. I've implemented the following function:

cv::Mat apply_hue_for_data(cv::Mat &currentImage, float hueFactor) {
    // Create the output image with the same size and type as the current image
    cv::Mat outputImage = currentImage.clone();

    // Separate the alpha channel
    std::vector<cv::Mat> channels(4);
    cv::split(outputImage, channels);
    cv::Mat alpha = channels[3];

    // Convert the image from BGR to HSV
    cv::cvtColor(outputImage, outputImage, cv::COLOR_BGRA2BGR);
    cv::cvtColor(outputImage, outputImage, cv::COLOR_BGR2HSV);

    // Loop through the rows
    for (int y = 0; y < outputImage.rows; ++y) {
        // Loop through the columns
        for (int x = 0; x < outputImage.cols; ++x) {
            // Retrieve the pixel value
            cv::Vec3b &pixelValue = outputImage.at<cv::Vec3b>(y, x);

            // Adjust the hue value
            int hue = static_cast<int>(pixelValue[0]) + static_cast<int>(hueFactor * 179.0f);
            
            // Ensure the hue value wraps around correctly within the 0-179 range
            hue = hue % 180;
            if (hue < 0) {
                hue += 180;
            }
            pixelValue[0] = static_cast<uchar>(hue);
        }
    }

    // Convert the image back to BGR
    cv::cvtColor(outputImage, outputImage, cv::COLOR_HSV2BGR);

    // Merge the alpha channel back
    std::vector<cv::Mat> bgrChannels;
    cv::split(outputImage, bgrChannels);
    std::vector<cv::Mat> bgraChannels = {bgrChannels[0], bgrChannels[1], bgrChannels[2], alpha};
    cv::merge(bgraChannels, outputImage);

    // Return the modified image data
    return outputImage;
}

Here, “currentImage” contains the image data in CV::Mat format, and “hueFactor” represents the applied hue value, which is 50.
However, after applying the hue value, the color doesn't resemble what I see in Photoshop. The first screenshot shows the original image without applying the hue value, while the second screenshot displays the image with a +50 hue value in Photoshop. However, the third screenshot shows the image with a +50 hue value using the above code in ImGui.
How can I adjust the code to make the image appear similar to the one adjusted with a +50 hue value in Photoshop?

Can anyone please help me with the above!
Thank you!

### Screenshots/Video:

<img width="2108" alt="Applying_Hue_Value" src="https://github.com/ocornut/imgui/assets/161587965/485316d8-86ca-40d0-ad0b-7662c02e4c16">

**Comment by GamingMinds-DanielC** [comment]
While ImGui might be the UI library in use in your application, it doesn't have anything to do with your color conversion code, so your question would better be asked in a forum about OpenCV.

That being said, there might be a simple reason for the mismatch. If you interpret RGB data as BGR, this will surely alter the conversion from and to HSV. Try RGB equivalents if available, otherwise swap R and B channels as additional stept before converting to HSV and after converting back from HSV. I'm not familiar with the OpenGL backends, so this is just a guess.
