### ISSUE TITLE
What is that "(?)" item that shows a popup when hovered over?

### ISSUE THREAD

**Issue by zMidair** [ocornut/imgui#7388]
### Version/Branch of Dear ImGui:

Version 1.88

### Back-ends:

n/a

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

I am searching through the ImGui demo but I cant find that "(?)" item that shows you a popup.

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/130979602/16182cf7-ba7b-4a62-aaf7-ca68a344e8d5)

**Comment by ocornut** [comment]
Have you searched for `"(?)"` in the codebase?
You would quickly find this function in imgui_demo.cpp:

```cpp
// Helper to display a little (?) mark which shows a tooltip when hovered.
// In your own code you may want to display an actual icon if you are using a merged icon fonts (see docs/FONTS.md)
static void HelpMarker(const char* desc)
{
    ImGui::TextDisabled("(?)");
    if (ImGui::BeginItemTooltip())
    {
        ImGui::PushTextWrapPos(ImGui::GetFontSize() * 35.0f);
        ImGui::TextUnformatted(desc);
        ImGui::PopTextWrapPos();
        ImGui::EndTooltip();
    }
}
```

**Comment by zMidair** [comment]
For some reason, it says that BeginItemTooltip is not a member of ImGui

**Comment by zMidair** [comment]
Hmm, removing the if always shows the message but when I add the if it doesnt compile with the error:
"a conditional expression of type 'void' is not valid"
