### ISSUE TITLE
Change Text Color and Text Sliders Color Seperate

### ISSUE THREAD

**Issue by S0pex** [ocornut/imgui#739]
Hello,

I implemented imgui into my renderer and using it as my menu.
So i played a little bit with the style and what i am trying to do is change the slivers text color into white but still having my Label Color in Orange.

I found the Text Color but it always the general color of all text, is there any seperated color option ?

Regards Artur

**Comment by ocornut** [comment]
Render the two parts separately, e.g.
SliderFloat("##PlayerDistance"); SameLine(); PushStyleCol(..); Text(); PopStyleCol().

**Comment by theysp** [comment]
Set color and render something and set another color and rend something.
