### ISSUE TITLE
Would it be reasonable for functions that accept text_begin/text_end to allow text_begin equals text_end equals NULL?

### ISSUE THREAD

**Issue by alien-brother** [ocornut/imgui#7391]
### Version/Branch of Dear ImGui:

Version 1.90.4, Branch: master (I guess?)

### Back-ends:

(Unrelated to backends) imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

(Unrelated to compiler and OS) MSVC 2022, Windows 11

### Full config/build information:

Unrelated to configuration

### Details:

I'm looking at `ImDrawList::AddText()`, but there are other functions that accept a text range. The code that handles `text_begin`/`text_end` looks like this:
```cpp
    if (text_end == NULL)
        text_end = text_begin + strlen(text_begin);
    if (text_begin == text_end)
        return;
```
If `text_begin` equals `text_end` equals `NULL`, the code will call `strlen()` on `NULL`. This can reasonably happen when `text_begin` and `text_end` are directly taken from an `std::string_view` as `data()` and `data() + size()`, since a default-constructed `std::string_view` has `NULL` as `data()` as `size()` of `0`. I believe, adding `0` to a null pointer is valid.

Instead, `AddText` (and other functions) could do something like
```cpp
    if (text_end == NULL && text_begin != NULL)
        text_end = text_begin + strlen(text_begin);
    if (text_begin == text_end)
        return;
```

Obviously, the caller can work around this by placing the condition `text_begin != NULL` before the call.

### Minimal, Complete and Verifiable Example code:

```cpp
std::string_view empty_view;
ImGui::GetWindowDrawList()->AddText(ImGui::GetCursorScreenPos(), IM_COL32(0, 0, 0, 0), empty_view.data(), empty_view.data() + empty_view.size());
```

**Comment by ocornut** [comment]
Yes, in this situation I think we can support it, same as #3615

**Comment by ocornut** [comment]
I have pushed the fix for this 37b37fc
And the test: https://github.com/ocornut/imgui_test_engine/commit/a3b029682b8c3654c1c53cd323062fc944d9272c

Thank you!

**Comment by alien-brother** [comment]
Thanks. This helps get rid of some boilerplate code.

**Comment by alien-brother** [comment]
Another existing API that does not allow text_begin == text_end == NULL is `ImFont::CalcTextSizeA()`.
https://github.com/ocornut/imgui/blob/master/imgui_draw.cpp#L3915
