### ISSUE TITLE
Imgui version before using SDL versions higher than 2.0.2

### ISSUE THREAD

**Issue by AnonimiAngels** [ocornut/imgui#7394]
### Version/Branch of Dear ImGui:

Version 1.90.4, Branch: master (master/docking/etc.)

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_sdlrenderer2.cpp

### Compiler, OS:

G++ LINUX

### Details:

I want to know which is the lattest usable version with SDL 2.0.2 of imgui, since mine version of SDL is missing
`SDL_RenderIsClipEnabled`, `SDL_RenderGeometry`, `SDL_ScaleModeLinear`, `SDL_SetTextureScaleMode`, i cant upgrade the sdl version

**Comment by ocornut** [comment]
See the top of imgui_impl_sdlrenderer2 for details.

SDL_Renderer was only recently made capable of rendering dear imgui. However you can use SDL backend without SDL_Renderer if you use another render backend, eg the OpenGL3 backend.

**Comment by AnonimiAngels** [comment]
The machine for witch i need to use sdl_renderer is an embeded os and doesnt have the opengl libraries

**Comment by ocornut** [comment]
You need an api that can render textured triangles. You may use one of the software renderer listed in the wiki as well but it’a not going to be particularly CPU efficient.

**Comment by ocornut** [comment]
Closing this, you’ll find what you need in the wiki.
If you are working on an embedded OS you’ll need to find an adequate solution. If it has a GPU surely there’s a way to render textured triangles, otherwise use a software rasterizer.
