### ISSUE TITLE
Imgui build freezing on win10 but not win11

### ISSUE THREAD

**Issue by rlewkowicz** [ocornut/imgui#7396]
### Version/Branch of Dear ImGui:

v1.90.4

### Back-ends:

imgui_impl_win32.h, imgui_impl_dx11.h

### Compiler, OS:

Windows 11 + MSVC 2022

### Full config/build information:

N/A

### Details:

I have a dx11 frame that I render with imgui more or less using your examples and it works great on my windows 11 laptop. I move it to my windows 10 PC, pre compiled on the windows 10 sdk, and it doesn't work right. And the worst part is it gets a few frames in and freezes. If it didn't work at all I'd have a better starting point. 

I have a console with average frame times, that will scroll for sometime even without rendering so I know the loop is functional. 

I'm sure I'll need more info, but just off the top of your head, have you seen something like this? 

I'm hoping it's like "Ah yeah on win 10, your swap chain numerator for your refresh rate can't be too high" (I did lower it to 120, from 240). 

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/17415445/6ae4fcc3-78a0-4bfd-af9c-f2df0518cf22)

### Minimal, Complete and Verifiable Example code:

N/A

**Comment by ocornut** [comment]
What was your issue Ryan ?

**Comment by ns-rlewkowicz** [comment]
I think it was just a memory leak if I recall. I wasn't releasing the frame.
