### ISSUE TITLE
ImGui Device Not Responding After Fullscreen Application Changes Resolution

### ISSUE THREAD

**Issue by syulen** [ocornut/imgui#7397]
### Version/Branch of Dear ImGui:

Version 1.90.4, Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx9.cpp

### Compiler, OS:

Windows 11 + MSVS 2022

### Details:

**ImGui Device Not Responding After Fullscreen Application Changes Resolution**

I've been working with ImGui for some time now, but today I encountered a new issue that I haven't been able to resolve. Whenever I open a fullscreen application, like a game or any other program that changes my resolution, the ImGui interface in my application becomes unresponsive. The problem occurs specifically when I alt-tab back to my ImGui application from fullscreen mode. It seems to freeze buttons and checkboxes, rendering them unclickable. Strangely, the only thing I can still do is drag my application window around.

I've attempted to debug the issue and tried resetting the device after receiving the WM_DISPLAYCHANGE message, but it appears that this only resets the device when entering fullscreen mode, not when alt-tabbing or exiting out of it.

Has anyone else experienced this issue, and if so, do you know of any solutions to reset the device after exiting fullscreen mode? Any insights would be greatly appreciated. Thank you.

**Comment by GamingMinds-DanielC** [comment]
That's not really an ImGui issue, but a Direct3D issue. When another app enters exclusive full screen mode (emphasis on exclusive), your device is lost. You should get an error when you try to present from your device and need to handle it properly. Take a look at the example sources for reference.
