### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by emoon** [ocornut/imgui#740]
Something that I would think would be great is if dear imgui could adapt Semantic Versioning. Details can be read here: http://semver.org/ but it really boils down to this:

Given a version number MAJOR.MINOR.PATCH, increment the:
1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.

This makes it very clear to people when they take releases on what to expect.

**Comment by ocornut** [comment]
I think it's been already discussed somewhere. I believe it would sort of work with bigger team and roadmap, aka development that's a little more organized. Here it would imply that I aggressively bump versions rather often (which wouldn't be a problem per se but probably a little odd) and/or maintain branches (probably more work) and/or start organizing my priorities a little more strictly which I'm not sure would be really beneficial.? 

Were you bitten by an undesirable MAJOR version change?

I assume your particular wrap-it-all use case is probably more annoyed by my changes than the average :(

**Comment by emoon** [comment]
I had some issues but it hasn't been that bad. Also this style is used through out the whole Rust ecosystem so when a crate (lib) gets updated and you see it's a bump x.x.0 -> x.x.1 you know that it's just a bug fix and you can take it without thinking that much about it while you see there is a 1.x.x -> 2.x.x you will like consider and looking a bit closer.

I really don't think you need to go so far as keeping separate branch and such and development can proceed just the way you do it now. The only thing is that when you release a new version you use the guideline of how the version should be bumped.

It's just a suggestion of course but the version number will communicate "intent" of the scale of changes without needing to actually diff the code.

**Comment by bkaradzic** [comment]
I merge latest ImGui ASAP, in YOLO incremental versioning style. I highly recommend this approach! :)

**Comment by ocornut** [comment]
Is YOLO taking over your desire for semantic versioning? :)

I'm not against but it's probably not something I will adopt until my development schedule becomes less chaotic (perhaps after January).

**Comment by emoon** [comment]
I would really like if this could be done yes.
