### ISSUE TITLE
Random Intermittent Crash - perhaps triggered by imgui reading outside of viewport buffer?

### ISSUE THREAD

**Issue by dgm3333** [ocornut/imgui#7408]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)1.90.5 WIP: direct pull and build of docker branch

### Back-ends:

multiple (definitely glfw_opengl3 and wind32_opengl3

### Compiler, OS:

VS 2022, Win11+10, AMD+Intel PCs

### Details:

For many months I have been having problems with a random infrequent crash which only happens intermittently during normal use (approx every 30 hours of run time)
It seems to be sometimes triggered by user interaction - particularly resizing a window, but will still sometimes happen randomly without any user input.
Switching backends doesn't provide protection.

I've replicated what appears to be the same crash on at least 5 different Windows PCs and given complaints of random crashes it's probably also occuring on others. 

I'm not totally sure if I'm replicating the same bug with my example code (although I think it's likely pretty close), but I think ImGui might be trying to write outside the viewport buffer which then causes a fatal crash.

The minimal example seems to be able to replicate the crash or something similar.

Drag the window outside the main viewport. Grab the resize handle in the bottom corner. Rapidly randomly resize it for a bit. Crash then should trigger

### Screenshots/Video:

There are various screenshots which seem to tie back to the original code.
try/catches provide no protection

I accept that nahimic is in the callstack for this AMD PC, but this is not the problem - the same fault occurs on Intel machines which have never been contaminated with nahimic.
![image](https://github.com/ocornut/imgui/assets/51210/e9f154cf-b40c-4de2-aa66-258e3fc79ea1)

This is the correct view of a test window functioning normally. Just as it crashes is renders incorrectly as below
![image](https://github.com/ocornut/imgui/assets/51210/b6f191bd-5e47-4526-8392-71875d2be030)

This is the final frame rendered just before the crash triggered - the borders on the panel frame are drawing beyond the window borders
![crash 240316b](https://github.com/ocornut/imgui/assets/51210/046df176-ff04-4be7-8e18-75f424408fde)

These are a couple of other crashes under similar circumstances

![240222 opengl crash0 (ai4GP was recieving no active user interaction)](https://github.com/ocornut/imgui/assets/51210/ced7d709-3f8f-43d3-bf8f-78ab058b55e0)

![crash 240316a](https://github.com/ocornut/imgui/assets/51210/1a9b7b86-0197-4835-a7c8-259ca61fade0)

### Minimal, Complete and Verifiable Example code:

//This minimal example seems to be able to replicate it:
//Drag the window outside the main viewport. Grab the resize handle in the bottom corner. Rapidly randomly resize it for a bit. Crash then should trigger
{
    ImGui::Begin("Crashing Window");            //ImVec2 size = ImGui::GetContentRegionAvail();
    ImGui::BeginChild("Child1", ImVec2(-1, -1), ImGuiChildFlags_Border);
    ImGui::Text("This window will crash the application if dragged outside the main viewport then resized rapidly.");
    ImGui::EndChild();
    ImGui::End();
}

**Comment by PathogenDavid** [comment]
> Switching backends doesn't provide protection.

Which backends did you try? The render backend is what most likely matters here, so only changing the platform backend would not affect anything.

> perhaps triggered by imgui writing outside of viewport buffer?

Not entirely sure what gave you the impression this might be the cause. Anything rendered outside the viewport is simply clipped by the GPU.

If you meant rendering outside the main viewport -- we call those secondary viewports. That alone isn't really enough information to be useful, but you can rule that out by not enabling them by omitting `ImGuiConfigFlags_ViewportsEnable` from `ImGuiIO::ConfigFlags` when you're initializing Dear ImGui.

> I accept that nahimic is in the callstack for this AMD PC, but this is not the problem - the same fault occurs on Intel machines which have never been contaminated with nahimic.

As you deduced from the callstack, this crash is happening in Nahimic. There's simply nothing we can do besides recommend you remove it from affected systems, [it's notoriously buggy](https://github.com/ocornut/imgui/issues?q=is%3Aissue+nahimic+).

> These are a couple of other crashes under similar circumstances

Unfortunately you did not enable `Show External Code` in the call stack window here, so it's hard to say for sure. `ig9icd64.dll` is Intel's graphics driver though. Updating graphics drivers may fix it.

> *Third and final example with no identifying text*

This one is also Nahimic.

**Comment by dgm3333** [comment]
Thats a reasonable point - all the development has been done on opengl3.
I'll try directX as it would be a reasonable suggestion that the ImGui opengl3 backend is buggy.

As noted it's not nahimic this time- some of these screenshots happen to be for a PC with nahimic installed but at least one other screenshot is not - ig9icd64.dll is an intel driver!

Obviously updating drivers was the first thing I tried. That didn't work so last month I had my older model i7 replaced with a brand new i5 to test if having a clean intel machine solved the problem - it crashed after running only 8 hours.
I've just purchased a new i7 to see if that helps but that isn't possible across thousands of PCs so we really need a solution which isn't hardware dependent.
The complaints of random crashes occur for users on our beta test site - which is something like 20 other intel machines too - although I would accept that our IT service are managing thousands of machines so they won't update to pre-release drivers - thus the reason for the replacement machine. But it has been going on for many months - so I think an update would have fixed it on either intel or nahimic if it was caused primarily by an error in external drivers.

If you'd like even more screenshots from non-AMD machines I can do when I back at work next week.

I actually don't know what causes it and my apologies for my typo the consistently reported fault is an access violation *reading*, not writing.

**Comment by PathogenDavid** [comment]
> ogl backend is buggy.

I want to emphasize that Dear ImGui's OpenGL backend is rock solid, it's OpenGL drivers and things which mess with them that are buggy.

> As noted it's not nahimic this time- some of these screenshots happen to be for a PC with nahimic installed but at least one other screenshot is not - ig9icd64.dll is an intel driver!

Seeing intermediate stack frames can still point towards something more specific than the driver. (For example the Nahimic bug doesn't actually go bang until `atio6axx.dll`, which is AMD's driver but Nahimic is most likely the actual culprit.)

> I've just purchased a new i7 to see if that helps

I would not be hopeful of this improving anything unless it's also a significantly different generation of Intel graphics. (In which case I'm pretty sure you'd be buying more than just a CPU.)

> so I think an update would have fixed it on either intel or nahimic if it was caused primarily by an error in external drivers.

You think incorrectly. OpenGL drivers have always been a bit of a mess on Windows (it's better now than it used to be, but still not great.)

IIRC `ig9icd64` is used by older for Intel HD graphics which are no longer being updated and haven't been for quite some time.

Nahimic is just bad software in general, its bugginess affects a lot more than just Dear ImGui.

Compounding this is the fact that apps which own multiple OpenGL contexts (like Dear ImGui apps with multi-viewports enabled) are not super common on Windows--as a result these apps exercise rarely used and under-tested code paths within OpenGL drivers and bugs scurry out from their depths.

**Comment by dgm3333** [comment]
Sorry I don't think I'm being clear enough. Nahimic is ONLY installed on *ONE* machine (the other 20 don't have it) so that is NOT the cause.

I think your suggestion it's OpenGL is a much better one though, so I've switched the application to Win32/DX12. The minimal example now isn't crashing almost instantly on my AMD (ie the one *with* Nahimic) so that's progess. I'm still not entirely sure the minimal example is replicating the same issue, but I should hopefully find out whether this cures the random crash over the next week or so.

PS: Don't get me wrong - I'm definitely not trying to insult ImGui or all the amazing work which has gone into it as I absolutely love using it.
The fact that it took me around 30mins to update the application code and switch backends on something developed over many years is reflection of ImGuis strength. And I also now have defines so I can select between glfw,sdl2,win32 and also ogl3,dx12 going forward.

**Comment by PathogenDavid** [comment]
> Sorry I don't think I'm being clear enough. Nahimic is ONLY installed on _ONE_ machine (the other 20 don't have it) so that is NOT the cause.

No worries, I got that! I was just using Nahimic as an example when I mentioned showing the stack frames. Other apps which inject themselves into back buffer presentation has the potential to be problematic as well, and the stack during present is usually where you see them show up.

Glad to hear Direct3D is working out better for you!

**Comment by dgm3333** [comment]
closing as unresolved, but no longer relevant/required and I have no way of assessing the source of the error further.
