### ISSUE TITLE
If I want  cut-outs area inside of window or set some effective area transparent, how should I set？

### ISSUE THREAD

**Issue by zhouxs1023** [ocornut/imgui#742]
Effect as below：
![qq 20160719211720](https://cloud.githubusercontent.com/assets/905931/16951498/d796ae06-4df7-11e6-8cab-c4e9deab991f.png)

**Comment by MINIONBOTS** [comment]
Make 2 windows, attach one below the other...is the only way I can think of that will do what you want.

**Comment by zhouxs1023** [comment]
Can you provide simple code for me?

**Comment by ocornut** [comment]
Why do you want to do that?
You can set the WindowBg color to alpha 0.0 to disable background and display it yourself

**Comment by zhouxs1023** [comment]
Thanks!
