### ISSUE TITLE
How to rename browser's tab?

### ISSUE THREAD

**Issue by deloverzeus** [ocornut/imgui#7423]
### Version/Branch of Dear ImGui:

Version 1.95.0, Branch: docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Linux +gcc

### Details:

How to rename browser's tab
When I run imgui in browser,but the browser's tab always show "Dear ImGui Emscripten example".How to rename it?Thank you

### Screenshots/Video:
![Uploading 20240320085343.png…]()

**Comment by ocornut** [comment]
This is the html page title. Search for that string in your project and change it. This isn’t really a dear imgui question so i must close this.

**Comment by deloverzeus** [comment]
> This is the html page title. Search for that string in your project and change it. This isn’t really a dear imgui question so i must close this.

The html page title always show "Dear ImGui Emscripten example".This isn't my project string.

**Comment by deloverzeus** [comment]
> @deloverzeus since you use `imgui_impl_glfw.cpp`, you can try to use [`glfwSetWindowTitle(window, "My Window");`](https://www.glfw.org/docs/3.3/window_guide.html#window_title) or emscripten function for it: [`void emscripten_set_window_title(char *title)`](https://emscripten.org/docs/api_reference/emscripten.h.html#c.emscripten_set_window_title)

Thank you.
