### ISSUE TITLE
Not an issue, just a perf profiling of InputTextMultiline on 4 million lines of text

### ISSUE THREAD

**Issue by redgpu** [ocornut/imgui#7426]
### Version/Branch of Dear ImGui:

Version 1.77 WIP, version number 17601

### Back-ends:

Custom GLFW+OpenGL backend (it doesn't matter for this issue)

### Compiler, OS:

Windows 10 + MSVC 2019

### Details:

I was giving Dear ImGui a hard time today by feeding to its InputTextMultiline widget some 4 million lines of text, I instrumented the InputTextMultiline's code to visualize where it spends the most time, and turns out the most expensive lines of code (aside from my personal callback one that just counts lines, I know that it's slowish, you can ignore it) are the following three:

![screenshot](https://github.com/ocornut/imgui/assets/96029069/bdcd2825-93df-42f1-bb09-61ce71b923a8)

You can open the .json trace file in any Chrome-based browser by opening a new tab and typing "about:tracing" (without quotes) and hitting Enter, then pressing the Load button and choosing this `dear_imgui_1.77_WIP_v17601_InputTextMultiline_about_tracing_trace.json` file:
[dear_imgui_1.77_WIP_v17601_InputTextMultiline_about_tracing_trace.json](https://github.com/ocornut/imgui/files/14692587/dear_imgui_1.77_WIP_v17601_InputTextMultiline_about_tracing_trace.json)

This is not an issue btw, Dear ImGui is great regardless of anything, because I remember the time before Dear ImGui existed. :)

**Comment by ocornut** [comment]
Thanks for the feedback.

I am aware of this and consider is an issue that inputtextv2 will address by maintaining a line index, however we’d still have the worst case scenario that we need to checksum input data at some point. We may introduce a flag for users to forcefully guarantee no under-the-hood changes while active.

It however seems strange to be profiling a nearly 4 years old version.

**Comment by ocornut** [comment]
I am going to remove those conversions at some point this year :)
