### ISSUE TITLE
Missing right & bottom table outer borders when inside a window without padding (1.90 regression)

### ISSUE THREAD

**Issue by cfillion** [ocornut/imgui#7428]
### Version/Branch of Dear ImGui:

1.90 - 1.90.4, since a34071876f2ddb084e499307723180a51fd45655

### Back-ends:

Tested with example_glfw_metal, example_glfw_opengl3 & custom

### Compiler, OS:

macOS

### Details:

Commit a34071876f2ddb084e499307723180a51fd45655 (1.90) draws the bottom and right borders of tables offset by 1px, beyond the expected area and potentially past the window's clip rect.

They're invisible when the table spans all available space within a child window or a normal window with no padding.

`BeginTable(outer_size = ImVec2(100, 100))` produces a 101x101px table.

### Screenshots/Video:

Invisible/clipped borders:
![Missing borders](https://github.com/ocornut/imgui/assets/4297676/ab2441a7-797c-4d24-b196-fbb3f2d24c58)

1px bigger than child window borders and item frames = invading into window padding and item spacing:
![Inconsistent pixel](https://github.com/ocornut/imgui/assets/4297676/4ce92b4f-6aaf-4387-a23f-becbd35e5c1f)
(Zoomed 3x)

### Minimal, Complete and Verifiable Example code:

```cpp
auto table = [] (ImVec2 size = {}) {
  if(ImGui::BeginTable("table", 2, ImGuiTableFlags_Borders /* with an S */ | ImGuiTableFlags_ScrollY, size)) {
    ImGui::TableNextRow();
    ImGui::TableNextColumn();
    ImGui::Text("Hello, world!");
    ImGui::EndTable();
  }
};

ImGui::Begin("Case 1");
ImGui::BeginChild("child");
table();
ImGui::EndChild();
ImGui::End();

ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0);
ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, { 0, 0 });
ImGui::Begin("Case 2");
table();
ImGui::End();
ImGui::PopStyleVar(2);

ImGui::Begin("Case 3");
ImGui::BeginChild("child", { 0, 16 }, ImGuiChildFlags_Border /* without an S */); ImGui::EndChild();
table({ 0, 24 });
ImGui::Button("Test", { -FLT_MIN, 0 });
ImGui::End();
```

**Comment by ocornut** [comment]
>  if(ImGui::BeginTable("table", 2, ImGuiTableFlags_Borders /* with an S */ 
> ImGui::BeginChild("child", { 0, 16 }, ImGuiChildFlags_Border /* without an S */);

You win :)
https://github.com/ocornut/imgui/commit/0b9adc2c799f5ed6b33fefd7cdb3c68d10751a29

**Comment by ocornut** [comment]
For now I have reverted a3407187 with a131c3e. 
I am trying to work on a better solution as this exhibit other minor visual issues, but I believe this one is more damaging currently.
I'll keep this open until I am satisfied with a solution for #6765 and #3752.

**Comment by ocornut** [comment]
Pushed new fix 864a2bf
Please see https://github.com/ocornut/imgui/issues/6765#issuecomment-2307494861 for details.
Hope it works this time!

**Comment by cfillion** [comment]
Thank you!

**Comment by binaryfox0** [comment]
> BeginTable(outer_size = ImVec2(100, 100)) produces a 101x101px table.
Hello, I think the bug is still there
```cpp
static float table_width = 150.0f;
void DrawWindow()
{
    ImGui::Begin("Window");
    // ImGui::BeginChild("##child", ImVec2(table_width, 0), 0, ImGuiWindowFlags_NoScrollbar);
    ImGui::BeginChild("##child", ImVec2(table_width + 1, 0), 0, ImGuiWindowFlags_NoScrollbar);
    if(ImGui::BeginTable("##table", 2, ImGuiTableFlags_BordersV, ImVec2(table_width, 0)))
    {
        // ImGui::TableSetupColumn("##col1", ImGuiTableColumnFlags_WidthFixed);
        ImGui::TableSetupColumn("##one", ImGuiTableColumnFlags_WidthFixed);
        ImGui::TableSetupColumn("##two", ImGuiTableColumnFlags_WidthFixed);
        // ImGui::TableSetupColumn("##tmp", ImGuiTableColumnFlags_WidthFixed);
        DrawTableContent();
        ImGui::EndTable();
    }
    ImGui::EndChild();
    ImGui::End();
}

```

with `table_width + 1` for child size
![Image](https://github.com/user-attachments/assets/5f9c5441-a292-4ff1-bfb1-975e014e356b)
with `table_width` for child size

![Image](https://github.com/user-attachments/assets/75ac1515-e1f2-4e24-b79e-75377d37819f)
