### ISSUE TITLE
Design rational for requireing a non-empty string as window title

### ISSUE THREAD

**Issue by milasudril** [ocornut/imgui#7434]
### Version/Branch of Dear ImGui:

Version 1.86

### Back-ends:

OpenGL + GLFW

### Compiler, OS:

g++-11, Mint 21.2

### Details:

**My Issue/Question:**
Why is it illegal to use an empty or null string when creating a window?

### Screenshots/Video:

imgui.cpp:5948: bool ImGui::Begin(const char*, bool*, ImGuiWindowFlags): Assertion `name != __null && name[0] != '\0'' failed.

This is annoying. I could understand the no-null requirement, but an empty string should be allowed, or do you do some stuff that require it to have an actual length, such as dividing by its length?

**Comment by ocornut** [comment]
Windows and widgets needs to be identified somehow.

You can use "##anything" as an ID and it won’t show.

The use of empty identifier is answered in the first "Usage" section of the FAQ:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-have-widgets-with-an-empty-label

**Comment by milasudril** [comment]
I thought you didn't have that option, because then I would expect it to return a handle. What if I want a different title than identifier?

**Comment by ocornut** [comment]
You don’t need an handler, but need to store data internally. And also eg in the .ini file.

Your question is answered in that FAQ entry and also in some demos like Examples>Manipulating Window Titles.
