### ISSUE TITLE
Auto-resize functionality with Tables API

### ISSUE THREAD

**Issue by fauder** [ocornut/imgui#7441]
### Version/Branch of Dear ImGui:

Version 1.90.2, Branch: master

### Back-ends:

Magnum Engine with GLFW, using Magnum-Integration[ImGui]

### Compiler, OS:

Windows 10, Visual Studio 2019

### Full config/build information:

```
Dear ImGui 1.90.2 (19020)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1929
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: NULL
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000001
 NavEnableKeyboard
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000A
 HasMouseCursors
 RendererHasVtxOffset
--------------------------------
io.Fonts: 46 fonts, Flags: 0x00000000, TexSize: 2048,2048
io.DisplaySize: 1536.00,800.80
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 1.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

How to get auto-resize working with mostly ImGui::InputXXX() widgets, with the new Tables API?

### Screenshots/Video:

Screenshot of working (Columns API) table implementation:
![image](https://github.com/ocornut/imgui/assets/15929475/39569390-deae-4ec9-90ff-16d83a1e3998)

### Minimal, Complete and Verifiable Example code:

I have a grid of data that I was drawing just fine with the (now legacy) Columns API. However, I can not get it to work correctly with the Tables API, in terms of column sizing.

I attached a screenshot of how the table looks, drawn with the Columns API, working as intended.

### How it works the old way, with the Columns API
This table is drawn inside a Tab, which is inside a Window with flags `ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar`.
At the end of the window's drawing code, I resize it programmatically, with the width info I collect during the frame.
Most cells are drawn with `ImGui::InputXXX()` widgets. Kind of like a spreadsheet.
I draw every cell with `ImGui::PushItemWidth(-1)`.
I also take note of the widest cell's width for every column. After every cell is processed, I do this:
```cpp
void AutoResizeColumnWidths()
{
    for( auto i = 0; i < currentColumnCount; i++ )
    {
	columnWidths[ i ] += 4 * ImGui::GetStyle().FramePadding.x;
	ImGui::SetColumnWidth( -1, columnWidths[ i ] );
	ImGui::NextColumn();
    }
}
```

This works just fine.

However, I can not simulate this behavior with the new Tables API.
Auto calculation of column widths does not seem to be working. I believe that's because `ImGui::InputXXX()` widgets do not report a width value as @ocornut mentions in https://github.com/ocornut/imgui/issues/6979.

This is sub-optimal for my use case but I thought I could get around it as I did with the Columns API; Take note of max. column widths during drawing & draw with PushItemWidth(-1), then finally set all columns' widths one by one, with the max. width info. gathered during drawing.

The problem with this is I could not find a way to set column widths post-humously; From what I gathered looking at the sources, the layout is locked and modification of column width is not permitted after the header row is submitted.

What is the advised route here?

Also, from a design perspective, shouldn't Tables API support input cells too? Most people aiming to create a spreadsheet will suffer from the same problems mentioned imho.

I will produce a minimal working example shortly.

**Comment by fauder** [comment]
I'll edit the main post when I have the MCVE.

**Comment by ocornut** [comment]
Hello,

Without submitting explicit/specific details about what you attempted so it is difficult to help you. Even written in good faith, textual explanations are often ambiguous if not erroneous. It's better to wait for the MCVE exhibiting an issue.

> Auto calculation of column widths does not seem to be working.

What have you tried? It's not clear. Are you measuring the maximum expected width of all submitted values? I don't see what that would be any different between columns and tables.

> The problem with this is I could not find a way to set column widths post-humously; From what I gathered looking at the sources, the layout is locked and modification of column width is not permitted after the header row is submitted.

It's locked for the frame as it should be - same as Columns, but if you modify it it'll be taken into account for the next frame.
Have you tried calling `ImGui::TableSetColumnWidth()` ?

**Comment by fauder** [comment]
I did try `ImGui::TableSetColumnWidth()` but could not get it to work. 

> Without submitting explicit/specific details about what you attempted so it is difficult to help you. Even written in good faith, textual explanations are often ambiguous if not erroneous. It's better to wait for the MCVE exhibiting an issue.
You're completely right and I apologize for the lack of MCVE for the moment. I was pressed for time (and still am) and could not strip code in time to produce the MCVE. I'll get to it ASAP.

**Comment by fauder** [comment]
While trying to produce MCVE, I got it to work 😅

I don't know what I did wrong before but caching max. column widths calculated during a frame and feeding it to `ImGui::TableSetupColumn()` calls the _next_ frame works as intended.

Thank you for your time and for authoring ImGui as well 🤘
Cheers!
