### ISSUE TITLE
Make sure InputText is selected without breaking buttons

### ISSUE THREAD

**Issue by katemonster33** [ocornut/imgui#7444]
### Version/Branch of Dear ImGui:

Version 1.89, Branch: master

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_sdl2renderer.cpp

### Compiler, OS:

Windows, MSVC

### Details:

Using a window with an InputText widget. Window has some other elements and some users use only keyboard. When the window first shows (first frame), I call ImGui::SetKeyboardFocusHere to put focus on the InputText. Some users report that the focus gets lost. I am trying to use ImGui::IsItemFocused() to only call SetKeyboardFocusHere when the item is not focused. That didn't work as expected, so instead I am just continuously calling SetKeyboardFocusHere. However, the user can use a mouse if they like, and the window has buttons defined. I've found that, with this new fix, though the text box keeps the focus as expected, now the buttons don't work.

How can I fix the focus problem without breaking buttons?

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
> Some users report that the focus gets lost. I am trying to use ImGui::IsItemFocused() to only call SetKeyboardFocusHere when the item is not focused. That didn't work as expected

You should solve this problem because that your actual problem. A repro would be helpful, and building one you may understand the nature of your issue. Right now your statement and claim is too vague for us to be able to help without extra details.
You can use the Dear ImGui Debug Log window it may help you understand what is happening.

(PS: If you steal focus every frame buttons won't work, that's expected behavior.)

**Comment by katemonster33** [comment]
Yeah, what you said at the end is basically what I'm getting at with this issue. If I set focus to the InputText every frame that it is unfocused, then buttons will be broken. But at the same time, I feel like my users will complain that the focus ever leaves the input text field. 

In the old UI (this is for Cataclysm: Dark Days Ahead), we were able to draw a text entry field, and without having the focus leave that control, allow users to click buttons with the mouse, then still enter text into the text entry field after the mouse click event. I am trying to have some common way in my code to keep that behavior intact.

**Comment by ocornut** [comment]
> In the old UI (this is for Cataclysm: Dark Days Ahead), we were able to draw a text entry field, and without having the focus leave that control, allow users to click buttons with the mouse, then still enter text into the text entry field after the mouse click event without having to click the text field again. I am trying to have some common way in my code to keep that behavior intact.

Emulating precisely this is currently not simple with our current focusing system and we have an issue for it, so if you want to emulate precisely this, I would move the discussion to #1418.
