### ISSUE TITLE
Image buttons - loop - no response - always false

### ISSUE THREAD

**Issue by petrasvestartas** [ocornut/imgui#7448]
### Version/Branch of Dear ImGui:

Last

### Back-ends:

imgui_impl_OpenGL.cpp

### Compiler, OS:

Windows

### Details:

**My Issue/Question:**

The loop below creates button but `isClicked `is always false. Why?

### Minimal, Complete and Verifiable Example code:

```cpp
for (int i = 0; i < cam_names.size(); i++) //
{
ImGui::PushID(i);
ImGui::SameLine();
int my_image_width = 0;
int my_image_height = 0;
GLuint my_image_texture = 0;
bool ret = LoadTextureFromFile((opengl_globals::shaders_folder + "/icons/" + cam_names[i]).c_str(), &my_image_texture, &my_image_width, &my_image_height);
IM_ASSERT(ret); // Ensure texture is loaded successfully

bool isClicked = ImGui::ImageButton((void *)(intptr_t)my_image_texture, ImVec2(40, 40));

if (isClicked)
{
	opengl_cameras::cam_type = static_cast<opengl_cameras::camera_type>(cam_types[i]);
	opengl_cameras::set_camera(); // Perform action for button click
}
ImGui::PopID();
}
```

**Comment by ocornut** [comment]
Please don't reload a million textures every frames in a loop. It's going to be slow and consume all CPU/GPU resources very fast. You should load them once.

Code as posted should work. You probably have a problem elsewhere. It could just be that your app is essentially frozen by that loading.
