### ISSUE TITLE
Resizing Widgets with SDL and Ogre

### ISSUE THREAD

**Issue by LauraWangQiu** [ocornut/imgui#7453]
### Version/Branch of Dear ImGui:

Version 1.89.8, Branch: master

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11 + MSCV 2022

### Full config/build information:

```
Dear ImGui 1.89.8 (18980)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: _WIN32
define: _WIN64
define: _MSC_VER=1939
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_sdl2
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 14 fonts, Flags: 0x00000000, TexSize: 512,1024
io.DisplaySize: 680.00,480.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**Resizing Widgets with SDL and Ogre:**

Hello there!

First of all, I wanted to mention that my English level is not the best so I'm just making sure that this might conflict the way I want to express my problem.

The context is that we're developing a game engine with SDL and Ogre, and we're integrating ImGui as our UI.
One of our problems is that when resizing the window, it makes a flickery thing with the buttons, texts, etc. It also doesn't resize the interface. 

As you might see in the code attached, we're changing the `DisplaySize` so then, is there anything else we have to take into consideration?

### Screenshots/Video:

![resizing](https://github.com/ocornut/imgui/assets/98849496/b478c082-493d-46b5-a01a-f170d88565d5)

### Minimal, Complete and Verifiable Example code:

```cpp
bool UIManager::handleEvents(const SDL_Event& event) {
    if (event.type == SDL_WINDOWEVENT) {
        if (event.window.event == SDL_WINDOWEVENT_RESIZED) {
            ImGui::GetIO().DisplaySize = ImVec2(windowManager->getWindowW(), windowManager->getWindowH());
            return false;
        }
    }
    if (ImGui_ImplSDL2_ProcessEvent(&event) &&
        (ImGui::IsAnyItemHovered() || ImGui::IsAnyItemActive() || ImGui::IsAnyItemFocused())) {
        // ...
        return true;
    }
    return false;
}
```

**Comment by ocornut** [comment]
Hello,
I don't think this is a dear imgui specific problem. If you were to draw other shapes using OpenGL or Ogre API you are likely to see the same problem. It involves:
- what does windows do during this animation
- is your framebuffer being refreshed during it

Windows notoriously uses a blocking/modal loop when manually resizing or moving Windows, which makes resize by default not look nice. This results in many questions about this (e.g. #5274 #3672 and many many more) but unfortunately it is not within the scope of Dear ImGui to solve. Rather ask on Ogre or graphics programming forums.

> if (ImGui::IsAnyItemHovered() || ImGui::IsAnyItemActive() || ImGui::IsAnyItemFocused())) { return true; }

By the way this is wrong. You should use `if (ImGui::GetIO().WantCaptureMouse) { return true; }` as explained in FAQ and various pieces of documentation.

Cheers.
