### ISSUE TITLE
ImGui resizes itself to git content when setting size to 0.

### ISSUE THREAD

**Issue by SamHoque** [ocornut/imgui#7454]
### Version/Branch of Dear ImGui:

Version 1.90.4, Branch: master

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 11 + CMake (Using Ninja)

### Details:

**My Issue/Question:**

When setting the size of ImGui to 0, 0 using `SetWindowSize` it resizes itself to fit the content, attached a gif, the size should be 0,0 but it resizes itself to make the checkbox visible.

### Screenshots/Video:

![ui framework](https://github.com/ocornut/imgui/assets/30783651/a8d426e6-c45d-4c22-815c-49ffef95f0c9)

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::Begin(name.c_str(), nullptr, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar);
ImGui::SetWindowSize(ImVec2(0, 0));
ImGui::End();
```

**Comment by SamHoque** [comment]
Setting It to `ImVec2(1, 1)` works just fine. I might just use that, if its not possible to completely resize it to 0.

**Comment by SamHoque** [comment]
https://github.com/ocornut/imgui/assets/30783651/4db0c3b5-1545-4f65-81fb-f1172bac58c2

would be nice, if I could get it to resize even smaller, but also adding a lerp to the alpha, it doesn't look half as bad.

**Comment by ocornut** [comment]
Sorry but #1586
