### ISSUE TITLE
How to set the clipboard functions to default ImGui implementation?

### ISSUE THREAD

**Issue by paul-akl** [ocornut/imgui#7455]
### Version/Branch of Dear ImGui:

Version v1.89.9, Branch: docking

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_sdl2.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Details:

**Question:** how to manually set the default implementation for clipboard functions?

**My issue:** application freezes for a short time when using CTRL+C. SDL2 implementation of ImGui uses _**SDL_SetClipboardText**_ as a _**io.SetClipboardTextFn**_ function for setting the clipboard text. However, when multithreading and running ImGui calls on a different thread (non-main thread that created the SDL context), setting the clipboard (i.e. CTRL+C) freezes for around 10 seconds.

Disabling multithreading or commenting out this code in _**imgui_impl_sdl2.cpp**_ fixes the issue:
```cpp
//io.SetClipboardTextFn = ImGui_ImplSDL2_SetClipboardText;
//io.GetClipboardTextFn = ImGui_ImplSDL2_GetClipboardText;
//io.ClipboardUserData = nullptr;
```
What would be the best way to manually set the clipboard functions to default implementation, i.e.:
```cpp
g.IO.GetClipboardTextFn = GetClipboardTextFn_DefaultImpl;    // Platform dependent default implementations
g.IO.SetClipboardTextFn = SetClipboardTextFn_DefaultImpl;
g.IO.ClipboardUserData = (void*)&g;
```
without editing any of the ImGui implementation files. The **_XXXClipboardTextFn_DefaultImpl_** functions are declared in the **_imgui.cpp_** files, so I cannot see a simple way of accessing them.

By the way, if it's of any interest to anyone, the application hangs at this call, in **_SDL_windowsclipboard.c_** file:
```c
int WIN_SetClipboardText(_THIS, const char *text)
{
// ...
EmptyClipboard(); // <- hangs here
// ...
}
```

**Comment by PathogenDavid** [comment]
The easiest route would be to save and restore the clipboard functions before/after the backend initialization. IE:

```cpp
auto defaultSetClipboardTextFn = io.SetClipboardTextFn;
auto defaultGetClipboardTextFn = io.GetClipboardTextFn;
ImGui_ImplSDL2_InitForOpenGL(window, gl_context);
io.SetClipboardTextFn = defaultSetClipboardTextFn;
io.GetClipboardTextFn = defaultGetClipboardTextFn;
```

**Comment by paul-akl** [comment]
> The easiest route would be to save and restore the clipboard functions before/after the backend initialization. IE:
> 
> ```c++
> auto defaultSetClipboardTextFn = io.SetClipboardTextFn;
> auto defaultGetClipboardTextFn = io.GetClipboardTextFn;
> ImGui_ImplSDL2_InitForOpenGL(window, gl_context);
> io.SetClipboardTextFn = defaultSetClipboardTextFn;
> io.GetClipboardTextFn = defaultGetClipboardTextFn;
> ```

That is actually a clever solution, how didn't I think of that. Thank you!

**Comment by PathogenDavid** [comment]
> ClipboardUserData

Oops yeah, that's my bad. Sorry about that! 😅

**Comment by ocornut** [comment]
Also make sure that what you perceive as hanging isn’t some kind of symbol loading performed by the debugger (in which case you may set it up to lazily load symbols on crash only).

**Comment by paul-akl** [comment]
> Also make sure that what you perceive as hanging isn’t some kind of symbol loading performed by the debugger (in which case you may set it up to lazily load symbols on crash only).

Thanks for your input, ocornut!

It wasn't a debuggers fault, as the same hanging is happening when manually running the binary compiled in release mode. In addition, the freezing happens every time the clipboard is accessed, not just the first time after running the program.

Assuming there is no intended way to explicitly access the default clipboard implementation and there is a work-around that I'm happy with, I'll close the issue as resolved 👍
