### ISSUE TITLE
Displaying Directory/Path Tree

### ISSUE THREAD

**Issue by Basavaraj-PN** [ocornut/imgui#7463]
### Version/Branch of Dear ImGui:

Master

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

g++14, Linux os

### Details:

**Displaying Directory Tree**

Basically I want to read directory and display it on the gui window by maintaining  the directory tree structure  and then I want select the file  (as marked in the screenshot below) from tree and drag and drop it.

How can it be achieved ? any example code?

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/23361336/7e19360b-ae42-450f-a3d5-70da709d50c0)

here in the screenshot you can see, I want select the files and then drag and drop.

**Comment by GamingMinds-DanielC** [comment]
Take a look at the demo window that every example shows. Selectables, tree views and drag&drop are all in there, you just need to combine them. You can also take a look at the extensions linked from the main page, specifically this section:
https://github.com/ocornut/imgui/wiki/Useful-Extensions#file-browsers--file-dialog

**Comment by ocornut** [comment]
Note that handling drag and drop in a tree isn't particularly easy (we don't have a full-featured demo for it), and multi-select isn't either. I suggest you investigate this further by implementing a base view without drag and drop, and explore existing demo and resources. Right now your question is too open-ended and suggest you haven't got the bases in. We unfortunately don't have resources to be e.g. teaching people how to read a directory, as this isn't a dear imgui specific question.
