### ISSUE TITLE
main.exe is not compatible with mi pc

### ISSUE THREAD

**Issue by 81937mm** [ocornut/imgui#7466]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Windows 10, g++, Visual studio

### Details:

**My Issue/Question:**

XXX _(please provide as much context as possible)_

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/114319877/0f60f0f4-92fe-4bb1-8c70-5bbc66dad078)
error that appears

https://youtu.be/te29wTao-dA?si=YFqbrHYZjjv6QNFM
tutorial followed

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Sorry that’s a building or debugging setup issue that has nothing to do with dear imgui. Closing.
