### ISSUE TITLE
Difference between backends?

### ISSUE THREAD

**Issue by aidv** [ocornut/imgui#7470]
### Version/Branch of Dear ImGui:

1.90.4

### Back-ends:

win32_opengl3 vs sdl3_opengl3

### Compiler, OS:

Windows11

### Details:

I just need help understanding imgui

### Minimal, Complete and Verifiable Example code:

Can anyone explain to me what the difference is between the different backends, e.g for Windows?

SLD3 vs Win32 OpenGL3, what are the benefits with one over the other?

**Comment by zao** [comment]
Some backends have slightly more features (clipboard, gamepads, multiple viewports, etc.) but they're all reasonably similar in capability.
You would pick a backend and rendering API that fits the application that you want to build and if you do not have any particular preference, pick one that seems most aligned with what you want to build.

**Comment by aidv** [comment]
> Some backends have slightly more features (clipboard, gamepads, multiple viewports, etc.) but they're all reasonably similar in capability. You would pick a backend and rendering API that fits the application that you want to build and if you do not have any particular preference, pick one that seems most aligned with what you want to build.

Great answer. I guess I can change backend later on if and when needed.
