### ISSUE TITLE
是否有办法在使用AddText绘制多行文本时，设置行间距

### ISSUE THREAD

**Issue by kiemz** [ocornut/imgui#7475]
### Version/Branch of Dear ImGui:

v1.90.2

### Back-ends:

example_win32_opengl3

### Compiler, OS:

windows 11 + vs2022

### Details:

**如题:**
如果没有办法，是否可以增加属性，使调用AddText接口绘制多行文本时，修改文本行间距

**Comment by ocornut** [comment]
Hello,
This is not supported yet. See #4742
