### ISSUE TITLE
Noob Issue - Button: visible, hover: works, onclick: always returns: false! 

### ISSUE THREAD

**Issue by Bitefish** [ocornut/imgui#7478]
### Version/Branch of Dear ImGui:

dear imgui, v1.90.5 WIP

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

gcc c++20, ubuntu  64bit, amd ryzen 9

### Details:

My noob issue:

The button  is there, "hover" works, but it always returns false on click.

Minimal running example (on: gcc c++20, ubuntu  64bit, amd ryzen 9): 
https://github.com/Bitefish/mre_tmp

Thank you for helping!

I love ImGui! 

### Screenshots/Video:

![screen_mre](https://github.com/ocornut/imgui/assets/12999947/433fc549-74fe-4636-b0f9-96be60d00f50)

### Minimal, Complete and Verifiable Example code:

```cpp

// main loop // 

ImGui_ImplOpenGL3_NewFrame();
//ImGui_ImplSDL2_NewFrame(window);
ImGui_ImplSDL2_NewFrame();
ImGui::NewFrame();

//std::cout << imgui_window_flags << std::endl;

int width = 0;
int height = 0;

SDL_GetWindowSize(window, &width, &height);
//std::cout << static_cast<float>(width) << "x" << static_cast<float>(height) << std::endl;
window_size = ImVec2(static_cast<float>(width), static_cast<float>(height));

ImGui::SetNextWindowSize(window_size);
ImGui::SetNextWindowPos(window_pos);

ImGui::Begin("IML", &window_active, imgui_window_flags); //


bool check = false;

if (ImGui::Button(ctLabel.c_str(), ImVec2(90,30)) || ImGui::IsItemClicked()) {
  std::cout << "draw.action: " << std::endl;
  check = true;
  txtBox = "clicked it!";
}

if (check) {
  std::cout << "draw.action: TRUE" << std::endl;
}

ImGui::Text(txtBox.c_str());


ImGui::End();
ImGui::Render();
SDL_GL_MakeCurrent(window, gl_context);

//glViewport(0, 0, (int) io->DisplaySize.x, (int) io->DisplaySize.y); // VIDEO? //
glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
glClear(GL_COLOR_BUFFER_BIT);
ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
SDL_GL_SwapWindow(window);
```

**Comment by JustaSimpleUser** [comment]
Where are you expecting the std::cout statements to send the output?

It's because the `check` variable is not `static`.  Also, check the ImGUI comments for IsItemClicked().

**Comment by Bitefish** [comment]
thank you for your reply! the std::cout goes to the console, from which I started the application.
turning the variable static did not help.  the button just seamingly always returns false . 
so the variable cant do much about that.

**Comment by Bitefish** [comment]
slider doesnt work either. I would be so greatful if anybody could look at the loop,  I must be missing sth obvious!

**Comment by ocornut** [comment]
Your event listener is never calling `ImGui_ImplSDL2_ProcessEvent()`.

**Comment by Bitefish** [comment]
Thank you so much!
I cannot tell you how dear Dear ImGui is to me! :)
