### ISSUE TITLE
How to set Framerate?

### ISSUE THREAD

**Issue by alanyangbo** [ocornut/imgui#748]

**Comment by ocornut** [comment]
There's no concept of framerate in ImGui, this is a concept that exists in your application.

There's is `io.DeltaTime` speed that you set before calling NewFrame() where you can tell the time in seconds, which is used for double-click and repeat rates.

PS:
When you ask a question please be mindful that this software and support are given to you and it would be nice to 1) be clear and explicit in your questions, the context and what you are trying to do. 2) be polite and say thank you.

**Comment by alanyangbo** [comment]
Thank you very much for all your help.My english is not good,so sometimes express is not very clear.I am so sorry.Your lib is so good and very helpful for me.Thanks again.
