### ISSUE TITLE
QA. How I can do something when a widget changed its data

### ISSUE THREAD

**Issue by stirwl** [ocornut/imgui#7483]
### Version/Branch of Dear ImGui:

Version 1.89.7, Branch: master

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_vulkan.cpp

### Compiler, OS:

Windows11+MinGW

### Details:

Hello,
I know it is Immediate Mode GUI to draw GUI with data simultaneously for each frame.

I need do someting when a widget changed its data, for example, a InputInt change need cause a light change with some command send.
How can I get this done?

**Comment by ocornut** [comment]
Every widgets returns a bool value when the underlying data has been changed.

```
if (ImGui::SliderFloat(....))
   // do something
```

You may also see Demo->Widgets->Querying Item Status to use functions such as `IsItemEdited()`, `IsItemDeactivatedAfterEdit()` etc.
