### ISSUE TITLE
how to zoom a picture hard edges

### ISSUE THREAD

**Issue by thewoz** [ocornut/imgui#7485]
### Version/Branch of Dear ImGui:

Version 1.90.5, Branch: docking

### Back-ends:

ImGui_ImplGlfw ImGui_ImplOpenGL3

### Compiler, OS:

macOS

### Details:

**My Question:**

I am developing an image viewer and right now I am implementing image zooming.
Right now the code I am using is as follows:

```
 glGenTextures(1, &texture);
 glBindTexture(GL_TEXTURE_2D, texture);
 glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
 glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
 glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
      
 glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, imageRGBA.cols, imageRGBA.rows, 0, GL_RGBA, GL_UNSIGNED_BYTE, imageRGBA.data);
    
 ImVec2 imageSize = ImVec2(imageScale * imageRGBA.size().width, imageScale * imageRGBA.size().height);
    
 ImGui::Image(reinterpret_cast<void*>(static_cast<intptr_t>(texture)), imageSize);
```

what I would like to do is to try to implement something that looks like the more familiar graphics programs.

This is what I get right now:
![Screenshot 2024-04-11 at 14 17 40](https://github.com/ocornut/imgui/assets/907951/03191134-930e-4fce-b628-dfa287a60421)

this what I would like to achieve:

![Screenshot 2024-04-11 at 14 15 53](https://github.com/ocornut/imgui/assets/907951/54ff33ee-59bf-4157-a91c-c44bfd02fb4d)

do you have any suggestions for me?
Thank you very much

**Comment by ocornut** [comment]
This is an OpenGL question, in OpenGL the sampler is stored into texture data.
You may want to change the value fo GL_TEXTURE_MIN_FILTER and GL_TEXTURE_MAX_FILTER to `GL_NEAREST` instead of `GL_LINEAR`. 
Please find resources or ask further questions on graphics programming forums.

**Comment by thewoz** [comment]
Sorry actually you are right.
I was thinking that maybe I was mistaking the approach of how I was using Imgui more than being an OpenGL problem.

**Comment by ocornut** [comment]
In the latest version it is now possible to switch to Point/Nearest sampling in a backend-agnostic way:

```cpp
draw_list->AddCallback(ImGui::GetPlatformIO().DrawCallback_SetSamplerNearest);
draw_list->AddImage(...);
```

See #9378 for details.
