### ISSUE TITLE
Custom ini setting handler saves settings but does not load settings

### ISSUE THREAD

**Issue by Grzegorz2121** [ocornut/imgui#7489]
### Version/Branch of Dear ImGui:

v1.90.5 WIP Docking branch

### Back-ends:

GLEW + GLWF + opengl 3

### Compiler, OS:

mingw, cmake, win10

### Full config/build information:

No problem with that, compiles without an issue. Docking features work as well :D.

### Details:

Hello. I am running basically the demo application with a single window.
I am trying to use a custom ini setting handler to save the content of single ImGui::InputText() widget.
Nothing fancy, no dynamically made windows. I just want to be able to load the saved data on startup and save on shutdown.

I wasnt able to find a complete example of writing to imgui ini file so i have created the best effort solution using other issue.

https://github.com/ocornut/imgui/issues/2564

Problem is that my code is able to save into the user defined key using UserData_WriteAll but the functions UserData_ReadOpen and UserData_ReadLine never fire. I have no idea if that is the initialization problem or if i am lacking another line to make that solution work.

If i move the ini_handler before ImGui::CreateContext() i get segfault. I had though that maybe imgui reads the settings in ImGui::CreateContext() that is why loading does not work but calling ImGui::LoadIniSettingsFromDisk(ImGui::GetIO().IniFilename);
after i init my ini file handler does not work.

I have no idea how UserData_ReadOpen and UserData_ReadLine is supposed to operate so i have tried to debug the window setting handlers but i cant debug them either. (The breakpoints never hit) 
I think i could discover how they work by printing the parameters they get but they never get called.

Help would be greatly appreciated. 

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
glfwSetErrorCallback(glfw_error_callback);
    if (!glfwInit())
        return 1;

    const char* glsl_version = "#version 330";
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);  

    glfwWindowHint(GLFW_RESIZABLE, 1);
    guiref->window = glfwCreateWindow(1280, 720, "Dear ImGui GLFW+OpenGL3 example", NULL, NULL);
    if (guiref->window == NULL)
        return 1;
    glfwMakeContextCurrent(guiref->window);
    glfwSwapInterval(1); // Enable vsync
    
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImPlot::CreateContext();
    imnodes::CreateContext();

    ImGuiSettingsHandler ini_handler;
    ini_handler.TypeName = "UserData";
    ini_handler.TypeHash = ImHashStr("UserData");
    ini_handler.ReadOpenFn = UserData_ReadOpen;
    ini_handler.ReadLineFn = UserData_ReadLine;
    ini_handler.WriteAllFn = UserData_WriteAll;
    ImGui::AddSettingsHandler(&ini_handler);
    
    ImGuiIO & io = ImGui::GetIO();
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard; 
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;

    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
    //io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
    //io.ConfigFlags |= ImGuiViewportFlags_NoAutoMerge;
    ImGui::StyleColorsDark();

    ImGui::LoadIniSettingsFromDisk(ImGui::GetIO().IniFilename);

    ImGui_ImplGlfw_InitForOpenGL(guiref->window, true);
    ImGui_ImplOpenGL3_Init(glsl_version);

    glewInit();
```
```cpp
static void* UserData_ReadOpen(ImGuiContext*, ImGuiSettingsHandler*, const char* name)
{ 
    std::cout << name << "Does not fire" << std::endl; 
    return (void*)"Path";
}

static void UserData_ReadLine(ImGuiContext*, ImGuiSettingsHandler*, void* entry, const char* line)
{
    std::cout << "Does not fire" << std::endl; 
    std::cout << line << std::endl; 
}

static void UserData_WriteAll(ImGuiContext* ctx, ImGuiSettingsHandler* handler, ImGuiTextBuffer* buf)
{
    std::cout << "Fires on exit" << std::endl; 
    buf->appendf("[%s][%s]\n", "User data", "Path");
    buf->appendf("Path=%s\n", "Hello");
    buf->append("\n");
}
```

**Comment by cfillion** [comment]
The string between the first pair of brackets must match the TypeName of your handler: "UserData".

```cpp
buf->appendf("[%s][%s]\n", "UserData", "Path");
```

https://github.com/ocornut/imgui/blob/231cbee0fc4f59dbe5b8b853a11b08dc84e57c65/imgui.cpp#L13602

**Comment by Grzegorz2121** [comment]
Damn, a single space ruins my day once again.
Sorry for the bother.
Thank you for help. Issue closed.
