### ISSUE TITLE
"Hold SHIFT to enable Docking window" tooltip inherits `NextWindowData`

### ISSUE THREAD

**Issue by cfillion** [ocornut/imgui#7491]
### Version/Branch of Dear ImGui:

1.89.9-docking – 1.90.5-docking

### Details:

Since 300464a4878c8ba659807c4d78d95e1357af87b1, `Begin` shows a tooltip when `io.ConfigDockingWithShift` is enabled and the left mouse button is down without moving for >1s.

However it does so before clearing `NextWindowData`, which causes the tooltip to inherit any `SetNextWindowSize` or `SetNextWindowSizeConstraints` and display with an inappropriate size.

Even if it was correctly sized, it is quite surprising to have a tooltip show up in the middle of the window that wasn't intended by the application/tool/script developer: https://i.imgur.com/hGw49go.gif.

### Screenshots/Video:

![Screen capture](https://github.com/ocornut/imgui/assets/4297676/2746e9ab-d01c-49e8-b089-803cdc2dcc29)

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::GetIO().ConfigDockingWithShift = true;

ImGui::SetNextWindowSize(ImVec2(256, 256));
// ImGui::SetNextWindowSizeConstraints(ImVec2(884, 626), ImVec2(2652, 626));
ImGui::Begin("My window");
ImGui::End();
```

**Comment by ocornut** [comment]
Thank you for your report. This should now be fixed with c1743ee
