### ISSUE TITLE
How to create a very big table?

### ISSUE THREAD

**Issue by gegogi** [ocornut/imgui#7494]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_wgpu.cpp

### Compiler, OS:

MSVC 2022, Windows

### Details:

Is there a way to display a table with lots of rows, say 1M ?
Or the more precise question will be: 
Is there a way to feed the only visible range of rows when you know partial range of data to draw?

I could do this in a Qt app as you are given the exact range of rows to draw by callback.
It doesn't seem to be a matter of event-driven or immediate but I wonder whether there is a way to do this.
I'd like to implement a CSV file viewer app which features dynamic data loading and drawing to support handling of very big data.

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
This is well documented in the demo and in many places.
