### ISSUE TITLE
Standalone ImDrawList/ImDrawCmd/Low level renderer API

### ISSUE THREAD

**Issue by bbbbbzzzz** [ocornut/imgui#7495]
### Version/Branch of Dear ImGui:

Version 1.95.5, Branch: master

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Details:

**My Issue/Question:**

Hi, i was wondering is there any chance to get new branch/define for stand-alone low-level ImGui's drawing API? 
I want to use ImGui_ImplXXX_DrawData and ImDrawList to render things, without UI/KeyIO/etc implementation, just renderer.
Thanks!

**Comment by GamingMinds-DanielC** [comment]
If you want to just draw, use `ImGui::GetBackgroundDrawList()` to get your draw list and just draw. If you don't ever submit anything interactive, your linker should be able to throw out the unused stuff. Indroducing new defines for this would needlessly complicate the library for stuff that can already be done.

**Comment by ocornut** [comment]
Also see this example, which requires a call to `NewFrame()` as this setups the `ImDrawListSharedData` instance:
https://github.com/ocornut/imgui/issues/6406#issuecomment-1563002902

Indeed if you don't call much ImGui functions they will be stripped out by the linker, so I agree it's not worth working and maintaining such feature.

You can in theory get rid of even calling any ImGui function e.g. `ImGui::NewFrame()` if you create your own `ImDrawListSharedData` and set it up, but changes to it are internals/undocumented so you would need to do a bit of catch-up with it, easier to call `ImGui::GetDrawListSharedData()`. 
I have now pushed a minor refactor 76bc1b8 to implicitly better document setting up but I would still recommend using the one setup by ImGui.
