### ISSUE TITLE
`TextWrapped` will cause `too-many-vertices` error for long single-line strings

### ISSUE THREAD

**Issue by achabense** [ocornut/imgui#7496]
### Version/Branch of Dear ImGui:

Version 1.90.5

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_sdlrenderer2.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Details:

`ImGui::TextWrapped` and other text functions using wrap-pos settings will cause `too-many-vertices` error when displaying long `single-line` strings.
![image](https://github.com/ocornut/imgui/assets/60953653/6a315b57-eed3-40cd-be29-0471c7d29ae1)
Background: I met this problem when trying to `TextWrapped` the lines `getline`-ed from files. I got the assertion failure after unexpectedly opening a large non-text file (which does not contain `\n`).
Similar issue: #5720

### Screenshots/Video:

The effect for the first example below:
![image](https://github.com/ocornut/imgui/assets/60953653/83a015bc-0b72-491b-b696-e93e565307e5)

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::SetNextWindowSize(ImVec2(300, 50), ImGuiCond_Always);
if (ImGui::Begin("Failed")) {
    std::string long_single_line(20000, 'a');
    ImGui::TextWrapped("%s", long_single_line.c_str());
}
ImGui::End();
```

The problem is not limited to `TextWrapped`. It can affect every text function via wrap-pos settings:
```cpp
ImGui::SetNextWindowSize(ImVec2(300, 50), ImGuiCond_Always);
if (ImGui::Begin("Failed")) {
    ImGui::PushTextWrapPos(200);
    std::string long_single_line(20000, 'a');
    ImGui::TextUnformatted(long_single_line.data(), long_single_line.data() + long_single_line.size());
    ImGui::PopTextWrapPos();
}
ImGui::End();
```

**Comment by ocornut** [comment]
Thanks. I have pushed a mitigation: daecfff

This is a known issue, I don't envision a fuller fix before we replace the text functions (the new WIP text functions don't have this issue). With the mitigation however you are much less likely to encounter the issue, so it may be good enough.

**Comment by ocornut** [comment]
Closing this as I don't expect to fix the current codebase further, but with the mitigation it's more or less not any worse that any other functions.

> the new WIP text functions don't have this issue

Actually I was wrong, they also DID have this issue, but I have managed to fix it in the new text functions (no ETA, sorry) for a negligible cost (one pointer compare per visible wrapped line):
![image](https://github.com/ocornut/imgui/assets/8225057/db7700e6-c3c6-4c46-9358-379bff46db59)
