### ISSUE TITLE
How do I load custom fonts in memory?

### ISSUE THREAD

**Issue by zMidair** [ocornut/imgui#7497]
### Version/Branch of Dear ImGui:

Version 1.88

### Back-ends:

n/a

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

I wanna load a .ttf file in memory. How may I do that?

**Comment by zMidair** [comment]
Also, I wanna make a button with the settings gear logo on it. May I also load the image in the memory somehow?

**Comment by GamingMinds-DanielC** [comment]
Questions like these is what the FAQ is for:
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md

Take a look at the answers to those questions in particular:
- How can I load a different font than the default?
- How can I display an image? What is ImTextureID, how does it work?
