### ISSUE TITLE
PDIRECT3D11

### ISSUE THREAD

**Issue by MrBeefFlavour** [ocornut/imgui#7499]
### Version/Branch of Dear ImGui:

Version 1.90.5 Master

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

wIndows 10

### Details:

PDIRECT3D9 works but im trying to make a Fivem Menu work and i can't find  PDIRECT3D11

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Sorry but #1586
