### ISSUE TITLE
How to get a window handle ?

### ISSUE THREAD

**Issue by zhouxs1023** [ocornut/imgui#750]
Can not get the window handle like Win32-GetHandle() ? as below:

// Create Render Window
bool OgreWidget::CreateRenderWindow()
{
 assert(m_pRoot);
 Ogre::NameValuePairList params;
 params["left"]                 = "0";
 params["top"]                  = "0";
 params["border"]               = "none";
 params["parentWindowHandle"] = Ogre::StringConverter::toString((size_t)(**_HWND)winId()_**);
 string strName  ;
 strName = m_strInsName_.toStdString() ;
 strName += "_Window" ;
 m_pRenderWindow = m_pRoot->createRenderWindow(strName, width(), height(), false, &params) ;
 if(m_pRenderWindow == NULL) return false;
 return true;
}

**Comment by ocornut** [comment]
I don't understand how this question is any related to ImGui.
