### ISSUE TITLE
Unable to use Menu

### ISSUE THREAD

**Issue by BraunSilas** [ocornut/imgui#7502]
### Version/Branch of Dear ImGui:

// dear imgui, v1.90.4, Branch: Master

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_sdlrenderer2.cpp

### Compiler, OS:

Windows 10 + CLion + Bundled MinGW

### Details:

Hey Guys, great libray it has been fun to use!
I have been working on a program using I am Gui and recently I have been implementing a MenuBar(which I turned into a MainMenuBar). Everything worked fine. A couple of days later working on the project and wanted to create a seperate MenuBar for one of my Windows and it suddenly didn't work anymore.
Simplifying the code, I realised it has to do with ImGui::BeginMenu(and End);
regardless weather I try to place a menu int the MenuBar or on its own in the window(oddly not when the menu is inside of MainMenuBar), I receive the following error from ImGui during runtime:
 
"
Assertion failed!
Programm...
File:<_ProjectFolderpath_>/imgui_...ets.cpp
Line:7655

Expression: window->Flags & ImGuiWindowFlags_Popup

For inforamation on how your programm can cause assertion failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)
"
--see first screenshot

I found Line 7655 in imgui_widgets.cpp and it says this:
`void ImGui::EndMenu()
{
    // Nav: When a left move request our menu failed, close ourselves.
    ImGuiContext& g = *GImGui;
    ImGuiWindow* window = g.CurrentWindow;
    **IM_ASSERT(window->Flags & ImGuiWindowFlags_Popup);  // Mismatched BeginMenu()/EndMenu() calls**
    ImGuiWindow* parent_window = window->ParentWindow;  // Should always be != NULL is we passed assert.
    if (window->BeginCount == window->BeginCountPreviousFrame)
        if (g.NavMoveDir == ImGuiDir_Left && NavMoveRequestButNoResultYet())
            if (g.NavWindow && (g.NavWindow->RootWindowForNav == window) && parent_window->DC.LayoutType == ImGuiLayoutType_Vertical)
            {
                ClosePopupToLevel(g.BeginPopupStack.Size - 1, true);
                NavMoveRequestCancel();
            }

    EndPopup();
}`

So it seems to be an issue of mismatching the BeginMenus and EndMenus.

I really don't know what this could be because my code is really simple and I don't even have any other BeginMenu in the code.
Here is the code I am running:
`
#include "imgui.h"
#include "imgui_impl_sdl2.h"
#include "imgui_impl_sdlrenderer2.h"
#include <stdio.h>
#include <SDL.h>

#include "MyLib/Helpers.h"
#include "MCSControl.h"
#include "MyLib/SetUp.h"
#include "MyLib/ProcessInput.h"
#include "MyLib/Update.h"
#include "MyLib/Utilities/FileHandling.h"
#include "MyLib/FinishUp.h"
#include "MyLib/MCSFiles/ToolPoint.h"
#include "MyLib/SDLIMGUIFrame.h"
#include "MyLib/WindowScenes/MainWindow.h"
#include "MyLib/WindowScenes/CalibrateAngleScene.h"
#include "MyLib/WindowScenes/CalibrateRadiusScene.h"
#include "MyLib/WindowScenes/RoutineWindow.h"
#include "MyLib/WindowScenes/SaveCalibrationWindow.h"
#include "MyLib/WindowScenes/CustomRoutineWindow.h"
ImVec2 Size = ImVec2(1000, 1000);
ImVec2 *p_Size;

// Main code
int main(int, char **) {

    SDL_WindowFlags window_flags = (SDL_WindowFlags) (SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_GAMECONTROLLER) != 0) {
        SDL_Log("Error: %s\n", SDL_GetError());}
#ifdef SDL_HINT_IME_SHOW_UI     // From 2.0.18: Enable native IME.
    SDL_SetHint(SDL_HINT_IME_SHOW_UI, "1");
#endif
    window = SDL_CreateWindow("Dear ImGui SDL2+SDL_Renderer example", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                              1280, 720, window_flags);
    if (window == nullptr) {
        SDL_Log("Error: SDL_CreateWindow(): %s\n", SDL_GetError());}
    renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED);
    if (renderer == nullptr) {
        SDL_Log("Error creating SDL_Renderer!");}
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO &io = ImGui::GetIO();
    (void) io;
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;     // Enable Keyboard Controls
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;      // Enable Gamepad Controls
    ImGui::StyleColorsDark();//ImGui::StyleColorsLight();
    // Setup Platform/Renderer backends
    ImGui_ImplSDL2_InitForSDLRenderer(window, renderer);
    ImGui_ImplSDLRenderer2_Init(renderer);//    ImGui::PushStyleColor(ImGuiCol_Button, (ImVec4)ImColor::HSV(203, 0.82f, 0.52f));

    bool Run = true;
    while (Run) {
        Run = processInput_MainWindow();
        update();
        ImGui_ImplSDLRenderer2_NewFrame();
        ImGui_ImplSDL2_NewFrame();
        ImGui::NewFrame();

//Important part -----v-------

        ImGui::Begin("Title", 0, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_MenuBar);

    ImGui::Button("Buttons");
    ImGui::BeginMenu("Menu in window");
    ImGui::EndMenu();

        ImGui::End();

        renderFrame(io);
    }
    closeImGui();
    closeSDL();
    return 0;
}
`
I read in the somewhere that the WindowFlag PopUp was only for internal use but I still tried using it. But it didn't work I got a different Assert Error through that.

I was also suspecting, that my IDE changed something in the includefiles or somehwere else when I refactored something(it has happened before) but I could find anything wrong? Even when comparing it to the v1.90.4 on git.

If there are any questions unanswered please feel free to ask. 
Thank you for your help.

### Screenshots/Video:

<img width="319" alt="IMGUI_Scrrenshot1" src="https://github.com/ocornut/imgui/assets/159521291/d9a48121-d1f8-41e1-a1f1-89d8c4a20767">

**Comment by GamingMinds-DanielC** [comment]
There is a lot of useful documentation (in form of source comments) in the header file itself if you navigate to the function declarations. Small excerpt:
```c++
    IMGUI_API bool          BeginMenu(const char* label, bool enabled = true);                  // create a sub-menu entry. only call EndMenu() if this returns true!
    IMGUI_API void          EndMenu();                                                          // only call EndMenu() if BeginMenu() returns true!
```
In short: your unconditional call to `EndMenu()` is wrong.

**Comment by BraunSilas** [comment]
WOOW, Thank you. I didn't expect it to be this simple. HAHA. 
Well thank you very much for your quick response. 
I'll close this issue now.

**Comment by GamingMinds-DanielC** [comment]
That's not the only thing though. As you can see in the documentation, `BeginMenu()` is for sub-menues only, not for menu bars. A few lines higher in the header you will find the correct functions to use if you want a menu bar (and according to your window flag that seems to be your intention) instead of a sub-menu widget.

Also always a good reference for how things work: `ImGui::ShowDemoWindow()`. That function is there to showcase features and is basically a reference source on how to use them. And it starts with a menu bar.
