### ISSUE TITLE
Drag and Drop from Menubar

### ISSUE THREAD

**Issue by BraunSilas** [ocornut/imgui#7504]
### Version/Branch of Dear ImGui:

v1.90.4 / Main

### Back-ends:

imgui_impl_sdl2.cpp + sdl2renderer.cpp

### Compiler, OS:

Windows 10 + CLion + Bundled MinGW

### Details:

I want to create a drag and drop functionality, where I can go in Menubar and enter a submenu and then drag an object into a child in the window. 

While I was able to drag and drop all kind of Objects in a window I wasn't able to make it work within the Menubar.

Thank you for your help

### Minimal, Complete and Verifiable Example code:

```ImGui::Begin("Custom Routines", 0, ImGuiWindowFlags_MenuBar);//

    ImGui::BeginMenuBar();
    if(ImGui::BeginMenu("Menu")){
        ImGui::MenuItem("Item");
        if (ImGui::BeginDragDropSource(ImGuiDragDropFlags_None)) {
            ImGui::SetDragDropPayload("DND_DEMO_CELL", &taken, sizeof(int));
            SDL_Log("test works");
            ImGui::Text("Swap %s", taken);
            ImGui::EndDragDropSource();
            if (ImGui::BeginDragDropTarget()) {
                if (const ImGuiPayload *payload = ImGui::AcceptDragDropPayload("DND_DEMO_CELL")) {
                    IM_ASSERT(payload->DataSize == sizeof(int));
                        SDL_Log("Droped :%d", taken);
                    }
                }
                ImGui::EndDragDropTarget();
            }
        ImGui::EndMenu();
    }
    ImGui::EndMenuBar();
```

**Comment by ocornut** [comment]
(Note that I added an assert to detect nested `BeginDragDropTarget()`/`BeginDragDropSource()`, but this specific error won't be caught as it is merely in the conditional block)

**Comment by BraunSilas** [comment]
@GamingMinds-DanielC yes you are correct let me fix that. Reading thorugh the documentation and applying your feedback I get get to this code.

`ImGui::BeginMenuBar();
    if(ImGui::BeginMenu("Menu")){
        ImGui::MenuItem("Item");
        if (ImGui::BeginDragDropSource(ImGuiDragDropFlags_None)) {
            ImGui::SetDragDropPayload("DND_DEMO_CELL", &taken, sizeof(int));
            SDL_Log("test works");
            ImGui::Text("Swap %s", taken);
            ImGui::EndDragDropSource();
        }

        ImGui::EndMenu();
    }
    ImGui::EndMenuBar();

    ImGui::BeginChild("drop here");
    ImGui::EndChild();
    if (ImGui::BeginDragDropTarget()) {
        if (const ImGuiPayload *payload = ImGui::AcceptDragDropPayload("DND_DEMO_CELL")) {
            SDL_Log("Droped :%d", taken);
        }
        ImGui::EndDragDropTarget();
    }`

It does run, but I am still not able to begin the DragDropSource.(as in I still don't see a tooltip or the SDL.Log).
Am I making any other mistakes?

**Comment by GamingMinds-DanielC** [comment]
One mistake I see is that you call `ImGui::EndMenuBar()` unconditionally. Everything after `ImGui::BeginMenuBar()` up to and including `ImGui::EndMenuBar()` must be called if and ONLY if `ImGui::BeginMenuBar()` returns true.

That's not why it doesn't work though. I have never tested drag&drop with menu items before, but a quick test suggests that `ImGui::MenuItem()` doesn't support it. Since you can put any type of widget inside of a menu, try replacing your menu item with `ImGui::Selectable()`, that should work.

**Comment by BraunSilas** [comment]
Thank you @GamingMinds-DanielC 
You're the boss!

@ocornut It would be nice for `MenuItem()` to support drag and drop.
Its not a must, since we can exchange it. but it would be convenient and intuitive.
