### ISSUE TITLE
Preventing PopUps from closing when clicking selectables

### ISSUE THREAD

**Issue by xGhostShipIV** [ocornut/imgui#751]
Is it possible in anyway to prevent a non-modal popup menu from immediately closing after clicking a selectable?

**Comment by ocornut** [comment]
For a given Selectable() you can pass it the `ImGuiSelectableFlags_DontClosePopups` flag, however I intend to add a window/popup-wide runtime setting to disable this behavior by default. It's been requested by @MrMarkie in the context of #323 as with gamepad control it may be more desirable to tweak many values from a menu at once.

**Comment by xGhostShipIV** [comment]
Excellent, thank you! I was looking to see if the popups took a flag to disable that feature and consequently missed that it was part of Selectable()
