### ISSUE TITLE
How to make hover highlighting on (many) overlapping InputTexts?

### ISSUE THREAD

**Issue by wolfgang371** [ocornut/imgui#7510]
### Version/Branch of Dear ImGui:

1.89.9 master

### Back-ends:

crsfml, 2.5.3

### Compiler, OS:

gcc/crystal, Ubuntu

### Full config/build information:

```
Dear ImGui 1.89.9 (18990)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
--------------------------------
io.BackendPlatformName: imgui_impl_sfml
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000007
 HasGamepad
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

My main window consists of a spreadsheet-like bunch of cells, mostly `InputText`s. I cannot use the table implementation because I have a lot of custom requirements, e.g. having rather arbitrary cell overlap.
One other requirement is that I want to have `InputText`s change the color when hovered. This is rather straightforward as long as cells don't overlap, but I can't get rid of the glitches when working with overlap (e.g. neighbour cells start to get highlighted in addition).

So far I checked with `SetNextItemAllowOverlap` along with `Dummy`, `InvisibleButton`; I checked with `Group`s, I tested `DrawList`s.
The latter _almost_ solving the issue, if it would let me draw a rectangle after the `InputText`, in between the depth of the window and the `InputText` - but this I also find impossible to achieve (either below the window, on the very top or at least right above the `InputText`).

Any help appreciated!

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
I don't understand your question please showcase a more concrete problem or code.

**Comment by ocornut** [comment]
> Ok, sorry, I should have been more precise. I would like to have an input_text to have a separate hover color, like many other widgets. 

Linking to #3411 for tracking. Indeed `InputText()` doesn't use `FrameBgHovered` currently.

This is very much a [XY Problem](https://xyproblem.info/) here and you seem to have gone quite deep and far into the workaround.

Let's move this to #3411.

**Comment by ocornut** [comment]
I'll close this. Will keep #7515 open as it raises a very specific issue, which is rather complex to solve, but I eventually would like to. I will however lower its priority considering its report is not motivated by a use case that you really need IMHO. Better working on #3411.

**Comment by wolfgang371** [comment]
Thanks for picking it up; but no, not an XY problem (you caught me once on this already ) - this here was the first issue I raised; the others I posted later, because I thought you might be interested in them independently :smile:

**Comment by ocornut** [comment]
Can you clarify? It seems like your issue is to colorize the frame of an `InputText()` when hovered, in which case that should be the first issue to raise?

A slightly saner workaround, for being simple, might be:
```cpp
if (g.HoveredIdPreviousFrame == ImGui::GetID("YourInputText"))
    PushStyleColor(...);
```

**Comment by wolfgang371** [comment]
Hm. I called it "How to make hover highlighting on (many) overlapping InputTexts" and in the first post I also wrote "One other requirement is that I want to have InputTexts change the color when hovered. This is rather straightforward as long as cells don't overlap".

So veeery strictly speaking you say, I should have raised a ticket for general `InputText` hover highlighting. This would probably have resulted in one of my attempts; which all fail for overlapping cases. That's why I included it in the first place...

**Comment by wolfgang371** [comment]
Thanks for your proposal, I will have a look!

> Can you clarify? It seems like your issue is to colorize the frame of an `InputText()` when hovered, in which case that should be the first issue to raise?
> 
> A slightly saner workaround, for being simple, might be:
> 
> ```c++
> if (g.HoveredIdPreviousFrame == ImGui::GetID("YourInputText"))
>     PushStyleColor(...);
> ```

**Comment by wolfgang371** [comment]
The context structure is part of ImGui's internals; I think I don't have access to it via the Crystal wrapper

**Comment by ocornut** [comment]
> Hm. I called it "How to make hover highlighting on (many) overlapping InputTexts" and in the first post I also wrote "One other requirement is that I want to have InputTexts change the color when hovered. This is rather straightforward as long as cells don't overlap".
> So veeery strictly speaking you say, I should have raised a ticket for general InputText hover highlighting. This would probably have resulted in one of my attempts; which all fail for overlapping cases. That's why I included it in the first place...

Can you provide more context and images about your use case, in term or when and how you need to overlap?

I am not sure how to would trivially achieve an excel like setup with e.g. merged cell. I assume it should be possible but honestly I'd recommend implementing the whole thing as one custom canvas/widget and then submitting e.g. `InputText()` only when something is edited. Closer to what I did here: https://github.com/ocornut/imgui/issues/7424#issuecomment-2066922973

> The context structure is part of ImGui's internals; I think I don't have access to it via the Crystal wrap

🤷

**Comment by wolfgang371** [comment]
> > Hm. I called it "How to make hover highlighting on (many) overlapping InputTexts" and in the first post I also wrote "One other requirement is that I want to have InputTexts change the color when hovered. This is rather straightforward as long as cells don't overlap".
> > So veeery strictly speaking you say, I should have raised a ticket for general InputText hover highlighting. This would probably have resulted in one of my attempts; which all fail for overlapping cases. That's why I included it in the first place...
> 
> Can you provide more context and images about your use case, in term or when and how you need to overlap?

Ok, not sure if you will gain something from it, but here you go: this is a 3x3 matrix, all cells equal size, but scrolled to an overlapping state. You will see several glitches here (frame glitch with missing highlighting, overlapping highlighting of two or four cells):
![imgui-hover-issue](https://github.com/ocornut/imgui/assets/71232437/34499dc3-d390-4010-ae0d-fc9f38c34a0f)
 
> I am not sure how to would trivially achieve an excel like setup with e.g. merged cell. I assume it should be possible but honestly I'd recommend implementing the whole thing as one custom canvas/widget and then submitting e.g. `InputText()` only when something is edited. Closer to what I did here: [#7424 (comment)](https://github.com/ocornut/imgui/issues/7424#issuecomment-2066922973)

Merged cells currently I don't support (yet). Thanks for the link, you're dynamically switching between `Selectable` and `InputFloat`, I see.

> 
> > The context structure is part of ImGui's internals; I think I don't have access to it via the Crystal wrap
> 
> 🤷

Sure...

**Comment by wolfgang371** [comment]
I'm pretty much done with my implementation, the only thing left for the time being is the overlap thing. I'll leave it for the time being.
I was thinking about using tables but then gave up the concept since I need (1) clipping in both dimensions, (2) a very flexible column/row fixing and (3) for it to work on a sparse data structure, just to name a few topics. Also, standard drag-and-drop didn't work out for me, in the picture you actually see my own version of it.

**Comment by wolfgang371** [comment]
> > > 🤷
> > > Sure...
> 
> I mean, I would encourage you to see if you can allow exposing more in your language, or at least allow a path for custom exposure of the data you need via a custom helper C function?

Actually I'm still waiting on @oprypin supporting your newest version on Crystal (hi!); maybe there's even some support for the ImGui internals I'm not aware of...
And I'm stubbornly refusing getting back to C++; I had two projects in the past, all started in C++ and I switched the first one to Digital Mars D, the second one to Crystal - and since the latter I was never happier! :smile: But, of course, that's just me.
