### ISSUE TITLE
SDL3 SDL_KeyCode no longer an enum

### ISSUE THREAD

**Issue by ryanriccio1** [ocornut/imgui#7512]
### Version/Branch of Dear ImGui:

Version: latest commit, Branch: master

### Back-ends:

imgui_impl_sdl3.cpp + imgui_impl_sdlrenderer3.cpp

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

**My Issue/Question:**

Since the SDL_KeyCode enum no longer exists (libsdl-org/SDL@70ce808c090fdaf5d98ce3fc8273bcb115427de1), non-alphabetical keyboard inputs are not properly forwarded to ImGui. Things like arrow keys, backspace, etc. no longer work with InputText widgets. My temporary fix was to modify the binding in the backend from `event->key.keysym.sym` to `event->key.keysym.scancode`, not sure what else this might break though. Looking for suggestions for a permanent fix.

**Comment by ocornut** [comment]
I have updated to latest SDL3 and couldn't reproduce your issue. Our SDL3 example seem to be still work.

**Comment by ryanriccio1** [comment]
Ah rookie mistake on my part. I had updated SDL3 submodule but my toolchain never successfully rebuilt the .dll, so I was linking to the wrong lib.
