### ISSUE TITLE
Dummy does not respect SetNextItemAllowOverlap

### ISSUE THREAD

**Issue by wolfgang371** [ocornut/imgui#7516]
### Version/Branch of Dear ImGui:

1.89.9 master

### Back-ends:

crsfml, 2.5.3

### Compiler, OS:

gcc/crystal, Ubuntu

### Details:

Below code produces something like this when e.g. moving down (bad):
```console
80, hover on top dummy
81, hover on top dummy
82, hover on top dummy, hover on bottom button
83, hover on top dummy, hover on bottom button
```

### Minimal, Complete and Verifiable Example code:

```crystal
pos = ImGui.get_cursor_pos
ImGui.set_next_item_allow_overlap # important; ignored for dummy
ImGui.dummy(ImVec2.new(50.0,50.0)) # important
# ImGui.button("##button5", ImVec2.new(50.0,50.0)) # works (respects set_next_item_allow_overlap)
h1 = ImGui.is_item_hovered
pos.y += 15
ImGui.set_cursor_pos(pos)
ImGui.button("##button6", ImVec2.new(50.0,50.0))
h2 = ImGui.is_item_hovered
puts [ImGui.get_frame_count, h1 ? "hover on top dummy" : nil, h2 ? "hover on bottom button" : nil].reject(&.nil?).join(", ")
```

**Comment by ocornut** [comment]
`SetNextItemAllowOverlap()` only makes senses for items which are interactive.
So I indeed i would say that works as intended.
Any button over a dummy would always work regardless of using `SetNextItemAllowOverlap()`  or not.

Can you clarify what's your actual real problem you are trying to solve?

(As I cannot run your code and it would take a bit of time to convert it to C++, it may be easier for comprehension if you submit screenshots or gif along with your code, thank you!)

**Comment by wolfgang371** [comment]
Hi @ocornut,
thanks again. Actually, most of the (minor) issues I reported these days are linked to #7510 - my actual problem (which I couldn't solve, but encountered some other glitches along the way trying to do so).
`Dummy` is not interactive, but hoverable, that's why I had a look at it when trying to solve my initial issue - seemed to be the best fit for that purpose. But `Dummy` ignores `SetNextItemAllowOverlap`, and for the other widgets it works either "all" or "none" (using it vs. not using it), which makes this approach fail.
