### ISSUE TITLE
Edit ImGui's Window Title to add a button

### ISSUE THREAD

**Issue by luis605** [ocornut/imgui#7518]
### Version/Branch of Dear ImGui:

1.90.5, Branch: docking

### Back-ends:

rlImGui

### Compiler, OS:

G++; Linux Mint

### Details:

**My Issue/Question:**

I'm trying to add a button next to the title of a Dear ImGui window, but I'm unable to achieve this directly using the provided functions.

Steps to Reproduce:

    1. Attempt to add a button next to the title of a Dear ImGui window using the available functions.
    2. Notice that the button appears below the title instead of next to it.

Expected Behavior:
I expect to be able to place a button directly adjacent to the title of a Dear ImGui window, similar to the functionality commonly seen in user interfaces.

Actual Behavior:
The button appears below the title of the window, rather than next to it.

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
    ImGui::SameLine(ImGui::GetWindowWidth() - ImGui::GetTextLineHeight());
    if (ImGui::Button("+"))
    {
        // Button action
    }

ImGui::End();
```

**Comment by ocornut** [comment]
This strategy anyhow won't work with docked windows.
Also see #5115 #5449 #3882 no need to open a duplicate issue.

I am planning to work on a way to do that easily with an API, before 1.91, but it might take a few months.
