### ISSUE TITLE
ImGui not using the entire screen surface with Android NDK

### ISSUE THREAD

**Issue by Sandra-Schr** [ocornut/imgui#7521]
### Version/Branch of Dear ImGui:

Version 1.90.4, Branch: master

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

GCC, Android

### Details:

Hi,
i use the AGDK with the game controller example code successfully. As you know, the example is based on ImGui.
In this context I see the following incorrect behavior: The entire display size is not used.

Repo with the game controller example:
[https://github.com/natetrost/games-samples/tree/main/agdk/game_controller](https://www.google.com/url?q=https://github.com/natetrost/games-samples/tree/main/agdk/game_controller&sa=D&source=buganizer&usg=AOvVaw0VHoYhEbZDug-J272A6WYT)

The current ImGui version (1.90.4) is used:
[https://github.com/ocornut/imgui](https://www.google.com/url?q=https://github.com/ocornut/imgui&sa=D&source=buganizer&usg=AOvVaw2ZsHDol3SEO3SGVp3m1QaH)

In the method NativeEngine::PrepareToRender(), the display size is still correctly passed to the ImGui manager:
--> File native_engine.cpp, line 546
      // Keep the ImGui display size up to date
          mImGuiManager -> SetDisplaySize(mSurfWidth, mSurfHeight, mScreenDensity);

For a Samsung Tab S7, for example, 1600x2560 pixels.

However, this area is not used, but a space of around 150 pixels is always left free on the right edge of the screen (see screenshot).
This behavior is observed on many devices and in the Android Studio Emulator.
The behavior affects at least Android versions 11-14.

### Screenshots/Video:

[
![Screenshot_20240409](https://github.com/ocornut/imgui/assets/150257230/1e446e83-1486-4c6e-a01f-eb38ad772bf2)
](url)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Please fill in the template and specify which backend you are using. Presently we have no idea if the issue is in your code or ours.

**Comment by ocornut** [comment]
I answered my questions by digging in your links:
https://github.com/natetrost/games-samples/blob/main/agdk/game_controller/app/src/main/cpp/imgui_manager.cpp#L51

Sorry but that's not our code so it's not a problem within the scope of dear imgui.
