### ISSUE TITLE
Strange endian behaviour causing ImU32 colors to be flipped

### ISSUE THREAD

**Issue by avetharun** [ocornut/imgui#7525]
### Version/Branch of Dear ImGui:

Version v1.90.5 (unchanged)

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11 + MSVC using Visual Studio 2022

### Full config/build information:

```
Dear ImGui 1.90.5 (19050)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1938
define: _MSVC_LANG=202002
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1920.00,1009.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**
When using pure hex codes for various ImU32 -> ImColor operations, the byte order gets swapped.

This issue persists regardless of using x86 or x64

I used the cppreference example for endian-checks, and it *says* it's using little-endian, however in this specific use case, the colors get their byte order swapped. ImGui's default colors don't change.

File for my example can be found at https://gist.github.com/avetharun/2916e0d02abfd08a9bb7d48e06685673

### Screenshots/Video:

Code for button in following image:
```cpp
ImGui::ColorButton("TEST", ImGui::ColorConvertU32ToFloat4(0x000000ff));
```
![image](https://github.com/ocornut/imgui/assets/80366076/3dab7d9f-8552-4b37-b5a7-ad3851b0406c)
![image](https://github.com/ocornut/imgui/assets/80366076/0b9a2297-ba16-415a-9a19-d1a795f0c92e)
![image](https://github.com/ocornut/imgui/assets/80366076/de4df74a-b8f9-4ce4-b80c-29cbf118e1a2)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
// In test window, provided by example:

ImGui::ColorButton("TEST", ImGui::ColorConvertU32ToFloat4(0x000000ff));


ImGui::End();


// Elsewhere (after rendering everything else)


// What should happen: a fully black rect
// What actually happens: nothing displays (except when I add a slight amount of color. This is done for debugging and the issue posted)
// (0xAABBGGRR is what ImGui/GL3 sees)
ImGui::GetForegroundDrawList()->AddRectFilled({ 0,0 }, { 128,128}, 0x0c0000ff, 0);
// However, the following creates a black rect:
// (0xAABBGGRR is what ImGui/GL3 sees)
ImGui::GetForegroundDrawList()->AddRectFilled({ 255, 0 }, { 512, 512 }, 0xff000000, 0);

```

**Comment by avetharun** [comment]
Full solution + project is uploaded to [avetharun/cwe](https://github.com/avetharun/cwe)

**Comment by avetharun** [comment]
In other projects using the same (or very similar) code, this issue has never presented itself.

**Comment by GamingMinds-DanielC** [comment]
That has nothing to do with endianess, this is just the difference between ARGB and ABGR formats (or BGRA/RGBA depending on perspective).

**Comment by avetharun** [comment]
Thats why I closed it. Just strange issue that hasn't appeared on other
platforms (namely android)

**Comment by ocornut** [comment]
We have a `IM_COL32()` macro you can use to clear the ambiguity:
```cpp
ImGui::ColorButton("TEST", ImGui::ColorConvertU32ToFloat4(IM_COL32(255, 0, 0, 0)));
```

Traditionally and on the web when we display an hex color it is always displayed as `#RRGGBBAA` regardless of internal storage.
