### ISSUE TITLE
Dealing with the glfw window 

### ISSUE THREAD

**Issue by gkolll** [ocornut/imgui#7529]
### Version/Branch of Dear ImGui:

Version 1.9.0, Branch: Docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 10 + Mingw64

### Details:

**My Issue/Question:**
The DearImGui window is not dockable to the "main" glfw window (GLFWwindow* window = glfwcreateWindow(....)).
It is standing out from rest of the window (not in a good way). And it is appearing as seperate window (of the same app) in the task bar.

Is there any way to dock the DearImGui windows to it? Or is it just removed somehow?
Cause I haven't seen any screenshots where it is visible. 

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/168035383/b590e32c-e362-4237-ad94-409c342fd0a5)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by PathogenDavid** [comment]
> Is there any way to dock the DearImGui windows to it?

Use `DockSpaceOverViewport`. You can try it in the demo under Examples > Dockspace.

> Or is it just removed somehow?

Removing the main viewport isn't currently supported. See https://github.com/ocornut/imgui/issues/3680

**Comment by gkolll** [comment]
> Use `DockSpaceOverViewport`. You can try it in the demo under Examples > Dockspace.
thank you, got it.
![image](https://github.com/ocornut/imgui/assets/168035383/72bea71b-1f1e-48c6-854f-1d4d79d4226d)

**Comment by gkolll** [comment]
> There are also configuration flags to configure if you want secondary viewports to appear in the taskbar.

Good to know. I'll keep that in mind for future.
