### ISSUE TITLE
Instantiating imgui from within WinMain entry point

### ISSUE THREAD

**Issue by valera-rozuvan** [ocornut/imgui#753]
Maybe someone can point me to an example of how to integrate **imgui** into an existing Windows API program. I am creating a standard MS Window by defining [WinMain](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633559(v=vs.85).aspx), and then proceeding to use [CreateWindow](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632679(v=vs.85).aspx) function. I want to have **imgui** content inside the window I create. Has someone done such a thing before?

**Comment by ocornut** [comment]
Your question is misunderstanding the role and position of dear imgui. WinMain/CreateWindow have nothing to do with it.

_"ImGui outputs vertex buffers that you can render in your 3D-pipeline enabled application."_

ImGui requires rendering textured polygon so you either need a library like OpenGL or DirectX (or any high-level 3d/game engine) rendering over your window. You might get away with using old GDI api for drawing triangles but it very probably won't be fast enough. You generally want to aim to have OpenGL or DirectX setup in your app. You can follow any tutorial for those API or use a library such as GLFW to make it easer to create a window with an OpenGL context.
