### ISSUE TITLE
OpenGL backend + OpenCascades: black screen is shown. 

### ISSUE THREAD

**Issue by notalfredo** [ocornut/imgui#7532]
### Version/Branch of Dear ImGui:

Version 1.90.5, Branch: master

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Linux (mint) + GCC

### Details:

**(glfw) OpenCascade and ImGui. ImGui + OpenCascade Code code compiles and executes without errors, but black screen is shown.**

Hello I am trying to use OpenCascade (open-source software development platform for 3D CAD, CAM, CAE etc...) with ImGui. Anytime I try and have the two in the same application I get a black screen. (I am super unsure how to approach the problem)

I am able to compile and run the [_**Open cascade GLFW example**_](https://github.com/Open-Cascade-SAS/OCCT/tree/master/samples/glfw) just fine.

I was able to compile and run the Dear im gui example in `/examples/example_glfw_opengl3` and it ran successfully. 

The issue comes up when I try and combine the two together. 

First I found this [OpenCascade IMGUI example](https://github.com/eryar/OcctImgui.git). The example had a build config file that was made for windows machines, I did a little toying around and got it compile on my linux machine. But when I tried to execute the program it executed just fine (meaning no errors) but I just got a black screen. Now at this point I was not sure if the black screen was due to me changing the build file or something with my machine. I decided to build a minimal viable product on my own.

In my search I found this [**Open cascade forum post (regarding imgui + occt)**](https://dev.opencascade.org/content/using-opencascade-dear-imgui-and-glfw) which had solved [this persons issue](https://github.com/ocornut/imgui/discussions/5968) #5968 . I felt like this was promising so I decided to look further into this forum post.

This is what I experienced when I followed the [first pose](https://dev.opencascade.org/content/using-opencascade-dear-imgui-and-glfw) (meaning just following what the person did in the original post not taking into consideration the replies yet)

NOTE: We are building off this [open cascade example](https://github.com/Open-Cascade-SAS/OCCT/tree/master/samples/glfw)

//Changed my main routine to this 
```c++ 
void GlfwOcctView::run()
{
  initWindow (800, 600, "glfw occt");
  initViewer();
  initDemoScene();
  if (myView.IsNull())
  {
    return;
  }

  myView->MustBeResized();
  myOcctWindow->Map();
  initUI();
  mainloop();
  cleanupUI();
  cleanup();
}
```
Added these new functions
```c++
void GlfwOcctView::initUI()
{
    // Setup Dear ImGui context
    const char* glsl_version = "#version 330";
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();    
    // Setup Platform/Renderer bindings
    ImGui_ImplGlfw_InitForOpenGL(myOcctWindow->getGlfwWindow(), true);
    ImGui_ImplOpenGL3_Init(glsl_version);
    // Setup Dear ImGui style
    ImGui::StyleColorsDark();
}

void GlfwOcctView::processUI()
{
    // feed inputs to dear imgui, start new frame 
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();
    
    ImGui::Begin("STEP files");   
    
    ImGui::Button("Add File");
    ImGui::SameLine();
    ImGui::Button("Clear List");
    //ImGui::ListBox("Files",&currentItem,listboxItems,currentItemsCount,10);
    
    ImGui::End();

    // Rendering
    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
}

void GlfwOcctView::cleanupUI()
{
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
}
```
Here is the main loop up to this point
```c++
void GlfwOcctView::mainloop()
{
  while (!glfwWindowShouldClose (myOcctWindow->getGlfwWindow()))
  {
    // glfwPollEvents() for continuous rendering (immediate return if there are no new events)
    // and glfwWaitEvents() for rendering on demand (something actually happened in the viewer)
    //glfwPollEvents();
    glfwWaitEvents();
    if (!myView.IsNull())
    {
        processUI();
      
        glfwSwapBuffers(myOcctWindow->getGlfwWindow());
        //FlushViewEvents(myContext, myView, true);
    }
 
  }
  ```

This is where some behavior changes are noticeable

OP from [here](https://dev.opencascade.org/content/using-opencascade-dear-imgui-and-glfw) said 
> I mean, if I use
glfwSwapBuffers(myOcctWindow->getGlfwWindow());
, then my scene becomes unresponsible, but my Dear Imgui window shows and can be controlled

In my case I cannot see either the OpenCascade scene nor any Imgui windows  (black screen)

He then said 
>  If I use
FlushViewEvents(myContext, myView, true);
then my Dear Imgui window is not showing at all, but scene is responsible.

My situation here is the same (I can see the open cascade scene and is responsive but cannot see any imgui windows)

He then says

> If I have both these lines, glfwSwapBuffers and FlushViewEvents then my Dear ImGui window and scene shows, but with graphical artifacts - flickering heavily, Dear ImGui window not redrawing properly when it covers a scene.

My situation is that my scene shows and has heavy graphical artifacts (flickering) but cannot see any imgui windows.

Then in the [forum](https://dev.opencascade.org/content/using-opencascade-dear-imgui-and-glfw) post somebody replied to the original post with useful information between OpenCascade and IMGUI. Which prompted the original poster to reply with the solution to their problem 

> Thanks a lot, it worked.
In initViewer() I added this call:
aGraphicDriver->SetBuffersNoSwap(true);
And then I changed mainloop() as advised:
void GlfwOcctView::mainloop()
{
  while (!glfwWindowShouldClose (myOcctWindow->getGlfwWindow()))
  {
    // glfwPollEvents() for continuous rendering (immediate return if there are no new events)
    // and glfwWaitEvents() for rendering on demand (something actually happened in the viewer)
    //glfwPollEvents();
    glfwWaitEvents();
    if (!myView.IsNull())
    {                
        FlushViewEvents(myContext, myView, true);
        processUI();
        glfwSwapBuffers(myOcctWindow->getGlfwWindow());
    }
  }
}
There is a little problem though: when moving ImGui window, my scene reacts too on moves. It's worth investigating too

In my case when I made these changes I just get a black screen (no error messages)

Now I find it super strange that both the [occt + imgui github repo](https://github.com/eryar/OcctImgui) and following [this forum](https://dev.opencascade.org/content/using-opencascade-dear-imgui-and-glfw) both lead to a black screen. Which makes me believe there is something wrong with my system. But its also strange that running the OpenCascade GLFW and the example_glfw_opengl3 independently of each other work just fine.

I am using cmake to compile my project I do get this warning _but_ I doubt that has anything to do with it because I get the same warning when I use cmake instead of Makefile to compile the example in `/examples/example_glfw_opengl3` and that runs just fine.
```cmake

CMake Warning (dev) at /usr/local/share/cmake-3.24/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

if I run the command `glxinfo | grep OpenGL` I get the following 
```txt
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 4600 (HSW GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.2.1 - kisak-mesa PPA
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.2.1 - kisak-mesa PPA
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.2.1 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

my imgui folder contains the following 
```
imconfig.h      imgui.h                 imgui_impl_opengl3.h         imgui_widgets.cpp
imgui.cpp       imgui_impl_glfw.cpp     imgui_impl_opengl3_loader.h  imstb_rectpack.h
imgui_demo.cpp  imgui_impl_glfw.h       imgui_internal.h             imstb_textedit.h
imgui_draw.cpp  imgui_impl_opengl3.cpp  imgui_tables.cpp             imstb_truetype.h
```

I am not sure how to approach the problem but I feel like its an issue with IMGUI. Any help would be appreciated !!!

### Minimal, Complete and Verifiable Example code:

[link to github gist with my changes](https://gist.github.com/notalfredo/be097b5e66fa10cbefe7a85efa6263ab)

[link to my cmake lists file](https://gist.github.com/notalfredo/198e1d8b074dc54ee1863a1d42df2525)

Again any help will be appreciated ! please let me know if there is any more information I can provide to help solve this problem. I am stuck and do not know where to go from here.

edit 1/2/3: small grammar fixes / semantic fixes

**Comment by ocornut** [comment]
You can try using a GPU Debugger like RenderDoc to try to compare the states of a successful render vs the states of a black one.

OpenCascade is probably setting some OpenGL state which is conflicting with our OpenGL backend. As OpenGL is a giant state machine it’s impossible to list them all, but I assume if you can save/clear/restore the offending state it would fix it.

The easiest way would be to try to get the minimum OpenCascade use that triggers the use and see what this does with OpenGL. Or you can use a GPU Debugger to try to find the culprit setting. The GPU Debugger will also help you understand what OpenCascade is doing with OpenGL.

We are not equipped for supporting detective work on every codebase, this is draining our resources.
If you can prove that there is something we can do better in our OpenGL3 backend, but I’m afraid we cannot help tracing every opengl call done by OpenCascade. Someone familiar with its internals or looking at source code may help.

I need to close it to protect dear imgui resources, sorry.

**Comment by ocornut** [comment]
I ought to clarify this is no reason this shouldn’t be doable. But OpenCascade being the enormous software doing 50 things and dear imgui backend being so trivial to read and understand, it’s likely the big thing interfering with state and this needs to be researched by someone willing to look at the OpenGL code.

**Comment by ocornut** [comment]
A good GPU debugger should be able to let you look into the draw calls emitted by dear imgui and see what is happening with them, at which points the pixels gets culled and why, or if they are black pixels for whatever reason. 
You can also confirm what's "right" e.g you can view/confirm the imgui submitted mesh.
https://renderdoc.org/

**Comment by notalfredo** [comment]
> A good GPU debugger should be able to let you look into the draw calls emitted by dear imgui and see what is happening with them, at which points the pixels gets culled and why, or if they are black pixels for whatever reason. You can also confirm what's "right" e.g you can view/confirm the imgui submitted mesh. https://renderdoc.org/

I installed renderdoc and played around with it for a bit. I am really intrigued by the tool.

I found a "hack" around the problem. Instead of displaying the im gui and OCCT in the same window I display them on different windows. [This OCCT forum post gave me that idea](https://dev.opencascade.org/content/occt-render-texture-without-window) (ill edit this post and share a code snippet once I clean up my mess)
![image](https://github.com/ocornut/imgui/assets/82833619/fbce1f94-5259-4abd-88b0-a667f565b296)


Ideally I need the imgui window and occt window to be one. So ill have to play around with RenderDoc to see what I can discover. 

Thanks,

**Comment by MattiaMontanari** [comment]
@notalfredo I'm running in the opposite issue: I have OCCT render into the main window and I can't render it into a different ImGUI window. I understand the idea is to get OCCT to render offscreen and bring the texture with ImGUI::Image, however I can't get it to work. I'm on MacOS.
Have you published your code anywhere I  can take a look?
