### ISSUE TITLE
Mouse position issue

### ISSUE THREAD

**Issue by Nic-Urb** [ocornut/imgui#7534]
### Version/Branch of Dear ImGui:

Version: 1.90.5, Branch: master

### Back-ends:

raylib

### Compiler, OS:

macOS + Clang

### Details:

**Mouse position issue:**

I encountered an issue when copying the same code ShowExampleAppSimpleOverlay() from imgui_demo, which correctly retrieves values for io.MousePos. However, if we paste the same code anywhere else into ImGui::NewFrame(), it returns fixed values like (0.5,0.1) or some other constant values. I resolved the issue by replacing io.MousePos with ImGui::GetMousePos().

I discovered this issue while investigating why ImGuizmo wasn't responding to mouseover until I moved the gizmo to the fixed position (0.5,0.1) from io.MousePos.

I'm curious why io.MousePos returns correct values only in imgui_demo and not anywhere else.

Here are the values from io.GetPos() and ImGui::GetMousePos():

### Screenshots/Video:

<img width="443" alt="Screenshot 2024-04-27 at 23 30 57" src="https://github.com/ocornut/imgui/assets/79403684/9c9e2547-f0c5-4c7b-8c74-c8baea1f4268">

### Minimal, Complete and Verifiable Example code:

```cpp
 if (ImGui::Begin("Mouse position")) {
      ImGuiIO& io = ImGui::GetIO();
      if (ImGui::IsMousePosValid()) {
              ImGui::Text("Mouse Position from ImGui::GetMousePos : (%.1f,%.1f)", ImGui::GetMousePos().x, 
                   ImGui::GetMousePos().y);
               ImGui::Text("Mouse Position from io.MousePos : (%.1f,%.1f)", io.MousePos.x, io.MousePos.y);
      }
```

**Comment by ocornut** [comment]
It should be the same, if it's different it could mean that:
- your `ImGuiIO` pointer is invalid, but here it is valid as you got it from ImGui::GetIO() in same scope where ImGui::GetMousePos()
- the struct layout in current compilation unit is incorrect. Either it means the file wasn't rebuilt, either it means the structure layout from the point of view of your compilation unit, doesn't match the structure kayout used by imgui. It could be the case if you used some `#define` affecting the layout of `ImGuiIO`. The only leftover #define which affects the struct layout are `IMGUI_DISABLE_OBSOLETE_KEYIO` and `IMGUI_DISABLE_OBSOLETE_FUNCTIONS`. If you use them they must in used in all compilation units or e.g. in your imconfig file.
- our examples use a `IMGUI_CHECKVERSION()` macros which is used to compare struct layout sizes between your code and dear imgui and detect this sorts of mistake.

**Comment by ocornut** [comment]
What was the issue then?

**Comment by Nic-Urb** [comment]
I had to remove the defines **IMGUI_DISABLE_OBSOLETE_KEYIO and IMGUI_DISABLE_OBSOLETE_FUNCTIONS** from my project.

**Comment by ocornut** [comment]
You can use them but they need to be defined the same for all compilation unit (imgui code and your code using imgui). The best place to put them is indeed in the imconfig file.

**Comment by Nic-Urb** [comment]
Okay, thanks for the help!
