### ISSUE TITLE
Lag when changing mouse cursor (was: lag hovering over text inputs)

### ISSUE THREAD

**Issue by MiquelNasarre** [ocornut/imgui#7538]
### Version/Branch of Dear ImGui:

I do not know

### Back-ends:

DirectX 11

### Compiler, OS:

Windows 10 GCC

### Details:

Good evening,

I've been having an issue for a long time with all the ImGui text inputs, when I hover over them they produce some kind of lag or delay and I don't know where that comes from. My program runs smoothly all the time and it always have that problem even when running in no stress.
Just checking if it is a common problem or something already solved or its just a bad implementation on my behalf. I am new to graphics programming so chances are I messed something up, but I cannot find it. I attached a video for some reference.

### Screenshots/Video:

https://github.com/ocornut/imgui/assets/124403865/e45477bd-c11a-447b-90ff-7a8f8d9af5b5

**Comment by ocornut** [comment]
The only I can think of is that hovering an `InputText()` sets `io.MouseCursor` requesting the backend to change mouse cursor.
So maybe your backend has an issue honoring that thing.
We can also see your cursor flickering here and the cursor is not changed.

1. See if you have the same issue in Demo->Inputs & Focus->Mouse Cursors section.
2. Which platform backend are you using, you didn't specify?
3. Perhaps you have conflicting code trying to change mouse cursor, I don;'t know.
4. You can set `io.ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange` to request our standard backend to nor care about the value of `io.MouseCursor` but then you are missing a feature. Worth investigating.

**Comment by MiquelNasarre** [comment]
Thank you very much for your answer.
I just tried the `io.ConfigFlags |= ImGuiConfigFlags_NoMouseCursorChange` and it solved the problem.
I also tried to debug it and it seems that the lag comes from my message pump, that uses the `peekmessageW` function from Win32. It seem to be receiving a lot of messages and lagging everything. 
It's been months since I did all that stuff so I barely remember how it works, nevertheless I am going to take a look at it and try to solve it, otherwise I will just leave it with the flag.
Thank you for your help.

**Comment by ocornut** [comment]
I believe it is more correct to leave this WNDCLASS field null.
I suppose some of our backends **(please note: you haven't said which platform backend you are using)** could potentially detect this case and output to debug log (only visible when enabled).

**Comment by MiquelNasarre** [comment]
Yes, at the end I decided to erase that line from my code since it wasn't doing anything useful in that particular program, and there's probably better ways of changing the cursor. That line was what was causing all that flickering and lag. 
Thank you very much for your help!
