### ISSUE TITLE
Issue double clicking Selectables

### ISSUE THREAD

**Issue by xGhostShipIV** [ocornut/imgui#754]
I'm trying to build a resource management system for listed files can be double clicked to be opened, while the following code mostly works, it appears that what is required is a triple click as opposed to double. Is this an issue with how I'm arranging the code? How can this be fixed?

Based on a previous and similar issue the code has been arranged as follows:
```
                if (ImGui::Selectable(m_name.c_str(), selected, ImGuiSelectableFlags_AllowDoubleClick))
                {
                    // Do stuff

                    if (ImGui::IsMouseDoubleClicked(0))
                    {
                        // Do stuff
                    }
                }
```
The IsMouseDoubleClicked is triggered, however it seems to take three clicks minimum to get into it.

**Comment by ocornut** [comment]
I couldn't repro.
```
        ImGui::Begin("Bug #754");
        static int counter = 0;
        if (ImGui::Selectable("Double click me", false, ImGuiSelectableFlags_AllowDoubleClick))
            if (ImGui::IsMouseDoubleClicked(0))
                counter++;
        ImGui::Text("Counter = %d", counter);
        ImGui::End();
```
Seems to work on double-click for me.

**Comment by dodo1004** [comment]
I do not know what you made, but in my experience first one could be a focus click.

**Comment by ocornut** [comment]
You may want to test the code as is and see what happens with your bindings.

dodo1004 is right, is the first click received by the owner window/selectable at all ?

```
ImGui::Begin("Bug #754");
static int counter_single = 0;
static int counter_double = 0;
if (ImGui::Selectable("Double click me", false, ImGuiSelectableFlags_AllowDoubleClick))
    if (ImGui::IsMouseDoubleClicked(0))
        counter_double++;
    else
        counter_single++;
ImGui::Text("counter_single = %d", counter_single);
ImGui::Text("counter_double = %d", counter_double);
ImGui::End();
```

**Comment by xGhostShipIV** [comment]
Sorry for the delay -- long weekend. So I've added checks to see when there's a double click or a single click. If the selectable is not selected and is double clicked it only receives a single click, if it is selected and double clicked it receives single click until double clicked again.

**Comment by ocornut** [comment]
Could you provide a repro in the form of imgui code that compiles and exhibit the bug within the example app?

**Comment by xGhostShipIV** [comment]
Sure thing. 

Executing the following code and rampantly double clicking the selectable the output alternates between Single and Double.
```
            if (ImGui::Selectable("Test", true, ImGuiSelectableFlags_AllowDoubleClick))
            {
                if (ImGui::IsMouseDoubleClicked(0))
                {
                    printf("Double");
                }
                else
                {
                    printf("Single");
                }
            }
```

**Comment by ocornut** [comment]
Alternating between single and double is the expected behavior. This isn't what you described in the first post saying it needed three clicks tho?

**Comment by xGhostShipIV** [comment]
My apologies, I may have been unclear. Basically what I'm trying to make is a File viewer where the user can select files in the list to do various operations with, but when they double click the selectable the file should open. Because of the alternation between single and double clicks, the user must triple click the file to open it, rather than double which is not the desired behaviour.

**Comment by ocornut** [comment]
If I click twice on my mouse I see "single" then "double" printed. Do you see something else?

**Comment by xGhostShipIV** [comment]
If I double click I only see single. If I double click again I see double. I'm trying to get to a point where whether the Selectable is selected or not, double clicking the first time would only print double.

**Comment by ocornut** [comment]
Are you using cs_dblclks flag in Windows that translates double clicks into something magic?

**Comment by xGhostShipIV** [comment]
That did it. Thank you.
