### ISSUE TITLE
When ImGuiChildFlags_AlwaysUseWindowPadding is enabled, the left and right padding widths of the Child are different, but the Parent window is the same

### ISSUE THREAD

**Issue by o-3-o** [ocornut/imgui#7540]
### Version/Branch of Dear ImGui:

Version 1.90.6 WIP, Branch: docking (master/docking/etc.)

### Back-ends:

imgui_impl_Win32.cpp + imgui_impl_DX11.cpp

### Compiler, OS:

Win11 + MSVC 2022 

### Full config/build information:

```
Dear ImGui 1.90.6 WIP (19052)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: IMGUI_DISABLE_OBSOLETE_KEYIO
define: _WIN32
define: _WIN64
define: _MSC_VER=1939
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x0000C443
 NavEnableKeyboard
 NavEnableGamepad
 DockingEnable
 ViewportsEnable
 DpiEnableScaleViewports
 DpiEnableScaleFonts
io.ConfigViewportsNoAutoMerge
io.ConfigViewportsNoDecoration
io.ConfigViewportsNoDefaultParent
io.ConfigDockingTransparentPayload
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 3440.00,1392.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

When [ImGuiChildFlags_AlwaysUseWindowPadding] is enabled, the left and right padding widths of the Child are different, but the Parent window is the same

### Screenshots/Video:

![20240430014257](https://github.com/ocornut/imgui/assets/51990072/b981c1a7-e99d-4553-8341-17149bd1ac09)

### Minimal, Complete and Verifiable Example code:

```cpp
ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(20.0f, 20.0f));
ImGui::Begin("fafafaefaefe");
	ImGui::PushStyleColor(ImGuiCol_ChildBg, IM_COL32(204, 205, 209, 255));
	ImGui::BeginChild("##Container", ImVec2(0.0f, 0.0f), ImGuiChildFlags_AlwaysUseWindowPadding);
		ImGui::Button("fafafqwfwqfqwfwqfe");
	ImGui::EndChild();
	ImGui::PopStyleColor();
ImGui::End();
ImGui::PopStyleVar();
```

**Comment by cfillion** [comment]
The inner clipping rectangle of all windows (child or not) is always larger than the padding (by half).

The actual padding is the same on the left and right sides, which you can observe by setting `ImGuiChildFlags_AutoResizeX`. Or "Show window rectangles" in `ShowMetricsWindow()` under "Tools".

https://github.com/ocornut/imgui/blob/a60387a3c25c18d223494873c7429d965691ea7f/imgui.cpp#L6824-L6836

**Comment by o-3-o** [comment]
> The inner clipping rectangle of all windows (child or not) is always larger than the padding (by half).所有窗口（无论是否为子窗口）的内部剪切矩形始终大于填充（大一半）。
> 
> The actual padding is the same on the left and right sides, which you can observe by setting `ImGuiChildFlags_AutoResizeX`. Or "Show window rectangles" in `ShowMetricsWindow()` under "Tools".实际的左右边距是相同的，您可以通过设置 `ImGuiChildFlags_AutoResizeX` 来观察。或者“工具”下的 `ShowMetricsWindow()` 中的“显示窗口矩形”。
> 
> `ImVec2(0.0f, 0.0f)` makes the child window use all available width in the work rectangle which includes the full padding. `ImVec2(0.0f, 0.0f)` 使子窗口使用工作矩形中的所有可用宽度，其中包括完整的填充。
> 
> https://github.com/ocornut/imgui/blob/a60387a3c25c18d223494873c7429d965691ea7f/imgui.cpp#L6824-L6836

Thanks for your answer, now I realize that it is always larger than the padding (by half). It was a visual misunderstanding.

**Comment by o-3-o** [comment]
can solve this visual problem by using PushClipRect to limit it yourself.

ImGui::PushClipRect(ImGui::GetCurrentWindow()->Pos + ImGui::GetStyle().WindowPadding, ImGui::GetCurrentWindow()->Pos - ImGui::GetStyle().WindowPadding + ImGui::GetCurrentWindow()->Size, false);
//...
ImGui::PopClipRect();
![QQ截图20240430112925](https://github.com/ocornut/imgui/assets/51990072/591fc3fc-20b1-4871-9e5e-ad83a3e6448b)

**Comment by ocornut** [comment]
Linking to #3312 as I've been considering changing this and make the clip rect fill entire inner rect. I'll post here too if this changes.

**Comment by ocornut** [comment]
I went and pushed the change discussed in #3312 I think it's for the best 0b309471f2ed0117bbffda43684f54404cf14ea2
Also generally makes it easier to draw stuff in edge of windows without requiring a clip rect change.
