### ISSUE TITLE
Where's the binaries?

### ISSUE THREAD

**Issue by acidhorse1972** [ocornut/imgui#7545]
### Version/Branch of Dear ImGui:

master

### Back-ends:

any

### Compiler, OS:

any

### Full config/build information:

any

### Details:

Here you have all these prerequisites for reporting and you don't even have the consideration of supplying any precompiled binaries and resort to dumping the task of compiling the library on the programmers?
That's too much of a burden on programmers compiling a different project which depends on this project and several others who also may resort to the same tactic of dumping a source ball and slapping a version number on it.
It would be helpful to see that the code has been tested properly on the different platforms and a working binary supplied to help eliminate huge 4 GB or more git clone situations. 
If there is a bug in your code there needs to be a pathway to drop in alternatives or substitutes.

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by acidhorse1972** [comment]
No static libs no dynamic libs for any platforms

**Comment by ocornut** [comment]
This is meant to be built from source and sometimes involved configuration flags for building. If building code is a problem from you it may be best you don’t use this project.

**Comment by ocornut** [comment]
In addition this is a small and well tested repository and the main library is extremely portable.

**Comment by ocornut** [comment]
I am sure if you try to build it by simply adding the source files to your project you will find it is trivial to build.

Most people are making this unnecessarily more complicated by creating build systems, librairies etc. Just try add the files to your existing project first.
