### ISSUE TITLE
Change value of widget

### ISSUE THREAD

**Issue by Birdboat** [ocornut/imgui#755]
Is there any way to change the value of a widget at runtime? I have looked through the API and widget functions and there seems to be no easy way to do it.

**Comment by ocornut** [comment]
Which widget? The question doesn't make a lot of sense since by design imgui tries to not carry any copy of your value. One exception is while text editing is active.

**Comment by Birdboat** [comment]
The widgets I'm concerned about are the Checkbox, InputFloat, InputText, and Combo.

**Comment by ocornut** [comment]
Your own all those values you can change them at any time.

**Comment by Birdboat** [comment]
Okay, thanks. Sorry for pointless question.
