### ISSUE TITLE
Can't access some stuff from imgui.h

### ISSUE THREAD

**Issue by KlewyWorle** [ocornut/imgui#7550]
### Version/Branch of Dear ImGui:

Version newest, Branch: master (master/docking/etc.)

### Back-ends:

imgui_impl_opengl3

### Compiler, OS:

Linux GCC Clang

### Details:

![image](https://github.com/ocornut/imgui/assets/45066731/2fe945fc-9bd3-4e57-a848-7309f145b90a)
im trying to set imgui window to fullscreen and i Found a way, but I need to access GetCurrentWindow() for it.
The problem is I can't, because the compiler tells me there is no such function, even though it's literally in imgui.cpp

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by GamingMinds-DanielC** [comment]
Imagine having an obscure problem, searching the internet and coming across an issue, a thread or something similar where someone else has the exact same problem. You read until the end in hopes that their solution applies to your case, but you only find something like "nevermind, solved it" without further explanation. Not what you would want to see, right? So please, even if the problem isn't too obscure and if the solution is trivial (once found), it would be nice to at least write a sentence about it.

So here is a short explanation for this issue:
The compiler needs to know about the interfaces you want to use, to make them known you need to include the corrrect header file. Only the stable interface is declared in `imgui.h`. There are more interfaces (experimental/unstable/WIP) that are not yet part of the public interface, you need to include `imgui_internal.h` to use them.
