### ISSUE TITLE
Suggestion: Consider Adding Title Bar Text to Popups

### ISSUE THREAD

**Issue by vdweller84** [ocornut/imgui#7551]
### Version/Branch of Dear ImGui:

Version 1.90.6, Branch: docking

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_sdl2.cpp

### Compiler, OS:

MSVC 2019

### Details:

As the title says. This is obviously not a huge priority but it would be nice if we could add Text on popup title bars, like this:
![image](https://github.com/ocornut/imgui/assets/96083791/6560fbe3-87bf-4238-8186-976069e56342)
From what I understand, as of now, one can either hack `BeginPopupEx()` (this is what I did to make the image above work) or create a modified version of it. If there is any other way to make this work please let me know.

EDIT: Drawing text with Foreground Draw list works,  but if there is a context menu when one right clicks the popup's title bar, things can get visually messy.

**Comment by ocornut** [comment]
> From what I understand, as of now, one can either hack BeginPopupEx() (this is what I did to make the image above work) or create a modified version of it. If there is any other way to make this work please let me know.

You can just created a modified version of it.

```cpp
bool BeginPopupWithTitle(const char* name)
{
    ImGuiContext& g = *GImGui;
    if (!IsPopupOpen(GetID(name), ImGuiPopupFlags_None))
    {
        g.NextWindowData.ClearFlags(); // We behave like Begin() and need to consume those values
        return false;
    }

    // NB: Begin can return false when the popup is completely clipped (e.g. zero size display)
    if (!Begin(name, NULL, ImGuiWindowFlags_Popup))
        EndPopup();
    return true;
}
```

**Comment by vdweller84** [comment]
Sounds good. Thanks Omar!
