### ISSUE TITLE
Add RGFW backend implementation

### ISSUE THREAD

**Issue by Ikos3k** [ocornut/imgui#7558]
### Version/Branch of Dear ImGui:

any

### Back-ends:

imgui_impl_RGFW.cpp

### Compiler, OS:

any

### Details:

You can create an RGFW implementation (https://github.com/ColleagueRiley/RGFW)

**Comment by ocornut** [comment]
Feel free to create one, it should be easy. We’ll link to it from wiki pages. But we can’t maintain backends for every engine under the sun.

**Comment by ColleagueRiley** [comment]
@Ikos3k  Feel free to move this issue to the RGFW repo. I may look into creating an example using imgui in the future.

**Comment by ColleagueRiley** [comment]
https://github.com/ColleagueRiley/imgui_imp_rgfw.h/

I made a dear RGFW backend for dear imgui. 

@ocornut @Ikos3k

**Comment by ocornut** [comment]
Thank you, added to https://github.com/ocornut/imgui/wiki/Bindings

**Comment by ColleagueRiley** [comment]
@ocornut I have a question, I'm not sure where to put it so I'll ask it here. 

I noticed that there's the docking branch which includes support for 'viewports', the ability to create a subsurface/subwindow from one a menu. (Sorry if I'm using the wrong terminology I'm not too familiar with imgui.)

I'm curious how it works and if I will need to add any additional functionality to RGFW to support such a feature.

**Comment by ocornut** [comment]
Read code for any existing backend in this branch and you’ll find out quickly.
