### ISSUE TITLE
AddTriangleFilledMultiColor

### ISSUE THREAD

**Issue by Kubikx** [ocornut/imgui#757]
I am wondering, why there is "AddRectFilledMultiColor", but no "AddTriangleFilledMultiColor", so I create it.
I am not sure if it is correct ( the uv coordinates), but its working in my case.
Is there a way how can I add it as some kind of extension, or this must be in "imgui_draw.cpp".
If it must be in "imgui_draw.cpp", may you please add it.

    void ImDrawList::AddTriangleFilledMultiColor(const ImVec2& a, const ImVec2& b, const ImVec2& c, ImU32 aCol, ImU32 bCol, ImU32 cCol)
    {
    	const ImVec2 uv = GImGui->FontTexUvWhitePixel;
    	PrimReserve(3, 3);
    	PrimWriteIdx((ImDrawIdx)(_VtxCurrentIdx)); PrimWriteIdx((ImDrawIdx)(_VtxCurrentIdx + 1)); PrimWriteIdx((ImDrawIdx)(_VtxCurrentIdx + 2));
    	PrimWriteVtx(a, uv, aCol);
    	PrimWriteVtx(b, uv, bCol);
    	PrimWriteVtx(c, uv, cCol);
    }
I need it for colored graph, maybe I later create a widget for it.
![coloredgraphtest](https://cloud.githubusercontent.com/assets/5793444/17274988/20dbdafa-56f9-11e6-9230-2e15e447ea14.JPG)
Axes, scales, labels.. still missing :disappointed: 

Thanks

**Comment by ocornut** [comment]
The reason is that individual triangles are used more rarely. If you are going to render lots of triangles you probably want to call e.g. PrimReserve yourself once and/or share indices.

You can also create a helper function on the side that takes ImDrawList* as a parametero.

**Comment by Kubikx** [comment]
Thanks I take a look at how to create helper function with ImDrawList* as a parametero.

**Comment by Kubikx** [comment]
Big thanks, now it look better :smiley: 
    #include "..\ImGUI\imgui.h"
    #include "..\ImGUI\imgui_internal.h"
    ImColor* yc;
    void prepareGraphColors(const ImColor c[], int lenght)
    {
    	yc = new ImColor[lenght];
    	for (size_t i = 0; i < lenght; i++)
    	{
    		yc[i] = c[i];
    	}
    }
    
    void drawGraph(const float x[], const float yA[], int Lenght)
    {
    	ImDrawList* draw_list = ImGui::GetWindowDrawList();
    	const ImVec2 uv = ImGui::GetCurrentContext()->FontTexUvWhitePixel;
    	ImVec2 size = ImGui::GetContentRegionAvail();
    	int yLenght = Lenght;
    	int xLenght = Lenght;
    	yLenght--;
    	const float smallerSizeBy = 64.0f;
    	const ImVec2 p = ImGui::GetCursorScreenPos();
    	if (size.x < 2 * smallerSizeBy || size.y < 2 * smallerSizeBy)
    	{//error if not enough space
    		draw_list->AddLine(p, ImVec2(p.x + size.x, p.y + size.y), ImColor(255, 0, 0, 128));
    		draw_list->AddLine(ImVec2(p.x + size.x, p.y), ImVec2(p.x, p.y + size.y), ImColor(255, 0, 0, 128));
    		draw_list->AddText(p, ImColor(255, 255, 0), "Too\nsmall\narea\nfor\ngraph.");
    		return;
    	}
    	float s = (x[yLenght] - x[0]) / (size.x - smallerSizeBy);
    	float spacing;
    	float x1;
    	float y1 = p.y + size.y - smallerSizeBy;
    	float y = y1 - (p.y);
    
    	//Auto scale graph
    	float max = yA[0];
    	for (size_t i = 1; i < xLenght; i++)
    	{
    		if (yA[i] > max)
    		{
    			max = yA[i];
    		}
    	}
    	y /= max;
    	//----------------
    
    	//render graph area
    	draw_list->PrimReserve(yLenght * 6, 2 * xLenght);//2 vertex per point, 2 triangels per point == 6 indexes per point
    	for (size_t i = 0; i < yLenght; i++)
    	{
    		x1 = p.x + smallerSizeBy + (x[i] - x[0]) / s;
    		draw_list->PrimWriteIdx((ImDrawIdx)(draw_list->_VtxCurrentIdx)); draw_list->PrimWriteIdx((ImDrawIdx)(draw_list->_VtxCurrentIdx + 3)); draw_list->PrimWriteIdx((ImDrawIdx)(draw_list->_VtxCurrentIdx + 1));
    		draw_list->PrimWriteIdx((ImDrawIdx)(draw_list->_VtxCurrentIdx)); draw_list->PrimWriteIdx((ImDrawIdx)(draw_list->_VtxCurrentIdx + 2)); draw_list->PrimWriteIdx((ImDrawIdx)(draw_list->_VtxCurrentIdx + 3));
    		draw_list->PrimWriteVtx(ImVec2(x1, y1), uv, yc[i]);
    		draw_list->PrimWriteVtx(ImVec2(x1, y1 - y*yA[i]), uv, yc[i]);
    	}
    	x1 = p.x + smallerSizeBy + (x[yLenght] - x[0]) / s;
    	draw_list->PrimWriteVtx(ImVec2(x1, y1), uv, yc[yLenght]);
    	draw_list->PrimWriteVtx(ImVec2(x1, y1 - y*yA[yLenght]), uv, yc[yLenght]);
    	//-----------------
    
    	//Axis
    	draw_list->AddLine(ImVec2(p.x, y1 + 2), ImVec2(p.x + size.x, y1 + 2), ImColor(0, 0, 0));
    	draw_list->AddLine(ImVec2(p.x+smallerSizeBy-2, p.y), ImVec2(p.x + smallerSizeBy-2, p.y+size.y), ImColor(0, 0, 0));
    	//----
    
    	//TODO axis label and values
    }

It will need an instance, or maybe colors list as parametr.
Can you recommend me a way how to implement values on axes?
If the graph will contain for example 256 points rendering every label make no sense, because none of them will be visible under the others.
It will need checking the size and show only every "X" value to keep space between textx.
Can you again point me where to start with this.
