### ISSUE TITLE
Keeping combo open after clicking selectable

### ISSUE THREAD

**Issue by JerimiahOfficial** [ocornut/imgui#7573]
### Version/Branch of Dear ImGui:

Version 1.90.6, Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

Windows 10 + gcc

### Details:

**My Issue/Question:**
I want to create a multi select combo box that doesn't close when selecting an option. I am currently using the example from #1658 and it closes when I selected and option. Is there a way to keep the popup open when clicking the selectable inside of it?

### Minimal, Complete and Verifiable Example code:

```cpp
const char* items[] = { "AAAA", "BBBB", "CCCC", "DDDD", "EEEE", "FFFF", "GGGG", "HHHH", "IIII", "JJJJ", "KKKK", "LLLLLLL", "MMMM", "OOOOOOO", "PPPP", "QQQQQQQQQQ", "RRR", "SSSS" };
static const char* current_item = NULL;

if (ImGui::BeginCombo("##combo", current_item)) {
    for (int n = 0; n < IM_ARRAYSIZE(items); n++) {
        bool is_selected = (current_item == items[n]);
        
        if (ImGui::Selectable(items[n], is_selected)
            current_item = items[n];
            
        if (is_selected)
            ImGui::SetItemDefaultFocus();
    }
    ImGui::EndCombo();
}
```

**Comment by ocornut** [comment]
It is now possible to control this for Selectable, MenuItem() using the public API:
```
ImGui::PushItemFlag(ImGuiItemFlags_AutoClosePopups, false);
ImGui::MenuItem(....);
ImGui::PopItemFlags();
```
