### ISSUE TITLE
Arrow keys in InputTextMultiline() not working - what'd I miss?

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#758]
While I can create, and use, the text area generated, for some reason I can't seem to use arrow keys, either numeric-pad or inverted-T ones (standard IBM M US 101 keyboard).

The arrows work fine in the program as I use them for moving things around.  I even commented out my entire keyboard handling section responding to those just to see if I was somehow consuming them before the popupModal.

```
if (ImGui::BeginPopupModal("ContextOptions", nullptr, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_ShowBorders)) {
//...
ImGui::InputTextMultiline( "##annotationnew", contextbuf, sizeof(contextbuf), ImVec2(600, ImGui::GetTextLineHeight() * 16), 0, NULL, contextbuf);
//...
}

```

**Comment by ocornut** [comment]
Hello,

1) Please try to provide a complete repro that I can paste as-is when reporting a bug.
Here's a functional repro:
```
if (!ImGui::IsAnyWindowHovered() && ImGui::IsMouseClicked(1))
    ImGui::OpenPopup("ContextOptions");
if (ImGui::BeginPopupModal("ContextOptions", nullptr, ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_ShowBorders)) 
{
    static char contextbuf[256] = "hello";
    ImGui::InputTextMultiline( "##annotationnew", contextbuf, sizeof(contextbuf), ImVec2(600, ImGui::GetTextLineHeight() * 16), 0, NULL, contextbuf);
    ImGui::EndPopup();
}
```

It works here within the examples/opengl_example/ application.

2) Which bindings are you using? Is your code passing the up/down arrow keys at all? (You can check in the demo window under the `Keyboard, Mouse & Focus` section.
In the absence of a full repro, it is possibly that your code keeps calling OpenPopup() every frame which might have unwanted side-effect of reinitializing some  fields. I am not sure

**Comment by inflex** [comment]
Found the fault.  Was a carry over from an issue I had about a month ago with trying to map SDL_ keycodes that had the highbit set.  My code was incorrect in that it modified the key, rather than just marking the KeysDown array.
