### ISSUE TITLE
Jumping the user to a different part of the GUI

### ISSUE THREAD

**Issue by tenpn** [ocornut/imgui#7583]
### Version/Branch of Dear ImGui:

1.90.1

### Back-ends:

Psydack's UImGui port v4.1.0

### Compiler, OS:

Windows 10, Unity 2023.2.13

### Details:

I have multiple windows started with Begin, each with CollapsingHeaders, each of those with some TreeNodes. Often the windows are all tabbed together but they might not be. 

At certain points in the application I'd like to be able to bring a particular window to the front, and unfold headers/trees down to a particular point. 

I saw SetKeyboardFocusHere, but if my window isn't even rendering, I am not running the subtree that needs to own the focus to call it. 

do I have to do something like `if (ImGui::Begin("window") || IsPartOfFocusTree("window"))` in every part of my code?

**Comment by GamingMinds-DanielC** [comment]
Before calling `ImGui::Begin()` for your window, you can call `ImGui::SetNextWindowFocus()` to bring it to the front and focus it. For tree nodes and collapsing headers you can use `ImGui::SetNextItemOpen()` and `ImGui::SetScrollHereY()` to scroll to the current cursor position.

**Comment by ocornut** [comment]
It's not a trivial problem to solve in a generic manner here, as they are ample variations of the same thing.

Generally you ought to focus the window:

`ImGui::SetWindowFocus("name")` (or `ImGui::SetNextWindowFocus()` before `Begin()`)

As for the tree itself, depending on how you store your focus request (as a path?), if you can compute their ImGuiID you might access the storage directly (`ImGui::GetStateStorage()->SetBool()`, see #7553) so you might incrementally as you render the tree use data from your focus request path to call `ImGui::SetNextItemOpen(true / false)` on tree nodes.

**Comment by tenpn** [comment]
Thank you folks! A combo of SetWindowFocus(name) and SetNextItemOpen seemed to work. Luckily my code is mostly autogenerated, so I only had to add it to two places to work everywhere. (SetNextWindowFocus didn't seem to work, maybe because I was attempting to focus the same frame that I was adding new windows)
