### ISSUE TITLE
Changing hIcon and hIconSm are not changing to custom icon

### ISSUE THREAD

**Issue by XECTRA-RAW** [ocornut/imgui#7586]
### Version/Branch of Dear ImGui:

1.89.2

### Back-ends:

imgui_impl_dx11

### Compiler, OS:

Windows 11, VS 2022

### Details:

**My Issue/Question:**

Wondering if someone could support me with changing the hIcon and hIconSm to my custom .ico file. Ive followed some guides and it only seem to change the exe icon when building not the icons when hovering over program on taskbar or using alt tab! 

The guides i followed did change the icon however, they only changed to windows icon such as default application, yellow warning triangle, red error triangle etc.

Code in resource.h
#define IDI_MYICON       101 //changing these up and down do change the icon but only to window's ones
#define IDI_MYICON_SMALL 102 //changing these up and down do change the icon but only to window's ones

Code in resource.rc
#include "resource.h"
IDI_MYICON       ICON "icon.ico"
IDI_MYICON_SMALL ICON "icon.ico"

Code in main.cpp
wc.hIcon = LoadIcon(0, MAKEINTRESOURCE(IDI_MYICON));
wc.hIconSm = LoadIcon(0, MAKEINTRESOURCE(IDI_MYICON_SMALL));

**Comment by ocornut** [comment]
Sorry but this question is not related to dear imgui, i’ll have to close it.
