### ISSUE TITLE
getting tightest possible horizontal spacing 

### ISSUE THREAD

**Issue by tenpn** [ocornut/imgui#7601]
### Version/Branch of Dear ImGui:

1.90.1

### Back-ends:

Psydack's UImGui port v4.1.0

### Compiler, OS:

Windows 10, Unity 2023.2.13

### Details:

I've got a collection of mostly Labels under Collapsible Headers. Something about my layout means I have to have much wider windows than seem necessary. 

In the first screenshot below, this is the narrowest I can have this window and still read everything in the right-hand column. If I go narrower, as in the second screenshot, the right-hand column starts to get cut off. This is despite there still being plenty of space in the middle to eat up. 

Am I missing an option to let Dear ImGui prioritise shrinking empty space before it cuts off content? 

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/360648/a221c308-eade-4c83-baa2-3975d5e3a293)
![image](https://github.com/ocornut/imgui/assets/360648/901f962b-91eb-4313-8bf7-87e25502b8e3)

**Comment by ocornut** [comment]
If by labels you mean LabelText() its quite an old widget that follows the current value of ItemWidth to match the width of a Slider or any other framed widget. You can control that width with PushItemWidth() or SetNextItemWidth() and there’s a section in Demo>Layout detailing it. It defaults to something like 2/3 of the window and its a bit awkward because it doesn’t lend itself to manual resizing (i have some ideas in mind to improve it).

However, it seems like you should be using a table and set column policy to fit/stretch or make the table resizable.

**Comment by ocornut** [comment]
To clarify if you were submitting eg Drags or Sliders or Inputs you would see the frame on the left and this frame’s width is derived from ItemWidth, and it would make a little bit more sense as to why the left side is not best-fit.

(It’s a recurrent question/wonder in the sense that both the order and lack of manual resizing is not ideal. What people do nowadays if they want the best-fit is to use a two columns name, add label in one column and widgets without label filling the other column (using -FLT_MIN you right align frames to available bounds).

**Comment by tenpn** [comment]
my GUI is constructed dynamically, so it's awkward to know if you're in a run of labels that could share a table or not. 

I could do Text--SameLine--Text but what would really make it sing is some way of tabstopping. If the first Text was < some width, then pass an offset to SameLine. CalcItemWidth isn't what I need according to the docs. I've been digging in the excellent manual demo https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html but not found anything yet.

**Comment by ocornut** [comment]
> my GUI is constructed dynamically, so it's awkward to know if you're in a run of labels that could share a table or not.

I believe every fields should share the same table, why wouldn’t they?

**Comment by tenpn** [comment]
I've got collapsing headers and tree nodes all mixed up in there, it's callbacks all over the place. I think I figured out a way to table runs of labels tho, will give that a go.

**Comment by tenpn** [comment]
😤
![image](https://github.com/ocornut/imgui/assets/360648/a20708dc-3879-4844-a845-44a4bae006a1)
using a cached CalcTextSize for the label key to pass a minimum offset to SameLine()

**Comment by ocornut** [comment]
You can call EndTable() when using a collapsing header and reopen it immediately, that’s also a solution.
