### ISSUE TITLE
ColorConvertU32ToFloat4

### ISSUE THREAD

**Issue by Barashuk** [ocornut/imgui#761]
Hey. Function "ColorConvertU32ToFloat4" returns the array of colors in the palette ABGR. So it must be, or this is a bug?
PS. I use on Google Translate.

**Comment by inflex** [comment]
Yes, I believe that is normal (actually it should be ABGR, 0xAABBGGRR).

**Comment by Barashuk** [comment]
But then, why some functions use RGBA palette of colors, and not ABGR? For example, TextColored used RGBA.

**Comment by ocornut** [comment]
It really doesn't matter and it is actually correct for little-endian CPU which is the most common type nowadays.

0xAABBGGRR = RGBA

```
struct Col4i
{
    unsigned char r, g, b, a;
};
Col4i test;
test.r = 0x10;
test.g = 0x20;
test.b = 0x40;
test.a = 0x80;

ImU32 test2 = IM_COL32(0x10,0x20,0x40,0x80);
```

Note in the debugger the values are the same:

![rgba](https://cloud.githubusercontent.com/assets/8225057/17358650/5745ef42-5963-11e6-9a70-ed7a2c798990.PNG)
