### ISSUE TITLE
altas is null when use llvm

### ISSUE THREAD

**Issue by EnderMagic** [ocornut/imgui#7621]
### Version/Branch of Dear ImGui:

Version 1.8.19, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_winap.cpp

### Compiler, OS:

win10 newest llvm+clang

### Details:

**My Issue/Question:**

working well on msvc but when i change it into llvm 
XXX _(please provide as much context as possible)_

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/31653737/2417da30-6e3b-4aad-a120-a2b57ad76077)
![image](https://github.com/ocornut/imgui/assets/31653737/2417da30-6e3b-4aad-a120-a2b57ad76077)
![Uploading image.png…]()

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by EnderMagic** [comment]
![image](https://github.com/ocornut/imgui/assets/31653737/1a33ec8f-d553-4f37-87a1-dacd6ef40edc)
its with msvc

**Comment by ocornut** [comment]
Sorry but #1586
