### ISSUE TITLE
Slider automatically setting to random large value on load

### ISSUE THREAD

**Issue by kuuneh** [ocornut/imgui#7624]
### Version/Branch of Dear ImGui:

Version 1.90.6, Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_openGL3.cpp

### Compiler, OS:

Arch Linux, g++

### Details:

I'm trying to make a password manager and have a slider that lets the user pick the length of a generated password.
On making the slider, I noticed that the value would automatically set to some crazy large value like "3112034" and on printing the value of the slider, the numbers are different.

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/137254885/2a7bfd71-81ae-4aa6-a331-163c13ab3439)
![image](https://github.com/ocornut/imgui/assets/137254885/d135841f-5e69-47f4-9c9a-0d2dfa5c51e9)

### Minimal, Complete and Verifiable Example code:

```cpp
// My code:
		if (tabs::index == 1) {
			int x;
			if (ImGui::SliderInt("Length", &x, 0,20)) {
				std::cout << x;
			}
```

**Comment by PathogenDavid** [comment]
`x` is uninitialized, and as such starts with some garbage value.

You need to initialize it to something sensible and store it somewhere that persists across function calls.

**Comment by kuuneh** [comment]
> `x` is uninitialized, and as such starts with some garbage value.
> 
> You need to initialize it to something sensible and store it somewhere that persists across function calls.

Tysm! Rookie mistake, my fix was doing as you said and storing it somewhere like where I kept all my global variables and that fixed it.
