### ISSUE TITLE
DX12 example exception

### ISSUE THREAD

**Issue by njikmf** [ocornut/imgui#7628]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: master

### Back-ends:

imgui_impl_dx12.cpp 

### Compiler, OS:

Win10 + vs2022

### Full config/build information:

Unhandled exception at 0x00007FF9AB79CF19 (KernelBase.dll) in example_win32_directx12.exe: 0x0000087A (parameters: 0x0000000000000002, 0x0000009D8F4FC460, 0x0000009D8F4FD200).

 	KernelBase.dll!00007ff9ab79cf19()	Unknown
 	DXGIDebug.dll!00007ff94e963563()	Unknown
 	DXGIDebug.dll!00007ff94e96d387()	Unknown
 	d3d12SDKLayers.dll!00007ff93655bba5()	Unknown
 	DXGIDebug.dll!00007ff94e96cb61()	Unknown
 	DXGIDebug.dll!00007ff94e96cfad()	Unknown
 	DXGIDebug.dll!00007ff94e96d01f()	Unknown
>	example_win32_directx12.exe!CleanupDeviceD3D() Line 385	C++
 	example_win32_directx12.exe!main(int __formal, char * * __formal) Line 241	C++
 	[External Code]	

### Details:

**My Issue/Question:**

Debug version of DX12 example throw the exception when exit

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by PathogenDavid** [comment]
Please check Visual Studio's output window, there should be a message there with more details.

**Comment by ocornut** [comment]
Closing as stale / not providing info.
