### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ocornut/imgui#763]
I would like to point out that an identifier like "[`_OwnerName`](https://github.com/ocornut/imgui/blob/907265d6320ffdfb438fff94aa88133d33ac3775/imgui.h#L1171 "Update candidate: ImDrawList structure")" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by ocornut** [comment]
Hello, sorry it appears you are either a zealous bot either a zealous human. I'll happily tweak or fix things that have an actual side-effect in the wild but this is not one of them, regardless of what ISO/something may say!

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](http://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Avoid undefined behaviour?")?

**Comment by paulsapps** [comment]
I don't believe that @elfring is a bot haha
