### ISSUE TITLE
 imgui_impl_glfw.h has an "imgui.h" header in the global installation with libimgui-dev.

### ISSUE THREAD

**Issue by tstwroot** [ocornut/imgui#7633]
### Version/Branch of Dear ImGui:

libimgui-dev (1.81+ds-1)

### Back-ends:

imgui_impl_glfw.h + imgui_impl_opengl3.h

### Compiler, OS:

g++, Debian

### Full config/build information:

g++ main.c -o main -lglfw -limgui -lstb -lGL

### Details:

I can't compile using the global imgui installation because the backend headers use an "imgui.h" file in a different directory.
Can't the problem be resolved by replacing "imgui.h" with <imgui/imgui.h> in all backend headers (only for global instalation) ? 
For now, how i can solve it ?

**Comment by ocornut** [comment]
I don’t know what a “global installation” is or means, that’s not something we designed or support and it is the first time i hear of “libimgui-dev”.

If you use the library you are expected to add its folder to your include path.

Also note that 1.81 is many years old and it is not recommended that you start using the library with an old version.

**Comment by tstwroot** [comment]
Ok, thanks for your attention. I will use the latest version now.
