### ISSUE TITLE
Indent of TreeNode in a table columns (moves only first column offset when the third column is selected)

### ISSUE THREAD

**Issue by oscar7070** [ocornut/imgui#7635]
### Version/Branch of Dear ImGui:

Version 1.90.7, Branch: docking.

### Back-ends:

imgui_impl_SDL3.cpp + imgui_impl_SDL3Renderer.cpp

### Compiler, OS:

Windows11 + MSVC

### Details:

**My Issue/Question:**
When i use the TreeNode inside a table column it's moves only the first column elements and not the selected column elements.

### Screenshots/Video:

**The bug:**
![Screenshot_388](https://github.com/ocornut/imgui/assets/56559647/ceb4911b-e4dc-4295-a9bb-27a9647461fb)

https://github.com/ocornut/imgui/assets/56559647/48dadc55-9566-48a4-b944-2444f581bd2f

**How it's needs to be:**
![Screenshot_3881](https://github.com/ocornut/imgui/assets/56559647/ed092eb7-4757-4a17-b147-303c6f9b63b5)

**My code(the code written in c# through my engine it's a regular c++ imgui(with custom minor changes) just imported with dll import):**
```
public override void OnGUI()
{
    if (MapManager.CurrentMap != null)
    {
        if (GUILayout.BeginTable("HierarchyTable", 3, GUILayout.GUITableFlags.Resizable))
        {
            GUILayout.TableSetupColumn("👁");
            GUILayout.TableSetupColumn("V");
            GUILayout.TableSetupColumn("Entities");

            GUILayout.TableHeadersRow();

            for (int i = 0; i < MapManager.CurrentMap.Entities.Count; i++)
            {
                if (MapManager.CurrentMap.Entities[i].Parent == null)
                {
                    GUILayout.TableNextRow();
                    DrawEntity(MapManager.CurrentMap.Entities[i]);
                }
            }
            GUILayout.EndTable();
        }
    }
}

private void DrawEntity(EntityObject entity)
{
    GUILayout.TableSetColumnIndex(0);
    GUILayout.Image(GUIDefaultImages.HierarchyVisibleIconID);
    GUILayout.TableSetColumnIndex(2);
    GUILayout.GUITreeNodeFlags flags = GUILayout.GUITreeNodeFlags.None;

    if (!entity.HasChilds())
        flags |= GUILayout.GUITreeNodeFlags.Leaf;

    if (GUILayout.TreeNode(entity.Name, flags | GUILayout.GUITreeNodeFlags.FramePadding))
    {
        var childs = entity.GetChilds();
        for (int i = 0; i < childs.Count; i++)
        {
            GUILayout.TableNextRow();
            DrawEntity(childs[i]);
        }
        GUILayout.TreePop();
    }
}
```

**Comment by ocornut** [comment]
Similar question as #6316, see Demo->Tables->Columns Flags for how to configure per-column indentation by using `ImGuiTableColumnFlags_IndentEnable` and `ImGuiTableColumnFlags_IndentDisable` flags in `TableSetupColumn()`.

It's true that it looks particularly strange if your tree is not in the first column!

**Comment by oscar7070** [comment]
Thanks, now it's works as expected!
