### ISSUE TITLE
DearImGui - RunnerParams- create an alternativeDockingLayout from dockingParams

### ISSUE THREAD

**Issue by algotron** [ocornut/imgui#7639]
### Version/Branch of Dear ImGui:

Version 1.90.5 (19050) , Branch: docking - from ImGui_Bundle

### Back-ends:

runner_sdl2.cpp

### Compiler, OS:

MacOs Apple Clang -std=gnu++20 -fPIC

### Full config/build information:

```
Dear ImGui 1.90.5 (19050)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __APPLE__
define: __GNUC__=4
define: __clang_version__=15.0.0 (clang-1500.3.9.4)
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl2
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000440
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigMacOSXBehaviors
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigWindowsMoveFromTitleBarOnly
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000140E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 14 fonts, Flags: 0x00000000, TexSize: 1024,1024
io.DisplaySize: 1400.00,950.00
io.DisplayFramebufferScale: 2.00,2.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 3.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

When a user rearranges (splits) the windows, and creates new docking splits I want to allow the new layout to be saved so that the user can switched back into that layout from the View menu at a later time after the layout has been changed at a later time.

However the new splitter layout that I see on the screen is not copied. I want to save the splitter layout as it is seen by the user.

My efforts:
-----------

After I have interactively split the windows by dragging them into new positions, I have tried to save the new layout from
    HelloImGui::GetRunnerParams()->dockingParams 
into
   HelloImGui::GetRunnerParams()->alternativeDockingLayouts

but the docking splits are not saved. When new splits are created interactively, those splits doe not appear in the 
   HelloImGui::GetRunnerParams()->dockingParams.dockingSplits 

Background:
-------------

I downloaded and compiled the example from Imgui_bundle. I then created my own minimal version of that project, stripping away the demo function code so the functions are there but do nothing (Lines 49-64 in the attached file which is modified from the imgui_bundle main.cpp)

I then added my own Imgui function "home_screen" at line 75. Home Screen displays the Current Layout, the Alternative Layouts, along with the number of windows and split in each.

The original layout is a simple tabbed layout, so there are no docking splits in it.

The docking splits are always zero.

The "Save layout" Button allows the Current Layout to be copied into an Alternative Layout with a new name. I added the home_scree function to a window at line 266.

The View menu sees the new layouts, and I can switch between layouts in the View menu, but the docking splits never duplicated.

How do I save the docking splits as seen by the user?

Attachments:
-------------

- The code
- A series of screenshots 1..5 illustrating the steps taken; refer to the file names.

Thank-you.

### Screenshots/Video:

[Imgui_test_code_main.cpp.zip](https://github.com/ocornut/imgui/files/15504971/Imgui_test_code_main.cpp.zip)
[5 Screenshots.zip](https://github.com/ocornut/imgui/files/15504974/5.Screenshots.zip)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Hello,
This seems like an issue to post in https://github.com/pthom/hello_imgui as I have no idea what those `dockingParams` and `alternativeDockingLayouts` things are, they seems to be higher level features of hello_imgui built using dear imgui apis.
Please post this to hello_imgui! Thank you
