### ISSUE TITLE
Lexical Oriented Pops

### ISSUE THREAD

**Issue by Nowayz** [ocornut/imgui#764]
After some thought I came to the conclusion that pops really are never logically or lexically separate(in any scenario I could imagine) from their counterparts. 

I propose a potential design where destructors will pop their objects automatically, allowing for cleaner and more digestible(visually modular) code layout.

**The example from imgui_demo.cpp:** 
```
ImGui::PushItemWidth(80);
ImGui::Text("Lists:");
static int selection[4] = { 0, 1, 2, 3 };
for (int i = 0; i < 4; i++)
{
    if (i > 0) ImGui::SameLine();
    ImGui::PushID(i);
    ImGui::ListBox("", &selection[i], items, IM_ARRAYSIZE(items));
    ImGui::PopID();
}
ImGui::PopItemWidth();
```

**Would become:**
```
{	ImGui::PushItemWidth(80);
	ImGui::Text("Lists:");
	static int selection[4] = { 0, 1, 2, 3 };
	for (int i = 0; i < 4; i++)
	{
		if (i > 0) ImGui::SameLine();
		ImGui::PushID(i);
		ImGui::ListBox("", &selection[i], items, IM_ARRAYSIZE(items));
	} /* Destructor for PushID automatically pops here */
} /* Destructor for PushItemWidth automatically pops here */
```

The lexical scoping in C++ compiler manages the stack for the programmer, the code becomes visually easier to interpret(in my opinion), and it becomes harder to create awful stack issues when modifying a huge user-interface function.

P.S.
If anybody can show a case where they are programmatically popping styles or objects I would be curious.  I couldn't come up with anything, though it could be my lack of creativity.

**Comment by ratzlaff** [comment]
In your example, you have not indicated where 'the pop' happens. You are still calling a bunch of ImGui:: functions. Which destructors are you relying upon?

**Comment by Nowayz** [comment]
In C++, destructors are automatically called at the end of a lexical scope.

**Comment by ratzlaff** [comment]
I see the edit to your comment, but still puzzled
ImGui::PushItemWidth(80) is a function call. 
Where are your objects being created on the stack?

**Comment by Nowayz** [comment]
I have no idea what you're insinuating other than that the design of the library will have to be changed, which is the whole point.  Otherwise you're going to have to be far more clear.

**Comment by adam4813** [comment]
Omar doesn't have the time to make drastic changes, as this isn't a full
time job nor is he subsidized to work on it.

**Comment by Nowayz** [comment]
This is a proposal, not a demand.  Does nobody understand?

**Comment by ratzlaff** [comment]
If I understand your proposal, you advocate the removal of the Pop() functions.
Your proposal provides no other details on how the design of the library should be changed.
Your proposal is to add curly braces and delete the lines ImGui::PopID(); and ImGui::PopItemWidth();
Your proposal adds no c++

**Comment by Nowayz** [comment]
Yes, I've already implemented this on my copy but was interested what people thought

**Comment by ratzlaff** [comment]
> Yes, I've already implemented this on my copy but was interested what people thought. 
So where are those details? What did you have to change?

**Comment by Nowayz** [comment]
My implementation is not online currently, but I'll explain what I did:

**Comment by ocornut** [comment]
You probably mean that the function would be replaced by a constructed variable (which would have a destructor).

Problems I see:
- break current code/api
- c++ centric means no obvious mapping for wrapper and other languages
- there's many cases where you want to push/pop accross function calls, so that would require two sets to be available in an already crowded api: two functions for those cases + a variable for your cases
- imgui doesnt really use destructors for its logic/flow so that would be a massive design change and make things less explicit

Note that you can always implement those (using a non conflicting name) as helpers in your own codebase if you want.

O.

**Comment by Nowayz** [comment]
In my approach: the function is just supplemented by constructed type with a macro; which is extensible and preserves modularity of codebase(also way less work).  Macros can end up being messy looking(WindowsNT Src) but are powerful tool for a flexible interface.

I'm not sure about pushing and popping between calls, as I've not designed such nightmare code myself, but I guess somebody is probably doing it.

Such a supplemental design as I mentioned could possibly aid in ease of integration with wrapper interface for other languages, where a similar system is implemented via scope of second language (though will have to think more about this).

**Comment by ocornut** [comment]
There's nothing "nightmareish" about pushing and popping out of scope, it is useful sometimes. e.g. implementing a PushMyButtonStyle() function would require dragging the scope logic along. ImGui design choices needs to not be a constraint to the user. 

In your example on the first post I don't even believe that the second piece of code is better than the first, for being less explicit. 

Count-wise majority of languages don't have scopes destructors.

You are still free to use them, but as replacement to existing function they are not fit for the library. If we add similar facility they would have to use another name, e.g `ImGui::ScopedItemWidth()`.

**Comment by Nowayz** [comment]
Scope-destructors no, but many can be made to perform immediate local variable garbage collecting which is going to serve the same purpose.  This is true for some by default, while others can be made to do such things.

Neither piece of code is intrinsically better than the other in terms of explicitivity, it allows for some visual separation and saves a little bit of typing time in some instances, but largely just makes it faster to discover where things are being destroyed.

**Comment by adam4813** [comment]
An example of calling push pop across function calls might be when parsing
a file and you have to throw an assertion or exception. The handling code
might have a pop counter it can use to make the gui tree structure valid
while breaking gracefully.

Not that I'm saying your parsing code should be doing gui work, just making
a more concrete example as you've requested.

**Comment by emoon** [comment]
In my case (as I already wrap ImGui) I have a some convince code for something similar to this:

```Rust
ui.tree_node("some node", |ui| {
   ui.text("foobar");
});
```

In this case the closure will only be called if user has expanded the node and then ``pop_tree`` will be called automatically.

**Comment by ocornut** [comment]
@Nowayz Shall we close this or is this an idea you would like to push for?

**Comment by Nowayz** [comment]
This is something I may push when I have the time to ensure suitable quality for contribution.  Can probably close this in the meantime though, I don't know my availability or timeframe
