### ISSUE TITLE
ImGui for HUD

### ISSUE THREAD

**Issue by ecraven** [ocornut/imgui#765]
Using DrawLists, would it be possible to use imgui to draw the entire HUD of a space game? Targetting reticule, direction indicators, frames around targets, various rotated icons, etc? Or is this something better left to other libraries?

**Comment by Nowayz** [comment]
The answer is yes, though if you don't require the use of any features this library has, why use it?

**Comment by ecraven** [comment]
This would be in addition to all the windowed ui, I really like the way immediate mode guis work, and would prefer to use it for everything 2d in the project :)

**Comment by ocornut** [comment]
Use whatever works for you!
I'm finding ImDrawList to be rather useful for various simple uses. In fact my game www.TheDragonsTrap is entirely rendered using ImDrawList. I'm using callback to change render state.

You might just to duplicate the code and adapt it to your project.

**Comment by ecraven** [comment]
Would you consider adding a few convenience methods (mainly for rotation) to the DrawList API?

**Comment by ocornut** [comment]
Depends what exactly.
I definitively would not add anything that would hurt performances of the current API.

**Comment by ecraven** [comment]
Oh, that was not my intention. I'll investigate, and post if I find out what I want exactly :) Thanks!
