### ISSUE TITLE
Old-style casts

### ISSUE THREAD

**Issue by ecraven** [ocornut/imgui#766]
There are some 40 "old-style casts" in imgui.h, which gcc complains about. Is there a reason for these, or could I send a PR that replaces them with static_cast<..>?

**Comment by ocornut** [comment]
I don't want c++ style casts.
You could adjust your warning settings to not be unnecessary pedantic (because this is a really unecessary and dumb warning), or we replace this block:

```
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wold-style-cast"
#endif
```
With GCC version.

**Comment by ecraven** [comment]
OK, clear enough, thanks for clarifying this! I'm mostly interested in not seeing any warnings, that block you pasted works nicely for that if adapted :)

**Comment by ecraven** [comment]
I'm closing this, there are several different warnings with current GCC, but it is probably best to just silence them directly where including imgui.h. Thanks for the comments!

**Comment by paulsapps** [comment]
Whats the issue with C++ casts in C++ only code?

**Comment by ocornut** [comment]
- they take more space (and look ugly imho),
- not everybody understands the subtleties and meaning of all of them, meaning you are raising the access bar to readability.
- they are often included in the loose/biased heuristic that C-style programmers use to detect smelly C++ code and stay away from it. I'd rather have the modern C++ zealots elects themselves to stay away from imgui than have the oldschool c/c++ zealots do that.

**Comment by ocornut** [comment]
@ecraven would you mind posting all the warning you are getting? (Along with your gcc version and command lines). I am still waiting to fix everything.
