### ISSUE TITLE
ImGui::CalcTextSize() Escaped Symbols

### ISSUE THREAD

**Issue by Patchu1i** [ocornut/imgui#7679]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: master

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 10, MSVC, Visual Studio 17 2022

### Full config/build information:

```
Dear ImGui 1.90.0 (19000)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1939
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx11
io.ConfigFlags: 0x00000000
io.MouseDrawCursor
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 17 fonts, Flags: 0x00000000, TexSize: 1024,1024
io.DisplaySize: 1920.00,1080.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

I am trying to use `ImGui::SameLine()` to right-align text containing a "%" symbol. To calculate the right-align position, I'm using `ImGui::CalcTextSize()`. As shown here:

```cpp
float padding = 150.0f;
ImGui::Text("Percent");
ImGui::SameLine(padding - ImGui::CalcTextSize("100%%").x);
ImGui::Text("100%%");
```

The problem is that `ImGui::CalcTextSize("100%%")` does not consider the escaped "%" symbol in the size, resulting in the text being short by the size of one character. I have tried many variations as shown in the MCVE code. The only way I can resolve this is by appending an additional `ImGui::CalcTextSize()` call with a disposable character. The provided image shows a breakdown of the MCVE code, with a red line indicating the targeted position to align to.

This is my first issue I've posted on Github so apologies in advanced if I missed something.

### Screenshots/Video:

![imgui_percent](https://github.com/ocornut/imgui/assets/168756592/35ba76b5-be15-4372-8919-169d5003c3db)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
	float padding = 150.0f;
	ImGui::Text("Percent");  // No Escape with %
	ImGui::SameLine(padding - ImGui::CalcTextSize("100%").x);
	ImGui::Text("100%");

	ImGui::Text("Percent");  // No Escape without %
	ImGui::SameLine(padding - ImGui::CalcTextSize("100").x);
	ImGui::Text("100");

	ImGui::Text("Percent");  // Escaped Calc & Text
	ImGui::SameLine(padding - ImGui::CalcTextSize("100%%").x);
	ImGui::Text("100%%");

	ImGui::Text("Percent");  // Escaped only Calc
	ImGui::SameLine(padding - ImGui::CalcTextSize("100").x);
	ImGui::Text("100%%");

	ImGui::Text("Desired");  // No Escape with disposable call
	ImGui::SameLine(padding - ImGui::CalcTextSize("100").x - ImGui::CalcTextSize("_").x);
	ImGui::Text("100%%");
ImGui::End();
```

**Comment by cfillion** [comment]
```cpp
const char *text { "100%" };
ImGui::CalcTextSize(text).x;
ImGui::TextUnformatted(text);
ImGui::Text("%s", text);
```

**Comment by ocornut** [comment]
`CalcTextSize()` does not take a format string.
As realistically you may want to dynamically format a string instead of always passing "100%" you should probably pre-format then call `TextUnformatted()`.
```cpp
char buf[64];
snprintf(buf, sizeof(buf), "%d%%", percentage);
ImGui::CalcTextSize(buf, ...);
ImGui::TextUnformatted(buf);
```

Some people use std:: facilities for formatting (because they dislike lightweight things), or the fmt library. I personally https://github.com/ocornut/Str as my own convenient wrapper, where it would become:

```cpp
Str30f buf("%d%%", percentage");
```
