### ISSUE TITLE
ImGui for multiple child windows WIN API

### ISSUE THREAD

**Issue by Ayushkr3** [ocornut/imgui#7695]
### Version/Branch of Dear ImGui:

Version 1.90.2, (master)

### Back-ends:

imgui_impl_dx11cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 11 + Visual studio 2017

### Details:

I have a scenario where there is a Single Parent(skeleton) windows and 3 child windows. the parentwindow does not contain any ImGui widget or anything ImGui related but it does contain Windows procedure now according to this [https://github.com/ocornut/imgui/issues/4952](url)
It is said that you can use multiple context and use SetCurrentContext for each windows 
but which windows handle should i put in `ImGui_ImplWin32_Init(hwnd);`,Parent or child. function and should create multiple d3d devices and device context for each windows .Also how ImGui will get correct windows message for each child window by `ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam)` for inputs.Since i am not very good in UI and designing it would be generous if someone can answer in more beginner friendly manner

**Comment by GamingMinds-DanielC** [comment]
There is not enough information about your goal to make any meaningful suggestions, but your approach sounds overly complicated.

The example sources show you how to use a single window with ImGui. You can do that with a child window if needed, or with multiple independently if you use contexts and switch them at the right time. Distributing the correct messages from different windows to the right contexts is your responsibility, you are in control of everything that goes into the library.

Sorry, but if you need it to be beginner friendly, maybe you shouldn't jump straight into advanced stuff. Juggling multiple contexts will not be beginner friendly. Maybe you can use the docking branch and accomplish what you need with a single window.

**Comment by Ayushkr3** [comment]
@GamingMinds-DanielC 
Yes I over complicated simple things but what I was going for is this 


![image](https://github.com/ocornut/imgui/assets/56124793/d62c0ef2-8524-4874-9616-5af4cfbea1ad)


All ImGui things are in their own separate child Windows and Parent window contain all windows. I did this thinking that could have more control like file dropping for explorer and stuff but I was confused about windows Procedure and how to set context for 3 windows and should i create d3d devices and context for all windows

**Comment by GamingMinds-DanielC** [comment]
That type of UI is what the docking branch is for. Switch to the docking branch, use only one Win32 window and one ImGui context. Set up a dockspace over the main viewport, then submit your ImGui windows and dock them as you see fit. That will save you a lot of headaches.

**Comment by Ayushkr3** [comment]
@GamingMinds-DanielC  Does docking support file drag drop System? and the documentation is so less Its very hard for me to understand stuff

**Comment by GamingMinds-DanielC** [comment]
Drag & drop works exactly like in the master branch. If you want to be able to drop files from the Windows explorer, you have to implement that, just like you would have to implement it when using the master branch.

What do you mean with "documentation is so less"? The few things you need to do for docking are documented in the header file. You can also take a look into the demo window, it has a docking demo as well in its "Examples" menu.
