### ISSUE TITLE
Widget Rotations

### ISSUE THREAD

**Issue by rifkikesepara** [ocornut/imgui#7699]
### Version/Branch of Dear ImGui:

Version 1.9, Branch: master

### Back-ends:

imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11+ MSVC 22

### Details:

I am trying to implement ImGUI into my in-game UI system but want to rotate any widget that ImGUI has. So I was wondering if there is already a built-in integration for that and if not how can I implement it?

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
ImGui::Button("Example Rotated Button",
{100.0f,100.0f}, //size
30.0f //rotation angle
);
ImGui::End();
```

**Comment by PathogenDavid** [comment]
This is not currently possible. Dear ImGui assumes all widgets are axis-aligned rectangles for the purposes of hit testing, so it would not be straightforward to add support for this either.
