### ISSUE TITLE
Center along single axis only (ie, horizontal)

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#770]
Currently I'm using     ImGui::SetNextWindowPosCenter(); to place my modal dialog in to the middle of the screen (it dynamically grows vertically). 

I would prefer to hard-code the vertical position of the dialog but have the horizontal position determined by ImGui; ie,

   SetNextWindowPosCenter(-1,20); // center horizontally, fixed vertical position

Apologies if I've missed something obvious.

**Comment by ocornut** [comment]
There's no official way currently but if you look at `SetNextWindowPosCenter()` you'll find out it justs pass -FLT_MAX on each axis as a key to request centering. So (-FLT_MAX, 20) may work.

**Comment by inflex** [comment]
Thanks @ocornut , I was diving in to those areas but I am glad to hear I was heading down the "right direction" :+1:

**Comment by inflex** [comment]
Okay, I made something work but I had to rework the imgui.cpp file. 

Now I can make calls like; 	SetNextWindowPos(ImVec2( -FLT_MAX, 20)); and it'll center only on the horizontal.
```

    // Process SetNextWindow***() calls
    bool window_pos_set_by_api = false, window_size_set_by_api = false;
    if (g.SetNextWindowPosCond)
    {
        const ImVec2 backup_cursor_pos = window->DC.CursorPos;                  // FIXME: not sure of the exact reason of this saving/restore anymore :( need to look into that.
        if (!window_was_active || window_appearing_after_being_hidden) window->SetWindowPosAllowFlags |= ImGuiSetCond_Appearing;
        window_pos_set_by_api = (window->SetWindowPosAllowFlags & g.SetNextWindowPosCond) != 0;
        if (window_pos_set_by_api && ImLengthSqr(g.SetNextWindowPosVal - ImVec2(-FLT_MAX,-FLT_MAX)) < 0.001f)
        {
            window->SetWindowPosCenterWanted = true;                            // May be processed on the next frame if this is our first frame and we are measuring size
            window->SetWindowPosAllowFlags &= ~(ImGuiSetCond_Once | ImGuiSetCond_FirstUseEver | ImGuiSetCond_Appearing);
        }
		// INFLEX20160806
		else if ((g.SetNextWindowPosVal.x == -FLT_MAX)||(g.SetNextWindowPosVal.y == -FLT_MAX))
		{
			window->SetWindowPosCenterWanted = true;
            window->SetWindowPosAllowFlags &= ~(ImGuiSetCond_Once | ImGuiSetCond_FirstUseEver | ImGuiSetCond_Appearing);
		}
        else
        {
            SetWindowPos(window, g.SetNextWindowPosVal, g.SetNextWindowPosCond);
        }
        window->DC.CursorPos = backup_cursor_pos;
        g.SetNextWindowPosCond = 0;
    }

```

...and a bit further on...


```

        bool window_pos_center = false;
        window_pos_center |= (window->SetWindowPosCenterWanted && window->HiddenFrames == 0);
        window_pos_center |= ((flags & ImGuiWindowFlags_Modal) && !window_pos_set_by_api && window_appearing_after_being_hidden);
        if (window_pos_center)
        {
			ImVec2 centerv = fullscreen_rect.GetCenter() - window->SizeFull * 0.5f;
			if (g.SetNextWindowPosVal.x != -FLT_MAX) centerv.x = g.SetNextWindowPosVal.x;
			if (g.SetNextWindowPosVal.y != -FLT_MAX) centerv.y = g.SetNextWindowPosVal.y;
			SetWindowPos(ImMax(style.DisplaySafeAreaPadding, centerv));
        }

```

**Comment by ocornut** [comment]
This needs to be patched in properly by replacing `SetWindowPosCenterWanted` with flags for each axis.

**Comment by inflex** [comment]
> This needs to be patched in properly by replacing SetWindowPosCenterWanted with flags for each axis.

I'll leave that in your capable hands :+1:

**Comment by ocornut** [comment]
Err, I would appreciate if people were putting the time to make mergeable-quality contributions. I'm already working 15+ hours a week on this. I can't handle every features and support requests.

**Comment by inflex** [comment]
My apologies, happy to put together a patch.

**Comment by ocornut** [comment]
Sorry I'm being a bit harsh sometimes but it's been rather hard for me to maintain and handle all requests.

**Comment by inflex** [comment]
My only concern was my lack of intimate knowledge of the preferred flag / syntax / design so as to do it properly.  I guess this is one way to find out.

I've submitted the PR.  There was more time spent getting my project to change over to my fork  than doing the changes.

https://github.com/ocornut/imgui/pull/771

(Completely understand the work strain - full time repair job here and the night is spent coding)

**Comment by ocornut** [comment]
Closing this old issue as it was solved by the Pivot parameter of SetNextWindowPos(), see details in
https://github.com/ocornut/imgui/pull/771#issuecomment-396915210
