### ISSUE TITLE
Created Docked layout only using `imgui.h`

### ISSUE THREAD

**Issue by matthewcrews** [ocornut/imgui#7700]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: docking

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11 MSVC 2022

### Full config/build information:

Dear Imgui -> Dear Bindings -> Odin Imgui

dear_bindings: https://github.com/dearimgui/dear_bindings 
Odin Imgui: https://gitlab.com/L-4/odin-imgui

### Details:

**My Issue/Question:**

I am attempting to create the layout that I have included in a screenshot. It is made up of a host window with docked windows. Each red box would be a separate window. I have seen examples of people doing something similar, but in all of those cases, `imgui_internal.h` was used. Currently, `dear_bindings` only wraps the `imgui.h` file which means the `Odin Imgui` library does not expose that functionality. Is it possible to create a layout like the one I show in the screenshot just using the API exposed in the `imgui.h` file? Everything I have seen uses the `DockBuilder` family of functions that are only in the `imgui_internal.h` file.

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/1593215/2f898d18-12f7-4a2c-b706-da19dd9e8bc1)

**Comment by ocornut** [comment]
It’s not possible.
It’s an issue that dear bindings doesn’t support internals yet, feel free to add a comment in the dedicated thread there (without spamming).

In the meanwhile, if you temporarily moved those function declarations to imgui.h and ran dear bindings it would likely generate the correct usable bindings anyhow.

**Comment by matthewcrews** [comment]
Thanks! That's what I need to know.
