### ISSUE TITLE
Hantverk'n Video Game Graphics and Testing Settings GUI

### ISSUE THREAD

**Issue by Teknologicus** [ocornut/imgui#7707]
### Version/Branch of Dear ImGui:

Version 1.90.9

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp

### Compiler, OS:

gcc version 13.2.1 20230801 (GCC), Manjaro Linux

### Details:

Screenshot

### Screenshots/Video:

![+7j1Vb](https://github.com/ocornut/imgui/assets/10877045/f2849884-86e5-495d-9fdb-a2e4c48114d3)
![o5oaMV](https://github.com/ocornut/imgui/assets/10877045/10a6fa32-7234-4a0b-b1df-58970221ce9e)
![UntitledS](https://github.com/ocornut/imgui/assets/10877045/4f08f3eb-90b3-489b-ad05-7109cf7c8c1b)
![Untitled](https://github.com/ocornut/imgui/assets/10877045/d45fb370-dad9-49f9-a5a5-93108404ed26)
https://teknologicus.itch.io/hantverkn

**Comment by Teknologicus** [comment]
Posted to wrong area

**Comment by ocornut** [comment]
Please post there and we can then delete this topic :)
Thanks!

**Comment by Teknologicus** [comment]
Done.
