### ISSUE TITLE
Question: fine-tuning the window scrollbar

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#7709]
### Version/Branch of Dear ImGui:

1.90.6

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Windows 10

### Details:

Can you please tell me if Imgui has a function for adding “arrows” to fine-tune window scrolling?
It’s just that when there is a lot of “content” in the window, scrolling with the slider is very inaccurate - it’s difficult to position and find the desired element in the window, it constantly skips.

Of course, I completely made my own scrollbar by drawing them using ImGui::GetWindowDrawList() and setting up the logic, but this is not very convenient to use; it would be much more convenient and easier to use an already existing scrollbar with fine tuning.

**Comment by ocornut** [comment]
Since 1.90.8 scrollbar have been changed to scroll page by page when clicking outside the grab. (#7328)
Would that help?

**Comment by ElectroidDes** [comment]
> Since 1.90.8 scrollbar have been changed to scroll page by page when clicking outside the grab. (#7328) Would that help?

Thanks, I checked it and it definitely improves the positioning accuracy of the scrollbar :)

**Comment by ElectroidDes** [comment]
scroll page works with this simple example:

```
   static int size = 10000;

    ImGui::Begin("Window text 1");

    for (int i = 0; i < size; ++i) 
    {
        ImGui::Text("This is line number %d", i);
    }
    ImGui::End();
```

However, when I try to use the same code with the ImGuiListClipper class, scrolling across the page doesn't seem to work - it scrolls more than one page:

```
    ImGui::Begin("Window text 2");

    ImGuiListClipper clipper;

    clipper.Begin(size, ImGui::GetTextLineHeight());

    while (clipper.Step())
    {
        for (int i = clipper.DisplayStart; i < clipper.DisplayEnd; ++i)
        {
            ImGui::Text("This is line number %d", i);
        }
    }

    clipper.End();

    ImGui::End();
```

**Comment by GamingMinds-DanielC** [comment]
> Perhaps I misunderstand something.

You are giving the clipper an explicit height that is too small, therefore it thinks that more lines will fit. `GetTextLineHeight()` will give you only the height of a line itself without the spacing to the next line, try `GetTextLineHeightWithSpacing()` instead.

**Comment by ElectroidDes** [comment]
> > Возможно, я что-то неправильно понимаю.
> 
> Вы задаете клипперу слишком маленькую высоту, поэтому он думает, что поместится больше линий. даст вам только высоту самой строки без интервала до следующей строки, попробуйте вместо этого.`GetTextLineHeight()``GetTextLineHeightWithSpacing()`

It worked. Thank you very much!
