### ISSUE TITLE
Are there ImGui APIs that can throw?

### ISSUE THREAD

**Issue by alien-brother** [ocornut/imgui#7711]
### Version/Branch of Dear ImGui:

Version 1.90.8, Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx11.cpp (the question stands for other backends as well)

### Compiler, OS:

Windows 11, Visual Studio 2022

### Full config/build information:

Any

### Details:

**My Issue/Question:**

Are there ImGui APIs that can throw? It would seem that there aren't? However, ImGui does not use `noexcept`, so maybe I'm missing a piece of information?

**Comment by ocornut** [comment]
Nothing does throw except maybe calls to IM_NEW() depending on your new() setup.

**Comment by alien-brother** [comment]
If I'm not touching anything around `IM_NEW()`, it cannot throw, right? By default, it seems to be doing placement `new` in a buffer created by `malloc()`.

**Comment by ocornut** [comment]
Yes that's correct.

**Comment by ocornut** [comment]
Closing as answered.
