### ISSUE TITLE
Flick gesture.

### ISSUE THREAD

**Issue by oxffffffff** [ocornut/imgui#773]
Hi,

Is it possible to implement a flickable control using imgui? Something like Qt's flickable item?

http://doc.qt.io/qt-5/videos/flickable.mp4

Thanks.

**Comment by ocornut** [comment]
I am not sure I understand the question. What's a flickable control?
Do you just want to adjust a scrolling/offset by holding the mouse?

**Comment by oxffffffff** [comment]
Thanks for quick reply.

Here is more info, please read "Detailed Description" section.
http://doc.qt.io/qt-5/qml-qtquick-flickable.html

Thanks.

**Comment by ocornut** [comment]
Well it is just a matter of adjusting a position to display things from.

For example in one of my applet I do this. 
```
ImGui::Dummy(CANVAS_SIZE);
if (ImGui::IsItemHovered() && ImGui::IsMouseDown(2))
    anim_pan += ImGui::GetIO().MouseDelta;
```
That's over a given item (the item here is a dummy because I do all the drawing myself).
Or over all the "void" part (not over another widget) of a given window:
```
if (ImGui::IsWindowHovered() && !ImGui::IsAnyItemHovered() && ImGuI::IsMouseDown(2))
    anim_pan += ImGui::GetIO().MouseDelta;
```

**Comment by oxffffffff** [comment]
Got it, that's like scrolling items, may be i should start a timer on mouse release and set the anim_pan periodically to give a flick gesture. I will try that. Hope it makes sense.

Thanks.

**Comment by oxffffffff** [comment]
I will try to animate and see how it work.. I will close this issue now, will contact you if i need any help.

Thanks.
