### ISSUE TITLE
Wrong "Number of Segment" value in Demo Window.

### ISSUE THREAD

**Issue by JTtNinjaCode** [ocornut/imgui#7731]
### Version/Branch of Dear ImGui:

Version 1.90, Branch: docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl.cpp

### Compiler, OS:

windows 10

### Full config/build information:

```
Dear ImGui 1.90.6 (19060)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1939
define: _MSVC_LANG=201703
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000443
 NavEnableKeyboard
 NavEnableGamepad
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

In demo window > style editor > rendering > circle tessellation max error. When I drag to 5.00, N value in popup with "R: 70" is wrong, please check the picture, N should be 12.

### Screenshots/Video:

![image](https://github.com/ocornut/imgui/assets/50322815/720f8e4d-16d4-47d8-afe0-a68857e06d10)

### Minimal, Complete and Verifiable Example code:

none

**Comment by ocornut** [comment]
Thanks, I've determined that it is not easily possible to compute the exact amount here, so I've amended the demo with aab27130a to suggest the number is indicative and may be imprecise.
