### ISSUE TITLE
Can I get imgui to run without an imgui window?

### ISSUE THREAD

**Issue by TheSlugInTub** [ocornut/imgui#7738]
### Version/Branch of Dear ImGui:

master

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Windows 10 + MSVC

### Details:

I'm trying to make a game engine and I am wondering if you can display imgui widgets, without an imgui window. Meaning imgui would just render straight to the GLFW window.

**Comment by GamingMinds-DanielC** [comment]
You need a window. But you can disable all of its decorations and its background (take a look at window flags for that) and make it cover everything (set window position and size accordingly).

**Comment by ocornut** [comment]
However please note that even if the window has a transparent background, the entirety of the window will catch imgui inputs, so you cannot have another imgui window behind it.
