### ISSUE TITLE
Detect when Combo() opened

### ISSUE THREAD

**Issue by zMidair** [ocornut/imgui#7739]
### Version/Branch of Dear ImGui:

Version 1.90

### Back-ends:

n/a

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

**How can I detect when a Combo() is opened?**

Hello, by opened I mean when its clicked and its items are shown.

### Minimal, Complete and Verifiable Example code:

```cpp
if (ImGui::Combo("Clickpack", &clickpack.selectedClickpack, clickpack.clickpackList.data(), clickpack.clickpackList.size())) 
{}
```

**Comment by GamingMinds-DanielC** [comment]
If you can rework your call to `Combo()` to a `BeginCombo()` / `EndCombo()` pair, the combo is open if `BeginCombo()` returns true. You would then have to submit your items yourself, but you can look at the `Combo()` implementation for how to do that.

If you want to keep using the more compact `Combo()` function, you can calculate the popup id with `ImHashStr("##ComboPopup", 0, GetItemID())` and check if that popup is currently open.

**Comment by ocornut** [comment]
> How can I detect when a Combo() is opened?

It's also worth explaining why you need this, as this might be a [XY Problem](https://xyproblem.info/) question.

**Comment by zMidair** [comment]
> > How can I detect when a Combo() is opened?
> 
> It's also worth explaining why you need this, as this might be a [XY Problem](https://xyproblem.info/) question.

I need this since im using the Combo to choose a file in a folder and I want to update the list when the Combo is opened.

**Comment by GamingMinds-DanielC** [comment]
> Can you give me an example?

As I said, you can look at the implementation of `Combo()` for an example of how to use those functions. After all, that is just a wrapper for the step by step approach. Here is the exact place:
https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp#L1951-L1978

**Comment by zMidair** [comment]
> > I need this since im using the Combo to choose a file in a folder and I want to update the list when the Combo is opened.
> 
> Then you should use `if (ImGui::IsWindowAppearing())`

Doesnt it need a parameter? Or where should I put it? Before or after the Combo is created

**Comment by zMidair** [comment]
> > Can you give me an example?
> 
> As I said, you can look at the implementation of `Combo()` for an example of how to use those functions. After all, that is just a wrapper for the step by step approach. Here is the exact place: https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp#L1951-L1978
> 
> As Omar hinted at, you can use `IsWindowAppearing()` to test if a window has just been opened. Right after `BeginCombo()` returns true is the best place for that, then you are testing if the opened popup is just appearing.

Alr thanks, I will try this
