### ISSUE TITLE
Backends/OpenGL3 1.90.8 font texture not recreated

### ISSUE THREAD

**Issue by mlauss2** [ocornut/imgui#7748]
### Version/Branch of Dear ImGui:

Version 1.90.8

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_sdl2.cpp

### Compiler, OS:

Linux/GCC

### Details:

**My Issue/Question:**

1.90.8/OpenGL3 backend: After invalidating the font atlas, no fonts are displayed after NewFrame().
This quick hack here fixes it for me, but I'm not certain whether it's the right thing to do:

```diff --git a/backends/imgui_impl_opengl3.cpp b/backends/imgui_impl_opengl3.cpp
index 58603a047..fc20afb73 100644
--- a/backends/imgui_impl_opengl3.cpp
+++ b/backends/imgui_impl_opengl3.cpp
@@ -402,6 +402,8 @@ void    ImGui_ImplOpenGL3_NewFrame()
 
     if (!bd->ShaderHandle)
         ImGui_ImplOpenGL3_CreateDeviceObjects();
+    if (!bd->FontTexture)
+        ImGui_ImplOpenGL3_CreateFontsTexture();
 }
 
```

**Comment by ocornut** [comment]
I've pushed 404af57, thanks!
It hasn't been not fully specced, but since the OpenGL backend offer a DestroyFontTexture function this makes sense.
When we finish #3761 we will go through this in more details for all backend.
