### ISSUE TITLE
Applying style to a group

### ISSUE THREAD

**Issue by ecraven** [ocornut/imgui#775]
Is there a way to apply styling (background colour, hovering colour, borders) to a BeginGroup/EndGroup block? To create "custom widgets" from the normal building blocks? So you can just drop an image and some text in a group, and handle that as "one widget" easily.

**Comment by ocornut** [comment]
Hello,

You can use `PushStyleCol`, `PushStyleVar` / `PopStyleCol`, `PopStyleVar` to manipulate style for a block of code. `BeginGroup()` is a tool for layout mostly.

**Comment by ecraven** [comment]
Which ImGuiCol would I use to set the background of something I added to the draw list with AddText? Or for a Selectable?

**Comment by ocornut** [comment]
Oh I see what you mean.
You can't easily render things out of order. If you can obtain the bounding box in advance you can render it yourself.

You can use the low-level `ImDrawList::ChannelsSplit()` api to perform out of order rendering:
```
draw_list->ChannelsSplit(2);
draw_list->ChannelsSetCurrent(1);
// render group content
draw_list->ChannelsSetCurrent(0);
// render a background quad
draw_list->ChannelsMerge();
```
It is a little inefficient just to do that.

**Comment by ocornut** [comment]
@ecraven Are you happy with this?

**Comment by ocornut** [comment]
@ecraven Revisiting this thread it seems ever more confusing as I think we are talking about different things and even your original question is referring to different things.

> So you can just drop an image and some text in a group, and handle that as "one widget" easily.

This is a layout/logic question not a style question, BeginGroup() pretty much does that kind of stuff. 

For style, if you have frequent changes you can make your own helper functions to push different Style values on the stack. So you can push the style changes, call BeginGroup(), and later EndGroup, PopStyleXXX.

If you indeed need to draw the background _after_ the content you'd need to use different DrawList or the channel splitting mechanism. If you can draw the background _before_ the content, aka you can calculate the size in advance, then it's just a matter of using the ImDrawList API and call AddRectFilled(). You don't need a specific ImGuiCol enum value for that, just use the color that you see fit for your background.

Or technically you can also record the current vertex number, submit a dummy rectangle as background, submit your content and only after you are done with the content retroactively poke the background vertices to resize them. This may be one of the best solution but it's a bit low-levelly and not obvious. I added note in my todo list that we may want to add helpers/docs to make that sort of thing more natural down the line.

Closing this as I think everything as been answered.
