### ISSUE TITLE
Correct way to disable window draging for a custom widget

### ISSUE THREAD

**Issue by Organic-Code** [ocornut/imgui#7750]
### Version/Branch of Dear ImGui:

Version 1.90.8, Branch: master

### Back-ends:

Imgui-sfml

### Compiler, OS:

Linux, Clang

### Full config/build information:

```
Dear ImGui 1.90.8 (19080)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: IMGUI_DISABLE_OBSOLETE_KEYIO
define: __linux__
define: __GNUC__=4
define: __clang_version__=17.0.6 
--------------------------------
io.BackendPlatformName: imgui_impl_sfml
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000007
 HasGamepad
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1600.00,900.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

I am trying to implement a widget that includes text editing.
As such, when click & drag occurs, I want my widget to select text.

I am not sure of how to disable window dragging when the click&drag started on the widget.
Using ``InvisibleButton`` does work for that, but then ``ImGui::IsMouseDragging(0)`` always return false

Here is what I have for now:
```cpp
    const ImGuiID imgui_id = ImGui::GetCurrentWindow()->GetID(id_str.c_str());
    ImGui::PushID(imgui_id);

   // widget code


    ImGui::Dummy(...);

    if (ImGui::IsItemHovered()) {
        if (ImGui::IsWindowFocused()) {
            ImGui::SetHoveredID(imgui_id);
        }
    }

    ImGui::PopID();
```

Which kind of works, but only if the window has the focus.
I could just remove the ``if (ImGui::IsWindowFocused())``, but that means I have to manually call ``ImGui::FocusWindow(...)`` whenever a click occurs over the widgets, otherwise the window does not take focus anymore.

Is that actually the correct way to do so? Is there a way to do this without using ``imgui_internal``?
Should I instead use ``InvisibleButton`` and handle mouse dragging differently?

### Minimal, Complete and Verifiable Example code:

```cpp
        auto show_wid = [](){
            ImGui::PushID(1);
            ImGui::Dummy({500, 500});
    
            if (ImGui::IsItemHovered()) {
                ImGui::SetMouseCursor(ImGuiMouseCursor_TextInput);
                if (ImGui::IsWindowFocused()) 
                    ImGui::SetHoveredID(1);
            }
            ImGui::PopID();
        };
           
        if (ImGui::Begin("win1")) {
            show_wid();
        }
        ImGui::End();
    
        if (ImGui::Begin("win2")) {
            show_wid();
        }
        ImGui::End();
```

**Comment by ocornut** [comment]
> Should I instead use InvisibleButton and handle mouse dragging differently?

Yes.

The correct way is to use `InvisibleButton()`, as `Dummy()` doesn't claim input. 
Right now you are trying to recreate what a normal widget would do, with probably extra bugs.

I see no reason for IsMouseDragging() not working with InvisibleButton(). I am pretty sure without testing that InvisibleButton() + IsMouseDragging(0) works since they are unrelated and don't poll same data. IsMouseDragging() doesn't consider item interaction. You probably want to use IsItemActive().

**Comment by Organic-Code** [comment]
It must be an issue with the rest of my code then
I should’ve made an MCVE with ``InvisibleButton`` as well, as it indeed does work with ``IsMouseDragging``.

I’ll dig into that; thank you, and sorry for the inconvenience

**Comment by ocornut** [comment]
I think we are lacking good examples to implement custom widgets solely with public API.
But basically using `InvisibleButton()` + `IsItemActive()` you can already do a lot. 
Check "Demo->Widgets->Querying Item Status" section for a recap of the main signal but `IsItemActive()` is the more commonly used.
