### ISSUE TITLE
Latest SDL3 changes break SDL3 backend build. SDL_SetTextInputRect renamed to SDL_SetTextInputArea

### ISSUE THREAD

**Issue by adrian-purser** [ocornut/imgui#7754]
### Version/Branch of Dear ImGui:

Version 1.90.9, Branch: docking

### Back-ends:

imgui_impl_SDL3.cpp + imgui_impl_OpenGL3.cpp

### Compiler, OS:

Linux + GCC 14.1.1

### Full config/build information:

```
Dear ImGui 1.90.9 WIP (19083)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=202002
define: IMGUI_DISABLE_OBSOLETE_KEYIO
define: __linux__
define: __GNUC__=14
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl3
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000480
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 2 fonts, Flags: 0x00000000, TexSize: 512,256
io.DisplaySize: 1024.00,768.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 1.00,1.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 3.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

The latest version of SDL3 has replaced SDL_SetTextInputRect with SDL_SetTextInputArea.  SDL_SetTextInputArea also takes an extra parameter for cursor (the offset of the current cursor location relative to `rect->x`, in window coordinates)

The relevant commit is -

> SDL_SetTextInputRect() has been renamed to SDL_SetTextInputArea()
> The new function includes the cursor position so IME UI elements can be placed relative to the cursor, as well as having the whole text area available so on-screen keyboards can avoid it.
> 

This is used in imgui_impl_sdl3.cpp on line 154.

**Comment by ocornut** [comment]
Thank you! Fixed by ccf3ee6
