### ISSUE TITLE
Cann't display text with  big font size

### ISSUE THREAD

**Issue by xingyun86** [ocornut/imgui#7766]
### Version/Branch of Dear ImGui:

Version 1.90.9, Branch: all (master/docking/etc.)

### Back-ends:

imgui_impl_all.cpp + imgui_impl_all.cpp

### Compiler, OS:

windows 10 + msvc

### Full config/build information:

cmake build

### Details:

**My Issue/Question:**

```
//set font size to 88 or great size
ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\ArialUni.ttf", 88.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());
```

### Screenshots/Video:

![图片](https://github.com/ocornut/imgui/assets/8170682/3af67632-a012-4e75-a157-1d585d765ce0)

### Minimal, Complete and Verifiable Example code:

```cpp
//set font size to 88 or great size
ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\ArialUni.ttf", 88.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());
```

**Comment by ocornut** [comment]
See https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#4-font-atlas-texture-fails-to-upload-to-gpu

With the current system it is unlikely you can use GetGlyphRangesChineseFull() with such a big size. See link above for workarounds.

**Comment by xingyun86** [comment]
> See https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#4-font-atlas-texture-fails-to-upload-to-gpu
> 
> With the current system it is unlikely you can use GetGlyphRangesChineseFull() with such a big size. See link above for workarounds.

When I use freetype2.xx, 360 or greater font size also ok!. But I don't know how replace it with freetype in imgui.

**Comment by xingyun86** [comment]
> > See https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#4-font-atlas-texture-fails-to-upload-to-gpu
> > With the current system it is unlikely you can use GetGlyphRangesChineseFull() with such a big size. See link above for workarounds.
> 
> When I use freetype2.xx, 360 or greater font size also ok!. But I don't know how replace it with freetype in imgui.

Ok. I did it now. Use freetype. Thanks a lot!

**Comment by xingyun86** [comment]
> > > See https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#4-font-atlas-texture-fails-to-upload-to-gpu
> > > With the current system it is unlikely you can use GetGlyphRangesChineseFull() with such a big size. See link above for workarounds.
> > 
> > 
> > When I use freetype2.xx, 360 or greater font size also ok!. But I don't know how replace it with freetype in imgui.
> 
> Ok. I did it now. Use freetype. Thanks a lot!
![image](https://github.com/ocornut/imgui/assets/8170682/939f7801-7d7d-4f68-97de-20753fcc1800)

**Comment by xingyun86** [comment]
> See https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#4-font-atlas-texture-fails-to-upload-to-gpu
> 
> With the current system it is unlikely you can use GetGlyphRangesChineseFull() with such a big size. See link above for workarounds.

I think font control: When I draw string, alloc texture with string。Now when I add ttf， and Imgui create all texture。But I real use           
a little。
