### ISSUE TITLE
Assertion failed: g.frameCount == 0

### ISSUE THREAD

**Issue by TheSlugInTub** [ocornut/imgui#7767]
### Version/Branch of Dear ImGui:

docking

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Windows 10 + MSVC

### Details:

I switched from the master branch to the docking branch in my C++ project and now it's giving me this error which it didn't give before: `Assertion failed: (g.FrameCount == 0 || g.FrameCount == g.FrameCountPlatformEnded) && "Forgot to call UpdatePlatformWindows() in main loop after EndFrame()?` My config flags are set to this:
```
	io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;  
	io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;      
	io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;
```
How do I fix this?

**Comment by ocornut** [comment]
What the assert message says.. If you enable `ImGuiConfigFlags_ViewportsEnable` you need to be calling `ImGui::UpdatePlatformWindows()` and likely `ImGui::RenderPlatformWindowsDefault()` in your main loop. Refer to example code.
