### ISSUE TITLE
a magical problem about ImGui_ImplWin32_EnableAlphaCompositing api

### ISSUE THREAD

**Issue by iKunCai** [ocornut/imgui#7769]
### Version/Branch of Dear ImGui:

Branch master  1.90.9

### Back-ends:

imgui_impl_dx9.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 11 +MSVC 2022

### Details:

**My Issue/Question:   i used intel 13980hx + 4090 laptop gpu     and use ImGui_ImplWin32_EnableAlphaCompositing

I write an app use topmost and will be moving window overlay on the game. like  cs2. However, i found a little strange..

when i use mix gpu mode(intel igpu +4090 both work) run  game in 4090,the  imgui will  be 100% transparent.which means,i can't see imgui . if this game/or any app  run in igpu(i guess) i can see imgui that is not transparent.

if i did not use ImGui_ImplWin32_EnableAlphaCompositing.  i can see imgui normally.

and also, i don't use mix gpu mode.(which means i only use 4090 gpu)  ImGui_ImplWin32_EnableAlphaCompositing or not.  work everything fines...

it is nvidia bug? or windows?

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by iKunCai** [comment]
//it's use ImGui_ImplWin32_EnableAlphaCompositing

https://github.com/ocornut/imgui/assets/22653841/e8f6523f-f57b-416b-9284-a3ef0262f111

**Comment by iKunCai** [comment]
//it's NOT use ImGui_ImplWin32_EnableAlphaCompositing

https://github.com/ocornut/imgui/assets/22653841/a4d70973-24bf-40a9-bfe7-88578b99c3ee

**Comment by ocornut** [comment]
Sorry but #1586
