### ISSUE TITLE
Automatic button color change on hover

### ISSUE THREAD

**Issue by ElectroidDes** [ocornut/imgui#7773]
### Version/Branch of Dear ImGui:

Version 1.90.8

### Back-ends:

Raylib

### Compiler, OS:

Windows 10

### Details:

When a simple button is created:

```
    ImGui::Begin("Main Window");

    ImGui::Button("Button_1");

    ImGui::End();
```
 when you hover the mouse cursor over it and left-click the mouse, the color of the button changes automatically by default. Sometimes this is very inconvenient, since I have my own collision and click handler.

Is it possible to somehow disable this behavior by default?

**Comment by GamingMinds-DanielC** [comment]
You can retrieve the color for `ImGuiCol_Button` and push it to the style color stack for `ImGuiCol_ButtonHovered` (and `ImGuiCol_ButtonActive` if needed) for the button in question. Alternatively you could draw the button yourself or even make a custom widget if you need full control.

**Comment by ocornut** [comment]
Closing as answered, thanks Daniel!

Reference code:
```cpp
ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImGui::GetStyle().Colors[ImGuiCol_Button]);
ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImGui::GetStyle().Colors[ImGuiCol_Button]);
ImGui::Button("Button");
ImGui::PopStyleColor(2);
```
