### ISSUE TITLE
SDL_SetTextInputArea (in ImGui 1.90.9) no longer available >>>  SDL_SetTextInputRect 

### ISSUE THREAD

**Issue by NostraMagister** [ocornut/imgui#7775]
### Version/Branch of Dear ImGui:

Version 1.90.9 master

### Back-ends:

imgui_impl_SDL3.cpp + imgui_impl_Vulkan.cpp

### Compiler, OS:

Windows 11 MSVC, Linux GNU

### Full config/build information:

Occurred with C/C++ MSVC 2022 (last update) and SDL version 3.1.2 (github master)

### Details:

The `SDL_SetTextInputArea()` function that should be in `SDL_keyboard.h` (according https://wiki.libsdl.org/SDL3/SDL_SetTextInputArea) seems no longer to be there.

 `error C3861: 'SDL_SetTextInputArea': identifier not found`

Occurs in `ImGui_ImplSDL3_PlatformSetImeData()` function, line 143: `SDL_SetTextInputArea(window, &r, 0);`
file: imgui_impl_sdl3.cpp

All other SDL functions compile. 

I think this is an SDL ABI break (wanted, not by error).
The closest I could find to a replacement is `SDL_SetTextInputRect(window, &r);` (see https://wiki.libsdl.org/SDL3/SDL_SetTextInputRect) 

### Minimal, Complete and Verifiable Example code:

Easily reproducible because the error is consistently there at the same line.
For confirmation, just remark the above mentioned line and everything builds fine.

**Comment by ocornut** [comment]
Hello,
This is already fixed in latest:
https://github.com/ocornut/imgui/commit/ccf3ee674a063a85653056a80fafc9e398c7dd68

**Comment by NostraMagister** [comment]
Changelog says: 2024-07-01: Update for SDL3 api changes: SDL_SetTextInputRect() changed to SDL_SetTextInputArea().

IMO, it should be the reverse: SDL_SetTextInputArea changed to SDL_SetTextInputRect()

I checked the code again (JULY 11) and it still uses SDL_SetTextInputArea() in the current master and docking branch of 1.90.9.

If its me that do not understand it, just leave it because as I said in OP i changed it myself to SDL_SetTextInputRect() in the SDL3 backend and it all works.

grtz

**Comment by ocornut** [comment]
The function in SDL3 latest is called `SDL_SetTextInputArea()` and the code in imgui latest calls `SDL_SetTextInputArea()`.

https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_sdl3.cpp

There is no `SDL_SetTextInputRect()` currently in SDL3.
SDL3 is a fast moving and instable target, if you use it you must use latest.
