### ISSUE TITLE
How to never steal keyboard/window focus but process mouse and keyboard keys ?

### ISSUE THREAD

**Issue by AnasNaz** [ocornut/imgui#7778]
### Version/Branch of Dear ImGui:

Version 1.91, Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl2.cpp

### Compiler, OS:

Windows 11 + MVSC

### Details:

Hello,

I am trying to recreate the window behavior of the default Windows clipboard manager on windows 10/11, triggered by the Win + V hotkey. I have attached a GIF demonstrating that the clipboard manager never steals keyboard focus. Specifically, the keyboard input/caret continues blinking in another application even when the clipboard manager is opened via the Win + V hotkey. The keyboard focus remains in the previous application, but the clipboard manager window remains responsive to clicks and keyboard inputs, including text fields, keyboard navigation with arrow keys, and tab/shift+tab for moving between interactable UI widgets. When the user clicks on a clipboard item, it pastes immediately into the previous application.

I have searched through many issues related to window focus, but they mostly pertain to windows within the same ImGui application (e.g., popups for autocomplete not stealing focus from the input text, or invisible button for hit tests, etc.). My goal is to achieve this behavior on Windows only and not steal window focus from other applications.

I have looked through the Win32 documentation and found commands to show the window without stealing focus, such as using:

ShowWindow(glfwGetWin32Window(glfwWindowHndl), SW_SHOWNOACTIVATE);

or modifying window attributes with SetWindowLong and SetLayeredWindowAttributes to bring the window to the top-most Z axis without stealing focus. These methods successfully show the window without stealing keyboard focus, but as soon as I click anything in the window, my ImGui application steals focus.

I understand that Windows can only have one focused window at a time, and it routes mouse and key press events to the current active window. Therefore, I tried using the Win32 function AttachThreadInput to attach my thread to the last focused window and share the keyboard state:

[AttachThreadInput documentation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-attachthreadinput).

Before delving into methods like attaching threads and listening to low-level message events with SetWindowsHookEx, am I missing some concept to make this work with ImGui? How does Microsoft's clipboard manager avoid stealing focus and how does Imgui set focus through its IO detection? Can I still allow inputs to take effect in my Imgui application but not steal focus ?

I would appreciate any help or advice to look in the right direction. 

### Screenshots/Video:

![Windows_11_Clipboard_Does_Not_Steal_Focus](https://github.com/ocornut/imgui/assets/24490527/ec5bff6e-199c-47d2-908e-b67fa9d6b5d8)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Hello;
I am not sure anything about your problem has to do with dear imgui itself, therefore I don't think this is the right place to ask. I am wrong?

It may also generally be worth clarifying/explaining what you are actually trying to achieve in concrete terms, because it is possible that you may digging your way into a [XY Problem](https://xyproblem.info/).

**Comment by AnasNaz** [comment]
Hello, thank you for your reply. Please feel free to close or delete this issue if it is not dear imgui related at all. 

My objective: Interact (mouse clicks, key presses) with the imgui application without stealing the keyboard focus from the last active application but have my imgui widgets react to clicks or key presses.

Context: I am developing a "Passwords Clipboard Manager," where the user can at any time (even when typing in an input text box) press a certain hotkey, and my imgui window will appear near the user's cursor. Upon clicking on the clipboard item, the text should be pasted directly in the last keyboard focus. 

Problem: Any input to imgui will automatically steal keyboard focus. I was unable so far to find any mechanism or flag to prevent taking focus, which is why i started looking at Win32 API. When the focus is stolen, the blinking cursor is gone from the last application, and I can no longer paste contents directly into the previous application. 

The GIF I have attached shows that the Windows clipboard manager can interact with mouse clicks and key presses, but the blinking cursor indicating keyboard focus is never stolen. Even when you close the clipboard manager, the cursor just continues blinking in the last active input text field.

**Comment by ocornut** [comment]
Thanks for detailing. Unfortunately as stated this has nothing to do with dear imgui per se. We are drowned in support requests so those in particular needs to be ignored for our sanity.
If you reformulate and search for your issue in Win32 terms you are more likely to find a answer for it.
I did a quick search "win32 don't take focus on click" and stumbled on `WM_MOUSEACTIVATE` which may be it but I am not sure. https://learn.microsoft.com/en-us/windows/win32/inputdev/wm-mouseactivate
Feel free to confirm/post details so this is more likely to be found by future users.

**Comment by brokensword2018** [comment]
> Hello, thank you for your reply. Please feel free to close or delete this issue if it is not dear imgui related at all.
> 
> My objective: Interact (mouse clicks, key presses) with the imgui application without stealing the keyboard focus from the last active application but have my imgui widgets react to clicks or key presses.
> 
> Context: I am developing a "Passwords Clipboard Manager," where the user can at any time (even when typing in an input text box) press a certain hotkey, and my imgui window will appear near the user's cursor. Upon clicking on the clipboard item, the text should be pasted directly in the last keyboard focus.
> 
> Problem: Any input to imgui will automatically steal keyboard focus. I was unable so far to find any mechanism or flag to prevent taking focus, which is why i started looking at Win32 API. When the focus is stolen, the blinking cursor is gone from the last application, and I can no longer paste contents directly into the previous application.
> 
> The GIF I have attached shows that the Windows clipboard manager can interact with mouse clicks and key presses, but the blinking cursor indicating keyboard focus is never stolen. Even when you close the clipboard manager, the cursor just continues blinking in the last active input text field.

hello. I have the same problem。 do you have any idea. we can have a discuss.
