### ISSUE TITLE
Scroll (SetScrollHereY) precision issue with messy font size float (and solution)

### ISSUE THREAD

**Issue by ividyon** [ocornut/imgui#7782]
### Version/Branch of Dear ImGui:

ImGuiNET wrapper

### Back-ends:

Vulkan

### Compiler, OS:

Windows 11

### Details:

For a while our ImGuiNET C# project had an issue with `SetScrollHereY()`, where raising the program's scale up and down via some code of ours would cause list scrolling to break down. `SetScrollHereY()` would need 3-4 attempts to properly focus a given element in a given list.

I just found the issue: Our scale factor was a big messy float with many decimal points. We provided this to `size_pixels` in `AddFontFromMemoryTTF`. And this appears to have been the culprit. Rounding the value to a flat number has resolved the issue.

Since we're using some NET wrapper of some indeterminable version, I'm just leaving this information here for your perusal, and for future visitors from Google who may encounter the same issue. I can't judge whether it's a bug with ImGui itself, but `SetScrollHereY` is an ImGui function whose behavior wasn't customizable, and it displayed this error, which was resolved as described above. Apologies if this was already addressed or otherwise isn't present in the main library.

### Minimal, Complete and Verifiable Example code:

```csharp
ImFontAtlasPtr fonts = ImGui.GetIO().Fonts;
fonts.AddFontFromMemoryTTF(fontEnNative, fontIcon.Length, (float)Math.Round(14.0f * scale), cfg,
                fonts.GetGlyphRangesDefault());
```

**Comment by ocornut** [comment]
Hello, 

You didn't specify which version you are using, but from 1.90 (released 15 nov 2023) we round this value:

> Argument 'float size_pixels' passed to AddFontXXX() functions is now rounded to lowest integer. This is because our layout/font system currently doesn't fully support non-integer sizes. Until it does, this has been a common pitfall leading to more or less subtle issues. (#3164, #3309, #6800)

You also didn't really describe your precise issue, without a repro or some minimal code it is ambiguous. I however believe that the most common issue related to non round font size would have been related to when using ImGuiListClipper.

Thanks for sharing!

**Comment by ividyon** [comment]
It appears to be the exact same issue you already handled, yeah. Unfortunately the NET wrapper is quite a bit behind. I just couldn't find solutions on Google, so I thought I'd add one more issue to make this more searchable although it's not useful for the maintainer. Thanks again!

**Comment by ocornut** [comment]
FYI the NET wrapper seems up to date:
https://github.com/ImGuiNET/ImGui.NET
