### ISSUE TITLE
Window goes blank on AMD GPU (driver issue)

### ISSUE THREAD

**Issue by jbfloyd** [ocornut/imgui#7787]
### Version/Branch of Dear ImGui:

Version 1.91.0, Branch: master

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_sdl3.cpp

### Compiler, OS:

Windows 11 + MSVC 2022

### Full config/build information:

```
Dear ImGui 1.91.0 WIP (19093)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1940
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

When I resize the container window on my PC (AMD Radeon RX 6750 XT GPU), the contents go black. See video of ImGui demo example.

### Screenshots/Video:

https://github.com/user-attachments/assets/279532ab-8d68-4878-ba17-b92031ebf552

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by LuckyIntel** [comment]
https://github.com/ocornut/imgui/blob/master/examples/example_glfw_opengl3/main.cpp

Is this the example are you using by any chance?

**Comment by jbfloyd** [comment]
Yes. I tried that example and example_sdl2_opengl3. The examples work as-is on other computers I use with NVIDIA GPU or integrated graphics without the window going black on a resize, so I jumped to it having something to do with an AMD gpu.

I'll try your suggestion when I have time and will let you know the result.

**Comment by LuckyIntel** [comment]
I am not any good with SDL2 but GLFW example for sure lacks of the size callback i've mentioned.I, myself also have an AMD GPU and i always use size callbacks.I believe this is the problem here.Have a nice day!

**Comment by ocornut** [comment]
@jbfloyd can you clarify your last message, do you have the same problem on your machine with example_sdl2_opengl3 AND example_sdl3_opengl3 and example_glfw_opengl3 ?

**Comment by jbfloyd** [comment]
Sorry. Yes, I made a mistake in the original report. I originally tested example_sdl3_opengl3. I went back and tested more examples and had the following results on my PC.

Works OK:
example_glfw_vulkan
example_sdl2_directx11
example_sdl2_sdlrenderer2
example_sdl2_vulkan
example_win32_directx9
example_win32_directx10
example_win32_directx11
example_win32_directx12
example_win32_opengl3

Container window goes black after resize:
example_glfw_opengl2
example_glfw_opengl3
example_sdl2_opengl2
example_sdl2_opengl3

So the problem seems associated with just the OpenGL implementation. I tried the suggestion of @LuckyIntel, but the window contents still goes black after being resized in the glfw_opengl examples.

Sorry for the confusion/mixup on which implementation has the issue.

**Comment by ocornut** [comment]
Maybe so some sanity debug-stepping to check various values, io.DisplaySize, contents of ImDrawData etc.
Consider using [RenderDoc](https://renderdoc.org/) to see if you can debug your rendering.

**Comment by LuckyIntel** [comment]
I think this can be also related to your AMD gpu driver version.What drivers are you running on?Have you tried another gpu drivers?

**Comment by jbfloyd** [comment]
You can close it. It seems to have been an issue with the AMD driver I was using. I built the OpenGL examples in Linux and they worked fine. I updated to the latest Windows driver (only available in the last few days) and the OpenGL examples work fine now in Windows too. Now that I know, if it happens again, I'll bother AMD about it. Thanks for the feedback.
