### ISSUE TITLE
Sub sub-menu fail to display using ImGuiConfigFlags_ViewportsEnable

### ISSUE THREAD

**Issue by niclar** [ocornut/imgui#7789]
### Version/Branch of Dear ImGui:

Version 1.90.7, Branch: docking

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_sdl2.cpp

### Compiler, OS:

WIndows 11 + MSVC 2022 Version 17.10.4

### Details:

Using the docking branch with ImGuiConfigFlags_ViewportsEnable set it seems sub sub-menues don't show.

"Menu3" in the attached snippet

(not setting ImGuiConfigFlags_ViewportsEnable sub sub-menus work as expected) 

### Minimal, Complete and Verifiable Example code:

```cpp

 ImGuiIO& io = ImGui::GetIO(); (void)io;
 io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;


ImGui::Begin("Example Bug");
 if (ImGui::BeginMenu("Menue"))
   {
      if (ImGui::BeginMenu("Menu2"))
      {
         if (ImGui::BeginMenu("Menu3"))   //  <-- this is not displayed
         {
              ImGui::EndMenu();
         }
         ImGui::EndMenu();
     }
     ImGui::End();
}

```

**Comment by ocornut** [comment]
What’s the size of your main viewport?
Can you try updating to latest?

**Comment by GamingMinds-DanielC** [comment]
In your example code, you have mismatched `BeginMenu()` (3x) and `EndMenu()` (only 2x) calls. First please enable debug messages so that you get assertions if something is wrong. Maybe fixing those mistakes already solves the issue.

**Comment by niclar** [comment]
it works using v1.90.9-docking /thx
