### ISSUE TITLE
Style color for active input field (feature request)

### ISSUE THREAD

**Issue by pixtur** [ocornut/imgui#7791]
### Version/Branch of Dear ImGui:

Version 1.87.3 Branch: master

### Back-ends:

imgui.net

### Compiler, OS:

Windows 10

### Details:

**My Issue/Question:**

I'm trying to get a better understanding of how to use ImGui's colors. In particular, I was looking for a color to define the background color of focused input fields. I initially assumed this to be ImGuiCol_FrameBgActive (given that FrameBg defines the background color for input fields). But the only place I found where this is used is for CheckBoxes and RadioButtons while being pressed.

I believe that having the option to override the color of focused input fields would be useful because [checking its active state is not possible in my case](https://github.com/ocornut/imgui/issues/3147).

Maybe FrameBgActive could just be used for that considering that its name is already implying that purpose?

**Comment by ocornut** [comment]
Hello,

I believe this is the same issue as #3411. I don’t have a good solution for it yet :( Making in particular large/multiline input text use FrameBgHovered/Active consistently seems unusually noisy.

> fields would be useful because because checking its active state is not possible in my case.

I am not sure why it is not possible. If your issue is still that you can’t manually add wrapping for 1-2 functions from imgui_internal.h (here you’d only need GetActiveID()), when needed, I believe you should investigate ways to solve this issue.

**Comment by pixtur** [comment]
> I don’t have a good solution for it yet :( Making in particular large/multiline input text use FrameBgHovered/Active consistently seems unusually noisy.

I can totally see that for hover. But I personally like the focused field to stand out. It's just a matter of taste.

> I am not sure why it is not possible. If your issue is still that you can’t manually add wrapping for 1-2 functions from imgui_internal.h (here you’d only need GetActiveID()), when needed, I believe you should investigate ways to solve this issue.

Yes, I'm still shying away from internals. Although I believe that there was some progress on that front with ImGui.Net.

After spending the weekend on cleaning up my user visual design and interface code, I believe I can live without the focused input-field being highlighted.
