### ISSUE TITLE
identifier "ImGui_ImplWin32_WndProcHandler" is undefined

### ISSUE THREAD

**Issue by coolgameinside** [ocornut/imgui#7799]
### Version/Branch of Dear ImGui:

last version

### Back-ends:

imgui_impl_win32

### Compiler, OS:

Win11+ MSVC 2022

### Details:

For the first time I decided to make a simple menu (dll) for the game, but an error haunts me, I don’t understand where to look and what can be done.

```
Error (active)	E0020	identifier "ImGui_ImplWin32_WndProcHandler" is undefined	
Error C3861	'ImGui_ImplWin32_WndProcHandler': identifier not found
```

### Minimal, Complete and Verifiable Example code:

This is what the beginning of the code looks like

#include <windows.h>
#include <d3d11.h>
#include <tchar.h>
#pragma comment(lib, "d3d11.lib")

#include "imgui.h"
#include "imgui_impl_dx11.h"
#include "imgui_impl_win32.h"

**Comment by ocornut** [comment]
>  but an error haunts me

If you search for `ImGui_ImplWin32_WndProcHandler` in the codebase, 

(1) The first hit says:

```
// Copy this line into your .cpp file to forward declare the function.
extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);
```

(2) All five examples demonstrating how to use imgui_impl_win32 are doing exactly that:

```cpp
// Forward declare message handler from imgui_impl_win32.cpp
extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);

[...]
LRESULT WINAPI WndProc(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    if (ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam))
        return true;
```

So here's your answer..
