### ISSUE TITLE
Access violation in ImTextStrToUtf8

### ISSUE THREAD

**Issue by xGhostShipIV** [ocornut/imgui#780]
I'm trying to make a renaming system wherein items are listed originally as TreeNodes, but if a node is already selected and then clicked again the node is replaced with a InputText where a new name for the node can be typed in. This can also be done through a right click menu. If done through the right click menu everything works fine, however if it's done by clicking a selected node I get an access violation in ImTextStrToUtf8 which appears to be the result of a null edit_state in the ImGuiContext. I can't see why it works in one situation but not in another.

```    
    if (m_renamingObjectName == node->Name.Get())
        {
            ImGui::PushID((void *)node.get());

            char buffer[64] = {};
            memcpy(buffer, m_renamingObjectName.c_str(), 64);
            if (ImGui::InputText("", buffer, 64, ImGuiInputTextFlags_EnterReturnsTrue))
            {
                // Do stuff
            }
            ImGui::PopID();
        }
        else
        {
            open = ImGui::TreeNodeEx(node.get(), flags, node->Name.Get().c_str());
            if (ImGui::IsItemClicked(kMouseLeft))
            {
                std::vector<Node::Id> selected = GetSelectedNodes();
                if (std::find(selected.begin(), selected.end(), node->Id.Get()) != selected.end())
                {
                    // trying to rename this way does not work
                    m_renamingObjectName = node->Name.Get();
                }
            }
        }

        ImGui::PushID((void *)node.get());
        if (ImGui::BeginPopupContextItem("Game Object Menu"))
        {
            if (ImGui::Selectable("Rename"))
            {
                // Trying to rename this way works
                m_renamingObjectName = node->Name.Get();
            }
            ImGui::EndPopup();
        }
        ImGui::PopID();
```

**Comment by ocornut** [comment]
I don't know about all the context but:
```
char buffer[64] = {};
memcpy(buffer, m_renamingObjectName.c_str(), 64);
```

If `m_renamingObjectName` is shorter it may crash, if it's longer buffer won't be zero terminated which also likely to crash.

**Comment by xGhostShipIV** [comment]
I figured it out, I was giving the tree node and the input text the same ID which caused the InputText to freak out thinking it was immediately the activeID

**Comment by ocornut** [comment]
Interesting, I should still aim to avoid the crash all-together. Even if id conflicts shouldn't happens in theory it is problematic that the code can crash in such mysterious manner. I'm adding it to my todo list.
