### ISSUE TITLE
Proper way to align Text to the Right of a Selectable on the SameLine (width problems)

### ISSUE THREAD

**Issue by A-Debord** [ocornut/imgui#7805]
### Version/Branch of Dear ImGui:

Version v1.90.9

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

clang 16, ubuntu 20.04

### Details:

Hi, i've just started working with imgui
great times so far, but I can't figure out how to do this properly :

i have a `Selectable`, and i'm trying to align right some `Text` that is on the `SameLine`.

like so:
![image](https://github.com/user-attachments/assets/fb80f872-0060-4c26-b731-a9c400cccbc8)

I suppose that I need to set the offset of `SameLine` to the correct value.
However the `Selectable` sets the cursor all the way to the next line and `GetItemRectSize` doesn't help much more.
from what i understand, i need to extract the rect given to `ItemSize` by `Selectable`. 
not the one given to `ItemAdd`.
but I havent found a canonical way to do so.

I could re compute the `Selectable` text size, but it seems expensive.
I've also found a hack to extract this size using another `SameLine` call, but it seems quite brittle.

So i think if i missed something in the docs, any help would be appreciated.

thanks !

### Minimal, Complete and Verifiable Example code:

```c++
ImGui::Selectable(left_str, is_selected)

float orig = ImGui::GetCursorPosX();
ImGui::SameLine(); // sets the cursor to the end of the first text
float selectable_width = ImGui::GetCursorPosX() - orig; // extract the width of the selectable text

ImVec2 dims = ImGui::CalcTextSize(right_str, right_str+right_str_size);
ImVec2 avail = ImGui::GetContentRegionAvail();
float offset = avail.x - dims.x;

// prevent overlap
if(offset > 0) {
    offset += selectable_width + ImGui::GetStyle().ItemSpacing.x;
}

ImGui::SameLine(std::max(0.f, offset));

ImGui::TextDisabled("%s", right_str);
```

**Comment by ocornut** [comment]
There's no canonical way but here's how I would do it:

```cpp
bool SelectableWithHint(const char* label, const char* hint)
{
    using namespace ImGui;
    bool ret = Selectable(label);
    SameLine();
    SetCursorPosX(GetCursorPosX() + ImMax(0.0f, GetContentRegionAvail().x - CalcTextSize(hint).x));
    TextDisabled("%s", hint);
    return ret;
}
```

Usage
```cpp
SelectableWithHint("/loader/loader", "MeshObjLoader");
```
It seems to do the job well.

I think your issue stem from using `SameLine()` for offseting instead of `SetCursorPosX()`

**Comment by A-Debord** [comment]
I see, it seems better indeed. 
I will use that, thanks for the help !
