### ISSUE TITLE
Unable to set the style correctly (right angle edge&rounded edge)

### ISSUE THREAD

**Issue by Moerre** [ocornut/imgui#7813]
### Version/Branch of Dear ImGui:

v1.90.9-docking

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

win10+msvc2020

### Full config/build information:

https://github.com/user-attachments/assets/dc468d38-1e01-40c1-af13-1796e7e52cc0

### Details:

After enabling the function of leaving the parent window, it is not possible to set the child window style to rounded edges. When the child window leaves the parent window, it will automatically become a right angled edge

**Comment by GamingMinds-DanielC** [comment]
The additional viewport that is opened for your window doesn't have support for rounded corners. You don't even have to leave the main viewport, rounded window corners don't work well with docking in general. That's not a bug that can be easily fixed, it is more of a conceptual limitation. So if you want a consistent look and docking/viewport support, I would suggest to not use window rounding at all.

**Comment by ocornut** [comment]
Not easily, no. You would have to configure per-pixel alpha compositing/transparency which is currently not demonstrated nor possible in a portable manner.

This is the same issue as #6599 #5852 #4180 

About transparency you may investigate #5988 #7788 #7462 #7045 #7181 #6558 #5282 #2766 #2764 but given the form of your question it's unlikely to be simple.
