### ISSUE TITLE
Problem with changing the password sign.

### ISSUE THREAD

**Issue by Flinez** [ocornut/imgui#7816]
### Version/Branch of Dear ImGui:

Version 1.90.9, Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

**My Question:**

I need help with changing the password character as my changed character is being output as '?' in the app but my font and program supports these characters.

![image](https://github.com/user-attachments/assets/8feaa117-6783-443e-bde3-30dccf9994ef)

I have tried changing the imgui code e.g. ImFontAtlas::AddFontDefault to load my font as default, ImFontAtlas::GetGlyphRangesDefault() to extend ranges. But nothing works. Below in the picture is the code that is responsible for this character. Setting it to anything else e.g. '#' or '*' works fine, but not the more complicated characters. Using '\u2022' or '•' doesn't matter, as the '?' appears anyway.

![Zrzut ekranu 2024-07-24 164310](https://github.com/user-attachments/assets/d86aa795-a16e-4bc0-8242-d9e260081bcf)

**Comment by ocornut** [comment]
Try `FindGlyph(0x2022);`
Other forms would depends on your compiler and compiler settings and I am not even sure if the `'x'` form is supported for non-ASCII character.

Use Tools->Metrics->Fonts to make sure the right glyphs are loaded.

**Comment by Flinez** [comment]
0x2022 is working, thank you for your quick help
