### ISSUE TITLE
Imgui not work on emulator

### ISSUE THREAD

**Issue by muathudaudon** [ocornut/imgui#7817]
### Version/Branch of Dear ImGui:

#define IMGUI_VERSION               "1.89 WIP" #define IMGUI_VERSION_NUM           18832

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Window

### Details:

Im using #define IMGUI_VERSION               "1.89 WIP"
#define IMGUI_VERSION_NUM           18832

After build , my imgui only work android device but not work on any emulator, idk why, anyone know the issue , please help. Thanks..

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Not helping without useful information provided, sorry.
