### ISSUE TITLE
Reusable code that creates a new window

### ISSUE THREAD

**Issue by justinblaber** [ocornut/imgui#7819]
### Version/Branch of Dear ImGui:

Version 1.00

### Back-ends:

imgui_impl_vulkan.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

linux g++

### Details:

Very basic question (and probably asked a million times) but I can't seem to find a lot of info on it. If there's an existing answer feel free to link and close this. 

I'm wondering what the general approach should be if we want a function/class that creates a window (and if we want to use it multiple times). A good example would be the `ImGui::ShowDemoWindow()` function. If we want to be able to generate two demo windows, if we call `ImGui::ShowDemoWindow()` twice it doesn't work because the names are the same. In addition, if we have some code elsewhere that accidentally creates a window with `ImGui::Begin("Dear ImGui Demo")` then it won't work either.

The only solution I can think of is to wrap things into a class that generates a UUID and prepends it to the name string. Before I go down that route I was wondering if I'm kind of heading in a bad direction (i.e. is this a mis-use of imgui in some way) or if there's a better solution.

### Minimal, Complete and Verifiable Example code:

```cpp
        ImGui::ShowDemoWindow();
        ImGui::ShowDemoWindow();
```
or 
```cpp
        ImGui::ShowDemoWindow(&one);
        ImGui::Begin("Dear ImGui Demo");
        ImGui::End();
```

**Comment by ocornut** [comment]
If you have a function to display varying data which is aimed to be output into multiple windows you may decide to let the user specify the window name, or generate a window name with the ## suffix.

But the way you are describing things seems a little obtuse so i am not entirely sure what your actual problem you need to solve is.

**Comment by justinblaber** [comment]
Sorry, let me give a concrete example.  Below is kind of what I feel inclined to do if I want to have some sort of code resuse for duplicate windows I want to create. For instance:

Class:

```
class ExampleWindow {
public:
    ExampleWindow(const std::string& prefix_in, ImVec2 p_window_in, ImVec2 sz_window_in, float val_in) :
        prefix(prefix_in), p_window(p_window_in), sz_window(sz_window_in), val(val_in) {
    }

    void draw() {
        ImGui::SetNextWindowPos(p_window);
        ImGui::SetNextWindowSize(sz_window);
        ImGui::Begin((prefix + "Window").c_str());
        ImGui::Button("Button");
        ImGui::SliderFloat("float", &val, 0.0f, 1.0f);
        ImGui::End();
    }

    std::string prefix;
    ImVec2 p_window;
    ImVec2 sz_window;
    float val;
};
```

Before the render loop:
```
ExampleWindow window0("0", ImVec2(0, 0), ImVec2(100, 100), 0.5f);
ExampleWindow window1("1", ImVec2(150, 0), ImVec2(100, 100), 0.5f);
ExampleWindow window2("2", ImVec2(150, 150), ImVec2(100, 100), 0.5f);
ExampleWindow window3("3", ImVec2(0, 150), ImVec2(100, 100), 0.5f);
```

In the render loop:

```
    window0.draw();
    std::cout << "window0.val: " << window0.val << std::endl;
    window1.draw();
    std::cout << "window1.val: " << window1.val << std::endl;
    window2.draw();
    std::cout << "window2.val: " << window2.val << std::endl;
    window3.draw();
    std::cout << "window3.val: " << window3.val << std::endl;
```

Results in something I want:
![Screenshot from 2024-07-25 13-55-16](https://github.com/user-attachments/assets/74c83b44-e429-4a73-8b81-9c35fe14835a)

But the problem is I have to provide the name prefix, and even then you could create a window with the name `"0Window"` by mistake elsewhere in your code. So I was thinking if you generate a UUID in the class and use that as a prefix it would solve the issue of not needing to provide a prefix and preventing name collisions. But in general since I'm a new imgui user I was wandering if this is the wrong overall approach.

**Comment by JustaSimpleUser** [comment]
How about a static class member variable that is incremented in the constructor for each window created, and used to alter the window tag?

**Comment by ocornut** [comment]
I think you are overthinking this a bit. If you end up having four windows they will likely be tied to something: eg a subsystem, or a specific entity, and then you can include their ID or name in the window name. But that decision can only happens when you have a concrete case.

Your class also may be a sign of preemptive over-engineering that removes value instead of adding value. With that code now you cannot resize or move windows, they are not meaningfully saved anymore etc. Consider using dear imgui in its simple form first.

Whether you’ll want to use unique tags (entity id) or recycled tags (small counter as suggested in @JustaSimpleUser) depends on variety of other parameters, eg if you want windows for a given entity to have their using persistent location.

Refer to FAQ about using ## and ### if you need to use an identifier that isn’t entirely in the visible part of the name.

**Comment by justinblaber** [comment]
Ok this is exactly what I needed. Wanted to get some general feedback before I went too far down the wrong path. Gotta play around with dearimgui a little more and get a better feel for it. Thanks.
