### ISSUE TITLE
SliderFloat3 moves all values

### ISSUE THREAD

**Issue by Syphonx** [ocornut/imgui#782]
Hi, the below code seems to only track updates on the 1st SliderFloat3, yet updates all variables in the array with the same value? It works when referencing only the x/y/z values when using SliderFloat1 however

I made sure the SliderFloat3's label was different for each one (as referenced [here](https://github.com/ocornut/imgui/issues/381)) any ideas?

	//... declared earlier
	std::vector<glm::vec3> pointLightColors = {
		glm::vec3(0.4f, 0.7f, 0.1f),
		glm::vec3(0.4f, 0.7f, 0.1f),
		glm::vec3(0.4f, 0.7f, 0.1f),
		glm::vec3(0.4f, 0.7f, 0.1f)
	};

	//... in app update loop 
	ui.Update(pointLightColors);

	//... in ui update loop
	void UI::Update(std::vector<glm::vec3> &lightcolors) {

		for (size_t i = 0; i < lightcolors.size(); i++)
		{
			bool show_window = true;
			ImGui::SetNextWindowSize(ImVec2(400, 200), ImGuiSetCond_FirstUseEver);
			std::string windowname = "Scene lights";// +std::to_string(i);
			ImGui::Begin(windowname.c_str(), &show_window);
			std::string slidername = "Light_" + std::to_string(i);
			ImGui::SliderFloat3(slidername.c_str(), glm::value_ptr(lightcolors.at(i)), 0.1f, 1.0f);
			// ImGui::SliderFloat("x", &lightcolors[i].x, 0.0f, 1.0f);
			ImGui::End();
		}
	}

**Comment by ocornut** [comment]
What was the problem in the end?

**Comment by Syphonx** [comment]
Oversight on my part, It seems everything i wrote worked fine, some rogue code elsewhere was altering the array.
