### ISSUE TITLE
Cause of colour banding in convex poly fill ( 

### ISSUE THREAD

**Issue by inflex** [ocornut/imgui#7833]
### Version/Branch of Dear ImGui:

Version 1.90.9

### Back-ends:

imgui_impl_SDL2

### Compiler, OS:

linux + gcc

### Details:

Hello,

   I have seen this sort of bicolour-filling in the past on some boards I view and I'm trying to understand what could be causing it ?  I'm assuming it has something to do with the alpha of the fill colour and maybe an overlap occuring as  the blue fill is fully opaque but the other colour has a partial-alpha (0x88) #A26E5788
   
   To clarify, not actually asking to debug my code, just wondering what sort of things can create this kind of patterning on a PathFillConvex() call?   Note also, the bicolour transitions aren't happening on each segment/point.
   
   
   How the path is generated for each pad; 
```

						draw->PathClear();
						for (auto op: outline) {
							draw->PathLineTo(op);
						}
						draw->PathFillConvex(color);

```

This is a typical, set of points of one of the rounded-corner pads

```
4087.209, 605.614
4086.200, 605.526
4085.223, 605.264
4084.305, 604.836
4083.476, 604.256
4082.760, 603.540
4082.180, 602.711
4081.752, 601.793
4081.490, 600.815
4081.402, 599.807
4081.402, 588.193
4081.490, 587.185
4081.752, 586.207
4082.180, 585.289
4082.760, 584.460
4083.476, 583.744
4084.305, 583.164
4085.223, 582.736
4086.200, 582.474
4087.209, 582.386
4100.791, 582.386
4087.209, 582.386
4100.791, 582.386
4101.800, 582.474
4102.777, 582.736
4103.695, 583.164
4104.524, 583.744
4105.240, 584.460
4105.820, 585.289
4106.248, 586.207
4106.510, 587.185
4106.598, 588.193
4106.598, 599.807
4106.598, 588.193
4106.598, 599.807
4106.510, 600.815
4106.248, 601.793
4105.820, 602.711
4105.240, 603.540
4104.524, 604.256
4103.695, 604.836
4102.777, 605.264
4101.800, 605.526
4100.791, 605.614
4087.209, 605.614
4100.791, 605.614
```

### Screenshots/Video:

![Screenshot at 2024-07-29 21-38-32](https://github.com/user-attachments/assets/408ff870-aabe-4c05-9fd2-8ab33d763097)
![Screenshot at 2024-07-29 21-46-36](https://github.com/user-attachments/assets/144cc38f-b9de-4329-9d10-3c949ce7d659)
![Screenshot at 2024-07-29 21-45-52](https://github.com/user-attachments/assets/4c8a0de0-ca81-4bea-a90f-9a421a5af84d)

**Comment by inflex** [comment]
Thank you RubberyDucky effect...

I was going through the points more carefully and I noticed this....

```
...
4087.209, 582.386
4100.791, 582.386
4087.209, 582.386
...
...
4106.598, 599.807
4106.598, 588.193
4106.598, 599.807
...
...
4100.791, 605.614
4087.209, 605.614
4100.791, 605.614
```

So the point outline was wrapping back on itself, hence the variation in alpha.

**Comment by ocornut** [comment]
Note that the Metrics->Windows section has a way to visualize each individual triangle and the triangle mesh so it might occasionally be a helpful thing to debug custom drawing.

**Comment by inflex** [comment]
Thank you @ocornut - I was not aware of that.  Very good to know.
