### ISSUE TITLE
Select default tab not working

### ISSUE THREAD

**Issue by rrizik** [ocornut/imgui#7835]
### Version/Branch of Dear ImGui:

v1.90.9

### Back-ends:

imgui_impl_dx11.cpp

### Compiler, OS:

Windows 10

### Details:

I'm writing a program where I can serialize/deserialize data.
One piece of data that I'm saving/loading is which tab was last selected, so that when I load the program, it selects the tab I was last on.

I'm using the flag ImGuiTabItemFlags_SetSelected which almost works but is doing something weird.

More Context:
I'm writing a budgeting program where I have tabs from Jan - Dec to select from. By selecting a Tab, it simply sets the appropriate index for me to use for other parts of the code. I have an array[12] of flags for each Tab so it has its own flag to use so that I can set different tabs with flags of either ImGuiTabItemFlags_SetSelected or ImGuiTabItemFlags_None. 

If I default my tab to lets say May, that works. And then if I click on April (one tab left), that works as well in setting the previous tabs flag (May) to None and the new tab (April) to Selected. But if I try and go to any tab to the right, it switches for a frame and then switches back. (So I can only move tabs left essentially, due to order of operations)

When I step through the program, it looks like even though I'm passing in ImGuiTabItemFlags_None into the tab that I'm switching away from (so in this case switching away from April and moving to May), it still evaluates to true, overwriting my selection.

I'm not clear on why or how this tab is evaluating to True even though I'm passing it ImGuiTabItemFlags_None.

I can provide any and all information.
I was having trouble getting a video less than 10mb's on file size which is a the limit. But if it becomes imperative that I provide more, I can try again.

### Minimal, Complete and Verifiable Example code:

```cpp
// Even though pm->tf[3] is 0, it still evaluates this tab as True even though I didn't click on it
            if(ImGui::BeginTabItem("April", 0, pm->tf[3])){
                pm->tf[pm->month_idx] = 0;
                pm->month_idx = Month_Apr;
                pm->tf[pm->month_idx] = ImGuiTabItemFlags_SetSelected;
                ImGui::EndTabItem();
            }
// This is the tab I'm clicking on, attempting to move from April to May
            if(ImGui::BeginTabItem("May", 0, pm->tf[4])){
                pm->tf[pm->month_idx] = 0;
                pm->month_idx = Month_May;
                pm->tf[pm->month_idx] = ImGuiTabItemFlags_SetSelected;
                ImGui::EndTabItem();
            }
```

**Comment by ocornut** [comment]
> When I step through the program, it looks like even though I'm passing in ImGuiTabItemFlags_None into the tab that I'm switching away from (so in this case switching away from April and moving to May), it still evaluates to true, overwriting my selection.

`ImGuiTabItemFlags_SetSelected` cannot behave on the same frame, see #6681 

If i may suggest, your code also seems a little error-prone. You could probably simplify it by storing a single `int selected_tab_idx;` field.

(We should eventually support auto-saving of selected tab in standalone tab-bar.)

**Comment by ocornut** [comment]
Apart from the solution of using `TabBarQueueFocus()` from imgui_internal.h right after `BeginTabBar()`, your other solution is to only set the `ImGuiTabItemFlags_SetSelected` flag once on load, there's no necessity to set it every frame, in fact that is what is causing your issue.

**Comment by rrizik** [comment]
Ahhh ok, your second suggestion solved it for me perfectly. Thanks!

"If i may suggest, your code also seems a little error-pron" - yeah I wasn't happy with the code, I was just struggling to anything working haha. All of that code went away and I'm just storing an index.

Thanks for the help

**Comment by ocornut** [comment]
Good to hear. Closing now. I will post here again if we end up adding .ini support for standalone tab-bars.
