### ISSUE TITLE
AddShadowRect not rouned

### ISSUE THREAD

**Issue by Alignzwry** [ocornut/imgui#7836]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_win32.cpp

### Compiler, OS:

MSVC 2022, Windows 11

### Details:

I use AddShadowRect to draw a rounded rectangle shadow, but it doesn't have rounded corners. Will there be a fix to this issue? Or do I need to find a way myself?

### Screenshots/Video:

![image_2024-07-30_091113439](https://github.com/user-attachments/assets/d01e273e-4826-48c1-a0a8-45dadae05d2f)

### Minimal, Complete and Verifiable Example code:

float rounding = 50.f;
ImGui::GetBackgroundDrawList()->AddShadowRect(ImVec2(x, y), ImVec2(x + w, y + h), ImColor(_theme.childBackground.Value.x, _theme.childBackground.Value.y, _theme.childBackground.Value.z, _theme.childBackground.Value.w * ImGui::GetStyle().Alpha), 50.f, ImVec2(0,0), 0, rounding);

**Comment by ocornut** [comment]
This is in the undocumented and pretty much stalled `shadows` branch.

This is not currently supported, aka shadows not expected to be used for that. The best you can do is tweak parameters to make the shadow looks more subtle or more rounded but you can't tweak them live. Shadows can't function properly until we finish work on texture refresh update (maybe 1.92).

**Comment by ocornut** [comment]
Also, sorry but #1586.
