### ISSUE TITLE
Malformed backtick escape in v1.91.0 release notes

### ISSUE THREAD

**Issue by Rageking8** [ocornut/imgui#7839]
### Version/Branch of Dear ImGui:

Not applicable

### Back-ends:

Not applicable

### Compiler, OS:

Not applicable

### Details:

**My Issue:**

Malformed backtick escape on this line of the v1.91.0 release notes:
![image](https://github.com/user-attachments/assets/365c22d3-3dc0-4a14-942e-4cdb04046bcb)

**Comment by ocornut** [comment]
Fixed, thank you!
