### ISSUE TITLE
Emscripten: Handling "external" clipboard

### ISSUE THREAD

**Issue by ypujante** [ocornut/imgui#7851]
### Version/Branch of Dear ImGui:

Version 1.91.0

### Back-ends:

imgui_impl_glfw.cpp

### Compiler, OS:

emscripten / browser

### Details:

With the release of ImGui 1.91.0 and the support for `emscripten-glfw`, as you know, the clipboard is now supported in the browser environment. For example, you can now copy the build configuration (which can [try for yourself](https://pongasoft.github.io/imgui/pr-7647/use_port_contrib_glfw3/) with the demo I pushed with the PR)

If you copy to the clipboard by calling `glfwSetClipboardString`, then I store the string locally and push it to the external clipboard (which is why you can paste it outside the browser).
If you then paste from the clipboard by calling `glfwGetClipboardString`, then the clipboard string that was stored previously is returned.

In other words, copy/paste from within the application works great.

The issue comes with pasting **from** the "external" clipboard: the Javascript API, which is the API that I need to use is asynchronous. For this purpose, in the latest version of `emscripten-glfw`, I added a new API which reflects this API:

```c
typedef void (* emscripten_glfw_clipboard_string_fun)(void *userData, char const *clipboardString, char const *error);
void emscripten_glfw_get_clipboard_string(emscripten_glfw_clipboard_string_fun callback, void *userData);
```

I am using this API in my recently released [WebGPU Shader Toy](https://pongasoft.github.io/webgpu-shader-toy/) tool for the code editor class (`TextEditor`) because I am in control of this logic: when I detect a "Paste" event (CTRL+V), I call the asynchronous API and when I receive the result, I do the actual Paste action.

Of course this does not work with `ImGui::InputText` and I wanted to ask you if you could think of a way, or giving me pointers of whether this would be possible to do in ImGui (I tried to look at Shortcut routing but I don't know if that is even the right place to start...). I would be more than happy to do a PR for the work if this is something that is possible at all. Otherwise I could implement an entirely new control for my project.

Thank you

**Comment by ocornut** [comment]
> when I detect a "Paste" event (CTRL+V),

Who is detecting the event? Is that a paste event emitted from the browser? or it is your app querying key for ctrl+v press and then doing an asynchronous query for clipboard data?

Could you e.g. preemptively do this query every time an InputText is activated (via polling `io.WantTextInput`) and everytime the application is refocused while one is active? and then you carry that data locally in the emscripten data and it would be ready to provide whenever needed?

**Comment by ypujante** [comment]
> Who is detecting the event? Is that a paste event emitted from the browser? or it is your app querying key for ctrl+v press and then doing an asynchronous query for clipboard data?

The detection is from the ImGui side, something like this

```cpp
if (ImGui::GetIO().KeyCtrl && ImGui::IsKeyPressed(ImGuiKey_V))
```

> Could you e.g. preemptively do this query every time an InputText is activated (via polling `io.WantTextInput`) and everytime the application is refocused while one is active? and then you carry that data locally in the emscripten data and it would be ready to provide whenever needed?

I didn't think about doing it preemptively. But I know that Firefox does a little popup when you try do do a paste from Javascript to allow/disallow pasting:

<img width="604" alt="Screenshot 2024-08-01 at 13 07 19" src="https://github.com/user-attachments/assets/04049782-f50c-4927-aeea-0cbb565ac4e0">

If you want to try it yourself, you can use Firefox and go [there](https://pongasoft.github.io/emscripten-glfw/test/demo/main.html) and click on Paste after copying something in the clipboard outside the browser...

So if I were to do it preemptively then I would end up with these popups even if you are not trying to copy the clipboard.

**Comment by ocornut** [comment]
In that case we may need to design a new API replacement for `GetClipboardText()` that would allow widgets for polling for readyness of a async request and make `InputTextEx()` uses that.

**Comment by ypujante** [comment]
Clearly somebody [already noticed](https://github.com/ocornut/imgui/pull/7647#issuecomment-2265178670) the issue raised by this ticket :)

> In that case we may need to design a new API replacement for `GetClipboardText()` that would allow widgets for polling for readyness of a async request and make `InputTextEx()` uses that.

I don't mind looking into your suggestion. Any code I could look at that does something somewhat similar?

Thanks

**Comment by ocornut** [comment]
Nope I cannot think of an example. I believe the caller would probably need to get a unique id (eg a simple sequential integer) and use that when creating and polling the request. Request would naturally elapse if it stops being polled.

**Comment by ypujante** [comment]
I will spend some cycles on this and report back. Thank you!

**Comment by ypujante** [comment]
Just wanted to let you know that I am looking into this. I was able to build a prototype with the async API fairly easily (far easier than I thought). I am bumping into some issues with the "Paste" popup displayed by Safari and Firefox as a security measure because they kill event propagation, so the keys (ex: CTRL + V) remained stuck down forever because I never get the "up" event :(

You can try for yourself with this 100% pure HTML test case.

[paste.html.zip](https://github.com/user-attachments/files/16513787/paste.html.zip)

I am looking into this as well as other ways of doing this entirely...

**Comment by Maksons** [comment]
Sorry, 
Did you tried it similar way to https://github.com/Armchair-Software/emscripten-browser-clipboard  ?
This one worked for me,  had do find correct place to register callbacks, it is after "ImGui::CreateContext();" in my case.

**Comment by ypujante** [comment]
Following up on this, I have now released emscripten-glfw v3.4.0.20240817 with the changes mentioned. Once released with emscripten (unclear about timing), I will create a PR for changes in ImGui (very small PR).

As an FYI I have updated my real live application [WebGPU Shader Toy](https://pongasoft.github.io/webgpu-shader-toy/) to use this latest version. You can try it out and you will see that the main editor supports copy/paste with the desktop as well as all text fields (like the one in the "Rename" popup) and this one is an `ImGui::InputText` widget. If you use a Mac, then the shortcuts are now the macOS shortcuts and copy/paste work as well.

The *only* changes in my code is this:

```cpp
  ImGuiIO& io = ImGui::GetIO();
  io.ConfigMacOSXBehaviors = emscripten::glfw3::IsRuntimePlatformApple();

  // essentially disable repeat on Meta + Key
  emscripten::glfw3::SetSuperPlusKeyTimeouts(10, 10);

```

**Comment by ocornut** [comment]
Hello,
Is this a closable issue?

**Comment by ypujante** [comment]
I believe so. When using emscripten 3.1.65+ (current version is 3.1.66) it will automatically work for pc/linux and it will work for macos as soon as the changes you committed recently are released. 

Of course this assumes using emscripten-glfw with ImGui instead of the built-in implementation
