### ISSUE TITLE
How can I detect when the user is focused on a specific InputText() ?

### ISSUE THREAD

**Issue by zMidair** [ocornut/imgui#7855]
### Version/Branch of Dear ImGui:

Version 1.90

### Back-ends:

n/a

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

Hi! I have an Input Text that is read-only and I want to detect and do something when the user focuses on the input (even without trying to write). Or, better said, how can I detect when the user clicks on the InputText() ?

**Comment by zMidair** [comment]
I also want to do something else, when the user clicks on the Input and presses ESC. I know about the ```ImGuiInputTextFlags_EscapeClearsAll``` flag but I want to do something else

**Comment by ocornut** [comment]
You can use IsItemActive() to detect the state or IsItemActivated() to detect the transition. 

To override Esc you can use Shortcut(ImGuiKey_Esc, ImGui::GetItemID(), ImGuiInputFlags_RouteOverActive); this will naturally disable the inputtext own processing or Esc as your input routing will override the default one.

**Comment by zMidair** [comment]
I cant seem to find the Shortcut thing. Can you provide more info about where I could find specific functions and where to use them? (for IsItemActive() idk where to use it, after I create the input?)

**Comment by ocornut** [comment]
You’ll need to update to latest version.
For IsItemXXX functions search for their use in demo and in demo>widgets>querying item state.

**Comment by zMidair** [comment]
Okay, thanks!

**Comment by zMidair** [comment]
One more question, huge sorry for asking too much things, what the version number for the latest version? I’m using a modified version of ImGui and I have to make a workaround for updating it past 1.90

**Comment by ocornut** [comment]
I am not answering a question for which you can get the answer in 1 click.

**Comment by zMidair** [comment]
Okay, have a good day.
