### ISSUE TITLE
ImFontAtlasBuildWithStbTrueType assertion with Gcc 13+

### ISSUE THREAD

**Issue by smallstepforman** [ocornut/imgui#7856]
### Version/Branch of Dear ImGui:

v1.91.1

### Back-ends:

OpenGL / glfw3

### Compiler, OS:

gcc 13.2 and higher

### Details:

With older Gcc compilers (11, 12) and with VS 2022, I have working code which appends a range of glyphs to StbTruetype.  Using gcc compiler 13 and 14, I get an assertion in imgui_draw.cpp:2819 bool ImFontAtlasBuildWithStbTruetype(ImFontAtlas *) Assertion 'src_range[0] <= src_range[1]' failed.

### Minimal, Complete and Verifiable Example code:

```cpp
static const ImWchar kAdditionalUnicodeChars[] =
	{
		0x00a1/*¡*/, 0x00a2/*¢*/, 0x00a9/*©*/, 0x00ae/*®*/, 0x00b1/*±*/, 0x00bf/*¿*/, 0x00c3/*Ã*/, 0x00c9/*É*/, 0x00cd/*Í*/, 0x00d1/*Ñ*/,
		0x00d3/*Ó*/, 0x00da/*Ú*/, 0x00e1/*á*/, 0x00e9/*é*/, 0x00ed/*í*/, 0x00f1/*ñ*/, 0x00f3/*ó*/, 0x00fa/*ú*/, 0x0e3f/*฿*/, 0x2018/*‘*/,
		0x2019/*’*/, 0x201b/*‛*/, 0x201c/*“*/, 0x20ac/*€*/, 0x20b1/*₱*/, 0x2122/*™*/,
	};
	fFonts[0] = io.Fonts->AddFontFromFileTTF("../../Resources/ProximaNova-Regular.ttf", 48);
	fFonts[1] = io.Fonts->AddFontFromFileTTF("../../Resources/ProximaNova-Regular.ttf", 32);
	fFonts[2] = io.Fonts->AddFontFromFileTTF("../../Resources/DejaVuSerif.ttf", 28, &config, kAdditionalUnicodeChars);  // Crashes here with Gcc 13/14, but works fine with VS2022 and GCC 11/12.
```

**Comment by smallstepforman** [comment]
Forgot to add the following for config:
ImFontConfig config;
config.MergeMode = true;

**Comment by smallstepforman** [comment]
The glyph range is persistent (static const global)

**Comment by ocornut** [comment]
There’s no end zero terminator in your array so it’s reading undefined memory.

**Comment by smallstepforman** [comment]
That works.  Thanks ocornut.

**Comment by smallstepforman** [comment]
Not a bug.  The array was not zero terminated.

**Comment by ocornut** [comment]
I will amend the comments to suggest that as another possibility of mistake. Thanks!
