### ISSUE TITLE
Inconsistent Width and strange ending behavior of PathLineTo

### ISSUE THREAD

**Issue by matthewcrews** [ocornut/imgui#7860]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: docking

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11 MSVC 2022

### Full config/build information:

Dear Imgui -> Dear Bindings -> Odin Imgui

dear_bindings: https://github.com/dearimgui/dear_bindings
Odin Imgui: https://gitlab.com/L-4/odin-imgui

### Details:

**My Issue/Question:**

I am trying to draw a segment of a circle with the goal of rendering something like this:
![image](https://github.com/user-attachments/assets/539ddee5-1d63-4119-8a8a-80d3f64bb1e5)

The code I am using is the following. It's Odin using the DearBindings but the API has a near 1:1 translations:

```odin
imgui.SetWindowPos({800, 800})
center := [2]f32{400, 400}
r1 : f32 = 100
r2 : f32 = 150
phi_2 : f32 = 0.0
phi_1 : f32 = 0.5 * math.PI

pos_1 := center + {r1 * math.cos_f32(phi_2), r1 * math.sin_f32(phi_2)}
pos_2 := center + {r2 * math.cos_f32(phi_1), r2 * math.sin_f32(phi_1)}

draw_list := imgui.GetWindowDrawList()
// Outer arc
imgui.DrawList_PathArcTo(draw_list, center, r2, phi_1, phi_2)
// Line Moving In
imgui.DrawList_PathLineTo(draw_list, pos_1)
// Inner Arc
imgui.DrawList_PathArcTo(draw_list, center, r1, phi_2, phi_1)
// Line Moving Out
imgui.DrawList_PathLineTo(draw_list, pos_2)
// Fill Line
// imgui.DrawList_PathFillConvex(draw_list, 0xaa_aa_aa_ff)
imgui.DrawList_PathStroke(draw_list, 0xaa_aa_aa_ff, {}, 2.0)
```

What I'm getting on the screen is the following (don't worry about the colors not matching):
![image](https://github.com/user-attachments/assets/74bb0183-d024-4459-bfce-6963b48c62d4)

You'll notice there are some weird artifacts where the arrows are pointing. There's some inconsistent thickness and something strange for the final line. I also tried filling the shape using this code:

```odin
// Fill Line
// imgui.DrawList_PathStroke(draw_list, 0xaa_aa_aa_ff, {}, 2.0)
imgui.DrawList_PathFillConvex(draw_list, 0xaa_aa_aa_ff)
```

Which gives me an even stranger result:
![image](https://github.com/user-attachments/assets/536b91be-1f52-4e7b-a0f0-9af919f2186f)

I believe I must be missing something fundamental to be getting such strange results. I've checked the math and I believe it's correct so I must be using the API incorrectly.

### Minimal, Complete and Verifiable Example code:

```odin
imgui.SetWindowPos({800, 800})
center := [2]f32{400, 400}
r1 : f32 = 100
r2 : f32 = 150
phi_2 : f32 = 0.0
phi_1 : f32 = 0.5 * math.PI

pos_1 := center + {r1 * math.cos_f32(phi_2), r1 * math.sin_f32(phi_2)}
pos_2 := center + {r2 * math.cos_f32(phi_1), r2 * math.sin_f32(phi_1)}

draw_list := imgui.GetWindowDrawList()
// Outer arc
imgui.DrawList_PathArcTo(draw_list, center, r2, phi_1, phi_2)
// Line Moving In
imgui.DrawList_PathLineTo(draw_list, pos_1)
// Inner Arc
imgui.DrawList_PathArcTo(draw_list, center, r1, phi_2, phi_1)
// Line Moving Out
imgui.DrawList_PathLineTo(draw_list, pos_2)
// Fill Line
imgui.DrawList_PathStroke(draw_list, 0xaa_aa_aa_ff, {}, 2.0)
```

**Comment by matthewcrews** [comment]
Closing. The problem is that I didn't realize that the calls to draw arcs automatically connect to each other. The code that worked is the following:

```odin
center := [2]f32{400, 400}
r1 : f32 = 100
r2 : f32 = 150
phi_1 : f32 = 0.0
phi_2 : f32 = 0.5 * math.PI

pos_1 := center + {r2 * math.cos_f32(phi_1), r2 * math.sin_f32(phi_1)}

draw_list := imgui.GetWindowDrawList()
imgui.DrawList_PathArcTo(draw_list, center, r2, phi_1, phi_2)
imgui.DrawList_PathArcTo(draw_list, center, r1, phi_2, phi_1)
imgui.DrawList_PathLineTo(draw_list, pos_1)
// Fill Line
imgui.DrawList_PathStroke(draw_list, 0xaa_aa_aa_ff, {}, 2.0)
```

**Comment by ocornut** [comment]
For the second question it is because the shape is not convex, but you may use the new concave filler function.
