### ISSUE TITLE
How to change InputXXX formatting when it becomes active?

### ISSUE THREAD

**Issue by pegvin** [ocornut/imgui#7861]
### Version/Branch of Dear ImGui:

Version 1.90.9, Branch: master (Using cimgui generated bindings for C)

### Compiler, OS:

GCC v12.2.0, Debian 12

### Details:

**My Issue/Question:**

I have a `InputFloat` whose formatting I want to change when it becomes active, Currently I am trying to check if the Item was activated and I set the new format accordingly, but it doesn't take affect probably because ImGui is somehow using the old format? I am mainly trying to do this because if I use `x%.2f` formatting then the user has to manually remove the `x` from the input and enter the value else ImGui won't parse it.

```c
static const char* formatting = "x%.2f";
if (igInputFloat("##ZoomControl", &ed.view.scale, step, step, formatting, 0)) {
	ed.view.scale = ed.view.scale < 0.05 ? 0.05 : ed.view.scale;
	EditorUpdateView(&ed);
}
if (igIsItemActivated()) {
	formatting = "%.2f";
}
if (igIsItemDeactivated()) {
	formatting = "x%.2f";
}
```
If I go on to disable the `igIsItemDeactivated()` then after I "deactivate" the input, the new formatting I set in `igIsItemActivated()` is used.

### Minimal, Complete and Verifiable Example code:
```c++
static float zoom = 1.0;
static const char* formatting = "x%.2f";

ImGui::InputFloat("Zoom", &zoom, 1, 1, formatting));

if (ImGui::IsItemActivated()) {
	formatting = "%.2f";
}
if (ImGui::IsItemDeactivated()) {
	formatting = "x%.2f";
}
```

**Comment by ocornut** [comment]
It's not going to be easy to do for various reasons, I would suggest to not do it.

**Comment by pegvin** [comment]
Okay! No problem!
