### ISSUE TITLE
How can I set the default window dock position and size if they are not present inside imgui.ini ?

### ISSUE THREAD

**Issue by abdullahoday710** [ocornut/imgui#7863]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: docking

### Back-ends:

imgui_impl_SDL2.cpp + imgui_impl_bgfx.cpp (custom for bgfx)

### Compiler, OS:

windows 10 + MSVC 2022

### Details:

**My Issue/Question:**

I'm working on the level editor of my game engine, And I have realized that committing the imgui.ini file will cause a lot of merge conflicts in my repo, However, I need it to have the default "Layout" of my tools to show up properly when someone downloads or clones and builds the tools, My question is that can I set the default window size and dock space position when I call let's say ImGui::Begin() on my windows ? but only if their info is not found in the ini file

I have attached 2 screenshots of my tools with the .ini and without the ini file.

also my tool is built around the idea of "Panels" and panels can be closed and opened, and each panel basically represent an ImGui::Begin() ... ImGui::End() window

I have also attached code that displays the default opened panels for reference

also sorry if this has been asked a lot, but I couldn't find an answer to this exact problem, Any help would be appreciated :D

### Screenshots/Video:

![withoutINI](https://github.com/user-attachments/assets/63b87629-252c-414d-acd4-36a0fb9be15a)
![withINI](https://github.com/user-attachments/assets/cd418209-4a88-4d50-b97b-6c3b5ce8ab86)

### Minimal, Complete and Verifiable Example code:

```cpp
			ToolSideBar* sidebar = new ToolSideBar();
			PanelManager::AddPanel(sidebar);

// and ToolSideBar has a drawImgui function that will handle imgui
	void ToolSideBar::DrawImGui()
	{
		ImGui::Begin("Tools", &ShowToolSideBar);
                   // normal imgui stuff...
		ImGui::End();
	}
```

**Comment by ocornut** [comment]
You can call LoadSettingsFromFile() on first run with a file dedicated to be loaded once. That’s one way to solve this.

**Comment by ocornut** [comment]
Yes, apologies, i typed the previous answer on my phone and suspected I didn’t get the function name right :)

i guess you could check if there is an imgui.ini file and if there is none you load this one.
