### ISSUE TITLE
Win32 DirectX11 app resize resizes ImGui window

### ISSUE THREAD

**Issue by bubonja** [ocornut/imgui#7867]
### Version/Branch of Dear ImGui:

Version 1.88, Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

Windows 11 + MSVC

### Details:

I am rendering web cam stream (bitmaps) to win32 window with a ImGui window that contains options for my app. The problem I am encountering is that when app window is resized the ImGui window gets resized proportionally.

The default behavior in the imgui examples folder is that the imgui demo window size stays fixed when app window is resized.

I am not experienced with DirectX11 nor ImGui, could some one point me to what might be happening here and where I could look for a fix?

### Screenshots/Video:

![Screenshot 2024-08-07 151239](https://github.com/user-attachments/assets/6fbff907-2e5f-492a-8aaa-7ebf8559dc72)
![Screenshot 2024-08-07 151318](https://github.com/user-attachments/assets/2179def4-c657-48a9-91b5-00b6e7f69fe1)
![Screenshot 2024-08-07 151352](https://github.com/user-attachments/assets/8d3af40e-e586-408c-a58e-7f496e6f1171)

**Comment by ocornut** [comment]
Hello,

Please study the code of our examples and you will find what you are missing. Likely you are not resizing your frame buffer or not handling e.g. WM_SIZE events, or not calling some backend functions.
