### ISSUE TITLE
SetKeyboardFocusHere(-1) not working as expected with InputTextMultiline

### ISSUE THREAD

**Issue by SimonMaracine** [ocornut/imgui#7870]
### Version/Branch of Dear ImGui:

Version 1.91.1 WIP and 1.90.4, Branch: docking and master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Linux + GCC

### Details:

**My Issue/Question:**

As per issue [4761](https://github.com/ocornut/imgui/issues/4761), `SetKeyboardFocusHere` looks like it doesn't work correctly with `InputTextMultiline`:

```cpp
static char buffer[16];
bool reclaim_focus {false};
const auto flags {ImGuiInputTextFlags_CtrlEnterForNewLine | ImGuiInputTextFlags_EnterReturnsTrue};

if (ImGui::InputTextMultiline("##", buffer, sizeof(buffer), {}, flags)) {
    reclaim_focus = true;
}

if (reclaim_focus) {
    ImGui::SetKeyboardFocusHere(-1);
}
```

Pressing enter still makes the input text box loose focus.

But with `InputText` it works:

```cpp
static char buffer[16];
bool reclaim_focus {false};
const auto flags {ImGuiInputTextFlags_CtrlEnterForNewLine | ImGuiInputTextFlags_EnterReturnsTrue};

if (ImGui::InputText("##", buffer, sizeof(buffer), flags)) {
    reclaim_focus = true;
}

if (reclaim_focus) {
    ImGui::SetKeyboardFocusHere(-1);
}
```

It looks like resetting the focus every frame works (sets the focus), but it's undesirable:

```cpp
static char buffer[16];
const auto flags {ImGuiInputTextFlags_CtrlEnterForNewLine | ImGuiInputTextFlags_EnterReturnsTrue};

ImGui::InputTextMultiline("##", buffer, sizeof(buffer), flags);

ImGui::SetKeyboardFocusHere(-1);
```

### Screenshots/Video:

https://github.com/user-attachments/assets/bbd9f25f-fe17-416f-9579-5ad75649dcad

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
// Sorry, the code snippets are above
ImGui::End();
```

**Comment by ocornut** [comment]
Fixed again 521f84a3a + extra test https://github.com/ocornut/imgui_test_engine/commit/633988ec575ceca4e3f75660fa390b521469573e
