### ISSUE TITLE
Table drawing Horizontal Scrollbar too far below

### ISSUE THREAD

**Issue by matthewcrews** [ocornut/imgui#7874]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: docking

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11 MSVC 2022

### Full config/build information:

Dear Imgui -> Dear Bindings -> Odin Imgui

dear_bindings: https://github.com/dearimgui/dear_bindings
Odin Imgui: https://gitlab.com/L-4/odin-imgui

### Details:

**My Issue/Question:**

I'm playing with the [Imgui Manual](https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html)  to try to figure out the correct configuration of Table settings get get the behavior I want. I have a table that starts with only a few rows but users can potentially add many. At the beginning, the horizontal scrollbar is well below where the values are. Here's a screenshot from me reproducing the issue with Imgui Manual:
![image](https://github.com/user-attachments/assets/fb9d6240-502d-471c-8314-d0f419bebb02)

The red arrow points to where the horizontal scrollbar is and the blue points to where I expect it to be, next to the data in the table. What set of table settings has the horizontal scrollbar hug the data instead of all the way against the containing child window?

**Comment by GamingMinds-DanielC** [comment]
After testing a few settings I didn't find a combination that does this for you. So you would basically have to precalculate the desired table height, limit it with the available height and specify that as an explicit outer size.

**Comment by ocornut** [comment]
A table with scrolling requires a sized container, in your screenshot the specified height was 224.

We will in the future provide flags analogous to the new resize flags available in BeginChild(), to manually resize that container and apply constraints. 

As stated you can alter the table height based on the amount of contents, which may be a workaround for those missing features.

**Comment by matthewcrews** [comment]
Perfect. Thanks for the clarification!
