### ISSUE TITLE
Vertical Misalignment when using different size fonts with AlignTextToFramePadding

### ISSUE THREAD

**Issue by matthewcrews** [ocornut/imgui#7875]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: docking

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11 MSVC 2022

### Full config/build information:

Dear Imgui -> Dear Bindings -> Odin Imgui

dear_bindings: https://github.com/dearimgui/dear_bindings
Odin Imgui: https://gitlab.com/L-4/odin-imgui

### Details:

**My Issue/Question:**

I am attempting to vertically align text using `AlignTextToFramePadding` with two different font sizes but it does not appear to work.

Here is some code where I load a larger font to draw with `imgui.Text`, which I then pop to then draw the `InputDouble`. The code is Odin but the mapping to `Imgui` is essentially 1:1.

```odin
// I lookup the Label font which is 1.2x larger than the default font I use for the rest of the UI.
// This lookup returns a pointer to the loaded font
label_font : ^imgui.Font = get_label_font(state, state.font_size)
imgui.PushFont(label_font)
// Attempt to have the next Text element vertically aligned by the following InputDouble
imgui.AlignTextToFramePadding()
// The Text that is not vertically aligned with the next Input element
imgui.Text("Limit: ")
imgui.PopFont()

imgui.SameLine()
limit_label := fmt.ctprintf("##Limit_%s", constraint_settings.name)
imgui.SetNextItemWidth(number_input_width)
// The Input element that the Text should be vertically aligned with
imgui.InputDouble(
	limit_label,
	&constraint_settings.limit,
	format = double_input_format,
)
```

The result from my program is the following. I have added some horizontal red line to illustrate the misalignment.
![image](https://github.com/user-attachments/assets/1e8b4849-3833-432c-8fe7-13345a304ea7)

Should it be possible to line up a `Text` element and an `InputDouble` element that are using two different fonts?

**Comment by GamingMinds-DanielC** [comment]
`AlignTextToFramePadding()` is just supposed to align unframed texts to framed texts of the same font. Since it is immediate mode, it has no way to know in advance that you will change the font. Other than that, there are multiple potential ways to align different fonts (baseline, top, bottom, vertical center). So if you want to do that, you will need to handle the alignment yourself.

**Comment by ocornut** [comment]
I would strongly advise against trying to do this at the moment (until our layout helpers allows per-element vertical centering). But if you have to do it it may be simpler that you manually adjust the cursor position prior to each call and not use `AlignTextToFramePadding()`.

**Comment by matthewcrews** [comment]
Thanks for the clarification! It makes sense why you can't.
