### ISSUE TITLE
How can I set FULL window transparency

### ISSUE THREAD

**Issue by zMidair** [ocornut/imgui#7878]
### Version/Branch of Dear ImGui:

Version 1.91.0

### Back-ends:

n/a

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

Hi!
I want to essentially make a fade for the window. I got my functions for it but im only setting it on `ImGui::GetStyle().Alpha` which doesn't set the transparency for the window borders and margins.

Huge thanks for help and have a nice day!

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/3017f144-4813-407c-b1bf-bb786300d058)
![image](https://github.com/user-attachments/assets/5c1ce3cd-04af-4d29-b684-aa5fc711b226)

as you can see in the second, it only faded the text and background

### Minimal, Complete and Verifiable Example code:

```cpp
style.Alpha = getFadeOpacity(); //getFadeOpacity() is my own function, I run an update fade every frame and I get the opacity with this
```

**Comment by ocornut** [comment]
It clearly works if I manipulate Global Alpha in the style editor.
So it is a problem on your end.
