### ISSUE TITLE
Detecting a mouse click

### ISSUE THREAD

**Issue by voidware** [ocornut/imgui#7879]
### Version/Branch of Dear ImGui:

1.90

### Back-ends:

whatever

### Compiler, OS:

windows

### Details:

I would like to detect mouse down, followed up mouse up within a certain time without undo drag.

If i press and hold the mouse `IsMouseClicked` returns true.

How can i detect a "full click" ?

Thanks.

**Comment by voidware** [comment]
This seems to work;

```
#struct MouseMonitor
{
    bool   _down = false;
    bool   _canClick = false;

    // test this for a click
    bool   _click = false;
    
    void update()
    {
        bool down = ImGui::IsMouseDown(0);

        _click = false;

        if (down)
        {
            
            if (!_down)
            {
                _down = true;
                _canClick = true;
            }
            else if (_canClick)
            {
                auto& io = ImGui::GetIO();
                float d = io.MouseDownDuration[0];
                if (d >= 0.3f) _canClick = false;
                if (ImGui::IsMouseDragging(0)) _canClick = false;
            }
        }
        else
        {
            if (_canClick) _click = true;
            _canClick = false;
            _down = false;
        }
    }
};
```
I'll run with this until something better.

**Comment by ocornut** [comment]
This seems like a XY Problem question.
Please first clarify what you are trying to achieve and trying to solve.

**Comment by voidware** [comment]
Not sure what an XY problem is, but this is what I'm doing:

I have a picture that you can zoom and pan whilst holding the mouse down. I want to "click" on the picture to reset the zoom and pan.

How do it detect "click" on the picture to reset zoom without it being also interpreted as a pan?

If i call `IsMouseClicked` it returns true _when the mouse goes down but before it is known if this is a pan_.

If i call `IsMouseReleased` it returns true _after a pan_ when it is not a "click" and consequently pans wind up accidentally resetting the zoom.

It seems there is no proper "click" detection in `imgui`. I wrote a workaround, but i keep thinking i have missed something obvious.

Thanks for your help.

**Comment by ocornut** [comment]
`IsMouseXXX` functions are direct access to current mouse data and don't relate to more stateful elements, such as which item was clicked, etc. So your logic is fine (I would personally tend to write it in a more compact way, but that's not the point).

I believe one niggle is that `IsMouseDragging()` correctly returns false at the time of mouse button release, but actually the underlying data is still valid at the time of mouse release.
If you bypass `IsMouseDragging()` to access this data you get everything you need:

```cpp
if (ImGui::IsMouseReleased(0))
{
    IMGUI_DEBUG_LOG("duration=%.3f, dragging = %d\n", io.MouseDownDurationPrev[0], io.MouseDragMaxDistanceSqr[0] >= io.MouseDragThreshold * io.MouseDragThreshold);
}
```

So by your definition of a click (where there is a time limit) you could write:
```cpp
_click = ImGui::IsMouseReleased(0) && io.MouseDownDurationPrev[0] < 3.0f && io.MouseDragMaxDistanceSqr[0] < io.MouseDragThreshold * io.MouseDragThreshold;
```
or using imgui_internal.h you can use `IsMouseDragPastThreshold()`:
```cpp
_click = ImGui::IsMouseReleased(0) && io.MouseDownDurationPrev[0] < 0.3f && ImGui::IsMouseDragPastThreshold(0) == false;
```

But similar to your posted code that doesn't take into account the location where you initially pressed the button.

----

Higher level concepts include `ButtonBehavior()`, typically called through `InvisibleButton()`, which sets ActiveId.

```cpp
InvisibleButton(...);
_click = IsItemDeactivated() && g.LastActiveIdTimer < 0.3f && IsMouseDragPastThreshold(0) == false;
```

But you can properly emulate the same by tracking state like you did (setting a can_click on IsMouseClicked(), testing it on IsMouseReleased()).

**Comment by ocornut** [comment]
> But you can properly emulate the same by tracking state like you did (setting a can_click on IsMouseClicked(), testing it on IsMouseReleased()).

It's probably more reasonable to do this IMHO:

```cpp
InvisibleButton();
if (IsItemClicked())
   can_click = true;
if (io.MouseDownDuration[0] >= 0.3f || IsMouseDragPastThreshold(0))
   can_click = false;
if (can_click && IsMouseReleased(0))
   click = true;
```
But it requires storing "can_click".
The reason being that if you have panning and other features you are likely to want to maintain state anyhow.

**Comment by voidware** [comment]
Hi,

This is fantastic! Thanks very much for taking the time to write this. I hadn't realised there was an easy way to find the time since the mouse was pressed.

This works perfectly:

```
     ImGui::IsMouseReleased(0) && io.MouseDownDurationPrev[0] < 0.3f && ImGui::IsMouseDragPastThreshold(0) == false;
```

If i were using normal widgets I would have your `InvisibleButton` method, which is neat, but as it is I'm in a nasty bit of clickery, so the above good.

Thanks again.

**Comment by ocornut** [comment]
Closing this then, let me know if that's good for you.
