### ISSUE TITLE
IsKeyReleased throwing twice

### ISSUE THREAD

**Issue by ecraven** [ocornut/imgui#788]
If I run the following code in the sdl_opengl3 example, and add the following code, I get two lines of output for each releasing of a key:

````
		int key = SDLK_F1 & ~SDLK_SCANCODE_MASK;
		if(ImGui::IsKeyReleased(key))
			printf("F1 released, kddp: %f\n", ImGui::GetIO().KeysDownDurationPrev[key]);
````
Debugging output shows
````
SDL: set F2 to 1
SDL: set F2 to 0
F2 released, kddp: 0.000000
F2 released, kddp: 0.020000
````
So SDL sets it once, then resets it once, but ImGui shows the release twice :-/
Am I using this incorrectly, or is this an actual bug?

**Comment by ecraven** [comment]
It seems that if you replace `KeysDownDurationPrev[key]` by KeysDownDuration[key]` in `IsKeyReleased` in imgui.cpp, things work fine. Without knowing much about it and by thinking about it for a minute, this seems like the right thing anyway.

**Comment by ocornut** [comment]
Are you passing a correct >0 deltatime to imgui ?

**Comment by ecraven** [comment]
Yes, from my tests, io.DeltaTime is always around 0.01 to 0.04.

**Comment by ocornut** [comment]
I added exactly your 3 lines in examples/sdl_opengl3_example/main.cpp and it works as expected (prints once per release). Are you sure you are adding it in an unmodified backend/example base?

**Comment by ocornut** [comment]
@ecraven Any news? Could you provide a full repro?

**Comment by ecraven** [comment]
Still trying to find out what the problem is... I see a few frames between the SDL key-up event and the imgui IsKeyReleased, is that intentional? Shouldn't the release be reported in the same (or at least the next) frame?

**Comment by ocornut** [comment]
It should be reported and updated as soon as `NewFrame()` is called.

How about providing an exact self-contained repro? I pasted your code in the SDL example and it worked for me. Your report refer to other bits of printing/code and shows inconsistent F1/F2 string so I'm guessing it's not coming from a clean example repo with the 3 lines added.

**Comment by ecraven** [comment]
OK, as suspected it was my fault, I was calling the NewFrame function before the ProcessEvents function, which leads to the event being reported on the frame it happens, and on the next frame. After moving things around to the proper order, they work fine. Sorry for the time spent on this :-/ Thank you very much for all your efforts!

**Comment by ecraven** [comment]
For reference, https://imgur.com/a/HLkEM is what I've been working on, all the UI (except for the two buttons lower right) is drawn with imgui :)

**Comment by ocornut** [comment]
No worry! Thanks. I wonder if there's something we can do in NewFrame() to "detect" this but I can't find any right now. Eventually I would like to have "ImGui Test" window that has way to methodically confirm/test for all features that an application/binding should handle.

Thanks for the shot! Please post the cool action shots in the screenshot threads when you have them.
