### ISSUE TITLE
CMake Support

### ISSUE THREAD

**Issue by mccakit** [ocornut/imgui#7881]
### Version/Branch of Dear ImGui:

1.91.0

### Back-ends:

C++

### Compiler, OS:

Clang

### Full config/build information:

CLion 2024.1

### Details:

Please add CMake support so we can install imgui with fetching alone.
Like this:

cmake_minimum_required(VERSION 3.28)
project(Hello_World)

set(CMAKE_CXX_STANDARD 23)

add_executable(${PROJECT_NAME} main.cpp)

include(FetchContent)

set(GLFW_VERSION 3.4)
FetchContent_Declare(
        GLFW
        URL https://github.com/glfw/glfw/archive/refs/tags/${GLFW_VERSION}.tar.gz
)
set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(GLFW)
target_include_directories(${PROJECT_NAME} PRIVATE ${GLFW_SOURCE_DIR}/include)
target_link_libraries(${PROJECT_NAME} PRIVATE GLFW)

set(IMGUI_VERSION v1.91.0)
FetchContent_Declare(
        IMGUI
        URL https://github.com/ocornut/imgui/archive/refs/tags/${IMGUI_VERSION}.tar.gz
)
set(IMGUI_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(IMGUI_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(IMGUI_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(IMGUI)
target_include_directories(${PROJECT_NAME} PRIVATE ${IMGUI_SOURCE_DIR})
target_include_directories(${PROJECT_NAME} PRIVATE ${IMGUI_SOURCE_DIR}/backends)
add_library(IMGUI_LIB STATIC
        ${IMGUI_SOURCE_DIR}/imgui.cpp
        ${IMGUI_SOURCE_DIR}/imgui_demo.cpp
        ${IMGUI_SOURCE_DIR}/imgui_draw.cpp
        ${IMGUI_SOURCE_DIR}/imgui_tables.cpp
        ${IMGUI_SOURCE_DIR}/imgui_widgets.cpp
        ${IMGUI_SOURCE_DIR}/backends/imgui_impl_glfw.cpp
        ${IMGUI_SOURCE_DIR}/backends/imgui_impl_opengl3.cpp
)
target_link_libraries(${PROJECT_NAME} PRIVATE IMGUI)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
I don’t have the patience to answer this fifty million times.
It’s a difficult problem to provide cmake support for backends since there are no standard ways to access packages. Without cmake support for backends there’s no added value.
There are dozens of PR with cmake files already. Please use one you like.
