### ISSUE TITLE
Question: How to load state of docked windows

### ISSUE THREAD

**Issue by alexlnkp** [ocornut/imgui#7883]
### Version/Branch of Dear ImGui:

Version 1.91, Branch: docking (cimgui bindings)

### Back-ends:

https://github.com/alfredbaudisch/raylib-cimgui ; https://github.com/cimgui/cimgui

### Compiler, OS:

GCC 14.2.1, Arch Linux 6.10.3-arch1-2

### Full config/build information:

```
Dear ImGui 1.91.0 (19100)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201103
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: IMGUI_DISABLE_OBSOLETE_KEYIO
define: __linux__
define: __GNUC__=14
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_raylib
io.BackendRendererName: NULL
io.ConfigFlags: 0x00000080
 DockingEnable
io.ConfigViewportsNoDecoration
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000007
 HasGamepad
 HasMouseCursors
 HasSetMousePos
--------------------------------
io.Fonts: 2 fonts, Flags: 0x00000000, TexSize: 1024,1024
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

How do I save info on whether a window was docked or not? I can programmatically dock a window, sure, but I also want users to change the layout however they want, so that it is also saved **the way they left it**. I.E. Whatever was docked in the end of a previous launch of an app is docked on the next launch, etc.

For the docking I used code from this example: https://gist.github.com/moebiussurfing/8dbc7fef5964adcd29428943b78e45d2
I think I had to do something more than that, but honestly I'm confused with inner workings of Dear ImGui enough as is.

The worst part about this issue is that I have no idea how to narrow it down to ONE element in the convoluted chain of how Dear ImGui is integrated in my software. raylib-cimgui (rlcimgui) hooks up to raylib graphics API, so it's probably not it, thus the only culprits left are Dear ImGui itself and the cimgui bindings for it (also I might be the culprit but I wouldn't notice if I failed to add a line of code for proper docking honestly).

### Screenshots/Video:

The following video showcases the issue in my own repo: https://github.com/alexlnkp/Mapper

https://github.com/user-attachments/assets/d01b7520-8a11-4c63-934f-560f57fcc719

The following video showcases the issue in the MCVE example attached below

https://github.com/user-attachments/assets/ff8381b0-aff8-4bb7-ac23-6ee931df7009

### Minimal, Complete and Verifiable Example code:

```c
/* Command used to compile the code is
`gcc -o helpimgui helpimgui.c vendor/rlcimgui.c -l:cimgui.so -lraylib -lm -Ivendor -Ivendor/include -Lvendor/lib -Wl,-Rvendor/lib`
*/
/*Adjust the command so that it compiles properly, as I didn't use any build system for this one.
Or just use a build system with cimgui as a subdirectory, like a normal person (unlike me)*/
#include "imgui_impl_raylib.h"
#include "rlcimgui.h"
#include <cimgui.h>

#include <raylib.h>

void InitDockSpace(void) {
    static ImGuiDockNodeFlags dockspace_flags = ImGuiDockNodeFlags_PassthruCentralNode;

    ImGuiWindowFlags window_flags = ImGuiWindowFlags_MenuBar | ImGuiWindowFlags_NoDocking;

    ImGuiViewport* viewport = igGetMainViewport();
    igSetNextWindowPos(viewport->Pos, ImGuiCond_Always, (ImVec2){0,0});
    igSetNextWindowSize(viewport->Size, ImGuiCond_Always);
    igSetNextWindowViewport(viewport->ID);
    igPushStyleVar_Float(ImGuiStyleVar_WindowRounding, 0.0f);
    igPushStyleVar_Float(ImGuiStyleVar_WindowBorderSize, 0.0f);
    window_flags |= ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove;
    window_flags |= ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoNavFocus;

    if (dockspace_flags & ImGuiDockNodeFlags_PassthruCentralNode)
        window_flags |= ImGuiWindowFlags_NoBackground;

    igPushStyleVar_Vec2(ImGuiStyleVar_WindowPadding, (ImVec2){0.0f, 0.0f});
    igBegin("DockSpace", NULL, window_flags);
    igPopStyleVar(1); // NOTE: original code called this function without any arguments, I assume it's overloaded to either accept 1 or 0 arguments, my only guess is that the overload that doesn't accept any arguments means to call PopStyleVar for only one entry in the stack?
    igPopStyleVar(2);

    ImGuiIO* io = igGetIO();
    if (io->ConfigFlags & ImGuiConfigFlags_DockingEnable) {
        ImGuiID dockspace_id = igGetID_Str("MyDockSpace");
        igDockSpace(dockspace_id, (ImVec2){0.0f, 0.0f}, dockspace_flags, ImGuiWindowClass_ImGuiWindowClass());

        static bool first_time = true;
        if (first_time) {
            first_time = false;

            igDockBuilderRemoveNode(dockspace_id); // clear any previous layout
            igDockBuilderAddNode(dockspace_id, dockspace_flags | ImGuiDockNodeFlags_DockSpace);
            igDockBuilderSetNodeSize(dockspace_id, viewport->Size);

            igDockBuilderFinish(dockspace_id);
        }
    }
}

void BeginGUIDraw(void) {
    ImGui_ImplRaylib_ProcessEvents();

    ImGui_ImplRaylib_NewFrame();
    igNewFrame();
}

void EndGUIDraw(void) {
    igRender();
    ImGui_ImplRaylib_RenderDrawData(igGetDrawData());
}

void DrawMenuBar(void) {
    if (igBeginMenuBar()) {
        if (igBeginMenu("File", true)) {
            if (igMenuItem_Bool("Exit", "Esc", false, true)) printf("Pretend this does something\n");
            if (igMenuItem_Bool("Export map", "Ctrl+S", false, true)) printf("Pretend this does something\n");
            
            igEndMenu();
        }
        if (igBeginMenu("Create", true)) {
            if (igMenuItem_Bool("Cube", "Shift+C", false, true)) printf("Pretend this does something\n");
            igEndMenu();
        }

        igEndMenuBar();
    }
}

void DrawObjectListPanel(void) {
    ImGuiWindowFlags windowFlags = ImGuiWindowFlags_NoCollapse;

    igPushStyleColor_U32(ImGuiCol_ResizeGrip, 0);

    bool show = (igBegin("Object list", NULL, windowFlags)); {
        /* Pretend there's code here */
    } igEnd();
}

void DrawObjectContextMenu(void) {
    ImGuiWindowFlags windowFlags = ImGuiWindowFlags_NoCollapse;

    bool show = (igBegin("Object context menu", NULL, windowFlags)); {
        
    } igEnd();
}

void DrawGUI(void) {
    BeginGUIDraw(); {
        InitDockSpace();
        DrawObjectListPanel();
        DrawObjectContextMenu();
        DrawMenuBar();
    } EndGUIDraw();
}

void InitGUI(void) {
    rligSetup(true);

    igCreateContext(NULL);
    ImGuiIO *ioptr = igGetIO();

#ifdef IMGUI_HAS_DOCK
    ioptr->ConfigFlags |= ImGuiConfigFlags_DockingEnable;
#endif

    ImGui_ImplRaylib_Init();
    ImFontAtlas_AddFontDefault(ioptr->Fonts, NULL);
    rligSetupFontAwesome();

    /* required to be called to cache the font texture with raylib */
    ImGui_ImplRaylib_BuildFontAtlas();
}

void DeInitGUI(void) { ImGui_ImplRaylib_Shutdown(); igDestroyContext(NULL); }

void Draw(void) {
    BeginDrawing(); {
        ClearBackground(RAYWHITE);

        DrawGUI();
    } EndDrawing();
}

int main(void) {
    InitWindow(1280, 720, "insert_a_window_title_here");
    SetTargetFPS(60);

    InitGUI();

    while (!WindowShouldClose()) {
        Draw();
    }

    DeInitGUI();
    CloseWindow();

    return 0;
}
```

**Comment by ocornut** [comment]
It is already saved and restored. You are the one destroying it with your call to igDockBuilderRemoveNode(). Maybe check if the node already exists or if imgui.ini already exists or another criteria.

**Comment by alexlnkp** [comment]
> It is already saved and restored. You are the one destroying it with your call to igDockBuilderRemoveNode(). Maybe check if the node already exists or if imgui.ini already exists or another criteria.

I suspected that too, but removing the line doesn't seem to do anything.

**Comment by alexlnkp** [comment]
Changed the name of the issue due to learning that the layout and docking parameters **are** saved correctly, but seem to just not load properly.

**Comment by alexlnkp** [comment]
> > removing the line doesn't seem to do anything.
> > What is also strange is the fact that without the line, this layout is loaded correctly:
> 
> You are saying two contradictory things here, and it’s unclear what you actually changed or tested.

I edited the comment later after finding out about the one kind of layout that indeed loads, forgot to change that part, my bad.
Removing the line allows for the loading of the layout in the attached screenshot; I'll edit the comment.

**Comment by ocornut** [comment]
This is still very ambiguous. You are talking about a line when there’s a whole block modifying dock layout.

First confirm that everything works well by removing the entire block, then you know that block is the culprit.

**Comment by alexlnkp** [comment]
> This is still very ambiguous. You are talking about a line when there’s a whole block modifying dock layout.
> 
> First confirm that everything works well by removing the entire block, then you know that block is the culprit.

Alrighty, It works now, thanks! The only issue that remains is this kind of overlapping docking visual helpers or whatever those are called:
(on the right, when dragging a window)
![idkd](https://github.com/user-attachments/assets/c203d228-2650-4bdf-b6e7-b232a2524a8a)

**Comment by ocornut** [comment]
You removed the block which confirms that block was overwriting layout data.
Now as mentioned in my first answer, and replace the `if (first_time)` test by e.g. `if (igDockBuilderGetNode(dockspace_id) == NULL)`.

I don't understand what other issue you are talking about. What's the issue? Those markers are showing when dragging a dock node. What is the problem in your screenshot? Please be a little more explicit when you ask questions.

**Comment by alexlnkp** [comment]
> I don't understand what other issue you are talking about. What's the issue? Those markers are showing when dragging a dock node. What is the problem in your screenshot?

It's the fact that those two "right-side" markers in particular do overlap. One is from the window docked to the right side of the screen, the other is from the right side of the screen itself, which should ideally be hidden and not-interactive, as there's another window docked to it already.
![idkdd](https://github.com/user-attachments/assets/a641567b-699c-46aa-83ba-e15dbbd27d99)

> Please be a little more explicit when you ask questions.

I apologize if my questions and/or responses are vague, I barely understand the inner mechanics of Dear ImGui, so it's a bit hard for me to properly refer to some things that bother me, but I'm trying to be as explicit as possible when describing issues. I appreciate You pointing out what I should clarify.

**Comment by ocornut** [comment]
> overlap. One is from the window docked to the right side of the screen, the other is from the right side of the screen itself, which should ideally be hidden and not-interactive, as there's another window docked to it already.

the two locations have slightly different meanings as the nodes are hierarchical.

**Comment by alexlnkp** [comment]
> > overlap. One is from the window docked to the right side of the screen, the other is from the right side of the screen itself, which should ideally be hidden and not-interactive, as there's another window docked to it already.
> 
> the two locations have slightly different meanings as the nodes are hierarchical.

Got it! Thank You so much for helping me with this :)
Closing this issue.
