### ISSUE TITLE
Locked on 62 / 63 fps in dx11 without Vsync

### ISSUE THREAD

**Issue by sb4ggy** [ocornut/imgui#7884]
### Version/Branch of Dear ImGui:

ImGui Directx11

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 10 Visual studio 2022

### Details:

**My Issue/Question:**

on my ch3at with dx11 the fps is locked on 62 / 63 also if i enable vsync ( im on 144hz monitor ). i tryied also changing overlay but nothing. im using also the standard imgui so i dont have " fps drop " for animation and other things. when i tryied on the dx11 imgui example without vsync my fps were at 8000 and more. idk how to resolve this problem. i tryied everything

**Comment by ocornut** [comment]
Sorry but #1586
