### ISSUE TITLE
InputText display latency when trickling events

### ISSUE THREAD

**Issue by kyle-sylvestre** [ocornut/imgui#7889]
### Version/Branch of Dear ImGui:

Version 1.91.1 WIP, Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

Windows 10 MSVC 2022

### Details:

Created from the discussion in #7886

io.ConfigInputTrickleEventQueue adds a frame delay in processing characters. This effect is cumulative, simultaneous keystrokes that would have happened in one frame are now spread over many.

### Minimal, Complete and Verifiable Example code:

```cpp
// Type fast into the input box, toggle the checkbox to see the difference
static char buf[1024];
ImGui::Begin("Trickle Latency");
ImGui::Checkbox("io.ConfigInputTrickleEventQueue", &ImGui::GetIO().ConfigInputTrickleEventQueue);
ImGui::InputText("Input", buf, sizeof(buf));
ImGui::End();
```

**Comment by ocornut** [comment]
I have pushed a fix : 092c88d (sorry forgot to amend Changelog, will be done in a subsequent commit).
It's not perfect there's a bit of heuristic involved, basically we only trickle "non-char" keys, so e.g. Key Enter + Char 'A' in same space would be trickled, whereas Key A + Char 'A' won't.

It seems unfortunately I little bit difficult to do better without e.g. making backend provide extra information to allow us to associate key event and char event (e.g. some low-level timestamp?). I hope this workaround can get us running for a good amount of time.

If esoteric keyboard layouts requires us to reevaluate how we built `KeysMayBeCharInput[]` (which was built for 5fdcdf708, #456), we could potentially dynamically adjust/infer part of this based on key/event sequences.

Let me know if that works for you!

**Comment by ocornut** [comment]
Amended TestSuite to take account for that:
https://github.com/ocornut/imgui_test_engine/commit/91713638f76856c057be4b9fbe7d9ed5023d3e4d

**Comment by kyle-sylvestre** [comment]
I'm no longer seeing the display latency in my project, thanks!

**Comment by ocornut** [comment]
Honestly I am surprised this hasn't been reported earlier, and even more so that I didn't notice it myself.
Thank you for that.
