### ISSUE TITLE
ImGui::Image tint_col doesn't allow amplifying texture color intensity

### ISSUE THREAD

**Issue by voithos** [ocornut/imgui#7890]
### Version/Branch of Dear ImGui:

Branch: master

### Back-ends:

Using custom engine/back-end

### Compiler, OS:

Linux/WebGL/Android

### Details:

**My Issue/Question:**

I was attempting to use `ImGui::Image` to draw some previews for some intermediate LUT textures that I'm generating in my app. Some of these textures are pretty "dark" when drawn directly to screen, as they contain low-magnitude luminance information, so ideally I'd want to multiply the texture values by some static number in order to make it more visually readable.

Currently, `ImGui::Image` takes an `ImVec4& tint_col` param that can be used to tint the color of the image before drawing it, so I thought that could work for my use case, but after trying to pass colors with component values >1, I realized that this doesn't work and that ImGui seems to clamp the tint color between [0, 1]. Looking at the code, it seems `GetColorU32()` ends up calling `IM_F32_TO_INT8_SAT()` which saturates the color component before packing it.

I'm not sure how hard it would be to support this case, but it seems like it'd be nice to support this.

### Minimal, Complete and Verifiable Example code:

```cpp
// Try to amplify image color by 5.
ImVec4 tint_col = {5.0f, 5.0f, 5.0f, 1.0f};
// Draw image and notice that colors didn't change.
ImGui::Image(texture, /*size=*/ImVec2(100, 100), /*uv0=*/ImVec2(0, 0),
               /*uv1=*/ImVec2(1, 1), tint_col);
```

**Comment by ocornut** [comment]
Colors are encoded into packed U32 when stored in ImDrawList, and thus capped to 0..255 range and not float or HDR.
So it's not currently possible until perhaps later (but unlikely) we switch to another format.

A possible workaround may be to use `ImDrawList::AddCallback()` to set some parameters or custom shader which will use an extra uniform value for scaling colors. Generally for this kind of work you will likely end up wanting to use a custom shader eventually.
