### ISSUE TITLE
doc: mistake in comment

### ISSUE THREAD

**Issue by ryuukk** [ocornut/imgui#7897]
### Version/Branch of Dear ImGui:

master: 29fadad1939ab62adcc5cd9339db7a784de90120

### Back-ends:

imgui.h

### Compiler, OS:

linux x64

### Details:

**My Issue/Question:**

https://github.com/ocornut/imgui/blob/29fadad1939ab62adcc5cd9339db7a784de90120/imgui.h#L3388

A mistake in this comment `which only this this info` 2x `this`

**Comment by ocornut** [comment]
Thank you, I fixed it as part of 1b61d55!
