### ISSUE TITLE
Support char 'x' for ImGuiInputTextFlags_CharsHexadecimal

### ISSUE THREAD

**Issue by Halen84** [ocornut/imgui#7899]
### Version/Branch of Dear ImGui:

Version 1.91.0, Branch: master

### Back-ends:

- 

### Compiler, OS:

- 

### Details:

**My Issue/Question:**

I'm not sure if this is a intentional design choice so I didn't create a PR for this

It would be nice if `ImGuiInputTextFlags_CharsHexadecimal` supported char 'x' for inputs. This can be implemented by changing some code in `InputTextFilterCharacter()` in `imgui_widgets.cpp` (See code below)

However, the code below would allow 'x' to be placed anywhere, so improvements can be made here if you so desire

### Minimal, Complete and Verifiable Example code:

```cpp
// Allow x 0-9 a-F A-F
if (flags & ImGuiInputTextFlags_CharsHexadecimal)
    if (c != 'x' && !(c >= '0' && c <= '9') && !(c >= 'a' && c <= 'f') && !(c >= 'A' && c <= 'F'))
        return false;
```

**Comment by ocornut** [comment]
I believe it is a simpler that you don't use `ImGuiInputTextFlags_CharsHexadecimal` but your own `ImGuiInputTextFlags_CallbackCharFilter`. If you are going to implement custom parsing (to remove the 0x) your widget is going to be wrapped anyhow.
