### ISSUE TITLE
Persian / Arabic font support 

### ISSUE THREAD

**Issue by AMRD1234** [ocornut/imgui#7905]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Windows

### Details:

**My Issue/Question:**

Hello, can you add right to left texts to imgui?
Because it really needs something too, for a user interface library.
Thank you very much for this wonderful library.

**Comment by ocornut** [comment]
Sorry unfortunately, right-to-left text, bidirectional text and text shaping are not planned.
See #4227
Also #6536 #5620 

And section 5 of https://github.com/ocornut/imgui/issues/7892#issuecomment-2291436235
