### ISSUE TITLE
where is imgui_impl_glfw_gl3.cpp in the latest version

### ISSUE THREAD

**Issue by sagoishandsome** [ocornut/imgui#7910]
### Version/Branch of Dear ImGui:

1.91.0

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

windows11+msvc2022

### Details:

**My Issue/Question:**

XXX _(please provide as much context as possible)_

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
As stated in [v1.62](https://github.com/ocornut/imgui/releases/tag/v1.62) release notes and Changelog.
```cpp
before: imgui_impl_glfw_gl3.cpp    --> after: imgui_impl_glfw.cpp + imgui_impl_opengl2.cpp
```
Backends were split into a Renderer part and a Platform part in June 2018.

Please read to examples to know how to use backends.
