### ISSUE TITLE
Being able to dock by dragging from any empty space within ImGui window, not only title bar

### ISSUE THREAD

**Issue by MirrasHue** [ocornut/imgui#7911]
### Version/Branch of Dear ImGui:

Version 1.89, Branch: docking

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Windows 11 + GCC 14

### Full config/build information:

```cpp
// Basic initialization code:
void init(GLFWwindow* window)
{
    // Setup Dear ImGui context
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO();

    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;       // Enable Keyboard Controls
    //io.ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;        // Enable Gamepad Controls
    io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;           // Enable Docking

    // Setup Dear ImGui style
    ImGui::StyleColorsDark();

    ImGuiStyle& style = ImGui::GetStyle();
    style.WindowRounding = 5.0f;
    style.Colors[ImGuiCol_WindowBg].w = 1.f;

    // Setup Platform/Renderer backends
    ImGui_ImplGlfw_InitForOpenGL(window, true);
    ImGui_ImplOpenGL3_Init("#version 330");
}
```

### Details:

**My Issue/Question:**

I have an old project which uses ImGui version 1.89, and there, even if I drag a window from any of its empty space, imgui gives me the option to dock it.

Now I'm working on a new project, using version 1.91.1, and I only can dock the window if I drag it from its title bar.

I tried to look at the changelogs to see if this behavior changed in a newer version, but couldn't find it.

I also tried using the new version on the old project, and it stopped working.

Is there a way to enable the old behavior without many workarounds? I find this feature very useful.

### Minimal, Complete and Verifiable Example code:

```cpp
// imgui begin frame

// On 1.89 (docking), only this is sufficient to achieve what I mentioned
ImGui::DockSpaceOverViewport();
ImGui::ShowDemoWindow();

// imgui render
```

**Comment by ocornut** [comment]
Hello,
I am pretty sure that has never been the case and I just tried 1.89 to confirm and it isn't the case.

However, there is a configuration option:
```cpp
io.ConfigDockingWithShift = true;
```
Which makes Docking requires holding Shift. Because this is more explicit, when using this you can dock window even by dragging them from empty space. The feature was briefly removed between 1.83 and 1.85 WIP then restored because I realize some big users wanted it.

(aside from that: there is some rework I want to do to better track whether a drag leads to docking or not, because currently the geometry tests done based on title bar geometry, and it's not obvious how to implement a "docking" widget. It also leads to this bug #7210).

**Comment by MirrasHue** [comment]
Hey Omar, thanks for responding.

It's been almost two years since I worked on that project, I can't quite remember if I modified ImGui in such a way to enable this docking behavior. Unfortunately, I can't get the source files for the 1.89 (docking) version here on GitHub, only newer releases have the docking branch under the available tags. If you could share the source code here, I would appreciate it, so that I could find a way to look at the diff. I'm also going to share the source files I'm using, if you want to take a look.

[src-1.89_docking.zip](https://github.com/user-attachments/files/16731242/src-1.89_docking.zip)

The mouse cursor doesn't appear on the print, but I'm dragging the window from its lower empty space, and just to make the functionality clear, I made the title bar go out of sight, to demonstrate I can still dock:

![image](https://github.com/user-attachments/assets/fb81daaf-0f6d-43b3-9236-f7159e8fddd8)

**Comment by ocornut** [comment]
Hello,
I can't study your random source code drop, I am just stating that I verified with 1.89 docking by manually pulling a hash and it didn't do that. If you want this feature it's probably better than you use `io.ConfigDockingWithShift = true`.

**Comment by MirrasHue** [comment]
I need to figure out how to do that to get the original 1.89 docking branch. Maybe the zip file is a little sketchy, I could've just uploaded imgui.h/cpp and the backends I'm using, but it probably wouldn't make a difference.

Oh, I forgot to mention, the version num is 18808, it was hidden in the print. I don't know if they change within the same version or not, 1.89(WIP) in this case.

**Comment by MirrasHue** [comment]
Hello, @ocornut

After some inspection, the difference is in this function:
```cpp
void ImGui::BeginDockableDragDropSource(ImGuiWindow* window)
```

Indeed, I modified it to achieve that behavior, basically, I made is_drag_docking to be always true:

```cpp
void ImGui::BeginDockableDragDropSource(ImGuiWindow* window)
{
    ImGuiContext& g = *GImGui;
    IM_ASSERT(g.ActiveId == window->MoveId);
    IM_ASSERT(g.MovingWindow == window);
    IM_ASSERT(g.CurrentWindow == window);

    g.LastItemData.ID = window->MoveId;
    window = window->RootWindowDockTree;
    IM_ASSERT((window->Flags & ImGuiWindowFlags_NoDocking) == 0);
    bool is_drag_docking = (g.IO.ConfigDockingWithShift) || true; //ImRect(0, 0, window->SizeFull.x, GetFrameHeight()).Contains(g.ActiveIdClickOffset); // FIXME-DOCKING: Need to make this stateful and explicit
    if (is_drag_docking && BeginDragDropSource(ImGuiDragDropFlags_SourceNoPreviewTooltip | ImGuiDragDropFlags_SourceNoHoldToOpenOthers | ImGuiDragDropFlags_SourceAutoExpirePayload))
    {
        SetDragDropPayload(IMGUI_PAYLOAD_TYPE_WINDOW, &window, sizeof(window));
        EndDragDropSource();

        // Store style overrides
        for (int color_n = 0; color_n < ImGuiWindowDockStyleCol_COUNT; color_n++)
            window->DockStyle.Colors[color_n] = ColorConvertFloat4ToU32(g.Style.Colors[GWindowDockStyleColors[color_n]]);
    }
}
```

My bad for not remembering this change on my part and thinking it was in the library by default.

Thanks for your time, I'm going to close the issue.
