### ISSUE TITLE
is it possible to render glow text with imgui

### ISSUE THREAD

**Issue by driftsy-dev** [ocornut/imgui#7916]
### Version/Branch of Dear ImGui:

1.89.4 WIP

### Back-ends:

win32, opengl

### Compiler, OS:

Windows

### Details:

**how can i render glowing text with imgui?**

i was hanging around rectangle glow done it alr
but i dont have a idea to make glowing text with imgui

is it possible to make it with imgui ?

**Comment by ocornut** [comment]
No.
