### ISSUE TITLE
Is GetPlatformIO() being declared twice in the docking branch intentional?

### ISSUE THREAD

**Issue by ShironekoBen** [ocornut/imgui#7917]
### Version/Branch of Dear ImGui:

Version 1.91.1 WIP, Branch: docking

### Back-ends:

N/A

### Compiler, OS:

N/A

### Details:

**My Issue/Question:**

It seems that `GetPlatformIO()` is declared twice in the docking branch `imgui.h` - once at line 335 under `main`, and then again at line 1083 under `Platform/IO interface`... is this intentional?

(it results in Dear Bindings complaining about the duplicate definition so if it's intentional then I'll change the code there to support it, but it wasn't really clear to me if it was there to make it easier for people to find when looking for platform support stuff or just the result of a merge-gone-wrong)

**Comment by ocornut** [comment]
That’s a mistake, i’ll fix it. Thank you.

i’ve been meaning to add eg cimgui and dear bindings to Ci maybe it’d be a good idea.

**Comment by ocornut** [comment]
Should be fixed now!

**Comment by ShironekoBen** [comment]
Thanks! I can confirm that Dear Bindings processes the header correctly now.
