### ISSUE TITLE
Exposing [imgui_impl_win32] ImGui_ImplWin32_WndProcHandler in a .dll is problematic

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [ocornut/imgui#7930]
### Version/Branch of Dear ImGui:

Version 1.91.1 WIP, Branch: docking

### Back-ends:

imgui_impl_win32.cpp

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

**My Issue/Question:**

`ImGui_ImplWin32_WndProcHandler` is defined in `imgui_impl_win32.h` as:

```
extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);
```

Now, this is fine when statically linking the backend into the executable, however, I'm having a problem exporting this symbol in a Windows DLL file. I'm setting `IMGUI_IMPL_API` to `extern "C" __declspec(dllexport)` and that works for other backends, however, this one symbol creates a problem, as the whole thing expands to
```
extern extern "C" __declspec(dllexport) LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);
```

The double `extern` results in `error C2159: more than one storage class specified`.

Granted, I'm not sure if backend functions are even designed to be exported like that, but, manually fudging the definition to
```
extern "C" __declspec(dllexport) LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);
```

... allows for the dll to build with correct symbol names.

**Comment by PathogenDavid** [comment]
Using `exern "C"` should not be used with `IMGUI_IMPL_API`. Dear ImGui is a C++ library, the symbols should be exported as C++ symbols.
