### ISSUE TITLE
How to prevent imgui ui update from freezing during window move, double click and resize events?

### ISSUE THREAD

**Issue by adityachd** [ocornut/imgui#7931]
### Version/Branch of Dear ImGui:

Version 1.91, Branch: docking

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx12.cpp

### Compiler, OS:

Windows 11 + MSVC

### Details:

**My Issue/Question:**

Hi ! I am making a simple serial terminal application using dear imgui and libserialport library in cpp.
In my initial test (and also found by running demo/examples) , I found out that if the application window is dragged or resized, the UI is not resumed until the mouse click is released. As I also saw the demo code, the Hello World Window which shows frame rate, stops updating when title bar is double clicked and not released or the title bar is dragged or the window is resized. 
I hope there would be a way to prevent the ui from pausing during these events somehow, as the serial monitor needs to update data at all times. Please help.

Thanks and Regards
Aditya

**Comment by adityachd** [comment]
I believe the WndProc function is called automatically every time on such window events like dragging etc and wither the calls are multiple i.e until the mouse in released, calls are being made.  These events are I think not letting the main loop code to get executed. Is there a way so that on such events, the WndProc function is not called, instead, we poll events in the main while loop and send events to Windows OS using DefWindowProcW once every loop iteration. 
Please help, my first day with Dear Imgui and I am loving it so far.

**Comment by GamingMinds-DanielC** [comment]
The problem stems from this basic loop:
```c++
while (!done)
{
	while (PeekMessage(...))
	{
		TranslateMessage(...);
		DispatchMessage(...);
	}

	// ImGui frame stuff
}
```
When a window is f.e. resized, Windows takes control and enters a modal message loop to enforce a few things. So while your window still receives messages through that other loop, your own loop is on hold and all of the ImGui frame stuff is not called.

The way my editor application handles it is basically this:
- move ImGui frame stuff into the handler for the `WM_PAINT` message
- secure the paint handler with a flag to make it not reentrant (hidden recursion could mess up your day otherwise)
- within your paint handler, invalidate your window again to ensure a constant flow of frames
- if your window is disabled, defer to `DefWindowProc` after handling the above (modal dialogs won't work correctly otherwise)

**Comment by adityachd** [comment]
Hi ! @GamingMinds-DanielC 
I tried following the instructions you gave. I am stuck at second step and could not understand the third one also. Please help

- move ImGui frame stuff into the handler for the WM_PAINT message
Moved the stuff into a separate function and made some stuff global like 
`WNDCLASSEXW wc;
HWND hwnd;
bool show_demo_window = true;
bool show_another_window = false;
ImVec4 clear_color = ImVec4(0.45f, 0.55f, 0.60f, 1.00f);
bool done = false;
bool wmPaintEnteredFlag = false;
void imGuiStuffFn() {
    // Start the Dear ImGui frame
    ImGui_ImplDX12_NewFrame();
    ImGui_ImplWin32_NewFrame();
    ImGui::NewFrame();
    // 1. Show the big demo window (Most of the sample code is in ImGui::ShowDemoWindow()! You can browse its code to learn more about Dear ImGui!).
    if (show_demo_window)
        ImGui::ShowDemoWindow(&show_demo_window);
    // 2. Show a simple window that we create ourselves. We use a Begin/End pair to create a named window.
    {
        static float f = 0.0f;
        static int counter = 0;
        ImGui::Begin("Hello, world!");                          // Create a window called "Hello, world!" and append into it.
        ImGui::Text("This is some useful text.");               // Display some text (you can use a format strings too)
        ImGui::Checkbox("Demo Window", &show_demo_window);      // Edit bools storing our window open/close state
        ImGui::Checkbox("Another Window", &show_another_window);
        ImGui::SliderFloat("float", &f, 0.0f, 1.0f);            // Edit 1 float using a slider from 0.0f to 1.0f
        ImGui::ColorEdit3("clear color", (float*)&clear_color); // Edit 3 floats representing a color
        if (ImGui::Button("Button"))                            // Buttons return true when clicked (most widgets return true when edited/activated)
            counter++;
        ImGui::SameLine();
        ImGui::Text("counter = %d", counter);
        ImGui::Text("Application average %.3f ms/frame (%.1f FPS)", 1000.0f / io.Framerate, io.Framerate);
        ImGui::End();
    }
    // 3. Show another simple window.
    if (show_another_window)
    {
        ImGui::Begin("Another Window", &show_another_window);   // Pass a pointer to our bool variable (the window will have a closing button that will clear the bool when clicked)
        ImGui::Text("Hello from another window!");
        if (ImGui::Button("Close Me"))
            show_another_window = false;
        ImGui::End();
    }
    // Rendering
    ImGui::Render();
    FrameContext* frameCtx = WaitForNextFrameResources();
    UINT backBufferIdx = g_pSwapChain->GetCurrentBackBufferIndex();
    frameCtx->CommandAllocator->Reset();

    D3D12_RESOURCE_BARRIER barrier = {};
    barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
    barrier.Flags = D3D12_RESOURCE_BARRIER_FLAG_NONE;
    barrier.Transition.pResource = g_mainRenderTargetResource[backBufferIdx];
    barrier.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
    barrier.Transition.StateBefore = D3D12_RESOURCE_STATE_PRESENT;
    barrier.Transition.StateAfter = D3D12_RESOURCE_STATE_RENDER_TARGET;
    g_pd3dCommandList->Reset(frameCtx->CommandAllocator, nullptr);
    g_pd3dCommandList->ResourceBarrier(1, &barrier);

    // Render Dear ImGui graphics
    const float clear_color_with_alpha[4] = { clear_color.x * clear_color.w, clear_color.y * clear_color.w, clear_color.z * clear_color.w, clear_color.w };
    g_pd3dCommandList->ClearRenderTargetView(g_mainRenderTargetDescriptor[backBufferIdx], clear_color_with_alpha, 0, nullptr);
    g_pd3dCommandList->OMSetRenderTargets(1, &g_mainRenderTargetDescriptor[backBufferIdx], FALSE, nullptr);
    g_pd3dCommandList->SetDescriptorHeaps(1, &g_pd3dSrvDescHeap);
    ImGui_ImplDX12_RenderDrawData(ImGui::GetDrawData(), g_pd3dCommandList);
    barrier.Transition.StateBefore = D3D12_RESOURCE_STATE_RENDER_TARGET;
    barrier.Transition.StateAfter = D3D12_RESOURCE_STATE_PRESENT;
    g_pd3dCommandList->ResourceBarrier(1, &barrier);
    g_pd3dCommandList->Close();
    g_pd3dCommandQueue->ExecuteCommandLists(1, (ID3D12CommandList* const*)&g_pd3dCommandList);
    ImGuiIO& io = ImGui::GetIO(); (void)io;
    // Update and Render additional Platform Windows
    if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable)
    {
        ImGui::UpdatePlatformWindows();
        ImGui::RenderPlatformWindowsDefault(nullptr, (void*)g_pd3dCommandList);
    }
    // Present
    HRESULT hr = g_pSwapChain->Present(1, 0);   // Present with vsync
    //HRESULT hr = g_pSwapChain->Present(0, 0); // Present without vsync
    g_SwapChainOccluded = (hr == DXGI_STATUS_OCCLUDED);

    UINT64 fenceValue = g_fenceLastSignaledValue + 1;
    g_pd3dCommandQueue->Signal(g_fence, fenceValue);
    g_fenceLastSignaledValue = fenceValue;
    frameCtx->FenceValue = fenceValue;
}`
Calling this function from inside while loop works fine.
- secure the paint handler with a flag to make it not reentrant (hidden recursion could mess up your day otherwise)
Added switch case inside WndProc
`
    case WM_PAINT:
        if (!wmPaintEnteredFlag) {
            wmPaintEnteredFlag = true;
            imGuiStuffFn();
            wmPaintEnteredFlag = false;
        }
        break;`
Now the window does not show anything but white screen and closes after a few seconds.
- within your paint handler, invalidate your window again to ensure a constant flow of frames
Sorry I could not understand which function to call to invalidate window. Please help
- if your window is disabled, defer to DefWindowProc after handling the above (modal dialogs won't work correctly otherwise)
I am not sure but as this is demo code only so I believe the window is not disabled. Correct me if I am wrong.

Thanks and Regards
Aditya

**Comment by adityachd** [comment]
Adding the wmPaintEnteredFlag check inside the imGuiStuffFn function also made it display the window correctly as before but still gragging and resizing the window halts the code.
Here is the whole main file in case you want to see.

[main.zip](https://github.com/user-attachments/files/16812296/main.zip)

Thanks and Regards
Aditya

**Comment by GamingMinds-DanielC** [comment]
Do not call `imGuiStuffFn()` from your main loop, only from `WM_PAINT` Also move your swapchain presentation out of your main loop, it should be the last thing you do in `imGuiStuffFn()`.

For `WM_PAINT` try this:
```c++
case WM_PAINT:
        if (!wmPaintEnteredFlag) {
            wmPaintEnteredFlag = true;
            imGuiStuffFn();
            wmPaintEnteredFlag = false;

            // invalidate in case of validation by any modal loop
            ::InvalidateRect(hWnd, NULL, FALSE)`
        }

        // let DefWindowProc handle WM_PAINT if f.e. file dialogs are open, otherwise modal prompts are somehow suppressed,
        // also required for message boxes and other modals to work correctly
        if (::IsWindowEnabled(hWnd))
            return 0;

        break;
```
You basically want to avoid `DefWindowProc` handling your painting as well, so you need to return 0. Unless you have modals open. That case might not be relevant for you right now, but if you ever need modals it gets tricky otherwise.

**Comment by adityachd** [comment]
The window is comes white and nothing is rendered inside it. ALso where do I enable CS_HREDRAW and CS_VREDRAW

**Comment by GamingMinds-DanielC** [comment]
You can set these flags in the `WNDCLASSEXW` structure you give to `RegisterClassExW()`. You can read details about that in the Win32 API documentation. If you don't know how to find it, just putting function or structure names into Google will point you in the right direction.

After that you should step through your code with a debugger to check if everything gets called as expected and that variables hold the values they should have. If that doesn't help, maybe a capture with RenderDoc can show you what is wrong.

**Comment by GamingMinds-DanielC** [comment]
No idea. You could add some logging to see what kind of messages are sent to your window. Maybe the message queue is saturated with other messages. WM_PAINT is a low priority message, it usually gets sent when everything else is done. Maybe your window gets validated somehow so that there are no more paint messages for a while, then invalidating in reaction to a short cyclic timer could help.

**Comment by adityachd** [comment]
Thanks again @GamingMinds-DanielC .
I saw the exact same behavior in QT too with windows so again must be a win32 related issue. I'll try and write back if I find any solution to that.

**Comment by adityachd** [comment]
Hi @GamingMinds-DanielC 
I added the below code to start timer on mouseclick and stop on release and also added wm_timer handler. But the WM_TIMER is not called at all. added print to check if there is error in setTimer call but there was not error. What seems wrong here?
```cpp
    case WM_TIMER:
            printf("___%d    %d\n", msg, printCounter++);
            if (!wmPaintEnteredFlag && contextCreated) {
                imGuiStuffFn();
                InvalidateRect(hWnd, NULL, FALSE);
                if (::IsWindowEnabled(hWnd))
                    return 0;
            }
            break;
    case WM_NCLBUTTONDOWN:
        if (!SetTimer(hwnd, 1, 16, (TIMERPROC)NULL))
        {
            printf("er  %8x\n",GetLastError());
        }
        else {
            printf("ner\n");
        }
        break;
    case WM_NCLBUTTONUP:
        KillTimer(hwnd, IDT_TIMER1);
        break;
```

Thanks and regards
Aditya

**Comment by adityachd** [comment]
Thanks again for the help @GamingMinds-DanielC.
