### ISSUE TITLE
Interact with the game/app when the ImGui is collapsed.  How can i do that?

### ISSUE THREAD

**Issue by aQReh** [ocornut/imgui#7938]
Hello, i need a little help with my imGui. when my menu is open i cant interact with game which is fine but i want to be able to interact with the game when the ImGui is collapsed.  How can i do that?

### Screenshots/Video:

![img](https://github.com/user-attachments/assets/43c0da47-a101-43bb-b384-c696946816f3)

```

**Comment by ocornut** [comment]
Sorry but #1586
