### ISSUE TITLE
Update GLFW example to modern OpenGL?

### ISSUE THREAD

**Issue by Megavoxel01** [ocornut/imgui#794]
Hi!

I‘m new to imgui and encounter quite a few problems when trying to integrate imgui to my OpenGL demo. I'm using the GLFW sample code you provided and I find that the sample code is using fixed function pipeline and a lot of deprecated function call, like glvertexpointer(). This makes the situation worse as some modern graphics debuggers do not support deprecated OpenGL function call (i.e. Nsight). It will be harder to figure out where's the problem.

Do you have any plan to update to modern OpenGL?

**Comment by Megavoxel01** [comment]
Oh I just found out the SDL sample was using modern OpenGL. Will give a read :)

**Comment by ocornut** [comment]
Err, have you noticed that there's two different GLFW examples?

**Comment by Megavoxel01** [comment]
Oh, my bad. I thought that's for older OpenGL.
