### ISSUE TITLE
CalcWorkRectSize discrepancy

### ISSUE THREAD

**Issue by pdoane** [ocornut/imgui#7940]
### Version/Branch of Dear ImGui:

Branch: master/docking

### Back-ends:

N/A

### Compiler, OS:

N/A

### Details:

The implementation of `CalcWorkRectSize()` differs between the master and docking branch.  I don't think either is correct though.

On master branch:

```
    ImVec2  CalcWorkRectSize(const ImVec2& off_min, const ImVec2& off_max) const    { return ImVec2(ImMax(0.0f, Size.x - off_min.x + off_max.x), ImMax(0.0f, Size.y - off_min.y + off_max.y)); }
```

On docking branch:

```
    ImVec2  CalcWorkRectSize(const ImVec2& inset_min, const ImVec2& inset_max) const { return ImVec2(ImMax(0.0f, Size.x - inset_min.x - inset_max.x), ImMax(0.0f, Size.y - inset_min.y + inset_max.y)); }
```

Note how the `max` variable contributes to the final result.

With `BeginViewportSideBar` modifying `BuildWorkInsetMax` for `ImGuiDir_Down` and `ImGuiDir_Right`, subtracting the `max` value seems like the correct behavior (which is currently done for the X axis on the docking branch).  I think the correct code here should be:

```
    ImVec2  CalcWorkRectSize(const ImVec2& inset_min, const ImVec2& inset_max) const { return ImVec2(ImMax(0.0f, Size.x - inset_min.x - inset_max.x), ImMax(0.0f, Size.y - inset_min.y - inset_max.y)); }
```

With that change, I am able to use `BeginViewportSideBar` to create a status bar at the bottom of the main viewport and the dockspace fills the remaining space correctly.

### Minimal, Complete and Verifiable Example code:

```cpp
        ImGuiWindowFlags window_flags = ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoSavedSettings;
        float windowPadding = ImGui::GetStyle().WindowPadding.y;
        if (ImGui::BeginViewportSideBar("statusbar", ImGui::GetMainViewport(), ImGuiDir_Down, ImGui::GetFrameHeight() + 2 * windowPadding, window_flags))
        {
            ImGui::Button("Status bar goes here");
        }

        ImGui::End();

        ImGui::DockSpaceOverViewport();
```

**Comment by ocornut** [comment]
Thank you and apologies for those mistakes.

The discrepancy between branches is because when I pushed cfd2395 I intended to push to master first and I guess I skipped this, and logic has been inverted there. I'll do a sync now to move a few small things back to master including this.

Fixed the subtracting in `CalcWorkRectSize()` with 6d70c2d
