### ISSUE TITLE
AddFontFromFileTTF

### ISSUE THREAD

**Issue by LongLasting** [ocornut/imgui#7944]
### Version/Branch of Dear ImGui:

1.19.0

### Back-ends:

not sure

### Compiler, OS:

Win10

### Full config/build information:

ImFont* font = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\Dengl.ttf", 30.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());
if the float value(here is 30.0f) is too big like 31.0f, the font cant be displayed, instead, it shows a ![bug](https://github.com/user-attachments/assets/16db6ea3-3882-41a8-bf46-961586b800bb)

### Details:

check the screenshot

### Screenshots/Video:

![bug](https://github.com/user-attachments/assets/123d1470-9fb2-4483-807e-bb406b7260ee)

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by GamingMinds-DanielC** [comment]
You are adding a ton of characters with a substantial size, so they can't fit into a single texture. That exceeds the limits of the current font system.

https://github.com/ocornut/imgui/blob/master/docs/FONTS.md
See troubleshooting point 4 for some potential workarounds.

**Comment by ocornut** [comment]
Closing this as answered in FAQ. Added a picture in the FAQ to make this issue more noticeable.
