### ISSUE TITLE
Examples for FreeGLUT ?

### ISSUE THREAD

**Issue by bitxue** [ocornut/imgui#795]
Hi omar,

Thank you for this awesome GUI library !

We have a project which relies on FreeGLUT and CEGUI. Currently we want to use IMGUI to rewrite the GUI part. However we cannot find FreeGLUT examples in the repository and find it hard to write one by modifying the glfw examples. Could you kindly add examples for FreeGLUT? Thanks!

**Comment by ocornut** [comment]
Hello, sorry I am not using FreeGlut myself. It should be rather easy to bind imgui to it.

**Comment by bitxue** [comment]
I finally managed to bind imgui to FreeGlut  ;)   Thanks!

**Comment by ocornut** [comment]
How about creating a PR for an additional FreeGlut example?

**Comment by bitxue** [comment]
still have a bug: the imgui windows won't update if the mouse position does not change.

will create a PR after the bug is fixed.

**Comment by bitxue** [comment]
Hi omar,

Maybe you can have a look at the code to help fix the bugs if you have some spare time :)
https://github.com/bitxue/imgui/commit/e69de80c9007accfa56ee5a3ffbac7d5dc3d6059

**Comment by bitxue** [comment]
The updating bug was fixed.    https://github.com/bitxue/imgui/commit/41f3e8e3d9885906568904b0f4e9c9da46de3c95

**Comment by bitxue** [comment]
Added glut mouse scrolling binding. https://github.com/bitxue/imgui/commit/1e4d7a3ac9c99adb183e6b4621ae42904411de38

**Comment by ppisecky** [comment]
Hey man - I am using your freeglut example for a school project. It works great except one minor thing - for some reason, when I go to fullscreen mode using glutFullScreen() I am unable to open and close windows via double click. Now what I am doing is actually rendering a mandelbrot set with 100 iterations at a quite a high resolution on a slow pc so I am not quite sure if this is a problem with the code or simply a problem of not being able to register double click. 

Have you encountered a similar issue?

**Comment by bitxue** [comment]
@ppisecky What do you mean by " open and close windows via double click"?  glutFullScreen() works without problem on my machine. I am currently under win10 64bit and vc14. What is your machine configuration?

**Comment by ocornut** [comment]
With the current API double click typically don't work at very low framerate (if your framerate is <5 fps).
