### ISSUE TITLE
Semi transparent background (Win32, DX11)

### ISSUE THREAD

**Issue by Ra1n6666** [ocornut/imgui#7952]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 11

### Details:

Hello, I am trying to make an application (Not a DLL) but I can't seem to find a way to make the window background semi-transparent (Changing the alpha).
I have tried removing the background with a flag but it seems like it not working aswell.

I am using DX11 & Win32.
Thanks.

**Comment by Ra1n6666** [comment]
> try this https://gofile.io/d/yMHabA select the desired compiler in the installer

LOL nice try...

**Comment by GamingMinds-DanielC** [comment]
Better edit out the quoted malware link there, would be a shame if anybody clicked it and got infected that way.

As for your question: if you mean the platform window, that is currently out of the scope of ImGui. If you want to give it a try yourself, this might help:
https://learn.microsoft.com/en-us/answers/questions/1190872/how-do-i-create-a-simple-transparent-window-in-win

**Comment by Ra1n6666** [comment]
> What window background? the platform (win32) window or the imgui window? https://github.com/ocornut/imgui/wiki/Glossary Have you searched for "transparent" already?

Both will work cause I am only showing the ImGui window as a win32 window
Like that:
![{18F6EB93-2EE2-4889-B20B-E68C1A2E9C11}](https://github.com/user-attachments/assets/12b40124-a2a2-497b-aca1-3531064e3f63)

**Comment by ocornut** [comment]
You are on your own there are ample resources here and outside about this.

**Comment by ocornut** [comment]
Sorry but #1586 (i was merely a proof for this I have now found it)
