### ISSUE TITLE
Suggestion: Extend demo with full screen window / docking examples

### ISSUE THREAD

**Issue by Andersama** [ocornut/imgui#7955]
### Version/Branch of Dear ImGui:

Any

### Back-ends:

Any

### Compiler, OS:

Any

### Details:

I just figured I'd point out that while:
```c
ImGui::ShowDemoWindow(&show_demo_window);
```
is an excellent resource for the basics, this function doesn't show off how to make a window "maximized" or fit to the screen, which is one of the first things a person would like to do.

I figure there's probably a good place to add a toggle button in the demo to do just that, and similarly, for builds with the dock enabled there should probably maybe there's there's a variation of "ShowDemoWindow" called "ShowDemoDock" that allows shuffling around some child windows.

**Comment by ocornut** [comment]
The DockSpace demo already has a fullscreen demo but because it does quite more things it may be a little unobvious.

You basically need to do:

```cpp
const ImGuiViewport* viewport = ImGui::GetMainViewport();
ImGui::SetNextWindowPos(viewport->WorkPos);
ImGui::SetNextWindowSize(viewport->WorkSize);
ImGui::SetNextWindowViewport(viewport->ID); // in docking branch
ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
ImGuiWindowFlags flags = ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBringToFrontOnFocus;
ImGui::Begin(...., ..., flags);
ImGui::PopStyleVar();
```

**Comment by ocornut** [comment]
Err, I just realized there IS such demo.
Demo->Examples->Fullscreen Window.
Leading to the `ShowExampleAppFullscreen()` function.

But if you mean adding a "Maximize" button to every window, that's another topic. I presume we might support it at some point. Linking to #2104 and #3486.

> called "ShowDemoDock" that allows shuffling around some child windows.

There is a Dockspace demo but that's more advanced. You can already dock and drag anything into anything by default.

**Comment by Andersama** [comment]
Ah, well, I didn't find that example, despite it being under the examples drop down. Yeah it might be better if it's related to minimizing/maximizing/restoring type buttons.

**Comment by ocornut** [comment]
> Yeah it might be better if it's related to minimizing/maximizing/restoring type buttons, 

The existing open issues are here to track when this will be implemented.

> I'm realizing now why it's strange, that demo opens another window, where you might expect it to impact the demo window.

We have many many features to demo they cannot all be packed at the beginning of the main demo window.

**Comment by Andersama** [comment]
Call me crazy, would it not be possible to add it to the front/main window?

I mean it seems like you're referencing static variables to do similar things for other features.

**Comment by ocornut** [comment]
I don't understand what you are saying. Please be more explicit. Maybe https://github.com/ocornut/imgui/wiki/Glossary can help.

**Comment by Andersama** [comment]
I thought you were referring to adding code to demonstrate the feature on the demo window itself, it seems like it'd be doable towards the start of the demo window function.

**Comment by Andersama** [comment]
@ocornut I'm not sure because it seems like from the links you referenced that someone started on this project quite a while ago, is there a commit already being considered?

I took a couple minutes and I've got a minimize/maximize/restore button in the title bar using flags. The only remaining part is what the behavior exactly is.

**Comment by ocornut** [comment]
I think this discussion may be moved to #2104. If that issue is open it means that the work hasn't been done.
