### ISSUE TITLE
All windows black using SDL rendering functions

### ISSUE THREAD

**Issue by zapetino** [ocornut/imgui#796]
I'm using imgui + SDL2 with the code given in the example, if i don't render  nothing with SDL  the imgui window show correctly, if i use any sdl rendering function (SDL_RenderCopy/SDL_RenderCopyEx) the window show in grayscale.
![screen](https://cloud.githubusercontent.com/assets/1933524/17928673/1d7bf8ca-69fc-11e6-8e46-0879c56cd650.png)

**Comment by ocornut** [comment]
Maybe use SDL+OpenGL3 and try to look in the code for SDL_RenderCopy that sort of GL state is being altered, and what isn't setup by ImGui_ImplSdlGL3_RenderDrawLists().

**Comment by paulsapps** [comment]
Don't mix SDL_Render* and OpenGL, they are mutually exclusive. You need to change all of your rendering to use GL only.
