### ISSUE TITLE
Build error with recent version of dawn

### ISSUE THREAD

**Issue by blitz-research** [ocornut/imgui#7969]
### Version/Branch of Dear ImGui:

Version 1.91.1, Branch: master

### Back-ends:

imgui_impl_wgpu.cpp

### Compiler, OS:

All

### Details:

The wgpu backend does not build with the latest versions of dawn. The error occurs on this line:

https://github.com/ocornut/imgui/blob/a8eec244056b8880f459d2073333fca4da5a917a/backends/imgui_impl_wgpu.cpp#L663

The 'false' on this line should now be 'WGPUOptionalBool_False'.

I can make a PR for this, but it'll break every one's code if they don't have the latest version of Dawn so it may not be a good idea just yet.

Bye,
Mark

**Comment by ocornut** [comment]
Fixed by 1ac162f !
