### ISSUE TITLE
Incorrect set for FontScale in the SetCurrentWindow

### ISSUE THREAD

**Issue by DDeimos** [ocornut/imgui#7976]
### Version/Branch of Dear ImGui:

Version 1.91.1, Branch: docking

### Back-ends:

any

### Compiler, OS:

Windows 11 + MSVS 2022

### Details:

I've just updated to 1.91.1 and noticed that if you resize a docked window, you won't get 3 dots after window's name. It looks like this: 
![image](https://github.com/user-attachments/assets/1a88c22e-4217-4322-94f9-3b2a701afd0b)
Further investigation showed that the problem is in the `ImGui::RenderTextEllipsis` function. It calculates ellipsis size first, and it needs new `FontScale` property. The property must be in the draw list. But when the `SetCurrentWindow` function is being called, it updates `FontSize` this way:
`g.FontSize = g.DrawListSharedData.FontSize = window->CalcFontSize();`
and the `FontScale` is being update like this:
`g.FontScale = g.FontSize / g.Font->FontSize;`
I believe the correct version should be this:
`g.FontScale = g.DrawListSharedData.FontScale = g.FontSize / g.Font->FontSize;`
I tested the fix and the problem went away.
The commit we are taking about was made on July 2 - https://github.com/ocornut/imgui/commit/0f63d3e9164de47ec5059b9e647a6581dd3c7524. I tried to find any similar issue, but I couldn't. Am I right in understanding that this is a bug and no one has noticed it yet?
P.S. Please, tell me if you need me to provide any additional info.

### Screenshots/Video:

Before https://github.com/ocornut/imgui/commit/0f63d3e9164de47ec5059b9e647a6581dd3c7524:
![image](https://github.com/user-attachments/assets/489aa7c3-537d-42d8-afbd-53fc103c3836)
After https://github.com/ocornut/imgui/commit/0f63d3e9164de47ec5059b9e647a6581dd3c7524:
![image](https://github.com/user-attachments/assets/e6c029fc-cd49-49c6-b9d4-2eb1d45ae675)

**Comment by ocornut** [comment]
You are absolutely correct, and somehow only Ellipsis rendering was effectively affected.
Pushed fix dc6346b.
Thank you!
