### ISSUE TITLE
How can I size a table correctly for a given number of rows when using ImGuiTableFlags_ScrollX?

### ISSUE THREAD

**Issue by simonvanbernem** [ocornut/imgui#7982]
### Version/Branch of Dear ImGui:

Version 1.91.1, Branch: docking

### Back-ends:

Directx9 example that comes with dear imgui

### Compiler, OS:

MSVC 22

### Full config/build information:

```
Dear ImGui 1.91.1 (19110)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1941
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx9
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**How can I properly size my table when ImGuiTableFlags_ScrollX is used?**

The screenshots below show a window where 4 tables are drawn after another. When using ImGuiTableFlags_ScrollX, the first one grows way too large and all the others get 0 vertical space. That seems very strange to me. The comment for ImGuiTableFlags_ScrollX explicitely states that outer_size should be provided in this case, because layout stuff changes, which is why I am unsure if this is a bug. In any case, I don't understand why sizing of the first table would make the other tables completly unreadable and I also don't understand why the first table becomes huge for no reasons. My expectation would be that nothing about their size changes, as horizontal scrolling is not needed in this case. And if horizontal scrolling was necessary, the table should only get as much taller as the scrollbar requires it.

My question is: If I have to specify the y size manually, how do I find appropriate values for outer_size? I could hardcode some value for y, or calculated some multiple of the number of rows, but I believe that might be tricky and I might end up with sizes slightly too large or slightly too small for the content. Is there a way to determine the exact height needed, so that no space is wasted (and the other tables remain readable), and the table doesn't need a vertical scrollbar?

### Screenshots/Video:

With ScrollX disabled, the tables are appropriately sized vertically.
![image](https://github.com/user-attachments/assets/dbfa3cfb-16d9-4fc7-b7a7-114c6e87fbf4)
With ScrollX enabled, the first table uses all the vertical space of the window.
![image](https://github.com/user-attachments/assets/c9e5c5a3-24af-4a50-bed0-62c2c27e7100)
Still with ScrollX enabled, scrolling down reveals that all the other tables are still drawn, but apparently with 0 height.
![image](https://github.com/user-attachments/assets/5adde6c9-3824-4cf7-beaf-7eef2610d5b2)

### Minimal, Complete and Verifiable Example code:

```cpp
{
    static bool ScrollX;

    if(ImGui::Begin("Test Window")){
        ImGui::Checkbox("ScrollX", &ScrollX);

        for (int it = 0; it < 4; it++){
            ImGui::PushID(it);

            if(ImGui::BeginTable("test", 2, ScrollX ? ImGuiTableFlags_ScrollX : 0)) {
                ImGui::TableSetupColumn("delete", ImGuiTableColumnFlags_WidthFixed);
                ImGui::TableSetupColumn("name", ImGuiTableColumnFlags_WidthFixed);
                ImGui::TableHeadersRow();

                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0); ImGui::Text("0");
                ImGui::TableSetColumnIndex(1); ImGui::Text("1");

                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0); ImGui::Text("0");
                ImGui::TableSetColumnIndex(1); ImGui::Text("1");

                ImGui::EndTable();
            }

            ImGui::PopID();
        }
    }

    ImGui::End();
}
```

**Comment by ocornut** [comment]
Hello Simon,

> The screenshots below show a window where 4 tables are drawn after another. When using ImGuiTableFlags_ScrollX, the first one grows way too large and all the others get 0 vertical space. That seems very strange to me. The comment for ImGuiTableFlags_ScrollX explicitely states that outer_size should be provided in this case, because layout stuff changes, which is why I am unsure if this is a bug. In any case, I don't understand why sizing of the first table would make the other tables completly unreadable and I also don't understand why the first table becomes huge for no reasons.

When enabling scrolling the table creates a child window and currently this needs to be explicitly sized.
The default outer_size in this situation means "fill all remaining space in the parent window" so the first table does that, and then there's no space for others.

Since 1.90 we introduced new flags for Child windows such as `ImGuiChildFlags_AutoResizeY`. In theory that feature could be adapted to tables in some way, but there is additional complexity in doing so and I haven't finished that work so presently it isn't possible.

> My question is: If I have to specify the y size manually, how do I find appropriate values for outer_size? I could hardcode some value for y, or calculated some multiple of the number of rows, but I believe that might be tricky and I might end up with sizes slightly too large or slightly too small for the content. Is there a way to determine the exact height needed, so that no space is wasted (and the other tables remain readable), and the table doesn't need a vertical scrollbar?

There's no great answer to that unfortunately.
Here your table would likely be `GetFrameHeight() + row_count * (GetTextLineHeight() + GetStyle().CellPadding.y * 2.0f)` high.

(Note that `ImGuiTableFlags_ScrollX` also have other side effects as it alter the default sizing behaviors of columns. It makes total sense when you dig into the reasons, but may be rather unobvious at first. e.g. Stretch columns don't make sense with _ScrollX flag. See the paragraph on top of `enum ImGuiTableFlags_` and "COLUMNS SIZING POLICIES" section of imgui_tables.cpp.)

**Comment by simonvanbernem** [comment]
Ok, I'll go with `GetFrameHeight() + row_count * (GetTextLineHeight() + GetStyle().CellPadding.y * 2.0f)` then, and see if that fits for me. It's just debug UI in my case, so small layouting issues are annoying but not real problems.

**Comment by simonvanbernem** [comment]
I tried it, changed `GetTextLineHeight()` to `GetTextLineHeight() * 1.2f` to account for the fact that I have checkboxes in my rows which seem to be a little taller than a text row. And it sort of works out. The table is a little too large, but that is not a big issue.

**Comment by ocornut** [comment]
The framed items are `GetFrameHeight()`. It is essentially `GetTextLineHeight() + style.FramePadding.y * 2.0f`.

**Comment by sodamouse** [comment]
I would like to +1 this issue.
