### ISSUE TITLE
Translating between backend keycode and ImGuiKey

### ISSUE THREAD

**Issue by rokups** [ocornut/imgui#7997]
### Version/Branch of Dear ImGui:

Version 1.91, Branch: docking

### Back-ends:

imgui_impl_sdl2.cpp

### Compiler, OS:

Not applicalbe

### Details:

My project has a hotkey system which in the past used a mix of SDL keycodes and scancodes. Dear ImGui now handles keys through `ImGuiKey` enum, which maps to SDL2 keycodes. In order to maintain ability to use scancodes for keybindings i need a way to translate SDL2 scancode to `ImGuiKey`. This can be done indirectly, by translating SDL2 scancode to SDL2 keycode, and then translating SDL2 keycode to `ImGuiKey`. `ImGui_ImplSDL2_KeyEventToImGuiKey` function does exactly this, however this function is private and static. For time being i patched SDL2 backend so it exposes this function and i can use it. It would probably be helpful to more people than me alone if there was an official way to translate between `ImGuiKey` and backend keycode.

Thanks for considering this 🙏

**Comment by ocornut** [comment]
Made that change as cfae5ac.
It'd prefer to make it an undocumented thing for now, so you would need to forward declare.
