### ISSUE TITLE
SDL2 backend does not build on UWP

### ISSUE THREAD

**Issue by rokups** [ocornut/imgui#8008]
### Version/Branch of Dear ImGui:

Version 1.91, Branch: docking

### Back-ends:

imgui_impl_sdl2.cpp

### Compiler, OS:

MSVC

### Details:

SDL2 backend uses `GetWindowLong`/`SetWindowLong`/`ShowWindow` windows API, which are not allowed with UWP and the build fails. It would make sense to disable code using these APIs on UWP. You can check presence of UWP build like so:
```c
#if defined(WINAPI_FAMILY_PARTITION)
#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP) && !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
// Is UWP
#endif
#endif
```

**Comment by ocornut** [comment]
Could you provide a PR for it? (if adequate, over docking branch with 1 commit for master 1 commit for docking if needed)
We do test for UWP here and there already so can use same syntax as whatever is already in.

**Comment by ocornut** [comment]
Pushed a fix d7cedd6

**Comment by rokups** [comment]
Sorry, i did not manage to get to this in time. Thanks for the fix :)

**Comment by ocornut** [comment]
Note that I used the same logic as main lib was using: `(defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_APP || WINAPI_FAMILY == WINAPI_FAMILY_GAMES)` which differs from your proposed version.
I am not entirely sure what the FAMILY vs FAMILY_PARTITION means at this point.
