### ISSUE TITLE
Latest Dawn source code breaks WGPU Backend.

### ISSUE THREAD

**Issue by blitz-research** [ocornut/imgui#8009]
### Version/Branch of Dear ImGui:

Version 1.91.2, Branch: master

### Back-ends:

imgui_impl_wgpu.cpp

### Compiler, OS:

NA

### Details:

The latest Dawn source code breaks the WGPU backend (again).

Strings now need to be encapsulated in a WGPUStringView which is a breaking change. The WGSL shader source descriptor's type name has changed so I've updated that too, although this isn't strictly speaking a breaking change yet.

I'll make a PR for this too using this issue number.

**Comment by ocornut** [comment]
Fixed by 7f81fbc. Thanks!
