### ISSUE TITLE
How Do i implement `imgui` to a source engine based game?

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [ocornut/imgui#8014]
### Version/Branch of Dear ImGui:

Version 1.91.2, Branch: master

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Windows 11 (MingGW) GCC

### Details:

**My Issue/Question:**
how would i implement imgui to a game made with the source engine?

**Comment by ocornut** [comment]
There's no stock backend for source so you would need to implement your own ASSUMING you can compile code that use Source Engine features (I don't even know if that's available) and if you want to use Source Engine API for the rendering/inputs:
- See imgui.cpp's "IMPLEMENTING CUSTOM BACKEND / CUSTOM ENGINE" and "HOW A SIMPLE RENDERING FUNCTION MAY LOOK LIKE" for a few references.
- And then you can refer to the 20+ existing backends for references https://github.com/ocornut/imgui/blob/master/docs/BACKENDS.md

But you can also simply use the existing backends e.g. imgui_impl_win32.cpp, imgui_impl_dx11.cpp based on whatever the engine is using on a specific platform. In that case it isn't more complicated than e.g https://github.com/ocornut/imgui/wiki/Getting-Started

If you need to hook into an external exe that you are not compiling, they are resources elsewhere but this is outside of the scope of dear imgui.

**Comment by GuestSneezeOSDev** [comment]
@ocornut thanks
