### ISSUE TITLE
My imgui has "Debug" written on the top left and I don't know how to remove it

### ISSUE THREAD

**Issue by addressnopping** [ocornut/imgui#8019]
### Version/Branch of Dear ImGui:

last, master

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Windows 10 + MSVC 22

### Details:

my imgui has "Debug" written on it

i've searched the entire project for any string with the value "Debug", but i couldn't find any

(ignore the hidden project name)

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/3b3fdf22-c5f0-4cf2-a43f-676b3662a023)

**Comment by ocornut** [comment]
The implicit Debug window appears when you call an imgui function outside of a Begin/End scope.

**Comment by addressnopping** [comment]
does ImGui::StyleColorsDark() need to be inside Begin/End scope?

**Comment by addressnopping** [comment]
there are no imgui functions outside of the scope

**Comment by ocornut** [comment]
> there are no imgui functions outside of the scope

There is. Up to you to find it in your code.

**Comment by addressnopping** [comment]
`cpp
int main(int, char**)
{
    //createDeviceD3D and create window

    ::ShowWindow(hwnd, SW_SHOWDEFAULT);
    ::UpdateWindow(hwnd);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io = ImGui::GetIO(); (void)io;

    Lexend_Medium_1 = io.Fonts->AddFontFromMemoryTTF(&Lexend_M, sizeof Lexend_M, 17.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Medium = io.Fonts->AddFontFromMemoryTTF(&Lexend_M, sizeof Lexend_M, 22.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Bold = io.Fonts->AddFontFromMemoryTTF(&Lexend_B, sizeof Lexend_B, 20.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Bold_1 = io.Fonts->AddFontFromMemoryTTF(&Lexend_B, sizeof Lexend_B, 18.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Regular = io.Fonts->AddFontFromMemoryTTF(&Lexend_R, sizeof Lexend_R, 15.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Regular_2 = io.Fonts->AddFontFromMemoryTTF(&Lexend_R, sizeof Lexend_R, 13.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Regular_1 = io.Fonts->AddFontFromMemoryTTF(&Lexend_R, sizeof Lexend_R, 18.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Semibold = io.Fonts->AddFontFromMemoryTTF(&Lexend_S, sizeof Lexend_S, 18.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Semibold_1 = io.Fonts->AddFontFromMemoryTTF(&Lexend_S, sizeof Lexend_S, 15.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Semibold_2 = io.Fonts->AddFontFromMemoryTTF(&Lexend_S, sizeof Lexend_S, 12.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    Lexend_Medium_2 = io.Fonts->AddFontFromMemoryTTF(&Lexend_M, sizeof Lexend_M, 13.f, NULL, io.Fonts->GetGlyphRangesCyrillic());

    if (image::heart == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Heart, sizeof(I_Heart), &info, pump, &image::heart, 0);

    if (image::update == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Update, sizeof(I_Update), &info, pump, &image::update, 0);

    if (image::docs == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Docs, sizeof(I_Docs), &info, pump, &image::docs, 0);

    if (image::save == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Save, sizeof(I_Save), &info, pump, &image::save, 0);

    if (image::user == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_User, sizeof(I_User), &info, pump, &image::user, 0);

    if (image::password == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Password, sizeof(I_Password), &info, pump, &image::password, 0);

    if (image::info == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Info, sizeof(I_Info), &info, pump, &image::info, 0);

    if (image::key == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Key, sizeof(I_Key), &info, pump, &image::key, 0);

    if (image::game == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Game, sizeof(I_Game), &info, pump, &image::game, 0);

    if (image::settings == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_Settings, sizeof(I_Settings), &info, pump, &image::settings, 0);

    if (image::fivem == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, FIVEM, sizeof(FIVEM), &info, pump, &image::fivem, 0);

    if (image::csgo == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, CSGO, sizeof(CSGO), &info, pump, &image::csgo, 0);

    if (image::csgo2 == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, CSGO2, sizeof(CSGO2), &info, pump, &image::csgo2, 0);

    if (image::minecraft == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, MINECRAFT, sizeof(MINECRAFT), &info, pump, &image::minecraft, 0);

    if (image::rust == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, RUST, sizeof(RUST), &info, pump, &image::rust, 0);

    if (image::gta == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, GTA, sizeof(GTA), &info, pump, &image::gta, 0);

    if (image::apex == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, APEX, sizeof(APEX), &info, pump, &image::apex, 0);

    if (image::garrys == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, GARRYS, sizeof(GARRYS), &info, pump, &image::garrys, 0);

    if (image::tf2 == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, TF2, sizeof(TF2), &info, pump, &image::tf2, 0);

    if (image::lethal == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, LETHAL, sizeof(LETHAL), &info, pump, &image::lethal, 0);

    if (image::back == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, BACK, sizeof(BACK), &info, pump, &image::back, 0);

    if (image::check == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, check_icon, sizeof(check_icon), &info, pump, &image::check, 0);

    if (image::exit == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, exit_icon, sizeof(exit_icon), &info, pump, &image::exit, 0);

    if (image::arrows == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, arrows_icon, sizeof(arrows_icon), &info, pump, &image::arrows, 0);

    if (logo == nullptr) D3DX11CreateShaderResourceViewFromMemory(g_pd3dDevice, I_logo, sizeof(I_logo), &info, pump, &logo, 0);

    ImGui::StyleColorsDark();

    ImGui_ImplWin32_Init(hwnd);
    ImGui_ImplDX11_Init(g_pd3dDevice, g_pd3dDeviceContext);

    bool show_demo_window = false;
    bool show_another_window = false;
    ImVec4 clear_color = ImVec4(0.f, 0.f, 0.f, 0.f);

    // Main loop
    bool done = false;
    while (!done)
    {
        MSG msg;
        while (::PeekMessage(&msg, NULL, 0U, 0U, PM_REMOVE))
        {
            ::TranslateMessage(&msg);
            ::DispatchMessage(&msg);
            if (msg.message == WM_QUIT)
                done = true;
        }
        if (done)
            break;

        ImGuiContext& g = *GImGui;
        const ImGuiStyle& style = g.Style;
        CustomStyleColor();

        ImGui::GetStyle().ItemSpacing = ImVec2(0, 10);

        ImGui_ImplDX11_NewFrame();
        ImGui_ImplWin32_NewFrame();
        ImGui::NewFrame();
        {
            ImGui::SetNextWindowSize(window_size);
            ImGui::SetNextWindowPos({ 0, 0 });

            ImGui::Begin("General", nullptr, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoMove);
            {
               //code
               
                ImGui::PopStyleVar();

            }ImGui::End();
        }

        ImGui::Render();
        const float clear_color_with_alpha[4] = { clear_color.x * clear_color.w, clear_color.y * clear_color.w, clear_color.z * clear_color.w, clear_color.w };
        g_pd3dDeviceContext->OMSetRenderTargets(1, &g_mainRenderTargetView, NULL);
        g_pd3dDeviceContext->ClearRenderTargetView(g_mainRenderTargetView, clear_color_with_alpha);
        ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());

        g_pSwapChain->Present(1, 0);

    }

    // Cleanup
    ImGui_ImplDX11_Shutdown();
    ImGui_ImplWin32_Shutdown();
    ImGui::DestroyContext();

    CleanupDeviceD3D();
    ::DestroyWindow(hwnd);
    ::UnregisterClassW(wc.lpszClassName, wc.hInstance);

    return 0;
}`

**Comment by addressnopping** [comment]
the entire imgui code is inside
 ```cpp
ImGui::Begin("General", nullptr, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoBringToFrontOnFocus | ImGuiWindowFlags_NoMove);
            {
               //code
               
                ImGui::PopStyleVar();

            }ImGui::End();
```

**Comment by ocornut** [comment]
What’s in CustomStyleColor() ?

The code you posted should crash/assert because there is an extra PopStyleVar(), and window_size doesn’t exist. meaning maybe you haven’t verified that this exact code doesn’t exhibit the issue.

**Comment by GamingMinds-DanielC** [comment]
> i've searched the entire project for any string with the value "Debug", but i couldn't find any

That exact string exists multiple times in source code comments, including in `imgui.cpp` at the end of `ImGui::NewFrame()` just before opening the fallback window with the title `"Debug##Default"`.

Since the fallback window is visible, there must be some call in your code outside of a `Begin()`/`End()` pair that requires an open window. Either that or you are making calls requiring a window after a `Begin()` that returned false.

**Comment by ocornut** [comment]
I'll close this as answered. You'll eventually find where in your code (in a section that you omitted to share) you are calling ImGui code that needs a window.
