### ISSUE TITLE
Assert when rendering large amount of text (overflow with 16-bits ImDrawIdx)

### ISSUE THREAD

**Issue by emoon** [ocornut/imgui#803]
Related twitter thread (a bit down into it) https://twitter.com/daniel_collin/status/758231662006239232 Also original issue here https://github.com/emoon/ProDBG/issues/270

And the assert is

```
((int64_t)draw_list->_VtxCurrentIdx <= ((int64_t)1L << (sizeof(ImDrawIdx)*8))), function AddDrawListToRenderList, file /Users/danielcollin/code/prodbg/src/native/external/imgui/imgui.cpp, line 2354.
```

I haven't looked into fixing this as suggested in the twitter thread but if someone wants to take a look it would be very appreciated!

**Comment by ocornut** [comment]
(Nothing new for you but making a generic answer for anyone else interested)

So, as stated in the thread for now you can use 32-bit indices, and you might perhaps want to toggle 16-bit/32-bit indices based on platforms.

Temporary workaround is to create dummy child windows, still requires a bit of juggling on your side.

I assume what you would want is an automatic or semi-automatic way to use more than one ImDrawList per window (aka multiple vertex buffers). I'll look into that eventually but being such a uniquely requested and rarely tested need I'll try to keep it simple to avoid further issues.

**Comment by ocornut** [comment]
Closing this old topic. By the way, the assert comments have since been modified to prioritize suggesting the suggest to switch to 32-bit indices, and that suggestion/info has also been added to `imconfig.h`.
