### ISSUE TITLE
Multiple ID Error on Button Behavior

### ISSUE THREAD

**Issue by Zaryob** [ocornut/imgui#8030]
### Version/Branch of Dear ImGui:

Branch: docking, Commit: 793773209bb0fdeb8ccb756052e770457193c9f2

### Back-ends:

imgui_impl_opengl3.cpp

### Compiler, OS:

macOS + Clang 12, GCC, Windows + MSVC

### Details:

**My Issue/Question:**

Hi,

I was getting the click behavior using two ButtonBehavior(), one left click (with ImGuiButtonFlags_MouseButtonLeft flag) and one right click (with ImGuiButtonFlags_MouseButtonRight flag). 

```cpp
bool mouseClicked = ImGui::ButtonBehavior(ImRect(fftAreaMin, wfMax), GetID("WaterfallID"), &mouseHovered, &mouseHeld,
                                                  ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_PressedOnClick);

        bool mouseRClicked = ImGui::ButtonBehavior(ImRect(fftAreaMin, wfMax), GetID("WaterfallID"), &mouseHovered, &mouseHeld,
                                                  ImGuiButtonFlags_MouseButtonRight | ImGuiButtonFlags_PressedOnClick);

```

However, I get the following image with the io.ConfigDebugDetectIdConflicts added since commit number d1ea03b872c1de31ab4c0167cf959dffe947cbeb.
<img width="1218" alt="Screenshot 2024-09-30 at 20 31 12" src="https://github.com/user-attachments/assets/baa7bde4-7f89-416c-ba5f-560480d0e599">

Here I have a basic situation and two questions.

I think the io.ConfigDebugDetectIdConflicts parameter is not implemented because it is still in development. Therefore I cannot close this error ("Unless I patch it manually"). Will it be added???

Secondly, I use two ButtonBehaviour's to achieve this behavior. I tried different ways:
* When I assigned different IDs with GetID, right click did not work
* I defined left click and right click simultaneously and then used IsMouseClicked to detect whether it is right or left, but it did not work)

So, how can I encourage with this issue?

### Minimal, Complete and Verifiable Example code:

It is fork of SDRPlusPlus of AlexandreRouma, 

Code is on [https://github.com/Zaryob/SDRPlusPlus](https://github.com/Zaryob/SDRPlusPlus/blob/dc3e474507bd14e71a1f77b96d2296bbb5a9cc3a/core/src/gui/widgets/waterfall.cpp#L263C2-L266C20)

**Comment by ocornut** [comment]
> bool mouseClicked = ImGui::ButtonBehavior(ImRect(fftAreaMin, wfMax), GetID("WaterfallID"), &mouseHovered, &mouseHeld,
ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_PressedOnClick);
> bool mouseRClicked = ImGui::ButtonBehavior(ImRect(fftAreaMin, wfMax), GetID("WaterfallID"), &mouseHovered, &mouseHeld,
ImGuiButtonFlags_MouseButtonRight | ImGuiButtonFlags_PressedOnClick);

That's an interesting use case. I think it this specific case indeed did work before (even if it should be illegal).
I will investigate this.

I think you can use single button with both `ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_MouseButtonRight` and then checking which mouse button was clicked or released? This should work.

**Comment by ocornut** [comment]
You can surround this block of code with:

```cpp
PushItemFlag(ImGuiItemFlags_AllowDuplicateId, true);
ButtonBehavior(...)
ButtonBehavior(...)
PopItemFlag();
```

**Comment by Zaryob** [comment]
> > bool mouseClicked = ImGui::ButtonBehavior(ImRect(fftAreaMin, wfMax), GetID("WaterfallID"), &mouseHovered, &mouseHeld,
> > ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_PressedOnClick);
> > bool mouseRClicked = ImGui::ButtonBehavior(ImRect(fftAreaMin, wfMax), GetID("WaterfallID"), &mouseHovered, &mouseHeld,
> > ImGuiButtonFlags_MouseButtonRight | ImGuiButtonFlags_PressedOnClick);
> 
> That's an interesting use case. I think it this specific case indeed did work before (even if it should be illegal). I will investigate this.
> 
> I think you can use single button with both `ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_MouseButtonRight` and then checking which mouse button was clicked or released? This should work.

It legally fixed like this:

```
bool mouseClicked = ImGui::ButtonBehavior(ImRect(fftAreaMin, wfMax), GetID("WaterfallID"), &mouseHovered, &mouseHeld,
                                                  ImGuiButtonFlags_MouseButtonLeft | ImGuiButtonFlags_MouseButtonRight | ImGuiButtonFlags_PressedOnClick);
```

It gathers if mouseClicked and then;

``
if (mouseClicked && !targetFound) {

    if (IsMouseClicked(ImGuiMouseButton_Right)) {
          ......
    }  
    else {
          ......
    }
}
```

It solved my problem but if you consider to investigate, Issue can be open remain.

**Comment by ocornut** [comment]
I have investigated this and deemed that it was a legit case where a false positive would be emitted.
I have pushed various references to it in 3d399bc
