### ISSUE TITLE
Custom ToolTip for BeginTabItem

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#8035]
### Version/Branch of Dear ImGui:

Version 1.91.2 docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl.cpp

### Compiler, OS:

windows 10 mingw-w64

### Details:

**My Issue/Question:**

I need a custom Tooltip behaviour for TabItems.
Tabs get label from v.shrt_name but when hovering should show long file_name. This is the code.

```Lua
    if (ig.BeginTabBar("##Tabs", ig.lib.ImGuiTabBarFlags_NoTooltip)) then
        if (ig.BeginTabItem(v.shrt_name.."##"..i, nil,(i==new_doc) and ig.lib.ImGuiTabItemFlags_SetSelected or 0)) then
            if ig.IsItemHovered() then ig.SetTooltip(v.file_name) end
            if new_doc == i then new_doc = -1 end
            curr_opendoc = i
            v:Render()
            ig.EndTabItem();
        end
        ig.EndTabBar();
    end
```
The problem is that `  if ig.IsItemHovered() then ig.SetTooltip(v.file_name) end` does not get called unless the tab is selected.
How should I solve it?

**Comment by ocornut** [comment]
> The problem is that   if ig.IsItemHovered() then ig.SetTooltip(v.file_name) end does not get called unless the tab is selected.
How should I solve it?

Call it even when the tab is not selected?

```
bool open = BeginTabItem(...);
SetItemTooltip("your tooltip");
if (open)
{
   ..
   EndTabItem();
}
```

**Comment by sonoro1234** [comment]
So obvious, Thanks!!
