### ISSUE TITLE
drawlist’s addtext Method When Handling Multibyte Encoded Strings

### ISSUE THREAD

**Issue by muchenspace** [ocornut/imgui#8042]
### Version/Branch of Dear ImGui:

Version 1.9.0, docking

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_win32.cpp

### Compiler, OS:

win11+msvc2022

### Details:

I have encountered an issue when using the drawlist’s addtext method.  If the argument passed to the text_begin parameter is a multibyte encoded string, it is still processed internally as a single-byte encoded string.  I am unsure whether this is a problem with my project or an issue with ImGui.  Could you please provide some clarification?  Thank you！

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Every string processed by dear imgui are utf-8.
Refer to https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#about-utf-8-encoding

You are making ambiguous statements without providing details.

**Comment by ocornut** [comment]
Could you clarify your issue with actual code or details?

**Comment by muchenspace** [comment]
> 您能否通过实际代码或详细信息澄清您的问题？

This doesn't seem to be an issue with imgui，I passed in a non-UTF8 string by mistake，im so sorry

**Comment by ocornut** [comment]
No worries! Glad it works for you.

(I hope in a few months we will be able to push work on better font atlas system, which will facilitate using chinese language without loading too many glyphs)
