### ISSUE TITLE
Differences in scale between glfw and sdl2

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#8044]
### Version/Branch of Dear ImGui:

Version 1.91.3, Branch: docking

### Back-ends:

imgui_impl_glfw.cpp (or imgui_impl_sdl2.cpp) + imgui_impl_opengl3.cpp

### Compiler, OS:

windows 10 mingw-w64

### Details:

**My Issue/Question:**

The scaling of gui elements and font is different between glfw+opengl3 and sdl2+opengl3.
It is strange because both of them use the default font and ScaleAllSizes is never called.
The reported dpi is also different.
Docking is enabled and viewports disabled.
Is this expected?

### Screenshots/Video:
glfw above and sdl2 below

![dpi](https://github.com/user-attachments/assets/b5cdb9da-1e66-4da2-932b-7c9c1236718c)

**Comment by ocornut** [comment]
The one above is DPI aware and the one below is not. When the process is not marked DPI aware, Windows applies scaling to framebuffer and coordinates fed to the application.

In SDL2 creating windows with `SDL_WINDOW_ALLOW_HIGHDPI` should make it DPI aware.
In Windows generally you can do it via app manifest or by calling `SetThreadDpiAwarenessContext()` on Windows 10+ and `SetProcessDpiAwareness()` on Windows 8.1+. See our helper function `ImGui_ImplWin32_EnableDpiAwareness()` in win32 backend:
https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_win32.cpp#L823
(we implemented it this way with dynamic load and no header so it can work on all systems/SDK, but with Windows 10 SDK you can call `SetThreadDpiAwarenessContext()` directly).

**Comment by sonoro1234** [comment]
After using `SetThreadDpiAwarenessContext()` at the begining of SDL program I get the correct DpiScale but mouse behaviour has an offset:

![dpi_sdl](https://github.com/user-attachments/assets/fb50e7d5-8273-4a5f-a37e-96e1cb0e7d70)

**Comment by ocornut** [comment]
Does it works better with `SDL_WINDOW_ALLOW_HIGHDPI` ?

> this only happens in 32bit but not in 64bit!!!

This could be a build issue (mismatching SDL version between 32 and 64 bits),
Or, Windows store custom override settings for each .exe
![image](https://github.com/user-attachments/assets/29cca422-6ae0-4a11-9da8-69f0046cf7b1)

It happens that when you experiment with something Windows decide to change some settings and remembers them.

**Comment by sonoro1234** [comment]
> Does it works better with `SDL_WINDOW_ALLOW_HIGHDPI`

It was already

> This could be a build issue (mismatching SDL version between 32 and 64 bits),

I dont think so because it is a script and the exe is always LuaJIT

I have implemented SDL3 with LuaJIT-ImGui and it is dpi aware!!
