### ISSUE TITLE
Regression in synced table default column size

### ISSUE THREAD

**Issue by mattftw** [ocornut/imgui#8045]
### Version/Branch of Dear ImGui:

1.91.3

### Back-ends:

example_win32_directx9

### Compiler, OS:

Windows 10 + MSVC2022

### Full config/build information:

```
Dear ImGui 1.91.3 (19130)
--------------------------------
sizeof(size_t): 4, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _MSC_VER=1938
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx9
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

There seems to be a regression with the loading of synced instances.
Somewhere between 1.89.2 and 1.91.3 the columns went from defaulting to an appropriate size, to defaulting to extremely small.

See attached images.

### Screenshots/Video:

**1.89.2** notice how "synced instances" tables have loaded with sensible widths
![1 89 2](https://github.com/user-attachments/assets/f5e232d4-1034-425f-bfb6-9e08f0dcb388)

**1.91.3** notice how "synced instances" columns have loaded extremely thin
![1 91 3](https://github.com/user-attachments/assets/3c35c9e9-8ad4-4671-afe0-fa5389a7c205)

### Minimal, Complete and Verifiable Example code:

use example_win32_directx9 example solution.

**Comment by mattftw** [comment]
The bug seems to have bee introduced in this commit
https://github.com/ocornut/imgui/commit/e648dbb59d24c29a2e2ac964777822e96befd808

**Comment by ocornut** [comment]
Thank you for your report. I believe f3d242a should fix this now.
