### ISSUE TITLE
App crash after ImGui::Image

### ISSUE THREAD

**Issue by ruslan180912344** [ocornut/imgui#805]
i adding 
`ImGui::Image("rage.png", ImVec2(64, 64));`
to my code and after this my app crashes,what i am doing wrong,and where rage.png need to locate? In directory witch app or in resources files?

**Comment by Flix01** [comment]
Well, in short, ImGui::Image(...) needs a ImGui-agnostic texture id as argument, not a path to an image.

ImGui can't decode images for you. You should do it yourself (for example using **stb_image**).
Then form the image pixels you should create a texture id or a texture class (usually using OpenGL or Direct3D) and pass it to ImGui::Image(...).

**Comment by ocornut** [comment]
The parameter is ImTextureId which is essentially a `void*`, aka enough to store a pointer or an integer value to identify a texture in your own rendering subsystem. The value is passed unmodified to your renderer and its content is totally up to you. The example renderers in the examples/ folder each describe in their comment how they treat that type (e.g the example OpenGL renderer use that type to store an OpenGL gluint texture identifier).

Depending on the rendered you use you'll need to pass on the appropriate data to the Image() function.
