### ISSUE TITLE
ImGui in C++ style(class/interface)

### ISSUE THREAD

**Issue by abramann** [ocornut/imgui#8050]
Has someone done ImGui in C++ style(interfaces/classes) in an opensource project?

**Comment by ocornut** [comment]
It doesn't make much sense as the library follows a functional design.

However, specifically on the matter or RAII helpers to deal with begin/end push/pop there are a few things:
- https://github.com/ocornut/imgui/wiki/Useful-Extensions#cness
- #2096
- #2197

I may put some work at implementing an official RAII solution for people who want it. #2197 is a good contender.
