### ISSUE TITLE
Crash when obtaining multiple fonts

### ISSUE THREAD

**Issue by LItterBoy-GB** [ocornut/imgui#8052]
### Version/Branch of Dear ImGui:

1.91.3

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx12.cpp

### Compiler, OS:

Windows11 + VS2022

### Full config/build information:

include source code

### Details:

**My Issue/Question:**

I want the text to be bigger, but there was a problem when I changed the font size.

### Screenshots/Video:

D3D12 ERROR: ID3D12Device::CreateCommittedResource: D3D12_RESOURCE_DESC::Width, D3D12_RESOURCE_DESC::Height, and/ or D3D12_RESOURCE_DESC::DepthOrArraySize are too large for the D3D12_RESOURCE_DESC::Dimension and FeatureLevel. Width = 4096 and must be <= 16384, Height = 32768 and must be <= 16384, DepthOrArraySize = 1 and must be <= 2048, Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D, and FeatureLevel = D3D_FEATURE_LEVEL_12_1. [ STATE_CREATION ERROR #597: CREATERESOURCE_INVALIDDIMENSIONS]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR STATE_CREATION #597: CREATERESOURCE_INVALIDDIMENSIONS ]
0x00007FFF36F3FE4C (KernelBase.dll)处(位于 ImGuiDemo.exe 中)引发的异常: 0x0000087A (参数: 0x0000000000000001, 0x000000BF780FAE40, 0x000000BF780FCC10)。
0x00007FFF36F3FE4C (KernelBase.dll) (ImGuiDemo.exe 中)处有未经处理的异常: 0x0000087A (参数: 0x0000000000000001, 0x000000BF780FAE40, 0x000000BF780FCC10)。

![image](https://github.com/user-attachments/assets/b30c3849-749e-4de6-a0c6-0f82daa1215b)

![image](https://github.com/user-attachments/assets/12623dcd-0403-4d4c-9979-c24ebc956eeb)

### Minimal, Complete and Verifiable Example code:

use  https://github.com/ocornut/imgui/blob/master/examples/example_win32_directx12/main.cpp
```cpp
 // Setup Platform/Renderer backends
 ImGui_ImplWin32_Init(hwnd);
 ImGui_ImplDX12_Init(g_pd3dDevice, NUM_FRAMES_IN_FLIGHT,
     DXGI_FORMAT_R8G8B8A8_UNORM, g_pd3dSrvDescHeap,
     g_pd3dSrvDescHeap->GetCPUDescriptorHandleForHeapStart(),
     g_pd3dSrvDescHeap->GetGPUDescriptorHandleForHeapStart());

// add font
ImFont* font1 = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\msyh.ttc", 10.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());
ImFont* font2 = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\msyh.ttc", 16.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());
ImFont* font3 = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\msyh.ttc", 20.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());
ImFont* font4 = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\msyh.ttc", 30.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());
ImFont *font5 = io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\msyh.ttc", 40.0f, nullptr, io.Fonts->GetGlyphRangesChineseFull());

```

**Comment by GamingMinds-DanielC** [comment]
You are specifying a huge range of glyphs combined with a considerable size, as a result your texture gets too big to handle. That's a known limitation of the current font system. Until a new one solves this, you need to reduce the size or the number of glyphs, see here for details:
https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#troubleshooting

**Comment by ocornut** [comment]
You can also see OversamplingH=1 for the larger sizes to save on space.
