### ISSUE TITLE
(Question) Black Box Issue

### ISSUE THREAD

**Issue by GamebP** [ocornut/imgui#8056]
### Version/Branch of Dear ImGui:

Version 1.91.3 WIP, Branch: Docking

### Back-ends:

imgui_impl_dx9 + imgui_impl_win32.cpp

### Compiler, OS:

Windows 10 + Visual Studio 2022 (v143)

### Details:

**My Issue/Question:**
My current X problem is, that I have `CreateWindowExA` with `CreateDevice`, `CreateImGui`.  
And then it creates a rendered from D3D9, then loads the ImGui, then calls EndFrame.  
But at the end I need to call... to make it not crash since I want to use [ImGuiNotify](https://github.com/TyomaVader/ImGuiNotify/tree/Dev) to display some data at bottom left corner.  
```
if (ImGui::GetIO().ConfigFlags & ImGuiConfigFlags_ViewportsEnable) 
{
    ImGui::UpdatePlatformWindows();
    ImGui::RenderPlatformWindowsDefault();
}
```
  
I just want it to not create a black box when doing CreateHWindow (for short CreateWindowExA from (winuser.h)).  
It is CreateHWindow issue but can't get rid of it.  
So my Y solution could be getting rid of the Black box but at the same time I am able to see Notifications at bottom left corner. Like I Need to move the imgui menu that has the alot of data not stay at the same place.   
Removing black box -> fixes the movment for (main window) and removes (yeap!) child from the main Generator.exe 

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/2ecfe252-cc83-4259-a556-656a634d2e43)
![image](https://github.com/user-attachments/assets/f51102d7-8377-4338-ae31-2b9b3ae9e614)
![image](https://github.com/user-attachments/assets/6bcfc5ef-bfc7-46a6-a3fc-7d8d62f1e5e7)

### Minimal, Complete and Verifiable Example code:

[BlackBoxImgui.zip](https://github.com/user-attachments/files/17355320/BlackBoxImgui.zip)

**Comment by ocornut** [comment]
Question seems to have nothing to do with dear imgui.
Sorry but #1586
