### ISSUE TITLE
Problem with SliderFloat3

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#806]
I have a method in a Transform class that gets the current position of a model :

inline glm::vec3* GetPosition() { return &position; }

Which I would usually use in the relevant main loop to change the model’s x position using. For example:
Transform transform;
transform.GetPosition()->x = 2.0f;

I’m building a separate GUI class for the controls and want to link this method to a SliderFloat3 so I can control the object dynamically. I’ve tried in the GUI.cpp:
Transform* txyz;
ImGui::SliderFloat3("Position", (float*)txyz->GetPosition(), -4.0f, 4.0f);

But it keeps crashing and not sure what I’m doing here! 
Error: Access violation reading location 0x00000000.

Do I need to write a GetTransform() method in the Transform class to use in the SliderFloat3, say:
ImGui::SliderFloat3("Position", txyz->GetTransform()->GetPosition(), -4.0f, 4.0f);
??? If so, how would that look?

**Comment by Flix01** [comment]
I would try something like:
```c++
ImGui::SliderFloat3("Position", &(txyz->GetPosition()->x), -4.0f, 4.0f);
// or:
ImGui::SliderFloat3("Position", glm::value_ptr(*txyz->GetPosition()), -4.0f, 4.0f);
```
Does it work ?

**Comment by djones4487169** [comment]
Both of them are error free code-wise but I'm still getting crash when trying to use the SliderFloat3 in the app with an access violation??

**Comment by ocornut** [comment]
You aren't specifying where is the crash.

**Comment by djones4487169** [comment]
The crash happens when I try to open the 'Transform' node in the GUI when the app is running:

if (ImGui::TreeNode("Transform"))
{
	//ImGui::SliderFloat3("Position", (float*)txyz->GetPosition(), -4.0f, 4.0f);
	//ImGui::SliderFloat3("Position", &(txyz->GetPosition()->x), -4.0f, 4.0f);
	ImGui::SliderFloat3("Position", glm::value_ptr(*txyz->GetPosition()), -4.0f, 4.0f);
	ImGui::TreePop();
}

**Comment by ocornut** [comment]
That's not saying where the crash happens.

**Comment by emoon** [comment]
@djones4487169 Please provide a callstack. Otherwise it's impossible to see where it crashes.

**Comment by MKUltra42** [comment]
Dumb question, but txyz is non-null and pointing at valid memory?

**Comment by ocornut** [comment]
Realistically speaking, this function is likeg to have no bug that would affect you. It only requires you to pass a pointer to 3 contiguous float (12 bytes). I guess it must be what those glm functions are providing you with but not knowing about how glm works we can't say for sure.

I recall someone having a similar problem a few months ago, maybe search for "glm" here.

**Comment by djones4487169** [comment]
I will search for any other issues with GLM.

BTW, how do I get the callstack in a state to show you? This could be useful to know!

**Comment by emoon** [comment]
Easiest is to use a debugger and copy'n'paste it from there.

**Comment by emoon** [comment]
Also you seems to have a similar issue here https://github.com/ocornut/imgui/issues/779 is `glm::vec3` doubles? then this won't work correctly. in that case you can likely do something like

```C++
float temp[3] = { (float)txyz->GetPosition()->x, (float)txyz->GetPosition()->y, (float)txyz->GetPosition()->z };
ImGui::SliderFloat3("Position", &temp, -4.0f, 4.0f);
// write back temp to txyy here
```

**Comment by paulsapps** [comment]
@emoon funny since this is the same guy ;)

**Comment by emoon** [comment]
Yeah just my point

**Comment by djones4487169** [comment]
I got the other issue working OK which is why I don't understand why this wont work the same way?
I've used your code snippet and I'm getting:

Transform* txyz;
float temp[3] = { (float)txyz->GetPosition()->x, (float)txyz->GetPosition()->y, (float)txyz->GetPosition()->z };
ImGui::SliderFloat3("Position", (float*)temp, -4.0f, 4.0f);

returned null ptr error on the temp[3] array?

**Comment by Flix01** [comment]
> returned null ptr error on the temp[3] array?

You mean on the line:
```c++
float temp[3] = { (float)txyz->GetPosition()->x, (float)txyz->GetPosition()->y, (float)txyz->GetPosition()->z };
```
?

That seems to indicate that ImGui::SliderFloat3(...) is not to blame...
You should show us the code of the GetPosition() method, or of the Transform class.

@emoon was right: a callstack makes fixing errors MUCH easier.

**Comment by ocornut** [comment]
Either txyz is NULL either GetPosition() returns NULL.
Either way it is a problem with your code and/or your usage of GLM but not ImGui.

I have to close this but feel free to post when you find your issue!

**Comment by paulsapps** [comment]
```
float temp[3] = { (float)txyz->GetPosition()->x, (float)txyz->GetPosition()->y, (float)txyz->GetPosition()->z };
ImGui::SliderFloat3("Position", (float*)temp, -4.0f, 4.0f);
```

I'm pretty sure that should be (float*)&temp

**Comment by Flix01** [comment]
@paulsapps wrote:
> I'm pretty sure that should be (float*)&temp

The signature in imgui.h is:
```c++
IMGUI_API bool          SliderFloat3(const char* label, float v[3], float v_min, float v_max, const char* display_format = "%.3f", float power = 1.0f);
```
AFAIK, float v[3] can be passed through *temp* or *&temp[0]*.
Shouldn't **&temp** be a (float**) ?
