### ISSUE TITLE
OpenPopupOnItemClick() doesn't work with SameLine()

### ISSUE THREAD

**Issue by pajero-atr** [ocornut/imgui#8067]
### Version/Branch of Dear ImGui:

original v1.91.4 WIP

### Compiler, OS:

Win10, VSC++ 2022

### Details:

fragment of the file "imgui_demo.cpp" with the entered TEST, shown below

### Minimal, Complete and Verifiable Example code:

// Example 2
// Popup on a Text() element which doesn't have an identifier: we need to provide an identifier to BeginPopupContextItem().
// Using an explicit identifier is also convenient if you want to activate the popups from different locations.
{
    HelpMarker("Text() elements don't have stable identifiers so we need to provide one.");
    static float value = 0.5f;
    ImGui::Text("Value = %.3f <-- (1) right-click this text", value);

            ImGui::Text("! NOT CLICK :( ");    //TEST
            ImGui::SameLine();
            ImGui::Text("! CLICK :)");

    if (ImGui::BeginPopupContextItem("my popup"))
    {
        if (ImGui::Selectable("Set to zero")) value = 0.0f;
        if (ImGui::Selectable("Set to PI")) value = 3.1415f;
        ImGui::SetNextItemWidth(-FLT_MIN);
        ImGui::DragFloat("##Value", &value, 0.1f, 0.0f, 0.0f);
        ImGui::EndPopup();
    }

    // We can also use OpenPopupOnItemClick() to toggle the visibility of a given popup.
    // Here we make it that right-clicking this other text element opens the same popup as above.
    // The popup itself will be submitted by the code above.
    ImGui::Text("(2) Or right-click this text");
    ImGui::OpenPopupOnItemClick("my popup", ImGuiPopupFlags_MouseButtonRight);

    // Back to square one: manually open the same popup.
    if (ImGui::Button("(3) Or click this button"))
        ImGui::OpenPopup("my popup");
}

**Comment by ocornut** [comment]
I don't understand your problem or question. Please clarify.
If I test your code, the popup works perfectly when you right click on "! CLICK :)" which is the item it applies to.

**Comment by pajero-atr** [comment]
The popup doesn't work if I click on the text "Not Click"

It doesn't work on any ImGui::Text() that comes before ImGui::SameLine()

**Comment by GamingMinds-DanielC** [comment]
It doesn't work if you click on another item than the last item because these functions are intended to work on the single last item only. If you have two calls to `Text()`, that are two items, they don't get merged into a singular last item. `SameLine()` has nothing to do with it.

**Comment by pajero-atr** [comment]
Ok. I assumed it was possible. OpenPopupOnItemClick() works on multiple lines. It doesn't work if I use SameLine() to split different ImGui::Text()

Thanks for your help

**Comment by GamingMinds-DanielC** [comment]
You could try packing multiple items into a group (`BeginGroup()` / `EndGroup()`) and test if checking right after closing the group gives the desired effect if the group acts as a single item.
