### ISSUE TITLE
Cannot specify ImGuiWindowFlags_AlwaysAutoResize for BeginChild()

### ISSUE THREAD

**Issue by hinxx** [ocornut/imgui#8072]
### Version/Branch of Dear ImGui:

1.91.3

### Back-ends:

imgui_impl_opengl3.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Linux + gcc

### Full config/build information:

```
Dear ImGui 1.91.3 (19130)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=11
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

This is not with my code, I'm trying to get the `ImGuiFileBrowser` addon running found here https://github.com/gallickgunner/ImGui-Addons.

The `ImGui::BeginChildEx()` does this check:

```
IM_ASSERT((window_flags & ImGuiWindowFlags_AlwaysAutoResize) == 0 && "Cannot specify ImGuiWindowFlags_AlwaysAutoResize for BeginChild(). Use ImGuiChildFlags_AlwaysAutoResize!");
```

and even if I do what is requested by changing the `ImGuiFileBrowser` code:

```
ImGui::BeginChild("##NavigationWindow", nw_size, true, ImGuiChildFlags_AlwaysAutoResize | ImGuiWindowFlags_NoScrollbar);
```

assert still hits.

I guess it is due to both enums having the same vallue:

```
ImGuiChildFlags_AlwaysAutoResize        = 1 << 6,

ImGuiWindowFlags_AlwaysAutoResize       = 1 << 6,
```

If I comment out the `IM_ASSERT` line the code runs as expected.

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue

#include "ImGuiFileBrowser.h"

imgui_addons::ImGuiFileBrowser file_dialog; // As a class member or globally

ImGui::Begin("Example Bug");

if (ImGui::Button("Load")) {
    ImGui::OpenPopup("Open File");
}
if (file_dialog.showFileDialog("Open File", imgui_addons::ImGuiFileBrowser::DialogMode::OPEN, ImVec2(700, 310), ".rar,.zip,.7z")) {
}

ImGui::End();
```

**Comment by ocornut** [comment]
You are not passing the child flags in the right parameter:

ImGui::BeginChild("##NavigationWindow", nw_size, true, ImGuiChildFlags_AlwaysAutoResize | ImGuiWindowFlags_NoScrollbar);

Mixing child flags and window flags.

The “true” here is the child flag. True is ImGuiChildFlags_Borders.
Before we introduced child flags this was a boolean so it is “normal” to see a bool here in legacy code.

So it should be:

ImGui::BeginChild("##NavigationWindow", nw_size, ImGuiChildFlags_Borders | ImGuiChildFlags_AlwaysAutoResize, ImGuiWindowFlags_NoScrollbar);

In doubt about something always search in the codebase for use of a flag and see how it is used :)

**Comment by hinxx** [comment]
Thanks for explaining. Will try to do more research next time :)
