### ISSUE TITLE
ImGuiConfigFlags_NavEnableGamepad can cause enormous slowdown when application first starts

### ISSUE THREAD

**Issue by hatfield-c** [ocornut/imgui#8075]
### Version/Branch of Dear ImGui:

Version 1.91.3, Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_vulkan.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Full config/build information:

```
Dear ImGui 1.91.3 WIP (19121)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1941
define: _MSVC_LANG=202002
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_vulkan
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

I have had an intermittent issue for a few weeks now where Dear ImGUI will show a blank window for 30 seconds or more, when typically the window can otherwise show up in less than a second. Once the 30 seconds has passed and the window successfully renders for the first time these problems disappear. This seems to be more frequent when I accidentally cause the program to crash during other development activities, and starting today the issue is now constant and unceasing. Previously a computer restart could fix the error, but not anymore.

After some digging, I traced the problem to the function _ImGui_ImplGlfw_UpdateGamepads()_ inside the file _imgui_impl_glfw.cpp_ at line 784, which contains the following line of code: _if (!glfwGetGamepadState(GLFW_JOYSTICK_1, &gamepad))_ If I place a _return;_ statement before this line of code, the application window renders just fine without issue. 

I believe the issue is related to how glfw does input polling for gampads. I tried calling _glfwJoystickPresent(GLFW_JOYSTICK_1)_ as a test, and it also causes the same 30 second delay that happens with _glfwGetGamepadState(GLFW_JOYSTICK_1, &gamepad)_

After the 30 second start up time and the first successful render, _ImGui_ImplGlfw_UpdateGamepads()_ can be called every frame without issue or slowdown (I'm getting 170 fps right now).

The issue can be avoided by ensuring you do not add the ImGuiConfigFlags_NavEnableGamepad flag to the io->ConfigFlag variable. While I am mainly submitting this issue for the benefit of others facing this bug, I do feel further investigation is warranted. This extra io config flag is included by default in a lot of tutorials. Furthermore, adding this flag should not result in such a dramatic slowdown. Ideally ImGUI should take action to prevent this error from occurring.

I have tried connecting a gamepad (Xbox One controller via bluetooth) and then running the application. The issue persists regardless of whether or not a gamepad is present. 

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/be8b3e25-ddb2-490c-b53b-a41aaacdc3e0)

### Minimal, Complete and Verifiable Example code:

```cpp
IMGUI_CHECKVERSION();
ImGui::CreateContext();

ImGuiIO* io = &(ImGui::GetIO());
this->io = io;
this->io->ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
this->io->ConfigFlags |= ImGuiConfigFlags_NavEnableGamepad;
```

**Comment by hatfield-c** [comment]
Previously I've (sometimes) been able to get the error to trigger by clicking the "Stop Debugging" button (the red square) in Visual Studio Community 2022. The next time I compile and run the code in Debug mode for x64, the issue will (sometimes) start. I had a hard time getting this behavior to reliably work, and now that the issue is permanent for me now I have no way of re-testing this.

![image](https://github.com/user-attachments/assets/b09b3359-5c16-4e23-8aa6-bbbc76bee3db)

**Comment by ocornut** [comment]
Well as you pointed out this seems like an issue with GLFW, not with Dear ImGui. Have you tried updating GLFW? Otherwise perhaps report the issue there.

**Comment by Smiley98** [comment]
I also encountered this error today and can confirm it stems from glfw rather than imgui. In fact, its due to a bug in xinput rather than glfw itself (other backends such as sdl use different windows APIs to handle gamepads)!

As for how to move forward, I suppose it depends on the frequency of people facing this issue, which doesn't seem to be too many. It seems like this is a known bug, yet people haven't taken any steps to fix it.

Given the low frequency of this bug, and the ability to side-step it by either removing gamepad support, or switching to a different backend, its probably not worth removing default gamepad support from imgui io configuration.

**Comment by ocornut** [comment]
> its due to a bug in xinput rather than glfw itself 

What makes you think that?

The Win32 backend also uses XInput do you have this issue with it?  If you don’t then presumably GLFW could be fixed?
