### ISSUE TITLE
IM_ASSERT in release mode

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#8078]
### Version/Branch of Dear ImGui:

.

### Back-ends:

.

### Compiler, OS:

windows 10 mingw-w64

### Details:

Hi,

I  would like to have IM_ASSERT working in release mode build in order to reduce size but without lossing the valuable information provided by IM_ASSERT to detect imgui bad programming practices. For this to happen `NDEBUG` should not be defined even in release build.

A pattern as:

```cpp
// Helper Macros
#ifndef IM_ASSERT
#ifdef USE_ASSERT_IN_RELEASE
#undef NDEBUG
#endif
#include <assert.h>
#define IM_ASSERT(_EXPR)            assert(_EXPR)                               // You can override the default assert handler by editing imconfig.h
#endif
```
would be enougt so that adding `USE_ASSERT_IN_RELEASE` to compiler definitions would change the behaviour

**Comment by ocornut** [comment]
I agree asserts should always be enabled.

> For this to happen NDEBUG should not be defined even in release build. […] would be enougt so that adding USE_ASSERT_IN_RELEASE to compiler definitions would change the behaviour

You’ve provided the answer here. Why simply not remove NDEBUG from your compiler definition? It’s unrelated to dear imgui.

**Comment by sonoro1234** [comment]
I dont know how to remove it without #undef

**Comment by ocornut** [comment]
Don’t add it… it’s added to your project somewhere. Or your build system must add option. Or add #undef NDEBUG in your imconfig.h file.

**Comment by sonoro1234** [comment]
> Don’t add it… it’s added to your project somewhere.

cmake depending on `CMAKE_BUILD_TYPE` but I dont know if NDEBUG can be avoided (havent found the way)

> Or your build system must add option.

remove_definitions("-DNDEBUG") does not work and the other options are compiler dependant


> Or add #undef NDEBUG in your imconfig.h file.

This works but is what I was trying to avoid. After every imgui pull I would have to edit imconfig.h

**Comment by sonoro1234** [comment]
Also works:

`add_definitions("-DIMGUI_USER_CONFIG=\"../cimconfig.h\"")` in CMakeLists.txt and `#undef NDEBUG` in cimconfig.h

**Comment by ocornut** [comment]
> cmake depending on CMAKE_BUILD_TYPE but I dont know if NDEBUG can be avoided (havent found the way)

That’s a cmake problem not a dear imgui usage problem.

> remove_definitions("-DNDEBUG") does not work and the other options are compiler dependant

NDEBUG is compiler dependent anyway. Strictly speaking it is a define of the MS standard library afaik?

**Comment by sonoro1234** [comment]
https://www.oreilly.com/library/view/c-in-a/059600298X/re171.html

**Comment by ocornut** [comment]
Good to know, i didn’t realize it was standardized. Thanks!
