### ISSUE TITLE
Question: Input Capture behavior with IsMouseClicked()

### ISSUE THREAD

**Issue by luppichristian** [ocornut/imgui#8088]
### Version/Branch of Dear ImGui:

Version latest, Branch: docking

### Back-ends:

imgui_impl_sdl3.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

**My Issue/Question:**

Hi, I am trying to create a selection box using the ImGui API but i am having the following issue: 
ImGui::IsMouseClicked(ImGuiMouseButton_Left) captures the input always setting WantCaptureKeyboard to true, locking input from my app. I viewed in the debugger that NavActive is true and that is what captures the input. Why is that getting set? Is this expected behavior? I am not using ButtonBehavior because I am calling this not inside a Window.

If I disable io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard; this is fixed but i would still like to using with nav.

### Minimal, Complete and Verifiable Example code:

```cpp
bool selection_interaction(const char* name, bool* is_clicking, bool* started_click)
{
	ImGuiID id = ImGui::GetID(name);
	*started_click = false;
	*is_clicking = false;

	if(ImGui::IsMouseClicked(ImGuiMouseButton_Left) && (!ImGui::IsAnyItemHovered()) && (ImGui::GetActiveID()==0))
	{
		*started_click = true;
		*is_clicking = true;
		ImGui::SetActiveID(id, NULL);
		return false;
	}
	else if(ImGui::GetActiveID() == id)
	{
		*is_clicking = ImGui::IsMouseDown(ImGuiMouseButton_Left);
		ImGui::KeepAliveID(id);
		if(!(*is_clicking))
		{
			ImGui::ClearActiveID();
			return true;
		}
	}

	return false;
}
```

**Comment by ocornut** [comment]
> ImGui::IsMouseClicked(ImGuiMouseButton_Left) captures the input always setting WantCaptureKeyboard to true

That's not true. 

Your `SetActiveID()` logic does. I'm not sure I understand why you are using `SetActiveID()`. If this is not inside a window you are not really supposed to use those imgui functions.

You may override the value of `io.WantCaptureKeyboard` with e.g calling `ImGui::SetNextFrameWantCaptureKeyboard(false);` if you like.
