### ISSUE TITLE
Feature request: slang-gfx backend

### ISSUE THREAD

**Issue by Hyiker** [ocornut/imgui#8089]
### Version/Branch of Dear ImGui:

1.91.1

### Back-ends:

slang

### Compiler, OS:

None

## Motivation

I'm writing a personal project with imgui and [slang-gfx](https://shader-slang.com/slang/gfx-user-guide/), and I hope there could be official support for slang-gfx backend. In short, [slang](https://github.com/shader-slang/slang) is a brand new shading language resembling HLSL, but has richer language features and can be compiled to mainstream backends like dxil, spir-v etc. . `slang-gfx` is the abstraction library of graphics APIs, supporting cross-platform backends.

An official implementation of slang backend could be helpful for slang and imgui users.

## Details of implementation

I've implemented [my personal slang backend](https://gist.github.com/Hyiker/33c33977a60d93a52c678e30b45fa505)(haven't decoupled from my project framework, but it should be easy to do so). If this proposal could be taken, I'd be glad to make a PR writing the implementation.

## Concerns

The only concern I have is slang is still under fast iteration development, which exact version we use in this implementation should be decided.

**Comment by ocornut** [comment]
Hello, thanks for your interest and links.

Until a technology is widespread/common enough and stable I would not want to take on hosting an official backend.

I would however encourage you to extract yours into one, following our conventions (eg: imgui_impl_slang.cpp filenames, same function names etc). We will link to it from the list of backends in wiki. If ever Slang becomes more popular and you want it we can later consider merging it into the main repository.

**Comment by Hyiker** [comment]
> Hello, thanks for your interest and links.
> 
> Until a technology is widespread/common enough and stable I would not want to take on hosting an official backend.
> 
> I would however encourage you to extract yours into one, following our conventions (eg: imgui_impl_slang.cpp filenames, same function names etc). We will link to it from the list of backends in wiki. If ever Slang becomes more popular and you want it we can later consider merging it into the main repository.

Sounds reasonable, I may deliver my impl after some minor modifications to it.

**Comment by ocornut** [comment]
Thank you. I'll close this now. If you end up sharing something please post here as people are likely to stumble here.

In the meanwhile I'm adding a link to this thread from https://github.com/ocornut/imgui/wiki/Bindings#frameworkengine-backends

**Comment by fangjunzhou** [comment]
slang-gfx is deprecated. I'm currently maintaining this repo for my own projects: https://github.com/fangjunzhou/imgui.slang

Slang team is planning to add a imgui draw data pointer in the future.

Related threads in slangpy repo: https://github.com/shader-slang/slangpy/issues/600, https://github.com/shader-slang/slangpy/pull/858
