### ISSUE TITLE
Zip does not contain binaries as stated

### ISSUE THREAD

**Issue by mfeemster** [ocornut/imgui#809]
The download link says "imgui-demo-binaries-20160410.zip (Windows binaries, ImGui 1.48+ 2016/04/10, 4 executables, 534 KB)"

But there are no Windows executables included. I think it would be helpful to include them as stated so a casual observer might be able to quickly assess how an imgui program will look without having to build.

Thanks.

**Comment by ocornut** [comment]
It must be your OS or anti-virus software hiding them out. I can see them.

**Comment by mfeemster** [comment]
My bad, sorry for the confusion. Marking as closed.
