### ISSUE TITLE
Possible problems with endianess

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#81]
I'm using a little endian machine.

I was wondering if the library would still work on big endian systems (I guess I'll never use one, but my mind seems to like to create problems...).

Possible issues I can see:
1) Binary .fnt loading. Is that format endian free ?
2) The bin2c file conversion used by ImGui seems to group bytes into blocks of 4 (4 bytes -> 1 Uin32).

These problems could be solved in two ways:
a) creating all the binaries on the same machine they're supposed to be used.
b) using a more robust approach:
- 1) Adding code to support loading .fnt in text format (currently it's not trivial to extend the ImBitmapFont class, because it seems to store the binary .fnt blob in a single block and use pointers to access its parts.).
- 2) Using a different bin2c file conversion that just stores bytes one after another (producing longer source code, but the binary code size should be equal).

<b>I don't think this is a high-priority problem</b> [solution (a) above needs no code change], but maybe some note should be written about it...

**Comment by ocornut** [comment]
The embedded font data now used a base85 encoded string processed byte a byte and should be working on big-endian machines.

**Comment by ocornut** [comment]
I switched the font back to regular encoding to reduce binary space, source code is in a way that is big-endianess compatible.
