### ISSUE TITLE
Issue ImGui::ImplWin32_Init + ImGui::ImplDX9_Init

### ISSUE THREAD

**Issue by YarIchkaT** [ocornut/imgui#8108]
### Version/Branch of Dear ImGui:

Version last.

### Back-ends:

imgui_impl_dx9.cpp + imgui_impl_win32.cpp

### Compiler, OS:

Win 10 + VS 2022 

### Full config/build information:

ISO C++20
Release x86
Platform: Win32
Windows SDK version: 10.0 latest
Character Set: Use Multy-Byte Character Set
Additional Dependencies: d3d9.lib;%(AdditionalDependencies)
SubSystem: Windows (/SUBSYSTEM:WINDOWS)

### Details:

Hello everyone! I have a problem.
I am trying to create my own .dll, but there is a problem.
I am using a tutorial because I am not very good at c++, and in this tutorial everything is fine and there are no problems.

My problem is that I import:
#include "../ext/imgui/imgui.h"
#include "../ext/imgui/imgui_impl_win32.h"
#include "../ext/imgui/imgui_impl_dx9.h"

But when I call
ImGui::ImplWin32_Init(window);
ImGui::ImplDX9_Init(device);
I get the error:
namespace "ImGui" has no member "ImplWin32_Init"
namespace "ImGui" has no member "ImplDX9_Init"

It seems that everything is imported, there are no defects in imgui_impl_win32.h and imgui_impl_dx9.h, everything is fine:
IMGUI_IMPL_API bool ImGui_ImplDX9_Init(IDirect3DDevice9* device);
IMGUI_IMPL_API bool ImGui_ImplWin32_Init(void* hwnd);

I hope you can help me with this problem. Thanks in advance.

### Screenshots/Video:

// issue
![image](https://github.com/user-attachments/assets/149c8c38-0dd3-4daa-971e-58629ba44db0)
![image](https://github.com/user-attachments/assets/a5358793-3e12-4564-af6d-ba319efc965f)

// .h files not have deffects
![image](https://github.com/user-attachments/assets/030e3309-496c-492a-963a-9c113466a1a8)
![image](https://github.com/user-attachments/assets/0996c921-f1ea-433e-825a-dff05d484a44)

// edited, in at the beginning of the file I indicated:
![image](https://github.com/user-attachments/assets/bb18b239-7dd6-45ca-8b6d-fff280390cfe)

### Minimal, Complete and Verifiable Example code:

```cpp
#include "../ext/imgui/imgui.h"
#include "../ext/imgui/imgui_impl_win32.h"
#include "../ext/imgui/imgui_impl_dx9.h"

// Im calling:
ImGui::ImplWin32_Init(window);
ImGui::ImplDX9_Init(device);

// I get the error:
namespace "ImGui" has no member "ImplWin32_Init"
namespace "ImGui" has no member "ImplDX9_Init"
```

**Comment by ocornut** [comment]
Well you are not calling the right function name..
As you pasted one function is called eg ImGui_ImplDX9_Init() and you are calling ImGui::ImplDX9_Init() which doesn’t exists.

Refer to Getting Started guide and example_win32_dx9 for references.

**Comment by YarIchkaT** [comment]
> Well you are not calling the right function name.. As you pasted one function is called eg ImGui_ImplDX9_Init() and you are calling ImGui::ImplDX9_Init() which doesn’t exists.
> 
> Refer to Getting Started guide and example_win32_dx9 for references.

Oh my god, thank you, I've already searched the entire internet, as I now understand, the two lines of code above started with ImGui::

```cpp
ImGui::CreateContext();
ImGui::StyleColorsDark();
```

And when I wanted to write the other two lines, I specified ImGui:: instead of _.

Thanks anyway.
