### ISSUE TITLE
Check if any windows are drawn to screen right now?

### ISSUE THREAD

**Issue by iUltimateLP** [ocornut/imgui#8123]
### Version/Branch of Dear ImGui:

Version 1.87, Branch: master

### Back-ends:

https://github.com/EnvarStudio/UnrealImGui

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

Hey there! I'm wondering, what's the best way to check if there are any windows currently displayed? I'm trying to show a hint "Hold ALT to interact with debug UI", but only show it if there's actually something to interact with. Since we have various places in code that can and will draw ImGui windows for debugging, there's no unified place of setting a variable on my own. After digging a bit, I came up with:

```cpp
		bIsAnyWindowActive = false;
		for (int32 WindowIdx = 0; WindowIdx < Context->Windows.Size; WindowIdx++)
		{
			ImGuiWindow* Window = Context->Windows[WindowIdx];
			FString WindowName = FString(Window->Name);

			if (Window->Active && !Window->Hidden && !WindowName.StartsWith(TEXT("#")))
			{
				bIsAnyWindowActive = true;
			}
		}
```

But, including the requied imgui_internal.h for this results in a bunch of compiler errors - could be related to the [UnrealEngine backend I'm using](https://github.com/EnvarStudio/UnrealImGui), but I'm also unsure whether it'd be the best way to do this in our UnrealImGui fork, sounds more like something that could be integrated in ImGui itself?

Best, Johnny

**Comment by GamingMinds-DanielC** [comment]
I don't think you will get around imgui_internal.h to access window information. You didn't state which compiler errors you get, but they probably stem from conflicts between the internals and some Unreal headers. Just don't mix them. You can compartmentalize this problem by putting the code that accesses the internals into a function (f.e. `IsAnyWindowActive()`), putting the internals include and the function definition into a separate cpp and a declaration into a matching header. Then you have basically a small extension library that accesses internals, so you don't need to include the internals into other sources. That extension library should then of course not include any Unreal headers.

**Comment by ocornut** [comment]
There is `int MetricsRenderWindows` exposed in `ImGuiIO` which you can use.
There is also `int MetricsActiveWindows` but note you'll need to test >1 because the implicit "Debug" window is always marked active.
