### ISSUE TITLE
Is it possible to change widget's active area?

### ISSUE THREAD

**Issue by nikitablack** [ocornut/imgui#8134]
### Version/Branch of Dear ImGui:

Version v1.90.7, Branch: docking

### Back-ends:

Custom

### Compiler, OS:

Ubuntu 20.04

### Details:

I'm making a timeline and I want each frame marker to be a button widget - it should interact on hover, mouse press, etc. Something like this:
![Screenshot from 2024-11-07 10-31-19](https://github.com/user-attachments/assets/b6f0fc2e-853f-40bc-996c-7d8bd2f0818d)
Here I hovered over a frame 20 button (though the capture software moved mouse a bit to the left).

Now I want the markers to stay the same size, but capture mouse below them:
![Screenshot from 2024-11-07 10-31-39](https://github.com/user-attachments/assets/0b84be01-63c5-4f0d-bd35-59df91a7178d)
Here I hold the mouse cursor under the frame 20 button and want it to be hovered. Also, when I press the button, I want it to look pressed.

I can draw rectangles and assign a color depending on a mouse positions, but is there maybe a simper recommended way? For example, expand the _active area_ of a button somehow?

**Comment by ocornut** [comment]
Typically you would create your own widget by calling either `InvisibleButton()` or `ButtonBehavior()` (slightly lower level)
And then draw the visuals yourself (here it would be two calls).

For a timeline like this, I often found it even more practical to submit a _single_ button from ImGui point of view and do the geometry hit-testing yourself based on mouse position. But both ways would work.

**Comment by nikitablack** [comment]
Thank you. I implemented this with multiple `InvisibleButton`s.
