### ISSUE TITLE
Compile warning in ImDrawListSplitter constructor with recent Clang 20

### ISSUE THREAD

**Issue by floooh** [ocornut/imgui#8135]
### Version/Branch of Dear ImGui:

1.91.4

### Back-ends:

n/a

### Compiler, OS:

Clang 20.0 (via Emscripten)

### Details:

I'm seeing a new warning when compiling with the most recent Emscripten SDK (which is based on Clang 20.0 - according to cmake):

```
imgui.h:3020:43: warning: first argument in call to 'memset' is a pointer to non-trivially copyable type 'ImDrawListSplitter' [-Wnontrivial-memaccess]
 3020 |     inline ImDrawListSplitter()  { memset(this, 0, sizeof(*this)); }
```

...I think Clang sees that ImDrawListSplitter isn't a POD object (because it has a `ImVector<ImDrawChannel>` member) and warns about the 'brute force' memset, but as the warning says, a cast may be enough to silence the warning (but maybe it's better to get rid of the memset?)

**Comment by ocornut** [comment]
Linking to #8129 as per my comment there I was surprised the PR didn't need to be applied to other files.

Can you confirm that adding
```cpp
#pragma clang diagnostic ignored "-Wnontrivial-memaccess"           // warning: first argument in call to 'memset' is a pointer to non-trivially copyable type
```
in imgui.h in the right block gets you to zero warnings?

**Comment by ocornut** [comment]
I'd be also curious if you can confirm if casting the pointer to `(void*)` fixes it?
(I don't have a Clang 20 setup yet)

**Comment by floooh** [comment]
Let me try both things, back in a minute :)

**Comment by floooh** [comment]
...wow I'm getting a ton of similar warnings when trying locally (before I just checked Github CI).

One interesting thing is that the Emscripten SDK `3.1.70` and `3.1.71` both report `Clang 20.0.0` in cmake, but the warnings are only in 3.1.71.

A `(void*)` cast silences the warning, like this:

```cpp
inline ImDrawListSplitter()  { memset((void*)this, 0, sizeof(*this)); }
```

...but there's lot of other places...

The pragma solution works too (might be the better solution), but I need to put that into the following files to silence all warnings (which is kinda expected I guess):

- imgui.cpp
- imgui.h
- imgui_draw.cpp
- imgui_tables.cpp
- imgui_widgets.cpp
- imgui_internal.h

**Comment by ocornut** [comment]
Thanks. Let me know if 419a9ad fixes it 100%.

**Comment by floooh** [comment]
Yep looks good 👍

**Comment by floooh** [comment]
Should I close the ticket? I'll just close the ticket...
