### ISSUE TITLE
What kind of anti aliasing is that???

### ISSUE THREAD

**Issue by DrJedikiah** [ocornut/imgui#814]
![screenshot_1](https://cloud.githubusercontent.com/assets/12988451/18227342/3133ffd0-722a-11e6-9260-8872112edfba.png)

This looks so anti aliased :(

Everything which has "AntiAliasing" is open. I cannot draw a perfect circle.

**Comment by ocornut** [comment]
What kind of bug report is that???

It looks like AA is disabled or your renderer is faulty. Circles are fine in the examples application. Please submit a repro.

**Comment by DrJedikiah** [comment]
Sorry for my bad report the reason is i'm trying to draw a perfect circle since this morning and its 23:10PM here :( And that made me angry. I'm trying to figure out renderer's problem. I'm using EndScene hook to existing device.

**Comment by ocornut** [comment]
There's no EndScene in imgui, that must be part of your own software infrastructure.
First try testing the same render in a vanilla ImGui example.

**Comment by ocornut** [comment]
I have to close this because it looks like a bug on your side, that is until you can provide a repro.
```
ImDrawList* draw_list = ImGui::GetWindowDrawList();
ImVec2 p = ImGui::GetCursorScreenPos();
draw_list->AddRectFilledMultiColor(ImVec2(p.x, p.y), ImVec2(p.x+100,p.y+100), IM_COL32(255,255,255,255), IM_COL32(255,255,255,255), IM_COL32(255,0,0,255), IM_COL32(255,0,0,255));
draw_list->AddCircle(ImVec2(p.x + 50, p.y + 50), 5.0f, IM_COL32(255,255,255,255), 12, 2.0f);
draw_list->AddCircle(ImVec2(p.x + 50, p.y + 50), 6.0f, IM_COL32(0,0,0,255), 12, 2.0f);
ImGui::Dummy(ImVec2(100.0f, 100.0f));
```
![circle](https://cloud.githubusercontent.com/assets/8225057/18227507/e1e1b060-7226-11e6-9bd8-820e40a3f5ad.png)
