### ISSUE TITLE
Demo App says "io.ConfigDebugDetectIdConflicts" instead of "io.ConfigDebugHighlightIdConflicts"

### ISSUE THREAD

**Issue by xezon** [ocornut/imgui#8142]
### Version/Branch of Dear ImGui:

Version 1.91.4, Branch: docking

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx9.cpp

### Compiler, OS:

Windows 10

### Details:

Demo App says "io.ConfigDebugDetectIdConflicts" instead of "io.ConfigDebugHighlightIdConflicts"

```cpp
BulletText("Set io.ConfigDebugDetectIdConflicts=false to disable this warning in non-programmers builds.");
```

**Comment by ocornut** [comment]
Thank you! I fixed this as part of 3381ab4
