### ISSUE TITLE
Basic API misuse causes crash on one device but not the other

### ISSUE THREAD

**Issue by BenMcAvoy** [ocornut/imgui#8146]
### Version/Branch of Dear ImGui:

Version 1.91.5 WIP, Branch: docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Arch Linux, GCC/G++ 

### Full config/build information:

```
Dear ImGui 1.91.5 WIP (19141)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=202002
define: __linux__
define: __GNUC__=14
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000000
io.ConfigViewportsNoDecoration
io.ConfigNavCaptureKeyboard
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1052.00,1052.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

I am using the latest docking branch and I am building a game engine. I have given users access to ImGui through the Lua bridge using bindings however this problem exists whether writing the bug in raw C++ or Lua, I simply noted this here as it may be unclear why API mismanage crashing the program even matters.

On my desktop, misuse of the API is a hard crash whereas on my laptop it simply displays an error message in the GUI (the outcome that I want and not crashing). Is this expected behaviour to crash on certain platforms, is there a way for me to fix this?

My project can be found here: https://github.com/jenjinengine/exgine if it is of any use.

### Screenshots/Video:

PC demo, crashing:

https://github.com/user-attachments/assets/617d07a2-9dfc-4254-b76a-e7fa8ed3bb6f

Laptop demo, no crash:

https://github.com/user-attachments/assets/a023076e-3d36-4292-ab67-72fd228dcdae

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's an example misusage of the API
ImGui::Begin("Example Bug");
// Anything
// Missing an End statement
```

```lua
-- Here's an example misusage of the API
ImGui.Begin("Example Bug");
-- Anything
-- Missing an End statement
```

**Comment by BenMcAvoy** [comment]
A deeper backtrace is provided here:
![image](https://github.com/user-attachments/assets/25d04976-0105-4946-b1a6-a1e903c3d867)

**Comment by GamingMinds-DanielC** [comment]
That's not a hard crash on your PC, but an assertion that is handles with a controlled exit. You should check your build configurations, maybe they diverged on your machines. With identical build configurations they should behave identically. Possibly different versions of linked libraries.

**Comment by ocornut** [comment]
We call `IM_ASSERT()` which by default calls `assert()`. This is a traditional mechanism we use to detect programming errors.
By default `assert()` from the stdlib is defined as a no-op when `NDEBUG` is defined in your build configuration. IHMO you should never have assert disabled ever.
What's probable is that your laptop build was compiled with NDEBUG set.

Also note that although the asserts have been here for a decade, since [1.91.3](https://github.com/ocornut/imgui/releases/tag/v1.91.3) we added features to facilitate error recovery. See https://github.com/ocornut/imgui/wiki/Error-Handling

You may e.g. set `io.ConfigErrorRecoveryEnableAssert = false` to disable recoverable errors calling IM_ASSERT() and rely on the tooltips instead. You may selectively disable it until while running Lua code or also when running C++ code.

**Comment by BenMcAvoy** [comment]
Thank you so much to both of you, this worked a treat!

Out of interest, when you said:
> "IHMO you should never have assert disabled ever."

What did you mean? What's an alternative you would recommend as I can't have the engine crashing any time a user makes a mistake with the ImGui API. For now, I simply have disabled them when unimportant and wrapped in some recovery code as the docs demonstrate for scripting.

Thank you for working continuously on this library, it's amazing!

**Comment by ocornut** [comment]
The new error handling features allows you to not throw asserts for selected errors that are recoverable, but the non recoverable errors will still throw asserts and you should absolutely see the asserts. If you don't you'll have a harder time catching errors.

**Comment by BenMcAvoy** [comment]
Sorry if I'm being silly here, I have the following rough code
```cpp
void LuaLoader::Draw() {
  ImGuiErrorRecoveryState state;
  ImGui::ErrorRecoveryStoreState(&state);

  try {
    for (auto &script : this->scripts) {
        // run the script! Excluded for simplicity
    }
  } catch (...) {
    spdlog::error("LuaLoader::Draw(): An error occurred, attempting to recover ImGui state.");

    ImGui::ErrorRecoveryTryToRecoverState(&state);
  }
}
```

Do I need to opt-in to the exceptions instead of pure asserts? I still get an assertion that kills the process
