### ISSUE TITLE
Emscripten builds to single file, no need for http server, no browser security restrictions

### ISSUE THREAD

**Issue by Pe3ucTop** [ocornut/imgui#8153]
### Version/Branch of Dear ImGui:

Version: any , Branch: any

### Back-ends:

- imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp
- imgui_impl_glfw.cpp + imgui_impl_wgpu.cpp  ( with examples/libs/emscripten/shell_minimal.html modifications )

### Compiler, OS:

Linux + Emscripten

### Details:

Suggestion for builds with Emscripten to use Makefile linker flag:  `LDFLAGS += -sSINGLE_FILE` which will result in single html file output (`EXE = $(WEB_DIR)/index.html`).

Goals of single output file:
- no need for http server, file could be opened directly by Web browser;
- no Web browser security restrictions for hardware use requests (serial port in my condition and should be the same for gamepad / usb / audio / camera / etc );
- easy to redistribute.

Negative aspect:
- output file is bigger then sum of all files of split build because of included binary files got converted to BASE64 format.

**Comment by ocornut** [comment]
You are free to build your app however you like. I don’t think there is value in us providing _example apps_ that use this build method.

**Comment by ocornut** [comment]
I'm adding a comment in the Makefile to suggest this is a possible option.
