### ISSUE TITLE
Using ImGui::Image() with Allegro5-OpenGL

### ISSUE THREAD

**Issue by Quark3e** [ocornut/imgui#8155]
### Version/Branch of Dear ImGui:

Version 1.90.8 Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_allegro5.cpp

### Compiler, OS:

ChromeOS(Version 130.0.6723.101)_Linux (Debian 12 "Bookworm") + G++

### Full config/build information:

**(Note: Can't copy to clipboard so the output is written by hand and mistakes might exist, as a heads up. Screenshots are included)**

Dear ImGui 1.90.8 WIP (19071)
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=201703
define: __linux__
define: __GNUC__=12
io.BackendPlatformName: imgui_impl_allegro5
io.BackendRendererName: imgui_impl_allegro5
io.ConfigFlags: 0x00000001
 NavEnableKeyboard
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00000002
 HasMouseCursors
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,64
io.DisplaySize: 1280.00,698.00
io.DisplayFramebufferScale: 1.00,1.00
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00

![Screenshot 2024-11-17 12 35 16](https://github.com/user-attachments/assets/0ebb3bf5-f4ee-4d46-b1db-3de16bd29026)
![Screenshot 2024-11-17 12 35 09](https://github.com/user-attachments/assets/50e57421-fbd2-440a-8e77-d0ce49d0ca16)

### Details:

[Knowledge level: **Beginner**]

Is there a way to use `ImGui::Image()` with imgui-allegro5-opengl?

Hi. I recently began using ImGui for learning how to make simple c++ gui applications and am interested in adding images to my applications. My choice of "method"/library is Allegro5 which on my system uses opengl 4.3 (assuming i haven't misunderstood allegro5 graphics basics) but i had trouble finding any tutorials or examples specifically for imgui-allegro5/opengl image rendering.

I assume this is possible solely because the function
```c++
void ImGui::Image(ImTextureID user_texture_id, const ImVec2 &image_size, const ImVec2 &uv0, const ImVec2 &uv1, const ImVec4 &tint_col, const ImVec4 &border_col)
```
is available with allegro5 dependencies so I tried finding a solution through "brute forcing"(writing, try to build, change something, repeat without any idea what I'm doing), by using the [opengl tutorial](https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples#example-for-opengl-users) with two ways/methods:
- using the `allegro5/allegro_opengl.h` header provided by allegro5.
- using the `GLFW/glfw3.h` header.

Below are the setups for how it's all run: (apologies for the atrocities):

The full included header looks like this: (idk how to add code with newline sorry)
```c++
 #include <allegro5/allegro.h>
 #include <allegro5/allegro_primitives.h>
 #include <imgui/imgui.h>
 #include <imgui/backends/imgui_impl_allegro5.h>
 #if method1
 #include <allegro5/allegro_opengl.h>
 #else
 #include <GLFW/glfw3.h>
 #endif
```
and the build command:
```bash
/usr/bin/g++ 
-DIMGUI_USER_CONFIG=\"/usr/local/include/imgui/examples/example_allegro5/imconfig_allegro5.h\" 
-fdiagnostics-color=always 
-I/usr/local/include/imgui/ 
-I/usr/local/include/imgui/backends/ 
-I/projDir/ 
-g 
/projDir/src/main.cpp 
/projDir/src/global_variables.cpp 
/projDir/src/tab_options.cpp 
/usr/local/include/HC_useful/diy_dictionary.cpp 
/usr/local/include/HC_useful/pathSchedule.cpp 
/usr/local/include/imgui/backends/imgui_impl_allegro5.cpp 
/usr/local/include/imgui/imgui*.cpp 
-L/usr/local/lib 
-lallegro 
-lallegro_main 
-lallegro_primitives 
-lallegro_image 
-lglfw 
-lGLU 
-lGL 
-o 
outEXE
```

how the image is loaded:
```c++
//header file: global scope
extern int my_image_width;
extern int my_image_height;
extern GLuint my_image_texture;

//source file: global scope 
int my_image_width = 0;
int my_image_height = 0;
GLuint my_image_texture = 0;

//main source file: int main() scope
bool ret = LoadTextureFromFile("/projDir/media/MyImage01.jpg", &my_image_texture, &my_image_width, &my_image_height);
IM_ASSERT(ret);

//secondary source file: custom function scope:
//  located inside a ImGui::BeginTabItem()
ImGui::Text("pointer = %x", my_image_texture);
ImGui::Text("size = %d x %d", my_image_width, my_image_height);
ImGui::Image((ImTextureID)(intptr_t)my_image_texture, ImVec2(my_image_width, my_image_height));
```

Running this with both headers, everything runs fine until i selected the tab and reach the `ImGui::Image()`  call, which when i do causes Segmentation error at 
```c++
ImGui_ImplAllegro5_RenderDrawData(ImGui::GetDrawData());
```
Looking with vscode's debugging it showed that the segmentation error happend at 
```c++
al_draw_indexed_prim(&vertices[0], bd->VertexDecl, texture, &indices[pcmd->IdxOffset], pcmd->ElemCount, ALLEGRO_PRIM_TRIANGLE_LIST);
```
in the `imgui_impl_allegro5.cpp` file.

For any detailed info the FULL project is here: https://github.com/Quark3e/Chromebook-projects/tree/main/projects/proj_Hexclaw_cpp/remote_GUI.

I'm trying this because I'm assuming it is possible to call the `ImGui::Image()` method with allegro5, but that it's just me messing up somewhere so I'd like any help i can get. If any more info/context is needed then I'll be happy to do my best to respond. Thanks in advance and again, apologies for the level of ineptitude by me.

### Screenshots/Video:

[Screen recording 2024-11-17 17.23.49.webm - VSCode Debugger output when the app crashes](https://github.com/user-attachments/assets/d75e0329-4810-4ace-b880-e505ee16db30)
[Screen recording 2024-11-17 17.22.54.webm - the app crashing](https://github.com/user-attachments/assets/4ee2bc55-d92a-49f1-b028-e0786ba1aa8f)

### Minimal, Complete and Verifiable Example code:

(Not sure what to add here)

**Comment by ocornut** [comment]
As outlined at the top of imgui_impl_allegro5.cpp/.h, this backend requires an ALLEGRO_BITMAP* in ImTextureID. The value is passed straight to al_draw_indexed_prim() which takes a ALLEGRO_BITMAP*.

**Comment by Quark3e** [comment]
> As outlined at the top of imgui_impl_allegro5.cpp/.h, this backend requires an ALLEGRO_BITMAP* in ImTextureID. The value is passed straight to al_draw_indexed_prim() which takes a ALLEGRO_BITMAP*.

Holy crap... it really is just pass the ALLEGRO_BITMAP* to ImGui::Image, e.g.
```c++
ImGui::Image((ImTextureID)(intptr_t)bitmapVar, ...);
```

Welp thanks. This "solved" everything. Sorry for the troubles and thanks again for answering. Do I delete this issue because it was too basic of a question or is closing it just fine?

**Comment by ocornut** [comment]
It’s always good to leave issues for future reference for others! Glad it is solved.

**Comment by ocornut** [comment]
I suppose we could add an Allegro example in https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
