### ISSUE TITLE
Wrong CurrentDpiScale value / Tree nodes in a table no more clickable / expandable

### ISSUE THREAD

**Issue by etsach** [ocornut/imgui#8156]
### Version/Branch of Dear ImGui:

Version 1.91.0

### Back-ends:

n/a

### Compiler, OS:

MSVC 2022

### Details:

**Issue**

Grouping table rows inside a tree node for allowing row collapse/expansion used to work with 1.90.5, but after updating to 1.91.0, the tree nodes cannot be interacted with mouse anymore. Clicking on the expand arrow grabs the column width handle.
Is this a bug introduced in 1.91.0, a new set of flags that is required for this to work, or is treenode nesting inside a table not supported?

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by ocornut** [comment]
Please provide at minimum at video so we can see the context, and some code.

**Comment by etsach** [comment]
Here is a code example, with the corresponding video.
Expanding nodes with arrow worked with 1.90.5, and does not anymore with 1.91.0

Interestingly, it works, only if the first column is >=50% of the width.
So:
- It always works with one column
- It works at start with two columns, but stops working if we reduce the column width to <50%
- It doesn't work at start with three columns, but starts working if we expand first column to more than 50%
[

https://github.com/user-attachments/assets/7828e198-491f-4ca5-9da1-07e2d4f92e5f

](url)

```
if (ImGui::BeginTable("My Table", 3, ImGuiTableFlags_RowBg | ImGuiTableFlags_Borders | ImGuiTableFlags_SizingStretchProp | ImGuiTableFlags_Resizable))
	{
		ImGui::TableSetupColumn("Name");
		ImGui::TableSetupColumn("Value");
		ImGui::TableSetupColumn("Unit");
		ImGui::TableHeadersRow();


		for(int i=0;i<10;++i)
		{
			ImGui::TableNextRow();
			ImGui::TableNextColumn();
			if(ImGui::TreeNodeEx(std::to_string(i).c_str(),ImGuiTreeNodeFlags_SpanAllColumns + ImGuiTreeNodeFlags_AllowOverlap))
			{
				ImGui::TableNextRow();
				ImGui::TableNextColumn();
				ImGui::Text("%s", "Foo");
				ImGui::TableNextColumn();
				ImGui::Text("%s", "123");
				ImGui::TableNextColumn();
				ImGui::Text("%s", "bar");

				ImGui::TreePop();
			}
		}
		


		ImGui::EndTable();
	}
```

**Comment by ocornut** [comment]
Hmm that's very odd. Some related code changed in 1.90.6.

Are you on `master` or `docking` branch?
Could you debug step in `TableUpdateBorders()` and verify the value of `g.CurrentDpiScale` ?

**Comment by etsach** [comment]
I'm using ImGUI Unreal Engine plugin from here : https://github.com/VesCodes/ImGui?tab=readme-ov-file
It uses the docking branch.

**Comment by etsach** [comment]
I have g.CurrentDpiScale = 109

**Comment by ocornut** [comment]
> I have g.CurrentDpiScale = 109

That is extremely wrong and this is causing your issue as we started using this value for more things.

The value should in ranges such as 1.0f (100% scale) to maybe e.g. 3.0f (300%).

Probably the backend code is wrong. Perhaps some struct definitions are mismatching.

g.CurrentDpiScale is pulled from viewport's DpiScale which should be pulled from monitor's DpiScale.
You would need to debug things to figure out why you are ending with a wrong value somewhere in the chain.

This code in the backend you linked aimed to write to Monitor's DpiScale:
https://github.com/VesCodes/ImGui/blob/af47725545ca727c06d7fdbd7fa9fbba61340274/Source/ImGui/Private/ImGuiContext.cpp#L532

```cpp
ImGuiMonitor.DpiScale = Monitor.DPI / 96.0f;
```

**Comment by etsach** [comment]
Not an issue from ImGui but from the UE plugin backend
