### ISSUE TITLE
Should I contribute a Date Picker?

### ISSUE THREAD

**Issue by Brotcrunsher** [ocornut/imgui#8159]
### Version/Branch of Dear ImGui:

Not necessary for the question

### Back-ends:

Not necessary for the question

### Compiler, OS:

Not necessary for the question

### Details:

Hi there!

I've made a rather simple but effective Date Picker for my own project and I wondered if it makes sense to add this to Dear ImGui. The current implementation is using custom types of my engine, so a bit of clean up would be necessary to use time_t instead.  Before doing so, I wanted to check if this is even a wanted contribution to the base Dear ImGui project.

The header would probably look something like this:

`bool DatePicker(const char* label, time_t* time, SomeKindOfFlags flags = First Day is Monday/Sunday...);`

For a reference implementation see: https://github.com/Brotcrunsher/BrotBoxEngine/blob/master/BrotBoxEngine/ImGuiExtensions.cpp#L93 (Final pull request version would look quite a bit different)

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/143261eb-34b7-4ed5-a38d-33b73412a52e)

**Comment by ocornut** [comment]
Hello, 

Thanks for asking! In theory it would be a desirable addition. But my gut intuition is that it'll be too much work right now to iterate on this toward a version that's acceptable for core imgui lib so I am not sure I want to take on that cognitive load right now.

I would however always encourage you to try extracting/separating the code, into e.g. its own file (or even project) if you can.
Then we can link it from https://github.com/ocornut/imgui/wiki/Useful-Extensions to increase visibility and likelihood of it being used by other people. 

Flix01 repo (https://github.com/Flix01/imgui/wiki/ImGui-Addons-Branch-Home) which is rather old had one.
But until right one I didn't think there was another.. and I just googled "imgui date picker" now and found one which looks good: https://github.com/DnA-IntRicate/ImGuiDatePicker so there's htat.

**Comment by ozlb** [comment]
In implot there is a neat implementation of both date and time picker
