### ISSUE TITLE
ImGui::ImageButton render transparent image error

### ISSUE THREAD

**Issue by chris0306** [ocornut/imgui#8165]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

GLESv2

### Details:

ImGui::Image(texid, ImVec2(128, 128), uv0, uv1);

if (ImGui::ImageButton(texid, ImVec2(128, 128))) {
     printf("btn clicked!12!!\n");
}

ImGui::Image is right, but imagebutton color is wrong, the edge of "p" image is transparent.
how to solve it , thanks!!!

### Screenshots/Video:

![ppp](https://github.com/user-attachments/assets/45784aa3-93e4-4c99-8dc5-764d5d9ceaac)

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue
ImGui::Begin("Example Bug");
MoreCodeToExplainMyIssue();
ImGui::End();
```

**Comment by GamingMinds-DanielC** [comment]
Could be many things, you left out so much information that there is nothing to go on. First you can check the texture format and the blend states with RenderDoc, to see if they are as they should be.

**Comment by ocornut** [comment]
> ImageButton() draws a background frame using the ImGuiCol_ButtonXXXX colors.

So if you have a transparent image and want to disable that background you may need to use:

```cpp
PushStyleColor(ImGuiCol_Button, ImVec4(0, 0, 0, 0));
PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0, 0, 0, 0));
PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0, 0, 0, 0));
ImageButton(...);
PopStyleColor(3);
```
You may wrap this into your own helper function if needed.

I am adding comments to clarify this in the `ImageButton()` declaration and definition.
Ideally we might introduce flags to control those behavior. Similarly to the problem discussed in #8131 for `Image()`.

Closing.
