### ISSUE TITLE
Viewport's WorkPos not up to date on first frame

### ISSUE THREAD

**Issue by lailoken** [ocornut/imgui#8170]
### Version/Branch of Dear ImGui:

Version 1.91.1, Branch: docking

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_opengl3.cpp + imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

MSVC / Linux Clang/GCC

### Full config/build information:

```
Dear ImGui 1.91.1 WIP (19101)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 4, sizeof(ImDrawVert): 20
define: __cplusplus=201103
define: IMGUI_DISABLE_OBSOLETE_FUNCTIONS
define: IMGUI_DISABLE_OBSOLETE_KEYIO
define: __linux__
define: __GNUC__=13
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_sdl2
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000081
 NavEnableKeyboard
 DockingEnable
io.ConfigViewportsNoAutoMerge
io.ConfigViewportsNoDecoration
io.ConfigViewportsNoDefaultParent
io.ConfigDockingWithShift
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x00001C0E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 HasMouseHoveredViewport
 RendererHasVtxOffset
 RendererHasViewports
--------------------------------
io.Fonts: 11 fonts, Flags: 0x00000000, TexSize: 1024,2048
io.DisplaySize: 1920.00,1080.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

What I'm trying to do is: open up a window so that it does not obscure the/a possible menu bar.

 I'm building for multiple platforms and backends (windows, linux and emscripten) and am trying to write code that uses the correct layout while allowing the user to slectively use viewports vs single window mode.
 
 However, while I do see that the menu bar correctly changes the workpos, it only does so on the second iteration.
 Thus if my window opened up on a menu trigger it would work correctly, but if it opens up at the start, then not.
 
 Currently as a workaround I'm checking if workpos is still initial after rendering my menu, and then just incremeting it for that iteration manually.
 
 I've checked the changelogs of updates and issues, but have not seen references.

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/68dc0221-c75f-4138-b80a-2ec8a819d77f)

### Minimal, Complete and Verifiable Example code:

```cpp
    if (ImGui::BeginMainMenuBar())
    {
        ImGui::MenuItem("Test");
        ImGui::EndMainMenuBar();
    }
    auto pos = ImGui::GetMainViewport()->WorkPos;
    // assert(ImGui::GetMainViewport()->WorkPos.y != 0.f); // this fails
    ImGui::SetNextWindowPos(pos, ImGuiCond_FirstUseEver);
    ImGui::Begin("Test");
    ImGui::End();
```

**Comment by ocornut** [comment]
Viewport's WorkPos/WorkSize are one frame behind because they need to account for multiple submissions (e.g. status bar, other side bars) regardless of order, and are locked for the frame. So indeed you would experience the issue you reported.

I'm not sure how to solve this neatly other than making you defer your window submission (`if (ImGui::GetFrameCount() >1`). If we adjust WorkPos/WorkSize iteratively we become order dependent which is undesirable for a feature designed to tie two things submitted in wildly different location, and which will tend to manifest for single frames.

**Comment by lailoken** [comment]
Thanks,  my main loop does the (optional) menu first, then it does my custom application launcher (which does a manual adjustment of work area as well).

I'll do a:
```
if (ImGui::GetFrameCount() == 0)
   continue;
```
after that. Should be a bit cleaner.
