### ISSUE TITLE
Assert in Render()

### ISSUE THREAD

**Issue by KraXarN** [ocornut/imgui#818]
Application crashes when trying the Allegro 5 example with the following error:
`imgui.cpp:2620: void ImGui::Render(): Assertion 'g.Initialized' failed.`
Commenting out ImGui::Render() from the code makes it run, but ImGui doesn't render anything obviously.

**Comment by ocornut** [comment]
Have you read the comment on this line?
`IM_ASSERT(g.Initialized);   // Forgot to call ImGui::NewFrame()`

**Comment by ocornut** [comment]
You should call NewFrame() at least once prior to Render() to setup the data structures and start using imgui. The usual loop is NewFrame()/yourcode/Render().

**Comment by KraXarN** [comment]
NewFrame() was called in a different place than it should, my bad. Thanks!
