### ISSUE TITLE
AddRectMultiColor

### ISSUE THREAD

**Issue by paindoll** [ocornut/imgui#8181]
### Version/Branch of Dear ImGui:

Current version

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

Windows 11 + MSVC 2022

### Full config/build information:

v1.91.5 WIP

### Details:

Is there any kind method to render a non-filled gradient rect without creating four rects of AddRectFilledMultiColor?

**Comment by ocornut** [comment]
Also see #4722 but it is essentially the same as answered above: draw the shape you want as white and then "shade" them, which is the call to `ShadeVertsLinearColorGradientKeepAlpha()` in #4722. I am also pretty sure the loop Daniel posted is equivalent to be calling `ShadeVertsLinearColorGradientKeepAlpha()`. So technically you could add well call `AddRect()` + `ShadeVertsLinearColorGradientKeepAlpha()`.

However, I strongly feel that answer (1) is probably the right answer. It's very probably not a problem to call e.g. `AddRectFilledMultiColor()` multiple times if you need it. If you are not drawing 10000+ shapes every frame the difference will likely not matter.

**Comment by ocornut** [comment]
Closing as answered. Thanks Daniel!
