### ISSUE TITLE
Use of `ImGui::IsKeyPressed()` in `ImGui::NavUpdateCreateMoveRequest()` triggers assert due to unsupported flags

### ISSUE THREAD

**Issue by Julianiolo** [ocornut/imgui#8182]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: master

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Windows 10 + msvc 2022

### Details:

[`ImGui::NavUpdateCreateMoveRequest()`](https://github.com/ocornut/imgui/blob/9b273294377dfe0e054614489f90632bfb7af0e3/imgui.cpp#L13009) uses `ImGui::IsKeyPressed()` with the flag `ImGuiKeyOwner_NoOwner`, which triggers this [assert](https://github.com/ocornut/imgui/blob/9b273294377dfe0e054614489f90632bfb7af0e3/imgui.cpp#L9317) (also see [`ImGuiInputFlags_SupportedByIsKeyPressed`](https://github.com/ocornut/imgui/blob/9b273294377dfe0e054614489f90632bfb7af0e3/imgui_internal.h#L1492))

The assert gets triggered when using the arrow keys.

**Comment by ocornut** [comment]
It doesn't. `ImGuiKeyOwner_NoOwner` is passed in the `owner_id` parameters, not as flags, you can see it in the code you linked.

However, the parameters were swapped in 85513de2 (May 2024).
Although this is all internal code, and should not have any effect on it, it's possible that you have an old version that had a bug, or that you have a broken merge. But you didn't specify a version.
