### ISSUE TITLE
how to : showing items border inside the menu 

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#819]
Hi
how to apply ImGuiWindowFlags_ShowBorders flag to those items ?
![imgui](https://cloud.githubusercontent.com/assets/10813427/18341445/4eb17532-75aa-11e6-80ce-4de2cf393311.png)

**Comment by ocornut** [comment]
The ShowBorders flag is inherited, so your parent most window must have that flag.
Interestingly it's not currently possible from BeginMainMenuBar(), etc.
As a test, does adding the _ShowBorders flag within `BeginMainMenuBar()` fixes it for you?

(The ShowBorders flag perhaps should maybe be retired/reworked it should be only part of style.)

**Comment by codz01** [comment]
>>As a test, does adding the _ShowBorders flag within BeginMainMenuBar() fixes it for you?
no , still  the same

**Comment by colesnicov** [comment]
https://github.com/ocornut/imgui/issues/1031

**Comment by ocornut** [comment]
@codz01 Pushed changes today so you can now freely alter the border size `style.FrameBorderSize` with e.g. `ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f)`. The ImGuiWindowFlags_ShowBorders flag has been completely obsoleted.

**Comment by codz01** [comment]
great , many thanks
