### ISSUE TITLE
How To Render Chat View

### ISSUE THREAD

**Issue by llxiaoyuan** [ocornut/imgui#8192]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_dx11.cpp + imgui_impl_dx11.cpp

### Compiler, OS:

win10

### Details:

**My Issue/Question:**

XXX _(please provide as much context as possible)_

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/6b9427b3-eb3d-42bd-9723-ccabd91bc219)
I want to render a chat window like this, which has a mix of text and emojis, but the emojis are not generic Unicode Emoji，Is there any method guidance 

### Minimal, Complete and Verifiable Example code:

```cpp

Maybe my text is like this


i am [[boy img]] ...   [[smile]]   




--------------------------------------------
// Add font, then register two custom 13x13 rectangles mapped to glyph 'a' and 'b' of this font
ImFont* font = io.Fonts->AddFontDefault();
int rect_ids[2];
rect_ids[0] = io.Fonts->AddCustomRectFontGlyph(font, 'a', 13, 13, 13+1);
rect_ids[1] = io.Fonts->AddCustomRectFontGlyph(font, 'b', 13, 13, 13+1);

// Build atlas
io.Fonts->Build();

// Retrieve texture in RGBA format
unsigned char* tex_pixels = nullptr;
int tex_width, tex_height;
io.Fonts->GetTexDataAsRGBA32(&tex_pixels, &tex_width, &tex_height);

for (int rect_n = 0; rect_n < IM_ARRAYSIZE(rect_ids); rect_n++)
{
    int rect_id = rect_ids[rect_n];
    if (const ImFontAtlasCustomRect* rect = io.Fonts->GetCustomRectByIndex(rect_id))
    {
        // Fill the custom rectangle with red pixels (in reality you would draw/copy your bitmap data here!)
        for (int y = 0; y < rect->Height; y++)
        {
            ImU32* p = (ImU32*)tex_pixels + (rect->Y + y) * tex_width + (rect->X);
            for (int x = rect->Width; x > 0; x--)
                *p++ = IM_COL32(255, 0, 0, 255);
        }
    }
}
------------------------------------------------------------
Can I replace strings ?  instead single char like 'a' 'b'
```

**Comment by ocornut** [comment]
> i am [[boy img]] ...   [[smile]]   
> Can I replace strings ?  instead single char like 'a' 'b'

No, you need you preprocess your text to replace markers with codepoints, or process your text chunk by chunk like a Markdown parser would do (https://github.com/ocornut/imgui/wiki/Useful-Extensions#rich-text--markdown).

Your question isn't much of a Dear ImGui question but is a general programming question, so best asked elsewhere.
