### ISSUE TITLE
How to stretch the height of the control

### ISSUE THREAD

**Issue by jackie-weiwei** [ocornut/imgui#8194]
### Version/Branch of Dear ImGui:

latest version

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx9.cpp

### Compiler, OS:

windows10 VS2022

### Full config/build information:

How to stretch the height of the control

### Details:

Why is there no setitemheight function? I want to implement a three-column layout. I want to put a Listbox in the first column. I want the height of this listbox to be equal to the height of the window. When the size of the window changes, the height of the Listbox automatically stretches to keep the same height as the window. How can I achieve this? I think it would be simpler and clearer if there was a setitemheight function. Request a solution. Like in flutter, I use an expand component to automatically fill the subcomponents to the height of the entire window. How can I implement imgui? In addition, what is the layout principle of imgui? Is there any relevant documentation?

**Comment by ocornut** [comment]
`BeginListBox()` has a size parameter. If you pass `(-FLT_MIN,-FLT_MIN)` to size it will be aligned to bottom and to right side of its parent window.

The Demo->Layout section explains many of the concepts used by dear imgui, but it's very different from flutter.

**Comment by jackie-weiwei** [comment]
imgui is the best UI framework I have found so far. In fact, I have been studying UI frameworks. I have some feelings during the use process, and I want to share them with you. First, about fonts, because I use a 4K screen, when I run it for the first time with Chinese, I find that the font is very blurry. I found that FreeType can be used through the help document, but when I open FreeType, the program cannot be compiled. Then I solved this problem by looking at the document. The next problem is that the program startup is obviously slow when using MSYH.TTC. Then I converted the font to font data and loaded the font through memory loading. The program startup did not load quickly. In addition, the font is clear only when I use dpiawarenees, but at this time the entire program does not perform dpi scale, which results in me needing to manually enlarge all controls in my program, including fonts. What I want to say is that if it is a UI framework, problems like this should be automatically handled within the framework. Instead of letting users consider the problem. Users should focus on the logic development of the program instead of considering framework issues.

**Comment by ocornut** [comment]
Please don't share random feedback in same issues. There are dozens/hundreds of issues discussing those topics.

I'm working on rework on font system to avoid need to preload all glyphs, so loading time for Chinese will be fixed in 1-2 months.

I am aware of those issues among many others. I don't have resources to fix everything in a timely manner.

**Comment by jackie-weiwei** [comment]
Why did you close the issue so quickly? If you have thousands of problems to solve, then that's your problem. Since you open sourced it, you should face it. This has nothing to do with me. You encapsulated such a rubbish code, and you still have the nerve to say there are thousands of problems. There is no design, no concept of software engineering, and it can only be regarded as a DEMO at best.
