### ISSUE TITLE
How to get a slider or input field to only return results once the user stops editing?

### ISSUE THREAD

**Issue by ekmett** [ocornut/imgui#820]
I have a direction in my editor that when edited takes something like half a second of background processing to adjust.

I'd like to have imgui change the value in place only once upon finishing edit, rather than as the user types, as otherwise my world stutters to a halt.

I can't quite figure out how to do this through the current API.

**Comment by ocornut** [comment]
Sorry it's not possible right now. The feature is planned and listed in https://github.com/ocornut/imgui/issues/701 but surprisingly more work than expected for some widgets (perhaps easier for regular Slider).

For text input you can however use `ImGuiInputTextFlags_EnterReturnsTrue` and check return value, but your underlying value will still be edited. You may work around with temporaries.

**Comment by ekmett** [comment]
I'm trying to figure out the right workflow to work around it with temporaries at least for the sun direction, which is a vec3. 

Right now I do something like:

```
gui::InputFloat3("sun", &uniforms.sun_dir.x, 2);
```

I can make a `temporary_sun_dir` or something, but it isn't clear to me how to know when to copy from the uniforms into the new temporary. Copying out seems straightforward enough.

**Comment by ekmett** [comment]
I think I have a hack.

**Comment by ocornut** [comment]
The hack I've been using recently is:

```
#include <imgui_internal.h>

bool ImGuiEx::IsItemActiveLastFrame()
{
    ImGuiContext& g = *GImGui;
    if (g.ActiveIdPreviousFrame)
        return g.ActiveIdPreviousFrame == g.CurrentWindow->DC.LastItemId;
    return false;
}

bool ImGuiEx::IsItemJustReleased()
{
	return IsItemActiveLastFrame() && !ImGui::IsItemActive();
}
```

```
ImGui::SliderFloat(..);
if (ImGuiEx::IsItemJustReleased()) ...
```

I might add and expose that function publicly to facilitate that sort of thing.

**Comment by ekmett** [comment]
That is a fair bit cleaner than my hack =)

**Comment by ocornut** [comment]
Reopening this issue as I would like to like to provide an official public implementation of it.

**Comment by ocornut** [comment]
@ekmett Reviving this old request, we now have a much better solution. See there:
https://github.com/ocornut/imgui/issues/1875#issuecomment-396752570
(Closing this topic as now redundant of 1875)
