### ISSUE TITLE
SDL2: unexpected color rgba mismatch?

### ISSUE THREAD

**Issue by achabense** [ocornut/imgui#8201]
### Version/Branch of Dear ImGui:

Version 1.91.2

### Back-ends:

imgui_impl_sdl2.cpp + imgui_impl_sdlrenderer2.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Full config/build information:

`#define IMGUI_USE_BGRA_PACKED_COLOR` in "imconfig.h".

### Details:

When RGBA-shifts are not the default ones, the rgba settings will not produce intended effects.
(May this because `ImGui_ImplSDLRenderer2_CreateFontsTexture` uses `SDL_PIXELFORMAT_ABGR8888` unconditionally?)

### Screenshots/Video:

(Using `ImGui::StyleColorsDark();` the style colors are generally affected.)
![image](https://github.com/user-attachments/assets/8bc546bd-ebdd-42ee-9604-9196b3790059)

### Minimal, Complete and Verifiable Example code:

```cpp
// In imconfig.h:
#define IMGUI_USE_BGRA_PACKED_COLOR
```

```cpp
// main.cpp
static void test_color() {
    ImGui::Begin("Test color");

    ImGui::TextColored(ImVec4(1, 0, 0, 1), "Red");
    ImGui::TextColored(ImVec4(0, 1, 0, 1), "Green");
    ImGui::TextColored(ImVec4(0, 0, 1, 1), "Blue");

    ImGui::End();
}
```

According to `ColorConvertFloat4ToU32`, ImVec4's x-y-z-w always means r-g-b-a, so I think the color changes are not intentional.

**Comment by ocornut** [comment]
`IMGUI_USE_BGRA_PACKED_COLOR` means the colors in ImDrawVtx will be packed differently, but the backend needs to also support it. Traditionally only the DX9 backend supports it because that's the native format for DX9.

Why would you need `IMGUI_USE_BGRA_PACKED_COLOR` ?

**Comment by achabense** [comment]
I was experimenting with `IM_COL32_X_SHIFT` and thought the order of RGBA can be specified arbitrarily, and found this. For my own use cases, I don't really need a different shift-setting.

**Comment by ocornut** [comment]
Then if you don't have a specific problem to solve I would rather close this, but I will add comment to explain this needs backend support, as this is currently unexplained indeed.

**Comment by ocornut** [comment]
Added comments: 70b6ba42. Let me know if you feel you need something else solved.
