### ISSUE TITLE
Can you add an optional custom field to the ImGuiWindow structure?

### ISSUE THREAD

**Issue by wusikijeronii** [ocornut/imgui#8208]
### Version/Branch of Dear ImGui:

Version 1.91.6, Branch: master

### Back-ends:

custom backend

### Compiler, OS:

Windows 11 + Clang 18.1.8

### Full config/build information:

I think it is too superfluous for my question

### Details:

Hello.
I dislike ImGui Dockspace. ImGui native docking uses the recursive approach. I prefer dockspace like Affinity Photo dockspace. You know when you have left to right sections and top to bottom nodes. I wrote my own dockspace. I want to prevent dropping for some non-docked windows (Drag'n'Drop external ImGui Windows).
Look to the example code. Here I check if the active window has my custom flag. Just I don't want to make a fork and change ImGui source code. I prefer to write imgui behavior as an extended layer over the library, but without changing it. 
I can write a wrapper for ImGui windows, but I think to refer to the wapper for every frame, it is too expensive. Can you add an optional custom field for custom flags for the `ImGuiWindow`? May be adding through the opt macro?
Now, I use child flags for extend window flags 'cos `ImGuiWindowFlags_` is fully filled.
```cpp
    enum ImGuiWindowFlagsExt_
    {
        ImGuiWindowFlagsExt_Docked = 1 << 10,
        ImGuiWindowFlagsExt_TabMenu = 1 << 11,
        ImGuiWindowFlagsExt_Stretch = 1 << 12,
        ImGuiWindowFlagsExt_NoDock = 1 << 13
    };
 ```
 After Begin():
 ```cpp
                 auto* window = ImGui::GetCurrentWindow();
                window->ChildFlags |= uikit::ImGuiWindowFlagsExt_Docked;
  ```
It works, but I think it isn't a good solution. May be tomorrow ImGui will change and `ImGuiChildFlags` will also be busied.

### Minimal, Complete and Verifiable Example code:

```cpp
        void Space::updateDragState(bool hovered, int si, int ni, bool is_content)
        {
            ImGuiContext &g = *GImGui;
            if (_hovered || _frame.flags & FrameStateFlagBits::resizing) return;
            if (ImGui::IsMouseDragging(ImGuiMouseButton_Left) && g.MovingWindow)
            {
                if (g.MovingWindow->ChildFlags & ImGuiWindowFlagsExt_NoDock) return; // here
                _frame.flags |= FrameStateFlagBits::dropped;
            }
            else if (_frame.flags & FrameStateFlagBits::dropped && hovered)
            {
                _frame.flags &= ~FrameStateFlagBits::dropped;
                if (g.NavWindow)
                    _e->dispatch<ChangeEvent>(is_content ? "ds:window_docked" : "ds:newtab", g.NavWindow->Name, si, ni);
            }
        }
```

**Comment by ocornut** [comment]
It's not possible presently. To make it possible for multiple extensions it would need a query of some sort, at which point you can do the "window => your data" query in your own data structures.

**Comment by wusikijeronii** [comment]
> It's not possible presently. To make it possible for multiple extensions it would need a query of some sort, at which point you can do the "window => your data" query in your own data structures.

Exactly. Need to provide API. You write as if it could be developed in the future. So, I'll leave this issue open. Maybe later...

**Comment by ocornut** [comment]
What I meant is you can perfectly write it on your side, you don't need imgui support for it.

- (A) imgui would need to use a "extension->extension data" map stored in window.
- (B) your extension can use a "window->extension data" in extension code.

You can use B.

**Comment by wusikijeronii** [comment]
Yeah, I've been thinking about that. That's what I used to call a wrapper. It just seems to me that if you address from the window side to the extension, it's a bit expensive per frame. The other thing is when you form a stack and put the window in there. You can put external data together with the window. But I don't control this directly from my side. To be honest, I wrote it because it seemed to me to be a useful feature for backend vendors first of all. That's why I decided to offer it.

**Comment by wusikijeronii** [comment]
I really misunderstood you. I read your message again. It is impossible and the solution is only on my side. Okay.
