### ISSUE TITLE
[Feature request] User defined OpenGL header

### ISSUE THREAD

**Issue by 1vanK** [ocornut/imgui#8214]
### Version/Branch of Dear ImGui:

master

### Back-ends:

imgui_impl_sdl3.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

VS 2022

### Details:

I use glad. I want to add `#include <glad/gl.h>` to `imgui_impl_opengl3.cpp` without modifying this file.
What about adding to `imgui_impl_opengl3.cpp`:

```
#ifdef GL_HEADER
#include GL_HEADER
#endif
```

This way I can specify the header file in my CMake config:

```
target_compile_definitions(${target_name} PUBLIC IMGUI_IMPL_OPENGL_LOADER_CUSTOM=1 GL_HEADER=<glad/gl.h>)
```

**Comment by ocornut** [comment]
> I use glad. I want to add #include <glad/gl.h> to imgui_impl_opengl3.cpp

You can use Glad in your app. You shouldn’t need to modify our backend, it uses its own loader. Why do you need the imgui backend to use Glad ?

**Comment by 1vanK** [comment]
I don't need the loader because opengl functions are already loaded. Why load them a second time?

**Comment by 1vanK** [comment]
I have imgui as a git submodule. hat's why I don't want to modify it. I just compile imgui to a static library and link to my application.

**Comment by 1vanK** [comment]
Or maybe add a define that will leave only prototypes in `imgui_impl_opengl3_loader.h` but disable loading

**Comment by ocornut** [comment]
> Why load them a second time?

Because it doesn’t take any meaningfully measurable time.
It’s looking up a symbol in an already loaded library.

There is zero issue as far as I know.
If you want to manufacture your own issues feel free to do so, but this is not a productive use of anyone’s time imho.

**Comment by 1vanK** [comment]
What was the idea behind having IMGUI_IMPL_OPENGL_LOADER_CUSTOM? It disables the header file but does not allow include another one.

**Comment by ocornut** [comment]
It was to allow compiling the backend in a same compilation unit.
You can probably include the cpp file in your other cpp file.

For years we tried to cater to people using varying loaders and it only created more issues and confusions for people.

**Comment by 1vanK** [comment]
![изображение](https://github.com/user-attachments/assets/805fb8a5-a14c-4917-a4e0-31260aaa7a0d)

Is there a way for Imgui to know when a redraw is required?

My idea is to redraw my app only when required and don't load the video card to 100%.
Of course I can limit the fps, but then a movement of windows will not be as smooth.

```
static bool need_redraw = true;

void App::handle_sdl_event(const SDL_Event& event)
{
    need_redraw = true;

    ImGui_ImplSDL3_ProcessEvent(&event);
}

void App::update(u64 ns)
{
     if (need_redraw)
     {
        ImGui_ImplOpenGL3_NewFrame();
        ImGui_ImplSDL3_NewFrame();
        ImGui::NewFrame();

        static bool show_demo_window = true;
        ImGui::ShowDemoWindow(&show_demo_window);
    }
}

void App::draw()
{
    if (!need_redraw)
        return;

    glClearColor(0x3a/255.f, 0x6f/255.f, 0xa5/255.f, 1.f);
    glClear(GL_COLOR_BUFFER_BIT);

    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    need_redraw = false;
}
```

This mostly works, but the problem is that the app redraws every time user move the mouse.

**Comment by 1vanK** [comment]
It also looks like ImGui doesn't draw anything on the first frame.

**Comment by 1vanK** [comment]
(This is not a game, but an application with several windows, so regular updating is not needed)

**Comment by 1vanK** [comment]
It mostly works, but I don't think it's very reliable

```
void App::update(u64 ns)
{
    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplSDL3_NewFrame();
    ImGui::NewFrame();

    static bool show_demo_window = true;
    ImGui::ShowDemoWindow(&show_demo_window);

    Uint32 mouse_state = SDL_GetMouseState(nullptr, nullptr);
    if (!(ImGui::IsWindowHovered(ImGuiHoveredFlags_AnyWindow) && mouse_state))
        SDL_Delay(25);
}
```

**Comment by ocornut** [comment]
Please don’t ask unrelated questions in an existing thread. There are half a dozen of threads discussing those things.
