### ISSUE TITLE
Right-align inputtext when clipped (was: Scroll InputText to the end)

### ISSUE THREAD

**Issue by 1vanK** [ocornut/imgui#8216]
### Version/Branch of Dear ImGui:

master

### Details:

Is it possible to automatically scoll TextInput to the end? It's more important for me to see the file name, not the beginning of the path to it.

![изображение](https://github.com/user-attachments/assets/1067b3d2-afe0-4869-bab8-d68c6609811e)

```
static StrUtf8 src_font_path = get_base_path() + "font_generator_data/fonts/ubuntu/Ubuntu-R.ttf";
ImGuiStyle& style = GetStyle();

Begin("Font");
StrUtf8 open_button_label = "...";
Text("File path");
PushItemWidth(-calc_button_width(open_button_label) - style.ItemSpacing.x);
InputText("##src_font_path", &src_font_path);
PopItemWidth();
SameLine();
Button(open_button_label.c_str());
ImGui::End();
```

**Comment by ocornut** [comment]
It's not currently possible. Duplicate of #4391. I hope to work on it in the following few months.

**Comment by ocornut** [comment]
This is now supported with `ImGuiInputTextFlags_ElideLeft` flag.
See https://github.com/ocornut/imgui/pull/1442#issuecomment-2528054644

**Comment by 1vanK** [comment]
Thanks!
