### ISSUE TITLE
Multi Select page question.

### ISSUE THREAD

**Issue by lailoken** [ocornut/imgui#8219]
### Version/Branch of Dear ImGui:

1.92.5

### Back-ends:

n/a

### Compiler, OS:

n/a

### Details:

On the Multi Select wiki:
https://github.com/ocornut/imgui/wiki/Multi-Select
There is the example line:
`selection.AdapterData = (void*)&items;`

should this be:
`selection.UserData = (void*)&items;`
?

(I don't see AdapterData)

**Comment by ocornut** [comment]
Thank you! I fixed the two occurrences of it now.
