### ISSUE TITLE
Child Window inside a List Box has a border by default

### ISSUE THREAD

**Issue by xezon** [ocornut/imgui#8220]
### Version/Branch of Dear ImGui:

Version 1.91.4, Branch: docking

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx9.cpp

### Compiler, OS:

Windows 10

### Details:

I have this code:

```cpp
...
    ImScoped::Child child1("file_list_container", ImVec2(0, 0), ImGuiChildFlags_None, ImGuiWindowFlags_None);
    if (child1.IsContentVisible)
    {
        ImGui::TextUnformatted("Select File");
        const float column_width = ImGui::GetContentRegionAvail().x;
        const float column_height = ImGui::GetContentRegionAvail().y;
        const ImVec2 size(column_width, column_height);
        ImScoped::ListBox list_box("file_list_box", size);

        if (list_box.IsContentVisible)
        {
            ImScoped::Child child2(
                "file_list_box_scroll",
                ImVec2(0, 0),
                ImGuiChildFlags_None,
                ImGuiWindowFlags_HorizontalScrollbar);
            if (child2.IsContentVisible)
            {
                ...
            }
        }
    }
...
```

It produces a list box and once the child2 is placed inside then it will have a border, eventhough the child2 does not specify window border or padding flags.

![listbox_child](https://github.com/user-attachments/assets/7a60e784-56b1-4f99-9587-308966b5d3cf)

**Comment by ocornut** [comment]
BeginListBox itself is a merely a very thin wrapper to calling BeginChild, so there's no reason for calling both nested.

`BeginListBox()` does more or less:
```cpp
BeginChild(id, size, ImGuiChildFlags_FrameStyle);
```

And FrameStyle uses FrameBorder, FramePadding, FrameBg, FrameRounding settings. 

> It produces a list box and once the child2 is placed inside then it will have a border, eventhough the child2 does not specify window border or padding flags.

The padding you are seeing is the padding of the parent listbox.
If you don't want your listbox to look this like you can call `BeginChild` directly. But I see no reason calling BOTH nested into each others.

**Comment by xezon** [comment]
Oh okay. I will try to merge these 2 and see if that fixes it. Thank you. I very much like ImGui :-) Have a nice day.

**Comment by xezon** [comment]
Ok. I created a copy of the original `ImGui::BeginListBox` and added the window flags arguments to then be able to pass the `ImGuiWindowFlags_HorizontalScrollbar` flag into its `BeginChild` call.

```
bool BeginListBoxEx(
    const char *label,
    const ImVec2 &size_arg = ImVec2(0, 0),
    ImGuiChildFlags child_flags = 0,
    ImGuiWindowFlags window_flags = 0);
{
...
    ImGui::BeginChild(id, frame_bb.GetSize(), child_flags | ImGuiChildFlags_FrameStyle, window_flags);
    return true;
}
```

This works.

![compare9](https://github.com/user-attachments/assets/996e8727-b25a-4c7e-bb5a-29564abe2778)

**Comment by ocornut** [comment]
The contents of BeginListBox() is only useful to display a label. if you don't use a label (you are not using one in your screenshot) you can just call BeginChild() directly.

**Comment by xezon** [comment]
Ok thanks, then I will simplify this further as you have advised.

**Comment by ocornut** [comment]
I have added comments to clarify this. Closing as hopefully answered!
