### ISSUE TITLE
Main menu bar contents doesnt get shown on linux

### ISSUE THREAD

**Issue by Gamer069** [ocornut/imgui#8224]
### Version/Branch of Dear ImGui:

Version 1.91.6, Branch: docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Arch linux, XFCE with SDDM

### Details:

**My Issue/Question:**

Recently I've been making an app with ImGui.
For some reason though, the menu bar perfectly worked on macOS, but didn't in linux.
By didn't work, i mean it did render, and it does show the menu bar item hover style.
But, upon clicking a menu, it didnt show the menu's contents, and stopped detecting hovers.
It worked perfectly on macOS, but didn't on linux.

### Minimal, Complete and Verifiable Example code:

```cpp
if (ImGui::BeginMainMenuBar()) {
    if (ImGui::BeginMenu("Test")) {
        if (ImGui::MenuItem("Test item")) {
            std::cout << "Test item clicked" << std::endl;
        }    
    }
}
```

# EDIT: this example code works... idk what causes the issue and my project is too big to paste here...

**Comment by ocornut** [comment]
Please work toward a repro as explained in issue submitting guidelines, and then we can reopen the issue. Thanks.
