### ISSUE TITLE
Text filters do not work correctly with pasted text

### ISSUE THREAD

**Issue by TheBrokenRail** [ocornut/imgui#8229]
### Version/Branch of Dear ImGui:

`551b6c4d662a3938f0cd197e79cc29922feec1ff` (on `master`)

### Back-ends:

`imgui_impl_glfw.cpp` + `imgui_impl_opengl2.cpp`

### Compiler, OS:

Linux + GCC + Wayland

### Details:

**My Issue/Question:**

When copying text into an `InputText`, filtering (with `ImGuiInputTextFlags_CallbackCharFilter` or the built-in filters) only partially works.

Blocking certain characters entirely works fine. If you try to paste text into the `"imgui"` text field in the demo, only the allowed characters are inserted.

The issue is that transforming characters does not work. For instance, if I type `a` into the `uppercase` text field in the demo, it gets turned into `A`. However, if I paste `a` into the field, it stays lowercase.

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/5e11fc8a-1637-48ce-b035-fca07c38cfc8)

### Minimal, Complete and Verifiable Example code:

This can be reproduced with the `Filtered Text Input` section in the demo.

**Comment by ocornut** [comment]
Thank you for reporting this. I have pushed a fix f5f11e9!
