### ISSUE TITLE
Help with tabs

### ISSUE THREAD

**Issue by DadLine757** [ocornut/imgui#8230]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: XXX (master/docking/etc.)

### Back-ends:

imgui_impl_XXX.cpp + imgui_impl_XXX.cpp

### Compiler, OS:

Macos

### Full config/build information:

Hello. How to make it so that when you click on the button, that is, when you open the first tab, the content is shown, but when you open the second tab, the content of the first one is hidden?

In my code, it's just like that:

static int Tab = 0;
static int Tab2 = 0;

if (ImGui::Button(“Tab1”, ImVec2(140,40)))
{
Tab = 1;
}

if (Tab == 1) {
ImGui::Checkbox(“Tab1”, &tab1);
}

And also with the second tab only not Tab a Tab2

### Details:

**My Issue/Question:**

XXX _(please provide as much context as possible)_

### Minimal, Complete and Verifiable Example code:

```cpp
// Here's some code anyone can copy and paste to reproduce your issue

static int Tab = 0;
static int Tab2 = 0;

if (ImGui::Button(“Tab1”, ImVec2(140,40)))
{
Tab = 1;
}

if (Tab == 1) {
ImGui::Checkbox(“Tab1”, &tab1);
}

```

**Comment by ocornut** [comment]
> And also with the second tab only not Tab a Tab2

Well that's your problem. If you want to emulate tabs with buttons, store 1 value which is the currently selected tab index.

```cpp
static int Tab = 1;
if (ImGui::Button(“Tab1”, ImVec2(140,40)))
   Tab = 1;
if (ImGui::Button(“Tab2”, ImVec2(140,40)))
   Tab = 2;
if (Tab == 1) {
// display tab 1
}
if (Tab == 2) {
// display tab 2
}
```

However, it feels odds to be using buttons for that when there's a dedicated API for tabs, BeginTabBar(), BeginTabItem() etc. see Demo window under Widgets->Tabs.
