### ISSUE TITLE
Nav: Pressing Alt deactivates widget when nav inputs are disabled with ImGuiWindowFlags_NoNavInputs

### ISSUE THREAD

**Issue by petrihakkinen** [ocornut/imgui#8231]
### Version/Branch of Dear ImGui:

Version 1.91.7 (WIP), Branch: master

### Back-ends:

imgui_impl_win32.cpp + imgui_impl_dx10.cpp

### Compiler, OS:

Windows 10 + MSVC 2022

### Full config/build information:

```
Dear ImGui 1.91.7 WIP (19161)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1941
define: _MSVC_LANG=201402
--------------------------------
io.BackendPlatformName: imgui_impl_win32
io.BackendRendererName: imgui_impl_dx10
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigNavCaptureKeyboard
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.DisplaySize: 1264.00,761.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

An ImGui window that sets the ImGuiWindowFlags_NoNavInputs flag still reacts to Alt being pressed by deactivating the current widget. I would expect all nav inputs (including Alt) to be disabled in this case.

Repro: open the demo window and check "No nav" in Window options. Click any input text box. Press Alt and observe that the widget is deactivated.

**Comment by ocornut** [comment]
Hello,
Thanks for your report. I have pushed a fix: 13c4084

Please note that there is now an input ownership/routing mechanism, so I am curious to know about the particular reason you may be using `ImGuiWindowFlags_NoNavInputs`, because specific nav keys/features can also be disabled via this mechanism.

**Comment by petrihakkinen** [comment]
That was fast, thank you! :)

This is a rather large codebase with ~50 places where ImGuiWindowFlags_NoNav / ImGuiWindowFlags_NoNavInputs is used. From the top of my head it's hard to say what are the reasons for disabling nav, but I suspect there are historical reasons. We are also running a few releases behind.

**Comment by ocornut** [comment]
Added a basic test for it too https://github.com/ocornut/imgui_test_engine/commit/f881a75ec1361520dc539f6edee357adbe036b0e
