### ISSUE TITLE
Using MultiSelect for entire rows in a Table with various kinds of items

### ISSUE THREAD

**Issue by bratpilz** [ocornut/imgui#8232]
### Version/Branch of Dear ImGui:

Version 1.91.7 WIP (19161), Branch: master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Linux + GCC 12.2.0

### Full config/build information:

```
Dear ImGui 1.91.7 WIP (19161)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=201103
define: __linux__
define: __GNUC__=12
--------------------------------
io.BackendPlatformName: imgui_impl_glfw
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigNavCaptureKeyboard
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000000E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.DisplaySize: 1280.00,720.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**My Issue/Question:**

Hello! I have a table where each row corresponds to a certain data record and the user can configure different columns, some of which contain text, some contain buttons or even things like InputTexts or custom items.
I also want to support mass operations on the displayed data records, like selecting 10 rows (or even all rows via Ctrl+A) and then pressing a button to perform an operation on all of them at once.

Is there a way to make MultiSelect work for this use case? Currently I can only associate MultiSelect user data for individual items via SetNextItemSelectionUserData. If there was a function SetNextTableRowSelectionUserData, that would be exactly what I need. But if that's a lot of work to implement, could I maybe instead try to place a dummy item over each row after it is done and then use SetNextItemSelectionUserData as normal? In that case, I could see there being issues with still being able to interact with the actual items in the table though. 

I've attached some test code and a video showing the current situation. Here I'm simply calling SetNextItemSelectionUserData for the Selectable in the first Table column. This means that MultiSelect of course only works when the selection rectangle overlaps the first column. Furthermore, the selection rectangle doesn't show up at all until the first time that I start to drag from one of the first column Selectables, as shown in the beginning of the video.

### Screenshots/Video:

https://github.com/user-attachments/assets/5310dfbd-f483-4537-9e9c-1f3df78e95fd

### Minimal, Complete and Verifiable Example code:

```cpp
        {
	  using namespace ImGui;
	  SetNextWindowSize (ImVec2 (400.0f, 300.0f), ImGuiCond_Appearing);
	  Begin ("Test");
	  if (BeginTable ("Table", 3, ImGuiTableFlags_Borders | ImGuiTableFlags_ScrollX | ImGuiTableFlags_ScrollY))
	    {
	      static ImGuiSelectionBasicStorage selection;
	      static unsigned const N = 1000;
	      auto ms = BeginMultiSelect (ImGuiMultiSelectFlags_BoxSelect1d, selection.Size, N);
	      selection.ApplyRequests (ms);
	      for (unsigned i = 0; i < N; ++i)
		{
		  char buf[32];
		  snprintf (buf, sizeof buf, "Selectable %03d", i);
		  TableNextColumn();
		  SetNextItemSelectionUserData (i); // I would like to set this for the whole table row instead of just this one item.
		  Selectable (buf, selection.Contains (i));
		  snprintf (buf, sizeof buf, "Button %03d", i);
		  TableNextColumn();
		  SmallButton (buf);
		  TableNextColumn();
		  Text ("Text %03d Bla bla bla", i);
		}
	      ms = EndMultiSelect();
	      selection.ApplyRequests (ms);
	      EndTable();
	    }
	  End();
        }
```

**Comment by ocornut** [comment]
Hello,

You can pass `ImGuiSelectableFlags_SpanAllColumns` to your call to `Selectable()` exactly for this purpose, as demonstrated in the Tables demos.

It's also a common idiom to submit a selectable with an empty label, e.g. `Selectable("##row", ..., ImGuiSelectableFlags_SpanAllColumns)` in case you don't need a selectable in your first column. Technically your should submit the selectable in the first visible column.

**Comment by bratpilz** [comment]
I had somehow missed that part of the demo, thanks for pointing me in that direction!
Normally I don't have a Selectable in any of the columns, but it indeed works to do the following in the first visible column:
```cpp
Selectable (buf, sel, ImGuiSelectableFlags_SpanAllColumns | ImGuiSelectableFlags_AllowOverlap, sel_size);
SameLine (FLT_MIN, 0.0f); // Do actual cell content after this.
```
When there are rows of different heights, the height needs to be known in advance for this option though.
But I managed to get around that too, by first submitting all actual items of the row, calling TableEndCell to ensure that RowPosY1 and RowPosY2 are set, and then calculating the Selectable's height via RowPosY2 - RowPosY1 (minus cell padding etc.). Of course this is only possible when #including imgui_internal.h. But in this case, it is also not necessary to use ImGuiSelectableFlags_AllowOverlap, since the Selectable is always the last item in the row. Here's a summary of this other option:
```cpp
	      static ImGuiSelectionBasicStorage selection;
	      static unsigned const N = 1000;
	      for (unsigned i = 0; i < N; ++i)
		{
		  char buf[32];

		  // [...] Do actual row items.

		  auto table = GetCurrentTable();
		  TableEndCell (table); // In case there is only one column.
		  TableSetColumnIndex (0); // Make sure we are within a column for the Selectable. Not sure if this is necessary.
		  snprintf (buf, sizeof buf, "##Selectable %03d", i);
		  bool sel = selection.Contains (i);
		  SetNextItemSelectionUserData (i);
		  ImVec2 sel_size (0.0f, table->RowPosY2 - table->RowPosY1 - 2.0f * table->RowCellPaddingY - 2.0f); // Not sure if this calculation is correct, but it seems to work well.
		  SetCursorScreenPos (ImVec2 (GetCursorScreenPos().x, table->RowPosY1));
		  Selectable (buf, sel, ImGuiSelectableFlags_SpanAllColumns, sel_size);
		  TableNextRow();
		}
```
Works like a charm:

https://github.com/user-attachments/assets/34428461-8f13-488c-a386-fc2b53745ce8

**Comment by ocornut** [comment]
> When there are rows of different heights, the height needs to be known in advance for this option though. But I managed to get around that too,

It would seem easier to compute that height ahead of time and submit the selectable first. But good you worked it out.
