### ISSUE TITLE
Vulkan Backend: Cleanup/Shutdown Problem

### ISSUE THREAD

**Issue by ymozer** [ocornut/imgui#8234]
### Version/Branch of Dear ImGui:

Version  1.91.7, Branch: master

### Back-ends:

imgui_impl_vulkan.cpp + imgui_impl_glfw.cpp

### Compiler, OS:

Windows 11, CMake, MSBuild

### Details:

**Cleanup/Shutdown Problem on Vulkan Backend**
In ImGui_ImplVulkan_RemoveTexture()  vkFreeDescriptorSets(v->Device, pool, 1, &descriptor_set); function execution gives following validation errors:

``` bash
Validation Error: [ VUID-vkFreeDescriptorSets-descriptorPool-parameter ] Object 0: handle = 0x21395738e30, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0xfc0204f1 | vkFreeDescriptorSets(): descriptorPool Invalid VkDescriptorPool Object 0x4b7df1000000002f.
The Vulkan spec states: descriptorPool must be a valid VkDescriptorPool handle (https://vulkan.lunarg.com/doc/view/1.3.296.0/windows/1.3-extensions/vkspec.html#VUID-vkFreeDescriptorSets-descriptorPool-parameter)
Validation Error: [ VUID-vkFreeDescriptorSets-pDescriptorSets-00310 ] Object 0: handle = 0x210d07000000003a, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x7cd4a2da | vkFreeDescriptorSets(): pDescriptorSets[0] Invalid VkDescriptorSet 0x210d07000000003a[].
The Vulkan spec states: pDescriptorSets must be a valid pointer to an array of descriptorSetCount VkDescriptorSet handles, each element of which must either be a valid handle or VK_NULL_HANDLE (https://vulkan.lunarg.com/doc/view/1.3.296.0/windows/1.3-extensions/vkspec.html#VUID-vkFreeDescriptorSets-pDescriptorSets-00310)
Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x4b7df1000000002f, type = VK_OBJECT_TYPE_DESCRIPTOR_POOL; | MessageID = 0x5d6b67e2 | vkFreeDescriptorSets():  Couldn't find VkDescriptorPool Object 0x4b7df1000000002f. This should not happen and may indicate a bug in the application.
Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x210d07000000003a, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x5d6b67e2 | vkFreeDescriptorSets():  Couldn't find VkDescriptorSet Object 0x210d07000000003a. This should not happen and may indicate a bug in the application.
Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x4b7df1000000002f, type = VK_OBJECT_TYPE_DESCRIPTOR_POOL; | MessageID = 0x5d6b67e2 | vkFreeDescriptorSets():  Couldn't find VkDescriptorPool Object 0x4b7df1000000002f. This should not happen and may indicate a bug in the application.
Validation Error: [ UNASSIGNED-Threading-Info ] Object 0: handle = 0x210d07000000003a, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0x5d6b67e2 | vkFreeDescriptorSets():  Couldn't find VkDescriptorSet Object 0x210d07000000003a. This should not happen and may indicate a bug in the application.
```
If I comment it out `vkFreeDescriptorSets` it works fine. I don't know if it can caused by my app code but I doubt so.

**Comment by GamingMinds-DanielC** [comment]
> I don't know if it can caused by my app code but I doubt so.

If you build and run the matching example app (see `imgui/examples/example_glfw_vulkan/`), do you get validation errors as well?

**Comment by ymozer** [comment]
No, I don't. Do you have any idea why it behaves like this?

**Comment by ocornut** [comment]
Well maybe you are destructing your pool before calling the backend Shutdown function. But you are not providing any details nor repro - as requested by issue submitting guidelines - so we can only guess.

**Comment by GamingMinds-DanielC** [comment]
The example app not having this error strongly suggests that the problem is somewhere in your application. Impossible to pinpoint without any sources.

Did you build your initialization and shutdown handling and your main loop yourself? If yes, you need to compare that with the example sources and look closer where you do things differently. Did you start with a copy of the example sources as a base and modify from there? Then one of your modifications might be the issue. If it isn't or if you didn't make modifications, you probably have an outdated base. Depending on how much you changed or build yourself, you could update the base or look at the differences between an old version of the example app (from around when you first made your application) and the current one and then port those differences into your app.

**Comment by ymozer** [comment]
I was able to resolve the issue, which was caused by a confusing order of function destruction. I didn't think that I should destuct the pool after the backend shutdown. I will examine examples in detail from now on. Thank you both for your support and for this fantastic library. You guys are awesome!

**Comment by hughes** [comment]
The specific solution to the descriptorPool error is to make sure you set the descriptor set flag (from the [example](https://github.com/ocornut/imgui/blob/b23a216ecddedcc1bf3c1241b5428d39399b622a/examples/example_glfw_vulkan/main.cpp#L200)):

```
pool_info.flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT
```
