### ISSUE TITLE
Error with multiple windows & imgui contexts

### ISSUE THREAD

**Issue by GitJVGuinot** [ocornut/imgui#8236]
### Version/Branch of Dear ImGui:

Version 1.91.6, Branch Docking

### Back-ends:

Custom

### Compiler, OS:

Windows 11 MSVC 2022

### Full config/build information:

Compiler line for all files: cl /nologo /EHsc /Ox /W4 /WX /MT /std:c++20 /c /I..\..\include /I..\..\deps\include /IC:\VulkanSDK\1.3.283.0\Include /IC:\OpenAL_1.1_SDK\include /DNDEBUG /D_NDEBUG /D_REENTRANT /D_THREAD_SAFE file.cpp /Fo: obj_folder/file.obj

### Details:

I'm making alittle vulkan engine. This need to have multiple windows so each window has it's own vulkan surface, glfw window and imgui context.
But for some reason the inputs, which I don't know if they can have a specific context per glfw window, when I try to move/amplify, or touch something in the imgui window it is as if the inputs were taken by the last window to be rendered.

Sorry for the video size. Each window is named by the render order.
Int he next scheme i use glfw one for global frame. But i also tried to use one for each window frame and is the same.
On the other hand, glfw correctly obtains the inputs per screen.

frame while
  glfwPollEvents (Call once every frame)
  for each window update (3)
    glfw window frame start
    imgui frame start
    window stuff (Camer, model......)
    vulkan begin (to get command buffer)
    scene render
    imgui render
    vulkan end
    glfw window refresh

### Screenshots/Video:

https://github.com/user-attachments/assets/9ca4421f-3bad-45ee-b28f-fa4f51ea2111

### Minimal, Complete and Verifiable Example code:

```cpp
 /// @author F.c.o Javier guinot Almenar <whitewholffox@gmail.com>
#include "jvlke/ui/imgui.hpp"

#include "jvlke/render/swapchain.hpp"
#include "jvlke/gpu/device.hpp"
#include "jvlke/utils/logger.hpp"

#include "imgui/imgui.h"
#include "imgui/imgui_impl_glfw.h"
#include "imgui/imgui_impl_vulkan.h"

namespace jvlke
{
  namespace ui
  {
    struct Imgui::Data
    {
      VkDescriptorPool descriptor_pool_ = VK_NULL_HANDLE;
      VkRenderPass render_pass_ = VK_NULL_HANDLE;

      ImGuiContext *context_ = nullptr; // One for each windwo
      ImGuiIO *io_ = nullptr; // Seems to be global

      GLFWwindow *window_ = nullptr;

      std::weak_ptr<gpu::Device> device_ = {};
    };

    Imgui::Imgui() {}

    void Imgui::init(std::weak_ptr<render::Viewer> viewer, std::weak_ptr<gpu::Device> device, VkInstance instance)
    {
      if (data_)
        return;

      data_ = std::make_shared<Imgui::Data>();
      data_->device_ = device;
      data_->window_ = viewer.lock()->getWindow().lock()->getWindowPtr();

      // Crear contexto ImGui
      /////////////////////////////////////////////////////////////////////////
      IMGUI_CHECKVERSION();
      glfwMakeContextCurrent(data_->window_);
      data_->context_ = ImGui::CreateContext();
      ImGui::SetCurrentContext(data_->context_);
      data_->io_ = &ImGui::GetIO();
      (void)data_->io_;

      // Inicializar backend de GLFW
      if (!ImGui_ImplGlfw_InitForVulkan(data_->window_, true))
      {
        LOG_ERROR("Imgui GLFW initialization failed");
        this->free();
        return;
      }
      /////////////////////////////////////////////////////////////////////////

      // Crear descriptor pool para este contexto
      /////////////////////////////////////////////////////////////////////////
      VkDescriptorPoolSize pool_sizes[1] = {
          {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1},
      };
      VkDescriptorPoolCreateInfo pool_info = {};
      pool_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
      pool_info.flags = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT;
      pool_info.maxSets = 1;
      pool_info.poolSizeCount = (uint32_t)(sizeof(pool_sizes) / sizeof(*pool_sizes));
      pool_info.pPoolSizes = pool_sizes;

      if (vkCreateDescriptorPool(data_->device_.lock()->getDevice(), &pool_info, nullptr, &data_->descriptor_pool_) != VK_SUCCESS)
      {
        LOG_ERROR("Failed to create descriptor pool for Imgui");
        this->free();
        return;
      }
      /////////////////////////////////////////////////////////////////////////

      // Crear render pass para este contexto
      /////////////////////////////////////////////////////////////////////////
      VkAttachmentDescription colorAttachment = {};
      colorAttachment.format = viewer.lock()->getRender().lock()->getSwapChainFormat();
      colorAttachment.samples = VK_SAMPLE_COUNT_1_BIT;
      colorAttachment.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;
      colorAttachment.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
      colorAttachment.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
      colorAttachment.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
      colorAttachment.initialLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
      colorAttachment.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;

      // Configurar referencia para el color attachment
      VkAttachmentReference colorAttachmentRef = {};
      colorAttachmentRef.attachment = 0;
      colorAttachmentRef.layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;

      // Configurar descripción del depth attachment
      VkAttachmentDescription depthAttachment = {};
      depthAttachment.format = viewer.lock()->getRender().lock()->getSwapChainDepthFormat();
      depthAttachment.samples = VK_SAMPLE_COUNT_1_BIT;
      depthAttachment.loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
      depthAttachment.storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
      depthAttachment.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
      depthAttachment.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
      depthAttachment.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
      depthAttachment.finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

      // Configurar referencia para el depth attachment
      VkAttachmentReference depthAttachmentRef = {};
      depthAttachmentRef.attachment = 1;
      depthAttachmentRef.layout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

      // Configurar subpass para usar el depth attachment
      VkSubpassDescription subpass = {};
      subpass.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
      subpass.colorAttachmentCount = 1;
      subpass.pColorAttachments = &colorAttachmentRef;
      subpass.pDepthStencilAttachment = &depthAttachmentRef;

      // Configurar dependencias para garantizar las transiciones de layouts
      VkSubpassDependency dependency = {};
      dependency.srcSubpass = VK_SUBPASS_EXTERNAL;
      dependency.dstSubpass = 0;
      dependency.srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
      dependency.srcAccessMask = 0;
      dependency.dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
      dependency.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;

      // Crear el render pass con color y depth attachments
      std::vector<VkAttachmentDescription> attachments = {colorAttachment, depthAttachment};

      VkRenderPassCreateInfo renderPassInfo = {};
      renderPassInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO;
      renderPassInfo.attachmentCount = static_cast<uint32_t>(attachments.size());
      renderPassInfo.pAttachments = attachments.data();
      renderPassInfo.subpassCount = 1;
      renderPassInfo.pSubpasses = &subpass;
      renderPassInfo.dependencyCount = 1;
      renderPassInfo.pDependencies = &dependency;

      // Crear el render pass
      if (vkCreateRenderPass(device.lock()->getDevice(), &renderPassInfo, nullptr, &data_->render_pass_) != VK_SUCCESS)
      {
        LOG_ERROR("Failed to create ImGui render pass with depth attachment");
        this->free();
        return;
      }
      /////////////////////////////////////////////////////////////////////////

      // Configuración del backend (Vulkan)
      /////////////////////////////////////////////////////////////////////////
      ImGui_ImplVulkan_InitInfo init_info = {};
      init_info.Instance = instance;
      init_info.PhysicalDevice = device.lock()->getPhysicalDevice();
      init_info.Device = device.lock()->getDevice();
      init_info.QueueFamily = device.lock()->getQueueFamilyIndices().graphics_family_;
      init_info.Queue = device.lock()->getGraphicsQueue();
      init_info.DescriptorPool = data_->descriptor_pool_;
      init_info.RenderPass = data_->render_pass_;
      init_info.MinImageCount = render::SwapChain::MAX_FRAMES_IN_FLIGHT;
      init_info.ImageCount = (uint32_t)(viewer.lock()->getRender().lock()->getImageCount());
      init_info.CheckVkResultFn = [](VkResult err)
      {
        if (err != VK_SUCCESS)
          LOG_ERROR(("Vulkan error: " + std::to_string(err)).c_str());
      };

      if (!ImGui_ImplVulkan_Init(&init_info))
      {
        LOG_ERROR("ImGui Vulkan initialization failed");
        this->free();
        return;
      }
      /////////////////////////////////////////////////////////////////////////
    }

    void Imgui::free()
    {
      if (!data_)
        return;

      ImGui::SetCurrentContext(data_->context_);
      ImGui_ImplGlfw_Shutdown();
      ImGui_ImplVulkan_Shutdown();
      ImGui::DestroyContext(data_->context_);

      if (data_->descriptor_pool_ != VK_NULL_HANDLE)
        vkDestroyDescriptorPool(data_->device_.lock()->getDevice(), data_->descriptor_pool_, nullptr);

      if (data_->render_pass_ != VK_NULL_HANDLE)
        vkDestroyRenderPass(data_->device_.lock()->getDevice(), data_->render_pass_, nullptr);

      data_.reset();
    }

    Imgui::~Imgui()
    {
      if (data_)
      {
        LOG_WARNING("Calling ui::Imgui::free in ui::Imgui::destructor, some error could occur");
        this->free();
      }
    }

    void Imgui::frameStart()
    {
      if (!data_ || !data_->context_)
        return;

      glfwMakeContextCurrent(data_->window_);
      ImGui::SetCurrentContext(data_->context_);
      ImGui_ImplGlfw_NewFrame();
      ImGui_ImplVulkan_NewFrame();
      ImGui::NewFrame();
    }

    void Imgui::render(VkCommandBuffer command_buffer)
    {
      if (!data_ || !data_->context_)
        return;

      glfwMakeContextCurrent(data_->window_);
      ImGui::SetCurrentContext(data_->context_);
      ImGui::Render();

      ImDrawData *draw_data = ImGui::GetDrawData();
      if (draw_data && draw_data->DisplaySize.x > 0 && draw_data->DisplaySize.y > 0)
        ImGui_ImplVulkan_RenderDrawData(draw_data, command_buffer);
    }

  } /* ui */
} /* jvlke */
```

**Comment by GamingMinds-DanielC** [comment]
Sounds like your problem lies with `glfwPollEvents()` only having the last set context to work with. There is a code comment in the backend source that outlines a possible solution:
https://github.com/ocornut/imgui/blob/13c4084362b35ce58a25be70b9f1710dfe3377e9/backends/imgui_impl_glfw.cpp#L175-L185

Your call to `ImGui_ImplGlfw_InitForVulkan()` registers the default callbacks that are not prepared for multiple contexts. You can use the implementation of `ImGui_ImplGlfw_InstallCallbacks()` as a reference to how to register your own callbacks.

**Comment by GitJVGuinot** [comment]
So there is no possibility of using imgui with multiple windows. Can I only have 1 general context and use imgui in the window which has been used to generate said context?

As far as I know, glfwPolEvents() collects the input from all windows, yes. But when you call glfwgetKey() or glfwGetMouseButton()... they return exclusively the one from the active GLFW context. I don't know how it works below imgui, but there should be some way to do it, right?

**Comment by ocornut** [comment]
Err Daniel gave you the answer to solve it and it didn’t seem like you read it.

**Comment by GitJVGuinot** [comment]
> Err Daniel gave you the answer to solve it and it didn’t seem like you read it.

I just made it and doesn't seem to work that solution.
 The callbacks
Imgui detect the cursor but not the inputs. Maybe i'm doing something bad...
´´´c
    void Window::focusCallback(int focused)
    {
      LOG_DEBUG("Called focus call back");
      focused = (bool)(focused);
      ImGui_ImplGlfw_WindowFocusCallback(data_->window_, focused);
    }

    void Window::cursorEnterCallback(int entered)
    {
      LOG_DEBUG("Called cursor enter call back");
      if (data_->focused_)
        ImGui_ImplGlfw_CursorEnterCallback(data_->window_, entered);
    }

    void Window::cursorPosCallback(double x_pos, double y_pos)
    {
      LOG_DEBUG("Called cursor pos call back");
      if (data_->focused_)
        ImGui_ImplGlfw_CursorPosCallback(data_->window_, x_pos, y_pos);
    }

    void Window::mouseButtonCallback(int button, int action, int mods)
    {
      LOG_DEBUG("Called mouse button call back");
      if (data_->focused_)
        ImGui_ImplGlfw_MouseButtonCallback(data_->window_, button, action, mods);
    }

    void Window::scrollCallback(double x_offset, double y_offset)
    {
      LOG_DEBUG("Called scroll call back");
      data_->mouse_scroll_.x = (float)(x_offset);
      data_->mouse_scroll_.y = (float)(y_offset);
      if (data_->focused_)
        ImGui_ImplGlfw_ScrollCallback(data_->window_, x_offset, y_offset);
    }

    void Window::keyCallback(int key, int scancode, int action, int mods)
    {
      LOG_DEBUG("Called key call back");
      if (data_->focused_)
        ImGui_ImplGlfw_KeyCallback(data_->window_, key, scancode, action, mods);
    }

    void Window::charCallback(unsigned codepoint)
    {
      LOG_DEBUG("Called char call back");
      if (data_->focused_)
        ImGui_ImplGlfw_CharCallback(data_->window_, codepoint);
    }            
           
 void Window::initGLFWFunctions()          
{
       glfwSetWindowFocusCallback(data_->window_, [](GLFWwindow *window, int focused)
                                 { ((Window *)(glfwGetWindowUserPointer(window)))->focusCallback(focused); });
      glfwSetCursorEnterCallback(data_->window_, [](GLFWwindow *window, int entered)
                                 { ((Window *)(glfwGetWindowUserPointer(window)))->cursorEnterCallback(entered); });
      glfwSetCursorPosCallback(data_->window_, [](GLFWwindow *window, double xpos, double ypos)
                               { ((Window *)(glfwGetWindowUserPointer(window)))->cursorPosCallback(xpos, ypos); });
      glfwSetMouseButtonCallback(data_->window_, [](GLFWwindow *window, int button, int action, int mods)
                                 { ((Window *)(glfwGetWindowUserPointer(window)))->mouseButtonCallback(button, action, mods); });
      glfwSetScrollCallback(data_->window_, [](GLFWwindow *window, double xoffset, double yoffset)
                            { ((Window *)(glfwGetWindowUserPointer(window)))->scrollCallback(xoffset, yoffset); });
      glfwSetKeyCallback(data_->window_, [](GLFWwindow *window, int key, int scancode, int action, int mods)
                         { ((Window *)(glfwGetWindowUserPointer(window)))->keyCallback(key, scancode, action, mods); });
      glfwSetCharCallback(data_->window_, [](GLFWwindow *window, unsigned codepoint)
                          { ((Window *)(glfwGetWindowUserPointer(window)))->charCallback(codepoint); });
                          
      }
      ´´´

**Comment by GamingMinds-DanielC** [comment]
> I just made it and doesn't seem to work that solution. The callbacks Imgui detect the cursor but not the inputs. Maybe i'm doing something bad...

From the code comment I quoted:
"..., set the current dear imgui context and then call our callbacks."

Setting the current context to the one associated to your window is the entire point of this solution. You are not doing this in your callbacks.

**Comment by GitJVGuinot** [comment]
Oh, i yet undertood it.
Thanks for all.
It fix. But now the error callback send me a invalid window ptr and i doesn't know why.
The solution was to install my own callbacks calling to imgui callbacks if the window was focussed.
See imgui_backend (GLFW) ImGui_ImplGlfw_InstallCallbacks function to know the neccesaries callbacks.
```c
    void Window::keyCallback(int key, int scancode, int action, int mods)
    {
      LOG_DEBUG("Called key call back");
      if (glfwGetWindowAttrib(data_->window_, GLFW_FOCUSED))
      {
        ImGui::SetCurrentContext(data_->imgui_context_);
        ImGui_ImplGlfw_KeyCallback(data_->window_, key, scancode, action, mods);
      }
    }
```
