### ISSUE TITLE
Proposal: Generic RAII for Backend Integration in ImGui

### ISSUE THREAD

**Issue by pinwhell** [ocornut/imgui#8237]
### Version/Branch of Dear ImGui:

master

### Back-ends:

Any

### Compiler, OS:

Default

### Full config/build information:

Default

### Details:

Guys... how about implementing generic `RAII` for basic backend aspects... for example: 
```cpp
namespace ImGui {
namespace RAII {

struct Frame {
    Frame() {
        NewFrame();
    }

    ~Frame() {
        Render();
    }
};

namespace Backend {

template<void (*NewFrame)()>
struct Frame {
    Frame() {
        NewFrame();
    }
};

template<void (*NewFrame)(), void (*RenderDrawData)(ImDrawData*)>
struct FrameWithRender : public Frame<NewFrame> {
    ~FrameWithRender() {
        RenderDrawData(GetDrawData());
    }
};

}  // namespace Backend

}  // namespace RAII
```

Then instantiating it... example:

```cpp
namespace ImGui {

using OpenGL2Frame = Backend::FrameWithRender<
    ImGui_ImplOpenGL2_NewFrame, ImGui_ImplOpenGL2_RenderDrawData>;

using Win32Frame = Backend::Frame<
    ImGui_ImplWin32_NewFrame>;

}
```

Using it would be as easy. as:

```cpp
int main() {
    while (/* condition */) {
        {
              Win32Frame imw32Frame;
              OpenGL2Frame imglFrame;
              ImGui::Frame imFrame;
              /*User Imgui Code Here*/
        }
        // Platform Present
    }
}
```

**Comment by PathogenDavid** [comment]
See https://github.com/ocornut/imgui/issues/2096 and https://github.com/ocornut/imgui/pull/2197 for existing discussions/implementation of using RAII patterns with Dear ImGui.

Personally I feel that your specific examples feel like RAII for the sake of RAII.

**Comment by ocornut** [comment]
Hello,
I am afraid I also only see negative aspects to your proposal. It doesn’t seem like a good idea. I’ll close this.
