### ISSUE TITLE
Rendering issue in my app (Transparent black widget)

### ISSUE THREAD

**Issue by siddharthuniv** [ocornut/imgui#824]
Hi,

A new user here. I just pulled the latest source and I'm using the opengl3 example as reference. I have Imgui working within my rendering engine. However, I see that the widget is a transparent black widget and the text is also black.
![image](https://cloud.githubusercontent.com/assets/7758521/18406483/66c88f80-76cb-11e6-917e-d3a533d2ad3a.png)
As you can see, the titlebar is also black.

I have checked to see if the font texture image is valid and i see a valid ID for it. The rendering code is exactly the same as in the example. I'm not sure if this has anything to do with texture itself. I'm guessing the texture is completely black.

Any suggestions on how i can debug this issue?

Thanks

**Comment by siddharthuniv** [comment]
I'm sorry, i forgot to mention my windowing system. I'm using opengl with win32, if that helps.

**Comment by hypernewbie** [comment]
are you uploading the texture correctly? I recommend using a frame debugger
such as renderdoc

**Comment by ocornut** [comment]
Your texture is probably ok as you can read the text. The problem may come from the blending state or shaders.

**Comment by hypernewbie** [comment]
Yep I was thinking the texture might have been fetched as A8, so alpha only.
is the vertex colour getting propagated correctly to the shader?

**Comment by siddharthuniv** [comment]
yup, that was it..the example code has io.Fonts->GetTexDataAsAlpha8(..). Any reason for this? I think this would confuse new comers.

I changed it to io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height) and glTexImage2D to have format as GL_RGBA and it started to work. 

Thanks hypernewbie, ocornut

**Comment by ocornut** [comment]
Well, it is correct to try to use only required memory rather than 4 times what's needed, but indeed for the casual end user it makes mixing shaders more confusing.

The OpenGL3 example was already using RGBA for exactly this reason, to favor ease to use rather than performances.. It is a bit unfortunate but perhaps the best thing to do. I'm making that change in the OpengL2 example as well and adding comments.

**Comment by siddharthuniv** [comment]
thanks ocornut!
