### ISSUE TITLE
ImGui::GetCurrentContext returns nullptr when linking to ImGui library

### ISSUE THREAD

**Issue by Platforming-Mayhem** [ocornut/imgui#8262]
### Version/Branch of Dear ImGui:

Version 1.XX, Branch: docking

### Back-ends:

imgui_impl_glfwcpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows 11, MSVC

### Details:

I've been creating ImGui as a static library on windows and calling functions from it within a shared library. Then that shared library links with my executable. So I've been statically linking to ImGui in the executable and the shared library, but I've been having this issue where ImGui::GetCurrentWindow() keeps returning null in the exe. How do I go about sharing my ImGuiContext across from my Dll to my exe?

### Screenshots/Video:

![image](https://github.com/user-attachments/assets/4ef55765-8e3f-4782-b965-74c65d132702)

**Comment by ocornut** [comment]
You need to call SetCurrentContext() on every DLL boundaries, as globals are not shared.

**Comment by Platforming-Mayhem** [comment]
That worked!
Thanks a bunch :)
