### ISSUE TITLE
Android EGL Context Loss handling

### ISSUE THREAD

**Issue by ZLangJIT** [ocornut/imgui#8263]
### Version/Branch of Dear ImGui:

master

### Back-ends:

OpenGL3 Android

### Compiler, OS:

CLANG NDK

### Details:

how can i deal with opengl context loss and recovering the imgui state ?

for example, saving and restoring all window positions, tab indications, check box select status, text content, ect

**Comment by ocornut** [comment]
OpenGL context state has nothing to do with the other states you are mentioning. Losing an OpenGL context shouldn’t magically lose other states.
