### ISSUE TITLE
PlotHistogram with negative values (and return value proposal)

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#828]
Hi.
I've just found out that ImGui::PlotHistogram(...) works better with positive values than with negative ones.
Here is an example:
```c++
static float TestData[6]={0.f,-4.f,3.f,-2.f,0.f,4.f};
ImGui::PlotHistogram("Histogram With Negative Values", TestData, 6, 0, "Test", -5.f, 5.f, ImVec2(0,80));
```
![selection_039](https://cloud.githubusercontent.com/assets/9608982/18440370/2251e032-7909-11e6-9bf4-305288c240c4.png)

It's not a great deal for me... I can live with this issue.
I was just wondering if there's something I'm missing or not...

Anyways... another thing:
Since ImGui::PlotHistogram(...) and ImGui::PlotLines(...) return void, and by hovering the mouse on the diagrams we can highlight a "sample", can't we just return an int with the "hovered sample" index (or -1) ?

**Comment by ocornut** [comment]
I don't understand, what "works better" with negative numbers? What's the issue?

> Since ImGui::PlotHistogram(...) and ImGui::PlotLines(...) return void, and by hovering the mouse on the diagrams we can highlight a "sample", can't we just return an int with the sample index ?

Yes-ish, though probably waiting for a better API e.g. #632 before adding short-term new stuff to it.

**Comment by Flix01** [comment]
>I don't understand, what "works better" with negative numbers? What's the issue?

That the base line is not at zero.

**Comment by ocornut** [comment]
Isn't that the whole point of passing a range? e.g. -5.0 +5.0 the zero line will be in the middle.
I'm not sure what you consider an issue, maybe I'm missing out on something.

**Comment by Flix01** [comment]
> Isn't that the whole point of passing a range? e.g. -5.0 +5.0 the zero line will be in the middle.
I'm not sure what you consider an issue, maybe I'm missing out on something.

No problem! I just thought that the histograms could be allowed to go downward too...
However I was mainly asking if I was missing something about it. So I can close this issue now.

**Comment by ocornut** [comment]
Aaah I see what you mean, that's a good point. If we revamp the API we should leave the option.

**Comment by Flix01** [comment]
Thanks!

**Comment by ocornut** [comment]
@Flix01 the change to support that by default is now committed.
