### ISSUE TITLE
Using InputFloat3 and GUI:SameLine() changes line positions

### ISSUE THREAD

**Issue by MINIONBOTS** [ocornut/imgui#829]
Hello,
there seems to be a tiny bug with the alignment that slipped in (not 100% sure when exactly, but must be within the last 1-2 months). (Kinda different syntax, using my lua bindings, but you'll get the point ;) )

```
GUI:Text("AAAA") GUI:SameLine(200) GUI:InputText("##dev0","12345)
GUI:Text("I Break Stuff Below") GUI:SameLine(200) GUI:InputFloat3( "##dev9", 111, 222, 333, 2)
GUI:Text("BBBB") GUI:SameLine(200) GUI:InputText("##dev1","12345)
GUI:Text("CCCC") GUI:SameLine(200) GUI:InputText("##dev2","12345)
```
Result looks like this:
![index](https://cloud.githubusercontent.com/assets/2842405/18464332/ae11495a-7990-11e6-8ac8-fbeef96560af.png)

So the moment I use InputFloat3, all lines below using SameLine(200) have a different line position than the ones above the InputFloat3. This was not the case 1-2 months ago. 

Thanks for a hint :)

**Comment by ocornut** [comment]
Please provide a repro in a language supported by ImGui.

**Comment by ocornut** [comment]
Broken by https://github.com/ocornut/imgui/commit/954c890c6782fda494a3ac36f3c5a591db584cf4

```
ImGui::Begin("Bug #829");
char buf[32] = "";
ImGui::Text("AAAA"); ImGui::SameLine(200); ImGui::InputText("##dev0", buf, 32);
ImGui::Text("I Break Stuff Below"); ImGui::SameLine(200); float v[3] = { 100,200,300 }; ImGui::InputFloat3( "##dev9", &v[0], 2);
ImGui::Text("BBBB"); ImGui::SameLine(200); ImGui::InputText("##dev1",buf, 32);
ImGui::Text("CCCC"); ImGui::SameLine(200); ImGui::InputText("##dev2",buf, 32);
ImGui::End();
```

**Comment by ocornut** [comment]
Should be fixed! Thanks for the report. 
Please be extra mindful to provide an actual working repro to save me time because I have to do it otherwise. Thanks.

**Comment by MINIONBOTS** [comment]
It is hard to provide a repo....since I use my lua bindings. But I see you found the bug. 
Thanks a lot for the super quick fix !!!
:)

**Comment by ocornut** [comment]
C++ compilers are free and the imgui examples compile on every major platforms!
