### ISSUE TITLE
How to use memory_editor_example?

### ISSUE THREAD

**Issue by PCPisChill** [ocornut/imgui#831]
In https://github.com/ocornut/imgui/wiki/memory_editor_example , how do you get char* mem_block for the draw function?

**Comment by ocornut** [comment]
That's the address of the memory you want to edit, it's up to up to provide it.

**Comment by stonedreamforest** [comment]
i cann't finding memoryeditor example in [imgui-demo-binaries-20190715.zip](http://www.dearimgui.org/binaries/imgui-demo-binaries-20190715.zip) now. @ocornut
