### ISSUE TITLE
Linker errors in "imgui_impl_dx11"?

### ISSUE THREAD

**Issue by TristanWLB** [ocornut/imgui#835]
So I've had no trouble getting ImGui up and running for DX9 but DX11 doesn't want to cooperate for some reason; I haven't modified the implementation file and I made sure to add ImGui to my includes yet the linker keeps throwing LNK2001s at me:
![lnk2001](https://cloud.githubusercontent.com/assets/3197578/18601845/0b037cb8-7c2b-11e6-873a-2b9e46b2abfa.png)
I apologize in advance if this is just me being dumb and forgetting something!

**Comment by TristanWLB** [comment]
I add the ImGui source files to my project which was causing the linker errors, just #including them didn't suffice; TIL.

**Comment by ocornut** [comment]
Well  here you aren't linking the output of imgui.cpp into your project. It has nothing to do with dx11.

**Comment by TristanWLB** [comment]
Haha yeah, dumb mistake on my part. It's all good to go now so I closed the issue, only been working with ImGui for a couple days but I'm loving it so far; keep up the awesome work! :smile:
