### ISSUE TITLE
CurrentWindow dangling pointer after shutdown

### ISSUE THREAD

**Issue by petrihakkinen** [ocornut/imgui#836]
ImGui::Shutdown() does not reset g.CurrentWindow to NULL so restarting imgui after shutdown can cause a crash when the pointer is deferenced in NewFrame(). Now this is probably an unusual use case but I have a live coding setup that requires restarting the app occasionally...

**Comment by ocornut** [comment]
Should be fixed.

**Comment by petrihakkinen** [comment]
Thank you!
