### ISSUE TITLE
Image renders atlas font

### ISSUE THREAD

**Issue by xGhostShipIV** [ocornut/imgui#838]
Hello,

I've seen an issue similar to this that was closed, but does not appear to be the same issue I am having.
What I am trying to do is use glReadPixels to take a snapshot of an OpenGL application and render that snapshot as an OpenGL texture in an ImGui image.

I am creating the texture like the following:
```
glGenTextures(1, &m_screenshotTexture);
glBindTexture(GL_TEXTURE_2D, m_screenshotTexture);
glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
glPixelStoref(GL_UNPACK_ALIGNMENT, 1);
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGB, width, height, 0, GL_RGB, GL_UNSIGNED_BYTE, textureData);
```

And later trying to draw the image as such:
```
ImTextureID id = (void*)m_screenshotTexture;
ImGui::Image(id, dockSize);
```

I have used the ``ShowMetricsWindow()`` function to further examine what is happening and it shows that the tex for the draw call is 0x00000001 whereas the id I'm giving the Image call is 0x00000002.

**Comment by ocornut** [comment]
Could you clarify what was your problem, if you solved it now?

**Comment by xGhostShipIV** [comment]
It wasn't an issue with ImGui. There was some vestigial code in our render function that was setting every texture to the atlas font for some reason. It took a while to figure that out but it's all solved now.
