### ISSUE TITLE
Button label alignment

### ISSUE THREAD

**Issue by BLK-Dragon** [ocornut/imgui#842]
Is it possible to have button label left-aligned?  
(when button-size is explicitly set larger than text, text is always centered)

**Comment by ocornut** [comment]
Not currently possible, but it shouldn't be too hard to add the option in Style.

**Comment by BLK-Dragon** [comment]
Indeed, judging from ImGui::ButtonEx() code.
Probably, it should be a button-flag.

**Comment by ocornut** [comment]
Note that it would be left-aligned but still will FramePadding applied, so not touching the border.

**Comment by ocornut** [comment]
Done. I took the occasion to clean up a few related things I wanted to change.
You can adjust style.ButtonTextAlign or use PushStyleVar(ImGuiStyleVar_ButtonTextAlign, ...)
`ImVec2(0.5f,0.5f)` = centered (default for buttons)
