### ISSUE TITLE
Multiple ImGui::Input(something) not working as intended

### ISSUE THREAD

**Issue by Widgertius** [ocornut/imgui#843]
Hello,

When I try to put mulitple inputs, for example, 

ImGui::InputInt("int1", &x);
ImGui::InputInt("int2", &y);

only the last input text-box works. All previous input text-boxes can't be edited. The moment you click'em the cursor disappears and when you click on the last input text-box it edits all previous instances even though the variable it points to is different.

 I feel like I'm missing something and am almost positive that I have not yet searched hard enough and I apologize. But I simply can't seem to find the solution for this problem anywhere. Your help will be greatly appreciated. Thanks!

P.S : the problem persists for any input(something), inputfloat3, inputfloat. 

Regards

**Comment by ocornut** [comment]
Are you using one of the unmodified example binding or something else?

Can you provide your actual code?
Are you using code exactly as written here or are your string labels identical?

Can you repro it in the examples app?

**Comment by ocornut** [comment]
Cool.

Also - When you provide code in your bug report please provide the actual code you are using :)
