### ISSUE TITLE
Show images non-axis-aligned / rotated

### ISSUE THREAD

**Issue by ecraven** [ocornut/imgui#847]
Is there any way currently to add an image to a draw list rotated?

**Comment by ecraven** [comment]
Is AddQuad the best way to do this?

**Comment by ocornut** [comment]
Right now you need to use:

```
PrimReserve(6, 4);
PrimQuadUV(...); // passing your 4 vertices and uv
```

**Comment by ecraven** [comment]
Any chance of adding draw list AddImageQuad doing the obvious?
I've done this locally, seems to work fine. If you'd merge it, I'll prepare a PR

**Comment by ocornut** [comment]
If we do this it'd need a rotation pivot.

**Comment by ecraven** [comment]
I don't think we do.

````
void ImDrawList::AddImageQuad(ImTextureID user_texture_id, const ImVec2& a, const ImVec2& b, const ImVec2& c, const ImVec2& d, const ImVec2& uva, const ImVec2& uvb, const ImVec2& uvc, const ImVec2& uvd, ImU32 col) {
  ...
  PrimQuadUV(a, b, c, d, uva, uvb, uvc, uvd, col);
  ...
}
````
So the user needs to get a,b,c and d right (by rotating according to whatever scheme they want). In essence, you specify 4 points (and 4 texture uv coordinates), and that is drawn as a quad.

It wouldn't solve the general problem of showing rotated images, but it would at least provide a portable way of achieving this in the special case of quads.

**Comment by ocornut** [comment]
Closing this.
Reference:
https://github.com/ocornut/imgui/issues/1982#issuecomment-408834301
https://github.com/ocornut/imgui/issues/1286
