### ISSUE TITLE
Funny tooltip behavior if using BeginGroup/EndGroup

### ISSUE THREAD

**Issue by usagi** [ocornut/imgui#849]
# Code

```c++
    ImGui::BeginGroup();
    ImGui::SmallButton( "button" );
    if ( ImGui::IsItemHovered() )
      ImGui::SetTooltip( "BUTTON" );
    ImGui::EndGroup();
    if ( ImGui::IsItemHovered() )
      ImGui::SetTooltip( "GROUP" );
```

# Behavior

1. We can see the "GROUP" tooltip if hovered.
2. But, we will see the "BUTTON" tooltip if pressing the `button`. ( I think it is a funny behavior. )

I think, the correct behavior is show the "GROUP" tooltip in every time. Or, the "BUTTON" in every time.

**Comment by ocornut** [comment]
Thanks, I will look at it.

**Comment by ocornut** [comment]
Should be fixed now. IsItemHovered() will return true for both the button and the group.

(Note that the behavior of SetTooltip() is to overwrite a previous tooltip, whereas BeginTooltip()/EndTooltip() does a regular append.)

````
ImGui::Begin("Bug #849");
ImGui::BeginGroup();
ImGui::SmallButton( "button" );
if ( ImGui::IsItemHovered() )
    ImGui::SetTooltip( "BUTTON" );
ImGui::EndGroup();
if ( ImGui::IsItemHovered() )
    ImGui::SetTooltip( "GROUP" );
ImGui::End();
```
