### ISSUE TITLE
Display flashed on Win 7 

### ISSUE THREAD

**Issue by zhoutingunl** [ocornut/imgui#850]
run the demo on WIN 7(64 bits), get the following display effect:

![c34655c3b6d6de753fba049b7ccfc158](https://cloud.githubusercontent.com/assets/17873750/18904778/6ceabb60-8592-11e6-8138-2c91c934ee60.jpg)

It happens on two computers.  Please tell me how to fix it.

Thanks in advance,

**Comment by ocornut** [comment]
Which demos did you run?
Did you try all the precompiled binaries?
Did you build it yourself?

**Comment by zhoutingunl** [comment]
run example-demo in the ofxImGui-master. builded under VS 2015 by myself.

Actually it is fine on MAC OS X and the other two Win 7 based PCs.

**Comment by ocornut** [comment]
If it is ofxImGui binding please report to the ofxImGui repository.

**Comment by zhoutingunl** [comment]
Sorry for that, I just figure out there are two different projects: ofxImGui and imgui.
