### ISSUE TITLE
ItemSpacing applied later than expected

### ISSUE THREAD

**Issue by pdoane** [ocornut/imgui#851]
With this fragment:

```
            static char buf[1024];
            static bool adjustSpacing;
            ImGui::Checkbox("Adjust spacing", &adjustSpacing);

            if (adjustSpacing)
                ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0f, 0.0f));

            ImGui::Button("A");
            ImGui::SameLine();
            ImGui::Button("B");

            if (adjustSpacing)
                ImGui::PopStyleVar();

            ImGui::InputText("Text", buf, sizeof(buf));
```
My expectation is that the vertical spacing between "AB" and the InputText should be the default/restored value, but instead the vertical spacing is 0.  Is this the intended behavior?

**Comment by ocornut** [comment]
It's hard to say what is "the intended behavior" but it pretty much has always been the behavior and I don't imagine it will change.

A way to see it is that by default every item adds a carriage return, to the vertical spacing is used there. I believe once you see it that way it shouldn't be a problem.

I haven't tested it, but I think if after your `PopStyleVar()` you did a `SameLine()` + `Text("")` it would probably yield the effect you want. SameLine() pretty much cancel the carriage return and Text("") would add a new one. It may be an ok workaround if you need that sort of control over vertical spacing?

**Comment by pdoane** [comment]
Yeah I'm using SameLine() + Dummy() right now - I agree it's not hard to workaround but wanted to confirm it wasn't a bug.
