### ISSUE TITLE
PushID()/PopID() make IsItemActive() return wrong value

### ISSUE THREAD

**Issue by thedmd** [ocornut/imgui#852]
`PushID()/PopID()` make `IsItemActive()` return wrong value. I'm tracking active flag to tell when focus on item is lost. 

Code to reproduce issue is listed below. It is simple 'click to edit' pattern. 
![img0](https://cloud.githubusercontent.com/assets/1197433/18947512/a337e520-8633-11e6-8feb-e022e55fbacb.png)
After clicking:
![img1](https://cloud.githubusercontent.com/assets/1197433/18947518/a961f6e8-8633-11e6-839f-e76eca2e80dd.png)
(By the way, clicking '+' or '-' cause whole `InputInt` to change active item and finish edit, is this a bug or intended behavior?)
When showing multiple editors using PushID()/PopID() what I get is after clicking is:
![img2](https://cloud.githubusercontent.com/assets/1197433/18947742/97834db8-8634-11e6-99f6-0b4202504573.png)
`IsItemActive` returns `false`, `true`, `false`.
First `false` is ignored, because `IsItemActive` is lagging one frame (probably LastItemId comparison is responsible for that).
Second `false` is returned because calling `PushID()` leads to calling `KeepAliveID()` and setting `ActiveIdIsAlive` to `true`. Returning from `InputInt` calls `EndGroup()` and recently added condition is not satisfied and `LastItemId` isn't restored.

Set `showMultipleEditors` to `false` to see working example and to `true` to see when PushID() is used.

``` cpp
        struct Editor
        {
            const char* Name;
            bool        Edit;
            bool        OnShow;
            int         Value;

            int         LiveFrameCount;
            int         ActiveFrameCount;
        };

        static Editor editors[] =
        {
            { "Edit Value 1", false, false, 0, 0, 0 },
            { "Edit Value 2", false, false, 0, 0, 0 }
        };

        bool showMultipleEditors = true;

        for (int i = 0; i < (showMultipleEditors ? 2 : 1); ++i)
        {
            Editor& editor = editors[i];

            if (showMultipleEditors)
                ImGui::PushID(i);

            if (!editor.Edit)
            {
                if (ImGui::Button("Edit", ImVec2(100, 19)))
                {
                    editor.Edit   = true;
                    editor.OnShow = true;
                    editor.LiveFrameCount   = 0;
                    editor.ActiveFrameCount = 0;
                }
            }
            else
            {
                if (editor.OnShow)
                    ImGui::SetKeyboardFocusHere();

                ImGui::PushItemWidth(100);
                ImGui::InputInt("", &editor.Value);
                ImGui::PopItemWidth();

                // Avoid calling ImGui::IsItemActive(), because it is lagging one frame

                if (editor.OnShow)
                {
                    editor.OnShow = false;
                }
                else
                {
                    // Stop edit when focus is lost
                    if (!ImGui::IsItemActive())
                        editor.Edit = false;
                }

                ++editor.LiveFrameCount;
                if (ImGui::IsItemActive())
                    ++editor.ActiveFrameCount;
            }

            // Display value
            ImGui::SameLine();
            ImGui::Text("%d,   Live: %d,  Active: %d", editor.Value, editor.LiveFrameCount, editor.ActiveFrameCount);

            if (showMultipleEditors)
                ImGui::PopID();
        }
```

**Comment by ocornut** [comment]
Thanks. Before I dig in deeper, have you merged https://github.com/ocornut/imgui/commit/6def01be5df16e17d71f81a8d4083a0f48d04a8d ?

**Comment by thedmd** [comment]
@ocornut Yes.

**Comment by ocornut** [comment]
Closing (discussed with @thedmd, decided issues as described is probably not existent anymore, as for implementing said pattern not sure what the best UX is to be honest, but that's not part of the issue itself).
