### ISSUE TITLE
Is it possible to set an ImGui window as the main application window?

### ISSUE THREAD

**Issue by ancrist** [ocornut/imgui#853]
I was wondering if there's a way to set an ImGui window as the main application window.
I used SDL + OpenGL to create a borderless, transparent window and the code in the ImGui `sdl_opengl3_example` for rendering. 

Here's the code I use to obtain the what's in the attached image:
```C
int width, height;
SDL_GetWindowSize(window, &width, &height);
ImGui::SetNextWindowPos(ImVec2(.0f, .0f), ImGuiSetCond_Always);
ImGui::SetNextWindowSize(ImVec2(width+2, height+2), ImGuiSetCond_Always);
ImGui::Begin("GL Editor", &show_another_window, ImGuiWindowFlags_NoResize | 
	ImGuiWindowFlags_NoMove | 
	ImGuiWindowFlags_NoCollapse);
ImGui::Text("Hello");
ImGui::End();
```
So what I'm basically doing is a `BeginWindow(...)` with it's size and position set to cover the main SDL window and prevent resizing, collapsing and moving ( you can see this as the round corners do not completely cover the background window )

This feels a bit hacky and now if I close the ImGui window the background window just stays there so I guess I have to forward the close event from ImGui back t the main SDL event loop.

Is there a better way achieving this?
Sorry if I'm missing something obvious as I just got started with ImGui yesterday :)

![Editor Window](http://oi65.tinypic.com/30lpkcm.jpg)

**Comment by metiscus** [comment]
ImGui isn't really intended to interact with the window manager in the way you describe. You were on the right track in how to accomplish what you want by forwarding the events back from ImGui to the software that interacts with the window manager (in your case SDL).

**Comment by ancrist** [comment]
@metiscus thanks for the tip.

I sort of had an aha moment and realized that to be the case as I browsed the ImGui code more. I guess retained mode GUI wasn't completely out of my system at the time of my initial comment :)

**Comment by ocornut** [comment]
In this case you probably want to avoid using the ImGui title bar and just use your application title bar directly?

**Comment by ocornut** [comment]
Closing this, hope it is ok.

**Comment by ancrist** [comment]
Sry I sort got caught up in something else and didn't get around to
replying. Sure, it's ok if you close it. I managed to implement what I was
after with SetWindowPos on the win32 window.
