### ISSUE TITLE
Slider reverse direction

### ISSUE THREAD

**Issue by wasawi** [ocornut/imgui#854]
Just bumped into a very stupid issue but don't see how to fix it. I'm very sorry I must be missing something very obvious. 
How to set the minimum value (0) on the right hand side?

```
    ImGui::SliderFloat("Float", &floatValue, 1.0f, 0.0f);
```

This has a strange behavior. The slider appears and disappears on the sides when dragging.
Again, sorry for a very basic question.

**Comment by ocornut** [comment]
Amusingly you are the first person to request that. I never tested nor tried to make the slider work this way and curiously I have not even added an assert.

So, it needs to be worked on!

**Comment by wasawi** [comment]
Thank you for your fast reply!

**Comment by ocornut** [comment]
@wasawi This has been added now!
