### ISSUE TITLE
I need help using font.ttf on my app

### ISSUE THREAD

**Issue by edselmalasig** [ocornut/imgui#856]
<code>
ImGui::SetupImGuiStyle( false, 1.01f  );
    ImGui_ImplGlfwGL3_NewFrame();
    
    ImFontConfig icons_config; icons_config.MergeMode = false; icons_config.PixelSnapH = true; icons_config.FontDataOwnedByAtlas = true; icons_config.FontDataSize=72;
    
    io = ImGui::GetIO();
    io.WantCaptureKeyboard = true;
    ImFont* font = io.Fonts->AddFontFromFileTTF( "../icons/California.ttf", 16.0f, &icons_config, io.Fonts->GetGlyphRangesDefault());
    
    unsigned char* pixels;
    int width, height;
    io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height);
    ImFontAtlas* atlas = ImGui::GetIO().Fonts;
    
    ImGui::PushFont(atlas->Fonts[0]);
</code>

error is:
Assertion failed: (*p_backup == current && "PushFont/PopFont Mismatch!"), function CheckStacksSize, file ../../../lib/imgui/imgui.cpp, line 3669.
Abort trap: 6

**Comment by ocornut** [comment]
That assert has nothing to do with the font data.

It refers to the fact that you within the same level of the window stack you need a matching PopFont() for everything PushFont().

If you called PushFont() while inside a window (Begin() block) you need to call PopFont() before End().

**Comment by edselmalasig** [comment]
i noticed that using a ttf directly as rob slows my pc. Whats the best way to compile binary_to_compressed_c.cpp?

i get this error:
<code>
 g++ binary_to_compressed_c.cpp 
binary_to_compressed_c.cpp:180:5: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
    stb_out(v >> 8);
    ^~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:181:5: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
    stb_out(v);
    ^~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:184:36: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
static void stb_out3(stb_uint v) { stb_out(v >> 16); stb_out(v >> 8); st...
                                   ^~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:184:54: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
static void stb_out3(stb_uint v) { stb_out(v >> 16); stb_out(v >> 8); stb_out(v...
                                                     ^~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:184:71: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
  ...stb_out3(stb_uint v) { stb_out(v >> 16); stb_out(v >> 8); stb_out(v); }
                                                               ^~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:185:36: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
static void stb_out4(stb_uint v) { stb_out(v >> 24); stb_out(v >> 16);
                                   ^~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:185:54: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
static void stb_out4(stb_uint v) { stb_out(v >> 24); stb_out(v >> 16);
                                                     ^~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:186:5: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
    stb_out(v >> 8 ); stb_out(v);                  }
    ^~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:186:23: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
    stb_out(v >> 8 ); stb_out(v);                  }
                      ^~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:197:34: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
    else if (numlit <=    32)    stb_out (0x000020 + numlit-1);
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:290:13: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
            stb_out(0x80 + best-1);
            ^~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:291:13: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
            stb_out(dist-1);
            ^~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:295:13: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
            stb_out(best-1);
            ^~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:299:13: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
            stb_out(best-1);
            ^~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:308:17: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
                stb_out(0x06);
                ^~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:310:17: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
                stb_out(best-1);
                ^~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:312:17: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
                stb_out(0x04);
                ^~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:344:5: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
    stb_out(0x57); stb_out(0xbc);
    ^~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
binary_to_compressed_c.cpp:344:20: error: right operand to ? is void, but left
      operand is of type 'stb_uchar' (aka 'unsigned char')
    stb_out(0x57); stb_out(0xbc);
                   ^~~~~~~~~~~~~
binary_to_compressed_c.cpp:176:33: note: expanded from macro 'stb_out'
  ...(stb__out ? *stb__out++ = (stb_uchar) (v) : stb__write((stb_uchar) (v)))
               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
19 errors generated.

</code>

**Comment by ocornut** [comment]
> i noticed that using a ttf directly as rob slows my pc. 

I don't understand nor believe this statement.

> Whats the best way to compile binary_to_compressed_c.cpp?

There was bug in the code which would make modern G++ fails at it. It should be fixed now.
It won't be any faster to use binary_to_compressed_c. This is only a tool to help if you want to avoid loading files from the disk.
