### ISSUE TITLE
How to enable a checkbox by default?

### ISSUE THREAD

**Issue by Cod3sss** [ocornut/imgui#865]
Hello, I have been looking around and have found nothing but is there a way to enable a checkbox by default? meaning when I start the imgui the box will be checked as well with the function. C++

ty

**Comment by ratchetfreak** [comment]
```static bool checked = true;
Checkbox("checkbox", &checked);```

Set the boolean to true before the first time calling Checkbox.

**Comment by Cod3sss** [comment]
ty
but how do you set the checkbox already checked? 

ImGui::Checkbox( charenc( "Watermark" ), &Vars.Misc.Watermark );

**Comment by Cod3sss** [comment]
I tried 

ImGui::Checkbox( charenc( "Watermark" ), &Vars.Misc.Watermark, &checked );


but too many arguments.

**Comment by ocornut** [comment]
> but how do you set the checkbox already checked?
> 
Vars.Misc.Watermark = true;

**Comment by Cod3sss** [comment]
Alright it worked... lol but now I cant uncheck it..

**Comment by ongamex** [comment]
Are you sure you're not resetting it every time before calling ImGui::CheckBox again? This is usually the case the the most of us aren't used to "immediate mode gui" style of handling variable changes and updates.

**Comment by ocornut** [comment]
The bool value is yours.
Checkbox() just toggles it when you click.
