### ISSUE TITLE
Rainbow Bar?

### ISSUE THREAD

**Issue by confirmed12** [ocornut/imgui#867]
Hey! I'm loving ImGUI so far but i have a quick question. Is there anyway i can do this rainbow bar in imgui?

http://i.imgur.com/cbBdsHS.gif

ty

**Comment by ocornut** [comment]
You can use ImGui::ProgressBar(). And use ImGui::PushStyleCol()/PopStyleCol() to change a certain color.

PS: please do not link to imgur but use the github attachment system. Imgur links are all volatile.

**Comment by ocornut** [comment]
I though you meant the progress bar within the window, sorry.
For the rainbowish thing you can use the ImDrawList API and draw whatever you want.

**Comment by ZaWarudo111** [comment]
Sorry but #1586

**Comment by ZaWarudo111** [comment]
bruh
