### ISSUE TITLE
Flickering mouse cursor while in game. please help

### ISSUE THREAD

**Issue by Cod3sss** [ocornut/imgui#868]
Hello, I'm using ImGUI for my csgo cheat and I'm loving it but there is a problem and its kinda annoying but everytime I open the menu the windows cursor gets in the game "fullscreen" and starts flickering between the game cursor and the mouse cursor any ideas of what is causing it? ty

**Comment by ocornut** [comment]
Your wording is unclear and you aren't providing much information.

Please provide repro (code that actually be pasted in an example app and exhibit the issue) when you ask about issues.

**Comment by Cod3sss** [comment]
I'm sorry, well whats happening is that when I open the game csgo has his own cursor right? but when I open the menu the windows cursor appears and starts flickering, when I close the menu the cursor stays which I don't want to, here is my code.

http://pastebin.com/b66qtZTZ

**Comment by ocornut** [comment]
ImGui displays a software (2 triangles) cursor only if you set `io.MouseDrawCursor` to true.

Any other cursor would be handled by the OS. 

imgui_impl_dx9.cpp happen to calls SetCursor(NULL) or SetCursor(LoadCursor(NULL, IDC_ARROW)) depending on the state of `io.MouseDrawCursor`, which is perhaps not a good thing to do. See https://github.com/ocornut/imgui/issues/585 - So perhaps that needs tweaking and you may see if that line may be best removed for you.

Whatever your hooking system and host app does is totally unknown to me so I can't begin to guess what other things may be involved there. (not even mentioning the fact that is unethical and running other people's games, which really doesn't give me much incentive to help you).

**Comment by Cod3sss** [comment]
Tried deleting the mousedrawcursor but still the same... Also tried what lised in #585 didn't help either. Still shows 2 cursors, the game cursor and the windows cursor.

**Comment by Cod3sss** [comment]
It must be ImGUI too because without it the cursor is fine.

**Comment by Cod3sss** [comment]
I have set 

	if (ImGui::GetIO().MouseDrawCursor) SetCursor(NULL);

still showing..

**Comment by ocornut** [comment]
It's not ImGui, ImGui doesn't do anything with your OS cursor. The only place that ever does is the wrapper  `imgui_impl_dx9.cpp`.
