### ISSUE TITLE
Display GUI in games

### ISSUE THREAD

**Issue by Bluetexon** [ocornut/imgui#869]
Hi,
I'm quite new to this GUI, so I need a little bit help.
How do I display the GUI in a game, when I'm running it from an external .exe?
I've googled for some tutorials, etc and found nothing. The demo's are a bit confusing to me and the "Programmers Guide" is not telling me how I can initialise this GUI. Or atleast I don't understand it.

So, it would be nice, if someone would help me, because I wanted to use this GUI so much.

Greetings, Bluetexon

**Comment by ocornut** [comment]
Hello Bluetexon,

What do you mean by "running it from an external .exe" ? Please clarify what's your existing application like and which system/engine it is using (OS? rendering? input?).

All the documentation and information are including at the top of imgui.cpp and in the examples/ directory. I realize that's not a lot and it requires some programming experience to "get" it.

The examples directory contains full reference application. You may want to grab a set of the imgui_impl_xxxx binding one that's most suitable to the rendering/input technology you are using. Then the content of a main.cpp file matches what your existing application would do to integrate the binding and it is usually few lines of code.

Omar

**Comment by Bluetexon** [comment]
Hi,
first, thanks for the fast response.
So, I want to use this GUI outside the demo-DirectX window. I want to run it in a DirectX11 Game on Windows 10. I already tried several things(copying, editing, etc) but nothing worked. 
Now I am asking myself, what code I need to dispaly a "simple" blank ImGui window.

I hope I haven't forgot anything. 
Thanks in advance.

Greetings, Bluetexon

**Comment by ocornut** [comment]
You have to add all the folders in the root folder into your project + imgui_impl_dx11.cpp files.
Then the code you need to set it up and display is main.cpp in the DX11 folder.

**Comment by Bluetexon** [comment]
The problem is, that the DX11 game is not mine. I want to make a game trainer, so I have to inject the GUI somehow in the game(existing window). Is this possible?

**Comment by ocornut** [comment]
It is, many of your peers are already doing so. I can't provide much more information than what's readily available and completely sufficient.

**Comment by Bluetexon** [comment]
Ok, thank you anyways for your support.
