### ISSUE TITLE
[Request] Button Style

### ISSUE THREAD

**Issue by Netsploitt** [ocornut/imgui#870]
Hello, I would love to be able to make something like this, I believe it's a parallelogram? 

![image](https://cloud.githubusercontent.com/assets/16443556/19220905/22408cec-8e30-11e6-8a9b-0238589ed50a.png)

If anyone can shed some light on how to edit the button to this style I would be very appreciative. 

I have a tabbing function which I created what utilises buttons to create tabs.

**Comment by ocornut** [comment]
It's not possible to edit the stock button this way. You can create your own button code following what button done but all hit test in imgui are done on an axis aligned rectangle area.
