### ISSUE TITLE
Annotating an image

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#871]
I have a scene with several GUI's already loaded. When I load a .jpg file from one of these GUIs it appears full screen under the GUIs already present which is fine. I now want to be able to add lines, circles, etc. with annotations to the image to highlight various parts of the image probably controlled from another GUI on the screen. Do I need to apply a full screen overlay which I can draw upon but still see the image underneath? What is the best way and most efficient way to do this please? 

Thanks

David

**Comment by ocornut** [comment]
You can use the ImDrawList API to add custom draw commands.

So typically ImGui::Image() or draw_list->AddImage() followed by other draw_list->AddXXX calls.

**Comment by djones4487169** [comment]
Thanks Omar,

So if I have a basic jpeg image attached to the draw_list method I can draw
on top of it with subsequent draw-list function calls. I think I get it
could you show me a quick example snippet please?

david

**Comment by ocornut** [comment]
ImGui and ImDrawList don't deal with JPEG, they deal with "textures" via the ImTextureId type which is simply storage for a pointer or an integer. Most generally you would use this value to store reference to a texture within your own rendering system. e.g. If you use OpenGL texture ID, you can store a GLuint ID in that value, etc. This is well documented in the FAQ and in the code and at the top of every binding.

It is up to you to take a JPG from disk and load it into a texture. Libraries like stb_image.h generally makes this easy.

**Comment by Thanh-Binh** [comment]
@ocornut 
I used exactly what you recommend, and want to draw a circle at the center of my image 200x200, but the circle is display under my image 
```C`
ImGui::Begin("Green Texture Image");
sf::Texture imTexture; // image 200 x 200
ImGui::Image(imTexture, sf::Color(0,0,0), sf::Color(0,0,255)); // 2nd color for image frame
        
ImDrawList* draw_list   = ImGui::GetWindowDrawList();
ImGuiStyle style        = ImGui::GetStyle();
float width             = ImGui::CalcItemWidth();

ImVec2 picker_pos       = ImGui::GetCursorScreenPos();
picker_pos.x += imTexture.getSize().x / 2;
picker_pos.y += imTexture.getSize().y / 2;

draw_list->AddCircleFilled(picker_pos, 10, IM_COL32(255,0,0,2), 4);
```
I really do not understand if ImGui::GetCursorScreenPos() or ImGui::GetWindowPos() is the right function to get the upper-left corner of my current windows.

What did I do wrong here? [Thanks](![Screenshot from 2023-01-30 16-45-19](https://user-images.githubusercontent.com/6269904/215525335-1f09be44-7290-4567-9fd4-151cc19e0cc0.png))
