### ISSUE TITLE
Distance between two points

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#872]
I've added a function to calc distance between two points:

```
float calc_distance(ImVec2 p1, ImVec2 p2)
{
	const float dx = p2.x - p1.x;
	const float dy = p2.y - p1.y;

	return sqrt((dx * dx) + (dy * dy));
}
```

I'm using this function to try and get the size of the line drawn in the Custom Rendering example provided using the for loop like this:

```
ImVec2 value_raw = ImGui::GetMouseDragDelta(0, 0.0f);
float dist = 0.0f;
draw_list->PushClipRect(ImVec4(canvas_pos.x, canvas_pos.y, canvas_pos.x + canvas_size.x, canvas_pos.y + canvas_size.y));      // clip lines within the canvas (if we resize it, etc.)

for (int i = 0; i < points.Size - 1; i += 2)
{
	draw_list->AddLine(ImVec2(canvas_pos.x + points[i].x, canvas_pos.y + points[i].y), ImVec2(canvas_pos.x + points[i + 1].x, canvas_pos.y + points[i + 1].y), 0xFF00FFFF, 1.5f);
	dist = calc_distance(ImVec2(canvas_pos.x + points[i].x, canvas_pos.y + points[i].y), ImVec2(canvas_pos.x + points[i + 1].x, canvas_pos.y + points[i + 1].y));
}

draw_list->PopClipRect();
if (adding_preview)
	points.pop_back();

ImGui::Text("Raw (%.1f, %.1f)", value_raw.x, value_raw.y);
ImGui::Text("%.1f", dist);
```

I'm not sure i'm doing this quite right? I also need to convert the value to a metric e.g. mm - how could I do that?

Thanks

David

**Comment by ocornut** [comment]
> I'm not sure i'm doing this quite right? 

That looks correct.

> I also need to convert the value to a metric e.g. mm - how could I do that?

That question doesn't really make sense. The units here are in whatever unit you want them to be, most generally if your render is not scaled 1 = 1 pixel. Converting 1 pixel to a real-world metric unit can be done if you know your monitor size and DPI. Most likely you may want to convert to your virtual-real metric unit and then it is whatever you want it to be.

PS: It is generally expected that the user have their own vector math library and can use e.g. the IM_VEC2_CLASS_EXTRA define in imconfig.h to use their own vector type. But you can also `#define IMGUI_DEFINE_MATH_OPERATORS` and then `#include "imgui_internal.h` to use the functions that ImGui internal uses such as ImLengthSqr().

**Comment by djones4487169** [comment]
Thanks for the reply!

With regards converting to mm I keep seeing everywhere that 1 pixel = 0.2654 mm so is it simply a question of multiplying the pixel value calculated above by 0.2654 mm to get the length of the line in mm. Doesn't seem right when we have different monitor resolutions etc.? Is there are standard way of calculating it for all monitors?

**Comment by ocornut** [comment]
This is out of the scope of ImGui, sorry.

**Comment by stfx** [comment]
Hey @ocornut, does the compiler resolve those conversions on compile-time or does for example `#define IM_VEC2_CLASS_EXTRA ImVec2(const glm::vec2& f) { x = f.x; y = f.y; } operator glm::vec2() const { return glm::vec2(x, y); }` result in a performance hit?

> It is generally expected that the user have their own vector math library and can use e.g. the IM_VEC2_CLASS_EXTRA define in imconfig.h to use their own vector type
