### ISSUE TITLE
The imgui program will crash if I set the refresh_time at a high level!

### ISSUE THREAD

**Issue by 127huangfei** [ocornut/imgui#873]
Hello, ocornut. I found a bug when test the imgui_demo.cpp. When I change the demo code" for (; ImGui::GetTime() > refresh_time + 1.0f / 60.0f; refresh_time += 1.0f / 60.0f)" into  "for (; ImGui::GetTime() > refresh_time + 1.0f / 1000000.0f; refresh_time += 1.0f /1000000.0f)", the GUI will crash after running for a few seconds(about 25 secs). When I change the number from 1000000.f to 100000.0f, the GUI will also crash after running for a few minutes(about 4mins20secs). Did you find the problem?

**Comment by MKUltra42** [comment]
You are likely exceeding the limits of floating point precision (roughly
think 6 digits of precision for a small number after the decimal) and
probably running into updates that take near-zero time and possibly confuse
some code. Why do you think you need this? Also, it is probably helpful
attaching a debugger and providing things like call stacks when reporting
crashes ...

**Comment by 127huangfei** [comment]
Actually, I need the GUI refresh at a high frequency due to the high data sampling rate. So when I set the number at a high level, the problem occurs. In addition, it is so weird that the GUI will crash at a fixed time, such as when the number is 1000000.0f, the GUI will always crash at about 25secs, when the number is 100000.0f, the GUI will always crash at about 4mins20secs, and 10000.f for about 30mins. I wonder if there is something ragular or some underlying relationship behind this phenomenon. Maybe memory leak or something like this? It really bother me.

**Comment by ocornut** [comment]
You are not tellin us where it crashes, please clarify this. Saying that code crashes without providing more information is not useful enough.

And you don't need a refresh rate of 100000 per second it doesn't make any sense, your screen can't display that.

**Comment by 127huangfei** [comment]
Sorry, I didn't make myself clear. Let's take the "imgui_demo.cpp" for example. When I change the demo code like this (just changing 60.0f to 10000.0f):
`        if (animate)
        {
            static float refresh_time = ImGui::GetTime();
            			for (; ImGui::GetTime() > refresh_time + 1.0f / 100000.0f; refresh_time += 1.0f / 10000.0f)
            {
                static float phase = 0.0f;
                values[values_offset] = cosf(phase);
                values_offset = (values_offset+1) % IM_ARRAYSIZE(values);
                phase += 0.10f*values_offset;
            }
        }`
the GUI will always crash after running 30mins at the refresh rate of 10000, and it always stop before this code:
` values[values_offset] = cosf(phase);`
By the way, the refresh rate of 10000 is very significant in our software, and we can display sampling data at this refresh rate. I know the higher refresh rate is insignificant, I just want to show the problem by setting it at 1000000. And it shows that the higher the refresh rate is, the faster the GUI will crash.

**Comment by ocornut** [comment]
This is not the GUI crashing.

Marko is right:
> You are likely exceeding the limits of floating point precision (roughly think 6 digits of precision for a small number after the decimal) and probably running into updates that take near-zero time and possibly confuse some code. 

If you keep adding 1.0f/1000000.0f to a floating point number and compare it a threshold (here GetTime()) at some point the precision will faill you and the > test will never return true. I just verified it with that bit of code.

You are just running into an infinite loop and it has nothing to do with ImGui.

About refresh rate - you are confused. Your data can come at high-frequency but you cannot DISPLAY it on a screen at 10000 hz. Unless you are working with 10000 hz screen? There's no display code in that code you pasted. It is merely filling at array of float. The array in the demo carry 90 values. If you keep filling it a million time you will only overwrite the same values. The creation of vertices for display comes when you call PlotEx() giving it the range you want to display.

If you are working with high-frequency data (say, 10000 samples a second) you probably need to store it in a big array, so you can look at the data after the fact with an interactive interface to browse the data.

**Comment by 127huangfei** [comment]
Thank you for your response! Maybe I was just confused the refresh rate and the sampling rate. Thank you for your advice. Good night!
