### ISSUE TITLE
sdl_opengl2_example does not clear screen properly when resizing 

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#874]
Hi
i got this weird behaviour only with my laptop (win7 32bits , opengl3 capable graphic card), 
on my pc it works fine 
![gif5](https://cloud.githubusercontent.com/assets/10813427/19379625/30ca939a-91f3-11e6-964f-843fc61e0328.gif)

**Comment by ocornut** [comment]
Any fix? I don't really use SDL myself.

**Comment by codz01** [comment]
note that if i comment the line : ImGui::Render(); , the screen cleared properly

**Comment by Wohlstand** [comment]
Are you doing glClear() every frame before render?
That background rectangle seems don't accepting window resize event.

**Comment by codz01** [comment]
yes , you can see
        glViewport(0, 0, (int)ImGui::GetIO().DisplaySize.x, (int)ImGui::GetIO().DisplaySize.y);
        glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
        glClear(GL_COLOR_BUFFER_BIT);
        ImGui::Render();
        SDL_GL_SwapWindow(window);


i just checked the value of ImGui::GetIO().DisplaySize.x and ImGui::GetIO().DisplaySize.y , they are updated correctly . 
i dont know where is the problem  !!

**Comment by Wohlstand** [comment]
> i dont know where is the problem !! 
but width and height?
Try to compare with SDL's poll events thing and catch SDL_WINDOWEVENT_RESIZED event yourself and use that yousefl

**Comment by codz01** [comment]
thanks , yes i tried that too , it gives the same result !

**Comment by Wohlstand** [comment]
Quick question: are you used SAME x86 assembly for both PCs or for your laptop you built x64 binary? If binary is same, seems you need to try reset OpenGL's viewport to initial after rendering, because a trouble on a side of video driver (are you have latest?)

**Comment by codz01** [comment]
no  , they are both 32bits , i didn't touch the code i just compiled the demo sdl_opengl2_example come with dear imgui . but later i tried  SDL_WINDOWEVENT_RESIZED as i said with no luck

the driver on my pc is the latest , the laptop has an old driver . but i used sdl2 befor that on this laptop  with no problem ! .

i'll try you suggestion .

**Comment by Wohlstand** [comment]
Anyway, a trouble seems when you seted viewport, it still be same when glClear called. Anther thing for test - comment glViewport completely and keep this code only:
(Code I posted above for case when you need use viewports in your application before/after rendering of ImGui)
```C++
glClearColor(clear_color.x, clear_color.y, clear_color.z, clear_color.w);
glClear(GL_COLOR_BUFFER_BIT);
ImGui::Render();
SDL_GL_SwapWindow(window);
```

**Comment by ocornut** [comment]
I cannot reproduce the issue either.
Windows 10, Nvida GTX 870M, driver 372.70

Your GIF above suggest that you are not using an unmodified example app. Do you also get the bug with the example app on GIT without any modification?

**Comment by codz01** [comment]
yes even with last git . last night i spent 4h trying to figure out whats wrong , with no result :(
![imgui](https://cloud.githubusercontent.com/assets/10813427/19410391/8bc26eaa-92eb-11e6-8bec-620e01c747ce.gif)

**Comment by Wohlstand** [comment]
Okay, just for a test I'll try make some dummy SDL2-based OpenGL app to let you compile it and run on that machine

**Comment by codz01** [comment]
i solved the issue by moving the line 101 in imgui_impl_sdl.cpp ( glScissor(....) ) into the main loop .
and change it to : glScissor(0 , 0 , ImGui::GetIO().DisplaySize.x , ImGui::GetIO().DisplaySize.y);

i still don't know why !!

**Comment by ocornut** [comment]
OK so the code in the `imgui_impl_sdl.cpp` doesn't restore the scissor bit, it's probably that.
But `imgui_impl_sdl_gl3.cpp` is ok.

**Comment by Wohlstand** [comment]
Anyway, any scissors and viewports are must be restored to initial state after rendering to prevent any wired bugs on random hardware and software.

**Comment by ocornut** [comment]
I edited my message above. The examples are supposedly saving/restoring all states. For that old GL examples it uses the old functions for that.

**Comment by codz01** [comment]
thanks ocornut , i'll try your suggestions & i'll tell you later .
about imgui_impl_sdl_gl3.cpp , this machine support only ogl 3.0 and below  , so no core profile .

**Comment by codz01** [comment]
glDisable(GL_SCISSOR_TEST) resolved the problem too , many thanks 
seems cleaner solution .

**Comment by ocornut** [comment]
So that's definitively a bug in the driver with handling the very old functions, but can't blame them for that, I assume they must "old gl" vs "new gl" with different code and mixing them both is not well supported. I'll have to see if there's a GL2 compatible requirement.

I though the code in sdl_gl3 was GL 3.0 ?

**Comment by codz01** [comment]
no , it is 3.2 , you can see the initialization in main.cpp
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);

its ok ,  i'll continue using gl2

**Comment by bgsa** [comment]
> i solved the issue by moving the line 101 in imgui_impl_sdl.cpp ( glScissor(....) ) into the main loop .
> and change it to : glScissor(0 , 0 , ImGui::GetIO().DisplaySize.x , ImGui::GetIO().DisplaySize.y);
> 
> i still don't know why !!

Worked for me !
The reason may be I just call  glScissor once. 
Perhaps, It is stored on opengl state.

**Comment by albertvaka** [comment]
This still happens to me, on both Nvidia and Intel cards, so it seems unlikely it's a driver problem...
