### ISSUE TITLE
User pointer for callbacks?

### ISSUE THREAD

**Issue by aaronhyperum** [ocornut/imgui#875]
As you are pursuing multi-context, it would be useful to be able to set a pointer to user data when setting up the callbacks, similar to how GLFW does it. For example, 

```
io.SetClipboardTextFn = [](const char* text)
    {
        glfwSetClipboardString(g_Window, text);
    };
```

The window must be a global variable in this case, but if a context specific pointer was given back, then an instance-local window could be passed in. Is this a feature you would be interested in implementing?

**Comment by ocornut** [comment]
I agree it would be a useful change. It'll be a breaking change but not everybody override it and breakage will be trivial so I think I'll just go for it.

**Comment by ocornut** [comment]
Done
