### ISSUE TITLE
How is ImDrawList::AddCallback Used?

### ISSUE THREAD

**Issue by sprinkle131313** [ocornut/imgui#876]
For example I want to draw a texture from OpenGL to debug it, but it had an alpha channel so it needs to be rendered differently from the rest of ImGui. I don't want any transparency when rendering the texture, but I also want to be able to render the alpha channel as a black/white image. I'm not sure what AddCallback applys to as well.

**Comment by ocornut** [comment]
There's different ways you can achieve what you need.

1)
In most situation, people who build engine over OpenGL would have a higher-level concept of what is a "texture" or a "material".
So rather than passing a raw GLuint texture identifier as ImTextureId, you could pass your own e.g. `MyTexture*` and this would hold sufficient information about the texture type. Or `MyMaterial*` would typically refer to an even high-level concept of associating shaders, textures and various parameters.  Maybe it could carry texture+shader. ? Maybe it could carry a texture and enough parameter to decide how to render it.

2)
You could indeed use callback to either change the state of your renderer, either perform the actual rendering. AddCallback() just registers a function and parameter that your imgui renderer loop will call. The order within a same window/drawlist are preserved, so if you add 1000 triangles and then add a callback, then 1000 triangles again, your renderer will see them in that order.

So you can use the callback for altering the state of your renderer (e.g. selecting a different shader, blending state...). If you do so you may need to add a callback _after_ the texture to restore your render state.

So it would be something like:
```
AddCallback(function_to_select_shader_or_blend_state, args);
AddImage(...); 
AddCallback(function_to_restore_shader_or_blend_state);
```

Or you can perform the actual rendering of the quad within your callback if you prefer (useful/necessary if you need to deal with vertex types that aren't the same as ImDrawVert).

```
AddCallback(one_function_to_do_everything).
```

I'd suggest going for 1) at will would be more natural and easier to extend but both would work.

**Comment by sprinkle131313** [comment]
I'm a bit confused by your usage of Callback. Does addCallback make the callback for every function call use that specific callback, or is it simply an extra call that will happen?

```
AddCallback(function_to_select_shader_or_blend_state, args);
AddImage(...); 
AddCallback(function_to_restore_shader_or_blend_state);

// implementation will look like:

void function_to_select_shader_or_blend_state(...)
{
    glDisable(GL_BLEND);
}

void function_to_restore_shader_or_blend_state(...)
{
    glEnable(GL_BLEND);
}

// so when AddImage(...) draw is called it won't call a UserCallback ? It'll just use normal call:

if(cmd->UserCallback)
{
    // AddImage(...) will Not use this ?
}

```

or...

```
AddCallback(one_function_to_do_everything); // what vertices are passed to this?
AddImage(...); // this "draw" will have ImDrawCmd::UserCallback set to above ?
AddCallback(null);

// ...

void one_function_to_do_everything(... , const ImDrawCmd* cmd)
{
    // cmd.TextureId == AddImage(...) from above ?
}

```

**Comment by ocornut** [comment]
It is a call that happen once. Look at what the render loop does:

```
        for (int cmd_i = 0; cmd_i < cmd_list->CmdBuffer.Size; cmd_i++)
        {
            const ImDrawCmd* pcmd = &cmd_list->CmdBuffer[cmd_i];
            if (pcmd->UserCallback)
            {
                pcmd->UserCallback(cmd_list, pcmd);
            }
            else
            {
                glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->TextureId);
                glScissor((int)pcmd->ClipRect.x, (int)(fb_height - pcmd->ClipRect.w), (int)(pcmd->ClipRect.z - pcmd->ClipRect.x), (int)(pcmd->ClipRect.w - pcmd->ClipRect.y));
                glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer);
            }
            idx_buffer += pcmd->ElemCount;
        }
```

**Comment by sprinkle131313** [comment]
I ended up changing the type of TextureID to be 2 pointers. It was the only way I could think of doing it without allocating memory with malloc/new and then having to free/delete it at some point, unreliably. One pointer is just a GLuint or index to one of my custom textures and the other is a function pointer to the desired rendering.

```C++

struct ImTextureID// changed
{
    void* first;
    void* second;
}

using MyFuncPtr = void(*)(MyRenderer&, void*, ...);

MyFuncPtr lambda = [](MyRenderer& renderer, void* tex, ... )
{
    renderer.doTheRenderIWant(GLuint(tex));
};

ImTextureID tex;

tex.first  = lambda;
tex.second = (void*)(myGLTex);

AddImage(tex, ...);

// then in the rendering

MyFuncPtr func = MyFuncPtr(cmd.TextureID.first);
func(myRenderer, cmd.TextureID.second, ...);
```

I didn't really see a way to do it the way I wanted to with say a Material, since if there was the case I needed to create a new Material it would have been difficult to track when I didn't actually need it anymore. This way no resources are allocated and it's just one additional pointer for the ImTextureID.

**Comment by ocornut** [comment]
That's sort of elegant.

But I'm not sure to understand: ImTexture is defined as a void* you can't change its type unless you modify the type declaration code in imgui.h. Did you do that ?

Again here your lambda code imply doing actual rendering, where are position/vertices coming from? It may be better to store data in `first` that defines how to render, and leave it to the render loop to use the vertices submitted by imgui.

**Comment by sprinkle131313** [comment]
> But I'm not sure to understand: ImTexture is defined as a void* you can't change its type unless you modify the type declaration code in imgui.h. Did you do that ?

Yah I had to do that, it's a small change that wouldn't be that difficult to do for any future versions, if I want to upgrade to.

> Again here your lambda code imply doing actual rendering, where are position/vertices coming from? It may be better to store data in first that defines how to render, and leave it to the render loop to use the vertices submitted by imgui.

It does the actual rendering, since ImTextureId now has a function call the rendering code would change. I tried to illustrate that:

```C++
for (const ImDrawCmd* pcmd = cmd_list->CmdBuffer.begin(); pcmd != cmd_list->CmdBuffer.end(); pcmd++)
{
    if (pcmd->UserCallback)
    {
        pcmd->UserCallback(cmd_list, pcmd);
    }
    else
    {
        MyFuncPtr func = MyFuncPtr(pcmd->TextureId.first);
        func(
            myRenderer,             // myRenderer could just be "this" instead, eg: myRenderer.drawImgui();
            pcmd->TextureId.second,
            vertexArrayObject,      // pass the GL array vertex + buffers containg the vertex render data
            idx_buffer_offset);     // the offset to draw

        // original:
        // glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->TextureId);
        // glScissor((int)pcmd->ClipRect.x, (int)(fb_height - pcmd->ClipRect.w), (int)(pcmd->ClipRect.z - pcmd->ClipRect.x), (int)(pcmd->ClipRect.w - pcmd->ClipRect.y));
        // glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer_offset);
    }
    idx_buffer_offset += pcmd->ElemCount;
}
```

When setting the Font texture, it would include a lambda that would make the call to do the default rendering for ImGui. It only works for textures though and only one "ImTextureId" exists for the font, so you can't change that per draw command.

Maybe adding another "user callback" as to provide a function that does the drawing. That way when the font "ImTextureId" is passed, the render behavior can also change.

```C++

for (const ImDrawCmd* pcmd = cmd_list->CmdBuffer.begin(); pcmd != cmd_list->CmdBuffer.end(); pcmd++)
{
    if (pcmd->UserCallback)
    {
        pcmd->UserCallback(cmd_list, pcmd);
    }
    else
    {

        if(pcmd->CustomRenderCallback)
        {
            pcmd->CustomRenderCallback(
                myRenderer,             // myRenderer could just be "this" instead, eg: myRenderer.drawImgui();
                pcmd->TextureId.second,
                vertexArrayObject,      // pass the GL array vertex + buffers containg the vertex render data
                idx_buffer_offset);     // the offset to draw
        }
        else
        {
            glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->TextureId);
            glScissor((int)pcmd->ClipRect.x, (int)(fb_height - pcmd->ClipRect.w), (int)(pcmd->ClipRect.z - pcmd->ClipRect.x), (int)(pcmd->ClipRect.w - pcmd->ClipRect.y));
            glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer_offset);
        }

    }
    idx_buffer_offset += pcmd->ElemCount;
}

// then when creating the UI:

// SetCustomRenderCallback wouldn't behave like the current AddUserCallback
// it doesn't add any additional calls to the command list, just changes the behavior of whatever gets render
// this is sort of what I thought AddUserCallback did
ImGui::SetCustomRenderCallback([](MyRender& myRenderer, ... ) { myRenderer.doCustomRender( ... ); });
ImGui::Text("this is custom rendered"); // pcmd->CustomRenderCallback != nullptr

ImGui::SetCustomRenderCallback(nullptr);
ImGui::Test("this is not"); // pcmd->CustomRenderCallback == nullptr

```

**Comment by ocornut** [comment]
> SetCustomRenderCallback wouldn't behave like the current AddUserCallback
> it doesn't add any additional calls to the command list, just changes the behavior of whatever gets render
> this is sort of what I thought AddUserCallback did

Those two things are exactly the same thing. I'm suggesting to use callback to change the behavior of whatever you will render afterward, instead of doing actual rendering.

**Comment by sprinkle131313** [comment]
That assumes you know the state you want it to be in though.

```
AddCallback(function_to_select_shader_or_blend_state, args);
AddImage(...); 

// what state are we restoring here?
// we'd need to be conscious of what the state was before we changed it
AddCallback(function_to_restore_shader_or_blend_state);
```

I see your point though, It's not that big of an issue to warrant a change. The small ImTextureId change I did is enough for me anyways.

**Comment by ocornut** [comment]
Implement a stack in the renderer?
