### ISSUE TITLE
GUI Transparent when Margins are set to -1

### ISSUE THREAD

**Issue by TaranVG** [ocornut/imgui#878]
Hey,
I'm making an external overlay, by hiding the window background by putting the margins to -1.

like this:
`
	wchar_t* windowtitle = L"Overlay";

	WNDCLASSEX wc = { sizeof(WNDCLASSEX), ACS_TRANSPARENT, WndProc, 0L, 0L, GetModuleHandle(NULL), NULL, LoadCursor(NULL, IDC_ARROW), NULL, NULL, _T("Overlay"), NULL };
	RegisterClassEx(&wc);
	HWND hwnd = CreateWindowExW(WS_EX_TOPMOST | WS_EX_NOACTIVATE | WS_EX_TRANSPARENT, windowtitle, windowtitle, WS_POPUP, 0, 0, 1920, 1080, NULL, NULL, 0, NULL);
	MARGINS margins = { 0, 100, 0, 0 };
	DwmExtendFrameIntoClientArea(hwnd, &margins);
`
What will result in this:
http://i.imgur.com/vvZMie6.png

Is it possible to display the GUI solid?

**Comment by ocornut** [comment]
> Is it possible to display the GUI solid?

I don't understand the question.

PS: Please do not use imgur for image hosting to ensure the questions and their attachment will be readable in the future, use the github attachment system.

**Comment by TaranVG** [comment]
I want to make the GUI external so I made the background of the window invisible so I could put it over other applications, I did this by changing to margins to -1, but that makes the GUI transparent(It's normal when I put the margins to 0, but not transparent).

**Comment by Keyz55** [comment]
@TaranVG @ocornut 
I'm also very interrested by this.
I want to get rid of the window background

**Comment by ocornut** [comment]
This old PR may help
https://github.com/ocornut/imgui/pull/18

But none of this is really directly related to imgui, it's more of a rendering and input forwarding problems that are out of the desired scope of imgui.

**Comment by Keyz55** [comment]
I dont think that's a big issue. Let me explain you what I wanna do.
First of all, I need to create an overlay that will be going over other applications, that means it need to be transparent. Here is an illustration 
![dd23c8bc2ba64166975b9309c3082005](https://cloud.githubusercontent.com/assets/17110511/19628527/f6d79894-995f-11e6-9e0a-e698df10c2d0.png)

I dont want this blue background. I wanna remove/hide or make it transparent.

Any idea how to achieve this?

Thanks for your time.

**Comment by paulsapps** [comment]
Like Omar said its outside of the scope of ImGui since ImGui just gives you stuff to render, how you render it is up to you and isn't part of the library code. Having a fully transparent window background is highly platform specific.
