### ISSUE TITLE
What's the deal with the GL3W.h header instead of GLEW.h

### ISSUE THREAD

**Issue by Moeman** [ocornut/imgui#880]
I'm really confused about this. Are these the same libraries? The OpenGL tutorial I followed used GLEW instead of GL3W, and on the official OpenGL website GLEW is available in the libraries downloads.

imgui_impl_glfw.cpp crashes for me because I hadn't initialised GL3W, but I changed #include GL3W.h to #include GLEW.h and it works fine now. I'm not using an old version of OpenGL, it's relatively new, 3.2, and it's definitely not fixed function pipeline. I noticed in the OpenGL2 renderer example it just includes GLFW.

Thanks.

**Comment by sprinkle131313** [comment]
It's just a OpenGL function loader, there isn't really anything special about it. GLEW has some problems with newer versions of GL and it can't correctly create a core profile. Creating GL contexts changed at some point and GLEW was never updated, as far as I know, or never correctly updated to match. Anyways it's just an example, you don't have to follow it. I use an OpenGL loader called GLAD, and it's worked for me so far.

**Comment by Tyran37** [comment]
Keep in mind gl3w loads core functions only if you decide to go with that.
You should probably read [this](https://www.opengl.org/wiki/OpenGL_Loading_Library) if you want to know more about what these libraries are and the differences between them.
I personally recommend glad as well, it's lightweight and fully customizable to allow loading only what you really need.

**Comment by ocornut** [comment]
OpenGL requiring those things is quite a unfortunate mess!
I'm just using GL3W for those example because it is simpler and smaller, but as mentioned you probably want to keep using whatever you are already using.

I will add commentary to the Examples to clarify that.

**Comment by ocornut** [comment]
Added those comments now. Thanks for the links. Glad looks quite better.

For those examples I like that gl3w has all its files in the same folder, whereas Glad spans multiple folders, and it's not really worth looking into a change seeing that examples/ are already a pain to maintain, but I'll keep it in mind.

**Comment by r-lyeh** [comment]
FYI :) https://github.com/gingerBill/gl3w-Single-File

**Comment by stolk** [comment]
I had an issue with using GL extensions when I used the imgui-provided gl3w. If you build your own version of gl3w, you can use the flag `./gl3w_gen.py --ext` to get access to the extensions.
