### ISSUE TITLE
g.IO.DeltaTime >= 0.0f  assertion failed

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#881]
Hi
i got this error message time to time . some time at app startup , and some time after startup .
![error](https://cloud.githubusercontent.com/assets/10813427/19596020/db0f0c8e-978c-11e6-8b4d-5fa57c1ccb39.png)

**Comment by ocornut** [comment]
Well, it means what it means. You shouldn't pass a negative delta to imgui...

It could mean that you've called NewFrame() the first time before you could ever set a delta time.
