### ISSUE TITLE
font compressor

### ISSUE THREAD

**Issue by edselmalasig** [ocornut/imgui#882]
I am using bin to c cpp but when I compress a ttf with 128kB size on windows I get compile limit error string is more than 65535 size.

Can someone help?

**Comment by sprinkle131313** [comment]
You could just make a bunch of arrays that are 65535 in size, and then at runtime allocate a buffer big enough to stitch them together. Use the buffer to load the file, then delete the buffer when done. Not ideal but it's one possible solution. I think windows has some sort of resource files as well you can look into, though that wouldn't be crossplatform.

**Comment by ocornut** [comment]
You can modify the code to output it as an array of bytes than than a string.
The source code will be longer but it'll be exactly the same in the binary.
Otherwise just load .ttf file from the disk.

**Comment by ocornut** [comment]
Use the other encoder which doesn't encode as string, or load font from the filesystem.

**Comment by paulsapps** [comment]
Using byte array is the correct workaround to the MSVC literal string limit, assuming you have to have it as hard coded data.

**Comment by ocornut** [comment]
As Paul said you can use a different encoder, tho the provided tool is practical as it allows for compression. The whole point of the compression followed by base85 string encoding is to **reduce source code size** (with no effect on binary.. actually there is an effect as the base85 encoding would have a bigger static footprint than a raw array). It's a weird goal that mostly make senses in the context of providing the default Proggy font embedded within imgui, but you shouldn't have this problem in your own application. 
Just including an array of byte would do the job well enough.

**Comment by ocornut** [comment]
@edselmalasig Just to clarify, we only use strings for base85 encoding, but if you encode normally it'll be an array and then you shouldn't have a limit.
