### ISSUE TITLE
D3Dcompiler problem

### ISSUE THREAD

**Issue by Tonyx97** [ocornut/imgui#886]
I've been using ImGui for months and now I come with my first problem I don't really know how to fix. ImGui uses d3dcompiler.lib and it works properly in 8.1 and 10 OS but in windows 7 it doesn't work because all w7 users don't have d3dcompiler_47.dll. For example, GTA5 is using the 42 one, why am I using 47? I've tried to download old directx sdk but didn't work. I'm not sure what I should do, any ideas about how to use d3dcompiler_42.dll/lib instead of the 47 one?
Thanks in advance.

**Comment by Tonyx97** [comment]
ok nvm I fixed it.

**Comment by deekay42** [comment]
how?

**Comment by ice1000** [comment]
DXSDK
