### ISSUE TITLE
Multi-column layout isn't aware of scroll bar

### ISSUE THREAD

**Issue by mkeeter** [ocornut/imgui#893]
Normally, things that are told to fill their window (with a size of `-1.0f`) adjust based on whether the scroll bar is displayed or not.

This doesn't work when drawing more than one column:
![resize](https://cloud.githubusercontent.com/assets/745333/19908825/44b2b812-a05b-11e6-99bd-82e0239328d9.gif)
Notice that the full-width buttons change size, but the first multi-column buttons do not.

Here's a minimal reproduction:
```
    ImGui::SetNextWindowSize({300, 100}, ImGuiSetCond_Once);
    ImGui::Begin("Demo");
    ImGui::Columns(2);
    ImGui::Button("dear", {100, 0});
    ImGui::NextColumn();
    ImGui::Button("imgui", {-1, 0});
    ImGui::Columns(1);
    ImGui::Button("hello world", {-1, 0});
    ImGui::Button("goodbye world", {-1, 0});
    ImGui::Button("hello there", {-1, 0});
    ImGui::End();
```

I'd be glad to dig into this myself if you can give me a few pointers for where to look!

**Comment by ocornut** [comment]
I forgot the exact reason now, but it was intentional as it made lots of problems easier to solve. Last time I looked into it (1+ year ago) came to the conclusion it was better not fixing. 

I may dig back into it at some point, ideally we'd fix it. It is causing you a specific problem or it is just a thing you noticed?

**Comment by mkeeter** [comment]
It's not particularly critical, but I did run into this while doing real work:
I'm doing a layout that uses both columns and `ImGui::SameLine`, and noticed the discrepancy in where the right edge lines up.

<img width="318" alt="screen shot 2016-11-01 at 8 46 57 pm" src="https://cloud.githubusercontent.com/assets/745333/19912914/5b87b452-a074-11e6-80d1-75f1e0351d40.png">

I fixed it by shrinking the `SameLine` layout by `ImGui::GetStyle().ScrollbarSize`, which is inelegant but makes the edges line up nicely.

**Comment by ocornut** [comment]
This should be fixed now. @mkeeter. As you are using `Columns`, would be interested in seeing if you are seeing any issue with the latest update.
