### ISSUE TITLE
PathFill and PathStroke

### ISSUE THREAD

**Issue by alanyangbo** [ocornut/imgui#895]
Why the charts of same data source be drawn  with PathFill and PathStroke are much different?Thanks in advance：）
<img src="http://ww1.sinaimg.cn/large/006tzUeNjw1f9hru9brzzj30x80msmzw.jpg"/>
//=====code=============
<img src="http://ww4.sinaimg.cn/large/006tzUeNjw1f9hsrjpgh8j30fz0fadhk.jpg"/>

**Comment by ocornut** [comment]
We only have a path filling routine for convex polygons (the underlying function is called `AddConvexPolyFilled`). This probably should be clarified in the comments for `PathFill`.

You could workaround this by drawing it like a histogram, horizontal chunk by horizontal chunk.

**Comment by ocornut** [comment]
Also see this thread for discussing/code of non-convex filling:
https://github.com/ocornut/imgui/issues/760

**Comment by alanyangbo** [comment]
@ocornut Thanks so much for response.
