### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#900]
Is there a color picker I can implement in ImGui I am using version 1.49 WIP? If so, can you let me know how to get one working with this version please?

**Comment by ocornut** [comment]
There is an unfinished branch you can merge
https://github.com/ocornut/imgui/tree/2016-02-colorpicker

Please refer the thread that appears if you search for "color picker" here (and ask further questions there!)
https://github.com/ocornut/imgui/issues/346

Thanks.
