### ISSUE TITLE
Problems With Draw Chinese

### ISSUE THREAD

**Issue by huoji120** [ocornut/imgui#905]
hello, I am the first use IMGUI ;
I try to draw chinese but not work.
code:

```
ImFontConfig font_config;
font_config.OversampleH = 1; //or 2 is the same
font_config.OversampleV = 1;
font_config.PixelSnapH = 1;
io.Fonts->AddFontFromFileTTF("F:\\asimhei.ttf", 18.0f, &font_config, io.Fonts >GetGlyphRangesChinese());
```

F:\\asimhei.ttf font file exist
ImGui::Text("\x68\x65\x6C\x6C\x6F\x20" "\xE8\x8F\x9C\xE5\x8D\x95\x20" "\xE5\x9C\xA8\xE5\x93\xAA\x20" "a" "\xE9\x87\x8C\xE6\x96\x87" "\xE4\xBB\x3F\xE6\x88\x91\xE6\x98\xAF\xE4\xB8\xAD\xE6\x96\x87\x61");
ImGui::Text(charenc("你好IMGUI"));
ImGui::Text("你好,IMGUI");
Can not Draw Chinese:
it Draw "hello ???????????[] ????? ???" .... "????? IMGUI"
and i try to debug AddFontFromFileTTF

```
ImFont* ImFontAtlas::AddFontFromFileTTF(const char* filename, float size_pixels, const ImFontConfig* font_cfg_template, const ImWchar* glyph_ranges)
{
    int data_size = 0;
    void* data = ImLoadFileToMemory(filename, "rb", &data_size, 0);
    if (!data)
    {
        IM_ASSERT(0); // Could not load file.
		Z::PrintMessage("Colud Not Load File");
        return NULL;
    }
    ImFontConfig font_cfg = font_cfg_template ? *font_cfg_template : ImFontConfig();
    if (font_cfg.Name[0] == '\0')
    {
        // Store a short copy of filename into into the font name for convenience
        const char* p;
        for (p = filename + strlen(filename); p > filename && p[-1] != '/' && p[-1] != '\\'; p--) {}
        snprintf(font_cfg.Name, IM_ARRAYSIZE(font_cfg.Name), "%s", p);
    }
	Z::PrintMessage("Load Good");
    return AddFontFromMemoryTTF(data, data_size, size_pixels, &font_cfg, glyph_ranges);
}
```
it Print "Load Good" .
so i have not idea how can i do.

**Comment by huoji120** [comment]
@ocornut

**Comment by ocornut** [comment]
```
ImGui::Text("\x68\x65\x6C\x6C\x6F\x20" "\xE8\x8F\x9C\xE5\x8D\x95\x20" "\xE5\x9C\xA8\xE5\x93\xAA\x20" "a" "\xE9\x87\x8C\xE6\x96\x87" "\xE4\xBB\x3F\xE6\x88\x91\xE6\x98\xAF\xE4\xB8\xAD\xE6\x96\x87\x61");
```
This is not UTF-8 data.

With C++11 you can use u8"你好" syntax to create UTF-8 string literal. It should emit "\xE4\xBD\xA0\xE5\xA5\xBD"

你 in UTF-8 is E4 BD A0 
好 in UTF-8 is E5 A5 BD 

See
http://www.ltg.ed.ac.uk/~richard/utf-8.html

**Comment by huoji120** [comment]
not work 
ImGui::Text("\xE4\xBD\xA0\xE5\xA5\xBD");
maby not support UTF-8?

**Comment by Wohlstand** [comment]
Does your compiler reads files in UTF-8? I'll try that myself

**Comment by huoji120** [comment]
not good idea make  files to UTF-8,because i use  \xE4\xBD\xA0\xE5\xA5\xBD to draw.

**Comment by Wohlstand** [comment]
in my case all files are UTF8 by default (GCC, Clang, MinGW are reading them as UTF-8)

**Comment by Wohlstand** [comment]
Okay, just tried myself: it seems rendering ASCII-only (same trouble with Cyrillic)

**Comment by ocornut** [comment]
```
    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->AddFontFromFileTTF("c:\\Windows\\Fonts\\ArialUni.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesChinese());
```
+
```
ImGui::Text("\xE4\xBD\xA0\xE5\xA5\xBD");
```

![chinese](https://cloud.githubusercontent.com/assets/8225057/20247335/dce19640-a9c9-11e6-8592-c1c8dfac156b.PNG)

It is working and it pretty much always worked.
You are either passing wrong UTF-8 data or using a font that doesn't have those character, or not using the right font. 

Check Style Editor->Fonts for details about loaded fonts.

![font](https://cloud.githubusercontent.com/assets/8225057/20247342/16eeb052-a9ca-11e6-8581-665cd308a343.PNG)
