### ISSUE TITLE
Newbie issue

### ISSUE THREAD

**Issue by wiotq** [ocornut/imgui#906]
Hello, i've started using imgui and got some problems. I want to create menu with buttons.
Maybe im just blind or bain damaged dunno :sob: 
https://youtu.be/ycgAEgKLHqM
`		ImGui::Begin( charenc( "test" ), &Vars.Menu.Opened, ImVec2( 600, 500 ), 0.9f, ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse );
		{
			if (ImGui::Button(charenc("test1"))) &Vars.Menu.button1;
			ImGui::SameLine();
			if (ImGui::Button(charenc("test2"))) &Vars.Menu.button2;
			ImGui::SameLine();
			ImGui::Button(charenc("button3")) &Vars.Menu.button3;
			ImGui::SameLine();
			ImGui::Button(charenc("button4")) &Vars.Menu.button4;
			if (&Vars.Menu.button1)
			{
				ImGui::Text(charenc("test1"));
			}
			if (&Vars.Menu.button2)
			{
				ImGui::Text(charenc("test2"));
			}
		}
		ImGui::End();

**Comment by ocornut** [comment]
1) Please describe the problem in the subject line when posting a bug.

2) Your code doesn't make sense. I presume you are learning C++ at the moment so I am going to give a few advices. 

`&Vars.Menu.button3` is taking the address of your boolean, it isn't modifying anything. That statement after the if does nothing:
```
if (ImGui::Button(charenc("test1"))) &Vars.Menu.button1;
```

You probably want to store your "current panel" index an integer and have the buttons change it.

```
if (ImGui::Button(charenc("test1"))) &Vars.Menu.Current = 1;
ImGui::SameLine();
if (ImGui::Button(charenc("test2"))) &Vars.Menu.Current = 2;
```

Then test for that value:
```
if (&Vars.Menu.Current == 1)
{
 // do stuff
}
```

3) At this point you are looking for programming advices and we unfortunately can't provide programming/C++ instructions here. Please ask on programming forums! (I'm also sorry to say that the fact that it is used for cheating in games reduces my will to help a little further.)
