### ISSUE TITLE
[Possible Enhancement] ImGui::SetStylePointer(...)

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#907]
...well, I still have to consider if this idea is good or bad and if it's easy or difficult to implement.

The idea is to allow users to have their own set of (static, owned by the user) ImGuiStyles, and to be able to switch them at runtime without the cost of deep copying the whole style structure.

@ocornut: I don't need this ATM. It's just an idea. Feel free to close this issue at any time.

[Edit:] I initially thought about having a stack of style pointers (ImGui::Push/PopStylePointer), but now I think that a way to just change/restore the default style pointer would be better (I've changed the title of this post).

**Comment by ocornut** [comment]
The whole structure is about 800 bytes (flat, 1 memcpy) and don't really see lots of use for changing whole style so often. Perhaps in some extreme/odd case I can imagine a user to change the entire style for each window, even at that pace the 800 bytes memcpy would be negligible compared to the processing associated to drawing to a window. I don't think it is worth adding anything extra.

Same as other threads, I'd prefer not coming up with features that you don't have actually need or that are solving a real problem for you. Let's prioritize real problems.

**Comment by Flix01** [comment]
OK.
