### ISSUE TITLE
[Possible enhancement] Adding an "hidden" boolean inside ImGui::Window

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#908]
...well, I still have to consider if this idea is good or bad and if it's easy or difficult to implement (again).

The idea is to be able to filter the visibility of ImGui::Windows at runtime (based on their name), with something like:
```c++
void ImGui::SetWindowVisible(const char* name,const bool visible,bool nameIsASubstringFilterForAllWindows=false);
// Or just ImGui::SetWindowHidden(...) instead
```

I was thinking this could help people to filter out a group of Windows together (for example people who want to keep in-program options visible, but hide all program-editor windows: this problem can probably be solved using multiple instances too).

@ocornut: I don't need this ATM. It's just an idea. Feel free to close this issue at any time.

**Comment by ocornut** [comment]
I don't understand this at all. If you don't want to a show a window, don't call Begin(). It's entirely up to the user with maximum flexibility already.

( I'd also prefer not suggesting features you don't actually need. We already have a million useful things to do. )

**Comment by Flix01** [comment]
OK.

> I don't understand this at all. If you don't want to a show a window, don't call Begin(). It's entirely up to the user with maximum flexibility already.

I know it, I was just suggesting a shortcut for lazy users.

**Comment by ocornut** [comment]
> I know it, I was just suggesting a shortcut for lazy users.

But it wouldn't be right, it would be paying all the cost of processing widgets and vertex buffers and then dropping that output.
