### ISSUE TITLE
Allow multiple fonts at runtime + embed ProggyTiny font

### ISSUE THREAD

**Issue by ocornut** [ocornut/imgui#91]
Most of the code allows for one font per window but ImBitmapFont store UV into a single texture so effectively the data provided by default doesn't really allows it.

I would like to:
- embed the smaller ProggyTiny font into the default texture, figure out a way to elegantly patch the ImBitmapFont data accordingly (currently data in read-only segment so might be to copy it).
http://upperbounds.net/index.php?menu=download
- allow user to switch font on the fly, even within a same window
- while keeping in mind longer-term goals such as the ability to load TTF fonts via stb_truetype and use arbitrary textures (discussed and pretty much implemented in https://github.com/ocornut/imgui/issues/73 ), so while both default fonts will be in a same texture effort should be provided to allow multiple textures.

**Comment by ocornut** [comment]
FYI I am working on revamping the font system to be based on stb_truetype.h now

  https://github.com/ocornut/imgui/issues/102#issuecomment-68707241

And there will be a default but odd path reading an embedded bitmap font for the sake of simplicity.

**Comment by memononen** [comment]
I case you feel tempted to embed a true type font. I just found nice, simple, legible (even on small sizes) and small (17kB) TTF font called Karla: http://www.google.com/fonts/specimen/Karla

**Comment by ocornut** [comment]
Thanks! Sound like a good one along with ProggyClean.
Any idea for a simple decompression stub I could use to store it compressed?
ZIP only gets it down to 10 KB so I'm not expecting an exciting compression rate on Karla but ProggyClean is 41 KB uncompressed and compresses much better.

**Comment by memononen** [comment]
I was about to say that you might end up having mode code than data if you try to be too smart :) stb_decompress sounds just about right.
Tangential: I started to change the rendering code to anti-aliased at some point. Would you mind that, or do you prefer the pixelated look?

**Comment by ocornut** [comment]
"Tangential: I started to change the rendering code to anti-aliased at some point. Would you mind that, or do you prefer the pixelated look?"

The rendering code of what, you mean of ImGui? (didn't know you were doing something with it)
Anti-aliased rendering yes! May depend if it has any drawback. I like the idea that ImGui can be made very compact by omitting any extra padding / spacing, this is useful for certain type of apps with lots of information (e.g. we have a PS4 gpu/cpu profiler on a project here that does that, items are the size of text using the smallest font). So for example in this specific super compact case you'd want rectangles to be pixel aligned, no visible transparent pixels, neighbours rectangle touching each others. So the ant-aliased path just has to be tweaked to allow those things with the right settings.

**Comment by memononen** [comment]
Cool, I'll pick it up again when I have time. My idea was to first change the code to use more common draw functions (draw poly, draw polyline) and then add the versions on top. And I agree that it should be pixel perfect, so the AA would mostly show at rounded corners, etc.

**Comment by ocornut** [comment]
FYI as pointed in the other topic the font change will remove reliance on PNG and imgui will be generating the texture, so we can stick in any piece of graphics in there, if that's of use to drawing shapes.

**Comment by ocornut** [comment]
I have merged the TTF branch into trunk.
It uses a font atlas to assemble multiple fonts into the same texture. ImFontAtlas / ImFont are designed so you can create your own atlas aside from the "main" one if for some reason you want multiple textures.
You can PushFont() / PopFont() during rendering.
