### ISSUE TITLE
Using std::vector with ListBox/Combo

### ISSUE THREAD

**Issue by mumin16** [ocornut/imgui#911]
It is too bad that we can not use  vector string in listbox. My solution is not working:

vector<string> symbols={"a","b",,....};
const char* strs[1024] = {0};

for (std::string::size_type i = 0; i < symbols.size(); ++i) {
	strs[i] = (char*)malloc(strlen(symbols.at(i).c_str()) + 1);
        strcpy((char*)strs[i], symbols.at(i).c_str());						
}

static int listbox_item_current = 1;
ImGui::ListBox("Symbols list", &listbox_item_current, strs, symbols.size(), 4);

What is problem?

**Comment by ocornut** [comment]
You should absolutely not attempt to copy/duplicate data this way, it's really slow.

ListBox() has an override where you can pass a function pointer to access your data:
```
bool ListBox(const char* label, int* current_item, bool (*items_getter)(void* data, int idx, const char** out_text), void* data, int items_count, int height_in_items = -1)
```

Use something like:

```
bool VectorOfStringGetter(void* data, int n, const char** out_text)
{
  const vector<string>* v = (vector<string>*)data;
  *out_text = v[n].c_str();
  return true;
}
ImGui::ListBox("Symbols", listbox_item_current, VectorOfStringGetter(, (void*)&symbols, (int)symbols.size());
```

That later ListBox() call you probably want to wrap into a helper functor that takes a const std::vector<string>& parameter.

PS: When you ask a question please fill in the subject line with a short description of the question/content.

**Comment by ocornut** [comment]
Also see:
https://eliasdaler.github.io/using-imgui-with-sfml-pt2
