### ISSUE TITLE
Absorb mouse/keyboard action

### ISSUE THREAD

**Issue by PlutoniumHeart** [ocornut/imgui#912]
Hi,

I am using imgui to add some control to my scene, however, I am also using some keyboard short cuts and mouse actions to control/rotate the scene.

I noticed that even when I am dragging my GUI, the scene behind it is also rotating, is there a way to for the imgui to absorb mouse/keyboard action, or do I have to implement this by myself?

Thanks!

**Comment by ratchetfreak** [comment]
There is a flag you can check `WantCaptureMouse` in the `ImGuiIO` struct that tells the application that it is capturing the mouse. 

You can use this to null out the input for the underlying scene.

**Comment by PlutoniumHeart** [comment]
That works nicely, thank you!
