### ISSUE TITLE
Metrics Window Showing Negative ms/frame

### ISSUE THREAD

**Issue by sprinkle131313** [ocornut/imgui#916]
I'm using the actual delta time between ImGui frames and the values stay in a range between 6 and 16 ms. The value displayed by the metrics window seems to be wrong as it jumps around, sometimes switching between negative and positive numbers. Is the "io.DeltaTime" value suppose to be a constant?

**Comment by ocornut** [comment]
No it doesn't have to be a constant, it's fine to have it be variable.
I don't understand how Framerate could be <0 unless you passed negative values for `io.DeltaTime`, and we have an assert in NewFrame() preventing that to happen (unless you have disabled asserts).

Could you make a repro?

**Comment by sprinkle131313** [comment]
I solved it, the timer I was using initializes to a large value. Clamping the value fixed it.

Code that reproduces the error:

```
static bool first = false;

if(first)
{
    io.DeltaTime = 0.01f * (rand() % 10 + 1);
}
else
{
    io.DeltaTime = std::numeric_limits<float>::max() / 2;
    first = true;
}

// igNewFrame();
// ...

```

**Comment by ocornut** [comment]
Cool.
I don't think this needs an extra assert. We could assert against FLT_MAX but it is rather unlikely/unusual, passing NaN is actually more likely there. You should probably pass DeltaTime 0.0 for your first time if for some reason you can't compute it.
