### ISSUE TITLE
Windows's fopen() Assertion if path contains utf-8

### ISSUE THREAD

**Issue by ecraven** [ocornut/imgui#917]
Using imgui in a game, we pass the pathnames as utf-8 to it. Under windows, it seems ImLoadFileToMemory uses fopen, which does not deal with utf-8 correctly, but just uses the "default locale". Would it be possible to just make every pathname in imgui work correctly with utf-8? Otherwise cross-platform support is even harder :-/

Thanks for a great library!

**Comment by ocornut** [comment]
Pinging @dougbinks as he had the same problem last week.
What would be the correct way to open files with UTF-8 path under Windows?

**Comment by Wohlstand** [comment]
on Windows fopen reads ANSI-only. To have support of UTF8 paths you must convert your string into std::wstring and use _wfopen (then use same fread/fwrite, fprintf, fscanf, etc. as is).
Look to an example to force UTF8 paths support on the Windows:
```C++
std::string filePath = "C:/Папка Васи/Что-то.txt";

#ifndef _WIN32
    FILE *f = fopen(filePath.c_str(), "rb");
#else
    std::wstring filePathW;
    filePathW.resize(filePath.size());
    int newSize = MultiByteToWideChar(CP_UTF8, 0, filePath.c_str(), filePath.length(), const_cast<wchar_t *>(filePathW.c_str()), filePath.length());
    filePathW.resize(newSize);
    FILE *f = _wfopen(filePathW.c_str(), L"rb");
#endif

    fread(&xxx, 1, xxx_size, f);

```

**Comment by mooskagh** [comment]
Windows'es native encoding is UTF-16, so I cannot think out anything better than somehow to convert filename from utf-8 to utf-16 (using MultiByteToWideChar()) and then use _wfopen().
It's ugly though as requires allocating buffer etc.

**Comment by dougbinks** [comment]
I converted the filenames to ASCII with GetShortPathName for use in imgui, see https://github.com/dougbinks/RuntimeCompiledCPlusPlus/blob/Avoyd/Aurora/RuntimeCompiler/FileSystemUtils.h#L528-L544

**Comment by Wohlstand** [comment]
>  converted the filenames to ASCII with GetShortPathName for use in imgui, see https://github.com/dougbinks/RuntimeCompiledCPlusPlus/blob/Avoyd/Aurora/RuntimeCompiler/FileSystemUtils.h#L528-L544
I think, is not good call MultiByteToWideChar twise while it internally doing lot of works. Instead while you converting UTF8 into UTF16, just make buffer equal to UTF8 string, then cut tail when you got the resulted size. When converting UTF16 to UTF8, just make buffer of double size, then same - cut tail.

**Comment by dougbinks** [comment]
Converting all fopen to _wfopen and supporting UTF8 to UTF16 is certainly the right way to approach this, I used the GetShortPathName solution since I needed a solution for more than just imgui this was the fastest way to get this with no code change needed for imgui.

**Comment by Wohlstand** [comment]
In my case I just used a custom function (on non-Win32 platforms just a macro to regular fopen) which accepts same arguments as fopen, but inside I converting a string into UTF8 and then passing _wfopen

**Comment by ecraven** [comment]
hm.. so this boils down to either imgui converting internally (thus providing an actual utf-8 interface), or me converting externally, and imgui pretending it supported utf-8 in pathnames, while I only pass it ascii on windows?

**Comment by ocornut** [comment]
I could probably implement the utf-8 to utf-16 conversion + _wfopen() under Windows.
How about OSX, Linux, etc?
Would it make sense for your app to obtain those filenames in utf-8 in the first place?

**Comment by dougbinks** [comment]
I think that for OSX and Linux nothing needs to change for dear imgui since on both fopen accepts UTF-8 - though there is a slight complexity on Linux as although most systems are default set up to have a UTF-8 locale not all do. However the app can handle everything required (using iconv for example) since the interface to fopen is always the same, it's how the buffer is interpreted which is changed by the locale.

**Comment by ocornut** [comment]
Thank you Doug. Would MultiByteToWideChar() work with non-MSVC Windows enviroment, or should I test for `_MSC_VER`?

**Comment by dougbinks** [comment]
Sadly this depends on the non-MSVC environment, it's a bit of a mess. I would use _MSC_VER and await contributions from anyone developing with MinGW or PellesC etc (Cygwin should go through a POSIX interface so be like Linux I would hope).

**Comment by ocornut** [comment]
I will use the UTF-8>wchar functions internal to imgui for the _wfopen() path + test with _MSC_VER for now.

**Comment by ocornut** [comment]
Should be done now.
@ecraven @dougbinks @Wohlstand let me know if that looks all ok to you.

**Comment by dougbinks** [comment]
Just tested this on Windows 10, VS2015 with a Sanskrit directory for my assets (fonts) and this worked wonderfully. Many thanks!

**Comment by Wohlstand** [comment]
I think, you need to use _WIN32 macro than _MSC_VER, because many custom compilers like MinGW will still have this bug

**Comment by ocornut** [comment]
@Wohlstand Doesn't MinGW comes with its own standard library? How does fopen() perform there?

**Comment by Wohlstand** [comment]
@ocornut, MinGW != CygWin, and it's purpose to build native Windows apps, therefore most of things are dealing with Windows's stuff.
Yea, it has own runtime, but in result it is more same as MSVC's by standard WinAPI and fopen / _wfopen / etc. functions. MinGW is able to build application which will work even on Windows 95 (in case of avoiding usage impossible functions on it) while latest versions of MSVC are hates to keep backward compatibility with older Windows versions. MinGW has no fmemopen function like CygWin and unix systems, for example. Main difference between MinGW and MSVC compiler that MinGW faster receiving a most modern C++ standard features (MinGW itself is a native port of GCC for Windows which specifying to it) while MSVC usually doing that with a big delaying.

**Comment by dougbinks** [comment]
@Wohlstand 

[See my earlier comment](https://github.com/ocornut/imgui/issues/917#issuecomment-263128693) about my advice to @ocornut  - if you have a working tested solution to fopen on MinGW then a contribution would be the recommended path.

My own experience with MinGW is that there is sufficient difference in behaviour (especially of win32 POSIX APIs), that testing is needed, especially as the documentation is poor. Many POSIX APIs behave more like the their Unix variants than the Windows VS ones.

**Comment by Wohlstand** [comment]
@dougbinks, you seems have very old MinGW version. I using always fresh version (4.9 or 5+) (even 4.7 is same). In all my cases fopen accepts ANSI string for locale and dislikes UTF-8. Only converting into UTF-16 and using _wfopen allows me open file by right UTF-8 path.

# My working MinGW example:

## INI Processing - INI parser with API like QSettings, but in pure STL
https://github.com/WohlSoft/IniProcessing/tree/master/src
I.e.:
https://github.com/WohlSoft/IniProcessing/blob/master/src/ini_processing.cpp#L338

(included test application is requires a Qt 5, but IniProcessing class itself must don't require any Qt API). All source codes I saving into UTF-8 with no BOM. (MSVC reads UTF-8 code only if BOM presented. MinGW is reads UTF-8 code always).

**Comment by dougbinks** [comment]
@Wohlstand I think you're misunderstanding me.

I don't have an old MinGW version since I don't have a MinGW version installed at all currently. Hence the request for you to check your proposed solution with imgui and submit a pull request or at least let @ocornut know it works.

My apologies to everyone if I have confused issues.

**Comment by Wohlstand** [comment]
@dougbinks, oh, okay, wait a sec

**Comment by Wohlstand** [comment]
@dougbinks , @ocornut , I just built SDL2 OpenGL2 example by MinGW, and bug still be presented (it will assert on attempt open font in the non-ASCII folder).
But, when I replaced _MSC_VER with _WIN32, everything works fine (try ImguiExample-failed.exe (built as-is) and then ImguiExample-fixed.exe (built with my fix))

http://wohlsoft.ru/docs/Software/imgui-mingw-example-449c47c.7z

**Comment by Flix01** [comment]
I think using **_WIN32** is the way to go, and then we can add exceptions for other Windows compilers on request if necessary (and AFAIK _WIN64 defines _WIN32 too).

**Comment by Wohlstand** [comment]
@Flix01, _WIN32 is always defined even Windows build for Win64, _WIN64 means build is targeted to pure x64.

**Comment by Flix01** [comment]
@Wohlstand, yep!

**Comment by ocornut** [comment]
Should be ok now.

**Comment by Flix01** [comment]
As I've posted [here](https://github.com/ocornut/imgui/commit/104b3810237d4a959ff421fea14c6fc0fd8d0b79), as far as I can see in _imgui_internals.h_:
```c++
IMGUI_API FILE*         ImOpenFile(const char* filename, const char* file_open_mode); 
```
it's declared but never defined (in _imgui.cpp_ it's called **ImFileOpen**).

That makes it inaccessible from _imgui_internals.h_.

**Comment by ocornut** [comment]
Correct, sorry for the mismatching declaration. The correct name is ImFileOpen() and I have renamed ImLoadFileToMemory to ImFileLoadMemory for consistency. (It might affect some code using those internals but the renaming will be obvious)

**Comment by Flix01** [comment]
Thanks!
