### ISSUE TITLE
Multiple CreateWindow in the same application

### ISSUE THREAD

**Issue by BrunoGysin** [ocornut/imgui#922]
Is there the possibility of creating several CreateWindow (Directx11) with imgui?

I tried to create a simple class using the example in directx 11, However I had several problems.

But first is there a possibility for what I need?

thanks

**Comment by ocornut** [comment]
> Is there the possibility of creating several CreateWindow (Directx11) with imgui?

CreateWindow and DX11 have nothing to do with imgui.

If what you want are multiple imgui contexts, there are functions bearing the name _Context_ to create and change the current context, so you can have multiple, separate instances of imgui running in parallel.
