### ISSUE TITLE
Dynamically closing CollaspingHeader

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#924]
I have the following code snippet:

ImGui::Begin("Control Centre II", &ImGui_WindowOpened, ImVec2(0, 0), 0.5f, ImGuiWindowFlags_AlwaysUseWindowPadding | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoSavedSettings);
ImGui::SetWindowPos(ImVec2(1602, 2)); 
ImGui::SetWindowSize(ImVec2(right_menu_width, Display::GetScreenHeight() - 2));
	if (ImGui::CollapsingHeader("Image Library", 0, true, true))
	{
         // Do stuff
        }
ImGui::Checkbox("Show Grayscale", &show_grayscale_image);

How can I dynamically force the “Image Library” CollaspingHeader to close/open when I check the “Show Grayscale” checkbox?

**Comment by ocornut** [comment]
You can use `SetNextTreeNodeOpen()` for that, order that is an ordered primitive so you need to call it before CollapsingHeader() and therefore it is easier just to move your checkbox above it.

**Comment by djones4487169** [comment]
Soory ocornut can you give me a quick code snippet example I have to have the checkbox after the CollaspingHeader on the GUI?

**Comment by ocornut** [comment]
Move the Checkbox() before CollapsingHeader()

```
if (CheckBox(...))
   SetNextTreeNodeOpen(...)

if (CollapsingHeader(...))
{
}
```

**Comment by djones4487169** [comment]
Is it not possible to have the Checkbox() shown after the CollaspingHeader() and somehow get the same result as above? Can we access an id or something for that particular widget and change its state?

**Comment by ocornut** [comment]
It isn't possible at the moment. It is a missing feature.

If you need the checkbox to be below you can store your own data to call SetNextTreeNodexx on the next frame, or manipulate the cursor position to draw the checkbox first then move back upward and draw the tree node.

**Comment by ocornut** [comment]
Hmm.. actually you can access the StateStorage and manually set the value corresponding to the treenode id to 0 and 1 and that would work currently.

**Comment by djones4487169** [comment]
Can you give me a code example of how to access the StateStorage if that would work please?

**Comment by pdoane** [comment]
Manipulating the state storage works and it can sometimes be a cleaner solution.  With the checkbox after the header, it will happen on the next frame though.  If that's acceptable, you can get the same behavior with SetNextTreeNodeOpen:

```
static bool changedValue;
if (changedValue)
{
   SetNextTreeNodeOpen(...);
   changedValue = false;
}

if (CollapsingHeader(...))
{
}

if (CheckBox(...))
   changedValue = true;

```

My preferred approach would be to allow the app to maintain the open state and pass in a bool* to ImGui.  This would simplify dynamic manipulation and the existing entrypoints can continue to use the StateStorage mechanism.

**Comment by djones4487169** [comment]
Yes, got it working. Thanks

**Comment by ocornut** [comment]
@pdoane 
> My preferred approach would be to allow the app to maintain the open state and pass in a bool* to ImGui. This would simplify dynamic manipulation and the existing entrypoints can continue to use the StateStorage mechanism.

I sort of agree this would be good. 

- The node stills needs a unique ID for its regular button behavior.

- The _Internal_ `TreeNodeBehavior` `TreeNodeBehaviorIsOpen` would probably need some rework and an extra optional `bool*` as those functions are designed to lazily add to the storage only when needed. Reworking those isn't so much of a problem. We also need to honor SetNextTreeNodeOpened() functions for completeness (which would set the bool).

- However adding more public API however is a bigger problem.? We could be adding:
```
IMGUI_API bool TreeNodeEx(const char* str_id, bool* p_open, ImGuiTreeNodeFlags flags, const char* fmt, ...) IM_PRINTFARGS(3);
IMGUI_API bool TreeNodeEx(const void* ptr_id, bool* p_open, ImGuiTreeNodeFlags flags, const char* fmt, ...) IM_PRINTFARGS(3);
IMGUI_API bool TreeNodeExV(const char* str_id, bool* p_open, ImGuiTreeNodeFlags flags, const char* fmt, va_list args);
IMGUI_API bool TreeNodeExV(const void* ptr_id, bool* p_open, ImGuiTreeNodeFlags flags, const char* fmt, va_list args);
```
