### ISSUE TITLE
Clicking on button & holding down prevents hovering over any other item

### ISSUE THREAD

**Issue by CarlRewind** [ocornut/imgui#925]
I'm trying to do a drag-and-drop thing for parenting in a data tree using Selectables and TreeNodes, and it involves the user clicking down on one of the items, dragging the mouse over to the item they want to parent their selection to, then releasing to complete the act. For the releasing part, I'm using IsItemHovered to check which item they are hovering over.

Unfortunately it seems that IsItemHovered will only recognise the initially clicked button while the mouse button is held down (i.e. it'll return true only if that button is hovered over; everyone else gets ignored). Is there a flag I could set somewhere to change this (assuming it's intended behaviour to begin with)? Thanks in advance.

**Comment by ocornut** [comment]
This is intended and desirable behavior for most cases, as you don't want most widgets to visually react in that situation.

The function you want to use here, and it may be oddly named, is `IsItemHoveredRect()`.

```
bool IsItemHovered();      // is the last item hovered by mouse (and usable)? or we are currently using Nav and the item is focused.
bool IsItemHoveredRect();  // is the last item hovered by mouse? even if another item is active or window is blocked by popup while we are hovering this
```

**Comment by CarlRewind** [comment]
Fair enough. IsItemHoveredRect() works wonders, thanks.
