### ISSUE TITLE
Rendered but not displayed

### ISSUE THREAD

**Issue by Tbone2401** [ocornut/imgui#926]
Dear Mr Ocornut

I'm having a bit of trouble displaying the ImGui.. 
I am using NSight to check what get's rendered, and it's showing me no errors, it renders the display, but it doesn't show up on screen.
![screenshot_3](https://cloud.githubusercontent.com/assets/20252795/20798461/335c288c-b7df-11e6-82b7-3cefafe61491.png)
The screenshot shows the buffer and shows a drawcall but it is simply not showing me anything.
Below is the GameLoop of my engine.

`bool show_test_window = true;
	//Clear Backbuffer
	m_pDeviceContext->ClearRenderTargetView(m_pCurrentRenderTarget->GetRenderTargetView(), reinterpret_cast<const float*>(&Colors::CornflowerBlue));
	m_pDeviceContext->ClearDepthStencilView(m_pCurrentRenderTarget->GetDepthStencilView(), D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL, 1.0f, 0);
	ImGui_ImplDX11_NewFrame();

	//******
	//UPDATE
	SceneManager::GetInstance()->Update();
	//****
	//DRAW
	SceneManager::GetInstance()->Draw();
	ImGui::SetNextWindowPos(ImVec2(650, 20), ImGuiSetCond_FirstUseEver);     // Normally user code doesn't need/want to call it because positions are saved in .ini file anyway. Here we just want to make the demo initial state a bit more friendly!
	ImGui::ShowTestWindow(&show_test_window);
	ImGui::Render();

	//Present Backbuffer
	m_pSwapchain->Present(0,0);`

**Comment by ocornut** [comment]
Did you solve your problem?

**Comment by Tbone2401** [comment]
Yes I did, apparently my text renderer was the issue. As soon as I deleted that it was fixed.
Now I just display the normal text with ImGui :)
