### ISSUE TITLE
Loop over all widgets

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#927]
Is there a way to loop over (or query) each widget and check its status e.g. Checkbox() checked or not,  along with any values that have been set using e.g. InputFloat()?

**Comment by ratchetfreak** [comment]
normally that is your data (you pass pointers to the place where the state is stored when calling Checkbox or InputFloat)

You can pass around a reference struct where those things are stored and have them all in one place instead of `static` locals.

**Comment by djones4487169** [comment]
OK I think I get the idea but could you elaborate with a quick example snippet on your second statement referring to the reference struct all being in one place?

**Comment by ocornut** [comment]
It looks like you are misunderstanding the design and intent of dear imgui.
It doesn't store any of your data by design. You own your data and therefore want to be iterating your data if you need to perform any specific query.
