### ISSUE TITLE
InputFloat3 not aligned

### ISSUE THREAD

**Issue by edin-p** [ocornut/imgui#929]
Hi! I'm not sure why but the InputFloat3 isn't aligned on Position like the rest...

![1470115_1597586917166788_2108325710428084400_n - copy](https://cloud.githubusercontent.com/assets/12642134/20840594/00f24890-b8b1-11e6-8d46-b0764ea2b388.jpg)

Code: 
  
```
static bool closable_group = true;
if (ImGui::CollapsingHeader("Transform Component", &closable_group, ImGuiTreeNodeFlags_DefaultOpen)) {
	static float f3[]{ 0,0,0 };

	ImGui::Text("Position");
	ImGui::SameLine(80);
	ImGui::PushItemWidth(-1);
	ImGui::InputFloat3("", f3, 3);
	ImGui::PopItemWidth();

        ImGui::Text("Rotation");
	ImGui::SameLine(80);
	ImGui::PushItemWidth(-1);
	ImGui::InputFloat3("", f3,3);
	ImGui::PopItemWidth();

	ImGui::Text("Scale");
	ImGui::SameLine(80);
	ImGui::PushItemWidth(-1);
	ImGui::InputFloat3("", f3, 3);
	ImGui::PopItemWidth();
}
```

**Comment by wasikuss** [comment]
This is correct.

**Comment by edin-p** [comment]
I fixed it by drawing in a child window (actually child window in a child window)... 
It's caused by WindowPadding style var but I'm confused why is it offseting only the first InputFloat3.. 
I guess its by design or maybe not?!

**Comment by wasikuss** [comment]
can you shrink code that generates visual bug as shown above to minimum? remove all unrelated code and post in attachment here ;)

**Comment by ocornut** [comment]
Same here, your code doesn't exhibit the bug here. A more complete repro is desirable.

(Aside from the issue at hand - Generally I'd advise against trying to use this sort of layout, it's less flexible than having label on the right)

**Comment by pdoane** [comment]
Have you tried updating to latest code? I was having similar issues based on a snapshot from master that went away after getting latest.

**Comment by edin-p** [comment]
I'm not at home so have no access to source, will try updateing imgui and if the problem persists will put a more complete repro later today or tomorrow..

**Comment by edin-p** [comment]
Forgot about this.. Problem fixed by updating ImGui, thanks!
