### ISSUE TITLE
Hide from Screenshot

### ISSUE THREAD

**Issue by EatingPeopleIsFun** [ocornut/imgui#932]
Hi, I have a question, I develop ImGui overlay with some cheats for game, and think about the way to hide overlay from ScreenShot (which can be made by user or protection software) do u have any ideas how it can be implemented? Is it possible?

**Comment by ocornut** [comment]
Just don't create any window or don't render imgui.

**Comment by EatingPeopleIsFun** [comment]
Good idea, but I need to show GUI xD I want to hide it for few millisecs during screenshot process, automatically, do u know api functions which are used for making screenshots? I think the better way is to hook that methods and stop render gui on each call.

**Comment by ocornut** [comment]
Screenshots are your responsability. Just don't render imgui for the frame you are making the screenshot.

**Comment by EatingPeopleIsFun** [comment]
I'm mostly care about screenshots created by game-protection-software. Well, thanks for you answers, I'll try to find an API

**Comment by ratchetfreak** [comment]
@EatingPeopleIsFun it's most likely as simple as putting something like the following at the top of the io.RenderDrawListsFn.

```C++
if(TakingScreenShot){
    return;
}
```
