### ISSUE TITLE
make ImGui window dynamically fit glfw window

### ISSUE THREAD

**Issue by badeip** [ocornut/imgui#933]
Hi,

Is it possible to make ImGui windows fit e.g the "glfwCreateWindow", and adjust accordingly when the latter window is resized?

Regards,

p.

**Comment by ocornut** [comment]
Call SetNextWindowPos() and SetNextWindowSize() every frame before creating your imgui window.

**Comment by badeip** [comment]
Wow, quick response!

Very impressive, thank you!

**Comment by badeip** [comment]
I am still unsure what values to put in SetNextWindowSize(), as GetWindowWidth et al. does not seem to   reflect the GL window width (and does not change when I resize this window).

**Comment by ocornut** [comment]
`ImGui::GetWindowWidth()` retrieve the width of the current ImGui window that was Begin-ed into.

Retrieving your GL window size is out of the scope of ImGui. See your glfw documentation.

**Comment by badeip** [comment]
For future reference, here is how I was able to get the c-style glfw callback to trigger my member function

    gui::init() {
        ....
        glfwSetWindowUserPointer(window_, this);
        glfwSetWindowSizeCallback(window_, resize_callback);
        ....
    }

    void resize_callback(GLFWwindow * window, int width, int height)
    {
        auto g = static_cast<gui *>(glfwGetWindowUserPointer(window));
        g->window_resize(width, height);
    }

**Comment by matthijsvk** [comment]
If anyone else needs this; I used this simple solution in my main loop:

use glfwGetWindowSize and ImGui::setNextWindowSize to match imGui to glfw,
and use Implot::BeginPlot with size (-1,-1) to make the imPlot fit imGui.
```
while (!glfwWindowShouldClose(window)) {
  glfwPollEvents();
  // Start the Dear ImGui frame for the iteration
  ImGui_ImplOpenGL3_NewFrame();
  ImGui_ImplGlfw_NewFrame();
  ImGui::NewFrame();
  
  // here's the ImGui window resizing code
  int width, height;
  glfwGetWindowSize(window, &width, &height);
  ImGui::SetNextWindowSize(ImVec2(width, height)); // ensures ImGui fits the GLFW window
  
  ImGui::Begin(...);
  ...
  ImPlot::BeginPlot("My Plot", ImVec2(-1, -1)); //  ensures ImPlot plot fits the ImGUI window.
  ... 
}

**Comment by aquila-const** [comment]
I found out that for me it worked to add a low res height and width then scale. Works for fixing video flash too:
```cpp
int width_mm, height_mm = 0;
int low_res_width = 700;
int low_res_height = 400;
int count = 0;
acquire_screen_resolution(width_mm, height_mm);
GLFWmonitor *primary_monitor = glfwGetPrimaryMonitor();
auto *window = glfwCreateWindow(low_res_width,
                                low_res_height,
                                "Window title",
                                primary_monitor,
                                nullptr);
```
get_resolution:
```cpp
void acquire_screen_resolution(int window_width, int window_height) {
    const GLFWvidmode * video_mode = glfwGetVideoMode(glfwGetPrimaryMonitor());

    window_width = video_mode->width;
    window_height = video_mode->height;
}
```

**Comment by ocornut** [comment]
The proper portable solution is simply:

```cpp
ImGuiViewport* viewport = ImGui::GetMainViewport();
ImGui::SetNextWindowPos(viewport->Pos);
ImGui::SetNextWindowSize(viewport->Size);
ImGui::Begin("fullscreen video", NULL, ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize);
```

**Comment by aquila-const** [comment]
> The proper portable solution is simply:
> 
> ```cpp
> ImGuiViewport* viewport = ImGui::GetMainViewport();
> ImGui::SetNextWindowPos(viewport->Pos);
> ImGui::SetNextWindowSize(viewport->Size);
> ImGui::Begin("fullscreen video", NULL, ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize);
> ```

Does that prevent screen flashing in glfw video mode?
