### ISSUE TITLE
FileBrowser

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#936]
Is there any filebrowser widget?
Is there any plan to add it?

Thanks

**Comment by ocornut** [comment]
There's no default's one and file systems aren't standardized.
@flix01 made one here https://github.com/Flix01/imgui/tree/2015-10-Addons/addons/imguifilesystem

In my own app usually I use simple popups with sorted MenuItem for each folder/file, no persistent storage, and recursing into child popups. It's simple to make but not really a full featured file browser, merely a file selector.

**Comment by sonoro1234** [comment]
Thaks alot!!

**Comment by FOLOME** [comment]
link not work?

**Comment by kudaba** [comment]
https://github.com/Flix01/imgui/tree/imgui_with_addons/addons/imguifilesystem

**Comment by FOLOME** [comment]
thnks
