### ISSUE TITLE
question: setting window at bottom of display

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#941]
Hi,

For setting a window to the bottom fo display I use
````
SetNextWindowPos(ImVec2(0, GetIO().DisplaySize.y - height), 0);
SetNextWindowSize(ImVec2(GetIO().DisplaySize.x, 0), 0);
````
But I dont know how to calculate height (for SetNextWindowSize is enough setting 0)

**Comment by sonoro1234** [comment]
using
````
GetItemsLineHeightWithSpacing()
````
as height value leaves some part of window out of display

**Comment by ocornut** [comment]
You may use GetWindowHeight(). As ImGui doesn't do full proper layout you may need to either render the window once to get its height (if it is fixed), or reapply it every frame, or use a fixed height there. There's no ideal solution right now.

**Comment by sonoro1234** [comment]
WindowPadding was left over
````
height = imgui.igGetItemsLineHeightWithSpacing() + imgui.igGetStyle().WindowPadding.y*2
imgui.igSetNextWindowPos(ig.ImVec2(0, imgui.igGetIO().DisplaySize.y - height),0);
imgui.igSetNextWindowSize(ig.ImVec2(imgui.igGetIO().DisplaySize.x, height),0);
````
(sorry about cimgui style)
seems to work but I am not sure if SetNextWindowSize(ImVec2(xsize, height)); adds more padding to the requested height

**Comment by ocornut** [comment]
SetNextWindowSize() doesn't add any extra padding.
In fact we are lacking a helper function to derive "client size" from "window size" and vice-versa. It is useful it you want to force an exact size for your content without having to do those awkward calculations yourself.

**Comment by redora0212** [comment]
Is this possible to do with a MainMenuBar? Like, how would I exactly place this bar at the bottom of the window?

An example would be appreciated.

**Comment by Milerius** [comment]
@ocornut any idea about the question of @redora0212 (Writting a software, i want to have both bar one in bottom one in top, is it possible to duplicate MainMenuBar to have BotttomBar ?

**Comment by ocornut** [comment]
@Milerius You can use the pivot parameter of `SetNextWindowPos`:

`ImGui::SetNextWindowPos(ImVec2(0.0f, io.DisplaySize.y), 0, ImVec2(0.0f, 1.0f));`

Then see what `BeginMainMenuBar()` is doing and do something similar in your code.
