### ISSUE TITLE
View log

### ISSUE THREAD

**Issue by zer0sec** [ocornut/imgui#943]
hi, i'm new to all of this i was wondering if it's possible to make a window for a log viewer? that pretty much just views game logs while playing!! or previous logged files.

**Comment by ocornut** [comment]
Have you look at the examples/demo code that exactly has this as a demo?

**Comment by zer0sec** [comment]
Yes i'm looking at it but how would i make it display the contents of a directory such as 
Documents\ETS2MP\logs
this is what i have so far
```
if (ImGui::Button("Logs"))
		{
			UI::Text("MP Player Logs");
			ImGui::MenuItem("fish_hat.c");
			ImGui::MenuItem("fish_hat.inl");
			ImGui::MenuItem("fish_hat.h");
		}
```

**Comment by ocornut** [comment]
Load the file contents (fopen, fread) and display them (ImGui::TextUnformatted). There's dozens of subtle different ways to do it but a single TextUnformatted call, if not the most efficient, would work.

**Comment by zer0sec** [comment]
thanks pal

**Comment by zer0sec** [comment]
i have another question how would i be able to display the current value of an int address? this is what im using to edit the value but not quiet sure how i would display it
```
                static int f = 0.0f;
		*(int*)(0x096C0A0) = f;
		ImGui::SliderInt("XP", &f, 0.0f, 5000.0f);
```

i know i'd have to some how make it display via UI::Text
