### ISSUE TITLE
Progress Bar linked to function on button click

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#944]
I have a function that is called on a button click i.e., Process( .... ) that return a value. How can I start an animated ProgressBar that will run until the function has completed i.e. return value calculated? Sometimes the function only takes 10 secs to complete but other times, maybe 1 min+?

**Comment by ratchetfreak** [comment]
refactor the function so it will do a little bit of work and then return.

then when called again it will do the next bit of work. 

each bit of work should be small (take less than a millisecond).

Then have that function also calculate how far it is percentage wise to display:

```C++
if(!processState.isProcessing){
  if(ImGui::Button(...)){
      //init processState
      processState.isProcessing = true;
  }
}
if(processState.isProcessing){
   Process(&processState);
   ImGui::ProgressBar(processState.progress,...);
}
```

**Comment by ocornut** [comment]
ImGui renders as you request it to do so. It's up to you to reorganize your code if you have large block tasks. Either split the work in chunks or if the work can be done in a thread it may be able to communicate its % of completion to another thread in case of drawing the tools/ui.
