### ISSUE TITLE
Collapsing header isn't resized properly when in a group.

### ISSUE THREAD

**Issue by ongamex** [ocornut/imgui#945]
Collapsing header isn't resized properly when in a group.

```
ImGui::PushItemWidth(300);
ImGui::BeginGroup();
if(ImGui::CollapsingHeader("Parameters")) { 
 // ... just a few drag values here, nothing fancy
}
ImGuiEndGroup()

ImGui::SameLine():
ImGui::InvisibleButton("placeholder_name", ImVec2(500, 500)); // or an image button.
```

The problem is that the the CollapsingHeader is always as long as the current window, bypassing the size of the current Group.

This is what I'm trying to achieve:
https://s28.postimg.org/mf1fma1bx/imguibug.png

Sorry for not posting a complete example.

**Comment by ocornut** [comment]
Groups are merely capturing a bounding box; at the time you are within the group it is just being extended and has no size. We could potentially make groups takes an explicit width and/or height, if explicit width is good enough for you. You can use BeginChild() right now with similar results.

**Comment by ongamex** [comment]
Begin/EndChild could really do the trick. I'm currently using ImGui::Columns as a some sort of workaround, it works for me, so I'm good for now.

Thanks for the quick reply!

**Comment by ocornut** [comment]
BeginChild() may be more appropriate here. I have a few notes already about improving and clarifying the behavior of groups. As for columns, well, there's a lots to do :) 2017 onward!
