### ISSUE TITLE
#define  IMGUI_API extern "C" __declspec( dllexport )

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#948]
Hi,

I am preparing a luajit binding for imgui with glfw3.
I am using cimgui for that and also imgui_impl_glfw_gl3.cpp and header.
I need access to ImGui_ImplGlfwGL3_Init and similar functions for this I should:
````
#define  IMGUI_API extern "C" __declspec( dllexport )
````
but then all imgui functions are exported (which is not neccesary as they are C++ functions)

Would be possible to have another definition here as for example IMGUI_API_IMPL?
Is there a better solution?

Thanks

**Comment by ocornut** [comment]
Hello Victor,

I found out it was the better default since some people are bundling both pieces of code into a DLL for usage in their engine. 

It is actually a problem to have those few extra functions exported?
I mean, I could add an extra define I need to avoid extra addition of complexity in the code/headers whenever possible.

-Omar

**Comment by sonoro1234** [comment]
As I need other changes: 

1-Calling gl3wInit(); from ImGui_ImplGlfwGL3_Init (In order to not do it from the luajit side) 
2-Perhaps diverging from the original cimgui...

May be the best solution would be to copy and modify imgui_impl_glfw_gl3.cpp and header in my fork (As they are small files)

**Comment by ocornut** [comment]
Yes, it is sort of expected/intended that some users will end up copying those files, there are so many subtleties and variations of uses that can't be right for everyone.

(but -1- doesn't sound like a great reason, you could add another function that calls `gl3winit` or whatever you code needs and not have to touch the imgui_impl_xxx files for that)

**Comment by sonoro1234** [comment]
I will take the route of copying files. It is easier for every one.
Thaks alot Omar
