### ISSUE TITLE
Question regarding custom UnformatedText-like widget implementation

### ISSUE THREAD

**Issue by hb3p8** [ocornut/imgui#949]
Hello! I am finally moved my question from twitter here, hopefully Omar or someone else will find time to help me :)

I want to make a custom widget: like simple **ImGui::UnformatedText** but on double click it should be replaced by read-only **ImGui::InputText** for partial selection with mouse.

I remember that **ImGui::FloatSlider** have similar behavior and firstly I looked at its code. So I found this part in **InputScalarAsWidgetReplacement**:

```
    bool text_value_changed = InputTextEx(label, buf, IM_ARRAYSIZE(buf), aabb.GetSize(), ImGuiInputTextFlags_CharsDecimal | ImGuiInputTextFlags_AutoSelectAll);
    if (g.ScalarAsInputTextId == 0)
    {
        // First frame
        IM_ASSERT(g.ActiveId == id);    // InputText ID expected to match the Slider ID (else we'd need to store them both, which is also possible)
        g.ScalarAsInputTextId = g.ActiveId;
        SetHoveredID(id);
    }
    else if (g.ActiveId != g.ScalarAsInputTextId)
    {
        // Release
        g.ScalarAsInputTextId = 0;
    }
```

I have reused the same logic for my custom widget and it worked but I have got a side effect: replacement widget has label which duplicates all the text.

I can think of a few possible workarounds:

1) Sprintf a new label into temporary buffer so it will look like "###old_text" and InputText will still have the same id (for some reason that did not worked)

2) Write custom **InputText** without a label (too much to copy paste)

3) Make it work with **InputText** with another id e.g. "##SomeID"

In particular:

> InputText ID expected to match the Slider ID (else we'd need to store them both, which is also possible)

This comment implies that it should be possible but not out of the box.

And the question in general is how to make this custom widget with minimum pain =)

**Comment by ocornut** [comment]
Please post your code as reference too :)

**Comment by megaton** [comment]
Sure!

https://gist.github.com/megaton/d97b7afe9e037339027121ff6c0eb6d9

**Comment by ocornut** [comment]
Moving to #950
