### ISSUE TITLE
Multi window one thread...

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#954]
Hello Omar,

I am trying to get a dialog with this function
````
function Dialog(parent)
	local dialog = lj_glfw.Window(300, 300, "Dialog")
	imgui.ImGui_ImplGlfwGL3_Init(dialog, false);
	dialog:makeContextCurrent()
		
	while not dialog:shouldClose() do
		lj_glfw.pollEvents()
		
		gl.glClearColor(1,0,0,1)
		ut.Clear()

	        imgui.ImGui_ImplGlfwGL3_NewFrame()	
	        if ig.Begin("drawFB") then
		   ig.Button("test active")
		   if imgui.igIsItemActive() then print"active" end
		   imgui.igSliderFloat("slid", valor, 0, 10, "%.3f", 1.0)
	        end
	        ig.End()	
	        imgui.igRender()
			
		dialog:swapBuffers()
	end

	dialog:destroy()
	--imgui.ImGui_ImplGlfwGL3_InvalidateDeviceObjects()
	imgui.ImGui_ImplGlfwGL3_Init(parent, false);
	parent:makeContextCurrent()
end

````

If I dont use ImGui_ImplGlfwGL3_InvalidateDeviceObjects when dialog closes there is an invalid gl operation. It seems strange because this device objects are not bound to the window (at least explicitly). As my knowledge is limited my speculation is that the window context is binded to these objects.
If this is true I have two options:
1- call ImGui_ImplGlfwGL3_InvalidateDeviceObjects() and ImGui_ImplGlfwGL3_Init(parent, false);
each time I must switch window. (which seem expensive)
2- rewrite ImGui_ImplGlfwGL3_Init so that It calls CreateDeviceObjects and returns an struct for this window with all global gl values and rewrite NewFrame for receiving this struct and copy this gl values to globals.

I would be so gratefull receiving your guidance.

victor

**Comment by sonoro1234** [comment]
Things get worse when I open this dialog from inside main window because invalidating objects is done before the main window's Render is finished (crash)

**Comment by sonoro1234** [comment]
I arrived to this
````
function Dialog(parent)

	imgui.ImGui_ImplGlfwGL3_InvalidateDeviceObjects()
	
	local ctxparent = imgui.igGetCurrentContext()
	local ctx = imgui.igCreateContext(nil,nil)
	imgui.igSetCurrentContext(ctx)
	
	local dialog = lj_glfw.Window(300, 300, "Dialog")
	dialog:makeContextCurrent()
	imgui.ImGui_ImplGlfwGL3_Init(dialog, false);
	imgui.ImGui_ImplGlfwGL3_CreateDeviceObjects()
	
	while not dialog:shouldClose() do

		lj_glfw.pollEvents()
		
		gl.glClearColor(1,0,0,1)
		ut.Clear()
	
		imgui.ImGui_ImplGlfwGL3_NewFrame()	
		if ig.Begin("drawFB") then
			ig.Button("test active")
			if imgui.igIsItemActive() then print"active" end
			imgui.igSliderFloat("slid", valor, 0, 10, "%.3f", 1.0)
		end
		ig.End()	
		imgui.igRender()
	
			
		dialog:swapBuffers()
	end

	dialog:destroy()
	imgui.ImGui_ImplGlfwGL3_InvalidateDeviceObjects()
	
	imgui.igSetCurrentContext(ctxparent)
	imgui.igDestroyContext(ctx)
	parent:makeContextCurrent()

	imgui.ImGui_ImplGlfwGL3_Init(parent, false);
	imgui.ImGui_ImplGlfwGL3_CreateDeviceObjects()
end
````
which works if I call Dialog from main window.
Now my worries are which of the two options of my first message would be better

**Comment by sonoro1234** [comment]
modified glfw3 impl:
https://github.com/sonoro1234/cimgui/tree/lua_build/extras/impl_glfw3

for Impl class intantiation and some automatic ImGuiContext and glcontext handling

allows:
````
function Dialog(parent)
	
	local ctxparent = imgui.igGetCurrentContext()

	local dialog = lj_glfw.Window(300, 300, "Dialog")

	local Impl = imgui.Impl_new()
	imgui.ImGui_ImplGlfwGL3_InitC(Impl,dialog, true);
	
	while not dialog:shouldClose() do

		lj_glfw.pollEvents()
		
		dialog:makeContextCurrent()
		
		gl.glClearColor(1,0,0,1)
		ut.Clear()
	
		imgui.ImGui_ImplGlfwGL3_NewFrameC(Impl)	
		if ig.Begin("drawFB") then
			ig.Button("test active")
			if imgui.igIsItemActive() then print"active" end
			imgui.igSliderFloat("slid", valor, 0, 10, "%.3f", 1.0)
		end
		ig.End()

		imgui.ImGui_ImplGlfwGL3_RenderC(Impl)
		dialog:swapBuffers()
		
		-----
		parent:makeContextCurrent()
		ut.Clear()
                --cant use parent imgui if we are in the middle of a frame but can use gl on it
		--GL:postdraw()
		parent:swapBuffers()
		---

	end

	imgui.Impl_delete(Impl)
	dialog:destroy()
	
        --must set this because may be we are in the middle of parent NewFrame
	imgui.igSetCurrentContext(ctxparent)
	parent:makeContextCurrent()

end
````

**Comment by sonoro1234** [comment]
So option 2 was not so difficult. Only left to wait for ImGui as a class for multithreading.

**Comment by ocornut** [comment]
I don't understand this thread, what you are trying to achieve and why multiple contexts are needed here.

**Comment by sonoro1234** [comment]
Trying to achieve using an imgui module in two different windows. Several glfw windows need several gl context (diffferent for each window) so I need a different ImGuiContext asociated, for doing gl objects allocation, using and deallocation.

**Comment by ocornut** [comment]
But if the final intent (as implied by the look of your code) is to use the second window for a temporary dialog and block interaction of the other stuff, why not just using imgui's modal dialog system?

**Comment by pdoane** [comment]
> But if the final intent (as implied by the look of your code) is to use the second window for a temporary dialog and block interaction of the other stuff, why not just using imgui's modal dialog system?

In most situations I would like use the OS/Desktop windows system. The primary issue for me is the clipping of ImGui windows to the host window rather than look&feel.

**Comment by sonoro1234** [comment]
Yes, imgui's modal dialog is better for this use case, but I want to be able to have several OS windows for other cases.

**Comment by nico-abram** [comment]
Is there a way to do this now?
