### ISSUE TITLE
Column autowidth 

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#955]
I have a window with the following flag set: 

ImGui::Begin("Name", &e, ImGuiWindowFlags_AlwaysAutoResize);
....
ImGui::End();

The window contains an 8 column table of text. Is it possible to set column width individually or set them to the largest text so all text is visible i.e., autowidth?

**Comment by ocornut** [comment]
You can set columns offset individually with SetColumnOffset() but there's no mechanism to only do it once so you need to track it with a boolean, and there's no auto-width at the moment. Columns are pretty lackluster.

**Comment by djones4487169** [comment]
Sorry Omar - what do you mean track it with a boolean?

**Comment by ocornut** [comment]
You only want to call SetColumnOffset() once per column, else if you call it every frame user won't be able to resize the columns. There's no mechanism to handle this pattern automatically yet.

**Comment by djones4487169** [comment]
Omar - can you give me a simple example code snippet I'm trying it and it
is messing everything up?
