### ISSUE TITLE
TLS #define

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#957]
Hello Omar,

I think it should be very usefull having an #ifdef for compile GImGui as thead_local or not depending on a definition passed at compilation time. Very easy to do for anyone but if it is in github master we will not have to change it every time after a pull

victor

**Comment by ocornut** [comment]
There's already a define system to allow this and other flexible hackery, check the code.

**Comment by sonoro1234** [comment]
I mean without changing imconfig.h
````
ImGuiContext*         TLSDEF  GImGui = &GImDefaultContext;
and
extern IMGUI_API ImGuiContext* TLSDEF GImGui;  // Current implicit ImGui context pointer
````
so that just doing -DTLSDEF=thread_local in compiler makes the dll TSL

**Comment by ocornut** [comment]
It is preferable to just change imconfig.h, what is the problem with that?
There are different ways people may want to implement this and I don't know if a TLSDEF define at this position is adequate for all.

**Comment by sonoro1234** [comment]
It is just that I am not able to do it. I dont know how to change the two definitions in imgui.cpp and imgui_internal.h
````
ImGuiContext*   GImGui = &GImDefaultContext;
and
extern IMGUI_API ImGuiContext* GImGui;  // Current implicit ImGui context pointer
````
with one define GImGui in imconfig.h to be both thread_local.

**Comment by ocornut** [comment]
Defiine GImGui to be the name of the variable (or even function call) you want, and you can declare the variable/function wheve you like.

```
ImGuiContext* TLS mythingwhereverilike;
#define GImGui mythingwhereverilike
```
