### ISSUE TITLE
Properly determing if a child is clicked.

### ISSUE THREAD

**Issue by vivienneanthony** [ocornut/imgui#958]
Hello

Super quick question. Is this the right way to see if a child window/frame was pressed?

```
 // Create a child career for the window
if(ImGui::BeginChild(buf,ImVec2(0,100),true))
{
	// Show Career information
	ImGui::Text(ShowCareerName.CString());
	ImGui::Text(ShowCareerDescription.CString());

	ImGui::Spacing();

	ImGui::Text(CurrentTier.CString());

	ImGui::EndChild();
}

// determin is item hovered and mouse double clicked
if(ImGui::IsItemHovered()&&ImGui::IsMouseDoubleClicked(0))
{
	m_SelectedTab==ShowTabSkills;
	m_DefaultSelectedCareer=idx;
}
```
This is something super minor. Just wondering.

Vivienne

**Comment by ocornut** [comment]
Childs are windows. Use functions with the word 'Window' within the beginchild/endchild block to test for that sort of things.

**Comment by ocornut** [comment]
Adding some details in (previous answer made from mobile while travelling so partly misleading).

What you posted should also work as well, at least IsItemHovered() will. Maybe some other XXXItemXXX functions will react inconsistently after EndChild() in which case feel free to report it here. 

```
ImGui::Begin("Issue #958");
if (ImGui::BeginChild("test", ImVec2(0,100), true))
{
    ImGui::Text("Hello");
}
ImGui::EndChild();
ImGui::Text("ChildHovered %d", ImGui::IsItemHovered());
ImGui::End();
```

PS: As a minor thing, note that ImGui::Text() take a format string, so if any of your string contains a `%` character for formatting you can expect incorrect output or a crash. You may use ImGui::Text("%s", mystring) or ImGui::TextUnformatted(). You may also add your own helper ImGui::Text(MyStringType* s) function that does exactly that as a helper to avoid calling .CString() if you feel like it).
