### ISSUE TITLE
Direct X examples

### ISSUE THREAD

**Issue by NetaSploit** [ocornut/imgui#959]
Hello, I was wondering if you can help me load 2 fonts on the direct X example, I have loaded my first font, but I do not know how to switch between them. 

I am currently doing:
`io.Fonts->AddFontFromFileTTF("c:/windows/fonts/SegoeUI.ttf", 14.0f, NULL, io.Fonts->GetGlyphRangesJapanese());`

Thanks for your time, I am using the Direct X example (DX9)

**Comment by kateon11** [comment]
Q: How can I load multiple fonts?
 A: Use the font atlas to pack them into a single texture:
[...]
// the first loaded font gets used by default
// use ImGui::PushFont()/ImGui::PopFont() to change the font at runtime

**Comment by ocornut** [comment]
Thanks @kateon11 for answering. Oddly enough @NetaSploit initial message was different (talking about spacing and edited).

**Comment by NetaSploit** [comment]
Yeah, originally I wanted to ask about that, however I fixed it and then wanted to ask another question, thank you @kateon11 for your reply.
