### ISSUE TITLE
Fixed width popup and proper text wrapping

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#960]
I'm trying to get the tooltip popup to be a certain width for all usage and text wrap properly around that width e.g., 100.

void GUI::ShowHelpMarker(const std::string& s)
{
	ImGui::TextDisabled("(?)");
	if (ImGui::IsItemHovered())
	{
		ImVec2 sp = ImGui::GetCursorScreenPos();
		ImGui::PushTextWrapPos(ImGui::GetCursorPos().x + 100);
		ImGui::SetTooltip(s.c_str());
		ImGui::PopTextWrapPos();
	}
}

Can you help me out setting the fixed width of popup?

**Comment by ocornut** [comment]
Use SetNextWindowSize(), BeginTooltip(), Text(), EndTooltip();
