### ISSUE TITLE
Centre text inside AddRect()?

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#961]
How can I centre "11.45" inside the rectangle when using AddRect(). I'm trying code snippet below but get top-left alignment of text?

ImVec2 p = ImGui::GetCursorScreenPos();
ImGui::PushTextWrapPos(ImGui::GetCursorPos().x + 100);
ImGui::Text("%s", "11.45");
ImGui::GetWindowDrawList()->AddRect(ImVec2(p.x, p.y), ImVec2(p.x + 100, p.y + 40), 0xFFFFFFFF);
ImGui::PopTextWrapPos();

**Comment by ocornut** [comment]
Calculate the size of text yourself and position it (or draw the text with the right position using the ImDrawList api). The text alignment helpers aren't exposed publicly yet (api is unsatisfactory for now).
