### ISSUE TITLE
In the GLFW3 version, entering text using an IME sends the "enter pressed" event prematurely

### ISSUE THREAD

**Issue by bluebear94** [ocornut/imgui#962]
Most IMEs recognise pressing the Enter key as an instruction to finalise the input, but the GLFW3 backend sends the "enter pressed" event after any text input event. If the focus was previously on a textbox, the focus will be lost before any characters are entered.

In addition, it might be useful to ignore any Enter key presses that are used to confirm IME inputs, though I'm unsure how that would be done.

**Comment by ocornut** [comment]
I think this is a bug in GLFW3 which as far as I know was patched in 3.2 (I submitted the fix).
Which version of GLFW3 are you using? 
https://github.com/glfw/glfw/pull/651#event-655579045
https://github.com/glfw/glfw/issues/41#issuecomment-160421273

**Comment by bluebear94** [comment]
Upgraded from 3.1.2 to 3.3 and I still seem to get the bug.

**Comment by bluebear94** [comment]
Maybe [this PR](https://github.com/glfw/glfw/pull/658/files) is relevant?

**Comment by ocornut** [comment]
I have confirmed that recent version of GLFW have this fixed (not sure exactly when it was fixed).

(We have still bundling in old windows binaries in `examples/` because I have no idea of pushing more binaries to the repo)
