### ISSUE TITLE
Cannot load glyphs

### ISSUE THREAD

**Issue by Chekr** [ocornut/imgui#963]
My window is showing up like this:
![image](https://cloud.githubusercontent.com/assets/695293/21600010/76a73f44-d13b-11e6-8073-3da1ac0c16a2.png)

When I debug against AddFontDefault(), the ImFont* font object ends up with zero glyphs. 

The background and imgui frame rendering seem to be working correctly, just not the text rendering. 

I have no idea why this is happening. Does anyone have any insight?

**Comment by edin-p** [comment]
Same thing happened to me when implementing in Vulkan, check your OpenGL/DirectX blendfactor..

**Comment by ocornut** [comment]
Either your blending is incorrect, either your texture was incorrectly uploaded or incorrectly bound.

Check if you can with a graphic debugger to see if the texture is correctly uploaded or what are your render state.

**Comment by Chekr** [comment]
I was doing texture binding with GL_TEXTURE_RECTANGLE_ARB, and something about that broke it. I changed it to GL_TEXTURE_2D and everything works. I'll look into it more later, but for now that solved the problem. Thank you.
