### ISSUE TITLE
ImGuiTreeNodeFlags_SpanAllAvailWidth?

### ISSUE THREAD

**Issue by edin-p** [ocornut/imgui#964]
Hi @ocornut , any progress on this?

**Comment by ocornut** [comment]
No update means no progress, :/ Should be fairly easy to add locally if you need it!

**Comment by edin-p** [comment]
Done! I guess I should close this..  Thanks!

**Comment by ocornut** [comment]
Btw 1.73 added `ImGuiTreeNodeFlags_SpanAvailWidth` and `ImGuiTreeNodeFlags_SpanFullWidth` flags.
