### ISSUE TITLE
Add ability to provide global callbacks for interacting with a certain type of element

### ISSUE THREAD

**Issue by bluebear94** [ocornut/imgui#965]
e. g. having a sound play every time you press a button.

Probably a low-priority issue since the only purpose I can conceive for this functionality is production stuff, which imgui isn't meant for.

**Comment by ratchetfreak** [comment]
```C++
if(ImGui::Button(...)){
    queueClickSound();
}
```

or just wrap the functions you need and add the functionality that way:

```C++
bool SoundPlayingButton(const char* label, const ImVec2& size = ImVec2(0,0)){
     bool result = ImGui::Button(label, size);
     if(result) queueClickSound();
     return result;
}
```

**Comment by bluebear94** [comment]
Yeah, I was thinking of that, but if you already have code that uses ImGui::Button a lot, you'd have to change lots of code (of course, you could automate this).

**Comment by ocornut** [comment]
Sorry this is not planned not desirable for the scope and purpose of imgui, as you pointed out. Encouraging this sort of thing would attract more users with different expectations than what imgui is meant for.
