### ISSUE TITLE
invoke button click through code?

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#966]
Is it possible to invoke a button click (or other widget) with code i.e., the same as if the user clicked the mouse on the button?

**Comment by ocornut** [comment]
No, if you mean that you want the button to look pressed it isn't possible.

**Comment by djones4487169** [comment]
Not look pressed but act as though it has been clicked using code?

**Comment by ocornut** [comment]
Just call the code that you would call on your if() statement.

**Comment by ratchetfreak** [comment]
You can adjust where the keyboard focus is with `SetKeyboardFocusHere`

**Comment by ocornut** [comment]
Closing this for now, it looks like there's no clear issue between discussed in the first place.

**Comment by sailfish009** [comment]
To OP, just some hint:

```
std::atomic<bool> b_want_some_toggle = false;

// if (ImGui::Button(label.c_str(), { 30,30 })) // previous code
if ((b_want_some_toggle == false) || ImGui::Button(label.c_str(), { 30,30 }))
{
    // ...
}

if ((b_want_some_toggle == true)  ||  ImGui::Button(label.c_str(), { 30,30 }))
{
    // ...
}

void class_somewhere::control_function()
{
    if (b_want_some_toggle)
    {
        b_want_some_toggle = false;
    }
    else
    {
        b_want_some_toggle = true;
    }
    // ...
}
```

**Comment by ocornut** [comment]
Note that there are plan for a new API to programmatically activate widgets based on their ID, but that won't be ready short-term.
