### ISSUE TITLE
Add a circle at a specific (x,y) on the main screen from a popup table choice.

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#967]
I have the following code that creates a popup and display in a table of columns the relevant information. What I want to do is click on a row and draw a circle at a specific coordinate on the main screen. Is this possible? Here is what I have but doesn't work:

	ImGui::Columns(IM_ARRAYSIZE(headers), "Columns", true);
	ImGui::Separator();
	float offset = 0.0f;
	for (ColumnHeader & header : headers)
	{
		ImGui::Text(header.label);
		ImGui::SetColumnOffset(-1, offset);
		offset += header.size;
		ImGui::NextColumn();
	}
	ImGui::Separator();

	ImDrawList* draw_list = ImGui::GetWindowDrawList();
	static ImVec4 col = ImVec4(1.0f, 1.0f, 0.4f, 1.0f);

	static int selected = -1;
	for (int i = 0; i < roi_perimeter.size(); i++)
	{
		char label[32];
		sprintf(label, "%03d", i + 1);
		if (ImGui::Selectable(label, selected == i, ImGuiSelectableFlags_SpanAllColumns))
		{
			selected = i;
			LOG(INFO) << "ROI Selected: " << i + 1;
			const ImU32 col32 = ImColor(col);
			draw_list->AddCircle(ImVec2(roi_com[i].x, roi_com[i].y), 5, col32, 20, 1);
		}
		ImGui::NextColumn();
		ImGui::Text("%.0f", roi_perimeter[i]); ImGui::NextColumn();
		ImGui::Text("%.0f", roi_area[i]); ImGui::NextColumn();
	        ImGui::Text("(%u, %u)", roi_com[i].x, roi_com[i].y); ImGui::NextColumn();
		ImGui::Text("%.2f", roi_roundness[i]); ImGui::NextColumn();
		ImGui::Text("%.2f", roi_eccentricity[i]); ImGui::NextColumn();
		ImGui::Text("%.2f", roi_orientation[i]); ImGui::NextColumn();
		ImGui::Text("%.2f", roi_moi[i]); ImGui::NextColumn();
	}
	ImGui::Columns(1);

**Comment by ocornut** [comment]
You can use GetCursorScreenPos() to query the current imgui cursor pos.
Your request is vague and your code incomplete. This possibly isn't much related to imgui at all.
Please take more time in the future to provide clear and self-sufficient repro code, if only to force you to do your research beforehand.

**Comment by djones4487169** [comment]
Basically, if I choose a particular row in a table in a popup which gives the required (x,y) coordinates relating to the main screen (i.e., underneath/behind the popup window) how can I draw a circle at that (x,y) position on the main screen whilst the popup is still active? 

If I use GetCursorScreenPos() how can I relate that to the main screen so the circle does not draw in the popup but on the main screen only?

**Comment by ocornut** [comment]
> Basically, if I choose a particular row in a table in a popup which gives the required (x,y) coordinates relating to the main screen (i.e., underneath/behind the popup window) how can I draw a circle at that (x,y) position on the main screen whilst the popup is still active?

Exactly what you are doing, use the draw list and draw wherever you want. You may need to push a fullscreen cliprectangle to avoid the drawing being clipped by window edge.

Here the logic you pasted until draws for 1 frame at the time of click, so you want to fix your program logic. There's really nothing about this which is an imgui support question you have all the elements already, it's mostly up to your code to know what it is doing.

GetCursorScreenPos() isn't useful in this case, it gives you the 2d position of the imgui "drawing" cursor, which would be useful if you want to draw stuff over the UI or matching widget positions, etc.
