### ISSUE TITLE
Min height for window??

### ISSUE THREAD

**Issue by colesnicov** [ocornut/imgui#969]
Hi Omar, is there any way to set the window size to be 10 pixels? I tried 
`SetNextWindowSize (...)`
 but also 
`SetNextWindowContentSize (...)`
 but everything is futile meetings, it is at least 32 pixels. Any advice from anyone? Thanks :)

**Comment by ocornut** [comment]
Hello,

See:
```
[...]
ImGuiStyleVar_WindowMinSize,       // ImVec2
[...]
struct ImGuiStyle
{
    [...]
    ImVec2      WindowMinSize;              // Minimum window size
    [...]
}
```

**Comment by colesnicov** [comment]
Thanks. ImGui is incredible!! :+1:
