### ISSUE TITLE
Get id name of menu

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#971]
If I have a menu tree e.g.:

if (ImGui::BeginMenu("Database")) 
{
        if (ImGui::BeginMenu("DDSM"))
	{
             ImGui::MenuItem("1");
	     ImGui::EndMenu();
        }
        if (ImGui::BeginMenu("ABDR"))
	{
        }
ImGui::EndMenu();
}

How do I get the id name e.g. DDSM or ABDR for the active menu item?

**Comment by ocornut** [comment]
I am not sure I understand the question, nor what you are trying to do. Please clarify!
Maybe using `IsWindowHovered()` within the menu would be useful for you.

(Please surround code blocks with triple back quotes)

**Comment by djones4487169** [comment]
When I click on MenuItem("1") which opens up a help popup for example. How can  I get the name of the menu item pressed, in this case "1"? Similarly, say I have a MenuItem("2") - how can I retrieve the name "2" when it is pressed?

**Comment by ocornut** [comment]
You can't retrieve any name from anywhere, names aren't stored. 
If MenuItem() returns true it's been pressed, and you just passed the name therefore you must have it.

**Comment by djones4487169** [comment]
I see what you mean just have a bool flag in the menu {} that can be linked to the name of the menu item kind of thing?

**Comment by ocornut** [comment]
I don't understand what you are saying.
Your code has the name of the menu item as you are passing it to MenuItem(). Therefore when MenuItem() return true you still have that name.

**Comment by djones4487169** [comment]
Yes I understand what you are saying I was confusing g the issue. Sorted out now.
