### ISSUE TITLE
How to make a window preventing other windows from recieving input ?

### ISSUE THREAD

**Issue by dhiahassen** [ocornut/imgui#972]
i want to make a window that when shown it prevents other present windows from getting mouse/keyboard focus , it acts like a message box window , in other words , i want to make it the only window that the user can interact with while it is shown , the popup flag is not helping , i know it is internal , even BeginPopup() is not doing the trick ,it made me have doubt about the meaning of its name or its purpose , thankssss

**Comment by ocornut** [comment]
Have you checked the demo application? Itlists most imgui features in a categorized manner and should be the first thing to look at.

Those windows are called Modal windows.

**Comment by dhiahassen** [comment]
yeah i did , i remember i found it one time , but now when i need it i looked over and over again but still can find it , it would be more helpful if you guide me directly to the issue , and ill be very thankful

**Comment by dhiahassen** [comment]
thanks alot , ur comment didnt appear complete at first , only its first part was there , maybe a bug , very special thanks , u have done greate in this project
