### ISSUE TITLE
How to use ImGui::GetStateStorage()

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#974]
Hi, I don't know if what I want to do can be done with the state storage.

Basically I have same data (currently just a boolean, but in the general case other variables) that I want to be associated to a (custom) widget label.

So basically, if I have a custom widget, I can have its unique ID using:
```c++
const ImGuiID id = window->GetID(label);
```
Now I'm thinking about creating in same way (how?) some kind of sub-id for my stored variables (all must be related to that id in an unique way). Then when  I get a sub-id, I'm thinking about doing something like:
```c++
ImGuiStorage* storage = ImGui::GetStateStorage();
//storage->SetInt(subId, ...);
//storage->GetInt(subId, ...);
```
My questions are:
* Is it possible to do what I'm trying to do this way ?
* How can I calculate an unique sub-id (I think I can fully process the widget (text) label myself and then append some kind of tag, but that doesn't seem to be very easy...) ?

Hope I've been clear enough,... but I'm not sure.

**[Edit:]** For a single variable, is the widget 'main' ID (i.e.  window->GetID(label) ) safe to use ? I ask because in my simple case it seems to work.

**Comment by ocornut** [comment]
use PushId/GetId/PopId to generate sub-id, or you can use GetId() and then use id+0, id+1. Note that CRC32 conflict can in theory happen, in practice probably won't.

The per-window state storage is a generic thing that can be convenient, but it's not really easier or faster to use than your own regular data structure. It may be beneficial to use your own storage/structure for your own widgets. For example InputText() stores only 1 full state in a regular structure and associate it to an id.

**Comment by Flix01** [comment]
> use PushId/GetId/PopId to generate sub-id, or you can use GetId() and then use id+0, id+1. Note that CRC32 conflict can in theory happen, in practice probably won't.

Yes, I was thinking about incrementing the ids... good to know that it's 99% safe.
For now I just need one boolean, so reusing the main id as key seems to work.

> It may be beneficial to use your own storage/structure for your own widgets. For example InputText() stores only 1 full state in a regular structure and associate it to an id.

That seems to be really useful and having an example [InputText()] makes this task easier.

Thanks for your answer!

P.S. For big/complex widgets I prefer using proper classes and instances, so that I can call some methods in any part of my code (like load/save methods an stuff like that). Obviously this breaks the immediate-mode-design-rules, but I don't care much about that...
