### ISSUE TITLE
New version of stb_truetype.h

### ISSUE THREAD

**Issue by Flix01** [ocornut/imgui#976]
@ocornut:
Hi, as far as I can see there's a new version of [stb_truetype.h](https://github.com/nothings/stb/blob/master/stb_truetype.h) with:
_1.13 (2017-01-02) support OpenType fonts, certain Apple fonts, num-fonts-in-TTC function_

Is there some specific reason not to update to the new version (does Dear ImGui use a custom version) ?

**Comment by ocornut** [comment]
It's not custom anymore, it could be updated.

**Comment by Flix01** [comment]
Good to know. 

If I need to use .otf fonts, I'll do it.

**Comment by itamago** [comment]
I tried to load .otf files, using latest ImGui, but it generates huge atlas (1024x32768) which obviously is insane :)
The font I'm using is a small one : http://dl.1001fonts.com/glacial-indifference.zip
Am I missing some specific config for OTF support in ImGui ?

**Comment by ocornut** [comment]
I have just updated stb_truetype but not tried the OTF support. Maybe it has issues or limitations. I would suggest trying different fonts and maybe checking the stb github for issues?

**Comment by itamago** [comment]
You're right, I checked the issues on STB github, and the OTF support is mostly working but not with all fonts. 
I tried with 2 other OTF fonts and they were loaded with decent dimensions.
So, be careful with otf support for the moment, it's not perfect.
