### ISSUE TITLE
OpenGL example: Blinking and distortion on certain systems (Intel HD Graphics 4600?)

### ISSUE THREAD

**Issue by Axelwickm** [ocornut/imgui#977]
Everything works as intended on my GTX 970, but when running the project on an Intel HD Graphics 4600 i get this when i start using the interface:
![ezgif com-87984b5b6e](https://cloud.githubusercontent.com/assets/1360495/21925060/0afafb3e-d97c-11e6-8299-a56d9c08e883.gif)
My own graphics are working consistently on both systems.

I am using OpenGL 3 & GLFW 3.2.1 with the imgui_impl_glfw_gl3 implementation. Graphics drivers have been updated. Source code can be found at: https://github.com/Axelwickm/NeuroCorrelation (mainly renderInterface() in NeuCor_Renderer.cpp).

**Comment by ocornut** [comment]
Does the raw unmodified examples works?

Try to comment out part of your own code until you narrow it down.
It's probably a given render state that breaking the render. In theory the example code tries to set the states it needs, in practice OpenGL has so much implicit stuff that we could be missing something.

**Comment by Axelwickm** [comment]
I have tried isolating the error, but the behavior more or less always remains.
Since I'm using glew (forgot to mention) I have to modify the example files to run them, and the error exists there to. Should I try using gl3w?

**Comment by ocornut** [comment]
I'd imagine they are pretty much the same. Try posting a gif of the example app glitching.

**Comment by Axelwickm** [comment]
![ezgif com-aeebe452e4](https://cloud.githubusercontent.com/assets/1360495/21928092/2658293a-d989-11e6-9822-bc43cca5d861.gif)

**Comment by ocornut** [comment]
Well, hard to guess what's creating that, first time I hear of issues on an Intel card. The OpenGL rendering code is pretty trivial so you can attempt to try to track down the issue on your graphic card maybe?

**Comment by Axelwickm** [comment]
Solving this problem isn't number one priority right now, but I'll write if I find a solution ;)

**Comment by Axelwickm** [comment]
Alright so it turned out that Window's device manager hadn't really updated the drivers at all. Downloading and updating the Intel Graphics driver manually fixed it :smile:

**Comment by ocornut** [comment]
Good to hear!

**Comment by temcgraw** [comment]
I was about to post that I have seen this issue also on Intel HD 4000, but it seems that the issue has been closed. Unfortunately I am seeing this problem on a client's machine that I cannot access regularly and the client does not have admin access to update drivers. One clue is that resizing an imgui window will temporarily stop that window from flickering. I will be able to debug on that system again in a few weeks.

**Comment by snbmm** [comment]
I meet this problem in a non-windows platform, wondering whats the change of the new driver fixed this issue? And do you find another solution temcgraw?

**Comment by ocornut** [comment]
If you have the problem locally, try to experiment with the render loop code in imgui_impl_xxx.cpp to find a workaround.

**Comment by simo-11** [comment]
I had similar issue with Intel HD Graphics 4600 on Lenovo T540p. 
Driver 9.18.10.3272 (checked using GPU-Z)
Double-clicking Window titles changes situation to one of these states
- Works ok
- One window disappears as expected and other one is distorted
- Both windows flicker
I updated driver to version 10.18.14.4414 and issue disappeared
Updated driver is internally referred as 15.36.31.64.4414, current intel version is 15.36.33.4578
Changes mentioned in VERSION INFORMATION section do not point out which change could
have fixed this issue but one garbage generating bug and one vulnerability problem were mentioned
https://download.lenovo.com/ibmdl/pub/pc/pccbbs/mobiles/gid641ww.txt

**Comment by maihd** [comment]
Hi all, sorry about late comment and my bad English. But today, I about to met the same bug discuss above. My OpenGL index buffer use modern glNamedBufferData, then the bug happend in my company pc that only has Intel HD graphics card. Avoid glNamedBufferData in old Intel HD graphics driver that works for me.
P/S: I also test with GTX1050+glNamedBufferData, work fine!
