### ISSUE TITLE
Combo ID question

### ISSUE THREAD

**Issue by sonoro1234** [ocornut/imgui#978]
Hello,

I am adapting some curve widget.
I pushID before combo to be able to have several Curve in a window:

Curve(char * label, ...)
{
   //do somethings
   PushID(label);
  if ( Combo("combo",...
   {
    //do combo things
   }
   PopID();
}

Each combo action is correctly generated for one combo but combo item changes in all the window combos.

What am I missing?
Thanks

victor

**Comment by ocornut** [comment]
Please provide an actual repro in the form of code that can be pasted into an imgui enabled application.

**Comment by sonoro1234** [comment]
Perhaps not necessary. I found what I was missing:
original code had static declaration

Curve(char * label, ...)
{
//do somethings
static int item = 0;
PushID(label);
if ( Combo("combo",&item,..
{
//do combo things
}
PopID();
}

So all ImGui Curve combos would had the same item.
I guess I can make it non static for memoryless item or give item as Curve argument for persistance.

**Comment by ocornut** [comment]
Correct.
Combo are meant to change a selection but I see how it you want to use them only to "select" an option it may be worthy to provide an alternate combo with no user-side state returning selected item.
