### ISSUE TITLE
Is this software using dear imgui ?

### ISSUE THREAD

**Issue by UselesssUser** [ocornut/imgui#979]
Hello Ocornut! No issues, just I need your opinion.
How do you think, the interface of this software is done using IMGUI? If so, why do you you think so? Maybe special things you notice here? I wonder to use IMGUI. Thanks!

**Comment by ocornut** [comment]
Hello,

I guess this software use a custom ui, not dear imgui. You might get similar (but not exact) results with dear imgui if you spent time writing custom widgets etc.

PS: Please fill the subject line properly when asking a question.

**Comment by UselesssUser** [comment]
Thank you! :)
