### ISSUE TITLE
ImGui as a Shared Library

### ISSUE THREAD

**Issue by colesnicov** [ocornut/imgui#980]
In fact this is not issue but the instructions. For modular applications, such as mine, where ImGui also use modules, it is better ImGui implemented as a shared library.

Linking must be both libraries (libImGui.so and libImGui_draw.so - in no particular order).

How to compile (using Linux - Ubuntu):

`$ gcc -c -Wall -Werror -fpic imgui.cpp`
`$ gcc -shared -o libImGui.so imgui.o`
`$ gcc -c -Wall -Werror -fpic imgui_draw.cpp`
`$ gcc -shared -o libImGui_draw.so imgui_draw.o`

**Beware, if you want to use _libImGui\*.so_, do not add to the project files _imgui\*.cpp_! It would not make sense.**

_(Sorry, Google Translate last time spitting nonsense)_

**Comment by ocornut** [comment]
Thanks. Those instructions don't really pertain to imgui as it is a fairly standard procedure for .so file with gcc.

You can combine imgui.o and imgui_draw.o in the same library file. You should also include imgui_demo.o.

( Personally I discourage using imgui as a library, people tend to not edit imconfig.h as much in that situation especially when librairies are handed to them pre-packaged, and people rarely _actually_ need the shared library modularity, 80% of the time it is over engineering :)

**Comment by colesnicov** [comment]
You're right, **you've got to do this configuration before you do compile the library**. **Mathematical functions for ImVec and other things also you have to define a before**. On the other hand, if you are using more of the module and each of them produces a GUI, so the size of the resulting application + library will grow quite a bit.

_But, ImGui as a shared library? Yes, it is possible._

**Comment by ocornut** [comment]
Anything is possible as a shared library! 

Closing this, it'll appear in searches for other people who are interested about this but unfamiliar of how to compile with GCC.

**Comment by jiapei100** [comment]
Please refer to my pull request [https://github.com/ocornut/imgui/commit/f75ce42fbddaa133fd34e38188756fcd4678b580](https://github.com/ocornut/imgui/commit/f75ce42fbddaa133fd34e38188756fcd4678b580)
