### ISSUE TITLE
The render result is blurry (I have tried translate my project matrix)

### ISSUE THREAD

**Issue by daysofbeingwild** [ocornut/imgui#981]
This is what I got when I copy most codes in example/opengl2 into my project.
I just change the fix-function-pipeline rendering funcdtion in the example to the core profile one in my project.

-------------------------
What I did in my rendering functdion:

1. Make project matrix through GLM's `ortho` function:
`glm::ortho(0.0f, io.DisplaySize.x, io.DisplaySize.y, 0.0f, -1.0f, +1.0f);`
(I have also tried translate this matrix (0.375, 0.375) and (0.5, 0.5) )

2. Foreach vertex IMGUI provided:
  + For position, make a `vec4(position.xy, 0.f, 1.f)` and multiply this `vec4` by the projection matrix and then extract the result's xy components as vertex position. 
  + For texture coordinates, flip the texture coordinates' v component. 
  + For vertex color, convert the 32-bits integer represented vertex color provided by IMGUI to vec4, by dividing each bytes by 255.f.

3. Upload the VBO and EBO.

4. In my shader, directly set the `gl_Position` to vec4(position.xy, 0.f, 0.f) and set the output `color` as sum of Vertex color and teture color. 

Could you help me to resovle this?

**Comment by daysofbeingwild** [comment]
![qq 20170116124052](https://cloud.githubusercontent.com/assets/16398854/21971657/b06c0450-dbed-11e6-9af4-a96c32222a78.jpg)

**Comment by ocornut** [comment]
Why aren't you using the OGL3 code as a base?

Check the OGL3 shaders for reference of what to do (multiply vertex color by texel color), and check your OpenGL documentation on how to setup shaders.

I can't see any blurryness here, just the fact that texture isn't being sampled properly. If you actually have blurryness it may be because your ortho matrix doesn't match the size of your render target, or your render target doesn't match the size of your window.

**Comment by daysofbeingwild** [comment]
I change my blender mode as vertex color.rgb * texel color.rgb and vertex color.a + texel color.a(If I multipy the alpha component I will lose background!). The color is right but characters not.
After changes:
![qq 20170116124052](https://cloud.githubusercontent.com/assets/16398854/21979631/bbcfac48-dc1a-11e6-91bb-d15c004acb1e.jpg)
Example of IMGUI:
![demo](https://cloud.githubusercontent.com/assets/16398854/21979725/2c77f81a-dc1b-11e6-8808-dbb45d2bfa59.jpg)

**Comment by ocornut** [comment]
Your texture isn't properly setup/uploaded/bound/sampled, 
or, you are always sampling at (0,0) and not using the correct UV coordinates.

**Comment by daysofbeingwild** [comment]
Hi ocornut, I have resolved this.

Note:
1. No need to flip the UVs' v coordianate component.
2. In fragment shader, simply multiply vertexcolor's rgba components with texelcolor's rgba.

Hope these helps other people suffering from the same question.

**Comment by ocornut** [comment]
Good to hear!
Those answers are already pretty explicit (implicit?) in the shader used by the OpenGL3 and DirectX11 demo. I'm not sure why you didn't use those examples as a base.
