### ISSUE TITLE
How to enable non-latin character input?

### ISSUE THREAD

**Issue by Paalon** [ocornut/imgui#985]
Hello.
I am using SFML and imgui-SFML binding (https://github.com/eliasdaler/imgui-sfml).
That's a nice software, thanks.
But I have struggled to input non-latin (Japanese) character.
I have succeeded to show Japanese in ImGui:
![2017-01-19 2 22 03](https://cloud.githubusercontent.com/assets/11065457/22075146/27d05486-ddee-11e6-9ac1-3a2f9bd7532f.png)
by the code:
`
// load font
ImGuiIO& io = ImGui::GetIO();
io.Fonts->AddFontFromFileTTF("./font/mplus-1p-regular.ttf", 18.0f, NULL, io.Fonts->GetGlyphRangesJapanese());
`
How to enable non-latin character input?

**Comment by ocornut** [comment]
Characters are passed to ImGui via the io.AddInputCharacter(). Maybe SFML or the SFML wrapper are not handling non-ascii or IME type of inputs properly. Check with the maintainer of the SFML imgui wrapper.

**Comment by Paalon** [comment]
Ok, thanks. I'll try. If I succeeded, I'll report it here.

**Comment by Paalon** [comment]
SFML does not seem support IME right now. So it is difficult to use IME in imgui-SFML. I need to use other rendering wrapper (SDL, glfw) or write code myself. That's my conclusion as far as I searched.

**Comment by ocornut** [comment]
Look at the imgui DirectX examples and you may easily adapt and add IME to SFML.

**Comment by Paalon** [comment]
I don't have Windows PC so I tested `apple_example` on my Mac and succeeded to use IME. But the sample is depend on GLFW (and Cocoa API) so I'm still trying to use it with SFML.
