### ISSUE TITLE
Add Word Coloring to Multi-Line Control

### ISSUE THREAD

**Issue by aiekick** [ocornut/imgui#986]
Hello,

finally i abandon scintilla.

i just need word coloring in the text multi line control.

I hope i can have a string with information about word start, word end, and word color to pass to the multi-line control. like that maybe "start : end : color" => "10:22:#99ccff"

So before the multi-line control i imagine analyse the text and format a special string for it in the ImGuiTextEditCallback

Finally i imagine pass this buffer to a modified version of ImFont::RenderText.

Do you think i may be heavy , maybe you have another way ?

Thanks for your help

**Comment by ocornut** [comment]
Hello,
I will merge this topic with https://github.com/ocornut/imgui/issues/902

Realistically it isn't going to happen soon, but eventually we may evolve the text editor to provide some sort of text coloring facility. It's not a trivial feature and won't happen soon so don't hold your breath.

**Comment by aiekick** [comment]
ah, ok thanks :)

**Comment by ocornut** [comment]
Closing this as expected. 

Note that there is a full-featured code editor that you might want to use here:
https://github.com/BalazsJako/ImGuiColorTextEdit

**Comment by sadovsf** [comment]
Unfortunatelly linked widget has currently broken calculation of cursor position. It is off in +x axis more the longer text is on line. Basically there seems to be some issue with calculation from column to screen pos of character. I did report it to author. Maybe you may know about some change that may broke it i found for example rounding in ImGui::CalcTextSize which iam not sure about (but removing it did not help either)

**Comment by ocornut** [comment]
Hmm, the only thing I can think of is that change
https://github.com/eliasdaler/imgui/commit/3d20471559ddba7cebd4ee53eacc3dd06541375d

**Comment by sadovsf** [comment]
I tried to revert this but it did not fix the issue but when i removed rounding at the end of ImGui::CalcTextSize it started working. Problem from what i have seen is that author is using CalcTextSize on per character basis to calculate cursor position. This rounding then introduces bigger and bigger error with each character (none of them has exact size). Part from commit you mentioned he probably attempt to mitigate resulting in another error after mentioned commit.

**Comment by ocornut** [comment]
They should probably use the lower level `ImFont->CalcTextSizeA` function.

**Comment by sadovsf** [comment]
I tried that and it seem to be working well now (had to remove their parts that were fighting removed code you mentioned previously). OK, will test font scaling and give them patch :-)

Thank you for your assistance, it was really helpfull
