### ISSUE TITLE
Dynamically draw circle changing radius

### ISSUE THREAD

**Issue by djones4487169** [ocornut/imgui#988]
I'm using the code from the Custom Rendering to make dynamic circles. I'm having trouble with how to define the radius once I have set the centre point since it changes with mouse drag? I'm not really sure what to use for the radius?

draw->PushClipRect(ImVec4(canvas_pos.x, canvas_pos.y, canvas_pos.x + canvas_size.x, canvas_pos.y + canvas_size.y));
for (int i = 0; i < points.Size - 1; i += 2)
	{
		draw->AddCircle(ImVec2(canvas_pos.x + points[i].x, canvas_pos.y + points[i].y), canvas_pos.x + points[i].x, ImColor(255, 0, 0), 1.0f);
	}
draw->PopClipRect();
if (adding_preview) points.pop_back();

**Comment by ocornut** [comment]
This isn't a dear imgui question (and the subject is misleading). Please refrain from abusing this github with requests when you haven't worked through the problem seriously yourself. From now on I will only take your questions will pastable reproduction code + screenshot + correct subject line and clear explanation or what you are trying to achieve.

**Comment by ocornut** [comment]
As a rule of thumb please spend a day on a problem before asking here (that day should show up in your question in the form of concrete explanations and data). It is being clear from the nature of your questions that you are learning c++ and programming, and while it is a amazing thing to do, this place isn't a place for me to solve your programming issues. There are numerous places to discuss programming, graphic programming, C++. Doing it here is harming imgui and stealing time away from actual imgui improvements. Please be considerate.
