### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by jztflokzz** [ocornut/imgui#990]
How do i do it?

**Comment by ocornut** [comment]
I have no idea what you are talking about. Transparency can means a hundred things.

Please be more clear and explain in lengthy and clear details what you would like to do, the context etc. This is the minimum amount of respect expected if you wish to obtain an answer.

**Comment by jztflokzz** [comment]
I mean the transparency on the window

**Comment by ocornut** [comment]
Closing this until you can make full sentences.
Please run the example code, read the docs and comments on ImGuiStyle and ImGui::Begin().
Regards.

**Comment by jztflokzz** [comment]
Where is the docs?
