### ISSUE TITLE
How to attach multiple windows/make tabs (example)

### ISSUE THREAD

**Issue by jztflokzz** [ocornut/imgui#991]
How would i attach multiple windows in 1 tab or make a tab 
like in this example (as you can see on the top, it's different tabs like VISUALS AIMBOT ANTIAIM TARGETLIST etc):
![image](https://cloud.githubusercontent.com/assets/12187072/22184536/f24ef8b0-e0d3-11e6-9feb-4d187e80d8cb.png)

**Comment by ocornut** [comment]
Use buttons. Pressing a button will change your current tab index. Display the data you want according to the tab index.
