### ISSUE TITLE
Issue opening Menus when moving in diagonal with two adjacent menus

### ISSUE THREAD

**Issue by codz01** [ocornut/imgui#994]
the problem is if you drag the cursor diagonally from for example (options) to (colors) , the colors sub menu won't opened .
![imgui_menu](https://cloud.githubusercontent.com/assets/10813427/22243677/a483b8f4-e228-11e6-8c34-edf9d0b10176.gif)

**Comment by ocornut** [comment]
The code in `BeginMenu` is intentionally implementing something based on 
  http://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown
To avoid using timers so menus appears immediately.

It works well and pretty much necessary when moving fast to actually access the "Options" menu in this example, but I admit having had occasional false negative. Perhaps it should settle on current item if the user has stopped moving?

**Comment by ocornut** [comment]
Closing as non-issue.
