### ISSUE TITLE
WindowDrawList order off *sometimes*

### ISSUE THREAD

**Issue by avaskoog** [ocornut/imgui#998]
Hello again!

I stumbled across a rendering issue where these green little things rendered by manually adding filled shapes to the window's draw list appear below _some_ things but not others (they're drawn last and are intended/supposed to go on top of everything else inside the box):

![skarmavbild 2017-01-28 kl 20 16 03](https://cloud.githubusercontent.com/assets/25255407/22399158/5df78114-e597-11e6-890a-82b86f2bbb1a.png)

---

At first it seemed reminiscent of this one: https://github.com/ocornut/imgui/issues/811

But that seems not to be it. I have tried all manners of variations on pushing clip rects and no luck. There's also the fact that it's only an issue with the `ImGui::Image` and not with the `ImGui::Button`s, as you can see.

The calls to add to the draw list and the calls to draw the buttons or the image are all carried out sequentially inside of a `BeginChild()` and `EndChild()` pair. The calls to add to the draw list are performed last. With or without pushing a clip rect first makes no difference, no matter the parameters. I've tried reördering everything too just in case, but no combination works.

So is there an issue when `ImGui::Image`s are involved? Is this at all related to the issue I linked at the top? Am I simply doing something wrong?

Simplified version of the code:

> if (ImGui::BeginChild(...))
> {
> 	ImGui::Button/Image(...);
>	...
> 
> 	// Optional PushClipRect() here.
> 
> 	auto dl(ImGui::GetWindowDrawList());
> 	dl->AddRectFilled(...);
> 	dl->AddTriangleFilled(...);
> 	...
> 
> 	// Optional PopClipRect() here.
> }
> ImGui::EndChild();

---

Now, I personally bypassed this by resetting the cursor and then drawing another child on top of everything, which also allowed me to add a semitransparent overlay on top of everything which I wanted anyway, so this problem won't affect me this time, but if it is indeed a bug it might come back to bite someone else (even me!) in the future, and if it isn't a bug at all, it'd at least be nice to have an explanation. c:

![skarmavbild 2017-01-28 kl 20 36 51](https://cloud.githubusercontent.com/assets/25255407/22399281/b9a05688-e599-11e6-834b-26c261b7b6cd.png)

> if (ImGui::BeginChild(...))
> {
> 	const auto cursor(ImGui::GetCursorPos());
> 
> 	ImGui::Button/Image(...);
> 	...
> 
> 	ImGui::SetCursorPos(cursor);
> 	if (ImGui::BeginChild(...))
> 	{
> 		auto dl(ImGui::GetWindowDrawList());
> 		dl->AddRectFilled(...);
> 		dl->AddTriangleFilled(...);
> 		...
> 	}
> 	ImGui::EndChild();
> }
> ImGui::EndChild();

👍

**Comment by ocornut** [comment]
> also the fact that it's only an issue with the ImGui::Image and not with the ImGui::Buttons, as you can see.

That's odd. The only thing that Image should do is to push a different ImTextureId which will create a new ImDrawCmd to be processed by your rendering. 

Perhaps your renderer is involved somehow (how do you handle textures changes? does any of the rendering affects z-writing z-depth or something unexpected). Is that viewport just a Image() and not an image within a child?

Child windows are always drawn after their parent.

There's a possibility that certain specific use cases lead to be bug in ImDrawList command splitting/merging, it happened in the past. You should probably first look at the Metrics windows to interactively inspect all the draw commands/vertices/clipping and understand what is going on.

**Comment by avaskoog** [comment]
> Is that viewport just a Image() and not an image within a child?

... Oh, wow. It was inside a child, actually. I didn't think it was. I tried removing the child and reverted my draw list code not to draw in a child, and indeed, that fixed it:

![skarmavbild 2017-01-28 kl 21 23 31](https://cloud.githubusercontent.com/assets/25255407/22399594/167e4ec2-e5a0-11e6-8e36-065f1db2f4f1.png)

Sorry. q__q Feel free to remove this unless you feel it can be useful to someone else in the future.

**Comment by ocornut** [comment]
Closing this, may show up in searches (there has been other issues related to sorting before, such as #595).

Each window is appendable - you can call `Begin` multiple times which has various uses (appending/drawing to a same child or regular window from different spot)., so at the end of the frame we compute the final z-order and render that. If you understand that child are their own windows and that same thing is used for the ordering of regular windows as you bring them to front/back (the ordering is dissociated from the order your code submits them) it should makes some sense.

I feel that making the metrics windows a little more prominent would also help clearing that sort of confusion. Seeing things as they happens is usually better than reading stray comments. Maybe Metrics should be more prominent in the examples app.
